### ISSUE TITLE
Support awaiting promises which are passed in the expect() function

### ISSUE THREAD

**Issue by romanresh** [DevExpress/testcafe#1012]
### What is the current behavior?
If I pass the promise (async function) to the expect() method, then this promise is not executed, but it's compared with parameter passed to eql(). So, I get this error: "AssertionError: expected {} to deeply equal 'Last Name'".

### What is the expected behavior?
The expect() function should execute the promise and compare result of execution.

```js
await t.expect(getHeaderText(1)).eql("Last Name");
async getHeaderText(column) {
  const header = await findHeaderByIndex(column);
  return header.innerText;
}
```
Inside `findHeaderByIndex` I execute ClientFunction and process its results. So, I cannot remove the `async` keyword from the getHeaderText() function.

**Comment by inikulin** [comment]
@romanresh If I get it right you can simply workaround it by using:
```js

await t.expect(await getHeaderText(1)).eql("Last Name");
```

**Comment by romanresh** [comment]
Yes, I do. And I had to use this workaround. But the built-in testcafe assert functions make comparisons a few times inside timeout. They make a few requests to a browser and check results (make assertion).

But `await getHeaderText(1)` will make request only once. Moreover, it will get innerText from the selector immediately. So, `await` before `t.expect``won't make sense because the expect parameter will be calculated before expect() call.

**Comment by romanresh** [comment]
I mean 
```js
console.log(await getHeaderText(1)) // "text"
```

**Comment by romanresh** [comment]
Closed because of this solution: https://github.com/DevExpress/testcafe/issues/1025
