### ISSUE TITLE
Incorrect window resizing after t.maximizeWindow

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#1016]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
A browser window is not resized to the specified size.

### What is the expected behavior?
A browser window is resized to the specified size.

### How would you reproduce the current behavior (if this is a bug)?
Use t.resizeWindow or t.resizeWindowToFitDevice after using t.maximizeWindow

### Specify your

* operating system: Windows
* testcafe version: 0.11.0-alpha2
* node.js version: 6.5.0

**Comment by miherlosev** [comment]
The problem is not reproduced with `testcafe@1.10.1`.

```js
fixture `Fixture`;

test('test', async t => {
	await t
	   .maximizeWindow()
	   .resizeWindow(500, 500);
});
```
