### ISSUE TITLE
Attribute Selector like jQuery `custom-tag[data-custom-foo=bar]`

### ISSUE THREAD

**Issue by jgraup** [DevExpress/testcafe#1017]
### Are you requesting a feature or reporting a bug?

Either. I may just be using this incorrectly but being new to this lib I don't see any relevant examples except for [this one](https://github.com/DevExpress/testcafe/blob/master/examples/basic/test.js#L24) -- but it's unclear how to use it without the `.click(page.macOSRadioButton)`.

### What is the current behavior?

When I try to query a custom tag with an attribute selector it currently throws an error.

```js
var button = await t. select(() => document.querySelector('custom-tag[data-custom-foo=bar]'));
```
> SyntaxError: Failed to execute 'querySelector' on 'Document': 'custom-tag[data-custom-foo=bar]' is not a valid selector.

### What is the expected behavior?

I want to wait for the page to finish loading and AngularJS to execute some state changes on elements based on a query param.

At that point, I want to query an element and make sure it's class matches a desired state. I expect to be able to query tags using an attribute selector because that will be the only item with a class modification. I also expect it to behave like jQuery selectors in some respects:

```js
jQuery('custom-tag[data-custom-foo=bar]')
```

### How would you reproduce the current behavior (if this is a bug)?

Create any element with an attribute and try to query that element+attribute.

#### Provide the test code and the tested page URL (if applicable)

Test code

```html
<custom-tag data-custom-foo="bar" class="toggled">
  Some Text
</custom-tag>
```
```js
import { expect } from 'chai';
import { Selector } from 'testcafe';

var button = await t. select(() => document.querySelector('custom-tag[data-custom-foo=bar]'));

expect(button).to.not.be.null;
```

### Specify your

* operating system: Mac OS X 10.11.6
* testcafe version: 0.10.0
* node.js version: v4.4.5

**Comment by inikulin** [comment]
Hi @jgraup,

I've tried to reproduce the problem on my side but failed, I've used the following test code:
```js
fixture `test`.page('http://google.com');

test('test', async t=> {
    var button = await t.select(() => document.querySelector('custom-tag[data-custom-foo=bar]'));

   expect(button).to.be.null;
});
```

Test passed without selector error in Chrome. Can you clarify which browser you are using, please?

Also, note that you can just pass a selector string to `Selector` or `t.select` and it will be a shorthand for `document.querySelector`: 
```js
ar button = await t.select('custom-tag[data-custom-foo=bar]');
```

**Comment by jgraup** [comment]
Thans @inikulin, 

I apologize. The example I gave changed some variables but maybe that was a good thing. I tried the above code and it worked like it worked for you. I went back to my test and I was using int numbers instead. This does appear to be working but only if the number is in quotes.

```js
console.log('THIS IS OK');
var button = await t.select(() => document.querySelector('custom-tag[data-custom-foo="1234"]'));
```
  
```js
console.log('WILL FAIL');
var button = await t.select(() => document.querySelector('custom-tag[data-custom-foo=1234]'));
```

So this issue is possibly misleading. In summary; a string value is OK while a number value without quotes failed for me.

**Comment by inikulin** [comment]
This is a by design behavior of CSS selectors. According to the [spec](https://www.w3.org/TR/css3-selectors/#attribute-selectors):

> Attribute values must be CSS identifiers or strings. [CSS21] The case-sensitivity of attribute names and values in selectors depends on the document language.

So, if value in selector is not enclosed in quotes it's treated as `indentifier` and according to the spec:

> In CSS, identifiers (including element names, classes, and IDs in selectors) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); **they cannot start with a digit, two hyphens**...

**Comment by jgraup** [comment]
@inikulin - Thanks! That's good to know. I would consider this not an issue at this point. jQuery might be a little more relaxed in it's rules but good to stick to the spec.
