### ISSUE TITLE
`--app-command` option

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#1047]
### Are you requesting a feature or reporting a bug?

feature

### What is the current behavior?

There is no way to run tested server app and terminate it once tests finish.

### What is the expected behavior?

Provide `--app-command` option which will allow to start test server and automatically terminate it, once testing is finished, e.g.:
```sh
testcafe chrome --app-command "node server.js" tests/
```

**Comment by inikulin** [comment]
Use (concurrently)[https://www.npmjs.com/package/concurrently] module instead.

**Comment by inikulin** [comment]
@AlexanderMoskovkin We need a recipe for this one and modify existing recipies as well

**Comment by inikulin** [comment]
I guess I'd like to revisit it. `concurrency` is to verbose and you need to add it to every recipe. Built-in functionality would be nice.

**Comment by VasilyStrelyaev** [comment]
Will do the docs
