### ISSUE TITLE
Is it possible to query shadow dom of Angular?

### ISSUE THREAD

**Issue by gowram** [DevExpress/testcafe#1053]
I am not sure how to use Selector for querying shadow dom,  where as i have  working query in console as follows...

```js
ct = document.querySelector('#sbPageContainer').shadowRoot.querySelector("#content < sb-line-editor").children[0]

ct.shadowRoot.querySelector("#lineEditorPageHeader").querySelector("#actions").children[0].shadowRoot.querySelector("#mainButton")
```
i tried same query using testcafe as ....

```js
Selector('#sbPageContainer').shadowRoot.find('#content').nth(0).shadowRoot.find('#lineEditorPageHeader').find('#actions').nth(0).shadowRoot.find('#mainButton')
```
please let me know how to get it right.

### Specify your

* operating system: Window 8.1
* testcafe version:0.11
* node.js version: 6.9.1

**Comment by AndreyBelym** [comment]
Hello, @gowram! Currently you can't use `Selector` for querying `shadowRoot` in that manner. Instead, try to use `Selector` with a function, that returns the desired element, e.g.
```js
Selector(() => {
    ct = document.querySelector('#sbPageContainer').shadowRoot.querySelector("#content < sb-line-editor").children[0];

    ct.shadowRoot.querySelector("#lineEditorPageHeader").querySelector("#actions").children[0].shadowRoot.querySelector("#mainButton")
})
```

**Comment by gowram** [comment]
I tried this way, but it queried till   
```js
document.querySelector('#sbPageContainer')
```
rest got skipped, no error message as well.
i think "shadowRoot" failed to get element, is there any workaround?

**Comment by AndreyBelym** [comment]
Can you provide me the link to your page and/or the test code? I tried a page with Shadow DOM, it have worked fine for me.

**Comment by gowram** [comment]
@AndreyBelym 

It's pointing to the element successfully but click event is not happening, even i tried with wait(50000).

I have angular page which is part of Salesforce org, that's the reason I won't be able share with you?

```js
document.querySelector('#sbPageContainer').shadowRoot.querySelector("#content").children[0].shadowRoot.querySelector("#lineEditorPageHeader").querySelector("#actions").children[0].shadowRoot.querySelectorAll("paper-button#mainButton")[0]
```
the flow was perfect except the click, if possible can we have a call?

**Comment by varunkumar** [comment]
@gowram Were you able to get this working? If so, what is the fix. Please re-open if the issue still exists. Linking my issue here -- https://github.com/DevExpress/testcafe/issues/1312
