### ISSUE TITLE
Allow to run browser by shell script

### ISSUE THREAD

**Issue by IhostVlad** [DevExpress/testcafe#1055]
The current implementation most likely doesn't allow to realize start of the target browser in which it will be executed the functional tests, by means of arbitrary shell-script.

It can be used if it is necessary to launch testcafe in docker container which in the normal mode chrome doesn't allow to launch or chromium normally - instead is required a set of arguments of command line.

Preliminary start of the browser in that case too doesn't help - if there is a chrome or chromium window which is already opened in a preliminary way, then testcafe can't find it.

The possibility of start of the browser arbitrary shell script to which the url-address for transition is transferred could be the convenient decision in that case.

Now it is passed to be done by means of a manual call of testcafe in the remote-mode, the program analysis of a console output, and start of the browser with target arguments - that is quite inconvenient.

Also there is one more problem - if chrome or chromium are only set in system, then the modal window with a question of installation of the browser by default opens. Unfortunately, testcafe isn't able to define and close this window that it is also difficult in inconveniently with the above restrictions.

Now this issue has workaround with following code:
```js
function runTestcafeTest(name) {
    const testFullPath = path.join(__dirname, `./${name}.test.js`);
    return new Promise((resolve, reject) => {
        testcafeProc = spawn(testcafeCommand, ['remote', testFullPath]);
        let testcafeDone = false;
        const handleOutFunc = (data) => {
            const outLine = data.toString('utf8');
            log('[TestCafe]: ', outLine);

            const match = outLine.match(/(http:\/\/(?:.*?))(?:\r\n|\n|$)/i);
            if(browserProc || !(match && match[1])) return;

            browserProc = execFile(
                browserBaseName, 
                browserBaseArgs.concat(match[1]),
                (err) => {
                    if(testcafeDone) return;
                    log(`Browser ${browserBaseName} can't be inited with arguments:`);
                    log(browserBaseArgs.concat(match[1]));
                    reject(2);
                }
            );
        };

        testcafeProc.stdout.on('data', handleOutFunc);
        testcafeProc.stderr.on('data', handleOutFunc);

        testcafeProc.on('exit', (code) => {
            testcafeDone = true;
            browserProc ? treeKill(browserProc.pid) : null;
            browserProc = null;
            if(code !== 0) {
                return reject(code);
            }
            return resolve();
        });
    })
}
```

But ideal solution is using `testcafe ./runbrowser.sh /testsuite` with file `runbrowser.sh` like this:
```
#!/bin/bash
/usr/bin/magic-preparation-utility
/usr/bin/browser-binary --magic-flag-1 --magic-flag-2  $1
```

**Comment by AndreyBelym** [comment]
Hello @IhostVlad!

Actually, you can start a browser with a shell script, e.g. check a discussion here: https://testcafe-discuss.devexpress.com/t/launching-browser-in-virtual-x-mode/76/3

through
```
testcafe path:/path/to/runbrowser.sh /testsuite
```

and the test url will be the second argument of the script
```
#!/bin/bash
/usr/bin/magic-preparation-utility
/usr/bin/browser-binary --magic-flag-1 --magic-flag-2  $2
```

Also, since `testcafe@0.11.0` you can use CLI to pass browser arguments, e.g.
```
testcafe "chrome --flag1 --flag2" test
testcafe "path:/usr/bin/browser-bin --flag1 --flag2" test
```
About first run modal dialog: have you tried `testcafe@0.11.1`? We have improved launching of fresh-installed browsers in this version, so, please try it, and if it will not help you, please specify your OS and Chrome versions.
