### ISSUE TITLE
Click action misses an element if its hidden under fixed element

### ISSUE THREAD

**Issue by romanresh** [DevExpress/testcafe#1057]
### Are you requesting a feature or reporting a bug?
bug

### What is the current behavior?
See: https://getbootstrap.com/examples/navbar-fixed-top/. If before click on the "View navbar docs" hyperlink scroll was at the bottom side of the page when testcafe scrolls page to the hyperlink but it leaves hidden under the top navbar and the hyperlink remains unavailable for click.

### What is the expected behavior?
TestCafe should check visibility of clicking element and scroll page to make it visible for click.

### How would you reproduce the current behavior (if this is a bug)?
1. Scroll page to bottom
2. ```await t.click(".btn")```

Tested page URL:
https://getbootstrap.com/examples/navbar-fixed-top/

**Comment by AlexanderMoskovkin** [comment]
We've not handled a case when a target element is hidden under other element that has a parent with `style="fixed"`
/cc @AndreyBelym

**Comment by Li34** [comment]
hi！
Is this problem solved?

**Comment by AlexanderMoskovkin** [comment]
Hi @Li34,

We've fixed it for a case when an overlapping element has `style="fixed"`. But the problem still occurs when an overlapping element is not `fixed` but it has a parent with `style="fixed"`. Meanwhile usually it's easy to find a workaround for this case.
Have you faced with this issue in your tests? If yes could you please provide an url to your page or create a simple example to reproduce the problem. With it we can help to find a way how to resolve the issue.

**Comment by RemeJuan** [comment]
I think this may be related. We have a container which is fixed and are unable to find the child within it that is also fixed, while I can find the non-fixed elements.

parent (fixed)
  --child (NOT fixed)
  --child (NOT fixed)
  --child (NOT fixed)
  --child (fixed)

**Comment by AlexanderMoskovkin** [comment]
Hi @RemeJuan,

Could you please create a simple example markup to demonstrate this (on https://jsfiddle.net/ for example)
