### ISSUE TITLE
Wrong error message if file does not contain 'fixture' definition

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#1058]
File contains only test definition
```
test('t', async t => {});
```

I peform the command `testcafe chrome index.js`.

After I get the error:
`ERROR No tests to run. Either the test files contain no tests or the filter func
tion is too restrictive.`

It is a bug because I cannot find problem using error message.

* testcafe version: 0.12.0-alpha

**Comment by inikulin** [comment]
It's by design. TestCafe recognizes test files by `fixture` and `test` definitions, otherwise they considered a regular js file.
