### ISSUE TITLE
Tescafe exclude wrong test files from execution

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#1059]
I have 3 test files:

### index.js
```
fixture `index`;

test('t', async t => {});
```

### index1.js
```
123
```

### index3.js
```
fixture `index3`;
test('t', async t => {});
```

So, `index1.js` test file formats wrongly.
I perform the command `testcafe chrome index*.js`
After I get the report:
```
Running tests in:
- Chrome 55.0.2883 / Windows 8.1 0.0.0
index
v t
index3
v t
```

Testcafe hides wrongly formtted `index1.js` file from execution.
I expect that testcafe shows error message about wrongly formatted file.

* testcafe version: 0.12.0-alpha

**Comment by inikulin** [comment]
I don't get it. index1 doesn't contain any tests, why it should be executed?

**Comment by inikulin** [comment]
We need to filter out TestCafe test files somehow, because you can specify e.g. `tests/*.*.js` as a source. We treat file a TestCafe fixture if it contains `fixture` declaration and at least single `test`

**Comment by AlexanderMoskovkin** [comment]
Also you can keep your page model files in the same directory with tests:
```
tests/
-- page-models/
---- page.js
-- test1.js
-- test2.js
```

It should not raise a error like `the page.js file doesn't contain tests` if you specify tests to run as `tests/*.*.js`.
