### ISSUE TITLE
Show error message then use assertion without method

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#1063]
When I run test file as

```
fixture `fixture`;

test('', async t => {
    await t.expect();
});
```
I get a green report.

Assertion inside test looks like a mistake - one forgot to write an assertion method.
For this case I want to see an error message.

* testcafe version: 0.12.0-alpha

**Comment by miherlosev** [comment]
https://github.com/DevExpress/testcafe/issues/2567#issuecomment-401779617

**Comment by ymor** [comment]
I came across this issue recently when i had chained expect/asserts, however one of the expects was missing an assert.  This made the whole test pass even though the first expect + assert should have failed.

Example:
```
import { Selector } from 'testcafe'; // first import testcafe selectors

fixture `Getting Started`// declare the fixture
    .page `https://devexpress.github.io/testcafe/example`;  // specify the start page

//then create a test and place your code there
test('My first test', async t => {

    const header = await Selector('header h1');
    const input = await Selector('#developer-name');

    await t
        .expect(header.textContent).eql('derp') //Should fail
        .expect(input.textContent);
}); 
```

**Comment by bxt** [comment]
Since this adds a `then` method, the "first half" of an assertion is now regarded a Promise by JS and you can no longer return it from an async method. I.e. this code:

```js
  async expectFooDisabled() {
    return this.t.expect(
      Selector('button')
        .withText(await getText('FOO'))
        .getAttribute('disabled')
    );
  }
  async expectFooDisabledTrue() {
    return (await this.expectFooDisabled()).eql('true');
  }
```

Will now cause the error "An assertion method is not specified.".

The workaround is to do the whole assertion in the function:

```js
  async expectFooDisabledIsEqualTo(value) {
    return this.t.expect(
      Selector('button')
        .withText(await getText('FOO'))
        .getAttribute('disabled')
    ).eql(value);
  }
  async expectFooDisabledTrue() {
    return this.expectFooDisabledIsEqualTo('true');
  }
```
