### ISSUE TITLE
select标签测试不见了。

### ISSUE THREAD

**Issue by jinzw1993** [DevExpress/testcafe#1064]
hover 不能正确选择select标签的子项目。

希望获得教程

code：

import { Selector } from 'testcafe';

fixture `Getting Started`
    .page `http://www.560417.com/User/Register`;
       const fdg=Selector('#FirstID');
test('My first test', async t => {

    await t
        // .click('#FirstID')
        .hover(fdg)
        //   .click('#FirstID')
          .expect(fdg.value)
          .eql('1')
          .typeText('#userName',"dsafdssdfajkhfdskjhfsdkhjfdshjkfdhjkkhf")
          ;
    
});

```

### Specify your

* operating system:ubuntu14.04 chrome
* testcafe version:0.11.1
* node.js version:6.9.2

**Comment by AlexanderMoskovkin** [comment]
Hi @jinzw1993 ,

I see you want to select the `北京市` option in the `<select>` element. Call two clicks to do this: on for the `<select>` element and on for the `<option>` element. Here is modified test that works on my side:

```js
import { Selector } from 'testcafe';

fixture `Getting Started`
    .page `http://www.560417.com/User/Register`;

const fdg = Selector('#FirstID');

test('My first test', async t => {
await t
      // click the <select> element to expand it
      .click(fdg)
      
      // select the option by its text
      .click(fdg.find('option').withText('北京市'))
      
      // or by its index
      //.click(fdg.find('option').nth(1))
      
      .expect(fdg.value).eql('1')
      .typeText('#userName',"dsafdssdfajkhfdskjhfsdkhjfdshjkfdhjkkhf");
});
```

Also I see there is an js-error on your page. So, to run this test with the [`skip-js-errors`](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors) option:
```bash
testcafe chrome test.js -e
```
