### ISSUE TITLE
Add the 'origin' parameter to callback function of find(), child(), parent() methods

### ISSUE THREAD

**Issue by romanresh** [DevExpress/testcafe#1065]
### Are you requesting a feature or reporting a bug?
feature

### What is the current behavior?
It's impossible to get properties of parent element inside callback function of the find(), child(), parent() methods. 

### What is the expected behavior?
```js
var mainElement = Selector("#main-element-id");
var childByIdPostfix = mainElement.find((node, index, origin) => node.id === origin.id + "_idpostfix");
```

**Comment by VasilyStrelyaev** [comment]
Will do the docs
