### ISSUE TITLE
Wrong command line for 'Test Static Html Pages' recipe

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#1074]
Origin
`concurrently -r -k "http-server" "http-server ./dist -p 4000 -s" "testcafe chrome ./test/acceptance/**"`

should be
`concurrently -s first -r -k "http-server ./dist -p 4000 -s" "testcafe chrome ./test/acceptance/**"`
because
- `-k` parameter doesn't have arguments
- `-s first` - we should return `testcafe ` exit code as a result and `testcafe` completed the first

Also, we can simplify command line and drop `-p` parameter  - in this case default port will be used.

**Comment by inikulin** [comment]
Not relevant anymore
