### ISSUE TITLE
Firefox doesn't work with Debian

### ISSUE THREAD

**Issue by marchugon** [DevExpress/testcafe#1076]
### Are you requesting a feature or reporting a bug?
bug

### What is the current behavior?
If I launch a test with firefox, the browser shows up, but nothing more happens. Testcafe waits something like one minute and fails with this message : 

> ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.

My Firefox version is 43.0

### What is the expected behavior?
Firefox should connect to nodejs instance in order to launch the test. I had no problem with testcafe v0.10

### How would you reproduce the current behavior (if this is a bug)?
It fails every tyime

#### Provide the test code and the tested page URL (if applicable)
Tested with test.js example from testcafe

### Specify your

* operating system: Debian GNU/Linux 8 (jessie) 64 bits
* testcafe version: 0.11.1
* node.js version: 6.9.2

**Comment by AlexanderMoskovkin** [comment]
Hi @marchugon,

Thanks for you report. It seems we've fixed this problem already, but it's not published yet. We'll publish the version with the fix soon, I'll notify you.

**Comment by AlexanderMoskovkin** [comment]
@marchugon, please check the both problems (#1075, #1076) on the new `alpha` version. To install it run
```bash
npm install [-g] testcafe@alpha
```

Please notify me does it work now?

**Comment by marchugon** [comment]
Ok for me, it worked with v0.12.0-alpha1
