### ISSUE TITLE
Contribute 'testcafe' enviroment to the eslint

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#1083]
http://eslint.org/docs/user-guide/configuring#specifying-environments

testcafe will add `test` and `fixture` globals.

**Comment by miherlosev** [comment]
I'm working on this

**Comment by inikulin** [comment]
@miherlosev Why it's done as a plugin not by contributing env directly to eslint: http://eslint.org/docs/user-guide/configuring#specifying-environments

**Comment by miherlosev** [comment]
Unfortunately, we cannot contribute `testcafe` environment directly to eslint.
All build-in environments from eslint are placed in [globals](https://www.npmjs.com/package/globals)
Phrase from description:
This module no longer accepts new environments. If you need it for ESLint, just create a plugin.

However, we can contribute `testcafe` environment to modules that agregate eslint rules and plugins - [xo](https://www.npmjs.com/package/xo)

**Comment by inikulin** [comment]
Got it, thanks for explanation

**Comment by miherlosev** [comment]
https://www.npmjs.com/package/eslint-plugin-testcafe

**Comment by inikulin** [comment]
@miherlosev We need to add it somewhere to the docs

**Comment by AlexanderMoskovkin** [comment]
https://github.com/DevExpress/testcafe/issues/1098
