### ISSUE TITLE
Add a flag to retrieve the available browsers

### ISSUE THREAD

**Issue by churkin** [DevExpress/testcafe#1096]
### Are you requesting a feature or reporting a bug?
feature

testcafe --browser-list

I think it will be useful for CI and for IDE extensions.

**Comment by AlexanderMoskovkin** [comment]
Great proposal!
And .... we have this already 😃😃 : 
[testcafe --list-browsers](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-b---list-browsers)
