### ISSUE TITLE
Http errors after empty test execution

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#1097]
Then I run an empty test
```
fixture `fixture`;
test('test', => {
});
```

I get two http errors in browser Network tab:
- 404 `/favicon.png` (referrer - `http://172.22.7.216:50599/browser/idle/B1Dl9KRNe`)
- 404 `/browser/init-script/B1Dl9KRNe` (referrer - `http://172.22.7.216:50599/browser/idle/B1Dl9KRNe`)

Initially, I found these errors in browser Network tab.
To capture this I used the Fiddler tool.

I think we should fix these errors.

* testcafe version: 0.12.0-apha2

**Comment by inikulin** [comment]
Can be accomplished with https://github.com/DevExpress/testcafe/issues/1270
