### ISSUE TITLE
Fix QUnit tests in MS Edge browser

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#110]
One test hangs because of the `testcafe-hammerhead` bug ([see on saucelabs](https://saucelabs.com/tests/6413e77d6b50426785f0340275228622))
@helen-dikareva please, create an issue for the `testcafe-hammerhead` with the problem description

**Comment by helen-dikareva** [comment]
I'm working on this

**Comment by helen-dikareva** [comment]
Closed by https://github.com/DevExpress/testcafe/pull/187
