### ISSUE TITLE
navigateTo() returns error

### ISSUE THREAD

**Issue by solsenfinovertech** [DevExpress/testcafe#1101]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

`.navigateTo()` always returns an `Uncaught SyntaxError: Unexpected identifier`

### What is the expected behavior?

`.navigateTo()` should navigate to the specified web page.

### How would you reproduce the current behavior (if this is a bug)?

Pretty straightforward, any test (a relative or absolute URL path) and then `wait()`.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js
await t
        .navigateTo('https://google.ca/')
        .wait(1000)
```

### Specify your

* operating system: Windows 10
* testcafe version: 0.11.1
* node.js version: 6.9.1

**Comment by AlexanderMoskovkin** [comment]
Hi Steven,

I've tried to run the following test in chrome, firefox and ie:
```js
fixture `Example`
    .page `http://github.com`;

test('Check navigateTo', async t => {
    await t
        .navigateTo('https://google.ca/')
        .wait(1000)
});
```

It works properly on my side:
![2016-12-28_1204](https://cloud.githubusercontent.com/assets/12047804/21518204/cd04cba8-ccf5-11e6-8226-0377441caa46.png)

Could you please provide the whole test to reproduce the problem.
If you run the test in chrome try to check it in the `incognito` mode to disable all extensions:
`testcafe "chrome --incognito" test.js`

**Comment by solsenfinovertech** [comment]
Hi,

Yes you are correct, this test also "passes" (doesn't fail) for me:
```
fixture `Example page test navigateTo`
    .page `http://www.yahoo.com/`;

const pauseMs = 1000;

test('Emulate simple navigateTo', async t => {
    await t
        .setNativeDialogHandler(() => true)
        .navigateTo('/foo')
        .wait(pauseMs)
});
```

However, this test does not "pass", gives an error "Uncaught SyntaxError: Unexpected identifier":
```
import {
    Selector
} from 'testcafe';

fixture `Example page`
    .page `http://www.example.com/`;

const pauseMs = 10000;

test('Emulate user actions and perform a verification', async t => {
    await t
        .setNativeDialogHandler(() => true)
        .hover('#username')
        .typeText('#username', 'user1')
        .wait(500)
        .hover('#password')
        .typeText('#password', 'pwd')
        .wait(500)
        .hover('#signBtn')
        .click('#signBtn')
        .wait(pauseMs * 2)

     // <snip> a little logic here, of no consequence

    await t
        .navigateTo('/foo')
        .wait(pauseMs) // ERROR: Uncaught SyntaxError: Unexpected identifier
});
```

Apparently my syntax is just incorrect somewhere?

**Comment by AlexanderMoskovkin** [comment]
Actual documentation for the open-source TestCafe version is here: https://devexpress.github.io/testcafe/documentation/getting-started/

You can find how to ignore js-errors on the page in the [Command Line Interface](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors) article

**Comment by solsenfinovertech** [comment]
It seems that `testcafe -e ...` arg does the trick. I think this ticket can be closed!
