### ISSUE TITLE
Node.js

### ISSUE THREAD

**Issue by brettz9** [DevExpress/testcafe#1111]
### Are you requesting a feature or reporting a bug?

Feature

### What is the expected behavior?

I'd like One Test Framework To Rule Them All, i.e., a framework I can use without modification in Node.js as well as the browser.

While your design goals may be focused on the browser, I'd think that even if you weren't interested in Node testing, your success may also hinge on it meeting a broader range of needs, especially given the number of projects which work in either environment.

Even the page loading and selector features could be implemented in Node (e.g., through [`jsdom`](https://github.com/tmpvar/jsdom)).

Is this something you might consider if it is not already possible?

Thanks!

**Comment by WillemMali** [comment]
You could use MochaJS this way? It has e.g. a Selenium Webdriver plugin which you can use to run your tests in real browsers.

I think the focus of TestCafe is explicitly "browser testing", and should not expand to "all testing ever".
