### ISSUE TITLE
Wrong script in documentation (Test Static Html Pages recipe)

### ISSUE THREAD

**Issue by pilyugin** [DevExpress/testcafe#1122]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
There are some mistakes in recipe ([Test Static Html Pages](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html)) which says to run this script:
```
"scripts": {
    "test": "concurrently -r -k \"http-server\" \"http-server ./dist -p 4000 -s\" \"testcafe chrome ./test/acceptance/**\""
}
```
But it does not work properly.

**1. `http-server` will be run with default settings**
This document ([Test Static Html Pages recipe](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html)) says:
> This script contains the following commands.
> 1. concurrently -r -k "http-server" - starts concurrently with the raw output flag on and kills the http-server after running the tests

But in [concurrently documentation](https://www.npmjs.com/package/concurrently) `-k` (`--kill-others`) option has not any arguments. So `"http-server\"` will be interpreted as command to run and will be started with default options (path, port and etc). Next command (`http-server ./dist -p 4000 -s`) with custom options will be ignored.

**2. This `test` script will always exit with error (exit code 1) whatever the `testcafe` result** 
because by default `concurrently` process will return 0 exit code if all child processes succeed (see `-s`, `--success` option in [concurrently documentation](https://www.npmjs.com/package/concurrently)). But when `http-server` will be killed it will return error (exit code 1). So `test` script will be failed.
It can be fixed by using `--success first` option in this script.

**This corrected script works for me:**
```
"test": "concurrently -r -k -s first \"http-server ./dist -p 4000 -s\" \"testcafe chrome ./test/acceptance/**\""
```

I have also found **another version of this recipe** in this repository ([docs/articles/documentation/recipes/test-static-html-pages.md](https://github.com/DevExpress/testcafe/blob/master/docs/articles/documentation/recipes/test-static-html-pages.md)) which suggests another solution:
```
"test": "testcafe chrome ./test/acceptance/** --app \"http-server ./dist -s\""
```
But in does not work for me. It is seems like `--app` option is ignored. 

### What is the expected behavior?
Provided script should run `http-server` with passed path and options (port and etc) and exit returning exit code of `testcafe` process.

### How would you reproduce the current behavior (if this is a bug)?
run `npm test` command with provided script.

### Specify your

* operating system: Windows 10
* testcafe version:
* node.js version: 6.9.2

**Comment by AlexanderMoskovkin** [comment]
Hi Alexey,

Thanks for your report!

We've found these mistakes too and we've already updated our recipes in the repository (#1069). You can actual recipes [here](https://github.com/DevExpress/testcafe/blob/master/docs/articles/documentation/recipes/index.md). They will be updated on the site when the next testcafe version (0.12.0) is released.

> But in does not work for me. It is seems like --app option is ignored.

We've implemented this feature (#1047) in 0.12.0 that is not released yet. But you can try it now in the  `alpha` version (`npm install testcafe@alpha`). You can find the feature description in the [documentation topic](https://github.com/DevExpress/testcafe/blob/master/docs/articles/documentation/using-testcafe/command-line-interface.md#-a-command---app-command) in the repository.
