### ISSUE TITLE
Screenshot extension

### ISSUE THREAD

**Issue by beatscode** [DevExpress/testcafe#1126]
I would like to implement some sort of hook or extension to take a screenshot everytime there is a url change. If the application goes from a.html to b.html I would like to take a photo of b.html with a filename corresponding to the page url. Is this possible? If so where would I start?

**Comment by AlexanderMoskovkin** [comment]
Hi Alex,

I don't see a way how it can be done with the current testcafe version, this requires some additional implementation in our API.
Could you please tell us why do you need it? How are you going to use it in your project? With this information, we do our best to find a solution for you.

**Comment by beatscode** [comment]
I'm trying to map the different views in the application to another set of logs. I'd like to sync screenshots to the logs I have which are segmented by url. I could augment my scripts to to do this I was just curious if I could implement a hack locally.

**Comment by AlexanderMoskovkin** [comment]
Thanks for clarification. For now TestCafe doesn't provide functionality to add such hook.
I'm not 100% sure that this is what you need, but maybe the following approach will be useful for you:
```js
fixture `Get screenshots`;

const urls = ['http://google.com', 'http://gmail.com'];

for (let i = 0; i < urls.length; i++) {
    const url = urls[i];

    test('Get screenshot', async t => {
        await t.navigateTo(url);
       
        const pageUrl = await t.eval(() => window.location.href);
        const fileName = pageUrl.replace(/:|\/|\./g, '_');
        
        await t.takeScreenshot(`${fileName}.png`);
    });
}
```

Or maybe the following:
```js
import { Selector } from 'testcafe';

fixture `Get screenshots`
    .page `google.com`;

let lastPageUrl = '';

async function checkUrlAndTakeScreenshot (t) {
    const pageUrl = await t.eval(() => window.location.href);

    if(pageUrl !== lastPageUrl) {
        lastPageUrl = pageUrl;
       
        const fileName = pageUrl.replace(/:|\/|\./g, '_');
        
        await t.takeScreenshot(`${fileName}.png`);
    }
}

test('Get screenshot', async t => {
    // add the takeScreenshot function after each action
   await t.click('body');
   await checkUrlAndTakeScreenshot(t);
   await t.click(Selector('a').withText('Images'));
   await checkUrlAndTakeScreenshot(t);
   // ...
});
```

The second solution looks not pretty but maybe it'll ok for your task
