### ISSUE TITLE
Add the `--debug` flag to CLI API

### ISSUE THREAD

**Issue by churkin** [DevExpress/testcafe#1127]
This flag should passes on `--inspect` and `--debug-brk` to the testcafe and opens new chrome instance with debugger.

**Comment by AlexanderMoskovkin** [comment]
It's easy to do it without this built-in option (see the [recipe](https://github.com/DevExpress/testcafe/blob/master/docs/articles/documentation/recipes/debugging-with-chrome-dev-tools.md)).
And we have another [debug-mode](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-d---debug-mode) flag, so this feature will lead to a confusion.
