### ISSUE TITLE
Fix QUnit tests in iOS browsers (Safari, iPhone, iPad)

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#113]
It seems, problems are the same in all the browsers

https://saucelabs.com/tests/8679452a63474586af2d33eed02a589e
https://saucelabs.com/tests/e7498fd2bde04c80b7e77be44254436a
https://saucelabs.com/tests/5213d7175e8345bc8424ebd2a8e3d5c3

**Comment by AlexanderMoskovkin** [comment]
I've just found a strange thing for me in [hammerhead browser utils](https://github.com/superroma/testcafe-hammerhead/blob/master/src/client/utils/browser.js#L46).
The `isWebKit` property returns false for `Safari`. It seems some our tests are false because this.

I've found the commit (before the repo was moved to github) by @miherlosev with this change (`!isSafari` flag was added to the `isWebKit` check). In TestCafe we use the `isWebKit` check as 'it's Chrome or Safari or other webkit-based browsers'. In fact it's a breaking change for us.
I suppose we should have rename `isWebKit` property to `isChrome`. Or have both `isWebKit` and `isChrome` /cc @churkin @miherlosev

**Comment by AlexanderMoskovkin** [comment]
ping @churkin @miherlosev 
What do you think?

**Comment by miherlosev** [comment]
I think we need to rename `isWebKit` to `isChrome`.
We support only chrome and safari. We don't support other webkit-based browsers

**Comment by inikulin** [comment]
@miherlosev How about Opera?

**Comment by AlexanderMoskovkin** [comment]
we have `isOpera` and `isOperaWithWebKit` flags. But `isWebKit` is true for Opera too. So, it's confusion. We should set to rights here.

**Comment by miherlosev** [comment]
I think we need to drop support Opera with old non-webkit engine, remove `isOpera` and rename `isOperaWithWebKit` to `isOpera`.
If we support all webkit-based browsers then need to revert my change (`!isSafari` for `isWebKit` check)

**Comment by inikulin** [comment]
> I think we need to drop support Opera with old non-webkit engine, remove isOpera and rename isOperaWithWebKit to isOpera

Let's do this

**Comment by inikulin** [comment]
Stop, here is the deal: currently only Safari uses WebKit. Chrome, Opera and Yandex Browsers uses Blink - fork of WebKit which is currently is quite distinct from WebKit.

**Comment by inikulin** [comment]
Gosh, that's why I'd like to see feature detection instead of this flags.

**Comment by inikulin** [comment]
@miherlosev Any progress on this?

**Comment by miherlosev** [comment]
I think we need to revert my changes (https://github.com/DevExpress/testcafe/issues/113#issuecomment-147323077). 
Then we need to create separate issue for feature detection instead of browser detection

**Comment by helen-dikareva** [comment]
I'm working on this

**Comment by helen-dikareva** [comment]
All problems are not related to definition of 'isWebKit' or 'isSafari' was solved

**Comment by helen-dikareva** [comment]
We'll push required changed after testcafe-hammerhead update. @miherlosev

**Comment by inikulin** [comment]
Is there any pending blocking changes in hammerhead left?

**Comment by helen-dikareva** [comment]
No, to facilitate merging I'll push it after first part of https://github.com/DevExpress/testcafe/issues/56 which almost ready
