### ISSUE TITLE
Corrupted PDF files when using a printing function withing TestCafe

### ISSUE THREAD

**Issue by klepek42** [DevExpress/testcafe#1130]
### Are you requesting a feature or reporting a bug?

A bug.

### What is the current behavior?

Creating PDF documents via TestCafe results in corrupted PDF files.
Doing the same steps without TestCafe (Open Source version) or with TestCafe (paid version) results in valid PDF documents.

When comparing both PDF documents it gets clear that the PDF documents (in TestCafe) are corrupted because of inserted HTML and JavaScript code plus different encoded special characters ("&amp;" instead of "&").

You can find the following lines directly in the beginning of the corrupted PDF document:
http://pastebin.com/DuRJztzX
It seems like 'hammerhead' inserts some code in PDF documents which is wrong in this moment.

### What is the expected behavior?

Created PDF documents should be valid.

### How would you reproduce the current behavior (if this is a bug)?

Run my provided test.
It does all needed steps and creates a PDF document in the end which gets downloaded automatically.
In this case it is a web application instead of a normal website.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://www.formulare-bfinv.de (my test opens it)

Test code

```js
import { Selector } from 'testcafe';

String.prototype.find = function(pattern) {
    let re, selector = this.toString();

    if (Object.prototype.toString.call(pattern) == '[object RegExp]')
        re = new RegExp(/^\\s*/ + pattern + /\\s*$/, pattern.flags);
    else
        re = new RegExp(`^\\s*${pattern.replace(/([.*+?^=!:${}()|\[\]\/\\])/g, "\\$1")}\\s*$`);
    return Selector(selector).withText(re);
};

fixture `Kassenabrechnung`
    .page `https://www.formulare-bfinv.de`;

test('Corrupted PDF files', async t => {
    await t.click('a'.find('Formularcenter'));
    await t.click('a'.find('Steuerformulare'));
    await t.click('a'.find('Verbrauchsteuer'));
    await t.click('a'.find('Biersteuer'));
    await t.click('a'.find('2076 Biersteuererklärung'));
    await t.wait(1000);
    await t
        .click('input[title="Drucken (ALT + 5)"]')
        .click('a[title="(wird in einem separaten Fenster geöffnet)"]');
});
```

### Specify your

* operating system: MacOS Sierra 10.11.12 and Windows 7 (32-Bit)
* testcafe version: 0.11.1 (latest version via npm)
* node.js version: v4.4.4 on Mac and v6.1.0 on Windows
* browsers: Chrome 55.0.2883.95, Firefox 50.1.0, Safari 10.0.2, Opera 32.0, IE 11

**Comment by LavrovArtem** [comment]
Hi @klepek42.

Thanks for your cooperation. I reproduced your problem. I will fix it, but we don't support PDF documents. After the opening of your document you can't test it.
