### ISSUE TITLE
ERROR Unable to establish one or more of the specified browser connections

### ISSUE THREAD

**Issue by mokone91** [DevExpress/testcafe#1133]
### Are you requesting a feature or reporting a bug?
bug

### What is the current behavior?
when I launch test with nightmare (using testcafe-browser-provider-nightmare) i get 
`ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.`

I use amazone EC2 instance,
also i open some ports from amazon console, and runt tests using "DEBUG=* testcafe nightmare tests/ --ports 9991,9992 --hostname 127.0.0.1" - no luck( 
### What is the expected behavior?

test results expected

### How would you reproduce the current behavior (if this is a bug)?

fails at any test

#### Provide the test code and the tested page URL (if applicable)

Tested with test.js example from testcafe

### Specify your

* operating system: ubuntu 14.04
* testcafe version: 0.12.0-alpha4
* node.js version: 4.2

**Comment by AndreyBelym** [comment]
Hello, Eldar! Likely it's because the `nightmare` browser requires an X11 display server on Linux, which is not enabled by default on Amazon EC2. You have to install and run Xvfb; required commands depend on a distribution that you use in your instance. E.g. for Debian-based distros, including Ubuntu, it is like:
```bash
apt-get install xvfb
Xvfb :99 -ac -screen 0 1024x768x16
export DISPLAY=:99.0
testcafe nightmare tests/
```

**Comment by mokone91** [comment]
Hi Andrey,
It works!!

I use "xvfb-run" to run this tests,

Thanks!

**Comment by jackyxiao126** [comment]
Hi how to run xvfb-run? what's the options?

**Comment by AndreyBelym** [comment]
Hello @jackyxiao126, it's likely
```
xvfb-run --server-num=99 --server-args='-ac -screen 0 1024x768x16' testcafe ...
```

Check the [xvfb-run manual](http://manpages.ubuntu.com/manpages/trusty/man1/xvfb-run.1.html).

**Comment by rafaelcichocki** [comment]
Could get Jenkins in Docker to run TestCafe with Firefox and Nightmare, but not Chrome/Chromium.

    xvfb-run -a --server-args='-ac -screen 0 1024x768x16' npm run jenkins-testcafe

**Comment by AndreyBelym** [comment]
Chrome needs `--no-sandbox` flag in a Docker container, or a container should be started in privileged mode.
```
testcafe 'chrome --no-sandbox' tests/
```

**Comment by avozicov** [comment]
Hi Everyone,
I am facing the same issue when running tests in Jenkins env using Firefox browser.
```Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.```

Could somebody help me here ?

**Comment by AndreyBelym** [comment]
Hi @avozicov,if it's a headless Linux server  you should check that you've configured Xvfb: https://github.com/DevExpress/testcafe/issues/1133#issuecomment-272447990. Or you can try to use Firefox 57+ in [headless mode](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/testing-in-headless-mode.html).

If it's a WIndows server, and you configured Jenkins to run as a service, you can try to start Jenkins from command line, or follow [this article](http://blog.dougdragon.com/what-is-jenkins-doing/) to enable GUI for the Jenkins service.

**Comment by markusguenther** [comment]
I had the same issue with the Travis CI setup for the open source project I am working on.
The changes made the work again.

[Github PR](https://github.com/neos/neos-ui/pull/1544)

Testcafe itself has a documentation page for such topics.
[Documentation](http://devexpress.github.io/testcafe/documentation/recipes/running-tests-in-firefox-and-chrome-using-travis-ci.html)
