### ISSUE TITLE
Onclick event handler is not executed when TestCafe clicks on the div

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#1138]
### Are you requesting a feature or reporting a bug?

bug (converted from the [discussion](https://testcafe-discuss.devexpress.com/t/click-on-a-div-element-with-an-onclick-handler-supported/110/7))

### What is the current behavior?

An error `Click occured outside the div!!!` is raised during test execution (see the test)

### What is the expected behavior?

Test should be passed

#### Provide the test code and the tested page URL (if applicable)

Test code

```js
import { Selector } from 'testcafe';

fixture `Sample`
.page `https://rawgit.com/p-bakker/cb1113e61bf721551df08917cada1775/raw/3971d3ce01f5822b0675cebcaffb9b2822285335/test.html`;

test('div', async t => {
	const div = Selector('[data-sv-element-name="test"]')
		
	await t
	    .click(div)
            .expect(div.find('span').textContent).contains('it worked')
            .wait(2000); // just to see the page state
	}
)
```

### Specify your
* testcafe version: 0.12.0-alpha5

**Comment by AlexanderMoskovkin** [comment]
@AndreyBelym please take it

**Comment by AndreyBelym** [comment]
Okay
