### ISSUE TITLE
new feature - docker

### ISSUE THREAD

**Issue by nosovk** [DevExpress/testcafe#1141]
It would be great to run testcafe tests inside docker, to allow executing on a docker hosts with other tests.

Now there is requirement to launch testcafe on a system with locally installed browsers.

Would be nice to have some predefined docker images with different browsers to launch tests without installing chrome\firefox etc on a server.

**Comment by AlexanderMoskovkin** [comment]
Hi Konstantin,

Thanks for the idea, it looks interesting. We need to do some research to make a decision.

**Comment by IhostVlad** [comment]
@nosovk You can use this solution now https://gist.github.com/IhostVlad/09ec32f7443a52926973e9c9ca08ceed
