### ISSUE TITLE
Can't test React components with Storybook

### ISSUE THREAD

**Issue by mkubrycz** [DevExpress/testcafe#1147]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

In our project we use [React Storybook](https://github.com/storybooks/react-storybook) and we can't run tests for it with testcafe. When trying to run tests against storybook's server we keep getting this error:
```
 Storybook
 ✖ Component

   1) Error on page "http://localhost:6006/":

      Uncaught TypeError: se[e.type] is not a function

      Browser: Chrome 55.0.2883 / Mac OS X 10.12.2



 1/1 failed (1s)
```

![screen shot 2017-01-18 at 12 28 29](https://cloud.githubusercontent.com/assets/17340842/22063445/2c4f529c-dd7f-11e6-9c9d-0e95b2654181.png)

### What is the expected behavior?

for tests to run and pass

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: local storybook server

Test code

```js
import { Selector } from 'testcafe';

fixture `Storybook`
    .page `http://localhost:6006/`;

test('Component', async t => {
    await t
        .click(Selector('#component'))
       // it doesn't matter what are test instructions
});
```

### Specify your

* operating system: Mac OS X 10.12.2
* testcafe version: 0.11.1
* node.js version: 6.9.1

**Comment by churkin** [comment]
@mkubrycz I'm researching it now

**Comment by churkin** [comment]
Hi @mkubrycz,
I've deployed storybook demo app - https://github.com/kadira-samples/react-storybook-demo. And get a lot of js errors without testcafe:

![storybook](https://cloud.githubusercontent.com/assets/5182202/22107293/04969a1e-de5e-11e6-8d11-38b5c17400bc.png)

Please, try to [skip js errors.](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors). Let me know if it helps.

**Comment by mkubrycz** [comment]
Hi @churkin,

so I've tried and skipping js errors results with error:
```
1) The specified selector does not match any element in the DOM tree.
```
my browser displays just blank page although url is correct.

**Comment by churkin** [comment]
@mkubrycz Unfortunately I need example for debugging. Could you share problem link?

**Comment by mkubrycz** [comment]
@churkin 
For example you can try setting simple react app with [create-react-app](https://github.com/facebookincubator/create-react-app) and then follow [instructions on storybook page](https://getstorybook.io/docs/react-storybook/basics/slow-start-guide).
I get the same results here without any js errors

testcode:
```js
import { Selector } from 'testcafe';

const helloButton = Selector("button").withText("Hello Button");

fixture `Storybook`
    .page `http://localhost:9001/`;

test('Storybook example', async t => {
    await t
        .switchToIframe("#storybook-preview-iframe")
        .click(helloButton);
});
```

**Comment by miherlosev** [comment]
I ran `test-example.js` from your [repo](https://github.com/mkubrycz/test-storybook-example) and got an error:
![Report](https://cloud.githubusercontent.com/assets/4133518/22205444/f49c5982-e187-11e6-8dee-98ae3749ac01.png)

It looks like you don't add a file with page model definitions.

Please, provide this file.

**Comment by mkubrycz** [comment]
@miherlosev 
Sorry I was copying quickly from another example I was trying to run. It was supposed to be:
```js
import { Selector } from 'testcafe';

const helloButton = Selector("button").withText("Hello Button");

fixture `Storybook`
    .page `http://localhost:9001/`;

test('Storybook example', async t => {
    await t
        .switchToIframe("#storybook-preview-iframe")
        .click(helloButton);
});
```
from the start.
I've fixed this in my [repo](https://github.com/mkubrycz/test-storybook-example). Still doesn't work, when I run normally I get `Uncaught TypeError: se[e.type] is not a function` and when I'm ignoring js errors `The specified selector does not match any element in the DOM tree.` and there's nothing displayed in the browser window besides `Waiting for an element to appear`.

**Comment by miherlosev** [comment]
Cannot reproduce.

![screen shot 2017-01-24 at 4 06 38 pm](https://cloud.githubusercontent.com/assets/4133518/22248394/7d4659dc-e24f-11e6-879a-e34484af7fea.png)

Try to update to the latest testcafe version - 0.12.1 and check on it

**Comment by mkubrycz** [comment]
Thank you @miherlosev and @churkin !

new version indeed fixed my problem.
