### ISSUE TITLE
TestCafe cursor is not visible

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#1156]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
TestCafe mouse cursor is not visible when performing actions.

### What is the expected behavior?
TestCafe mouse cursor should be visible when performing actions.

### How would you reproduce the current behavior (if this is a bug)?
Run any test

### Specify your

* operating system: Ubuntu 14.04, Windows 10
* testcafe version: 0.12.0
* node.js version: 7.2.0

**Comment by AlexanderMoskovkin** [comment]
https://github.com/DevExpress/testcafe/commit/1cb440a956f32798a7afb526d62ca876566386e0
