### ISSUE TITLE
ReferenceError: TestCafe is not defined

### ISSUE THREAD

**Issue by WillemMali** [DevExpress/testcafe#1157]
### Are you requesting a feature or reporting a bug?

Reporting a bug.

### What is the current behavior?

I install TestCafe in my project directory using:

`npm install testcafe`

Then I make a JS script in the same folder to start TestCafe:

```
var testCafe = require('testcafe');

var testCafe = new TestCafe({
    controlPanelPort: 8000,
    servicePort: 8080,
    testDir: 'tests'
});
```

Then I call this script using the following script (also in the same directory):

```
#!/bin/sh -eu
node run.js "$@"
```

I've also tried using this instead:

```
#!/bin/sh -eu
NODE_PATH=`realpath node_modules` node run.js "$@"
```

But both give me the following output:

```
/home/redacted/testcafe/node_modules/brotli/build/encode.js:3
ocess.on("uncaughtException",function(a){if(!(a instanceof y))throw a;});b.ins
                                                                    ^
ReferenceError: TestCafe is not defined
    at Object.<anonymous> (/home/redacted/testcafe/run.js:3:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

### What is the expected behavior?

No errors, and I can proceed to expanding my script to run my tests.

### How would you reproduce the current behavior (if this is a bug)?

Re-run the steps I mentioned.

### Specify your

* Debian Testing x64
* 0.12.0
* v4.6.1

**Comment by AlexanderMoskovkin** [comment]
Hi @WillemMali,

It seems you have found this example in the [documentation](https://testcafe.devexpress.com/Documentation/Using_TestCafe/Continuous_Integration/#Sample_Testing_Application) for the [previous TestCafe version](https://testcafe.devexpress.com/).

The new [open-source TestCafe](https://devexpress.github.io/testcafe/) has different API (see [documentation](https://devexpress.github.io/testcafe/documentation/getting-started/)). In the [Programming Interface](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/) article you can find how to use TestCafe from your Node.js modules.

Also there is a typo in your code for the previous version, it should be:
```js
var TestCafe = require('testcafe');

var testCafe = new TestCafe({
    controlPanelPort: 8000,
    servicePort: 8080,
    testDir: 'tests'
});
```

**Comment by WillemMali** [comment]
Hi @AlexanderMoskovkin, thank you very much for the support! I wasn't aware that there were two sets of docs, neither of them indicate a version or that one is deprecated.

Shall I flesh out an issue for "Add deprecation/out-of-date notice to documentation on testcafe.devexpress.com", or would you consider that "pollution" of the open-source issue tracker? A one-word response will do fine.

**Comment by AlexanderMoskovkin** [comment]
I put it wrong in my previous post. [testcafe.devexpress.com](https://testcafe.devexpress.com/) is a website dedicated to the paid version of TestCafe, not the previous one. So, the documentation at [testcafe.devexpress.com](https://testcafe.devexpress.com/) is recent but it doesn't relate to the open-source TestCafe.
