### ISSUE TITLE
SyntaxError: Unexpected identier at createTestCafe

### ISSUE THREAD

**Issue by WillemMali** [DevExpress/testcafe#1159]
### Are you requesting a feature or reporting a bug?

Reporting a bug.

### What is the current behavior?

I'm trying to set up my testing environment for the first time, so I took [the code](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/testcafe.html) [from the](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/) [testcafe.github.io documentation](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html).

Start of my test runner:
```
#!/usr/bin/env node
const createTestCafe = require('testcafe');
const testCafe       = await createTestCafe('localhost', 1337, 1338);
```

Error message:

```
/home/willem/w/bizaline/testcafe/run.js:3
const testCafe = await createTestCafe('localhost', 1337, 1338);
                       ^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

I'm pretty confused how this can contain a syntax error.

I double checked I didn't have typos, copied it from the examples and ran that, copied the example code from all three places I found it at and diffed them (no difference), and stared at these lines for a few minutes. Nothing about it looks strange.

### What is the expected behavior?

No errors.

### How would you reproduce the current behavior (if this is a bug)?

See above.

### Specify your

* Debian Testing x64
* testcafe 0.12.0
* node.js version: 0.10.29

**Comment by VasilyStrelyaev** [comment]
Hi @WillemMali ,
This example uses `async/await` syntax that isn't supported by the version of Node.js you use.

We have an issue about that https://github.com/DevExpress/testcafe/issues/989.

With Node.js v0.10.29, use promises

```js
const createTestCafe = require('testcafe');

createTestCafe('localhost', 1337, 1338)
    .then(testcafe => {
        testcafe
            .createRunner()
            .src('tests/fixture1.js')
            .browsers(['chrome', 'safari'])
            .run();
    });
```
