### ISSUE TITLE
Create TAP reporter plugin

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#1177]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
We cannot emit reports in [TAP](https://testanything.org/tap-specification.html) format, which is quite popular and has good interoperability (https://github.com/sindresorhus/awesome-tap).

### What is the expected behavior?
We should have TAP as an output format

**Comment by inikulin** [comment]
Dup #407. Do we need plugin or built-in reporter? I guess we should make it built-in reporter
