### ISSUE TITLE
Support XPath based selectors

### ISSUE THREAD

**Issue by georgiy-abbasov** [DevExpress/testcafe#1178]
### Are you requesting a feature or reporting a bug?

Feature

### What is the current behavior?

TestCafe admits CSS and ClientFunction based selectors. It would be nice, if XPath selectors were supported too. 

### What is the expected behavior?

something like
```js
let submitBtn    = Selector('//form/input[text()="Submit"]')
let submitForm   = Selector('//input[text()="Submit"]/../')
```

**Comment by Jeroenhuisjes** [comment]
Would save a lot of time with making tests at the company I work for!

**Comment by mkubrycz** [comment]
But you can do exactly the same thing using TestCafe API:
```javascript
let submitBtn = Selector('form input').withText('Submit')
let submitForm = Selector(input).withText('Submit').parent()
```
IMHO it reads better than clumsy XPath

**Comment by Uninen** [comment]
+1

This would help a lot with porting old e2e tests to testcafe.

**Comment by lnfnunes** [comment]
@mkubrycz regardless of better or not, it's a common option from other e2e test runners and will help to port old test-cases to _testcafe_.
Besides that, it will be an extra option to be used for anyone interested on it!

**Comment by AlexanderMoskovkin** [comment]
Although TestCafe doesn't support XPath based selectors out-of-the-box now you can use them in your tests. Take a look at my example:

```js
// xpath-selector.js
import { Selector } from 'testcafe';

const elementByXPath = Selector(xpath => {
    const iterator = document.evaluate(xpath, document, null, XPathResult.UNORDERED_NODE_ITERATOR_TYPE, null )
    const items = [];

    let item = iterator.iterateNext();

    while (item) {
        items.push(item);
        item = iterator.iterateNext();
    }

    return items;
});

export default function (xpath) {
    return Selector(elementByXPath(xpath));
}
```
```js
// test.js
import XPathSelector from './xpath-selector';

fixture `Use XPath`
    .page `https://github.com`;

test('Check header links count', async t => {
    const headerLinkXPath = '/html/body/div[1]/header/div/div[2]/nav/ul/li/a';
    const headerLink =      XPathSelector(headerLinkXPath);
    
    await t
        .maximizeWindow()
        .expect(XPathSelector(headerLinkXPath).count).eql(5);
});
```

**Comment by neilmatillano** [comment]
@AlexanderMoskovkin : I want to reuse this function inside my testcafe tests, but it seems like we always need to have it specify the exact path from "/html/...", I am updating the function now as we speak, but if you already have created the updated version of this function, it would be great ;)

XPath formats like this is a bit hard to distinguish...
//*[@id="audiences-creation-form"]/div[2]/fieldset[1]/div/div[2]/div/div/div[2]/div[2]/ul/li/span[1]

**Comment by AlexanderMoskovkin** [comment]
Hi @neilmatillano,

I haven't worked on this yet, so it would be nice if you add you improved version of this function.

**Comment by xcb6** [comment]
maybe use https://www.npmjs.com/package/xpath-to-css

**Comment by neilmatillano** [comment]
@xcb6 : Sounds good, do you have more examples of the usage? One that is working well 
I get this error in testcafe even just calling console.log

TypeError: xpath_to_css_1.default is not a function

**Comment by xcb6** [comment]
work well for me
```js
import { Selector } from 'testcafe'
import xPathToCss from 'xpath-to-css'
const xPath = '//div[@id="foo"][2]/span[@class="bar"]//a[contains(@class, "baz")]//img[1]'
const css = xPathToCss(xPath)
console.log(css)
...
```

**Comment by neilmatillano** [comment]
@xcb6 : Maybe it's my version of testcafe. I am using this version : 0.18.7-dev20180206
Which version are you using?

**Comment by neilmatillano** [comment]
@xcb6 : Found the issue, i am using typescript ... so I should follow the es6 format of importing which is  _import * as xPathToCss from 'xpath-to-css'_

**Comment by Andrei1982** [comment]
When I use xpath-to-css recive this issue: " 

> Invalid or unsupported XPath: .//a[text()="Регистрация"]"

There is import in my file.js: 
```
import xPathToCss from 'xpath-to-css';
```
Can any help me?

**Comment by AlexanderMoskovkin** [comment]
I'm closing this since it can be done with third-party modules (like `xpath-to-css`). So, we are not going to implement this in the near future.

**Comment by miherlosev** [comment]
I believe it make sense to have build-in XPath support in TestCafe.

Workaround

```js
import { Selector } from 'testcafe';

fixture `fixture`
	.page('https://devexpress.github.io/testcafe/example/');

test('type text', async t => {
	const bodySelector = Selector(() => {
		return document.evaluate('/html/body', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue
	});
	
	await t.typeText(bodySelector, 'This is some text');
});	
```

**Comment by miherlosev** [comment]
https://github.com/DevExpress/testcafe/issues/4548

**Comment by wentwrong** [comment]
One more [case](https://stackoverflow.com/questions/62510808/how-to-override-standard-testcafe-errors). Probably should be implemented along with [this](https://github.com/DevExpress/testcafe/issues/5254).

**Comment by miherlosev** [comment]
Hi folks,

We recommended creating CSS-based selectors. If you need support with XPath-based selectors, please use one of the many approaches described in this thread. Also, you can see an [example](%5Bhttps://github.com/DevExpress/testcafe-examples/tree/master/examples/use-xpath-selectors%5D(https://github.com/DevExpress/testcafe-examples/tree/master/examples/use-xpath-selectors)) in the `testcafe-examples` repository.
