### ISSUE TITLE
Unable to take screenshots on linux with GNOME on Wayland

### ISSUE THREAD

**Issue by sirgallifrey** [DevExpress/testcafe#1180]
### Are you requesting a feature or reporting a bug?

Bug (I think)

### What is the current behavior?

Test unable to take screenshots on linux
![error screenshot](https://cloud.githubusercontent.com/assets/2331645/22347199/2a203ae8-e3ee-11e6-8745-c3725f3cabc9.png)
```
  Was unable to take a screenshot due to an error.

  Command failed: /home/browser-tests/node_modules/testcafe-browser-tools/bin/linux/64/screenshot
  /home/browser-tests/ss/2017-01-26_05-15-43/test-3/Chrome_55.0.2883_Linux_0.0.0/errors/1.png
  X Error of failed request:  BadWindow (invalid Window parameter)
    Major opcode of failed request:  3 (X_GetWindowAttributes)
    Resource id in failed request:  0x0
    Serial number of failed request:  7
    Current serial number in output stream:  8

```

### What is the expected behavior?

To take screenshots normally, as it as introduced for linux in v0.12.0

### How would you reproduce the current behavior (if this is a bug)?

I just run a test which fails with the options to take screenshots on fails

### Steps to reproduce

`test.js`
```javascript
fixture('test').page('http://google.com')

test('if is facebook', async (t) => {

    await t.expect(await t.eval(() => {window.location.toString()})).match(/(facebook.com)$/, 'hey, this is not facebook');
});
```

```bash
testcafe -S -s ./ss chrome test.js
```

### Specify your

* operating system: Arch Linux x86_64 / Kernel Release: 4.8.13-1-ARCH
* testcafe version: v0.12.1
* node.js version: v7.4.0

**Comment by AndreyBelym** [comment]
Hello, @sirgallifrey! What window manager are you using? Currently we need full EWMH support: https://github.com/DevExpress/testcafe-browser-tools/issues/112.

**Comment by sirgallifrey** [comment]
Ohh I see.. Sorry I haven't searched for issues on testcafe-browser-tools
Is there something I can do to help?

My wm info:
```
# wmctrl -m
Name: GNOME Shell
Class: N/A
PID: N/A
Window manager's "showing the desktop" mode: N/A
```

**Comment by AndreyBelym** [comment]
Are you using Wayland or X11?

**Comment by sirgallifrey** [comment]
X11

**Comment by AndreyBelym** [comment]
Can you give me the outputs of `pacman -Q` and `ps aux`, please?

**Comment by sirgallifrey** [comment]
yes, but they are a little big, I paste here anyway?

**Comment by sirgallifrey** [comment]
[ps aux](http://pastebin.com/U2qKK7EK)

[pacman -Q](http://pastebin.com/1tYwDNQ6)

**Comment by AndreyBelym** [comment]
Really thank you! Unfortunately, you are using Wayland (search for `wayland` in `ps aux`). GNOME Shell has very limited support for EWMH under Wayland: https://wiki.gnome.org/Initiatives/Wayland/Gaps#ICCCM.2BAC8-EWMH. With X11 Gnome Shell it must be fine, I have tested X11 GNOME on Fedora 24. As workaround, please, try to log out, get to the password input screen, press the gear and select regular GNOME (not GNOME on Wayland), like on the screenshot below.
![image](https://cloud.githubusercontent.com/assets/4479386/22368917/18fd551e-e49a-11e6-95b3-6793c9fcebc4.png)

**Comment by sirgallifrey** [comment]
:open_mouth: You know more about my OS setup than myself.. haha
In my 'gear menu' I have the options: GNOME, GNOME Classic and GNOME on Xorg. I was using the `GNOME` option and to test I changed to `GNOME on Xorg` but it had no effect and the `ps aux` still shows Wayland... 
I am the one who have to thank you @AndreyBelym 

So it's not a bug then.
It's expected to not work on a EWMH-non-compliant window manager.

I don't know if you guys have plans on supporting non EWMH window managers or not, but if you do I'm available to help if you need to test something

**Comment by AndreyBelym** [comment]
Yes, we have, and I think that we have to develop it ASAP, because GNOME is quite popular desktop environments, and meanwhile Wayland is getting more common.

**Comment by AndreyBelym** [comment]
Closed in favor of https://github.com/DevExpress/testcafe/issues/2415
