### ISSUE TITLE
Firefox: cant input text in input field with type="email"

### ISSUE THREAD

**Issue by dwasilew** [DevExpress/testcafe#1187]
### Are you requesting a feature or reporting a bug?
reporting a Bug

### What is the current behavior?
If running test with Firefox 51.0  input fields with type email can't be set. Instead the following error occurs:
```
Uncaught object "[object Object]" was thrown. Throw Error instead.
```
Chrome and Opera are working as expected. When changing type="email" to type="text" also Firefox works.

### What is the expected behavior?

Input text in input with type "email" without an error

### How would you reproduce the current behavior (if this is a bug)?

i attached a [input-test.tar.gz](https://github.com/DevExpress/testcafe/files/738704/input-test.tar.gz) based on one of your examples.
* extract
* npm install
* npm test

should be enough to get the error. When exchanging firefox with chrome in package.json the test runs fine

### Specify your

* operating system: Ubuntu 16.10
* testcafe version: 0.12.1
* node.js version: v4.2.6

**Comment by georgiy-abbasov** [comment]
Hello Daniel ! Thanks a lot for report. We reproduced the issue and have found, that Firefox 51 doesn't allow to call method `setSelectionRange` for input elements, which type isn't `text`. 
We are working on it, i'll let you know, when it'll be fixed.

**Comment by georgiy-abbasov** [comment]
Hi Daniel! We have fixed this issue in our new version (it's with alpha tag now). Please check whether the fix works with your site. To install fix, run:
```cmd 
npm install testcafe@alpha.
```
