### ISSUE TITLE
Script error causes tests to fail

### ISSUE THREAD

**Issue by umaar** [DevExpress/testcafe#1188]
Sometimes tests exit early with logging like this:

```
   1) Error on page "http://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-016-2850-8":

      Script error.
```

Which doesn't really say what the problem is. I imagine this is due to a client side JS error with the 
web page? The problems I see here are:
- Testcafe tests should not fail due to a client side JS error
- 'script error' is not very useful. It would be good to see the actual error which was thrown 

### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Tests exit with ` Script error.`

### What is the expected behavior?
Tests do not exit

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: //bmcgenomics.biomedcentral.com/articles/10.1186/s12864-016-2850-8

### Specify your

* operating system: OS X
* testcafe version: 0.12.1
* node.js version: 7

**Comment by AlexanderMoskovkin** [comment]
Hi,

I've reproduced the issue and I'm working on it.

> Testcafe tests should not fail due to a client side JS error

You can do it optionally with the [`skip-js-errors` option](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors)

**Comment by AlexanderMoskovkin** [comment]
After some investigation we've found that the issue relates to our proxy module and we've created an issue there: https://github.com/DevExpress/testcafe-hammerhead/issues/1026

**Comment by umaar** [comment]
Quick response! Thanks a lot. In the mean time, `skip-js-errors` is great.

**Comment by AlexanderMoskovkin** [comment]
We've fixed the issue. It will be available in the next release.
Also we've published a daily build version with the fix (`v0.13.0-alpha2`). You can install it via
```sh
npm install testcafe@alpha
```

**Comment by Lwdthe1** [comment]
Hmm, I'm running into this issue today. My tests work as expected in the chrome browser, but it fails with:

```
Uncaught Error: Script error for "services/services"
http://requirejs.org/docs/errors.html#scripterror
```

**Comment by Lwdthe1** [comment]
^ I didn't mean to unassign someone. Not sure how that happened.

**Comment by Lwdthe1** [comment]
I found the issue using `t.debug()`. It was a problem with a library my site was loading.
