### ISSUE TITLE
Script error and hangs in iOS webviews (Firefox, Chrome of iOS)

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#1189]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Test throws 'Script Error' or even hangs when using `navigateTo` on https://staging.implantbase.com/cases/list
Forum thread: https://testcafe-discuss.devexpress.com/t/script-error-with-no-information/140

### What is the expected behavior?
Test should work normally.

### How would you reproduce the current behavior (if this is a bug)?
Run the test fragment

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://staging.implantbase.com/cases/list

Test code

```js
t.navigateTo('https://staging.implantbase.com/mobileHome/home')
```

### Specify your

* operating system: iOS 9
* testcafe version: 0.13.0-alpha1
* node.js version: 7.4.0

**Comment by AlexanderMoskovkin** [comment]
It seems it works ok with `testcafe@0.13.0-alpha2`.
Feel free to reopen the issue if it doesn't work on your side
