### ISSUE TITLE
An inconsistent appears while the window.history.back() method is using

### ISSUE THREAD

**Issue by Raushen** [DevExpress/testcafe#1190]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

Input's value is not stored by browsers

### What is the expected behavior?

Input's value is stored by browsers

### How would you reproduce the current behavior (if this is a bug)?

See below

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

//HTML
```
<input type="text" id="textInput"/>
<input type="submit" id="submitInput"/>
```

Test code

```
const historyBack = ClientFunction(() => window.history.back());

test('History syncronization', async t => {
    const submitInput =  Selector('#submitInput');
    const textInput = Selector('#textInput');
    await t.typeText(textInput, "Some text");
    await t.click(submitInput);
    await t.expect(textInput.value).eql(""); //OK
    await historyBack();
    await t.expect(textInput.value).eql("Some text"); //FAIL
}

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by churkin** [comment]
@raushen please, add completed html markup to problem reproducing

**Comment by Raushen** [comment]
Hello, you can use the follow markup in .aspx file to reproduce issue:
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
</head>
<body>
    <form id ="form1" runat="server">
        <input type="text" id="textInput" />
        <input type="submit" id="submitInput" />
        <input onclick="window.history.back()" type="button" value="history.back" id="historyInput" />
    </form>
    
</body>
</html>
```
Complete test:
test('History test', async t => {
    const submitInput =  Selector('#submitInput');
    const textInput = Selector('#textInput');
    const historyInput = Selector('#historyInput');
    await t.typeText(textInput, "Some text");
    await t.click(submitInput);
    await t.expect(textInput.value).eql(""); //OK
    await t.click(historyInput);
    await t.expect(textInput.value).eql("Some text"); //FAIL
});

**Comment by inikulin** [comment]
@churkin Was you able to reproduce it?

**Comment by churkin** [comment]
duplicate https://github.com/DevExpress/testcafe-hammerhead/issues/1013
