### ISSUE TITLE
Feature Request: Wait For Custom Condition

### ISSUE THREAD

**Issue by umaar** [DevExpress/testcafe#1192]
### Are you requesting a feature or reporting a bug?

Feature

Can you provide a `waitFor` implementation please? See https://github.com/admc/wd/blob/43ab7d2d005b78b5496d1a03545273460daa0ad2/README.md#waiting-for-something

**Comment by AlexanderMoskovkin** [comment]
Take a look at [Selectors](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors.html) and [built-in assertions](https://devexpress.github.io/testcafe/documentation/test-api/assertions/).
For example, if you need to wait for some element is appeared on the page you can use the following:
```js
await t.expect(Selector('.foo').exists).ok('element exists', { timeout: 10000 })
```

If you need to implement waiting with some custom client-side logic you can use [ClientFunction](https://devexpress.github.io/testcafe/documentation/test-api/obtaining-data-from-the-client.html):
```js
const getSomePropertyValue = CilentFunction(() => window.someProperty);
await t.expect(getSomePropertyValue()).gt(5, 'assertion message', { timeout: 6000 });
```

So, `waitFor` action will duplicate assertions. Do you have some cases that can't be covered with `Selectors`, `ClientFunctions` and assertions?

**Comment by umaar** [comment]
Perfect that's what I was looking for. Sorry should have read the docs properly!

Thank you.

**Comment by mjhea0** [comment]
@AlexanderMoskovkin what if you have a task that could take anywhere from 1 second to 3 minutes? 

Workflow:

1. end user submits code into an editor
1. code is sent to server, tests run
1. button on the client changes 
1. when tests are done (anywhere from 1 second to 3 minutes) and sent back to the client, the button changes and results are displayed

I want to assert that the results are as they should be. How can I wait for this to be completed? I'd love to be able to wait to check the results until the button changes the second time..

**Comment by inikulin** [comment]
@mjhea0 Create `ClientFunction`/`Selector` query that observes required change and use assertion with 3 minutes [timeout](https://devexpress.github.io/testcafe/documentation/test-api/assertions/#assertion-options).

**Comment by mjhea0** [comment]
So if the change happens before 3 minutes it will work?

**Comment by mjhea0** [comment]
the timeout is like a bound?
