### ISSUE TITLE
Can't open up DevTools with keyboard shortcuts or Right Click

### ISSUE THREAD

**Issue by umaar** [DevExpress/testcafe#1193]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

DevTools can't be opened with keyboard shortcuts or right clicking

### What is the expected behavior?

I should be able to open DevTools using shortcuts

### How would you reproduce the current behavior (if this is a bug)?

`t.wait(10000)` in the test, then try to right click and inspect element. Notice Right Clicking doesn't do anything.

**Comment by inikulin** [comment]
We usually prevent non-testcafe actions on page to avoid side effects by accidental user actions. Though we've made exceptions for shortcuts that open dev tools, seems like we missed something. Which OS and browser you are using?

**Comment by umaar** [comment]
I'm on mobile now but off the top of my head its cmd+alt+I on mac using the Chrome browser

**Comment by AlexanderMoskovkin** [comment]
Hi,

I've reproduced the problem on mac. We will fix it. 
As a workaround you can click on the browser's address bar and then press cmd+alt+I. Dev tools will be opened then

**Comment by umaar** [comment]
Thank you for the quick responses!
