### ISSUE TITLE
Using 'fast-async' for transpiling async functions

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#1205]
The [fast-async](https://www.npmjs.com/package/fast-async) package can transform ES2017 async/await to a plain Promise chain, with _no runtime needed_. It's implemented as a babel plugin, so it can be used instead of `babel-transform-async-functions-to-generator`.

Example input:
```js
let answer = async () => 42;

(async () => console.log(`Answer is ${await answer()}`))()
```

Example output:
```js
let answer = () => new Promise(function ($return, $error) {
  return $return(42);
}.bind(this));

(() => new Promise(function ($return, $error) {
  return Promise.resolve(answer()).then(function ($await_1) {
    try {
      return $return(console.log(`Answer is ${$await_1}`));
    } catch ($boundEx) {
      return $error($boundEx);
    }
  }.bind(this), $error);
}.bind(this)))();
```

**Comment by inikulin** [comment]
What's benefits of this? IMHO compilation to generators looks much cleaner + I guess compilation to promise chain will not play well with source maps

**Comment by AndreyBelym** [comment]
No runtime means that we can use it for the client side. Sourcemaps generation works, and it's possible to use breakpoints in DevTools.

**Comment by AndreyBelym** [comment]
There is no benefit in using this module now.
