### ISSUE TITLE
Implement proxy settings for TestCafe

### ISSUE THREAD

**Issue by georgiy-abbasov** [DevExpress/testcafe#1206]
### Are you requesting a feature or reporting a bug?

feature

### What is the current behavior?

In corporate networks, where browser have specified proxy settings for access to WEB, TestCafe cannot establish connection to the remote resources, cause all requests are sent directly to the remote host, bypassing corporate proxy.

### What is the expected behavior?

TestCafe should provide capability to setup proxy options, like `http proxy url`, `http proxy port` etc

**Comment by churkin** [comment]
https://github.com/DevExpress/testcafe-hammerhead/issues/1032

**Comment by AlexanderMoskovkin** [comment]
Let determine API for this feature.
My proposal:
CLI:
```sh
New options:
--proxy-url
--proxy-ignore

testcafe chrome tests/ --proxy-url x.x.x.x --proxy-ignore "a.com,b.com"
```

Programming Interface:
```js
const proxyUrl = 'x.x.x.x'
const ignoreHosts = ['a.com', 'b.com'];

runner
    .proxy(proxyUrl, ignoreHosts)
```

/cc @DevExpress/testcafe-docs @inikulin @VasilyStrelyaev

**Comment by inikulin** [comment]
What's proxy ignore options are for?

**Comment by VasilyStrelyaev** [comment]
maybe `proxy-bypass` instead of `proxy-ignore` (if I get it right)?

**Comment by AlexanderMoskovkin** [comment]
So, as I understand, we've decided don't add proxy-ignore option for now.

CLI:
```sh
New option:
--proxy-url

testcafe chrome tests/ --proxy-url x.x.x.x
```

Programming Interface:
```js
const proxyUrl = 'x.x.x.x'

runner
    .proxy(proxyUrl)
```

Is it ok?

**Comment by georgiy-abbasov** [comment]
@AlexanderMoskovkin, we can specify proxy port in the url, if it necessary. I mean, change 'x.x.x.x' to 'x.x.x.x:yyyy' in these snippets (in the docs in the future).

**Comment by tiagorosendo** [comment]
any update ?

**Comment by inikulin** [comment]
@tiagorosendo We are working on it. More likely it will be released in `alpha` in a couple of weeks.

**Comment by tiagorosendo** [comment]
Ok thanks !

**Comment by anescobar1991** [comment]
Why did you guys decide on not adding proxy-ignore option? Is there any plan to add this in future and if not can I help contribute?

**Comment by inikulin** [comment]
@anescobar1991 We've decided to start with minimal feature set and advanced features afterwards if there will be a demand for them. If you are interested in this feature, open new issue, please. PRs are welcome as well.

**Comment by wengxuan** [comment]
any update on this?

**Comment by AlexanderMoskovkin** [comment]
It's already available (since the `0.15.0` version). See the [--proxy](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--proxy-host) option for details.

**Comment by n0v1** [comment]
It seems that the proxy option sets the proxy even for requests to localhost, I think it would make sense to ignore the proxy for requests to localhost or 127.0.0.1. What do you think?

**Comment by AlexanderMoskovkin** [comment]
@n0v1, It sounds reasonable. We'll think about it in the context of the #1791 issue.

**Comment by MishraApa** [comment]
@AlexanderEgorov 

I tried below your solutions to implement Proxy setting but did not get any proper solution:

1)I tried with command (testcafe chrome tests/ --proxy-url x.x.x.x --proxy-ignore "a.com,b.com")  but it does not work for me . Can you please provide the exact syntax.

2)test runner -It's saying proxy is not a function

Also i gone thorugh http://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/user-profiles.html and tried to create new user profile but it  also does work for me .

It would be great if you can reply ASAP.

**Comment by AlexanderMoskovkin** [comment]
Hi @MishraApa,

You can find the correct TestCafe API in our [documentation](http://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html).
Now TestCafe has option [--proxy](http://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--proxy-host) which specifies the proxy server in your local network to access the Internet.
The [proxy-ignore](https://github.com/DevExpress/testcafe/issues/1791) feature is not implemented yet but will be included in the next TestCafe release.

**Comment by MishraApa** [comment]
Hi @AlexanderMoskovkin 

I have tried above solution provided in documentation to host proxy  but none of the solution is working for me .Could please suggest how to do proxy setting testcafe ?

Thanks
Aparna

**Comment by AlexanderMoskovkin** [comment]
Could you please describe your issue in details? What url you'd like to open in you tests, what proxy do you use, what happens when you run your tests?
