### ISSUE TITLE
Allow to use file protocol for test page URLs

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#1213]
- [ ] Update `testcafe-hammerhead`  to `v.10.3.3`
 - [ ] Fix protocol detection in [TestingUnit](https://github.com/DevExpress/testcafe/blob/013480c79ded45d5ff3960a899b7e56cec0f0316/src/api/globals/testing-unit.js#L8)

**Comment by miherlosev** [comment]
> Fix protocol detection in TestingUnit

You can import this from Fix protocol detection in TestingUnit
