### ISSUE TITLE
Add `paste` option to TypeOptions

### ISSUE THREAD

**Issue by ericyd** [DevExpress/testcafe#1230]
### Are you requesting a feature or reporting a bug?

Requesting a feature

### What is the current behavior?

The `typeText` command enters text character by character with no option to insert a block of text in a single keystroke.

### What is the expected behavior?

A TypeOption should be added to insert a block of text in one keystroke.

#### Suggested syntax

I propose an option named `paste`, as this functionality will emulate the copy and paste functionality that should already be familiar to users.

```js
await t.typeText(selector, text, { paste: true };
```

### Specify your

* operating system: Linux Mint 17.1
* testcafe version: 0.13.0
* node.js version: 7.4

**Comment by inikulin** [comment]
Hi, good idea. I saw you issued PR already: feel free to contribute.

**Comment by drakor007** [comment]
Thanks a lot, 
 it solved my problem with inserting a message into the html editor field. Because HTML editor changed normal spaces to &nbsp;
Insert whole message like a ctrl+v leaves spaces as they are.
