### ISSUE TITLE
An error appeared when try to get a non-existent child by index

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#1240]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

`Function that specifies a selector can only return a DOM node, an array of nodes, NodeList, HTMLCollection, null or undefined. Use ClientFunction to return other values` error is appeared

### What is the expected behavior?

Should return a Selector instance that returns `false` for `await element.exists`

### How would you reproduce the current behavior (if this is a bug)?

run the test

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
any. For example:
https://testcafe-discuss.devexpress.com/

Test code

```js
import { Selector } from 'testcafe';

fixture `Example`
    .page `https://testcafe-discuss.devexpress.com/`;
    

test('Example', async t => {
    const btn = Selector('#main').child(2);
    
    console.log(await btn.exists);
});
```

### Specify your

* testcafe version: 0.13.0-alpha2

**Comment by p-bakker** [comment]
Should it raise an error at all? Shouldn't it just return a Selector instance that returns false when you call .exists on it?

**Comment by AlexanderMoskovkin** [comment]
You are right. I've updated the initial post
