### ISSUE TITLE
Touch cursor is not centered on target element

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#1244]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Circle cursor positioned over target element so it's top left corner is over target's center. It's behavior of the pointer-like cursor. E.g. the target is YouTube logo.

![image](https://cloud.githubusercontent.com/assets/4479386/22981432/718fb33a-f3ad-11e6-9a1b-ad85229f3dca.png)

### What is the expected behavior?
Touch cursor should be centered on target-element

### How would you reproduce the current behavior (if this is a bug)?
Start test on a touch device

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://youtube.com

Test code

```js
fixture `Google`.page `https://youtube.com`;

test('test', async t => {
    await t
        .click('#koya_elem_2_1 > div._mihc > div > button > span')
        .wait(1000000000);    
});
```

### Specify your

* operating system: Windows 10
* testcafe version: 0.13.0-alpha3
* node.js version: 7.5.0

**Comment by georgiy-abbasov** [comment]
Duplicate of https://github.com/DevExpress/testcafe/issues/739

**Comment by AndreyBelym** [comment]
My fault, I was misleading, `initial-scale` doesn't help with this one, cursor is still displaced with this meta. Something is wrong with `pointerOffsetX` and `pointerOffsetY` in cursor UI.
