### ISSUE TITLE
Uncaught JavaScript error Script error. on page

### ISSUE THREAD

**Issue by kirovboris** [DevExpress/testcafe#1248]
I get this error in report if i throw exception in React component constructor in Electron application.

**Comment by CrashyBang** [comment]
Hey @kirovboris you don't happen to have an open sour repo showing your electron/testcafe setup?

**Comment by kirovboris** [comment]
Hi @CrashyBang.
We are planning to support testing of electron applications soon, you can subscribe to notifications to be informed about our progress:
https://github.com/DevExpress/testcafe/issues/224

**Comment by AlexanderMoskovkin** [comment]
Here is a conclusion after the first investigation:
Testcafe works properly here. This error occurs without testcafe when the Electron application is run in the testing environment. It's reproduced when we run the application via our [provider](https://github.com/AndreyBelym/testcafe-browser-provider-electron) too. 

If we run the application, handle `window.onerror` event and raise an error in the application, we see the `Script error.` in the `window.onerror` handler. Here is described when does it usually happen: http://stackoverflow.com/a/7778424/7162281

We'll investigate more it in the context of the issue: https://github.com/AndreyBelym/testcafe-browser-provider-electron/issues/2

**Comment by Turkirafaa** [comment]
Hi @AlexanderMoskovkin 
Can you help my i am having this problem 

Error on page 

      Uncaught TypeError: Cannot read property 'secret' of undefined

**Comment by AlexanderMoskovkin** [comment]
Hi @Turkirafaa,

Please take a look at the following section in our F.A.Q.: [When I run a TestCafe test, I get an unexpected error. What can cause that?](https://devexpress.github.io/testcafe/faq/#when-i-run-a-testcafe-test-i-get-an-unexpected-error-what-can-cause-that)

It this doesn't help could you please provide a link to your page if it's possible?

**Comment by Turkirafaa** [comment]
Hi @AlexanderMoskovkin 
I am still have the same problem and i am sorry for can't send link but if you have privet chat so i can explain more to you

**Comment by AlexanderMoskovkin** [comment]
Please email me to the mail address in my GitHub profile. I'll provide you with a link to a Slack channel where we can discuss your issue
