### ISSUE TITLE
Let `Runner.browser()` accept browser paths

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#125]

**Comment by inikulin** [comment]
I guess we should just update `browser-natives`? \cc @AlexanderMoskovkin @AndreyBelym

**Comment by AlexanderMoskovkin** [comment]
As I see not just this. We should also replace
`var browserInfo   = installations[alias.toLowerCase()];`
with something like
`var browserInfo = browserNatives.getBrowserInfo(alias)`
[here](https://github.com/superroma/testcafe-phoenix/blob/master/src/runner/bootstrapper.js#L35)

**Comment by inikulin** [comment]
I'm working on this

**Comment by inikulin** [comment]
Closed via #165
