### ISSUE TITLE
Scroll Action request

### ISSUE THREAD

**Issue by ClaytonAstrom** [DevExpress/testcafe#1256]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
DHTMLX grids need to be scrolled by hacky ways, such as adding to the scrollTop value or sending pagedown

### What is the expected behavior?
I should be able to reliable scroll down pages, DHTMLX grids, or objects with an action invocation, similar to `.click` or `.hover`.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:  https://dhtmlx.com/docs/products/dhtmlxGrid/samples/14_loading_big_datasets/01_50000.html

Test code

```js
"use strict";

import { expect } from "chai";
import { ClientFunction, Selector } from "testcafe";

const querySelector = Selector(n => document.querySelector(n));

fixture("DHTMLX grid test")
    .page("https://dhtmlx.com/docs/products/dhtmlxGrid/samples/14_loading_big_datasets/01_50000.html");

test("Scroll to element", async t => {
        const index = "tr:nth-child(200)"; //I know, this doesn't actually select the 200th element.  It's like, 214 or something.  Not really relevant to this
        await t.click(Selector("tr:nth-child(3)"));
        await scrollDown(t, ".objbox", index);
        await t
            .click(index)
            .expect(Selector(index).visible).ok();
    });


const scrollDown = async (t, moveEl, targEl) => {
    const queryVisibleSelector = querySelector.with({
        visibilityCheck: true,
        timeout: .01
    });
    var elTop = await Selector(moveEl).scrollTop;
    var elHeight = await Selector(moveEl).scrollHeight;
    var elTotal = await Selector(moveEl).clientHeight;
    console.log(await queryVisibleSelector(targEl));

    do {
        await t.eval(() => document.getElementsByClassName("objbox")[0].scrollTop += 500);
        elTop = await Selector(moveEl).scrollTop;
        elHeight = await Selector(moveEl).scrollHeight;
        elTotal = await Selector(moveEl).clientHeight;
        console.log(elHeight - elTop, elTotal);
        console.log(await queryVisibleSelector(targEl));
    } while (await queryVisibleSelector(targEl) === null && elHeight - elTop > elTotal);
    return;
}
```

### Specify your

* operating system:  Windows 7
* testcafe version:  0.12.1
* node.js version:  6.9.1

It's also possible I completely missed something in the documentation, apologies if I did!

**Comment by ClaytonAstrom** [comment]
Looks like if element is rendered in the overflow, testcafe has issues scrolling to the element and returns the error, `The element that matches the specified selector is not visible`

**Comment by AlexanderMoskovkin** [comment]
Hi @ClaytonAstrom,

Thanks for the proposal. Your workaround looks ok for now.
I agree, the scroll action will be useful, we need to think out it's api.
What the arguments for the t.scroll action do you expect for your case?

```js
    t.scroll(elementSelector, scrollX, scrollY);
```
?

**Comment by ClaytonAstrom** [comment]
Thanks @AlexanderMoskovkin !

While I thought that might originally work, I'm not sure how universal that would be for other scenarios I'm not thinking of.  Is it possible to instead emulate the mouse wheel scroll action?  Something like `t.mouseUp(y)` and `t.mouseDown(y)` where `x` is the number of times the action is invoked?

That would cover the majority of conventional actions I'd guess, but then you'd probably still need something to scroll along the x-axis, so maybe the arguments you suggested are best.  I'll see if I can find a public example, but I'll at least explain what I'm looking at as best I can:

In our scenario, we use 2 dhtmlx grids side by side.  The mouse wheel moves both of them up and down at the same time, but moving left and right only scrolls the right object (so that you can still see which item that row is).  So by manipulating the objects directly, I may miss the opportunity to test if the mouse wheel functions as I expect on the page.

**Comment by inikulin** [comment]
@ClaytonAstrom Check out https://github.com/DevExpress/testcafe/issues/527, maybe suggest API will fit your needs

**Comment by ClaytonAstrom** [comment]
Thanks @inikulin, that's pretty much exactly what I'm talking about.  I'll close the issue

**Comment by inikulin** [comment]
@ClaytonAstrom Can you add 👍 to #527 then, please? We usually give higher priority to voted issues.

**Comment by lzxb** [comment]
Is the window scrolling operation okay?

**Comment by AlexanderMoskovkin** [comment]
TestCafe performs scroll automatically when you call any action. For example if you need to scroll to some element you can use the [hover](https://devexpress.github.io/testcafe/documentation/test-api/actions/hover.html) action.

**Comment by lzxb** [comment]
ok

**Comment by guptaakhil** [comment]
t.scroll(element, x,y) is failing any time. it's not stablize method , hover would be alternative in this case.

**Comment by shalsabilaf** [comment]
> TestCafe performs scroll automatically when you call any action. For example if you need to scroll to some element you can use the [hover](https://devexpress.github.io/testcafe/documentation/test-api/actions/hover.html) action.

hi @AlexanderMoskovkin our site having issue, not automaticlly scroll down. i've tried **Hover** action, but still not worked. any suggestion? 

thanks.

**Comment by adamgen** [comment]
I know it's an old issue but we do need a scroll event in our project. We have an interface similar to google maps that give different results when scrolling with or without the cmd key pressed.

@AlexanderMoskovkin any thought about this?

**Comment by AndreyBelym** [comment]
@adamgen, I think the scrolling action won't work for your case, you need something that will emulate the mouse wheel to cover your scenario. Your page likely reacts to the `mousewheel` event because it is created when a user tries to scroll a page with the mouse wheel. The programmatic scroll techniques  TestCafe uses for page scrolling create only `scroll` events, like when a user drags the page scrollbar to scroll a page. 

It will be nice if you create a separate issue about introducing the `t.scrollMouseWheel` action and describe your use-case there.

Also if you need the `t.scroll` action too, take a look at the issuehttps://github.com/DevExpress/testcafe/issues/527, I think it provides a better alternative for this proposal.
