### ISSUE TITLE
[Documentation]: Add 'Edit this page on GitHub' link on pages

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#1264]
Some documentation sites allow their customers to edit documentation themselves.
For example: [Telerik](https://www.screencast.com/t/JVw4BgwyF), [AppVeyour](https://www.screencast.com/t/lUA0flYJxfH).
Let's do this for our documentation site.
* testcafe version:0.13.0

**Comment by sirgallifrey** [comment]
[Docker Docs](https://docs.docker.com/compose/) has it too, It's a link that lead to the relevant file on github.

**Comment by titerman** [comment]
This issue is no longer relevant since the TestCafe repo no longer includes the documentation for the product. We'll reconsider this suggestion if we ever create a dedicated open-source documentation repository.
