### ISSUE TITLE
Angular 2 support

### ISSUE THREAD

**Issue by maxmill** [DevExpress/testcafe#1268]
### Are you requesting a feature or reporting a bug?
Reporting a bug

### What is the current behavior?
Unable to query selectors 

### What is the expected behavior?
It should be able to traverse the dom for angular 2 apps

### How would you reproduce the current behavior (if this is a bug)?
create an app using angular-cli (ng new && ng serve). by default, the scaffolder creates an app component that contains an H1 tag. Try selecting that header

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: http://localhost:4200/

Test code

```js
const elementByTagName = Selector((tagName) => document.getElementsByTagName(tagName));

fixture`My fixture`.page`http://localhost:4200/`;

test('it finds a header on the the page', async t => {
    const visibleElement = elementByTagName('h1');
    await t.expect(visibleElement.exists).eql(true, 'app works!');
});
```

### Specify your
 
* operating system: Mac OS X 10.12.3
* testcafe version: 0.12.1
* node.js version: 6.9.5

**Comment by jpicone** [comment]
Thank you for your well-detailed question @maxmill, I also would very much appreciate insight from the github community on this. By the way, is this issue you've noticed happening only in Angular 2, or also when trying to test with TestCafe in other frameworks as well?

**Comment by AlexanderMoskovkin** [comment]
Hi @maxmill,

I've tried to run this test and it works properly on my side (I've tested it on Windows 7, Chrome).
What browser do you use? What error do you see in the report?
Have you added the `import { Selector } from 'testcafe';` line to your test code?

Here is the test code that I run:
```js
import { Selector } from 'testcafe';

const elementByTagName = Selector((tagName) => document.getElementsByTagName(tagName));

fixture`My fixture`.page`http://localhost:4200/`;

test('it finds a header on the the page', async t => {
    const visibleElement = elementByTagName('h1');
    await t.expect(visibleElement.exists).eql(true, 'app works!');
});
```

**Comment by maxmill** [comment]
@AlexanderMoskovkin it looks like it is working. I am using Chrome 58 (dev build) and updated last night - perhaps issue was a result of my environment. I appreciate the the quick response!

**Comment by AlexanderMoskovkin** [comment]
Great news!
