### ISSUE TITLE
JSON reporter returns `screenshotPath: null` if a screenshot path is specified

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#1269]
### Are you requesting a feature or reporting a bug?

bug (created from a [discussion](https://testcafe-discuss.devexpress.com/t/why-json-reporter-returns-screenshotpath-null-when-i-specify-a-screenshot-path-in-cli/177)

### What is the current behavior?

`"screenshotPath": null`

### What is the expected behavior?

`"screenshotPath": "screenshots/..."`

### How would you reproduce the current behavior (if this is a bug)?

run `testcafe chrome test.js -S -s screenshots --reporter json`

#### Provide the test code and the tested page URL (if applicable)

any failed test

### Specify your
* testcafe version: 0.13.0

**Comment by inikulin** [comment]
@AlexanderMoskovkin As far as I can tell should work as expected: https://github.com/DevExpress/testcafe-reporter-json/blob/master/src/index.js#L40. Covered by tests as well: https://github.com/DevExpress/testcafe-reporter-json/blob/master/test/data/report-with-colors#L31 I guess there might be confusion in original post when screenshots are made (e.g. `t.takeScreenshot` is not used)?

**Comment by Rask777** [comment]
Hello,
Here are more details. I get a screenshot path in a report as expected when I run my tests with this command `testcafe chrome test.js  -s screenshots --reporter json`
and inside my test I take a screenshot with `t.takeScreenshot()`

But it returns `screenshotPath": null,` when I want to take a screenshot when test fails and I don't 
use `t.takeScreenshot()` inside my test.
`testcafe chrome test.js -S -s screenshots --reporter json`

**Comment by inikulin** [comment]
Hello @Rask777,
thank you for the details. We'll investigate it.

**Comment by AlexanderMoskovkin** [comment]
I'm working on this
