### ISSUE TITLE
Monitor network requests

### ISSUE THREAD

**Issue by umaar** [DevExpress/testcafe#1270]
### Are you requesting a feature or reporting a bug?

Feature

Many websites make ajax requests to resources which don't affect the page. E.g. Analytics. It can be useful to test when such ajax requests are made e.g.

```js
test.page('Analytics triggers on click', async t => {
    await t.click('.button');
    await t.expect(networkRequests[0].url).eql('https://example.com/analytics');
    await t.expect(networkRequests[0].method).eql('GET');
});
```

But the question is, what's a nice way of getting network requests? e.g.

```js
t.startNetworkRecording('some name');
await t.click('.button');
t.stopNetworkRecording('some name');
const networkRequests = await t.getNetworkRequests('some name');

// or this?

t.addEventListener('onRequest', request => {});
```

If using WebDriver or something, you can normally instruct the browser instance to connect to a proxy, but with Testcafe, I think there is already a proxy (hammerhead) so that could be enhanced to expose all network requests to the test code.

What do you think?

**Comment by inikulin** [comment]
Looks like it can be combined API-wise with #1271. We need to bikeshed it a bit.

**Comment by umaar** [comment]
Mocking is very useful indeed. 

What needs to happen for this to progress? I guess you want to collect the feedback of others?

Thanks for considering it - hopefully the use case makes sense.

**Comment by inikulin** [comment]
Yes, we need some feedback and probably time to figure out the shape of this. Anyway, current sprint is fully packed with features already, so we'll not be able to implement it until the next one.

**Comment by churkin** [comment]
@umaar What if we'll add handler for all proxy requests? For example:
```javascript
test.onRequest(req => {
   var url = req.url;
   ...
})
```
WilI it solve your problem? What request parameters will be useful for you?

**Comment by umaar** [comment]
By the way, I'm not just suggesting this feature for me, but also because I think it will be useful for the testcafe project 👍 

With your example, I'm not sure if it will work.

```js
test.page('Analytics triggers on click', async t => {
  test.onRequest(req => {
     var url = req.url;
     t.expect(url).eql('https://example.com/analytics');
  })
});
```

Because I don't think the test runner will wait for assertions in the `onRequest` callback.

The end goal is to be able to do something like:

```js
await t.expect(networkRequests[0].url).eql('https://example.com/analytics');
```

Which is probably easier accomplished with this?

```js
const networkRequests = await t.getNetworkRequests('recording-label');
```

Because many websites fire ajax requests without changing the UI, the only way you can test for this is by looking at the network requests. Which is the point of this feature request.

As for what data, I'd say as much as you have available e.g. all request headers, URL etc. A regular [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request) object would be good.

**Comment by inikulin** [comment]
I guess I've figure out how it can be done. At first we'll implement [request hooks](https://github.com/DevExpress/testcafe/issues/1341) and provide `RequestLogger` hook with testcafe:

```js
import { RequestLogger } from 'testcafe';

fixture `Fixture`;

test('My test', async t => {
    const logger = new RequestLogger({ logHeaders: true, logBody: false });

    t.addRequestHook(logger);

    // Do something...

    console.log(logger.lastUrl);
    console.log(logger.getRequestsFor('http://example.com/*')[0].headers);
   
    // etc. We can exact API for logger helpers later 
});
```

@umaar What do you think?

**Comment by umaar** [comment]
That looks great! Makes sense to me.

**Comment by miherlosev** [comment]
Done. For more information see the https://github.com/DevExpress/testcafe/issues/1341#issuecomment-386626497
