### ISSUE TITLE
Mock HTTP calls and standard API

### ISSUE THREAD

**Issue by thecodejack** [DevExpress/testcafe#1271]
### Are you requesting a feature or reporting a bug?

Feature

### What is the current behavior?

Wait for Ajax Request responses.

### What is the expected behavior?

Rather waiting for long sometimes as a developer, I want to mock all HTTP calls for faster execution of tests. Something like this (https://github.com/atecarlos/protractor-http-mock) will be very helpful. 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by inikulin** [comment]
Will be implemented with special [request hook](https://github.com/DevExpress/testcafe/issues/1341 `RequestMock`. E.g.:

```js
import { RequestMock } from 'testcafe';

const requestMock = new RequestMock();

requestMock
      .onRequest('http://example.com/*') 
      .filter({ method: 'POST', isAjax: true })
      .respond({
           status: 200,
           body: 'test'
      });
```

fixture `Fixture`
    .useRequestHook(requestMock);

test('My test', () => {
    //...
})

**Comment by thecodejack** [comment]
Looks great. 

How granular mock can become? is It possible to achieve following?
```
mock
      .onRequest('http://example.com/*') 
      .filter({ method: 'POST', isAjax: true, data: {name: 'adi'} })
      .respond({
           status: 200,
           body: 'test1'
      });
     .onRequest('http://example.com/*') 
      .filter({ method: 'POST', isAjax: true, data: {name: 'jack'} })
      .respond({
           status: 200,
           body: 'test2'
      });
      .onRequest('http://example.com/*') 
      .filter({ method: 'GET', isAjax: true, params: {name: 'jack2'} })
      .respond({
           status: 200,
           body: 'test3'
      });
     .onRequest('http://example.com/*') 
      .filter({ method: 'GET', isAjax: true, params: {name: 'jack2', job: 'programmer'} })
      .respond({
           status: 200,
           body: 'test4'
      });
```

**Comment by inikulin** [comment]
@thecodejack Sure

**Comment by tombertrand** [comment]
Hey guys, any update regarding this? or is there a current recommended workaround to mock responses?

**Comment by tombertrand** [comment]
Thanks for the quick reply, I'll give it a try!

**Comment by Matheusbafutto** [comment]
Any updates on this? I use testcafe on a project and mocking would be really useful.

**Comment by rhymes** [comment]
@AlexanderMoskovkin does that work only with "node.js driven" tests?

Because I'm trying using it with [webpack proxy](https://webpack.js.org/configuration/dev-server/#devserver-proxy) but it doesn't work.

I have webpack's proxy configured this way:

```json
{
  proxy: {
      '/api': {
        target: 'http://localhost:5000',
      },
  }
}
```
which enables webpack dev server to talk to the backend running on port 5000.

I tried like this:

```javascript
import { Selector } from 'testcafe'
import nock from 'nock'

import config from '../../../config'

const data = {
  results: [{foo: 'bar'}],
  total: 1,
}

fixture('Result List')
  .beforeEach(() => {
    nock('http://localhost:5000')
      .get(/api$/)
      .reply(200, data)
  })
  .page(`http://localhost:${config.dev.port}/`)


test('Click "Create info"', async (t) => {
  const createLink = await Selector('#create')

  await t
    .click(createLink)
    .expect(Selector('h1').innerText).eql('Create info')
})
```

**Comment by AlexanderMoskovkin** [comment]
Hi @rhymes ,

Actually I haven't checked this case, so it requires some time to try it. If you have some results before please let us know. 
Meanwhile we plan to implement built-in request hooks in the next release (after the current one)

**Comment by miherlosev** [comment]
@rhymes 
Could you please provide a full example that I can run on my computer without writing additional code?
It will allow me to find the reason of the problem quickly.

**Comment by rhymes** [comment]
@miherlosev not really sorry, it was just an experiment. I used a webpack config with the proxy activated and sent a request to a backend.

**Comment by miherlosev** [comment]
Done. For more information see the https://github.com/DevExpress/testcafe/issues/1341#issuecomment-386626497
