### ISSUE TITLE
Add ability to run Google Chrome in the device emulation mode

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#1274]
* testcafe version: 0.13.0

https://developers.google.com/web/tools/chrome-devtools/device-mode/

**Comment by AndreyBelym** [comment]
We can use [chrome-remote-interface](https://developer.chrome.com/devtools/docs/debugging-clients#chrome-remote-interface) to start emulation with the [setDeviceMetricsOverride](https://chromedevtools.github.io/debugger-protocol-viewer/tot/Emulation/#method-setDeviceMetricsOverride).

**Comment by AlexanderMoskovkin** [comment]
It's implemented in #1417. It available in the latest `alpha` version and will be included in the `0.16.0` version.
