### ISSUE TITLE
Process doesn't terminate after tests are finished

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#1284]
see [video](https://www.screencast.com/t/10DA6Z9gn)
If I use npm based run then all works right.

Files to reproduce:
### simple.js
```js
fixture `Simple`;

test('test', async t => {
	await t.click('body');
});
```

###run-simple.js
```js
const createTestCafe = require('testcafe');
let runner           = null;

createTestCafe('localhost', 1337, 1338)
    .then(testcafe => {
        runner = testcafe.createRunner();
    })
    .then(() => {
        return runner
            .src('simple.js')
            .browsers(['chrome'])
            .reporter()
            .screenshots('screenshots')
            .run();
    }).catch((err) => console.log(err));
```

* testcafe version: 0.14.0-alpha2
* node.js version:7.4.0

**Comment by AndreyBelym** [comment]
It happens because you don't call `testcafe.close()`. and the process keeps waiting on opened sockets.

**Comment by miherlosev** [comment]
Ok. Then we should add more details about this in 'Programmic Interface' section.
Something like that - 'Then your tests are finished you should call `testcafe.close()` method to close testcafe connection. Otherwise the process will keep waiting for opened sockets.'
@VasilyStrelyaev

**Comment by VasilyStrelyaev** [comment]
Agree, will do it
