### ISSUE TITLE
Allow relative file URLs for test pages

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#1286]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
Currently we should specify the full URL for `file://` protocol, so to reference test file relative pages you should do something like:
```js
    .page `file://${path.join(__dirname, '../path/to/page.html')}`;
```

### What is the expected behavior?
Check if URL starts with `./` or `../` and resolve relative file URL with `__dirname`.

**Comment by VasilyStrelyaev** [comment]
Should this issue be added to a milestone? Should it have the `documentation: requred` label?
