### ISSUE TITLE
Add ability to run multiple functions in beforeEach hook

### ISSUE THREAD

**Issue by mokone91** [DevExpress/testcafe#1287]
Its can be useful in case if we want execute few actions before each test,

for example : 

- resize window
- login

of course we can create single helper function for this like : 
```
function login({login, password}) {
  return async t => {
    await t
      .resizeWindow(1024, 768)
      .navigateTo("/login")
      .typeText("#email", login)
      .typeText("#password", password)
      .click("button[type='submit']")
  };
}
```

and then : 
`fixture.before(login({login:admin,password:admin}));
`
but in this case we mix 2 actions to 1, and reusing of this action will be not so clear.

its will be nice if we can use it like : 
`fixture.before([resizeWindow(1024, 768), login({login:admin,password:admin})]);`

**Comment by AndreyBelym** [comment]
Hello, Eldar!

What's about [TestController import](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#using-test-controller-outside-of-test-code)? You can write something like this:

helpers.js:
```js
import { t } from 'testcafe';

export async function prepareWindow () {
    await t.resizeWindow(1024, 768);
}

export async function login({login, password}) {
    await t
      .navigateTo("/login")
      .typeText("#email", login)
      .typeText("#password", password)
      .click("button[type='submit']")
}
```

test.js:
```js
fixture `Fixture`
    .page `page.html`
    .before(async () => {
        await prepareWindow();
        await login({login, password});
    });
```

**Comment by mokone91** [comment]
This is exactly what I need!

Thank!
