### ISSUE TITLE
[Raw API]: Unhandled error on running fixture without tests

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#1302]
### 1.testcafe
```js
{
    "fixtures": [
        {
            "name": "1",
            "pageUrl": "http://mail.ru"
        }
    ]
}
```

![Error](https://cloud.githubusercontent.com/assets/4133518/23659691/03fda146-0358-11e7-98bf-4b91b04df9d7.png)

* testcafe version: 0.14.0-alpha3

**Comment by inikulin** [comment]
It's by design. The main purpose of RAW API is that it intended to be created by machine, so we can avoid validation-related burden.

**Comment by inikulin** [comment]
@miherlosev Then you should open issue in studio repo.

**Comment by miherlosev** [comment]
We decide to add in compiler a checking of not well formatted file structure.
