### ISSUE TITLE
Assign custom headers (e.g. JWT Bearer Tokens)

### ISSUE THREAD

**Issue by brettveenstra** [DevExpress/testcafe#1306]
### Are you requesting a feature or reporting a bug?

Feature

### What is the current behavior?

Cannot specify a HTTP header during fixture/test runs

### What is the expected behavior?

Insert a value for any HTTP header for the Fixture or Test scope (e.g. JWT bearer token)

Ideally create a fixture hook that obtains a JWT token from an authentication source and assigns a custom header to future browser traffic (e.g. `Authorization: Bearer JWT.TOKEN.HERE`)

### Specify your

* operating system: Windows & Mac
* testcafe version: 0.13.0
* node.js version: 6.9.1

**Comment by AlexanderMoskovkin** [comment]
Hi Brett,

Thanks for your proposal.
We've discussed the similar question in the https://github.com/DevExpress/testcafe/issues/1125 issue.

Am I understand right your case? To be logged in you need do some actions (e.g. type login + password, click submit). You wouldn't like to do it in each test. 
If so, we are working on the [Implement user roles](https://github.com/DevExpress/testcafe/issues/243) feature that will allow to do logging actions once for all tests. Does it work for you?

**Comment by thecodejack** [comment]
Just to add more, we follow `kerberos` authentication. Most of applications don't even have login pages. So need a way to apply custom headers.

**Comment by inikulin** [comment]
@thecodejack Have you tried [HTTP auth feature](https://devexpress.github.io/testcafe/documentation/test-api/http-authentication.html)? It supports NTLM authentication with which Kerberos is back compatible

**Comment by brettveenstra** [comment]
Thanks I did not see that feature request before.

I suppose a better E2E testing approach that covers our needs would be to support a Fixture-based hook that starts wth login and still allows the clean .page method.  I wasn't seeing a way to automate our logging screens and begin at the correct URL.  

This is for a SPA so I was assuming it would be easier to obtain a token and pass through the test context before starting browser automation steps.

Which approach would you advise (hook vs headers)?

**Comment by thecodejack** [comment]
@inikulin That's very quick response.

Reg NTLM. Yes. I have NTLM. But no luck. it is logging out.

**Comment by inikulin** [comment]
@brettveenstra If I understood you correct, upcoming Roles feature suggested by @AlexanderMoskovkin should fit your requirements.

**Comment by AlexanderMoskovkin** [comment]
@thecodejack I've created an [issue](https://github.com/DevExpress/testcafe/issues/1309) for the problem with kerberos, we'll try to found the reason and fix it.

**Comment by thecodejack** [comment]
Thanks @AlexanderMoskovkin .

**Comment by brettveenstra** [comment]
@inikulin: that should cover this request. Thanks

**Comment by AlexanderMoskovkin** [comment]
As I see the requested case can be covered via [User Roles](https://devexpress.github.io/testcafe/documentation/test-api/authentication/user-roles.html) or [Request Hooks](https://github.com/DevExpress/testcafe/issues/1341), so I close it as a duplicate. If I'm wrong feel free to comment or reopen the issue.
