### ISSUE TITLE
id selector

### ISSUE THREAD

**Issue by dai875939260** [DevExpress/testcafe#1307]
hi,when i use
`switchToIframe('#4028821255e860e70155e8c3712c00eb')`
,it tells me SyntaxError,how to reslove it ?

**Comment by inikulin** [comment]
Hi,

id selectors that start with digit are forbidden by CSS spec. Possible workarounds for the issue can be found in this article: https://benfrain.com/when-and-where-you-can-use-numbers-in-id-and-class-names/
