### ISSUE TITLE
HTTP Authentication doesn't work for Kerberos

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#1309]
Created from the [discussion](https://github.com/DevExpress/testcafe/issues/1306#issuecomment-286345658). 

> @thecodejack:
Just to add more, we follow `kerberos` authentication. Most of applications don't even have login pages. So need a way to apply custom headers.

> @inikulin:
Have you tried [HTTP auth feature](https://devexpress.github.io/testcafe/documentation/test-api/http-authentication.html)? It supports NTLM authentication with which Kerberos is back compatible

> @thecodejack:
Reg NTLM. Yes. I have NTLM. But no luck. it is logging out.

**Comment by zhaighin** [comment]
Can this bug be fixed asap? I have been waiting the fix since the ticket created.

**Comment by churkin** [comment]
Hi @zhaighin, Unfortunately it is very difficult to implement `Kerberos` authentication in the testcafe. It has a very complex mechanism to generate authentication tokens and at the moment there is no complete universal nodejs module for this. All we can do is add the ability to set `Authentication` header value that you will need to generate yourself. For this we have created #1306 issue. At the moment we can't suggest you another solution.

**Comment by AlexanderMoskovkin** [comment]
According to the last comment I close it as a duplicate for #1341
