### ISSUE TITLE
Add support for ShadowDOM

### ISSUE THREAD

**Issue by varunkumar** [DevExpress/testcafe#1312]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
`typeText` doesn't seem to be working on an element present inside ShadowDOM. I had written a custom selector to pickup an element inside the ShadowDOM. However, I am not able to type text into it. I am assuming that other actions also won't work with elements inside ShadowDOM.

### What is the expected behavior?
Should be able to perform all actions on elements inside ShadowDOM as well.

### How would you reproduce the current behavior (if this is a bug)?
* Create a simple custom element with text box inside its ShadowRoot. 
* Select the textbox using custom selector
* `typeText` with some data. 
* Nothing is happening

#### Test code and page URL

Tested page URL: http://output.jsbin.com/mefabikeqa

Test code

```js
import {
  Selector
} from 'testcafe';

fixture `Web components test`
  .page `http://output.jsbin.com/mefabikeqa`;

test('Test ShadowDom', async t => {
  await Selector('#host');
  const textBox = await Selector(() => document.querySelector('#host').shadowRoot.querySelector('#txtTest'));
  await t
    .typeText(textBox, 'Some text')
    .expect(textBox.value).eql('Some text');
});
```

### Environment details

* operating system: Windows 7.0.0
* testcafe version: 0.13.0
* node.js version: v6.2.2

**Comment by AndreyBelym** [comment]
Hello @varunkumar! I can confirm your issue, working on the fix now.

**Comment by AndreyBelym** [comment]
Hello @varunkumar! We've just released the new TestCafe alpha version that fixes your issue. You can try it by executing `npm install testcafe@alpha`. Feel free to reopen the issue if the fix didn't help you!

**Comment by varunkumar** [comment]
Thanks. Will check and get back.

**Comment by varunkumar** [comment]
This is working as expected. However, I noticed an issue with scrolling when the element is not in view. Logged #1808 for that. I will see if I can provide an PR for this.

**Comment by AlexanderMoskovkin** [comment]
@varunkumar feel free to contribute.
