### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded on rumbo site

### ISSUE THREAD

**Issue by Axel92Dev** [DevExpress/testcafe#1318]
### Are you requesting a feature or reporting a bug?
Reporting a bug

### What is the current behavior?
When i try to run:
```
fixture `Getting Started`
    .page `https://secure.rumbo.com/account`;
```
 Uncaught RangeError: Maximum call stack size exceeded is returned
If i try with other websistes, it works

### What is the expected behavior?
To pass the test

### How would you reproduce the current behavior (if this is a bug)?
Just run the code i provided with testcafe cli

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://secure.rumbo.com/account

Test code

```js
fixture `Getting Started`
    .page `https://secure.rumbo.com/account`;
```

### Specify your

* operating system: Chrome 56.0.2924 / Mac OS X 10.11.6
* testcafe version: latest
* node.js version: v7.4.0

**Comment by churkin** [comment]
This bug has been fixed at https://github.com/DevExpress/testcafe-hammerhead/issues/1055

**Comment by churkin** [comment]
@Axel92Dev Please, try `0.14.0-alpha3` version. I think it does not have your problem.
