### ISSUE TITLE
SauceLabs integration: report test status (success/fail) to the SauceLabs service

### ISSUE THREAD

**Issue by tsv2013** [DevExpress/testcafe#1320]
### Are you requesting a feature or reporting a bug?

A feature

### What is the current behavior?

After test job has been completed, SauceLabs task status is "unknown".
"This status is set if one or more jobs of the latest build haven't been reported as passed or failed. This state is equivalent to Finished."

### What is the expected behavior?

Test results status is reported to the SauceLabs service.

#### Provide the test code and the tested page URL (if applicable)

https://github.com/surveyjs/surveyjs

Take a look to the sauce labs test status badge.

**Comment by tsv2013** [comment]
Please check the [Annotating Tests with the Sauce Labs REST API](https://wiki.saucelabs.com/display/DOCS/Annotating+Tests+with+the+Sauce+Labs+REST+API) article.
Also an option to make test results public could be helpful.

**Comment by inikulin** [comment]
@AndreyBelym Can you take a look, please?

**Comment by AndreyBelym** [comment]
Ok, so we should perform a request to the SauceLabs REST API when tests are finished to set the status of the SauceLabs session to passed/failed. It requires some interaction between reporter and browser provider.
