### ISSUE TITLE
SauceLabs task fails if testcafe trying to start tests in several browsers

### ISSUE THREAD

**Issue by tsv2013** [DevExpress/testcafe#1322]
### Are you requesting a feature or reporting a bug?

A bug

If tests are running on two browsers, connection with SauceLabs is Ok
If browsers count is more than 2, TestCafe loose connection to SauceLabs service

### What is the current behavior?

ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.

### What is the expected behavior?

90 passed (3m 41s)
The command "testcafe chrome testCafe/" exited with 0.

### How would you reproduce the current behavior (if this is a bug)?

testcafe "saucelabs:Chrome@56.0:Windows 10,saucelabs:MicrosoftEdge@14.14393:Windows 10,saucelabs:Internet Explorer@11.103:Windows 10,saucelabs:Chrome@48.0:Linux" testCafe/

#### Provide the test code and the tested page URL (if applicable)

Repo:
https://github.com/surveyjs/surveyjs
Travis build log:
https://travis-ci.org/surveyjs/surveyjs/builds/211664344

**Comment by inikulin** [comment]
\cc @AndreyBelym take a look pls

**Comment by AndreyBelym** [comment]
It doesn't related to the browser count, as you can see: https://travis-ci.org/AndreyBelym/surveyjs#L2615.

**Comment by tsv2013** [comment]
@AndreyBelym Yes, this is the expected behaviour. But in my log I've got completely another error. Not errors in tests, but "Unable to establish one or more of the specified browser connections.". SauceLabs tasks start ok, but no feedback to the testcafe running under TravisCI.

**Comment by tsv2013** [comment]
@AndreyBelym In our SauceLabs account we have two concurrent sessions. This may be the reason why 2 is the magic number here.

**Comment by AndreyBelym** [comment]
Oh now I see. So we have to check that the number of requested browsers doesn't exceed the concurrency limit, and throw a meaningful error if it isn't so.

**Comment by AndreyBelym** [comment]
Looks like it's very hand to implement session-balancing on the TestCafe. It's better to split requested browsers manually, and then use it like `testcafe browser1,browser2 tests; testcafe browser3,browser4 tests;...`. So showing an error that too much browsers was requested is the best thing that we can do.
