### ISSUE TITLE
Stop test task on first failed test (`--bail`)

### ISSUE THREAD

**Issue by darlanmendonca** [DevExpress/testcafe#1323]
### Are you requesting a feature or reporting a bug?
feature

### What is the current behavior?
when a test fail, the process continues, will be good if have a option to stop to dont have an avalanche of test errors, just the first in focus (reference `mocha --bail`)

### What is the expected behavior?
fails whole task once there is an error in the test, like `mocha --bail`

**Comment by chinjon** [comment]
Is there any progress on this feature? I was also wondering if there is any way to "catch" a failed assertion within a `test` or return some sort of value.

**Comment by karolisgrinkevicius** [comment]
I'd also really love to have such feature. @chinjon have you solved this somehow already? If so please share your implementation since we could patch the module in a meanwhile.

**Comment by chinjon** [comment]
@karolisgrinkevicius I have not as of yet still. I did some experimentation. Essentially I perform a conditional with the assertion I am performing. This is not the exact code I used, but this should work (haven't tested).

This is by far not an optimal solution, but something that came to mind while I was experimenting. I also explored with `exit codes` but haven't came up with a good solution either. 

Thank you for your interest in this feature.

```js
test(`test #1`, async t => {
  if (await (Selector('.nexttt-button').exists) === false) {
     await (Selector('.nexttt-button').exists) // this should throw error to CLI
     process.kill(process.pid); // this should kill current process
  }
})

// should not run
test(`test #2`, async t => {
  if (await (Selector('.nexttt-button').exists) === false) {
     await (Selector('.nexttt-button').exists)
     process.kill(process.pid);
  }
})
```

**Comment by row1** [comment]
This would also be useful when you have a lot of tests for application state and you want to diagnose the current state that the application is in when it failed. For example I have a fixture that passes when run by itself, but it fails when a certain number of fixtures before it have run. Subsequent fixtures seem to fix the state, so it would be good to abort the test at the first failure so that I can login and inspect the application state.

**Comment by AndreyBelym** [comment]
@row1 I think for the use case you described it will be better to switch TestCafe to the [debug mode](http://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-d---debug-mode) when a test fails.

**Comment by chinjon** [comment]
@AndreyBelym Can we have something like `debug on fail` but without the GUI and pause functionality? A full test could be comprised of 50+ tests of numerous fixtures. It'd be useful to immediately understand there is an error immediately. Might be a niche request, but thank you for considering it.

**Comment by AndreyBelym** [comment]
Hi @chinjon, I agree that the fast fail (or bail) mode is a very useful feature. But currently we are working on improving our infrastructure and increasing overall stability of TestCafe, so implementing new features is not the first priority for some time. But of course we will be happy to accept a PR, as always 😉

**Comment by chinjon** [comment]
@AndreyBelym noted. Thank you for `TestCafe` and the continued active development.

**Comment by row1** [comment]
@AndreyBelym I run the 100+ tests on a separate machine where debugging isn't ideal. But since the debug flag will pause the execution, it should maintain the state and allow me to login to the website from my PC and observe the issue, so this could be a suitable workaround. Thanks for your help.

**Comment by karolisgrinkevicius** [comment]
Already tried that but it seems not to be working with `testcafe@0.22.0`.

Run on:
```
Chrome 68.0.3440 / Mac OS X 10.13.6
```

Do you have an example with this option of working e2e tests?

**Comment by miherlosev** [comment]
@karolisgrinkevicius 

`testcafe@0.22.0` doesnot include this feature. `Stop task on failed` feature will be  available in the next  TestCafe version (major, minor or alpha).
