### ISSUE TITLE
Feature Request: flow type checker support

### ISSUE THREAD

**Issue by zenoplex** [DevExpress/testcafe#1329]
### Are you requesting a feature or reporting a bug?

Feature

Can you add [babel-plugin-transform-flow-strip-types](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-flow-strip-types) so test code can be type checked with flow?

**Comment by AndreyBelym** [comment]
=== Summary
Flow is stand-alone type checker for JS by Facebook: https://flow.org/

1. Install flow
```
npm install flow-bin
```

2. Create `testcafe.js` file in `${PROJECT_ROOT}/flow-typed`:
```
declare var fixture: any;
declare var test: any;
```

3. Add a `// @flow` comment at  the begging of each of your test files and also add type definitions, e.g. https://github.com/DevExpress/testcafe/blob/master/test/server/data/test-suites/flow-type-declarations/testfile.js, https://github.com/DevExpress/testcafe/blob/master/test/server/data/test-suites/flow-type-declarations/rocket.js

4. `./node_modules/.bin/flow`
