### ISSUE TITLE
jsdom, DOM access

### ISSUE THREAD

**Issue by darlanmendonca** [DevExpress/testcafe#1344]
### Are you requesting a feature or reporting a bug?
anyone, is a DOUBT

has a way to get the entire html markup?

I'm looking a way to use testcafe with jsdom, and not found anything in test controller :( (an docs, google, etc)

**Comment by AndreyBelym** [comment]
You can use
```js
import { ClientFunction } from 'testcafe';

const getPageHTML = ClientFunction(() => document.documentElement.innerHTML);

test('Test', async t => {
    var html = await getPageHTML();
});
```

**Comment by darlanmendonca** [comment]
awesome!!

thank you so much  @AndreyBelym !!
