### ISSUE TITLE
Question: google oauth client side

### ISSUE THREAD

**Issue by nihaux** [DevExpress/testcafe#1368]
Trying to use testcafe on my company SPA (react).
The login use google oauth in javascript.
It seems that the callback which is supposed to be called after successfull login is not called
Am I missing sth ?

**Comment by inikulin** [comment]
Hi @nihaux, did you manage to resolve the issue on your side?

**Comment by nihaux** [comment]
I forgot to whitelist the ip/port testcafe is using in google dev console. :)
However, I had another issue related to localstorage, for the next login step.
I'll open a new issue if I can't figure it out, but given this code:


test('My Test', async t => {   
  const localStorageSet = ClientFunction((key, val) => localStorage.setItem(key, val));
  await localStorageSet('bone.jwt', jwt);
  await t
    .debug()
    .expect(currentSite.exists).ok('show vsd');
});


and this code in my app:
`
console.log(window.locaStorage, window.localStorage.getItem('bone.jwt'), window.localStorage['bone.jwt']);
`

window.localStorage contains my data but neither getItem or direct access returns a value.

**Comment by inikulin** [comment]
@nihaux Are you trying to evaluate `getItem` from console?
