### ISSUE TITLE
Allow using dragToElement if target element appears on drag-start event or moves while dragging

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#1374]
### Are you requesting a feature or reporting a bug?
Feature (from StackOverflow question [TestCafe DragNDrop Not Good Enough](http://stackoverflow.com/questions/43207684/testcafe-dragndrop-not-good-enough))

### What is the current behavior?
- [ ] We can't drag an element to another element if the target element appears just on `drag-start` event (it's hidden or non-existing before the event). 
- [ ] If the target element moves after drag is started, we cannot detect it and adjust the final drag coordinates.

### What is the expected behavior?
The `dragToElement` action should emit `drag-start` event before determining the target element.

**Comment by xMort** [comment]
Is there any workaround until this gets implemented correctly?

**Comment by tipy01** [comment]
I had that on an app that need scrolling to show the destinationSelector.
My weak workaround is to t.hover on destinationSelector  (this will scroll to destinationSelector) before dragToElement .
Without that it behaves like if the mouseup event on drop is never fired.

**Comment by Artem-Babich** [comment]
Hello,

We decided not to implement this behavior since it can be different and strongly depends on a specific web app implementation. You can implement the desired behavior using the [t.dispatchEvent](https://testcafe.io/documentation/403091/reference/test-api/testcontroller/dispatchevent) action. Here is an example of emulating the dragstart event before dragging:

```js
// .testcaferc.js
const { Selector } = require('testcafe');

module.exports = {
    customActions: {
        dragToElement: async function (...args) {
            const dragElement = args.shift();
            const targetElement = args.shift();

            const eventArgs = {
                cancelable: true,
                bubbles:    true,
            };

            const options = Object.assign(
                { eventConstructor: 'DragEvent' },
                eventArgs,
            );

            await this
                .dispatchEvent(dragElement, 'dragstart', options)
                .expect(Selector(targetElement).exists).ok()
                .dragToElement(dragElement, targetElement, ...args);
        }
    }
}
```
```js
// test.js

import { Selector } from 'testcafe';

fixture`Fixture 1`
    .page('./index.html');

test('Test 1', async t => {
    await t.customActions.dragToElement('#dragElement', '.zone')
        .expect(Selector('#result').innerText).eql('DROPPED')
});
```

Feel free to reopen this issue and share appropriate details if this approach is not suitable.
