### ISSUE TITLE
Try to exit gracefully on SIGINT

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#1378]
### Are you requesting a feature or reporting a bug?
feature

### What is the current behavior?
TestCafe terminates leaving browsers open

### What is the expected behavior?
Try to terminate running tasks gracefully and only after some timeout terminate process if
it didn't work

**Comment by inikulin** [comment]
Proposed strategy:
1. Try to call `task.abort()` in CLI on `SIGTERM` and `SIGINT`
2. After some considerably big timeout forcefully terminate the process.
3. If `SIGTERM` or `SIGINT` was raised second time then forcefully terminate the process.

\cc @AndreyBelym

**Comment by AlexanderMoskovkin** [comment]
I reopen this since it works when you run build and run `testcafe` from sources, but doesn't work when you run globally installed `testcafe`.

**Comment by miherlosev** [comment]
It is not working on `testcafe@0.17.0@alpha-5`.
https://www.screencast.com/t/ob1S43IJ

**Comment by inikulin** [comment]
@AlexanderMoskovkin It's because we spawn another process in CLI and this parent process receives SIGINT, not the actula testcafe. We need just to pass it to the child process.

**Comment by inikulin** [comment]
It uses my `v8-flag-filter` module: https://github.com/DevExpress/testcafe/blob/master/bin/testcafe-with-v8-flag-filter.js#L8

Hmm, but seems like it already do signal redirection:
https://github.com/inikulin/bin-v8-flags-filter/blob/master/index.js#L62

**Comment by inikulin** [comment]
Oh, seems like the problem is that in `v8-flag-filter` we send `SIGTERM` immediately after `SIGINT`. It expects program to terminate synchronously. @AlexanderMoskovkin I'll add you as a co-maintainer to module on github and npm, so you will be able to fix it.

**Comment by AndreyBelym** [comment]
It happens because `process.kill` doesn't work properly on Windows, it just silently terminate the child process: https://github.com/nodejs/node/issues/12378. PM2 (popular process manager for Node.js https://www.npmjs.com/package/pm2) uses special `shutdown` message on Windows: http://pm2.keymetrics.io/docs/usage/signals-clean-restart/#windows-graceful-stop. IMHO we can use it in our case.

**Comment by AlexanderMoskovkin** [comment]
`bin-v8-flags-filter@1.1.0` is released
