### ISSUE TITLE
Can't install testcafe against GitHub URLs

### ISSUE THREAD

**Issue by FrankV01** [DevExpress/testcafe#1380]
### current behavior
I'm wanting to use a later version of testcafe then what is npm, so I've installed it against the github version (this repository) like: 

```  
"dependencies": {
    "jsdoc": "^3.4.3",
    "jsdoc-strip-async-await": "^0.1.0",
    "testcafe": "DevExpress/testcafe#v0.15.0-alpha1"
  }
```

It installed as expected but when I attempt to run the program, I am given 

```

> PortalTestCafe@1.0.0 test C:\Users\fvillase\WebstormProjects\Portal-TestCafe
> node index.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'testcafe'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\fvillase\WebstormProjects\Portal-TestCafe\index.js:1:86)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! Test failed.  See above for more details.

```

### Expected behavior
On the other hand, if install with `npm install --save testcafe`, and hence have `"testcafe": "^0.14.0"` in my package it works.  Everything else is exactly the same. Just changed out the testcafe version. 

To reproduce it create a package node package and install testcafe as I have it above. Make a basic test and runner and problem will occur. 

* operating system: Windows 7 x64
* testcafe version: v0.15.0-alpha1 and v0.14.0
* node.js version:  v6.10.2

**Comment by FrankV01** [comment]
Relevant documentation: https://docs.npmjs.com/files/package.json#github-urls

Also, I tried master for LOLs. Indeed, the problem exists with master as well.

**Comment by inikulin** [comment]
Hello, we don't support installs from GitHub and don't plan to implement it. Any valuable changes between major release are published in `alpha` channel and can be installed via `npm install testcafe@alpha`
