### ISSUE TITLE
Incorrect click emulation on monaco code editor

### ISSUE THREAD

**Issue by kirovboris** [DevExpress/testcafe#1385]
### Are you requesting a feature or reporting a bug?
bug

### What is the current behavior?
TestCafe doesn't set the cursor position in monaco editor at during click action.

#### Provide the test code and the tested page URL (if applicable)
```js
import { Selector } from 'testcafe';

fixture `Monaco test`.page('https://microsoft.github.io/monaco-editor/playground.html');

test('Set cursor position', async t => {
	const seventhLine = Selector('.monaco-editor .view-line').nth(7);
		
	await t.click(seventhLine, { offsetX: 10, offsetY: 5 });
	
	const cursor = Selector('.cursors-layer .cursor');	
	
	await t
		.expect(cursor.getAttribute('linenumber')).eql(7)
		.expect(cursor.getAttribute('column')).eql(1)
});
```

### Specify your

* operating system: win 7
* testcafe version: 0.14.0
* node.js version:  6.5.0

**Comment by AlexanderMoskovkin** [comment]
I'm working on this

**Comment by AlexanderMoskovkin** [comment]
Waiting for https://github.com/DevExpress/testcafe-hammerhead/issues/1084

**Comment by AlexanderMoskovkin** [comment]
It's fixed after Hammerhead is updated to v10.6.5 (#1414). I'll close the issue when I add a functional test

**Comment by TestAndunR** [comment]
Hello, 
Does typeText() method works for monaco code editor in a web application

**Comment by AndreyBelym** [comment]
@TestAndunR, yes, it works. Do you have a page which has a problem with `typeText`?

**Comment by TestAndunR** [comment]
Hi @AndreyBelym ,
Yes I'm working with an online IDE.  And followig is the code i used. typeText() method did not worked in this scenario
```import { Selector } from 'testcafe';
fixture`Login and Creating a new Project`



.page`https://sigma.slappforge.com`

test('write on monaco editor',async t=> {
    const resourceElement = await Selector('.mtk1').withText("event").with({ visibilityCheck: true })();
    await t
        .typeText(Selector('input[name=email]'), 'username')
        .typeText(Selector('input[name=password]'), 'password')
        .click(Selector('button[type=button]'))
        .typeText(Selector('input[name=projectName]'), "TestCafeProject")
        .click(Selector('button[type=button]'))
        .wait(5000)
        .click(Selector('.view-line').nth(3))
        .typeText(Selector('.view-line').nth(3),"asas");
})```

**Comment by AndreyBelym** [comment]
@TestAndunR, thanks for the test, I'll check it.
