### ISSUE TITLE
"Input" event is raised with wrong selection value when input value was changed

### ISSUE THREAD

**Issue by kirovboris** [DevExpress/testcafe#1388]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

`.pressKey('enter')` works incorrect, content inserts a part of code instead of new line.

#### Provide the test code and the tested page URL (if applicable)

Test code

```js
fixture `Monaco test`.page('https://microsoft.github.io/monaco-editor/playground.html');

test('Enter button handler', async t => {
        //Some extra steps as workaround for #1385
	for(var i=0; i< 10; i++) {
		await t.pressKey('tab');
		await t.wait(500);
	}
	
	for(var i=0; i< 10;i++) {
		await t.pressKey('enter');
		await t.wait(500);
	}
});
```

### Specify your

* operating system: win 7
* testcafe version: 0.14.0
* node.js version: 6.5.0

**Comment by AlexanderMoskovkin** [comment]
I'm working on this

**Comment by kirovboris** [comment]
It's still not fixed. I've tried testcafe@0.16.0-alpha1. Watch video
https://www.screencast.com/t/GcOGmAGai

**Comment by AlexanderMoskovkin** [comment]
After some investigation I've found the initial problem is successfully resolved.
I've reproduced the problem from the video in the previous comment and I've created a separated issue for it: https://github.com/DevExpress/testcafe/issues/1499
