### ISSUE TITLE
if - else

### ISSUE THREAD

**Issue by mjhea0** [DevExpress/testcafe#1391]
Before I submit a full issue, is there a better way of handling if/else logic..

```javascript
const getDropdownListItem = ClientFunction(() => {
  const elementList = document.getElementsByClassName('dropdown-wrapper');
  const filterList = Array.prototype.slice.call(elementList).filter((el) => {
    return el.innerText === 'SOMETHING';
  });
  if (filterList.length) {
    return true;
  }
  return false;
});

...

if (await getDropdownListItem()) {
  console.log('do something');
}
else {
   console.log('do something else');
}
```

**Comment by inikulin** [comment]
@mjhea0 
Use selectors:
```js
const dropdown = Selector('.dropdown-wrapper').withText('SOMETHING');

if (await dropdown.exists) 
   //...
```

**Comment by mjhea0** [comment]
Yes, I tried that. Even though `dropdown.exists` is a boolean, it always evaluates to falsey. When I use my approach it works fine. Ugh.

**Comment by inikulin** [comment]
Interesting, can you provide tested markup, please?

**Comment by gpsarkar** [comment]
@mjhea0 I faced a similar issue last night, but then found that the selector was returning multiple items and was processing result from some hidden element instead of the one i was expecting. I then refined the selector to pin point that particular element and then the test worked fine.

**Comment by mjhea0** [comment]
@gpsarkar yes, that may be what's happening. I'll dig in today. Thanks!

**Comment by mjhea0** [comment]
Yes, it was returning multiple items. Closing the issue. Thanks!
