### ISSUE TITLE
Ngrok support

### ISSUE THREAD

**Issue by YacheLee** [DevExpress/testcafe#1393]
Currently, I can't find ways to test browsers that are not in my LAN.
Do you have any plan to support ngrok?

**Comment by AndreyBelym** [comment]
Hello @YacheLee! Currently we don't support ngrok, The best way in this case is using VPN-based solution, like [Hamachi](https://www.vpn.net/) to create virtual network.

However, if you really want to use ngrock, it's possible but with some limitations:
 - Cross-domain iframes are not supported
 - TestCafe  needs to be started at port `80`
 - This way requires editing `hosts` file.

So, 

 1. Start `ngrok http 80`. Store you public url somewhere. I will refer to it as `ngrok-url`. Do not include `http://` or `https://` in `ngrock-url`.

 2.  Append `127.0.0.1 ngrock-url` to the `hosts` file. The full file path is `C:\Windows\System32\drivers\etc\hosts` on Windows and `/etc/hosts` on macOS and Linux.

 3. Start TestCafe as `testcafe remote --hostname ngrock-url --ports 80,81 test.js`

 4. Open the url provided by TestCafe in a remote browser.
