### ISSUE TITLE
Add info about relative paths to 'Test Static HTML Pages' article

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#1394]
We supports relative paths to test static pages (from `0.14.0` version).
```js
fixture `MyFixture`
    .page `../my-project/index.html`;
```

Add info about this to [Test Static HTML Pages](http://devexpress.github.io/testcafe/documentation/recipes/test-static-html-pages.html) article

**Comment by VasilyStrelyaev** [comment]
Will do this
