### ISSUE TITLE
Setting Chrome's user-agent from a CLI parameter

### ISSUE THREAD

**Issue by baens** [DevExpress/testcafe#1406]
### Are you requesting a feature or reporting a bug?
I believe a bug (though, it may be me using it wrong)

### What is the current behavior?
The test runner does startup (I expect it's because of a missing quote)

```
ERROR Was unable to open the browser “locally-installed:chrome --user-agent=Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Mobile Safari/537.36” due to error.

Unable to run the browser. The file at /Applications/Google Chrome.app does not exist or is not executable.

Type “testcafe -h” for help.
```

### What is the expected behavior?
Chrome starts up with my user-agent

### How would you reproduce the current behavior (if this is a bug)?
Run the command like this:

`testcafe “chrome --user-agent=‘Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Mobile Safari/537.36’” test1.js`

### Specify your

* operating system: Mac OS X 
* testcafe version: 0.14.0
* node.js version: 7.4.0

**Comment by AlexanderMoskovkin** [comment]
Hi @baens,

It seems the terminal can't handle the arguments as you expect. It works on my side if I escape some symbols (`;` ` ` `)`):
```sh
testcafe "chrome --user-agent='Mozilla/5.0\ \(Linux\;\ Android\ 5.0\;\ SM-G900P\ Build/LRX21T\)\ AppleWebKit/537.36\ \(KHTML,\ like\ Gecko\)\ Chrome/57.0.2987.133\ Mobile\ Safari/537.36'" test.js
```

**Comment by baens** [comment]
Thank you @AlexanderMoskovkin! That is what I was looking for. Didn't realize that I needed to escape in the string itself.

BTW, if there was a flag or something I could pass into testcafe to do this automatically, that would be awesome, but for now, this works!

**Comment by inikulin** [comment]
@baens Command line arguments resolution happens on terminal level, before hitting any testcafe code. There is nothing we can do with it.
