### ISSUE TITLE
Tab focusing starts from page start even after click on an element in the middle of a page

### ISSUE THREAD

**Issue by romanresh** [DevExpress/testcafe#1408]
### Are you requesting a feature or reporting a bug?
bug

### What is the current behavior?
After click on an element in the middle of a page and pressing the 'tab' key a browser focuses the first element on the page

### What is the expected behavior?
After click on an element in the middle of a page and pressing the 'tab' key a browser SHOULD focus the next (after clicked element) nearest active element on the page.

### How would you reproduce the current behavior (if this is a bug)?
1. Open "https://demos.devexpress.com/aspxgridviewdemos/Accessibility/ComplianceEditing.aspx". 
2. Click on the GridView's caption ("Products").
3. Press "TAB"
4. Native browser will focus the 1st table header (Product Name) but testcafe will focus the 1st active element on the page (and you will see the large "Skip to Main Element" page header).

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://demos.devexpress.com/aspxgridviewdemos/Accessibility/ComplianceEditing.aspx

Test code

```js
fixture `test`
    .page `https://demos.devexpress.com/aspxgridviewdemos/Accessibility/ComplianceEditing.aspx`
test("Wrong tab focusing after click", async t => {
    await t
        .click("#ContentHolder_grid_DXHeaderTable")
        .pressKey("tab")
        .expect(Selector("#ContentHolder_grid_col1 a").focused).ok();
});
```

### Specify your

* operating system: Windows 10
* testcafe version: 0.14.0

**Comment by helen-dikareva** [comment]
After click on GridView's caption ("Products") page's `activeElement` was not changed. So our algoritm for `tab` pressing detect next element for focusing from the start of the page.
It seems like browser have some logic of detection next element for focusing not only by information about `activeElement`. We need take it into account.
BTW workaround for your case is click and change `activeElement`:
```js
import { Selector } from 'testcafe';

fixture `test`
    .page `https://demos.devexpress.com/aspxgridviewdemos/Accessibility/ComplianceEditing.aspx`;

test("Wrong tab focusing after click", async t => {
    await t
       //click on radio button (it's checked already)
        .click('#ContentHolder_rblEditMode_RB0_I_D')
        .pressKey("tab tab")
        .expect(Selector("#ContentHolder_grid_col1 a").focused).ok();
});
```

**Comment by helen-dikareva** [comment]
We've investigated this issue and decided to close it because:
1) this behavior is not described in specification
2) FF has own bahavior for this case
3) it's pretty uncommon case
4) we found simple workaround

We will be able to reopen this issue if it would be required.
