### ISSUE TITLE
Drag not working

### ISSUE THREAD

**Issue by sagarvora** [DevExpress/testcafe#1409]
### Are you requesting a feature or reporting a bug?

A bug.

### What is the current behavior?

The `drag` method is not working as expected.

### What is the expected behavior?

It should drag the Task icon.

### How would you reproduce the current behavior (if this is a bug)?

By executing below code.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://demo.erpnext.com/

Test code

```
import { Selector } from 'testcafe';

fixture `Example page`
    .page `http://demo.erpnext.com`;

test('Check login', async t => {
    const login_btn = Selector('#login_btn');
    const task_icon = Selector('.case-wrapper[data-link="List/Task"]');

    await t
        .click(login_btn)
        .drag(task_icon, 360, 0, { offsetX: 50, offsetY: 20, speed: 0.3 })
});

```

### Specify your

* operating system: OS X
* testcafe version: 0.14.0
* node.js version: 7.5.0

**Comment by inikulin** [comment]
@sagarvora Unfortunately, tested page is unreachable, therefore we'll not be able to reproduce the problem. Is it possible to provide page that is publicly available? If not, we can sign NDA and communicate via private medium.

**Comment by sagarvora** [comment]
@inikulin I have update the code and above issue. You can test it now.

**Comment by helen-dikareva** [comment]
Thank you for the good catch. It's a known problem: we need to add support for HTML5 drag & drop simulation (please [see the corresponding issue](https://github.com/DevExpress/testcafe/issues/897)).
We've decided to add a fix for this issue in one of the upcoming releases.

**Comment by sagarvora** [comment]
Thanks @helen-dikareva! I am looking forward to this being fixed. Really liked your team's prompt response.

**Comment by inikulin** [comment]
I'm closing this one as duplicate, to track updates refer to #897.
