### ISSUE TITLE
Screenshots do not work in TestCafe with Headless Chrome

### ISSUE THREAD

**Issue by jimthedev** [DevExpress/testcafe#1411]
### Are you requesting a feature or reporting a bug?
Reporting a bug

### What is the current behavior?
The current behavior is that no screenshot is generated and a warning is thrown in the terminal:

```

 Warnings (1):
 --
  Was unable to take a screenshot due to an error.

  Command failed:
  /Users/MYUSERNAME/projects/angular1-systemjs-seed/node_modules/testcafe-browser-tools/bin/mac/screenshot
  SkQPrdfAe
  /Users/MYUSERNAME/projects/angular1-systemjs-seed/test/testcafe/shots/Users/jim.cummins/projects/angular1-systemjs-seed.png
  There are no TestCafe windows

```

### What is the expected behavior?

I would expect testCafe to use Chrome's Debugging Protocol to take a screenshot.

The Chrome Debugging Protocol [supports](https://github.com/cyrus-and/chrome-remote-interface/blob/master/lib/protocol.json#L887) capturing screenshots.

### How would you reproduce the current behavior (if this is a bug)?

1. Install testcafe and Chrome Canary on OSX.
2. Create a test that uses t.takeScreenshot() in test/index.test.js
2. Execute the following:

$(npm bin)/testcafe path:\''{"path":"/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary","cmd":"--headless --remote-debugging-port=9222 --disable-gpu"}'\' --screenshots /Users/MYUSERNAME/projects/angular1-systemjs-seed/test/testcafe/shots test/index.test.js

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: N/A

Test code

```js
  await t.takeScreenshot('myshot.jpg');
```

### Specify your

* operating system: macOS Sierra 10.12.4
* testcafe version: ^0.14.0
* node.js version: 7.8.0

**Comment by AndreyBelym** [comment]
Hello @jimthedev! an offtopic first: you don't have to use json to specify the browser, you can just use
```
testcafe 'path:`/Applications/Google Chrome Canary.app` --headless --remote-debugging-port=9222' test.js
```
Use backticks if path to the app contains spaces: [docs](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#starting-browser-with-arguments).

To the point: currently we use native OS routines to take screenshots, it means that if there is no window -there will be now screenshot. But we are planning to create an additional browser provider that will use Chrome Debugging Protocol. It's related to mobile emulation mode: https://github.com/DevExpress/testcafe/issues/1274. I think we also can implement screenshots through CDP in this provider, and you will be able to start it in headless mode using command line switch.

**Comment by AlexanderMoskovkin** [comment]
It's implemented in #1417. It available in the latest `alpha` version and will be included in the `0.16.0` version.

**Comment by TestAndunR** [comment]
Hi guys, I got the following warning although the screenshot did save in the directory. 
```
Warnings (1):
 --
  Was unable to take a screenshot due to an error.

  Error: Unable to locate the page area in the browser window screenshot at
  C:\ADRT\Code\SigmaGit\testcafe\Sigma_Automation_Testcafe\screenshots\2018-06-21_10-35-29\test-1\Chrome_67.0.3396_Windows_10.0.0\errors\1.png, because the page area mark with
  ID 3833739374 is not found in the screenshot.
      at _callee$ (C:\Users\Andun - ADRT\AppData\Roaming\npm\node_modules\testcafe\lib\screenshots\crop.js:95:31)
      at tryCatch (C:\Users\Andun - ADRT\AppData\Roaming\npm\node_modules\testcafe\node_modules\regenerator-runtime\runtime.js:62:40)
      at Generator.invoke [as _invoke] (C:\Users\Andun - ADRT\AppData\Roaming\npm\node_modules\testcafe\node_modules\regenerator-runtime\runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (C:\Users\Andun - ADRT\AppData\Roaming\npm\node_modules\testcafe\node_modules\regenerator-runtime\runtime.js:114:21)
      at step (C:\Users\Andun - ADRT\AppData\Roaming\npm\node_modules\testcafe\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
      at C:\Users\Andun - ADRT\AppData\Roaming\npm\node_modules\testcafe\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
      at <anonymous>
```

**Comment by AndreyBelym** [comment]
Hi @TestAndunR, we are about to release a next TestCafe version, which mustn't report this warning. I will notify you when it is published to NPM.

**Comment by TestAndunR** [comment]
@AndreyBelym 
Thank you very much
