### ISSUE TITLE
browser context menue

### ISSUE THREAD

**Issue by mjhea0** [DevExpress/testcafe#1413]
Hi - Is it possible to assert items are present/not present in the browser's right-click context menu? 

![screen shot 2017-04-17 at 4 45 59 pm](https://cloud.githubusercontent.com/assets/2018167/25107674/16dc3394-238e-11e7-8acf-47e329309908.png)

**Comment by AlexanderMoskovkin** [comment]
Hi Michael,

Unfortunately we have no access to browser's context menu from javascript due to browser limitations, so TestCafe has no this functionality
