### ISSUE TITLE
Implement Chrome Debugging Protocol provider

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#1417]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
Currently there is no support for Chrome Debugging Protocol in TestCafe.

### What is the expected behavior?
Implement a provider that will use CDP  and will support:

 - [ ] Headless mode: screenshots, closing windows #1411

 - [ ] Device emulation #1274

**Comment by AndreyBelym** [comment]
# Feature summary
## Usage
`chrome[:pathToBrowser][:headless][:emulation][:arg1=value;arg2=value][ --cmd-args]`


E. g.
```sh
// Default headless mode
"chrome:headless"

// Device emulation
"chrome:emulation:device=iphone 6"
"chrome:emulation:width=100;height=200;scaleFactor=1;mobile=false;orientation=vertical;userAgent=abc;touch=true"

// Headless device emulation
"chrome:headless:emulation:device=iphone 6;cdpPort=9223"

// Headless with cdpPort setting
"chrome:headless:cdpPort=9223"

// Headless/device emulation for a portable version
"chrome:path/to/chrome:headless:cdpPort=9223"
```

## Config
`path` - for the case if you want to run headless or device emulation mode for a portable browser;
`headless` - enable headless mode;
`emulation` - enable device emulation;

Available arguments:
- for device emulation: `device=<string>,width=<number>`, `height=<number>`, `scaleFactor=<number>`, `mobile=<bool>`, `orientation=<vertical|horizontal>`, `userAgent=<string>`, `touch=<bool>`.
- cdp args: `cdpPort=<int>`

**Comment by ls-guillaume-lambert** [comment]
Amazing feature! I was wondering, how would you run this in CI?

**Comment by AndreyBelym** [comment]
Hello @ls-guillaume-lambert, it depends on your CI. Generally, it's enough to install Chrome 59 on Mac/Linux and Chrome 61 on Windows. E.g. for [Travis](http://travis-ci.org) you can follow [our recipe](https://devexpress.github.io/testcafe/documentation/recipes/running-tests-in-firefox-and-chrome-using-travis-ci.html), but use another config for the Step 3:
```yaml
dist: trusty

addons:
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable
```

And on step 4 use the following configuration:
```json
"scripts": {
    "test":  "testcafe chrome:headless tests/index-test.js"
}
```

We will update the recipe soon to note Chrome Headless mode.

**Comment by AndreyBelym** [comment]
Here is an example for Travis CI: [GitHub repo](https://github.com/AndreyBelym/testcafe-example-travis-local/tree/dd98c00c381457868a624ea86f58d4d482070f0b), [Travis build](https://travis-ci.org/AndreyBelym/testcafe-example-travis-local/builds/243172465).

**Comment by ls-guillaume-lambert** [comment]
Thanks for the info!
