### ISSUE TITLE
Automatically copy remote worker URL to the system clipboard

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#1418]
### Are you requesting a feature or reporting a bug?
Feature (idea of @georgiy-abbasov)

### What is the current behavior?
Currently user have to highlight and copy the remote worker url by hands. It's slow and inconvenient.

### What is the expected behavior?
Copy remote worker url to the system clipboard. We can use https://github.com/sindresorhus/clipboardy to do this.

**Comment by okvv** [comment]
const clipboardy = require('clipboardy');
.
.
.
var connectionUrl = testCafe.browserConnectionGateway.connectUrl; //as in original code

if (clipboardy) {
    clipboardy.writeSync(connectionUrl);
}

**Comment by AndreyBelym** [comment]
Hello @okvv, you can connect any number of browsers using this URL, so if `remoteCount == n`, TestCafe will wait until `n` browsers will navigate to the URL.

**Comment by chinjon** [comment]
Is there traction with this feature, I found a use case for this that would be extremely helpful. Ideally, the remote URL would be pasted into the clipboard or accessible somewhere.
