### ISSUE TITLE
Move to testcafe-hammerhead v.2.x.x

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#142]

**Comment by inikulin** [comment]
@AlexanderMoskovkin NOTE: we should close #110 and #54 in context of this. #54 requires some additional work on testcafe side BTW

**Comment by inikulin** [comment]
**NOTE:** There was a breaking change - jsProcessor is not available anymore in Hammerhead API. 
Therefore you shouldn't use `jsProcessor.PROCESS_SCRIPT_METH_NAME` in testcafe code. In tests you can use `hammerhead.get()` to reach them. There is only one production code usage: jsProcessor.PROCESS_SCRIPT_METH_NAME. But it can be replaced with 
```js
window.location= hammerhead.getProxyUrl(url);
```

**Comment by helen-dikareva** [comment]
I'm working on this

**Comment by inikulin** [comment]
@helen-dikareva List of breking changes: https://github.com/DevExpress/testcafe-hammerhead/issues?q=is%3Aissue+label%3A%22API+MODIFICATION+LEVEL%3A+breaking+changes%22+is%3Aclosed

You can find notes regardings breaking changes in comments.
