### ISSUE TITLE
EventListeners 'mouseenter' and 'mouseleave' not working with testcafe

### ISSUE THREAD

**Issue by mkubrycz** [DevExpress/testcafe#1426]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

I have a button that should show up on 'mouseenter' and disappear on 'mouseleave', but nothing shows when running tests. Test passes anyway since element with opacity = 0 is clicked.

### What is the expected behavior?

hidden element should show up

### How would you reproduce the current behavior (if this is a bug)?

when I reproduce this manually everything works fine.
1. go to URL given below
2. hover over red square
3. blue element with button should appear but id doesn't
4. click button to change red to yellow

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://jsfiddle.net/p5reyep3/3/

Test code

```js
import { Selector } from 'testcafe';

fixture('click a thing on hover')
.page('https://jsfiddle.net/p5reyep3/3/');

test('succeed to click', async (t) => {
  await t
  .switchToIframe('[name="result"]')
  .hover('#outer')
  .click('button')
  .expect(Selector('#outer').hasClass('yellow')).eql(true);
});

```

### Specify your

* operating system: macOS Sierra 10.12.4
* testcafe version: 0.14.0
* node.js version: 6.10.0

**Comment by AlexanderMoskovkin** [comment]
Hi @mkubrycz,

I've reproduced the problem, we will investigate it

**Comment by AlexanderMoskovkin** [comment]
I'm working on this
