### ISSUE TITLE
Improve handling errors for file:// protocol

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#1434]
* testcafe version: 0.15.0-alpha3
Cases:
1. Navigate to a folder.
```js
fixture `Fixture`
    .page('../');

test('test', async t => {});
```
TestCafe hungs.
![image](https://cloud.githubusercontent.com/assets/4133518/25275396/c3bb5e3e-269d-11e7-964f-d669ea252954.png)

2. Navigate to non-existing file.
TestCafe opens an empty page. So this test is passed.
```js
import { Selector } from 'testcafe';

fixture `Fixture`
    .page('./wrong-file');

test('test', async t => {
    const bodySelector = Selector('body');

    await t.wait(10000)
        .expect(bodySelector.exists).ok();
});
```
3. Also need to check all common file access errors. For example, `EPERM`, `

**Comment by AndreyBelym** [comment]
> 2. Navigate to non-existing file.
TestCafe opens an empty page. So this test is passed.

It's the same behavior when a HTTP(S) request to a page has no `body` and has non-`2xx` error code. So should we report an error too if a request to the test page has status `404` or `500`?

**Comment by miherlosev** [comment]
I think we should emulate browser behavior in this case.
If I open a nonexistent file in browser then I am getting the following message:
![image](https://cloud.githubusercontent.com/assets/4133518/25327140/af0a53a6-28db-11e7-8ffd-79e6f9cdd519.png)

**Comment by inikulin** [comment]
Already discussed: we'll through error in hammerhead and redirect to `about:error`. Semantically it's pretty much the same as DNS error.

**Comment by AndreyBelym** [comment]
https://github.com/DevExpress/testcafe-hammerhead/issues/1115

**Comment by AlexanderMoskovkin** [comment]
fixed
