### ISSUE TITLE
Don't wait for all browsers to be connected

### ISSUE THREAD

**Issue by madmod** [DevExpress/testcafe#1441]
### Are you requesting a feature or reporting a bug?

Feature.

### What is the current behavior?

When running testcafe with a command that includes many browsers test execution is not started until all browsers are connected. In one case I had a browser which would not load, (Google Nexus 5@5.0) causing many minutes of wasted BrowserStack automation before it timed out. Implementing this would save resources on local testing with many browsers and also save the often expensive/limited testing minutes and parallel sessions in cloud providers such as BrowserStack and Sauce Labs.

An example command with many browsers:
```bash
testcafe 'browserstack:edge,browserstack:ie@11:Windows 7,browserstack:Chrome:Windows 7,browserstack:ie@10:Windows 7,browserstack:Firefox:Windows 7,browserstack:Safari:OS X Mavericks,browserstack:Google Nexus 5@5.0,browserstack:iPhone SE@10.0,browserstack:iPhone' test/
```

Note this is separate from the issue [Option to run tests in parallel #1165](https://github.com/DevExpress/testcafe/issues/1165) because that (I assume) is about running multiple tests at once in the same browser in different iframes.

### What is the expected behavior?

The core of the enhancement would be allowing tests to run in each browser as soon as it is connected.

A secondary goal of the enhancement could be to add per-browser progress information to reporters, giving the developer more immediate feedback if a test were failing in many/all browsers. For example a reporter could show `(1/2)` after the test name to indicate that one browser still needs to complete the test like this:

```
bash
 Running tests in:
 - Chrome 57.0.2987 / Mac OS X 10.12.3
 - Chrome 57.0.2987 / Windows 10

 Embedded Example
 ✓ With no path on load the parent window hash should change to the iframe path (2/2)
 ✓ When a link in the iframe is clicked the iframe should navigate to it (1/2)
```

### Specify your

* operating system: Mac OS Sierra
* testcafe version: 0.14.0
* node.js version: v6.10.0

Thanks for the awesome project!

**Comment by inikulin** [comment]
@madmod But what's the purpose of starting tests if task will terminate anyway if one of browsers is not connected?

**Comment by inikulin** [comment]
> A secondary goal of the enhancement could be to add per-browser progress information to reporters, giving the developer more immediate feedback if a test were failing in many/all browsers. For example a reporter could show (1/2) after the test name to indicate that one browser still needs to complete the test like this

We can't report progress per browser, because it will require output rewrite, which is impossible if you redirect report to the file or terminal which doesn't support that.

**Comment by madmod** [comment]
@inikulin Sorry my example was a bit confusing. That comment was more of an aside about why immediate per-browser reporting would be useful. Even without per-browser reporting running the tests in each browser as soon as it is connected would save a significant number of testing minutes for runs with many browsers or runs in which a browser fails to load and times out. In BrowserStack I see wait times of several minutes before any tests start running. That can really add up when you are testing in 10 or so browsers.
