### ISSUE TITLE
Hide all toolbars when taking screenshots

### ISSUE THREAD

**Issue by mjhea0** [DevExpress/testcafe#1445]
### Are you requesting a feature or reporting a bug?

feature request

### What is the current behavior?

all toolbars are displayed when a screenshot is taken

### What is the expected behavior?

remove all toolbars (run chrome from application mode)

### Specify your

* operating system: OS-X 10.11.6
* testcafe version: 0.14.0
* node.js version: 7.9.0

**Comment by AlexanderMoskovkin** [comment]
Hi,

Thanks for the report, we should think out it thoroughly. If we will create screenshots without browser toolbars it can be a breaking change for someone.

As a workaround you can run chrome in application mode via browser arguments:
`testcafe "chrome --kiosk" test.js`
(quit the running chrome before try it)

**Comment by mjhea0** [comment]
The problem with application mode is that debugging is difficult (if not impossible). I don't believe there is a way to open dev tools or toggle application mode if a breakpoint is added. 

This issue seems related to https://github.com/DevExpress/testcafe/issues/1357.

The use case for me is for visual regression testing. Since the address is different for each test, there will always be a regression. Perhaps a flag that removes the testcafe UI bar and does not include the address bar on screenshots...

**Comment by mjhea0** [comment]
Also, curious if you know of anyone that has added on a visual regression feature to testcafe? Looking at using https://github.com/mapbox/pixelmatch to compare the images. Writing a few scripts now to incorporate into the testing workflow.

**Comment by inikulin** [comment]
@mjhea0 We have #1207. We even had had a long in person discussion about original proposal and decided to drastically change proposed approach afterwards. Discussion should have been documented by @kirovboris. However, unfortunately I can't find any notes 😞 . You can add 👍 to the #1207 so we'll know that there is a demand for the feature.
