### ISSUE TITLE
Does withRole restore localStorage?

### ISSUE THREAD

**Issue by astanciu** [DevExpress/testcafe#1454]
Wondering if the new `withRole` feature restores items in localStorage? I'm noticing that with jwt based authentication where access tokens are stored in localStorage, session are not properly restored.

**Comment by inikulin** [comment]
@astanciu We thought about this scenario, but decided to postpone local storage sandboxing implementation for Roles. Now when there is a demand for the feature, I'll add it to the planned.

@churkin What we need from hammerhead side to implement it?

**Comment by astanciu** [comment]
+1 for this. As it stands, unless I'm missing something, I cannot find a way to run multiple tests within 1 fixture w/o each test needing to do its own login. Alternatively, it would be great if the tests within a fixture would share the same session

**Comment by churkin** [comment]
@inikulin All is ready, we just need to add `backupStarage` and `restoreStorage` methods to the hammeread's API

**Comment by astanciu** [comment]
any updates here? Is this something that will happen, and if so, is there a rough timeline?

**Comment by AlexanderMoskovkin** [comment]
Hi @astanciu,

We plan to implement this in one of the next two releases.

**Comment by churkin** [comment]
https://github.com/DevExpress/testcafe-hammerhead/issues/1125
