### ISSUE TITLE
testcafe banner hide part of my page 

### ISSUE THREAD

**Issue by mulyoved** [DevExpress/testcafe#1457]
### Are you requesting a feature or reporting a bug?
feature

### What is the current behavior?
I use 
```js
    .resizeWindowToFitDevice(deviceName, {
      portraitOrientation: true
    })
```

during test and when taking screenshot testcafe banner hide part of my screen (this does not effect access hiden elements, just visuall problem)

![feedback](https://cloud.githubusercontent.com/assets/2309907/25563411/8e9f2c9a-2da4-11e7-81b3-2eb04474a567.png)

### What is the expected behavior?
testcafe banner should be draw outside of the selected screen size and if possible things like 100vh still work properly, 

or should have an option to hide the banner

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js
  await t
    .resizeWindowToFitDevice(deviceName, {
      portraitOrientation: true
    })
    .takeScreenshot("start")
```

### Specify your

* operating system: Windows
* testcafe version: 0.15.0
* node.js version:v7.8.4

**Comment by AlexanderMoskovkin** [comment]
Hi @mulyoved,

TestCafe panel doesn't affect on test running or page behavior. If you want to see some elements under the panel you can hover the cursor over it and it will be hidden.
Meanwhile we are going to hide this panel when TestCafe creates a screenshot (see #1357), so you will not see this panel on page screenshots. Does it work for you?

**Comment by mulyoved** [comment]
Yes, this is fine, closing this now
