### ISSUE TITLE
testcafe hangs on pages with server sent event subscriptions

### ISSUE THREAD

**Issue by yusinto** [DevExpress/testcafe#1458]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Tests hang on pages with server sent event subscriptions.

### What is the expected behavior?
Tests should not hang and should continue to finish even with server sent event subscriptions.

### How would you reproduce the current behavior (if this is a bug)?
A page with more than one server sent event subscriptions will suffer from this hang. Please run the supplied test below against the supplied url to reproduce the problem. Also I have attached devtools network tab errors and their details in screenshots, please refer to them below

The first screenshot is the server sent event connection timeout (57df4354dd79c70721bcb507). We use launch darkly as our feature flag provider, and these are subscribing to launch darkly servers for feature flag updates.

After the hang, testcafe output: 
ERROR The Chrome 57.0.2987 / Mac OS X 10.12.2 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.

<img width="1148" alt="network error details 3" src="https://cloud.githubusercontent.com/assets/1593077/25569901/1ae11f70-2e62-11e7-9664-30d21467bd9a.png">
<img width="1275" alt="network error details 2" src="https://cloud.githubusercontent.com/assets/1593077/25569902/1ae23be4-2e62-11e7-9f72-9f7fb9a31202.png">
<img width="1132" alt="network error details 1" src="https://cloud.githubusercontent.com/assets/1593077/25569900/1adee2fa-2e62-11e7-8cbf-55347c1f209b.png">
<img width="593" alt="network connection erros" src="https://cloud.githubusercontent.com/assets/1593077/25569899/1ade813e-2e62-11e7-8380-5c66d89eb85d.png">

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://testcafe-spike.qantasassure.com/health-insurance/quote

Test code

```js
import { Selector } from 'testcafe';

fixture `Enter Your Details`
  .page `https://testcafe-spike.qantasassure.com/health-insurance/quote`;

test('Verify FrequentFlyer page is displayed after details are entered', async t => {
  await t
    .typeText('input[name="firstName"]', 'Yus')
    .click('label[for="scale-Single"]')
    .click('label[for="countryState-NSW"]')
    .click('label[for="rebateTier-Tier0"]')
    .typeText('input[name="day"]', '18')
    .typeText('input[name="month"]', '06')
    .typeText('input[name="year"]', '1977')
    .click('label[for="isSwitching-false"]')
    .click('button[type="button"]')
    .click(Selector('button[type="button"]').nth(1))
    .click(Selector('.Ht2Nhh button'));
});

```

### Specify your

* operating system: Mac OS X 10.12.2
* testcafe version: 0.14.0
* node.js version: 7.2.0

**Comment by AlexanderMoskovkin** [comment]
Hi Yusinto, 

I've reproduced the issue and we will investigate it.

**Comment by yusinto** [comment]
Thanks, let me know if I can do anything to help. I was trying to debug it myself but not sure where to start.

**Comment by AlexanderMoskovkin** [comment]
I've found that something is broken in our proxy (https://github.com/DevExpress/testcafe-hammerhead/issues/1106) in your case. If we will need some additional information from you we'll let you know, thanks.

**Comment by AlexanderMoskovkin** [comment]
Hi @yusinto,

We've fixed the issue. You can check it with the latest `alpha` version (`v0.16.0-alpha1`). 
You can install it via
```sh
npm install testcafe@alpha
```

**Comment by bouzoumita** [comment]
@AlexanderMoskovkin the problem still exist with v0.18.6
