### ISSUE TITLE
Asynchronous tests running

### ISSUE THREAD

**Issue by gerardus1995** [DevExpress/testcafe#1460]
### Are you requesting a feature or reporting a bug?

Feature

### What is the current behavior?

testcafe.createRunner() executes every fixture one after the other.

### What is the expected behavior?

Is there any way to execute all at the same time (asynchronously). Like opening 4 consoles and executing 4 tests at same time (with nightmare headless browser).

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Mac OSX
* testcafe version: 
* node.js version:

**Comment by AlexanderMoskovkin** [comment]
Hi,

Thanks for the proposal. We have this feature in our `planned` milestone but now we have no estimated date for this. You can vote for the feature by adding your 👍 there: https://github.com/DevExpress/testcafe/issues/1165
