### ISSUE TITLE
Implement re-evaluation for `expected` value for smart assertions

### ISSUE THREAD

**Issue by Scrum** [DevExpress/testcafe#1467]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

expected 5 to deeply equal { Object (_then, _fn, ...) }

### What is the expected behavior?

This should be equivalent

#### Provide the test code and the tested page URL (if applicable)

Tested page:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <a href="">1</a>
    <a href="">2</a>
    <a href="">3</a>
    <a href="">4</a>
    <a href="">5</a>
</body>
</html>
```

Test code

```js
import {Selector} from 'testcafe';

fixture `Equal`
	.page `./expect.html`;

test('equal', async t => {
	const links = Selector('a');
	await t
		.expect(links.count).eql(links.count)
});
```

### Specify your

* operating system: windows 10
* testcafe version: 0.15.0
* node.js version: 7.7.4

**Comment by AndreyBelym** [comment]
Hello @GitScrum, currently TestCafe doesn't automatically awaits Promises returned by Selectror Shorthands in `eql`.  As a workaround you can use the `await` keyword:
```
await t.expect(links.count).eql(await links.count);
```
The drawback of this workaround is that it's better to don't chain it with other actions/assertions.

**Comment by inikulin** [comment]
@AndreyBelym actually it does. But it only re-evaluates `actual` value. We've discussed it previously and decided to not implement handling for `expected` value. Shouldn't be hard to implement.

**Comment by miherlosev** [comment]
One more customer - https://testcafe-discuss.devexpress.com/t/using-testcafe-with-vue/981/4

**Comment by helen-dikareva** [comment]
Another mention https://stackoverflow.com/questions/57527461/testcafe-gets-stuck-when-using-await-async-in-expect-assertion

**Comment by miherlosev** [comment]
https://stackoverflow.com/questions/61496353/check-if-the-innertext-of-a-selector-includes-a-substring
