### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by Scrum** [DevExpress/testcafe#1470]
- [ ] chaining/callback condition
  
  ```js
  await t
    .if(/* Boolean condition */)
    .hover(selector)
    .endif()
    .click(selector)
  ```
  or

  ```js
  const callback = async t => {
    await t
        .hover(selector)
  }

  async t
    .if(/* Boolean condition */, callback)
    .click(selector)
  ```

- [ ] Selector.random elements
  ```js
    // Select a random number of elements
    const buyButton = await Selector('.in-cart').random(/* number */) 
  ```

- [ ] MultiEvent
  ```js
  // if selector array do event for of each
  const afterAction = async (t, currentNode) => {
    await t
      .hover(currentNode)
  };

  const beforeAction = async t => {
    const modalClose = await Selector('.modal .close');
    await t
      .click(modalClose)
  };

  await t
    .click(buyButton, {afterAction, beforeAction})
  ```

- [ ] Call other test
  ```js
  // We have many tests, eg:
  // put-in-cart-random-goods.js
  // checkout.js
  
  test('Random test generator', async t => {
    await t
      .importTest('put-in-cart-random-goods.js')
      // Some other actions
      .importTest('checkout.js')
  })
  ```

**Comment by inikulin** [comment]
\cc @AlexanderMoskovkin

**Comment by AlexanderMoskovkin** [comment]
Hi @GitScrum,

Thanks for your proposals. 
I suppose most of them quite specific and can be implemented with a few additional lines of code in the test or in a helper. I'm inclined to add only most valuable features to API in this case to don't do the API overloaded.

For example, it's easy to replace proposed chaining condition with a regular condition:
```js
await t
  .if(/* Boolean condition */)
  .hover(selector)
  .endif()
  .click(selector)
```
->
```js
if(await selector.visible)
    await t.hover(selector);
```

Instead `Selector.random` you can use the following:

```js
function getRandomInt(min, max) {
  return Math.floor(Math.random() * (max - min)) + min;
}

async function getRandomEl (selector) {
    const count = await selector.count;
    
    if(!count)
        return null;

    const index = getRandomInt(0, count);
    return selector.nth(index);
}
```

MultiEvent:
```js
const count = await selector.count;

for(let i = 0; i < count; i++) {
    // run beforeAction();
    await t.click(selector.nth(i));
    // run afterAction();
}
```

The `Call other test` approach has a lot of uncertainties. What if the fixture in the imported file has several tests? What the test has their own [page directive](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#specifying-the-start-webpage) or it's [skipped](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#skipping-tests)?
I think the best practice here is to place shared steps to a function and call it from different tests:
```js
// login.js
import { t } from 'testcafe';

export default async function () {
    await t
        .typeText('#login', 'login')
        .typeText('#password', 'password')
        .pressKey('enter');
}

// test.js
import login from './login.js';

fixture `Fixture`
  .page `http://example.com`;

test('Test', async t => {
  await login();
});
```

**Comment by AlexanderMoskovkin** [comment]
> Can be have the ability to connect plug-ins? As done for example in babel.

We have no such ability now, but we had the similar thoughts before. So, let's keep your issue opened as a reminder to think out it again.

**Comment by abenhamdine** [comment]
I have the same need to call other tests, and so far, I failed to make your exemple run : 

```ts
// login.js
import { t } from 'testcafe';

export default async function () {
    await t
        .typeText('#login', 'login')
        .typeText('#password', 'password')
        .pressKey('enter');
}

// test.js
import login from './login.js';

fixture `Fixture`
  .page `http://example.com`;

test('Test', async t => {
  await login();
});
```

I have the following error : 


   1) ReferenceError: testcafe_1 is not defined

on line 
```ts
export default async function () {
    await t
```

I eventuallly succeeded by another way , by passing t to the imported function :  

```ts
// helpers.js
export async function createNew (t) {
    await t.click('.new-btn');
}

// test.js
import { createNew } from './helpers';

test('Test', async t => {
    await createNew(t);
    // ...
});
```

**Comment by AlexanderMoskovkin** [comment]
Hi @abenhamdine,

Usually this code should work properly. It can relate to the way how did you install testcafe module. Could you please share us with details of your file and module structure? How did you install testcafe, locally or globally. How do you run tests, via CLI, package.json script command, programming interface. Do you have any other modules installed in your project?
