### ISSUE TITLE
Test hangs with non-HTML tested pages (pdf, plain text, etc.)

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#1471]
### Are you requesting a feature or reporting a bug?
Enhancement

### What is the current behavior?
If you are redirected by tested page to some non-HTML document (e.g. SVG, PNG, or PDF), or use such document in a fixture as a test page, the document will be loaded, but the test will hang because we don't proxy such documents.

### What is the expected behavior?
Show an error with a message that will explain that we don't support such documents as test pages.

### How would you reproduce the current behavior (if this is a bug)?
Run test

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://andreybelym.github.io/test-pages/gh-1471.html

Test code

```js
fixture `Redirect`
        .page `https://andreybelym.github.io/test-pages/gh-1471.html`;


test('1',async t => {
    await t
        .click('a')
        .expect(true).ok();
}); 
```

### Specify your

* operating system: Windows 10
* testcafe version: 0.15.0
* node.js version: 7.4.0

**Comment by miherlosev** [comment]
It's synthetic scenario. We will wait until a real-user case.

**Comment by DavidJRobertson** [comment]
I have run into this today while trying to use testcafe to test an application which heavily uses PDF export functionality. I'm not expecting to be able to do assertions on the content of a PDF or anything like that, but it would be essential for my use case to be able to test that a PDF is generated and displayed in the browser.

**Comment by callmeaponte** [comment]
+1 for this.

I'm behind a corporate proxy which prevents certain third-party scripts from loading properly (such as Google Analytics, Google reCAPTCHA, etc) - since the initial response contains a login/redirect page.

The only way around this is to visit each script URL we need directly, log in and/or wait for it to redirect, and then go back to the original site we're developing for. After that the script URLs all load properly for the duration of the browser session.

If TestCafe could allow me to do something like the following it would be incredibly useful:

```
await t
    .navigateTo("some/path/to/file.js")
    .navigateTo("another/path/to/file.js")
    .navigateTo("mysite.com")
```

TestCafe is an amazing tool btw. Keep up the great work!

**Comment by ancentz** [comment]
Yes, this is what I'm experiencing as well. I hope you will be able to add support to Non Html Files.
https://stackoverflow.com/questions/52361644/testcafe-cant-take-screenshot-when-opening-pdf

**Comment by zgbrianp** [comment]
Hi, having a similar problem with this. Some of our error messages come with type "text/plain" so when testcafe visits a broken page, instead of marking it as failed and continuing, it breaks the entire test. Is there any workaround to this? I've tried setting the timeout, but it doesn't help.

**Comment by Farfurix** [comment]
@zgbrianp 

Hi,

There is no workaround. This issue is in the [Enhancement processing](https://github.com/DevExpress/testcafe/projects/11#card-18273858) project. Please stay tuned to our updates here.

**Comment by marcinlesek** [comment]
+1 for it, I also need to go through user flow, where in one step is generating PDF in another window (but due to fact, that TestCafe didn't allow for multi tabs, it's loaded in main window) so it crash test execution. 

Although you only want go through and do `navigate(url)` to another place, still didn't work. 💔

**Comment by AlexKamaev** [comment]
@marcinlesek 
Thank you for your feedback. 
Also I want to mention that we have plans to implement multiple window support according to the [testcafe roadmap](https://devexpress.github.io/testcafe/roadmap/)

**Comment by jcreek** [comment]
I also have need of this feature.

**Comment by devmondo** [comment]
yes please, this is a deal breaker for some projects.

**Comment by appendixshuffle** [comment]
s same situation like in testcase described by @marcinlesek so please consider it faster ;-)

**Comment by AndreyBelym** [comment]
Also, we have a problem with file downloading dialogs in Firefox & IE11: https://github.com/DevExpress/testcafe/issues/2741. When we fix this issue, it's better to cover #2741 too.

**Comment by elimence** [comment]
Any updates on this? run into this problem a couple times as well.

**Comment by miherlosev** [comment]
Our developers will look into this issue in one of the next springs. You will be automatically notified once we make progress. Your patience is greatly appreciated.

**Comment by MirreJensen** [comment]
We would appreciate it too, as we are handling with some long URL during multiple redirects.

**Comment by ognif** [comment]
When this issue will be solved? A sprint is common 7-14 days. In my eyes it is not. bug this is definitely an incident because it blocks your customer. So if this will take a year more, it was reported in 2018 as I read, I have to look for another solution. Be fair and please give an estimation.

**Comment by alexey-lin** [comment]
Sorry, we cannot give any estimates. This issue is not planned for the current sprint, because we are focused on other tasks right now. And of course, your PR would be highly appreciated.

**Comment by SimonKlausLudwig** [comment]
I have the same problem,  after login I got redirect to a page which shows some JSON. I am successfully logged in but everything freezes so I can't navigate to the html page.

**Comment by felis2803** [comment]
Hello,

We have not implemented this enhancement yet. Please design your test so that you don't end up on non-html pages.

**Comment by Akshay-Kawlay** [comment]
> We have not implemented this enhancement yet. Please design your test so that you don't end up on non-html pages.

For this issue when browser hangs, testcafe restarts it but it only does it 3 times and then stops everything. Maybe if you allow an option to make testcafe restart a set number of times or infinite restarts, that should work for me. 
Also, is there an interrupt handler that will notify if testcafe is about to go in non-html page so I can avoid going there? That would also help since I have a lot of tests and manually checking /updating them will take a very long time.

**Comment by aleks-pro** [comment]
Hello @Akshay-Kawlay ,

Thank you for sharing your idea with us. We will take it into account.
As a workaround, try to use the [RequestMock](https://devexpress.github.io/testcafe/documentation/reference/test-api/requestmock/) API. It will allow you to check if a requested page is non-HTML and redirect to another page. See the following test example:

```js
import { RequestMock } from 'testcafe';

fixture `Redirect`
    .page `https://andreybelym.github.io/test-pages/gh-1471.html`;

test('1', async t => {
    const mock = RequestMock()
        .onRequestTo(/\.svg$/)
        .respond('<script>window.location="https://google.com"');

    await t
        .addRequestHooks(mock)
        .click('a')
        .expect(true).ok();
});
```

**Comment by Akshay-Kawlay** [comment]
Hello @aleks-pro,

Thank you very much for your reply. I will try your suggestion.
However, due to the high number of occurrences of non html pages in the test suite, it will take quite a bit of time to figure out all the URIs that return non-html pages even with regex since they can be all sorts of format right?

So, I wanted to ask if there is a way to modify testcafe code instead to increase the number of allowed restarts from 3 to infinite?
For example, where in the code can I update that number 3, then build it and install it for my system? I could not find the section of code I need to update...

**Comment by wentwrong** [comment]
Hello @Akshay-Kawlay,

Yes, the workaround implies that you know in advance which non-HTML pages TestCafe will be redirected to. I think this solution is more stable than relying on multiple TestCafe restarts when your browser hangs. If you still want to try that, you can change the threshold value [here](https://github.com/DevExpress/testcafe/blob/faec4a93682d51a6f51909514b437236899b08c1/src/runner/test-run-controller.ts#L17) and build a custom version of TestCafe using [Build Instructions](https://github.com/DevExpress/testcafe/blob/master/CONTRIBUTING.md#build-instructions) from our contributing guide.

**Comment by Akshay-Kawlay** [comment]
Hello @wentwrong, 

Thank you so much for this! That helped perfectly.

**Comment by Akshay-Kawlay** [comment]
Hello @wentwrong,
Regarding this issue, I was also wondering how to modify the timeout value such that it only waits a short amount of time before restarting the browser. I tried setting the --ajax-request-timeout and --page-request-timeout but that does not affect the default 2 mins wait time for the browser restart case...
Thank you in advance!

**Comment by lpelypenko** [comment]
Hi all,
I am trying to reduce flakiness and optimize my tests where we currently create a job via UI and after the job is created we verify it was created with correct values. Verification can be done using UI but page is opening slow and is affected by other functionality that we don't want to test in the same test. The best for optimization is to split creation via UI and checking created values via opening API endpoint, e.g _/api/jobKey_ that has **Content-Type: application/json;charset=UTF-8**. Currently TestCafe hands when we open such page with json content and I can't reuse browser's authorization to just open /api/jobKey and read response as json.

What do you think is this improvement will be worked on some time soon? Maybe someone can suggest what I could miss and have a solution for opening in TestCafe test **Content-Type: application/json;charset=UTF-8** page and reusing authorization from browser to open it?

**Comment by aleks-pro** [comment]
Hi @lpelypenko,

You can programmatically make a request to your API endpoint from the TestCafe test and then check the received JSON data. Please take a look at the answer in the following thread on StackOverflow: https://stackoverflow.com/questions/62271173/make-a-real-http-request-using-testcafe
