### ISSUE TITLE
Test doesn't fail on uncaughtRejection

### ISSUE THREAD

**Issue by kirovboris** [DevExpress/testcafe#1473]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

Test doen't fail if client code throws exception in Promise

### What is the expected behavior?

Test should fail

### Specify your

* operating system: any
* testcafe version: 0.15.0
* node.js version: 6.x

**Comment by kirovboris** [comment]
What's the difference between `window.onerror` and `window.onunhandledrejection`? Why can't we detect failed test?

**Comment by inikulin** [comment]
Oh, you mean on the client side...

**Comment by AlexanderMoskovkin** [comment]
closed in #1703
