### ISSUE TITLE
Enable testcafe remote with fixed URL

### ISSUE THREAD

**Issue by mulyoved** [DevExpress/testcafe#1476]
### Are you requesting a feature or reporting a bug?
feature 

### What is the current behavior?
each time I run `testcafe remote` new url is generated and need to copy & paste it to the remote simulator this turn to be a pain when debug a test and need to redo this many time, 

### What is the expected behavior?
if testcafe will generate the same URL each time it will simplify the flow as all is needed it to hit refresh on the remote browser

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by AndreyBelym** [comment]
Hello @mulyoved! We need some time to discuss that feature. At the moment, you can vote for this feature : [Automatically copy remote worker URL to the system clipboard](https://github.com/DevExpress/testcafe/issues/1418). Just add 👍 to the post. Also, if you are talking about iOS simulator, you can try [FBSimCtl browser provider](https://www.npmjs.com/package/testcafe-browser-provider-fbsimctl), or we can consider creating a dedicated browser provider. So what is the simulator you are talking about?

**Comment by mulyoved** [comment]
Hi @AndreyBelym 

I am working on Windows and iOS simulator work on a OSX VM 

Automatically copy remote worker URL to the system clipboard. does not help my use case as still hard to paste and sometimes paste really does not work across this stack of software (Host->VM->iOS Simulator)

Just a preconfigured URL will do the work much better

**Comment by AlexanderMoskovkin** [comment]
@mulyoved,

Yeah, I see that the current way is painful for you. Now a remote browser connect url looks like:
`http://some-hostname:{port}/browser/connect/{uid}`.
You can fix the `{port}` in the url via the [--ports](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--ports-port1port2) option.

I see the following way to resolve the problem - simplify the last part of the url, for example if you would like to run several remote browsers:
```
http://hostname:port/browser/connect/
http://hostname:port/browser/connect/2
```

Or even just use only `http://hostname:port/browser/connect` url to connect each next remote browser. 
In this case you just reenter the same url as before to start the tests in the remote browser (the url is stored in the browser history).
Does this approach work for you?

**Comment by mulyoved** [comment]
@AlexanderMoskovkin 

yes that will work nicely

**Comment by AlexanderMoskovkin** [comment]
Nice. It seems it shouldn't take much time to implement this. We will think over it one more time and if we will not find any unexpected side effects we'll do it.
