### ISSUE TITLE
Clicks on the wrong button

### ISSUE THREAD

**Issue by dxBeardedBear** [DevExpress/testcafe#1482]
### Are you requesting a feature or reporting a bug?

Bug.

### What is the current behavior?

TestCafe clicks on the "Copy" button instead of "Export" (at this time it still doesn't render).

### What is the expected behavior?

TestCafe clicks on the "Export" button (specified in the test).

### How would you reproduce the current behavior (if this is a bug)?
![testcafebug](https://cloud.githubusercontent.com/assets/28751590/26148008/f1d6da72-3afd-11e7-8f70-0ca6a502fc44.png)

![screenexport](https://cloud.githubusercontent.com/assets/28751590/26148383/1e7fe1e4-3aff-11e7-8def-c6bed6826e98.jpg)
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
http://bezborodov-w8/171/Bootstrap/Charts/Export.aspx
Test code

```js
import { Selector } from 'testcafe';
import { bootstrapUrl } from '../../lib/config';
import { findChart, findButton } from '../../lib/bootstrap';

fixture`Charts - Export`
    .page`${bootstrapUrl}/Charts/Export.aspx`
    .beforeEach( async t => {
        await t
            .maximizeWindow()
            .setTestSpeed(0.8);
    });

test('Charts - check export menu items', async t => {
    const chartPartialId = 'Chart1';
    const chart = await findChart(chartPartialId);
    
    await t
        .click(chart.exportButton)
        .expect(chart.getExportMenuItem("Print").exists).ok("Menu item 'Print' not found")
        .expect(chart.getExportMenuItem("JPEG file").exists).ok("Menu item 'JPEG file' not found")
        .expect(chart.getExportMenuItem("PNG file").exists).ok("Menu item 'PNG file' not found")
        .expect(chart.getExportMenuItem("SVG file").exists).ok("Menu item 'SVG file' not found")
        .expect(chart.getExportMenuItem("GIF file").exists).ok("Menu item 'GIF file' not found")
        .expect(chart.getExportMenuItem("PDF file").exists).ok("Menu item 'PDF file' not found")            
});
```

### Specify your

* operating system: Windows 10 64-bit
* browser: IE 11
* testcafe version: 0.14.0

**Comment by AlexanderMoskovkin** [comment]
As a workaround you can add some assertion before click to ensure the render is completed.
Anyway we will think how we can handle this case

**Comment by AlexanderMoskovkin** [comment]
It seems it works properly now
