### ISSUE TITLE
Runner's speed option affects the speed of 'doubleClick' action.

### ISSUE THREAD

**Issue by arubtsov** [DevExpress/testcafe#1486]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

Runner's speed option affects the speed of 'doubleClick' action.

### What is the expected behavior?

Double click's speed should not depend on the speed of a test.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Win 8
* testcafe version: 0.15.0
* node.js version: 7.9.0

**Comment by AlexanderMoskovkin** [comment]
I'm working on this
