### ISSUE TITLE
Introduce a flag "Report Failed Tests Only" to report failed tests only.

### ISSUE THREAD

**Issue by tsv2013** [DevExpress/testcafe#1489]
### Are you requesting a feature or reporting a bug?

Feature

### What is the current behavior?

Too long tests report including all passed tests. Its too hard to find e.g. 2 failed tests in case of 400 tests.

### What is the expected behavior?

Introduce a flag "Report Failed Tests Only" to report failed tests only.

#### Provide the test code and the tested page URL (if applicable)

https://travis-ci.org/surveyjs/surveyjs/builds/234853875

**Comment by inikulin** [comment]
You can use the `minimal` reporter if you are interested in failed tests only.
