### ISSUE TITLE
DOM nodes 'filter' function cannot filter nodes by 'visible' attribute

### ISSUE THREAD

**Issue by mkubrycz** [DevExpress/testcafe#1491]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

I'm filtering a set of nodes by their visibility and getting 0 nodes in return when I'm supposed to get 3. But when I check if those nodes are visible separately test passes.

### What is the expected behavior?

I should be able to filter nodes by their visibility and then use that set of nodes in further testing.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://reactcommunity.org/react-tabs/example/

Test code

```js
import { Selector } from 'testcafe';

fixture('only visible tab items')
.page('https://reactcommunity.org/react-tabs/example/');

const tab = opt => Selector('[role="tab"]').nth(opt);
const items = Selector('[role="tabpanel"] h2');
const visibleItems = Selector('[role="tabpanel"] h2').filter(node => node.visible);

test('succeed to count visible items', async (t) => {
  await t
  .click(tab(1))
  .expect(items.count).eql(9)
  .expect(items.nth(0).visible).eql(false)
  .expect(items.nth(1).visible).eql(false)
  .expect(items.nth(2).visible).eql(false)
  .expect(items.nth(3).visible).eql(true)
  .expect(items.nth(4).visible).eql(true)
  .expect(items.nth(5).visible).eql(true)
  .expect(items.nth(6).visible).eql(false)
  .expect(items.nth(7).visible).eql(false)
  .expect(items.nth(8).visible).eql(false)
  .expect(visibleItems.count).eql(3);
});
```

### Specify your

* operating system: macOS 10.12.4
* testcafe version: 0.15.0
* node.js version: 6.10.0

**Comment by AlexanderMoskovkin** [comment]
Hi @mkubrycz,

`items.nth(0)` - it's a selector that provides the [`visible`](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/dom-node-state.html#members-specific-to-element-nodes) field.
But when you use `filter(node => node.visible)` - it's a client function that is executed in the browser. In this case `node` - it's' not a Testcafe selector but a regular DOM Node, so it doesn't provide the `visible` property (it returns `undefined` for any node).

So I see the following ways to know how much visible elements exist:
1) Check it on the server-side:
```js
const itemsCount = await items.count;
let visibleCount = 0;

for(let i = 0; i < itemsCount; i++) {
    if(await items.nth(i).visible)
        visibleCount++;
}
```

2) Use some logic to check whether the DOM Node is visible or not in your client function.

**Comment by inikulin** [comment]
@AlexanderMoskovkin Actually we have an issue for the visibility ticket: https://github.com/DevExpress/testcafe/issues/1018. I guess it makes sense to implement it. The only problem is the proper name for it, since `visible` will conflict with `visible` property of the selector.

**Comment by AlexanderMoskovkin** [comment]
Yep. Do you have any other ideas besides `hidden` ?

**Comment by inikulin** [comment]
@AlexanderMoskovkin Unfortunately, no.

**Comment by mkubrycz** [comment]
@AlexanderMoskovkin thanks for explaining! I thought it was still a Testcafe selector, my main issue with this was that I still wanted to use this filtered set of selectors as:

```js
await t.click(visibleItems.nth(0));
```
so I came up with an idea that solves my problem:

```js
import { Selector } from 'testcafe';

fixture('only visible tab items')
.page('https://reactcommunity.org/react-tabs/example/');

const tab = opt => Selector('[role="tab"]').nth(opt);
const items = Selector('[role="tabpanel"] h2');
const visibles = [];
const visibleItems = Selector('[role="tabpanel"] h2').filter((node, idx) => visibles[idx], { visibles });

test('succeed to count visible items', async (t) => {
  await t
  .click(tab(1))
  .expect(items.count).eql(9);

  for (let i = 0; i < await items.count; i += 1) {
    visibles.push(await items.nth(i).visible);
  }

  await t
  .expect(items.nth(0).visible).eql(false)
  .expect(items.nth(1).visible).eql(false)
  .expect(items.nth(2).visible).eql(false)
  .expect(items.nth(3).visible).eql(true)
  .expect(items.nth(4).visible).eql(true)
  .expect(items.nth(5).visible).eql(true)
  .expect(items.nth(6).visible).eql(false)
  .expect(items.nth(7).visible).eql(false)
  .expect(items.nth(8).visible).eql(false)
  .expect(visibleItems.count).eql(3)
  .hover(visibleItems.nth(0))
  .click(visibleItems.nth(1));
});
```

of course it would be helpful if there was a simpler way for this. In my experience visibility checking is quite a big deal in e2e testing.

**Comment by AlexanderMoskovkin** [comment]
Yeah, this approach should work. Note if you have several tests in the file you should reset the `visibles` variable to an empty array before each test. If necessary you can you [Test Hooks](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#test-hooks) for this.
