### ISSUE TITLE
Process hangs if tests were run in nightmare

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#1493]
(created from the [stackoverflow question](https://stackoverflow.com/questions/44132703/how-to-close-testcafe-runner))

The process doesn't exit after tests run if `testcafe-browser-provider-nightmare` is used.
We should check where we should fix it in `testcafe` or in the provider.

#### Provide the test code and the tested page URL (if applicable)

```js
createTestCafe('localhost', 1337, 1338)
.then(tc => {
    testcafe     = tc;
    runner = testcafe.createRunner();

    return runner
        .src(['offerRefresh.js'])
        .browsers(['nightmare'])
        .screenshots('./screenshots', true)
        .run();
})
.then(failedCount => {
    console.log('Tests failed: ' + failedCount);
    testcafe.close();
});
```

The console remains like this:

Tests failed: 0

And never closes the process.

### Specify your
* testcafe version: 0.15.0

**Comment by inikulin** [comment]
I bet it's a nightmare process that is never terminated and blocking node from exit.

**Comment by AndreyBelym** [comment]
https://github.com/ryx/testcafe-browser-provider-nightmare/pull/13

**Comment by AndreyBelym** [comment]
Fixed in `testcafe-browser-provider-nightmare@0.0.5`.

**Comment by AlexanderMoskovkin** [comment]
@AndreyBelym, nice work!
