### ISSUE TITLE
Unable to enter integers into a date picker after being selected. 

### ISSUE THREAD

**Issue by afcbpeter** [DevExpress/testcafe#1497]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behaviour?
Currently I have a date picker which I can select and find the element but unable to typetext a date into the field.

<input type="date" placeholder="Date" id="startDate" class="input">

Here's my test cafe code
        .typeText(page.startDate, '26052017')

Typing the number on the screen manually fills the date in.

### What is the expected behaviour?
Would like to enter the date using typtext

### How would you reproduce the current behavior (if this is a bug)?
1.click on the date pickert
2.enter numbers into the field.

#### Provide the test code and the tested page URL (if applicable)
Config File
        this.startDate = this.auditQuery.child('#startDate');       
Test
 .typeText(page.startDate, '26052017')

### Specify your

* operating system: Mac
* testcafe version: ?
* node.js version: ?

**Comment by AlexanderMoskovkin** [comment]
Hi @afcbpeter ,

Could you please clarify, do you use native HTML5 input with type="date" (like [here](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_date)) or some UI datapicker widget (for exapmle like [jquery ui datepicker](https://jqueryui.com/datepicker/))?

**Comment by afcbpeter** [comment]
Hi @AlexanderMoskovkin we are using the in built date picker in chrome. If that helps?

**Comment by AlexanderMoskovkin** [comment]
We have limited html5 inputs support for now. Please try to pass the value that should be set as element's value as the second argument to the typeText action: '2017-26-05'

**Comment by afcbpeter** [comment]
Hi this seems to work for what we need.

const page = new Page();

const setValueToTimeInput = ClientFunction(val => itemSelector().value = val, {
    dependencies: {
        itemSelector: page.startDate

    }

});

**Comment by AlexanderMoskovkin** [comment]
Yes, you are right. You can use both approaches in this case (via `typeText` and `ClientFunction`):

```js
import { Selector, ClientFunction } from 'testcafe';

fixture `DatePicker`;

const setValue = ClientFunction(value => getEl().value = value);
const input = Selector('input[name="bday"]')

test.page `https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_date`
('Use typeText', async t => {
	await t
		.switchToIframe('#iframeResult')
		.typeText(input, '2017-05-05')
		.pressKey('tab')
		.expect(input.value).eql('2017-05-05');
});

test.page `https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_date`
('Use ClientFunction', async t => {
	await t.switchToIframe('#iframeResult');

	await setValue.with({ dependencies: { getEl: input } })('2017-05-05');
	
	await t
		.pressKey('tab')
		.expect(input.value).eql('2017-05-05');
});

```

**Comment by hex0cter** [comment]
👍
