### ISSUE TITLE
Testing onbeforeunload

### ISSUE THREAD

**Issue by andrewleith** [DevExpress/testcafe#1498]
Is it possible to test that closing the browser tab results in an alert being displayed?

**Comment by AlexanderMoskovkin** [comment]
Hi @andrewleith,

Yes, you can use the `setNativeDialogHandler` function. See [Handling Native Dialogs](https://devexpress.github.io/testcafe/documentation/test-api/handling-native-dialogs.html) documentation topic for details.

**Comment by andrewleith** [comment]
Can't believe I missed that in the docs, sorry!

Thanks for your help!

**Comment by AlexanderMoskovkin** [comment]
You're welcome!
