### ISSUE TITLE
Improve look in device emulation mode

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#1514]
Then I use device emulation mode manually the emulated window is centered.
If I use the device emulation mode from testcafe then emulated window has left alignment.
![DeviceEmulation](https://cloud.githubusercontent.com/assets/4133518/26725040/2b399d32-47a5-11e7-9b5b-1758a107a8ef.png)

* testcafe version: 0.16.0-alpha4

**Comment by AlexanderMoskovkin** [comment]
fixed in #1524
