### ISSUE TITLE
[Docs] Wrong description for 'path' parameter of the 'takeScreenshot' action

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#1515]
From [docs](https://devexpress.github.io/testcafe/documentation/test-api/actions/take-screenshot.html):
`path` - A relative path to the folder where screenshots should be saved. 

It is wrong.
`path` is a screenshot path. Screenshots are saved in `.png` format. If screenshot name doesn't contain `.png` then it will be added to the result name.
Examples:
```js
Screenshots folder is 'screenshots'

takeScreenshot('test') - > screenshots/test.png
takeScreenshot('/test') -> screenshots/test.png
takeScreenshot('/test.png')  -> screenshots/test.png

```

* testcafe version: 0.16.0@alpha4

**Comment by VasilyStrelyaev** [comment]
if `path` includes the filename - what is the default filename if `path` is not specified?

**Comment by miherlosev** [comment]
If path does not specified the full path will be calculated as:
`screenshots folder + {current-date}\{testName-testIndex}\{userAgent}\screenshotIndex.png`

Example:
screenshots folder: `c:\\temp`

```js
test('test', asynct t => {
    await t.takeScreenshot();
});
```

Screenshot will be saved in `c:\temp\2017-07-05_02-34-34\test-2\Chrome_59.0.3071_Windows_8.1_0.0.0\.1.png` file.

@AndreyBelym correct me if I don't right

**Comment by AndreyBelym** [comment]
Yes, that's mostly right, there will be no `{testName}` in path, and it differs slightly when quarantine mode is enabled. So if quarantine mode is not enabled:
```
{screenshotsFolder}\{currentDate}\test-{testIndex}\{userAgent}\{screenshotIndex}.png
``` 
and if quarantine is enabled, it is:
```
{screenshotsFolder}\{currentDate}\test-{testIndex}\run-{quarantineAttempt}\{userAgent}\{screenshotIndex}.png
```
