### ISSUE TITLE
Edge 15.15063.0 / Windows 10 0.0.0

### ISSUE THREAD

**Issue by GitScrum** [DevExpress/testcafe#1517]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

```console
1) AssertionError: expected 30 to deeply equal 29

      Browser: Edge 15.15063.0 / Windows 10 0.0.0

         16 |    const gridRowPage = new GridRowPage();
         17 |
         18 |    await t.navigateTo(gridColPage.url)
         19 |        .expect(gridColPage.colums.count).eql(12)
         20 |        .resizeWindow(500, 500)
       > 21 |        .expect(gridColPage.colums.nth(0).clientWidth).eql(29)
         22 |        .navigateTo(gridRowPage.url)
         23 |        .expect(gridRowPage.rows.count).eql(12)
         24 |        .resizeWindow(500, 500)
         25 |        .expect(gridRowPage.rows.clientHeight).eql(25);
         26 |});
```  
> If you perform a manual inspection, then the width of the element is **29**

### What is the expected behavior?

test passed

### How would you reproduce the current behavior (if this is a bug)?

```bash
$ git clone https://github.com/GitScrum/slims.git && cd slims
$ npm i && npm t
```
> This should be done on the platform Windows 10

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://github.com/GitScrum/slims/blob/master/tests/e2e/index-test.js#L14-L26

### Specify your

* operating system: Windows 10 0.0.0
* testcafe version: 0.15.0
* node.js version: v8.0.0

**Comment by AlexanderMoskovkin** [comment]
Hi Ivan,

I've checked your scenario and it works properly on my side. 
I've added a `debug` command before the assertion:
```js
await t.navigateTo(gridColPage.url)
        .expect(gridColPage.colums.count).eql(12)
        .resizeWindow(500, 500)
        .debug()
        .expect(gridColPage.colums.nth(0).clientWidth).eql(29)
```

Here is a screenshot how does it look on my side:
![2017-06-07_0947](https://user-images.githubusercontent.com/12047804/26865675-7195f838-4b66-11e7-8261-e747babc62de.png)

As you can see TestCafe run is stopped on the `debug` command. `window.innerWidth` equals 500 as expected and the `clientWidth` of the column is 29. I think it can be related to your MS Edge rendering specific or some extensions behavior. Could you please perform the same steps as I did to see what's wrong on your side?

**Comment by GitScrum** [comment]
@AlexanderMoskovkin Hi, I think the problem is `resizeWindow`. I changed the value to 600 but the window did not change

![bug](https://user-images.githubusercontent.com/2789192/26883208-1eabfc8c-4ba5-11e7-9961-e208ff4b72a2.jpg)

**Comment by AndreyBelym** [comment]
Hello @GitScrum, I reproduced the problem with `resizeWindow` and Edge 15. It's related to the OS-specific native module: https://github.com/DevExpress/testcafe-browser-tools/issues/117. Need some to investigate and fix it. I will inform you when the fix will be available in a next alpha/release.

**Comment by GitScrum** [comment]
@AndreyBelym Hi, thanks for the feedback. And also I have problems with:
MacOS 10.12.5
Firefox DE 54.0b14 
Chrome 61.0.3122
Safari 10.1.1
![2017-06-08 0 08 54](https://user-images.githubusercontent.com/2789192/26901957-35ebf268-4be0-11e7-8734-f8b1aad3cd57.png)

**Comment by AndreyBelym** [comment]
Hello @GitScrum, we discovered that some apps can prevent TestCafe from accessing browser windows. In this case, relogin without session restore might be helpful.
