### ISSUE TITLE
Tests fail in PhantomJS because the DataTransfer class is not supported there

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#1522]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Any test fails in PhantomJS because it has no window.DataTransfer.

### What is the expected behavior?
Tests should not fail with an error about DataTransfer

### Specify your

* testcafe version: 0.16.0-alpha4

**Comment by AndreyBelym** [comment]
https://github.com/DevExpress/testcafe-hammerhead/pull/1170

**Comment by AlexanderMoskovkin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#1426](https://trello.com/c/dZOmIq5F/1-1426)
