### ISSUE TITLE
Test Parameterization

### ISSUE THREAD

**Issue by jesperalmstrom** [DevExpress/testcafe#1527]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
Have tried to find a way to run the same test with different parameters. 
In a similar concept that is shown in the older version of the API: 
https://testcafe.devexpress.com/Documentation/API_Reference/Test_Fixture_API/Common_Concepts/#Test_Parameterization

### What is the expected behavior?
Would be nice if you could explain if there is a way to have a parameter file like JSON to make this happen. Better than having 30+ similar test cases in one test JS file. 

### Specify your

* operating system: Windows 10
* testcafe version: 0.15.4
* node.js version: 8.1

**Comment by inikulin** [comment]
Hi, now you can generate tests by simply using language features, e.g.:
```js
const testCases = [
    { name: 'button1', selector: '#btn1' },
    { name: 'button2', selector: '#btn2' }
];

for (const c of testCases) {
    test(`Click ${c.name}`, async t => {
         await t.click(c.selector);
    });
}
```

**Comment by jesperalmstrom** [comment]
Thanks for rapid answer. 
I did try a similar approach but I declared testCases as a var: 
```js
var testCases = [
    { name: 'button1', selector: '#btn1' },
    { name: 'button2', selector: '#btn2' }
];

for (var c of testCases) {
    test('Test ' + c.name, async t => {
         await t.click(c.selector);
    });
}
```
the value of `c.selector` is always the last of the array. I guess that is because I don't use `const`?

**Comment by inikulin** [comment]
Yes. `const` and `let` are block scoped, whereas `var` is function scoped.

**Comment by pkundu06** [comment]
is it possible to provide hooks similar to testNG like @test(dataprovider="abc")

**Comment by AndreyBelym** [comment]
@pkundu06, IMHO the solution proposed in [this comment](https://github.com/DevExpress/testcafe/issues/1527#issuecomment-307931294) is very idiomatic for JS.
