### ISSUE TITLE
Throw an Error if Chrome-specific args are incorrect

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#1528]
### Are you requesting a feature or reporting a bug?
Improve argument checking

### What is the current behavior?
There is no descriptive error message if there are incorrect values in Chrome-specific arguments:
```
testcafe chrome:blabla:blabla=blabla test.js
```

### What is the expected behavior?
We should show a descriptive error message about what's wrong in the arguments string.

### Specify your

* testcafe version: 0.16.0-alpha4

**Comment by Farfurix** [comment]
For the team: I found an issue with the order of parameters [here](https://github.com/DevExpress/testcafe/issues/5221#issuecomment-645989828).
