### ISSUE TITLE
Type inference for customized Selectors in TypeScript

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#1529]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
Currently you have to specify interfaces of customized Selector and customized Snapshot: https://github.com/DevExpress/testcafe/blob/master/test/server/data/test-suites/typescript-defs/selectors.ts#L760

### What is the expected behavior?
These interfaces can be inferred automatically by Mapped Types from TypeScript 2.1: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html#mapped-types

### Specify your

* testcafe version: 0.16.0-alpha4

**Comment by inikulin** [comment]
How's that?

**Comment by inikulin** [comment]
ping @AndreyBelym

**Comment by AndreyBelym** [comment]
Ok, surprisingly Flow was better at generics, TypeScript has some issues:
 - This one prevents is required for inferring custom methods arguments: https://github.com/Microsoft/TypeScript/issues/5453

 - and this one for inferring custom methods/properties return type:
https://github.com/Microsoft/TypeScript/issues/9366

Without typechecking for arguments and return type it looks like:
```js
interface CustomPropertiesMap {
    {[prop: string]: (node: Element) => any})
}

interface CustomPropertiesOnSnapshot<T> {
    [P in keyof T]: any
}

interface CustomPropertiesOnSelector<T> {
    [P in keyof T]: Promise<any>
}

interface TestController {
    //...
   addCustomDOMProperties<T extends CustomPropertiesMap>(props: T): CustomSelector<T>;
   //...
}

interface CustomSelector<T> extends Selector, CustomPropertiesOnSelector<T> {
    (...args: any[]): CustomSelectorPromise<T>;
}

interface CustomSelectorPomise<T> extends SelectorPromise, CustomPropertiesOnSelector<T>, Promise<NodeSnapshot & CustomPropertiesOnSnapshot<T>> {
}
```
