### ISSUE TITLE
Running chrome headless not actually headless

### ISSUE THREAD

**Issue by RichiCoder1** [DevExpress/testcafe#1534]
### Are you requesting a feature or reporting a bug?
Reporting a Bug

### What is the current behavior?
When I run chrome in headless mode `chrome:headless` it's not, well, headless. When run, it still displays a browser window.

### What is the expected behavior?
Running chrome in headless mode will not display a browser window.

### How would you reproduce the current behavior (if this is a bug)?
It happens everytime for me. Can provide enviromnent details if necessary

#### Provide the test code and the tested page URL (if applicable)
I use the following npm run script:
`"test:headless": "testcafe \"chrome:headless\" src/**/*.spec.* --app \"npm run web\" --app-init-delay 20000 -q -S -s build_output/tests/screenshots"`
### Specify your

* operating system: Windows 10 (Fall Creators Update Insider Build 16215)
* testcafe version: 0.16
* node.js version: 8.0.0
* chrome version: 59

**Comment by AlexanderMoskovkin** [comment]
Hi @RichiCoder1,

Please take a look at the note in the [Running Tests in Headless Mode](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browser-support.html#running-tests-in-headless-mode) topic:

> Note that headless mode is available for Mac and Linux in Chrome 59. You need a [Canary build](https://www.google.com/chrome/browser/canary.html) to enable headless mode on Windows.

So, to use headless mode in Chrome on Windows it necessary to install a Canary build and run the command like: `testcafe "chrome:C:\Users\YourUserName\AppData\Local\Google\Chrome SxS\Application\chrome.exe:headless" test.js`
When the feature will be available in the stable version of Chrome on Windows you can use just `testcafe chrome:headless test.js`.

**Comment by RichiCoder1** [comment]
Ahh, I completely missed that. Just heard all the fuss about headless and both the docs and the official blog had support in little text haha.
