### ISSUE TITLE
Unable to take screenshots with testcafe docker

### ISSUE THREAD

**Issue by elaygl** [DevExpress/testcafe#1540]
### Are you requesting a feature or reporting a bug?
**Bug**

### What is the current behavior?
When trying to take screenshots in a test that runs on testcafe's docker image, I'm getting the following warning:
```
Warnings (1):
 --
  Was unable to take a screenshot due to an error.

  spawn /opt/testcafe/node_modules/testcafe-browser-tools/bin/linux/64/screenshot ENOENT
```
and no screenshot is taken.

### What is the expected behavior?
A screenshot will be taken and the image file will be placed in the right directory.

### How would you reproduce the current behavior (if this is a bug)?
Try to run any test with `t.takeScreenshot( [path] )` with testcafe's docker.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
any url.

Test code
```js
test('take screenshot', async t => {
    await t.takeScreenshot()
});
```

### Specify your

* operating system:
testcafe docker - linux alpine
* testcafe version:
0.16.0
* node.js version:

**Comment by AndreyBelym** [comment]
Hi @elaygl, I reproduced the problem, trying to fix it ASAP.
