### ISSUE TITLE
Clear out the localStorage after test

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe#1546]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

Each test is run with the new session id. The test writes some large data into the localStorage with key generated by page url and session id. After some tests, the error occurs:
```
Error: Failed to set the 'hammerhead|storages-sandbox-temp' property on 'Storage': Setting the value of 'hammerhead|storages-sandbox-temp' exceeded the quota.
```

### What is the expected behavior?

The localStorage must be cleaned after each test.

### How would you reproduce the current behavior (if this is a bug)?

Tested server:

```js
var http = require('http');

http.createServer(function (req, res) {
    if (req.url === '/') {
        res.writeHead(200, { 'Content-Type': 'text/html' });
        res.end(`
            <body>
                <script>
                    localStorage.setItem('item', new Array(1e6).join('1'));
                    setTimeout(function () {
                        document.body.appendChild(document.createElement('input'));
                        setTimeout(function () {
                            location.href = '/page';
                        }, 1000);
                    }, 1000);
                </script>
            </body>
        `);
    } else if (req.url === '/page') {
        res.writeHead(200, { 'Content-Type': 'text/html' });
        res.end('<h1>hello</h1>');
    } else {
        res.end();
    }
}).listen(8787);
```

Test code

```js
fixture `Error`
    .page `http://localhost:8787/`;

for (var i = 0; i < 5; i++) {
    test('test', async t => {
        await t
            .click('input')
            .click('h1');
    });
}
```

![image](https://user-images.githubusercontent.com/5373460/27296254-cc878736-5528-11e7-90e6-4db588869ae1.png)

### Specify your

* testcafe version: 0.16.0

**Comment by ww8912188** [comment]
This issue is really annoying. As a temporary workaround, I divided my tests into small pieces. Anyway, looking forward to the fix.

**Comment by AlexanderMoskovkin** [comment]
It shouldn't take too much time to fix it and provide you with the new version

**Comment by LavrovArtem** [comment]
Hi @ww8912188,
As a temporary workaround clear the `localStorage` after each test. You can use the `afterEach` [test hook](http://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#test-hooks) for this:
```js
fixture `Tests`
    .page `http://localhost:8787/`
    .afterEach(async t => {
        await t.eval(() => localStorage.clear());
    });
```
