### ISSUE TITLE
Selector's `withAttribute` method should filter attribute by strict name match when string argument is provided

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#1548]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

We always convert the `withText` and `withAttribute` methods' arguments to RegExp

Based on [a question in discuss](https://testcafe-discuss.devexpress.com/t/a-question-about-behavior-of-withattribute-selector/325): our documentation don't contains enough information about work of Selector's filter methods

### What is the expected behavior?

We should filter attribute by strict name match when string argument is provided

We should add required info

**Comment by inikulin** [comment]
I believe that's a bug that you can't filter attr by strict name match when string argument is provided.

**Comment by helen-dikareva** [comment]
Ok, let's change this behaviour

**Comment by VasilyStrelyaev** [comment]
Since we decided to change the behavior to an intuitive one, this issue doesn't require documentation anymore. Am I wrong?

**Comment by helen-dikareva** [comment]
Yep, you're right, that's why this issue has `Documentation: required` label
