### ISSUE TITLE
Don't create thumbnails by default

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#1550]
### Are you requesting a feature or reporting a bug?
Features

### What is the current behavior?
Thumbnails are always generated when taking screenshots.

### What is the expected behavior?
Give an option to disable screenshot generation.

### Specify your

* testcafe version: 0.16.1

**Comment by jiteshsojitra** [comment]
+5. Is there any plan to provide this option?

**Comment by AlexSkorkin** [comment]
Yes, we do have plans to implement this option as you can see by the issue state (Open) and the Milestone (Planned). I can't, however, provide you with a precise date as to when it may be introduced.

**Comment by trooperjey01** [comment]
Hi,

Are there any update about this issue ?
