### ISSUE TITLE
Option element is not visible error is thrown even though it is selected by click function.

### ISSUE THREAD

**Issue by ismailgmutlu** [DevExpress/testcafe#1559]
### Are you requesting a feature or reporting a bug?
Reporting a bug

### What is the current behavior?
Option in the combobox is selected by the act.click() function but it throws "A target element of the "click" action ("
<li class="select2-results__option">
") is not visible. If this element should appear when you are hovering over another element, make sure that you properly recorded the Hover action." error.

### What is the expected behavior?
After selecting the element it should continue execution.

### How would you reproduce the current behavior (if this is a bug)?

If we click an option element it throws element not visible error after selecting it. While recording it does not throw any errors but while playing the record it throws the error.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: (not applicable)

Test code: 
"@test"["withcharity4"] = {
    '1.Click image button "Submit"': inIFrame($("#test"), function() {
        act.click("#loginButton");
    }),
    "2.Type in input": inIFrame($("#test"), function() {
        act.type("#username", "username");
    }),
    "3.Type in password input": inIFrame($("#test"), function() {
        act.type("#password", "password");
    }),
    '4.Click submit button "GİRİŞ"': inIFrame($("#test"), function() {
        act.click("#login");
    }),
    '5.Click radio button "[object Object]"': inIFrame($("#test"), function() {
        var actionTarget = function() {
            return $("#inst_2").find("[name='taksit-option']");
        };
        act.click(actionTarget);
    }),
    '6.Click submit button "ÖDEME YAP"': inIFrame($("#test"), function() {
        act.click("#pay");
    }),
    '7.Click link "tıklayın"': inIFrame($("#test"), function() {
        var actionTarget = function() {
            return $(":containsExcludeChildren(tklayn)").eq(0);
        };
        act.click(actionTarget);
    }),
    "8.Click span": inIFrame($("#test"), function() {
        act.click("#app > section > div.container > div.form-group > span > span.selection > span > span.select2-selection__arrow");
    }),
    '9.Hover over list': inIFrame($("#test"), function() {
        act.hover(".select2-selection__rendered");
    }),
    '10.Click list item "Sanal Market"': inIFrame($("#test"), function() {
        act.click("span > .select2-dropdown .select2-results .select2-results__options li");
    }),
    '11.Click submit button "DEVAM"': inIFrame($("#test"), function() {
        act.click("#selectCharityButton");
    }),
    "12.Type in input": inIFrame($("#test"), function() {
        act.type("#verificationCodeNumeric", "987654");
    }),
    '13.Click submit button "ONAYLA"': inIFrame($("#test"), function() {
        act.click(":containsExcludeChildren(ONAYLA)");
    })
};

```js

```

### Specify your

* operating system: Win 10
* testcafe version: 15.1.3
* node.js version:  6.11.0

**Comment by AlexanderMoskovkin** [comment]
Hi @ismailgmutlu,
 
Please note that there are two TestCafe versions: 
- [Open source version](https://github.com/DevExpress/testcafe). In this repository, we discuss questions about this version only.
- [Paid version (15.1.3)](https://testcafe.devexpress.com/) with the recorder. If you have questions about the paid version, please submit tickets at [DevExpress Support Center](https://www.devexpress.com/Support/Center/Question/Create).
 
As far as I understand, your test failed at step 5. Possibly, it is necessary to add a click on the appropriate `select` element before it.
 
If you need our further assistance with the paid TestCafe version (15.1.3), use [DevExpress Support Center](https://www.devexpress.com/Support/Center/Question/Create).

**Comment by AlexSkorkin** [comment]
Hi,
 
Thank you for your clarification. All commercial version inquiries must be submitted to the [Support Center](http://www.devexpress.com/sc). This place is for a different TestCafe version.
