### ISSUE TITLE
Error running headless mode with Google Chrome version 59

### ISSUE THREAD

**Issue by afcbpeter** [DevExpress/testcafe#1561]
### Are you requesting a feature or reporting a bug?
Bug? 

### What is the current behavior?
Currently attempting to run Testcafe in headless mode and receiving an error. 

TypeError: Cannot read property 'connectionString' of undefined
    at new SubscriptionStore (/Users/peterki/IdeaProjects/hermes-ui-tests/test/storage/subscription-store.js:14:25)
    at Object.<anonymous> (/Users/peterki/IdeaProjects/hermes-ui-tests/test/storage/subscription-store.js:73:18)
    at Object.<anonymous> (/Users/peterki/IdeaProjects/hermes-ui-tests/test/spec/audit-search-page.test.js:13:1)

### What is the expected behavior?
Should run in headless mode. Not sure if my path is incorrect

### How would you reproduce the current behavior (if this is a bug)?
testcafe "chrome:./Users/peterki/Library/Application Support/Google/Chrome:headless" npm test

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: OSX
* testcafe version:     "testcafe": "0.15.0",
    "testcafe-hammerhead": "10.8.0",
* node.js version: 4.2.0

**Comment by AndreyBelym** [comment]
Hello @afcbpeter, unfortunately there is a little information about what's going on. Stacktrace shows that there is an error in your test code (/Users/peterki/IdeaProjects/hermes-ui-tests/test/storage/subscription-store.js at line 14, column 25). Can you give the test code, and full TestCafe output, please?

**Comment by AndreyBelym** [comment]
Also the command that runs TestCafe looks very strange (because of `npm test` in the place of testfile), are you sure that it isn't wrong?

**Comment by afcbpeter** [comment]
Well that is the full error from testcafe, not entirely comfy giving all the code out, on a positive note that actually does work. I'm just scratching my head a little. I've altered the package.json so it runs the test using npm test however just for the purposes of this. I've also ran this.

testcafe "chrome:./Users/peterki/Library/Application Support/Google/Chrome:headless" audit-search-page.test.js

ERROR No test file specified.

**Comment by AndreyBelym** [comment]
From the original post I understand that `audit-search-page.test.js` located in `/Users/peterki/IdeaProjects/hermes-ui-tests/test/spec` directory. So if this directory is not your current directory when you run TestCafe, you will get no test file error because the file doesn't exists here. You can try to specify absolute path for the test file: `testcafe "chrome:./Users/peterki/Library/Application Support/Google/Chrome:headless" /Users/peterki/IdeaProjects/hermes-ui-tests/test/spec/audit-search-page.test.js`.

**Comment by afcbpeter** [comment]
Im still getting the same error with the absolute test path. So I will go away and investigate this a bit further.
