### ISSUE TITLE
Any plans for the native apps testing?

### ISSUE THREAD

**Issue by vasyas** [DevExpress/testcafe#1562]
### Are you requesting a feature or reporting a bug?
Feature

I find TestCafe to be very developer-friendly and easy to use.
And it would be great if I can use the same approach for testing native android/ios apps.

So any plans to implementing native testing?

**Comment by AlexanderMoskovkin** [comment]
Hi Vasyl,

Thanks for your interest in our project. I believe that our approach would be useful for testing mobile apps. But our project is web-based and it necessary to rework almost the whole project to support it. So we don't plan to support native mobile apps testing for now.
