### ISSUE TITLE
switchToIFrame doesn't support frame

### ISSUE THREAD

**Issue by FrankV01** [DevExpress/testcafe#1565]
### Are you requesting a feature or reporting a bug?
I believe this is a bug but it could be viewed as a feature request. Depends on the intended original implementation.

### What is the current behavior?
The web page I've attempting to manipulate has a frameset with three frames. I need to activate the middle one and am hence trying to use `switchToIFrame` such as this: 

```
await t.switchToIframe(Selector('frame').nth(1))
```

I get an error stating"The action element is expected to be an <iframe>." 

### What is the expected behavior?
Activate the frame in the same manner an iframe would be activated

### How would you reproduce the current behavior (if this is a bug)?
Create a test page with a frameset and attempt to use your API on it. 

### Specify your

* operating system: Windows 7 Pro
* testcafe version: 0.16.1
* node.js version: v6.10.2

**Comment by AlexanderMoskovkin** [comment]
Hi @FrankV01,

`frameset` is an [obsolete](https://www.w3.org/TR/html/obsolete.html#non-conforming-features) feature. TestCafe has limited `framesets` support but we can't guarantee that all cases work properly. We will check whether we can fix switching to `frame` via the `switchToIframe` or not and will notify you.

**Comment by FrankV01** [comment]
First, thank you. Second, I do know it's an obsolete feature. Its use in the tech stack I'm working on is beyond my control and despite requests to do so, removal isn't slated. I'm dealing with it best I can. Again, I appreciate any attention you can give this matter.

**Comment by guptaakhil** [comment]
please suggest if we can find elements with in Frame like this way (#myFrame #myLocator) instead of switching this by method t.switchToFrame()

**Comment by AlexanderMoskovkin** [comment]
Hi @guptaakhil,

The `switchToFrame()` function is the only way to work with elements inside iframes in TestCafe tests.

**Comment by AlexanderMoskovkin** [comment]
It will cost too much for us to support this obsolete browser feature. So, we are not going to implement this in the near future.
