### ISSUE TITLE
Chrome 59 headless on Debian failing

### ISSUE THREAD

**Issue by marchugon** [DevExpress/testcafe#1569]
### Are you requesting a feature or reporting a bug?
This is a bug

### What is the current behavior?
When I try to launch a test with the new chrome 59 in headless mode, after 2 minutes, it fails with the error `ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.`
I'm launching my test with this command line : `testcafe "chrome:headless" mytest.js`
Chrome version is 59.0.3071.109
Headless mode is working on my debian, I've verified it with the command 
`google-chrome --headless --dump-dom https://www.chromestatus.com/`
But I have this error showing on startup : 
```
[0626/113914.060209:ERROR:gpu_child_thread.cc(174)] Exiting GPU process due to errors during initialization
[0626/113914.217726:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
```
As stated here (https://developers.google.com/web/updates/2017/04/headless-chrome), it may be better to launch google chrome in headless mode with the `--disable-gpu` option. I haven't found a way to test it.

### What is the expected behavior?
Well, it should find chrome

### How would you reproduce the current behavior (if this is a bug)?
Testing this feature under Debian maybe ?

### Specify your

* operating system: Debian 8.8
* testcafe version: 0.15.0 
* node.js version: v6.11.0

**Comment by AndreyBelym** [comment]
Hello @marchugon, TestCafe started to support Chrome Headless since `v0.16.0`, but you have reported 
> testcafe version: 0.15.0
Please, check your TestCafe version.
You can pass any Chrome options after `:headless`, so you can try `testcafe 'chrome:headless --disable-gpu' test.js`, but this GPU error shouldn't prevent starting the browser.
I'm installing Debian 8.8 now, and I assume that you use Chrome from Google repo ( not Chromium from Debian repos)  on x86_64 arch, right?

**Comment by AndreyBelym** [comment]
Also, did you try to start Chrome Headless without X11? Or maybe under root user?

**Comment by AndreyBelym** [comment]
Works on fresh-installed Debian Jessie 8.8 amd64, testcafe v0.16.0, node 6.11.0, google-chrome 59.0.3071.109, no X11 at all, with command `testcafe chrome:headless tests.js`.

**Comment by marchugon** [comment]
Sorry, my bad, running well after upgrade !
