### ISSUE TITLE
Syntax support in Webstorm

### ISSUE THREAD

**Issue by mnemanja** [DevExpress/testcafe#1574]
Hi!
I'd like to thank you for this awesome e2e solution. Keep up with the great work!

I'm wondering if there is a way to have the API be recognizable in Webstorm IDE?
I've had it installed both globally and then locally, but the syntax is not recognized.

I've added the screenshot of the problematic behavior in question.
Also, I have tried searching through the Webstorm's Javascript libraries > TypeScript community stubs, but with no success.

![image](https://user-images.githubusercontent.com/1423218/27626141-3ff3605e-5be7-11e7-92ec-ce67870dc32d.png)

* system: Windows 10:
* testcafe: 0.16.2:
* node: 6.10.0:

**Comment by AlexanderMoskovkin** [comment]
TestCafe bundles the TypeScript declaration file with the npm package, so you do not need to install it separately. As I now WebStorm should load TestCafe declaration file automatically if you have installed `testcafe` package locally.
We've tested it on the WebStorm v2017.1.3 (see the [screencast](https://www.screencast.com/t/X0nSkHF8B)). What WebStorm version do you use?

**Comment by mnemanja** [comment]
I'm using the 2017.1.4 version of the Webstorm.
I have no code quality tools enabled at the moment of testing.

I wonder about the list of Webstorm's Javascript Libraries in that Webstorm? In mine, I've disabled everything except HTML and it looks like this:
![image](https://user-images.githubusercontent.com/1423218/27639615-0903d5e4-5c17-11e7-9b01-eb5abce12633.png)

And here is the list of libraries in my IDE:
![image](https://user-images.githubusercontent.com/1423218/27639657-22767810-5c17-11e7-8fb5-d084692ca668.png)

**Comment by miherlosev** [comment]
Please, [export your WebStorm settings](https://www.jetbrains.com/help/webstorm/exporting-and-importing-settings.html#export) and send them to us.

**Comment by mnemanja** [comment]
Sure thing, Here it is!
[settings.zip](https://github.com/DevExpress/testcafe/files/1119640/settings.zip)

**Comment by miherlosev** [comment]
I've imported your settings and my WebStorm still indexes typescript definitions from `TestCafe`.
Please, hover the cursor over the hightlighted word with an error and provide the displayed error message (as in [video](https://www.screencast.com/t/uY5n997MxRc)).

I've reproduced your issue when I turned off the `Use TypeScript Service` option.
![image](https://user-images.githubusercontent.com/4133518/27796431-9ef82650-6012-11e7-9b5a-e96058593d57.png)

Make sure that typescript is installed and WebStorm finds it.
Then check that `Use TypeScript Service` option is turned on.

**Comment by mnemanja** [comment]
I've, actually, never used typescript before.
Is it necessary to use it with Testcafe?

![image](https://user-images.githubusercontent.com/1423218/27819450-a6b8199e-609a-11e7-8d0d-c3b5a69714f6.png)

![image](https://user-images.githubusercontent.com/1423218/27819482-c975e8ee-609a-11e7-8215-a0ad5d8a3ad5.png)

**Comment by MarinaRukavitsyna** [comment]
TestCafe does not require TypeScript for creating tests. TypeScript is used for IDE code completion. So, the TypeScript Service should be enabled if you wish to use code completion for your IDE.

**Comment by mnemanja** [comment]
Hi Marina,

I've installed TypeScript 2.4.1 globally and have configured it, as shown in the image bellow, but the highlighting did not change.
![image](https://user-images.githubusercontent.com/1423218/27827973-1b24ed10-60ba-11e7-8a94-e6bdeef25236.png)

**Comment by Leksat** [comment]
I was able to get basic autocomplete in JS tests by adding `node_modules/testcafe/ts-defs/index.d.ts` as a JS library in PhpStorm settings:
<img width="1017" alt="screen shot 2017-09-07 at 12 47 25" src="https://user-images.githubusercontent.com/989015/30159916-f6c8585c-93d2-11e7-994e-a7dccd5d9878.png">

Result:
<img width="523" alt="screen shot 2017-09-07 at 12 49 58" src="https://user-images.githubusercontent.com/989015/30159934-ffc1dabe-93d2-11e7-8c24-dbec66dcc63a.png">

**Comment by mnemanja** [comment]
Thanks, @Leksat. 
Your suggested solution worked for me as well.
