### ISSUE TITLE
Question: How to use mixins

### ISSUE THREAD

**Issue by mnemanja** [DevExpress/testcafe#1578]
Hi! I would like to use mixins to organize and re-use my tests. However, the documentation on mixins seems to be in a different syntax and I'm not quite sure on how to proceed.

Could you please add here a simple example of defining and exporting a mixin in a separate file for, let's say, creating a record, and then reusing it in the test (import and apply).

Thanks a bunch!
Nemanja

**Comment by AlexanderMoskovkin** [comment]
Do you mean [this](https://testcafe.devexpress.com/Documentation/API_Reference/Test_Fixture_API/Common_Concepts/#Mixins) mixin documentation? If so it relates to the paid TestCafe version. The actual documentation about the open-source version is [here](https://devexpress.github.io/testcafe/documentation/getting-started/).

You can define reusable parts of code via regular functions. For example:
```js
import { t } from 'testcafe';

async function reusablePart () {
    await t
        .click('#some-btn')
        .typeText('#some-input', 'text');
}

test('my test', async t => {
    await reusablePart();
});
```

Also it's a good practice to use [Page Model](https://devexpress.github.io/testcafe/documentation/recipes/using-page-model.html) pattern. You can define reusable part in your page model.

**Comment by mnemanja** [comment]
I've meant the open source version. Much obliged :)
