### ISSUE TITLE
Custom runner, cannot use a glob

### ISSUE THREAD

**Issue by dhoko** [DevExpress/testcafe#1579]
Hey :wave: 

Imho it's better if we we can use a glob with the runner, instead of loading the glob ourselves and give to the `.src()` the output. Via the CLI we can give a glob.

### Are you requesting a feature or reporting a bug?
feature

### What is the current behavior?
An error

```js
{ Error: Cannot find a test source file at "/home/dhoko/[custom]/test/e2e/specs/**/*.js".
    at Compiler._callee$ (/home/dhoko/[custom]/node_modules/testcafe/lib/compiler/index.js
:106:35)
    at tryCatch (/home/dhoko/[custom]/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/dhoko/[custom]/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as throw] (/home/dhoko/[custom]/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/dhoko/[custom]/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dhoko/[custom]/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13 constructor: [Function: GeneralError] }

```

### What is the expected behavior?
Same as the one with the CLI, we load a glob, it works

#### Provide the test code and the tested page URL (if applicable)
Test code

```js
#!/usr/bin/env node

const createTestCafe = require('testcafe');
const {  ALL } = require('./config');

createTestCafe('localhost', 1664)
    .then((instance) => {
        const runner = instance.createRunner();

        return runner.src(ALL)
            .browsers(['chrome'])
            .run();
    })

```
If `ALL`   === `/home/dhoko/[custom]/test/e2e/specs/**/*.js` or `test/e2e/specs/` it doesn't work.
Via the CLI if the input is `test/e2e/specs/` testcafe creates this glob `test/e2e/specs/**/*@(.test.js|.js|.ts|.testcafe)` [cf](https://github.com/DevExpress/testcafe/blob/3f2be5311b51ec7967fce88bff3601f8022d295c/src/cli/argument-parser.js#L196)

### Specify your

* operating system: GNU/Linux Ubuntu 16.10
* testcafe version: 0.16.1
* node.js version: 7.0.0

**Comment by inikulin** [comment]
I guess it's a duplicate of https://github.com/DevExpress/testcafe/issues/980

**Comment by dhoko** [comment]
Woops I  forgot to check :grin:
