### ISSUE TITLE
TypeScript Performance

### ISSUE THREAD

**Issue by caseyWebb** [DevExpress/testcafe#1591]
### Are you requesting a feature or reporting a bug?

Bug / Perf Issue

### What is the current behavior?

Using the OOTB TypeScript support causes *significant* performance overhead.

The following are results from precompiling w/ tsc and running testcafe on the output vs. running testcafe on TypeScript files directly:

```
> npm run benchmark

> testcafe-slow-modules-example@ benchmark /Users/caseywebb/Code/testcafe-example
> echo TestCafé Version: $(testcafe --version) && npm run benchmark:prebuild && npm run benchmark:native

TestCafé Version: 0.16.2

> testcafe-slow-modules-example@ benchmark:prebuild /Users/caseywebb/Code/testcafe-example
> time sh -c 'tsc && testcafe chrome fixture/dist/index.js' > /dev/null


real    0m7.073s
user    0m3.328s
sys     0m0.370s

> testcafe-slow-modules-example@ benchmark:native /Users/caseywebb/Code/testcafe-example
> time testcafe chrome fixture/src/index.ts > /dev/null


real    0m20.673s
user    0m16.759s
sys     0m0.997s
```

### What is the expected behavior?

Compilation should be comparable with precompiling tests with `tsc`

### How would you reproduce the current behavior (if this is a bug)?

[funny you should ask](https://github.com/caseyWebb/testcafe-slow-typescript-example)

### System Details

* operating system: macOS 10.12 and Windows 10
* testcafe version: 0.16.2
* node.js version: 8.1.3

**Comment by AndreyBelym** [comment]
Hello @caseyWebb, likely we need to use `"exclude":  ["node_modules"]` when compiling TypeScript. Looks easy enough. Thank you for benchmarking 😄

**Comment by caseyWebb** [comment]
I didn't see that you'd made a commit in your fork and got to playing with this. I took a different route, so not sure you'll want it.

https://github.com/caseyWebb/testcafe/commit/83c720f7f3cbe23deed1dfa5490ca291e084117f

```
yarn benchmark v0.27.5
$ echo TestCafé Version: $(testcafe --version) && npm run benchmark:prebuild && npm run benchmark:native
TestCafé Version: 0.17.0-alpha2

> testcafe-slow-modules-example@ benchmark:prebuild /Users/caseywebb/Code/testcafe-example
> time sh -c 'tsc && testcafe chrome fixture/dist/index.js' > /dev/null


real    0m9.001s
user    0m5.503s
sys     0m0.483s

> testcafe-slow-modules-example@ benchmark:native /Users/caseywebb/Code/testcafe-example
> time testcafe chrome fixture/src/index.ts > /dev/null


real    0m7.214s
user    0m3.473s
sys     0m0.334s
```

I tried running the benchmarks on your branch but got the following error:

```
ERROR Cannot prepare tests due to an error.

TypeError: Cannot read property 'length' of undefined

Type "testcafe -h" for help.
```
