### ISSUE TITLE
DOMException thrown that "Blocked a frame from accessing a cross-origin frame"

### ISSUE THREAD

**Issue by hang-ren** [DevExpress/testcafe#1592]
### Are you requesting a feature or reporting a bug?
A bug

### What is the current behavior?
Sign-in page hanged and there is an exception thrown in console.

### What is the expected behavior?
Sign-in successfully.

### How would you reproduce the current behavior (if this is a bug)?
Just force sign-in case.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
http://alpha-www.gdfcx.net/
Test code

File1 ----- logindata.js:

import { Selector } from 'testcafe';

var usname = "18621504828";
var pwd = "123456";
var logina = Selector('li[class="no-login"]');
var loginpage = Selector('iframe[id="login-iframe"]');
var usernameInput = Selector('input[placeholder="手机/邮箱/用户名"]');
var pwdInput = Selector('input[placeholder="密码"]');
var loginBtn = Selector('a[class="sso-submit"]');

exports.usname = usname;
exports.pwd = pwd;
exports.logina = logina;
exports.loginpage = loginpage;
exports.usernameInput = usernameInput;
exports.pwdInput = pwdInput;
exports.loginBtn = loginBtn;

File2 ---- login.js:

import { t  } from 'testcafe';

var logindata = require('../data/logindata.js');

export default class LoginCSS {
    constructor () {
		this.logina = logindata.logina;
		this.loginpage = logindata.loginpage;
		this.usernameInput = logindata.usernameInput;
		this.pwdInput  = logindata.pwdInput;
		this.loginBtn  = logindata.loginBtn;
		this.loginLink = logindata.loginLink;		
    }
	
	async login () {
        await t
		.maximizeWindow()
		.wait(5000)
		.click(this.logina)
		.wait(2000)
		.switchToIframe(this.loginpage)
		.wait(2000)
		.typeText(this.usernameInput,logindata.usname)  
		.wait(2000)
		.typeText(this.pwdInput, logindata.pwd)
		.wait(2000)
		.click(this.loginBtn)
		.wait(2000)
		.switchToMainWindow()
		.wait(2000)
    }
}

### Specify your

* operating system: Win7
* testcafe version: 0.17.0-alpha1
* node.js version:v6.11.0

**Comment by hang-ren** [comment]
I think it is similar with issue#1580, could you please have a check. Greatly appreciated!

**Comment by hang-ren** [comment]
![default](https://user-images.githubusercontent.com/29770618/27948284-e6207e4e-632b-11e7-946e-1bb8adebd6bb.JPG)

**Comment by LavrovArtem** [comment]
Hi @hang-ren,
Unfortunatly, I cann't reproduces this issue. See video https://www.screencast.com/t/kZDwK56U

**Comment by hang-ren** [comment]
@LavrovArtem，

So weird. 
I saw you use "https" to access the link from the video, right? But in my code it is "http", could you help to double check the difference? From my side, I can sign-in successfully both with "https" and "http" manually.
Thanks a lot!

BRs,
Hang

**Comment by LavrovArtem** [comment]
Hi @hang-ren,

I use `http` link, but it immediately redirect to `https` via `301` status code and the `location` header.
![image](https://user-images.githubusercontent.com/5373460/28015055-15b187be-6577-11e7-9a7f-a0d4d226f40e.png)

Also please try to run your test in incognito mode in Chrome via command below:
`testcafe "chrome --incognito" test-name.js`

It excludes the possibility of the plugins affecting on the page.

**Comment by hang-ren** [comment]
Thanks @LavrovArtem , I had tried it as your mentioned but still met the same issue.
I think I need research my website firstly, maybe it is a bug from my website.
Thanks for your suggestion all the same. And please close this issue.

**Comment by LavrovArtem** [comment]
Thank you for your time. Please let me know if you find the cause of this behavior.
