### ISSUE TITLE
Allow to disable hipster spinning wheel on command line

### ISSUE THREAD

**Issue by manuelkiessling** [DevExpress/testcafe#1593]
### Are you requesting a feature or reporting a bug?

Feature

### What is the current behavior?

Running testcafe on the command line outputs a hipster version of an ASCII spinning wheel which under certain circumstances litters e.g. Jenkins output logs with megabytes of useless lines.

### What is the expected behavior?

Running testcafe on the command line with a certain parameter no longer outputs a hipster version of an ASCII spinning wheel which under certain circumstances litters e.g. Jenkins output logs with megabytes of useless lines.

### Specify your

* operating system: Linux
* testcafe version: 0.16.2
* node.js version: 7.10.0

**Comment by AndreyBelym** [comment]
Hello @manuelkiessling, currently we us [is-ci](https://www.npmjs.com/package/is-ci) package to disable CLI animation on CI systems like Jenkins. Maybe it's a bug in that package. BTW, you can declare/export the `CI` environment variable, and the hipster wheel must go away. 😉  Examples:

for bash:
```
CI=1 testcafe ...
```
cmd
```
set CI=1 
testcafe ...
```
powershell
```
$env:CI=1; node .\bin\testcafe.js chrome .\examples\basic\test.js
```
