### ISSUE TITLE
is it possible to use static port for testcafe remote runner 

### ISSUE THREAD

**Issue by gowram** [DevExpress/testcafe#1594]
### Are you requesting a feature or reporting a bug?
Can we config to run testcafe remote with specified port instead of dynamic port no.

### What is the current behavior?
Dynamic port get's assigned automatically.

### What is the expected behavior?
Config option to set static port like "8080".

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by inikulin** [comment]
Yes, it is possible via [--ports](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--ports-port1port2) option.
