### ISSUE TITLE
ClientFunction compilation issue

### ISSUE THREAD

**Issue by Freak613** [DevExpress/testcafe#1596]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
I passing following code to ClientFunction
```
const getPayload = ClientFunction(() => {
  const components = document.querySelectorAll('tbody tr')
  return [...components].map(c => {
    return c.childNodes
  })
})
```

At the output in browser I have
```
(function(){
    return (function () {
        var components = document.querySelectorAll('tbody tr');
        return [].concat(components).map(function (c) {
            return c.childNodes;
        });
    });
})();
```

### What is the expected behavior?
It looks like you have some precompilation for ClientFunction, that wrongly converts spread function to `[].concat(array)` while the correct code must be something like `[].slice.call(array)`
Let's not discuss why I'm working with nodes outside of framework scope, I could do similar spread operation with any other data
If you wouldn't fix this bug, at least it will be good to know what transpilers are you use for client code.

### Specify your

* testcafe version: 0.16.2
* node.js version: 6.7.0

** Updated **
## Related issues:
[#2100 Math.trunc ](https://github.com/DevExpress/testcafe/issues/2100)
[#2063 ClientFunction dependencies can’t be in another file](https://github.com/DevExpress/testcafe/issues/2063)

**Comment by AlexanderMoskovkin** [comment]
Hi,

We use [Babel](https://babeljs.io/) to compile JavaScript. We use [Loose mode](https://developit.github.io/babel-legacy-docs//docs/advanced/loose/) to compile the code inside `ClientFunction`. It allows us to avoid `babel-runtime` library using in the browser.
One on the loose mode caveats is `All iterable destructuring are assumed to be arrays.`

As a workaround you can avoid array destructuring in your code inside `ClientFunction`. Meanwhile we'll try to find a fix for this.

**Comment by AndreyBelym** [comment]
It's a part of https://github.com/DevExpress/testcafe/issues/2544 now.
