### ISSUE TITLE
Uncaught error in JSON.parse which brakes test task

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#160]
Run this test:

```js
"@fixture jj";

"@page http://tema.livejournal.com";

"@test"["qqq"] = {
    '1.Click <b> "tema"': function() {
        var bElement = $("#lj_controlstrip_new").find(":containsExcludeChildren(tema)");
        act.click(bElement, {});
    }
};
```

Test fail will be reported correctly, however after this error occurs in `JSON.parse` within Hammerhead (can't be reproduced in HHM) and task frozes.

**Comment by inikulin** [comment]
Any news on this?

**Comment by helen-dikareva** [comment]
It's done, but wait for some commits from @AlexanderMoskovkin

**Comment by AlexanderMoskovkin** [comment]
we'll fix it when the https://github.com/DevExpress/testcafe/pull/130 issue is closed to avoid merging problems. https://github.com/DevExpress/testcafe/pull/130 is close to be closed =)
