### ISSUE TITLE
DNS Issue

### ISSUE THREAD

**Issue by Freak613** [DevExpress/testcafe#1601]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
TestCafe constantly tries to resolve addresses before start , instead of direct usage, and constantly fails with it
```
Failed to find a DNS-record for the resource at "http://localhost:3000/"
```

### What is the expected behavior?
Either to fix DNS resolving algorithm which can't resolve localhost for example, or don't try to resolve itself just pass it as is to nodejs/system api that will done resolving in regular way.
What is the point for resolving address internally in testcafe?

### How would you reproduce the current behavior (if this is a bug)?
Try to test app runned locally at localhost with testcafe

### Specify your

* operating system: MacOS 10.12.2
* testcafe version: 0.16.2
* node.js version: v6.7.0

**Comment by AndreyBelym** [comment]
Hello @Freak613 , due to new multiprocess rendering in Firefox 54, it has troubles with running on Travis with Xvfb. Please, try to use Firefox 53, you can specify version (`53.0`) [here](https://github.com/medatc/vuet/blob/master/.travis.yml#L11).

**Comment by AndreyBelym** [comment]
Hello @Freak613! Unfortunately, the error text is quite misleading, (I've created an issue about that: https://github.com/DevExpress/testcafe/issues/1606). Of course in the `localhost` case, it's not related to DNS, but likely to the port or server connection in general. So:
 
 1. Check that you server is running on `localhost:3000`. Try to navigate to it with your browser.

 2. Check that there is no firewall rules that prevents Node.js or TestCafe from accessing localhost.

**Comment by Freak613** [comment]
Yes, I've checked, and it's not related to system configuration.
Error happens from time to time and it looks like app trying to do something that is not related to it. Node.js has it's own errors for networking and they're more clear in debugging of the core issue.
If you just wrapping node.js error, you can at least add original trace and error message to output.

**Comment by AlexanderMoskovkin** [comment]
#1606
