### ISSUE TITLE
Screenshot flexibility request

### ISSUE THREAD

**Issue by ClaytonAstrom** [DevExpress/testcafe#1602]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
Screenshot naming conventions are very restricted, command line parameter `-S` has no control at all.

### What is the expected behavior?
1)  Screenshots should have flexible naming conventions.  For example, [Junit Attachment Plugin](https://wiki.jenkins.io/display/JENKINS/JUnit+Attachments+Plugin) uses the `classname` xml attribute to associate the artifacts with the package, or uses absolute references
2)  Fixtures and/or tests should have the ability to individually take screenshots on fail.  Maybe a hook that can be defined per test?  If I have a fixture with:

	```js
	test("Test A", async => {});
    test("Test B", async => {});
    test("Test C", async => {});
	```
	Then I should be able to specify which tests I want to take a screenshot on failure.  Example:
    ```js
	test("Test A", async => {});
    test
      .screenShotOnFail(
		//Some kind of path structure here maybe?      
      )
      ("Test B", async => {});
    test("Test C", async => {});
	```

### Specify your

* operating system:  Windows 7
* testcafe version:  0.16.0
* node.js version:  6.10.1

Similar issues:  #1515 and #1595

**Comment by AlexanderMoskovkin** [comment]
closed in favor of #2152
