### ISSUE TITLE
fixture() call cannot be wrapped

### ISSUE THREAD

**Issue by peterwestendorp** [DevExpress/testcafe#1605]
### Are you requesting a feature or reporting a bug?
Requesting a feature

### What is the current behavior?
When I want to run Testcafe with the `testcafe` cli command I need to have a `fixture()` call in my code.
As long as you have `fixture()` in the code (even if it's just in a comment) Testcafe will run the tests. If you don't have that you'll get a "No tests to run." error.

### What is the expected behavior?
I would like to be able to wrap the fixture function. Just so that I don't have to specify the `beforeEach` and `afterEach` on each fixture. (they'll be all the same in my case).
```
let setupFixture = (name, url) => {  
 fixture(name).page(`http://localhost:11119${url}`).beforeEach(myBeforeFunction).afterEach(myAfterFunction);
};
```

### Specify your

* operating system: Windows 10
* testcafe version: 0.15
* node.js version: 7.10.0

**Comment by peterwestendorp** [comment]
My proposal would be to remove `FIXTURE_RE.test(code)` from https://github.com/DevExpress/testcafe/blob/master/src/compiler/test-file/api-based.js#L165
I tried to create a PR for that, but can't get the unit tests working, hence this lazy proposal... :-)

**Comment by AndreyBelym** [comment]
Hello @peterwestendorp, unfortunately it's a very serious design-level change, and I'm afraid we can't afford it yet. The recommended approach is to extract `myBeforeFunction` and `myAfterFunction` to a dedicated file, and then import and use them in your fixtures. E. g. https://github.com/surveyjs/surveyjs/blob/master/testCafe/settings.js, https://github.com/surveyjs/surveyjs/blob/master/testCafe/validation/standardValidators.js#L22. Also there is a similar feature that we are considering for implementation, you can vote for it if it may be useful for you: https://github.com/DevExpress/testcafe/issues/792,

**Comment by peterwestendorp** [comment]
Thanks for your response @AndreyBelym! In your first solution I would still have to add .beforeEach and .afterEach on each fixture manually, which is not ideal. I have now worked around the issue by doing this: 
```
let f = fixture('My fixture');
utils.setupFixture(f, '/some-page')
```
```
setupFixture = (fixtureInstance, url) => {
  fixtureInstance.page(`http://localhost:11119/pages${url}`)
    .beforeEach(foo)
    .afterEach(bar)
}
```
Ideally there would be some sort of global beforeEach and afterEach, like you have in Mocha: https://stackoverflow.com/questions/10561598/global-before-and-beforeeach-for-mocha
Would that be an easier solution? (This is very similar to the solution suggested in #792).

For now now I can work around the issue though, thanks! :-)

**Comment by inikulin** [comment]
Hmm, I guess it would be better to implement global `beforeEach` and `afterEach`, e.g.:
```js
import { beforeEach } from 'testcafe';

beforeEach(...); //This sets before each handler for all tests in the task.
```

and it will be a good chance to finally implement https://github.com/DevExpress/testcafe/issues/745
