### ISSUE TITLE
Wait upon network fecth and page re-render. 

### ISSUE THREAD

**Issue by gowram** [DevExpress/testcafe#1607]
### Are you requesting a feature or reporting a bug?
I would like to know is there any way to wait till network fetch completes. 
I have a page in which DOM load first then data gets load, upon data page will re-render again but my click event gets fired when initial DOM load happens and it's get crashed. 

### What is the current behavior?
Currently wait functionality works against DOM load

### What is the expected behavior?
I want to have wait after page  re-render.

### Specify your

* operating system: windows
* testcafe version: 0.16.2
* node.js version: 8.1.3

**Comment by helen-dikareva** [comment]
Hello @gowram.
To determine that the page is fully re-rendered, you can check whether some specific element that appears after re-rendering is actually displayed. Use our [Smart Assertion Query Mechanism](https://devexpress.github.io/testcafe/documentation/test-api/assertions/#smart-assertion-query-mechanism) and introduce an appropriate timeout, e.g.:
```js
import { Selector } from 'testcafe';

fixture `fixture`
    .page `http://localhost/testcafe`;

test('test with Assertion', async t => {
    await t
        .expect(Selector('#textarea').exists).ok({ timeout: 20000 })
        .click('#textarea');
});
```

Alternatively, you can check any condition that is met when the page is loaded
using the [ClientFunction](https://devexpress.github.io/testcafe/documentation/test-api/obtaining-data-from-the-client.html#creating-client-functions), e.g.:

```js
import { ClientFunction } from 'testcafe';

fixture `fixture`
    .page `http://localhost/testcafe`;

test('test with ClientFunction', async t => {
    var waitForElementLoading = ClientFunction(() => {
        return new Promise(resolve => {
            window.setInterval(() => {
                if (document.getElementById('textarea'))
                    resolve();
            });
        });
    });

    await waitForElementLoading();

    await t.click('#textarea');
});
```

**Comment by gowram** [comment]
I tried this one and expect is waiting for before dom load, i am looking form something after dom load. 
```js
test('test with Assertion', async t => {
    await t
        .expect(Selector('#textarea').exists).ok({ timeout: 20000 })
        .click('#textarea');
});
```

**Comment by helen-dikareva** [comment]
It's not quite clear. What was the result of using `Assertion` for waiting for page loading? Does this approach work for you?
