### ISSUE TITLE
Can i capture ajax request or `createSpy ` api

### ISSUE THREAD

**Issue by chenby** [DevExpress/testcafe#1610]
### Are you requesting a feature or reporting a bug?

i want to test a case that when i scroll to the bottom and send a ajax request.

what should i do?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by AlexanderMoskovkin** [comment]
Hi @chenby,

To scroll a page to the bottom you can use the [hover](https://devexpress.github.io/testcafe/documentation/test-api/actions/hover.html) action:
```js
await t.hover('body', { offsetY: -1 });
```

You can send an xhr-request via [ClientFunction](https://devexpress.github.io/testcafe/documentation/test-api/obtaining-data-from-the-client.html#creating-client-functions):
```js
const sendXhr = ClientFunction(() => {
    // here is xhr sending code
});

await sendXhr();
```

**Comment by chenby** [comment]
Thanks。
I mean that my website send an xhr-request,and How do i know it can work.

**Comment by AlexanderMoskovkin** [comment]
It there some results of this xhr-request? I suppose it should be some new markup? If so, you can check that the markup is added.

```js
await t
    .hover('body', { offsetY: -1 })
    .expect(Selector('some-new-element').exists).ok();
```

**Comment by chenby** [comment]
It just report some event, and return `{code：200}`

**Comment by AlexanderMoskovkin** [comment]
We have no such built-in functionality but we've planned to implement it: #1341.

As a workaround you can use some third-party library to handle requests, for exapmle [nock](https://github.com/node-nock/nock#recording)

**Comment by chenby** [comment]
Thanks a lot
