### ISSUE TITLE
Scrolling body doesn't work

### ISSUE THREAD

**Issue by Freak613** [DevExpress/testcafe#1611]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
```
   1) AssertionError: expected 593 to deeply equal 0

      Browser: Chrome 60.0.3112 / Mac OS X 10.12.2

         32 |    await t.eval(() => {window.document.body.scrollTop=0;})
       > 33 |    await t.expect(Selector('body').scrollTop).eql(0)

```
Same with `window.scrollTo` and any other native js ways to scroll the window to top. It just doesn't scroll.
I have the page where automated scrolling with hover/click doesn't work. I see that cursor is moving outside visible area but scrolling not happened.
Anyway, page may be any kind, just strange that above test can't be passed in any ways.

### Specify your

* operating system: Mac OS X 10.12.2
* testcafe version: 0.16.2

**Comment by thecodejack** [comment]
it may not be related, but FTR I put up a setTimeOut with await after scrolling, to get it worked.

**Comment by Freak613** [comment]
setTimeout also don't work
Can you provide code snippet?

**Comment by Freak613** [comment]
I just figured out that scrolling works, we just have some react plugin on the page that performs some scroll animation and this animation triggers after I'm resetting scroll position or has some significant duration.

**Comment by haoshasha** [comment]
let s = Selector('.page-tab:not(.ng-hide) .contentPage')


            const sn = ClientFunction((el) => {
                return el().scrollTop = 650;
            }).with({boundTestRun: cafe});
            await sn(s)
