### ISSUE TITLE
DOM Node Snapshot example in docs is not clear

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#1614]
https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors.html#dom-node-snapshot

The description is ok, the code example works but in fact it shows how to use selector's properties but not a snapshot. To show how to use a snapshot the example should be like this:
```js
import { Selector } from 'testcafe';

fixture `My fixture`
    .page `http://devexpress.github.io/testcafe/example/`;

test('DOM Node Snapshot', async t => {
    const sliderHandle = Selector('#slider').child('span');
    const sliderHandleSnaphot = await sliderHandle();

    console.log(sliderHandleSnaphot.hasClass('ui-slider-handle'));    // => true
    console.log(sliderHandleSnaphot.childElementCount);                // => 0
});
```
/cc @VasilyStrelyaev

**Comment by rock9u** [comment]
`sliderHandleSnaphot` has a typo, it should be `sliderHandleSnapShot`

**Comment by VasilyStrelyaev** [comment]
Thanks, I've fixed it here and in the docs!
