### ISSUE TITLE
Is there a way to get npm variables inside testing?

### ISSUE THREAD

**Issue by ganlanyuan** [DevExpress/testcafe#1620]
IE9- using `tabIndex` attribute rather than `tabindex`. The following test will get an `undefined` error on IE9-.
```javascript
.expect(await container.getAttribute('tabindex')).eql('0')
```

I would like to set an environment variable on the `npm run` command and set the `tabindex` string based on that variable in my test.
```javascript
{
  "script": {
    "ie": "testcafe \"browserstack:ie@9.0:Windows 7\" tests/features/base.js --isie=true"
  }
}
```
My question is: is there a way that I can get the `isie` variable in my test.

Currently I can only use `||` to make it work for both IE and other browsers:
```javascript
.expect(await container.getAttribute('tabindex') || await container.getAttribute('tabIndex')).eql('0')
```

**Comment by AlexanderMoskovkin** [comment]
Hi,

You can use `process.argv` to check options:
```js
const isIE = process.argv.indexOf('--isie') > -1;
```

As an alternative you case check it via userAgent: 
```js
const ua = await t.eval(() => navigator.userAgent);
```
You can parse it with some module, for example [UAParser.js](https://github.com/faisalman/ua-parser-js)

**Comment by ganlanyuan** [comment]
Thanks
