### ISSUE TITLE
Repeat a group of actions several times

### ISSUE THREAD

**Issue by ganlanyuan** [DevExpress/testcafe#1621]
### Are you requesting a feature or reporting a bug?
feature

### What is the current behavior?
Have to repeat a command many times:
```javascript
await t
  .click(button)
  .wait(300)
  .click(button)
  .wait(300)
  .click(button)
  .wait(300)
  .click(button)
  .wait(300)
  .doTheTest();
```

### What is the expected behavior?
Can we have a `repeat` command so that I can do:
 ```javascript
await t
  .repeat(4,
    await t
      .click(button)
      .wait(300)
  )
  .doTheTest();
```
The syntax maybe wrong, but you know what I mean right?
Thanks

**Comment by AlexanderMoskovkin** [comment]
Hi William,

Thanks for the proposal, but it can be easily implemented with pure js:
```js
for(let i = 0; i < 4; i++) {
    await t
        .click(button)
        .wait(300)
}

// or
async function actions () {
    await t
        .click(button)
        .wait(300);
}

let counter = 4;

while(counter--)
    await actions();
```

With this I don't see a reason to add such compicated syntax like
```js
await t
 .repeat(4, () => {
   await t
     .click(button)
     .wait(300)
})
 .doTheTest();
```

If you'd like to add all actions to a chain, we have a proposal for this: #1535.

**Comment by ganlanyuan** [comment]
Thanks, 
Pure js is enough
