### ISSUE TITLE
Keep TestCafe running for rapid development

### ISSUE THREAD

**Issue by jvanoostveen** [DevExpress/testcafe#1624]
### Are you requesting a feature or reporting a bug?
Feature request.

### What is the current/expected behavior?
After each testrun, TestCafe stops and closes the browser window(s).
During the development of the integration tests, the startup and teardown of TestCafe is very time consuming.
It would be nice to have TestCafe remain open/active and watching for changes in the test files. If a change is made, the current running tests would abort and the updated test files loaded and executed. All this without TestCafe doing it's browser resize dance and bootstrapping :).

If such behavior is already possible, please direct me to the documentation :).

**Comment by tamlyn** [comment]
I've been evaluating [Cypress](https://github.com/cypress-io/cypress) alongside Testcafe and watch mode is something that they really do right. It's so fast it makes writing E2E tests feel as good as writing unit tests.

**Comment by AlexanderMoskovkin** [comment]
Hi, thanks for your feedback. I believe the watch mode is a very useful thing. I guess we'll provide some news about this the next week.

**Comment by pierreh** [comment]
Is there any update on this feature? We would really appreciate it. Thanks!

**Comment by AlexanderMoskovkin** [comment]
Hi @pierreh,

It's in the testing stage now and you can already try it. Take a look at the [DevExpress/TestCafe Live](https://github.com/DevExpress/testcafe-live) repository. Any early feedback is appreciated.

**Comment by pierreh** [comment]
Thanks Alexander, looking forward to it. We have just decided to adopt TestCafe and run both endpoint tests and browser tests in one package.
I hope in the future TestCafe can be integrated into other runners as well, like AVA.

**Comment by xcb6** [comment]
https://github.com/DevExpress/testcafe-live is broken

**Comment by AlexanderMoskovkin** [comment]
Hi @xcb6,

> testcafe-live is broken

Could you please clarify what do you mean? You can't install it or can't run tests?

I call the following command on my machine and it runs tests succesfully:

```sh
npm install testcafe testcafe-live -g
testcafe-live chrome d:\tests\example\example.js
```

**Comment by xcb6** [comment]
https://github.com/DevExpress/testcafe-live => 404

**Comment by AlexanderMoskovkin** [comment]
oops. you're right. Fixed

**Comment by xcb6** [comment]
feedback (npm install) => very very great !!!! it's ok on win7

**Comment by AlexanderMoskovkin** [comment]
Hi everyone who is interested in this feature. We've done some work and published the [testcafe-live](https://www.npmjs.com/package/testcafe-live) module. The full description about it you can read in the [TestCafe Live](https://github.com/DevExpress/testcafe-live#testcafe-live) repository.
It would be greatly appreciated if you try it and provide us with your feedback! 

/cc @jvanoostveen @chandureddivari @kartojal, @tamlyn @jonataswalker @gmschouten @fiws @noderat @RickHoving @FabioAntunes @Dattaya @tijhaart and others

**Comment by AndreyBelym** [comment]
\cc @ganlanyuan @ervoiox @chinjon @ablipan @pierreh @xcb6

**Comment by AlexanderMoskovkin** [comment]
We've done this in [TestCafe Live](https://github.com/DevExpress/testcafe-live) so I close the issue. I guess we'll add info about it to the Readme soon.
