### ISSUE TITLE
Skip tests conditionally

### ISSUE THREAD

**Issue by gmschouten** [DevExpress/testcafe#1626]
### Are you requesting a feature or reporting a bug?

Requesting a feature

### What is the current behavior?

Tests can only be skipped unconditionally:

``` javascript
test.skip('testing mobile', async t => {});
````

### What is the expected behavior?

Skip tests depending on certain conditions:

``` javascript
test
    .skip(function (t) {
        return t.ctx.foo === 'bar' && process.env.abc === 'xyz';
    })
    ('test name', async t => {...});
```

**Comment by AlexanderMoskovkin** [comment]
Hi @gmschouten,

Thanks for the proposal.
Also we have a related issue: [Implement `t.browserInfo`](https://github.com/DevExpress/testcafe/issues/481) issue. The `browserInfo` can be used if `skip` conditional

**Comment by kot-lex** [comment]
Any news here?

**Comment by TychonautVII** [comment]
+1

**Comment by ricwal-richa** [comment]
+1

**Comment by hex0cter** [comment]
+1

**Comment by chinjon** [comment]
+1

**Comment by chinjon** [comment]
I found a way to handle this but it's not scalable. I use this solution to skip over tests that require window resize, but can't be performed due to devices the test is running on, IE: mobile device browsers.

I created a function that leverages clientFunctions and obtains the document width (or height if your test is dependent on height) and conditionally run test:

```
test
const pageWidth = getPageWidth();
if (pageWidth < 1000) {
  // do test stuff
} else {
  console.log('SKIP TEST: Does not meet dimension requirements')
}
```

**Comment by AndreyBelym** [comment]
Hi @ricwal-richa @hex0cter @chinjon, unfortunately there is a design flaw in our report system, which leads to reporting wrong number of runned and failed tests when canceling tests after test suite is started. So we need to redesign reporting plugins API and make a breaking change to properly support this feature. 

Due to this complications, I should say that implementation for this feature will take a long time, but PRs are welcome as always.

**Comment by hex0cter** [comment]
This is way I am using currently:

```javascript
const testDesktop = (name, testToRun) => {
  name = `${name} - desktop only`
  if (process.env['MOBILE'] !== 'yes') {
    test(name, testToRun)
  } else {
    test.skip(name, testToRun)
  }
}

testDesktop.skip = (name, testToRun) => {
  test.skip(name, testToRun)
}
```
Then call it like below:
```javascript
testDesktop('Field validation', async t => {
  await t
    .navigateTo(`${baseURL}&fixture=default`)
    .typeText(form.dateOfBirth.field, '123123')
```

There is a similar for mobile. In our case I set a environment variable to distinguish the devices.

**Comment by evegreen** [comment]
> This is the way I am currently using:
> 
> ```js
> const testDesktop = (name, testToRun) => {
>   name = `${name} - desktop only`
>   if (process.env['MOBILE'] !== 'yes') {
>     test(name, testToRun)
>   } else {
>     test.skip(name, testToRun)
>   }
> }
> 
> testDesktop.skip = (name, testToRun) => {
>   test.skip(name, testToRun)
> }
> 
> export default testDesktop
> ```
> 
> Then call it like below:
> 
> ```js
> testDesktop('Field validation', async t => {
>   await t
>     .navigateTo(`${baseURL}&fixture=default`)
>     .typeText(form.dateOfBirth.field, '123123')
> })
> ```
> 
> There is a similar method for mobile. In our case I set an environment variable to distinguish the devices.

hi @hex0cter , does your solution works on testcafe version 0.23.3 ?

**Comment by adrian-inafuku-olx** [comment]
Hi @hex0cter , is there a way to pass (.meta) data and use it as a condition to whether run or skip the test? 
Thanks and regards,

**Comment by AlexKamaev** [comment]
@adrian-inafuku-olx is that the [feature](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--test-meta-keyvaluekey2value2) you are looking for?

**Comment by adrian-inafuku-olx** [comment]
@AlexKamaev no, thanks. What I am looking for is to pass test-metas as parameters to implement something similar to what @hex0cter did. 
I need to run some test cases conditionally. To give you an example:
I have for all of the test cases, a meta which identifies if a TCs should be run within smoke or regression test. In addition, I need to run some specific test cases based on a market condition. 
What I did was: 
`
testMarketCondition
    ('Show number (not logged in)', ['olxin', 'olxpk'], [{ smokeTest: 'false', regressionTest: 'true' }], async t => {
// TC commands
    });
`
And something like this to implement it. 
`
const testMarketCondition = (name, markets, meta, testToRun) => {
  if (markets.includes(config.siteCode)) {
    test
        .meta(meta[0])
        (name, testToRun)
  } else {
    test.skip(name, testToRun)
  }
}
`
But doing it this way, I can only pass one test-meta. Which I would like to make it more flexible. 

Thanks!

**Comment by AlexSkorkin** [comment]
Would you please clarify what you mean by 'make it more flexible'? Why the current meta feature with multiple key=value parameters does not meet your requirements?

**Comment by adrian-inafuku-olx** [comment]
@AlexSkorkin in case I'd like to add more .meta in a TC. With the above approach, I know that I am receiving only 1 meta (Could be with multiple key=value). But as many people will be working on this same suite, I want to have the possibility of adding more .meta in the same TC. 
```
const testMarketCondition = (name, markets, meta, testToRun) => { if (markets.includes(config.siteCode)) { 
    test .meta(meta[0]) (name, testToRun) 
   // Here, I would like to add more ".meta" 
} else { test.skip(name, testToRun) } }
```
Not sure what the best approach could be since I cannot evaluate the "meta" to divide it into as many metas desired.

**Comment by AlexKamaev** [comment]
@adrian-inafuku-olx 
Thank you for your clarification. You cannot pass multiple meta objects to a test, and we do not have plans to implement this in the near future.

**Comment by benlind** [comment]
Wrapping my entire test in an if statement works for me:

```
if (!isSandbox) {
  test('test that does not run in sandboxes', async t => {
    // ...
  })
}
```

**Comment by AlexSkorkin** [comment]
@benlind, thank you for sharing your solution.

**Comment by karmajunkie** [comment]
What I'm looking for is a way to skip tests based on their metadata. I can *run* them based on a positive metadata match, but I can't exclude them. This is a feature of every other test framework I've ever used—is there not a way to do it currently in testcafe?

**Comment by miherlosev** [comment]
Hi @karmajunkie 

You can do it in the programming way using the [filter](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#filter) function :
```js
const createTestCafe = require('testcafe');
let testcafe         = null;

createTestCafe('localhost', 1337, 1338, void 0, true)
    .then(tc => {
        testcafe     = tc;
        const runner = testcafe.createRunner();

        return runner
            .src('test.js')
            .browsers('chrome')
            .filter((testName, fixtureName, fixturePath, testMeta, fixtureMeta) => {
                const excludeKeys     = ['key1', 'key2'];
                const testMetaKeys    = Object.keys(testMeta);
                const fixtureMetaKeys = Object.keys(fixtureMeta);

                const testMetaContainsExcludeKeys = testMetaKeys.some(item => excludeKeys.includes(item));
                const fixtureMetaContainsExcludeKeys = fixtureMetaKeys.some(item => excludeKeys.includes(item));

                return !testMetaContainsExcludeKeys && !fixtureMetaContainsExcludeKeys;

            })
            .run();
    })
    .then(failedCount => {
        console.log('Tests failed: ' + failedCount);
        testcafe.close();
    });

```

**Comment by track0x1** [comment]
Bumping this as it's quite a big deal for being able to test multiple viewports / devices.

**Comment by thelazurite** [comment]
Hey guys, I'd like to try and pick this one up. any pointers?

**Comment by miherlosev** [comment]
Hi @thelazurite

Thank you for your interest in TestCafe. Though this seems to be simple at first glance, it's a complex task that affects a lot of TestCafe subsystems. Before giving any instructions, we need to discuss it between team members. As soon we get any news, we will post them in this thread.

**Comment by rob4629** [comment]
> Wrapping my entire test in an if statement works for me:
> 
> ```
> if (!isSandbox) {
>   test('test that does not run in sandboxes', async t => {
>     // ...
>   })
> }
> ```

Looks like there's no way to do this at the `fixture` level:
```js
if (isAcceptedBrowser()) {
  fixture('Join Membership with Paypal, as Guest User')
    .page(baseUrl)
    .httpAuth(httpAuthCredentials);
} else {
  fixture.skip('Join Membership with Paypal, as Guest User')
};
```
Results in...
```sh
ERROR Cannot prepare tests due to an error.

Cannot implicitly resolve the test run in the context of which the test controller action should be executed. Use test function's 't' argument instead.
```

**Comment by miherlosev** [comment]
https://stackoverflow.com/questions/65312771/testcafe-unable-to-use-testcontroller-t-outside-of-test-run-e-g-as-a-conditi

**Comment by kPepis** [comment]
This worked for me:

```
let conditionToSkip;

const currentTest = test('test title', async t => {
  /** your actual test code */
}).before(async t => {
  /**
   * anything you need to do to assign a value to conditionToSkip,
   * in my case I check if a certain element is present
   */
})

if (conditionToSkip) {
  currentTest.skip;
}
```

**Comment by Mike-T-Mitchell** [comment]
+1

**Comment by qualityshepherd** [comment]
after spending a whole day trying and failing to implement a reasonable feature flag skip... I turn to my testcafe brethren for help. What would be lovely is something like this:

```
import { featureFlagXDisabled } from 'lib/featureFlags'

// skip on `true`?
fixture.skipIf(featureFlagXDisabled)...
```

Whatever way you wanna do this... but DO do this... pretty please... sugar... top or otherwise.

**Comment by benlind** [comment]
@qualityshepherd , it's inelegant, but would wrapping the entire fixture in an if statement work?

```
import { featureFlagXDisabled } from 'lib/featureFlags'

if (!featureFlagXDisabled) {
  fixture() ...
}
```

**Comment by qualityshepherd** [comment]
hilariously, wrapping the fixture in a test fails with `HEY... THERE'S NO FIXTURE OR TEST IN HERE`... so... nope.

**Comment by qualityshepherd** [comment]
FWIW, I'm having issues with doing things in the global test space and trying (in my case) to use promises to hit an endpoint to see if the flag is enabled. 

Sadly, this is now added to _an admittedly short list_ of reasons to NOT use Testcafe. This would of course include:
1. no `before All()` // this is the biggy
2. threading tests at the _test_ level (this is just dumb)
3. `this`

**Comment by rob4629** [comment]
> hilariously, wrapping the fixture in a test fails with `HEY... THERE'S NO FIXTURE OR TEST IN HERE`... so... nope.

Could you add an else clause with `.skip()`?
```js
import { featureFlagXDisabled } from 'lib/featureFlags'

if (!featureFlagXDisabled) {
  fixture() ...
} else {
  fixture.skip():
}
```

**Comment by qualityshepherd** [comment]
tried that too. Same issue... Testcafe doesn't see the fixture and errors out. I also tried things like:
```
const ifFixture = (featureFlagXDisabled) ? fixture.skip : fixture;

ifFixture`my fixture`...
```

the skip works this way but `fixture` does not. Errors that ifFixture is not a function. 🤔

**Comment by qualityshepherd** [comment]
Do note: enclosing `fixture` & `test` in an `if()` _used_ to work... not sure why it doesn't any more. Would love a workaround for that... which would likely solve _this_ :)

**Comment by miherlosev** [comment]
https://github.com/DevExpress/testcafe/issues/1626

> Do note: enclosing fixture & test in an if() used to work... not sure why it doesn't any more. Would love a workaround for that... which would likely solve this :)

@qualityshepherd 
Could you please share a complete example illustrating the described behavior?

**Comment by qualityshepherd** [comment]
The problem is when the conditional is `false`... but I would expect this to work 🤔 

```
import { Selector as $ } from 'testcafe'

const featureDisabled = false;

if(featureDisabled) {
  fixture`test`
    .beforeEach(async t => {
      await t.navigateTo('https://google.com')
    })

  test('should work but does not', async t => {
    await t.expect($('[name="q"]').visible).ok()
  })
// and even...
} else {
  fixture.skip`test`
}
```

![image](https://user-images.githubusercontent.com/3298906/135621059-ecb2ac20-7418-4e12-9739-bd0ebdc827d1.png)

**Comment by qualityshepherd** [comment]
Also... just to illustrate my _actual_ problem... THIS works:

```
import { Selector as $ } from 'testcafe'

const featureDisabled = true
const ifFixture = (featureDisabled === true) ? fixture.skip : fixture

ifFixture`test`
  .beforeEach(async t => {
    await t.navigateTo('https://google.com')
  })

test('should work but does not', async t => {
  await t.expect($('[name="q"]').visible).ok()
})
```

BUT... not if your conditional returns a promise... which is of course correct... but this is my problem as I need to hit an endpoint to see if my featureFlag is disabled. 

```
import { Selector as $ } from 'testcafe'

const featureDisabled = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve(false);
  }, 300);
})
const ifFixture = (featureDisabled === true) ? fixture.skip : fixture

ifFixture`test`
  .beforeEach(async t => {
    await t.navigateTo('https://google.com')
  })

test('should work but does not', async t => {
  await t.expect($('[name="q"]').visible).ok()
})
```

I know... I'M NEEDY 😄

**Comment by miherlosev** [comment]
TestCafe requires that the test file contains the `fixture` and `test` statements on the parsing state. If you postpone parsing declarations in any way

```js
if(featureDisabled) {
fixture\\`test\\`;
}
```

then TestCafe will mark such files as invalid and report the `Source files do not contain valid 'fixture' or 'test' declarations` error.


> BUT... not if your conditional returns a promise... which is of course correct... but this is my problem as I need to hit an endpoint to see if my featureFlag is disabled.

Calculate this condition before test execution and pass the value to fixtures using the environment variable.

**Comment by qualityshepherd** [comment]
I've tried env vars too... which requires waiting for a promise; which then fails in the test because it's not been resolved yet. 

I don't know of a way for Testcafe to trigger setting the env var BEFORE all tests... is there such a hook? And not the `fixture.before` as then we're already doing the thing I want to skip :)

**Comment by helen-dikareva** [comment]
We have added global hooks that should be executed before and after the TestCafe test run in TestCafe of v1.19.0. You can use these hooks to set environment variables.
See more in [Docs](https://testcafe.io/documentation/403435/guides/intermediate-guides/hooks#hooks-before-and-after-test-runs).

**Comment by miherlosev** [comment]
[https://github.com/DevExpress/testcafe/issues/1626](https://github.com/DevExpress/testcafe/issues/1626)

Hi folks,

We have implemented a few features ([t.browserInfo](https://github.com/DevExpress/testcafe/issues/481), [global hooks](https://testcafe.io/documentation/403435/guides/intermediate-guides/hooks#hooks-before-and-after-test-runs), [meta](https://testcafe.io/documentation/403436/guides/intermediate-guides/metadata-and-filtering) and etc.) that cover all described use cases. Are there real use cases that cannot be reached with the current feature set?

**Comment by AlexKamaev** [comment]
@codambro

It looks like your usage scenario differs from the issue described in the initial post. In the initial post, the `skip` method should get the `testController` object. However, in your case, it should be enough to use the described mechanisms, such as `filter`, `meta`, etc. Thus, you can use the workaround from the following comment to implement your usage scenario:
[https://github.com/DevExpress/testcafe/issues/1626#issuecomment-417424558](https://github.com/DevExpress/testcafe/issues/1626#issuecomment-417424558)

Moreover, TestCafe has the [t.report](https://testcafe.io/documentation/404350/reference/test-api/testcontroller/report) method, which allows you to pass custom data to the reporter. So you can combine `t.report` with conditional return and handle this situation in a custom reporter.

At present, we do not see the necessity to leave this issue open. Please describe the usage scenario that cannot be implemented with the existing TestCafe methods.

**Comment by 1rbis** [comment]
Can you tell me how I can skip the test based on their conditions in the test itself? This is necessary because some tests are working on the result of past tests. Failure of one test leads to cascading failure of several tests after it.
