### ISSUE TITLE
refresh browser

### ISSUE THREAD

**Issue by ganlanyuan** [DevExpress/testcafe#1627]
### Are you requesting a feature or reporting a bug?
Question.

After a few of clicks, I want to refresh the browser to clear everything. 
So that I can start a new test.
How can I refresh the browser?
Thanks

**Comment by AlexanderMoskovkin** [comment]
Hi,

Would you please clarify what exactly would you like to refresh?
If for example just some filled field you can use the [navigateTo](https://devexpress.github.io/testcafe/documentation/test-api/actions/navigate.html) action.
If cookies, LocalStorage - you can use [Anonymous Role](https://devexpress.github.io/testcafe/documentation/test-api/authentication/user-roles.html#anonymous-role).

And why don't use two separate tests?

**Comment by ganlanyuan** [comment]
Thanks @AlexanderMoskovkin , "nagigateTo" is what I wanted.

I'm actually testing several slideshows in one page.  
After clicking the prev/next buttons, the slideshow changed its position. So I want to refresh the browser to move it back to the original position.

BTW, can I run parallel tests against each slideshow?

**Comment by AlexanderMoskovkin** [comment]
> I run parallel tests against each slideshow?

Do you mean run in several browsers in parallel? Yes you can.

**Comment by ganlanyuan** [comment]
How could I achieve that?
I run `npm script` as below:
```javascript
"test": "npm run firefox && npm run chrome && npm run safari && npm run opera && npm run ie",
"firefox": "..."
```
But seems it runs the tests one by one.

Is it possible to run each fixture in parallel?
```
fixture `test A`
fixture `test B`
fixture `test C`
```

**Comment by AlexanderMoskovkin** [comment]
To run tests in several browsers in parallel you can use the following command: `testcafe chrome,firefox,safari,opera,ie test.js`.


BTW Also we plan to add the `concurrency` option soon. Here is a details: https://github.com/DevExpress/testcafe/blob/master/docs/articles/documentation/using-testcafe/common-concepts/concurrent-test-execution.md#concurrent-test-execution

Note that this option is not available in the current version but will be included in the next major release

**Comment by ganlanyuan** [comment]
That's a great feature!
Thanks a lot!
