### ISSUE TITLE
Legacy browser support

### ISSUE THREAD

**Issue by ganlanyuan** [DevExpress/testcafe#1628]
### Are you requesting a feature or reporting a bug?
Feature.

The [doc](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browser-support.html#officially-supported-browsers) says

> TestCafe supports the latest version of each browser unless specified explicitly.

1. Could you specify which version of each browser are supported?
2. Do you have any plan to add supports for legacy browsers in the future? 

If only the latest ones are supported, `Testcafe` seems not very useful because most of the projects are supposed to test on legacy browsers, not latest browsers.

Thanks

**Comment by VasilyStrelyaev** [comment]
Hi @ganlanyuan ,
This docs says about officially supported browsers, i.e. those against which we test TestCafe. In fact, TestCafe works in many legacy browsers. This depends on whether a particular browser supports basic HTML5 features.
We haven't investigated in what particular versions of legacy browsers TestCafe works.

**Comment by ganlanyuan** [comment]
Thanks @VasilyStrelyaev  for your explanation.
> This depends on whether a particular browser supports basic HTML5 features.

May I know which features `Testcafe` requires right now?

**Comment by VasilyStrelyaev** [comment]
@ganlanyuan, we don't have a complete list of features TestCafe requires. To compose such a list, we would have to examine the entire TestCafe code in detail.

However, I can give you certain general considerations,

The oldest browser we **officially** support is IE9. so you can expect other legacy browsers released in the same period to work with TestCafe.

Another point is that we usually avoid using new browser features in TestCafe. We use only features that became a de facto standard in most browsers.

BTW, are you interested in particular versions of legacy browsers? If you give us specific versions, we could test TestCafe in those browsers for you.

**Comment by ganlanyuan** [comment]
Thank you so much!
I would like to know about the supports of the following browsers:
Firefox 8+ 
Chrome 15+
Safari 4+ 
Opera 11.5+
IE 8+

**Comment by VasilyStrelyaev** [comment]
It will take some time, please bear with us.

**Comment by ganlanyuan** [comment]
Sure, take your time

**Comment by VasilyStrelyaev** [comment]
I've carried out a couple of experiments on SauceLabs and that's what I found out.

* Firefox: currently supported **35+**
* Chrome: currently supported **38+**
* Safari: the oldest version available on SauceLabs is **6** and TestCafe supports it.
* Opera: I was unable to run tests in it for some reason
* IE: currently supported **9+**

Note that the situation can change at any moment.

**Comment by ganlanyuan** [comment]
Thanks @VasilyStrelyaev for the information!
Have a blessed weekend!
