### ISSUE TITLE
APIv2 discussion

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#163]
This is a general place for the APIv2 discussion. I'll move proposals from wiki to here. Any suggestions/ideas/proposals are welcome.
\cc @DevExpress/testcafe

**Comment by inikulin** [comment]
# Assertion system

## Use only async assertions
To increase stability I suggest to get rid of sync assertions. With new powerfull assertion system
where will be no need for them. We will continiously execute assertion condition until it will not be met
or timeout will not happen (3sec by default). This is the only possible consensus beetween stability
and speed. E.g.:

```js
test `Button color changes`
    .save('color', () => document.querySelect('#btn').style.color)
    .click('#change-color')

    .expect.element('#btn').style('color').not.eql.saved('color');
```

You can use custom timeout by using `.within()`

```js
test `Button color changes`
    .save('color', () => document.querySelect('#btn').style.color)
    .click('#change-color')
    
    .within(3000).ms
    .expect.element('#btn').style('color').not.eql.saved('color');
```

Or if you want assertion to run once and immediately use `now`

```js
test `Button color changes`
    .save('color', () => document.querySelect('#btn').style.color)
    .click('#change-color')

    .now.expect.element('#btn').style('color').not.eql.saved('color');
```
## Actual argument
- `expect(func)` - no plain values, only funcs, since everything is async and should be calculated
- `expect.stored(name)` - stored value
- `expect.element(selector)` - element
- `expect.element(selector).attribute(name)` - element attribute
- `expect.element(selector).width` - element offset width
- `expect.element(selector).height` - element offset height
- `expect.element(selector).count` - number of elements matching the selector
- `expect.element(selector).style(styleProp)` - element computed style properties

## Assertions
### Common
- `.eql(value), .eql(func), .eql.stored(), .eql.element(selector), ...` - deep equality
- `.to.be.true` - boolean true equality
- `.to.be.false` - boolean false equality
- `.to.be.null` - null equality
- `.to.be.undefined` - undefined equality
- `.to.be.NaN` - NaN equality
- `.to.be.ok` - non-null, non-undefined, non-false
- `.to.be.empty` - empty array, object without fields, empty strings, elements without content
- `.more.than(value), .more.than(func), .more.than.stored(value)` - more than comparison
- `.less.than(value), .less.than(func), .less.than.stored(value)` - less than comparison
- `.contain(value), .contain(func), .contain.stored(value), .contain.element(selector), ...` - string contain substring, array contain value, object contain key, element contain text, element contain element

### String-only
- `.match(regexp)` - string matches regular expression

### Element-only
- `.visible` - visibility check
- `.exists` - element present in DOM

### Negation

- `.not.[assertion]` - negotiate assertion

## Timing prefixes

- `within(ms).ms.expect, within(ms).expect` - test assertion within given time range
- `now.expect` - test assertion once and immediately, sync assertion alternative

**Comment by inikulin** [comment]
# Fixture before/after/beforeEach/afterEach

E.g.:
```js
import deleteAllPosts from './mixins';

fixture `example.org forum functionality`
.beforeEach
   .go('http://example.org')
.after
   .do(deleteAllPosts);
```

**Comment by inikulin** [comment]
# Roles

Use roles to observe results or perform actions from different user perspectives. Also, it's a solution for
the forms authentication problem. Role initialization will be executed once per task on first demand and can be shared among tests and fixtures. Technically role saves created cookies and storages state. When we switch role in tests and if it's not initialized yet then initializations steps run and we return back to the page on which we stopped execution. If it's already initialized then page will be just reloaded with the new credentials.

*helpers.js*
```js
import testcafe from 'testcafe';

export var registeredUser = testcafe.role()
    .go('http://example.org')
    .type('#login', 'TonyStark')
    .type('#password', 'swordFish');
    .click('#login');
                   
export var anonymous = testcafe.role();
```

*test.js*
```js
import { registeredUser, anonymous } from '../helpers';

fixture `example.org tests`;

test `Anonymous users can see newly created comments`
    .as(registeredUser)
    .go('http://example.org')
    .type('#comment', 'Hey ya!')
    .click('#submit')
    .as(anonymous)
    .expect.element('#comment-area').contain('Hey ya!');
```

**Comment by inikulin** [comment]
# Waits
Autowaits are enabled by default.

*Disable all:*
```js
.autowait(false)
```

*Enable all*:
```js
.autowait(true)
```

*Optional*:
```js
.autowait({ xhr: true, pageLoad: false, timers: true })
```

*Forced (fails test if not occure), default timeout 3sec:*
```js
.waitPageLoad(timeout)
.waitXhr(timeout)
```

**Comment by kirovboris** [comment]
# Conditional statements

I suggest to use next syntax:

```javascript
.if(() => { return isBtnVisible(); 	})
	.click('#button')
	
	.if(() => { return isFormOpened('testForm'); })
		.click('#submit')
	.endif
	
.elif(() => { return getCheckboxes().length === 1; })
	.click('input[type="checkbox"]')
	
.else
	.click('#close-btn')
	
.endif;	
```

```if(func)```, ```elif(func)``` parameter is function, which will used as condition of statement.

**Comment by churkin** [comment]
Looks harmoniously

**Comment by churkin** [comment]
How are we going to report about forgotten endif?

**Comment by inikulin** [comment]
@churkin Should we?

**Comment by churkin** [comment]
@inikulin  I think this is a potential error when the number of `if` does not match the number of `endif`

**Comment by inikulin** [comment]
Well, we can raise error then.

**Comment by churkin** [comment]
Oh, we have to build a virtual logical tree and catch structure errors. Also with loops, if we will implement them.

**Comment by inikulin** [comment]
@churkin we will need virtual control flow tree anyway

**Comment by churkin** [comment]
@inikulin I was hoping we greatly simplify the analysis of the test code structure with the new API.

**Comment by inikulin** [comment]
Tree will be built in runtime via API calls, syntax analysis will not be involved

**Comment by VasilyStrelyaev** [comment]
Let's try to make assertions grammatically consistent.

If we stick to the *expect smth to* phrase, we would have to add a lot of wording:

`.to.eql(value), .to.eql(func), .to.eql.stored(), .to.eql.element(selector), ... `- deep equality
`.to.be.true` - boolean true equality
`.to.be.false` - boolean false equality
`.to.be.null` - null equality
`.to.be.undefined` - undefined equality
`.to.be.NaN` - NaN equality
`.to.be.ok` - non-null, non-undefined, non-false
`.to.be.empty` - empty array, object without fields, empty strings
`.to.be.more.than(value), .to.be.more.than(func), .to.be.more.than.stored(value)` - more than comparison
`.to.be.less.than(value), .to.be.less.than(func), .to.be.less.than.stored(value)` - less than comparison
`.to.contain(value), .to.contain(func), .to.contain.stored(value), .to.contain.element(selector), ... `- string contain substring, array contain value, object contain key, element contain text, element contain element

`.to.match(regexp)` - string matches regular expression

`.to.be.visible` - visibility check
`.to.exist` - element present in DOM
`.to.haveClass(className)` - element has one or more classname
`.to.be.disabled` - element is disabled
`.to.be.readonly` - input is readonly
`.to.be.checked` - checkbox is checked

My suggestion is to use the phrase *expect [that] smth*

`.eqls(value), .eqls(func), .eqls.stored(), .eqls.element(selector), ... `- deep equality
`.is.true` - boolean true equality
`.is.false` - boolean false equality
`.is.null` - null equality
`.is.undefined` - undefined equality
`.is.NaN` - NaN equality
`.is.ok` - non-null, non-undefined, non-false
`.is.empty` - empty array, object without fields, empty strings
`.is.more.than(value), .is.more.than(func), .is.more.than.stored(value)` - more than comparison
`.is.less.than(value), .is.less.than(func), .is.less.than.stored(value)` - less than comparison
`.contains(value), .contains(func), .contains.stored(value), .contains.element(selector), ... `- string contain substring, array contain value, object contain key, element contain text, element contain element

`.matches(regexp)` - string matches regular expression

`.is.visible` - visibility check
`.exists` - element present in DOM
`.hasClass(className)` - element has one or more classname
`.is.disabled` - element is disabled
`.is.readonly` - input is readonly
`.is.checked` - checkbox is checked

**Comment by AlexanderMoskovkin** [comment]
# New APIv2.1

## Fixture defenition
```js
fixture `My fixture`;
```

or

```js
fixture('My fixture');
```

## Test, actions and assertions
```js
test('My test', async t => {
    await t
        .click('#myelem')
        .expect.element('#myelem').visible;
});
```
## Hybrid functions
```js
var getElementById = Hbrd(id => documen.querySelector('#' + id));

var elem = await getElementById('myid'); // -> returns ElementDescriptor (props from recorder)
                                                                 // Can return any serializable value as well

// Can be passed to action (in that case evaluated in one round trip to client):
await t.click(getElementById('myid'))

// Or you can pass ElementDescriptor 
await t.click(elem);
```

## Roles
```js
var registeredUser = Role(async t => {
    // initialization steps
});

// Usage
test('roleTest', async t => {
   await t.as(registeredUser);
});
```

**Comment by inikulin** [comment]
I think we should restrict usage of the global `test`, `fixture`, `beforeEach`, etc. only to the test file and don't inject them to the globals on the project level, So, any module that will be require by test file will not be able to declare tests. Meanwhile, things like `Hybrid` and `Role` can be declared and used anywhere, but on the other hand they don't represent the minimal test harness. So, user will need to require them:
```js
import { Hybrid, Role } from 'testcafe';
```

Let me know what do you think \cc @DevExpress/testcafe

**Comment by AlexanderMoskovkin** [comment]
I like this way

**Comment by miherlosev** [comment]
1)I prefer the following variant:
```javascript
fixture `My fixture;`
```
2)If Hybrid function executing on client maybe we will name it as `Client` of `ClientCode`.
3)Frame switching is good. 
I think we should rename `switchToMain` -> `switchToTop` and add `switchToParent`.
(simular as `window.top` and `window.parent`)
4)Script injection.
I think that name is not clear.
I should be `injectClientScript`, `injectClientScriptForFrames`, `injectClientScriptForPages`.
The main goal - describe where we will inject script.
5)I think that Hybrid is a very usable feature. 
Therefore it should be avalible without additional import directive.

**Comment by inikulin** [comment]
@miherlosev 

> 1)I prefer the following variant:

Both will be available

> 3)Frame switching is good. 
I think we should rename switchToMain -> switchToTop and add switchToParent.
(simular as window.top and window.parent)

`top frame` may have different meaning depending in which frame you are currently. Meanwhile. we have only one `main` frame

> 4)Script injection.
I think that name is not clear.
I should be injectClientScript, injectClientScriptForFrames, injectClientScriptForPages.

Too long, however, I'm not quite happy with the original naming either

> 5)I think that Hybrid is a very usable feature. 
Therefore it should be avalible without additional import directive.

This will require globals pollution even in test dependencies. It's not good at all. Moreover, we will introduce conceptual inconsistency in test declaration interface and this utility API.

**Comment by AlexanderMoskovkin** [comment]
We need to add native dialogs handling api (`alert`, `confirm`, `prompt`, `beforeUnload`). Will it be look like an action?

```js
await t.click(el1)
    .handleAlert()    // or .waitForAlert
    .click(el2)
```

**Comment by inikulin** [comment]
@AlexanderMoskovkin sure. But I'd prefer to not use predictive model like we had before:
```js
await t
    .click(el) // <-- cause alert
    .handleAlertDialog();
```

**Comment by AlexanderMoskovkin** [comment]
Yeah, i mean the same

**Comment by inikulin** [comment]
Guys, just found fundamental issue with our current concept of Hybrid functions.

**The problem:**
Currenlty we just declare Hybrid functions somewhere and execute them without passing them any test run context. So we don't know in which Hammerhead session given Hybrid function should be executed. It became even worse if we think about calling Hybrid function from fixture dependency.

**The solutions:**
In general it's just the same solution with different control directions.

1. Hybrid function call should always accept TestApiHost as the first argument:
```js
import { Hybrid } from 'testcafe';

var getElementById = Hybrid(id => document.querySelector('#' + id));

test('Yo', async t => {
    var btn = await getElementById(t, 'myId');
});
```
*Pros:* we have explicit way of hybrid function declaration, so there is no room for confusion.
*Cons:* calling convention is a little bit confusing, it's not as elegant as we hoped.
2. Hybrid wrapper will be built-in into the TestApiHost:
```js
var getElementById = id => document.querySelector('#' + id);

test('Yo', async t => {
    var btn = await t.hybridCall(getElementById , 'myId');
});
```
*Pros:* calling convention looks a little bit cleaner, but still it's not quite elegant.
*Cons:*  it's hard to distinguish hybrid function declaration.

Please, let me know what do you think and if you have better ideas. \cc @DevExpress/testcafe

**Comment by churkin** [comment]
I vote for the first variant

**Comment by AlexanderMoskovkin** [comment]
I suppose it's critical to distinguish hybrid and common function declarations, so I choose the first.

**Comment by inikulin** [comment]
I vote for first as well, since it's also looks better in the action calls:
```js
await t.click(getElementById(t, 'myId'))
```

vs

```js
await t.click(t.hybrid(getElementById)('myId'))
```

However, it's still sucks =(( I was hoping we could create something better

**Comment by inikulin** [comment]
Well, actually there is a "black magic" way to keep old syntax, without passing `t` explicitly. We can wrap testrun-fn with the function with special name that will contain test run ID. When in Hybrid fn we can traverse up callstack using v8 StackTrace API to determine the test run. 
*What's cool about it*: we can keep the old syntax. 
*What's not cool*: 
- it's may be fragile, 
- we will need to introduce a global pool of test-runs as well, so Hybrid function will be able to peek appropriate test-run,
- behavior of the Hybrid function which was called out of the test run context is undetermined (we can just throw, actually).

**Comment by miherlosev** [comment]
I prefer the second variant:
```javascript
var getElementById = id => document.querySelector('#' + id);

test('Yo', async t => {
    var btn = await t.hybridCall(getElementById , 'myId');
});
```
Because for this variant we directly declare that we call hibrid function in the specified test context.
Also it is simular to http://api.qunitjs.com/QUnit.test.

I think for actions we need to create build-in selector instructions:
```javascript
await t.click(t.findById('myId'))
await t.click(t.findByContainClass('myClass'))
await t.click(t.findByContainText('myText'))
etc.
```

**Comment by churkin** [comment]
I am categorically against mixing hybrid and common functions

**Comment by churkin** [comment]
The hybrid function is not very obvious concept for a beginner, do not complicate the interface even more

**Comment by kirovboris** [comment]
I like the first variant too, but i think 'hybrid function'  is still a complicated conception for novice. The term  'hybrid' doesn't associate with the call function on the client side.

**Comment by VasilyStrelyaev** [comment]
So, which is the final variant?

**Comment by inikulin** [comment]
@VasilyStrelyaev initial, without any context. But it's still doubtable and require further research

**Comment by VasilyStrelyaev** [comment]
> Actual argument
> expect.stored(name) - stored value

We have the capability to pass a stored value as the *expected* argument, which does make sense.
But does it make sense to use a stored value as the *actual* argument?

**Comment by inikulin** [comment]
@VasilyStrelyaev we don't have stored values in the APIv2. You can just use plain vars now

**Comment by VasilyStrelyaev** [comment]
Where can I see an updated version of APIv2?

**Comment by inikulin** [comment]
# New API (25/2/2016)

## Fixture defenition
```js
fixture `My fixture`;
```

or

```js
fixture('My fixture');
```

## Test, actions and assertions
```js
test('My test', async t => {
    await t
        .click('#myelem')
        .expect.element('#myelem').visible;
});
```
## Hybrid functions
```js
var getElementById = Hybrid(id => document.querySelector('#' + id));

var elem = await getElementById('myid'); // -> returns ElementDescriptor (props from recorder)
                                                                 // Can return any serializable value as well

// Can be passed to action (in that case evaluated in one round trip to client):
await t.click(getElementById('myid'))

// Or you can pass ElementDescriptor 
await t.click(elem);
```

## Roles
```js
var registeredUser = Role(async t => {
    // initialization steps
});

// Usage
test('roleTest', async t => {
   await t.as(registeredUser);
});
```

## Frame switching
```js
await t
         .switchTo('#frame')
          ...
         .switchToMain();
```

## Script injection
```js
// Inject on all pages (and frames)
t.alwaysInject(() => {
   // code
});

t.alwaysInject('filename,js');

// Inject ones
t.inject(...);
```

## Assertions
All assertions are **async** and chainable:
```js
await t
    .expect.element('div').text.contains('Yo!')
    .expect.element('span').not.visible;
```

### L-value
`expect(value)` - value,
`expect(hybridFunction)` - hybrid function return value,
`expect.element(selector)` - element,
`expect.element(selector).text` - element text
`expect.element(selector).attr` - element attr

### R-value
`.eql(value),  .eql.element(selector). ... `- deep equality
`.contains(value)`- string contain substring, array contain value, object contain key, element contain text, element contain element
`.matches(regexp)` - string matches regular expression

`.is.true` - boolean true equality
`.is.false` - boolean false equality
`.is.null` - null equality
`.is.undefined` - undefined equality
`.is.NaN` - NaN equality
`.is.ok` - non-null, non-undefined, non-false
`.is.empty` - empty array, object without fields, empty strings

#### Element-only:
`.visible` - visibility check
`.exists` - element present in DOM
`.hasClass(className)` - element has one or more classname
`.disabled` - element is disabled
`.readonly` - input is readonly
`.checked` - checkbox is checked

#### Negation
`.not` + R-value
`.is.not`  for R-values that starts with `.is`

**Comment by VasilyStrelyaev** [comment]
Cool!
Notice no `beforeEach`, `afterEach`, `page`... No waits or autowaits...
Actions won't change from what I gather...

**Comment by inikulin** [comment]
- Added `page`, but semantics has changed.
 - `beforeEach`, `afterEach` - not sure if we'll be able to finish them for the first version.
 - waits and autowaits - are in discussion and not sure if we'll be able to finish them as well. For now it will work as it worked before (autowaits always enabled).
 - Actions won't change in general, but they now accept regular functions, Hybrid functions, element descriptors return by Hybrid functions and strings now as a selector. No arrays, no jquery objects

**Comment by VasilyStrelyaev** [comment]
> .eql(value), .eql.element(selector). ...- deep equality

does "deep equality" relate to both value and element?

**Comment by inikulin** [comment]
@VasilyStrelyaev elements are equal if they are the same element.

**Comment by VasilyStrelyaev** [comment]
no `expect(hybridFunc)` so far?

**Comment by inikulin** [comment]
`expect(val)` works with raw values. So it will examine hybrid functions as plain JS object. To convert hybrid function in the selector you will need to pass it to `expect.element()`

**Comment by VasilyStrelyaev** [comment]
Seems that `t.alwaysInject` is more like `t.injectEverywhere`, isn't it?

**Comment by inikulin** [comment]
@VasilyStrelyaev this one is still debatable. I'm starting to think that we should use this syntax instead:

```js
fixture `Fixture`
    .useClientHelper('dx', '../dx.js'); // Will be built using browserify

test('Some test')
   .useClientHelper('$', '../vendor/jquery.js')
   .body(async t => {
       // Helpers are visible via provided alias in the scope of Hybrid function.
       var gridElem = Hybrid(() => dx.getGrid())();
     
       t.click(() => $('.btn'));
   });
```
\cc @DevExpress/testcafe 
What do you guys think?

**Comment by kirovboris** [comment]
I like this way. Also I think an alias should be the second argument, because it isn't always required.

**Comment by inikulin** [comment]
@kirovboris how you will access helper without alias?

**Comment by kirovboris** [comment]
E.g. if i want to prepare loaded site in a certain way - set start sizes or change css or someone else.

**Comment by kirovboris** [comment]
Anyway these preparing can be completed with beforeEach methods later.

**Comment by VasilyStrelyaev** [comment]
> test('Some test').body(

Oh, changes arrive so fast... :(

> useClientHelper

makes sense to me

**Comment by VasilyStrelyaev** [comment]
> t.click(() => $('.btn'));

So, you can pass a hybrid function as a selector, or you can pass a regular function that will be wrapped to become hybrid, right?

**Comment by VasilyStrelyaev** [comment]
> test('Some test').body(

And, BTW, is introduction of `body()` connected with `useClientHelper` or is it a separate topic?

**Comment by inikulin** [comment]
@VasilyStrelyaev it's separate thing. We will need to introduce test-local chains for setups/teardowns, skip functionality, etc. E.g.:
```js
test `Some test`
   .before(t => ...)
   .after(t => ...)
   .skip(browser => browser.ie)
   .body(t => {
      ...
    });
```

**Comment by VasilyStrelyaev** [comment]
So, the main purpose of them is to override fixture-level setups and teardowns?
Which can be achieved by using a flag to skip the latter. However, this way we'll have local setup/teardown logic mixed with test code, which you think is not ok?

**Comment by VasilyStrelyaev** [comment]
What about https://github.com/DevExpress/testcafe/issues/163#issuecomment-199717730

**Comment by inikulin** [comment]
@VasilyStrelyaev 
> Which can be achieved by using a flag to skip the latter. 

Nope. Test may require additional logic. And it's used for `skip` and `useClientHelper` as well. And possibly many other things in the future.

**Comment by inikulin** [comment]
> So, you can pass a hybrid function as a selector, or you can pass a regular function that will be wrapped to become hybrid, right?

Yes. I'm still not sure if it's quite clear, BTW. You can pass:
- string selector
- hybrid function call result
- hybrid function (auto-invoke)
- regular function (auto-transform to hybrid and auto-invoke)

**Comment by VasilyStrelyaev** [comment]
One more thing.
I'm not sure if my js skills allow me to say it properly, so I'll use an example.
It's about closures in hybrid functions

I suspect that
```js
test `Some test`
    .body( t => {
        var id = 'myId';
        var hf = Hybrid(() => document.querySelector(id));
        await t.click(hf);
    });
```
won't work, while
```js
'@test'['myTest'] = {
    var id = 'myId';
    act.click(() => document.querySelector(id));
}
```
used to?

**Comment by inikulin** [comment]
@VasilyStrelyaev Yap. You need to introduce arg:
```js
test('Some test', async t => {
    var hf = Hybrid(id => document.querySelector(id));

    await t.click(hf('myId'));
});
```

**Comment by VasilyStrelyaev** [comment]
Okay.
Now...
Do we expect users to study DOM element descriptors returned by hybrid functions, or just use them as tokens to pass to actions/assertions?

**Comment by inikulin** [comment]
@VasilyStrelyaev More likely we will allow them to study descriptors. We need to discuss descriptor content first.

**Comment by VasilyStrelyaev** [comment]
We are really waiting for the final API design to be posted here.

**Comment by VasilyStrelyaev** [comment]
It may have sounded harsh, but API is the main thing still to be documented.

**Comment by inikulin** [comment]
Okey dokey =)

**Comment by helen-dikareva** [comment]
What should be `wait` and `waitForElement` parameters?
Should `waitForElement(selector, [timeout])` has `timeout` as required parameter or not?

**Comment by inikulin** [comment]
`waitForElement` has default timeout that is equal to the one that specified via `elementAvailabilityTimeout`, it also has optional `elementAvailabilityTimeout` second argument, which will override global option

**Comment by helen-dikareva** [comment]
And what about `wait` command? We still need predicate for it?

**Comment by inikulin** [comment]
No, `wait` will just wait for the specified amount of time. We need to introduce `waitForCondition` action for the predicate I guess.

**Comment by helen-dikareva** [comment]
Where predicate will be evaluated: on server or on client?

**Comment by inikulin** [comment]
On client of course. But `waitForCondition` has some caveats: it should be executed correctly if it's interrupted by page load. We will need to implement similar machinery for Hybrids and it will require some significant amount of work to be done. So I suggest to postpone `waitForCondition` implementation for now.

**Comment by helen-dikareva** [comment]
ok, thanks for your clarification

**Comment by inikulin** [comment]
Nothing to discuss left here. Any further API discussion should be continued in the appropriate issues.
