### ISSUE TITLE
change typescript version to exact or make it peerDependency

### ISSUE THREAD

**Issue by Hotell** [DevExpress/testcafe#1632]
### Are you requesting a feature or reporting a bug?
none of them, rather a build change

### What is the current behavior?
If I use TS version 2.2.2 for instance in my project, and install testcafe, which has `^` in typescript package version ( which will install latest version till 3 ), my whole build will start to break, because `testcafe's` TS dependency overrides my older version -> what does it mean?

node_modules/.bin/tsc -> will symlink to testcafe/node_modules/typescript,
so when I run `yarn tsc` during my build tsc version `2.4.2` will run ( which had breaking changes by means of stricter type checking ) and my build will not pass, which is very unfortunate

similar issue like
https://github.com/TypeStrong/typedoc/issues/556

### What is the expected behavior?
making typescript peerDependency or fixing version in dependencies to oldest possible.

### Specify your

* operating system: OSX/Win 10
* testcafe version:  0.16.2
* node.js version: 8.x

**Comment by inikulin** [comment]
Testcafe has `^2.2.2` version specified in package.json, which means it will install latest `2.x.x` and never any other major version. Also, package manager shouldn't override binary bindings in project root node_modules with transitive dependency version if their semver range doesn't overlap. So, it's either bug in yarn or something is wrong with your project configuration.

**Comment by Hotell** [comment]
> Testcafe has ^2.2.2 version specified in package.json, which means it will install latest 2.x.x and never any other major version. 

Don't you worry I know what `^` means :)

As I've said, using `^` versioning especially for typescript is very wrong as they are not following semver for breaking changes

> So, it's either bug in yarn or something is wrong with your project configuration.

yup you definitely right here, just tried id with npm 5.3 and it behaves as it should
