### ISSUE TITLE
Add `--page-load-timeout`

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#1645]
(follow up #1521)
TestCafe starts tests when the `DomContentLoaded` event is raised. `window.load` event is raised with some delay sometimes.
Some pages executes page preparation scripts on the `window.load` event so we should wait for it. But it's possible you wouldn't like to wait additional timeouts so we should provide an ability to set this timeout to `0`.

It'll be 5 seconds by default.

Also add a per-test option via `setPageLoadTimeout(<ms>)`

**Comment by inikulin** [comment]
Shouldn't it be a per-test API options as well?

**Comment by AlexanderMoskovkin** [comment]
do you mean like `setTestSpeed` ?

**Comment by inikulin** [comment]
Yes

**Comment by AlexanderMoskovkin** [comment]
I agree
