### ISSUE TITLE
Basic example fails with script errors

### ISSUE THREAD

**Issue by morsdyce** [DevExpress/testcafe#1649]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Example Basic tests failing

### What is the expected behavior?
Example Basic tests passing

### How would you reproduce the current behavior (if this is a bug)?
clone the basic example, follow instructions to run (npm install, npm test)

#### Provide the test code and the tested page URL (if applicable)
basic example in the examples folder

Tested page URL:
NA

Test code
NA

### Specify your
Tests in the examples are failing (both from the examples project and from basic setup from getting started guide).

All of them are attributed to "Script Error".

example output:

```
A set of examples that illustrate how to use TestCafe API
 ✖ Text typing basics

   1) Error on page "https://devexpress.github.io/testcafe/example/":

      Script error.

      Browser: Chrome 59.0.3071 / Mac OS X 10.11.3

          7 |const page = new Page();
          8 |
          9 |// Tests
         10 |test('Text typing basics', async t => {
         11 |    await t
       > 12 |        .typeText(page.nameInput, 'Peter')                      // Type name
         13 |        .typeText(page.nameInput, 'Paker', { replace: true })   // Replace with last
      name
         14 |        .typeText(page.nameInput, 'r', { caretPos: 2 })         // Correct last name
         15 |        .expect(page.nameInput.value).eql('Parker');            // Check result
         16 |});
         17 |

         at <anonymous> (/Users/maayan/projects/testcafe/examples/basic/test.js:12:10)
         at test (/Users/maayan/projects/testcafe/examples/basic/test.js:10:1)


   2) Error on page "https://devexpress.github.io/testcafe/example/":

      Script error.

      Browser: Chrome 59.0.3071 / Mac OS X 10.11.3

```

Note: I did change the npm test command to only run on chrome as I have firefox developer edition installed which caused the tests to hang and not provide any output.

* operating system: Mac OS X 10.11.3
* testcafe version: master branch
* node.js version: 8.2.1

**Comment by morsdyce** [comment]
I just found out from the release notes that you also support headless mode for chrome which does work, so I assume this is related to browser extensions.

Although not testcafe fault, this is very confusing for a first time user which will cause people to not use testcafe.

It is probably best to at least start chrome in incognito mode so browsers extensions aren't loaded by default.

**Comment by AlexanderMoskovkin** [comment]
Hi @morsdyce,

You are right, some extensions can break TestCafe behavior. We have an issue for it in our sub-module: https://github.com/DevExpress/testcafe-browser-tools/issues/106 so I close this as a duplicate.
Definitely we will think about it in near future.
