### ISSUE TITLE
Screenshots custom naming

### ISSUE THREAD

**Issue by adamorlowskipoland** [DevExpress/testcafe#1651]
### Are you requesting a feature or reporting a bug?
requesting a feature

### What is the current behavior?
Current default settings for saving a screenshot is:
{currentDate}\test-{testIndex}{userAgent}{screenshotIndex}.png; {currentDate}\test-{testIndex}\run-{quarantineAttempt}{userAgent}{screenshotIndex}.png if quarantine mode is enabled.

### What is the expected behavior?
Screenshot will be named:
'userAgent ' + 'screenshotIndex' + '.png'
V
{currentDate}\test-{testIndex}{userAgent}{userAgentscreenshotIndex}.png

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
Windows 10 Home
10.0.15063
* testcafe version:
    "testcafe": "^0.16.2",
* node.js version:
v6.10.3

**Comment by helen-dikareva** [comment]
So far, you can specify a custom path to save a screenshot to only when you take screenshots using the [`takeScreenshot`](https://devexpress.github.io/testcafe/documentation/test-api/actions/take-screenshot.html) action. Anyway, we like your idea to create a template for the screenshot path, we will think about a better way to implement it.

**Comment by thireven** [comment]
I wrote this helper function to manage how my screenshots are saved:

`function screenshotPath(t, ...args) {
  let filename = args.pop();
  const currentTest = t.testRun.test;
  const browser = t.testRun.browserConnection;

  const pathArray = [
    browser.browserInfo.userAgent.replace('/', '_'), // Browser and OS
    currentTest.fixture.name, // Fixture name
    currentTest.name, // Test name
    ...args
  ];

  const path = pathArray.join('/').replace(/\s/g, '-');
  
  if (screenshotMap[path] === undefined) {
    screenshotMap[path] = -1;
  }
  screenshotMap[path]++;

  const numberIndex = (`000${screenshotMap[path]}`).slice(-3);
  filename = `${numberIndex}.${filename}`;
  return `${path}/${filename}`;
}`

I'm also building an internal GUI for testcafe and would love to be able to apply screenshot path "filters" in the CLI. For instance, something like: `<path to screenshots>/%BROWSER%/%FIXTURE_NAME%/%TEST_NAME%/%NUMBERED%_%FILENAME%`

I don't suppose it's something that can feasibly be done in the CLI right now?

**Comment by helen-dikareva** [comment]
Hello @thireven 
This feature request is not included in our nearest sprints, but we are going to implement setting templates for screenshot paths. You can create your own TestCafe fork, PRs are always welcome.
And please vote for the features you like.

**Comment by AlexanderMoskovkin** [comment]
closed in favor of #2152
