### ISSUE TITLE
click handler not getting triggered

### ISSUE THREAD

**Issue by bhavinkamani** [DevExpress/testcafe#1655]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?
When I goto https://paytm.com and try to login 

I am receiving a failed test because, click handler is not getting triggered. When I trigger click through `document.querySelector("._3ac-")` on devTool console, it works fine and i see the modal dialog coming up.

### What is the expected behavior?

triggering click on `Log In/Sign Up` text should trigger

### How would you reproduce the current behavior (if this is a bug)?

Refer to the test code below

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: http://paytm.com

Test code

```js
import { Selector } from "testcafe";
fixture`Paytm Home Page`.page`http://paytm.com`;

test("My test", async t => {
  const login = Selector("._3ac-");
  await t.click(login).expect(Selector("input[name=username]").exists).ok();
});
```

### Specify your

* operating system: OSX 10.11
* testcafe version: 0.16.2
* node.js version: 8.1.4

**Comment by AlexanderMoskovkin** [comment]
Hi @bhavinkamani,

I'm able to reproduce the same on the original page without TestCafe. It seems that the `Log In/Sign Up` button became workable after some timeout after the page is fully loaded. 
Take a look at the screencast: I open the page and click several times on the `Log In` link but nothing happens. The modal dialog opens if I click on the link only *after* the `Offer` badge in the top of the page is appeared: https://www.screencast.com/t/g1bDBP9uKyA5

So, to make the test workable it necessary to handle it:
```js
import { Selector } from "testcafe";
fixture`Paytm Home Page`.page`http://paytm.com`;

test("My test", async t => {
  const login = Selector("._3ac-");
  const offerBadge = Selector('._2egn'); 

  await t.expect(offerBadge.visible).ok();
  await t.click(login).expect(Selector("input[name=username]").exists).ok();
});
```

**Comment by bhavinkamani** [comment]
Thank you so much. That must have been indeed tricky.
