### ISSUE TITLE
Reusing chrome instance

### ISSUE THREAD

**Issue by bhavinkamani** [DevExpress/testcafe#1656]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?

Every new test runs from command-line opens up a new chrome tab instance.

### What is the expected behavior?

Like Karma, is there a way to reuse the existing browser connection and reload the test sequence into the same browser instance. This is especially useful during development and may help in shaving off couple of startup seconds.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: 10.12.5
* testcafe version: 0.16.2
* node.js version: 8.1.4

**Comment by FabioAntunes** [comment]
dup https://github.com/DevExpress/testcafe/issues/1624

**Comment by AlexanderMoskovkin** [comment]
@FabioAntunes you are right, we have a similar proposal in the #1624.

@bhavinkamani You can use the `remote` alias to run tests in the same browser instance (see [Remote Browsers](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#remote-browsers)). But it's necessary to enter a provided url into browser's address bar before each run

**Comment by bhavinkamani** [comment]
Thanks @AlexanderMoskovkin. I tried that option. While it allows me to use the same browser tab. It still takes some time to reconnect and is cumbersome to copy n paste the url for every run. A file watcher that reloads the run on the connected instance would serve us great
