### ISSUE TITLE
Describe auto waiting mechanism for ClientFunctions

### ISSUE THREAD

**Issue by kirovboris** [DevExpress/testcafe#1660]
We discussed it in private and have decided to describe the auto-waiting mechanism for `ClientFunciton`. Also we should add an info about the type of return values in selector plugins. E.g. `.getReact` and `.getVue` are `ClientFunction`, but we didn't describe it. So, it confuses at during the trying to use `console.log` from the result of call
```js
const id = comp.getReact(({props}) => props.id);

console.log(id);
//> ClientFunctionResultPromise { _then: [], _fn: [Function], _taskPromise: null }
```
@VasilyStrelyaev @miherlosev

**Comment by VasilyStrelyaev** [comment]
Added info about the returned client function

https://github.com/DevExpress/testcafe-vue-selectors/pull/23
https://github.com/DevExpress/testcafe-react-selectors/pull/57

**Comment by VasilyStrelyaev** [comment]
What else should we do regarding this issue?

**Comment by kirovboris** [comment]
It's OK now. I suggested to add a separate section about the waiting `ClientFunction` and snapshot properties in the smart assertion topic, or highlight it somehow.
