### ISSUE TITLE
[Docs] Add information about browser extensions' influence on test running

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#1663]

**Comment by FabioAntunes** [comment]
This is definitely a must have, I spent a couple of hours trying to figure why my tests were failing, since the error message didn't had any info related to that. As newcomer it was a bit frustrating.

**Comment by AlexanderMoskovkin** [comment]
@FabioAntunes thanks for the feedback. I suppose we should try to disable browser extensions by default to prevent such troubles.

**Comment by AlexanderMoskovkin** [comment]
> I suppose we should try to disable browser extensions by default to prevent such troubles.

We've done this in context of the #1623 issue. It's already available in the `0.18.0-alpha1` version.
