### ISSUE TITLE
Debug buttons does not appear on the specific page

### ISSUE THREAD

**Issue by churkin** [DevExpress/testcafe#1665]
Test:
```javascript
fixture `Let\'s take a look at the new TestCafe`
    .page `https://www.starbucks.com/green-apron-delivery/`;
	
test(`Get a cup of coffee`, async t => {
	await t.debug();
});
```
Test pauses, but there are no 'resume' and 'step over' buttons.

**Comment by AlexanderMoskovkin** [comment]
The problem is not with the panel. TestCafe crashes there. If you remove the `debug` command you will see the same behavior. Issue for this is already created in `testcafe-hammerhead` https://github.com/DevExpress/testcafe-hammerhead/issues/1252
