### ISSUE TITLE
Role api is not working for Single Page Application using hash based navigation.

### ISSUE THREAD

**Issue by tuanquynet** [DevExpress/testcafe#1671]
### Are you requesting a feature or reporting a bug?
Yes. I am reporting a bug. useRole api is not working well.

### What is the current behavior?
I am developing SPA with react and hash based navigation with React-Router. I configured Role with url sign in url of "http://localhost:3030/index.html#sign-in". It navigate to index.html#sign-in for signing in and store successfully token into localStorage. In the test cases, I navigate to #dashboard. But there is no token in localStorage. It seem that localStorage is not restore if I don't navigate to other html page. If I create another page for signin such as signin.html. And in test case, I navigate to index.html#dashboard. Everything was working well.

### What is the expected behavior?
It should be able to use single page for sign in and other feature.

Tested page URL:

Test code

```js

```

### Specify your

* operating system: MacOS
* testcafe version: 0.17.0
* node.js version: 8.2.1

**Comment by AlexanderMoskovkin** [comment]
Hi @tuanquynet,

Have you tried to set the [preserveUrl](https://devexpress.github.io/testcafe/documentation/test-api/authentication/user-roles.html#optionspreserveurl) option to `true`? From your description it seems it should work.

**Comment by TatriX** [comment]
`preserveUrl` helped with my react app. Actually I think preserving urls should be a default behavior because it's not obvious why test redirects to a login page in scenario like this:
```
    await t
        .useRole(testUser)
        .expect(logout.exists).ok();

    const location = await t.eval(() => window.location); // redirect to the login page
    await t.expect(location.pathname).eql("/");
```

**Comment by AlexanderMoskovkin** [comment]
Hi @TatriX,

This default behavior allows to isolate the whole `login` logic (including the login page url) with Roles. You can set an actual tested page url as a [Start Webpage](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#specifying-the-start-webpage) of a fixture or test and a login page url as a Role initializing url, for exapmle:
```js
fixture `My fixture`
    .page `https://actual-page-to-be-tested`;

const user = Role('https://login-page', async t => {
    //...
});

test('My test', async t => {
    await t.useRole(user);
   // you are on the `action-page-to-be-tested` page here and you don't need to call `navigateTo()`
});
```

And the `preserveUrl` option covers other cases (like single page applications)

**Comment by TatriX** [comment]
I see, thanks.
