### ISSUE TITLE
Browsers not launching through Jenkins

### ISSUE THREAD

**Issue by 3562Nathan** [DevExpress/testcafe#1673]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

We are experiencing an issue when running Testcafe on the master build server via Jenkins, the browsers refuse to open up, however, when we run them manually per server then it works. Testcafe seems to only function with Edge successfully. Other browsers refuse to open(Firefox, IE and Chrome - Latest Versions). Please see Jenkins log below.

We've tried another test automation framework(Codecept using selenium) and it worked perfectly(All browsers were launched).

### What is the expected behavior?
If we kick off the Testcafe test runner via Jenkins and select all available operating systems(Windows 7, 8, 10) our tests should run and open across all major browsers(IE, Edge, Firefox and Chrome)

### How would you reproduce the current behavior (if this is a bug)?

Refer to our testing samples below using a basic Jenkins installation.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

http://www.google.com

Test code:

Runner that we are currently using:
```js
const createTestCafe    = require('testcafe');

createTestCafe('localhost', 1337, 1338)
	.then(tc => {
		testcafe     = tc;
		const runner = testcafe.createRunner();

		runner.src(['tests/googleSearch.js']);
		runner.browsers(['chrome']);
		runner.useProxy('10.100.1.2:8080');

		return runner.run({
			skipJsErrors: true,
			speed: 1
		});
	})
	.then(failedCount => {
		if (failedCount > 0) console.log('[FAILED] Total Tests Failed: ' + failedCount);
		else console.log("[SUCCESS] All Tests Passed");
		testcafe.close();
	})
	.catch(error => {
		console.log(error)
		testcafe.close();
	});
```

Test code that we are using:

```js
fixture `Google Test`
    .page `https://www.google.com`;

    test('Google Search', async t => {
        await t
	    .typeText('input[type="text"]', 'wikipedia')
            .pressKey('enter');
    });
```

Jenkins Log:

```
13:08:38 [Xcelerator] $ C:\nodejs\node.exe C:\Users\jenkins\AppData\Local\Temp\hudson8629938761236949315.js
13:10:41 { Error: Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
13:10:41     at BrowserSet._callee4$ (C:\Users\jenkins\node_modules\testcafe\lib\runner\browser-set.js:199:44)
13:10:41     at tryCatch (C:\Users\jenkins\node_modules\regenerator-runtime\runtime.js:65:40)
13:10:41     at Generator.invoke [as _invoke] (C:\Users\jenkins\node_modules\regenerator-runtime\runtime.js:303:22)
13:10:41     at Generator.prototype.(anonymous function) [as next] (C:\Users\jenkins\node_modules\regenerator-runtime\runtime.js:117:21)
13:10:41     at step (C:\Users\jenkins\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
13:10:41     at C:\Users\jenkins\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
13:10:41     at Promise (<anonymous>)
13:10:41     at F (C:\Users\jenkins\node_modules\core-js\library\modules\_export.js:35:28)
13:10:41     at BrowserSet.<anonymous> (C:\Users\jenkins\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12)
13:10:41     at BrowserSet._waitConnectionsOpened (C:\Users\jenkins\node_modules\testcafe\lib\runner\browser-set.js:217:26) constructor: [Function: GeneralError] }
```

### Specify your

* operating system: Tried Windows 7, 8 and 10.
* testcafe version: 0.17.0
* node.js version: 8.2.1
* jenkins version: 2.60.2

**Comment by AndreyBelym** [comment]
Hello @3562Nathan and @redfox256! Do you start Jenkins as a service? If so, you may need to set 'Allow service to interact with desktop' in the service properties: https://github.com/SeleniumHQ/selenium/issues/3349 and on Windows 10 you have to toggle the `NoInteractiveServices` [registry key](https://msdn.microsoft.com/ru-ru/library/windows/desktop/ms683502(v=vs.85).aspx), or try to start it as a regular Windows CLI process from the terminal or a batch file. 

If TeamCity is also running as a service on Windows, you can try to apply similar tweaks to its service too.

**Comment by redfox256** [comment]
Hi Andrey 

After making the changes on Windows 7 'Allow service to interest with desktop' started running the tests in chrome and firefox but still not in IE, left the same message as above.

And on Windows 10 changing NoInteractiveServices to zero and also ticking 'Allow service to interest with desktop' now runs fine in chrome but not in firefox and ie (even rebooted the system in hope it might work)

**Comment by AndreyBelym** [comment]
Can you please try so start Jenkins from the command line and check how browsers will start? 
`cd "C:\Program Files (x86)\Jenkins" && java -jar jenkins.war`

**Comment by redfox256** [comment]
Running from the command line works like a charm.
Started all the slaves up with the command below and browsers started opening running the tests.

java -jar slave.jar -jnlpUrl http://jenkins_url/slave-agent.jnlp -secret the_secret

Thanks for the help.

**Comment by 3562Nathan** [comment]
Thanks Andrey.

**Comment by arobertsf** [comment]
Indeed this works if I log in to the remote Windows slave and start the agent from the command line.  However we don't want to manage this startup manually ourselves, but run Jenkins from a Windows service, which works fine for Chrome and Firefox.  (We have made the registry and service changes to allow interactivity and rebooted, which allowed Firefox to run, but still not IE.)  Should I open a new issue for starting IE when the Jenkins agent runs as a service, or can we reopen this ticket?

**Comment by AndreyBelym** [comment]
@arobertsf, TestCafe can't handle this problem because it's fundamental OS-level restriction. Windows prevents running GUI apps from services. So I won't reopen this issue, and will close any new issue with the same subject. You can try to ask a question in the [Jenkins chatrooms](https://jenkins.io/chat/) or on [Microsoft Community](https://answers.microsoft.com) about configuring the Jenkins service. There are some configuration options, but seems they don't work well too in latest Windows versions, so I strongly suggest you to avoid using Jenkins as a service. 

You can create a Batch or PowerShell script that start Jenkins from its JAR file, and [add this script to the startup directory](https://support.microsoft.com/en-us/help/4026268/windows-10-change-startup-apps). If you need to restart your Jenkins machine frequently, you can configure automatic logon.

**Comment by arobertsf** [comment]
@AndreyBelym Thanks, we will try these work-arounds.  I don't want to bug you guys further, but still just trying to connect "Windows prevents running GUI apps from services" with the fact that Chrome and Firefox GUI apps work fine.  Is there some kind of automatic headless mode that both Chrome and Firefox (partially, since we needed service/reg changes for the latter) are invoking behind the scenes, which IE11 lacks?
