### ISSUE TITLE
Cannot run tests in the Private mode in Firefox

### ISSUE THREAD

**Issue by VasilyStrelyaev** [DevExpress/testcafe#1675]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

When trying to launch Firefox with a Private mode flag, it opens two windows: one regular and one private. And tests run in the regular window.

### What is the expected behavior?

One window should be opened and, more important, test should run in the Private window.

### How would you reproduce the current behavior (if this is a bug)?

```sh
testcafe "firefox -private-window" tests/test.js
```

#### Provide the test code and the tested page URL (if applicable)

 n/a

### Specify your

* operating system: Windows 10
* testcafe version: 0.17.0
* node.js version: 6.9.4

**Comment by oliversturm** [comment]
This happens the same way on my system. I'm passing `--private-window` (double dash), but the behavior is the same. 

* Operating system: Ubuntu 16.10
* testcafe version: 0.17.1
* node.js: 8.4.0

**Comment by GrafDa** [comment]
Still not working.

Operating system: Windows 10
testcafe version: 1.4.3
node.js: 12.2.0

**Comment by Vitalii4as** [comment]
Same problem

Ubuntu 24.04
testcafe 3.6.2
node.js 20.14.0

**Comment by PavelMor25** [comment]
Hello @Vitalii4as,

Could you please clarify why it's necessary for you to run the test in Private mode?

**Comment by Vitalii4as** [comment]
Hi @PavelMor25. Our application supports validation of license key in the browser, some license information is stored on the client side in local storage. The local storage is cleared when the incognito window is closed. So, we show a warning message to the user when he/she tries to validate license key in incognito mode. We want to test that such a warning is shown and that we can detect that the user uses an incognito window. It works fine in chrome and edge but in firefox I get the behavior described in this issue.

**Comment by Vitalii4as** [comment]
@PavelMor25 Sorry, not sure what you mean. We use [this library](https://www.npmjs.com/package/detectincognitojs) to detect whether the incognito window is used. It works fine for our use cases. But I'm not sure how it can be related to this issue.

**Comment by PavelMor25** [comment]
@Vitalii4as, The issue you're facing is quite complex and represents a less popular use case. Unfortunately, we won't be able to take it on at this time as our team is currently focused on other priorities.
We appreciate your understanding, and we’re always here to assist with any other questions or challenges you may encounter.
