### ISSUE TITLE
Should have ability to run a test case multiple times based on criteria

### ISSUE THREAD

**Issue by djbreen7** [DevExpress/testcafe#1676]
### Feature Request
Coming from NUnit, I would like the ability to run a test multiple times based on criteria. This is slightly addressed with the Roles feature. Here's an example of what I'd like

```js
let phoneNumbers = ["123", "5555555555", "(555)555-5555", "lizard", "-1"];
test('Should display error for invalid phone number', async (t, phoneNumbers[i]) => {
        await t
        // test each case, write code once
    });
```

Workaround: for now, I've wrapped my fixture in a forEach. This doesn't work perfectly though. 
* If I just want to run one test with two cases, the forEach is ignored.
* If tests have different numbers of test cases (2, 3, 5), then forEach is not a solution.

Here's what it looks like in C# (NUnit)
```csharp
        [TestCase("123")]
        [TestCase("5555555555")]
        [TestCase("(555)555-5555")]
        [TestCase("lizard")]
        [TestCase("-1")]
        public void Should_Display_Error_For_Invalid_Phone_Number(string phone)
        {
            // Test each case, write code once
        }
```

### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
Test cases with multiple roles still require additional code within the test case

### What is the expected behavior?
As stated above.

### How would you reproduce the current behavior (if this is a bug)?
NA

### Specify your

* operating system: Windows 10
* testcafe version: 0.17
* node.js version: 8.1.2

**Comment by inikulin** [comment]
@djbreen7 You can wrap individual tests in `forEach`, I guess covers both of your use cases.

**Comment by djbreen7** [comment]
@inikulin: I'll have to confirm, but I don't think a forEach wrapped around a `test` will work if you run a single test, i.e., using VS Code extension to run an individual test out of a fixture. I'll give it a shot though and see what happens.

**Comment by djbreen7** [comment]
@inikulin: I stand corrected.
