### ISSUE TITLE
Selecting an id only when its visible in UI

### ISSUE THREAD

**Issue by neelay** [DevExpress/testcafe#1682]
### Are you requesting a feature or reporting a bug?
Not sure feature or bug

### What is the current behavior?
I am creating a test where #menu-toggle id is visible only in mobile mode, but in browser mode it is not visible. I am trying to write a common test which can be used both in web mode and mobile layout mode. 

I am trying to check if #menu-toggle is visible. Currently, it shows visible in both the modes. Even though in browser it is not visible in UI.  I did not proceed with that. 

Next option I tried is 
```const menuToggleBar = await Selector('#menu-toggle');
     if ( menuToggleBar.offsetWidth > 0){
     await t 
              .click(menuToggleBar)
     }
```

The above code does not work as menuToggleBar.offsetWidth returns a promise. How do I achieve the selection of menuToggleBar only when its visible.

### What is the expected behavior?

To able to click on menuToggleBar when its visible

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
Mac OS 10.12.6
* testcafe version:
0.17.0
* node.js version:
v6.11.2

**Comment by neelay** [comment]
```
const menuToggleBar =  Selector('#menu-toggle');
    const offset = await menuToggleBar.offsetWidth
    if (offset>0){
        await t
            .click(menuToggleBar)
    }
```

I was incorrectly doing await on Selector()

It works now.

**Comment by AlexanderMoskovkin** [comment]
Hi @neelay,

Your solution is ok. Also you can use the `visible` property:

```js
if (await menuToggleBar.visible)
    await t.click(menuToggleBar);
```

**Comment by neelay** [comment]
thank you @AlexanderMoskovkin. 

Your solutions is more elegant and it works.
