### ISSUE TITLE
#Question #Feature Take screenshot of entire webpage.

### ISSUE THREAD

**Issue by alltheoptions** [DevExpress/testcafe#1683]
### Are you requesting a feature or reporting a bug?

Feature / Question

### What is the current behavior?

[Take Screenshot](http://devexpress.github.io/testcafe/documentation/test-api/actions/take-screenshot.html) is not taking screenshot of entire webpage.

### What is the expected behavior?

Take Screenshot takes screenshot of entire webpage.

**Comment by AlexanderMoskovkin** [comment]
Hi @alltheoptions,

We have such proposal in the #1520 issue. Can you add 👍 to it, please? We usually give higher priority to voted issues.

**Comment by alltheoptions** [comment]
@AlexanderMoskovkin hello, thank you.

Do you realize we can automate github registration and vote the issue also?::) 📦

**Comment by AlexanderMoskovkin** [comment]
I think we will detect it 😁
