### ISSUE TITLE
Test hangs when `takeScreenshot` is called in headless Chrome Canary on Windows

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#1685]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

test hangs on Windows (works properly on MacOS)

#### Provide the test code and the tested page URL (if applicable)

```js
fixture('example')
    .page('http://example.com');

test('take screenshot', async (t) => {
  await t.takeScreenshot();
});
```

### Specify your

* operating system: Windows 10
* testcafe version: 0.17.0
* browser: Version 62.0.3181.0 (Official Build) canary (64-bit)

**Comment by AndreyBelym** [comment]
Looks like it is a Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=754708

Workaround is on the way.

BTW, headless is available in the latest Chrome stable on Windows, we should change the docs to get rid of Canary notes.

**Comment by AlexanderMoskovkin** [comment]
@AndreyBelym Create please a separate issue with the `Documentation` label and assign it to @VasilyStrelyaev since it's a separate task
