### ISSUE TITLE
Restart failed tests via command-line

### ISSUE THREAD

**Issue by gyopiazza** [DevExpress/testcafe#1687]
Hello, I can't find an option to restart only the failed tests through the command-line. Is it possible?

Thanks!

**Comment by AlexanderMoskovkin** [comment]
Hi @gyopiazza,

TestCafe has no such option. Each test run is independent from others and TestCafe doesn't keep any state between runs. 
Meanwhile TestCafe has the [quarantine-mode](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-q---quarantine-mode) option. It possible it meets your need.

**Comment by gyopiazza** [comment]
Thanks @AlexanderMoskovkin, that might work!

**Comment by AlexanderMoskovkin** [comment]
You're welcome!
