### ISSUE TITLE
TestCafe can't find browsers on Window that are installed only for a current user

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#1688]
See https://github.com/DevExpress/testcafe-browser-tools/issues/128

**Comment by Master244** [comment]
+1 it doens't matter what I do reinstall ad chrome to my path ( I can start it with chrome from terminal ),

The testcafe package globally or locally installed will never see any listed browsers running testcafe -b 

Installed Firefox didn't pop up on -b reinstalled testcafe still no luck and your docementation really lacks on this issue or how to force a default browser.

**Comment by AlexanderMoskovkin** [comment]
We've found the cause of the problem and we're going to fix it soon.
As a temporary workaround you can pass a path to the installed browser to TestCafe (See [Portable Browsers](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#portable-browsers)).

**Comment by Master244** [comment]
I tried with portableChrome but no matter what browser I use it keeps saying unable to find browser. Even if I install the browser in my user folder

**Comment by AlexanderMoskovkin** [comment]
do you mean the approach like `testcafe path:d:\chromeportable\chromeportable.exe tests/sample-fixture.js` doesn't work on your side?

**Comment by Master244** [comment]
Nope, but it might be a problem with my work computer as well, regarding permissions, I will try and install firefox in my user Folder and try again.

**Comment by Master244** [comment]
but should it work with portable chrome'? Because that I tried and that also didn't work

**Comment by AlexanderMoskovkin** [comment]
> but should it work with portable chrome'? Because that I tried and that also didn't work

what the error do you see in the report?

**Comment by Master244** [comment]
`testcafe path "/c/Users/barrybadpak/chrome/GoogleChromePortable" tests/**/*test.js -r list -S -s report/screenshots/ -e --selector-timeout 500000 --assertion-timeout 10000
Using locally installed version of TestCafe.
ERROR Was unable to open the browser "path:" due to error.

TypeError: Cannot read property 'trim' of undefined
    at Object.callee$0$0$ (C:\Users\barrybadpak\WORK\end-to-end-test\node_modules\testcafe-browser-tools\lib\api\get-browser-info.js:54:41)
    at tryCatch (C:\Users\barrybadpak\WORK\end-to-end-test\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:72:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\barrybadpak\WORK\end-to-end-test\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:334:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\barrybadpak\WORK\end-to-end-test\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:105:21)
    at tryCatch (C:\Users\barrybadpak\WORK\end-to-end-test\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:72:40)
    at invoke (C:\Users\barrybadpak\WORK\end-to-end-test\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:146:20)
    at C:\Users\barrybadpak\WORK\end-to-end-test\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:154:13`

**Comment by Master244** [comment]
also tried with adding the executable, /c/Users/barrybadpak/chrome/GoogleChromePortable/chrome.exe

**Comment by AlexanderMoskovkin** [comment]
> testcafe path "/c/Users/barrybadpak/chrome/GoogleChromePortable" tests/**/*test.js

Your syntax is not quite correct. It should be like this:
```
testcafe "path:`C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`" d:\temp\gh-1679.js
```

Note, it necessary to pass a path to a Chrome executable file.

**Comment by Master244** [comment]
I already noticed that and tried that same error, then I got it to work with the nightmare browser. But then I took the trouble of getting a new computer here at work with full root acces, that one does run with chrome and all my test pass. On my own computer not with root acces ( work laptop ) they all fail with nightmare. Any ideas?

**Comment by AlexanderMoskovkin** [comment]
Have you tried exactly the same syntax as in my example?

```
testcafe "path:`C:\Users\barrybadpak\chrome\GoogleChromePortable\chrome.exe`" tests/**/*test.js
```

It should be a `:` symbol after the `path` part and the path should be started with `C:\`.
If this command run is failed too please provide me.

> On my own computer not with root acces ( work laptop ) they all fail with nightmare. Any ideas?

Do you mean you are able to run tests in nightmare but they are failed? If yes please let me know what the errors do you see?

**Comment by Master244** [comment]
https://github.com/ryx/testcafe-browser-provider-nightmare/issues/7 In nightmare I googled my errors and I think it has something to do with the fact that the window size is too small and the buttons don't appear properly ( our site is not so responsive yet ) but preferable I will try your command. Because during devloping seeing the test is way better :) ( the screenshots don't tell me a lot )

**Comment by Master244** [comment]
![1](https://user-images.githubusercontent.com/5592239/29274845-796c48fe-8109-11e7-9186-361727ae4e57.png)

**Comment by Master244** [comment]
testcafe "path:`C:\Users\barrybadpak\chrome\GoogleChromePortable\chrome.exe`" tests/**/*test.js

I tried this too but it says same error:

 testcafe "path:`C:\Users\barrybadpak\chrome\GoogleChromePortable\chrome.exe`" tests/**/*test.js
bash: C:UsersbarrybadpakchromeGoogleChromePortablechrome.exe: command not found
Using locally installed version of TestCafe.
ERROR Was unable to open the browser "path:" due to error.

TypeError: Cannot read property 'trim' of undefined
    at Object.callee$0$0$ (C:\Users\barrybadpak\WORK\end-to-end-test\node_modules\testcafe-browser-tools\lib\api\get-browser-info.js:54:41)
    at tryCatch (C:\Users\barrybadpak\WORK\end-to-end-test\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:72:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\barrybadpak\WORK\end-to-end-test\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:334:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\barrybadpak\WORK\end-to-end-test\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:105:21)
    at tryCatch (C:\Users\barrybadpak\WORK\end-to-end-test\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:72:40)
    at invoke (C:\Users\barrybadpak\WORK\end-to-end-test\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:146:20)
    at C:\Users\barrybadpak\WORK\end-to-end-test\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:154:13

**Comment by Master244** [comment]
but using the path with a CD command does work

**Comment by AndreyBelym** [comment]
That's because you should escape backslashes in Bash: http://wiki.bash-hackers.org/syntax/quoting. e.g. `C:\\Users\\barrybadpak\\chrome\\GoogleChromePortable\\chrome.exe`. Or use regular slashes: `C:/Users/barrybadpak/chrome/GoogleChromePortable/chrome.exe`

**Comment by Master244** [comment]
@AndreyBelym That worked! Though it started up the browser nothing seems to be happening. The full command im using now is 

testcafe "path:`/c//Users//barrybadpak//chrome//GoogleChromePortable//chrome.exe`" -r list -S -s report/screenshots/ -e --selector-timeout 500000 --assertion-timeout 10000

**Comment by Master244** [comment]
Just stating that this all works perfectly fine one computer with root acces and the build in chrome browser

**Comment by Master244** [comment]
A workarround for this if your user does not have access to program files, copy paste the chrome folder somewhere within your user folder and specify the path. 

"test": "testcafe path:C:\\Users\\barrybadpak\\chrome\\GoogleChromePortable\\chrome.exe tests/**/*test.js -r list -S -s report/screenshots/ -e --selector-timeout 500000 --assertion-timeout 10000"

don't use ``

**Comment by AlexanderMoskovkin** [comment]
> don't use ``

It's necessary if you have spaces in the path to the browser executable
