### ISSUE TITLE
[feature] enable webpack as the module loader

### ISSUE THREAD

**Issue by mpham-r7** [DevExpress/testcafe#1699]
### Are you requesting a feature or reporting a bug?
Requesting a feature

### What is the current behavior?
Cannot use webpack as the module loader. For example, I wanted to use it to import files that require preprocessing (e.g. via webpack) into tests.

e.g. if i wanted to identify an element via its css-module class name (in a test), i would do something like:
```
import styles from 'src/components/SomeComponent/styles.scss'
t.click(Selector(styles.someButton))
```

### What is the expected behavior?
enable webpack as the module loader if possible. this would enable the above use-case (does anyone have any alternate ideas if that's not possible?)

**Comment by miherlosev** [comment]
We decided to not implement this feature because there is not much interest in this among the community. However, if this feature is important for you, you can create a PR yourself.
