### ISSUE TITLE
Headless Chrome process doesn't terminate on Arch Linux

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#1700]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Headless Chrome process doesn't terminate after tests have been runned.

### What is the expected behavior?
Headless Chrome process should be terminated

### How would you reproduce the current behavior (if this is a bug)?
Run tests on ArchLinux.

### Specify your

* operating system: Arch Linux
* testcafe version:
* node.js version:

**Comment by watermelonjuice** [comment]
This happens both when tests are successful and when chrome process crashes due to going over 2GB memory consumption. 

Testcafe version: 0.17.0
Node version: v8.3.0

**Comment by AndreyBelym** [comment]
I close this issue due to a long inactivity period. Please feel free to reopen the issue if you still can reproduce the problem with the latest TestCafe version.
