### ISSUE TITLE
If testcafe provide http interceptor and use it to record http req/res?

### ISSUE THREAD

**Issue by CommanderXL** [DevExpress/testcafe#1706]
### Are you requesting a feature or reporting a bug?

feature

### What is the current behavior?

Well, I hava joined a very complex webapp project.And I used testcafe for this project, I performs very well, our engineers like it.I read the document,I didn't find some topic about http request and response.So I want to know if testcafe has some plugin or tools to record the http req/res and log to the report.So we can record the whole test process.

### What is the expected behavior?

Well.If testcafe provide the http req/res interceptor, we use it to record http req/res and log it to the report.We can compare the req/res to the real page.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by watermelonjuice** [comment]
Use a proxy like privoxy to do this.

**Comment by churkin** [comment]
Hi @CommanderXL,
At the moment TestCafe does not have this functionality out of the box, but this task is on our To-Do list and our guys are working on it. I think this feature will be available soon. Please track this issue https://github.com/DevExpress/testcafe/issues/1341 status.
