### ISSUE TITLE
Can I log the custom test info?

### ISSUE THREAD

**Issue by CommanderXL** [DevExpress/testcafe#1709]
### Are you requesting a feature or reporting a bug?

feature

### What is the current behavior?

Well,I read the testcafe doc, I found the Reporter Plugin can redefine the report format using the Reporter Methods like reportTaskStart and the other three.It likes the report hooks.I trigger during the test cycle life.So I want to know if there are some other methods to log custom info in the test code.

just like:

```javascript
    await t
       .doubleClick('.foo')
       .log('double click the foo')
       .click('.bar')
       .log('click the bar')
```

It will log the custom info to the report.

### What is the expected behavior?

Log the custom test info in the test code where you'd like.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by MarinaRukavitsyna** [comment]
@CommanderXL No, it is not possible to use a reporter inside a test to show custom information. It is also unlikely that we will implement "await t.log('double click the foo')" since there is an equivalent already. Please use console.log('double click the foo').

**Comment by AndreyBelym** [comment]
Could you please clarify what do you mean by 
> information or actions performed by TestCafe method?
Raised DOM events? Method arguments? IMO TestCafe methods have self-descriptive names like `t.click`, `t.typeText`, etc.

**Comment by jiteshsojitra** [comment]
As far as this ticket is concerned, we want to log information/actions performed by TestCafe in console, for e.g.

t.click('bar');
x.log('double click the foo');

**Comment by AndreyBelym** [comment]
You can use `console.log` or `console.error` to output something to the console.

**Comment by theredwillow** [comment]
```
    const cityTags = await Selector(".city.boldTxt");
    console.log("CITYTAGS:", cityTags);
```

Console.log does not log anything for me within a test() function (in neither the browser the tests are running in, nor the terminal). Am I misunderstanding something? How are we supposed to debug what the Selector is grabbing?
