### ISSUE TITLE
in ts-defs/index.d.ts file, ClientFunctionOptions.dependencies declare is error

### ISSUE THREAD

**Issue by zhangtasdq** [DevExpress/testcafe#1713]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?
in ts-defs/index.d.ts

`ClientFunctionOptions.dependencies` only receive Function,

the code is ` dependencies?: {[key: string]: Function},`

### What is the expected behavior?

`ClientFunctionOptions.dependencies`  should receive Function、String...

### How would you reproduce the current behavior (if this is a bug)?

1. create a typescript file
2. paste code 
```js
import { ClientFunction } from "testcafe";

let testMsg:string = "hello";

ClientFunction(() => window.location.href, {
    dependencies: {
        testMsg
    }
});
```

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js
import { ClientFunction } from "testcafe";

let testMsg:string = "hello";

ClientFunction(() => window.location.href, {
    dependencies: {
        testMsg
    }
});

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by AndreyBelym** [comment]
Hello @zhangtasdq! I can confirm, there is a mistake in TypeScript definitions. We'll fix it shortly. Until then you can pass strings as arguments to a `ClientFunction`:
```js
import { ClientFunction } from "testcafe";

let testMsg:string = "hello";

let myFunc = ClientFunction(testMsg => `${testMsg} ${window.location.href}`);

test('My test', async t => {
   await myFunc(testMsg);
});
```

**Comment by zhangtasdq** [comment]
@AndreyBelym Thanks  for your reply and advice!
