### ISSUE TITLE
Possibilities to get a wide-covered error report.

### ISSUE THREAD

**Issue by ajhsu** [DevExpress/testcafe#1717]
### Are you requesting a feature or reporting a bug?
Feature Request

### Description
I think the purpose of end-to-end testing (or UI testing) is to test web app automatically without doing it manually. Then, the most important part, be able to find out where goes wrong in the shortest time when test case failed. Which means locating the problem is one of the important tasks when we're doing end-to-end testing.

Once test case failed, we can only get a screenshot and the position of the code where it fails so far. But sometimes we would like to see those errors in more detail (or let's say a complete picture about what's going on), like console messages (which is super helpful to understand how the program runs) or network history (including headers and status code of network traffic) so that we can fully understand the root-cause of the failure.

While [chrome-remote-interface](https://github.com/cyrus-and/chrome-remote-interface) support Chrome DevTools Protocol like [Network.requestWillBeSent](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-requestWillBeSent) / [Network.responseReceived](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-responseReceived) to sniff request/response from page and [Runtime.consoleAPICalled](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#event-consoleAPICalled) to gather messages from console. I think it may be possible to support such feature. And maybe we can have log files, for example **network.log** or **runtime.log**, like snapshot files.

Do we have any plan on this? I think that would be super helpful!

**Comment by AlexanderMoskovkin** [comment]
Hi @ajhsu,

Thanks for your proposal. We don't plan to implement this feature soon but we can consider it for the future releases. Meanwhile, we are going to ship the [request hooks](https://github.com/DevExpress/testcafe/issues/1341) feature. It can help you create a custom request logger.

**Comment by ajhsu** [comment]
Hi @AlexanderMoskovkin ,
I will take a look into request hooks, thanks for your kindly reply!
