### ISSUE TITLE
Does testcafe support chrome cookie

### ISSUE THREAD

**Issue by haoshasha** [DevExpress/testcafe#1722]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by AlexanderMoskovkin** [comment]
Hi @haoshasha, It seems you've asked the same question in the #1721 issue. If you have a question connected to an opened issue please create a new comment there instead of opening a new issue.
