### ISSUE TITLE
Suggestion: Add headless-chromium topic to the project description for better discoverability 

### ISSUE THREAD

**Issue by alfonsodev** [DevExpress/testcafe#1725]
### Are you requesting a feature or reporting a bug?
A minor change in Project description (feature request ?)
### What is the current behavior?
The project is hard to find on Github search.
### What is the expected behavior?
I can find the project by clicking on #headless-chromium topic on Github description.  
**example:**
https://github.com/search?q=topic%3Aheadless-chromium&type=Repositories

#### Provide the test code and the tested page URL (if applicable)
Test page URL: https://github.com/search?q=topic%3Aheadless-chromium&type=Repositories

### Specify your

* operating system: any
* testcafe version: any
* node.js version: any

**Comment by AlexanderMoskovkin** [comment]
Thanks for the idea. We've investigated it and it seems the `headless-chromium` topic is too specific (I found only 5 repos with it). We've decided to don't add it.
