### ISSUE TITLE
The test can’t run remote device

### ISSUE THREAD

**Issue by CommanderXL** [DevExpress/testcafe#1732]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

Well, two days ago, I can run the test on the remote device, but it can't work now.And I didn't edit the the test scripts.

So I try to use the get started demo code you provided on the website. And type

```js
testcafe remote demo.js -e
```

But it can't run on the remote device, I get the req and res through charles,I find that it doesn't load the test page and stay in the init page:

![wechatimg13](https://user-images.githubusercontent.com/9695264/29746866-647bdf3e-8b1a-11e7-8572-893bb0f6db61.jpeg)

But I run on the chrome:

```js
test chrome demo.js -e
```

It works well, and load the demo test page.

### What is the expected behavior?

It can run on remote device correctly.

### How would you reproduce the current behavior (if this is a bug)?

I use the test demo code:

```javascript
import { Selector } from 'testcafe';

fixture `Getting Started`
    .page `http://devexpress.github.io/testcafe/example`;

test('My first test', async t => {
    await t
        .typeText('#developer-name', 'John Smith')
        .click('#submit-button');
});
```

and run it :

```javascript
test remote demo.js -e
```

No matter I open the Connect URL on the remote device or desktop chrome, it can't load the test page and stay in the initial page.But If run it :

```js
test chrome demo.js -e
```

It works well

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Mac OS X 10.11
* testcafe version: 0.17.0
* node.js version: 8.0.0

**Comment by AlexanderMoskovkin** [comment]
@CommanderXL, thanks for your report. I've reproduced the issue. We will provide you with a fix once it's available.

**Comment by CommanderXL** [comment]
@AlexanderMoskovkin Thanks very much.

Two days ago, I could run the remote test and I don't change the version of testcafe. So I doubt that the port is being occupied.But it didn't seem that.In the last two days, I tried many ways link through the node.js remote API method not CLI, but I faild too.

**Comment by farhd** [comment]
unfortunately, it still doesn't work.
node: 8.15.0
testcafe: 0.23.3
OS: 0.23.3

**Comment by AndreyBelym** [comment]
@farhd, please consider creating a [new bug report](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md) and provide an example that can be used to reproduce the problem.
