### ISSUE TITLE
MacOS: setFilesToUpload() gives    “The specified selector does not match a file input element.”

### ISSUE THREAD

**Issue by haoshasha** [DevExpress/testcafe#1734]
### Are you requesting a feature or reporting a bug?

   1) The specified selector does not match a file input element.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js
await cafe.click('.icon-dataSource')
            .click(Selector('.frame_menu').withText('电子发票'))
            .wait(config.time(1))
            .setFilesToUpload('.upload',[electric])
            .wait(10000)
```

### Specify your

* operating system:mac
* testcafe version:
* node.js version:

**Comment by AlexanderMoskovkin** [comment]
@haoshasha The error means that the first element with the `upload` className on the page is not `input` or doesn't have `type="file"`. Please check it. To do it open the tested page, open developer tools and type into the console: `document.querySelectorAll('.upload')`. See what elements are displayed.

**Comment by haoshasha** [comment]
thankyou ，My page Not input type， Just an upload button

**Comment by haoshasha** [comment]
@AlexanderMoskovkin How should I upload it?

**Comment by AlexanderMoskovkin** [comment]
It should be an `input` with `type="file"` on your page. Call the `t.setFilesToUpload` action for this input and then call `t.click` for your upload button.

**Comment by haoshasha** [comment]
![image](https://user-images.githubusercontent.com/30857050/29770284-e36fc0a6-8c20-11e7-9e92-ef74f8776659.png)

**Comment by haoshasha** [comment]
@AlexanderMoskovkin

**Comment by haoshasha** [comment]
The upload button on my page is not input type

**Comment by AlexanderMoskovkin** [comment]
Find an `input` with `type="file"` on your page. For example you can call the following command in the console:
`document.querySelectorAll('input[type="file"]')`

**Comment by haoshasha** [comment]
@AlexanderMoskovkin Support non input tags upload files?

**Comment by AlexanderMoskovkin** [comment]
@haoshasha Please read the [Upload Action](https://devexpress.github.io/testcafe/documentation/test-api/actions/upload.html) section carefully, it's actual for `input` elements only.
File uploading usually contains two actions:
1) Chose files for uploading (use `setFilesToUpload`);
2) Trigger uploading (in your case it's click on a button).

**Comment by haoshasha** [comment]
@AlexanderMoskovkin  thankyou thankyou  thankyou
