### ISSUE TITLE
import { fixture, test } from 'testcafe'

### ISSUE THREAD

**Issue by arty-name** [DevExpress/testcafe#1735]
### Are you requesting a feature or reporting a bug?

I am requesting a feature

### What is the current behavior?

`feature` and `test` are globals and have to be configured as such in ESLint

### What is the expected behavior?

I would like to avoid globals in the same way as I do in `mocha`: by importing the necessary functions from `testcafe`: 

```javascript
import { fixture, test } from 'testcafe'
```

### Specify your

* operating system: Ubuntu
* testcafe version: 0.17.1
* node.js version: 8.4

**Comment by renanbastos93** [comment]
@AndreyBelym this issue `https://github.com/DevExpress/testcafe/issues/3940`

it was don't resolved, I tested your suggestion but don't a success.

**Comment by renanbastos93** [comment]
To complement this information, we can take another approach:

Create file below:
 
.testcaferc.json
```json
"src": ["./clear.js","./tests/**/main.js"]
```
