### ISSUE TITLE
Screenshots in Chrome are black & in Firefox no screenshots

### ISSUE THREAD

**Issue by L1am0** [DevExpress/testcafe#1736]
### Are you requesting a feature or reporting a bug?

This is a bug

### What is the current behavior?

The Screenshots are not working. 

- Chrome
 there are screenshots but they are all just black 
![image](https://user-images.githubusercontent.com/24354822/29821072-f5b7bbbe-8cc6-11e7-80b6-1d117133f8ed.png)

- Firefox
no screenshots at all
![image](https://user-images.githubusercontent.com/24354822/29821104-0a4f8d72-8cc7-11e7-813d-97fddfa7bed1.png)

### What is the expected behavior?

Have screenshots working

### How would you reproduce the current behavior (if this is a bug)?

I am using TestCafe Pro. And adding the screenshots via the Recorder-

#### Provide the test code and the tested page URL (if applicable)

```
    "3.Take a screenshot": function() {
        act.screenshot();
    }
```

### Specify your

* operating system: Windows 10
* testcafe version: 15.1.3
* node.js version:  6.11.0

**Comment by AlexSkorkin** [comment]
@L1am0 
 
Please submit your "TestCafe Pro" inquiries to our Support Center at www.devexpress.com/ask. This github repo is reserved for the free TestCafe version only.
 
I recommend that you refer to the following thread where a similar inquiry was discussed: 
 
[TestCafe takes a blank screenshot when running in Chrome and FireFox](url=https://www.devexpress.com/Support/Center/Question/Details/T245982/testcafe-takes-a-blank-screenshot-when-running-in-chrome-and-firefox)
 
You need to disable the 'Use hardware acceleration when available' option, restart your browser, and see if it makes any difference. If this does not help, you know where to ask for further assistance :-)
