### ISSUE TITLE
Add maximum waiting time for remote connection to start

### ISSUE THREAD

**Issue by QuackMartins** [DevExpress/testcafe#1737]
### Are you requesting a feature or reporting a bug?
Feature

### Description
Actually testcafe waits forever for a remote browser to connect if we run `testcafe remote:1 test/*`

It would be nice if we had an option like `testcafe --remote-timeout 10s remote:1 test/*`...
Then if 10 seconds exceeds we return an `exit 1`

**Comment by dcharan** [comment]
I am working on PR for this change
