### ISSUE TITLE
Add the capability to get browser console messages

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#1738]
### Are you requesting a feature or reporting a bug?

feature suggestion

### What is the expected behavior?

It allows to check messages that your application outputs via `console.log()`, `console.warn()`, `console.error()`, `console.info()`.

One of possible use cases is described in the [Catch JS errors and console output](https://testcafe-discuss.devexpress.com/t/catch-js-errors-and-console-output/421) discussion. React notifies about a `PropTypes` error via `console.error` but doesn't call something like `throw new Error()`.

### Proposed API:
```js
fixture `My fixture`
    .beforeEach(await t => {
        var { error, warn, log, info } = await t.getConsoleMessages();

        const expectedInfoMessages = info.filter(msg => msg.indexOf('important message') > -1);

        await t
            .expect(error.length).eql(0)
            .expect(warn.length).eql(0)
            .expect(expectedInfoMessages.length).ok();
    });
```

**Feel free to vote for the feature if you consider it useful and please let us know about your use case for it.**

**Comment by dimaip** [comment]
One usecase for it would be to make tests fail on React PropTypes errors (React uses `console.error` to warn on such errors).
