### ISSUE TITLE
Worker has been utilized

### ISSUE THREAD

**Issue by mqliutie** [DevExpress/testcafe#1741]
I have created a new fixture  and REC some actions

When I run the REC the error show

**Comment by AndreyBelym** [comment]
Hello @mqliutie, your question is about "TestCafe Pro", not about the open-source version which resides in this repository. 
 
Please submit your "TestCafe Pro" inquiries to our Support Center at www.devexpress.com/ask. This GitHub repo is reserved for the free TestCafe version only.
 
BTW, looks like your worker has been disconnected for some reason. Some more information about your setup and working scenario is needed to say something more helpful.
