### ISSUE TITLE
Support headless firefox

### ISSUE THREAD

**Issue by joshuataylor** [DevExpress/testcafe#1742]
### Are you requesting a feature or reporting a bug?
[Headless firefox](https://developer.mozilla.org/en-US/Firefox/Headless_mode) was just released, which would be an awesome feature for testcafe alongside headless chrome.

### What is the current behavior?
Only normal firefox is supported.

### What is the expected behavior?
To support headless firefox.

**Comment by AlexanderMoskovkin** [comment]
Hi @joshuataylor,

Definitely we should investigate it. We'll comment here once we have any news.

**Comment by dimaip** [comment]
Really need this too! We urgently need to test FF, too many bugs slip in there, yet I don't want to setup selenium grid.
