### ISSUE TITLE
TestCafe does not have access to data URL iframe

### ISSUE THREAD

**Issue by shhnjk** [DevExpress/testcafe#1752]
### Are you requesting a feature or reporting a bug?
Reporting bug.

### What is the current behavior?
Accessing data URL iframe fails with error access is denied.

### What is the expected behavior?
TestCafe should have access to data URL iframe

### How would you reproduce the current behavior (if this is a bug)?
Access data URL iframe with .switchToIframe

#### Provide the test code and the tested page URL (if applicable)

---------------------------------------------------------------
import { Selector } from 'testcafe';

fixture `Getting Started`
    .page `https://test.shhnjk.com/iframer.php?url=data:,test`;

test('My first test', async t => {
await t
    .switchToIframe("#frame0");

    const test = await t.eval(() => document.body.innerText);

    await t.expect(text).eql('test');
});
-----------------------------------------------------------------

### Specify your

* operating system: Windows 10
* testcafe version: Latest (downloaded today)
* node.js version: Latest (downloaded today)

**Comment by shhnjk** [comment]
I repro this with Edge. I haven't tested other browsers.

**Comment by miherlosev** [comment]
I've created the separate issue in another repository https://github.com/DevExpress/testcafe-hammerhead/issues/1297
