### ISSUE TITLE
iframe gets wrong origin

### ISSUE THREAD

**Issue by shhnjk** [DevExpress/testcafe#1753]
### Are you requesting a feature or reporting a bug?
Bug.

### What is the current behavior?
Content inside iframe gets wrong origin, and stop test.

### What is the expected behavior?
It gets right origin.

### How would you reproduce the current behavior (if this is a bug)?
navigate iframe to javascript URL

#### Provide the test code and the tested page URL (if applicable)

Test code

```
1import { Selector } from 'testcafe';

fixture `Getting Started`
    .page `https://test.shhnjk.com/iframer.php?url=https://shhnjk.com`;

test('My first test', async t => {
await t
    .switchToIframe("#frame0");

    await t.eval(() => location.href="javascript:document.write(document.domain)");

    const text = await t.eval(() => document.domain);

    await t.expect(text).eql('https://shhnjk.com');
});

```

### Specify your

* operating system: Windows 10, Edge
* testcafe version: latest
* node.js version: latest

**Comment by miherlosev** [comment]
Fixed in https://github.com/DevExpress/testcafe-hammerhead/issues/1289.
Waiting for update the `testcafe-hammerhead` dependency.

**Comment by miherlosev** [comment]
Fixed in https://github.com/DevExpress/testcafe-hammerhead/pull/1290.
The fix will be included to the next release version. You can try it in the latest `dev` version (`npm install testcafe@0.17.3-dev20170913` or `npm install testcafe@dev`).
