### ISSUE TITLE
[docs] Improve the Selectors topic

### ISSUE THREAD

**Issue by VasilyStrelyaev** [DevExpress/testcafe#1760]
(On behalf of Oliver Sturm)

### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

The topic is long and some phrasing is vague

### What is the expected behavior?

**Oliver Sturm** on selectors API:

Right, thanks for clarifying. I think the docs could do with some improvement in that area: 
 
Clarify that by "descendants" you mean descendants of any depth. Add the comparable CSS selector with a link to a good description (incidentally, the w3 schools page on that topic also sucks).
Clarify that by "child" you mean direct children. Again, comparable CSS.
Show more examples for the various selector forms. I noticed that the section on child, for instance, is followed by an example of using the filter function (not really an example anyway, rather a syntax example). Why not show examples using various CSS selectors, and other simple overloads of various helper functions?
I think it would also be good to split up the docs about Selector, because they are way too long to read comfortably.
Generally I didn't find this part of the docs very helpful. I read most of it, some of it a few times, before I asked my question in this thread. However, I didn't correctly pick up on some of the language - elements vs nodes, for instance. After all, I'm reading documentation, not a scientific text. I was expecting explanation, not the necessity to evaluate each term and phrase extremely carefully in order to grasp important distinctions.
I'll gladly help with improvements, if you'd like - thanks for your help!

### How would you reproduce the current behavior (if this is a bug)?

n/a

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by titerman** [comment]
Related issues:

https://github.com/DevExpress/testcafe/issues/6083
https://github.com/DevExpress/testcafe/issues/3007
https://github.com/DevExpress/testcafe-doc-issues/issues/17
