### ISSUE TITLE
Need for proxy ignore/bypass feature

### ISSUE THREAD

**Issue by wengxuan** [DevExpress/testcafe#1791]
### Are you requesting a feature or reporting a bug?
feature

### What is the current behavior?
For individual devoloper at home, it's enough to have basic proxy settings as document discribe. We can set proxy host, port and also auth.
[https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--proxy-host](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--proxy-host)

### What is the expected behavior?
However, when you work in a company, you have to visit the internet through company's intranet. There exist some limitations. Some sites only can visit from inside network, and others need to use proxy.
In IE `LAN Setting`, we can set proxy, port and address not use proxy. So can we add an issue of `proxy --ignore/bypass` ?
I saw [Issue1206](https://github.com/DevExpress/testcafe/issues/1206) had mentioned this feature, but for some reason not added.
Guys, if you have this needs, add your comments under this issue. Thank you.

Long live testcafe! xD

**Comment by AlexanderMoskovkin** [comment]
Hi @wengxuan,

Thanks for you proposal. We'll consider it on future releases planning. If someone is interested in this feature feel free vote for it and leave your comments.

**Comment by n0v1** [comment]
We also have to use a corporate proxy to access some ressources but our backend is only accessible directly without proxy. It would be ideal if Testcafe would respect the NO_PROXY environment variable or had an equivalent option.

**Comment by AlexanderMoskovkin** [comment]
Thanks for your feedback. I guess we'll consider it on the next release planning soon

**Comment by raDiesle** [comment]
Great

**Comment by maximgeerinck** [comment]
Also looking forward to this, can not access local resources without

**Comment by AlexKamaev** [comment]
closed in #2187

**Comment by AlexanderMoskovkin** [comment]
Done in #2209

**Comment by n0v1** [comment]
I tested the proy bypass feature with version `v0.19.2-alpha1` and it works perfectly for our use case. Thank you very much!
