### ISSUE TITLE
Add ability to debug client scripts during test execution using source map mechanism

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#1793]
From [discuss](https://testcafe-discuss.devexpress.com/t/debugging-transformed-not-bundled-code-while-running-the-tests/439/3)

* testcafe version: 0.17.2

**Comment by Scyks** [comment]
+1

**Comment by cdoger** [comment]
+1

**Comment by Neatoro** [comment]
+1

**Comment by AlexKamaev** [comment]
This functionality works in Native Automation mode. Please refer to this help topic for details: [https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode)
