### ISSUE TITLE
Before and After hooks parameter is an empty object instead of a test controller

### ISSUE THREAD

**Issue by classicalConditioning** [DevExpress/testcafe#1821]
### Are you requesting a feature or reporting a bug?
bug

### What is the current behavior?
```js
fixture('Test fixture')
  .page('http://google.com/')
  .before(async t => {
    console.log(t);
  })
  .after(async t => {
    console.log(t);
  })
  
  test('Scenario 1. ', async t => {

  })`
```

this currently outputs `{}` to the console in both hooks

### What is the expected behavior?
`t` should be an Object that represents the test **controller** as per
[documentation](http://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#fixture-hooks)

### How would you reproduce the current behavior (if this is a bug)?
see fixture code provided above

### Specify your

* operating system: Windows 10
* testcafe version: 0.17.2
* node.js version: 6.10.2

**Comment by inikulin** [comment]
Hi @classicalConditioning,

It's an intended behaviour of fixture hooks, for further details please refer to https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#fixture-hooks
