### ISSUE TITLE
Different behavior between testcafe testing and manual testing

### ISSUE THREAD

**Issue by dhilgarth** [DevExpress/testcafe#1822]
### Are you requesting a feature or reporting a bug?

A bug, I guess.

### What is the current behavior?

In some circumstances, an automated test with testcafe is successful, while the same test, performed manually, isn't successful. I have seen this happening with two very different tests in IE11.
Is testcafe somehow polluting the global namespace with some polyfills?

### What is the expected behavior?

It is expected that there is no difference between automated and manual testing

### How would you reproduce the current behavior (if this is a bug)?

I am working on a reproduction.

#### Provide the test code and the tested page URL (if applicable)

Tested page:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>testcafe bug</title>
    <style>
        #container { display: inline-block; }
        #hover-indicator { display: none; }
        #container:hover > #hover-indicator { display: block; }
    </style>
</head>
<body>
<div id="container">
    <p id="hover-indicator">Hovering over page</p>
    <iframe src="http://www.fire-development.com"></iframe>
</div>
</body>
```

Test code

```js
test("Hovering the iframe shows the text", function(t) {
    return t
        .hover(Selector("#container"))
        .expect(Selector("#hover-indicator").visible)
        .ok("Not visible, but should be");
});
```

In IE, when hovering over an iFrame, the parent elements outside the iFrame - in the parent page - do not get the `:hover` pseudo class, and therefore, the `p` should only be visible while moving the mouse over the border of the element. As soon as the mouse is over the iFrame, it should disappear again.
Still, the test passes, and just from looking at it during executing, it is evident that the text is not disappearing.

### Specify your

* operating system: Windows 10
* testcafe version: 0.17.2
* node.js version: 6.10.2

**Comment by AlexanderMoskovkin** [comment]
Hi Daniel,

Not, TestCafe shouldn't pollute the global namespace with any polyfills. The page should work in the same way as it works without TestCafe. If something is wrong it's likely a bug. We're looking forward to an example where we can reproduce it.

**Comment by dhilgarth** [comment]
Hi Alex,

thanks for the quick feedback. I have added a reproduction.
Please let me know, if that helps.

**Comment by dhilgarth** [comment]
Interestingly enough, the behaviour is correct - the test fails - if the `p` tag is moved outside of `#container`.

**Comment by AlexanderMoskovkin** [comment]
Thanks for the details. I've reproduced the problem and will fix it
