### ISSUE TITLE
Test run report contains inaccurate information about browsers

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#1827]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

For `chrome:headless`  there is no version
- HeadlessChrome 0.0.0 / Windows 10 0.0.0

For `firefox:headless` there is no information about headless mode
- Firefox 57.0.0 / Windows 10 0.0.0

**Comment by AlexanderMoskovkin** [comment]
> For chrome:headless there is no version

It's fixed with the latest Chrome and TestCafe versions

![image](https://user-images.githubusercontent.com/12047804/36247178-1e098540-1244-11e8-9654-e4a35ab69240.png)

**Comment by AlexanderMoskovkin** [comment]
We write the info that the browser provides. I guess it's ok.
