### ISSUE TITLE
Resolve absolute and relative file paths for `t.navigateTo`

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#1837]
Need to resolve absolute and relative file paths for `navigateTo` action.
Same as for a `page` directive.
See also https://github.com/DevExpress/testcafe-hammerhead/issues/1330

* testcafe version: 0.18.0-alpha1

**Comment by rob4629** [comment]
Should something be done, to stop this issue being closed/locked?

**Comment by AlexSkorkin** [comment]
@rob4629, we will keep it opened.

**Comment by AlexKamaev** [comment]
According to the following help topic, the issue is fixed: [https://testcafe.io/documentation/402695/reference/test-api/testcontroller/navigateto](https://testcafe.io/documentation/402695/reference/test-api/testcontroller/navigateto).
