### ISSUE TITLE
Chrome headless not opening due to missing flags

### ISSUE THREAD

**Issue by KaneMorgan** [DevExpress/testcafe#1838]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
I'm trying to run testcafe inside of a docker container based on openshift/jenkins-slave-base-centos7. using chrome headless.

The command I run is:
`node_modules/testcafe/bin/testcafe.js chrome:headless integration_tests`

The tests fail to run and after a while i get the following exception

```
Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
```

After some digging I've found that the problem is that chrome headless needs a couple of additional flags to run correctly. This command opens the browser successfully and runs the tests

```
node node_modules/testcafe/bin/testcafe.js 'chrome:headless --no-sandbox --disable-gpu' integration_tests
```

Could these arguments be passed in by default?

As an aside i found it a little tricky working the syntax for passing in the additional flags, could this be added to the readme?

### Specify your

* operating system: docker container running centos7
* testcafe version: 0.17.2
* node.js version: v6.11.3

**Comment by AndreyBelym** [comment]
Hello @KaneMorgan!

We already have a note about `--no-sandbox` flag in our [docs](https://devexpress.github.io/testcafe/documentation/using-testcafe/installing-testcafe.html#using-testcafe-docker-image):
```
Add the --no-sandbox flag to Chromium if the container is run in the unprivileged mode.
```

So if you run the image with `docker run --privileged`, you won't need this flag.

Also, official TestCafe image based on Alpine + Chromium works fine without `--disable-gpu` flag on Docker Toolbox for Windows and Mac. Could you please try to run your image without it, only with `--no-sandbox` flag?

**Comment by KaneMorgan** [comment]
Thanks for the speedy response.
yes it seems to work with just the no-sandbox flag, 

I'll close this issue
