### ISSUE TITLE
Add possibility to press and hold the key

### ISSUE THREAD

**Issue by kirovboris** [DevExpress/testcafe#1839]
### Are you requesting a feature or reporting a bug?

feature

### What is the current behavior?

We disable mouse click modifiers for the next action.

### What is the expected behavior?

I want to hover on the element, press the key, hold it and do click, smth like:
```js
await t
    .hover('.el-inactive')
    .holdKey('ctrl')
    .click('.el-active')
```
or hover modifiers just should work in the next action, but it inconsistent.

### Specify your

* operating system: any
* testcafe version: 0.18.0-alpha1
* node.js version: any supported

**Comment by AlexanderMoskovkin** [comment]
I'd prefer to fix your case in the other way.

Now when you call `click(el, { ctrl: true })` we just set the `ctrl` property in click dom events (mousedown, click, mouseup etc..) to true. 
But to be more correct we should emulate pressing the `ctrl` key, then perform click, then release the `ctrl` key.
If we implement this you need to just call `.click(el, { ctrl: true })`.

Would it fit you needs? /cc @kirovboris

**Comment by palpatine1991** [comment]
I would also ask for such functionality. In some scenarios you need to create callbacks not on keyPress action but on keyDown/keyUp. In my case, we are implementing "accelerator keys" where on alt+key we are adding focus to input. On alt press, we change the styling of particular character in input's label. On alt release, we put the appearance back to original state.

**Comment by harryCompu** [comment]
Hi 

Can anyone help me on this ? Is hold and release key implemented ? I want to click two rows by holding ctrl key and mouse click . 

This code is not clicking two rows 
await testController.click(firstRow).pressKey('ctrl').click(secondRow); 

please how to hold ctrl button?

**Comment by djwashburn** [comment]
Using .click(el, { ctrl: true }) is not working for me - trying to select multiple rows in a jQuery DataTable, for what it's worth. Triggering the event using jQuery from the console (i.e., `.trigger($.Event("click", { ctrlKey: true }))` ) works just fine, but no approach using testCafe has been able to work. I need to be able to test this behavior (multiple selection).

**Comment by djwashburn** [comment]
I found this documentation about sending multiple targets to a click action [here](https://testcafe.devexpress.com/Documentation/API_Reference/Test_Fixture_API/User_Actions/): 

> The following example shows how to pass an array of targets to the Click action. (TestCafe Example Page)
> 
> ```
> '@test'['Click Checkboxes and Check State'] = {
>     'Click two checkbox labels': function() {
>         var labels = [ $(':containsExcludeChildren(Support for testing on remote devices)'), 
>                        $(':containsExcludeChildren(Reusing existing JavaScript code for testing)') ];
>         act.click(labels);
>     },
>     'Confirm checked state': function() {
>         ok($('#testing-on-remote-devices').is(':checked'));
>         ok($('#re-using-existing-javascript').is(':checked'));
>     }
> };
> ```

...however the entire API seems to be completely different, so I'm not sure how I would go about using this feature in my existing test code. What is the relationship between the API documented at https://testcafe.devexpress.com/ and the one documented at https://devexpress.github.io/, which I am used to?

**Comment by djwashburn** [comment]
I have devised a workaround using client functions and jQuery, others may find it useful:

```
var ctrlClickRow = ClientFunction((row) => {
	$('#theTable > tbody > tr:nth-child(' + row + ')').trigger($.Event("click", { ctrlKey: true }));
});
```

**Comment by AlexanderMoskovkin** [comment]
Hi @harryCompu @djwashburn,

You can use the [modifiers](https://devexpress.github.io/testcafe/documentation/test-api/actions/action-options.html#click-action-options) option of the `Click` action.

I've created an example to demonstrate it on the DevExtreme Data Grid demo:
```js
import { Selector } from 'testcafe';

fixture `grid-selection`
    .page `https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/MultipleRecordSelectionModes/jQuery/Light/`;

test('New Test', async t => {
    const iframe = Selector('#demoFrame');
    const row = Selector('.dx-row');

    await t
        .switchToIframe(iframe)
        .click(row.withText('New York'), { modifiers: { ctrl: true } })
        .click(row.withText('Denver'), { modifiers: { ctrl: true } })
        .expect(row.withText('New York').hasClass('dx-selection')).ok()
        .expect(row.withText('Denver').hasClass('dx-selection')).ok();
});
```

**Comment by AlexanderMoskovkin** [comment]
@djwashburn 

> What is the relationship between the API documented at https://testcafe.devexpress.com/ and the one documented at https://devexpress.github.io/, which I am used to?

We've answered this question in the [FAQ Section](https://devexpress.github.io/testcafe/faq/#what-is-the-difference-between-a-paid-and-an-open-source-testcafe-version).

**Comment by Artem-Babich** [comment]
Hi all,

Most of the test cases can be covered by calling actions with modifiers. If you have a usage scenario where you need to hold a key before performing some action, you can use the [dispatchEvent](https://testcafe.io/documentation/403091/reference/test-api/testcontroller/dispatchevent) action. Please note that the exact event types and calling orders depend on your application logic.
Here is an example where I hold the Shift key that hides one button and replaces it with a new one:

```html
<html>
<head>
    <style>
        .invisible {
            display: none;
        }
    </style>
</head>
<body>
<button id="button1">VisibleButton</button>
<button id="button2" class="invisible" onclick="document.getElementById('result').innerText = 'Test'">InvisibleButton</button>
<span id="result"></span>
<script>
    document.addEventListener('keydown', function (e) {
        if (e.key !== 'Shift')
            return;

        document.getElementById('button1').className = 'invisible'
        document.getElementById('button2').className = ''
    })
    document.addEventListener('keyup', function (e) {
        if (e.key !== 'Shift')
            return;

        document.getElementById('button1').className = ''
        document.getElementById('button2').className = 'invisible'
    });
</script>
</body>
</html>
```

```js
import { Selector } from 'testcafe';

fixture\\\`Fixture\\\`
    .page\\\`./index.html\\\`;

test('Test', async t => {
    const button2 = Selector('#button2');
    const result  = Selector('#result')

    const eventArgs = {
        bubbles:    true,
        key:    'Shift',
    };

    const options = Object.assign(
        { eventConstructor: 'KeyboardEvent' },
        eventArgs,
    );

    await t
        .dispatchEvent('body', 'keydown', options)
        .click(button2)
        .dispatchEvent('body', 'keyup', options)
        .expect(result.innerText).eql('Test');
});
```

If this approach is not suitable in your use case, feel free to reopen this issue and share appropriate details.
