### ISSUE TITLE
Error while running sample test

### ISSUE THREAD

**Issue by ggrimbert** [DevExpress/testcafe#1844]
### Are you requesting a feature or reporting a bug?
I report a bug

### What is the current behavior?
I try to launch the sample test given in https://github.com/DevExpress/testcafe.
I run with chrome and firefox but the html opened is displayed as text, not read.

Here is what chrome displayed when opened.
![image](https://user-images.githubusercontent.com/15869188/31233663-6f92c68e-a9ed-11e7-937c-cee550aa71ac.png)

I have nothing in logs

### What is the expected behavior?
The HTML should be interpreted

### How would you reproduce the current behavior (if this is a bug)?
I just followed getting started https://github.com/DevExpress/testcafe

### Specify your

* operating system: Ubuntu 16.04
* testcafe version: 0.17.2
* node.js version: 6.11.3
* chrome version : 61.0.3163.100 (official release) (64bits)

**Comment by AndreyBelym** [comment]
Hello @ggrimbert, could you please try the latest TestCafe alpha? You can install it with `npm i testcafe@alpha`.

**Comment by ggrimbert** [comment]
Same thing,

I tried to launch tests with following commands : 
```
testcafe 'chrome --user-data-dir=/tmp/temp-chrome-profile --auto-open-devtools-for-tabs --allow-javascript' test1.ts --proxy 192.168.0.254:80

testcafe chrome test1.ts
```

In these examples it's .ts, but I tried with .js and got the same results.

**Comment by AndreyBelym** [comment]
Do you have some proxy? If so, could you disable it and try to run tests without it? If you need your proxy to access the Internet, you can install `http-server` (`npm i -g http-server`), run it from an another terminal window (just `http-server`), disable proxy and use the following test:
```
fixture `Simple`. page `localhost:8080`;

test('Test', t => t.wait(3000));
```

**Comment by ggrimbert** [comment]
I do have a proxy...

While using the following command 
```
testcafe 'chrome --user-data-dir=/tmp/temp-chrome-profile --no-proxy-server' test1.ts --proxy 192.168.0.254:80
```

it works ! Thanks for your help
