### ISSUE TITLE
WebSocket sends requests to an original server bypassing the proxy

### ISSUE THREAD

**Issue by Bonuspunkt** [DevExpress/testcafe#1851]
### Are you requesting a feature or reporting a bug?
bug

### What is the current behavior?
testcafe replaces window.location with the original location

### What is the expected behavior?
i can alter it to get a url that uses the proxy

### How would you reproduce the current behavior (if this is a bug)?
```
const { protocol, host } = window.location;
const url = `${protocol.replace(/http/, 'ws')}//${host}/`;
const webSocket = new WebSocket(url);
```
the websocket is be opened _directly_ to the server and not via the testcafe proxy.

### Specify your

* operating system: Windows 10 0.0.0
* testcafe version: testcafe@0.17.2
* node.js version: v8.6.0

**Comment by churkin** [comment]
@miherlosev Are we overriding WebSockets?

**Comment by miherlosev** [comment]
No. This feature in progress.

**Comment by miherlosev** [comment]
There is a [separate issue](https://github.com/DevExpress/testcafe-hammerhead/issues/911) related to the WebSocket support. Currently, this feature is in progress. 
We will publish a new `testcafe` version right after a WebSocket support will be implemented.

**Comment by AlexanderMoskovkin** [comment]
Let's keep the issue opened to be notified about the progress. We'll close this when we implement it in the `testcafe-hammerhead` module and when it is updated in the `testcafe` repository.

**Comment by danielabar** [comment]
Any update on when WebSocket support will be released? I'm running into the same issue.

**Comment by AlexanderMoskovkin** [comment]
Hi @danielabar,

We [fixed](https://github.com/DevExpress/testcafe-hammerhead/pull/1341) it yesterday in our proxy. We are going to release a `testcafe` version with the fix this week

**Comment by AlexanderMoskovkin** [comment]
Published in `testcafe@0.18.4`

**Comment by danielabar** [comment]
I tried the latest version `0.18.4` and it works with websockets. Thanks so much!

**Comment by AlexanderMoskovkin** [comment]
Glad to hear this! You are welcome!
