### ISSUE TITLE
Unable to use js tests directly from testcafe dashboard

### ISSUE THREAD

**Issue by starstuffharvestingstarlight** [DevExpress/testcafe#1855]
### Are you requesting a feature or reporting a bug?

Maybe it's a bug, but it's hard to say. Can't find anything in the documentation about it.

### What is the current behavior?

I have some tests written with typescript which work fine. I also have scripts that were done using the TestCafe UI. I tried copy-pasting the scripts generated by the UI to a `.js` file, but the cli tool says no tests exist:

```shell
Error: No tests to run. Either the test files contain no tests or the filter function is too restrictive.
at Bootstrapper._callee3$ ...node_modules/testcafe/lib/runner/bootstrapper.js:213:35
```

I tried writing a runner (copying the docs example with `createTestCafe()....`) and tried a gulp task as well but no luck. 

### What is the expected behavior?

Expected these recorded tests to run normally as they do via the dashboard, or at least some info on why it can't be done.

### How would you reproduce the current behavior (if this is a bug)?

1. Record a complex interaction via the TestCafe dashboard
2. Copy the source code and save it to a test file `exampleFixture.js`
3. Run it inside testcafe `testcafe firefox exampleFixture.js`

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: N/A

Test code

```js
// exampleFixture.js
"@fixture Example login test";
"@page http://www.example.com/";


"@test"["Login"] = {
    '1.Click link "Log In"': function() {
        act.click(":containsExcludeChildren(Log In)");
    }
};
```

### Specify your

* operating system: `Linux 4.4.0-96-generic #119-Ubuntu SMP x86_64 GNU/Linux`
* testcafe version: `0.17.2`
* node.js version: `v8.4.0`

Any thoughts? Looking at the code exported from the dashboard vs. what test code usually looks like, it might be doable to cross compile or preprocess these, then run them as normal fixtures?

**Comment by AlexanderMoskovkin** [comment]
Hi @starstuffharvestingstarlight,

TestCafe supports both the new API and the legacy syntax (that is generated by the UI). But files with legacy TestCafe syntax should have `.test.js` extension (the UI generates them in this way). 
So to resolve you issue just rename your file to `exampleFixture.test.js`. For now we don't have any docs about it but we're going to make it.

**Comment by starstuffharvestingstarlight** [comment]
Too easy! Thanks so much!

**Comment by AlexanderMoskovkin** [comment]
You're welcome!

**Comment by L-David** [comment]
I think this should be in one place in the docs, as a small note in the FAQ place where you mention this backward compatibility. Maybe the file name should follow the *.test.js. So easy yet spent some time to finally come with this answer.
