### ISSUE TITLE
Window actions do not work with Firefox with user profile if there is running headless process on macOS

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#1856]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
If there is running Headless Firefox process, it will block window actions (closing, resizing, screenshoting) for `firefox:UserProfile` on macOS. 

### Specify your

* operating system: macOS 10.13
* testcafe version: 0.18.0-alpha2

**Comment by AlexanderMoskovkin** [comment]
Is it actual for all browsers (chrome and ff)?

**Comment by AlexanderMoskovkin** [comment]
Is it actual only for ff?

**Comment by AndreyBelym** [comment]
Yep

**Comment by AndreyBelym** [comment]
Closing was failed due hanged headless process.

**Comment by AndreyBelym** [comment]
Duplicate of https://github.com/DevExpress/testcafe/issues/2095
