### ISSUE TITLE
Test hangs if `click` and `eval` are called in a chain under some circumstances

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#1859]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

A test run hangs if all of the following conditions are met:

1) Call some action (`click`) and `eval` **in a chain**;
2) The function in an `eval` command raises a js-error **asynchronously** (via `setTimeout`);
3) Call `getNativeDialogHistory` or `getBrowserConsoleMessages` after `eval`.

If you avoid at least one of this conditions the test finishes succesfully.

### How would you reproduce the current behavior (if this is a bug)?

```js
fixture `Check Unlock Button UI`
    .page `http://example.com`;

test('Test with Debuggers', async t => {
    await t
        .click('body')

        .eval(() => {
            setTimeout(() => {
                throw new Error('my error');
            })
        });

    await t.getNativeDialogHistory();
});
```
Meanwhile the test doesn't hang if you split `click` and `eval` into to separate calls:

```js
await t.click('body');
await t.eval(() => { /*  */ });
```
### Specify your
* testcafe version: 0.17.2

**Comment by AndreyBelym** [comment]
Another variant of the same problem:
```js
import { Selector } from 'testcafe';

fixture `Check Unlock Button UI`
    .page `http://example.com`;

test('Test with Debuggers', async t => {
    t.click(Selector('blabla'), { timeout: 1000 });

    await new Promise(r => setTimeout(r, 500));

    await Selector('body').exists;
});
```

**Comment by rob4629** [comment]
👋🏻 Looks like this issue has been closed without actually fixing... Would you suggest **NOT** chaining `.click`?

**Comment by Farfurix** [comment]
@rob4629 

Hello,

This issue was related to **`eval` chaining**. We updated [our documentation](https://devexpress.github.io/testcafe/documentation/reference/test-api/testcontroller/eval.html):

> Always place `eval` in a separate call.
>
> `eval` returns a promise-wrapped value instead of a local context so you cannot chain other methods of the test controller after `eval`. If you chain `eval` on to other methods of the test controller, their promises don't ever resolve which breaks the execution order.
