### ISSUE TITLE
Simplify Travis CI workflow using conditional builds

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#1864]
### What is the current behavior?
Currently we have some complex functionality provided by build bot, that replaces `.travis.yml` with `.travis-docs.yml` to run documentation tests. 

### What is the expected behavior?
With the new [Conditional Builds](https://docs.travis-ci.com/user/conditional-builds-stages-jobs#Specifying-conditions) we can use Travis built-in functionality to run documentation tests.

**Comment by AlexanderMoskovkin** [comment]
Sounds good!
