### ISSUE TITLE
v0.18.0 regression: RequreJS mismatch error

### ISSUE THREAD

**Issue by hpinkos** [DevExpress/testcafe#1874]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?

The test fails because of a requirejs define module error.  This is what is the error output to the console:
```
Uncaught Error: Mismatched anonymous define() module: function (){return br}
http://requirejs.org/docs/errors.html#mismatch
```

I don't have a good workaround for this because the error causes the page not to load properly, so this is preventing me from updating to the newest TestCafe release.

### What is the expected behavior?

This works fine in v0.17.2

### How would you reproduce the current behavior (if this is a bug)?
Here is my sample test case:

```js
'use strict';
var testcafe = require('testcafe');
var Selector = testcafe.Selector;

var tabs = new Selector('.action-pane-tabs > div > ul > li > a');

fixture('Test')
    .page('https://beta.cesium.com/viewer/018c4eba-675e-49f5-93aa-13c7b7844c99');

test('example', function(tc) {
    return tc
        .expect(tabs.count).eql(3);
});
```

I ran this with the following command:
`testcafe chrome ./specs_e2e/test.js --assertion-timeout 10000`

This error only happens on certain pages of our site.  For example, if you switch the page to `https://beta.cesium.com/signin` the page loads as expected.

### Specify your

* operating system: Windows 10
* testcafe version: 0.18.0
* node.js version: 6.11.2

**Comment by AlexanderMoskovkin** [comment]
@miherlosev, @AndreyBelym please take a look at this asap

**Comment by miherlosev** [comment]
I've reproduced the issue.
On the latest commit of hammerhead(https://github.com/DevExpress/testcafe-hammerhead/commit/9e41e1c500f76b15e79840f77239fcfc091a99c5) the problem does not reproduce.
So, search a problem place in testcafe.

**Comment by AndreyBelym** [comment]
It's introduced in https://github.com/DevExpress/testcafe/commit/7dc8cd4911c5526e23db98a3543da8f18da424b9

**Comment by AndreyBelym** [comment]
Importing `test-run/browser-console-messages.js` into `driver.js` causes the error.

**Comment by hpinkos** [comment]
Thanks for the quick turnaround on this @AlexanderMoskovkin, @AndreyBelym!

**Comment by AlexanderMoskovkin** [comment]
@hpinkos You are always welcome!
