### ISSUE TITLE
Cannot obtain information about the node because the specified selector does not match any node in the DOM tree

### ISSUE THREAD

**Issue by nicolocarpignoli** [DevExpress/testcafe#1878]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

I get an error "Cannot obtain information about the node because the specified selector does not match any node in the DOM tree." but the element is on the DOM as I can see from Chrome Debugger.

### What is the expected behavior?

I want to test an element that appear on the DOM after some action

### How would you reproduce the current behavior (if this is a bug)?
This is my test. I get the error on undoButton element
```
 let voteTwoStar = Selector('.rating-rate-label:not(.active)').withAttribute("rate", "2");
 let undoButton = Selector('.rating-undo-label');
    await t
        .click(voteTwoStar)
        .expect(undoButton.innerText).eql('annulla')`
```
I am using .jsx to render the view of this application.

And this is a screenshot of the page after the click (as you can see the element is now on the DOM).

<img width="1062" alt="schermata 2017-10-13 alle 17 30 02" src="https://user-images.githubusercontent.com/22395670/31553903-3a16dd6a-b03c-11e7-8cba-cd9f1037cc8d.png">

* operating system: Mac OS X 10.13.0
* testcafe version: 0.18.0
* node.js version: 8.6.0

**Comment by AlexanderMoskovkin** [comment]
Hi @nicolocarpignoli,

I've tried to reproduce the problem on the simple example with your markup but it works properly on my side:
```js
import { Selector } from 'testcafe';

fixture('Test')
    .page('https://jsfiddle.net/3r330kbs/1/');

test('example', async function (t) {
    await t.switchToIframe('[name=result]');

    let voteTwoStar = Selector('.rating-rate-label:not(.active)').withAttribute("rate", "2");
    let undoButton = Selector('.rating-undo-label');

    await t
        .click(voteTwoStar)
        .expect(undoButton.innerText).eql('annulla');
});
```

It seems the problem is specific for your page. Could you please provide us with the url of your page or create a simple example where we can reproduce the issue?
Additionally you can add the `debug` command to your test to see the page state during test execution:
```js
await t
        .click(voteTwoStar)
        .debug()
        .expect(undoButton.innerText).eql('annulla')
```

**Comment by nicolocarpignoli** [comment]
Thank you so much for the reply. 
I think the example you used is not a useful one, because on the HTML you have from the beginning the 'undoButton' element. My problem appears to object that are appended to the DOM **after** the loading of the page.

This is my .jsx file:

```[
    this.model && <div model={this.model} options={this.options} sharedCallback={this.sharedCallback}>
        {this.rating && this.rating.map((rate) =>
            <label class={this.hasToHighlightRate(rate) ? 'rating-rate-label active' : 'rating-rate-label'} rate={rate}>
                ★
            </label>
        )}
        {this.hasSendedVote && <label class="rating-undo-label"> annulla </label>}
    </div>,
];
```

As you can see, `<label class="rating-undo-label"> annulla </label>` is appended to the DOM only if `this.hasSendedVote` is `true` (which happens after a click in another element).

The `debug` command doesn't help me, it only shows that before the click the element is not present, and after the click the element doesn't appear because the `expect` get stuck waiting for it.

Obviously the flux of the page works fine without TestCafè and the element appears correctly after the click.

**Comment by AlexanderMoskovkin** [comment]
If you put the `debug` command between `click` and `expect` it should show whether the `annulla` element is appeared after click (without waiting for the `expect` command).

If you create a simple example if would be super helpful (it can be a repository with dependencies, a simple model and your .jsx file). There are several possible reasons of the issue so it would be great to have an example which repeat exactly your page behavior.

**Comment by nicolocarpignoli** [comment]
@AlexanderMoskovkin Hi, I get the error cause. I had authorization data in localStorage (without them, the application get stuck with an API error and 'annulla' button doesn't appear on DOM). It appears that testcafe can't handle such data. It is a known problem? Is there a workaround?

**Comment by AlexanderMoskovkin** [comment]
TestCafe starts each test with clean cookies and storages. Do you perform authorization actions in the start of the test?

**Comment by nicolocarpignoli** [comment]
I perform authorization actions BEFORE the test. So now my question is: is it possible to configure this testcafe behaviour? Can I set to not clean storage before a test, for example?

**Comment by AlexanderMoskovkin** [comment]
Thanks for the clarification.
To make tests independent from each other (it's a best practice for testing) TestCafe always runs any test in a clear environment (with empty storages). So, when the test is just started you are logged out.

TestCafe provides [User Roles](https://devexpress.github.io/testcafe/documentation/test-api/authentication/user-roles.html) to handle this cases. So you can use the following template:

```js
import { Role } from 'testcafe';

const registeredUser = Role('login-page-url', async t => {
    // perform login actions
}, { preserveUrl: true /* if necessary */ });

fixture `Fixture`
    .page `your-page-url`
    .beforeEach(async t => { await t.useRole(registeredUser) });

test('Test1', async t => {
    // your are logged in here already
});
```

In this case TestCafe execute User Role initialization function once for a test run. Then it keeps cookies/storages content and use it for each test.

**Comment by nicolocarpignoli** [comment]
@AlexanderMoskovkin thank you, this is exactly what I was looking for!

**Comment by AlexanderMoskovkin** [comment]
Great! Glad to hear it. You are always welcome.
