### ISSUE TITLE
Uncomment assertion in qunit test after update on MS Edge browser version on Sauce Labs

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#188]
key-press-simulator-shortcuts-test.js
test^ 'press shift+home in input'

**Comment by AlexanderMoskovkin** [comment]
Test is fixed on the latest MSEdge build version. But on Sauce Labs just the 20.10240 version is available now. We have to wait for the update

**Comment by helen-dikareva** [comment]
https://github.com/DevExpress/testcafe/pull/187/files#diff-81b2ac50068bd4a9ca12caedf8146fb8R740

**Comment by inikulin** [comment]
I guess it can be resolved now?

**Comment by AlexanderMoskovkin** [comment]
They have `MS Edge 13.10586` now. I suppose it should be ok for us. I'll check
