### ISSUE TITLE
Improve host connectivity check in restricted network environments 

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#1886]
### Are you requesting a feature or reporting a bug?
Proposal (https://testcafe-discuss.devexpress.com/t/has-anyone-been-able-to-connect-remotes-to-ecs-containers/428)

### What is the current behavior?
TestCafe fails to validate hostname, because it checks a random port for connectivity. In environments with explicitly exposed network ports this check will fail.

### What is the expected behavior?
TestCafe should be able to validate hostname using predefined ports.

### Specify your

* testcafe version: 0.18.0
* node.js version: 8.6.0

**Comment by ClaytonAstrom** [comment]
To clarify the expected a bit:  the user should be able to specify the port that testcafe needs to validate on.  Especially if you have multiple instances on a single ip, you will need to translate the port number.  So 4444 cold be mappend to 32756 on the host, flr example.  This would namely be for AWS setups

**Comment by ClaytonAstrom** [comment]
For anyone coming across this issue, I recommend using [Fargate](https://aws.amazon.com/fargate/).  You can get the IP via "ip a" and [here's a handy guide to grab the ip](https://unix.stackexchange.com/questions/87468/is-there-an-easy-way-to-programmatically-extract-ip-address)

Hostname can be verified in this configuration
