### ISSUE TITLE
Unexpected [Vue Warn] is appeared in the console during testing

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#1895]
### Are you requesting a feature or reporting a bug?

bug (cloned from https://github.com/DevExpress/testcafe-vue-selectors/issues/29)

### What is the current behavior?

The following Vue Error is appeared in the console:
`'[Vue warn]: Property or method "nodeType" is not defined on the instance but referenced during render`

### What is the expected behavior?

There are no errors on the original page.

### How would you reproduce the current behavior (if this is a bug)?

You can reproduce it with the [vue-spa-template](https://github.com/Ranmus/vue-spa-template) project:

Run the application:
```
git clone https://github.com/Ranmus/vue-spa-template.git
cd vue-spa-template
git checkout testcafe-error
yarn
npm run dev
```

Run the following test:
```js
import { Selector } from 'testcafe';

fixture `vue-spa-template`
    .page `http://localhost:8080`;

test(`Check errors`, async t => {
    await t.click(Selector('button').withText('Toggle text'));

    const { error } = await t.getBrowserConsoleMessages();

    await t.expect(error[0]).notOk('Vue Error is appeared on the page');
});
```

I've reproduced it in `testcafe-hammerhead` playground. @LavrovArtem please take a look at this. We should open a separated issue in the `testcafe-hammerhead` repository. Let's keep this issue opened until it's fixed in `hammerhead` and we update the version here.

### Specify your

* testcafe version: 0.18.1

**Comment by Horsetoast** [comment]
When I run testcafe from cli it works as expected. However, I get the same error when I use testcafe recording GUI from the browser + one more error from hammerhead.js "TypeError: e.toString is not a function"

**Comment by MarinaRukavitsyna** [comment]
@Horsetoast 
We provide two TestCafe versions: a paid version with a recorder and an open source version. According to your description, you are using the first version. So, please use the DevExpress Support Center to submit tickets regarding your version (https://www.devexpress.com/Support/Center/Question/Create) as we generally process paid TestCafe issues there to avoid mixing two different versions. The GitHub channel is intended for the open-source version.
As for the issue you encountered, I would like to note that we have fixed a similar problem before. So, please submit a ticket to the DevExpress Support Center and request a hotfix.
 
In addition, I should say that the current paid TestCafe version is maintained. Instead, our team is developing the absolutely new TestCafe version with a recorder based on https://devexpress.github.io/testcafe/ as the current one has many limitations (e.g. there is no way to re-record a test or use conditions) that will be overcome in the new version. 
So, I suggest you take a look at this version instead.
What's more, we provide a beta version of a new TestCafe recorder on demand. If you wish, we can also provide you with this version.
