### ISSUE TITLE
Screenshots are cropped when system DPI is > 100%

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#1896]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Taken screenshot is only a part of a browser window.

### What is the expected behavior?
Screenshot should contain the whole image of a browser window.

### How would you reproduce the current behavior (if this is a bug)?
Set DPI > 100% in Windows Display Settings

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Windows 10
* testcafe version: 0.18.1
* node.js version: 8.6.0

**Comment by AlexanderMoskovkin** [comment]
Fixed in `0.18.2`
