### ISSUE TITLE
Uncaught SecurityError: Blocked a frame with origin "xxx" from accessing a cross-origin frame

### ISSUE THREAD

**Issue by hang-ren** [DevExpress/testcafe#1898]
### Are you requesting a feature or reporting a bug?

A bug

### What is the current behavior?

When I try to run my case with testcafe, it will return the error message that "Uncaught SecurityError: Blocked a frame with origin "xxx" from accessing a cross-origin frame"
And it works fine if I run it manually.

### What is the expected behavior?

Run pass.

### How would you reproduce the current behavior (if this is a bug)?

Just run my case.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

http://3d.shejijia.com/?brand=ezhome

Test code

2 Files I used to save the input, just importing them will be ok, I will attach them later.

1 File is test script:

```
import { Selector } from 'testcafe';
import LoginCSS from '../modules/3DLogin';

const loginCss = new LoginCSS();
//const closeBtn = Selector('a[id="closemsgboxbtn"]');
const closeW = Selector('img[class="closewelcome"]');
const d3frame = Selector('iframe[id="3DiFrame"]');
const file = Selector('svg[data-path="plugin/toolbar/res/ImgToolBar/file.svg"]');
const openfile = Selector('li[data-toolbar-path="toolBar_file/toolBar_load"]');
const assetid = Selector('div[data-assetid="15cb1320-3eb3-4f8d-9cff-2c17ec1ef9eb"]');
const render = Selector('svg[data-path="plugin/toolbar/res/ImgToolBar/render.svg"]');
const render_view = Selector('#floorplannerToolbar > div:nth-child(1) > ul > li[data-toolbar-path="toolBar_snapshot_render"] > ul > li[data-toolbar-path="toolBar_snapshot_render/toolBar_view_render_results"]');
const panoramalist = Selector('#productswindown > div.windowcontent > div > div.menusbar.noprint > ul > li.panorama');
const indicatorContainer = Selector('#productlistItem > div.design_render_list.ps-container.ps-theme-default > div.contentscontainer > div > div > div:nth-child(2) > div > div.indicatorContainer');
const edittag = Selector('#productlistItem > div.design_render_list > div > div > div.detail_footer.footer_edit_bar > div > span.footeritem.renderops > div > ul > li.edittagbtn');

fixture `render`
   .page `http://3d.shejijia.com/?brand=ezhome`
   .beforeEach( async t => {
        await loginCss.login();
    });

test('render', async t => {
   await t
       .wait(4000)
	   .click(file)
       .wait(4000)
       .click(openfile)
       .wait(5000)
       .click(assetid)
       .wait(5000)
       .click(render)
       .wait(4000)
       .click(render_view)
       .wait(4000)
       .click(panoramalist)
       .wait(4000)
       .click(indicatorContainer)
       .wait(4000)
       .click(edittag)
       .wait(4000)
});

```

### Specify your

* operating system: Windows 7
* testcafe version: 0.17.0-alpha1
* node.js version:v6.11.0

**Comment by hang-ren** [comment]
``
import { t  } from 'testcafe';

var logindata = require('../data/3Dlogin.js');

export default class LoginCSS {
    constructor () {
	//	this.logina = logindata.logina;
		this.loginpage = logindata.loginpage;
		this.usernameInput = logindata.usernameInput;
		this.pwdInput  = logindata.pwdInput;
		this.loginBtn  = logindata.loginBtn;
		this.loginLink = logindata.loginLink;	
		this.tologin  = logindata.tologin;
		this.closeW = logindata.closeW;		
    }
	
	async login () {
        await t
		.maximizeWindow()
		.wait(5000)
		.click(this.tologin)
		.wait(2000)
		.switchToIframe( this.loginpage )
		.wait(2000)
		.typeText(this.usernameInput,logindata.usname)  
		.wait(2000)
		.typeText(this.pwdInput, logindata.pwd)
		.wait(2000)
		.click(this.loginBtn)		
		.wait(4000)
		.switchToMainWindow()
		.wait(4000)
		.click(this.closeW)
		.wait(4000)
    }
}
``

**Comment by hang-ren** [comment]
File ../data/3Dlogin.js --->


``js

import { Selector } from 'testcafe';

var usname = "tester";
var pwd = "123456";
//var logina = Selector('a[class="loginpp"]');
var loginpage = Selector('iframe[id="loginFrame"]');
var usernameInput = Selector('input[placeholder="手机/邮箱/用户名"]');
var pwdInput = Selector('input[placeholder="密码"]');
var loginBtn = Selector('a[class="sso-submit"]');
var tologin = Selector('button[title="马上登录"]');
var closeW = Selector('img[class="closewelcome"]');



exports.usname = usname;
exports.pwd = pwd;
//exports.logina = logina;
exports.loginpage = loginpage;
exports.usernameInput = usernameInput;
exports.pwdInput = pwdInput;
exports.loginBtn = loginBtn;
exports.tologin = tologin;
exports.closeW = closeW;

``

**Comment by churkin** [comment]
Hi @hang-ren,
I've reproduced the problem with v0.17.0-alpha1 but it works fine with the latest v0.18.1. 
Please try to update your TestCafe version and let me know if this solves the problem.

**Comment by hang-ren** [comment]
Thanks @churkin , but how to just update, not re-install?

**Comment by churkin** [comment]
It does not matter, just use 
`npm -g install testcafe`

**Comment by hang-ren** [comment]
ok, thanks. So I close it.
