### ISSUE TITLE
Unable to test Xaf.Mobile application without a device simulator

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe#1901]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
The Xaf Mobile Application crashes in the TestCafe environment when it has been started without simulator. But when it has been started in the simulator page, tests work properly.

### What is the expected behavior?
The application must be started in the TestCafe environment without errors.

### How would you reproduce the current behavior (if this is a bug)?
Try to run any test for the following page with enabled Developer tools. A "The 'dxLayout' template with the 'slideout' name is not found. Make sure the case is correct in the specified view name and the template fits the current context." exception will be thrown. 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
Without simulator: http://xafbuilder2/MainDemo.Mobile/Static/17.2.0.0/player.html
With simulator: http://xafbuilder2/MainDemo.Mobile

**Comment by miherlosev** [comment]
After discussing with issue's author in private we decide to close it.
