### ISSUE TITLE
The exception block tests --Uncaught (in promise) failed to preload product meta

### ISSUE THREAD

**Issue by hang-ren** [DevExpress/testcafe#1904]
### Are you requesting a feature or reporting a bug?

A bug

### What is the current behavior?

The exception block the test continue.

### What is the expected behavior?

Go on running.

### How would you reproduce the current behavior (if this is a bug)?

Just run my case.
I could also open the page manually, but break if using testcafe(automation).

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
http://ezhome-alpha-3d.shejijia.com/?brand=ezhome&assetId=ecd6dc0a-6a64-459a-9c3c-24431d9a09b9
Test code

```
import { Selector } from 'testcafe';
import exportDWGFunc from '../general/exportdwg';

const exportDWGFunction = new exportDWGFunc();

fixture `Check Export DWG Service`
    .page `http://ezhome-alpha-3d.shejijia.com/?brand=ezhome`

test
    .page `http://ezhome-alpha-3d.shejijia.com/?brand=ezhome&assetId=ecd6dc0a-6a64-459a-9c3c-24431d9a09b9`
    ('export_dwg_design_1', async t => {
    /* Test Check Export DWG Service */
    await exportDWGFunction.export();

});
```
import:'../general/exportdwg'

```
import { t } from 'testcafe';
import { Selector } from 'testcafe';

const file = Selector('#floorplannerToolbar > div:nth-child(1) > ul > li[data-toolbar-path="toolBar_file"]');
const liveHint = Selector('div.msg>p');
const exportDWG = Selector('#floorplannerToolbar > div:nth-child(1) > ul > li[data-toolbar-path="toolBar_file"] > ul > li[data-toolbar-path="toolBar_file/toolBar_export_dwg"]');
const exportButton = Selector('#exportdwgdone');
const continueBtn = Selector('button.btn_continuebtn');
const closeWelcomeImg = Selector('img.closewelcome');

export default class exportDWGFunc {
	
	async export () {
        await t
            .maximizeWindow()
            .click(continueBtn)
            .wait(2000)
            //.expect(liveHint.innerText).contains('加载成功', 'Failed to load design.', { timeout: 30000 })
            .wait(30000)
            .hover(file)
            .wait(2000)
            .click(exportDWG)
            .click(exportButton)
            .wait(2000)
            .expect(liveHint.innerText).contains('成功导出DWG文件', 'Failed to export DWG.', { timeout: 30000 })
    }
}
```

### Specify your

* operating system: Window 7
* testcafe version:0.18.1
* node.js version:6.11.4

**Comment by helen-dikareva** [comment]
There are some JS errors in the console when I try to open the page with this url in Chrome (without TestCafe): `http://ezhome-alpha-3d.shejijia.com/?brand=ezhome&assetId=ecd6dc0a-6a64-459a-9c3c-24431d9a09b9`.

![2017-10-23_1425](https://user-images.githubusercontent.com/12034551/31886662-f3ddef86-b7fd-11e7-8aaa-9cb745b57392.png)

To skip failure on throwing JS errors during test running, you can use [`--skip-js-errors`](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors) flag in the Command Line Interface or skipJsErrors options in [`runner.run()`](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#run) method in the Programming Interface.

**Comment by hang-ren** [comment]
Thanks @helen-dikareva , it works fine as you mentioned.
