### ISSUE TITLE
Disable password bubble in Chrome

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#1913]
### Are you requesting a feature or reporting a bug?
Feature (https://testcafe-discuss.devexpress.com/t/how-to-disable-password-bubble-in-chrome/523)

### What is the current behavior?
Chrome shows a prompt to save a password when it was typed in a password input.

### What is the expected behavior?
Chrome shouldn't show the password saving prompt.

### Specify your

* operating system: any
* testcafe version: 0.18.1
* node.js version: 8.6.0

**Comment by morph027** [comment]
Hi guys...just stumbled upon this.

Our custom testcafe docker image is still showing the password bubble..

OS: CentOS 7
Chrome: 64.0.3282.119-1
Testcafe: 0.18.6

**Comment by AndreyBelym** [comment]
Hi @morph027, I can't reproduce it, could you please share your Dockerfile and HTML markup?

**Comment by morph027** [comment]
Strange thing is that is working yesterday while I was about to implement the tests into our internal Gitlab and today the bubble showed up (after found a way to disable the bubble in Firefox ;) )

**Dockerfile** (slightly modified ;) )

```
FROM	our-centos-7-base-image-which-already-has-node-and-yarn-and-other-stuff

ADD	google-chrome.repo /etc/yum.repos.d/google-chrome.repo

RUN	yum -y install \
		google-chrome-stable \
		firefox \
		xorg-x11-server-Xvfb \
		fluxbox \
	&& yum -y groupinstall "Fonts" \
	&& yum clean all

RUN 	useradd \
		-m \
		-s /bin/bash \
		-r \
		testcafe

RUN	install -b -m 400 /dev/null /etc/sudoers.d/testcafe

RUN	echo 'Defaults env_keep += "DISPLAY"' > /etc/sudoers.d/testcafe

RUN	echo 'pref("signon.rememberSignons", false);' >> /usr/lib64/firefox/defaults/preferences/all-redhat.js

RUN	npm install -g testcafe
```

There is no `CMD` as Gitlab CI is always starting the containers with `bash` and then executes the given script.

The script does things like this:

```bash
# here is some logic to start our apps (3 of them, backend, api and frontend)
...

Xvfb :1 -screen 0 ${SCREEN_WIDTH:-2560}x${SCREEN_HEIGHT:-1440}x24 >/dev/null 2>&1 &
export DISPLAY=:1.0
sudo -u testcafe -H fluxbox >/dev/null 2>&1 &
mkdir -p screenshots
setfacl -m "u:testcafe:rwx" screenshots
sudo -u testcafe -H yarn "$@"
```

and gets parametes like:

`gui:testcafe:screenshots:chrome` which resolves to `yarn run gui:build:testcafe && testcafe chrome dist/testcafe/dashboard-screenshots.fixture.js --screenshots screenshots/chrome --screenshots-on-fails`

I'm the CI guy and really have no clue about the js code our frontend guys are testing on their machines (and i'm trying to automate) ... this is the test entrypoint, if you need more info, just let me know.

**dist/testcafe/dashboard-screenshots.fixture.js**

```
import { login, PoChartRenderer, PoDashboardNavigation, PoLicense, PoSidebar } from './po';
const sidebar = new PoSidebar();
const windowSizes = {
    small: [599, 800],
    medium: [960, 800],
    large: [1280, 800],
    xlarge: [1920, 1200] // will hang if your monitor doesn't support this resolution!
};
fixture('Dashboard')
    .page(login.targetUrl)
    .beforeEach(async (t) => {
    await login.login();
    await PoLicense.installValidLicense();
    await sidebar.navigateToDashboard();
})
    .afterEach(async (t) => {
    await PoLicense.removeLicense();
});
Object.keys(windowSizes).forEach(windowSize => {
    const width = windowSizes[windowSize][0];
    const height = windowSizes[windowSize][1];
    test(`Window size ${windowSize} (${width}x${height})`, async (t) => {
        const topLevelDashboardNavigation = new PoDashboardNavigation(0);
        const chartRenderer = new PoChartRenderer();
        await t
            .resizeWindow(width, height)
            .click(topLevelDashboardNavigation.tab.nth(1));
        // Make sure charts are loaded
        await chartRenderer.renderedN(3)
            .takeScreenshot(`analytics/${windowSize}-dashboard-overview.png`)
            .click(topLevelDashboardNavigation.clickableMetricTitle.nth(0));
        // Make sure charts are loaded
        await chartRenderer.renderedN(3)
            .takeScreenshot(`analytics/${windowSize}-dashboard-overview-interfaces.png`)
            .click(topLevelDashboardNavigation.tab.nth(3));
        // Make sure charts are loaded
        await chartRenderer.renderedN(6)
            .takeScreenshot(`analytics/${windowSize}-dashboard-system.png`);
    });
});
```

**Comment by morph027** [comment]
![bildschirmfoto vom 2018-02-01 19-10-50](https://user-images.githubusercontent.com/600106/35695061-ab0de2ea-0783-11e8-916e-c5af2a72e9e2.png)

**Comment by morph027** [comment]
Ok, kind of "fixed" it for now using the headless browsers ;)
