### ISSUE TITLE
Custom filter for Selector

### ISSUE THREAD

**Issue by kirovboris** [DevExpress/testcafe#1919]
### Are you requesting a feature or reporting a bug?

feature

### What is the current behavior?

We can filter elements by `.filter()` method. In complicated cases it looks like:

```js
import { filterFn } from 'my-lib';

const el = Selector('.el').filter(filterFn);
```

### What is the expected behavior?

For plugins it would be useful to create custom filter function like `.addCustomMethods`, e.g.

```js
/*my-lib*/

export default Selector(...).addCustomFilter({
    customFilter: (nodes, ...args) => {
        function filterFn() {
            ...
        }

        return filterFn(nodes, ...args);
    }
});

/*test*/
import CustomSelector from 'my-lib';

const el = CustomSelector('El').customFilter('...');

```
Related issues:
https://github.com/DevExpress/testcafe-react-selectors/issues/14
https://github.com/DevExpress/testcafe-react-selectors/issues/51

### Specify your

* operating system: any
* testcafe version: 0.18.2
* node.js version: any supported

/cc @DevExpress/testcafe

**Comment by inikulin** [comment]
Please don't. It will kill any opportunity for selector API extensions from our side, since it may conflict with filters introduced by users.

**Comment by kirovboris** [comment]
Yep, but we've already made it with `.addCustomMethods`. What's difference?

**Comment by inikulin** [comment]
Hmm, I completely forgot about it. And now looking at the provided code snippet I realise that you should explicitly create new selector, so it will not pollute all selectors. I guess it's fine then. However, I think we still need to rethink this for `v1.0.0`, e.g. it would be nice to have a way to create extended selector without calling it and make all these custom stuff propagate throughout selector chain.

**Comment by AlexanderMoskovkin** [comment]
Agree. I'm preparing a list of things we should think about before v1.0.0. This idea will be there
