### ISSUE TITLE
Redirect breaks the test

### ISSUE THREAD

**Issue by jamesryanbell** [DevExpress/testcafe#1920]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Running the test the form is triggered, fields completed and submitted correctly but when the form is submitted and the user is redirected to the thank you page the testing framework gets stuck.

The testing software appears to lose it's session, for example the URL on the initial page is as follows: http://127.0.0.1:60566/By5BzTl0Z/https://example.co.uk/ but after the redirect happens on the form completion the unique ID is removed from the URL e.g. http://192.168.12.101:60566/thank-you

### What is the expected behavior?
The redirect would happen and I would be able to assert the form is completed either by the URL or a specific selector

### How would you reproduce the current behavior (if this is a bug)?
This happens every time I run the test

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: I can't share that publicly

Test code

```js
test('Form test', async t => {

	await t
	.click('a#quote')

	await Selector('form');

	await t
	.typeText('input[name="first_name"]', testData.first_name, {replace: true})
	.typeText('input[name="last_name"]', testData.last_name, {replace: true})
	.typeText('input[name="email"]', testData.email, {replace: true})
	.typeText('input[name="phone"]', testData.phone, {replace: true})
	.typeText('input[name="address1"]', testData.address1, {replace: true})
	.typeText('input[name="postcode"]', testData.postcode, {replace: true})
	.typeText('textarea[name="comments"]', testData.comments, {replace: true})
	.click('input[name="acceptance_privacy_policy_terms"]', {replace: true})
	.click('input[type="submit"]')

	//.expect(getPageUrl()).contains('/thank-you', { timeout: 10000 })
	
	.expect(Selector('.container .content .thank-you').exists).ok();

});
```

### Specify your

* operating system: Mac High Sierra version 10.13 (17A365)
* testcafe version: 0.18.1
* node.js version: v8.4.0

**Comment by AlexanderMoskovkin** [comment]
Hi @jamesryanbell,

It seems our proxy processes your page incorrectly. The fastest way to find a reason is provide us with a link to your page privately if it's appropriate for you (I sent you an email last Friday or you can find my email in my GitHub account. For example we can use [ngrok](ngrok.io). It's free for a simple cases.). 

If it's impossible we'll ask you for some debug information.

**Comment by jamesryanbell** [comment]
Hi @AlexanderMoskovkin,

No worries, I replied to you on Friday as unfortunately I can't share the URL with you. If you have a Slack group we can chat in to save emails bouncing around just let me know :)

Thanks

**Comment by AlexanderMoskovkin** [comment]
@jamesryanbell I sent you an invintation.

**Comment by s-a** [comment]
@jamesryanbell I have a similar problem described here https://stackoverflow.com/questions/51026669/testing-oauth-with-testcafe-hangs-at-authclaims-get-route-instead-server-side-r. Have you solved this or are there public informations regarding redirect problems available?
