### ISSUE TITLE
v[0.18.2] Test waits until timeout of 'Waiting an Element to appear' to trigger first click

### ISSUE THREAD

**Issue by anubhavsagar** [DevExpress/testcafe#1924]
### Are you requesting a feature or reporting a bug?
Reporting a bug

### What is the current behavior?
In **v0.18.2**
With each test case run, the first '.click' gets triggered only after the timeout for 'Waiting an Element to appear' expires. 
So each testcase ends up taking more time.

### What is the expected behavior?
With **v0.16.2**, testcafe finds the element on the page earlier and executes the click early

### How would you reproduce the current behavior (if this is a bug)?
Trigger a .click in a testcase and observe the test

#### Provide the test code and the tested page URL (if applicable)

Tested this for an internal test suite.
Will update this later

Tested page URL: 

Test code

```js

```

### Specify your

* operating system:Linux
* testcafe version:0.18.2
* node.js version:8.0.0

**Comment by AlexanderMoskovkin** [comment]
Hi @anubhavsagar,

It likely means that the click target is overlapped by some other element. You can check it on your page without TestCafe in the following way:

```js
const element = document.querySelector('css-selector');
const { x, y, width, height } =  element.getBoundingClientRect();
const center = { x: x + width / 2, y: y + height / 2 }

const elementFromPoint = document.elementFromPoint(center.x, center.y);
```

It seems the `elementFromPoint` is not the target `element` or its child in your case. TestCafe tries to get the target via `document.elementFromPoint`. After the timeout if the element is still overlapped TestCafe clicks on the point on the page where where the target is located.

It's implemented in this way to avoid flaky tests in cases when an element is overlapped for a while by some animation or modal elements. Meanwhile we are going to improve the behavior to make it's clear for a tester why it happens.

**Comment by anubhavsagar** [comment]
Thanks @AlexanderMoskovkin for the explanation! 
This was the case for me. 
I'll fix my page's CSS to prevent this from happening

**Comment by AlexanderMoskovkin** [comment]
Great! Optionally you can decrease a timeout for the Selector to avoid long waiting:

```js
const overlappedSelector = Selector('your-element', { timeout: 1000 });

await t.click(overlappedSelector);
```

**Comment by arenddeboer** [comment]
This also happens on bootstrap vue checkboxes as the native input element has an absolute offset
