### ISSUE TITLE
Embedding testcafe-ui to existing page.

### ISSUE THREAD

**Issue by ismail-codar** [DevExpress/testcafe#1925]
### What is the current behavior?

Currently testcafe opens browser with url option and and runs tests. Test progress is 1 second but all running time 4 second.

### What is the expected behavior?

I hope to live reload for TDD like browsersync. If the testcafe-ui can be embed my page and can be automate given test this feature can be. 

I am a webpack-dev-server user and my development environment has live reload.  If a feature similar to the one below is developed live reload can be work for tests.
#### Desired example usage (in my page)
```js
var testCafeUi = require("testcafe-ui")
var myTest = require("./my-test");
testCafeUi.runTest(myTest);
```

**Comment by ismail-codar** [comment]
https://github.com/bitovi/funcunit have this feature.

**Comment by AlexanderMoskovkin** [comment]
Hi @ismail-codar,

It'll be too hard to implement test running in this way according to the TestCafe architecture. As I understand you'd like to have live reloading tests running. It seems like it the same proposal as in the [#1624 - Keep TestCafe running for rapid development](https://github.com/DevExpress/testcafe/issues/1624) issue. If so we are going to provide a solution for this soon.

**Comment by ismail-codar** [comment]
Yes issue dublication and I am clossing this issue. I decided to use funcunit. It working well.
