### ISSUE TITLE
Running testcafe instance on local host to connect remote workers

### ISSUE THREAD

**Issue by HenningThiemann** [DevExpress/testcafe#1927]
### Are you requesting a feature or reporting a bug?
bug

### What is the current behavior?
I have followed these instructions: https://testcafe-discuss.devexpress.com/t/run-testsuite-on-remote/423 to set up TestCafe to run tests on a remote device.
If I run my testfile via 'testcafe chrome app.js' it is working fine. 
I have adapted the code from the example to run my file (app.js). When I run it via 'node testRemote.js', I get an unexpected error:  

_ReferenceError: fixture is not defined
    at Object.<anonymous> (C:/Projekte/TestCafe/app.js:31:5)
    at Module._compile (module.js:624:30)
    at loader (C:\Projekte\TestCafe\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Projekte\TestCafe\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:/Projekte/TestCafe/testRemote.js:12:15)_

### What is the expected behavior?
Open new server instance on local host, log URL to connect remote browser.

### How would you reproduce the current behavior (if this is a bug)?
Run a standard testfile that includes a fixture.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: WIN10
* testcafe version: latest
* node.js version: 8.7.0

**Comment by AlexanderMoskovkin** [comment]
Hi @HenningThiemann,

Could you please provide us with your `testRemote.js` file content?

**Comment by HenningThiemann** [comment]
Hi @AlexanderMoskovkin, 
my Code is the following:

`const createTestCafe = require("testcafe");
const fs = require("fs");
const path = require("path");
const stream = fs.createWriteStream("output.json");

const filePathSettings = path.join(__dirname, "/settings/", "settings.js");
const settings = require(filePathSettings);

const filePathAppJS = path.join(__dirname, "app.js");
const appJS = require(filePathAppJS);

const testCafe = require('testcafe');

let testcafe = null;
let connection = null;

createTestCafe("localhost", 1337, 1338)
  .then(tc => {
    testcafe = tc;
    console.log("New TestCafe created");

    return testcafe.createBrowserConnection();
  })
  .then(bc => {
    connection = bc;

    console.log(connection.url);

    const runner = testcafe.createRunner();

    return runner
      .src(appJS)
      .screenshots(settings.takenScreenshotFolder + "/", true)
      .browsers(connection)
      .reporter("json", stream)
      .run();
  })
  .then(failedCount => {
    stream.end();
    console.log(failedCount);
    testcafe.close();
  })
  .catch(error => {
    console.log(error);
  });`

**Comment by HenningThiemann** [comment]
Great, thanks for your answer. It is working as expected now!

**Comment by dineshpaduchuri** [comment]
Hi,
When i run testcafe remote test.ts -e, i get a URL where i can run in remote browser in the network. But when i run the url in the remote browser, i am getting Page cannot be displayed.

Do i need to establish connection to the server in my test.ts file to run?

**Comment by AndreyBelym** [comment]
Hi @dineshpaduchuri, let's keep the conversation in #2795.
