### ISSUE TITLE
IE does not work when Test Cafe starts remotely

### ISSUE THREAD

**Issue by Sm1le291** [DevExpress/testcafe#1930]
Hi! We have some problems with running Test Cafe tests on build server. 
How it works:
1. We have our custom console deployment tool that created in TFS build process.
2. In last build step we copy this tool to test server and start using Power Shell remotely using Start-Process command.
3.  Then we start TestCafe using System.Diagnostics.Process class from our tool locally.
4. Here we expect results.xml is filled, but if we run tests in IE we show this message in log: ERROR: **The IE 7.0.0 / Windows 8.1 0.0.0 browser disconnected and empty results.xml file. This problem may appear when a browser hangs or s closed, or due to network issues.** In Chrome all works fine. What cause this problem?

Environment: admin domain account, Windows Server 2012 R2

**Comment by AlexanderMoskovkin** [comment]
Hi @Sm1le291,

I see from the report that you run tests in IE7. TestCafe supports Internet Explorer 9+. The issue can be related to this fact.

**Comment by Sm1le291** [comment]
@AlexanderMoskovkin  I think it's not problem. Windows Server 2012 R2 includes IE 11 by default. When I run tool directly(not using Power Shell) on the same PC report.xml file created and the same browser is used for test running. Maybe browser starts in Compatibility mode
Now I look at the reports. Some of them contains mention of IE 7 - that means Test Cafe started with IE 7, not works properly, but started. 
In my case I have no successful starts and think that problem not in the version.

**Comment by AlexanderMoskovkin** [comment]
When the browser is connected TestCafe waits a service `ping` request from the browser every 2 minutes. The error message you provided means that TestCafe didn't received any requests from the browser for 2 minutes. Please try to run TestCafe in the `debug` mode as described on the [Debugging TestRun](https://github.com/DevExpress/testcafe/wiki/Debugging-TestRun) and provide us with a log.

**Comment by Sm1le291** [comment]
@AlexanderMoskovkin . I am using short command for test run like testcafe ie
This problem reproduced when I try to start tests on WIndows 7, not in 2012 R2
But all works fine with Chrome.
When I set sessionId as my user, I see that console utility creates process with TestCafe and then run IE,  but it does not interact with IE

Steps to reproduce.
1. Create simple console tool that just create testCafe process with some tests
2. Run this tool using Power Shell or PSexec 
3 Two minutes you will show black IE screen and then process finished with error

**Comment by Sm1le291** [comment]
@AlexanderMoskovkin  I resolved problem with IE, now it started in IE 11 mode, bit it did not help.
I resolved many problems with IE
1. Necessary set all zones in Security Settings of IE to one minimal level and turned off Enhanced Security 
Mode
2. Execute this script  
icacls %userprofile%\Appdata\LocalLow /t /setintegritylevel (OI)(CI)L

To set privilege level where IE stored localStorage files

After all these steps tests on some pages works fine.
But some pages don't work properly, and failed with this error
Unable to get property 'hammerhead|storage-wrapper|r1iZlJLyM|cf-front' of undefined or null reference

**Comment by AlexanderMoskovkin** [comment]
@Sm1le291, Thanks for the details. Do I understand right you don't have an issue with a `disconnect` error now?

Meanwhile we're investigating the `Unable to get property` issue.

**Comment by AlexanderMoskovkin** [comment]
> But some pages don't work properly, and failed with this error
Unable to get property 'hammerhead|storage-wrapper|r1iZlJLyM|cf-front' of undefined or null reference

@Sm1le291 Is it possible to share your page with us to check the issue on our side? If it's impossible we need some additional info to find the reason of the problem.

Could you please add a [debug](https://devexpress.github.io/testcafe/documentation/test-api/debugging.html#client-side-debugging) action into the faied test, open dev tools when the test is paused and execute the following code in the command line: `JSON.stringify(localStorage)`. Then do the same on the original page (without TestCafe). Provide us with the results.

Meanwhile, could you please contact me via email (you can find it in my profile). With a direct connection we'll be able to find the reason faster.

**Comment by AlexanderMoskovkin** [comment]
After some investigation we found the reason of the issue. IE was run with the disabled `DOM Storage` option. It turns off `localStorage` and `sessionStorage` support in the browser. TestCafe use them for its service purposes. 
To fix the issue it necessary to enable the `DOM Storage` option. It can be done manually or by setting the windows registry field `Computer\HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main\DOMStorage` to 1.

**Comment by guptaakhil** [comment]
How can we enable this option if want to run our scripts in cloud. As per above  converstation this is setting only with local system.

**Comment by MarinaRukavitsyna** [comment]
@guptaakhil 
From what I gather, you are talking about browserstack. If so, I did not find a public API to change browser settings on the Internet. I suggest you contact the browserstack support team regarding this.

**Comment by guptaakhil** [comment]
@MarinaRukavitsyna : have asked the same question. they are not able to make it possible in testcafe as it require to set the flag in Registry. 

please do let me know if you have any other input for this.
