### ISSUE TITLE
Mistake in documentation

### ISSUE THREAD

**Issue by IhostVlad** [DevExpress/testcafe#1931]
TL;DR: `path` part is forgotten in API reference

In documentation about runner class, located at https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#specifying-the-path-to-the-browser-executable , there some small mistake.
Actually, to use `Specifying the Path to the Browser Executable`, string should be like this: `runner.browsers('path:C:\\Program Files\\Internet Explorer\\iexplore.exe');`
Prefix `path:` is mandatory in string representation, instead, executable will not be found

**Comment by AlexanderMoskovkin** [comment]
Hi @IhostVlad,

Thanks for the reports, we'll fix this.
