### ISSUE TITLE
Global Start URL Option

### ISSUE THREAD

**Issue by bdwain** [DevExpress/testcafe#1932]
### Are you requesting a feature or reporting a bug?
Request a feature

### What is the current behavior?
Start Urls must be specified on fixtures or tests

### What is the requested behavior?
It would be nice if I could set a global start url, instead of doing it for every fixture.

My app is a single page app, so for all tests, my start url is just localhost:PORT, and then I just navigate to the page I am testing with my app. It would be nice to only specify the start url in one spot on either the cmd line or the test runner (if using the node api).

I think it could be the lowest priority, so it would be overridden by a fixture.page call, which would then be overridden by test.page

**Comment by AlexanderMoskovkin** [comment]
Hi @bdwain,

I feel it rather relates to test settings than to test run settings. I suppose it's a nice way to use a `config` file with `baseUrl` in this case as proposed in the [forum discussion](https://testcafe-discuss.devexpress.com/t/passing-url-or-environment-details-as-parameter-or-arguments-or-through-config-file/233/2?u=amoskovkin).

**Comment by bdwain** [comment]
Yea i was doing something similar

```js
import {getUrl} from './helpers';
fixture `Getting Started`
    .page(getUrl());
```

It just seemed like a global option would reduce the repetition since I have to say `.page(getUrl())` in every file.

**Comment by bdwain** [comment]
any chance this will be considered? I really think it will reduce repetition for tests of single page apps. E2E's will typically always just point to the root location (e.g. localhost:4567) and navigate from there using the app itself. It seems like a waste to have to specify it every time. I would even argue that the location of the app itself is a test-run setting, since you might say run it locally (localhost:1234), or hit my preprod environment (preprod.foo.com), or my prod environment (prod.foo.com). Either way that is almost always global for the test run, and not differing by fixture or file.

**Comment by bdwain** [comment]
I could make a PR to do it if it would be considered.

**Comment by AlexanderMoskovkin** [comment]
Hi @bdwain, thanks for your offer to help. I think we'll discuss in a near future changes in a way how you can setup settings for the whole test run, and we'll consider the url options too. We'll notify you once we have any news

**Comment by bdwain** [comment]
sounds good!

**Comment by stalniy** [comment]
any news?

**Comment by AndreyBelym** [comment]
Hi @stalniy, there is no such option yet, but you can use [this approach](https://github.com/DevExpress/testcafe/issues/1932#issuecomment-343050809).

**Comment by mwagz** [comment]
To elaborate on [this](https://github.com/DevExpress/testcafe/issues/1932#issuecomment-343050809) a bit, this was my solution:

```typescript
// ./testcafe.conf.ts|js
const config = {
  // Replace localhost:4200 with your baseUrl
  baseUrl: 'localhost:4200'
};

export { config };
```

```typescript
// ./helpers/url.helper.ts|js
import { config } from '../testcafe.conf';

function urlFor(route) {
  return `${config.baseUrl}/${route}`;
}

export { urlFor };
```

```typescript
// ./src/dashboard.e2e-spec.ts|js
import { urlFor } from '../helpers/url.helper';

fixture('dashboard').page(urlFor('dashboard'));

// ...
````

I'm running my tests in an Angular environment, so please adjust accordingly.

**Comment by AlexSkorkin** [comment]
Thank you for sharing your solution with us. We will take it into account when implementing this option.

**Comment by miherlosev** [comment]
One more request from https://isc.devexpress.com/Thread/WorkplaceDetails/T746291

> My application has multiple environments/deployments with different URLs: development, staging, production.
Is there a way I can automatically run tests against multiple environments?

**Comment by Dema** [comment]
It's interesting how such a base feature is not being considered important.

**Comment by Ogurecher** [comment]
Another request from the Support Center: [Possibility to feed the URL of the page under test from the console](https://supportcenter.devexpress.com/ticket/details/t939304/possibility-to-feed-the-url-of-the-page-under-test-from-the-console)

> Is it possible to pass the test env in the console when running the test command and not from the file?

> Example:
testcafe chrome ./ URL: "https://ourpageundertest.com/"

**Comment by Dmitry-Ostashev** [comment]
One more request from https://supportcenter.devexpress.com/internal/ticket/details/T947417

> Changing the url of all fixtures at directory level before running a test

**Comment by DRiewaldt** [comment]
Has anything been done besides the mess they outline for baseURL with different environments? Cypress handles this with easy, just create configs for each env and just run that config file when launching cypress.

That made it easy and fast to switch from creating a test on stage to running it against production. 

Right now I have to go manually update my code with what env i'm on which isn't a good solution, or rather is a lack of a solution. All the ways i've seen are convoluted, not explained great, and don't show how to tell it what env i'm in. 

The best solution that I don't know how to use is here: https://stackoverflow.com/questions/62626778/testcafe-in-azure-devops-with-specific-url

However, they don't explain how they are passing in what env to use when the test is run. 

I think most QA will need to be able to run this against at minimum two envs, far more likely at least three envs to account for local development. I shouldn't need to write a single method to make this work, it should just let me pass the config file i want in when running it or allow me to pass in the env so it knows which base url to use.

**Comment by stalniy** [comment]
I think the feature is not important because there are good workarounds. Just use `dotenv` or similar package and use `process.env.TC_BASE_URL` everywhere in the code. 

The config part looks like this:

```ts
import dotenv from “dotenv”;

dotenv.load({ path: `.env.${process.env.TC_ENV}` })

console.log(process.env.TC_BASE_URL)
```

Run it like this:
```
TC_ENV=production testcafe
```

And `.env.production`:

```
TC_BASE_URL=https://production.com
```

You will need a separate .env for every env (e.g., `.env.staging`)

**Comment by DRiewaldt** [comment]
Having a work around is the worst way to develop software. This should have it built in is the point, and I'm not able to use a third party package currently.

I need a way to do this built into TestCafe just like Cypress or other similar testing suits that understand development doesn't happen on one env.

**Comment by stalniy** [comment]
According to the latest docs there are `userVariables` which can be used to implement env specific vars: https://testcafe.io/documentation/402638/reference/configuration-file#uservariables

That means you may create separate testcafe.conf.js files with different userVariwbles

**Comment by helen-dikareva** [comment]
ready for tech writer's review
