### ISSUE TITLE
Invoking and testing browser history actions (back / forward)

### ISSUE THREAD

**Issue by denisw** [DevExpress/testcafe#1936]
We have an app that contains a wizard with complex browser history interaction (pushing and restoring form state to/from browser history entries using the History API). We tried to test this behavior with Testcafe, but are not sure if it is possible at all. We tried things like:

```javascript
const goBack = ClientFunction(() => window.history.back())
await goBack();
```

But this results in either no change or the test restarting. Is this a fundamental limitation of the proxy approach Testcafe takes? Or is there a way to make this work?

**Comment by helen-dikareva** [comment]
This functionality is fully supported in TestCafe and works properly on my side. You can try the following test:
```js
import { ClientFunction } from 'testcafe';

const getLocation = ClientFunction(() => window.location.href);

 fixture `fixture`
    .page `http://google.com`;

 test('test history navigation', async t => {
    await t
        .expect(getLocation()).contains('google')
        .navigateTo('http://js.devexpress.com/')
        .expect(getLocation()).contains('/js.devexpress');

    const goBack = ClientFunction(() => window.history.back());
    await goBack();

    await t.expect(getLocation()).contains('google');
});
```
It seems that the problem may be related to your page or test scenario. Could you please provide us with a link to your page if it's possible or create a simple example to reproduce the problem? Also please provide us with full code of your test.
In addition, specify the TestCafe version and the browser where the problem occurs.

**Comment by denisw** [comment]
Yes, that works! Seems we did something wrong before. Thank you for pointing us in the right direction!
