### ISSUE TITLE
Can instrumentation be disabled?

### ISSUE THREAD

**Issue by danielabar** [DevExpress/testcafe#1944]
Is it possible to disable instrumentation or is this a fundamental feature of the test framework? Or to send it babel options? Thought maybe it's only required for js errors, but even when running with `--skip-js-errors`, instrumentation still applies.

Reason for asking, was getting this error trying to load one of my app pages in a test:

```
system.js:5 Uncaught (in promise) Error: (SystemJS) Unexpected token (
  SyntaxError: Unexpected token (
      at eval (<anonymous>)
      at http://my.ip:58656/hammerhead.js:1:21318
      at <anonymous>
```

Following [these instructions](https://github.com/DevExpress/testcafe/issues/930#issuecomment-320766614) to run hammerhead playground, was able to track down cause of this error. App has code written in ES2015, for example:

```
let originalThings = [];
let transformedThings = []
mythings.forEach(myThing =>
  transformedThings.push({
    foo: myThing + 'some transformation...'
  })
);
```

This app only targets modern Chrome and Firefox, so it uses [babel-preset-env](https://github.com/babel/babel/tree/master/experimental/babel-preset-env):

```
presets: [[ 'env', {
      modules: "systemjs",
      targets: {
        browsers: ["last 10 chrome versions", "last 5 firefox versions"]
      },
      ... other settings
    ]
```

So the code delivered to browser is not transpiled all the way down to ES5, the arrow functions remain. Then hammerhead instrumentation processes it and generates invalid code something like this:

```
var originalThings = [];
var transformedThings = []
mythings.forEach( __get$Loc(myThing) => transformedThings.push({
    foo: myThing + 'some transformation blab blah...'
  })
);
```

A workaround is to have another set of babel options that will transpile to ES5 and use that for the tests, but not ideal because then the tests are running a different version of the code than what's delivered to production.

**Comment by AndreyBelym** [comment]
Hello @danielabar! 

Unfortunately, disabling instrumentation is not an option, because it is used to emulate user actions. I think we need some time to implement support of new ES201x syntax features in Hammerhead's script processing.

The simplest workaround is to remove `targets` property from the preset config. In that case `babel-preset-env` will enable all available transformations and will transpile code to ES5 supported by TestCafe.

**Comment by danielabar** [comment]
Removing the `targets` property worked, thanks for your help.
