### ISSUE TITLE
ReDoS vulnerability parsing Set-Cookie

### ISSUE THREAD

**Issue by ddimitrioglo** [DevExpress/testcafe#1949]
### Are you requesting a feature or reporting a bug?
This is an enhancements.

### What is the current behavior?
During npm install, receiving following warning:

> tough-cookie@0.9.14: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

### What is the expected behavior?
Could you please upgrade the module, to escape the vulnerability.

### How would you reproduce the current behavior (if this is a bug)?
just run `npm install`

### Specify your

* operating system: macOS High Sierra (10.13.1)
* testcafe version: v0.18.1
* node.js version: v6.11.4

**Comment by AlexanderMoskovkin** [comment]
Hi Dmitri,

We have the `tough-cookie` module as a dependency in the `testcafe-hammerhead` module but we've fixed this about two months ago in the https://github.com/DevExpress/testcafe-hammerhead/commit/fe7f47d875d0b738b6a0b38e410e253c69669ea8 commit.
I see you have the `"testcafe": "^13.1.1"` dependency in your repository. Note that this version relates to the paid TestCafe version (see [details](https://devexpress.github.io/testcafe/faq/#what-is-the-difference-between-a-paid-and-an-open-source-testcafe-version)). Could you please try update TestCafe to the latest version (`0.18.4`)?

**Comment by ddimitrioglo** [comment]
Thank you @AlexanderMoskovkin! it helped!
