### ISSUE TITLE
Weird behaviour when typing into Slate Editor field in Chrome

### ISSUE THREAD

**Issue by tamlyn** [DevExpress/testcafe#1956]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

When using `typeText` into a [Slate](http://slatejs.org) WYSIWYG editor input in Chrome or Safari, the text gets jumbled up.

![screenshot](https://tamlyn.s3.amazonaws.com/Screen%20Shot%202017-11-21%20at%2010.57.12.png)

### What is the expected behavior?

Text should be input normally, like in FIrefox.

### How would you reproduce the current behavior (if this is a bug)?

See this gist https://gist.github.com/tamlyn/08b4be11424f2539d4d5105ceebf3d4d

#### Provide the test code and the tested page URL (if applicable)

See above

### Specify your

* operating system: MacOS 10.11
* testcafe version: 0.18.3
* node.js version: 8.9

**Comment by AndreyBelym** [comment]
Hello @tamlyn!

I reproduced the issue. You can try `paste: true` for typing options as a workaround:
```js
.typeText('div[contenteditable=true]', 'This is some text which does not work', { paste: true })
```

**Comment by benbrandt** [comment]
I'm seeing similar behavior in when using DraftJS. It seems like maybe testcafe is modifying the DOM directly when using typeText, which is then causing React's virtual dom to become out of sync and causing errors to be thrown.

**Comment by AlexanderMoskovkin** [comment]
Hi @benbrandt, thanks for the info. Have you tried the approach with the `paste: true` option? Does it work in your case?

**Comment by benbrandt** [comment]
`paste: true` makes it so that it all gets input in the correct order. But then Draft starts throwing errors I think related to this: https://draftjs.org/docs/advanced-topics-issues-and-pitfalls.html#browser-plugins-extensions

**Comment by MichaReiser** [comment]
This issue might also be due to race conditions in your react code. 
See the [draft.js documentation](https://draftjs.org/docs/advanced-topics-editorstate-race-conditions.html#content) for details.
