### ISSUE TITLE
getStyleProperty("overflow") does not work for document.documentElement in Chrome browser

### ISSUE THREAD

**Issue by pgrivachev** [DevExpress/testcafe#1971]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

AssertionError: expected undefined to deeply equal 'hidden' 
in Chrome

### What is the expected behavior?

test passed

### How would you reproduce the current behavior (if this is a bug)?

Create an empty html page with style on html tag:
`style="overflow:hidden"`

Test that html style contains "overflow:hidden":

#### Provide the test code and the tested page URL (if applicable)

Tested page:
```html
<!DOCTYPE html>
<html style="overflow:hidden;">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>

</body>
</html>
```
Test code

```js
test('Test overflow', async t => {
    var documentElement = Selector(() => document.documentElement);
    await t
        .expect(documentElement.getStyleProperty("overflow")).eql("hidden");
});
```

### Specify your

* operating system: Windows 8.1
* testcafe version: 0.17.0
* node.js version: 6.11.2

**Comment by miherlosev** [comment]
Hi @pgrivachev.

It's not a bug. 
According to the [documentation](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/dom-node-state.html), `getStyleProperty` returns the computed value of the CSS property. For your markup, the computed properties are `overflow-x` and `overflow-y`.
![image](https://user-images.githubusercontent.com/4133518/39761260-51ced510-52e0-11e8-9a23-0582cd29b83e.png)

So, you need to change your assertion code to the following one:
```js
.expect(documentElement.getStyleProperty("overflow-x")).eql("hidden");
```
and it will pass.
