### ISSUE TITLE
[Documentation]: Navigation styling is broken

### ISSUE THREAD

**Issue by wintermute42** [DevExpress/testcafe#1972]
### Are you requesting a feature or reporting a bug?
Seems like a bug

### What is the current behavior?
The main nav on http://devexpress.github.io/testcafe/documentation looks broken and links are not clickable due to overlapping divs on Chrome 62 (Linux)(Official Build)(64-bit) - see screenshot.
![image](https://user-images.githubusercontent.com/10060882/33388997-d52b2094-d531-11e7-9294-9e1c7f2d5fba.png)

### What is the expected behavior?
Should look and work like e.g. in Firefox 57 (Linux) - see screenshot.
![image](https://user-images.githubusercontent.com/10060882/33389064-03a5b9fc-d532-11e7-9689-6124c48b8155.png)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
http://devexpress.github.io/testcafe/documentation/test-api/
Test code

```js

```

### Specify your

* operating system: Ubuntu Linux 16.04.3 64 bit
* testcafe version:
* node.js version:

**Comment by AlexanderMoskovkin** [comment]
Hi @wintermute42,

Thanks for pointing this out. We're working on this.

**Comment by VasilyStrelyaev** [comment]
@wintermute42 You'll be able to try the fix once we update the website (in a couple of days)
