### ISSUE TITLE
Name a screenshots folder by the test name, or add a text file under the folder having the test name

### ISSUE THREAD

**Issue by adrianaisemberg** [DevExpress/testcafe#1975]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
Running several tests and saving screenshots in each results in a list of folders and having no way to correlate between a test and its screenshots folder.

### What is the expected behavior?
Somehow be able to find the relevant screenshots of a test, especially a failed test.

**suggestion:
Place a `test.txt` file in each folder with the test details, such as name, file-name etc.**

### How would you reproduce the current behavior (if this is a bug)?
Write some tests. Take screenshots from each. Run all of them.
Observer the folder structure. Although it is well-structured (date/index/browser), it seems completely random when I want to find my test's screenshots.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by adrianaisemberg** [comment]
Just realized that the report shows the screenshots path:
![image](https://user-images.githubusercontent.com/857478/33495880-fc9e5a8c-d67c-11e7-910a-1a4cbfd9ebc5.png)

**Comment by AndreyBelym** [comment]
Hi @adrianaisemberg, we are in process of designing extensions of screenshoting API, and they will make screenshot paths more flexible. Stay tuned for the next couple of weeks!

Right now, it's possible to use JSON reporter: https://github.com/DevExpress/testcafe-reporter-json to get more structured screenshot information.

**Comment by thireven** [comment]
Do we have any updates on the screenshottng API since it's been a month and a half?

**Comment by AlexanderMoskovkin** [comment]
closed in favor of #2152
