### ISSUE TITLE
[docs] Add how-to guides that illustrate our main concepts

### ISSUE THREAD

**Issue by VasilyStrelyaev** [DevExpress/testcafe#1977]
- [x] How to work with page DOM (Selectors)
- [x] How to interact with client code (Client Functions)
- [x] How to structure your project

**Comment by DIRECTcut** [comment]
'How to structure your project' fixed as part of [best practices article](https://github.com/DevExpress/testcafe/pull/5603/files#diff-9fbc21622da603ea01cab35a7fa64fb5e5a84aada324c586fdb6de9b6513dce4R241)
