### ISSUE TITLE
[Docs] Improve t.navigateTo(url) description, note caveats

### ISSUE THREAD

**Issue by DmitryFillo** [DevExpress/testcafe#1978]
### Are you requesting a feature or reporting a bug?
It's clarification to the docs.

### What is the current behavior?
All actions with targets like `t.click(selector)` waits for selector, but it can confuse `t.navigateTo(url)` usage. Referring to [this post](https://github.com/DevExpress/testcafe/issues/1836#issuecomment-333785784) there are some cases when `t.navigateTo(url)` can fail, e.g. in cases like JS code do ajax request after delay and/or then `document.location.href = newUrl` and server response is slow, etc.

### What is the expected behavior?
It should be noted [there](http://devexpress.github.io/testcafe/documentation/test-api/actions/navigate.html)  that `t.navigateTo(url)` will wait for URL change only in simple cases by some algorithm (wait for immediately XHR, etc). Intuitively seems like "huh, I've read that actions will wait for ... let's do navigate and I think it will wait for URL change somehow anyway". It can lead to very flaky bugs.

### Specify your

* testcafe version: 0.18.4

**Comment by AlexanderMoskovkin** [comment]
Hi @DmitryFillo,

TestCafe should always wait for the page reloading after `t.navigateTo()` is called (at least we didn't meet a case when it doesn't work). Did you meet the case when it works wrong?

In the ticket that you mentioned before I wrote about a case when some side effects (like xhr-requests or page reload) are performed after some timeout after the `click` action.

**Comment by DmitryFillo** [comment]
Hi @AlexanderMoskovkin,

I created repo with examples https://github.com/DmitryFillo/testcafe-navigateto-works-wrong.

In my case server was very slow sometimes, so `t.navigateTo()` fails. I think it's OK behaviour, but it's not clear from docs.

Also I've found another case while preparing example: TestCafe fails if server responds with string only, not HTML: 
> Test fails if server returns only string
ERROR The HeadlessChrome 0.0.0 / Windows 10 0.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.

**Comment by AlexanderMoskovkin** [comment]
Hi @DmitryFillo,

Thanks for you example. TestCafe wait for 15 seconds for a server response after redirect. If it doesn't get response for this time it resumes the test. We did it to avoid unexpected test hangs. As a workaround you can add an assertion after each redirect with a long [timeout](https://devexpress.github.io/testcafe/documentation/test-api/assertions/#optionstimeout). It will check the new page is loaded (by `document.location` or some elements on the page). Meanwhile we'll figure out how we can note this in our docs.


> Also I've found another case while preparing example: TestCafe fails if server responds with string only, not HTML:

@miherlosev @LavrovArtem please take a look at this

**Comment by DmitryFillo** [comment]
Thanks. Suggested workaround is OK, currently I do both assertion for location and delay.
