### ISSUE TITLE
testcafe table raws not use??

### ISSUE THREAD

**Issue by haoshasha** [DevExpress/testcafe#1979]
### Are you requesting a feature or reporting a bug?
![image](https://user-images.githubusercontent.com/30857050/33523858-941d7a6e-d7d6-11e7-9e8c-ccd0f8884a7e.png)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by haoshasha** [comment]
![image](https://user-images.githubusercontent.com/30857050/33523874-f133f1c4-d7d6-11e7-9cbd-1c4765a7cd50.png)

**Comment by MarinaRukavitsyna** [comment]
Hello @haoshasha ,
TestCafe does not support the Selector('..').rows.length` syntax. You can check a list of supported selectors below:
[Selecting Page Elements](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/)

For example:
```javascript
Selector('.jfj-table-body table tr').count
```
