### ISSUE TITLE
The element that matches the specified selector is not visible - But button is visible

### ISSUE THREAD

**Issue by Hack4Life** [DevExpress/testcafe#1988]
### Are you requesting a feature or reporting a bug?
Maybe a bug

### What is the current behavior?
Cannot click a button that is in my site and do not gets manipulated at any time.

In the command line I get the following message shown:
![2017_12_06 - testcafe error message on cmd](https://user-images.githubusercontent.com/11788789/33666788-57f6c1e0-da9b-11e7-82a8-f8f8d7773012.png)

The test breaks after this message:
![2017_12_06 - testcafe waiting for an element to appear](https://user-images.githubusercontent.com/11788789/33666790-58a768b0-da9b-11e7-9173-bd861661cc43.png)

### What is the expected behavior?
Button click should work like on all other pages I use for the tests.

### How would you reproduce the current behavior (if this is a bug)?
It can not be reproduced, since on every other site the .click function works without any problems.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: - 

Test code

```js
const submitOrderBtn = Selector('button[type="submit"].btn-success');
//also tried with this:
//const submitOrderBtn = Selector('#confirmation-submit');
// and this:
//const submitOrderBtn = Selector('button').withText('order now');

const agbBtn = Selector("#conditions_accepted5");
const wiederrufsrechtBtn = Selector("#rescission_accepted6");

fixture `shop a product`
     .page `http://dev.local/checkout`;

test('complete order', async t =>{
     await t
          //some other actions for the process. Alle the stuff below is on the same page:
          .click(paymentSubmitBtn)
	  .click(agbBtn);
     console.log("[DEBUG], Trying to click submit button");
     await t
          .click(paymentSubmitBtn)
	  .click(agbBtn)
          .click(submitOrderBtn)

```

This is what the button looks in the html code:
```html
<button id="confirmation-submit" type="submit" class="btn btn-success pull-right hidden-xs">
     <span class="glyphicon glyphicon-flag"></span>
     order now
</button>
```

### Specify your

* operating system: Windows 10
* testcafe version: 0.8.15
* node.js version: 8.9.0

**Comment by AndreyBelym** [comment]
Hello @Hack4Life!

Unfortunately, it's hard to say something without the full page source code. If you concern about privacy, you can send a link/source through private messages on our forum: https://testcafe-discuss.devexpress.com/ to [me](https://testcafe-discuss.devexpress.com/users/AndreyBelym), [Helen Dikareva](https://testcafe-discuss.devexpress.com/users/helen-dikareva) or [Alexander Moskovkin](https://testcafe-discuss.devexpress.com/users/amoskovkin).

If you can't share your code, could you please try to write minimal reproducible example, please?

TestCafe will consider element visibile if its width or height have a non-zero value. In your case `#confirmation-button` might be an invisible button hidden somewhere in an actual visible element.

Also, you can try to resize browser window using [resizeWindow](https://devexpress.github.io/testcafe/documentation/test-api/actions/resize-window.html) action. It may help if your layout is adaptive or it is a scrolling issue.

**Comment by Hack4Life** [comment]
Thanks for your reply @AndreyBelym! 

Your hint with resizeWindow helped me. I completely overlooked that another submit button is hidden on desktops and only visible on smaller devices. Since the first step in my tests is always `.maximizeWindow()` I have not thought that this could be the problem. 

I will close this issue since it was just me overlooking a html piece of code.

**Comment by Avinger27** [comment]
@Hack4Life Did you maximize the window again, after resizing it? or continued the test execution in the resized window?
