### ISSUE TITLE
Material-UI Popover Bug?

### ISSUE THREAD

**Issue by eliw00d** [DevExpress/testcafe#1989]
I have a test that includes the following selector and action:
```
let popover = ReactSelector('PopoverAnimationDefault').find('div').withText('CLICK ME')
await t.click(popover)
```
When the popover is displayed on-screen, I get the following error in testcafe:

![screen shot 2017-12-06 at 3 48 49 pm](https://user-images.githubusercontent.com/1801127/33688845-9f6fcdb2-daa2-11e7-9506-66eece42fc16.png)

Which seems to point to the following piece of code in material-ui/Popover/Popover.js:
```
    _this.setPlacement = function (scrolling) {
      if (!_this.state.open) {
        return;
      }

      if (!_this.popoverRefs.layer.getLayer()) {
        return;
      }
```

Which makes it seem like `_this.popoverRefs.layer` is undefined?

The site itself works fine and there are no errors related to this popover outside of using testcafe. The rest of the stacktrace when the popover comes up is extremely unhelpful, pointing at comments and even whitespace. 

Any thoughts?

* operating system: macOS Sierra
* testcafe version: 0.18.5
* node.js version: 8.9.1

**Comment by miherlosev** [comment]
Hi @eliw00d 
I've created a simple test for `Material-UI Popover`.
```js
import ReactSelector from 'testcafe-react-selectors';

fixture `Material UI Popover`
    .page('http://www.material-ui.com/#/components/popover');

test('test', async t => {
    const clickMeLinks      = ReactSelector('RouterContext').find('span').withText('CLICK ME');
    const clickMeLinksCount = await clickMeLinks.count;

    for (let i = 0; i < clickMeLinksCount; i++)
        await t.click(clickMeLinks.nth(i));
});	
```
and it works good.

It's a difficult to locate a problem without example.
Could you, please, provide an example on which this issue is reproduced?

**Comment by eliw00d** [comment]
We are trying to isolate the issue to a specific set of code, but it is proving to be extremely difficult. 

The scenario is a Dialog that leads to another Dialog with an AutoComplete. When the test reaches the point where it types into the AutoComplete and the Popover shows up it crashes and burns with the above error.

However, if we open the second Dialog directly and type into the AutoComplete, the test works.

I am not really sure what the issue is, as these errors do not show up in our deployed site, only when we've been trying to implement TestCafe.

**Comment by miherlosev** [comment]
Ok. I get it. I will try to reproduce the problem myself.
Could you please provide:
- `material-ui` module version
- markup and code for the `Dialog that leads to another Dialog with an AutoComplete`

**Comment by eliw00d** [comment]
We are using:

```
"material-ui": "0.19.4"
```

However, I think I may have figured it out. We are using a "fix" for a MUI bug that dispatches a new window event for resizing. It looks like this:

```
    componentDidUpdate() {
        this.resizeFix()
    }

    resizeFix() {
        setTimeout(() => {
            window.dispatchEvent(new Event('resize'))
        })
    }
```

If I remove the calling line the test passes.

**Comment by eliw00d** [comment]
Some more details:
```
Uncaught TypeError: Cannot read property 'getLayer' of null
    at Popover._this.setPlacement (bundle.js:50350)
    at invokeFunc (bundle.js:18647)
    at leadingEdge (bundle.js:18657)
    at debounced (bundle.js:18722)
    at hammerhead.js:formatted:4201
    at dispatchEvent (hammerhead.js:formatted:3990)
    at bundle.js:123994
```
Where hammerhead.js:formatted:3990 is `                                                      , t = e ? S["default"].windowDispatchEvent.apply(this, arguments) : S["default"].dispatchEvent.apply(this, arguments);`
and bundle.js:123994 is `window.dispatchEvent(new Event('resize'));`

**Comment by miherlosev** [comment]
I've created an example based on the `create-react-app` template and Material UI Demos.
You can find it [here](https://github.com/DevExpress/testcafe/files/1555694/my-app.zip).
I was trying to reproduce the issue. But unfortunately, I did not succeed.

Could you please try to modify my example and reproduce the problem?
Also I need some additional information from you: please, tell the version of the browser you are using.

**Comment by eliw00d** [comment]
I will give it a shot.

Google Chrome
Version 63.0.3239.90 (Official Build) beta (64-bit)

**Comment by eliw00d** [comment]
I forgot to update this, but switching to Material UI 1.0.0 solved this problem.
