### ISSUE TITLE
Is it possible to mock HTML5 APIs (like geolocation) ?

### ISSUE THREAD

**Issue by florentpeyrard** [DevExpress/testcafe#1991]
### Are you requesting a feature or reporting a bug?
Asking if something is possible, and maybe requesting a feature.

### What is the current behavior?
I didn't find a way to mock geolocation API.

### What is the expected behavior?
Allow mocking data returned by HTML5 API. This would allow controlling values returned, geolocation accuracy for instance. My application code has a different behavior depending on this data, so tests cases must handle this. If I can't control this data, I never know what the browser will actually return during the tests.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by AndreyBelym** [comment]
Hi @florentpeyrard!

If your page doesn't request location during it is loading, you can write a simple Client Function to mock the location API:
```js
const mockLocationAPI =  ClientFunction(() => {
    navigator.geolocation.getCurrentPosition = success =>  success({ coords: { latitude: 30, longitude: -105, }, timestamp: Date.now() });
});
```

Then you can use it in a test body or in a `beforeEach` section.
```js
test('test', async t => {
    ...
    await mockLocationAPI();
    ...
});
```js
fixture `Fixture`
    .beforeEach(async t => {
        await mockLocationAPI();
    });
```

But, if you need to mock location before a page is completely loaded, you will need to wait for https://github.com/DevExpress/testcafe/issues/1739 to be implemented.

**Comment by florentpeyrard** [comment]
This works like a charm, thanks a lot @AndreyBelym :)
