### ISSUE TITLE
AMP Page Validation fails with testcafe

### ISSUE THREAD

**Issue by harryurban** [DevExpress/testcafe#1993]
### Are you requesting a feature or reporting a bug?
*bug*

### What is the current behavior?
Opening amp pages with the `#development=1 flag` triggers the validation scripts which log success or failure to the console. 
The validation, which is usually successful, fails because of amp vaildation assertions, I assume because of the page being tested is served via the proxy.

### What is the expected behavior?
testing an amp page with the `#development=1` flag should validate during a  testcafe run (if the page is valid, of course)

### How would you reproduce the current behavior (if this is a bug)?
1. open any amp url with your regular browser and watch out in the console log for "AMP validation successful".
2. Access the console output in a testcafe run opening the same url and assert that the info logs contain `AMP validation successful`. it will fail and validation errors will be in the error logs.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

`https://amp.welt.de/amp/politik/deutschland/article167948204/Stossen-an-Grenzen-Kommunen-fordern-Stopp-der-Fluechtlingsverteilung.html#development=1`

Test code

```js
public ampValidationSuccessful: ClientFunction = ClientFunction((): Promise<boolean> => {
        return new Promise((resolve: (value: boolean) => void, reject: (msg: string) => void): void => {
            let interval: number = window.setInterval((): void => {
                let validates = t.getBrowserConsoleMessages().then(out => {
                    return (out.info.join().match(/.*AMP validation successful.*/) !== null);
                });
                if (validates) {
                    window.clearInterval(interval);
                    resolve(true);
                }
            }, 20);
            window.setTimeout((): void => reject('did not find validation message'), 30000)
        });
    });

```

### Specify your

* operating system: `Mac OS X 10.13.1, Chrome: Version 62.0.3202.94 (Offizieller Build) (64-Bit)`
* testcafe version: `"testcafe": "0.18.3"`
* node.js version: `v8.2.1`

**Comment by miherlosev** [comment]
Hi, @harryurban
Thanks for your report.
I've reproduced the problem and created a separate issue in the our web proxy repository - https://github.com/DevExpress/testcafe-hammerhead/issues/1418

**Comment by harryurban** [comment]
did the closed issue above solve our issue?

**Comment by miherlosev** [comment]
>did the closed issue above solve our issue?

@harryurban .
Unfortunately, it is very difficult to fix this problem.
`TestCafe` adds a lot of elements to the tested page: custom scripts, stylesheets, attributes, comments, etc. 
The [AMP site building technology](https://www.ampproject.org/) prohibits using custom scripts and attributes. Also, our proxy handles all content using the `http` protocol (from page to proxy). Also, [AMP](https://www.ampproject.org/) doesn't allow using the `http` schema for media sources.
See the links below:
* https://www.ampproject.org/docs/fundamentals/spec#html-tags 
* https://www.ampproject.org/docs/fundamentals/spec#links 
* https://www.ampproject.org/docs/reference/components/amp-video 

[AMP Validator tool](https://validator.ampproject.org/) uses regular expressions internally to parse html markup. So, there is no good way to hide the `TestCafe` part from it.
