### ISSUE TITLE
Add an option to only display assertion messages when a test fails

### ISSUE THREAD

**Issue by berrutti** [DevExpress/testcafe#1997]
### Are you requesting a feature or reporting a bug?
Requesting a feature

### What is the current behavior?
When a test fails, the console gets the entire output of the error, for instance:
```
 1) AssertionError: expected false to be truthy
      Browser: Chrome 62.0.3202 / Windows 10 0.0.0
       227 ...
       228 ...
       229 ...
       > 230 |          await t.expect(expensesPage.allTableDropdown.exists).ok();
       231 ...
       232 ...
       ...
```

### What is the expected behavior?
When executing testcafé with the option, the console output should display only the message. For instance.
```
 × TC 123456:
   1) AssertionError: 'The Table dropdown should exist'

```
That way, someone who didn't write the test code but is in charge of executing the suit could easily understand in a natural language what is failing at a glance and report it. Instead of getting the line that failed and trying to understand what is the test code doing.

### How would you reproduce the current behavior (if this is a bug)?
Not a bug.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Windows 10
* testcafe version: 0.18.2
* node.js version: 5.0.3

**Comment by AlexanderMoskovkin** [comment]
Hi @berrutti,

Thanks for you proposal.

Meanwhile, TestCafe provides a capability to create custom reporter plugins (see [Reporter Plugin](https://devexpress.github.io/testcafe/documentation/extending-testcafe/reporter-plugin/)).

It allows to format TestCafe output in any way:
![reporter](https://user-images.githubusercontent.com/12047804/33884177-bdd9a9ba-df4f-11e7-8910-a4930cee60c2.png)

**Comment by AndreyBelym** [comment]
We discussed this suggestion and decided that using the [minimal](https://github.com/DevExpress/testcafe-reporter-minimal) reporter or a custom reporter is a best solution here.
