### ISSUE TITLE
Redirection to a local host is not working properly

### ISSUE THREAD

**Issue by alencar13** [DevExpress/testcafe#2006]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

After redirect to login page localhost an error is appeared

### What is the expected behavior?

Acces a login page locallly

### How would you reproduce the current behavior (if this is a bug)?

Actual Testcafe is configured "Control panel port: 1337 | Service port 1: 1338" and my application is allocated localhost too but in 3000 port (http://localhost:3000/login).
When I try to record some action via testcafe control panel, directing to my application, this error is shown:

Error: [$rootScope:inprog] $digest already in progress
http://error.angularjs.org/1.6.6/$rootScope/inprog?p0=%24digest
Error
columnNumber: 405
fileName: "http://localhost:1338/scripts/vendor.js?7929ba6d39aa4465=http%3A%7Clocalhost%3A3000%7C96b907a6-7776-4057-97fe-4fc8c34bf2b4%7Cr%7Cscript"
lineNumber: 123
message: "[$rootScope:inprog] $digest already in progress\nhttp://errors.angularjs.org/1.6.6/$rootScope/inprog?p0=%24digest"
stack: "u/<@http://localhost:1338/scripts/vendor.js?7929ba6d39aa4465=http%3A%7Clocalhost%3A3000%7C96b907a6-7776-4057-97fe-4fc8c34bf2b4%7Cr%7Cscript:123:405\nm@http://localhost:1338/scripts/vendor.js?7929ba6d39aa4465=http%3A%7Clocalhost%3A3000%7C96b907a6-7776-4057-97fe-4fc8c34bf2b4%7Cr%7Cscript:171:70121\n$apply@http://localhost:1338/scripts/vendor.js?7929ba6d39aa4465=http%3A%7Clocalhost%3A3000%7C96b907a6-7776-4057-97fe-4fc8c34bf2b4%7Cr%7Cscript:171:74412\ni/m<@http://localhost:1338/scripts/vendor.js?7929ba6d39aa4465=http%3A%7Clocalhost%3A3000%7C96b907a6-7776-4057-97fe-4fc8c34bf2b4%7Cr%7Cscript:171:81858\nr@http://localhost:1338/scripts/vendor.js?7929ba6d39aa4465=http%3A%7Clocalhost%3A3000%7C96b907a6-7776-4057-97fe-4fc8c34bf2b4%7Cr%7Cscript:171:19584\nvt/d.defer/n<@http://localhost:1338/scripts/vendor.js?7929ba6d39aa4465=http%3A%7Clocalhost%3A3000%7C96b907a6-7776-4057-97fe-4fc8c34bf2b4%7Cr%7Cscript:171:21050\n"

I don't know if this error is because proxy or if is without some especific configuration on angular.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: http://localhost:3000/login

```js

```

### Specify your

* operating system: Linux Ubuntu 5.4.0

* testcafe version: v. 15.1.3

* node.js version: v7.10.1

```

**Comment by MarinaRukavitsyna** [comment]
Hello,
We process all issues for TestCafe v15.1.3 via our Support Center. Please submit a ticket there, so that our support team will help you:
https://www.devexpress.com/Support/Center/Question/Create

**Comment by alencar13** [comment]
Hello,

I opened a ticket via support center, follow ticket: https://www.devexpress.com/Support/Center/Question/Details/T588146/angular-application-in-testcafe-control-panel

Take a look @darlanmendonca
