### ISSUE TITLE
Page is scrolled down when I type a text with the space symbol (Safari 11)

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe#2008]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

Page is scrolled down when I type a text with the space symbol into a content editable element.

### What is the expected behavior?

Page should not be scrolled.

### How would you reproduce the current behavior (if this is a bug)?

Start the client test into the Safari 11.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
 `test\client\fixtures\automation\content-editable\api-actions-content-editable-test\index-test.js`

### Specify your

* operating system: win 8.1
* testcafe version: 0.18.6-dev20171211
* node.js version: 9.0.0

**Comment by rob4629** [comment]
Seeing this issue referenced in the code alongside https://github.com/DevExpress/testcafe/issues/2008. Can we re-open unless they've been resolved?

**Comment by alexphilin** [comment]
Yes, you can re-open issues if they still affect your use cases.
