### ISSUE TITLE
Chome doesn't close with command+q on Mac

### ISSUE THREAD

**Issue by Nuarat** [DevExpress/testcafe#2013]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

TestCafe doesn't close Chrome when interrupted with command+q

### What is the expected behavior?

TestCafe should close chrome

### How would you reproduce the current behavior (if this is a bug)?

On MacOS, when tests are running in Chrome, press command+q, in the console

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: MacOS
* testcafe version: 0.18.5
* node.js version: 8.9.3 LTS (?)

**Comment by operatino** [comment]
Experiencing the same issue since few months.

MacOS version 10.13.2
Testcafe 0.18.6
Chrome 63.0.3239.84

**Comment by operatino** [comment]
Same happens with Firefox, multiple instances hanging after few test runs.

**Comment by AndreyBelym** [comment]
Hi @operatino! Unfortunately, it's not possible to handle Command + Q gracefully in a command line app. This key combination sends close command to the Terminal app, and it will terminate its children command-line process unconditionally if you agree to close running processes. It means TestCafe has no possibility to detect termination and sends close command to browsers.
