### ISSUE TITLE
Can We Have Watch Mode and Browser Not Closed

### ISSUE THREAD

**Issue by simonatorw** [DevExpress/testcafe#2016]
### Are you requesting a feature or reporting a bug?

Feature

### What is the current behavior?

Browser closes after test

### What is the expected behavior?

Browser remains open and any new test saved will be rerun

### How would you reproduce the current behavior (if this is a bug)?

N/A

#### Provide the test code and the tested page URL (if applicable)

N/A

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Windows 7
* testcafe version: 0.18.5
* node.js version: 6.11.0

**Comment by AlexanderMoskovkin** [comment]
Hi @simonatorw,

We are working on this right now (#1624) and it's in the testing stage. So I guess we'll provide a solution for this soon.
