### ISSUE TITLE
Chrome prevents download of multiple files using `createObjectURL`

### ISSUE THREAD

**Issue by cdroulers** [DevExpress/testcafe#2017]
### Are you requesting a feature or reporting a bug?

Reporting a bug!

### What is the current behavior?

When I run my full suite of tests, the last three all use the same page and click a button that downloads a file using `window.URL.createObjectURL` and adding it to an `a` element then clicking it.

This triggers a Chrome permission dialog to allow or block the files:

<img width="536" alt="1" src="https://user-images.githubusercontent.com/708798/33839623-c26a8386-de60-11e7-89c1-be938595ba6b.png">

### What is the expected behavior?

Either ignore the dialog or have an API to allow the file downloads. I think there's settings for Chrome profiles to auto-allow files, but I couldn't figure out how to get TestCafé to use a custom profile.

### How would you reproduce the current behavior (if this is a bug)?

See this repo: https://github.com/cdroulers/testcafe-multiple-files-repro

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: See repo above!

Test code

```html
<!doctype html>
<html lang="fr-CA">

<head>
  <meta charset="utf-8">
  <title>derp</title>
</head>

<body>
  HAI!

  <script>
    function createLink(content, name) {
      var blob = new Blob([content], {
        type: "application/octect-stream"
      });
      var url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.innerHTML = name;
      document.body.appendChild(a);
      a.href = url;
      a.download = name;
    }

    createLink("file1", "file1.txt");
    createLink("file2", "file2.txt");
    createLink("file3", "file3.txt");
  </script>
</body>

</html>
```

```js
import { Selector } from "testcafe";
import fs from "fs";

fixture(`Test multiple files`).page(`http://localhost:7777/`);

test("Can download three files", async t => {
  await t
    .click(Selector("a").nth(0))
    .click(Selector("a").nth(1))
    .click(Selector("a").nth(2))
    .wait(5000);
});
```

### Specify your

* operating system: Windows 10 Pro
* testcafe version: 0.18.5
* node.js version: v6.10.2

**Comment by cdroulers** [comment]
@LavrovArtem @AndreyBelym Thanks for the fix!

From the changes, it seems we can specify profile settings? Is that something that is available from the CLI or from code that we can use and if so, is there any documentation? Thanks for a great product!

**Comment by AndreyBelym** [comment]
Hello Christian!

You can use the `--user-data-dir` flag for Chrome and the `-profile` for
Firefox:

```
testcafe "chrome --user-data-dir=<your-profile-dir>

testcafe 'firefox -profile "<your-profile-dir>"'
```

21 дек. 2017 г. 18:27 пользователь "Christian Droulers" <
notifications@github.com> написал:

@LavrovArtem <https://github.com/lavrovartem> @AndreyBelym
<https://github.com/andreybelym> Thanks for the fix!

From the changes, it seems we can specify profile settings? Is that
something that is available from the CLI or from code that we can use and
if so, is there any documentation? Thanks for a great product!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/DevExpress/testcafe/issues/2017#issuecomment-353378947>,
or mute the thread

**Comment by alejandro-martinez** [comment]
Hi @AndreyBelym, I'm already using the "user-data-dir", still doesn't work. Thoughts? Thanks for this framework, it's amazing

**Comment by AndreyBelym** [comment]
Hi @alejandro-martinez, have you switched on 'Allow all sites download multiple files automatically' in the profile, whose path is specified with `--user-data-dir`? You can follow [this article](http://ccm.net/faq/32938-google-chrome-allow-websites-to-perform-simultaneous-downloads), if you don't how to do it. 

I can enable this flag for temporary profiles, generated by TestCafe, but I need some time to figure out which flag in the `$PROFILE_DIR/Default/Preferences` file actually controls this functionality. I'll very appreciate, if someone directs me to the flag name or maybe some documentation of the `Preferences` file structure.

**Comment by alejandro-martinez** [comment]
@AndreyBelym thanks dude, but I'm skipping the warning by deleting the first downloaded file first. So I just download the file, do some assertions, delete the file, download another file, and all over again. Cheers and thanks

**Comment by cdroulers** [comment]
@AndreyBelym Hey Andrey, The setting you're looking for is

```json
        "automatic_downloads": {
          "http://*,*": { "last_modified": "13158356206788629", "setting": 1 }
        },
```

I've successfully used a custom data dir with chrome to get this to work. I have a template folder copied from a new profile from Chrome in source control, copy that over in another folder before every run so I get a clean profile and it also use my settings properly.

**Comment by AndreyBelym** [comment]
Hi @cdroulers, @alejandro-martinez! I've missed that automatic downloads must be allowed in TestCafe-generated profiles in the latest release build. Could you please try to install `testcafe@0.19.1` and check your pages without the `--user-data-dir` flag?
