### ISSUE TITLE
Do Not Restart App After Each Test

### ISSUE THREAD

**Issue by simonatorw** [DevExpress/testcafe#2018]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

After each test, it would restart the app from the beginning.  Can we have a continuous flow of events?  It would not make sense to have multiple assertions in a test because that would not be descriptive.

### What is the expected behavior?

App will not restart after each test

### How would you reproduce the current behavior (if this is a bug)?

Have multiples test and run the tests

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Windows 7
* testcafe version: most current version
* node.js version: most current veresion

**Comment by AlexanderMoskovkin** [comment]
Hi @simonatorw ,

Thanks for the proposal. Take a look at the #1770 issue. We've discussed it there. We will add comments about any progress there.
