### ISSUE TITLE
Perform action on 1px elements hangs until it timeout

### ISSUE THREAD

**Issue by dfleury** [DevExpress/testcafe#2020]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

TestCafé is waiting the whole action timeout after perform an action on an element when one of yours dimensions (width or width) is equal to 1px.

### What is the expected behavior?

When an action is performed on a element with one of your dimensions being equal to 1px, it should proceed to the next step without waiting the entire action timeout

### How would you reproduce the current behavior (if this is a bug)?

Render an element with height or width as 1px and perform an action like hover or click

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://jsfiddle.net/b27vwh7r/

Test code

```html
<style>
        #failing {
            display: block;
            height: 1px;
            background: red;
        }
        #allgood {
            display: block;
            height: 2px;
            background: green;
        }
</style>
<div id="failing"></div>
<br /><br /><br /><br />
<div id="allgood"></div>
```

```js
import { Selector as $ } from 'testcafe'

fixture `bug`
	.page `http://localhost:8000/test.html`

test('Perform action on 1px elements hangs until it timeout', async (t) => {
	await t
		.hover($('#failing')) // slow
		.click($('#allgood')) // fast
})
```

### Specify your

* operating system: macOS 10.12.6 (Sierra)
* testcafe version: 0.18.5
* node.js version: 9.3.0

**Comment by AlexanderMoskovkin** [comment]
Hi @dfleury,

Thanks for you report, I've reproduced it and we'll investigate it.
As a workaround you can add the `timeout` option to the selector:

```js
    await t
        .click(Selector('#failing', { timeout: 500 }))
        .click(Selector('#allgood'));
```
