### ISSUE TITLE
E2E testing with react and redux

### ISSUE THREAD

**Issue by khrizt** [DevExpress/testcafe#2022]
### Are you requesting a feature or reporting a bug?

Probably it's a feature request or maybe a case that is not covered.

### What is the current behavior?

I'm trying to implement e2e tests in my react web and I need to clear the redux state on each test, as I use `redux-persist` the localStorage and sessionStorage clear don't clear the redux state.

The `redux-persist` package uses localforage as storage library and by default this library stores the data in IndexedDB, that's why, at least I think, that current code does not clean the data.

### What is the expected behavior?

The expectation was that after every test, or even after every fixture, the data was completely cleaned from the browser.

### How would you reproduce the current behavior (if this is a bug)?

Everytime I run a test I have the previous user data in the browser.

### Specify your

* operating system: All
* testcafe version: 0.18.5
* node.js version: 9.2.0

**Comment by miherlosev** [comment]
Hi, @khrizt.
At present, `TestCafe` does not clear the `indexedDB` storage. I've created a proposal in the proxy repository - https://github.com/DevExpress/testcafe-hammerhead/issues/1429.

However, there is a workaround. You can manually delete the database containing the redux state of your application.

```js
import { ClientFunction } from 'testcafe';

fixture `i2022`
	.page('http://devexpress.github.io/testcafe/example/')
	.afterEach(async t => {
		const removeDbWithState = ClientFunction(() => {
			return new Promise((resolve, reject) => {
				var DBDeleteRequest = window.indexedDB.deleteDatabase("db-with-redux-state");

				DBDeleteRequest.onerror = function(event) {
					reject("Error deleting database.");
				};
 
				DBDeleteRequest.onsuccess = function(event) {
					resolve("Database deleted successfully");
				};
			});
		});
		
		await removeDbWithState();
	});
	
test('1', async t => {
	// You code here...
});	
	
```

**Comment by khrizt** [comment]
When executing `deleteDatabase` the database is in blocked state and I can delete it. Is there a way to unblock the database? 

Looks like it's blocked because of the test execution. I tried to open it again, but I can't close it.

**Comment by miherlosev** [comment]
> database is in blocked state

It means that there are unclosed connections to this database.
See paragraph 8 in https://www.w3.org/TR/IndexedDB/#deleting-a-database.

I modified the [example](https://github.com/DevExpress/testcafe/files/1585652/index.zip) provided earlier to reproduce this situation.
See [video](https://www.screencast.com/t/O6ZnOxva) with reproduction.

To fix the problem, perform test actions without `TestCafe` and evaluate the code that clears the database in the Console tab.
If it works then use your code in a `ClientFunction` as shown in the example.
Also if it is difficult to find unclosed connections to database, you can try to enumerate database objects and clear them.

**Comment by khrizt** [comment]
I managed to get it working by navigating (and awaiting) on the afterEach callback to another page to unblock the database. But looks like that when running afterEach code the page is not unloaded so the database is not unblocked. A better way to do that would be great, but looks like this one must do for now.

**Comment by miherlosev** [comment]
> I managed to get it working by navigating (and awaiting) on the afterEach callback to another page to unblock the database

Glad to hear that.
We will search for a better way of clearing `indexedDb` in scope of https://github.com/DevExpress/testcafe-hammerhead/issues/1429

**Comment by khrizt** [comment]
Great! Thanks for the help. Let me know if I can contribute with something.
