### ISSUE TITLE
Skip javascript errors via programming interface

### ISSUE THREAD

**Issue by djwashburn** [DevExpress/testcafe#2033]
### Are you requesting a feature or reporting a bug?
Requesting a feature / asking a question

### What is the current behavior?
TestCafe will fail when a client javascript error occurs unless run with the -skip-js-errors command line flag.

### What is the expected behavior?
I would like to be able to enable this functionality within the test code itself, so that the tester does not have to remember to specify it in the command line when running the tests. I looked through the documentation for a way to do this but did not find one.

### Specify your

* operating system: Windows 10
* testcafe version: 0.18.5
* node.js version: v8.9.2

**Comment by helen-dikareva** [comment]
You can use the `run` method's `skipJsErrors` argument. Please take a look at corresponding [documentation](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#run).
