### ISSUE TITLE
Prevent fixtures from running on certain browsers

### ISSUE THREAD

**Issue by berrutti** [DevExpress/testcafe#2034]
### Are you requesting a feature or reporting a bug?
Requesting a feature

### What is the current behavior?
When executed, a fixture runs on whatever browser you assign it to. I have some tests that are written for a mobile version of a site, and they only work when I execute testcafe with chrome and the mobile options. If I run the test in say firefox, they fail because the page objects are not the same.

### What is the expected behavior?
A fixture should be able to check what browser is beign run on and skip if some conditions are not met.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Windows 10
* testcafe version: 0.18.2
* node.js version: v8.9.0

**Comment by AlexanderMoskovkin** [comment]
Hi @berrutti,

Thanks for your idea. We already have such proposal in the #1626 issue. Subscribe on it to be notified about any progress.
