### ISSUE TITLE
TestCafe can't find browser when executing concurrently

### ISSUE THREAD

**Issue by ameyagholkar** [DevExpress/testcafe#2035]
### Are you requesting a feature or reporting a bug?
Maybe, a bug.

#### Our setup
We're running testCafe in Visual Studio Team Services as a part of our build infrastructure. We're using VM's running Mac OS X 10.12.6. We're installing Chrome (latest stable), Firefox (57.0.3) via `brew`.

We run testCafe via our npm script. The npm script ferries our cmd arguments to testcafe.
We also use a custom js file to execute testCafe via it's programming interface. 
We run tests on chrome in headless mode.

#### Issue
When we run the tests in concurrency mode on our build infrastructure, for some reason, we're seeing the error:
```
Error: Unable to run the browser. The file at /Applications/Chrome.app does not exist or is not executable.
```
We've verified that --
- The browser exists
- `chrome` is listed by testCafe as one of the installed browsers (via `testcafe -b`)
- We tried removing all our npm scripts, the custom js file and just run the tests by directly targeting the testcafe.js in node_modules - but we see the same result when executing the test in concurrency mode.

The interesting observation is that the tests run fine on the same VMs with the same setup with the same commands _without_ concurrency mode.

### How would you reproduce the current behavior (if this is a bug)?
We couldn't get a repro locally. We tried installing chrome via `brew` and could still run tests concurrently.

Do you guys have any ideas on how to debug/solve this? Have you guys seen this happen before or have any ideas on what could be the possible issue?

* operating system: Mac OS X 10.12.6
* testcafe version: testcafe@0.18.6 
* node.js version: node/v6.12.2 darwin x64

**Comment by lukaszblasz** [comment]
I have the same error message, when trying to run testcafe using jenkins build on my mac.
In my jenkins bash file im calling:
`
npm install testcafe testcafe-reporter-xunit
node_modules/.bin/testcafe chrome e2e/ -r xunit:res.xml
`
I was trying solutions from other posts, like: 
-renaming Goole Chrome.app to Chrome.app 
-changing Chrome properties to have Read&Write permissions for all the users

Unfortunalety without success. `testcafe -b` is giving me 2 browsers: chrome and safari

When trying to run tests in safari i am getting similar error:

`ERROR Was unable to open the browser "locally-installed:safari" due to error.
Error: Unable to run the browser. The file at /Users/Shared/Jenkins/Home/workspace/test/node_modules/testcafe-browser-tools/bin/mac/open.scpt does not exist or is not executable.`

**Comment by AndreyBelym** [comment]
Hello @ameyagholkar, thank you for feedback. I've reproduced the problem. Could you please try to use `:userProfile` advanced Chrome Mode as a workaround? E.g.
```testcafe chrome:userProfile --concurrency 4 test.js```

@lukaszblasz, it can be a problem with your Jenkins setup. A user that runs Jenkins service needs Administrator privileges. Check this [gist](https://gist.github.com/ostinelli/972cfdb4bce51d428d3b#jenkins-user) for instructions. Also, the user should be logged in through the Mac's Login Screen.

**Comment by ameyagholkar** [comment]
👋 @AndreyBelym Thanks for your reply!

I'm not sure if I made it explicit, but we're using `chrome:headless` in our scripts.

I ran `testcafe chrome:headless:userProfile --concurrency 3 <my-files>` but I get the same error.

Since I'm using headless mode, is that above browser name correct?

**Comment by AndreyBelym** [comment]
Unfortunately. `userProfile` can't be used together with `headless`.

**Comment by ameyagholkar** [comment]
@AndreyBelym i see. Is there any other way to solve this for our case? Any suggestions?
Should the commit referenced above solve this issue even for headless mode?

**Comment by AndreyBelym** [comment]
@ameyagholkar, yes, it's intended to solve the issue for the headless mode.

**Comment by ameyagholkar** [comment]
@AndreyBelym I should mention that this happens on Firefox headless as well. Sorry didn't write that up in the original issue description.

**Comment by ameyagholkar** [comment]
Just making sure you guys read that ☝️ cc/ @AndreyBelym

**Comment by AndreyBelym** [comment]
Yep, I got it.

**Comment by ameyagholkar** [comment]
Any specific release (stable or dev) we can test this out on? 

cc/ @AndreyBelym @AlexanderMoskovkin

**Comment by AlexanderMoskovkin** [comment]
Hi @ameyagholkar, we are going to release a dev version with the fix tomorrow

**Comment by mpham-r7** [comment]
@ameyagholkar i see the fix is specific to chrome... i am having the same issue with firefox/firefox:headless as well... will there be a fix for those browsers?
