### ISSUE TITLE
Update testcafe docker image with nodejs 8

### ISSUE THREAD

**Issue by AlexDel** [DevExpress/testcafe#2039]
### Are you requesting a feature or reporting a bug?
Feature.

### What is the current behavior?
We are using testcafe docker image with mounted volumes that contain modules written for nodejs 8. Unfortunately current testcafe docker image can't run this modules (that contain 'async\await' and other node8 native stuff) because it has been build with node 6.

### What is the expected behavior?
Modules written with node8 features can be run via testcafe docker image.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by AndreyBelym** [comment]
Hello @AlexDel! You can pull the updated image with node 8 from Docker Hub.
