### ISSUE TITLE
Print stack of client-side JS errors

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#2043]
### Are you requesting a feature or reporting a bug?
Feature (from https://testcafe-discuss.devexpress.com/t/718)

### What is the current behavior?
TestCafe shows only the error's message.

### What is the expected behavior?
TestCafe should show full error information.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by helsont** [comment]
Is there any update on this? My use case is in my CI. If something goes wrong with an API call and my frontend code fails, it's hard to know what exactly went wrong with just my current backend logs. 

Can someone suggest a work around in the interim?
