### ISSUE TITLE
The same selector hangs the test in when clicking on specific HighChart visualisation while it performs correctly on others

### ISSUE THREAD

**Issue by xMort** [DevExpress/testcafe#2044]
### Are you requesting a feature or reporting a bug?
bug

### What is the current behavior?
I'm using TestCafe to test the functionality of some HighChart visualisations.

I have an issue with a stacked column chart where one of the Selectors hangs until the resolve timeouts and then TestCafe successfully clicks on the element. I can solve the situation by adding `{timeout: 500}` to the selector as I seen recommended as the workaround in some other bug reported here but this is not the solution.

In my application I use exactly the same selector but on two different pages (and on one it behaves correctly, on the other it hangs). For the issues replication test case posted bellow I added both charts to a single page and prefixed the selectors with an ID of the chart's containers, i.e., not the same selector object is used for both charts but issue should be obvious.

### What is the expected behavior?
The selector finds the existing element immediately and TestCafe clicks on the element it identifies promptly without unnecessary delay. 

### How would you reproduce the current behavior (if this is a bug)?
Check the test page in jsfiddle linked below and run the test to see the behavior. When TestCafe clicks on the first chart column the 0 in tested div is immediately changed to 1. Then there is a prolonged period of time before TestCafe moves to the second chart and clicks it (which for there is no obvious reason). The second tested div has its content correctly changed from 0 and 1 and test succeeds.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: 
[https://jsfiddle.net/xmort/a8z1mnLr/1/](https://jsfiddle.net/xmort/a8z1mnLr/1/)

Test code

```js
import { Selector } from 'testcafe';

fixture('Tests')
    .beforeEach(async (t) => {
        await t.navigateTo('https://jsfiddle.net/xmort/a8z1mnLr/1/');
    });

const firstChartSelector = Selector('#chart1-container .highcharts-series.highcharts-series-0 rect:first-child');
const secondChartSelector = Selector('#chart2-container .highcharts-series.highcharts-series-0 rect:first-child');

test('Test that charts are clickable', async (t) => {
    await t.switchToIframe('iframe[name=result]');
    await t.click(firstChartSelector);
    await t.click(secondChartSelector);
    await t.expect(Selector('#chart1-clicked').innerText).eql('1');
    await t.expect(Selector('#chart2-clicked').innerText).eql('1');
});
```

### Specify your

* operating system: macOS 10.13.2 (High Sierra)
* testcafe version: 0.18.5
* node.js version: 6.9.1

**Comment by miherlosev** [comment]
Hi @xMort .

I ran your test using `testcafe@0.19.2` and it passed.
I will close the issue. Feel free to reopen it if the problem persists.
