### ISSUE TITLE
Focusing on the checked radio button does not work by tab key 

### ISSUE THREAD

**Issue by nikolaj10** [DevExpress/testcafe#2045]
### Are you requesting a feature or reporting a bug?
Bug report

### What is the current behavior? (this step can be also used to reproduce the bug)
Example: In real environment (on any web page) when radio group gets focus by tab key, the selected radio is focused. The testcafe focuses the first radio (checked or unchecked).

### What is the expected behavior?
Focusing the checked radio button after pressing tab key from the previous element above this group of radio buttons

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
http://devexpress.github.io/testcafe/example/

Test code:
````
test('Should select the checked radio button by pressing the tab key', async () => {
    await t
       .click(Selector('#macos'))
       .click(Selector('#traffic-markup-analysis'))
       .pressKey('tab')
       .expect(Selector('#macos').focused).ok();
});
````
This test should pass, but it fails

### Specify your

* operating system: Win 7
* testcafe version: 0.18.6
* node.js version: 6.10.2

**Comment by AlexanderMoskovkin** [comment]
Hi @nikolaj10,

Thanks for your report. I've reproduced the issue and we'll fix this.
