### ISSUE TITLE
Safari is not closing after successfully executing a test that has passed

### ISSUE THREAD

**Issue by evanniedojadlo** [DevExpress/testcafe#2047]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Unlike Chrome, Safari will not automatically close the instance after the test has successfully executed and passed. The Safari window that was opened during the test will stay open. This issue is intermittent but I thought that you should be aware.

### What is the expected behavior?
I am expecting the Safari to close after the test is executed

### How would you reproduce the current behavior (if this is a bug)?
Run a test using safari e.g. `testcafe safari first_testcafe.js` and watch the test execute on Safari, pass, and the browser will sometimes stay open after the test executes

#### Provide the test code and the tested page URL (if applicable)
This was using the demo code provided here: http://devexpress.github.io/testcafe/documentation/getting-started/

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
 Running tests in:
 - Safari 11.0.2 / Mac OS X 10.12.6

* testcafe version:
0.18.6

* node.js version:
5.6.0

**Comment by AndreyBelym** [comment]
Hello @evanniedojadlo!

We've found a problem with browser manipulation binaries, which prevented to set executable permissions during post-installation phase,  and fixed it the version `0.19.0-alpha1`. So could you please try to install it and check if the problem still affects you?

**Comment by evanniedojadlo** [comment]
@AndreyBelym thanks, I went ahead and downloaded separately using https://github.com/DevExpress/testcafe/releases/tag/v0.19.0-alpha1 executed several tests using safari and didn't see the issue again.

**Comment by qualityshepherd** [comment]
I'm seeing this currently on osx mojave; testcafe 0.23.3; safari 12.0.3; node v10.15.2

**Comment by AlexKamaev** [comment]
@qualityshepherd 
We haven't faced any similar issue since it was fixed in the 0.19 version, so probably the cause of the issue is different. I think it would be better if you create a separate issue using this [form](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md).
We would appreciate it if you provide us with any additional information, which will help us to reproduce the issue.
