### ISSUE TITLE
On iOS Safari, clicking a moving link on the bottom of the page has issues

### ISSUE THREAD

**Issue by dcsaszar** [DevExpress/testcafe#2050]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

In Safari, TestCafe does not always click a link, but considers the `click` step successful.
This happens often for a link in the footer of a long page, when testing Mobile Safari in Sauce Labs.
Our tested page is filled dynamically, so the footer is a moving target.

### What is the expected behavior?

A successful click happens. This triggers a click event on the element.

### How would you reproduce the current behavior (if this is a bug)?

See below. Trying to simulate what may happen on Mobile Safari, this is a hardcore setup with local Safari. It fails in about 50% when run with
`testcafe safari tests/test.js --selector-timeout 5000 --assertion-timeout 5000`

Not sure if this really simulates what happens on iOS simulator, but the symptoms are identical.

```
Browser: Safari 11.0.2 / Mac OS X 10.13.2

          5 |
          6 |test('Footer navigation', async t => {
          7 |  await t
          8 |    .switchToIframe('[name=result]')
          9 |    .click(Selector('a').withText('Test'))
       > 10 |    .expect(Selector('i').exists).ok()
         11 |});
         12 |
```

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

https://jsfiddle.net/e8cg16r7/11/

Test code

```js
import { Selector } from 'testcafe';

fixture `test`
  .page `https://jsfiddle.net/e8cg16r7/11/`;

test('Footer navigation', async t => {
  await t
    .switchToIframe('[name=result]')
    .click(Selector('a').withText('Test'))
    .expect(Selector('i').exists).ok()
});
```

### Specify your

* operating system: OSX 10.13.2
* testcafe version: 0.18.6
* node.js version: 9.4.0

### Related

This comment talks about missed clicks when a reflow occurs, maybe related:
https://github.com/DevExpress/testcafe/issues/1191#issuecomment-276143445

#1237 may also be related, because we observe the issue with a scrolling page and Sauce Labs simulated iOS.

**Comment by AndreyBelym** [comment]
Hello @dcsaszar!

We encountered some scroll issues, especially on mobile devices. Currently I'm doing some work to improve scrolling functionality, so maybe it will fix your problem too. I'll let you know when a developer build with a fix will be available.

**Comment by AndreyBelym** [comment]
Hi @dcsaszar, we've significantly improved scrolling in the last versions. Could you please try to install `testcafe@0.22.0` and check if you can reproduce the issue?

**Comment by dcsaszar** [comment]
Hi @AndreyBelym we upgraded three weeks ago, and also updated other parts of our test infrastructure. Currently this issue doesn't affect us in real life. So, it has no priority for us at the moment.

FYI: While we are no longer experiencing the issue in *our* tests, my synthetic test case for this issue still fails.

**Comment by dcsaszar** [comment]
With 1.9.4 the test setup consistently fails at the click step:

```js
Running tests in:
 - Safari 14.0 / macOS 10.15.7
✖ Footer navigation

   1) The element that matches the specified selector is not visible.

      Browser: Safari 14.0 / macOS 10.15.7

          4 |  .page `https://jsfiddle.net/e8cg16r7/11/`;
          5 |
          6 |test('Footer navigation', async t => {
          7 |  await t
          8 |    .switchToIframe('[name=result]')
       >  9 |    .click(Selector('a').withText('Test'))
         10 |    .expect(Selector('i').exists).ok()
         11 |});
         12 |
```

The screen shows how the test is trying to scroll and to click at the right spot, but it probably clicks too late.
So the situation has improved in the sense that testcafe is acting like a human user, and it reports the observed error correctly.

I'd say the initial issue

> In Safari, TestCafe does not always click a link, but considers the click step successful.

is solved.
