### ISSUE TITLE
How to intercept entire webpage picture?

### ISSUE THREAD

**Issue by OneSir** [DevExpress/testcafe#2055]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by AlexanderMoskovkin** [comment]
Hi @OneSir,

For now TestCafe doesn't allow to take a screenshot of the entire page and we already have a proposal for this (see #1520).
