### ISSUE TITLE
Selector() not consistently finding DOM elements

### ISSUE THREAD

**Issue by nkamenar** [DevExpress/testcafe#2059]
### Are you requesting a feature or reporting a bug?
Reporting a bug

### What is the current behavior?
Given this HTML on the page:
```
<div class="dxb" id="LoginButton_CD">
	<input name="LoginButton" class="dxb-hb" id="LoginButton_I" type="submit" value="Log In" />
	<span class="dx-vam">Log In</span>
</div>
```
None of the following work and the page just says "Waiting for an element to appear" and times out:
```
await t.click("#LoginButton_I");
await t.click(Selector("input[value='Log In']"));
await t.click(Selector("input").withAttribute("name", "LoginButton"));
await t.click(Selector("input").withAttribute("value", "Log In"));
```
But the following does work:
`await t.click(Selector("span").withText("Log In"));`

### What is the expected behavior?
All of the above should work. Running the above through equivalent jQuery selectors on the page returns the objects as expected.

### How would you reproduce the current behavior (if this is a bug)?
-

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: -

Test code: included above

### Specify your

* operating system: Windows 10
* testcafe version: latest release
* node.js version: latest release

**Comment by AlexanderMoskovkin** [comment]
Hi @nkamenar,

I've created a simple example based on your description and it works properly on my side:

```js
import { Selector } from 'testcafe';

fixture`gh-2059`
    .page`https://jsfiddle.net/o0wb7e90/`;

test('test', async t => {
    await t.switchToIframe(Selector('iframe').withAttribute('name', 'result'));

    await t.click("#LoginButton_I");
    await t.click(Selector("input[value='Log In']"));
    await t.click(Selector("input").withAttribute("name", "LoginButton"));
    await t.click(Selector("input").withAttribute("value", "Log In"));
});
```

Please take a look at this. 
You can run tests with the [--debug-on-fail](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--debug-on-fail) to ensure whether the target button is visible on the page when the test fails in your case.

**Comment by nkamenar** [comment]
![image](https://user-images.githubusercontent.com/8999291/35283240-b7f92178-0025-11e8-9d23-e701e814607c.png)
As you can see above the button is on the page. Additionally debugging the page after fail I can see the following if I inspect element:
![image](https://user-images.githubusercontent.com/8999291/35283313-ebf5249a-0025-11e8-8e68-6ca2f604ef9e.png)
And running jQuery in the console to try and select it works:
![image](https://user-images.githubusercontent.com/8999291/35283373-1420a9ee-0026-11e8-9cd4-4a75205fd1be.png)
So I am really just at a loss for why the selector on the span works but the selector for the input refuses to.

**Comment by AlexanderMoskovkin** [comment]
To be honest I don't see any reason why it can't be found. Could you please provide us with the url of your page to check the issue on our side? If it contains any sensitive data you can send it privately to the email from my Github profile.

**Comment by nkamenar** [comment]
Unfortunately it's an intranet site so I can't provide a link. I am going to keep experimenting and if I find anything I will post it here. Thanks for the assistance.

**Comment by AlexanderMoskovkin** [comment]
@nkamenar Could you please clarify what the exactly error TestCafe throws when the test fails?

**Comment by nkamenar** [comment]
The error is "The element that matches the specified selector is not visible." but I have shown you the html and there isn't anything there that should be "hiding" it as far as I can tell.

**Comment by AlexanderMoskovkin** [comment]
@nkamenar Thanks a lot for you clarification. TestCafe founds the element but consider it invisible for some reason. I guess it can be related to the element styles.
We will appreciate it quite a lot if you help us reproduce the issue.
Could you please create an example (on the jsfiddle for example) with the same markup and css styles as in your site? For example you can just add css styles to [my example](https://jsfiddle.net/o0wb7e90/).

**Comment by nkamenar** [comment]
I have updated the fiddle attaching the styles relevant to those tags but in js fiddle it ends up not even looking like a button anymore. I think this is because it is a DevExpress button control so it is a bit complex. Here is the updated [fiddle](https://jsfiddle.net/o0wb7e90/1/)

**Comment by AlexanderMoskovkin** [comment]
Thanks for the example! I see that the button has `width=0` and `height=0`. So in fact the button is not visible. That's why TestCafe can't find it. It seems it's a part of the DevExpress button implementation. I guess when you click on the `Log In` span DevExpress scripts triggers click on the button. 
So the best solution for an E2E test here is to click on the `span`.

**Comment by nkamenar** [comment]
Alright, thank you very much for the support!

**Comment by MatiasFB** [comment]
Hello, I am trying testCafe and I am not able to select elements. What am I doing wrong? Here you have the example:

The Code:
import { Selector} from 'testcafe';

const testing = Selector('input').withAttribute('title','Search');

fixture `My own Training`
    .page `www.google.com`;

test('My first test', async t => {
    await t.typeText(testing, "hello word");
  
});

The page:
<img width="1427" alt="Screen Shot 2020-06-25 at 6 48 44 PM" src="https://user-images.githubusercontent.com/67442489/85799829-46033400-b716-11ea-95a8-0f2fe8a4e98a.png">
The result:
![Screen Shot 2020-06-25 at 7 02 10 PM](https://user-images.githubusercontent.com/67442489/85799905-69c67a00-b716-11ea-94c8-970043c0f31a.png)

**Comment by lpelipenko** [comment]
I am experiencing the same issue when I try to use selector `Selector('input').withAttribute('title','Search');`

**Comment by wentwrong** [comment]
TestCafe launches a browser with a clean profile (you can change that by using [User Profiles](https://devexpress.github.io/testcafe/documentation/guides/concepts/browsers.html#user-profiles)) and, because of that, Google will redirect you to the internationalized version of the site based on your location. The "title" attribute of the search input will use a localized word too. I assume that Google shows you "Buscar" instead of "Search".

Use the [Debug Mode](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#-d---debug-mode) to search the attribute value. The following article may be helpful: [How to Debug Tests in TestCafe: Quick Guide](https://devexpress.github.io/testcafe/media/team-blog/how-to-debug-tests-in-testcafe-quick-guide.html).

**Comment by manoadamro** [comment]
same issue here, apparently this highlighted element doesn't exist. even with a 5 second wait between every action:

<img width="1196" alt="Screenshot 2021-07-21 at 13 45 38" src="https://user-images.githubusercontent.com/29605020/126490679-1f6d85b7-f50a-483f-bc32-f27185baa03d.png">
