### ISSUE TITLE
Get host information for remote browsers inside the test

### ISSUE THREAD

**Issue by dininski** [DevExpress/testcafe#2061]
### Are you requesting a feature or reporting a bug?
Requesting a feature

### What is the current behavior?
When running tests using a remote browser you should be able to obtain information on which host the test is running on.

### What is the expected behavior?
Ability to get host information when a test is being executed on a remote worker.

### How would you reproduce the current behavior (if this is a bug)?
After inspecting a bit of the code it seems that testcafe might not be passing that information to the tests, but instead keeps a plain queue of workers and simple passes the test information.

#### Provide the test code and the tested page URL (if applicable)
N/A

Tested page URL: N/A

Test code

```js
N/A
```

### Specify your

* operating system: any
* testcafe version: 0.18.7-dev20180117
* node.js version: 8.x

**Comment by AlexanderMoskovkin** [comment]
Hi @dininski,

Am I understand right you'd like to detect in the test the url where the TestCafe server is served? I'm wondering how are you going to use this info?
Meanwhile if you need to have a constant address for this you can set it by using `hostname` and `ports` options ([cli](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--ports-port1port2) and [programming](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/testcafe.html)).

**Comment by dininski** [comment]
NVM turns out this was easily achievable using a custom browser provide. Closing.
