### ISSUE TITLE
Suggestion: move testcafe type to @types repository

### ISSUE THREAD

**Issue by AhnpGit** [DevExpress/testcafe#2065]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
Testcafe type is inside Testcafe package

### What is the expected behavior?
Move to @types repository like other libraries

### How would you reproduce the current behavior (if this is a bug)?
N.A.

#### Provide the test code and the tested page URL (if applicable)
N.A

### Specify your

* operating system: Windows 10 64 bit
* testcafe version: 0.18.6
* node.js version: 8.9.4

Hi,

I have a question regarding to TypeScript support for TestCafe. Is it better to move it to @types repository like the other libraries ? What do you guys think about it ?

**Comment by AlexanderMoskovkin** [comment]
Hi @AhnpGit,

Thanks for you suggestion. The [Typescript handbook](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) proposes to bundle the declaration file with the npm package. Additionally it makes typedefs maintaining easier for us (since it's in the same repository). 
But if we find significant reasons to change it we can always review this. Did you face with any problems because of our current way of typedefs publishing.

**Comment by AhnpGit** [comment]
Hi @AlexanderMoskovkin,
Actually I don't have problems with the current way of typedefs publishing. I'm just curious about the reason why you keep it in the source code but not separate it like other libraries. Now I understand it. Thank you for your response.

**Comment by jadams88** [comment]
Hi @AlexanderMoskovkin ,
I'm not sure if this is related or that moving the definitions to @types would solve the issues, but I am currently getting a clash between the declaration of 'var test' between the type definitions of Testcafe and Jest.

TestCafe -> declare var test: TestFn;
Jest -> declare var test: jest.It;

TS Error
[ts] Subsequent variable declarations must have the same type.  Variable 'test' must be of type 'TestFn', but here has type 'It'.

The Jest definitions are installed from @types/jest as a devDependency and the Testcafe types are loaded from the npm package.

The clash in definitions are preventing my NativeScript project from compiling via webpack.

Thank you for your time.
Jono
