### ISSUE TITLE
Implement a form submitting after pressing the space button

### ISSUE THREAD

**Issue by nikolaj10** [DevExpress/testcafe#2066]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

Pressing the space key on the focused button (the submit one) does not cause any reaction, but it should be the same as clicking on this button

### What is the expected behavior?

Pressing the space key on focused button (the submit one) should triggers click event, so the testcafe page should displays the text: "Thank you, " + expected name

### How would you reproduce the current behavior (if this is a bug)?

1. Insert some text into the input with label 'your name'
2. Click on the checkbox with text ' I have tried TestCafe'
3. Pressing the tab key three times to focus the 'Submit' button
4. Pressing the space key to simulate click event
5. Page should displays the text "Thank you, [insert name from the first input]" but it does not happen

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

http://devexpress.github.io/testcafe/example/

Test code

```
test('Should focus the "Submit" button by pressing tab key from previous element, then pressing space key to simulate click event on the button ', async () => {
    await t
        .typeText(Selector('#developer-name'), 'Nick')
        .click(Selector('#tried-test-cafe'))
        .pressKey('tab tab tab')
        .pressKey('space')
        .expect(Selector('#article-header').innerText).eql('Thank you, Nick!');
});
```
This test should pass, but it fails

### Specify your

* operating system: Win 7
* testcafe version: 0.18.6
* node.js version: 6.10.2

**Comment by helen-dikareva** [comment]
Thank you for your suggestion. We will think about implementing this functionality.

The browser recognizes pressing the space or enter, or a click on the submit button as equivalent actions, and these actions are default browser behavior. So it isn't of importance here what action is used - you can use `pressKey('enter')` or `click('#submit-button')` instead of `pressKey('space')`.

**Comment by nikolaj10** [comment]
I agree with you, there are a few equivalents for click event, but i work as a Tester SW, so i sometimes need to test space event too. I think that, all these equivalents for click event should also work in a situation, where we do not have a choice. I understand that, it is not so important, but eventually it should works mainly because it is a part of default browser behavior too. Thank you for understanding.

**Comment by helen-dikareva** [comment]
Anyway we are going to implement this functionality)
