### ISSUE TITLE
Pressing the down key does not work for switching between radio buttons

### ISSUE THREAD

**Issue by nikolaj10** [DevExpress/testcafe#2067]
### Are you requesting a feature or reporting a bug?

Bug report

### What is the current behavior?

Pressing the down key from the checked radio button to focus the next one does not cause any reaction in testcafe environment unlike manual testing (behavior)

### What is the expected behavior?

Pressing the down key from checked (focused) radio button should checked (focused) the next one (below the first checked) 

### How would you reproduce the current behavior (if this is a bug)?

1. Click on the 'MacOS' radio button to checked it
2. Pressing the down key (arrow down) should checked the next one ('Linux' radio button) but it does not happen

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

http://devexpress.github.io/testcafe/example/

Test code

```
test('Should checked the "MacOS" radio button and pressing the down key to focus the next "Linux" radio button', async () => {
    await t
        .click(Selector('#macos'))
        .pressKey('down')
        .expect(Selector('#linux').focused).ok();
});
```
This test should pass, but it fails

### Specify your

* operating system: Win 7
* testcafe version: 0.18.6
* node.js version: 6.10.2

**Comment by helen-dikareva** [comment]
Thanks for your report. I've reproduced the issue and we'll fix this.
