### ISSUE TITLE
Wrong handling  of key pressing in input

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#2070]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

Input value changed after click and press "Up" button

### What is the expected behavior?

Input value should not be changed

### How would you reproduce the current behavior (if this is a bug)?

```js
import { Selector, ClientFunction } from 'testcafe';

fixture `fixture`
    .page `http://dolzhikov-w8/172/RegressionTestsSite/ASPxEditors/ASPxDateEdit/T187651.aspx`;

test('test', async t => {
    const input = Selector("#ASPxDateEdit1_I");

    await t.click(input);

    var oldValue = await input.value;

    await t
        .pressKey("up")
        .expect(input.value).eql(oldValue);
});
```

### Specify your

* testcafe version: 0.18.6-dev20171222

**Comment by miherlosev** [comment]
I'm working on this

**Comment by AndreyBelym** [comment]
The issue will be closed after updating `testcafe-hammerhead`.
