### ISSUE TITLE
Onpaste event is not called using Typing Action Option "paste"

### ISSUE THREAD

**Issue by PierreRott** [DevExpress/testcafe#2075]
### Are you requesting a feature or reporting a bug?
BUG

### What is the current behavior?
TypeText option 'paste' doesn't work as expected, onpaste event is not called.

### What is the expected behavior?
Onpaste event in input, span etc. is called.

### How would you reproduce the current behavior (if this is a bug)?

Create two inputs as in the code below.
There will be an alert text displayed in the second input while onpaste event is called on the first input.
When you copy paste anything ( using Ctrl+C, Ctrl+V ) inside the first input, the second input displays an alert text, whereas the second input stays empty while using testcafe.

HTML:

```
<input type="text" id="input" onpaste="document.getElementById('input2').value = 'event was called'"/>
<input type="text" id="input2" />
```

testcafe:

```
test('Should verify that input2 will contain event alert text', async () => {
    const input = Selector('#input');
    const input2 = Selector('#input2');
    await t
        .typeText(input, 'sssss', {paste: true})
        .expect(input2.value).eql('event was called'); //this will fail!
```

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Windows7
* testcafe version: 0.18.6
* node.js version: 8.9.3

**Comment by helen-dikareva** [comment]
Hello @PierreRott.
Thank you for your request. We've planned the `paste` option for the `typeText` action primarily to reduce time for typing operations which are carried out symbol by symbol. 
Now we are going to implement typing with the `paste` option as an equivalent of a paste operation including raising of the `paste` event.

**Comment by PierreRott** [comment]
Hello, Hellen.
Thank you for your prompt reply, I really appreciate it.
This feature would be very helpful, so it is nice to see, that you are going to implement a paste operation including raising of the paste event.
I think you are doing a great job! Many thanks and keep up the good work!
