### ISSUE TITLE
eql not casesensitive for IE

### ISSUE THREAD

**Issue by ItsMeFP** [DevExpress/testcafe#2079]
### Are you requesting a feature or reporting a bug?
A Bug

### What is the current behavior?
While a test with chrome performs ok, the same test failes with IE 11.786.15063.0

### What is the expected behavior?
This test should perform ok with big letters for IE

But result for ie:

 × test page

   1) AssertionError: expected 'Should be a big text' to deeply equal 'SHOULD BE A BIG TEXT'

      Browser: IE 11.0.0 / Windows 10 0.0.0

         29 |.page `C:\Temp\TestHtml.html`;
         30 |
         31 |test('test page', async t => {
         32 |    const selected = await Selector('#test').innerText;
         33 |    console.log("Output : " + selected);
       > 34 |    await t.expect(selected).eql('SHOULD BE A BIG TEXT');
         35 |});
         36 |

...

 1/1 failed (0s)

### How would you reproduce the current behavior (if this is a bug)?
Perform test at IE

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
`<html> <span id="test" style="text-transform:uppercase">Should be a big text</span></html>`

Test code

test('test page', async t => {
    const selected = await Selector('#test').innerText;
    console.log("Output : " + selected);
    await t.expect(selected).eql('SHOULD BE A BIG TEXT');
});
### Specify your

* operating system: Windows10
* testcafe version: 0.18.3
* node.js version: 3.2.0

**Comment by AlexanderMoskovkin** [comment]
Hi @ItsMeFP,

This issue relates to the way how the `innerText` property works in IE. As you can see in the [jsfiddle example](https://jsfiddle.net/cw97xe7n/1/) the `innerText` property returns value not in `UPPERCASE`. TestCafe operates with values that are returned by browsers. Unfortunately, it seems there is no way to know how the text of the element exactly looks in IE.

You can check the `textContent` property or the [match](https://devexpress.github.io/testcafe/documentation/test-api/assertions/assertion-api.html#match) assertion with a regexp with [a case-insensitive modifier](https://www.w3schools.com/jsref/jsref_regexp_i.asp) if you need a case-insensitive check.

Additionally you can check the `getStyleProperty('textTransform')` function to check the element is displayed in the `uppercase style`:

```js
import {Selector} from 'testcafe';

fixture('gh-2079')
    .page('https://jsfiddle.net/cw97xe7n/2/');


test('/take screen shot', async (t) => {
    await t.switchToIframe(Selector('iframe').withAttribute('name', 'result'));

    const el = Selector('#test');

    await t
        .expect(el.textContent).eql('Should be a big text')
        .expect(el.innerText).match(/Should be a big text/i)
        .expect(el.getStyleProperty('text-transform')).eql('uppercase');
});
```
