### ISSUE TITLE
Firefox waits for an element without necessity 

### ISSUE THREAD

**Issue by VasilyStrelyaev** [DevExpress/testcafe#2080]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

During the test, Firefox waits for some element to appear for no reason.

### What is the expected behavior?

Firefox does not wait for an element during the specified test.

### How would you reproduce the current behavior (if this is a bug)?

Run the specified test. Firefox types text into an input, then waits for something for the entire timeout period and then continues the test.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: http://devexpress.github.io/testcafe/example/

Test code

https://github.com/DevExpress/testcafe/blob/master/examples/basic/test.js#L49

### Specify your

* operating system: Windows 10
* testcafe version: 0.18.7-dev20180117
* node.js version: 9.2.0

**Comment by adback03** [comment]
I'm also experiencing the exact same thing in both Firefox and IE 11. Chrome (and headless Chrome) both work fine.

**Comment by berrutti** [comment]
Can confirm this behavior

**Comment by AndreyBelym** [comment]
Hi @adback03 @berrutti  @arenddeboer! The fix is released in `testcafe@0.22.0`, you can install it with `npm i testcafe@latest` and try it on your machine.

**Comment by AlisarDius** [comment]
Hello, please, can you confirm this issue is fixed? I'm running testcafe v 0.22.0 and the issue is occuring for me everytime I use selectText action (on both Windows with Chrome, and remote device - iPad with Safari).
I even tried npm i testcafe@latest - installed TestCafe v 0.23.2 but without any change.

**Comment by AlexSkorkin** [comment]
@AlisarDius  
Yes, we confirm that this issue has been fixed. If you think that this issue still exists, please [submit a new issue](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md) with your sample test, your webpage URL and all steps we need to perform, so we can examine it. Thank you in advance.
