### ISSUE TITLE
Edge - Windows popup appears on test start

### ISSUE THREAD

**Issue by VasilyStrelyaev** [DevExpress/testcafe#2081]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

When starting a test in Edge, a Windows popup appears asking where to open the web page.

### What is the expected behavior?

No popup should appear.

### How would you reproduce the current behavior (if this is a bug)?

Run any test in Edge

### Specify your

* operating system: Windows 10
* testcafe version: 0.18.7-dev20180117
* node.js version: 9.2.0

**Comment by miherlosev** [comment]
On the latest TestCafe version (`0.20.2`) all works fine.

**Comment by VasilyStrelyaev** [comment]
Or it was fixed by an Edge update
