### ISSUE TITLE
Reused the test 

### ISSUE THREAD

**Issue by ChiaShan** [DevExpress/testcafe#2088]
### Are you requesting a feature or reporting a bug?
feature

### What is the current behavior?
hi, I am news in testcafe...
I am trying to test button's behavior in a page in different test, and it should link to other page then continue, but I don't want to overwriting the same click in the following test, is it there any way to avoid it? 
for example:
```js
test('test  1', async t => {
    await t
        .click(button1)
)}
test('test  2', async t => {
    await t
        .click(button1)
        .click(button2)
)}
```

**Comment by AlexanderMoskovkin** [comment]
Hi @ChiaShan,

You can place common used code into a function a reuse it:

```js
import { Selector, t } from 'testcafe';

const performSomeActions = async () => {
    await t.click(button1);
    // ...
};

test('test 1', async t => {
    await performSomeActions();
});
```

Additionally, it's a good practice to use Page Models in your tests. Take a look at our [recipe](https://devexpress.github.io/testcafe/documentation/recipes/using-page-model.html).
