### ISSUE TITLE
[Feedback request] Can someone check my code generator strings for test cafe? Especially visibility assertions.

### ISSUE THREAD

**Issue by QuantumInformation** [DevExpress/testcafe#2090]
Hi, I'm the author of https://github.com/QuantumInformation/test-recorder
I am currently working on support for Testcafe.
I was wondering if someone could advise me if I have the correct string templates to match your API, especially the visibility assertions.

If you look at the generator for the Testcafe, I have an old string `.waitForElementNotPresent('${queryPath}', 1000)` that I use for nightwatch, would be the equivalent for Testcafe?
https://github.com/QuantumInformation/test-recorder/blob/backup/src/codeGenerators/TestCafeGenerator.ts#L45

It is also my understanding that I don't need to add wait for statements for assertions.

This is the current version (without testcafe support):

https://chrome.google.com/webstore/detail/test-recorder/mehbmedddkpilcbbjcichiopegameghh

I'm also wondering what would be equivalent of this nightwatch assertion for text content in testcafe? `.assert.containsText('#${el.parentElement.id}','${el.nodeValue}')`
https://github.com/QuantumInformation/test-recorder/blob/backup/src/codeGenerators/TestCafeGenerator.ts#L54

**Comment by AlexanderMoskovkin** [comment]
Hi @QuantumInformation,

> I have an old string .waitForElementNotPresent('${queryPath}', 1000)

In TestCafe it will be `await t.expect(Selector('<queryPath>').exists).notOk({ timeout: 1000 })`. (where `<queryPath>` is a css selector)

> I don't need to add wait for statements for assertions.

You are right. (see [Smart Assertion Query Mechanism](https://devexpress.github.io/testcafe/documentation/test-api/assertions/#smart-assertion-query-mechanism))

> .assert.containsText('#${el.parentElement.id}','${el.nodeValue}')

I guess it will be more complicated in TestCafe:

```js
const el = Selector('some-css-selector');
const expectedValue = await el.textContent; // this depends on what is it `el.nodeValue`

await t.expect(el.parent(0).id).contains(expectedValue);
```

**Comment by QuantumInformation** [comment]
Thx @AlexanderMoskovkin so much, I think what I will do is get my next version in 2-3 weeks to contain these assertions and see if the community likes it.
