### ISSUE TITLE
take screenshot only when test fails

### ISSUE THREAD

**Issue by multivoltage** [DevExpress/testcafe#2092]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
testcafe provide a way to take screenshot

### What is the expected behavior?
a callback function or similar which check if test/assertion/action fails and take screenshot

**Comment by shaikatz** [comment]
You can use -S flag to take screenshots on failures. 

```
-S, --screenshots-on-fails
Takes a screenshot whenever a test fails. Screenshots are saved to the directory specified by using the -screenshots <path> option.

For example, the following command runs tests from the  sample-fixture.js file in all browsers, takes screenshots if tests fail, and saves the screenshots to the  screenshots directory.

testcafe all tests/sample-fixture.js -S -s screenshots
```

**Comment by multivoltage** [comment]
very good :)
