### ISSUE TITLE
t.maximizeWindow on before fixture

### ISSUE THREAD

**Issue by shaikatz** [DevExpress/testcafe#2098]
### Are you requesting a feature or reporting a bug?
bug

### What is the current behavior?
using t.maximizeWindow() on before fixture function will fail with 
`TypeError: t.maximizeWindow is not a function`

### What is the expected behavior?
It should maximizeWindow before each test

### How would you reproduce the current behavior (if this is a bug)?
put t.maximizeWindow inside before function

* operating system: official latest testcafe docker.

Actually my goal is the maximizeWindow before each test, because this is the only way I can make screenshots work on the docker image. 
if there is another place to put the maximizeWindow if I want all the tests to be maximized it'll be also a good solution for me.

**Comment by AlexanderMoskovkin** [comment]
Hi @shaikatz,

It seems you use the [fixture hook](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#fixture-hooks) `fixture.before`. Fixture hooks are executed between test runs and do not have access to the tested page. Use them to perform server-side operations like preparing the server that hosts the tested app.
Use the [test hook](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#test-hooks) `fixture.beforeEach` to maximize window before each test.

**Comment by shaikatz** [comment]
It'll add alot of boilerplate code to my tests, there is a way to maximizeWindow for all the tests? or another solution to take screenshot in the docker image that works?
