### ISSUE TITLE
Can't access cookie on localhost inside app

### ISSUE THREAD

**Issue by green-arrow** [DevExpress/testcafe#2103]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

Calling `document.cookie` returns an empty string within the application being tested.

### What is the expected behavior?

Calling `document.cookie` returns all cookies on `localhost`.

### How would you reproduce the current behavior (if this is a bug)?

Our situation is a little unique in that we have our login page on a separate subdomain from the app we're testing. Upon logging in, the API returns an `XSRF-TOKEN` cookie set to the root domain (for this case, `localhost`). The application then reads `document.cookie` to inject the token into future request headers.

Sample response header:

```
Set-Cookie:XSRF-TOKEN=<some token>; Domain=localhost; Path=/
```

This works fine in our deployed environment, where we have `www.ourapp.com` and `my.ourapp.com` domains, and the cookie specifies `.ourapp.com` as the domain for the `XSRF-TOKEN` cookie. This only occurs on localhost. The two application run on separate ports on localhost, one on port 8080 and one on 3000.

### Specify your

* operating system: macOS Sierra
* testcafe version: 0.18.6
* node.js version: 8.9.4

Please let me know if you need any additional details. As a temporary measure we are disabling CSRF protection locally, but this is not a long term solution for us unfortunately.

Thanks!

**Comment by miherlosev** [comment]
Hi @green-arrow 
Please, describe in more detail how you do this:
> Calling document.cookie returns an empty string within the application being tested.

Did you write a `ClientFunction` that returns `document.cookie`? Or you just call `document.cookie` in DevTools Console?

**Comment by green-arrow** [comment]
@miherlosev - The `document.cookie` call is within the actual application being tested. The app gets the `XSRF-TOKEN` cookie to set it as a header on other calls to our API when creating / modifying resources.

**Comment by miherlosev** [comment]
Ok, I understand you. We need additional time to reproduce the problem.
When it is done, I'll notify you about the result.

**Comment by green-arrow** [comment]
Thanks for looking into this!

**Comment by miherlosev** [comment]
We found the problem looks like the one described above.
See the separate issue in our proxy repository - https://github.com/DevExpress/testcafe-hammerhead/issues/1491

**Comment by green-arrow** [comment]
Thanks for the investigation! I’ll close this issue since it’s tracked in the other repo.
