### ISSUE TITLE
 Client Certificate Authentication

### ISSUE THREAD

**Issue by snowl** [DevExpress/testcafe#2104]
### Are you requesting a feature or reporting a bug?

Requesting a feature

### What is the current behavior?

Connecting to a website that uses client certificate authentication doesn't authenticate the user (or even show the prompt for the client certificate authentication).

### What is the expected behavior?

You should be able to connect to a server that uses client certificate authentication (either by specifying a certificate to load within the test, like HTTP Authentication, or at least showing the prompt to the user).

### How would you reproduce the current behavior (if this is a bug)?

Connect to any server that requires client certificate authentication. The browser will not show any prompts to select the user certificate to use, and all requests will show as a 403 through hammerhead.

### Specify your

* operating system: Fedora 24
* testcafe version: 0.18.6
* node.js version: 8.9.4

**Comment by miherlosev** [comment]
Hi @snowl 
Thanks for your proposal.
When the [Request Hooks Feature](https://github.com/DevExpress/testcafe/issues/1341) will be implemented, it will be possible to use Client Sertificate Autentification in tests. I'll create an example.

For myself: [the detailed article](https://engineering.circle.com/https-authorized-certs-with-node-js-315e548354a2) about 'Client Sertificate Autentification' in nodejs.

**Comment by BobLuursema** [comment]
+1

**Comment by snowl** [comment]
Hi @miherlosev,

Since request hooks has been merged into the alpha and you have added docs for Request Hooks (#2309), are you able to add documentation to enable Client Certificate Authentication within the docs as well?

Thanks
