### ISSUE TITLE
Can't interact with websites that require CSRF Tokens

### ISSUE THREAD

**Issue by bramroop** [DevExpress/testcafe#2106]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

Interaction is blocked on certain websites that require CSRF Tokens (website warns that cookies need to be enabled before you can submit forms)

### What is the expected behavior?

Interactions on such websites should be allowed even through testcafe

### How would you reproduce the current behavior (if this is a bug)?

Use testcafe to try to submit a form (eg, try to login to the website below) by executing
`testcafe chrome <test_file>`

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://mypharmacy.shoppersdrugmart.ca/en/login

Test code

```js
import { Selector } from 'testcafe';

const url = 'https://mypharmacy.shoppersdrugmart.ca/en/login';

fixture `Login`
    .page(url);

test('Login', async t => {

    await t
        .typeText(Selector('[name="email"]'), 'test@test.com')
        .typeText(Selector('[name="password"]'), 'password')
        .click(Selector('[value="Continue"]'))

    const pageHeader = await Selector('.notification-bar__text');

    // Obtain the text of the article header
    let headerText = await pageHeader.innerText;
    console.log("Actual header text = " + headerText)

    await t.expect(headerText).eql('The email and/or password you entered are not correct.')
});

```

### Specify your

* operating system: macOS Sierra  10.12.4
* testcafe version: 0.18.5
* node.js version: v7.7.1

**Comment by LavrovArtem** [comment]
Hi @bramroop,
I've reproduced your problem on the `0.18.5` version of Testcafe. On the last version problem is missed. Could you please update version to `0.18.6`?

**Comment by bramroop** [comment]
Hi @LavrovArtem thanks for your help. Unfortunately I'm still getting the same issue even after upgrading to v0.18.6

```
$ testcafe --version
0.18.6
$ testcafe chrome testcafe_test.js 
 Running tests in:
 - Chrome 64.0.3282 / Mac OS X 10.12.4

 Login
Actual header text = Please enable cookies to continue.
 ✖ Login

   1) AssertionError: expected 'Please enable cookies to continue.' to deeply equal 'The email and/or password you entered are not correct.'

      Browser: Chrome 64.0.3282 / Mac OS X 10.12.4

         16 |
         17 |    // Obtain the text of the article header
         18 |    let headerText = await pageHeader.innerText;
         19 |    console.log("Actual header text = " + headerText)
         20 |
       > 21 |    await t.expect(headerText).eql('The email and/or password you entered are not correct.')
         22 |});
         23 |

         at <anonymous> (testcafe_test.js:21:32)



 1/1 failed (5s)
```

Is there any other difference in the way we're running things that you can think of that might be causing the issue?

Thanks again

**Comment by AlexanderMoskovkin** [comment]
Hi @bramroop,

It's seem I can reproduce the issue on my side. I run it 6 times. It was failed 5 times but it was passed once. We'll investigate with @LavrovArtem why it happens

**Comment by LavrovArtem** [comment]
I've reproduced the issue and created a separate [issue](https://github.com/DevExpress/testcafe-hammerhead/issues/1486) in our proxy server repo.

**Comment by AlexanderMoskovkin** [comment]
Great! Let's keep this issue opened to track the progress.

**Comment by shiveshyadav** [comment]
I am facing similar issue for one of our application :  
testcafe --version 0.18.6  
Chrome 63.0.3239 
Windows 7.0.0  
We are not able to interact with website , it continuously showing loading without error. I have checked proxy and firewall as well for another application on same network it is working fine.

**Comment by LavrovArtem** [comment]
Hi @SolaTest,
I'd like you to have a look at forum thread by link below.

https://testcafe-discuss.devexpress.com/t/testcafe-not-always-catching-requests-from-browser/818/3?u=lavrovartem

**Comment by vigneshwar-v** [comment]
Anything on this??

**Comment by SolaTest** [comment]
@LavrovArtem All right, that post says image requests are not proxied.  That's unfortunate in our case, as we serve some of our images behind authentication, and have not implemented a separate CSRF pathway for those.  We can work around it, but it would be better if there were at least an option to just let image requests go through the same pathway.  Is there a ticket for this?  Or were there actually measured performance issues with that approach?

**Comment by LavrovArtem** [comment]
Hi @SolaTest 
> At this point, you cannot turn off this behavior. 
This feature will appear after the implementation of the https://github.com/DevExpress/testcafe/issues/1341 issue. 
You can track the issue to stay informed.

https://testcafe-discuss.devexpress.com/t/testcafe-not-always-catching-requests-from-browser/818/5?u=lavrovartem

**Comment by miherlosev** [comment]
@bramroop @vigneshwar-v @shiveshyadav @SolaTest

The cause of the problem is described in DevExpress/testcafe-hammerhead#1486. Track it to stay informed about our progress.

**Comment by AndreyBelym** [comment]
Hi @bramroop @SolaTest  @shiveshyadav, thanks for sharing your problems. I close this because it's duplicated by https://github.com/DevExpress/testcafe-hammerhead/issues/1486. You can use https://github.com/DevExpress/testcafe-hammerhead/issues/1486 to track the progress in resolving this issue, and I will inform you when a fix is available on NPM.
