### ISSUE TITLE
Homepage- make the second step easier to implement

### ISSUE THREAD

**Issue by vzaidman** [DevExpress/testcafe#2108]
### Are you requesting a feature or reporting a bug?
Requesting an enhancement.

### What is the current behavior?
Currently on the second stage it just says "Write your first test" and it shows this image:

![image](https://user-images.githubusercontent.com/5188459/35959227-63885c14-0cad-11e8-9d2d-c7aed103fdc9.png)

### What is the expected behavior?
I expected it to be a copy-pastable text so I can copy it to a newly created file and immediately run it.

**Comment by Nuarat** [comment]
Sounds cool, thanks for the idea! I'll work on that.

**Comment by AlexanderMoskovkin** [comment]
Done!
![image](https://user-images.githubusercontent.com/12047804/38998962-60ff10c2-43f9-11e8-957d-fa3f23d3b5f4.png)
