### ISSUE TITLE
Let' unify errors.

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#211]
Currently we have `Error` objects if we `throw` and plain strings in `error` events. This may cause a confusion. Let's simplify things and always use `Error`

**Comment by inikulin** [comment]
@DevExpress/testcafe Can someone else take care of this?

**Comment by AndreyBelym** [comment]
Ok, I'll do it.

сб, 5 дек. 2015, 2:55, Ivan Nikulin <notifications@github.com>:

**Comment by inikulin** [comment]
@AndreyBelym thanks!

**Comment by AndreyBelym** [comment]
I'm working on it.
