### ISSUE TITLE
Docker image / SW WebGL support

### ISSUE THREAD

**Issue by sommcz** [DevExpress/testcafe#2116]
### Are you requesting a feature or reporting a bug?
bug?

### What is the current behavior?
WebGL is disabled by default (in chromium and firefox browsers in testcafe docker)

### What is the expected behavior?
WebGL is enabled by default or there is possibility to enable/disable it

### How would you reproduce the current behavior (if this is a bug)?
Run following test with docker command:
`docker run -v c:\MyPath\Tests:/tests -it testcafe/testcafe "chromium --no-sandbox" /tests/test1.ts -S -s /tests/screenshots`

```typescript
fixture(`Getting Started`)
		.page(`https://browserleaks.com/webgl`);

test('My first test', async t => {
	await t.takeScreenshot();
});
```

See created screenshot:
![image](https://user-images.githubusercontent.com/20799785/36075257-ac3502c2-0f4c-11e8-8dbf-a371539bbe30.png)

I tried real app with WebGL component (mapbox-gl) also and it fails with WebGL init js error.

As there is not chrome://settings etc. available within testcafe fixtures, there is no posibility to control webgl settings.

Thank you for any help.

### Specify your

* operating system: Windows 10 + Docker version 17.12.0-ce, build c97c6d6
* testcafe version: 0.18.6
* node.js version: used from testcafes docker container

**Comment by sommcz** [comment]
After some experiments, there is no sw gl renderers in the docker image (osmesa or swiftshader).

WebGL works with osmesa installed!
![image](https://user-images.githubusercontent.com/20799785/36090657-7bf8a150-0fe1-11e8-9b56-d9a1f3c5758b.png)

Simple step to install osmesa in dockerfile:
RUN apk --no-cache add mesa-osmesa && \
  ln -s /usr/lib/libOSMesa.so.8 /usr/lib/chromium/libosmesa.so

After that, following command run testcafe with WebGL support:
/opt/testcafe/docker/testcafe-docker.sh 'chromium --no-sandbox --use-gl=osmesa' /tests/test1.ts

Please add official support for sw renderers to docker image.
Thank you

**Comment by AndreyBelym** [comment]
Hi @sommcz! Thank you for your research! I've found a way to enable WebGL in Firefox. I'll update Dockerfile and `dev` build on Docker Hub.

**Comment by sommcz** [comment]
I didn't test, but it will be fine to add support for swiftshader too. So developers can choose which one to use.

Alpine package: https://pkgs.alpinelinux.org/contents?branch=edge&name=mesa-gles&arch=x86_64&repo=main

Link path for Chromium: `/usr/lib/chromium/swiftshader/libGLESv2.so`

usage: `--use-gl=swiftshader`

**Comment by tombh** [comment]
I've also found that `testcafe 'chrome --headless --use-gl=swiftshader' test.js` works out of the box without any `.so` linking.

**Comment by mhoennig** [comment]
This issues seems to be fixed at least from the Testcafe Docker image 1.8.6 on. It worked out of the box for us after upgrading from 1.7.0. Important: I am talking about the Docker image, not just the Testcafe version.

**Comment by arubtsov** [comment]
@mhoennig Thank you for pointing this out.
