### ISSUE TITLE
Can you please tag master?  "stack-chain": "^2.0.0" is needed in a tag so cucumberjs 3/4 works with testcafe

### ISSUE THREAD

**Issue by ahungry** [DevExpress/testcafe#2129]
Cucumberjs 4 with testcafe master seems to work fine, however none of the npm published testcafe versions are on 2.0.0 stack-chain, and the old 1.x.x produces an incompatability with the cucumber required version.

A simple tag and publish would fix this and make life much easier for some of us (me) :)

**Comment by AlexanderMoskovkin** [comment]
Hi @ahungry,

We plan to publish a release the next week. But we can provide you with a `dev` build with updated `stack-chain` module today if you need it

**Comment by AlexanderMoskovkin** [comment]
Hi @ahungry, we've released the `0.19.0-alpha1` version with updated `stack-chain` module. You can already use it. And we're going to release `0.19.0` this week

**Comment by ahungry** [comment]
Thank you!
