### ISSUE TITLE
React "onChange" event doesn't fire

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#214]
Originally created by @arubtsov 

Paragraph element in following sample should reflect user input.

https://gist.github.com/arubtsov/a50fb167c38357de98d4
https://gist.github.com/arubtsov/9580b0e446922bdcb8fc

**Comment by AndreyBelym** [comment]
I'm working on it.

**Comment by AndreyBelym** [comment]
Depends on DevExpress/testcafe-hammerhead#318.

**Comment by AndreyBelym** [comment]
The issue in `hammerhead` was just fixed, so this issue can be closed after publishing a next version of `hammerhead`.

**Comment by inikulin** [comment]
@churkin Any plans for release?

**Comment by AndreyBelym** [comment]
Fixed in `testcafe-hammerhead@3.1.2`.
