### ISSUE TITLE
Dockerfile fails to create lib folder

### ISSUE THREAD

**Issue by lucidtech** [DevExpress/testcafe#2140]
### Are you requesting a feature or reporting a bug?

reporting a bug

### What is the current behavior?

git clone https://github.com/DevExpress/testcafe
cd testcafe
docker build -f ./docker/Dockerfile . -t mytag
docker run -v /mytests:/tests mytag firefox /tests/*.test.js

```
Error: Cannot find module '../lib/cli'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/testcafe/bin/testcafe.js:5:1)
```

docker run --rm -it --entrypoint /bin/sh mytag
ls
```
bin                docker             node_modules       package-lock.json  package.json
```

### What is the expected behavior?

tests run without error

docker run --rm -it --entrypoint /bin/sh testcafe/testcafe
ls
```
bin                docker             node_modules      lib       package-lock.json  package.json
```

### How would you reproduce the current behavior (if this is a bug)?

build the container directly from fresh clone of this repository

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:

OSX 10.13.3

* testcafe version:

master  285d5f3 

* node.js version:

as specified in the dockerfile

**Comment by AndreyBelym** [comment]
Hi @lucidtech, you should use the `docker-build` Gulp task for building the container.
```
npm i -g gulp
gulp docker-build
```

**Comment by lucidtech** [comment]
@AndreyBelym 
thanks for the response. sorry I missed the gulpfile.
