### ISSUE TITLE
Comparing two deeply nested objects should give proper error messages

### ISSUE THREAD

**Issue by snowl** [DevExpress/testcafe#2141]
### Are you requesting a feature or reporting a bug?
Requesting a feature

### What is the current behavior?
For the example object:

```
new Top({
        name: "bla",
        b: new Abc({
            description: "my description",
            c: [
                new Bcd({
                    name: "bcd-name",
                    description: "bcd-description",
                    id: 1,
                    d: [
                        new Cde({
                            name: "cde-name",
                            id: 1
                        })
                    ]
                })
            ]
        })
    })
```

When comparing a deeply nested object that fails, the output will be shown as so:
```
AssertionError: expected { Object (name, b) } to deeply equal {
      Object (name, b) }
```

And if you console.log the objects to diff them, you get output that isn't helpful:
```
{ name: 'bla',
  b: 
   { description: 'TeraText Schema Test Database',
     c: [ [Object] ] } }
```
instead of showing the whole object.

### What is the expected behavior?
The output should show better information, like so:
```
AssertionError: expected Object (b.c[0].d[0].id) -> 1 to deeply equal Object (b.c[0].d[0].id) -> 2
```

**Comment by Aaronius** [comment]
Yes, absolutely. Every time I use `eql` with objects I have to pass the following as a second argument to `eql` just to see what's going on:

```
`Expected settings: ${JSON.stringify(expected)} Actual settings: ${JSON.stringify(actualSettings)}`
```

**Comment by Aaronius** [comment]
Yes, absolutely. Every time I use `eql` with objects I have to pass the following as a second argument to `eql` just to see what's going on:

```
`Expected settings: ${JSON.stringify(expected)} Actual settings: ${JSON.stringify(actualSettings)}`
```

**Comment by miherlosev** [comment]
https://stackoverflow.com/questions/59722434/make-testcafe-show-an-object-diff

**Comment by wentwrong** [comment]
Since the `1.9.0` release, TestCafe shows the difference between an assertion's actual and expected values. For example, here's how the comparison of two deeply nested objects looks like:

<img src="https://user-images.githubusercontent.com/26363017/111433756-bf610d80-870f-11eb-8160-422a87002978.PNG" width="500" height="300">
