### ISSUE TITLE
Add example with using `takeElementScreenshot` action with `options` and without `path`

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#2149]
E.g., `await t.takeElementScreenshot(Selector('body').nth(0), { scrollTargetX: 100, scrollTargetY: 200 });`
Also may be add a note about it.

**Comment by VasilyStrelyaev** [comment]
Are you saying that the example after the images (https://github.com/DevExpress/testcafe/blob/master/docs/articles/documentation/test-api/actions/take-screenshot.md) is bad because it has a `path`? Or you don't like `crop`?

**Comment by VasilyStrelyaev** [comment]
Though, I should admit that crop dimensions are not quite realistic

**Comment by helen-dikareva** [comment]
It's not bad, I think it should be clear that I can use options without setting path:
`.takeElementScreenshot(Selector, path, options)` and `.takeElementScreenshot(Selector, options)` both possible

**Comment by VasilyStrelyaev** [comment]
fixed in https://github.com/DevExpress/testcafe/pull/2165
