### ISSUE TITLE
Support video recording of test running

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#2151]
## Proposal
`Last update 2/20/2018`
### What?

Provide an ability to create a video of a test run (in Chrome and Firefox (included headless) at start ). 

### Why?

Make it easier to identify why your test is failed. Especially it's actual for CI.

### How?

I guess the best way is make screenshots by using browser's api and make a video from them by using a tool like [ffmpeg](https://www.ffmpeg.org/).

### Questions to answer.

- Make one big video for the whole test run or create a separated video for every test? (I vote for the second case).
- Save a video for every test or just for failed test? (I vote for 'failed only')

### Additional requirements.

- It should be possible to configure video quality settings

### Things to do:

- [ ] - Investigate possibility to make screenshots in Firefox;
- [ ] - Investigate possibility to use `ffmpeg` or find other way;
- [ ] - Investigate how much machine resources it requires;
- [ ] - Figure out new API (all available options);
- [ ] - Implement;
- [ ] - Find ways how to save/get video for popular CI systems.

### Something else?

If anyone have some thoughts here feel free to comment

**Comment by ahungry** [comment]
We just started to test out something similar for grabbing screen videos of tests by launching a child_process.spawn of ffmpeg (and closing it) in Before() / After() hooks, naming it based on the SUT/scenario.  Unfortunately, it relies on being able to record the active x11 screen session (ie, won't work in headless mode).

Maybe it would work in headless if something like xvfb was used to simulate an x11 display?

Our setup is currently testcafe+cucumberjs, so we're relying on the cucumber Before/After hooks and just using testcafe as a driver+assertion framework.

**Comment by ahungry** [comment]
Another thought - for C.I. you could run the setup in non-headless within a docker container (therefore, no reliance on xvfb or headless mode), we did something similar with selenium docker images (just watch when needed by hooking to a vnc server the container was running).

**Comment by AndreyBelym** [comment]
Implementation of the feature is delayed due to unclear consequences of adding LGPL licensed FFMPEG to TestCafe dependencies. A lawyer consultation is needed.

**Comment by andrzej-kodify** [comment]
For anyone who is desperate to record video from Chrome (e.g. to troubleshoot headless CI) I've made this reporter https://www.npmjs.com/package/testcafe-reporter-chrome-recorder 

I wouldn't recommend to use it if there's an alternative but worked for me.

**Comment by AndreyBelym** [comment]
Closed by https://github.com/DevExpress/testcafe/commit/daa552b48863249036a6e435e3b6317dbba85669.
