### ISSUE TITLE
Support screenshot path pattern

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#2152]
## Proposal

related issues: #1602, #1651, #1974, #1975.
related PR: #2086

### What

Provide a capability to set a pattern for a screenshot path.

### API

- CLI API:

```
-p or --screenshot-path-pattern

testcafe chrome test.js -s <path> -p "${DATE}_${TIME}/test-${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.png"

Available options:
- ${DATE}
- ${TIME}
- ${TEST_INDEX}
- ${FILE_INDEX}
- ${QUARANTINE_ATTEMPT} --by default "1" (if you add it to the template but run tests without the `-q` option).

- ${FIXTURE}
- ${TEST}
- ${USERAGENT}
- ${BROWSER}
- ${BROWSER_VERSION}
- ${OS}
- ${OS_VERSION}
```

If TestCafe creates a screenshot when a test fails ([--screenshots-on-fails](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-s---screenshots-on-fails) option enabled) we just add the `-error` postfix to the filename.

- Programming API:

```js
runner.screenshot(path [, takeOnFails][, filePath])
// where filePath is a template string or a function that take the info and returns a value
```

- t.takeScreenshot, t.takeElementScreenshot
Should support file path pattern as well.

**Comment by miherlosev** [comment]
Implemented in https://github.com/DevExpress/testcafe/pull/2562
