### ISSUE TITLE
TestCafe.close() issue

### ISSUE THREAD

**Issue by georgiy-abbasov** [DevExpress/testcafe#216]
The process is still hanging after the gulp task is finished.

To reproduce this issue, create a gulp task that:
1. Creates TestCafe, a TestCafe runner instance and a browser connection.
2. Establishes the browser connection (for example, opens connection.url in the local browser)
3. Closes TestCafe.

After closing TestCafe and finishing the task, the node process is still hanging for about 2 minutes, which is equivalent to the HEARTBEAT_TIMEOUT value.

**Comment by inikulin** [comment]
We need to unref all timers used

**Comment by inikulin** [comment]
Just use unref for hearbeat timeouts (and other timeouts, if we have them): https://nodejs.org/api/timers.html#timers_unref @DevExpress/testcafe can someone take care of this?

**Comment by AlexanderMoskovkin** [comment]
I'll do
