### ISSUE TITLE
Feature Request: CLI flag to ignore unavailable browsers

### ISSUE THREAD

**Issue by justrhysism** [DevExpress/testcafe#2162]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
Errors when attempting to execute a browser which is unavailable.

### What is the expected behavior?
Not "expected behaviour", but my team work on both macOS and Windows. I'd like tests to run in Edge and Safari on the machines where it is available, but don't want to have to maintain separate commands for each. It would be nice if there was a cli flag to ignore browsers which aren't found.

### Specify your

* operating system: macOS & Windows
* testcafe version: 0.18.6
* node.js version: 8.9.4

**Comment by AndreyBelym** [comment]
Hi @justrhysism! Thank you for your proposal. It must be useful to have just one command for running tests on different platforms. We need to discuss the necessary API.
