### ISSUE TITLE
"boundTestRun" expected a test controller error when importing `t`

### ISSUE THREAD

**Issue by leegee** [DevExpress/testcafe#2163]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

`The "boundTestRun" option value is expected to be a test controller.`

### What is the expected behavior?

`TestCafe allows you to avoid passing the test controller to the method explicitly. Instead, you can simply import t to the page model file.` -- http://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#test-controller

### How would you reproduce the current behavior (if this is a bug)?

Please see the code below — just import `t` and use it to bind a test.

#### Provide the test code and the tested page URL (if applicable)

Test code

```js
const { Selector, t } = require( 'testcafe' );

export class FrontPage {
  constructor() { }

  async selectHierarchyOption( elName, text ) {
    console.log('***', t);
    const textRe = new RegExp('^\\s*' + text.replace(/\s+/, ' ') + '\\s*$', 'i');
    const selectSelector = Selector( 'select' )
      .withAttribute('name', elName)
      .with({
        visibilityCheck: true,
        boundTestRun: t,
      });
  }
}

```

### Specify your

* operating system: latest osx
* testcafe version: latest
* node.js version: carbon lts

**Comment by AndreyBelym** [comment]
Hi @leegee! I see `console.log('***', t);` in your test, could you please provide me the TestCafe output for this command, or the whole TestCafe report? Also, could you give me a code where `FrontPage` is instanced and `selectHierarchyOption` is actually called?

**Comment by leegee** [comment]
```
[954-e2e 15:44]$ 

 Running tests in:
 - HeadlessChrome 64.0.3282 / Mac OS X 10.13.3

 Feature: The hierachy selector
***  { click: [Function: fn],
  rightClick: [Function: fn],
  doubleClick: [Function: fn],
  hover: [Function: fn],
  drag: [Function: fn],
  dragToElement: [Function: fn],
  typeText: [Function: fn],
  selectText: [Function: fn],
  selectTextAreaContent: [Function: fn],
  selectEditableContent: [Function: fn],
  pressKey: [Function: fn],
  wait: [Function: fn],
  navigateTo: [Function: fn],
  setFilesToUpload: [Function: fn],
  clearUpload: [Function: fn],
  takeScreenshot: [Function: fn],
  resizeWindow: [Function: fn],
  resizeWindowToFitDevice: [Function: fn],
  maximizeWindow: [Function: fn],
  switchToIframe: [Function: fn],
  switchToMainWindow: [Function: fn],
  eval: [Function: fn],
  setNativeDialogHandler: [Function: fn],
  getNativeDialogHistory: [Function: fn],
  getBrowserConsoleMessages: [Function: fn],
  expect: [Function: fn],
  debug: [Function: fn],
  setTestSpeed: [Function: fn],
  setPageLoadTimeout: [Function: fn],
  useRole: [Function: fn] }
 ✖ Scenario: Load the grid with the same hierachy as mocked.

   1) The "boundTestRun" option value is expected to be a test controller.

      Browser: HeadlessChrome 64.0.3282 / Mac OS X 10.13.3

         11 |
         12 |  async selectOption( elName, text ) {
         13 |    console.log( '*** ', t );
         14 |    console.debug( 'selectOption [%s] [%s]', elName, text );
         15 |    const textRe = new RegExp( `^\\s*${ text.replace( /\s+/, ' ' ) }\\s*$`, 'i' );
       > 16 |    const selectSelector = Selector( 'select' )
         17 |      .withAttribute( 'name', elName )
         18 |      .with({
         19 |        visibilityCheck: true,
         20 |        boundTestRun: this.t,
         21 |      });

```

**Comment by leegee** [comment]
Using Testcafe with the Gherkin, btw: testcafe-gherkin

**Comment by AndreyBelym** [comment]
Looks like you misprinted `t` with `this.t` at line `20`. Could you please check that it is just `t` (without `this`) in your code?

**Comment by leegee** [comment]
The `this.t` is the imported `t` in that code — which is not stated by the code or me, sorry.

```js
const { Selector, t } = require( 'testcafe' );

export class Page {
  constructor( ) {
    this.t = t;
    this.INITIAL_TIMEOUT_MS = 1000 * 30;
  }

```

**Comment by AlexanderMoskovkin** [comment]
Hi @leegee,

In most cases TestCafe can determine test execution context automatically during test execution and you don't need to use the `boundTestRun` option. You can use the test context `t` from `import { t } from 'testcafe'`.

The `boundTestRun` option is used in edge cases that are described in the [topic](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/edge-cases-and-limitations.html#calling-selectors-from-nodejs-callbacks). But if you use it you should pass the test context `t` from the test (`test('Test name', async t => {})`) to determine required test context.

So, if your code doesn't work without the `boundTestRun` option pass the test context `t` to your page model from the test.

If you have some troubles with it you can provide us with a problematic code and we'll take a look at it.
