### ISSUE TITLE
Page navigation in page objects: how to await next page

### ISSUE THREAD

**Issue by rick-schubert** [DevExpress/testcafe#2171]
I am having trouble understanding the documentation in regards to the page model. 

## What I want to do
Similiar to the proposal in the Selenium Wiki ([with Java Example](https://github.com/SeleniumHQ/selenium/wiki/PageObjects)), I want to create page objects with a method in the constructor to wait for the page to be fully loaded. 

## Example
Let's consider the following test code: I instantiate my first page with testcafe in the constructor and then perform an action.

```javascript
test("I search for a product code", async (testcafe) => {
    const navBar = await new Navigation(testcafe)
    await navBar.search("ddd")
})
```

The Navigation page object looks like this:

```javascript
export default class Navigation {
    constructor(testcafe) {
        this.testcafe = testcafe
    }

    get searchInput() {
        return Selector(".SearchBar-queryInput")
    }

    async search(searchTerm) {
        await this.testcafe
            .typeText(this.searchInput, "high heels")
            .expect(this.searchInput.value)
            .eql(
                "high heels",
                "Navigation search input: The search term doesn't show on the input."
            )
        await this.testcafe.pressKey("enter")
        // THIS LINE IS THE BIG PROBLEM
        // Pressing Enter will lead me to the next page. But how do I properly
        // await the next page to be fully loaded?
        const plp = await new PLP(this.testcafe)
    }
}
```

The next page's page object is this:

```javascript
export default class PLP {
    constructor(testcafe) {
        this.testcafe = testcafe
        // This should throw an error: this element can't exist
        this.nonexisting = Selector(".thiselementcantexist")
    }

    async awaitFullyLoaded() {
        // This should throw an error: this element can't exist
        await Selector(".thiselementcantexist")
    }
}
```

How can I wait in the first class (Navigaton) for PLP to be fully loaded? Instantiating the next page's constructor with `const plp = await new PLP(this.testcafe)` does not cause testcafe to await the page elements. (Which is what I think [was outlined here](https://devexpress.github.io/testcafe/documentation/recipes/using-page-model.html) on the testcafe documentation actually.)
The below doesn't work either, it passes falsely.
```javascript
const plp = new PLP(this.testcafe)
await plp.awaitFullyLoaded()
```

Similiarly, even doing it straight and dirty in the search method doesn't work:

```javascript
await this.testcafe.pressKey("enter")
await Selector(".thiselementcantexist")
```

**Comment by AndreyBelym** [comment]
Hi @rick-schubert!

You can't mark a class constructor as an `async` function, it's a language-level limitation. So you could you a class constructor and an async method (you already tried it) and (optionally) static async method which calls constructor internally (IMHO it's a bit better) to create a page object and asynchronously wait for its loading:
```
class Page () {
    constructor () {
        // do stuff
    }
    
    async waitForLoading () {
   
    }

    static async create () {
        const page = new Page();
        await page.waitForLoading();
        return page;    
    }
}
```
For loading condition you could check if some element exists on the page. Checking element, which won't appear on the page, is useless.

**Comment by rick-schubert** [comment]
Hi @AndreyBelym , thank you very much for this answer! I haven't used `static` class methods before, your solutions looks like a really good trick though. Thank you!
