### ISSUE TITLE
Fixture doesn't accept template string variable

### ISSUE THREAD

**Issue by AhnpGit** [DevExpress/testcafe#2176]
### Are you requesting a feature or reporting a bug?

A bug

### What is the current behavior?

Fixture doesn't accept template string variable. TSlint says "TS2554: Expected 1 arguments, but got 2"

### What is the expected behavior?

It should accept template string variable like normal template string so TSlint shouldn't complain about it.

### How would you reproduce the current behavior (if this is a bug)?

- Create a TypeScript test file
- Define a `const testConditions = 'A test condition'`
- Write down fixture `This is a demo test with ${testConditions}`
- TSlint complains about the `${testConditions}`

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: 
**N.A.**

Test code
**N.A**

### Specify your

* operating system: Windows 10 x64
* testcafe version: 0.18.6
* node.js version: 8.9.4

**Comment by AndreyBelym** [comment]
Hi @AhnpGit! It's a flaw in TestCafe TS definitions, but you can just add parentheses around the string as a workaround:
```
import { Selector } from "testcafe";

const testConditions = "A test condition";

fixture(`This is a demo test with with ${testConditions}`)
    .page(`example.com`);

test("1", (t) => t.wait(5000));
```

**Comment by AhnpGit** [comment]
Hi @AndreyBelym, thank you for your reply. Will the TS definition be fixed in the upcoming release ?
