### ISSUE TITLE
How to check for a 404?

### ISSUE THREAD

**Issue by TauPan** [DevExpress/testcafe#2177]
### Are you requesting a feature or reporting a bug?
Clarification. Since I find nothing in the documentation it's probably a new feature.

### What is the current behavior?

`t.navigateTo('view/123/')` after the
object with id `123` has been deleted (with a 404 from my backend)
causes the test controller to become non-operational even if I catch the
exception:

```js
try {
  await t.
    navigateTo('view/123/');
} catch (err) {
    // is never caught
}

await t.expect(Selector('h1').innerText).eql('Page not found (404)').ok();
```

`TypeError: t.expect(...).eql(...).ok is not a function`

I get the following error

`TypeError: t.expect(...).eql(...).ok is not a function`

so some part of the chain probably returns something other than `t`.

### What is the expected behavior?
I'm trying to check if an object can be successfully deleted from the web by checking if its details view yields a 404 status page.

I'd like to catch other javascript errors on pages, so
`--skip-js-errors` is not what I want (globally).

It would be helpful if I could either inspect the error object or
check the 404-page. Currently I can't do either.

(What I currently do as a workaround is search for the deleted object
and check the number of results.)

### How would you reproduce the current behavior (if this is a bug)?
```js
try {
  await t.
    navigateTo('view/123/');
} catch (err) {
    // is never caught
}

await t.expect(Selector('h1').innerText).eql('Page not found (404)').ok();
```

### Specify your

* operating system: 4.4.114-42-default #1 SMP Tue Feb 6 10:58:10 UTC 2018 (b6ee9ae) x86_64 x86_64 x86_64 GNU/Linux
* testcafe version: 15.1.317522
* node.js version: 6.11.2

**Comment by helen-dikareva** [comment]
Hello @TauPan,
TestCafe doesn't raise any error during navigation to the page with status 404. It was done to allow checking a custom UI of page 404, for example. So you do not need the `try...catch` construction.

Please take a look at an example for `eql` assertion in our [docs](https://devexpress.github.io/testcafe/documentation/test-api/assertions/assertion-api.html#deep-equal). To check that `innerText` is equal to `Page not found (404)`, use the assertion below:
`await t.expect(Selector('h1').innerText).eql('Page not found (404)');`.

If you just want to check the page status, you can use the following code:
```js
import { ClientFunction } from 'testcafe';

fixture `fixture`
    .page `http://localhost/testcafe`;

test('test', async t => {
    const getRequestResult = ClientFunction(url => {
        return new Promise(resolve => {
            var xhr = new XMLHttpRequest();

            xhr.open('GET', url);

            xhr.onload = function () {
                resolve(xhr.status);
            };

            xhr.send(null);
        });
    });

    const status = await getRequestResult('http://localhost/testcafe/non-exist.html');

    await t.expect(status).eql(404);
})

```

**Comment by TauPan** [comment]
Oh dear! I wonder what made me think I should use `ok` after `eql`. I've used eql loads of times in my tests. It seems I was quite confused yesterday.

Thanks for clearing that up. Also thanks for the pointer how to check for the actual 404, however checking for the error page from the backend (django in my case) is of course a lot easier.
