### ISSUE TITLE
Screenshot of an element is cropped not correctly for some cases

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#2183]
Screenshot is cropped by 1 pixel more than it needs (top and left).
Full browser version: Google Chrome  64.0.3282.186

Element screenshot:
![Element screenshot](https://user-images.githubusercontent.com/4133518/36844241-f929d34a-1d62-11e8-91ff-524a41a0729c.png)

Text size settings:
![Text size settings](https://user-images.githubusercontent.com/4133518/36844290-22e84568-1d63-11e8-86d2-19b17c976259.png)

Test for reproduce
```js
fixture `0.19.0`
	.page('https://mail.ru');
	
test('1', async t => {
	await t.takeElementScreenshot('#mailbox\\:login');
});	
```

* testcafe version: 0.19.0-alpha3
* node.js version: 8.9.4

**Comment by AndreyBelym** [comment]
This issue must be fixed by https://github.com/DevExpress/testcafe/pull/2492.
