### ISSUE TITLE
Add configuration section with TypeScript in documentation

### ISSUE THREAD

**Issue by AhnpGit** [DevExpress/testcafe#2188]
### Are you requesting a feature or reporting a bug?

A documentation suggestion change

### What is the current behavior?

The doc doesn't have a section to configure with TypeScript

### What is the expected behavior?

The doc should have a section to configure with TypeScript. For example setting up type in `tsconfig.json`. After configuring types in `tsconfig.json`, the users can easily get code completion from IDE

### How would you reproduce the current behavior (if this is a bug)?

**N.A.**

#### Provide the test code and the tested page URL (if applicable)

**N.A.**

### Specify your

* operating system: MacOS High Sierra
* testcafe version: 0.19.0
* node.js version: 9.7.1

**Comment by AlexanderMoskovkin** [comment]
Hi @AhnpGit,

For now TestCafe doesn't support custom `tsconfig.json` files but we have planned to implement it (#1845).

> After configuring types in tsconfig.json, the users can easily get code completion from IDE

Do you mean code completion for TestCafe API? IDEs should enable it automatically when you write TestCafe tests (see [TypeScript Support](https://devexpress.github.io/testcafe/documentation/test-api/typescript-support.html#writing-tests-with-typescript)).
