### ISSUE TITLE
TestCafe Control Panel recording actions for vue.js application: e.toString is not a function

### ISSUE THREAD

**Issue by jasteuer** [DevExpress/testcafe#2190]
### Are you requesting a feature or reporting a bug?
I am reporting a bug.

![screenshot_20180304_185418](https://user-images.githubusercontent.com/33730307/36948603-8ff549ea-1fdd-11e8-8e52-28cfa4be30b9.png)

### What is the current behavior?
TestCafe Control Panel runs into problems if I try to record test actions of a vue.js application. In the browser console occurred following error (see screenshot):

    Uncaught TypeError: e.toString is not a function
        at Object.t.isStyleSheetInstance (hammerhead.js:56)
        at Object.condition (hammerhead.js:54)
        at R (hammerhead.js:54)
        at vue.js?7929ba6d39aa4465=https%3A|unpkg.com|28a49b15-35e5-41f3-bc76-c8768039707c|r|script:11
        at setAttr (vue.js?7929ba6d39aa4465=https%3A|unpkg.com|28a49b15-35e5-41f3-bc76-c8768039707c|r|script:11)
        at Array.updateAttrs (vue.js?7929ba6d39aa4465=https%3A|unpkg.com|28a49b15-35e5-41f3-bc76-c8768039707c|r|script:11)
        at O (hammerhead.js:54)
        at invokeCreateHooks (vue.js?7929ba6d39aa4465=https%3A|unpkg.com|28a49b15-35e5-41f3-bc76-c8768039707c|r|script:11)
        at createElm (vue.js?7929ba6d39aa4465=https%3A|unpkg.com|28a49b15-35e5-41f3-bc76-c8768039707c|r|script:11)
        at createChildren (vue.js?7929ba6d39aa4465=https%3A|unpkg.com|28a49b15-35e5-41f3-bc76-c8768039707c|r|script:11)

With this behavior the vue.js application is broken so that I can not record test actions.

### What is the expected behavior?
TestCafe Control Panel should not run into such problems.

### How would you reproduce the current behavior (if this is a bug)?
- start TestCafe Control Panel
- create a new fixture for some vue.js application
- try to record some test actions
- check the browser console for errors

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://vuejs.org/v2/examples/todomvc.html 
(other vue.js applications I want to test are broken too)

### Specify your
* browser: chrome 64, firefox 58
* operating system: Linux, x64
* testcafe version: DevExpressTestCafae-Linux64 15.1.3
* node.js version: 8.9.4

Hope you can fix this. Thank you!

**Comment by MarinaRukavitsyna** [comment]
Hello,
We provide two TestCafe versions: a paid version with a recorder and an open source version. According to your screenshot and description, you are using the first version. So, please use DevExpress Support Center to submit tickets regarding your version (https://www.devexpress.com/Support/Center/Question/Create) as we generally process paid TestCafe issues there to avoid mixing two different versions. The GitHub channel is intended for the open-source version.
As for the issue you encountered, I would like to note that we have already fixed it. So, please submit a ticket to DevExpress Support Center and request a hot fix.

**Comment by webia1** [comment]
Is there a hotfix now? Could you please update? Thank you,..

**Comment by ershwetabansal** [comment]
Is the fix available for the open source version?

**Comment by AndreyBelym** [comment]
Hi @ershwetabansal, could you please try the `testcafe@0.22.0`? We've recently fixed an issue with the `toString` method: https://github.com/DevExpress/testcafe-hammerhead/issues/1713

**Comment by ershwetabansal** [comment]
Thanks @AndreyBelym. I will try it tonight. Hope it works. I am planning to go for the paid version if I get past all the issues while testing vue js app.
