### ISSUE TITLE
Allow asynchronous test declarations

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#2191]
### Are you requesting a feature or reporting a bug?
Feature (https://testcafe-discuss.devexpress.com/t/896)

### What is the current behavior?
You can use conditions, loops and synchronous functions to declare tests:
```
if (os.windows) 
    test('Windows test', ...);

for (let i = 0; i < 10; i++)
    test(`Test ${i}`, ...);

function declareTest (feature) {
    test(`Testing ${feature}`, ...);
}

declareTest('yo!');
```

Declaring a test in a callback, in a Promise chain, or in an asynchronous function doesn't work:
```
// DO NOT WORK
setTimeout(() => {
     test('Test', ...);    
}, 0);

// DO NOT WORK
Promise
    .resolve(42)
    .then(val => test(`Test that the answer is ${val}`, ...));

// DO NOT WORK
(async () => {
     await doSmth();

     test('Test', ...);
})();
```
### What is the expected behavior?
Find a way to enable test declarations in callbacks, Promise chains, and async funcitons

### Specify your

* operating system: any
* testcafe version: 0.19.0
* node.js version: any

**Comment by AlexanderMoskovkin** [comment]
I doubt we'll implement this since it requires huge rework of the whole test compilation and running systems. We've discussed it in the #1948 issue
