### ISSUE TITLE
ExtJS menu items not clickable by TestCafe anymore (used to work for 0.17.2)

### ISSUE THREAD

**Issue by jschumme** [DevExpress/testcafe#2197]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

Menu items in Sencha ExtJS not clickable by TestCafe. It used to work for v. 0.17.2

### What is the expected behavior?

TestCafe should be able to click on menu items and buttons

#### Provide the test code and the tested page URL (if applicable)

Test code

```js
import { Selector } from 'testcafe';

fixture`Roundtrip fixture`
   .page('http://examples.sencha.com/extjs/6.5.1/examples/kitchensink/#tree-grid')
   
test('click excel button', async t => {
   await t
      .setPageLoadTimeout(10000)
      .click(Selector('.x-btn').withText('Export to ...'))
      .click(Selector('.x-menu-item').withText('Excel xlsx'))
      .wait(3000)
})
```

### Specify your

* operating system: Windows 10
* testcafe version: v 0.19.0
* node.js version: v 8.9.0

**Comment by aleks-pro** [comment]
Hello @jschumme ,

Thank you for the provided test code. I have reproduced the issue on my side. We will investigate it and update this thread as soon as we have any results.

**Comment by AlexKamaev** [comment]
Looks like it fails starting from the following commit 

> 09ea85815e7cf0ae5013ea9cd47ff35be4ec6266 Link without href but with tabIndex is focusable 

in testcafe-hammerhead repo

**Comment by miherlosev** [comment]
This bug is a result of fix the https://github.com/DevExpress/testcafe/issues/1803 issue.
Changes were make in the both repositories (testcafe and hammerhead).

**Comment by AlexKamaev** [comment]
fixed in testcafe-hammerhead https://github.com/DevExpress/testcafe-hammerhead/pull/1547
