### ISSUE TITLE
Add a .map function

### ISSUE THREAD

**Issue by dv297** [DevExpress/testcafe#2201]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
N/A

### What is the expected behavior?
Generic map function that allows you to map over a Selector. This could be useful with creating assertions that deal with predefined/ expected lists vs actual lists created by the DOM. Since there is already a .filter function, and people always talk about map/filter/reduce being together, this seems like a natural addition to the Selector API.

### How would you reproduce the current behavior (if this is a bug)?
N/A

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js
Selector('li').map((element) => element.innerText);
```

### Specify your

* operating system: Windows 10
* testcafe version: 0.18.1
* node.js version: 8.8.1

**Comment by kirovboris** [comment]
Hi @dv297,

Thanks for you proposal, it sounds reasonable.

We need to know what will be returned by `Selector` methods (a DOM node or something else). Obviously, we can't determine it in case of the `map` function. 
To implement these methods, we would have to rethink the internal `Selector` methods mechanism.
We'll discuss the possibility to do this in the future.

As a workaround, you can create a `ClientFunction`, e.g.:
```js
const getInnerTextArr = ClientFunciton((selector) => {
    return document.querySelectorAll(selector).map(el => el.innerText);
});

test('Test', async t => {
    await t.expect(getInnerTextArr('li')).eql(...);
});
```
/cc @AlexanderMoskovkin

**Comment by efleming969** [comment]
The suggested code won't work because NodeList does not support "map"

```javascript
const getInnerTextArr = ClientFunction( function ( selector ) {
    const values = []
    const elements = document.querySelectorAll( selector )

    for ( let i = 0; i < elements.length; i++ ) {
        values.push( elements[ i ].textContent )
    }

    return values
} )
```
