### ISSUE TITLE
selector help in testcafe-live

### ISSUE THREAD

**Issue by jianentrinsik** [DevExpress/testcafe#2208]
### Are you requesting a feature or reporting a bug?
feature

### What is the current behavior?
I have to manually inspect browser element to find and test out unique selectors

### What is the expected behavior?
I'd like to use the newest testcafe-live to click on any element on the webpage to show its suggested / preferred selectors. I'd like to test the selector out without re-run the test, meaning that I'd like testcafe-live to show me if the selector is uniquely success or not unique. (A good reference point is your competitor cypress's way of suggesting selectors)

### How would you reproduce the current behavior (if this is a bug)?
n/a

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: mac osx
* testcafe version: 0.19
* node.js version: 6

**Comment by AndreyBelym** [comment]
Hi @jianentrinsik!

We already have plans to allow execution of `ClientFunction`s and `Selector`s in the browser console. I've created an issue about it: https://github.com/DevExpress/testcafe-live/issues/14

BTW, you can easily generate unique CSS selector using Chrome DevTools. Just right-click on an element in the elements tree, and use the Copy menu:
![image](https://user-images.githubusercontent.com/4479386/37283108-df4fb482-2607-11e8-9c10-6a2425f2992f.png)

**Comment by jianentrinsik** [comment]
Thanks Andrey! Your team is doing awesome work, and testcafe is getting more fun to play with every release.

**Comment by AlexanderMoskovkin** [comment]
closed in favor of https://github.com/DevExpress/testcafe-live/issues/14
