### ISSUE TITLE
Cannot run test with Chrome headless

### ISSUE THREAD

**Issue by AhnpGit** [DevExpress/testcafe#2215]
### Are you requesting a feature or reporting a bug?

A bug

### What is the current behavior?

-  Run testcafe with chrome:headless and the tests failed because of `ERROR The HeadlessChrome 65.0.3325 / Windows 10.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.`
- When running with Chrome, I see error in the console
![image](https://user-images.githubusercontent.com/27772165/37412391-121dc4be-27a5-11e8-944d-d07658c0e241.png)

### What is the expected behavior?

Run testcafe with chrome:headless should not be hung

### How would you reproduce the current behavior (if this is a bug)?

- Install testcafe 0.19.1
- Create some tests and run with chrome:headless and the tests fail

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: **N.A.**

Test code

**N.A.**

### Specify your

* operating system: Windows 10 x64
* testcafe version: 0.19.1
* node.js version: 8.9.4

**Comment by AndreyBelym** [comment]
Hello @AhnpGit!

Unfortunately, I can't reproduce the issue. Try to run basic tests from https://github.com/DevExpress/testcafe/tree/master/examples/basic (you can download archive of the directory with [GitZip](http://kinolien.github.io/gitzip/)). If they fail in headless mode, rerun them some times to see if they fail after a specific test or just randomly. If basic tests pass, there is something in your site that causes the browser to hang. You can try to increase virtual window size in headless mode by using device emulation options. If emulation doesn't help, I'm afraid I will need access to your webpage for debugging.

**Comment by AndreyBelym** [comment]
After you have added a screenshot of the console, it looks like something is wrong with proxy settings. Could you provide me the command which you use to start tests?

**Comment by AhnpGit** [comment]
Hi @AndreyBelym ,

I think it is the issue with the network of my company. I put an extra option to testcafe cli to run on specific ports and it works well. Thank you for your quick response 👍 

Side question: does TestCafe have an option in cli that can read config from a json/js file ? I couldn't find it in the documentation. That would be nice because now the command to run testcafe for me is really long inside package.json

**Comment by AlexanderMoskovkin** [comment]
@AhnpGit, Glad to hear that the problem is resolved!

Now TestCafe doesn't support config files, it possible we'll think out it in future.
