### ISSUE TITLE
Add screenshots path from takeScreenshot\takeElementScreenshot actions into report

### ISSUE THREAD

**Issue by arubtsov** [DevExpress/testcafe#2216]
### Are you requesting a feature or reporting a bug?

Requesting a feature.

### What is the current behavior?

If `path` option is specified for one of takeScreenshot actions in test, then `testRunInfo` parameter of `reportTestDone` reporter plugin's method receives only base screenshots path (specified in `screenshots` method of test runner).

### What is the expected behavior?

Information about screenshots locations could be obtained from `testRunInfo`.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by MargaritaLoseva** [comment]
I'm working on this
