### ISSUE TITLE
Test duration time with console.log

### ISSUE THREAD

**Issue by kaaanshady** [DevExpress/testcafe#2217]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
There is a durationMs with json reporter but I would like to see test durations on console.

### What is the expected behavior?
I would like to see test durations on console with console.log

```
Test Name: {test name}
Duration: xxx seconds
```

**Comment by AlexanderMoskovkin** [comment]
Hi @kaaanshady,

TestCafe built-in reporters don't output duration of each test but TestCafe allows to create a custom reporter that outputs test results in a required format. See the [Reporter Plugin](https://devexpress.github.io/testcafe/documentation/extending-testcafe/reporter-plugin/) documentation section for details.

Additionally TestCafe allows to use multiple reporters in a single test run (see the [--reporter](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-r-namefile---reporter-namefile) option). You can output results from your custom reporter to the console and save the json report to the file.
