### ISSUE TITLE
Testcafe can't establish connection with headless browser when running in CI (Jenkins)

### ISSUE THREAD

**Issue by operatino** [DevExpress/testcafe#2218]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

The test running can't connect to browser when executed in Jenkins (dockerized slaves with chrome/firefox installed from apt, extended from `jenkinsci/jnlp-slave:latest`).

Error I get after long timeout since test start:

```
$ npm run testcafe -- chrome:headless tests/accommodation/adLinks.js --debug-mode

> functional-tests-testcafe@1.0.0 testcafe /path/functional-tests-testcafe
> testcafe "chrome:headless" "tests/accommodation/adLinks.js" "--debug-mode"

ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
```

### What is the expected behavior?

Test expected to be functional same as locally (working with same headless browser), and as in local docker env (based on circleci/node:8-browsers).

### How would you reproduce the current behavior (if this is a bug)?

By running test suite in Jenkins.

### Specify your

* operating system: Debian 9
* testcafe version: 0.19.0
* node.js version: 8.10.0

__

I understand the issue could be very specific to our setup, but is there a way to enable some verbose mode or extra logging, to understand where to dig?

UPD

Tried running phantomjs within same build, that start, so looks that browser runner is the issue.

**Comment by operatino** [comment]
Managed to get an example Docker image setup, in which testcafe hangs with mentioned above error.

```
FROM jenkinsci/jnlp-slave:latest

USER root

# Install packages
RUN apt-get update -y && \
    apt-get install -y \
    libseccomp2 python-openssl wget \
    libxss1 libappindicator1 libindicator7 fonts-liberation xdg-utils lsb-release && \
    rm -rf /var/lib/apt/lists/*

# Install Chrome
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    dpkg -i google-chrome*.deb

ARG NODE_VERSION=8
ENV NODE_VERSION $NODE_VERSION

# Get NodeJS the distribution
RUN curl -sL https://deb.nodesource.com/setup_$NODE_VERSION.x | bash -
RUN apt-get install -y nodejs build-essential

# Install yarn
RUN npm install yarn -g

# Set environment variables
ENV NODE_ENV production

# Create app directory
RUN mkdir -p /usr/local/app
RUN chmod -R ugo+rw /usr/local/app
WORKDIR /usr/local/app

# Install app dependencies
COPY ./package.json /usr/local/app/
COPY ./yarn.lock /usr/local/app/
RUN yarn install --production

# Bundle app source
COPY . /usr/local/app
RUN npm run testcafe -- chrome:headless tests/accommodation/adLinks.js
```

**Comment by AndreyBelym** [comment]
Hi @operatino!

Unfortunately, there is no debug mode that will help you with the issue. Likely you have two problems in your setup:

1. You don't have all required dependencies for headless Chrome (look at [this command](https://github.com/Googlechrome/puppeteer/issues/290#issuecomment-360542685) which installs them).

2. You should run Chrome with the `--no-sandbox` flag in unprivileged Docker mode as it is stated in [the docs](https://devexpress.github.io/testcafe/documentation/using-testcafe/installing-testcafe.html#using-testcafe-docker-image).

**Comment by operatino** [comment]
Thanks a lot, that solved the isssue. Beek googling a lot, sad that I've missed that thread, would be nice to have it somewhere in docs.

Here's updated Dockerfile for future:

```
FROM jenkinsci/jnlp-slave:latest

USER root

# Install packages
RUN apt-get update -y && \
    apt-get install -y \
    libseccomp2 python-openssl \
    gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget && \
    rm -rf /var/lib/apt/lists/*

# Install Chrome
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    dpkg -i google-chrome*.deb

ARG NODE_VERSION=8
ENV NODE_VERSION $NODE_VERSION

# Get NodeJS the distribution
RUN curl -sL https://deb.nodesource.com/setup_$NODE_VERSION.x | bash -
RUN apt-get install -y nodejs build-essential

# Install yarn
RUN npm install yarn -g

# Set environment variables
ENV NODE_ENV production

# Create app directory
RUN mkdir -p /usr/local/app
RUN chmod -R ugo+rw /usr/local/app
WORKDIR /usr/local/app

# Install app dependencies
COPY ./package.json /usr/local/app/
COPY ./yarn.lock /usr/local/app/
RUN yarn install --production

# Bundle app source
COPY . /usr/local/app
RUN npm run test:headless
```

**Comment by davidarce** [comment]
I'll try with the flag --no-sandbox and not working...
