### ISSUE TITLE
Testcafe doesn't work with privately scoped providers

### ISSUE THREAD

**Issue by bsmithb2** [DevExpress/testcafe#2221]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
When publishing a browser provider to a private npm repository under a scope (@bsmithb2 for example) the installed provider fails to be detected by the browser provider pool. 

### What is the expected behavior?
That you can install the browser provider from a private npm repo in a scope and the browser provider is detected. 

### How would you reproduce the current behavior (if this is a bug)?
Create a demo browser provider. Publish to a private repo under a scope. Install the private, scoped npm package. Run testcafe -b. Note the provider is not detected. 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Windows
* testcafe version: 0.18.6
* node.js version: 9.8.0

**Comment by AndreyBelym** [comment]
Hi @bsmithb2,

You are right, currently we don't support installing browser providers from scoped packages. Also please note that `testcafe -b` command outputs a list of locally installed browsers, if no provider name is specified. Currently you can't get a list of available providers.

**Comment by bsmithb2** [comment]
Will you accept a PR that allows them?

**Comment by AndreyBelym** [comment]
Of course, your contribution will be welcome!

**Comment by bsmithb2** [comment]
Hi @AndreyBelym - my plan is to modify the pool.js file in the server to allow the following command
testcafe @private/testcafe-browser-provider-package by adding a regex where the require statement is currently trying to blindly load. 

My initial implementation test scenario is: https://github.com/bsmithb2/testcafe/blob/master/test/server/browser-provider-module-loader-test.js

Thoughts? Think it will work?

I'm blocked on how to execute testcafe locally from the built files in order to test. Any thoughts on that process? I'd like to end to end test it against my privately scoped package in my internal repo.  

Thanks,

Bradley

**Comment by AndreyBelym** [comment]
Hi @bsmithb2, I think you have already figured it by yourself, but just to be sure:
1. Run `gulp build` or `gulp fast-build` (build without linting)
2. Run `node ./bin/testcafe.js chrome tests.js -S ...`
