### ISSUE TITLE
Using fixture.beforeEach/fixture.afterEach and test.before/test.after at the same time

### ISSUE THREAD

**Issue by Lukas-Kullmann** [DevExpress/testcafe#2230]
### Are you requesting a feature or reporting a bug?

Feature request

### What is the current behavior?

> If `test.before` or `test.after` is specified, it overrides the corresponding `fixture.beforeEach` and `fixture.afterEach` hook, so that the latter are not executed.

Taken from the [documentation](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#test-hooks).

### What is the expected behavior?

First, `fixture.beforeEach` is executed, then `test.before` is executed.
In case of teardown, `test.after` is executed first, then `fixture.afterEach` is executed.

### Usecase

Having multiple tests in the same common initialization logic, e.g. logging into a page.
But each individual test has it's own, specific initialization logic as well.
Maybe in the different tests, the website needs to be prepared slightly differently.
I think duplicating the code for every `test.before` is not en elegant solution.
In my opinion, `fixture.before`, `fixture.beforeEach` and `test.before` should all be called before a test starts.

I imagine it like this:

- `fixture.before` called
- test 1:
  - `fixture.beforeEach` called
  - `test.before` called
  - `test` executed
  - `test.after` called
  - `fixture.afterEach` called
- test 2:
  - `fixture.beforeEach` called
  - `test.before` called
  - `test` executed
  - `test.after` called
  - `fixture.afterEach` called
- continue for test 3, 4, ...
- `fixture.after` called

**Comment by bisubus** [comment]
I had similar difficulty, but it seems to me that the only reason why test.before and test.after can be used is that they cancel beforeEach and afterEach. If they shouldn't cancel them then this
```
test(async t => { /* test */ })
.before(async t => { /* before */ })
.after(async => { /* after */ })
```
is basically same thing as
```
test(async t => {
  try {
    /* before */
    /* test */
  } finally {
    /* after */
  }
})
```

**Comment by timnederhoff** [comment]
I think it's nice to have an override hook like this. With your proposed solution, the `.beforeEach()` hook can't be overwritten. The method for adding additional before and after using in the test itself like @bisubus mentioned looks fine to me.

**Comment by gilmeir-curv** [comment]
> I think it's nice to have an override hook like this. With your proposed solution, the `.beforeEach()` hook can't be overwritten. The method for adding additional before and after using in the test itself like @bisubus mentioned looks fine to me.

I think overriding is counter intuitive.
In my case it confused my that a test's `before` overrides a fixture's `beforeEach`, eventually I found that in the docs.

If `beforeEach` on fixture level doesn't apply to all the fixture's tests then move it down to the tests' `before` hook.
Since testcafe doesn't support nested fixtures, you can't add a `beforeEach` to a subset of tests, which is a bummer.

The order @Lukas-Kullmann suggested is similar to [jest](https://jestjs.io/docs/en/setup-teardown#scoping), only I added a `test.beforeEach`:

(Fixture start)
`fixture.before`

(Test start)
`fixture.beforeEach`
`test.beforeEach`
... execute test ...
`test.afterEach`
`fixture.afterEach`
(Test end)

`fixture.after`
(Fixture end)

**Comment by antunesfabio** [comment]
I also agree that overriding is counter-intuitive as it differs from how most test runners work.

Let's say that I have a set of 7 tests. I have the same code that I want to be executed before each test, and I have some more specific code that I want to run before just a few tests.

I expected to be executed like:
`fixture.beforeEach`
`test.before`
`test`

The current implementation of overriding the beforeEach makes us having to duplicate code in test.before of each test which is quite inelegant and against best practices.
The other option would be moving the code to a new function, but I would still need to call it in all seven test.before.

**Comment by miherlosev** [comment]
Hi folks,

We decided to preserve the current test execution order. To achieve your goal, please use the approach from [https://github.com/DevExpress/testcafe/issues/2230#issuecomment-1156276884](https://github.com/DevExpress/testcafe/issues/2230#issuecomment-1156276884)
