### ISSUE TITLE
Feature: Test Failure Hook

### ISSUE THREAD

**Issue by justrhysism** [DevExpress/testcafe#2231]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
None (that I'm aware of)

### What is the requested behavior?
A hook which executes only on a test failure which provides some data detailing the failure (could potentially pass through the internal model).

I think it should execute on all failures (e.g. still execute on failures in _quarantine_ mode).

### Why
I'd like to be able to set up a some custom logging and notifications on test failures. For my team, often the failures are the result of a systems integration failure, but we require some logging to join associate the error logs on the system integration level.

**Comment by Artem-Babich** [comment]
Hi @justrhysism,

According to your description, [a custom reporter](https://testcafe.io/documentation/402810/guides/extend-testcafe/reporter-plugin) can be used to accomplish this task. You can use it as an additional reporter in your test run. Here is an example of what this reporter might look like:

```js
module.exports = function CustomReporter () {
    return {
        async reportTaskStart (startTime, userAgents, testCount) {},

        async reportFixtureStart (name, path, meta) {
            this.currentFixture = { name, path, meta };
        },

        async reportTestDone (name, testRunInfo, meta) {
            const {
                      path: fixturePath,
                      name: fixtureName,
                      meta: fixtureMeta,
                  } = this.currentFixture;

            const errors      = testRunInfo.errs;
            const warnings    = testRunInfo.warnings;
            const quarantine  = testRunInfo.quarantine;
            const browsers    = testRunInfo.browsers;
            const reportData  = testRunInfo.reportData;
            const hasErrors   = !!errors.length;
            const hasWarnings = !!warnings.length;
            const result      = hasErrors ? `failed` : `passed`;


            if (hasErrors) {
                errors.forEach(error => {
                    const formattedError = this.formatError(error);

                    //Do something
                });
            }

            if (hasWarnings) {
                warnings.forEach(warning => {
                    // Do something
                });
            }

            if (quarantine) {
                for (const browser of browsers) {
                    const { quarantineAttemptsTestRunIds, name } = browser;
                    const attempts                               = quarantineAttemptsTestRunIds.map(id => quarantine[id]);

                    for (const attempt of attempts) {
                        const { passed, errors } = attempt;
                        const formattedErrors    = errors.map(err => this.formatError(err));
                        // Do something
                    }
                }
            }
        },

        async reportTaskDone () {},
    };
};

```

```js
// .testcaferc.js
const customReporter = require('./custom-reporter.js');

module.exports = {
    reporter: ['spec', customReporter],
};
```

If this approach is not suitable for you, feel free to reopen this issue and share more details about your usage scenario:
What kind of information do you want to receive in this hook?
What kind of logic are you planning to execute inside this hook?
You can also share any other details you think might be helpful.
