### ISSUE TITLE
Load external scripts to browser

### ISSUE THREAD

**Issue by bisubus** [DevExpress/testcafe#2234]
### Are you requesting a feature or reporting a bug?

Feature

### What is the current behavior?

Currently the framework doesn't provide ways to push external scripts and other assets to browser.

Current supposed method to load UMD on client side is rather hacky, with ClientFunction or t.eval:
```
const mockdateUMD = fs.readFileSync(require.resolve('mockdate'), 'utf8');
const mockdateLoader = ClientFunction(
  () => { new Function(mockdateUMD)(); },
  { dependencies: { mockdateUMD } }
);
```
And there's no control when it is loaded; the earliest point in beforeEach can be too late (it likely happens after document `ready`).

 It appears that there is undocumented `embeddingOptions` runner method, but it seems that it only allows to serve an asset and is defined globally, not per fixture:
```
runner.embeddingOptions({
  assets: [{
    path: '/mockdate.js',
    info: { content: mockdateUMD, contentType: 'application/x-javascript' }
  }]
})...
```
And the way it can be injected to current test likely belongs to internal API:
```
.beforeEach(async t => { t.testRun.injectable.scripts.push('/mockdate.js') })
```
### What is the expected behavior?

Local or CDN scripts and assets can be specified in runner or fixture configuration. The place where they are pushed (`head` or `body`) could also provide necessary flexibility.

**Comment by AlexanderMoskovkin** [comment]
Hi @bisubus ,

We have a similar suggestion in the #1739 issue. It seems it should feet your needs. If so you can vote for it by adding your 👍 and close this issue as duplicate. Personally I consider this feature important, so I guess we'll try to implement it in one of the next releases.

> And there's no control when it is loaded; the earliest point in beforeEach can be too late (it likely happens after document ready).

You are right, it is executed after document ready. In some cases it can be too late. So while the feature is not implemented you can use mentioned workarounds.
