### ISSUE TITLE
Input typing on Android devices does not reflect actual behavior of Android keyboard

### ISSUE THREAD

**Issue by palpatine1991** [DevExpress/testcafe#2236]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Using Android device keyboard, the input does not get `keyPress` event but some other event. On the other hand TestCafe fires the `keyPress` event. 

### What is the expected behavior?
Writing to input using TestCafe should fire the same set of events as the manual tests.

### How would you reproduce the current behavior (if this is a bug)?
Use Android device and try to write something to native HTML input. Put the event handlers of `keyPress` or `keyDown` events on this input and watch the difference between manual test and TestCafe test.

### Specify your

* operating system: Android
* testcafe version: 0.19.0
* node.js version: 8.9.4

**Comment by AlexKamaev** [comment]
Hi, I was able to reproduce the described behavior so I've marked the issue as a bug.
