### ISSUE TITLE
resetting indexedDB between test-runs

### ISSUE THREAD

**Issue by phoet** [DevExpress/testcafe#2240]
### Are you requesting a feature or reporting a bug?

as of the latest firebase release (4.12.0) they keep track of the login-state in the indexdDB.

because of this all my testcafe tests fail as they expect a login before checking the app.

### What is the current behavior?

indexDB keeps state

### What is the expected behavior?

indexDB is cleared

### How would you reproduce the current behavior (if this is a bug)?

```
app.auth().onAuthStateChanged((user) => {
  console.log(user);
}
```

#### Provide the test code and the tested page URL (if applicable)

the workaround i'm doing right now looks like this.

```js
fixture(`Index page`)
  .page('http://localhost:8080/')
  .afterEach(async t => {
    await t.eval(() => indexedDB.deleteDatabase('firebaseLocalStorageDb'));
  })
```

mainly leaving this here becaus i could not find anything about this change on the web.

**Comment by miherlosev** [comment]
Hi @phoet 
Thanks for your proposal. We have the separate issue [testcafe-hammerhead/1429](https://github.com/DevExpress/testcafe-hammerhead/issues/1429) in our proxy repository for this case .
Track [testcafe-hammerhead/1429](https://github.com/DevExpress/testcafe-hammerhead/issues/1429) to be notified about our progress.

**Comment by phoet** [comment]
@miherlosev ah great, thanks for redirecting me!
