### ISSUE TITLE
The selection will be not un-checked after injecting "esc"

### ISSUE THREAD

**Issue by hang-ren** [DevExpress/testcafe#2245]
### Are you requesting a feature or reporting a bug?
A bug

### What is the current behavior?

Test failed.

### What is the expected behavior?

Test passed and should be no error in console

### How would you reproduce the current behavior (if this is a bug)?

Run passed if manually

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

import { Selector } from 'testcafe';

const continueBtn = Selector('button.btn_continuebtn');
const closeWelcomeImg = Selector('img.closewelcome');
const drawRoom = Selector('#floorplannerToolbar > div:nth-child(1) > ul > li[data-toolbar-path="toolBar_create_room"]');
const drawRoom_1 = Selector('#floorplannerToolbar > div:nth-child(1) > ul > li[data-toolbar-path="toolBar_create_room"] > ul > li[data-toolbar-path="toolBar_create_room/toolBar_draw_room_1"]');
const to3D = Selector('div[class="fullScreen btn"]');
const closeCard = Selector('span.closecard');
const currentViewMode = Selector('div.viewspan');
const switchToPlanViewMode = Selector('li.viewModeDropdown > div > ul > li:nth-child(2)');
const switchToRCPViewMode = Selector('li.viewModeDropdown > div > ul > li:nth-child(3)');
const switchToConcealedMode = Selector('li.viewModeDropdown > div > ul > li:nth-child(4)');

fixture `View Mode`
   .page `https://ezhome-alpha-3d.shejijia.com/?brand=ezhome`

test('check_view_mode', async t => {
    /* Test View Mode */

    await t
        .maximizeWindow()
        .click(continueBtn)
        .click(closeWelcomeImg)
        .wait(2000)
        .hover(drawRoom)
        .wait(2000)
        .click(drawRoom_1)
        .wait(2000)
        .click('#editor2d', {offsetX: 960, offsetY: 400})
        .pressKey('esc')
        .wait(1000)
        //.click(closeCard)
        //.wait(2000)
        .expect(currentViewMode.innerText).eql('设计视图', 'The view mode is not right.')
        .click(currentViewMode)
        .wait(1000)
        .click(switchToPlanViewMode)
        .wait(2000)
        .expect(currentViewMode.innerText).eql('平面视图', 'The view mode is not right.')
        .click(currentViewMode)
        .wait(1000)
        .click(switchToRCPViewMode)
        .wait(2000)
        .expect(currentViewMode.innerText).eql('吊顶视图', 'The view mode is not right.')
        .wait(1000)
        .click(to3D)
        .wait(1000)
        .expect(currentViewMode.exists).notOk()
    });


```

### Specify your

* operating system: Windows 7 
* testcafe version: 0.19.1
* node.js version: 8.9.0

**Comment by hang-ren** [comment]
![2018-03-23_1034](https://user-images.githubusercontent.com/29770618/37808523-bfd7ea9e-2e85-11e8-813d-539c96976899.png)
This button stays on "enabled" but in fact "esc" already input.

**Comment by hang-ren** [comment]
And the console will report error but it will be not occurred if force manually testing:

vendor.bundle.js?1521711585385:2 Uncaught TypeError: r.extractPoints is not a function
    at addShape (vendor.bundle.js?1521711585385:2)
    at new ShapeBufferGeometry (vendor.bundle.js?1521711585385:2)
    at new ShapeGeometry (vendor.bundle.js?1521711585385:2)
    at hsw.view.webgl3d.Floor.draw (core.0816a5cf4954e38a56d0.bundle.js:2)
    at hsw.view.webgl3d.Floor.hsw.view.base.Display.redraw (core.0816a5cf4954e38a56d0.bundle.js:2)
    at hsw.view.webgl3d.Canvas.hsw.view.base.Canvas.renderNewFrame (core.0816a5cf4954e38a56d0.bundle.js:2)
    at hsw.view.webgl3d.Canvas.renderNewFrame (core.0816a5cf4954e38a56d0.bundle.js:2)
    at hsw.view.webgl3d.Canvas.hsw.view.base.Canvas._onNewAnimationFrame (core.0816a5cf4954e38a56d0.bundle.js:2)
    at goog.events.EventTarget.fireListeners (core.0816a5cf4954e38a56d0.bundle.js:2)
    at Function.goog.events.EventTarget.dispatchEventInternal_ (core.0816a5cf4954e38a56d0.bundle.js:2)

**Comment by miherlosev** [comment]
Hi @hang-ren.
The problem is not reproduced in `testcafe@0.19.2`.
Try this version and let us know if the problem persists.
