### ISSUE TITLE
Hover (scroll) doesn't seem to work on dynamically created data

### ISSUE THREAD

**Issue by viking2917** [DevExpress/testcafe#2250]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

After dynamically loading a set of elements (using the Masonry js tool to create a pinterest style layout), and writing a test to hover over the nth element (for example the fifth element), calling hover does not move the page and the test fails. 

### What is the expected behavior?

Scrolling to requested element of dynamically generated list should work.

### How would you reproduce the current behavior (if this is a bug)?

This is in an ionic project. The code for the project can be found here, it is an example project showing how to use Masonry with Ionic. Installing this code and then running the test below fails. 

https://github.com/viking2917/ionicMasonryExample

Test code: localhost:8100 or similar, after iconic project above installed and "ionic serve" is running

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
import { Role, Selector } from 'testcafe';
import { AngularJSSelector } from 'testcafe-angular-selectors';

const tabButton = Selector('span.tab-title');
const fifthBook = Selector(".masonry-brick").nth(5);

fixture `Getting Started`
    .page `http://localhost:8103/`;

test('Tabs test', async t => {
    await t

	.click(tabButton.withText('Chats').parent())
	.wait(500)
	.hover(fifthBook)
});

```

This tail will fail with the error 

`1) The element that matches the specified selector is not visible.
`

However, if *while the test is running* you manually scroll the page up so the item is visible, the test will pass. 

I think some how the state of the page inside of TestCafe somehow does not know about these new items, and/or where they are on the page....

I have seen this is a number of situations with other forms of dynamically generated data...

Loving TestCafe! But much of my app is data-driven from server side and I'm having trouble getting it to scroll to off-screen items...

### Specify your

* operating system: 0.13.3
* testcafe version: 0.19.1
* node.js version: v8.9.4

**Comment by AlexKamaev** [comment]
Hi,
I was able to reproduce the issue when the screen size is too small to display more than five items.

TestCafe has a mechanism to scroll the page to the target element. This mechanism is based on an element's scrollTop and scrollLeft properties. However, Ionic uses its own mechanism of scrolling, so TestCafe cannot scroll the page to a required element.

To overcome this issue, I recommend using the Custom Methods feature http://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/extending-selectors.html#custom-methods:

 Please see the code below:

```JS
const tabButton = Selector('span.tab-title');
const fifthBook = Selector(".masonry-brick").nth(5).addCustomMethods({
    scroll: (el) => {
        el.scrollIntoView();
    }
});

fixture `Getting Started`
    .page `http://localhost:8100/`;

test('Tabs test', async t => {
    await t
	.click(tabButton.withText('Chats').parent())
    .wait(500);
    await fifthBook.scroll();
    await t.hover(fifthBook);
});
```

Here we defined a custom method for the selector, which calls an element's scrollToView function to scroll the visible area to the element.

**Comment by viking2917** [comment]
Thank you @AlexKamaev! I can confirm this workaround is working for me as well. It does mean most any Ionic page with dynamically generated content will need to define these custom selectors/scroll methods rather than relying on hover(), but that should be manageable. Is there a way to enforce this scrolling method globally? (or replace the underpinnings of Hover() so it works globally for Ionic apps?). 

Thanks again for the workaround! Loving Testcafe and this makes it usable for my app, where most pages have this behavior....

**Comment by AlexKamaev** [comment]
I am glad to hear that my assistance was helpful.
If you want to use this approach in different tests you can extract it as a method or even move this code to a separate module. Please refer to the following code:
 
```JS
const tabButton = Selector('span.tab-title');
const fifthBook = Selector(".masonry-brick").nth(5);
const sixthBook = Selector(".masonry-brick").nth(6);

async function scrollAndHover (t, selector) {
    const result = selector.addCustomMethods({
        scroll: (el) => {
            el.scrollIntoView();
        }
    });
    await result.scroll();
    await t.hover(result);
}

test('Test 1', async t => {
    await t.click(tabButton.withText('Chats').parent());
    await t.wait(500);
    await scrollAndHover(t, fifthBook);
    await t.wait(1000)
});

test('Test 2', async t => {
    await t.click(tabButton.withText('Chats').parent());
    await t.wait(500);
    await scrollAndHover(t, sixthBook);
    await t.wait(1000)
});
```
