### ISSUE TITLE
Incorrect Selector returns as truthy in page model

### ISSUE THREAD

**Issue by james-brndwgn** [DevExpress/testcafe#2256]
### Are you requesting a feature or reporting a bug?

Reporting a bug

### What is the current behavior?

When using a page model, a Selector will always return as truthy even if the selector is incorrect/doesn't exist.

### What is the expected behavior?

The test should fail and report an error saying "Selector is not defined" or similar.

### How would you reproduce the current behavior (if this is a bug)?
```
import { Selector } from 'testcafe';

export default class PageModel {
  constructor() {
    // This is the incorrect selector, which still passes the test
    this.bar = Selector('.foo');
  }
}
```

```
import PageModel from './page.model';

const Page = new PageModel();

fixture(`Page Test`)
  .page('http://localhost/')

test('The selector bar exists', async t => {
    const bar = await Page.bar; 

    if (await bar.exists && await bar.visible) {
      await t
        .expect(bar.count).eql(1); // Passes, even though the selector is incorrect
    }
});
```

### Specify your

* operating system: OS X 10.11.6 (15G1510)
* testcafe version: 0.19.1
* node.js version: v8.2.1

**Comment by AlexanderMoskovkin** [comment]
Hi @james-brndwgn,

The test works properly based on your description. `await bar.exists` returns `false` and the code inside the `if` statement is not executed. If you want to check that the page contains an element with the `.foo` selector just use an assertion without the `if` statement:

```js
test('The selector bar exists', async t => {
      await t
        .expect(Page.bar.count).eql(1); // Fails if there is no such element on the page
});
```

**Comment by james-brndwgn** [comment]
@AlexanderMoskovkin you are completely right. It was the `if (await bar.exists && await bar.visible)` that was throwing me off. Removing that, but keeping the incorrect selector causes the test to fail with `AssertionError: expected 0 to deeply equal 1` as would be expected. Thanks for clarifying the issue.

**Comment by AlexanderMoskovkin** [comment]
You're always welcome
