### ISSUE TITLE
Need to update list of available devices for emulation in google chome

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#2257]
Fix require in https://github.com/AndreyBelym/chrome-emulated-devices-list
Corresponding with the [question](https://testcafe-discuss.devexpress.com/t/having-trouble-with-device-emulation-some-devices-not-found/988) on our forum.

**Comment by viking2917** [comment]
I was able to re-install testcafe and see this working.

**Comment by AndreyBelym** [comment]
Hi @viking2917, I've updated the [chrome-emulated-devices-list](https://github.com/AndreyBelym/chrome-emulated-devices-list) package, so it might be necessary to remove `package-lock.json` and reinstall `node_modules` or completely re-install TestCafe.

**Comment by viking2917** [comment]
yes I re-installed all of Testcafe and saw it working.
