### ISSUE TITLE
localStorage.getitem() in test does not return item

### ISSUE THREAD

**Issue by korsun** [DevExpress/testcafe#2262]
### Are you requesting a feature or reporting a bug?

Troubleshooting

Hi guys and thanks a lot for a great product!

I have a question.

A click on `saveButton` in my code saves `somevalue` to the localstorage. No problems with it. But when i simulate this behavior with Testcafe my `localStorageGet` fn returns null as i've never saved anything. I tried to `t.wait(some time)` after click but it didn't work.
When i do localStorageSet with ClientFucntion right in the test then localStorageGet returns a value.
`t.debug()` doesn't help, in chrome devtools i see only storage sandbox not actual localstorage for my page.
Maybe I'm doing something wrong.

```js
const localStorageGet = ClientFunction((key: string) => localStorage.getItem(key));
test('...', async t => {
    await t
    .click(saveButton)
    .expect(await localStorageGet('somekey')).eql('somevalue') // fail
})
```

### Specify your

* operating system: macOS
* testcafe version: 0.19.1
* node.js version: 8.9.4

**Comment by helen-dikareva** [comment]
Hello @korsun
In your example, a click on `saveButton` will be executed after `ClientFunction` execution. You can use a [smart assertion query mechanism](https://devexpress.github.io/testcafe/documentation/test-api/assertions/#smart-assertion-query-mechanism):
```js
await t
    .click(saveButton)
    .expect(localStorageGet('somekey')).eql('somevalue')
```
or extract execution `ClientFunction` from action chain:
```js
await t.click(saveButton);
 
const stor = await localStorageGet('somekey');
 
await t.expect(stor).eql('somevalue');
```

**Comment by korsun** [comment]
@helen-dikareva thank you ! It worked
