### ISSUE TITLE
Make external request

### ISSUE THREAD

**Issue by filoxo** [DevExpress/testcafe#2263]
I'm struggling to understand if/how to make an external request for my tests. My app requires a test code, and using a previous suite I was able to make an http request to an external microservice to get this code (ex. [Cypress command](https://docs.cypress.io/api/commands/request.html#Usage)). What might be the equivalent with Testcafe? 

### What is the current behavior?

Currently I've tried using `whatwg-fetch` that is included in my React project, as well as using node's `https` module. I'd expected to be able to use [Client Functions](https://devexpress.github.io/testcafe/documentation/test-api/obtaining-data-from-the-client.html#calling-client-functions-from-nodejs-callbacks) to execute something like this but haven't had luck with it.

I've searched issues and haven't found any that seem similar to my use case. This seems like something that might be pretty common, so it'd also be great to add docs to it (I'd love to once I get something working!). Any help or insight is much appreciated!

#### Test code

```js

import { stageAuthUser } from './Roles'
const https = require('https')
const options = {
	host: 'testcodeprovider.stage.int',
	path: '/code',
	method: 'POST',
	headers: {
		'accept': 'application/json;charset=UTF-8',
		'content-type': 'application/json'
	}
}

fixture `Stage`
	.page `https://www.stage.com/`
test('Stage test', async t => {
	await t
		.useRole(stageAuthUser)
		.click('#selfBtn')
		.click('#nextBtn')

	const code = await new Promise(resolve => {
		return https.request(options, (res) => {
			console.log(res) // Never logged
			resolve(res.body[0]) // Never resolves
		})
	})
})
```

### Specify your

* operating system: Mac OS High Sierra
* testcafe version: 0.19.1
* node.js version: 9.8.0

**Comment by helen-dikareva** [comment]
Hello @filoxo 
Please try this working example of request execution:
```js
import https from 'https';

fixture `fixture`
    .page `http://google.com`;

test('test', async t => {
    const executeRequest = () => {
        return new Promise(resolve => {
            const options = {
                hostname: 'encrypted.google.com',
                port:     443,
                path:     '/',
                method:   'GET'
            };

            const req = https.request(options, res => {
                console.log('statusCode:', res.statusCode);
                console.log('headers:', res.headers);
                resolve();
            });

            req.on('error', e => {
                console.error(e);
            });

            req.end();
        });
    };

    await executeRequest();
});
```
It seems like you forget to call `req.end();`.
Also you can take a look at the corresponding [question ](https://stackoverflow.com/questions/46830313/testcafe-check-for-images/46831540?noredirect=1#comment80617127_46831540)about request execution.

**Comment by filoxo** [comment]
Thanks for the info! Closing.
