### ISSUE TITLE
Add testcafe parameter that allows user to interact with the page during tests run

### ISSUE THREAD

**Issue by Andgoncharov** [DevExpress/testcafe#2266]
### Are you requesting a feature or reporting a bug?

I'm requesting a feature.

### What is the current behavior?

Currently, when a test is executed, manual interaction with the page isn't allowed. As I understand it's intentional behavior and it's really preferable in most cases. However, I have several tests where I need a human operator to determine whether a test has passed or failed (like video playback artifacts or smooth switch between player renditions). So, I add two buttons on a page ('pass' and 'fail') for an operator to press according to the result.

### What is the expected behavior?

As I see it from my perspective, I would add a parameter to testcafe (like --allow-manual-interaction) which allows user to interact with the page. I would like to make a PR if you can give me a hint where to start from.

### How would you reproduce the current behavior (if this is a bug)?

N/A

#### Provide the test code and the tested page URL (if applicable)

N/A

Tested page URL:

Test code

```js

```

### Specify your

* operating system: N/A
* testcafe version: N/A
* node.js version: N/A

**Comment by AlexanderMoskovkin** [comment]
Hi @Andgoncharov,

Take a look at the [Client-Side Debugging](https://devexpress.github.io/testcafe/documentation/test-api/debugging.html#client-side-debugging) topic. TestCafe shows the `Unlock page` button when the test is stopped on the `t.debug()` action. Also you can use the [--debug-mode](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-d---debug-mode) option and unlock the page by using this button. 
Does it meet your needs?

**Comment by Andgoncharov** [comment]
Hi @AlexanderMoskovkin,

Thanks for your answer, I've tried your suggestion and it's almost perfect, except the fact that I need to click two buttons (Unlock page and Resume) for every test. I think it's enough for me, I have not so many of such tests for now. So thank you again.

As of making it even more convenient, what do you think about adding the parameter I proposed before?  I could do that by analogy the Unlock page button. Will you accept such PR?

**Comment by helen-dikareva** [comment]
Hello @Andgoncharov 
This may be a good idea, but what you described is quite an edge case. TestCafe specializes in fully automated functional testing so we think a property that allows manual testing won't be necessary and, moreover, will be bewildering for most of the users. Of course, you can fork TestCafe and implement this property in your fork.
