### ISSUE TITLE
Debug mode and emulation don't seem to work together - debug menus freeze

### ISSUE THREAD

**Issue by viking2917** [DevExpress/testcafe#2268]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

If I run

`testcafe -d "chrome:emulation:device=iphone 6" test.js
`

When the first menus appear, they are locked - i.e. I cannot select "Resume" or any other buttons. 

However, 

```
testcafe "chrome:emulation:device=iphone 6" test.js
testcafe -d chrome test.js
```

both work as expected.

### What is the expected behavior?

Debug menus should work in emulation mode

### How would you reproduce the current behavior (if this is a bug)?

This occurs with any test I run. For example, the code in this issue will reproduce it: https://github.com/DevExpress/testcafe/issues/2251

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: 0.13.3
* testcafe version: 0.19.1
* node.js version: v8.9.4

**Comment by AndreyBelym** [comment]
Hi @viking2917, I reproduced the issue. Strange, but looks like Chrome doesn't emit touch events when emulating touch devices in some cases. We have to find a workaround for this.

**Comment by AndreyBelym** [comment]
Chrome devs changed emulation API: method [setTouchEmulationEnabled](https://chromedevtools.github.io/devtools-protocol/1-2/Emulation#method-setTouchEmulationEnabled) was renamed to [emulateTouchFromMouseEvent](https://chromedevtools.github.io/devtools-protocol/tot/Input/#method-emulateTouchFromMouseEvent).
