### ISSUE TITLE
Status panel is not shown in v0.19.2-alpha1

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#2270]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Status panel is not show in both regular and debugging modes

### What is the expected behavior?
Status panel must be visible

### How would you reproduce the current behavior (if this is a bug)?
Run any test

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Windows 10
* testcafe version: 0.19.2-alpha1
* node.js version:

**Comment by AlexanderMoskovkin** [comment]
I'm working on this

**Comment by AlexanderMoskovkin** [comment]
It seems it works properly

**Comment by AndreyBelym** [comment]
Just for reference, reinstalling of `node_modules` is required.

**Comment by AlexanderMoskovkin** [comment]
on my side it worked without reinstalling. It seems it depends
