### ISSUE TITLE
TestCafe resizing browsers problem

### ISSUE THREAD

**Issue by ancafolo** [DevExpress/testcafe#2284]
I tried all the possible commands (link below) for resizing Safari and IE browsers to mobile resolution and it fails everytime. With Chrome and Firefox it works though.

http://devexpress.github.io/testcafe/documentation/test-api/actions/resize-window.html

**Comment by AndreyBelym** [comment]
Hi @ancafolo, please specify your OS, node.js, TestCafe and browsers versions. How have you installed TestCafe: locally/globally, using NPM/Yarn? How do you start TestCafe: directly from command line, using `package.json` or NPM? Also, it will be great if you can share code of the test.

**Comment by ancafolo** [comment]
os: Windows 10
node.js: type npm --version on your terminal
testcafe: type testcafe on the terminal to see the version
installed: locally using npm
starting: directly from commandline
code of the test: console.log(parsePage(environment,domain));
fixture("Home")
    .page(parsePage(environment,domain))

test
.before(async t => {
  // Resize window
  await t.resizeWindow(1280,500);
})

  ("Home Page", async t => {

**Comment by AndreyBelym** [comment]
@ancafolo, `fixture.before` hooks are executed before starting browsers, and you can't use test controller  `t` inside these hooks: [docs](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#fixture-hooks). Use the `beforeEach` hook instead.

**Comment by ancafolo** [comment]
Thanks a lot for the reply, @AndreyBelym 
Ok, so I changed the code to this:

console.log(parsePage(environment,domain));
fixture("Home")
    .page(parsePage(environment,domain))
    .beforeEach(async t => {
      // Resize window
      await t.resizeWindow(1280,500);
    });

test


  ("Home Page", async t => {


And it still doesn't work..

**Comment by AndreyBelym** [comment]
@ancafolo, how do you run Safari 11 on Windows?

**Comment by ancafolo** [comment]
@AndreyBelym this experiment was for IE. Safari and IE don't work.

**Comment by AndreyBelym** [comment]
So it falls in Safari on macOS and in IE on Windows?

**Comment by ancafolo** [comment]
Exactly

**Comment by AndreyBelym** [comment]
And Chrome and Firefox are resized correctly on Mac too?

**Comment by AndreyBelym** [comment]
Also, are IE and Safari closed automatically by TestCafe whe tests finished, or they stay open?

**Comment by ancafolo** [comment]
Home Page

   1) - Error in fixture.beforeEach hook -
      Error on page "https://www.staging.juniqe.de/":

      NetworkError

      Browser: IE 11.0.0 / Windows 10.0.0

         11 |console.log(parsePage(environment,domain));
         12 |fixture("Home")
         13 |    .page(parsePage(environment,domain))
         14 |    .beforeEach(async t => {
         15 |      // Resize window
       > 16 |      await t.resizeWindow(500,500);
         17 |    });
         18 |
         19 |test
         20 |
         21 |
