### ISSUE TITLE
open a new tab replace currently tab

### ISSUE THREAD

**Issue by Priccc** [DevExpress/testcafe#2293]
### Are you requesting a feature or reporting a bug?
I think this is a bug

### What is the current behavior?
open a new tab replace currently tab

### What is the expected behavior?
there are  two tab not one

#### Provide the test code and the tested page URL (if applicable)
My tested Code
```js
const newWindow = window.open('/salesorders/redirect');
...
const res = await api.post('/agent/salesorders/precreate', saveData);
```
My request will be canceled, when `window.open` executed.
Because a new tab replace current tab.

### Specify your

* operating system: Mac OS
* testcafe version: 0.19.1
* node.js version: 8.4.0

**Comment by AlexanderMoskovkin** [comment]
Hi @Priccc,

For now TestCafe doesn't support testing in multiple browser windows. That's why it opens a new page in the same tab.

Here's an issue for this functionality: #912

**Comment by Priccc** [comment]
@AlexanderMoskovkin 
Thanks for your answer. Now I use a special way to achieve my test. But I hope you can realize as soon as possible.

**Comment by theTainted** [comment]
@Priccc 
I have been looking for something similar but also to interact with the second tab, would you be able to share your workaround, please ?

Thanks

**Comment by amirse80** [comment]
Any new on new tab functionality? Will TestCafe ever support it?

**Comment by educamais** [comment]
> @AlexanderMoskovkin
> Thanks for your answer. Now I use a special way to achieve my test. But I hope you can realize as soon as possible.

Hey man, can you share what you did to solve this problem?
