### ISSUE TITLE
Tests don't run on Chromium 41

### ISSUE THREAD

**Issue by dcsaszar** [DevExpress/testcafe#2296]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

Test starts, but breaks:

Browser console:
```
Uncaught TypeError: Cannot read property 'get' of undefined
testcafe-core.js:2 Uncaught TypeError: Cannot read property 'utils' of undefined
testcafe-ui.js:1 Uncaught TypeError: Cannot read property 'shadowUI' of undefined
testcafe-automation.js:1 Uncaught TypeError: Cannot read property 'domUtils' of undefined
testcafe-driver.js:1 Uncaught TypeError: Cannot read property 'Promise' of undefined
task.js:1 Uncaught TypeError: Cannot read property 'start' of undefined
jquery-1.12.4.min.js:3 Uncaught TypeError: undefined is not a function
jquery-ui.min.js:7 Uncaught ReferenceError: jQuery is not defined
10.0.40.2/:12 Uncaught ReferenceError: $ is not defined
```

Shell:
```
Running tests in:
 - Chrome 41.0.2272 / Mac OS X 10.13.4

 Getting Started
ERROR The Chrome 41.0.2272 / Mac OS X 10.13.4 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.

Type "testcafe -h" for help.
```

### What is the expected behavior?

Test runs fine

### How would you reproduce the current behavior (if this is a bug)?

* Install Chromium 41.0.2272 (https://sourceforge.net/projects/osxportableapps/files/Chromium/Chromium_OSX_41.0.2272.118.dmg/download)
* Copy the example `test1.js` from the README
* `npm i testcafe@0.18.7-dev20180201 -D`
* Run `npx testcafe chromium test1.js`

#### Provide the test code and the tested page URL (if applicable)

Test code

```js
import { Selector } from 'testcafe'; // first import testcafe selectors

fixture `Getting Started`// declare the fixture
    .page `https://devexpress.github.io/testcafe/example`;  // specify the start page


//then create a test and place your code there
test('My first test', async t => {
    await t
        .typeText('#developer-name', 'John Smith')
        .click('#submit-button')

        // Use the assertion to check if the actual header text is equal to the expected one
        .expect(Selector('#article-header').innerText).eql('Thank you, John Smith!');
});
```

### Specify your

* operating system: Mac OS X 10.13.4
* testcafe version: 0.18.7-dev20180201
* node.js version: 9.5.0

### Notes

* `0.18.7-dev20180124` is the last version without the issue
* Chrome V. 41 support is important because of https://www.elephate.com/blog/chrome-41-key-to-website-rendering/

**Comment by MarinaRukavitsyna** [comment]
Hello @dcsaszar 
According to [this help topic](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/browser-support.html), TestCafe supports the latest version of each browser. 

In particular, Chrome v. 41 was released is 2015 and does not support some modern features (e.g. property redefinition), which are used by TestCafe and modern browsers. It is not possible to add features that are not supported by outdated browsers at the TestCafe level.

As, generally, Chrome is updated automatically, I suggest you test your app in the latest Chrome version.

**Comment by AlexanderMoskovkin** [comment]
Hi @dcsaszar,
 
Unfortunately, we can't support testing in Chrome v. 41. We use some features in our javascript code, which allow us to have better performance and more reliable behavior in modern browser versions. Chrome v. 41 doesn't support some of them.
