### ISSUE TITLE
Cannot select text in contenteditable element

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#2301]
Based on [the question](https://testcafe-discuss.devexpress.com/t/bug-selecttext-is-not-working/1027) from discuss forum

**Comment by LavrovArtem** [comment]
The fix is published `in testcafe@0.20.0-alpha.1`.

**Comment by Andrei1982** [comment]
In ver testcafe@0.20.2 - method selectText doesn't work http://s.csssr.ru/U5LQQCK7T/20180606190308.jpg

**Comment by miherlosev** [comment]
Hi @Andrei1982 

Could you please send me your test credentials (login/password) so I can reproduce the issue on a real-life web site?
My corporate email is mikhail.losev@devexpress.com.
