### ISSUE TITLE
testcafe-reporter developped in TypeScript cannot be loaded in testcafe at runtime

### ISSUE THREAD

**Issue by hdorgeval** [DevExpress/testcafe#2304]
### Are you requesting a feature or reporting a bug?
Maybe a bug

### What is the current behavior?
I am currently developping a testcafe-reporter in TS
When testcafe starts its execution, there is an error in bootstrapper.js:267 
```javascript
return {
     plugin: pluginFactory(),
     outStream: outStream
};
````
### What is the expected behavior?
reporters developped with TS should load correctly

#### Provide the test code and the tested page URL (if applicable)
content of the index.ts
```typescript
import { reportFixtureStart, reportTaskDone, reportTaskStart, reportTestDone } from "./reporter";
import { IReporter } from "./reporter-interface";

const reporterPlugin: () => IReporter = () => {
    return {
        reportFixtureStart,
        reportTaskDone,
        reportTaskStart,
        reportTestDone,
    };
};

export default reporterPlugin;
````

content of the compiled index.js:
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var reporter_1 = require("./reporter");
var reporterPlugin = function () {
    return {
        reportFixtureStart: reporter_1.reportFixtureStart,
        reportTaskDone: reporter_1.reportTaskDone,
        reportTaskStart: reporter_1.reportTaskStart,
        reportTestDone: reporter_1.reportTestDone,
    };
};
exports.default = reporterPlugin;
//# sourceMappingURL=index.js.map
```
The problem is solved when doing the following modification in bootstrapper.js:
```javascript
if (typeof pluginFactory !== 'function') {
                try {
                    pluginFactory = require('testcafe-reporter-' + name);
                    if ( pluginFactory.default &&  typeof pluginFactory.default === 'function') {
                        pluginFactory = pluginFactory.default;
                    }
                } catch (err) {
                    throw new _runtime.GeneralError(_message2.default.cantFindReporterForAlias, name);
                }
            }

```

### Specify your

* operating system: Mac OS X
* testcafe version: latest
* node.js version: v9.2.0

**Comment by AndreyBelym** [comment]
Hi @hdorgeval, TestCafe expects that your reporter plugin module is a CommonJS module, so you should use 
```
export = reporterPlugin;
```
instead of
```
export default reporterPlugin
```

It's a special TypeScript syntax, that makes your module CommonJS compatible: [TypeScript docs](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require).

**Comment by hdorgeval** [comment]
@AndreyBelym, @AlexanderMoskovkin,
Thank you for your feedback, here is the result: [testcafe-reporter-cucumber-json](https://github.com/hdorgeval/testcafe-reporter-cucumber-json)
