### ISSUE TITLE
Enable support of page zooming

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#2314]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
Currently TestCafe doesn't support zooming of a whole page, because it was believed that zooming can be performed only by manual interaction with the browser UI. However, there are widely supported CSS properties like `zoom` and `transform` (with the `scale()` modifier) which can be used on the `html` element to apply zoom on per-page basis. 

### What is the expected behavior?
TestCafe actions should work on pages with CSS properties like `zoom` and `transform: scale()`.

### Specify your

* operating system: Windows 10
* testcafe version: 0.19.2
* node.js version: 8.9.4

**Comment by VladimirCacicArapovic** [comment]
Hi guys..any news regarding this;)

**Comment by vvedachalam** [comment]
Hi @AndreyBelym @miherlosev Is this enhancement in your roadmap?

**Comment by samplehub** [comment]
Can you reopen this please ??

**Comment by AlexKamaev** [comment]
At present, we do not have plans to support zooming, since we have higher prioritized tasks.
