### ISSUE TITLE
Version tags to docker images

### ISSUE THREAD

**Issue by ronkot** [DevExpress/testcafe#2315]
### Are you requesting a feature or reporting a bug?

Enhancement

### What is the current behavior?

Only tags `latest`, `alpha` and `dev` for testcafe docker images

### What is the expected behavior?

In addition to current tags a unique version tag for each release. For example: `testcafe/testcafe:0.19.1`

### Reasoning

Without specific version tags our CI tests will fail when a non-backwards compatible image with `latest` tag is released. I'd like to pin a specific version to be used in CI.

**Comment by neelakansha85** [comment]
Thanks for supporting the docker image, I am planning to use your image for our production end to end test use case and was wondering if you have a timeline for supporting version tags for docker image?

It would be really nice and helpful to have that.

**Comment by Gwerlas** [comment]
Even better, perhaps is it possible to become the [official repo on docker hub](https://docs.docker.com/docker-hub/official_repos/) and the users could launch testcafe like this :

```
docker run testcafe
docker run testcafe:0.21.1
```

And You'll benefit of the layers vulnerability scanning.
With an automatic build and the link between GitHub and Docker Hub, you'll have the `README` and the `Dockerfile` displayed and up to date in Docker Hub.

**Comment by AndreyBelym** [comment]
Hi @Gwerlas, thanks for the hint! I think I will try to get the official image status next sprint (2-3 weeks usually).

**Comment by kruckenb** [comment]
It looks like Gulpfile.js has most of what's needed to publish with tags, with some tweaks.

```
const PUBLISH_TAG = JSON.parse(fs.readFileSync(path.join(__dirname, '.publishrc')).toString()).publishTag;
[...]
childProcess.execSync('docker tag ' + imageId + ' testcafe/testcafe:' + PUBLISH_TAG, {
```

If the version was added to `publishTag` in `.publishrc` when `Bump version` commits are generated (like this example modified from 6e8e806430ba650a6abe24317971c2317139f595)

```
diff --git a/.publishrc b/.publishrc
@@ -8,7 +8,7 @@
     "gitTag": true
   },
   "confirm": true,
-  "publishTag": ["alpha","0.23.0-alpha.2"],
+  "publishTag": ["latest","0.23.0"],
   "prePublishScript": "gulp test-server",
   "postPublishScript": "gulp docker-publish"
 }
```

then `Gulpfile.js` could also generate a version tag, something like this (not tested):

```
diff --git a/Gulpfile.js b/Gulpfile.js
@@ -743,16 +743,13 @@ gulp.task('docker-build', done => {
         }
     }

-    const imageId = childProcess
-        .execSync('docker build -q -t testcafe -f docker/Dockerfile .', { env: process.env })
+    const tagParam = PUBLISH_TAG.map((tag) => { return `-t testcafe/testcafe:${tag}`; });
+
+    childProcess
+        .execSync(`docker build -q ${tagParam} -f docker/Dockerfile .`, { env: process.env }
         .toString()
         .replace(/\n/g, '');

-    childProcess.execSync('docker tag ' + imageId + ' testcafe/testcafe:' + PUBLISH_TAG, {
-        stdio: 'inherit',
-        env:   process.env
-    });
-
     done();
 });
```
