### ISSUE TITLE
Android browsers fails to connect because connection URL requested twice

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#2318]
### Are you requesting a feature or reporting a bug?
Ehhancement

### What is the current behavior?
Android browsers from Browserstack makes two requests to the TestCafe connection URL specified as a worker start URL. A browser ignores or just doesn't have time to process the first request's response, but immediately sends the second request which fails to complete, because TestCafe consider this browser as already connected. We didn't encounter this problem in our functional tests, because we naviagate browser to an additional page before the connection page: https://github.com/AlexanderMoskovkin/browserstack-connector/blob/master/src/hub.js 

### What is the expected behavior?
Browser must be considered connected only if TestCafe processed request to the browser's idle page, or received browser's hearbeat.

### Specify your

* operating system: Windows 10
* testcafe version: 0.19.2
* node.js version: 8.9.4

**Comment by guptaakhil** [comment]
I have encouter this issue with ff version: 49 as well, below version using: 

testcafe version : 0.18.6
node version : 6

**Comment by davidarce** [comment]
I have the same issue on

testcafe version : 0.21.1

**Comment by venkatakhil18** [comment]
The "Google Chrome" worker did not respond to the TestCafe and was deleted. This problem may appear when a worker browser hangs or is closed, or due to network issues.

operating system: Windows 10
testcafe version: v.15.13
node.js version: 6.4.1
