### ISSUE TITLE
onChange event not fired on Controlled input in Angular 5

### ISSUE THREAD

**Issue by sommcz** [DevExpress/testcafe#2319]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

Using action.type not fire onChange event when used on controlled input in Angular5

### What is the expected behavior?

onChange resp. "(change)" event is fired no matter if it is controlled or non-controlled (with binded [value] property) input

### How would you reproduce the current behavior (if this is a bug)?

Create input with binded value which updates its value in onInput event. See example at: 
https://stackblitz.com/edit/testcafe-and-angular-controlled-componenet-issue

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://testcafe-and-angular-controlled-componenet-issue.stackblitz.io

Test code

```js

"@fixture test input change event";
"@page https://testcafe-and-angular-controlled-componenet-issue.stackblitz.io/";


"@test"["test1"] = {
    '1.Type in input "A"': function() {
        act.type("input[name='A']", "10");
    },
    '2.Type in input "B"': function() {
        act.type("input[name='B']", "11");
    },
    '3.Type in input "C"': function() {
        act.type("input[name='C']", "12");
    },
    '4.Type in input "D"': function() {
        act.type("input[name='D']", "13");
    },
    "5.Click body": function() {
        act.click("body");
    },
    "6.Assert": function() {
        eq($("#testChangeResult").text(), '{\n  "a": true,\n  "b": true,\n  "c": true,\n  "d": true\n}', "Change events fired");
    }
};
```

### Specify your

* operating system: & browser: Chrome 65.0.3325 / Windows 10 0.0.0
* testcafe version: 0.19.2
* node.js version: v8.9.4

**Comment by AlexKamaev** [comment]
Hi, I was able to reproduce the issue. I'll investigate it

**Comment by AlexKamaev** [comment]
fixed in https://github.com/DevExpress/testcafe-hammerhead/issues/1580
