### ISSUE TITLE
Quarantine mode - number of retries

### ISSUE THREAD

**Issue by ancafolo** [DevExpress/testcafe#2329]
Is there a possible way to set the number of retries in quarantine mode?
I'm using Windows10, testcafe 0.19.1, node.js: npm@5.6.0

**Comment by AndreyBelym** [comment]
Hi @ancafolo, currently quarantine mode is hardcoded to run a failed test until there is 3 passed or failed runs in total.

**Comment by link89** [comment]
I think we should provide the ability to overwrite the number of retry. Maybe we can start from overwrite via environment vars, which is easy and clean. And then move to runner and command line arguments.
