### ISSUE TITLE
Native window.print() dialog is not handled

### ISSUE THREAD

**Issue by AlexKamaev** [DevExpress/testcafe#2331]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

system print dialog appears and prevent test execution

### What is the expected behavior?

this dialog should be handled

#### Provide the test code and the tested page URL (if applicable)

```HTML
<html>
    <head>
    </head>
    <body>
        <button onclick="window.print()">print</button>
        <button>click</button>
    </body>
</html>
```

Test code

```js
test('Print dialog', async t => {
    await t
        .click(Selector('button').withText('print')) // waiting here and prevents further test execution
        .click(Selector('button').withText('click')) // 
});
```

**Comment by AlexKamaev** [comment]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

system print dialog appears and prevent test execution

### What is the expected behavior?

this dialog should be handled

#### Provide the test code and the tested page URL (if applicable)

<html>
    <head>
    </head>
    <body>
        <button onclick="window.print()">print</button>
        <button>click</button>
    </body>
</html>

Test code

```js
test('Print dialog', async t => {
    await t
        .click(Selector('button').withText('print')) // waiting here and prevents further test execution
        .click(Selector('button').withText('click')) // 
});
```

**Comment by ZayanNadeem** [comment]
Is there any update on this issue?

**Comment by miherlosev** [comment]
Hi @ZayanNadeem 

The current development [sprint](https://github.com/DevExpress/testcafe/milestone/26) is already planned. We will consider this issue during planning the next development sprint.

**Comment by weyert** [comment]
Any update on this?

**Comment by miherlosev** [comment]
Hi @weyert 

At present, this enhancement is not implemented.
The features that we are planning to implement are listed on the [Roadmap](https://devexpress.github.io/testcafe/roadmap/) page. The current feature is not on this list. I'm afraid I cannot provide you with any time frames as to when it will be implemented.

If this enhancement is very important for you, the PR is greatly appreciated.

**Comment by rob4629** [comment]
Hi, I'm just wondering if an issue I'm experiencing is related to this.

Running my tests in Safari, and I get a browser dialog/pop-up window: `this website has been blocked from automatically composing an email`. I've tried to use `await t.setNativeDialogHandler(() => true)`, but I'm unable to clear the dialog. This then prevents the rest of my tests from executing (as referenced [here](https://github.com/DevExpress/testcafe/issues/4732)).

**Comment by AlexSkorkin** [comment]
The [setNativeDialogHandler](https://devexpress.github.io/testcafe/documentation/test-api/handling-native-dialogs.html) method is intended for the native alert/confirm/prompt and beforeunload dialogs. It does not support the print dialog (as mentioned in this thread) or other dialogs. We will look deeper into it in the context of your other thread: #4732

**Comment by rob4629** [comment]
Hey, can you leave this open, please?

**Comment by Farfurix** [comment]
Hello @rob4629,

OK.

**Comment by fabidev1993** [comment]
hi
any update on this issues?
i have same problem
i want to be sure that button is working correctly but when i click on the button print dialog comes out and i can not do any thing with that :|

**Comment by LaszloQ** [comment]
Hello, I'm experiencing the same problem. The print window is opened and the browser hangs and eventually closes down. 

Do you have any workarounds for this? The submit button doesn't have an onClick attribute.

**Comment by miherlosev** [comment]
Hi @kerrijackson,

There are still no updates. However, you can use the following workaround to prevent test execution from being stopped. Add the following code to [clientScript](https://testcafe.io/documentation/402843/guides/advanced-guides/inject-client-scripts).

```js
window.print = function () {};
```
