### ISSUE TITLE
Safari Stuck Loading Tested Page URL

### ISSUE THREAD

**Issue by GregoryCBT** [DevExpress/testcafe#2344]
### Are you requesting a feature or reporting a bug?
Reporting a Bug.

### What is the current behavior?
Test won't load initial webpage in safari.

### What is the expected behavior?
Test should load initial webpage in safari just as it does 
when running the same test in chrome or firefox or running the example test
in the testcafe readme in safari.

### How would you reproduce the current behavior (if this is a bug)?
Run the test I've made using the safari browser.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: Can't post it

Test code

```js
import { Selector } from 'testcafe';

fixture `Login Test`
    .page `[URL HERE]`;  

test('Login Test', async t => {
    await t
    	.resizeWindow(1280, 720)
        .typeText('#app > div > div > div > aside > div.container.fluid.fill-height > div > div > div > div.card__text > form > div:nth-child(1) > div.input-group__input > input[type="text"]', '[LOGIN HERE]')
        .typeText('#password', '[PASSWORD HERE]')
        .click('#login > div')

        .expect(Selector('#create > div > div > div > div.card__title > h3').innerText).eql('Systems');
});
```

### Specify your

* operating system: MacOSX 10.12.0
* testcafe version: 0.19.2
* node.js version: 8.11.1
* safari version: 10.0.0

**Comment by kirovboris** [comment]
Hi @GregoryCBT,

Could you please check if the tested page loads without testcafe? Also are there any js errors in the developer tools console during tests?

**Comment by MarinaRukavitsyna** [comment]
Hello @GregoryCBT 
Would you please also describe how you are using this URL in your code or framework?
In addition, send us an error stack if possible.

**Comment by GregoryCBT** [comment]
Hi @MarinaRukavitsyna 
I'm not sure I understand the first question, I am using the URL to access a website that I need to test.
And this is the error stack I'm getting:

```
Using locally installed version of TestCafe.
 Running tests in:
 - Safari 10.0.0 / Mac OS X 10.12.0

 Login Test
 ✖ Login Test

   1) Error on page "[URL HERE]":

      TypeError: undefined is not an object (evaluating 'urlObj.searchParams.get')

      Browser: Safari 10.0.0 / Mac OS X 10.12.0

          3 |fixture `Login Test`
          4 |    .page `[URL HERE]`;
          5 |
          6 |test('Login Test', async t => {
          7 |    await t
       >  8 |    	.resizeWindow(1280, 720)
          9 |        .typeText('#app > div > div > div > aside > div.container.fluid.fill-height > div > div > div > div.card__text > form >
      div:nth-child(1) > div.input-group__input > input[type="text"]', '[USERNAME HERE]')
         10 |        .typeText('#password', '[PASSWORD HERE]')
         11 |        .click('#login > div')
         12 |
         13 |        .expect(Selector('#create > div > div > div > div.card__title > h3').innerText).eql('Systems');

         at <anonymous> (pathtofile/testcafe/LoginTest.js:8:7)
         at test (pathtofile/testcafe/LoginTest.js:6:1)



 1/1 failed (1m 13s)
```

I hope this is of use to you, thanks again for all the help.

**Comment by MarinaRukavitsyna** [comment]
TestCafe may raise a similar error when a web page has JS errors. To check this, please open your page in a browser and enable the browser console (press F12 for this). If there are JS errors there, you can either fix them on your website or skip them during testing using the -e or --skip-js-errors option:

[-e, --skip-js-errors documentation](http://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors)

If the above steps do not help, please send us the error stack that is obtained from the **browser console**, not TestCafe console.

**Comment by GregoryCBT** [comment]
Hi everyone,
I figured out the solution to my safari issues. Turns out I had to update my version of safari and turn off the webdriver extension I had activated within safari. Thank you all for the help!
