### ISSUE TITLE
Documentation: Add the "Injecting Custom Libraries into a Test" example

### ISSUE THREAD

**Issue by MarinaRukavitsyna** [DevExpress/testcafe#2346]
### Are you requesting a feature or reporting a bug?

Feature

### What is the current behavior?

There is no example that illustrates how to add custom libraries into a test

### What is the expected behavior?

There is such an example since the task is not trivial

#### Provide the test code and the tested page URL (if applicable)
Example:

foo.js
```js
export function foo1() {
    return 111;
}
```
test.js
```js
import { ClientFunction } from 'testcafe';
const foo1 = require('./foo.js').foo1;

fixture `My fixture`
    .page `http://devexpress.github.io/testcafe/example/`;

test('My test', async t => {
    const getElementText = ClientFunction(() => {
        return foo1();
    }, { dependencies: { foo1 } });

    var fooResult = await getElementText();
    console.log(fooResult );
});
```

**Comment by kirovboris** [comment]
We have problems with `import` statement because of `babel-plugin-add-module-exports`, i.e. you can't use `impor`t for importing dependancies of `ClientFunction`, only via `require`, it's not obvious at all.

**Comment by VasilyStrelyaev** [comment]
ah, I see, okay
