### ISSUE TITLE
TestCafe hangs when a test fails in the quarantine mode

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#236]
[here](https://github.com/DevExpress/testcafe/blob/master/src/runner/browser-job.js#L49) is the cause of the problem. The arguments of the `_createTestRun` function were changed.

@inikulin Server tests require a lot of mocking in this situation. Do we need them now or will we be waiting for functional tests?

**Comment by inikulin** [comment]
@AlexanderMoskovkin you can write functional test already

**Comment by AlexanderMoskovkin** [comment]
sure, I mean we can write the test now and push it later with functional harness?

**Comment by inikulin** [comment]
Yep

**Comment by AlexanderMoskovkin** [comment]
closed with https://github.com/DevExpress/testcafe/pull/237
