### ISSUE TITLE
File upload fails in IE11

### ISSUE THREAD

**Issue by gsarkarsavo** [DevExpress/testcafe#2370]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
File upload fails in IE, with `await t.setFilesToUpload`

### What is the expected behavior?
File upload should work like other browsers.

### How would you reproduce the current behavior (if this is a bug)?
Below test would fail with error:

> 1) Uncaught object "[object Object]" was thrown. Throw Error instead.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

> http://kopasite.net/up
This is a 3rd party site, which i have no control with. I saw a similar issue in my own project but there IE 11 froze indefinitely on upload step without any error. I had to stop testcafe manually after the tests being for an hour. Not sure if these are related, but common culprit is the file upload input.

Test code

```js
test('ie11_upload_test', async t => {
	await t.navigateTo("http://kopasite.net/up");
	await t.setFilesToUpload(Selector('input[type=file]'), ['./test_file.pptx']);
	await t.click(Selector('input[type=submit]'));	
});

```

### Specify your

* operating system: Windows 10.0.0
* testcafe version: 0.19.2
* node.js version: v8.7.0

**Comment by LavrovArtem** [comment]
I cannot reproduce this issue.
https://www.screencast.com/t/OY7eggILpgW

**Comment by miherlosev** [comment]
Feel free to reopen the issue if the problem persists and you can provide an example to reproduce it.
