### ISSUE TITLE
Using testcafe browser tools to pass flags to chrome breaks screenshots

### ISSUE THREAD

**Issue by bdwain** [DevExpress/testcafe#2373]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
I am using testcafe browser tools to add command line flags to chrome when running testcafe via the node api, but it seems to prevent testcafe from saving screenshots. It creates the screenshot directory but does not save any images.

### What is the expected behavior?
Testcafe should behave like normal except for the command line flags I add, including saving screenshots. Or if there's another way I'm missing to add flags to the browser, that would be helpful too.

### How would you reproduce the current behavior (if this is a bug)?
```js
  const testcafeBrowserTools = require('testcafe-browser-tools');
  .....

  //args.browsers is ['chrome']

  const configuredBrowsers = args.browsers.map(browser => {
    if (browser === 'chrome') {
      return testcafeBrowserTools
        .getBrowserInfo('chrome')
        .then(res => {
          res.cmd = `${res.cmd} --autoplay-policy=no-user-gesture-required`;
          return res;
        });
    } else {
      return browser;
    }
  });

  args.browsers = await Promise.all(configuredBrowsers)

  createTestCafe('localhost', 1337).then(tc => {
    testcafe = tc;
    const runner = testcafe.createRunner();

    runner
      .src(getTests())
      .browsers(args.browsers)
      .screenshots(screenshotPath, true);

    return runner.run({
      debugMode: args.debug,
      debugOnFail: args.debugOnFail,
      quarantineMode: args.quarantine
    });
```

### Specify your

* operating system: Mac High Sierra
* testcafe version: 0.18.6
* node.js version: 9.11.1

**Comment by AndreyBelym** [comment]
Hi @bdwain, you can just append additional command line flags after the `chrome` alias when specifying browsers:
```
return runner
    .browsers(['chrome --autoplay-policy=no-user-gesture-required'])
```
Do you have warnings in your test reports? Could you please share a test report with me?

**Comment by bdwain** [comment]
Hi that worked. Thanks!

I don't see that behavior documented anywhere. I think it would be useful to add somewhere to https://devexpress.github.io/testcafe/documentation/using-testcafe/
