### ISSUE TITLE
Provide support for NTLM authorization for proxy

### ISSUE THREAD

**Issue by MarinaRukavitsyna** [DevExpress/testcafe#2377]
### Are you requesting a feature or reporting a bug?
A feature 

### What is the current behavior?
TestCafe supports only basic authorization for proxy, but not NTLM

### What is the expected behavior?
TestCafe supports NTLM authorization for proxy

### Specify your

* testcafe version: 0.19.2

**Comment by AlexKamaev** [comment]
TestCafe supports NTLM authentication: [https://testcafe.io/documentation/402845/guides/intermediate-guides/authentication#http-authentication](https://testcafe.io/documentation/402845/guides/intermediate-guides/authentication#http-authentication)
If it does not work in your use case, please create a separate issue.
