### ISSUE TITLE
Option for failing on skip or only (for CI).

### ISSUE THREAD

**Issue by d7ark** [DevExpress/testcafe#2378]
### Are you requesting a feature or reporting a bug?

Requesting a feature.

### What is the current behavior?

Can't find any option to disallow skip or only in tests.

### What is the expected behavior?

Tests run with proper option should fail if any test/fixture is using skip or only method.

### How would you reproduce the current behavior (if this is a bug)?

Not a bug.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: MacOS 10.13.4
* testcafe version: 0.19.1
* node.js version: 8.11.1

**Comment by miherlosev** [comment]
Hi @d7ark,
 
Thank you for this suggestion. Please note that it should be implemented in the code linting tool.
We already have an issue regarding this - https://github.com/miherlosev/eslint-plugin-testcafe/issues/1.
Track this issue to get more information or feel free to contribute.
