### ISSUE TITLE
The switchToIframe method does not wait for iframe load and raises an error

### ISSUE THREAD

**Issue by MarinaRukavitsyna** [DevExpress/testcafe#2387]
### Are you requesting a feature or reporting a bug?
A bug

### What is the current behavior?
The switchToIframe method does not wait for iframe load and raises an error

### What is the expected behavior?
The switchToIframe method should wait for iframe load. 

#### Provide the test code and the tested page URL (if applicable)
```js
await t
        .setPageLoadTimeout(47000)
        .navigateTo(`page`);

await t
        .switchToIframe(iframe)   
        .click(button);
```

### Specify your

* operating system: Windows 10
* testcafe version:  0.19.2
* node.js version: v8.11

**Comment by konstantinmaximov** [comment]
http://ccnet.devexpress.devx/ccnet/server/farm/project/AspTestCafe.VisualTests.Bootstrap.Demos.CardView.v18.1/build/log20180515010054.xml/ViewBuildReport.aspx

http://ccnet.devexpress.devx/ccnet/server/farm/project/AspTestCafe.VisualTests.Bootstrap.Demos.GridView.v18.1/build/log20180515010208.xml/ViewBuildReport.aspx

**Comment by MariaRyadchikova** [comment]
Hey guys, I know it has already been included into the sprint, but is there any time frames when you plan to resolve the issue? This one is blocking me pretty badly. Thanks!

**Comment by AndreyBelym** [comment]
@MariaRyadchikova, I think I'll fix it next week, and publish an alpha build with the fix.

**Comment by MariaRyadchikova** [comment]
Hey guys, it's been more than a month since the issue was reported, and the sprint is about to end. Any more accurate forecasts? The issue blocks from working with any frames.

**Comment by miherlosev** [comment]
I cann't reproduce the problem with the latest commit (https://github.com/DevExpress/testcafe/commit/a9a1c1e5841d5923b0970df168fc0ce35618c223).

```js
import { Selector } from 'testcafe';

fixture `test`
    .page('http://builder03/Demos-18.2/Bootstrap/CardView/Adaptivity.aspx');

test('test', async t => {
    const demoIframe = Selector('.demo-frame');
    const body       = Selector('body').exists;

    await t
        .switchToIframe(demoIframe)
        .expect(body).ok();

    await t.switchToMainWindow();
});
```
