### ISSUE TITLE
Refactor automations, make them Promised-based, unify their API to serve as the basic building blocks for both API versions

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#239]

**Comment by AlexanderMoskovkin** [comment]
I'm working on this

**Comment by AlexanderMoskovkin** [comment]
@helen-dikareva Please create here a checkbox list with all automations and check refactored automations

**Comment by helen-dikareva** [comment]
- [x] scroll
- [x] move
- [x] press
- [x] rclick
- [x] drag
- [x] hover
- [ ] select
- [ ] click
- [ ] dblclick
- [ ] type
