### ISSUE TITLE
Is it possible to simulate user gesture in TestCafe?

### ISSUE THREAD

**Issue by Andgoncharov** [DevExpress/testcafe#2396]
### Are you requesting a feature or reporting a bug?

This is more like feature request, but I'm not sure if it's possible for TestCafe.

### What is the current behavior?

When I try to enter full screen mode for video element by clicking relevant button (via TestCafe click() method), it doesn't work and I see the following error in Chrome console: "Failed to execute 'requestFullScreen' on 'Element': API can only be initiated by a user gesture."
The same behavior appears when I try to start video playback by clicking play button, because latest Chrome doesn't allow autoplay without explicit user gesture. I've bypassed the autoplay problem by setting autoplay-policy Chrome flag, but there's no such flag for full screen mode. 
Is there a way for TestCafe to simulate user gesture so that browser will accept it as the real one?

### What is the expected behavior?

Clicking play and full screen button in video player works correctly.

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by miherlosev** [comment]
Hi @Andgoncharov 

Could you please provide a page on which I can reproduce the error?

**Comment by Andgoncharov** [comment]
Hi @miherlosev 

You can try any page, that has javascript video player (based on html5 video element). For example, http://player.wmspanel.com

**Comment by miherlosev** [comment]
@Andgoncharov 
I've reproduced the problem and created a separate issue in the our proxy repository - https://github.com/DevExpress/testcafe-hammerhead/issues/1614.

**Comment by Andgoncharov** [comment]
Hi @miherlosev,

Thanks for the prompt response.
The problem you've observed is related to browser's cross-origin resource sharing policy (CORS). It differs from the problem, that I want to handle. Roughly saying, my problem appears from fact that browser detects TestCafe click() method execution as automatic click but not as real user click. Therefore it doesn't allow automatic full screen or autoplay.

**Comment by Andgoncharov** [comment]
@miherlosev ,
Got it, thanks!

**Comment by AndreyBelym** [comment]
Hi @Andgoncharov, I've found that due to changes in Chrome autoplay policies you might need to specify the `--autoplay-policy=no-user-gesture-required` flag for the browser. Could you please try it and check if your player can switch to the full screen mode with this flag?

**Comment by AndreyBelym** [comment]
Specifying this flag fixes the issue for me, but feel free to reopen it if you still have problems or questions.
