### ISSUE TITLE
Implement `t.request` action

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#2397]
`t.request (options)` action allows to make HTTP request and use response data in test.

*Examples* 
```js
t.request(url)
t.request(url, body)
t.request(method, url)
t.request(method, url, body)
t.request(options)

t.request(/example.com/).then(data => {....})
```
where `options` are fields from [requestoptions](https://github.com/request/request#requestoptions-callback)

Without this feature it is impossible to sent HTTP request with cookies.
Links:
* https://github.com/DevExpress/testcafe/issues/2263
* https://stackoverflow.com/questions/46830313/testcafe-check-for-images/46831540?noredirect=1#comment80617127_46831540
* https://testcafe-discuss.devexpress.com/t/making-http-requests-in-helpers/621/3

**Comment by inikulin** [comment]
Why it should be built-in and not an external helper like [r2](https://github.com/mikeal/r2)?

**Comment by miherlosev** [comment]
It's impossible to send request to any resource with cookie (without accessing to [internal api](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/request-pipeline/header-transforms.js#L94))

Also if response contains 'Set-Cookie` header need an additional helper code to apply cookie for request chains (see https://testcafe-discuss.devexpress.com/t/making-http-requests-in-helpers/621/3).

**Comment by miherlosev** [comment]
https://stackoverflow.com/questions/56997198/implementing-fetch-api-testcafe

**Comment by rob4629** [comment]
Would this have any impact on the feature request I made regarding getting secure/`httponly` cookies?

https://github.com/DevExpress/testcafe/issues/4063

**Comment by miherlosev** [comment]
@rob4629 

No, this is another feature. The `t.request` feature will allow you to send HTTP request with the current cookie state.

**Comment by rob4629** [comment]
No worries, it still sounds good to me. Looking forward to when it's implemented

**Comment by rob4629** [comment]
Another question... like some people, I've been using ClientFunctions w/ Axios to send requests. These were working fine, but recently have been failing frequently due to `ClientFunction execution was interrupted by page unload. This problem may appear if you trigger page navigation from ClientFunction code.`.

Would the `t.request` function be able to wait until the page has completely loaded prior to executing the request?

**Comment by rob4629** [comment]
Is there an ETA on when this might be implemented? I'm really looking forward to using it.

**Comment by miherlosev** [comment]
The features that we are planning to implement are listed on the [Roadmap](https://devexpress.github.io/testcafe/roadmap/) page. The current feature is not on this list. I'm afraid I cannot provide you with any time frames as to when it will be implemented.

If this enhancement is very important for you, the PR is greatly appreciated.

**Comment by thxv3n0lvl** [comment]
I think this is similar to https://github.com/Codeception/CodeceptJS/blob/master/lib/helper/REST.js
are we looking for something like this?

**Comment by AndreyBelym** [comment]
The main idea behind this feature is similar, but API is not finalized yet.

**Comment by rob4629** [comment]
When this is implemented, is the plan for it to work on ALL supported browsers? We run tests in IE 11, and  I know it's not the greatest for supporting libraries (e.g. Fetch is unsupported).

**Comment by AlexKamaev** [comment]
@rob4629 we suppose that the `r.request` action will be a server-side action, so there will not be any browser specifics.

**Comment by rob4629** [comment]
That makes sense. Final clarification... will this be intended for API testing specifically, or is the intention for it to be alongside UI automation?

(_I'm currently looking in to API automation frameworks.... and if this is something TestCafe is planning to implement, then it might be useful for us to keep everything under the same product_)

**Comment by Dmitry-Ostashev** [comment]
We are considering implementing this action as a part of the TestController API to use it in the same test with the regular TestCafe actions.

**Comment by miherlosev** [comment]
Closed in favor https://github.com/DevExpress/testcafe/issues/4288.
