### ISSUE TITLE
Error raises during switching to Iframe in IE

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#2399]
There is no error on page without TestCafe
```js
import { Selector } from 'testcafe';

fixture `fix`
    .page `https://demos.devexpress.com/MVCxHTMLEditorDemos/Features/Features`;

test('t', async t => {
    await t
        .switchToIframe('#Html_DesignIFrame')
        .selectText(Selector('table').find('div').find('p'));
});
```

**Comment by LavrovArtem** [comment]
[Issue](https://github.com/DevExpress/testcafe-hammerhead/issues/1325) in `testcafe-hammerhead`

**Comment by AndreyBelym** [comment]
I close the issue because it is a duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/1325. Use https://github.com/DevExpress/testcafe-hammerhead/issues/1325 to track progress in resolving the issue.
