### ISSUE TITLE
APIv2: Implement user actions

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#240]
Notes:

- Should accept extended selector (Sizzle), isomorphic functions, isomorphic function results
- Should throw about missing `await` if it's fullfiled without listeners

TODO:

- [x] .click
- [x] .rightClick
- [x] .doubleClick
- [x] .drag
- [x] .dragToElement
- [x] .hover
- [x] .takeScreenshot
- [x] .navigateTo
- [x] .pressKey
- [x] .selectText
- [x] .selectTextAreaContent
- [x] .selectEditableContent
- [x] .typeText
- [x] .uploadFile
- [x] .clearUpload
- [x] .resizeWindow
- [x] .wait
- [x] .waitElement

**Comment by inikulin** [comment]
# .click

 - [ ] Create command class
-  [ ] Create API method
-  [ ] Implement and test option validation
-  [ ] Implement client command execution
-  [ ] Add functional tests for client command execution

**Comment by inikulin** [comment]
I'm working on this.

**Comment by AndreyBelym** [comment]
I'm working on .rightClick now.

**Comment by AndreyBelym** [comment]
I'm working on **.doubleClick** now.

**Comment by AndreyBelym** [comment]
Working on **.hover** now.

**Comment by AndreyBelym** [comment]
Working on **.drag** and **dragToElement** now.

**Comment by AndreyBelym** [comment]
Working on **.type** nowю

**Comment by AndreyBelym** [comment]
According to our documentation for 15.1:

**act.upload**
_Uploads a file or a set of files._

`act.upload( target, path )`
_This action uploads an individual file._

_Use the following variant of the user action to implement the uploading of multiple files at once._
`act.upload( target, paths )`

_If you need to imitate the browser's behaviour when a user clicks the Cancel button, use the following version of the user action._

`act.upload( target )`

So I suppose, that we need `.uploadFiles` and, ugh, `.uploadCancel` actions as well? \cc @inikulin.

**Comment by inikulin** [comment]
> If you need to imitate the browser's behaviour when a user clicks the Cancel button, use the following version of the user action.

This is something new to me. What does this mean? \cc @churkin @AlexanderMoskovkin

**Comment by AlexanderMoskovkin** [comment]
this is from our [15.1 documentation](http://testcafe.devexpress.com/Documentation/API_Reference/Test_Fixture_API/User_Actions/#actupload)
As a understand it just reset input's state to initial (when was no selected files for upload)

**Comment by inikulin** [comment]
Let's call it `clearUpload` or smthg like this then.

**Comment by inikulin** [comment]
I still thinking about renaming `upload` to `setUpload`. Not quite sure though

**Comment by VasilyStrelyaev** [comment]
> I still thinking about renaming upload to setUpload. Not quite sure though

That was the right state of mind. I just realized that `uploadFile` simply populates the input... well, there's not too much of upload...

**Comment by VasilyStrelyaev** [comment]
`populateUpload` as an option

**Comment by VasilyStrelyaev** [comment]
Is anyone receiving?

**Comment by inikulin** [comment]
???

**Comment by VasilyStrelyaev** [comment]
@inikulin coulc you please scroll up a bit

**Comment by inikulin** [comment]
Maybe `setFilesToUpload`?

**Comment by VasilyStrelyaev** [comment]
sounds good

**Comment by AlexanderMoskovkin** [comment]
So, if we change `uploadFile -> setFilesToUpload`, what about `clearUpload`. We leave it as is?

**Comment by VasilyStrelyaev** [comment]
Meaning "clear the upload object"... I, personally, don't mind.

**Comment by AlexanderMoskovkin** [comment]
We take a decision to rename `uploadFile` -> `setFilesToUpload`, and leave `clearUpload`. If all agree with this, @georgiy-abbasov please take care of this

**Comment by inikulin** [comment]
I agree

**Comment by AlexanderMoskovkin** [comment]
actions implementing done.
A couple of questions about the first comment

> Should accept extended selector (Sizzle), isomorphic functions, isomorphic function results

I suppose it'll be implemented in the #574 issue?

> Should throw about missing await if it's fullfiled without listeners

This is implemented already, am I right?

/cc @inikulin

**Comment by inikulin** [comment]
Yes to both questions. We can close it now
