### ISSUE TITLE
Add support of socks5 proxy with and without auth

### ISSUE THREAD

**Issue by gtroshin** [DevExpress/testcafe#2403]
### Are you requesting a feature or reporting a bug?

A feature.

### What is the current behavior?

When I pass socks5 host and port (with or without simple login/password auth) it fails with

2) - Error in fixture.beforeEach hook -
      Failed to connect to the proxy. Cannot establish tunneling connection to the host at "...".

### What is the expected behavior?

Should works

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by miherlosev** [comment]
Hi @tsboom,

Thank you for sharing this information. Since the issue is still actual, I will reopen it.

**Comment by AlexKamaev** [comment]
In order to keep our backlog actual, we decided not to implement this feature since its user demand is insufficient.
