### ISSUE TITLE
Investigate the possibility to collect debug info

### ISSUE THREAD

**Issue by kirovboris** [DevExpress/testcafe#2413]

**Comment by miherlosev** [comment]
For hammerhead we need the following info:
* stack trace for unhanded Promise rejection - add `process.on('unhandledRejection', error => { ...} `
* stack trace for TestCafe related scripts (`testcafe.js`, `hammerhead.js`, etc.) - add possibility to use unminified scripts

**Comment by AndreyBelym** [comment]
Let's make a list of features that will help to improve reproducing and debugging issues:

- [ ] Unminified client scripts - better and clearer stack traces in errors from browsers
- [ ] Source maps - better stack traces for both server and client
- [ ] `unhandledRejection` and `unhandledException` handlers in server code - capture stack traces on server when something unexpected happens
- [ ] capturing all console output on client and saving it on server - detailed debug information about client code execution
- [ ] debug log of browser connections & providers systems and native modules -  debugging issues with browser starting/stopping and window manipulations
- [ ] debug log of automation client scripts - debugging issues with element existence & visibility, events simulation
- [ ] debug log of driver client scripts - debugging pages & iframes loading issues
- [ ] capturing all network requests and responses to a file - reproducing issues on specific private pages
- [ ] capturing video of running browsers - useful for debugging automations and examining page's layout

**Comment by miherlosev** [comment]
> Source maps - better stack traces for both server and client

For client side I don't know how it will work because we modify the origin scripts.


> capturing all network requests and responses to a file

Should be done without testcafe or hammerhead to find problem with hammerhead server side proxying.


For other items there are no questions or remarks.

**Comment by dylang** [comment]
Suggestion:

## Save page source. 

This is similar to the screenshot feature, except it's saving the current state of the DOM to an HTML file.

The HTML is then easy to open in a browser and inspect the DOM.

This is useful in CI environments when tests fail, it could be something as simple as an unexpected DOM element change that's not possible to discover from a screenshot.

**Comment by dylang** [comment]
Hmm, might have solved my own request:

```js
	saveSource = async (filename: string) => {
        const getSource = ClientFunction(() => [
            '<html>',
            '<head>',
            document.head.innerHTML,
            '</head>',
            '<body>',
            document.body.innerHTML,
            '</body>',
            '</html>'
        ].join('\n'));

        const source = await getSource();

        return writeFileSync(filename, source, 'utf8');
    }
```

Note: the above is just an example, not necessary a robust solution for all situations.

**Comment by sivanisentinel** [comment]
do we have progress any with these enhancements?

**Comment by miherlosev** [comment]
Hi @sivanisentinel 

Basically, it's an internal task. It's necessary to reproduce the difficult and unstable problem. Also,  to process collected debug information, it's necessary to understand how TestCafe works internally. 
We are thinking about collecting the all network requests with full data (request, response, headers). But, it's not as easy as it might seem due to GDPR retrictions.

At present, we are working on the '[Debugging selectors](https://github.com/DevExpress/testcafe/issues/3244)'  feature. It's an end-user way to debug problematic selectors.

**Comment by sivanisentinel** [comment]
debugging  tools to investigate and reproduce  difficult and unstable problems is what I need..

**Comment by Dmitry-Ostashev** [comment]
@sivanisentinel Could you please describe what particular tools you need? You can create a separate issue for this.

**Comment by miherlosev** [comment]
Now, all the necessary debug information is collected. If we need some additional information, we'll collect it separately.
