### ISSUE TITLE
Support window automations on Linux Wayland

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#2415]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by miherlosev** [comment]
Hi @ChrisLane

It looks like Linux Wayland support is not a very popular request in the TestCafe community. If this capability is important in your usage scenario, you can try implementing the necessary functionality on your own. See the code structure and techniques in use at [testcafe-browser-tools](https://github.com/devexpress/testcafe-browser-tools).
