### ISSUE TITLE
Proxy handler result inconsistent with target object's state 

### ISSUE THREAD

**Issue by Aporrasniche** [DevExpress/testcafe#2424]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Test fails with error
```
      TypeError: Proxy handler's 'set' on a non-configurable and
      non-writable property on 'target' should either return false or be
      the same value already on the 'target'
```

If I had to guess the cause of the issue I would say the proxy handler method's reported result is inconsistent with the target object's state (remote device) and cannot be resolved due to the proxy object's immutability 

I ran this same test on an iPhone X using iOS 11.3/Mobile Safari 11 and the test passes properly

### What is the expected behavior?
Test passes with no errors

### How would you reproduce the current behavior (if this is a bug)?
Run example test on an iPhone 6 running iOS 10.1.1/Mobile Safari 10 (maybe all 10+?)

#### Provide the test code and the tested page URL (if applicable)
example js file provided on repo
```
import { Selector } from 'testcafe'; // first import testcafe selectors

fixture `Getting Started`// declare the fixture
    .page `https://devexpress.github.io/testcafe/example`;  // specify the start page


//then create a test and place your code there
test('My first test', async t => {
    await t
        .typeText('#developer-name', 'John Smith')
        .click('#submit-button')

        // Use the assertion to check if the actual header text is equal to the expected one
        .expect(Selector('#article-header').innerText).eql('Thank you, John Smith!');
});
```

### Specify your

* operating system: iPhone 6 iOS 10.1.1 on remote; Windows 10 64 bit on Desktop
* testcafe version: 0.20
* node.js version: 6.11.2

**Comment by miherlosev** [comment]
Hi @Aporrasniche 

At present, iOS 10.1.1 is in the discontinued state (see [IOS_version_history](https://en.wikipedia.org/wiki/IOS_version_history#Overview)).
We support and run our tests with [iOS 10.3.3](https://github.com/DevExpress/testcafe/blob/master/Gulpfile.js#L129) and [OS X 11.0](https://github.com/DevExpress/testcafe/blob/master/Gulpfile.js#L91) operation system versions.

Nevertheless, you can try to use the previous TestCafe releases (for example `0.18.0`) for testing on iOS 10.1.1.
