### ISSUE TITLE
Type definitions for Request Hooks

### ISSUE THREAD

**Issue by danroshko** [DevExpress/testcafe#2428]
### Are you requesting a feature or reporting a bug?
I'm requesting a feature.

### What is the current behavior?
Typescript compilation fails when trying to use Request Hooks.

### What is the expected behavior?
It is possible to write tests in Typescript and use request hooks.

### How would you reproduce the current behavior (if this is a bug)?

```ts
import { RequestMock } from 'testcafe'; // Error: Module 'testcafe' has no exported member 'RequestMock'.

const mock = RequestMock()
  .onRequestTo('')
  .respond('', 200);

fixture(`Test page`).page(`http://127.0.0.1:4200`);

test.only('Request Hooks', async t => {
  await t.addRequestHooks(mock); // Error: Property 'addRequestHooks' does not exist on type 'TestController'.
});

```

### Specify your

* testcafe version: 0.20.0
* node.js version: 10.0.0
* typescript version: 2.7.2

**Comment by miherlosev** [comment]
Hi @danroshko 

Type definitions is already in [PR](https://github.com/DevExpress/testcafe/pull/2423)
