### ISSUE TITLE
Add the modules license checker

### ISSUE THREAD

**Issue by kirovboris** [DevExpress/testcafe#2430]
- [x] https://github.com/DevExpress/testcafe
 - [ ] https://github.com/DevExpress/testcafe-browser-provider-browserstack
 - [ ] https://github.com/DevExpress/testcafe-browser-provider-saucelabs
 - [ ] https://github.com/DevExpress/testcafe-browser-provider-electron
 - [ ] https://github.com/DevExpress/generator-testcafe-reporter
 - [ ] https://github.com/DevExpress/generator-testcafe-browser-provider
 - [ ] https://github.com/DevExpress/testcafe-angular-selectors
 - [ ] https://github.com/DevExpress/testcafe-react-selectors
 - [ ] https://github.com/DevExpress/testcafe-vue-selectors

**Comment by AndreyBelym** [comment]
We also should enable license checking in our plugins and utilities:
 - [ ] https://github.com/DevExpress/testcafe-live
 - [ ] https://github.com/DevExpress/testcafe-browser-provider-browserstack
 - [ ] https://github.com/DevExpress/testcafe-browser-provider-saucelabs
 - [ ] https://github.com/DevExpress/testcafe-browser-provider-electron
 - [ ] https://github.com/DevExpress/generator-testcafe-reporter
 - [ ] https://github.com/DevExpress/generator-testcafe-browser-provider

**Comment by miherlosev** [comment]
To check other our repositories we need a module with simple interface: 
* if there are problem then log messages; 
* if all is ok then log success message.

@kirovboris Combine your code to the separate module `devexpress/license-checker` and after it we will apply license checking to all other repositores.

**Comment by kirovboris** [comment]
It'll take some time, because, obviously, we have different lists of excluded items for other modules. Besides, you can do it yourself.
