### ISSUE TITLE
Provide a way to pass settings from runner to fixtures

### ISSUE THREAD

**Issue by fpoppinga** [DevExpress/testcafe#2431]
### Feature Request
Provide a way to pass configuration from `Runner` to test fixtures. 

### What is the current behavior?
There is no way to pass any information from the TestCafé runner to the actual tests. 

### What is the expected behavior?
For our use case, we want to provide different configuration from various sources to the tests on a per-execution basis. This means that e.g. configuration files as proposed [here](https://testcafe-discuss.devexpress.com/t/pass-params-into-the-test-runner/283/3) are not a viable option. 

It would be great, if you could pre-fill the fixture context `fixtureCtx` from the TestCafé runner, like so: 

```ts
const tc = await createTestCafe();
const runner = tx.createRunner();

await runner
  .src(myFiles)
  .browsers(myBrowsers)
  .fixtureContext({
    mySetting: getSomeValueSomehow()
  })
  .run();
```
resulting in this test fixtures: 

```ts
fixture("My fixture")
  .before(fixtureCtx => {
    // fixtureCtx now equals 
    // {mySetting: ...}
  });

```

**Comment by AndreyBelym** [comment]
Hi @fpoppinga, you can use `process.env` to pass strings from runner to test code.

**Comment by fpoppinga** [comment]
@AndreyBelym, yes I know, but in my opinion a) `process.env` is not meant to be used this way, b) this works rather badly for more complex configuration data.

**Comment by Asuza** [comment]
I too would like to see this feature. I see no other good way to run the same test from two or more different runners with different configuration options. `process.env` does technically work, but it's hacky and can cause the test to get settings from the wrong runner.

**Comment by Artem-Babich** [comment]
Hi, you can use [userVariables](https://testcafe.io/documentation/402638/reference/configuration-file?search#uservariables) to pass additional data to the tests. You can define them in the configuration file as well as in your runner code:
`createTestCafe({userVariables: { url: 'test' }})`

```
import { userVariables } from 'testcafe';

fixture `Test user variables`

test('Type text', async t => {
    await t.expect(userVariables.url).eql('test')
});
```

Feel free to reopen this issue if this approach cannot be used in your usage scenario.
