### ISSUE TITLE
Make pressKey to work for elements within shadowDOM

### ISSUE THREAD

**Issue by ls84** [DevExpress/testcafe#2432]
### Are you requesting a feature or reporting a bug?
I am selecting an element like this
````const nameInput = Selector(() => component.shadow.querySelector('.nameInput'))````
It worked fine if the <input> element is outside of shadow root, like a normal element.

### What is the current behavior?
When I am testing
````
await t.typeText(nameInput, 'apple')
.pressKey('backspace')
````
nothing happens

I am on version 0.20.0

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by AndreyBelym** [comment]
Hi @ls84, I've reproduced the issue. I'll notify you when we will publish a new version with the fix to NPM.

**Comment by raphaellueckl** [comment]
Neither hover nor mouseclicks work combined with shadow dom. Any progress regarding this would be appreciated.

**Comment by AlexKamaev** [comment]
@raphaellueckl the initial issue is only about the `pressKey` action. We would like to research your issue in detail. Please create a separate bug report using this form https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md
Please also provide us with a sample demonstrating the issue.

**Comment by AlexKamaev** [comment]
@raphaellueckl the initial issue is only about `pressKey` action. We would like to research your issue in detail. Please create a separate bug report using this form https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md
Please also provide us with sample which demonstrates the issue.

**Comment by hartjus** [comment]
I'm running into the same issue with `.pressKey('enter')` on an input within a shadow DOM.  Any progress/updates on this?

**Comment by AlexSkorkin** [comment]
No updates yet. Our developers are still looking into this issue. You will be automatically notified if you track this issue once we make progress.

**Comment by matthewdouglas** [comment]
@AlexSkorkin Do you know if this is being actively worked on, or would PRs be welcomed?

**Comment by AlexSkorkin** [comment]
@matthewdouglas 
Since this issue is not in the current 'Sprint #37' milestone, your PR is welcome!

**Comment by saritha11** [comment]
I still see this issue, will this be fixed soon?

**Comment by Farfurix** [comment]
@saritha11 

Hello,

We plan to fix it. However, I cannot give you any estimate at the moment.

**Comment by karankumar7** [comment]
Any update on this ticket?

**Comment by alexey-lin** [comment]
@karankumar7 No news yet. We'll update this thread once we have any results. We would highly appreciate your PR.
