### ISSUE TITLE
Bug: Linux chromium screenshot: unable to locate page area

### ISSUE THREAD

**Issue by psi-4ward** [DevExpress/testcafe#2433]
`npx testcafe -s screens -S chromium tests`  

```
  Was unable to take a screenshot due to an error.

  Error: Unable to locate the page area in the browser window screenshot at
  .../screens/2018-05-18_09-27-20/test-1/Chrome_66.0.3359_Linux_0.0.0/errors/1.png, because the page area mark with ID 1491073397 is not found in
  the screenshot.
      at _callee$ (.../node_modules/testcafe/lib/screenshots/crop.js:95:31)
      at tryCatch (.../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (.../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (.../node_modules/regenerator-runtime/runtime.js:114:21)
      at step (.../node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at .../node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
      at run (.../node_modules/core-js/library/modules/es6.promise.js:75:22)
      at .../node_modules/core-js/library/modules/es6.promise.js:92:30
      at flush (.../node_modules/core-js/library/modules/_microtask.js:18:9)
      at process._tickCallback (internal/process/next_tick.js:172:11)
```

```js
// test.js
import { Selector } from 'testcafe';
fixture('t1').page('https://google.com');
test('My first test', async t => {
  await t.expect(Selector('not-exists').exists).ok();
});
```
* operating system: ArchLinux, KDE, Chromium 66.0.3359
* testcafe version: 0.20.0
* node.js version: v10.0.0

**Comment by AndreyBelym** [comment]
Could you please provide me the screenshot file that caused this warning?

**Comment by psi-4ward** [comment]
![1](https://user-images.githubusercontent.com/1191572/40223103-2c4e00d2-5a82-11e8-8675-4b3664feb9eb.png)

**Comment by AndreyBelym** [comment]
Hi @psi-4ward! Unfortunately, I can't reproduce the issue on my machine. I would try to figure out what's wrong with screenshots if you could provide me a remote session (trough VNC, TeamViewer, etc.). Also, I'm working on the screenshots code to enable capturing images through browsers' debug protocols. It must fix the issue, but I can't say it for sure without reproducing the issue. I'll notify you when a debug build is available.

**Comment by AndreyBelym** [comment]
Hi @amits1995. this functionality is implemented in https://github.com/DevExpress/testcafe/commit/2a748edbc31c98577d8ea3c89dd4c32e9a19b11a. I think we will release an alpha build next week.

**Comment by miherlosev** [comment]
Try the `0.20.4` version and feel free to reopen issue if problem still persists.

**Comment by gytisgreitai** [comment]
I'm having the same issue with IE11 on 0.20.4

````
  Error: Unable to locate the page area in the browser window screenshot at
  xxx\2018-07-02_06-28-29\test-2\IE_11.0.0_Windows_7.0.0\1.png,
  because the page area mark with ID 3405349736 is not found in the screenshot.
      at detectClippingArea
```

**Comment by AndreyBelym** [comment]
Could you please share the screenshot with me?

**Comment by gytisgreitai** [comment]
and today I cannot reproduce it :/ though yesterday it was almost 100% like this...
