### ISSUE TITLE
Wrong 'enter' key press simulation in Firefox

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#2435]
Test should hide the first grid column, but instead of this test sorts first column
```js
import { Selector } from 'testcafe';

fixture `fix`
    .page `http://dolzhikov-w10/181/RegressionTestsSite/ASPxGridView/Bugs/T634867.aspx`;

test('t', async t => {
    await t
        .setTestSpeed(0.2)
        .rightClick(Selector('a').withText('C1'))
        .pressKey('down down down down enter')
        .debug();
});
```
Please fix status panel UI too
![image](https://user-images.githubusercontent.com/12034551/40230736-5d5827b0-5aa1-11e8-902d-4604e7bfdfef.png)

**Comment by AlexKamaev** [comment]
I was not able to reproduce the issue with the 0.22.1-alpha.3 version. As for the status panel, it's displayed incorrectly because the page doesn't have the DOCTYPE definition
