### ISSUE TITLE
Cannot execute tests in Firefox

### ISSUE THREAD

**Issue by krilllind** [DevExpress/testcafe#2439]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Firefox webbrowser can not execute tests.

Application throws error:
`Uncaught JavaScript error "TypeError: Argument 4 of TouchEvent.initTouchEvent is not an object." on page`

### What is the expected behavior?
Would like to execute tests as in Chrome or Egde.

### How would you reproduce the current behavior (if this is a bug)?
Run a test in Firefox

#### Provide the test code and the tested page URL (if applicable)
```
"@fixture Authentication";
"@page [Can not de shown]

"@test"["Login (username & password)"] = {
    "1.Clear current session": function() {
        window.localStorage.clear();
        window.location.reload();
        act.wait(5e3);
    },
    "2.Click div": function() {
        act.click(".overlay");
    },
    "3.Press key TAB": function() {
        act.press("tab");
    },
    '4.Type in input "Username"': function() {
        act.type("#username", "MY_TEST_USER");
    },
    "5.Press key TAB": function() {
        act.press("tab");
    },
    '6.Type in password input "Password"': function() {
        act.type("#password", "MY_TEST_PASSWORD");
    },
    "7.Press key ENTER": function() {
        act.press("enter");
    },
    "5.Check login success": function() {
        eq($(".col-xs-12").find(" > h3:nth(0)").text(), "Welcome TEST_USER");
    }
};
```

### Specify your

* operating system: Windows 10 64bit
* testcafe version: 15.1.3
* node.js version: 8.11.1 (But are not you providing a Node.exe of your own?)
* Firefox version: 60.0.1

**Comment by MarinaRukavitsyna** [comment]
Hellom
We provide two TestCafe versions: a paid version with a recorder and an open source version. According to your description, you are using the former version. So, please use the DevExpress Support Center to submit tickets regarding your version (https://www.devexpress.com/Support/Center/Question/Create) as we generally process issues related to the paid TestCafe version there to avoid mixing two different versions. The GitHub channel is intended for the open-source version.

**Comment by mhyrka** [comment]
Was this issue ever addressed in the support center? I cannot seem to find this ticket.
