### ISSUE TITLE
APIv2: Implement frame switching

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#244]
- [x] `t.switchToIFrame(selector)`
- [x] `t.switchToMainWindow()`

**Comment by AlexanderMoskovkin** [comment]
I'm working on this

**Comment by AlexanderMoskovkin** [comment]
Do we leave the old behavior with js-errors in iframes?

When we are in the main window context or in a same-domain iframe context:
- if an error occurs in the main window we fail the test with the error
- if an error occurs in any same-domain iframe we fail the test with the error
- if an error occurs in any cross-domain iframe we ignore it

When we are in a cross-domain iframe context:
- if an error occurs on the main window or in any same-domain iframe we fail the test
- if an error occurs in the current cross-domain window we fail the test
- if an error occurs in any other cross-domain window we ignore it

/cc @inikulin

**Comment by inikulin** [comment]
Yep

**Comment by AlexanderMoskovkin** [comment]
I'd like to ensure one more detail. What the command should be failed if there is no an iframe with the specified selector, `switchToIframe` or the next action command in the iframe.
What we choose:
```js
try {
t.switchToIFrame(iframeSelector);
}
catch (err) {// iframe doesn't exist error}
```
or
```js
try {
t.switchToIFrame(iframeSelector).click(elementSelector);
}
catch (err) {// iframe doesn't exist error}
```

I prefer the first

**Comment by inikulin** [comment]
`switchToIframe` itself. It's like action error, we fail action if selector doesn't exists.
