### ISSUE TITLE
Scroll in nav menu should stay in a current position

### ISSUE THREAD

**Issue by MargaritaLoseva** [DevExpress/testcafe#2440]
Open https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/

Currently, if I select the Intercepting HTTP Requests topic in the nav menu, the nav menu scrolls up to an initial position. However, I expect that the menu stays in the current position (I want to see the child topic of the Intercepting HTTP Requests topic).

**Comment by titerman** [comment]
This issue is no longer relevant since it relates to the old TestCafe website.
