### ISSUE TITLE
Unable to detect touchable device

### ISSUE THREAD

**Issue by ferencbeutel4711** [DevExpress/testcafe#2448]
### Are you requesting a feature or reporting a bug?
thats a good question, probably reporting a bug

### What is the current behavior?
There seems to be no way to correctly detect a touchable device when using chrome mobile emulation

### What is the expected behavior?

```
'ontouchstart' in window
```

returns true when chrome mobile emulator is used

### How would you reproduce the current behavior (if this is a bug)?

```
  console.log(`touch? ${await testcafe.eval(() => {
    return 'ontouchstart' in window;
  })}`);
```

run testcafe with chrome mobile emulation (tested with iphone X)

### Specify your

* operating system:
tested on osx 10.13.12 and ubuntu 16.04
* testcafe version:
0.19.2
* node.js version:
8.9.1
* chrome version:
66.0.3359.139

Hello there,

our application is detecting touch devices to run different javascript code for the page initialization. We want to test that the touchable version is working fine using testcafe. In order to detect a touch device, we use the following logic:

```
((("ontouchstart" in window ||
                        !!(window.DocumentTouch && document instanceof DocumentTouch) ||
                        window.navigator.maxTouchPoints)) && 
                        !window._phantom && !window.phantom) ? true : false;
```

This works fine in the chrome devtools for example. Select a mobile device, reload the page and executing the code will return true.
However, when we use chrome mobile emulation provided by testcafe, the code returns false and there seem to be 0 registered touch event listener in the document.

Is there a better way to detect touch devices or is this an issue with testcafe mobile emulation?

**Comment by AndreyBelym** [comment]
Hi @ferencbeutel, could you please specify your TestCafe (you can get it with `testcafe -v`) and Chrome versions?

**Comment by AndreyBelym** [comment]
I've reproduced it in the latest TestCafe and Chrome. Looks like commands required to start touch emulation changed again, I'll fix it today.

**Comment by ferencbeutel** [comment]
Hey @AndreyBelym, thanks for your quick response!
Sorry to hear that the chrome api seems to be so unstable.
