### ISSUE TITLE
Unable to import { RequestHook,RequestMock, RequestLogger}  from 'testcafe';

### ISSUE THREAD

**Issue by rupeshmore** [DevExpress/testcafe#2449]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Cannot 
import { RequestHook,RequestMock, RequestLogger } from 'testcafe';
using typescript

Error: TypeScript compilation failed.
Module ''testcafe'' has no exported member 'RequestHook'.
Module ''testcafe'' has no exported member 'RequestMock'.
Module ''testcafe'' has no exported member 'RequestLogger'.

### What is the expected behavior?
import { RequestHook,RequestMock, RequestLogger } from 'testcafe';
should work with no typescript compilation error.

### How would you reproduce the current behavior (if this is a bug)?
Typescript project and import the above statement in a .ts file
No tsconfig file.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: No

Test code

```js
import { RequestHook,RequestMock, RequestLogger } from 'testcafe';
```

### Specify your

* operating system: Windows 8
* testcafe version: 0.20.0
* node.js version: 6.11.2

**Comment by miherlosev** [comment]
Hi @rupeshmore

This problem has already been fixed in `testcafe@0.20.1`.
