### ISSUE TITLE
Testcafe is not awaiting location changes correctly for chrome mobile emulation

### ISSUE THREAD

**Issue by ferencbeutel4711** [DevExpress/testcafe#2455]
### Are you requesting a feature or reporting a bug?
reporting a bug

### What is the current behavior?
When using chrome mobile emulation, testcafe is not correctly awaiting location changes when evaluating expressions

### What is the expected behavior?
Regardless of the device emulation mode, testcafe will await the location change before continuing

### How would you reproduce the current behavior (if this is a bug)?
Test for regular chrome:

```js
import {Selector} from 'testcafe';

fixture`Google Test`
  .page('https://www.google.com');

test('expect to wait for link click before continuing evaluations', async (testcafe) => {
  const inputField = Selector('#lst-ib');
  const submitButton = Selector('.jsb > center > [name=btnK]');

  await testcafe.typeText(inputField, 'testcafe');

  const oldUrl = await testcafe.eval(() => {
    return location.href;
  });

  await testcafe.click(submitButton);

  const newUrl = await testcafe.eval(() => {
    return location.href;
  });

  await testcafe.expect(oldUrl).notContains('search');
  await testcafe.expect(newUrl).contains('search');
});
```

Test for chrome mobile emulation (google changes the classes):

```js
import {Selector} from 'testcafe';

fixture`Google Test`
  .page('https://www.google.com');

test('expect to wait for link click before continuing evaluations', async (testcafe) => {
  const inputField = Selector('.gLFyf');
  const submitButton = Selector('.Tg7LZd');

  await testcafe.typeText(inputField, 'testcafe');

  const oldUrl = await testcafe.eval(() => {
    return location.href;
  });

  await testcafe.click(submitButton);

  const newUrl = await testcafe.eval(() => {
    return location.href;
  });

  await testcafe.expect(oldUrl).notContains('search');
  await testcafe.expect(newUrl).contains('search');
});
```

### Specify your

* operating system:
osx 10.13.2
* testcafe version:
0.19.2
* node.js version:
8.9.1
* chrome version:
66.0.3359.181 with mobile device emulation "iphone X"

Hi there,

recently I've discovered that testcafe seems to be not awaiting a location change, for example when navigating on a page by clicking a link, when executed in chrome mobile emulation mode.
It looks like chrome in mobile emulation mode isnt immediately changing the url after the link click which causes testcafe to continue with the test. However, I am not sure about this.

**Comment by AndreyBelym** [comment]
Hi @ferencbeutel4711, I've reproduced the problem, but I need some time to figure out its reason.

**Comment by ferencbeutel4711** [comment]
Hi @AndreyBelym, is there anything I can support you with in order to get this fixed?

**Comment by darin-sai** [comment]
We are experiencing the same with chrome iPhone 6 emulation. Works correctly in safari.

**Comment by hisaichi5518** [comment]
It seems to reproduce when the following code is called. but I do not know why...


https://github.com/DevExpress/testcafe/blob/9c96672c9c6a7fb50658a4c57f1e17ce645cd3b6/src/browser/provider/built-in/dedicated/chrome/cdp.js#L28

If you do not change the UserAgent, it will not be reproduced.
```
testcafe chrome:emulation:width=1125;height=2436;mobile=true;orientation=vertical;touch=true
```

**Comment by miherlosev** [comment]
Hi @hisaichi5518 

Thank you for your investigation.We will think what we can do with it.

**Comment by EladHeller** [comment]
I think i found the bug!
The user agent of chrome mobile emulation for safari is safari user agent, not chrome user agent.
So, in [This line](https://github.com/DevExpress/testcafe-hammerhead/blob/bc1f69788fda77563a7680af3c754cddb6d9b12c/src/client/utils/dom.ts#L589), Testcafe check if Object is location or not.
But Testcafe think the browser is safari and check it like safari, not like chrome.

Testcafe uses bowser to detect the browser according user agent. Maybe [this answer](https://stackoverflow.com/questions/28083715/how-to-detect-if-a-mobile-device-is-emulated-by-google-chrome) can help how to differentiate between chrome emulation and safari.

(I'm sorry about my English, i'm hoping it's understandable).
