### ISSUE TITLE
How to run test in full screen in testsuite

### ISSUE THREAD

**Issue by harryCompu** [DevExpress/testcafe#2456]
### Are you requesting a feature or reporting a bug?
I am trying to add few different keys in testsuite to run all test in full screen but not success-ed .

createTestCafe('localhost', 1337, 1338)
    .then(tc => {
        testcafe = tc;
        const runner = testcafe.createRunner();

        return runner
            .src('../ISPW-CES.js')
            .browsers(["chrome --start-full-screen"])
            .reporter('json', stream)
            .run({
                skipJsErrors: true,
                quarantineMode: true,
                selectorTimeout: 50000,
                assertionTimeout: 7000,
                pageLoadTimeout: 8000,
                speed: 0.5
            });;
    })
    .then(failedCount => {
        stream.end();
        testcafe.close();
    })
    .catch(error => {
        console.log(error);
        stream.write('{"error" : ' + error + '}');
        stream.end();
        runner.stop();
        testcafe.close();
    });

.browsers(["chrome --start-full-screen"]) is not working even I tried different options 

Can you help me on this ?
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by AndreyBelym** [comment]
Hi @harryCompu, try to use `chrome --kiosk`.
