### ISSUE TITLE
Disable skipLibCheck option in TypeScript compiler or Write tests for checking consistency of TS-definitions 

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#2457]
The `skipLibCheck` option enabled in the TypeScript test compiler disables syntax checks for our TypeScript definition file. We haven't caught [a mistake](https://github.com/DevExpress/testcafe/commit/3294ffd534f20b4b99a6c7ed92ac8052f3e675db#diff-6baf1ad70587978c1199d08cc7f8298fR1594) (a semicolon can't be used after a class definition) in the `v0.20.1` release.

**Comment by JonathanOuellet1275** [comment]
Just to tell you guys that i had to remove the ";" at the end of the class RequestHook on line 1594 to be able to compile

**Comment by AndreyBelym** [comment]
I've fixed definitions in `v0.20.2` but we really should do something to prevent such situations in future.

**Comment by JonathanOuellet1275** [comment]
thanks!

**Comment by AndreyBelym** [comment]
Closed by https://github.com/DevExpress/testcafe/commit/ca2b2dc167ae23a22dd0f01533a2a01e1bfa2e07
