### ISSUE TITLE
Test marked as passed even if t.typeText(...) throws an error

### ISSUE THREAD

**Issue by Masiako** [DevExpress/testcafe#2458]
### Are you requesting a feature or reporting a bug?
Reporting a bug.

### What is the current behavior?
Test is marked as passed even if an error is thrown.

### What is the expected behavior?
Test should be marked as failed.

### How would you reproduce the current behavior (if this is a bug)?
Please check the provided test code. The error happens as soon as e.g. t.typeText is used with an empty string.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: www.google.de

Test code

```js
import "testcafe";

fixture `minimal example` // declare the fixture
    .page("www.google.de");

test.only("minimal example for failed test marked as success", async (t: TestController) => {
    try {
        await t
            .typeText("#lst-ib", "")
            .click("#tsf > div.tsf-p > div.jsb > center > input[type=\"submit\"]:nth-child(1)");

    } catch (error) {
        await t.takeScreenshot();
    }
});
```

### Specify your

* operating system: Windows 10
* testcafe version: 0.20.0
* node.js version: 10.1.0

**Comment by AndreyBelym** [comment]
@Masiako, it's not a bug, it's just the way how JavaScript exceptions handling works. You suppressed exceptions by wrapping code in the `try { } catch () {}`  block. You should allow TestCafe to handle exceptions in tests, in other words, you should add `throw error;` to the `catch` clause of the block. 

Also note, that if you just want to take screenshot on a test failure, you can just use the [Screenshots on Fails](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-s---screenshots-on-fails) feature.
