### ISSUE TITLE
Docker (testcafe/testcafe): Can't connect to browser if concurrency is 2 or higher

### ISSUE THREAD

**Issue by dgieselaar** [DevExpress/testcafe#2461]
### Are you requesting a feature or reporting a bug?

Bug.

### What is the current behavior?

When using the Testcafe docker image (testcafe/testcafe), running the following command will fail:

```docker run -v path/to/tests/:/tests -it testcafe/testcafe 'firefox' ./tests/ --skip-js-errors --target=http://example.com --concurrency 2```

with the following error message:

> Running tests in:
> - Firefox 57.0.0 / Linux 0.0.0
>
> Adlinks
> ERROR The Firefox 57.0.0 / Linux 0.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.
>
> Type "testcafe -h" for help.

When using chromium, the error message is slightly different:

> ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
> 
> Type "testcafe -h" for help.

Both browsers work fine locally, with concurrency.

### What is the expected behavior?

The tests should be run concurrently and the test run should complete when concurrency is set.

### How would you reproduce the current behavior (if this is a bug)?

```bash
$ docker pull testcafe/testcafe
$ docker run -v path/to/tests/:/tests -it testcafe/testcafe 'firefox' ./tests/ --skip-js-errors --target=http://example.com --concurrency 2
```

### Specify your

* operating system: Windows
* testcafe version: from testcafe/testcafe
* node.js version: from testcafe/testcafe

**Comment by AndreyBelym** [comment]
Hi @dgieselaar, make sure that you've specified the `--no-sandbox` flag for chromium. Unfortunately I can't reproduce you problem with concurrency. You might have to change Docker's virtual machine settings to increase available RAM size. Do you use native Docker for Windows or Docker Toolbox/Docker Machine?

**Comment by karolisgrinkevicius** [comment]
I'm also getting it hanged up even with concurrency of 1 running it on browserstack. Downgraded `@0.20.2` to `@0.19.2` and it starts to works without hanging up.

`testcafe 'browserstack:IE@11:Windows 7' e2e-tests/test-suite.js --concurrency 1 --app 'yarn start' -q -e -S -s e2e-tests/logs`.

In `Browserstack` I can only see the log below 👇🏻

```sh
2018-05-31 07:27:44:0 REQUEST [2018-05-31 07:27:44:0] POST /session/bc1c8a199b3b85269883d0a6ae9461defc5585c5/url {"url":"http://172.18.15.215:60328/browser/connect/v0bAX~t"}
2018-05-31 07:27:44:0 RESPONSE {"state":"success","sessionId":"bc1c8a199b3b85269883d0a6ae9461defc5585c5","status":0,"value":null}
```

**Comment by iegor-zabielin** [comment]
@AndreyBelym i have exactly the same issue for chrome (testcafe docker image and macOS operation system). if the reason in Docker's virtual machine configuration, an you please specify which parameters is okay at least for concurrency 3?

**Comment by AndreyBelym** [comment]
@iegor-zabielin, likely it's due to high resources consumption by browsers in a virtual machine, especially if you use concurrency. Unfortunately I can't give you a specific configuration which is guaranteed to run fine. Try to increase available RAM size by using the `--shm-size` option:
```
docker run --shm-size=1gb
```
