### ISSUE TITLE
gulp-testcafe is not closing my puppeteer session

### ISSUE THREAD

**Issue by PriyoBh** [DevExpress/testcafe#2463]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?

Using gulp-testcafe to launch a test in puppeteer. The test launches and executed perfectly but the gulp task is not ending. This only happens with puppeteer and not with chrome, chrome:headless, firefox etc. I even ran - "testcafe puppeteer specs -r xunit:'./reports/report01.xml" from command line and there are no issues. It only happens with the **gulp-testcafe for puppeteer only.**

### What is the expected behavior?
The task should be completed once the test ends.

### How would you reproduce the current behavior (if this is a bug)?

1. Create any test (doesn't matter)
2. Install as dev dependency  - testcafe-browser-provider-puppeteer 
3. Create a gulp task and give puppeteer as the browser name.
4. Run the test using command line gulp.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
<<not relevant>>
Test code
Here is my gulpfile.js

const gulp = require("gulp");
const testcafe = require("gulp-testcafe");
const fs = require("fs");

gulp.task("runLoginTest", () => {
  return gulp.src("specs/login.js").pipe(
    testcafe({
      browsers: ["puppeteer"],
      reporter: {
        name: "xunit",
        outStream: fs.createWriteStream("./reports/report.xml")
      }
    })
  );
});

### Specify your

* operating system: macOS High Sierra Version 10.13.4 (17E202)
* testcafe version: 0.20.2
* node.js version: 9.11.0

**Comment by AndreyBelym** [comment]
Hi @PriyoBh, it's an implementation flaw in the `testcafe-browser-provider-puppeteer`. I've created an issue about it: https://github.com/jdobosz/testcafe-browser-provider-puppeteer/issues/3, you can track it to receive notifications about the progress in solving the problem. 

As a workaround, you can use `puppeteer` only as a browser installler, and use Chromium with TestCafe by specifying `chromium:$PATH_TO_CHROMIUM_BINARY` as a browser alias. Judging by [the code](https://github.com/GoogleChrome/puppeteer/blob/master/lib/BrowserFetcher.js#L55), `puppeteer` installs a Chromium copy into the `$PROJECT_ROOT/.local-chromium` directory.
