### ISSUE TITLE
Support 'ctrl+c' and 'ctrl+v' key combinations for copying/pasting selected text

### ISSUE THREAD

**Issue by alexschwantes** [DevExpress/testcafe#2466]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
The method t.pressKey('ctrl+c') does not simulate the actual key press of ctrl+c which would copy the selected text in the web browser. The same goes for ctrl+v for paste (although as ctrl+c doesn't work my test doesn't prove that ctrl+v doesn't work).

### What is the expected behavior?
t.pressKey('ctrl+c') should copy the selected text in the browser so that t.pressKey('ctrl+v') would trigger a pasting of the text in the browser

### How would you reproduce the current behavior (if this is a bug)?
see test code below for reproducible steps

#### Provide the test code and the tested page URL (if applicable)
Tested page URL: http://devexpress.github.io/testcafe/example/

Test code

```js
test('pressKey copy and paste ', async (t) => {
  await t.navigateTo('http://devexpress.github.io/testcafe/example/');
  await t.click('#tried-test-cafe');
  await t.typeText('#comments', 'The quick brown fox jumps over the lazy dog');
  await t.selectText('#comments', 4, 9);
  await t.pressKey('ctrl+c');
  await t.selectText('#comments', 10, 15);
  await t.pressKey('ctrl+v'); 
  await t.pressKey('ctrl+a'); // this works as expected but the others don't
});
```

### Specify your

* operating system: windows/linux
* testcafe version: 0.19.2 
* node.js version: v9.11.1

**Comment by AndreyBelym** [comment]
Hi @alexschwantes, unfortunately we don't support key combinations for clipboard opertaions As it's  stated in the [documentation](https://devexpress.github.io/testcafe/documentation/test-api/actions/press-key.html), I think it's more like a feature request than  a bug. 

As a workaround, you can take a text from a textarea with a `Selector`, and then use the `typeText` action with the [paste option](https://devexpress.github.io/testcafe/documentation/test-api/actions/action-options.html#typing-action-options) to simulate pasting from the system clipboard.

**Comment by alexschwantes** [comment]
Hi @AndreyBelym thanks for this. 
Yes I didn't quite get that the table in the documentation was only what was supported vs just an example of what combinations could be used. 

Unfortunately we only want to copy and paste a portion of the text. The copy and paste commands in the browser also copies the html that is selected eg. in a WYSIWYG editor it would copy font styling etc. I also think this issue #2075 would prevent us from using the typeText as it doesn't trigger the paste event.

**Comment by crki76** [comment]
Is any real workaround of this issue? Presently I need only crtl+v functionality (our system contains a copy functionality). When can this fix available? Thanks

**Comment by AlexKamaev** [comment]
@crki76
I think the solution provided by @AndreyBelym is the only appropriate solution, while this feature is not implemented.
We cannot give you any estimates when this feature will be available.

**Comment by saripr** [comment]
In my website, there is an option for copying some text to the clipboard. I want my tests to create a file and paste those contents to it and assert the content. Is there a workaround for it?

**Comment by AlexSkorkin** [comment]
No other workarounds are available.

**Comment by TempeBrennan** [comment]
I found latest doc write support ctrl+c
![image](https://user-images.githubusercontent.com/51563666/83375033-25d6a280-a400-11ea-94af-9180f67473f9.png)
https://devexpress.github.io/testcafe/documentation/reference/test-api/testcontroller/presskey.html

Does this means we supported to latest version?

**Comment by AlexanderMoiseev** [comment]
Hi @TempeBrennan, the part you mentioned is about browser events in general. Supported combinations are listed below. We cannot give you any estimates as to when we will support other combinations.
