### ISSUE TITLE
RequestMock response chaining for the same onRequestTo match

### ISSUE THREAD

**Issue by robokozo** [DevExpress/testcafe#2477]
### Are you requesting a feature or reporting a bug?
Feature - create an easy way to simulate difference responses from a server for the same endpoint

I test a number of scenarios where I would like to have a mocked endpoint return different data. 

### What is the current behavior?

```js
const mock = RequestMock()
.onRequestTo("http://localhost:8080/api/people").respond([])
.onRequestTo("http://localhost:8080/api/people").respond([{ name: "Bruce" }], 200);
```
Will only ever return []

An alternative syntax could be something like

(Taking this great suggestion into consideration: https://github.com/DevExpress/testcafe/issues/2425)
```js
const mock = RequestMock()
.onRequestTo("http://localhost:8080/api/people")
.responseSequence([{
    body: [],
},
{
    body: [{ name: "Bruce" }],
    statusCode: 200,
    delay: 2000
}]);
```

I would expect both these cases to return ```[]``` the first time it is called and ```[{ name: "Bruce" }]``` afterwards.

My current workaround looks like this:
```js
let callCount = 0;
const mock = RequestMock()
.onRequestTo("http://localhost:8080/api/people").respond((req, res) => {
    if (callCount === 0){
        res.setBody([]);
    }
    else {
        res.setBody([name: "Bruce"]);
    }

    callCount++;
})
```
### Specify your

* operating system: Windows 10
* testcafe version: "^0.20.2",
* node.js version:  8.9.4

**Comment by davidcunha** [comment]
Hello all,

I was about to create an issue about this situation too, but glad to see that it's on "Featured Proposals" 👏At this moment I'm not able to test a lot of features because I simply cannot get different responses from the same request, e.g, listing addresses -> deleting an address -> listing addresses to validate the diff.

**Comment by miherlosev** [comment]
Hi @davidcunha 

> At this moment I'm not able to test a lot of features because I simply cannot get different responses

Could you please clarify your scenario in more detail?

**Comment by miherlosev** [comment]
@davidcunha
For your scenario, use 'RequesMock' with a callback function - it is a recommended way (it's not a workaround).
 
> I would prefer a way to assign different RequestMocks to the same test and indicate, by order in chaining or some kind of parameter
At present, we have only one precise criterion - a response mock call number. If you know another criterion, please let us know.
For 'some kind of parameter', you can use a separate variable.

**Comment by knanduri** [comment]
@miherlosev 
I am a little confused on how to use the callback function but I have tried a different approach. Below is the test code 

```
import pageUrl from ‘Urls’;

const mockRespone1 = [];
const mockResponse2= [{ name: "Bruce" }];

export const mock = (mockResponse, status = 200) => RequestMock()
  .onRequestTo("http://localhost:8080/api/people")
  .respond(mockResponse, status);

fixture `Try mocks with different responses`
  .page(pageUrl);

test
  ('should return different responses ’, async browser => {
       await browser.addRequestHooks(mock(mockResponse1));
       await browser.expect(Selector(‘#name’)).exists.notOk();
       await browser.removeRequestHooks(mock(mockResponse1));
       await browser.addRequestHooks(mock(mockResponse2));
       await browser.navigateTo(pageUrl);  //Doesnt necessarily have to be a refresh here , but click on a button that triggers the same API again should also return
       await browser.expect(Selector(‘#name’)).exists.ok();
  });

```
But this kind of did not work for me , it always returns the mockResponse1. I was expecting removerequesthooks to remove the existing hook and add it again with the new response but it was always returning the response with the mockResponse1 

Let me know if my understanding is wrong in this approach but we also have many tests which need different responses but with same requests

**Comment by Farfurix** [comment]
@knanduri 

Hello,

I corrected your example. Please take special note of the "First mock" comment and the ["assertion" syntax](https://devexpress.github.io/testcafe/documentation/test-api/assertions/assertion-api.html#ok):
```js
import { RequestMock, Selector } from 'testcafe';

const pageUrl = 'http://example.com/';

const mockResponse1 = '<html><head></head><body<p>mockResponse1</p></body></html>';
const mockResponse2 = '<html><head></head><body><p>mockResponse2</p><div id="name"></div></body></html>';

const mock = mockResponse => RequestMock()
    .onRequestTo('http://example.com/')
    .respond(mockResponse, 200);

const mock1 = mock(mockResponse1);
const mock2 = mock(mockResponse2);

fixture`Try mocks with different responses`
    .page(pageUrl);

test
    .requestHooks(mock1) // [!] First mock
    ('should return different responses', async t => {
    await t.expect((Selector('#name')).exists).notOk(); // [!] "assertion" syntax
    await t.removeRequestHooks(mock1);

    await t.addRequestHooks(mock2);
    await t.navigateTo(pageUrl);
    await t.expect((Selector('#name')).exists).ok();
});

```

Result:
```
 Running tests in:
 - Chrome 74.0.3729 / Windows 10.0.0

 Try mocks with different responses
 √ should return different responses


 1 passed (1s)
```
