### ISSUE TITLE
Error: TypeScript compilation failed. Cannot find module 'testcafe' when running typescript tests via the testcafe container

### ISSUE THREAD

**Issue by vigie** [DevExpress/testcafe#2478]
The testcafe docker image contains the testcafe binary, but not it seems the testcafe type definition files. As a result, attempting to use the container to run tests written in typescript will fail with the above problem.

The docker image should also include the type definition file for testcafe.

The workaround is to provide the definition file as part of the source code being mounted as a volume to the container, probably by first running `npm install testcafe`, but this somewhat defeats the purpose of running from a container in the first place.

**Comment by AndreyBelym** [comment]
Hi @vigie, yeah, definitions aren't in the image due to missing entry in https://github.com/DevExpress/testcafe/blob/master/.dockerignore. I'll fix it and rebuild the image ASAP.

**Comment by AndreyBelym** [comment]
`.dockerignore` is fixed and Docker image is updated, you can run `docker pull testcafe/testcafe` to get version with the fix. Feel free to reopen the issue if it doesn't work with your configuration.
