### ISSUE TITLE
Clicking a dynamicaly created button does not work

### ISSUE THREAD

**Issue by nicholas-valiente** [DevExpress/testcafe#2479]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
On clicking a dynamically created button nothing happens.

### What is the expected behavior?
On clicking a dynamically created button the onclick() fires

### How would you reproduce the current behavior (if this is a bug)?
at the website [Qantas QA]https://www.phptravels.net/hotels/detail/singapore/rendezvous-hotels/24-12-2018/25-12-2018/2/0l) attempting to use the click function on the "book now" button does nothing.
To make sure it was not some other problem i have tried it with Chrome, FF, edge and IE with no luck. However it works perfectly fine with selenium.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://www.phptravels.net/hotels/detail/singapore/rendezvous-hotels/24-12-2018/25-12-2018/2/0

Test code

```ts
 const bookingButton = await Selector(".bgwhite > tbody:nth-child(7) > tr:nth-child(1) > td:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > button:nth-child(1)");
    const rooms = await Selector(".bgwhite");

    console.error(await bookingButton.visible);
    console.error(await bookingButton.attributes);
    await t
        .hover(rooms)
        .hover(bookingButton)
        .expect(bookingButton.exists).ok

    console.error(await bookingButton.visible);
    await t
        .debug()
        .click(bookingButton)

    console.error("button aparently clicked");
```

### Specify your

* operating system: Windows 10 home
* testcafe version: 0.20.2
* node.js version:  8.11.1 (x64)

**Comment by AndreyBelym** [comment]
Hi @nicholas-valiente, I've reproduced the issue. I need time to investigate the problem.

**Comment by AlexKamaev** [comment]
Hi @nicholas-valiente 
I've researched the issue and think that it is caused by invalid markup. I've inspected markup in Chrome `View page source` mode and found that your form is located directly in a table like in code below:

```HTML
<div class="panel-heading go-text-right panel-default ttu">Available Rooms</div>
    <table class="bgwhite table table-striped">
        <form action="https://www.phptravels.net/hotels/book/Rendezvous-Hotels" method="GET">
            <input type="hidden" name="adults" value="2" />
            <input type="hidden" name="child" value="0" />
            <input type="hidden" name="checkin" value="24/12/2018" />
            <input type="hidden" name="checkout" value="25/12/2018" />
            <input type="hidden" name="roomid" value="51" />
           ...
        </form>
```

It is not valid. If you open your site in the `Elements` tab of Chrome Developer Tools you'll find that this markup is processed incorrectly. See the code below:

```HTML
<table class="bgwhite table table-striped">
    <form action="https://www.phptravels.net/hotels/book/Rendezvous-Hotels" method="GET"></form>
    <input type="hidden" name="adults" value="2">
    <input type="hidden" name="child" value="0">
    <input type="hidden" name="checkin" value="24/12/2018">
    <input type="hidden" name="checkout" value="25/12/2018">
    <input type="hidden" name="roomid" value="51">
```

In Chrome, the form does not contain input elements, and that's why the submit button does not work under TestCafe.
If you modify your markup in the way when forms are not located in the table, it all should work correctly.
