### ISSUE TITLE
[RequestMock] Add a warning with a clear message when CORS validation is failed

### ISSUE THREAD

**Issue by davidcunha** [DevExpress/testcafe#2482]
I'm testing to mock a remote API endpoint (http://remote-api.com/api/auth?user_type=customer) that is being called with "isomorphic-fetch" when filling a form and clicking in a simple submit button. It seems that the mock is returning HTTP status 222. Does this means it can be a CORS issue? Or a bug of the RequestMock?

Tested page URL: http://localhost:3000/

Test code

```js
const mock = RequestMock()
  .onRequestTo('http://remote-api.com/api/auth?user_type=customer')
  .respond({
    result: null,
    errors: [
      {
        message: 'Incorrect username or password.',
      },
    ],
  });

fixture('As a customer I want to be able to sign in')
  .page('http://localhost:3000/login')
  .requestHooks(mock);

test('Login with incorrect credentials', async (t) => {
  await t
    .typeText(Selector("input[name='email']"), 'joe@example.com')
    .typeText(Selector("input[name='password']"), 'password')
    .click(Selector("input[type='submit']"));
  const location = await t.eval(() => window.location);
  await t.expect(location.pathname).eql('/login');
});

```

* operating system: Mac OS X 10.13.4
* testcafe version: 0.20.0
* node.js version: 8.11.1

**Comment by davidcunha** [comment]
By adding nock as dependency and `.reply(200, jsonMockedResponse, { 'Access-Control-Allow-Origin': '*'});` the request was correctly intercepted. But it means there must be some bug with RequestMock.

**Comment by miherlosev** [comment]
Hi @davidcunha 

Yes, your are right. It's a CORS issue. You need to change your code as follows:

```js
const mock = RequestMock()
  .onRequestTo('http://remote-api.com/api/auth?user_type=customer')
  .respond({
    result: null,
    errors: [
      {
        message: 'Incorrect username or password.',
      },
    ],
  }, 200, {'Access-Control-Allow-Origin': '*'});
```

From our side we will add a warning with a clear message for this case.

**Comment by miherlosev** [comment]
I am working on it
