### ISSUE TITLE
Unable to test anything after successful login on h2database [hammerhead not loaded after redirect]

### ISSUE THREAD

**Issue by cmichon** [DevExpress/testcafe#2486]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
After a successful login on a memory-only database (h2-1.4.196 from h2database.com), it's impossible to perform any action with the browser anymore as apparently the hammerhead status bar does not show up. This happens after a redirect from the successful login.

### What is the expected behavior?
I would expect the hammerhead status bar to stay alive and to be able to complete any new action.

### How would you reproduce the current behavior (if this is a bug)?
Download h2-1.4.196.jar
Launch the local server: java -jar h2-1.4.196.jar
Testcafe with either ie,edge,chrome or firefox will fail (use test-h2-login.js below)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: http://localhost:8082

Test code

```js
// test-h2-login.js:
import { Selector } from 'testcafe';

fixture('First fixture')
  .page('http://localhost:8082');

test('First test', async t => {

  await t
    .typeText('form#login input[name=driver]','org.h2.Driver',{replace:true})
    .typeText('form#login input[name=url]','jdbc:h2:mem:',{replace:true})
    .typeText('form#login input[name=user]','sa',{replace:true})
    .click('form#login input[type=submit][value=Connect]')
    .debug() // this allows to see the debug is not functional after the redirect. Any other interaction with the redirected page is also impossible

});
```

### Specify your

* operating system: Win10 enterprise
* testcafe version: 0.20.2
* node.js version: 8.11.1

**Comment by AndreyBelym** [comment]
Hi @cmichon! Unfortunately the H2DB control page is built upon the [obsolete <frameset> feature](https://www.w3.org/TR/html/obsolete.html#non-conforming-features), and we don't support pages that contain the `<frame>` and `<frameset>` tags. Only `<iframe>` is supported.

**Comment by cmichon** [comment]
Hi @AndreyBelym: that would discard entirely TestCafe from my comparative study. This is unfortunate...

Though I understand the decision taken (obsolescence of several legacy html markers), there are plenty of sites out there still using these markers.

FWIW, Cypress and CodeceptJS have no issue at all supporting H2 database web application and its frame/frameset legacy markers.
