### ISSUE TITLE
Custom Repoter stdout

### ISSUE THREAD

**Issue by hauptrolle** [DevExpress/testcafe#2488]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

I was trying to build a custom reporter which creates a html file. Along to the custom reporter I want to use the spec reporter for reporting to stdout. I get the following error:
`ERROR Multiple reporters attempting to write to stdout: "spec, html". Only one reporter can write to stdout.
`

As you can see in the code below the custom reporter does not write anything to stdout.

### What is the expected behavior?

I can use a custom report along to the default ones.

### How would you reproduce the current behavior (if this is a bug)?

Use the code below as a custom reporter together with the default spec reporter.
For example: `-r spec,html`

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: -

Test code

```js
export default function () {
    return {
        noColors:    true,

        reportTaskStart () {

        },

        reportFixtureStart () {

        },

        reportTestDone () {

        },

        reportTaskDone () {

        }
    };
}

```

### Specify your

* operating system: MacOS High Siearra 10.13.4
* testcafe version: ^0.20.1
* node.js version: v8.8.1

**Comment by AndreyBelym** [comment]
Hi @hauptrolle!

In your particular case your reporter doesn't write anything at all. However, if you use [output helpers](https://devexpress.github.io/testcafe/documentation/extending-testcafe/reporter-plugin/helpers.html#output-helpers)(which is *highly* recommended) to output something, it will be reported to `stdout` by default, and it might break some other reporter's output. To prevent this, you should redirect output to a file.

I understand that using `stdout` for both reporters can be useful for debugging while implementing a reporter. However, you can use the `tail -f $filename &` [command](https://superuser.com/a/316423) to read contents of a file in the background and output it to the console.
