### ISSUE TITLE
CLI TestCafe crashes when the test contains test cases

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#249]
It seems the error is in the reporter (I've tried with `json` and default reporters)
Run any test with `test cases` from the CLI:
```ShellSession
$ node bin/testcafe chrome D:/Tests/test.test.js

Running tests in: Chrome 47.0.2526 / Windows 10 0.0.0

  test (D:\Tests\test.test.js)



  1 passed (10s)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EIO
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)

```

I'll research this a little later if nobody takes it

**Comment by georgiy-abbasov** [comment]
For now we know the reason of this problem.
[The problem relates to the `testcafe-browser-natives` module](https://github.com/DevExpress/testcafe-browser-natives/issues/58)
