### ISSUE TITLE
Old website, why is it still online?

### ISSUE THREAD

**Issue by sebastiaanviaene** [DevExpress/testcafe#2491]
Hey,

First I want to express how much I love using testcafe. There is just a strange thing I'm curious about.
Why are you guys still keeping online the old version of TestCafe on : https://testcafe.devexpress.com/ ? When people google for testcafe this comes up above the "real" website : https://devexpress.github.io/testcafe/ . On the old site it has outdated information about the project, still has this HUGE payment yearly which will scare off potential users and the last version available there is from 17 January 2017. I would suggest to remove this old website and redirect it to the new one to avoid confusion.

**Comment by MarinaRukavitsyna** [comment]
Hi Sebastiaan,
Thank you for your words.
I would like to note that we provide two TestCafe versions: a paid version **with a recorder** (https://testcafe.devexpress.com/) and an open source version without visual elements (https://github.com/DevExpress/testcafe). These versions are different.
We are now working on a paid TestCafe Studio, which is based on our current open-source version. It will support all features of the open-source TestCafe, but will also provide a visual test recorder with the ability to record additional steps for a recorded test. Once we release it (this summer), the old paid version (including the site) will be substituted with the new TestCafe Studio.

**Comment by maertz** [comment]
@MarinaRukavitsyna awesome, is the ETA for this summer still realistic? Is it possible to obtain the created tests with the new visual recorder (open source core) I've seen the test files are slightly different - if not, is there any plan to provide a migration script to convert these?

Sincerely Ben

**Comment by MarinaRukavitsyna** [comment]
@maertz 
We are putting the finishing touches to TestCafe Studio and are going to release it soon. Currently, we do not have the exact release date because thorough testing is required.
 
>>Is it possible to obtain the created tests with the new visual recorder
You can open .js tests in TestCafe Studio, continue developing them using an API or/and run them as is. The only limitation is that it is impossible to continue recording an existing .js test since the latter has a non-supported format.

**Comment by maertz** [comment]
@MarinaRukavitsyna Thank you very much for your quick response. Sounds promising! Good luck with the testing phase 👍
