### ISSUE TITLE
Run tests in different browsers sequentially

### ISSUE THREAD

**Issue by Lukas-Kullmann** [DevExpress/testcafe#2495]
Is there a way to make tests run as soon as a browser is connected? Currently if you run tests in multiple browsers at the same time, browsers wait for each other before running the tests. 
This is not desirable for us since we use browserstack and our license only allows one connection at a time, but we want to run the tests in five different browsers. So we would like to run the tests in these browsers sequentially.
Is there a possibility to do this (e.g. by passing some option to the test run)?

**Comment by miherlosev** [comment]
At present, you can do it by running TestCafe for each browser.
```js
testcafe "browserstack:Chrome@67.0:Windows 10" /tests
testcafe "browserstack:Firefox@60.0:Windows 10" /tests
testcafe "browserstack:Internet Explorer@11.0:Windows 10" /tests
etc.
```

TestCafe does not allow running tests in several browsers sequentially at the level of one test run.

**Comment by nabrahamson** [comment]
I hope it's alright to add this code snippet to this closed issue. 
@Lukas-Kullmann 

I've figured out a way to do this in a scripted node application using async/await. Please see the code below

```
const browsers = [
  ['browserstack:edge@17.0:Windows 10', 'browserstack:chrome@68.0:Windows 10'],
  ['browserstack:firefox@61.0:Windows 10', 'browserstack:firefox@61.0:OS X High Sierra'],
  ['browserstack:chrome@68.0:OS X High Sierra', 'browserstack:safari@11.1:OS X High Sierra'],
];

const runTest = async browser => {
  console.log('starting tests');
  await createTestCafe('localhost', 1337, 1338)
    .then(tc => {
      testcafe = tc;
      const runner = testcafe.createRunner();

      return runner
        .src(['web-tests/*.ts'])
        .browsers(browser)
        .run();
    })
    .then(async failedCount => {
      console.log('Tests failed: ' + failedCount);
      await testcafe.close();
      return;
    });
}

const runAllBrowsers = async () => {
  for (const browser of browsers) {
    await runTest(browser);
  }
}
```

Adjust the browsers array to include the browsers you want to execute your tests against. The array may be a list of strings, or arrays containing browsers to run parallel. In my case, I can reliably run against 2-3 browsers synchronously.
