### ISSUE TITLE
Should Grab updated values of elements when they are sorted in DOM

### ISSUE THREAD

**Issue by ZayanNadeem** [DevExpress/testcafe#2496]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
I am trying to compare the values with in a column of a table. The functionality I am testing is sorting the column. So after the sort button is clicked. I grab the rows in a loop and compare the value of the top with bottom asserting that top value will be lower than the bottom one. 
I use the child method with .nth() to grab the values. And I grab these values after I sort them but it picks the values that were originally rendered. 
I removed the loop for now

### What is the expected behavior?
It should be grabbing the updated values, not the one rendered originally when the page loaded. 

#### Provide the test code and the tested page URL (if applicable)
Tested page URL:

Test code

```js
await t.click(Selector('div.fixed-column-header .ColHead.leaf.sortable').withText('Trustee')); // this click is supposed to sort the list
const row1 = await trustloanCol.child('[id*="_2"]').nth(0).innerText;
    const row2 = await trustloanCol.child('[id*="_2"]').nth(1).innerText;
    const row3 = await trustloanCol.child('[id*="_2"]').nth(2).innerText;
    await t
      .expect(row1.exists);
    await t
      .expect(row2.exists);    
    await t
      .expect(row2).gte(row1);
    await t
      .expect(row3).gte(row2); 
  });
```

### Specify your

* operating system: Windows 10 Pro
* testcafe version: 0.20.1
* node.js version: 8.9.4

**Comment by AndreyBelym** [comment]
Hi @ZayanNadeem, unfortunately I can't reproduce the problem without the tested page. Maybe sorting takes to much time, and you have to put `await t.wait()` between the click and assertion code. Maybe sorting causes only changes in visible order of the elements, but doesn't change their order in DOM.

There also errors in your assertions:
1) When you use `t.expect`, you always should use an [assertion method](https://devexpress.github.io/testcafe/documentation/test-api/assertions/assertion-api.html) as the second part of an assertion. E.g. `await t.expect(row1.exists).ok()`;

2) `row1` has the value of the `innerText` property of a Selector, it is just a string and doesn't have the `exists` property. You should check a Selector for existence, and then retrieve its `innerText` property:
```
const row1Selector = await trustloanCol.child('[id*="_2"]').nth(0);

await t.expect(row1Selector.exists).ok();

const row1 = await row1Selector.innerText;
```

**Comment by ZayanNadeem** [comment]
Hi @AndreyBelym, thank you for getting back to me quickly. You comment really helps. Let me take a look at the sorting method and get back to you with what I find.
Also, Thank you for pointing out my errors in my test cases.

**Comment by ZayanNadeem** [comment]
@AndreyBelym I just checked, so the system I am working on is legacy. what it is doing is just an XHR request which sends back a HTML/text based response. So, in a way the DOM is being replaced but the Selector still selects the data according to original DOM that loaded. Is there a way I can ask testcafe to forget the original DOM and read the new one again? Or is there any other way I can test I can do?

**Comment by miherlosev** [comment]
@ZayanNadeem 

I found that you don't specify an [assetion method ](https://devexpress.github.io/testcafe/documentation/test-api/assertions/assertion-api.html) in your code

```js
await t
      .expect(row1.exists); // Should be replaced with .expect(row1.exists).ok();
    await t
      .expect(row2.exists);
```

**Comment by ZayanNadeem** [comment]
@miherlosev I figured out that my sort was sending me a response back and testcafe was adding it to the list. So if my list was 10 items. sorting it would result in 20 items. the last 10 were sorted.

Also, i added the changes that both you and @AndreyBelym recommended. I was apparently testing a lot of items wrongly! Thanks for helping me out.
