### ISSUE TITLE
Allow TestCafe to be used for Browser Automation only (no testing)

### ISSUE THREAD

**Issue by HopefulLlama** [DevExpress/testcafe#2501]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
A test fixture is required for browser automation to work. The test controller must be run within the context of a test.

### What is the expected behavior?
Browser automation to work regardless of whether in or outside the context of a test

### How would you reproduce the current behavior (if this is a bug)?
Execute some browser automation outside of a test fixture.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js
const { t } = require('testcafe');

t.navigateTo('https://github.com/DevExpress/testcafe/issues/new');
```

### Specify your

* operating system: Windows 10
* testcafe version: 0.20.3
* node.js version: 8.10.0

**Comment by miherlosev** [comment]
> Execute some browser automation outside of a test fixture.

Could you please describe the scenario where it is necessary?

**Comment by tk8817** [comment]
This would also allow TestCafe to be easily adopted by teams who are currently using Selenium or another test framework such as Cucumber, Mocha, or Jest. Great request.

**Comment by HopefulLlama** [comment]
Is there any progress on this request?

**Comment by AndreyBelym** [comment]
We haven't made much progress in this direction. Different TestCafe subsystems like сompilers and browser connections are tightly coupled, so it will take a lot of time to separate the browser automation subsystem from other TestCafe code.
 
However, we would like to have this feature in TestCafe, so it will be nice if you make a PR.

**Comment by miherlosev** [comment]
Hi folks,

Extracting the browser automation part from TestCafe would require numerous changes, and we do not see much interest in this among the community. This is why, we decided to not implement this feature. However, if someone creates a PR, we will review it.
