### ISSUE TITLE
When a report is output to a file, the process terminates before the file buffer is written to a disk

### ISSUE THREAD

**Issue by MarinaRukavitsyna** [DevExpress/testcafe#2502]
### Are you requesting a feature or reporting a bug?
A bug

### What is the current behavior?
When a report is output to a file, the process terminates before the file buffer is written to a disk

### What is the expected behavior?
TestCafe  should wait for the "finish" event when test run is finished.

### Specify your

* testcafe version: 0.20

**Comment by LitterBeach** [comment]
HI, I am wondering if you guys have an estimate time on how soon will this issue being addressed?Thank you.

**Comment by AndreyBelym** [comment]
I'm working on it.
