### ISSUE TITLE
Can we make use of more CPU cores?

### ISSUE THREAD

**Issue by ClaytonAstrom** [DevExpress/testcafe#2504]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
Testcafe seems to only use 1 cpu, capping at ~20 remote connections

### What is the expected behavior?
Testcafe should be able to make use of more cores

### How would you reproduce the current behavior (if this is a bug)?
In AWS, if I create a Fargate container with 1vCPU and 2GB memory, I can connect around 20 remotes.  If I create a container 4vCPU and 8GB memory, I still can only connect around 20 remotes.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:  alpine linux
* testcafe version:  0.20.3
* node.js version:  8.9.3

**Comment by miherlosev** [comment]
Hi @ClaytonAstrom,

At present, TestCafe executes tests using a single thread. Implementing a multi-thread test execution flow requires significant changes in the testcafe architecture. Right now, we see little demand for this feature in the community. I'm going to close this issue as we don't have plans to implement this in the near future.
