### ISSUE TITLE
File upload doesn't work with inputs with a required attribute

### ISSUE THREAD

**Issue by artykr** [DevExpress/testcafe#2509]
### Are you requesting a feature or reporting a bug?

A bug

### What is the current behavior?

Forms with the file upload fields that have a `required` attribute do not pass HTML5 built-in validation on submit after the upload field has been populated using `setFilesToUpload` method.

### What is the expected behavior?

The form with a required filed upload field should be able to be submitted.

### How would you reproduce the current behavior (if this is a bug)?

1. Create a simple page:
```html
<html>
<body>
	<form>
		<input type="file" id="file-upload" required>
		<button id="submit-button">Submit</button>
	</form>
</body>
</html>
```
2. Create a sample test file for upload.
3. Run the test code (see below).
3. Observe a validation message appears on form submission.

#### Provide the test code and the tested page URL (if applicable)

Test code:

```js
import { Selector } from 'testcafe';

fixture('File upload')
    .page('http://example.com/test.html');

test('it uploads a file', async (t) => {
    const fileUpload = Selector('input#file-upload');
    const button = Selector('button#submit-button');

    await t
        .setFilesToUpload(fileUpload, 'upload.pdf')
        .click(button)
        .wait(5000);
});
```

### Specify your

* operating system: Windows 10
* testcafe version: 0.20.3
* node.js version: 8.11.2 & 10.4.0

**Comment by LavrovArtem** [comment]
Hi @artykr,
I've reproduced and created the separate [issue](https://github.com/DevExpress/testcafe-hammerhead/issues/1645) in our proxy repository.
