### ISSUE TITLE
Custom dropdown cannot be scrolled on Internet Explorer

### ISSUE THREAD

**Issue by berrutti** [DevExpress/testcafe#2511]
### Are you requesting a feature or reporting a bug?
Reporting a Bug

### What is the current behavior?
Internet Explorer fails to scroll on a custom angular dropdown

### What is the expected behavior?
Internet Explorer should scroll our custom dropdown before clicking/performing actions

### How would you reproduce the current behavior (if this is a bug)?
Click the last element of our custom dropdown. Chrome and Firefox scroll fine.

#### Provide the test code and the tested page URL (if applicable)
I created a code pen and a test case.
This is a simplified version of our angular component, but the dom element and the style is the same.

Tested page URL:
https://codepen.io/anon/pen/rKmRNo

Test code

```js
import { Selector } from 'testcafe';

fixture `IE BUG`
    .page('https://codepen.io/anon/pen/rKmRNo');

test(`Cannot click on the last element`, async t => {
    let iframe = Selector('iframe.result-iframe');
    let last = Selector('p').withText('Ten');

    await t
        .wait(10000)
        .switchToIframe(iframe)
        .expect(last.exists).ok('The element exists')
        .click(last);
});
```

### Specify your

* operating system: Windows 10. Internet Explorer 11.48.17134,0
* testcafe version: 0.20.1
* node.js version: v8.9.4

**Comment by LavrovArtem** [comment]
Hi @berrutti,
I've reproduced this problem and will investigate it.

**Comment by LavrovArtem** [comment]
The [`hasScroll`](https://github.com/DevExpress/testcafe/blob/31cf3373bf314eb0dd42e0e40c7d61a3b972d1e1/src/client/core/utils/style.js#L117) function works incorrectly in IE11 if an element has the `overflow-x: auto` CSS attribute only. In other browsers, `computedStyle.overflowX` and `computedStyle.overflowY` equal `auto` by default. In IE11, `computedStyle.overflowY` equals `visible`. Test is passed if I change the `overflow-x: auto` line to `overflow-y: auto` in example higher.

**Comment by berrutti** [comment]
Thank you very much. We added the changes and can confirm it now scrolls properly. Thanks a lot.

**Comment by miherlosev** [comment]
I'm working on it

**Comment by miherlosev** [comment]
Test cases:
- [ ] element
- [ ] `<body>`
- [ ] `<html>`
