### ISSUE TITLE
Cookies are not proxied with iframes

### ISSUE THREAD

**Issue by javiercbk** [DevExpress/testcafe#2512]
### Are you requesting a feature or reporting a bug?
This is a regression bug

### What is the current behavior?
When you set cookies via iframe you cannot access them

### What is the expected behavior?
Access the cookies inside the iframe

### How would you reproduce the current behavior (if this is a bug)?
Use my [testcafe-http-cookies](https://github.com/javiercbk/testcafe-http-cookies) repository. I've sent it to you in the past. It used to fail when cookies were setted up in a non 200 response, but now it is failing even with 200.

To run the test

```bash
npm install
npm start &
npm test
```

#### Provide the test code and the tested page URL (if applicable)
See the response above

### Specify your

* operating system: OS X
* testcafe version: 0.20.3
* node.js version: 8.9.4

**Comment by MarinaRukavitsyna** [comment]
Hello @javiercbk 
We have been informed about a similar issue and are going to fix it in the context of the following thread:
[Cookies are not synchronized between iframes](https://github.com/DevExpress/testcafe-hammerhead/issues/1489)
