### ISSUE TITLE
Testcafe doesn't finish running after opening a new page in an iframe

### ISSUE THREAD

**Issue by Horsetoast** [DevExpress/testcafe#2515]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Testcafe keeps hanging idle during a test after clicking a link that opens a new tab with javascript

### What is the expected behavior?
Testcafe should exit and report tests.

### How would you reproduce the current behavior (if this is a bug)?
Have a button in an iframe that redirects or opens a new page.
This is the iframe.html file:
```
<script>
  function openUrl () {
    window.open('https://www.google.com');
  }
</script>

<a href="#" id="button" onclick="openUrl()">Google link</a>
```
Then have testcafe click it. It will stop working (without throwing any errors).

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://horsetoast.github.io/testcafe-button-problem/

Test code

```js
import { ClientFunction, Selector } from 'testcafe';

fixture`Testcafe redirect bug`.page(
  `https://horsetoast.github.io/testcafe-button-problem/`
);

test('Click a button in iframe and redirect', async t => {

  const iframe = Selector('#iframe');
  const button = Selector('#button');
  await t
    .switchToIframe(iframe)
    .click(button)
});
```
here is my github repo with the problem 
[https://github.com/Horsetoast/testcafe-button-problem](https://github.com/Horsetoast/testcafe-button-problem)

### Specify your

* operating system: macOS High Sierra 10.13.4
* testcafe version: 0.20.3
* node.js version: v8.9.4

**Comment by miherlosev** [comment]
Hi @Horsetoast 

Thank you for your report. I've reproduce the problem.

**Comment by AndreyBelym** [comment]
It's blocked by #912. Please, use #912 to track progress in resolving this issue. I will inform you when a fix is available, feel free to reopen the issue after examining the fix in your environment.
