### ISSUE TITLE
Browser alias for using the system's default browser

### ISSUE THREAD

**Issue by tobinus** [DevExpress/testcafe#2518]
### Are you requesting a feature or reporting a bug?
Feature request!

I would like to suggest a new browser alias, which uses whatever browser is the preferred/default browser on the running system. For example, I imagine you could run:

```sh
testcafe default
```

and on my Fedora, it would run Firefox (since that is set as my default), while for a co-worker, the same command might open in Chrome, if that's the default browser on their system.

This is not so useful when everyone uses the TestCafe CLI directly, but I think it would be very useful when creating a script in `package.json` which is then run by everyone, especially when using the `all` alias would be a bit too much (for example when using testcafe-live to debug a test).

Granted, it is easy to work around this by using the TestCafe CLI directly or by assuming one browser for everyone collaborating. I consider this more of a quality-of-life improvement :slightly_smiling_face:

**Comment by AndreyBelym** [comment]
Hi @tobinus, thanks for the proposal, I see the point for using such alias in the `package.json`.

**Comment by wentwrong** [comment]
For the team: @milahu shared his findings regarding how to find the name of the default browser on Darwin systems [here](https://github.com/DevExpress/testcafe/issues/5510#issuecomment-689832682).
