### ISSUE TITLE
Include information about resource management in the Docker image to the docs

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#2519]
We should note that amounts of resources dedicated to the Docker image should be increased for testing heavy websites, and explain how to do it using `docker run` command line switches (described [here](https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources). The most important is the `--shm-size=1gb` switch for Chromium.

**Comment by VasilyStrelyaev** [comment]
Fixed by https://github.com/DevExpress/testcafe/pull/2520
