### ISSUE TITLE
Cant run first test: ERROR No tests to run. Either the test files contain no tests or the filter function is too restrictive.

### ISSUE THREAD

**Issue by Lumca** [DevExpress/testcafe#2524]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Cant run first test
ERROR No tests to run. Either the test files contain no tests or the filter function is too restrictive.

### What is the expected behavior?
Running test

### How would you reproduce the current behavior (if this is a bug)?
Installed testcafe globally, with everything set

#### Provide the test code and the tested page URL (if applicable)

import { Selector } from 'testcafe';

fixture `Getting Started`
    .page `http://devexpress.github.io/testcafe/example`;

test('My first test', async t => {
    await t
        .typeText('#developer-name', 'John Smith')
        .click('#submit-button');

    const articleHeader = await Selector('.result-content').find('h1');

    // Obtain the text of the article header
    let headerText = await articleHeader.innerText;
});

### Screen of the bug

![1](https://user-images.githubusercontent.com/4989415/41526146-898cd68c-72e3-11e8-814b-29fa7d2c2f4b.PNG)

### Specify your

* operating system: Windows 10
* testcafe version: newest
* node.js version: newest

**Comment by AndreyBelym** [comment]
Hi @Lumca, I can't reproduce the issue. What is the full path of the `test1.js` file? Could you please create a new GitHub repo which can reproduce the problem?

**Comment by Lumca** [comment]
the path is C:\Users\verne\Desktop\FE\src\Tests\test1.js
I would love to help and create new github repo but I dont know how..

I am FE tester with newely given chance to do e2e FE testing.. I want to learn JS with your program but cant get past the first test.

**Comment by Lumca** [comment]
Still cant find the problem. Is the syntax right? what is the error? how can I fix the error? I someone here who have designed the error and could tell what does it mean and how to fix it?

**Comment by forjone** [comment]
I Have the same problem，How you fix it？

**Comment by LavrovArtem** [comment]
Make sure you've correctly specified a path to the test file and saved the test file. Please create a separate issue and fill the [bug template](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md) if you still face this issue.

**Comment by arunb0405** [comment]
I'm getting same error when I use the filter in Test Runner (when I use variable name inside filter)
The variable is assigned a valid value 'ABCD-123'

        .filter((testName, fixtureName, fixturePath, testMeta, fixtureMeta) => {
            return testMeta.testID === `"${jiraTick}"`
        })

However, this goes through fine (if I hard-code the value)
        .filter((testName, fixtureName, fixturePath, testMeta, fixtureMeta) => {
            return testMeta.testID === 'ABCD-123'
        })

any ideas ?

Error: No tests to run. Either the test files contain no tests or the filter function is too restrictive.
    at C:\dev\01_mp-test\mp-angular-frontend-qa\vtt_tests\node_modules\testcafe\src\runner\bootstrapper.js:90:19

**Comment by AndreyBelym** [comment]
1) Are you sure that `jiraTick` contains a valid value? `process.argv[3]` usually contains a list of test files. Try to add `console.log(jiraTick)` to your code and use `process.env` to pass a value.

2) Test meta values must be strings according to the API specification: [Specifying Testing Metadata](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#specifying-testing-metadata). If you want to filter tests by possible metadata values specified in an array, you can use `Array.includes`: `['abc1', 'abc2'].includes(testMeta.testID)`.

**Comment by forjone** [comment]
my problem was fix， finally I found my JS file name was “test.JS”，It should be ‘test.js’，file Extension name should be lower case

**Comment by AndreyBelym** [comment]
Thank you for sharing your solution. Yes, file extensions must have the lower case on case-sensitive filesystems.

**Comment by arunb0405** [comment]
Hi thanks, 
I'm using testrunner with a filter function, you are right, it's process.argv[4] not [3] I had to read-in and it worked. In this test-runner.filter function (code below) :
    return runner
        .src([
            './tests/e2e.test.js',
        ])
        .browsers([
            `${browsers}`,
        ])
        .reporter(htmlReport, htmlStream)
        .filter((testName, fixtureName, fixturePath, testMeta, fixtureMeta) => {
            return testMeta.testID === jiraTick
        }), 
                I want to specify multiple testIDs as metadata, which I don't see in documentation.
I mean to say  like testMeta.testID===arr where arr is an array of testIDs which filter function searches?
arr = ['abcd','1234'], didn't work.
Any work-around for this.

However, this worked successful (for multiple IDs filter), 

        .filter((testName, fixtureName, fixturePath, testMeta, fixtureMeta) => {
            return testMeta.testID === 'SQDC5-679' || testMeta.testID === 'SQDC5-680'
        })

But can we specify an array for this?

Thanks in advance,

**Comment by AlexKamaev** [comment]
@arunb0405 
According to the documentation, `metadata` could be only of the `string` type. The only workaround is to stringify your array and pass it as a string to `metadata`. Then in the `filter` method you need to parse the string back.
