### ISSUE TITLE
Add "group" metadata to define which tests will be run

### ISSUE THREAD

**Issue by MarinaRukavitsyna** [DevExpress/testcafe#2527]
### Are you requesting a feature or reporting a bug?
A feature, posted by one of TestCafe customers (see details below)

### 
In one of the recent releases I noticed that test and fixture metadata can now be added to the test scripts.  Would it be possible in the future to use the metadata of a test to group them when running from command line? ie setting test.meta({sanity: true, fullRegression: true, feature1: false})  then from command line start all tests that have --meta '{sanity: true}' when i want to run only a small subset of my scripts? 

I'm currently doing this using globs on Fixture and Test names but they will become long and involved with too many unsafe keywords when I expand my test suite.

### Specify your

* testcafe version: 0.20

**Comment by iswarya-voxy** [comment]
This is a much needed feature. Ability to run a particular category of tests using their meta data set on the test or the fixture. 
Example: `test.meta({smoke: true, feature: true})` or `fixture.meta({crud: read})` 
Command to run only smoke tests : `testcafe --meta "smoke:true" test` 
Command to run only read tests : `testcafe --meta "crud:read" test` 
or something similar.

**Comment by NickCis** [comment]
I've implemented this feature in this [PR](https://github.com/DevExpress/testcafe/pull/2841).

The `--meta JSON` (eg: `--meta {smoke: true}`) flag was introduced. Only tests whose metadata [matches](https://lodash.com/docs/4.17.10#isMatch) the provided json will be run.

**Comment by jafin** [comment]
Is there any way to use the filter when a test omits the meta tag.   ie  
if we execute test with --test-meta smoke=false
and only have some tests marked up with test.meta("smoke","true")  
it would be useful to have all tests without the attribute to execute the test given they do not meet truthy.

**Comment by NickCis** [comment]
@jafin As the [docs state](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#specifying-testing-metadata): metadata value's are strings, so it really doesn't have sense to speak of _truthy_ or _falsy_ value. If you read the [PR](https://github.com/DevExpress/testcafe/pull/2841)'s comments, you will fully understand the cmd line api decision.

Anyway, you can implement you own custom runner, using the [programming interface](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#filter), to have the custom behavior that you need.
