### ISSUE TITLE
Selector fails on Safari: SyntaxError (DOM Exception 12): The string did not match the expected pattern.

### ISSUE THREAD

**Issue by gytisgreitai** [DevExpress/testcafe#2535]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

Safari fails with `SyntaxError (DOM Exception 12): The string did not match the expected pattern.`

### What is the expected behavior?

Selector should be found

### How would you reproduce the current behavior (if this is a bug)?

Try selecting the `a` element based on `data` attribute

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://codepen.io/anon/pen/vrdjJB

Test code

```ts
import { Selector } from 'testcafe';

fixture `Safari Selector Issue`
    .page('https://codepen.io/anon/pen/vrdjJB');

test(`Selector fails with "The string did not match the expected pattern"`, async t => {
    let iframe = Selector('iframe.result-iframe');
    let countryLink = Selector('a[data-suggestion="Country"');

    await t
        .wait(10000)
        .switchToIframe(iframe)
        .click(countryLink);
});

```

It all works on Chrome (67.0.3396) and Firefox (58.0.0) but fails on safari with:

```sh
testcafe safari ./tests/safari.ts
Using locally installed version of TestCafe.
 Running tests in:
 - Safari 11.0.3 / Mac OS X 10.13.3

 Safari Selector Issue
 ✖ Selector fails with "The string did not match the expected pattern"

   1) An error occurred in Selector code:

      SyntaxError (DOM Exception 12): The string did not match the expected pattern.

      Browser: Safari 11.0.3 / Mac OS X 10.13.3

          8 |    let countryLink = Selector('a[data-suggestion="Country"');
          9 |
         10 |    await t
         11 |        .wait(10000)
         12 |        .switchToIframe(iframe)
       > 13 |        .click(countryLink);
         14 |});
         15 |


```

If I execute document.querySelector('a[data-suggestion="Country"]') straight in safari console, it works:

![screenshot 2018-06-20 10 18 15](https://user-images.githubusercontent.com/1690228/41643217-47828548-7473-11e8-926e-d9ba8ab46aef.png)

### Specify your

* operating system: Mac OS X 10.13.3
* testcafe version: 0.20.2
* node.js version: v8.2.1
* safari version: 11.0.3

**Comment by AndreyBelym** [comment]
Hi @gytisgreitai! In the tests posted in the issue you've missed `]` in the Selector expression (line 8). Could you check your test code, please?

**Comment by gytisgreitai** [comment]
uh so sorry, I was sure I've double checked everything. Working fine
