### ISSUE TITLE
Enable advanced ES6 features in ClientFunctions

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#2544]
Enable the following ES6 features in ClientFunctions code:
 - [ ] async/await
 - [ ] generators
 - [ ] spread with non-arrays (https://github.com/DevExpress/testcafe/issues/1596)

**Comment by akdor1154** [comment]
request - "new" std library methods, e.g. Object.entries ?

**Comment by bertBruynooghe** [comment]
It looks like there's more to it then simply enabling these ES6 features in ClientFunctions: I had to replace every occurrence of spreads on iterables in the test target webpages to have my pages properly rendering using testcafe...

**Comment by amitzur** [comment]
@AlexKamaev Could you provide an explanation why this isn't supported? What does TestCafe do with user scripts that causes them to fail? I'd imagine running them through Babel with some configuration that's specific to the target browser. But if that's so, then why does this fail?

**Comment by LavrovArtem** [comment]
Hi @amitzur ,
Please see this comment:
https://github.com/DevExpress/testcafe/issues/1596#issuecomment-314135764
