### ISSUE TITLE
Enable debug mode with non-minified client scripts

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#2545]

**Comment by miherlosev** [comment]
I'm working on it

**Comment by miherlosev** [comment]
Need to do:
* `testcafe` and `testcafe-hammerhead` will ship with 2 script versions: minified and non-minified.
Naming conversion (same as for `jquery`, `vuejs`, etc.):
`hammerhead.js` - non-minified script
`hammerhead.min.js` - minified script

* add `--debug-mode` option. Use non-minified version of scripts when this option will be specified.

**Comment by AndreyBelym** [comment]
Closed by #2616

**Comment by MargaritaLoseva** [comment]
I'm working on this
