### ISSUE TITLE
Introduce more convenient syntax for redefining options in parameterized Selectors

### ISSUE THREAD

**Issue by kirovboris** [DevExpress/testcafe#2548]
### Are you requesting a feature or reporting a bug?

Enhancement
### What is the current behavior?

When you need to call a Selector's methods like `.with` methods for a parameterized selector (defined through a function with arguments, e.g. `Selector((arg) => {...})`), you have to use very inconvenient syntax: call the method first, and then apply Selector's arguments. In most cases, users expect that the should apply Selector's arguments first, and then use Selector's methods, and this way leads to quite cryptic exception like `TypeError: el(...).with is not a function`.

Test code

```js
import { Selector } from 'testcafe';

fixture('Fixture').page`http://devexpress.com`;

test('test', async t => {
	const el = Selector((selector) => document.querySelector(selector));
	
        var correctElWithBoundTestRun   = el.with({boundTestRun: t})('div');
	var incorrectElWithBoundTestRun = el('div').with({boundTestRun: t});
});
```

### Specify your

* operating system: any
* testcafe version: 0.20.3
* node.js version: any

**Comment by vvedachalam** [comment]
@AndreyBelym Any update on this?
