### ISSUE TITLE
TestCafe server throws an exception if inIFrame target is not found

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#255]
By some reason when client raises `emptyIFrameArgument` error it doesn't set `relatedSourceCode` property. Server throws an exception in function `getStepCode`, and hangs until browser is disconnected by heartbeat timeout.

**Comment by AlexanderMoskovkin** [comment]
@AndreyBelym is working on this

**Comment by AndreyBelym** [comment]
Thanks!
