### ISSUE TITLE
Use a more descriptive error message for 'Not match any element' case if Selector was initialized with string

### ISSUE THREAD

**Issue by vvedachalam** [DevExpress/testcafe#2551]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

TypeError: frames[i].getFunctionName is not a function

### What is the expected behavior?

We expect better descriptive message saying 'unable to find the locator' rather the above msg.

### How would you reproduce the current behavior (if this is a bug)?
const EMAILTEXTBOX = 'div > form > div:nth-child(1) > div > div > input';

export class SignUpPage {
    getEmailAddress(){
        return Selector(EMAILTEXTBOX).with({ boundTestRun: testController });
    }
}
This works as the locator is correct.

When I change the locator to incorrect, I get the above mentioned unhelpful error message.
const EMAILTEXTBOX = 'div > form > div:nth-child(1) sdfdsfdfsd > div > div > input';

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
N/A
Test code
N/A
```js
N/A

```

### Specify your

* operating system: 3.6.7-8Ubuntu1
* testcafe version: 0.19.2
* node.js version: 10.1.0

**Comment by miherlosev** [comment]
Hi @vvedachalam 

Could you please provide a full example on which I can reproduce the described above behavior?

**Comment by vvedachalam** [comment]
@miherlosev Thanks. I couldnt provide you the test URL as it is internal one. Any locator value, if we pass incorrectly, we should get this error. 
I am using Cucumber TestCafe TypeScript... In the page Object code, change the locator value to incorrect one and try which will throw the above mentioned error.

testPage.ts
--------------
import { Role, Selector} from 'testcafe'
import { testController } from '../../support/testControllerHolder'
import {waitForReact, ReactSelector} from 'testcafe-react-selectors';

const URL = 'http://localhost/test';
const CONTINUEBUTTON = 'div.eOiKsBgg button';

export class SitePage {
    getURL() {
        return URL;
    }

    getContinueButton() {
        //  return ReactSelector(CBUTTON).with({ boundTestRun: testController });
        return Selector(CONTINUEBUTTON).with({ boundTestRun: testController });
    }
}

testSteps.ts
-----------------
import {Given, When, Then} from 'cucumber';
import {SitePage} from "../support/pages/sitePage";
import {testController} from '../support/testControllerHolder';

const sitepage: SitePage=new SitePage();

Given(/^I open URL page$/, async() => {
    await testController.navigateTo(sitepage.getURL());
});

Then(/^continue button is enabled$/, async() => {
    await testController.expect(sitepage.getContinueButton().hasAttribute('disabled')).notOk();
});

test.feature
---------------
Feature: Verifying CONTINUE button state

I Selecting URL from the drop-down
  @debug
  Scenario: Verifying CONTINUE button is disabled
    Given I open URL page
    Then continue button is disabled

**Comment by miherlosev** [comment]
Ok, I understood you proposal.
If selector is initialized with string then add selector value to an error message.
For another [cases](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/creating-selectors.html#initializing-selectors) we will use a general message `The specified selector does not match any elements in the DOM tree`.

**Comment by vvedachalam** [comment]
@AndreyBelym Not sure about the state of this issue. Any progress? I have shared the code with you (link sent to your email). If we fix this, it will encourage people to use TestCafe with Cucumber

**Comment by vvedachalam** [comment]
@AndreyBelym I can see some improvements in console errors after updating TestCafe to version 0.20.2 But I guess the ticket is not fully attended to be considered as 'Resolved' to close.

**Comment by AndreyBelym** [comment]
Hi @vvedachalam, I would consider it resolved if you don't get 
```
TypeError: frames[i].getFunctionName is not a function
```
in error messages. 

I agree that the error message about non-existent element is quite unclear, but we have another issue for improving it: https://github.com/DevExpress/testcafe/issues/2568.

**Comment by AndreyBelym** [comment]
Closing this issue caused the `frames[i].getFuncitonName` to appear [is fixed](https://github.com/DevExpress/testcafe/issues/2653#issuecomment-408885269) in `v0.20.2`, and #2568 is closed too.
