### ISSUE TITLE
RequestLogger: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by hdorgeval** [DevExpress/testcafe#2554]
### Are you requesting a feature or reporting a bug?
May be a bug

### What is the current behavior?
Test is launched throufh testcafe-live
But stops immediately with the following error message:

```sh
ERROR: TypeError: Cannot read property 'replace' of undefined
```

### How would you reproduce the current behavior (if this is a bug)?
```js
import { RequestLogger, t} from 'testcafe';
const url=/\/log/;
const logger = RequestLogger(
  {url, method: 'put'},
  {
     logRequestHeaders: false,
     logRequestBody: true,
     logResponseHeaders: false,
     logResponseBody: false,
     stringifyRequestBody: true,
     stringifyResponseBody: true,
 }
);

fixture('test').requestHooks(logger);

test('request logger issue', async () => {
  await t.debug();
});
```
test will run when `logResponseBody: false` is replaced by `logResponseBody: true`

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: windows 10
* testcafe version: 0.23.0
* node.js version: v10.1.0
* npm version: 6.0.1

**Comment by AndreyBelym** [comment]
Hi @hdorgeval! Thanks for the feedback. TestCafe-Live is a separate experimental project, and it can miss some functionality or be not compatible with the changes of the core TestCafe. Could you please try to run your test with the regular TestCafe?

**Comment by AndreyBelym** [comment]
Hi @hdorgeval, thanks for the feedback! It happened because you had passed `stringifyResponseBody: true` and `logResponseBody: false`. You can't stringify a request body, if you don't log it. I think we can throw a more descriptive error in this case, or just ignore the `stringifyResponseBody` option in the context of this issue: #2555.

**Comment by hdorgeval** [comment]
Hi @AndreyBelym, thank you for your feedback. This solves the problem.
