### ISSUE TITLE
Prevent situations when request logger tries to stringify a body that is not logged

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#2555]
E. g. when passing `{ logRequestBody: false, stringifyRequestBody: true}` to a logger. We can throw an error in this case or just ignore the `stringify` options. We also should state this situation in the docs.

**Comment by miherlosev** [comment]
We already have a code that handles this case - https://github.com/DevExpress/testcafe/blob/master/src/api/request-hooks/request-logger.js#L31.

Problem is in `src/errors/stack-cleaning-hook.js`

**Comment by AndreyBelym** [comment]
An additional reason is that RequestHookConfigureAPIError is an instance of `TestRunErrorBase`. It must use the `APIError` [class](https://github.com/DevExpress/testcafe/blob/master/src/errors/runtime/index.js#L29) as a base class.

**Comment by miherlosev** [comment]
I'm working on this
