### ISSUE TITLE
Define Default Reporter

### ISSUE THREAD

**Issue by berrutti** [DevExpress/testcafe#2556]
### Are you requesting a feature or reporting a bug?
Requesting a feature

### What is the current behavior?
If a user wants to run tests with a custom reporter, a command line option must be added every time the tests are executed

### What is the expected behavior?
Let us define a default reporter so we can avoid adding another command line argument
Something like:
testcafe -setReporter reporterName

### How would you reproduce the current behavior (if this is a bug)?
NA

#### Provide the test code and the tested page URL (if applicable)
NA

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Windows 10
* testcafe version: 0.20.1
* node.js version:  v8.9.4

**Comment by miherlosev** [comment]
For a command-line interface, other test runners such as `mocha` and `ava` don't store any state between test runs. `TestCafe` also will not do it. 
One more argument not to do it - code readability will degrade.

**Comment by berrutti** [comment]
You are right. Thanks for the explanation!
