### ISSUE TITLE
"A call to an async function is not awaited. Use the "await" keyword..." message displayed when all calls are awaited properly

### ISSUE THREAD

**Issue by berrutti** [DevExpress/testcafe#2557]
### Are you requesting a feature or reporting a bug?
Reporting a bug

### What is the current behavior?
The message "A call to an async function is not awaited. Use the "await" keyword before actions, assertions or chains of them to ensure that they run in the right sequence." is displayed even though the calls are properly awaited. Then after that message, the actual error code is displayed.

### What is the expected behavior?
Only the actual error message should be printed

### How would you reproduce the current behavior (if this is a bug)?
Run the provided test code

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: www.google.com

Test code

```js
import { Selector } from 'testcafe';

fixture `Fixture for Error Demo`
	.page('www.google.com')

test(`Two messages when trying to get a selector from an undefined property`, async t => {
    let searchInput = Selector('input[role="combobox"]');
    let value;
    
    await t
        .click(searchInput)
        .click(value.someProperty)
        .typeText(searchInput,'Test');
});

```

### Specify your

* operating system: Windows 10
* testcafe version: 0.20.3
* node.js version: v8.9.4

**Comment by miherlosev** [comment]
Hi @berrutti 

Thank you for the detailed description. I've reproduced the problem.

**Comment by TestAndunR** [comment]
I got the same issue. Is there any workaround for this.
```
test("test",async t => {
        await cognitoTriggers.forEach(trigger => {
                t.expect(triggerTypes).contains(trigger,trigger+" could not found in the sample list");     
    });
})
```

**Comment by AndreyBelym** [comment]
Hi @TestAndunR, in your case assertions are not awaited - the `Array#forEach` method doesn't await results of the iterator function. Use `Promise.all` or `for..of` loop instead of the `forEach` method.

**Comment by miherlosev** [comment]
I'm working on this

**Comment by bhreinb** [comment]
Hi Folks,

I'm fairly sure this code commit broke functionality that was working prior to version v0.23.0

https://github.com/DevExpress/testcafe/releases#v0.23.0%20(2018-10-18)

I had a sample code snippet like so within a function...

```
const promises = [
t.typeText('input[aria-label="Search Learning catalog"]', searchText, {}),
t.pressKey('enter', {}),
];
return Promise.all(promises);
```

I've had to change to to the following because of this change 

```
await this.classBasePage.testCafeTypeText('input[aria-label="Search Learning catalog"]', textSearch, {});
await this.classBasePage.testCafeActionsPressKey('enter', {});
```

the first construct is perfectly valid and should be still supported should it not?

**Comment by LavrovArtem** [comment]
@bhreinb 
The `Promise.all` function waits until all promises are resolved, but this [doesn't guarantee](https://stackoverflow.com/questions/30823653/is-node-js-native-promise-all-processing-in-parallel-or-sequentially) that an action order will be preserved and this code can lead to an error. We have a similar feature request. You can vote for it using the following link: [[Feature request] Add .pipe method similar to Rxjs 6 to TestController](https://github.com/DevExpress/testcafe/issues/2573).

**Comment by bhreinb** [comment]
Hi @LavrovArtem. Thanks for the update and providing me with the feature request. All the best.
