### ISSUE TITLE
Concurrent IE11 execution fails intermittently

### ISSUE THREAD

**Issue by berrutti** [DevExpress/testcafe#2558]
### Are you requesting a feature or reporting a bug?
Reporting a bug

### What is the current behavior?
We have a battery of 30+ tests. Sometimes IE explorer fails to open enough browsers while executing concurrently and tests execution hang. Only 3 or 4 windows open and nothing happens on console. The browsers display the "Connected" message but remain idle (E.G: http://172.16.106.8:1268/browser/idle/XouBY5T) I presume because those are waiting until enough browsers are open, but that never happens.
After some timeout, the following message is displayed on console:
ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
And the open IE windows close

### What is the expected behavior?
The amount of browsers declared after the -c option should open. Tests execution should start without problems

### How would you reproduce the current behavior (if this is a bug)?
Run a battery of 30+ tests concurrently on IE11 (Between -c 5 and -c 10 should be enough).
After trying multiple times, enough windows are opened and the tests start, but it's not clear what can be causing this issue.
It's not a memory/resources problem. After trying some more times, the tests start normally.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Windows 10 PRO 1803 - OS Compilation 17134.112
* IE version: 11.112.17134.0 - Update version: 11.0.70 (KB4230450)
* testcafe version: 0.20.3
* node.js version: v8.9.4

**Comment by miherlosev** [comment]
Hi @berrutti 

This problem is related to IE11. It takes a lot of RAM and CPU.
There is an issue - [Restart browser if it became unresponsive](https://github.com/DevExpress/testcafe/issues/1815) - that should help to fix it. Track this issue to be aware about progress.
