### ISSUE TITLE
Extend user action

### ISSUE THREAD

**Issue by apiel** [DevExpress/testcafe#2560]
**Feature**

Is there any possibility to extend user action? for example if I would like to do something like:

```
test('My Test', async t => {
    await t
        .myAction()
        .typeText(nameInput, 'Peter');
});
```
I could imagine to do:

`t.myAction = () => { ... };`

But would be great to have something reusable for all the tests.

**Comment by miherlosev** [comment]
Hi @apiel 

Could you please provide an example of user-defined test action?

**Comment by apiel** [comment]
myAction could be for example login(), right now we use a utility function:

```
const login (t) =>
    t
        .typeText(loginPage.nameInput, 'hello@world.com')
        .typeText(loginPage.passwordInput, 'hello')
        .click(loginPage.loginButton);
```
It would be great that instead to call:
`login(t).expect(...),ok();`

We could do:
`t.login().expect(...),ok();`

**Comment by miherlosev** [comment]
We already have issue for your scenario - https://github.com/DevExpress/testcafe/issues/1535.
Track this to be aware about progress.
