### ISSUE TITLE
Screenshot path is not reported when Unable to take screenshot warning is thrown

### ISSUE THREAD

**Issue by jburgs** [DevExpress/testcafe#2565]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
I am using the reporter `JSON` to create a report in the `testcafe/testcafe` docker container.
The -S option is being used to screenshot on fail.  When a test fails it throws a warning that wraps an error BUT the screenshot is taken successfully.  

```  
Was unable to take a screenshot due to an error.

  Error: Unable to locate the page area in the browser window screenshot at
  /builds/time0/tyrion/tests/output/2018-06-26_07-21-20/test-41/Chrome_63.0.3239_Linux_0.0.0/errors/1.png,
  because the page area mark with ID 1679705575 is not found in the screenshot.
      at _callee$  (/builds/time0/tyrion/node_modules/testcafe/lib/screenshots/crop.js:95:31)
      at tryCatch  (/builds/time0/tyrion/node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke]  (/builds/time0/tyrion/node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (/builds/time0/tyrion/node_modules/regenerator-runtime/runtime.js:114:21)
      at step (/builds/time0/tyrion/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /builds/time0/tyrion/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
      at <anonymous>
```
the screenshot found at the location in the stacktrace is: 

![1](https://user-images.githubusercontent.com/6913832/41925581-fed1c918-793a-11e8-835d-292e1b5cebc2.png)

When the report is generated the failed tests have no value for screenshotPath.

```
        {
          "name": "Log Viewer - Multi Log - Search Results - Case Sensitive Toggle",
          "errs": [
            "AssertionError: expected 28 to deeply equal 14\n\nBrowser: Chrome 63.0.3239 / Linux 0.0.0
          ...
          ...
          ],
          "durationMs": 145845,
          "screenshotPath": null,
          "skipped": false
        }
```

### What is the expected behavior?

if the screenshot is taken the screenshotPath should be set

### How would you reproduce the current behavior (if this is a bug)?
run a failing test on the `testcafe/testcafe` docker image with these options
`> testcafe $BROWSER $TESTS -F $FIXTURES_GLOB -S -s $SCREENSHOT_FOLDER --reporter spec,json:report.json`

### Specify your

* operating system: latest testcafe/testcafe docker image
* testcafe version: 0.20.4
* node.js version: 5.6

**Comment by AndreyBelym** [comment]
Hi @jburgs, could you please share the output of `docker run -it --rm testcafe/testcafe -v`?

**Comment by jburgs** [comment]
the output is 0.20.4

**Comment by AndreyBelym** [comment]
Could you please try to use `chromium:headless` as the browser?

**Comment by jburgs** [comment]
chromium:headless does not throw the warning and takes the screenshot as expected with `screenshotPath` value filled in

**Comment by jburgs** [comment]
i found that my package.json file still had testcafe version 0.20.3 defined in it.  Updated the package file to match the version in the docker container and i don't see the warning  anymore the screenshotPath value is filled in

**Comment by AndreyBelym** [comment]
So I close it, because the problem was resolved by updating TestCafe version in `package.json`.
