### ISSUE TITLE
Unable to run tests within testcafe docker image - Unable to find modules

### ISSUE THREAD

**Issue by dsayerjp** [DevExpress/testcafe#2566]
### Are you requesting a feature or reporting a bug?

Reporting an issue with the testcafe docker image.

We are trying to run the tests through the docker image on Jenkins and are encountering an issue where it cannot find the NPM modules.

### What is the current behavior?

Jenkins logs the error as: 

```
ERROR Cannot prepare tests due to an error.

Error: Cannot find module 'dotenv'
    at Object.<anonymous> (/app/config.js:3:12)
    at Object.<anonymous> (/app/tests/web/auth/emailLoginTests.js:1:16)

```

### How would you reproduce the current behavior (if this is a bug)?

Our Jenkins build does the following shell commands:

1. Uses Ansible vault to decrypt our secret file
2. copies the decrypted file into a .env file
3. `docker pull testcafe/testcafe`
4. ```docker run -v `pwd`:/app -i testcafe/testcafe chromium /app/tests/web/auth/emailLoginTests.js -e```

Steps 1 to 3 are successful but step 4 isn't.

#### Provide the test code and the tested page URL (if applicable)

In our base directory we have a config.js file that is used to interact with our .env file, below is the relevant section.

Our package.json contains the `donenv` in our dependencies.

Test code:

```js
const path = require('path');
const fs = require('fs');
const en = require('dotenv');

const _environment = 'staging';

en.load({
  path: path.resolve(__dirname, './.env')
});
```

### Specify your

* operating system: MacOS (High Sierra) 
* testcafe version: 0.20.2
* node.js version: 8.11.1

**Comment by AndreyBelym** [comment]
Hi @dsayerjp, you should set  the `NODE_PATH` variable to `/app/node_modules` or to the directory where your Node.js modules are installed (in this case probably you will need to mount the directory as an additional volume):
```
docker run -v `pwd`:/app -e "NODE_PATH=/app/node_modules" -i testcafe/testcafe chromium /app/tests/web/auth/emailLoginTests.js -e
```

**Comment by dsayerjp** [comment]
Hi @AndreyBelym, thanks for your response. I've managed to get this working.
