### ISSUE TITLE
Multiple asssertion is not working

### ISSUE THREAD

**Issue by vvedachalam** [DevExpress/testcafe#2567]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

When multiple assertions to be carried out, if I add the below code, I get error :       TypeError: testControllerHolder_1.testController.expect(...).expect is not a function

### What is the expected behavior?
The multiple assertion should work

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```
===========
import { Given, When, Then } from 'cucumber';
import { Role, Selector, t } from 'testcafe'
import { testController } from '../support/testControllerHolder';
import { SignUpPage } from '../support/pages/signUpPage';

const signuppage: SignUpPage = new SignUpPage();

When(/^I can see all the fields$/, async () => {
    await testController
        .expect(signuppage.getEmailAddress().visible)
        .expect(signuppage.getFirstName().visble)
        .expect(signuppage.getLastName().visble)
        .expect(signuppage.getMerchantName().visble)
        .expect(signuppage.getIndustry().visible)
        .expect(signuppage.getCountryName().visble)
        .expect(signuppage.getPhone().visble)
        .expect(signuppage.getVisitors().visble);
});

=============
import { Role, Selector } from 'testcafe'
import { testController } from '../../support/testControllerHolder'
import { waitForReact, ReactSelector } from 'testcafe-react-selectors';

const EMAILTEXTBOX = 'div > form > div:nth-child(1) > div > div > input';
const FIRSTNAMETEXTBOX = ReactSelector('TextInput').withProps('name', 'first-name');
const LASTNAMETEXTBOX = ReactSelector('TextInput').withProps('name', 'last-name');
const MERCHANTNAMETEXTBOX = ReactSelector('TextInput').withProps('name', 'merchant-name');

export class SignUpPage {
    getEmailAddress(){
        // console.log("Email field webelement: "+ EMAILTEXTBOX + "\n")
        return Selector(EMAILTEXTBOX).with({ boundTestRun: testController });
    }

    getFirstName(){
        return FIRSTNAMETEXTBOX.with({ boundTestRun: testController });
    }
    getLastName(){
        return LASTNAMETEXTBOX.with({ boundTestRun: testController });
    }
    getMerchantName(){
        return MERCHANTNAMETEXTBOX.with({ boundTestRun: testController });
    }
}
### Specify your

* operating system: Ubuntu 18.04
* testcafe version: 19.2
* node.js version: 10.1.0

**Comment by miherlosev** [comment]
Hi @vvedachalam

You should write the [assertion method](https://devexpress.github.io/testcafe/documentation/test-api/assertions/assertion-api.html) after `expect` action.

Rewrite your code as follows:
```
await testController
.expect(signuppage.getEmailAddress().visible).ok()
.expect(signuppage.getFirstName().visble).ok()
.expect(signuppage.getLastName().visble).ok()
```

Also, we have an issue https://github.com/DevExpress/testcafe/issues/1063 that should help you prevent this unclear behavior. Track it to be aware of any progress there.
