### ISSUE TITLE
Show the selector text used when "The specified selector does not match any element in the DOM tree."

### ISSUE THREAD

**Issue by dylang** [DevExpress/testcafe#2568]
### Are you requesting a feature or reporting a bug?

New feature

### What is the current behavior?

<img width="639" alt="screen shot 2018-06-27 at 10 35 44 am" src="https://user-images.githubusercontent.com/51505/41981009-ec9c9c6c-79f5-11e8-9108-073aaba57f14.png">

When a selector is used that does not find anything, we print the error message 

```
The specified selector does not match any element in the DOM tree.
```

If using a page model like the above screenshot then the source code doesn't show the selector that was used.

### What is the expected behavior?

```
The specified selector does not match any element in the DOM tree:
[data-testid="navigation"] [data-testid="visible-items"] > a:nth-child(3) foobar
```

### How would you reproduce the current behavior (if this is a bug)?

* Use a selector that doesn't find anything on the page.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Any page

Test code

```js
const selector = '[data-testid="navigation"] [data-testid="visible-items"] > a:nth-child(3) foobar';
await t.click(Selector(selector));
```

### Specify your

* operating system: `macos`
* testcafe version: `0.20.4`
* node.js version: `10.5.0`

**Comment by AndreyBelym** [comment]
Hi @dylang, thanks for the proposal! I think it's a good idea.

**Comment by vvedachalam** [comment]
@dylang Thanks for considering my request

**Comment by miherlosev** [comment]
Dublicate of https://github.com/DevExpress/testcafe/issues/2551

**Comment by vvedachalam** [comment]
ah.. I thought my bug was created as new Req for Dev purpose :P

**Comment by AndreyBelym** [comment]
It's not a duplicate, this one is an actual proposal, and #2551 is an issue caused by poor Cucumber integration.

**Comment by dylang** [comment]
FWIW, I don't think this is a duplicate of #2551.

#2551 triage suggests it's a Cucumber issue related to stack parsing.

This issue is not using Cucumber. The problem is that the error message text doesn't include useful data from the `Selector`.
