### ISSUE TITLE
Testcafe hangs when trying to resizeWindow on certain monitors

### ISSUE THREAD

**Issue by bdwain** [DevExpress/testcafe#2571]
### Are you requesting a feature or reporting a bug?
bug

### What is the current behavior?
`await t.resizeWindow(750,1000);` hangs forever on certain monitors (but not all) in chrome and firefox (and safari sometimes)

### What is the expected behavior?
resizing window would not hang

### How would you reproduce the current behavior (if this is a bug)?
try to resizeWindow on an acer V233H or on the laptop screen of a 2016 15 inch macbook pro
It works on an Acer G257HU

It also works in safari for the acer V233H.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: None

Test code

```js
fixture('foo');
test('bar', async t => {
  await t.resizeWindow(750,1000);
});
```

### Specify your

* operating system: OS X High Sierra
* testcafe version: 0.18.6
* node.js version: 9.11.1
* Chrome version: 67
* Firefox version: 62 (dev edition)

**Comment by AndreyBelym** [comment]
Hi @bdwain, could you please upgrade your TestCafe to the latest version `v0.20.4` or at least to the `v0.20.2`? The macOS-specific code of window manipulation modules (including window resizing module) was completely rewritten in this version, so the problem can be already resolved.

**Comment by bdwain** [comment]
Cool! I figured it might be. Thanks!
