### ISSUE TITLE
Page object methods that use test controller throw error when called in `before`

### ISSUE THREAD

**Issue by qualityshepherd** [DevExpress/testcafe#2572]
### Are you requesting a feature or reporting a bug?
Either a bug with my brain or the app... or perhaps a feature request :)

### What is the current behavior?
I'm calling a page object method `goto` that builds/alters an url and then uses `await t.navigateTo(url)` to goto the page. This works fine within a `test` or `beforeEach`, but _not_ in a `before`. It throws:

```
Cannot implicitly resolve the test run in the context of which the test controller action should be executed. Use test function's 't'
      argument instead.
``` 
### What is the expected behavior?
I can kinda see _why_ this might be, but I want this to work. Writing tests this way allows me to decouple tests from one another, especially ones with long, slow, setups. Ie. in my before, I'd login, setup any data I need, then run a number of tests. Calling this in one of the tests couples _all_ tests to _that_ test. I _could_ use the `beforeOnce` hack as noted in #1345... but... hacky. 

### How would you reproduce the current behavior (if this is a bug)?
**myPageObject method**
```
async goto(url) {
    // url building magic here
    await t.navigateTo(url);
}
```

**Test**
```
...
fixture `Url Sadness`
    .before(async t => {
        await myPageObject.goto(url);
    }
    
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code
:point_up:

### Specify your

* operating system: macos latests
* testcafe version: 0.20.3
* node.js version: latest lts

**Comment by AndreyBelym** [comment]
Hi @qualityshepherd, the `fixture.before` and `fixture.after` hooks are designed for server-side test environment setup actions and are executed before a test page is loaded in a browser. It means you can't use a test controller in these hooks, check the [documentation]( http://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#fixture-hooks).

**Comment by AndreyBelym** [comment]
You can take [this approach](https://github.com/DevExpress/testcafe/issues/1345#issuecomment-338796731) to execute `fixture.beforeEach` only once.

**Comment by qualityshepherd** [comment]
Yeah, that would be the _hacky_ I spoke of above... figured.
