### ISSUE TITLE
[Feature request] Add .pipe method similar to Rxjs 6 to TestController

### ISSUE THREAD

**Issue by Juansasa** [DevExpress/testcafe#2573]
While method chaining is highly readable its very limiting when it comes to flexibility, reusability and customization. Please consider breaking TestController to smaller functions, add a pipe function and provide an interface for creating new pipable methods.

### Are you requesting a feature or reporting a bug?
Feature request

### What is the current behavior?
`t.click().expect().typeText()....
`

### What is the expected behavior?
`t.pipe(click(), expect(), typeText(),......)`
or
`t.pipe(...[click(), expect(), typeText()])`

Which will allow me to do something like this and much more.
`t.pipe(...['a', 'b, 'c].map((val, index) => expect(selector.nth(index)).el(val)))`

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by bhreinb** [comment]
+1 for this feature, It would be a nice alternative to have rather than chaining actions.
