### ISSUE TITLE
Emulate HTML 5 Validation API

### ISSUE THREAD

**Issue by kafeterio** [DevExpress/testcafe#2576]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

calls to checkValidity() for input with value < minlength  return true

### What is the expected behavior?

should return false

### How would you reproduce the current behavior (if this is a bug)?

```html
<form>
	<label> label: </label><input minlength="4" maxlength="10"></input>
</form>
```

```js
import { ClientFunction } from "testcafe";

fixture `Test native validity`
.page `http://localhost:3939`

const getValid = ClientFunction(()=>{
	return document.getElementsByTagName('input')[0].checkValidity()
})

test('not valid when length < 4', async t => {
	await t
	.typeText('input', 'aaa')
	.expect(getValid()).eql(false)
})
```

### Error
![image](https://user-images.githubusercontent.com/40469846/42109054-5cf534fa-7baa-11e8-9fa0-02e7fa8603df.png)

* operating system: linux
* testcafe version: 0.20.4
* node.js version: 9.11.1

**Comment by miherlosev** [comment]
Hi @kafeterio 

It's a restriction of the current 'Event emulation' subsystem implementation. 
Actually, we type via programmatic event creation.
The problem will be fixed once we implement [Automations using browser-specific API](https://github.com/DevExpress/testcafe/issues/2543).
