### ISSUE TITLE
Blacklist 'useStrict' in Babel

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#258]
Strict mode disallows usage of `callee.caller`. So if a function traverses call stack with `callee.caller`, and TestCafe functions are strict-mode functions, an exception will be thrown. Unfortunately, we have  that nasty kind of a function in DevExpress ASP.Net controls, so we need to disable strict mode in Babel transform options.

**Comment by inikulin** [comment]
Don't forget about regression test for this one
