### ISSUE TITLE
RequestLogger issue with Typescript Compilation

### ISSUE THREAD

**Issue by ZayanNadeem** [DevExpress/testcafe#2582]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
I recently decided to move all my testcafe files which I had written in JS to TS and:

```
const logger =  RequestLogger({'myfiledownloadlink', method: 'GET'}) or
const logger =  RequestLogger({url: 'myfiledownloadlink', method: 'GET'}) *This also fails my tests*
```
gives me the following error:  Argument of type '{ pageUrl: string; method: string; }' is not assignable to parameter of type 'string | object | RegExp | ((req: any, res: any) => boolean)'.
 Object literal may only specify known properties, and 'pageUrl' does not exist in type 'string | object | RegExp | ((req: any, res: any) => boolean)'.

but when I do

```
const options = {'www.example.com', method: 'GET'}
const logger = RequestLogger(options)
```
it compiles.

### What is the expected behavior?
Shouldn't it work in both cases nonetheless? Am I doing something wrong?
I also looked at the PR#[2423](https://github.com/DevExpress/testcafe/pull/2423) which explains the error. I tried the "skipLibCheck" as well - didn't do anything.

### My test

```
 test
  .requestHooks(logger)
  ('should be able to download', async t => {
    const downloadButton = Selector('#button_download');
    await t
      .click(downloadButton)
      .expect(logger.contains(r=>r.response.statusCode === 200)).ok();
  });
```

### Specify your

* operating system: linux
* testcafe version: 0.20.4
* node.js version: 10.3.3

**Comment by miherlosev** [comment]
Hi @ZayanNadeem 

> but when I do

> const options = {'www.example.com', method: 'GET'}
> const logger = RequestLogger(options)

> it compiles.

The code `const options = {'www.example.com', method: 'GET'}` was written with a syntax error.

I've tried with `0.20.4` TestCafe version and it does not compiled.
Change your code piece to 
```const options = { url: 'www.example.com', method: 'GET'};```
and let us know about results.

**Comment by ZayanNadeem** [comment]
For me:

1. const options = {'www.example.com', method: 'GET'}
  It compiles and my test passes.

2. const options = { url: 'www.example.com', method: 'GET'}
  It compiles but my test fails. 
```
 .expect(logger.contains(r=>r.response.statusCode === 200)).ok(); 
expected false to be truthy.
```

Please let me know if I wrote my test wrong! Thanks.

**Comment by ZayanNadeem** [comment]
This is my test in case you are wondering

``` 
test
  .requestHooks(logger)
  ('should be able to download', async t => {
    const downloadButton = Selector('#button_download');
    await t
      .click(downloadButton)
      .expect(logger.contains(r=>r.response.statusCode === 200)).ok();
  });
```

**Comment by MarinaRukavitsyna** [comment]
Hello @ZayanNadeem 

The following test works properly for me:

```js
import { RequestLogger } from 'testcafe';

const options = { url: 'https://testcafe.devexpress.com/', method: 'GET'};
const logger = RequestLogger(options);

fixture `test`
    .page('https://testcafe.devexpress.com');

test
    .requestHooks(logger)
    ('test', async t => {
     await t.expect(logger.contains(record => record.response.statusCode === 200)).ok(); 
 
        const logRecord = logger.requests[0];

        console.log(logRecord.userAgent);          
        console.log(logRecord.request.url);         
        console.log(logRecord.request.method);      
        console.log(logRecord.response.statusCode); 
    });
```
Would you please check how this test works on your side? If it works, update the test so that I can see the problem on my side. Otherwise, send me an error message you see when the test fails.

**Comment by MarinaRukavitsyna** [comment]
@ZayanNadeem 
It is possible that the issue is related to TestCafe timeouts: t.expect waits for 3 seconds and this time might be not enough to load a resource. 

If the issue persists, try calling "wait" before "expect": 

```js
await t
   .wait(4000)
   .expect(logger.contains(record => record.response.statusCode === 200)).ok();
```

**Comment by ZayanNadeem** [comment]
@MarinaRukavitsyna I haven't gotten a chance to work on this issue. I will do so today and circle back.
