### ISSUE TITLE
Screenshots on Firefox not working correctly.

### ISSUE THREAD

**Issue by KidyovrS** [DevExpress/testcafe#2584]
### Are you requesting a feature or reporting a bug?

Reporting a bug.

### What is the current behavior?

On Firefox, testcafe only takes screenshot of all elements with normal `position` style.

### What is the expected behavior?

Should take screenshot of the whole visible area.

### How would you reproduce the current behavior (if this is a bug)?

I've created a repo [here](https://github.com/KidyovrS/testcafe-bug-demo) for your reference.

For example, a web page like this:
``` html
<html>

<head>
	<style>
		body {
			margin: 0;
		}
	</style>
</head>

<body>
	<div style="height:200px; background-color: blue"></div>
	<div style="height:200px; background-color: green; position:fixed; top:200px; left:0; right:0;"></div>
</body>

</html>
```

Screenshot from Chrome:
![1](https://github.com/KidyovrS/testcafe-bug-demo/raw/master/screenshots/2018-07-04_03-19-35/test-1/Chrome_67.0.3396_Windows_10.0.0/1.png)

Screenshot from Firefox:
![1](https://github.com/KidyovrS/testcafe-bug-demo/raw/master/screenshots/2018-07-04_03-19-35/test-1/Firefox_61.0.0_Windows_10.0.0/1.png)

This issue does not appear if I roll back to previous releases of testcafe.

### Specify your

* operating system: Windows 10
* testcafe version: 0.20.4
* node.js version: 8.11.3

**Comment by AndreyBelym** [comment]
It's a bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1385706

**Comment by AndreyBelym** [comment]
Fixed in Firefox 66.
