### ISSUE TITLE
.setConfirmDialogHandler is not working properly

### ISSUE THREAD

**Issue by hiruthre** [DevExpress/testcafe#2585]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

.setConfirmDialogHandler only works then the text of alert is mentioned in .setConfirmDialogHandler function.

### What is the expected behavior?

.setConfirmDialogHandler should also work when text is matched with a variable which contains the actual text of alert.

### How would you reproduce the current behavior (if this is a bug)?

Check with any URL with below-mentioned code.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code
In below code, passing actual text of alert window through a variable.  However, testcafe is not considering variable and always returns 'Null'....

```js
test('Expected confirm after an action', async t => {
    await t
        var que = 'Confirm?'
        .setNativeDialogHandler((type, text, que) => {
            if (type === 'confirm' && text === que)
                return true;
 
            return null;
        })
        .click('#buttonConfirm');
 
    expect(await getResult()).equals('true');
});
```

### Specify your

* operating system: Windows 10
* testcafe version: 0.20.3
* node.js version: 8.11.1

**Comment by AndreyBelym** [comment]
Hi @hiruthre, please check the documentation for the [.setNativeDialogHandler](https://devexpress.github.io/testcafe/documentation/test-api/handling-native-dialogs.html#dialog-handler) method. The third parameter of handler function is an URL of a page that triggered the dialog. To pass a variable to a dialog handler, you should use the [dependencies](https://devexpress.github.io/testcafe/documentation/test-api/obtaining-data-from-the-client/#optionsdependencies) option:
```
test('Expected confirm after an action', async t => {
    await t
        var que = 'Confirm?'
        .setNativeDialogHandler((type, text) => {
            if (type === 'confirm' && text === que)
                return true;
 
            return null;
        }, { dependencies: { que } })
        .click('#buttonConfirm');
 
    expect(await getResult()).equals('true');
});
```

**Comment by hiruthre** [comment]
Thanks Andrey...
