### ISSUE TITLE
g is null after page navigation

### ISSUE THREAD

**Issue by ericorruption** [DevExpress/testcafe#2587]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
The following errors are thrown, highlighting the second `click` line.

Firefox 62.0.0
TypeError: g is null

Safari 11.1.1
TypeError: null is not an object (evaluating 'g.split')

Chrome 67
 Uncaught TypeError: Cannot read property 'split' of null

### What is the expected behavior?
The second click should happen in the new, navigated page.

### How would you reproduce the current behavior (if this is a bug)?
Running the code below in any browser.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://www.happycar.de

Test code

```js
import { Selector } from "testcafe";

fixture("HAPPYCAR").page("https://www.happycar.de");

test("Happy Path", async test => {
  await test
    .typeText(Selector(`.o-input[name="rentLocationName"]`), "Berlin")
    .click(Selector(".search-submit"))
    .click(Selector(".o-btn"));
});
```

### Specify your

* operating system: Mac OS X 10.13.5
* testcafe version: 0.20.0 to 0.20.4
* node.js version: v8.10.0

**Comment by ericorruption** [comment]
Weirdly enough, it works from node.js version 10.1 upwards.

**Comment by ericorruption** [comment]
Using the flag `--skip-js-errors` works. So I assume this is a problem on the tested pages.

**Comment by AndreyBelym** [comment]
Hi @ericorruption, I agree, looks like it was a problem on the tested site, so I close the issue.
