### ISSUE TITLE
Visual Recorder Issue

### ISSUE THREAD

**Issue by pranshu1995** [DevExpress/testcafe#2591]
### Are you requesting a feature or reporting a bug?

Bug

Hi I'm using Testcafe Visual recorder to record my Web Application Behaviour.
Most of my workflows are dependent upon this Grid Library which I am using : https://www.ag-grid.com
Now the problem is that Grid is always filled by dynamic data and when I try to select the data (like first 4 rows of the grid), it captures the required Element by its X-Path. Sometimes it able to find the element and sometimes it is not even when the Grid is formed.  
The HTML of the Grid formed is quite nested.

This is Element Click Step : 

` "19.Click span": function() {
        act.click("body > div:nth(0) > div:nth(2) > div:nth(0) > div:nth(0) > div:nth(8) > div:nth(0) > div:nth(0) > div:nth(0) > div:nth(0) > div:nth(0) > div:nth(1) > div:nth(0) > div:nth(0) > div:nth(0) > div:nth(0) > div:nth(1) > div:nth(1) > div:nth(0) > div:nth(0) > div:nth(0) > div:nth(3) > div:nth(2) > div:nth(0) > div:nth(0) > div:nth(0) > div:nth(5) > span:nth(0) > span:nth(0) > span:nth(1)");
    }`

 The test fails more often when it is run on a headless browser.
Sometimes It fails to load the Alert box too which is supposed to open after a successful AJAX request.
Alert Library being used : https://sweetalert.js.org/

This is the part of error in the generated JSON report : 

` [ "Error at step \"19.Click span\":\nA target element of the click action has not been found in the DOM tree.\nIf this element should be created after animation or a time-consuming operation is finished,
use the waitFor action (available for use in code) to pause test execution until this element appears.\n\nBrowser: Firefox 60.0.0 / Ubuntu 0.0.0\n\nCode:\nact.click(\"body > div:nth(0) > div:nth(2) > div:nth(0) > div:nth(0) > div:nth(8) > div:nth(0) > div:nth(0) > div:nth(0) > div:nth(0) > div:nth(0) > div:nth(1) > div:nth(0) > div:nth(0) > div:nth(0) > div:nth(0) > div:nth(1) > div:nth(1) > div:nth(0) > div:nth(0) > div:nth(0) > div:nth(3) > div:nth(2) > div:nth(0) > div:nth(0) > div:nth(0) > div:nth(0) > span:nth(0) > span:nth(0) > span:nth(1)\");" ]`

Kindly guide on how to resolve this?

Thanks

* operating system: Linux
* testcafe version:0.19.2
* node.js version:4.2.6

**Comment by AndreyBelym** [comment]
Hi @pranshu1995,
We provide two TestCafe versions: a paid version with a recorder and an open source version. According to your description, you are using the former version. So, please use the DevExpress Support Center to submit tickets regarding your version (https://www.devexpress.com/Support/Center/Question/Create) as we generally process issues related to the paid TestCafe version there to avoid mixing two different versions. The GitHub channel is intended for the open-source version.

**Comment by pranshu1995** [comment]
Hi @AndreyBelym Please share your Email ID on which I can share the required information.
Sorry I can't share it publicly since it is a Company's project.
Thanks

**Comment by AndreyBelym** [comment]
Hi @pranshu1995, sorry for the late response, you can find my email on my GitHub profile page.

**Comment by AndreyBelym** [comment]
I close this issue because of the long period of inactivity. Feel free to reopen it if you have any updates.
