### ISSUE TITLE
Reload clear local storage when useRole is used 

### ISSUE THREAD

**Issue by Juansasa** [DevExpress/testcafe#2608]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

Any modification to local storage is resetted when reload the browser using `TestController.eval(() => location.reload())`

### What is the expected behavior?

The changes made during testing should remain unchanged

### How would you reproduce the current behavior (if this is a bug)?

```
await t
.useRole(admin)
  .click(page.saveToStorage())
  console.log(await ClientFunction(key => localStorage.getItem(key))('key')); ==> 'xxx'
  await t.eval(() => location.reload(true));
  console.log(await ClientFunction(key => localStorage.getItem(key))('key')); ==> null
```

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by LavrovArtem** [comment]
Hi @Juansasa,
I cannot reproduce this issue in Chrome - please see my test below. 
Would you please specify the browser you are using and the tested page's URL, or create a sample page where I can reproduce the issue?
```js
import { ClientFunction } from 'testcafe';

fixture `fixture`
    .page `http://devexpress.github.io/testcafe/example`;

const getLocalStorageItem = ClientFunction(key => localStorage.getItem(key));

test('local storage', async t => {
    await t.eval(() => localStorage.setItem('key', 'value'));
    await t.expect(getLocalStorageItem('key')).eql('value');
    await t.wait(2000);
    await t.eval(() => location.reload(true));
    await t.wait(2000);
    await t.expect(getLocalStorageItem('key')).eql('value');
});
```

**Comment by Juansasa** [comment]
@LavrovArtem 
You are right i debugged the code and found the issues stems from the app code not TestCafe.
Thanks you can close this now :)
