### ISSUE TITLE
Check sizes of objects returned by ClientFuncitons

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#2618]
### Are you requesting a feature or reporting a bug?
Suggestion

### What is the current behavior?
Currently when trying to get a really big object (e.g. an array with about 99k entries) with a ClientFunction tests can silently fail to execute.

### What is the expected behavior?
Check size of the object returned by a ClientFunction and throw a descriptive error if it's too big and can't be serialized and passed to the test code.

**Comment by dlangerenken** [comment]
Hey @AndreyBelym, as stated in #1110, this check might help to throw errors, but it's not helping the underlying problem that an object/array might be of this size and we do want to read it.

I do code-coverage analysis using istanbul-instrumenter. The coverage is logged in window.**coverage** and I need to access this after a successful test-run.

**Comment by Farfurix** [comment]
@dlangerenken.

Hello.
At present, we are going to prevent the silent fail using an error. However, we will take your suggestion into account for the future.
