### ISSUE TITLE
Implement user action emulation using Firefox Marionette protocol

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#2623]

**Comment by tsvetann** [comment]
May I kindly  ask if there are any plans to move this forward. Thx :)

**Comment by AndreyBelym** [comment]
Thank you for your interest. We tried to implement it a year ago: https://github.com/DevExpress/testcafe/pull/2626. Unfortunately, we found that built-in actions don't cover some scenarios that was brought to us by customers and saved as functional tests.
