### ISSUE TITLE
Implement user action emulation using Chrome Remote Debugging protocol

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#2624]

**Comment by tsvetann** [comment]
May I kindly ask if there are any plans to move this forward. Thx :)

**Comment by AndreyBelym** [comment]
I've tried to describe briefly our situation with this feature in [another comment](https://github.com/DevExpress/testcafe/issues/2623#issuecomment-526117765). Situation with Chrome is very similar.
