### ISSUE TITLE
Investigate possibilities of connection problems monitoring

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#2627]
- [ ] Document parts of the browser connections system that can be useful for logging
 - [ ] Check possibility of running browser heartbeat code in a separate worker for improving heartbeat reliability

**Comment by miherlosev** [comment]
Causes of the `The {userAgent} browser disconnected` problem:
* testcafe and hammerhead code problems
* not enough memory
* unexpected system dialogs (`Allow multiple downloads`, `Choose color`, `Print` and etc.)
* absence of system components (some actions require an ICCCM/EWMH-compliant window manager on Linux)

**Comment by AndreyBelym** [comment]
Additionally to the things mentioned by @miherlosev, I think we should also note problems, when a browser is connected, but test execution hangs indefinitely, until TestCafe process is interrupted, e.g. by pressing `<Ctrl> + C`:
* testcafe and hammerhead code problems
* network problems (resulting in failed driver requests to server)
* infinite redirect

**Comment by harry7771** [comment]
I have used TestCafe in both my current position and in my previous position, and in both cases we face a persistent, unsolvable *intermittent* issue:  TestCafe fails to receive contact from a BrowserStack browser before TestCafe times out, reporting: "Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure."

For some reason the issue occurs with Firefox on BrowserStack more than other browsers.

**Comment by Farfurix** [comment]
@harry7771 

Hello,

There are some problems related to connect stability using BrowserStack. This can be caused for many reasons, for example: [https://github.com/browserstack/browserstack-local-nodejs/issues/41](https://github.com/browserstack/browserstack-local-nodejs/issues/41). We'll think about ways to stabilize the launch of tests and "loss of connection" notifications.

**Comment by harry7771** [comment]
Thanks. I've messed around with increasing/decreasing all of the TestCafe and BrowserStack timeouts that I can with no luck.  I just can't get TestCafe to wait around a half-minute more for BrowserStack to catch up to it. 

Thanks for whatever your team is able to do.  I and many others will be anxiously awaiting a fix!

**Comment by AndreyBelym** [comment]
We decided to integrate these ideas into the main list in https://github.com/DevExpress/testcafe/issues/2413
