### ISSUE TITLE
APIv2: Figure out duplex server-client communication protocol

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#263]

**Comment by AlexanderMoskovkin** [comment]
I'm working on this

**Comment by inikulin** [comment]
Ok, I've kinda figured out how we can do thing right. Ping me tomorrow, pls

**Comment by inikulin** [comment]
## Handling page error
- Send `about:page-error` and add pending error (this is blocking on DevExpress/testcafe-hammerhead#339)
- Then if error was not handled use standard `done` mechanism

## Client driver
- Create `src/client/driver` lib.
- Driver waits page ready event and sends `ready` hanging message to test run
- Once it get's message it executes appropriate automation/assertion
- Save `executingCommand` flag to `true` and run automation
- Set xhr/page load barrier
- If page not unloaded then send `ready` with the success status, set  `executingCommand` flag to `false` 
- If we have a new page load, check `executingCommand` flag, if it's true, repeat actions from the step above.


## Processing commands
- Commands should be defined as classes for the clarity, so we will have defined set of fields
- On client we will need to get elements from selectors contained in command, for this we should use our querying mechanism (try to obtain element within 10 seconds).
- For client errors create declarative classes in `src/client/driver/errors`.

## First steps
- Start implementing driver 
- Start implementing `click` action in both raw and v2 format (implement options validation, etc.)
- Figure out minimal required assertions mechanims and implement it.
- Create functional tests for click

**Comment by inikulin** [comment]
Closed in #263
