### ISSUE TITLE
Implementing digest authentication

### ISSUE THREAD

**Issue by gknapp** [DevExpress/testcafe#2630]
I'd like to implement digest authentication, I started out writing this as a `RequestHook` but I am not sure if a test hook might be a better option?

I need to persist some state, perhaps in the test context object? To authenticate:

- Request page
- Check if HTTP status code is `401`
- If `401`, read `WWW-Authenticate` header, generate an MD5 digest (using `nonce`, `opaque`, `realm` and credentials, taken from test config) and store it for future requests.
Re-issue request with `Authorization` header set (includes digest).
- If not `401`, include `Authorization` header with digest value (assume step 1/2 occured earlier).

Step 4 might not be needed, only if tests have to re-auth (unlikely).

What is the best mechanism for this? How can I re-send the request if an authentication challenge is received from the server?

I note there are requests for docs in #2489 and #2104

Thanks, Greg

**Comment by AndreyBelym** [comment]
Hi @gknapp, currently `RequestHook`s are the only options to work with request. The purpose of test hooks is to execute some code when a fixture or a test started/finished to perform initialization/clean-up steps. You can't intercept a request and modify its response from a test hook.

**Comment by gknapp** [comment]
Is there a recommended way to persist state using a RequestHook? I'll need to store the generated MD5 digest.

**Comment by claudiocro** [comment]
@gknapp did manage to git it to work? I have the same problem. Also i don't get the headers in the `onResponse` functions, thank for a short clarification.

**Comment by gknapp** [comment]
I've not revisited this yet to implement it. It's not front of mind or clear to me the cleanest place to store state.

Could you obtain the nonce?
