### ISSUE TITLE
Allow to change URL using requestOptions.url in RequestHooks

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#2635]
### Are you requesting a feature or reporting a bug?
Enhancement

### What is the current behavior?
The destination URL of a request can be changed in a RequestHook by modifying parts like `hostname`, `port`, `protocol` of the URL by altering corresponding properties of a `requestOptions` object. The `requestOptions.url` property can be changed, but it doesn't lead to change of the request's destination.

### What is the expected behavior?
The destination of a request must be changed when the `requestOptions.url` is changed.

**Comment by kennychua** [comment]
any leads for fixing this issue? I'd be interested in picking this up if you think this is easy enough to understand -- I'm new to the testcafe codebase

**Comment by miherlosev** [comment]
Hi @kennychua 

Thank you for your interest in TestCafe. At present, we don't have a final API design for this enhancement.  We will discuss about it and let you know about results.

**Comment by gudoy** [comment]
We faced the same issue. After struggling a couple of hours try to find why this didn't work, I found a reference to this issue.
If you do not intend to fix this for the moment, it would be nice at least to edit the document [here](https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/requestoptions-object.html) to mark the `url` prop as read-only.

**Comment by miherlosev** [comment]
This feature is implemented.

```js
import { RequestHook } from 'testcafe';

class CustomRequestHook extends RequestHook {
     onRequest (e) {
        e.requestOptions.path = '/another-page';
     }
}
```

**Comment by pjweisberg** [comment]
Do you know how many hours I spent today trying to figure out why changing the url in requestOptions wasn't working?

Almost as many as I spent yesterday trying to figure out why modifying the headers in onResponse didn't work.  At least there's a README somewhere that mentions that that won't work, even though it's not in the jsdoc on the actual method where I might have seen it.

I was on the verge of concluding that the line in the docs about being able to use `onRequest` to change request parameters was just a lie.

**Comment by Aleksey28** [comment]
Hi @pjweisberg,

We apologize for this misunderstanding. We will update information about how to change a URL in the documentation.
