### ISSUE TITLE
When we check an external link to be opened in the current browser, the test fails due to jQuery error in the external site

### ISSUE THREAD

**Issue by vvedachalam** [DevExpress/testcafe#2638]
### Are you requesting a feature or reporting a bug?

BUG

### What is the current behavior?

     Uncaught TypeError: jQuery(...).scrollGallery is not a function
      Browser: Chrome 67.0.3396 / Linux 0.0.0
 1/1 failed (11s)

### What is the expected behavior?
Test should pass as the site opens successfully. It shouldnt depend on the external site

### How would you reproduce the current behavior (if this is a bug)?

Open an external site which throws some jQuery error

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code
home.feature
  Scenario: External-site link is present
    Given I am in homepage
    When I access the External-site link
    Then it should open the External-site 
```step.ts
When(/^I access the External-site link$/, async () => {
    await testController.click(termsandconditionspage.getExtenalSiteLink());
})

Then(/^it should open the Cloud-IQ site$/, async () => {
    const currentLocation = ClientFunction(() => document.location.href).with({ boundTestRun: testController });
    await testController.expect(currentLocation()).contains(homepage.getExternalSiteURL());
})

``` page.ts
import { Selector } from 'testcafe'
import { testController } from '../../support/testControllerHolder'

const EXTSITEURL = 'http://www.cloud-iq.com';
const EXTSITELINK= Selector('div[name=tc-ciq--txt-container--txt] 

export class Page {
    getCloudIQLink() {
        return EXTSITELINK.with({ boundTestRun: testController });
    }
    getCloudIQURL() {
        return EXTSITEURL;
    }
}
### Specify your

* operating system: LINUX 
* testcafe version: 0.19.2
* node.js version: 10.1.0

**Comment by AndreyBelym** [comment]
Hi @vvedachalam, TestCafe aborts test execution when an uncaught exception is raised on a page. If you don't like this behavior, you can turn it off by using the `-e` CLI switch or the `skipJsErrors` runner's option: [-e, --skip-js-errors](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors), [Runner#run](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#run)

**Comment by AndreyBelym** [comment]
You can also use a [RequestMock](http://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/mocking-http-responses.html) instance to replace the content of the third-party site with a test data.
