### ISSUE TITLE
fixture.beforeEach doen not work together with test.before

### ISSUE THREAD

**Issue by testcafeninja** [DevExpress/testcafe#2646]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
You can use either fixture.beforeEach hook or test.before hook. Both cannot be used together

### What is the expected behavior?
As per the documentation we can use both at the same time.

### How would you reproduce the current behavior (if this is a bug)?
Get message printed from the below code.

fixture `Getting Started`
    .page `http://devexpress.github.io/testcafe/example`
    .beforeEach(async t => {
        console.log('Inside beforeEach hook')
    });

test
    .before(async t => {
        console.log('Inside before Test hook')
    })
    ('My first test', async t => {
        console.log('Inside Test')
    });

You will not get message printed for both the hook (i.e. fixture.beforeEach and test.before) together.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js
fixture `Getting Started`
    .page `http://devexpress.github.io/testcafe/example`
    .beforeEach(async t => {
        console.log('Inside beforeEach hook')
    });

test
    .before(async t => {
        console.log('Inside before Test hook')
    })
    ('My first test', async t => {
        console.log('Inside Test')
    });
```

### Specify your

* operating system: Mac
* testcafe version:0.20.5
* node.js version:8.9.4
* npm version: 5.6.0

**Comment by AndreyBelym** [comment]
Hi @testcafeninja! It's not a bug. The documentation for [Test Hooks](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#test-hooks) has a note about this behavior:
```
If test.before or test.after is specified, it overrides the corresponding fixture.beforeEach and fixture.afterEach hook, so that the latter are not executed.
```

**Comment by AndreyBelym** [comment]
There is a proposal (https://github.com/DevExpress/testcafe/issues/2230) that suggests to run test hooks in the way that you described in this issue. You can add 👍 to it to help us decide what features we should consider for implementation.
