### ISSUE TITLE
Waiting so much after downloading a file

### ISSUE THREAD

**Issue by kaansan** [DevExpress/testcafe#2647]
### Are you requesting a feature or reporting a bug?

**Bug**

### What is the current behavior?

**testCafe waits so much after downloading a file.
waits about 13 secs.**

### What is the expected behavior?

**It shouldn't wait after downloading a file.**

### How would you reproduce the current behavior (if this is a bug)?

**It should wait as less as possible.**

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: `https://sonuc.ysk.gov.tr/module/sspsYeni.jsf`

On this page you should select first option then, select a city = 'Secim cevresi adi' 
select a novice = 'Ilce secim kurulu adi' then click 'Sorgula' button and '
click Tabloyu kaydet (excel)' button. This will download a xls file after that testcafe succesfully downloads but waits so much after download.

Test code
here is the video for demonstration.
https://vimeo.com/280921314

I didn't want to publish the code but if it's necessary I can.

### Specify your

* operating system: Mac OS X 10.13.3
* testcafe version: 0.20.5
* node.js version: v6.0.0

**Comment by stephenryanlee** [comment]
We have this issue too. Download a file and then it just sits there for like 15s before moving on. I assume this is just to allow a good amount of time for a file to download, since TestCafe may not be able to know when it finishes. 

Short of a fix, does anyone know of a workaround at least, so we can proceed with the test without having to wait? Thanks

**Comment by AlexSkorkin** [comment]
Check out these threads for a workaround:

[How to do fs.existsSync(path) with Timeout](https://stackoverflow.com/questions/48910111/how-to-do-fs-existssyncpath-with-timeout)
[Testcafe example to assert file download](https://stackoverflow.com/questions/57582108/testcafe-example-to-assert-file-download)

**Comment by stephenryanlee** [comment]
Thanks for the response @AlexSkorkin. It seems like these threads are all about solving the problem of waiting long enough for the file to download and then verifying it's there.

I have sort of the opposite problem, which is that my files download almost instantaneously but then TestCafe waits 15s before executing the next line. For a simple example:

```
  let time = Date.now();
  await t.click(Selector("span").withText("Download"));
  console.log("time after: ", Date.now() - time);
```

yields:
```
time after:  15157 // 15 seconds have elapsed
```

I'm looking for a way to have TestCafe not do that default 15s wait...

**Comment by LavrovArtem** [comment]
Unfortunately, we don't have a workaround for this issue at the moment.
