### ISSUE TITLE
Testcafe's proxy seems to have a problem with connecting to websockets

### ISSUE THREAD

**Issue by ColCh** [DevExpress/testcafe#2649]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

Test runs one time.

After that, testcafe not runs and crashes with error.

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onread (net.js:659:25)
Emitted 'error' event at:
    at Socket.onerror (_stream_readable.js:693:12)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm forced to restart webpack-dev-server every time after testcafe run.

Unfortunately, behaviour is not determined. This error is not really every time.

### What is the expected behavior?

There should be no error

### How would you reproduce the current behavior (if this is a bug)?

Use create-react-app.

run `yarn run start` to start the app. Provide `http://localhost:3000` as app url to `testcafe`

#### Provide the test code and the tested page URL (if applicable)

it's possible to test on CRA

### Specify your

* operating system: MAC OS 10.13.5
* testcafe version: 0.20.5
* node.js version: v10.1.0

**Comment by LavrovArtem** [comment]
Hi @ColCh,
I've investigated this issue and I cannot reproduce it. I have Node.js `v10.5.0`. Could you please update your Node.js to `v10.5.0` or higher?

**Comment by ColCh** [comment]
Hi @LavrovArtem 

updated to `v10.7.0`, got same result...

I throws after testcafe starts. It seems that it tries to proxy websocket request and fails because of that.

CRA uses websockets with webpack-dev-server.

How can I get more information about this issue? It's pretty random

**Comment by ColCh** [comment]
oh sorry, with `v10.5.0` works nicely, my bad

it seems that using specified nodejs version resolved my issue

Thanks!

**Comment by willgarcia** [comment]
I have the same issue with node `v.10.5.0`:

```
Error: read ECONNRESET
    at TCP.onread (net.js:656:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! e2e@1.0.0 test: `testcafe --hostname localhost chrome ./src`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the e2e@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by miherlosev** [comment]
@willgarcia 

Which version of the TestCafe do you use?

**Comment by willgarcia** [comment]
@miherlosev TestCafe version 0.20.5

**Comment by miherlosev** [comment]
@willgarcia 

Try to use the latest TestCafe (`0.21.1`) version and let us know about result.

**Comment by ColCh** [comment]
Let's reopen this and try to find why this happends

Any idea out there?

**Comment by MarinaRukavitsyna** [comment]
Hello guys,
It looks like you have encountered the issue that we are going to fix in the context of the following thread:
https://github.com/DevExpress/testcafe/issues/2711

**Comment by ColCh** [comment]
Thank you @MarinaRukavitsyna !
