### ISSUE TITLE
Request hook added multiple times when using filter rule

### ISSUE THREAD

**Issue by andrzej-kodify** [DevExpress/testcafe#2650]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
If I initialize hook without filter like `const hook = new RequestLogger();` then `onRequest` and `onResponse` are executed only once with running tests.
But adding filter function seems like attaching new hook with each executed test.

```
const filterFunction = function (request) {
    return !/^https?:\/\/\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/.test(request.url);
};

const hook = new RequestLogger(filterFunction);
fixture('Test').requestHooks(hook);

----

import { RequestHook } from 'testcafe';

export class RequestLogger extends RequestHook {
    constructor(requestFilterRuleInit) {
        super(requestFilterRuleInit, DEFAULT_OPTIONS);
    }

    onRequest(event) {
       // This get's called as many times as number executed tests in run
    }

    onResponse(event) {
       // This get's called as many times as number executed tests in run
  }
}
```

### What is the expected behavior?
I would expect that since it's the same `const` hook it won't get attached more than once.

### How would you reproduce the current behavior (if this is a bug)?
See below

#### Provide the test code and the tested page URL (if applicable)
https://github.com/andrzej-kodify/testcafe-requesthook-bug

### Specify your

* operating system: OSX
* testcafe version: 0.20.5
* node.js version: v10.5.0

**Comment by andrzej-kodify** [comment]
Hi @miherlosev 
I want to process requests by adding custom headers, logging them in real time, etc. 
But other than that shouldn't it just work since creating custom hooks is described in official docs https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/creating-a-custom-http-request-hook.html ?

**Comment by miherlosev** [comment]
I'm working on this
