### ISSUE TITLE
Unable to access element with style=display:none

### ISSUE THREAD

**Issue by vvedachalam** [DevExpress/testcafe#2653]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?
Not identifying hidden form elements

### What is the expected behaviour?
There is an upload functionality in which the file input field is hidden.
When we select a file, it automatically uploads using the hidden file input field. 
But TestCafe does not identify the element.

<input accept="image/*" name="file" id="file" type="file" style="display: none;">
### How would you reproduce the current behavior (if this is a bug)?

Try any field by setting the style to display:none
<input accept="image/*" name="file" id="file" type="file" style="display: none;">

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```page.ts
import { Selector } from 'testcafe'
import { testController } from '../../support/testControllerHolder'

const BROWSEYOURCOMPUTERBUTTON = Selector('span[name=upload-logo--browse-img--btn]');
const FILEPATHBOX = Selector('#file');

export class Page {
    getBrowseYourComputerButton() {
        return BROWSEYOURCOMPUTERBUTTON.with({ boundTestRun: testController });
    }
    getFilePathBox() {
        return FILEPATHBOX.with({boundTestRun: testController});
    }
}

```step.ts
import { Given, When, Then } from 'cucumber';
import { ClientFunction } from 'testcafe'
import { testController } from '../support/testControllerHolder';
import { Page } from "../support/pages/page";

const page: Page = new Page();
const RIGHTSIZEANDFILEEXT = '../images/3C-1.jpg';

Then(/^I successfully upload an image file less than 300kb size$/, async () => {
  //  await testController.click(page.getBrowseYourComputerButton());
    await testController.setFilesToUpload('#file',RIGHTSIZEANDFILEEXT);
    await testController.expect(addlogopage.getFilePathBox().value).eql(RIGHTSIZEANDFILEEXT);
})



### Specify your

* operating system: ubuntu
* testcafe version: 0.19.2
* node.js version: 10.1.0

**Comment by MarinaRukavitsyna** [comment]
@vvedachalam 
Would you please also provide us with the markup of the tested page?

**Comment by vvedachalam** [comment]
@MarinaRukavitsyna 
Please find the markup below:

<div class="styles__Wrapper-hZyTcS eOiKsB">
<form action="http://merchants-cloudiq-rook-dev-01-staging.storage.googleapis.com" method="post" enctype="multipart/form-data">
<input type="hidden" name="key" value="cloud-iq-default-merchant-id/raw_logotype/undefined">
<input type="hidden" name="bucket" value="merchants-cloudiq-rook-dev-01-staging">
<input type="hidden" name="GoogleAccessId" value="gcp-local@cloudiq-rook-dev-01.iam.gserviceaccount.com">
<input type="hidden" name="acl" value="public-read"><input type="hidden" name="success_action_status" value="201">
<input type="hidden" name="policy" value="eyJleHBpcmF0aW9uIjoiMjAxOC0wNy0yNVQwOTo1NTowNS41MDFaIiwiY29uZGl0aW9ucyI6W1sic3RhcnRzLXdpdGgiLCIka2V5IiwiY2xvdWQtaXEtZGVmYXVsdC1tZXJjaGFudC1pZC9yYXdfbG9nb3R5cGUvIl0seyJidWNrZXQiOiJtZXJjaGFudHMtY2xvdWRpcS1yb29rLWRldi0wMS1zdGFnaW5nIn0seyJhY2wiOiJwdWJsaWMtcmVhZCJ9LHsic3VjY2Vzc19hY3Rpb25fc3RhdHVzIjoiMjAxIn0sWyJjb250ZW50LWxlbmd0aC1yYW5nZSIsMCwzMDcyMDBdXX0=">
<input type="hidden" name="signature" value="SN+B+T0sqIX4pJQhARfOzqA3sQ7X/Ynybc/tYYQNHnLzJC61ST2tdIy/9aYctW4b4817aLnX2TKiitEo3liqLbQDg+APY5tFwLXjprnOmtOKYRqgKg3R2MwQjy9H2Z5Gmc/YWKhTuHpRoNkfeCb0xBHsKRUD05lhrIyo2XErlxM0biu6YWzrJ/VnJiz5H+GU9teRCoo8FUx947FEMmEuiTDw5NdHI2q5aZ+9nQJQhSYxPvTZ7VU5+NCKSJsFCEMOU1PXojGQDKyEb1fStRwFEIrKkvv17nXhaOflH+heia+811jVh6gPGcJraMmpAbXGKGJVwEGyM82MMS7j6J+31w==">
<input accept="image/*" name="file" id="file" type="file" style="display: none;">
</form>
<label for="file">
<span tabindex="0" class="MuiButtonBase-root-16 MuiButton-root-1 MuiButton-raised-6 styles__Button-fnfXjj cISAIm styles__BaseButton-gRoMHg iuAfeO Button__FlatButton-fmRbh ebjtSM" role="button" name="upload-logo--browse-img--btn">
<span class="MuiButton-label-2">Browse your computer</span>
<span class="MuiTouchRipple-root-18"></span>
</span>
</label>
</div>

**Comment by hdorgeval** [comment]
Hi @vvedachalam : my advice is that e2e test code should never do what a real user cannot do. 
A real user will never be able to interact with a hidden field. 
Your test is not an e2e test and should be placed in a unit test outside of TestCafe.

**Comment by vvedachalam** [comment]
@hdorgeval - The e2e test that I am trying to do is : 
When the user clicks 'Browse your Computer' button, a window popup appears where the user selects a file. Once they select the file, behind the scenes the file is uploaded using the hidden file element. 
I tried to open the file explorer by clicking the 'Browse  Your Computer' button. But I couldnt see it.
How to handle this scenario? - Opening file explorer and selecting a file.

````steps.ts
Then(/^I successfully upload an image file less than 300kb size$/, async () => {
    await testController.expect(addlogopage.getBrowseYourComputerButton().visible).ok();
    await testController.click(addlogopage.getBrowseYourComputerButton());
}

**Comment by hdorgeval** [comment]
@vvedachalam : what I understand from what you provided is that there is some magic hidden javascript that links the click on the (not a true) button and  pushes, behind the scene, the selected files to the hidden input field and then automatically upload files. Maybe you are relying on an external JS library for handling these file uploads. Could you tell me which library you are using and where I can find a sample page or a playground site for that library? Cheers

**Comment by vvedachalam** [comment]
@hdorgeval Sure, will provide you the details soon. 
Meanwhile, could you please tell me, why clicking the button is not invoking the file explorer? Like selenium (in which we use AutoIT to handle the windows popups), wont testCafe handle windows popup? Or is it Ubuntu issue (I am using Ubuntu)

**Comment by vvedachalam** [comment]
@hdorgeval Thanks a lot. I will try to execute the code on my mac today. Could you please run this in ubuntu if possible?

**Comment by vvedachalam** [comment]
@hdorgeval, here we access the hidden element and upload the image. If we click on the 'Browse your computer' button, will it invoke the file explorer window? Can we automate the real e2e flow?

**Comment by AndreyBelym** [comment]
@vvedachalam, native upload window can't be automated, because it's a native OS window, and TestCafe can automate only HTML elements.

**Comment by hdorgeval** [comment]
Thank you @AndreyBelym for the feedback.

**Comment by vvedachalam** [comment]
@AndreyBelym Thanks for that. said that, can we integrate autoIT (like how we do for selenium)? Does TestCafe support that?

**Comment by hdorgeval** [comment]
@vvedachalam : from what I understand by reading the autoIT documentation, it seems to me that autoIT execution result is exactly the same as `setFilesToUpload`.

So in my opinion, thank's to TestCafe, you do not need autoIT anymore.

**Comment by vvedachalam** [comment]
@hdorgeval AutoIT handles windows Explorer which selenium cant handle.
So is TestCafe. When windows explorer appears, testCafe cant handle it. So rather we use the hidden element to pass the file value

**Comment by vvedachalam** [comment]
@hdorgeval Is it uploading the file? I tried in my Mac. For me, it's only entering the image path into the file textbox. Not uploading. Even I triggered 'enter' key press but no success. 

    await testController.setFilesToUpload(addlogopage.getFilePathBox(),RIGHTSIZEANDFILEEXT);
    await testController.pressKey('enter');

Did you get a chance to run this in Ubuntu machine? Its one of our critical paths for our August release.

**Comment by hdorgeval** [comment]
@vvedachalam : to upload the file, you need a submit button inside the form.

**Comment by vvedachalam** [comment]
@hdorgeval Please find the form code in my above comments[https://github.com/DevExpress/testcafe/issues/2653#issuecomment-407685896](url)

**Comment by vvedachalam** [comment]
@hdorgeval , Thanks for the same. In that case how to trigger that action to upload the file? I tried tab, enter, tab & enter but none submitted the file

**Comment by hdorgeval** [comment]
@vvedachalam : 
```js
await t.setFilesToUpload(inputFileSelector, imagePath);
```
will change the content of the input file field and therefore this will raise the `onchange` event on this field.

So you just need to add this in your html page:

```html
<script>
    document.getElementById('file').onchange = function(e) {
        console.log("auto submitting on file submission", e);
        document.getElementsByTagName('form')[0].submit();
    };
</script>
```

and `t.setFilesToUpload` action will automatically upload the file.

If if does not work on your existing html page: either there is a javascript error that prevents the `onchange` event to fire or you should try to upgrade to latest TestCafe version.

**Comment by vvedachalam** [comment]
@hdorgeval Currently the automatic upload works fine in the page. There is no issue at all. Only in the TestCafe script, after setting the t.setFilesToUpload it is not triggering the upload.
In your [code](https://github.com/DevExpress/testcafe/issues/2653#issuecomment-407867009) the last two lines are:

    await t.setFilesToUpload(inputFileSelector, imagePath);
    await t.expect(inputFileSelector.value).contains(imageName, {timeout: 5000});
If the file is uploaded after setting t.setFilesToUpload, when you assert in the next line t.expect it will fail as the file text will be empty once the file is uploaded (Successfully or unsuccessfully)

The code I used is (to check to fakepath set by system)
    await testController.setFilesToUpload(addlogopage.getFilePathBox(),RIGHTSIZEANDFILEEXT);
    await testController.expect(addlogopage.getFilePathBox().value).eql('C:\\fakepath\\3C-1.jpg');

For me also the assertion passes but it remains in the same page after assertion as the file is not uploaded

NB: Did you check in any *nix machine as our client uses Ubuntu and I need to run the tests in Ubuntu

**Comment by hdorgeval** [comment]
@vvedachalam : could you provide the complete javascript code that enables the form to be auto submitted?

**Comment by vvedachalam** [comment]
@hdorgeval  Thanks a lot for all the kind support. The tests are running successfully in Ubuntu after upgrading to TestCafe version 0.20.2. (Though haven't checked in Mac but hope it should be ok in Mac too)
The error logging in the console also has been improved considerably. it specifies the element rather throwing common error message : *TypeError: frames[i].getFunctionName is not a function*

Closing the issue
