### ISSUE TITLE
document.getElementsByTagName returns large number of undefined tags and can't search by name attribute

### ISSUE THREAD

**Issue by andrewlw89** [DevExpress/testcafe#2670]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
When executing through the testcafe browser, using document.getElementsByTagName() returns tags that match but also returns up to another 10000 tags that are undefined when you click them in the javascript console.

More over, searching for a specific tag using syntax similar to this
```js
document.getElementsByTagName('meta')['csrf-token'];
```
will return undefined despite the tag existing in the DOM.

Example: 
1. document.getElementsByTagName('body') returns 10000 tags, most undefined
2. document.getElementsByTagName('meta')['csrf-token'] returns undefined

### What is the expected behavior?
Expected behavior is that only the elements that match by tag name will be returned and none that are simply undefined

### How would you reproduce the current behavior (if this is a bug)?
1.) Fire off a test against any website (tested in Chrome, Safari, Firefox)
2.) Put in a t.debug() command in the test
3.) Open developer tools after debug trips
4.) Open javascript console
5.) run - document.getElementsByTagName('body')
6.) 10000 tags will be returned and only 1, the actual body tag, will be defined
7.) run - document.getElementsByTagName('meta')['viewport']
8.) Expect to get the meta tag containing viewport info but instead get undefined

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: Can confirm against any site

Test code

Only test code needed is a t.debug() after loading the page in the fixture

### Specify your

* operating system: High Sierra 10.13.4
* testcafe version: 0.20.5
* node.js version: v8.9.0

**Comment by LavrovArtem** [comment]
Hi @andrewlw89,
This issue related to https://github.com/DevExpress/testcafe-hammerhead/issues/1376.

**Comment by andrewlw89** [comment]
Hey @LavrovArtem,

Thanks for linking that issue. They definitely seem similar.

At first glance, it looks to me like an error in how the namedItem() method is being implemented for the wrappers that go around the native selector methods. (https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/node/live-node-list/wrapper.js)[here]. That would normally allow for this lookup by string rather than by index.

I was wondering if you might be able to provide an update into the issue you linked to above and where it stands with regards to a solution. I'm currently looking into this issue as well and would be happy to offer some sort of collaboration with you guys if that would help reach a solution.

Thanks!

**Comment by andrewlw89** [comment]
@LavrovArtem while playing around with this, it looks like testcafe already supports using namedItem with standard dot notation. I believe the main issue here is that bracket syntax was never implemented.

Example 1 (works): document.getElementsByTagName('meta').namedItem('csrf-token')
Example 2 (fails): document.getElementsByTagName('meta')['csrf-token']

The bottom syntax should work identical to the top but returns undefined instead.

**Comment by MarinaRukavitsyna** [comment]
@andrewlw89 
Thank you for your research. We are going to fix this issue in the next release.

**Comment by miherlosev** [comment]
Fixed in https://github.com/DevExpress/testcafe/pull/2779
