### ISSUE TITLE
Add selector function to get CSS selector

### ISSUE THREAD

**Issue by palpatine1991** [DevExpress/testcafe#2671]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
Selectors are created in 2 different ways
 - By `Selector` constructor using CSS selector, e.g. `let mySelector = Selector('#MyNode')`
 - By using `Selector` functions, e.g. mySelector.find('.myCLass')

Currently there is no way to obtain the CSS selector back from Selector object, e.g. `mySelector.getCssSelector() //Expected result '#MyNode .myClass'`

### What is the expected behavior?
It would be nice to have such possibility. I did try to debug the testcafe code but I did not find any way how to get this information.

**Comment by palpatine1991** [comment]
@AndreyBelym I am not sure if those two issues are representing what I am asking for.

What I am looking for is to get the CSS selector from the Selector class instance. It is sometimes useful for us when we are writing our own ClientFunctions for some features which are missing from TestCafe. In this case, the client function accepts the CSS selector and therefore we need to duplicate the selector building logic.

Having the `Selector.getCssSelector()` method would simply our life significantly.

**Comment by AndreyBelym** [comment]
Hi @palpatine1991, I've got your point. However there are tips that can help you right now:

1.  You can access the element specified by a Selector in a ClientFunction by specifying the corresponding Selector as a [dependency](https://devexpress.github.io/testcafe/documentation/test-api/obtaining-data-from-the-client/#optionsdependencies).

2. You can wrap Selector constructor with your own function, and store CSS selector as a property on the Selector:
```js
function createSelector (cssSelector) {
    return Object.assign(Selector(cssSelector), { cssSelector });
} 
//...
const mySelector = createSelector('...');

console.log(mySelector.cssSelector);
```
