### ISSUE TITLE
How do I wait for an element that exists in a page for API Call

### ISSUE THREAD

**Issue by raja1313** [DevExpress/testcafe#2676]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

How do I wait for an element that exists in a page for API Call

### What is the expected behavior?

My Testcase failed if the element is not present at that time

### How would you reproduce the current behavior (if this is a bug)?

Click a button, It goes to the next page, I wanna click a button there. But that button would be shown after five minutes(API call). 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js
  const activityBtn = Selector('#getstartedHBtn');
  test('TestReport', async t => {
  await t
 .click(".btn.deploy.right") 
  const activityBtnElement1 = await activityBtn.with({ visibilityCheck: true })()
 .click(activityBtn)
    });
```

### Specify your

* operating system:MAC OS
* testcafe version:0.20.4
* node.js version:4.0.0

**Comment by AndreyBelym** [comment]
Hi @raja1313, I guess you should specify the [timeout](http://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/selector-options.html#optionstimeout) option for the `Selector` of the button.

**Comment by raja1313** [comment]
Hi @AndreyBelym, The time varies for every run of test cases.
For Example: In my case, The button only displayed when the status got 200. Here I wanna wait for the button to be visible and then click, But testcafe doesn't wait for too much of time

**Comment by hdorgeval** [comment]
@raja1313 : [testcafe snippets](https://github.com/hdorgeval/testcafe-snippets) might help you to handle your business case correctly

**Comment by miherlosev** [comment]
@raja1313 

Please specify the [timeout](http://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/selector-options.html#optionstimeout) option for the `Selector` of your button.

```js
const button = Selector('you button selector', { timeout: 60000});

await t.click(button);
```
