### ISSUE TITLE
t.navigateTo broken 

### ISSUE THREAD

**Issue by emildimitrov** [DevExpress/testcafe#2678]
Bug report

t.navigateTo singe page app does not open

t.navigateTo single page app opens the page

When i updated to 0.20.5 from 0.19.2 t.navigateTo functionality stopped working correctly

I'm not specifying url on test or fixture. I'm navigating from the test implementation

Example await t.navigateTo('desktop.ttqa4.xyz/register')

* operating system: OSX
* testcafe version: 0.20.5
* node.js version: 6.5

**Comment by emildimitrov** [comment]
Rolling back to 0.19.2 fixes it, but i'm losing meta features

**Comment by AndreyBelym** [comment]
Hi @emildimitrov, try to specify protocol in the links specified in the `navigateTo` action.

**Comment by emildimitrov** [comment]
Hi @AndreyBelym with and without protocol its the same. Since 0.19.2 this functionality is broken. I tried all the releases since then

**Comment by emildimitrov** [comment]
If this is helpful the runner shows a blank white screen after the waiting for the page and fails on finding elements on the page, but if untill the runner is waiting i refresh the url test gets executed properly

**Comment by emildimitrov** [comment]
Thanks a lot @LavrovArtem

**Comment by LavrovArtem** [comment]
Related to https://github.com/DevExpress/testcafe-hammerhead/issues/1702

**Comment by miherlosev** [comment]
Fixed in https://github.com/DevExpress/testcafe-hammerhead/commit/6ff79ed73b6efa4e3cb8dd76d7ddceb2ed09f862
