### ISSUE TITLE
Older versions of TestCafe support for IE9?

### ISSUE THREAD

**Issue by chinjon** [DevExpress/testcafe#2685]
### Are you requesting a feature or reporting a bug?
Reporting a bug, but more of a question

### What is the current behavior?
Leveraging _older_ versions of TestCafe to run automated tests on legacy browsers does not work, pages load but interactions and assertions are not being executed.

### What is the expected behavior?

Older versions of TestCafe have compatibility with `IE9`

### How would you reproduce the current behavior (if this is a bug)?
I know that older versions of TestCafe did support `IE9`, this is well documented in the past forum and within a few issues. I tried downgrading to versions `0.19.0`, `0.18.6`, and `0.18.3`, but unable to get TestCafe to run automated tests on `IE9`.

I know the documentation that laid out the official browser support had changed around the release of `0.19.0`.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: http://devexpress.github.io/testcafe/example

Test code

```js
import { Selector } from 'testcafe';

fixture `Getting Started`
    .page `http://devexpress.github.io/testcafe/example`;

test('My first test', async t => {
    await t
        .typeText('#developer-name', 'John Smith')
        .click('#submit-button');
});
```

### Specify your

* operating system: `Windows 7 Ultimate`
* testcafe version: `0.19.0`, `0.18.6`, `0.18.3`
* node.js version: `8.11.2`
* browser: `IE9`

**Comment by AndreyBelym** [comment]
Hi @chinjon! Despite we cleaned our repositories from the code that supported IE 9 & IE 10 not so long time ago, we stopped running our tests in these browser regularly before the `0.9.0-rc1`. So the last known version that works in IE 9 & 10 is `0.3.1-alpha`.

**Comment by chinjon** [comment]
@AndreyBelym Alright, thank you so much for the response. Did some additional testing on my end and found that `0.17.2` works fine with `IE9` and `IE10`.

**Comment by uladzimir-miadzinski** [comment]
0.18.6 also works with IE10
