### ISSUE TITLE
Upgrading to testcafe 0.20 breaks in new relic script

### ISSUE THREAD

**Issue by bdwain** [DevExpress/testcafe#2686]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
When I upgraded my version of testcafe from 0.18 - 0.20, I started seeing errors as soon as I tried to execute an action in my testcafe test. The error was in [new relic's](https://newrelic.com/) code.

`Uncaught TypeError: Cannot read property 'cancelled' of null`

The action I tried to take was just `await t.typeText(Selector('.username', 'foo')`

### What is the expected behavior?
The app should not crash in my third party code.

### How would you reproduce the current behavior (if this is a bug)?
Run a test with newrelic's browser code in the app.

#### Provide the test code and the tested page URL (if applicable)
`await t.typeText(Selector('.username', 'foo')`

I can't provide the app as it's internal. But it's just a plain react app and index.html contains the code provided by new relic to run in your browser.

### Specify your

* operating system: OS X High Sierra
* testcafe version: 0.20.5
* node.js version: 9.11.1

**Comment by miherlosev** [comment]
@LavrovArtem 

See [this](https://testcafe-hhhm.devexpress.com/history?timestamp=1532891201996&siteUrl=http://www.meetup.com/) health monitor run.

**Comment by LavrovArtem** [comment]
fixed in https://github.com/DevExpress/testcafe-hammerhead/pull/1709

**Comment by miherlosev** [comment]
@bdwain 

We have plans to release a new version this week.

**Comment by bdwain** [comment]
Sweet! Thanks!

**Comment by miherlosev** [comment]
Fixed in https://github.com/DevExpress/testcafe/pull/2708
