### ISSUE TITLE
When an element is present in page below the visible area (overflow), it is not picked by testCafe

### ISSUE THREAD

**Issue by vvedachalam** [DevExpress/testcafe#2689]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?
TC is not moving focus to the button element to click. Rather, wait for the element for default wait time and picks a floating button element which is in the visible area of the page

### What is the expected behavior?
Testcafe should click the element though it is present in the overflow area.
Currently I am using tabbing as a work around to bring the button element to the visible area

### How would you reproduce the current behavior (if this is a bug)?
create an element well below the visible area and try to click.
When we check for presence of the element ( .visible & .exists) , it passes but only when we try to click it is not working. It wait for the element until the default timeout period and clicks a button that is visible

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Ubuntu
* testcafe version: 0.20.2
* node.js version: 10.1.0

**Comment by vvedachalam** [comment]
@AndreyBelym Not sure why this issue is not attended. It should be easily reproducible

**Comment by AndreyBelym** [comment]
Hi @vvedachalam! Sorry for the late response, unfortunately I can't reproduce it with my example:

###### test.html
```
<!DOCTYPE html>
<html>
    <head>

    </head>
    <body>
        <button style="margin:3000px;margin: 3000px" onclick="window.clicked=true">Click</button>
        <div style="position:fixed;bottom:0;left:0;right:0;height:50px;background-color:black">
            <button>Click Fixed</button>
        </div>
    </body>
</html>
```

###### test.js
```
import { ClientFunction } from 'testcafe';

fixture `Test fixture`
.page(`./test.html`);

test('Click close button to dismiss modal', async t => {
    await t
        .click('button')
        .expect(ClientFunction(() => window.clicked)()).eql(true);
});
```

Could you please provide me an example layout with the problem?

**Comment by AndreyBelym** [comment]
@vvedachalam, in my test click happens on the first button that isn't fixed and it's over 3 screens in height (given `1600x900` screen resolution) to scroll:
```html
<button style="margin:3000px;margin: 3000px" onclick="window.clicked=true">Click</button>
```

However, I've increased margins and removed the `position: fixed` property, the test still passes:
```
<!DOCTYPE html>
<html>
    <head>

    </head>
    <body>
        <button style="margin:6000px" onclick="window.clicked=true">Click</button>
        <div style="bottom:0;left:0;right:0;height:50px;background-color:black">
            <button>Click Fixed</button>
        </div>
    </body>
</html>
```

Please note that you must avoid interacting with the browser as much as possible while automated tests are running. If TestCafe can't find an element after you've manually scrolled the page, it's not a bug. AFAIK you can't prevent scrolling caused by a real user.

**Comment by vvedachalam** [comment]
@AndreyBelym - Just an update. One of my pages has got a list with 30 items that over spills the visible area but the list has to be expanded by clicking an icon. When I expand the items, TestCafe automatically scrolls down to identify the required item and clicks.
Not sure why it isn't working in the other page. I thought updating to 0.20.5 has fixed the issue as the scenario having 30 items is working but it is not so.

**Comment by AndreyBelym** [comment]
Can't reproduce the issue without a proper example. Feel free to reopen the issue if you have an example where the problem can be reproduced.
