### ISSUE TITLE
RequestLogger 'requests' array always has only one element

### ISSUE THREAD

**Issue by ricovitch** [DevExpress/testcafe#2692]
### Are you requesting a feature or reporting a bug?
Bug report

### What is the current behavior?
When using a RequestLogger for multiple calls, the 'requests' array property has always only one element, which is the first request logged.
This, combined with the RequestLogger 'clear' bug #2688 makes it hard to implement assertions on the lastest request logged.

### What is the expected behavior?
logger.requests[logger.requests.length-1] should always return the latest logged request

### How would you reproduce the current behavior (if this is a bug)?
implement a test which fires multiple logged request, then try to get the latest request element from the requests array

#### Provide the test code and the tested page URL (if applicable)

Test code

```js
test.only('Transactions Base Filters', async (t) => {
  await t.typeText(filters.grossAmountMin, '10')
    .expect(filters.activeFilter.count).eql(1)
    .expect(logger.contains(r => (
      r.response.statusCode === 200
      && requestParser.getParams(r.request.url).grossAmount === '10__value'
    ))).ok()
    .typeText(filters.grossAmountMax, '5')
    .expect(filters.grossAmountMin.getReact(({ props: { error } }) => error)).ok()
    .expect(filters.grossAmountMax.getReact(({ props: { error } }) => error)).ok()
    // check invalid input does not fire a request
    .expect(logger.count(r => (r.request.url.indexOf('grossAmount=10__value__5') > 0))).eql(0)
    .typeText(filters.grossAmountMax, '00')
    .expect(filters.grossAmountMin.getReact(({ props: { error } }) => error)).notOk()
    .expect(filters.grossAmountMax.getReact(({ props: { error } }) => error)).notOk()
    .expect(logger.contains(r => (
      r.response.statusCode === 200
      && requestParser.getParams(r.request.url).grossAmount === '10__value__500'
    ))).ok();

   // in this test there are two requests logged
    console.log('request :', logger.requests[1].request.url); // error
});
```

### Specify your

* operating system: windows 10 / chrome 67
* testcafe version: 0.20.4 (testcafe-hammerhead@14.1.0, testcafe-react-selectors@2.1.0)
* node.js version: 8.9.2

**Comment by miherlosev** [comment]
Hi @ricovitch 

It is difficult to understand a cause of the problem without a direct access to the tested app.
Could you please share a link to the tested app or provide a simple example to reproduce?
In this case, I can fix the problem very fast and provide you a build with fix ASAP.

**Comment by ricovitch** [comment]
Basically, what i observe is that the RequestLogger instance 'requests' array does not allow to access a particular logged request by it's index if there are multiple logged requests.

In the case of multiple logged requests, i thought i could make assertions on the last logged one by getting it from this array, but that does not work like it should.

I think any test with multiple logged request should allow to reproduce this problem.
Just try to access the latest logged request at the end of the test by getting it from the array.

**Comment by miherlosev** [comment]
> Basically, what i observe is that the RequestLogger instance 'requests' array does not allow to access a particular logged request by it's index if there are multiple logged requests.

I don't observer this behavior.
See an example:
```js
import { RequestLogger, Selector } from 'testcafe';

const DEMOS_PAGE_URL = 'https://www.devexpress.com/support/demos/';
const PAGE_URL       = 'https://www.devexpress.com/';

const logger = new RequestLogger(new RegExp(PAGE_URL));

fixture `Fixture`
    .page(PAGE_URL)
    .requestHooks(logger);

test('test', async t => {
    await t.expect(logger.contains(r => r.response.statusCode === 200 && r.request.url == PAGE_URL)).ok();

    console.log(logger.requests.length);
    console.log(logger.requests[logger.requests.length - 1]);

    const demosLinkSelector = Selector('a').withAttribute('href', DEMOS_PAGE_URL);

    await t.click(demosLinkSelector)
        .expect(logger.contains(r => r.response.statusCode === 200 && r.request.url == DEMOS_PAGE_URL)).ok();

    console.log(logger.requests.length);
    console.log(logger.requests[logger.requests.length - 1]);
});

```

> Sorry i can not give access to our apps/apis.

Could you please provide us a simple example to reproduce.

**Comment by ricovitch** [comment]
Sorry for the delay. Back from holidays we had a fresh look at this on our side.
It seems this relates to a misunderstanding of us about "Smart Assertion Query Mechanism".

We where not waiting for logger.count() assertion to update before asserting on logger.requests property.

So for future understanding, this does not work
```
await t.click(filters.resetButton);
const lastRequest = logger.requests[1];
```

And this work
```
await t.click(filters.resetButton)
  .expect(logger.count(() => true)).eql(2);
const lastRequest = logger.requests[1];
```
