### ISSUE TITLE
Modal popup not displayed on home page. Unable to proceed further and blocked.

### ISSUE THREAD

**Issue by sijosyn** [DevExpress/testcafe#2699]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

When I go to http://aperture.synacor.net or https://aperture.synacor.net , the modal popup is not displayed. I'm unable to continue with my tests. (see bug screenshot below)

<img width="1277" alt="screen shot 2018-08-03 at 7 45 23 pm" src="https://user-images.githubusercontent.com/29459281/43670048-f8134f5a-9755-11e8-980e-966d4819cc72.png">

### What is the expected behavior?

The modal popup should be displayed. (see expected screenshot below)

<img width="1280" alt="screen shot 2018-08-03 at 7 19 19 pm" src="https://user-images.githubusercontent.com/29459281/43670086-44a90224-9756-11e8-93ae-73bbcb232905.png">

### How would you reproduce the current behavior (if this is a bug)?

Run test in Chrome, Safari, Firebox.  (Remember to clear cache to see the modal again if user already clicked modal once)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: http://aperture.synacor.net ,  https://aperture.synacor.net , https://start.toshiba.com/ , 

Test code

```
import { Selector } from 'testcafe';

fixture `Test fixture`
.page(`https://aperture.synacor.net`);

test('Click close button to dismiss modal', async t => {
    await t.click(Selector('.modal__email-campaign').find('.close'));
});
```

### Specify your

* operating system: Mac 10.13.6 (High Sierra)
* testcafe version: 0.21.0 (Latest version)
* node.js version: 8.9.4

**Comment by miherlosev** [comment]
Hi @sijosyn 

Thank you for the detailed description. I've reproduced the problem.

**Comment by LavrovArtem** [comment]
Hi @sijosyn,
This issue is related to https://github.com/DevExpress/testcafe-hammerhead/issues/1380.
The tested site sends two requests:
```http://aperture.synacor.net/_/?_uri=component%3A%2F%2FSynacor%2FGen4%2FConfiguration%2FComponents%2FWeather%2F%3Fparse_active%3D0&_action=locate```
and
```http://aperture.synacor.net/_/?_uri=component%3A%2F%2FSynacor%2FGen4%2FConfiguration%2FComponents%2FModal%2FEmailCampaign%2F&_action=display```
These requests are received with a wrong body if headers are lowercased.

**Comment by sijosyn** [comment]
Thanks @LavrovArtem, @miherlosev for investigating & fixing this issue quickly. Nice job. Let me know here the TestCafe version that will be available with this fix.

**Comment by miherlosev** [comment]
Fixed in https://github.com/DevExpress/testcafe/pull/2743
