### ISSUE TITLE
Test speed in headless mode

### ISSUE THREAD

**Issue by smileart** [DevExpress/testcafe#2710]
### Are you requesting a feature or reporting a bug?

Rather asking a question.

### What is the current behaviour?

When running in headless mode `setTestSpeed` factor is still taken into account (judging by the reported execution time). The question is: is it so by design and what's the point of having this delays effective in headless mode? And also: is there any API to find out which params/mode being used right now, at least to change the speed (or any other behaviour) depending on them.

### What is the expected behavior?

Overall I think the test speed should be ignored in headless mode. But it'd be even better to have `testcafe`'s CLI or `browsers`' params to set the desired speed if the current execution is headless.

### How would you reproduce the current behavior (if this is a bug)?

1. Write any test with setTestSpeed less then 1 (e.g. 0.5)
2. Execute it in usual mode. Check the total execution time.
3. Execute the same test in headless (notice a bit shorter execution)
4. Change the test speed back to 1 or entirely delete the statement
5. Execute the test in headless mode one more time (notice much quicker execution)

### Specify your

* operating system: 

> ProductName:    Mac OS X
> ProductVersion: 10.13.6
> BuildVersion:   17G65
> Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz

* testcafe version:
> 0.21.0

* node.js version:
> v9.11.2

**Comment by miherlosev** [comment]
> Overall I think the test speed should be ignored in headless mode.

The `test speed` option works the same way for normal and headless browser. It's by design.

> But it'd be even better to have testcafe's CLI or browsers' params to set the desired speed if the current execution is headless.

You can do it without an additional parameter. Set the 'test speed option' manually if you run browser in headless mode.
```js
const createTestCafe = require('testcafe');
let testcafe         = null;

createTestCafe('localhost', 1337, 1338)
    .then(tc => {
        testcafe     = tc;
        const runner = testcafe.createRunner();

        const isHeadlessMode = true;
        const browser              = 'chrome';
        const runOptions         = {};
     
        if (isHeadlessMode) {
           browser += ':headless';
           runOptions = { speed: 0.5 };
        }
           
        return runner
              .src('tests/test.js')
              .browsers(browser)
              .run(runOptions);
    })

```
