### ISSUE TITLE
Tests started to fail with error message 'window.location.toString' after updating to TC 0.21.1

### ISSUE THREAD

**Issue by vvedachalam** [DevExpress/testcafe#2717]
### Are you requesting a feature or reporting a bug?

BUG

### What is the current behavior?

The tests are passing with TestCafe version 0.20.2 and 0.20.5.
With 0.21.1, the tests are failing

error log:

       Error: { type: 'uncaughtErrorOnPage',
         isTestCafeError: true,
         callsite:
          CallsiteRecord {
            filename: '/home/vijay_vedachalam/Vijay/crow/crow-ui-acceptance-tests/features/step_definitions/dashBoardStep.ts',
            lineNum: 20,
            callsiteFrameIdx: 6,
            stackFrames:
             [ [CallSite],
               [CallSite],
               [CallSite],
               [CallSite],
               [CallSite],
               [CallSite],
               [CallSite],
               [CallSite],
               [CallSite],
               [CallSite] ],
            isV8Frames: true },
         errMsg: 'Uncaught TypeError: window.location.toString is not a function',
         pageDestUrl: 'http://localhost/cart-reminders' }
### What is the expected behavior?

The tests should pass with 0.21.1 version of TC like how they were passing with 0.20.2 & 0.20.5

### How would you reproduce the current behavior (if this is a bug)?

All tests are failing. Not sure whether it is compatibility issue with Cucumber-js

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```page.ts
`import { Selector } from 'testcafe'
`import { testController } from '../../support/testControllerHolder'
`
`const DASHBOARDHEADLINETEXT = Selector('div[name=dashboard--heading--txt]');
`const CARTREMINDERURL = 'http://localhost/cart-reminders';
`
`export class DashboardPage {
`    getCartReminderURL() {
`        return CARTREMINDERURL;
`    }
`    getDashboardHeadlineText() {
`        return DASHBOARDHEADLINETEXTu
`    }
`}

```-----steps.ts
`import { Given, When, Then } from 'cucumber';
`import { testController } from '../support/testControllerHolder';
`const dashboardpage: DashboardPage = new DashboardPage();

`Given(/^I am in Dashboard page$/, async () => {
`    await testController.navigateTo(dashboardpage.getCartReminderURL());
`}

`Then(/^I should see the Dashboard heading$/, async () => {
`    await testController.expect(dashboardpage.getDashboardHeadlineText().visible).ok();
`})

`------scen.feature
`Feature: Verifying Dashboard page
`  Scenario: Dashbaord heading is present
`    Given I am in Dashboard page
`    Then I should see the Dashboard heading

### Specify your

* operating system: Ubuntu 
* testcafe version: 0.21.1
* node.js version: 10.1.0

**Comment by AndreyBelym** [comment]
Hi @vvedachalam! Could you please check the folowing things:

 * That this error is not shown when visiting the problematic page with TestCafe. If it's shown there is an error on your page, and it's better to find and fix it on your side or turn on the [Skip JS Errors](http://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors) mode.

 *  That this error doesn't come after changes in your tested site: install and try to run tests with different TestCafe versions. I think testing `v0.20.5`, `v0.21.0` and finally `v0.21.1` wll be enough as you say that the `v0.20.5` worked fine.

* That turning on the [Skip JS Errors](http://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors) mode won't help TestCafe session won't be continued or finished properly even in this mode.

If the above steps don't help, I'm afraid we'll need access to the problematic page to investigate the problem.

**Comment by vvedachalam** [comment]
@AndreyBelym Just to confirm, its not just one page. I tried all the tests which run against 3 different sites (not just env but totally different domains).
Same tests are passing when I revert to 0.20.2 and 0.20.5
Currently I settled with 0.20.5 upgrade.
I will try Skip JS errors step and keep you posted.
But why this change when my tests are getting executed succesfully with both 0.20.2 and 0.20.5 ?

**Comment by LavrovArtem** [comment]
Hi @vvedachalam,
I've reproduced this problem and created the [issue](https://github.com/DevExpress/testcafe-hammerhead/issues/1722) in the `testcafe-hammerhead` repository.

**Comment by vvedachalam** [comment]
@LavrovArtem Thanks for the update

**Comment by miherlosev** [comment]
Fixed in https://github.com/DevExpress/testcafe/pull/2743
