### ISSUE TITLE
RequestLogger with stringifyResponseBody: true missing null check

### ISSUE THREAD

**Issue by mwhebert** [DevExpress/testcafe#2718]
### Are you requesting a feature or reporting a bug? 
Bug

### What is the current behavior? 
When my client made a bad REST call that returned an http status of 400, this cause the RequestLogger to throw a null exception issue when the stringifyResponseBody is set to true.  In this case the body is null.

testcafe\lib\api\request-hooks\request-logger.js:131:117)

Code that is failing:
        if (this.options.logResponseBody) loggerReq.response.body = this.options.stringifyResponseBody ? event.body.toString() : event.body;

### What is the expected behavior? 
body should be set to null instead of toString being called.

### How would you reproduce the current behavior (if this is a bug)? 
I assume any REST call that returns a null body would reproduce this.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: 
non-accessible server

Test code

```js

```

### Specify your

* operating system: Windows 10
* testcafe version: 0.20.5
* node.js version: v8.10.0

**Comment by miherlosev** [comment]
Hi @mwhebert 

I will try to reproduce this behavior.

**Comment by AndreyBelym** [comment]
Hi @mwhebert! The fix is released in `testcafe@0.22.0`, you can install it with `npm i testcafe@latest` and try it on your machine.
