### ISSUE TITLE
"ERROR No test file specified" while running tests in latest docker image

### ISSUE THREAD

**Issue by okurichenko** [DevExpress/testcafe#2722]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?

Running using docker image testcafe/testcafe:latest fails with error `ERROR No test file specified.`
```
#docker run --network host -v $(pwd)/testcafe:/tests -i testcafe/testcafe "firefox -S /tests/*.js"
Unable to find image 'testcafe/testcafe:latest' locally
latest: Pulling from testcafe/testcafe
a0710691c81a: Pulling fs layer
5d59cf66a84f: Pulling fs layer
51f2e61d569e: Pulling fs layer
9b874c7a69e0: Pulling fs layer
9b874c7a69e0: Waiting
a0710691c81a: Verifying Checksum
a0710691c81a: Download complete
51f2e61d569e: Verifying Checksum
51f2e61d569e: Download complete
a0710691c81a: Pull complete
9b874c7a69e0: Verifying Checksum
9b874c7a69e0: Download complete
5d59cf66a84f: Verifying Checksum
5d59cf66a84f: Download complete
5d59cf66a84f: Pull complete
51f2e61d569e: Pull complete
9b874c7a69e0: Pull complete
Digest: sha256:e5d9fb2ac23d99e3889125ee5e3ed76cdb633d7e1a7cb3419f930a6bac48dcd0
Status: Downloaded newer image for testcafe/testcafe:latest
ERROR No test file specified.
```

The same line works perfect for `testcafe/testcafe:alpha` and worked ~5-6 days ago before latest image has been updated.

### What is the expected behavior?

Docker image `testcafe/testcafe:latest` should find files with tests and run them like before, or if breaking changes were applied, docs of how to use docker image should be updated.

### How would you reproduce the current behavior (if this is a bug)?

Run the following right from tests folder:
```
docker rmi -f testcafe/testcafe
docker run --network host -v $(pwd):/tests -i testcafe/testcafe "firefox -S /tests/*.js"
```

### Specify your

* operating system: Debian Linux
* testcafe version: same as in the latest testcafe/testcafe docker image
* node.js version: 8

**Comment by okurichenko** [comment]
Will answer to myself on this: now it works if you split arguments to different strings like below
`docker run --network host -v $(pwd)/testcafe:/tests -i testcafe/testcafe "firefox" "-S" "/tests/*.js"`

**Comment by miherlosev** [comment]
Hi @okurichenko 

Command `docker run --network host -v $(pwd):/tests -i testcafe/testcafe "firefox -S /tests/*.js"` 
runs TestCafe with only one parameter - `"firefox -S /tests/*.js"`.
TestCafe command line interface requires two parameters: `<browser-list-comma-separated>`, `<file-or-glob ...>`.

The error message `ERROR No test file specified.` tells that you did not specify the second command line argument.

I've corrected your example:

```js
docker rmi -f testcafe/testcafe
docker run --network host -v $(pwd):/tests -i testcafe/testcafe firefox -S /tests/*.js
```

See more detail in the [Using TestCafe Docker Image](https://devexpress.github.io/testcafe/documentation/using-testcafe/using-testcafe-docker-image.html) help topic.

**Comment by okurichenko** [comment]
@miherlosev yes, that's totally clear now. Just saying that it worked 5 days ago with my command. Maybe it will be useful to someone. Thanks
