### ISSUE TITLE
incorrect screenshot path in report output

### ISSUE THREAD

**Issue by cullophid** [DevExpress/testcafe#2726]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
screenshots linked in the test output assumes the default screenshot pattern

### What is the expected behavior?
links should use the pattern set by --screenshot-pattern to link to the correct screenshots

### How would you reproduce the current behavior (if this is a bug)?
set a screenshot pattern that is different from the default an run the test using "spec" or "list" reporter

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Ubuntu 16.4
* testcafe version:  0.21.0
* node.js version:  8.11.3

**Comment by MarinaRukavitsyna** [comment]
@cullophid 
Thank you for pointing out to this issue. I have reproduced it based on your description. We need some additional time to research it.

**Comment by MarinaRukavitsyna** [comment]
A command example:

    testcafe chrome reportIssue.js -r list -s screenshots -p "${DATE}_${TIME}_$(OS)/${FILE_INDEX}.png"

A test example:

    import { Selector } from 'testcafe';

    fixture `Getting Started`
        .page `http://devexpress.github.io/testcafe/example`;

    test('Select Text wait till timeout', async t => {
      const firstNameInput = Selector('#developer-name');

      await t
        .typeText(firstNameInput, 'Max')
        .selectText(firstNameInput)
        .pressKey('delete')
        .takeScreenshot()
        .typeText(firstNameInput, 'Max 2');
    });

**Comment by cullophid** [comment]
Thanks :)

**Comment by miherlosev** [comment]
I'm working on this
