### ISSUE TITLE
Describe new features for version 0.22.0

### ISSUE THREAD

**Issue by MargaritaLoseva** [DevExpress/testcafe#2729]
- [x] CoffeeScript support
https://github.com/DevExpress/testcafe/pull/2651

- [x] Support glob pattern
documentation is ready - https://github.com/DevExpress/testcafe/pull/1805

- [x] new option --ignore-uncaught-errors
https://github.com/DevExpress/testcafe/pull/2606 - described here https://github.com/DevExpress/testcafe/pull/2736

- [x] Callsite for selectors - https://github.com/DevExpress/testcafe/pull/2704
described in https://github.com/DevExpress/testcafe/pull/2733

**Comment by VasilyStrelyaev** [comment]
All topics are ready
