### ISSUE TITLE
Temp files creation

### ISSUE THREAD

**Issue by Lupiano** [DevExpress/testcafe#2735]
### Are you requesting a feature or reporting a bug?

Reporting a bug.

### What is the current behavior?

On every execution there are temp files created in C:\Users\[USER]\AppData\Local\Temp

### What is the expected behavior?

Is there a way to automatically delete these files? We run the tests in a VM and it is running out of hd space.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

operating system: Windows 7
testcafe version: 0.20.4
node.js version: 8.11.3

**Comment by AndreyBelym** [comment]
Hi @Lupiano! I've reproduced the issue. TestCafe creates temporary directories for Chrome and Firefox profiles for each test session using the [tmp](https://github.com/raszi/node-tmp) module. Looks like the module can't properly remove directories when TestCafe execution is finished. I will fix it ASAP.

**Comment by Lupiano** [comment]
Great @AndreyBelym! Thanks!

**Comment by AndreyBelym** [comment]
Hi @Lupiano! The fix is released in `testcafe@0.22.0`, you can install it with `npm i testcafe@latest` and try it on your machine.

**Comment by Lupiano** [comment]
Great @AndreyBelym ! Thank you very much!
