### ISSUE TITLE
${BROWSER} resolves to undefined in screenshot pattern

### ISSUE THREAD

**Issue by cullophid** [DevExpress/testcafe#2742]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?
when using ${BROWSER} in screenshot pattern it resolves to undefined

### What is the expected behavior?
should resolve to the browser name

### How would you reproduce the current behavior (if this is a bug)?
use any pattern with ${BROWSER}

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Windows 10
* testcafe version: 0.21.0
* node.js version: 0.8.3

**Comment by miherlosev** [comment]
I'm working on it.

**Comment by AndreyBelym** [comment]
Hi @cullophid! The fix is released in `testcafe@0.22.0`, you can install it with `npm i testcafe@latest` and try it on your machine.
