### ISSUE TITLE
Running all the test on existing browser instance

### ISSUE THREAD

**Issue by stavalfi** [DevExpress/testcafe#2748]
### Are you requesting a feature or reporting a bug?

Feature

### What is the current behavior?
Every test is running on a new browser instance.

### What is the expected behavior?

Have the possibility to execute the test on an existing browser (already opened browser before the test started).

### Why

In the company I work for, we want to access cookies (from `TestCafe` tests) which are accessible only from a browser (`IE`) that is ensured to be open before we execute the tests. 
We have an old app written in `C#` and running on the `IE` using `XBAP` and it manually creates cookies which are accessible only from the same browser instance.

If my request is not doable or rejected for some reason, could you please give me an alternative?

**Comment by AndreyBelym** [comment]
Hi @stavalfi, you can connect this browser as a remote: [Remote Browsers](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#remote-browsers)

**Comment by AndreyBelym** [comment]
And optionally use [TestCafe Live](https://github.com/DevExpress/testcafe-live) to keep the browser connected between different test sessions.

**Comment by stavalfi** [comment]
Thanks, @AndreyBelym.

I'm using https://github.com/rquellh/testcafe-cucumber which runs `TestCafe` from within the code and not from the command line. Does it mean that I can't use `remote browsers` (as you suggested)?

**Comment by helen-dikareva** [comment]
Sorry for the very late response.
Take a look at the TestCafe [Programming Interface](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/). You can use [a remote browser connection](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#passing-a-remote-browser-connection) but you should patch the `testcafe-cucubmer` plugin. Please refer to the [`runTest` method](https://github.com/rquellh/testcafe-cucumber/blob/master/features/support/hooks.js#L33); here you should pass the `remoteConnection` as a argument for the `runner.browsers()` method.
