### ISSUE TITLE
Can't find screen size using JQuery

### ISSUE THREAD

**Issue by darkraincloud** [DevExpress/testcafe#2756]
### Are you requesting a feature or reporting a bug?

Bug, I guess. I'm really just looking for a workaround. There's probably something I don't understand.

### What is the current behavior?

When I try to run a test, I get:

> ERROR Cannot prepare tests due to an error.
> 
> TypeError: Cannot read property 'document' of undefined
>   at document (...path to...\jquery-1.11.0.min.js:2:90)
>   at Object.<anonymous> (...path to...\jquery-1-11.0.min.js:2:2)
>   at Object.<anonymous> (...path to...\screen_size.js:1:1)
>   at Object.<anonymous> (...path to...\test_screen_size.js:2:1)
> 

### What is the expected behavior?

I would expect there to be some way to fool either my code or TestCafe into reporting a screen size without giving the error.

### How would you reproduce the current behavior (if this is a bug)?

I run

`testcafe chrome test_screen_size.js`

#### Provide the test code and the tested page URL (if applicable)

screen_size.js:
```
import * as $ from "../src/lib/jquery/jquery-1.11.0.min.js";

export function getScreenSize() {
   return {
      width: $(window).width(),
      height: $(window).height()
   };
}
```

test_screen_size.js:
```
import { Selector } from 'testcafe';
import { getScreenSize } from './screen_size.js';

fixture `Test Screen Size`
    .page `http://devexpress.github.io/testcafe/example`;

test('Test screen size', async t => {
    await t
        .typeText('#developer-name', 'John Smith')
        .click('#submit-button');

    const articleHeader = await Selector('.result-content').find('h1');

    // Obtain the text of the article header
    let headerText = await articleHeader.innerText;
});

```

Tested page URL: I have http://devexpress.github.io/testcafe/example, but it doesn't matter. The test never gets that far.

### Specify your

* operating system: Windows 10 Enterprise
* testcafe version: 0.21.1
* node.js version: v8.11.3

**Comment by MarinaRukavitsyna** [comment]
Hello @darkraincloud 
According to the [jQuery npm](https://www.npmjs.com/package/jquery) documentation, a window with a document is required for jQuery to work in Node. Since no such window exists natively in Node, one can be mocked by tools such as [jsdom](https://github.com/jsdom/jsdom). Did you install it?

**Comment by MarinaRukavitsyna** [comment]
P.S. TestCafe runs tests on the server. So, it is impossible to output the result of the server-side code execution on the client side. If you wish  to interact with a browser, please use [ClientFunction](https://devexpress.github.io/testcafe/documentation/test-api/obtaining-data-from-the-client/#creating-client-functions).

**Comment by miherlosev** [comment]
At present, you cannot include additional scripts during your test run. There is an issue for this - https://github.com/DevExpress/testcafe/issues/1739.

If your page included the JQuery library then use this code snippet:

**test.js**
```js
import { Selector } from 'testcafe';
import { getScreenSize } from './screen_size.js';

fixture `Test Screen Size`
    .page `http://devexpress.github.io/testcafe/example`;

test('Test screen size', async t => {
	console.log(await getScreenSize());
	
    await t
        .typeText('#developer-name', 'John Smith')
        .click('#submit-button');

    const articleHeader = await Selector('.result-content').find('h1');

    // Obtain the text of the article header
    let headerText = await articleHeader.innerText;
});
```

**screen_size.js**
```js
import { ClientFunction } from 'testcafe';

export async function getScreenSize() {
	const fn = ClientFunction(() => {
		return {
			width: $(window).width(),
			height: $(window).height()
		};
	});
	
	return fn();
}
```
