### ISSUE TITLE
Testcafe can't establish connection with browser when running in CI

### ISSUE THREAD

**Issue by davidarce** [DevExpress/testcafe#2757]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

The test running can't connect to browser when executed in node (dockerized with chrome installed from apt, extended from ¡ node:8.11.1 ).

`ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.`

### What is the expected behavior?

Test expected to be functional same as locally 

### How would you reproduce the current behavior (if this is a bug)?

By running test suite in bash docker container.

### Specify your

* operating system: Debian
* testcafe version: 0.21.1
* node.js version: 8.11.1

# This is my DockerFile configuration

`FROM node:8.11.1 as base
WORKDIR /opt/app

USER root

RUN apt-get update -y && \
    apt-get install -y \
    libseccomp2 python-openssl \
    gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 \ 
    libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 \ 
    libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 \ 
    libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libappindicator3-1 libnss3 lsb-release xdg-utils wget && \
    rm -rf /var/lib/apt/lists/*

RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    dpkg -i google-chrome*.deb

FROM base as build
ARG ENV=$ENV
COPY ./ ./
RUN npm install
RUN npm run build

FROM base
ARG ENV=$ENV
COPY .npmrc package*.json yarn.* newrelic.js process.yml start.sh ./
COPY --from=build /opt/app/build ./build
RUN chmod -R ugo+rw /opt/app
RUN chmod +x start.sh
RUN npm install -g pm2@2.10.4
RUN npm install -g testcafe
RUN npm install --production
EXPOSE 5000
ENTRYPOINT ["./start.sh"]`

**Comment by davidarce** [comment]
I'll try with the flag "--no-sandbox" like chromium but not working

**Comment by davidarce** [comment]
HI @AndreyBelym i have a js for exec my test with child process "exec"

`testcafe path:/path/to/my/sh ./mytest.js`
 
and my .sh like:

`#!/bin/sh
Xvfb :19 -screen 0 "1024x768x16" >/dev/null 2>&1 &
export DISPLAY=:19
firefox`

and throw... ERROR Unable to establish one or more of the specified, i changed my docker file:

`FROM alpine:edge

WORKDIR /opt/app
ARG ENV=$ENV

RUN apk --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ add \
 python make g++ nodejs nodejs-npm chromium firefox xwininfo xvfb dbus eudev ttf-freefont fluxbox bash`

thanks for your answer

**Comment by melwynjensen** [comment]
Hi @davidarce 

Was this issue fixed and closed? If so can you please let me know what was done to fix it?

**Comment by davidarce** [comment]
Hi @melwynjensen 

Yes, it was fixed, the solution was in the start.sh, this is my start.sh

`dbus-daemon --session --fork
    Xvfb :1 -screen 0 "1280x720x24" >/dev/null 2>&1 &
    export DISPLAY=:1.0
    fluxbox >/dev/null 2>&1 &
    exec testcafe "$@"
`

**Comment by melwynjensen** [comment]
Hi @davidarce 

Thanks. But in my case am using headless chromium and firefox but get the same error which you have mentioned not really sure how to fix that.

**Comment by avozicov** [comment]
Hi everyone, 
I am facing the same issue when trying to run my tests in Jenkins CI using `firefox` browser.

Here is the log from Jenkins job:

```
Switched to a new branch 'dev'
Branch dev set up to track remote branch dev from origin.
e2e@1.0.0 /mnt/data/jenkins/jobs/e2e-tests/workspace/tests
├── chance@1.0.18 
└── testcafe@1.0.1 

npm WARN e2e@1.0.0 No description
npm WARN e2e@1.0.0 No repository field.
Using locally installed version of TestCafe.
ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.

Type "testcafe -h" for help.
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by avozicov** [comment]
UPDATE ^^
Sorry for spam here ;)
Just found the older answer for this issue from @AndreyBelym  and it solved the error.
Hope this helps:
https://github.com/DevExpress/testcafe/issues/1133#issuecomment-353849065
