### ISSUE TITLE
Can't set cookies in request, although in the code they are set successfully.

### ISSUE THREAD

**Issue by Aniku2009** [DevExpress/testcafe#2758]
### Are you requesting a feature or reporting a bug?

Feature

### What is the current behavior?
Hi. We use cookies for authentication. According logs, I see that cookies have been set successfully, but in IE Developer tool, requests have no cookies at all and I get Error 401 (Unauthorized). When I send request manually (not using TestCafe), authentication is successfully, get cookies in DevTool. 

### What is the expected behavior?
I expect to see request with cookies in IE DevTool

#### Provide the test code and the tested page URL (if applicable)
 const setCookie = ClientFunction(() => {
        document.cookie = "App=1_a6281148-e57f-4d2d-9495-cedc9ec43d8f; path=/"
    }).with({boundTestRun: testController});
    const getCookie = ClientFunction(() => {
        return document.cookie;
    }).with({boundTestRun: testController});
    await setCookie()
    console.log('Lets see cookies----------')
    console.log(await getCookie());
    await testController.navigateTo(url)
      .maximizeWindow();

Result of the running in console:

 Running tests in:
 - IE 11.0.0 / Windows 10.0.0

 fixture
.Lets see cookies----------
App=1_a6281148-e57f-4d2d-9495-cedc9ec43d8f
.F--------------------..

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Win 10
* testcafe version: 0.20.5
* node.js version:8.9.4

**Comment by AndreyBelym** [comment]
Hi @Aniku2009, if your login page performs authentication request while it is loading, you can't set cookies in a test body or hooks, because they are executed after the page loading is finished. Try to set cookies in a [Role](https://devexpress.github.io/testcafe/documentation/test-api/authentication/user-roles.html), and then use it in your tests.

**Comment by Aniku2009** [comment]
Thank you, Andrey, for the answer.
 I did this but result is the same :(

  const pmUserRole = Role(url, async t => {
        await t
        const setCookie = ClientFunction(() => {
            document.cookie = "OApp=1_f6b4ec8b-84b8-4804-9fc5-2a746f4a3c3f"
        }).with({boundTestRun: testController});
        const getCookie = ClientFunction(() => {
            return document.cookie;
        }).with({boundTestRun: testController});
        await setCookie()
        console.log('Lets see cookies----------')
        console.log(await getCookie());
    });
  
   await testController.useRole(pmUserRole)
           .maximizeWindow();

**Comment by AndreyBelym** [comment]
Try to log the `cookie` header on your server. You can't see the `cookie` request header in DevTools, because request shown in DevTools aren't processed directly by your server, but go to the `testcafe-hammerhead` proxy server, which stores cookies independently and sends them to your server.

I'm afraid I can't help you much without access to your server and full test suite code. Simplified basic scenario works fine on my machine:
###### server.js
```js
const http = require('http');


const COOKIE = 'blabla=foobar';

const render = ({ authorized } = {}) => `
<!DOCTYPE html>
<html>
    <head><title>Test</title></head>
    <body>
        <h2>${authorized ? 'Authorized' : 'Not authorized'}</h2>
        <div id="cookies"></div>
        <button id="addCookie">Add Cookie</button>
        <button id="removeCookie">Remove Cookie</button>        
        <script>
            cookies.innerText = document.cookie;

            addCookie.addEventListener('click', function () {
                document.cookie = '${COOKIE}';
                
                location.reload();
            });

            removeCookie.addEventListener('click', function () {
                document.cookie = '${COOKIE};expires=' + (new Date(0)).toUTCString();

                location.reload();                
            });
        </script>
    </body>
</html>
`;


const server = http.createServer((req, res) => {
    console.log(req.headers.cookie)
    const hasCookie = req.headers.cookie && req.headers.cookie.includes(COOKIE);

    res.writeHead(200);
    res.end(render({ authorized: hasCookie }));
});

server.listen(7777);
```

###### test,js
```js
import { Selector, ClientFunction, Role } from 'testcafe';

const setCookie = ClientFunction(() => {
    document.cookie = "blabla=foobar"
});

const getCookie = ClientFunction(() => {
    return document.cookie;
});

const pmUserRole = Role('localhost:7777', async t => {
    await setCookie.with({ boundTestRun: t })();

    await t.debug();
    console.log('Lets see cookies----------')
    console.log(await getCookie.with({ boundTestRun: t })());
});

fixture `cookies`
    .page`localhost:7777`
    .beforeEach(t => t.useRole(pmUserRole))

test
    (`cookie`, async t => {
        await t.expect(Selector('h2').textContent).match(/^Authorized/).wait(100000);    
    })
```

**Comment by Aniku2009** [comment]
Thank you Andrey for support. 
Unfortunately, we could not solve the issue and applied workaround to disable authentication on server.
Good luck.
