### ISSUE TITLE
How To use Programming Interface Runner Class inside Docker container (node modules)

### ISSUE THREAD

**Issue by davidarce** [DevExpress/testcafe#2761]
### Are you requesting a feature or reporting a bug?

Bug, I guess. I'm really just looking for a solution. There's probably something I don't understand.

### What is the current behavior?

I have a implementation of Programming interface with a Runner class of Testcafe. So I want to run the test cases inside node module in a docker container

### What is the expected behavior?

Run test inside a docker container in a node module

### Specify your

* operating system: Docker image alpine:edge
* testcafe version: lastest 
* node.js version: 8.11.1

**Comment by AndreyBelym** [comment]
Hi @davidarce! You need to mount the directory with your script and override container's entrypoint.

E.g. if you use the following command to start TestCafe:
```
docker run -v ${pwd}:/e2e -it testcafe/testcafe "firefox" /e2e/**/*-spec.js
```
and your runner code is in the `${pwd}/runner.js` file, you can start using the following command:
```
docker run -v ${pwd}:/e2e -it --entrypoint node testcafe/testcafe /e2e/runner.js
```

But please note, that you will have to perform environment initialization steps from the [TestCafe Docker script](https://github.com/DevExpress/testcafe/blob/master/docker/testcafe-docker.sh) in your runner.

**Comment by AndreyBelym** [comment]
Or you can create your own base image based on [our Dockerfile](https://github.com/DevExpress/testcafe/blob/master/docker/Dockerfile) and replace [TestCafe installation step](https://github.com/DevExpress/testcafe/blob/master/docker/Dockerfile#L8) with a step installing your module.
