### ISSUE TITLE
Docs say node requirement is 4.0 but install requires 6.0.0

### ISSUE THREAD

**Issue by samanthablasbalg** [DevExpress/testcafe#2766]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
My app currently uses an old version of Node (5.6) and I was happy to see that the docs in the repo say that Testcafe works with Node 4.0. However, when I installed Testcafe, it threw errors because of javascript syntax that it couldn't handle. I scrolled back up through the install logs and at the top there was an error saying that Testcafe requires Node 6.0.0.

### What is the expected behavior?
The docs should be updated to reflect the new requirements.

### How would you reproduce the current behavior (if this is a bug)?
Try to install Testcafe with a Node version below 6.0.0.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code
```
js
```

### Specify your

* operating system: Mac OS High Sierra 10.13.6
* testcafe version: 0.21.1
* node.js version: 5.6

**Comment by AndreyBelym** [comment]
@samanthablasbalg, thanks for pointing this out! I will fix the version in Readme. You can try to install `testcafe@v0.19.2` if you really need to run tests on Node.js < 6.0.0.

**Comment by AndreyBelym** [comment]
Closed by #2767
