### ISSUE TITLE
Need the publish task for docs

### ISSUE THREAD

**Issue by VasilyStrelyaev** [DevExpress/testcafe#277]
Use `gulp-gh-pages` for that. Prompt before publishing.
Do when the docs are ready and it's safe to try it (there is an option for dry run in `gulp-gh-pages` - but do you trust it?).

**Comment by VasilyStrelyaev** [comment]
And, yeah, consider using  https://github.com/SBoudrias/Inquirer.js/ for prompting

**Comment by VasilyStrelyaev** [comment]
Unfortunately, GitHub Pages engine disables all custom Jekyll plugins for safety reasons.
So, if we want to go with automatic anchor links (which I'm going to implement via a plugin), we need to build the website locally and then push it to gh-pages instead of pushing Jekyll sources

**Comment by inikulin** [comment]
> build the website locally 

We have task for this already, so it's not a big problem I think

**Comment by VasilyStrelyaev** [comment]
yep, I just post this as a reminder

**Comment by VasilyStrelyaev** [comment]
Before building the website, this task should check that the local Jekyll is > 3.0
(we happen to use extensionless permalinks)
