### ISSUE TITLE
Gauge Integration with Testcafe

### ISSUE THREAD

**Issue by edimistra** [DevExpress/testcafe#2788]
### Are you requesting a feature or reporting a bug?
A feature

### What is the current behavior?
Gauge is a test automation framework that focus on user acceptance testing. 
https://www.gauge.org

Tests are written based on concepts, scenarios and steps using markdown’s syntax. Steps tests are then written on several programming languages including javascript.  Gauge can interact with several testing frameworks including Selenium but so far there’s no way to make it work with Testcafe

### What is the expected behavior?
Writing high level tests with Gauge and implementing steps with Testcafe

**Comment by edimistra** [comment]
Thanks @churkin for pointing me to the Cucumber solution. I'll take a deeper look into it, so far my firsts impressions are that this Cucumber integration will fit our needs (writing tests before coding even starts)

**Comment by edimistra** [comment]
@zabil This is amazing! Thank you very much for your contribution!

**Comment by churkin** [comment]
Good work, @zabil! We will recommend your example to our users who are interested in `Gauge `.
 
@edimistra I hope @zabil's example will help you get started with `TestCafe` and `Gauge`.
