### ISSUE TITLE
URL not running in remote browser in the network

### ISSUE THREAD

**Issue by dineshpaduchuri** [DevExpress/testcafe#2795]
### What is the current behavior?

I am getting url to run when i run testcafe remote test.ts -e but when i run the URL in browser in remote machine in the network i get Page Cannot be displayed error. but when i run the same url in my local machine browser it is running

Do i need to establish any connection to the remote server in my test.ts file?  W
Please help me in running the browser remotely. Below is my code

import { Selector, t } from "testcafe"
import { ProblemsLevel2Page }from '../../pages/problems_level2.page'
import { CommonPageBusiness } from '../../business/common_page.business'
import { environment_variables } from '../../Property/properties';

var problemsl2 : ProblemsLevel2Page;
var common_page :  CommonPageBusiness;
const mockurl = environment_variables.mockUrl;

fixture`Verify Problems Level2 details`.beforeEach(async (t: TestController) => {
 problemsl2 = new ProblemsLevel2Page(t);
 common_page = new CommonPageBusiness(t);

}).page(mockurl);

test(`Login to Patient View with valid credentials`,  async t => {
    
    await t.click(problemsl2.expandpv1);
    await t.click(problemsl2.problempv1);
     await t.wait(10000);

})

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by AndreyBelym** [comment]
Hi @dineshpaduchuri! Please specify your TestCafe, OS and Node.js versions. Likely you have to configure firewall on your machine to allow connections from your network.

**Comment by dineshpaduchuri** [comment]
TestCafe : 0.20.4
OS : Windows 10 64 bit
Ndoe.js : 8.11.2

How to configure firewall on my machine to allow connections. Any blog?

**Comment by AndreyBelym** [comment]
There is an article about configuring the Windows Firewall: https://www.online-tech-tips.com/windows-10/adjust-windows-10-firewall-settings/

Please note, if you use additional Anti-Virus software, it may come with its own firewall, and you'll need to configure it as well.

**Comment by dineshpaduchuri** [comment]
There were two inbound rules in firewall settings which blocked node.js hence my url is not running remotely.
I disabled those rules and later url is running remotely
Thanks!
