### ISSUE TITLE
Error SkipJSerror dont works when I use tester schedule with cron

### ISSUE THREAD

**Issue by dmjesus89** [DevExpress/testcafe#2797]
### Are you requesting a feature or reporting a bug?
reporting a bug

### What is the current behavior?
            skipJsErrors: true not works

### What is the expected behavior?
            skipJsErrors: true to works in my tests

### How would you reproduce the current behavior (if this is a bug)?
When I start my test for my server in 1338 he works,
But if I use cron time he dont recognizes skipJsErrors in my options runtime

#### Provide the test code and the tested page URL (if applicable)
@fixture prod_verifiy_GE";
"@page https://www.google.com.br";

Tested page URL:
https://www.google.com.br

Test code

```js

function runTests() {
	console.log('running 50');
	var runOptions = {
		skipJsErrors: true,
        selectorTimeout: 50000,
        assertionTimeout: 7000,
        debugMode: true,
        speed: 0.1,
		workers: testCafe.listConnectedWorkers(), // Return an array of strings identifying the connected remote workers
		browsers: testCafe.listAvailableBrowsers(), // Return an array of strings identifying available browsers
		emulateCursor: true // Emulate cursor movements while testing
	};

```

### Specify your

* operating system: mac os
* testcafe version: 15.1.317522
* node.js version: v10.6.0

**Comment by dmjesus89** [comment]
I resolved, 
I need put failOnJsErrors and remove skipJsErrors

**Comment by AndreyBelym** [comment]
Hi @dmjesus89, looks like you use the Legacy TestCafe (`v15.x`). In this version you should use the `failOnJSError` options to disable uncaught JS exception handling, see the [docs](https://testcafe.devexpress.com/Documentation/API_Reference/Continuous_Integration_API/TestCafe_Methods/#runTests). 

I highly recommend you to use more modern TestCafe Open Source version, that has improved API and has better integrations with CLI and CI systems. In the new version, you should use the `skipJsErrors` option.

**Comment by dmjesus89** [comment]
I did not know I was using a legacy version.
How do I use the latest version?
First I used "npm install testcafe -g" and I installed test cafe 0.21.1
after that I used "npm install testcafe@15.1.x" and installed testcafe 15.1.372552
remembering that I need to upload server 1337 and 1338

**Comment by AndreyBelym** [comment]
The latest version is `0.21.1`. If you don't sure which version could be installed by NPM, use the `latest` tag:
```
npm install testcafe@latest -g
```

**Comment by dmjesus89** [comment]
@AndreyBelym  thank you for your help

**Comment by dmjesus89** [comment]
@AndreyBelym  I try use 0.21.1 but dont have version interface in 1337 and 1338 with Control Panel

**Comment by AndreyBelym** [comment]
Sorry, I didn't understand you before, if you need graphical interface you have to stick with TestCafe Legacy. 

Please note, that the Legacy package in NPM is meant to be used in Continuous Integration systems, it's not intended to be used with Control Panel and it's missing  visual recorder.  If you need Control Panel, you should download TestCafe from https://testcafe.devexpress.com.

Also you can try or TestCafe Studio Beta - https://testcafe-studio.devexpress.com/, the new app for running and recording tests, based on TestCafe Open Source and thus having all latest features and improvements.
