### ISSUE TITLE
File Upload - Click on dropzone selector doesn't open finder window

### ISSUE THREAD

**Issue by benjamin33** [DevExpress/testcafe#2798]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

Finder window won't open
```javascript
        await t.click('.dropzone')
```

*Note:*
Calling `click` method directly from browser console works:
```javascript
document.querySelector('.dropzone').click()
```

### What is the expected behavior?

Calling `click` method on ".dropzone" should open Finder window

```js

```

### Specify your
Please see attached code 

import {Selector} from 'testcafe';

fixture`New Fixture`.page`http://kavanamusic.com/admin/`;

test('New Test', async t => {
    await t
        .maximizeWindow()
        .typeText(Selector('#email'), 'test@test.com')
        .typeText(Selector('#password'), '123456')
        .click(Selector('span').withText('Login'))
        .click(Selector('.menu-item.ng-star-inserted').nth(3).find('span').withText('Artists'))
        .click(Selector('#mat-checkbox-3').find('[class^="mat-checkbox-inner-container mat-checkbox-inner-co"]'))
        .click(Selector('[name="edit"].icon-edit').find('svg').find('use'))
        .click(Selector('span').withText('New Album'))
        .typeText(Selector('#album-name'), '11')
        .typeText(Selector('#album-popularity'), '11')
        .typeText(Selector('#album-release-date'), '11')
        .click(Selector('span').withText('New Track'))
        .typeText(Selector('#track-name'), '11')
        .typeText(Selector('#track-artists'), '11')
        .click(Selector('span').withText('Upload'))
        .click(Selector('.dropzone'))
        .wait(10000);
});

* operating system: macOs High Sierra 
* testcafe version: 0.21.1
* node.js version: 10.7.0

**Comment by AndreyBelym** [comment]
Hi @benjamin33, all native dialog windows are suppressed by TestCafe, because TestCafe can't control them through its HTML5 automation engine. If you need to upload a file, please try to call the [t.setFilesToUpload](https://devexpress.github.io/testcafe/documentation/test-api/actions/upload.html#populate-file-upload-input) for the file input, and then submit the corresponding form.

**Comment by benjamin33** [comment]
I'm also tried that but didn't success

test('New Test', async t => {
    await t
        .maximizeWindow()
        .typeText(Selector('#email'), 'test@test.com')
        .typeText(Selector('#password'), '123456')
        .click(Selector('span').withText('Login'))
        .click(Selector('.menu-item.ng-star-inserted').nth(3).find('span').withText('Artists'))
        .click(Selector('#mat-checkbox-3').find('[class^="mat-checkbox-inner-container mat-checkbox-inner-co"]'))
        .click(Selector('[name="edit"].icon-edit').find('svg').find('use'))
        .click(Selector('span').withText('New Album'))
        .typeText(Selector('#album-name'), '11')
        .typeText(Selector('#album-popularity'), '11')
        .typeText(Selector('#album-release-date'), '11')
        .click(Selector('span').withText('New Track'))
        .typeText(Selector('#track-name'), '11')
        .typeText(Selector('#track-artists'), '11')
        .click(Selector('span').withText('Upload'))
        .setFilesToUpload('.dropzone', ['./Users/benjamin/Downloads/Radio/upload/0010-302-2.mp3'])
        // .click('.dropzone')
        .wait(10000);
});

**Comment by AndreyBelym** [comment]
Could you please share the HTML code of your page?

**Comment by benjamin33** [comment]
Sure please rename to .html
[htmlOfKavanaMusic.txt](https://github.com/DevExpress/testcafe/files/2345463/htmlOfKavanaMusic.txt)
Thanks a lot

**Comment by AndreyBelym** [comment]
In your case a hidden file input appears after clicking on the `.dropzone` element, check the following test:
```js
import {Selector} from 'testcafe';

fixture`New Fixture`.page`http://kavanamusic.com/admin/`;

test('New Test', async t => {
await t
.maximizeWindow()
.typeText(Selector('#email'), 'test@test.com')
.typeText(Selector('#password'), '123456')
.click(Selector('span').withText('Login'))
.click(Selector('.menu-item.ng-star-inserted').nth(3).find('span').withText('Artists'))
.click(Selector('#mat-checkbox-3').find('[class^="mat-checkbox-inner-container mat-checkbox-inner-co"]'))
.click(Selector('[name="edit"].icon-edit').find('svg').find('use'))
.click(Selector('span').withText('New Album'))
.typeText(Selector('#album-name'), '11')
.typeText(Selector('#album-popularity'), '11')
.typeText(Selector('#album-release-date'), '11')
.click(Selector('span').withText('New Track'))
.typeText(Selector('#track-name'), '11')
.typeText(Selector('#track-artists'), '11')
.click(Selector('span').withText('Upload'))
.click(Selector('.dropzone'))
.setFilesToUpload('#hidden-file-upload-input', 'Example.ogg.mp3')
.wait(10000)
});

``

**Comment by benjamin33** [comment]
Yep !!! Thank you @AndreyBelym for you time and help !!!
