### ISSUE TITLE
How to find nth div label and span value when there are multiple div

### ISSUE THREAD

**Issue by dineshpaduchuri** [DevExpress/testcafe#2801]
### What is the current behavior?
There are multiple indexes for one of the div with Class = "d-flex flex-wrap pt-3". 
parent Div  Class = "d-flex flex-wrap pt-3"
and child Div Class = "pt-2 mb-4 mr-4 wrapper-box"
and grandchild Div Class = "wrapper-content"
i need label and span tag values for each child Div class

And i need to find each 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
![image](https://user-images.githubusercontent.com/42802100/44980867-aac42c00-af8e-11e8-9484-902654283cc1.png)

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by AndreyBelym** [comment]
Hi @dineshpaduchuri, you can use the [nth](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/functional-style-selectors.html#nth) method of the Selector class, or the [nth-child](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child) CSS Pseudoclass. 

E.g. if you have multiple `<div>`'s with the `d-flex` class on your page, and you need `<label>` and `<span>` descendants, you can use the following selectors:
```js
const label = Selector('.d-flex').find('label').nth(1);
const span  = Selector('.d-flex').find('span').nth(1);
```
or
```js
const label = Selector('.d-flex:nth-child(1)').find('label');
const span  = Selector('.d-flex:nth-child(1)').find('span');
```

**Comment by dineshpaduchuri** [comment]
Thanks!
But when there are multiple Wrapper boxes like below and need to access each Label and Span 
![image](https://user-images.githubusercontent.com/42802100/44985965-e4516300-af9f-11e8-89a0-31e24c580365.png)

**Comment by AndreyBelym** [comment]
In this case you can keep the Selectors using the `nth` method, and use different class for Selectors using the CSS Pseudoclass:
```js
const label = Selector('.wrapper-box:nth-child(1)').find('label');
const span  = Selector('.wrapper-box:nth-child(1)').find('span');
```

Of course, you can change the class in Selectors using the `nth` method too.
