### ISSUE TITLE
Feature: Allow to "hold mouse for X time" before dragging

### ISSUE THREAD

**Issue by Worie** [DevExpress/testcafe#2803]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
You cannot set the amount of time an element has to be "hold" in order to drag it. (no option for doing `hold mouse on element -> then drag`

### What is the expected behavior?
You can optionally pass a variable that'll represent amount of time which will "mousedown" the source element before starting drag action

### How would you reproduce the current behavior (if this is a bug)?
N/A

#### Provide the test code and the tested page URL (if applicable)
N/A

### Specify your

* operating system: Mac OS 10.12.6
* testcafe version: 0.20.1
* node.js version: 8.10

Surely, if there's any kind of workaround I'd really appriciate giving me a tip, however I guess this should be customizable for this particular action.

Thanks in advance!

**Comment by AndreyBelym** [comment]
Hi @Worie, thanks for the proposal, I'll post a possible workaround and post it if I get one.

**Comment by link89** [comment]
Hi @AndreyBelym , is there any workaround for this?

**Comment by svego** [comment]
As requested for issue #4165 an example for my use case:
```javascript
import { Selector } from "testcafe";

fixture('draggable').page('https://jsbin.com/zosiwah');


test('Drag example #4165', async t => {
    var fooSelector = Selector('.list-group-item').nth(0);
    var bazSelector = Selector('.list-group-item').nth(2);
    await t.expect(fooSelector.exists).ok()
        .expect(bazSelector.exists).ok()
        .dragToElement(fooSelector, bazSelector, { speed: 0.01 })
        .expect(Selector('.list-group-item').nth(0).innerText).eql('baz');
        
    }
)
```
In this example on jsbin it is required to hold the mouse for 400ms before dragging is enabled. In our project we use similar functionality.

A workaround as proposed in this issue would also be acceptable.

**Comment by AndreyBelym** [comment]
@Worie I apologize for the delay in providing a workaround, but thanks to @svego I got a page for tests and found a way to enable such functionality.

@Worie @svego You can use `ClientFunction` to patch TestCafe internal functions and add a delay after TestCafe simulates mouse down events on an element. But I should warn you that the workaround code is a hack and some future TestCafe update can break it without a notice.
```js
import { Selector, ClientFunction } from "testcafe";

fixture('draggable').page('https://jsbin.com/zosiwah');

// HACK: Define functions that monkey-patch TestCafe internals
const enableMouseDownDelay = ClientFunction(() => {
    const proto     = window['%testCafeAutomation%'].DragToElement.prototype.constructor.prototype
    const mousedown = proto._mousedown;

    proto._mousedown = function (...args) {
        let result;

        return mousedown
            .apply(this, args)
            .then(r => result = r)
            .then(() => new Promise(r => setTimeout(r, window.mouseDownDelay || 0)))
            .then(() => result);
    }
});

const setMouseDownDelay = ClientFunction(ms => window.mouseDownDelay = ms);
// End of function definitions

test('Drag example #4165', async t => {
    var fooSelector = Selector('.list-group-item').nth(0);
    var bazSelector = Selector('.list-group-item').nth(2);

    // HACK: Call patching functions to enable delays during a test

    // Can be called only once per test
    await enableMouseDownDelay();

    // Can be called multiple times per test
    await setMouseDownDelay(1000);

    await t.expect(fooSelector.exists).ok()
        .expect(bazSelector.exists).ok()
        .dragToElement(fooSelector, bazSelector, { speed: 0.01 })
        .expect(Selector('.list-group-item').nth(0).innerText).eql('bar');

    }
)
```
