### ISSUE TITLE
async-await / promise support for onRequest and onResponse hook methods.

### ISSUE THREAD

**Issue by rupeshmore** [DevExpress/testcafe#2816]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
When using the Hooks, req or response is sent before promise is resolved.

### What is the expected behavior?
Promise is resolved before the req, res is sent back.
I want to use async/await for `onRequest` and `onResponse`

### How would you reproduce the current behavior (if this is a bug)?
NA

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
NA
Test code

```js
import { RequestHook } from 'testcafe';

class JwtBearerAuthorization extends RequestHook {
    constructor () {
        super();
    }
}
    async onRequest (e) {
        const jwt = await getJWTPromise();
        e.requestOptions.headers['Authorization'] = `Basic ${jwt}`;
    }
   async  onResponse (e) {
        const newHeader = await somePromise();
        e.headers['some-headers'] = newHeader;
    }
}
```

### Specify your

* operating system: Windows 10
* testcafe version: 0.21.1
* node.js version: 8.11.2

**Comment by AndreyBelym** [comment]
Closed by https://github.com/DevExpress/testcafe/commit/d7c05de023f06811ea445ed4aaad75c1a9fc9630, shipped in `testcafe@1.0.0-alpha.2`.
