### ISSUE TITLE
Clicking on normal elements does not work

### ISSUE THREAD

**Issue by Neatoro** [DevExpress/testcafe#2817]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

The click does not work on elements which have a click listener that are not a default clickable element. This seems to happen only with a frontend framework. I used VueJS but did not check whether it does not work with React or Angular.

### What is the expected behavior?

The click event is triggered.

### How would you reproduce the current behavior (if this is a bug)?

I created two repositories. One with [VueJS](https://github.com/Neatoro/testcafe-issue) were it does not work and another with [plain HTML + JS](https://github.com/Neatoro/testcafe-issue-without-vue) where it actually works (same HTML and test).

### Specify your

* operating system: macOS High Sierra v10.13.6
* testcafe version: 0.22.0
* node.js version: v8.11.3

**Comment by AndreyBelym** [comment]
Hi @Neatoro, have you resolved the issue?

**Comment by Neatoro** [comment]
No Sorry I did a mistake while reproducing it. We still have an issue but not able to reproduce it in a different project by now. That is why I closed the issue, since I could not verify that the issue is not on our site.
