### ISSUE TITLE
Disable heartbeat when debugging is enabled

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#2819]
### Are you requesting a feature or reporting a bug?
Enhancement

### What is the current behavior?
Browser disconnects when you pause script in browser's DevTools or stay on a breakpoint in a server debugger for more than 30 seconds.

### What is the expected behavior?
Browser mustn't be disconnected when debugging client or server scripts

### Specify your

* operating system: any
* testcafe version: 0.22.0
* node.js version: any

**Comment by leopatras** [comment]
This is biting me too. Debugging with those restarts inbetween is hell.

**Comment by PavelMor25** [comment]
Hello everyone,

In the [latest release Testcafe](https://testcafe.io/404619/release-notes/framework/2023-11-10-testcafe-v3-4-0-released) does not relaunch unresponsive browsers if you enter development mode.
