### ISSUE TITLE
Setup greenkeeper.io for automatic PRs on `hammerhead` and `browser-natives` updates

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#282]
Use it for built-in reporter updates as well. 

See: http://greenkeeper.io/
How to disable it for some deps: https://github.com/greenkeeperio/greenkeeper/issues/47#issuecomment-146474309

We might need it for some other important deps (Babel I guess)

**Comment by AlexanderMoskovkin** [comment]
done
