### ISSUE TITLE
No way to get current testname using c.ctx or c.fixtureCtx?

### ISSUE THREAD

**Issue by jiteshsojitra** [DevExpress/testcafe#2823]
I'm sorry currently i don't find any easy way or no way to return current test name. I tried controller and some internal testcafe methods but no luck. Is there any way to get current testname using c.ctx or c.fixtureCtx or controller?

For e.g.
Testcase name - "Smoke | Login to client" for:
test("Smoke | Login to client", async t => {

I'm using latest versions of testcafe and node.

**Comment by AndreyBelym** [comment]
Hi @jiteshsojitra, currently test and fixture names aren't stored in `t.ctx` and `t.fixtureCtx`. I've created a new issue for this proposal: https://github.com/DevExpress/testcafe/issues/2826. As a workaround, you can wrap the `test` function in another function, and store test name as property of test's body function:
```
function defineTest(name, func) {
    func.testName = name;

    return test(name, func);
}
...
defineTest('test', funciton f () {
    console.log(f.testName);
})
```

**Comment by jiteshsojitra** [comment]
It requires to change all the tests to include function which is not good. Any better way without changing much?

**Comment by AndreyBelym** [comment]
Unfortunately there is no other way yet.
