### ISSUE TITLE
Click on play button in HTML5 video player raising DOMException

### ISSUE THREAD

**Issue by samuelsh** [DevExpress/testcafe#2829]
### Are you requesting a feature or reporting a bug?
bug

### What is the current behavior?

Test attempting to start Video playback by clicking on [play] button in HTML5 Video player control bar.
But failing on DOMException:
> timeCodeUpdateByPlay
> 
>    1) Error on page "https://kabbalahmedia.info/en/lessons/cu/koUvHS4T?language=en":
> 
>       [object DOMException]
> 
>       Browser: Chrome 68.0.3440 / Mac OS X 10.13.6
> 
>          42 |});
>          43 |
>          44 |test('timeCodeUpdateByPlay', async t => {
>          45 |
>          46 |    await player_utils.waitForPlayerToLoad();
>        \> 47 |    await t.click('i.play.icon');
>          48 |    await t.wait(5000);
>          49 |    await t
>          50 |           .expect(await player_utils.getPlayerCurrentTime()).gt(0);
>          51 |});
>          52 |
> 
>          at Object.<anonymous> (/Users/samuelshapiro/WebstormProjects/archive_tests_jest/_testcafe_tests/player_spec.ts:47:13)
>          at fulfilled (/Users/samuelshapiro/WebstormProjects/archive_tests_jest/_testcafe_tests/player_spec.ts:7:58)
> 

### What is the expected behavior?
Click on [play] should start Video Playback

### How would you reproduce the current behavior (if this is a bug)?
Please run code from test posted below

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js
fixture`Video Player Test Suite`
    .page("https://kabbalahmedia.info/en/lessons/cu/TGfvHRww?language=en");

test('timeCodeUpdateByPlay', async t => {

    await player_utils.waitForPlayerToLoad();
    await t.click('i.play.icon');
    await t.wait(5000);
    await t
           .expect(await player_utils.getPlayerCurrentTime()).gt(0);
});
```

### Specify your

* operating system: MacOS HighSierra
* testcafe version: 0.21.1 
* node.js version: 9.8

**Comment by churkin** [comment]
Hi @samuelsh,
I've investigated this problem and see that in your case you get the "Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first." exception. It is a browser policy limitation. To disable it, use the `--autoplay-policy=no-user-gesture-required` Chrome browser flag:
 
`testcafe "chrome --autoplay-policy=no-user-gesture-required" test.js`

**Comment by samuelsh** [comment]
Great! 
Thanks @churkin 
How did you managed to get that exact error message, btw?
When I run this code on my machine I'm getting only "DOMException" message (as you can see from bt above), without any further explanation

**Comment by AndreyBelym** [comment]
@samuelsh, we have implemented printing stack trace of browser JS errors: https://github.com/DevExpress/testcafe/pull/2791, it will be available in the next release. I close the issue because it was resolved by specifying the additional Chrome flag.
