### ISSUE TITLE
Issue with multiple browser running. Tests are running on one browser only and instances are not closed

### ISSUE THREAD

**Issue by Aniku2009** [DevExpress/testcafe#2838]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
We are using TestCafe with Cucumber and pass parameters to cucumber using “world-parameters”.
My project consists from 3 feature files. 
When I run tests on IE or Chrome, all works fine.

Get issues when try to use concurrent running or use more than one browser.

**package.json**
"test-ie": "./node_modules/.bin/cucumber-js.cmd  --world-parameters \"{\\\"browser\\\": [\\\"ie\\\",\\\"chrome\\\"],\\\"url\\\": \\\"http://localhost:4200/#\\\"}\"",

**C:\Users\ddd\AppData\Roaming\npm\node_modules\testcafe\lib\utils\kill-browser-process.js**
var processOptions = { arguments: browserId, psargs: 'aux' };

With this configuration IE and Chrome instances  are starting, but actually I can see that tests execute in IE only.
Get 3 IE instances and 3 Chrome instances running. As I understand, one instance for one feature file.
Get message, that tests completed successfully, but IE instances did not close, Chrome instances are still  executing with status “CONNECTED” in the browser.

**Comand line:**
> cucumber-js.cmd  --world-parameters "{\"browser\": [\"ie\",\"chrome\"],\"url\": \"http://localhost:4200/#\"}"

 Running tests in:
 - IE 11.0.0 / Windows 10.0.0
 - Chrome 68.0.3440 / Windows 10.0.0

3 scenarios (3 passed)
56 steps (56 passed)
2m59.468s

Even after 10 min get the same state. When stop project manually, get message "Process finished with exit code 1"

### What is the expected behavior?
Tests should be run in in both browsers
I should get message in console: "Process finished with exit code 0"

### How would you reproduce the current behavior (if this is a bug)?

Please, see above

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:Win 10
* testcafe version:0.22.0(updated today)
* node.js version:8.9.4

**Comment by AndreyBelym** [comment]
Hi @Aniku2009, `cucumber-js` doesn't support running tests in multiple browsers: https://stackoverflow.com/a/43386755/5114901

**Comment by bhreinb** [comment]
Hello @Aniku2009 

This may be of interest to you. I use this package to run tests in parallel via cucumber (with some limitations)

https://www.npmjs.com/package/cuke-skywalker

Hope this helps.
