### ISSUE TITLE
Is possible running testcafe out node server? I cant use node in my company

### ISSUE THREAD

**Issue by dmjesus89** [DevExpress/testcafe#2839]
### Are you requesting a feature or reporting a bug?
requesting a feature

### What is the current behavior?

N/A

### What is the expected behavior?
Running another server

### How would you reproduce the current behavior (if this is a bug)?
N/A

#### Provide the test code and the tested page URL (if applicable)
createTestCafe('localhost', 1337, 1338)
.then(tc => {
    testcafe     = tc;
    runner = testcafe.createRunner();
    console.log('chamou');

    return runner
        .src(['portal_do_segurado.js'])
        .browsers(['firefox'])
        .screenshots('./screenshots', true)
        .reporter('json')
       // .useProxy(proxyUrl)
        .run({
            skipJsErrors: true,  // Define se deve continuar executando um teste depois que um erro de JavaScript ocorrer em uma página (true) ou se considerar que tal teste falhou
            skipUncaughtErrors: true,// Booleano Define se um teste deve continuar depois que um erro não detectado ou uma rejeição de promessa não tratada ocorrer no servidor (true) ou considerar que um teste desse tipo falhou (false).
            quarantineMode: false,
            selectorTimeout: 500, // Especifica o tempo (em milissegundos) no qual os seletores tentam obter um nó a ser retornado.
            assertionTimeout: 7000, // Especifica o tempo (em milissegundos) dentro do qual o TestCafe tenta executar com êxito uma declaração se uma propriedade do seletor ou uma função do cliente foi passada como um valor real
            pageLoadTimeout: 2000, // Especifica o tempo (em milissegundos) passado após o evento DOMContentLoaded, dentro do qual o TestCafe aguarda o disparo do evento window.load. Depois que o tempo limite passar ou o evento window.load for gerado (o que ocorrer primeiro), o TestCafe iniciará o teste. Você pode definir esse tempo limite como 0 para pular a espera de window.load.
            debugMode: false,
            debugOnFail : true,
			speed: 1
        });
        
})
.then(failedCount => {
    console.log('Tests failed: ' + failedCount);
    console.log(error + "error no teste")
    testcafe.close();
   // process.exit(failedCount ? 1 : 0);
    
})
.catch(error => {
    console.log(error + "error no server")
    testcafe.close();
});

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Windows
* testcafe version: 0.22
* node.js version: 8.11.3

**Comment by churkin** [comment]
Hi @dmjesus89,
Would you please clarify what you mean by "I can't use node in my company". In the simplest case, a node is just a `node.exe` file and you can use it anywhere. So, please elaborate on the issue.

**Comment by dmjesus89** [comment]
Hi @churkin 
Thanks, To raise the testcafe I need to start a node server with the command node "file.js" in my company the node is not homologated to be used as server

**Comment by churkin** [comment]
Hi @dmjesus89,
Is it a technical restriction or it is related to the company policy?

**Comment by dmjesus89** [comment]
is related to the company policy

**Comment by dmjesus89** [comment]
@churkin it is related to the company policy

**Comment by miherlosev** [comment]
`TestCafe` is a node.js based application. It is not possible to use `TestCafe` without node.js.
