### ISSUE TITLE
Error: Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.

### ISSUE THREAD

**Issue by adrianaisemberg** [DevExpress/testcafe#2842]
TestCafe is unable to connect to the browser.
This started happening a week ago on some of our CI machines and seems like the issue is "spreading" to other CI machines as well.
Is there a known recent OS update that may start causing this? 

I tried:
Chrome, Chromium, FireFox, Safari (headless and non-headless, when supported),
With and without concurrency,
With `--no-sandbox` and without.
With the `testcafe` executable and with the testcafe library (via our code).
With our test-suite and without (a single empty js test).
All fail for the same reason.
 
macOS 10.13.6
Node v8.11.1
TestCafe v0.22.0

**Comment by adrianaisemberg** [comment]
When trying Safari I get this error:

`Error: Was unable to open the browser "locally-installed:safari" due to error.`
`Error: Unable to run the browser. The file at /Users/vsts/agent/2.140.0/work/1/s/ux/portal/node_modules/testcafe-browser-tools/bin/mac/open.scpt does not exist or is not executable.`

**Comment by AndreyBelym** [comment]
Hi @adrianaisemberg, could you please provide the error message which you get when starting Chrome and Firefox?

**Comment by adrianaisemberg** [comment]
As in the title:
`Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure`

**Comment by AndreyBelym** [comment]
I guess you start the tests using Azure Pipelines or TFS, Looks like the `vsts-agent` version that you use (`2.140.1`) was released 5 days ago. Could you try to rollback to the some previous agent version?

**Comment by adrianaisemberg** [comment]
@AndreyBelym I'm afraid I won't be able to do that.
What is the difference between running via the command-line versus the library?
Why does it work with one but fails with the other? (Only with Safari, otherwise they all fail)

**Comment by jossjacobo** [comment]
@AndreyBelym I think I am running into this issue as well and I am seeing different results depending on the vsts-agent that gets picked up from the pool. Would the only way to select the agent be to have an agent in the pool with a lower target and then pick that agent? Or is there a way to define that on my `vsts-ci.yaml` file? I've been googling for a couple of hours and their documentation is not clear to me, I'd appreciate the help.

Thanks,

**Comment by AndreyBelym** [comment]
Hi @adrianaisemberg, @jossjacobo! Unfortunately I'm not familiar with TFS infrastructure, so I need some days to setup environment and debug TestCafe under a VSTS agent. Looks like that TestCafe has no permissions to spawn processes in VSTS environment, so it can't start any browser. I don't think that there should be no difference between running TestCafe from CLI wrapper or from your own script as a library, but I can't be sure without testing it. The error message for Safari is different, because TestCafe uses AppleScript to start Safari, and other browsers are started from their binaries directly.

**Comment by AndreyBelym** [comment]
@adrianaisemberg, @jossjacobo could you please clarify, do you use Microsoft-hosted agents or your own machines? If the latter, do you start your agents [interactively](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-osx?view=vsts#run-interactively) or [as a service](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-osx?view=vsts#run-as-a-launchd-service)?

**Comment by chrisrpatterson** [comment]
Hello I am a Product Manager on the Azure Pipelines team.

@adrianaisemberg  and @jossjacobo We have typically seen this be an issue on mac when not running as a LaunchAgent or running interactively.  The agent update process simply replaces the binaries on disk and should not impact any configured permissions as far as launching processes is concerned.  However, if there is something we can do to help out please let me know.

**Comment by adrianaisemberg** [comment]
We eventually switched to running on Linux.
