### ISSUE TITLE
Allow concurrent execution of fixtures

### ISSUE THREAD

**Issue by jarekb84** [DevExpress/testcafe#2843]
### Are you requesting a feature or reporting a bug?
feature

### What is the current behavior?
When testcafe is running e2e's with the concurrency option set, it appears to be only running the tests under a single fixture concurrently, not all tests from all fixtures. Once those tests are done, it goes onto the next fixture and runs any tests from it in parallel. 

The [Concurrent Test Execution ](http://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/concurrent-test-execution.html) docs don't mention this. One of the responses in the [community questions](https://testcafe-discuss.devexpress.com/t/parallel-tests-in-multiple-sessions/983/4) did say that current behavior is that

> TestCafe runs all tests from the current fixture (a category, folder) concurrently.

The result of this is that if we have several groups of fixtures to run through, and one of them happens to have a long running tests, we could have multiple free browser instances that aren't used since testcafe waits till all the tests in the current running fixture are done.

This results in longer running times for the full e2e suite than necessary. 

### What is the expected behavior?
When testcafe is executed in concurrent mode, once a browser instance is free, grab the next available tests in the current fixture. If there are no more tests to run in the current fixture, start running the tests from the next fixture. 

ie Don't wait for all tests in current fixture to complete before starting on the next set of tests. 

### How would you reproduce the current behavior (if this is a bug)?
Create multiple fixtures with multiple tests that are long running. You'll see execution done in parallel  within each fixture, but fixtures are executed in serial.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: OXS
* testcafe version: 0.21.1
* node.js version: v9.11.1

**Comment by AndreyBelym** [comment]
Hi @jarekb84, thanks for the proposal. However there is a catch with fixture hooks: I think that we can't execute a fixture hook before all tests of the previous/current fixture are done. Maybe we can detect if  fixtures in a testsuite don't have hooks, and then start fixtures concurrently.

**Comment by bdwain** [comment]
Why is that not possible? Seems like the running of separate fixtures would be independent.

**Comment by AndreyBelym** [comment]
@bdwain, e.g. you use fixture hooks to create and remove test databases, Different fixtures use different test databases content, but use the same name for the databases. If we create a database in the `before` hook of fixture B before removing database in the `after` hook of fixture A (given that fixture B runs after fixture A), the database of fixture B will be destroyed while tests from the fixture B are running.

**Comment by bdwain** [comment]
hmmm seems to me that if i'm running with concurrency on i should not expect to share resources across fixtures. The fact that only one fixture at a time is run isn't even documented. I could understand the expectation if concurrency was off, but with it on, there's no reason to expect resources to be shared.

**Comment by jarekb84** [comment]
@AndreyBelym could another parameter be exposed to allow you to do what I suggested instead of trying to determine if a hook exists. Our e2e's all have before/after hooks that don't step on each other's toes, so this limitation would not solve anything for my use-case.

**Comment by bdwain** [comment]
Agreed that a param would be better than trying to look for fixture hooks.

**Comment by jarekb84** [comment]
As @bdwain mentioned, what I proposed seems like what people would expect as the default behavior.   An alternative approach would be to make my proposal the default behavior and have the parameter put the test run into `--serialFixture` execution mode. This would be a breaking change for anyone who does rely on fixtures running fully before proceeding to the next one.

**Comment by Juansasa** [comment]
@AndreyBelym 
I did managed to run fixtures concurrency using the command line CLI so its completely possible.

**Comment by Juansasa** [comment]
I also need this. test based concurrency does not cut it for me.

**Comment by AndreyBelym** [comment]
Looks like TestCafe doesn't wait until a fixture is completed, at least in a basic test:
```js
fixture `1`;

test(`1`, t => t.wait(5000));
test(`2`, t => t.wait(10000));
test(`3`, t => t.wait(15000));

fixture `2`;

test(`1`, t => t.wait(5000));
test(`2`, t => t.wait(10000));
test(`3`, t => t.wait(15000));
```

if you run it with `testcafe -c 2 chrome test.js` you'll notice that the second browser manages to complete `2 - 1` and `2 - 2` test while the first browser is still executing the `1 -  3` test. I tried to use separate files for each fixture, but TestCafe still worked the same way. So could you please provide an example that can be used to reproduce this behavior?

**Comment by vishpat2020** [comment]
> Looks like TestCafe doesn't wait until a fixture is completed, at least in a basic test:
> 
> ```js
> fixture `1`;
> 
> test(`1`, t => t.wait(5000));
> test(`2`, t => t.wait(10000));
> test(`3`, t => t.wait(15000));
> 
> fixture `2`;
> 
> test(`1`, t => t.wait(5000));
> test(`2`, t => t.wait(10000));
> test(`3`, t => t.wait(15000));
> ```
> 
> if you run it with `testcafe -c 2 chrome test.js` you'll notice that the second browser manages to complete `2 - 1` and `2 - 2` test while the first browser is still executing the `1 - 3` test. I tried to use separate files for each fixture, but TestCafe still worked the same way. So could you please provide an example that can be used to reproduce this behavior?

Tests inside the fixtures are run concurrently. But across the fixtures are not. E.g. Create only have 1 test in each fixture 1 and fixture 2. If you try to run tests with 2 concurrent sessions, only 1 browser is used to run tests sequentially.

Any chance this issue can be resolved? The tests from different fixtures should be run concurrently. Otherwise for large number of tests, it takes too long to run.

**Comment by arubtsov** [comment]
@vishpat2020, let's continue the discussion in the [issue you created](https://github.com/DevExpress/testcafe/issues/5112).
