### ISSUE TITLE
Concurrent Execution definition

### ISSUE THREAD

**Issue by dineshpaduchuri** [DevExpress/testcafe#2845]
### Are you requesting a feature or reporting a bug?

I have small confusion regarding Concurrent execution. 
Example : I have some 10 tests(.ts files) in tests folder. And when i run below command all 10 tests will be distributed in two browsers like 5 tests in each browser and execute?
testcafe -c 2 chrome e2e\testcafe\tests\*.ts

Can you please  clarify concurrent means distributing the tests in multiple instances of browsers for faster execution or executing all tests in multiples instances?
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by MarinaRukavitsyna** [comment]
Hi @dineshpaduchuri 
You are almost correct: the "-c 2 chrome" command runs two chrome instances. But this mode does not mean that each instance operates with 5 tests.

Normally, when you run tests, TestCafe opens and connects a single browser instance (e.g. Chrome) and runs tests one after another. When the concurrency mode is used, TestCafe opens several instances of the same browser, e.g. two instances of Chrome in your case, and runs two tests (the number of instances) one by one. Once one of the browser instances completes running a test, it runs another test from the queue. So, one browser instance may run 7 tests and another one - only 3 if they work long. 

Note that the concurrency mode operates the test queue, not fixtures.
