### ISSUE TITLE
Tests hang up for headless browsers when --debug-on-fail option is enabled

### ISSUE THREAD

**Issue by MargaritaLoseva** [DevExpress/testcafe#2846]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

If we run tests in a headless browser (Chrome headless) and with the **--debug-on-fail** option enabled, tests hang up.

**Comment by miherlosev** [comment]
Running tests in headless mode with `--debug-on-fail` or `--debug-mode` options will cause an unexpected pause of the tests execution. For customers, it looks like a hung up.
In this case, we need to show a clear message about it.
