### ISSUE TITLE
Test failing makes other tests running in parallel fail

### ISSUE THREAD

**Issue by Lupiano** [DevExpress/testcafe#2852]
### Are you requesting a feature or reporting a bug?
Reporting a bug.

### What is the current behavior?
When I am running my tests concurrently in more than one browser and one test fails, all the tests that are running at the same time also fail. The other tests continue its execution but the final report is this:

  1) - Error in fixture.after hook -
      Unhandled promise rejection:

      [object Object]

### What is the expected behavior?
Failure in one tests must not affect others.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Windows 10
* testcafe version: 0.22.0
* node.js version: 8.11.4

**Comment by Lupiano** [comment]
I think it is related to #2546 because with -u this bug disappears.

**Comment by AlexKamaev** [comment]
Hi, @Lupiano 
You are right, the reason of the issues is in #2546. However, It is an expected and documented behavior. This mechanism is created to help developers to find uncaught errors and unhandled rejections, so if the issue occurs there is a possibility of error in the test code. The mechanism is implemented via Node's [`unhandledRejection` event](https://nodejs.org/api/process.html#process_event_unhandledrejection). When the event is handled, there is no reliable way to detect the place where error occurred, so we force TestCafe to fail all tests which are running at the moment. 
This behavior is described in the documentation. Please refer the article http://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-u---skip-uncaught-errors
If you are sure about your test code you can ignore this mechanism by using CLI `--skip-uncaught-errors` of `-u` option, as you've already mentioned.
 
I think we need to research why you have got the `[object Object]` string in the error message. Could please handle `process.unhandledRejection` event` in your test file?
 
Something like this:
```JS
var util = require('util');
process.on('unhandledRejection', (reason, p) => {
    console.log(util.format('%j', reason))
});
```

**Comment by Lupiano** [comment]
I'm getting this:

{"type":"externalAssertionLibraryError","isTestCafeError":true,"callsite":{"filename":"[filePath]","lineNum":[someLine],"callsiteFrameIdx":6,"stackFrames":[{},{},{},{},{},{},{},{},{},{},{},{},{}],"isV8Frames":true},"errMsg":"AssertionError: Some description: expected false to be truthy"}

It is a simple assertion error on some Selector.

**Comment by Lupiano** [comment]
BTW @AlexKamaev is there a way to skip these errors by code? Thanks for your time!

**Comment by AlexKamaev** [comment]
@Lupiano, thanks for your cooperation. The issue is unexpected, a simple assertion error should not cause unhandled rejection. Could I ask you to share your test file and test page or prepare a simple test, which shows the issue?
 
You can skip these errors only if you remove the listener from the process:
```JS
process.removeAllListeners('unhandledRejection');
```
Still, I do not recommend using this approach, because we need to detect the reason of the issue.

**Comment by Lupiano** [comment]
Hello @AlexKamaev, currently I cannot show you the test page, and the test file is a bit complex because uses some page objects, but it's something like this:

`await t.click(reportsPage.pendingTab).expect(reportsPage.pendingNameInput.exists).ok('The "Name" input for the "Pending" table should exist').expect(...).ok(...)... and the chain continues.`

This fails because the "reportsPage.pendingTab" selector is not possible to click (the element is under some other div that makes not possible to click it), so there is an assertion error:

```
AssertionError: The "Name" input for the "Pending" table should
      exist: expected false to be truthy

```
This is what generates the Unhandled Rejection errors in the other tests running in parallel.

**Comment by AlexKamaev** [comment]
@Lupiano 
I'll try to reproduce the issue. Until it is fixed, please use the '--skip-uncaught-errors' option.

**Comment by Lupiano** [comment]
Sure @AlexKamaev, if you need me to help you with something just tell me. Thanks!

**Comment by ymor** [comment]
Hi,
I've managed to recreate this heres an example:
```
import { Selector } from 'testcafe'; // first import testcafe selectors

fixture `Getting Started`// declare the fixture
    .page `https://devexpress.github.io/testcafe/example`;  // specify the start page

//then create a test and place your code there
test('My first test', async t => {

    const header = await Selector('header h1');
    const input = await Selector('#developer-name');

    await t
        .expect(header.textContent).eql('derp')
        .expect(input.textContent).eql('');
});
```

It only seems to occur when using chaining multiple expect asserts and when the failure does not occur in the last expect/assert.  e.g if you flip the two expects around in the example,  you won't see the unhandled promise rejection
