### ISSUE TITLE
[Feature] Allow scoped reporter plugins

### ISSUE THREAD

**Issue by chheller** [DevExpress/testcafe#2859]
### Are you requesting a feature or reporting a bug?

Feature

### What is the current behavior?

Currently, when using a reporter it must be a publicly published module, due to L111 of [src/runner/bootstrapper.js](https://github.com/DevExpress/testcafe/blob/master/src/runner/bootstrapper.js#L111). 

### What is the expected behavior?

When using a privately scoped NPM module, it should be possible to specify the scope, perhaps like 
```js
createTestCafe()
  .createRunner()
  .reporter('reporter-name', stream, 'scope')
```
so that scope can be modified like 
```js
return this.reporters.map(({ name, outStream, scope }) => {
  let pluginFactory = name;

  if (typeof pluginFactory !== 'function') {
    try {
      let scopedName = 'testcafe-reporter-' + name;
      if (scope) 
        scopedName = '@' + scope + '/' + scopedName;
      pluginFactory = require(scopedName);
     } catch (err) {
        throw new GeneralError(MESSAGE.cantFindReporterForAlias, name);
    }
  }
}
```
So that scoped packages can be used

**Comment by AndreyBelym** [comment]
Hi @chheller! Thanks for the feedback! If you use Runner API, you can pass the reporter's factory function instead of the reporter's name:
```js
const myReporter = require('@scope/testcafe-reporter-my-reporter');
// ...
testCafe
    .createRunner()
    .reporter(myReporter)
```

**Comment by chheller** [comment]
Ah I see, just 2 lines up should have given [that away](https://github.com/DevExpress/testcafe/blob/master/src/runner/bootstrapper.js#L109). Thank you! 

Though, could we update the docs the show that the reporter can be a function instead of a string of the [reporter's name](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#reporter)? That might help prevent future confusion
