### ISSUE TITLE
Docs: API reference required

### ISSUE THREAD

**Issue by VasilyStrelyaev** [DevExpress/testcafe#286]

**Comment by inikulin** [comment]
Let's call it "Using TestCafe programmatically" to avoid confusion with the actual test API. With current approach this shouldn't be a common demand to use this thing BTW.

**Comment by VasilyStrelyaev** [comment]
I thought of *test API* as *test framework*

**Comment by VasilyStrelyaev** [comment]
To me, API is how you interact with TestCafe from the outside, while tests do this "from the inside".
That's why I was thinking of "TestCafe API" and "Test Framework"
@inikulin

**Comment by VasilyStrelyaev** [comment]
Anyway, *Using TestCafe programmatically* (i.e., *How to use TestCafe programmatically*) is a name for a how-to topic, a recipe, while we need a name for a reference section.

So, as long as we don't want anything to be confused with *Test API*, that's what my first thought is:
![image](https://cloud.githubusercontent.com/assets/11459924/12393988/348cfb5c-be0a-11e5-9696-9634c4c8c484.png)

@inikulin

**Comment by VasilyStrelyaev** [comment]
other names, like Test Structure, Assertions, Hybrid Functions, Roles, Reporter Plugins, Browser Provider Plugins, Report Test Utils are just for clarity here - don't take them serious

**Comment by VasilyStrelyaev** [comment]
...or take, if you can come up with a better name right away

**Comment by inikulin** [comment]
@VasilyStrelyaev `TEST API` missing `Actions`. ` Report Test Utils` is the part of the `Reporter Plugins` and I'm not sure if it's need dedicated section, since there will be `pluginTestUtils` which are used for plugin testing, so it will be described in context of the plugin creation. `EXTENDING TESTCAFE` should include `Selector extensions` as well.

**Comment by VasilyStrelyaev** [comment]
@inikulin Ok, thx, updated the TOC
And since we are here to discuss the reference - I guess this time the section names are ok...
