### ISSUE TITLE
v0.22.0 on Mac regression - 'browser not closing after test' is re-occurring

### ISSUE THREAD

**Issue by jantonypdx** [DevExpress/testcafe#2860]
### Are you requesting a feature or reporting a bug?
bug

### What is the current behavior?
Looks like a regression of this issue: https://github.com/DevExpress/testcafe/issues/2132

In v0.22.0 - after test completes, Chrome process remains open (in dock)

### What is the expected behavior?
In v0.20.5 - after test completes, Chrome browser closes

### How would you reproduce the current behavior (if this is a bug)?
Run test using Chrome: 
```
npx testcafe chrome test.js
```

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://devexpress.github.io/testcafe/example
Test code

```js
// From your github page: https://github.com/DevExpress/testcafe
import { Selector } from 'testcafe'; // first import testcafe selectors

fixture `Getting Started`// declare the fixture
    .page `https://devexpress.github.io/testcafe/example`;  // specify the start page

//then create a test and place your code there
test('My first test', async t => {
    await t
        .typeText('#developer-name', 'John Smith')
        .click('#submit-button')

        // Use the assertion to check if the actual header text is equal to the expected one
        .expect(Selector('#article-header').innerText).eql('Thank you, John Smith!');
});
```

### Specify your

* operating system: Mac Sierra 10.12.6
* testcafe version: 0.22.0
* node.js version: 10.9.0

**Comment by AndreyBelym** [comment]
Hi @jantonypdx, I guess it's a regression of https://github.com/DevExpress/testcafe/issues/2226. Please read [my comment](https://github.com/DevExpress/testcafe/issues/2226#issuecomment-419095793) for more details. Could you please run `ps -ef >ps-ef.log` and `ps aux >ps-aux.log` after running TestCafe, and post the `ps-ef.log` and `ps-aux.log` files?

**Comment by jantonypdx** [comment]
Here you go:
[ps-ef.log](https://github.com/DevExpress/testcafe/files/2381163/ps-ef.log)
[ps-aux.log](https://github.com/DevExpress/testcafe/files/2381166/ps-aux.log)

**Comment by AndreyBelym** [comment]
Hi @jantonypdx, sorry for the late response. Judging by the differences in the log files, it's really the regressed #2226. I think we have to get rid of the `ps-node` module, because it works unreliably on macOS systems.
