### ISSUE TITLE
Testcafe freezes when clicking a custom element on Chrome 68

### ISSUE THREAD

**Issue by leofavre** [DevExpress/testcafe#2861]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

In the following example, `await Selector('sling-button')` works fine but Testcafe doesn't seem to handle clicking the `sling-button` custom element, causing the test to pause and the browser to freeze.

The bug happens on Chrome 68 but not on Safari 11.1.2 or Firefox 63.0b5. Note that I'm not using polyfills for custom elements.

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <script src="index.bundle.js"></script>
  </head>
  <body>
    <button>Native</button>
    <span>Native</span>
    <sling-button>Custom</sling-button>
  </body>
</html>
```

```javascript
import { Selector } from 'testcafe';

fixture`My Fixture`
  .page`http://127.0.0.1:8080`;

test('My Test', async (t) => {
  const nativeButton = await Selector('button');
  const nativeSpan = await Selector('span');
  const customElementButton = await Selector('sling-button');

  await t
    .click(nativeButton) // works fine
    .click(nativeSpan) // works fine
    .click(customElementButton); // Chrome crashes
});
```

### What is the expected behavior?

Clicking a custom element should work like any other native element.

### How would you reproduce the current behavior (if this is a bug)?

1. Import a custom element to the project.
2. Include it in the html.
3. Write a test that selects it with `Selector` and uses `t.click` to try to click it.
4. Run testcafe with Chrome.
5. Verify that the browser stops responding.

### Specify your

* operating system: Mac OS 10.13.6
* testcafe version: 0.22.0
* node.js version: 8.11.4
* chrome 68.0.3440.106

**Comment by AndreyBelym** [comment]
Hi @leofavre! Unfortunately you code misses the `index.bundle.js` JS file that creates the `<sling-button>` custom HTML element. Could you please attach its content to a comment, or point me to the library/framework that provides this button?

**Comment by leofavre** [comment]
@AndreyBelym Here's a complete example:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <script>
      const myButtonTemplate = document.createElement('template');
      myButtonTemplate.innerHTML = '<button><slot></slot></button>';

      class myButton extends HTMLElement {
        constructor() {
          super();
          this.attachShadow({ mode: 'open' });
        }
        connectedCallback() {
          const content = myButtonTemplate.content.cloneNode(true);
          this.shadowRoot.appendChild(content);
        }
      }

      window.customElements.define('my-button', myButton);
    </script>
    <title>TestCafé</title>
  </head>
  <body>
    <button>Laser</button>
    <span>Native</span>
    <my-button>Text</my-button>
  </body>
</html>
```

```javascript
import { Selector } from 'testcafe';

fixture`Getting Started`
  .page`http://127.0.0.1:8080`;

test('Laser', async (browser) => {
  const nativeButton = await Selector('button');
  const nativeSpan = await Selector('span');
  const customElementButton = await Selector('my-button');

  await browser
    .click(nativeButton)
    .click(nativeSpan)
    .click(customElementButton);
});
```

**Comment by miherlosev** [comment]
Hi @leofavre 

Thank you for completed example. I've reproduced the problem.
