### ISSUE TITLE
Cannot navigate away from YouTube pages without getting an error

### ISSUE THREAD

**Issue by nabond240** [DevExpress/testcafe#2862]
### Are you requesting a feature or reporting a bug?

Reporting a bug

### What is the current behavior?

Using locally installed version of TestCafe.
 Running tests in:
 - Chrome 68.0.3440 / Windows 10.0.0

 YouTube Test
 × testing

   1) Error on page "https://www.youtube.com/user/CBSNewsOnline":

      [object DOMException]

      Browser: Chrome 68.0.3440 / Windows 10.0.0

         2 |
         3 |test('testing', async t => {
         4 |    await t.maximizeWindow();
         5 |    await t.navigateTo('https://www.yahoo.com/');
         6 |    await t.navigateTo('https://www.youtube.com/user/CBSNewsOnline');
       > 7 |    await t.navigateTo('https://www.google.com');
         8 |})

         at navigateTo (C:\YouTube_Test\tests\test.js:7:13)

 1/1 failed (20s)

### What is the expected behavior?

I was expecting to be able to navigate to and from any youtube.com site without errors.

### How would you reproduce the current behavior (if this is a bug)?

execute the following code:

fixture `YouTube Test`.page `https://www.google.com/`;

test('testing', async t => {
    await t.maximizeWindow();
    await t.navigateTo('https://www.yahoo.com/');
    await t.navigateTo('https://www.youtube.com/user/CBSNewsOnline');
    await t.navigateTo('https://www.google.com');
})

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:  please see sample code above.

Test code
please see sample code above.
```js

```

### Specify your

* operating system:  Windows 10
* testcafe version:  0.21.1
* node.js version:  8.11.3

**Comment by miherlosev** [comment]
Hi @nabond240 

I cannot reproduce the problem. 
It looks like the `https://www.youtube.com/user/CBSNewsOnline` page has JavaScript errors. TestCafe handle these errors on the tested page and report about it.
Use the [--skip-js-errors](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors) option to ignore JavaScript error handling.
