### ISSUE TITLE
Element.requestFullScreen() throws an Error when a page is tested with TestCafe

### ISSUE THREAD

**Issue by samuelsh** [DevExpress/testcafe#2863]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

Click on fullScreen control seems not working

### What is the expected behavior?

Click on fullScreen control will switch video player to full screen mode

### How would you reproduce the current behavior (if this is a bug)?

Following code should reproduces the issue:
```js
  const client_isFullScreen = ClientFunction (() => {
        return document.webkitCurrentFullScreenElement &&
            document.webkitCurrentFullScreenElement.nodeName == "DIV";
  });
 
   isFullScreen: async function (){
        return client_isFullScreen()
    }

    playerFullScreenToggle: async function (t: TestController){
      await t
          .click(".player-button.player-control-fullscreen")
    }

fixture`Video Player Test Suite`
    .page("https://kabbalahmedia.info/en/lessons/cu/koUvHS4T?language=en");

test('fullScreenToggle', async t => {
    await player_utils.waitForPlayerToLoad();
    await t.expect(await player_utils.isFullScreen()).notOk();
    await player_utils.playerFullScreenToggle(t);
    await t.expect(await player_utils.isFullScreen()).ok();
    await player_utils.playerFullScreenToggle(t);
    await t.expect(await player_utils.isFullScreen()).notOk();
});
```

      AssertionError: expected null to be truthy

      Browser: Chrome 69.0.3497 / Mac OS X 10.13.6

          97 |test('fullScreenToggle', async t => {
          98 |    // await setHeight(selectors.player.controls.fullScreen);
          99 |    await player_utils.waitForPlayerToLoad();
         100 |    await t.expect(await player_utils.isFullScreen()).notOk();
         101 |    await player_utils.playerFullScreenToggle(t);
       > 102 |    await t.expect(await player_utils.isFullScreen()).ok();
         103 |    await player_utils.playerFullScreenToggle(t);
         104 |    await t.expect(await player_utils.isFullScreen()).notOk();
         105 |});

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://kabbalahmedia.info/en/lessons/cu/koUvHS4T?language=en

### Specify your

* operating system: MacOS HighSierra
* testcafe version: 0.21.1
* node.js version: 9.8

**Comment by ZeddEn** [comment]
I have a similar problem with jwplayer. No problem is detected with other player's actions (play, pause, mute, unmute, close ad, etc)
