### ISSUE TITLE
TestCafe clicks on item in Last second of given selectorTimeout, although the item exists on the DOM

### ISSUE THREAD

**Issue by asharmab** [DevExpress/testcafe#2870]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

**Use Case :** I have a kebab Menu icon. I want to click on it

**Steps performed:**

Check if kebab.exists  --> this returns true
Hover over the kebab ---> Successfully hovers over the kabab
Click on kebab   ---> Here the Application waits for the element to appear for the provided selector timeout timer(20 secs), in the end of the 20 seconds( (19th second)) it clicks on the kabab.
If I reduce the selectortimeout to 10 seconds it clicks on kabab at 9th second.

### What is the expected behavior?

The kebab already exists on DOM, it already returned true and hovered over the item. So the delay in clicking it is not expected. It should click on it immediately

### How would you reproduce the current behavior (if this is a bug)?

I am new to testcafe. I believe, the issue could be specific to the way our application's DOM is structured.

#### Provide the test code and the tested page URL (if applicable)
**The Item on the page I am accessing is following :** 

` td _ngcontent-c10="" style="width: 30px; text-align: right;"
`
 **I am accessing it as  :** 
` Selector('table').find('tbody').find('tr').nth(i).find('td:last-child')`
      
```
  if(await formArray[0].editKebab.exists){
          await t
                .hover(formArray[0].editKebab) ---- **It hovers here immediately**
                .click(formArray[0].editKebab) --- **Line where it waits and clicks after 19 seconds**
                await requestForm.initEditKebab();
                if(await requestForm.editKebab.deleteForm.exists){
                  await t.click(requestForm.editKebab.deleteForm);
                }
        
        }

```
### Specify your

* operating system: macOS Sierra
* testcafe version:0.21.1
* node.js version:v8.9.1

**Comment by AndreyBelym** [comment]
Hi @asharmab! This behaviour means that the element specified by your Selector is covered by another element. If you use Chrome, you can check it by right-clicking in the target element's position, choosing `Inspect` in the menu, and check that the inspected element is the element specified by your Selector. I can help you with this check if you post HTML source of your page.

**Comment by asharmab** [comment]
Thanks for the pointer. I figured out the hidden element. Now I am hovering over the old item and then clicking on the item covering it . Since, the item to be clicked shows up after one hovers over the item I was using earlier. Thanks a lot for your help!!
