### ISSUE TITLE
The 'Tested with TestCafe' badge image is not available

### ISSUE THREAD

**Issue by AlexSkorkin** [DevExpress/testcafe#2872]
### Are you requesting a feature or reporting a bug?

Bug.

### What is the current behavior?

The badge image is not available at the specified link: https://img.shields.io/badge/tested%20with-TestCafe-2fa4cf.svg

### What is the expected behavior?

The image is available.

### How would you reproduce the current behavior (if this is a bug)?

1) Go at https://github.com/DevExpress/testcafe#badge
2) Use the specified HTML code.

**Comment by AndreyBelym** [comment]
I guess we have a problem accessing the `shields.io` contents from our corporate network.

**Comment by AndreyBelym** [comment]
Confirmed network problems caused by our corporate firewall.
