### ISSUE TITLE
Create GitLab CI recipe

### ISSUE THREAD

**Issue by lucianonooijen** [DevExpress/testcafe#2873]
### Are you requesting a feature or reporting a bug? 

Requesting a feature

### What is the current behavior? 

There is only CI support for for AppVeyor, CircleCI, Travis, TeamCity, Jenkins

### What is the expected behavior? 

Support for GitLab CI

### Specify your

* operating system: **Testserver: GitLab Docker Runner (latest), using image `node:8-alpine`**
* testcafe version: **-**
* node.js version: **8 latest**

**Comment by AndreyBelym** [comment]
Hi @lucianonooijen! You can use the [official TestCafe Docker Image](https://devexpress.github.io/testcafe/documentation/using-testcafe/using-testcafe-docker-image.html) in GitLab environment. Check [this comment](https://github.com/DevExpress/testcafe/issues/2747#issuecomment-414319643) for configuration details: 

I think we should add a recipe for GitLab to our docs.

**Comment by lucianonooijen** [comment]
Hi @AndreyBelym, thanks for the prompt response! What the biggest challenge is (I think), is to make it possible to test the project itself.

For example: for the project https://github.com/BytecodeBV/Bytecode-Website I want the following tests:

* All pages are working
* Contact forms are working correctly (both server-side and client-side)

This would mean the following should happen in GitLab for the `testcafe` job:

1. Install Yarn and run `yarn` to install dependencies, and build with `yarn run build`
2. Start the Express server (`yarn run start`) in the background
3. When the Express server is up and running on `localhost:4000`, continue
4. Now run TestCafe testing scripts, using the `localhost:4000` server
5. If any tests fail, exit with non-zero exit code
6. If all tests pass, exit with exit code zero
7. Close the Express server

The fact that the Express server must be running in the background, and the TestCafe tests cannot run until the server is up and running is the part where I get stuck.

A dirty hack could be to run a script (for example with the `concurrently` NPM package), where the server is started, and then after `sleep`-ing for x seconds, the tests will run. 

An example where I implemented a similar script in `package.json` is (this is without `sleep`): 

```json
"export": "concurrently -k -s \"first\" 'yarn run server' 'yarn run tests && exit 0'"
```

It is obvious this is not an ideal way to deal with the concurrent processes, so it would be awesome if it would be possible to do this without any dirty hacks.

**Comment by AndreyBelym** [comment]
@lucianonooijen, you can use TestCafe's [app option](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-a-command---app-command) to start the server.

TestCafe image comes with `npm`, so you can use `npm` to install your project's dependencies and build it. If you really need `yarn`, you can install it with `npm i -g yarn`.

**Comment by lucianonooijen** [comment]
@AndreyBelym I wasn't aware of the server starting option. That will definitely come in handy!

**Comment by jugglingthebits** [comment]
> so it would be awesome if it would be possible to do this without any dirty hacks.

@lucianonooijen there is already: Start the server using `.gitlab-ci.yml`, then use [wait-on](https://github.com/jeffbski/wait-on) to wait until the server is started. Then run the tests.
