### ISSUE TITLE
Tests can't run in "InPrivate" window in Edge

### ISSUE THREAD

**Issue by aboe026** [DevExpress/testcafe#2881]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
I'm trying to get the tests to run in an "InPrivate" window in Edge by doing the following:
```
testcafe "edge -private" tests/*.js
```
The tests run in an ordinary, non-"InPrivate", Edge window. Do I have the flag incorrect? I see for other browsers it is:
```
testcafe "chrome -incognito" tests/*.js
testcafe "firefox –private-window" tests/*.js
```

### What is the expected behavior?
The tests run in an "InPrivate" Edge window

### How would you reproduce the current behavior (if this is a bug)?
attempt to run testcafe tests with the `"edge -private"` option for browser

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Windows 10 17134
* testcafe version: 0.21.1
* node.js version: 9.9.0

**Comment by AlexSkorkin** [comment]
Thank you for reaching out to us and submitting this issue.
 
The 'edge' browser alias executes the microsoft-edge command to start the browser. While in other browsers like Chrome and Firefox, their '-incognito' and '-private-window' arguments work in a straightforward way, the Edge browser requires additional tweaks to be executed in private mode.
 
You might want to check out the following threads where a similar issue with Edge was discussed:
 
[How to start Microsoft Edge in private mode from command line](https://social.msdn.microsoft.com/Forums/en-US/21affc27-64e1-495c-aa23-c0cbbce4a39c/how-to-start-microsoft-edge-in-private-mode-from-command-line?forum=scripting)
[How to launch Edge -inprivate by default](https://dancharblog.wordpress.com/2017/03/18/how-to-launch-edge-inprivate-by-default/)

We decided to improve the Edge browser's launching, so it will properly start in private mode in the context of this issue:
 
DevExpress/testcafe-hammerhead#1764
 
In the meantime, as a workaround, you might want to create a [custom browser provider plug-in](http://devexpress.github.io/testcafe/documentation/extending-testcafe/browser-provider-plugin/), which will execute Edge in private mode. For instance, I've created this sample to start with:

[testcafe-browser-provider-edge-private](https://github.com/AlexSkorkin/testcafe-browser-provider-edge-private)

The Edge browser starts in private mode when you use this plug-in. Please note that you can use this plug-in at your own risk and I don't guarantee that it will work under all circumstances.
