### ISSUE TITLE
Error when using Roles in headless firefox on ubuntu

### ISSUE THREAD

**Issue by cullophid** [DevExpress/testcafe#2885]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Throws and error when using roles

```
✖ should load dashboard (screenshots: /mnt/c/code/cms-frontend/artifacts/screenshots/2018-09-20_13-16-23/test-1)

   1) - Error while restoring configuration after Role switch -
      Error on page "http://localhost:4200/":

      uncaught exception: Response with status: 0  for URL: null

      Browser: Firefox 61.0.0 / Ubuntu 0.0.0
```

### What is the expected behavior?
login and continue to test

### How would you reproduce the current behavior (if this is a bug)?
running the first test using a role

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js
const User = Role(
  "http://localhost:4200/login",
  async t => {
    await t
      .typeText("#login-form-email", "andreas@cylindo.com")
      .typeText("#login-form-password", "Cylindopassword1")
      .click("#login-form-submit");
  },
  { preserveUrl: true }
);

fixture("Auth").page("http://localhost:4200")";

test("should load dashboard", async t => {
  await t
    .useRole(User)
    .expect(Selector("app-dashboard-home").exists)
    .ok()
    .takeScreenshot();
});

```

### Specify your

* operating system:
Ubuntu in Windows 10
* testcafe version:
0.22
* node.js version:
8.11.3

**Comment by cullophid** [comment]
Same Issue on MacOS with firefox..
Works on:
MacOS, Chrome
Windows 10, chrome, firefox

**Comment by AndreyBelym** [comment]
Hi @cullophid, looks like there is an exception in your JS code on the page. I need an example page or access to the real page to reproduce the issue. You can also try to enable the [Skip JS errors](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors) option to suppress uncaught exceptions in JS code.

**Comment by subbiah2806** [comment]
import { Role } from 'testCafe' and use -e in cmd line to skip js error.

Hope it resolves

**Comment by cullophid** [comment]
I'll give that a try:)
