### ISSUE TITLE
testcafe takes 2x more time to boot than than vanilla js when "native" typescript compilation is used

### ISSUE THREAD

**Issue by Hotell** [DevExpress/testcafe#2887]
### Are you requesting a feature or reporting a bug?

**BUG**

### What is the current behavior?

tests that are compiled "natively" within testcafe take 2x more time then precompiled with `tsc` and run on compiled vanilla js files:
![image](https://user-images.githubusercontent.com/1223799/45847367-1fd38780-bd2b-11e8-9bbf-3341c96fdcfa.png)

### What is the expected behavior?
leverage `tsc` properly and run test on par with vanilla js

### How would you reproduce the current behavior (if this is a bug)?

run  e2e test written in typescript so testcafe takes care of compilation , then compile test files via `tsc` and run testcafe against compiled files

#### Provide the test code and the tested page URL (if applicable)

the app is private under corporate repo, so I cannot share that much

### Specify your

* operating system: macOs / Win 10
* testcafe version: testcafe@0.22.0
* node.js version: v8.10.0
* typescript version used for precompile manually: typescript@2.9.2

**Comment by miherlosev** [comment]
We try to reproduce the problem on synthetic tests and don't see a serious performance degradation.
 Feel free to reopen the issue if you provide a test set in which we can reproduce the problem.

**Comment by Hotell** [comment]
This isn't helping really.

First thing, I'm not a testing expert so I don't completely understand what you mean by your " reproducing the problem on synthetic tests" 👀

Also I provided you exact data about the difference. You can really test it in  60 seconds by creating 1 test file and run it in both TS and vanilla JS version to see the difference. With TS it's 2 times slower. 

I would like to do the transpilation right and submit a PR to your compiler, but unfortunately I'm kinda lost within your compiler logic. Maybe if someone would provide a guidance I would be able to finish it and with it resolve other TS related issues ( like support for consuming custom tsconfig.json ).

The tests are also slow because the way how you compile TS. file by file which is really not efficient.

> Feel free to reopen the issue 

I've no rights so how can I possible reopen this ? 😄

**Comment by AndreyBelym** [comment]
Hi @Hotell, yes, we already know that TestCafe should send all TS test files to the TS compiler (`tsc`) at once, instead of the current "one-by-one" approach. But I've been able to reproduce the problem only when you specify multiple TS test files. Module dependencies are already compiled in the batch mode by `tsc`, so they don't have impact on the compilation time. For the just one file (as in your original post), there must be no difference between TestCafe and `tsc`. This is why we need your project, or just some example project which can be used to reproduce the problem.
