### ISSUE TITLE
Unlock Page and finish button appears when Test fails

### ISSUE THREAD

**Issue by automation9006** [DevExpress/testcafe#2888]
### Are you requesting a feature or reporting a bug?
 Reporting an issue

### What is the current behavior?
 I get finish and unlock page button when my test fails

### What is the expected behavior?
 to continue for new test

### How would you reproduce the current behavior (if this is a bug)?

Just run bunch of tests in serial

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
its my work project

Please see the screen shot here
https://i.imgur.com/V2FzWWa.jpg
Test code
just run bunch of tests
```js

```

### Specify your

* operating system:
windows 7
* testcafe version:
0.21.1
* node.js version:
6.10.0

**Comment by AlexKamaev** [comment]
Hi @automation9006 
The `Finish` button usually appears when you run tests with the `--debug-on-fail` option. Please refer the following article: http://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--debug-on-fail
To avoid this behavior, it is sufficient to remove this option from CLI arguments (or from the `run` method options if you are using `Runner`)

**Comment by automation9006** [comment]
@AlexKamaev  Thanks ! Sorted.
