### ISSUE TITLE
ERROR No tests to run. Either the test files contain no tests or the filter function is too restrictive.

### ISSUE THREAD

**Issue by subbiah2806** [DevExpress/testcafe#2889]
### reporting a bug?
I have written the test in another file and calling it below the fixture, but now I am getting this error. 

ERROR No tests to run. Either the test files contain no tests or the filter function is too restrictive.

Test code

---CommonScripts.js---

const commonScripts = {
    google() {
        test('google', async t => {
            await t
                .typeText('#tsf > div:nth-child(2) > div.A8SBwf > div.RNNXgb > div > div.a4bIc > input', 'Hello World');
        });
    }
};
export default commonScripts;

---google.js---

import commonScripts from './commonScripts.js';

fixture('google')
    .disablePageReloads
    .page('https://google.com');

commonScripts.google();

### Specify your

* operating system:10.13.6
* testcafe version:"^0.22.0",
* node.js version:10.9.0

**Comment by subbiah2806** [comment]
It works if there is atleast one test below fixture like this.

import commonScripts from './commonScripts.js';

fixture('google')
    .disablePageReloads
    .page('https://google.com');

test('wait', async t => {
    await t
        .wait(1);
});
commonScripts.google();

**Comment by ljowen** [comment]
Seems to be an issue with the static analysis testcafe does to determine testfiles.
As a hacky work around you can try adding a comment in google.js:
`// test()`

It would be nice to be able to add an annotation to allow importing tests as modules

**Comment by subbiah2806** [comment]
Helpful thanks

**Comment by AlexKamaev** [comment]
@subbiah2806 @ljowen 
Hi
The code analyzer requires use of the `test` method in the test file, but you can easily bypass this restriction in the following manner:
 
Create your module with some object which contains a test name and test function:
```JS
const commonScripts = {
    testSet1 () {
        return [{
            testName: 'test',
            testFn: async t => {
                await t.click('a');
            }
        }];
    }
};
 
export default commonScripts;
```
 
Import this module and call the test function from the module's resulting object:
 
```JS
import commonScripts from './test-module';
 
fixture `gh-1312`
    .page `http://example.com`;
 
function startTesting(testSet) {
    for (let i = 0; i < testSet.length; i++)
        test(testSet[i].testName, testSet[i].testFn);
}
 
startTesting(commonScripts.testSet1());
```
It will allow structurizing your tests as you wish and avoid the code analyzer's restrictions.

**Comment by Jgshirley** [comment]
Hello, I am currently having the same issue and I don't understand how this solution works. Could you please explain.

**Comment by AlexKamaev** [comment]
@Jgshirley
This issue occurs, because the TestCafe static code analyzer requires words `test` and `feature` in your test file. My solution is to reorganize the test files structure. I define the array of test names and test functions in a separate module (see `commonScripts`). Then I import test names and test functions and use them as params of the global  `test` function::
```JS
function startTesting(testSet) {
    for (let i = 0; i < testSet.length; i++)
        test(testSet[i].testName, testSet[i].testFn);
}
```
It allows me to bypass the restrictions of the static analyzer.
I should add that the latest TestCafe version supports the `--disable-test-syntax-validation` option (http://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--disable-test-syntax-validation) . This option disables checks for test and fixture directives in test files. Use this flag to run dynamically loaded tests.

**Comment by dirkrooijakkers** [comment]
The same problem occurred to me and i found out it was the .tsx extension that caused the problem. Changing back to .ts fixed it. 👍

**Comment by icfantv** [comment]
I got bit by the same issue as @dirkrooijakkers.  Might be worth updating the documentation to indicate that TSX files are not supported or point to documentation that lets you point testcafe to the right `tsconfig.json` file or just specify your own compiler options.  I have `jsx: 'react'` set in my workspace's tsconfig.json file but it's not being used by testcafe.

**Comment by AndreyBelym** [comment]
@icfantv this issue is covered by https://github.com/DevExpress/testcafe/issues/1845. Don't hesitate to add 👍 to it.

We have plans to implement it, but I can't give you any estimates yet. Of course, your PR will be welcomed 😄

**Comment by icfantv** [comment]
@andreybelym ah, thanks for the reference.
