### ISSUE TITLE
Unable to click onlclick action menu items...

### ISSUE THREAD

**Issue by hiruthre** [DevExpress/testcafe#2891]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?
Unable to click onlclick action menu items...

"< a class="waves-effect waves-cyan active" href="#" onclick="javascript:__fnLoadScreen('Bodm/Layout?mode=CUD');" title="User Master">< i class="mdi-action-view-carousel">< /i>User Master< /a>

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: Restricted... Provided Link code

Test code

Unable to click onlclick action menu items...

< a class="waves-effect waves-cyan active" href="#" onclick="javascript:__fnLoadScreen('Bodm/Layout?mode=CUD');" title="User Master">< i class="mdi-action-view-carousel">< /i>User Master< /a>

Kindly help..
```js

```

### Specify your

* operating system: Windows 10
* testcafe version: 0.20.3
* node.js version: v8.11.1

**Comment by AlexKamaev** [comment]
@hiruthre
Would you please provide me with the details of the issue since I need to know how your `__fnLoadScreen` works and how the action menu items are rendered?
 
I would appreciate it if you prepare a small working example to demonstrate the issue.

**Comment by hiruthre** [comment]
Since webpage is confidential and can't share in public. 
The webpage contains the following components
1. Main URL
2. Left Menus
3. iframe (in which __fnLoadScreen URL will be load based on onclick action).

Each Menu is having onclick action with __fnLoadScreen(URL). whenever a user clicks on a menu, the system appends fnLoadScreen URL with the main URL and load the screen in an iframe.

**Comment by AlexKamaev** [comment]
I prepared a sample based on your code and was not able to reproduce the issue.
Could you please modify it to demonstrate the problem?
Test page:
```HTML
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <script type="text/javascript">
        function __fnLoadScreen (url) {
            document.getElementById('frame').src = url;
        }
    </script>
</head>
<body>


<a class="waves-effect waves-cyan active" href="#" onclick="javascript:__fnLoadScreen('http://example.com');" title="User Master">
    <i class="mdi-action-view-carousel"></i>User Master
</a>

<iframe id="frame"></iframe>

</body>
</html>
```

Test file:

```JS
fixture `gh-1312`
    .page `../pages/index.html`;

test('something', async t => {
    await t.click('a');
    await t.wait(4000);
});
```

If you are unable to reproduce the issue in my sample, it would help if you prepare a simple project with test data and remove confidential information to show the problem.

**Comment by hiruthre** [comment]
Alex,
I am able to click link using the selector. Since selector changes based on the menu configuration i.e. position of a menu. However onclick action is constant even though position change.. Hence I want to click menu based on onclick action attribute rather than using selector.

**Comment by AlexKamaev** [comment]
If you just want to click an element by it's attribute you can use [attribute selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors)
 
Thus for the button in the following example:
```HTML
<a class="waves-effect waves-cyan active" href="#" onclick="javascript:__fnLoadScreen('http://example.com');" title="User Master">
    <i class="mdi-action-view-carousel"></i>User Master
</a>
```
you can use this selector:
```JS
await t.click('a[onclick="javascript:__fnLoadScreen(\'http://example.com\');"]');
```

**Comment by hiruthre** [comment]
Alex, am able to click menu using attribute selector.  Thanks..
