### ISSUE TITLE
Provide more details when test cannot load a page due to corporate network security rules

### ISSUE THREAD

**Issue by msemkowicziwanow** [DevExpress/testcafe#2893]
### Are you requesting a feature or reporting a bug?

Bug/Feature(??)

### What is the current behavior?

After creating and running a super simple test (which just jumps to the google main page and expects the body to be visible) browser is being open, test cafe logo is displayed but google page is not reached -  I'm getting an error 'Failed to find a DNS-record for the resource at "https://google.com" ' 

Tests are being executed on a machine in corporate network, I'm guessing that the security rules are somehow blocking the execution.

Is there a way to get more detailed logs so that I can adjust the security policy?
Without it I'm just stabbing in the dark

### What is the expected behavior?

Get more detailed dev logs for the error

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code
import { Selector } from 'testcafe';

fixture `Start Test codeing Here`
.page("https://www.google.com/")

test('Views Home page', async actions => {
console.log("AAA");
const body = Selector("#gsr");
await actions.
expect(body.visible);
return actions;
}); 

### Specify your

* operating system: WIndows 7
* testcafe version: 0.22.0
* node.js version: 8.11.3

**Comment by AndreyBelym** [comment]
It's a duplicate of #3492 and #1606.
