### ISSUE TITLE
Cookies not being set 

### ISSUE THREAD

**Issue by ludwigbacklund** [DevExpress/testcafe#2894]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

Setting cookies through a client function is not actually setting them on the correct document(?). They do not exist when trying to find them through the "Application" tab of the chrome developer tools but can be seen with ```console.log(document.cookie)```. The application does not detect the cookies at all. I also tried setting the cookies via a user role with the same result

### What is the expected behavior?

The application should detect the set cookies.

### How would you reproduce the current behavior (if this is a bug)?

Create a fixture with a beforeEach hook or a test with a before hook and call a clientFunction that sets cookies via ```document.cookie = "someCookie=something"```

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: Private

Test code

```js
const setCookies = ClientFunction(() => {
    console.log('This is called');
    document.cookie = 'cookie1=1';
    document.cookie = 'cookie2=true';
});

fixture`Something`
    .page('redacted')
    .beforeEach(async t => {
        await setCookies();
    });

test('something', async t => {
// The cookies have not been set when it gets here
    await t
        .click(Selector('button').withText('Something'));
});
```

### Specify your

* operating system: macOS 10.13.6
* testcafe version: 0.22.0
* node.js version: 10.10.0

**Comment by AlexKamaev** [comment]
Hi @ludwigbacklund
I modified your test to check it on my machine and found that cookies are saved and restored correctly. Please see the following code::

```JS
import { Selector, ClientFunction } from 'testcafe';

const setCookies = ClientFunction(() => {
    document.cookie = 'cookie1=1';
    document.cookie = 'cookie2=true';
});

const getCookie = ClientFunction(() => {
   return document.cookie;
});

fixture`Something`
    .page('http://example.com')
    .beforeEach(async t => {
        console.log('set cookies');
        await setCookies();
    });

test('something', async t => {
    console.log('get cookies:' + await getCookie());
    await t
        .click(Selector('h1'));
});

```
And here is console output:

```JS
Something
set cookies
get cookies:cookie1=1; cookie2=true
 √ something

```

In the log, I see that cookies are restored correctly. 
As for the issue with the `Application tab`, cookies are not displayed at the `Application tab` because of our internal mechanisms. When you set cookies, they are stored not in the browser but in our own storage.

**Comment by ludwigbacklund** [comment]
Thanks for the quick response. You are correct in that the cookies appear with a call to getCookie but the application is still not seeing/utilizing them. In my case there is an overlay that disappears when a cookie is set to true, which is verified to be working outside of any test framework but also in Cypress, but does not work here. I don't know if you know how Cypress works but do you think there's any functional difference between these two snippets?

```js
    cy.setCookie('cookie1', '1');
    cy.setCookie('cookie2', 'true');
```
and
```js
    document.cookie = 'cookie1=1';
    document.cookie = 'cookie2=true';
```
I'm properly confused here.

**Comment by AlexKamaev** [comment]
@ludwigbacklund
Could you please try to modify your test code in the following manner:

```JS
.beforeEach(async t => {
        console.log('set cookies');
        await setCookies();
        await t.navigateTo(testPageUrl);
    });
```
I added additional navigation to the test page to force page reloading. As I've mentioned before, testcafe has it's own mechanism to store cookies. This mechanism works on the server side so we need to reload the page to synchronize cookies.
 
Could you please try this approach?

**Comment by ludwigbacklund** [comment]
@AlexKamaev Thank you, that seems to work. I'm not sure if it's just for this use-case but that was not very straight forward. Might be interesting to work towards a TestCafe solution to setting cookies so force reloading is not necessary.

**Comment by callmeaponte** [comment]
Any idea why setting cookies would work fine in Google Chrome, Mozilla Firefox and Internet Explorer - but not in Microsoft Edge? I'm using the same scripts listed above.

I'm not sure if this is worth opening a new ticket over, or if maybe it's just me.

**Comment by AlexKamaev** [comment]
@callmeaponte
Could you please clarify whether you have problems on the server or client side? Do you have any result after executing this method `console.log('get cookies:' + await getCookie());`? Are you using the approach with the `navigateTo` command after setting the cookies?

**Comment by callmeaponte** [comment]
No worries, I've been tinkering with this all weekend and I think it was just me. I was able to get it working by moving `setCookies()` outside the `beforeEach` hook and inside the test script - where it would fire well after the page loaded  -and that did the trick.

All of the requests at our office are routed through a proxy so I suspect that was the issue...? It might have been trying to set the cookie before the request was redirected to the final destination/domain. I was just stumped as to why it only affected Microsoft Edge.
