### ISSUE TITLE
Docs: Report test utils should be documented

### ISSUE THREAD

**Issue by VasilyStrelyaev** [DevExpress/testcafe#290]
Whatever this is... I was just writing down...

**Comment by MargaritaLoseva** [comment]
@VasilyStrelyaev @inikulin I suppose this issue is about custom reporters. Can we close it?

https://github.com/DevExpress/testcafe/pull/378 is merged

**Comment by inikulin** [comment]
I guess so

**Comment by inikulin** [comment]
Implemented in #378
