### ISSUE TITLE
Improve a message about JavaScript error occurred on the page

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#2909]
TestCafe tracks JavaScript errors occurred on the page. A test writer often doesn't know that a tested page has JavaScript errors. According to the error message provided by TestCafe, a customer cannot identify that problem is related to the tested page.

Need to extend the error message as follow (it's a draft message format):
```js
A JavaScript error was occurred on the https://example.com.
If this error is occurred on the page without TestCafe, then you can disable JavaScript error tracking by turn on the --skip-js-error flag.
If the error is occurred only with TestCafe, then it's a TestCafe's bug. Write a new issue about it - https://github.com/DevExpress/testcafe/issues/new and attach a small reproducible example.

JavaScript error details:
{error.message}
{error.stack}
```

**Comment by AlexKamaev** [comment]
I've modified the message a bit and checked it:
A JavaScript error on the "http://example.org".
If this error occurred on a page without TestCafe, you can disable JavaScript
error tracking by turning the --skip-js-errors option on.
If the error occurs only with TestCafe, then it's a TestCafe's bug. Write a
new issue about it using the following template:
"https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

JavaScript error details:
Test error:
    at method3 (http://example.com):1:3
    at method2 (http://example.com):1:2
    at method1 (http://example.com):1:1
