### ISSUE TITLE
An error appears when test starts without defined fixture

### ISSUE THREAD

**Issue by AlexKamaev** [DevExpress/testcafe#2913]
I missed `fixture` keyword and got
`TypeError: Cannot read property 'requestHooks' of null
at new requestHooks (D:\projects\testcafe\src\api\structure\test.js:16:42)`

**Comment by AndreyBelym** [comment]
Please take into account that we are about to remove checking for `fixture` and `test` in test files: #2470 is in the current sprint's milestone.

IMHO it's better to check in the `test` 's constuctor that there is a defined fixture.
