### ISSUE TITLE
If - Else If - Testcafe ignoring the first condition of If Else If statement even if it's true

### ISSUE THREAD

**Issue by narpendranapit** [DevExpress/testcafe#2915]
### Are you requesting a feature or reporting a bug?
Issue

### What is the current behavior?
Currently first statement of If Else If not being executed even if it's conditions are matched. I tried by switching the order of statements and it always fails on first condition. 

### What is the expected behavior?
It should execute the first condition as well.

#### Provide the test code and the tested page URL (if applicable)
Test code

```js

// This is the part of js code for Login Page of my application in which when user logs in for the first time he can be asked any one of below mentioned question.

export default class webPage {
constructor () {
this.securityQuestion = Selector('#challengeQuestionLabelId');
this.securityAnswer   = Selector('#challengeSecurityAnswerId');
this.sportQuestion    = this.securityQuestion.withText('sports');
this.colorQuestion    = this.securityQuestion.withText('color');
this.phoneQuestion    = this.securityQuestion.withText('phone');

}
}
// This is the part of js code of the test file(testLogin.js) which will be validating above questions. 

this.webpage = new webPage();
this.dashboard = new DashboardPage(); // this is the second page of the application which opens up after successful login

async answerSecurityQuestion() { 
                 var myAnswer; 

                 if ( await this.webpage.colorQuestion.exists ) { 
                     myAnswer = "color1"; 
                 } else if ( await this.webpage.phoneQuestion.exists ) { 
                     myAnswer = "phone1"; 
                 } else {
                     myAnswer = "sports1"; 
                 }

await t
            .typeText(this.webpage.securityAnswer, myAnswer)
            .click(this.webpage.nextButton)
            .expect(this.dashboard.pageHeader.innerText).contains('Welcome');  // Once authentication is successful new web page (dashboard) should open up with header text as welcome. 
    }

```

### Specify your

* operating system: win 10
* testcafe version: 
* node.js version: v8.11.0

**Comment by AlexSkorkin** [comment]
I created a test with a similar scenario, but my attempts to replicate this behavior were unsuccessful. Would you please clarify to what you are referring by keyword 'this'? What do you mean by 'fails on first statement'? Is there any error message when the first statement is executed?

**Comment by AlexSkorkin** [comment]
Thank you for the update. Would you please clarify to what you are referring by keyword 'this'? You can figure this out by [debugging your test code](http://devexpress.github.io/testcafe/documentation/test-api/debugging.html#debugging-test-code). Is the 'webPage' page model is referenced properly? Does the selector return a proper element?

**Comment by narpendranapit** [comment]
Hi,

I have added `await t.wait(3000);` before first if statement and it's working as expected now.

But I still don't know why it's not working without it as I have "await" inside the statement as well.

Still if you can look into this and let me know why it's behaving like this will help me. 

**Would you please clarify to what you are referring by keyword 'this'?**

I have created a class in testLogin.js which i am calling from other test scripts as login is required in order to validate other ui elements. 

Below is the constructor code of the testLogin.js

`export default class loginSteps {

    constructor() {
        this.webpage = new webPage();
        this.dashboard = new DashboardPage();
    }`

As suggested I have used the t.debug() function and I am able to see the correct element using developer tools of the browser.

![image](https://user-images.githubusercontent.com/42864675/46390734-e28dd300-c6f6-11e8-9efa-dfd07876be79.png)

Also I have added below code to check if it's identifying right element or not and it is identifying it correctly.

`
        const securityquestiontext = await this.webpage.securityQuestion.textContent;
        console.log(securityquestiontext);
`
Below is the output in console
![image](https://user-images.githubusercontent.com/42864675/46391215-4addb400-c6f9-11e8-9c98-02b2ad3a576f.png)

**Comment by AlexSkorkin** [comment]
Hi,
Thank you for providing this information. It looks like the default selector timeout value is insufficient for your web page due to some delays on the server or your side. Instead of the wait statement, you can also tweak the [selector's timeout value](http://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/selector-options.html#optionstimeout). If this is not the case, please provide us with your complete test case and the URL you are testing, so we can also run it on our side.

**Comment by narpendranapit** [comment]
Thanks for assisting me with this issue. I have added another assertion before IF Else IF statements so that my code can get some more time to read the element on the security page.
