### ISSUE TITLE
Windows version detection is incomplete: the build number is missing

### ISSUE THREAD

**Issue by AlexSkorkin** [DevExpress/testcafe#2919]
### What is the current behavior?

Windows version is detected incompletely. The correct OS Windows version is 10.0.17134.137. However, the `browserProviderPool.getBrowserInfo` method from the `testcafe-browser-tools` package detects version as 10.0.0:

![image](https://user-images.githubusercontent.com/995726/46336280-0f78b200-c633-11e8-962f-fd2f0a3b597f.png)

![image](https://user-images.githubusercontent.com/995726/46336349-36cf7f00-c633-11e8-8212-77fb5074de7f.png)

The proper version is the following one:

![image](https://user-images.githubusercontent.com/995726/46336372-4353d780-c633-11e8-9613-5a7b06710902.png)

### What is the expected behavior?

The version is determined correctly as 10.0.17134.137.

### How would you reproduce the current behavior (if this is a bug)?

Run any test case on Windows 10 Version 1803 Build 17134.137.

### Specify your

* operating system: Windows 10 Version 1803 Build 17134.137
* testcafe version: 0.22.0
* node.js version: v10.4.0

**Comment by miherlosev** [comment]
It's not a bug. TestCafe displays the version which [useragent](https://www.npmjs.com/package/useragent) module retrieves from browser's `navigator.useragent` property.
