### ISSUE TITLE
0.22.1-alpha.2 broke testcafe-live

### ISSUE THREAD

**Issue by sorin-davidoi** [DevExpress/testcafe#2920]
### Are you requesting a feature or reporting a bug?

Bug.

### What is the current behavior?

Reloading a test doesn't work. Changes are picked up but the test doesn't restart (it gets stuck at `Test run is starting...`).

### What is the expected behavior?

Reloading a test in `testcafe-live` works.

### How would you reproduce the current behavior (if this is a bug)?

Run a test with `testcafe-live` and press `Ctrl-R` when it finished.

### Specify your

* operating system: `macOS`
* testcafe version: `0.22.1-alpha.2`
* node.js version: `v8.12.0`

**The bug is not present in `0.22.1-alpha.1`.**

I'm reporting it here since the regression happened in `testcafe`.

**Comment by AlexKamaev** [comment]
I was able to reproduce the issue only in two cases. 
1) A test does not restart if VSCode (I run tests via integrated terminal) is opened in full screen mode.
2) If I close the browser and then press Ctrl+R in terminal. 
However both these cases are reproducible with the previous TextCafe version. If you able to recreate the issue without any extra conditions, could you please clarify which macOC version you are using? In which browser are you executing the tests? Could you provide a simple test project or screencast that demonstrates the problem?

**Comment by sorin-davidoi** [comment]
It seems to be related to the number of tests:
 - if I place the attached test in `demo.ts` and run it with `testcafe-live firefox demo.ts`, reloading works just fine.
 - if I place the attached test it in `tests/demo.ts` (where `tests` contains ~60 other tests, none of which have `.only`) and run it with `testcafe-live firefox tests` reload doesn't work.

```ts
import { Selector } from 'testcafe';

fixture`Demo`.page('https://joinmastodon.org');

test.only('has get started button', async test => {
    await test.expect(Selector('a').withText('Get started').visible).ok();
});
```

macOS version: 10.13.0
Firefox version: 62.0.3 (though TestCafe reports it as 62.0.0)

**Comment by AlexKamaev** [comment]
Thank you for providing this information. My attempts to replicate it, however, were unsuccessful. I can confirm that it works really slowly with more than 150 files, but it still does not fail.
I've attached my screencast illustrating my steps. Would you please review it and let me know what steps I need to perform in order to replicate the issue? https://drive.google.com/file/d/1WQlsjNSBOWu5CzC9vEbItFCqejlJVmYY/view?usp=sharing

**Comment by sorin-davidoi** [comment]
I can't replicate it anymore 😕 (tested with exactly the same versions). Will close this now, thank you for taking the time to investigate!

**Comment by miherlosev** [comment]
Hi @pciavald

Thank you for the detailed description. I've reproduced the problem.
