### ISSUE TITLE
Using fixtureGrep option in gulp-testcafe or on runner instance.

### ISSUE THREAD

**Issue by rpolishetti** [DevExpress/testcafe#2922]
### Are you requesting a feature or reporting a bug?

feature

### What is the expected behavior?

We should be able to add this option as part of testcafe options in gulp task, so that we can pass a pattern code to run specific group of tests.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by miherlosev** [comment]
You can use the [filter](http://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#filter) option.
