### ISSUE TITLE
Inform a user that a click was made on a wrong element

### ISSUE THREAD

**Issue by AlexKamaev** [DevExpress/testcafe#2930]
When testcafe clicks an element which is overlapped by the second element, it waits for the first element to appear. If the first element do not appear during selector timeout period, then it clicks the second element.
It would be nice to inform users that a click is made on a wrong element.

```HTML
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title></title>
    <style>
        #parent {
            position: relative;
        }

        #child1 {
            width: 100px;
            height: 100px;
            background-color: blue;
            position: absolute;
            top: 0;
            left: 0;
        }

        #child2 {
            width: 400px;
            height: 400px;
            background-color: red;
            position: absolute;
            top: 0;
            left: 0;
        }
    </style>
</head>
<body>
    <div id="parent"></div>
    <div id="child1"></div>
    <div id="child2"></div>
</body>
</html>
```
```JS
fixture `fixture`
    .page `../pages/index.html`;

test(`test`, async t => {
    await t
        .click('#child1');
});
```

**Comment by AlexKamaev** [comment]
https://github.com/DevExpress/testcafe/issues/2861
Sometimes we cannot click on element inside a shadow root. See #2861 tests

**Comment by rob4629** [comment]
Can this be re-opened? I believe it still happens (we're seeing it occur on some of our tests while running against BrowserStack's iPhone 8.

**Comment by jbradenclickfunnels** [comment]
This is also an issue for us when we have a dynamic notification box display on top of elements we need to click. Instead of failing the test, TestCafe continues to find the element and try to interact with it again and again creating an infinite loop.
