### ISSUE TITLE
Try/Catch doesn't work if you have code after the catch statement

### ISSUE THREAD

**Issue by ericenders** [DevExpress/testcafe#2933]
### Are you requesting a feature or reporting a bug?
A bug

### What is the current behavior?
Try/Catch works if it is the end of the test or if there are other try/catch statements after.  The try/catch fails if there is code after the statement within that test.

### What is the expected behavior?
It is expected that you can have a try/catch anywhere within your test.  

### How would you reproduce the current behavior (if this is a bug)?
Write a test script that has a try catch statement with additional scripts after the statement.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: N/A

Test code

```js
try{
  t.expect(true).eql(false);
catch(err){
  console.log(err.errMsg);
}

t.expect(true).eql(true); //this will never be reached because it fails in the try statement
//if you wrap this in try/catch, it will work

```

### Specify your

* operating system: MacOS and Windows 10
* testcafe version:  0.21.1
* node.js version: 6.2.0

**Comment by ljowen** [comment]
Why do you want to use try catch may I ask?

**Comment by AlexKamaev** [comment]
I don't recommend this approach. Using assertions inside a try-catch block can lead to incorrect assertion processing by testcafe. I think the best way to solve the issue is to reorganize tests in the following manner:
```JS
test(`1`, async t => {
    const a = true;
    const b = false;
    const c = 4;
    const d = 5;
    try {
        await t.expect(a).eql(b);
    }
    catch(err){
        console.log(err.errMsg);
    }
    try {
        await t.expect(c).eql(d);
    }
    catch(err){
        console.log(err.errMsg);
    }
});
```

```JS
test(`2`, async t => {
    const a = true;
    const b = false;
    const c = 4;
    const d = 5;

    const actual = { prop1: a, prop2: c };
    const expected = { prop1: b, prop2: d };

    await t.expect(actual).eql(expected);
});
```
In the second test, I replaced multiple assertions by the single one which deeply checks an expected object with many properties.
