### ISSUE TITLE
Add option to disable saving log messages to local storage

### ISSUE THREAD

**Issue by eljenso** [DevExpress/testcafe#2942]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
When something is logged to the browser console, testcafe will save this to local storage.
These messages can be accessed via `t.getBrowserConsoleMessages()`.
See: http://devexpress.github.io/testcafe/documentation/test-api/accessing-console-messages.html

### What is the expected behavior?
This is the expected behavior but problems occur if the application logs big messages to the console.
These might exceed the local storage limit. This is what happened in #2895.

We added a workaround in our tests which runs the following code before every test (during user setup):
```js
/**
 * Prevent testcafe from saving console logs to local storage
 * Logs can become pretty big, fill up local storage and break testcafe
 */
const disableTestcafeLogStorage = ClientFunction(() => {
  // _onConsoleMessage is testcafe's method which saves all logs to localstorage
  window["%testCafeDriverInstance%"]._onConsoleMessage = () => {};
});

await disableTestcafeLogStorage();
```

Hence, I'd like to have an option to disable (or maybe limit) storage of console messages at the cost of not being able to use `t.getBrowserConsoleMessages()` (which we do not use anyway).

### Specify your

* operating system: Fedora 28
* testcafe version: 0.22.0
* node.js version: 10.11.0

**Comment by link89** [comment]
Hi @miherlosev we have the problem recently. It would be good if testcafe can provide an option to disable this feature.
