### ISSUE TITLE
ERROR Was unable to open the browser due to error.

### ISSUE THREAD

**Issue by cormac-dunphy** [DevExpress/testcafe#2944]
### Are you requesting a feature or reporting a bug?

reporting a bug

### What is the current behavior?
test wont run because is 'unable to open browser'

### What is the expected behavior?
test to run

### How would you reproduce the current behavior (if this is a bug)?
try to run "testcafe chrome test.js" from the terminal

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: server

Test code

```js
'test.js'
import Page from './page-model';
import { Selector } from 'testcafe';

fixture `Testing front end`
    .page `http://10.10.1.2`;

// Page model
const page = new Page();

// Tests
test('check if sidebar exists', async t => {
    await t
        .expect(Selector("#sidebar").visible).ok();
});

'page-model.js'
import { Selector } from 'testcafe';

const label = Selector('label');

export default class Page {
    constructor () {
        this.sidebar = Selector('#sidebar');
      }
    }

```

### Specify your

* operating system: osx
* testcafe version: 0.22.0
* node.js version: 8.9.2

**Comment by miherlosev** [comment]
I am afraid this information is not sufficient to find the cause of the issue. Could you please provide a page or a small example so that we can reproduce it on our side?

**Comment by cormac-dunphy** [comment]
I am running this test inside a vagrant vm would this have anything to do with why testcafe cant detect any browsers when i run "testcafe -b"

**Comment by miherlosev** [comment]
I don't think that running your tests in a Vargant VM is the cause of the problem. Only the operation system and the list of the installed browsers can affect the work of the 'testcafe -b' command.
Would you share your Vargant VM image?

**Comment by cormac-dunphy** [comment]
got it working it was because i didnt have a browser installed in the vm. thanks

**Comment by miherlosev** [comment]
I am glad to hear this. I've created a separate [issue](https://github.com/DevExpress/testcafe/issues/2947) to improve the 'Unable to find the browser' message of the CLI interface.
