### ISSUE TITLE
Test execution with concurrency or multiple browsers fails in Docker container (Linux)

### ISSUE THREAD

**Issue by jmullo** [DevExpress/testcafe#2946]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

Running tests with headless Firefox & headless Chrome.

Test execution fails if c > 1.
Test execution fails if c = 1 and both browsers used.

Test execution succeeds if c = 1 and only headless Firefox used.
Test execution succeeds if c = 1 and only headless Chrome used.
Test execution succeeds with any combination when running in Windows 7 and no Docker container.

"Error: The Firefox 60.0.0 / Linux 0.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues."

### Specify your

* operating system: Docker container running CentOS 7
* testcafe version: 0.22.0
* node.js version: v8.12.0

**Comment by jmullo** [comment]
Ah, only now noticed the --shm-size option. Increasing it seems to have fixed the issue.
You can remove "It usually happens when you run tests in Chromium." from the documentation, because it seems to affect Firefox as well.

**Comment by miherlosev** [comment]
> You can remove "It usually happens when you run tests in Chromium." from the documentation, because it seems to affect Firefox as well.

Yes, you are right. It's not related to the Chromium browser.
@VasilyStrelyaev remove the "It usually happens when you run tests in Chromium." phrase from [Using TestCafe Docker Image](http://devexpress.github.io/testcafe/documentation/using-testcafe/using-testcafe-docker-image.html) topic.
