### ISSUE TITLE
The Screenshot Pattern example doesn't work on Unix shells

### ISSUE THREAD

**Issue by bryant-sfdo** [DevExpress/testcafe#2952]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

Screenshots that are saved on failure with pattern provided doesn't work.

Running the following test with the following command:

test.js:

```js
import { Selector } from "testcafe";

fixture("test").page("https://google.com/");
const foo = Selector("#topabar");
const bar = Selector("#appbar");
const logo = Selector("#logo");
test("Fail", async t => {
  await t
    .typeText("[title='Search']", "foobar")
    .expect(1)
    .eql(2);
});


```

command ran: 
`testcafe chrome test.js -e -S -s screenshots -p "${DATE}_${TIME}/test-${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.png"`

NOTE: the pattern was taken from here: http://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-p---screenshot-path-pattern
### What is the expected behavior?
That the correct pattern is used when screenshots are taken during failure.

### How would you reproduce the current behavior (if this is a bug)?

Create the file provide and run the command provided.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: google.com

Test code

```js
import { Selector } from "testcafe";

fixture("test").page("https://google.com/");
const foo = Selector("#topabar");
const bar = Selector("#appbar");
const logo = Selector("#logo");
test("Fail", async t => {
  await t
    .typeText("[title='Search']", "foobar")
    .expect(1)
    .eql(2);
});


```

### Specify your

* operating system: mac os x
* testcafe version: v0.22.1-alpha.3
* node.js version: v9.2.1

**Comment by bryant-sfdo** [comment]
This is what I see when running test with -p provided.
![image](https://user-images.githubusercontent.com/37118738/46704856-c0f28700-cbe1-11e8-96da-d8fcee283a3f.png)

**Comment by AndreyBelym** [comment]
@bryant-sfdo, you should use single quotes on macOS around screenshot pattern. The pattern syntax is similar to the shell's variable expansion syntax, so you have to disable the variable expansion using the single quotes around the path pattern:
```
testcafe chrome test.js -e -S -s screenshots -p '${DATE}_${TIME}/test-${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.png'
```

We should note this in documentation.
