### ISSUE TITLE
Test is not working with IE.11

### ISSUE THREAD

**Issue by Turkirafaa** [DevExpress/testcafe#2955]
### Are you requesting a feature or reporting a bug?
Yes

### What is the current behavior?
Erorr with IE.11 

### What is the expected behavior?
Test are working 

### How would you reproduce the current behavior (if this is a bug)?
Test is not passing 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code
```
fixture `Test`
    .beforeEach(async t => {
        await t.useRole(Users.test)
               .navigateTo(baseUrl)
    });

test('1', async t => {
      await t
          .expect(Selector('*').withText('test').exists).ok()
});

test('2', async t => {
    await t.click('.carousel-card-text-container')
           .expect(Selector('.sub-nav').exists).ok()
});

for (let i=0; i< 2; i++) {
    const carouselCards = Selector('.carousel-card');
    test(`Access material ${i}`, async t => {
        const card = await carouselCards.nth(i);
        const text = await card.find('.carousel-card-title').innerText;
        await t.click(card)
               .expect(Selector('.course-title').withText(text).exists).ok()
    });
}


``````js

```

### Specify your

* operating system: Windows
* testcafe version:0.22.0
* node.js version:v8.12.0

**Comment by ljowen** [comment]
What is the failure you're seeing? Have you tried increasing Selector / Assertion timeouts?

**Comment by miherlosev** [comment]
I am afraid this information is not sufficient to find the cause of the issue. Could you please provide a page or a small example so that we can reproduce it on our side?

**Comment by Turkirafaa** [comment]
Thank you for assistent Problem solved
