### ISSUE TITLE
provide delay in browser start time

### ISSUE THREAD

**Issue by kumarkullan** [DevExpress/testcafe#2961]
### Are you requesting a feature or reporting a bug?
Feature:
I need to provide a time delay in browser start sequence (Testcafe Runner file)

### What is the current behavior?
 .browsers(['chrome','edge','firefox','ie'])

All the browsers will start at same time but I do not want this way, instead I would like to provide a little bit delay in browser starting sequence to avoid duplicate records insert. 

### What is the expected behavior?
  .browsers('chrome')
  .browsers('edge --delay time 4000ms')
  .browsers('ie --delay time 500ms')
  .browsers('firefox --delay time 500ms')
OR  
 .browsers(['chrome ','edge delay 2000','firefox delay 2000','ie delay 2000'])

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Windows 10
* testcafe version:0.22.0
* node.js version:8.11.4

**Comment by AndreyBelym** [comment]
Could you please tell more about your case? For me it looks like that you can just use some [Promise-based Mutual Exclusion Pattern](https://thecodebarbarian.com/mutual-exclusion-patterns-with-node-promises) or the [t.wait](https://devexpress.github.io/testcafe/documentation/test-api/pausing-the-test.html) action in your test code.

**Comment by kumarkullan** [comment]
Thank you so much for your response.
Please look into the below code: *I need to add a wait statement between 2
browsers start time in runner function.*

const fs = require('fs');
const stream = fs.createWriteStream(__dirname+'/reports/' + new
Date().getTime() + '.html');

const createTestCafe = require('testcafe');
let testcafe = null;
let runner = null;

   createTestCafe('localhost', 1337, 1338)
    .then(tc => {
        testcafe     = tc;
        runner =   testcafe.createRunner();

        return  runner

    .src(['test.js])

           * .browsers('chrome')*

*             await t .wait(5000) =====> If its a testcase, we can add a
wait statement but we are in runner function, how can we provide wait time
between two browsers? *
*                                                           I would like
delay a bit my second browser start time.   *
        *    .browsers(['edge'])          *

            .screenshots('./screens/', true)
            .reporter('phil', stream) // <-
            .reporter('minimal') // <-
            .run(
                {
                    selectorTimeout: 50000,
                    assertionTimeout:50000,
                    pageLoadTimeout: 80000,
                }
            );
    })

  .then(numFailed => {
    console.log('finished with ', numFailed, ' errors');
     testcafe.close(); //normally the process exits about 2 seconds after
this. now we need process.exit(0)
     if(numFailed){
       process.exit(1);
     }
   }, err => {
     console.error(err);
     testcafe.close();
     process.exit(1);
   });

**Comment by AndreyBelym** [comment]
You can't use test actions in regular Node.js files. If you really need to add a delay before a browser is opened, you can create a `*.bat` or `*.sh` script that will suspend its execution for some time and then start the browser. Then you can start the script using the [Path Browser Provider](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#portable-browsers).

But I think that it's a very bad practice when your tests depend when browsers are started. Additional delays can be introduced by network  and activity of another running apps, AV software can start scanning browser's executable files, etc. All these delays can easily mitigate the effect of delays created by your code, making the test suite fragile and unpredictable. If you describe me why you actually need to control browser starting behavior, maybe I will figure out a better solution.

**Comment by kumarkullan** [comment]
Thank you so much for your response. Thanks!

**Comment by AndreyBelym** [comment]
So it seems as resolved now.
