### ISSUE TITLE
When running under testcafe + chromium, page cannot access chrome.runtime object

### ISSUE THREAD

**Issue by bard** [DevExpress/testcafe#2968]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

The `chrome.runtime` object is not available if the page is being loaded in testcafe.

### What is the expected behavior?

The`chrome.runtime` is available under testcafe as it is when page is running outside of testcafe.

### How would you reproduce the current behavior (if this is a bug)?

Code below

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: any

Test code:

```js
import { ClientFunction } from 'testcafe'

fixture `Example`
  .page('https://google.com')

const chromeAPI = ClientFunction(() => window['chrome'])
const chromeRuntimeAPI = ClientFunction(() => window['chrome'].runtime)

test('Can access the chrome API', async t => {
  await t
    .expect(chromeAPI()).ok() // => success
})

test('Can access the chrome.runtime API', async t => {
  await t
    .expect(chromeRuntimeAPI()).ok() // => failure
})
```

### Specify your

* operating system: Arch Linux
* testcafe version: 0.22.0
* node.js version: 10.11.0

**Comment by AndreyBelym** [comment]
I can't find it the Chrome documentation, but it seems that Chrome allows access to the `chrome.runtime` API only for the following conditions:

1. If page's origin is `localhost`;
2. If page's protocol is HTTPS.

So you can use the [hostname](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--hostname-name) option to serve your test pages on the `localhost`, or get a HTTPS certificate and [serve your test pages over the HTTPS protocol](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/connect-to-the-testcafe-server-over-https.html).

**Comment by bard** [comment]
Absolutely correct. Thank you for pointing me in the right direction!
