### ISSUE TITLE
`setNativeDialogHandler` ignored when `useRole` redirects to login page

### ISSUE THREAD

**Issue by NickCis** [DevExpress/testcafe#2969]
### Are you requesting a feature or reporting a bug?
Reporting a bug

### What is the current behavior?
If the tested page has a listener to `beforeunload` (which returns a string), `setNativeDialogHandler` is set up, and `useRole` is used, the test will always fail (**note:** only the tested page has the `beforeunload` listener, not the login one!).

Console output:
```
npm test                                                                                                                                                                                    

> testcafe-setNativeHandler-userRole-bug@0.0.1 test /tmp/1ca33e22641c9d6dda1fc88c4de49c3a
> testcafe chromium test.js --app 'npm start'

 Running tests in:
 - Chrome 69.0.3497 / Linux 0.0.0

 Home
 ✖ My first test

   1) - Error in Role initializer -
      A native beforeunload dialog was invoked on page "http://localhost:8080/", but no handler was set for it. Use the "setNativeDialogHandler" function to introduce a handler function for native dialogs.

      Browser: Chrome 69.0.3497 / Linux 0.0.0



 1/1 failed (1s)
npm ERR! Test failed.  See above for more details.
```

### What is the expected behavior?
`setNativeDialogHandler` function is used, and `useRole` is performed correctly.

#### Provide the test code and the tested page URL (if applicable)
Test case can be found on this [gist](https://gist.github.com/NickCis/1ca33e22641c9d6dda1fc88c4de49c3a):

```
git clone https://gist.github.com/NickCis/1ca33e22641c9d6dda1fc88c4de49c3a
cd 1ca33e22641c9d6dda1fc88c4de49c3a
npm install && npm test
```

A quick workarround is navigating to a page that hasn't attached the `beforeunload`:

```js
await t
   .setNativeDialogHandler( ... )
   .navigateTo('about:blank')
   .useRole(user)
   .navigateTo(url);
```

### Specify your

* operating system: `Arch Linux (Kernel 4.18.12)`
* testcafe version: `0.22.0`
* node.js version: `v10.0.0`

**Comment by NickCis** [comment]
Digging a little further, the problem may originate as in [role's initialization](https://github.com/DevExpress/testcafe/blob/e7790ccad7a67b3962d7df16c117c88144faed04/src/role/index.js#L61) the test run is [switched to a clean state](https://github.com/DevExpress/testcafe/blob/master/src/test-run/index.js#L604) (which cleans testrun's `activeDialogHandler`)  before navigating to the login page.

Shouldn't the correct behaviour be?:
1. Redirect to an empty page (something like `.navigateTo('about:blank')`, idk if `about:blank` is available across all browsers or the proxy should provide an empty page)
2. Switch to Clean state
3. Redirect to Login page

**Comment by AlexKamaev** [comment]
I've reproduced the issue. We'll see how we can improve this behavior. For now I recommend you use your workaround. In addition you can modify it in the following manner:

```JS
import { Role, Selector } from 'testcafe';

const url = 'http://127.0.0.1:8080';

const user = new Role(`${url}/login.html`, async t => {
    await t
        .typeText('#user', 'user')
        .typeText('#password', 'password')
        .click('#submit');
});

fixture('Home')

test('My first test', async t => {
    await t.setNativeDialogHandler((...args) => {
        console.log('handler', args);
        return true;
    });
    await t.useRole(user);
});
```
I've removed page declaration in the fixture. It'll start test from `about:blank` page so `beforeunload` will not be raised.

**Comment by NickCis** [comment]
The example was just to provide a test escenario. In the real escenario, all the site's pages set `beforeunload` when you are logged in, i'm trying to test interaction between two users so this was constantly failing.

I am eager to provide a PR with a fix, but idk what would be the correct approach :)

**Comment by AlexKamaev** [comment]
As you previously mentioned, the issue occurs because test run is switched to a clean state before navigating to the login page. I think it is too early, so the correct approach will be to move `switchToCleanRun` after navigating to the login page. In this case, navigation will be processed correctly. In addition, you will need to change your test and add the `setNativeDialogHandler` method to a role initializer. So, modify your test in the following manner:
```JS
const user = new Role(`${url}/login.html`, async t => {
    await t.setNativeDialogHandler(...)
    ...
});

fixture('Home')

test('My first test', async t => {
    await t.setNativeDialogHandler((...args) => {
        console.log('handler', args);
        return true;
    });
    await t.useRole(user);
});
```
You are welcome to make a PR with a fix if you want.

**Comment by NickCis** [comment]
If i navigate to the login page before switching to a clean run won't have the test run in an invalid state? (particularly regarding the current session).

Isn't preferable to perform a navigation to a blank page, then switch to a clean run and finally perform the navigation to the login page?

**Comment by NickCis** [comment]
The problem of first navigating to the login page and then switching to a clean state is that the login page is loaded with the last used role. This will be a problem if the login page response depends on whether a user is logged or not.

For example:

```js
const userA = ...;
const userB = ...;

test('Chat', async t => {
  await t
    .setNativeDialogHandler(() => true)
    .useRole(userA)
    // ...
    .useRole(userB); // -> Fails as the login screen is loaded with userA session, so no login button is found
});
```

This test fails as the login page is loaded with `userA` session.

This is why i'm suggesting to do:

1. Redirect to an empty page (something like .navigateTo('about:blank'), idk if about:blank is available across all browsers or the proxy should provide an empty page)
2. Switch to Clean state
3. Redirect to Login page

**Comment by AlexKamaev** [comment]
We'd like to avoid navigating to the `about:blank` page, so it's better to call `switchToCleanRun` after `_navigateToLoginPage`. As you correctly mentioned in your case there will be a problem with login page, however it can be solved if you clear storages before the navigating. Something like that:
```JS
testRun.session.useStateSnapshot(null);
await this._navigateToLoginPage(testRun);
await testRun.switchToCleanRun();
```

**Comment by marcinlesek** [comment]
@AlexKamaev is this issue still valid? I'm occurred this same issue now as @NickCis.

**Comment by AlexKamaev** [comment]
@marcinlesek 
Yes, the issue still exists. I think we can fix it in the near future. Meanwhile, you can use one of the workarounds described above.

**Comment by marcinlesek** [comment]
@AlexKamaev unfortunately, this workarounds mentioned here doesn't work for my case. Let's assume case as below (I couldn't pass urls to app because it's internal):

```js
// ...

const signInPage = 'https://example.com';
const userData = {
  email: 'email@email.com',
  password: 'password',
};

const signIn = async (email, password) => {
  const signInPage = new SignInPage();

  await t.setNativeDialogHandler(() => true); // With or without
  await signInPage.signIn(email, password);
};

const user = Role(
  signInPage,
  async () => signIn(userData.email, userData.password)
);

const pageWithNativeDialog = 'https://...';
const authCredentials = { ... };
const hook = new Hook(...);

fixture`role mechanics`
  .page(pageWithNativeDialog)
  .httpAuth(authCredentials)
  .requestHooks(hook);

test('test role mechanics', async (t) => {
  const myPage = new MyPage();
  const userPage = new UserPage();
  await t.setNativeDialogHandler(() => true); // With or without

  await myPage.firstAction();
  await myPage.secondAction();

  await t
    .setNativeDialogHandler(() => true) // With or without
    .useRole(user);

  await userPage.firstActionAsUser();
  await userPage.secondActionAsUser();
});
```

This case example made me, that test is performing actions on `myPage`, after that `signInPage` is appearing but nothing happened and after timeout, I got error about incorrectly set nativeDialogHandler:

```
1) - Error in Role initializer -
      A native beforeunload dialog was invoked on page
      "http://localhost:5000/", but no handler was set for it. Use the
      "setNativeDialogHandler" function to introduce a handler function for native dialogs.

      Browser: Chrome 74.0.3729 / Mac OS X 10.14.4
```

Any ideas how we could workaround this?

Thanks in advance!

Best,
Marcin

**Comment by AlexKamaev** [comment]
@marcinlesek 
It's difficult to give any advice without a working project. If you want, you can send detailed information about your project (full test code, url, credentials, etc) at support@devexpress.com.
Also I want to mention that I added this issue into the current milestone, so this means that we have plans to fix it in the near future.

**Comment by marcinlesek** [comment]
@AlexKamaev thanks for answer. Unfortunately, I couldn't provide any informations about project, above example is the most similar I could provide. Thanks for adding this issue to your current sprint, I hope it'll be fixed soon so we'll have opportunity to start using roles on our daily basis.

Best,
Marcin
