### ISSUE TITLE
Testcafe stops after redirects and ignore the rest of code

### ISSUE THREAD

**Issue by poliscukmykola** [DevExpress/testcafe#2972]
### Are you requesting a feature or reporting a bug?
BUG (not sure about that)

### What is the current behavior?
FYI: I can say, that I am have some experience with testcafe. Anyway, I will try to describe my issue as much as possible. 

In my work I am currently working on a automated test where before I can run tests I have to build code for UI which runs on localhost:4200/... , also start a local server containing manager for our application model on localhost:5000 which has also api/1 which is really important for me.
Issue begins, when I finish all those verification in tests and I have to navigate from localhost:4200/xxx to localhost:5000/api/1/xxx/xxx. So when the testcafe runs on localhost:4200, everything works fine, then I use navigateTo() function to redirect to localhost:5000/api/1/xxx/xxx, Testcafe is succesfully redirected and it loads the image, which is correct, but unfortunately testcafe stops right after redirect, browser is still present, bottom bar disappears and code the rest of the code is ignored, but after some time like 2-5 min, testcafe timeouts with message **ERROR The Chrome 69.0.3497 / Windows 7 0.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.** The biggest mystery for me, is why it just stops like this. In Developer tools (Chrome) no console errors, no network issues. 

If it is not a BUG, please give me at least any explanation, what is wrong or what I am doing wrong. Thanks!

### What is the expected behavior?
Expected behavior for my case is that, it should be able to navigate to any URL, even localhost without any issue

#### Provide the test code and the tested page URL (if applicable)
Tested page URL:
Test code

```ts

const localhost = 'http://localhost:5000/api/1/mime/';
const jpgMime = 'MyEnterprise.jpg.value';

// verify Mime
    await t
    .navigateTo(localhost + jpgMime)
    .expect(po.getImage(jpgMime).visible).ok();

```

### Specify your
* operating system: Windows 7 0.0.0
* testcafe version: 0.20.0
* node.js version: v8.11.4

**Comment by poliscukmykola** [comment]
@AndreyBelym Thanks a lot for reply. I will try it!

**Comment by miherlosev** [comment]
As far as I understand, you are trying to navigate to a non-html page.
@AndreyBelym provided the necessary information.
So, I will close this issue.
 
If you have additional questions, please address them in separate issues.
