### ISSUE TITLE
Testcafe doesn't work with Hellosign

### ISSUE THREAD

**Issue by jelling** [DevExpress/testcafe#2985]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?

Our original problem was that Testcafe could not click on any elements in an iframe created by Hellosign even after switching to that iframe.

To demonstrate the issue, I asked Hellosign for a test page. I recorded a test against it using Test Cafe but it errors immediately when trying to replay. I modified the code to test simple selectors and even those fail. 

I suspect there is something block testing of this iframe as a whole. Test Cafe otherwise works well for us. 

### What is the expected behavior?

Can find selectors, click on items, and sign document

### How would you reproduce the current behavior (if this is a bug)?

Run the below code 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://app.hellosign.com/api/embeddedTest

Test code

```js
import { Selector } from "testcafe";

fixture`Hellosign Embed Test`.page`https://app.hellosign.com/api/embeddedTest`;

test("hellosign modal", async t => {
    await t
        // A few obvious selectors that didn't work:
        // .expect(Selector("div").withText("Embedded Testing Tool").exists) // doesn't work
        // .expect(Selector("h3").withText("Embedded Url").exists); // doesn't work either

        // Everything below was generated by Testcafe Record, still doesn't work
        // .click(Selector("span").withText("GET A SAMPLE DOCUMENT")); // tried lowercase as well, doesn't work
        .switchToIframe(Selector("#hsEmbeddedFrame"))
        // .wait(5000)
        .click(Selector("span").withText("GET STARTED"))
        .click(
            Selector("#component_1721320110_1")
                .find("span")
                .withText("Click to sign")
        )
        .click(
            Selector(".m-sign-modal--menu--item--label")
                .nth(1)
                .find("span")
                .withText("Type it in")
        )
        .click(Selector("#insertButton"))
        .click(
            Selector(".l-nowrap")
                .find("span")
                .withText("CONTINUE")
        )
        .click(
            Selector(".l-nowrap")
                .find("span")
                .withText("I AGREE")
        )
        .click(
            Selector(".l-nowrap")
                .find("span")
                .withText("CLOSE")
        );
});


```

### Specify your

* operating system: Chrome 69.0.3497 / Mac OS X 10.13.6
* testcafe version: 0.3.0
* node.js version: v10.8.0

**Comment by AlexKamaev** [comment]
I've modified your testcode and it works now:

```JS
import { Selector } from 'testcafe';

fixture`Hellosign Embed Test`.page`https://app.hellosign.com/api/embeddedTest`;

test('hellosign modal', async t => {
    await t.wait(1000);
    await t.click(Selector('span').withText('GET A SAMPLE DOCUMENT'));
    await t.click(Selector('span').withText('LAUNCH EMBEDDED PAGE'));

    await t.expect(Selector('div').withText('Embedded Testing Tool').exists).ok();
    await t.expect(Selector('h3').withText('Embedded URL').exists).ok();

    await t.switchToIframe(Selector('#hsEmbeddedFrame'));
    await t.setNativeDialogHandler(() => true);
    await t.click(Selector('span').withText('GET STARTED'));
});
```
I also noticed several mistakes:
1. `.expect(Selector("div").withText("Embedded Testing Tool").exists)` - use ok() as in my code.
2. `.expect(Selector("h3").withText("Embedded Url").exists);` - the `withText` argument is case-sensitive.
3. I've found that some errors occur on the test page. To ignore them, please add the `-e` param to the cli command.
