### ISSUE TITLE
Feature Request: Add ability to mock only part of a response

### ISSUE THREAD

**Issue by bdwain** [DevExpress/testcafe#2991]
### What is your Test Scenario?
I would like to test a scenario where a certain field is set in the response my page gets from the server.

### What are you suggesting?
Rather than mocking out the whole response, which contains a lot of data and would be difficult, it would be nice to be able to have something in RequestMock that let me change only part of the response. for example, something like this.

```js
RequestMock().onRequestTo(/foo/).respond((req, rsp) => {
  const newBody = rsp.getBody();
  newBody.testField = true;
  rsp.setBody(newBody);
});
```
This way I don't have to worry about mocking the rest of the response from /foo.

### What alternatives have you considered?
Mocking the entire response, which can be difficult.

**Comment by miherlosev** [comment]
Hi @bdwain 

A response consists of two parts: a body and headers. A [pull request](https://github.com/DevExpress/testcafe-hammerhead/pull/1790) that allows modifying response headers is already in progress.
Does it suit your needs? Or, do need to modify a request body too?

**Comment by bdwain** [comment]
I was hoping to change the body too.

**Comment by miherlosev** [comment]
We know a user case for which it's  necessary to change response headers (https://github.com/DevExpress/testcafe-hammerhead/issues/1657#issuecomment-427021262).
Would please clarify a real use case for which you need to change the response body?

**Comment by bdwain** [comment]
the service i hit when i log in to my app returns a bunch of data in the form of a big object. One of the fields, foo, has a big impact on the login process, and I would like to test specifically the case when foo is true. If i can't modify the response, I'll have to mock the entire thing, which is hard because there's a lot of specific data in there. It's also hard to set up the backend so that foo is true, and would be easier to just mock it.

**Comment by GeneGenie** [comment]
+1 for me. 

# What I'm doing: 
I'm writing e2e tests for AdSDK. And I'd like to modify single field in ad response to test different scenarios. 

# Why I can't mock the whole body: 
Ad request includes a lot of fields that are generated in runtime by "thirdParty" script, those IDs should also be present in response. 


PS: actually  I could mock the whole body, if I could get request body in test runtime.

**Comment by AlexKamaev** [comment]
We discussed this with the team and decided to close the issue, since we do not have plans to implement this.
