### ISSUE TITLE
Canvas support

### ISSUE THREAD

**Issue by wangyan-9067** [DevExpress/testcafe#2992]
### Are you requesting a feature or reporting a bug?
feature

### What is the current behavior?

I'm developing an HTML5 game with canvas. When trying to use this tool to do automation testing, I can only select the "canvas" tag and apply (x, y) offset in the click event. It's not quite convenient especially the app supports multiple devices.

### What is the expected behavior?

I use a third party library Egret (https://www.egret.com/en/) to create and render elements on canvas. It provides different elements like rectangle, image, button etc and uses xml files to describe the parent-child relationship of them. Is there anyway testcafe can support canvas more powerfully instead of click offset?

**Comment by miherlosev** [comment]
At present, we don't have plans to extend the Selector's features for a canvas element.
There is no common way to get component tree is drawing on `canvas`.
However, you can try to implement this by using the [Extending Selectors mechanism](http://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/extending-selectors.html.).
This mechanism is used by [TestCafe React Selectors](https://github.com/DevExpress/testcafe-react-selectors), [TestCafe Angular Selectors](https://github.com/devexpress/testcafe-angular-selectors) and [TestCafe Vue Selectors](https://github.com/devexpress/testcafe-vue-selectors).
