### ISSUE TITLE
testcafe-angular-selectors: does not supported angular 6

### ISSUE THREAD

**Issue by bertheto** [DevExpress/testcafe#2993]
### What is your Test Scenario?
* try to use testcafe-angular-selectors with angular 6 
 I use :  await waitForAngular();
 result : 
An error occurred in ClientFunction code:
      Error: Cannot find Angular in development mode.

### What is the Current behavior?
Angular 6 not supported using  testcafe-angular-selectors .
 
### What is the Expected behavior?
Angular 6 supported.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
fixture `tnt Admin login`
  .page('http://toto.page-7w2:8080/');

test('Login', async ( t: any) => {
  await t
    .typeText('#username', 'toto').typeText('#password', 'toto')
    .click('#login-submit');
  await t.expect(Selector('div.ng-star-inserted > h2').innerText).eql('Welcome admintoto');
  // await waitForAngular();
  const env: Selector = Selector('.title').withText('tnt Admin for toto');
  const exist: boolean = await env.exists;

  t.expect(exist);
  await t
    .click(env);
  await waitForAngular();
});
</details>

<details>
<summary>Your complete test report:</summary>

Running tests in:
 - Chrome 69.0.3497 / Windows 7 0.0.0

 tnt Admin login

 × Login

   1) An error occurred in ClientFunction code:

      Error: Cannot find Angular in development mode.

      Browser: Chrome 69.0.3497 / Windows 7 0.0.0

         21 |  const exist: boolean = await env.exists;
         22 |
         23 |  t.expect(exist);
         24 |  await t
         25 |    .click(env);
       > 26 |  await waitForAngular();
         27 |});
         28 |
         29 |

         at Object.<anonymous> (C:\work\SAAS\tnt-admin\ui\TestCafe\specification.ts:26:9)
         at fulfilled (C:\work\SAAS\tnt-admin\ui\TestCafe\specification.ts:4:58)

</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

launch the test
 
### Your Environment details:
 
* testcafe version:                   0.22.0
* node.js version:                    v8.9.4
* command-line arguments:  testcafe chrome TestCafe/specification.ts
* browser name and version: Chrome 69.0.3497 
* platform and version:          Windows 7 0.0.0

**Comment by miherlosev** [comment]
According to the [documentation](https://github.com/DevExpress/testcafe-angular-selectors/blob/master/angular-selector.md#wait-for-application-to-be-ready-to-run-tests), you need to put the `waitForAngular` method into the [beforeEach](http://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#test-hooks) fixture hook. 
If my suggestion doesn't fix the problem, please create a separate issue in the [testcafe-angular-selectors](https://github.com/devexpress/testcafe-angular-selectors) repository and attach to it an Angular application with which I can reproduce the problem.
