### ISSUE TITLE
Assertions caching failure when wrapped with try/catch

### ISSUE THREAD

**Issue by tamlyn** [DevExpress/testcafe#2996]
I'm getting very unexpected behaviour when catching an assertion error from TestCafe.

```js
fixture('Assertions')

test('Caches failure', async t => {
  try {
    await t.expect('apples').eql('oranges')
  } catch (e) {
    console.log(1, e.errMsg)
  }

  try {
    await t.expect('apples').eql('apples')
  } catch (e) {
    console.log(2, e.errMsg)
  }
})

```

Output:
```
 Assertions
1 'AssertionError: expected \'apples\' to deeply equal \'oranges\''
2 'AssertionError: expected \'apples\' to deeply equal \'oranges\''
 ✓ Caches failure
```

Needless to say I would expect `t.expect('apples').eql('apples')` to pass and therefore only one message to be logged to the console.

It seems that once an assertion has failed, all other assertions in the same test will fail with the same message, even if the thing being asserted is true (like `apples` to `apples` above). I'm aware that TestCafe does a bunch of good magic with its assertions and promises but this seems like the other kind of magic. It certainly magicked away my morning.

**Comment by AlexKamaev** [comment]
All testcafe API methods add their commands to one chain of promises via the `then` method. This means that if an error occurs in one method of the chain, further methods will also catch the same error. For example, I've rewritten your test with other commands and it behaves in the same manner:
```JS
test('Caches failure', async t => {
    try {
        await t.click('non-existing element');
    } catch (e) {
        console.log(1, e.apiFnChain);
    }
    try {
        await t.click('body');
    } catch (err) {
        console.log(2, err.apiFnChain);
    }
});
```
I recommend you avoid using try/catch blocks with testcafe API methods. Could you please explain why you need the described use case?

**Comment by tamlyn** [comment]
I see, thanks.

What I was trying to do is replicate the auto retry logic because I need to assert on the presence of a file in a mock SFTP server but there's nothing in the UI to indicate when it's uploaded. I created the following helper function:

```js
const autoRetry = async (fn, timeout = 5000, delay = 100) => {
  const start = Date.now()
  while (true) {
    try {
      return await fn()
    } catch (err) {
      if (Date.now() > start + timeout) {
        throw err
      }
      logger.debug(`Auto retrying failed assertion:`, err.message || err.errMsg)
    }
    await new Promise(resolve => setTimeout(resolve, delay))
  }
}
```

Which I can use like 

```js
await autoRetry(() => {
  assert.strictEqual(mockFs.readdirSync('/test'), ['expected.file'])
})
```

This works fine when using Node `assert` instead of TestCafe `expect` so that's what we're doing.

Incidentally, it would be neat if we could piggy back on TestCafe's retry logic for stuff like this.
