### ISSUE TITLE
Get proxy credentials from environment variables

### ISSUE THREAD

**Issue by arnaud** [DevExpress/testcafe#2997]
### What is your Test Scenario?

I'd like to do automated non-regression testing for a big corp from within its **proxy-enabled internal network**. This corp relies on an authenticated proxy that requires command-line users to do something like this:

```
testcafe --proxy user:password@proxy:port chrome test.js
```

This issue here being we don't want to create a NRT solution that **includes credentials in clear sight**.

### What are you suggesting?

Something that could tackle part of the problem would be letting testcafe to read environment variables. So that we could make it work with `process.env` and unbundle the credentials from the script.

### Additional context

Thank you for this testing marvel!

**Comment by AndreyBelym** [comment]
Thanks for the feedback! As an alternative, you can use your shell's syntax to pass values from enivronment variables to the TestCafe parameters, but you'l have to use different syntax for Windows and Linux/macOS:
##### bash (Linux/macOS)
```bash
testcafe --proxy $TESTCAFE_PROXY chrome test.js
```
##### cmd (Windows)
```cmd
testcafe --proxy %TESTCAFE_PROXY% chrome test.js
```

**Comment by arnaud** [comment]
> use your shell's syntax to pass values from enivronment variables to the TestCafe parameters

Seems legit. I'll try next week. Thanks for the tip.

**Comment by arnaud** [comment]
It works great. Thanks for the sharing this approach.
