### ISSUE TITLE
Enterprise firewall

### ISSUE THREAD

**Issue by arnaud** [DevExpress/testcafe#2998]
### What is your Test Scenario?

I'd like to do automated non-regression testing for a big corp from within its proxy-enabled **enterprise-grade firewalled internal network**. This corp relies on **hardened firewall restrictions** that require command-line users to run tests on localhost:

```
testcafe --hostname localhost --port 1337,1338 chrome test.js
```

This issue here being **we are restricted from listening on local network ports**, for security concerns.

### What are you suggesting?

In terms of CLI, things are covered, thanks to the `--hostname` option.
But this feature is missing in the GUI. I suggest this feature to be added so that TestCafé Studio can be used from within firewall-restricted internal company devices.

### What alternatives have you considered?

Letting the client know of this TestCafé Studio limitation and make them consider using a closed-source money-making evil-doing alternative.

### Additional context

We love you.

**Comment by aleks-pro** [comment]
Thank you for your kind words, @arnaud . 
 
At present, TestCafe Studio does not support the feature you described. We are going to implement it in one of our future releases.

If you have further questions regarding TestCafe Studio, you can address them to the [Developer Express support center](https://www.devexpress.com/Support/Center/Question/List/1).
