### ISSUE TITLE
No 'trim' in hammerhead.utils

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#301]
`hammerhead.utils.trim` was added in `testcafe-hammerhead` by commit [2326fec](https://github.com/DevExpress/testcafe-hammerhead/commit/2326fec8a54ceaa87c98de2a3ae14071624df965#diff-c4d47be494321bcb7989fbc811500f53R77) and since then it is used in `testcafe` [here](https://github.com/DevExpress/testcafe/blob/master/src/client/core/utils/key-char.js#L7) and [here](https://github.com/DevExpress/testcafe/blob/master/src/client/core/jquery-extensions/custom-selectors.js#L24).

After that, `hammerhead.utils.trim` was removed, and stringUtils was added to `hammerhead.utils.string` in commit [a9dc9cd](https://github.com/DevExpress/testcafe-hammerhead/commit/a9dc9cd51d32a27e594c50dfce9b7010558acbe1#diff-c4d47be494321bcb7989fbc811500f53L77). So use `hammerhead.utils.string.trim` now.

**Comment by AndreyBelym** [comment]
I'm working on it.

**Comment by AlexanderMoskovkin** [comment]
We will fix this in context of the 'update `testcafe-hammerhead` version' issue, so, I'm closing this
