### ISSUE TITLE
TestCafe - redirecting issue - LOGIN FAILED

### ISSUE THREAD

**Issue by amirse80** [DevExpress/testcafe#3014]
Hi,
As requested in the StackOverflow I am writing this new post with my test code. Unfortunatelly you will not be able to access these pages since they are company internal but you will see my code.
I have added some comments in the code so you can see where the issue occurs.

import { t, Role, ClientFunction } from 'testcafe';
import TrygghetsrådgivningStartPage from "./tStartPage";
import TrygghetsrådgivningCustomerProfilePage from "./tCustomerProfilePage";
import TrygghetsrådgivningRequirementQuestionsPage from "./tRequirementQuestionsPage";
import TrygghetsrådgivningErrorPage from "./tErrorPage";
import BusinessProposalPage from "./tBusinessProposal.js";
import SigningPage from "./tSigningPage.js";
import SimDigPage from "./tSimDig.js";

var config  = require('./tConfig');

const startPage = new TrygghetsrådgivningStartPage();
const customerProfilePage = new TrygghetsrådgivningCustomerProfilePage();
const requirementQuestionsPage = new TrygghetsrådgivningRequirementQuestionsPage();
const errorPage = new TrygghetsrådgivningErrorPage();
const businessProposalPage = new BusinessProposalPage();
const signingPage = new SigningPage();
const simDigPage = new SimDigPage();

var basePage = 'http://dap-iis-acc.sebank.se/?customernumber=198311114634&advisorycategory=1&advisorid=S24123';
var loginPage = 'https://pension-acc.sebank.se/PensionLogIn/?returnUrl=Uppdragswebben';

const basePageRole = Role(basePage, async () => {
    await t
     
    //start page
    .click(startPage.kundenHarIngetKollektivavtalCheckBox)
    .click(startPage.allaSomSkaFörsäkrasÄrArbetsföraCheckBox)
    .click(startPage.gåVidareTillTryggStartButton)
    
    
    //crate customer profile
    .click(customerProfilePage.läggTillPersonButton)
    .typeText(customerProfilePage.personNummerInput, '198311114634')
    .click(customerProfilePage.hämtaUppgifterButton)
    .typeText(customerProfilePage.årsInkomstInput, '123456')
    .click(customerProfilePage.skaFörsäkrasCheckBox)
    .click(customerProfilePage.skaSigneraKontraktetCheckBox)
    .click(customerProfilePage.mobilNummerInput)
    .pressKey('ctrl+a delete')      //delete old number and add new one
    .typeText(customerProfilePage.mobilNummerInput, '+46700500012')
    .click(customerProfilePage.sparaOchStängButton)
    .click(customerProfilePage.besvaraBehovsFrågorButton) 

    //Answer questions about customer
    .click(requirementQuestionsPage.jaButton)
    .click(requirementQuestionsPage.nextButton)
    .click(requirementQuestionsPage.jaButton)
    .click(requirementQuestionsPage.nextButton)
    .click(requirementQuestionsPage.jaButton)
    .click(requirementQuestionsPage.nextButton)
    .click(requirementQuestionsPage.jaButton)
    .click(requirementQuestionsPage.nextButton)
    .click(requirementQuestionsPage.jaButton)
    .click(requirementQuestionsPage.seErbjudandeButton)
   .click(businessProposalPage.AnsökOmTrygghetslösningButton)
   .click(signingPage.SkickaAnsökanButton)
   /*After this last buttonclick I get LOGIN FAILED message which I don´t get if ROLE is not used and I run the test manually.
   When running tests manually I would after clicking on AnsökanButton click on the next button called SigneraAnsökanDirektMedKundButton (see loginPageRole)
   and this action will redirect me to the login page which is the URL as written in the variable "var loginPage". As I wrote in the stackoverflow post the TestCafe seem to detect this redirection as a native beforerun dialog which requires some handler. I used "await t.setNativeDialogHandler(() => {})" but I am not sure if this is correct way of handling this or if it is in the right place. Can I use ROLES inside this setNativeDialogHandler()? */
   
}, {preserveUrl:true});

const loginPageRole = Role(loginPage, async () => {
    await t
    .click(simDigPage.DigiPassTab)
    .typeText(simDigPage.AddPersonnummer, '8311114634')
    .typeText(simDigPage.Inloggningskod, '155495')
    //.click(simDigPage.LoggaInButton)
    //.click(signingPage.SigneraAnsökanDirektMedKundButton)
});

fixture `Fixture`
    .httpAuth({
        username:   config.username,
        password:   config.password,
        domain:     config.domain
     })

test('Test', async t => {
    console.log('Debug 1')
    await t.setNativeDialogHandler(() => {})
    await t.useRole(basePageRole) // state is saved
    console.log('Debug 2')
    await t.useRole(loginPageRole); // 
    console.log('Debug 3')
    await t.useRole(basePageRole) // state is restored
    console.log('Debug 4')
    
});

**Comment by amirse80** [comment]
Stackoverflow post:
https://stackoverflow.com/questions/52900501/testcafe-redirecting-issue

**Comment by AlexKamaev** [comment]
Thank you for providing the code. However, without a running project it is difficult to determine the cause of the issue. If it's impossible to share it here, you can send me a simple project via email.

**Comment by amirse80** [comment]
Hi Alex,
 First where do I find your email?

I could share my project but I am afraid you will not be able to run it on your side due to all security settings (firewalls). The application will not start. Is there any logs or something else I could provide you with in order for you to get more info about the issue. Would it be ok to create a Word document with pictures and console output?

**Comment by amirse80** [comment]
Hello, would you please comment on this issue. We are really hitting the wall at the moment. If we don´t solve this issue today and tomorrow we most likely need to go back to Selenium. I would love to continue with TestCafe.

As I wrote. The problem we face now is that when we are logged in to one page and do some clicking on it at one of these clicks we are redirected to another login page (a new tab when run manually) but by using ROLES, this redirection (which is done in same tab by TestCafe) gets us logged out so the message "LOGIN FAILED" is shown just before the new ROLE is started (or let say directly after the code in first ROLE definition is done).

I really need to be able to go the same state where I was before the role change. To make it worse on one URL we do some YES/NO questions so a redirection could be at question 4 out of 10, then I would actually need to go back to question4 after I am redirected back to first role, not to start from beginning.

Is this even possible? Or is the Selenium way to go?

**Comment by amirse80** [comment]
I see the errand is in satte "Need clarification". Will it help  you anything if I send you a word document with printscreens on what is happening?

**Comment by amirse80** [comment]
I see the errand is in set to"Need clarification". Will it help you anything if I send you a word document with printscreens on what is happening? Just tell me the email address and I will fix it

**Comment by AlexSkorkin** [comment]
The information you provided is insufficient to determine the cause of the issue. We need to see your application in action. Screenshots won't help us much here. I suggest you minimize your application and remove all external dependencies from your environment. This way, we can run the application on our side, see what's going on, and find a solution, if any.

**Comment by amirse80** [comment]
AlexKamaev/AlexSkorkin, I have created a simple project where I log in to Outlook. This is very similar to the project and issue I have in my company internal project. Would you please give me an email address to where I can send you the code since it contains a password to my test account. 
In the code I have explained the issue and what I expect. You have my email just send me a message about where to send you this project.

**Comment by AlexSkorkin** [comment]
Please send it at support@devexpress.com.

**Comment by AlexSkorkin** [comment]
Thank you. We have received your Email and will look into it soon.

**Comment by AlexKamaev** [comment]
I've modified your example and now it works. Please see the code below (I've removed login/pass information):
```JS
import { Role, Selector } from 'testcafe';

const basePage = 'https://outlook.live.com/';
const login    = '*****';
const password = '*****';
let role2      = null;

const role1 = Role(basePage, async t => {
    await t.click('body > section > div > div > nav > div > div > div > a');
    await t.typeText('#i0116', login);
    await t.click('#idSIButton9');
    await t.typeText('#i0118', password);
    await t.click('#idSIButton9');

    await t.maximizeWindow();
    await t.wait(2000);

    await t.click(Selector('div.ms-FocusZone > button:nth-child(3)'), { offsetX: 1, offsetY: 1 });
    await t.click(Selector('button').withText('Användningsvillkor'));

}, { preserveUrl: true });


fixture `My fixture`
    .page(basePage);


test('test', async t => {
    await t.useRole(role1);

    role2               = Role.anonymous();
    role2.stateSnapshot = role1.stateSnapshot; // internal: copy state

    await t.useRole(role2);
    await t.click(Selector('label').withText('Your Privacy'));

    role1.url = basePage; // internal: correct url

    await t.useRole(role1);
    await t.typeText('input[type=search]', 'it works');
});
```

I should mention that you can solve this issue only using our internal api. For now it is stable, but we can change it in the future.
 
I've created two roles: `role1` and `role2`. `role1` has the `preserveUrl: true` option. It's required to stay on the `Användningsvillkor` page. Once `role1` is initialized and its state is saved, I create an anonymous `role2`. Then I copy the `role1` state to the `role2` state and call the `useRole(role2)` function. For now we have the `role1` state stored in `role1`. It will not be changed. So, we can restore it.

Then you can do anything you want in the context of the anonymous `role2`. Here it is this string `await t.click(Selector('label').withText('Your Privacy'));`
 
Then, you need to restore the `role1` state. So, I've changed `role1.url`(it's internal) to `basePage` and call `useRole(role1)`.
 
Please let me know your results.

**Comment by amirse80** [comment]
Hi Alex,

Thank you for providing this code.
I am at home now and trying this out (since it uses external webpages which I cannot access at work) and when it works I will try to apply the same solution on the Project at work.

At the moment I face an issue with GetBposSshellInfoNavBarData, it fails on "await t.maximizeWindow();".

I tried to comment out that one but then it fails on same error on the next row you added "await t.click(Selector('div.ms-FocusZone > button:nth-child(3)'), { offsetX: 1, offsetY: 1 });"

I tried to google on issue but there is almost nothing on GetBposSshellInfoNavBarData.

**Comment by AlexKamaev** [comment]
Probably `GetBposSshellInfoNavBarData` is not connected with TestCafe. However, I've discovered that the page contains some js errors so I've executed the test with the `-e` option which allows skipping js errors. 
In addition, `await t.maximizeWindow()` is not required, I used it only for an example.

**Comment by amirse80** [comment]
Running the above step in Chrome shows the real issue. The pop up says exactly this "Leave site? Changes you made may not be saved."
Then I can click on Leave or Cancel button.
So our company page interprets any new page opened in the same tab as like leaving the application and therefor logges me out.

So my question would be, is there a way to "continue be logged in" when using TestCafe which opens other pages in the same tab instead of new tab?

**Comment by AlexKamaev** [comment]
I am not exactly sure that I understand what you mean by 'to continue be logged in'. The Roles mechanism is intended for this purpose and it is unclear what exactly is not working. Would you please share your current test code and your sample project, so we can better understand your scenario? Without having such a sample, we are not able to provide any precise solution.

**Comment by amirse80** [comment]
Hi, I sent you another email with I hope more in detail explanation.

**Comment by amirse80** [comment]
Hello Alex,


Actually I am writing to both Alex Skorkin and Alex Kamaev since both of you have answered my emails before.

Last email I sent you was a Word document with printscreens from my Company Project.

You could unfortunatelly not use that to give me some more hints about how to solve my issue and meet deadline on Friday so now I have spent half a day to find a webpage which has the same functionality.


I found Keeper Webapp which has exactly the same behaviour as in my Company webpage.

I.e once you are logged in the session is started and it will be Active as long as I stay on that page/tab.

If I in the same tab enter Another url like "https://github.com/" the session is lost and I need to re-login to come back to same state.

Ofcourse in real life I can always use another tab and the problem is solved.

But testcafe opens Everything in the same tab.


So, for you to take a look on the exact same problem I have and also being able to debug I send you this code.

Please try to modify the code so that it meets the requirements I wrote as comments in the code.

Since this is a JavaScript file Outlook might remove that so I send you a copy of the code here as well.

Just copy and paste the code to a .js file and it will work for you to debug.




import { Role, Selector, ClientFunction } from 'testcafe';

const basePage = 'https://keepersecurity.com/vault/';
const login    = 'devtest123456789@outlook.com';
const password = '123456789devtest';
let role2      = null;


const role1 = Role(basePage, async t => {
    await t.typeText('#login-email-input', login);
    await t.typeText('#keeperlogin > div.login_box > div.login_content > form > div:nth-child(2) > input[type="password"]', password);
    await t.click('#keeperlogin > div.login_box > div.login_content > form > div:nth-child(5) > button');

    //When I click on this record in keeper webapp I want to later on come back to the same view.
    //On exactly this page and this record that I am clickin on now
   await t.click('#folderlist > div > div > div > ul > div:nth-child(1) > div > div > div > div > li')

   await t.wait(3000)

}, { preserveUrl: true });


fixture `My fixture`
   // .page(basePage);


test('test', async t => {

    console.log('navigate to keeper web app via role1');
    await t.useRole(role1);

    console.log('navigate to github');
    await t.navigateTo('https://github.com/');
    await t.wait(5000);

    console.log('go back to keeper webapp via role1 preservedUrl');

    role1.url = basePage;
    await t.useRole(role1); //here I expect to go back to the keeperweb app and the record I clicked on in the Role1
                            //but what testcafe does is to redirect me back to the keeper login page and that was not
                            //where the tests ended when I was in Role1.
                            //So how do I do to go back to exactly the record I clicked on in Role1 at this step???

    await t.wait(5000);
    console.log('end of test');

});


Now I have really tried Everything I can to give you as much info about this issue I am facing so I hope you can have use of this example.
This is what you needed, the complete sample Project which you could run on your own.

Please please have in mind that my deadline is on Friday. It is do or die for TestCafe.

Br,
/Amir

________________________________
Från: AlexKamaev <notifications@github.com>
Skickat: den 30 oktober 2018 14:12
Till: DevExpress/testcafe
Kopia: amirse80; Author
Ämne: Re: [DevExpress/testcafe] TestCafe - redirecting issue - LOGIN FAILED (#3014)


I am not exactly sure that I understand what you mean by 'to continue be logged in'. The Roles mechanism is intended for this purpose and it is unclear what exactly is not working. Would you please share your current test code and your sample project, so we can better understand your scenario? Without having such a sample, we are not able to provide any precise solution.

**Comment by AlexKamaev** [comment]
I've checked `https://keepersecurity.com/vault/` and found that it requires login/password if you refresh the page by pressing F5. This is how the website is designed and TestCafe with its roles mechanism cannot overcome this behavior. The use of the roles mechanism implies that some redirection will be performed during test execution. Usually, sites restore their state after redirection using localStorage/cookies. But in this case, despite the fact that the localStorage/cookies were saved correctly, the state will not be restored. Again, it's behavior of this website and there are no approaches (including roles) that can help here.

**Comment by amirse80** [comment]
ok Alex. Thank you for your input. Our application has the same functionality as you describe, i.e. press F5 and I am logged out. In this case I will need to wait for some future update of testcafe which maybe will be able to handle this scenario although my test contain a real redirection to a new tab.
