### ISSUE TITLE
Plans to switch to Webdriver if it becomes standard?

### ISSUE THREAD

**Issue by ljowen** [DevExpress/testcafe#3019]
Hi, just wondering if assuming the following spec: https://w3c.github.io/webdriver/ is implemented by vendors would testcafe switch to / support using the browser's own automation api?

My main motivation is the inability to test media playback due to autoplay policies and I feel similar rules will be added in the future making it more difficult to test via injected automation scripts.

**Comment by miherlosev** [comment]
Hi @ljowen 

We have an [issue](https://github.com/DevExpress/testcafe/issues/2543) to use the browser specific automation API for Chrome and Firefox. Track this to be aware of our progress.
