### ISSUE TITLE
Unable to resize the window because the specified size exceeds the screen size. On macOS, a window cannot be larger than the screen.

### ISSUE THREAD

**Issue by AnjolaA** [DevExpress/testcafe#3022]
### What is your Test Scenario?
Basic web tests on a Mac OS X 10.12.6
 
### What is the Current behavior?
The Chrome test doesnt run on my Mac unless I have it connected to a monitor or I switch to Safari or hide the dock
 
### What is the Expected behavior?
The tests should run as normal
 
### What is your web application and your TestCafe test code?
See Below
 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

```
import { Selector } from 'testcafe'; // first import testcafe selectors

fixture `Getting Started`// declare the fixture
    .page `https://devexpress.github.io/testcafe/example`;  // specify the start page


//then create a test and place your code there
test('My first test', async t => {
    await t
        .resizeWindow(1024, 768)
        .typeText('#developer-name', 'John Smith')
        .click('#submit-button')
        .expect(Selector('#article-header').innerText).eql('Thank you, John Smith!');
});
 
```
</details>

<details>
<summary>Your complete test report:</summary>

```
Running tests in:
 - Chrome 70.0.3538 / Mac OS X 10.12.6

 Getting Started
 ✖ My first test

   1) Unable to resize the window because the specified size exceeds the screen size. On macOS, a window cannot be larger than the screen.

      Browser: Chrome 70.0.3538 / Mac OS X 10.12.6

          5 |
          6 |
          7 |//then create a test and place your code there
          8 |test('My first test', async t => {
          9 |    await t
       > 10 |        .resizeWindow(1024, 768)
         11 |        .typeText('#developer-name', 'John Smith')
         12 |        .click('#submit-button')
         13 |        .expect(Selector('#article-header').innerText).eql('Thank you, John Smith!');
         14 |});

         at resizeWindow (/Users/user/macode/datestcafe/test.js:10:10)
         at test (/Users/user/macode/datestcafe/test.js:8:1)
         at markeredfn (/Users/user/macode/datestcafe/node_modules/testcafe/src/api/wrap-test-function.js:18:28)
         at <anonymous> (/Users/user/macode/datestcafe/node_modules/testcafe/src/api/wrap-test-function.js:8:5)
         at fn (/Users/user/macode/datestcafe/node_modules/testcafe/src/test-run/index.js:238:19)
         at TestRun._executeTestFn (/Users/user/macode/datestcafe/node_modules/testcafe/src/test-run/index.js:234:38)
         at _executeTestFn (/Users/user/macode/datestcafe/node_modules/testcafe/src/test-run/index.js:279:24)



 1/1 failed (2s)

```
</details>

### Steps to Reproduce:
Run the test above with the same environment info below.
 
### Your Environment details:
 
* testcafe version:                       0.22.1-alpha.3,
* node.js version:                    8.11.1
* command-line arguments:  testcafe chrome test.js
* browser name and version: Chrome 70.0.3538
* platform and version:     Mac OS X 10.12.6
* other:
It works when I hide the dock or move it to the side.

**Comment by AlexKamaev** [comment]
It is expected behavior. MacOS does not allow you to have a window larger than the screen. When you hide the dock or connect to the monitor, you are increasing the available area for your window, so it works in this case. I've also checked this in Safari and noticed the same behavior.
