### ISSUE TITLE
Docker publishing is broken for alpha versions

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#3026]
![image](https://user-images.githubusercontent.com/4133518/47440375-b2e26000-d7b6-11e8-9e93-aeff1e18667f.png)

**Comment by kruckenb** [comment]
I'm not sure if it's the same issue, but I'm getting an error when building the Docker container:

```
]$ docker build -f docker/Dockerfile .
[...]
Step 4/7 : RUN cd /opt/testcafe;  npm install --production &&  npm cache clean --force &&  rm -rf /tmp/* &&  chmod +x /opt/testcafe/docker/testcafe-docker.sh &&  adduser -D user
 ---> Running in f45d69e97426
npm ERR! code EADDRNOTAVAIL
npm ERR! errno EADDRNOTAVAIL
npm ERR! request to https://registry.npmjs.org/async-exit-hook failed, reason: getaddrinfo EADDRNOTAVAIL registry.npmjs.org:443

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-26T13_35_09_309Z-debug.log
The command '/bin/sh -c cd /opt/testcafe;  npm install --production &&  npm cache clean --force &&  rm -rf /tmp/* &&  chmod +x /opt/testcafe/docker/testcafe-docker.sh &&  adduser -D user' returned a non-zero code: 1
```

This looks similar to this bug https://github.com/yarnpkg/yarn/issues/6384#issuecomment-422830091 in [musl-1.1.20](https://git.musl-libc.org/cgit/musl/commit/?id=f381c118b2d4f7d914481d3cdc830ce41369b002) in alpine:edge

**Comment by miherlosev** [comment]
Also, need to add an error message when you run `docker-publish` not in DockerToolbox environment.
For example, if you run docker publishing with a Windows CMD terminal then image publish will be hung.
