### ISSUE TITLE
Injected library is not defined

### ISSUE THREAD

**Issue by ilyasbasharov** [DevExpress/testcafe#3032]
### What is your Test Scenario?

```
import { ClientFunction } from 'testcafe';
import fs from 'fs';

fixture `My fixture`
    .page `http://devexpress.github.io/testcafe/example/`;

test('My test', async t => {
    await t.eval(new Function(fs.readFileSync(__dirname + '\\d3-selection.min.js').toString()));

    const getElementText = ClientFunction(() => {
        
        return d3.select('div.column.col-2').html();
    });

    await t.expect(getElementText()).contains('What is your primary Operating System');
});
```
 
### What is the Current behavior?

   1) An error occurred in ClientFunction code:

      ReferenceError: d3 is not defined

### What is the Expected behavior?

I can use d3 in the test accroding to http://devexpress.github.io/testcafe/documentation/test-api/obtaining-data-from-the-client/examples-of-using-client-functions.html#injecting-external-libraries-into-a-page-from-a-test
### Your Environment details:
 
* testcafe version:      0.22.0             
* node.js version:       10.11.0             
* command-line arguments:  testcafe chrome .\tests\simpleTest.js 
* browser name and version: Chrome 70.0.353 
* platform and version:   Windows 10.0.0       
* other:

**Comment by AlexKamaev** [comment]
It works as expected. I've modified your test a little and checked it. Please take a look at the example below:

Test code
```JS
import { ClientFunction } from 'testcafe';
import fs from 'fs';

fixture `My fixture`
    .page `http://devexpress.github.io/testcafe/example/`;

test('My test', async t => {
    await t.eval(new Function(fs.readFileSync(__dirname + '\\d3-selection.min.js').toString()));

    const getElementText = ClientFunction(() => {
        return d3.select();
    });

    await getElementText();
});
```
d3-selection-min.js library code:
```JS
window.d3 = {
    select: function () {
        alert('test');
    }
};
```
The test with fail on `alert('test')` execution as expected.

**Comment by ilyasbasharov** [comment]
Thanks.

Could you look at the different example. I want to inject external lib into a page such as d3.min.js. d3.min.js is attached to this comment.

```
import { ClientFunction } from 'testcafe';
import fs from 'fs';

fixture `My fixture`
    .page `http://devexpress.github.io/testcafe/example/`;

test('My test', async t => {
    await t.eval(new Function(fs.readFileSync(__dirname + '\\d3.min.js').toString()));

    const getElementText = ClientFunction(() => {
        return d3.select('legend').size();
    });

    await getElementText();
});
```
I'm still get an error 

>    1) An error occurred in ClientFunction code:
> 
>       ReferenceError: d3 is not defined

[d3.min.js.zip](https://github.com/DevExpress/testcafe/files/2518414/d3.min.js.zip)
