### ISSUE TITLE
Old, out-of-date docs should point to the updated docs on devexpress.github.io

### ISSUE THREAD

**Issue by dwaltrip** [DevExpress/testcafe#3036]
Through google, I found myself in the docs located at: https://testcafe.devexpress.com/Documentation

These docs seem to be very incomplete and out-of-date, which is obviously quite a bad thing, especially if someone is checking out `testcafe` for the first time.

Luckily, I double-checked on github and found the up-to-date website: https://devexpress.github.io/testcafe/

It would be good to either remove the old docs on https://testcafe.devexpress.com, or even better, have that link take you the updated documentation.

**Comment by VasilyStrelyaev** [comment]
Hi @dwaltrip,
Documentation at https://testcafe.devexpress.com is not out of date, it describes a different tool - a paid web testing framework released in 2013. This tool is still in use.

You can learn more about TestCafe versions in our [FAQ](https://devexpress.github.io/testcafe/faq/#what-is-the-difference-between-a-paid-and-an-open-source-testcafe-version-what-is-testcafe-studio).

Although we cannot remove these docs, we will try to come up with a better way to indicate a TestCafe version to which this documentation relates.

**Comment by dwaltrip** [comment]
Thanks for the response. I have to say, having the exact same name is quite confusing!
