### ISSUE TITLE
External lib is not injected into a page

### ISSUE THREAD

**Issue by ilyasbasharov** [DevExpress/testcafe#3039]
Could you look at the different example. I want to inject external lib into a page such as d3.min.js. d3.min.js is attached to this comment.

```
import { ClientFunction } from 'testcafe';
import fs from 'fs';

fixture `My fixture`
    .page `http://devexpress.github.io/testcafe/example/`;

test('My test', async t => {
    await t.eval(new Function(fs.readFileSync(__dirname + '\\d3.min.js').toString()));

    const getElementText = ClientFunction(() => {
        return d3.select('legend').size();
    });

    await getElementText();
});
```
I'm still get an error 

>    1) An error occurred in ClientFunction code:
> 
>       ReferenceError: d3 is not defined

[d3.min.js.zip](https://github.com/DevExpress/testcafe/files/2518414/d3.min.js.zip)

_Originally posted by @ilyasbasharov in https://github.com/DevExpress/testcafe/issues/3032#issuecomment-433334249_

**Comment by AlexKamaev** [comment]
The TestCafe `t.eval` command runs js code in a separate module for security reasons. Therefore some checks inside the `d3` library prevent modifying the `window` object so you can't use the `d3` variable. Could you please try following workaround: `await t.eval(new Function(fs.readFileSync(__dirname + '\\d3.min.js', 'utf-8')), { dependencies: { module: undefined } });` ?

**Comment by ilyasbasharov** [comment]
Thanks, it works as expected.
