### ISSUE TITLE
Fix development dependencies with vulnarabilities

### ISSUE THREAD

**Issue by hdorgeval** [DevExpress/testcafe#3045]
Just for your information: latest version of `publish-please` will report vulnerabilities in `testcafe`

```sh
npx publish-please@5.0.0 --dry-run
```

will ouput the following:

```
Running validations
-------------------

✖ Checking for the vulnerable dependencies
✓ Checking for the sensitive and non-essential data in the npm package
✓ Validating branch
✓ Validating git tag

ERRORS
  * Vulnerability found in broken-link-checker -> bhttp -> lodash
  * Vulnerability found in broken-link-checker -> bhttp -> string
  * Vulnerability found in broken-link-checker -> bhttp -> form-data2 -> lodash
```

`broken-link-checker > bhttp > string`is scored high vulnerability

Best regards

**Comment by miherlosev** [comment]
Hi @hdorgeval 

Thanky for your note. `publish-please` is a development dependency. We will migrate to the latest `publish-please` module version.

**Comment by miherlosev** [comment]
![image](https://user-images.githubusercontent.com/4133518/48052385-d3e48100-e1b8-11e8-947b-4bafbd7c48c0.png)

**Comment by AndreyBelym** [comment]
Closed by https://github.com/DevExpress/testcafe/commit/bc26207ae416404287db88f22b4713dba26f8605.
