### ISSUE TITLE
Docker and runner class

### ISSUE THREAD

**Issue by subbiah28062** [DevExpress/testcafe#3052]
Hello,

Can we run runner class file in dockers.

Like:
docker run -v ${folder}:/tests -it testcafe/testcafe tests/runner.js

When I run above command I get this error:
ERROR Unable to find the browser. "tests/runner.js" is not a browser alias or path to an executable file.

My runner.js file:

const createTestCafe = require('testcafe');
let testcafe = null;
var fs = require('file-system');
const stream = fs.createWriteStream('report.html');

function getTests(){
    const suite1 = ['Setup-screen-common-tests/fullScreenRuleCreate1.js'];
    const suite2 = ['Setup-screen-common-tests/fullScreenRuleCreate.js'];

    return [suite1, suite2];
}

createTestCafe('localhost', 1362, 1363)
    .then(tc => {

        function runSuite(suite){
          const runner = tc.createRunner();

          return runner
            .src(suite)
            .browsers(['chrome'])
            .reporter('html', stream)
            .reporter('list')
            .run({
              skipJsErrors: true,
            })
            .then(() => console.log('runner finished'))
            .catch(e => console.log('runner failed', e));
        }

        return Promise.all(getTests().map(runSuite)).then(() => console.log('tests finished')).then(() => tc);
    })
    .then(tc => {
      console.log('closing testcafe');
      return tc.close();
    })
    .then(() => stream.close())
    .catch(e => console.log('testcafe failed', e));

**Comment by miherlosev** [comment]
Thank you for your inquiry. Please route your questions on StackOveflow where you will receive community support. Don't forget to [set the testcafe tag when asking](https://stackoverflow.com/questions/ask?tags=testcafe). We reserved this repo for bugs and feature requests: [Contributing](https://github.com/DevExpress/testcafe#contributing).

You may also find answers in our up-to-date [documentation](https://devexpress.github.io/testcafe/documentation/getting-started/) and [answered questions](https://stackoverflow.com/questions/tagged/testcafe).
