### ISSUE TITLE
Resize window does not work in Firefox v63

### ISSUE THREAD

**Issue by AlexisGlez** [DevExpress/testcafe#3071]
### What is your Test Scenario?
I'm trying to test elements being resized in Firefox v63 and I'm getting this warning:
![image](https://user-images.githubusercontent.com/13372889/47883847-50134900-ddf4-11e8-96aa-73cee747ec6b.png)

Therefore, the test is not passing.

 
### What is the Current behavior?
Any resize test does not work in latest Firefox version (63). This is working with version 62.
 
### What is the Expected behavior?
Resize test must work correctly.
 
### Your Environment details:
 
* testcafe version: v0.22.0
* node.js version: v8.9.0
* browser name and version: Firefox Version 63 (64-bit)
* platform and version: MacOS Sierra 10.12.6

**Comment by cejavoa** [comment]
Hey that is happening to me right now! Is there any solution for this?

**Comment by miherlosev** [comment]
Fixed in `testcafe@0.23.0-alpha.1.`
