### ISSUE TITLE
When a browser window is small, Status Panel does not show fixture/test name

### ISSUE THREAD

**Issue by MargaritaLoseva** [DevExpress/testcafe#3073]
![image](https://user-images.githubusercontent.com/12034505/47855540-ef850b80-ddf5-11e8-8f45-e6ae0258bb19.png)

**One more note**: Status text is not centered vertically. In addition, should we align the fixture/test name text block with the icon's bottom?
![image](https://user-images.githubusercontent.com/12034505/47855914-e0eb2400-ddf6-11e8-92e6-824ff3f74b03.png)

**Comment by joma74** [comment]
Also for Chrome on Ubuntu, especially if not in debug mode - so even if enough space is available; Does not apply for Firefox.

**Comment by AndreyBelym** [comment]
Closed by https://github.com/DevExpress/testcafe/commit/33e547491551c419707680326b53c8b66ef22037.
