### ISSUE TITLE
 User Profile and Log In

### ISSUE THREAD

**Issue by ilyasbasharov** [DevExpress/testcafe#3074]
I have a scenario where I need to use the current user chrome profile . I expected that I don't need to log in to web app. I thought TestCafe would use stored credentials. But all tests are redirected to Log In page. 
I launch testcafe tests with flag chrome:userProfile. 

How could I run tests and use stored credentials in browser?

**Comment by AlexSkorkin** [comment]
Thank you for your inquiry. This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe). I see that you already submitted your inquiry there: [TestCafe - User Profile and Log In](https://stackoverflow.com/questions/53124462/testcafe-user-profile-and-log-in)
 
StackOverflow is an amazing platform for users to ask and answer questions: the community will see and answer your question there.

We try to keep GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing).
