### ISSUE TITLE
[Feature]: Support internet throttling 

### ISSUE THREAD

**Issue by vitalics** [DevExpress/testcafe#3075]
### What is your Test Scenario?

I have a PWA application and scenario is simple: turn off internet and launch this application. As a result, I want to see that service worker cached some data and this data is loading from cache.
### What are you suggesting?

Create a syntax just like in [protractor](https://stackoverflow.com/a/46672403):
``` js
test('no internet', async t =>{
t.setNetworkConnection() // just like in protractor
})
```
### What alternatives have you considered?
LightHouse can [emulate throttling](https://github.com/GoogleChrome/lighthouse/blob/648a2fd4b8c5f7b47eee07c722381851467cbfbb/lighthouse-core/lib/emulation.js#L103) but only for chrome and chromium-based browsers

**Comment by aprabh001c** [comment]
Any update on this please.

**Comment by AndriiSakiienko** [comment]
@AndreyBelym, any update?

**Comment by TomRodano** [comment]
In the example provided, No Network was specifically called out, but the headline suggests implementing Network Throttling. Supporting throttling such as controlling upload and download speed and latency is needed as well, to be able to emulate slow/poor network conditions in the test.

**Comment by Aleksey28** [comment]
Hi @TomRodano,

Thank you for the additional information. We will consider it when we take this enhancement into work.
