### ISSUE TITLE
add option to match only trimmed strings

### ISSUE THREAD

**Issue by TauPan** [DevExpress/testcafe#3083]
### What is your Test Scenario?
Since the upgrade from chromium 69 to 70, the way certain elements are rendered on the page has changed. Both `innerText` and `textContent` now have additional whitespace (in a DataTable), e.g. an element in the table that previously could be matched with `await t.expect(selector.innerText).eql('foo')` now doesn't match any more because it contains 'foo\t' (with a tab character at the end, no idea why).

I now have to judiciously switch to `textContent` and more narrow element matching, which helps in some cases, in other cases the easiest way is to match with `.contains` instead of `.eql`, which might not be appropriate in all situations.

Also it might be harder to make tests robust across browser, but I haven't run the "fixed" tests for firefox yet.

### What are you suggesting?
Add an option `trim` to the `.eql` and `.notEql` assertions that will cause them to operate on strings after trimming them.

### What alternatives have you considered?
I've considered writing my own helper function to get trimmed text from a selector, however I expect this to be a more common problem with chrom(ium|e) 70.

**Comment by Juansasa** [comment]
A relaxed operator would be nice for example .closeTo() or .similarTo()
1 = '1'
'abc' = '  abc   '
'aBC'  = '  AbC  '

**Comment by TauPan** [comment]
Note that there are cases where `.match` is simpler, more appropriate and more robust. But I'm not talking about those cases but rather a case where I expect the element text to be a simple string and unexpected whitespace sneaks in for some reason only known to the webbrowser (or a javascript module).

This is reproducible on the DataTables examples page https://datatables.net/examples/basic_init/zero_configuration.html if you enter `$('tr td')[0].innerText` in the javascript console (in chrome/chromium before 70 or firefox), you get `"Airi Satou"` and in Chromium or Chrome 70: `"Airi Satou	"`.

(Not sure if this is actually a bug in chrome or datatables or any other framework, but that's not really the point here either.)

**Comment by TauPan** [comment]
See here https://bugs.chromium.org/p/chromium/issues/detail?id=897373 wrt whether this is a chrome bug or not...

**Comment by AndreyBelym** [comment]
You can use the `await` keyword to get the value of the `Selector.innerText` property, and then just use the [String.trim](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/Trim) method to  remove leading and trailing spaces:
```js
const rawInnerText = await Selector('...').innerText;
const innerText    = rawInnerText.trim();

await t.expect(innerText).eql('...');
```

I agree that it's a bit verbose. Maybe we can use [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) to wrap all `Selector`'s proreties, and allow to use corresponding methods on them?

```js
await t.expect(Selector('...').innerText.trim()).eql('...');
```

**Comment by TauPan** [comment]
> I agree that it's a bit verbose. Maybe we can use [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) to wrap all `Selector`'s proreties, and allow to use corresponding methods on them?
> 
> ```js
> await t.expect(Selector('...').innerText.trim()).eql('...');
> ```

That looks very pleasing and convenient indeed. And it's a more generic solution than what I proposed.

**Comment by viveleroi** [comment]
I had this same issue and was hoping to find a way to chain a solution. I couldn't find a way to make an async/await function in my page model that would still allow chaining but I also realized that a custom Selector property could work nicely:

In a page object model constructor:

```
this.symbolPreview = Selector('...').addCustomDOMProperties({
    innerTextTrimmed: el => el.innerText.trim()
});
```

In my test:
```
.expect(page.symbolPreview.innerTextTrimmed).eql('...')
```

**Comment by miherlosev** [comment]
There is one more case - conversion to integer value (https://stackoverflow.com/questions/56288625/how-to-assert-a-value-within-a-span).
