### ISSUE TITLE
Testcafe disconnects from browser if we use one "await t" with many actions

### ISSUE THREAD

**Issue by ZeddEn** [DevExpress/testcafe#3088]
### What is the Current behavior?
Testcafe goes on a ECONNABORTED and closes the connexion with the browser (chrome in my case)
 
### What is the Expected behavior?
The test should continue and no connexion exit should be raised
 
### What is your web application and your TestCafe test code?
 
Your website URL (or attach your complete example): Local intranet website

<details>
<summary>
Chaining many testcafe instructions with just one single "await t" instead of many forces testcafe to be disconnected from the browser. This has been noticed locally and also remotely. I think before the v23 the browser froze but with the release of this new version (a possible fix to the browser timeout connexion -> force connection to close)
</summary>

 
```js
This raises the error:
 await t
            .expect(this.title.visible).ok()
            .expect(this.sideID.visible).ok()
            .expect(this.pageID.visible).ok()
            .expect(this.formatID.visible).ok()
            .expect(this.siteName.visible).ok()
            .expect(this.pageName.visible).ok()
            .expect(this.formatName.visible).ok()
            .expect(this.viewList.visible).ok()
            .expect(this.siteNameList.count).gt(10)
            .expect(this.pageNameList.count).gt(10)
            .expect(this.formatNameList.count).gt(10)

While there is no error with this:
    await t
            .expect(this.title.visible).ok()
            .expect(this.sideID.visible).ok()
            .expect(this.pageID.visible).ok()
            .expect(this.formatID.visible).ok()
            .expect(this.siteName.visible).ok()
            .expect(this.pageName.visible).ok()
            .expect(this.formatName.visible).ok()
            .expect(this.viewList.visible).ok();

        await t
            .expect(this.siteNameList.count).gt(10)
            .expect(this.pageNameList.count).gt(10)
            .expect(this.formatNameList.count).gt(10)
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

Just use one await t with more than 7 expects and the error should be raised starting from the number 6 expect.

Error: write ECONNABORTED
    at Socket._writeGeneric (net.js:768:25)
    at Socket._write (net.js:787:8)
    at doWrite (_stream_writable.js:396:12)
    at writeOrBuffer (_stream_writable.js:382:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:711:40)
    at TLSSocket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
Waiting for the debugger to disconnect...
 
### Your Environment details:
 
* testcafe version:                   ^0.23.0
* node.js version:                    v8.12.0
* command-line arguments:  Plugin VS Code Testcafe (run with right click)
* browser name and version: Chrome 70.0.3538 
* platform and version:           Windows 10.0.0

**Comment by miherlosev** [comment]
Hi @ZeddEn

We've fixed this problem in the `testcafe@0.23.1` version.
