### ISSUE TITLE
IE 11: Network error after microsoft windows authentication.

### ISSUE THREAD

**Issue by ilyasbasharov** [DevExpress/testcafe#3092]
### What is your Test Scenario?
Precondition: I have Excel Online document and I want to open it using testcafe in IE11.

Steps:
1) Open Excel Online document;
2) Browser redirected to authentication page(https://login.microsoftonline.com);
3) Pass authentication steps;
3) Excel Document is starting to load.
 
### What is the Current behavior?
Test failed with message: NetworkError. Only I could reproduce it in IE11
 
### What is the Expected behavior?
Authentication is passed.
 
### What is your web application and your TestCafe test code?
Need to have Office Online subscription to reproduce this issue. 

 
### Your Environment details:
 
* testcafe version:                   0.23.1
* node.js version:                    v11.0.0
* command-line arguments:  testcafe ie .\tests\simpleTest.ts
* browser name and version: IE 11.345.17134.0
* platform and version:          Windows 10

**Comment by Farfurix** [comment]
@miherlosev i've reproduced `NetworkError` on testcafe@0.23.1 / Internet Explorer 11 / Windows 10, but authentication is passed and Excel document loaded successfully:

```js
import { Selector } from 'testcafe';

fixture('Excel online')
    .page(`shared-excel-document-url`);

const loginInput   = Selector('input').withAttribute('type', 'email');
const passInput    = Selector('input').withAttribute('type', 'password');
const submitButton = Selector('input').withAttribute('type', 'submit');
const noButton     = Selector('input[value=\'No\']');

const login = '***';
const pass  = '***';

test(`login`, async (t) => {
    await t.typeText(loginInput, login)
        .click(submitButton)
        .typeText(passInput, pass)
        .click(submitButton)
        .click(noButton) // Stay signed in? No.
        .wait(10000);
});
```
Result:
```
 × login

   1) Error on page

   "shared-excel-document-url":

      NetworkError:
          No stack trace available

      Browser: IE 11.0.0 / Windows 10.0.0
```

@ilyasbasharov, could you please try running your test scenario with the [`-e`](http://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors) option and check if all assertions were successful?

**Comment by ilyasbasharov** [comment]
@Farfurix, I runned my test with -e option and all assertions were successful.
