### ISSUE TITLE
New user - testcafe 

### ISSUE THREAD

**Issue by SiemplifyMarketplace** [DevExpress/testcafe#3093]
Hello,
I am a new user of tesstcafe and there are few issues I feel:
1. The code created automatically in .js while all the examples in your website are .ts.
is there any way to convert your code to the relevant example and still run it through your framework?

2. Is there any way I can use windows authentication via your framework?

3. For now, any test starts directly on our homepage instead of on the login screen. is there any way to make them start in the login screen? 

many thanks,
Daniel

**Comment by AlexSkorkin** [comment]
Daniel, thank you for your interest in our testing tools. 

This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe). StackOverflow is an amazing platform for users to ask and answer questions: the community will see and answer your question there.

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)).

As for our documentation samples, I'm not sure which ones you mean. All our samples are provided in JavaScript; e.g., [Test Controller](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#test-controller).
