### ISSUE TITLE
Browser disconnected starting from version 0.22.0

### ISSUE THREAD

**Issue by ZeddEn** [DevExpress/testcafe#3094]
### What is your Test Scenario?
Triggering the tests from a CI environment fails from time to times and raise an exit code 1.
 
### What is the Current behavior?
So I am getting an "Error: Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure." but it is produced not all the time. Maybe once every 4 or 5 builds. So once this error is raised, the builds stop.

This may be strongly related with the disconnection from the browser. I have managed to reproduce it on multi-browser (chrome and firefox) and also a single browser (chrome) so it is not related to parallel testing.

Somehow I cannot produce it locally so it is raised only on CI configuration (TeamCity).

On the old versions (version 0.20 for example), I have this kind of problem but instead of the build exiting the build hanged for hours (I guess I saw there was a fix for that in the last versions).
 
### What is the Expected behavior?
Normally such error should not be raised.
 
### What is your web application and your TestCafe test code?
Intranet app, so no access sadly.
 

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
The raised error is:
```js
 Error: Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure. at C:\BuildAgent\work\4a74606c58d6f60f\node_modules\testcafe\src\runner\browser-set.js:84:30 at next (native) at step (C:\BuildAgent\work\4a74606c58d6f60f\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30) at C:\BuildAgent\work\4a74606c58d6f60f\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14 at Promise.F (C:\BuildAgent\work\4a74606c58d6f60f\node_modules\core-js\library\modules\_export.js:36:28) at C:\BuildAgent\work\4a74606c58d6f60f\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12 at BrowserSet._waitConnectionsOpened (C:\BuildAgent\work\4a74606c58d6f60f\node_modules\testcafe\src\runner\browser-set.js:77:37) at _waitConnectionsOpened (C:\BuildAgent\work\4a74606c58d6f60f\node_modules\testcafe\src\runner\browser-set.js:107:35) at invokeCallback (C:\BuildAgent\work\4a74606c58d6f60f\node_modules\pinkie\index.js:60:12) at Array.forEach (native) Process exited with code 1
```
------------------------------------------------------------------------------------------------------
I use this as a  runner:
```js
createTestCafe("localhost", 1337, 1338)
    .then(tc => {
        testcafe = tc;
        const runner = testcafe.createRunner();

        return (
            runner
            .src("./tests/**/*.ts")
            .browsers(["chrome --start-fullscreen"])
            .concurrency(1)
            // -- Run tests on full screen
            //.browsers(['chrome --start-fullscreen'])
            .reporter("allure", "/allure/allure-results")
            //.reporter('spec')
            .reporter("teamcity")
            .screenshots(
                "./report/screenshots/",
                true,
                "${USERAGENT}_${FIXTURE}_${TEST}_${QUARANTINE_ATTEMPT}.png"
            )
            .run({
                // -- Enter debug mode --
                //debugMode: true,

                // -- Enter debug mode when a test fails --
                //debugOnFail: true,

                skipJsErrors: false,
                quarantineMode: true,
                selectorTimeout: 60000,
                assertionTimeout: 60000
            })
        );
    })
    .then(failedCount => {
        console.log("Tests failed: " + failedCount);
        testcafe.close();
        process.exit(failedCount ? 1 : 0);
    });
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Your Environment details:
 
* testcafe version:                   0.23.1
* node.js version:                    8.11.3
* command-line arguments:  Look at the runner code above
* browser name and version:    Chrome 70.0.3538
* platform and version:            Windows 10.0.0
* other:

**Comment by ZeddEn** [comment]
I have found where the problem is from: the option  --no-sandbox is to be added to the runner's browser (chrome) to avoid that. 
Example: 	.browsers(['chrome:headless --no-sandbox'])

**Comment by AndreyBelym** [comment]
Thank you for sharing your solution. The `--no-sandbox` flag is already documented in the [Using TesTCafe Docker Image](https://devexpress.github.io/testcafe/documentation/using-testcafe/using-testcafe-docker-image.html#test-in-docker-containers) section and in the next TestCafe release will be applied automatically when running tests in a Docker container.
