### ISSUE TITLE
[docs] Add a topic about TestCafe integration into TFS

### ISSUE THREAD

**Issue by AlexSkorkin** [DevExpress/testcafe#3095]
The following topic seems to be missing the TFS integration sub-section:

[Integrating TestCafe with CI Systems](https://devexpress.github.io/testcafe/documentation/recipes/integrating-testcafe-with-ci-systems/)

**Comment by VasilyStrelyaev** [comment]
Maybe we should already close this as outdated?

**Comment by AlexSkorkin** [comment]
I agree, let's close it.
