### ISSUE TITLE
Improve TestCafe stability and performance in concurrency mode under heavy load

### ISSUE THREAD

**Issue by dbschwartz** [DevExpress/testcafe#3103]
### What is your Test Scenario?
 Running tests in concurrency in Windows 10 and Node 6.10.3 with TestCafe 0.23.1
### What is the Current behavior?
The tests start to run normally, but the status for the first test is the only one that shows in the command prompt.  Eventually the browsers either show the TestCafe start page or are on the start pageURL and are just awaiting further commands from hammerhead.  They just stay this way until I abort by pressing CTRL + C.
 
### What is the Expected behavior?
Concurrent tests should just as they did in TestCafe 0.22.0

### What is your web application and your TestCafe test code?
I can't put the actual tests on here but I could probably make a sample eventually.  I'm afraid though that the problem is possibly Node v6.10.3 or maybe Windows 10
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   0.23.1
* node.js version:                    6.10.3
* command-line arguments:  
* browser name and version: Chrome 70
* platform and version:          Windows 10
* other:

**Comment by AndreyBelym** [comment]
Unfortunately, I can't reproduce this behavior. Could you please provide a [HAR report](https://community.box.com/t5/Managing-Content-Troubleshooting/How-to-Generate-a-HAR-File-in-Chrome-IE-Firefox-and-Safari/ta-p/366) or record a screencast of your test session?

Judging by the description, the problem can be caused by Chrome's background tabs throttling feature. When Chrome suspends a background tab, it can't respond to the TestCafe server and thus can't execute any test command. Try to specify the `--disable-background-timer-throttling` flag in the TestCafe CLI parameters:
```
testcafe "chrome --disable-background-timer-throttling" tests.jd
```
and manually focus each Chrome window when it is opened.

**Comment by dbschwartz** [comment]
Hi @AndreyBelym ,

Thank you so much for your response.  I don't think the Chrome background tabs throttling feature is the issue, because I tried the tests in concurrency with Firefox and was also getting the same problems.

What's strange is that concurrency works if things are simple. I tried to run concurrency if only one test is used and it worked fine.
 
I tried tests in https://github.com/DevExpress/testcafe/tree/master/examples/basic , and they also worked fine.


I then added two roles which caused the tests not to update status on the console till the end, but eventually they did.

However once I added a test-cafe-vue-selector it repeated the same behavior.  Essentially the test code runs, but the status only gets updated for the first or second tests and the process then hangs indefinitely.

So I think the problem is with the latest version of TestCafe (0.23.1) and testcafe-vue-selectors.

I pushed up the code to my GitHub [here](https://github.com/dbschwartz/test-cafe-error-demo).  

You can clone and just run npm test to reproduce.  Thanks so much again!

-Dave

**Comment by AndreyBelym** [comment]
Thank you for your feedback! 

I've found that your example works fine with the `-c 2` argument on my machine. The relation between resources of your machine and the maximum number of browsers that you can use in a testing session is not linear. We will try to keep TestCafe responsive even when the performance capabilities are not enough to run all requested browsers and use browser resources more efficiently in no article here concurrency mode.

**Comment by dbschwartz** [comment]
My pleasure!

What's interesting here though is if you run these tests with Test Cafe v 0.22.0, everything finishes.   This repo illustrates problems with my current tests because they run concurrently in v 0.22.0 with ```-c 4``` without a hitch, but they become problematic when run concurrently with TestCafe 0.32.1 with ```-c -4```.

I made another repo with everything being same except using Test Cafe v 0.22.0 that runs in a stable state with 4 concurrent instances if you'd like to check it out:  https://github.com/dbschwartz/test-cafe-error-demo-stable

Note the test statuses take about 10 seconds before they start updating, but they eventually do and everything finishes and closes as normal.

My guess is that maybe there was some new server code introduced that might have lent itself to this.  Perhaps it's related to handling the unhandled promise rejection errors that were happening in concurrency before.  Again just a guess.

When I have use concurrency in other applications, its usually recommended to somewhat match instances with the number of cores on the machine, maybe using one less, i.e. If there are 7 cores, use  6 instances, etc.. I have been testing on machines with more than 4 processors.  Should Test Cafe be run fairly conservatively with concurrency?

Thank you so much for all your help!

**Comment by dbschwartz** [comment]
Apologies if you recently cloned the repo, my changes weren't pushed till now.  The other abnormal thing I realized is that with v 0.23.1 it seems only 2 of the concurrent instances are actually being used during the test execution.  The other 2 just seem to be idle on the Test Cafe example page for most of the test run without any actions, commands, assertions being run.  Granted this isn't the ideal scenario, but still strange none-the-less.  This does not happen in v 0.22.0

**Comment by dbschwartz** [comment]
Also, after I run concurrency with ```-c -4``` in v 0.22.0 I also get the following:
(node:15240) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit

This is just a warning, but might concern some users.  Maybe those who use concurrency should increase their max listeners in Node.

**Comment by AndreyBelym** [comment]
I tried to reproduce the problem with `testcafe@0.23.3-alpha.4` on my machine but it seems to be fixed. Could you please try to update the TestCafe version in your `package.json` and run tests in your environment?

**Comment by dbschwartz** [comment]
Yes!! I tried it!  Looks great!!  Only thing I might want to add is these two tests seem to be failing randomly.  They fail on testcafe `0.22.0` too so I don't think it's due to a bug in the package.  I think perhaps maybe the Test Cafe Example site was updated (https://devexpress.github.io/testcafe/example/).  Might just want to update your [tests](https://github.com/DevExpress/testcafe/tree/master/examples) to reflect the change.  Minor, but just wanted to let you know.  Thanks again for all your help! Love this software.

![image](https://user-images.githubusercontent.com/8890954/50037689-55f27180-ffd1-11e8-86fd-76cbeb4f9e15.png)

**Comment by AndreyBelym** [comment]
@dbschwartz, it seems that the bug is caused by using a role in the test: https://github.com/dbschwartz/test-cafe-error-demo-stable/blob/master/tests/testsCafeExamples1/test3.js#L7. I've created separate ticket #3232  about this issue.
