### ISSUE TITLE
The Smart Assertion Query Mechanism doesn't seem to wait to evaluate a full expression

### ISSUE THREAD

**Issue by danh293** [DevExpress/testcafe#3104]
### What is your Test Scenario?
I would expect to be able to make assertions on attributes of DOM nodes without having to `await` the Selector. It seems to me as though the Smart Assertion Query Mechanism does not resolve the entire expression before asserting.

### What is the Current behavior?
Here is a test I want to be able to write, but it fails:
```
test("This test does not work", async t =>
  await t.expect(Selector(".my-class").attributes.myattribute).eql("Attribute value"));
 ```
Making the change below fixes the test:
```
test("This test does work", async t =>
  await t.expect((await Selector(".my-class")()).attributes.myattribute).eql("Attribute value"));
 ```
 
### What is the Expected behavior?
I expect the Smart Assertion Query Mechanism to do the awaiting for me, without having to specify it manually.

### Your Environment details:
 
* testcafe version:                   0.23.1

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe). StackOverflow is an amazing platform for users to ask and answer questions: the community will see and answer your question there.

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing))

The Smart Assertion Query Mechanism works only for the [DOM Node state properties](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/dom-node-state.html), not for their subproperties. So you need to use the `await` keyword for the `Selector.attributes` property and then use a specific attribute in the assertion:
```js
  await t.expect((await Selector(".my-class")().attributes).myattribute).eql("Attribute value"));
```

**Comment by danh293** [comment]
Thanks for clarifying that @AndreyBelym :)

I still maintain that the API would be clearer if the Smart Assertion Query Mechanism could handle subproperties too, but your suggestion is cleaner than what I was using, so thanks.
