### ISSUE TITLE
testcafe run does not react to proxy error

### ISSUE THREAD

**Issue by joma74** [DevExpress/testcafe#3105]
### What is your Test Scenario?
Use testcafe behind a gateway proxy; For e.g. Chrome the local OS proxy settings are misconfigured, such that browser requests are not routed to the local host, but to the gateway proxy.
 
### What is the Current behavior?
testcafe run does not react if establishing a tunnel via proxy server failed.  It keeps running indefinitely.

But browser console displays _(which got me on the right track what went wrong; nevertheless, the test run hangs indefinitely)_
```
sockjs.js:1672 WebSocket connection to 'ws://192.168.1.106​:34631/8Nmi_M52g!w!http%3A%2F%2Flocalhost%3A4001/http://localhost:4001/sockjs-node/020/qdi2beg1/websocket' failed: Establishing a tunnel via proxy server failed.
r.WebSocket.r.WebSocket @ hammerhead.js:7
WebSocketBrowserDriver @ sockjs.js:1672
WebSocketTransport @ sockjs.js:2928
SockJS._connect @ sockjs.js:827
SockJS._receiveInfo @ sockjs.js:801
g @ sockjs.js:66
EventEmitter.emit @ sockjs.js:86
(anonymous) @ sockjs.js:566
g @ sockjs.js:66
EventEmitter.emit @ sockjs.js:86
(anonymous) @ sockjs.js:373
g @ sockjs.js:66
EventEmitter.emit @ sockjs.js:86
xhr.onreadystatechange @ sockjs.js:1586
wrapFn @ zone.js:1182
ZoneDelegate.invokeTask @ zone.js:421
Zone.runTask @ zone.js:188
ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1507
globalZoneAwareCallback @ zone.js:1533
``` 
 
### What is the Expected behavior?
testcafe does fail the the run
 
### What is your web application and your TestCafe test code?
Not applicable, may happen anywhere; depends on other environment settings(gateway proxy and misconfigured local OS proxy settings and Chrome, which relies on those settings)

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 fixture(fixtureName)
  .page("http://localhost:4001/index.html")
  .beforeEach(async () => {
    await waitForAngular()
  })
...
...
```
</details>

<details>
<summary>Your complete test report:</summary>
```
There is none
```
</details>

<details>
<summary>Screenshots:</summary>

```
There are none
```
</details>

### Steps to Reproduce:
1. Have a gateway proxy
2. Have your browser/OS relay calls to your local IP to some gateway proxy 
3. Run testcafe
4. See run indefinitely run; On browser console, the error as in ``Current behavior is logged 
 
### Your Environment details:
 
* testcafe version:                   0.23.1
* node.js version:                    v10.13.0
* command-line arguments:  `testcafe 'firefox:headless,chrome:headless --no-sandbox --disable-gpu' -S -s $npm_package_config_screenshots -p $npm_package_config_screenshot_path_pattern -r spec,xunit:$npm_package_config_reports/report.xml src/tests/index-test.js`
* browser name and version: HeadlessChrome 70.0.3538,  Firefox 63.0.0
* platform and version:          Ubuntu 14.04.5 LTS
* other:                                   OS Proxy Settings for Chrome, Gateway proxy

**Comment by AndreyBelym** [comment]
Thank you for your feedback! I need some time to simulate your environment with a gateway proxy. However, it will be really helpful if you can generate a [HAR report](https://community.box.com/t5/Managing-Content-Troubleshooting/How-to-Generate-a-HAR-File-in-Chrome-IE-Firefox-and-Safari/ta-p/366) for a problematic test session.
 
Also, please note that TestCafe already has a timeout to prevent stalling builds in the case of non-responding browsers, but it's big - 2 minutes in older TestCafe versions and about 6 minutes in the latest (v0.23.0) TestCafe version due to the [Restart on Browser Disconnection](https://github.com/DevExpress/testcafe/blob/master/CHANGELOG.md#gear-browsers-are-automatically-restarted-when-they-stop-responding-1815) feature. Maybe you didn't notice that browsers were restarting because they were in headless mode, and didn't wait enough to get the test session terminated. So could you please try to run browsers in non-headless mode, and wait for more than 6 minutes to be sure that browsers are not restarted and the test session is not terminated?

**Comment by joma74** [comment]
Attached is the HAR report [192.168.1.106.har.zip](https://github.com/DevExpress/testcafe/files/2578140/192.168.1.106.har.zip) covering nearly 9 minutes. It was run as requested. What i observed and what i believe one may derive from the log, is that the browser did neither restart nor was the test session terminated.

Other observations are

Case 2 
If the test is started via a not reachable proxy server e.g. `chrome --proxy-server="1.2.3.4"`, then gives the behaviour @AndreyBelym  mentioned 
```
joma@edison:~/entwicklung/nodews/angular-ultimate-pro$ cd /home/joma/entwicklung/nodews/angular-ultimate-pro ; /home/joma/bin/node --inspect-brk=39592 node_modules/testcafe/bin/testcafe.js "chrome --proxy-server=\"1.2.3.4\"" --speed 0.75 -S -s target/reports/screenshots/actual -p '${FIXTURE}/${TEST}/${USERAGENT}/${FILE_INDEX}.png' /home/joma/entwicklung/nodews/angular-ultimate-pro/src/tests/index-test.js
Debugger listening on ws://127.0.0.1:39592/23bbadce-19ec-4f47-bc05-6b240fdc29c3
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
```

Case 3 
The same behaviour seems to happen very regularly if i put a breakpoint on some statement of a test, and open the developer tools on the then opened browser. After continueing the debugger, the browser sends heartbeats, and the test never ends; plus the browser did neither restart nor was the test session terminated._ 

Case 4,5
Btw, the same behaviour happens 
- in testcafe-live after the first re-run(see other testcafe issues)
- waiting for more than 13 seconds on any breakpoint(see other testcafe ​issues)
