### ISSUE TITLE
Jenksins Job will not complete with testcafe@0.23.2

### ISSUE THREAD

**Issue by ericenders** [DevExpress/testcafe#3110]
### What is your Test Scenario?
Any test will not complete on Jenkins.  Tests complete when I run it locally. 
 
### What is the Current behavior?
The test just spins until I abort the job.  I let the test run for hours until I finally aborted.
 
### What is the Expected behavior?
Move on to the next stage of the build process
 
### What is your web application and your TestCafe test code?
N/A

### Steps to Reproduce:
Use testcafe@0.23.2 and run Jenkins Pipeline Build 

.
 
### Your Environment details:
 
* testcafe version:                   0.23.2 
* node.js version:                     6.2.0

**Comment by ericenders** [comment]
I have advised my team to specify using 0.21.1 which I know works well with Jenkins.

**Comment by AndreyBelym** [comment]
Please provide additional information to help us reproduce and examine the problem:
 - The name and version of the operating system installed on the machine with your Jenkins server;
 - Versions and names of browsers installed on the machine with your Jenkins server;
 - Configuration files of the test task;
 - The latest TestCafe version that works well in your Jenkins environment.

You can also perform some steps to debug the problem:
 - Try to connect to your Jenkins server via SSH and run browsers manually.
 - Try to connect to your Jenkins server via SSH and run the `testcafe -b` command.

**Comment by ericenders** [comment]
Hi Andrey,

I think this issue is very similar to https://github.com/DevExpress/testcafe/issues/3114.  

Test Cafe and node.js versions are stated above.

operating system: MacOS and Windows 10
browser: Chrome Version 69.0.3497.100
latest working version: 0.21.1

I am not able to provide config files nor allow to share our tests.

**Comment by dlangerenken** [comment]
Seeing similar issues in our Jenkins/Docker environment. 
In 0.23.2 it just hangs after finishing the tests. I went with 0.21.1 as well and don't see any issues here.

I also tested versions between 0.23.2 and 0.21.1. 0.21.1 - 0.23.1 seem to work fine - only 0.23.2 hangs for me.

**Comment by AndreyBelym** [comment]
I tried to run a build with Jenkins in a Windows environment, and it was terminated successfully. Thus I think that the problem can be reproduced only with a Jenkins agent running in Docker, and I need additional time to set it up.

Issue #3114 seems to be very similar to the problem we are discussing here, and I think that both of them have the same cause. Please perform the steps described in [this comment](https://github.com/DevExpress/testcafe/issues/3114#issuecomment-439072307).

**Comment by ericenders** [comment]
I have added the dependencies and tried with 0.23.2.  It still doesn't work.  @dlangerenken does it work for you?  I have tested and it does work with 0.23.1.

**Comment by rvyshnevskyi** [comment]
Noticed similar behaviour with tc@0.23.2 & node@10 along with Travic-CI, but with node@8 the combo works just fine
