### ISSUE TITLE
Function keys press with TestCafe

### ISSUE THREAD

**Issue by sophiecdd** [DevExpress/testcafe#3113]
As the Function keys are not listed in the supported key type in the document, I assume this is not supported by .pressKey, if so, is there any work around?

**Comment by AndreyBelym** [comment]
This thread appears to be a duplicate of #1887. Please use the original thread instead of this issue to get notifications about our progress with implementing this feature.

**Comment by sophiecdd** [comment]
Thanks Andrey for reply. Sorry I didn't get to read the feature enhancement board earlier, wondering do we have a timeline on the implementation of this feature, I see it was logged a year ago, any updates? If there any work around you would suggest?
