### ISSUE TITLE
testcafe-live does not work with latest version

### ISSUE THREAD

**Issue by hdorgeval** [DevExpress/testcafe#3121]
I opened an issue about testcafe-live here because it seems that the `testcafe-live` repo is not monitored by the TestCafe team.

Issue details are here: https://github.com/DevExpress/testcafe-live/pull/30

Thanks

**Comment by AndreyBelym** [comment]
I apologize for our delayed response. We were a bit overloaded this week.
 
You've done a great job in your PR - thank you! We will need to discuss some of your points and this may take some time. I will keep you informed of our progress.

**Comment by AndreyBelym** [comment]
This issue can be considered closed since `testcafe-live` was merged in the main TestCafe repository in `v1.0.0.`: [Live mode](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/live-mode.html).
