### ISSUE TITLE
Unable to get page url

### ISSUE THREAD

**Issue by anandxp** [DevExpress/testcafe#3125]
Hi TestCafe team,
I am not able to retrieve the current url as a string using TestCafe. 
`import { Selector,ClientFunction } from 'testcafe';

fixture `Getting Started`
    .page `nucleus.cantiz.com`;

test('Click on Sign-In', async t => {
	  await t
	  .click('#site-sign-in');
	const getLocation = ClientFunction(() => document.location.href);
	await t.expect(getLocation()).contains('identity');
	console.log('Loc is : '+getLocation);

});

`

While i am trying to print the URL only on console, below is getting printed.
![image](https://user-images.githubusercontent.com/21304150/48566935-06614d00-e922-11e8-96e8-93da78267ab6.png)

I am able to compare the value of url using contains function. But my purpose is to retrieve this url and pass to an API call using mochaJs. (Similar functionality of driver.getCurrentUrl() function in Selenium that returns url as a String ). 

Thanks in Advance
Anand Xavier

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing]()). This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.
 
You can also try to find a similar question by [using the [testcafe] tag](https://stackoverflow.com/questions/tagged/testcafe). For example, I think that this is what you were looking for: [Write current URL to console in TestCafe](https://stackoverflow.com/a/52952716/5114901).
