### ISSUE TITLE
Implement config file

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#3131]

**Comment by miherlosev** [comment]
After discussion, we decide to implement the following algorithm:
* `.testcaferc.json` is a name of the configuration file.
* `<browser_name>` and `<sources>` parameters become optional.  I.e. it's a possible to run TestCafe with `testcafe` command.
* look in the current directory (`process.cwd()`) `.testcaferc.json`. If it exists then read options from it.
* if there are user-defined options then merge them with options from configuration file and show the inform message 'The values for <option comma-separated names> from the configuration file will be ignored'.
* run TestCafe

**Comment by miherlosev** [comment]
Implemented in https://github.com/DevExpress/testcafe/pull/3147
