### ISSUE TITLE
Allow reporter plugin to get assertion message no matter it is passed or failed.

### ISSUE THREAD

**Issue by nqwang** [DevExpress/testcafe#3133]
### What is your Test Scenario?
In my case, there are more than one assertion in one test, but if all assertion are passed, I can only get one passed test information. I would like to get all assertion message information, and put on my reporter.

### What are you suggesting?
Expose more information on testRunInfo object.

**Comment by AlexKamaev** [comment]
For now, we don't have any plans to modify our reporter mechanism to allow passing an assertion message to the report. However, you can pass any information you want via `fixture.meta` or `test.meta` method. Please refer to the following articles:

[Specifying Testing Metadata](http://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#specifying-testing-metadata)
[reportTestDone](http://devexpress.github.io/testcafe/documentation/extending-testcafe/reporter-plugin/reporter-methods.html#reporttestdone)

I've prepared a sample example to demonstrate the solution:
```JS
fixture `test`
    .page `http://example.com`;
 
const test1meta = {
    assertion1: 'True is equal to True',
    assertion2: 'False is equal to False'
}
 
test.meta(test1meta)
('test', async t => {
    await t.expect(true).eql(true, test1meta.assertion1);
    await t.expect(false).eql(false, test1meta.assertion2);
})
```

**Comment by nqwang** [comment]
I have read this help from website, but I would like to get assert message. In the Assertion API, i can pass a message in expect method, such as below code.

```
await t
    .expect({ a: 'bar' }).eql({ a: 'bar' }, 'this assertion will pass')
    .expect({ a: 'bar' }).eql({ a: 'foo' }, 'this assertion will fail');
```

I want to get "this assertion will pass" in report.

**Comment by AlexKamaev** [comment]
I understand that passing an assertion message through our reporter mechanism would be more convenient, but it is unlikely that we will implement it in the near future. Using metadata to pass something to the report seems to be the only workaround I can suggest.

**Comment by nqwang** [comment]
@AlexKamaev Thanks for your feedback. If I use metadata to pass information to report. Is there a way to set metadata after test completed. See below sample code.
```
let vpCount = 10;
test
.meta({
    Id: `${vpCount}`,
})
('Sample', async t => {
    vpCount = 13
});
```
In this code, I can only get 10 in report. But I want to get 13 in report. Is there any solution for this?

**Comment by AlexKamaev** [comment]
Metadata is not suitable for this purpose and cannot be changed during the test run.
You can try to create a `shared-module.js` module :
```JS
exports.sharedInfo = {}
```
Then import it in your test file and modify the `sharedInfo` object:
```JS
import { sharedInfo } from './shared-module';

fixture `test`
    .page `http://example.com`;

test('test1', async t => {
    sharedInfo.id = 5;
    await t.click('h1');
});

test('test2', async t => {
    sharedInfo.test = 5;
    await t.click('h1');
});

test('test3', async t => {
    sharedInfo.id = 10;
    sharedInfo.test = 10;
    await t.click('h1');
});
```
Here I create a module that will be shared between the test file and the reporter.
Then in the reporter you can import `sharedInfo`:
```JS
var sharedInfo = require('../path-to/shared-module.js');
```
and modify the `reportTestDone` method:
```JS
reportTestDone: function reportTestDone(name, testRunInfo, meta) {
    console.log(JSON.stringify(sharedInfo));
    ....
```
I've got the following report:
```JS
 test
{"sharedInfo":{"id":5}}
 √ test1
{"sharedInfo":{"id":5,"test":5}}
 √ test2
{"sharedInfo":{"id":10,"test":10}}
 √ test3
```

**Comment by nqwang** [comment]
@AlexKamaev Thanks for your feedback. This workaround can help me pass information to report. But this workaround is not very friendly for both reporter and test scripts. They need to have an agreement for shared data format. The purpose for this requirement is that I want to get total vp account, passed vp account, failed vp account and blocked vp account to report. Is there any other convenience way to get these information? 

Here is an sample.
```
fixture `test`
    .page `http://example.com`;

test('test1', async t => {
    await t.
        .expect('string1').eql('string1')
        .expect('string2').eql('string2')
        .expect('string3').eql('string31') //Failed vp
        .expect('string4').eql('string4')
});
```
I would like to get a result like total vp is 4, passed vp is 2, failed vp is 1 and blocked vp is 1 in report.

**Comment by AlexKamaev** [comment]
Thanks for the provided example. At present, you can pass some information from a test to a report only using the `metadata`. However, it does not allow passing any dynamic data. There is no other valid mechanism, so using the suggested workaround is the most optimal approach.

**Comment by nqwang** [comment]
@AlexKamaev Anyway, thanks for your support. Looking forward TestCafe will have a feature for verfication point. 👍
