### ISSUE TITLE
Can not set public ip on an Microsoft Azure virtual machine

### ISSUE THREAD

**Issue by nqwang** [DevExpress/testcafe#3134]
### What is your Test Scenario?
I want to setup TestCafe on a Microsoft Azure VM, and allow tester to access remote server from local machine.
 
### What is the Current behavior?
When I set host name to the public ip or DNS name, TestCafe can not start up. It will shows error below.
```
testcafe remote ./e2e/src/*.e2e.spec.ts --hostname xxx.eastus2.cloudapp.azure.com
Using locally installed version of TestCafe.
ERROR The specified "xxx.eastus2.cloudapp.azure.com" hostname cannot be resolved to the current machine.

Type "testcafe -h" for help.

```
 
### What is the Expected behavior?
TestCafe can works on Azure VM.

The root cause is TestCafe check the hostname is valid or not in index.js file.
```
async function getValidHostname (hostname) {
    if (hostname) {
        const valid = await endpointUtils.isMyHostname(hostname);

        if (!valid)
            throw new GeneralError(MESSAGE.invalidHostname, hostname);
    }
    else
        hostname = endpointUtils.getIPAddress();

    return hostname;
}
```
But from Azure VM design, the hostname is not a DNS name.
 
### What is your web application and your TestCafe test code?

Not applicable.

### Steps to Reproduce:
1. Start a Azure VM (Ubuntu Server)
3. Execute `testcafe remote ./e2e/src/*.e2e.spec.ts --hostname xxx.eastus2.cloudapp.azure.com`
4. See the error...
```
Using locally installed version of TestCafe.
ERROR The specified "xxx.eastus2.cloudapp.azure.com" hostname cannot be resolved to the current machine.

Type "testcafe -h" for help.

```
 
### Your Environment details:
 
* testcafe version:                   0.20.1
* node.js version:                    v8.10.0
* command-line arguments:  testcafe remote ./e2e/src/*.e2e.spec.ts --hostname xxx.eastus2.cloudapp.azure.com
* browser name and version: Not Applicable
* platform and version:          Ubuntu 18.04.1 LTS
* other:                                   None

**Comment by nqwang** [comment]
I am trying a Windows OS on Azure today, and I found a workaround for TestCafe is that to set full DNS name to 127.0.0.1 on hosts file to avoid computer name check. 

So that, I think this solution could also apply on Ubuntu OS, but I am not an expert on Linux OS. Maybe some Linux guys can also set this on Linux OS.

**Comment by AndreyBelym** [comment]
Thank you for your inquiry! I think that we already have a feature suggestion that covers your request: https://github.com/DevExpress/testcafe/issues/1886

Your workaround for Windows is brilliant. For Linux, you can use the `hostname` command to change the machine name and pass the hostname check:
```sh
hostname xxx.eastus2.cloudapp.azure.com
testcafe --hostname xxx.eastus2.cloudapp.azure.com ...
```
