### ISSUE TITLE
Ability to run code every time a role is used

### ISSUE THREAD

**Issue by marcin-chwedczuk-meow** [DevExpress/testcafe#3135]
In my environment from time to time we must test localization. This usually involves changing user language and checking that screen contains properly localized values.

So far we were successful using Roles to log in particular users (admins, regular users etc.) into the application. Unfortunately Roles currently cannot be used to reset additional users settings like a language, which in my application is automatically saved to the user profile after it is changed. 

Good test practices suggest that we should arrange all settings before test starts. Ideally I wold like to just call `useRole` to both login the user and reset all user settings instead of relaying on `finally` blocks to clean up data after test ends. Of course I can use workaround from: https://github.com/DevExpress/testcafe/issues/2195 but I think this feature can also be useful to others. Ideally I should be able to pass additional block of code to the role that will be executed every time the role is used, alternatively there should be an option to make testcafe always initialize the role.

**Comment by AlexKamaev** [comment]
The TestCafe roles mechanism is intended only for manipulation with roles (you can save and restore cookies/storages).  It's unlikely that we will modify roles' API in the near future, so I recommend you use the workaround you mentioned:
```JS
async function UseRoleAndReset (role, t) {
    await t.useRole(role);
    // place your reset logic here
}
```
In addition, I need to mention the TestCafe [hooks](http://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#test-hooks) feature. The use of hooks could help you avoid copying your reset method to each test. It will allow you to reset your settings before each test starts or after each test finishes.
