### ISSUE TITLE
Can we Disable the mouse pointer ?

### ISSUE THREAD

**Issue by Harisharavindt** [DevExpress/testcafe#3139]

**Comment by AlexKamaev** [comment]
At the moment it is not quite clear why you need to disable the mouse pointer. Would you please describe your scenario in greater detail?
 
Anyway since the cursor is just an HTML element, use can use the following workaround:
```JS
import { ClientFunction } from 'testcafe';
 
fixture `test`
    .page `http://example.com`
    .beforeEach(async t => {
        await disableCursor();
    });
 
const disableCursor = ClientFunction(() => {
    var styleElement = document.createElement('style');
    styleElement.innerHTML = '.cursor-hammerhead-shadow-ui { display: none !important }';
    document.head.appendChild(styleElement);
});
 
test('test', async t => {
...
});
```
Here, I add CSS to the page before each test starts. Note, since in a general case, it is hard to predict what unexpected results adding this CSS may produce, I suggest that you carefully check this prior to integrating this solution into your project.

**Comment by Harisharavindt** [comment]
Thanks for the solution ....  But actually my scenario is to reduce the size of the Cursor pointer .Can you help me  with this Issue .

**Comment by AlexKamaev** [comment]
You can modify the suggested workaround. Since `.cursor-hammerhead-shadow-ui` is just an HTML element you can apply any CSS styles including `width` and `height` to it.

**Comment by Harisharavindt** [comment]
Thanks Lot :)

**Comment by Harisharavindt** [comment]
Hi Alex ,Disabling the Mouse Pointer works Fine :)
 But **reducing the size of the Mouse didn't work** with the workaround . I have added the code can you Look into it 


import { ClientFunction } from 'testcafe';
import { Selector } from 'testcafe';
 
fixture `test`
    .page `http://example.com`
    .beforeEach(async t => {
        await disableCursor();
    })
    
 
const disableCursor = ClientFunction(() => {
    var styleElement = document.createElement('style');
    styleElement.innerHTML = '.cursor-hammerhead-shadow-ui {width:10px; height:40px }';
    document.head.appendChild(styleElement);
});
 
test('test', async t => {
await t.click(Selector('body > div > p:nth-child(3) > a'))
await t.click(Selector('#header > div.navigation > ul > li:nth-child(1) > a'))
});

**Comment by AlexKamaev** [comment]
Add the `!important` rule as I did in my example to override the existing CSS rules. I think you also need to change `background-image` to use the pointer image of a smaller size.
I should note that your last questions about CSS are not related to TestCafe. So, I kindly ask you to use [StackOverflow ](https://stackoverflow.com/) for this kind of questions. If you have a question about TestCafe I also recommend asking it on StackOverflow with the `testcafe` tag. Please use the following [link ](https://stackoverflow.com/questions/ask?tags=testcafe) for this.
