### ISSUE TITLE
How can I run multiple fixtures (one after the other, not concurrent)? 

### ISSUE THREAD

**Issue by Mihai0909** [DevExpress/testcafe#3148]
I have multiple fixtures (interaction between a website and a hybrid app) and I would like to have a test suite run (Smoke test, regression test ...) but I'm not sure how to do it. 

This is how my tests look like: 
![testcafe](https://user-images.githubusercontent.com/11134926/48910863-bdf1e400-ee79-11e8-860f-5dff232f3097.png)

What I want to do is run all tests (eg. CreatePollAndCloseIt.js, CreatePollPinAndDelete.js, CreateStreamAssertions.js and so on until the last one VotePollWhitelabel ) and get a report after. 

Thank you !

**Comment by AlexKamaev** [comment]
Thank you for your inquiry. This issue looks like a question that would be best asked on [StackOverflow](https://stackoverflow.com/) - an amazing platform to ask and answer questions.
 
We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)).
 
Please route your question to StackOverflow using the following [form](https://stackoverflow.com/questions/ask?tags=testcafe)
