### ISSUE TITLE
Unexpected end of input error appears during the `gulp build` task

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#315]
Sometimes the following error appears when the `gulp build` task is running:
```
SyntaxError: Cannot read config file: c:\Work\Git\testcafe-phoenix\package.json
Error: c:\Work\Git\testcafe-phoenix\package.json: Unexpected end of input
```

This appears when the `lint` task reads the `package.json` file while the `update-greenkeeper` task is rewriting it. 
I propose to use the `fs.writeFileSync` method instead of async version in the `update-greenkeeper` task to avoid this problem and possible collisions with some other task

**Comment by inikulin** [comment]
> I propose to use the fs.writeFileSync method instead

Sounds good to me
