### ISSUE TITLE
While running Testcafe-BDD test suite, the test run closes completely after running first feature

### ISSUE THREAD

**Issue by shariqMohammed92** [DevExpress/testcafe#3151]
The test automation suite was developed using Test cafe in BDD framework.

The issue faced is that after running my first feature file, the test run closes completely,testcafe version used is v0.23.2.Issue is also seen in the same version.

While downgrading test cafe version v0.20.5.The suite run perfectly, but no snippets where being generated for my features which has no step definition, still the suite runs completely 

Issue is seen across all platforms and browsers.

 ### What is the Current behavior?
Currently the test run completes after running my first feature.
 
### What is the Expected behavior?
I have almost 7 features and expecting to run all features and also to generate snippets for features which have no step definitions
 
The suite has been attached with issue PFA.Issue is seen while running attached suite.

### Steps to Reproduce:
Go to project folder

1. run- npm install
2.Once dependencies are downloaded, run - npm run test-firefox
3. Suite fails after first feature run.

Error:

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cantizconnect_ui-automation@1.0.0 test-chrome: `cucumber-js  --world-parameters "{\"browser\": \"chrome\"}"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cantizconnect_ui-automation@1.0.0 test-chrome script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 
### Your Environment details:
 
* testcafe version:  v0.23.2
* node.js version: v10.10.0
* command-line arguments: ' npm run test-{{browserName}}'
* browser name and version:  safari v 11.1.2
* platform and version:       masOS High Sierra v10.13.6

![error](https://user-images.githubusercontent.com/37373409/49005407-a58d0c80-f18c-11e8-9e02-461a9774f641.png)
[connect-ui-automation.zip](https://github.com/DevExpress/testcafe/files/2614848/connect-ui-automation.zip)

**Comment by shariqMohammed92** [comment]
The test automation suite was developed using Test cafe in BDD framework.

The issue faced is that after running my first feature file, the test run closes completely,testcafe version used is v0.23.2.Issue is also seen in the same version.

While downgrading test cafe version v0.20.5.The suite run perfectly, but no snippets where being generated for my features which has no step definition, still the suite runs completely 

Issue is seen across all platforms and browsers.

 ### What is the Current behavior?
Currently the test run completes after running my first feature.
 
### What is the Expected behavior?
I have almost 7 features and expecting to run all features and also to generate snippets for features which have no step definitions
 
The suite has been attached with issue PFA.Issue is seen while running attached suite.

### Steps to Reproduce:
Go to project folder

1. run- npm install
2.Once depend ices are downloaded, run - npm run test-firefox
3. Suite fails after first feature run.

Error:

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cantizconnect_ui-automation@1.0.0 test-chrome: `cucumber-js  --world-parameters "{\"browser\": \"chrome\"}"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cantizconnect_ui-automation@1.0.0 test-chrome script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 
### Your Environment details:
 
* testcafe version:  v0.23.2
* node.js version: v10.10.0
* command-line arguments: ' npm run test-{{browserName}}'
* browser name and version:  safari v 11.1.2
* platform and version:       masOS High Sierra v10.13.6

![error](https://user-images.githubusercontent.com/37373409/49005407-a58d0c80-f18c-11e8-9e02-461a9774f641.png)
[connect-ui-automation.zip](https://github.com/DevExpress/testcafe/files/2614842/connect-ui-automation.zip)

**Comment by Farfurix** [comment]
@shariqMohammed92 
I checked your test project and I can't reproduce this error after upgrading TestCafe to the latest alpha version. Please try
```
"testcafe ":" 0.23.3-alpha.1"
```
and let us know if it solves the issue.
