### ISSUE TITLE
unable to establish browser connections - In windows virutal machines

### ISSUE THREAD

**Issue by automation9006** [DevExpress/testcafe#3152]
### What is your Test Scenario?

Executing tests on windows virtual machines through Jenkins.
browsers- chrome and firefox
 
### What is the Current behavior?

When the jobs on Jenkins are executed we are getting the below error:
ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.

 
### What is the Expected behavior?

The job should run successfully, and these jobs where running before with any issues and suddenly we are facing this issue.
 
### What is your web application and your TestCafe test code?

 It is our internal application
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete test report:</summary>

[promotion-homepage-tests] Running batch script

c:\corp_prod_jenkins\workspace\test\promotions manager tests\promotion-homepage-tests>npm config set https-proxy=http://proxy.scee.net:3128/ 
[Pipeline] bat
[promotion-homepage-tests] Running batch script

c:\corp_prod_jenkins\workspace\test\promotions manager tests\promotion-homepage-tests>npm config set registry https://nexus.internal.scee.net/nexus/repository/npm-group/ 
[Pipeline] bat
[promotion-homepage-tests] Running batch script

c:\corp_prod_jenkins\workspace\test\promotions manager tests\promotion-homepage-tests>npm config set strict-ssl false 
[Pipeline] bat
[promotion-homepage-tests] Running batch script

c:\corp_prod_jenkins\workspace\test\promotions manager tests\promotion-homepage-tests>npm config set always-auth true 
[Pipeline] withCredentials
[Pipeline] {
[Pipeline] bat
[promotion-homepage-tests] Running batch script

c:\corp_prod_jenkins\workspace\test\promotions manager tests\promotion-homepage-tests>npm config set _auth  amVua2lucy10ZXN0OmRYV1lSRWpjcXZMbTlZczlibWE3Mw== 
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] bat
[promotion-homepage-tests] Running batch script

c:\corp_prod_jenkins\workspace\test\promotions manager tests\promotion-homepage-tests>npm install 
npm WARN autotest@1.0.0 No repository field.

added 4 packages from 3 contributors and removed 3 packages in 7.112s
[Pipeline] bat
[promotion-homepage-tests] Running batch script

c:\corp_prod_jenkins\workspace\test\promotions manager tests\promotion-homepage-tests>npm run testcafe firefox, -- --tEnv sitEnv tests/promotions/homePageTest.spec.js -r html:./reports/reports.html 

> autotest@1.0.0 testcafe c:\corp_prod_jenkins\workspace\test\promotions manager tests\promotion-homepage-tests
> node ./node_modules/testcafe/bin/testcafe.js --hostname 127.0.0.1 --proxy proxy.scee.net:3128 --proxy-bypass 127.0.0.1:8080,localhost:80,localhost --ports 8091,8092 "firefox," "--tEnv" "sitEnv" "tests/promotions/homePageTest.spec.js" "-r" "html:./reports/reports.html"

Environment is: undefined
ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.

Type "testcafe -h" for help.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! autotest@1.0.0 testcafe: `node ./node_modules/testcafe/bin/testcafe.js --hostname 127.0.0.1 --proxy proxy.scee.net:3128 --proxy-bypass 127.0.0.1:8080,localhost:80,localhost --ports 8091,8092 "firefox," "--tEnv" "sitEnv" "tests/promotions/homePageTest.spec.js" "-r" "html:./reports/reports.html"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the autotest@1.0.0 testcafe script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\windows\system32\config\systemprofile\AppData\Roaming\npm-cache\_logs\2018-11-23T14_26_03_484Z-debug.log
[Pipeline] publishHTML
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level c:\corp_prod_jenkins\workspace\test\promotions manager tests\promotion-homepage-tests\reports to /u01/jenkins/jobs/test/jobs/promotions manager tests/jobs/promotion-homepage-tests/builds/184/htmlreports/Promotions_20Functional_20Tests_20Report
```

```
</details>

<details>
<summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/17795630/49019148-2c3deb80-f185-11e8-9750-99bbec5664ef.png)

 Just captured this on, one of the VM, when the job is executed the VM receives the request and checkouts out the latest code from git repo  to it's work space and execute the pipeline script.
the command to execute the script , 
Eg: npm run testcafe firefox, -- --tEnv sitEnv tests/promotions/homePageTest.spec.js -r html:./reports/reports.html

When I logged in to VM to see whats happening with the tests, I have notices the browser opens but it fails to execute the test and hangs on this blank page.

<strong> Note:  These tests would able to run  with out any issues on my local PC</strong>
```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   0.21.1
* node.js version:                     6.10.0
* command-line arguments:  
* browser name and version:  Firefox and chrome latest
* platform and version:           windows 7 and windows 10 ( they are virtual machines)
* other:

**Comment by Farfurix** [comment]
@automation9006, we have already experienced an issue with a similar error. Please try to run your tests with the TestCafe `testcafe@0.23.3-alpha.1` version and let us know if it solves the issue.
