### ISSUE TITLE
Add way to exclude tests using pattern using -ET like -T

### ISSUE THREAD

**Issue by jiteshsojitra** [DevExpress/testcafe#3153]
Add way to exclude test pattern when using -T and -ET to exclude. We have many tests and some of the set works at X time and set of tests at Y. When Y set of test runs we want to exclude X set of tests to save the time and duplication. We can add various patterns in the test and deal that way but many pattern requires unnecessary groups and test description goes messy for e.g.

# Tests:
    test('X0 | Smoke | Test1')
    test('X1 | Smoke | Test2')
    test('X2 | Sanity | Test3')
    test('X3 | Sanity | Test4')
    test('X0 | Sanity | Test5')

# CLI Examples:

    testcafe -e chrome -T X0 -ET Smoke
    testcafe -e chrome -T Smoke -ET X1

### What are you suggesting?
I suggest to add additional pattern like -ET.

### What alternatives have you considered?
No alternatives that TestCafe provides using exclude option in CLI.

**Comment by Farfurix** [comment]
This is not something we have planned to do in the near future. Note that TestCafe helps you organize your tests using the [key-value metadata](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#specifying-testing-metadata):
1. https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--test-meta-keyvaluekey2value2.
2. https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--fixture-meta-keyvaluekey2value2.

Simple tests organization example:
```
test.meta({ device: 'mobile', env: 'production' })('Test1')
test.meta({ device: 'desktop', env: 'production' })('Test2')
test.meta({ device: 'mobile', env: 'production' })('Test3')
test.meta({ device: 'desktop', env: 'development' })('Test4')
 
// Test1, Test3
testcafe chrome my-tests --test-meta device=mobile
// Test4
testcafe chrome my-tests --test-meta device=desktop,env=development
```
