### ISSUE TITLE
testcafe version 0.23.1 second test stacks if before test pause or doing request to server

### ISSUE THREAD

**Issue by benjamin33** [DevExpress/testcafe#3155]
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. start first test case 
2. before starting the second test wait 10 seconds or do api requests, to create new user for example
3. after testcafe back to browser, can't continue 
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by Farfurix** [comment]
@benjamin33 
It is difficult to see the cause of the problem having only the information you provided. In particular it is unclear how you implemented the timeouts you described ("before starting the second test"). Could you please provide a small sample project we can run locally and reproduce the problem you reported?

I also suggest that you add all information we request in the "bug report" template. This will help us reduce the number of turnarounds required to understand and reproduce the problem, and thus, will enable us to provide you with a solution faster.
