### ISSUE TITLE
Unable to find element by class through find method

### ISSUE THREAD

**Issue by arthurgeron** [DevExpress/testcafe#3156]
### What is your Test Scenario?
 
 I've elements that should behaviour the same way (which is what I was trying to test when I found out about this bug), they are identical and can only be differentiated by the class name of the parent div, therefore I need to first find the parent div then search for the element to test each one of them individually.

### What is the Current behavior?
 Searching for an element by classname from another element through the `find` method returns nothing. In this example Selector('svg').find('.find-me') doesn't work, even though an element with the `find-me` class is inside a svg element which is the only one present in the HTML code.

### What is the Expected behavior?
 It should be finding elements by class when using the `find` method.

### What is your web application and your TestCafe test code?

The problem can be replicated in [this repository](https://github.com/arthurgeron/testcafe-find-issue).

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Role, Selector } from 'testcafe';

const userRole = Role('http://localhost:1234', async () => {}, { preserveUrl: true });

fixture`Testcafe issue`
  .beforeEach(async (t) => {
    await t.useRole(userRole);
  });


test('Test selling charts', async (t) => {
  const svg = Selector('svg');
  // this works
  await t.expect(Selector('.find-me').exists).ok();
  // this doesn't
  await t.expect(svg.find('.find-me').exists).ok();
});

```
</details>

<details>
<summary>Your complete test report:</summary>

```
> testcafeproblem@1.0.0 test /home/ageron/Documents/Projects/testcafe-find-issue
> testcafe 'chrome -incognito' tests/functional --app "npm run server:dev" 

 Running tests in:
 - Chrome 70.0.3538 / Linux 0.0.0

 Testcafe issue
 ✖ Test selling charts

   1) AssertionError: expected false to be truthy

      Browser: Chrome 70.0.3538 / Linux 0.0.0

         11 |test('Test selling charts', async (t) => {
         12 |  const svg = Selector('svg');
         13 |  // this works
         14 |  await t.expect(Selector('.find-me').exists).ok();
         15 |  // this doesn't
       > 16 |  await t.expect(svg.find('.find-me').exists).ok();
         17 |});
         18 |

         at ok
      (/home/ageron/Documents/Projects/testcafe-find-issue/tests/functional/index.js:16:47)



 1/1 failed (4s)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testcafeproblem@1.0.0 test: `testcafe 'chrome -incognito' tests/functional --app "npm run server:dev" `
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the testcafeproblem@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ageron/.npm/_logs/2018-11-27T17_07_27_655Z-debug.log


```
</details>

### Steps to Reproduce:

1. Clone the repository linked at the start of this issue .
2. Execute `npm i` to intall packages and `npm run  test` to run functional tests.
3. See the error.
 
### Your Environment details:
 
* testcafe version:  0.23.2
* node.js version:  8.13.0
* command-line arguments:  `'chrome -incognito' tests/functional --app \"npm run server:dev\"`
* browser name and version: Chrome 70.0.3538.110
* platform and version:  Linux Ubuntu 18.04

**Comment by Farfurix** [comment]
@arthurgeron, please check your [project](https://github.com/arthurgeron/testcafe-find-issue/blob/master/src/index.html). There is no nested `div` in the `svg` tag in your result markup (`server:dev`):

![svg-div](https://user-images.githubusercontent.com/30019338/49207090-0b63d900-f3c5-11e8-93fa-6c515ccced93.PNG)

Your `svg.find('.find-me').exists` expression returns `false` in this markup case correctly.

Try adding the `foreignObject` element to you markup as follows (see https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject):
```
<svg>
    <foreignobject>
        <div class="find-me" />
     </foreignobject>
</svg>
```
In this case all your assertions are successful.
