### ISSUE TITLE
Finding an inline-flex element withText and regular expression does not work in Edge

### ISSUE THREAD

**Issue by Lukas-Kullmann** [DevExpress/testcafe#3159]
### What is your Test Scenario?
I would like to find an element on the page that matches a certain text. (i.e. `Selector('button').withText(/^text$/iu);`)
 
### What is the Current behavior?
The element is not found on the page if the element has

- display: inline-block
- a child element containing the text (e.g. a span)
- usually has display: inline (like button or a)

As far as I can tell, this only applies to Edge (not chromium, firefox or IE).
 
### What is the Expected behavior?
The element is found on the page
 
### What is your web application and your TestCafe test code?
<details>
<summary>Your tested Page:</summary>

 
```html
<!doctype html>
<head>
    <title>withText example</title>
</head>
<body>
<a style="display: inline-flex;"><span>text</span></a>
</body>
```
</details>

<details>
<summary>Your complete test code:</summary>

 
```js
import { Selector } from 'testcafe'

fixture('withText example').page('http://192.168.156.166:8080/index.html');

test('matching element', async t => {
  const button = Selector('a').withText(/^text$/iu);

  await t.expect(button.exists).ok('button does not exist!')
});
```

Note that it works if 

- you remove the `^` and `$` characters from the regex: `.withText(/text/iu)` or
- the button does not have `display: inline-flex` or
- the text is not inside the `span` element
</details>

<details>
<summary>Your complete test report:</summary>

```
 Running tests in:
 - Edge 17.17134.0 / Windows 10.0.0

 withText example
 ✖ matching element

   1) AssertionError: button does not exist!: expected false to be truthy

      Browser: Edge 17.17134.0 / Windows 10.0.0

          3 |fixture('withText example').page('http://localhost:8080/index.html');
          4 |
          5 |test('matching element', async t => {
          6 |  const button = Selector('a').withText(/^text$/iu);
          7 |
       >  8 |  await t.expect(button.exists).ok('button does not exist!')
          9 |});
         10 |
```
</details>

### Steps to Reproduce:

1. Serve the provided HTML as index.html on localhost:8080 (e.g. use http-server: `http-server .`)
3. Run tests in edge (`npx testcafe edge test.js`) → Test fail
4. Run tests in a different browser (`npx testcafe firefox test.js`) → Test runs
 
### Your Environment details:
 
* testcafe version:                   0.23.2
* node.js version:                    10.14.0
* command-line arguments:  (see steps to reproduce)
* browser name and version: Edge 17.17134.0
* platform and version:          Windows 10

**Comment by Farfurix** [comment]
@Lukas-Kullmann [`withText`](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/functional-style-selectors.html#withtext) related to the browser specific `innerText` property.

For example, in your case with the Chrome browser we have an extra newline symbol:
```
> document.querySelector('a').innerText
< "text
  "
```
Try to add `\s*` to your `RegEx`:
```
/^\s*text\s*$/iu.test(document.querySelector('a').innerText) === true
```
This inquiry is not related to TestCafe and the code above should also work in the browser natively.
