### ISSUE TITLE
Stream Logs From Docker Container

### ISSUE THREAD

**Issue by aboe026** [DevExpress/testcafe#3173]
### What is your Test Scenario?
We're using the `testcafe/testcafe` docker image to run our tests, and having it save the results to an xml file.

### What are you suggesting?
I'd like to have the container output the status of which test it is on (much like it does when running tests locally - i.e. not in the `testcafe/testcafe` docker image). Even though we're saving the test results to an xml file, it would still be nice to know where the tests are at, instead of having no indication of the progress.

### What alternatives have you considered?
None.

### Additional context
None.

**Comment by LavrovArtem** [comment]
Testcafe allows you to use [multiple reporters](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-r-namefile---reporter-namefile). You can simultaneously save results to an xml file and write to `stdout`. For example, you can try to run tests using the `-r spec,xunit:report.xml` flag configuration from our [documentation](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-r-namefile---reporter-namefile).
