### ISSUE TITLE
Comma separated values for device in test meta doesn't work

### ISSUE THREAD

**Issue by jiteshsojitra** [DevExpress/testcafe#3174]
I tried to run --test-meta with comma separated devices for e.g. { device: 'web,mobile' } but it doesn't work. Our objective is to run same tests in multiple devices and without duplicating device statement in the test meta.

### What is your Test Scenario?
test.meta({ device: 'web,mobile' })('Login to client', async t => {
 
### What is the Current behavior?
ERROR No tests to run. Either the test files contain no tests or the filter function is too restrictive.
 
### What is the Expected behavior?
Test meta matches with web or mobile should run.

What is the best solution you suggest other than duplication of device?
 
* testcafe version:  0.23.2
* node.js version: v8.12.0
* command-line arguments:  testcafe -e chrome . --test-meta device=web

**Comment by LavrovArtem** [comment]
The described behavior is unsupported. Meta is a key and just a value that should not be parsed. You can use a set of metadata entries if you want to combine device types, for example:
```js
test.meta({ mobileDevice: 'true', webDevice: 'true' })(`Test 1`, async t => { ... });
test.meta({ mobileDevice: 'true' })(`Test 2`, async t => { ... });
test.meta({ webDevice: 'true' })(`Test 3`, async t => { ... });
```
and use the following arguments:
```
--test-meta webDevice=true
--test-meta mobileDevice=true
--test-meta webDevice=true,mobileDevice=true
--test-meta mobileDevice=true,webDevice=true
```
 
Reference links:
[Specifying Testing Metadata](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#specifying-testing-metadata)
[--test-meta <key=value[,key2=value2,...]>](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--test-meta-keyvaluekey2value2)

**Comment by jiteshsojitra** [comment]
Here is the problem:

# Tests

    test.meta({ web: 'true', mobile: 'false', suite: 'sanity' })(`Create folder1`, async t => { ... });
    test.meta({ web: 'true', mobile: 'false', suite: 'smoke' })(`Create folder2`, async t => { ... });
    test.meta({ web: 'true', mobile: 'false', suite: 'smoke' })(`Create folder3`, async t => { ... });
    test.meta({ web: 'true', mobile: 'false', suite: 'functional' })(`Modify folder1`, async t => { ... });
    test.meta({ web: 'true', mobile: 'false', suite: 'functional' })(`Modify folder2`, async t => { ... });
    test.meta({ web: 'true', mobile: 'false', suite: 'functional' })(`Modify folder3`, async t => { ... });

# Test pattern:

Run tests where pattern matches to 'Create' and suite = sanity or smoke.

    testcafe -e -q chrome . -T 'Create' --test-meta 'web=true,suite=sanity,suite=smoke'

# Actual result (Only runs below 2 tests):

It looks like --test-meta only picks last 'suite=smoke' and intial ignores 'suite=sanity'. Is there any solution for performing OR operation instead of AND without defining another meta variable?

    test.meta({ web: 'true', mobile: 'false', suite: 'smoke' })(`Create folder2`, async t => { ... });
    test.meta({ web: 'true', mobile: 'false', suite: 'smoke' })(`Create folder3`, async t => { ... });

# Expected result (Run first 3 tests):

    test.meta({ web: 'true', mobile: 'false', suite: 'sanity' })(`Create folder1`, async t => { ... });
    test.meta({ web: 'true', mobile: 'false', suite: 'smoke' })(`Create folder2`, async t => { ... });
    test.meta({ web: 'true', mobile: 'false', suite: 'smoke' })(`Create folder3`, async t => { ... });

**Comment by AlexKamaev** [comment]
The metadata filtering mechanism does not support this behavior. It is based on the [ lodash.isMatch](https://lodash.com/docs/4.17.11#isMatch) function, which performs a partial deep comparison between the object and source to determine if the object contains equivalent property values. Thus you cannot pass two values of the same property to the filtering mechanism.
I think the best option to implement your own filtering mechanism is to use TestCafe API.
Please refer to the following [link](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#filter).
I also prepared an example to demonstrate this approach:
```JS
const createTestCafe = require('testcafe');
let testcafe         = null;

createTestCafe('localhost', 1337, 1338)
    .then(tc => {
        testcafe = tc;

        return testcafe.createRunner();
    })
    .then(runner => {
        return runner
            .src('test.js')
            .browsers('chrome')
            .filter((testName, fixtureName, fixturePath, testMeta, fixtureMeta) => {
                return testMeta.suite === 'sanity' || testMeta.suite === 'functional';
            })
            .run();
    })
    .then(() => {
        return testcafe.close();
    });

```
