### ISSUE TITLE
Uncaught exception: Error without stack trace

### ISSUE THREAD

**Issue by MiguelGPereira** [DevExpress/testcafe#3183]
### What is your Test Scenario?
Running a testcafe suite in circleci
 
### What is the Current behaviour?
Sometimes (unpredictably) there are tests that fail, without giving a descriptive message, testcafe just logs
```
1) Uncaught exception:

      Error

      Browser: Chrome 68.0.3440 / Linux 0.0.0
```
 
### What is the Expected behavior?
A stack trace of the error. I also tried adding the --skip-js-errors flag, to no success.
 
### Your Environment details:
 
* testcafe version:                  0.23.0
* node.js version:                    8.11.3
* command-line arguments:  chromium --no-sandbox --incognito --disable-web-security --user-data-dir --disable-save-password-bubble --skip-js-errors
* browser name and version: Chrome 68.0.3440
* platform and version:          the official TestCafe Docker image (testcafe/testcafe)

**Comment by LavrovArtem** [comment]
It seems like the error is related to the code of your site and to skip it, you need to use the `--skip-js-errors` flag, which you are currently using incorrectly. You need to pass it as a TestCafe flag, but you are passing it as a Chrome flag.

**Comment by MiguelGPereira** [comment]
Thank you, I will fix the flag to see if it works. But shouldn't the error include a stack trace?

**Comment by MiguelGPereira** [comment]
The error still happens sometimes. Current testcafe flags:
`-s /artifacts --selector-timeout 20000 --assertion-timeout 20000  --screenshots-on-fails --skip-js-errors -e`

**Comment by LavrovArtem** [comment]
> But shouldn't the error include a stack trace?

Usually an error has a stack trace, but, in some cases, the stack trace is empty.

The information we have does not allow us to determine why the error is raised. We need to examine your page to be able to give you any advice. Please provide us with a link to your web site, so that we can try to replicate the problem locally. In addition, please provide us with the full command you are using to start test and a link to your CircleCI build.

**Comment by Evilweed** [comment]
I'm experiencing the same issue.

**Happens with:**
chromium:headless --disk-cache-size=1 --disable-dev-shm-usage --disable-gpu --no-sandbox --incognito --enable-features=NetworkService,NetworkServiceInProcess --disable-features=VizDisplayCompositor\"

**Hapens with:**
chromium:headless

Docker in docker, using latest testcafe docker container. Latest version of testcafe.

![21E7BA51-39E6-4597-9CBE-407D539A4C0D](https://user-images.githubusercontent.com/5477821/66072690-cc0e9780-e555-11e9-91c9-1e240a430a8b.png)

**Comment by AlexKamaev** [comment]
We were not able to reproduce the issue at that time. If you can share your example with us to demonstrate the issue, we would appreciate it.

**Comment by sukhvinderb** [comment]
I am also seeing Uncaught Exception which makes my tests to fail. My test basically clicks on the links on the left panel of the page. It gives uncaught exception on certain links. Every time I run the the test, it fails on a different link
01/29/20 11:49:26    1) Uncaught exception:
01/29/20 11:49:26 
01/29/20 11:49:26       Error:
01/29/20 11:49:26 
01/29/20 11:49:26       Browser: Chrome 77.0.3865 / Linux 0.0.0

**Comment by AlexKamaev** [comment]
@sukhvinderb, this issue is closed. If you think that you found a bug, feel free to open a new issue in the GitHub repo [https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md)). Thank you for your cooperation.

**Comment by sukhvinderb** [comment]
I am using node version 10
