### ISSUE TITLE
Unable to launch chrome in headless on windows, when there is space in the path to executable

### ISSUE THREAD

**Issue by Mikuu** [DevExpress/testcafe#3185]
### What is your Test Scenario?
Use Testcafe to launch chrome in headless, but failed
```
testcafe "path:`C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`:headless" sandbox.js --proxy localhost:3128 --screenshots screenshots
Using locally installed version of TestCafe.
ERROR Was unable to open the browser "path:`C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`:headless" due to error.

Error: The specified browser name is not valid!
```
 
### What is the Current behavior?
It failed due to the browser name is not valid.

If I don't specify the 'headless', it's working well with the command:
```
testcafe "path:`C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`" sandbox.js --proxy localhost:3128 --screenshots screenshots
```
 
### What is the Expected behavior?
Need it works with headless option in Windows when the command line has space in the path to executable.
 
 
### Your Environment details:
 
* testcafe version:                   0.23.2
* node.js version:                    10.13.0
* browser name and version: chrome v66
* platform and version:          windows 7

**Comment by LavrovArtem** [comment]
The problem is connected not to the spaces in the path to a browser, but to a way the browser is run. Instead of the path:prefix, use a browser alias (chrome: in your case) and get rid of apostrophes. It works on my side with the following argument:

`"chrome:C:\Program Files (x86)\Google\Chrome\Application\chrome.exe:headless"`

**Comment by Mikuu** [comment]
@LavrovArtem ,

thanks for your reply, that makes it's working!

Happy to close this issue.
