### ISSUE TITLE
Docker image testcafe version

### ISSUE THREAD

**Issue by admglaser** [DevExpress/testcafe#3187]
It looks like the testcafe version in the latest/alpha docker image is outdated.

I get the following error while running the tests with it:
```
An error occurred in Selector code:
ReferenceError: builder is not defined
```
Code:
```
          5 |  return t
       >  6 |      .click(Selector('#secure'))
          7 |      .typeText('#loginname', login)
          8 |      .typeText('#password', password)
          9 |      .click('#login')
         10 |
```
This code runs fine locally with version 0.23.2.

**Comment by LavrovArtem** [comment]
I cannot reproduce this error. I am afraid this information is not sufficient to find the cause of the issue. Could you please provide a page or a small example so that we can reproduce it on our side?
