### ISSUE TITLE
File Upload - Click on Change selector doesn't open finder window 

### ISSUE THREAD

**Issue by filiplucian** [DevExpress/testcafe#3192]
### What is your Test Scenario?
I click on **the image**, it opens a Modal Window, click **change** and it opens a finder Window, choose the image and then click ok.

### What is the Current behavior?
Finder window won't open.

.click(Selector('a').withText('Change'))
 
### What is the Expected behavior?

Calling Selector('a').withText('Change') should open finder window.
 
### What is your web application and your TestCafe test code?

import { Selector } from 'testcafe';

fixture `testJS`
    .page `http://localhost:3000/dashboard/`;
    

test('New Test', async t => {
    await t
        .typeText(Selector('.form-group').find('[class^="form-control ng-pristine ng-untouched ng-empty ng-"]'), 'email')
        .pressKey('tab')
        .typeText(Selector('[class^="form-control ng-pristine ng-untouched ng-empty ng-"]'), 'password')
        .click(Selector('button').withText('Login'))
        .click(Selector('button').withText('Create Exercise'))
        .click(Selector('button').withText('description'))
        .typeText(Selector('.modal-body.ng-scope').find('.ng-pristine.ng-untouched.ng-valid.ng-empty'), 'testcafe')
        .click(Selector('a').withText('Save'))
        .click(Selector('#exercises_table').find('tbody').find('tr').find('td').find('div').find('a').find('img'))      
        .click(Selector('a').withText('Change'))
        .wait(5000)
});
```
I used **.setFilesToUpload** too but nothing changed:
( .........
        .click(Selector('#exercises_table').find('tbody').find('tr').find('td').find('div').find('a').find('img'))   
        **.setFilesToUpload('#hidden-file-upload-input', './Users/user/Downloads/Example.png')**
        .click(Selector('a').withText('Change'))
        .wait(5000)
)


### Steps to Reproduce:

Works to Record the Test, but fails when i run the Test.
 
### Your Environment details:
 
* testcafe studio version:                   0.3.0
* node.js version:                    8
* browser name and version:  Chrome
* platform and version:          Windows 7

**Comment by miherlosev** [comment]
@filiplucian

The [setFilesToUpload](https://devexpress.github.io/testcafe/documentation/test-api/actions/upload.html#populate-file-upload-input) function is designed to emulate two end-user actions: opening the "Choose File" window and selecting a file in that window.  This is the intended behavior that the browser's native popup is not invoked in this situation.

The fact that your test fails is likely connected to specifying a wrong selector for the [setFilesToUpload](https://devexpress.github.io/testcafe/documentation/test-api/actions/upload.html#populate-file-upload-input) action. I suggest that you check this and ensure that it points to an `<input type=file>` element.

**Comment by filiplucian** [comment]
Hello.

**Comment by miherlosev** [comment]
Selector should point to `<input type='file'>`.
However, I see that your selector points to a link with the 'Change' text content.
I cannot provide you with a strong selector, because your markup doesn't contain inputs with the 'file' type.
Your application is written with AngularJS, and inputs can be created dynamically during an application lifecycle.
So, it may be difficult to find target inputs.
Could you please provide a small example (or a public link to your application) so we can try to build a valid selector?

**Comment by AndreyBelym** [comment]
I close this issue due to long inactivity period. Feel free to reopen it if you can provide additional details.
