### ISSUE TITLE
typeText [as null] in IE 11 on Saucelabs

### ISSUE THREAD

**Issue by jwineman** [DevExpress/testcafe#3195]
In sauce labs I can watch the page load successfully, with the input visible.  This same code works fine if I run it in chrome on saucelabs or in chrome with the testcafe package.  It only fails in IE11 on saucelabs.

### What is your Test Scenario?
```
<main>
<input type="email" maxlength="255" placeholder="email" autocomplete="email" required="" name="login-email" id="instanceid-6" class="INPUT_nPFTaeLR" aria-labelledby="instanceid-6-label instanceid-6-error" aria-describedby="instanceid-6-description" value="">
</main>
```
```
const emailInput = await Selector('main').find('input[name=login-email]');
await t.typeText(emailInput, 'email@website.com');
```
 
### What is the Current behavior?
```
         at Login.typeText [as null]
      (/front-end/src/__e2e__/models/Login.js:31:20)
```
 
### What is the Expected behavior?
I would expect the text to be typed.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
* testcafe version:                   v0.23.2
* node.js version:                    v8.10.0
* command-line arguments:  `testcafe \"saucelabs:internet explorer@11.285:Windows 10\" test.js`
* browser name and version: IE 11
* platform and version:          Windows 10
* other:                                   testcafe-browser-provider-saucelabs @ 1.4.0

**Comment by jwineman** [comment]
Hi @hdorgeval,

Even adding `"` produces the same error.  `input[name=login-email]` is a valid CSS selector, evidenced by the fact that this code functions correctly in chrome on both saucelabs and in the testcafe npm package.

**Comment by jwineman** [comment]
Here is a video: 
https://assets.saucelabs.com/jobs/29e58a888499480ab124ed9491a2c0c0/video.mp4

**Comment by LavrovArtem** [comment]
@jwineman 
I've saved your html code in `index.html` file and ran the following test:
```js
import { Selector } from 'testcafe';

fixture`type text`
    .page`./index.html`;

test('type text', async t => {
    const emailInput = await Selector('main').find('input[name=login-email]');

    await t.typeText(emailInput, 'email@website.com');
});
```
In my desktop IE11, both variants work fine.
Into the `emailInput` variable saves the [DOM Node Snapshot](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/using-selectors.html#dom-node-snapshot) that contains all property values exposed by the selector in a single object if you using the `await` keyword. And when you pass the snapshot to the `typeText` function, everything works fine on my side. But we recommend you don't use the snapshot, just use the [Selectors](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/).

**Comment by LavrovArtem** [comment]
@jwineman 
I've saved your html code in the `index.html` file and ran the following test:
```js
import { Selector } from 'testcafe';

fixture`type text`
    .page`./index.html`;

test('type text', async t => {
    const emailInput = await Selector('main').find('input[name=login-email]');

    await t.typeText(emailInput, 'email@website.com');
});
```
On my desktop IE11, both variants(with and without the await keyword) work fine. But the await keyword is unnecessary, because the `Selector` and `find` functions are synchronous and they return [Selector](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/creating-selectors.html) immediately. Could you please try to reproduce the error on desktop IE11?

**Comment by jwineman** [comment]
Sorry it took me so long to reply, I needed to stand up an IE VM.  You're right, I get the same error on IE11/Windows 7.  

How do I debug further?  I don't know what to look at since these models execute fine in Chrome.

**Comment by miherlosev** [comment]
@jwineman 

As you can see in the report, TestCafe cannot capture a stack trace of the occurred error. 
Therefore, it's difficult to provide any future debug instructions.
The problem is likely related to your website and I need an example showing this issue to find its cause.
Feel free to reopen this issue if you can provide such an example.

**Comment by jwineman** [comment]
I would be willing to PR a fix for this if you could give me an overview of what needs to change.

**Comment by jwineman** [comment]
@miherlosev - Thanks for the update!  If anything changes and I can help let me know.  Thanks for all your work on this project.

**Comment by LavrovArtem** [comment]
@jwineman,
I've investigated your site and discovered that the `Syntax error` error occurs on your site without Testcafe. Your code contains the arrow functions that aren't supported by Internet Explorer. You can use the [--skip-js-errors](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors) flag to skip this error.

**Comment by jwineman** [comment]
@LavrovArtem - Thank you for taking the time to debug, sorry this wasn't a real issue.  I'll look into fixing the errors or adding the flag!
