### ISSUE TITLE
not able to print logger's response body during test cafe run 

### ISSUE THREAD

**Issue by shyedhu** [DevExpress/testcafe#3196]
I am not able to print the logger's response body during test cafe run , it says undefined in console log , however it works well on these data 
1) request body - works good( able to print it)

2) request header - works good 

3) response code - works good 

4) response body - not working ( not able to return in console log )

For example : - console.log('printing response body: '+logger.requests[0].response.body)

output is : undefined 

Does any one knows how to fix and what i need to requestHooks(logger);

**Comment by hdorgeval** [comment]
Hi @shyedhu, it seems to me that property availability in request/response objects depends on the setup of the option object of the [request logger](https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/logging-http-requests.html): if an option is set to false, I think it makes sense that the corresponding property is either null or undefined.

As explained in the documentation, the default option for the response body is false. 

Did you forgot to set the `logResponseBody` to true?

**Comment by shyedhu** [comment]
Thanks @hdorgeval for your quick response , Let me try to set the logResponseBody to true

**Comment by miherlosev** [comment]
Hi @shyedhu
@hdorgeval is right.
By default, [`RequestLogger`](https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/logging-http-requests.html#creating-a-logger) does not collect  headers and bodies for requests and responses.
You need to set the [`logResponseBody`](https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/logging-http-requests.html#creating-a-logger) option to the `true` value. After that, RequestLogger will collect a response body for specified requests.

See a small example:
```js
const logger = RequestLogger('https://example.com', { logResponseBody: true });
```

**Comment by shyedhu** [comment]
Thanks @miherlosev  , It woks good now . Thanks for your support !
