### ISSUE TITLE
Typing text into input[type=number] gives wrong result

### ISSUE THREAD

**Issue by lemnis** [DevExpress/testcafe#3197]
### What is your Test Scenario?
Trying to type a complicated (or invalid) value into a number field
 
### What is the Current behavior?
It only enters number values and commas

### What is the Expected behavior?
It should be allowed to enter any character, e.g. in the example it should result in `-.3e3`
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from 'testcafe'; // first import testcafe selectors
 
fixture `Getting Started`// declare the fixture
    .page `http://nativeformelements.com/`;  // specify the start page
 
 
//then create a test and place your code there
test('My first test', async t => {
    await t
        .typeText('input[type=number]', '-.3e3')
        .expect(Selector('input[type=number]').value).eql('-.3e3'); // Actual chrome: 33
});
```
</details>

<details>
<summary>Your complete test report:</summary>

```
 Running tests in:
 - Chrome 71.0.3578 / Mac OS X 10.13.6

 Getting Started
 ✖ My first test

   1) AssertionError: expected '.33' to deeply equal ''

      Browser: Chrome 71.0.3578 / Mac OS X 10.13.6

          6 |
          7 |//then create a test and place your code there
          8 |test('My first test', async t => {
          9 |    await t
         10 |        .typeText('input[type=number]', '-.3e3.')
       > 11 |        .expect(Selector('input[type=number]').value).eql(''); // Actual chrome: 33
         12 |});
         13 |

         at eql (/Users/lisa/dev/a21y/tests/testcafe/test.js:11:55)
         at test (/Users/lisa/dev/a21y/tests/testcafe/test.js:8:1)
         at markeredfn (/Users/lisa/dev/a21y/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at <anonymous> (/Users/lisa/dev/a21y/node_modules/testcafe/src/api/wrap-test-function.js:7:5)
         at fn (/Users/lisa/dev/a21y/node_modules/testcafe/src/test-run/index.js:239:19)
         at TestRun._executeTestFn
      (/Users/lisa/dev/a21y/node_modules/testcafe/src/test-run/index.js:235:38)
         at _executeTestFn (/Users/lisa/dev/a21y/node_modules/testcafe/src/test-run/index.js:284:24)



 1/1 failed (10s)
```
</details>

### Steps to Reproduce:

1. Go to my nativeformelements.com
3. Select the input with the type number
4. Type in -.3e3
 
### Your Environment details:
 
* testcafe version: 0.23.2                  
* node.js version: v10.11.0                    
* command-line arguments: testcafe chrome ./myfile.js
* browser name and version: Chrome 71
* platform and version:  MacOS 10.13.6

**Comment by miherlosev** [comment]
Hi @lemnis

Thank you for the detailed description. I've reproduced the problem.

**Comment by AlexKamaev** [comment]
I've researched the issue and found that Chrome behaves inconsistently if you type text from the keyboard and if you set a value via the `input.value=...` property. Though in Chrome you can type such symbols as '.', '-' or 'e', it does not allow you to programmatically set these symbols into the input value char by char. However, you can set the value to `-.3e3` at once. So, as a workaround, you can use the { paste: true } option of the `typeText` method.
Please refer to the following article to get more details: https://devexpress.github.io/testcafe/documentation/test-api/actions/action-options.html#typing-action-options
