### ISSUE TITLE
I have to use "--start-fullscreen"  and absolute chrome.exe path to run testcafe test on Chrome otherwise the browser will crash

### ISSUE THREAD

**Issue by BigYu** [DevExpress/testcafe#3198]
OS: Windows Server 2012 R2 Datacenter
Nodejs Version: v10.13.0

If I do "testcafe chrome xxx" the Chrome browsers will be opened with all tabs crashed. Even though those //extensions or //settings page are crashed.
![image](https://user-images.githubusercontent.com/5934735/49624541-c8c97e80-fa0c-11e8-872d-930aa983aeb1.png)
![image](https://user-images.githubusercontent.com/5934735/49624769-c6b3ef80-fa0d-11e8-80c8-bb1568d2a59a.png)

The only way I can make it work is to use absolute path to the chrome.exe with --start-fullscreen arument:
testcafe \"path:`C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe` --start-fullscreen\"  Spec/index.js

All the below will crash:
testcafe 'chrome --start-fullscreen'  Spec/index.js
testcafe chrome Spec/index.js
testcafe chrome:headless Spec/index.js
testcafe 'chrome:headless --start-fullscreen' Spec/index.js

**Comment by miherlosev** [comment]
Hi @BigYu
We've already encountered similar behavior. In this case, you need to specify the [`--no-sandbox`](https://peter.sh/experiments/chromium-command-line-switches/#no-sandbox) flag for the Google Chrome browser.
Take a look at this example:
```js
testcafe 'chrome --start-fullscreen --no-sandbox' Spec/index.js
```

**Comment by BigYu** [comment]
Hi @miherlosev  Thanks for your reply but unfortunately it does not work for me.

I'm not going to reopen this issue because it happens even I use some other automation test software like puppeteer, and still crashes with Chromium. I updated my Chrome to the latest version which is Version 71.0.3578.98 (Official Build) (64-bit) and the issue is still there.
Testcafe works for FF and IE on my machine. It is so weired and mysterious. I will seek for help on Chrome forum.
