### ISSUE TITLE
Chrome 71 support on MaxOS

### ISSUE THREAD

**Issue by ion-willo** [DevExpress/testcafe#3199]
Just started looking at TestCafe and immediately ran in to an issue:
```
 1) Error on page "https://www.iol.co.za/":

      invalid version specified:
          No stack trace available

      Browser: Chrome 71.0.3578 / Mac OS X 10.14.1
```
Am I missing something in my setup? Any pointers to get this going would be much appreciated.

**Comment by dimkinv** [comment]
Having the same issue, any update on that?

**Comment by LavrovArtem** [comment]
@ion-willo

![image](https://user-images.githubusercontent.com/5373460/49717578-a16eed80-fc68-11e8-87bf-16ffb1f0ccd6.png)
I've checked your website and found that this error occurs without our testing tools involved. You can check this out in the browser console. I recommend that you fix this error on your website. Alternatively, you can use the [--skip-js-error](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors) flag when running TestCafe to ignore such errors.
