### ISSUE TITLE
intermittent bug when running test

### ISSUE THREAD

**Issue by zoejobson** [DevExpress/testcafe#3200]
### Are you requesting a feature or reporting a bug?
Bug

### What is the Current behavior?
this only happens occasionally, the error log looks like this, the timestamps are from jenkins

14:38:27 
14:38:27    1) TypeError: Cannot read property '0' of null
14:38:27 
14:38:27       Browser: HeadlessChrome 70.0.3538 / Linux 0.0.0
14:38:27       Screenshot:
14:38:27 
14:38:27    /home/ec2-user/workspaces/2018-12-07T14_28_21.347Z/results/2018-12-07_14-28-37/test-1/HeadlessChrome_70.0.3538_Linux_0.0.0/errors/1.png
14:38:27 
14:38:27          266 |        this._handlePlainObject(val);
14:38:27          267 |};
14:38:27          268 |
14:38:27          269 |DecodingTransformer.prototype.transform = function () {
14:38:27          270 |    this.visitedRefs[0] = true;
14:38:27        > 271 |    this._handleValue(this.references[0], this.references,
14:38:27       0);
14:38:27          272 |
14:38:27          273 |    return this.references[0];
14:38:27          274 |};
14:38:27          275 |
14:38:27          276 |
14:38:27 
14:38:27    [Source: info, Timestamp: 2018-12-07T14:35:05.337Z]
14:38:27       at DecodingTransformer.transform
14:38:27 
14:38:27    (/home/ec2-user/workspaces/2018-12-07T14_28_21.347Z/node_modules/replicator/index.js:271:38)
14:38:27          at module.exports.Replicator.decode
14:38:27 
14:38:27    (/home/ec2-user/workspaces/2018-12-07T14_28_21.347Z/node_modules/replicator/index.js:559:24)
14:38:27          at SelectorBuilder.decode
14:38:27 
14:38:27    (/home/ec2-user/workspaces/2018-12-07T14_28_21.347Z/node_modules/testcafe/src/client-functions/client-function-builder.js:142:32)
14:38:27          at SelectorBuilder._processResult
14:38:27 
14:38:27    (/home/ec2-user/workspaces/2018-12-07T14_28_21.347Z/node_modules/testcafe/src/client-functions/selectors/selector-builder.js:188:32)
14:38:27          at _processResult
14:38:27 
14:38:27    (/home/ec2-user/workspaces/2018-12-07T14_28_21.347Z/node_modules/testcafe/src/client-functions/client-function-builder.js:137:25)
14:38:27          at $$testcafe_test_run$$HpM0inZ9j$$
14:38:27 
14:38:27    (/home/ec2-user/workspaces/2018-12-07T14_28_21.347Z/node_modules/testcafe/src/api/test-run-tracker.js:76:16)
14:38:27          at $$testcafe_test_run$$HpM0inZ9j$$
14:38:27       (/home/ec2-user/workspaces/2018-12-07T14_28_21.347Z/node_modules/testcafe/src/api/test-run-tracker.js:76:16)
14:38:27 
14:38:27 
14:38:27    2) - Error in test.after hook -
14:38:27       TypeError: Cannot read property '0' of null
14:38:27 
14:38:27       Browser: HeadlessChrome 70.0.3538 / Linux 0.0.0
14:38:27       Screenshot:
14:38:27 
14:38:27    /home/ec2-user/workspaces/2018-12-07T14_28_21.347Z/results/2018-12-07_14-28-37/test-1/HeadlessChrome_70.0.3538_Linux_0.0.0/errors/2.png
14:38:27 
14:38:27          266 |        this._handlePlainObject(val);
14:38:27          267 |};
14:38:27          268 |
14:38:27          269 |DecodingTransformer.prototype.transform = function () {
14:38:27          270 |    this.visitedRefs[0] = true;
14:38:27        > 271 |    this._handleValue(this.references[0], this.references,
14:38:27       0);
14:38:27          272 |
14:38:27          273 |    return this.references[0];
14:38:27          274 |};
14:38:27          275 |
14:38:27          276 |
14:38:27 
14:38:27          at DecodingTransformer.transform
14:38:27 
14:38:27    (/home/ec2-user/workspaces/2018-12-07T14_28_21.347Z/node_modules/replicator/index.js:271:38)
14:38:27          at module.exports.Replicator.decode
14:38:27 
14:38:27    (/home/ec2-user/workspaces/2018-12-07T14_28_21.347Z/node_modules/replicator/index.js:559:24)
14:38:27          at SelectorBuilder.decode
14:38:27 
14:38:27    (/home/ec2-user/workspaces/2018-12-07T14_28_21.347Z/node_modules/testcafe/src/client-functions/client-function-builder.js:142:32)
14:38:27          at SelectorBuilder._processResult
14:38:27 
14:38:27    (/home/ec2-user/workspaces/2018-12-07T14_28_21.347Z/node_modules/testcafe/src/client-functions/selectors/selector-builder.js:188:32)
14:38:27          at _processResult
14:38:27 
14:38:27    (/home/ec2-user/workspaces/2018-12-07T14_28_21.347Z/node_modules/testcafe/src/client-functions/client-function-builder.js:137:25)
14:38:27          at $$testcafe_test_run$$HpM0inZ9j$$
14:38:27 
14:38:27    (/home/ec2-user/workspaces/2018-12-07T14_28_21.347Z/node_modules/testcafe/src/api/test-run-tracker.js:76:16)
14:38:27          at $$testcafe_test_run$$HpM0inZ9j$$
14:38:27       (/home/ec2-user/workspaces/2018-12-07T14_28_21.347Z/node_modules/testcafe/src/api/test-run-tracker.js:76:16)
14:38:27 

### What is the Expected behavior?
the test to continue or to produce a real error.

### How would you reproduce the current behavior (if this is a bug)?
I have not yet been able to reproduce, it happens sporadically, I would appreciate a clue as to how to pin it down

#### Provide the test code and the tested page URL (if applicable)
not possible our website is not publically accessible, and the test code is complex.

### Your Environment details:
 
* testcafe version:                   <0.23.0>
* node.js version:                    <6.0.0>
* command-line arguments:  node_modules/.bin/testcafe --screenshots-on-fails --screenshots /home/ec2-user/workspaces/2018-12-07T14_28_21.347Z/results --reporter list,xunit:/home/ec2-user/workspaces/2018-12-07T14_28_21.347Z/results/results.xml --selector-timeout 60000 --assertion-timeout 60000 --page-load-timeout 300000 chrome:headless smoke-tests/**/*.js
* browser name and version: <see above>
* platform and version:          <linux>

**Comment by miherlosev** [comment]
Hi @zoejobson
Judging by the stack trace you provided, I think that this issue occurred in the [replicator](https://www.npmjs.com/package/replicator) module. Without an example, I cannot determine exactly what module (`testcafe` or `replicator`) causes the problem. Feel free to reopen this issue if you can provide us with an example showing the problem in action.

**Comment by GertB1** [comment]
Hi

Not sure if it could help but this is the error that I get running the testcafe test


   266 |        this._handlePlainObject(val);
   267 |};
   268 |
   269 |DecodingTransformer.prototype.transform = function () {
   270 |    this.visitedRefs[0] = true;
 > 271 |    this._handleValue(this.references[0], this.references, 0);
   272 |
   273 |    return this.references[0];
   274 |};
   275 |
   276 |

   at DecodingTransformer.transform (C:\Work\BeKoSt\e2e\testcafe-e2e\node_modules\replicator\index.js:271:38)
   at module.exports.Replicator.decode (C:\Work\BeKoSt\e2e\testcafe-e2e\node_modules\replicator\index.js:559:24)
   at SelectorBuilder.decode (C:\Work\BeKoSt\e2e\testcafe-e2e\node_modules\testcafe\src\client-functions\client-function-builder.js:142:32)
   at SelectorBuilder._processResult (C:\Work\BeKoSt\e2e\testcafe-e2e\node_modules\testcafe\src\client-functions\selectors\selector-builder.js:188:32)
   at _processResult (C:\Work\BeKoSt\e2e\testcafe-e2e\node_modules\testcafe\src\client-functions\client-function-builder.js:137:25)
   at $$testcafe_test_run$$hXJq0nl1P$$ (C:\Work\BeKoSt\e2e\testcafe-e2e\node_modules\testcafe\src\api\test-run-tracker.js:76:16)
   at $$testcafe_test_run$$hXJq0nl1P$$ (C:\Work\BeKoSt\e2e\testcafe-e2e\node_modules\testcafe\src\api\test-run-tracker.js:76:16)

**Comment by GertB1** [comment]
Hi @zoejobson

I upgraded to 1.0.0-alpha.1 of testcafe and the error went away. 

Hope it helps
