### ISSUE TITLE
Add ability to specify a folder as a second parameter of the 'setFilesToUpload' action

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#3206]
https://devexpress.github.io/testcafe/documentation/test-api/actions/upload.html#populate-file-upload-input

https://stackoverflow.com/questions/53667429/is-there-any-way-to-upload-folders-using-testcafe

**Comment by Farfurix** [comment]
One more request: https://stackoverflow.com/questions/63044557/setfilestoupload-appear-to-not-be-working-when-we-need-to-upload-a-directory/63070682#63070682

**Comment by ngrossi** [comment]
Thanks Team!

**Comment by aleks-pro** [comment]
One more request: https://supportcenter.devexpress.com/internal/ticket/details/T1017799

**Comment by miherlosev** [comment]
We decided to not implement this feature because there is not much interest in this in the community. However, if this feature is important for you, you can create a PR yourself.
