### ISSUE TITLE
 typeText not working with textarea in Edge 17

### ISSUE THREAD

**Issue by Luciefer66** [DevExpress/testcafe#3207]
Are you requesting a feature or reporting a bug?
A bug.

What is the current behavior?
typeText doesn't input values into textarea fields in Edge 17.17134 / Windows 10.0.17134
Works fine in Chrome.

What is the expected behavior?
It should work

How would you reproduce the current behavior (if this is a bug)?
Create a page with an textarea:
<textarea data-v-8ae60cb4="" data-v-d1fd5838="" id="mTextfield-8cad2597-6273-4e92-87bf-1beea2e7d150" rows="1" class="m-textfield__input" style="height: 20px;"></textarea>
Try fill it in using typeText:
export const module = Selector('span').withText("Edge Module Testcafe");
const titreInput = Selector('textarea').withAttribute('class','m-textfield__input', { visibilityCheck: true });
await t.typeText(titreInput, nomModule);  
Specify your
operating system: Edge 17.17134.0 / Windows 10.0.17134
testcafe version: 0.23.2

**Comment by miherlosev** [comment]
Hi @Luciefer66
I've tried to run a simple test with the `typeText` action and it all works fine (see [my test video](https://monosnap.com/file/pz2VOL4RhLZne5W0t2zCcPor4m1wQz)).
It looks like you have a special case in which the `typeText` action works wrong.
Could you please provide a simple example to reproduce the problem?

**Comment by Luciefer66** [comment]
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/45772903/49893822-58f73180-fe1a-11e8-903c-f3f0b4a55821.png">
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/45772903/49893894-8c39c080-fe1a-11e8-9322-83a931c8cfea.png">

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/45772903/49893865-7c21e100-fe1a-11e8-8d45-c995562654d0.png">

**Comment by miherlosev** [comment]
If I run your example on my computer, I get the following report:

![image](https://user-images.githubusercontent.com/4133518/49945318-ab5d4e80-fefd-11e8-95b3-f00af4a8b386.png)

It means that I need all dependent files to reproduce the problem.
If you test an internal application, I would need a simple copy of your application.
It's easy to organize this example as a repository on GitHub.
Feel free to reopen this issue if you are able to provide us with such a sample.
