### ISSUE TITLE
Error: Can not get list of processes

### ISSUE THREAD

**Issue by sorin-davidoi** [DevExpress/testcafe#3210]
### What is your Test Scenario?

Application running on `localhost` inside Docker.
 
### What is the Current behavior?

The `testcafe` process terminates with non-zero exit code. Can't be reproduced all the time. Noticed when runing just one test and when running 30 tests.

```
{number} passed ({elapsed_time})
Error: Can not get list of processes
    at getProcessOutputUnix ({redacted}/node_modules/testcafe/lib/utils/process.js:149:19)
    at {redacted}/node_modules/testcafe/lib/utils/process.js:12:30
    at Generator.next (<anonymous>)
    at step ({redacted}/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at {redacted}/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F ({redacted}/node_modules/core-js/library/modules/_export.js:36:28)
    at {redacted}/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at findProcessUnix ({redacted}/node_modules/testcafe/lib/utils/process.js:18:21)
at {redacted}/node_modules/testcafe/lib/utils/process.js:104:92
```
 
### What is the Expected behavior?

TestCafe terminates with exit code 0 if all the tests pass.

### Your Environment details:
 
* testcafe version:                   `0.23.3-alpha.2`
* node.js version:                    `v8.14.0`
* command-line arguments:  `--hostname localhost --ports 3001,3002 --concurrency 1 --assertion-timeout 30000 --selector-timeout 30000 --quarantine-mode firefox:headless tests`
* browser name and version:  Firefox 63
* platform and version:           Docker base image: `node:8-slim`
* other:                                    Noticed non-zero exit codes when running `v0.23.2`, but with no error message. I've debugged the issue a bit and noticed that [`error` is emitted](https://github.com/DevExpress/testcafe/blob/master/src/utils/process.js#L37) but `stderr` and `stdout` are empty.

**Comment by miherlosev** [comment]
https://github.com/DevExpress/testcafe/issues/3210

Hi @sorin-davidoi 

The docker image (`node:8-slim`) you are using doesn't contain the `ps` utility.
This is why, the `getProcessOutputUnix` function will fail (see the problematic code line -https://github.com/DevExpress/testcafe/blob/41525a9dcb1ddda7582119c2179aa84d02b51897/src/utils/process.js#L17).

To fix the error, you need to install it by running this command: `apt-get install procps`.

**Comment by sorin-davidoi** [comment]
Thanks, that solved the issue! It is strange however that it only failed _sometimes_. Perhaps the introduction of new system-level dependencies should come with a major version bump?
