### ISSUE TITLE
Blocking browser for long against localhost with version v0.23.3-alpha.2

### ISSUE THREAD

**Issue by rpolishetti** [DevExpress/testcafe#3211]
### What is your Test Scenario?
Simulating click on a button on DOM
 
### What is the Current behavior?
 We see waiting / processing for long, after that testcafe reloads the page again we see tests start. This is happening only in chrome ( v71.0.3578.80 ). Works fine and fast in firefox.
 
### What is the Expected behavior?
should continue to next assertion.
 
### What is your web application and your TestCafe test code?
Sample code 

  await this.t
      .click(this.qtyIncrementBtn);

  this.selectedQty = await this.qtyValueEl.innerText;

Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by miherlosev** [comment]
Hi @rpolishetti

The behavior you described looks like a bug. However, I cannot find the cause of the problem without a small example. Also, specify the TestCafe version you are using.
So, could you please run your tests with the latest TestCafe version (`testcafe@0.23.3-alpha.2`)?
If the problem persists, provide us with a small example in which we can reproduce this issue.
