### ISSUE TITLE
Add a possibility to handle the 'Know your location' dialog in tests

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#3224]
![image](https://user-images.githubusercontent.com/4133518/49939430-e5265900-feed-11e8-881b-6894ee06e3b4.png)

**Comment by miherlosev** [comment]
https://github.com/DevExpress/testcafe/issues/1991

**Comment by kmistry27** [comment]
I am having this issue at the moment.

The `  .setNativeDialogHandler(() => null)` syntax provided here: https://devexpress.github.io/testcafe/documentation/reference/test-api/testcontroller/setnativedialoghandler.html, does not dismiss this "know your location" alert.

Could this re-opened?

**Comment by AndreyBelym** [comment]
Thank you for your feedback. We'll keep this issue open. This functionality does not come out-of-the-box with TestCafe in a more convenient way, but you can use several existing APIs to solve this task. Have a look at this example: [https://github.com/DevExpress/testcafe-examples/tree/master/examples/mock-geolocation-api](https://github.com/DevExpress/testcafe-examples/tree/master/examples/mock-geolocation-api)

**Comment by kmistry27** [comment]
> Thank you for your feedback. We'll keep this issue open. This functionality does not come out-of-the-box with TestCafe in a more convenient way, but you can use several existing APIs to solve this task. Have a look at this example: https://github.com/DevExpress/testcafe-examples/tree/master/examples/mock-geolocation-api

Thanks for the swift response @AndreyBelym -- a colleague pointed me in that direction which does do the trick. Many thanks.
