### ISSUE TITLE
ClientFunction cannot implicitly resolve the test run 

### ISSUE THREAD

**Issue by chrisshiplet** [DevExpress/testcafe#3225]
### What is your Test Scenario?
I'm attempting to use the `testcafe-react-selectors` plugin to test my React app with the TestCafe docker container.

Seems similar to #3186 and DevExpress/testcafe-react-selectors#109 but I'm using the alpha channel with the code from #3186 merged and not seeing any improvement. Looks like that change may have only helped on Windows systems.
 
### What is the Current behavior?
I get `ClientFunction cannot implicitly resolve the test run in context of which it should be executed` every time `await waitForReact()` is called
 
### What is the Expected behavior?
The tests should run
 
### What is your web application and your TestCafe test code?
 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

```js
 import { waitForReact, ReactSelector } from 'testcafe-react-selectors';

fixture`Reproduce error`.page(`https://reactjs.org/`).beforeEach(async () => {
  await waitForReact();
});

test('Test that does nothing', async t => {
  // noop
});
```
</details>

<details>
<summary>Your complete test report:</summary>

```
 Running tests in:
 - HeadlessChrome 68.0.3440 / Linux 0.0.0

 Reproduce error
 ✖ Test that does nothing

   1) - Error in fixture.beforeEach hook -
      Error: Cannot prepare tests due to an error.

      ClientFunction cannot implicitly resolve the test run in context of which it should be executed. If you
      need to call ClientFunction from the Node.js API callback, pass the test controller manually via
      ClientFunction's `.with({ boundTestRun: t })` method first. Note that you cannot execute ClientFunction
      outside the test code.

      Browser: HeadlessChrome 68.0.3440 / Linux 0.0.0

         1327 |                stopChecking = true;
         1328 |
         1329 |                reject('waitForReact: The waiting timeout is exceeded');
         1330 |            }, checkTimeout);
         1331 |        });
       > 1332 |    }, { dependencies: { checkTimeout } })();
         1333 |};

         at waitForReact (/tests/node_modules/testcafe-react-selectors/lib/index.js:1332:43)
         at <anonymous> (/tests/fixtures/basic.js:5:50)
         at markeredfn (/usr/lib/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at <anonymous> (/usr/lib/node_modules/testcafe/src/api/wrap-test-function.js:7:5)
         at fn (/usr/lib/node_modules/testcafe/src/test-run/index.js:239:19)
         at TestRun._executeTestFn (/usr/lib/node_modules/testcafe/src/test-run/index.js:235:38)
         at _executeTestFn (/usr/lib/node_modules/testcafe/src/test-run/index.js:259:31)
         at TestRun._runBeforeHook (/usr/lib/node_modules/testcafe/src/test-run/index.js:254:29)
         at _runBeforeHook (/usr/lib/node_modules/testcafe/src/test-run/index.js:283:24)
         at TestRun.start (/usr/lib/node_modules/testcafe/src/test-run/index.js:274:20)



 1/1 failed (2s)
```
</details>

<details>
<summary>Screenshots:</summary>

![screen shot 2018-12-13 at 10 32 20 am](https://user-images.githubusercontent.com/933501/49956431-636d0600-fec2-11e8-8fd8-5ad6d26069e8.png)

This is the folder structure of the volume that I'm mapping into the container. `package.json` contains the following dependencies:

```
"dependencies": {
    "testcafe": "^0.23.2",
    "testcafe-react-selectors": "^3.0.2"
  },
```
</details>

### Steps to Reproduce:

1. Create a folder as above with tests and `testcafe-react-selectors` in a `package.json`
3. Run the docker container: `docker run -v $(pwd)/testcafe:/tests -it testcafe/testcafe:alpha 'chromium:headless --no-sandbox' '/tests/fixtures/**/*.js'`
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   `0.23.3-alpha.4` (from `docker run --entrypoint "testcafe" -it testcafe/testcafe:alpha -v`)
* node.js version:                    `v10.14.1`
* command-line arguments:  `'chromium:headless --no-sandbox' '/tests/fixtures/**/*.js'`
* browser name and version: `HeadlessChrome 68.0.3440`
* platform and version:          Docker version 18.09.0

**Comment by AlexKamaev** [comment]
I can reproduce the issue only if I have both the `testcafe` and `testcafe-react-selectors` modules in the package.json file. In this case, there is a conflict between the local testcafe version and the global testcafe version which is already installed in the docker image.
To overcome this issue, I recommend deleting both modules from `package.json`, create your own docker image based on the testcafe image and install the `testcafe-react-selectors` module globally in your image. Please refer to the following issue to get the details https://github.com/DevExpress/testcafe-react-selectors/issues/28#issuecomment-392251312
 
I think your `dockerfile` could be something like the following:
```
FROM testcafe/testcafe:alpha
USER root
ENV NODE_PATH=/usr/lib/node_modules/
RUN npm install -g testcafe-react-selectors
```
 
Please feel free to contact us if you need further assistance.

**Comment by chrisshiplet** [comment]
Sorry for the late reply! Just got back from vacation. Your suggest works just fine - but not with the `alpha` tag, only `latest`. `alpha` causes an unhandled rejection when running 
```
const loginLink = ReactSelector('TopNav Link').withProps({ to: '/sign-in' });
await t.click(loginLink);
```

Anyway, I think `latest` will work fine for me for now. Thank you for the help!

**Comment by Pr60** [comment]
@AlexKamaev - I'm facing the same issue. I have the same Dockerfile as you mentioned. Is there any workaround? Here is a link to my issue [https://stackoverflow.com/questions/58716989/testcafe-docker-getting-error-because-of-reactselector](url)

**Comment by aleks-pro** [comment]
Hello @Pr60 ,

Thank you for your inquiry. This issue looks like a question. We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)). So let's continue the discussion regarding this issue in the StackOverflow thread you've created.
