### ISSUE TITLE
Session storage doesn't save values after navigation when a role is used

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#3232]
### What is your Test Scenario?
Retrieve a value from the session storage after a page navigation when using a role.
 
### What is the Current behavior?
The session storage is empty after a page navigation when a role is used.
 
### What is the Expected behavior?
The session storage contains previously stored values after a page navigation when a role is used.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):
http://devexpress.github.io/testcafe/example/

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
import Page from './page-model';

import { Role } from 'testcafe';

// Page model
const page = new Page();

const role = new Role('http://devexpress.github.io/testcafe/example/', () => {});

fixture `A set of examples that illustrate how to use TestCafe API`
    .page `https://devexpress.github.io/testcafe/example/`
    .beforeEach(t => t.useRole(role));

// Tests
test('Handle native confirmation dialog', async t => {
    await t
        .setNativeDialogHandler(() => true)
        .click(page.populateButton);

    const dialogHistory = await t.getNativeDialogHistory();

    await t.expect(dialogHistory[0].text).eql('Reset information before proceeding?');

    await t
        .click(page.submitButton)
        .expect(page.results.innerText).contains('Peter Parker');
}); 
```
</details>

### Steps to Reproduce:
Run the test
 
### Your Environment details:
 
* testcafe version:                   0.23.3-alpha.4
* node.js version:                    any
* command-line arguments:  N/A
* browser name and version: Chrome 71
* platform and version:          Windows 10

**Comment by morganedmonds** [comment]
I maintain a fairly large Testcafe suite on my current project, and we depend heavily on role-switching. I've been struggling with what appears to be this issue since 0.23.2 was released. We're going to pin 0.23.1 in our project for now. Definitely looking forward to the fix, thank you for your work on it!

**Comment by AndreyBelym** [comment]
Hi @morganedmonds, this issue can be reproduced in `0.23.1` as well. Could you please create a new issue and provide the information that I can use to reproduce the problem: an example project, your test files, the page URL or source code?

You could also try `testcafe@0.23.3` we've fixed a lot of problem in this version.

**Comment by morganedmonds** [comment]
Hi @AndreyBelym, yes we figured that out. I was able to work around the issue by clicking on a link to the URL rather than navigating to it directly. I'm afraid I don't have time to put together a sample project in the next couple of weeks with the holidays, and I can't share our app code.  Thank you for following up!

**Comment by AndreyBelym** [comment]
After examing the problem, I consider this issue as a duplicate of issue #2195. A Role should reload the test page, but it doesn't happen in some situations. The workaround is to manually reload the page after using a Role, e.g.:
```js
const reloadPage = ClientFunction(() => location.reload());

await t.useRole(role);

await reloadPage();
```
