### ISSUE TITLE
Entering debug mode after test instead of pausing during test on --debug-on-fail

### ISSUE THREAD

**Issue by timnederhoff** [DevExpress/testcafe#3237]
### What is the Test Scenario?
When developing tests, I want a test to pause in debug mode when it fails when --debug-on-fail option is enabled, without TestCafe running the `fixture.afterEach()` or `test.after()` hooks.

### What is the Current behavior?
The test finishes completely, including finishing `fixture.afterEach()`/`test.after()`, then enters debug mode.
 
### What is the Expected behavior?
The test holds on the point where an error occurs (e.g. a failed `t.expect()`), and enters debug mode without running the `fixture.afterEach()`/`test.after()` first.
 
### Environment details:
 
* testcafe version:                   0.23.1
* node.js version:                    10.14.2
* command-line arguments:    `testcafe --debug-on-fail e2e/myTest.ts
* browser name and version:  Chrome 71
* platform and version:            Linux Ubuntu 18.04.1

**Comment by rob4629** [comment]
Any updates on this?

**Comment by miherlosev** [comment]
Hi @rob4629 
 
At present, we have no news related to this enhancement. 
If that functionality is crucial for you, you can try to implement it yourself. We can help with that.

**Comment by AlexKamaev** [comment]
In order to keep our backlog clean, we decided to close the issue. If anybody is ready to create a PR, we'll check it.
