### ISSUE TITLE
adding request hook causes test to fail

### ISSUE THREAD

**Issue by JohnHartman939** [DevExpress/testcafe#3238]
### What is your Test Scenario?
I am having a hard time getting request hooks to work properly, I think I am having an SSL issue but I also have noticed that with a request hook an object identified with a URL is not able to be found. Without the request hook the object is found no problem.

The test just checks for object visibility
 
### What is the Current behavior?
with the request hook the object cannot be found

 
### What is the Expected behavior?
with the request hook the object should be found

 
### What is your web application and your TestCafe test code?

 

I have an object with this for the html
without hook
`<img src-hammerhead-stored-value="http://localhost:8080/images/tenant/toonix-main.svg" src="http://localhost:1337/8IoxkDtcH/http://localhost:8080/images/tenant/toonix-main.svg" data-hammerhead-hovered="">`

with hook
`<img src-hammerhead-stored-value="/images/tenant/toonix-main.svg" src="http://localhost:1337/wju_iiAQH/http://localhost:8080/images/tenant/toonix-main.svg" data-hammerhead-hovered="">`

I am using this selector
   `javascript toonixLogo = Selector(
        "img[src='http://localhost:8080/images/tenant/toonix-main.svg']"
    );`

this is my custom request hook
`import { RequestHook } from 'testcafe'
export default class AdultHomeScreenHook extends RequestHook{
    constructor(requestFilter:any, responceOptions:any){
        super(requestFilter,responceOptions)
    }
    onRequest (event:any) {
        console.log('========================')
        console.log('Request Body')
        let buf = event._requestContext.reqBody as Buffer
        console.log(buf.toLocaleString())
    }
onResponse (event:any) {
        console.log('========================')
        let buf = event.body as Buffer
        console.log(event)
    }
}`

and this is the fixture it is being attached to
``fixture.only`Adult Home Screen Tests`.page`http://localhost:8080`.requestHooks(adultHomeHook);``

if I run the test with the request hook the test I am running fails, if I comment out the request hook part of this the test will pass
 
* testcafe version:   0.23.2                
* node.js version:    9.11.1                
* command-line arguments:  
* browser name and version: latest Chrome 
* platform and version:   macOS 10.14       
* other:   I am using the programming interface to spin up the webserver locally

**Comment by JohnHartman939** [comment]
just to clarify I mentioned that I thought I might be having an ssl issue, This is not the case. I was thinking I had an ssl issue because the response I was getting returned unreadable chars, turns out the response body was gzipped after unzipping the response body and running toString on the unzipped Buffer object I was able to see the text. 

That said this issue is still occurring

**Comment by VasilyStrelyaev** [comment]
I tried to reproduce the described behavior on several websites, but my attempts were unsuccessful.

The `src-hammerhead-stored-value` attribute did not change regardless of the hook. The `img[src=...]` selector also did not fail because it takes into account `src-hammerhead-stored-value` rather than `src`.

Could you please provide a webpage where I could reproduce the behavior you encountered?
