### ISSUE TITLE
Shift Click does not highlight text

### ISSUE THREAD

**Issue by nickroth** [DevExpress/testcafe#3239]
### What is your Test Scenario?
Using Shift+Click to highlight text. For example, click one element then shift+click another to highlight all the text in between the two locations.

I need to update my application to prevent text highlight with Shift+Click. The exact use case is the user will select an element then Shift+Click to select all elements in between (like selecting many items in a list). But, in manual testing, the Shift+Click causes text on the page to highlight. This is highlight undesired.

I'd like to automate the test case but since no highlight happens when using TestCafe before I've changed my application, I can't use TestCafe to help verify my changes worked as expected.
 
### What is the Current behavior?
Text does not get highlighted with Click then Shift+Click.
 
### What is the Expected behavior?
Text should be highlighted.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```typescript
import {
    ClientFunction,
} from "testcafe";

fixture("TestCafe test page");

test("Shift click to highlight text", async (t) => {

    const selectionRangeCount = ClientFunction(() => document.getSelection().rangeCount);

    await t.navigateTo("https://devexpress.github.io/testcafe/example/")
        .click("#main-form > div > header > h1")
        .click("#main-form > div > header > p", {
            modifiers: {
                shift: true,
            },
        })
        .expect(selectionRangeCount()).gt(0, "Something was selected.");
});
 
```
</details>

<details>
<summary>Your complete test report:</summary>

```
testcafe -S -s "screenshots -e chrome ShiftClickToHighlight.ts

 Running tests in:
 - Chrome 71.0.3578 / Windows 10.0.0

 TestCafe test page
 × Shift click to highlight text (screenshots: .\screenshots\2018-12-18_13-05-51\test-1\Chrome_71.0.3578_Windows_10.0.0\errors\1.png)

   1) AssertionError: Something was selected.: expected 0 to be above 0

      Browser: Chrome 71.0.3578 / Windows 10.0.0
      Screenshot: .\screenshots\2018-12-18_13-05-51\test-1\Chrome_71.0.3578_Windows_10.0.0\errors\1.png

         13 |        .click("#main-form > div > header > p", {
         14 |            modifiers: {
         15 |                shift: true,
         16 |            },
         17 |        })
       > 18 |        .expect(selectionRangeCount()).gt(0, "Something was selected.");
         19 |});
         20 |
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

Run the sample test code. No text is highlighted in the browser. However if I perform the same steps manually, the browser will highlight text.
 
### Your Environment details:
 
* testcafe version:                   0.23.2
* node.js version:                    v10.7.0
* command-line arguments:  
* browser name and version: Chrome 71.0.3578.98, no others tried
* platform and version:          Windows 10

**Comment by VasilyStrelyaev** [comment]
Technically, there are user actions processed by webpages and actions that use integrated browser features. For instance, when you press Ctrl+A to select text, this action is processed by a webpage. When you double-click a word, it is selected by the browser.

TestCafe can only emulate actions processed by webpages. This limitation is imposed by TestCafe specifics and cannot be overcome. The action you are asking about is processed by the browser and thus cannot be emulated by TestCafe.
