### ISSUE TITLE
TestCafe fails to show custom push notification bar

### ISSUE THREAD

**Issue by sijosyn** [DevExpress/testcafe#3242]
### What is your Test Scenario?

Download the provided test repo and execute the notification test
 
### What is the Current behavior?

TestCafe fails to render/show custom (blue) push notification bar. (see attached screenshot).
**Note:** If you see a red or grey alert bar on the page, please dismiss it first and reload the page to see the blue push notification bar. 
 
### What is the Expected behavior?

TestCafe should show the custom (blue) push notification bar.
 
### What is your web application and your TestCafe test code?

 
Download this repo - https://github.com/sijosyn/testcafe-syntests and run the notification test from test suite.

Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 testcafe chrome desktop/notification.js -e

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

**Expected:**

<img width="1436" alt="expected" src="https://user-images.githubusercontent.com/29459281/50235001-ec81b280-0384-11e9-9754-8ab1373b591d.png">

-----
**Bug:**
<img width="1196" alt="screen shot 2018-12-19 at 11 27 53 am" src="https://user-images.githubusercontent.com/29459281/50235027-fc999200-0384-11e9-8abb-a5ab432754b1.png">

</details>

### Steps to Reproduce:

Run the notification test from the provided test suite.
 
### Your Environment details:
 
* testcafe version:                    0.23.3
* node.js version:                     v8.11.1
* command-line arguments:   testcafe chrome desktop/notification.js -e
* browser name and version:  Chrome 71
* platform and version:           macOS 10.13
* other:                                    Notification bar is Chrome only feature.

**Comment by VasilyStrelyaev** [comment]
We tried to open this webpage in a regular way in Chrome and discovered that this notification bar appears only when the HTTPS connection is used.

TestCafe connects to websites over HTTP by default. However, you can configure it to use HTTPS.

See the [Connect to TestCafe Server over HTTPS](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/connect-to-the-testcafe-server-over-https.html) topic to learn how to do this.
