### ISSUE TITLE
Have a multiple stacktrace reporter for fast analysis when a test fails

### ISSUE THREAD

**Issue by hdorgeval** [DevExpress/testcafe#3245]
### The problem
Very often a test code executes code from imported files or modules, which in turn may also import other files and modules.
When code fails in one of the 'leaf', the `spec` reporter will report the source code around the failed line and also reports the stack-trace for each files within the call stack like in the following example:

```text
1) The specified selector does not match any element in the DOM tree.

   Browser: Firefox 59.0.0 / Mac OS X 10.12.0

      16 |  await t
      17 |    .setTestSpeed(config.testcafe.testSpeed)
   --------------------------------------------
    → 18 |    .hover(selector.userNameInputBox)
   --------------------------------------------
      19 |    .expect(selector.userNameInputBox.hasAttribute("disabled")).notOk()
      20 |    .typeText(selector.userNameInputBox, value, {replace: true})


      at Object.(anonymous) (/Users/HDO/VSCodeProjects/testcafe-starter/domains/testcafe-sample-page/steps/i-enter-my-name.ts:18:6)
      at (anonymous) (/Users/HDO/VSCodeProjects/testcafe-starter/domains/testcafe-sample-page/steps/i-enter-my-name.ts:7:71)
      at (anonymous) (/Users/HDO/VSCodeProjects/testcafe-starter/step-runner.ts:11:11)
      at test (/Users/HDO/VSCodeProjects/testcafe-starter/features/testcafe-sample-page.spec.ts:23:66)
```
There is only details for the code on the last file in the call stack, and very often this code is too generic at that level because this code is just a method that is reused everywhere in other tests.
In this situation it is very difficult to find the root cause of the failure. 

As tests are executed on remote agent (Teamcity), the way to find the root cause of the test failure is to load the test locally on the dev machine and debug it.

The main workaround is to spread, everywhere in the code, `console.log` statements so that Teamcity can generate a detailed log for every test execution. But this detailed log does not enable a fast analysis.

### Proposed solution

It would be great to have an enhanced `spec` reporter that enables to have the source code not only on the last error in the stack trace but for each file inside the stack trace, like in this example 
Note that:
 - for each file there are more source code lines around the failure point
- all files in the stack trace are visited up to the fixture file itself (which is not the case for the current `spec`reporter

```txt
1) The specified selector does not match any element in the DOM tree.

   Browser: Firefox 59.0.0 / Mac OS X 10.12.0

      13 |
      14 |  const value = inputData.name || "";
      15 |
      16 |  await t
      17 |    .setTestSpeed(config.testcafe.testSpeed)
   --------------------------------------------
    → 18 |    .hover(selector.userNameInputBox)
   --------------------------------------------
      19 |    .expect(selector.userNameInputBox.hasAttribute("disabled")).notOk()
      20 |    .typeText(selector.userNameInputBox, value, {replace: true})
      21 |    .pressKey("tab");
      22 |};
      23 |

      at Object.(anonymous) (/Users/HDO/VSCodeProjects/testcafe-starter/domains/testcafe-sample-page/steps/i-enter-my-name.ts:18:6)
      at (anonymous) (/Users/HDO/VSCodeProjects/testcafe-starter/domains/testcafe-sample-page/steps/i-enter-my-name.ts:7:71)
      at __awaiter (/Users/HDO/VSCodeProjects/testcafe-starter/domains/testcafe-sample-page/steps/i-enter-my-name.ts:3:12)
      at exports.default (/Users/HDO/VSCodeProjects/testcafe-starter/domains/testcafe-sample-page/steps/i-enter-my-name.ts:7:36)


       6 |  if (canExecute === false) {
       7 |    return;
       8 |  }
       9 |  const foundStep = stepMappings[stepName];
      10 |  if (typeof foundStep === "function" ) {
   --------------------------------------------
    → 11 |    await foundStep(stepName);
   --------------------------------------------
      12 |    return;
      13 |  }
      14 |  throw new Error(`Step "${stepName}" is not mapped to an executable code.`);
      15 |}
      16 |export async function given(stepName: GivenStep) {

      at (anonymous) (/Users/HDO/VSCodeProjects/testcafe-starter/step-runner.ts:11:11)
      at (anonymous) (/Users/HDO/VSCodeProjects/testcafe-starter/step-runner.ts:7:71)
      at __awaiter (/Users/HDO/VSCodeProjects/testcafe-starter/step-runner.ts:3:12)
      at executeStep (/Users/HDO/VSCodeProjects/testcafe-starter/step-runner.ts:14:12)
      at Object.(anonymous) (/Users/HDO/VSCodeProjects/testcafe-starter/step-runner.ts:20:9)
      at (anonymous) (/Users/HDO/VSCodeProjects/testcafe-starter/step-runner.ts:7:71)
      at __awaiter (/Users/HDO/VSCodeProjects/testcafe-starter/step-runner.ts:3:12)
      at Object.when (/Users/HDO/VSCodeProjects/testcafe-starter/step-runner.ts:34:12)


      19 |  await  then("no name should be populated");
      20 |  await   and("I cannot submit my feedback on testcafe");
      21 |});
      22 |
      23 |test("Scenario: can send feedback with my name only", async () =) {
   --------------------------------------------
    → 24 |  await  when("I enter my name");
   --------------------------------------------
      25 |  await  then("I can submit my feedback on testcafe");
      26 |});
      27 |
      28 |test("Scenario: send feedback", async () =) {
      29 |  await env.only( "devci");

      at Object.(anonymous) (/Users/HDO/VSCodeProjects/testcafe-starter/features/testcafe-sample-page.spec.ts:24:10)
      at (anonymous) (/Users/HDO/VSCodeProjects/testcafe-starter/features/testcafe-sample-page.spec.ts:7:71)
      at __awaiter (/Users/HDO/VSCodeProjects/testcafe-starter/features/testcafe-sample-page.spec.ts:3:12)
      at test (/Users/HDO/VSCodeProjects/testcafe-starter/features/testcafe-sample-page.spec.ts:23:66)
```

**Comment by VasilyStrelyaev** [comment]
Note that every line in the callstack shows line and column numbers that locate a place in code where the exception occurred. This helps pinpoint the error origin while keeping the report brief.

However, I agree that a verbose report could be useful in certain cases. At the same time, I cannot promise that we will create such a reporter in the nearest future. You can try to do this yourself. Use our [Reporter Plugin](https://devexpress.github.io/testcafe/documentation/extending-testcafe/reporter-plugin/) guide for help.

And feel free to ask us for assistance should you face any difficulties.

**Comment by Makavelic** [comment]
Please leave this open, a custom reporter does not fix the issue as testRunInfo.errs does not contain information about where the issue occurred. Like OP said, it contains the stack trace for the file causing the error, but that isn't always helpful since it could be a common function causing the issue. Instead, it would be great for the error to also include the test step causing the issue. This is extremely common when using a Page Object Model design.

**Comment by IssacH** [comment]
> Please leave this open, a custom reporter does not fix the issue as testRunInfo.errs does not contain information about where the issue occurred. Like OP said, it contains the stack trace for the file causing the error, but that isn't always helpful since it could be a common function causing the issue. Instead, it would be great for the error to also include the test step causing the issue. This is extremely common when using a Page Object Model design.

Hi @Makavelic @hdorgeval @AndreyBelym @Ogurecher  ,

Currently we also face the problem in testcafe that the callstack will be incomplete when we are using page object to organize our util functions. We could only see the file causing the error, but we could not see the full call stack information. Since node with latest version has a flag '--async-stack-traces' and I did some testing with this flag and I can see a clear callstack for all the async functions. So is there any chance for testcafe not to use babel but to use node original mechanism to interpret the modules? Or do you have any other solution now to show a complete full stack trace for testcafe?

Thanks,
Issac

**Comment by VasilyStrelyaev** [comment]
There is no such capability at present. Please see the detailed explanation in [this comment](https://github.com/DevExpress/testcafe/issues/6251#issuecomment-852076584).

**Comment by Bayheck** [comment]
Unfortunately, we cannot currently address this issue because its priority is low.
