### ISSUE TITLE
Be able to mock long lasting request

### ISSUE THREAD

**Issue by hdorgeval** [DevExpress/testcafe#3246]
### The problem

TestCafe does not enable to test the case where an asynchronous HTTP call to the backend takes too long.

if you create a request mock like this:

```js
var mock = RequestMock()
    .onRequestTo(/*...*/)
    .respond((req, res) => {
        // Step 1 : execute sync code that takes a lot of time (more than 30 seconds for example) like a for loop with millions of iterations
       // Step 2 : send response
    });
```

At runtime, when the code reach step2, the testcafe code hangs.

### Proposed solution (not the same as [proposal](https://github.com/DevExpress/testcafe/issues/2425))

It would be great to have an API like this:

```js
var mock = RequestMock()
    .onRequestTo(/*...*/)
    .delayResponse(30000) // duration in milliseconds
    .respond((req, res) => {
       // send response: the response is sent only after the duration specified in .delayResponse
    });
```

**Comment by VasilyStrelyaev** [comment]
Thank you for your proposal. We will consider this feature during our future planning.

**Comment by GeneGenie** [comment]
any plans here?

**Comment by AlexKamaev** [comment]
We do not plan to implement this in the near future

**Comment by Artem-Babich** [comment]
We decided not to implement this enhancement. The promise-based solution from the [https://github.com/DevExpress/testcafe/issues/2425#issuecomment-855941322](https://github.com/DevExpress/testcafe/issues/2425#issuecomment-855941322) comment is an official solution. Please use it.
