### ISSUE TITLE
Same code working in v0.20.4 not working in v 0.23.3---Error - Content of the iframe in which the test is currently operating did not load.

### ISSUE THREAD

**Issue by anuragpattanayak3** [DevExpress/testcafe#3253]
Same code working in v0.20.4 not working in v 0.23.3---Error - Content of the iframe in which the test is currently operating did not load.

### What is your Test Scenario?
 An anchor link inside an iframe
 
### What is the Current behavior?
1) Content of the iframe in which the test is currently operating did not load.
 
### What is the Expected behavior?
pass
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 await t.switchToIframe('#myframe1234')
 .click('div[class="colioioiodl-xzfas-11212"]>a') 
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...  can not disclose
3. Execute this command... await t.switchToIframe('#myframe1234')
                                            .click('div[class="colioioiodl-xzfas-11212"]>a') 
4. See the error...  Content of the iframe in which the test is currently operating did not load
 
### Your Environment details:
 
* testcafe version:                 0.23.3
* node.js version:                 any
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:                                   reproduced in a newer version

**Comment by AndreyBelym** [comment]
Please provide additional information to help us reproduce the issue.
1. The Node.js, browser and operating system versions.
2. Screenshots of the browser Developer Tools window during the test session, including the Console and Network tabs.
3. A screencast of the test session with DevTools window.
4. A [network activity report](https://confluence.atlassian.com/kb/generating-har-files-and-analyzing-web-requests-720420612.html).

**Comment by anuragpattanayak3** [comment]
![screenshot 18](https://user-images.githubusercontent.com/46106819/50412734-c732ef80-082f-11e9-877e-9760788ea98f.png)
This refers to the error in the command prompt window.



![screenshot 19](https://user-images.githubusercontent.com/46106819/50412735-c732ef80-082f-11e9-915d-f1dba012e558.png)
This refer to the node version and windows pc version.


problem is not with the code because its perfectly and smoothly working with v0.20.4

**Comment by anuragpattanayak3** [comment]
![screenshot 19](https://user-images.githubusercontent.com/46106819/50413005-c69b5880-0831-11e9-93d4-96ffd51b9e1a.png)

This refers to the node version and the windows pc version




![screenshot 20](https://user-images.githubusercontent.com/46106819/50413007-c733ef00-0831-11e9-839e-f964f3b9ac29.png)

this refers to the testcafe running environment.

**Comment by anuragpattanayak3** [comment]
But getting passed for all posibilities for version version 0.20.4

**Comment by AndreyBelym** [comment]
Thank you for the provided information, but it still not enough to find the cause of the issue. 

Since you can't disclose your page, please create a sample project that can be used to reproduce the problem or provide the remaining information described in [my previous comment](https://github.com/DevExpress/testcafe/issues/3253#issuecomment-449747912).

In particular, share screenshots or a screencast of the browser's Developer Tools window during the test session, including the Console and Network tabs. There is an instruction at: [How To: Use Windows 10's Screen Recording Utility](https://www.itprotoday.com/windows-10/how-use-windows-10s-screen-recording-utility) that helps you record a screencast with Windows 10 using the built-in Game DVR tool.
As for a network activity report, you can generate it using the following instructions - [Generating HAR files and analyzing web requests](https://confluence.atlassian.com/kb/generating-har-files-and-analyzing-web-requests-720420612.html).

**Comment by anuragpattanayak3** [comment]
As per privacy concerns we can not share our screen cast and report publicly. Is there any way we can cast the screen as one on one in anydesk or teamviewer.

**Comment by AndreyBelym** [comment]
Currently our team members can't accept a live session, but you can send a screencast to my email. You can find my public email on my GitHub profile page: https://github.com/AndreyBelym.

**Comment by anuragpattanayak3** [comment]
Thank you for your support. Kindly give us some time as we are trying to reproduce the issue or else we will provide all the details in your public mail id.

**Comment by anuragpattanayak3** [comment]
hi andrey
i have sent all the details to your mail: belym.a.2105@gmail.com
kindly check.

Thank you

**Comment by AndreyBelym** [comment]
Thank you. I've received the message with your data. I need some time to process this information. I will post a message in this thread if I find the cause of the problem or need additional details.

**Comment by anuragpattanayak3** [comment]
Thank you for your quick response.

**Comment by anuragpattanayak3** [comment]
Thank you for your suggestions. Actually previously i have tried with skipping js errors. It was not working, So i will try to see which version has the issue and try for that access thing also. Thank you

**Comment by anuragpattanayak3** [comment]
Hi Andrey
I tried with the versions and found out that upto v0.20.4 its working on every versions but the issue is persistent from v0.20.5 onwards. Kindly check whether there are some modifications in the iframe context. I am still trying for that access thing. i will confirm as soon as possible.
Thank you

**Comment by Farfurix** [comment]
@anuragpattanayak3 

Hello,

Please accept my apologies for the delayed response.
There were a lot of changes since `testcafe@0.20.4`. Could you please update your TestCafe Installation to `v1.1.3`? Please try it and tell us if it resolves the issue.
