### ISSUE TITLE
Does testcafe support to load any crx extensions and also setup ModHeader extension with the custom header values in chrome browser

### ISSUE THREAD

**Issue by shyedhu** [DevExpress/testcafe#3258]
Does testcafe support to load crx extensions in chrome browser 

If so , please let me know what method needs to be try out

i tried below the code it doesn’t work out
======================
await t.eval(new Function(fs.readFileSync('/foo.crx').toString()));
==================
And also testcafe support to setup ModHeader extension with the custom header values

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. We try to keep the GitHub issue tracker for bugs and feature requests only (see also: Contributing). This issue looks like a question that would be best asked on StackOverflow - an amazing platform for users to ask and answer questions.

Also I've found a thread about Chrome extensions in the TestCafe forum, check this answer for instructions about installing and using extensions in a test session: https://testcafe-discuss.devexpress.com/t/how-to-handle-chrome-extensions/1061/2
