### ISSUE TITLE
await Selector('div').withText(/some Text/);

### ISSUE THREAD

**Issue by suncodeer** [DevExpress/testcafe#3259]
#### HEADS UP!

For TestCafe API, usage and configuration inquiries, we recommend [StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)).

You may also find answers in our up-to-date [documentation](https://devexpress.github.io/testcafe/documentation/getting-started/) and [answered questions](https://stackoverflow.com/questions/tagged/testcafe) on StackOverflow. This may save your time.

If you have already looked there and have not found an appropriate answer, [file a new question on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe).

**Comment by suncodeer** [comment]
How could I get inner text of testcafe ?

**Comment by AndreyBelym** [comment]
Thank you for your inquiry! We try to keep the GitHub issue tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)). This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions. You can also search for already answered questions by using the `testcafe` tag: https://stackoverflow.com/search?q=%5Btestcafe%5D+innertext
