### ISSUE TITLE
Sometimes browsers are hanging on their idle pages during test execution.

### ISSUE THREAD

**Issue by georgiy-abbasov** [DevExpress/testcafe#326]
It happens when client send service message 'fatal-error', and this deferred object is true:
[TestRun-legacy](https://github.com/DevExpress/testcafe/blob/master/src/legacy/test-run/index.js#L106). 

We need some time to investigate this problem.

**Comment by georgiy-abbasov** [comment]
Looks like the issue duplicated

**Comment by AlexanderMoskovkin** [comment]
Fixed with #313
