### ISSUE TITLE
Add example of the data-driven testing

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#3268]
Links:
* https://stackoverflow.com/questions/53953746/documentation-for-performing-data-driven-testing-using-testcafe
* https://testcafe-discuss.devexpress.com/t/multiple-execution-of-one-test-with-different-data/219/2

**Comment by ShumonA** [comment]
any update on this?

**Comment by Farfurix** [comment]
@ShumonA, I cannot provide any estimate date as to when it will be implemented. Please stay tuned to our updates in this issue.
