### ISSUE TITLE
[docs] Add Continuous Integration Recipes

### ISSUE THREAD

**Issue by VasilyStrelyaev** [DevExpress/testcafe#3270]
Add new CI services to the Continuous Integration section:
https://devexpress.github.io/testcafe/documentation/continuous-integration/

- [ ] [AWS CodePipeline](https://aws.amazon.com/codepipeline/)
- [ ] [Shippable](https://www.shippable.com/index.html)
- [ ] [Codeship](https://codeship.com/)

What other CI services you use for your projects do you want us to cover? Please leave suggestions in the comments!

**Comment by ljowen** [comment]
I'm using bamboo for CI, could offer some assistance with documenting steps

**Comment by titerman** [comment]
Closed in favour of https://github.com/DevExpress/testcafe/issues/7151
