### ISSUE TITLE
When running with --test-grep and --concurrency, more browsers are started than needed

### ISSUE THREAD

**Issue by pbiggar** [DevExpress/testcafe#3274]
### What is your Test Scenario?

I'm running test-cafe with `--concurrency 4` and also with `--test-grep` to limit the number of tests being run. There are less than 4 tests to run.

### What is the Current behavior?

Testcafe starts up 4 browsers.
 
### What is the Expected behavior?

Testcafe should run the only the number of browsers needed to run the tests (in my case, 3).
 
 
### Your Environment details:
 
* testcafe version:                   0.23.1
* node.js version:                    v11.4.0
* command-line arguments:  test-cafe chrome --test-grep paste --reporter=spec,json:result.json,xunit:result.xml
* browser name and version: Chrome 71
* platform and version:          MacOS 10.13.6

**Comment by AndreyBelym** [comment]
Thank you for your suggestion! 

However, I don't think that the described case is very common. Generally, if you want to run a small number of tests, you do this for debugging purposes, and the concurrency mode will only make it harder. Also the benefit of running multiple browsers is almost negligible if you don't have a large test suite. So I think such optimization won't be useful, but will make the code more complex.

**Comment by pbiggar** [comment]
To clarify, we run testcafe from a script, and so users do not independently choose these. I suspect that many folks use testing tools from scripts and not just at the command line, so I do feel this could be more common than you suppose.
