### ISSUE TITLE
Run test commands from an interactive console

### ISSUE THREAD

**Issue by dimaip** [DevExpress/testcafe#3275]
### What are you suggesting?
I want to be able to run TestCafe test commands from some sort of interactive console, instead of having to wait for the whole test to run. Also this console should have auto-completion, so it would to explore the TestCafe API interactively.

### What alternatives have you considered?
I tried entering debug mode from VSC debugger and run some commands from the console.
The problems that I found are:
1) since the tests are transpiled, I had to manually lookup the right path to imported modules, e.g. `_exportableLib.Selector`
2) I wasn't actually able to get any results from selectors by running them in console manually.
E.g. `t.expect(_exportableLib.Selector('body').exists).ok('exists').then(a => console.log(a))` outputs another Promise, and I have no idea how to unwrap it: `Promise {_then: Array(0)}`

So the ideal solution for me would be if the `.debug()` screen had an interactive console built in, from which I could run all the commands that I could from inside the test and that position (including all imported modules resolved correctly).
Alternatively I'd like to at least be able to do that from a debugger.

Wdyt?

**Comment by AlexSkorkin** [comment]
Thank you for sharing your idea with us. We were thinking about a similar functionality and have already planned it in the context of this issue:

https://github.com/DevExpress/testcafe/issues/3244 [Allow to debug Selector expressions in the debug mode](https://github.com/DevExpress/testcafe/issues/3244)
 
I'll link the issue you reported to that thread and close it as a duplicate, so we will take your scenario and requirements into account when implementing this feature.

**Comment by dimaip** [comment]
Thanks a lot, that's precisely what I was thinking about, sorry for not being able to locate that issue before creating this one.
