### ISSUE TITLE
Handle multiple browser screenshots

### ISSUE THREAD

**Issue by nicgirault** [DevExpress/testcafe#3277]
I can't find a solution in the doc to run the tests on multiple browsers without screenshot collision.

For example:

```javascript
runner
        .src(['./tests/**/*.cafe.ts'])
        .browsers([
          'chrome --allow-insecure-localhost',
          'chrome:emulation:device=iphone X --allow-insecure-localhost',
        ])
        .screenshots( './screenshots')

...

test('Testcafe is awesome', async t => {
  await t
    .navigateTo(url)
    .takeScreenshot('file1.png')
```

is creating screenshot collision with testcafe 0.23.3.

And

```javascript
runner
        .src(['./tests/**/*.cafe.ts'])
        .browsers([
          'chrome --allow-insecure-localhost',
          'chrome:emulation:device=iphone X --allow-insecure-localhost',
        ])
        .screenshots(
          './screenshots',
          false,
          '${USERAGENT}/${TEST_INDEX}/${FILE_INDEX}'
        )

...

test('Testcafe is awesome', async t => {
  await t
    .navigateTo(url)
    .takeScreenshot()
})
```

is also creating collision since it runs in the same chrome version.

I noticed the message (https://github.com/DevExpress/testcafe/commit/99879219d0914b562996db1392ac782eba8e10b0#diff-21bd011656e62e7ec1bce6665df4447dR98) `make sure that each screenshot has a unique path`. But in the tests, I don't have access to the current browser string specified in the runner.

Write now, I will deal with this issue like this but it looks like a big hack.

```javascript
import bowser from 'bowser'

test('Testcafe is awesome', async t => {
  const userAgent = await t.eval(() => window.navigator.userAgent)
  const browser = bowser.getParser(window.navigator.userAgent).getBrowser()

  await t
    .navigateTo(url)
    .takeScreenshot(`${browser.mobile ? 'mobile' : 'desktop'}/my-screenshot.png`)
})
```

Thanks for your help

**Comment by nicgirault** [comment]
Actually running this is OKish so this issue could be closed although I think it would be interesting to implement something

```javascript
const runTests = ({ browser, screenshotsFolder }) =>
  createTestCafe(config.hostname)
    .then(tc => {
      testcafe = tc
      return testcafe.createRunner()
    })
    .then(runner => {
      return runner
        .src(['./tests/**/*.cafe.ts'])
        .browsers(browser)
        .screenshots(`./screenshots/${screenshotsFolder}`)
        .reporter('spec')
        .run()
        .then(failedCount => {
          testcafe.close()
          if (failedCount) {
            throw new Error('Tests failed: ' + failedCount)
          }
        })
    })

startServer()
  .then(() => {
    return Promise.all([
      runTests({
        browser: 'chrome --allow-insecure-localhost',
        screenshotsFolder: 'desktop',
      }),
      runTests({
        browser: 'chrome:emulation:device=iphone X --allow-insecure-localhost',
        screenshotsFolder: 'mobile',
      }),
    ]).then(() => {
      process.exit(0)
    })
  })
  .catch(error => {
    process.stderr.write(`${error}\n`)
    process.exit(1)
  })

```

**Comment by LavrovArtem** [comment]
Thank you for providing additional details.
I'm happy to hear that you have figured out how to resolve the original issue. However, I agree that the current behavior is not optimal and we need to improve our user agent pattern generation algorithm because at the moment the user agent string is identical in both scenarios you described. That is why you faced a screenshot collision issue when running your test cases in multiple browsers with different emulation arguments.
I've created a separate [issue](https://github.com/DevExpress/testcafe/issues/3290) where we will improve this. You are welcome to track it to see our progress with this optimization.
