### ISSUE TITLE
Ability to restart the browser for each fixture

### ISSUE THREAD

**Issue by nickroth** [DevExpress/testcafe#3278]
### What is your Test Scenario?

Our Single Page App can be very heavy at times. I've noticed that if I refresh the page numerous times IE has a tendency to run into what looks like a memory leak issue causing the page to fail to fully load and I have to restart the browser. During this time, TestCafe is still responsive and operating as expected 👏 but tests fail because the application failed to load. However I want my test suite to be a bit more robust and just restart the browser for each fixture.

### What are you suggesting?

Either as a configuration option or via some API available to fixture setup let me restart the browser for each fixture.

### What alternatives have you considered?

The current workaround I have is to run TestCafe multiple times for IE. Each run just runs a few fixtures so that IE doesn't get overloaded in any single run. Otherwise I simply just have to ignore IE (which I'd love to do on a more permanent basis but this isn't October 2020 yet).

I also did try going through some of the TestController code to find a way to get access to the BrowserConnection to manually call restart (added with #1815) but I couldn't easily find a way to that. 

### Additional context

I do understand that the core issue that I should be fixing is outside of TestCafe's realm. However I could see a general "restart the browser" API being useful to some test scenarios. For example, verifying that certain data or preferences persists across browser sessions as expected.

**Comment by miherlosev** [comment]
Hi @nickroth 

Thank you for your suggestion. TestCafe should automatically restart the browser when the latter starts to slow down. It's a core feature and we have plans to improve this behavior.
Track this [issue](https://github.com/DevExpress/testcafe/issues/3278) to be notified of progress.
