### ISSUE TITLE
useRole IndexedDB on Chrome71 cleanup fails

### ISSUE THREAD

**Issue by raDiesle** [DevExpress/testcafe#3279]
For longer time I haven't run the tests and now they fail.
The only version change is to Chrome 71.

await t
  .useRole(testHelper.playerA)
 .useRole(testHelper.playerB)

Problem: 
When useRole playerB is executed the first time, IndexedDB does no cleanup/switch,
so playerA is still logged in and Login form UI is not visible so useRole Login for playerB 
can be performed.

upgrading testcafe to 0.23.3 does not help

I am using GoogleAuth, firebaseui-angular/ https://github.com/firebase/firebaseui-web
to do Login

**Comment by miherlosev** [comment]
Hi @raDiesle 

At present, TestCafe doesn't reset/restore `indexedDB` databases when roles are switched.
There is a feature request for your case - https://github.com/DevExpress/testcafe/issues/2420.
Track https://github.com/DevExpress/testcafe/issues/2420 to be notified of our progress.
