### ISSUE TITLE
BrowserConnection and BrowserJob interoperation issue in quarantine mode

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#328]
When a test fails in quarantine mode, browser goes to idle page, and server hangs. 

*Short version:*
We need to refactor how `browserConnection` removes `browserJob` from its `jobQueue`.

*Long version:*
For simplification, let's assume that a `browserConnection` has an one `browserJob` in `jobQueue`, and the `browserJob` has an one `testRun` in `testRunQueue`. 

Whats going on when you start test in quarantine mode and it fails:

1. Just when we are about to start the test, Idle Page requests status from server, so [browserConnection.getStatus](https://github.com/DevExpress/testcafe/blob/master/src/browser-connection/index.js#L105) is called. The method calls itself [browserConnection._popNextTestRunUrl](https://github.com/DevExpress/testcafe/blob/master/src/browser-connection/index.js#L51), that checks `jobQueue.length` and makes a call to [browserJob.popNextTestRunUrl](https://github.com/DevExpress/testcafe/blob/master/src/runner/browser-job.js#L105).

2. [browserJob.popNextTestRunUrl](https://github.com/DevExpress/testcafe/blob/master/src/runner/browser-job.js#L105) shifts `testRunQueue` and returns URL to an opened session. Note that `testRunQueue` is empty now.

3. After we have returned to  [browserConnection._popNextTestRunUrl](https://github.com/DevExpress/testcafe/blob/master/src/browser-connection/index.js#L51), we are calling [browserJob.hasQueuedTestRun](https://github.com/DevExpress/testcafe/blob/master/src/runner/browser-job.js#L101). Because `testRunQueue` is empty, it returns `false`, so `browserConnections` shifts `jobQueue`. So `jobQueue` is empty now.

4. When test is failed, client sends a message with error to server and requests status. The message is passed to server `testRun` object, that reports failure to `browserJob`. Because we are quarantine mode, [_startQuarantine](https://github.com/DevExpress/testcafe/blob/master/src/runner/browser-job.js#L29) and [_keepInQuarantine](https://github.com/DevExpress/testcafe/blob/master/src/runner/browser-job.js#L50) are called, and a new `testRun` is prepended into `testRunQueue`. Now `browserConnection` must return status url. We are expecting that `browserConnection` will call `browserJob.popNextTestRunUrl` and get a url for the new `testRun`, but `browserConnection` removed `browserJob` from `jobQueue`, so it's empty and `browserConnection` simply returns idle page url. So client navigates to idle page, and server waits for `done` event from `browserJob` that will never be emitted.

**Comment by inikulin** [comment]
Yap, this whole thing is quite fragile. Do you have any ideas about how we can make things better and bulletproof?

**Comment by AndreyBelym** [comment]
Maybe we need to remove `browserJob` from `jobQueue` when it emits `done`, or when `browserJob.popNextTestRunUrl` returns `null`.

**Comment by inikulin** [comment]
> Maybe we need to remove browserJob from jobQueue when it emits done, or when browserJob.popNextTestRunUrl returns null.

AFAIK there were some problems with this options already
