### ISSUE TITLE
Testcafe: Unable to open browser (safari) due to error

### ISSUE THREAD

**Issue by phyllisnoester** [DevExpress/testcafe#3281]
### What is your Test Scenario?

 We are running cross-browser end2end tests on browserstack for our website in a Concourse pipeline.

### What is the Current behavior?

Although passing locally and in a docker container, when running the e2e in safari in our pipeline, the first few pass, afterwards they fail with the following error message:

<img width="843" alt="screen shot 2019-01-07 at 14 29 02" src="https://user-images.githubusercontent.com/43133295/50770739-9ff50d00-1288-11e9-8e7f-7f63a9cb28f0.png">

### Your Environment details:
 
* testcafe version: 0.21.1                  
* browser name and version: Safari 12.0

**Comment by AndreyBelym** [comment]
I can't reproduce the problem with `testcafe@0.23.3` and `testcafe-browser-provider-browserstack@1.7.0`. Please try these versions in your pipeline.

If you still can reproduce the issue with the latest package versions, try to start the browsers using the Browserstack Automate API: [Browserstack JS Testing and Browserstack Automate](https://github.com/DevExpress/testcafe-browser-provider-browserstack#browserstack-js-testing-and-browserstack-automate) and provide additional information about your environment: CI system type, configuration, test image, etc.
