### ISSUE TITLE
testcafe 0.23.3 broken on windows 10

### ISSUE THREAD

**Issue by Hotell** [DevExpress/testcafe#3283]
### What is your Test Scenario?
Not important
 
### What is the Current behavior?
- testcafe 0.23.0 works on both win 10 and mac.
- testcafe 0.23.3 won't run on Windows 10. On mac everything works

**ERROR:**

```
yarn testcafe chrome e2e/tests --hostname localhost -e -u
yarn run v1.12.3
$ C:\Users\david.klement\Documents\Thor\lossevents-ui\node_modules\.bin\testcafe chrome e2e/tests --hostname localhost -e -u
ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
``` 

### What is the Expected behavior?
don't break software with semver "fix" bumps :)
 

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   0.23.0 (works), 0.23.3 (doesn't work)
* node.js version:                    8.12.0
* command-line arguments:   testcafe chrome e2e/tests -e -u --hostname localhost 
* browser name and version: Chrome 71
* platform and version:          macOS 10.14.2, Windows 10

**Comment by drakor007** [comment]
testcafe 1.0.0-alpha.1 doesn't work on Windows10 too. Other versions of node.js,Chrome were unchanged.

> $ yarn testcafe chrome e2e/tests --hostname localhost
> yarn run v1.12.3
> $ C:\Users\david.klement\Documents\Thor\lossevents-ui\node_modules\.bin\testcafe chrome e2e/tests --hostname localhost
> ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
> 
> Type "testcafe -h" for help.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
> David.Klement@N1244 MINGW64 ~/Documents/Thor/lossevents-ui (develop)
> $ yarn testcafe -v
> yarn run v1.12.3
> $ C:\Users\david.klement\Documents\Thor\lossevents-ui\node_modules\.bin\testcafe -v
> 1.0.0-alpha.1
> Done in 1.21s.

**Comment by AlexSkorkin** [comment]
Thank you for submitting this issue. However, until now my attempts to replicate it were unsuccessful.
 
I've tried both 0.23.3 and 1.0.0-alpha.1 versions on Windows 10 version 1803 using yarn in Chrome 71.0.3578.98 (Official Build) (64-bit) and tests are executed properly.
 
We will continue looking into it. If you have any additional details that may help us to replicate this issue, please share them with us.

**Comment by drakor007** [comment]
Hi, due to corporate decisions I run on Windows version:

Edition: Windows 10 Enterprise
Version: 1709
OS Build 16299.371

Chrome 71.0.3578.98 (Official Build) (64bit)

Last Testcafe working build is 0.23.0

**Comment by AlexSkorkin** [comment]
Thank you for providing additional information. We tried to reproduce this issue on several other test machines and were unable to replicate it. 
 
We noticed that you are using some non-standard command prompt window to execute testcafe. Would you please clarify what tools (bash?) you are using to run test cases? In addition, please try using the regular Windows PowerShell or DOS Command Prompt to run tests and see how it works. You might also want to run tests under an admin user.

**Comment by drakor007** [comment]
Hi, I tried it in cmd , admin cmd, power shell, admin power shell and Error is exactly the same. :(

![power-shell-admin](https://user-images.githubusercontent.com/12645375/50963547-4e898f80-14cd-11e9-884b-bcc85cb8f523.png)

**Comment by AlexSkorkin** [comment]
Thank you for the update. 
To help us research this issue, would you please provide us with your test suite and a configuration script (testcafe-configr)? If you don't want to share the tests publicly on github, you can send them at suppport@devexpress.com and no one except our team will see your tests.

**Comment by Hotell** [comment]
the `testcafe-configr` uses `testcafe` programatic API. the same "results" are when running testcafe directly. 

It must be definitely an issue on your side. `0.23.0` works, since `0.23.2` it doesn't 👀

**Comment by AlexSkorkin** [comment]
Our attempts to replicate this issue were unsuccessful. The error message you provided does not look like a Windows 10 related issue and it may be caused by any other reasons including your application. That is why I'm asking you to provide your tests suite and your web site URL or a sample application. Once we examine them, it will be easier to find the real cause of the issue and fix it. I appreciate your cooperation.
