### ISSUE TITLE
Mobile emulation does not work with xvfb-run

### ISSUE THREAD

**Issue by trannguyenhung011086** [DevExpress/testcafe#3284]
### What is your Test Scenario?

 Run mobile emulation test with using virtual display xvfb
### What is the Current behavior?

Command: `~/www-auto$ xvfb-run -a -s "-screen 0 1280x720x24" testcafe "chromium:emulation:device=iphone --no-sandbox" tests/testcafe/e2e_ui/mobile --selector-timeout 15000 --assertion-timeout 5000`

Error:
`Using locally installed version of TestCafe.
ERROR Was unable to open the browser "chromium:emulation:device=iphone --no-sandbox" due to error.`

Error: Command failed: /home/nguyenhung86/www-auto/node_modules/testcafe-browser-tools/bin/linux/glibc-64/resize 400001 320 552

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:188:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)

Type "testcafe -h" for help.`
### What is the Expected behavior?

 Should be able to use xvfb like when using desktop browser. When not use mobile emalation, test can work.
 
### Your Environment details:
 
* testcafe version:                   0.23.3
* node.js version:                    11.6.0
* platform and version:          Linux Ubuntu 19.04

**Comment by AndreyBelym** [comment]
TestCafe needs to resize a browser window to make it have the same size as the emulated device screen size. Thus, TestCafe requires a ICCCM/EWMH compatible window manager in X11 environments (e.g. XVFB) - [Resize Window](https://devexpress.github.io/testcafe/documentation/test-api/actions/resize-window.html).

You can install and start a compatible window manager (e.g. Fluxbox) before starting TestCafe if you want to use XVFB, or just use Chrome's Headless mode: [Testing in Headless Mode](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/testing-in-headless-mode.html). In the latter case, you won't need additional software like XVFB and Fluxbox and your tests will likely run faster and more stably.
