### ISSUE TITLE
Provide API to dump and restore state

### ISSUE THREAD

**Issue by link89** [DevExpress/testcafe#3286]
### What is your Test Scenario?

In order to save time in test execution, we may try to reuse state cross different tests.
Testcafe have provided a feature name "Role". But this feature is just for login scenarios.
I hope that we could have some low level API to dump and restore states.

### What are you suggesting?

My suggestions is testcafe should provide two API: dumpState, restoreState

When I calling `const state: String = await t.dumpState()`, testcafe should collect necessary information and serialize it.
Then when I need to using the state dumped by other tests, I just need to call `await t.restoreState(state)`. And testcafe should restore browser to the point that `await t.dumpState()` is called.

This design will provide enough flexibility for developer to using the state in their test cases. For example, when I using testcafe for integration testing, I can even persist state to database so that I can share state cross run!

**Comment by miherlosev** [comment]
Hi @link89 
 
TestCafe has several built-in mechanisms which control the web page state.
* The [Roles](https://devexpress.github.io/testcafe/documentation/test-api/authentication/user-roles.html) feature manages the `localStorage` and `sessionStorage` states.
* The [Disable page reloads](https://github.com/DevExpress/testcafe/issues/1770) feature allows you to
control test page reloading during test execution.
* [Test and fixture hook](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#initialization-and-clean-up) allows you to perform initialization and clean up actions for your tests (this feature covers your use case with database state sharing). 
 
Implementation of the API you described makes sense if there are a lot of other use cases which the current TestCafe API doesn't cover. Could you please elaborate on such use cases?

**Comment by link89** [comment]
Hi @miherlosev 

The API I want to have should be able to dump all data will be persisted in browser, includes: Cookies, Session Storage, Local storage, indexedDB, so `Role` is not enough.

`Disable page reloads` looks good but the API is not clear. It seems like have a lot of discussion under this topic.

As a developer, I think a simple and clean API can be applied to more scenarios. Here is some examples.
Suppose we have following API
`resetState()`: reset browser to init state
`dumpState(): String`: dump all date persisted in browsers (include testcafe context)
`restoreState(data: String)`: restore persisted data and testcafe context according to dumped data

## Scenario 1: skip login if

**Comment by miherlosev** [comment]
Thank you for the detailed explanation. I've marked this issue as a suggestion.

**Comment by misu-moriya** [comment]
Any update?
I also would like to reuse data in IndexedDB among different tests.

**Comment by AlexSkorkin** [comment]
Once we get any results, we will post them here.

**Comment by chriswwalz** [comment]
Just going to bump this as this as this is something that's hampered our use of TestCafe

**Comment by AdrienLemaire** [comment]
Can we re-open this issue please ? This is one of @miherlosev suggestions for working with firebase https://github.com/DevExpress/testcafe/issues/4939#issuecomment-609744085

I am unable to get a TestCafe + Firebase + Browserstack flow working (testcafe not supporting signInWithPopup with cloud browsers, and firebase not working with signInWithRedirect if removing indexedDB . This issue could have been an alternative to get something working.

**Comment by alexphilin** [comment]
The case with supporting Firebase for Role is described in a separate issue – [https://github.com/DevExpress/testcafe/issues/2420](https://github.com/DevExpress/testcafe/issues/2420).

The enhancement described in this issue is very abstract. Also, there are no other cases when it's necessary. So, this issue can be closed.
