### ISSUE TITLE
--test-meta  and  --fixture-meta  doesn't work on testcafe  v0.21.1 and v0.22.0

### ISSUE THREAD

**Issue by shyedhu** [DevExpress/testcafe#3300]
I tried to run --test-meta  and --fixture-meta on testcafe  v0.21.1 and v0.22.0

Since testcafe  v0.21.1 and v0.22.0 are stable version on my project , so can you please help me what exact value needs to be passed on inside test class and run command 

Test1.js
==========

fixture
 .meta({ smoke: 'true'})

test
 .meta({ device: 'true'})

================

Example run command 1 

testcafe chrome my-tests --fixture-meta smoke=true

Example run command 2 

testcafe chrome my-tests —test-meta device=true

**Comment by shyedhu** [comment]
Please note : --test-meta and --fixture-meta should work latest testcafe version , my concern is --test-meta and --fixture-meta doesn't work on testcafe v0.21.1 and v0.22.0 , since testcafe v0.21.1 and v0.22.0 are stable version against my web project , can you please help what exact json value needs to passed over CLI and test file also

**Comment by shyedhu** [comment]
i checked the https://github.com/DevExpress/testcafe/pull/2841 , but not clear for stable testcafe v0.21.1 and v0.22.0

**Comment by AlexKamaev** [comment]
The `--test-meta` and `--fixture-meta` features were introduced in version 0.23.1. Please see the changelog for details: https://github.com/DevExpress/testcafe/blob/master/CHANGELOG.md#v0231-2018-11-7
 
In addition, I need to mention that this inquiry looks like a question that would be best asked on [StackOverflow ](https://stackoverflow.com/questions/ask?tags=testcafe)- an amazing platform for users to ask and answer questions.
 
We try to keep the GitHub issue tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)).
