### ISSUE TITLE
Sporadic browser connectivity issues

### ISSUE THREAD

**Issue by jmullo** [DevExpress/testcafe#3304]
There are other similar issues reported. Issues tend to keep closing, but the problem still exists. Yes, it might be something outside TestCafe causing the issues, but retry functionality would make test runs more robust. There's apparently some half-implemented retrying for the proxy already, but what about that browser connection error?

### What is your Test Scenario?

Tests cases are browsing a page on localhost dev server (create-react-app/webpack).
 
### What is the Current behavior?

A few different sporadic errors. Increasing concurrency (-c X) seems to make the errors appear more often. The first two might appear in the middle of the test run. The last one always happens right in the beginning and no test cases are executed after that.

``` 
Failed to find a DNS-record for the resource at "http://localhost:3000/"
``` 

``` 
Failed to find a DNS-record for the resource at "http://localhost:3000/someResource.jpg"
``` 

``` 
{ Error: Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
    at /app/node_modules/testcafe/src/runner/browser-set.js:84:30
    at Generator.next (<anonymous>)
    at step (/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /app/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/app/node_modules/babel-runtime/node_modules/core-js/library/modules/_export.js:36:28)
    at /app/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at BrowserSet._waitConnectionsOpened (/app/node_modules/testcafe/src/runner/browser-set.js:77:37)
    at _waitConnectionsOpened (/app/node_modules/testcafe/src/runner/browser-set.js:107:35)
    at invokeCallback (/app/node_modules/pinkie/index.js:60:12)
    at Array.forEach (<anonymous>)
    at publish (/app/node_modules/pinkie/index.js:147:32)
    at Array.publishFulfillment (/app/node_modules/pinkie/index.js:152:2)
    at Immediate.asyncFlush [as _onImmediate] (/app/node_modules/pinkie/index.js:17:19)
    at runCallback (timers.js:812:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5) constructor: [Function: GeneralError] }
``` 
 
### Your Environment details:
 
* testcafe version:                   0.23.3
* node.js version:                    8.12.0
* command-line arguments:   -c 4
* browser name and version:  Firefox 60 (headless), Chrome 71 (headless)
* platform and version:           Jenkins/Kubernetes/Docker/Linux (not TestCafe's own Docker image)

**Comment by jmullo** [comment]
Yes, I meant `retryTestPages`. Is there a reason why it's still undocumented and not included in CLI options? I'm not using TestCafe directly, so another project needs to be modified in order to use it.

Also, does it only retry the initial page load or also any resource requests after that?

Anyway, it won't help with that last error on my list. Sure, I can fork it. Just tell me what would be worth logging and where.

**Comment by AndreyBelym** [comment]
Thank you for your cooperation, I think the following points are worth for noting:

1. HTTP requests and responses handled by your application server. I think you know the place where you can embed some logging statements. We will now that requests from the browser are handled by your application and get the data that is supposed to be processed by the browser.

2.  [Stages of the Request Pipeline class](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/request-pipeline/index.js#L28) in `testcafe-hammerhead`. `testcafe-hammerhead` is the most important part of TestCafe. It acts as a proxy between your application server and the browser, and Request Pipeline sends requests and process responses to your server. We will know that TestCafe sends correct requests to your server and get correct responses from it.

3. The [_onRequest method of the Proxy class](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/proxy/index.js#L139). Proxy accepts requests from the browser and passes them to Request Pipeline. When Request Pipeline sends a request and get a response back from your server, `testcafe-hammerhead` does some modifications and returns the modified response to Proxy. Also Proxy handles special TestCafe request like requests when a browser connects to TestCafe. So we can be assured that TestCafe gets correct requests from the browser and then responds with correct data back to it.

4. Browser's network activity. In Chrome, you can collect network activity information as an HAR report. If you can connect a browser from your machine to a container as a remote browser and still can reproduce the issue, you can easily generate an HAR report by using instructions from the following article: [Generating HAR files and analyzing web requests](https://confluence.atlassian.com/kb/generating-har-files-and-analyzing-web-requests-720420612.html). If you can't reproduce the issue when the browser is not inside the container, you can try to integrate [cyrus-and/chrome-har-capturer](https://github.com/cyrus-and/chrome-har-capturer) into the [Chrome browser provider](https://github.com/DevExpress/testcafe/blob/master/src/browser/provider/built-in/chrome/cdp.js#L48).

**Comment by kel30a** [comment]
We have been experiencing this issue for a while now too. 

Slightly different app, ours is a .NET Core React app built using webpack 4.

**My Environment details:**
testcafe: 1.0.1,
testcafe-reporter-teamcity: 1.0.10,
testcafe-reporter-html: 1.3.0,
Browser: Chrome 72.0.3626 / Windows 8.1.0.0 (Issue occurs both in Headless and non-headless)
I've set it up using using the 6th parameter:
`createTestCafe('localhost', undefined, undefined, undefined, true, true)`

Looking at our webserver logs, I can't see any errors or anything unusual - I suspect once testcafe gets this error, the web server never receives or see a request for the page. I initially suspected it could be a timeout issue if our webserver was getting caught in a long running process, but the tests that fail only run for <3 seconds which is well short of any default timeouts. It's  seemingly random which tests fail, (even though the tests always run in the same order) sometimes early tests can fail, but they tend to usually be later in the test run, and not the last (IE tests will generally pass after them).

Is there any logs that I could take that you think might help?

**Comment by kel30a** [comment]
The quarantine mode seems to help, some "evidence" (I'm hesitant to be call it confirmed with 4/4 successful runs in a row) that it is helping is that we have Screenshots on fail enabled, and we are getting screenshots when no tests are failing. The screenshots are from different tests too.

**Comment by kel30a** [comment]
Concurrency definitely exacerbates the issue and have reverted back to concurrency 1. I've have had a few failures since, but its noticeably more stable.
