### ISSUE TITLE
docs: Update Travis CI doc to remove xvfb

### ISSUE THREAD

**Issue by CozyKourai** [DevExpress/testcafe#3306]
Hello! 

xvfb is no longer needed to run headless browser in travis. 

I run a few tests without 
```
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
```
and everything is working just fine! :)

**Comment by VasilyStrelyaev** [comment]
Thank you for reporting this!

I'll try your approach in Travis CI and if it works for me as well, I'll update the tutorial accordingly.

**Comment by titerman** [comment]
The latest version of the Travis CI guide no longer mentions `xvfb`
