### ISSUE TITLE
 Run TestCafe and  Appium with a real device

### ISSUE THREAD

**Issue by maximilianosilva753** [DevExpress/testcafe#3315]
### What is your Test Scenario?
Run tests on a real mobile device, with TestCafe and appium.

### What are you suggesting?
Help to create a simple test, where the testcafe opens the browser on an actual device, through the appium connection.

**Comment by Farfurix** [comment]
Hello, @maximilianosilva753.
Could you please clarify what issues you have when you tried to connect Appium and TestCafe and run your test?

Once you have started your [Appium server](http://appium.io/docs/en/about-appium/getting-started/#starting-appium), you can try one of these approaches to connect the server:
1. Using the TestCafe API - https://testcafe-discuss.devexpress.com/t/is-there-a-way-to-run-test-on-mobile-browser-without-manually-opening-the-url-scanning-qr-code/511/2
2. Using the Browser Provider - https://www.npmjs.com/package/testcafe-browser-provider-selenium

This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions. We try to keep the GitHub issues tracker for bugs and feature requests only.
