### ISSUE TITLE
File download options popup window in IE

### ISSUE THREAD

**Issue by hiruthre** [DevExpress/testcafe#3325]
### Are you requesting a feature or reporting a bug?
Feature

### What is your Test Scenario?

Need to validate excel file.. On clicking download button, system is asking options to save, open and close.. Due to IT policy I can't disable option in IE..Now want to click save option and validate the file...

Tried with nativedailogue handler..but no luck..
#### Provide the test code and the tested page URL (if applicable)

 
Your website URL (or attach your complete example):

Your complete test code (or attach your test files)

```js

```
### Your Environment details:
 
* testcafe version:        0.21.1           
* node.js version:         8.9.4           
* command-line arguments:  
* browser name and version:  IE 11
* platform and version:           WINDOWS
* other:

**Comment by AlexKamaev** [comment]
There is no way to overcome this issue, except for disabling the popup in settings. As a workaround, I can suggest you use the `requestHooks` feature to download the file. Please try the following example in IE:
```JS
import fs from 'fs';
import { Selector, RequestHook } from 'testcafe';

class MyHook extends RequestHook {
    constructor (requestFilterRules, responseEventConfigureOpts) {
        super(requestFilterRules, responseEventConfigureOpts);
    }

    onRequest (event) {
    }

    onResponse (event) {
        const path = 'file.zip';

        fs.writeFileSync(path, event.body);
   }
}

fixture `fixture`
    .page `https://github.com/AlexKamaev/match-url-wildcard`;

test.requestHooks(new MyHook('https://codeload.github.com/AlexKamaev/match-url-wildcard/zip/master', {
    includeHeaders: true,
    includeBody:    true
}))(`test`, async t => {
    await t.click(Selector('summary').withText('Clone or download'));
    await t.click(Selector('a').withText('Download ZIP'));

    await t.wait(10000);
});
```
When the browser finishes downloading, the hook gets the response and saves it to the file system. 
 
Please refer to the following articles to read more information about hooks:
https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/
https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/creating-a-custom-http-request-hook.html

**Comment by hiruthre** [comment]
Thanks for the response Alex.... 
Want to know which URL i need to pass in below code
`test.requestHooks(new MyHook('https://codeload.github.com/AlexKamaev/match-url-wildcard/zip/master', {`

Following is scenario
1. Open main URL and goto transaction screen
2. Click on detail link
3. System opens popup with details
4. In detail popup, have 'Export' button
5. Click 'Export' button to download file...

Currently, I am passing popup URL in requestHooks but no luck...
Kindly advise...

**Comment by AlexKamaev** [comment]
You need to pass the exact url of your file if you have it. If you don't have one (in case your url is generated automatically), you can pass a regular expression that matches the url of your file.
 
Please refer to the following article to get details: https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/specifying-which-requests-are-handled-by-the-hook.html
