### ISSUE TITLE
404 hammerhead.js for SSR app 

### ISSUE THREAD

**Issue by alexlopez-natgeo** [DevExpress/testcafe#3327]
### What is your Test Scenario?

I have a fastify server with nextjs (for SSR) and when try to test headless, 404 for /hammerhead.js, it does make sense because to use dynamic routing I need `f.get('/*', cb)`, so the statics are located under `static/`  (it does work without headless because is running inside an Iframe)

### What is the Current behavior?

 I cant change the path for `hammerhead.js` to use `/static/hammerhead.js`
### What is the Expected behavior?

 a config key or env var to set the prefix of the static resources

* testcafe version: 0.23.3                  
* node.js version: 10.14                   
* command-line arguments:  "chrome:headless" 
* browser name and version: chrome 71 
* platform and version: ubuntu 18.04

**Comment by AlexKamaev** [comment]
Would you please clarify why you need this functionality by giving us more details? It would be great if you also provide the url to your project and your test code
