### ISSUE TITLE
Display what the exact element is being waited for on the web test page

### ISSUE THREAD

**Issue by fnlctrl** [DevExpress/testcafe#3328]
### What is your Test Scenario?
Testing my integration on a third party page that has various behaviors that needs handling, i.e. when there is element A, do this, otherwise do that. For example, when the page has a loading spinner, don't press save; when the page displays "failed to load, try again", press "try again" button.
So there're lots of 
```js
if (await Selector('.foo').with({timeout: 10000})()) {
  // do this
}
if (await Selector('.bar').with({timeout: 10000})()) {
  // do that
}
```
code in my test.

When the third party page does something unexpected that breaks my test, I need to find out what exactly went wrong. But even if I watch the test from beginning, all I see is "Waiting for an element to appear", and I have no idea what my test is actually doing, which branch is it at, so there's no hint for what Selector condition needs fixing.

### What are you suggesting?

![image](https://user-images.githubusercontent.com/5557143/51517924-51826980-1e57-11e9-96a0-a0dad0918770.png)

It would be very helpful if the exact Selector condition can be displayed, e.g. "Waiting for #foo to appear"

**Comment by AndreyBelym** [comment]
Thank you for your inquiry! It's an interesting suggestion, our team will discuss this feature and think about adding it to the development roadmap.
