### ISSUE TITLE
Using of SIKULI script in testcafe

### ISSUE THREAD

**Issue by anuragpattanayak3** [DevExpress/testcafe#3333]
### What is your Test Scenario?
  

I have to test a flash application and it is forcing me to use other tools over testcafe. Which i dont want because testacef is very user friendly and handy when comes to web based testing.

### What are you suggesting?

My suggestion is the sikuli script should be injected using client function so that it would be helpful to accomplish some other processes alongwith GUI basesd flash applications.

### What alternatives have you considered?

As of now Flash-Selenium is working with sikuli.

### Additional context
 

Inclusion of SIKULI script will be a pretty useful step for testcafe.

**Comment by AlexKamaev** [comment]
TestCafe does not support flash applications and we do not have plans to develop it in this direction. That's why it's unlikely that we will support Sikuli in the future
