### ISSUE TITLE
Inconsistent withText behavior with text-transform:uppercase

### ISSUE THREAD

**Issue by kirovboris** [DevExpress/testcafe#3335]
### What is your Test Scenario?
```js
import { Selector } from 'testcafe';

fixture `New Fixture`
    .page `devexpress.com`;

test('New Test', async t => {
    await t
        .maximizeWindow()
        .click(Selector('a').withText('PRODUCTS'));
});
```
 
### What is the Current behavior?
The link has textContext `Products`, uppercase implemented via `text-transform:uppercase`.
`Selector('a').withText('PRODUCTS')` finds an element in Chrome and Firefox, but it can't find in IE and Edge.

**Comment by AndreyBelym** [comment]
We apply a text filter to the `innerText` property for elements that are not `<option>`'s: https://github.com/DevExpress/testcafe/blob/master/src/client-functions/selectors/selector-text-filter.js#L28. In Chrome and Firefox, `innerText` follows the CSS transformation and gets upper-cased, but in IE (can't check it in Edge) it preserves the original case.

**Comment by miherlosev** [comment]
After discussing this issue with @kirovboris , we decided to interpret it as an enhancement.

**Comment by freddiecoleman** [comment]
Also being affected by this. I understand it is a browser issue rather than testcafe but without a case insensitive option for withText (or another alternative) there is not a clean workaround for this.

**Comment by AlexKamaev** [comment]
@freddiecoleman the `withText` method can accept Regexp with [ignore case modifier](https://www.w3schools.com/jsref/jsref_regexp_i.asp) as param.

**Comment by adamdicarlo** [comment]
What I've been experiencing is sometimes the withText() selector matches the `text-transform: uppercase` text and sometimes it does not. Maybe a race condition with the styling getting applied?

Please add something to the withText and withExactText docs about this -- I spent hours figuring this out. :(

**Comment by miherlosev** [comment]
Hi @folks,

IE support will end after the TestCafe 3.0 release, the Edge browser moved to the Chrome script engine. So, now there are no browsers that affect this issue. We also added information about case sensitivity of the `withText` method to our documentation.
