### ISSUE TITLE
Allow to run TestCafe over HTTPS with self-signed certificates in Chrome Headless

### ISSUE THREAD

**Issue by sijosyn** [DevExpress/testcafe#3340]
### What is your Test Scenario?

Download the provided test repo and execute the notification test in Chrome Headless with SSL (TestCafe HTTPS mode)
 
### What is the Current behavior?

We have a push notification bar/prompt that works only in TestCafe HTTPS mode (see screenshot). Tests run fine in Chrome with SSL certs. But TestCafe fails to run in Chrome Headless with SSL certs.
 
### What is the Expected behavior?

Tests should run fine in Chrome Headless with SSL certs. I tried passing '--allow-insecure-localhost --ignore-certificate-errors' flags. Didn't help. Any suggestions how to make the tests run in Chrome Headless with SSL?
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

Download this repo - https://github.com/sijosyn/testcafe-syntests and run the notification test from test suite.

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 testcafe 'chrome:headless --allow-insecure-localhost --ignore-certificate-errors' desktop/notification.js --ssl 'key=./node_modules/openssl-self-signed-certificate/key.pem;cert=./node_modules/openssl-self-signed-certificate/cert.pem'
```
</details>

<details>
<summary>Your complete test report:</summary>

<img width="923" alt="screen shot 2019-01-23 at 10 22 36 am" src="https://user-images.githubusercontent.com/29459281/51617191-b7bfc880-1ef9-11e9-8a97-eaea476098c5.png">
</details>

<details>
<summary>Screenshots:</summary>

<img width="1436" alt="expected" src="https://user-images.githubusercontent.com/29459281/50235001-ec81b280-0384-11e9-9754-8ab1373b591d.png">

Works in Chrome:
------------------
<img width="913" alt="screen shot 2019-01-23 at 10 19 03 am" src="https://user-images.githubusercontent.com/29459281/51617359-108f6100-1efa-11e9-9c6b-bb7f2fbe317a.png">
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                    0.23.3
* node.js version:                     v8.11.1
* command-line arguments:    testcafe 'chrome:headless --allow-insecure-localhost --ignore-certificate-errors' desktop/notification.js --ssl 'key=./node_modules/openssl-self-signed-certificate/key.pem;cert=./node_modules/openssl-self-signed-certificate/cert.pem'
* browser name and version:  Chrome 71
* platform and version:           macOS 10.14
* other:                                    Notification bar is Chrome only feature.

**Comment by AlexKamaev** [comment]
I was able to reproduce the issue. It seems it's related to Chrome Headless, not to TestCafe. Chrome Headless does not support the `--ignore-certificate-errors` flag. Please refer to the following thread https://groups.google.com/a/chromium.org/forum/#!msg/headless-dev/eiudRsYdc3A/BLuLMTX_BgAJ
In theory, it's possible to overcome the issue using the [Chrome debug protocol ](https://chromedevtools.github.io/devtools-protocol/)
I've discussed the issue with the team and we will consider implementing it in the future, so for now I recommend you use Chrome without the enabled Headless mode.

**Comment by SteveSonoa** [comment]
Greetings! Is there any movement or status on this issue, please?

**Comment by Farfurix** [comment]
@SteveSonoa 

Hello,

I cannot give you any additional information about this issue. We will update this thread once we have any news regarding this.

**Comment by KimNikB** [comment]
Hello there!
Is there any news regarding this you can share? The issue is really _bugging_ me out. Thanks :)

**Comment by AlexSkorkin** [comment]
Once we get any results, we will post them here. You are also welcome to submit your PR to address this issue.

**Comment by star-kashyap** [comment]
Hi, I am able to run tests with ssl certificate and chrome flags --allow-insecure-localhost --ignore-certificate-errors', however testcafe is too slow with xhr and other requests keep pending for longer times. Can someone help ?

**Comment by alexey-lin** [comment]
Hi @star-kashyap, 

Thank you for sharing your experience. Since XHR performance is not related to the topic of this discussion, I believe it would be better to open a separate issue here on GitHub or ask a question on [StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.

**Comment by jzhang52** [comment]
We also run into this issue using a self-signed cert for testing. Hope to see this support in TestCafe soon!

**Comment by sswales** [comment]
Just wondering if this has progressed any further?

**Comment by DonRichards** [comment]
Still no update?

**Comment by miherlosev** [comment]
Hi @DonRichards,

In this case, it's a Google Chrome restriction. TestCafe will support this feature as soon as Google Chrome implements it.

So, there is no reason to keep this issue open. Please track the related Google Chrome channels.
