### ISSUE TITLE
Missing typings for TestCafe, Runner, BrowserConnection Classes

### ISSUE THREAD

**Issue by infctr** [DevExpress/testcafe#3341]
### What is your Test Scenario?

```js
import testcafe from 'testcafe';

testcafe('localhost', 1338)
  .then(t => {
    tc = t;

    return tc
      .createRunner()
      .src(tests)
      .browsers(['chrome'])
      .run();
  })
```

![image](https://user-images.githubusercontent.com/15550153/51619973-7d2e4e00-1f42-11e9-85b8-ad8b9e02aaee.png)

 
### What is the Current behavior?

Results in TS error
```
Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("testcafe")' has no compatible call signatures.ts(2349)
```
 
### What is the Expected behavior?

TestCafe, Runner and BrowserConnection Classes have proper typings
 
I wasn't able to find whether this was addressed before. Looked up into the source definitions file as well and I'm not sure whether this is a `declare module { ... }` limitation.

What's the proper way to declare and merge types for these classes locally? How can I contribute adding typings for missing classes, I mean how can I add a callbale signature to a module?

**Comment by infctr** [comment]
Currently I've defined types locally and doing a type cast 

```ts
((createTestCafe as unknown) as TestCafeFactory)('localhost', 1338)
```

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. Yes, TestCafe lacks TypeScript definitions for the Runner API, as they were created to support TestCafe testing API for tests written in TypeScript. However, it will be nice to have definitions for all APIs.

 If you think about making a PR, I think we can define a callable interface (take a look at [ClientFunction](https://github.com/DevExpress/testcafe/blob/master/ts-defs/index.d.ts#L15))  as a default module export.

**Comment by infctr** [comment]
@AndreyBelym thanks for the tip, figured out how to do it!
