### ISSUE TITLE
Docker Compose doesn't mount windows volumes

### ISSUE THREAD

**Issue by StrangeKarma** [DevExpress/testcafe#3354]
### What is your Test Scenario?
Id like to get TestCafe containers into our enterprise Rancher host.
 
### What is the Current behavior?
I'm am not able to mount the folders that contain my test files locally in to the rancher container.  
 
### What is the Expected behavior?
The local test folder should be accessible in the TestCafe container 
 
### What is your web application and your TestCafe test code?
docker-compose.yml:

version: '2'
services:
   hub:
    image: selenium/hub
    ports:
    - 4444:4444/tcp
   chrome:
    image: selenium/node-chrome
    environment:
      HUB_HOST: hub
    volumes:
    - /dev/shm:/dev/shm
   firefox:
    image: selenium/node-firefox
    environment:
      HUB_HOST: hub
    volumes:
    - /dev/shm:/dev/shm
   hub-lb:
    image: rancher/lb-service-haproxy:v0.9.6
    ports:
    - 4001:4001/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'
   testcafe:
    container_name: testcafe
    image: testcafe/testcafe
    ports:
      - 1337:1337
      - 1338:1338
      - 3000:3000
    shm_size: 2G
    environment:
    - SELENIUM_SERVER=http://docker-04-tst-grid.prd.costargroup.com:4001/wd/hub
    - SCREEN_WIDTH=1920
    - SCREEN_HEIGHT=1080
    - COMPOSE_CONVERT_WINDOWS_PATHS=0
    volumes:
    - //c/costar-suite-market-search/tests:/tests
    entrypoint: ["/opt/testcafe/docker/testcafe-docker.sh", "chromium --no-sandbox", "/tests/docker/"]

rancher-compose.yml:

version: '2'
services:
  hub:
    retain_ip: true
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 4444
      unhealthy_threshold: 3
      interval: 5000
      strategy: recreate
      request_line: GET / HTTP/1.0
  chrome:
    scale: 2
    start_on_create: true
  firefox:
    scale: 1
    start_on_create: true
  hub-lb:
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - protocol: http
        service: hub
        source_port: 4001
        target_port: 4444
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      strategy: recreate
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```
function runTest(iteration, browser) {
	if (browser === 'rancher') {
		createTestCafe('localhost', 1338 + iteration, 1339 + iteration)
			.then(function(tc) {
				cafeRunner = tc
				const runner = tc.createRunner()
				return runner
					.src('./test.js')
					.screenshots('./reports/screenshots', true)
					.browsers('selenium:chrome')
					.run()
					.catch(function(error) {
						console.error(error)
					})
			})
			.then(function(report) {})
	}
 
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by StrangeKarma** [comment]
Also I am using the npm package testcafe-browser-provider-selenium for connectivity, although my primary problem is I cannot access my testfiles in the docker container.

**Comment by miherlosev** [comment]
Hi @StrangeKarma 

At first glance, the problem is related to the folder mounted to the docker image.
If you are using the Docker Toolbox, note that Docker containers can only access the `C:\Users` directory by default. If you need to run tests from other directories, share these directories as described in the [Docker documentation](https://docs.docker.com/toolbox/toolbox_install_windows/#optional-add-shared-directories).

**Comment by StrangeKarma** [comment]
Hello again Mikhail, just a quick update on the issue I'm experiencing. I removed everything from my rancher compose besides the hub and chrome to isolate the issue better. Now when I run my script i get the following error:

> Executing task: npm run marketanalytics-tstmain-AnalyticsTabPageHealthChecks <


> @ marketanalytics-tstmain-AnalyticsTabPageHealthChecks c:\costar-suite-market-search\tests
> cucumber-js.cmd ./features/AnalyticsTabPageHealthCheck.feature $ cucumber.js --tag 'AnalyticsTabPageHealthChecksTstMain' --format json:./reports/report.json --world-parameters "{\"browser\": \"rancher\"}"

Server started on port 3000
(node:22004) UnhandledPromiseRejectionWarning: WebDriverError: Session [b3d5346123de55944bbed0bf907596a0] not available and is not among the last 1000 terminated sessions.
Active sessions are[]
    at Object.checkLegacyResponse (c:\costar-suite-market-search\tests\node_modules\selenium-webdriver\lib\error.js:585:15)
    at parseHttpResponse (c:\costar-suite-market-search\tests\node_modules\selenium-webdriver\lib\http.js:533:13)
    at Executor.execute (c:\costar-suite-market-search\tests\node_modules\selenium-webdriver\lib\http.js:468:26)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:22004) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22004) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
F---F.(node:22004) UnhandledPromiseRejectionWarning: WebDriverError: Session [780f02deb1e0434b13f7e87620642e7c] not available and is not among the last 1000 terminated sessions.
Active sessions are[]
    at Object.checkLegacyResponse (c:\costar-suite-market-search\tests\node_modules\selenium-webdriver\lib\error.js:585:15)
    at parseHttpResponse (c:\costar-suite-market-search\tests\node_modules\selenium-webdriver\lib\http.js:533:13)
    at Executor.execute (c:\costar-suite-market-search\tests\node_modules\selenium-webdriver\lib\http.js:468:26)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:22004) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

Here is the rancher compose which worked perfectly when i was using Specflow:
version: '2'
services:
  firefox:
    image: selenium/node-firefox:3.5.1
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    networks:
      - int-prd-dockeroverlay01
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444 
  chrome:
    image: selenium/node-chrome:3.5.1
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    networks:
      - int-prd-dockeroverlay01
    environment:
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444 

  hub:
    image: selenium/hub:3.5.1
    ports:
      - "4444:4444"
  hub-lb:
    image: rancher/lb-service-haproxy:v0.7.9
    ports:
    - 4001    # external load balancer port
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'

**Comment by StrangeKarma** [comment]
Any idea or suggestion will be greatly appreciated. Thanks.

**Comment by miherlosev** [comment]
Your environment is too complex. It takes a lot of time to setup it on my machine.
The problem can be related to wrong docker setup, communication with Rancher or issues with the 'selenium:chrome' browser's provider, or something else.
Would you please create a simple example to reproduce which I can run on my machine?
