### ISSUE TITLE
Cookies not preserved when running with docker testcafe/testcafe

### ISSUE THREAD

**Issue by aboe026** [DevExpress/testcafe#3355]
### What is your Test Scenario?
That reloading a specific page (with `t.navigateTo()`) correctly preserves a users selection by way of a cookie value.
 
### What is the Current behavior?
This works with testcafe locally, but fails when running testcafe with the docker image (`testcafe/testcafe`, even with the `alpha` tag). I put a div that contains the cookie value, and when running in docker container I have screenshots before refresh where I see the cookie set, then after refresh the cookie is undefined.
 
### What is the Expected behavior?
The cookie should be preserved on page refresh so the users selection is preserved on page refresh
 
### What is your web application and your TestCafe test code?
```js
 test('Visits Sort Cookie Persists Across Refresh', async t => {
  await browserTestUtil.createVisits(BROWSER_VISITS, t.ctx.user.email, password)
  await t.navigateTo(visitsPage.url)
  await visitsPage.validateSort('start', 'desc')
  await visitsPage.setSort('city')
  await t.takeScreenshot()
  await visitsPage.validateSort('city')
  const visit = {
    country: 'United States',
    state: 'Michigan',
    city: 'Detroit',
    start: '2018-10-25',
    end: '2018-10-30'
  }
  await visitsPage.createVisit(visit)
  await visitsPage.validateRow(9, visit)
  await t.navigateTo(visitsPage.url)
  await visitsPage.validateSort('city')
  await visitsPage.validateRow(9, visit)
})
```

```
1) AssertionError: Visits table shows city as sort field: expected false to be truthy

         Browser: Chrome 68.0.3440 / Linux 0.0.0
         Screenshot:
      /app/screenshots/2019-01-26_02-52-08/test-1/Chrome_68.0.3440_Linux_0.0.0/errors/1.png

            146 |        .click(this.sort)
            147 |
      .expect(this.getSortDialogOptionSelected()).eql(`${field}${browserUtil.capitalizeFirstLetter(order)}`,
      `Visits table shows ${field} as sort field ordered ${order}`)
            148 |        .pressKey('esc')
            149 |    } else {
            150 |      await t
          > 151 |        .expect(this.getTableHeader(field).find('svg').exists).ok(`Visits table
      shows ${field} as sort field`)
            152 |        .expect(this.getTableHeader(field).find('svg').hasClass('desc')).eql(order
      === 'desc', 'Visits table shows correct sort order')
            153 |    }
            154 |  }
            155 |
            156 |  async setFilter(fieldMap, wait = true, pressEnter = false) {

            at ok (/app/test/browser/pages/visitsPage.js:151:64)
            at VisitsPage.validateSort (/app/test/browser/pages/visitsPage.js:143:44)
            at validateSort (/app/test/browser/tests/visitsPageTest.js:169:20)
```
screenshot before reload (notice cookie value at top center)
![testcafe-scrot-before-reload](https://user-images.githubusercontent.com/11340779/51781981-cde2aa00-20ee-11e9-8e6a-82201c66800b.png)
screenshot after reload (notice cookie value at top center)
![testcafe-scrot-after-reload](https://user-images.githubusercontent.com/11340779/51782056-4c8c1700-20f0-11e9-829c-6249e8af3c07.png)

 
### Your Environment details:
 * Local
** testcafe version: 0.23.3
** node.js version: 9.3.0
** command-line arguments: `cross-env MONGO_DB=mygellyn-test SCREEN_SIZE=desktop testcafe chrome test/browser --app \"cross-env MONGO_DB=mygellyn-test node -r dotenv/config build/server_bundle.js\" --app-init-delay 5000 --skip-js-errors`
** browser name and version: chrome version 71.0.3578.98
** platform and version: Windows 10 build 17763

* CI:
** testcafe version:
```
testcafe/testcafe          alpha               7ad34554ef78        3 weeks ago         623MB
testcafe/testcafe          latest              f4d0595ea4d4        2 months ago        596MB
```
** node.js version: 10.10.0
** command-line arguments: `docker run --rm --network=${dockerName} -v ${mountDir}:/app -e BASE_URL=http://${dockerName}:3000 -e SCREEN_SIZE=desktop -i testcafe/testcafe \'chromium --no-sandbox\' /app/test/browser --app-init-delay 5000 --skip-js-errors --reporter spec,xunit:/app/test-results/chrome-desktop.xml --screenshots-on-fails --screenshots /app/screenshots/`
** browser name and version: `chromium`
** platform and version: Docker container of Jenkins (Debian GNU/Linux 9 (stretch))

** other - I also see the same behavior with firefox (works locally but not in docker)

**Comment by aboe026** [comment]
@istvandesign No I have not tried an explicit `wait` before the refresh. What effect would that have? It seems like the cookie is correctly saved before the refresh already.

**Comment by miherlosev** [comment]
Hi @aboe026

You mentioned that your tests works fine locally and fails with the docker image. This means that performance of your application so considerably degraded when it was run with the docker image that this broke some TestCafe mechanisms. 
Try to use the `--shm-size` docker option (see [Testing Heavy Websites](https://devexpress.github.io/testcafe/documentation/using-testcafe/using-testcafe-docker-image.html#testing-heavy-websites)) and make sure you are using the latest TestCafe version.
![latest-docker](https://user-images.githubusercontent.com/4133518/51828154-086d6200-22fc-11e9-8016-da24366d2635.png)

If it does not help you, we will need an example which we can run on our side.
Your application is rather complex and it's difficult to understand the cause of the problem without direct access to it.

**Comment by aboe026** [comment]
@miherlosev I was able to get past the issue by running the tests on a faster PC. It seems that you were right when you mentioned it was performance related. Thanks for your help!

**Comment by miherlosev** [comment]
I am happy to hear this. Unfortunately, it's difficult to find the cause of the problem without a small example to reproduce which I can run on my machine. Feel free to reopen this ticket if you can provide such an example.

**Comment by aboe026** [comment]
@miherlosev I've invited you to be a collaborator for the repository I saw this error with. Check out the `display-cookie` branch, the `Jenkinsfile` in there has the format of how I run testcafe using the docker image. Let me know if you have any questions.

**Comment by miherlosev** [comment]
I didn't get any notifications regarding it. Please give me a direct link to the repository.

**Comment by aboe026** [comment]
https://github.com/aboe026/mygellyn

**Comment by miherlosev** [comment]
Thank you for the provided example. I need additional time to investigate the problem.

**Comment by miherlosev** [comment]
At present, there is an unsolved problem related to setting up an environment for the example from https://github.com/aboe026/mygellyn repository. 
I'm waiting for the repository owner response.
I will add the issue to the current sprint as soon the problem is reproduced.

**Comment by miherlosev** [comment]
I finally managed to run the project from your repository. The problem is not reproduced with the latest TestCafe version (`1.3.3`). Please try to run your tests with this version and let me know your results.
