### ISSUE TITLE
Test vrious Mobile device and browser

### ISSUE THREAD

**Issue by tuan91** [DevExpress/testcafe#3360]
Hi, is it possible to test various mobile devices and browser?
If so, how can I do that?
Thank you!

**Comment by miherlosev** [comment]
TestCafe allows you to test your application in various browsers.
See more detail in the following help topics:
* [Testing with locally installed browsers](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#local-browsers)
* [Testing using Chrome device emulation](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#using-chrome-device-emulation)
* [Testing via browser-provide plugins](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#browsers-accessed-through-browser-provider-plugins)

We tested TestCafe in [many browsers](https://github.com/DevExpress/testcafe/blob/107f038295f0b1e543a9a473ec6b6d63882d5bb7/Gulpfile.js#L86) (desktop and mobile) using [Saucelabs]() and [BrowserStack]() provides.

In the future, please ask your question on [StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe).
StackOverflow is an amazing platform for users to ask and answer questions: the community will see and answer your question there.
We try to keep GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing). If you find a bug, feel free to open a new issue, but please make sure to follow the bug template. Thank you in advance.
