### ISSUE TITLE
runnerClass - Fails to end process when using reporters with fileStreams

### ISSUE THREAD

**Issue by djbreen7** [DevExpress/testcafe#3361]
### Summary
The node process does not end when running tests in TeamCity with reporters that output to a fileStream. Specifically, I'm using testcafe-reporter-html (latest). The only seems to be on >= 0.23.3. This is potentially a problem with custom reporter boilerplate, but the issue clearly resolves when downgrading testcafe to 0.23.1.

### Workaround
Two options:
1. Don't use a reporter that outputs to a stream.
2. Downgrade testcafe to 0.23.1

### What is your Test Scenario?
Running tests in teamcity with multiple reporters where at least one reporter outputs to a file stream.
 
### What is the Current behavior?
Test finish and build log shows completed, however the process hangs and must be manually ended. It appears the code never reaches the final `.then()`
 
### What is the Expected behavior?
TestCafe should close and the node process should end.
 
### What is your web application and your TestCafe test code?
```javascript
let testcafe = null;

createTestCafe('localhost', 1337, 1338)
    .then(tc => {
        testcafe = tc;
        const runner = testcafe.createRunner();
        const htmlReport = fs.createWriteStream('./reports/integration_report.html');

        return runner
            .screenshots('./screenshots/testsuite', true)
            .src([
                // test files
            ])
            .browsers(['chrome:headless --no-sandbox'])
            .reporter('html', htmlReport)
            // .reporter('html', null) <-- Everything works fine if I do this, however, it's counter-productive
            .reporter('teamcity')
            .run()
            .then(failedCount => {
                console.log(failedCount;
                testcafe.close();
                process.exit();

            })
            .catch(err => {
                console.log(err);
                testcafe.close();
                process.exit(1);
            })
    })
```
 
Your website URL (or attach your complete example):
NA

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

Screenshots:
![image](https://user-images.githubusercontent.com/13296622/51846560-0ba22700-22d7-11e9-9f30-4243b36ed3d3.png)

![image](https://user-images.githubusercontent.com/13296622/51847686-73f20800-22d9-11e9-8665-498c37afeb43.png)
(note that `Process exited with code 1`  is added to the logs on a manual termination from within TeamcCity. You can see from the timestamps that it occurs hours after test completion)

### Steps to Reproduce:
1. Ensure you are running testcafe 0.23.3
2. Ensure testcafe-reporter-html is latest
3. Run your test suite in TeamCity
 
### Your Environment details:
 
* testcafe version:                   0.23.3
* node.js version:                    10.14.1
* command-line arguments:  `node ./tests/testSuite.js`
* browser name and version:  Chrome Headless 71.0.3578.98
* platform and version:           Windows Server 2012 R2, version 6.3

**Comment by miherlosev** [comment]
Hi @djbreen7

The problem was fixed in `testcafe@1.0.0-alpha.2`.
