### ISSUE TITLE
Code Page being changed by testcafe

### ISSUE THREAD

**Issue by Lupiano** [DevExpress/testcafe#3365]
### What is your Test Scenario?

We are trying to run testcafe with chcp 850, because otherwise we are getting the following output:
```
(node:24696) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rej
ection id: 1): Error: write EIO
(node:24696) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr
ecated. In the future, promise rejections that are not handled will terminate th
e Node.js process with a non-zero exit code.
```
 
### What is the Current behavior?

The problem is that sometimes the Code Page is changed when the testcafe command is executed. Before executing testcafe command we execute "chcp 850" but It seems that testcafe is replacing this value.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   0.22.0
* node.js version:                    8.11.4
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by miherlosev** [comment]
Hi @Lupiano 

Try to run your tests using the latest TestCafe version - testcafe@1.0.0-alpha.3.
It the problem still persists, then we need more information about your environment to find the cause of the problem.

Could you please
* run your tests with the latest TestCafe version and send us the stack trace of the unhanded rejection error described above (TestCafe will show the whole stack trace, not only an error message)
* specify your operating system and version and also the current locale name on your computer .

**Comment by Lupiano** [comment]
Hi @miherlosev , thanks for your response. I updated to that testcafe version, and the problem persists. We are running on a VM with Windows Server 2012 R2. The full stack trace is the following:

```
(node:652) UnhandledPromiseRejectionWarning: Error: write EIO
    at _errnoException (util.js:992:11)
    at WriteStream.Socket._writeGeneric (net.js:764:25)
    at WriteStream.Socket._write (net.js:783:8)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at WriteStream.Writable.write (_stream_writable.js:290:11)
    at WriteStream.Socket.write (net.js:707:40)
    at ReporterPluginHost.write (C:\Users\mberruti\AppData\Roaming\npm\node_modu
les\testcafe\src\reporter\plugin-host.js:119:22)
    at ReporterPluginHost.reportTestDone (C:\Users\mberruti\AppData\Roaming\npm\
node_modules\testcafe\node_modules\testcafe-reporter-spec\lib\index.js:74:18)
    at reportTestDone (C:\Users\mberruti\AppData\Roaming\npm\node_modules\testca
fe\src\reporter\index.js:88:31)
(node:652) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This e
rror originated either by throwing inside of an async function without a catch b
lock, or by rejecting a promise which was not handled with .catch(). (rejection
id: 2)
(node:652) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprec
ated. In the future, promise rejections that are not handled will terminate the
Node.js process with a non-zero exit code.
```
The behavior that we are seeing is that at some point the code page is changed to 65001. The tests continue running, but the output is always the specified above.

**Comment by Lupiano** [comment]
BTW we are running on a Command Prompt

**Comment by miherlosev** [comment]
@Lupiano 

Thank you for the provided stack trace. We checked our code that changed the console encoding.
At present, the algorithm is the following: [testcafe-browser-tools](https://github.com/DevExpress/testcafe-browser-tools) change the console encoding to `utf8` to find the browser's installation path. After that, the original encoding will be restored.
This encoding manipulation occurred before test execution. So, we don't have any ideas on how it can affect the reporter output. 
 
Let's try the following experiment.
Run this script with the `node run-test.js` command. 
 
run-test.js
```js
const cp = require('child_process');
const createTestCafe=require('testcafe'); 
 
(async () => {
    const tc = await createTestCafe();     console.log(String(cp.execSync(`chcp`)));     await tc
        .createRunner()
        .src('test.js')
        .browsers('chrome')
        .run();     await tc.close();
})();
```
 
test.js
```js
fixture`1`; test(`1`, t => console.log(String(require('child_process').execSync('chcp'))))
``` 
 
Then, please send us the whole console output.

**Comment by Lupiano** [comment]
Hi @miherlosev 
Yes, for that test example, the chcp is the same at the beginning and at the end. But at some point in our tests the chcp is changed and does not return to the previous state. Is that possible in some way?
