### ISSUE TITLE
Concurrent Test with Roles are Interdependent

### ISSUE THREAD

**Issue by afarqu** [DevExpress/testcafe#3385]
### What is your Test Scenario?
If I set concurrency to 2, ,or just simply run 2 chrome browsers (chrome, chrome), the Roles functionality behaves strangely.

### What is the Current behavior?
The one session waits on the other and automatically logs in, or simply sits 'Waiting for assertion execution' 
 
### What is the Expected behavior?
Sessions can run concurrently 
 
### What is your web application and your TestCafe test code?
Site is at https://studio.varius.cc

Simple login script:
 
```js
 import { waitForReact } from "testcafe-react-selectors";
import { Selector, Role } from "testcafe";

const studioBase = "https://studio.varius.cc"

fixture`Login Test`.page(studioBase).beforeEach(async () => {
	await waitForReact();
});

const regularAccUser = Role(`${studioBase}/login`, async t => {
	// console.log("page", `${studioBase}/login`);
	const emailField = Selector('input[type="email"]');
	const passwordField = Selector('input[type="password"]');
	const submitButton = Selector('button[type="submit"]');
	const checkboxes = Selector('input[type="checkbox"]', { timeout: 0 });

	await t
		.typeText(emailField, "studio.test@varius.io")
		.typeText(passwordField, "Test123!")
		.click(checkboxes.nth(0))
		.click(checkboxes.nth(1))
		.click(submitButton);

}, { preserveUrl: true }
);

test("Login", async t => {
	// Fill out login form
	await t.useRole(regularAccUser);

	// verify correct login
	const pageTitle = Selector("h1");
	await t.expect(pageTitle.innerText).eql("My Objects");
	
});

```
</details>

<details>
<summary>Your complete test report:</summary>

```
<?xml version="1.0" encoding="UTF-8" ?>
<testsuite name="TestCafe Tests: Chrome 72.0.3626 / Mac OS X 10.13.6, Chrome 72.0.3626 / Mac OS X 10.13.6" tests="1" failures="1" skipped="0" errors="1" time="57.375" timestamp="Sat, 02 Feb 2019 21:27:51 GMT" >
  <testcase classname="Login Test" name="Login" time="57.267">
    <failure>
    <![CDATA[
      1) AssertionError: expected 'Welcome to Varius Studio' to deeply equal 'My Objects'

         Browser: Chrome 72.0.3626 / Mac OS X 10.13.6

            29 |    await t.useRole(regularAccUser);
            30 |
            31 |        // verify correct login
            32 |        const pageTitle = Selector("h1");
            33 |        // await t.expect(pageTitle.innerText).eql("Create Your First Object");
          > 34 |        await t.expect(pageTitle.innerText).eql("My Objects");
            35 |
            36 |});
            37 |
            38 |
            39 |

            at eql (/Users/alistairfarquharson/git/studio-common/tests/user/login.test.js:34:38)
    ]]>
    </failure>
  </testcase>
</testsuite>
```
</details>

### Steps to Reproduce:

1. Website is https://www.studio.varius.cc
3. Execute concurrent tests as follows: testcafe -c 2 chrome, chrome tests -e -r xunit:/tmp/test-results/res.xml --selector-timeout 30000 --assertion-timeout 30000 --page-load-timeout 30000
 
### Your Environment details:
 
* testcafe version:   0.23.3
* node.js version:     v10.15.0
* command-line arguments:  testcafe -c 2 chrome tests -e -r xunit:/tmp/test-results/res.xml --selector-timeout 30000 --assertion-timeout 30000 --page-load-timeout 30000
* browser name and version: chrome 71
* platform and version:          macOS 10.13.6

**Comment by AlexKamaev** [comment]
It is expected that when a session in one browser waits until the role is initialized in another browser. Every single role is initialized only once and saves website cookies/storages. When you're using the role for the second time, it's already initialized and cookies/storages are already saved.

However, there is still an issue with roles. When I start a test in two browsers, it is sometimes impossible to sign in in one of the browsers. The cause of the issue is in hash based navigation after the login action (the url is `https://studio.varius.cc/login#access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIs.....`)

Hash based navigation is a limitation of the roles mechanism.

To overcome this issue, you can remove the `preserveUrl: true` option.
