### ISSUE TITLE
Add a mention about video recording feature on the landing page

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#3395]
I think it may attract attention. We could do it after an implementation some other debugability features and highlight them all in one section.

**Comment by miherlosev** [comment]
Live mode is a very valuable feature. We can add mention about live mode on the landing page too.

Cypress put info about the same feature on its landing page.
![image](https://user-images.githubusercontent.com/4133518/52327318-c24f8700-29fc-11e9-80c6-12efd19188fa.png)

**Comment by titerman** [comment]
Collectively decided against this idea (had other priorities) when making the new testcafe.io landing page.
