### ISSUE TITLE
TestCafe fails to start a browser if another TestCafe process cleans temp directories

### ISSUE THREAD

**Issue by joma74** [DevExpress/testcafe#3399]
### What is your Test Scenario?
testcafe tests against chrome and firefox in parallel
 
### What is the Current behavior?

This is not always reproduceable(:sweat:). Happens on travis, but also on local workstation.

Observed at https://travis-ci.org/joma74/angular-ultimate-pro/builds/489304617. Also https://travis-ci.org/joma74/angular-ultimate-pro/builds/488394555. May name a few others.
```
[ci-prod] [test-servencafe-prod-once] ERROR Was unable to open the browser "firefox:headless" due to error.
[ci-prod] [test-servencafe-prod-once]
[ci-prod] [test-servencafe-prod-once] Error: ENOENT: no such file or directory, open '/tmp/testcafe/firefox-profile-5186V7WEUkBnT9PM/user.js'
```

Happend not at e.g. https://travis-ci.org/joma74/angular-ultimate-pro/jobs/489319319.
 
### What is the Expected behavior?
no error
 
### What is your web application and your TestCafe test code?
master at https://github.com/joma74/angular-ultimate-pro
 
Your website URL (or attach your complete example): 

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
const ENVAPPSRVPORT = require("../../config/env/ENVAPPSRVPORT")

import { Selector } from "testcafe"
var Mustache = require("mustache")

fixture("Index_Page_Test").page(
  `http://localhost:${ENVAPPSRVPORT.get()}/index.html`,
)

test("dom_has_critical_elements", async (t) => {
  await t.takeScreenshot()
  await checkHeading(t)

  /**
   * @type { SelectorAPI & HTMLImageElement }
   */
  const imageAngularFirst = await /** @type { ? } */ (Selector(
    "img[data-desc='angular-first']",
  ).addCustomDOMProperties({
    complete: (/** @type {HTMLImageElement} */ el) => {
      return el.complete
    },
    naturalHeight: (/** @type {HTMLImageElement} */ el) => el.naturalHeight,
  }))
  await t.expect(imageAngularFirst.visible).ok()
  await t.expect(imageAngularFirst.complete).eql(true)
  await t.expect(imageAngularFirst.naturalHeight).gt(0)

  /**
   * @type { SelectorAPI & HTMLImageElement }
   */
  const imageAngularSecond = await /** @type { ? } */ (Selector(
    "img[data-desc='angular-second']",
  ).addCustomDOMProperties({
    complete: (/** @type {HTMLImageElement} */ el) => el.complete,
    naturalHeight: (/** @type {HTMLImageElement} */ el) => el.naturalHeight,
  }))
  await t.expect(imageAngularSecond.visible).ok()
  await t.expect(imageAngularSecond.complete).eql(true)
  await t.expect(imageAngularSecond.naturalHeight).gt(0)

  const { error, warn } = await t.getBrowserConsoleMessages()
  await t.expect(error.length).eql(0)
  await t.expect(warn.length).eql(0)
})

/**
 *
 * @param {TestController} t
 */
async function checkHeading(t) {
  const heading = Selector("h1[data-desc='heading']")
  const headingText = await heading.innerText
  const expected = Mustache.render(
    "{{ title }} from Angular 4 App with Webpack {{ major }}.{{ minor }}.{{ patch }}",
    {
      major: "3",
      minor: "12",
      patch: "0",
      title: "Hello",
    },
  )
  await t.expect(headingText).eql(expected)
}

```
</details>

<details>
<summary>Your complete test report:</summary>

```txt
Sorry, but copying all from https://travis-ci.org/joma74/angular-ultimate-pro/builds/489304617 gives this issue output a tilt.

[ci-prod] [test-servencafe-prod-once] $ cross-var start-server-and-test serve-prod http-get://localhost:$npm_package_config_app_svrprod_port/index.html test-prod-cafe-once
[ci-prod] [test-servencafe-prod-once] starting server using command "npm run serve-prod"
[ci-prod] [test-servencafe-prod-once] and when url "http-get://localhost:4003/index.html" is responding
[ci-prod] [test-servencafe-prod-once] running tests using command "test-prod-cafe-once"
[ci-prod] [test-servencafe-prod-once] 
[ci-prod] [test-servencafe-prod-once] > angular-ultimate-pro@0.0.1 serve-prod /home/travis/build/joma74/angular-ultimate-pro
[ci-prod] [test-servencafe-prod-once] > cross-var json-server --quiet --watch db.json --port $npm_package_config_app_svrprod_port --static dist
[ci-prod] [test-servencafe-prod-once] 
[ci-dev ] [test-servencafe-dev-once]  Running tests in:
[ci-dev ] [test-servencafe-dev-once]  - Firefox 65.0.0 / Linux 0.0.0
[ci-dev ] [test-servencafe-dev-once]  - HeadlessChrome 72.0.3626 / Linux 0.0.0
[ci-dev ] [test-servencafe-dev-once] 
[ci-dev ] [test-servencafe-dev-once]  Index_Page_Test
[ci-prod] [test-servencafe-prod-once] 
[ci-prod] [test-servencafe-prod-once] > angular-ultimate-pro@0.0.1 test-prod-cafe-once /home/travis/build/joma74/angular-ultimate-pro
[ci-prod] [test-servencafe-prod-once] > cross-env NODE_ENV=production yarn test-cafe-once
[ci-prod] [test-servencafe-prod-once] 
[ci-prod] [test-servencafe-prod-once] $ cross-var testcafe 'firefox:headless,chrome:headless --no-sandbox --disable-gpu' -S -s $npm_package_config_screenshots -p $npm_package_config_screenshot_path_pattern -r spec,xunit:$npm_package_config_reports/report.xml --page-load-timeout 5000 src/tests/
[ci-dev ] [test-servencafe-dev-once]  ✓ dom_has_critical_elements (screenshots:
[ci-dev ] [test-servencafe-dev-once]  /home/travis/build/joma74/angular-ultimate-pro/target/reports/screenshots/actual/Index_Page_Test/dom_has_critical_elements)
[ci-dev ] [test-servencafe-dev-once] 
[ci-dev ] [test-servencafe-dev-once] 
[ci-dev ] [test-servencafe-dev-once]  1 passed (9s)
[ci-prod] [test-servencafe-prod-once] ERROR Was unable to open the browser "firefox:headless" due to error.
[ci-prod] [test-servencafe-prod-once] 
[ci-prod] [test-servencafe-prod-once] Error: ENOENT: no such file or directory, open '/tmp/testcafe/firefox-profile-8225Hx1vOveakWd1/user.js'
[ci-prod] [test-servencafe-prod-once] 
[ci-prod] [test-servencafe-prod-once] Type "testcafe -h" for help.
[ci-prod] [test-servencafe-prod-once] error Command failed with exit code 1.
[ci-prod] [test-servencafe-prod-once] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[ci-prod] [test-servencafe-prod-once] npm ERR! code ELIFECYCLE
```
</details>

<details>
<summary>Screenshots:</summary>
n.a. console log only
</details>

### Steps to Reproduce:

Linux only

1. git clone https://github.com/joma74/angular-ultimate-pro
2. yarn
3. yarn ci
4. Eventually observe
 
### Your Environment details:
 
* testcafe version:                   1.0.0-alpha.5
* node.js version:                    v10.13.0
* command-line arguments:  cross-var testcafe 'firefox:headless,chrome:headless --no-sandbox --disable-gpu' -S -s $npm_package_config_screenshots -p $npm_package_config_screenshot_path_pattern -r spec,xunit:$npm_package_config_reports/report.xml --page-load-timeout 5000 src/tests/
* browser name and version: Mozilla Firefox 65.0, Chrome 72.0.3626.81
* platform and version:          Ubuntu 16.04.5 LTS
* other:                                   Tested in that setup for a few months now. In the last few days i observed more and more of the above erroring results, which IMO boiled down to be caused by/related to firefox latest. But at the same time kept up to date with testcafe alpha releases.

**Comment by miherlosev** [comment]
Your example contains two TestCafe launches. Sometimes the second launch starts before the first one completely ends. This causes the temporary folder to be cleaned in the wrong way.
As a workaround, you can add a small timeout between runs.

**Comment by alexschwantes** [comment]
We have just started experiencing kind of the opposite. All of our testcafe runs started failing in jenkins due to a testcafe error where it seemed to fail to start a browser: `ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.` However, adding a command to delete the `/tmp/testcafe` folder before running the test has seemed to fix it.

**Comment by miherlosev** [comment]
The problem is not reproduced with the `testcafe@1.10.1`.

**Comment by karim-penny** [comment]
I still face this issue, in testcafe @latest - how can I work around this issue?

**Comment by AlexKamaev** [comment]
The initial issue is marked as closed, as we were unable to reproduce the issue in the 1.10.1 version.

Please try using the example from the comment above: [https://github.com/DevExpress/testcafe/issues/3399#issuecomment-461058340](https://github.com/DevExpress/testcafe/issues/3399#issuecomment-461058340)

If this does not help, could you share a sample project to demonstrate the issue?
