### ISSUE TITLE
Fix unstable /fixtures/runner/api/press-test.js (qunit)

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#340]
It seems the tests fails frequently on OS X and Linux:

https://travis-ci.org/testcafe-build-bot/testcafe/jobs/108036003
https://travis-ci.org/testcafe-build-bot/testcafe/jobs/108037862
https://travis-ci.org/testcafe-build-bot/testcafe/jobs/108047688
https://travis-ci.org/testcafe-build-bot/testcafe/jobs/108055300
https://travis-ci.org/testcafe-build-bot/testcafe/jobs/108238796

**Comment by helen-dikareva** [comment]
We fixed it in https://github.com/DevExpress/testcafe/pull/342
