### ISSUE TITLE
Upgrage embedded TypeScript version to 3.x

### ISSUE THREAD

**Issue by janhartmann** [DevExpress/testcafe#3401]
I have been using Testcafe for a long time and had no problems compiling my TypeScript code with it until today. I am currently experimenting with a MapBox component for our application, but ever since we got the type definitions in from MapBox, the preparation step of Testcafe fails.

Note that no of my test touches any MapBox component or library. 

```
$ testcafe chrome ./test/**/*.test.ts ./test/pages/**/*.test.ts
ERROR Cannot prepare tests due to an error.

Error: TypeScript compilation failed.
/Users/janhartmann/Projects/manager-ui/client/node_modules/@types/mapbox-gl/index.d.ts (50, 40): Type expected.

    at Function._reportErrors (/Users/janhartmann/Projects/manager-ui/client/node_modules/testcafe/src/compiler/test-file/formats/typescript/compiler.js:44:15)
    at TypeScriptTestFileCompiler._reportErrors [as _compileCode] (/Users/janhartmann/Projects/manager-ui/client/node_modules/testcafe/src/compiler/test-file/formats/typescript/compiler.js:75:40)
    at TypeScriptTestFileCompiler._compileCode [as _compileCodeForTestFile] (/Users/janhartmann/Projects/manager-ui/client/node_modules/testcafe/src/compiler/test-file/api-based.js:104:33)
    at TypeScriptTestFileCompiler._compileCodeForTestFile [as compile] (/Users/janhartmann/Projects/manager-ui/client/node_modules/testcafe/src/compiler/test-file/api-based.js:134:35)
    at compile (/Users/janhartmann/Projects/manager-ui/client/node_modules/testcafe/src/compiler/index.js:50:42)

Type "testcafe -h" for help.
```

Line 50 of `@types/mapbox-gl/index.d.ts` is the following (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mapbox-gl/index.d.ts#L50):

```
type Expression = [ExpressionName, ...any[]]
```

I have tried adding `skipLibCheck: true` to my `tsconfig.json` and the compile error still exists.

I am currently running with:

```
"testcafe": "^0.23.3",
"testcafe-react-selectors": "^3.0.2",
```

I have tried to upgrade to the newest alpha of v1.0.0 and the error still exists. 

Using TypeScript Version 3.2.1

Any help appreciated.

**Comment by janhartmann** [comment]
Manually removing `...any[]` from the `type Expression = ....` makes the test run again.

**Comment by miherlosev** [comment]
TestCafe uses own TypeScript configuration for test compilation. There is an enhancement for allowing to specify custom typescript compilation options - https://github.com/DevExpress/testcafe/issues/1845. Please track this issue to be aware of our progress.
 
There is one more workaround: you can add the `// @ts-ignore` comment for all rows that produce the error.

**Comment by janhartmann** [comment]
Okay, I am not able to use `// @ts-ignore` as this error is spawning from an external library type definitions.

**Comment by janhartmann** [comment]
Also, I am unaware on why Testcafe can not compile this single file? It is TypeScript, no need for custom configuration to compile that.

**Comment by janhartmann** [comment]
Maybe we can consider updating Testcafe TypeScript version to 3.X?

**Comment by janhartmann** [comment]
Would Testcafe be able to upgrade TypeScript to 3?

**Comment by miherlosev** [comment]
Could you please clarify why you want to upgrade the TypeScript version to 3.x?

**Comment by janhartmann** [comment]
Hi @miherlosev 

Some of the types I am using is using the `...any[]` syntax, which is only supported in TypeScript 3.X.

The `...any[]` is supposed to stand for "any number of elements of type any" in this tuple. See also https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#rest-elements-in-tuple-types

**Comment by miherlosev** [comment]
OK, I understand you. I will mark this issue as a suggestion - `Upgrage embedded TypeScript version to 3.x`.

**Comment by janhartmann** [comment]
Great, thank you! :-)

**Comment by infctr** [comment]
I used yarn's `resolutions` field to make testcafe use project's typescript version

```json
  "resolutions": {
    "**/typescript": "3.2.2"
  }
```

https://yarnpkg.com/lang/en/docs/selective-version-resolutions/

**Comment by janhartmann** [comment]
Great information @infctr, I will try that. Thank you.
