### ISSUE TITLE
Incorrect progress bar filling while uploading a file through non-existing element

### ISSUE THREAD

**Issue by georgiy-abbasov** [DevExpress/testcafe#341]
When we try to upload a file using a non-existent element, the progress bar doesn’t fill up while waiting for the element to appear.
[Screencast](http://screencast.com/t/MjQvIFzo)

**Comment by georgiy-abbasov** [comment]
After some research it was found out, that css on test pages can extend testcafe-client-ui properties, so, it was a problem with the test page.

**Comment by inikulin** [comment]
> After some research it was found out, that css on test pages can extend testcafe-client-ui properties

It's bug in our stylesheets then

**Comment by AlexanderMoskovkin** [comment]
@inikulin the issue reproduced if add the following style rule on the page:
```css
div { float: left }
```
We can fix it but it looks unreal. We can create a lot of such cases:
```css
* { visibility: hidden }
div { width: 0 !important }
```
etc..

**Comment by inikulin** [comment]
I don't get it. We have a generic reset rule. Why we can't add
```css
float: none;
```
to it?

**Comment by AlexanderMoskovkin** [comment]
we can

**Comment by inikulin** [comment]
> we can

awesome :smile:
