### ISSUE TITLE
uncaughtErrorOnPage while executing a test scenario

### ISSUE THREAD

**Issue by betic0** [DevExpress/testcafe#3414]
### What is your Test Scenario?

Console error is shown when running a test for a project which is using knockout.js. The error is reproducible with ^0.23.0 and it seems to be working fine with 0.22.0 and lower.

The error happens when trying to perform a click in an element found by class.

I've upgraded to 1.0.0 and the behavior it is the same.
 
### What is the Current behavior?

`errStack: 'Error: Cannot read property \'__ko__1549557152997\' of undefined\n    at Function.t._error (http://localhost:1338/hammerhead.js:2:10524)\n    at value (http://localhost:1338/hammerhead.js:2:11948)\n    at r
(https://{URL_IN_TEST}/bundles/knockout?v=cz_cX9LVCpl4qU19D8Gp_2IOlBp5WMGGNgPtO2NcySk1:2:10025)\n    at Object.get (https://{URL_IN_TEST}/bundles/knockout?v=cz_cX9LVCpl4qU19D8Gp_2IOlBp5WMGGNgPtO2NcySk1:2:10220)\n    at t (https://{URL_IN_TEST}/bundles/knockout?v=cz_cX9LVCpl4qU19D8Gp_2IOlBp5WMGGNgPtO2NcySk1:2:10555)\n    at r (https://{URL_IN_TEST}/bundles/knockout?v=cz_cX9LVCpl4qU19D8Gp_2IOlBp5WMGGNgPtO2NcySk1:2:10628)\n    at Object.ba (https://{URL_IN_TEST}/bundles/knockout?v=cz_cX9LVCpl4qU19D8Gp_2IOlBp5WMGGNgPtO2NcySk1:2:11210)\n    at Object.t (https://{URL_IN_TEST}/bundles/app?v=jj4reTGvkoHuWbqfBFyF9bppo8HFHZauBj29-uQy6BE1:2:151881)\n    at c (https://{URL_IN_TEST}/bundles/jquery?v=aUkXT16ly7mMTtXOYpZjW3KYLC7Sd4qFwQTuRNPRwvc1:2:41828)\n    at Object.fireWith [as resolveWith] (https://{URL_IN_TEST}/bundles/jquery?v=aUkXT16ly7mMTtXOYpZjW3KYLC7Sd4qFwQTuRNPRwvc1:2:42593)'`
 
### What is the Expected behavior?

 No error shown and perform the action requested (A click in an element in this case)

 
### Your Environment details:
 
* testcafe version: 0.23.0 - 1.0.0                 
* node.js version:  8.11.3                  
* platform and version: Windows 10

**Comment by AndreyBelym** [comment]
Thank you for your report. I've tried to reproduce the problem with the [Click Counter Knockout example](), but the following test passes with no errors on my machine:
```js
import { Selector } from 'testcafe';

fixture`knockout`.page`http://jsfiddle.net/rniemeyer/3Lqsx/`;

test(`knockout`, t => t
    .switchToIframe('iframe[name="result"]')
    .click('button')
    .expect(Selector('body > div > div:nth-child(1) > span').textContent).eql('1')
);
```

Could you please provide an example with a page and a test that can be used to reproduce the problem?

Also you can try to run TestCafe with the [--skip-js-errors](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors) option to supress uncaught JS exceptions in a browser during a test session.

**Comment by betic0** [comment]
Hi Andrey,

Thanks a lot for your feedback.

I've tried using the --skip-js-errors parameter in the testcafe runner config and it seems works fine now. I've upgraded to 1.0.0 and it's running fine using the javascript skipping errors.

If you still need the information to fix anything you consider, please let me know and I provide whatever it's possible from my side.

Thanks!

**Comment by miherlosev** [comment]
Hi @betic0
 
I am happy to hear that the problem is resolved. Also, we've improved the error message for this case - https://github.com/DevExpress/testcafe/commit/9dda31e63b376e67f70cc7b686b9b3b92a32b60c.
