### ISSUE TITLE
videoOptions option is ignored

### ISSUE THREAD

**Issue by ampc** [DevExpress/testcafe#3415]
### What is your Test Scenario?
Run test with ` "testcafe -c 2 chrome tests/fixtures/**/*.spec.ts --env=pre --selector-timeout 10000 "`
Save video capture to the path pattern provided in `.testcaferc.json` 
### What is the Current behavior?
`videoOptions` option from the configuration file is ignored 
### What is the Expected behavior?
Save video capture to the path pattern provided in `.testcaferc.json` 
### What is your web application and your TestCafe test code?

<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from 'testcafe';

fixture`Getting Started`.page`http://devexpress.github.io/testcafe/example`;

test('My first test', async (t) => {
  await t.typeText('#developer-name', 'John Smith').click('#submit-button');
});

```
```json

{
  "videoPath": "reports/screen-captures",
  "videoOptions": {
    "singleFile": false,
    "failedOnly": false,
    "pathPattern": "${FIXTURE}/${TEST}/${USERAGENT}/${FILE_INDEX}.mp4"
  }
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```
npm run test                                                                                                                                               

> e2e_smart@1.0.0 test /X/e2e_smart
> testcafe -c 2 chrome tests/fixtures/**/*.spec.ts --env=pre --selector-timeout 10000 

The "videoOptions" option from the configuration file will be ignored.
 Running tests in:
 - Chrome 71.0.3578 / Linux 0.0.0

 Getting Started
 ✓ My first test
```
</details>

<details>

### Steps to Reproduce:

1. Run test with ` "testcafe -c 2 chrome tests/fixtures/**/*.spec.ts --env=pre --selector-timeout 10000 "`
2. Video saved in different folder
 
![image](https://user-images.githubusercontent.com/284907/52435196-1f386380-2b09-11e9-8ccb-afa6377c6ab4.png)

### Your Environment details:
 
* testcafe version:                   1.0.0
* node.js version:                    v10.15.0
* command-line arguments: testcafe -c 2 chrome tests/fixtures/**/*.spec.ts --env=pre --selector-timeout 10000
* browser name and version: Chrome 71
* platform and version:          Linux

**Comment by AndreyBelym** [comment]
Thank you for your report. I've found the cause of the problem and prepared a fix in PR #3420. I will post a message in this thread when we release a build with the fix.
