### ISSUE TITLE
Type inference for maps inside generic functions

### ISSUE THREAD

**Issue by domoritz** [DevExpress/testcafe#3416]
### What is your Test Scenario?

I'd like type inference inside generic functions to infer precise types for elements of maps. 

https://www.typescriptlang.org/play/#src=type%20Names%20%3D%20'foo'%20%7C%20'bar'%3B%0D%0A%0D%0Afunction%20func%3CT%20extends%20string%3E(arg%3A%20T)%20%7B%0D%0A%20%20const%20a%3A%20%7B%20%5Bkey%20in%20T%5D%3F%3A%20number%20%7D%20%3D%20%7B%7D%3B%0D%0A%20%20const%20val%20%3D%20a%5Barg%5D%3B%0D%0A%0D%0A%20%20%2F%2F%20I'm%20expecting%20%60val%60%60%20to%20be%20of%20type%20number%20here%0D%0A%20%20type%20ShouldBeNumber%20%3D%20typeof%20val%3B%0D%0A%0D%0A%20%20return%20val%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20%60val%60%60%20is%20number%20here%0D%0Aconst%20val%20%3D%20func%3CNames%3E('foo')%3B%0D%0Atype%20IsNumber%20%3D%20typeof%20val%3B%0D%0A

### What are you suggesting?

In the screenshot below, you can see that TS does not infer that `val` is a `number`. I'm proposing to improve the type inference so that the types will be inferred correctly. 

<img width="499" alt="screen shot 2019-02-07 at 12 13 29" src="https://user-images.githubusercontent.com/589034/52439988-cef1df00-2ad1-11e9-98a1-fa7256e23eba.png">

### Additional context

This could be part of https://github.com/DevExpress/testcafe/issues/1529 but I'm not sure. Please close this issue if it is.

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. However, it looks like a feature of the TypeScript compiler. Please create an issue with your suggestion in the [Microsoft/TypeScript](https://github.com/Microsoft/TypeScript) repository.

**Comment by domoritz** [comment]
I have no idea how I accidentally filed this here... Sorry about that.
