### ISSUE TITLE
[PathPattern] Allow pathPatterns to be used with reporter path in config / CLI

### ISSUE THREAD

**Issue by Niceplace** [DevExpress/testcafe#3417]
### What is your Test Scenario?
I'd like to be able to use the same patterns to define my paths where reporters output to, I like this feature a lot with Screenshots and I think it would be nice to be able to organise reports with the available variables used in screenshots/video patterns (the browser name)

### What are you suggesting?
Use the already implemented PathPattern: https://github.com/DevExpress/testcafe/blob/master/src/utils/path-pattern.js to manage the filename of the report(s) depending on the value passed either as a CLI arg or in the config file.

**Comment by AndreyBelym** [comment]
Thank you for your suggestion. I will discuss with other team members if we can implement this feature.
