### ISSUE TITLE
Console.log in webworker is not available via t.getBrowserConsoleMessages()

### ISSUE THREAD

**Issue by pbiggar** [DevExpress/testcafe#3418]
### What is your Test Scenario?

I am using webworkers, and I'd like to see the output of `console.log` from the worker, via `t.getBrowserConsoleMessages()`.

### What is the Current behavior?

Currently, messages sent to the console logs in the web worker are not available in `t.getBrowserConsoleMessages()`. My understanding is that many objects are proxied to provide testcafe functionality - we previously had an [issue](https://github.com/DevExpress/testcafe-hammerhead/issues/1914
) where `fetch` in a web worker was not proxied, so I'm guessing the problem is that the `console` object has not been proxied in web workers either.

### What is the Expected behavior?

Messages written to `console.log` in a web worker should be available in `t.getBrowserConsoleMessages()`
 
### What is your web application and your TestCafe test code?

This should be enough to trigger it:

```js
var code = "console.log('test');";
var workerURL = window.URL.createObjectURL(new Blob([code]));
var worker = new Worker(workerURL);
```

### Steps to Reproduce:

1. Run the code above
2. Run `t.getBrowserConsoleMessages()` and notice that "test" does not appear.
 
### Your Environment details:
 
* testcafe version:                   1.0.0
* node.js version:                    11.9.0
* command-line arguments:  testcafe chrome tests.js
* browser name and version: Chrome 72
* platform and version:          macOS 10.14
* other:                                    n/a

**Comment by AndreyBelym** [comment]
Thank you for your feedback.

Yes, TestCafe doesn't support intercepting console messages from worker scripts. If it is possible, we will try to implement it in future releases.
