### ISSUE TITLE
ES6 Imports in node modules folders are causing syntax errors

### ISSUE THREAD

**Issue by bdwain** [DevExpress/testcafe#3424]
I am noticing that testcafe seems to skip transpiling files in the node modules folder, but this can cause problems if you ran your e2e library through a bundler like [rollup](https://rollupjs.org/guide/en), which leaves import statements in the code.

In my example, one of my libraries exposes helpers in a file like this

```js
import { Selector, t, ClientFunction } from 'testcafe';
//....

export function helper1(){
 //....
}
```

This gives an error though

```
Cannot prepare tests due to an error.

(function (exports, require, module, __filename, __dirname) { import { Selector, t, ClientFunction } from 'testcafe';

```SyntaxError: Unexpected token {```
```

My code is organized in a monorepo (using yarn workspaces), and I don't see this error for projects whose build directories are symlinked in the root directory like normal, only when in the actual node modules folder of the project I am working in. I am guessing it has something to do with [this filter](https://github.com/DevExpress/testcafe/blob/8a0929cc4529ed1e7b96f82172adb9849bd38af9/src/live/file-watcher/modules-graph.js#L22), though I'm not positive.

I can try to get a reproduction up soon. But I figured I'd post this now to start thinking about it.

### Your Environment details:
 
* testcafe version: 1.0.0
* node.js version: 10.14.2
* command-line arguments:  I use the node runner api with no special arguments.
* browser name and version: chrome 71
* platform and version: OS X High Sierra

**Comment by AlexKamaev** [comment]
TestCafe should not transpile any external library by design. If TestCafe transpiles all files from the `node_modules` folder, it will cause performance issues, since the `node_modules` folder can contain an enormous number of modules. A module that is expected to be external should be delivered to npm already compiled to prevent any incompatibilities.
The `filter` method is used only when the Live mode is enabled, so it cannot be the cause of the issue. An appropriate decision would be implementing your module without ES6 syntax or using the `babel` compiler in your library.

**Comment by bdwain** [comment]
Hi @AlexKamaev please reconsider this for a few reasons. 

1. Rollup is a popular tool for bundling libraries and it intentionally uses es6 imports in its final bundle. There’s no need to run everything in node modules through Babel, which is the slow part. But webpack will process the imports correctly if you allow it to, even without running Babel on the file. My app uses libraries built like
This without running Babel on node modules 

2. The current behavior is inconsistent. Like I said above, I am in a monorepo using yarn workspaces, and things work fine when my libraries are symlinked at the root node modules folder like normal. Things only break if I try to use a specific version of a library in a subprojects

**Comment by bdwain** [comment]
Hi @AlexKamaev please reconsider this for a few reasons. 

1. Rollup is a popular tool for bundling libraries and it intentionally uses es6 imports in its final bundle, even though it runs the code through Babel and transpires all other aspects of it. The only es6 thing is the imports and exports. There’s no need to run everything in node modules through Babel, which is the slow part. But webpack will process the imports correctly if you allow it to, even without running Babel on the library. My app uses libraries built like
This without running Babel on node modules, because it is slower to do that. 

2. The current behavior is inconsistent. Like I said above, I am in a monorepo using yarn workspaces, and things work fine when my libraries are symlinked at the root node modules folder like normal. Things only break if I try to use a specific version of a library in a subproject’s local node modules folder. But in a standard build, nothing is in WORKING_DIR/node_modules anyway. It’s all in the top level node modules folder (sometimes with a symlink), so it seems to be transpiled anyway. 

3. If I don’t control a library that is exported and built with rollup, I have no good way of using it in my tests. 

4. When I used to build my library with commonjs modules, requesthooks would break with some testcafe error. I don’t remember the error. They stopped breaking when I switched the e2e file to Use es6 exports. 

I think if you avoid running the node modules through Babel but still allow them to be processed by webpack, things will work without a performance penalty. If nothing else, this behavior could be exposed only if an option was enabled in testcafe. That would allow people to opt in. But I don’t think there’s much harm in it either way.

**Comment by AlexKamaev** [comment]
I discussed this issue with the team and we decided not to include this feature into our list for the near future. As a workaround, I would take a look at some custom module loader. For example, I recommend the `esm` module. Please refer to the following links to get details:
https://github.com/standard-things/esm
https://medium.com/web-on-the-edge/tomorrows-es-modules-today-c53d29ac448c
I've checked it with the scenario similar to yours and it works as expected.

**Comment by bdwain** [comment]
Hi @AlexKamaev. If you don't mind me asking, why does the team not think it's important? I think I laid out some good points on why it's a problem.

Thank you for the ESM library suggestion. I will try that. But if it's an easy fix anyway, why does testcafe not just include it automatically? That would solve the problem for everyone at once rather than have each individual person have to do it in their own project.

**Comment by bdwain** [comment]
Hi @AlexKamaev. I tried esm and I was only able to get it working by doing something like this

```js
node -r esm node_modules/.bin/my-e2e-script.js
```

I have my code organized in a monorepo, and a lot of the scripts are in a shared package to make it easier to reuse. My package script runs uses the testcafe node api to run my tests.

The blog post you linked mentions that the CLI for a bunch of tools expose some sort of register (-r) option, which you can use the provide the esm loader. Does testcafe have anything like that? Or if not, do you have a recommendation of how esm would work with testcafe?

Thanks

**Comment by bdwain** [comment]
Sorry it turns out I think I just had a bug in my configuration. I was able to get rid of `esm` just by changing the package.json for my e2e helper library to use a `module` field instead of the `main` field. Sorry to have wasted your time. I appreciate the help.

**Comment by AndreyBelym** [comment]
It's great to hear that you've resolved the issue. Feel free to contact us with any questions and suggestions. Thank you for using TestCafe!
