### ISSUE TITLE
Config file - allow to specify different config files

### ISSUE THREAD

**Issue by AlexSkorkin** [DevExpress/testcafe#3428]
### What is your Test Scenario?

I have different environments where I'd like to specify alternative config files.

### What are you suggesting?

Allow using various config files, not only one at the root level.

### What alternatives have you considered?

None

**Comment by Waterstraal** [comment]
I think the way Cypress does this is really well thought out, maybe it can serve as inspiration for Testcafé: 

https://docs.cypress.io/guides/guides/environment-variables.html#Setting

**Comment by miherlosev** [comment]
Thank you for your suggestion. We will research it and consider implementing it in the future.

**Comment by hitautodestruct** [comment]
I would also be happy to see this feature added for two reasons:
1. I have a project the is nested inside of a larger one and would like to have all the configuration files in one place.

2. I would like to have different configurations for when I debug tests and when I run them using the CI.

I think you could simply add an option to specify where the configuration file exists using a cli command such as:
```
testcafe --config ./config-folder/config.json
```

Therefore allowing the user to choose where he puts the file and what to call it.

In your package.json you would specify different scripts with different configs:
```
// package.json
{
  "scripts": {
    "test:production": "testcafe --config ./config-folder/prod.json",
    "test:debug": "testcafe --config ./config-folder/debug.json"
  }
}
```

**Comment by chge** [comment]
The [test metadata](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#specifying-testing-metadata) along with the [--test-meta](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--test-meta-keyvaluekey2value2) command line flag could be potentially used to distinguish between environments.

But support for separate configs is a really good feature to have.

**Comment by Farfurix** [comment]
https://github.com/DevExpress/testcafe/issues/4824

**Comment by gatorjuice** [comment]
Hi everyone and @miherlosev . I found this issue while digging around looking for a way to use different config files for things like local env, CI on jenkins, QA servers etc. Right now we have pretty long CLI script commands in our package.json and it's not ideal, but I would love to have this ability for all the reasons mentioned above. I'm just curious if this feature is still on the way as activity here has died down for a while.

**Comment by AlexanderMoiseev** [comment]
Thank you for bringing this to our attention. This feature is on our TO-DO list. I can't, however, provide you with a precise date as to when it may be introduced. You are welcome to submit your PR with the implementation, and we will review it.

**Comment by sveyret** [comment]
Hi @AlexanderMoiseev. As seen with @Farfurix in issue #4824, I can create a PR using [confinode](https://www.npmjs.com/package/confinode), but this solution needs to be discussed in the team before I start. Please tell me if you want me to work on it.

**Comment by Dmitry-Ostashev** [comment]
Thank you for your interest in this feature. We are going to implement it without using third-party libraries.

**Comment by alanjohnson** [comment]
Same as everyone else, would like to see this feature dded.  in my case i'm working in a monorepo, with several packages inside it.  The goal would be to have separate config files for each package based on their needs.  and be able to target which package to run e2e tests for.

**Comment by becciwatson** [comment]
Hi  @sveyret, this issue has been waiting for two years.   Agile is about getting it done with an Minimal Viable Product (MVP), seeing how/if it is used and then improving it.  My tester would be intersted in collorating with you to get it up and working using using [confinode](url) as you suggest.  Then let's see how many people use it, because something is better than nothing.  Confinode has over 4,000 weekly downloads and is MIT licensed.  Given this, we don't care if it has an external repo when that repo is MIT licensed.

**Comment by Chris-Greaves** [comment]
Hello,

Similar to some of the other use cases mentioned, I want the ability to have two config files, one for pipelines and one for local development. There is an existing workaround for this problem by having a step in the pipeline to replace the contents of `.testcaferc.json` with the contents of `pipeline.testcaferc.json`. 

Regardless of this, I am looking at how this can be implemented (without third-party libs) and have started some development on it today. Currently my solution involves changing the `createTestCafe` and `getConfiguration` methods by adding a parameter on each for the config filepath. This should work but is a breaking change that I doubt the devs will want to implement. That being said, I will implement it as such to begin with so we can see it working and start the conversation going.

**Comment by becciwatson** [comment]
Hi Christopher, that sounds exciting.

Let me know if you want a beta customer.

Regards,
Becci


(Probably brief as sent on the run ... aka: Sent from my iPhone)

On 10 Mar 2021, at 4:05 am, Christopher Greaves <notifications@github.com> wrote:

﻿

Hello,

Similar to some of the other use cases mentioned, I want the ability to have two config files, one for pipelines and one for local development. There is an existing workaround for this problem by having a step in the pipeline to replace the contents of .testcaferc.json with the contents of pipeline.testcaferc.json.

Regardless of this, I am looking at how this can be implemented (without third-party libs) and have started some development on it today. Currently my solution involves changing the createTestCafe and getConfiguration methods by adding a parameter on each for the config filepath. This should work but is a breaking change that I doubt the devs will want to implement. That being said, I will implement it as such to begin with so we can see it working and start the conversation going.

**Comment by Chris-Greaves** [comment]
I have submitted a PR to get this added. I still need to update the docs, but this is a good start to getting this issue resolved.

**Comment by viktoria2506** [comment]
Thank you for contributing to TestCafe.

**Comment by Chris-Greaves** [comment]
Hello all,

My PR #6035 has been merged and is set to be included in the next Testcafe release (Apparently in the next few days). I believe this should cover most if not all the use cases mentioned here so this issue can probably be closed, if your use case is still needed and isn't solved I would suggest raising a new issue.

Thank you very much @miherlosev and @DIRECTcut for your support and the rest of the team working on Testcafe ❤️

**Comment by haideralii** [comment]
@Chris-Greaves How I can use your PR to set different URLs for staging, dev, prod environments?

**Comment by aleks-pro** [comment]
@haideralii, the changes are available in the latest TestCafe version - v1.14.0.

**Comment by Chris-Greaves** [comment]
@haideralii The code changes are in, but possibly the feature that was added wasn't explained correctly. 

These config files are used to configure testcafe, not provide configuration to be used within the tests themselves. It is best explained in the [docs](https://devexpress.github.io/testcafe/documentation/reference/configuration-file.html).

I would look at any existing issues asking for variable files to be passed in as params, or if none exist raise a new issue. I would also search of anyone that has solved this problem already, Node.js is pretty powerful so I'm sure there are workarounds.

Hope this explains things.

p.s. @aleks-pro If you think my PR has solved this issue, I'm guessing you can close it.

**Comment by rehael** [comment]
> search of anyone that has solved this problem already, Node.js is pretty powerful so I'm sure there are workarounds

For anyone stumbling upon this and having trouble of making the tests suites configurable – shameless plug, but _UNLICENSED_, so… ;) https://github.com/rehael/testcafe-config-example – minimal working example of making test suites configurable with variables specified in external file driven by environmental variable. There are many other ways one can do it, but if it can help anyone – enjoy.

Basically, it's solution based on these ideas:

- https://devexpress.github.io/testcafe/documentation/recipes/best-practices/create-helpers.html
- https://devexpress.github.io/testcafe/documentation/recipes/best-practices/create-data-driven-tests.html
- https://devexpress.github.io/testcafe/documentation/recipes/configuration/access-environment-variables-in-tests.html

Dear TestCafé developers – if you'd like to include this example somewhere (or even copy-paste pieces of it into docs or testcafe-examples) – it'd be cool. It's unlicensed, I don't need attribution.

**Comment by VasilyStrelyaev** [comment]
Thank you for sharing your code! We will consider adding your findings to our documentation or example repository.

As this topic doesn't directly relate to the initial discussion in this thread, would you please create a new issue and describe your suggestion in detail?

**Comment by AndreyBelym** [comment]
The original proposal is implemented, so I close this issue. If you are interested in using configuration files to provide test environments, please track https://github.com/DevExpress/testcafe/issues/6143 and https://github.com/DevExpress/testcafe/issues/3593.
