### ISSUE TITLE
TestCafe hangs when running with Node LTS (v10.15.1)

### ISSUE THREAD

**Issue by sijosyn** [DevExpress/testcafe#3436]
### What is your Test Scenario?

Download the provided test repo and execute the tests with **node v10.15.1** (LTS) or or v10.14.2
 
### What is the Current behavior?

TestCafe hangs when trying to execute tests and won't proceed to next tests. TestCafe will sometimes automatically restart & retry the test but most of the time it stays stuck during the execution. This is 100% reproducible all the time. Note: There is also another related issue where page styles/CSS won't load when running with Node LTS - https://github.com/DevExpress/testcafe-hammerhead/issues/1920

### What is the Expected behavior?

TestCafe should run all tests without any issues.
 
### What is your web application and your TestCafe test code?

Download this repo - https://github.com/sijosyn/testcafe-syntests and run the test suite.
 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

Please read the README provided in the repo - https://github.com/sijosyn/testcafe-syntests .
Run the full test suite.

 
### Your Environment details:
 
* testcafe version:                    1.0.0
* node.js version:                     v10.15.1 or  v10.14.2
* command-line arguments:   * npm run aperture   or   testcafe chrome desktop -e
* browser name and version:  Chrome 72
* platform and version:           macOS 10.14
* other:

**Comment by Farfurix** [comment]
@sijosyn,

I've reproduced this issue here: https://github.com/DevExpress/testcafe-hammerhead/issues/1920#issuecomment-463155015.
Our team will research it and check for a suitable solution.
