### ISSUE TITLE
npm audit finds 1 vulnerability in lodash from testcafe-hammerhead

### ISSUE THREAD

**Issue by igorn-beardguy** [DevExpress/testcafe#3442]
Running `npm audit` for a project with testcafe in the dependencies brings up vulnerability in testcafe-hammerhead which located in lodash v.4.17.10.

The testcafe-hammerhead was [updated to use newer lodash](https://github.com/DevExpress/testcafe-hammerhead/commit/0b4edea3bb61fa2117508438c3c898004240959f)

But testcafe project still uses the old testcafe-hammerhead version 14.4.12

### What is your Test Scenario?
npm audit 

### What is the Current behavior?
found 1 moderate severity vulnerability
 
### What is the Expected behavior?
npm audit finds 0 vulnerabilities
 
### What is your web application and your TestCafe test code?
<details>
<summary>package.json:</summary>

 
```json
{
  "devDependencies": {
    "testcafe": "^1.0.0"
  }
}
```
</details>

<details>
<summary>result of npm audit</summary>
found 1 moderate severity vulnerability

title | details
------------ | -------------
Moderate | Prototype Pollution
Package | lodash
Dependency of | testcafe [dev]
Path | testcafe > testcafe-hammerhead > lodash
More info |  [https://npmjs.com/advisories/782](https://npmjs.com/advisories/782)
</details>

### Steps to Reproduce:

1. Create a directory and open it in terminal
2. Create package.json with testcafe in dependency
3. Execute "npm i && npm audit"
4. See the message about vulnerability
 
### Your Environment details:
 
* testcafe version:                   1.0.0
* node.js version:                    v10.9.0
* command-line arguments:  "npm i && npm audit"
* platform and version:          "macOS 10.14.2"
* other:                                    npm version: 6.7.0

**Comment by AndreyBelym** [comment]
Thank you for contacting us. We will update `testcafe-hammerhead` and release a new TestCafe version today.
