### ISSUE TITLE
Use drag() method and then use doubleClick() method to cause the element to disappear.

### ISSUE THREAD

**Issue by JustinRong** [DevExpress/testcafe#3444]
I want to drag the element on the left to the panel on the right, then double-click on the element, but when I want to double-click on the element, the element disappears.

I debug found that when the program runs to doubleClick method, the element disappears.

here is my code:
```
.switchToIframe(Selector('iframe[name="overview"]'))
            //select datasets
            .drag('div#palette_node_datasets', 240, -50, {
                offsetX: -8,
                offsetY: -8,
                speed: 0.08          
            })
            .drag('div#palette_node_datasets', 480, -100, {offsetX: -8, offsetY: -9})
            .expect(Selector('g.innerCanvas > g:nth-child(2)')).ok()
            .doubleClick('g.innerCanvas > g:nth-child(2)')
```

**Comment by Farfurix** [comment]
@JustinRong,

Unfortunately, this information is not sufficient to find the cause of the issue. There can be many causes, and, therefore, we can't give you any advice without analyzing your page or code.

Could you please reproduce the issue on some public site and share its URL? Or could you prepare a sample project which demonstrates the issue?

**Comment by JustinRong** [comment]
Sorry, I found the problem. After dragging the element, the selector could not find the element.

thanks all
