### ISSUE TITLE
Speed up tests with video recording in quarantine mode

### ISSUE THREAD

**Issue by petrjanu** [DevExpress/testcafe#3446]
### What is your Test Scenario?
Video recording seems to be running for all 3 test in quarantine + failed only mode and slowing down tests.

### What are you suggesting?
There may be an option which will control video recording in quarantine mode. This means video capture will be started for 2nd or 3rd attemp only when first attemp fails. This should save resources and make tests faster, but user can still get video of failed test.

**Comment by LavrovArtem** [comment]
Thank you for sharing your idea with us. We will discuss it and consider implementing it in one of our future product updates.
