### ISSUE TITLE
switchToMainWindow() doesnt work if something was clicked in iframe before

### ISSUE THREAD

**Issue by MilippFeier** [DevExpress/testcafe#3447]
### What is your Test Scenario?
I'm clicking around in my webapp. 
 
### What is the Current behavior?
After several steps, i need to click on an element in an iframe. Switching to that iframe works as expected. If i switch back to main window immediately, this works fine, too. 
BUT, if i perform a click in that iframe and then try to switch back to the main window, the tear down (afterEach) starts to be performed (in that particular iframe). 
Hence, i guess switchBackToMainWindow is broken ?
 
### What is the Expected behavior?
- Switch to Iframe
- Perform click
- Switch to main window
- perform click
 
### What is your web application and your TestCafe test code?

I managed to find an example site that represents exactly our problem.
We're testing a confluence page. The plan is to click on an image (that's in an iframe) and then perform a click on the opened context menu . These buttons (of the context menu), however, are on the main window. 

First i click on the image (blue marked). This image is inside the iframe. So, i switch to iframe and click the image.

![image](https://user-images.githubusercontent.com/29304260/52858203-cb8dd180-3129-11e9-82eb-25f3f0d123c1.png)

The result is an opened context menu with two buttons (edit/remove). The two buttons are on the main window. So in order to click one of them, we need to switch back to the main window first. 

![image](https://user-images.githubusercontent.com/29304260/52858295-04c64180-312a-11e9-80bf-fe2d18903ebd.png)

The test will jump into afterEach after having performed the click on the iframe image.

```
fixture.only("iframeBugDemo")
    .page("https://confluence.demo.goedit.io/login.action?os_destination=%2Findex.action&permissionViolation=true&os_username=goedit&os_password=thatssimple")
    .beforeEach(async (t) => {
        await t.setTestSpeed(0.8).resizeWindow(1366, 768)
    })
    .afterEach(async (t) => {
        await t.navigateTo("www.afterEachisStarted.com")
    });
test("DemoTest", async (t: TestController) => {
    await t
        .debug()
        .click(Selector("#main-content > div > div:nth-child(2) > div > div > p > strong > a > span > img"))
       
        // switching back and forth, no problem if nothing is clicked in the iframe:
        .switchToIframe("#wysiwygTextarea_ifr")
        .switchToMainWindow()
        .switchToIframe("#wysiwygTextarea_ifr")

        // perform click in iframe => run into afterEach:
        .click(Selector("#tinymce > div > div:nth-child(3) > div > div > p:nth-child(4) > img"))
        .switchToMainWindow()  // < this wont be executed, will jump into afterEach
        .click(Selector("#property-panel > div.aui-property-panel > div > a.aui-button.macro-placeholder-property-panel-remove-button.last > span.panel-button-text"))
});
```

### Steps to Reproduce:
Visit https://confluence.demo.goedit.io/pages/copypage.action?idOfPageToCopy=1507362&spaceKey=GOEDT

If you need to log in, use "goedit" with "thatssimple" as PW.

The sample test should log in automatically and reproduce the problem.

### Your Environment details:
 
* testcafe version:                   1.0.0
* node.js version:                    10.14.1
* command-line arguments:  "testcafe chrome ./e2e/tests -S -s ./e2e/screenshots",
* browser name and version:  71.0.3578.98 (Offizieller Build) (64-Bit) (cohort: Stable)
* platform and version:          Windows 7

**Comment by LavrovArtem** [comment]
Thank you for providing this information. However, it is not sufficient to find the cause of the issue and provide a solution. There can be different causes and without having access to your page or code, I cannot give you any advice. If possible, please provide us with access to your web site, so we can diagnose the issue.

**Comment by MilippFeier** [comment]
Thanks for the fast response. I will try to find a public page where this occurs and post it here.

**Comment by MilippFeier** [comment]
I found an example site that represents exactly our problem. Updated the ticket.

**Comment by LavrovArtem** [comment]
Thank you for providing additional information.
I still cannot reproduce this issue. I've recorded a video to show my steps. Would you please check out the issue on another machine to see if it is reproducible there? Thank you in advance.
[video.zip](https://github.com/DevExpress/testcafe/files/2888407/video.zip)

**Comment by MilippFeier** [comment]
Hi, thanks for your effort. 
I tested it again with another browser (firefox) instead of chrome. I get the following results:

Firefox:
- Works if not in debug mode
- Does not work if in debug mode and clicking step to step

Chrome:
- Never works. 

I will just use firefox in the future ;-)

Thank you again for your support.
