### ISSUE TITLE
Node/TestCafé stops working on large SPA

### ISSUE THREAD

**Issue by BobLuursema** [DevExpress/testcafe#3459]
### What is the Current behavior?
Node/TestCafé stops working.

The application I am trying to test is a bit slow after logging in, it is a SPA built with GWT and the html file is 3.8 MB. Loading it normally takes about 1 minute before the UI shows up (or about 1:20 when running in TestCafé). At first it was working with TestCafé but after some update to the application Node would crash with an OOM error. I tried digging into this issue with ChromeDevTools for Node and it seems that it has to do with parsing and tokenizer. I then assumed the issue has to do something with Hammerhead needing to rewrite the HTML and apparently needing more memory for this application. To resolve this I increased the max-old-space-size to 6000.

To make sure that TestCafé waits for the UI to completely be available I setup an expect to check for an element. But now the issue is that this assertion never completes nor throws an error. Using some well placed `console.log`s in TestCafé and reading the source code it looks like the assertion should happen every 200ms. But my observation is that after around 40 of those they stop, then continue on for another 10 or so before halting completely. The point at which they halt is in `https://github.com/DevExpress/testcafe/blob/master/src/assertions/executor.js`, first on line 61, then it continues about 15 seconds later, then again on line 61 and after another 40 or so seconds it goes to line 47 and never continues again. Both are `await` calls so I assume that something is going wrong with regards to whatever controls asynchronous calls.

(The Node process while loading the website is basically using all of my CPU and after loading the website in about one minute it drops to 0% CPU).

### What is the Expected behavior?
I would expect the assertion to keep going until the timeout or until success. But I don't know if this qualifies as a bug or if an SPA this size/complexity is not in scope for TestCafé to handle. I would like to know if this is a known limitation of TestCafé or if this would have more to do with the application's design and TestCafé should be able to handle it.
 
### What is your web application and your TestCafe test code?
It is an internal application so unfortunately I cannot share the actual website.

```js
 import { Selector } from 'testcafe'

fixture('test')

test('testnaam', async t => {
    let username = Selector('#userNameInput')
    let password = Selector('#passwordInput')
    let button = Selector('#submitButton')
    let homeUsername = Selector('span.login-menu-name-content')
    await t
        .navigateTo("https://example.com")
        .typeText(username, "admin",)
        .typeText(password, "verysecret")
        .click(button)
        .expect(homeUsername.exists).ok({timeout: 120*1000})
})
```

### Your Environment details:
 
* testcafe version: 1.0.1
* node.js version: 11.9.9
* command-line arguments:  --proxy 10.something:etc --skip-js-errors
* browser name and version: Chrome 72
* platform and version: Windows 10

**Comment by miherlosev** [comment]
@BobLuursema 

According to your description, I see several problems:
* serialization / serialization should not take more than 512 mb
* there is an unknown error that corrupts assertion logic
 
Maybe, some fine-tuning of the TestCafe parameters is necessary, because your application is very large. 
If you provide a simple example to reproduce the issue or provide direct access to your application, I will perform TestCafe fine-tuning and try to find the cause of the problem.

**Comment by BobLuursema** [comment]
I'm trying to pull some strings so that we can white list an IP address for access to the application for a day/week. I'll update the ticket if I can get people to do that.

**Comment by Farfurix** [comment]
Hello, @BobLuursema.

Thank you for the update. We look forward to hearing from you.

**Comment by BobLuursema** [comment]
Hey, we can whitelist an IP address so that you can test the application. It is probably better to communicate the details over email/Slack or something? You can reach me at bob.luursema@nn.nl.

**Comment by AlexKamaev** [comment]
@BobLuursema please provide all required info at support@devexpress.com

**Comment by BobLuursema** [comment]
I send the info a few days ago and I haven't heard anything, did it arrive?

**Comment by miherlosev** [comment]
Yes, we got all necessary information. We deal with this problem. We will inform you when we have any news.

**Comment by AlexKamaev** [comment]
> Yes, we got all necessary information. We deal with this problem. We will inform you when we have any news.

Just a simple remark. We've sent you an email message with our IP to add it to the white list.

**Comment by BobLuursema** [comment]
Yes, I already replied back. The issue has disappeared after a release from our provider, I've asked what changes they made to see if I can figure out what caused it, see the email for a bit more information.

**Comment by Farfurix** [comment]
@BobLuursema,
 
We are happy to hear that the problem is solved. If you have another question related to this issue, feel free to reopen it.
