### ISSUE TITLE
White areas on screenshots and videos when scrolling the page in Chrome / Chromium

### ISSUE THREAD

**Issue by kalabro** [DevExpress/testcafe#3461]
### What is your Test Scenario?
I interact with an element at the bottom of the page (i.e. contact form on http://systemseed.com front page) and if test fails I expect a screenshot to be taken properly.
 
### What is the Current behavior?
Screenshots are either completely white or some areas are white in Chrome / Chromium (see screenshot).

![testcafe-chrome-screenshots](https://user-images.githubusercontent.com/264922/52913467-97ecac00-32cf-11e9-8611-bc70940b71b5.png)

 
### What is the Expected behavior?
Screenshots represent all elements from current viewport.
 
### What is your web application and your TestCafe test code?
```js
import { Selector } from 'testcafe';
fixture.only('Scrolling long pages in Chrome / Chromium and taking screenshots');

test('Take screenshots before / after scroll', async t => {
  // A few reproducible examples.
  const urls = [
    'https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#tests',
    'https://www.mozilla.org',
    'https://systemseed.com'
  ];

  for (let i = 0; i < urls.length; i++) {
    await t.navigateTo(urls[i]);
    await t.takeScreenshot(`site-${i}/before scroll.png`);
    // 5000px is just an example that helps reproduce the bug on the three sites
    // above.
    await t.eval(() => window.scrollBy && window.scrollBy(0, 5000));

    await t.takeScreenshot(`site-${i}/after scroll - 5000.png`);
  }


});
```
 I reproduced the issue on multiple sites:
- https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#tests
- https://www.mozilla.org
- https://systemseed.com

The page should be long enough (5000px+).

### Steps to Reproduce:

1. Run 'Take screenshots before / after scroll' test from the code snippet above in Chrome / Chromium. Browser screen height should be less than 2000px.
2. Review generated screenshots. *Before scroll...* screenshots should look fine. *After scroll...* screenshot should be white or partially white. 

I could reproduce this issue on my mac, in Docker, and in Docker on Circle CI. Details of my own machine are provided below. 
 
### Your Environment details (Docker on Mac):
 
* testcafe version:                   1.0.1
* node.js version:                     v10.14.2 (from `testcafe/testcafe:alpha` docker image)
* command-line arguments:  'chromium --no-sandbox' --screenshots-on-fails --screenshots results
* browser name and version: Chrome 71.0.3578 / Linux 0.0.0 (from `testcafe/testcafe:alpha` docker image)
* platform and version:          Docker for Mac 2.0.0.3
* other:                                    shm_size: 1g
* known workarounds:          Pass SCREEN_HEIGHT=6000 or larger to avoid scrolling

### Your Environment details (MacOS native):
 
* testcafe version:                   1.0.1
* node.js version:                    v10.8.0
* command-line arguments:  chrome --screenshots results
* browser name and version: 72.0.3626 (stable), 74.0.3702.0 (dev)
* platform and version:          MacOS 10.14.3 13,3-inch (2560 x 1600)
* other:                                   When I watch tests execution, I can see a quick white blink of the area being captured:
![blinking when tacking screenshot after scrolling](https://user-images.githubusercontent.com/264922/52914989-ad69d200-32df-11e9-95eb-f81ec67a792f.gif)

Video recording seems to be affected by this issue too.
The issue is NOT reproducible in Firefox and Safari.

**Comment by AlexKamaev** [comment]
Thanks for such detailed information. The issue looks similar to https://github.com/DevExpress/testcafe/issues/3292
I believe both these issues have the same cause, so I'll mark this one as a duplicate. Please follow our progress in https://github.com/DevExpress/testcafe/issues/3292
