### ISSUE TITLE
Report is not logged to the output xml/json file when the browser disconnects or hangs.

### ISSUE THREAD

**Issue by Muthuvenaktesh** [DevExpress/testcafe#3467]
Whenever the below error occurs, the result of the pervious tests are not written to the output file. The file was created inthe specified path but it was empty.

ERROR The IE 11.0.0 / Windows 7.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.

Type "testcafe -h" for help.
----------------------------------------------------------------------------------------------------------

Testcafe cli command used:

testcafe ie ./root/testcafe/*.js --proxy proxy.company.com:8080 -e -u environment=QA browser=IE  -r xunit:res.xml,json:res.json,spec --selector-timeout 30000 --assertion-timeout 30000

----------------------------------------------------------------------------------------------------------
Testcafe Version:
# testcafe -v
1.0.1

----------------------------------------------------------------------------------------------------------

While trying to read output xml file below error occurs:

Test report file C:\Jenkins\workspace\BPS_QA_IE\res.xml was length 0

----------------------------------------------------------------------------------------------------------

-->

### What is your Test Scenario?

Testing a group of testcafe script file through cli command.
 
### What is the Current behavior?

When the browser disconnets, logs are not written to the report file.
 
### What is the Expected behavior?

Even when the browser disconnets, logs should output to the report file.
 
<details>
<summary>Jenkisn console output:</summary>

####################################### Starting Test Case #####################################################
57:Validate user can select Service down emergency forwarding number to any other number from personal contacts
################################################################################################################
[18-02-2019-11:43:57 PM]  Starting function ==> deleteContact
[18-02-2019-11:44:06 PM]  Contact does not exists :Auto-EmergencyForwarding Replace
[18-02-2019-11:44:06 PM]  Starting function ==> addContactWithMobileNumber
[18-02-2019-11:45:58 PM]  Starting function ==> deleteContact
[18-02-2019-11:46:25 PM]  Contact deleted successfully :Auto-EmergencyForwarding Replace
[18-02-2019-11:46:25 PM]  Success: User can select Service down emergency forwarding number to any other number  from personal contacts
****************************************** End *****************************************************************

[18-02-2019-11:46:25 PM]  Starting function ==> removeNumberFromEmergencyForwarding
ERROR The IE 11.0.0 / Windows 7.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.

Type "testcafe -h" for help.

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.0.1
* node.js version:                   v10.15.0
* command-line arguments:  testcafe ie ./root/testcafe/*.js --proxy proxy.company.com:8080 -e -u environment=QA browser=IE  -r xunit:res.xml,json:res.json,spec --selector-timeout 30000 --assertion-timeout 3000
* browser name and version: Chrome, IE, firefox
* platform and version:          Linux Cent os

**Comment by miherlosev** [comment]
Hi @Muthuvenaktesh

Initially, we don't think about the described case, so we will interpret this issue as an enhancement of our reporting system.

**Comment by Muthuvenaktesh** [comment]
Thanks @miherlosev , Please let me know when the enhancement is available.

**Comment by pschmolke** [comment]
Is there an update? I have a similar problem. The ".. browser disconnected." message sometime appears without context across different tests and fixtures. That is one problem but the following problem is more frustrating for me. The <whatever-file-name>.xml is created but with no content. This results in an interpreter error from the testcafe reporter jenkins plugin which again lets the complete pipeline fail.

**Comment by Artem-Babich** [comment]
Fixed in #7518
The fix is available in v2.4.0 and higher.
