### ISSUE TITLE
Getting the proxy connection error 

### ISSUE THREAD

**Issue by Subhrasini** [DevExpress/testcafe#3468]
I am trying to run my tests from testcafe with the below command:
testcafe "chrome --incognito --disable-web-security -disable-popup-blocking" --proxy www-proxy.us.(mycompanyname).com:80  Suits\Test.js

After logging in to the application , when it clicks on any link ,its getting disconnected with the below error:
This site can’t be reached 
10.191.242.176 refused to connect.
ERR_CONNECTION_REFUSED

But if I restart my laptop and then try the same thing, Its working fine for few times .

Can Anyone help me with the issue ?

**Comment by LavrovArtem** [comment]
Thank you for reaching out to us and submitting this issue. We didn't face this issue previously. It looks like it is related to your machine and your proxy configuration, but not TestCafe. This means that the information you provided is insufficient for me to determine the cause of the issue and find a precise solution. Feel free to reopen this thread if you have a clear reproduction scenario, which we can follow to examine this issue.

**Comment by Subhrasini** [comment]
If its a proxy issue ,it wouldn't have worked one time also . I am able to run the scripts few(two or three) times, once I restart the system . After that , I get this kind of error . 
http://10.177.157.170:52799/HAk20GHRX!f/http://(application)/#/

**Comment by AndreyBelym** [comment]
If restarting your system helps you for some time, I guess your system, antivirus or proxy software can cause the issue. You can try to create a virtual machine image and reproduce the problem in it.
