### ISSUE TITLE
Please add Node 11 testcafe docker image

### ISSUE THREAD

**Issue by jcollum-nike** [DevExpress/testcafe#3472]
I have a large group of tests that I'm trying to run. For some reason they fail after running 8-10 of them when running in Node 8 but run fine (300+) in Node 11. When I run them in `testcafe/testcafe` docker I get the same failure: 

```✗ nr test:prod:docker

> ...

> docker run -v `pwd`/tests:/tests -it testcafe/testcafe  'chromium --no-sandbox,firefox' /tests/**/*.test.js

 Running tests in:
 - Chrome 71.0.3578 / Linux 0.0.0
 - Firefox 62.0.0 / Linux 0.0.0

 Test connection to internet
 ✓ Assert logo is present on google.com

... [runs 4 or 5 tests here]

ERROR The Firefox 62.0.0 / Linux 0.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.
```

I suspect this is because the `testcafe/testcafe` image is running Node 10. Can we get a version published that uses Node 11? 

```
✗ docker run -ti --entrypoint=/bin/sh testcafe/testcafe -s
/ $ node --version
v10.14.2
```

I don't have any more information to offer on the failure -- there was never any meaningful output. It just ran a few tests then died (with the message about the browser disconnecting). It was page-dependent: about 5% of our production pages would load successfully regardless of number of pages loaded. All I can tell you is that problem went away when I bumped up to Node 11 and ran my testcafe tests.

**Comment by AlexKamaev** [comment]
At the moment we do not have plans to create multiple testcafe docker images for different node versions. However, I created a separate [feature request](https://github.com/DevExpress/testcafe/issues/3480).
Please track that ticket and vote for it. We can add it to our plans in the future.
