### ISSUE TITLE
Cannot find name 'process' when running Typescript test with docker image

### ISSUE THREAD

**Issue by SveLil** [DevExpress/testcafe#3477]
### What is your Test Scenario?
- Simple test to open a web page.
- The IP where the page is located should be provided through environment variables.
- The tests should run inside a Docker container
- The tests are written with typescript
 
### What is the Current behavior?
When running the test locally, everything works fine. When running them via Docker, the TS compilation fails:
```
Error: TypeScript compilation failed.
/tests/src/test/e2e/login.testcafe.ts (10, 14): Cannot find name 'process'.
```

### What is the Expected behavior?
The tests run inside Docker
 
### What is your web application and your TestCafe test code?

Your website URL (or attach your complete example):

<details>

```javascript
import { Selector } from "testcafe";
import * as fetch from "isomorphic-fetch";

// import { ReactSelector } from "testcafe-react-selectors";

fixture("Getting Started")
	.page(`http://${process.env.CLIENT_HOST}:3000/website/`)
	.beforeEach(async t => {
		return fetch(
			`http://${process.env.SERVER_HOST}:${process.env.SERVER_PORT}/server/end2end/load?profileName=minimal`,
			{ method: "PUT" }
		);
	});
```
</details>

### Steps to Reproduce:

1. Create a simple test that uses environment variables and is written in typescript
3. Run: `docker run -v /home/.../src/main/client/:/tests -it testcafe/testcafe firefox /tests/**/*testcafe.ts`
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.0.1
* node.js version:                    10.14.1
* platform and version:            Linux Ubuntu 16.04.5
* Docker version:                    18.09.2
* Docker image:                      testcafe/testcafe:latest ("Created": "2019-02-14T17:34:22.494691569Z")

**Comment by SveLil** [comment]
Hint: Adding
```js
import * as process from 'process'
```
to the file helps, adding node to the compilerOptions "types" arrays didn't

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. I've reproduced the problem.

Please note that TestCafe doesn't support custom compiler options yet: https://github.com/DevExpress/testcafe/issues/1845.

**Comment by miherlosev** [comment]
Hi @SveLil 

I cannot reproduce the problem with the latest docker image (`1.2.1`).

Test code
```js
import { Selector } from "testcafe";

fixture("Getting Started");

test('test', async t => {
	console.log(`${process.env.HOSTNAME}`);
});
```

![image](https://user-images.githubusercontent.com/4133518/59276717-83119b00-8c67-11e9-84bd-0f3aa6537803.png)

Try to run your tests with this docker image and let us know about your results.
