### ISSUE TITLE
Docs: Update docs how to use the docker image with proxy

### ISSUE THREAD

**Issue by nmohaupt** [DevExpress/testcafe#3479]
### What is your Test Scenario?

I want to use the Testcafe docker image on my CI system behind a proxy. Currently I can't find any documentation on that. 
### What are you suggesting?

Please add the documentation here: https://devexpress.github.io/testcafe/documentation/using-testcafe/using-testcafe-docker-image.html
What took me a long time to figure: don't set the http_proxy, https_proxy, no_proxy variables from the host system in the docker container. (I guess the are used by Testcafé?) Only use pass --proxy parameter when starting the container to Testcafé.

**Comment by AlexKamaev** [comment]
Thank you for your inquiry. We'll think about how to improve this.
