### ISSUE TITLE
Use Testcafe in Single Sign On enviornment is not working

### ISSUE THREAD

**Issue by walidanwar75** [DevExpress/testcafe#3484]
### What is your Test Scenario?
I am trying testcafe with a web app that uses windows authentication. So the current logged in user is picked up by the web app if we launch it directly from the browser and works fine. 
### What is the Current behavior?
When I try testcafe, it seems that the proxy is not using and not passing along the current logged in user credentials, which causes the 401 Unauthorized Error

### What is the Expected behavior?
I am expecting testcafe to launch tests using the current logged in user credential so it matches the real scenario when we launch the  SUT app from the browser directly. 

### What is your web application and your Testcafe test code?
It is an intranet application that uses Windows authentication. In our environment, we have SSO for everything and we can not even login using username and password, so using the NTLM HTTP authentication with username and password will be a major roadblock.

Example Code (not real app URL)

import { Selector } from 'testcafe';

fixture `OCC Test`
    .page `https://my_windows_authentication_intra_app/`;
    
    test('My test', async t => {

        const link = Selector('a');
        await t
            .typeText('#q','press release')
            .pressKey('enter')
            .expect(Selector('#news').find('tr').count).eql(13);
});

If I launch https://my_windows_authentication_intra_app/ from the browser it works fine.
When I run testcafe, the proxy-ed page gets 401 HTTP unauthorized error

**Comment by AlexKamaev** [comment]
TestCafe allows you to test web pages protected with Windows (NTLM) authentication. Please refer to the following article for more details: https://devexpress.github.io/testcafe/documentation/test-api/authentication/http-authentication.html

**Comment by walidanwar75** [comment]
Thanks for your reply. In our environment we use PIV cards to logon to the workstation. So the usage of username and password is prohibited. We only use the PIV card with a pin code. My question is, why the proxy or the testcafe studio ignore the current logged on user credentials and pass them along to the SUT pages? This will be a major roadblock for all federal agencies in the to adopt this awesome test automation tool.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by AlexKamaev** [comment]
Thank you for your explanation. As far as I understand, this question is also discussed at https://github.com/DevExpress/testcafe/issues/3500
Let's continue our discussion there.
