### ISSUE TITLE
How to skip failing assertions without try/catch

### ISSUE THREAD

**Issue by boerdjamin** [DevExpress/testcafe#3487]
Hello everyone,

the app I am testing changes its UI in the middle of the test execution (at different points of time) and leads the test to fail at different points of execution. I want testcafe to break out of the nested test functions when the UI changes and return to a previous point of code. I tried to solve it with try/catch, but this did not work out (same problem as #2996).
The difference is, that I don't want to restart the failing assertion, but skipping all assertions after it and return to the code after the block.

My current code with try/catch:

```
test('Run player tests', async (t: TestController) => {
    let shouldRunTest = await isPlayerRunning();
    await t.expect(shouldRunTest).ok('Player is not running');
    while (shouldRunTest) {
        shouldRunTest = await isPlayerRunning();

        if (!shouldRunTest) break;

        if (await component.exists) {
            try {
              // the function where the test will fail
                await runTest(t);
            } catch (e) {
                if (!(await component.exists)) {
                  // catch error when UI changes and restart while loop
                    continue;
                } else throw e;
            }
        }

        if (await anotherComponent.exists) {
            await runAnotherTest(t);
            continue;
        }

    }
});
```

How can I stop testcafe from caching the error and just restart the while loop? Or is there a way to restart the test run without closing the app?

**Comment by Farfurix** [comment]
@boerdjamin.

TestCafe cannot restart the loop in the catch block or restart the test without closing your application. We don't recommend using such scenarios with TestCafe API methods' try/catch logic because this [will break the chain of promises](https://github.com/DevExpress/testcafe/issues/2996#issuecomment-431286965).

**Comment by boerdjamin** [comment]
Ok it seems like there is no way to catch errors in testcafe, so I suppose the only solution is to check the existence of the component before each assertion
