### ISSUE TITLE
Customize user agents in reports

### ISSUE THREAD

**Issue by palpatine1991** [DevExpress/testcafe#3489]
### What is your Test Scenario?
We are testing on large test matrix which caontains both iPhone and iPad with the latest iOS. The problem is that the generated report does conatain only the user agents which are equal for those devices and therefore there is no way how to find out which tests are failing on which device.

### What are you suggesting?
It would be nice if there would be a way how to distinguish between the user agents in the failed tests. At least to assign some ID based on the order in which the devices were connected to the testcafe.

**Comment by miherlosev** [comment]
Hi @palpatine1991 

Thank you for your suggestion.
In the future, we will consider ways to improve displaying browsers in which tests are executed.
Now, we display the user agent, but in my opinion the browser alias is more readable.
