### ISSUE TITLE
Test never returns to fixture page after authentication

### ISSUE THREAD

**Issue by viveleroi** [DevExpress/testcafe#3490]
### What is your Test Scenario?

After authentication I expect the test's `page` URL to be used/hit.

I'm trying out testcafe so am just getting everything working.
 
### What is the Current behavior?

After authenticating correctly, the test never returns to the `page` URL. It will if I use `navigateTo` after the `useRole` command.

- It first hits `/signin` correct
- It enters login data and clicks submit, and authentication completes
- Our login code (java, via tomcat/spring) redirects to `/` which when logged in, is an AngularJS app
- angular router "redirects" to `/#!/our/path/`
- tc sends me back to `/signin`
- the redirects happen over again
- it never goes back to the actual test url
 
### What is the Expected behavior?

I expect the page url to be used. 
 
### What is your web application and your TestCafe test code?

Unfortunately I can't share a public example.

<details>
<summary>Your complete test code (or attach your test files):</summary>

```js
import { Role, Selector } from 'testcafe';

const regularUser = Role('http://127.0.0.1/signin?r', async t => {
    await t
        .typeText('[name=username]', 'abc')
        .typeText('[name=password]', '123')
        .click('.btn-primary');
});

fixture `Characters Modal`
    .page `http://127.0.0.1/example`;

test('it opens the modal', async t => {
    await t
        .useRole(regularUser)
        .expect(Selector('.ng-scope').exists).ok();
});
```
</details>

<details>
<summary>Your complete test report:</summary>

```
AssertionError: expected false to be truthy

      Browser: Chrome 72.0.3626 / Mac OS X 10.14.2

          7 |test('it opens the modal', async t => {
          8 |    await t
          9 |        .useRole(regularUser)
         10 |        .expect(Selector('.ng-scope').exists).ok()
         11 |        .click('.btn')
       > 12 |        .expect(Selector('.modal-dialog').exists).ok();
         13 |});
         14 |
         15 |// test('it\'s titled "Insert Symbol"', async t => {
         16 |//     await
      t.expect(Selector('.modal-title').innerText).eql('Insert Symbol');
         17 |// });

         at ok
      (/Users/redacted/test/e2e/modals/character.spec.js:12:51)
         at test
      (/Users/redacted/test/e2e/modals/character.spec.js:7:1)
         at markeredfn

   (/Users/redacted/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at <anonymous>

   (/Users/redacted/node_modules/testcafe/src/api/wrap-test-function.js:7:5)
         at fn

   (/Users/redacted/node_modules/testcafe/src/test-run/index.js:240:19)
         at TestRun._executeTestFn

   (/Users/redacted/node_modules/testcafe/src/test-run/index.js:236:38)
         at _executeTestFn
      (/Users/redacted/node_modules/testcafe/src/test-run/index.js:289:24)
```
</details>

### Steps to Reproduce:

Redirect user after login, use angular or another URL-writing router, use the fixture above.
 
### Your Environment details:
 
* testcafe version:                   1.0.1
* node.js version:                    v11.9.0
* command-line arguments:  testcafe chrome test
* browser name and version: Chrome 72
* platform and version:          macOS 10.14.2

**Comment by miherlosev** [comment]
Hi @viveleroi 

Try to use the [PreserveUrl](https://devexpress.github.io/testcafe/documentation/test-api/authentication/user-roles.html#optionspreserveurl) option.

**Comment by viveleroi** [comment]
I have, but unless I misunderstand it's purpose, that's for preserving the post-login URL for future `useRole` instances, not anything that returns tc to the actual fixture `page`

**Comment by miherlosev** [comment]
Did [PreserveUrl](https://devexpress.github.io/testcafe/documentation/test-api/authentication/user-roles.html#optionspreserveurl) option help you?

**Comment by viveleroi** [comment]
No, I had tried it before posting.

**Comment by miherlosev** [comment]
OK, I understand. According to your description, it's difficult to determine the cause of the problem. It can be a known issue - https://github.com/DevExpress/testcafe/issues/2195 or something else.
In general, I need to look at your application and tests to say something definite.
If you can provide us with a simple example to reproduce the issue, please feel free to reopen the issue.
