### ISSUE TITLE
Improve the 'Failed to find a DNS-record for the resource at' error message

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#3492]
See links:
* https://github.com/DevExpress/testcafe/issues/1802
* https://github.com/DevExpress/testcafe/issues/3304
* https://github.com/DevExpress/testcafe/issues/1606
* https://github.com/DevExpress/testcafe/issues/1135
* https://github.com/DevExpress/testcafe/issues/1601
* https://github.com/DevExpress/testcafe/issues/2460

Now the message is very technical.
It should be more user-friendly. For example:
```js
TestCafe cannot load the 'https://localhost:3000' resource.
Make sure that this resource is available on machine on which you run your tests.
See the <link-to-help-topic> for more detail.
```

Help topic will contain information about the causes of the connectivity issue and ways to fix it.

**Comment by helen-dikareva** [comment]
It would be great if you provided different errors (and error codes) for [all hammerhead errors](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/messages.ts#L2). In this case we will be able to decorate them in Studio.
