### ISSUE TITLE
Integrate TestCafe with Google Chrome lighthouse

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#3493]
https://github.com/GoogleChrome/lighthouse
https://stackoverflow.com/questions/54863796/how-to-integrate-lighthouse-with-testcafe

**Comment by tsvetann** [comment]
Any chance  for an update here? Thx

**Comment by arubtsov** [comment]
Hello @tsvetann,
 
Thank you for your interest in our tool. At present, Lighthouse integration won't be very useful because the underlying testcafe proxy will negatively affect Lighthouse metrics. To implement this feature, we need to support native browser protocols first: https://github.com/DevExpress/testcafe/issues/2623 and https://github.com/DevExpress/testcafe/issues/2624. Feel free to vote for them.

**Comment by Tall-KU-RideOn** [comment]
+100 - I would love to use TestCafe to integrate LightHouse into our testing! Their suggestion of puppeteer introduces a completely different language into my Automation that I do not want.  This would be 100% beneficial!  Please implement. :)

**Comment by AlexSkorkin** [comment]
Thank you for your input.

**Comment by vvedachalam** [comment]
Same here. I would love Lighthouse to get integrated with TestCafe so that I no need to rely on other frameworks to Audit our App.

**Comment by miherlosev** [comment]
Hi @abhinaba-ghosh

Thank you for your efforts. I've tried to run your module and found a problem.
![image](https://user-images.githubusercontent.com/4133518/84248878-b143e800-ab12-11ea-95ee-038775813435.png)

I guess you need to replace the `export` keyword with the `import` one.

**Comment by miherlosev** [comment]
Hi @abhinaba-ghosh

Thank you for your efforts. Before we close this enhancement, we need to perform a small test your library.

**Comment by abhinaba-ghosh** [comment]
Hi @miherlosev That would be great. Feel free to raise PR and suggest enhancements.

**Comment by miherlosev** [comment]
The module checking is blocked by this issue: [https://github.com/DevExpress/testcafe/issues/5190](https://github.com/DevExpress/testcafe/issues/5190). We will research the cause of the issue and check for a suitable solution. We will update this thread once we have any news.

**Comment by abhinaba-ghosh** [comment]
The ```exports``` issue related to [testcafe-lighthouse](https://www.npmjs.com/package/testcafe-lighthouse) is solved in version ```1.2.0```
Reference: https://github.com/abhinaba-ghosh/testcafe-lighthouse/issues/4

**Comment by AlexSkorkin** [comment]
Thank you for the update. We will take it into account.

**Comment by abhinaba-ghosh** [comment]
@miherlosev Is it good to close now?

**Comment by miherlosev** [comment]
Yes, we can close this issue.
