### ISSUE TITLE
Visibility check should incorporate visibility of parent element(s)

### ISSUE THREAD

**Issue by stefanschenk** [DevExpress/testcafe#3495]
Looking at the following example:

```
<body>
  <div>
    <span data-test="checkbox">
      <div style="display:none">
        <svg>...</svg>
      </div>
    </span>
...
```

If I perform a visibility check on the svg my test fails.
```.expect(Selector('[data-test="checkbox"]).find('svg').visible).notOk()```
```AssertionError: expected true to be falsy```

I suspect this happens because the svg element itself does not have `display:none` or a width and height of 0. But the parent of the svg **is** invisible, therefore from a DOM perspective (and user perspective), the child elements of the div are also invisible.

I would like to see that the visibility check incorporates the visibility of the parent element(s) of the tested element.
 
* testcafe version:                   0.23.3
* node.js version:                    v9.5.0
* command-line arguments:   testcafe chrome test/specs/component-test
* browser name and version: Chrome 71.0.3542
* platform and version:           Linux Ubuntu 17.10

**Comment by miherlosev** [comment]
Thank you for the detailed description. I've reproduce the problem.

**Comment by miherlosev** [comment]
For team:

*index.html*
```html
<html>
    <body>
		<div>
			<span data-test="checkbox">
				<div style="display:none">
					<svg viewBox="0 0 300 100" stroke="red" fill="grey">
						<circle cx="50" cy="50" r="40" />
						<circle cx="150" cy="50" r="4" />
					</svg>
				</div>
			</span>
		</div>
	</body>
</html>
```

*test.js*
```js
import { Selector } from 'testcafe';

fixture `Fixture`
	.page('http://localhost:8080/index.html');
	
test('test', async t => {
	const svg = Selector('[data-test=checkbox]').find('svg');
	
	await t
	.expect(svg.exists).ok()
	.expect(svg.visible).notOk();
});	
```

**Comment by adlantz** [comment]
Hello was wondering if there's an update on this/should I expect a fix any time soon?

**Comment by aleks-pro** [comment]
Hello @adlantz ,

There are no updates yet. Once we have any news, we will post it here.

**Comment by adlantz** [comment]
In the meantime I've found a workaround that works for me. The code

`yourSelector = yourSelector.filter((element) => element.closest('[style="display: none;"]') === null)`

will filter out any invisible elements selected by your selector. Then you could do something like

`t.expect(yourSelector.count).lte(0);`

Ain't the prettiest solution but it does the deed.

**Comment by wentwrong** [comment]
Hello @adlantz,

Thank you for sharing your workaround.
