### ISSUE TITLE
Docker fails when test in chromium

### ISSUE THREAD

**Issue by doomleika** [DevExpress/testcafe#3499]
### What is your Test Scenario?

As titile, test fails when run tests in official docker image when browser is chromium. I have tested this on 1.0.0, 1.0.1 and 1.0.2-alpha.1 and they all have same problem

### What is the Current behavior?

```
ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or
 remote device failure.
```
 
### What is the Expected behavior?

 
Um, It's not supposed to fail.

### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example): https://grafana.com/

<details>
<summary>see above</summary>

</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1.  Have this dummy test

```js
'use strict';

fixture(`Test Fixture`)
    .page(`https://www.google.com`)
    .afterEach(async (t) => {
        await t.takeScreenshot()
    })

test(`specific test`, async t => {
    await t.hover(`body`);
})
```

2. Run tests in docker

```
docker run -ti -v `pwd`:/tests testcafe/testcafe chromium /tests/dummy.js
```

3. docker reports 

```
ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or
 remote device failure.
```
 
### Your Environment details:
 
* testcafe version:                  1.0.1
* node.js version:                    8.11
* command-line arguments:  see above
* browser name and version: provided in 
* platform and version:          MacOS 10.10 and windows 10 pro
* other:

**Comment by miherlosev** [comment]
Hi @doomleika 

In your case, you need to add the `--no-sandbox` flag to Chromium.
```js
docker run -v `pwd`:/tests testcafe/testcafe 'chromium --no-sandbox' /tests/dummy.js
```
![image](https://user-images.githubusercontent.com/4133518/53495229-929e1700-3ab0-11e9-9164-ca06a1156939.png)

For more details, see the [Using TestCafe Docker image](https://devexpress.github.io/testcafe/documentation/using-testcafe/using-testcafe-docker-image.html) help topic.

**Comment by doomleika** [comment]
Thanks, and sorry, I must've missed the note on `--no-sandbox`
