### ISSUE TITLE
Support for Kerberos SSO authentication

### ISSUE THREAD

**Issue by walidanwar75** [DevExpress/testcafe#3500]
I downloaded the testcafe source code into my machine. How can I debug the testcafe specifically how it starts the browser when I start a test. Ia m trying to figure out if there is any possibility of testcafe to support SSO (Single Sign On) using client certificates

**Comment by miherlosev** [comment]
Hi @walidanwar75 

TestCafe uses different ways to run browsers. TestCafe starts Google Chrome and Firefox browsers using debug protocols (Chrome Debug Protocol and Marionette) and spawn a new process with specified parameters for other browsers. Start to debug the browser starting mechanism [here](https://github.com/DevExpress/testcafe/blob/master/src/browser/provider/index.js#L226).
 
However, it's too complex. If you can provide us with a simple example, we can try to run TestCafe for websites with 'Single Sign On' and answer all your questions.

**Comment by walidanwar75** [comment]
Hi Miherlosev
Thank you so much for your quick reply. I am so grateful for the nice work that has been done in testCafe, it is really an amazing e2e testing tool. 
I am trying to convenes management in my organization to use it and also use the TestCafe Studio once released to production. They are on board and excited to move forward but we have a major road block which is we can not use user name and password in our organization. We use smart cards to login to our laptops. so these smart card authentication allows me to logon to Windows OS and the network using my card and a pin. Once I am logged on, any intranet site that I use already authenticate me and never asks about password. This is done through mutual authentication where my smart card is associated with a client certificate that is used for the web sites authentication. When using testCafe, my guess is since we are running our scripts through hammerhead, that client certificate that normally authenticate me is not picked up. so unless I use httpauth with a username and password it will give me http 401 error. But again, my organization is strongly restricting the use of username and password.

I think it is possible to add a feature to pick a client certificate in hammerhead and use it when launching the browser connections but not sure how this can be done

Thanks again and sorry for the long explanation.

**Comment by walidanwar75** [comment]
In fact, digging deeper into the issue, it is not only support for client certificate, but in order for testcafe to be adopted at large scale, testcafe need to support Kerberos SSO authentication that is integrated with smart card logon to windows OS. This is a very common setup in so many organizations and government agencies
Check out these links
https://www.npmjs.com/package/express-kerberos

https://60devs.com/nodejs-sso-with-kerberos.html

**Comment by Farfurix** [comment]
@walidanwar75
 
Thank you for your investigation.
In practice, we didn't use this authentication system in our environment. If I understand it correctly, you can use the following snippet partially in your [Custom Hook](https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/#creating-a-custom-http-request-hook):
```js
//cut phrase "Negotiate"
var ticket = req.headers.authorization.substring(10);

//init context
kerberos.authGSSServerInit("HTTP", function(err, context) {
  //check ticket
  kerberos.authGSSServerStep(context, ticket, function(err) {
    //in success context contains username
    res.set( 'WWW-Authenticate', 'Negotiate ' + context.response);
    res.send(context.username);
  });
});
```
 
Useful links:
1. https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/
2. https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/creating-a-custom-http-request-hook.html
3. https://github.com/DevExpress/testcafe/issues/2489#issuecomment-420627710
