### ISSUE TITLE
It's not possible to focus on label with tabIndex=0 and "for" attribute

### ISSUE THREAD

**Issue by andres-kovalev** [DevExpress/testcafe#3501]
### What is your Test Scenario?
I have a radio button associated with label using "for" attribute. Label also has "tabIndex" attribute to be focused. When i click on this label using testcafe, it not became focused. But in real situation it is.
 
### What is the Current behavior?
Currently this test always fails.
 
### What is the Expected behavior?
When i'm clicking on this label by mouse, label became focused.
 
### What is your web application and your TestCafe test code?

My component looks like this one

```html
<div>
 <label for="radio" tabIndex="0">...</label>
 <input type=radio id=radio>
</div>
```

```scss
label {
  background: red;
  &:focus {
    outline: 0;
    background: green;  // just to check whether this component is focused
  }
}
```

And test case is:

```js
const label = Selector('label');
test('...', async t => {
  await t
     .click(label)
     .expect(label.focused)
     .ok();
});
```

### Steps to Reproduce:
1. Run test

### Workaround

When i replacing label with span, it works (but i need to check radio button by myself because "for" attribute does not work for spans).

### Your Environment details:
 
* testcafe version:                   0.22
* node.js version:                    10.13.0
* browser name and version: chrome 72
* platform and version:         macOS 10.13.6

**Comment by miherlosev** [comment]
Hi @andres-kovalev 

Thank you for the detailed description. I've reproduced the problem.

For TestCafe Team
The `focus` event does not raise for `label` component when TestCafe clicks on this.

*index.html*
```js
<html>
    <head>
	    <style>
		    label { background: red; }
			label:focus {background: green;outline: 0}
		</style>
	</head>
    <body>
		<div> 
			<label for="radio" tabIndex="0">...</label> <input type=radio id=radio> 
		</div>
		<span id='log'></span>
		<script>
		   var label = document.querySelector('label');
		   var log   = document.querySelector('#log');
		   
		   label.addEventListener('focus', function () {
		       log.textContent = log.textContent + 'label focused ';
		   });
		</script>
	</body>
</html>
```
*test.js*
```js
import { Selector, t } from 'testcafe';

fixture`Login`.page('http://localhost:8080');

 const label = Selector('label'); 

 test('...', async t => { 
	await t
	    .setTestSpeed(0.1)
		.click(label);
		
});
```

**Comment by pshendry** [comment]
I have a similar problem which seems related: I've got a custom dropdown component that looks like this:

```html
<div tabindex="0">
  <div>Placeholder</div>
  <div>
    <ul>
      <li>Item 1</li>
      <li>Item 2</li>
    </ul>
  </div>
</div>
```

On Chrome/Edge/Firefox/IE11, clicking the outer `<div>` focuses it, however on TestCafe in IE11, the click does not focus the div. It appears to work in TestCafe in Chrome/Edge/Firefox.
