### ISSUE TITLE
await ctx.eval(() => location.reload(true)); doesn't refresh the page from fixture

### ISSUE THREAD

**Issue by jiteshsojitra** [DevExpress/testcafe#3502]
How can we refresh the page/URL from fixture? Tried await ctx.eval(() => location.reload(true)); but it doesn't work, the same code works fine from the test but not from fixture (.after).

### What is your Test Scenario?
    fixture `Create Mail fixture`
	  .page(process.env.SERVER_HOST_URL)
	  .before(async ctx => {
		await common.configuration(__filename, ctx);
	  })
	  .beforeEach(async t => {
		try {
			await common.createAccount(t);
		} catch (error) {
			console.log(error);
			throw new Error('Error occured in fixture beforeEach method');
		}
	  })
	  .after(async ctx => {
		await ctx.eval(() => location.reload(true));
	});
 
### Error:
    1) - Error in fixture.after hook -
        TypeError: ctx.eval is not a function

### What is the Current behavior?
- Page doesn't refresh.
 
### What is the Expected behavior?
- Page should be refreshed
 
### Your Environment details:
 
* testcafe version:                   
v1.0.1
* node.js version:                    
v8.12.0

**Comment by miherlosev** [comment]
Hi @jiteshsojitra 

Fixtures `before` and `after` hooks does not have access to the tested page (see the [corresponding help topic](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#fixture-hooks)).

You can refresh the tested page in the `afterEach` hook:
```js
fixture `Create Mail fixture`
  .page(process.env.SERVER_HOST_URL)
  ....
  .beforeEach(async t => {})
  .afterEach(async t => {
	await t.eval(() => location.reload(true));
        or
        await t.navigateTo(process.env.SERVER_HOST_URL)
});
```

**Comment by jiteshsojitra** [comment]
Sorry but as mentioned in the question, i don't want to refresh the page after each tests but would like to refresh the page after fixture to save the time and free occupied resources.

**Comment by Farfurix** [comment]
@jiteshsojitra.

Could you please clarify what resources you are going to release and how this will help you save time?

**Comment by jiteshsojitra** [comment]
Our application occupies some memory which it releases on refreshing browser but we don't want to reload browser on each tests but once per fixture only. If we reload the browser on each test then it will obviously will take more time because application waits till it loads fine.

**Comment by Farfurix** [comment]
@jiteshsojitra.

In the following example, we have one specified Start Page and, as you can see in your browser, the page is reloaded twice after `Test1` and `Test2`. This is the default behavior.
```js
fixture `MyFixture`
    .page `http://devexpress.github.io/testcafe/example`;
 test('Test1', async t => {
    await t.wait(2000);
});
 test('Test2', async t => {
    await t.wait(2000);
});
 test('Test3', async t => {
    await t.wait(2000);
});
```
 
If you don't want to reload the page between tests, you need to use the `--disable-page-reloads` flag. Note that this flag is undocumented and experimental, so you will need to control all reload cleanups manually: clean cookie, storage, etc. Refer to the following issues for more information: DevExpress/testcafe#1770, DevExpress/testcafe#2850.

**Comment by jiteshsojitra** [comment]
@Farfurix, i think you didn't understand about the actual problem. I would like to refresh page from fixture using @after method.

**Comment by miherlosev** [comment]
@jiteshsojitra You can not reload the tested page in `fixture.after` test hook.
There are two opened suggestions that suit your needs: [Restart browser if it became unresponsive](https://github.com/DevExpress/testcafe/issues/1815), [
Implement per-test, not per-browser hooks](https://github.com/DevExpress/testcafe/issues/1345)

At present, I advise you to use the workaround from the #1345:
```js
function once(fn) {
    var executed = false;

    return function() {
          if (!executed) {
               executed = true;
               return fn.apply(this, arguments);
          }
    };
}


fixture `My fixture`
     .afterEach(once(async t => {
             await ctx.eval(() => location.reload(true))
      }));
```
