### ISSUE TITLE
Allow to specify a Role for a test or fixture page

### ISSUE THREAD

**Issue by viveleroi** [DevExpress/testcafe#3511]
My app redirects anonymous users to a login and while useRole restores a session and refreshes the page, it winds up sitting at a dashboard, not the test page.

### What is your Test Scenario?

I need to test an application/website which requires user authentication.
 
### What is the Current behavior?

When an anonymous user hits a user-specific/private URL within my site, they're redirected to a login page.

1. Anonymous user goes to `example.com/some/private/page`
2. App redirects them to `example.com/login`

There appears to be a fatal incompatibility with TestCafe's Roles implementation.

1. TestCafe goes to `example.com`
2. `useRole` is called for the first time, TestCafe navigates to `example.com/login`
3. TestCafe signs in correctly
4. TC goes back to the test URL, but has not yet "refreshed" with the correct state
5. Because TC is still "unauthorized" to view the page, app redirects back to `example.com/login`
6. TC "refreshes" the page with the correct useRole
7. Since TC now has the authenticated state, the dashboard shows, but it's not the right page
8. TC sits "Waiting for element to appear..."
9. Test fails

### What is the Expected behavior?

I would expect the navigation to happen after the state/session is restored.
 
### What is your web application and your TestCafe test code?

I can't provide a public website, but I've reproduced this on two completely unrelated websites with "redirect anonymous user" behaviors.

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
// role.js:
import { Role } from 'testcafe';

const regularUser = Role('https://example.com/login', async t => {
    await t
        .typeText('#user', 'abc')
        .typeText('#pass', '123')
        .click('#login');
}, { preserveUrl: true });

export { regularUser };


// login.spec.js:
import { regularUser } from './role';
import { Selector } from 'testcafe';

fixture `Login`
    .page `https://example.com`
    .beforeEach(async t => {
        await t.useRole(regularUser);
    });

test('username shows after login', async t => {
    await t.expect(Selector('#usr-admin a').innerText).eql('foo');
});

// project.spec.js:
import { regularUser } from './role';
import { Role, Selector } from 'testcafe';

fixture `Private Project Page`
    .page `https://example.com/private/project`
    .beforeEach(async t => {
        await t.useRole(regularUser);
    });

// This fails because the navigation to this page happens before useRole, so my app redirects to /login, useRole refreshes then, and ends up sitting on the app dashboard
test('project name shows', async t => {
    await t.expect(Selector('#proj-current a').innerText).eql('Foo');
});
```
</details>

<details>
<summary>Your complete test report:</summary>

```
testcafe chrome test/**/*.spec.js
Using locally installed version of TestCafe.
 Running tests in:
 - Chrome 72.0.3626 / Mac OS X 10.14.2

 Login
 ✓ username shows after login

 Private Project Page
 ✖ project name shows

   1) Cannot obtain information about the node because the specified
      selector does not match any node in the DOM tree.

       > | Selector('#proj-current a')

      Browser: Chrome 72.0.3626 / Mac OS X 10.14.2

          6 |    .beforeEach(async t => {
          7 |        await t.useRole(regularUser);
          8 |    });
          9 |
         10 |test('project name shows', async t => {
       > 11 |    await t.expect(Selector('#proj-current
      a').innerText).eql('Foo');
         12 |});
         13 |

         at eql
      (/usr/local/var/www/testcafe-test/test/project.spec.js:11:59)
         at test
      (/usr/local/var/www/testcafe-test/test/project.spec.js:10:1)
         at markeredfn

   (/usr/local/var/www/testcafe-test/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at <anonymous>

   (/usr/local/var/www/testcafe-test/node_modules/testcafe/src/api/wrap-test-function.js:7:5)
         at fn

   (/usr/local/var/www/testcafe-test/node_modules/testcafe/src/test-run/index.js:240:19)
         at TestRun._executeTestFn

   (/usr/local/var/www/testcafe-test/node_modules/testcafe/src/test-run/index.js:236:38)
         at _executeTestFn
      (/usr/local/var/www/testcafe-test/node_modules/testcafe/src/test-run/index.js:289:24)



 1/2 failed (23s)
```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.0.1
* node.js version:                    v11.9.0
* command-line arguments:  testcafe chrome test
* browser name and version: Chrome 72
* platform and version:          macOS 10.14.2

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. I think I understand what causes the problem. If your website always redirects a browser to a specific page after authorization despite which page was accessed by an unauthorized user before the authorization, then the `useRole` method can't restore the original test page.

As a workaround you can use the `navigateTo` method after a call to `useRole` without specifying `fixture.page`:
```js
const FIXTURE_PAGE = 'http://example.com/private';

fixture `Fixture`
    .beforeEach(async t => {
        await t
            .useRole(role)
            .navigateTo(FIXTURE_PAGE);
    }):
```
