### ISSUE TITLE
Test Sections

### ISSUE THREAD

**Issue by tomGrisley** [DevExpress/testcafe#3512]
Any update for https://github.com/DevExpress/testcafe/issues/1381, is this still planned to be implemented?

This would be extremely useful for the test suite that I have developed. 

Thanks,

**Comment by Farfurix** [comment]
@tomGrisley

Hello.
Thank you for your interest in this feature. At present we don't plan to implement it. Here you can see our roadmap update: https://github.com/DevExpress/testcafe/pull/3494/files?short_path=8133e7e#diff-8133e7e5c08d1b2cf8e71b95be1c3993
