### ISSUE TITLE
Edge fails to connect to test runner when vpn connection is open

### ISSUE THREAD

**Issue by viveleroi** [DevExpress/testcafe#3516]
On my local Windows 10 machine, Edge fails to connect to the TestCafe tests proxy/platform when I'm connected to my work VPN. That VPN needs to be active for testing, due to application authentication. 

My tests work fine on Chrome and Firefox.

1. I connect to the VPN
2. I started my tests with `$ testcafe edge "test/e2e/**/*.spec.js"`
3. Edge opens to `http://192.168.213.104:56680/browser/connect/fDl~1T1`
4. Edge shows an error page "Hmmm...can’t reach this page"

```
Try this
Make sure you’ve got the right web address: http://192.168.213.104:56680
Search for "http://192.168.213.104:56680" on Bing
```

I've tried specifying a `hostname` in `.testcaferc.json` of `127.0.0.1` but that didn't have any effect.
 
### Your Environment details:
 
* testcafe version:                   1.1.0
* node.js version:                    v11.9.0
* command-line arguments:  `$ testcafe edge "test/e2e/**/*.spec.js"`
* browser name and version: Microsoft Edge 44.17763.1.0
* platform and version:          Windows 10 x64

**Comment by AndreyBelym** [comment]
It looks like MS Edge has a problem with the VPN connection. Please try to install and run `http-server` with the following commands:
```
npm i - g http-server
http-server
```

After `http-server` starts, try to open `http://192.168.213.104:8080` in MS Edge.

> I've tried specifying a hostname in .testcaferc.json of 127.0.0.1 but that didn't have any effect.

Do you mean that MS Edge showed the  `http://192.168.213.104` url after you specified `127.0.0.1` in the config file? Have you tried to use the `--hostname` CLI switch or specify `localhost` as a hostname?

**Comment by viveleroi** [comment]
You're right, I suspect Edge is somehow failing without testcafe involved.

Trying http-server, and Edge fails to connect to it while Chrome works fine.

**Comment by viveleroi** [comment]
Just noting in case anyone has this issue: My VPN was configured *without* IPv6 support. Enabling that allowed Edge and IE11 to work.
