### ISSUE TITLE
beforeAll fixture hook

### ISSUE THREAD

**Issue by qualityshepherd** [DevExpress/testcafe#3517]
### What is your Test Scenario?

I need the ability to perform some actions in a browser _before all_ tests. Sadly, `before` doesn't have browser access and some actions you do not want to be repeated each test like in a `beforeEach`. Currently, my only solution is to couple tests or waste time with unneeded, repeated steps. 

### What are you suggesting?

A `beforeAll` hook that is fired only once per fixture. 

### What alternatives have you considered?

I've tried hacky ways to have things in `bforeEach` only fire once... but why not just have a `beforeAll`?

**Comment by Farfurix** [comment]
@qualityshepherd,

Hello. Our team will process your feature request in the context of https://github.com/DevExpress/testcafe/issues/1345.
