### ISSUE TITLE
Add HTMLMediaElement properties to Selector properties

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#3520]
### What is your Test Scenario?
Assert properties of a [HTMLMediaElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement) (`paused`, `currentTime`, `volume` , `muted` etc.).

### What are you suggesting?
Add important properties of the HTMLMediaElement class to the list of Selector properties.

**Comment by Artem-Babich** [comment]
We decided not to implement these properties inside the Selector class. To test the HTMLMediaElement with the TestCafe Selector function, you can use the [Selector.addCustomDOMProperties](https://testcafe.io/documentation/402759/reference/test-api/selector/addcustomdomproperties) method as follows:

```js
import { Selector } from 'testcafe';

 

fixture`Test fixture`
    .page('./index.html')

 

const MediaSelector = (selector) => Selector(selector).addCustomDOMProperties({
    paused:      el => el.paused,
    currentTime: el => el.currentTime,
    volume:      el => el.volume,
    muted:       el => el.muted,
});

 

test(`test`, async t => {
    const videoSelector = MediaSelector('#my-video');
    await playVideo();
    await t
        .wait(2000)
        .expect(videoSelector.paused).eql(false);
    await pauseVideo();
    await t
        .expect(videoSelector.paused).eql(true)
        .expect(videoSelector.currentTime).gt(0)
        .expect(videoSelector.volume).eql(1)
        .expect(videoSelector.muted).eql(false);
})
```

Feel free to reopen this issue and share appropriate details if this approach is not suitable for your usage scenario.
