### ISSUE TITLE
Add support for multiple configuration files

### ISSUE THREAD

**Issue by Waterstraal** [DevExpress/testcafe#3522]
At the moment Testcafé supports a single `.testcaferc.json` file. However, I have different needs in a c.i. environment than I have on my local machine for example. In my c.i. environment I have a need for the [xunit reporter](https://github.com/DevExpress/testcafe-reporter-xunit), multiple browsers and video recording for example, which I don't need locally. 

The api could look like this:
`testcafe --config .testcaferc-dev.json`
`testcafe --config .testcaferc-test.json`

.testcaferc-dev.json:
```json
{
  "browsers": "chrome",
  "reporter": "list"
}
```

 .testcaferc-test.json:
```json
{
  "browsers": [
    "chrome",
    "firefox",
    "edge"
  ],
  "reporter": [
    {
      "name": "xunit",
      "output": "reports/testcafe_tests.xml"
    },
    {
      "name": "html",
      "output": "reports/index.html"
    }
  ],
  "screenshotPath": "reports/screenshots",
  "takeScreenshotsOnFails": true,
  "videoPath": "reports/videos",
  "videoOptions": {
    "singleFile": true,
    "failedOnly": false,
    "pathPattern": "${USERAGENT}/${FILE_INDEX}.mp4"
  },
}
```

Aside from this, I would also need a different `baseUrl` for each environment in my DTAP street so adding `baseUrl` to the config and having the option to pass in the config file to testcafé would be very nice. Sadly `baseUrl` is currently not part of the configuration [yet](https://github.com/DevExpress/testcafe/issues/1932).

**Comment by miherlosev** [comment]
@Waterstraal

Thank you for your suggestion regarding the support for multiple configuration files. We received a similar request earlier and will consider implementing this feature in the context of this issue:

https://github.com/DevExpress/testcafe/issues/3428.

As for the `baseUrl` feature, is not a part of our [roadmap](https://github.com/DevExpress/testcafe/commit/c1cce3aba8b9d290a9c0039116828187198197bc). We will appreciate it if you get a chance to contribute this feature to our project. We will certainly help you in implementing this feature.
