### ISSUE TITLE
Support configuring proxy with environment variables

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#3525]
### What is your Test Scenario?
Use TestCafe in an environment that can automatically configure proxy via environment variables (e.g. [Docker](https://docs.docker.com/network/proxy/#configure-the-docker-client)) without additional efforts.

### What are you suggesting?
Read a proxy configuration from environment variables:
 - `HTTP_PROXY`
 - `HTTPS_PROXY`
 - `NO_PROXY`

**Comment by mfestrada** [comment]
Bumping... this would make life easier 🙏

**Comment by thelazurite-cell** [comment]
Hi folks! would this be a good beginner issue? 

I'd be interested in helping out :)

**Comment by AndreyBelym** [comment]
Hi @thelazurite-cell. We have plans to implement a centralized approach to retrieving TestCafe configuration from environment variables (in a way similar to [npm config](https://docs.npmjs.com/cli/v8/using-npm/config#environment-variables)). I'm afraid that the planned feature and this feature will have many common points in the code. There can be a lot of merge conflicts and we would like to avoid this situation. Let's postpone this feature for now. I will post a message here after we merge the other feature.

**Comment by Artem-Babich** [comment]
Hi,

We decided not to implement this enhancement. This task can be accomplished with TestCafe [javascript configuration file](https://testcafe.io/documentation/402638/reference/configuration-file#javascript). You can specify any option using environment variables and your own logic.

```js
module.exports = {
   proxy: process.env.HTTP_PROXY
}
```

Feel free to reopen this issue and share appropriate details if this approach is not suitable in your usage scenario.
