### ISSUE TITLE
TestCafe hangs for multiple tests on slow sites. 

### ISSUE THREAD

**Issue by NanjoW** [DevExpress/testcafe#3527]
### What is your Test Scenario?
```
fixture`Test`;
test.page('https://www.cnn.com/')('Something 1', async (t) => {});
test.page('https://www.cnn.com/')('Something 2', async (t) => {});
test.page('https://www.cnn.com/')('Something 3', async (t) => {});
test.page('https://www.cnn.com/')('Something 4', async (t) => {});
test.page('https://www.cnn.com/')('Something 5', async (t) => {});
```
 
### What is the Current behavior?
Testcafe gets through 2 of the tests and then hangs without error until suite times out. 
 
### What is the Expected behavior?
All tests should pass without hanging 
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 fixture`Test`;
test.page('https://www.cnn.com/')('Something 1', async (t) => {});
test.page('https://www.cnn.com/')('Something 2', async (t) => {});
test.page('https://www.cnn.com/')('Something 3', async (t) => {});
test.page('https://www.cnn.com/')('Something 4', async (t) => {});
test.page('https://www.cnn.com/')('Something 5', async (t) => {});
```
</details>

<details>
<summary>Your complete test report:</summary>

```
Using locally installed version of TestCafe.
 Running tests in:
 - Chrome 72.0.3626 / Mac OS X 10.13.6

 Test
(node:27638) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
 ✓ Something 1
 ✓ Something 2
ERROR The Chrome 72.0.3626 / Mac OS X 10.13.6 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.1.0
* node.js version:                    11.9.0
* command-line arguments:  testcafe chrome test.js
* browser name and version: Chrome v72.0.3626.119
* platform and version:             macOS 10.13.6

**Comment by miherlosev** [comment]
Hi @NanjoW 
 
I tried to run your example 10 times and always tests passed. I found that the tested page raises uncaught JavaScript errors sometimes. These errors are related to wrong setup Google Adwords or advertising network problems on the tested site.
I suggest you turn on the `--skip-js-errors` option to stabilize your tests.
If it does not help, please create another example where we can reproduce the problem and share it with us.
