### ISSUE TITLE
Testcafe integration with Create-react-app and Electron not firing correctly.

### ISSUE THREAD

**Issue by calebswank11** [DevExpress/testcafe#3533]
### What is your Test Scenario?

I want to run a simple e2e test on this test react-electron application
 
### What is the Current behavior?

I can get TestCafe to launch but depending on .testcafe-electron-rc config, it shows a blank page not loading the bundler or shows the application and hangs acting as if it didnt load.
 
### What is the Expected behavior?

TestCafe to complete tests and interact with the application in an electron window. 

### What is your web application and your TestCafe test code?

https://github.com/calebswank11/testcafe-electron

### Steps to Reproduce:

1. Create React App "app name" 
2. Change start/dev scripts via tutorial
    https://medium.freecodecamp.org/building-an-electron-application-with-create-react-app-97945861647c
3. implement testcafe and "testcafe-browser-provider-electron": "^0.0.8"
4. write sample test in ./src/e2e/e2etest.test.js (redundant naming I know)
5. run `yarn testcafe` which equals `"testcafe": "testcafe \"electron:.\" \"./src/e2e/**/*.js\""`

**.testcafe-electron-rc**
for white page that doesnt load bundle.js
```
{
  "mainWindowUrl": "./build/index.html",
  "appPath": "./"
}
```
for loading the app but not responding to events and recognizing it.
```
{
  "mainWindowUrl": "./public/index.html",
  "appPath": "./"
}
```

### Your Environment details:
 
* testcafe version:                   ^1.1.0
* node.js version:                    8.11.3 => a littl old, but works with testcafe 1.1.0 on other projects
* command-line arguments:  see package.json or above for list
* browser name and version: Chrome Version 72.0.3626.119 (Official Build) (64-bit)
* platform and version:          macOS Mojave 10.14

**Notes:** 
I believe it to probably be a config issue, but I've tried alot of different things and have searched the vastness of the interwebs for a solution.

reference: https://stackoverflow.com/questions/54988921/test-cafe-electron-create-react-app-not-loading-bundle-js-properly

**Comment by calebswank11** [comment]
@AndreyBelym Thank you very much for taking the time to look at this. I knew it had to be something simple like this, just couldn't quite piece it together. Duley noted about the deprecated `.test.` suffix as well. I have got it working now.

**Comment by AndreyBelym** [comment]
You are always welcome 😄
