### ISSUE TITLE
Fetch PUT Request gives 222 status code 

### ISSUE THREAD

**Issue by alexistaocognite** [DevExpress/testcafe#3535]
### What is your Test Scenario?
Fetch PUT request returns a 222 status code instead of a proper error code or 200 

### What is the Current behavior?
* In the test, after clicking the `click me` words on the page, no error is thrown, we get 222 status code instead
 
### What is the Expected behavior?
* After clicking the `click me` words on the page, an error should be thrown, then the state should be changed to display `error`
* Text should show up on page saying `error`
* Testcafe tests should pass 

## Your complete test code (or attach your test files):
```
import { Selector } from 'testcafe';

const button = Selector(`[data-test-id="button"]`);
const clicked = Selector(`[data-test-id="clicked"]`);

fixture('Button').page(`http://localhost:3000`);

test('Help', async t => {
  console.log('Help model opens on click');
  await t
    .click(button).expect(clicked.visible).ok().wait(100000);
});
```

## Your complete test report:
Note: this test fails because an error is never thrown, which affects the visibility of `clicked`. So, the test report below is not very useful 
```
✖ Help

   1) AssertionError: expected false to be truthy

      Browser: Chrome 72.0.3626 / Mac OS X 10.14.1

          6 |fixture('Button').page(`http://localhost:3001`);
          7 |
          8 |test('Help', async t => {
          9 |  console.log('Help model opens on click');
         10 |  await t
       > 11 |    .click(button).expect(clicked.visible).ok().wait(100000);
         12 |});
         13 |

         at ok (/Users/a/Desktop/test/tests/App.testcafe.js:11:44)
         at test (/Users/a/Desktop/test/tests/App.testcafe.js:8:1)
         at markeredfn
      (/Users/a/Desktop/test/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at <anonymous>
      (/Users/a/Desktop/test/node_modules/testcafe/src/api/wrap-test-function.js:7:5)
         at fn (/Users/a/Desktop/test/node_modules/testcafe/src/test-run/index.js:240:19)
         at TestRun._executeTestFn
      (/Users/a/Desktop/test/node_modules/testcafe/src/test-run/index.js:236:38)
         at _executeTestFn
      (/Users/a/Desktop/test/node_modules/testcafe/src/test-run/index.js:289:24)
```

### Steps to Reproduce:

1. Download the provided file 
2. Run `yarn start`
3. Click `click me` on the webpage
4. Text should show up saying `error`
5. Run `testcafe chrome tests/`
6. Test will fail because an error is never thrown 
 
### Your Environment details:
 
* testcafe version: 1.1.0
* node.js version: v8.15.0
* command-line arguments:  testcafe chrome tests/
* browser name and version: Chrome Version 72.0.3626.119
* platform and version: macOS Mojave Version 10.14.1

## File 
[test.zip](https://github.com/DevExpress/testcafe/files/2936406/test.zip)

**Comment by miherlosev** [comment]
Hi @alexistaocognite 

`222` is an internal TestCafe status code. It indicates the request does not pass the [CORS](https://developer.mozilla.org/ru/docs/Web/HTTP/CORS) rules.
If you open the application and click the 'click me' text on the page when you will get the error.

![image](https://user-images.githubusercontent.com/4133518/53886454-1e73ee00-4031-11e9-82bc-15a7fd18cd70.png)

You need to configure the `fetch` request to it passes the [CORS](https://developer.mozilla.org/ru/docs/Web/HTTP/CORS) rules.

At present, it is not clear what is happening. We will improve the current behavior. I've created an enhancement for you case - https://github.com/DevExpress/testcafe/issues/3536.
