### ISSUE TITLE
testcafe@1.1.0 capture the screenshot failed on iMac (Retina screen)

### ISSUE THREAD

**Issue by allayli** [DevExpress/testcafe#3541]
### What is your Test Scenario?

Capture the screenshot on iMac (Retina screen) 

### What is the Current behavior?

 
Only partial (half width & half height) is captured.

### What is the Expected behavior?

Full width & full height can be captured. (It works fine on testcafe@0.23.3)
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

https://www.mydevice.io/

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 fixture `fixture`
    .page `https://www.mydevice.io/`;

test(`test`, async t => {
    await t.takeScreenshot();
});

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

Screenshot:

![1](https://user-images.githubusercontent.com/5625605/53939317-a7e8f600-40ed-11e9-9d05-a44ff2af93d2.png)

thumbnails:

![1](https://user-images.githubusercontent.com/5625605/53939356-c222d400-40ed-11e9-8b5d-27fd7fa38111.png)

Expected:
<img width="1201" alt="screen shot 2019-03-07 at 3 18 40 pm" src="https://user-images.githubusercontent.com/5625605/53939729-e3d08b00-40ee-11e9-8162-4632c17225a0.png">

It seems that the screenshot() function does NOT concern the devicePixelRatio

</details>

### Your Environment details:
 
* testcafe version:                   1.1.0
* node.js version:                    v10.15.2
* command-line arguments:  testcafe ie,chrome -e test.js
* browser name and version: Chrome 72.0.3626
* platform and version:          Mac OS X 10.13.6
* other:                                   windows.devicePixelRatio = 2

**Comment by TareqElMasri** [comment]
I have the same problem

**Comment by RD0916** [comment]
And no error message is displayed.

**Comment by allayli** [comment]
Hi @AndreyBelym , I tested with ```testcafe@1.0.1``` and it works as expected. So I also think it is related to 0f86212 . 
And the commit also raise another issue about screenshot #3552
Please have a check. Thanks.

**Comment by AndreyBelym** [comment]
Thank you for confirming my assumption. We will fix this problem in the next development sprint.

**Comment by infctr** [comment]
I can confirm that `1.1.0` introduced a regression.

**Comment by AndreyBelym** [comment]
Fixed by https://github.com/DevExpress/testcafe/commit/9c96672c9c6a7fb50658a4c57f1e17ce645cd3b6, available in `testcafe@1,1,1`.
