### ISSUE TITLE
Clicking on element that is asserted visible fails due to not being visible

### ISSUE THREAD

**Issue by demsullivan** [DevExpress/testcafe#3545]
### What is your Test Scenario?
Trying to test clicking on a Google Maps marker. I've configured Google Maps to create markers with `optimized: false` which renders them as DOM elements. In my test, I verify that the element is visible first before attempting to click on it.
 
### What is the Current behavior?
Test click fails with error "The element that matches the specified selector is not visible"
 
### What is the Expected behavior?
The test should click on the element.
 
### What is your web application and your TestCafe test code?
Your website URL (or attach your complete example): http://hoodq-sdk-demo.s3-website-us-east-1.amazonaws.com/

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from 'testcafe';

fixture('Expose TestCafe bug')
    .page('http://hoodq-sdk-demo.s3-website-us-east-1.amazonaws.com/');

test('It fails to click on a visible element', async t => {
    const markers = Selector("img[src*='_school_marker.png']");
    const infoWindow = Selector('.hq-map-info-bubble');

    const targetMarker = markers.nth(0);

    await t
        .expect(targetMarker.visible).ok()
        .click(targetMarker)
        .expect(infoWindow.visible).ok();
});
```
</details>

<details>
<summary>Your complete test report:</summary>

```
Connecting 1 remote browser(s)...
Navigate to the following URL from each remote browser.
Connect URL: http://192.168.156.241:55805/browser/connect
CONNECTED Chrome 72.0.3626 / Windows 10.0.0
 Running tests in:
 - Chrome 72.0.3626 / Windows 10.0.0

 Expose TestCafe bug
 ✖ It fails to click on a visible element

   1) The element that matches the specified selector is not visible.

      Browser: Chrome 72.0.3626 / Windows 10.0.0

          9 |
         10 |    const targetMarker = markers.nth(0);
         11 |
         12 |    await t
         13 |        .expect(targetMarker.visible).ok()
       > 14 |        .click(targetMarker)
         15 |        .expect(infoWindow.visible).ok();
         16 |});

         at Object.<anonymous> (/mnt/c/Users/demsu/work/hoodq/hq-sdk/tests/functional/isolated.ts:14:10)
         at <anonymous> (/mnt/c/Users/demsu/work/hoodq/hq-sdk/tests/functional/isolated.ts:7:71)
         at __awaiter (/mnt/c/Users/demsu/work/hoodq/hq-sdk/tests/functional/isolated.ts:3:12)
         at test (/mnt/c/Users/demsu/work/hoodq/hq-sdk/tests/functional/isolated.ts:6:58)
         at markeredfn (/mnt/c/Users/demsu/work/hoodq/hq-sdk/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at <anonymous> (/mnt/c/Users/demsu/work/hoodq/hq-sdk/node_modules/testcafe/src/api/wrap-test-function.js:7:5)
         at fn (/mnt/c/Users/demsu/work/hoodq/hq-sdk/node_modules/testcafe/src/test-run/index.js:240:19)
         at TestRun._executeTestFn (/mnt/c/Users/demsu/work/hoodq/hq-sdk/node_modules/testcafe/src/test-run/index.js:236:38)
         at _executeTestFn (/mnt/c/Users/demsu/work/hoodq/hq-sdk/node_modules/testcafe/src/test-run/index.js:289:24)



 1/1 failed (21s)

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

Run the test.
 
### Your Environment details:
 
* testcafe version: 1.1.0
* node.js version: 10.11.0
* command-line arguments: testcafe remote path/to/test.ts
* browser name and version: Chrome 72
* platform and version: Chrome running on Windows 10; TestCafe running in WSL on Ubuntu 16.04
* other:

**Comment by demsullivan** [comment]
Also relevant: this fails intermittently, though the vast majority of the time. It passes successfully maybe every 4th or 5th run.

**Comment by AlexKamaev** [comment]
I checked your example and found two causes which lead to the issue.
1. The searchable element is not in the viewport of the page. Since this website does not have usual scrolling, but has some kind of endless scrolling, the TestCafe cannot scroll to the searchable element automatically.
2. The search element (the first with `img[src*='_school_marker.png']`) can be rendered in any place of the page; it is not defined.
I think in this endless scrolling scenario, you need to process scrolling to the searchable element in your code.
I prepared a sample test that demonstrates how this behavior can be reached.
```JS
import { Selector } from 'testcafe';

fixture('Expose TestCafe bug')
    .page('http://hoodq-sdk-demo.s3-website-us-east-1.amazonaws.com/');

test('It fails to click on a visible element', async t => {
    const markers = Selector("img[src*='_school_marker.png']");

    const targetMarker = markers.nth(0);

    const top = parseInt(await targetMarker.parent().getStyleProperty('top'));
    const left = parseInt(await targetMarker.parent().getStyleProperty('left'));

    const dragNumber = 5;

    for (let i = 0; i < dragNumber; i++) {
        await t.drag('#map',  -parseInt(left / dragNumber), -parseInt(top / dragNumber));
    }

    await t
        .expect(targetMarker.visible).ok()
        .click(targetMarker)
});
```
This code is still not 100% reliable, however, I think it's a good starting point to solve the issue.

**Comment by demsullivan** [comment]
Thanks, this pointed me in the right direction! I settled on this for my solution (additional help from https://stackoverflow.com/questions/52472321/need-help-to-check-if-element-is-in-current-viewport-with-testcafe)

```js
        const visibleMarkers = <Selector>Selector(() => {
            const windowHeight = window.innerHeight;
            const windowWidth  = window.innerWidth;
            const docWidth     = document.documentElement.clientWidth;
            const docHeight    = document.documentElement.clientHeight;

            return Array
                .from(document.querySelectorAll("img[src*='_school_marker.png']"))
                .filter((el: HTMLElement) => {
                    const boundValues = el.getBoundingClientRect();
                    return boundValues.bottom > 0 && boundValues.right > 0 &&
                        boundValues.left < (windowWidth || docWidth) &&
                        boundValues.top < (windowHeight || docHeight);
                });
        });
        const targetMarker = visibleMarkers.nth(0);
```
