### ISSUE TITLE
window.performance missing in ClientFunction

### ISSUE THREAD

**Issue by pavelloz** [DevExpress/testcafe#3546]
### What is your Test Scenario?
I want to get `window.performance` object with data inside
 
### What is the Current behavior?
Its empty
 
### What is the Expected behavior?
Will be filled with the same data as i have inside the browser when i inspect the test using .debug()
![image](https://user-images.githubusercontent.com/546845/54046884-e78b0d00-41d5-11e9-8b8d-7106bf7da450.png)

### What is your web application and your TestCafe test code?
```js
test('timing works', async t => {
  const getLoadTime = ClientFunction(() => performance.timing);
  console.log(await getLoadTime());
});
```
Your website URL (or attach your complete example):
https://www.example.com

### Steps to Reproduce:
Use example code above to see `{}` as a result instead of whats actually in the browser. 
 
### Your Environment details:
 
* testcafe version: 1.1.0
* node.js version:  10.13.0
* command-line arguments:  npx testcafe chrome
* browser name and version: chrome 72
* platform and version:        mac os 10.13.6

**Comment by AndreyBelym** [comment]
I've reproduced the problem. `performance.timing` stores all its properties in the prototype, not in the object. The [replicator]() package used by TestCafe for serializing objects and transferring them from a browser to the test code doesn't support this case yet. Thus I've created a feature request in the `replicator` repository: https://github.com/inikulin/replicator/issues/7.

As a workaround, you can use `JSON.stringify`/`JSON.parse`:
```js
const getLoadTime = async t => JSON.parse(await t.eval(() => JSON.stringify(window.performance.timing)));

console.log(await getLoadTime(t));
```

**Comment by pavelloz** [comment]
Thank you :)

**Comment by rakeshkumartripathy** [comment]
Hi Guys,

I want to get window.performance.memory object with data inside in TestCafe.

This "window.performance.memory" returns memory stats in Browser Console and I am not able to get the same through TestCafe.

Can you please help me here?

**Comment by alexey-lin** [comment]
Hi @rakeshkumartripathy,

`window.performance.memory`'s properties are non-enumerable, so `JSON.stringify` ignores them. You can adjust Andrey's sample like this:

```js
const getMemory = async t => JSON.parse(await t.eval(() => {
	const { jsHeapSizeLimit, totalJSHeapSize, usedJSHeapSize } = window.performance.memory;
	return JSON.stringify({ jsHeapSizeLimit, totalJSHeapSize, usedJSHeapSize });
}));
```

**Comment by rakeshkumartripathy** [comment]
Thank you @alexey-lin
