### ISSUE TITLE
Start executing test bodies only when a page is loaded completely

### ISSUE THREAD

**Issue by b324jll2j3h4lj23h4lj23n** [DevExpress/testcafe#3547]
### What is your Test Scenario?

Debugging by using the debugging instructions for Webstorm and Vscode
 
### What is the Current behavior?

When hitting breakpoints, the browser is sitting on the black screen
 
### What is the Expected behavior?
 
When hitting the breakpoint, the browser should be displaying the site under test
 
### What is your web application and your TestCafe test code?

 The example test from Testcafe github page

Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Setup Webstorm or Vscode by using the debugging instructions on the site
2. Set a breakpoint on one of the steps like .click()
3. Debug the test
4. When the breakpoint is hit - the browser is showing black screen
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by AlexKamaev** [comment]
I was not able to reproduce the issue with VSCode. I was following that [guide ](https://devexpress.github.io/testcafe/documentation/recipes/debug-tests/visual-studio-code.html) to create the debug configuration.
Here is my `launch.json` file
```JSON
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "protocol": "inspector",
            "request": "launch",
            "name": "Launch test files with TestCafe",
            "program": "${workspaceRoot}/node_modules/testcafe/bin/testcafe",
            "args": [
                "chrome",
                "${relativeFile}"
            ],
            "console": "integratedTerminal",
            "cwd": "${workspaceRoot}"
        }
    ]
}
```
And here is test code, which works as expected:
```JS
fixture `fixture`
    .page `http://example.com`;

test('test', async t => {
    await t.click('h1');
});
```
I think the cause of the issue could be related to some typo in configuration. Please provide us with your system configuration, your`launch.js` configuration file and the test code. This information will help me reproduce the issue on my side and research it.

**Comment by b324jll2j3h4lj23h4lj23n** [comment]
@AlexKamaev , I now see that it depends on the tested website, I tried example.com from your example and had no issues, however if you try devexpress.github.io/testcafe/example from the official example, the screen goes black on a breakpoint.

**Comment by miherlosev** [comment]
@b324jll2j3h4lj23h4lj23n 

As @AlexKamaev, I cannot reproduce the problem as well. Moreover, I can not even imagine how it looks. Would you please shoot video demonstrating the problem?

For video recording I  usually use [Jing](https://www.techsmith.com/jing-tool.html) tool .

**Comment by b324jll2j3h4lj23h4lj23n** [comment]
@miherlosev here's the video https://www.screencast.com/t/9uyC86Xe
I have a breakpoint in the test. 
I start debugging. 
Chrome launches, hits the breakpoint and remains black...
This is webstorm, same is happening in VScode and on different machines.

**Comment by miherlosev** [comment]
It looks very strange. I will try to reproduce the problem again.
Could you please provide more information about your environment: the operation system and browser names and versions, TestCafe version?

**Comment by b324jll2j3h4lj23h4lj23n** [comment]
Testcafe 1.1.0
MacOS 10.14.13
Chrome 72 (but repro on other browsers like FF too)

**Comment by AndreyBelym** [comment]
I've reproduced this behavior. TestCafe starts executing test functions before the test page is completely loaded and rendered. When you place a breakpoint on a chained action, the debugger will stop on it not when an action is actually executed but when the chain is constructed. 

We can make TestCafe wait until a page is completely loaded before starting test function execution. But it won't help you with breakpoints in chained actions. We need to make actions synchronous to achieve the expected behavior or design new syntax bearing this caveat in mind.

As for now, it's better to use the `t,debug` action to pause execution in the middle of a chain:
```js
test("test", async t => {
    await t
        .typeText(...)
        .debug()
        .click(...);
});
```

You can make a snippet in your IDE of choice and assign a key combination to save time on typing. Read more about this action in our documentation: [Debugging](https://devexpress.github.io/testcafe/documentation/test-api/debugging.html).

**Comment by AndreyBelym** [comment]
Implementing #3812 can potentially fix the issue.
