### ISSUE TITLE
Screenshot is not saved when TestCafe fails to detect page area

### ISSUE THREAD

**Issue by allayli** [DevExpress/testcafe#3552]
### What is your Test Scenario?

 Test with customised browser provider run on a real device.

### What is the Current behavior?

 With ```testcafe@1.1.0``` the screenshot will be deleted if there is no Crop Dimensions.
The following code is introduced in 0f86212
```js
await addToQueue(screenshotPath, async () => {
            await this._takeScreenshot(screenshotPath, ... pageDimensions ? [pageDimensions.innerWidth, pageDimensions.innerHeight] : []);

            if (!await Capturer._isScreenshotCaptured(screenshotPath))
                return;

            try {
                const binaryImage = await readFile(screenshotPath);

                const croppedImage = await cropScreenshot(
                    screenshotPath,
                    markSeed,
                    Capturer._getClientAreaDimensions(pageDimensions),
                    Capturer._getCropDimensions(cropDimensions, pageDimensions),
                    binaryImage
                );

                if (croppedImage)
                    await writePng(screenshotPath, croppedImage);
            }
            catch (err) {
                await deleteFile(screenshotPath);

                throw err;
            }

            await generateThumbnail(screenshotPath, thumbnailPath);
        });
```

### What is the Expected behavior?

 Expected result:

- Allow to save the fullscreen screenshot without any chop, which means:
```js
            catch (err) {
                // await deleteFile(screenshotPath);

                console.error(err);
            }
```

Or:

- Provide method in Browser Provide to fill in cropDimensions.

 
### Your Environment details:
 
* testcafe version:                   1.1.0 
* node.js version:                    v8.9.3 
* browser name and version: UC Browser 12.0.4 
* platform and version:          Android 7.1.1

**Comment by AndreyBelym** [comment]
Thank you for your report. Yes, TestCafe doesn't save a screenshot now if it can't detect a page area in the screenshot. In previous versions, TestCafe showed a warning in this case and saved a screenshot. We will fix this bug in the next development sprint.
