### ISSUE TITLE
Cannot read property 'tagName' of undefined

### ISSUE THREAD

**Issue by haydeemunozdelarocha** [DevExpress/testcafe#3553]
### What is your Test Scenario?
Regular e2e testing using roles in a react app with hash router, so currently reloading after the role to preserve the local storage item.
 
### What is the Current behavior?
Sometimes getting error:

```
 JavaScript error details:
      TypeError: Cannot read property 'tagName' of undefined
          at e.computedNthIndex (https://rec.smartlook.com/bundle-20190218085550.js:20:97496)
          at e.generate (https://rec.smartlook.com/bundle-20190218085550.js:20:97656)
          at t.moveListener (https://rec.smartlook.com/bundle-20190218085550.js:20:100751)
          at l (http://192.168.120.253:61063/hammerhead.js:13:25467)
          at HTMLDocument.<anonymous> (http://192.168.120.253:61063/hammerhead.js:6:26610)
```

When navigating to login page.

Showing error here:

```
import {e2eConfig as config} from "../e2e-config";
import {ClientFunction, Role, Selector} from "testcafe";

const reloadPage = ClientFunction(() => location.reload());
const getLocation = ClientFunction(() => document.location.href);

const loginRole = Role(config.urls.loginToDashboard, async test => {
    await test
        .expect(getLocation()).contains(config.urls.loginToDashboard)
        .maximizeWindow()
        .expect(config.selectors.login.emailInput.exists).ok()
      .expect(config.selectors.login.emailInput.visible).ok()
error thrown here >>        .typeText(config.selectors.login.emailInput, config.user.name)
        .typeText(config.selectors.login.passwordInput, config.user.password)
        .click(config.selectors.login.submitButton).wait(200)
        .expect(Selector('.analytics-head').visible).ok();
});

export const loginDashboard = async (test) => {
    await test.useRole(loginRole);
    // Reloading the page to load role localStorageItem, because of hash router the localStorageItem is not being set in the first redirect
    await test.expect(getLocation()).notContains(config.urls.loginToDashboard);
    await reloadPage();
};

```
 
### What is the Expected behavior?
No js errors
 
### Your Environment details:
 
* testcafe version:                   1.0.1
* node.js version:                    8.11.4
* command-line arguments:  testcafe chrome --speed .5 test/__e2e-tests__/selectors.e2e.spec.js
* browser name and version: Chrome 72
* platform and version:          macOS 10.13.6

**Comment by AlexKamaev** [comment]
We didn't face a similar issue, so we need to research it. It's unexpected that you got an error on `typeText` text. Please check if the error exists without TestCafe. If so, you can run TestCafe with the `--skip-js-errors` option (https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors)
Could you also reproduce the issue without roles but only with `typeText`?
If the error occurs only with TestCafe, I would appreciate it if you share your project or url to your site and full test code. If you cannot share your project, it would help if you prepare a simple example that demonstrates the issue.
