### ISSUE TITLE
Reuse browser instance

### ISSUE THREAD

**Issue by wistcc** [DevExpress/testcafe#3554]
Is there a way to reuse the browser instance?

At the moment Testcafe is opening a new browser instance for each `fixture` and this takes around 2 minutes. For the amount of `fixture` that I have, this is to much wasted time.

I saw this ticket https://github.com/DevExpress/testcafe/issues/1656 and then saw the [Remote browsers](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/browser-support.html#browsers-on-remote-devices) and [Test cafe Live](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/live-mode.html) modes but I don't think any of them help with this.

**Comment by AlexKamaev** [comment]
Using `fixtures` does not suppose that new browser instance will be started on each fixture.
You can check it by executing the following code:
```JS

for (let i = 0; i < 10; i++) {
    fixture `Fixture ${i}`
        .page('http://example.com');

    test(`${i}`, async t => {
        await t.click('h1');
    });
}
```
Could you please provide us with your working project and your test code? It will help us to research the issue efficiently. Please also specify the command you are using to run the tests.

**Comment by wistcc** [comment]
Yeap, you are right.

I was confused because I noticed several browser instances but after looking at your example I noticed that those instances were per job in Jenkins instead of per `fixture`, which makes complete sense.

Sorry about the false alarm and thank you for the quick response and the great job here on Testcafe.
