### ISSUE TITLE
How can I specify baseUrl for my tests in docker container?

### ISSUE THREAD

**Issue by medinsky** [DevExpress/testcafe#3556]
Greetings!

Hope you can help me.

I have urls that I want to test on different environments, for example on prod and dev envs.
Prod: https://my-project.host.com
Dev: https://my-project-dev.host.com

In tests I write 
```
fixture(`App on`)
        .page(`/main-page`)
```

when I am on local env, I have here autorouting to http://main-page
that isn't correct. I can write smth like this on local
```
fixture(`App on`)
        .page(`localhost/main-page`)
```
and everything works good, but I want to run this test on ci, and test two endpoints wich is not localhost.
how can I specify smth like baseUrl (in cypress) to make testcafe understand that 
```
        .page(`/main-page`)
```
means to go to route `https://my-project.host.com/main-page` on prod and `https://my-project-dev.host.com/main-page` on dev env

**Comment by LavrovArtem** [comment]
You can use the solution from the [Run Same Testcafe tests with different URLs per environment](https://stackoverflow.com/questions/54634918/run-same-testcafe-tests-with-different-urls-per-environment) question.

Or you can use `process.env` to pass a base url from the runner or docker to test code. 
The test example:
```js
fixture`fixture`
    .page`${process.env.baseUrl}/documentation/getting-started/`;
 
test('test', async t => {
    await t.click('body');
});
```
The runner example:
```js
const createTestCafe = require('testcafe');
 
createTestCafe()
    .then(tc => {
        process.env.baseUrl = 'https://devexpress.github.io/testcafe';
 
        tc.createRunner()
            .src('test.js')
            .browsers('chrome')
            .run()
            .then(() => tc.close());
    });
```
Docker documentation:
https://docs.docker.com/engine/reference/run/#env-environment-variables

Also, we try to keep the GitHub issue tracker for bugs and feature requests only (see also: Contributing). This issue looks like a question that would be best asked on StackOverflow - an amazing platform for users to ask and answer questions.
