### ISSUE TITLE
I have some questions regarding our functional testing

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#356]
Ok, I was not quite attentive to what's going on with our functional testing. Looking at it currently I have some questions:

1. https://github.com/DevExpress/testcafe/blob/master/test/functional/fixtures/runner/uncaught-js-errors/uncaught-js-errors-test.js#L35 - why `runTests` resolves with error?
2. https://github.com/DevExpress/testcafe/blob/master/test/functional/fixtures/runner/uncaught-js-errors/uncaught-js-errors-test.js#L47 - Why tests that names starts with `Should fail` expects successful completion?
3. https://github.com/DevExpress/testcafe/tree/master/test/functional/fixtures/runner/api/click - it's hard to determine the actual test and testcafe-test, the difference with naming is minimal. Can we have subdirs, e.g. `quarantine-mode/test.js` - actual test, `quarantine-mode/pages/*.html` - markup, `quarantine-mode/testcafe-fixtures/*.test.js` - TC fixtures?
4.  Why quarantine mode tests are not inside `runner` directory? BTW, I don't think we need `runner` directory` for now. We can start with the plain dir structure for now.
5. https://github.com/DevExpress/testcafe/blob/master/test/functional/fixtures/quarantine-mode/index-test.js#L40 - why we need additional server here? Can't we incorporate this functionality to the already existing test server?

\cc @AlexanderMoskovkin @georgiy-abbasov @AndreyBelym

**Comment by AlexanderMoskovkin** [comment]
>  2 . https://github.com/DevExpress/testcafe/blob/master/test/functional/fixtures/runner/uncaught-js-errors/uncaught-js-errors-test.js#L47 - Why tests that names starts with Should fail expects successful completion?

These tests should fail when the `skipJsErrors` option is disabled, but they should success when the option is enabled. So, we should change tests names. /cc @georgiy-abbasov

**Comment by AlexanderMoskovkin** [comment]
> 3 . https://github.com/DevExpress/testcafe/tree/master/test/functional/fixtures/runner/api/click - it's hard to determine the actual test and testcafe-test, the difference with naming is minimal. Can we have subdirs, e.g. quarantine-mode/test.js - actual test, quarantine-mode/pages/*.html - markup, quarantine-mode/testcafe-fixtures/*.test.js - TC fixtures?
4 . Why quarantine mode tests are not inside runner directory? BTW, I don't think we need runner directory` for now. We can start with the plain dir structure for now.

Sure we can. @georgiy-abbasov please do this

**Comment by AlexanderMoskovkin** [comment]
> 1 . https://github.com/DevExpress/testcafe/blob/master/test/functional/fixtures/runner/uncaught-js-errors/uncaught-js-errors-test.js#L35 - why runTests resolves with error?

As i remember we discussed this when `functional-harness` was implementing. @georgiy-abbasov please describe details of this here

**Comment by AlexanderMoskovkin** [comment]
> 5 .https://github.com/DevExpress/testcafe/blob/master/test/functional/fixtures/quarantine-mode/index-test.js#L40 - why we need additional server here? Can't we incorporate this functionality to the already existing test server?

I guess we can. We will discuss this with @AndreyBelym in private

**Comment by georgiy-abbasov** [comment]
1. This was done for pretty print if test unexpectedly fails.

Comparsion:
[`runtests` without `then`](http://content.screencast.com/users/GeorgeZA/folders/Jing/media/8f9348f1-1099-4780-9524-bdc299cc3c66/2016-02-26_1132.png)
[`runtests` with `then`](http://content.screencast.com/users/GeorgeZA/folders/Jing/media/7dafbe33-e851-408c-ab5b-f7bc6964bb10/2016-02-26_1131.png)

**Comment by inikulin** [comment]
@georgiy-abbasov You should not sacrifice integrity and correct usage of tooling to achieve pretty printing in the edge cases.

**Comment by georgiy-abbasov** [comment]
@inikulin, we discussed first and second paragraphs with @AlexanderMoskovkin, and found complexity.

```js
it(`Should success when peforming click action on the present element`,function () {
	return runTests(); // it resolves when success, and rejects when error occures
})

it('Shouldn\'t fail when performing click action on the missing element and shouldFail option enabled', function () {
	return runTests('fixture.test.js', 'testName', {shouldFail:true}); // it always rejects
})
```

We can refuse `shouldFail` argument, in that case "should fail" tests might look like this:
```js 
it('Shouldn\'t fail when performing click action on the missing element and shouldFail option enabled', function () {
	return runTests('fixture.test.js', 'testName')
        .then(function () {
           throw new Error('Test should be failed but it is succeed');
        })
        .catch(function (err) {
           expect(err).eql(expectedError);
        });
})
```
What do you think ?

**Comment by inikulin** [comment]
I don't get it, so, what's the problem?

**Comment by georgiy-abbasov** [comment]
`runTests` method always rejects when `shouldFail` option enabled. And it resolves and rejects, when `shouldFail` option disabled. Different behavior, i mean. It's ok ?

**Comment by inikulin** [comment]
Well, it's says it should fail and... it fails. What's wrong with it?

**Comment by georgiy-abbasov** [comment]
@inikulin, nothing, just made sure.

**Comment by georgiy-abbasov** [comment]
Cause we started work to refactor functional tests, i want to ask tech writers. \cc @VasilyStrelyaev, \cc @MargaritaLoseva 

We have different test naming, for example:
[Should success](https://github.com/DevExpress/testcafe/blob/master/test/functional/fixtures/runner/uncaught-js-errors/uncaught-js-errors-test.js#L40)
[Should be successful](https://github.com/DevExpress/testcafe/blob/master/test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js#L4)
[Should pass](https://github.com/DevExpress/testcafe/blob/master/test/functional/fixtures/runner/using-shared-code/shared-code-test.js#L12)

It's clear, that names are valid, but i think, test names should be more uniform.

And i have one more question. As @inikulin said, it's not clear why tests with name "Should fail" succeed. I have a one variant, @AlexanderMoskovkind suggested another two.
1. it('Should succes when element isn't present on the page and an exception is thrown')
2. it('Should not fail when element isn't present on the page if the shouldFail opt is enabled')
3. it('Should success when element isn't present on the page if the shouldFail opt is enabled')

What do you think ?

**Comment by inikulin** [comment]
@georgiy-abbasov There are 3 options here and it feels like 1 doesn't belong here. Am I wrong?

**Comment by VasilyStrelyaev** [comment]
@georgiy-abbasov 
*Should success* is not a correct phrase at all
*Should be successful* seems too long
*Should pass* is ok. Let's stick to it if we want our tests to be named uniformly.

**Comment by VasilyStrelyaev** [comment]
I didn't get the second question.
```
it('Shouldn\'t fail when performing click action on the missing element with the shouldFail option enabled', function () {
```
This name looks pretty. If it's not correct as to whether the test fails or not, we should change the first two words accordingly, choosing between *should fail* and *should pass*.

Is there a different problem

**Comment by georgiy-abbasov** [comment]
Ok, let it be 'Should pass when performing click action on the missing element with the shouldFail option enabled'. In that case i have false sense, that test pass only because shouldFail option enabled.

**Comment by inikulin** [comment]
> In that case i have false sense, that test pass only because shouldFail option enabled

Aaah, I've finally got it. You've messed it up. But in different way this time

**Comment by inikulin** [comment]
When we say `Should pass` or `Should fail` we talk about underlying **tescafe test**, not the mocha test. Is it clear?

**Comment by georgiy-abbasov** [comment]
Yes, we mean testcafe behavior.

**Comment by inikulin** [comment]
BTW `shouldFail`is the helper flag, it shouldn't leak to the test name. It should be just:
`Should fail when performing click action on the missing element`

**Comment by AlexanderMoskovkin** [comment]
> In that case i have false sense, that test pass only because shouldFail option enabled

Here should be `skipJsError` TestCafe option instead of `shouldFail`. And we should have two tests like this:
`Should fail if <condintion>`
`Should pass if <condintion> when 'skipJsError' is enabled`

**Comment by georgiy-abbasov** [comment]
@AlexanderMoskovkin, thanks, that's correct, because TestCafe doesn't have option `shouldFail`, it's

**Comment by inikulin** [comment]
Why close?

**Comment by AlexanderMoskovkin** [comment]
> georgiy-abbasov closed this 10 minutes ago

Why? We haven't fix this yet

**Comment by georgiy-abbasov** [comment]
Clicked wrong button, sorry.

**Comment by georgiy-abbasov** [comment]
@VasilyStrelyaev, should we use `if` instead of `when` ?

> Should fail if \<condintion\>
Should pass if \<condintion\> when 'skipJsError' is enabled

**Comment by VasilyStrelyaev** [comment]
interchangeable in this context
