### ISSUE TITLE
TestCafe starts getting 404 errors for any pages in session

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#3560]
### What is your Test Scenario?
Test a page that submits a form.
 
### What is the Current behavior?
After the form is submitted, the browser shows the 404 error. Trying to manually open any page in the current session will also lead to the 404 error.
 
### What is the Expected behavior?
The page is shown after the form is submitted.
 
### What is your web application and your TestCafe test code?
Check the origin ticket link.
 
### Your Environment details:
 
* testcafe version:                   1.1.0
* node.js version:                    10.12.0
* command-line arguments:  n/a
* browser name and version: Chrome 74
* platform and version:          Windows 10

**Comment by addisonmiller** [comment]
I'm experiencing this as well. Just wanted to pass along, that running safari test at same time corrects issue in Chrome. Just a workaround, not a fix.

**Comment by AlexKamaev** [comment]
@addisonmiller 
The website from the original issue has its own specifics so your problem is hardly related to it.
It's better to create a separate report using this [form](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md) . Please also provide us with an example which demonstrates the issue.
I would also recommend using the latest testcafe version since it has some fixes for similar issues

**Comment by AlexKamaev** [comment]
I was able to reproduce the issue on the sample. It's very unstable, but still fails:
```HTML
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

<script>
    function onClick () {
        setTimeout(function () {
            document.forms[0].submit();
        }, 100);
    }
</script>

<form action="http://google.com">
    <input type="text" id="text"/>
    <button onclick="onClick(); return false;">submit</button>
</form>

</body>
</html>

```
```JS
import { Selector } from 'testcafe';

fixture`fixture`
    .page`...`;

for (let i = 0; i < 10; i++) {
    test('1', async t => {
        await t.typeText('input', '12345');
        await t.click('button');
    });

    test('2', async t => {
       await t.wait(5000);
    });
}

```
