### ISSUE TITLE
Clicking SSL link does not trigger url redirect

### ISSUE THREAD

**Issue by brian-mathews** [DevExpress/testcafe#3562]
Submitting a form with a ssl cred link is not actually triggering expected confirmation url loading.
Same test works with Selenium and Robot Framework.

Expected Behavior:
1. Load Page
2. Fill Form Informaiton
3. Click Submit button
4. Confirmation Page loads

With TestCafe the last (#4) expected step never happens.

Test:
import { Selector, ClientFunction } from 'testcafe';
var generate_email = new Date().getTime();

fixture ('A User Buys A Subscription')
    .page('https://www.newyorker.com/subscribe');

test('A User Busy A Subscription And Redirects To Confirmation', async t => {
  await t
    .click('#NYR_MAGSUBHOME_SUBSCRIBELINK .btn.primary-btn')
    .wait(3000)
    .click('#digitalOffer .desktopShow .btn')
    .typeText('#first_name', 'Ford')
    .typeText('#last_name', 'Prefect')
    .typeText('#email', generate_email + '@newemail.com')
    .typeText('#zip', '78738')
    .typeText('#city', 'Austin')
    .typeText('#address', '11710 Emerald Falls Dr')
    .click(Selector('select[name="state"]'))
    .click(Selector('select[name="state"] option').filter('[value="TX"]'))
    .typeText(Selector('#cvv'), '222')
    .typeText(Selector('#credit-card-number'), '4111111111111111')
    .click(Selector('#credit-card-exp-month'))
    .click(Selector('#credit-card-exp-month option').filter('[value="02"]'))
    .click(Selector('#credit-card-exp-year'))
    .click(Selector('#credit-card-exp-year option').filter('[value="22"]'))
    .click('#btnSubmit');
  await t
    .expect(Selector('#website a').exists).ok()
    .expect(Selector('#customerCare a').exists).ok()
    .expect(Selector('#legal').exists).ok();
});

![image](https://user-images.githubusercontent.com/1863600/54292535-5cff3080-457c-11e9-918a-1f611b126848.png)

* testcafe version:                   0.20.2
* node.js version:                    v11.9.0
* command-line arguments:   testcafe -e chrome user-purchases-subscription.js
* browser name and version: Chrome 72.0.3626 / Mac OS X 10.12.6

**Comment by miherlosev** [comment]
Hi @brian-mathews 

You test have passed with `testcafe@1.1.0`. Try to use this version to run your tests.
![image](https://user-images.githubusercontent.com/4133518/54347656-75dd1400-4658-11e9-8e7e-27b30e9b7917.png)

**Comment by brian-mathews** [comment]
installed 1.1.0. now browsers launch but does no action after they initially open. happens with firefox, chrome and safari.

**Comment by AlexKamaev** [comment]
@brian-mathews
The issue in the 1.1.0 version is related to https://github.com/DevExpress/testcafe-hammerhead/issues/1885
Please also refer to the https://github.com/DevExpress/testcafe/issues/3438 issue for more information about this problem.
While we are working on it, you can use the following workarounds:
1. use the `--max-http-header-size` argument in the command line;
2. use the `RequestHooks` mechanism and mock all requests to external resources from your page. Please see the sample:
```JS
import { Selector, RequestMock } from 'testcafe';

const mock = RequestMock()
    .onRequestTo(req => {
        return req.url.indexOf('newyorker') === -1;
    })
    .respond(null, 200);

fixture('A User Buys A Subscription')
    .page('https://www.newyorker.com/subscribe')
    .requestHooks(mock);
```

I also want to mention that I needed to maximize the Chrome window to make your test work.

**Comment by brian-mathews** [comment]
Great, thanks for the information. I'll try the workarounds.
