### ISSUE TITLE
--allow-insecure-localhost --allow-running-insecure-content parameters not supported with IE11?

### ISSUE THREAD

**Issue by b324jll2j3h4lj23h4lj23n** [DevExpress/testcafe#3563]
I created Testcafe instance with SSL and tried to run it in IE11 with --allow-insecure-localhost --allow-running-insecure-content and was still hitting IE11 certificate errors. Everything worked in Chrome though.

**Comment by Farfurix** [comment]
@b324jll2j3h4lj23h4lj23n.

Hello, if I understand correctly, it is impossible to run Internet Explorer 11 with Chrome command line options: `--allow-insecure-localhost` and `--allow-running-insecure-content`. There are no such options in the [IE Command-Line Options](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/general-info/hh826025(v=vs.85)) list.

Also, this issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions. We try to keep the GitHub issues tracker for bugs and feature requests only.
