### ISSUE TITLE
Live mode does not work with tests written in TypeScript

### ISSUE THREAD

**Issue by janrozycki** [DevExpress/testcafe#3566]
When running tests written in TypeScript, they are executed once but after making some changes in watched file, TestCafe does not react.

**Comment by miherlosev** [comment]
Hi @janrozycki 

I cannot reproduce the problem (see the [video](https://www.screencast.com/t/4mPzuE08YAl)).
Could you please provide an example demonstrating the problem?
We also need more information about your environment: the operation system name and version, Node.js and TestCafe versions.
