### ISSUE TITLE
Allow to configure the HEARTBEAT_TIMEOUT

### ISSUE THREAD

**Issue by allayli** [DevExpress/testcafe#3567]
### What is your Test Scenario?

A test case needs long time to run. And sometimes heartbeat does not send periodically with HEARTBEAT_TIMEOUT

### What are you suggesting?

Allow to configure the HEARTBEAT_TIMEOUT. A longer timeout can work around the heartbeat bug.

### What alternatives have you considered?

Make sure that the heartbeat can be sent.

**Comment by miherlosev** [comment]
Hi @allayli 

It looks like a TestCafe problem. Would please provide an example of your test case for which you want to increase HEARTBEAT_TIMEOUT?
