### ISSUE TITLE
Perform escaping of errors in templates

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#357]
While fixing #355, I've found that we are escaping [diff description in utils](https://github.com/DevExpress/testcafe/blob/master/src/client/core/utils/dom.js#L324), that are used by assertions and actions, and [step name in runner](https://github.com/DevExpress/testcafe/blob/master/src/client/runner/runner.js#L151). In order to fix #355, I will need to escape diffs in assertions, and `relatedSourceCode` on server side. So after that we will have escaping in 4 different places, 3 on a client, and 1 on the server.

According to @kirovboris ' [comment](https://github.com/DevExpress/testcafe/issues/127#issuecomment-152106511) and @inikulin 's [comment](https://github.com/DevExpress/testcafe/issues/127#issuecomment-152125060) we are doing escaping to avoid [breaking an error template](https://github.com/DevExpress/testcafe/blob/master/src/reporter/errors/format.js#L29) parser because we use HTML markup for errors.

So I'm curious, why wouldn't we do this just right in [error templates](https://github.com/DevExpress/testcafe/blob/master/src/reporter/errors/templates.js), because here we are forming HTML markup for an error and here we can escape all including data?
\cc @inikulin @AlexanderMoskovkin @kirovboris @helen-dikareva

**Comment by kirovboris** [comment]
The relatedSourceCode is always a string. We can't detect whether it's html or string with brackets on the templates side.

**Comment by inikulin** [comment]
@kirovboris Related source code is always a js-code. So we can always escape it before inserting into template (since template is HTML)

**Comment by AndreyBelym** [comment]
Just the fun fact: can you find a tag in an expression below? `parse5` can :)
```
ok(5<x-x>5)
```
Shame, no spoilers here, but tag is `<x-x>`.
What is more interesting, that it's a valid JS expression after all.

**Comment by kirovboris** [comment]
@inikulin, @AndreyBelym 
I agree. Let's implement html escaping in the templates.

**Comment by AlexanderMoskovkin** [comment]
I agree too

**Comment by inikulin** [comment]
@AndreyBelym Yap, any character except whitespace, `>` and `/` is perfectly valid in HTML5 tag name: https://github.com/inikulin/parse5/blob/master/lib/tokenizer/index.js#L767
