### ISSUE TITLE
 The string did not match the expected pattern in isomorphic fetch

### ISSUE THREAD

**Issue by midhun8454** [DevExpress/testcafe#3570]
am new to react,and am getting this error in fetch... Can you help me to resolve this

**Comment by midhun8454** [comment]
what response you guys need?

**Comment by LavrovArtem** [comment]
Thank you for bringing this to our attention. However, it's not quite clear how this 'react' inquiry is related to TestCafe. If you believe that it is related to TestCafe and it is an issue, please fill the bug template and update the description with full information about your problem, so we can examine it and put you on the right track.

If you simply want to ask a question, I recommend that you forward it on StackOverflow - an amazing platform for users to ask and answer questions. We try to keep the GitHub issue tracker for bugs and feature requests only.
