### ISSUE TITLE
Add Option to specify the maximum buffer size for the app

### ISSUE THREAD

**Issue by Patrick-Spiegel** [DevExpress/testcafe#3571]
### What is your Test Scenario?

When you try to serve a vue application for the e2e tests then you run quickly out of buffer space. The default size is around 200 KB which is definetly not enough. 

### What are you suggesting?

There should be a parameter like app-init-delay which should increase the maximumx buffer size of the started child process.

### What alternatives have you considered?

https://github.com/DevExpress/testcafe/issues/2119#issuecomment-364904277
On unix systems you can specify some parameters to suppress console output. On windows systems that does not work.

**Comment by mindaugas-acosta** [comment]
@Patrick-Spiegel what is the status of this issue? I currently have this exact problem. trying to serve vue app for testcafe and testcafe fails because maxBuffer exceeded.

**Comment by Patrick-Spiegel** [comment]
@mindaugas-acosta try  ```npm run serve > logs/vue.log 2>&1``` as start script

**Comment by AndreyBelym** [comment]
@mindaugas-acosta @mindaugas-acosta Thank you for using TestCafe. The cause of this issue is covered by #2857 and I've summarized available workarounds in [this comment](https://github.com/DevExpress/testcafe/issues/2857#issuecomment-474743251).

**Comment by mindaugas-acosta** [comment]
> @mindaugas-acosta try `npm run serve > logs/vue.log 2>&1` as start script

Hello @Patrick-Spiegel this helped to eliminate maxBuffer problem. Thank you very much! Appreciate your help sir.

Now the problem is that testcafe loads white screen instead of app and all tests are failing because of this?

Maybe you guys could point me to some direction where i could look at?

**Comment by AndreyBelym** [comment]
@mindaugas-acosta please consider submitting a [new bug report](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md). An example page that can be used to reproduce the problem will be very useful in this case.

You can also run TestCafe in the [Developer Mode](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--dev) and take a look at the Console tab in Chrome DevTools. Likely it will show an error message and stack trace.
