### ISSUE TITLE
Cookies are not persisted when navigating to next page

### ISSUE THREAD

**Issue by crhistianramirez** [DevExpress/testcafe#3574]
### What is your Test Scenario?
I am trying to login programatically by setting the cookies. So the general flow is i'll go to the login page, set the token in the cookies and then navigate to the homepage which should allow me to side-step the slow process of logging in via the UI
 
### What is the Current behavior?
Navigating to the home page clears any of the cookies I saved while on the login page
 
### What is the Expected behavior?
I should be able to have access to cookies on the home page that were set while on the login page
 
### What is your web application and your TestCafe test code?
Web Application: https://demo-internal-test.herokuapp.com
Test Code:
```typescript
import { Selector, ClientFunction } from 'testcafe';

const setCookies = ClientFunction(() => {
    document.cookie = 'mysuperawesomecookie=sadface';
});

const getCookie = ClientFunction(() => {
   return document.cookie;
});

const testPageUrl = 'https://demo-internal-test.herokuapp.com';

fixture`Cookies`
    .page(testPageUrl)
    .beforeEach(async t => {
        console.log('set cookies');
        await setCookies();
        console.log('get cookies on page: ' + await getCookie());
        await t.navigateTo(testPageUrl);
    });

test('Should have cookie on next page', async t => {
    console.log('get cookies after page:' + await getCookie());
});
```
</details>

### Steps to Reproduce:

1. Clone [repository](https://github.com/crhistianramirez/testcafe-bug-3574)
2. run `npm install`
3. run `npm start`
4. View logs and see that cookies on next page do not have `mysuperawesomecookie`
 
### Your Environment details:
 
* testcafe version:                   1.1.0
* node.js version:                    10.15.2
* command-line arguments:  testcafe chrome test.ts
* browser name and version: Chrome 73
* platform and version:           Windows 10
* other:

**Comment by Farfurix** [comment]
@crhistianramirez.

Hello. Thank you for providing the test repository.

Since you are using ["Adding history entries"](https://developer.mozilla.org/en-US/docs/Web/API/History_API#Adding_and_modifying_history_entries) in your [page](https://demo-internal-test.herokuapp.com) code, you need to specify the `Path` cookie parameter:
```js
document.cookie = 'mysuperawesomecookie=sadface; path=/';
```
Or you can change `testPageUrl` to https://demo-internal-test.herokuapp.com/login/.

Modified **test.ts**:
```js
import { Selector, ClientFunction } from 'testcafe';

const setCookies = ClientFunction(() => {
    document.cookie = 'mysuperawesomecookie=sadface; path=/';
});

const getCookie = ClientFunction(() => {
   return document.cookie;
});

const testPageUrl = 'https://demo-internal-test.herokuapp.com';
// const testPageUrl = 'https://demo-internal-test.herokuapp.com/login/'; // document.cookie = 'mysuperawesomecookie=sadface';

fixture`Cookies`
    .page(testPageUrl)
    .beforeEach(async t => {
        console.log('beforeEach. Set cookies');
        await setCookies();
        console.log('beforeEach. Get cookies:                  ' + await getCookie());
        await t.navigateTo(testPageUrl);
        console.log('beforeEach. Get cookies after navigateTo: ' + await getCookie());
    });

test('Should have cookie on next page', async t => {
    console.log('test. Get cookies:                        ' + await getCookie());
});
```

Result:
```
 Running tests in:
 - Chrome 72.0.3626 / Windows 10.0.0

 Cookies
beforeEach. Set cookies
beforeEach. Get cookies:                  demo_internal_redirectState=%7B%22name%22%3A%22home%22%2C%22params%22%3A%7B%22%23%22%3Anull%7D%7D; mysuperawesomecookie=sadface
beforeEach. Get cookies after navigateTo: demo_internal_redirectState=%7B%22name%22%3A%22home%22%2C%22params%22%3A%7B%22%23%22%3Anull%7D%7D; mysuperawesomecookie=sadface
test. Get cookies:                        demo_internal_redirectState=%7B%22name%22%3A%22home%22%2C%22params%22%3A%7B%22%23%22%3Anull%7D%7D; mysuperawesomecookie=sadface
```

**Comment by crhistianramirez** [comment]
You're a hero! Thank you very much @Farfurix

**Comment by Farfurix** [comment]
@crhistianramirez 

You're welcome :)
