### ISSUE TITLE
testcafe stuck with error "upstream connect error or disconnect/reset before headers"

### ISSUE THREAD

**Issue by gal432** [DevExpress/testcafe#3576]
### What is your Test Scenario?
 navigate to site

### What is the Current behavior?
before the test even starts, I'm getting "upstream connect error or disconnect/reset before headers" in the browser. no indicative error on the process. the test itself will stuck forever

### What is the Expected behavior?
No error / timeout in case of failure in setup the browser & exit failure

### Steps to Reproduce:
Statistic bug. should be run in loops to make this reproduce. I see it more often when I run the tests in CI (after I saw the tests got stucked in my CI server, I tunneled & connected to the chromium debugging port and saw this message)

Debug logs didn't help since its even before the tests starts. in the fixture level and I don't get any logs about it when DEBUG=* 

### Your Environment details:
* testcafe version: 1.1.0
* node.js version:10.14.2
* command-line arguments:  chromium:headless --no-sandbox /tests/e2e/tests/Tests/CITests/ --dev -r spec,xunit:/tests/e2e/tests/ui-test-results.xml
* browser name and version: chromium / chrome 73
* platform and version: Mac, Linux and testcafe docker image

**Comment by gal432** [comment]
When it happened not in chrome headless:
![image](https://user-images.githubusercontent.com/9626302/54536148-cde98280-4998-11e9-8360-aa331e05ef9e.png)
![image](https://user-images.githubusercontent.com/9626302/54536187-e3f74300-4998-11e9-9300-5ed6baf90550.png)

**Comment by gal432** [comment]
From chrome headless:
![image](https://user-images.githubusercontent.com/9626302/54597579-74885e80-4a3f-11e9-8e0b-6e73cbd36258.png)

**Comment by AlexKamaev** [comment]
We didn't face such an issue and it does not look related to TestCafe. I think it's somehow related to your project/environment. So, please provide us with a working example which demonstrates the issue.

**Comment by gal432** [comment]
I'm sad to say that you right. its indeed coming from my env. I don't sure why (envoy with multiple proxies).
but for some reason when the testcafe gets this 503 page everything is stuck. No matter where I put a code to patch this problem (before / after in fixture, in the test itself),  it will stuck the test process forever. any idea how I can patch this for now?

**Comment by AlexKamaev** [comment]
Since the issue can be related to https://github.com/DevExpress/testcafe-hammerhead/issues/1961 as you mentioned, I think it's better to wait for the fix. So I'll close this issue as duplicate. If the fix of DevExpress/testcafe-hammerhead#1961 does not help, feel free to open a new issue with an example providing detailed information.
