### ISSUE TITLE
localStorage is no longer being store correctly in hammer head

### ISSUE THREAD

**Issue by dbschwartz** [DevExpress/testcafe#3580]
### What is your Test Scenario?

localStorage is persisted when going to a new tab  via the hammerhead-storages mechanism
 
### What is the Current behavior?

When going to a new tab in TestCafe v1.0.0 or above, local storage data is no longer available once `window.open(url, '_blank')` occurs whereas it happened previously.  It looks llike hammerhead|storages-sandbox-temp is not being transferred to hammerhead|storage-wrapper| as it was in TestCafe v0.23.3 and below
 
### What is the Expected behavior?

Data in localStorage is persisted in a new link.
 
### What is your web application and your TestCafe test code?

I am trying to make a reproducible demo as I cannot share the actual test because it is not a public site.  It is difficult to reproduce since it seems to only happen in one particular use case while it worked in others (it worked previously in Test Cafe versions <= 0.23.3).  When a link is clicked to open a new tab the localStorage mechanism doesn't work properly. The hammerhead|storages-sandbox-temp value becomes the key of the value pair it had (so if hammerhead|storages-sandbox-temp  was `foo: {bar: 'baz'}`  then it becomes foo.  At this point ordinarily the `foo: {bar: 'baz'}` would be put into the hammerhead|storage-wrapper| property in localStorage but this doesn't happen for some reason.
 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:     1.1.0              
* node.js version:          8.10.0          
* command-line arguments:  chrome -e 
* browser name and version: chrome 
* platform and version:   Windows 10       
* other:

**Comment by AlexKamaev** [comment]
I've checked the behavior in a sample project and it works as expected. Please see the following example:

ls.html:
```HTML
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<div id="result">
</div>
<script>
    localStorage.setItem('myCat', 'Felix');

    document.getElementById('result').innerHTML = window.localStorage.getItem('myCat');

    localStorage.setItem('myCat', 'Tom');

    function redirect () {
        window.open('ls2.html')
    }

</script>

<a href="ls2.html" target="_blank">Open link</a>

<button onclick="redirect()">Click button</button>

</body>
</html>
```
ls2.html
```HTML
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

<div id="result">
</div>

<script>
    document.getElementById('result').innerHTML = window.localStorage.getItem('myCat');
</script>

</body>
</html>

```
Tests
```JS
import { Selector } from 'testcafe';

fixture`fixture`
    .page`../pages/ls.html`;

test(`test1`, async t => {
    await t.expect(Selector('#result').innerText).eql('Felix');

    await t.click('a');

    await t.expect(Selector('#result').innerText).eql('Tom');
});

test(`test2`, async t => {
    await t.expect(Selector('#result').innerText).eql('Felix');

    await t.click('button');

    await t.expect(Selector('#result').innerText).eql('Tom');
});
```

I would really appreciate it if you reproduce the issue in a simple project. If you cannot share your project for security reasons, you can send all the details at support@devexpress.com
