### ISSUE TITLE
Property 'createLiveModeRunner' does not exist on type 'TestCafe'

### ISSUE THREAD

**Issue by honsq90** [DevExpress/testcafe#3581]
### What is your Test Scenario?

We have a programatic runner written in TypeScript and it seems that the interface definition is missing createLiveModeRunner so it fails to compile.

### What is the Current behavior?

TestCafe runner fails to compile.
 
### What is the Expected behavior?

TestCafe runner should compile as `createLiveModeRunner` is a new method.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```ts

import { default as createTestCafe } from "testcafe";

 createTestCafe("localhost")
  .then((tc: TestCafe) => {
    testcafe = tc;
    runner = environment.live ? testcafe.createLiveModeRunner() : testcafe.createRunner();
    return getTests();
  })


```
</details>

### Your Environment details:
 
* testcafe version:          1.1.0         
* node.js version:           8.12.0

**Comment by AlexKamaev** [comment]
Thank you for pointing this issue to us and for your PR. We'll have a look at it in the nearest future.

**Comment by AlexKamaev** [comment]
fixed in https://github.com/DevExpress/testcafe/pull/3582
