### ISSUE TITLE
RequestLogger: testcafe hangs when requesting JSON api

### ISSUE THREAD

**Issue by bstd** [DevExpress/testcafe#3591]
### What is your Test Scenario?
Test request responses from json api.
 
### What is the Current behavior?
Test hangs without error or timing out.
 
### What is the Expected behavior?
Error or timeout.
 
### What is your web application and your TestCafe test code?
one test file, requesting from http://www.mocky.io/v2

<details>
<summary>Your complete test code (or attach your test files):</summary>

/tests/api.spec.js 
```js
 import { RequestLogger } from 'testcafe';

//const apiUrl = 'http://www.mocky.io/v2/5c92309c320000e51c6bcdef'; // []
const apiUrl = 'http://www.mocky.io/v2/5c92542c320000e51c6bcf28'; // some entries
const apiLogger = RequestLogger(apiUrl);

// test api content
fixture('Test API - Headers')
	.page(apiUrl)
	.requestHooks(apiLogger);

test('response statusCode 200 ok', async (t) => {
	await t
		.expect(apiLogger.contains(record => record.response.statusCode === 200)).ok();
});
```
</details>

<details>
<summary>Your complete test report:</summary>
Nothing, test hangs indefinitely ("Test API - Headers"), browser windows stays open.
Same result when JSON response returns some entries.
<details>

### Steps to Reproduce:
1. npm init
2. default init (enter) except for test command: "testcafe"
3. npm i testcafe
4. put .testcaferc.json (see below) in project folder root
5. put api.spec.js in project /tests/ folder
6.. npm test
 
### Your Environment details:
 
* testcafe version:                   1.1.0
* node.js version:                    v10.15.3
* command-line arguments:  "npm test"
* browser name and version: Chrome 72
* platform and version:          Windows 10.0.0
* other:    .testcaferc.json:     {
	"browsers": [ "chrome" ],
	"src": [ "./tests/" ],
	"reporter": [
		{
			"name": "spec"
		}
	]
}

**Comment by AlexKamaev** [comment]
TestCafe requires the `page` method argument to be an url to an existing webpage, not to JSON or smth like that. This requirement  is based on the fact that TestCafe injects some scripts into the target page.
The easiest way to overcome the issue is  to create a simple page just with one `script` tag. Please see the following example:
```HTML
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title></title>

    <script type="text/javascript" src="http://www.mocky.io/v2/5c92542c320000e51c6bcf28"></script>
</head>
<body>
</body>
</html>
```
JS:
```JS
import { RequestLogger } from 'testcafe';

const apiUrl    = 'http://www.mocky.io/v2/5c92542c320000e51c6bcf28'; // some entries
const page      = '../pages/index.html';
const apiLogger = RequestLogger(apiUrl);

// test api content
fixture('Test API - Headers')
    .page(page)
    .requestHooks(apiLogger);

test('response statusCode 200 ok', async (t) => {
    await t
        .expect(apiLogger.contains(record => record.response.statusCode === 200)).ok();
});
```
As a possible solution, you can also consider using [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) in combination with [ClientFunctions](https://devexpress.github.io/testcafe/documentation/test-api/obtaining-data-from-the-client/#creating-client-functions)
