### ISSUE TITLE
 t.getBrowserConsoleMessages is not a function

### ISSUE THREAD

**Issue by oreporan** [DevExpress/testcafe#3597]
### What is your Test Scenario?
I'd like to print all browser logs after each test/fixture. However I keep getting  
` t.getBrowserConsoleMessages is not a function`
I'm using testcafe version `1.0.0`

### What is the Current behavior?
Fails due to function not existing  

### What is the Expected behavior?
Will get the browser console messages
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 fixture`Some Fixture`.page`http://${APPNAME}:3000`
    .after(async t => {
        const {warn, error, info} = await t.getBrowserConsoleMessages();
        console.warn('Warnings From the Browser \n', warn);
        console.warn('Errors From the Browser \n', error);
        console.log('Info Logs from the Browser \n', info);
    })
```
</details>

<details>
<summary>Your complete test report:</summary>

```
   1) - Error in fixture.after hook -
      TypeError: t.getBrowserConsoleMessages is not a function
```
</details>
 
### Your Environment details:
 
* testcafe version:                   1.0.0
* node.js version:                    v8.9.4
* command-line arguments:  `testcafe --skip-js-errors --selector-timeout 30000 --assertion-timeout 30000 --quarantine-mode chrome ./tests/behaviour/web`
* browser name and version:  Chrome 72.0.3626
* platform and version:          Mac OS X 10.13.6

**Comment by Farfurix** [comment]
@oreporan 

Hello.

Unlike [test hooks](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#test-hooks),[ fixture hooks](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#fixture-hooks) are executed between test runs and do not have access to the tested page. Thus, it is impossible to call `t.getBrowserConsoleMessages` from `before`/`after` fixture hooks.

If you need to access console messages for each test, you may consider using the `fixture.afterEach` method. Check this sample code:

```js
fixture `getBrowserConsoleMessages`
    .page `https://google.com`
    .afterEach(async t => {
        const { error } = await t.getBrowserConsoleMessages();

        await t
            .expect(error.length).eql(1)
            .expect(error[0]).ok();
    });

test('test 1', async t => {
    await t
        .eval(() => {
            console.error('my error');
        });
});

test('test 2', async t => {
    const { error } = await t.getBrowserConsoleMessages();

    await t
        .expect(error.length).eql(0); // There are no errors from "test 1"

    await t
        .eval(() => {
            console.error('my error');
        });
});
```

**Comment by oreporan** [comment]
Thanks
thats a bit frustrating seeing as that I have tens of test files, all with a global beforeFixture/afterFixture, and I would like to add this on a global level.

Any other way to do it? Is there some `afterEachTest` hook I can use?

**Comment by AndreyBelym** [comment]
The `fixture.afterEach` hook is declared once in the same way as the `fixture.after` hook and is executed after each test in a fixture. Take a look at the [example](https://github.com/DevExpress/testcafe/issues/3597#issuecomment-475674877).
