### ISSUE TITLE
if first if statement is false, control dont pass to the else if; it directly fails

### ISSUE THREAD

**Issue by tabassumSpringernature** [DevExpress/testcafe#3599]
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by tabassumSpringernature** [comment]
code:
await t.wait(3000);
	if(await t.expect(winSize.innerHTML).contains("player__maximized"))
	{
		await t
		.click(playerWindowToggleButton)
		.expect(winSizeOnOpen).contains("player__windowed");
		console.log("player window is in player__windowed mode");
	}

	else (await t.expect(winSize.innerHTML).contains("player__windowed"))
	{
		await t
		.click(playerWindowToggleButton)
		.expect(winSizeOnOpen).contains("player__maximized");
		console.log("player window is in player__maximized mode");
	}

**Comment by Farfurix** [comment]
@tabassumSpringernature 

The information you provided is insufficient to determine the cause of the problem you are experiencing. Please fill all issue template sections and provide all details requested there.
This will help us better understand your scenario and provide you with an appropriate solution.

**Comment by dlangerenken** [comment]
I think what @tabassumSpringernature  is trying to achieve is:
```typescript
const foo = Selector('.foo')
const bar = Selector('.bar')
if (t.expect(foo.exists).ok()) {
// deal with foo
} else if (t.expect(bar.exists).ok()) {
// deal with bar
}
```
However, as far as I understand the semantics, t.expect(..).ok() will do an assertion and therefore fail if foo does not exist.

What you could do is:
```
if (t.expect(await foo.exists).ok()) {
// deal with foo
} else if (t.expect(await bar.exists).ok()) {
// deal with bar
}
```
But here you should ensure that foo is correctly loaded since the waiting mechanism from testcafe does not kick in.

**Comment by LavrovArtem** [comment]
The assertion is not a function that returns some boolean value. You can use `if (await foo.exists)` condition if you want to check if an element exists.
