### ISSUE TITLE
cdpPort and concurrency

### ISSUE THREAD

**Issue by dlangerenken** [DevExpress/testcafe#3600]
I don't think this question would fit onto stackoverflow so I'll post it here.

When I run my tests using `chrome:headless:cdpPort=9222 --disable-dev-shm-usage --no-sandbox` I see a lot of flakyness in some of my tests when run in concurrency-mode (e.g. up to 8 threads).

However, if  I change it to `chrome:headless --disable-dev-shm-usage --no-sandbox` and let testcafe assign the cdpPort automatically, I don't see this flakyness.

This brings me to my question: Does manual assigning of the cdpPort even make sense in concurrency-mode? If I run `netstat -ltnp` during those testcafe runs, I can see that testcafe is reserving up to 8 extra ports when I run it without specifying the cdpPort. I assume the cdpPort should NOT be shared across different threads?

1. If so, this definitely should be documented since I just found out by accident.
2. How do we know what CDP port is in use? Can we get this information in `t` ? In my scenario, I need to know it since I download a file based on the suggestions here: https://github.com/DevExpress/testcafe/issues/3127

**Comment by miherlosev** [comment]
Hi @dlangerenken 
 
It's a TestCafe problem. In your example, TestCafe runs 8 browser instances with the same `cdp` port.
I guess we should raise an error if TestCafe is running with the specified `cdp` port in concurrency mode (we also need to check other machine specific settings).
 
At present, there is no public API to determine what `cdp` port is used by the browser instance. This information will not be necessary once we fix #3127.
