### ISSUE TITLE
Hide banner when shooting a video

### ISSUE THREAD

**Issue by claustres** [DevExpress/testcafe#3603]
### What is your Test Scenario?

We are using testcafé to generate videos from tests, these videos also serve the purpose of application usage samples or tutorials.

### What are you suggesting?

The testcafé banner hides part of the video, it should be great to be able to hide it on request during the video shot.

### What alternatives have you considered?

If the banner is required as a support to the dissemination of the open source testcafé solution maybe it can automatically hides after a couple of seconds or its size/position should at least be customized.

**Comment by miherlosev** [comment]
Hi @claustres 

Thank you for your suggestion. We will consider this issue on planning the next development sprint.
