### ISSUE TITLE
JavaScript error details: SyntaxError: Unexpected token < is seen in TestCafe

### ISSUE THREAD

**Issue by ijkelvinrambacud** [DevExpress/testcafe#3604]
### What is your Test Scenario?
Just running through a login page and a JS Error occurs using TestCafe Studio
 
### What is the Expected behavior?
JS Error should be skipped when running a single test in TestCafe Studio
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                    v0.4
* node.js version:                    
* command-line arguments:   N/A (I'm using the Studio)
* browser name and version:  Chrome
* platform and version:           MacOS
* other:

**Comment by miherlosev** [comment]
Hi @ijkelvinrambacud 
 
In this repository we process only bugs and enhancements for TestCafe (not TestCafe Studio). If you have questions about TestCafe Studio, please ask them in the [Support Center](https://www.devexpress.com/Support/Center/Question).
 
TestCafe tracks unhandled JavaScript errors that occur on the tested page.
You can turn off this option in the [Run configuration](https://docs.devexpress.com/TestCafeStudio/400189/user-interface/run-configurations-dialog) dialog.
![image](https://user-images.githubusercontent.com/4133518/54995703-6a82d480-4fd8-11e9-852c-b8d53ee9a276.png)
