### ISSUE TITLE
useRole doesnt login in Docker GitlabCI

### ISSUE THREAD

**Issue by Avanti24** [DevExpress/testcafe#3608]
### What is your Test Scenario?
Run a test within a Docker image. Test in run on Chrome and Firefox headless mode.
It needs to first login to my application and then "waitForReact" and then run the test which simply verifies the react DOM.
 
### What is the Current behavior?
Currently the page does not go past LOGIN. it keeps coming back to Login even after doing "useRole" or simply performing login by using Selectors on the DOM
 
### What is the Expected behavior?
It should login after useRole and go to the redirected page, instead of being stuck at the Login page
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example): internal, cannot be shared

<details>
<summary>Your complete test code (or attach your test files):</summary>

```

const getLocation = ClientFunction(() => document.location.href.toString());

export const TesterOne = Role(tiLoginURL, async t => {
    await t
        .typeText(loginPg.username, "abc")
        .typeText(loginPg.password, "def")
        .click(loginPg.submit);
}
);


fixture`01 TI E2E - React DOM Verification`
    .page`${tiSearchURL}`
    .beforeEach(async t => {

        await t.maximizeWindow();
      //  await t.useRole(TesterOne);
        await t
            .typeText(loginPg.username, "abc")
            .typeText(loginPg.password, "def")
            .click(loginPg.submit);

        console.info("After use role");
        console.info(await getLocation());

    });

test.only("01_01 Check VirtualBoard", async t => {
    console.info("In the test");
    console.info(await getLocation());
    await waitForReact();
    await t
        .click(ReactSelector("ThreatLevel").find(".level-2"))
        .typeText(ReactSelector("Name"), "testcafe test")
        .click(ReactSelector("CheckboxGroup").find(".input-checkbox").withAttribute("data-scope", "test"))
        .typeText(ReactSelector("Description").find("textarea"), "testcafe test description")
        .click(ReactSelector("Restriction").find("label").withAttribute("value", "private"));
});

```
 

</details>

<details>
<summary>Your complete test report:</summary>

```
 Running tests in:
 - HeadlessChrome 73.0.3683 / Linux 0.0.0

After use role
http://APP/login?goto=%2Fpage%2Finvestigate_manager
In the test
http://APP/login?goto=%2Fpage%2Finvestigate_manager
 ✖ 01 TI E2E - React DOM Verification - 01_01 Check VirtualBoard

   1) ClientFunction execution was interrupted by page unload. This
      problem may appear if you trigger page navigation from
      ClientFunction code.

      Browser: HeadlessChrome 73.0.3683 / Linux 0.0.0

         1622 |                stopChecking = true;
         1623 |
         1624 |                reject('waitForReact: The waiting timeout
      is exceeded');
         1625 |            }, checkTimeout);
         1626 |        });
       > 1627 |    }, { dependencies: { checkTimeout } })();
         1628 |};

         at waitForReact

   (/tmp/uitest/node_modules/testcafe-react-selectors/lib/index.js:1627:43)
         at <anonymous> (/tmp/uitest/test.js:39:11)



 1/1 failed (9s)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ testcafe:test: `testcafe -e -u --dev --reporter list --color 'chrome:headless --disable-dev-shm-usage --no-sandbox' /tmp/uitest/test.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ testcafe:test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jenkins/.npm/_logs/2019-03-26T14_16_55_276Z-debug.log
```
</details>

<details>
As a note, it works swiftly and successfully on my local system(Windows with FF or Chrome, headless or not)
</details>

### Steps to Reproduce:

1. I run it as a npm script 

```
 "testcafe:test": "testcafe -e -u --dev --reporter list --color 'chrome:headless --disable-dev-shm-usage --no-sandbox' /tmp/uitest/test.js",
 ```

2. Using Firefox just gives the error 

```
After use role
http://APP/login?goto=%2Fpage%2Finvestigate_manager
In the test
http://APP/login?goto=%2Fpage%2Finvestigate_manager
ERROR The Firefox 60.0.0 / Linux 0.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.

Type "testcafe -h" for help.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ testcafe:test: `testcafe -e -u --dev --reporter list --color 'firefox:headless' /tmp/uitest/test.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ testcafe:test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jenkins/.npm/_logs/2019-03-26T10_14_37_132Z-debug.log
```

### Already tried

I have tried with useRole OR manually logging in
adding waits before useRole, after useRole
trying to force reload using a ClientFunction after the useRole, as i had seen a suggestion on one of the tickets
```
const reloadPage = new ClientFunction(() => location.reload(true));
```
4. Increasing pageload timeout

### Your Environment details:

firefox : Mozilla Firefox 60.5.1
google-chrome: Google Chrome 73.0.3683.75
node : v10.15.2
testcafe : 1.1.0
testcafe-react-selectors: 3.1.0
platform : Debian 9

**Comment by AndreyBelym** [comment]
I understand that the issue can be reproduced without using a `Role` just by executing required actions in a test directly. If it is, TestCafe could have problems with simulating actions on your website. Could you please provide a page that can be used to reproduce the problem?

You can also try to decrease the [test speed](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--speed-factor), or add a `t.wait` action after each login step.

**Comment by Avanti24** [comment]
I have tried reducing the test speed and add t.wait before or after useRole, still doesn't work. 
I could solve it by doing a **2nd authentication in the first test of my first fixture**. Thereafter, no test or fixture needed any further authentication. All the redirections happened normally.

THIS SOLUTION:

1. **works in CI** : with --disable-dev-shm flag in **Chrome**
2. **doesn't work in CI : with Firefox**
3. **doesn't work in local,** because in local the useRole is enough and the 2nd authentication is not needed

Do you know of any way to handle the flag in FF. I am now almost sure this is happening because of memory issues.

```
//FIXTURE 01
fixture`01`
    .beforeEach(async t => {
        await t.maximizeWindow();
        await t.setTestSpeed(0.8);
        await t.useRole(TesterOne); // use Role in before each
    });

//FIXTURE 01 TEST 01
test("01_01", async t => {

    await t.navigateTo(tiInvestMgrURL) // this first navigateTo redirects to login page again
        .expect(getLocation()).contains("login")
        .expect(getLocation()).contains("pagename");

// doing a 2nd authentication in 1st test
    await t
        .typeText(loginPg.username, "aa")
        .typeText(loginPg.password, "aa")
        .click(loginPg.submit).expect(getLocation()).notContains("login");
});
test("01_02", async t => {
// no need for authentication anymore
    await t.navigateTo(tiInvestMgrURL).expect(getLocation()).contains("pagename");
});

//FIXTURE 02
fixture`02`
    .beforeEach(async t => {
        await t.maximizeWindow();
        await t.setTestSpeed(0.8);
        await t.useRole(TesterOne); // use Role in before each
    });

//FIXTURE 02 TEST 01
test("02_01", async t => {
//this navigateto doesnt need another login, it is now always authenticated
    await t.navigateTo(tiHomeURL).expect(getLocation()).contains("index");

});
```

**Comment by Farfurix** [comment]
@Avanti24,

Hello. 
I have not found a similar flag in Firefox. It looks like you need to set up the /dev/shm size in your CI environment, but I cannot help much here. It is better to search for this in GitLab CI documentation.

It is still not clear why the issue may occur and how we can reproduce it. As my colleague mentioned at https://github.com/DevExpress/testcafe/issues/3608#issuecomment-477214586, it will be of great help if you reproduce the issue on some public site and share its URL and needed credentials. Or, could you prepare a sample project that demonstrates the issue?
