### ISSUE TITLE
Different behavior of IE11 and chrome. Selectors with shadowRoot are undefined in IE11

### ISSUE THREAD

**Issue by jackblackCH** [DevExpress/testcafe#3618]
- IE11 -> error: `TypeError: Unable to get property 'shadowRoot' of undefined or null reference`
- Works in Chrome.

Test code:
```
test('Should click on a custom element and find and click on it's custom button', async t => {
  const dropdownButton = Selector(() =>
    document
      .querySelector('my-main-element') // an element with a shadowDOM
      .shadowRoot.querySelector('my-child-dropdown') // an element with a shadowDOM
      .shadowRoot.querySelector('.js-dropdown__toggle') // a normal element 
  );
  await t.click(await dropdownButton());
  await t.debug();
```

**Comment by AndreyBelym** [comment]
IE11 doesn't support HTML templates and Shadow DOM:

 - [Can I use... HTML Templates](https://caniuse.com/#feat=template)
 - [Can I use... Shadow DOM v1](https://caniuse.com/#feat=shadowdomv1)

If your page uses some polyfill library for IE11, please provide an example page built with this library.
