### ISSUE TITLE
Bug eval when getting client width on specific element

### ISSUE THREAD

**Issue by dirkrooijakkers** [DevExpress/testcafe#3619]
### What is your Test Scenario?
Testing a React application. 
Using eval function to get client width.

### What is the Current behavior?
Selector's are working, function is working, but on this specific element, since the latest build, there is one component that does not give access to it anymore through the eval function.
Developers have no clue what this might be. Used console log to test if the objects are working and printing whatever i want, and objects are recognized everywhere except inside the eval function on this specific element.

Unfortunately, i cannot share the component right here (i know, makes it a lot harder)...
 
### What is the Expected behavior?
Give me the client width
 
### What is your web application and your TestCafe test code?
```
export async function getClientWidth (selector: any) {
  const S = selector
  const width = await t.eval(() =>
    S().clientWidth, {
     dependencies: { S }
  });

  return width
};

import * as u from '../../util/functions';

test('Testcase', async (t) => {
     await t.expect(
     await u.getClientWidth(s.viewportParent))
     .eql(await u.getClientWidth(s.graphParent));
});

```

<details>

This used to work. With the same conditions. But something is off after the latest build. 
Developers don't know, so i'm hoping there is some information you can give me to find out what's going on.

</details>

 
### Your Environment details:
 
* testcafe version:                   1.1.0
* node.js version:                    10.14.2
* browser name and version:  Chrome 73.0.3683
* platform and version:           Windows 10.0.0

**Comment by AlexKamaev** [comment]
It's difficult to determine the cause of the issue based only on this information.
I tried to reproduce the issue on the sample project, however, it all works as expected. Please see the following example::
```HTML
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title></title>

    <style>
        #t1, #t2 {
            width: 300px;
            height: 300px;
            border: 1px solid black;
        }
    </style>
</head>
<body>

<div id="t1"></div>
<div id="t2"></div>

</body>
</html>
```
```JS
import { Selector } from 'testcafe';

fixture `fixture`
    .page `../pages/index.html`;

async function getClientWidth (t, selector) {
    const S = selector

    const width = await t.eval(() =>
        S().clientWidth, {
        dependencies: { S }
    });

    return width;
};

test('Testcase', async (t) => {
    await t.expect(
        await getClientWidth(t, Selector('#t1')))
        .eql(await getClientWidth(t, Selector('#t1')));
});
```
Since you're unable to share your project here, you can send it at support@devexpress.com. Or you can modify my example to reproduce the issue.
