### ISSUE TITLE
File Upload function does not send the type of the file to the server

### ISSUE THREAD

**Issue by asharmab** [DevExpress/testcafe#3620]
File upload is not sending the Type of file because of which the file is not getting uploaded in the under test application
### What is your Test Scenario?
I am trying to do automation of an application which deals in uploading and managing the images.  

### What is the Current behavior?
The issue is that when I upload the file manually the 'key' sent in the Request Payload has an appended filetype with it but when I upload the image with Testcafe the 'Key ' sent in the Request payload does not contain the filetype.

Eg: 
The Key in Payload is : 4fdgjshfh643129 when Sent through testcafe
The Key in Payload is : 4fdgjshfh643129.jpg when Sent manually

Because of this the uploaded file is always corrupted as the filetype was not identified by the application and thus application names every such file without filetype as 'misc_data' which is unopenable

**_RequestPayload sent when image uploaded via testcafe:_**
![image](https://user-images.githubusercontent.com/36713542/55180380-b9e71300-5146-11e9-83ee-832ea0430168.png)

**_RequestPayload sent when image uploaded manually:_**
![image](https://user-images.githubusercontent.com/36713542/55180700-5a3d3780-5147-11e9-8cc8-7fb0d9359bfd.png)

### What is the Expected behavior?
I expect the upload function from testcafe should work exactly same as that it works when the file is uploaded manually . The difference in request Key sent in the payload when uploaded via testcafe is causing the issue.
 
### What is your web application and your TestCafe test code?
My web application uploads the file with its metadata and manages its and helps user to edit and work with the uploaded files/images. Following is the code I used:

 .setFilesToUpload(attach.browseButon,constant.ImageArray[1].path)
 

.
 
### Your Environment details:
 
* testcafe version:                 1.1.0
* node.js version:                  v8.9.1
* browser name and version: Chrome 73
* platform and version:         macOs Sierra Version 10.12.6

**Comment by AlexKamaev** [comment]
We didn't face any issues similar to this one, so we need to research it in detail. Could you please provide us with your project or prepare a sample which reproduces the behavior you described? It will help us determine the cause of the issue.

**Comment by asharmab** [comment]
My application use S3FineUploader for uploading the assets. The issue seems to be that the S3fineuploader does not identify the file when File is sent via testcafe thus the key is sent without filetype. Please let me know how can I help you to resolve this.

**Comment by Farfurix** [comment]
@asharmab 

Hello,

Would you please prepare a sample project that illustrates your working scenario in action?
This will help us investigate the issue on our side and provide you with an appropriate solution.
