### ISSUE TITLE
Try to pass strings with spaces to a method

### ISSUE THREAD

**Issue by jkilliananaplan** [DevExpress/testcafe#3621]
### What is your Test Scenario?
I want to paginate until a specific taskname with spaces is found on the page
For example:
taskname='This has spaces'
 
### What is the Current behavior?
If there are no spaces in the taskname, it is found. For example taskname='NoSpacesInTaskName1234'
 
### What is the Expected behavior?
Paginate until the taskname is on the page and click on it.
 
### What is your web application and your TestCafe test code?
This is the method I am trying to use
```
   async clickNextPageFindTask(taskname) {
        if (!taskname && (taskname !== 0)) {
            throw new Error(taskname);
        }
        console.log(taskname);
        while (!await this.taskTableTaskNameText.withText(taskname).exists) {
            await t
                .click(this.taskPaginationComponent.nextPageButton);
        }
        if (await this.taskTableTaskNameText.withText(taskname)); {
            await t
                .click(this.taskTableTaskNameText.withText(taskname))
                .click(this.processTasksGuidePageModel.commonTaskGuideComponent.taskTabRowComponent);
        }
    }
```
 
Your website URL (or attach your complete example):
This is my test:
```
test('Paginate until task is found', async t => {
    let taskname = 'Step 1 Try to reassign'
    await loginPageModel.login(user.email, user.password);
    await workflowGlobalNav.clickAppMenuItem("Tasks")
    await processTasksListPageModel.clickNextPageFindTask(taskname);

    await processTaskGuidePageModel.submitAllTasks('Next')
    await t.click(processTaskGuidePageModel.commonTaskGuideComponent.submitCompleteTaskButton)
    await t.click(processTaskGuidePageModel.returnToTaskListButton)
})
```

 
* testcafe version:    1.0.1     
* node.js version:   v8.14.0

**Comment by AlexKamaev** [comment]
This code seems to be valid. Without a working project I can only suppose that spaces are different in your test code and on your web page. I mean that on your page `&nbsp;` symbols, which are not equal to usual spaces, can be used. Please check this assumption. If it does not help, provide us with a sample that demonstrates the issue or the url to your project.

**Comment by jkilliananaplan** [comment]
I discovered a solution.  If I pass my taskname parameter as follows:
 await processTasksListPageModel.clickNextPageFindTask(`${task}`);

instead of  await processTasksListPageModel.clickNextPageFindTask(taskname);

-- and --
My task name on my page is unique enough.
The method works.

This taskname was found:
let task = ‘Step 1 Propose Good?’
But this one was not found:
let task = ‘Step 1 Try to reassign’

I have many tasks on the page that start with 'Step 1...'
So I am not sure if TestCafe or node can't determine uniqueness up to a certain length of a text string or if there is some other issue.

I will use my solution, and make sure I have uniqueness in my text strings for now.
Thank you.
You can close this issue if you like.
