### ISSUE TITLE
-app not working for "ng serve" or "yarn start"

### ISSUE THREAD

**Issue by mledour** [DevExpress/testcafe#3626]
### What is your Test Scenario?
A localhost served angular app
 
### What is the Current behavior?
The app is not started so the tests fail
 
### What is the Expected behavior?
It should start the app then launch the tests.
The test work correctly when i start the app then the tests in another console.

I'm using the --app --app-init-delay options

`"e2e": "testcafe chrome:headless e2e/**/**.spec.ts --app \"yarn start\" --app-init-delay 4000"`

 I get this error 

   1) - Error in fixture.beforeEach hook -
      An error occurred in ClientFunction code:

      Error: Cannot find Angular in development mode.
 
### Environment details:
 
* testcafe version:                   1.1.0
* node.js version:                    11.10.0
* command-line arguments:  testcafe chrome:headless e2e/**/**.spec.ts --app "yarn start" --app-init-delay 10000
* browser name and version:  Chrome 73.0.3683.86
* platform and version:          macOS 10.14, Windows 10, Linux

**Comment by Meemaw** [comment]
I have found --app argument not working as one would expect. I am using the following command and it works fine:

`"e2e": "BROWSER=none yarn start 2>&1 > /dev/null & wait-on http-get://localhost:3000 && testcafe chrome:headless src/test/e2e --hostname 127.0.0.1"`

**Comment by Farfurix** [comment]
@mledour 

Hello.

Could you please try to increase your `app-init-delay` delay? I tried to run some "hello world" example and all tests were successful with the `--app-init-delay 15000` value.
If this issue is still present, could you please provide us with a simple example that demonstrates it?

**Comment by mledour** [comment]
Ok thank's I got it working but I think is not a reliable solution as it could not work anymore as the app is growing..
Maybe an implementation like npm wait-on. Listening on specific url:port with an options like --app-wait-on-url "localhost:4200" would be more reliable.

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. I think it will be useful to provide a way to delay tests until a tested app can respond to requests. I've created a feature suggestion for it: https://github.com/DevExpress/testcafe/issues/3636, please check it for a workaround and don't forget to add 👍  to it 😄

**Comment by mledour** [comment]
Hi Andrey

Thank's. 👍added ;-)
