### ISSUE TITLE
SyntaxError: 'super' keyword unexpected here

### ISSUE THREAD

**Issue by snehalka** [DevExpress/testcafe#3630]
### What is your Test Scenario?
I would like to launch my web application and click on few web elements.
 
### What is the Current behavior?
Doesn't load the site and comes up with the blank page.
 
### What is the Expected behavior?
It should load the web application and should perform the further actions.
 
### What is your web application and your TestCafe test code?
https://www.volkswagen.de/app/konfigurator/vw-de/de
but I am using a local URL, with prod URL is working all fine.

Your website URL (or attach your complete example):

<details>
<summary>import { Selector } from 'testcafe';

fixture `New Fixture`
    .page `https://www.volkswagen.de/app/konfigurator/vw-de/de`;
    

test('Teste2eVW', async t => {
    await t
        .click(Selector('.vw_m641_system_notification_icon_wrapper').find('svg'))
        .click(Selector('[class^="icon icon--size-small icon--icon-name-thumbnails-l"]'))
        .click(Selector('[class^="icon icon--size-small icon--icon-name-thumbnails-s"]'))
        .click(Selector('span').withText('Der Polo').find('[class^="image image--full-width image-with-placeholder__im"][alt="image"][data-alt-img="car-tile-expandable-image"]'))
        .concat(items...: any)lick(Selector('span').withText('Comfortline').find('[class^="image image--full-width image-with-placeholder__im"][alt="image"][data-alt-img="car-tile-expandable-image"]'))
        .click(Selector('[class^="button button--primary button-group__item button-g"]').nth(1).find('span').withText('Zur Motorenauswahl'))
        .click(Selector('label').withText('1').nth(4).find('.radio-icon.engine-row__radio__icon'))
        .click(Selector('span').withText('Weiter zu Außenlackierungen'))
        .click(Selector('span').withText('Weiter zu Felgen'))
        .click(Selector('#GPJ6PJ6').find('.card-content-wheels__prices'))
        .click(Selector('span').withText('Weiter zum Interieur'))
        .click(Selector('div').withText('Style').nth(13).find('[class^="icon icon--size-small icon--icon-name-checkmark ch"]'))
        .click(Selector('button').withText('Abbrechen'))
        .click(Selector('span').withText('Weiter zu Ausstattungen'))
        .click(Selector('.checkbox.option-row-checkbox').find('[class^="icon icon--size-small icon--icon-name-checkmark ch"]'))
        .click(Selector('.option-row-price-icons').find('.action-icon.option-row-price-icons-icon'))
        .click(Selector('[class^="action-icon generic-lightbox__close-button generic"]'))
        .click(Selector('span').withText('Weiter zu Ihrem Wunschfahrzeug'))
        .click(Selector('button').withText('Technische Daten'))
        .click(Selector('[class^="action-icon generic-lightbox__close-button generic"]'));
});</summary>

 
### Your Environment details:
 
* testcafe version:   0.4.5               
* node.js version:                    
* command-line arguments:  testcafe chrome testscriptname
* browser name and version: Chrome 72.0.3626.121
* platform and version:          macOS  Mojave10.14.3

**Comment by LavrovArtem** [comment]
It looks like we need further clarification, as we did not release TestCafe v0.4.5. The latest version is "1.1.1-rc.2" and I cannot reproduce this problem using that version. Would you please clarify what product you are using: [TestCafe](https://devexpress.github.io/testcafe/) or [TestCafe Studio](https://www.devexpress.com/products/testcafestudio/)?  If you are working with TestCafe Studio, it is better to post this problem to our [Support Center](https://www.devexpress.com/Support/Center/Question). This our primary support channel for that product.  
Judging by the error message in the title, the problem might be related to our js parser that changes page code. If you can find a place in your page code where this error occurs (see the Sources tab in DevTools) and provide us with that piece of code, that would be very helpful.
