### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Michael2601** [DevExpress/testcafe#3635]
When I download file occurs this error
JavaScript error details:
TypeError: Cannot read property 'ETd' of undefined

Browser: Chrome 73.0.3683 / Windows 10.0.0

   at click)}C:\Users\...\TestCafeStudio\Examples\213.testcafe.js:13:10
   at test)}C:\Users\...\TestCafeStudio\Examples\213.testcafe.js:6:1
   at markeredfn)}C:\Users\...\AppData\Local\Programs\TestCafe Studio\resources\app.asar.unpacked\node_modules\testcafe\src\api\wrap-test-function.js:17:28
   at )}C:\Users\...\AppData\Local\Programs\TestCafe Studio\resources\app.asar.unpacked\node_modules\testcafe\src\api\wrap-test-function.js:7:5
   at fn)}C:\Users\...\AppData\Local\Programs\TestCafe Studio\resources\app.asar.unpacked\node_modules\testcafe\src\test-run\index.js:240:19
   at TestRun._executeTestFn)}C:\Users\...\AppData\Local\Programs\TestCafe Studio\resources\app.asar.unpacked\node_modules\testcafe\src\test-run\index.js:236:38
   at _executeTestFn)}C:\Users\...\AppData\Local\Programs\TestCafe Studio\resources\app.asar.unpacked\node_modules\testcafe\src\test-run\index.js:289:24

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. Please try to format your message using the [bug report](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md) and provide an example that can be used to reproduce the problem.
