### ISSUE TITLE
Simple requestlogger doesn't log anything at all

### ISSUE THREAD

**Issue by jcollum-nike** [DevExpress/testcafe#3637]
### What is your Test Scenario?
I want to log my requests to the server so I can troubleshoot a test in a docker container
 
### What is the Current behavior?
No logging output at all
 
### What is the Expected behavior?
I expect all requests to be logged 
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
const logger = RequestLogger(/.*/, {logResponseBody: true, logRequestBody: true});
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by LavrovArtem** [comment]
This information is not sufficient to find the cause of the issue. Could you please provide your environment details, full test code and a page or a small example so that we can reproduce it?

**Comment by jcollum-nike** [comment]
Sorry I somehow pressed enter before I was done with the ticket. 

I think the docs need a little clarification: this isn't really a logger in the normal sense (like Bunyan) it's a request collector. A logger will output a message at the time a log event happens. This logger doesn't do that, so it's poorly named. Maybe analyzer is a better word here. 

You have to log the requests separately after they have fired off: 

`  logger.requests.forEach((req) => console.log(req.request.url))` 

The docs do state this but it's like one sentence in the middle, very easy to miss.
