### ISSUE TITLE
ERROR Unable to establish one or more of the specified browser connections - Chromium on Docker

### ISSUE THREAD

**Issue by mannluong** [DevExpress/testcafe#3638]
### What is your Test Scenario?

 The test failed to run in Chromium when executed in Docker testcafe/testcafe base image (1.1.0 or 1.1.1-rc.1).

ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
### What is the Current behavior?

The test works correctly in Firefox but fails in Chromium.

Working
docker run -v c//tests:/tests -it testcafe/testcafe firefox --proxy proxy:8080 /tests/simple_test.js

Not Working
docker run -v c//tests:/tests -it testcafe/testcafe chromium --proxy proxy:8080 /tests/simple_test.js
### What is the Expected behavior?

Test should pass in Chromium  

### What is your web application and your TestCafe test code?

 
<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```simple_test.js

 import { Selector } from 'testcafe'; // first import testcafe selectors

fixture `Getting Started`// declare the fixture
    .page `https://devexpress.github.io/testcafe/example`;  // specify the start page


//then create a test and place your code there
test('My first test', async t => {
    await t
        .typeText('#developer-name', 'John Smith')
        .click('#submit-button')

        // Use the assertion to check if the actual header text is equal to the expected one
        .expect(Selector('#article-header').innerText).eql('Thank you, John Smith!');
});
```
</details>

### Steps to Reproduce:

1. docker pull testcafe/testcafe
2. docker run -v c//tests:/tests -it testcafe/testcafe chromium --proxy proxy:8080 /tests/simple_test.js 
3. ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
 
### Your Environment details:
 
* testcafe version:                   
1.1.0
* node.js version:                    
v10.15.3
* platform and version:          
Docker testcafe/testcafe base image (1.1.0 or 1.1.1-rc.1)

**Comment by behlrattan** [comment]
Facing same problem with the base image, works well on Firefox but not on Chromium.

**Comment by AndreyBelym** [comment]
Thank you for your inquiries. 

@mannluong, likely there is a problem with the proxy configuration. I can't reproduce it without a proxy. You can use instructions from the following article and troubleshoot Chrome by accessing its GUI:

[Running GUI apps with docker](http://somatorio.org/en/post/running-gui-apps-with-docker/) 

I tried the Windows section and it worked for me. I've used the following commands to start TestCafe and display Chrome's GUI:
```
docker run -it --rm -e DISPLAY=${YOUR HOST IP}:0 -v /host/path/to/tests:/tests --entrypoint sh testcafe/testcafe:rc

dbus-daemon --session --fork

testcafe 'chromium --no-sandbox' /tests
``` 

@behlrattan it's a too generic description, could you please create a [new bug report](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md) and provide some example in it? Also please try to troubleshoot Chrome by accessing its GUI.

**Comment by mannluong** [comment]
Thanks @AndreyBelym. I couldn't get GUI to work but it is working on headless Chromium now works for me on testcafe/testcafe:rc tag.
docker run -it --rm -v //c/tests:/tests -it testcafe/testcafe:rc chromium:headless --no-sandbox --proxy proxy:8080 /tests/simple_test.js

The current Firefox 62.0.0 on testcafe/testcafe:rc tag is buggy Is it possible to upgrade FireFox to 66.0.2 for the next release?

**Comment by AndreyBelym** [comment]
@mannluong, unfortunately, Firefox 62 is the latest available Firefox version for Alpine Linux: https://pkgs.alpinelinux.org/packages?name=firefox&branch=edge
