### ISSUE TITLE
ERROR The Chrome 73.0.3683 / Linux 0.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.  in Travis CI

### ISSUE THREAD

**Issue by jwineman** [DevExpress/testcafe#3642]
Hi,

Last week we started getting the following error in Travis:
```
ERROR The Chrome 73.0.3683 / Linux 0.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.
```
As far as I can tell nothing changed code wise to cause this, we were on `1.1.0`, I tried upgrading to `1.1.1`, still happened.  Is there anything obvious I'm missing that would cause the time out?

The timeout doesn't occur deterministically and passes occasionally.
### Your Environment details:
 
* testcafe version: 1.1.1 / 1.1.0                  
* node.js version: v8.15.1                   
* command-line arguments:`NODE_ENV=production npm run build && testcafe chrome ./src/__e2e__/tests/**/*.test.js -q -c 4 --app=\"npm run start\" --app-init-delay 2000`  
* browser name and version: Chrome 73.0.3683 / Linux 0.0.0 
* platform and version:          
* other:

**Comment by Farfurix** [comment]
@jwineman

Hello.
Unfortunately, this information is not sufficient to find the cause of the issue.

Could you please do the following?
1. Can you find the test that failed or does the test hang randomly?
2. Run your tests with the [concurrency mode](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-c-n---concurrency-n) and [quarantine mode](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-q---quarantine-mode) disabled. Does this help or does your test still hang randomly?
3. Try to localize the TestCafe version on which the failure does not occur using [this release list](https://github.com/DevExpress/testcafe/releases).

**Comment by jwineman** [comment]
Thanks, I wasn't sure how to debug further.  
1. The same test doesn't fail, different tests hang randomly.
2. I'll disable concurrency and quarantine mode. 
3. I'm assuming its not version specific since the tests were working on 1.1.0 and continued to break on 1.1.1 but I'll double check.

**Comment by jwineman** [comment]
Disabling concurrency showed our API was throwing 500s randomly.  This was because we have threaded code which was failing under high load, which only happened on travis where we run tests concurrently.  

Thank you for the help!

**Comment by Farfurix** [comment]
@jwineman 

You are welcome.
