### ISSUE TITLE
Custom offline plugin not working in V1.1.1

### ISSUE THREAD

**Issue by miteshsavani810** [DevExpress/testcafe#3643]
### What is your Test Scenario?
As per discussion on https://testcafe-discuss.devexpress.com/t/how-to-start-chrome-with-offline-mode-on/585/2, We have created offline plugin which redirect specific url to **Dead proxy** when plugin is getting called from automation test cases

	goOnlineOfflineToggle = ClientFunction(() => {
		window.onlineOfflineToggle();
	});
	
	test.only("Offline Checking", async t => {
		await t.eval(() => location.reload(true));
		await goOnlineOfflineToggle(); // or remove this step and disconnect internet at this step 
		await common.sleep(4000);
		await t.debug();
	});

So afterward we could verify offline feature/functionality using automation and all automation test cases were working perfectly on V1.1.0 but After upgrading to V1.1.1 All offline automation test cases are getting failed as application doesn't switched to offline mode at step **await goOnlineOfflineToggle();.**  As per my investigation, The plugin is loaded perfectly and  plugin function (which is responsible for enabling PAC script to redirecting URL to Dead proxy) is called from automation code. But I can see in Chrome's Network tab the blocker urls (all localhost) are still pointing to Actual resource (instead of Dead proxy) and Base application doesn't switched to Offline mode.
 
### What is the Current behavior?
PAC script is not working. See the below PAC script which is get enable when we call window.onlineOfflineToggle(); function.

	DEAD_PROXY = {
		mode: "pac_script",
		pacScript: {
			  data: "function FindProxyForURL(url, host) {\n" +
					"  if (url.includes('localhost')){\n" +
					"    return 'PROXY blackhole:80';}\n" +
					"  else return 'DIRECT';\n" +
					"}"
			}
	};
 
### What is the Expected behavior?
All localhost resource should redirect to Dead proxy **blackhole:80** on enabling offline plugin

### Your Environment details:
 
* testcafe version:                   1.1.1
* node.js version:                    v8.11.3
* browser name and version:  Chrome Version 73.0.3683.86
* platform and version:          Windows 10

**Comment by jiteshsojitra** [comment]
I'm facing the same issue, can TestCafe provide the solution for same? It was working fine till 1.0.0 but not after that.

**Comment by AlexKamaev** [comment]
It's difficult to determine the cause of the issue based on your description. Please provide us with working example which demonstrates the issue.
I also need to mention that TestCafe officially does not guarantee compatibility with extensions or PAC scripts, since TestCafe has its own proxy mechanism.

**Comment by miteshsavani810** [comment]
@AlexKamaev  I have created sample test script for you investigation. See the below test.js

// test.js file -- sample file

import { ClientFunction } from 'testcafe';

fixture Offline fixture // Add back quote
    .page('https://localhost:8080');

let goOnlineOfflineToggle = ClientFunction(() => {
    window.onlineOfflineToggle();
});

test.only("Offline Checking", async t => {
    await t.eval(() => location.reload(true));
    await goOnlineOfflineToggle(); // or remove this step and disconnect internet at this step 
    await t.wait(4000);
    await t.debug();
});

// End of file 

You have to pass chrome extension path while running this script so at step await goOnlineOfflineToggle(); , It calls plugin background method and block all localhost resources to Dead Proxy.

`testcafe "chrome --load-extension='<path of plugin>'" -e test.js`

Notes: I have attached custom offline plugin 
[offlineExtension.zip](https://github.com/DevExpress/testcafe/files/3047743/offlineExtension.zip)

**Comment by AlexKamaev** [comment]
@miteshsavani810 
I checked your extension and did not find any difference in behavior between TestCafe v1.1.0 and v1.1.1
I can confirm that your extension is executed but I did not reproduce the described behavior. None of the urls in the Network tab point to the "dead" proxy.
Could you please provide a full step by step instruction on how to reproduce the issue with a test project and test code with required assertions working in the 1.1.0 version and not working in the 1.1.1 version?

**Comment by miteshsavani810** [comment]
@AlexKamaev  I have created test environment. Please see below test case. i am still facing issue on testcafe V1.1.3

//test.js 

import { ClientFunction, Selector } from 'testcafe';

fixture `Offline fixture` // Add back quote
.page('https://suspicious-ptolemy-1b35ca.netlify.com');

const goOnline = ClientFunction( () => {
    window.onlineOfflineToggle('GO_ONLINE');
});

const goOffline = ClientFunction( () => {
    window.onlineOfflineToggle('GO_OFFLINE');
});

test.meta({ web: 'true' })("Offline Checking", async t => {
let statusSelector = Selector('span#status');
await t.wait(8000);
await t.expect(await statusSelector.textContent).contains('Online' , 'Verify status');
await goOffline(); 
await t.wait(5000);
await t.expect(await statusSelector.textContent).contains('Offline' , 'Verify status');
await goOnline(); 
await t.wait(5000);
await t.expect(await statusSelector.textContent).contains('Online' , 'Verify status');
});

// end of test.js file

run the testcase with below command
`testcafe "chrome --load-extension='<path of plugin>'" -e test.js`

see offline extension 
[offlineExtension.zip](https://github.com/DevExpress/testcafe/files/3118138/offlineExtension.zip)

**Comment by AlexKamaev** [comment]
We checked your extension on several machines and found that it works very unstable even without TestCafe. So it's very difficult to debug it and find the cause. Moreover, it looks like the extension changes proxy settings for all Chrome instances at the moment. So it can lead to unexpected problems during the test run. We recommend you not use it for testing purposes.
TestCafe does not guarantee compatibility with extensions, so we cannot research this issue in detail.
