### ISSUE TITLE
Click action performed twice

### ISSUE THREAD

**Issue by Farfurix** [DevExpress/testcafe#3645]
### Steps to Reproduce:
1. Run test (one click on checkbox):
```js
import { Selector } from 'testcafe';

fixture `enactjs sampler`
    .page `http://enactjs.com/2.3.0/sampler/`;

test('New Test', async t => {
    await t
        .setTestSpeed(0.75)
        .click(Selector('div').withText('Moonstone').nth(12).find('div').find('div').find('svg'))
        .click(Selector('[data-radium="true"]').nth(5).find('div').withText('CheckboxItem').nth(1))
        .switchToIframe(Selector('#storybook-preview-iframe'))
        .click(Selector('[class^="ToggleIcon-module__toggleIcon___2V_Lg Checkbox-mod"]')) // one click on checkbox
        .debug();
});
```
2. See "Action Logger":
![Capture](https://user-images.githubusercontent.com/30019338/55610644-0dcbaa80-578c-11e9-8914-1218d038f3a1.PNG)

### Additional info
`.click(Selector('[class^="ToggleIcon-module__toggleIcon___2V_Lg Checkbox-mod"]'))`:
1. First `onToggle` after `ClickAutomation.prototype._mousedown`.
2. Second `onToggle` after `ClickAutomation.prototype._click`.

Support Center ticket: T676301.
 
### Your Environment details:
 * testcafe version:                 1.1.1 [e26eebc]
* browser name and version: Chrome, Firefox, Internet Explorer 11, Edge
* platform and version:          Windows 10

**Comment by gferreri** [comment]
I'm also running into this. My test clicks on an ellipsis to expose a drop-down menu. The double-click causes the menu to disappear, thereby breaking the test. Is there a workaround? I can't go back to 1.0.0 because of another issue that causes weirdness with window.location
