### ISSUE TITLE
TestCafe from the official Docker image doesn't take --inspect-brk, --inspect and other V8 flags into account

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#3646]
### What is your Test Scenario?
Try to debug tests with Node Inspector in the official Docker image 
### What is the Current behavior?
The `--inspect` and `--inspect-brk` flags are ignored by TestCafe.
 
### What is the Expected behavior?
TestCafe should take `--inspect` and `--inspect-brk` flags into account and enable the Node.js debugger.

### Your Environment details:
 
* testcafe version:                   testcafe 1.1.1
* node.js version:                    10.12
* command-line arguments:  `--inspect-brk=0.0.0.0:9229 ...`
* browser name and version: 
* platform and version:          
* other:                                   use the `testcafe/testcafe` Docker image to reproduce

**Comment by jcollum-nike** [comment]
Quick turnaround! Thanks.
