### ISSUE TITLE
Window.document.body.scrollHeight retrieved with ClientFunction is not resetting between test runs

### ISSUE THREAD

**Issue by byrne-greg** [DevExpress/testcafe#3648]
I asked the question at [StackOverflow](https://stackoverflow.com/questions/55520225/how-to-reset-the-scrollheight-values-on-dom-elements-retrieved-using-clientfunct) and couldn't find an example of this explained in the docs or other issues, but the more I thought of it, the more I thought it could be a bug (just need to verify from a maintainer).

Rehasing the question asked on [StackOverflow](https://stackoverflow.com/questions/55520225/how-to-reset-the-scrollheight-values-on-dom-elements-retrieved-using-clientfunct), I have tests where I need to recognise the `scrollHeight` of each page. The `scrollHeight` will differ wildly between pages, depending on the page content.

Using the `ClientFunction`, I can retrieve the `window.document.body.scrollHeight` successfully and correctly within a test. However the weirdness starts when I test with multiple tests.

smallpageTest.js
```
fixture`smallpage`
test('smallpageTest', async t => {
  //...
  const getBodyHeight = ClientFunction(() => window.document.body.scrollHeight); 
  console.log(`${test} body.scrollHeight`, await getBodyHeight()); // 800px
 // ...
});
```
longpageTest.js
```
fixture`longpage`
test('longpageTest', async t => {
  //...
  const getBodyHeight = ClientFunction(() => window.document.body.scrollHeight); 
  console.log(`${test} body.scrollHeight`, await getBodyHeight()); // 1200px
  //...
});
```
When run in that order, it's fine. 
```
smallpageTest body.scrollHeight 800px
longpageTest body.scrollHeight 1200px
```

However when ran in reverse order (big to small), it seems the `scrollHeight` is set to the long side all the time
```
longpageTest body.scrollHeight 1200px
smallpageTest body.scrollHeight 1200px
```

My gut is that the test runner is holding onto the state at a global level. I call the tests using an `npm` test call (`testcafe -firefox:headless *Test.js`) rather than setting up any specific testcafe runner.
Adding `-c` for concurrency and passing 2 (as there are two tests) also solves this issue, but theorising only because each of the two tests are executed separately.

Any ideas how I can have the correct sizing independent of the order? Or perhaps a way to reset the scrollHeight between tests?

**Comment by Farfurix** [comment]
@byrne-greg.

Hello.

Please check the answer on [StackOverflow](https://stackoverflow.com/a/55536143/10448174). If you still have questions, let's continue discussing this issue there.
