### ISSUE TITLE
Error when I click on the "Unlock Page" button

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe#3652]
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example): http://todomvc.com/examples/vue/

Your complete test code (or attach your test files):

```js
fixture `Fixture`
    .page `http://todomvc.com/examples/vue/`;

test('Test', async t => {
    await t.debug();
});
```

### Steps to Reproduce:

1. Start the test
2. Open developer tools
3. Click the "Unlock Page" button
4. See the error `Uncaught TypeError: Cannot read property 'call' of undefined`
 
### Your Environment details:
 
* testcafe version:                   1.1.1
* node.js version:                    10.15.0
* command-line arguments:  testcafe chrome test.js
* browser name and version: Chrome 73.0.3683
* platform and version:          Windows 10.0.0

**Comment by jafin** [comment]
Seeing same error for internal page,  
test ran fine in 1.1, failing in 1.1.1  Click unlock on page returns 
`Uncaught TypeError: Cannot read property 'call' of undefined
    at hammerhead.js:7
`
Node: 10.15.3
Browser: Chrome 73
Platform: windows 10

**Comment by helen-dikareva** [comment]
We have 3 internal handlers for `mousedown` event: one `preventRealEventHandler` and two (somehow) `downHandler` from `StatusBar._bindClickOnce`. `preventRealEventHandler` works fine and the first `downHandler` calls `removeInternalEventListener`. That causes the error.
For me it looks like we should handle such a situation when one handler removes itself during execution.
