### ISSUE TITLE
Could not run under GitlabCi omnibus

### ISSUE THREAD

**Issue by guilhermecgs** [DevExpress/testcafe#3654]
### What is your Test Scenario?
Gitlab CI private **omnibus** installation with proxy server.

Does it have anything to do with the ports used? Because gitlab docker runner creates a container with no ports exposed, i guess...
 
### What is the Current behavior?
Could not run under [Option 1](https://devexpress.github.io/testcafe/documentation/continuous-integration/gitlab.html#option-1---use-testcafe-docker-image) or [Option 2](https://devexpress.github.io/testcafe/documentation/continuous-integration/gitlab.html#option-2---install-testcafe-on-a-docker-image) .
It works only with docker in docker (dind)
![image](https://user-images.githubusercontent.com/8465337/55742102-43c79380-5a05-11e9-96f5-09b950cb1a1d.png)
 
ERROR:
![image](https://user-images.githubusercontent.com/8465337/55742494-34951580-5a06-11e9-900c-edbd346a6e72.png)

ERROR:
![image](https://user-images.githubusercontent.com/8465337/55742908-4d51fb00-5a07-11e9-9595-57d6ed2d05a7.png)

Works:
![image](https://user-images.githubusercontent.com/8465337/55742882-41663900-5a07-11e9-8311-a1eba63ca41c.png)

How can i debug what exactly is ...

> "ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure."

### What is the Expected behavior?
Tests executed just like my local machine
 
### Your Environment details:
 
* testcafe version:                   1.1.1
* node.js version:                    v8.11.3
* command-line arguments:  "testcafe firefox:headless tests/**/* --proxy user:pass@server:port"
* browser name and version: 
* platform and version:          
* other:                                   gitlab-ce v 11.7

**Comment by miherlosev** [comment]
Hi @guilhermecgs 
 
> How can i debug what exactly is ...
 

I suggest you record and send us a video of test execution. 
To create such a video append appropriate packages/scripts to your docker image.

**Comment by miherlosev** [comment]
I cannot determinate the cause of the problem with the provided information.
Could you please prepare an example to reproduce the problem?

**Comment by HsuTing** [comment]
I had the same error with `circleci` when I upgrade to `testcafe@1.1.2`. After I go back to use `testcafe@1.1.0`, this can work. I think the version between `1.1.2` to `1.1.0` had changed something caused this problem.
