### ISSUE TITLE
Dockerized TestCafe creates screenshot images to volume with incorrect permissions

### ISSUE THREAD

**Issue by aluokkal** [DevExpress/testcafe#3655]
### What is your Test Scenario?
Run official testcafe docker image with screenshots activated.

Testcafe options:
--screenshots-on-fails true \
--screenshots /tests \
--screenshot-path-pattern '${DATE}-${TIME}-${TEST_INDEX}-${USERAGENT}-$
 
### What is the Current behavior?
Screenshots created to /tests folder (a volume mapped to docker host) cannot
be removed without sudo. This a problem in Jenkins environment, because workspace
cleanup fails due to missing permissions.
 
### What is the Expected behavior?
Normal user (without sudo) can delete generated screenshot images from the volume.
 
### What is your web application and your Testcafe test code?
This is generic problem.
 
### Steps to Reproduce:
Run any testcafe tests with docker image and output screenshots to docker host volume.
Try to remove screenshot images without sudo.

### Your Environment details:
Linux\docker.

**Comment by AndreyBelym** [comment]
It's a restriction of permission management in Docker volumes. Your host machine and the Docker container use different user IDs when accessing files in a volume with your screenshots. You can add a user account with user ID 1000 to your host machine with the following command and use it when working with Docker:
```
useradd -u 1000 docker-user
```

Or you can call the `process.umask(0777)` function in a `fixture.before` hook to allow removing your screenshot files with any user ID.

**Comment by aluokkal** [comment]
Ok, thanks for quick response.

**Comment by AndreyBelym** [comment]
You're welcome 😄

**Comment by aluokkal** [comment]
This did the needed trick in fixture hook: process.umask(0o000).

**Comment by AndreyBelym** [comment]
Thank you for correcting the mask, I've updated the original post to include it.
