### ISSUE TITLE
Testcafe not waiting to finish requests

### ISSUE THREAD

**Issue by gaborari** [DevExpress/testcafe#3657]
### What is your Test Scenario?
Having an Angular SPA with lazy loaded independent plugins - every plugin has own stylesheet, bundled js files, localization files etc.

The flow of using the site is the following:
- The user opens the main page, then the user gets navigated to a splash screen:
   The splash screen shows some loading indicators, and starts to bootstrap the application (load dependencies bundle, and fetch js files for components). Then navigates to MS Sign in page.
- When the MS login is done, the user gets navigated back to splash screen, and the application initiates calls with the login information to an API to check authorization information, e.g.: user grants. When all necessary call is finished, the user gets navigated to a landing page, where actual user interaction can be done.
- The user clicks on side nav bar links:
   These links are essentially the entry points of the lazy loaded plugins. The click triggers to actually load the plugin - fetch bundle of plugin, css, locale file (from an api)
- When the plugin is loaded, the user can create business entities. Sometimes, especially with larger entities, the backend processing can take a while, like ~half minute.

Using the following code:
```
fixture('New Fixture')
    .page('test site url');

test('New Test', async (t) => {
    await t
        // type email
        .typeText(Selector('[type="email"]'), 'test user email address')
        .pressKey('enter')
        // type pwd
        .typeText(Selector('[type="password"]'), 'test user password')
        .pressKey('enter')
        // navigate to the first plugin
        .click(Selector('a').withText('First plugin')) 
        ...
```

### What is the Current behavior?

When opening the splash screen, Testcafe is not waiting for the bootstrapping:
not waiting for fetch requests.
So the result is the following (navigation to MS Sign in is not happened yet):

```
The specified selector does not match any element in the DOM tree.

> | Selector('[type="email"]')
```

Sometimes when the bootstrapping happens quickly, the test navigates to the MS Sign in page, writes the email and password, then navigates back to splash screen.

In this case, I've observed the same behaviour, Testcafe is not waiting for new fetch and xhr calls consistently, getting the following error:
```
The specified selector does not match any element in the DOM tree.

> | Selector('a')
|   .withText('First plugin')
```

In the case when the test can go to the landing page and can create entities, I've observed the same behavior for the actual 'create entity' xhr request, Testcafe is not waiting consistently for the xhr completions - got a timeout for the assertion to check if the newly created entity is shown on the UI. 
 
### What is the Expected behavior?

Testcafe waits for all fetch and xhr completion.

### Your Environment details:
 
* testcafe version:                   1.1.1 (same result with lower version like 0.23.3)
* node.js version:                    10.13.0
* command-line arguments:  testcafe chrome .\tests\test.spec.ts
* browser name and version: chrome v73.0.3683.103
* platform and version:          Windows 10

**Comment by miherlosev** [comment]
Hi @gaborari 

TestCafe waits for the xhr and fetch requests completion ([see the checked test cases](https://github.com/DevExpress/testcafe/blob/master/test/client/fixtures/core/request-barrier-test.js)).
According to your description, page load time for some pages of your web site can be big.
Try to increase the selector timeout for selectors that evaluated the first after navigation.

```js
Selector('[type="email"]', { timeout: 60000 })
Selector('a', { timeout: 60000 }) .withText('First plugin')
```

**Comment by gaborari** [comment]
Hi @miherlosev 
Thanks for the quick feedback!

I found that selectors have option for overriding the timeout, and I used them - basically I wanted to remove those manual timeout override.
Mainly because of I had to add the timeout to several points - by that, every dev in the team has to be familiar with every key points where the timeout overrides has to be added.

From the other hand, those timeouts can cause 'false waits', for example:
I have a test scenario when I open the first plugin, I do some actions, navigate to the second plugin for getting data to continue the business case.
The second plugin is also a lazy loaded plugin, and when loaded, it shows a list of data.
Suppose that, to make sure that there is no loading timeout issue, I add 1 min timeout override for selecting the first data row.
If the plugin loaded quickly (e.g: 1s) and there is a communication issue or there is no data in the list, the test will hang for 1min - even if there is no fetch/get in the background and no rendering on the UI.

(Just a personal note, Testcafe has a pretty nice api, and I'd prefer to not put timeout overrides to lot of places)

I also tried to mimic the behaviour of the RequestBarrier class within a request hook:
- collect request ids to a collection within the onRequest method
- wait the test run until the collection of requests ids is not empty
- remove the request ids from the collection within the onResponse method

But I got no luck yet.

**Comment by miherlosev** [comment]
> I found that selectors have option for overriding the timeout, and I used them - basically I wanted to remove those manual timeout overrides.

 
The default Selector timeout value is [10 sec](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--selector-timeout-ms), which is a sufficient time for most of the web sites. 
 
I agree with you that it's possible to have a 'false waits' in case of a communication issue.
 
Anyway, you need to increase the timeouts because your web pages can have a big load time.
You can increase timeouts on the test run level. For more details, see [this](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#run) article.

**Comment by gaborari** [comment]
@miherlosev I'll create a similar application to simulate the issue. This may take a while.

**Comment by miherlosev** [comment]
Please reopen this issue when the example is ready.
