### ISSUE TITLE
[docs] Create an article described  'How to structure reusable code', 'How to use a regular node.js module in tests' and 'How to use environment variables in tests'

### ISSUE THREAD

**Issue by jbradensmile** [DevExpress/testcafe#3661]
### What is your Test Scenario?
Calling repeatable test steps from an external file full of functions so when maintenance is needed, there is only one place to update.

### What are you suggesting?
To be able to call the function from an external file into the test, using the same async and await as the test.

### What alternatives have you considered?
I've tried all types of JS syntax and node.js friendly ways.

### Additional context
I've worked mainly with TestComplete and QTP and this feature is very simple to execute on those. It seems this is not a feature with TestCafe. If I'm wrong, please enlighten us with a documentation link or an explanation.

**Comment by miherlosev** [comment]
Hi @jbradensmile 
 
Thank you for your suggestion. We will create an article to cover such common cases as 'Structure reusable code', 'How to use a regular node.js mode in tests' and 'How to use environment variables in tests'.
