### ISSUE TITLE
[docs] Add version to the feature description

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#3675]
Need to add version number to the feature description.

https://stackoverflow.com/questions/55635138/testcafe-runner-video-is-not-a-function-at-createtestcafe-then-then-remoteconnec#55635138

Same as for Node.js documentation.

![image](https://user-images.githubusercontent.com/4133518/55967118-687c6f00-5c82-11e9-8893-6bba08685b02.png)

**Comment by titerman** [comment]
We don't plan to address this issue in the near future. Feel free to reopen the ticket if the issue is important for you.
