### ISSUE TITLE
Google login button click has no effect when using testcafe

### ISSUE THREAD

**Issue by gagoncal** [DevExpress/testcafe#3677]
### What is your Test Scenario?
I wan´t to use a google sign in button , so that the click triggers a pop up to insert user information. 

### What is the Current behavior?
Clicking the button using testcafe works, button element is found on the page and click is executed, but no subsequent action occurs.
Manually everything works fine, clicking on the button opens a popup with the google account form, to enter details. When using testcafe , clicking on the button executes nothing, I tried to use the debug mode and unlock the page , and manually the button click does nothing.
 
### What is the Expected behavior?
Clicking the google sign in button on the page should trigger the popup , exactly as it occurs with the standard webpage with manual steps.

### What is your web application and your TestCafe test code?
I am testing a single page application , the button html :
```
<button class="button button--with-variations button--has-icon button--utility google-sign-in-button" data-event-click="{&quot;element&quot;:&quot;Button&quot;}" id="g-signin2" type="button"><div class="button__icon-container button__icon-container--before"><svg width="32px" height="32px" viewBox="0 0 32 32" version="1.1" xmlns="http://www.w3.org/2000/svg"><title>Verso G</title><desc>Created with Sketch.</desc><defs></defs><g id="Verso-G" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><rect id="Rectangle" fill="#FFFFFF" fill-rule="nonzero" x="0" y="0" width="32" height="32"></rect><path d="M24.64,16.2045455 C24.64,15.5663636 24.5827273,14.9527273 24.4763636,14.3636364 L16,14.3636364 L16,17.845 L20.8436364,17.845 C20.635,18.97 20.0009091,19.9231818 19.0477273,20.5613636 L19.0477273,22.8195455 L21.9563636,22.8195455 C23.6581818,21.2527273 24.64,18.9454545 24.64,16.2045455 L24.64,16.2045455 Z" id="Shape" fill="#4285F4"></path><path d="M16,25 C18.43,25 20.4672727,24.1940909 21.9563636,22.8195455 L19.0477273,20.5613636 C18.2418182,21.1013636 17.2109091,21.4204545 16,21.4204545 C13.6559091,21.4204545 11.6718182,19.8372727 10.9640909,17.71 L7.95727273,17.71 L7.95727273,20.0418182 C9.43818182,22.9831818 12.4818182,25 16,25 L16,25 Z" id="Shape" fill="#34A853"></path><path d="M10.9640909,17.71 C10.7840909,17.17 10.6818182,16.5931818 10.6818182,16 C10.6818182,15.4068182 10.7840909,14.83 10.9640909,14.29 L10.9640909,11.9581818 L7.95727273,11.9581818 C7.34772727,13.1731818 7,14.5477273 7,16 C7,17.4522727 7.34772727,18.8268182 7.95727273,20.0418182 L10.9640909,17.71 L10.9640909,17.71 Z" id="Shape" fill="#FBBC05"></path><path d="M16,10.5795455 C17.3213636,10.5795455 18.5077273,11.0336364 19.4404545,11.9254545 L22.0218182,9.34409091 C20.4631818,7.89181818 18.4259091,7 16,7 C12.4818182,7 9.43818182,9.01681818 7.95727273,11.9581818 L10.9640909,14.29 C11.6718182,12.1627273 13.6559091,10.5795455 16,10.5795455 L16,10.5795455 Z" id="Shape" fill="#EA4335"></path><polygon id="Shape" points="7 7 25 7 25 25 7 25"></polygon></g></svg></div><span class="button__label">Use Google</span></button>
```

I am just executing click using : 
```js
 export async function signInUsingGoogle(userEmail, userPassword, buttonElement) {
   await t
    .maximizeWindow()
    .click(Selector('#g-signin2'))
}
```
 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

<details>
<summary>Your complete test report:</summary>
Next step after the click will fail, there is no action upon click.
</details>
 
### Your Environment details:
 
* testcafe version:                   1.1.0
* node.js version:                    v6.4.0
* platform and version:          macOS 10.14
<img width="1427" alt="screen" src="https://user-images.githubusercontent.com/10652567/55977245-3836cf80-5c86-11e9-8170-acc717b78826.png">

**Comment by LavrovArtem** [comment]
This information is not sufficient to find the cause of the issue and therefore we cannot give you advice without analyzing your page or code. Would you please give me a link to your site if it is public?
