### ISSUE TITLE
'An error occurred in Selector - ReferenceError: builder is not defined' when running test that using a Selector in Page class

### ISSUE THREAD

**Issue by oemekaogala** [DevExpress/testcafe#3678]
### What is the Current behavior?
The code runs up until it's suppose to click on a Selector that exists in a Page class. It crashes.

### What is the Expected behavior?
The Selector should be clicked with no issue.

<details>
<summary>Project Structure:</summary>

*Availble with yarn add (internal): MainTestFramework #imports TestCafe*
```
MyProject
	node_modules
	package.json
	test
		__tests__
			sampleTest.js # imports pages from local-framework/pages
		local-framework # has MainTestFramework as a depenency
			node_modules
			package.json
			pages # imports Selectors from MainTestFramework (which imports TestCafe and exports Selectors)
			utils

	dist # Transpiled to run tests. Created after a build
		test
			__tests__
				sampleTest.js
			local-framework
				node_modules
				package.json
				pages
				utils
```
</details>

<details>
<summary>Run Test:</summary>
To run code: 
testcafe chrome ./MyProject/dist/test/__tests__/sampleTest.js
</details>

<details>
<summary>Your complete test report:</summary>
```
 1) - Error in fixture.beforeEach hook -
      An error occurred in Selector code:

      ReferenceError: builder is not defined

      Browser: Chrome 73.0.3683 / Mac OS X 10.14.4

         25 |var accountId = 'xxxxxxxxx';
         26 |
         27 |var setup = async function setup(t) {
         28 |    await _BaseTestCase2.default.beforeEach(t, configuration, [settings]);
         29 |    await _BasePage.BasePage.goToHomePage(t, accountId);
       > 30 |    await t.click(dashboard.createButton);
         31 |    await form.clickStartOver(t);
         32 |    await t.click(form.friendsObjectiveButton).click(form.photosButton);
         33 |};
         34 |
         35 |// Pages

         at click (/Users/../../../../../__tests__/sampleTest.js:30:13)
```
</details>

### Your Environment details:
 
* testcafe version:                   0.21.1
* node.js version:                    v10.13.0
* command-line arguments:  			  testcafe chrome /Users/../../../../../__tests__/sampleTest.js --skip-js-errors
* browser name and version: 		  Chrome 73
* platform and version:          	  macOS 10.14.4

**Comment by AlexKamaev** [comment]
This information is not sufficient to reproduce the issue. Please provide us a working project which demonstrate the issue and your test code file.

**Comment by oemekaogala** [comment]
Found the issue. It was another local issue. Thanks!

**Comment by rob4629** [comment]
> Found the issue. It was another local issue. Thanks!

I'm attempting to execute a Rendr App function in the client window (to change a user's state), and getting the same error when calling the ClientFunction:

```
const _changeUserState = ClientFunction(() => {
    return App.get('currentUser').set('login_state', 'someState');
});


await _changeUserState();
```

Can you explain what you did wrong that caused the "builder not defined error"?

**Comment by oemekaogala** [comment]
My issue was from using the global testcafe instead of the local testcafe to run my code. There were different 'testcafes' available to something broke somewhere.

**Comment by rob4629** [comment]
Ahh ok. Thanks for clarifying.
