### ISSUE TITLE
the typed text is removed for some reason

### ISSUE THREAD

**Issue by PonmaniAnnamalai** [DevExpress/testcafe#3680]
PageObject.js:
export default class AppSelection {
    constructor () {
 this.userid = Selector('input#login-email[type="text"]');}
Test.js:
const descriptionModule = "xxxx@xxxx.com";
typeText(appselection.userid,descriptionModule,{replace: true, paste: true})
        .wait(2000)
        .pressKey("enter")

Expected:
Input given should remain as such

Actual:
The text input is removed for some reason. Attached screen shot for reference

Environment: Chrome 73.0.3683 / Mac OS X 10.14.4
![image](https://user-images.githubusercontent.com/46040608/56016545-33bbf680-5d1a-11e9-95a9-318b7dee20cb.png)

**Comment by PonmaniAnnamalai** [comment]
Entering the email:
![image](https://user-images.githubusercontent.com/46040608/56016712-cfe5fd80-5d1a-11e9-8120-07cb6113b5f3.png)

**Comment by Farfurix** [comment]
@PonmaniAnnamalai 

Hello.

Unfortunately, this information is not sufficient to find the cause of the issue. There can be many causes, and therefore we can't give you any advice without analyzing your page or code.

Could you please provide us with a sample example project (or some public URL) to reproduce this issue on our side?

I've tried to reproduce the issue, but with no success:
**test.js**
```js
// testcafe@1.1.1 / macOS / Chrome
import { Selector } from 'testcafe';

fixture `My Fixture`
    .page `https://getbootstrap.com/docs/4.0/components/forms/#overview`;

test('test', async (t) => {
    const input = Selector('#exampleInputEmail1');

    await t
        .typeText(input, 'name@example.com', { replace: true, paste: true })
        .debug();
});
```

**Comment by PonmaniAnnamalai** [comment]
Hi,
I have resolved the issue by installing testcafe globally, Previously I tried it using -dev --save.
Thank you.
