### ISSUE TITLE
Cannot click buttons on https://google.com/

### ISSUE THREAD

**Issue by phartshorn** [DevExpress/testcafe#3688]
I am currently writing automated tests for my company's react application and I've had an issue where an element (a link) is considered not visible by TestCafe whereas the screenshots show that it is visible. As this project is fairly private (at the moment) I can't share any code, but I've discovered the same issue with google's search page. That being, TestCafe can find the search and feeling lucky buttons, but it will not click on them as it things they're hidden.

### What is your Test Scenario?
I'd like to test clicking on a link loads a new page
 
### What is the Current behavior?
I'm not able to get TestCafe to click on the link for TestCafe thinks the link is not visible (screenshots show that it is quite visible)
 
### What is the Expected behavior?
TestCafe should correctly identify hidden and visible dom nodes.
 
### What is your web application and your TestCafe test code?
https://google.com/

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
import { Selector } from "testcafe";

fixture `Google`
  .page("https://google.com");

test("feeling lucky", async (t) => {
  const feelinLucky1 = Selector('input').withAttribute('value', /Feelin/i);
  const feelinLucky2 = Selector('input[value*="Feelin"]');

  console.log("FL1: ", await feelinLucky1.visible, await feelinLucky1.value);
  console.log("FL2: ", await feelinLucky2.visible, await feelinLucky2.value);

  await t.click(feelinLucky1);
}); 
```
</details>

<details>
<summary>Your complete test report:</summary>

```
MACBOOK-PRO:tmp user$ npm run test

> test@1.0.0 test /Users/user/tmp
> testcafe chrome google/test.ts

 Running tests in:
 - Chrome 73.0.3683 / Mac OS X 10.14.4

 Google
FL1:  false I'm Feeling Lucky
FL2:  false I'm Feeling Lucky
 ✖ feeling lucky

   1) The element that matches the specified selector is not visible.

      Browser: Chrome 73.0.3683 / Mac OS X 10.14.4

          8 |  const feelinLucky2 = Selector('input[value*="Feelin"]');
          9 |
         10 |  console.log("FL1: ", await feelinLucky1.visible, await feelinLucky1.value);
         11 |  console.log("FL2: ", await feelinLucky2.visible, await feelinLucky2.value);
         12 |
       > 13 |  await t.click(feelinLucky1);
         14 |});
         15 |

         at Object.<anonymous> (/Users/user/tmp/google/test.ts:13:11)
         at fulfilled (/Users/user/tmp/google/test.ts:4:58)



 1/1 failed (14s)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@1.0.0 test: `testcafe chrome google/test.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2019-04-15T06_16_32_374Z-debug.log
```
</details>

<details>
<summary>Screenshots:</summary>

```
Just load https://google.com to get an idea of where the buttons are located
```
</details>

### Steps to Reproduce:

1. Go to https://google.com/
2. testcafe chrome google/test.ts
3. observe that TestCafe think that the I'm Feeling Lucky button is not visible
 
### Your Environment details:
 
* testcafe version:                   1.1.2
* node.js version:                    v8.15.1
* command-line arguments:  testcafe chrome google/test.ts
* browser name and version: Chrome 73.0.3683.103
* platform and version:          macOS 10.14.4
* other:                                   testcafe installed with `npm install testcafe`

**Comment by AlexKamaev** [comment]
The test fails on the `google` page because that page actually contains two `input` elements with the same `value` attributes.
You can modify your selector in the following way and the test will pass:
`Selector('input').withAttribute('value', /Feelin/i).nth(1);`
 
As for your project, there can be multiple causes of that behavior. Check that the element has `clientWidth` and `clientHeight` more than zero. Check that element does not have the `visibility: hidden` or `display: none` properties.
 
If you still have the issue, please prepare a sample page from your project which demonstrates the issue.
