### ISSUE TITLE
Not able to upload a file via setFilesToUpload

### ISSUE THREAD

**Issue by rduinmaijer** [DevExpress/testcafe#3699]
### What is your Test Scenario?
I want to upload a file (file is in the root same as the test)
```
const file =  'filename.img';
const ccc = Selector('[name=fileFile]');
    return t
      .expect(ccc.exists).ok()
      .setFilesToUpload(ccc, file)
       .click(Selector('input').withAttribute('value', 'add'))
```

### What is the Current behavior?
Nothing happens
 
### What is the Expected behavior?
File should be added to the form and uploaded
 

### Part of the source
**File browser / seaching**
`<input name="fileFile" type="file" size="50">
`

**Upload button**
`<input type="submit" value="add ">
`

### Your Environment details:
 
* testcafe version:                   1.1.0
* node.js version:                    v10.15.1
* command-line arguments:  "testcafe -c 1 \"chrome --window-size='1280,1600' --incognito --disable-web-security\" e2e\\src\\*\\*.spec.ts -S -s dist\\screenshots --reporter spec,html:e2e\\src\\reports\\report.html"
* browser name and version: Chrome
* platform and version:          Windows 7

**Comment by AlexKamaev** [comment]
This information is not sufficient to reproduce the issue. Please provide us with an example (or url to your web site) which demonstrates the issue and full test code.

**Comment by rduinmaijer** [comment]
@AlexSkorkin I edited the issue with some more highlighting.

**Comment by rduinmaijer** [comment]
Also added My Environment details

**Comment by AlexKamaev** [comment]
I was not able to reproduce the issue, since it's not sufficient to have only an html page for file upload testing. I mean what do you expect to see after the file is uploaded? Probably some list of uploaded elements. But this is task for the server, so I need the full project to reproduce it.
 
I also tried to reproduce the problem on some other site, however, it works as expected. Please see and check the following test code:

import { Selector } from 'testcafe';

```JS
fixture`test`
    .page`https://fineuploader.com/demos.html`;

test('test', async t => {
    const file = 'D:\\Projects\\testcafe\\media\\testcafe-studio-banner.png';
    const ccc  = Selector('input[type=file]').nth(1);

    await t.expect(ccc.exists).ok()
        .setFilesToUpload(ccc, file)

    await t.click('#trigger-upload')

    await t.wait(5000);
});
```
As you can see, the image is uploaded successfully

**Comment by rduinmaijer** [comment]
Are you known with issue with a Selector by name? Because that's the only difference I can see quickly.
Selector('[name=fileFile]')

**Comment by AlexKamaev** [comment]
I don't think so. I've created your page and checked your code and I can confirm that Selector works correctly. I still think that the cause of the issue is on your server side, so I ask you to provide a full project or public url.

**Comment by rduinmaijer** [comment]
Hi Alex thanks for looking into it.

I made a codepen with some html upload as we use them here and the test for it looks like this:
https://codepen.io/anon/pen/JVpoOz

Testcafe fails on the first expect. If I take the expect out then it doesn't add the file to the form.

```
import {Selector} from 'testcafe';

const routeFile = 'rwpl_HLM_v785.gz';
const fileUploadInput = Selector('input').withAttribute('name', 'routeFile');

fixture.only(`tests`)
  .page('https://codepen.io/anon/pen/JVpoOz');

test('test', async t => {
  await t
    .expect(fileUploadInput.exists).ok()
    .setFilesToUpload(fileUploadInput, routeFile)
    .expect(fileUploadInput.value).contains('rwpl_HLM_v785.gz');

  await t.click(Selector('input').withAttribute('value', 'voeg configuratie toe'));


  await t.wait(5000);
});

```

**Comment by AlexKamaev** [comment]
The error occurs because the CodePen page has an iframe inside. If you modify your test by adding
the `.switchToIframe('#result')` command before `.expect(fileUploadInput.exists).ok()` the test will pass.

**Comment by rduinmaijer** [comment]
The iframe is a good trick.
The test looks green but in fact the file is not added to the upload-thingie.

"Geen bestand gekozen" means no file chosen.
However the second expect is checking that the filename is filled-out. But it's not filled-out. 
Even if I click the upload button our app says that there is no file add.

![image](https://user-images.githubusercontent.com/31839655/56284608-4026c180-6115-11e9-9866-ae487a70686c.png)

**Comment by AlexKamaev** [comment]
The `setFilesToUpload` command emulates upload behavior, but does not copy the native behavior since there are some restrictions. It's impossible to change the message of input[file] element. However, you still can check an input value like you do in the following code: `.expect(fileUploadInput.value).contains('rwpl_HLM_v785.gz');`

**Comment by rduinmaijer** [comment]
I upgraded to 1.1.2 in the hope that would magically fix it. But not the case. 

So the expects give a green test untill the last step, we expect no error message of course.

```
const fileUploadbuttonRijwegplan = Selector('[name=routeFile]');
const fileUploadbuttondgnFile0 = Selector('[name=xx]');
const fileUploadbuttondgnFile1 = Selector('[name=xx2]');
const routeFile = 'abc.gz';
const dgnFile0File = 'xxx.zip';
const dgnFile01File = 'xyz.zip';
      .expect(fileUploadbuttonRijwegplan.exists).ok()
      .setFilesToUpload(fileUploadbuttonRijwegplan, routeFile)
      .expect(fileUploadbuttonRijwegplan.value).contains(routeFile)

      .expect(fileUploadbuttondgnFile0.exists).ok()
      .setFilesToUpload(fileUploadbuttondgnFile0, dgnFile0File)
      .expect(fileUploadbuttondgnFile0.value).contains(dgnFile0File)

      .expect(fileUploadbuttondgnFile1.exists).ok()
      .setFilesToUpload(fileUploadbuttondgnFile1, dgnFile01File)
      .expect(fileUploadbuttondgnFile1.value).contains(dgnFile01File)

      .click(Selector('input').withAttribute('value', 'voeg configuratie toe'))
      .wait(2400)
      .expect(body.innerText).notContains('Ontbrekend rijwegplan bestand');
```

**Comment by rduinmaijer** [comment]
<blockquote class="imgur-embed-pub" lang="en" data-id="a/Vp77NCw"><a href="//imgur.com/Vp77NCw"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by AlexKamaev** [comment]
I see that there is something wrong with your scenario. However, it is impossible to say anything definite about the issue without a full working project. I've checked a similar scenario on `https://fineuploader.com/demos.html`, and it works as expected. If you are unable to share your full project, please find any other public website, which demonstrates issue.

**Comment by rduinmaijer** [comment]
Do you have any suggestions? Perhaps code-base-wize for my team?

**Comment by rduinmaijer** [comment]
Alex is there a way to send you a private message regarding this issue? @AlexKamaev

**Comment by AlexKamaev** [comment]
You can send a private message at support@devexpress.com

**Comment by AlexSkorkin** [comment]
@rduinmaijer  
We received your updated codepen. However, to help us research this issue, please provide us with a complete working sample project including your server-side code where you encountered these problems. Your codepen sample is insufficient to determine the cause of the issue. Without your full example, we are unable to find a solution.
