### ISSUE TITLE
Support test running in several instances of Chrome or Safari on Mac

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#3700]
Current Behavior:
When you try to run a simple test e.g. in 3 chrome or in 3 Safari instances (the same behavior for start test running in all browsers or e.g `safari,chrome,firefox`) test successfully executes in browser on the top and just pauses int he others. 

We should:
1) start Chrome with `--disable-background-timer-throttling` flag by default (according to this [issue](https://github.com/DevExpress/testcafe/issues/2939))
2) [docs] create an example how to set `Disable Hidden Page Timer Throttling` [flag](https://apple.stackexchange.com/questions/280679/preventing-safari-background-tabs-disconnecting-from-server) in Safari

**Comment by VasilyStrelyaev** [comment]
Can TestCafe... like... detect when these actions for Safari are necessary and output a link to this example in the console?

**Comment by VasilyStrelyaev** [comment]
Otherwise, I don't think many will find this example

**Comment by VasilyStrelyaev** [comment]
Okay, I guess we can detect the '3 browsers` case but we can't detect the flag state. But it's better than nothing.

**Comment by sijosyn** [comment]
Please note - You need to do this first on Mac before execute terminal command to enable debug mode. 

Go to System Preferences > Security & Privacy > Privacy > Full Disk Access and add Terminal.
Then use terminal command.

**Comment by AlexSkorkin** [comment]
@sijosyn, thank you for your input. We will take it into account.
