### ISSUE TITLE
U2F not supported

### ISSUE THREAD

**Issue by Yastrenky** [DevExpress/testcafe#3701]
### What is your Test Scenario?

Using FOB device (YUBICO) with [u2f-api ](https://www.npmjs.com/package/u2f-api)

### What is the Current behavior?

 _ensureSupport (/Users/yas/webapp-automation/node_modules/u2f-api/lib/u2f-api.ts:150:3)
### What is the Expected behavior?

 <u2f-api>.register(key, key, timeout) should be supported.
the function register return U2F not supported. It only trow this error in testcafe. Works fine in the IU implementation.
### What is your web application and your TestCafe test code?

 No public repo to share. (Company policy)
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:    1.1.2               
* node.js version:   10.15.3                 
* command-line arguments:  
* browser name and version: Chrome Version 73.0.3683.103
* platform and version:   MacOs Mojave 10.14.4  
* other:

**Comment by AlexKamaev** [comment]
This information is not sufficient to reproduce the issue. Please follow this [form](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md) and provide us with more details about the problem (a full project, step by step instruction, your test code, detail error message, etc)

**Comment by Yastrenky** [comment]
async registerU2f (userId, deviceName) {
    let client = await this.getClient()
    try {
      const { data } = await client.get(`${this.user}${userId}${this.u2frequestInit}`)
      let u2frequest = data
      if (u2frequest) {
        let keyResponse = await u2f.register(u2frequest.registerRequests, u2frequest.registeredKeys, 5000)
        if (keyResponse) {
          const data = {
            tokenName: deviceName,
            tokenResponse: keyResponse
          }
          JSON.stringify(data)
          const completeRegistration = await client.post(`${this.user}${userId}${this.u2frequestComp}`,
            { data })

          if (completeRegistration) {
            console.log('Registration completed')
          }
        }
      }
    } catch (error) {
      console.log(error)
    }
  }

**Comment by Yastrenky** [comment]
u2f.register() function is not supported for some reason in testcafe

**Comment by AndreyBelym** [comment]
https://www.npmjs.com/package/u2f-api works only in a browser environment. TestCafe tests are executed in a Node.js environment. You can try to read the library code with `fs.readFileSync` and execute it in a browser using a `ClientFunction` instance.
