### ISSUE TITLE
browers remote alias in .testcaferc.json is not working

### ISSUE THREAD

**Issue by brianlaw033** [DevExpress/testcafe#3702]
### What is the Current behavior?

```
{
  "browsers": "remote",
  "src": "index.js",
  "screenshotPath": "screenshots",
  "screenshotPathPattern": "${DATE}_${TIME}/test-${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.png",
  "speed": 0.5
}
```
I have the above settings in `.testcaferc.json` , when i run `testcafe` in command line,
the spinner never stops and no remote link appears. like this:

```
$ testcafe
Using locally installed version of TestCafe.
/
```

### What is the Expected behavior?
works like `testcafe remote`

### Your Environment details:
 
* testcafe version: 1.1.2
* node.js version: v10.15.1
* command-line arguments:  testcafe
* platform and version:  Windows 10

**Comment by AlexKamaev** [comment]
I was able to reproduce the issue.

**Comment by AlexKamaev** [comment]
I discussed the issue with the team and we decided not to include the fix in our nearest plans, since it can lead to some significant changes. We'll consider implementing this feature in the future, however, I cannot give you any estimates on it.
