### ISSUE TITLE
Element properties like "isContentEditable" is not working

### ISSUE THREAD

**Issue by jbradensmile** [DevExpress/testcafe#3709]
###TestCafe version
1.1.2

### What is your Test Scenario?
I am trying to assert an element's property is a specific value. I have found that properties like "innerText" works, but even "innerHTML" returns undefined. 
 
### What is the Current behavior?
The value returns "undefined".
 
### What is the Expected behavior?
The value returns what it says it is in the developer tools
![image](https://user-images.githubusercontent.com/44841753/56314156-e248a880-6119-11e9-844b-f5eb09eb87fa.png)

### Reason we need this:
We should be able to assert on any element's property, not just some.

**Comment by AlexKamaev** [comment]
Not all DOM element properties are included in Selector API. For the `innerHTML` property you can use the [CustomProperties ](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/extending-selectors.html)approach:
```JS
import {Selector} from 'testcafe';

const selector = Selector('div');

fixture(`tests`)
    .page `../pages/index.html`

test('test', async t => {
    const extendedSelector = selector.addCustomDOMProperties({
        innerHTML: el => el.innerHTML
    });
    console.log(await extendedSelector.innerHTML);
});
```
Please also refer to the following article to get detailed information: https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/examples-of-working-with-dom-elements.html#accessing-page-element-properties

**Comment by jbradensmile** [comment]
Thank you for the quick turn around on this. Follow up question: Is it intensive to add more properties to the Selector API? This solution seems like overkill just to call a property like we can with innerText. Automation tools are used by non-developers (SQA, HQA, BAs, etc.) in an attempt to make their jobs/lives easier. Having to write a function to grab a property obviously isn't for everyone. Having to assert element properties is a big part of functional automation testing, like strings, visibility, read only, even styles and fonts and much more.

**Comment by AndreyBelym** [comment]
Thank you for your interest. It's not very hard to add a particular property, take a look at the `innerText` getter: 

https://github.com/DevExpress/testcafe/blob/master/src/client-functions/selectors/snapshot-properties.js

https://github.com/DevExpress/testcafe/blob/master/src/client/driver/command-executors/client-functions/selector-executor/node-snapshots.js#L112

It will be superb if you can make a PR. However, I would like to implement a more general approach that allows using any element property as a `Selector` property in the context of this task: https://github.com/DevExpress/testcafe/issues/3723.
