### ISSUE TITLE
Make the website responsive

### ISSUE THREAD

**Issue by luismartinezs** [DevExpress/testcafe#3712]
Make the website, where the documentation pages are held, responsive and mobile friendly

### What is your Test Scenario?
Viewing testcafe docs in mobile and in different browser sizes

### What are you suggesting?
Make the website responsive

### What alternatives have you considered?
None

### Additional context
None

**Comment by VasilyStrelyaev** [comment]
Thank you for your suggestion!
 
We agree that website responsiveness and mobile adaptivity are important, and we will work on enhancing them further.

**Comment by danawoodman** [comment]
Been over a year, this would be very nice to have and lends more credibility to the product for new users.

**Comment by miherlosev** [comment]
We made the [https://devexpress.github.io/testcafe/](https://devexpress.github.io/testcafe/) website quite responsive. At present, you can use it on mobile devices.

However, when working on its responsiveness, we decided to create a new website based on a new web site engine to make it more SEO friendly and even more responsive. As soon the new website is released, we will announce this in our news channels. Please stay tuned.

**Comment by luismartinezs** [comment]
The website is indeed responsive and navigable on mobile now. One needs to use or simulate a mobile device to see that though. Narrowing the width of the browser window on desktop won't show responsiveness (which makes me think that responsiveness is handled by a plugin instead of by CSS media queries).

Anyhow, I am closing this issue
