### ISSUE TITLE
ClientFunction produces "badly" compiled input code

### ISSUE THREAD

**Issue by danielschwartz85** [DevExpress/testcafe#3713]
Hello ✋,

### Test Scenario?
Executing ClientFunction
 
### Current behavior?
The code given to  ClientFunction compiles in a wrong way:
1. for example: ```ClientFunction(() => !!Symbol);```
becomes: ```function () {return !!_symbol2.default;}```
which produces the error: ```ReferenceError: _symbol2 is not defined```

2. ```ClientFunction(() => JSON.stringify([...document.querySelectorAll('#not-there')]))```
returns ```"[{}]"```
but should return ```"[]"``` since the spread operator should transform the NodeList to an Array.
I.e. the spread does't compile correctly.
 
### Expected behavior?
1. should not fail 

2. should work the same as in the browser, i.e. convert the NodeList to an Array. 

### Reproduction
See simple Repo:
https://github.com/danielschwartz85/testcafe-clientfunction-isssue

### Complete test code
```js
 import {ClientFunction} from 'testcafe';
import {Selector} from 'testcafe';

fixture`Getting Started`.page`https://google.com`;

test('My Test', async t => {
    const f = ClientFunction(() => !!Symbol); //  becomes: function () {return !!_symbol2.default;} // ReferenceError: _symbol2 is not defined
    await f()
});

test('My Test 2', async t => {
    const f= ClientFunction(() => JSON.stringify([...document.querySelectorAll('#not-there')])); // returns [{}] should be []
    console.log(await f())
});
```

 Tnx.

**Comment by AlexKamaev** [comment]
We are aware about this issue and already discussed a similar problem here https://github.com/DevExpress/testcafe/issues/2544, so I'll mark it as a duplicate. However, I cannot give you estimates when the issue will be solved.
As a workaround to the `Symbol` problem, you can use `window.Symbol` instead of `Symbol`.

**Comment by danielschwartz85** [comment]
👍, Thanks for the quick response.
