### ISSUE TITLE
Update ReporterPluginHost class with reportTestStart

### ISSUE THREAD

**Issue by Ivan-Katovich** [DevExpress/testcafe#3715]
### What is your Test Scenario?
```
test('Test 1', async (t) => {
    await app.goRoot();
    await app.waitLoading();
    await allure.createStep('Check Help', async () => {
        await app.header.click('helpIcon');
        const title = await app.getPageTitle();
        await t.expect(title).eql('Docketing Portal');
    })();
});
```
### What are you suggesting?
IReporterPluginHost has just method reportTestDone and doesn't have reportTestStart method so we don,t have ability to add something between test start and finish. 
Fore example: it is impossible to add allure steps to tests which is very useful for e2e testing.
I suggest to add method for starting and finishing of test instead of handling all information in reportTestDone

**Comment by AlexKamaev** [comment]
I think this is a reasonable enhancement, however I cannot give you any estimates when we can implement it.
 
I can recommend using[ fixture hooks](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#fixture-hooks) and [tests hooks](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#test-hooks) to solve the issue. I find it very suitable for your task.

**Comment by Ivan-Katovich** [comment]
The problem is that allure.createStep is a wrapper on test code to attach step to a report, but it have to be executed between allure.startCase and allure.endCase, which both run in reportTestDone after test execution. Hooks are not able to help there.

**Comment by Farfurix** [comment]
@Ivan-Katovich 

Hello.

Thank you for the additional details. We will consider your suggestion.

**Comment by devmondo** [comment]
We are also facing the same issue as @Ivan-Katovich, it is really a show blocker for Allure. hope it would be implemented soom

**Comment by Farfurix** [comment]
Hello @devmondo,

Thank you for your input. You are welcome to vote on this feature request (👍 ), so it gets more attention.

**Comment by Ivan-Katovich** [comment]
Guys, I have implemented the feature. It took about half a day. Please, let me know if you need the code.

**Comment by LavrovArtem** [comment]
Hi @Ivan-Katovich,
Yes, please. Your PR is welcome.

**Comment by Ivan-Katovich** [comment]
PR for the feature: https://github.com/DevExpress/testcafe/pull/3743

**Comment by Ivan-Katovich** [comment]
Guys, I have 2 tests failed in "continuous-integration/travis-ci/push" check. It doesn't relate with functionality I add. It looks like error.message returns full stack trace instead of short message which is in test assertion. 
Both these tests don't touch my functionality. They relates with import of nonexistent module. So the PR will be ready when the test is fixed.

**Comment by miherlosev** [comment]
Hi @Ivan-Katovich 

It's our problem. We are fixing it right now.

**Comment by Ivan-Katovich** [comment]
Hi guys
How can I restart the checks if they are failed on random tests unrelated with my changes ?

**Comment by AlexKamaev** [comment]
@Ivan-Katovich add the following comment to the PR `@testcafe-build-bot retest`

**Comment by miherlosev** [comment]
@VasilyStrelyaev need to add information about a new reporter method `reporterTestStart` in [reporter-plugin/#implementing-the-reporter](https://devexpress.github.io/testcafe/documentation/extending-testcafe/reporter-plugin/#implementing-the-reporter) section.
```js
        ...
        async reportFixtureStart (/* name, path, meta */) {
            throw new Error('Not implemented');
        },
        ---------------------------------
        async reporterTestStart () {
            throw new Error('Not implemented');
        }
       --------------------------------------

        async reportTestDone (/* name, testRunInfo, meta */) {
            throw new Error('Not implemented');
        },

        ....
 }
```

**Comment by miherlosev** [comment]
Done in https://github.com/DevExpress/testcafe/pull/3804
