### ISSUE TITLE
Dropdwon arrow inside span element is not clicking after upgrading testcafe to v1.0.0 from 0.23.1

### ISSUE THREAD

**Issue by Muthuvenaktesh** [DevExpress/testcafe#3716]
![Element](https://user-images.githubusercontent.com/43955483/56356671-6f9b0400-61d1-11e9-96a4-40f6b0e2833f.JPG)

In the above attached snapshot when I was trying to click on the below selector,

await t..click(Selector('#main > div > div.main > div > div > form > div.container-fluid > section:nth-child(1) > div:nth-child(3) > div > div > div > span.Select-arrow-zone > span'));

It was working fine with the older versions of testcafe (0.22.0 or 0.23.1) but after upgrading to latest release the selector is not clicking and the dropdown values are not shown.

Please check the above snapshot, let me know is anything wrong with the UI original source.

### What is your Test Scenario?
Drop down arrow should be clickable and the values should display.
 
### What is the Current behavior?
With latest release drop down arrow is not clicking, worked with older versions.
 
### What is the Expected behavior?
Drop down arrow inside span should be clickable with latest release.
 
### What is your web application and your TestCafe test code?
await t..click(Selector('#main > div > div.main > div > div > form > div.container-fluid > section:nth-child(1) > div:nth-child(3) > div > div > div > span.Select-arrow-zone > span'));
 
Your website URL (or attach your complete example): 

<details>
<summary>Your complete test code (or attach your test files):</summary>

await t
            .click(directToadminListTab)
            .wait(5 * 1000)
            .click(addNewAdminButton)
            .debug()
            .typeText(enterFirstName, firstName)
            .typeText(enterLastName, lastName)
            .click(Selector('#main > div > div.main > div > div > form > div.container-fluid > section:nth-child(1) > div:nth-child(3) > div > div > div > span.Select-arrow-zone > span'))
            .click(selectDropDownValue.withText('Customer admin'))
            .typeText(enterUserName, userName)
            .typeText(enterEmail, email)
            .click(clickDropDownArrow.nth(2))
            .click(selectDropDownValue.withText('English'))
            .click(clickDropDownArrow.nth(3))
            .typeText(inputSelector.nth(3), 'VECredentialPolicy')
            .click(selectDropDownValue.withText('VECredentialPolicy'))
            .click(saveAndExit)
            .wait(5 * 1000);
    if (await clickOk.exists)
        await t.click(clickOk);

</details>

<details>
<summary>Screenshots:</summary>

![Testcafe_V0 23 1](https://user-images.githubusercontent.com/43955483/56356993-4464e480-61d2-11e9-8cc1-0fb49306a714.JPG)

![Testcafe_V1 1 0](https://user-images.githubusercontent.com/43955483/56357000-4a5ac580-61d2-11e9-8a38-b8c4123c94db.JPG)

</details>

### Your Environment details:
 
* testcafe version:                    1.1.0
* node.js version:                    v10.15.3
* command-line arguments:   testcafe chrome *.js -e -u browser=chrome --hostname 127.0.0.1 -S -s screenshots/253 -r spec -T "877"
* browser name and version:  Chrome 73.0.3683 / Windows 8.1.0.0
* platform and version:           Chrome 73.0.3683 / Windows 8.1.0.0
* other:

**Comment by AlexKamaev** [comment]
This issue looks like a bug but it's difficult to reproduce it on our side since the code is provided as a screenshot. Please provide us with an `html` file and a `js` file with code that I can run on my machine.

**Comment by Muthuvenaktesh** [comment]
Hi @AlexKamaev ,

I dont have access to the UI source code. 
But, I think the issue may be related to the changes for (TestCafe no longer triggers a click event when you disable a button with a span element inside (#2902) ) -https://github.com/DevExpress/testcafe/issues/2902

**Comment by LavrovArtem** [comment]
To make sure that this issue is related to the #2902 issue or anything else, we need your example to research the cause of the problem. Please create a simple sample that we can use on our side.
