### ISSUE TITLE
Simulate slow HTTP Requests

### ISSUE THREAD

**Issue by screendriver** [DevExpress/testcafe#3728]
### What is your Test Scenario?

I want to test a web app that makes some AJAX calls when you interact with it. I [intercept](https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/) the HTTP requests to test my app with different responses. For that I want to simulate slow responses. My tests should check what is the web app doing while waiting for the response (for example disable buttons and inputs, show a loading spinner and so on).

I didn't find anything regarding this in the docs. Additionally the same thing would be useful if you **do not** intercept network requests. For example if you want to call a real third party API just with a slow internet connection (the same thing as you can do with network throttling in the Chrome developer tools)

### What are you suggesting?

An `RequestMock` option for that like:

```ts
const mock = RequestMock()
  .onRequestTo({
    url: 'http://localhost:5000',
    method: 'POST',
    isAjax: true,
  })
  .respond(
	{ my: 'response' },
	200,
	{ 'server': 'nginx/1.10.3' },
    { waitForResponse: 2000 } // here we could add the option for a slow connection
  );
```

And / or something for real third party API calls like

```ts
fixture('My test')
  .page('http://my.url')
  .networkSpeed('slow')
```

**Comment by Farfurix** [comment]
@screendriver 

Hello.

Thank you for your suggestion. We will consider implementing this functionality in the context of the following: https://github.com/DevExpress/testcafe/issues/2425, https://github.com/DevExpress/testcafe/issues/3246

**Comment by screendriver** [comment]
Awesome. Thanks :+1:

**Comment by Farfurix** [comment]
@screendriver 

You are welcome.
