### ISSUE TITLE
Wrong IE11 version detection during functional testing on saucelabs

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#373]
it's detected as IE 7.0.0
(for example, see https://travis-ci.org/testcafe-build-bot/testcafe/jobs/111745475, https://saucelabs.com/tests/b2e64119e5f346259b0b776f940872d2)

**Comment by georgiy-abbasov** [comment]
"Display intranet sites in Compatibility View" option is enabled in Internet Explorer on SauceLabs side, so it sends user agent like: 
Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E)

**Comment by georgiy-abbasov** [comment]
Functionality for disabling this option has been added in `saucelabs-connector` `0.1.1`, so we need just update version of this package
