### ISSUE TITLE
Browser is closed before the page is loaded fully in testcafe

### ISSUE THREAD

**Issue by PonmaniAnnamalai** [DevExpress/testcafe#3731]
On accessing a private url and after login, the expected behavior is landing up in Home page
But browser gets closed before that,
Tried **beforeEach(async ()**, but it ends up in error, "Error in fixture.beforeEach hook - ClientFunction cannot implicitly resolve the test run in context of which it should be executed. If you need to call ClientFunction from the Node.js API callback, pass the test controller manually via Client Functions `.with({ boundTestRun: t })` method first. Note that you cannot execute ClientFunction outside the test code."
Kindly help in sorting it out,

**Comment by miherlosev** [comment]
> On accessing a private url and after login, the expected behavior is landing up in Home page
But browser gets closed before that,

It looks like a bug. Could you please provide us a simple example on which we can reproduce the problem on our side?

**Comment by PonmaniAnnamalai** [comment]
Ex:amazon website. Once Home page is been redirected testcafe is closing the browser, but I want to make sure the entire DOM is loaded
[sample.docx](https://github.com/DevExpress/testcafe/files/3107020/sample.docx)
, In my case, after login the page should be loaded completely, but it is closed once logged in after 10 seconds. But page load time is greater than 30 seconds. DOM loading is not happening
Can you also some other methods to make sure page loading happens before test is passed, apart from using explicit wait.
Is there any ways to get it done using mocha/chai,
Kindly help me on this.

**Comment by miherlosev** [comment]
I am afraid this information is not sufficient to find the cause of the issue.
Feel free to reopen this issue if you can provide an example which we can run on our side. 
It's easy to put all necessary files to a separate repository as shown [here](https://github.com/DevExpress/testcafe/issues/3399#issue-407031883).
