### ISSUE TITLE
RequestLogger to keep track of request/response timestamp

### ISSUE THREAD

**Issue by benjamin21st** [DevExpress/testcafe#3738]
### What is your Test Scenario?

My app makes a few requests and I would like to make sure these requests are made in the correct order and time interval. 

### What are you suggesting?

Currently the RequestLogger object in https://github.com/DevExpress/testcafe/blob/master/src/api/request-hooks/request-logger.js doesn't include a `timestamp` value when logging a request. I suggest we make these really small changes to `loggedReq` inside `onRequest`:
```javascript
        const loggedReq = {
            id:        event._requestInfo.requestId,
            testRunId: event._requestInfo.sessionId,
            userAgent,
            request:   {
                timestamp: Date.now(), // <--- Only line of new code
                url:    event._requestInfo.url,
                method: event._requestInfo.method,
            }
        };
```
and inside `onResponse`:
```javascript
        loggerReq.response            = {};
        loggerReq.response.statusCode = event.statusCode;
        loggerReq.response.timestamp = Date.now(); // <- Only line of new code
```

### What alternatives have you considered?

There really isn't an elegant workaround for this issue. 

### Additional context

The feature is simple enough, and code location as well as suggested edits are both provided. Please leave me a message if you need further clarification. 
I would be happy to take this ticket myself.

**Comment by LavrovArtem** [comment]
Thank you for sharing your idea with us. We will discuss it and consider implementing it in one of our future product updates.

**Comment by benjamin21st** [comment]
@LavrovArtem Thanks a lot!

**Comment by orihomie** [comment]
Any updates on this?

**Comment by alexey-lin** [comment]
@orihomie This feature is not planned for the current sprint. We will consider implementing it in future releases.
