### ISSUE TITLE
Not all cookies are present within testcafe 

### ISSUE THREAD

**Issue by rob4629** [DevExpress/testcafe#3739]
### What is your Test Scenario?

I'm attempting to retrieve an existing cookie, in order to manipulate it for testing purposes
 
### What is the Current behavior?

 I'm unable to locate a required cookie (or a number of cookies) via coded means (i.e. using 'document.cookie' or using chrome developer tools within the TestCafe server/runner to look at all the page cookies. Although some are available, there appears to be a number of cookies missing.
 
### What is the Expected behavior?

I would expect all the same cookies to be available, as when I access the website under test directly
 
### What is your web application and your TestCafe test code?

Although I'm using a staging environment, the same behaviour is experienced when running the code against our live site

Your website URL (or attach your complete example):
www.change.org

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
const _getAllCookies = ClientFunction(() => {
    return document.cookie.split(';');    
});


fixture `Confirm Cookies Present`
    .page(url)

test('Check Cookies', async t => {
    let cookies = await _getAllCookies()
    console.log(cookies);

    await t.expect(cookies.length == 20).ok();
})
```
</details>

<details>
<summary>Your complete test report:</summary>

```

1) AssertionError: expected false to be truthy

         Browser: HeadlessChrome 73.0.3683 / Mac OS X 10.14.4
         Screenshot:
      /Users/rcooper/testing-tools/test-cafe/artifacts/screenshots/2019-04-23_15-05-44/test-1/HeadlessChrome_73.0.3683_Mac_OS_X_10.14.4/errors/1.png

            34 |
            35 |test('Check Cookies', async t => {
            36 |    let cookies = await _getAllCookies()
            37 |    console.log(cookies);
            38 |
          > 39 |    await t.expect(cookies.length == 20).ok();
            40 |})
```
^^ Shows as only having 2 cookies, up to 5 if the user is logged in... however I would expect a much higher number.

</details>

<details>
<summary>Screenshots:</summary>

```
```

</details>

### Steps to Reproduce:

1. Go to my website
2. Open the Dev tools and look at the number of cookies.
3. Now either run the above code, or go in to the debug mode once the homepage has loaded, then check the Dev tools from within the TestCafe runner. 
 
### Your Environment details:
 
* testcafe version:                   1.1.0
* node.js version:                    11.9.0
* command-line arguments:  testcafe chrome:headless -u -r xunit:./artifacts/results.xml
* browser name and version: Chrome 73
* platform and version:          macOS 10.14.4

**Comment by miherlosev** [comment]
Hi @rob4629 

TestCafe uses its own cookie processing mechanism. The `document.cookie` getter is wrapped on the client side with TestCafe's service function (see the [video](https://www.screencast.com/t/UwWdGlyWr) about how it works) .
This makes the browser's development tools display the wrong cookie count; in your case, it is misleading to check the cookie count.
 
If I open the https://www.change.org page in Incognito mode then I can see only 8 cookies:
![image](https://user-images.githubusercontent.com/4133518/56666646-fad63700-66b4-11e9-84de-e219bbda8f20.png)
 
You should bear in mind that some piece of cookies is set by Google Analytics and can be changed any time.

**Comment by rob4629** [comment]
Thanks for the detailed explanation @miherlosev. I'm not checking the cookie count, I was just using that for the example. I'll put this down to user error / some issue with the way I'm retrieving cookies as to why the cookie I want isn't returned.

Thanks again.
