### ISSUE TITLE
Refactor report errors for the APIv2

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#374]
- [x] Move report-related errors code to `errors/test-run` and the runtime errors code to `errors/runtime`
- [x] Prefix all legacy API errors and categories with `legacy`, move them to `legacy/reporter/errors`
- [x] Use`LegacyTestRunError` type for legacy API errors and delegate processing to the legacy templates
- [x] Introduce `TestRunErrorFormattableAdapter`
- [x] Redesign error decorator so it fits need of both API versions
- [x] Check all reporters and introduce temporary testing infrastructure
  - [x] spec
  - [x] list
  - [x] minimal
  - [x] json
  - [x] xunit
- [ ] Implement generic errors
  - [x] External assertion lib errors
  - [x] Test code error
  - [x] Uncaught error on page
  - [ ] Callsites for assertion errors (filter `node_modules` and internal callsites)
  - [x] Page load error (see **Handling page error** below)

- [x] Add decorator for error subtitles (e.g. for beforeEach/afterEach headers)
- [x] Wrap null, undefined number, etc. with `<code>` in messages

## Handling page error
-  Send `about:page-error` and add pending error (this is blocking on DevExpress/testcafe-hammerhead#339)
- Then if error was not handled use standard `done` mechanism

**Comment by inikulin** [comment]
I'm working on this.

**Comment by inikulin** [comment]
This is currently blocking on the new API implementation

**Comment by inikulin** [comment]
@AlexanderMoskovkin I think we can move `Update reporters with new errors test data`-part to separate issues, because it's not MVP-blocking.

**Comment by AlexanderMoskovkin** [comment]
ok, I'll do this

**Comment by AlexanderMoskovkin** [comment]
` Update generator-testcafe-reporter with new decorator and test data` - the same?

**Comment by inikulin** [comment]
Yep
