### ISSUE TITLE
Test scenario doesn't work

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#3744]
https://isc.devexpress.com/Thread/WorkplaceDetails/T725283

import { Selector } from 'testcafe';

fixture `Dashboard`
    .page `https://st-common-next-frontend.azurewebsites.net/#/dashboard`;

test('Dashboard_debug', async t => {
    await t
        // See credentials from origin SC issue
        .typeText(Selector('.login-inputs[name="username"]'), '<secret>')
        .typeText(Selector('.login-inputs.password-field[name="password"]'), '<secret>')
        .click(Selector('button').withText('LOG IN'))
        .click(Selector('a').withText('Dashboard').find('.padding-left-20.ng-binding'))
        .wait(30000)
        .switchToIframe(Selector('#dashboardFrame'))
        .click(Selector('button').withText('Next'))
        .click(Selector('button').withText('Next'))
        .click(Selector('button').withText('Next'))
        .click(Selector('button').withText('Next'))
        .click(Selector('button').withText('Next'))
        .click(Selector('button').withText('Finish'));
});

**Comment by jia-ni** [comment]
so will be fixed end of month?

**Comment by AlexKamaev** [comment]
We have plans to fix the issue in the nearest future, however, we cannot give any estimates on this.

**Comment by miherlosev** [comment]
The maximum allowed size of the HTTP header for Node.js based apps is [8Kb](https://nodejs.org/api/http.html#http_http_maxheadersize).
During the test execution, your web app performs a request with a header of more than 8 Kb in size.
To fix the problem, run tests with the [--max-http-header-size](https://nodejs.org/api/cli.html#cli_max_http_header_size_size) flag.

```js
node --max-http-header-size=99999999 node_modules/testcafe/bin/testcafe chrome test.js
```
