### ISSUE TITLE
Error in Role initializer js error when running Testcafe on Browserstack

### ISSUE THREAD

**Issue by wjcheng1** [DevExpress/testcafe#3747]
I keep getting this "Error in Role initializer " js error when running in Chrome, Edge on Windows using Browserstack.  When I ran the same test on Chrome Mac on Browserstack it was fine and when I run the tests manually on Chrome/Edge on Widows on Browserstack there's also no js errors.   I'm using the suggested plugin: https://www.npmjs.com/package/testcafe-browser-provider-browserstack

```
JavaScript error details:
      TypeError: Object expected
         at r.sendServiceMsg (http://172.16.0.152:50065/hammerhead.js:7:23733)
         at d (http://172.16.0.152:50065/hammerhead.js:6:14894)
```

userRoles.ts:
```
export const regular = Role(config.pageUrl, async (t) => {
  await lp.switchLoginIframe();
  await lp.login(config.user, config.password, false);
  await t.switchToMainWindow();
});

export const admin = Role(config.pageUrl, async (t) => {
  await lp.switchLoginIframe();
  await lp.login(config.admin, config.adminpassword, false);
  await t.switchToMainWindow();
});
```

loginPage.ts:
```
async login(username:string, password:string, remember:boolean) {
    await t
      .typeText(this.username, username)
      .typeText(this.password, password);
    if (remember) {
      await t.click(this.rememberMe);
    }

    await t.click(this.loginBtn);
  }
```

login_test.ts:
```
const users = [
  { name: 'Admin User', type: admin },
  { name: 'Regular User', type: regular }];

for (const user of users) {
  test
  .meta({ level: 'sanity' })(`Valid ${user.name} login`, async (t) => {
    await t.useRole(user.type);
    await t
    .expect(Selector('i.icon.icon-Logout---med').visible).ok();
  });
}
```

**Comment by AlexKamaev** [comment]
It looks like some JS error appears on the client side during the Role initialization.
Please ensure that you are using the latest TestCafe version.
Also, since the cause of the issue is unclear, please try to run you tests with the [--skip-js-errors](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors) flag.
If it does not help, please provide us with a full working example which can demonstrate the issue on my machine. I'll check it on BrowserStack under my credentials.

**Comment by wjcheng1** [comment]
hi, yes using the latest testcafe.  I can get rid of the error with --skip-js-errors but then i would miss out on legitimate js errors as well.  I've actually seen quite a few random js errors when running with testcafe and it wasn't just with browserstack.  It would appear and then go away and each time the error is slightly different.   For example:

```
JavaScript error details:
      Error: error while retrieving userinfo
          at t [as constructor]
      (https://site/js/main.ee39841352d3a6087d3e.js:2:308750)
          at new t
      (https://site/js/main.ee39841352d3a6087d3e.js:2:310100)
          at
      https://site/js/main.ee39841352d3a6087d3e.js:2:326037
```
all these errors do not appear when I manually run the test and only appear when running with testcafe. Is there know issue with js errors and testcafe.

**Comment by AlexKamaev** [comment]
This is not a known issue. The cause of the issue could be on our side, however, I can not say anything definite without a working project. I would really appreciate it if your share you project or url to your project with us. If you can not share it here, you can send it at support@devexpress.com or create a simple example which demonstrates the issue.

**Comment by alexey-lin** [comment]
Hi @TonyKAmp,
 
I'm happy to hear you've managed to solve the problem. We would highly appreciate it if you could share your project with us so we could investigate what caused the error initially.

**Comment by TonyKAmp** [comment]
Sorry Alexey-lin 

> Hi @TonyKAmp,
>  
> I'm happy to hear you've managed to solve the problem. We would highly appreciate it if you could share your project with us so we could investigate what caused the error initially.

Sorry Alexey I cannot share my project as it's my company's.  However, I don't think it would be hard for you to reproduce.  Just use Roles api with the latest version of Firefox 69.0.0

**Comment by AlexKamaev** [comment]
@TonyKAmp

I was not able to reproduce the issue. Besides, we run our internal tests on BrowserStack in Firefox, and it works correctly. We would really appreciate it if you create a sample to demonstrate the issue to us.

**Comment by TonyKAmp** [comment]
> @TonyKAmp
> 
> I was not able to reproduce the issue. Besides, we run our internal tests on BrowserStack in Firefox, and it works correctly. We would really appreciate it if you create a sample to demonstrate the issue to us.

Another possibility is because I was running testcafe against firefox:headless within a docker container.  I recently had to pull my build jobs out of using docker because of instability of browser timeout.  I will try upgrading my firefox browser back to 69.0.0 and see what happens.

**Comment by AndreyBelym** [comment]
Thank you for your cooperation, please don't hesitate to share any results and asks any questions.

**Comment by bartzielonka** [comment]
I think I am struggling with the similar issue. 
Happens on Safari 13.1, when executing window.history.back() or go(-1) within Role.

`1) - Error in Role initializer -
      TypeError: Cannot read property '0' of null`
`Error in Role initializer -
      Unhandled promise rejection:`
      
      TestCafeErrorList { items: [ UncaughtErrorInTestCode { code: 'E2', isTestCafeError: true, callsite: [CallsiteRecord], errMsg: "TypeError:
      Cannot read property '0' of null", originError: TypeError: Cannot read property '0' of null
      at DecodingTransformer.transform (/Users/bart/Documents/e2e-tests/node_modules/replicator/index.js:271:38)
      at module.exports.Replicator.decode (/Users/bart/Documents/e2e-tests/node_modules/replicator/index.js:559:24)
      at ClientFunctionBuilder._processResult
      (/Users/bart/Documents/e2e-tests/node_modules/testcafe/src/client-functions/client-function-builder.js:146:32)
      at /Users/bart/Documents/e2e-tests/node_modules/testcafe/src/client-functions/client-function-builder.js:141:25
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5) } ], name: 'TestCafeErrorList' `

Workaround:
1. Save url as variable. 
2. Use .navigateTo later.

I could share the project etc. however NDA will be needed.

**Comment by miherlosev** [comment]
Hi @bartzielonka 

It looks like a separate problem. Please create a separate issue on Github if you can create a simple example to reproduce.

**Comment by bartzielonka** [comment]
@miherlosev will not bother adding issue.

Created new project. Tried reproducing it. No luck. If I will find exact steps will add it and let you know.

Thank you for your concern anyway!
