### ISSUE TITLE
onRequestTo / respond with a POST and 'access-control-allow-origin': '*' is still giving 222 error code 

### ISSUE THREAD

**Issue by jcollum-nike** [DevExpress/testcafe#3748]
Related https://github.com/DevExpress/testcafe/issues/2614#issuecomment-404208442

### What is your Test Scenario?
I need to override a POST to an endpoint so my test can run inside a docker container. 
 
### What is the Current behavior?

I'm overriding with `onRequestTo / respond` but still seeing a 222 error code instead of the 200 I told it to send. 
 
### What is the Expected behavior?

I should get back a 200 with the response object I specified

### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example): sorry, can't share that 

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
const loginResponse = {
  user_id: '--redacted--',
  access_token:
   '--redacted--',
  refresh_token:
    '--redacted--',
  expires_in: '3600',
  token_type: 'bearer',
};

const mockLogin = RequestMock()
  .onRequestTo(/.*portal.site.com\/login/)
  .respond(loginResponse, 200, { 'access-control-allow-origin': '*' })

```
</details>

<details>
<summary>Your complete test report:</summary>

Console output: `RequestMock: CORS validation failed for a request specified as { url: /.*portal.site.com\/login/ }`

The test passes if I don't mock the login but I need to mock the login to get the site to run inside a docker container. 

</details>

<details>
<summary>Screenshots:</summary>

This is the response to the POST

![image](https://user-images.githubusercontent.com/40277227/56701276-0e809e00-66b3-11e9-8df6-04565a05c1b4.png)

</details>

### Steps to Reproduce:

See test code above 

### Your Environment details:
 
* testcafe version:                  1.1.3
* node.js version:                    8.15.1
* command-line arguments:  n/a
* browser name and version: Chrome 73
* platform and version:         OSX
* other:

**Comment by AlexKamaev** [comment]
Thank you for the provided information. We need additional time to research this behavior.

**Comment by jcollum-nike** [comment]
Thanks. Is this enough info?

**Comment by miherlosev** [comment]
@jcollum-nike 

Try to debug the `CORS` validation mechanism on your side.
Please perform the following steps:
* Open the './node_modules/testcafe-hammerhead/lib/request-pipeline/xhr/same-origin-policy.js' file on your machine and set a breakpoint in function check(ctx) {}.
* Check how `CORS` validation mechanism works for the `XHR` request that matches the '/.*portal.site.com/login/' rule.

**Comment by jcollum-nike** [comment]
OK I will look, it might be a few days thoughwhy the Track Shipment buttons aren’t showing up in the docker container

**Comment by jcollum-nike** [comment]
We fixed this by setting these headers: 

```
const corsHeaders = {
  'access-control-allow-origin': settings.baseUrl,
  'access-control-allow-credentials': 'true',
  'content-type': 'application/json',
};
```

where `settings.baseUrl` in this case is something like `http://host.docker.internal:3000` or `http://localhost:3000`
