### ISSUE TITLE
Individual Interaction Actions

### ISSUE THREAD

**Issue by bytesnz** [DevExpress/testcafe#3750]
Copying from https://github.com/DevExpress/testcafe/issues/2054#issuecomment-486302449

### What is your Test Scenario?
Trying to test first-draft - an online interactive drawing/annotation app. An example of the interactions I need to be able to test (more at https://gitlab.com/MeldCE/first-draft/issues/59#tool-use) is
l-mousedown, mousemove, **run some checks**, _shiftdown, mousemove, shiftup_, **run some checks**,  mousemove, l-mouseup, **run final checks**

While is probably quite an extreme case of needing to test interactions, it could be useful other places, eg testing a map fetches tiles as you pan around the map.

### What are you suggesting?
Creating actions for interactions, eg ...down ...move ...up

Having the ability to run assertions part way through an interaction would be super useful (eg dragging a file onto a div to ensure the drop target is showing) and I think this would only be possible if the individual phases were available (eg, mousedown, mouseup, mousemove). 

Doing this (with the addition of an interaction pause action) would also help solve #2803 and #1374.

There is also a case for doing the same (or making sure they are included) for touch (#527) and pointer events - You could make them named after pointer (`PointerDown`, `PointerUp`, `PointerMove`...), give the type of device as one of the parameters, and then generate the other events as required.

### What alternatives have you considered?
- Using/extending DragElement action, but it won't allow for mid interaction tests
- Other testing libraries - there is nothing really out there for doing this kind of testing

### Additional context
Maybe this would be too complicated and could be a separate module once #1535 is completed

**Comment by owen-m1** [comment]
+1, really need a way of continuing the same drag to multiple different positions

**Comment by bytesnz** [comment]
I had a look at hammerhead (the code used for the automation) and it seems to already have the functionality required, it would just be a case of implementing in testcafe. However, testcafe would need to be able to track the state of keys and pointers so that all the actions work as expected. For example, if you extended it to keys as well doing something like `.keydown('shift').click(...)`, the click action would need to know that the shift key was pressed.
