### ISSUE TITLE
nth() strange behavior

### ISSUE THREAD

**Issue by benmonro** [DevExpress/testcafe#3755]
### What is your Test Scenario?

Custom selector that returns an array of nodes, the test then uses `nth` to click on the buttons used in the selector.
 
### What is the Current behavior?

using testcafe-testing-library, If I use `t.click` in reverse order, the test passes, however, if I use them in ascending order, it will never find the 2nd (1th) element.
```javascript
test('getAllByText (working)', async t => {
  const chans = getAllByText(/^Jackie Chan/)
  const count = await chans.count

  await t.expect(count).eql(2)

  await t.click(chans.nth(1))
  await t.click(chans.nth(0))
})

test('getAllByText (broken)', async t => {
  const chans = getAllByText(/^Jackie Chan/)
  const count = await chans.count

  await t.expect(count).eql(2)

  await t.click(chans.nth(0))
  await t.click(chans.nth(1))
})
```
 
### What is the Expected behavior?

 `nth()` works in both cases.
### What is your web application and your TestCafe test code?

 i've put an example of this on a branch of testcafe-testing-library that you can find here: https://github.com/benmonro/testcafe-testing-library/blob/fix/order_nth_issue/tests/testcafe/selectors.js#L44

Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```
➜  testcafe-testing-library git:(master) ✗ npm run test:testcafe

> testcafe-testing-library@0.0.0-development test:testcafe /Users/bmonro001/Code/testcafe-testing-library
> npm-run-all --silent --parallel --race test:testcafe:serve test:testcafe:run

UPDATE AVAILABLE The latest version of `serve` is 11.0.0
INFO: Accepting connections at http://localhost:13370
 Running tests in:
 - Chrome 73.0.3683 / Mac OS X 10.14.4

 selectors
 ✓ getByPlaceHolderText
 ✓ getByText
 ✓ getByLabelText
 ✓ getByAltText
 ✓ getByTestId
 ✓ getAllByText
 ✖ getAllByText (broken)

   1) The specified selector does not match any element in the DOM tree.

         | Selector([function])
       > |   .nth(1)

      Browser: Chrome 73.0.3683 / Mac OS X 10.14.4

         56 |  const count = await chans.count
         57 |
         58 |  await t.expect(count).eql(2)
         59 |
         60 |  await t.click(chans.nth(0)).wait(3000)
       > 61 |  await t.click(chans.nth(1))
         62 |})
         63 |
         64 |test('queryAllByText', async t => {
         65 |  await t.expect(queryAllByText('Button Text').exists).ok()
         66 |  await t.expect(queryAllByText('Non-existing Button Text').exists).notOk()

         at click (/Users/bmonro001/Code/testcafe-testing-library/tests/testcafe/selectors.js:61:11)
         at step (/Users/bmonro001/Code/testcafe-testing-library/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
         at <anonymous> (/Users/bmonro001/Code/testcafe-testing-library/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13)


 ✓ queryAllByText
 - getByText in container
 - getByTestId only throws the error message


 1/8 failed (18s)
 2 skipped

INFO: Gracefully shutting down. Please wait...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testcafe-testing-library@0.0.0-development test:testcafe: `npm-run-all --silent --parallel --race test:testcafe:serve test:testcafe:run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the testcafe-testing-library@0.0.0-development test:testcafe script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bmonro001/.npm/_logs/2019-04-26T15_22_40_005Z-debug.log
```
</details>

### Steps to Reproduce:

1. checkout the branch located here: https://github.com/benmonro/testcafe-testing-library/tree/fix/order_nth_issue
3. `npm install`
4. `npm run test:testcafe`
 
### Your Environment details:
 
* testcafe version:  1.1.2                 
* node.js version:     10.11.0               
* command-line arguments: testcafe 
* browser name and version: chromium
* platform and version:  macOS        
* other:

**Comment by AlexKamaev** [comment]
I've reproduced the issue, however, I do not think it is a bug.
You have two buttons with text `Jackie Chan`. You click the first one, and its text changes, and so the results of your selector change as well because now there is only one button with text `Jackie Chan`.
To resolve this, do the following:
```JS
  await t.click(chans.nth(0));
  await **t.click(chans.nth(1));
```
