### ISSUE TITLE
page loaded event

### ISSUE THREAD

**Issue by benmonro** [DevExpress/testcafe#3758]
### What is your Test Scenario?

For testcafe-testing-library, I'd like to support a use case for when navigation occurs (clicking a link, reloading, etc).  In order to do this, I need to inject dom-testing-library into the DOM on each page-load
### What are you suggesting?

I propose adding an event subscription which I can subscribe to in a test or hook.

```javascript

await t
  .on("pageload", () => addTestcafeTestingLibrary(t))
  .click(getByText("link to other page")
  .click(getByText("link to yet another page")
  .expect(getByText("element on other page").exists)
  .ok();

```

### What alternatives have you considered?

I have a work around, but it requires manually injecting after the link click,  it works, but it's toothy and cumbersome.  For example, in the example above, i have to do this:

```javascript
await addTestCafeTestingLibrary(t);

await t.click(getByText("link to other page"));

await addTestcafeTestingLibrary(t);

await t.click(getByText("link to yet another page"));

await addTestcafeTestingLibrary(t);

await t
  .expect(getByText("element on other page").exists)
  .ok();



```
quite verbose as you can see.  hence the desire to have an event I can subscribe to for whenever a page load occurs....

**Comment by AlexKamaev** [comment]
Thank you for your proposal. We'll consider its implementation with the team if the idea becomes popular.

**Comment by benmonro** [comment]
Hi @AlexKamaev Thank you.  Are there any work arounds you know of that I can use in the meantime to allow me to inject scripts into the page whenever a navigation event occurs?

**Comment by LavrovArtem** [comment]
You can try to wrap the `click` action and use it for clicks that lead to the page reload. For example:
```js
const clickThatLeadsToReload = async (t, selector) => {
    await t.click(selector);
    await addTestcafeTestingLibrary(t);
};

await clickThatLeadsToReload(t, getByText("link to other page"));
```

**Comment by benmonro** [comment]
@alexkamaev I'd be happy to submit a PR of you could point me in the right direction... Like where does testcafe interact with hammer head?

**Comment by benmonro** [comment]
found a  solution using the testRun class.

**Comment by corysimmons** [comment]
@benmonro Can https://testing-library.com/docs/testcafe-testing-library/intro#known-issues be removed since it looks like you fixed this in https://github.com/testing-library/testcafe-testing-library/commit/5998cfd7671ac0643bc351fc74cceb4a939c06d0 ?

**Comment by benmonro** [comment]
Ah yes.  Nice catch.  Thanks

**Comment by corysimmons** [comment]
@benmonro No, thank _you_. Really excited to use these two tools together. 🙇‍♂️
