### ISSUE TITLE
`window.location` reflects TestCafe test URL

### ISSUE THREAD

**Issue by green-arrow** [DevExpress/testcafe#3760]
I'm not really sure what happened to cause this, because from what I can see our TestCafe version hasn't been updated in a while. For some reason, `window.location` reflects the TestCafe server, not the application being tested. We use `window.location.origin` along with other things in the application, and this behavior causes our app to break.

### What is your Test Scenario?

Test a page that uses the URL for business logic.
 
### What is the Current behavior?

`window.location` returns properties which all have the TestCafe URL in them:

```
{
  "href": "http://192.168.1.10:56696/EwCkQ95Wu/http://localhost:3000/loops",
  "ancestorOrigins": {},
  "origin": "http://192.168.1.10:56696",
  "protocol": "http:",
  "host": "192.168.1.10:56696",
  "hostname": "192.168.1.10",
  "port": "56696",
  "pathname": "/EwCkQ95Wu/http://localhost:3000/loops",
  "search": "",
  "hash": ""
}
```
 
### What is the Expected behavior?

`window.location` should reflect the application being tested and not the TestCafe URL.
### Your Environment details:
 
* testcafe version:                   1.1.0
* node.js version:                    10.13.0
* command-line arguments:  testcafe chrome tests/acceptance-tests/**/*.ts -e
* browser name and version: Chrome 73
* platform and version:          macOS 10.14.4
* other:

**Comment by AlexKamaev** [comment]
It's not expected behavior. Still, I was not able to reproduce it in a sample project. Please try the following code:
```HTML
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>gh-1999</title>
</head>
<body>
<script>
    window.setTimeout(function () {
        document.getElementById('result').innerHTML = JSON.stringify(window.location);
    }, 500);
</script>
<div id="result"></div>
</body>
</html>
```
```JS
fixture `fixture`
    .page `http://127.0.0.1:8081`;

test(`test`, async t => {
    await t.click('body');
    await t.debug();
});
```
In my case the output is the following:
```JSON
{"href":"http://127.0.0.1:8081/index.html","ancestorOrigins":{},"origin":"http://127.0.0.1:8081","protocol":"http:","host":"127.0.0.1:8081","hostname":"127.0.0.1","port":"8081","pathname":"/index.html","search":"","hash":""}
```
It seems to be valid. Could you run my case on your machine?
If the issue occurs only in your case, we need to research your project. So, please provide us with a working example or url to your project which demonstrates the issue.

**Comment by green-arrow** [comment]
@AlexKamaev - I created a new `create-react-app` and used your test case and it works correctly. It must be something else specific to our project causing this issue.
