### ISSUE TITLE
Testcafe scripts always switches to newly opened window

### ISSUE THREAD

**Issue by saiparth** [DevExpress/testcafe#3762]
### What is your Test Scenario?

 browse the page which has pop up blocker checker on load and observe that testcafe switches to pop up blocker checker window instead of main page
### What is the Current behavior?

 Test cafe switches to newly opened window instead of staying in browsed page
### What is the Expected behavior?

 It should switch to window if we have script to that. or at least i should be able to close the other window
### What is your web application and your TestCafe test code?

https://pegasus5.qa.pegasus.pearsoncmg.com/Pegasus/frmLogin.aspx?s=3

 
```js
 import { ClientFunction } from 'testcafe';

fixture `My second fixture`
    .page `https://pegasus5.qa.pegasus.pearsoncmg.com/Pegasus/frmLogin.aspx?s=3`;
   
    const getLocation = ClientFunction(() => window.location.href);
    test('second test', async t => {
        await t
        //.expect(getLocation()).contains('about:blank')
        //.expect(getLocation()).contains('pegasus')
        .wait(15000);
        //await (()=>window.close());
            //const goBack=ClientFunction(()=>window.history.back());
            //await goBack();
            //await t.expect(getLocation()).contains('pegasus');
           await t.typeText('#username','test')
            .click('#mainButton');
    });
```

### Steps to Reproduce:

1. run the above code
2. it will browse the url ,now there is a pop up blocker window which opens and closes automatically when i browse manually.if i run through test cafe,it will switch to that pop up and blank page will be loaded
3. I tried using window.close ,window.history etc...but whatever I may do,it will browse and switch to newly opened window and i cant proceed further
 
### Environment details:
 
* testcafe version:  0.20.5                 
* node.js version:     v10.0.0               
* command-line arguments:  
* browser name and version: chrome 73 
* platform and version:  win 10        
* other:

**Comment by miherlosev** [comment]
Hi @saiparth 
 
The site uses the [window.open](https://developer.mozilla.org/en-US/docs/Web/API/Window/open) function to detect the way how to display popups.
At present, TestCafe doesn't support work with sites whose code contains the `window.open` call for the main browser window.
 
As a workaround, you can modify the 'checkPopUpEnabled' function from https://e2e-comms-stg.pearson.com/osbrowserchecker/stg/checker-module.min.js to not use the `window.open` function during testing.
 
Also, you can track https://github.com/DevExpress/testcafe/issues/912 to be notified of progress with the implementation.
