### ISSUE TITLE
addRequestHooks execution sequence broken

### ISSUE THREAD

**Issue by JWvP** [DevExpress/testcafe#3766]
I've searched through the issues with 'addRequestHooks' as keyword, only got 5 already closed issues from last year. So if there is some duplicate report then I am sorry.

What I gather from the documentation something like the code below should be possible, where the switch between the 2 hooks is detrimental for the outcome of said scenario:
`import {RequestMock } from 'testcafe'`
`import {foo, blabla, woohoo } 'from mock.helper'`

`const faa   = RequestMock()`
`    .onRequestTo('http://external-service.com/api/')`
`    .respond({ data: value })`

`fixture 'My fixture'`
`    .page('http://example.com')`
`    .requestHooks(foo, blabla, woohoo)`

`test`
`    ('My test', async t => {`
`    await t`
`         .click(something)`
`        .expect(somethingElse)`
`         .removeRequestHooks(foo)`
`         .addRequestHooks(faa)`
`         .click(anotherSomething)`
`         .expect(somethingCompletelyDifferent)`
`})`

However, and I gather this has something to do with the async part, in the above code I find that at the start of the scenario foo has already been switched for faa.

Also; I've tried adding foo at the beginning of the scenario, thinking that the issue might be caused by the fact that the hook is part of the fixture, but this does not seem to be the case.
(currently on version 1.1.0, but also confirmed on 1.1.1)

useCase:
Being able to switch between mock responses so that I can check whether the frontend does indeed correctly responds to changes made by the user.

**Comment by miherlosev** [comment]
Hi @JWvP 

All request mock works independently between themselves. If your test depends on the mocks execution order then it points to the mock's configuration mistakes.
I am afraid the provided information is very abstract and it is not sufficient to find the cause of the issue. Could you please provide a small example so that we can reproduce it on our side?

**Comment by JWvP** [comment]
Hi, sorry for the late response.

The abstract example i've given is just about a straight copy from your documentation:

`import { RequestLogger, RequestMock } from 'testcafe';

const logger = RequestLogger('http://example.com');
const mock   = RequestMock()
    .onRequestTo('http://external-service.com/api/')
    .respond({ data: 'value' });

fixture `My fixture`
    .page('http://example.com')
    .requestHooks(logger);

test
    .requestHooks(mock)
    ('My test', async t => {
    await t
         .click('#send-logged-request')
         .expect(logger.count(() => true)).eql(1)
         .removeRequestHooks(logger)
         .click('#send-unlogged-request')
         .expect(logger.count(() => true)).eql(1)
         .addRequestHooks(logger)
         .click('#send-logged-request')
         .expect(logger.count(() => true)).eql(2);
})`

found at:
https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/attaching-hooks-to-tests-and-fixtures.html

**Comment by LavrovArtem** [comment]
Thank you for the additional information. I've reproduced this behavior and created the [new feature request](https://github.com/DevExpress/testcafe/issues/3861). I've also described the workaround there. Track the new thread to stay informed about progress.
