### ISSUE TITLE
Allow device names newer than 2014 (viewportsizes.com)

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DevExpress/testcafe#3767]
### Are you requesting a feature or reporting a bug?
Reporting a bug

### What is your Test Scenario?
I'd like to test at resolutions of devices such as the Pixel series and newer iPhones.

### What is the Current behavior?
http://viewportsizes.com only has devices up through 2014's iPhone 6.

### What is the Expected behavior?
...more new than that?

### How would you reproduce the current behavior (if this is a bug)?
https://devexpress.github.io/testcafe/documentation/test-api/actions/resize-window.html#fitting-the-window-into-a-particular-device

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. I agree that the device list from `http://viewportsizes.com` is outdated and incomplete. The website owner doesn't support it anymore. It means that we need to find a different database that can be used as a source of device metrics. Do you have any suggestions on websites or APIs that can provide such information?

**Comment by JoshuaKGoldberg** [comment]
https://en.wikipedia.org/wiki/Comparison_of_high-definition_smartphone_displays is pretty complete, if that helps. I just Googled around till I found it 😉.

**Comment by devmondo** [comment]
I see that the http://viewportsizes.com/ is gone already! so it might be a good idea to update the docs?

this library is outdated, but it might help as base https://www.npmjs.com/package/viewport-list

hope that helps :)

**Comment by helen-dikareva** [comment]
Thank you for drawing our attention to this. Seems like the time to change the source of device resolutions has definitely come. I'll add this issue to the Planned milestone.

**Comment by JoshuaKGoldberg** [comment]
FWIW, this exists in https://github.com/DevExpress/testcafe-browser-tools/blob/master/data/devices.json.
