### ISSUE TITLE
Test hangs after doing navigateTo()

### ISSUE THREAD

**Issue by wjcheng1** [DevExpress/testcafe#3768]
### What is your Test Scenario?
After I do some action on the page then do a navigateTo(), the test just hangs.  Here's my code:

test.ts:
```
const lp = new loginPage;

test.meta({ level: 'sanity' })('test navigate', async (t) => {
  await lp.switchLoginIframe();
  await t.click(lp.forgotpassword);
  await t.navigateTo(url);
});
```
loginPage.ts:
```
this.forgotpassword = Selector('#kc-forgot-pword-link');

async switchLoginIframe() {
    await t
      .expect(this.loginIframe.exists).ok({ timeout: 5000 })
      .switchToIframe(this.loginIframe);
  }
```

I see the click of the forgotpassword link, and loads correctly.  Then I see browser navigate to the new url after that it just hangs.

### What is the Current behavior?
Browser just hangs and nothing happens
 
### What is the Expected behavior?
Test should end after navigateTo()
 
### Your Environment details:
 
* testcafe version:                 1.1.3
* node.js version:                   v10.13.0
* command-line arguments:  testcafe chrome e2e/testcafe/forgotpassword_test.ts --skip-js-errors --test-meta level=sanity
* browser name and version: Chrome 73
* platform and version:          Mac OS X 10.14.3

**Comment by LavrovArtem** [comment]
This information is not sufficient to find the cause of the issue. There can be many causes, and therefore we cannot give you any advice without analyzing your page or code. Could you please provide a page or a small example so that we can reproduce it on our side?

**Comment by wjcheng1** [comment]
unfortunately i cannot share the site as but the code I'm using is pretty much listed above. it seems that it gets stuck on the await t.navigateTo() after performing some action on the page.  it doesn't execute anything after the navigateTo() line.  the site I'm navigate to is under a different domain name but not sure if that matters.  i tried navigating to the same domain the probe was still there.

**Comment by wjcheng1** [comment]
a little more context, i'm testing our forgot password functionality.  i click on forgot password, enter the email and check gmail for the reset password email. i get the link from the email and navigates to that url.  the page loads fine but then the test just hangs.  it doesn't close the browser and doesn't end the test.

**Comment by miherlosev** [comment]
Hi @wjcheng1 

Unfortunately, it's very difficult to find the cause of the problem without direct access to your web application. Feel free to reopen the issue if you can provide direct access to your web site or can create an example where we can reproduce the problem.
