### ISSUE TITLE
JS error only when running testcafe

### ISSUE THREAD

**Issue by jia-ni** [DevExpress/testcafe#3769]
Test Scenario - When I click the submit button the above occurs through testcafe only.  This prevents me from creating this test because my form will not be submitted.

1) Enter in all required fields on the form field
2) Submit the form
3) above JS error occurs

When testing this page manually above error does not occur

through the console I found it errorred on:
jQuery.filter = function( expr, elems, not ) {
	var elem = elems[ 0 ];

	if ( not ) {
		expr = ":not(" + expr + ")";
	}

	return elems.length === 1 && elem.nodeType === 1 ?
		jQuery.find.matchesSelector( elem, expr ) ? [ elem ] : [] :
		jQuery.find.matches( expr, jQuery.grep( elems, function( elem ) {
		*	return elem.nodeType === 1;*
		}));
};

test code:
test('Register Proxy Registration', async t => {
    await t
    .click(proxyRules.addProxyDefinition)
    .click(proxyRules.proxyCreationDefinitionButton)
    .typeText(proxyRules.proxyNameField, 'HTTP proxy')
    .typeText(proxyRules.proxyDescriptionField, 'proxy HTTP description')
    .click(proxyRules.proxyTypeDropdown)
    .click(proxyRules.proxyTypeOption.withText('http'))
    .typeText(proxyRules.proxyIpField, '10.10.10.10')
    .typeText(proxyRules.proxyPortField, '8080')
    .click(proxyRules.proxyCreationDefinitionButton)

**Comment by AlexSkorkin** [comment]
The information you provided is insufficient for me to determine the cause of the issue and find a precise solution.  
The https://director.jia.qa.verodin.cloud URL is not reachable. Would you please provide us with the public accessible URL that you are testing, so we can examine the issue? Thank you in advance.

**Comment by jia-ni** [comment]
Sorry @AlexSkorkin the URL is only internal and we dont have public facing.  But what I can tell you is when I test it out manually I do not get that JS error and I am able to click on the button.  But through TestCafe I am getting that JS error and cannot click on the button

**Comment by LavrovArtem** [comment]
Thank you for the additional information. However, this information is not sufficient to find the cause of the issue. We cannot give you advice without your code. Would you please create a simple example where we can reproduce this issue?

**Comment by jia-ni** [comment]
so I tried the same test on testcafe studio and it is working.  same exact button and there's no JS error.    Are the code base different between the testcafe studio and testcafe?

**Comment by miherlosev** [comment]
Hi @jia-ni 

Could you please specify testcafe and TestCafe Studio versions?
 
Also, please provide the content of the https://director.jia.qa.verodin.cloud/assets/application-686f670f6932d2d7e39c8caea89fa50b.js asset.
I think this information will be sufficient for us to reproduce the problem.

**Comment by jia-ni** [comment]
testcafe `1.1.4`
testcafe studio `0.4.5`

**Comment by jia-ni** [comment]
[assets_file.txt](https://github.com/DevExpress/testcafe/files/3162802/assets_file.txt)

**Comment by AlexKamaev** [comment]
I afraid it is very difficult to find the cause of the issue based on the provided file with scripts. In this case it's better to prepare a sample project which demonstrates the issue based on your site and share it here like @LavrovArtem mentioned.

**Comment by jia-ni** [comment]
so no one else is having this issue?

**Comment by Farfurix** [comment]
@jia-ni 

Hello,

We didn't face similar issues earlier. So, it is difficult to determine the cause of this problem. Please provide us with a sample project which demonstrates it.

**Comment by jia-ni** [comment]
I cant... I'll just seek another solution

**Comment by Farfurix** [comment]
@jia-ni 

We discussed this issue with the team again and think that this issue is related to this problem: [Test scenario doesn't work](https://github.com/DevExpress/testcafe/issues/3744). You might want to check out the new TestCafe version once again once we fix the related issue.

**Comment by jia-ni** [comment]
so I saw you guys close the linked issue from @Farfurix.  Will you guys fix the problem or no?

**Comment by Farfurix** [comment]
@jia-ni 

I suggest you use the [`--max-http-header-size`](https://nodejs.org/api/cli.html#cli_max_http_header_size_size) flag from [this comment](https://github.com/DevExpress/testcafe/issues/3744#issuecomment-492688062).

If it doesn't help, we still need the [additional information mentioned above](https://github.com/DevExpress/testcafe/issues/3769#issuecomment-489990917).
