### ISSUE TITLE
Please give example of MongoDB data being used in a test

### ISSUE THREAD

**Issue by doverradio** [DevExpress/testcafe#3770]
#### HEADS UP!

For TestCafe API, usage and configuration inquiries, we recommend [StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)).

You may also find answers in our up-to-date [documentation](https://devexpress.github.io/testcafe/documentation/getting-started/) and [answered questions](https://stackoverflow.com/questions/tagged/testcafe) on StackOverflow. This may save your time.

If you have already looked there and have not found an appropriate answer, [file a new question on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe).

There's zero mention in here of how to take in data from MongoDB and use it in TestCafe scripts.  

I was able to find mention on Google of someone saying you could use ClientFunction() with the node MongoDB driver but I cannot find any example anywhere.

**Comment by AlexSkorkin** [comment]
Hi,
 
We don't have such a sample. I recommend that you look for such a sample [on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.
 
We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafeontributing)).

**Comment by doverradio** [comment]
Can you pass a value from MongoDB (or any database for that matter) into a live running TestCafe test so it will type that value out during the test?

https://stackoverflow.com/questions/56016619/is-there-any-way-to-use-mongodb-with-testcafe

I found this which phrases this question perfectly.

Just even a simple 'no, this is not possible' would be greatly helpful!  Thank you in advance!

**Comment by AndreyBelym** [comment]
It's possible to access MongoDB in a TestCafe test. The example from the StackOverflow question contains a mistake. I will answer the question and provide the corrected example.
