### ISSUE TITLE
TestCafe true parallelism failed after Chrome74 upgrade, was reliable till Chrome 73

### ISSUE THREAD

**Issue by jiteshsojitra** [DevExpress/testcafe#3771]
We are using latest TestCafe 1.1.3 for running automation tests, in every machine we were opening 8-10 chrome browser instances and our tests were very very fine. Since Chrome 74 launched, within couple of hours circleci/node:11-browsers image was updated with Chrome 74 and entire automation started failing.

Now we just have 10-15% PASSED rate with Chrome 74 compare to 99% PASSED rate with Chrome 73. Is this due to TestCafe multiple session or Chrome 74 performance issue? It looks like TestCafe is hanging with multiple sessions in Chrome 74 (8-10 browser instances), browser leaves control and hangs. It is pretty difficult to know what's going on inside TestCafe / Chrome.

Even we tried by decreasing browser instances from 8 till 1 and we saw PASSED rate little increased but results was quite unreliable even with 1 instance. Again it has been observed TestCafe proxy causing this issue?

For now, we have reverted back to old Chrome 73 image (circleci/node:11.13-browsers). We need to upgrade browser which we everyone know to support latest application code. Please resolve this issue and if needed can TestCafe talk with Google to fix the issue from Chrome 74 side if any?

Please let me know if you need more details.

# Problem:
TestCafe browser proxy session seems created but opening application doesn't load UI and loading continues after running couple of tests in each container. Due to this issue, application login page not displayed at all and TestCafe says chrome hanged/closed. TestCafe proxy session fails?

Tried with less number of browser instances to 1 instance but no luck, browser crashes even with 1 instance after running certain tests and there is no fixed pattern for crashes.

# Error:

    GeneralError: The Chrome 74.0.3729 / Linux 0.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.
    at BrowserConnection._createBrowserDisconnectedError (/home/circleci/repo/node_modules/testcafe/src/browser/connection/index.js:116:16)
    at Timeout._onTimeout (/home/circleci/repo/node_modules/testcafe/src/browser/connection/index.js:121:30)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
    code: 'E1002',
    data: [ 'Chrome 74.0.3729 / Linux 0.0.0' ],
    callsite: CallsiteRecord {
    filename: '/home/circleci/repo/tests/testcafe/pages/common.js',
    lineNum: 216,
    callsiteFrameIdx: 4,
    stackFrames: [
       [CallSite],  [CallSite],
       [CallSite],  [CallSite],
       [CallSite], CallSite {},
       [CallSite],  [CallSite],
       CallSite {},  [CallSite],
       [CallSite],  [CallSite],
       [CallSite], CallSite {},
       [CallSite],  [CallSite],
       [CallSite],  [CallSite]
    ],
    isV8Frames: true
    },
    isRejectedDriverTask: true
    }
    ERROR The Chrome 74.0.3729 / Linux 0.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.

![image](https://user-images.githubusercontent.com/21263826/57184892-1bd22f80-6ee0-11e9-95cc-716102db01ee.png)

![image](https://user-images.githubusercontent.com/21263826/57177694-6b830d80-6e84-11e9-9d85-4c0a20eb4496.png)

![image](https://user-images.githubusercontent.com/21263826/57184892-1bd22f80-6ee0-11e9-95cc-716102db01ee.png)

# Command:

    "test:testcafe": "cross-env HTML_REPORT_PATH='test-reports/testcafe-smoke' testcafe -e chrome 'tests/testcafe/tests' -T 'Smoke' --test-meta web=true -r html-testrail --app 'npm run serve' --app-init-delay 5000 -S -s test-reports/screenshots",

### What is the Current behavior?
We have to temporarily revert back to Chrome 73 and respective node browser image due to this blocker issue. Even i tried with latest Chrome Dev 76 version but no luck!
 
### What is the Expected behavior?
Everything should be fine with Chrome 74+ like before because there is no other change from application or TestCafe side hopefully.
 
### Your Environment details:
 
* testcafe version:  1.1.3/1.1.0
* node.js version:  11.0

**Comment by jiteshsojitra** [comment]
Similar to https://github.com/DevExpress/testcafe/issues/2194 but things were pretty for us till Chrome 73.

**Comment by AndreyBelym** [comment]
Thank you for your report. Have you checked that your Chrome 73 and Chrome 74 versions use the same TestCafe version? If it is so, it can be a Chrome bug introduced by the update, you can submit a bug report to the Chrome team: http://dev.chromium.org/for-testers/bug-reporting-guidelines. Also, 8-10 browser instances demand a lot of resources from a container host. A very minor performance bug can lead to a problem. Have you tried to decrease the number of concurrent browser instances?

I can't reproduce it with my example sites. Could you please provide a sample page and a sample Docker image that can be used to reproduce the problem.

**Comment by jiteshsojitra** [comment]
>> Have you checked that your Chrome 73 and Chrome 74 versions use the same TestCafe version?
Yes, latest 1.1.3.

>> If it is so, it can be a Chrome bug introduced by the update.
It is definitely a issue and agreed more suspect from Chrome. The interesting thing, TestCafe proxy hangs even for 1 instance sometime and high intermittency. For that reason, we should check whether anything we can check when TestCafe creates proxy session. We need to do memory profiling and high LOE task to report bug to Chrome which they seems introduced.

>> Have you tried to decrease the number of concurrent browser instances?
Not sure why external world don't see this issue but we are constantly observing it and had to revert back to Chrome 73. We checked only 2-3 instance sometime fine for Chrome 74, but seeing crashes often there too and suspect seems memory consumption.

Sharing some screenshots where loading of client fails and Chrome log doesn't report error when using --log-level=1. Pretty difficult to capture log due to intermittency and nothing it reports, i still suspect memory usage on Chrome 74. I can reproduce this issue locally and through CircleCI with Chrome74, everything is still fine with Chrome 73.

![image](https://user-images.githubusercontent.com/21263826/57394490-517a5f80-71e3-11e9-929b-c63e86ab9f4d.png)

![image](https://user-images.githubusercontent.com/21263826/57394556-7b338680-71e3-11e9-991b-188101cb9630.png)

**Comment by AndreyBelym** [comment]
Yes, I see your screenshots with errors from multiple failed requests. It can be caused by a memory leak as you have guessed. If this assumption is correct, we need an example to debug the problem and find its cause. Looks like you use the development version of Zimbra in your tests. Can I use the public version of the website to reproduce the issue?

**Comment by domasx2** [comment]
Hi, seeing similar issue after updating to chrome 74. If  parallelism > 1, testcafe randomly fails to start with chrome instances showing "disconnected"

**Comment by AlexKamaev** [comment]
@domasx2 Thank you for your inquiry. If you have some additional info or a public url that helps us reproduce the issue, please share it with us.

**Comment by Evilweed** [comment]
This issue still occurs. In order to reproduce it, create many tests and spec files that go to heavy website (for example https://app.packhelp.com/box/design?dielineMode=false&quantity=500&sku=box-eu--mailer-box--59--cardboard-white-one-side--print-eco-color--foil-none) and reload the page couple times. Make those tests run in CircleCI (free tier), set the parallelism to 3-4, quarantine to true. Set the reporters to screenshot on fail, spec, allure, junit. And run couple builds - one of them will fail with this issue.

**Comment by jiteshsojitra** [comment]
I'm with Evilweed and observing issues daily for our site. Evildweed, please help to reproduce the issue to TestCafe team if you have public website. If you increase browser instances then it would be very easy to reproduce further.

**Comment by AlexKamaev** [comment]
@Evilweed
 
Thank you for providing the public url. I would also appreciate it if you provide us with the full tests package, which demonstrates the issue.
Please also clarify what do you mean by " reload the page couple times".
 
Besides, as I understood you can reproduce the issue only on CI. Are you able to reproduce it locally?

**Comment by Evilweed** [comment]
@AlexKamaev I am reproducing it on CI as there is RAM restriction there, and I assume that if too much ram is used by Chrome and it fails then this bug occurs (locally I have much more ram to my disposal), maybe there is this problem in chrome in containers. As for the full tests package, I cannot make it public here. If you provide me any email I can send it privately then I'll prepare it for You.

**Comment by AndreyBelym** [comment]
@Evilweed  if you want to share your project, you can send it to support@devexpress.com. 

Also, you can measure how much RAM Chrome consumes with and without TestCafe. It is expected that TestCafe adds about 10-15% to the RAM usage. If it is your case, it means that your container needs more RAM to properly run Chrome with your website.
