### ISSUE TITLE
Automatic Browser Restart (when frozen/hung) feature broken from v1.0.0 onwards

### ISSUE THREAD

**Issue by sijosyn** [DevExpress/testcafe#3781]
### What is your Test Scenario?

I wonder what happened to this feature this was first introduced in v0.23.0 - [Browsers are Automatically Restarted When They Stop Responding](https://devexpress.github.io/testcafe/blog/testcafe-v0-23-0-released.html#browsers-are-automatically-restarted-when-they-stop-responding-1815). This is an excellent feature and was working fine up until v0.23.3. When TestCafe v1.0.0 came out, this feature stopped working (even happens in v1.1.4). TestCafe won't restart the browser when it goes into hung/frozen state (Browser instances are open but no actions happen inside the browser window). I don't have 100% reproducible test to provide to reproduce this issue as TestCafe freezes for some unknown reasons. When we run in tests in Bamboo CI server, our jobs are getting stuck because TestCafe goes into hung state and we have to manually kill the job & shutdown all open browsers (see screenshot).

I would love to have this feature working back again. Can you guys take a look at the feature again and see why/where it might be broken? 
 
### What is the Current behavior?

When TestCafe encounters some strange issue, TestCafe freezes and stays frozen/hung state forever. It won't quit & restart the browsers and attempt to run the tests again.
 
### What is the Expected behavior?

If a browser stops responding while it executes tests, TestCafe restarts the browser and reruns the current test in a new browser instance. If the same problem occurs with this test two more times, the test run finishes and an error is thrown.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

![f502bc](https://user-images.githubusercontent.com/29459281/57523725-bae99380-72f3-11e9-988d-5271519d804e.png)

</details>

### Steps to Reproduce:

No exact 100% reproducible test script to provide to reproduce this issue.
 
### Your Environment details:
 
* testcafe version:                    Happens in v1.0.0, v1.1.0, v1.1.3 & latest v1.1.4 . Works fine in v0.23.3
* node.js version:                     v8.11.1
* command-line arguments:  
* browser name and version:  Chrome 74
* platform and version:           macOS 10.14
* other:

**Comment by AlexKamaev** [comment]
I was able to reproduce the problem. We'll research it and keep you updated shortly.
