### ISSUE TITLE
Custom reporters don't work against the docker build

### ISSUE THREAD

**Issue by dgoemans** [DevExpress/testcafe#3782]
### What is your Test Scenario?
- Install a reported such as `testcafe-reporter-teamcity`
- Run the docker container with `-r teamcity` argument
 
### What is the Current behavior?
The test suite fails with the following output:
`ERROR The provided "teamcity" reporter does not exist. Check that you have specified the report format correctly.`
 
### What is the Expected behavior?
The tests run and report to the correct output
 
### What is your web application and your TestCafe test code?
Not available at this time.

```
docker run -v /c/myproject/tests:/tests -it testcafe/testcafe chromium "/tests/test.js" -e -r teamcity
```
</details>

### Steps to Reproduce:

1. Install a reported such as `testcafe-reporter-teamcity`
2. Run the docker container with `-r teamcity` argument
3. See the error: `ERROR The provided "teamcity" reporter does not exist. Check that you have specified the report format correctly.`
 
### Your Environment details:
 
* testcafe version:                   1.1.3
* node.js version:                    11.10.1
* command-line arguments:  docker run -v /c/myproject/tests:/tests -it testcafe/testcafe chromium "/tests/test.js" -e -r teamcity
* browser name and version: chromium in docker w/ testcafe 1.1.3
* platform and version:          Windows 10

**Comment by AndreyBelym** [comment]
If you want to use TestCafe plugins in a Docker image, you can create your own image based on the ` testcafe/testcafe` image and add plugins with the `npm i -g` command. Or you can add the `testcafe` package and plugins as dependencies to your test project and change the container working directory with the `-w=/tests` switch: [WORKDIR](https://docs.docker.com/engine/reference/run/#workdir). In this case, ensure that the `node_modules` directory with TestCafe and plugins is a subdirectory of the test project root directory.

**Comment by dgoemans** [comment]
Works like a charm! Thanks :)
