### ISSUE TITLE
TypeError: t.expect(...).ok(...).click(...).click(...).expect(...).ok(...).requestHooks is not a function

### ISSUE THREAD

**Issue by behlrattan** [DevExpress/testcafe#3784]
### What is your Test Scenario?
Hers's HTTP response JSON  **{"total": 0,"page": 1,"pageSize": 100,"rows": [] }**
**If (total:0)** then
"Don't show a card on webpage, IOW card should be invisible."
**else**
"Show a happy card on web page, IOW card should be visible."
 
### What is the Current behavior?
I get error as mentioned in bug title
 
### What is your web application and your TestCafe test code?
Its a web application on vue

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
const myURL = new RegExp('https://<url>/delta/Details?npList=*');

var str = '{"total": 0,"page": 1,"pageSize": 100,"rows": [] }'.toString

var mockedResponse = Buffer.from(str);

const mock = RequestMock().onRequestTo(myURL)
 .respond(mockedResponse, 200, {
   'content-length': mockedResponse.length,
   'content-type': 'application/json; charset=utf-8'
 });
 
fixture`Navigation`
  .beforeEach(login)
  test('My Test', async t => {
    await t
    .expect((stayHappyLink).exists).ok() 
    .click(stayHappyLink)
    .click(happyTab)
    .expect((.happyResearchTitle).exists).ok() //This should pass as total is more than 0
    .requestHooks(mock)
    .expect((.happyResearchTitle).exists).ok() // This test should fail after the mock
 });
 
</details>

<details>
<summary>Your complete test report:</summary>

TypeError: t.expect(...).ok(...).click(...).click(...).expect(...).ok(...).requestHooks is not a function
</details>

 
### Your Environment details:
 
* testcafe version:                   1.1.3
* node.js version:                    v11.13.0
* browser name and version: Chrome 74
* platform and version:          macOS 10.14.4

**Comment by AndreyBelym** [comment]
The `requestHooks` function can be used only in `fixture.requestHooks` or `test.requestHooks` forms. If you want to add a request in a test function, use the `t.addRequestHooks` function. Check the documentation: [Attaching Hooks To Tests And Fixtures](https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/attaching-hooks-to-tests-and-fixtures.html).
