### ISSUE TITLE
.testcaferc.json file does not work when running local TestCafe from outside of package

### ISSUE THREAD

**Issue by oemekaogala** [DevExpress/testcafe#3791]
### What is your Test Scenario?
I am trying to run tests with a .testcaferc.json config file 

### What is the Current behavior?
When running the local testcafe exe in the project folder directly, testcafe properly picks up the .testcaferc.json file and sets the configs, but when running tests from outside of the project folder and still using the locally installed testcafe, the .testcaferc.json file is not read. (See images below)
 
### What is the Expected behavior?
I expect testcafe to recognize the .testcafe.json in its proper location and apply the setting in the config file.
 
<details>
<summary>Screenshots:</summary>
You can see here that I first ran the tests with no problem when in the project folder, but the second I leave the project folder while still correctly calling to the testcafe exe and file location, it does **not** work.

![testcafe-bug](https://user-images.githubusercontent.com/43686641/57654902-277dc000-758a-11e9-903f-4962fc121657.png)

</details>

### Your Environment details:
 
* testcafe version:                   1.1.4
* node.js version:                    v10.13.0
* command-line arguments:  .../node_modules/bin/testcafe test.js" -->
* browser name and version: Chrome
* platform and version:          macOS 10.14.4

**Comment by Farfurix** [comment]
@oemekaogala 

Hello,

Thank you for your detailed description. I've reproduced this issue under Windows 10 / `testcafe@1.1.4`. Our team will research it and check for a suitable solution.

For team:
**.testcaferc.json:**
```
{
    "browsers": "chrome",
    "src": "test.js"
}
```


https://github.com/DevExpress/testcafe/blob/master/src/configuration/index.js#L43

```diff
export default class Configuration {
    constructor () {
        this._options  = {};
        this._filePath = resolvePathRelativelyCwd(CONFIGURATION_FILENAME);
+       console.log('_filePath:', this._filePath);
        this._overridenOptions = [];
    }
```
Results:
```
d:\tst\i3791-tc>testcafe
Using locally installed version of TestCafe.
_filePath: d:\tst\i3791-tc\.testcaferc.json
 Running tests in:
 - Chrome 74.0.3729 / Windows 10.0.0

 Fixture
 √ Test


 1 passed (4s)
```
```
d:\tst\i3791-tc>.\node_modules\.bin\testcafe
_filePath: d:\tst\i3791-tc\.testcaferc.json
 Running tests in:
 - Chrome 74.0.3729 / Windows 10.0.0

 Fixture
 √ Test


 1 passed (4s)
```
**Issue case (the wrong `_filePath` value):**
```
d:\tst\i3791-tc>cd ..

d:\tst>.\i3791-tc\node_modules\.bin\testcafe
_filePath: d:\tst\.testcaferc.json [!!!]
ERROR No browser selected to test against.

Type "testcafe -h" for help.
```

**Comment by AndreyBelym** [comment]
It's not a bug. TestCafe looks for a configuration file in the current directory, check [the documentation](https://devexpress.github.io/testcafe/documentation/using-testcafe/configuration-file.html):
```
Keep .testcaferc.json in the directory from which you run TestCafe.
```

We will implement the possibility of storing config files in other directories in the context of https://github.com/DevExpress/testcafe/issues/3428 and https://github.com/DevExpress/testcafe/issues/3136.
