### ISSUE TITLE
Add more recipes/FAQ topics

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#3792]
### Recipes
- [ ] The tested web application is built after the first request will complete. Need to start tests after that. 
It's possible to make using the `request-promise` module
```js
const request = require('request-promise');
  
request('tested-app-url.com')
    .then(() => {
      return  createTestCafe();
    })
    ....
```
or `wait-on` module (see https://github.com/DevExpress/testcafe-examples/issues/71).

- [ ] How to setup TestCafe to connect with Appium server. It allows customers to run their tests on real devices.
https://stackoverflow.com/questions/55953475/using-testcafe-with-appium/56037109#56037109

### FAQ topics
- [ ] TestCafe does not support offline mode. TestCafe uses xhr requests internally to communicate with the proxy server. In offline mode these requests failed. (https://github.com/DevExpress/testcafe/issues/3643, https://github.com/DevExpress/testcafe/issues/3190)
- [ ] Can I test my Electron app? Yes, use the [testcafe-browser-provider-electron](https://github.com/DevExpress/testcafe-browser-provider-electron) plugin.
- [ ] It's possible to test the downloaded file content? Yes, use `RequestLogger` for that.
- [ ] How to decrease execution time of my tests? Use headless browsers and concurrency mode.

**Comment by titerman** [comment]
We don't plan to address this issue in the near future. Feel free to reopen the ticket if the issue is important for you.
