### ISSUE TITLE
Test that run ok locally fails on Saucelabs

### ISSUE THREAD

**Issue by pgaliana** [DevExpress/testcafe#3793]
### What is your Test Scenario?
I designed the test using TestCafé Studio. The test runs smoothly in Studio.
I save the script and run it via the command line:
`testcafe chrome test.js`
The test runs and passes.
When I run the same test using Saucelabs the test fails:
`testcafe "saucelabs:Chrome@74.0:Windows 7" test.js`
 
### What is the Current behavior?
The test fails. I have tested different browsers and OS's. All attempts fail. 
 
### What is the Expected behavior?
The test should pass.
 
<details>
<summary>Code:</summary>
```
.click(Selector('a').withText('Custom dashboards'))
```
</details>

<details>
<summary>Test report:</summary>
```
1) The specified selector does not match any element in the DOM tree.

         | Selector('a')
       > |   .withText('Custom dashboards')
```
</details>
 
### Your Environment details:
 
* testcafe version:                   1.1.4
* node.js version:                    v8.11.1
* command-line arguments:  testcafe "saucelabs:Chrome@74.0:Windows 7" test.js
* browser name and version: not applicable
* platform and version:          macOS 10.14.4
* other:                                   using testcafe-browser-provider-saucelabs plugin

**Comment by Farfurix** [comment]
@pgaliana 

Hello,

It is difficult to determine the cause of this issue without reproducing your scenario. To start, I suggest you use one of the following Selector options: [`options.timeout`](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/selector-options.html#optionstimeout), [`options.visibilityCheck`](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/selector-options.html#optionsvisibilitycheck). If it doesn't help, please provide us with your Sauce Lab test video that illustrates your scenario in action.

**Comment by pgaliana** [comment]
Thanks @Farfurix 
Is there any change of a private channel for communications? You can write to my email (pablo.galiana@mulesoft.com).
Thanks

**Comment by Farfurix** [comment]
@pgaliana 

I see your email in our inbox. We will reply with a request to send us a Sauce Lab video (and your test code) that demonstrates the result of using the "Selector options" suggestion.
