### ISSUE TITLE
TestCafe hangs more frequently with v1.1.4. Need suggestions how to collect debug log.

### ISSUE THREAD

**Issue by sijosyn** [DevExpress/testcafe#3795]
### What is your Test Scenario?

There is a strange TestCafe issue when running tests on our staging/UAT test sites (behind firewall). The same public PROD test site is this (https://aperture.synacor.net). 

TestCafe hangs for no reason and stays stuck forever. Browser window is open but no actions happen inside. This issue happens more frequently with TestCafe v1.1.4. One thing I noticed is that, in the frozen browser window, I see extra param `/?inc=meta&metats=1557335926` & sometimes `/&inc=1` appended to the test URL. Any idea if those params are coming from TestCafe & would cause any issues? I tried launching test URL with those extra params but unable to reproduce hang/frozen issue. 

Is there a debug build or special debug logs that I can provide to you when this issue happens again to debug this issue?
 
### What is the Current behavior?

TestCafe hangs for no specific reason when running tests and stays stuck forever.
 
### What is the Expected behavior?

TestCafe to run without any issues
 
### What is your web application and your TestCafe test code?

No specific tests to share as TestCafe freezes at different intervals and no consistent way to reproduce this issue.

Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                    1.1.4
* node.js version:                     8.11.1
* command-line arguments:  
* browser name and version:  Chrome 74
* platform and version:           macOS 10.14
* other:

**Comment by AlexKamaev** [comment]
Could you please clarify if you are running tests on CI or on the local machine?
Could you also provide test code for the `https://aperture.synacor.net` web site? I want to run it on my local macOC to reproduce it in an environment similar to yours.

We do not have a debug build, however, your can try to put some `console.log` calls into important places in code. Also, you can collect an HAR report. Please follow the recommendations from the https://github.com/DevExpress/testcafe/issues/3304#issuecomment-455249417 comment.

As for strange parameters in your request urls, TestCafe does not append any params to a request so it's difficult to determine what it is.

**Comment by sijosyn** [comment]
@AlexKamaev I'm seeing this issue when running tests on Bamboo CI with 6 concurrent browsers (Mac Pro server machine with MacOS 10.12.6, 6 core CPU & 32GB RAM). I'm not able to reproduce this issue consistently. I can close this ticket for now and create new ticket when I have figured out the exact test thats causing this issue and provide more details.

**Comment by AlexKamaev** [comment]
Thank you for cooperation. We would really appreciate it if you provide us with some information which helps us find the cause of the issue. It's not required to create a new ticket, feel free to add new details here.
Meanwhile, I'll discuss with the team on how we could improve stability of our tests on CI.
