### ISSUE TITLE
2 HTTP Authentications in one scenario

### ISSUE THREAD

**Issue by nikolarss0n** [DevExpress/testcafe#3796]
Is there a way to use 2 http authentications in 1 test scenario?

Test scenario: 
1. Open first page with http auth
2. Choosing options
3. Choosing a catalog (click) (which leads to the second http auth)

Actual result: Not able to use the second httpauth because it's being overwritten and this leads to unauthorized.

Is there any way to use 2 httpAuths in one test case or something like this. Or any workaround?

The project is internal and I am not able to share it.

**Comment by AlexKamaev** [comment]
TestCafe does not provide the capability to set multiple HTTP authentications in one test scenario. However, I think you can bypass this restriction using the [Request Hooks ](https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/creating-a-custom-http-request-hook.html) mechanism.
You can modify your request by adding required authorization headers.
I recommend you check [this module](https://github.com/churkin/webauth) which TestCafe uses internally to have an idea which headers should be added to your request.
