### ISSUE TITLE
Intermittent Chrome Device Emulation issues on Mac. Window won't resize to mobile viewport size.

### ISSUE THREAD

**Issue by sijosyn** [DevExpress/testcafe#3797]
### What is your Test Scenario?

Chrome device emulation feature works well 90% of the time for me but in some occasions, it fails to resize the browser window to the specified device viewport size. This issue is seen on Mac. For e.g, if I run this command `testcafe 'chrome:emulation:device=iphone 6/7/8' test.js`, it resizes the browser window to iphone 6/7/8 device viewport size. But sometimes TestCafe fails to resize the window. It stays in the desktop window size and won't resize. To make it work again, I have to try running different device modes or commands like this `testcafe 'chrome:emulation:device=pixel 2' test.js` or `testcafe "chrome:emulation:width=100;height=200;mobile=true;orientation=vertical;touch=true" tests/sample-fixture.js` to make it work again. 

Not sure if we have any issue in the `testcafe-browser-tools`resize util on Mac's. Anyone else seen or come across this issue? Note: When trying to reproduce this issue, please quit execution during test run and try again. I wonder it has something to do with previous test execution not closed properly and TestCafe trying to run again which messes some things. 
 
### What is the Current behavior?

Chrome device emulation not working all the time on Mac
 
### What is the Expected behavior?

Chrome device emulation should work without any issues.
 
### What is your web application and your TestCafe test code?

No specific tests to provide.
 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                    v1.1.4
* node.js version:                     v8.11.1
* command-line arguments:   testcafe 'chrome:emulation:device=iphone 6/7/8' test.js
* browser name and version:  Chrome 74
* platform and version:           macOS 10.14
* other:

**Comment by AlexKamaev** [comment]
I was not able to reproduce the issue.
Besides, I tried to run tests concurrently and break test execution as you described, however, in all cases it works as expected. Does this problem appear only with TestCafe 1.1.4 version or with he previous one as well?
Do you use some custom user profile?
I would appreciate it if you share some additional information about the issue, e.g. video which demonstrates the resizing problem

**Comment by sijosyn** [comment]
@AlexKamaev This happens with the previous version v1.1.3 too. Attached 2 video dropbox links here to show the issue. 
First is 'Not_working.mov' version  - [Not_working.mov](https://www.dropbox.com/s/o0cgxr18kotku8c/Not_working.mov?dl=0)
Second is 'Working_fine.mov'. - [Working_fine.mov](https://www.dropbox.com/s/zrfrm5ftzvwi1co/Works_fine.mov?dl=0)



In the 'Not_working' video, you can see the window is not getting resized when device emulation is specified. The same command works fine later (Workaround that I did to make it work. I switched to another git branch & then back to develop branch).

**Comment by AlexKamaev** [comment]
I discussed the issue with the team and we decided that it can be related to the https://github.com/DevExpress/testcafe/issues/3399 problem, since you mentioned the situation when previous test execution was not executed correctly.
Please try to call the `killall "Google Chrome"` command each time you execute TestCafe. 
Also I added some `console.log` and `debugger` calls to the code related to the issue. Could you please check this and share results?
[testcafe.zip](https://github.com/DevExpress/testcafe/files/3187354/testcafe.zip)

**Comment by sijosyn** [comment]
@AlexKamaev Tried `killall "Google Chrome"` command for each run. It's not helping resolve this issue (browser still opens in normal window size). I tried the provided `testcafe.zip` and ran some tests. Not seeing any `console.log` in terminal. See screenshot below. 

![Screen Shot 2019-05-16 at 11 49 21 AM](https://user-images.githubusercontent.com/29459281/57870127-70c15000-77d4-11e9-9379-d7765ecc1504.png)

But if I insert `await t.resizeWindow( 300, 300 )` in the test, then I see `console.log` in terminal. Am I doing something wrong or missing some instructionsn?

![Screen Shot 2019-05-16 at 12 18 40 PM](https://user-images.githubusercontent.com/29459281/57870373-edecc500-77d4-11e9-8836-832c6a6fb39c.png)

**Comment by arubtsov** [comment]
It looks like running the `killall "Google Chrome"` command is not helping. Could you please execute the following code instead:
```
ps -e | grep [Cc]hrome
ls -l $TMPDIR | grep testcafe
ls -l $TMPDIR/testcafe
rm -rf $TMPDIR/testcafe
```
(it lists information about Chrome processes, testcafe temporary directory, it's contents, and deletes these contents).

**Comment by sijosyn** [comment]
@arubtsov @AlexKamaev I executed the provided commands. Still no luck. It's not working either. Browser still opens in normal window size. I think it's ignoring the chrome emulation device type. Could it be some command line parsing bug when it's trying to read the device type?

<img width="522" alt="Screen Shot 2019-05-17 at 8 42 27 AM" src="https://user-images.githubusercontent.com/29459281/57929377-234eec80-7881-11e9-92ea-78331b7cbc6d.png">

**Comment by AlexKamaev** [comment]
@sijosyn 

At the moment, we don't know whether or not this issue is related to the command line parsing algorithm.
It seems that testcafe cannot connect to the Chrome debug protocol for some reason. Perhaps some error occurs in this code: https://github.com/DevExpress/testcafe/blob/9c96672c9c6a7fb50658a4c57f1e17ce645cd3b6/src/browser/provider/built-in/dedicated/chrome/cdp.js#L65
I've prepared another archive with some logs which cover the described code. Please check it and redirect the output in a separate file, i.e. : `testcafe "chrome:emulation:device=Pixel 2" test.js > report.txt`

The output should look as follows:
```
open browser: _uR1BSX http://172.22.5.184:54110/browser/connect/_uR1BSX
create cdp client
get active tab 54112 - _uR1BSX
remote chrome
remote chrome connected
set emulation
 Running tests in:
 - Chrome 74.0.3729 / Windows 10.0.0

 fixture
 √ test


 1 passed (1s)

```
[testcafe.zip](https://github.com/DevExpress/testcafe/files/3202208/testcafe.zip)

**Comment by sijosyn** [comment]
@AlexKamaev See the latest results below. I see `error on connecting to cdp` in the logs.

```
open browser: 2PcyHRS http://192.168.0.15:52688/browser/connect/2PcyHRS
create cdp client
get active tab 52698 - 2PcyHRS
error on connecting to cdp
 Running tests in:
 - Chrome 74.0.3729 / Mac OS X 10.14.2

 fixture
 ✓ test


 1 passed (2s)
```

**Comment by AlexKamaev** [comment]
It definitely looks like a problem with Chrome Debug Protocol.
Here is the problematic part of code:
https://github.com/DevExpress/testcafe/blob/9c96672c9c6a7fb50658a4c57f1e17ce645cd3b6/src/browser/provider/built-in/dedicated/chrome/cdp.js#L6
We have not faced any similar issue, so we need some additional time to research it.
You can try to add the `cdpPort` parameter to your emulation arguments as described in this article: https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/using-chrome-device-emulation.html

You can also try examples from the https://github.com/cyrus-and/chrome-remote-interface repository, which is the core part of our emulation mechanism.

**Comment by sijosyn** [comment]
Thanks @AlexKamaev. I added the `cdpPort` parameter to emulation argument like this (`testcafe "chrome:emulation:device=pixel 2;cdpPort=9223" abc.js > report.txt`). Still no luck. Got same result (see log below). I'll look into examples provided in the `chrome-remote-interface `repo and will let you know.

```
open browser: mAj_GWO http://192.168.0.15:57447/browser/connect/mAj_GWO
create cdp client
get active tab 9223 - mAj_GWO
error on connecting to cdp
 Running tests in:
 - Chrome 74.0.3729 / Mac OS X 10.14.2

 fixture
 ✓ test


 1 passed (1s)
```

**Comment by sijosyn** [comment]
@AlexKamaev I found the reason why this is happening on my machine. I'm using hostfile manipulation tool called [hostile](https://www.npmjs.com/package/hostile) to add a bunch of ip addresses in the hostfile (overide DNS) before running the tests to hit URL's(UAT/Staging machines) that are behind firewall/non-public domain. 
When writing to the hostfile, it deleted the following required localhost block and that was causing this issue. Adding the localhost entry in the hostfile resolved this issue. I'll close this issue for now.

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost 
```

**Comment by arubtsov** [comment]
We are happy to hear that you have found the cause of the issue. Thank you for sharing this information with us.
