### ISSUE TITLE
Hammerhead IP and Hash key added to the Test App URL - same as Issue #2832

### ISSUE THREAD

**Issue by Abhinav-P** [DevExpress/testcafe#3798]
### Are you requesting a feature or reporting a bug?

Feature

### What is your Test Scenario?
Running testcafe fixture for an internal app from Browser-stack /Sauce labs. 

### What is the Current behavior?
1. Hammer Head IP & hash key gets added to the test application URL . 
2. This application being internal app and blocked for outside IP, the test URL gets proxied thru Hammer head IP which is Dynamic and hence application throws 401. 

To get around this problem the external IP should be white listed but as hammer head IP are dynamic , external Proxy IP 's or range is hard to predict . 

### What is the Expected behavior?
There should be a way to remove the hammer head proxy IP and Hash key to remove from application test URL's. 

Or hammer head Ip small range should be defined so as to whitelist the subnet . 

Also Curious to know where does Hammer head process (proxy server) runs  --> Host machine where the test are executed from or the remote machine running the test.

### How would you reproduce the current behavior (if this is a bug)?
Not applicable. 

#### Provide the test code and the tested page URL (if applicable)
Can't provide due to Security concern... It's a very simple integration nothing tricky. 
 
Your website URL (or attach your complete example):

Your complete test code (or attach your test files)

**Comment by AlexKamaev** [comment]
TestCafe uses the operating system's hostname or the current machine's network IP address. Thus, this url is predictable.
If TestCafe runs with [remote browsers](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#remote-browsers) you can also specify the [--hostname](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--hostname-name) option. Besides, you can set the [--ports](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--ports-port1port2) option.
>Also Curious to know where does Hammer head process (proxy server) runs --> Host machine where the test are executed from or the remote machine running the test.

The hammerhead process runs on the machine where TestCafe is installed.

If you still have questions, feel free to ask them here.
