### ISSUE TITLE
A test hangs if it contains calculations with awaits in a chain

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#3801]
### What is your Test Scenario?
Use math operators and selector properties in assertions.
 
### What is the Current behavior?
Test hangs
 
### What is the Expected behavior?
Test should not hang.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Test code:</summary>

 
```js
 import { Selector } from 'testcafe';

fixture `iframe`
    .page(`./index.html`);

test('Test1', async t => {
    const div = Selector("div");
    await t
        .expect(Selector("#test").offsetLeft).eql(await div.offsetLeft)
        .expect(Selector("#test").offsetTop).eql((await div.offsetTop) + (await div.offsetHeight));
});
```
</details>

<details>
<summary>Test page:</summary>

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>test</title>
    <script>
    </script>
</head>
<body>
    <div id="test"></div>
</body>
</html>
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by miherlosev** [comment]
The issue is not reproduced with the `testcafe@.1.10.1`.
