### ISSUE TITLE
Can't reference global variables (Globals)

### ISSUE THREAD

**Issue by sijosyn** [DevExpress/testcafe#3805]
### What is your Test Scenario?

Sorry for asking this dumb question. Can we not use Global Variables in tests? Getting not defined error when accessing global variables in the test script (screenshot attached).  [See specifying globals](https://eslint.org/docs/user-guide/configuring#specifying-globals)

I want to store some values in a global variable (e.g our test sites version number) and then later use that global variable in browser-provider-plugin to generate report with the version (stored in global variable).
 
### What is the Current behavior?

Getting error when accessing global variables in the test script.
 
### What is the Expected behavior?

Should be able to access global variables in test scripts
 
### What is your web application and your TestCafe test code?

 
See attached test code 

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 /* global version:writable*/

fixture `Getting Started`
    .page `http://devexpress.github.io/testcafe/example`;

test('Global variable test', async t => {
    version = '123'; // Store some values in global variable
});
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

<img width="535" alt="Screen Shot 2019-05-17 at 11 48 32 AM" src="https://user-images.githubusercontent.com/29459281/57940130-cd3a7300-7899-11e9-8c3d-2c350c67eb76.png">

</details>

### Steps to Reproduce:

Run the attached test script
 
### Your Environment details:
 
* testcafe version:                    v1.1.3
* node.js version:                     v8.11.1
* command-line arguments:   testcafe chrome test.js
* browser name and version:  Chrome 74
* platform and version:           macOS 10.14
* other:

**Comment by AlexSkorkin** [comment]
I recommend that you define your global variable first and then use it; e. g.: 
```
fixture `Getting Started`
.page `http://devexpress.github.io/testcafe/example`;
 
var version;

test('Global variable test', async t => {
  version = '123'; // Store some values in global variable
});
 
test('Global variable test 2', async t => {
  console.log(version);
});
```

P.S. Such questions would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions. We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafeontributing)).
