### ISSUE TITLE
Update flow-typed definitions to match new major version 1

### ISSUE THREAD

**Issue by rtarnaud** [DevExpress/testcafe#3806]
Currently, running: `flow-typed install testcafe@0.x.x` with testcafe@1.1.4 installed does not work.
Could you please update the libdefs?

**Comment by AndreyBelym** [comment]
The TestCafe type definitions for the Flow type checker are maintained by the community in a separate repository: https://github.com/flow-typed/flow-typed. We will try to upgrade our definitions, but likely there will be some problems with recent Flow versions. Thus it will be better if you create an issue in the https://github.com/flow-typed/flow-typed repository. In this way, you will catch the attention of people that are more skilled in Flow and can solve this problem faster.
