### ISSUE TITLE
TestCafe opens blank pages

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#3808]
The page looks ok without TestCafe but during test run we see blank area on the page and get one hammerhead error in console (in page's scripts).
Steps to reproduce you can find in [a private SC ticket](https://isc.devexpress.com/Thread/WorkplaceDetails/T742467).
I have failed to reproduce it in `hammerhead-playground`.

**Comment by miherlosev** [comment]
All works fine with the latest TestCafe version (`1.2.1`).
![image](https://user-images.githubusercontent.com/4133518/59281793-89584500-8c70-11e9-8c3a-0f967d0acfaf.png)
