### ISSUE TITLE
TC passing even when there is error "CantObtainInfoForElementSpecifiedBySelectorError" in console.

### ISSUE THREAD

**Issue by sonypriyadarshini** [DevExpress/testcafe#3817]
### What is your Test Scenario?
I am using "await t.expect(await element.visible).ok(message, { timeout: 2000 }); " to check the visibility of an element. This line works fine (the TC fails if the element is not visible and passes without any error in the console if visible) only when used directly in the method.
When the same line of code is written inside a method, the test passes even when the element is not actually visible and error is printed in the console.

 
### What is the Current behavior?
With the below code, which consists of a test method and a helper method containing the line "await t.expect(await element.visible).ok(message, { timeout: 2000 });", even when the element is not visible in real, the test is marked pass, with below error printed in the console:
`test('test 1', async t => {
  await Common.login(LOGIN_DATA.username,LOGIN_DATA.password);
  const errorMessageXpathFinal = XPathSelector("//div[@class='c-notification__message']//span[contains(.,'Invalid field')]");
  Common.elementIsVisible(errorMessageXpathFinal,"Error Message is not displayed");
})
static async elementIsVisible(element,message){
    await t.expect(await element.visible).ok(message, { timeout: 2000 }); 
}`

But if "await t.expect(await element.visible).ok(message, { timeout: 2000 });" is directly used in the test method as below, the test case fails when the element is not visible without any error being thrown in the console:
`test('test 1', async t => {
  await Common.login(LOGIN_DATA.username,LOGIN_DATA.password);
const errorMessageXpathFinal = XPathSelector("//div[@class='c-notification__message']//span[contains(.,'Invalid field')]");
  await t.expect(await errorMessageXpathFinal.visible).ok(message, { timeout: 2000 }); 
})`

 
### What is the Expected behavior?

The test should fail without any error in the console even when test and helper methods, both are used.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example): test application is internal tool.
<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
test('test 1', async t => {
  await Common.login(LOGIN_DATA.username,LOGIN_DATA.password);
  const errorMessageXpathFinal = XPathSelector("//div[@class='c-notification__message']//span[contains(.,'Invalid field')]");
  Common.elementIsVisible(errorMessageXpathFinal,"Error Message is not displayed");
})
static async elementIsVisible(element,message){
    await t.expect(await element.visible).ok(message, { timeout: 2000 }); 
}
 

Error:

CantObtainInfoForElementSpecifiedBySelectorError {
  type: 'cantObtainInfoForElementSpecifiedBySelectorError',
  isTestCafeError: true,
  callsite:
   CallsiteRecord {
     filename:
      '/Users/sonypriyadarshini/Traveloka_Code/UIAutomation/utils/UtilsCommon.js',
     lineNum: 136,
     callsiteFrameIdx: 3,
     stackFrames:
      [ [CallSite],
        [CallSite],
        [CallSite],
        [CallSite],
        CallSite {},
        [CallSite],
        [CallSite],
        CallSite {},
        [CallSite],
        [CallSite],
        [CallSite],
        [CallSite],
        CallSite {},
        [CallSite],
        [CallSite],
        [CallSite],
        [CallSite] ],
     isV8Frames: true } }

Code working fine:

test('test 1', async t => {
  await Common.login(LOGIN_DATA.username,LOGIN_DATA.password);
const errorMessageXpathFinal = XPathSelector("//div[@class='c-notification__message']//span[contains(.,'Invalid field')]");
  await t.expect(await errorMessageXpathFinal.visible).ok(message, { timeout: 2000 }); 
})
```

</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Your Environment details:
 
* testcafe version:1.1.4            
* node.js version:                    
* command-line arguments:  
* browser name and version:chrome 
* platform and version:          
* other:

**Comment by AlexKamaev** [comment]
I assume that the cause of the issue is that you forgot the `await` keyword before a call to the `Common.elementIsVisible` method. Please check it. If this does not help please provide us with a working project or the url to your project which demonstrates the issue.
