### ISSUE TITLE
Hammerhead proxy not retrieving file in expected format

### ISSUE THREAD

**Issue by SanderPetersNN** [DevExpress/testcafe#3818]
### What is your Test Scenario?
I am testing the behaviour of a JavaScript application on a website.

### What is the Current behavior?
When retrieving the .js document, the Hammerhead proxy returns gibberish instead of JavaScript code. It seems as though it is reading it as if it were the wrong filetype or encoding. The page, obviously, does not load this file properly and does not display the JavaScript application.

### What is the Expected behavior?
I expect to load the page, for the site to fetch the JavaScript document and display the application.

<details>
<summary>Screenshots:</summary>

https://user-images.githubusercontent.com/50835230/58172112-f0995f80-7c97-11e9-9fd6-164720bac721.png 

A screenshot of the response with a functioning browser on the left and the faulty response from TestCafe on the right. Note that the Content-Encoding is not returned. The Content-Length is the same for both responses. Could this be related to the error?

[This is the response that is received from the server. I have renamed it to a .txt file so I can upload it, it is originally downloaded as a .js file.](https://github.com/DevExpress/testcafe/files/3207190/blueriq.js.txt)

</details>

### Your Environment details:
 
* testcafe version:                   1.1.4
* node.js version:                    v12.3.0
* command-line arguments:  call testcafe "path:%CHROME%" -s screenshots test.js --debug-on-fail 
* browser name and version: Tried in various browsers, Chrome 74, IE11, Firefox 67
* platform and version:          Windows 10 64-bit
* other:                                   Due to the fact that this data is in a local corporate network, I can not post links or steps for reproducing. It does not seem like this is an issue with my code, but rather with the Hammerhead proxy, so I hope this is a sufficient amount of information.

**Comment by helen-dikareva** [comment]
This behavior looks like a bug but to be sure we need to reproduce it on our side.
Could you please provide us with your test file including the testing page url?

You can also try to get more info about the problem and open your site in the hammerhead-playground. Hammerhead-playground is TestCafe's sandbox where our built-in proxy mechanism can be tested separately.
To do it clone the [hammerhead repository](https://github.com/DevExpress/testcafe-hammerhead) and add the following code in the [request-pipeline](https://github.com/DevExpress/testcafe-hammerhead/blob/6f3439155d91fe71b4678c52f62efdfd26f2add3/src/request-pipeline/index.ts#L86) file.
```js
/*eslint-disable no-console*/
console.log(ctx.dest.url, ctx.destRes.headers, ctx.contentInfo);
```
after `ctx.buildContentInfo();` line.
Install npm modules and run the `http-playground` gulp task. Hammerhead-playground will be open on `http://localhost:1400/`. Type in you site url to open it and send us a screenshot of the results from the console.

**Comment by SanderPetersNN** [comment]
Hello, thank you for the information. As the site is on a local corporate network, I can not provide a functioning url.

I have looked at the hammerhead proxy playground. It seems that everything functions normally if I navigate to the site using the hammerhead proxy. The Javascript element loads properly and the site generally functions as expected. I have enclosed the console output as requested.
![hammerhead proxy console](https://user-images.githubusercontent.com/50835230/58331144-c206ba80-7e38-11e9-8883-9e69b22fba2a.png)
Note that the _Content-Encoding: gzip_ does appear in this case, while it does not appear when the page is loaded through testcafe, as seen in the screenshot in the original post.


Since the problem does not seem to (directly) be the hammerhead proxy, to try to narrow things down, I tried navigating directly to the .js file instead of to the page in which it is embedded. My experiences were as follows:

Navigating to the .js file in Chrome leads to the JavaScript file showing up normally. [blueriq from chrome.txt](https://github.com/DevExpress/testcafe/files/3217035/blueriq.from.chrome.txt)

Navigating to the .js file in the hammerhead proxy playground leads to the JavaScript file loading properly, but with a hammerhead header and footer. [blueriq from hammerhead.txt](https://github.com/DevExpress/testcafe/files/3217036/blueriq.from.hammerhead.txt)

Navigating to the .js file with Testcafe (in any browser) leads to a page of nonsense showing up. The script is just a _navigateTo_ that navigates to the .js file. [blueriq from testcafe.txt](https://github.com/DevExpress/testcafe/files/3217037/blueriq.from.testcafe.txt)

Note that again, all of these were originally .js files that I renamed to .txt files as Github does not allow uploading .js files.



There is one other thing I noticed while investigating this, though I am not sure if this is helpful to know or not. If I open the website (the one that the JavaScript component is supposed to load on) in Internet Explorer 11 in InPrivate mode, the page also does not load properly, just like if it were loaded by Testcafe. Looking at the network console in this case reveals that it also does not have a _Content-Encoding: gzip_ field, which also does not appear in the console output from the Testcafe session, as seen in the original post. If I navigate directly to the .js file with Internet Explorer 11 in InPrivate mode, then the .js file also comes out garbled. This .js file is very similar to the .js file that Testcafe loads, although they are not identical. I am not sure what the cause of this is, but it seems like Internet Explorer in InPrivate mode is "making the same mistake" as Testcafe is. I have enclosed a screenshot of the console and the .js file.
![internet explorer inprivate console](https://user-images.githubusercontent.com/50835230/58331336-33df0400-7e39-11e9-85d6-901490ee200a.png)
[blueriq from internet explorer inprivate.txt](https://github.com/DevExpress/testcafe/files/3217094/blueriq.from.internet.explorer.inprivate.txt)

I am not sure what is causing it, but it certainly seems like the _Content-Encoding_ is the root of the issue. I hope this information will be of use to you.

**Comment by AlexSkorkin** [comment]
Thank you for providing this information. Please give us additional time to examine it.

**Comment by LavrovArtem** [comment]
Thanks for providing additional information. However, this information is not sufficient to find the cause of the issue.

Could you please send us a [.har](https://en.wikipedia.org/wiki/.har) file with information about requests with and without Testcafe?

Also, run your page in Chrome Incognito mode and through Testcafe with [chrome:userProfile](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/user-profiles.html).

In addition, it would be awesome if you create a simple server example that provides the page with this script file for debugging purposes.

**Comment by SanderPetersNN** [comment]
Hello,

It seems as though a new deployment has happened on our local server, and we are no longer encountering this issue. We are not sure why, but I thank you for your help regardless. Furthermore, since the page is now loading properly, I can not provide a .har file. If this issue arises again, I will make a new ticket and refer to this one. I apologise for the inconvenience.
