### ISSUE TITLE
testcafe -b does not return any browsers

### ISSUE THREAD

**Issue by majnos** [DevExpress/testcafe#3821]
### Are you requesting a feature or reporting a bug?
Installation or setup issue

### What is your Test Scenario?
i have just started with testcafe struggling to make it run on mac. 

```
npm install -g testcafe
testcafe chrome tests/
```

returns:
![image](https://user-images.githubusercontent.com/8961447/58238121-f1d59580-7d46-11e9-88cb-0fb4c6c33aed.png)

if i try to run 
```
testcafe -b 
```

it returns empty line. 

So I have to run tests like this:
```
testcafe 'path:`/Applications/Google Chrome.app`'  ./src/testcafe/test.ts
```
because browsers are installed obviously:

```
ls /Applications/
``` 

![image](https://user-images.githubusercontent.com/8961447/58238921-6c52e500-7d48-11e9-8be1-90f0a8ab8cf0.png)

### What is the Current behavior?
Browser aliases do not work, actually no browser aliases are available.

### What is the Expected behavior?
I should be able to use browser aliases

### Your Environment details:
 
* testcafe version:                   1.1.4
* node.js version:                    v10.15.3
* browser name and version: Version 74.0.3729.169 (Official Build) (64-bit)
* platform and version:          macOS 10.14.5

**Comment by AndreyBelym** [comment]
Could you please try to execute the following command:
```
alias | grep ls
```

If it displays a line like `alias ls=...`, save this line and run `unalias ls`. It will disable colors in the output of the `ls` command. I guess that TestCafe can't properly parse browser names due to control sequences used to change colors. After the color output is disabled, try to run `testcafe -b`. If it works fine with disabled colors, you can restore colors by executing previously saved `alias ls='...'` command or you can keep colors disabled as a workaround until we fix the problem.

**Comment by majnos** [comment]
Thanks for the reply Andrey. Forgot about one thing.

![image](https://user-images.githubusercontent.com/8961447/58268752-519f6100-7d86-11e9-91ab-8daf30eb652f.png)

I have set terminal monochromatic:

```
export TERM=xterm-mono
``` 

Cannot use any of automatically generated browser aliases without sudo.

**Comment by majnos** [comment]
ok so it is the colours but not LS but grep:

```
# Tell grep to highlight matches (breaks testcafe)
# export GREP_OPTIONS='--color=always'
# export GREP_COLOR='1;35;40'
```

**Comment by AndreyBelym** [comment]
Thank you for your report. I'm happy to hear that you have found the cause of the problem and fixed it on your side. We will modify our browser detection code in the context of https://github.com/DevExpress/testcafe-browser-tools/issues/168 to avoid such situations in future TestCafe versions.
