### ISSUE TITLE
t.takeScreenshot fails and deletes screenshot when runs on browserstack

### ISSUE THREAD

**Issue by Bogdan-Lyashenko** [DevExpress/testcafe#3828]
### What is your Test Scenario?
Running tests on browserstack (iPhone) and trying to take screenshot using `takeScreenshot` API method.
 
### What is the Current behavior?
`takeScreenshot` fails with the next error
```javascript
Error: Unable to locate the page area in the browser window screenshot at /path/screen.png, because the page area mark with ID 3717636 is not found in the screenshot.
      at calculateClipInfo (/node_modules/testcafe/src/screenshots/crop.js:81:19)
      at /node_modules/testcafe/src/screenshots/crop.js:104:18
```
As far as I realised testcafe wasn't able to calc crop area and thrown an error. I found this issue https://github.com/DevExpress/testcafe-browser-provider-browserstack/issues/51 which is exactly same one (setting `BROWSERSTACK_USE_AUTOMATE=1` doesn't change anything). I understood the logic behind the error, it's probably fine, but **screenshot is not created, what's more it's deleted** (if file was there before).  

It happens on this line https://github.com/DevExpress/testcafe/blob/master/src/screenshots/capturer.js#L142 
 
### What is the Expected behavior?
If I simply comment the line https://github.com/DevExpress/testcafe/blob/master/src/screenshots/capturer.js#L142 screenshot is being taken and saved. Since (I guess) original behaviour for `takeScreenshot` should just take screenshot (not crop it to element bounds) it would be nice to keep that screenshot. 
 
### Your Environment details:
 
* testcafe version:                   1.1.1
* testcafe-browser-provider-browserstack:                    1.8.0

Please let me know if I can help/contribute to make this moving.

**Comment by miherlosev** [comment]
Hi @Bogdan-Lyashenko 

You are using an old TestCafe version - `1.1.1`.
The latest TestCafe version (`1.14`) includes a few bug fixes related to cropping screenshots.
Try this version and let us know about results.

**Comment by Bogdan-Lyashenko** [comment]
Hi @miherlosev thanks for the quick response.

I tried `1.2.0` - it's still the same behaviour, when `takeScreenshot` fails (`cropScreenshot` method throw the error `Unable to locate the page area`) the clean up logic you have in `catch` block deletes the file.

See the image with code (thrown error from cropping logic ends up in `catch` and delete file)
![image](https://user-images.githubusercontent.com/2098309/58540765-520e8080-81fa-11e9-8e30-e959c003d7c8.png)

So, I guess there are few ways here, either to NOT delete file there in case of error; or to not throw error where you were 'unable to locate the page' in crop method; or that can be control by some new param for `options` config in `takeScreenshot`.

Thanks. Once again - please let me know if I can help/contribute to make this moving faster 🙂

**Comment by aleks-pro** [comment]
Hello @Bogdan-Lyashenko ,

Thank you for your report. We are aware of this issue and going to fix it in the current development [sprint.](https://github.com/DevExpress/testcafe/milestone/50) Please follow [this](https://github.com/DevExpress/testcafe/issues/3552) thread to stay informed about our progress.
