### ISSUE TITLE
[RequestMock] Allow to mock websocket requests

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#3832]

**Comment by bbonczek** [comment]
Are there any plans for supporting this feature?

**Comment by Farfurix** [comment]
@bbonczek 

Hello,
This issue is still under discussion. At this moment we are not ready to give any estimate on this.

**Comment by NexisSis** [comment]
Any updates?

**Comment by AlexSkorkin** [comment]
No updates yet. Once we get any results, we will post them here.

**Comment by kru032** [comment]
Any updates on this? Do you have target release identified?

**Comment by wentwrong** [comment]
Hello, @kru032,

We can't give you any estimated time frames. We'll post an update as soon as we have any news to share. You are welcome to contribute if you want to speed up the process.

**Comment by Moortiii** [comment]
This is still something that would be useful. I don't have time to implement it myself right now, but wanted to bump the post to show that it is still needed.

**Comment by razorch** [comment]
Still relevant! Any updates here?

**Comment by helen-dikareva** [comment]
mentioning: https://supportcenter.devexpress.com/internal/ticket/details/T1094926

**Comment by JWvP** [comment]
Any updates? This would be a very appreciated feature.

**Comment by AlexKamaev** [comment]
We do not have immediate plans to support this functionality, so we decided to close this issue to keep our backlog up to date.
