### ISSUE TITLE
Wrong 'testcafe' installation is used by CLI

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#384]
I have my primary working folder `D:\testcafe-phoenix`, in which I've cloned the repo. I run tests by executing `node bin\testcafe ...` in `D:\testcafe-phoenix`.

For some reason I also have an another copy of `testcafe` in `D:\node_modules\testcafe`. Now, after [commit about using locally installed version](https://github.com/DevExpress/testcafe/commit/8d2fc4aecc6222a7b093a5aa1995d850191ee907) was pulled, when I execute `node bin\testcafe ...` in `D:\testcafe-phoenix`, it uses version from `D:\node_modules\testcafe`. It is so because `resolveCwd('testcafe/lib/cli')` resolves to `D:\node_modules\testcafe\lib\cli` - [here](https://github.com/DevExpress/testcafe/blob/537cfce7c53d71f3a7a5cc95e4fb53c7028f05cd/src/cli/index.js#L78).

**Comment by inikulin** [comment]
I'm working on it

**Comment by inikulin** [comment]
After thinking about it more I believe it should be a by design behavior. Imagine I have a project with the tests in the `test` dir. I do `cd ./test && testcafe chrome ./*.js`. I should use local testcafe anyway which is in `../node_modules/testcafe` relative to this dir.
