### ISSUE TITLE
Roles losing session between fixtures

### ISSUE THREAD

**Issue by ampc** [DevExpress/testcafe#3843]
### What is your Test Scenario?
Multiple fixtures using useRole method.
 
### What is the Current behavior?
1. Fixture-1: useRole(user1) :heavy_check_mark: 
2. Fixture-2: useRole(user2) :heavy_check_mark: 
3. Fixture-3: useRole(user1) :heavy_check_mark: 
4. Fixture-4 useRole(user1) Doesn't restore user1 session, stays on login page forever failing all the tests and never recovers(never tries to login again) 

### What is the Expected behavior?
1. Don't lose session using multiple users
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
export const user1 = Role(
  `${baseUrl}/#/public/login`,
  async (t) => {
    await t.maximizeWindow();
    await LoginPage.login(user1.username, user1.password);
    await t.expect(Helper.getLocation()).contains('/public/login', { timeout: 5000 });
    await t.expect(WelcomePage.welcomeMessage.innerText).eql(`${Helper.greetingText()});
  },
  { preserveUrl: true }
);
export const user2 = Role(
  `${baseUrl}/#/public/login`,
  async (t) => {
    await t.maximizeWindow();
    await LoginPage.login(user2.username, user2.password);
    await t.expect(Helper.getLocation()).contains('/public/login', { timeout: 5000 });
    await t.expect(WelcomePage.welcomeMessage.innerText).eql(`${Helper.greetingText()});
  },
  { preserveUrl: true }
); 

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.1.3
* node.js version:                    10.15.3
* command-line arguments:   testcafe  chrome tests/specs/*/*.ts
* browser name and version: Chrome 74
* platform and version:          Ubuntu 16.04
* other:

**Comment by ampc** [comment]
I think I've found the issue, the web application I'm testing does a refresh request to update session and somehow it fails

```:40083/nBq9WuIBS/https://smart-pre.mobime.local/auth/refresh:1 Failed to load resource: the server responded with a status of 419 (unknown)```

**Comment by aleks-pro** [comment]
Hello @ampc ,

Can you please check if this issue is reproducible without TestCafe? If it doesn't occur, please provide us with a public link to your application or send us a simple project which we can run to reproduce this behavior on our side.

**Comment by ampc** [comment]
Hi @aleks-pro I've sent credentials and link to support@devexpress.com. The web app tries to refresh token every 5 minutes, when I'm not using TC this process occurs without errors.

**Comment by AlexSkorkin** [comment]
Hi @ampc,
 
We've checked our Inbox, but have not found any emails containing this information. Would you please re-send your email again? Thank you in advance.

**Comment by ampc** [comment]
Sent :+1:

**Comment by AlexSkorkin** [comment]
Thank you. However, we don't have any new emails from you again. Please try sending your email to clientservices@devexpress.com.

**Comment by AlexSkorkin** [comment]
Hi, 
We received your information and will look into it soon.

**Comment by AlexSkorkin** [comment]
We found that you provided credentials only for one user. However, the issue we discussed in this thread involves two users. Did you intend to provide a second set of credentials for another user? If so, please share them with us.
 
Also, please provide us with a sample code without your helper functions so that we can run it on our side. Or, provide us with your complete test code including your helper functions.

**Comment by ampc** [comment]
Sent access to my private repo :ok_hand:

**Comment by AlexSkorkin** [comment]
Thank you. I've received your invitation and we are looking into it...

**Comment by helen-dikareva** [comment]
I couldn't reproduce the behavior you described (or anything similar to it) on my side.
I started a test run using `testcafe chrome ./tests/specs/*/*.ts` and `testcafe -c 2 chrome ./tests/specs/*/*.ts`. I had some failed tests. But it seems like it isn't related to switching between roles.
You can find my test run reports in the following files: in Chrome `report.txt` and in Chrome with the concurrency mode `report-c.txt`.
Please provide addition information on the problem:
- Could you please specify a minimal set of fixtures/tests required to reproduce the problem?
- Do you get an error with switching roles only in concurrency mode?
- Please provide us with your test run report.
[report.txt](https://github.com/DevExpress/testcafe/files/3253380/report.txt)
[report-c.txt](https://github.com/DevExpress/testcafe/files/3253381/report-c.txt)

**Comment by ampc** [comment]
Thank for your analysis,
- I think it's related with time, not with specific fixtures, e.g. after 5 minutes the token expires, testcafe gets HTTP 419 response from server and the tests start failing on the immediate step after `useRole` call  .
- I get the error on both modes single and concurrent.
- I've also detected a bug in our web application, it doesn't support multiple tabs.

**Comment by ampc** [comment]
Just re-ran tests and it worked :thinking:  I'll close this issue. Thank you for your time :+1:
