### ISSUE TITLE
Allow dates and times to be added to file names in .testcaferc.json

### ISSUE THREAD

**Issue by jbradensmile** [DevExpress/testcafe#3844]
### Are you requesting a feature or reporting a bug?
Requesting a feature.

### What is your Test Scenario?
In the .testcaferc.json file, I want to be able to append a date to the reporter.output object.

### What is the Current behavior?
Currently, we cannot append a date-time to the output value.

### What is the Expected behavior?
In the reporter.output, I want to be able to give a path and file name, including a formatted date, like "reporter": { "output": "artifacts/reports/report${DATE}${TIME}.html"}

### How would you reproduce the current behavior (if this is a bug)?
In the .testcaferc.json file, inside the reporter object, for the output child, try to name the file with ${DATE} and or ${TIME} in the string.

#### Provide the test code and the tested page URL (if applicable)

 
Your website URL (or attach your complete example):

Your complete test code (or attach your test files)

```
{
    "browsers": "chrome",
    "src": "Scripts",

    "reporter": {
        "name": "html",
        "output": "./Artifacts/Reports/report${DATE}_${TIME}.html"
    },

    "screenshotPath": "./Artifacts/Screenshots/", 
    "screenshotPathPattern": "${DATE}_${TIME}/test-${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.png",
    "takeScreenshotsOnFails": true,

    "videoPath": "./Artifacts/Videos/",

    "videoOptions": {
        "failedOnly": true,
        "pathPattern": "${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.mp4"
    },

    "videoEncodingOptions": {
        "r": 20,
        "aspect": "16:9"
    },

    "quarantineMode": true,
    "skipUncaughtErrors": false
}

```
### Your Environment details:
 
* testcafe version:        1.1.4           
* node.js version:         10.13.0         
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other: Maybe a "reportPathPattern" child in the reporter object would work?
* workaround: Currently, I have to run a powershell script that runs my testcafe project, then renames the report.html file after the execution of my project. It would be better if testcafe was able to do this all on its own by allowing us to append dates to the file name without the need of an external powershell script.

**Comment by LavrovArtem** [comment]
Thank you for sharing your idea with us. We will discuss it and consider implementing it in one of our future product updates.

**Comment by parekhkb** [comment]
I would really like this feature. When you run your tests multiple times, it's unfortunate the the report file is overwritten each time. You end up with many Screenshot/Video capture folders, one per each run, but the report output is a single file that only represents the most recent test run.

**Comment by Farfurix** [comment]
@parekhkb 

Hello,

Thank you for your interest in this feature. At present, I cannot give you any estimates on when the feature will be implemented. Since it is not in progress, your PR is welcome.
