### ISSUE TITLE
page url in screenshot 

### ISSUE THREAD

**Issue by mokone91** [DevExpress/testcafe#3850]
Hi, is its possible to include a browser url bar in a screenshot?
sometimes it can help to allocate a issue.
For example sometimes we can get a screenshot of notfound page, or even white page when we build SPA
Thanks!

**Comment by aleks-pro** [comment]
Hi @mokone91 ,

Testcafe doesn't support this functionality. The only thing I can suggest right now is to use [ClientFunction](https://devexpress.github.io/testcafe/documentation/test-api/obtaining-data-from-the-client/) to obtain a page url. See the following example:
```JS
import { ClientFunction } from 'testcafe';

fixture('New Fixture')
    .page('https://example.com');

test('New Test', async t => {
    const getURL = ClientFunction(() => window.location.href);
    const url    = await getURL();

    console.log(url);
});
```
 So you can call the getUrl function wherever you expect a screenshot is going to be taken.
 
P.S. This issue looks like a question that would be best asked on [StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions. We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)).

**Comment by mokone91** [comment]
Hi, sorry for delayed response.
The point of this issue is to discuss the ability of adding page url to screenshot which taken when test fails(--screenshots-on-fails).
Use case:
During test you get screenshot of 404 or 502 page, and you actually can only guess where the browser is now.

Thanks!
Eldar.

**Comment by AlexSkorkin** [comment]
Hi Eldar,
 
Thank you for your clarification. At the moment, there's no such a feature out of the box.
 
When you take a screenshot using the corresponding takeScreenshot action, you can use a third-party library to manipulate the image. For instance, check out the following thread where you can find more information on how to apply a watermark:
 
[How can I apply a watermark in images using JavaScript?](https://stackoverflow.com/questions/38700884/how-can-i-apply-a-watermark-in-images-using-javascript)
