### ISSUE TITLE
TestCafe cannot hit public port using BrowserStack without Local Testing

### ISSUE THREAD

**Issue by carolmirakove** [DevExpress/testcafe#3853]
### What is your Test Scenario?
As described in #3757 I would like to use BrowserStack without Local Testing in order to avoid unnecessary latency. I am running tests on a Jenkins Windows server which has two ports publicly accessible. I am passing those publicly available ports as `--ports` args with the testcafe run command.
Our Jenkins server uses the `testcafe-browser-provider-browserstack` plugin.

### What is the Current behavior?
When I run tests via Jenkins with Local Testing set to true, they run as expected.
When I run tests via Jenkins with Local Testing set to false, they fail with a timeout, stuck on "Can't reach this page" at the TestCafe initial proxy.

### What is the Expected behavior?
The resolution on #3757 advised "Your TestCafe machine should have a public IP address or domain name in order to run tests without establishing a BrowserStack Local tunnel." 
- [x] I have confirmed accessibility to the server running my tests from my local machine via telnet:
`telnet ec2-my-public-ip-address.compute-1.amazonaws.com 3389`
  
### Steps to Reproduce
- in my Jenkins configuration (/configure), I added an env var `BROWSERSTACK_NO_LOCAL` and set it to `TRUE`
- I ran a test specifying the server hostname and its publicly available ports: `testcafe --hostname ec2-my-public-ip-address.compute-1.amazonaws.com  "browserstack:chrome@18:Windows 10" myTest.js --ports 3389,22`
- I went to browserstack automate dashboard for results https://automate.browserstack.com/

### Expected
Test is able to load the TestCafe initial proxy URL since the ports specified in the cmd args are publicly available

### Actual
Test times out at the TestCafe initial proxy URL, e.g., http://ec2-my-public-ip-address.compute-1.amazonaws.com:3389/browser/connect/{session}
 
### Logs 
I compared the raw logs in BrowserStack of the test run with `BROWSERSTACK_NO_LOCAL` set to `TRUE` vs. `FALSE` (all other configs were exactly the same):

`testcafe --hostname ec2-my-public-ip-address.compute-1.amazonaws.com  "browserstack:chrome@18:Windows 10" myTest.js --ports 3389,22`

Upon making the initial connection, both runs were identical (nb: the ports here were not specified by me to be used and are not publicly available):
```
15:36:15.842 DEBUG - Opening connection {}->http://localhost:13093
15:36:15.844 DEBUG - Connecting to localhost/127.0.0.1:13093
15:36:15.846 DEBUG - Connection established 127.0.0.1:1757<->127.0.0.1:13093
```

Where the TestCafe proxy is initiated the two runs also look identical:
```
16:02:49.319 INFO - To upstream: {"url":"http://ec2-18-207-111-139.compute-1.amazonaws.com:3389/browser/connect/O2rWqgJ"}
16:02:49.319 DEBUG - sun.net.www.MessageHeader@fe6b8a14 pairs: {POST /session/863E7C57-58A3-42F6-B3B2-674A86682CD9/url HTTP/1.1: null}{Authorization: Basic ZGFuYnJpbGxtYW4tamVua2luczpvYnViYXpqSlZiSkRIYXlrVlAxeA==}{Accept: application/json}{X-Forwarded-Host: hub-cloud.browserstack.com}{X-Forwarded-For: 18.207.111.139}{x-connid: 18030068419}{x-conn: close}{Content-Type: application/json; charset=utf-8}{Connection: close}{Cache-Control: no-cache}{Pragma: no-cache}{User-Agent: Java/1.8.0_181}{Host: localhost:50748}{Content-Length: 86}
16:02:56.453 DEBUG - sun.net.www.MessageHeader@1e31c6d6 pairs: {null: HTTP/1.1 200 OK}{Content-Type: application/json;charset=UTF-8}{Server: Microsoft-HTTPAPI/2.0}{Date: Thu, 30 May 2019 20:02:56 GMT}{Connection: close}{Content-Length: 14}
16:02:56.463 INFO - To downstream: {"value":null}
16:04:09.319 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@158cbb
16:04:09.320 INFO - Handler thread for session 863E7C57-58A3-42F6-B3B2-674A86682CD9 (MicrosoftEdge): Executing POST on /session/863E7C57-58A3-42F6-B3B2-674A86682CD9/execute/sync (handler: ServicedSession)
```

But with Local Testing set to false, no document title is returned:
```
16:04:09.323 INFO - To upstream: {"script":"return document.readyState","args":[]}
```

And with Local Testing set to true, the document title is returned as expected:
```
15:37:38.285 INFO - To upstream: {"script":"return [document.readyState, document.title]","args":[]}
```

I see no errors in connectivity requests. Insight would be appreciated, my team is quite eager to avoid Local Testing.

**Comment by miherlosev** [comment]
Hi @carolmirakove 

At first glance, the problem is related to the usage of standard ports.
22 port is intended for SSH traffic, 3389 port - for RDP traffic (see the full list [here](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers)).
Try to use other ports - 9000, 9001. If the problem still persists, run TestCafe in [Live mode](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/live-mode.html) and send us a screenshot of an opened page.

**Comment by carolmirakove** [comment]
@miherlosev Thanks for the advice. I did know the intended use for the ports but thought it would be worth trying to reuse them.

I have opened 9000,9001 and ran my test with `--live`. The results didn't tell me much more; the console log reports `ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.` Here is a screenshot of the initial proxy, from which the test script never moves past:

![3853-page-not-found-at-initial-proxy](https://user-images.githubusercontent.com/747777/58728592-40250d00-83b5-11e9-8d47-0c3e88043f3d.png)

**Comment by miherlosev** [comment]
I assume that the ports didn't opened correctly.
Try to perform the following experiment:
1. Create a simple HTTP server
### server.js
```js
const http = require('http');

http.createServer((req, res) => {
	res.end('<html><body><h1>Simple http-server</h1></body></html>');
}).listen(9000);
```

2. Run it with the following command: `node server.js`
3. Open the http://es2-18-207-111-139.compute-1.amazonaws.com:9000 url.
You should get the following page
![image](https://user-images.githubusercontent.com/4133518/58805277-6f898300-861c-11e9-94f5-46c81f827ba9.png)

If you will get the 'Can't reach the page' message, it will indicate that the ports are not opened correctly. In this case, you need to fix it.

**Comment by carolmirakove** [comment]
Confirmed port 9000 is open
![3853 port 9000 is open](https://user-images.githubusercontent.com/747777/58825647-e9b20b80-860c-11e9-863b-466e92c5fc29.png)

**Comment by miherlosev** [comment]
I guess you checked the URL availability from your corporate network.  
Try to open the URL in the BrowserStack's mobile emulator.

![image](https://user-images.githubusercontent.com/4133518/58958256-303d6c80-87ab-11e9-88da-9c5b7923a5c0.png)
