### ISSUE TITLE
Pipeline shows green even when test fails

### ISSUE THREAD

**Issue by presha1** [DevExpress/testcafe#3854]
I am creating tests with testCafe, and running it in Concourse. Concourse shows green even when test fails.

**Comment by miherlosev** [comment]
Hi @presha1 

I am afraid this information is not sufficient to find the cause of the issue. Could you please provide more details: your test script, a command line or script that runs TestCafe and the `Concourse` configuration file?

**Comment by presha1** [comment]
Hi,
I am just using runner file start.js to run tests in different browsers in a queue.
I have package.json file with "test:e2e": "node scripts/startTests.js", And I simply starts test with npm run test:e2e.
Everything works fine locally. I have html test report created for each test runs as well.
In concourse, I am using the same script to run my tests. And it runs fine, create proper report. But just the problem is, though it shows in console that few test fails, pipeline is always green.

This part is being bit treaky for me, as though I assume test fails, i do need to create test report as well. I want to reciprocate this test fail by making pipeline red, instead of green, which shows everything is fine. But I want it to continue all further builds and test processes as well.
