### ISSUE TITLE
Improve detection of browsers closed during a test session

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#3856]
In Studio we use [a heir of TestRun](https://github.com/DevExpress/testcafe-studio/blob/master/src/recorder/record-run.js) and [an instance of BrowserConnection](https://github.com/DevExpress/testcafe-studio/pull/2485/files#diff-4e9d60d4b98ff3f88e4407ee6faa47fdR96).
Now we need some additional methods in TestCafe API:
1) we're not going to restart browser and test execution in the recording mode (e.g. if browser is hanging) because it may cause unexpected test playback. If it happens we will raise an error about unavailability of browser at once. 
So, we need to have a mode without browser restarting feature. In this case the `disconnected` event should let to an error raising.

2) we are following browser by using [`browserTools.watchWindow` ](https://github.com/DevExpress/testcafe-studio/pull/2485/files#diff-548627e85dc298fe848971a9ff88a75bR21) to be able stop recording if browser is closed. But we can't [switch off a connection](https://github.com/DevExpress/testcafe/blob/master/src/browser/connection/index.js#L257) without closing a browser beforehand. We can do it only by hacking: mocking some methods and using some internal methods. It would be nice to have such capability in API.

**Comment by helen-dikareva** [comment]
Based on [this bug](https://github.com/DevExpress/testcafe-studio/issues/2624) we found out that the following changes are required in TestCafe:
1) now we use the [`browserTools.watchWindow`](https://github.com/DevExpress/testcafe-studio/blob/master/src/recorder/connection-manager.js#L88) method to detect that a browser is closed during recording. It would be nice to move browser watching in [BrowserConnection class](https://github.com/DevExpress/testcafe/blob/master/src/browser/connection/index.js#L18). 
If browser is closed, an error should occur.
2) Better to start watching before opening a browser to prevent situations similar to https://github.com/DevExpress/testcafe-studio/issues/2624 (watching wasn't started). See the corresponding [line](https://github.com/DevExpress/testcafe/blob/master/src/browser/connection/index.js#L78)
Likely it would look like 
```js
Promise.race([
   this.provider.openBrowser(this.id, this.url, this.browserInfo.browserName), 
   this.on('error')
])
```
3) Maybe it would be required to have a customizable browser search timeout in [findWindow ](https://github.com/DevExpress/testcafe-browser-tools/blob/master/src/api/find-window.js) method.  To be sure that we'll find window even if watching starts before browser opening. Now we try to find browser's window 10 times with 300 ms timeout between attempts (hard coded).
3) We need to have handling of the situation when browser is closed before we found browser's window to start watching. Now [an error occurs](https://github.com/DevExpress/testcafe/blob/master/src/runner/browser-set.js#L86) after 2 minutes timeout. But this timeout should be customizable for Studio needs.

We still need the public method to prevent browser restarting (to get rid of this [line](https://github.com/DevExpress/testcafe-studio/blob/master/src/recorder/connection-manager.js#L56) and use it to prevent restarting after browser closing) and method to close only connection (instead of this [hacky code](https://github.com/DevExpress/testcafe-studio/blob/master/src/recorder/connection-manager.js#L34)). Described in [the previous comment](https://github.com/DevExpress/testcafe/issues/3856#issue-450844694).

**Comment by rob4629** [comment]
👋🏻 Just a friendly bump, as I notice we still run in to this issue occasionally
