### ISSUE TITLE
global setup

### ISSUE THREAD

**Issue by benmonro** [DevExpress/testcafe#3857]
### What is your Test Scenario?

similar to how jest has a setup and setupAfterEnv (https://jestjs.io/docs/en/configuration#setupfilesafterenv-array), it would be nice to have a way to have a global 'beforeEach' in testcafe.
### What are you suggesting?

this would help for the case when you have the same exact `beforeEach` in every fixture.
### What alternatives have you considered?

as far as I can tell there aren't any other ways to do this, other than always copy-pasting the same beforeEach to every fixture.
### Additional context

this would be useful w/ the testcafe testing library, where each test needs to do `addTestcafeTestingLibrary` in the before each.

**Comment by miherlosev** [comment]
Hi @benmonro 
 
I will close this suggestion in favor https://github.com/DevExpress/testcafe/issues/1739 because your suggestion is a part of this task.
