### ISSUE TITLE
Fix not-working example with RequestHooks

### ISSUE THREAD

**Issue by AlexKamaev** [DevExpress/testcafe#3858]
based on https://github.com/DevExpress/testcafe/issues/3786#issuecomment-497002996

see https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/

**Comment by VasilyStrelyaev** [comment]
Is it for https://github.com/DevExpress/testcafe/pull/3848?

**Comment by AlexKamaev** [comment]
yes

**Comment by VasilyStrelyaev** [comment]
Then what's it for - if the pr is merged?

**Comment by AlexKamaev** [comment]
I did't find that PR and missed that issue was fixed
