### ISSUE TITLE
Is it possible to uninitialize/reinitialize/delete role?

### ISSUE THREAD

**Issue by presha1** [DevExpress/testcafe#3859]
Scenario: I am running a test use test runs. For example: first test run execute tests in firefox browser, and next run in chrome (this is just example, I have cases where I need to run e2e tests in different stages as well) . I have used a role. When one test run completes, and it is running another test run, still the role cookie persist, and it acts as the user is logged in. 

Expected behavior: Roles should be re-initialized for each run.

Is there some way I can clean the cookie, or un-initialize the roles?

**Comment by AlexSkorkin** [comment]
Thank you for your inquiry. I see that you submitted your question on StackOverflow - an amazing platform for users to ask and answer questions.
 
We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafeontributing)).
 
Refer to your StackOverflow thread for further correspondence:
 
[Is it possible to uninitialize/reinitialize/delete role in testcafe E2E test?](https://stackoverflow.com/questions/56439705/is-it-possible-to-uninitialize-reinitialize-delete-role-in-testcafe-e2e-test)

**Comment by presha1** [comment]
Hello,
Can I ask it as feature? Ability for roles to be deleted or reinitialized. (I did not get answer that fits in stackoverflow)

**Comment by Farfurix** [comment]
@presha1 

Hello,
 
Thank you for your inquiry. At the moment, we don't see any practical scenarios where such functionality could be introduced. In your scenario, you can use the following [workaround](https://stackoverflow.com/a/56445455/10448174) with applying the fixture hooks mechanism.
