### ISSUE TITLE
Execution sequence of the addRequestHooks and removeRequestHooks methods

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe#3861]
### What is your Test Scenario?
The `foo` request hook will never catch any request in the following example:

```js
await t
    .addRequestHooks(foo)
    .click(something)
    .removeRequestHooks(foo);
```

### What are you suggesting?
The described chain should work.

### What alternatives have you considered?
A possible workaround is to break the chain.

```js
await t.addRequestHooks(foo);
await t.click(something);
await t.removeRequestHooks(foo);
```

**Comment by JWvP** [comment]
The solution of breaking the chain works indeed, although you can do without adding the `await` to every new line;

`await t.addRequestHooks(foo);
              .click(something);
  await t.removeRequestHooks(foo);`

should also work.

**Comment by AlexKamaev** [comment]
@JWvP 
it's better to use the `await` keyword before the `t.click` method since `t.click` returns a promise, and if somebody adds some other method after the `t.click` method, it can lead to unexpected issues.
