### ISSUE TITLE
Chrome headless hangs and doesn't work

### ISSUE THREAD

**Issue by gooddaytoday** [DevExpress/testcafe#3862]
### What is your Test Scenario?

typescript `test.ts` file: 

```typescript
import { Selector } from "testcafe";

fixture("Load Google").page("http://google.ru");


test("Loading Google...", async t => {

    await t.expect(Selector("#hplogo").exists).ok();

});
```

### What is the Current behavior?

 One of two behaviours:

1. Headless Chrome runs and test hangs with message `Loading Google...`  in console. Checked this also in VSCode debugger:
- steps `await t.except()..` and others if you add smth are calls.
- test waits endless for `await t.except()..`
2.  After some runs testcafe coudn't find chrome:headless and dont't ever run test with message: 

> ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.

### What is the Expected behavior?

Testcafe runs test in chrome's headless mode
 
### What is your web application and your TestCafe test code?

http://google.ru

### Steps to Reproduce:

1. `npm install testcafe --save`
2. `testcafe chrome:headless test.ts`
3. Test hangs
 
### Your Environment details:
 
* testcafe version: 1.2.0                  
* node.js version:  8.9.2 and 10.15.0                  
* command-line arguments: 
  * `testcafe chrome:headless test.ts`   
  * `testcafe chromium:headless test.ts`   
  * `testcafe "chrome-canary:D:\Users\<userfolder>\AppData\Local\Google\Chrome SxS\Application\chrome.exe:headless" test.ts`   
  * `testcafe "chromium:C:\Programs\chromium\chrome.exe:headless" test.ts`   
* browser name and version: 
  * Chromium: 77.0.3814.0
  * Google Chrome: 74.0.3729.169
  * Chrome-canary: 77.0.3814.0
* platform and version:  Windows 7.0.0        
* other: 
  * this bug was reproduced on chrome, chromium and chrome-canary on two computers.
  * non-headless chrome, chromium, chrome-canary runs successfully
  * headless firefox runs successfully

**Comment by Farfurix** [comment]
@gooddaytoday 

Hello,

I didn't reproduce this issue under Window 10 / Chrome 75 `:headless`, Chromium 77 `:headless` / `testcafe@1.2.0`.
 
Chrome and Firefox require a remote control port for TestCafe to attach to a browser instance. I suggest you specify the [`cdpPort` argument](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/testing-in-headless-mode.html#automation-port). For example:
```
testcafe "chromium:C:\Programs\chromium\chrome.exe:headless:cdpPort=9223" test.ts
```

And, of course, make sure that there are no restrictions for the Chrome / Chrimium / Chrome Canary browsers in your firewall / antivirus.

Let me know if it helps.

**Comment by gooddaytoday** [comment]
* `:cdpPort=9223` don't works
* there are no restrictions for the Chrome / Chrimium / Chrome Canary browsers in firewall/antivirus

It's strange, cause `firefox:headless` works fine. 

Some additional info: it seems, that with `chrome:headless` script works much more slowly. Even entering (just entering, before calling `await t.expect()` ) inside `test("", function () {})` takes 5-15x more time, than non-headless.

**Comment by gooddaytoday** [comment]
Some additional statistics:

* 4 Windows 7 computers with different NodeJS versions (7, 8, 10) hangs running test too.
* 5 Windows7/10 computers with different NodeJS versions run test successfully

**Comment by gooddaytoday** [comment]
Simple environment for repeat. Run `install_and_run.bat` to test.

[testcafe.zip](https://github.com/DevExpress/testcafe/files/3261063/testcafe.zip)

**Comment by LavrovArtem** [comment]
Like @Farfurix, I cannot reproduce this issue under Windows 7 and 10. The test always passes for 3-5 seconds. Maybe, the problem in Chrome behavior is related to Windows 7. You can try to run Chrome as [chrome:userProfile](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/user-profiles.html) as a workaround.

**Comment by gooddaytoday** [comment]
chrome:headless:userProfile don't work too.

**Comment by AlexSkorkin** [comment]
Thank you for the update. Until now, our attempts to replicate this issue were unsuccessful. On every machine where we have tried to execute your test, it is always passed quickly without any performance loss:
 
![image](https://user-images.githubusercontent.com/995726/59272136-00d0a900-8c5e-11e9-9cff-5941df53b242.png)
 
Are you running your tests in a corporate network or in some isolated environment? 
 
In your "Some additional statistics" message, did you mean that you executed your test on four and five different computers correspondingly?
 
![image](https://user-images.githubusercontent.com/995726/59272146-075f2080-8c5e-11e9-9e7f-6020a5a6c96f.png)
 
If so, are they located in the same network/environment?
 
In addition, please run the sysinfo tool on the computer where your tests are failing and export your computer information. It may provide some detailed information about your environment, so we can set up a similar one in order to replicate the issue. You might want to send your exported file to support@devexpress.com as it may contain private information. Thank you in advance.

**Comment by gooddaytoday** [comment]
> Are you running your tests in a corporate network or in some isolated environment?

Yes

> In your "Some additional statistics" message, did you mean that you executed your test on four and five different computers correspondingly?

Yes, different computers

> If so, are they located in the same network/environment?

Yes, same network

> In addition, please run the sysinfo tool on the computer

May be you could/wish recommend some particular sysinfo tool for this Issue?

**Comment by AndreyBelym** [comment]
> May be you could/wish recommend some particular sysinfo tool for this Issue?

You can use the built-in system information tool. Press the `Win+R` key combination on your keyboard, type `msinfo32` in the "Run" dialog and press `Enter`. You can save a system information report by using the `File -> Save` menu item.

In addition, I want to ask you to perform the following steps to collect Chrome debug logs:

1. Ensure the location of the Chrome executable file. Its default path is `C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`. If you can't find it in the default location, you can right-click Chrome shortcuts and use the `More -> Open File Location` and `Open File Location` menu items until you find the `chrome.exe` file.

2. Open a terminal window, navigate to a directory where you can create temporary files and create a temporary directory for a temporary Chrome profile:
```
cd D:\temp
mkdir debug-profile
``` 

3. Open an additional terminal window and start TestCafe with the following command:
```
testcafe remote --hostname localhost --ports 9000,9001 D:\tests\test.js
```

Replace the `D:\tests\test.js` path with an absolute path to your test file. If your system can't find the `testcafe` command, you can install it with `npm i -g testcafe`.

4. Execute the following command in the first terminal window:
```
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --enable-logging --v=1 --headless --remote-debugging-port=9222 --user-data-dir=D:\temp\debug-profile http://localhost:9000/browser/connect
```
Replace `C:\Program Files (x86)\Google\Chrome\Application\chrome.exe` with the actual path to the Chrome executable (step 1) and `D:\temp\debug-profile` with the actual path to the temporary debug profile (step 2). If you use PowerShell, add the `&` character and space at the beginning of the command:
```
& "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --enable-logging ...
```

5. Wait until TestCafe finishes or hangs. After that, locate the `D:\temp\debug-profile\Default\chrome_debug.txt` file and share it with me.

**Comment by gooddaytoday** [comment]
> In addition, I want to ask you to perform the following steps to collect Chrome debug logs:

I've done this and sended all info to your email. Test passed successfully, both with global testcafe and localy installed.

**Comment by AndreyBelym** [comment]
Thank you for the provided information. Unfortunately, I don't see anything that can give a clue about the reason for the issue? Would you mind to perform two additional steps for me?

1. Try to run the following command and check if it passes or hangs:
```
testcafe "chrome:headless:cdpPort=9222 --user-data-dir=D:\temp\debug-profile" tests
```
Remove all files from the temporary profile directory used in my previous instructions, and substitute its path in the place of `D:\temp\debug-profile`.

2. Try to install a debug build and run tests with it by executing the following commands:
```
npm i -g https://github.com/AndreyBelym/testcafe/releases/download/gh-3862-debug/testcafe-1.2.1.tgz
testcafe chrome:headless tests
```

**Comment by gooddaytoday** [comment]
> Would you mind to perform two additional steps for me?

Tried both and every try ended with hanging. In both cases `chrome_debug.log` is empty (seems that it 
open file for writing, hangs and doesn't close file with log cause of hanging)

**Comment by AndreyBelym** [comment]
Thank you for sharing your results. It's strange because there should be no difference between starting Chrome from the terminal and specifying `"chrome:headless:cdpPort=9222 --user-data-dir=D:\temp\debug-profile` to TestCafe.

I think you can take a look at the following points in the code if you want to debug the issue:

https://github.com/DevExpress/testcafe/blob/master/src/browser/provider/built-in/dedicated/chrome/index.js#L25

https://github.com/DevExpress/testcafe/blob/master/src/browser/provider/built-in/dedicated/chrome/runtime-info.js#L7

https://github.com/DevExpress/testcafe/blob/master/src/browser/provider/built-in/dedicated/chrome/create-temp-profile.js#L8

https://github.com/DevExpress/testcafe/blob/master/src/browser/provider/built-in/dedicated/chrome/local-chrome.js

https://github.com/DevExpress/testcafe-browser-tools/blob/master/src/api/open.js#L67
