### ISSUE TITLE
hasClass is not returning boolean result

### ISSUE THREAD

**Issue by dineshpaduchuri** [DevExpress/testcafe#3863]
I want to verify that titlerow div has class abnormal
![image](https://user-images.githubusercontent.com/42802100/58887696-b7370a00-8703-11e9-9c14-c323b7cca6e1.png)

tried using below it is returned type but not boolean
var resAbnormal = await Selector(resultCard.find('.dbm-lab-result-card-container').nth(y).find('.titlerow')).hasClass('.abnormal');
and tried like below and it is always returning false
  / const isAbnormal =await Selector(resultCard.find('.dbm-lab-result-card-container').nth(y).find('.titlerow').find('.abnormal'));
                //const isAbnormalSnapshot = await isAbnormal();
               // console.log(isAbnormalSnapshot.hasClass('abnormal'));
                 if (resAbnormal) {
                //     // await t.expect(Selector(resAbnormal).find('.value').find('span').getStyleProperty('color')).eql('rgb(203, 0, 0)');
                //     resCount = resCount + 1;
                //     console.log(resCount);
                 }

Please help me here

**Comment by LavrovArtem** [comment]
Thank you for your inquiry. The `hasClass` method takes a class name, the dot symbol is unnecessary.

Please note that we try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)). However this issue looks like a question that I suggest you [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.

**Comment by dineshpaduchuri** [comment]
That is mistakenly added in bug details. I have removed dot and checked still it is not returning boolean.

**Comment by AlexSkorkin** [comment]
Thank you for your clarification. I see that you submitted your question on StackOverflow. 
Please refer to your StackOverflow thread for further correspondence:
 
[hasClass method is not returning boolean result](https://stackoverflow.com/questions/56456157/hasclass-method-is-not-returning-boolean-result)
