### ISSUE TITLE
Browserstack urls not permitted

### ISSUE THREAD

**Issue by qakapil** [DevExpress/testcafe#3864]
### Are you requesting a feature or reporting a bug?
Bug

### What is your Test Scenario?
We are writing a new framework for UI testing on various browsers using testcafe with testcafe-browser-provider-browserstack plugin. Whilst this works fine on developer's local machine but it is not working for us in our CI environment. On the Jenkins machine where we try to run the tests the test is reaching out to these URLs which is restricted for the Proxy credential we used - 
https://eds.browserstack.com/ 
https://www.browserstack.com/ 
https://logs.browserstack.com/ 
https://repeater-local-*-prod.browserstack.com/

**Comment by miherlosev** [comment]
Hi @qakapil 

Could you please describe in detail what 'Proxy' do you mean and why the described behavior is a bug?
