### ISSUE TITLE
Testcafe requests take a very long time

### ISSUE THREAD

**Issue by CozyKourai** [DevExpress/testcafe#3871]
**What is the Current behavior?**
Using Travis, or Jenkins, testcafe returns unstable results unless we triple the default timeout (`selectorTimeout`, `assertionTimeout` & `pageLoadTimeout`) : the same tests were passing or failing randomly, mostly at page load, when checking for the page main div, some selectors were not found and trigger  an error on `await t.expect(selector.exists).ok()` while the selectors actually existed.

We did a bit of research using Jenkins to see what’s happening server side, to check if our component were slow to load, or to respond.
Our component were Ok, but we found out that’s actually the request that’s taking a lot of time, not the response as we were expecting. 
testcafe seems to take a lot of time (see chart below) to send the request for the selectors, sometime the request time it-self is longer than the timeout we set.
We did those tests on different environment (production, stagging, etc..), and using firefox and chrome. We run all our tests one by one (no concurrency problem), and the results end up beeing the same

![image_preview](https://user-images.githubusercontent.com/45870344/59036561-cfc43300-886f-11e9-98a9-0a9a289d32de.png)
On this exemple we can see the total request + response =12.2s but 11.8s where spent getting the request.

![image_preview3](https://user-images.githubusercontent.com/45870344/59036559-cf2b9c80-886f-11e9-9459-32ef1a07f230.png)
![image_preview2](https://user-images.githubusercontent.com/45870344/59036560-cf2b9c80-886f-11e9-8ad1-10816e87fe77.png)

As our tests instances use HTTPS/http2, we also try to launch the test using the flag `--disable-http2` while launching chrome, but it didn’t change a thing on request time.

**What is the Expected behavior?**
Stable results without the need for a bigger timeout.

What is your web application and your TestCafe test code?
Your website URL (or attach your complete example): https://github.com/cozy/cozy-drive
Your complete test code (or attach your test files): https://github.com/cozy/cozy-drive/tree/master/testcafe

**Your Environment details:**

- testcafe version: Currently 1.2.0 but we have the same problems on older versions
- node
```
    $ node --version
    v8.16.0
    $ npm --version
    2.15.12
    $ nvm --version
    0.34.0
    $ yarn --version
    1.3.2
```
- command-line arguments: https://github.com/cozy/cozy-drive/blob/master/testcafe/runner.js
- browser name and version: 
          Browser: HeadlessChrome 75.0.3770 / Linux 0.0.0

But we faced this issue with  HeadlessChrome 74 too

- platform and version:

Travis or Jenkins, we don’t face the problem while running tests locally

**Comment by miherlosev** [comment]
Hi @CozyKourai 

I was trying to set up your example repository and got many compilation errors for the `cozy-connector-libs` module (see the full [npm log](https://github.com/DevExpress/testcafe/files/3262213/log.txt)). 
Could you please tell me how I can fix that on my side? If it is easier, could you please provide the `cozy-connector-libs` module with precompiled binaries?

**Comment by CozyKourai** [comment]
Well it's gonna be quite hard to setup your own repository as we use rundeck, downcloud and a few other things that require secret tokens on travis. 

But, I created a test instance on our environment, so you can run the testcafe tests locally:
You'll need to setup this server before running `runner-drive.js`
```
export INSTANCE_TESTCAFE="testcafeissue.cozy.rocks"
export TESTCAFE_USER_PASSWORD="gitpassword"
```

Another thing you can do is a pull request in our repository

**Comment by miherlosev** [comment]
I ran your test site on my local machine and didn't face the slow request's problem.
 
> Travis or Jenkins, we don’t face the problem while running tests locally

 
According to this information, I can assume the problem is related to small CPU and memory amount on the CI virtual machines. Try to increase their value and let us know about results.

**Comment by CozyKourai** [comment]
We already check the CPU on Jenkins (which run on our own server), and only 60% of it was used.
(We cannot check on travis though)

**Comment by miherlosev** [comment]
Ok, I understand.
We need some more time to investigate the cause of the problem.

**Comment by miherlosev** [comment]
We investigated the example you provided and did not find obvious problems.
I recommend you try running your tests with the latest TestCafe (`1.3.3`) version.
If the problem persists, please reopen the issue and provide a sample so that we can use it to reproduce the problem on our side.
