### ISSUE TITLE
TestCafe: How to turn off advertisement in the logs for TestCafe studio?

### ISSUE THREAD

**Issue by KJHofstede** [DevExpress/testcafe#3873]
I'm using the open source version of Testcafe. I often notice announcements about TestCafe Studio in the logs. Is it possible to turn that off? It's annoying because my pipeline keeps failing.

![image](https://user-images.githubusercontent.com/46562822/59105748-ebddd800-8934-11e9-9fad-a0bd36ef8732.png)

**Comment by helen-dikareva** [comment]
Thank you for reporting this problem to us and let me take a moment to apologize for any inconvenience this issue might have caused you. 
We seem to found the cause of this problem with a pipeline failing and will do our best to fix it as soon as possible.   
We are printing this message about TestCafe Studio for three types of [reporters](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/reporters.html): `spec`, `list`, `minimal`.  
I suggest that you consider changing the reporter type as an immediate workaround.

**Comment by KJHofstede** [comment]
Thanks for the quick reply!

**Comment by KJHofstede** [comment]
Hmmm I need those reporters in my work process, but thanks anyway! Good luck fixing the bug!
