### ISSUE TITLE
The typeText function isn't working properly on a number input

### ISSUE THREAD

**Issue by BobLuursema** [DevExpress/testcafe#3878]
### What is your Test Scenario?
I'd like to type the number 51 into a number input.
 
### What is the Current behavior?
When the number input is empty it will type 15, except when using `paste: true`. But then when I use my Vue app it will initialize with 0 and then TestCafe will type `150` or when pasting `510` even when I specified `replace: true`.
 
### What is the Expected behavior?
The number 51 in the number input :-)
 
### What is your web application and your TestCafe test code?

test.js

<details>

```js
 import { Selector } from 'testcafe'

fixture('test')
.page('file:///home/bob/Desktop/test/vue.html')

test('test-1', async t => {
  await t
    .typeText(Selector('#inputnumber'), '51') // 150
    .wait(4000)
})

test('test-2', async t => {
  await t
    .typeText(Selector('#inputnumber'), '51', {caretPos: 0})  // 150
    .wait(4000)
})

test('test-3', async t => {
  await t 
    .typeText(Selector('#inputnumber'), '51', {replace: true})  // 150
    .wait(4000)
})

test('test-4', async t => {
  await t
    .typeText(Selector('#inputnumber'), '51', {replace: true, paste: true})  // 510
    .wait(4000)
})

test('test-5', async t => {
  await t
    .typeText(Selector('#inputnumber'), '51', {replace: true, speed: 0.2})  // 150
    .wait(4000)
})

test('test-6', async t => {
  await t
    .typeText(Selector('#inputnumber'), '51', {replace: true, caretPos: 0})  // 150
    .wait(4000)
})
```
</details>

vue.html

<details>

```html
<!DOCTYPE html>
<html>
<head>
  <script src="https://cdn.jsdelivr.net/npm/vue"></script>
</head>
<body>
  <div id="app">
    <input type="number" step="0.01" v-model="number" id="inputnumber">
  </div>
  <script>
  new Vue({
    el: '#app',
    data: {
      number: 0,
    }
  })
  </script>
</body>
</html>
```
</details>

### Your Environment details:
 
* testcafe version: 1.2.0
* node.js version: 12.4.0
* command-line arguments: testcafe chrome test.js
* browser name and version: Chrome 75.0.3770.80
* platform and version: Ubuntu 19.04

**Comment by PedroBorracho** [comment]
have a look to https://github.com/DevExpress/testcafe/issues/3865

**Comment by BobLuursema** [comment]
Thanks!
