### ISSUE TITLE
Gzip messaging requests to improve performance when running on Cloud Services (i.e.: Browserstack)

### ISSUE THREAD

**Issue by PedroBorracho** [DevExpress/testcafe#3879]
I'm working in improving the performance to speedup as much as possible the test execution during the CI pipeline.

Inspecting the traffic over network, I found out the most of the traffic is related to the **messaging** between the browser and the testcafe server: about 19k call with a generated traffic of 250MB
<img width="890" alt="Calls" src="https://user-images.githubusercontent.com/1810992/59145840-bba44100-89e9-11e9-94a6-9390eb40e81e.png">

and these calls are **not gZipped**
<img width="433" alt="call details" src="https://user-images.githubusercontent.com/1810992/59145846-cced4d80-89e9-11e9-964d-3ca9c541d32e.png">

This amount of traffic is not a big deal when the browser ant the Testcafe instance are on the same network, but it becomes serious when running against Cloud services (i.e.: Browserstack)

It would be great if these calls could be gzipped: it will save a lot of traffic and reduce the testing time!

**Comment by arubtsov** [comment]
Thank you for this report. Our team will need some additional time to research the issue in detail.

**Comment by miherlosev** [comment]
Hi @PedroBorracho 

At present, our service messages are not compressed. 
Right now, we are trying to use the `WebSocket` protocol for our service messages. It should strongly decrease the network traffic.

**Comment by PedroBorracho** [comment]
Thanks for the update!

Any idea on when the change will be introduced? Could you consider adding compression at ExpressJs level as short-term solution?

**Comment by miherlosev** [comment]
Hi @PedroBorracho 
 Any personal estimate may be misleading so I cannot give it for now.
 
> Could you consider adding compression at ExpressJs level as short-term solution?
 
We don't use the `Express.js` framework internally. 
At present, we will not add temporary solutions for this case, because the WebSocket-based implementation is already in progress.

**Comment by PedroBorracho** [comment]
> Hi @PedroBorracho
> 
> At present, our service messages are not compressed.
> Right now, we are trying to use the `WebSocket` protocol for our service messages. It should strongly decrease the network traffic.

Any update on this compression/websocket topics?

**Comment by wentwrong** [comment]
@PedroBorracho We rejected the idea to use WebSockets in the messaging process due to some issues. However, we extracted the messaging system into a worker. Please check whether the issue with a huge amount of traffic still persists.

In addition, perhaps, it will be useful to enable the [server-side caching](https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/speed-up-test-execution.html#enable-server-side-caching) feature. It's still experimental and it will not resolve the issue with our service messages. However, it will probably reduce the amount of outgoing traffic.
