### ISSUE TITLE
TypeText of TestCafe method doesn't work properly in Chrome 75

### ISSUE THREAD

**Issue by daenamkim** [DevExpress/testcafe#3881]
### What is your Test Scenario?
- Type a text and read it later after click on submission
 
### What is the Current behavior?
- Type a word backword  😱. i.e. "ABCD" => **DCBA**
  - if `{ paste: true }` and multiple strings are used, it will like this "ABCD", "EFGH" => **EFGH, ABCD**
- `{ replace: true }` is not applied.

(But it works well in Safari and Firefox)
 
### What is the Expected behavior?
- Type a work forward
- replace option should be working
 
### What is your web application and your TestCafe test code?
```js
await t
    .typeText(
      forgot.emailInput,
      'boaty',
    )
    .typeText(
      forgot.emailInput,
      '@abcd',
      { paste: true },
    )
    .typeText(
      forgot.emailInput,
      'test.co',
      { paste: true, replace: true },
    )
``` 

<details>
<summary>Screenshots:</summary>
<img width="201" alt="Screen Shot 2019-06-10 at 19 26 19" src="https://user-images.githubusercontent.com/16159767/59189667-aa0f9480-8bb5-11e9-85c0-3a3814fa978d.png">
</details>

### Steps to Reproduce:

1. Update the newest Chrome to 75 (Version 75.0.3770.80 (Official Build) (64-bit))
2. Run UI test with `TypeText` (see above)

### Your Environment details:
 
* testcafe version: 1.1.2 (1.2.0 also doesn't work)
* node.js version: v8.11.1
* command-line arguments:  
* browser name and version: Version 75.0.3770.80 (Official Build) (64-bit)
* platform and version: macOS 10.14.5 (18F203)

**Comment by Farfurix** [comment]
@daenamkim 

Hello,

We have already fixed a similar problem in the context of the following issue:https://github.com/DevExpress/testcafe/issues/3865. Please update your TestCafe to the `1.2.1-alpha.3` version.

We are going to release `v1.2.1` with this fix soon.

I will close it as a duplicate.
