### ISSUE TITLE
What causes the error    1) The iframe in which the test is currently operating does not exist anymore.

### ISSUE THREAD

**Issue by mmenninghaus** [DevExpress/testcafe#3892]
After clicking a certain button, a new IFrame is created in the html. I go back to the main window and then to the iframe and get the error
   1) The iframe in which the test is currently operating does not exist anymore.

after doing anything within the iframe. When debugging, the desired IFrame is visible and exists at the required moment. Any suggestions?

**Comment by miherlosev** [comment]
Hi @mmenninghaus 

I am afraid this information is not sufficient to find the cause of the issue. Could you please provide a page or a small example so that we can reproduce it on our side?

**Comment by mmenninghaus** [comment]
It is caused when testing our solution inside a Microsoft Dynamics CRM instance. I am afraid i cannot give you access. I only wanted to get a hint, when and why this error is usually thrown. That should be sufficient for now.

**Comment by miherlosev** [comment]
This situation occurs when the test performs the action in the iframe that is currently removed from DOM. 
See the following pseudo-code example:

```js
  test('test', async t => {
     await t
              .swithToIframe('iframe')
              .click('button')  // iframe was removed after this action
             .click('.another-button') 
 });
```

**Comment by mmenninghaus** [comment]
The html looks like this:
```
<html>
<div>
<iframe id="InlineDialog_Iframe" name="InlineDialog_Iframe" src="/SICDev/_controls/lookup/lookupsingle.aspx?browse=0&amp;class=ParentLookup&amp;dType=1&amp;objecttypes=2" style="height: 660.6px; width: 943.2px; border: 0px;"></iframe>
#document
<html>

</html>
</iframe>
</div>
</html>
``` 
I can access all elements, including other iframes, in the outer html. I am also able to switch to the questioned iframe. But i cannot access elements in the mentioned iframe. These elements are all in the inner html. Does this cause the error? How to avoid it?
I switch to the iframe by:  

```
    await t.switchToMainWindow();
    await t.switchToIframe(Selector('iframe#InlineDialog_Iframe'));
```

**Comment by miherlosev** [comment]
@mmenninghaus 

Unfortunately, we are unable to find the cause of the problem without access to your instance of Microsoft Dynamics CRM.
