### ISSUE TITLE
Concurrency keeps too many active sessions open.

### ISSUE THREAD

**Issue by danlomantoSamsungNext** [DevExpress/testcafe#3897]
### What is your Test Scenario?
When running tests using concurrency, I have noticed that as tests wind down (or if you're in the scenario here https://github.com/DevExpress/testcafe/issues/3274) that active browser/test sessions stay open even though tests aren't being run in them.  This is an issue because when running tests up in Browserstack, it is actually costing my company money.  It may be a small amount of time per test suite run, but those minutes add up and can become quite expensive.  It'd better if TestCafe both spun up and spun down necessary sessions for tests.

Another Reason why this should happen is that if I have separate test runs for different test suites that use the same Browserstack account, I would like to set my apps to be able to use all my available Browserstack parallel sessions.  If TestCafe uses all X of my test slots in Browserstack then my other test run is completely blocked.  And I don't want to allocate only a portion of my available Browserstack sessions to be used at a time.
 
### What is the Current behavior?
Configured number of concurrent browser sessions are created and kept open until ALL tests finish.

### What is the Expected behavior?
The number of browser sessions should increase up to concurrent limit and then be destroyed as they become unnecessary.
  
### Your Environment details:
 * testcafe version:                        1.2.1
* node.js version:                         v8.10.0
* command-line arguments:       "testcafe chrome -e test.js"
* browser name and version:      "browserstack:Chrome@62.0:Windows 10"
* platform and version:                macOS 10.14.3

**Comment by AlexKamaev** [comment]
Thank you for your suggestion. I think it really makes sense, however, it's a quite serious modification, so I cannot give any estimates on this. In this situation, I can only recommend you split your tests in parts and start several testcafe instances for each part.

**Comment by danlomantoSamsungNext** [comment]
Thanks for getting back to me @AlexKamaev !

By splitting up my tests and running several instances of testcafe, do you mean I should create multiple test runs using the concurrent option?  If so, then I can't do that due to the 2nd reason why  I created this enhancement.

Or are you suggesting that I somehow get all the desired tests in a test run and fire off multiple threads (one for each test I'd like to run) for the desired parallel execution?

**Comment by arubtsov** [comment]
Instead of running your tests concurrently, Alex suggested starting a number of testcafe runner instances and running separate parts of your tests in each of these instances without concurrency. This workaround will allow you to avoid idle browsers.

**Comment by danlomantoSamsungNext** [comment]
If I use different testcafe runner instances for each test then I'd have to aggregate all of the individual test results myself, correct?

**Comment by LavrovArtem** [comment]
Yes, you are right. In this case, you should aggregate individual test results by yourself. We understand that it is uncomfortable, but it seems that it is the only possible workaround which we can currently provide.

**Comment by danlomantoSamsungNext** [comment]
It feels like this is what testcafe should be doing in the background, right? Essentially spinning up the desired/appropriate number of browser sessions given the number of tests and level of concurrency.

**Comment by AndreyBelym** [comment]
Unfortunately, the idea behind this feature is very simple, but we need to put some serious effort to implement it in code. Currently, TestCafe's architecture doesn't allow changing the number of connected browsers after tests are started and can't terminate browsers one-by-one before tests are finished.

**Comment by dlangerenken** [comment]
How would someone implement this workaround? How do I split up my tests into chunks such that I have 8 same-sized test-suits that I can then start in parallel? Can I use some filter-function that allows me to only grep X tests?

**Comment by Dmitry-Ostashev** [comment]
Here is an example that shows how to run test suites in parallel:

```
const createTestCafe = require('testcafe');

let testcafe = null;

const runTests = (testFiles) => {
    const runner = testcafe.createRunner();
    return runner
        .src(testFiles)
        .browsers(['chrome'])
        .run();
};

createTestCafe('localhost', 1337, 1338)
    .then(tc => {
        testcafe = tc;
        return Promise.all([runTests(['test-suite-1.js']), runTests(['test-suite-2.js'])]);
    })
    .then(() => testcafe.close());
```

Also, you can use the runner.filter method to separate tests by test or fixture names.
