### ISSUE TITLE
Expose Browser Info to reporters

### ISSUE THREAD

**Issue by danlomantoSamsungNext** [DevExpress/testcafe#3898]
### What is your Test Scenario?
I'd like to get the link to the Browserstack session URL that's being used for a test run, into my custom report so that someone can easily get view a test run. I have found the Browserstack url by digging through the TestController object:

```
fixture`Getting started`
    .beforeEach(async (t) => {
            const url = test.testRun.browserConnection.browserInfo.userAgentProviderMetaInfo;
    })
```

The problem is that I have no way of getting that URL to my custom reporter.  It'd be nice if I could have some type of mechanism for setting some "report data" for a test that can be accessed via the **testRunInfo** object in the **reportTestDone()** function in a custom reporter.

### What are you suggesting?
It'd be nice to be able to somehow dynamically set data/properties, from within a test or hook, that can be accessed via a custom reporter. 

### What alternatives have you considered?
I've tried using the meta tags but I'm unable to dynamically set that value.
I tried setting a property in a **beforeEach()** function and have that property be used in a test.meta() tag. This, unfortunately, doesn't work.

**Comment by AlexKamaev** [comment]
Thank you for the detailed description. We already have a similar feature request: https://github.com/DevExpress/testcafe/issues/3584
We agree that this feature can be useful, however, we cannot give any estimates on this. If you want to create a PR with this feature, we will accept it and will help you.
