### ISSUE TITLE
Add example that illustrated filtering test by meta using 'exclude' pattern

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#3905]
https://github.com/DevExpress/testcafe/issues/1626#issuecomment-503006835
https://github.com/DevExpress/testcafe/issues/3153

**Comment by joywave** [comment]
This would be really useful and something every other test framework I've used has. For example I would expect something like  ` --test-meta type!=123` to skip tests that have a type of 123.

**Comment by AlexSkorkin** [comment]
Thank you for your input. We will take it into account.

**Comment by helen-dikareva** [comment]
+1 from DX @sergey-kanaev

**Comment by AlexKamaev** [comment]
fixed in https://github.com/DevExpress/testcafe-examples/pull/82
