### ISSUE TITLE
Test failing in IE 11

### ISSUE THREAD

**Issue by presha1** [DevExpress/testcafe#3906]
I am using browserstack to run my e2e tests. So far browsers I am using are chrome, safari, firefox and IE. Test passes in all other browsers except IE.
I am getting Javascript error in IE 11.0. 
![ie-error](https://user-images.githubusercontent.com/1432622/59668476-de3c1400-91b8-11e9-9c34-f5d97a2adbd8.PNG)

When I open my site in local IE browser, I can see warnings, but no javascript error.
![console-ie](https://user-images.githubusercontent.com/1432622/59668709-3b37ca00-91b9-11e9-930f-134a04784210.PNG)

**Comment by miherlosev** [comment]
Hi @presha1 

I am afraid this information is not sufficient to find the cause of the issue. Could you please provide a page or a small example so that we can reproduce it on our side?

**Comment by presha1** [comment]
Hi, 
I could not provide code as it is internal to the company, but I can send you screenshot of the error and console to ie. 
![ieerror](https://user-images.githubusercontent.com/1432622/61314440-e493cf00-a7fc-11e9-8fda-f54babb6623d.PNG)
![ieConsole](https://user-images.githubusercontent.com/1432622/61314449-e8275600-a7fc-11e9-93f8-905354e25f64.PNG)

**Comment by Farfurix** [comment]
@presha1 

Hello,

It is difficult to determine the cause of the issue without the page. Since you cannot provide us with the whole project, I suggest you prepare a minimal example page that demonstrates the issue. Our team will check it.
