### ISSUE TITLE
Random disconnection of chrome

### ISSUE THREAD

**Issue by HugoDel** [DevExpress/testcafe#3912]
### What is your Test Scenario?
Internal website testing. Testing the presence of images on a blog website.
 
### What is the Current behaviour?
Only with Teamcity agent on windows, not happening in on a local windows 10 computer. 
On a random basis (1 out of 5) test run, on a different test, the browser stuck on the page and the same error is displayed in the console almost every seconds. See the attached screenshot and chrome log file for more details. 
Can cause errors like : net::ERR_INSUFFICIENT_RESSOURCES

### What is the Expected behaviour?
The test should just pass or fail depending on the page.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
const createTestCafe = require('testcafe');
let testcafe = null;

createTestCafe('localhost', 1337, 1338)
    .then(tc => {
        testcafe = tc;
        const runner = testcafe.createRunner();

        return runner
            .src('./test-mobile/')
            .browsers(['chrome:emulation:device=iphone X; --no-sandbox'])
            .reporter([
                'teamcity',
                {
                    name: 'allure',
                    output: '/allure/allure-results'
                }
            ])
            // .reporter('spec')
            .screenshots('./report/screenshots/', true, '${USERAGENT}_${FIXTURE}_${TEST}_${QUARANTINE_ATTEMPT}.png')
            .run({
                skipJsErrors: false,
                quarantineMode: true,
                selectorTimeout: 45000,
                assertionTimeout: 45000,
                speed: 0.5
            });
    })
    .then(failedCount => {
        console.log('Tests failed: ' + failedCount);
        testcafe.close();
        process.exit(failedCount ? 1 : 0);
    });

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

<img width="376" alt="testcafe-error" src="https://user-images.githubusercontent.com/12988831/59766173-e28f2c80-929f-11e9-99e4-879d5b60e1e3.png">

[testcafe-error.txt](https://github.com/DevExpress/testcafe/files/3306103/testcafe-error.txt)
```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.1.4
* node.js version:                    12.4.0
* command-line arguments:  `chrome:emulation:device=iphone X; --no-sandbox`
* browser name and version: chrome 74.0.3729
* platform and version:          Windows Server 2016 in Hyper-V
* other:                                   Test running with Teamcity

**Comment by miherlosev** [comment]
Hi @HugoDel 
 
The `ERR_INSUFFICIENT_RESSOURCES` error indicates that web browser on the TeamCity agent machine does not have enough resources (memory or CPU). 
Try to increase the amount of resources which are not enough.

**Comment by HugoDel** [comment]
Hi! The `ERR_INSUFFICIENT_RESSOURCES` doesn't happen every time, only when **thousand** of ajax calls stay in `PENDING` status. The TeamCity agent is powerful enough to handle one chrome process.
Still, chrome stays open and got disconnected from the nodejs server. Two cases :

- If a test case is running, AJAX call to `:1337/browser/heartbeat/CI_C1~x` stay in `PENDING` in the network dev tool window.
- If the test page is loading, chrome displays a 404 error like in the screenshot below.

<img width="708" alt="testcafe-404" src="https://user-images.githubusercontent.com/12988831/59830619-52ed8a80-9340-11e9-88c8-b59722aee17d.png">

**Comment by miherlosev** [comment]
Do you mean that Google Chrome was not closed after test execution had finished?

**Comment by HugoDel** [comment]
Yes! It stays open on a 404 error OR calling each second `:1337/browser/heartbeat/` and request stay `PENDING` if the page is already loaded.

**Comment by LavrovArtem** [comment]
It seems like TestCafe break down and because of this heartbeat requests stay PENDING. Could you please look at the console output? Does it contain some errors?

**Comment by HugoDel** [comment]
As far as I know, I didn't notice any other error both in the browser console or in the command line console. I currently trying to reproduce the error and confirm that there is no error but I 99% sure that this is the case. 
Is there a way to debug a running process of TestCafé?

**Comment by HugoDel** [comment]
Here are some screenshots. No more information is available to me.
Starting pending message : 
<img width="896" alt="start_pending_status" src="https://user-images.githubusercontent.com/12988831/60106704-f20dea00-9765-11e9-82a0-36c1ed51003d.png">
No message from the server in the chrome devtool attached debugger :
<img width="949" alt="testcafe_error_server" src="https://user-images.githubusercontent.com/12988831/60106796-17025d00-9766-11e9-9869-d4fdfa6ba944.png">

**Comment by miherlosev** [comment]
Thank you for the provided details. 
At present, I don't have any ideas about why it happens.
To find the cause of the problem, I need an example which I can use to reproduce the issue on my side.
Try to provide access to your internal website and send all the necessary information at support@devexpress.com.

**Comment by HugoDel** [comment]
I recently discovered in your documentation de debug option `developmentMode`. I try with this mode and I get this from the browser console when testcafé is blocked : 
<img width="947" alt="Annotation 2019-06-27 174137" src="https://user-images.githubusercontent.com/12988831/60280850-0b4c9d00-9904-11e9-8995-76e2b79efd88.png">

Also, something I noticed is, when I press Enter in the testcafé console if the test is blocked, it stops the process and close the browser instance.

**Comment by AlexKamaev** [comment]
Unfortunately, this new information does not give us any clues on how to find the cause of the issue. Please provide us with all required information at support@devexpress.com.

**Comment by ZeddEn** [comment]
The issue seems to be fixed after the merge of this one: https://github.com/DevExpress/testcafe/issues/3929

**Comment by AlexKamaev** [comment]
@ZeddEn 
Thank you for updating this ticket. I hope that @HugoDel's issue is fixed as well.
@HugoDel 
If the issue persists, please feel free to contact us in this thread.
