### ISSUE TITLE
t.navigateTo(url) triggers TypeError in fixture.before() but not in fixture.beforeEach()

### ISSUE THREAD

**Issue by modelarious** [DevExpress/testcafe#3914]
### Example code
TypeError in .before():
```
fixture `Template tests`
    .page("http://www.google.com")
    .before( async t => {
        await t.navigateTo( "http://www.facebook.com" );
    });
```

No TypeError in .beforeEach():
```
fixture `Template tests`
    .page("http://www.google.com")
    .beforeEach( async t => {
        await t.navigateTo( "http://www.facebook.com" );
    });
```

### What is your Test Scenario?
I'm testing page X.  Before testing that page I must access page Y in order to perform a one-time setup for the whole test scenario.  To do this, I tried to use t.naviageTo(url) in fixture.before() which triggers an error : 
```
   1) - Error in fixture.before hook -
      TypeError: t.navigateTo is not a function
```

Do note that when used in fixture.beforeEach() it works as intended, but I don't want to perform the action on page Y before every test, I only want it done once at the start.
 
### What is the Current behavior?
TypeError is produced when I use t.naviageTo(url) in fixture.before()
```
   1) - Error in fixture.before hook -
      TypeError: t.navigateTo is not a function
```
 
### What is the Expected behavior?
Expected to navigate to the url in t.naviageTo(url) in order to perform a few actions to setup the test scenario
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

```js
 fixture `Template tests`
    .page("http://www.google.com")
    .before( async t => {
        await t.navigateTo( "http://www.facebook.com" );
    });


test('TC: blank test case', async t => {
});
```
</details>

<details>
<summary>Working version with beforeEach</summary>

```js
 fixture `Template tests`
    .page("http://www.google.com")
    .beforeEach( async t => {
        await t.navigateTo( "http://www.facebook.com" );
    });


test('TC: blank test case', async t => {
});
```
</details>

<details>
<summary>Your complete test report:</summary>

```
Running tests in:
 - Chrome 75.0.3770 / Mac OS X 10.12.5

 Template tests
 ✖ TC: blank test case

   1) - Error in fixture.before hook -
      TypeError: t.navigateTo is not a function

      Browser: Chrome 75.0.3770 / Mac OS X 10.12.5

          1 |
          2 |fixture `Template tests`
          3 |    .page("http://www.google.com")
          4 |    .before( async t => {
       >  5 |        await t.navigateTo( "http://www.facebook.com" );
          6 |    });
          7 |
          8 |
          9 |test('TC: blank test case', async t => {
         10 |});

         at Fixture.navigateTo (/Path/To/TemplateTests.js:5:17)
         at Fixture.fixture.page.before [as beforeFn] (/Path/To/TemplateTests.js:2:1)
         at FixtureHookController.runFixtureBeforeHookIfNecessary (/usr/local/lib/node_modules/testcafe/src/runner/fixture-hook-controller.js:62:35)
         at TestRunController.start (/usr/local/lib/node_modules/testcafe/src/runner/test-run-controller.js:190:57)



 1/1 failed (0s)

Does your QA team hate writing test scripts? Check out TestCafe Studio – now with an easy-to-use visual test recorder: https://devexpress.com/testcafe/studio
```
</details>

### Steps to Reproduce:

1. Simply execute the above test case
 
### Your Environment details:
 
* testcafe version:                  1.2.1
* node.js version:                    v10.15.0
* command-line arguments:  "testcafe chrome test.js"
* browser name and version: Chrome 75.0.3770
* platform and version:           Mac OS X 10.12.5

**Comment by miherlosev** [comment]
Hi @modelarious 

`fixture.before` is executed between test runs and do not have access to the tested page. 
It was designed to perform server-side operations like preparing the server that hosts the tested app.

If your set up requires access to the tested web page (ie navigation to other tested page) place it in the `fixture.beforeEach` hook.
