### ISSUE TITLE
Selector using 'withExactText' unexpectedly duplicates part of Selector content

### ISSUE THREAD

**Issue by harry7771** [DevExpress/testcafe#3915]
### Are you requesting a feature or reporting a bug?

bug.  thanks in advance for the help!

### What is your Test Scenario?

clicking a Selector that uses 'withExactText'.  
***NOTE: Using 'withText' in place of 'withExactText' resolves the issue!***

### What is the Current behavior?

-here's the Selector:
    const fooButton = Selector('div').withExactText('foo');
-here's the calling line of code:
    await t.click(fooButton);
-here's the TestCafe error:
    The specified selector does not match any element in the DOM tree.
        Selector('div.below_div')
            .withExactText('foo')
            .withExactText('foo')
-note that the 'withExactText' line above is unexpectedly duplicated

### What is the Expected behavior?

-'withExactText' Selector content should not be duplicated

### How would you reproduce the current behavior (if this is a bug)?

-I don't see this across all of my usage of withExactText, and I have been unable to determine what makes this case distinctive.

#### Provide the test code and the tested page URL (if applicable)

 
Your website URL (or attach your complete example):

Your complete test code (or attach your test files)

```js

```
### Your Environment details:
 
* testcafe version: 1.2.1                  
* node.js version:  10.13.0                  
* command-line arguments:  
* browser name and version: 
* platform and version: windows         
* other:

**Comment by miherlosev** [comment]
I am afraid this information is not sufficient to find the cause of the issue. Could you please provide a page or a small example so that we can reproduce it on our side?

**Comment by harry7771** [comment]
Thanks for the quick response, miherlosev.  I knew I wasn't giving you a whole lot of information to go on.  Unfortunately, I'm not able to add additional info for reproducing at the moment.  If I get that at some point, I will certainly send along.  Feel free to close this as you need.

Thanks again for the help.
