### ISSUE TITLE
Upgrade from testcafe v 1.1.0 to 1.2.1 - click selectors stopped working for some cases

### ISSUE THREAD

**Issue by apoluian** [DevExpress/testcafe#3920]
### Are you requesting a feature or reporting a bug?
Reporting a bug

### What is your Test Scenario?
I'm currently trying to upgrade 1.1.0 TestCafe version to 1.2.1. Some tests started failing after upgrade as previously working .click actions aren't clicking buttons and links if a button/link is part of the table. 

Also, the same buttons/links don't work under 'debug mode' with TestCafe:
1. Run tests under debug mode
2. Unlock page for the step where the button isn't clicked 
3. Click button

### What is the Current behavior?
Some buttons/links aren't clicked by selectors or under debug mode. 

### What is the Expected behavior?
Upgrade from version to version should not break tests. If there were some big changes in the release - notes for easy upgrade provided. 
Also, not sure why I can't click some buttons/links under debug mode but can do it while manually executing the same steps outside TestCafe or on version 1.1.0.

### How would you reproduce the current behavior (if this is a bug)?
Unfortunately, I can't share code/steps for application under test. But it's very weird that upgrade of TestCafe impacts tests. 
```
### Your Environment details:
 
* TestCafe version:                   v1.2.1
* node.js version:                    v10.15.3
* command-line arguments:  TestCafe chrome   -e --debug-mode
* browser name and version: Chrome 75.0.3770 
* platform and version:         Mac OS X 10.14.5

**Comment by LavrovArtem** [comment]
This information is not sufficient to find the cause of the issue. There can be many causes, and, therefore, we cannot give you recommendations without analyzing your code. Would you please create a small example that demonstrates this issue?

**Comment by apoluian** [comment]
@LavrovArtem, unfortunately, I can't publicly share information about the application under test. Checked other TestCafe versions, looks like it starts with version 1.1.1 (can't click buttons in debug mode as well.) Maybe it will help.

**Comment by LavrovArtem** [comment]
Unfortunately, it cannot help us. We cannot give you recommendations without analyzing your code. Could you please edit my example below and show how we can reproduce this error?

<details>
<summary>page.html</summary>

```html
<button>Click me!</button>
<input type="button" value="Click me!">
<script>
    document.querySelector('button').addEventListener('click', function (e) {
        e.target.textContent = 'Clicked!';
    });

    document.querySelector('input').addEventListener('click', function (e) {
        e.target.value = 'Clicked!';
    });
</script>
```
</details>

<details>
<summary>test.js</summary>

```js
import { Selector } from 'testcafe';

fixture`3920`
    .page`./page.html`;

test('button click', async t => {
    await t
        .debug()
        .click('button')
        .click('input')
        .expect(Selector('button').innerText).eql('Clicked!')
        .expect(Selector('input').value).eql('Clicked!');
});
```
</details>

Also, would you please try the alpha versions from the list below and find where the error starts to occur?

* 1.1.1-alpha.1
* 1.1.1-alpha.2
* 1.1.1-rc.1
* 1.1.1-rc.2
* 1.1.1-rc.3

**Comment by apoluian** [comment]
Hi, looks like I found a similar issue in your backlog: https://github.com/DevExpress/testcafe/issues/3904 

Steps to reproduce: 

1. Start test mentioned in 3904 with --debug-mode flag. 
2. proceed to 'Host status' page
3. click on any number in 'Host summary' table
4. click on any host in the table 

ER: clickable
AR: no clickable for TestCafe 1.1.1 or higher in debug mode.

**Comment by miherlosev** [comment]
Hi, @apoluian 

Thank you for the provided steps. We will investigate this issue after #3904 is fixed because this behavior can happen because of that problem.

**Comment by apoluian** [comment]
Also, tried versions of TestCafe provided above: 

1.1.1-alpha.1 - works 
1.1.1-alpha.2 -works
1.1.1-rc.1 - works
1.1.1-rc.2 - doesn't work, issue reproduced, JS errors occur all the time. In debug mode buttons are no longer clickable:
"      JavaScript error details:
      TypeError: Illegal invocation
          at i.get (http://192.168.1.36:55276/hammerhead.js:11:1431)
          at value (http://192.168.1.36:55276/hammerhead.js:6:6212)
          at getDropdown" 
1.1.1-rc.3 - haven't tried as above behavior most likely has been introduced in rc2.

**Comment by arubtsov** [comment]
Thank you for the additional information.

**Comment by apoluian** [comment]
Please advise if there is an ETA for this ticket. It's quite urgent for us and we won't be able to proceed with testcafe usage without it going forward.

**Comment by alexey-lin** [comment]
Any personal estimate might be misleading, so I cannot provide you with any. We will update this thread once we have any results.

**Comment by aleks-pro** [comment]
Hello @apoluian ,

We've made changes that may fix the problematic behavior. Could you check if the issue is reproduced in the latest TestCafe version (v1.10.1)?
If so, please send us a simple Web app and a test example, which we can use to reproduce the problem on our side.

**Comment by ebarila** [comment]
https://stackoverflow.com/questions/67779847/typeerror-hammerhead-extend-is-not-a-function

Hey, I'm experiencing this, not sure if related to the bug.

**Comment by Farfurix** [comment]
@ebarila 

Hello,

Your case doesn't seem to relate to original one.
