### ISSUE TITLE
Unable to PDF in an html page when script using testcafe 

### ISSUE THREAD

**Issue by dineshpaduchuri** [DevExpress/testcafe#3921]
When the application is opened through test script and if the web page has a pdf document along with the html content then the script is failing due to the pdf document is not loading in UI.

When the same application is opened manually then the pdf is loaded. Only through the test script the pdf is not loaded. No idea to use any addons here

Ran through test cafe:
Error descL
https://$aplicaitonurl$/assets/vendor/pdfjs/web/viewer.document.html?file=blob%3Ahttp%3A%2F%2F10.143.55.51%3A58854%2Ff36725ff-fc3d-47c3-8ece-03551debcbc6&openFile=true&download=false&viewBookmark=true&print=true":
![image](https://user-images.githubusercontent.com/42802100/59966881-e4771b00-953f-11e9-9c78-ea78b37155a9.png)

Opened manually
![image](https://user-images.githubusercontent.com/42802100/59966884-f8bb1800-953f-11e9-88f9-4a469bbc9e33.png)

**Comment by LavrovArtem** [comment]
This information is not sufficient to find the cause of the issue. There can be many causes, and, therefore, we cannot give you recommendations without analyzing your code. Would you please create a small example that demonstrates this issue?
 
Also, please provide us with your environment details (TestCafe version, node.js version, command-line arguments, browser name and version, platform and version).
