### ISSUE TITLE
[docs] Specify for which items our shortcuts work

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#3928]
In TestCafe and Studio docs.
Now we have only one note for content editable elements, but IMO we also should explain for which elements other our shortcuts work.
See shortcuts' code in [TestCafe](https://github.com/DevExpress/testcafe/blob/master/src/client/automation/playback/press/shortcuts.js#L183) and utils in [HH](https://github.com/DevExpress/testcafe-hammerhead/blob/8c832c78e04ec1d69a9da5af629629819a60a224/src/client/utils/dom.ts#L31).
Based on [a SOF ticket](https://stackoverflow.com/questions/56705435/remove-value-from-html5-date-input-using-testcafe).

**Comment by titerman** [comment]
The updated FAQ article answers this question https://testcafe.io/documentation/402636/faq/general-info?search#can-tests-emulate-keyboard-shortcuts-or-interact-with-browser-dialogs
