### ISSUE TITLE
Testcafè hangs without errors when there is a temporary network disconnection

### ISSUE THREAD

**Issue by mgallo** [DevExpress/testcafe#3929]
### Are you requesting a feature or reporting a bug?
Bug

### What is your Test Scenario?
The bug appears when launching the tests on a remote machine (Browserstack or similar, remote device) and a temporary network disconnection occurs. 
We were able to replicate the issue on two machines in the same LAN using the code attached in the gist below.

### What is the Current behavior?
When the network returns the tests won't continue, the browser is frozen and there are no error messages in the testcafè console. 

### What is the Expected behavior?
When the network returns, we expect the test to continue and either fail with an error, or better pass without errors.

### How would you reproduce the current behavior (if this is a bug)?
You should run the attached html file on a local httpserver (we used the "http-server" npm module to achieve that), run the test file we provided with the remote option and disconnect the network for a while. See the other readme.md file in the attached gist for more information.

#### Provide the test code and the tested page URL (if applicable)
 
Your website URL (or attach your complete example): https://gist.github.com/mgallo/e563f2a2fd69b8dc0fd6728ff00c991b 

### Your Environment details:
 
* testcafe version:                   1.2.1
* node.js version:                    10.15.0
* command-line arguments:  testcafe remote test-spec.js 
* browser name and version: Chrome 75.0.377.0
* platform and version:          MacOS 10.14.4
* other:                                   see the readme.md in the gist for additional information

**Comment by AlexKamaev** [comment]
Thank you for the detailed description. I was able to reproduce the issue. This behavior seems incorrect. We need some time to research it. We will reply to you when we have news.
