### ISSUE TITLE
Unable to run on Firefox from Jenkins on Alpine Docker

### ISSUE THREAD

**Issue by franciscolosardo** [DevExpress/testcafe#3933]
### What is your Test Scenario?
I'm using testcafe on a docker instanced by jenkins. This docker runs fine with chrome:headless but as soon as i run firefox:headless or firefox testcafe loses connection to the browser.
 
### What is the Current behavior?

ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
Is given whenever the firefox browsers are opened.
 
### What is the Expected behavior?
Firefox:headless browser should open and continue to execute.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
DOCKER FILE :

FROM alpine:edge
ARG CACHEBUST=1
RUN apk --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ add \
    nodejs \
    nodejs-npm \
    chromium \
    firefox \
    xwininfo \
    xvfb \
    dbus \
    eudev \
    ttf-freefont \
    fluxbox

RUN apk --no-cache add openjdk11 --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community

WORKDIR /opt/testcafe
RUN adduser -D -h /opt/testcafe user
USER user

RUN npm install \
    testcafe \
    testcafe-react-selectors \
    testcafe-angular-selectors \
    testcafe-vue-selectors \
    testcafe-aurelia-selectors \
    && npm cache clean --force \
    && rm -rf /tmp/*

ENV NODE_PATH=/opt/testcafe/node_modules
ENV PATH=${PATH}:/opt/testcafe/node_modules/.bin

USER root
COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh

ENV SCREEN_WIDTH=1920
ENV SCREEN_HEIGHT=1080

RUN firefox -headless

VOLUME [ "/tests" ]
EXPOSE 1337 1338
USER user
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD [ "testcafe" ]


--------

package.json script


    "test:ci:firefox": "testcafe --skip-js-errors \"firefox:headless\" main.ts --concurrency 6"


```
</details>

<details>
<summary>Your complete test report:</summary>
> testcafe --skip-js-errors "firefox:headless" main.ts --concurrency 6

Running test on: qa
Running suite: lrg
Post stage
ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.

Type "testcafe -h" for help.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testcafeApiDesigner@1.0.0 test:ci:firefox: `testcafe --skip-js-errors "firefox:headless" main.ts --concurrency 6`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the testcafeApiDesigner@1.0.0 test:ci:firefox script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

</details>

<details>
<summary>Screenshots:</summary>

</details>

### Steps to Reproduce:

1. Use the supplied dockerfile ...
2. Build a simple test
3. Create a runner under main.ts
4. Finally run the test:ci:firefox script on package.json
 
### Your Environment details:
 
* testcafe version: 1.2.1                   
* node.js version:    v10.16.0                
* command-line arguments: --skip-js-errors "firefox:headless" main.ts --concurrency 6
* browser name and version: Firefox 66 
* platform and version:  Linux Alpine        
* other:

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. As far as I know, Firefox requires a D-Bus session manager instance. You can use our Dockerfile and entrypoint script as a reference:

 https://github.com/DevExpress/testcafe/blob/master/docker/Dockerfile#L9

https://github.com/DevExpress/testcafe/blob/master/docker/testcafe-docker.sh#L5

**Comment by franciscolosardo** [comment]
Hi, its still not working propperly.
Dockerfile was modified to include 
```
RUN apk --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/ upgrade && \
 apk --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/ add \
 nodejs nodejs-npm chromium firefox xwininfo xvfb dbus eudev ttf-freefont fluxbox procps
```
package.json was modified to run
`    "test:ci:firefox": "dbus-daemon --session --fork Xvfb :1 -screen 0 \"1920x1080x24\" >/dev/null 2>&1 & export DISPLAY=:1.0 fluxbox >/dev/null 2>&1 & testcafe --skip-js-errors \"firefox:headless\" main.ts --concurrency 6",
`
Still having problem starting the firefox instance headless on linux alpine edge

**Comment by arubtsov** [comment]
One of the possible causes of the problem is using the `-concurrency 6` option - it can consume a lot of resources. We recommend you try getting things to work without it at first.

Since you are using Jenkins, you can also check if docker-entrypoint.sh is ignored. To do this, please use `/opt/testcafe/docker/testcafe-docker.sh firefox:headless main.ts` in the `test:ci:firefox` script.

We also suggest you check if the TestCafe Docker image works for you. If so, use the files referred by @AndreyBelym as a starting point and modify them as you require.
