### ISSUE TITLE
Hello i have a url and its not opening in IE 11 

### ISSUE THREAD

**Issue by avi0711** [DevExpress/testcafe#3934]
The URL use just fine in Chrome but not working in IE11

Here is the configuration:
IE:11
testcafe : 1.2.1
Node :11.3
Platform Windows 10

I have tried --hostname, i have also tried portnames but nothing works.
The moment the script runs in IE the url is as below:
MyIPaddress:port/browser/idle/<somecharacter>

**Comment by miherlosev** [comment]
I am afraid this information is not sufficient to find the cause of the issue. Could you please provide a small example so that we can reproduce it on our side?
