### ISSUE TITLE
Cannot get a function using eval

### ISSUE THREAD

**Issue by owen-m1** [DevExpress/testcafe#3935]
### What is your Test Scenario?
I have a simple HTML page with the following script tag:
```html
<script type="text/javascript">
	window.test = function() {};
</script>
```

and the following test:
```js
test('test', async t => {
    const test = await t.eval(() => window.test);
    console.log('window.test : ', test);
});
```
 
### What is the Current behavior?
Running the test will log `window.test : undefined`
 
### What is the Expected behavior?
It should log something similar to `window.test : function() {}`
### Your Environment details:
 
* testcafe version:                   1.2.1
* node.js version:                    v10.15.3
* command-line arguments:  testcafe chrome ./tests/test.js
* browser name and version: Chrome 75
* platform and version:          Windows 10 Version 1803

**Comment by miherlosev** [comment]
Hi @owen-m1 
 
In your case, the function will not be serialized to string automatically.
You need to do this yourself.

```js
test('test', async t => {
    const test = await t.eval(() => window.test.toString());
    console.log('window.test : ', test);
});
```

**Comment by owen-m1** [comment]
@miherlosev Actually I was hoping to get the actual function to be assigned to the variable, but then I realized I can just go further and get the serialized value I am looking for, or I can just run the code I need to run in the eval. So this is solved.
