### ISSUE TITLE
How can Jest be integrated in Testcafe

### ISSUE THREAD

**Issue by PonmaniAnnamalai** [DevExpress/testcafe#3942]
#### HEADS UP!

For TestCafe API, usage and configuration inquiries, we recommend [StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)).

You may also find answers in our up-to-date [documentation](https://devexpress.github.io/testcafe/documentation/getting-started/) and [answered questions](https://stackoverflow.com/questions/tagged/testcafe) on StackOverflow. This may save your time.

If you have already looked there and have not found an appropriate answer, [file a new question on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe).

**Comment by AlexKamaev** [comment]
Please provide us with full information about the issue using the following [template](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md). This will allow us to process your inquiry in the most efficient manner.
