### ISSUE TITLE
Ability to create unique context for each test in fixture's beforeEach

### ISSUE THREAD

**Issue by Evilweed** [DevExpress/testcafe#3944]
Please add possibility to set context in fixture's `beforeEach` in a way that it will be unique for each `test`.

I need to setup Backend before each test, and to do so I need to generate (for example) new unique user email, do some actions in fixture's `beforeEach`, and then use this user email in `test` block.

**Why:**
- Makes tests more readable in case you need different data between tests, yet you also need this data in fixture's beforeEach (especially if you need to use this data to setup backend);
- Gives more flexibility;
### What is your Test Scenario?
```
fixture(`Sample fixture`);

test('can signup to newsletter', async t => {
    const userEmail = generateRandomEmail(); // user1111@test.com
    await Backend.setupUser(userEmail);
    await t.useRole(UserRole.registered(userEmail));
    await newsletterPage.load();
    await newsletterPage.signUpToNewsletter(userEmail);
});

test('can complete checkout after newsletter signup', async t => {
    const userEmail = generateRandomEmail(); // user2222@test.com
    await Backend.setupUser(userEmail);
    await t.useRole(UserRole.registered(userEmail));
    await newsletterPage.load();
    await newsletterPage.signUpToNewsletter(userEmail);
    await paymentPage.completeCheckout(userEmail);
});
```

### What are you suggesting?
```
fixture(`Sample fixture`)
    .beforeEach(async (t, ctx) => {
        ctx.userEmail = generateRandomEmail();
        await Backend.setupUser(ctx.userEmail);
        await t.useRole(UserRole.registered(ctx.userEmail));
        await newsletterPage.load();
    });


test('can signup to newsletter', async t => {
    const { userEmail } = t.ctx; // user11111@test.com
    await newsletterPage.signUpToNewsletter(userEmail);
});

test('can complete checkout after newsletter signup', async t => {
    const { userEmail } = t.ctx; // user22222@test.com
    await newsletterPage.signUpToNewsletter(userEmail);
    await paymentPage.completeCheckout(userEmail);
});
```

### What alternatives have you considered?
None.

### Additional context
None.

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. I think the feature you requested is already implemented, take a look at the following article: [Test Code Structure - Sharing Variables between Test Hooks and Test Code](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#sharing-variables-between-test-hooks-and-test-code). Feel free to reopen the issue if you want to ask additional questions or share a use case that is not covered by our current implementation.

**Comment by Evilweed** [comment]
Thing I've described is NOT implemented. Let me simplify this:
This is what we have now:
```
fixture(`Spec`)
    .beforeEach(async (t) => {
        t.ctx.user = generateRandomUser();
        await  Backend.prepareUser(t.ctx.user);
    });

test('test', async t => {
    console.log(t.ctx.user); // <---- 11111@test.com (the same user as in other test case)
});

test('test', async t => {
    console.log(t.ctx.user); // <---- 11111@test.com (the same user as in other test case)
});
```

This is what I need:
```
fixture(`Spec`)
    .beforeEach(async (t) => {
        t.ctx.user = generateRandomUser();
        await  Backend.prepareUser(t.ctx.user);
    });

test('test', async t => {
    console.log(t.ctx.user); // <---- 11111@test.com
});

test('test', async t => {
    console.log(t.ctx.user); // <---- 22222@test.com (Different user than in first test case)
});
```

**Comment by Evilweed** [comment]
I'm sorry, this was a bug in my code - this can stay closed.
