### ISSUE TITLE
Ability to test and fix Selectors step by step in debug mode

### ISSUE THREAD

**Issue by Evilweed** [DevExpress/testcafe#3946]
Please add Ability to test and fix Selectors step by step in debug mode.

Time of execution  of E2E test scenario in some cases and in some type of websites can be very long. And because of that, if some selectors break during refactor, You need to run this very long test multiple times while trying to fix the selectors. This can take for example 1h to do.

Some of my tests take **15min** to finish execution. If I have to fix **100x** Selectors this takes a lot of time! 

### What are you suggesting?
With this feature being implemented, You could run test in debug mode, and whenever some selector was not found during test execution, the runner would pause and display `input` where You could test selectors. After inputing into this `input` value `Selector('.some-improper-class')` TestCafe would inform that no elements were found. After that, if You would input `Selector('.good-class')` and TestCafe would be able to find this element on page, You could update this selector in Code, press `Continue` button in TestCafe toolbar in browser and TestCafe would execute current step with this new Selector You have provided in input, and pause again next time it won't find another Selector.

**This would allow to fix whole test in one debug run - which would drastically reduce time to do refactors.**

### What alternatives have you considered?
None.

### Additional context
None.

**Comment by AlexSkorkin** [comment]
@Evilweed,
 
Thank you for sharing your idea with us. We are working on this feature in the context of this thread: #3244 .
 
I noticed that you already added a comment there. I will close this thread as a duplicate.
