### ISSUE TITLE
[BUG] Tests failing only on Android

### ISSUE THREAD

**Issue by owen-m1** [DevExpress/testcafe#3948]
Hi,
My tests (which involve using the drag actions), are all failing only on Android. When I watch the tests happen, the item that is supposed to be being dragged does not move. This is strange, because when I test manually on Android it works perfectly fine. The tests also pass on every other device.

They fail on every Browserstack Android device, and even on my own Android device (in all browsers).

So I am just wondering if Android is supported or not. It says [here](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/browser-support.html#officially-supported-browsers) that "Android Browser" is supported, but it does not specify which browser. If this is indeed a bug, I can provide all my test, but I would like to know if it is even supported first.

**Update**: This is very strange, but I just ran it on Chrome for Android on my remote device and the dragging was working. This test also happened to show a mouse as the pointer instead of a touch circle. Perhaps TestCafe only supports running tests on Chrome for Android, and the default browser for using the [testcafe-browser-provider-browserstack](https://github.com/DevExpress/testcafe-browser-provider-browserstack) on Android is not Chrome for Android?

**Update #2**: I just ran it again on Chrome for Android and the dragging did not work again, and the pointer went back to the circular touch indicator. Now I am really lost.

**Comment by miherlosev** [comment]
Hi @owen-m1 
 
> It says here that "Android Browser" is supported, but it does not specify which browser.
 
It's a mistake in our documentation. The "Android Browser" phrase should be replaced with the "Google Chrome mobile" one.
 
> I just ran it again on Chrome for Android and the dragging did not work again, and the pointer went back to the circular touch indicator. Now I am really lost.
 
Could you please provide a simple example which I can reproduce on my computer?

**Comment by owen-m1** [comment]
Hi @miherlosev,
You can clone this branch to see the tests: https://github.com/SortableJS/Sortable/tree/testcafe-tests

Run `npm run tests` and it should run some tests in Chrome and on a remote device (for which I used my Android device). For Android, if the circular touch indicator is used instead of a mouse pointer, then it probably won't be able to drag the elements when it should and the tests will fail.

**Comment by LavrovArtem** [comment]
I've reproduced this behavior on my Android device with Chrome 75 and now need some time to investigate this problem. We will inform you about the results.
