### ISSUE TITLE
opn is deprecated, switch to open

### ISSUE THREAD

**Issue by jamesgeorge007** [DevExpress/testcafe#3949]
[opn](http://npmjs.com/package/opn) was recenetly deprecated and renamed to [open](http://npmjs.com/package/open).

**Comment by jamesgeorge007** [comment]
I shall go ahead and shoot up a PR if someone could show a green signal here :+1:

**Comment by AlexSkorkin** [comment]
Please go ahead and submit your PR. We appreciate your cooperation.
