### ISSUE TITLE
Support code steps in Raw API

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#3954]

**Comment by AlexKamaev** [comment]
Testing plan:
1. async/await
2. promises
3. require absolute/relative modules
4. error handling and error stack with correct lines/columns
5. shared `t.ctx` between code steps
6. all available global variables and functions are working (setTimeout, new Array, everything)
7. __dirname, __filename
8. Capability to execute Selector/ClientFunction inside a code step
