### ISSUE TITLE
TestCafe hangs when a TypeScript class is passed as a dependency to a ClientFunction

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#3955]
### What is your Test Scenario?
Pass a class as a dependency to a client function in a TypeScript test. See the "Test Code" section.
 
### What is the Current behavior?
TestCafe hangs.
 
### What is the Expected behavior?
TestCafe executes the client function.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { ClientFunction } from 'testcafe';

class Foo {
    bar: number;
    
    constructor () {
        this.bar = 42;
    }
}

const exec = ClientFunction(() => new Foo(), { dependencies: { Foo }});

fixture `example`.page `example.com`;


test(`example`, async t => {
    console.log(await exec());    
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.2.1
* node.js version:                    any
* command-line arguments:  testcafe chrome test.ts
* browser name and version: any
* platform and version:          any
* other:

**Comment by Disorrder** [comment]
It happens also when you define a class into ClientFunction:

```javascript
const fn = ClientFunction(() => {
    class Foo {
        // . . .
    }
});
```

**Comment by alexey-lin** [comment]
@Disorder, Thank you for the information, we will take this into account.

**Comment by miherlosev** [comment]
@AndreyBelym @Disorrder

I cannot reproduce the problems with `testcafe@1.10.1`.

Example to reproduce:
```js

class Foo {
    bar: number;
    
    constructor () {
        this.bar = 42;
    }
}

const fn = ClientFunction(() => {
    class Foo1 {
    }
});

const exec = ClientFunction(() => new Foo(), { dependencies: { Foo }});

fixture `example`.page `example.com`;


test(`example`, async t => {
    console.log(await exec());    
	console.log(await fn());
});
```

Test report:
![image](https://user-images.githubusercontent.com/4133518/106242800-52ee8580-6219-11eb-8d57-d0e6ddf3a2ab.png)
