### ISSUE TITLE
Video recording  of test running is not showing up while folder created.

### ISSUE THREAD

**Issue by harryCompu** [DevExpress/testcafe#3957]
### What is your Test Scenario?
I am getting artifact/video folder but there is no video. I tried all possible combination. this is my runner section code

I have testcafe version : 1.1.3

### What is your web application and your TestCafe test code?
runner.src(tests);
    runner.browsers(['chrome --kiosk']);
    runner.reporter([{name : 'json', output : reporter}, 'spec']);
	
	runner.video('artifacts/videos', {
		singleFile: true,
		failedOnly: false,
		ffmpegPath: 'C:\ffmpeg-20190701-e51cc7e-win64-static\bin',
		pathPattern: '${TEST_ID}/${USERAGENT}/${FILE_INDEX}.mp4'
},{		r:20,
		aspect:'4:3'
});
    return runner.run({
        skipJsErrors: true,
        quarantineMode: false,
        selectorTimeout: 8000,
        assertionTimeout: 7000,
        pageLoadTimeout: 1000,
        speed: 0.9
    });
 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by AlexSkorkin** [comment]
I managed to record a video with your configuration. The only thing I changed in your config is the path to ffmpeg. Make sure that you specify this option properly. For instance, backslashes must be escaped; e. g.:
ffmpegPath: 'C:\\ffmpeg-20190701-e51cc7e-win64-static\\bin'

**Comment by harryCompu** [comment]
@AlexSK
I did ,what you said but still not getting recording video .I am getting two warning after test finishes.And I got a folder location correctly (C:\CESNew\CES\artifacts\videos\test-2\Chrome_75.0.3770_Windows_10.0.0) but have no video.
See the below warning message and help me to get it working please.


` **1/4 failed (36s)

 _**Warnings (2):
 --
  The browser window was resized during the "Test to setup Email with default host (Success)" test while TestCafe
  recorded a video. TestCafe cannot adjust the video resolution during recording. As a result, the video content may
  appear broken. Do not resize the browser window when TestCafe records a video.
 --
  _**_**The browser window was resized during the "Test to setup Email with default host (Failure)" test while TestCafe
  recorded a video. TestCafe cannot adjust the video resolution during recording. As a result, the video content may
  appear broken. Do not resize the browser window when TestCafe records a video.`**_**_**_**

**Comment by AlexSkorkin** [comment]
As the warning message states, your test case resizes the browser window, but should not. Make sure that your test case does not resize the browser window.
 
Also, your ffmpeg folder looks strange. I recommend that you install the @ffmpeg-installer/ffmpeg package from npm instead. See the [Prerequisites for Video Recording](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/screenshots-and-videos.html#prerequisites-for-video-recording) topic for more information.

**Comment by harryCompu** [comment]
@AlexSkorkin
Itried as you said but still not getting video. Is it possible for you to do 10 minutes one to one . I will share my screen .Its really important . 
Thanks

**Comment by devmondo** [comment]
@harryCompu, i could help if you want with one to one, as i successfully worked with video and testcafe before many times :)

**Comment by harryCompu** [comment]
@devmondo 

If you can share your skype ID or teams id at harish.kumar@compuware.com  as per your convenient time to show you my problem. My skype id is harish_prince1
Thanks
Harish Kumar
