### ISSUE TITLE
Give Browser Provider the Test Name

### ISSUE THREAD

**Issue by franciscolosardo** [DevExpress/testcafe#3958]
### What is your Test Scenario?

When browser provider's such as saucelabs browser provider plugins are included in testcafe, they can't get to know which test file is being runned, so , for example, saucelabs connector can't provide a job name to saucelabs while using concurrency in testcafe.
### What are you suggesting?

I'm suggesting testcafe browser providers should be notified at least the test filename it's being delivered or better yet a customized object passed in the test method with unique values for each provider.

**Comment by AndreyBelym** [comment]
Connected to https://github.com/DevExpress/testcafe-browser-provider-saucelabs/issues/23.
