### ISSUE TITLE
Provide an API to wait for third party requests

### ISSUE THREAD

**Issue by onyx-blackbird** [DevExpress/testcafe#3959]
We are trying to automate Analytics testing and Test Cafe seems a valid candidate especially with the Studio where Analytics Consultants without technical knowledge can create a test case.

Looking at the API I found the RequestHook, but with it I can only modify the request, but I'd need a way to wait for third party requests. I also tried the RequestLogger but this one also fails if the analytics request is a bit too late. So here is my suggestion add an API method to the RequestHook which waits for third party requests. This should be another "await" after the page is loaded.

Here my stub of a custom RequestHook:
```
import { RequestHook} from 'testcafe';

export class AnalyticsRequestHook extends RequestHook {
	constructor (requestFilterRules, responseEventConfigureOpts) {
		super(requestFilterRules, responseEventConfigureOpts);
		this._internalRequests = [];
	}
	async onRequest (event) {
		const request = {};
		if (event._requestInfo.method === 'get') {
			request.params = this._mapParams(event._requestInfo.url);
		} else if (event._requestInfo.method === 'post') {
			throw new Error('Not implemented');
		}
		this._internalRequests.push(request);
	}
	async onResponse (event) {
	}
	_mapParams (url) {
		//
	}
	//API
	contains(predicate) {
		//taken from RequestLogger, but need a logic to wait until at least one request is available in the _internalRequests array.
	}
}
```
The usage would be:
```
const hook = new AnalyticsRequestHook(/https:\/\/trackingdomain.com\//);

fixture('Analytics Test')
	.page('https://www.testdomain.com/en.html')
	.requestHooks(hook);
```

**Comment by helen-dikareva** [comment]
Thank you for your interest in TestCafe and TestCafe Studio.
It seems we have [a conversation](https://stackoverflow.com/questions/56835336/testcafe-how-to-share-variables-from-a-requesthook/) on the StackOverflow site. Let's continue our discussion in that thread.
