### ISSUE TITLE
Make tsConfigPath available in cli and api

### ISSUE THREAD

**Issue by timnederhoff** [DevExpress/testcafe#3972]
### What is your Test Scenario?
set the tsConfigPath via command line

### What are you suggesting?
testcafe will handle the tsConfigPath (or --ts-config-path) as an argument when running in cli.
Also, the `runner.run(options)` handles the tsConfigPath included in the options parameter.
the result is that it is possible to define the tsconfig file without setting a configuration file.

### What alternatives have you considered?
use a configuration file.

**Comment by timnederhoff** [comment]
It would also be nice to have TestCafe ignoring tsconfig files, and use its own default (like versions <1.30). After upgrading to 1.3.0 I got to add 2 files, one config to set the tsConfigPath (as my projects tsconfig breaks testcafe) and one tsConfig to re-set the default again.

**Comment by arubtsov** [comment]
Hello @timnederhoff ,

Thank you for your proposal. Our team will consider it when planning our future releases. In the meantime a pull request addressing this issue is welcome.

**Comment by timnederhoff** [comment]
Hi @arubtsov thanks for looking at is!
Here is the PR that adds this functionality: #3982

**Comment by timnederhoff** [comment]
ok cool, thanks!
