### ISSUE TITLE
Whitespace in browser executable not supported

### ISSUE THREAD

**Issue by onyx-blackbird** [DevExpress/testcafe#3973]
We are in a rather regulated environment and thus our browsers are very limited:
Chrome can only access DEV servers, but not the internet
IE can access most websites, but uses a proxy and has problems with the TestCafé proxy
Firefox is my browser of choice for manual testing, but it is a special build. And here I found a bug:
I am on a windows machine and the browser executable is called "Secure Firefox.exe". I provided the path to it as described in the documentation:
```
testcafe 'path:`c:\\Program Files\\Secure Browser\\Secure Firefox.exe`' mytest.js
```

I then get a windows error: `.\Secure could not be found ...`, so it seems it struggles with the space in the exe file as a space in the path should be supported with the backtick and it does not complain about `Program Files`. I am using git bash so single quotes but double backslash.

**Comment by Farfurix** [comment]
@onyx-blackbird 

Hello,

You need to use double quotation marks:
```
testcafe "path:`c:\\Program Files\\Secure Browser\\Secure Firefox.exe`" mytest.js
```
Check this sample out: https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#starting-browser-with-arguments.

**Comment by onyx-blackbird** [comment]
Sorry, but did you even read my post before closing it? I am using GitBash, which works as a bash and uses single quotes, else the path would already cause problems not only the .exe. Though I tried with double quotes, and then it complains (with \ or \\) `cprogram` cannot be found...

**Comment by Farfurix** [comment]
Thank you for your clarification. I've managed to replicate this "whitespace in the browser name" behavior under Git Bash.

The same issue occurs in command prompt on Windows:
```
testcafe "path:`c:\Program Files (x86)\Google\Chrome\Application\chrome Copy.exe`" test.js
```

I will reopen the issue and we will look into it.

**Comment by miherlosev** [comment]
![image](https://user-images.githubusercontent.com/4133518/106107310-d34cb200-6157-11eb-99af-d5fc0c3b44a2.png)

**Comment by AndreyBelym** [comment]
You should use single quotes in Bash, since double quotes do not prevent special character from being handled by the shell.
