### ISSUE TITLE
Decouple hostname value from host OS

### ISSUE THREAD

**Issue by mfestrada** [DevExpress/testcafe#3977]
### What is your Test Scenario?
We are attempting to deploy a TestCafe test suite behind a load balancer with a VIP and connecting to a Selenium Grid.  When the remoteConnection is made to the Selenium Grid, tests fail because the hostname forwarded along is for the individual machine instead of the VIP, which is not directly publicly accessible.

### What are you suggesting?
I am suggesting an override that bypasses resolving the specified hostname to a host's IP address.

### What alternatives have you considered?
I have tried setting the ```hostname``` option to match the VIP, but an error is thrown:

```shell
"The specified "https://foo.bar" hostname cannot be resolved to the current machine."
```

### Additional context
I cannot share specific project details but will provide as much context as I can if needed.

**Comment by arubtsov** [comment]
Hello @mfestrada,
 
Thank you for your suggestion. We will consider implementing it in future releases. Meanwhile, I would like to make a couple of notes concerning your scenario. First, the protocol is not related to the hostname, so you do not need to specify it in the corresponding option. Secondly, as a workaround, you can try to implement a loopback adapter on a machine where testcafe is running (you can refer to [this link](https://www.groovypost.com/howto/microsoft/install-a-loopback-adapter-in-windows-7/) for Windows and [this one](https://superuser.com/a/1089093) for Linux).

**Comment by mfestrada** [comment]
Hi @arubstov, thank you for your reply! 

1) Understood about the protocol, this is not an issue for me.
2) Can you explain this workaround?  I have a loopback adapter already available on the machine, not sure why I would need to implement another?

I've found a similar issue (#3134) but I am not keen on updating my instance hostnames with the public DNS entry if it can be avoided.

Also, since this feature has been up for discussion for a while (#1886), any possibility of expediting it?

**Comment by aleks-pro** [comment]
Hello @mfestrada ,

This feature is still in our plans, but we have not started to work on it yet and I cannot give any estimated time frame when it will be implemented.
 
Also, we need a bit more time to provide you with a detailed workaround. We will update this thread as soon as we have any results.

**Comment by aleks-pro** [comment]
Hi,

To resolve the issue we need to set the `hostname` option to a public virtual IP as you tried earlier. But in this case, TestCafe will validate the hostname by trying to set a connection with it. If the hostname is not reachable, TestCafe throws the known error: 
`"The specified "https://foo.bar" hostname cannot be resolved to the current machine."`
 
The idea of the workaround is to configure the loopback adapter on a local machine in such a way that it will answer requests to the address that is set in the hostname option (in your case it's the public virtual IP of your load balancer). So when TestCafe, in the process of hostname validation checking, will send a request to this address, the loopback adapter will answer it, and validation passes.
 
PS: the loopback adaptеr you already have on your machine is most likely configured to answer requests to the 127.0.0.1 IP address.
