### ISSUE TITLE
Testcafe Certificate issue

### ISSUE THREAD

**Issue by Testingfun** [DevExpress/testcafe#3978]
#### HEADS UP!

For a certificate enabled website (Certificate by a third party) to test in IE Browser using Testcafe, provided the ssl command.

`--ssl  p7b=pathtofilr.p7b `
as the pfx path is disabled and coudn't get that path.

**Commmand given**: `testcafe ie file.js --hostname localhost --ssl p7b=pathtofile.p7b`  also tried with this command: `testcafe ie file.js --hostname localhost --ssl pfx=pathtofile.p7b`

Getting this error:
![image001 (4)](https://user-images.githubusercontent.com/46961087/60644529-0cc21c00-9e54-11e9-8cf6-f3408cdff784.png)

Could you please assist on this issue.

**Comment by arubtsov** [comment]
Hello @Testingfun,
 
The `options` parameter of the `--ssl` argument contains options required to initialize a Node.js HTTPS server. You can find the list of those options in the documentation of Node.js (refer to [this](https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options) link). You can convert your `p7b` certificate to `pfx` as is shown for the example [here](https://www.lisenet.com/2014/convert-p7b-to-pfx-with-openssl/). We would recommend you to get things working on the examples [here](https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener) and then apply used configuration to run TestCafe.
