### ISSUE TITLE
Only use custom tsconfig when specified

### ISSUE THREAD

**Issue by timnederhoff** [DevExpress/testcafe#3979]
### What is your Test Scenario?
Testcafe keeps working in a project with a `tsconfig.json` in the root, using it's own typescript compilation config by default. If a specified tsconfig file is set/configured, that file is used for the typescript compilation config.

### What are you suggesting?
Many projects have a `tsconfig.json` file in the projects root, and run the Testcafe tests from that location. In many cases, the Testcafe typescript compilation fails because the project's tsconfig doesn't fit the testcafe typescript compilation settings.
It would be nice that test setups are working in projects with a tsconfig.json, by Testcafe ignoring the tsconfig.json. If you need specific compilation config, you can configure a specific file.

**Comment by LavrovArtem** [comment]
We have the same ticket [there](https://github.com/DevExpress/testcafe/issues/3970) and it was fixed. Please try to use the `testcafe@1.3.1-rc.1` version and feel free to reopen this issue if the problem occurs yet.

**Comment by timnederhoff** [comment]
not quite the same, but good enough :)
Thank you!

**Comment by AndreyBelym** [comment]
I apologize for the inconvenience. We decided to disable this problematic functionality as you suggested after discovering an additional set of conflicting options: https://github.com/DevExpress/testcafe/issues/3983.
