### ISSUE TITLE
DomUtils refactoring

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#398]
In the testcafe`s`domUtils`there are full or partial dublicates of functions from`testcafe-hammerhead`.
For example:

Testcafe
https://github.com/DevExpress/testcafe/blob/master/src/client/core/utils/dom.js
`getFocusableElements`
`isSelectElement`
`isTextarea`
`getParents`
`isDocumentRootElement`

Hammerhead
https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/utils/dom.js
`getFocusableSelector`
`isTextarea`
`getParents`
`isHtmlElement`

**Comment by AndreyBelym** [comment]
It's already done.
