### ISSUE TITLE
Allow to set a timeout for ClientFunction

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#3980]
### What is your Test Scenario?
Ensure that a Promise in `ClientFunction` will be fulfilled under all circumstances.

### What are you suggesting?
Add the `timeout` option to  `ClientFunction`'s options.

### What alternatives have you considered?
```js
function timeout (ms, msg = '') {
    return new Promise((_, reject) => setTimeout(() => reject(new Error(msg)), ms));
}

const myFunction = ClientFunction(() => {
   //...
   await Promise.race(someAsyncFunc(...args), timeout(3000, 'someAsyncFunc timeout'));
   //...
}, { dependencies: { timeout } }); 
```

**Comment by miherlosev** [comment]
It's a very rare use case. Please use the workaround from the issue description.
