### ISSUE TITLE
TestCafe can't compile TypeScript projects that have some specific options in tsconfig.json

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#3983]
### What is your Test Scenario?
Run tests written in TypeScript and enable the following TypeScript options in `tsconfig.json`:
```
"declaration"
"sourceMap"
"noEmit"
"noEmitHelpers"
"mapRoot"
```

And probably the following options too:
```
"rootDir"
"sourceRoot"
"lib"
"typeRoots"
"types"
```

### What is the Current behavior?
TestCafe can't compile test files and shows an error about conflicting options.
 
### What is the Expected behavior?
Successful compilation.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.3.1-rc.1
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by link89** [comment]
I can't get the point for this feature. 
For a well structure project this should not be a problem.
You webapp should have its tsconfig under webapp directory and test script should have a seperated one under test script directory. 
I don't think it worth to introduce a breaking change for such a feature.

**Comment by Pita** [comment]
We also seem to have a problem with esModuleInterop

**Comment by aleks-pro** [comment]
Thank you for the info, @Pita . We will check it when we get ready to fix the issue.

**Comment by orihomie** [comment]
Any updates? It seems this causes a problem when I'm trying to import dayjs lib in ts-mode, like:
> import dayjs from 'dayjs'; 

and when I'm trying to run test I get:

>Module '".../node_modules/dayjs/index"' can only be default-imported using the 'esModuleInterop' flag

**Comment by orihomie** [comment]
That's very annoying, I cant import any of date-libraries like moment or dayjs and this seems to me as a critical bug since I cant use ts-testcafe to write my tests on.

**Comment by orihomie** [comment]
Also seems to be related to https://github.com/DevExpress/testcafe/issues/3970

**Comment by SergeyShurygin** [comment]
@orihomie consider using import dayjs = require( 'dayjs')
(https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require)

**Comment by orihomie** [comment]
I've worked around using --ts-config-path and passing 
```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  }
}
```
onto testcafe launch script.
