### ISSUE TITLE
"Error" in terminal..

### ISSUE THREAD

**Issue by svaldesg** [DevExpress/testcafe#3984]
Why does this sign  `Error: No tests to run. Either the test files contain no tests or the filter function is too restrictive.` always come out, if I already do these tests in the TestCafe Studio and did not give an error. Also, I follow the Pluralsight course, wrote the same code an make the same steps, but still doesn't work. 
The TestCafe window pops out but closes automatically after finishing the loading. 
Why should I do, or try?

**Comment by AlexSkorkin** [comment]
Thank you for your inquiry. This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.
We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafeontributing)).

**Comment by svaldesg** [comment]
All fixed, was a version misunderstanding... with TestCafe 0.3.0 work immediately. Run  `npm install testcafe-blink-diff@0.3.0` to install that version. Also, I wasn't paying attention, cause the code I need it was on JavaScript, and I was writing down in TypeScript.

For some reason, my google chrome version was a problem too, so I change `Browser: Chrome 75.0.3770 / Windows 10.0.0` to  `Chrome 76.0.3809 / Windows 10.0.0`

**Comment by AlexSkorkin** [comment]
Thank you for sharing your findings with us.
