### ISSUE TITLE
Disable video on command line

### ISSUE THREAD

**Issue by hyunil-shin** [DevExpress/testcafe#3985]
### What is your Test Scenario?
I enabled video in .testcafec.json.
But, sometimes I want to disable video.

### What are you suggesting?
```
testcafe .... --video-options enable=false,...
```

**Comment by AlexSkorkin** [comment]
Thank you for your inquiry. This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.
We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafeontributing)).
