### ISSUE TITLE
Test hangs if an iframe is removed after an action in it

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#399]
([T353743](https://www.devexpress.com/Support/Center/Question/Details/T353743))

**Comment by AlexanderMoskovkin** [comment]
It is fixed in the github repo yet, so I will just add a test for this

**Comment by inikulin** [comment]
> It is fixed in the github repo yet

You mean `already`?

**Comment by AlexanderMoskovkin** [comment]
> You mean already?

Yes
