### ISSUE TITLE
Console errors ignored even with --skip-js-errors=false

### ISSUE THREAD

**Issue by ciarancourtney** [DevExpress/testcafe#3992]
### What is your Test Scenario?
I'm smoke testing all paths in my ui-router/angularjs app, basically a for loop containing a `t.navigateTo(path)`, but I'd also like every test to fail if there are console errors.
 
### What is the Current behavior?
Test runs with no failures, ignoring forced console errors and unhandled promise rejections.
 
### What is the Expected behavior?
Test fail on first console error encountered
 
### What is your web application and your TestCafe test code?
App is a private angularjs/ui-router app, local dev is served via webpack-dev-server. Below is a public fiddle example to demostrate issue.
 
<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```typescript
import { Selector } from 'testcafe';

fixture `New Fixture`
  .page `https://jsfiddle.net/boilerplate/typescript`;

test('New Test', async t => {
  await t
    .click(Selector('div').withText('16').nth(11).find('.CodeMirror-line'))
    .typeText(Selector('[class^="CodeMirror cm-s-default CodeMirror-wrap CodeMirror"]').find('div').find('textarea'), "console.error('dont ignore me!')")
    .click(Selector('.feather.feather-play'))
    .expect(Selector('#app').innerText).eql('Hello, Malcolm Reynolds');
});

```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
  "browsers": ["firefox"],
  "src": ["e2e/tests/"],
  "screenshotPath": "e2e-reports/screenshots",
  "screenshotPathPattern": "${DATE}_${TIME}/test-${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.png",
  "takeScreenshotsOnFails": true,
  "quarantineMode": false,
  "debugMode": false,
  "debugOnFail": false,
  "stopOnFirstFail": false,
  "skipJsErrors": false,
  "skipUncaughtErrors": false,
  "concurrency": 1,
  "selectorTimeout": 30000,
  "assertionTimeout": 1000,
  "pageLoadTimeout": 1000,
  "speed": 0.9,
  "developmentMode": false,
  "qrCode": false
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

I've noted this behaviour since I started using TestCafe since last year, it never seems to highlight any console errors.

### Your Environment details:
 
* testcafe version:                   1.3.1-rc.1
* node.js version:                    v10.15.3
* command-line arguments:  firefox --debug-on-fail
* browser name and version: Firefox 67.0.4 & Chrome 75.0.3770.100
* platform and version:          Windows 10
* other:                                   n/a

**Comment by aleks-pro** [comment]
Hello @ciarancourtney ,

Thank you for sharing your scenario with us. We will discuss the issue and update this thread as soon as we come up with a solution.

**Comment by rodmax** [comment]
hi, it seems i face with the similar(same) problem... I can't configure testcafe to able caught console errors in my web app.

To emulate the problem i add snippet to my app: 

```
 setTimeout(() => {
            throw new Error('Ups');
        });
```

and see the error (in --live mode after tests done)

![image](https://user-images.githubusercontent.com/6079597/61957549-2fb19d00-afc8-11e9-854a-2ef70dfe3b94.png)

but all tests passed

**Comment by miherlosev** [comment]
Hi @ciarancourtney @rodmax 

It's an expected behavior. TestCafe fails if there are unhandled errors and uncaught promise rejections on the tested page. it is important that error should be unhandled. It is critical for the tested web application and a customer should be notified about it. 
The `console.error` method call don't broke an application logic.

To achieve your requirements, use the 't.getBrowserConsoleMessages()' method.

```js
import { Selector } from 'testcafe';

fixture `New Fixture`
  .page `https://jsfiddle.net/boilerplate/typescript`
  .afterEach(async t => {
	  const { error } = await t.getBrowserConsoleMessages();

	  await t.expect(error[0]).notOk();
  });

test('New Test', async t => {
  await t
    .setTestSpeed(0.05)
    .click(Selector('div').withText('16').nth(11).find('.CodeMirror-line'))
    .typeText(Selector('[class^="CodeMirror cm-s-default CodeMirror-wrap CodeMirror"]').find('div').find('textarea'), "console.error('dont ignore me!')")
    .click(Selector('.feather.feather-play'))
    .expect(Selector('#app').innerText).eql('Hello, Malcolm Reynolds');
});
```
