### ISSUE TITLE
npm audit finds 4 vulnerabilities in lodash

### ISSUE THREAD

**Issue by r-s-sandbox** [DevExpress/testcafe#3995]
Running npm audit for a project with testcafe in the dependencies brings up vulnerability in lodash v.4.17.11.

### What is your Test Scenario?
npm audit
 
### What is the Current behavior?
found 4 high severity vulnerabilities
 
### What is the Expected behavior?
npm audit finds 0 vulnerabilities
 
### What is your web application and your TestCafe test code?
package.json:
result of npm audit

### Steps to Reproduce:
Create a directory and open it in terminal
Create package.json with testcafe in dependency
Execute "npm i && npm audit"
See the message about vulnerability
 
### Your Environment details:
 
* testcafe version: 1.3.1
* node.js version: v10.16.0
* command-line arguments: "npm i && npm audit"
* platform and version: "macOS 10.13.2"
* other: npm version: 6.10.0

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. TestCafe specifies the latest `lodash` version as a dependency - 4.17.11. I can't find any CVE for this version. Likely you have the `node_modules` directory or the `package-lock.json` file in a parent directory. Try to find and remove all `node_modules` directories and `package-lock.json` files in all parent directories.

**Comment by AndreyBelym** [comment]
I apologize for closing the issue, actually `lodash` has a security vulnerability - https://github.com/lodash/lodash/issues/4348. Strange that my `npm` doesn't report it to me. But we can't do anything about it until a new `lodash` version is released.

**Comment by r-s-sandbox** [comment]
lodash version 4.17.13 has been published with a fix. Any chance you can update to that version?

**Comment by miherlosev** [comment]
https://github.com/DevExpress/testcafe/pull/4012
