### ISSUE TITLE
.env testcafe vs testcafe studio

### ISSUE THREAD

**Issue by stychu** [DevExpress/testcafe#3996]
So I'm using dotenv for loading .env variables for my scripts.
I have a config.ts file in my root folder which is required in several places.
```
import * as dotenv from 'dotenv';
import * as process from 'process';

dotenv.config();

const config = {
  HOST_URL: process.env.HOST_URL || 'http://localhost:3000',
  ..............
```
When I run tests from CLI all works fine. .env . is loaded and all env variables are in place set up.
But when I run tests from testcafe studio it looks like the .env is not loaded therefore my tests fail. How can I approach this?

**Comment by miherlosev** [comment]
Please submit your TestCafe Studio questions to our [Support Center](https://www.devexpress.com/Support/Center/Question/ChangeFilterSet/1?FavoritesOnly=False&MyItemsOnly=False&MyTeamItemsOnly=False&TechnologyName=Testing+Tools&PlatformName=AllPlatforms&ProductName=TestCafe+Studio&TicketType=All). This repository is dedicated to the open source TestCafe version.
