### ISSUE TITLE
--use-fake-ui-for-media-stream --use-fake-device-for-media-stream --use-file-for-fake-video-capture arguments don't work

### ISSUE THREAD

**Issue by KomlevVladimir** [DevExpress/testcafe#3997]
In my test I need to interact with web camera. I pass the chrome options arguments to play fake video.
1)I run tests using command: testcafe "chrome --use-fake-ui-for-media-stream --use-fake-device-for-media-stream --use-file-for-fake-video-capture=./V90706-154641.y4m" tests/webcamTest.ts
2)Browser opens with url http://192.168.0.104:33825/tMHNA4DgC/https://mywebsite.com/, but 
web camera unavailable.
If I open https://mywebsite.com/ manually without http://192.168.0.104:33825/tMHNA4DgC/ then everything works well.
How to remove http://192.168.0.104:33825/tMHNA4DgC/ from url when I start the test?

```js
 fixture `Open website`
    .page (`${config.webcamUrl}`);

test('Web cam test', async t => {
    await t
        .wait(5000);

});
```
 
* testcafe version:                   1.3.1
* node.js version:                    v8.16.0
* command-line arguments:  chrome --use-fake-ui-for-media-stream --use-fake-device-for-media-stream --use-file-for-fake-video-capture=./V90706-154641.y4m
* browser name and version: Chrome 73.0.3683 / Linux 0.0.0

**Comment by miherlosev** [comment]
Hi @KomlevVladimir 

See answer in https://github.com/DevExpress/testcafe/issues/3532#issuecomment-470167128
