### ISSUE TITLE
TestCafe Studio enhancements/plugin

### ISSUE THREAD

**Issue by onyx-blackbird** [DevExpress/testcafe#3998]
I didn't find any link at the TestCafe Studio page to suggest features, so I hope it is ok to do so here.

I really like the recording functionality and Selector builder of the Studio. This is really helpful for my colleagues who aren't as technically versed as I am. The problem is, what we want to test is not just simple DOM manipulation, but analytics calls. I have a working script now where I wrote some helper classes to do the heavy lifting. But I can't use them in the Studio unless I convert a recorded test to a script. So for each test my colleagues would record (also for each edit), I would need to  convert that test to a script to be able to add my classes.

So my suggestion would be a some kind of macro I could write as script and the others could use them within the recorder just like the function but by selecting an existing macro from a list. And to go one step further if this macro could have parameters the user can provide.

If this is nothing you would consider for your roadmap is there a way to write our own plugins for this? I didn't find any info regarding this.

**Comment by miherlosev** [comment]
Hi @onyx-blackbird
 
1) We will think about the capability to publish the TestCafe Studio roadmap.
 
2) You mentioned several features:
* the ability to call custom JavaScript code from the recorded test
* the ability to pass parameters to a test
* support for the page model class
 
Please create an issue for each suggestion in our Support Center. This will help us prioritize these suggestions. You can post all your future questions and suggestion related to TestCafe Studio here.
 
This repository is dedicated to the open source TestCafe version.
