### ISSUE TITLE
Client service messages are still coming after the session has been closed

### ISSUE THREAD

**Issue by georgiy-abbasov** [DevExpress/testcafe#400]
Sometimes the client sends service messages after the session has been closed. For example:
'get-and-uncheck-downloading-flag', 
'done', 
'native-dialogs-info-set'

**Comment by AlexanderMoskovkin** [comment]
It leads to a js-error in the browsers but doesn't take effect on test because it's finished yet

**Comment by AlexanderMoskovkin** [comment]
moved to https://github.com/DevExpress/testcafe-legacy-api/issues/13
