### ISSUE TITLE
TestCafe freezes when accessing a specific URL

### ISSUE THREAD

**Issue by sijosyn** [DevExpress/testcafe#4002]
### What is your Test Scenario?

We do have a test scenario that does SSO (Single sign on) authentication and TestCafe freezes when it hits this URL - https://bridge.auth-gateway.net.ent-web01.dev.synacor.com/saml/module.php/bridge/test/offsite_login_dest.php
 
Kindly appreciate if TestCafe team can fix this issue asap. Thanks.

### What is the Current behavior?

 
TestCafe freezes when it hits the provided URL

### What is the Expected behavior?

TestCafe should not freeze/hang and complete the test run
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example): URL provided above

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 fixture `Getting Started`
	.page `https://bridge.auth-gateway.net.ent-web01.dev.synacor.com/saml/module.php/bridge/test/offsite_login_dest.php`;

test('My first test', async t => {
	// Test code
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

Run the provided testcode with URL
 
### Your Environment details:
 
* testcafe version:                    v 1.2.1 & v1.3.1
* node.js version:                     v8.11.1
* command-line arguments:   testcafe chrome test.js
* browser name and version:  Chrome 75
* platform and version:           macOS 10.14.5
* other:

**Comment by Farfurix** [comment]
@sijosyn 

Hello,

Could you please provide us with some test credentials so we can check your authentication scenario on our side? You can post it here or send it to support@devexpress.com.

**Comment by sijosyn** [comment]
Hi @Farfurix. We are developing a new feature and it is work in progress. So this new feature auth end to end integration scenario can only be tested within our firewall. Btw, you do not require test credentials to reproduce the freeze issue mentioned above. Just launch the provided URL in TestCafe and you can see TestCafe freezes. Could you please run the provided test code/url and see why TestCafe freezes? Thanks.

**Comment by Farfurix** [comment]
@sijosyn 

I wanted to check if the HTTP Authentication works in your case: 
```js
fixture `Getting Started`
    .page `https://bridge.auth-gateway.net.ent-web01.dev.synacor.com/saml/module.php/bridge/test/offsite_login_dest.php`;

test
    .httpAuth({
        username: 'UserName',
        password: 'Pa$$word'
    })('My first test', async t => {
        await t.debug();
});
```
In the case of wrong credentials, I don't see any freezes (click "Resume" to continue) and the following response looks valid:
![Capture](https://user-images.githubusercontent.com/30019338/60895133-c4986480-a26c-11e9-891d-6bffb1cc9e15.PNG)
As there may be other issues (a certificate issue), I would like to research your test scenario. With the current information we are unable to replicate the "freeze" issue. Please specify steps to reproduce this problem.

**Comment by sijosyn** [comment]
Thanks for checking this. Okay i'll go ahead and close this issue for now. When our feature goes live and if I still see this issue in Prod env, i'll log another ticket with exact steps.
