### ISSUE TITLE
Unexpected redirect happened after `useRole`

### ISSUE THREAD

**Issue by pbalaban** [DevExpress/testcafe#4003]
### What is your Test Scenario?
Verify that user is able to see validation message from login form. And it is not only one test scenario, based on this validation message I go to admin panel, register new account/user/etc. So it is kind of important for our application because this check happens before every test scenario.
I can not share the URL to my production application, so I created a small app to show you the problem.

### What is the Current behavior?
When the form is submitted, XHR request is executed, server returned JSON with 422 status code, and that is the indicator that authorization is not successful. NOTE: no redirects happened in our application. 

### What is the Expected behavior?
Redirect should not happened, because I need to check that selector exists on page
 
### What is your web application and your TestCafe test code?
Your website URL (or attach your complete example): https://testcafe-testing.herokuapp.com/
 
<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
import { Selector, t, Role } from 'testcafe'

fixture('Testing redirect')

const expectedErrorMessage = Selector("div#validation-error").withText('Invalid email or password')

const userRole = Role('https://testcafe-testing.herokuapp.com', async t => {
  const usernameInput = Selector("input[type='email']")
  const passwordInput = Selector("input[type='password']")
  const signInButton = Selector("input[type='submit']")

  await t.typeText(usernameInput, 'test-user-email@gmail.com', { paste: true })
  await t.typeText(passwordInput, 'password')
  await t.click(signInButton)
}, { preserveUrl: true })


test('Verify user is able to see validation message', async t => {
  await t.useRole(userRole)
  await t.expect(expectedErrorMessage.exists).ok()
}) 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```json
{
  "browsers": "chrome",
  "concurrency": 1,
  "skipJsErrors": true,
  "videoPath": "videos",
  "videoOptions" : {
    "failedOnly": false,
    "pathPattern": "${DATE}_${TIME}/${BROWSER}/${FIXTURE}/${TEST}.mp4"
  }
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```
➜ yarn run testcafe --speed 0.5 fixtures/orders/order_management/order_details/testing.js
yarn run v1.9.2
warning package.json: No license field
$ testcafe chrome --speed 0.5 fixtures/orders/order_management/order_details/testing.js
The "browsers" option from the configuration file will be ignored.
 Running tests in:
 - Chrome 75.0.3770 / Linux 0.0.0

 Testing redirect
 ✖ Verify user is able to see validation message

   1) AssertionError: expected false to be truthy

      Browser: Chrome 75.0.3770 / Linux 0.0.0

         15 |}, { preserveUrl: true })
         16 |
         17 |
         18 |test('Verify user is able to see validation message', async t => {
         19 |  await t.useRole(userRole)
       > 20 |  await t.expect(expectedErrorMessage.exists).ok()
         21 |})
         22 |

         at ok (/home/peter/projects/testcafe/fixtures/orders/order_management/order_details/testing.js:20:47)



 1/1 failed (14s)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</details>

<details>
<summary>Screenshots:</summary>

```
![Peek 2019-07-08 21-54](https://user-images.githubusercontent.com/213735/60835205-36b86d00-a1cb-11e9-968a-890c481c33d8.gif)
```
</details>

### Steps to Reproduce:

1. Go to test website - https://testcafe-testing.herokuapp.com/
3. Enter any email and password
4. you should see validation message 'Invalid email or password'
5. redirect is not happened, server returned JSON with 422 status code
6. Enter email: 'valid-email@gmail.com' and password 'password'
7. app redirected to '/dashboard' path
 
### Your Environment details:
 
* testcafe version: 1.3.1
* node.js version: v8.16.0
* command-line arguments: testcafe chrome fixtures/orders/order_management/order_details/testing.js
* browser name and version: Chrome 75
* platform and version: Linux Mint 19 Cinnamon

**Comment by Farfurix** [comment]
@pbalaban 

Hello,

Your test scenario role works correctly. In your scenario, you don't need to use the [User Role](https://devexpress.github.io/testcafe/documentation/test-api/authentication/user-roles.html) functionality (e. g. saving cookies).
I suggest you write a separate test to login with wrong credentials:

```js
import { Selector } from 'testcafe';

fixture `Testing redirect`;

test
    .page`https://testcafe-testing.herokuapp.com`
('Login with wrong credentials', async t => {
    const usernameInput        = Selector("input[type='email']");
    const passwordInput        = Selector("input[type='password']");
    const signInButton         = Selector("input[type='submit']");
    const expectedErrorMessage = Selector("div#validation-error").withText('Invalid email or password');

    await t.typeText(usernameInput, 'test-user-email@gmail.com', {paste: true})
        .typeText(passwordInput, 'password')
        .click(signInButton)
        .expect(expectedErrorMessage.exists).ok();
});
```

**Comment by pbalaban** [comment]
It makes sense. Thank you!
