### ISSUE TITLE
Using t.debug() causes: Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by mestwanick** [DevExpress/testcafe#4005]
### What is your Test Scenario?
 Have a test that will use t.debug().

### What is the Current behavior?
 ✖ Perform a simple test

   1) Error: ENOENT: no such file or directory, open
      '/Users/XXXXX/Documents/Projects/app/Projects/app/tests/testcafe/suites/Search.ts'

      Browser: Chrome 75.0.3770 / Mac OS X 10.14.4
 
### What is the Expected behavior?
I expect t.debug() to pause the browser

```js
// Search.ts
 test.meta({})(
        'Perform test .. ',
        async (t) => {
            t.debug();
        }
    );
```

### Steps to Reproduce:
1. run testcafe suite against chrome
 
### Your Environment details:
 
* testcafe version: 1.3.0                   
* node.js version: v10.13.0                    
* command-line arguments:  testcafe ./tests/testcafe --browser "chrome"
* browser name and version: Chrome 75.0.3770
* platform and version:          Mac OS X 10.14.4

**Comment by AlexSkorkin** [comment]
There's no '--browser' command line argument: [Command Line Interface](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html).
 
To execute tests, specify the browser alias as a first argument as follows:
 
`testcafe chrome ./tests/testcafe`
 
Make sure that the path '.tests/testcafe' is valid and exists.
 
Also, to call a debug action, use the "await" keyword before it: 
 
```
async (t) => {
  await t.debug();
}
```
