### ISSUE TITLE
TestCafe version of browser.getCookies('auth-token')

### ISSUE THREAD

**Issue by blanche-pinto** [DevExpress/testcafe#4017]
### Are you requesting a feature or reporting a bug?
Bug

### What is your Test Scenario?
Get cookie of the current page and check that it is null.

### What is the Current behavior?
Returns a guest_id.

### What is the Expected behavior?
Returns a null value.

### How would you reproduce the current behavior (if this is a bug)?

I need to get the cookie for the current page. In WebDriverIO, there is a function called browser.getCookie('auth-token') where auth-token is the key of the cookie I'm looking for.

Your complete test code (or attach your test files)

```js
export default class LogoutPage {
  constructor({ testController }) {
    this._testController = testController;
    this.getCookie = ClientFunction(() => {
      return document.cookie;
    });
  }
```

```js
test('Verify user can follow/unfollow', testController => {
  const getCookieFromClient = logoutPage.getCookie.with({ boundTestRun: testController });

  return (
      testController.expect(getCookieFromClient()).eql(null))
  );
});
```
### Your Environment details:
 
* testcafe version:                   1.2.1
* node.js version:                    v10.15.3
* command-line arguments:  testcafe chrome -d --skip-js-errors
* browser name and version: Chrome
* platform and version:          macOS 10.14

**Comment by blanche-pinto** [comment]
Note: I am using Promises to run my tests.

**Comment by aleks-pro** [comment]
Hello @blanche-pinto ,

If you want to get a value by key from coockies, you can create the following method in the `LogoutPage` class:
```JS
...
this.getCookieByKey = ClientFunction(key => {
    const name             = key + "=";
    const cookiesArray = decodeURIComponent(document.cookie).split(';');

    for (let i = 0; i < cookiesArray.length; i++) {
        let item = cookiesArray[i];

        while (item.charAt(0) == ' ')
            item = item.substring(1);

        if (item.indexOf(name) == 0)
            return item.substring(name.length, item.length);
    }

    return null;
});
```
Please use it in your test like this:
```JS
test('Verify user can follow/unfollow', testController => {
  const getCookieFromClient = logoutPage.getCookieByKey.with({ boundTestRun: testController });

  return (
      testController.expect(getCookieFromClient('auth-token')).eql(null))
  );
});
```
