### ISSUE TITLE
Interactive browser (CLI)

### ISSUE THREAD

**Issue by pavelloz** [DevExpress/testcafe#4025]
This is not a technical question, more of a RFC.

I've stumbled upon https://github.com/getgauge/taiko

The [main gif](https://user-images.githubusercontent.com/44019225/60337143-da31a280-99bf-11e9-80a4-57917d81e0b6.gif) made a huge impression on me so I decided to ask:

Is it very hard to do with current TC architecture to do something similar?
Meaning: live, nonheadless, interactive browser that can be manipulated with TC API in a CLI?

I can see that in taiko case the API is much simpler than TC, so learning API just because of this feature is much faster, but IMO even in TC it would speed up API adoption and test writing a lot (ie. selectors development, debugging - think of it as devtools console).

**Comment by arubtsov** [comment]
Hello @pavelloz,

We plan to implement this feature as a part of https://github.com/DevExpress/testcafe/issues/3244. Feel free to contact us if it doesn't meet your needs.

In the meantime, take a look at our [TestCafe Studio](https://www.devexpress.com/products/testcafestudio/) IDE. It ships with [Visual Test Recorder](https://docs.devexpress.com/TestCafeStudio/400165/guides/record-tests), which allows creating tests without writing code.
