### ISSUE TITLE
Integrating the Microsoft Office Outlook with TestCafe

### ISSUE THREAD

**Issue by dipeshDM1** [DevExpress/testcafe#4026]
Hi Team,
THis Dipesh More from Sterling Talent Solutions. We are doing a proto-type with testcafe tool and in process of exploring the various features for the same. 

### What is your Test Scenario?
While doing so,, we have come across a scenario where we need integration with Microsoft Outlook

### What are you suggesting?
We want to do certain operations like (Clicking on Button, Links ) came as part of an email.

### What alternatives have you considered?
We did not find any information regarding this. Requesting you to provide any ways where we could achive these scenarios..

### Additional context
Example : Suppose, after performing any operation on my UI application, I am recieving xyz link through email and to test it further, I have to click on link (which came in email) to automate remaining flow. We need to achive this through Test Cafe.

**Comment by arubtsov** [comment]
Hi Dipesh,

Thank you for your interest in our testing tool. TestCafe is designed to interact only with the browser. However, you can make it interact with your mail server via the web interface. Feel free to contact us if this approach doesn't cover your scenario or you face any difficulties while implementing it. We will be happy to help.
