### ISSUE TITLE
No tests to run. Either the test files contain no tests or the filter function is too restrictive.

### ISSUE THREAD

**Issue by shahmeet999** [DevExpress/testcafe#4028]
> Here i want to perform the automation testing with testcafe , but i got this error while i am testing with this command

`testcafe chrome testc.ts`

i am using this command for test the my testc.ts in my angular application and i was installed the testcafe globally on my project.

Here i can also attach the screenshot of my code.

**i have the latest angular cli,node and npm.**

give me solution for this problem.

![image](https://user-images.githubusercontent.com/20349696/61201082-f8f2a180-a700-11e9-844b-f02180e6423a.png)

**Comment by AlexSkorkin** [comment]
Hi,

Let's continue discussing this issue in the context of your StackOverflow thread:

[No tests to run. Either the test files contain no tests or the filter function is too restrictive](https://stackoverflow.com/questions/57035057/no-tests-to-run-either-the-test-files-contain-no-tests-or-the-filter-function-i)

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafeontributing)).

**Comment by shahmeet999** [comment]
ok
