### ISSUE TITLE
Indicate that the cdpPort option can't be used in concurrency mode

### ISSUE THREAD

**Issue by HugoDel** [DevExpress/testcafe#4029]
### What is your Test Scenario?
Just testing the google search webpage. I make the test failed to see If the screenshot on fail works.
 
### What is the Current behaviour?
3 screenshots are in the screenshot folder for the 2nd test (3 retires x 1 test). No screenshot is taken for the 1st and 3rd, plus I've got the error below. BUT I can take a screenshot if there is only ONE test. It only happens if there is more than one test. 

```
 Warnings:
     Was unable to take a screenshot due to an error.

    TypeError: Cannot read property 'Page' of undefined
        at Object.getScreenshotData (C:\Users\hdelannoy\Documents\Code\testcafe-manage\node_modules\testcafe\src\browser\provider\built-in\dedicated\chrome\cdp.js:48:41)
        at BrowserProviderPluginHost.takeScreenshot (C:\Users\hdelannoy\Documents\Code\testcafe-manage\node_modules\testcafe\src\browser\provider\built-in\dedicated\base.js:53:52)
        at BrowserProvider.takeScreenshot (C:\Users\hdelannoy\Documents\Code\testcafe-manage\node_modules\testcafe\src\browser\provider\index.js:303:27)
Allure reporter closed...
```
 
### What is the Expected behaviour?
I should have 9 screenshots (3 retries x 3 tests) in the screenshot directory and no error on the console.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example): http://google.com/

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
fixture('featureName')

test("Test screenshoot", async t => {
    await t.navigateTo('http://google.com/')
    await t.expect(1%2 === 2).ok()
}).only

test("Test screenshoot 2", async t => {
    await t.navigateTo('http://google.com/')
    await t.expect(1%2 === 2).ok()
}).only

test("Test screenshoot 3", async t => {
    await t.navigateTo('http://google.com/')
    await t.expect(1%2 === 2).ok()
}).only
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
const createTestCafe = require("testcafe");

let testcafe = null;



createTestCafe("localhost", 1337, 1338)
    .then(tc => {
        testcafe = tc;
        const runner = testcafe.createRunner();


        return (
            runner
            .src("./tests/**/*.ts")
            .browsers(['chrome:headless:cdpPort=9222 --no-sandbox'])
            .concurrency(4)
            .reporter([
                'teamcity',
                {
                    name: 'allure',
                    output: '/allure/allure-results'
                }
            ])
            .screenshots(
                "./report/screenshots/",
                true,
                "${USERAGENT}_${FIXTURE}_${TEST}_${QUARANTINE_ATTEMPT}.png"
            )
            .run({
                skipJsErrors: true,
                quarantineMode: true,
                selectorTimeout: 10000,
                assertionTimeout: 10000
            })
        );
    })
    .then(failedCount => {
        console.log("Tests failed: " + failedCount);
        testcafe.close();
        process.exit(failedCount ? 1 : 0);
    });
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Your Environment details:
 
* testcafe version:                   1.3.2
* node.js version:                    v10.15.3
* command-line arguments:  node conf/runner.js
* browser name and version: Chrome 75.0.3770.100  (64 bits)
* platform and version:          W10
* other:                                   "testcafe-reporter-teamcity": "^1.0.10",
                                               "testcafe-reporter-allure": "^1.0.5",

**Comment by AlexKamaev** [comment]
It looks like you enable two conflicting options: `concurrency` and `cdpPort`. You cannot run two browsers that use the same cdp port at the same time.
Please check if your test works without defining the `cdpPort` option (in this case the `cdpPort` option will be assigned automatically).
Meanwhile, I think that we need to improve our documentation or throw an error message to make the issue clear

**Comment by HugoDel** [comment]
Ok, it seems to work! I'm impatient to be able to use concurrency and CdpPort, thanks for your help.

**Comment by AndreyBelym** [comment]
If you don't mind, could you please clarify why do you want to explicitly configure the CDP port in concurrency mode?

**Comment by HugoDel** [comment]
Yes of course! In some test, we need to download files to check their content. Since we have a lot of tests, we use concurrency mode to speed up.

**Comment by miherlosev** [comment]
We decided to raise an error if the same `cdpPort` was specified for several browser instances in `concurrency` mode.

**Comment by HugoDel** [comment]
OK! It's technically possible to use concurrency and cdpPort to communicate with browsers? If yes, do you will plan it in your roadmap?

**Comment by AndreyBelym** [comment]
Could you please clarify why you have to manually configure CDP ports? Please note, that in concurrency mode each browser needs a dedicated port. It means that if you want to run 4 browsers concurrently, you will have to handle 4 different ports. I think this is quite inconvenient, so that's why I am so curious about your use case.

**Comment by HugoDel** [comment]
This is exactly the same problem as in #3127 
I want to download files and use concurrency to speed up tests. I know that it's complicated to handle both but If we can set manually each port for each browser in concurrency mode, I think it will be possible to resolve the problem.

**Comment by AlexKamaev** [comment]
I've modified the example from #3127 a little. Now it will allow you to use the concurrency option. Please refer to https://gist.github.com/AlexKamaev/8c1eb8a5fb638fa366b44447f6d7c5a4
This example is using an internal TestCafe API. It works stable, however, it can change in the future

**Comment by HugoDel** [comment]
Hi, sorry for the response delay but your solution doesn't solve my problem :/ 
I'm still getting `TypeError: Cannot read property 'Page' of undefined`

**Comment by AndreyBelym** [comment]
The problem with file downloading in Headless Chrome is fixed in `testcafe@1.4.0-rc.2`. Please, try to remove all workarounds and run your tests with this version.

**Comment by HugoDel** [comment]
Well, I'm still having the same error with the last version. I remove all workaround, update to `1.4.0-rc.2`

**Comment by AndreyBelym** [comment]
Specifying `cdpPort` is a part of the workaround. Have you removed it from TestCafe parameters?

**Comment by HugoDel** [comment]
Ok! You right, I forget it and it works perfectly. Thank you for supporting this feature!
