### ISSUE TITLE
'click()' method uses different visibility test from '.visible' property?

### ISSUE THREAD

**Issue by chrisveness** [DevExpress/testcafe#4030]
### Test Scenario
I have a navigation menu which dynamically pops out from the left of the page.

On the menu elements, the `.visible` property passes `ok()`, but the `click` method on the same element complains "the element that matches the specified selector is not visible".

The element is visible (to me!), but the `left` of its container element is set to a negative value, which may be confusing the visibility test?
 
### Web application

Website URL: https://www.movable-type.co.uk/test/testcafe-menu/test.html

Test result:

![image](https://user-images.githubusercontent.com/1066395/61226460-5e9f5780-a71a-11e9-9ab5-810e4756b253.png)

<details>
<summary>Complete test files</summary>

test.html:
~~~~
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>TestCafé Menu Test</title>
    <style>
        .left-nav {
            position: absolute;
            left: -280px;
        }
        .menu-left {
            background: #eeeeee;
            cursor: pointer;
            position: relative;
            width: 350px;
            text-align: right;
            left: 0;
        }
        .menu-item {
            padding: 15px 20px;
        }
        .menu-item > span {
            display: inline-block;
            margin-right: 15px;
            width: 160px;
        }
        .menu-item > i {
            display: inline-block;
            font-size: 3rem;
            width: 35px;
            text-align: center;
        }
        .bump {
            left: 125px;
            transition: left 0.3s;
        }
    </style>
    <script>
        document.addEventListener('DOMContentLoaded', async function() {
            document.querySelectorAll('.menu-left').forEach(mi => mi.onmouseenter = function() {
                this.classList.add('bump');
            });
            document.querySelectorAll('.menu-left').forEach(mi => mi.onmouseleave = function() {
                this.classList.remove('bump');
            });
            document.querySelectorAll('.menu-left').forEach(mi => mi.onclick = function() {
                console.log('click', this)
            });
        });
    </script>
</head>
<body>

<h1>TestCafé Menu Test</h1>

<div class="left-nav">
    <div id="menu1" class="menu-left menu-1">
        <div class="menu-item">
            <span>My 1st</span> <i>1</i>
        </div>
    </div>
    <div id="menu2" class="menu-left menu-2">
        <div class="menu-item">
            <span>My 2nd</span> <i>2</i>
        </div>
    </div>
</div>

</body>
</html>
~~~~

test.js:
~~~~js
import { Selector } from 'testcafe';

fixture('TestCafé menu bump test')
    .page('https://www.movable-type.co.uk/test/testcafe-menu/test.html');

test('test', async t => {
    await t
        .expect(Selector("#menu1").visible).ok() // <- passes
        .click(Selector('#menu1'));              // <- fails with "not visible"
});
~~~~
</details>

<details>
<summary>Environment details</summary>

* testcafe version:                   1.3.2
* node.js version:                    v12.4.0
* command-line arguments:  testcafe chrome test.js
* browser name and version: Chrome 77.0.3833
* platform and version:         Linux Mint 18 / Ubuntu 16.04

**Comment by LavrovArtem** [comment]
Thank you for the simple example. I've reproduced this behavior. We need some time to research this issue and will inform you about our progress as soon as we have any.

**Comment by chrisveness** [comment]
I've simplified the example: it has nothing to do with the container element having a negative left.

I've removed the `left` on the `left-nav` container, and made `.menu-left` (#menu1 / #menu2) `width: 350px`, `left: -290px`, with `.menu-left:hover` setting `left: -155px`.

The test behaviour is still the same, so it must just be the fact that the target element is only partially visible (with -ve `left`)?

<details>
<summary>test.html</summary>

~~~~
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>TestCafé Menu Test</title>
    <style>
        .left-nav {
            position: absolute;
        }
        .menu-left {
            background: #eeeeee;
            cursor: pointer;
            position: relative;
            width: 350px;
            text-align: right;
            left: -290px;
        }
        .menu-item {
            padding: 15px 20px;
        }
        .menu-item > span {
            display: inline-block;
            margin-right: 15px;
            width: 160px;
        }
        .menu-item > i {
            display: inline-block;
            font-size: 3rem;
            width: 35px;
        }
        .menu-left:hover {
            left: -155px;
            transition: left 0.3s;
        }
    </style>
    <script>
        document.addEventListener('DOMContentLoaded', async function() {
            document.querySelectorAll('.menu-left').forEach(mi => mi.onclick = function() {
                console.log('click', this)
            });
        });
    </script>
</head>
<body>

<h1>TestCafé Menu Test</h1>

<div class="left-nav">
    <div id="menu1" class="menu-left menu-1">
        <div class="menu-item">
            <span>My 1st</span> <i>1</i>
        </div>
    </div>
    <div id="menu2" class="menu-left menu-2">
        <div class="menu-item">
            <span>My 2nd</span> <i>2</i>
        </div>
    </div>
</div>

</body>
</html>
~~~~

</details>

**Comment by AlexKamaev** [comment]
@chrisveness 
Thank you for your cooperation. You are right, the `Selector(...).visible` command just checks that the element exists in the document and does not contain the `display: none` or the `visibility: hidden` rules. The `click` method is more complex. It tries to calculate the middle of the element (by default) to click on it. The middle of the element is hidden, and this is confusing the test.
While the issue exists, I recommend using the following workaround:
```JS
await t.click(Selector('#menu1'), { offsetX: -5 });
```
Here I am using the `offsetX` option to help the test to click an element on the visible part.

**Comment by chrisveness** [comment]
Thank you! That's sufficient work-around to enable me to progress.

Would it be difficult to make the visibility test that any part of the element is visible? The centre seems somewhat arbitrary... Anyway, I'll leave that with you, I can now move on, thx.

**Comment by AlexKamaev** [comment]
You can check if the element is fully visible by using your own custom code. To create it, use TestCafe's [ClientFunctions](https://devexpress.github.io/testcafe/documentation/test-api/obtaining-data-from-the-client/) mechanism.
You can implement your own `ClientFunction` and add your custom logic to it. Use the [How to test if an element is in the viewport with vanilla JavaScript](https://gomakethings.com/how-to-test-if-an-element-is-in-the-viewport-with-vanilla-javascript/) article as a basis.

**Comment by chrisveness** [comment]
Thanks for that – for the moment, the `offsetX` trick is sufficient, but I'll bear that in mind.

**Comment by FredMottey-expel** [comment]
Running into the same issue I believe.

The element is visible to me, and in the chrome dev console, when running `$('elementSelector).checkVisibility();` the response is true - but when trying to do a click event on the element in testcafe, I get the following error: `{elementSelector} is invisible. The value of its 'visibility' property is 'hidden'.`

**Comment by Bayheck** [comment]
Please use this [template](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&template=bug_report.yaml) to create a separate ticket and share a [Minimal Working Example](https://testcafe.io/documentation/402636/faq/general-info?search#how-to-create-a-minimal-working-example-when-you-submit-an-issue) in that ticket so that the TestCafe team can research the issue and help you.
