### ISSUE TITLE
Firefox 68.0 headless is not working inside docker containers 

### ISSUE THREAD

**Issue by cetra3** [DevExpress/testcafe#4031]
### What is your Test Scenario?

Running testcafe in a docker image, looks like firefox headless is broken for some reason.  I reckon it's a profile related issue.

Normal firefox with `xvfb` works OK (i.e, not headless).  `dbus-daemon` is also running in the background and makes no difference.

### What is the Current behavior?

Testcafe doesn't finish, and complains the browser is unresponsive:

```
ERROR The Firefox 68.0.0 / Ubuntu 0.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.
``` 

If you exec into the docker and run top you can see firefox taking up to 4gb RAM and using a lot of CPU.

### What is the Expected behavior?

Firefox runs fine in headless mode.

### What is your web application and your TestCafe test code?

Using the standard tutorial page.

<details>
<summary>Test Code:</summary>

 
```js
import { Selector } from 'testcafe';

fixture `Getting Started`
    .page `http://devexpress.github.io/testcafe/example`;

test('My first test', async t => {
    // Test code
});
```
</details>

<details>
<summary>Docker File:</summary>

 
```dockerfile
FROM ubuntu:18.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -y \
        curl \
        sudo \
        software-properties-common

RUN add-apt-repository -y ppa:ubuntu-mozilla-security/ppa
RUN apt-get update && apt-get install -y firefox

RUN curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
RUN apt-get install -y nodejs

RUN npm install -g testcafe

```
</details>

### Steps to Reproduce:

1. Run docker build with the dockerfile: `docker build -T 
2. Run docker run with the test file mounted somewhere or just cut & paste it.
3. Inside the docker execute `testcafe firefox:headless test.js`
4. See the error:

```
ERROR The Firefox 68.0.0 / Ubuntu 0.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.
``` 

### Your Environment details:
 
* testcafe version:                   `1.3.2`
* node.js version:                   `v10.16.0`
* command-line arguments:   `firefox:headless test.js`
* browser name and version: firefox headless 68.0
* platform and version:          Ubuntu 18.04 docker

**Comment by miherlosev** [comment]
Hi @cetra3 
 
I've updated the Firefox browser version up to 68 in our [Dockerfile](https://github.com/DevExpress/testcafe/blob/master/docker/Dockerfile) and build the new docker image.
After that, I run a simple test using the created docker image.
All works as expected.
![image](https://user-images.githubusercontent.com/4133518/61376066-0a76ad80-a8a9-11e9-97a4-5f4338545a47.png)
 
This fact means the cause of the problem is not Firefox 68. Most likely the cause of the problem is in Docker file settings. We need additional time to investigate the problem more deeply.

**Comment by cetra3** [comment]
@miherlosev 

Yeah I'm not sure where the issue is, but I see there is a [related closed issue](https://github.com/DevExpress/testcafe/issues/3933) that has a similar problem.

You should be able to replicate with the included Dockerfile which uses the ubuntu 18.04 image.

**Comment by aleks-pro** [comment]
> You should be able to replicate with the included Dockerfile which uses the ubuntu 18.04 image.

I hope so, but we need additional time to do this. We will update this thread as soon as we have any results.

**Comment by AndreyBelym** [comment]
Thank you for your patience. I tried to reproduce the issue using an image based on the provided Dockerfile and [our basic example](), but it didn't appear with my configuration. The huge RAM consumption indicates a problem with the browser. I will try to prepare a debug build that will output browser logs to the terminal.

**Comment by AndreyBelym** [comment]
Please use this command in your Dockerfile to install the debug build:
```
RUN npm i -g https://git.io/fj7CF
```

The debug build will output browser logs to your CI build log. Please collect and share them with me.

**Comment by cetra3** [comment]
I can't see any output when I run:

```
testcafe firefox:headless test.js
```

The output is as follows:

```
ERROR The Firefox 68.0.0 / Ubuntu 0.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.

Type "testcafe -h" for help.
```

To throw a spanner in the works, this appears to work fine on newer versions of Docker, but I'm not too sure why this matters.

The version of Docker I am running where I can replicate the issue is: `Docker version 17.05.0-ce, build 89658be` on an Ubuntu 14.04 server.  

The newer version is running `Docker version 19.03.1, build 74b1e89` on an Ubuntu 18.04 server.

**Comment by AndreyBelym** [comment]
Absence of browser logs indicates that some problem in the environment can cause browser failures. Since you can't reproduce this problem with newer OS and Docker version, I guess that the problem was caused either by the OS or Docker.

**Comment by cetra3** [comment]
Yep, I agree.  Hopefully this issue will assist if other people run into it!
