### ISSUE TITLE
Press and Hold key with testcafe

### ISSUE THREAD

**Issue by subashdbc** [DevExpress/testcafe#4034]
Hi,

Is there any way to perform press and hold the key with testcafe?
We have a scenario where a list of items displayed, from where the items should be selected by pressing and holding  `ctrl` key and do the drag and drop.

How can we achieve this scenario? Any suggestions or solutions?

Thanks in advance!

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. I guess in your case you can use `t.dragToElement` and `t.dragToOffset` actions and specify the `{ modifiers: { ctrl: true } }` option. Take a look at [Drag Element](https://devexpress.github.io/testcafe/documentation/test-api/actions/drag-element.html) and [Mouse Actions Options](https://devexpress.github.io/testcafe/documentation/test-api/actions/action-options.html#mouse-action-options) topics in our docs. Also, we already have a similar suggestion in our repository: https://github.com/DevExpress/testcafe/issues/1839, so I close this issue as a duplicate.
