### ISSUE TITLE
Assertion on textContent of a paragraph only works if it's just one word

### ISSUE THREAD

**Issue by viktorss89** [DevExpress/testcafe#4035]
### What is your Test Scenario?
I want to assert the textContent of a paragraph in a page. 
 
### What is the Current behavior?
If the textContent of the paragraph is just one word (i.e: "testtesttest"), it works fine.
The moment that there are two or more words (i.e: "This is a test, rest in peace"), it gives me the following error:
"   1) AssertionError: expected 'This is a test, rest in peace' to include 'This is a test, rest in peace' "

### What is the Expected behavior?
Assertion is correct.
 
### What is your web application and your TestCafe test code?
It's a private application, I cannot provide a real link, but this is how the paragraph looks like:

`<p class="ATheCampaign__SeoText"><p>This is a test, rest in peace</p></p>
` 

### Your Environment details:
 
* testcafe version: 1.3.0
* node.js version: 12.3.1
* browser name and version: Chrome 75
* platform and version:  macOS10.14.5

**Comment by LavrovArtem** [comment]
The issue you described looks similar to the problem we already discussed in this StackOverflow thread: 
[Assertion always return err (expected 'a' to deeply equal 'a')](https://stackoverflow.com/questions/52877344/assertion-always-return-err-expected-a-to-deeply-equal-a/52893981)
Please try the recommendations from that thread and see how it works.
