### ISSUE TITLE
(node:24684) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED and [DEP0005] DeprecationWarning: Buffer() is deprecated

### ISSUE THREAD

**Issue by jiteshsojitra** [DevExpress/testcafe#4036]
1. (node:24684) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

2. (node:509) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

### What is your Test Scenario?
When i launch TestCafe, it throws warning for NODE_TLS_REJECT_UNAUTHORIZED. Is there any solution to stop showing this warning when test starts?
 
### What is the Expected behavior?
No warning!

### Your Environment details:
 
* testcafe version: 1.3.2 and since 1.1.0 facing this error.
* node.js version:  v11.15.

![image](https://user-images.githubusercontent.com/21263826/61324553-53d6e680-a830-11e9-92d7-8a667a1f42fb.png)

![image](https://user-images.githubusercontent.com/21263826/61324652-95679180-a830-11e9-9177-b26fbe9f7623.png)

**Comment by miherlosev** [comment]
Hi @jiteshsojitra 

> (node:24684) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

We are aware of this problem - https://github.com/DevExpress/testcafe-hammerhead/issues/2051. Track it to be informed about our progress.

> (node:509) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

I didn't find the `Buffer()` calls in our code. Try to search for the `Buffer` calls in your project and installed Node.js modules. 
If you find the problematic instructions in modules connected with TestCafe (`testcafe`, `testcafe-hammerhead`, `testcafe-browser-tools` and etc.), please inform us.
