### ISSUE TITLE
[docs] ClientFunction example: return "new Promise" instead of "Promise"

### ISSUE THREAD

**Issue by Farfurix** [DevExpress/testcafe#4039]
https://devexpress.github.io/testcafe/documentation/test-api/obtaining-data-from-the-client/#running-asynchronous-client-code

```diff
- return Promise(resolve => {
+ return new Promise(resolve => {
```
"`return Promise`" error:
```
An error occurred in ClientFunction code:

      TypeError: Failed to construct 'Promise': Please use the 'new' operator, this object constructor cannot be
      called as a function.
```

**Comment by VasilyStrelyaev** [comment]
Commited to `master` directly:
https://github.com/DevExpress/testcafe/commit/a4f6a4ac3627ebeb29b344ed3a1793627dd87909
