### ISSUE TITLE
No screenshot file created when test fails

### ISSUE THREAD

**Issue by scnolton** [DevExpress/testcafe#4041]
This may be related to https://github.com/DevExpress/testcafe/issues/3552 but wasn't sure

### What is your Test Scenario?
I am running test cafe with cucumber. I have set up one of my tests to error out after logging in. using the runner API I have set `.screenshots('artifacts/screenshots/testcafe', true)` and I am trying to make sure the screen shot appears after the test fails
 
### What is the Current behavior?
When I call the `takeScreenshot` function explicitly within my test code the screenshot is taken and saved to the correct location. If I don't explicitly call `takeScreenshot` and just let the test fail, then there is no screen shot taken.
 
### What is the Expected behavior?
When the test fails it should take a screen shot the same way it does when I call the `takeScreenshot` function directly.

When my cucumber step fails, I get this message in my output log: 
```
Then I should be on the such and such page. # src/step_definitions/suchAndSuchSteps.ts:9
       Error: { code: 'E52',
         isTestCafeError: true,
         callsite:
          CallsiteRecord {
......
```

I have tried this with the latest testcafe version as well as 0.22.0 and 1.0.1, and it never seems to work for me. I suspect that it has something to do with running testcafe through cucumber but not sure.

**Comment by AlexKamaev** [comment]
May be your issue is really related to #3552, but it's quite difficult to say. We didn't have any trouble messages when screenshots successfully work using the API, but do not work with the `screenshotOnFail` option. We would really appreciate it if you share your project and test code with us to demonstrate the issue. Please also specify your browser and OS.
