### ISSUE TITLE
Typed text is reversed in a content editable iframe in IE

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#4046]
### What is your Test Scenario?
Type some text into a content editable iframe.

### What is the Current behavior?
The text order is revered.
 
### What is the Expected behavior?
The text order should be correct.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):
http://[HOST]/RegressionTestSite//ASPxHtmlEditor/UndoRedo.aspx

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from 'testcafe';

fixture `bugs_ie`
  .page(`http://[HOST]/RegressionTestSite//ASPxHtmlEditor/UndoRedo.aspx`);
const getTabs = (container:Selector) => {
    return container.find('.dxtc-tab span.dx-vam');
}
test('bug', async t => {
  const htmlEditor = Selector('[id$=ASPxHtmlEditor1]');
  const designIframe = htmlEditor.find('[id$=_DesignIFrame]');
  const htmlTab = getTabs(htmlEditor).withText(new RegExp(/HTML/, "i"));
  const designIframeBody = Selector('body');
  await t
    .switchToIframe(designIframe)
    .debug()
    .typeText('body', 'T')
    .typeText('body', 'e')
    .typeText('body', 'x')
    .typeText('body', 't');
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by miherlosev** [comment]
Page for reproduce: http://sarmin-nb-w10/201/RegressionTestsSite/ASPxHtmlEditor/UndoRedo.aspx
