### ISSUE TITLE
TestCafe throws an IndexSizeError after executing pressKey('enter') in a content editable iframe in IE

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#4047]
### What is your Test Scenario?
Press `<Enter>` in a content editable iframe in IE.
 
### What is the Current behavior?
TestCafe can't execute the action and throws `IndexSizeError:  No stack trace available` in the browser.
 
### What is the Expected behavior?
A new line is created in the iframe's body.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):
http://[HOST]/RegressionTestSite//ASPxHtmlEditor/UndoRedo.aspx

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 fixture `bugs_ie`
  .page(`http://[HOST]/RegressionTestSite//ASPxHtmlEditor/UndoRedo.aspx`);
const getTabs = (container:Selector) => {
    return container.find('.dxtc-tab span.dx-vam');
}
test('bug', async t => {
  const htmlEditor = Selector('[id$=ASPxHtmlEditor1]');
  const designIframe = htmlEditor.find('[id$=_DesignIFrame]');
  const htmlTab = getTabs(htmlEditor).withText(new RegExp(/HTML/, "i"));
  const designIframeBody = Selector('body');
  await t
    .switchToIframe(designIframe)
    .click('body')
    .debug()
    .pressKey('enter')
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by miherlosev** [comment]
Contact to Anton Sarmin (DevExpress) to get test site.
