### ISSUE TITLE
t.typeText() not triggering onChange function in textbox

### ISSUE THREAD

**Issue by andym0457** [DevExpress/testcafe#4050]
### What is your Test Scenario?

I have a text field and a disabled button inside the shadow dom. Once text is typed into the text field the button should become enabled 
 
### What is the Current behavior?

.typeText() types the text correctly into the text field and can test that this is correct but the onChange event in the text field to enable the button is never called
 
### What is the Expected behavior?

once the .typeText() starts typing the onChange event in the text field should be called which will change the button from enabled to disabled. 
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js

const findInApp = Selector((appName, element) => {
    const all = document.body.querySelector('container').shadowRoot.querySelector(appName).shadowRoot;
    const Component = all.querySelector(element);
    if (Component.nodeName === 'TEXT-FIELD') {
        const input = Component.shadowRoot.querySelector('input');
        return input;
    }
    console.log(Component);
    return Component;
});

const button1 = findInApp('app-two', 'button#b1');
    const textField = findInApp('app-two', 'text-field.textField');
    await t.debug()
            .click(textField)
            .expect(button1.hasAttribute('disabled')).ok()
            .typeText(textField, 'This works fine')
            .expect(textField.value).eql('This hardly works', 'input is empty')
            .expect(button1.hasAttribute('disabled')).notOk()
            .click(button1)
            .wait(1000);
});
 


```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version: 1.3.3  
* node.js version: 11.6.0   
* command-line arguments: testcafe chrome ./testcafe.js 
* browser name and version: chrome 75
* platform and version: Windows 10

**Comment by arubtsov** [comment]
Hello @andym0457,
 
The `сhange` event fires for `<input type="text">` only after the input element loses focus ([documentation](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event)). So if you change the mutual order of the assertion and the click as follows:
```
.click(button1)
.expect(button1.hasAttribute('disabled')).notOk()
```
the test should pass.
