### ISSUE TITLE
Request Logger not working for <a download> type of requests in Chromium

### ISSUE THREAD

**Issue by Lukas-Kullmann** [DevExpress/testcafe#4056]
### What is your Test Scenario?

I want to log requests that are done when clicking a `<a download>` type of link. And I use Chromium instead of Chrome.

I know that Chromium is not an officially supported browser, but to me it's very weird that this works in Chrome, but not in Chromium of the same version.
 
### What is the Current behavior?

Requests are __not__ logged if the `download` attribute is set.
If the `download` attribute is missing however, the request is logged.

My current workaround is to not provide a `download` attribute, but use a `target="_blank"`, but that's kinda ugly.
 
### What is the Expected behavior?

Requests for `<a download>` links are logged.
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

```html
<!doctype html>
<html>
    <head>
        <title>Test</title>
    </head>
    <body>
        <a download="testcafe.zip" href="https://github.com/DevExpress/testcafe/archive/v1.3.3.zip">Click me!</a>
        <a target="_blank" href="https://github.com/DevExpress/testcafe/archive/v1.3.3.zip">Click me!</a>
    </body>
</html>
```
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import {RequestLogger} from 'testcafe'

const logger = RequestLogger();

fixture('Links').page('http://localhost:4000/')

test('<a download>', async (t) => {
  await t.addRequestHooks(logger)

  await t.click('a[download]')

  await t
    .expect(logger.contains((request) => request.request.url === 'https://github.com/DevExpress/testcafe/archive/v1.3.3.zip'))
    .ok('Request was not logged!')
})

test('<a target="_blank">', async (t) => {
  await t.addRequestHooks(logger)

  await t.click('a[target]')

  await t
    .expect(logger.contains((request) => request.request.url === 'https://github.com/DevExpress/testcafe/archive/v1.3.3.zip'))
    .ok('Requst was not logged!')
})
```
</details>

<details>
<summary>Your complete test report:</summary>

```
npx testcafe chromium:headless index.ts
 Running tests in:
 - HeadlessChrome 75.0.3770 / Ubuntu 0.0.0

 Links
 ✖ <a download>

   1) AssertionError: Request was not logged!: expected false to be truthy

      Browser: HeadlessChrome 75.0.3770 / Ubuntu 0.0.0

          9 |
         10 |  await t.click('a[download]')
         11 |
         12 |  await t
         13 |    .expect(logger.contains((request) => request.request.url === 'https://github.com/DevExpress/testcafe/archive/v1.3.3.zip'))
       > 14 |    .ok('Request was not logged!')
         15 |})
         16 |
         17 |test('<a target="_blank">', async (t) => {
         18 |  await t.addRequestHooks(logger)
         19 |

         at Object.<anonymous> (index.ts:14:6)
         at fulfilled (index.ts:4:58)


 ✓ <a target="_blank">

```
</details>

### Steps to Reproduce:

1. Provide the page posted above at http://localhost:4000/ (e.g. via `http-server`)
2. Run tests
 
### Your Environment details:
 
* testcafe version: 1.3.3
* node.js version:  10.16.0
* command-line arguments:  `npx testcafe chromium:headless index.ts`
* browser name and version: Chormium 75.0.3770
* platform and version: Ubuntu 
* other: Works in Firefox 68.0.0 and Chrome 75.0.3770, headless and non-headless does not make a difference. Works in chrome headless, too.

**Comment by Dmitry-Ostashev** [comment]
Hello!
 
Thank you for your detailed report. I have reproduced this issue. We will research it and inform you as soon as we have any results.

**Comment by miherlosev** [comment]
Hi @Lukas-Kullmann 

I cannot reproduce the problem with the latest TestCafe (`1.4.2`) and Chromium versions (`78.0.3898.0`).
Try to run your tests with the same environment and let us know about results.
![image](https://user-images.githubusercontent.com/4133518/64006661-717bb900-cb1b-11e9-90ad-215162730d55.png)
