### ISSUE TITLE
'retryTestPages' option initiates two request for the tested page

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#4058]
Unpack an [example.zip](https://github.com/DevExpress/testcafe/files/3421746/example.zip) and run `node run.js` command in your terminal.

The executed test failed. If you set `retryTestPage` option to `false` value, test passed.

testcafe: `1.3.3`.

**Comment by AndreyBelym** [comment]
It's how this feature works for pages that can't be cached:

1. The first request is sent by TestCafe driver which tries to load pages into the browser's cache. Actually, the driver will retry sending requests until some of them succeeds. 
 
2. The second request is sent by the browser that wants to load a page. If the page is in the cache, the browser loads it from the cache and no additional request is sent. If the page is not configured to be stored in the browser's cache, the browser will send an additional request.
