### ISSUE TITLE
Add builtin support for shadow root

### ISSUE THREAD

**Issue by HugoDel** [DevExpress/testcafe#4059]
### What is your Test Scenario?

I'm running my tests on pages that use Web Component and Shadow DOM. It's a pain to use shadow root because every time, I need to do with a custom selector: `Selector( => document.querySelector('#theShadowRootID').shadowroot.querySelector('#targetElement'))` 

It could be more tricky if there is multiple Shadow root inside a shadow root.

### What are you suggesting?

Well, I don't really know if it's possible but If we can have the same way of getting an element in the shadow root as a regular Selector, it will be great! like: `Selector('#myTargetElementInTheShadowRoot')`

### What alternatives have you considered?

For now, I'm using the same painful syntax as upper. I create a generic method that reduces the verbosity of the selector.

**Comment by helen-dikareva** [comment]
Yes, you're correct, currently this is the only possible workaround for using shadow DOM elements' selectors. You can also use [`dependencies`](https://github.com/DevExpress/testcafe/pull/3855/files#diff-9cf5819f164b1cff720d3b165912d40bR159) or [`getShadowRoot`](https://github.com/DevExpress/testcafe/issues/2172#issuecomment-368440061) as a Selector's method to simplify such selectors a little. 
 
Thank you for your reasonable suggestion to add built-in support for shadow DOM elements' selectors.  We already have [an issue](https://github.com/DevExpress/testcafe/issues/2172) for this feature, so you can track our progress there.

**Comment by HugoDel** [comment]
Thanks for your response and for the documentation. I didn't catch this issue before opening this one, sorry.
