### ISSUE TITLE
PageModel Cannot implicitly resolve the test run 

### ISSUE THREAD

**Issue by devmondo** [DevExpress/testcafe#4061]
### What is your Test Scenario?
ability to use pageModel from external Lib 
### What is the Current behavior?
it is the exactly the same issue as in this thread (https://github.com/DevExpress/testcafe/issues/3526), the problem is that we are not using babel but `webpack`  + `typescript` and `tslib`  to transform `async/await`, and i have noticed that as mentioned in the other thread, whenever you use `async/await` in external lib or helper utilities this happens, because of the new clean stackframe created. 
sorry to create one, but it is closed and can not comment on it.

### What is the Expected behavior?
to be able to use PageModel, or at least able to use a similar solution in typescript instead of Babel

### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 

`page-model.ts`
```js
 import {t} from 'testcafe';

export class PageModel {

   async login(name: string, pass: string) {
       console.log(t);
        await  t.typeText(`#txtUserID`, name)
            .typeText(`#txtPassword`, pass)
            .click(`#sub`);
   }
}

export const pageModel = new PageModel();
```

`example.ts`

```js
import {pageModel} from "../../models/page-model";

test('example',t=>{
await pageModel.login(`blah@tgb`,`ddd!`);
}

```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```bash

Cannot implicitly resolve the test run in the context of which the test contr
oller action should be executed. Use test function's 't' argument instead.
C:/projects/test/src/models/page-model.ts


    2 |
    3 |export class PageModel {
    4 |
    5 |   async login(name: string, pass: string) {
    6 |       console.log(t);
 >  7 |        await  t.typeText(`#txtUserID`, name)
    8 |            .typeText(`#txtPassword`, pass)
    9 |            .click(`#sub`);
   10 |   }
   11 |}
   12 |
```

 </details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.3.1
* node.js version:                    10.16.0
* command-line arguments:  
* browser name and version: chrome 75
* platform and version:          windows 10 64 bit
* other:

**Comment by miherlosev** [comment]
Hi @devmondo 

Try the followings:
* specify the `es5` value for the TypeScript's [target](https://www.typescriptlang.org/docs/handbook/compiler-options.html) property
* turn off the `tslib` library
* specify TestCafe as `peerDependency`.

**Comment by devmondo** [comment]
@miherlosev thanks for the suggestions, 
should i do that in the main project or in the external lib ?

**Comment by AndreyBelym** [comment]
@miherlosev's suggestions are about compiling your external library.

**Comment by devmondo** [comment]
@AndreyBelym thanks a lot :)

@miherlosev, setting `tsonfig.json` `target` property to `es5 was the only thing that helped neither removing `tslib` or adding testcafe as peer dep solved it. thanks a lot really! 

but this is not the ultimate solution, for me, I am fine setting target to `es5` but some other projects requires having `es6` code and no transformation. is there a solution to make this work with any target `es6` `es7` etc...?

**Comment by AndreyBelym** [comment]
You can use any targets below `es2017` for compilation. With this and more modern targets (`es2018`, `es2019`, `esnext`) disable compiling `async` function to state machines. As it is said in issue #3526, currently TestCafe can't resolve test context in native `async` functions. Unfortunately, it seems that TypeScript doesn't have an option to enable `async` function compilation aside from setting the `target` property in `tsconfig.json`.

**Comment by devmondo** [comment]
@AndreyBelym thanks a lot for the detailed explanation, after reading that, is there a way to use babel + typescript to just transform the `async` parts and keep the rest of code?

**Comment by alexey-lin** [comment]
Hi @devmondo
 
If you are using TypeScript version 3+, you can use Babel for compilation (with preset-typescript) and for `async`s transformation (e.g. with plugin-transform-async-to-generator). If you are using an older version of TypeScript, you'll have to compile it as usual and then transform the result with Babel to get rid of `async`s. In any case, we cannot provide you a ready Babel config for your scenario.

**Comment by devmondo** [comment]
@alexey-lin thank you very much for the help and tips, it is exactly what i had in mind and that is what i am planning to do :)

**Comment by alexey-lin** [comment]
@devmondo you are welcome! Good luck with your project!
