### ISSUE TITLE
IE11 Input Typing Problem

### ISSUE THREAD

**Issue by franciscolosardo** [DevExpress/testcafe#4064]
### What is your Test Scenario?

 Given a webpage with 2 input fields i'm trying to type text into both. Problem is presented when using IE11 on saucelabs with testcafe. Typetext only inputs text to the first of both inputs, the second time i call typeText method it doesn't seem to work correctly.
### What is the Current behavior?

When using typeText method on first input (could be any of the two inputs mentioned) it types perfectly the text passed. Later when i try to switch to the other input and type text into it it refuses to type the text or even select the input requested. I tried both clicking and then typeText methods but nothing seems to work in IE11. 
Taking in consideration this works without any problem on chrome and firefox it's possibly a problem fully related to IE11.
### What is the Expected behavior?

 typeText method should switch between these two input fields typing the correct text. Using click and then triggering the typeText method or just by using typeText method.
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):
https://anypoint.mulesoft.com/login/
<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```
       // Please note all code below works on chrome and firefox and selectors are properly initialized
        await t.click(loginPage.userNameInput);
        await t.typeText(loginPage.userNameInput,username,{replace:true,caretPos:0,paste:true});
        await t.click(loginPage.passwordInpu);
        await t.typeText(loginPage.passwordInput,password,{replace:true,caretPos:0,paste:true});

        await t.click(loginPage.signInButton);
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
2. Try to fill in username and password with any value...
3. Second input field tried to access isn't filled up
 
### Your Environment details:
 
* testcafe version:    1.3.3               
* node.js version:       10.15.1             
* command-line arguments:  
* browser name and version: IE11 on Saucelabs
* platform and version:    Windows 8.1      
* other:  Using saucelabs provider

**Comment by franciscolosardo** [comment]
Just confirmed this also happens using IE11 on a local instance of testcafe on a windows 8.1 PC

**Comment by miherlosev** [comment]
Hi @franciscolosardo 

Thank you for the provided detail. I've reproduced the problem.

For team:
I've reproduced the problem with IE11 on Windows 10.
Test
```js
fixture `Fixture`
	.page('https://anypoint.mulesoft.com/login/');
	
test('test', async t => {
	await t
		.typeText('input[name=username]', '<username>') // need to register before
		.typeText('input[name=password]', '<password>')
		.click('[data-test-id=SignIn-Submit]');
});	
```

**Comment by ngrossi** [comment]
Hi Team: 
                This issue is also affecting us in some way. it would be nice to have a fix soon. 

Nic :)

**Comment by mnbattaglia** [comment]
Hi guys. This is blocking us too. Any updates on this? Thanks!

**Comment by AlexKamaev** [comment]
@mnbattaglia not yet, we'll close this issue once we fix it.
