### ISSUE TITLE
Zapproxy integration with Testcafe

### ISSUE THREAD

**Issue by shilpabasu22** [DevExpress/testcafe#4066]
### What is your Test Scenario?
I would like the ability to run Zap proxy along with my Testcafe tests

### What are you suggesting?
Integrate Zap proxy and Chrome capabilities required.

### What alternatives have you considered?
Can't find any

**Comment by Dmitry-Ostashev** [comment]
Thank you for sharing your idea with us. We will check out this tool and see how its integration might be useful for testcafe users.

**Comment by sjoedwards** [comment]
Hi, was there an investigation into ZAP proxy integration with Testcafe?

**Comment by shilpabasu22** [comment]
Hi, No there hasn't been any update.
