### ISSUE TITLE
Add capability to set up the { paste: true } as a default option value for `typeText` action

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#4067]
It would be useful to speed up the test execution.

https://stackoverflow.com/questions/57180579/testcafe-t-typetext-use-paste-true-by-default

**Comment by kirovboris** [comment]
I think it can be handled after the implementation of [custom actions](https://github.com/DevExpress/testcafe/issues/1535). It'll be simpler to create a wrapper over the `type` action instead of new options.

**Comment by AndreyBelym** [comment]
As @kirovboris said, it's better to implement custom actions or [clipboard actions](https://github.com/DevExpress/testcafe/issues/2668) instead. Using `paste` is not recommended in general conditions, because it just replaces the target's element value.
