### ISSUE TITLE
.click() not executing in latest version of firefox

### ISSUE THREAD

**Issue by andym0457** [DevExpress/testcafe#4069]
I have an initially login page which requires clicking the submit button to login into the main app. This happens inn the beforeEach function.
It works perfectly fine when running the tests in, chrome, chrome-canary and chromium. In firefox it can select the button and the cursor appears over it but never redirects to the main app.
Is this an issue with the latest version of firefox that it doesn't support the .click() fully?
- Firefox version 68.0.1
- Testcafe version 1.3.3

**Comment by arubtsov** [comment]
Hello @andym0457,
 
I was not able to reproduce the described behavior. Could you please provide us with a public page or a simplified example to reproduce the issue? Or, better yet, fill in all the fields of the [bug report template](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md).
