### ISSUE TITLE
Request hook's onResponse method not being called

### ISSUE THREAD

**Issue by Lukas-Kullmann** [DevExpress/testcafe#4070]
So I don't know how this happens. But I want to manipulate the response headers of a request.
So I set up a request hook:

```js
const { RequestHook } = require('testcafe');

class SecureCookieFlagRemovalHook extends RequestHook {
  constructor(requestFilterRules) {
    super(requestFilterRules, { includeHeaders: true, includeBody: false });
  }

  async onRequest({ requestOptions }) {
    console.log(`Doing request to ${requestOptions.url}`);
  }

  async onResponse(event) {
    console.log('event', event);
  }
}

module.exports = SecureCookieFlagRemovalHook;
```

and attach it to the test

```js
  const hook = new SecureCookieFlagRemovalHook(/\/url-filter\//);

  await t.addRequestHooks(hook);
```

There are actually two requests in the test that are being done. The console output is:

```
Doing request to [URL1]
Doing request to [URL2]
event ResponseEvent { [Response event for URL2] }
```

Why wouldn't the onResponse handler be called for the first request.
The way it works in this test is, that the response of the first request is actually used in the URL of the second one. So the first request is in fact finished.

The first request is a post request via `fetch` and the response then read via `response.json()`.
The second request is then a redirect to a new page via `window.location.assign()`.

How do I debug this? I'm really hitting the ceiling here. The testcafe code is very unreadable to me due to the integration of hammerhead. So I really don't know where to start.

**Comment by Dmitry-Ostashev** [comment]
Hello,

I was unable to reproduce this behavior on my side. Could you please provide us with a sample test page or a link to it?
Besides, you can help us to determine the issue by logging requests with the hammerhead proxy:

1. Add the following code [here](https://github.com/DevExpress/testcafe-hammerhead/blob/master/test/playground/server.js#L18):

```
session.addRequestEventListeners(require('../../')
    .RequestFilterRule
    .ANY, {
        onRequest:           (e) => console.log('request', e._requestInfo.requestId, e._requestInfo.url),
        onConfigureResponse: () => {},
        onResponse:          (e) => console.log('response', e.requestId, e.body) 
    }, err => console.log(err));
```

2. Run the proxy as it described in [Readme](https://github.com/DevExpress/testcafe-hammerhead#first-look).

3. Make sure that all your requests are displayed in the server-side console and let us know your results.

**Comment by Lukas-Kullmann** [comment]
Hey Dmitry!

Thanks for you response. I tried it. I see all the requests in the console. The particular ones that I was talking about above were logged with a response:

```
request GGoxWb501 [URL1]
response GGoxWb501 undefined
request 7kJSGkfM8 [URL2]
response 7kJSGkfM8 undefined
```

The response should have a body in both cases, but I guess that's just a configuration thing.

**Comment by AndreyBelym** [comment]
Thank you for your information. This behavior looks very similar to issue #4056. We need to research it, so it will be very helpful if you can provide a sample page.
