### ISSUE TITLE
Edge not closed after tests running with gitlab-runner

### ISSUE THREAD

**Issue by adminter3** [DevExpress/testcafe#4071]
### What is your Test Scenario?

 Running test with Gitlab-runner using the shell executor.
### What is the Current behavior?

When the tests are finished Edge doesn't close, only testcafe with a disonnected status is shown in the browser.
### What is the Expected behavior?

 The browser shall close when the tests are finished. 
### What is your web application and your TestCafe test code?

Your website URL (or attach your complete example):
x
<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```
 import { config } from "../../../testEnvironment/config";
import { logger } from "../../hosting/logger";
import { initialize } from "../../../helpers/initialize";
import { Selector } from "testcafe";

fixture(`Project`)
  .page(config.httpsUrl_DevEnv)
  .requestHooks(logger.simpleLogger)
  .beforeEach(async () => {
    // await initialize(logger.simpleLogger);
  });

test.only("First automation test", async t => {
  await t.click(Selector("input[type=checkbox]")).click(Selector("button"));
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
.testcaferc.json

{
  "browsers": ["edge", "chrome", "firefox"],
  "debugMode": false,
  "debugOnFail": false,
  "developmentMode": false,
  "hostname": "localhost",
  "port1": "5050",
  "port2": "5051",
  "screenshotPath": "/reports/screenshots",
  "takeScreenshotsOnFails": true,
  "reporter": "list",
  "selectorTimeout": 40000,
  "src": ["src/ui/project/*.test.ts", "src/ui/devices/*.test.ts"],
  "quarantineMode": false
}
```

```
.gitlab-ci.yml

stages:
  - test
Build_test:
  stage: test
  script:
    - npm ci
    - npm test

```
</details>

<details>
<summary>Your complete test report:</summary>
x

```

```
</details>

<details>
<summary>Screenshots:</summary>

![edge_disconnected](https://user-images.githubusercontent.com/29160941/61870810-56e06f80-aedf-11e9-84ea-fade28bfc958.PNG)

</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:  v1.3.3                 
* node.js version:   v10.15.3                 
* browser name and version: Edge 17.17134.0
* platform and version:  Windows 10.0.0
* other:    Gitlab-runner v12.1.0

**Comment by AndreyBelym** [comment]
If you use `gitlab-runner start` command to start your GitLab agent, it will be started as a service. There are some restrictions for running GUI apps as a service: https://gitlab.com/gitlab-org/gitlab-runner/issues/1046. Please, try to disable and stop the GitLab service and start your GitLab agent in the current user session by running `gitlab-runner run` in the command prompt.

**Comment by adminter3** [comment]
> If you use the `gitlab-runner start` command to start your GitLab agent, it will be started as a service. There are some restrictions for running GUI apps from a service: https://gitlab.com/gitlab-org/gitlab-runner/issues/1046. Please try to disable and stop the GitLab service and start your GitLab agent in the current user session by executing `gitlab-runner run` in the command prompt.

@AndreyBelym  thanks for your quick feedback!
Yes, it worked now!

BR

**Comment by Dmitry-Ostashev** [comment]
Thank you for the update. I'm happy to hear that you have figured out how to resolve the issue.
