### ISSUE TITLE
.click() not working on Web element with z-index

### ISSUE THREAD

**Issue by sahilolx** [DevExpress/testcafe#4072]
### What is your Test Scenario?
User is not able to click on a button with z-index.
 
### What is the Current behavior?
User is not able to click on a button with z-index.
 
### What is the Expected behavior?
User should able to click on a button with z-index.
 
### What is your web application and your TestCafe test code?
https://www.olx.in/

<details>
<summary>Your complete test code (or attach your test files):</summary>
 `async openNthConversation(){
        await t.click(Selector('[data-aut-id="listItemConversation"]').nth(0));  
        let safetyTips = Selector('[data-aut-id="continueBtn"]'); 
        let safetyTipsExists = await safetyTips.exists;
        if(safetyTipsExists) {
            await t.wait(2000);
            await t.click(safetyTips); // this is not working
        }
    }`
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
```
</details>

<details>
<summary>Your complete test report:</summary>
```
✖ Go to Chat Window - Verify Ad Banner Details

   1) A JavaScript error occurred on "https://www.olx.in/nf/chat/user/400001959/1500182520".
      Repeat test actions in the browser and check the console for errors.
      If you see this error, it means that the tested website caused it. You can fix it or disable tracking JavaScript errors in TestCafe. To do the latter, enable the "--skip-js-errors" option.
      If this error does not occur, please write a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      undefined:
          No stack trace available

      Browser: Chrome 69.0.3497 / Mac OS X 10.13.6


```
</details>

```
![image](https://user-images.githubusercontent.com/30290613/61873929-b604ab00-af04-11e9-8775-570452237ad5.png)

```
</details>

### Steps to Reproduce:

1. Go to https://www.olx.in/ & perform login.
2. Open any ad from home page & send seller a message to create chats.
3. Go to chats section & open any conversation. ( To open Chat Window.)
4. click on 3 dots menu in the top corner  & open safety Tips.
5. TestCafe is not able to click on the CONTINUE TO CHAT Button.
 
### Your Environment details:
 
* testcafe version:                   1.3.3
* node.js version:                    v9.10.1
* command-line arguments:   yarn testcafe 'firefox'
* browser name and version:  chrome 69.03497
* platform and version:           macOS 10.13.6
* other:

**Comment by Dmitry-Ostashev** [comment]
Hello,

I tried to reproduce this issue and got the following results.
There is a javascript error on the page (you can see information about it in the test resport). But when I run the test with the [--skip-js-errors](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors) option, it will work properly.

Try to reproduce and investigate console errors on your side without testcafe, or run it with the option mentioned above. Let us know your results.

**Comment by sahilolx** [comment]
Hello, I tried with --skip-js-errors option, I am not getting any errors but still .click() is not working. Manually its working fine & there is no error in browser console.

**Comment by Dmitry-Ostashev** [comment]
Until now, our attempts to replicate this issue were unsuccessful. If you obtain precise reproduction steps, so we can see the issue and examine it on our side, please let us know.

**Comment by sahilolx** [comment]
its still not working but I have found a workaround for the same & hence closing this issue.
