### ISSUE TITLE
Failed to find a DNS-record for the resource at <a href="https://site.com">https://https://site.com</a>.

### ISSUE THREAD

**Issue by nkrishna79** [DevExpress/testcafe#4074]
### What is your Test Scenario?
I am just using testcafe as a helper using codeceptjs. I have some end to end test which I would like to run using testcafe 
 
### What is the Current behavior?
i get this error message 
Failed to find a DNS-record for the resource at <a href="https://https://site.com">https://https://site.com</a>.
 upon trying to access an environment - internal. if i replace my test environment with bbc.co.uk - it opens up just fine. 
### What is the Expected behavior?
I was able to open up testcafe a while ago and was successful in running tests locally as well as in browserstack
 
### What is your web application and your TestCafe test code?
![image](https://user-images.githubusercontent.com/37705580/61879697-7e3d3980-aeeb-11e9-86f7-4ff600457add.png)

 
Your website URL (or attach your complete example): you can pick something thats behind your firewall 

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
************name of test is test1.js**************
import { Selector } from 'testcafe';

fixture `Getting Started`
    .page `https://lp3.prerelease.drthom.com/`;

test('My first test', async t => {
    // Test code
});
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...any site thats internal behind a firewall 
3. Execute this command... testcafe chrome test1.js
4. See the error... Failed to find a DNS-record for the resource at <a href="https://site.com">https://https://site.com</a>.
 
### Your Environment details:
 
* testcafe version:                   1.3.2
* node.js version:                    12.2.0
* command-line arguments:  testcafe chrome test1.js
* browser name and version: chrome 75
* platform and version:          windows 10 64 bit

**Comment by nkrishna79** [comment]
@AndreyBelym - it will be great if you can guide me on this. I tried running some snippets to see whats causing this issue and I got this 

![image](https://user-images.githubusercontent.com/37705580/61880064-1a674080-aeec-11e9-8555-2f3f8e4810db.png)
But i dont know why is this happening?

**Comment by nkrishna79** [comment]
@AndreyBelym Ignore this issue as i found out the problem happened due to an issue with nodejs 12.2.0. Upon downgrading to 10.16.0 - it works perfectly fine.

**Comment by devmondo** [comment]
i highly suggest to the great testcafe team to test testcafe with node 12x 

another example is https://github.com/DevExpress/testcafe/issues/4052

**Comment by LavrovArtem** [comment]
Thanks! We will test it.
