### ISSUE TITLE
Unable to switch to the new frame using switchToIframe() method.

### ISSUE THREAD

**Issue by dipeshDM1** [DevExpress/testcafe#4075]
### What is your Test Scenario?
Unable identify the element present inside the frame
 
### What is the Current behavior?
1. I am performing some operation on window1.
2. Now, I have clicked on a button which opened new window (window2).
3. On Window2, there is an element inside the frame.
 
### What is the Expected behavior?
We should be able to click this element
 
### What is your web application and your TestCafe test code?
 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
         await t 
        .switchToIframe(Selector('frame').nth(1))
        .click(this.adverseAction_btn)
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version: 1.2.1                  
* node.js version: 6.9.0                     
* command-line arguments:  None
* browser name and version: Chrome Version 75.0.3770.100 (Official Build) (64-bit)
* platform and version:        Windows 10 (64 bit)
* other:

**Comment by Farfurix** [comment]
@dipeshDM1 

Hello,

This information is not sufficient to reproduce the issue. Could you please provide us with your sample project (or some public URL)?
