### ISSUE TITLE
IE11 issue - TestCafe freezes on login page. Browser disconnects.

### ISSUE THREAD

**Issue by sijosyn** [DevExpress/testcafe#4079]
### What is your Test Scenario?

Attempting to run invalid login test in IE11. 

### What is the Current behavior?

But TestCafe freezes on login page and won't input text into username & password field. IE11 browser disconnects after few mins.
 
### What is the Expected behavior?

TestCafe should not freeze and should type in text into textfields similar. Note: Same script works in Chrome, Firefox & Safari.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from 'testcafe';

fixture `Invalid login check`
	.page `https://aperture.synacor.net/`
	.beforeEach(async t => {
		await t.pressKey('esc');
		const modalEmailCampaign = Selector('div[id*="2fEmailCampaign"]');
		if ((await modalEmailCampaign.exists) && (await modalEmailCampaign.visible)) {
			await t.click(modalEmailCampaign.find('.close'));
		}
	});

test('IE11 login issue', async t => {
	await t.click(Selector('li[id*="2Flogin"]').find('*').withText('Sign In'));
	await t.typeText(Selector('input#username', { timeout: 60000 }), 'xyz');
	await t.typeText(Selector('#password'), 'password');
	await t.click(Selector('button#login'));
	await t.expect(Selector('.alert-error').exists).ok('Invalid loging Alert Error displayed');
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

Browser disconnect error
<img width="1007" alt="Disconnect_Error" src="https://user-images.githubusercontent.com/29459281/61954842-c4e07180-af87-11e9-82e4-234ab475a883.png">

Login screen
<img width="1361" alt="Login_Screen" src="https://user-images.githubusercontent.com/29459281/61954845-c873f880-af87-11e9-81f1-9fa7c50618be.png">

</details>

### Steps to Reproduce:

Run the provided script
 
### Your Environment details:
 
* testcafe version:                    v1.3.2
* node.js version:                     v8.11.1
* command-line arguments:   testcafe ie test.js
* browser name and version:  Chrome 75
* platform and version:           Win 10
* other:

**Comment by LavrovArtem** [comment]
TestCafe supports IE starting with version 11 ([Officially Supported Browsers](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/browser-support.html#officially-supported-browsers)) but the login page contains the `X-UA-Compatible: IE=EmulateIE9` response header that runs emulation in IE9.
