### ISSUE TITLE
TypeScript compiler

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#408]
Make TypeScript first class citizen by automatically compiling `.ts` files like we do with ES6. This can be  done (and more likely should) as standalone plugin.

**Comment by rafakwolf** [comment]
With typescript can be more easy to learn the framework, the type definitions are a documentation itself. 
:D

**Comment by inikulin** [comment]
- [ ] Extract `ESTargetCompiler` base class
- [ ] Implement `TypeScriptCompiler`
- [ ] Implement #980 and let compiler provide extensions for the test lookup algorithm
- [ ] Implement TS definitions
