### ISSUE TITLE
add video path testRunInfo

### ISSUE THREAD

**Issue by philipgriffin** [DevExpress/testcafe#4080]
### What is your Test Scenario?
I would like to know the path of the video associated with the running test

### What are you suggesting?
To add a videoPath property to the testRunInfo

**Comment by miherlosev** [comment]
Hi @philipgriffin 

Your use case is a part of [Sending custom data to reporter ](https://github.com/DevExpress/testcafe/issues/3584) enhancement. Track this issue to be notified about our progress.

As a workaround, you can pass the 'video path' option to [reportTestDone](https://devexpress.github.io/testcafe/documentation/extending-testcafe/reporter-plugin/reporter-methods.html#reporttestdone) method via [meta](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#specifying-testing-metadata)  parameter.
