### ISSUE TITLE
quarantineMode mode stuck after the first failure

### ISSUE THREAD

**Issue by valerii-cognite** [DevExpress/testcafe#4089]
Are there any restrictions on how and when [quarantineMode](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#quarantine-mode) can be used? I'm currently running testcafe version 1.3.3 against Chrome:75. While setting `quarantineMode: true` and making a test fail on purpose the test run just stuck on the failing step. If to set `quarantineMode: false` the test fails as expected. Am I missing something obvious from the docs?

**Comment by alexey-lin** [comment]
@valerii-cognite There are no known restrictions and the behavior you describe is not typical. It sounds like there is something in your test code that might lead to a script hang. Please verify this. If you don't find any suspicious places, could you provide all required information and fill-in the [bug template](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md) including a sample project so we can reproduce and investigate the issue? Thank you in advance.
