### ISSUE TITLE
A problem with RequestMock api and fetch with parameter credentials: 'include'

### ISSUE THREAD

**Issue by AlexVasilenko** [DevExpress/testcafe#4092]
I try to use RequestMock with fetch and with `credentials: 'include'`.

Steps to reproduce.
I created a file with request 

```
const request = await fetch('http://localhost:8080', {
         method: 'GET',
         credentials: "include"
 });
```

And then I created a mock for that request.

```
const mock = RequestMock()
    .onRequestTo((request) => {
      return request.url === 'http://localhost:8080' && request.method === 'get'
    })
    .respond((req, res) => {
      res.statusCode = 200;
      res.headers = {
        'content-type': 'application/json',
        'access-control-allow-origin': '*',
        'access-control-allow-credentials': true,
        'access-control-expose-headers': 'api-version, content-length, content-md5, content-type, date, request-id, response-time'
      };
      res.setBody({ test: 123 })
    }
    )
```

For that mock I got error in test runner `RequestMock: CORS validation failed for a request specified as {
  <predicate> }` and in browser I got response status=0 and type=opaque.

Without credentials: "include" mocker works correctly.

Thanks for help.

**Comment by helen-dikareva** [comment]
I couldn't reproduce this behavior in a simple example. I created a simple [server](https://gist.github.com/helen-dikareva/8d4f40e902f4e915ecf3591c1f91d946), [a web page](https://gist.github.com/helen-dikareva/3baa817d46b786d91ec11ccbfe0a1034),  `user.json` [file](https://gist.github.com/helen-dikareva/7f1caebc1af87f5d2d6a51baef7735d2), and a testcafe [test ](https://gist.github.com/helen-dikareva/2f885ab76f9d3c1f0592bd4d7adb6829) with similar `RequestMock`. See gists.

You can try to execute the `test.js` test by using the `testcafe chrome test.js` command after you start the server using `node server`.
If you open the `http://localhost:3000/page` page in a browser and click the `CLICK ME!` button, you will see the expected response with `{originFile: 123}`(see the `user.json file`) in the Network tab. If you open the Console or Network tab in DevTools during TestCafe's test execution (the test will stop on the `debug` action), you will see the response's mocked data: `{test: 123}`. There will be no errors or warnings.
 
Please provide us with an example illustrating the problem you described. Also, try to use the `credentials: 'same-origin'` option and let us know your result.

**Comment by AlexVasilenko** [comment]
@helen-dikareva It's my dist with minimal example where I get error. https://gist.github.com/AlexVasilenko/5893c5c17c59bae55b17c837dc56dfed

Testcafe version: 1.3.3
Run: testcafe chrome index.js

**Comment by LavrovArtem** [comment]
I reproduced this behavior and created [example servers](https://gist.github.com/LavrovArtem/9905ebfe03ea8fc4aa3098e0dd6b18a1). I made the same actions as you tried with RequestMock. There was a CORS request with the credentials flag set, but the server is configured using the wildcard (*) as the value of Access-Control-Allow-Origin, which doesn't allow the use of credentials. Chrome throws the following error without TestCafe:
`Access to fetch at 'http://localhost:2019/fetch' from origin 'http://localhost:2018' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.`

[Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials)
