### ISSUE TITLE
Quarantine and live modes are not working nicely together

### ISSUE THREAD

**Issue by valerii-cognite** [DevExpress/testcafe#4093]
### What is the Current behavior?
In both quarantine and live modes failed test will stuck on the first try
 
### What is the Expected behavior?
Failed test should rerun 3 times and print an error of the last run
 
### What is your web application and your TestCafe test code?
```
import { Selector } from 'testcafe';

fixture('Test').page('http://localhost:3000/');

test('Test', async t => {
  console.log('Inside test');
  await t.click(Selector('.test'));
});

```
### Steps to Reproduce:
Clone this repo https://github.com/valerii-cognite/testcafe-quarantine-issue

run `yarn && yarn start`

In order to see a problem run 

`yarn testcafe chrome testcafe --live --quarantine-mode` 

and see theat failed test will never be retriggered and no error will be printed.

In order to see an expected behaviour run 

`yarn testcafe chrome testcafe --live` 

or 

`yarn testcafe chrome testcafe --quarantine-mode` 

and observe an error.

### Your Environment details:
 
* testcafe version:                   1.3.3
* node.js version:                    v8.13.0
* browser name and version: Chrome 75
* platform and version:           macOS 10.13

**Comment by AndreyBelym** [comment]
Thank you for your report. I've reproduced the issue. We will address it in some next development sprint.
