### ISSUE TITLE
Fix IFrames  Initialization Code for Chrome 76

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#4094]
- [ ] Fix the `<iframe>` re-initialization code in the TestCafe code:
 
https://github.com/DevExpress/testcafe/blob/7177efe484bfb7ff57d42964ecf988d331b47f76/src/client/ui/index.js#L73

https://github.com/DevExpress/testcafe/blob/7177efe484bfb7ff57d42964ecf988d331b47f76/src/client/core/index.js#L72

https://github.com/DevExpress/testcafe/blob/7177efe484bfb7ff57d42964ecf988d331b47f76/src/client/automation/index.js#L60

https://github.com/DevExpress/testcafe/blob/8c6e72128636389d884d9f07f9185749f4dddceb/src/client/driver/index.js#L20

- [ ] Fix the initializaton code for `<iframe src="javascript:'<html></html>'">` in Hammerhead:

https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/iframe.ts#L116

 - [ ] Enable back the `test/functional/fixtures/regression/gh-1999/test.js` test.

**Comment by gooddaytoday** [comment]
Is it related with this Issue: https://support.google.com/chrome/thread/11089651?msgid=11328844?

Cause in Chrome 76+ my tests fail until I switch off `chrome://flags/#out-of-blink-cors` flag.  More precisely, drag'n'drop operations with offsetX/offsetY become wrong (offsetY is more by 6px in test).

Or my bug is different and I must create new Issue?

**Comment by miherlosev** [comment]
Hi @gooddaytoday 

This issue is not related to the  https://support.google.com/chrome/thread/11089651?msgid=11328844 thread. Please create a separate issue and provide a simple example with which we can reproduce the problem on our side.

**Comment by gooddaytoday** [comment]
@miherlosev  
Sorry, investigated a little my problem and it is not because of TestCafe. Its just Chrome, that renders HTML blocks with different sizes for personal user and default new user. Also, Firefox renders HTML differently, than Chrome (sizes from `.getBoundingRectangleBox()`)
