### ISSUE TITLE
Webapps using window.parent !== window to validate the iframe is failing in tests

### ISSUE THREAD

**Issue by Hellboyksr2** [DevExpress/testcafe#4095]
### Are you requesting a feature or reporting a bug?
Bug

### What is your Test Scenario?
Any web page which contains window.parent !== window to validate the weather the webpage is rendered in iframe or not.

export const isInIframe = () => {
  return window.parent !== window
}

### What is the Current behavior?
Its always returning false as the window object being validated here is of test cafe instance.

### What is the Expected behavior?
Should return true/false based on the actual app.

```js

```
### Your Environment details:
 
* testcafe version: 1.3.3        
* node.js version:  v10.16.0              
* browser name and version: Browser: Chrome 76.0.3809
* platform and version:  Windows 10.0.0

**Comment by AndreyBelym** [comment]
Thank you for your report. Unfortunately, I can't reproduce this behavior. Could you please provide a sample page or help me modify my example so that it reproduces the problem?

##### index.html
```html
<!DOCTYPE html>
<html>
    <head>
        <title>Top window test</title>
        <script src="app.js"></script>
    </head>
    <body>
        <div id=log></div>
        <iframe src="iframe.html"></iframe>
        <script>
            log.innerHTML = `
                Top window test: ${test()} <br>
            `;
        </script>
    </body>
</html>
```

##### iframe.html
```html
<!DOCTYPE html>
<html>
    <head>
        <title>Iframe test</title>
        <script src="app.js"></script>
    </head>
    <body>
        <div id=log></div>
        <script>
            const parentTest = parent.test;

            log.innerHTML = `
                Iframe window test from parent: ${parentTest()} <br>
                Iframe window test: ${test()} <br>
            `;
        </script>
    </body>
</html>
```

##### app.js
```js
window.test = isInIframe = () => {
    return window.parent !== window
}
```

##### test.js
```js
import { Selector } from 'testcafe';

fixture `Simple_Fixture`
    .page `./test.html`;

test('Test_Login', async t => {
    await t
        .expect(Selector('#log').textContent).contains('Top window test: false')
        .switchToIframe('iframe')
        .expect(Selector('#log').textContent).contains('Iframe window test from parent: false')
        .expect(Selector('#log').textContent).contains('Iframe window test: true')
});
```

Also, please note that web apps that use native ES6 modules and `import/export` statements in the browser context are not supported by TestCafe yet: https://github.com/DevExpress/testcafe-hammerhead/issues/1725.
