### ISSUE TITLE
testcafe.maximizeWindow() causes issue on CircleCi

### ISSUE THREAD

**Issue by shilpabasu22** [DevExpress/testcafe#4096]
### What is your Test Scenario?
I am trying to run the testcafe tests on Circle CI and I have configured my tests according to https://devexpress.github.io/testcafe/documentation/continuous-integration/circleci.html
 
### What is the Current behavior?
I circle CI I am getting following error:
 A JavaScript error occurred on "<website url>".
         Repeat test actions in the browser and check the console for errors.
         If you see this error, it means that the tested website caused it. You can fix it or
      disable tracking JavaScript errors in TestCafe. To do the latter, enable the
      "--skip-js-errors" option.
         If this error does not occur, please write a new issue at:
         "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

         JavaScript error details:
         SyntaxError: Unexpected token <

         Browser: HeadlessChrome 75.0.3770 / Linux 0.0.0
         Screenshot: /home/circleci/repo/screenshots/2019-08-01_11-05-13/Todays-Meeting.png

             3 |
             4 |const configurationSettings = new Configuration();
             5 |
             6 |fixture`Todays-Meeting`.page`${configurationSettings.environment}`.beforeEach(
             7 |  async t => {
          >  8 |    await t.maximizeWindow();
             9 |  }
            10 |);
            11 |
            12 |test('Should be able to view the Todays meeting', async () => {
            13 |  await viewTodaysMeeting();

            at maximizeWindow (/home/circleci/repo/tests/desktop/todays-meeting.js:8:13)
            at fixture.page.beforeEach (/home/circleci/repo/tests/desktop/todays-meeting.js:6:1)
            at <anonymous>
      (/home/circleci/repo/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
            at TestRun._executeTestFn
      (/home/circleci/repo/node_modules/testcafe/src/test-run/index.js:263:19)
            at TestRun._runBeforeHook
      (/home/circleci/repo/node_modules/testcafe/src/test-run/index.js:283:31)
            at TestRun.start
      (/home/circleci/repo/node_modules/testcafe/src/test-run/index.js:311:24)
 
### What is the Expected behavior?
Tests should execute successfully
 
### What is your web application and your TestCafe test code?
Sorry, our website is currently not accessible outside the development environment right now but the code snippet is added below

 
Your website URL (or attach your complete example):

<details>
<summary>config.yml file:
version: 2.1

executors:  
  node-executor:
    docker:
      - image: circleci/node:10.16.0-jessie-browsers
    
    working_directory: ~/repo

jobs:
    test:
      executor: node-executor
      steps:
        - checkout
        - restore_cache:
            name: Restore Cache
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-
        - run: 
            npm install
        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}
        - run: npm test
        - run:
            name: Save Test Results
            command: |
              mkdir -p test-results
            when: always
        - store_test_results:
            path: test-results
          
workflows:
  version: 2
  nightly:
    jobs:
      - test
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - master
  build_and_test:
    jobs:
      - test
</summary>

 
import Configuration from '../../config';
import { viewTodaysMeeting } from '../../steps/todays-meeting';

const configurationSettings = new Configuration();

fixture`Todays-Meeting`.page`${configurationSettings.environment}`.beforeEach(
  async t => {
    await t.maximizeWindow();
  }
);

test('Should be able to view the Todays meeting', async () => {
  await viewTodaysMeeting();
});

```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

<!-- Paste your complete test config file here (even if it is huge): -->
test command:
testcafe chrome:headless tests/desktop/**/* -r xunit:test-results/res.xml

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by Dmitry-Ostashev** [comment]
Hello,
This information is insufficient to determine the issue. I was unable to reproduce it with the example from the testcafe documentation. It looks like the JavaScript error occurs on your page.
 
Could you please clarify if your tests work property on a local machine (including the headless browser)? Are there any console errors?
 
You can also try to debug errors on a page using the following instructions from CircleCI: [Debugging Browser Tests](https://circleci.com/docs/2.0/browser-testing/#debugging-browser-tests).

**Comment by shilpabasu22** [comment]
Heel Dmitry,
The test are running fine on my local environment both with headless browser and otherwise. Tehre are no console errors logged.

**Comment by VasilyStrelyaev** [comment]
We could not reproduce this error with a different page, so we need a link to the page that causes it.

If your website is not available publicly, could you please prepare and publish a sample page on which this error can be reproduced.
