### ISSUE TITLE
Improve HTTPS Documentation / Examples / Error Messages

### ISSUE THREAD

**Issue by pcurrivan** [DevExpress/testcafe#4099]
The "Test HTTPS and HTTP/2" documentation page [here](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/test-https-and-http2-websites.html) includes some code that uses a self-signed certificate and has this comment:

> // Browsers restrict self-signed certificate usage unless you
> // explicitly set a flag specific to each browser.
> // For Chrome, this is '--allow-insecure-localhost'.

As far as I can tell. **Firefox does not have such a flag**.  So in order to test in Firefox under HTTPS we must set up a certificate authority, for example using [mkcert](https://github.com/FiloSottile/mkcert).  I have been trying for two days to get a mkcert certificate to work with TestCafe and it simply doesn't work.  Although the browser claims to trust the certificate, the TestCafe / Hammerhead files simply do not load.  There are no useful error messages, which makes this issue very hard to debug.  (I get the typical "__get is not a function" error message which doesn't help me at all).

I have two requests:
1) Provide a complete example that works with Firefox under HTTPS.  The example you give for Chrome doesn't work with Firefox.

2) If possible, show better error messages if there is a problem loading the TestCafe files.

**Comment by alexey-lin** [comment]
@pcurrivan Thank you for bringing this to our attention. We will take a look into this and see what we can do. We'll reply here once we have any results.

**Comment by AlexSkorkin** [comment]
We improved the HTTPS documentation topic within this commit: [https://github.com/DevExpress/testcafe/commit/66e24a1f1c6b7b659a288cd7203432c4301e23cd](https://github.com/DevExpress/testcafe/commit/66e24a1f1c6b7b659a288cd7203432c4301e23cd).

**Comment by VasilyStrelyaev** [comment]
We updated the documentation in https://github.com/DevExpress/testcafe/commit/66e24a1f1c6b7b659a288cd7203432c4301e23cd
