### ISSUE TITLE
Tests stuck without any error

### ISSUE THREAD

**Issue by sivanisentinel** [DevExpress/testcafe#4104]
Sometimes test get stuck without any error thrown.
Is there a way to see testcafe errors? how to distinguish which test/fixture gets stuck?
Is there a way to set test timeout and fail the test of the timeout passed?

**Comment by miherlosev** [comment]
Hi @sivanisentinel 

The behavior your described looks like a bug. To find the cause of the problem we need to reproduce this behavior on our side. Could you please provide a small and complete example with which we can reproduce the problem?

**Comment by sivanisentinel** [comment]
It is really hard to reproduce. It sometimes happens and I don't know to predict when or what is causing it to suck.
Do you have testcafe debug logs? what about the test timeout option I asked about?

**Comment by miherlosev** [comment]
> Do you have testcafe debug logs?

Internally TestCafe contains some kinds of debug information, but at present this is not enough to find the cause of the problem.

Could you provide a more details about your environment: Node.js and TestCafe version, browser and operation system name and version?

**Comment by sivanisentinel** [comment]
We are running with node 9.5 on linux with the latest testcafe version on headless chrome 75.0.
But we are looking for solution or problem solving option for future issues as well.
what about the test timeout option I asked about? this will help us a lot.

**Comment by miherlosev** [comment]
> what about the test timeout option I asked about? this will help us a lot.
 
Usually, CI systems regulate the maximum time of test execution.
 
At present, we don't have this option in TestCafe.
You can define the maximum time of test execution programmatically:

```js
const createTestCafe   = require('testcafe');
let testcafe           = null;
const timeLimitPromise = require('time-limit-promise');

createTestCafe('localhost', 1337, 1338, void 0, true)
    .then(tc => {
        testcafe     = tc;
        const runner = testcafe.createRunner();

        const runPromise = runner
            .src('test.js')
            .browsers('chrome')
            .run();

        return timeLimitPromise(runPromise, 5000, { rejectWith: 1 });
    })
    .then(failedCount => {
        console.log('Tests failed: ' + failedCount);
        testcafe.close();
    });

```

**Comment by sivanisentinel** [comment]
Thanks!
I do have the option to timeout the whole run from CI but it does not help up with defining what is stuck.
if even one test is stuck we wont get to reporter and wont get any details about the other tests.
I I could fail only the one test that is stuck I can easily identify it and also get the information about the other tests.

**Comment by AlexKamaev** [comment]
This issue seems to be a bug, however, it's still very unclear, so I'm afraid we are unable to provide any effective help without a working example. Please provide us with your working project and test code to reproduce the issue. If you cannot share it here on Github you can send it at support@devexpress.com

**Comment by sivanisentinel** [comment]
I noticed it's suck when I raised concurrency from 3 to 8. is that a known issue?

Either way it is impossible to know what causing testcafe to stuck when we dont have any trace logs.

**Comment by AlexKamaev** [comment]
We are not aware of this issue, however, if increasing the number of browsers leads to the hang, it can be a problem with RAM. It's just my assumption, because it's impossible to say anything precise without an example.

**Comment by Yaowenjie** [comment]
I also have this issue which is not random on my local machine. Here is my info:
```
node: v10.15.1
testcafe: 1.3.1
system: Win10
browser: Chrome 68.0
```

**Comment by AlexKamaev** [comment]
@Yaowenjie, we need an example to reproduce the issue. I'm afraid the provided information is not sufficient. We would really appreciate it if you share your project details with us.

**Comment by Yaowenjie** [comment]
Hi @AlexKamaev, thanks for reply!

My project is using MicrosoftOnline as login entry and using `useRole` for each test case, it will hang when login was just finished and redirecting just happen (Actually, as opposed to redirecting to our home page, It will be redirected to one wrong URL which is a static resource <SVG icon> path).

But if we try to `fixture.page(URL).beforeEach(DO_LOGIN)`, this issue won't occur.

One difference I can see here is that URL is in fixture level or in Role

**Comment by LavrovArtem** [comment]
Thank you for providing the information. However, it is not sufficient to find the cause of the issue. We need to analyze your page or code to provide you with recommendations. Would you please give me a link to your site if it is public or create a simple example?

**Comment by Yaowenjie** [comment]
@LavrovArtem Thanks for reply! Unfortunately, it is not possible to give you a link, because that is a private project for enterprise. :(

**Comment by Yaowenjie** [comment]
We found more info. It seems like that once one request get a `403/500` response code with empty response body (which might be not the main requests of our app), testcafe will redirect us to `blank` as below. Sometimes it will be redirected to the SVG path as I said above. @AlexKamaev @LavrovArtem Does testcafe has some similar issues like this?
<img width="744" alt="Screen Shot 2019-09-25 at 2 33 02 PM" src="https://user-images.githubusercontent.com/9637652/65575089-912ec180-dfa1-11e9-8013-7f6ae4fa0abf.png">

**Comment by Farfurix** [comment]
@Yaowenjie 

Hello,

We cannot examine this issue without any reproducible example.
Feel free to open a [new bug report](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md) with all required information.
