### ISSUE TITLE
Disonnecting from browserstack and not reconnecting

### ISSUE THREAD

**Issue by W5rd1** [DevExpress/testcafe#4105]
## What is your Test Scenario?
End to End tests for website
 
### What is the Current behavior?
Random disconnects when running E2E tests
 
### What is the Expected behavior?
No disconnect, 3 browser reconnect attempts
 
### What is your web application and your TestCafe test code?

 
I can't provide the code but i wondered if you had a solution for random disconnects with TestCafe in Browserstack during e2e tests.

There's no specific tests that fail a lot, it happens both locally and in the pipeline, and we're using testcafe in conjunction with Browserstack and `testcafe-browser-provider-browserstack"`
`testcafe-reporter-html`

It would be hard to reproduce without running multiple times for it to eventually hit fail.

Is there anything that's just unstable or conflicting?

Can potentially provide a browserstack video of what happens.

**Comment by AndreyBelym** [comment]
Thank you for your report. Likely there is a conflict between your page and TestCafe. Unfortunately, we need to access your website or a sample page to reproduce and debug it. Also, you can try to run your tests with a locally installed browser or use a plugin for a different cloud provider like the [SauceLabs browser provider](https://www.npmjs.com/package/testcafe-browser-provider-saucelabs).
