### ISSUE TITLE
Browsers are not closed when using liveRunner.stop()

### ISSUE THREAD

**Issue by devmondo** [DevExpress/testcafe#4107]
### What is your Test Scenario?
we are using testcafe in the context of a custom framework, and we have a config file that when changed we need to restart testcafe to get new config values, but without killing the process. the way we do it is by using `testcafe.close()`.

everything works fine, but the problem is that testcafe does not close the previous session opened browsers. of course we used `runner.stop()` alongside `testcafe.close()`. but old browsers still open. we tried this hack 
```js
 const browsers = Object.values(this.runner.bootstrapper.browserConnectionGateway.connections);
            for (let browser of browsers) {
                await browser.provider.plugin.closeBrowser(browser.id);
            }
```

which indeed works and close previous session browsers, but i think it is a hack, and not stable, and sometimes causes errors in addition to that i think that there are some global events need to be cleaned up as well,  because when i hit ctrl + r to restart tests i get duplicate `A test run is starting...` so if we restart 3 times we get 4 `A test run is starting...`.
 
### What is the current behavior?
when stoping testcafe in live mode, the opened browsers are not closed.
 
### What is the Expected behavior?
when closing testcafe in live mode, the browsers windows should close too. 
if there is a command for that it would be great to provide.
if there is a way to reset testcafe settings without stoping and restarting it would be great too.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from 'testcafe';

fixture `Getting Started`
    .page `http://devexpress.github.io/testcafe/example`;

test('My first test', async t => {
    // Test code
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```js
const createTestCafe = require('testcafe');
let testcafe         = null;
let liveRunner 		 = null;

start(){
createTestCafe('localhost', 1337, 1338)
    .then(tc => {
        testcafe         = tc;
        liveRunner = testcafe.createLiveModeRunner();

        return liveRunner
            .src('tests/test.js')
            .browsers('chrome')
            .run();
    })
    .then(() => {
        testcafe.close();
    });
}

stop(){
testcafe.close()
liveRunner.stop()
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. use the code above
2. run node testcafe
3. stop testcafe and restart it

 
### Your Environment details:
 
* testcafe version:                   v1.3.3
* node.js version:                    10.6.0
* command-line arguments:  
* browser name and version: chrome, firefox
* platform and version:          WIndows 10 64 bit
* other:

**Comment by AndreyBelym** [comment]
Thank you for your report. I've reproduced the issue.
