### ISSUE TITLE
Assertion error less verbose in latest version

### ISSUE THREAD

**Issue by HugoDel** [DevExpress/testcafe#4117]
### What is your Test Scenario?
Any test scenario.

### What is the Current behavior?
Using the latest version of Testcafé, when an assertion fails, the stack trace is not present anymore.
I try the same test with the 1.2.0 version and I've got the stack trace (see the screenshots). 
 
### What is the Expected behavior?
The stack trace should display in the error message
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 fixture('Test fixture')

test('Test verbose error', async t => {
    await t.navigateTo('http://google.fr')
    await t.expect(1%2).eql(5)
})
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

<img width="757" alt="v1-2" src="https://user-images.githubusercontent.com/12988831/62550509-a5d8be00-b86a-11e9-81e8-16a9668dc91b.png">
<img width="770" alt="v1-3-3" src="https://user-images.githubusercontent.com/12988831/62550710-f9e3a280-b86a-11e9-9a5d-160a2ab86219.png">

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.3.3
* node.js version:                    10.15.3
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by Farfurix** [comment]
@HugoDel 

Hello,

I cannot reproduce the "stack trace is not present anymore" issue.
### My Environment details:
- testcafe version: 1.3.3
- node.js version: 10.15.3
- command-line arguments: `testcafe chrome test.js -S -s screenshots --debug-on-fail`

test.js:
```js
fixture('Test fixture')

test('Test verbose error', async t => {
    await t.navigateTo('http://google.fr')
    await t.expect(1%2).eql(5)
})
```

Result:
```
d:\tst\i4117>node -v
v10.15.3

d:\tst\i4117>testcafe -v
1.3.3

d:\tst\i4117>testcafe chrome test.js -S -s screenshots --debug-on-fail
 Running tests in:
 - Chrome 76.0.3809 / Windows 10.0.0

 Test fixture

----
Chrome 76.0.3809 / Windows 10.0.0
DEBUGGER PAUSE ON FAILED TEST:
AssertionError: expected 1 to deeply equal 5

Browser: Chrome 76.0.3809 / Windows 10.0.0
Screenshot: d:\tst\i4117\screenshots\2019-08-07_11-19-16\test-1\Chrome_76.0.3809_Windows_10.0.0\errors\1.png

1 |fixture('Test fixture')
2 |
3 |test('Test verbose error', async t => {
4 |    await t.navigateTo('http://google.fr')
> 5 |    await t.expect(1%2).eql(5)
6 |})
7 |

at eql (d:\tst\i4117\test.js:5:25)
----
```

Is there any difference in **your command-line arguments** that cause the issue?

**Comment by HugoDel** [comment]
Not really, I use the most simple command: `tetscafe chrome mytest.ts`

**Comment by Farfurix** [comment]
@HugoDel 

I tried to run the `*.ts` test without any flags and it was passed with the correct stack trace:
![Capture](https://user-images.githubusercontent.com/30019338/62625632-49d76d80-b92e-11e9-9a9b-0bcc1601a7af.PNG)

Could you please send us your screencast with the following steps:
1. Run `node -v`.
2. Run `testcafe -v`.
3. Run your `testcafe` command.
4. Show the report without the correct stack trace.
