### ISSUE TITLE
Timeouts set in .testcaferc.json are not respected (test fails after 30m+, should earlier)

### ISSUE THREAD

**Issue by rehael** [DevExpress/testcafe#4120]
### What is your Test Scenario?

Tests run on Angular 7 app sometimes kind–of freeze – heartbeats are flowing, but the test doesn't continue nor fail. Only **after over 30 minutes** TestCafe fails the test and continues.

We have all timeouts configured in `.testcaferc.json`.

This happens once or twice for a suite of over 100 tests, and is completely random – various tests fail, and we can't figure reproducible deterministic minimal case for that behaviour.

Mostly, I'm asking for help with how can we debug this further to find the root cause. Unless it's a known issue…
 
### What is the Current behavior?

Tests randomly fail after 1900+ seconds.
 
### What is the Expected behavior?

Failure should happen earlier, respecting the set timeouts.
 
### What is your web application and your TestCafe test code?

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
    "screenshotPathPattern": "${DATE}T${TIME}-${FIXTURE}_${TEST}-${TEST_INDEX}-Q${QUARANTINE_ATTEMPT}-${FILE_INDEX}",
    "screenshotPath": "./out/screenshots",
    "takeScreenshotsOnFails": true,
    "assertionTimeout": 180000,
    "pageLoadTimeout": 90000,
    "selectorTimeout": 90000
}
```
</details>

<details>
<summary>Part of test report:</summary>

```
1: The specified selector does not match any element in the DOM tree.

    > | Selector('#user-profile')

   Browser: HeadlessChrome 76.0.3809 / Linux 0.0.0
   Screenshot: /opt/vstsagent/_work/3/s/out/screenshots/2019-08-06T04-01-23-[redacted]-errors/1.png

      26 |  static async setLanguage(t: TestController, lang: Language) {
      27 |    await t
      28 |      .expect(navPO.userMenuButton.exists).ok()
      29 |      .click(navPO.userMenuButton)
    > 30 |      .click(navPO.userProfile);
      31 |
      32 |    const currentLanguage = await userProfilePO.selectedLanguage.textContent;

      at Function.<anonymous> (/opt/vstsagent/_work/3/s/helpers/[redacted].ts:30:8)
      at <anonymous> (/opt/vstsagent/_work/3/s/helpers/[redacted].ts:7:71)
      at __awaiter (/opt/vstsagent/_work/3/s/helpers/[redacted].ts:3:12)
      at Function.setLanguage (/opt/vstsagent/_work/3/s/helpers/[redacted].ts:26:16)
      at Object.<anonymous> (/opt/vstsagent/_work/3/s/suites/[redacted].test.ts:210:22)
      at fulfilled (/opt/vstsagent/_work/3/s/suites/[redacted].test.ts:4:58)

fail (1908.006s) - Should change states…[redacted]
```

The failure happens on various selectors:

```
1: The specified selector does not match any element in the DOM tree.

    > | Selector('#user-password')

   Browser: HeadlessChrome 76.0.3809 / Linux 0.0.0
   Screenshot: /opt/vstsagent/_work/1/s/out/screenshots/2019-08-01T09-38-34-[redacted]-errors/1.png

      56 |}
      57 |
      58 |test('[redacted]', async (t) => {
      59 |  await useRole(t, cvRole.cvPremium); // this does NOT use TC's Role mechanism!!!
      60 |  await t.expect(navPO.userMenuButton.exists).ok();
    > 61 |  await t.click(navPO.userMenuButton).click(navPO.userPassword);
      62 |  await expectToBeOnPasswordResetPage(t);
      63 |  await assertPasswordFieldsExistAndAreEmpty(t);

      at Object.<anonymous> (/opt/vstsagent/_work/1/s/suites/[redacted].test.ts:61:39)
      at fulfilled (/opt/vstsagent/_work/1/s/suites/[redacted].test.ts:4:58)

fail (1907.99s) - [redacted]
```
</details>

### Steps to Reproduce:

Unfortunately, we didn't find any reproducible deterministic minimal case resulting in the described behaviour.
 
### Your Environment details:
 
* testcafe version: 1.3.2
* node.js version: 8.14.0 and 10.16.1
* command-line arguments: testcafe chrome:headless suites/*.test.ts -S
* browser name and version: HeadlessChrome 76.0.3809 / Linux 0.0.0
* platform and version: Locally on Windows 10, and on Azure DevOps Build Agent '2.155.1' on CentOS

The question mostly is **why TestCafe doesn't fail the test earlier?** – any guidance how we can dig further into this would be helpful.

**Comment by miherlosev** [comment]
Hi @rehael 
 
I will address your questions one by one. 
 
> Timeouts set in .testcaferc.json are not respected
 

I've prepared an example and it works fine.
 
*test.js*
```js
import { Selector } from 'testcafe';
 
fixture `Fixture`
.page('https://example.com');
test('test', async t => {
await t.expect(Selector('h2').exists).ok();
}); 
```
 
*.testcaferc.json*
```js
{
"assertionTimeout": 30000
}
```
 
> Tests run on Angular 7 app sometimes kind–of freeze – heartbeats are flowing, but the test doesn't continue nor fail. Only after over 30 minutes TestCafe fails the test and continues.
 

It means at the moment TestCafe was already broken. All future problems are consequences of the initial problem.
 
> Unfortunately, we didn't find any reproducible deterministic minimal case resulting in the described behavior.
 

It can be a problem with the Chrome Headless browser. Try to run your tests in Chrome and tell us about your results.

**Comment by rehael** [comment]
Thank you for the time analyzing that. Now let me add more details.

We had this situation also on regular Chrome running on Windows 10 locally on devs's laptops. So it's not limited to headless and/or run on remote machines.

Timeouts for us also work most of the time. But this one or two times like seen in the log extracts – they don't.

Also, you write that _TestCafe was already broken_ – I'm not so sure about it. Yesterday morning run, TestCafe started at 04:01:24.504Z, run through 24 tests, and a while after ~04:11 freezed at the beginning of another test, untill about 04:43, when it failed the test and continued with 43 remaining tests without any browser restarts or any other hiccups.

So where this ~32 minute freeze could come from?

Can web application do this to TestCafe, somehow interfering the execution?

**Comment by miherlosev** [comment]
> Can web application do this to TestCafe, somehow interfering the execution?

Yes, web application can do it. This problem is unstable and can relate to a lot of factors: memory, os version, the tested application state and so on. Try to run your tests with the latest stable TestCafe version (`1.4.0`). If the problem persists, please provide us an example to reproduce the problem on our side.
