### ISSUE TITLE
getTabIds() not available for TestCafe

### ISSUE THREAD

**Issue by blanche-pinto** [DevExpress/testcafe#4121]
### What is your Test Scenario?
I'm trying to get the number of tabs open in the browser. I need to convert this Selenium code to testcafe:
`expect(browser.getTabIds().length).to.equal(1);`

### Your Environment details:
 
* testcafe version:                   1.3.3
* node.js version:                    v10.15.3
* command-line arguments:  chrome --skip-js-errors
* browser name and version: Chrome
* platform and version:          macOS

**Comment by miherlosev** [comment]
Hi @blanche-pinto 

At present TestCafe doesn't support working with multiple browser tabs. We have plans to implement this feature - it is in our [Roadmap](https://devexpress.github.io/testcafe/roadmap/). 

Track an appropriate [issue](https://github.com/DevExpress/testcafe/issues/912) to be informed about out progress.
