### ISSUE TITLE
Runner returns failed test but reporter does not log it

### ISSUE THREAD

**Issue by dlangerenken** [DevExpress/testcafe#4126]
I am using the runner-api to run subsets of my tests with different settings, e.g.

1. everything regarding downloading runs with cdp-port and no concurency
2. everything that is not download related runs wthout cdp-port and with concurrency

For this, I have a method (simplified) such as:
```typescript
const runTests = async (environment: Environment) => {
  const testcafe = (await require('testcafe')()) as TestCafe;
  try {
    let runner = testcafe.createRunner();
    return await runner
      .src(testDirectory)
      .browsers(environment.config)
      .concurrency(environment.concurrency)
      .reporter([
        'list'
      ])
      .filter(
        // some CDP test filtering based on metadata, not relevant here
      )
      .run({
        stopOnFirstFail: true,
        ...
      });
  } finally {
    testcafe.close();
  }
};
```

I call this method with my different configurations:
```typescript
const runAllBrowsers = async () => {
  let totalNumberOfFailedTests = 0;
  for (const browser of browsers) {
    try {
      totalNumberOfFailedTests += await runTests(browser);
      if (totalNumberOfFailedTests > 0) {
        throw new Error(`Number of tests failed: ${totalNumberOfFailedTests}`);
      }
    } catch (e) {
      console.error(e);
      if (stopOnFirstFail) {
        process.exit(1); // failure, quit early enabled
      }
    }
  }
  if (totalNumberOfFailedTests > 0) {
    return Promise.reject(`Number of tests failed: ${totalNumberOfFailedTests}`);
  }
  return Promise.resolve('Tests ran successfully.');
};

runAllBrowsers().catch(() => {
  process.exit(1); // there has been at least one failed test
});
```

This works fine in most scenarios. However, sometimes I see the e2e tests failing with: `Number of tests failed: 1`, but my report does not indicate any failure. Apparently, one of my tests actually failed (thus returning 1), but I cannot identify which test failed and why.

Is there anything wrong in my implementation? Or is this maybe a reporter bug (list-reporter), which is writing the error down asynchronously and I exit the process before it is written down? 

Do you have a recommended way of stopping the process? (I do want it to fail, so I need to return the error-code 1 to it).

**Comment by miherlosev** [comment]
The problem relates to the `stopOnFirstFail` option. We sometimes see the same behavior in our tests.

**Comment by jarekcieslak** [comment]
@miherlosev did you maybe investigate what's causing the issue? I'm being affected by this as well.  Maybe we can help somehow?

Sometimes in test runs I'm getting something like:

```
2020-10-09T08:31:10.081092875Z  Running tests in:
2020-10-09T08:31:10.081128625Z  - Chrome 83.0.4103.116 / Linux 0.0
2020-10-09T08:31:10.081334732Z 
2020-10-09T08:31:10.081342591Z  Test process number 1
2020-10-09T08:31:51.339164052Z  ✓ Test 1 description
2020-10-09T08:36:51.751527604Z 
2020-10-09T08:36:51.751561858Z 
2020-10-09T08:36:51.751780246Z  4/10 failed (5m 42s)
```

**Comment by miherlosev** [comment]
Hi @jarekcieslak 

> Sometimes in test runs I'm getting something like this (concurrency = 3, stopOnFirstFail = true):

Could you please share a full test report with us?
