### ISSUE TITLE
TestCafe - Removing hostname added by testcafe before actual URL?

### ISSUE THREAD

**Issue by Orchardeye** [DevExpress/testcafe#4128]
Testcafe unable to open internal link due to host name added before URL

Something like this http://172.31.18.124:50963/r9wBR_VsW/https://xyz.com

what should we do so that Page loads with out any issues  even after adding Testcafe hostname ?

**Comment by miherlosev** [comment]
Hi @Orchardeye 

TestCafe uses an [URL-rewritten proxy](https://github.com/devexpress/testcafe-hammerhead) internally. It means TestCafe processed all resource links to pass its content through proxy.

If the tested page work incorrectly with TestCafe, it's a bug. Could you please provide a small example to reproduce the problem on our side?

**Comment by Orchardeye** [comment]
1. Our application is on cloud, 
2. Sales force is used for authentication
3. After authentication sales force will redirect to actual application

Initial Internal link something like this: https://full-myxxxxxx.cs93.force.com/s/login/?startURL
After authentication it is redirected to link something like this: https://console.vpstage.xxxxcloud.com/xxxx/clusters

Issue I'm facing:
TestCafe is adding its host and port number before the link due to which Login page is not loaded

Ex:  http://172.31.18.124:50963/r9wBR_VsW/https://full-myxxxxxx.cs93.force.com/s/login/?startURL

I even tried with TestCafe Studio the result is same, I'm Blocked here

**Comment by Orchardeye** [comment]
Hi, is there a way get this issue resolved?

**Comment by AlexKamaev** [comment]
TestCafe runs its own proxy server, so these host and port are correct. These options should not cause an issue. If something does not work, it can be a bug, however, we cannot say it precisely. For further help we need to research your project in detail, so please provide us with access to your project to reproduce the issue.
If you cannot share credentials here, you can send it in a private email at support@devexpress.com

**Comment by AutomationTester143** [comment]
I am also facing this issue and I have report separate bug for this.
