### ISSUE TITLE
[Testcafe Bug] - Weird behaviour because of hostname and port before URL

### ISSUE THREAD

**Issue by VldSqt** [DevExpress/testcafe#4131]
I have a simple test that is supposed to do a login and a logout on a local web app, the problem is that i get CORS errors in my console while running the test: "has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

I tried the --disable-web-security option but it returns an other error:  "failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec." 

I believe this is an issue because of the hostname and port that is before the site's URL.

### What is your Test Scenario?
login with an username and password provided by me
 
### What is the Current behavior?
Site does pass the login phase, but i cannot interract with the site ( cannot click on any element because of CORS )  
 
### What is the Expected behavior?
 The test is supposed to succesful login and logout out of the webpage 
 

<details>
<summary>Your complete test code (or attach your test files):</summary>

 Paste your test code here:
Test.js
import { Selector } from 'testcafe'
 //the variables for the selector
const username = Selector('UsernameSelector');
const password = Selector('PasswordSelector);
const submit = Selector('SubmitSelector');
const menu = Selector(''MenuSelector');
const logout= Selector(''logoutSelector');

fixture `Getting Started`
.page ('http://websiteurl/login')

test('My first test', async t => {
login(t)
    await t
        .wait(1000)
});
------------------------------------------ 
Login.js

const username = Selector('UsernameSelector');
const password = Selector('PasswordSelector);
const submit = Selector('SubmitSelector');
const menu = Selector(''MenuSelector');
const logout= Selector(''logoutSelector');

export async function login(t){
await t

 .click(username)
    .typeText(username,'username')
      .expect(username.value).eql('username')
       .wait(1000)

  .click(password)
    .typeText(password,'password')
      .expect(password.value).eql('password')
       .wait(1000)

  .click(submit)
    .wait(1000)

  .click(menu)
    .wait(15000)
  .click(logout)
    .wait(15000)

}

### Steps to Reproduce:
 Describe what we should do to reproduce the behavior you encountered.

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                      1.4.0        
* node.js version:                    8.9.1
* command-line arguments:  testcafe "chrome -incognito --disable-web-security" test.js -q
* browser name and version: Browser: Version 75.0.3770.90 (Official Build) (64-bit)
* platform and version:          Windows 7

**Comment by VldSqt** [comment]
Current Behaviour: Site does the login phase, but is unable to use elements from the site ( press the logout button ) 
Expected Behaviour: the test does the test for the login and logout without the errors

**Comment by miherlosev** [comment]
Hi @VldSqt 

According to the error message, I assume your application uses [ES6 modules](https://exploringjs.com/es6/ch_modules.html). We are currently working on support for this feature.
If you can provide an example which I can run on my side,  I will be able to find the cause of the problem that you found.
