### ISSUE TITLE
Skip tests that caused browser DNRs when restarting browsers

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#4133]
### What is your Test Scenario?
Test heavy pages in low-performance environments.

### What are you suggesting?
From https://github.com/DevExpress/testcafe/issues/1815#issuecomment-517718875:
 - When a browser enters the Do Not Respond state during a test, restart the browser but skip the test caused the failure and run the next test.

**Comment by jbradenclickfunnels** [comment]
Hello,

Using 1.15.2, we are still experiencing freezes during our test executions. It doesn't happen all the time and we can't get log output because it's frozen, not just failing a test. Since this is an issue ranging back to 2017, could DevExpress please prioritize this higher?

Thanks,

**Comment by VasilyStrelyaev** [comment]
Thank you for telling us about your experience. We will take this information into account during our future planning.

Regarding the browser freezing: if it is possible to reproduce it with a sample that we can run on our side, please create a separate bug report and attach this sample so that we could take a look.

**Comment by jbradenclickfunnels** [comment]
Unfortunately for us, it's not consistent on what test or when it decides to freeze. We are using CircleCI for our execution. All we can tell is it happens mainly towards the end of our runs and we have ~54 scripts so far in our sanity tests. Our sanity tests are just navigating to a page, asserting the URL and a header on the screen. So nothing funky or complex. Someone should already have our repo for another issue, if you want to use that to try and replicate.

**Comment by VasilyStrelyaev** [comment]
Unfortunately, we cannot process multiple inquiries posted within the same GitHub issue. If you would like us to investigate the behavior you encountered, please create a separate issue with a reproducible example.

**Comment by Artem-Babich** [comment]
After additional research, we came to the conclusion that skipping hanging tests can be confusing and lead to clustering of tests with unstable behavior. Instead, I would rather suggest finding the real issue with the browser DNR.
