### ISSUE TITLE
Allow access to elements under the status panel in debug mode.

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#4136]
### What is your Test Scenario?
Enable debug mode and try to pick an element under the TestCafe status panel.

### What are you suggesting?
When debug mode is enable, the status panel no longer hides when the cursor enters its area. We should provide a way to allow accessing elements that are below the status panel in debug mode.

Options:
 - Add a button to hide/close the panel
 - Allow docking the panel to different sides of the page
 - Allow the switch the panel to floating mode

### What alternatives have you considered?
`$('#root-hammerhead-shadow-ui').style.visibility = 'hidden'` in DevTools.

**Comment by rob4629** [comment]
I know this isn't on the roadmap, but do you think it might be looked at this quarter/year?

**Comment by AlexSkorkin** [comment]
@rob4629,
Anyone can look into it and submit a PR.

**Comment by dennisdupont** [comment]
Here is my workaround:

First define a ClientFunction to turn off testcafe and hide the tools:
```
const hideTestCafeTools = ClientFunction(() => {
        window["%testCafeCore%"].disableRealEventsPreventing();
        window["%hammerhead%"].shadowUI.root.style.display = 'none';
});
```

Then call that function in your test script before calling debug:
```
        await hideTestCafeTools();
        await t.debug();

```

**Be aware that this uses undocumented features of testcafe and may break in future releases**

**Comment by rob4629** [comment]
I find that running tests in _"headed"_ mode, also occasionally can't find elements (due to being under the TestCafe Tools). We mostly run in `headless` for our CI, but also target a wide range of browsers during our overnight regression runs.

(_Such as Safari, Opera, Edge etc, where we can't specify headless_).
