### ISSUE TITLE
[docs] Add instructions of debugging TestCafe itself in the official documentation

### ISSUE THREAD

**Issue by tenjaa** [DevExpress/testcafe#4141]
Hey,
I have to admit that we had a major issue blocking us for longer than I want to admit (days) for a reason I neither want to tell you (copy paste mistake)...
What helped in the end was the `DEBUG` env variable you can set to debug testcafe itself.
https://github.com/DevExpress/testcafe/wiki/Debugging-TestRun
Maybe you want to consider to mention it briefly in the debugging section (or somewhere else) of the official documentation?
We took too long until we found it buried in the Github wiki.

**Comment by helen-dikareva** [comment]
Thank you for your suggestion.
We'll consider including this topic in the ['Debug Tests'](https://devexpress.github.io/testcafe/documentation/recipes/debug-tests/) section of the TestCafe site.

**Comment by AndreyBelym** [comment]
We discussed this suggestion and decided that it's better to implement a more user-friendly logging mechanism first - https://github.com/DevExpress/testcafe/issues/4001.
