### ISSUE TITLE
[docs] Highlight code in docs

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe#4143]
https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/inject-scripts-into-tested-pages.html

As javascript:
![image](https://user-images.githubusercontent.com/5373460/62933378-bc32cc80-bdca-11e9-990f-7e96c4f03817.png)

As json:
![image](https://user-images.githubusercontent.com/5373460/62933426-d40a5080-bdca-11e9-9da5-b4299749278f.png)

As typescript:
![image](https://user-images.githubusercontent.com/5373460/62933462-e5535d00-bdca-11e9-878e-52663cd3c70b.png)

**Comment by titerman** [comment]
JavaScript:
<img width="675" alt="Screenshot 2021-05-09 at 02 59 40" src="https://user-images.githubusercontent.com/43554315/117556527-9bb4a680-b072-11eb-8aa7-03767f628283.png">
JSON:
<img width="668" alt="Screenshot 2021-05-09 at 03 00 58" src="https://user-images.githubusercontent.com/43554315/117556545-ca328180-b072-11eb-887a-f9285d1db093.png">

fixed on testcafe.io
