### ISSUE TITLE
Embedding screenshot in html report for failure test cases

### ISSUE THREAD

**Issue by krishnakanth19** [DevExpress/testcafe#4151]
### What is your Test Scenario?
 When a test case fails, it is capturing screenshot and showing reason in the HTML report. But it is not appending or creating any link to the particular screenshot.

### What are you suggesting?
 Append screenshot for failed test cases along with error.

### Additional context
Is it possible to integrate 'beautify reports' or 'Extent reports' with test cafe? Because they provide reports with screenshot and opensource too.

**Comment by devmondo** [comment]
maybe I am wrong but you already have this `testRunInfo ` in 
https://devexpress.github.io/testcafe/documentation/extending-testcafe/reporter-plugin/reporter-methods.html#testruninfo-object

if you create custom reporter, you can append that information in your output
also, make sure to understand the screenshot options
https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#screenshots

we have custom reporters, and we do this in all of them to output custom info.

hope this helps :)

**Comment by miherlosev** [comment]
> When a test case fails, it is capturing screenshot and showing reason in the HTML report.
 

This behavior is determined by the [takeScreenshotOnFails](https://devexpress.github.io/testcafe/documentation/using-testcafe/configuration-file.html#takescreenshotsonfails) option. If a test fails, TestCafe takes a screenshot of the page at the moment when the problem event occurs (assertion failed, an unhandled error occurred, etc.)
 
TestCafe doesn't have a built-in HTML reporter (see a list of built-in reporters [here](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/reporters.html)).
If you develop the HTML reported plugin yourself, you can find information about screenshots in the [testRunInfo](https://devexpress.github.io/testcafe/documentation/extending-testcafe/reporter-plugin/reporter-methods.html#testruninfo-object) object.
If you use the third party HTML reporter, I suggest you contact its developers directly .
