### ISSUE TITLE
Allow to reevaluate asynchronous custom properties and results of asynchronous methods of Custom Request hooks

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#4159]
It should support the [Smart assertion query mechanism](https://devexpress.github.io/testcafe/documentation/test-api/assertions/#smart-assertion-query-mechanism).

When a custom request hook has a property that depends on an asynchronous hook state, you had to use some manual timeout, since this property cannot be reevaluated by our assertions.

**Comment by Klaster1** [comment]
Any updates on this? My app uses Web Sockets to transfer data, which are mocked by a custom hook for tests, so the default "page loaded" awaiter is not always enough.

**Comment by AndreyBelym** [comment]
Currently we have no updates about this feature. We keep the issue opened and consider discussing and implementing in the future.

**Comment by AlexKamaev** [comment]
We discussed the issue with the team and decided to close it. We do not have plans to implement this functionality, and the issue is not popular among TestCafe users.
