### ISSUE TITLE
Add to 'TestRunInfo' object information about recorded videos

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#4160]
https://devexpress.github.io/testcafe/documentation/extending-testcafe/reporter-plugin/reporter-methods.html#testruninfo-object

Add the following properties:
 - [ ] `testRunInfo.videos: Video[]`:

```ts
interface TestRunInfo.Video {
   testRunId: string;
   path: string; // absolute path
}
```

Also, add enhance the `TestRunInfo.Screenshot` interface:
```ts
interface TestRunInfo.Screenshot {
  testRunId: string;
}
```

**Comment by dcharan** [comment]
Any update on this. I am trying to build a custom report and I cant find a way to get video path to attach the video.

**Comment by miherlosev** [comment]
At present, this enhancement is not implemented.
The features that we are planning to implement are listed on the [Roadmap](https://devexpress.github.io/testcafe/roadmap/) page. The current feature is not on this list. I'm afraid I cannot provide you with any time frames as to when it will be implemented.

If this enhancement is very important for you, the PR is greatly appreciated.
