### ISSUE TITLE
.httpAuth not adding basic auth header to request

### ISSUE THREAD

**Issue by shannon-fluellen-aurea** [DevExpress/testcafe#4161]
I've tried every way I can find and nothing results in basic auth being added to the request. Any help would be greatly appreciated. Below is the test and the log output:

```js
import { Selector } from 'testcafe';
import { RequestLogger } from 'testcafe';

const logger = RequestLogger('http://localhost:8080/document/create.jspa?containerType=2020&containerID=1', {
	logRequestHeaders: true
});

fixture `Getting Started`
    .page `http://localhost:8080/document/create.jspa?containerType=2020&containerID=1`;

test
	.httpAuth({
        username: 'username',
        password: 'password'
    })
	.requestHooks(logger)
	('My first test', async t => {
    await t.expect(logger.contains(record => record.response.statusCode === 302)).ok();

     const logRecord = logger.requests[0];

     console.log(logRecord); 
     console.log(logRecord.request.headers);  
});

```

```
Running tests in:
 - Chrome 76.0.3809 / Mac OS X 10.14.5

 Getting Started
{ id: 'YOQTjdiaC',
  testRunId: 'A2jNLCeiv',
  userAgent: 'Chrome 76.0.3809 / Mac OS X 10.14.5',
  request:
   { url:
      'http://localhost:8080/document/create.jspa?containerType=2020&containerID=1',
     method: 'get',
     headers:
      { host: 'localhost:8080',
        connection: 'keep-alive',
        'upgrade-insecure-requests': '1',
        'user-agent':
         'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36',
        accept:
         'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
        'accept-encoding': 'gzip, deflate',
        'accept-language': 'en-US,en;q=0.9' } },
  response: { statusCode: 302 } }
{ host: 'localhost:8080',
  connection: 'keep-alive',
  'upgrade-insecure-requests': '1',
  'user-agent':
   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36',
  accept:
   'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
  'accept-encoding': 'gzip, deflate',
  'accept-language': 'en-US,en;q=0.9' }
 ✓ My first test


 1 passed (4s)
```

**Comment by Farfurix** [comment]
@shannon-fluellen-aurea 

Hello,

If I understand it correctly, you have an unsuccessful testcase with "Basic Auth".
I tried to reproduce the issue in the following example, but it passed successfully:
**server.js**
```js
const http = require('http');

const server = http.createServer(function(req, res) {
    console.log(req);

    const auth = req.headers['authorization'];
    console.log("Authorization Header: ", auth);

    if(!auth) {
        res.statusCode = 401;
        res.setHeader('WWW-Authenticate', 'Basic realm="Secure Area"');

        res.end('<html><body>!auth</body></html>');
    }

    else if(auth) {
        const tmp = auth.split(' ');

        const buf = new Buffer(tmp[1], 'base64');
        const plain_auth = buf.toString();

        const creds = plain_auth.split(':');
        const username = creds[0];
        const password = creds[1];

        if((username == 'test') && (password == 'test')) {
            res.statusCode = 200;
            res.end('<html><body>OK</body></html>');
        }
        else {
            res.statusCode = 401;
            res.setHeader('WWW-Authenticate', 'Basic realm="Secure Area"');

            res.end('<html><body>NOT OK</body></html>');
        }
    }
});

server.listen(8080, function() { console.log("http://localhost:8080/"); });
```

**test.js**
```js
fixture `Fixture`
    .page `http://localhost:8080/`;

test
    .httpAuth({
        username: 'test',
        password: 'test'
    })
    ('Auth test', async t => {
        await t
            .wait(1000000)
            .expect(true).ok();
    });
```

Could you please provide us with your "Basic Auth" sample project (or a public URL with required credentials)?

**Comment by shannon-fluellen-aurea** [comment]
Hi @Farfurix thanks for taking a look at this for me! I'm working on a company project so I don't really have anything I can share as far as that goes. Can you please help me understand why my logger is showing no BasicAuth header in the request? I tested my application using Postman's BasicAuth functionality and it's able to use that to directly access login protected pages without redirection to the login page itself which has led me to believe that Testcafe is not including the basic auth header in my test. Do you have any reason to believe the .httpAuth feature is actually working in the test file I provided? Thanks again!

**Comment by LavrovArtem** [comment]
Hi @shannon-fluellen-aurea, you can debug your test by logging all resources of your page via `RequestLogger` in console.
However, we are not able to find the cause of the issue without researching a simple example showing the problem. Could you please correct the example @Farfurix provided above?

**Comment by lynners** [comment]
I thought I was running into this same issue @shannon-fluellen-aurea but I checked our server config we are using digest authentication not basic. I see this might have been a request at one time? https://github.com/DevExpress/testcafe/issues/2630

I'm wondering if there is any workaround for this.

**Comment by shannon-fluellen-aurea** [comment]
> Hi @shannon-fluellen-aurea, you can debug your test by logging all resources of your page via `RequestLogger` in console.
> However, we are not able to find the cause of the issue without researching a simple example showing the problem. Could you please correct the example @Farfurix provided above?

Hi @LavrovArtem I'm not sure exactly what you're asking me to do, can you please explain more?

**Comment by Farfurix** [comment]
@shannon-fluellen-aurea 

Hello,

We cannot examine this issue without any example. Could you please provide us with a sample project (or some public URL)?
