### ISSUE TITLE
Unable to use axios in the initialization client script

### ISSUE THREAD

**Issue by noamaankhan** [DevExpress/testcafe#4163]
### What is your Test Scenario?
I m trying to make REST call from my client script but using 'fetch' doesnt help since I always run into CORS issue (see 222 response for the call in console). So I injected 'axios' to give it a try. 
 
### What is the Current behavior?
Testcafe fails with the following error:

`An error occurred in the 'axios' module injected into the tested page. Make sure that this module can be executed in the browser environment.
Error details: ReferenceError: module is not defined
Browser: Chrome 76.0.3809 / Mac OS X 10.14.5`
 
### What is the Expected behavior?
axios to work in my client script since it is supported in browser environment.
 

### Your Environment details:
 
* testcafe version:                   1.4.0
* node.js version:                    v12.7.0
* command-line arguments:  testcafe chrome ./src/test.js

**Comment by aleks-pro** [comment]
Hello @noamaankhan ,

I have managed to reproduce the issue. We will research it. As a workaround you can inject the axios module in the following way:
```JS
...
.clientScripts({ path: 'node_modules\\axios\\dist\\axios.js'})
...
```

**Comment by noamaankhan** [comment]
Thank you for looking into this and responding promptly. I tried injecting the script the way you described but I got the following error: 
`ERROR Cannot load a client script from node_modules\axios\dist\axios.js`

**Comment by aleks-pro** [comment]
@noamaankhan The path to the `axios.js` file should be relative to the test location. For example, if your test is in the `src` folder and this folder is a sibling for the `node_modules` folder, you need to use the following `path` value: '..\\node_modules\\axios\\dist\\axios.js'
 
PS: I've created a separate [issue](https://github.com/DevExpress/testcafe/issues/4170) for this scenario. You can follow it to be aware of our progress.
