### ISSUE TITLE
Can we automate mobile web using testcafe 

### ISSUE THREAD

**Issue by soumya-gobant** [DevExpress/testcafe#4164]
HI,
I just want to know about the mobile web automation, As per my knowledge we can't proceed with mobile app automation with testcafe and we handle mobile web automation.

**Comment by Farfurix** [comment]
@soumya-gobant 

Hello,

With TestCafe Framework, you are able to test your mobile applications. Here are some links to help you get started with mobile testing:
1. [Continuous Integration](https://devexpress.github.io/testcafe/documentation/continuous-integration/)
2. [Test on Remote Computers and Mobile Devices](https://devexpress.github.io/testcafe/documentation/recipes/test-on-remote-computers-and-mobile-devices.html)
3. [Using Chrome Device Emulation](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/using-chrome-device-emulation.html)

This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - a platform for users to ask and answer questions.
We try to keep the GitHub issues tracker for bugs and feature requests only.
