### ISSUE TITLE
Request hook not methods not called at all

### ISSUE THREAD

**Issue by bhassane73** [DevExpress/testcafe#4173]
### What is your Test Scenario?
Constructor , onRequest, onREesponse are not called at all. I followed instructions in https://github.com/DevExpress/testcafe/issues/3794 but still this does not help.

My code:

```js
import { Selector, RequestHook } from 'testcafe';
import Colors from 'colors';

class MyRequestHook extends RequestHook {

    constructor (requestFilterRules, responseEventConfigureOpts) {
      
        console.log('Constructing ... '); // displayed in console
        super(requestFilterRules,  responseEventConfigureOpts);
        process.env.NODE_TLS_REJECT_UNAUTHORIZED = 1; // Removing this line does not fix the issue
        console.log('Constructing finished'); // not displayed in console
            
    }
     
    async onRequest(event) {
        console.log('OnRequest ...');        // not displayed in console
    }

    async onResponse(event) {
        console.log('onResponse ...');        // not displayed in console
    }
}

// I don't want to give the complete URL but I can say it contains '/', '-' and '.' characters so I escpated all '/' with back slash
const customHook = new MyRequestHook(/https:\/\/busi......com\/ui\/v1/, 
    {
      includeHeaders: true,
      includeBody: false
    }
);
    
fixture `New Fixture`
    .page `https://www.google.com`;
    
test(`New Test`, async t => {
       console.log('START'); // displayed in console
       await t
        .maximizeWindow()
        .addRequestHooks(customHook);
        console.log('DONE'); // displayed in console
       
});
```

 
### Current behavior
I execute test cafe in Windonw 10 command line: testcafe chrome:headless testRequestHooks.js
Result:
C:\Users\TestCafeStudio>testcafe chrome:headless testRequestHooks.js
Using locally installed version of TestCafe.
\
Constructing ...
 Running tests in:
 - HeadlessChrome 76.0.3809 / Windows 10.0.0
 New Fixture
START
DONE
 √ New Test
 1 passed (4s)

You can stop writing and start recording. Check out our commercial testing platform – now with a fully integrated visual test recorder: https://devexpress.com/testcafe-studio
 
### Environment details:

* testcafe version:                   1.3.2
* node.js version:                    11.2.0
* command-line arguments:   testcafe chrome:headless testRequestHooks.js
* browser name and version: Version 76.0.3809.100 (Official Build) (64-bit)
* platform and version:          Windows 10

#

**Comment by LavrovArtem** [comment]
Hi @bhassane73,

Please make sure that the regular expression passed to `MyRequestHook` is correct. For instance, you can use a string instead of RegExp. Also, could you please open the Network tab in Chrome developer tools to make sure that this resource is loaded?

**Comment by bhassane73** [comment]
Thank you for quick answer. My resource is not loade at all in Chrome.
This is odd, I tried exactly the sample in https://github.com/DevExpress/testcafe/issues/3794 and it woks fine. Then I just replaced 'https://devexpress.github.io' by my own URL but i still does not work. My URL works fine with POSTMAN and returns a valid JSON payload. I am wondering if a REST api is supported.

**Comment by LavrovArtem** [comment]
The information you provided is not sufficient to find the cause of the issue. Could you please provide a page or a small example so that we can reproduce it on our side?

**Comment by bhassane73** [comment]
I suspect some security issue. However I could resolve the problem using node http package import https from 'https'; ....
