### ISSUE TITLE
Odd behavior with browser connection

### ISSUE THREAD

**Issue by Vicnovais** [DevExpress/testcafe#4174]
### What is your Test Scenario?
I am trying to run some default CRUD test cases on my enterprise application using TestCafe 1.1.0 (also tried the newest version 1.4.0, but no success)
 
### What is the Current behavior?
As of the browser connects, it simply hangs without any useful log.
This is happening intermittently, and also there's a strange behavior:
1) When I am using my virtual machine (Windows Server 2012), TestCafe works all the times
2) When a colleague uses his virtual machine (Windows Server 2016) or his host machine (Windows 10), TestCafe never works (stuck browser connection)
PS: Sometimes the log shows some javascript errors regarding Require.JS library, as we use it to allow javascript modules, but other times nothing is shown.
PS²: Sometimes TestCafe shows the browser disconnect error, and other times it just gets stuck forever

Note that this happens in every browser available to us: Chrome, Firefox and IE
 
### What is the Expected behavior?
The browser must not hang and it should complete the test cases.
 
### What is your web application and your TestCafe test code?
We are using IIS as the server to deliver our ERP.
The first test case is always the login page, so we can validate it is working, then the browser reloads and goes to the first CRUD test.
Note that the browser hanging sometimes occur on login and sometimes when the page is reloaded.
 
This is our login test:
```js
     async login(data) {
        const loginButton = await this.getSelector("login"); //Here we use our framework as a middleware to TestCafe, to get the login button
    
        await this.fillData(data);
        await t.click(loginButton);

        return this;
    }

    async baseLoginTest() {
        let loginData = this.getInsertData()[0]; //We get the data from an excel sheet

        test(loginData.Id, async t => {
                await this.login(loginData);
            });
    }
```

Here is our CRUD test:
```js
import FasePage from "./page";
import TestBuilder from "../_Default/test.builder";
import config from "../../config";

let newRoute = `${ config.url }/Edit`,
    testBuilder = new TestBuilder(FasePage, newRoute);

fixture 
    .disablePageReloads `Fase`
    .page `${ config.url }/?lang=${ config.lang }`;

testBuilder.buildDefaultTest();
```

And here is our test builder to make the CRUD tests dynamically:
```js
buildDefaultTest() {
        LoginPage.baseLoginTest();
        
        this.page.getInsertData().forEach(data => { //Data comes from excel sheet
            test.before(async t => {
                t.ctx.selectedProfile = "";
            })
            (data.Id, async t => {
                await this.addRequestHook(t);
                let defaultTest = new DefaultTest(this.page, data, this.logger);
                await defaultTest.startCreateTest();
                this.insertedEntities.push({ testId: data.Id, entityId: defaultTest.requestInterceptor.getBatchCreateEntityId(this.newRoute) });
                await t.removeRequestHooks(this.logger);
            });
        });

        this.page.getUpdateData().forEach(data => { //Data comes from excel sheet
            test(data.Id, async t => {
                    await this.addRequestHook(t);
                    if (!this.insertedEntities.length) throw new Error("There are no inserted entities to update.");
                    let defaultTest = new DefaultTest(this.page, data, this.logger);
                    await defaultTest.startUpdateTest(this.insertedEntities);
                    await t.removeRequestHooks(this.logger);
                });
        });

        this.page.getDeleteData().forEach(data => { //Data comes from excel sheet
            test(data.Id, async t => {
                    await this.addRequestHook(t);
                    if (!this.insertedEntities.length) throw new Error("There are no inserted entities to delete.");
                    let defaultTest = new DefaultTest(this.page, data, this.logger);
                    await defaultTest.startDeleteTest(this.insertedEntities);
                    await t.removeRequestHooks(this.logger);
                });
        });
    }
```
 
### Your Environment details:
 
* testcafe version:                   1.1.0
* node.js version:                    8.12.0 (My workstation, where TestCafe works) 10.16.2 (My colleague workstation, where TestCafe does not work)
* command-line arguments:   --speed 0.8 --page-load-timeout 20000
* browser name and version:  IE 11, Chrome 76, Firefox 68
* platform and version:           Windows Server 2012 (Mine) /2016, Windows 10 (Colleague)

### Additional Info:
Do I need to allow any ports on windows firewall? As of TestCafe uses a proxy to open the page, can it be a network issue? Can it be an issue with the node version?

**Comment by Vicnovais** [comment]
Just updating: the problems seems to be the node version, I've downgraded my colleague's node version to 8.12 and it seems to work.
Apparently node 10 doesn't fit with TestCafe.

**Comment by miherlosev** [comment]
Hi @Vicnovais 

I am afraid this information is not sufficient to find the cause of the issue. Could you please provide a full example so that we can reproduce it on our side?
