### ISSUE TITLE
Repository with executable examples

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#4175]
This issues should help us to determinate necessary of the repository with executable examples.
Please add here use cases for examples.

**Comment by miherlosev** [comment]
https://github.com/DevExpress/testcafe/issues/4140#issuecomment-522620075

**Comment by AndreyBelym** [comment]
Wait for a file download: https://stackoverflow.com/questions/57582108/testcafe-example-to-assert-file-download

**Comment by AndreyBelym** [comment]
Use Request Logger to log REST API calls: https://stackoverflow.com/questions/52745697/requestlogger-not-intercepting-all-http-requests

**Comment by AndreyBelym** [comment]
How to upload a file with TestCafe: https://stackoverflow.com/search?q=%5Btestcafe%5D+Upload

**Comment by miherlosev** [comment]
Windows and basic authentication example - https://supportcenter.devexpress.com/internal/ticket/details/T809667

**Comment by AndreyBelym** [comment]
A hot topic is avoiding the issue with [multiple windows](https://github.com/DevExpress/testcafe/issues/912), but I don't know if we can provide an example that will work for most cases.

**Comment by Farfurix** [comment]
Debug any "sibling" results using custom `outerHTML` `Selector` property: https://www.devexpress.com/Support/Center/Question/Details/T811021/i-am-some-how-not-able-to-get-hold-of-an-element-please-help

**Comment by Farfurix** [comment]
Check if the document in the `iframe` is loaded using `ClientFunction`:
https://stackoverflow.com/questions/57787520/interacting-with-iframe-with-empty-src-attribute

**Comment by miherlosev** [comment]
How to reload web page - https://stackoverflow.com/questions/57851542/testcafe-page-reload

**Comment by AndreyBelym** [comment]
We decided that it is time to create a repository for examples. When we do it, all example suggestions should be submitted as issues to this separate repository.

**Comment by AndreyBelym** [comment]
The repository for examples is located here: https://github.com/DevExpress/testcafe-examples. Please add your ideas to https://github.com/DevExpress/testcafe-examples/issues/2.
