### ISSUE TITLE
SyntaxError: Unexpected token function - on docker (ubuntu16:4) trying to run tests

### ISSUE THREAD

**Issue by ngrossi** [DevExpress/testcafe#4179]
SyntaxError: Unexpected token function

trying to run tests in a docker image from ubuntu:16:4

Post stage
+ PIPELINE_ENV=devx
+ PIPELINE_USER=E2euser
+ testcafe chrome:headless 'Tests/**/*.js'
/usr/lib/node_modules/testcafe/lib/cli/cli.js:64
async function runTests(argParser) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at loader (/usr/lib/node_modules/testcafe/lib/cli/index.js:18:5)
[Pipeline] slackSend

Team: before filing this ticket I were unable to find a similar ticket, please let me know if this is a known issue or it is something that we are not able to identify. I can provide the docker file and jenkinsfile if necessary.  Please let me known

**Comment by ngrossi** [comment]
docker file that it is working 

#Step 1
#Dockerfile to build an image for different versions of chrome
#Pull ubuntu base image
FROM ubuntu
MAINTAINER Qxf2 Services

#Step 2
#Essential tools and xvfb
RUN apt-get update && apt-get install -y \
    software-properties-common \
    unzip \
    curl \
    wget \
    xvfb

#Step 3
#Chrome browser to run the tests
ARG CHROME_VERSION=68.0.3440.84
RUN curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add \
      && wget https://www.slimjet.com/chrome/download-chrome.php?file=lnx%2Fchrome64_$CHROME_VERSION.deb \
      && dpkg -i download-chrome*.deb || true
RUN apt-get install -y -f \
      && rm -rf /var/lib/apt/lists/*

#Disable the SUID sandbox so that chrome can launch without being in a privileged container
RUN dpkg-divert --add --rename --divert /opt/google/chrome/google-chrome.real /opt/google/chrome/google-chrome \
        && echo "#! /bin/bash\nexec /opt/google/chrome/google-chrome.real --no-sandbox --disable-setuid-sandbox \"\$@\"" > /opt/google/chrome/google-chrome \
        && chmod 755 /opt/google/chrome/google-chrome

#Step 4
#Node.js
RUN apt-get update && apt-get install -y nodejs npm

#Step 5
#TestCafe
RUN npm install -g testcafe testcafe-reporter-xunit \
    && npm cache clean --force \
    && rm -rf /tmp/*

WORKDIR /usr/src/app

**Comment by ngrossi** [comment]
Is that error be related to node js was not installed?

**Comment by AndreyBelym** [comment]
Ubuntu 16.04 (Xenial) has only Node.js 4.2.6 in the repository: https://packages.ubuntu.com/xenial/nodejs. This version is obsolete since April 2018: https://github.com/nodejs/Release#end-of-life-releases. 

TestCafe needs Node.js 8.0.0 or newer: https://github.com/DevExpress/testcafe/blob/master/package.json#L19. You can use NVM to install a supported Node.js version on Linux: https://github.com/nvm-sh/nvm

**Comment by ngrossi** [comment]
Perfect Andrey I will consider that info!
