### ISSUE TITLE
Injected Client Script only works the first time in Live Mode

### ISSUE THREAD

**Issue by testorangemac** [DevExpress/testcafe#4183]
### What is your Test Scenario?

 I like to inject a Client Script and use it in Live Mode
### What is the Current behavior?

 The injection works when TestCafé starts the Live Mode and runs the test for the first time, but a second time the element is not found and an error is produced:
```
 ReferenceError: TestingLibraryDom is not defined
```
### What is the Expected behavior?

Injection keeps working in combination with Live Mode

### Steps to Reproduce:

1. Update config file and add:
```json  
"clientScripts": [
    "./node_modules/@testing-library/dom/dist/@testing-library/dom.umd.js"
  ],
```
2. Import methods:
```
import { getByTestId } from "@testing-library/testcafe";
```
See https://testing-library.com/docs/testcafe-testing-library/intro  for other queries to be used

3. Call method:
```js
  async startBtn() {
    await t.click(getByTestId("btn"));
  }
```

Someone had a similar issue: https://github.com/testing-library/testcafe-testing-library/issues/28
so we upgraded the testcafe-testing-library to 3.0.0 as suggested, but the problem unfortunately still persisted.
 
### Your Environment details:
 
* testcafe version:   1.4.1                
* testcafe-testing-library: 2.1.1 and 3.0.0
* node.js version:         10.5.0           
* command-line arguments:  -L 
* browser name and version: All 
* platform and version:  Win10        
* other:

**Comment by AndreyBelym** [comment]
Thank you for your report, I've reproduced the issue. We will try it in the next development sprint.

**Comment by benmonro** [comment]
@AndreyBelym  was this addressed?
