### ISSUE TITLE
Some iframe fields not being detected as filled

### ISSUE THREAD

**Issue by ampc** [DevExpress/testcafe#4187]
### What is your Test Scenario?
Fill payment card information on braintree iframes. 
### What is the Current behavior?
It fills the correct fields but some fields are not being detected as filled. 
### What is the Expected behavior?
Detect all fields as filled. 
### What is your web application and your TestCafe test code?
Web application:
https://cascais-pp.mobime.io
https://cascais-pp.mobime.io/product/TU9CSV9CVVNDQVNfREFJTFk=

Code:
https://github.com/ampc/testcafe-iframe
Page object :https://github.com/ampc/testcafe-iframe/blob/master/tests/page_objects/store/StorePage.ts
Test code: https://github.com/ampc/testcafe-iframe/blob/master/tests/specs/store/store.spec.ts

Check  `tests/specs/store/store.spec.ts`

<summary>Your complete test report:</summary>

```
➜ npx testcafe chrome tests/specs/store/store.spec.ts
 Running tests in:
 - Chrome 74.0.3729 / Linux 0.0.0

 Store
 ✖ Subscribe without saving card information

   1) Cannot obtain information about the node because the specified selector does not match any node in the DOM tree.

       > | Selector('div.popUp-container div div#main-messages')

      Browser: Chrome 74.0.3729 / Linux 0.0.0

         18 |  const expirationDate = "225"; //the system includes the zero for the month
         19 |
         20 |  await StorePage.subscribeProduct(creditCard, cvc, expirationDate);
         21 |  await t
         22 |    .expect(StorePage.message.innerText)
       > 23 |    .contains("A subscrição foi efetuada com sucesso!");
         24 |}).meta("regression", "true");
         25 |

         at Object.<anonymous> (/home/ceiia.com/antonio.carvalho/repos/automated_tests/iframe_error/tests/specs/store/store.spec.ts:23:6)
         at fulfilled (/home/ceiia.com/antonio.carvalho/repos/automated_tests/iframe_error/tests/specs/store/store.spec.ts:4:58)



 1/1 failed (44s)
```
</details>

<details>
<summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/284907/63509832-0a378680-c4d5-11e9-81ae-2a52478862b6.png)

</details>

### Steps to Reproduce:

1. Clone repo
2. Execute Run with `npx testcafe chrome tests/specs/store/store.spec.ts`
 
### Your Environment details:
 
* testcafe version:                  1.4.1
* node.js version:                    10.16.3
* browser name and version: Chrome 74
* platform and version:           Ubuntu Linux 16.04

**Comment by miherlosev** [comment]
Hi @ampc 

Thank you for the detailed description. I've reproduced the problem.

**Comment by pradeepdewda-okta** [comment]
Is there any update on this ?

**Comment by AlexSkorkin** [comment]
Once we get any results, we will post them here.
