### ISSUE TITLE
Test controller from Fixture passing to TESTS

### ISSUE THREAD

**Issue by avi0711** [DevExpress/testcafe#4190]
Hello I am using one condition( if else loop) to use different URLs based on the env. I am mentioning this in fixture.beforeEach(..) and want to hit the URLs in TESTS based on the outcome

fixture('Verifying')
       .beforeEach(async t =>{
        console.log("Execution Started ");
        const args = minimist(process.argv.slice(2));
        var environment = args.env;
        if(environment == 'Test')
        {
            t.ctx.Connectionstring=config.Test.Connectionstring;
            t.ctx.Url=config.Test.Url;
        }
        else if(environment == 'Stage')
        {
            t.ctx.Connectionstring=config.Stage.Connectionstring;
            t.ctx.Url=config.Stage.Url;
        }
        else if(environment == 'Prod')
        {
            t.ctx.Connectionstring=config.Prod.Connectionstring;
            t.ctx.Url=config.Prod.Url;
        }

 test.page(t.ctx.Url)
    ("TC1 - Report Batches", async t => {

    await t

    .typeText(lgpage.username, 'abc)
    .typeText(lgpage.password,'abc')
    .click(lgpage.submit)
})

test.page(t.ctx.Url) doesnot work. Even if i give fixture.page(t.ctx.Url) doesnot work both the time it is giving the error:

"Cannot implicitly resolve the test run in the context of which the test controller action should be executed. Use test function's 't' argument instead."

I also tried navigateTo(t.ctx.Url) this doesnot work.

**Comment by miherlosev** [comment]
Hi @avi0711 

I've already answered this question in the [StackOverflow thread](https://stackoverflow.com/questions/57614966/test-controller-from-fixture-passing-to-tests).

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing). So, if you have any questions, please ask them using StackOverflow and don't duplicate them on GitHub.
