### ISSUE TITLE
Allow user to bypass assert and method (click, double click, type) failure to continue running test or add try/catch support

### ISSUE THREAD

**Issue by jiteshsojitra** [DevExpress/testcafe#4191]
TestCafe don't continue tests if click, double click, type method fails but can't we tweak TestCafe methods to continue tests execution? We are adding long running tests using TestCafe and wants continue running the tests even though something fails.

We are using TestCafe very heaving, very helpful, very satisfied with the tool and we would be extremely happy if you fix this issue or provide way/work around to continue tests execution! We tried with try/catch, data provider work around etc.. but whenever TestCafe method (not even assertion) fails, it blocks entire execution.

Please help!

**Comment by Dmitry-Ostashev** [comment]
Currently, we don't provide such options out of the box.
 
Could you please describe your scenario? In what cases is it necessary to skip some unsuccessful action? Do those elements-to-click exist? If yes, are they visible in markup?  
As a workaround, you can check if the target element exists:
 
```
const button = Selector('button');
 
if(await button.exists) 
    await t.click(button);

```
Also, you may wrap the TestCafe actions into your own function using such checking. Here is an example illustrating how to do that: [Conditional test to bypass pop up with Testcafe](https://stackoverflow.com/a/45737370/10684943).

**Comment by jiteshsojitra** [comment]
We are performing various client actions, navigation and measuring time for individual UI operations. It is a single test where various test scenarios are performing let's say for 2 hours. The problem is, if one click fails at 10th minute (which i want to exclude considering we would report it via try { final }) then entire test fails. I'm more interested to get report after running tests for 2/3 hour. Please ignore where application is completely hanged or not accessible in between.

**Comment by Dmitry-Ostashev** [comment]
Thank you for the clarification. Is the workaround described above applicable for your case?

**Comment by jiteshsojitra** [comment]
> 
> 
> Thank you for the clarification. Is the workaround described above applicable for your case?

No because if click fails then test fails.

**Comment by AlexKamaev** [comment]
@jiteshsojitra 
I'm afraid there is no way to work around your issue. Testcafe API methods add their commands to one chain of promises via the 'then' method. This means that if an error occurs in one method of the chain, further methods will also catch the same error. Thus, try/catch will not work.
 
Would you please clarify why you need such a long-time test that can fail on the 10th minute? We usually recommend writing small tests. Also, if the target element exists as in @Dmitry-Ostashev's example, the `click` action should not fail.
