### ISSUE TITLE
Possible to call TestCafe from java?

### ISSUE THREAD

**Issue by dxxvi** [DevExpress/testcafe#4192]
I know that TestCafe is a node.js app, but I still wonder if there is any way to call testcafe from java and get all the testcafe result in java (besides Runtime.exec)?

**Comment by Dmitry-Ostashev** [comment]
As TestCafe is a regular node.js application, you can use any suitable way to run it from Java (for example: [Calling a node.js script from inside java](https://stackoverflow.com/questions/14275479/calling-a-node-js-script-from-inside-java) ). We don't have any special tools for this case.

Also you can implement your own reporter to obtain test results in the format you need. Take a look at this topic: [Reporter Plugin](https://devexpress.github.io/testcafe/documentation/extending-testcafe/reporter-plugin/).
