### ISSUE TITLE
Unnecessary await on the Promises

### ISSUE THREAD

**Issue by yashLadha** [DevExpress/testcafe#4193]
### What is the Current behavior?

Currently, there are functions like readFile, which uses promisified functions but using await in the lower level block of execution. 
 
### What is the Expected behavior?

This completely defies the purpose of calling the function using await at higher level stages, because promise is already resolved at the lower level. Instead it should be done at the top-most level.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   `1.4.2-rc.1`
* node.js version:                    `10.16.1`
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. Could you please add more details about your case? Functions referenced in your pull work as intended. They retrieve the content from a specified file and decorate possible errors. Moreover, this API is not documented so I am a bit curious about the way you use them in your project.

**Comment by yashLadha** [comment]
@AndreyBelym  They will work as intended because we are resolving promise at a very lower level of chain and that defies making the middle function as an async because in theory it will not return a promise and return resolved value only. So as a best practice and removing ambiguity of using await at every return statement. I propose to resolve the promise at the topmost level, where the logic is needed.

**Comment by AndreyBelym** [comment]
If you don't use `await`, you can catch an exception with the `try...catch` statement. Check the following code in Node.js REPL or Chrome DevTools:
```
async function fn1 () {
    try {
        return await Promise.reject(new Error('reason'));
    } catch (e) {
        console.log('exception caught');
    }
}

async function fn1 () {
    try {
        return Promise.reject(new Error('reason'));
    } catch (e) {
        console.log('exception caught');
    }
}

fn1()
// output: exception caught

fn2()
// output: Unhandled promise rejection: reason
```

So since this code is semantically valid, and you worry only about code style issues, I prefer to keep this function as is.

**Comment by yashLadha** [comment]
Then, in that case, upper-level functions do not need to `await` as at lower level we are resolving the promise.

**Comment by AndreyBelym** [comment]
>  upper-level functions do not need to await

This statement is not correct. If your lowe-level function is declared as `async`, you have to use the `await` keyword to get the real returned value. Otherwise, you will get a `Promise` wrapper.
