### ISSUE TITLE
Document additional options to run a locally installed binary

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#4196]
### What is your Test Scenario?
Run a locally installed TestCafe instance: https://devexpress.github.io/testcafe/documentation/using-testcafe/installing-testcafe.html#locally

### What are you suggesting?
Document how to use `npx` and `yarn run` to run a local TestCafe installation without writing a script section in `package.json`.

**Comment by VasilyStrelyaev** [comment]
Fixed in https://github.com/DevExpress/testcafe/pull/4200
