### ISSUE TITLE
Testcafe hangs randomly on a click method using Page Model

### ISSUE THREAD

**Issue by aneeshrelan** [DevExpress/testcafe#4197]
My TestCafe tests hangs indefinitely on a `await t.click(allAssetsVerticalDistributionPO.allButton);` randomly. I have 31 occurrences of this line covering a lot of E2E scenarios. It randomly gets stuck on one of them without any feedback/error. I had tried adding some `console.log` statements, with this it was evident that it randomly hangs. Everytime I execute the tests, it gets stuck on a different line, but it's the same click method. I have also tried to change the selectors on the Page Model.

### What is the Current behavior?
Random hang using TestCafe v1.4.1 on `click` methods. It's working just fine on local machines (everytime) but causing this random behavior on our CI machine
 
### What is the Expected behavior?
It should execute in the same manner on all machines
 
### Your Environment details:
 
* testcafe version:                   1.4.1
* node.js version:                    v10.16.0
* command-line arguments:  testcafe chrome:headless tests
* browser name and version: HeadlessChrome 77.0.3833 / Linux 0.0.0
* platform and version:         RHEL 7.6

**Comment by arubtsov** [comment]
Hello @aneeshrelan,
 
If I run [basic examples](https://github.com/DevExpress/testcafe/tree/master/examples/basic) everything works fine. The problem may relate to a lack of resources on your CI machine. Unfortunately, it is hard to make any other assumptions based on your description. Could you please provide a public page URL or a small reproducible example?
