### ISSUE TITLE
Selector property getter 'visible' waits for the element in DOM to exist and be visible till timeout but 'exists' doesnt

### ISSUE THREAD

**Issue by noamaankhan** [DevExpress/testcafe#4203]
### What is your Test Scenario?
I want to verify if an element exists in the DOM and if exists, is it visible.
 
### What is the Current behavior?
I use `Selector('#element').exists` to find out if the element exists and `Selector('#element').visible` to find out if it is visible. 
 
### What is the Expected behavior?
`Selector('#element').exists` to wait for the timeout before evaluating 'exists' property. Seems like it does wait for timeout when evaluating property 'visible', but doesnt wait for 'exists' and immediately returns false.
 
### Steps to Reproduce:

Try printing the 'exists' property before the 'visible' on the Selector of an element in DOM which takes a little while to be populated. 

**'exists' returns false but 'visible' returns true:**

`console.log(await Selector(#element).exists);
console.log(await Selector(#element).visible);`

**Then change the order of above statements. This time 'visible' returns true and 'exists' returns true:**

`console.log(await Selector(#element).visible);
console.log(await Selector(#element).visible);`
 

### Your Environment details:
 
* testcafe version:                   1.4.0
* node.js version:                    v12.7.0
* command-line arguments:  
* browser name and version: Chrome 76.0.3809.100
* platform and version:          macOS 10.14.5

**Comment by LavrovArtem** [comment]
We are aware of this issue and it was discussed in #2386. Please refer to it.
