### ISSUE TITLE
Cookies are not remain for several requests in Docker

### ISSUE THREAD

**Issue by alekseyzadorozhniy** [DevExpress/testcafe#4205]
Using Testcafe that runs in Docker I try to set up cookies using `ClientFunction`. The problem is that they set only for the first request. There is no page reloading between requests, only react component re-render is happens.
Without Docker everything works as expected (cookie remains for all requests).

### What is your Test Scenario?
I'm running my tests in Docker.
I've clicked on button and two requests (one after another) have been sent to my mock backend.
Before clicking I've set cookies to get specified mock data to test it
 
### What is the Current behavior?
Cookie has been set only for FIRST request.
![imageWithCookie](http://i.piccy.info/i9/7a7c32b4809d30200a250824d0c0ce56/1566979833/111400/1334930/Screenshot_from_2019_08_28_10_42_45.png)

The second request sending without cookie
![imageWithoutCookie](http://i.piccy.info/i9/abc09685524f056b4b84f9e48438c646/1566979793/97251/1334930/Screenshot_from_2019_08_28_10_44_09.png)
 
### What is the Expected behavior?
Cookie remains for ALL requests in current test.
 
### What is your web application and your TestCafe test code?
```js
    const sendMessageIcon = invoicesPage.sendMessageIcon(invoiceId);

    const setCookie = ClientFunction(() => {
        document.cookie = 'key=value';
    });
    await setCookie();

    await t.click(sendMessageIcon); // on this click requests are sending
```

### Steps to Reproduce:

1. Set cookie
3. Send few requests
4. See that cookie is present only in first one
 
### Your Environment details:
 
* testcafe version:                   1.2.1
* node.js version:                    10.15.1
* command-line arguments:    testcafe
* browser name and version:  Chrome
* other:                                   running in Docker

**Comment by alexey-lin** [comment]
Hi @alekseyzadorozhniy,

TestCafe has its own cookie processing mechanism. The `document.cookie` setter is wrapped with the TestCafe service function on the client side. So, request headers shown by a browser are not quite representative, because the cookie can be set by the TestCafe proxy later. The only way to be sure that cookies are missing is to check this on backend. Could you add some request logging to your backend code to see whether cookies are received by the server side?

**Comment by alekseyzadorozhniy** [comment]
@alexey-lin 

Strange, but after adding request logging to my backend I've seen that when I working in Docker cookies are empty at all 
![CookiesWithDocker](http://i.piccy.info/i9/66a6b8685a2265b2155077257eaffb47/1567078170/4056/1334930/Screenshot_from_2019_08_29_14_04_24.png)

When I executing the same code without Docker I get cookies as expected
![CookiesWithoutDocker](http://i.piccy.info/i9/302fa58955ead5fc1e0325cbc8ef55cd/1567078562/5287/1334930/Screenshot_from_2019_08_29_14_25_35.png)

**Comment by AlexKamaev** [comment]
@alekseyzadorozhniy 
I was not able to reproduce the issue on my side. I recommend using the built-in [RequestHooks](https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/creating-a-custom-http-request-hook.html) mechanism to log your page requests. I tried it on my page and everything works as expected.
 
Please use this code as a starting point:
```JS
import { RequestHook, ClientFunction } from 'testcafe';

class MyRequestHook extends RequestHook {
    constructor (requestFilterRules, responseEventConfigureOpts) {
        super(requestFilterRules, responseEventConfigureOpts);
        // ...
    }
    async onRequest (event) {
        console.log('onRequest: ' + JSON.stringify(event.requestOptions));
    }
    async onResponse (event) {
        // ...
    }
}
const customHook = new MyRequestHook(/.*/);

const setCookie = ClientFunction(() => {
    document.cookie = 'key=value';
});

fixture `fixture`
    .page `http://google.com`
    .requestHooks(customHook)

```
This hook intercepts all requests and logs the request options.
I hope it helps you find the cause of the issue. If not, I will appreciate it if you share your project with the team or prepare a sample to reproduce the issue on our side.
