### ISSUE TITLE
Research network problems in functional & client tests

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#4207]
#### Provide the test code and the tested page URL (if applicable)

 
Your website URL (or attach your complete example):

Your complete test code (or attach your test files)

```js

```
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by AlexKamaev** [comment]
I cannot reproduce it at this moment
