### ISSUE TITLE
How to wait for authentication response before navigating to an Url

### ISSUE THREAD

**Issue by ppratibha** [DevExpress/testcafe#4210]
#### HEADS UP!

For TestCafe API, usage and configuration inquiries, we recommend [StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)).

You may also find answers in our up-to-date [documentation](https://devexpress.github.io/testcafe/documentation/getting-started/) and [answered questions](https://stackoverflow.com/questions/tagged/testcafe) on StackOverflow. This may save your time.

If you have already looked there and have not found an appropriate answer, [file a new question on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe).

**Comment by ppratibha** [comment]
In the same test, I need to do following : 
1. Use user role user1
2. Send a message
3. Use user role user2
4. Go to a URL
5. Read the message sent in step 2

The problem is, after step 3, testcafe does not wait for authentication to finish and goes to a URL specified in step 4. As it is still in unauthenticated state , server redirects it login page. And the test hangs in this page. 

I have a question : 
1. Is it possible to use multiple user roles navigating to multiple pages in the same test ?

**Comment by Dmitry-Ostashev** [comment]
Your scenario looks correct and TestCafe should wait for any requests and page reloads. If you provide us with your page url, we could find the cause of this behavior. 
 
Also, take a look at a similar issue: https://github.com/DevExpress/testcafe/issues/1836.
