### ISSUE TITLE
RequestLogger doesnt log requests in chrome:headless mode

### ISSUE THREAD

**Issue by noamaankhan** [DevExpress/testcafe#4218]
### What is your Test Scenario?
I have a test where I expect certain requests to be made by my webapp on certain actions. 
 
### What is the Current behavior?
The RequestLogger is able to capture and log requests in regular 'chrome' mode but doesnt seem to be working in headless mode.
 
### What is the Expected behavior?
RequestLogger should work in irrespective of headless mode or not.

### Steps to Reproduce:

1. Set up RequestLogger to capture requests to a given url
2. Take some actions on your webapp which triggers requests to the above url.
3. Print captured results
4. Works in regular mode but is empty in chrome:headless mode.
 
### Your Environment details:
 
* testcafe version:                   1.4.1
* node.js version:                    v12.7.0
* command-line arguments:  testcafe chrome:headless ./test/integration/ 
* browser name and version: Chrome 76.0.3809.100
* platform and version:          macOS 10.14.5

**Comment by Farfurix** [comment]
@noamaankhan 

Hello,

I checked my base "RequestLogger" scenario and everything works properly. Could you please provide your test code to reproduce the issue?

**Comment by noamaankhan** [comment]
@Farfurix 
Hi,

Thank you for responding promptly. Thanks to the screenshot-on-failure cmdline option, I was able to figure out the issue. Some elements were overlapping with each other because of which the button that was supposed to trigger few expected calls wasnt getting clicked. I was able to resize the window and fix the issue.
