### ISSUE TITLE
Reporter is throwing error

### ISSUE THREAD

**Issue by enjoy-work** [DevExpress/testcafe#4219]
Hi Guys

I want to store the results to file but its not working for me.
Reporter is not saving content to file, I have tried so many ways from programming interface but getting below error: 

(node:14424) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: this[stream].write is not a function
(node:14424) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-
zero exit code.

Below is my code : 
**main.js**
```js
 const createTestCafe = require('testcafe');

let testcafe = null, runner = null;


createTestCafe("localhost", 1377, 1378)
   .then(tc => {
      testcafe     = tc;
      runner = testcafe.createRunner();
   })
   .then(()=>{
      return  runner
         .src( [
            "tr.js"
         ])
         .browsers(['chrome']) 
         .reporter("json","out.json")
         .run()
   })
   .then((failedCount) => {
      console.log('Tests failed: ' + failedCount);
      testcafe.close();
   })
```

**tr.js**
```js
import { Selector } from 'testcafe';
fixture `New Fixture`
    .page `https://www.google.co.in`;

test('New Test', async t => {
    await t
        .click(Selector('a').withText('Gmail'));
});
```

Please help me out from this.

**Comment by Farfurix** [comment]
@enjoy-work 

Hello,
 
I wasn't able to reproduce the issue on my side under Windows 10 / TestCafe v1.4.2. Please check the `testcafe chrome 'path/to/test/file.js' --reporter json` command (instead of `createTestCafe`) and let us know the result. What are your environment details (see the "Bug report" template)?

**Comment by enjoy-work** [comment]
Hi Farfurix

I'm able to  report from CLI "testcafe chrome 'path/to/test/file.js' --reporter json", but if we will try to achieve same by using "createTestCafe" its not generating report.

**Comment by Dmitry-Ostashev** [comment]
@enjoy-work 

I have executed your code on three platforms (Windows 10, Ubuntu, and Mac), and it works as expected. Could you please specify your OS and TestCafe version? Are there any folder permission restrictions?

**Comment by enjoy-work** [comment]
it works now. dont know what was the issue, but it works now.
