### ISSUE TITLE
Filter ShadowUI in content editable

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#422]
If a `document.body` has a `contenteditable` attribute, then its selection may contain ShadowUI root. We need to filter child elements when creating a selection in [content-editable utils](https://github.com/DevExpress/testcafe/blob/a7e94ce4b0765dbf2b055e1f859e32b16e4f25b0/src/client/core/utils/content-editable.js).

Discovered on [ASPxHtmlEditor Custom CSS Demo](http://demos.devexpress.com/ASPXHTMLEDITORDEMOS/ToolbarItems/CustomCSS.aspx).

**Comment by AlexanderMoskovkin** [comment]
closed in favor of #711
