### ISSUE TITLE
TestCafe click() function fails to scroll to the element inside ShadowDOM and click it

### ISSUE THREAD

**Issue by gaoruhao** [DevExpress/testcafe#4222]
### Are you requesting a feature or reporting a bug?
Bug

### What is your Test Scenario?
Click the button in the screenshot which is outside viewport.
![image](https://user-images.githubusercontent.com/6160645/64096898-6b910c80-cd95-11e9-972c-2f573dba2d1e.png)

### What is the Current behavior?
TestCafe click() function fails to scroll to the element inside ShadowDOM and click it.
 
### What is the Expected behavior?
TestCafe scrolls down to the element and click it.
 
### What is your web application and your TestCafe test code?
Your website URL (or attach your complete example):
https://measurementslive.ni.com/measure.html

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
import { Selector, ClientFunction } from "testcafe"

fixture `My first fixture`
    .page `https://measurementslive.ni.com/measure.html`;
const scope = Selector(() => {
    document.querySelector("#instrument1").shadowRoot.querySelector("#instrument-tab").shadowRoot.querySelector("#instrument-item-scope").shadowRoot.querySelector("#checkbox").shadowRoot.querySelector("#checkbox").click();
    return document.querySelector("#instrument1").shadowRoot.querySelector("#button");
});
const blankArea = Selector(() => document.querySelector("measurements-live").shadowRoot.querySelector("measurements-live-styles > div > div > div"));
const instrumentTabButton = Selector(() => document.querySelector("#instrument1").shadowRoot.querySelector("#button"));
const reference4 = Selector(() => document.querySelector("nchannel-scope").shadowRoot.querySelector("#settings").shadowRoot.querySelector("#reference-channel4").shadowRoot.querySelector("#channel-state").shadowRoot.querySelector("#switch-housing"));
const scopeIsAttached = ClientFunction(() => document.querySelector("nchannel-scope").isAttached);
test.only('My first test', async t => {
    await t
        .resizeWindow(1500,900)
        .click(blankArea)
        .click(instrumentTabButton)
        .click(scope)
        .expect(scopeIsAttached()).eql(true, { timeout: 50000 })
        .expect(reference4.visible).eql(true)
        .click(reference4) // !! failed to click here
        .debug();
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```
 My first fixture
 × My first test

   1) The element that matches the specified selector is not visible.

      Browser: Chrome 76.0.3809 / Windows 10.0.0

         16 |        .click(blankArea)
         17 |        .click(instrumentTabButton)
         18 |        .click(scope)
         19 |        .expect(scopeIsAttached()).eql(true, { timeout: 50000
      })
         20 |        .expect(reference4.visible).eql(true)
       > 21 |        .click(reference4) // !! failed to click here
         22 |        .debug();
         23 |});
         24 |
         25 |

         at click (C:\github\testcafe_example.js:21:10)
         at test.only (C:\github\testcafe_example.js:13:1)
         at <anonymous>

   (C:\Users\rgao\AppData\Roaming\npm\node_modules\testcafe\src\api\wrap-test-function.js:17:28)
         at TestRun._executeTestFn

   (C:\Users\rgao\AppData\Roaming\npm\node_modules\testcafe\src\test-run\index.js:288:19)
         at TestRun.start
      (C:\Users\rgao\AppData\Roaming\npm\node_modules\testcafe\src\test-run\index.js:337:24)

 1/1 failed (46s)
```
</details>

<details>
<summary>Screenshots: see the screenshot above </summary>
</details>

### Steps to Reproduce:

1. Go to my website: https://measurementslive.ni.com/measure.html
2. Open the instrument tab (in yellow rectangle)
![image](https://user-images.githubusercontent.com/6160645/64097594-42717b80-cd97-11e9-8eea-cf538eeba423.png)
3. Check "Oscilliscope"
![image](https://user-images.githubusercontent.com/6160645/64097646-6df46600-cd97-11e9-9915-8c5f7c5afa2a.png)
4. Scroll down the configuration pane on the right
5. Click the toggle button of "Reference 4"
![image](https://user-images.githubusercontent.com/6160645/64097753-aa27c680-cd97-11e9-946a-a8055d51a919.png)

### Your Environment details:
 
* testcafe version: 1.4.2
* node.js version:  10.14.1
* command-line arguments:  testcafe chrome testfile.js
* browser name and version: Chrome 76.0.3809.132 
* platform and version:          Windows 10

**Comment by alexey-lin** [comment]
Hi @gaoruhao,

Thank you for the detailed description. I've reproduced the problem. We'll look into it.

**Comment by gaoruhao** [comment]
Hi @alexey-lin 

Do you mind me asking whether there is an approximate timeline to fix this bug?

**Comment by alexey-lin** [comment]
@gaoruhao I'm afraid I cannot give any estimates. Our developers will look into this issue in one of the next springs. You will be automatically notified once we start to work on it and once we have any results. Your patience is greatly appreciated.
