### ISSUE TITLE
Selector and NodeSnapshot interfaces not exported

### ISSUE THREAD

**Issue by neilfar** [DevExpress/testcafe#4225]
### What is your Test Scenario?
Trying to extend Selector and NodeSnapshot as per below documentation when using addCustomDOMProperties

https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/extending-selectors.html
 
### What is the Current behavior?
Both interfaces are not exported and Selector is used for an exported function
 
### What is the Expected behavior?
Being able to import and extend the interfaces 
 
### Your Environment details:
 
* testcafe version:                   1.4.2

**Comment by aleks-pro** [comment]
Hello @neilfar ,
The following example works correctly on my side:
```js
import { Selector } from 'testcafe';

fixture `My fixture`
    .page `https://devexpress.github.io/testcafe/example/`;

test('Check Label HTML', async t => {
    interface CustomSelector extends Selector {
        innerHTML: Promise<any>;
    }
    
    interface CustomSnapshot extends NodeSnapshot {
        innerHTML: string;
    }

    // via selector property
    const label = <CustomSelector>Selector('label').addCustomDOMProperties({
        innerHTML: el => el.innerHTML
    });

    await t.expect(label.innerHTML).contains('input type="checkbox" name="remote"');
    
    // via element snapshot
    const labelSnapshot = <CustomSnapshot>await label();

    await t.expect(labelSnapshot.innerHTML).contains('input type="checkbox" name="remote"');
});
```
Also, I've tried this example in Visual Studio Code and it resolves the interfaces as expected.
Can you modify the example so we will be able to reproduce the issue?
