### ISSUE TITLE
Wrong emulation of 'click' event if target element was changed during 'mousedown' or  'mouseup'

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#423]
By now we just don't emulate `click` event if target element was changed during `mousedown` (and following `blur` and `focus`). Target element is an element returned by `document.elementFromPoint` for the point in which we need to perform a 'click' action event. We check this condition before emulating `mouseup`. 
But looks like rules are more complex:

 1. If changed element is contained in original target element, it will be a target for `mouseup` event. Also in this case a `click` event will be raised for the original target element.

 2.  If target element is changed during `mouseup` event, it must be contained in target element of `mousedown` event in order to raise `click` event. Target for `click` event will be a target element for 'mousedown' event.

Example:
Suppose we have elements `div1`, `div2`, `div3`. We are clicking on `div1`. For the event listeners:
```js
        //div1
        div1.addEventListener('mousedown', () => {
             console.log('div1 mousedown');
             div1.innerHTML = ''; //to get same bounding rectangle as a child element
             div1.appendChild(div2);
        });

        div1.addEventListener('mouseup', () => console.log('div1 mouseup'));

        div1.addEventListener('click', () => console.log('div1 click'));

        //div 2
        div1.addEventListener('mousedown', () => console.log('div2 mousedown'));

        div2.addEventListener('mouseup', () => {
              console.log('div2 mouseup');
              div2.innerHTML = ''; //to get same bounding rectangle as a child element
              div2.appendChild(div3);
        });

        div2.addEventListener('click', () => console.log('div2 click'));

        //div3
        div3.addEventListener('mousedown', () => console.log('div3 mousedown'));

        div3.addEventListener('mouseup', () => console.log('div3 mouseup'));

        div3.addEventListener('click', () => console.log('div3 click'));
```
the log output will be:
```
div1 mousedown
div2 mouseup
div1 click
```

**Comment by georgiy-abbasov** [comment]
At this moment natively only Firefox, unlike other browsers, doesn't fire 'click' event, if element under cursor has changed during 'mousedown' event handling.

**Comment by AlexanderMoskovkin** [comment]
@georgiy-abbasov is working on this
