### ISSUE TITLE
TestCafe hangs on click of submit button in an iframe when the click is submitting form and redirecting to a page of a different domain

### ISSUE THREAD

**Issue by lprasanthi** [DevExpress/testcafe#4232]
### What is your Test Scenario?
We are testing a page that loads a form in an iframe from source (www.domain1.comapny.com/load).
User completes the form and submit's it to www.domain1.company.com/submit which then redirects to www.domain2.company.com/anotherform(within the same iframe).

Test hangs after submit. It submits and redirects to the new page(i can see in the UI) but is stuck there(window never closes and next steps are not executed).

 
### What is your web application and your TestCafe test code?
Web application is in ruby on rails framework.
 
Your website URL (or attach your complete example):

Unfortunately I can't share the code but I'm happy to share snippets and video if that helps.
Wanted to understand if this is a limitation with testcafe framework as it's redirecting to a cross domain.

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.3.0-alpha.1
* node.js version:                    12.9.0
* command-line arguments:  "testcafe chrome -e test.js"
* browser name and version: Chrome Version 74.0.3729.131
* platform and version:          Mac OS Mojave Version 10.14.5
* other:

**Comment by alexey-lin** [comment]
Hi @lprasanthi,

We would love to assist you and diagnose this issue. However, we need to reproduce this issue on our side in order to understand its cause. Without a simple sample project, we are unable to provide any solutions.

**Comment by lprasanthi** [comment]
Hi @alexey-lin I'm happy to help. I'll try to create a sample app and share it with you.

**Comment by lprasanthi** [comment]
@alexey-lin https://github.com/lprasanthi/TestCafe-ForgotPwd is the code for the test and README has instructions.

**Comment by AlexKamaev** [comment]
@lprasanthi 
Thank you for cooperation.
I was able to reproduce the issue.

**Comment by lprasanthi** [comment]
Hello, Is there an update on this one ?

**Comment by Dmitry-Ostashev** [comment]
We cannot provide any estimates as to when it will be fixed. Stay tuned in this thread to be notified of our progress.

**Comment by sjt003** [comment]
bump

**Comment by alexey-lin** [comment]
@sjt003, thank you for your feedback. Please note that you can just react with +1 to the original post. It will help us keep the discussion clean and clear.

**Comment by Srutherford2407** [comment]
Any update on this or possible work around?

**Comment by Ogurecher** [comment]
@Srutherford2407, We don't have any updates on this issue. In the meantime, you can use the workaround from [this thread](https://github.com/DevExpress/testcafe/issues/4553).

**Comment by wentwrong** [comment]
@tomchan-bot
There are no updates on this from our side. But as @Ogurecher mentioned above, there is a workaround one can do: switch to the iframe and click the submit button via `ClientFunction` instead of using the `t.click` action.

```js
test('Switch and submit', async t => {
    await t.switchToIframe('iframe');
    await ClientFunction(() => document.querySelector('input').click());
});
```

**Comment by biniosuaf** [comment]
Hey, two things from me on this problem. We recently stumbled upon this and the issue makes most of our tests redundant :/

1. The issue itself - does it happen to you **only** Macs? Our dev machines are Macs, and at first, we noticed tests hanging on them. But also, just now, we've found the other test hanging in the pipeline (which is running on Docker image `node:15.5.0-alpine`) while the same test pass on Mac. So frustrating :/ 
2. BTW we tried the trick with the `ClientFunction` above. It turned out that it didn't click the button at all.

Hope this will add some insight 🤞

**Comment by Dmitry-Ostashev** [comment]
@biniosuaf 

Thank you for the information. We'll take it into account.

**Comment by stella-jivkova** [comment]
Hello,
I can see that a fix has been merged regarding this issue, but I'm still reproducing it with 1.18.5 version of TestCafe.
Can you please confirm if this is supposed to be fixed in the mentioned version?

**Comment by felis2803** [comment]
@stella-jivkova This issue should not be reproducible. So, I assume that the problem you encountered is different. Could you share a small example so that we can investigate this on our side?

**Comment by stella-jivkova** [comment]
@felis2803 the case is as follows: 
Our application is calling for 3DS verification of a credit card payment. The 3DS simulator loads on a new page and part of its contents (including the <form> to be submitted, a dropdown for choosing the response to be simulated and the submit button (of type <input>)) are inside of an iframe.
Clicking the submit button is supposed to trigger addition of the slected response to the form data and then post the form data to a different domain.
However, clicking the submit button triggers nothing and the execution is stuck at the 3DS simulator page.

Upon some investigation with our FE Dev we were able to detect that the submit form has an event listeren, which scope is being changed by TestCafe. I'm attaching a comparison of how things differ between the automated executin via TestCafe and a manual scenario.

<img width="1298" alt="Screenshot 2022-04-15 at 14 58 33" src="https://user-images.githubusercontent.com/3730837/163791216-1e8efda0-aa4e-485f-936e-ae25430fefef.png">

Please, let me know if additional information is needed.

**Comment by felis2803** [comment]
@stella-jivkova This is indeed a different bug that has similar symptoms. Please open a new issue. Also, please attach a link to a repository that reproduces this bug so that we can run it and investigate.

**Comment by chaithanyvv** [comment]
Hi,
Our application involves 3DS validation page where we were using Testcafe 3.3.0 . We are unable to load 3DS page using Testcafe as the hammerhead proxy is blocking the components from loading. The same scenario works with Selenium and we do not face any issues in it. Can you fix this 3DS page load issue in Testcafe ?

**Comment by Aleksey28** [comment]
Hi @chaithanyvv,

This issue is resolved. Please create a separate issue with a simple sample. Also, please follow [this instruction about creating simple examples](https://testcafe.io/documentation/402636/faq/general-info#how-to-create-a-minimal-working-example-when-you-submit-an-issue).
