### ISSUE TITLE
Cannot change the window size of Firefox window (v69)

### ISSUE THREAD

**Issue by mnemanja** [DevExpress/testcafe#4238]
### What is your Test Scenario?

I'm using Testcafe with cucumber in javascript environment.  
Here I have a hook `Before` in which I define that the browser should be maximized:
```ts
Before(async (t) => {
  await t.maximizeWindow();
});
```

### What is the Current behavior?

The Firefox window does not react to any of the resizing methods (fixed values or just maximization).
 
### What is the Expected behavior?

I can confirm that with the version of 68.0.2 the functionality worked as expected. However with the newest version of Firefox - 69.0.0 it does not.

### Your Environment details:
* testcafe version:       v1.4.3            
* node.js version:         v10.16.3           
* command-line arguments: --browsers "firefox"  
* browser name and version: Firefox v69 
* platform and version:    MacOS v10.14.6      
* other:

**Comment by LavrovArtem** [comment]
Hi, Thank you for reaching out to us and submitting this issue. My attempts to replicate it, however, were unsuccessful. Here is my complete sample test: 
```js
fixture `example`
    .page `http://example.com`;   test
    .before(async (t) => {
        await t
            .resizeWindow(500, 500)
            .maximizeWindow();
    })
    ('test', async t => {
        await t.debug();
    });
```
Please try running this test in your environment. Also, this issue can be related to Cucumber, but TestCafe officially does not support it. If you can reproduce this issue without Cucumber, please modify my sample test, so I can reproduce the issue on my side. If you are not able to reproduce this behavior without Cucumber, we won't be able to help.

**Comment by mnemanja** [comment]
I have tested this piece of code on 3 machines. Worked on one, didn't on two.

It worked with version 69 on Ubuntu, but not on 2 Macs, same browser version.

**Comment by aleks-pro** [comment]
Hello @mnemanja ,

I have not managed to reproduce the issue on MacOS v10.14.6, testcafe v1.4.3, node.js v10.16.3, and Fireforx v69.0.0 Please take a look at the [screencast](https://drive.google.com/file/d/1cZUfbLJSjUT9W5KlyjeGOKkqdXZtZoJz/view).
Can you record a screencast demonstrating the issue using, for example, the [Monosnap](https://monosnap.com/welcome) tool and provide us with it?
