### ISSUE TITLE
Active iframe window doesn't consider itself as active if it was reloaded

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#424]
When an iframe is reloaded by changing location or submitting a from, it's `contentWindow` will be reinitialized, but it will  be the same window object from top page view (`iframe.contentWindow` before reload === `iframe.contentWindow` after reload). So after iframe reloading it will be still considered as active by top window, but doesn't be considered as active from inside. It leads to infinite activation loop when trying to perform a click in this iframe.

Discovered in ASPxDockAndPopupsDemos\PopupControl\Content URL

**Comment by AlexanderMoskovkin** [comment]
the same as #418
