### ISSUE TITLE
ERROR No tests to run, when using docker container

### ISSUE THREAD

**Issue by usmanhafeez** [DevExpress/testcafe#4240]
using testcafe docker container on windows 10, and when execute test with command below i get error:

c:\Testcafe>docker run -v //c/Testcafe:/tests -i testcafe/testcafe chromium /tests/Login.js
ERROR No tests to run. Either the test files contain no tests or the filter function is too restrictive.

Type "testcafe -h" for help.

when i execute same test locally it works fine.

Testcafe  version 1.4.3, node version 12.9.1

**Comment by Farfurix** [comment]
@usmanhafeez 

Hello,

I've checked the scenario, and it works without any "No tests to run" errors. Please check your test paths and follow my steps:
1. Run `docker pull testcafe/testcafe`.
2. Run `docker pull diet/docker-chromium`.
3. Run `docker run -v //d/i4240/local-tests-dir:/container-tests-dir -it testcafe/testcafe chromium /container-tests-dir/test.js`. My local test path is "d:\i4240\local-tests-dir\test.js".


Also, note that the `testcafe/testcafe` image has the `v10.16.3` Node.js version:
```
λ docker run -ti --entrypoint=/bin/sh testcafe/testcafe -s
/ $ node -v
v10.16.3
```

**Comment by usmanhafeez** [comment]
C:\Users\Usman Hafeez\AppData\Roaming\npm>docker pull testcafe/testcafe
Using default tag: latest
latest: Pulling from testcafe/testcafe
01fa3b4a8bd4: Pull complete
70d88772cd9c: Pull complete
20e3fe5aa971: Pull complete
4f0d21f60148: Pull complete
7c01ffbb5422: Pull complete
Digest: sha256:4614c345ae3409fcea6f898eb8cc6874b8d081b4b20eb3ed379340af55bfc729
Status: Downloaded newer image for testcafe/testcafe:latest
docker.io/testcafe/testcafe:latest

C:\Users\Usman Hafeez\AppData\Roaming\npm>Run docker pull diet/docker-chromium
'Run' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Usman Hafeez\AppData\Roaming\npm>docker pull diet/docker-chromium
Using default tag: latest
latest: Pulling from diet/docker-chromium
[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the docker.io registry NOW to avoid future disruption.
a3ed95caeb02: Pull complete
7feb61e057c6: Pull complete
829d4994520d: Pull complete
3f3f9ca62565: Pull complete
f1f7cb61b07a: Pull complete
97609273f0ae: Pull complete
Digest: sha256:f3af8f97de88c12e7cb0123237982173f8f31a86c25bcc3719ee6cf4bdc77213
Status: Downloaded newer image for diet/docker-chromium:latest
docker.io/diet/docker-chromium:latest

C:\Users\Usman Hafeez\AppData\Roaming\npm>docker run -v //c/Testcafe:/tests -it testcafe/testcafe chromium /tests/Login.js
ERROR No tests to run. Either the test files contain no tests or the filter function is too restrictive.

Type "testcafe -h" for help.

**Comment by Farfurix** [comment]
@usmanhafeez 

I still cannot reproduce the "No tests to run" issue.
 
According to your `docker` command, you should have the "c:\Testcafe\Login.js" test file. It means that you are able to run both commands:
1. `testcafe chrome c:/Testcafe/Login.js`
2. `docker run -v //c/Testcafe:/tests -it testcafe/testcafe chromium /tests/Login.js`

In my case, both commands are executed successfully.

Login.js:
```js
fixture `Fixture`
    .page `https://google.com`;

test('test', async t => {
    await t
        .wait(3000)
        .expect(true).ok();
})
```

Result:
![Capture](https://user-images.githubusercontent.com/30019338/64428450-69dc8700-d0bc-11e9-9097-8df33d39aa65.PNG)

**Comment by usmanhafeez** [comment]
C:\Users\Usman Hafeez\AppData\Roaming\npm>testcafe chrome c:/Testcafe/Login.js
The "src", "browsers", "reporter" options from the configuration file will be ignored.
 Running tests in:
 - Chrome 76.0.3809 / Windows 10.0.0

 Main Page
 √ Login with valid user and password


 1 passed (13s)

C:\Users\Usman Hafeez\AppData\Roaming\npm>

**Comment by usmanhafeez** [comment]
C:\Users\Usman Hafeez\AppData\Roaming\npm>docker run -v //c/Testcafe:/tests -it testcafe/testcafe chromium /tests/Login.js
ERROR No tests to run. Either the test files contain no tests or the filter function is too restrictive.

Type "testcafe -h" for help.

C:\Users\Usman Hafeez\AppData\Roaming\npm>

**Comment by usmanhafeez** [comment]
And i see two different Version of testcafe depending on from which path i run command testcafe -v:

![image](https://user-images.githubusercontent.com/15941352/64512744-53feda00-d2e7-11e9-9d91-878ee9c038b8.png)

**Comment by miherlosev** [comment]
On Windows machines, Docker containers can only access the C:\Users directory by default. You need to share C:\TestCafe directory as described in the [Docker documentation](https://docs.docker.com/toolbox/toolbox_install_windows/#optional-add-shared-directories).

**Comment by usmanhafeez** [comment]
Optional: Add shared directories
By default, Toolbox only has access to the C:\Users directory and mounts it into the VMs at /c/Users.

But i don't have toolbox installed, i am using Docker Decktop version 2.1.0.2 (37877)

**Comment by Farfurix** [comment]
@usmanhafeez 

I found the "Shared drives" section in the Docker Desktop documentation: https://docs.docker.com/docker-for-windows/#shared-drives. I think it will help you run your test under Docker.
