### ISSUE TITLE
Uncaught TypeError: Cannot read property 'nodeType' of undefined

### ISSUE THREAD

**Issue by foxhard** [DevExpress/testcafe#4244]
### What is your Test Scenario?
Run a simple test on a form which is opened as a modal. The form is implemented with `jquery 3.4.0` and `parsleyjs 2.7.2`
 
### What is the Current behavior?
After opening the form, this error (`Uncaught TypeError: Cannot read property 'nodeType' of undefined`) is shown in the Chrome developer console
 
### What is the Expected behavior?
No error should be shown in the Chrome developer console.
 
<details>
<summary>Screenshots:</summary>

[Screenshot of the error](https://share.getcloudapp.com/L1uzbAKO)
</details>
 
### Your Environment details:
 
* testcafe version:                   1.4.3
* node.js version:                    12.2.0
* command-line arguments:  npx testcafe chrome test.js -e
* browser name and version: Chrome 76.0.3809.132
* platform and version:          Windows 10, MacOs Mojave

**Comment by miherlosev** [comment]
I am afraid this information is not sufficient to find the cause of the issue. Could you please provide a page or a small example so that we can reproduce it on our side?
