### ISSUE TITLE
testcafe -v shows two versions

### ISSUE THREAD

**Issue by usmanhafeez** [DevExpress/testcafe#4247]
C:\Users\aaa bbb\AppData\Roaming\npm>testcafe -v
1.4.3

and when testcafe version in any other path it shows:
c:\Testcafe>testcafe -v
Using locally installed version of TestCafe.
0.20.5

Using windows 10, Node version 12.9.1

**Comment by miherlosev** [comment]
You can install TestCafe locally and globally as any standard Node.js module.
When you execute the command `C:\Users\aaa bbb\AppData\Roaming\npm>testcafe -v`, your terminal display the version of the globally installed TestCafe.

The `c:\Testcafe>testcafe -v` command displays the version of the locally installed TestCafe.

Please note that if you have other questions, please ask them on [StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe). StackOverflow is an amazing platform for users to ask and answer questions: the community will see and answer your question there.
 
We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing). If you consider this to be a bug, feel free to open a new issue, but please make sure to follow the bug template. Thank you in advance.
