### ISSUE TITLE
Unexpected alert in step with handleAlert if alert occurs before step code exectuion

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#425]
Alert can be raised in time between next step started and `handleAlert()` was executed. In that case 'Unexpected alert` error will be raised, because we check expected alerts count when user-code calls `window.alert()`. Maybe we need to perform this check when the step is finished.

Example from '\ASPxFileManagerAndUploadDemos\FileManager\Client Side Events':
```
"14. Click the Upload button": function() {
        act.click(getFileManager().getUploadButton());
    },
    "15. Wait until file is uploaded. Alert box should pop up": function() {
        //This step is failing with unexpected alert 
        handleAlert();
        act.wait(500, isUploadComplete);
    },
```

**Comment by georgiy-abbasov** [comment]
Blocked by [testcafe-hammerhead-issue-199](https://github.com/DevExpress/testcafe-hammerhead/issues/199)

**Comment by AndreyBelym** [comment]
Now I can not reproduce the original issue, but it looks that I've found the reason of the problem.
Test page:
```html
<html>
	<head>
		<title>Test iframe</title>
	</head>
	<body>
        <button>Click</button>
        
        <script type="text/javascript">
            document.querySelector('button').addEventListener('click', function () {
                setTimeout(function(){
                    alert('Test')
                }, 1000);
            });
        </script>
	</body>
</html>
```


Test itself:
```js
"@fixture test";
"@page http://localhost:8080/test.cshtml";

__waitFor(function (cb){
    setTimeout(cb, 1000);
}, 20000)
        
"@test"["1"] = {
    
    0: function () {
        
        act.click('button');
    },
    1: function () {
        handleAlert();
        act.wait(5000);
    },
};
```
As a result:
```
1) Chrome 49.0.2623 / Windows 10 0.0.0
       Error at step "1":
       Unexpected system alert dialog Test appeared.
```
despite `handleAlert()` in step 1.

If `alert` is called on timeout big enough for `stepIterator` to call `globalWaitFor`, and before `globalWaitFor` will call callback, it will rise an error. Also I think that `globalWaitFor` behavior may be affected by VM performance, so it will give more delay when farm is under high load.  So disappearance of the problem is likely reasoned by decreased farm load due to scheduling tests for running once per day at night, so `globalWaitFor` delay is smaller and it returns control to `stepIterator` before `alert` call.

**Comment by inikulin** [comment]
Closing since it's not relevant to this repo anymore, moved to legacy API repo: https://github.com/DevExpress/testcafe-legacy-api/issues/14
