### ISSUE TITLE
Enhance Documentation for integration into devops

### ISSUE THREAD

**Issue by bluerouse** [DevExpress/testcafe#4250]
### What is your Test Scenario?
Configuring a build in azure Devops which reports as Testresults. This is possible using the testcafe-reporter-xunit and configuring a "Publish Test Result" step in the build pipeline

### What are you suggesting?
Enhance the documentation on https://devexpress.github.io/testcafe/documentation/continuous-integration/azure-devops.html how to add the reporter and the build step to publish results.

### Additional context
Attention, to get this running, devops has to be configured as "JUnit", see issue here: https://github.com/DevExpress/testcafe-reporter-xunit/issues/5

**Comment by alexey-lin** [comment]
Hi @bluerouse,
 
Thank you for the suggestion. I believe it's a good idea. We will consider this enhancement in future sprints.

**Comment by titerman** [comment]
Closed in favour of https://github.com/DevExpress/testcafe/issues/7151
