### ISSUE TITLE
Determine the sequence to run the test

### ISSUE THREAD

**Issue by presha1** [DevExpress/testcafe#4256]
I want to be able to determine the sequence in which tests are run. 

I want my tests to run in sequence as I want. For example, All the test related to landing tests first(the page that you reach first when you go to the site), then test for login test, and then other features that requires users to be Login. This helps me to run in sequence that make more sense in my application. 

In long run, I want to be able to skip or fail all the test that requires login, if the Login test fails. 

**Current behavior**: Test runs based on the alphabetic order of the filename. 

It is very hard to maintain filename as number of files are increasing.

**Comment by Dmitry-Ostashev** [comment]
You can define tests' order by using the Programming Interface and the [Runner.src method](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#src) with an array of file names or patterns.

For your global task, you can create several Runner instances and run them one by one with a particular test suite conditionally (e.g. don't run the second suite if the first one failed tests).
