### ISSUE TITLE
Testcafe should be closed if 'No tests to run' error has occurred in Live mode

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#4257]
```js
const createTestCafe = require('testcafe');
let testcafe         = null;
let liveRunner 		 = null;

createTestCafe('localhost', 1337, 1338)
    .then(tc => {
        testcafe         = tc;
        liveRunner = testcafe.createLiveModeRunner();

        return liveRunner
            .src('dummy.js')
            .browsers('chrome')
            .run();
    })
    .then(() => {
        testcafe.close();
    });

```

**Comment by AndreyBelym** [comment]
Hmm, I feel we should discuss it. It can occur if you haven't created the specified file or it is not a valid test file (missing `fixure`/`test` directive, etc.). IMHO in the first case, we should detect when the specified file is created, and for the second - just wait for file changes as always.

**Comment by miherlosev** [comment]
In general case, the customer should be notified about problem.

On `testcafe@1.10.1` the terminal will look like this
![image](https://user-images.githubusercontent.com/4133518/104287755-f32d7600-54c7-11eb-8b01-22c7fccb04ad.png)

and browser stay on the idle page.
