### ISSUE TITLE
[docs] Wrong description for the default value of the 'cdpPort' argument.

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#4259]
https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/using-chrome-device-emulation.html#emulator-parameters

cdpPort (optional) |  If not specified TestCafe automatically assigns a free port.

The default value for `cdpPort` is `9222`. 

See https://github.com/cyrus-and/chrome-remote-interface/blob/1003815fbf99e6973a8ab09bf10d8274c640d8ea/lib/defaults.js#L4

**Comment by AndreyBelym** [comment]
There is a more correct description of this situation is in this comment: https://github.com/DevExpress/testcafe/pull/4261#pullrequestreview-286868992
