### ISSUE TITLE
TestCafe - Chrome browser freezes and restarts continuously when running a test for an Auto-fill field 

### ISSUE THREAD

**Issue by rwedamuni** [DevExpress/testcafe#4271]
### What is your Test Scenario?
I'm trying to automate a web page with a auto fill address field 
 
### What is the Current behavior?
Chrome browser freezes and restart the browser without selecting an item from auto populated list
 
### What is the Expected behavior?
Test Cafe should be able to pick the 1st Suggestion from the auto populated list. 
 
### What is your web application and your TestCafe test code?

 
www.xfinity.com

<details>
<summary>Your complete test code (or attach your test files):</summary>

import {Selector} from 'testcafe';

fixture `Verifying the offers available for a given address` 
    .page `https://www.xfinity.com`;
    test(`Verify Internet offers for : '11346'`, async t => {
            
         await t
          .click(Selector('a').withText('SHOP/UPGRADE')) ;
          await t
          .typeText(Selector('#Address_SingleStreetAddress'),'11346',{ paste: true }) 
          .wait(5000)
          await t
          .click(Selector('span').withText('11346').nth(0))
          .click(BuyUpgradeLandingPage.btn_ShowMeDeals);

          await t.expect((offerListningPage.lbl_NumOfOffers).textContent).eql(user.itv_count)
         
      });
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to xfinity.com ...
3. click on 'SHOP/UPGRADE' link from top menu bar
4. Enter an part of a address in the address text field. (e.g.: 11346'
 
### Your Environment details:
 
* testcafe version:                   latest
* node.js version:                    v10.16.3
* command-line arguments:  node index.js
* browser name and version: Chrome - Version 77.0.3865.75 (Official Build) (64-bit)
* platform and version:          Windows 10
* other:                                   Runner Config as below

const createTestCafe = require('testcafe');
const log = console.log;

createTestCafe('localhost', 1337, 1338)
    .then(testcafe => {
        const runner = testcafe.createRunner();
        const remoteConnection = testcafe.createBrowserConnection();

        runner
            .src('./Tests/BuyFlowTestScenarios/*.js')
            .browsers(['chrome']) //--incognito
            .reporter('spec')
            .screenshots('./TestExecutions/Screenshots/', true, '${DATE}_${TIME}/test-${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.png')
            .run({skipJsErrors:true})
            .catch(error => {
                log("   An unexpected error has occured: ", error);
                testcafe.close();
        	}).then(r => {
            	testcafe.close();
        	});
    });

**Comment by arubtsov** [comment]
Hello @rwedamuni,
 
I changed the code you provided to run it on my side as follows:
Test:
```
import { Selector } from 'testcafe';

fixture`Verifying the offers available for a given address`
    .page`https://www.xfinity.com`;

test(`Verify Internet offers for : '11346'`, async t => {

    await t
        .click(Selector('a').withText('SHOP'));
    await t
        .typeText(Selector('#Address_SingleStreetAddress'), '11346', { paste: true })
        .wait(5000)
    await t
        .click(Selector('span').withText('11346').nth(0))
        .click(Selector('button').withText('Show me deals'));

    //await t.expect((offerListningPage.lbl_NumOfOffers).textContent).eql(user.itv_count);
});
```
Runner configuration:
```
const createTestCafe = require('testcafe');
const log = console.log;

createTestCafe('localhost', 1337, 1338)
    .then(testcafe => {
        const runner = testcafe.createRunner();
        const remoteConnection = testcafe.createBrowserConnection();

        runner
            .src('./path_to_the_test.js')
            .browsers(['chrome']) //--incognito
            .reporter('spec')
            .screenshots('./TestExecutions/Screenshots/', true, '${DATE}_${TIME}/test-${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.png')
            .run({ skipJsErrors: true })
            .catch(error => {
                log("   An unexpected error has occured: ", error);
                testcafe.close();
            }).then(r => {
                testcafe.close();
            });
    });
```

However, I was not able to reproduce the described behavior under Windows 10\ Testcafe 1.5.0\ Node v10.16.3. Am I missing something? Do you see any errors in the console or developer tools?

**Comment by rwedamuni** [comment]
[ScreenCapture.zip](https://github.com/DevExpress/testcafe/files/3616542/ScreenCapture.zip)
Hi ,
I have attached a Screen recording for your reference. hope this helps. Let me know if you need additional information regards to this.

Thanks & Regards,
Rasanga.

**Comment by tarjei** [comment]
@arubtsov  which chrome version are you running? I'm seeing something that looks a bit like this and I'm suspecting chrome 77 is the culprit.

**Comment by AlexKamaev** [comment]
I was able to reproduce the issue, however, I can reproduce it quite rarely, so it would be very difficult to research it. Thus I cannot give any estimate on this.
I do not think that the cause of the issue lies in typing. Sometimes it stops working before the typing. I assume that the cause of the issue can be in some external resources: advertisement, some amazon scripts, etc.
 
So I recommend you mock all external requests that are not required for testing. Please see the following article: https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/mocking-http-requests.html
 
Please tell us if it helps.

**Comment by sjt003** [comment]
can confirm. happening on chrome 81. mocking all external requests

**Comment by alexey-lin** [comment]
@sjt003, if you are able to reproduce the issue consistently, could you share a sample project? It would be very helpful.

**Comment by miherlosev** [comment]
Hi @rwedamuni,

This issue is not reproduced with combination of `testcafe@3.0.1` and the Google Chrome browser. Feel free to reopen this issue if you encounter it in other browsers.
