### ISSUE TITLE
Request Hooks `onResponse` not triggered for HTTP redirects 3xx

### ISSUE THREAD

**Issue by bsingr** [DevExpress/testcafe#4275]
# What is your Test Scenario?

I am testing the lifetime of authentication cookies in a Keycloak server. To test the lifetime i am using [request hooks](https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/creating-a-custom-http-request-hook.html) to extract the "set-cookie" values and re-use them later.

I don't know where the problem exactly is, maybe testcafe hammerhead?

### What is the Current behavior?

- `onRequest` is called for every request
- `onResponse` is only called for non-3xx responses
 
### What is the Expected behavior?

- `onRequest` must be called for every request
- `onResponse` must be called for every responses
 
### What is your web application and your TestCafe test code?

<details>
<summary>CookieInterceptorHook.js:</summary>

```js
import { RequestHook } from 'testcafe';
export default class CookieInterceptorHook extends RequestHook {
    constructor (requestUrlMatch) {
        super(undefined, {includeHeaders: true});
        this.requests = {}
    }
    async onRequest (event) {
      console.log('REQUEST', event.requestOptions.url)
      this.requests[event._requestInfo.requestId] = event
    }
    // PROBLEM: never is called for any redirect url?
    async onResponse (event) {
      const request = this.requests[event.requestId]
      console.log(' RESPONSE', request.requestOptions.path, event.statusCode)
      if (request && event.headers['set-cookie']) {
        // do something with cookie...
        console.log('set-cookie', request.requestOptions.path, event.headers['set-cookie'])
      }
    }
    shouldHandleEvent(event) {
      return true;
    }
} 
```

</details>

### Your Environment details:
 
* testcafe version:                   1.5.0
* node.js version:                    v12.4.0
* command-line arguments:  testcafe firefox test.js
* browser name and version: any (firefox, chrome, ...)
* platform and version:          any (macos)

**Comment by miherlosev** [comment]
Hi @bsingr 

I cannot reproduce this behavior with a [simple example](https://github.com/DevExpress/testcafe/files/3616403/example.zip). 
Could you please provide a full example which I can run on my machine without any additional setup?

**Comment by bsingr** [comment]
Hi @miherlosev 

Thanks for coming up and testing with the example. Actually the request logger does not illustrate the problem, because requests are correctly intercepted. The problem is just with the responses.

I updated your example to illustrate the problem [example.zip](https://github.com/DevExpress/testcafe/files/3616529/example.zip).

The log output I see tells me that no responses for 3xx requests are logged:

```json
{
    "I3JrxfoIG": {
        "url": "http://localhost:3000/",
        "response": true
    },
    "hhgWevUuf": {
        "url": "http://localhost:3000/redirect.html"
    },
    "oulMBHWcO": {
        "url": "http://localhost:3000/final_page.html",
        "response": true,
        "responseSetCookie": [
            "two=2"
        ]
    }
}
```

**Comment by AlexKamaev** [comment]
I'm afraid that you cannot check cookies using this approach.
TestCafe has its own cookie processing mechanism. The mechanism controls all cookie processing on the client ('document.cookie') and server sides ('set-cookie' header). This means that the client-side 'document.cookie' and response.headers properties don't contain an actual cookie state as you expected.
 
To get an actual cookie value of a request, inspect the header values in the `_send()` function from the `node_modules/testcafe-hammerhead/lib/request-pipeline/destination-request/index.js` file.
 
It seems strange that 'onResponse' is not called for 301 HTTP status code. We need additional time to investigate this behavior.

**Comment by bsingr** [comment]
@AlexKamaev the actual cookie-checking works for me. The onResponse hook actually contain the cookie I expect (i guess they are mapped and translated back somewhere..?)

Just not the case for 3xx response because there no onResponse hook is executed at all. But for all other works.

**Comment by AlexKamaev** [comment]
@bsingr we'll research this behavior

**Comment by miherlosev** [comment]
Hi @bsingr 

I cannot reproduce the problem with the latest TestCafe version (`1.8.8`).
![image](https://user-images.githubusercontent.com/4133518/89270014-6bebf480-d643-11ea-86a9-0b0d1da9f0b1.png)


Try to run your tests and feel free to reopen issue if the problem persists.
