### ISSUE TITLE
'spawn UNKNOWN' Error Executing TestCafe With Custom Test Runner Class in Windows

### ISSUE THREAD

**Issue by calisven** [DevExpress/testcafe#4276]
### Are you requesting a feature or reporting a bug?
Bug

### What is your Test Scenario?
Using a custom test runner via 'createRunner()' written in TypeScript and executing the test scenarios on a Windows 10 and Windows 7 machine, run any tests against Chrome or Firefox.

### What is the Current behavior?
When the runner starts, and either 'chrome' or 'firefox' are passed into the runner's 'browsers()' function, an error appears and I am unable to run the tests.

![image](https://user-images.githubusercontent.com/2982972/64881309-4a3ee480-d60f-11e9-9c75-321a80c8662b.png)

### What is the Expected behavior?
The browser should open up at the tests should begin to execute. We are able to execute TestCafe tests on Windows using the CLI for Chrome and Firefox without issue, and this issue with the custom test runner does not occur at all on our Macs.  

### How would you reproduce the current behavior (if this is a bug)?
Simply execute the NPM script 'test' with ```npm run test``` or ```yarn run test```, while having Chrome or Firefox installed. See Git repo link below along with README.

#### Provide the test code and the tested page URL (if applicable)
https://github.com/calisven/TestCafeWindowsBug

```js

```
### Your Environment details:
 
* testcafe version: 1.1.4
* node.js version: 10.16.3
* command-line arguments:  ```yarn run test``` or ```npm run test```
* browser name and version: Chrome 76.0.3809.132
* platform and version: Windows 10
* other: Please see the Git repo's README. We are able to reproduce this issue with Firefox as well, but the Test Runner class works fine with IE or Edge. Please see 'runner.ts' for implementation details.

**Comment by VasilyStrelyaev** [comment]
Thank you for the detailed example. I have reproduced this behavior.
 
We will research it and provide a solution.

**Comment by calisven** [comment]
Pulled your alpha build and confirmed that the changes fixed the issue - thank you!
