### ISSUE TITLE
Add role "healthcheck" function

### ISSUE THREAD

**Issue by andrzej-kodify** [DevExpress/testcafe#4277]
I've bumped into an issue today that one of my test cases actually kills user session server-side. This is an error in our website (not an intentional logout in test) but when it happens all subsequent tests start to fail (since user represented by that role is no longer logged in from server perspective).

I would like to propose adding an optional "healthcheck" function when creating role that could be invoked whenever `useRole` is executed. The flow would be for testcafe to do its magic and restore snapshot for role (if it was previously initialized) and after restoring snapshot trigger the healthcheck - if that returns `true` assume success, if returns `false` deinitialize role and try to initialize again.

**Comment by miherlosev** [comment]
Hi @andrzej-kodify 

Could you please describe in detail why this option can be useful for TestCafe?
