### ISSUE TITLE
the result of visibilityCheck and visible is different

### ISSUE THREAD

**Issue by link89** [DevExpress/testcafe#4279]
### What is your Test Scenario?

 When we want to check visibility, we don't care about whether node not exists or exists but not visible.
The reason we not use
```typescript
await t.expect(el.visible).notOk()
```
is, if the element not exists, testcafe will break case.

And following method is also flaky
```typescript
if (!(await el.exists)) return;
await t.expect(el.visible).notOk()
```
Because the element is still possible to unmount after pass exists check (we do observe cases failed due to this reason.

 So we use following statement in our cases, which IMO is the most solid method
```typescript
const el = Selector('dialog');
await t.expect(el.with({ visibilityCheck: true }).exists).notOk()
```
It works fine until recently, we found that the result of visibilityCheck is different with visible in some situation.
In our case, the computed style of target element is `block`, and the result is:
```typescript
await el.with({ visibilityCheck: true }).exists  // return true (should return false)
await el.with({ visibilityCheck: false }).exists  // return true (it's ok)
await el.visible // return false
```

### What is the Current behavior?

 the behavior of visibility Check and visible should be consistent.
### What is the Expected behavior?

 the behavior of visibility Check and visible is inconsistent.

### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):
Internal app.

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:  1.1.0                 
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by miherlosev** [comment]
I am afraid this information is not sufficient to find the cause of the issue. Could you please provide a page or a small example so that we can reproduce it on our side?

**Comment by link89** [comment]
I will try to provide demo once having spare time. But I guess it is possible to figure it out via code review.
