### ISSUE TITLE
Wrong element is clicked in Chrome mobile emulation mode

### ISSUE THREAD

**Issue by VasilyStrelyaev** [DevExpress/testcafe#4283]
### What is your Test Scenario?
I'm using Chrome mobile device emulation mode with the `device` parameter. In my test code, I click a button selected by its text content.
 
### What is the Current behavior?
The test clicks a wrong element and proceeds.
 
### What is the Expected behavior?
The test clicks the element I've specified.
 
### What is your web application and your TestCafe test code?
Your website URL (or attach your complete example): [change.org](https://www.change.org)

<details>
<summary>Your complete test code (or attach your test files):</summary>

```js
import { Selector } from 'testcafe';

fixture `My fixture`;

test('Demo test', async t => {
    await t
        .navigateTo('https://www.change.org')
        //.debug()
        .click(Selector('div').withText('Start a petition'))
        .expect(true).ok();
}); 
```

This test clicks an empty area if you run it without debug mode. In debug mode, if you wait for the petition list to load, the test scrolls down and clicks a petition title.
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

</details>

<details>
<summary>Your complete test report:</summary>

</details>

<details>
<summary>Screenshots:</summary>
</details>

### Steps to Reproduce:

Use Chrome mobile device emulation mode to run a test that:

1. Navigates to [change.org](https://www.change.org)
2. Clicks `Start a petition`.
 
### Your Environment details:
 
* testcafe version:                   1.5.0
* node.js version:                    8.16.0
* command-line arguments:  `testcafe 'chrome:emulation:device=iphone X' test.js`
* browser name and version: Chrome 77
* platform and version:          Windows 10 or macOS 10.14.6

**Comment by miherlosev** [comment]
TestCafe doesn't scroll to the target element even without emulation. Reproduced with the `testcafe@1.10.1`.

**Comment by rob4629** [comment]
bump

**Comment by Aleksey28** [comment]
Hi @rob4629,

I researched it and found that this behavior is expected. The issue occurs because for the `Selector('div').withText('Start a petition')`, `testcafe` performs three steps:

1. Gets all `div` elements with the method `querySelectorAll`;
2. Filters all elements from the first step by text `Start a petition`;
3. Returns the first element from filtered elements.

The order of elements depends on the browser and a more restrictive selector should be specified. For example:
```js
Selector('div[data-qa="page-content"] a').withText('Start a petition')
```

Feel free if you have any additional questions.
