### ISSUE TITLE
API testing

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#4288]
The feature should allow to send an HTTP request and check the response details.

See these tools for more information:
* https://github.com/rest-assured/rest-assured#examples
* https://www.getpostman.com/use-cases/api-testing-automation
* https://www.soapui.org/getting-started/introduction.html

There is a separate proposal for `t.request` action - https://github.com/DevExpress/testcafe/issues/2397
##### Notes:
Playwright 1.16 API testing: https://playwright.dev/docs/test-api-testing

**Comment by devdelpiero** [comment]
I would recommended looking at cypress.io. They did a great job with http requests. 

https://docs.cypress.io/api/commands/request.html#Arguments

**Comment by rehael** [comment]
Just a note – when designing this feature remember about OAuth and auth via bearer tokens. Cookies are not enough sometimes.

For direct communication with our μ–services API from within TestCafe scripts we now use Axios with Axios-OAuth interceptor. If the TestCafe's API testing feature would enable similar flexibility, it'd be awesome! Keeping fingers crossed. :)

**Comment by maximojoexpress** [comment]
Example of Karate, another API testing tool:

https://github.com/intuit/karate#hello-world

**Comment by jianentrinsik** [comment]
Like @devdelpiero said, cypress is the main competitor. I had to implement my own helper functions using request-promise module, but it would be really nice if testcafe can provide some built-in support on this!

**Comment by Channa-proxima** [comment]
Any hopes for API Testing (Roadmap) TestCafe Feature?

**Comment by LavrovArtem** [comment]
@Channa-proxima
Any personal estimate may be misleading, so I cannot currently tell you a precise date.

**Comment by miherlosev** [comment]
https://stackoverflow.com/questions/60379608/testcafe-do-we-have-support-for-api-testing

**Comment by vlucas** [comment]
Frisby.js is another option that is promise based and widely used: https://github.com/vlucas/frisby (I am the author)

**Comment by helen-dikareva** [comment]
Happy to announce that TestCafe 1.20.0 release offers the [`t.request` method](https://testcafe.io/documentation/403981/reference/test-api/testcontroller/request) that can be used for API testing right in your e2e tests. Read more in the [corresponding guide](https://testcafe.io/documentation/403971/guides/intermediate-guides/api-testing).
