### ISSUE TITLE
Extended Jenkins integration with TestCafe

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#4289]
Jenkins plugin should
* provide GUI for specifying TestCafe options.
* allows to attaching TestCafe artifacts (images and videos)

It should be allowed to install TestCafe Jenkins plugin from Jenkins GUI (Manage Jenkins-> Manage Plugins).

**Comment by prudhvidandamudi** [comment]
@miherlosev @AndreyBelym 
Any update on this feature?

**Comment by aleks-pro** [comment]
Hi @prudhvidandamudi ,

We are working on this feature and will update this thread once we get any results.

**Comment by prudhvidandamudi** [comment]
Just saw that this ticket is closed, is this feature implemented? waiting for this feature for a few months!!

**Comment by wentwrong** [comment]
Hi, @prudhvidandamudi,

Thank you for your patience. Yes, we've developed a plugin that makes it possible to view artifacts (screenshots and videos) on the resulting test page in Jenkins.
You can already install it using the Jenkins Plugin Manager. See [the ](https://plugins.jenkins.io/testcafe)[plugin page](https://plugins.jenkins.io/testcafe) for more information.
