### ISSUE TITLE
How will customize selector for an element in shadow root for type script? 

### ISSUE THREAD

**Issue by DebashishSamanta** [DevExpress/testcafe#4291]
import {Selector,t} from 'testcafe'

export default class homepage {
public parentHeading:any;
public heading:any;

constructor() {
    this.parentHeading = Selector('.app.form.selected').find('tools-assets');
    this.heading = Selector(() => 
    { return parent()..shadowRoot.querySelector('div').querySelector('.temp-id')},
    dependencies: {parent:parentHeading }}):
}

async clickSigninButton(){
    await t
    .click(this.heading)   
}

}

**Comment by AlexKamaev** [comment]
https://stackoverflow.com/questions/57974960/how-will-customize-selector-for-an-element-in-shadow-root-for-type-script
