### ISSUE TITLE
Option to not truncate error output to viewportWidth

### ISSUE THREAD

**Issue by eug48** [DevExpress/testcafe#4293]
### What is your Test Scenario?
Selector with a long CSS string is failing but the string is truncated using "..." in the error message

### What are you suggesting?
Provide CLI option to not truncate error output to viewportWidth

### What alternatives have you considered?
An option to write very detailed logging to a file (e.g. all actions/selectors) would also be very useful

### Additional context
The error currently looks like this (id consists of several GUIDs - the last one is completely missing)
   1) Cannot obtain information about the node because the specified selector does not match any node in the DOM
      tree.

         | Selector('#editor-5b8f3bc357b79b021655bd22_e5c03c18-2bf9-434e-9702-fbf449...)
       > |   .nextSibling()

**Comment by Farfurix** [comment]
@eug48 

Hello,

```
   | Selector('#editor-5b8f3bc357b79b021655bd22_e5c03c18-2bf9-434e-9702-fbf449...)
 > | .nextSibling()
```

The only purpose of this error message is to show the `.nextSibling()` step in your selector's chain.

In the case of the narrow console window, you have all the necessary information to find an issue in your test scenario. For example:
![Capture](https://user-images.githubusercontent.com/30019338/65232430-cc308100-dad9-11e9-800b-e62bd6047503.PNG)

We don't see any reason to add the "no truncate" CLI option.

**Comment by eug48** [comment]
Thanks @Farfurix for the response and helping to develop TestCafe. The problem is that my selector string is dynamically generated. Here is a screenshot:

![screen](https://user-images.githubusercontent.com/932521/65253861-b3a68200-db3e-11e9-9043-501f00729c96.png)

**Comment by miherlosev** [comment]
Hi @eug48 

You can see the full CSS string if you expand you terminal window to whole screen.
![image](https://user-images.githubusercontent.com/4133518/65312724-cb602380-db9b-11e9-8144-1901c30614f9.png)
