### ISSUE TITLE
`testcafe -b` returns the "The specified "true" browser provider was not found" error

### ISSUE THREAD

**Issue by Farfurix** [DevExpress/testcafe#4294]
![Capture](https://user-images.githubusercontent.com/30019338/65148987-f460a700-da29-11e9-81fb-2795ac22eed3.PNG)

### Your Environment details:
 
* testcafe version:                   v1.5.0
* node.js version:                    v12.8.0
* command-line arguments:  `testcafe -b` || `testcafe --list-browsers`
* platform and version:          Windows 10

**Comment by Daniel-Griffiths** [comment]
Same issue here.

**Comment by gajo4256** [comment]
It happens also on macOS Mojave (version 10.14.6)
