### ISSUE TITLE
Key press plus RMB or MMB

### ISSUE THREAD

**Issue by TravisBert** [DevExpress/testcafe#4295]
### What is your Test Scenario?
I would like to be able to test keyboard + mouse shortcuts for our product. 

For example:
Shift + right mouse button
Middle Mouse button (just in general) 
Ctrl + Right Mouse Button
Ctlr + Middle Mouse Button
Ctrl + Shift + Right Mouse button.

Also be able to drag with the right mouse / middle mouse button.

### What are you suggesting?
I would like to be able to preform a keyboard click then a mouse click and still be able to drag

### What alternatives have you considered?
await t.rightClick((xxx), { modifiers: { shift: true},offsetX: 40, offsetY: 40});

Also I guess a really deep client function could probably do this but it seems a little extreme for this.

### Additional context
This actions are for testing rotate, zoom, pan, etc and would be a really nice feature to have for testing the product.

Thank you.

**Comment by Farfurix** [comment]
@TravisBert 

Hello,

Thank you for your suggestion. I will set the "enhancement" label on this issue.

Note: we also have the "[Individual Interaction Actions](https://github.com/DevExpress/testcafe/issues/3750)" request.

**Comment by TravisBert** [comment]
@Farfurix 

Hello,

Thanks for the response. 

We take advantage of the Individual actions a lot. They work nicely! Just needed a little bit more functionality to complete our test coverage.
