### ISSUE TITLE
Testcafe - Website with ADFS Redirect

### ISSUE THREAD

**Issue by SpencerWaller** [DevExpress/testcafe#4299]
Hi,  We have an issue with testcafe and our production website testing.  It works great for our test environment and the only difference is that in our Test Environment we have one ADFS Server the URL hits before going to the website to continue testing.

In our production environment we have an Internal ADFS Server Identity Provider which then forwards onto our production ADFS Server with the the Relying Party Trust.  It all falls over with the Couldnt find a DNS record at.....

If i change our URL so that the ADFS part at the end of the url points to the production ADFS RP we dont get the DNS error but it just hangs and we get "Waiting for element to appear"

Has anyone else had this issue with ADFS redirect ?

**Comment by miherlosev** [comment]
Hi @SpencerWaller 
 
The test environment you described is very complex. Could you please provide access to your testing environment so we can find the cause of the problem?

**Comment by SpencerWaller** [comment]
Sorry, that we cannot do as it will break all sorts of security scenarios.  However the test environment works as it only uses one ADFS server for authentication before being passed to the website.  The issue we have is when we use our Production ADFS environment.  Please see below an example of the error i get

  1) A request to

   "https://adfs.adfs-idp.domain.com/adfs/ls/?wa=wsignin1.0&wtrealm=http%3a%2f%2fadfs.adfs-rp.domain.com%2fadfs%2fservices%2ftrust&wctx=3e191144-859f-49d9-97ce-a7c3d7521421&wct=2019-09-20T10%3a40%3a09Z"
      has failed.
      Use quarantine mode to perform additional attempts to execute this test.
      You can find troubleshooting information for this issue at "https://go.devexpress.com/TestCafe_FAQ_ARequestHasFailed.aspx".

      Error details:
      Failed to find a DNS-record for the resource at

   "https://adfs.adfs-idp.domain.com/adfs/ls/?wa=wsignin1.0&wtrealm=http%3a%2f%2fadfs.adfs-rp.domain.com%2fadfs%2fservices%2ftrust&wctx=3e191144-859f-49d9-97ce-a7c3d7521421&wct=2019-09-20T10%3a40%3a09Z".

**Comment by AlexKamaev** [comment]
It's very difficult to find the cause of the issue based only on the error message. I can make any suggestions only if somebody has a similar issue in a similar environment.

**Comment by SpencerWaller** [comment]
sure understood.  I think it is an issue related to node.js but cant be sure.  Our main test env works but that only has one ADFS.  i cant be the only one using this with two ADFS servers IDP and RP

**Comment by afcbpeter301** [comment]
I have the exact same issue has the above user. Is there a way around it I have the exact same message on our test environment.

**Comment by SpencerWaller** [comment]
HI,  We have updated to the latest version of node but still have the same problem.  We have two ADFS servers now in our test environment and the journey works but all on the same domain.  The issue with our prod is that the IDP ADFS Server and the RP ADFS Server are on different domains.  Works fine when going via browser,  only has issues when launching via test factory

**Comment by afcbpeter301** [comment]
I'm running it locAlly via my terminal using a js script. What would you recommend I can do to debug this?

**Comment by AndreyBelym** [comment]
@afcbpeter301 the first step could be using the Network DevTools tab to compare requests generated by your site. There should be a difference between manual and TestCafe testing that causes the issue.
