### ISSUE TITLE
Error [ERR_STREAM_CANNOT_PIPE]: Cannot pipe, not readable

### ISSUE THREAD

**Issue by natkrish** [DevExpress/testcafe#4301]
### What is your Test Scenario?
My test scenario is just to do a normal registration process on our website on cloud cross browser providers (www.lambdatest.com)
 
### What is the Current behavior?
Upon completion I get an error from the hammerhead plugin 
 
### What is the Expected behavior?
I do not want to see any errors 
 
### What is your web application and your TestCafe test code?
 Your website URL (or attach your complete example):
https://onlinedoctor.lloydspharmacy.com/register

<details>
<summary>Your complete test report:</summary>
× Register as a new female patient

   1) Unhandled promise rejection:

      Error [ERR_STREAM_CANNOT_PIPE]: Cannot pipe, not readable
      at ServerResponse.pipe (_http_outgoing.js:833:22)
      at respondOnWebSocket (C:\Users\krish.murthy\Documents\qa-testcafe-e2etests\node_modules\testcafe-hammerhead\lib\request-pipeline\websocket.js:41:11)
      at Array.decideOnProcessingStrategy (C:\Users\krish.murthy\Documents\qa-testcafe-e2etests\node_modules\testcafe-hammerhead\lib\request-pipeline\index.js:86:39)
      at run (C:\Users\krish.murthy\Documents\qa-testcafe-e2etests\node_modules\testcafe-hammerhead\lib\request-pipeline\index.js:158:20)
      at processTicksAndRejections (internal/process/next_tick.js:81:5)

          Browser: Mobile Safari 12.0.0 / iOS 12.1.0 ( https://automation.lambdatest.com/logs/?sessionID=3d8d6b2b-648a-46ac-a7e3-9bf1fc6fcc46 )
</details>

### Steps to Reproduce:

1. Go to my website and perform a registration
3. Execute this command :  testcafe "lambdatest:iPhone XS@12.1:ios" .\smoke\NewPreProd\Mobile\RegisterPatient.ts
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.5.0
* node.js version:                    11.7
* command-line arguments:  testcafe "lambdatest:iPhone XS@12.1:ios" .\smoke\NewPreProd\Mobile\RegisterPatient.ts
* browser name and version: Safari 12
* platform and version:          iPhone XS 12.1

**Comment by miherlosev** [comment]
Hi @natkrish 
 
I tried to reproduce the problem and found that the browser, in which you faced this problem, is not available on the free plan.
![image](https://user-images.githubusercontent.com/4133518/65324186-2d2c8780-dbb4-11e9-80cb-bdc5a927258e.png)
 
 
If it's possible, please provide us with a test user to reproduce the problem on LambdaTest service. Send its credentials at support@devexpress.com.

**Comment by natkrish** [comment]
@miherlosev  Please check your support email. You should have got my credentials. Please let me know when you are done. 

Thanks
Krish

**Comment by miherlosev** [comment]
Hi @natkrish 
 
Thank you for providing the additional information.
 
I've tried to run a simple test with the 'lamdatest' browser provider and all works fine.
![image](https://user-images.githubusercontent.com/4133518/65421450-6a8b5200-de0c-11e9-905e-31a827f1da0a.png)
 
To find the cause of the problem, I need the whole test content with all dependent scripts, helpers, etc. Could you please provide it?

**Comment by natkrish** [comment]
@miherlosev Finally i found out what was causing the issue. Its to do with the typescript compilation which was making it to fail. when I converted my tests to plain .js everything seems to work fine now. Hence no need to investigate on this further.
