### ISSUE TITLE
Client side selector to support nested selectors

### ISSUE THREAD

**Issue by benmonro** [DevExpress/testcafe#4308]
### What is your Test Scenario?

Currently in testcafe-testing-library we have the `within` selector.   I would like to be able to pass a selector to that selector as a way of narrowing the query.  In order to do this, I would like to be able to resolve a selector inside another selector.  I'm not sure if this is supported yet or not, so submitting it as a feature request in case it's not.  The docs gives an example of passing a selector to another selector, but I'm looking for a way to resolve this client side.

So for example.  
```
import {getByTestId, within} from '@testing-library/testcafe';

const myDiv = getByTestId('my-div'); //this is a Selector.

const myButton = within(myDiv).getByText("my button"); // within is another selector.

const within = (sel) => Selector(() => {
  return window.TestingLibraryDom.within(sel.resolveToDOMNode());
});

```
### What are you suggesting?

I'd like to have a 'resolveToDOMNode()' so that a selector can be resolved client side.

### What alternatives have you considered?

Another option I thought about was the ability to convert a selector to a xpath or css  query selector.  That would work as well if that's possible.

### Additional context

I'm happy to use an existing approach to solve this problem, but afaict from the docs I can't see any, but maybe i'm missing something.

**Comment by AlexKamaev** [comment]
> ```JS
> const within = (sel) => Selector(() => {
>   return window.TestingLibraryDom.within(sel.resolveToDOMNode());
> });
> ```

Judging by your code, you want to get an HTML element on the client side from the `sel` selector using the `resolveToDOMNode()` method.
If so, you can pass the `sel` selector as a [dependency](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/selector-options.html#optionsdependencies) of your new `within` selector.
Please see the following example:
```HTML
<body>
<div id="div">
    <button>my button</button>
</div>
</body>
```
```JS
const within = sel => {
    return Selector(() => {
        return sel();
    }, { dependencies: { sel } });
};

test(`Recreate invisible element and click`, async t => {
    await t.click(within(Selector('#div')).find('button'));
});
```

**Comment by benmonro** [comment]
ok @AlexKamaev when i try that I get an error saying 
```
   1) Selector code, arguments or dependencies cannot contain generators
      or "async/await" syntax (use Promises instead).```


```

but i'm not using any generators or async/await.  I'm trying to return an object/map of the query names so they can be used in the 'testing-library' approach.  example of what I'm trying to do is below:
```
const within = sel => {
    const queryName = 'getByText';

    return {
        [queryName]: Selector((...args) => {
            return window.TestingLibraryDom.within(sel())[queryName](...args);
        },
            { dependencies: { sel, queryName } })
    };
};

const queries = () => {
    const queryName = 'getByTestId';
    return { [queryName]: Selector((...args) => window.TestingLibraryDom[queryName](document.body, ...args), { dependencies: { queryName } }) }
}



test('works with nested selectors', async t => {
    // const nested = within(getByTestId('nested'));
    const { getByTestId } = queries();
    await t.expect(within(getByTestId('nested')).getByText('Button Text').exists).ok()

});
```

**Comment by benmonro** [comment]
I also tried using `.addCustomMethods` but I don't believe i can have a customMethod return a selector, can i?

**Comment by AndreyBelym** [comment]
Custom methods can return DOM nodes, but right now it's an internal extension to the `addCustomMethods` API. You can specify `{ returnDOMNodes: true }` as a second argument of `addCustomMethods` to enable this functionality: https://github.com/DevExpress/testcafe/blob/master/ts-defs/index.d.ts#L681. If you return a DOM node from a custom method, TestCafe will automatically map them to a basic Selector (without your custom properties/methods) and use this mapped Selector as a return value for your custom method.

**Comment by benmonro** [comment]
@AndreyBelym that doesn't seem to work for me, i get an error that says the customMethod i'm adding to the selector is not a function (but it is). `TypeError: nested.getByText is not a function`

my test looks like this:
```

test('works with nested selectors', async t => {
  const nested = within(getByTestId('nested'));

  await t.expect(nested.getByText('Button Text').exists).ok()

});
```

the within selector looks like this:
```
  return Selector(
      () => {
        return sel();
      }, { dependencies: { sel } })
      .addCustomMethods({
        getByText: (el, ...args) => {
          return window.TestingLibraryDom.within(el).getByText(...args);
        }
      }, { returnDOMNodes: true });
```


I have this all on a branch if you want to see: https://github.com/testing-library/testcafe-testing-library/blob/feature/no-more-evals/src/index.js#L67-L75

**Comment by AndreyBelym** [comment]
I have mentioned before that TestCafe doesn't add your custom methods to returned Selectors automatically. You can use the following approach to overcome this limitation:
```
function MySelector (baseSelector) {
    baseSelector.addCustomMethods({
        _myCustomMethodImpl () {
            return document.body
        }
    }, { returnDOMNodes: true });
   
    baseSelector.myCustomMethod = function () {
        const selector = this._myCustomMethodImpl();

        return MySelector(selector);
    }

    return baseSelector;
}
```

**Comment by AndreyBelym** [comment]
I've tried to play a bit with my example and found that custom methods added with the enabled `returnDOMNodes` option actually have a different signature:
```js
customMethod(nodes: Elements[], ...args: any[]): Selector
```

It means that they receive not a single element but **an array of elements** as a first parameter. So likely your example doesn't work due to your custom method returns an invalid value (e.g. `undefined`) due to a type of the first argument.

**Comment by benmonro** [comment]
@AndreyBelym, this is for my open source project testcafe-testing-library, a plugin for testcafe to use the testing-library approach to testing.  At the moment, I am kinda forced to do a whole bunch of `evals` in order to make it work.  if you can get 1 of my 3 broken tests working, I will A) be your best friend B) buy you a beer if we ever meet, C) add you as a contrib to that project. :)

🍺

**Comment by benmonro** [comment]
UPDATE @AndreyBelym I finally figured out what you meant about the customMethods using returnDOMNodes.  would be nice if that could be added to the documentation, its actually a pretty cool feature.  I also opened a new issue so that `{dependencies}` can be passed into those customMethods.  Thanks again for this, it has dramatically simplified the code of Testcafe testing library!

**Comment by LavrovArtem** [comment]
Thank you for your inquiry. Although we implemented this feature for internal use, we will discuss if we can make it public and document the `returnDOMNodes` flag accordingly in the near future.
