### ISSUE TITLE
clientScripts from runner are not found

### ISSUE THREAD

**Issue by svenakela** [DevExpress/testcafe#4309]
### What is your Test Scenario?
Running TestCafe programmatically, I can't invoke a clientScripts function in my test.

### What is the Current behavior?
The defined function added via `injectScripts` is not found from within the test code.
 
### What is the Expected behavior?
The expected behaviour should be to be able to call injected functions.
 
### What is your web application and your TestCafe test code?
I've written a simple test executed from a Node.js container:
```
   const scriptContent = `
    function getParameters() {
      return { kangarooId = '123456' };
    }
  `

  testcafe('localhost').then(cafe => {
    cafe.createRunner()
      .src('tests/testcafe.test.js')
      .clientScripts({ content: scriptContent })
      .reporter('json')
      .run()
      .then(result => {
        console.log(result);
      })
      .catch(err => {
        console.log(err);
      });
  })
```

The `testcafe.test.js` is like following:
```
import { Selector } from 'testcafe';
fixture `testcafe`
    .page `http://devexpress.github.io/testcafe/example`;
test('testcafe', async t => {
    await t.eval( () => getParameters() );
})
```

Log output is:
```
"An error occurred in eval code:\n\nReferenceError: getParameters is not defined\n\nBrowser: HeadlessChrome 76.0.3809 / Mac OS X 10.14.6\n\n    3 |\n    4 |fixture `testcafe`\n    5 |    .page `http://devexpress.github.io/testcafe/example`;\n    6 |\n    7 |test('testcafe', async t => {\n >  8 |    await t.eval( () => getParameters() );\n    9 |})\n   10 |\n\n   at eval (/Users/svenwesley/git/testcafewrapper/tests/testcafe.test.js:8:13)\n   at <anonymous> (/Users/svenwesley/git/testcafewrapper/tests/testcafe.test.js:7:1)\n   at <anonymous> (/Users/svenwesley/git/testcafewrapper/node_modules/testcafe/src/api/wrap-test-function.js:17:28)\n   at TestRun._executeTestFn (/Users/svenwesley/git/testcafewrapper/node_modules/testcafe/src/test-run/index.js:289:19)\n   at TestRun.start (/Users/svenwesley/git/testcafewrapper/node_modules/testcafe/src/test-run/index.js:338:24)"
```

### Steps to Reproduce:
1. Create a simple test, towards any website. Add a `clientScripts` content.
3. Run the test
 
### Your Environment details:
 
* testcafe version:                   1.5.0
* command-line arguments:  None, I invoke the runner from code (see above)
* browser name and version: HeadlessChrome 76.0.3809
* platform and version:           macOS 10.14.6

**Comment by Dmitry-Ostashev** [comment]
There is a syntax error in your script: 
`return { kangarooId = '123456' };`

I think this should look as follows:
`return { kangarooId: '123456' };`

**Comment by svenakela** [comment]
Unbelievable, you got me on one character... :smile:
