### ISSUE TITLE
The null reference exeption is thrown after login to office.com

### ISSUE THREAD

**Issue by aleks-pro** [DevExpress/testcafe#4311]
Run the following test example:
```js
import { Role, Selector } from 'testcafe';

fixture('My test');

const username = '***';
const password = '***';

const testrole = Role('https://login.microsoftonline.com/', async t => {
    await t
        .typeText(
            Selector('input').withAttribute('type', 'email'),
            username
        )
        .click(Selector('#idSIButton9'))
        .typeText(
            Selector('input').withAttribute('type', 'password'),
            password
        )
        .click(Selector('#idSIButton9'));
}, { preserveUrl: true });

test('Login', async t => {
    await t.navigateTo('https://www.office.com'); // Use your application URL here

    await t.useRole(testrole);

    await t.debug();
});
```
The error will occur:
![null_ref](https://user-images.githubusercontent.com/14822473/65426339-b47a3500-de18-11e9-8912-0f7cb83a36ba.png)

### Your Environment details:
 
* testcafe version:                   1.5.0
* node.js version:                    8.10.0
* command-line arguments:  chrom test.ts
* browser name and version: Chrome 76.0.3809.132 (Official Build) (64-bit)
* platform and version:          Windows 10

**Comment by miherlosev** [comment]
The origin error is not reproduced on the `testcafe@1.10.1` version.
But the login to the `login.office.com` is not performed successfully.

After entering the password, the site indicates about the problem.
![image](https://user-images.githubusercontent.com/4133518/103267746-48935e80-49c3-11eb-9337-de9a30298de4.png)

We need to investigate it.

**Comment by Farfurix** [comment]
```
Sorry, but we’re having trouble signing you in.

AADSTS90014: The required field 'request' is missing from the credential.
Ensure that you have all the necessary parameters for the login request.
```

This error appears only when I continue test execution without clicking "Yes" or "No" in the following dialog (I use a two-step verification):
![Capture](https://user-images.githubusercontent.com/30019338/145971826-997afde9-dcee-4364-b1c6-9c85792dc312.PNG)

It is possible to login (`testcafe@1.17.2-alpha.2`) by manually typing the verification code and clicking the "Stay signed in?" dialog option:
```js
import { Role, Selector } from 'testcafe';

fixture('My test')

const username = '**********';
const password = '**********';

const testrole = Role('https://login.microsoftonline.com/', async t => {
    await t
        .typeText(
            Selector('input').withAttribute('type', 'email'),
            username
        )
        .click(Selector('#idSIButton9'))
        .typeText(
            Selector('input').withAttribute('type', 'password'),
            password
        )
        .click(Selector('#idSIButton9'));

    await t.debug();
    // 1. Unlock the page when the test stops at this point.
    // 2. Enter the verification code (two-step verification) and click "Verify".
    // 3. Unlock the page and click "Yes" or "No" in the "Stay signed in?" dialog.
}, { preserveUrl: true });

test('Login', async t => {
    await t.navigateTo('https://www.office.com'); // Use your application URL here

    await t.useRole(testrole);

    await t.debug();
});
```
