### ISSUE TITLE
prepare and manipulate tests from runner

### ISSUE THREAD

**Issue by haubitzer** [DevExpress/testcafe#4313]
### What is your Test Scenario?
Provide a way to manipulate tests before they are executed from the runner.
There should be a way to set `fixtures`, `pageUrl`, etc.  

### What are you suggesting?
A function to set an async function that is called before the tests are executed, the same way as filters.

For example some thing like this: `runner.prepareTests(async function(tests)) `

/src/runner/index.js line 443
```
run (options = {}) {
        this.apiMethodWasCalled.reset();
        this.configuration.mergeOptions(options);
        this._setBootstrapperOptions();
        const runTaskPromise = Promise.resolve()
            .then(() => this._validateRunOptions())
            .then(() => this._createRunnableConfiguration())
            .then(async ({ reporterPlugins, browserSet, tests, testedApp, commonClientScripts }) => {
                await this._prepareClientScripts(tests, commonClientScripts);

                //add here the callback function: await this._prepareTests(tests);

                return this._runTask(reporterPlugins, browserSet, tests, testedApp);
            });

        return this._createCancelablePromise(runTaskPromise);
```

**Comment by Dmitry-Ostashev** [comment]
According to your description, you goal is to change pageUrl dynamically for tests and fixtures.To accomplish this task you can define this url in a separate file and import it as you need. Also take a look at this issue: https://github.com/DevExpress/testcafe/issues/1932. 

Is there any another scenario for your suggestion?
