### ISSUE TITLE
Testcafe command not found

### ISSUE THREAD

**Issue by remram** [DevExpress/testcafe#4314]
### What is your Test Scenario?

I didn't run any test yet, because **testcafe** command is still missing on my system!
 
### What is the Current behavior?

I'm getting a warning during the installation of testcafe regarding the version of core-js.
`npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.`

At the end of the installation I have received the following message:
`+ testcafe@1.5.0`
`added 427 packages from 295 contributors in 48.274s`

When I run 
`npm ls -g testcafe`
I receive the following message:
`C:\Users\MyNameOrWhat\AppData\Roaming\npm`
`-- testcafe@1.5.0`
 
### What is the Expected behavior?

When I run `testcafe chrome demo_test.js`
I was expecting, that the test will start and will run the test inside the chrome browser!
But I'm receiving the following message instead: `The command "testcafe" is either written incorrectly or
could not be found.`
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from 'testcafe';

fixture("Demo fixture")
    .page("https://www.demo-fixture.com");

test("Doing a demo test", async (t) => {

    const loginEmail = Selector('.inputText__input.mx-50[name=\"email\"]');
    const loginPassword = Selector('.inputText__input.mx-50[name=\"password\"]');
    const signIn = Selector('#app').find('div').find('div').nth(8).find('div').find('div').find('div').find('div').find('div').find('div').find('form').find('div').nth(7).find('button');
    const demoHeader = Selector('h1');

    await t
        .typeText(loginEmail, 'test@demo-fixture.com')
        .typeText(loginPassword, 'DemoTestPass')
        .click(signIn)
        .expect(demoHeader.textContent).contains('Great you made it!');
});
```
</details>

 
### Your Environment details:
 
* testcafe version: 1.5.0          
* node.js version: v10.16.3     
* command-line arguments: `testcafe chrome demo_test.js` 
* browser name and version: Chrome v76.0.... 
* platform and version: Window 10, v10.0.17763 Build 17763         
* other:

**Comment by Dmitry-Ostashev** [comment]
It seems TestCafe was not installed correctly on your machine. Check if the file `C:\Users\MyNameOrWhat\AppData\Roaming\npm\testcafe.cmd` exists. 
Also you can try to reinstall TestCafe.

**Comment by remram** [comment]
Thank you @Dmitry-Ostashev for your reply. 
Yes the file does exists and here is the content:

```sh
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\node_modules\testcafe\bin\testcafe-with-v8-flag-filter.js" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\node_modules\testcafe\bin\testcafe-with-v8-flag-filter.js" %*
)
```

I also reinstalled it several time... It didn't help, this is why I have opened this ticket.

**Comment by LavrovArtem** [comment]
Hello @remram,
I think that you have an issue with the `PATH` environment variable, but not TestCafe. Make sure that it contains the `C:\Users\MyNameOrWhat\AppData\Roaming\npm` directory. You can display the value of the `PATH` environment variable with the following command: 
```
echo %PATH%
echo $env:PATH
```
Also, you can test another module by installing the `cowsay` module globally and execute the `cowsay TestCafe` command to confirm this. So, I'll close this issue.
