### ISSUE TITLE
Page model doesn't fully inherit test controller objects

### ISSUE THREAD

**Issue by Kataract** [DevExpress/testcafe#4315]
### What is your Test Scenario?
I'd like to use the Page model to keep my actual tests as DRY as possible.  Inside one of my page classes I have something like:
```
import { Selector, t } from 'testcafe';

import { runAxe } from '../../helpers';

class Page {
    constructor() {
        this.emailOrUser = Selector('#username');
        this.password = Selector('#password');
        this.submitButton = Selector('#button-submit');
    }

    async submitLogin(username, password) {
        await runAxe(); // this is just a wrapper around https://github.com/helen-dikareva/axe-testcafe
        await t
            .typeText(this.emailOrUser, username)
            .typeText(this.password, password)
            .click(this.submitButton);
    }
}

export default new Page();
```
where I'm importing `t` to do a combination of [Step 7 of the Page model docs](https://devexpress.github.io/testcafe/documentation/recipes/extract-reusable-test-code/use-page-model.html#step-7---add-actions-to-the-page-model) and the [create helpers docs page](https://devexpress.github.io/testcafe/documentation/recipes/extract-reusable-test-code/create-helpers.html)

 
### What is the Current behavior?
The test fails with `1) The "boundTestRun" option value is expected to be a test controller.`.  When adding a logging line to `axe-testcafe`, I get an object that looks like this instead of the full test controller:
```
[Object: null prototype] {
  click: [Function: fn],
  rightClick: [Function: fn],
  doubleClick: [Function: fn],
  hover: [Function: fn],
  drag: [Function: fn],
  dragToElement: [Function: fn],
  typeText: [Function: fn],
  selectText: [Function: fn],
  selectTextAreaContent: [Function: fn],
  selectEditableContent: [Function: fn],
  pressKey: [Function: fn],
  wait: [Function: fn],
  navigateTo: [Function: fn],
  setFilesToUpload: [Function: fn],
  clearUpload: [Function: fn],
  takeScreenshot: [Function: fn],
  takeElementScreenshot: [Function: fn],
  resizeWindow: [Function: fn],
  resizeWindowToFitDevice: [Function: fn],
  maximizeWindow: [Function: fn],
  switchToIframe: [Function: fn],
  switchToMainWindow: [Function: fn],
  eval: [Function: fn],
  setNativeDialogHandler: [Function: fn],
  getNativeDialogHistory: [Function: fn],
  getBrowserConsoleMessages: [Function: fn],
  expect: [Function: fn],
  debug: [Function: fn],
  setTestSpeed: [Function: fn],
  setPageLoadTimeout: [Function: fn],
  useRole: [Function: fn],
  addRequestHooks: [Function: fn],
  removeRequestHooks: [Function: fn]
}
```

 
### What is the Expected behavior?
I would expect to see a full test controller object passed down and the test passes.

It's worth noting that this _does_ work as intended if I call it directly from the test, but my hope was to avoid repetition by moving some/all of these kinds of calls to functions in the page classes I was building.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):  I can't provide a link but this is page-agnostic

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector, t } from 'testcafe';

import { runAxe } from '../../helpers';

class Page {
    constructor() {
        this.emailOrUser = Selector('#username');
        this.password = Selector('#password');
        this.submitButton = Selector('#button-submit');
    }

    async submitLogin(username, password) {
        await runAxe(); // this is just a wrapper around https://github.com/helen-dikareva/axe-testcafe
        await t
            .typeText(this.emailOrUser, username)
            .typeText(this.password, password)
            .click(this.submitButton);
    }
}

export default new Page();

// this is the helper wrapper I'm calling:
import { axeCheck, createReport } from 'axe-testcafe';
import chalk from 'chalk';
import { Selector, t } from 'testcafe';

export const runAxe = async () => {
    const { error, violations } = await axeCheck(t);
    if (violations.length) {
        const highlighted = `${chalk.keyword('orange')(
            `axe results for page:`
        )}`;
        const output = `${highlighted}\n${createReport(violations)}`;
        console.warn(output);
    }
    // Uncomment me when warnings become failures
    // await t.expect(violations.length === 0).ok(createReport(violations));
};
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
  "pageLoadTimeout": 60000,
  "selectorTimeout": 60000,
  "assertionTimeout": 60000,
  "screenshotPath": "testcafe/reports/",
  "takeScreenshotsOnFails": true,
  "browsers": "chrome:headless"
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```
[kpassen@worktop:repo] [git@kat/branch]$ yarn testcafe testcafe/account/test-universal-login.js
yarn run v1.17.3
$ /Users/kat.passen/repo/node_modules/.bin/testcafe testcafe/account/test-universal-login.js
 Running tests in:
 - HeadlessChrome 77.0.3865 / Mac OS X 10.14.6

 ✖ Test succeeds (screenshots: /Users/kat.passen/repo/testcafe/reports/2019-09-23_10-23-33/test-1/HeadlessChrome_77.0.3865_Mac_OS_X_10.14.6/errors/1.png)

   1) The "boundTestRun" option value is expected to be a test controller.

      Browser: HeadlessChrome 77.0.3865 / Mac OS X 10.14.6
      Screenshot: /Users/kat.passen/repo/testcafe/reports/2019-09-23_10-23-33/test-1/HeadlessChrome_77.0.3865_Mac_OS_X_10.14.6/errors/1.png

         40 |    return reset(report);
         41 |
         42 |};
         43 |
         44 |const axeCheck = async (t, context, options) => {
       > 45 |    const hasScript = await hasAxe.with({ boundTestRun: t })();
         46 |    if (!hasScript)
         47 |        await injectAxe.with({ boundTestRun: t })();
         48 |
         49 |    try {
         50 |        return await runAxe.with({ boundTestRun: t })(context, options);

         at axeCheck (/Users/kat.passen/repo/node_modules/axe-testcafe/index.js:46:40)
         at <anonymous> (/Users/kat.passen/repo/testcafe/helpers.js:144:41)
         at step (/Users/kat.passen/repo/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
         at <anonymous> (/Users/kat.passen/repo/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14)
         at new F (/Users/kat.passen/repo/node_modules/core-js/library/modules/_export.js:36:28)
         at <anonymous> (/Users/kat.passen/repo/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
         at runAxe (/Users/kat.passen/repo/testcafe/helpers.js:143:14)
         at <anonymous> (/Users/kat.passen/repo/testcafe/account/pages/universal-login.js:14:15)
         at step (/Users/kat.passen/repo/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
         at <anonymous> (/Users/kat.passen/repo/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14)



 1/1 failed (5s)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Write a test that uses a `Page()`, which has a function that calls a helper like `axeCheck()` that relies on having a test controller object
3. Run the test
4. Test should fail when the helper receives a bad test controller object
 
### Your Environment details:
 
* testcafe version:  1.3.0                 
* node.js version:  v12.4.0                  
* command-line arguments:  
* browser name and version:  headless Chrome 77 
* platform and version:  macOS 10.14        
* other:

**Comment by LavrovArtem** [comment]
This information is not sufficient to find the cause of the issue.  There's no way to know what calls the `runAxe` function and where. All functions related to the test controller must be called in the context of the test. Could you please share your test?

**Comment by Kataract** [comment]
I made a really short reduced test case here: https://github.com/Kataract/literate-parakeet

Running `yarn testcafe test/test-app.js` with the server running will get you the failure I see.

**Comment by Dmitry-Ostashev** [comment]
As you can see in the error message, the axe-testcafe module uses the boundTestRun option. This option requires the test context `t` from the test  `test('Test', async t => {})` to determine required test context. 

I suggest you pass the test controller directly from your test:

app.js:
```
import { Selector } from 'testcafe';
//...

class Page {
    constructor() {}

    async submitForm(t) {
        //...
        const { error, violations } = await axeCheck(t);
        //...
    }
}
```


test-app.js:
```
//...
test('Ok', async t => {
    await page.submitForm(t);
});
```

**Comment by Kataract** [comment]
Ok, I'll update our tests to do that instead. Thank you 👍

**Comment by VasilyStrelyaev** [comment]
Thank you, @Kataract!
 
We will perform additional research to determine why the `boundTestRun` controller is not resolved automatically.

**Comment by hyunil-shin** [comment]
This issue might be related to yarn. With npm install, everything is ok. But with yarn install, there is error with boundTestRun. The only difference is npm and yarn. Recently, I try to use yarn as package manager for caching.

**Comment by arubtsov** [comment]
Hello @hyunil-shin,

TestCafe behavior should not depend on the package manager you are using. You can try to run the test in the example shared by @Kataract and see the same error for both of them.

**Comment by miherlosev** [comment]
Hi @Kataract 

The [axeCheck](https://github.com/helen-dikareva/axe-testcafe/blob/2f641856338e99dee6472e9683e5b8e71c40964a/index.js#L45) accepts a valid test controller value.

The `t` value that is imported from `testcafe` is not a regular test controller value, so it cannot be used as a value for the `boundTestRun` parameter. At present, we don't have plans to improve test controller detection in such cases. So, the recommended way is to pass the test controller as a parameter (as mentioned in https://github.com/DevExpress/testcafe/issues/4315#issuecomment-535873880).
