### ISSUE TITLE
 A JavaScript error occurred while click the submit button

### ISSUE THREAD

**Issue by RemigiusL** [DevExpress/testcafe#4318]
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by LavrovArtem** [comment]
This issue has no information about reproducing. So, I'll close this issue. Feel free to reopen it after filling the full bug template.
