### ISSUE TITLE
How to switch control from child window to parent window and parent window into child window in testcafe ?

### ISSUE THREAD

**Issue by RemigiusL** [DevExpress/testcafe#4320]
How to switch control from child window to parent window and parent window into child window in testcafe ?

**Comment by LavrovArtem** [comment]
TestCafe provides the next [API](https://devexpress.github.io/testcafe/documentation/test-api/working-with-iframes.html) for working with iframes.

Thank you for your inquiry. This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - a platform for users to ask and answer questions.

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)).
