### ISSUE TITLE
Type Error occurs when creating a Role in the coded step of a raw API test

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe#4326]
### What is your Test Scenario?
Use Role in the coded step in TestCafe Studio
 
### What is the Current behavior?
The following error occurs:

> - Error in Role initializer -
> TypeError: Cannot read property 'match' of undefined

### What is the Expected behavior?
It should work without errors
 
### What is your web application and your TestCafe test code?
 
```js
 const regularUser = Role('https://semantic-ui.com/examples/login.html', async t => {
    await t
        .typeText(Selector('input').withAttribute('name', 'email'), 'mail@example.com')
        .typeText(Selector('input').withAttribute('name', 'password'), '123456')
        .click(Selector('div').withText('Login'));
});

await t.useRole(regularUser);
```
</details>

### Steps to Reproduce:
1. Create a raw API test with the coded step as described above
2. Run it
 
### Your Environment details:
 
* testcafe version:                   1.5.0
* node.js version:                    10.16.0
* command-line arguments:  `testcafe chrome code-step-login.testcafe`
* browser name and version: Chrome 76
* platform and version:          Win 10

**Comment by miherlosev** [comment]
Steps to reproduce:
* Run TestCafe Studio
* Create a new fixture
* Create a new test
* Add the `Run TestCafe Script` action
* Put the code 
```js
const regularUser = Role('https://semantic-ui.com/examples/login.html', async t => {
    await t
        .typeText(Selector('input').withAttribute('name', 'email'), 'mail@example.com')
        .typeText(Selector('input').withAttribute('name', 'password'), '123456')
        .click(Selector('div').withText('Login'));
});

await t.useRole(regularUser);
```
to it
* Run the test
* Got the following error
![image](https://user-images.githubusercontent.com/4133518/104698863-01c39980-5723-11eb-86f0-91b841e09999.png)

**Comment by Dmitry-Ostashev** [comment]
I cannot reproduce the issue with TestCafe 1.15.0 and later. Let's close it.
