### ISSUE TITLE
Add capability to use the 'fixtureCtx' in a Role

### ISSUE THREAD

**Issue by benmonro** [DevExpress/testcafe#4328]
### What is your Test Scenario?

 I have to create a unique session id in the beforeEach for my fixture, i am then setting that session id in context:
```
fixture`banner`
    .beforeEach(async t => {
        t.fixtureCtx.sessionId = await registerSession();
    })
```

I would then like to access that context in a user role:
```
export const anonymousUser = Role(BASE_URL, async t => {
    const sessionId = t.fixtureCtx.sessionId;
    console.log({ sessionId });
});
```
### What is the Current behavior?

 currently I can get the context in the test, but not in the role.

### What is the Expected behavior?

to be able to set the context in the beforeEach and access it in the role. 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by miherlosev** [comment]
Hi @benmonro 

Thank you for you suggestion. We will consider to implement this feature in the future.
If this feature is important for you, the PR is very appreciated.
