### ISSUE TITLE
How can I build local development environment

### ISSUE THREAD

**Issue by sivanisentinel** [DevExpress/testcafe#4332]
Hi,
I want to contribute to testcafe and not sure how to build your project and create the required lib folder.
can you help me with that?

Thanks,
Sivan

**Comment by miherlosev** [comment]
Hi @sivanisentinel 

See the [Contribution guide](https://github.com/DevExpress/testcafe/blob/master/CONTRIBUTING.md) wit step-by-step instructions.

**Comment by sivanisentinel** [comment]
Obviously I have read this and it’s missing the build process info.

**Comment by AlexKamaev** [comment]
As far as I see you got stuck only on the build process. I assume that you have already created a fork.
If so, you just need to run the 'gulp build' command to build all sources and check them with 'eslint'.
If you do not want to lint your files you can use the 'gulp fast-build' command.
After one of the these commands is completed you will get the 'lib' directory.
Please ensure that you have the `gulp` module installed globally.
