### ISSUE TITLE
Testcafe safari with mac in azure devops

### ISSUE THREAD

**Issue by andrew-vdb** [DevExpress/testcafe#4333]
Is this supported scenario?

Can't figure it out on how to make it work
![image](https://user-images.githubusercontent.com/12871379/65698106-5057ab00-e07c-11e9-80ed-a80568c01983.png)

**Comment by andrew-vdb** [comment]
It works on mac 10.13!
![image](https://user-images.githubusercontent.com/12871379/65700262-a11cd300-e07f-11e9-9776-b7289a778f79.png)

**Comment by andrew-vdb** [comment]
Ok its not working on mac 10.14 for sure, will you fix this?

**Comment by VasilyStrelyaev** [comment]
Thank you for reporting this. I have reproduced this behavior.

Most likely, the reason for this error is that macOS does not permit TestCafe to run Safari.

When an application tries to a start or control a different program, macOS 10.14 asks the user for a permission. In the case of a CI agent running on a VM, there is no user to grant these permissions.

You can try the following approaches to work around this issue:

* Run the Azure DevOps agent on a real Mac where TestCafe has the required permissions.
* Run tests on macOS 10.13.
