### ISSUE TITLE
dependencies for addCustomMethods with `returnDOMNodes`

### ISSUE THREAD

**Issue by benmonro** [DevExpress/testcafe#4337]
### What is your Test Scenario?

would be nice to be able to pass `{dependencies}` to a `customMethod` that's using `returnDOMNodes:true`.  I am utilizing this undocumented feature (also please add docs 😄 for this its cool!)
### What are you suggesting?

adding the ability to pass in a `{dependenceis}` object as you can do with any other selector.  otherwise you are forced to use `eval` to pass in variables that are out of scope.

### What alternatives have you considered?

using eval 😢 
### Additional context

this is for testcafe testing library where i am dynamically adding the queries from DTL into the selector.

https://github.com/DevExpress/testcafe/blob/e7790ccad7a67b3962d7df16c117c88144faed04/test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-test.js#L1039-L1042

https://github.com/DevExpress/testcafe/blob/e7790ccad7a67b3962d7df16c117c88144faed04/test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-test.js#L1039-L1042

**Comment by arubtsov** [comment]
Hello @benmonro,
 
Thank you for your suggestion. Our team will need some time to discuss the possibility of its implementation.
