### ISSUE TITLE
Testcafe - failed to create screenshot fails with Error: ENOTDIR: not a directory, mkdir 

### ISSUE THREAD

**Issue by rmkanda** [DevExpress/testcafe#4339]
Testcafe fails to save screenshots

```
 ~/learning/testcafe-sample  testcafe specs/ -S -s screenshots -p '${DATE}_${TIME}/test-${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.png'
Using locally installed version of TestCafe.
The "screenshotPath", "screenshotPathPattern" options from the configuration file will be ignored.
 Running tests in:
 - Chrome 77.0.3865 / Mac OS X 10.14.6
 - Firefox 69.0.0 / Mac OS X 10.14.0

 Application Login
 ✓ Valid login test (screenshots: /Users/rmkanda/learning/testcafe-sample/screenshots)


 1 passed (9s)

 Warnings (3):
 --
  The file at "/Users/rmkanda/learning/testcafe-sample/screenshots" already exists. It has just been rewritten with a recent screenshot. This
  situation can possibly cause issues. To avoid them, make sure that each screenshot has a unique path. If a test runs in multiple browsers, consider
  including the user agent in the screenshot path or generate a unique identifier in another way.
 --
  Was unable to take a screenshot due to an error.

  Error: ENOTDIR: not a directory, mkdir
  '/Users/rmkanda/learning/testcafe-sample/screenshots/2019-09-30_11-46-38/test-1/Chrome_77.0.3865_Mac_OS_X_10.14.6'
 --
  Was unable to take a screenshot due to an error.

  Error: ENOTDIR: not a directory, mkdir
  '/Users/rmkanda/learning/testcafe-sample/screenshots/2019-09-30_11-46-38/test-1/Firefox_69.0.0_Mac_OS_X_10.14.0'
 ~/learning/testcafe-sample 
```
### Steps to Reproduce:

.testcaferc.json
```
{
  "browsers": ["chrome", "firefox"],
  "concurrency": 1,
  "speed": 1,
  "pageLoadTimeout": 3000,
  "selectorTimeout": 10000,
  "assertionTimeout": 3000,
  "takeScreenshotsOnFails": true,
  "screenshotPath": "/Users/rmkanda/learning/testcafe-sample/reports/screenshots/",
  "screenshotPathPattern": "test-${TEST_INDEX}-${USERAGENT}-${FILE_INDEX}.png",
  "debugOnFail": true
}
```
### Environment details:
 
* testcafe version: 1.5.0
* node.js version:   v10.16.3
* platform and version: macOS 10.14.6

**Comment by rmkanda** [comment]
@AlexKamaev @AndreyBelym Is this commit https://github.com/DevExpress/testcafe/commit/0c393b2ba2ba472188f8cea381d60edf09dcc994 is to resolve the above issue?

**Comment by Farfurix** [comment]
@rmkanda 

Hello,

I wasn't able to reproduce the issue under TestCafe v1.5.0 / macOS 10.14.6. I tried to run TestCafe with the following files:
**/Users/testuser/Desktop/tmp/.testcaferc.json**:
```
{
  "browsers": ["chrome", "firefox"],
  "src": "/Users/testuser/Desktop/tmp/test.js",
  "takeScreenshotsOnFails": true,
  "screenshotPath": "/Users/testuser/Desktop/tmp/reports/screenshots/",
  "screenshotPathPattern": "test-${TEST_INDEX}-${USERAGENT}-${FILE_INDEX}.png"
}
```

**/Users/testuser/Desktop/tmp/test.js**:
```js
import { Selector } from 'testcafe';

fixture `My fixture`
    .page `http://devexpress.github.io/testcafe/example/`;

test('test', async t => {
    await t
        .expect(false).ok();
});
```

Command (run it from /Users/testuser/Desktop/tmp/):
```
testcafe
```
As a result, all screenshots were created without any warning.

Could you please share with us your sample project (like the above files). We will check it on our side.

**Comment by rmkanda** [comment]
@Farfurix Please find the sample code base here - https://github.com/rmkanda/testcafe-sample

**Comment by miherlosev** [comment]
Hi @rmkanda 

I got this error when I ran your example.
![image](https://user-images.githubusercontent.com/4133518/66029094-47952800-e507-11e9-9c9f-fc9c554f0cff.png)

Please correct the example.

**Comment by rmkanda** [comment]
@miherlosev Please try now... Updated the credentials of demo site...

**Comment by AlexKamaev** [comment]
@rmkanda I found the cause of the issue. You have the following line in your `login/index.js` code:
```JS
await t.takeScreenshot("./");
```
This is incorrect. If you want to specify the screenshot path in the command, you need to specify the extension as well. However, since you already have the correct screenshot configuration in `.testcaferc.json`, I suppose that it's a mistake.

I've changed this line to
```JS
await t.takeScreenshot();
```
Now it works as expected and all your configurations settings are applied now.

**Comment by rmkanda** [comment]
@AlexKamaev My bad. Thanks for pointing out.
