### ISSUE TITLE
Get tests to be run via cli, without actually running.

### ISSUE THREAD

**Issue by danlomantoSamsungNext** [DevExpress/testcafe#4340]
### What is your Test Scenario?
I'm looking to create a test "coverage" report.  Or a simple way to create a list of test cases that would be run given a set of fixture/test meta filters. This way I can easily document the test cases that have been created and that are being executed in our test automation suite.

### What are you suggesting?
I'm looking to see what tests would be run given a set of both fixture and test meta filters, WITHOUT the tests actually being run.  So in essence, I would like a created report to have the following info:
- Fixture Name
- All Fixture Metadata
- Test Name
- All Test Metadata

It would also be nice (although not absolutely necessary) to have the tests grouped by Fixture in the created report file.

### What alternatives have you considered?
To temporarily accomplish this, I've added a logger to every "beforeEach()" test method that will add to a text file, the information I'm looking for (Fixture Name, Test Name, etc.).  However, I have to actually run all the tests in order to generate my log, which can take a bit of time for E2E tests. 

I also currently have to run the tests in serial so that the tests are grouped by fixture in my text file.  Running tests concurrently causes all the tests to be intermingled and not be grouped by fixture. Which is expected.

**Comment by Farfurix** [comment]
@danlomantoSamsungNext 

Hello,

Thank you for your suggestion.
At present, we don't have plans to implement this functionality.

You can create a list from each test file and process it. I prepared a simple sample - "get all tests":

**script.js**:
```js
const fs = require('fs');

const getTestListFromCode           = require('testcafe').embeddingUtils.getTestListFromCode;
const getTypeScriptTestListFromCode = require('testcafe').embeddingUtils.getTypeScriptTestListFromCode;

const codeFromJs = fs.readFileSync('d:/tst/i4340/test.js', 'utf8');
const jsonFromJs = getTestListFromCode(codeFromJs);

const codeFromTs = fs.readFileSync('d:/tst/i4340/test1.ts', 'utf8');
const jsonFromTs = getTestListFromCode(codeFromTs);

console.log('----------- JS -----------');
console.log('Fixture:')
console.log(jsonFromJs);
console.log('Tests in the "fixture1":')
console.log(jsonFromJs[0].tests); // tests in the fixture

console.log('----------- TS -----------');
console.log('Fixture:')
console.log(jsonFromTs);
console.log('Tests in the "fixture1":')
console.log(jsonFromTs[0].tests); // tests in the fixture
```

Command:
```
node script.js
```

**test.js**:
```
import { Selector } from 'testcafe';

fixture `fixture1`
    .meta('key1', 'value1')
    .page `http://devexpress.github.io/testcafe/example/`;

test
    .meta('key2', 'value2')
    ('test1', async t => {
        await t
            .expect(false).ok();
    });

test
    .meta('key3', 'value3')
    ('test2', async t => {
        await t
            .expect(false).ok();
    });

```
**test1.ts**:
```
import { Selector } from 'testcafe';

fixture `fixture1`
    .meta('key4', 'value4')
    .page `http://devexpress.github.io/testcafe/example/`;

test
    .meta('key5', 'value5')
    ('test1', async t => {
        await t
            .expect(false).ok();
    });

test
    .meta('key6', 'value6')
    ('test2', async t => {
        await t
            .expect(false).ok();
    });
```

Result:
![Capture](https://user-images.githubusercontent.com/30019338/65969895-3ba95780-e46e-11e9-81b3-a7d5c36372c2.PNG)

**Comment by danlomantoSamsungNext** [comment]
@Farfurix  Thank you so much!!!

**Comment by danlomantoSamsungNext** [comment]
@Farfurix I'm getting the following error when running the code:
```
/Users/#########/dev/whisk/whiskapis-tests/node_modules/testcafe/lib/compiler/test-file/formats/typescript/get-test-list.js:98
        while (exp.kind !== this.tokenType.Identifier) {
                   ^

TypeError: Cannot read property 'kind' of undefined
    at TypeScriptTestFileParser.analyzeMemberExp (/Users/#########/dev/whisk/whiskapis-tests/node_modules/testcafe/lib/compiler/test-file/formats/typescript/get-test-list.js:98:20)
    at TypeScriptTestFileParser.analyzeFnCall (/Users/#########/dev/whisk/whiskapis-tests/node_modules/testcafe/lib/compiler/test-file/formats/typescript/get-test-list.js:156:29)
    at TypeScriptTestFileParser.analyzeToken (/Users/#########/dev/whisk/whiskapis-tests/node_modules/testcafe/lib/compiler/test-file/test-file-parser-base.js:153:29)
    at TypeScriptTestFileParser.analyzeToken (/Users/#########/dev/whisk/whiskapis-tests/node_modules/testcafe/lib/compiler/test-file/test-file-parser-base.js:139:29)
    at /Users/#########/dev/whisk/whiskapis-tests/node_modules/testcafe/lib/compiler/test-file/test-file-parser-base.js:162:35
    at Array.forEach (<anonymous>)
    at TypeScriptTestFileParser.collectTestCafeCalls (/Users/#########/dev/whisk/whiskapis-tests/node_modules/testcafe/lib/compiler/test-file/test-file-parser-base.js:161:17)
    at TypeScriptTestFileParser.analyze (/Users/#########/dev/whisk/whiskapis-tests/node_modules/testcafe/lib/compiler/test-file/test-file-parser-base.js:170:39)
    at TypeScriptTestFileParser.parse (/Users/#########/dev/whisk/whiskapis-tests/node_modules/testcafe/lib/compiler/test-file/formats/typescript/get-test-list.js:179:21)
    at TypeScriptTestFileParser.getTestListFromCode (/Users/#########/dev/whisk/whiskapis-tests/node_modules/testcafe/lib/compiler/test-file/test-file-parser-base.js:200:21)
```


Do you know what could be causing this by any chance? I'm getting output for some tests, but not for all of my test files. One thing that may be causing it is having a data-driven test like this:
```
[
  null,
  '',
  '      '
].forEach(testName => {
  test.meta(`category`, `regression`)(
    `will try to create an object with a name of: '${testName}'`,
    async test => {
      // Do test stuff
    });
});
```

Any thoughts? Thanks!

**Comment by danlomantoSamsungNext** [comment]
Yeah, it definitely looks related to using that data-driven type test.

**Comment by aleks-pro** [comment]
Hello @danlomantoSamsungNext ,

Please provide a simple example project so we will be able to reproduce the error on our side.

**Comment by danlomantoSamsungNext** [comment]
@aleks-pro  Here is an example test file:
```
import { Selector } from 'testcafe';

fixture `Data-Driven Tests`
    .page `https://devexpress.github.io/testcafe/example/`;

[
    null,
    '',
    '     '
].forEach(name => {
    test(`Enter '${name}'`, async t => {
        await t
            .typeText('#developer-name',name)
            .click('#submit-button')
            .expect(Selector('#article-header').textContent).notEql(name);
    });
});
```

**Comment by AlexKamaev** [comment]
I'm afraid the described approach is not suitable for this data-driven case. The parser can analyze only static test files. So, probably, even if we fix the issue in the Typescript parser, this will not help to achieve your goal.
