### ISSUE TITLE
Wrong element is clicked (the minimized left page menu case)

### ISSUE THREAD

**Issue by Farfurix** [DevExpress/testcafe#4342]
https://www.devexpress.com/Support/Center/Question/Details/T819135/clicking-wrong-elements

https://github.com/DevExpress/testcafe-studio/issues/2770

It works fine under Windows 10 / Chrome (if we have the **maximized left page menu**).
Workaround: `t.maximizeWindow()`.

**Comment by AlexKamaev** [comment]
Not a bug
The original issues has two causes:
1) Wrong selector
2) Site has `zoom` which is not supported
I described the issue in details in the corresponding SC ticket
