### ISSUE TITLE
Show all links to all cloud test sessions in concurrency mode

### ISSUE THREAD

**Issue by aleks-pro** [DevExpress/testcafe#4346]
Run multiple tests in concurrency mode on BrowserStack. A resulting report will contain the same link for every failed test. Even if tests were failed in different sessions.
You can use the attached example project to reproduce the issue.
Command: `testcafe -c 4 "browserstack:Chrome" "./tests/*.js" -r xunit:res.xml`
[examples.zip](https://github.com/DevExpress/testcafe/files/3682032/examples.zip)

* testcafe version:                   1.5.0

**Comment by AndreyBelym** [comment]
The same for SauceLabs: https://github.com/DevExpress/testcafe-browser-provider-saucelabs/issues/78.
