### ISSUE TITLE
Handle Popup? We get white page now

### ISSUE THREAD

**Issue by rduinmaijer** [DevExpress/testcafe#4348]
**How to handle a popup with testcafe?**

### What is your Test Scenario?
We press a button and than a popup is opened. In that popup we select something and then the popup is closed again and that info is being used in the main page (which was still open in the background.
The behavior looks something like this: https://www.quackit.com/html/codes/html_popup_window_code.cfm
 
### What is the Current behavior?
However when trying this with testcafe the popup is full-sized and doesn't go back to the main page (maybe a relation is lost?)
 
### What is your web application and your TestCafe test code?
The behavior looks something like this: https://www.quackit.com/html/codes/html_popup_window_code.cfm

The button looks something like this in the code:
```
<input type="button" value="Calculate prices" onclick="if(check_fields(tmp_arr) &amp;&amp; check_positive_value_highlight(document.getElementsByName('value')[0], true) &amp;&amp; check_empty_() &amp;&amp; true) { showBig_v2('popup_thingie_cost.asp?formname=getInfo&amp;fieldname11=xx&amp;fieldname5=xx&amp;fieldname6=xx&amp;bgcolor=white&amp;fieldname10=xx&amp;fieldname12=xxx&amp;title=Choose+x+service&amp;footer=YES&amp;vat=NO&amp;default_off=YES&amp;type=xx&amp;fieldname4=xx&amp;fieldname1=xx;xx=&amp;xx=xx&amp;xx=&amp;xx=&amp;xx=&amp;xx=&amp;xx=&amp;xx=&amp;language=EN&amp;xx=&amp;xx=&amp;xx='); }">
```
Any tips?

**Comment by AlexKamaev** [comment]
https://stackoverflow.com/questions/58214970/handle-popup-we-get-white-page-now
