### ISSUE TITLE
Can't scroll to the drag target element in iframe in IE11

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#4350]
### What is your Test Scenario?
Drag an element located in an iframe, that is not visible in the viewport.

### What is the Current behavior?
TestCafe fails with the `Element doesn't exist` error.
 
Workaround: add a step, that hovers iframe's `<body>`.
```js
await t.switchToIframe('iframe');
await t.hover('body')
```

### What is the Expected behavior?
TestCafe should scroll iframe's parent and be able to drag the target element.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example): https://demos.devexpress.com/Bootstrap/GridView/Adaptivity.aspx

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 fixture`test`.page`https://demos.devexpress.com/Bootstrap/GridView/Adaptivity.aspx`;

test('test', async t => {
    await t.resizeWindow(1420, 760);

    await t.switchToIframe('#content > div:nth-child(11) > div.demo-device-container > div.demo-device.bg-secondary.border.border-secondary.qrcode-container > div > iframe');
    // NOTE: uncomment the line below to fix the test
    // await t.hover('body')

    await t.drag('#ctl05_GridViewAdaptiveLayout_col1', 200, 0);
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.5.0
* node.js version:                    10.15.0
* command-line arguments:  testcafe ie test.js
* browser name and version: IE 11
* platform and version:          
* other:

**Comment by miherlosev** [comment]
The problem is not reproduced with `testcafe@1.10.1`.
