### ISSUE TITLE
Is there a way to name the output file of a report dynamically like screenshots and videos?

### ISSUE THREAD

**Issue by FunPsycho** [DevExpress/testcafe#4351]
I posted this question to StackOverflow as well, but think I might get a little more traction here.  (https://stackoverflow.com/questions/58238558/is-there-a-way-to-specify-a-dynamic-report-filename-in-testcafe)

So basically I am looking for a way to specify the stdout of the reporter with the command line or config file like you can with the screenshots and videos.  Is that possible?

https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/screenshots-and-videos.html#path-pattern-placeholders

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. We try to keep our GitHub repository for bug reports and feature requests only. It's great that you've created a question on StackOverflow, our team tracks the `[testcafe]` tag and tries to answer all TestCafe-related questions. I can assure you that it will be answered in a couple of days.
