### ISSUE TITLE
Allow to set specific browsers for specific test files

### ISSUE THREAD

**Issue by nicgirault** [DevExpress/testcafe#4353]
Many sites have a mobile version which is different from the desktop version. This leads to write some mobile specific tests and desktop specific tests. Currently I am dealing with this by writing my mobile tests in `*.mobile.cafe.ts` files and desktop tests in `*.desktop.cafe.ts`. Then I configure my test runners:

```typescript
const runners = [
  createBaseRunner(testcafe)
      .src(['./tests/**/*.desktop.cafe.ts'])
      .browsers('chrome'),
  createBaseRunner(testcafe)
      .src(['`./tests/**/*.mobile.cafe.ts'])
      .browsers('chrome:emulation:device=iphone X')
]
```

This is working well but is not very easy to use with IDE integrations where you want to be able to run the open test file:

![image](https://user-images.githubusercontent.com/551837/66270547-535d5300-e855-11e9-8d19-94c5e965fdff.png)

I will have to write a bunch of code to handle this and it makes my testcafe configuration quite complex while my use case seems simple to me.

Thus I browsed testcafe documentation to check if it was possible to specify in fixtures or tests the browsers (I would expect it to override CLI or programatic values) like this:

```typescript
fixtures('My fixture').browsers('chrome:emulation:device=iphone X')
```

It seems that it is not possible. Does my request make sense to you? Would you suggest an alternative to me? Or any plan to implement it?

Thanks

**Comment by Farfurix** [comment]
@nicgirault 

Hello,

Thank you for your suggestion. Our team will research it. At first glance, we can implement such functionality in our [configuration files](https://devexpress.github.io/testcafe/documentation/using-testcafe/configuration-file.html).

Please stay tuned for updates in this thread.
