### ISSUE TITLE
Please, add my extension to testcafe plugin section

### ISSUE THREAD

**Issue by Selminha** [DevExpress/testcafe#4358]
Hello,

My name is Selma and I've developed an extension to help run and debug Testcafe tests on Visual Studio Code. 
The extension is called **TestLatte** and this is the link to it's repository https://github.com/Selminha/testlatte
I hope it can be listed on the Plugin section of Testcafe documentation.
Please let me know if you need more information about the extension.

Best Regards.

Selma

**Comment by AndreyBelym** [comment]
Hello Selmina. Thank you for using TestCafe and contributing to its ecosystem. I've created a pull request to add your plugin to our `README.md` - #4365.
