### ISSUE TITLE
Top level navigation to media "hangs" browser

### ISSUE THREAD

**Issue by andrzej-kodify** [DevExpress/testcafe#4362]
It's quite obvious that if during tests you click on a link that causes top level navigation directly to image or video file (which is not embedded inside HTML) then testcafe loses control over browser and considers it as hanged:
`ERROR The Chrome 77.0.3865 / Mac OS X 10.14.5 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.`

Not sure if that could and should be solved but it would help to print out some warning message stating what happened.
As for solution i guess wrapping it with an iframe would do the trick in my opinion.

**Comment by AlexKamaev** [comment]
Thank you for your thoughts. A similar issue already exists. So, I'll close this one in favor of [https://github.com/DevExpress/testcafe/issues/1471](https://github.com/DevExpress/testcafe/issues/1471).

I agree that this behavior can be improved. However, I cannot give you any estimates regarding this.
