### ISSUE TITLE
t.resizeWindow() somehow blows away prior set .requestHooks()

### ISSUE THREAD

**Issue by a-rcrawford** [DevExpress/testcafe#4366]
I had tests that needed to resize the window, and then make sure certain RequestLogger() calls were made.

Without calling await t.resizeWindow() my .requestHooks(logger) were working.

Calling t.resizeWindow() somehow meant that my requestHooks() never detected any more; logger.requests.length never updated.

**Comment by alexey-lin** [comment]
Hi @a-rcrawford,

I could not reproduce this on my side. Could you show your full test code and, if it's possible, a public URL to the page you are testing?

**Comment by a-rcrawford** [comment]
I've found a way to work around the problem, and I simply don't have time to go through the several steps to show you that this is indeed a problem.

Perhaps someone with more time will report a similar issue.
