### ISSUE TITLE
Test fails with "RangeError: Maximum call stack size exceeded" message when we perform action click on download link.

### ISSUE THREAD

**Issue by georgiy-abbasov** [DevExpress/testcafe#437]
Appearance: https://travis-ci.org/testcafe-build-bot/testcafe/jobs/121397666#L1215

Looks like consequence of [testcafe-hammerhead-issue-521](https://github.com/DevExpress/testcafe-hammerhead/issues/521)

**Comment by inikulin** [comment]
I don't get it. How it could be a consequence of #521 when #521 is not fixed yet?

**Comment by inikulin** [comment]
Is this test run in some PR. If yes, in which one?

**Comment by AlexanderMoskovkin** [comment]
@inikulin It seems this issue will be resolved after #521 is fixed.
The problem was detected after a regression test was added  here https://github.com/DevExpress/testcafe/pull/429 ([tests report](https://travis-ci.org/testcafe-build-bot/testcafe/jobs/121397666#L1216))
We should investigate this, so we've create this ticket for that.

**Comment by inikulin** [comment]
So why we need this one if we have DevExpress/testcafe-hammerhead#521?

**Comment by AlexanderMoskovkin** [comment]
We removed this failed test from #429 to merge it. We need this issue to don't forget to add the test when the hammerhead issue is fixed

**Comment by AlexanderMoskovkin** [comment]
The related `testcafe-hammerhead` issue was fixed, now we can resolve this issue. But we've found one more issue with click on a download link. `pageUnloadBarrier` works incorrectly after a click on the download link is performed. Let's fix it in the context of this issue. /cc @georgiy-abbasov

**Comment by AlexanderMoskovkin** [comment]
In fact, any test brakes after click on a download link now, so I move this issue to the `MVP` milestone

**Comment by georgiy-abbasov** [comment]
I'm working on this.

**Comment by inikulin** [comment]
@AlexanderMoskovkin why it's in APIv2 MVP? Is this somehow completely breaks any API? Or it's just a severe bug? If later - it's shouldn't be in MVP milestone

**Comment by AlexanderMoskovkin** [comment]
It's a severe bug

**Comment by inikulin** [comment]
I'll take it from the milestone then. For server bugs we just use important label.

**Comment by inikulin** [comment]
@AlexanderMoskovkin Do I understand right that it was fixed by #759?

**Comment by AlexanderMoskovkin** [comment]
it was fixed by #759
