### ISSUE TITLE
Allow send specific messages that will be available in test report

### ISSUE THREAD

**Issue by fmancardi** [DevExpress/testcafe#4370]
### What is your Test Scenario?
While running a test it will be useful to be able to write messages that will be available in the test report. Right now the only way to write a message is using an expect sentence that fails.

### What are you suggesting?
To have some method to write message to the test report

### What alternatives have you considered?
Right now I'm writing output to a text file and filter it after execution.

**Comment by Farfurix** [comment]
@fmancardi 

Hello,

Thank you for your request. We will consider your suggestion in the context of this thread: https://github.com/DevExpress/testcafe/issues/3584.

**Comment by fmancardi** [comment]
@Farfurix, I apologize for not having searched for duplicates.
Thanks a lot

**Comment by Farfurix** [comment]
@fmancardi 

No worries, you are welcome.
