### ISSUE TITLE
Whenever there is a url redirection, sometimes gives 404 pages

### ISSUE THREAD

**Issue by svg-cloud** [DevExpress/testcafe#4381]
This is regarding the 404 redirection when we have multi level redirections within the application. I did try to lookup for any help in below links but could not find any.

Here is the issue that i am noticing while running my suite.

1. We login in to the application.
2. execute the test steps within the tests
3. logout of the application.

In the logout step (#3) above there are multiple redirects that happen which the test cafe redirects to 404 page.
redirection sequenct when we logout 
1. We logout of the application using the url : <application>/logout
2. The above url will redirect to <application>/auth/logout
3. Which will redirect to the login screen <application>/login

After step c above test cafe reports the 404 page.

![image](https://user-images.githubusercontent.com/54597768/66863684-67394100-ef48-11e9-9ba9-cefa815fd8d6.png)

#### HEADS UP!

For TestCafe API, usage and configuration inquiries, we recommend [StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)).

You may also find answers in our up-to-date [documentation](https://devexpress.github.io/testcafe/documentation/getting-started/) and [answered questions](https://stackoverflow.com/questions/tagged/testcafe) on StackOverflow. This may save your time.

If you have already looked there and have not found an appropriate answer, [file a new question on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe).

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. HTTP redirects should work with TestCafe, we have [automated tests](https://github.com/DevExpress/testcafe/search?q=redirect&unscoped_q=redirect) that cover this functionality. Likely there is an interoperability issue between your web app and TestCafe. Could you please provide an example that can be used to reproduce the problem?
