### ISSUE TITLE
Using navigateTo in side the role redirects it to /about:blank

### ISSUE THREAD

**Issue by LOUKOUKOU** [DevExpress/testcafe#4385]
The code below causes the test to redirect to /about:blank after it redirected to the url.

```
const role = Role(url, async t => {
  await t
      .typeText('#UserName-field', 'tester@user.com')
      .typeText('#Password-field', 'password')
      .click('#submit-button')
      .navigateTo(url)
})
```

If I redirect after the role:

```
const **roleTest** = Role(url, async t => {
  await t
      .typeText('#UserName-field', 'tester@user.com')
      .typeText('#Password-field', 'password')
      .click('#submit-button')
})

test('Login test', async t => {
    await t
    .useRole(**roleTest**)
    .navigateTo(url)
    .expect(getLocation())
    .contains(url)
})
```
then it doesn't redirect to /about:blank, it redirects to the url successfully.

**Comment by Farfurix** [comment]
@LOUKOUKOU 

Hello,

I suggest you use one of the following ways:
1. Set the `preserveUrl: true` option  to ["save the URL to which the browser was redirected after logging in"](https://devexpress.github.io/testcafe/documentation/test-api/authentication/user-roles.html#optionspreserveurl).
2. Specify your start page in the [`test.page` function](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#specifying-the-start-webpage).
