### ISSUE TITLE
navigate history (back / forward)

### ISSUE THREAD

**Issue by arlac77** [DevExpress/testcafe#4391]
### What is your Test Scenario?
emulate the user pushing back forward in the history

### What are you suggesting?
like navigateTo() navigateBack() and navigateForaward()

### What alternatives have you considered?
manual testing

**Comment by Farfurix** [comment]
@arlac77 

Hello,

At present, the history (back / forward) navigation [is fully supported by using `ClientFuntion`](https://github.com/DevExpress/testcafe/issues/1936#issuecomment-343451532):
```js
import { ClientFunction } from 'testcafe';

const getLocation = ClientFunction(() => window.location.href);

 fixture `fixture`
    .page `http://google.com`;

 test('test history navigation', async t => {
    await t
        .expect(getLocation()).contains('google')
        .navigateTo('http://js.devexpress.com/')
        .expect(getLocation()).contains('/js.devexpress');

    const goBack = ClientFunction(() => window.history.back());
    await goBack();

    await t.expect(getLocation()).contains('google');
});
```
