### ISSUE TITLE
The testcafe statusbar is not visible when the browser viewport is larger than the browser size

### ISSUE THREAD

**Issue by stefanschenk** [DevExpress/testcafe#4396]
The testcafe statusbar (root-hammerhead-shadow-ui) which is normally displayed on the bottom of the browser, is not visible when the viewport of the browser is larger than the actual window size of that browser.

If I start the chrome or chromium browser with a window-size of 1920x1080 and a viewport of 2560x1440 the statusbar is presumably displayed at the bottom of the viewport (so outside the window).

This behaviour prevents me from using the debug mode of testcafe for these tests.

I would like to see the statusbar fixed to the bottom of the window and not the viewport. Or perhaps a configurable option where one could have the option to display the statusbar on for instance the top of the browserwindow.
 
### Your Environment details:
 
* testcafe version:                  1.4.3
* node.js version:                    10.15.3
* browser name and version: Chromium 74.0.3723.0
* platform and version:           Linux Ubuntu 18.04

**Comment by Farfurix** [comment]
@stefanschenk 

Hello,

I checked a simple scenario and it works correctly on my side.
My environment details: TestCafe v1.6.0, Ubuntu, Chromium.

Result:
![Capture](https://user-images.githubusercontent.com/30019338/67016119-57fcf380-f100-11e9-9aa2-27823adb9afa.PNG)

Please provide us with a simple project or a public URL. It will help us examine the issue.

**Comment by stefanschenk** [comment]
Sorry for the late comment. I don't have a public facing url to share for this issue. But maybe I can shed some light on the issue.

I don't have a problem using firefox or chrome, because I use the built-in default browser provider from testcafe.

With my testruns I use a forked version of the puppeteer browser provider.
Using puppeteer you can instruct chromium to start with a window size and a viewport size (for instance window size = 1920*1080, viewport size = 800*600)

Our application had to be tested on a resolution of 2560*1440. But as I was testing on a full hd monitor I set the window size to 1920*1080, but the viewport size to 2560*1440. (and I used forced device scaling to fit the larger viewport in the full hd window)

For the loaded webpage the available size is the latter and therefore the testcafe statusbar is also displayed at the bottom of the viewport and therefore invisible in the browser window.

So I'm guessing this issue can be closed.
