### ISSUE TITLE
Testcafe Login/click not working in Chrome/Firefox, but works in IE/Safari 

### ISSUE THREAD

**Issue by surendiranece** [DevExpress/testcafe#4398]

**Comment by surendiranece** [comment]
Hi,
Unfortunately this is an internal website and can't make it available through internet. Is there any other way ?Can i send the video recording? Or would you be available for desktop sharing?

This is the element in DOM

<div role="button" class="gw-action--inner gw-hasDivider" aria-label="Log In" aria-disabled="false" data-gw-click="fireEvent id:^" data-gw-default="{&quot;id&quot;:&quot;Login-LoginScreen-LoginDV-submit&quot;,&quot;key&quot;:&quot;ENTER&quot;,&quot;op&quot;:&quot;fireevent&quot;,&quot;panel&quot;:&quot;C&quot;}" tabindex="0"><div class="gw-minimized-view"><div class="gw-label-min gw-min-visible" data-gw-tooltip="Log In" data-gw-mouseenter="gwMouse.enter" data-gw-mousemove="gwTooltips.move" data-gw-mouseout="gwTooltips.hide" data-gw-mouseover-enabled="true" data-gw-mouseout-enabled="true" data-gw-mousemove-enabled="true" data-gw-mouseenter-enabled="true">LI</div></div><div aria-hidden="true" class="gw-label">Log In</div></div>

**Comment by surendiranece** [comment]
Hi,
Actually this was working till 0.20.0 version of testcafe and not working from 0.21.0. Could you please what you have changed during that time?

**Comment by surendiranece** [comment]
Hi Can we have a zoom call to fix this issue? I can share the control to you so that you can troubleshoot..Its pretty urgent.Wea re in evaluation phase of tools.. and Testcafe is prominent for us apart from this one big issue.

**Comment by AlexKamaev** [comment]
@surendiranece 
Hi,
The `0.21.0` version has a couple of significant changes, however, it's difficult to define which change breaks your test.
>Hi Can we have a zoom call to fix this issue? I can share the control to you so that you can troubleshoot..Its pretty urgent

Unfortunately, we cannot provide such a service, so since you cannot share your working project, we would really appreciate it if you prepare a sample which demonstrates the issue. Once we reproduce the issue, we'll try to fix it as soon as possible.

**Comment by surendiranece** [comment]
Hi,
I have managed to get the web throught internet

http://4385b10a.ngrok.io/cc/ClaimCenter.do


This is the login page ... login details are 
username : aapplegate
password: gw

Can you reproduce the issue? Issue is happening only in CHrome and firefox of the latest testcafe versions. It works with Testcafe version 0.20.0

**Comment by surendiranece** [comment]
Hi,

I have managed to get the website through internet..Here is the url
http://762e7e35.ngrok.io/pc/PolicyCenter.do

Username: su
password:gw

Could you please reproduce the issue with the login button.? It happens only in chrome & firefox on latest testcafe version from 0.21.0. It works with testcafe version 0.20.0

Even the testcafe studio is unable to record the login button click action with chrome browser.

Would be great if you fix this asap.

**Comment by Farfurix** [comment]
@surendiranece 

Hello,

Thank you for the additional information. I've reproduced the issue under macOS 10.15 / Chrome 77 / TestCafe v1.6.0. We need some time to examine this case using your credentials. Please stay tuned for our updates in this thread.

**Comment by surendiranece** [comment]
Let me know if you have any work around for this to work in chrome & firefox.
