### ISSUE TITLE
Add Scroll Actions to set of user Actions

### ISSUE THREAD

**Issue by switch201** [DevExpress/testcafe#4399]
### What is your Test Scenario?
IN many cases It could be useful to have the suer scroll explicitly. In some applications there are events and such triggered by the act of scrolling. It also helps when there are edge cases of testcafe not scrolling correctly. In some instance I want to offset the scroll based because there might be a footer element in the way for example. 

### What are you suggesting?
I am suggesting that Scrolling be added as a user action that can be called explicitly. It could take 2 argument types. if a Selector is passed in then it will scroll to that selector. If numbers are input it will attempt to scroll that many pixels (or whatever unit of measurement you want) In the X and Y directions. 

### What alternatives have you considered?
Right now I just have to send mouse and key board events directly in. For example for scrolling down I just tell the program to press the down key, but this doesn't work if a textbox is selected for example.

### Additional context
This is something that is built into other frame works I don't think its too crazy of an ask. I know that all user actions in testcafe should auto scroll, but I do find cases where this doesn't always work.

On the one hand I could submit a bug report for said issues, but I can't share my app as an example so I already for see it being closed as can not reproduce.

**Comment by Dmitry-Ostashev** [comment]
Hello,
Take a look at this issue: https://github.com/DevExpress/testcafe/issues/527. Could you please describe your scenario there in greater detail?

By the way, TestCafe can automatically scroll the page to click element at the bottom. If it does not work in your test, please provide us with a simple code snippet so that we can reproduce the issue.
