### ISSUE TITLE
Selector is expected to be initialized with a function, CSS selector

### ISSUE THREAD

**Issue by Meemaw** [DevExpress/testcafe#4400]
After upgrading to `testcafe` v1.6.0 it seems that `@testing-library/testcafe` selectors started failing:

```js
import { getByPlaceholderText } from '@testing-library/testcafe';

  const searchInput = getByPlaceholderText( 'Type...');
  await t
    .expect(searchInput.exists)
    .ok('Search input exists')
    .typeText(searchInput, 'randomText');
```

Throws:
<img width="724" alt="Screen Shot 2019-10-18 at 11 57 02 AM" src="https://user-images.githubusercontent.com/8524109/67085053-6d285f80-f19e-11e9-9753-8cdaf1ac262f.png">

Error points to the `.typeText` line.

 
### Your Environment details:
 
* testcafe version:                   1.6.0
* node.js version:                    v8.16.0
* browser name and version: HeadlessChrome 68.0.3440

**Comment by Dmitry-Ostashev** [comment]
This behavior is most likely caused by the `@testing-library/testcafe` library. I suggest you create an issue in this repository: https://github.com/testing-library/testcafe-testing-library.
