### ISSUE TITLE
Intermittent issue when running concurrent tests

### ISSUE THREAD

**Issue by johnrellis** [DevExpress/testcafe#4402]
### What is your Test Scenario?

Up until today we are running our tests with no concurrency today we introduced a concurrency of 3 and are running tests via

```
testcafe chrome:headless -S -s screenshots/headless -p '${DATE}_${TIME}/${FIXTURE}/${TEST}.png' --speed 0.5 -c 3 'testcafe/tests/!(ie11|l2)/*.js' --reporter json:report.json,list
```

 

### What is the Current behavior?
1 in 4 test runs fail with 

```
   1) TypeError: Cannot read property '0' of null 
 
      Browser: HeadlessChrome 77.0.3865 / Linux 0.0.0 
      Screenshot: 
 
   /codebuild/output/src201590524/src/github.com/servisbot/botcafe/screenshots/headless/2019-10-18_12-21-00/ConversationHistorySimpleFlow/Simple 
      Flow with Conversation History.png 
 
         266 |        this._handlePlainObject(val); 
         267 |}; 
         268 | 
         269 |DecodingTransformer.prototype.transform = function () { 
         270 |    this.visitedRefs[0] = true; 
       > 271 |    this._handleValue(this.references[0], this.references, 
      0); 
         272 | 
         273 |    return this.references[0]; 
         274 |}; 
         275 | 
         276 | 
 
         at DecodingTransformer.transform 
 
   (/codebuild/output/src201590524/src/github.com/servisbot/botcafe/node_modules/replicator/index.js:271:38) 
         at module.exports.Replicator.decode 
 
   (/codebuild/output/src201590524/src/github.com/servisbot/botcafe/node_modules/replicator/index.js:559:24) 
         at ClientFunctionBuilder._processResult 
 
   (/codebuild/output/src201590524/src/github.com/servisbot/botcafe/node_modules/testcafe/src/client-functions/client-function-builder.js:146:32) 
         at re_executable_promise_1.default.fromFn 
      (/codebuild/output/src201590524/src/github.com/servisbot/botcafe/node_modules/testcafe/src/client-functions/client-function-builder.js:141:25) 
```
 
### What is the Expected behavior?

Test does not fail with error
 

NOTE : this test is our only test that uses 

```
  await t.eval(() => location.reload(true));
```

Looks very similar to :

https://github.com/DevExpress/testcafe/issues/2916
and
https://github.com/DevExpress/testcafe/issues/3200

### Your Environment details:
 
* testcafe version:                   1.6.0
* node.js version:                   10
* command-line arguments:  see above
* browser name and version: chrome headless, see above
* platform and version:         AWS default codebuild (AWS linux)

**Comment by miherlosev** [comment]
Hi @johnrellis 

You've encountered the problem in the [replicator](https://www.npmjs.com/package/replicator) module. We can find the cause of the problem and create a PR with a fix to the module repository.
To do that, we need an example that we can run locally. Could you please provide such example?
