### ISSUE TITLE
Typescript error when using testcafe version 1.6.0

### ISSUE THREAD

**Issue by zsid** [DevExpress/testcafe#4405]
### What is the Current behavior?

 * I am currently using create react app  plus `"typescript": "3.6.0"`. When I upgraded from `version 1.5.0` to `v1.6.0` and I ran my tests I get this error:
```
 Property 'page' does not exist on type 'It'.
Property 'page' does not exist on type 'It'.
Property 'page' does not exist on type 'It'.
```
 Looks like this is similar to or maybe the same as the [declare var test on global scope issue](https://github.com/DevExpress/testcafe/issues/1537)

### What is the Expected behavior?

I would expect to run the tests.

### Your Environment details:
 
* testcafe version:                  `testcafe -v1.6.0` 
* typescript: `3.6.0`
* node.js version:                     `node -v10.15.3`
* browser name and version:  I run it headless
* platform and version:          macOS Mojava 10.14.6
* other:

**Comment by Meemaw** [comment]
Facing same issues

**Comment by AlexKamaev** [comment]
@zsid @Meemaw
Could you please provide more details on how to reproduce the issue on our side? We would really appreciate it if you prepare a sample project which demonstrates the issue.

**Comment by zsid** [comment]
@AlexKamaev - I have created a branch called [typescript error](https://github.com/zsid/testcafe-azure-ad/tree/typescript-error) and put the error I am getting in the README.

It is slightly different error from the original one but the underlining problem is the same - typescript is using `jest` for the type checking etc.

**Comment by AlexKamaev** [comment]
@zsid 
Thank you.
I was able to reproduce the issue using your example.
For the team: check this commit at first: https://github.com/DevExpress/testcafe/commit/bfd8985cf30b8a9f97d496afe5f89c07a7ae1842
