### ISSUE TITLE
Add Github Actions to Continuous Integration section

### ISSUE THREAD

**Issue by Meemaw** [DevExpress/testcafe#4406]
[Github actions](https://github.com/features/actions) are becoming more and more popular. Even though they are still in Beta, a lot of people are already trying them out and switching. They will be  generally available on November 13.

It would be very nice if using `testcafe` with Github Actions was documented by that time and people using testcafe would have an easy time switching if they wanted. I have successfully used `testcafe` in Github Actions in some side projects, and published a [testcafe-action](https://github.com/Meemaw/testcafe-action/) which makes that trivial.

It is basically just a wrapper around `testcafe` which runs inside `circleci/node:10.14-browsers` Docker image. It also uses a Github Action to test itself -- [workflows/main.yml](https://github.com/Meemaw/testcafe-action/blob/master/.github/workflows/main.yml).

**Comment by AlexKamaev** [comment]
Thank you for pointing out to this. It's a really good idea. I cannot give precise estimates, however, I think we'll work on this in one of the nearest sprints.

**Comment by AlexKamaev** [comment]
https://github.com/marketplace/actions/run-testcafe
