### ISSUE TITLE
screenX and screenY are 0 on mousedown event in drag operation

### ISSUE THREAD

**Issue by SebastianStamm** [DevExpress/testcafe#4408]
### What is your Test Scenario?
Drag an element across the page using the screenX and screenY properties of the mouse events keeping track of its position.
 
### What is the Current behavior?
The screenX and screenY properties of the mousedown event are 0 when calling `drag`.
 
### What is the Expected behavior?
The screenX and screenY properties of the mousedown event are the mouse position in screen coordinates when calling `drag`.
 
### Minimal Test Case:
<details>
  <summary>Click to expand</summary>

```html
<!DOCTYPE html>
<html>
  <body>
    <div
      style="position: absolute; width: 100px; height: 100px; top: 0; left: 0; background-color: red;"
    ></div>
    <script>
      const element = document.querySelector('div');

      let startPosition;
      element.addEventListener('mousedown', ({screenX, screenY}) => {
        startPosition = {screenX, screenY};

        element.textContent = screenY;

        document.body.addEventListener('mousemove', move);
        document.body.addEventListener('mouseup', stop);
      });

      function move({screenX, screenY}) {
        element.style.left = screenX - startPosition.screenX + 'px';
        element.style.top = screenY - startPosition.screenY + 'px';
      }

      function stop() {
        document.body.removeEventListener('mousemove', move);
        document.body.removeEventListener('mouseup', stop);
      }
    </script>
  </body>
</html>

```
</details>

### Your complete test code (or attach your test files):

 
```js
import {Selector} from 'testcafe';

fixture`New Fixture`.page`http://localhost:8080/`;

test('New Test', async t => {
  await t
    .click(Selector('div'))
    .drag(Selector('div'), 200, 200)
    .expect(Selector('div').textContent)
    .notEql('0');
});

```

### Steps to Reproduce:
1. Have a server that serves the included minimal test case.
1. Go to https://localhost:8080/ (or wherever you host it) to check the expected drag and drop behavior (the box display the screenY property. It should be greater than 0)
2. Execute the test code
3. Observe that the screenX and screenY coordinates of the mousedown event are both 0. Depending on your screen configuration the element is dragged too far to the left and down.
 
### Your Environment details:
 
* testcafe version:                   1.6.0
* node.js version:                    10.15.3
* command-line arguments:  testcafe chrome test.js
* browser name and version: Chrome 77
* platform and version:          Linux Ubuntu 18.04

**Comment by Farfurix** [comment]
@SebastianStamm 

Hello,

I wasn't able to reproduce the issue using the above test code. My environment details: Ubuntu 18.04 / Chrome 77. My result:
![Capture](https://user-images.githubusercontent.com/30019338/67275620-aaa52980-f4cb-11e9-99f2-883fbbab71b4.PNG)

Could you please provide us with a working example? We will examine it and check for a suitable solution.

**Comment by SebastianStamm** [comment]
It looks like codesandbox put the app to sleep due to inactivity, that's why the test did not run properly. I added a minimal test case html in the original issue description that you can host locally and test against:

<details>
  <summary>Click to expand</summary>

```html
<!DOCTYPE html>
<html>
  <body>
    <div
      style="position: absolute; width: 100px; height: 100px; top: 0; left: 0; background-color: red;"
    ></div>
    <script>
      const element = document.querySelector('div');

      let startPosition;
      element.addEventListener('mousedown', ({screenX, screenY}) => {
        startPosition = {screenX, screenY};

        element.textContent = screenY;

        document.body.addEventListener('mousemove', move);
        document.body.addEventListener('mouseup', stop);
      });

      function move({screenX, screenY}) {
        element.style.left = screenX - startPosition.screenX + 'px';
        element.style.top = screenY - startPosition.screenY + 'px';
      }

      function stop() {
        document.body.removeEventListener('mousemove', move);
        document.body.removeEventListener('mouseup', stop);
      }
    </script>
  </body>
</html>

```
</details>

**Comment by alexey-lin** [comment]
Thank you for the sample. I reproduced this behavior on our side, and it looks like a bug. We'll look into it and update this thread once we have any results.
