### ISSUE TITLE
Implement test-run commands

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#441]
- [x] click
- [x] rclick (call it rightClick)
- [x] dblclick (call it doubleClick)
- [x] press (pressKey)
- [x] select (selectText, selectTextInArea, selectEditableContent)
- [x] type (typeText)
- [x] drag (drag, dragToElement)
- [x] hover
- [x] uploadFile
- [x] clearUpload
- [x] wait
- [x] waitForElement
- [x] takeScreenshot
- [x] resizeWindow
- [x] navigateTo

**Comment by AlexanderMoskovkin** [comment]
I and @helen-dikareva are working on this

**Comment by AlexanderMoskovkin** [comment]
I'm working on drag now

**Comment by helen-dikareva** [comment]
I'm working on `rclick` now

**Comment by helen-dikareva** [comment]
I'm working on `dblclick` now

**Comment by helen-dikareva** [comment]
I'm working on `hover` now

**Comment by helen-dikareva** [comment]
I'm working on `type` now

**Comment by helen-dikareva** [comment]
I'm working on `select` now

**Comment by AlexanderMoskovkin** [comment]
I'm working on `press` now

**Comment by AndreyBelym** [comment]
I'm working on **uploadFile** now.

**Comment by helen-dikareva** [comment]
I'm working on `wait` and `waitElement` now

**Comment by helen-dikareva** [comment]
I'm working on `navigateTo` now.

**Comment by helen-dikareva** [comment]
I'm working on `takeScreenchot` now.

**Comment by inikulin** [comment]
Isn't `uploadFile` already implemented?

**Comment by AlexanderMoskovkin** [comment]
it's not merged yet #508

**Comment by helen-dikareva** [comment]
@inikulin In context of `takeScreenchotCommand` we decided to implement taking screenshots on fails. What do think should we take screenshots for errors are raised on server (error in test code, including assertion errors) or not?

**Comment by inikulin** [comment]
idk, let's bikeshed

**Comment by helen-dikareva** [comment]
Let's discuss @DevExpress/testcafe

**Comment by inikulin** [comment]
Moved `waitForCondition` in separate ticket: https://github.com/DevExpress/testcafe/issues/542 We don't need it in MVP

**Comment by helen-dikareva** [comment]
I'm working on `resizeWindow`

**Comment by AlexanderMoskovkin** [comment]
> What do think should we take screenshots for errors are raised on server (error in test code, including assertion errors) or not?

I don't know too what we should do in this case, I propose to discuss it together in the office and take a decision.

**Comment by helen-dikareva** [comment]
We decided to implement two command
`t.resizeWindow(widht, height)
t.resizeWindowToFitDevice(device, [orientation])`
like in testcafe-browser-natives https://github.com/DevExpress/testcafe-browser-natives/blob/master/API.md
Is it ok?

**Comment by AlexanderMoskovkin** [comment]
All commands are implemented
