### ISSUE TITLE
Find a way to improve test hooks

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#4411]
We need to discuss and possibly implement new test hook types.

**Comment by AlexKamaev** [comment]
Check the https://github.com/AlexKamaev/testcafe-once-hook repo

**Comment by miherlosev** [comment]
I checked it out. It looks ready for publication.
Anyone else want to take a look?

**Comment by AndreyBelym** [comment]
I think we can talk about some things before publication.

1. https://github.com/AlexKamaev/testcafe-once-hook/issues/1
2. What's about the use-case described by the original poster, **chadmyers**? For each test, but only for one browser. 
3. (WTF because of a TestCafe bug) I think we shouldn't start executing the hook body until *all browsers enter the hook*. Otherwise it can be executed in the middle of other tests.
#### Requires testcafe@1.1.4, the latest version is broken, see below why
##### tests/test-a.js
```js
import { once } from '../utils/once';

fixture `Fixture`
    .beforeEach(once(async t => {
        console.log(t.testRun.browserConnection.browserInfo.alias, 'HOOK A');
    }));

test('Test', async t => {
    console.log(t.testRun.browserConnection.browserInfo.alias, 'TEST A START');

    if (t.testRun.browserConnection.browserInfo.alias.includes('chrome'))
        await t.wait(10000);

    console.log(t.testRun.browserConnection.browserInfo.alias, 'TEST A FINISH');
});

test('Test', async t => {
    console.log(t.testRun.browserConnection.browserInfo.alias, 'TEST A START');

    if (t.testRun.browserConnection.browserInfo.alias.includes('chrome'))
        await t.wait(10000);

    console.log(t.testRun.browserConnection.browserInfo.alias, 'TEST A FINISH');
});

test('Test', async t => {
    console.log(t.testRun.browserConnection.browserInfo.alias, 'TEST A START');

    if (t.testRun.browserConnection.browserInfo.alias.includes('chrome'))
        await t.wait(10000);

    console.log(t.testRun.browserConnection.browserInfo.alias, 'TEST A FINISH');
});
```
##### tests/test-b.js
```js
import { once } from '../utils/once';

fixture `Fixture`
    .beforeEach(once(async t => {
        console.log(t.testRun.browserConnection.browserInfo.alias, 'HOOK B');
    }));

test('Test', async t => {
    console.log(t.testRun.browserConnection.browserInfo.alias, 'TEST B START');

    if (t.testRun.browserConnection.browserInfo.alias.includes('chrome'))
        await t.wait(10000);

    console.log(t.testRun.browserConnection.browserInfo.alias, 'TEST B FINISH');
});
```
##### CLI:
```
> npx testcafe chrome,firefox tests/test-a.js tests/test-b.js
 Running tests in:
 - Chrome 78.0.3904 / Windows 10.0.0
 - Firefox 70.0.0 / Windows 10.0.0

 Fixture
chrome HOOK A
chrome TEST A START
firefox TEST A START
firefox TEST A FINISH
firefox TEST A START
firefox TEST A FINISH
firefox TEST A START
firefox TEST A FINISH
firefox HOOK B      << HERE IS THE PROBLEM
chrome TEST A FINISH
 √ Test
chrome TEST A START
chrome TEST A FINISH
 √ Test
chrome TEST A START
chrome TEST A FINISH
 √ Test

 Fixture
firefox TEST B START
firefox TEST B FINISH
chrome TEST B START
chrome TEST B FINISH
 √ Test


 4 passed (41s)
```
Unfortunately, it can't be reproduced with the latest TestCafe version, since *all browsers wait until a test finishes*. This was introduced by https://github.com/DevExpress/testcafe/commit/2b791dc8dd51ae52396201e51c747cfcc0411e86. 

4. (Suggestion) It's really nice that you have implemented a full-featured server with a DB for testing the package, but IMHO for me it looks like that now there is too much code for such a simple package. We will need an example server for serving advanced examples from DevExpress/testcafe-examples, so why not splitting the test server into a separate package?

5. (Suggestion) I really worry that the hook body can be executed in different browsers in different test sessions. Maybe we should look at the order of how browsers were specified in CLI/API, and take the first/last from them, instead of relying on the test execution order?  

6. (Suggestion) I feel that the current implementation is heavy and can be decomposed into a number of smaller hooks, like:
 * `onceFixture`
 * `onlyFirstBrowser`/`onlyLastBrowser`
 * `sync` (to wait for this hook in all other browsers) 

It will be easier for us to understand and maintain the code, and our users will have a granular control if they want to implement some custom scenarios.

**Comment by AlexKamaev** [comment]
1. Please check the latest version, I updated the repo
2. As far as I remember the original question was not about browser, it was about the `beforeTest` hook request. Browsers are not required. If I rembered correctly the workaround was suggested.
3. I reproduced it :( I've made some modifications. Now the function will no be executed until all browsers are inside the hook.
4. I didn't intent to publish it with a server. I used this server during the developent. In addition I think we'll need this server to demonstrate how the `once` trick works. Of course, we should separate repositories before publishing.
5-6. Let discuss it

**Comment by AndreyBelym** [comment]
All my questions regarding the hook's code are resolved now. Feels like we are ready to separate the test server and publish it.

**Comment by helen-dikareva** [comment]
I agree to publish the example, I only noticed that you can't specify two bunch of actions:
- for `once` mode execution 
- for `beforeEach` mode execution
in beforeEach/afterEach hooks.

**Comment by AlexKamaev** [comment]
https://www.npmjs.com/package/testcafe-once-hook
