### ISSUE TITLE
Make timeout (retry) in assertions work for custom methods

### ISSUE THREAD

**Issue by franciscolosardo** [DevExpress/testcafe#4415]
### What is your Test Scenario?

I have a function which **scrolls through different selectors and grab their inner texts**. This method **returns an array with the texts found**.
I need to **check** if the function returns an **array equal to another array**.
My function **returns a promise<array>.** Testcafe doesn't allow custom methods to be called without the await, unless you pass the allowunawaitedpromise option. But when this option is passed **it just tries the promise once and if it fails it doesn't retry until it times out**...
### What are you suggesting?

I'd suggest , **when an allowunawaitedpromise option and a timeout option is sent**, the assertion method **calls repeatedly the function** passed as argument until it **times out or the assertion is valid**.

**Comment by franciscolosardo** [comment]
I'll leave a code example showing what i mean
```
async getArrayNames():Promise<any[]>{
	const count = await Selector("div.tabs").count;

	const names = [];
	for(let i = 0 ; i < count ; i++){
		names.push(await Selector("div.tabs").innerText)
	}
	return names;

}

t.expect(getArrayNames()).eql(['name1','name2'],{allowUnawaitedPromise : true})
```

**Comment by alexey-lin** [comment]
Hi @franciscolosardo,

Thank you for the suggestion. I understand your scenario, but there are a lot of other scenarios where the behavior you are suggesting would be inappropriate. So, the current behavior is by design. We will consider implementing a way to explicitly switch between these two options in future releases. In the meantime,  as a workaround, you can use a promise that checks a condition and re-evalutes it until it's met. Here is a simple sample how it can be done:

```js
fixture('My fixture').page('example.com');

test('My test', async t => {
    let count = 0;

    const clock = setInterval(() => {
        if ((++count) >= 10)
            clearInterval(clock);
    }, 10000); // decrease this value to make the test pass

    async function countReachedSeven() {
        return new Promise(resolve => {
            if (count >= 7)
                resolve(true);
            else {
                const polling = setInterval(() => {
                    if (count >= 7) {
                        clearInterval(polling);
                        clearTimeout(timeout);
                        resolve(true);
                    }
                });
                const timeout = setTimeout(() => {
                    clearInterval(polling);
                    resolve(false);
                }, 2000);
            }
        })
    }

    await t.expect(await countReachedSeven()).ok();
});
```
