### ISSUE TITLE
Clicking an SVG element two times throws an exception in IE

### ISSUE THREAD

**Issue by AdelorDM** [DevExpress/testcafe#4416]
[svg-test.zip](https://github.com/DevExpress/testcafe/files/3757008/svg-test.zip)

### What is your Test Scenario?
My SVG element is an icon to display a popup menu. This allows me to set filter options.
So I click this icon first time, set options, check result.
Then I click it second time and here an error occurs:

   1) Uncaught object "[object Object]" was thrown. Throw Error instead.

      Browser: IE 11.0.0 / Windows 10.0.0
 
### What is the Current behavior?
Error above occurs
 
### What is the Expected behavior?
No error
 
### What is your web application and your TestCafe test code?
You can reproduce this using the attached html page and test code below.
The page contains only the following:

```html
        <svg class="my-svg"  r="1" c="1">
            <use />
        </svg>
```

<details>
<summary>Your complete test code (or attach your test files):</summary>

```js
 import { Selector } from "testcafe"

fixture`svg test`
    .page(`${path_to_html_page}`)

test('check svg', async t => {
    let svg = Selector('.my-svg');
    await t
        .click(svg)
        .click(svg)
        .click(svg)
})
```
</details>

<details>
<summary>Your complete test report:</summary>

```
Debugger listening on ws://127.0.0.1:34158/d2e0f1d6-3778-43f2-9fb3-be6e971e5ee6
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
The "filter" option from the configuration file will be ignored.
 Running tests in:
 - IE 11.0.0 / Windows 10.0.0

 svg test
 × check svg

   1) Uncaught object "[object Object]" was thrown. Throw Error instead.

      Browser: IE 11.0.0 / Windows 10.0.0

 1/1 failed (9s)
```
</details>

### Steps to Reproduce:

Launch test in IE.
**This is reproducible only in IE**
 
### Your Environment details:
 
* testcafe version:                   1.6.0
* node.js version:                    8.7.0
* command-line arguments:  testcafe ie {filename}
* browser name and version: IE11
* platform and version:          Windows 10

**Comment by AlexKamaev** [comment]
the cause of the issue is same as in https://github.com/DevExpress/testcafe/issues/4709
