### ISSUE TITLE
Upgrade from 1.5.0 to 1.6.0 stopped resizeWindow() from working

### ISSUE THREAD

**Issue by a-rcrawford** [DevExpress/testcafe#4417]
I have found that upgrading from testcafe 1.5.0 to 1.6.0 somehow causes await t.resizeWindow(,) to stop working.  It doesn't output any error, it just returns happily without ever bothering to resize the window.  Downgrading back to testcafe 1.5.0, removing my package-lock.json and node_modules, before doing an "npm install", allowed resizeWindow() to work properly again.

I am running in Chrome on macOS Sierra Version 10.12.6.

**Comment by Dmitry-Ostashev** [comment]
This issue is caused by the same reasons as the problem from https://github.com/DevExpress/testcafe-browser-tools/issues/173. Let's continue our conversation there. By the way, the fix should be included in the 1.6.1 release.
