### ISSUE TITLE
Problem with multiple test files and current directory for test execution

### ISSUE THREAD

**Issue by freitasskeeled** [DevExpress/testcafe#4421]
### What is your Test Scenario?
With a set of individual test files in different directories, ran testcafe with the following syntax: 
`testcafe chrome test/e2e/**/test.js --sf`
*or*
`testcafe chrome test/e2e/tests --sf`
*or*
`testcafe chrome test/e2e/tests/<folder1>/test.js test/e2e/tests/<folder2>/test.js --sf`

Directory structure:
```
- test
    - e2e
        - tests
            - <subfolder_1>
                - test.js
            - ...
```
 
### What is the Current behavior?
Running a set of testcafe test files with the command line using a glob Pattern, parent directory or a list of paths to the test files causes the working directory for the test execution to be the one where the first test file is located. This then leads to problems with relative paths and `setFilesToUpload` where testcafe will try to get the file from the incorrect directory.
 
### What is the Expected behavior?
Each test file execution should have it's working directory set to the one where the test is located.

### Steps to Reproduce:
1) Create 2 separate test files within 2 different directories
2) For each directory, add a file to be used in the upload
3) In each test file, use `setFilesToUpload` with the relative path to the file located in the same folder
4) Run testcafe through the command line using the example provided in the test scenario
5) One of the tests will fail to locate the file
 
### Your Environment details:
 
* testcafe version: 1.6.0
* node.js version:  8.16.0
* command-line arguments: `testcafe chrome test/e2e/**/test.js --sf` (one of the 3 examples provided above)
* browser name and version: any
* platform and version: any

**Comment by miherlosev** [comment]
Hi @freitasskeeled 

Could you please provide a complete example that I can run locally without additional set up?

**Comment by patrickmcdougle-okta** [comment]
Try single quoting the glob. https://github.com/DevExpress/testcafe/pull/6125
