### ISSUE TITLE
Make http only cookies available to testcafe

### ISSUE THREAD

**Issue by ferencbeutel4711** [DevExpress/testcafe#4425]
### What is your Test Scenario?
I would like to retrieve some http only cookies from the browser into my testcafe code.

### What are you suggesting?
Please either change your proxy so that you could fetch http only cookies inside of ClientFunctions aswell or make an alternative way possible, like some kind of cookie storage on the testcafe instance.

Hi there,

it would be greatly apprechiated to have some kind of way to actually get the http only cookies from the client. AFAIK there is no way to achieve that with testcafe, but with selenium/ webdriver, there is.

I also found this: https://testcafe-discuss.devexpress.com/t/how-to-get-secure-http-only-cookie/753 however I couldnt get the mentioned workaround to work.
Thanks for your consideration!

**Comment by alexey-lin** [comment]
Hi @ferencbeutel4711,

Thank you for your suggestion. At the moment, there is no way to achieve HTTP-only cookies with TestCafe. We will consider implementing this functionality in future releases.

**Comment by alexey-lin** [comment]
Please, track the #4428 issue to be informed of any progress on this proposal.
