### ISSUE TITLE
Download fail after timeout

### ISSUE THREAD

**Issue by ognif** [DevExpress/testcafe#4426]
As sample:
`await t`
`.click(Selector('a').withText('Xml Exportieren'));`
`await t`
`.wait(150000)`

This will download a XML file via browser to the common downloads folder.

This will work if the server response immediately with the file.
If the Server need some time to generate the XML file on the fly, the download will fail.

Everything works fine with direct website access in browser. Download can have a timeout greater than 45 seconds without any problem. 
If the same case is played in Testcafe, and the time between click the link and the physical download is as sample 38 seconds, the download will fail.

To reproduce I suggest to make a PHP file that will generate a XML File on the fly with an timeout of 40 seconds and then send it to download.

Reproduce on Linux and Mac, 
Reproduce with Chrome and Firefox,

Node: 11.14.0
Testcafe: 1.2.1 / 1.6.0

**Comment by Farfurix** [comment]
@ognif 

Hello,

Could you please provide us with a simple project (or a public URL and your test code) so that we can reproduce the issue on our side? We will examine it and check for a suitable solution.
