### ISSUE TITLE
Standalone test controller can be used outside testcafe

### ISSUE THREAD

**Issue by link89** [DevExpress/testcafe#4427]
Testcafe is a battery included automation framework, you can just `npm install` and start to write script and execute it without any other dependencies. But on the other hand, testcafe's core feature, `TestController`, can only be used with testcafe, which substantially limits its usage.

As an automation engineer, I hope that testcafe can be integrated with other test framework like jest, as what we can do with webdriver.io.

A possible way to implement this feature is to provide a `TestControllerPool` to manage the life cycle of test controller. An example to use it with jest (but also with other )would like this
```typescript
import { createTestControllerPool } from 'testcafe';

// just declare which browser and how many of them to be used
// the number of browser should not less than max browsers used in single cases
const testControllerPool: TestControllerPool = createTestControllerPool(
  {
    browser: 'selenium:chrome',
    number: 4,
  },
);

beforeAll( async () => {
  // browsers will be opened and initialize from here
  await testControllerPool.init();
});

afterAll( async () => {
  // close browsers and release resource from this point
  await testControllerPool.destroy();
});

test('send messages to each other', async () => {
  // withBrowsers is a context manage (like with statement in python), which will checkout
  // 2 controllers from pool before enter the async closure
  // and it will wait automatically if not enough of browser can be used
  // and reset controllers and return to pool after exit the closure
  await testControllerPool.withBrowsers(2, async (t1: TestController, t2: TestController) => {
    // use t1 and t2 to control 2 browsers and do everything you want
  });
})
```
A lot of features in https://github.com/DevExpress/testcafe/issues/3788 can get benefit from this design, like https://github.com/DevExpress/testcafe/issues/2835 
 https://github.com/DevExpress/testcafe/issues/912

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. Your idea is great, but we already have a similar suggestion in our repository: https://github.com/DevExpress/testcafe/issues/2501. Please use it to be notified about our progress with this feature.
