### ISSUE TITLE
Testcafe behaving wierdly

### ISSUE THREAD

**Issue by Meemaw** [DevExpress/testcafe#4430]
A few days ago `testcafe` started to behave very weirdly for one of our applications and fail on some very bizarre things, such as:
- `Selector('div')` would always fail in some cases (even though there were tons of div in the application)

 I could not create a simple reproducible example as might be tied to our application, but I have bundled together our application with an API_KEY and a minimal reproducible failing test that I would like to share with the `testcafe` team.

Do you have any contact to where I could send the bundle to?

**Comment by LavrovArtem** [comment]
Yes, of course, you can send it at support@devexpress.com.

**Comment by AndreyBelym** [comment]
Thank you for your report. I've reproduced the issue, but its reason is still unclear. I need some time to research it.

**Comment by valgussev** [comment]
Hi @AndreyBelym any updates on the issue?

**Comment by AndreyBelym** [comment]
The reason is still unclear, we need some additional time for research.
