### ISSUE TITLE
Docker script returned exit code 1 after multiple tests run and Allure Reporter is Closed

### ISSUE THREAD

**Issue by mishmaccas** [DevExpress/testcafe#4431]
Dear All
I am anticipating an answer to say "this is not a DevExpress problem"
but I would like to use Allure Reporting in our Jenkins builds and we have issues with random crashing.

I'm afraid I cannot reproduce this for you easily.
And I cannot find any existing or past Allure issues about this.

My issue is that docker exits ungracefully, when I use the allure reporter in docker containers on Jenkins. 
This happens most of the time as soon as the Allure report is closed.
I tried various memory allocations and concurrent vs sequential runs but it doesnt work.
 

I have tried to reproduce this locally on my Mac but my docker run commands always pass successfully with the allure reporter.
And sometimes they pass on Jenkins slave too.

Please note the testcafe-reporter-allure plug in has not been maintained for a year.
And I have no way of contacting the author of the plugin.
In the meantime we have stopped using Allure.

I could not see any existing issues for this problem, is there anyone that can help me to shed some light?

Do you know how to contact the testcafe-reporter-allure contributor called azohra-core?

### What is your Test Scenario?
Running TestCafe multiple tests in a docker container with Allure Reporter - in Jenkins Pipeline
 
### What is the Current behavior?
Most of the time the jenkins step will fail because of an error code in Docker container
"script returned exit code 1" immediately after Allure Reporter Closed

### What is the Expected behavior?
To successfully run my tests in a docker container using --reporter allure without crashing
  

### Steps to Reproduce:

**1/  Docker file contains this sort of thing ** 
RUN npm install -g testcafe
RUN npm install
COPY . /test-suite
ENTRYPOINT ["testcafe"]
CMD ["--version"]
 
**2/ Jenkins Pipeline**

**Build Image with this command**
sh 'docker build -t test_cafe .'

**Example of a Run Docker with this command**
sh 'docker run --name="accounts" -t --memory=4g test_cafe "chromium:headless --no-sandbox" tests/Accounts/*.js -c 2 -u --skip-js-errors --env=test --locale=AU --reporter allure'
       
3/ Allure **Plugin** / Pipeline Stage -  allure will generate Reports

**4/ Report is produced and attached to the build**

### Your Environment details:
 
* testcafe version:                  "testcafe": "^1.5.0"
* node.js version:                   v 12.3.1
* allure version :  "testcafe-reporter-allure": "^1.0.5"
* browser name and version: chromium headless
* platform and version:          Linux Slave
* other:          screenshot of the offending crash
                        
<img width="325" alt="Screen Shot 2019-10-29 at 3 41 29 pm" src="https://user-images.githubusercontent.com/15898223/67741865-7bb02a00-fa6e-11e9-95cc-833dab90378c.png">

**Comment by aleks-pro** [comment]
Hello @mishmaccas ,

Please provide us with docker build logs. They might help us understand what happened during test execution.

**Comment by mishmaccas** [comment]
Sorry for delayed response.
I wanted to send the logs but I cannot reproduce this anymore. 
I changed my docker repository to alpine:latest ...
Scripts are now executing nicely using allure reporting in docker containers.

Thank you for your responses. I am closing this issue.
