### ISSUE TITLE
redirect after login fails with firefox

### ISSUE THREAD

**Issue by kaviad3** [DevExpress/testcafe#4439]
### What is your Test Scenario?
Hi 
I have an issue regarding redirect page after login .
The scenario of the test is
   0.  Firefox browser opens 
   1.  corporate authentication page opens 
   2.  Script type the user name 
   3.  Script type the password 
  4.  submit button is clicked
  5.  the browser is redirect to the site and start the empty cart function - fails

### What is the Current behavior?
the problem is that redirect fails , and I get the error "The connection was reset" with button try again , if I click on the try again manually the test continues 

the script was used to work until the login page was changed. we know that redirect url is correct because if the try again is clicked the browser login to the site with the authentication details  and the test continues 

### What is the Expected behavior?
The Expected behavior should be no error message and the test run without any error 

#### Provide the test code and the tested page URL (if applicable)

 
Your website URL (or attach your complete example):

Your complete test code (or attach your test files)

```js


import { Role } from 'testcafe';
import LoginPage from '../pageObjects/login.po';
import {testEnvironment} from "./config";

const loginPage = new LoginPage();

export const testUser = Role(testEnvironment.feUrl, async t => {
    await t
        .setTestSpeed(0.8)
        .wait(1000)
        // .click(loginPage.returnToLegacyLogon)
        .typeText(loginPage.inputUserId, testEnvironment.userId)
        .typeText(loginPage.inputPassword, testEnvironment.password)
        .click(loginPage.chkRememberMe)
        .click(loginPage.btnSubmit)
        .click(loginPage.btnSuccessOk);
}, { preserveUrl: true });

fixture `Clone order`
    .page(testEnvironment.feUrl)
    .requestHooks(logger)
    .beforeEach(async t => {
        await t.useRole(testUser);
        await CommonActions.emptyCart(t);
        await orderProducts.selectServiceByName(productName);
        await t
            .hover(productDetails.btnAddItemToCart, { speed: 0.3 }).click(productDetails.btnAddItemToCart)
            .click(homePage.btnCart)
    });



```
### Your Environment details:
 
* testcafe version:   1.6                
* node.js version:    8.16.0                
* command-line arguments:  testcafe --live --hostname localhost firefox ./tests/sanity/order/clone_order.ts
* browser name and version:  FireFox 70.01
* platform and version:          windows 10 
* other:

**Comment by alexey-lin** [comment]
Hi @kaviad3,

Could you please describe the changes that were introduced to your login page? The issue obviously has something to do with them.

We'd love to help you, but the information that you provided so far is not sufficient to reproduce the issue on our side and to diagnose its cause.

**Comment by kaviad3** [comment]
Hi @alexey-lin

we fixed the issue , the problem was with the command 
.requestHooks(logger)

after we remove it the test continue with out any problem,

Ope it will help other
