### ISSUE TITLE
Download file native dialog in Internet Explorer 11 (IE 11)

### ISSUE THREAD

**Issue by Farfurix** [DevExpress/testcafe#4445]
https://supportcenter.devexpress.com/ticket/details/t824766/handle-save-as-dialog-in-firefox-and-ie

### Steps to Reproduce:
**index.html**
```html
<html>
<head></head>
<body>
    <a href="/file.xlsx" download>Download</a>
</body>
</html>
```

**test.js**:
```js
import { Selector } from 'testcafe';
// import fs from 'fs';

fixture `Fixture`
    .page `http://localhost:8080/index.html`;

test('test', async t => {
    await t
        .click(Selector('body > a:nth-child(1)'));

    await t.wait(4000);

    // const filePath = 'c:\\Users\\name\\Downloads\\file.xlsx';
    // await t
    //     .expect(fs.existsSync(filePath)).ok();
});
```

1. Run `testcafe ie test.js`.
2. See the following result:
![Capture](https://user-images.githubusercontent.com/30019338/68204815-dcdd7d80-ffd9-11e9-9502-9462a97b401a.PNG)
 
### Your Environment details:
 
* testcafe version: v1.6.0
* browser name and version: IE 11
* platform and version: Windows 10

**Comment by AlexKamaev** [comment]
I researched the issue and concluded that it's not possible. I tried some suggestions from Google, however, some of them are obsolete, others are not applicable.
I'm afraid, the issue cannot be solved at this moment - see the following thread: [https://answers.microsoft.com/en-us/ie/forum/ie11-iewindows_10/can-i-automatically-save-downloaded-files-in-ie11/cfb58f5e-c748-42fd-bde6-25d9912426f3](https://answers.microsoft.com/en-us/ie/forum/ie11-iewindows_10/can-i-automatically-save-downloaded-files-in-ie11/cfb58f5e-c748-42fd-bde6-25d9912426f3)
