### ISSUE TITLE
[docs] Inconsistency between doc and code

### ISSUE THREAD

**Issue by frejfrej** [DevExpress/testcafe#4448]
I am trying to use the Selector.withAttribute method, and can't tell if the method should be wrapped in async/await.

### What is the Current behavior?
Selector.withAttribute, as documented [here](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/functional-style-selectors.html#withattribute), mentions the return type to be a Selector.
When I hover this method in VSCode, the method signature tells me it returns a SelectorPromise.

### What is the Expected behavior?
Well, I would expect consistency
 
### What is your web application and your TestCafe test code?
This impacts wether the method using this is
 
### Your Environment details:
 
* testcafe version: 1.4.2
* node.js version: 10.16.3
* platform and version: Windows 10

**Comment by AndreyBelym** [comment]
Thank you for your report. There is a mistake in our TypeScript Definitions. We will fix it ASAP.
