### ISSUE TITLE
Enhancement for pressing the mouse and holding.

### ISSUE THREAD

**Issue by TravisBert** [DevExpress/testcafe#4450]
### What is your Test Scenario?
I would like to be able to press the mouse and hold that press. The reason for is for having the ability to test functionality related to long presses with the mouse, or some sort of long hold.

### What are you suggesting?
Currently we have functionality that requires a long click and hold to activate some functionality. I have been looking for a way to test this but have been unsuccessful.

### What alternatives have you considered?
I have looked for a little while now and haven't been able to find anything that could help my situation but I might have over looked.

### Additional context
I think this would be really good for mobile touch and hold options. Would open a lot of new test cases that testcafe could cover.

**Comment by TravisBert** [comment]
Also similar to this, a click + hold that click and drag for fence selecting stuff.

**Comment by AlexKamaev** [comment]
Hi,
We already have similar requests, so I'll close this one as a duplicate.
At the moment, we cannot give you any estimates as to when this behavior will be implemented.

Similar issues:
[https://github.com/DevExpress/testcafe/issues/2054](https://github.com/DevExpress/testcafe/issues/2054)
[https://github.com/DevExpress/testcafe/issues/2803](https://github.com/DevExpress/testcafe/issues/2803)
[https://github.com/DevExpress/testcafe/issues/527](https://github.com/DevExpress/testcafe/issues/527)
