### ISSUE TITLE
Download File with Browserstack

### ISSUE THREAD

**Issue by ognif** [DevExpress/testcafe#4451]
In my tests I download a file by clicking a link. This is the native browser download to the native downloads folder. Works well with local browsers.

But in modern world we use as sample Browserstack. Now with Browserstack the file is downloaded to the virtual machine where the test is running. There have to be a way to get this file to the server who started the test run on Browserstack so it is possible to open the file for further tests inside Testcafe. Currently all tests with Browserstack are broken that expect a file inside the downloads folder.

**Comment by AlexKamaev** [comment]
I cannot say if it is possible to send the downloaded file to your host using the BrowserStack API. It's better to address this question to the BrowserStack team.

From the TestCafe perspective, I can recommend you take a look at the built-in Request Hooks mechanism. Please refer to the following article:  [Logging HTTP Requests](https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/logging-http-requests.html)

You can setup the `logger` object to log requests to the target file url. After the request is completed, you will be able to check the body of the response, which contains the file.

When you have the file, you can write some custom code and process it as you wish.
