### ISSUE TITLE
Unable to use RequestMock asynchronously 

### ISSUE THREAD

**Issue by timmak** [DevExpress/testcafe#4456]
### What is your Test Scenario?
```js

const GraphQLMock = RequestMock.onRequestTo("http://localhost:3000/graphql/").respond(async (req, res) => {
  res.setBody(await graphql(mockedSchema, JSON.parse(req.body).query))
})

fixture`Test Graphql Mock`.page`http://localhost:8080`.requestHooks(GraphQLMock)

```
 
### What is the Current behavior?

- res.setBody is not defined in an async case as its delete before it is reached
- RequestMock is exported as factory function rather then the class so can't be inherited

### What is the Expected behavior?

- Have respond take a promise
- Export RequestMock class so if can be extended 
 
### Your Environment details:
 
* testcafe version:                   1.6.0
* node.js version:                    v12.13.0

**Comment by aleks-pro** [comment]
Hello @timmak ,

_>> Have respond take a promise_
I've created a separate [feature request](https://github.com/DevExpress/testcafe/issues/4467) for this issue. You can follow it to be informed about our progress.

_>> Export RequestMock class so if can be extended_
Please describe your scenario in greater detail. Why do you want to extend the `RequestMock` class?

**Comment by timmak** [comment]
## Why do you want to extend the RequestMock class?

Not a requirement but I am would be able to create my own async RequestMock if it was a class by extending the current implementation.
