### ISSUE TITLE
Using alpine:latest instead of alpine:edge

### ISSUE THREAD

**Issue by chrisleekr** [DevExpress/testcafe#4459]
### What are you suggesting?

At the moment, testcafe is using Alpine:edge to build the docker image.
However, it looks like alpine:edge does not have x86_64 build.

**http://dl-cdn.alpinelinux.org/alpine/edge/main/**
![image](https://user-images.githubusercontent.com/5715919/68445954-7782ca00-022f-11ea-89fa-3d4167186c2a.png)

Because of the above issue, I am having an issue to add extra package based on the testcafe image.

```
Step 4/10 : RUN apk add curl
 ---> Running in 78752a2c7804
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/edge/main: No such file or directory
WARNING: Ignoring APKINDEX.066df28d.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/edge/community: No such file or directory
WARNING: Ignoring APKINDEX.b53994b4.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  curl (missing):
    required by: world[curl]
The command '/bin/sh -c apk add curl' returned a non-zero code: 1
```

I can see the commit two days ago to workaround the issue.
https://github.com/DevExpress/testcafe/commit/740c04324ee14b8cef4925195f6b035ba03e6c08#diff-ebacf6f6ae4ee68078bb16454b23247d

I understand this is technically an issue with alpine, not testcafe.
My question is why not just using alpine:latest instead of alpine:edge? Is there any specific reason for using alpine:edge?

### What alternatives have you considered?

Use alpine:stable to build testcafe image.

### Additional context

To workaround, I just use alpine:latest-stable repository to add extra packages.

```
FROM testcafe/testcafe:latest

USER root

RUN apk --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/latest-stable/main/ upgrade && \
    apk --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/latest-stable/main/ add \
   curl
```

**Comment by AndreyBelym** [comment]
Firefox versions in `alpine:latest` are very outdated:

https://pkgs.alpinelinux.org/packages?name=firefox-esr&branch=v3.10

vs

https://pkgs.alpinelinux.org/packages?name=firefox-esr&branch=edge

That's the only reason why we have to use `alpine:edge` as a base image until the situation with Firefox in `alpine:latest` improves.

When it comes to the problem with the missing `x86_64` packages, I guess your build happened in a very unfortunate moment when the `x86_64` repository index was in the middle of the rebuilding process. It can happen with any image version. Right now it is fine as always.
