### ISSUE TITLE
Intercept AND invalidate request

### ISSUE THREAD

**Issue by Raph-Capitale** [DevExpress/testcafe#4466]
Hello everyone ! I am currently trying to intercept requests sent to GA (which I am able to do) and stop the request so no data is sent to GA. 

I tried the mocking section of the documentation, which also works, but even if I mock the request and the response, data is still sent to GA.

I tried the hook section of the documentation (example below) in which I alter the request sent to GA by altering its URL from https://www.google-analytics.com/collect to a non-google URL.

import {
  RequestHook,
  RequestMock
} from 'testcafe';

export class CybermetrieRequestHook extends RequestHook { // RequestMock
  constructor(requestFilterRules, responseEventConfigureOpts) {
    super(requestFilterRules, responseEventConfigureOpts);
  }

  async onRequest(event) {
    event.requestOptions.url = "https://uselessURL.com";
  }
  async onResponse(event) {
 // ...
  }
}

Throwing Errors in the MOCK or HOOK methods still do not allow me to block, stop or invalidate the request. 

Can somebody help me ^

**Comment by miherlosev** [comment]
Hi @Raph-Capitale

> I tried the mocking section of the documentation, which also works, but even if I mock the request and the response, data is still sent to GA.

You don't need to write a custom hook for it. Inspect the Network in DevTools, determine all of the Google Analytics requests (requests can be sent via several URLs) and mock them using the built-in 'RequestMock' class.
See this [example](https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/#mocking-http-responses) for more information.

**Comment by Raph-Capitale** [comment]
Thanks Milher, but that way I still see the data coming out in GA ... I had already tried that solution without success ...

**Comment by Raph-Capitale** [comment]
Here is my setup : [![Screenshot from Gyazo](https://gyazo.com/e3ec6921aa22ad4011646e11067800ee/raw)](https://gyazo.com/e3ec6921aa22ad4011646e11067800ee)
