### ISSUE TITLE
Provide a way to execute an asynchronous code in a Custom Response Function

### ISSUE THREAD

**Issue by aleks-pro** [DevExpress/testcafe#4467]
### What is your Test Scenario?
Asynchronous code is used to generate a response body

### What are you suggesting?
The [`respond`](https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/mocking-http-requests.html#the-respond-method) method should accept an asynchronous [Custom Response Function](https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/mocking-http-requests.html#a-custom-response-function)

**Comment by aleks-pro** [comment]
https://github.com/DevExpress/testcafe/issues/4456

**Comment by miherlosev** [comment]
```js
var mock = RequestMock()
    .onRequestTo(/*...*/)
    .respond(async (req, res) => {
        // ...
    });
```

**Comment by timmak** [comment]
> ```js
> var mock = RequestMock()
>     .onRequestTo(/*...*/)
>     .respond(async (req, res) => {
>         // ...
>     });
> ```

Currently this doesn't work you can no set the body as it, the async function is put on the stack then on the next line req.setBody is removed before it can execute.

But ideally it would be nice if the api supported the above

**Comment by MeisterTea** [comment]
Hi, I am also stuck. Please see [here](https://stackoverflow.com/questions/59845424/mock-apollo-queries-inside-of-testcafe)

**Comment by miherlosev** [comment]
Hi @MeisterTea 

At present, this feature is not implemented. If it's important to you, we would highly appreciate a PR.
