### ISSUE TITLE
Firefox not running (headlessly or not) on docker with debian

### ISSUE THREAD

**Issue by franciscolosardo** [DevExpress/testcafe#4468]
### What is your Test Scenario?

 I'm using testcafe on a docker container which is based on debian. I use Xvfb to run a virtual screen in which i use testcafe.

### What is the Current behavior?

Chrome has no problems at all, it runs with the --no-sandbox argument without problems. It even records and takes screenshots
Firefox on the other hand is not working properly. I tried running firefox on the Xvfb after using fluxbox on it. I tried even running firefox:headless without luck.
Tests just don't seem to open or run the web browser. I get to where every test should start and im getting the following error on each :

`GeneralError: Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
    at BrowserSet._waitConnectionsOpened (/var/lib/jenkins/workspace/XXXX/node_modules/testcafe/lib/runner/browser-set.js:63:30)
    at /var/lib/jenkins/workspace/XXXX/node_modules/testcafe/lib/runner/browser-set.js:80:31
    at Bootstrapper._getBrowserConnections (/var/lib/jenkins/workspace/XXXX/node_modules/testcafe/lib/runner/bootstrapper.js:63:16)
    at Function.all (<anonymous>:null:null)
    at Bootstrapper._bootstrapParallel (/var/lib/jenkins/workspace/XXXX/node_modules/testcafe/lib/runner/bootstrapper.js:168:39)
    at Bootstrapper.createRunnableConfiguration (/var/lib/jenkins/workspace/XXXX/node_modules/testcafe/lib/runner/bootstrapper.js:184:69)
 {
  code: 'E1004',
  data: []
}`

### What is the Expected behavior?

 Firefox should run properly

### Your Environment details:
 
* testcafe version: 1.6.0                   
* node.js version: 13.1.0                   
* platform and version: Debian 10          
* other:

**Comment by miherlosev** [comment]
Hi @franciscolosardo 

Could you please provide a docker image with which we can reproduce the problem?

**Comment by franciscolosardo** [comment]
Ill paste our dockerfile since it doesn't have any personal or business related info :

``` 
FROM debian:latest
ARG packageId

RUN echo "Installing Visual Interface (XVFB)"
RUN apt-get update > /dev/null && \
      apt-get -y install sudo > /dev/null

RUN apt-get -qq --assume-yes install procps > /dev/null
RUN apt-get -qq --assume-yes install wget > /dev/null
RUN apt-get -qq --assume-yes install xvfb xfonts-100dpi xfonts-75dpi xfonts-cyrillic xorg dbus-x11 > /dev/null
RUN apt-get -qq --assume-yes install curl > /dev/null
RUN apt-get -qq --assume-yes install fluxbox > /dev/null
RUN apt-get remove iceweasel
RUN apt-get --assume-yes install libgtk-3-0 libdbus-glib-1-2 libasound2 libgtk2.0-0



#RUN apk add --no-cache py-pip git openssh bash
RUN rm -rf node_modules
RUN rm -rf package-lock.json

RUN apt-get --assume-yes remove nodejs > /dev/null

RUN echo "Installing NODEJS"

RUN wget -qO- https://deb.nodesource.com/setup_13.x | bash -

RUN apt-get install -y nodejs build-essential  xvfb > /dev/null

RUN echo "Installing Chrome"

RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb > /dev/null
RUN apt-get -q --assume-yes install ./google-chrome-stable_current_amd64.deb > /dev/null

RUN apt-get --assume-yes install screen > /dev/null

RUN echo "Installing Firefox"

RUN apt-get --assume-yes install software-properties-common > /dev/null
RUN apt-get update > /dev/null
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A6DCF7707EBC211F
RUN add-apt-repository "deb http://ppa.launchpad.net/ubuntu-mozilla-security/ppa/ubuntu bionic main"
RUN apt-get update > /dev/null
RUN apt-get --assume-yes install firefox > /dev/null



RUN echo "Cleaning NodeJS Cache"

RUN npm cache clean --force

RUN npm install -g testcafe  && \
 npm cache clean --force && \
 rm -rf /tmp/*

RUN apt-get --assume-yes install default-jdk > /dev/null

RUN npm install -g allure-commandline --save-dev

ARG CACHEBUST=1

RUN rm -rf screenshots
RUN rm -rf logs
RUN rm -rf videos
RUN mkdir screenshots
RUN chmod 777 screenshots
RUN rm -rf logs


RUN mkdir /tmp/.X11-unix
RUN chmod 1777 /tmp/.X11-unix
RUN chown root /tmp/.X11-unix/


```

**Comment by franciscolosardo** [comment]
I'll also add we tried with firefox-esr which is the usually distributed version of firefox on debian in docker

**Comment by AlexKamaev** [comment]
I'll close this issue in favor of https://github.com/DevExpress/testcafe/issues/4306
We will check this scenario after the https://github.com/DevExpress/testcafe/issues/4306 issue is fixed.

**Comment by franciscolosardo** [comment]
Just to make sure we both don't spend time testing concurrency, i want to insist that the problem isn't concurrency, as i tried to run just one instance of testcafe with just one test and that didn't work either.
Also, i created a virtual box machine with debian running and when trying the same commands we tried in the docker , the tests work fine.
