### ISSUE TITLE
Couldn't navigate back to URL

### ISSUE THREAD

**Issue by PavithraJaran** [DevExpress/testcafe#4471]
I have generated a report (in PDF) by clicking the button, report (in PDF) has generated in browser. Now I couldn't return back to the previous URL from the report (in PDF) URL. I have used NavigateTo(), to do these actions, but I could not run the test as expected. 

Thanks,

**Comment by miherlosev** [comment]
Hi @PavithraJaran 

It's a known limitation - TestCafe cannot operate with non-HTML pages.
Track the #1471 issue to be informed about our progress.
