### ISSUE TITLE
The typeText action does not work with the DevExtreme Lookup search field

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe#4472]
### What is your Test Scenario?
I need to type text into the dxLookup search field to find a particular item.
 
### What is the Current behavior?
The search field loses focus and stays empty.
 
### What is the Expected behavior?
The required text should be entered into the search field.
 
### What is your web application and your TestCafe test code?
 
Your website URL (or attach your complete example):
https://js.devexpress.com/Demos/WidgetsGallery/Demo/Lookup/Basics/jQuery/Light/

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from 'testcafe';

fixture `Devextreme`
    .page `https://js.devexpress.com/Demos/WidgetsGallery/Demo/Lookup/Basics/jQuery/Light/`;

test('Test 1', async t => {
    await t
        .switchToIframe(Selector('#demoFrame'))
        .expect(Selector('.dx-lookup-field-wrapper').exists).ok({
            timeout: 30000
        })
        .click(Selector('.dx-lookup-field-wrapper').find('div').withText('John Heart'))
        .click(Selector('.dx-texteditor-input'))
        .typeText(Selector('.dx-texteditor-input'), 'Billy')
        .expect(Selector('.dx-lookup-field-wrapper').find('div').withText('Billy').visible).ok();
});
```
</details>

### Steps to Reproduce:
Run the test
 
### Your Environment details:
 
* testcafe version:                   1.6.1
* node.js version:                    v10.16.0
* command-line arguments:  testcafe chrome test3.js
* browser name and version: Chrome 78
* platform and version:          Win10
* other:

**Comment by Dmitry-Ostashev** [comment]
I reproduced this issue with the `testcafe-hammerhead` playground:
![dxtreme-lookup-hammerhead](https://user-images.githubusercontent.com/24777868/113992816-7f97cc80-985c-11eb-91e9-799b49ca33ea.gif)

**Comment by Dmitry-Ostashev** [comment]
https://supportcenter.devexpress.com/internal/ticket/details/T988517

**Comment by wentwrong** [comment]
Fixed in https://github.com/DevExpress/testcafe-hammerhead/pull/2635
