### ISSUE TITLE
Mocking requests and NOT sending them to GA

### ISSUE THREAD

**Issue by Raph-Capitale** [DevExpress/testcafe#4473]
Hello everyone,

Here is my problem : I want my testcafe tests to run multiple times a day and I do NOT want the Pageviews and other events from my tests to appear in Google Analytics. However, I tried mocking requests AND the request hook.

Every single time, I still see the data appearing in my Google Analytics dashboard and stats.

I went through the testcafe documentation and didn't find the answer I was searching for.

Thank you ! Here is my setup : 

```js
const collectDataForGA = new RegExp('https://www.google-analytics.com/collect');

const mockedResponseGA = Buffer.from([0x47, 0x49, 0x46, 0x38, 0x39, 0x61, 0x01, 0x00, 0x01]);

const mock = RequestMock()
  .onRequestTo(collectDataForGA) // collectDataForGA   
  .respond(mockedResponseGA, 202, {
    'content-length': mockedResponseGA.length,
    'content-type': 'image/gif'
  });

fixture `Use Case : LACAPITALE-INTERCEPTOR`
  .page `https://www.lacapitale.com/fr?raph=testcafeMOCKER3333333333333333`.requestHooks(
    logger, mock
  );
 ```

**Comment by Farfurix** [comment]
@Raph-Capitale 

Hello,

I think it is a common task to turn off your Google Analytics in a testing environment. Here are some links about it:
https://developers.google.com/analytics/devguides/collection/android/v4/advanced#testing
https://developers.google.com/analytics/devguides/collection/gtagjs/user-opt-out

As for your `RequestMock` workaround, I suggest you [collect](https://github.com/DevExpress/testcafe/issues/4466#issuecomment-552408706) all your non-blocked Google Analytics requests: may be you should add addition URLs in your `RequestMock` or make your `filter` more common (`onRequestTo(/google-analytics/)`).
