### ISSUE TITLE
Authorization headers appear to be mangled 

### ISSUE THREAD

**Issue by chriswwalz** [DevExpress/testcafe#4474]
### What is your Test Scenario?

Upload to firebase using testcafe
 
### What is the Current behavior?

Upload is forbidden
 
### What is the Expected behavior?

Upload is OK
 
#### What the header looks

Without Testcafe: 

`Authorization: Firebase {token}`

With Testcafe: 

`Authorization: hammerhead|prefix|by-clientFirebase {token}`

notice that by-client and Firebase are appended to each other. How do I handle this? 

![image](https://user-images.githubusercontent.com/52255961/68602709-d5ecba00-0474-11ea-89f4-374dc9b50b31.png)
<summary>Your complete test report:</summary>
 
### Your Environment details:
 
* testcafe version:                   1.6.1
* node.js version:                    9.11.1
* command-line arguments:  testcafe chrome {fileName}
* browser name and version: Chrome 78
* platform and version:          Mac Mojave

**Comment by Farfurix** [comment]
@chriswwalz 

Hello,

If I understand you correctly, this "Request Headers" information is from Chrome DevTools. The "hammerhead" prefix is a part of our internal logic.

If you want to check an Authorization header value, you need to check it on your server side. Let us know whether the received header value is correct on the server side. If not, please provide us with a minimal example, so we can reproduce it and check for a suitable solution.

**Comment by chriswwalz** [comment]
I would tell you what the header looks like server side but unfortunately the request is sent to firebase so don't have access to it

**Comment by AlexanderMoiseev** [comment]
Hello,
Please send us a small project reproducing the problem.

**Comment by franciscolosardo** [comment]
Hi testcafe devs! WE're facing a similar issue we're getting a prefix attached to our Authorization requests :

~~~TestCafe added this prefix to control the authorization flow~~~ Bearer tokenXXXX....

This is a blocker for us as we can't continue testing our app with a token passed through uri param.
We're running the client on a webpage which captures from a URI parameter this Auth token and uses it in a request. This request adds this prefix automatically.

**Comment by miherlosev** [comment]
Hi @franciscolosardo

Let's continue the discussion in the DevExpress/testcafe-hammerhead#2690 thread.
