### ISSUE TITLE
Investigate screenshot problems introduced in v1.6.0

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#4477]
- [x] https://github.com/DevExpress/testcafe-browser-provider-saucelabs/issues/53
 - [x] https://github.com/DevExpress/testcafe/issues/4440
 - [ ] https://github.com/DevExpress/testcafe/issues/4475

**Comment by renita1509** [comment]
I am also facing the same issue of not being able to take a screenshot  with v1.6.0 specifically with "testcafe-browser-provider-puppeteer": "1.4.0",

**Comment by AlexKamaev** [comment]
I'll close it after
https://github.com/DevExpress/testcafe/issues/4475

**Comment by weyert** [comment]
Anyway you could release this fix for testcafe? Maybe as `next` channel on npm?

**Comment by miherlosev** [comment]
Hi @weyert 

We are going to release the `alpha` version of TestCafe this week. The released version will include the necessary fix.

**Comment by weyert** [comment]
Awesome, thank you very much! :)
