### ISSUE TITLE
Screenshots do not get taken for all failure conditions

### ISSUE THREAD

**Issue by switch201** [DevExpress/testcafe#4479]
### What is your Test Scenario?
I am throwing a custom exception in typescript from one of my cucumber steps. I am using the test runner API and I have everything set up to take screen shots on failure. this works when throwing an assertion error, but other error types don't appear to cause the screenshot to be taken.
 
### What is the Current behavior?
A screenshot is not taken in these cases even though the test fails
 
### What is the Expected behavior?
A failure screen should be taken when an exception is thrown from a cucumber step, (while screenshots on failure are enabled)
 
### What is your web application and your TestCafe test code?
I am throwing the exception like so:
```
throw new Error("Wait Time Out Exception. An element you were waiting for did not appears after " + timeout.toString() + " seconds.")
```
Your website URL (or attach your complete example):
N/A
<details>
<summary>Your complete test code (or attach your test files):</summary>
</details>
Create a cucumber st
<details>
<summary>Your complete configuration file (if any):</summary>

```
TestCafe version 1.6.0
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Configure the test runner API to allow for screenshots on failure
3. Create a step that goes to a web page, and then throws a custom exception similar to what is shown above
4. The screenshot will not be taken for this failure but it should be.
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by switch201** [comment]
I think the same behavior can occur when testcafe throws an error (for example what it can't find an action element on the screen or something similar). If possible it should take a screen shot in these cases as well.

**Comment by AlexKamaev** [comment]
I've checked the screnario and it works.

Here is the test code:
```JS
fixture `New Fixture`
    .page `http://example.com`;

test('New Test', async t => {
    throw new Error('It is a custom error');
});
```
And here is my terminal command:
```
testcafe chrome index.ts -s takeOnFails=true
```
I've got a screenshot as expected.
Could you please provide with a more detailed description and test code, which demonstrates the issue?

**Comment by switch201** [comment]
In my case I am setting the screenshot option via the test runner API rather than on the command line. here is that code snippet:
```
    createTestCafe('localhost')
      .then(function (tc: any) {
        testcafe = tc
        myTestCafe = tc
        runner = tc.createRunner()
        let screenshotPath = 'artifacts/screenshots/testcafe'
        if(process.env.SCREENSHOT_PATH){
          screenshotPath = process.env.SCREENSHOT_PATH
        }
        return runner
          .src(stepDefinitionsPath + '/test.js')
          .browsers(getBrowserSettings())
          .reporter('list')
          .screenshots({path: screenshotPath, takeOnFails: process.env.SCREENSHOT == 'true', fullPage: true})
          .run({
            skipJsErrors: true,
            quarantineMode: true,
            selectorTimeout: 10000,
            assertionTimeout: 10000,
            pageLoadTimeout: 10000
            //speed: 0.1
          })
          .catch(function (error: any) {
            console.error('Runner error count was: ', error)
          })
      })
      .then(function (report: any) {
        console.error('Report data was: ', report)
      })
```

**Comment by miherlosev** [comment]
I've created an [example](https://github.com/DevExpress/testcafe/files/3896799/i4479.zip)
 with Runner API and it works as expected.
Could you please provide a simple example that we can run locally without any additional setup?
