### ISSUE TITLE
t.typeText() function does not fire beforeInput event on input.

### ISSUE THREAD

**Issue by randomUser222** [DevExpress/testcafe#4486]
### What is your Test Scenario?
I have an input and some functionality in beforeInput event handler, that prevents characters other than digits to be stored into value. Once text with incorrect characters is typed into the input, the value should ignore them and contain only digits. I need the beforeInput event specifically for typing on Android keyboard, which works badly with KeyPress, KeyUp and KeyDown. 
 
### What is the Current behavior?
.typeText() types correctly text into input, but beforeinput event is never called, so the stored value is not changed.
 
### What is the Expected behavior?
Typing into input should fire same events as in manual tests on Chrome.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):
I made a simple Stackblitz use case.
https://stackblitz.com/edit/angular-xcfta5?file=src%2Fapp%2Ftestfile.ts

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
import {Selector} from 'testcafe';
 fixture `Input type number`
    .page(`https://angular-xcfta5.stackblitz.io`);
test.only('Should test that the value contains only digits', async () => {
    await t
        .typeText(Selector('#nativeInput'), 'abc25')
        .expect(Selector('#inputString').value).eql('25');
});
```
</details>

### Steps to Reproduce:

1. Go to the stackblitz example
2. Type text  'abc25' into the input
3. You can see that below the input 25 would be shown as the value stored.
4. Run the test
5. See that the value would be undefined because .typeText does not react to beforeinput event
 
### Your Environment details:
 
* testcafe version:                   1.2.1
* node.js version:                    10.16.0
* command-line arguments:  testcafe chrome test.ts
* browser name and version: Chrome 78, Android Chrome 78
* platform and version:          Win10, Android 9

**Comment by AlexKamaev** [comment]
I've reproduced the issue in Win10

**Comment by palpatine1991** [comment]
I would add that the same case is on Chrome on android...

**Comment by miherlosev** [comment]
Hi @palpatine1991 

We will fix this issue so that the `beforeinput` event will be raised in all compatible browsers.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/beforeinput_event
