### ISSUE TITLE
Custom User Agent causes simple test to Fail

### ISSUE THREAD

**Issue by ManuelMos** [DevExpress/testcafe#4491]
### What is your Test Scenario?
Login to intranet site using Azure AD. To bypass local certificate i need to use a custom useragent.
 
### What is the Current behavior?
Instead of entering credentials just the first letter is repeated and in console an error is thrown

  1) Uncaught object "[object Object]" was thrown. Throw Error instead.

      Browser: Chrome 78.0.3904 / Windows 10.0.0

 
### What is the Expected behavior?
Testcafe shoul enter my e-mail adress in the username field.
 
### What is your web application and your TestCafe test code?
Your website URL (or attach your complete example): https://login.microsoftonline.com

 
```js
 test('Open App', async t => {
    await t
        .typeText(
            Selector("input").withAttribute("type", "email"),
            'example@example.com'
        )
        .typeText(
            Selector("input").withAttribute("type", "password"),
            'myPw'
        )
        .click(Selector("input").withAttribute("type", "submit"))
        .wait(4000)

});
```

### Steps to Reproduce:

1. Start Test with custom user agent: testcafe --skip-js-errors "chrome:emulation:userAgent=\'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36'" first.js -L
 
### Your Environment details:
 
* testcafe version:                   1.6.90
* node.js version:                   10.16.3
* command-line arguments:  testcafe --skip-js-errors "chrome:emulation:userAgent=\'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36'" first.js -L
* browser name and version:  chrome
* platform and version:          Windows 10

**Comment by AlexKamaev** [comment]
It looks like you incorrectly escape your user agent string.
Try to use the following command in `powershell`:

```JS
testcafe 'chrome:emulation:userAgent=''Mozilla/5.0 (X11\; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36''' test.js
```

Please refer to the following issue to get the detailed explanation: https://github.com/DevExpress/testcafe/issues/3109
