### ISSUE TITLE
Support for changing accessTokens with useRole

### ISSUE THREAD

**Issue by bertBruynooghe** [DevExpress/testcafe#4492]
### What is your Test Scenario?
```
test('xxx', async t => {
  await t.useRole(anAdminUser)
  await ClientFunction(() => window.localStorage.setItem('xxx', 'xxx'))()
  await t.expect(await ClientFunction(() => window.localStorage.getItem('xxx'))()).eql('xxx')
}
test('yyy', async t => {
  await t.useRole(anAdminUser)
  await t.expect(await ClientFunction(() => window.localStorage.getItem('xxx'))()).eql('xxx') /* => fail */
}
```

### What are you suggesting?
If a role was still active at the time of the exiting the test, localStorage and cookies should (optionally?) be stored along with the role.
Same behaviour should happen when switching roles within a test.

### What alternatives have you considered?
A custom `useRole`, ` beforeEach` and `afterEach`, duplicating the stored information.

```
const roleAnonymous = Role.anonymous()
let lastUsedRole = roleAnonymous

// use this useRole in all m4e tests iso. testcafé's useRole because the latter messes up refresh tokens
async function useRole (t, role) {
  lastUsedRole.sessionLocalStorage = await extractSessionFromLocalStorage()
  await t.useRole(role)
  lastUsedRole = role
  if (!role.sessionLocalStorage) return // role logged in for the first time
  loadSessionToLocalStorage(role.sessionLocalStorage)
}

async function beforeTest (t, role) {
  await useRole(t, role)
  if (!role.sessionLocalStorage) return // role logged in for the first time
  loadSessionToLocalStorage(role.sessionLocalStorage)
}

async function afterTest  (_t, role) {
  role.sessionLocalStorage = await extractSessionFromLocalStorage()
  loadSessionToLocalStorage(roleAnonymous.sessionLocalStorage)
  lastUsedRole = roleAnonymous
}
```

### Additional context
I do think this is a scenario that is quite often needed if you use accessTokens with expirytimes shorter than the testsuite...

**Comment by miherlosev** [comment]
Hi @bertBruynooghe

I think that the described workaround with modifying the 'localStorage' is the best solution for your use case.
If you perform all test actions manually, you will get the same behavior - the session will be expired. I will close this issue. If there are requests for this functionality in the future, I will reopen it.
This [example](https://github.com/DevExpress/testcafe/issues/2142#issuecomment-367618275) with 'localStorage' manipulation can be useful to you.

**Comment by bertBruynooghe** [comment]
Ok, I can relate to that. But why would I even bother to use testcafé's `useRole` if it doesn't even properly support refreshToken behaviour?

**Comment by AlexKamaev** [comment]
Probably, roles are not required in your case, and the workaround @miherlosev suggested is more appropriate.
