### ISSUE TITLE
how to set cookie before redirect?

### ISSUE THREAD

**Issue by natvaldev** [DevExpress/testcafe#4495]
My web application redirect any unauthenticated user to external authentication application.
Using `setCookie` doesn't work since the page redirect before the `setCookie` finishes.

Can I disable the redirect somehow?
Or another solution?

**Comment by arubtsov** [comment]
Hi @natvaldev,

Just navigate to your original page after setting the cookie: `await t.navigateTo('https://your.page/');`. You may also consider using [Role](https://devexpress.github.io/testcafe/documentation/test-api/authentication/user-roles.html) as it is done [here](https://github.com/DevExpress/testcafe/issues/1721#issuecomment-379304569). Feel free to reopen this issue if you face any difficulties.

**Comment by natvaldev** [comment]
Hi @arubtsov thanks for your response.
As I mentioned, my application redirect an unauthenticated users,
so I can't set the document cookie (since it changes before the cookie can be set).

I have seen the `cypress` do offer a built in function to set a cookie before the page loads.
Do you know if `testcafe` can do the same?

**Comment by AlexKamaev** [comment]
@natvaldev
@arubtsov meant that if you already have the correct cookie, you can set it before navigating to your target page. Tests start with the `about:blank` page by default. Set the cookie there and then use the `navigateTo` method.
