### ISSUE TITLE
Couldn't handle browser alert

### ISSUE THREAD

**Issue by PavithraJaran** [DevExpress/testcafe#4502]
In my application ,I'm able to delete the records from the modules, which has trash button on list page, but in the case of delete button at edit page has not been handled browser confirmation alert, due to this the record has not been deleted during the automation. How can I solve this?

**Comment by alexey-lin** [comment]
Hi @PavithraJaran,

You can solve this using the [Dialog Handler](https://devexpress.github.io/testcafe/documentation/test-api/handling-native-dialogs.html).
