### ISSUE TITLE
RequestLogger instant logging requests

### ISSUE THREAD

**Issue by orihomie** [DevExpress/testcafe#4503]
Hey, I'm tryin to use RequestLogger to spy requests while executing tests and as I can see - requests are stored in logger's "requests" property, but isnt that option to make them log instantly as they made?

That would be an option to see what's going on the background of running test.

**Comment by alexey-lin** [comment]
Hi @orihomie,

If you want to perform some actions immediately as a request send, you can create your own custom logger for it using the approach described in the [Creating a Custom HTTP Request Hook](https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/creating-a-custom-http-request-hook.html) article.

**Comment by AlexKamaev** [comment]
Just a reminder that your approach uses our internal api.
I would still recommend you have a look at `custom-hooks`.
