### ISSUE TITLE
How would you run a a HTTPs website on Safari?

### ISSUE THREAD

**Issue by monagarg10** [DevExpress/testcafe#4509]
### What is your Test Scenario?
Trying to open a page.

### What is the Current behavior?
 It keeps loading. 

### What is the Expected behavior?
The homepage page should be loaded 

### How would you reproduce the current behavior (if this is a bug)?
Hit the page or run the below code

#### Provide the test code and the tested page URL (if applicable)
Page Url: https://tribegrouptravel.com

```
import { Selector } from 'testcafe';

fixture`Getting Started`
.page('https://tribegrouptravel.com')
        
const skipTheLines = Selector('div > button').withText('Skip these tips');

test('Successful Login', async t => {
  // Test code
  await t
  .click(skipTheLines)
  .wait(3000);
     
      });
```

### Your Environment details:
 
* testcafe version: 1.6.1 
* node.js version:  v10.16.3      
* command-line arguments:  "testcafe chrome loginTest.js"
* browser name and version: Chrome: 78.0.3, Safari: 13.0.3
* platform and version:  Mac OS X 10.14.6
* other: There is a google api that runs in the development tool not sure if that is the cause

**Comment by monagarg10** [comment]
@AlexKamaev  Can you help me with this one.

**Comment by AlexKamaev** [comment]
You do not need to do anything special to run your tests under Mac OS X 10.14.6.
I checked your example and it works as expected.
Does the test work under other operation systems?
Do you run your tests in a corporate environment behind the proxy server?
