### ISSUE TITLE
APIv2: Implement native dialogs handling

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#451]

**Comment by AlexanderMoskovkin** [comment]
I'm working on this

**Comment by AlexanderMoskovkin** [comment]
There are different cases with native dialogs, so I'd like to discuss how we should process them. Here is my opinion (below are cases that we can meet in tests):

**1) Alert dialog appears on page load (before any command executing)**
(`page loaded` - `alert appeared` - `click command started` - `click command done`)
Alert is not a result of click action, so I suppose we should process it in the test in the following way:
```js
t.handleAlert().click(); // it's all ok
t.click().handleAlert(); // "unexpected alert" error
```

**2) Alert dialog appears after an action (it is the simplest case)**
(`page loaded` - `click command started` - `alert appeared` - `click command done`)
```js
t.click().handleAlert(); // ok
t.click();               // "unexpected alert" error
t.handleAlert().click(); // "was no expected alert" error
```

**3) Alert dialog appears between actions (when the first is finished but the second is not started)**
(`page loaded` - `click command 1 started` - `click command 1 finished` - `waiting for the next command` - `alert appeared` - `click command 2 started` - ...)
```js
t.click().handleAlert().click(); // ok
t.click().click().handleAlert(); // "unexpected alert" error
```

In my variant `.handleAlert` looks like a separate api command.
What do you think, is it all ok? @inikulin @helen-dikareva @AndreyBelym

**Comment by inikulin** [comment]
Looks legit.

**Comment by helen-dikareva** [comment]
I agree on all points.
And now we can take into account sequence of dialogs handlers (like this `t.click().handleAlert().handlePrompt()`) In previous version we didn't do it.

**Comment by AlexanderMoskovkin** [comment]
yep

**Comment by AndreyBelym** [comment]
Looks nice.
There is some questions though.

1) What if `alert` is raised after some action, but with a significant delay? (e.g. file uploading). Obvious solution is to use `wait` action here, so we should write like:
`t.click().wait().handleAlert()`
right?

1.a) What if delay between `click` and raising `alert` is variable, and `alert` may be raised both between `click` and `wait`, and during `wait`? 

2) What I should do if I don't care about order of different dialog types?

**Comment by inikulin** [comment]
`t.click().wait().handleAlert()`

No need for this. We either have next action or end of test. In both cases we will fail with unhandled alert.

**Comment by AlexanderMoskovkin** [comment]
1 - Nice question. I suppose we should ignore `wait` in this case. In other words `t.click().wait().handleAlert()` and `t.click().handleAlert().wait()` is the same for us. Otherwise it may be too complicated.
@inikulin do you mean the same?

**Comment by inikulin** [comment]
> 2) What I should do if I don't care about order of different dialog types?

Well, you should. It's like you don't care about ordering of actions

**Comment by inikulin** [comment]
> 1 - Nice question. I suppose we should ignore wait in this case. In other words t.click().wait().handleAlert() and t.click().handleAlert().wait() is the same for us. Otherwise it may be too complicated.

Why?? We should fail on `wait` with `handleAlert` callsite. You have unhandled dialog.

**Comment by AlexanderMoskovkin** [comment]
- `click command started` - `alert appeared` - `click command done`
```js
t.click().handleAlert().wait(2000); // ok
t.click().wait(2000).handleAlert(); // "unexpected alert" error
```

- `click command started` - `click command done` - `1 sec delay` - `alert appeared`
```js
t.click().handleAlert().wait(2000); // "no expected alert" error
t.click().wait(2000).handleAlert(); // ok
```

ok?

**Comment by AndreyBelym** [comment]
OK, I'll describe situation. It's exactly how it goes on ASPxDemos. Test page is file manager.
1) Test selects a file for upload, and clicks 'Upload button'.
2) File takes some time to upload.
3) Test tries to upload the same file again.
4) Duplicate file takes some time to upload.
3) Server checks the duplicate file's name, and rejects it because a file with the same name was already uploaded. Page should display `alert` message. 
4) Test performs clean-up by deleting the first file (which involves some clicks) 

What I should do in this case to handle `alert`?

**Comment by inikulin** [comment]
But, I think no. We've discussed previously that `wait` actions are observational actions. So, I guess we should make exception for them

**Comment by AlexanderMoskovkin** [comment]
> What I should do in this case to handle alert?

As I understand, it should be
`t.select().select().wait().handleAlert()`

**Comment by inikulin** [comment]
I guess we will wait for 10 seconds by default for the dialog to appear, like we have with action elements?

**Comment by AlexanderMoskovkin** [comment]
If we have `t.click().handleAlert().click()` - we are waiting for 10 seconds between clicks or until alert dialog is appeared. It's ok for me

But what the final decision for the `wait` action?
> We've discussed previously that wait actions are observational actions. So, I guess we should make exception for them

unfortunately I didn't get it, could you please describe it with an example (like I did above)?

**Comment by AndreyBelym** [comment]
Also, what's about allowing user to check handled dialog message?

**Comment by AlexanderMoskovkin** [comment]
> Also, what's about allowing user to check handled dialog message?

I had one of two requests for this since we've released the first TestCafe version. I suppose, we can implement this

**Comment by inikulin** [comment]
I suggest `t.handleAlert(string)` and `t.handlerAlert(regularExpression)` to check text.

**Comment by inikulin** [comment]
> we are waiting for 10 seconds between clicks or until alert dialog is appeared. It's ok for me

If 10 seconds exceeds after the first click and dialog doesn't appear - we fail, right?

**Comment by AlexanderMoskovkin** [comment]
yep

**Comment by inikulin** [comment]
Sounds good to me

**Comment by helen-dikareva** [comment]
Now we decided to give up ideas of:
1) check the order and number of dialogs
2) check the dialogs' text

We decided to introduce the concept that dialog is always the result of action.
In this case if you have a dialog appearing during page loading (before the first step was running) you should use `t.navigateTo()` as first step in test. The only way we can process dialogs.

Information about dialogs will included in action this way:
```
test('Click button', async t => {
    await t.click('#btn', {
        offsetX:        -3,
        dialogHandlers: {
            alert: true,
            confirm: true/false,
            prompt: inputValue/false,
            beforeUnload: true
        }
    });
});
```

All alerts and beforeUnload we will just close, for all confirms we will return true/false, for all prompts we return inputValue, or null (it's browser behavior for press on button Cancel).

Default options will look like:
```
 dialogHandlers: {
            alert: null,
            confirm: null,
            prompt: null,
            beforeUnload: null
        }
```
Did I miss anything?
PS: If we don't have `t.navigateTo()` as first action and dialog was raised during page loading should we raise error or just skip it?

**Comment by inikulin** [comment]
It should be:
```js
 dialogHandlers: {
            alert: true | false,
            confirm: { result: true | false }  | false ,
            prompt: { result: String | null } | false,
            beforeUnload: true | false
}
```

**Comment by inikulin** [comment]
And I guess it should be `handleDialogs` instead of `dialogHandlers`

**Comment by VasilyStrelyaev** [comment]
even `handledDialogs`

**Comment by VasilyStrelyaev** [comment]
I wonder if we could add a server-side `onHandled` that's called after the handling - purely for assertions
```js
handleDialogs: {
    alert: true | false,
    confirm: { result: true | false }  | false ,
    prompt: { result: String | null } | false,
    beforeUnload: true | false,
    onHandled: (type, text) => {}
}
```

**Comment by VasilyStrelyaev** [comment]
@DevExpress/testcafe so what about `onHandled` ?

**Comment by inikulin** [comment]
>  so what about onHandled ?

Let's not do this in MVP

**Comment by helen-dikareva** [comment]
So, now we have new idea. Let's discuss @DevExpress/testcafe 
We'll have overridable dialog handler for all dialog types, we can set it in any time in test.
E.g.:
```
test('Confirm', async t => {
    //set handler for dialogs appearing on page load
    await t
	.setConfirmDialogHandler(text => {
		if(text === 'confirm1')
			return true;
             ...
		return false;
	})
        .click('#button');
});
```
Should `setAlertDialogHandler` and `setBeforeUnloadDialogHandler` be without argument?
If dialog appears and we don't have handler for it we should raise error.
And we should have something like that for checking raised dialog:
`{type, text} = t.getLastDialogInfo()`

**Comment by AlexanderMoskovkin** [comment]
I suppose a `setDialogHandler` function should get a `ClientFunction` as an argument. 
And maybe `setDialogsHandler` functions should be synchronous?

**Comment by inikulin** [comment]
> Should setAlertDialogHandler and setBeforeUnloadDialogHandler be without argument?

It's should accept client function as well, because we need to check their text

> I suppose a setDialogHandler function should get a ClientFunction as an argument. 

We should have the same machinery as for selectors: if regular functions is passed - try to convert it to client function.

> And maybe setDialogsHandler functions should be synchronous?

How you will pass handler to client after page load then?

**Comment by VasilyStrelyaev** [comment]
> It's should accept client function as well, because we need to check their text

As far as I understand, the only way to check text is outside of the handler - via `t.getLastDialogInfo()`.
The handler is just to return the value to close the dialog with. Although it can depend on the text.

So, I can't imagine what a handler would do in `setAlertDialogHandler` and `setBeforeUnloadDialogHandler `

**Comment by inikulin** [comment]
I would like to not introduce `t.getLastDialogInfo()` if handler has unexpected text then you will throw from within handler.

**Comment by helen-dikareva** [comment]
How to check was expected dialog or not?
