### ISSUE TITLE
Do not show the 'Screen Recording' permission dialog for remote browsers

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#4512]
### What is your Test Scenario?
Use a remote browser (BrowserStack, Saucelabs) on macOS Catalina.

### What is the Current behavior?
A request for the 'Screen Recording' permission is shown if TestCafe is installed and used for the very first time. However, **it doesn't block the test session and can be ignored**.

### What is the Expected behavior?
The permission dialog is not shown.

#### Provide the test code and the tested page URL (if applicable)

 
Your website URL (or attach your complete example):

Your complete test code (or attach your test files)

```js

```
### Your Environment details:
 
* testcafe version:                   1.7.0
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          macOS 10.15
* other:

**Comment by weyert** [comment]
Yes, wondering if this is something the cloud browser testing provider needs to somehow disable? If even possible?

**Comment by Farfurix** [comment]
@weyert 

Hello,

Thank you for your interest in this issue. We will update this thread once we have any news.

**Comment by AndreyBelym** [comment]
This dialog appears only when TestCafe access macOS APIs that are necessary only for managing local browsers. We can avoid using these APIs for remote browsers. If you don't plan to use local browsers, you can just ignore the dialog or even deny the 'Screen Recording' permission. If you change your mind, you can always visit the 'Settings > Security & Privacy > Screen Recording' panel and grant the 'Screen Recording' permission to use TestCafe with local browsers.

**Comment by danielroe** [comment]
Another use case: MacOS browsers with GitHub Actions image. Tests fail as a result.

**Comment by weyert** [comment]
@danielroe "MacOS browsers with GitHub Actions image. Tests fail as a result." this sounds interessting. What does this mean? Do you have a GitHub Actions image with MacOS browsers?

**Comment by danielroe** [comment]
@wayert Apologies for the cryptic previous comment!

GitHub Actions base images (`macos-latest`, `ubuntu-latest`, `windows-latest`) include browsers. The Windows image, for example, currently includes:
 - Firefox 72.0 / Windows 10
 - Chrome 79.0.3945.117 / Windows 10
 - Internet Explorer 11.0 / Windows 10

It's possible to use these browsers to perform testcafe tests - using, for example, [this action](https://github.com/DevExpress/testcafe-action). However, Testcafe on MacOS complains with the following error:
```
TestCafe requires permission to record the screen. Open 'System Preferences > Security & Privacy > Privacy > Screen Recording' and check 'TestCafe Browser Tools' in the application list.

Press any key to retry.
ERROR UnableToAccessScreenRecordingAPIError: The find-window process cannot access the Screen Recording API.
    at runFindWindowBinary (/Users/runner/runners/2.163.1/work/app/app/node_modules/testcafe-browser-tools/src/api/find-window.js:29:19)
```

**Comment by weyert** [comment]
Wow cool, I didn't know that! 💃

**Comment by AndreyBelym** [comment]
@danielroe the original context of the issue is a bit different. TestCafe doesn't need the Screen Recording permission to control remote browsers so we can just avoid showing the permission dialog for remote browsers. Unfortunately, the situation is much worse for local browsers that TestCafe should start in macOS CI images.

MacOS 10.15 Cataline brought an update to the security system that makes TestCafe unable to even detect browser windows without obtaining the Screen Recording permission. Moreover, this permission can't be obtained programmatically without disabling the System Integrity Protection and rebooting the system. Due to this, TestCafe has serious challenges with starting and controlling browsers in macOS CI images that should be solved in the context of a different issue.

**Comment by artipsingh** [comment]
I have already given TestCafe access to record my screen and I have run automated tests successfully, however I am now working on a new project and I am now getting this message :

 TestCafe requires permission to record the screen. Open 'System Preferences > Security & Privacy > Privacy > Screen Recording' and check 'TestCafe Browser Tools' in the application list.

Has anyone experienced this before?

**Comment by liront2** [comment]
solved it.
Simply gave permission to the local testcafe app instead of the global.
