### ISSUE TITLE
Random error popping up

### ISSUE THREAD

**Issue by franciscolosardo** [DevExpress/testcafe#4513]
### What is your Test Scenario?

 I'm running testcafe with concurrency on a docker with chrome.
The way i run concurrency is by creating multiple instances of testcafe runners and each executes just one test file.
Randomly , the following message pops up, specially when running multiple concurrent tests at the same time.

TypeError: Cannot read property '0' of null

### What is the Current behavior?

 This error pops up at allure report and specs report :

TypeError: Cannot read property '0' of null
                
                Browser: Chrome 78.0.3904.108 / Linux 0.0
                Screenshot: /var/lib/jenkins/screenshots/test-E2ECreateProjectFromExample_Chrome_78.0.3904.108_Linux_0.0.png
                
                   52 |
                   53 |    /**
                   54 |     *  Waits for page to load
                   55 |     */
                   56 |    public async at(): Promise<void> {
                 > 57 |        await t.expect(Selector("[data-test-id='heading-api-title']").exists).ok(`Did not load Page Visual Editor`, {timeout: 300000,timeoutSeconds:30000});
                   58 |    }
                   59 |
                   60 |    /**
                   61 |     * Creates a resource with respective name and
                   62 |     * @param resourceName
                
                   at VisualDesignerPage.<anonymous> (/var/lib/jenkins/src/pageobjects/visual/VisualDesignerPage.ts:57:70)
                   at <anonymous> (/var/lib/jenkins/src/pageobjects/visual/VisualDesignerPage.ts:8:71)
                   at __awaiter (/var/lib/jenkins/src/pageobjects/visual/VisualDesignerPage.ts:4:12)
                   at VisualDesignerPage.at (/var/lib/jenkins/src/pageobjects/visual/VisualDesignerPage.ts:55:16)
                   at E2ECreateProjectFromExample.<anonymous> (/var/lib/jenkins/src/tests/e2e/E2ECreateProjectFromExample.ts:73:34)
                   at fulfilled (/var/lib/jenkins/src/tests/e2e/E2ECreateProjectFromExample.ts:5:58)

 
### Your Environment details:
 
* testcafe version: 1.6.1                   
* node.js version:    10.17.0                
* command-line arguments:  
* browser name and version: chrome --disable-background-timer-throttling --no-sandbox --disable-gpu -incognito --window-size=1200,1000 
* platform and version: Debian Latest         
* other:

**Comment by AlexKamaev** [comment]
It appears that the information you provided is insufficient for us to determine the exact cause of the issue.
Does the issue occur only when the Docker is used? Can you reproduce it using the official TestCafe docker image? Can you reproduce it locally? Does the issue persist if you enable the `--skip-js-errors` flags?

Please share an example which will allows us to reproduce and research the issue in detail.

**Comment by franciscolosardo** [comment]
1 - Yes it happens only when used in CI, from docker build or running on saucelabs concurrently
2 - I haven't found an actual TestCafe image which supports Xvfb usage with Chrome for visual recording of videos, so we went ahead with a debian container of our own.
3 - No, we could not reproduce locally, though when running locally it's almost imposible to run so many concurrent tests due to performance.
4 - This issue persists with --skip-js-errors because we use this flag on each test.

I'll check with my superiors if a test can be shared, though it seems impossible due to accounts credentials we need to share with you guys.

**Comment by miherlosev** [comment]
Hi @franciscolosardo 

Your environment is very complex and we cannot find the cause of the problem without a reproducible example. Feel free to reopen this issue if you can provide such example.
