### ISSUE TITLE
skipJsErrors - log entire console output

### ISSUE THREAD

**Issue by dlangerenken** [DevExpress/testcafe#4520]
We have skipJsErrors set to false in our testing environment, mainly to prevent anyone from committing potentially erroneous code. Sometimes in our CI we see the build fail due to JS errors. However, the actual error is not shown:

```
JavaScript error details:
undefined:
       No stack trace available
```

I assume this is due to the framework we're using who somehow wraps the error message [0].

Since it's hard to reproduce I thought it would be easier to ask for a new feature: If a JS Error occurs on my page and the test fails, I'd like to see the entire console.log of my page (or have a way to add more information from my test). I know the error is logged, it's just not in the form of a console.error message. By having access to the full log, I can see what is going on without getting my "undefined - No stack trace available" error.

#### Additional Context
[0] I'm using Oracle JET 

Trying to build a reproducible example, but so far I cannot get it to even fail:
```
test.page('https://jsfiddle.net/d389vLz4/7/')('click button in jsfiddle', async (t) => {
  const selector = Selector('.oj-button');
  await t
    .switchToIframe(Selector('[name=result]'))
    .wait(1000)
    .expect(selector.hasClass('oj-enabled'))
    .ok()
    .switchToMainWindow()
    .wait(2000);
});
```

**Comment by miherlosev** [comment]
Hi @dlangerenken 

It's a TestCafe problem. We cannot calculate the error message and stack trace in the [_raiseUncaughtJsErrorEvent](https://github.com/DevExpress/testcafe-hammerhead/blob/f68857f899c538b3ee054be75a1166fe5b1dcf1e/src/client/sandbox/node/window.ts#L142) function.

Could you please help us debug the problematic case? It is necessary to log the `event` properties that are passed to the [_raiseUncaughtJsErrorEvent](https://github.com/DevExpress/testcafe-hammerhead/blob/f68857f899c538b3ee054be75a1166fe5b1dcf1e/src/client/sandbox/node/window.ts#L142) function.
