### ISSUE TITLE
Resolve Typescript dependencies properly

### ISSUE THREAD

**Issue by kristfal** [DevExpress/testcafe#4526]
### What is your Test Scenario?
Our repository is a monorepo using yarn workspaces and lerna. Our setup is:

`packages/app-web`
`packages/shared` 

Where `app-web` is where our tests lives. `app-web` consumes javascript and typescript modules from `shared`. Both repos are currently being converted to typescript. As such, we have a mix of `.js` and `.ts` files in both packages.

Webpack is set up to transpile the dependencies and all is well with development and production builds. Testcafe is set up to use the `tsconfig.json` in `app-web`.

What works with testcafe:

Any .ts file in `app-web` is handled just fine

What doesn't work:

Any .ts file in the `shared` package is not resolved properly when running a command such as `testcafe safari` unless the file extension is set specifically in the import.

Example:

1) `app-web/index.js` declares `import shared/foo` where `foo` is a `js` file -> Works
2) `app-web/index.js` declares `import shared/foo` where `foo` is a `ts` file -> Does not work 

Error printed:

```
ERROR Cannot prepare tests due to an error.

Error: Cannot find module 'shared/foo'
```

3) `app-web/index.js` declares `import shared/foo.ts` where `foo` is a `ts` file -> Works

### What are you suggesting?

Testcafe should allow us to customize file extensions to be resolved so `.ts` files in un-compiled dependencies are resolved properly.

**Comment by alexey-lin** [comment]
Hi @kristfal,

Thank you for your suggestion, we will think about it. Meanwhile, you can convert the tests to typescript. If the tests were in .ts files, testcafe would resolve both .ts and .js dependencies properly.
