### ISSUE TITLE
How can I simultaneously press the button and check that the text appears?

### ISSUE THREAD

**Issue by abnorman23** [DevExpress/testcafe#4527]
When I press the button - for one millisecond in the DOM appears Text.
```
await t
  .click(button)
  .expect(text.exists).ok('text is here')
```
But the text disappears so quickly that about once in five tests falls.

I'll try:
```
async function click() {  
  await t.click(button)  
}

await t
.expect(click() && text.exists).ok('when i click button text is here'
, { allowUnawaitedPromise: true })
```
It's works better but not always.

Testcafe does not have time to do expect.
How can I simultaneously press the button and check that the text appears?
What is the best way?

**Comment by alexey-lin** [comment]
Hi @abnorman23,

I believe that using the [quarantine mode](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#quarantine-mode) is your best option. The element lifetime of one millisecond is too short for TestCafe to be able to stably detect its appearance.
