### ISSUE TITLE
TestCafe v1.7.0 specific issue  - 'Error: ESPIPE: invalid seek, read' error thrown 

### ISSUE THREAD

**Issue by sijosyn** [DevExpress/testcafe#4528]
### What is your Test Scenario?

With Node v8.11.1, I get '**Error: ESPIPE: invalid seek, read**' error when running TestCafe example test.  

With Node v10.16.3 test runs fine. Seems like a regression in TestCafe v1.7.0. See screenshot.
 
### What is the Current behavior?

With Node v8.11.1, I get 'Error: ESPIPE: invalid seek, read' error when running TestCafe example test.

### What is the Expected behavior?

With Node v10.16.3 test runs fine.

### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from 'testcafe';

fixture `Getting Started`
	.page `http://devexpress.github.io/testcafe/example`;

test('My first test', async t => {
	// Test code
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

see screenshot
</details>

<details>
<summary>Screenshots:</summary>

<img width="407" alt="Screen Shot 2019-11-27 at 11 22 44 AM" src="https://user-images.githubusercontent.com/29459281/69741398-fbcabd80-1108-11ea-8307-6b83498e4e32.png">

</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                    v1.7.0
* node.js version:                     v8.11.1 . Note: Issue doesn't occur with v10.16.3
* command-line arguments:   testcafe chrome test.js
* browser name and version:  Chrome 78
* platform and version:           macOS 10.14.6
* other:

**Comment by alexey-lin** [comment]
Hi @sijosyn,

I reproduced the problem. Thank you for bringing this issue to our attention. We will look into it.

**Comment by jiteshsojitra** [comment]
Thanks @alexey-lin for accepting the issue, https://github.com/DevExpress/testcafe/issues/4530 looks same?

**Comment by alexey-lin** [comment]
@jiteshsojitra These issues seem to be different because they are reproducible under different OS's and in different node.js versions. Still, they might have a common cause, of course.

**Comment by AndreyBelym** [comment]
This issue is caused by a bug in Node.js: https://github.com/nodejs/node/issues/19240. You can update your Node.js to the latest 8.x version (8.16.1) or downgrade to a version that doesn't have this bug (8.9.4).

Please note, that we will discontinue supporting Node.js 8.x in January 2020 due to the Node.js end-of-life schedule: https://nodejs.org/en/about/releases/
