### ISSUE TITLE
The status bar may stay in a wait status in the debug mode

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe#4529]
### What is your Test Scenario?
Stop test on a breakpoint after successful delay for an element to appear.
 
### What is the Current behavior?
The status bar stays green-colored with a progress bar
 
### What is the Expected behavior?
The status bar appearance in the debugging state shouldn't depend on a previous action
 
### What is your web application and your TestCafe test code?
Your website URL (or attach your complete example):
https://interactive-examples.mdn.mozilla.net/pages/css/z-index.html

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from 'testcafe';

fixture`Fixture 1`
    .page`https://interactive-examples.mdn.mozilla.net/pages/css/z-index.html`;

test('Test 1', async t => {
    await t
        .click(Selector('.example-choice').withText('z-index: 5'))
        .click('.position2')
        .debug()
        .expect(Selector('#input').exists).ok({timeout: 5000});
});
```
</details>

<details>
<summary>Screenshots:</summary>
Old status bar:

![image](https://user-images.githubusercontent.com/24777868/69742234-79182180-114d-11ea-9cdf-f085849b2444.png)

Redesigned status bar:

![image](https://user-images.githubusercontent.com/24777868/69742446-d8763180-114d-11ea-9403-d9c0b4b3c822.png)

</details>

**Comment by miherlosev** [comment]
I encountered another issue with the `testcafe@1.10.1`.

![image](https://user-images.githubusercontent.com/4133518/104886562-06828a80-597b-11eb-9c65-7864c5bad7e4.png)

The problematic subsystem is the `testcafe-hammerhead`.
