### ISSUE TITLE
Ajax submission not working 

### ISSUE THREAD

**Issue by RemigiusL** [DevExpress/testcafe#4535]
### What is your web application and your TestCafe test code?

- https://september.weldtest.no/user/create
Credentials, 
remi@processdrive.com
Pd123456!

Your website URL (or attach your complete example):
![image](https://user-images.githubusercontent.com/54391573/69898819-3be9a480-1384-11ea-8433-0d08b235d14d.png)

<details>
<summary>Get it from below link,
 https://www.npmjs.com/package/keyword_driven</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:
![image](https://user-images.githubusercontent.com/54391573/69898862-b61a2900-1384-11ea-8d0d-ee33f1fb9500.png)
</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website with my given access ...(https://september.weldtest.no/user/create)
3.  Create a new user and submit by using testcafe..
4. See the error...
 
### Your Environment details:
 
* testcafe version:                  
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by aleks-pro** [comment]
Hello @RemigiusL ,

We would love to assist you and diagnose this issue. However, our policy prevents us from accessing internal resources without prior written approval from a site owner. If you want us to further research the problem directly on your side, please ask the website owner to send us (mailto:support@devexpress.com) a written confirmation. It must permit DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes.
