### ISSUE TITLE
TypeError: testcafe_1.default is not a function

### ISSUE THREAD

**Issue by guiyomh** [DevExpress/testcafe#4536]
### What is the Current behavior?
I'm trying to create my own command `run-e2e.ts`. 
I have this error : 
> TypeError: testcafe_1.default is not a function
 
### What is the Expected behavior?
Normally, I shouldn't have any exceptions. And I should see my message `after`
 
### What is your web application and your TestCafe test code?

<details>
<summary>My `run-e2e.ts`:</summary>

```js
import * as chalk from 'chalk';
import createTestCafe from 'testcafe';

async function main(hostname: string, port1: number, port2: number) {
	try {
		console.log('before');
		const testcafe = await createTestCafe(hostname, port1, port2);
		console.log('after');
	} catch (err) {
		console.log(`${chalk.red(err)}`);
	}
}
main('localhost', 1556, 1557);
```
</details>
<details>
<summary>the output: </summary>

![image](https://user-images.githubusercontent.com/363162/69906984-973f8500-13cc-11ea-98e0-b5cf4f020eeb.png)

</details>

### Steps to Reproduce:

1. Create the file `run-e2e.js` 
3. Add testcafe and chalk `yarn add testcafe chalk`
4. And run `ts-node src/run-e2e.ts`
 
### Your Environment details:
 
* testcafe version:                   1.7.0
* node.js version:                    12.13.1
* command-line arguments:  ts-node src/run-e2e.ts
* platform and version:          macOS 10.14

**Comment by guiyomh** [comment]
I found a work around: 
```js 
import * as createTestCafe from 'testcafe';
// ...
const testcafe = await (createTestCafe as any)('localhost', 1337, 1338);
```

**Comment by aleks-pro** [comment]
To solve the issue, please enable the `esModuleInterop` option in your `tsconfig.json` file:
```json
{
  "compilerOptions": {
    "esModuleInterop": true
  }
}
```
Refer to [this thread](https://stackoverflow.com/questions/56238356/understanding-esmoduleinterop-in-tsconfig-file) for more info about this option.
