### ISSUE TITLE
Session storage values were not removed

### ISSUE THREAD

**Issue by robert-isaev** [DevExpress/testcafe#4546]
### What is your Test Scenario?
Login then logout. 
When I do it manually browser cleans SessionStorage values but when I do the same thing in TestCafe then test fails.

### What is your web application and your TestCafe test code?
I have prepared a sample:

https://github.com/robert-isaev/testcafe-session-storage

### Steps to Reproduce:

1. git pull https://github.com/robert-isaev/testcafe-session-storage
2. yarn && yarn start
3. test will fail
 
### Your Environment details:
 
* testcafe version:                    1.7.0
* node.js version:                     8.16.2
* browser name and version:  Chrome Version 78.0.3904.108
* platform and version:           MacOS Mojave

**Comment by Dmitry-Ostashev** [comment]
Thank you for your report.

We would love to research this issue. As I can see from your test, it's necessary to log into the site. Our policy prevents us from accessing internal resources without prior written approval from a site owner. If you want us to further research the problem directly on your side, please ask the website owner to send us (mailto:support@devexpress.com) a written confirmation. It must permit the DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes.

**Comment by robert-isaev** [comment]
Hello! First of all thank you for a great tool and support! 

Unfortunately we can not provide access to internal resources of our application but I could provide some debugging information in a private chat. 
Please ping me on Telegram (@zlobert) for further investigation.

**Comment by AlexKamaev** [comment]
@robert-isaev You can send the additional information at support@devexpress.com
We understand that you cannot share your project with us. In this case we would really appreciate it if you prepare a sample project that demonstrates the issue.
