### ISSUE TITLE
Edge gives wrong key strings for arrows after keydown

### ISSUE THREAD

**Issue by RandomNonameDude** [DevExpress/testcafe#4549]
### What is your Test Scenario?

To test something that handles `KeyboardEvent` and arrow keys specifically.
 
### What is the Current behavior?

In Testcafe and in Edge, `KeyboardEvent.key` is incorrect string for arrow up and arrow down. According to the [documenation](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values), it should be `ArrowUp` and `ArrowDown`, respectively, but in Testcafe, it is `Up` and `Down`, respectively.

Therefore, test fails on Edge although the behavior itself works as expected.
 
### What is the Expected behavior?

`KeyboardEvent.key` should be consistent across browsers, Testcafe on Edge should give same values for the property as in the other browsers.
 
### What is your web application and your TestCafe test code?

Testable page: https://angular-7sqech.stackblitz.io

Here's the app so you can see the code to be tested if you need: https://stackblitz.com/edit/angular-7sqech?file=src/app/button-overview-example.ts

Test code:

````
fixture`edge keydown bug`
    .page(`https://angular-7sqech.stackblitz.io`);
test('should change value when arrow up is pressed', async () => {
    const input = Selector('#tentacles');
    await t
        .click(input)
        .pressKey('up');
    const {log} = await t.getBrowserConsoleMessages();
    for (const l of log) {
        console.log(l);
    }
    await t.expect(input.getAttribute('ng-reflect-model')).eql('100');
});
test('should change value when arrow down is pressed', async () => {
    const input = Selector('#tentacles');
    await t
        .click(input)
        .pressKey('down');
    const {log} = await t.getBrowserConsoleMessages();
    for (const l of log) {
        console.log(l);
    }
    await t.expect(input.getAttribute('ng-reflect-model')).eql('25');
});
````

### Steps to Reproduce:

 Try running the tests above. They fail on Edge with the following result:
```
AssertionError: expected '50' to deeply equal '100'
AssertionError: expected '50' to deeply equal '25'
````
They pass on other browsers
 
### Your Environment details:
 
* testcafe version:                   1.2.1
* node.js version:                    10.16.0
* command-line arguments:  `testcafe edge [test_file]`
* browser name and version: Edge
* platform and version:          Win10
* other:

**Comment by miherlosev** [comment]
Hi @RandomNonameDude 

Thank you for the provided example. I've reproduced the problem.

**Comment by miherlosev** [comment]
Hi @RandomNonameDude,

The [tested page](https://angular-7sqech.stackblitz.io/) is not opened in the browser for 2 min. Could your please share the project with the tested page?

**Comment by RandomNonameDude** [comment]
Hi @miherlosev 

Stackblitz sometimes does this, it's pretty annoying

Anyway, try this link: https://stackblitz.com/edit/angular-7sqech

**Comment by wentwrong** [comment]
Thanks for the quick response. 

I slightly modified the code of your test (just used your new link and added switching to the iframe with the application preview), and it passed without any errors:

```js
import { Selector } from 'testcafe';

fixture `edge keydown bug`
    .page(`https://stackblitz.com/edit/angular-7sqech`)
    .beforeEach(async t => {
        await t.switchToIframe(Selector('iframe').withAttribute('name', 'previewFrame'));
    });

test('should change value when arrow up is pressed', async t => {
    const input = Selector('#tentacles');
    await t
        .click(input)
        .pressKey('up');
    const {log} = await t.getBrowserConsoleMessages();
    for (const l of log) {
        console.log(l);
    }
    await t.expect(input.getAttribute('ng-reflect-model')).eql('100');
});

test('should change value when arrow down is pressed', async t => {
    const input = Selector('#tentacles');
    await t
        .click(input)
        .pressKey('down');
    const {log} = await t.getBrowserConsoleMessages();
    for (const l of log) {
        console.log(l);
    }
    await t.expect(input.getAttribute('ng-reflect-model')).eql('25');
});
```

Also, I tried it in a local application, and it passed too:

> Running tests in:
> - Microsoft Edge 88.0.705.68 / Windows 10
>
> edge keydown bug
> √ should change value when arrow up is pressed
> √ should change value when arrow down is pressed
>
>
> 2 passed (30s)

Can you confirm that the issue is no longer reproducible in the latest versions of TestCafe (`v1.11.0`) and the Edge browser?
