### ISSUE TITLE
Testcafe 1.7.0 run in docker against saucelabs hangs

### ISSUE THREAD

**Issue by vire** [DevExpress/testcafe#4551]
### What is your Test Scenario?

I ran the example test from https://github.com/DevExpress/testcafe/tree/master/examples/basic

### What is the Current behavior?

With `testcafe@1.7.0` run via `testcafe-browser-provider-saucelabs@1.8.0` against `saucelabs:MicrosoftEdge@15.15063:Windows 10` the test hangs for XX minutes
 
![image](https://user-images.githubusercontent.com/4021908/70252022-ef85d680-1780-11ea-9add-04f189bc5ea4.png)

### What is the Expected behavior?
As of `testcafe@1.6.1`  run via `testcafe-browser-provider-saucelabs@1.8.0` against `saucelabs:MicrosoftEdge@15.15063:Windows 10` the test will pass/fail in reasonable time

![image](https://user-images.githubusercontent.com/4021908/70251945-c8c7a000-1780-11ea-96fb-c5cd8bfd149d.png)

### Steps to Reproduce:

1. `git clone git@github.com:DevExpress/testcafe.git`
1. `cd testcafe/examples/basic`
1. start standard `node:dubnium  docker container, pass saucelabs credential
```
docker run -it --rm -v /absolute/path/to/testcafe/examples/basic/:/usr/src/app -e SAUCE_USERNAME=$SAUCE_USERNAME -e SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY node:dubnium /bin/sh
```
1. `yarn testcafe "saucelabs:chrome" test.js` - everything OK
1. `yarn testcafe "saucelabs:MicrosoftEdge@15.15063:Windows 10" test.js` - test fails but hangs
1. downgrade testcafe
```
yarn upgrade testcafe@1.6.1
```
1. `yarn testcafe "saucelabs:MicrosoftEdge@15.15063:Windows 10" test.js` - test fails but error appears as expected

 
### Your Environment details:
 
* testcafe version:                   1.7.0
* node.js version:                    v10.17.0
* command-line arguments:  NONE
* browser name and version: saucelabs
* platform and version:          PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
* other:                                   testcafe-browser-provider-saucelabs@1.8.0

**Comment by AlexKamaev** [comment]
The issue looks similar to https://github.com/DevExpress/testcafe/issues/4530
I'll close it as a duplicate.
