### ISSUE TITLE
Specify a range of ports on which testcafe can be run

### ISSUE THREAD

**Issue by gaurav517** [DevExpress/testcafe#4552]
### What is your Test Scenario?
Only few ports on our CI agent can be accessed from remote browsers.

### What are you suggesting?
Given a range of ports in testcafe cli, testcafe chooses one of available ports in that range.

### What alternatives have you considered?
I have considered using testcafe-browser-provider-selenium to run tests on selenium grid, but even in that case, remote browsers need to connect to CI agent on a port where testcafe is running.

### Additional context
If its going to take time on your side, given some guideline, I might be able to help add this feature. Its critical for us because we are not able to run tests in CI otherwise.

**Comment by eroetman** [comment]
Are you using remote testing? If so, maybe this will help you. We have set up remote testing with this configuration to run on port 8001. The configuration was created from the example given here: https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/browserconnection.html

```
const createRemoteTestCafe = require('gherkin-testcafe');
const os = require('os');
let remotetestcafe = null;
let remoteRunner = null;

createRemoteTestCafe(os.hostname() + '.mydomain', 8001, 8002)
    .then(tc => {
        remotetestcafe = tc;
        remoteRunner = remotetestcafe.createRunner();
        return remotetestcafe.createBrowserConnection();
    })
    .then(remoteConnection => {

        // Outputs remoteConnection.url so that it can be visited from the remote browser.
        console.log(remoteConnection.url);

        remoteConnection.once('ready', () => {
            remoteRunner
                .src(['testcafe/**/*.ts', 'testcafe/features/**/*.feature'])
                .browsers(remoteConnection)
                .run()
                .then(failedCount => {
                    console.log(failedCount);
                    testcafe.close();
                })
                .catch(error => {
                    console.log('Test failed.');
                    remotetestcafe.close();
                });
        });
    });
```

Note: The URL used for testing that Testcafé gives can be used without the random part.
Example: Full URL is http://hostname.mydomain:8001/browser/connect/qvl8aWB but the first part 
http://hostname.mydomain:8001/browser/connect/ is enough to start the test on a remote browser, even in a different domain.
Off course we have port 8001 open on the machine where Testcafé is running.
