### ISSUE TITLE
Clicking on button in shadow Dom doesn't work

### ISSUE THREAD

**Issue by saritha11** [DevExpress/testcafe#4556]
### What is your Test Scenario?
Click a button to add a new lane to kanban board
 
### What is the Current behavior?
It's clicking but OnClick action is not  triggered. There's a blue/green border around the button
 
### What is the Expected behavior?
Once the button is clicked it's supposed to open a form
 
### What is your web application and your TestCafe test code?
I cannot provide that url since it's production instance.

```
Code snippet to click:

 await t
	.expect(shadowElementSelector('designer >>> layout > div>div>board>>>div > main >lane:nth-child(4)>>> div>div>lane-header-empty >>> button-iconic >>> button').visible).ok()
    .click(shadowElementSelector('designer >>> layout > div>div>board>>>div > main >lane:nth-child(4)>>> div>div>lane-header-empty >>> button-iconic >>> button'))
    .wait(2000);

This is how I got my selector:

export const shadowElementSelector = Selector((selector, element = document, separator = '>>>') => {
  
  const segments = selector.split(separator);
 
    for (const segment of segments) {
      element = element.querySelector(segment);

      if (!element) {
        return null;
      }

      if (!!element.shadowRoot) {
        element = element.shadowRoot;
      }
    }
 
```
</details>

**Comment by AlexKamaev** [comment]
If you cannot provide us with url, please prepare a sample project that demonstrates the issue.
