### ISSUE TITLE
Allow to switch to an invisible iframe

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#4558]
Reasons:
1) some sites use invisible iframes to perform some util logic (for example see [a Studio issue](https://github.com/DevExpress/testcafe-studio/issues/2881))
2) we have actions that don't check element's visiblity before execution (`pressKey, navigateTo` etc.)
3) we have even one action with selector that doesn't check element's visibility - `setFilesToUpload`
4) users use a hack to execute such switching, they assign `1px*1px` size to an invisible iframe. So there is only 1px but our behavior is absolutely different in this case.

Test should fail during action execution for this iframe if the required element is invisible.

**Comment by Dmitry-Ostashev** [comment]
https://supportcenter.devexpress.com/internal/ticket/details/T1046549
