### ISSUE TITLE
Test function is not working as expected

### ISSUE THREAD

**Issue by zhkostadinov** [DevExpress/testcafe#4560]
Hi team. First thing, you are doing a great job.  I thin, I found an issue in the execution phase. 
The flow is the next: 
```js
async function login(username, password) {
        await t        
        .typeText('#username', username)
        .typeText('#password', password)
        .click('button'`);
    };


test("User should login", async t => {
    login("username", "password");

    await t.
          expect("true").eql("true");
}) ;
```

This is working fine, but if we use an anonymous function instead of `t` , the changes are not applied.  If we add the second function: 
```js
async function loginTest() {
        await t        
        .click('button'`);
    };
```
and then, we perform the test as: 
```js
test("User should login", async () => {
    login("username", "password");
    loginTest(); 
}) ;
```
The test is marked as pass, no mather what changes you've made.

**Comment by devmondo** [comment]
maybe because you are missing `await` ?
```js
test("User should login", async () => {
/* --> */ await login("username", "password"); 
/* --> */await loginTest();
}) ;
```

**Comment by zhkostadinov** [comment]
I have that `await` in the helpers, and should not be the problem. 
Will give a try. thanks.

**Comment by zhkostadinov** [comment]
Thanks @devmondo . Your approach is working.
