### ISSUE TITLE
Testcafe Studio: Error NJS-069 while trying to start a test using oracledb

### ISSUE THREAD

**Issue by albertorizzo** [DevExpress/testcafe#4561]
### What is your Test Scenario?

 I would like to execute a query connecting to local Oracle database.
### What is the Current behavior?

 I can't use Testcafe Studio for all my test because of this error:

Error: Cannot prepare tests due to an error.
_Error: NJS-069: node-oracledb-4.1.0 requires Node.js 8.16 or later_

Testing in command line with Testcafe 1.7.0 and oracledb works correctly
### What is the Expected behavior?

 Start the test using oracledb package. 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
import { t } from 'testcafe';
    import {Selector} from 'testcafe';
    import {Role} from 'testcafe';
    const fs = require('fs');
    const path = require("path");
    const fetch = require("node-fetch");

const oracledb = require('oracledb');
oracledb.outFormat = oracledb.OBJECT;

fixture `Test oracle`
        .page `https://google.com`
        .beforeEach(t => t.resizeWindow(1440, 900))

test(`Generic`, async t => {await t.setNativeDialogHandler(() => true).useRole(testUser); await Generic();})
//generic is a function which contain connection, execute query and close connection steps.
 
```
</details>

<details>
<summary>Screenshots:</summary>

```
https://user-images.githubusercontent.com/35951020/70513765-89a79f00-1b32-11ea-83e0-6ee2162d0a88.PNG

```
</details>

### Steps to Reproduce:

1. install oracledb from npm 
2. run test from testcafe Studio
3. See the error NJS-069
 
### Your Environment details:
 
* testcafe studio version: 1.2.1                  
* node.js version: 12.11.1                     
* browser name and version:  every browser
* platform and version: Microsoft Windows 7

**Comment by Farfurix** [comment]
@albertorizzo 

Hello,

We will fix it in one of our next TestCafe Studio releases. However, I cannot give you any estimate at the moment.
