### ISSUE TITLE
Undocumented fix to a double mouse click issue 

### ISSUE THREAD

**Issue by Zebirdman** [DevExpress/testcafe#4564]
#### Documentation lacking timestamp option for mouse click

So we have been having issues with certain click actions with drop down menu's as there is actually a double click that will close the drop down before the next action can select an option. I can see here https://github.com/DevExpress/testcafe/issues/3645 that there was an issue raised and a fix implemented to add a timestamp parameter to the click options.

Only thing is that this is not documented or explained on the issue itself as to how this fixes the issue. We are using a paid subscription for testcafe studio and the option does not exist in the latest version either. It would be great if this was documented and maybe added into testcafe studio at some point.

**Comment by Dmitry-Ostashev** [comment]
[Timestamp](https://developer.mozilla.org/en-US/docs/Web/API/Event/timeStamp)  is a property of the Event interface and is not related to Click Action Options.

We fixed the https://github.com/DevExpress/testcafe/issues/3645 issue in TestCafe v1.2.0 and the latest TestCafe Studio version contains this fix.

If you faced a similar issue in TestCafe Studio, please describe the problem in greater detail in the [DevExpress Support Center](https://www.devexpress.com/ask).
