### ISSUE TITLE
Testcafe hides/swallows half of my `console.log` when using `electron`

### ISSUE THREAD

**Issue by Raynos** [DevExpress/testcafe#4565]
### What is your Test Scenario?

I am using `testcafe` to write tests for both my website and my `electron` desktop application. In the website I can debug any issues I have by adding `console.log` to my implementation and opening chrome devtools.

In my `electron` desktop application; only half of my `console.log` show up; `electron` has two processes, the `main` and the `renderer` process, any `console.log` in the `main` process goes to `STDOUT` ; any `console.log` in the `renderer` process goes to the chrome devtools. I can see my logs in chrome devtools but not `STDOUT`
 
### What is the Current behavior?

I can only see half of my `console.log` in `electron` apps.
 
### What is the Expected behavior?

I expect to see all of my `console.log` in `electron` apps.
 
### What is your web application and your TestCafe test code?

Sharing the application and a test case is more challenging; however I did track down the code that causes the bug.

I opened a PR to make logs available ( https://github.com/DevExpress/testcafe-browser-provider-electron/pull/53 ).

The implementation of `testcafe-browser-provider-electron` just hides all stdout from the electron `main` process by setting `stdio: 'ignore'` when spawning the `electron` child process.

### Your Environment details:
 
* testcafe version:                   1.7.0
* node.js version:                    10.15.3
* command-line arguments:  `testcafe tests/testcafe/*.ts` 
* browser name and version: electron
* platform and version:          Linux

**Comment by Dmitry-Ostashev** [comment]
Thank you for report and PR. We will discuss it.

**Comment by AndreyBelym** [comment]
Closed by https://github.com/DevExpress/testcafe-browser-provider-electron/commit/664847fc4ff228a07cc8339e4f69a8e807fb2be1.
