### ISSUE TITLE
Add CLI option to provide config file path

### ISSUE THREAD

**Issue by DamianOsipiuk** [DevExpress/testcafe#4566]
## What is your Test Scenario?

I would like to simplify `npm scripts` by extracting testcafe configuration to a config file.
Problem is that I would like to have a different configuration for local runs, CI runs, etc.
Overriding options from CLI is cumbersome.

### What are you suggesting?

Adding a CLI option with a config file path would solve the issue since I will be able to create multiple configurations.
Something like `--config-path`, similar to `--ts-config-path`?

### What alternatives have you considered?

N/A

### Additional context

N/A

**Comment by miherlosev** [comment]
Hi @DamianOsipiuk 

Hi @DamianOsipiuk
We plan to add this functionality. Track the [https://github.com/DevExpress/testcafe/issues/3428](https://github.com/DevExpress/testcafe/issues/3428) issue to informed about our progress.
