### ISSUE TITLE
Firefox Android tests not executing correctly

### ISSUE THREAD

**Issue by nikgustafson** [DevExpress/testcafe#4567]
### What is your Test Scenario?
I'd like to run tests on a physical android device using Firefox
 
### What is the Current behavior?
With Firefox/Android I am seeing some strange behavior. With TestCafe 1.7.0 the test will start, and look like its moving down the page to click an element, but then nothing happens and it hangs. With TestCafe 1.4.3 I was seeing similar behavior, but instead of hanging, the test would fail with "1) Uncaught object "[object Object]" was thrown. Throw Error instead.". The test runs correctly with Chrome/Android, as well as Chrome and Firefox on my computer. When the test hangs, it will sit there "running" until I cancel it in the command line.
 
### What is the Expected behavior?
I would expect Firefox/Android to run the test correctly like it does with other browsers. 
 
### What is your web application and your TestCafe test code?

 I was able to recreate it using code that tests a public site. 
Your website URL (or attach your complete example): https://www.wikipedia.org/

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector, ClientFunction } from "testcafe"

const getLocation = ClientFunction(() => document.location.href)

fixture`Mobile Testing Tests`
    .page('https://www.wikipedia.org/')

    test('Click Wikipedia Link', async t => {
        let link = Selector('a').withText('Wikispecies')
        await t.click(link)
        await t.expect(getLocation()).contains('species')
})
```
</details>

### Steps to Reproduce:

Execute test in above code on an android device using Firefox
 
### Your Environment details:
 
* testcafe version: 1.7.0
* node.js version: 12.13.0
* command-line arguments: yarn testcafe remote tests/ -t 'Click Wikipedia Link'
* browser name and version: Firefox 68.0
* platform and version:  Android 10 (Pixel 3a)

**Comment by Dmitry-Ostashev** [comment]
Thank you for your report. I was able to reproduce this issue. We will research it and notify you as soon as we have any result.

**Comment by rtarnaud** [comment]
Any update on this one. It is a tool-breaking bug for that particular platform.

**Comment by AlexSkorkin** [comment]
Once we get any results, we will post them here.
