### ISSUE TITLE
Static pendingTestRunUrl

### ISSUE THREAD

**Issue by dmytropanontko** [DevExpress/testcafe#4568]
### What are you suggesting?

I have a trouble with performance in my tests. Process all tasks take 15min. I noticed that the main problem is `pendingTestRunUrl`. Every test makes new  `pendingTestRunUrl` instead redirect to the main page.
### What alternatives have you considered?

Add an additional parameter to run command which makes static url. 

### Additional context

Thanks for attention :relieved:

**Comment by miherlosev** [comment]
Hi @dmytropanontko 

Could you please create a simple example illustrating this behavior?
