### ISSUE TITLE
Allow user to specify URL used by Role instance

### ISSUE THREAD

**Issue by Joao-S-Martins** [DevExpress/testcafe#4569]
It would be helpful if I could set the `url` property on a role instance to the URL that I want it to reload to instead of the URL that it was redirected to on log-in. If the team agrees, I'd be interested in delivering this change and supporting tests and documents myself.

### What is your Test Scenario?
- Assume a log-in flow like `example.com/redirect` -> `example.com/other-redirect` -> `example.com/welcome`.
- Create a role instance, `role`.
- Set `role.url` to `example.com/welcome`.
- `useRole(role)` the first time and it'll take you through the process.
- `useRole(role)` every time afterwards and reload directly to `example.com/welcome`.

### What are you suggesting?
I suggest changing `preserveUrl ? this.role.url : this.url` to `this.role.url || this.url` at https://github.com/DevExpress/testcafe/blob/7abae2c9b146f6163df45fb3e3105663639c7d95/src/test-run/bookmark.js#L105.

### What alternatives have you considered?
I have gotten around the current functionality with a utility function that looks like this:
```
const overrideRoleUrl = (role, url) => {
  let origFn = role.initialize;
  role.initialize = async function () {
    await origFn.apply(this, arguments);
    this.url = url;
    this.opts = { preserveUrl: true };
  }.bind(role);
  return role;
}
```
Then I can `let role = overrideRoleUrl(new Role(...), 'example.com/welcome')` and re-use the role many times.
### Additional context
This request arose from a problem I encountered using TestCafe in my particular situation. My situation has a log-in flow with numerous redirects (beyond my control) and the `preserverUrl` feature was holding a URL that wasn't appropriate to return to and would get stuck.

**Comment by miherlosev** [comment]
Hi @Joao-S-Martins 

> My situation has a log-in flow with numerous redirects (beyond my control) and the preserverUrl feature was holding a URL that wasn't appropriate to return to and would get stuck.

We want to investigate this situation and look for a way to handle this without adding an additional option. Could you please provide an example there this issue is reproduced?

**Comment by Joao-S-Martins** [comment]
@miherlosev This flow is managed by another team. It may be some time before I'm able to get the details, but I'll work on it.

**Comment by LavrovArtem** [comment]
Thank you. We'll wait for it.
