### ISSUE TITLE
Custom reporter configurable via config file

### ISSUE THREAD

**Issue by DamianOsipiuk** [DevExpress/testcafe#4576]
## What is your Test Scenario?

Currently, the only option to provide configuration for a custom reporter is to define a bunch of ENV variables.

### What are you suggesting?

Since the configuration file already provides an option to define reporters, I would like to ask to add there an `options` key or something similar, which will be passed down to the reporter.
Those options could be passed to some `init` function or merged into the context like `chalk` and `moment`.

### What alternatives have you considered?
N/A

### Additional context

https://devexpress.github.io/testcafe/documentation/using-testcafe/configuration-file.html#reporter

**Comment by aleks-pro** [comment]
Hello @DamianOsipiuk ,

Thank you for sharing your idea with us. We will add it to our backlog.

Also, as TestCafe is an open-source tool, you always have a chance to create a pull request in the TestCafe GitHub repository to fix a bug or add a new functionality.
