### ISSUE TITLE
Improvement - Persistent Page Unlock while debugging

### ISSUE THREAD

**Issue by fmancardi** [DevExpress/testcafe#4593]
Hi

I found useful to use a test to help the user to access a certain feature (let say take the user by hand) and the leave him/her free to continue using the system.
Right now this is possible if you add t.debug(), then you can unlock the page, but according what your next action, the page locked again.
It will be great if after you ask for UNLOCK the page, it does not return locked.

hope is clear

**Comment by miherlosev** [comment]
@fmancardi 

>  if you add t.debug(), then you can unlock the page, but according what your next action, the page locked again.

I cannot reproduce this behavior (see the [video](https://www.screencast.com/t/DofaFkDYh)). 
Could please record a video to illustrate the problematic case?

**Comment by fmancardi** [comment]
Hi
OK, I will try to explain better, because I've used a confusing term 'Next Action'.
What I need is:
execute test case 
stop execution WITHOUT having the browser closed
do any other activity in the browser, without the page locking again.

I would like to use this approach in the way that the test I've written seems most a macro executor, to put the system in one condition, and from this condition the user can be free to continue to operate.

This is something that seems can be done on other tools like puppetter and taiko.
IMHO this can be very useful to provide another usage for test cafe.

Hope now description is a little bit clear.
Going to attach video anyway.

**Comment by Farfurix** [comment]
@fmancardi 

Hello,

Thank you for your clarification. I was able to reproduce the issue under Windows 10 / Chrome 80. Our team will research it and check for a suitable solution.

For the team:
1. Run this test:
```js
import { Selector } from 'testcafe';

fixture `New Fixture`
    .page `https://devexpress.github.io/testcafe/example/`;

test('New Test', async t => {
    await t
        .typeText(Selector('#developer-name'), '123123')
        .debug();
});
```
2. **Unlock** the current page.
3. Click the "Submit" button.
4. The page is **locked** after its location **is changed** to `https://devexpress.github.io/testcafe/example/thank-you.html`.
