### ISSUE TITLE
takeScreenshot warning and corrupt image

### ISSUE THREAD

**Issue by danielschwartz85** [DevExpress/testcafe#4600]
Hi ✋,
We are writing a visual testing library for TestCafe and encountered the following issue.

#### Scenario 1 - Running Testcafe locally with Safari
1. changing css of page with Testacfe eval()
2. calling takeScreenshot()
#### Scenario 2 - Running Testcafe with browserstack against any iPhone device.
1. calling takeScreenshot()

#### Scenario 1 and 2
* getting warning: 
> Unable to locate the page area in the browser window screenshot at
  xxxx/yyy/image.png, because the page area mark with ID 4038915447 is not
  found in the screenshot.
* image is corrupt - the image has a "mark" (I think Testacfe uses this "mark" for cropping the image but since the mark is not found it isn't removed..) related to: https://github.com/DevExpress/testcafe/issues/2444

### Expected behavior

No warning (without changing the css Testcafe knows how to crop the image on Safari) and expecting a non corrupt image (in both cases).

<details>
<summary>Reproduction - Scenario 1 - run on Safari:</summary>

```
fixture`Snapshot Bug`.page`https://applitools.com/helloworld`

test('snapshot bug', async t => {
  await t.resizeWindow(600, 500)
  await t.eval(() => document.documentElement.style.transform = 'translate(10px, 20px)')
  const image = await t.takeScreenshot('./corrupt-image.png')
})
```

* BTW changing "translate(10px, 20px)" to "translate(-10px, 20px)" produces a different warning (maybe need a separate issue for this):

```
Was unable to take a screenshot due to an error.

RangeError [ERR_OUT_OF_RANGE]: The value of "sourceStart" is out of range. It must be >= 0. Received -1267280
    at _copy (buffer.js:208:13)
    at Buffer.copy (buffer.js:747:12)
    at Object.copyImagePart (/XXXXXXX/eyes-testcafe/node_modules/testcafe/src/screenshots/utils.js:40:23)
    at Object.cropScreenshot (/XXXXXXX/eyes-testcafe/node_modules/testcafe/src/screenshots/crop.js:135:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at /XXXXXXX/eyes-testcafe/node_modules/testcafe/src/screenshots/capturer.js:137:34
    at Capturer._capture (/XXXXXXX/eyes-testcafe/node_modules/testcafe/src/screenshots/capturer.js:118:9)
    at Capturer.captureAction (/XXXXXXX/eyes-testcafe/node_modules/testcafe/src/screenshots/capturer.js:164:16)
    at BrowserManipulationQueue._takeScreenshot

```

</details>

</details>

<details>
<summary>Reproduction - Scenario 2 - run against browserstack iPhones:</summary>

```
fixture`Snapshot Bug`.page`https://applitools.com/helloworld`
test('snapshot bug', async t => {
  const image = await t.takeScreenshot('./corrupt-image.png')
})
```
</details>

<details>
<summary>Screenshots:</summary>
Scenario 1 :

![3444](https://user-images.githubusercontent.com/4113198/71419098-72aa9600-2676-11ea-80c2-ae766ab1961c.png)

Scenario 2 :

![953Z](https://user-images.githubusercontent.com/4113198/71419028-25c6bf80-2676-11ea-94ec-94131f0d0b40.png)

</details>

 
### Your Environment details:
 
* testcafe version:                   1.5.0
* node.js version:                   12.13.1
* platform and version:           macOS Catalina
* iPhone:                                 browserstack:iPhone XS (for example)

Thanks.

**Comment by Farfurix** [comment]
@danielschwartz85 

Hello,

Thank you for the detailed description. I was able to reproduce the issue. Our team will research it and check for a suitable solution.


For the team:
```
testcafe edge test.js -s pathPattern=${USERAGENT}/${FILE_INDEX}.png

testcafe "saucelabs:Safari@latest:macOS 10.14" test.js -s pathPattern=${USERAGENT}/${FILE_INDEX}.png

testcafe "saucelabs:iPhone XR Simulator@13.0" test.js -s pathPattern=${USERAGENT}/${FILE_INDEX}.png

testcafe "saucelabs:Chrome@latest:Windows 10" test.js -s pathPattern=${USERAGENT}/${FILE_INDEX}.png

testcafe "saucelabs:Firefox@latest:Windows 10" test.js -s pathPattern=${USERAGENT}/${FILE_INDEX}.png
```

test.js:
```js
fixture`Snapshot Bug`
    .page`https://applitools.com/helloworld`;

test('snapshot bug', async t => {
    await t
        .resizeWindow(600, 500);

    await t
        .eval(() => document.documentElement.style.transform = 'translate(10px, 20px)');

    await t
        .takeScreenshot();
});
```
**Note: The issue doesn't occur if Chrome and Firefox are installed locally.**

**Comment by tourdedave** [comment]
> We are writing a visual testing library for TestCafe and encountered the following issue.

I'm now the maintainer of the work that @danielschwartz85 started for this.

Any update on this issue?

**Comment by wentwrong** [comment]
No updates yet. We'll research issues with screenshot cropping. Please stay tuned.
