### ISSUE TITLE
AuthSdkError: This browser doesn't support PKCE

### ISSUE THREAD

**Issue by lh62594** [DevExpress/testcafe#4601]
### Are you requesting a feature or reporting a bug?
Bug

### What is your Test Scenario?
I've created a simple react app (using create-react-app) with Okta SignIn Widget for my login page, and would like to test the login flow using Testcafe. I followed the [documentation here](https://developer.okta.com/code/javascript/okta_sign-in_widget/) to build a simple login page with Okta. 

### What is the Current behavior?
If PKCE is enabled, the browser is unable to find any of the input field Selectors and my test throws an error saying browser doesn't support PKCE. When PKCE is turned off (PKCE set to false), the tests pass. 

Login page renders fine on my browser outside of the test. 

### What is the Expected behavior?
The test runs when PKCE is enabled. 

### How would you reproduce the current behavior (if this is a bug)?
Create a simple react app with Okta Signin Widget and a basic test to log in to the app. 

#### Provide the test code and the tested page URL (if applicable)
 
React App.jsx: 
```js
import React from 'react';
import logo from './logo.svg';
import { BrowserRouter as Router, Route} from 'react-router-dom';
import Login from './Login.jsx';
import Home from './Home.jsx'
import { Security, SecureRoute, ImplicitCallback } from '@okta/okta-react';
import './App.css';

function customAuthHandler({history}){
  history.push('./login')
}

class App extends React.Component {
  render(){
      return (
        <div>
          <Router>
          <Security
            issuer={'https://dev-1234.okta.com/oauth2/1234'}
            client_id={'12345abcde'}
            redirect_uri={'http://localhost:8080/callback'}
            tokenManager={'sessionStorage'}
            pkce={true}
            onAuthRequired={customAuthHandler} >
            <Route exact path="/login" component={Login} />
            <Route path="/callback" component={ImplicitCallback} />
          </Security>
          </Router>
        </div>
      )
  }
}


export default App;

```

React Login.jsx:
```js
import React from 'react';
import OktaSignIn from '@okta/okta-signin-widget';
import '@okta/okta-signin-widget/dist/css/okta-sign-in.min.css';


class Login extends React.Component {
  constructor(props) {
    super(props)
      this.signIn = new OktaSignIn({
        baseUrl: 'https://dev-1234.okta.com',
        clientId: '12345abcde',
        redirectUri: 'http://localhost:8080/callback',
        i18n: {
          en: {
            'primaryauth.title': 'sign in to okta test app'
          }
        },
        authParams: {
          responseType: ['id_token', 'token'],
          issuer: 'https://dev-1234.okta.com/oauth2/1234',
          display: 'page',
          scopes: ['openid', 'profile', 'email']
        }
      })
  }

  componentDidMount() {
    this.signIn.renderEl(
      {el: '#sign-in-widget'},
      () => {
        /*
        Okta org handles this
        */
      },
      (err) => {
        throw err;
      }
    )
  }

  render() {
    return (
      <div>
        <div id="sign-in-widget" />
      </div>
    )
  }
}

export default Login

```

Testcafe Test File: 

```js
import { Selector } from 'testcafe';

fixture `Getting Started`
    .page `http://localhost:3000/login`;

test('My first test', async t => {
  const username = Selector('#okta-signin-username')
  const loginBtn = Selector('#okta-signin-submit')
  await t
    .typeText( username, 'test')
    .click(loginBtn)
});
```
### Your Environment details:
 
* testcafe version:                   1.7.0
* node.js version:                    v12.5.0
* command-line arguments:  testcafe chrome --skip-js-errors src/testcafe.js
* browser name and version: Chrome 76.0

**Comment by AndreyBelym** [comment]
According to [this comment](https://devforum.okta.com/t/google-chrome-doesnt-support-pkce-authsdkerror/6772/2), Okta's PKCE implementation depends on the [Web Crypto](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) API, which is available only in secure contexts. Google Chrome considers pages secure if they served from `localhost` or with the HTTPS protocol. So you can force `localhost` as TestCafe's hostname: [--hostname](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--hostname-name), or enable TestCafe's HTTPS endpoint: [--ssl](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--ssl-options).
