### ISSUE TITLE
Feature - Provide a way to bypass  babel compilation

### ISSUE THREAD

**Issue by Millsky** [DevExpress/testcafe#4602]
### What is your Test Scenario?

1. Given a testcafe test file has already been passed through babel.
   When an option passed to the compiler
   Then I should be able to bypass compilation

### What are you suggesting?

I would like to reduce the time it takes for testcafe to execute. It seems like a lot of the time is spent parsing the file and extracting the tests to run. If I have already passed my tests through babel, I would like a way to avoid this compilation step and speed up my tests.

If possible, provide a quicker method to extract the lists of fixtures, tests and meta data from tests.

### What alternatives have you considered?

Manually importing the Compiler class and overriding the step that passes the tests through babel. However, I can't seem to get this to work, it looks like there is some sort of tokenization that occurs when testcafe calls `babel.transform` on es-next files.

### Additional context

I am running testcafe on a serverless environment. The test executer needs to parse a file that has already been through babel, this seems like an extra step that can be bypassed and greatly reduce total execution time.

**Comment by Dmitry-Ostashev** [comment]
Thank you for your suggestion. We have a similar question at https://github.com/DevExpress/testcafe/issues/2659. I suggest you track it and we continue our discussion there.
