### ISSUE TITLE
On Windows 10 "--test-grep" is incorrectly matching tests

### ISSUE THREAD

**Issue by jantonypdx** [DevExpress/testcafe#4615]
### What is your Test Scenario?

Using this test file - testGrep.js
```
fixture`Grep Test`.page`https://www.google.com`;

test('can test something', async t => {
  console.log(' - here 1');
});

test('can do something', async t => {
  console.log(' - here 2');
});

test('can do something else', async t => {
  console.log(' - here 3');
});

test('will not do', async t => {
  console.log(' - here 4');
});
```
Run these two tests:
`npx testcafe chrome grepTest.js --test-grep "can do"`
`npx testcafe chrome tests/other/sandbox/grepTest.js --test-grep "will do"`

### What is the Current behavior?

On a Windows 10 system, I see this output (which looks incorrect to me):
```
# NOTE: should see 2nd & 3rd test, but NOT the 1st test
> npx testcafe chrome grepTest.js --test-grep "can do"
 Running tests in:
 - Chrome 79.0.3945.88 / Windows 10

 Grep Test
 - here 1
 √ can test something
 - here 2
 √ can do something
 - here 3
 √ can do something else


 3 passed (8s)


# NOTE: shouldn't see any tests run
> npx testcafe chrome grepTest.js --test-grep "will do"
 Running tests in:
 - Chrome 79.0.3945.88 / Windows 10

 Grep Test
 - here 4
 √ will not do


 1 passed (5s)
```
 
### What is the Expected behavior?

On a Mac High Sierra system, I see this behavior (which I believe is correct):
```
> npx testcafe chrome grepTest.js --test-grep "can do"
 Running tests in:
 - Chrome 79.0.3945.88 / macOS 10.14.6

 Grep Test
 - here 2
 ✓ can do something
 - here 3
 ✓ can do something else


 2 passed (3s)

> npx testcafe chrome tests/other/sandbox/grepTest.js --test-grep "will do"
ERROR No tests to run. Either the test files contain no tests or the filter function is too restrictive.

Type "testcafe -h" for help.
```
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 fixture`Grep Test`.page`https://www.google.com`;

test('can test something', async t => {
  console.log(' - here 1');
});

test('can do something', async t => {
  console.log(' - here 2');
});

test('can do something else', async t => {
  console.log(' - here 3');
});

test('will not do', async t => {
  console.log(' - here 4');
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

see output above...
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Save above file to grepTest.js
2. Run above commands on Windows 10 system 
3. See similar results
 
### Your Environment details:
 
* testcafe version:  1.7.1          
* node.js version: v13.3.0       
* command-line arguments:  
npx testcafe chrome tests/other/sandbox/grepTest.js --test-grep "can do"
* browser name and version: 
Chrome 79.0.3945.88
* platform and version:          
Windows 10 versus Mac High Sierra
* other:

**Comment by AlexKamaev** [comment]
I was able to reproduce the behavior you described. I noticed the difference when I ran tests using the `npx` util and without it. It looks like the `npx` util processes the "can do" string as separate arguments, and this leads to the error. Thus, the error occurs in the `npx` util because testcafe initially gets incorrect arguments.

To prevent this behavior in the future, use the following regular expression as a `--test-grep` parameter: "**can\sdo**". I checked this approach, and it works as expected.

**Comment by jantonypdx** [comment]
Ah, okay. Yes, I see the issue with npx now. Instead of replacing spaces with '\s', another option is to stop using npx and just specify the node_modules path to testcafe like this:

`node_modules\.bin\testcafe chrome grepTest.js --test-grep "can do"`
`node_modules\.bin\testcafe chrome tests/other/sandbox/grepTest.js --test-grep "will do"`

Thanks for your help!
