### ISSUE TITLE
Support NTLM v2

### ISSUE THREAD

**Issue by BobLuursema** [DevExpress/testcafe#4617]
To login to our application I need to authenticate either with Kerberos or NTLMv2. I believe that the module TestCafé uses for NTLM (https://www.npmjs.com/package/webauth) only implements NTLMv1 (https://github.com/SamDecrock/node-http-ntlm/issues/59), is that correct?

**Comment by AlexSkorkin** [comment]
According to this third-party package description and the thread you provided, this module supports only NTLM v1. We don't have plans to add support for NTLM v2 in the nearest future.
