### ISSUE TITLE
Input type email doesn't work in combination with setting different user agent

### ISSUE THREAD

**Issue by BobLuursema** [DevExpress/testcafe#4618]
### What is your Test Scenario?

I need to start up Chrome using a different user-agent to trigger certain behavior, then I need to fill in an email input field.
 
### What is the Current behavior?

TestCafé types the first character of the email 40ish times and then crashes. Except when `AppleWebKit` is contained in the `user-agent` string.
 
### What is the Expected behavior?

Email is typed into email field
 
### What is your web application and your TestCafe test code?

https://github.com/BobLuursema/testcafe-issue-demo

### Steps to Reproduce:

```sh
git clone https://github.com/BobLuursema/testcafe-issue-demo.git
cd testcafe-issue-demo
npm install
node run.js
```
See that the email field isn't filled in correctly. Now change the commented lines in `run.js` to see that it works.
 
### Your Environment details:
 
* testcafe version:                   1.7.1
* node.js version:                    12.2
* browser name and version: Chrome 79.0.3945.88
* platform and version:          Windows 10 1809

This is probably the most specific bug I've found anywhere :-P

**Comment by Dmitry-Ostashev** [comment]
Please look at the following issue where we discussed this behavior: https://github.com/DevExpress/testcafe/issues/3109.
