### ISSUE TITLE
Implement es-next api actions

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#462]
- [x] click
- [ ] rclick (call it rightClick)
- [ ] dblclick (call it doubleClick)
- [ ] press
- [ ] select (selectText, selectTextInArea, selectEditableContent)
- [ ] type
- [ ] drag (drag, dragToElement)
- [ ] hover

**Comment by inikulin** [comment]
We already have issue for this

**Comment by inikulin** [comment]
https://github.com/DevExpress/testcafe/issues/240

**Comment by AlexanderMoskovkin** [comment]
yep, I see now
