### ISSUE TITLE
InternetExplorer 11: screenshot-mark positioned partly outside of the viewport

### ISSUE THREAD

**Issue by wvankuipers** [DevExpress/testcafe#4622]
### What is your Test Scenario?
Sample hello world page (literally only a H1)
 
### What is the Current behavior?
The take a screenshot method `t.takeScreenshot();` will generate a warning when running against InternetExplorer 11 (via BrowserStack using `testcafe-browser-provider-browserstack`)

> Unable to locate the page area in the browser window screenshot at <IMAGE_PATH>, because the page area mark with ID <PAGE_MARK_ID> is not found in the screenshot.

When running against another browser (Chrome for example) this warning is not produced.
 
### What is the Expected behavior?
There should be no warning I guess...
 
### What is your web application and your TestCafe test code?
The application code & test code are the bare minimum:

"Application":

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible"
        content="ie=edge">
  <title>TestCafe test</title>
</head>

<body>
  <h1>Hello TestCafe!</h1>
</body>

</html>
```

Test code:
```js
import {t, ClientFunction} from 'testcafe';
import * as uaParser from 'ua-parser-js';

fixture('test').page('http://localhost/index.html');

test('Should display', async t => {
  await t.maximizeWindow();

  const getUA = ClientFunction(() => navigator.userAgent);
  const ua = await getUA();
  const browserName = uaParser(ua).browser.name;

  await t.takeScreenshot({
    path: `${browserName}_test.png`,
    fullPage: true
  });
});
```

Outputs (notice I added a red outline to the mark to make it visible):

Chrome:
![Chrome_test](https://user-images.githubusercontent.com/3356735/71836405-36cef200-30b4-11ea-8e61-0694a70c69d5.png)

InternetExplorer 11:
![IE_test](https://user-images.githubusercontent.com/3356735/71836398-2e76b700-30b4-11ea-8cf0-328bd20a8ac5.png)

As you can see the mark is partly rendered outside the viewport in IE, causing the warning.

### Steps to Reproduce:
Run the code above against BrowserStack.

### Steps to fix
I was able to fix the issue by placing the mark in the top left corner of the browser.~, I will add a PR for review.~ But this will make the mark not suitable for the cropping process.

**Comment by AlexSkorkin** [comment]
Thank you for submitting this issue. We were informed about a similar issue in the past and will look into it in the context of this thread: #4600
