### ISSUE TITLE
Refactor the Recipes page to include examples from the example repository

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#4632]
#### Provide the test code and the tested page URL (if applicable)

 
Your website URL (or attach your complete example):

Your complete test code (or attach your test files)

```js

```
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by VasilyStrelyaev** [comment]
Created a dedicated 'Example' page
