### ISSUE TITLE
Enable the no-return-wait ESLint rule

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#4635]
https://eslint.org/docs/rules/no-return-await

**Comment by criskrzysiu** [comment]
what about rule to disallow wrapping testcafe selectors (Testcafe promises) into async functions?

**Comment by miherlosev** [comment]
Hi @criskrzysiu 

This suggestion is related only to the code from the following repository: [https://github.com/DevExpress/testcafe](https://github.com/DevExpress/testcafe). It will not affect the test code (page models, test files, etc.).
