### ISSUE TITLE
File upload not working for input type file and no other attribute exits in the UI

### ISSUE THREAD

**Issue by Bharath0989** [DevExpress/testcafe#4639]
**Code**::
await t.setFilesToUpload('#root > div > div.css-qop084 > div.body > div.content > div > div.ui.input > input[type=file]', [ filepath ]);

**UI Code**::
`<input type="file">`

**UI Look**::
<img width="311" alt="Screen Shot 2020-01-11 at 2 36 15 PM" src="https://user-images.githubusercontent.com/54145796/72209750-cf33f080-347f-11ea-9520-e4867fe77792.png">

**Version**::
"testcafe": "^1.6.1-alpha.3",

Manually how it works::
Step 1: User click the Choose File
Step 2: Popup will open and select the file
Step 3: Auto enter happens and pop up page will be loaded with the data exits in the input file.

**Comment by Farfurix** [comment]
@Bharath0989 

Hello,

Please update your version to the latest `v1.7.1` version.

You can check your upload 'input' value by using the following assertion:
```js
t.expect(input.value).contains('test.txt');
```
I wasn't able to reproduce the issue with the following basic scenario.
**index.html**:
```html
<html>

<head></head>

<body>
    <input id="input" type="file">
</body>

</html>

```
**test.js**:
```js
import { Selector } from 'testcafe';

fixture`fixture`
    .page('./index.html');

test('test', async t => {
    const input = Selector('#input');

    await t.setFilesToUpload(input, './test.txt');

    await t.expect(input.value).contains('test.txt');
});

```
**Command**:
`testcafe chrome tesst.js`

**Result**:
```
 Running tests in:
 - Chrome 79.0.3945.117 / Windows 10

 fixture
 √ test


 1 passed (1s)

```

If the `setFilesToUpload` action breaks your scenario, please send us your project (or a public URL) so that we can examine your case and check for a suitable solution.

**Comment by Bharath0989** [comment]
Hi Farfurix,
         Thanks for the quick response.

Am facing still issue, let me give you more details,

**Browser/Platform**
Chrome 79.0.3945 / Mac OS X 10.14.6

By page don't have any id or class
`<div><div class="ui input"><input type="file"></div><div class="ui inverted dimmer"><div class="content"><div class="ui inverted text loader">Loading...</div></div></div></div>`

<img width="307" alt="Screen Shot 2020-01-13 at 4 08 02 PM" src="https://user-images.githubusercontent.com/54145796/72292224-eeb54f80-361e-11ea-91a5-24d533e95645.png">


The code i tried

Step 1: Selector added in the constructor of the class
this.choosefile  = Selector('#root > div > div.css-qop084 > div.body > div.content > div > div.ui.input > input[type=file]');
    
Step 1: Verify selector exists
if(await this.choosefile.exists) {
            Logger.step("Selector Exists");
}

Result: Pass. Printed above log

Step 3: Called upload function
async uploadFile(filePath, fileName) {
        await t.setFilesToUpload(this.choosefile, filePath+fileName);
        await t.expect(this.choosefile.value).contains(fileName);
}

Test struct at this point

I dint updated my testcafe version. If you strongly recommend and say v1.7.1 has fix then i will.

**Comment by AlexKamaev** [comment]
@Bharath0989
At first glance your project is correct and should work. However, to say it precisely we need to run your full project/example on our machines and reproduce the issue on our side. So if you still face the issue, please provide us with a working example and full test code.
