### ISSUE TITLE
Unable to Run Test Cafe in Windows. Error Message - "NativeBinaryHasFailedError: "

### ISSUE THREAD

**Issue by karan1991995** [DevExpress/testcafe#4640]
### What is your Test Scenario?
To run Test Cafe Tests in Chrome
### What is the Current behavior?
TestCafe is getting disconnected
 
### What is the Expected behavior?
Tests should run as usual
 

 

import { Selector } from 'testcafe';

fixture`Stackoverflow`
    .page`https://stackoverflow.com/questions/55283981/testcafe-get-text-from-element`;

const adsboxz = Selector('.adsbox');
test('GetInnerText', async t => {
    await t
        .click(adsboxz);
    const adsboxzstring = await adsboxz.innerText;
    console.log(adsboxzstring);
});
 
<summary>Your complete configuration file (if any):</summary>

{
    "reporter": [
        {
            "name": "xunit",
            "output": "reports/report.xml"
        },
        {
            "name": "json",
            "output": "reports/report.json"
        }
    ],
    "screenshots": {
        "path": "tests/screenshots/",
        "pathPattern": "${DATE}_${TIME}/test-${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.png",
        "fullPage": true,
        "disableScreenshots": false,
        "takeScreenshotsOnFails": false
    },
    "skipJsErrors": true,
    "skipUncaughtErrors": true,
    "concurrency": 1,
    "selectorTimeout": 3000,
    "assertionTimeout": 1000,
    "pageLoadTimeout": 1000,
    "speed": 0.1,
    "stopOnFirstFail": false
}
```
* testcafe version:      1.7.1
* node.js version:      v12.14.1    
* command-line arguments:  testcafe chrome tests/
* browser name and version:  79.0.3945.117
* platform and version:   Windows 7   

Terminal Output:

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

E:\CTS_Work\TestCafe>testcafe chrome tests/
ERROR Was unable to open the browser "chrome:" due to error.

NativeBinaryHasFailedError: The C:\Users\Karan Kaushik\AppData\Roaming
pm
ode_modules\testcafe
ode_modules\testcafe-browser-tools\bin\win\find-window.exe process failed with the 2148734720 exit code.
    at Object.execFile (C:\Users\Karan Kaushik\AppData\Roaming\npm\node_modules\testcafe\node_modules\testcafe-browser-tools\src\utils\exec.js:125:15)

Type "testcafe -h" for help.

**Comment by Farfurix** [comment]
@karan1991995 

Hello,

I cannot reproduce the issue under Windows 7. Here is my result:
![Capture](https://user-images.githubusercontent.com/30019338/72266379-4cea2e80-362f-11ea-9350-c951b38a92a6.PNG)

Could you please send us a screencast file that includes your TestCafe running command? We will check it.

**Comment by karan1991995** [comment]
@Farfurix 

Please find the below screenshot of VS Code Terminal. Hope it helps. Please let me know if you need any other details.

![image](https://user-images.githubusercontent.com/53783962/72407045-520cc200-3784-11ea-88af-539b6e8273c9.png)

**Comment by AlexKamaev** [comment]
Could you please check if there is the `\node_modules\testcafe-browser-tools\bin\win\find-window.exe` file in your `project/node_modules` folder?
Please also ensure that you installed .NET v4 or newer on your machine,since some internal tools in TestCafe use .NET if you run TestCafe in Windows.

**Comment by karan1991995** [comment]
@AlexKamaev ,

Thanks so much for your assistance. It worked pretty well after installing .NET V4. Closing this issue.
![image](https://user-images.githubusercontent.com/53783962/72441275-6aa2c980-37d0-11ea-8ed4-5f65287308aa.png)
