### ISSUE TITLE
"Unhandled promise rejection": just want to check if a Button is visible

### ISSUE THREAD

**Issue by Alpakajoe** [DevExpress/testcafe#4641]
Hey Guys, 

I'm currently working with TestCafe Version 1.41.1. My current task is to write some test cases. One of them should check whether a button is visible on a page. I have two pages. I have done this: 

    await t
    .maximizeWindow() 
    cPage.navigateToC('abcd')
    mPage.navigateToM('place', 'time')

    await t
        .expect(Selector('#create-top-btn').exists).ok() 
   
The two methods called look like this: 
cPage.navigateToC('abcd'): 

async navigateToC(name) {

	await t
	.click(this.btnToC)
	.click(this.btnCreateC)
	.typeText(this.name, name)
	.click(this.btnAddMember)
	.click(this.btnMember1)
	.click(this.btnSave)
    } 

mPage.navigateToM('place', 'time'):

async navigateToM(Place, time) {

        await t
        .click(this.btnToM)
        .click(this.btnCreateM)
        .click(this.selectC)
        .click(this.testC)
        .click(this.date)
        .click(this.dateDay)
        .typeText(this.Place, Place)

        await t
        .typeText(this.time, time)
    }

The button is visible on the "M" Page. 

Now I get this long error message after test execution. 

Unhandled promise rejection: 
ActionSelectorError { code: 'E23', isTestCafeError: true, callsite: CallsiteRecord { filename: 'C:\\Users\\x\\test.js',
      lineNum: 18, callsiteFrameIdx: 6, stackFrames: [ [CallSite], [CallSite], [CallSite], [CallSite], [CallSite], [CallSite], [CallSite], CallSite {}, [CallSite], [CallSite], CallSite {}, [CallSite], [CallSite],
      [CallSite], [CallSite], CallSite {}, [CallSite], [CallSite], [CallSite], [CallSite] ], isV8Frames: true }, selectorName: 'selector', errMsg: 'Selector is expected to be initialized with a function, CSS
      selector string, another Selector, node snapshot or a Promise returned by a Selector, but undefined was passed.', originError: { Cannot prepare tests due to an error.
      Selector is expected to be initialized with a function, CSS selector string, another Selector, node snapshot or a Promise returned by a Selector, but undefined was passed. code: 'E1022', data: [ 'undefined'
      ], rawMessage: 'Selector is expected to be initialized with a function, CSS selector string, another Selector, node snapshot or a Promise returned by a Selector, but undefined was passed.', callsite: null }}

Can anyone help me with this? Don't understand what or where I did something wrong.

**Comment by devmondo** [comment]
probably because of missing `await` ? 

```js
await cPage.navigateToC('abcd')
await mPage.navigateToM('place', 'time')
```
