### ISSUE TITLE
add extensions to empty chrome profile

### ISSUE THREAD

**Issue by bhj-patrik** [DevExpress/testcafe#4643]
### What is your Test Scenario?
i want to open chrome with extension only 
### What are you suggesting?
possibility of add extensions to chrome profile

**Comment by Farfurix** [comment]
@bhj-patrik

Hello,

You can use your current user profile with all the needed extensions. Please refer to [this documentation article](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/user-profiles.html).
