### ISSUE TITLE
TestCafe on Windows fails with spawn powershell.exe ENOENT error

### ISSUE THREAD

**Issue by Holger2233** [DevExpress/testcafe#4646]
### What is your Test Scenario?
just running testcafe
 
### What is the Current behavior?
testcafe fails with spawn powershell.exe ENOENT error
 
### What is the Expected behavior?
testcafe runs successfully with any valid test and command options
 
### What is your web application and your TestCafe test code?
n/a
 
### Steps to Reproduce:
1. Install TestCafe on Windows as per instructions https://devexpress.github.io/testcafe/documentation/using-testcafe/installing-testcafe.html#local-installation
2. run `testcafe -b` command

**Result:** Running testcafe with any option that involves a browser results in the following error. Only exceptions are `testcafe -h` and `testcafe -v`:

```
ERROR Error: Command failed with ENOENT: powershell.exe -NoLogo -NonInteractive -Command "$cp = (chcp | Select-String '\\d+').Matches.Value; Try { chcp 65001; Get-Item 'Registry::HKEY_LOCAL_MACHINE\Software\Clients\StartMenuInternet\*\shell\open\command'|Get-ItemProperty -Name '(default)'|Format-List -Property '(default)','PSPath'|Out-String -Width 2147483647|Write-Host; } Finally { chcp $cp; }"
spawn powershell.exe ENOENT
    at notFoundError (C:\Users\xxxx\AppData\Roaming\npm\node_modules\testcafe\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\xxxx\AppData\Roaming\npm\node_modules\testcafe\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\xxxx\AppData\Roaming\npm\node_modules\testcafe\node_modules\cross-spawn\lib\enoent.js:27:25)
```
### Your Environment details:
 
* testcafe version:                   1.7.1
* node.js version:                    13.6.0 (64bit), but I also tried various other versions and 32bit
* command-line arguments:  e.g. `testcafe -b` or `testcafe chrome ./test.js`
* platform and version:          Windows 10.0.18363
* npm version:                        6.13.6

I presume this is related to my system configuration, as it happens to some people within our company and not for others, but we have not been able to isolate the issue.

**Comment by miherlosev** [comment]
Hi @Holger2233 

This problem is already fixed in the https://github.com/DevExpress/testcafe-browser-tools/commit/7e8baac47ec4279e896290668e68b4ff87734a83 commit.
The fix will be included in the `testcafe@.18.0` version.

**Comment by Holger2233** [comment]
Unfortunately your fix did not work and Testcafe is now throwing a different error. I raise that again in #4665

**Comment by Farfurix** [comment]
@Holger2233 

OK, we'll check it.
