### ISSUE TITLE
NativeBinaryHasFailedError: Chrome fails to launch on Heroku with versions ^1.7.0

### ISSUE THREAD

**Issue by jelling** [DevExpress/testcafe#4652]
Testcafe versions 1.7.0 and 1.7.1 cannot launch Chrome on Heroku and throws error:

```
NativeBinaryHasFailedError: The /app/node_modules/testcafe-browser-tools/bin/linux/glibc-64/find-window process failed with the 101 exit code.
```

The same test works fine with version 1.6.1 or below and works fine with versions ^1.7.0 on MacOS so this could be a Heroku issue. Chrome is installed on the Heroku dyno via buildpack https://github.com/heroku/heroku-buildpack-google-chrome.git.

We can work-around this using v1.6.1 but want to report to save anyone else the time debugging this.

Fuller log:

```
> pw-app@1.0.0 test:e2e:heroku /app
> concurrently -k -s=first -n e2e:server,e2e:testcafe "PORT=3333 npm run start:heroku" "TESTCAFE_URL=http://127.0.0.1:3333/ testcafe chrome e2e/*.e2e.js -s takeOnFails=true"

{...}

[e2e:testcafe] ERROR Was unable to open the browser "chrome:" due to error.
[e2e:testcafe] 
[e2e:testcafe] NativeBinaryHasFailedError: The /app/node_modules/testcafe-browser-tools/bin/linux/glibc-64/find-window process failed with the 101 exit code.
[e2e:testcafe]     at Object.execFile (/app/node_modules/testcafe-browser-tools/src/utils/exec.js:120:15)
[e2e:testcafe] 
[e2e:testcafe] Type "testcafe -h" for help.
[e2e:testcafe] TESTCAFE_URL=http://127.0.0.1:3333/ testcafe chrome e2e/*.e2e.js -s takeOnFails=true exited with code 1
```

**Comment by aleks-pro** [comment]
Hello @jelling ,

Please provide us with the [stack](https://devcenter.heroku.com/articles/stack) version you are using. You can determine it via the following command: [`heroku apps:info`](https://devcenter.heroku.com/articles/stack#viewing-which-stack-your-app-is-using)

**Comment by jelling** [comment]
@aleks-pro Heroku 18

**Comment by sjt003** [comment]
this is also happening with version 1.8.0 on ubuntu 18.04

**Comment by AndreyBelym** [comment]
@jelling this error means that TestCafe cannot establish connection to an X11 display system. Do you use Xvfb in your Heroku build? Could you please modify your CI build to run the `echo $DISPLAY` command before TestCafe. Also, if it is an X11-related issue, you could try to specify `chrome:headless` as a workaround.

@sjt003 Does it happens on a CI system or on your Ubuntu desktop?

**Comment by sjt003** [comment]
@AndreyBelym just on jenkins ci. everything works perfectly on my ubuntu machine

**Comment by dannyheardairelogic** [comment]
I'm also getting this issue on version 1.8.0 on WSL2, passing the chrome browser path

**Comment by sjt003** [comment]
rolling back to 1.6.1 didn't work for me.
changing `testcafe puppeteer-chromium:.chromium.js` 
to this `testcafe 'chromium:./node_modules/chromium/lib/chromium/chrome-linux/chrome:headless --no-sandbox' ` allowed tests to run in the container

**Comment by sjt003** [comment]
`--no-sandbox` is needed to allow the tests to run with root

**Comment by AndreyBelym** [comment]
@dannyheardairelogic Thank you for your report. I was able to reproduce the issue.

**Comment by jelling** [comment]
> @jelling this error means that TestCafe cannot establish connection to an X11 display system. Do you use Xvfb in your Heroku build? Could you please modify your CI build to run the `echo $DISPLAY` command before TestCafe. Also, if it is an X11-related issue, you could try to specify `chrome:headless` as a workaround.

Our tests are running in headless chrome already (at least with v1.6) even though we don't specify headless in the test command: 

```
> concurrently -k -s=first -n e2e:server,e2e:testcafe "PORT=3333 npm run start:heroku" "TESTCAFE_URL=http://127.0.0.1:3333/ testcafe chrome e2e/*.e2e.js -s takeOnFails=true"
{...}
[e2e:testcafe]  Running tests in:
[e2e:testcafe]  - HeadlessChrome 79.0.3945 / Linux 0.0.0
```

I suspect that Heroku buildpack only includes Chrome headless. I didn't see any sign of xvfb in the test/dyno setup.

**Comment by AndreyBelym** [comment]
@jelling Thank you for the provided information. Yes, the buildpack automatically adds the `--headless` switch to any `google-chrome` command: [Shims and Command-Line Flags](https://github.com/heroku/heroku-buildpack-google-chrome#shims-and-command-line-flags).

However, TestCafe can't detect that and tries to handle Chrome like it is in GUI mode. The `chrome:headless` modifier is required to properly use Chrome Headless with TestCafe.

**Comment by jelling** [comment]
@AndreyBelym that fixed it! Thank you.
