### ISSUE TITLE
Screenshot feature ("takeOnFails") works only once, or works very rarely 

### ISSUE THREAD

**Issue by DzikiKaczor** [DevExpress/testcafe#4656]
### What is your Test Scenario?
Just run any test that fails and capture a screenshot on failure.
 
### What is the Current behavior?
Screenshot feature works only once, or works very rarely (like once for many dozens times).
 
### What is the Expected behavior?
Screenshot is taken every time the test fails
 
### What is your web application and your TestCafe test code?
I can't give URL to the website :( So I'm not sure if a testcode will be of any use but anyways:

> import { ClientFunction } from 'testcafe';
> import channelsPage from '../page-model/channelsPage-model';
> import loginPage from '../page-model/loginPage-model';
> import commonElements from '../page-model/commonElements-model';
> import crmPage from '../page-model/crmPage-model';
> import config from '../config/config';
> 
> 
> let l1 =  require('../support/global').log[0];
> 
> 
> const customerIdProper = '3'
> const customerIdWrong = '1x2y3o5u'
> 
> fixture`SmokeTests`
>   .beforeEach(async t => {
>     await t.maximizeWindow()
>   })
>   .page`${config.baseUrl}`;
> 
> test('Search for a customer by Customer ID', async t => {
> 
>   await t.maximizeWindow();
> 
>   //Log in
>   await loginPage.logIn(l1.username, l1.password);
> 
>   //Check if proper site opened
>   if (await loginPage.keycloakLoginError.exists) {
>     await loginPage.logIn(l1.username, l1.password);
> 
>   }
>   else {
>     await t.expect(channelsPage.lineupsAndPackages.exists).ok();
>     await t.expect(channelsPage.createDropUp.exists).ok();
>   }
>   const mainPage = ClientFunction(() => window.location.href)
>   await t.expect(mainPage()).contains(`https://${config.baseUrl}` + `${config.channelsSufix}`);
> 
>   //Go to CRM main page (search)
>   await t.click(commonElements.navDropdown);
>   await t.click(commonElements.navDropdownItem.withText('CRM'));
> 
>   //Search for an existing Customer ID
>   await t.click(crmPage.customerIdRadioButton);
>   await t.typeText(crmPage.inputField, customerIdProper);
>   await t.click(crmPage.searchButton);
>   await t.expect(crmPage.resultsTable.exists).ok();
>   await t.expect(crmPage.searchMessage.withText('Found').exists).ok() && expect(crmPage.searchMessage.withExactText(customerIdProper).exists).ok();
> 
>   //Search for a non-existing Customer ID
>   await t.typeText(crmPage.inputField, customerIdWrong, {replace: true});
>   await t.click(crmPage.searchButton);
>   await t.expect(crmPage.resultsTable.exists).notOk();
>   await t.expect(crmPage.searchMessage.withText('No customer found with the provided ID:').exists).ok() && expect(crmPage.searchMessage.withExactText(customerIdWrong).exists).ok();
> 
> });

**<summary>Your complete configuration file (if any):</summary>**

> {
>   "browsers": "chrome",
>   "screenshots": {
>     "path": "reports/screenshots/",
>     "takeOnFails": true
>   },
>   "reporter": [
>     {
>       "name": "spec"
>     },
>     {
>       "name": "json",
>       "output": "reports/generatedReports/newReport.json"
>     }
>   ],
>   "pageLoadTimeout": 1000
> }

**<summary>Your complete test report:</summary>**

> {
>   "startTime": "2020-01-17T11:16:27.931Z",
>   "endTime": "2020-01-17T11:16:40.618Z",
>   "userAgents": [
>     "Chrome 79.0.3945.117 / Windows 10"
>   ],
>   "passed": 0,
>   "total": 1,
>   "skipped": 0,
>   "fixtures": [
>     {
>       "name": "SmokeTests",
>       "path": "C:\\TestCafe\\orchestrator-automation\\smoke\\searchForCustomerByCustomerID.js",
>       "meta": {},
>       "tests": [
>         {
>           "name": "Search for a customer by Customer ID",
>           "meta": {},
>           "errs": [
>             "AssertionError: expected false to be truthy\n\nBrowser: Chrome 79.0.3945.117 / Windows 10\n\n   43 |\n   44 |  //Search for an existing Customer ID\n   45 |  await t.click(crmPage.customerIdRadioButton);\n   46 |  await t.typeText(crmPage.inputField, customerIdProper);\n   47 |  await t.click(crmPage.searchButton);\n > 48 |  await t.expect(crmPage.resultsTable.exists).ok();\n   49 |  await t.expect(crmPage.searchMessage.withText('Found').exists).ok() && expect(crmPage.searchMessage.withExactText(customerIdProper).exists).ok();\n   50 |\n   51 |  //Search for a non-existing Customer ID\n   52 |  await t.typeText(crmPage.inputField, customerIdWrong, {replace: true});\n   53 |  await t.click(crmPage.searchButton);\n\n   at <anonymous> (C:\\TestCafe\\orchestrator-automation\\smoke\\searchForCustomerByCustomerID.js:48:47)"
>           ],
>           "durationMs": 12617,
>           "screenshotPath": null,
>           "skipped": false
>         }
>       ]
>     }
>   ],
>   "warnings": []
> }

### Steps to Reproduce:

Just run any test that fails and try to capture a screenshot on failure more than once.
 
### Your Environment details:

- testcafe version: 1.7.0
- node.js version: v10.16.3
- command-line arguments: testcafe ./smoke/searchForCustomerByCustomerID.js
- browser name and version: Chrome 79.0.3945.117
- platform and version: Windows 10

**Comment by aleks-pro** [comment]
Hello @DzikiKaczor ,

I have not managed to reproduce the issue by using your configuration file, TestCafe version 1.7.0 and the following test example:
```js
import { Selector } from 'testcafe';

fixture `Fixture 1`
    .page `https://devexpress.github.io/testcafe/example`;

test('Test 1', async t => {
    const header = Selector('h1').withText('Example');

    await t.expect(header.textContent).eql('Examples');
});
```
Is the problem reproducible with this test on your side? If it's not, please provide us with a simple test example with which we can reproduce the issue.

**Comment by DzikiKaczor** [comment]
Well... That's strange. When I use your example of a test, screenshot feature always works. But when I use my tests it doesn't.

I've edited your test, I've used it on my env and the bug doesn't reproduce.

Nevertheless it does reproduce every time with my own tests. Like the one pasted in the 1st post.

Or other one, simpler test:

```import { ClientFunction } from 'testcafe';
import channelsPage from '../page-model/channelsPage-model';
import loginPage from '../page-model/loginPage-model';
import config from '../config/config';


let l1 =  require('../support/global').log[0];


fixture `SanityTests`
  .beforeEach(async t => {
    await t.maximizeWindow()
  })
  .page`${config.baseUrl}`;

test ('Log In', async t => {

  await t.maximizeWindow();
  await loginPage.logIn(l1.username, l1.password);
  const afterLoginUrl = ClientFunction(() => window.location.href)
  await t.expect(afterLoginUrl()).contains(`https://${config.baseUrl}` + `${config.channelsSufix}` + 1)
    .expect(channelsPage.lineupsAndPackages.exists).ok();

});
```

**Comment by Farfurix** [comment]
@DzikiKaczor 

Hello,

> Nevertheless it does reproduce every time with my own tests.

I cannot reproduce the issue by using the [above information](https://github.com/DevExpress/testcafe/issues/4656#issuecomment-576261534): there are no required definitions: '../config/config', '../page-model/loginPage-model', '../page-model/channelsPage-model'.
Please provide us with your **complete** example, so that we can examine it and check for a suitable solution.

**Comment by DzikiKaczor** [comment]
Thanks for the response.

The thing is the app I'm testing is accessible only from internal web. I'll try to find a solution to make it available for you. In a meantime I'm attaching requested files.

[ConfigAndPomsForDebug.zip](https://github.com/DevExpress/testcafe/files/4096823/ConfigAndPomsForDebug.zip)

**Comment by AlexSkorkin** [comment]
@DzikiKaczor
We've received your information and will look into this issue soon. Please stay tuned.

**Comment by arubtsov** [comment]
Hello @DzikiKaczor,

Unfortunately, we are still not able to run your example because of the following error:
`Error: Cannot find module './channelEditPage-model'`
Please provide us with the missing dependency, so we could proceed with this problem.

**Comment by DzikiKaczor** [comment]
Ah, of course. Missed it when uploading the files.

I hope it will be working with given example as I did some changes in repo lately.

[ConfigAndPomsForDebugV2.zip](https://github.com/DevExpress/testcafe/files/4148484/ConfigAndPomsForDebugV2.zip)

**Comment by LavrovArtem** [comment]
Thank you. We will research it and inform you about the results.

**Comment by miherlosev** [comment]
Hi @DzikiKaczor 

I started to set up your example and found that the `username/password` and `${config.baseUrl}` parameters are missing.
Could you please create a final example that we can run locally without any additional set up? If the example contains the private information, you can send it via `support@devexpress.com`.

**Comment by DzikiKaczor** [comment]
Hello,

I'm pretty sure everything you need is attached (my previous comment attachment).

${config.baseUrl} value is provided in config.json and as of credentials I've sent them some time ago (27.01.2020 10:42 to be precise ;) ) to the provided e-mail address (support@devexpress.com). 

Please reach out to @AlexSkorkin as he was the one who's responded.

PS.
I can see that user created for TestCafe team has been deleted. I've recreated it just now.

**Comment by AlexSkorkin** [comment]
@DzikiKaczor,

Is it safe to return to researching your issue? Have you finished your demo presentation?

**Comment by DzikiKaczor** [comment]
@AlexSkorkin

Hello,

yes it is safe right now :) Please, do your thing ;)

**Comment by miherlosev** [comment]
Hi @DzikiKaczor

Could you please run your tests with the latest TestCafe version `1.10.1` and let us know your results?

**Comment by DzikiKaczor** [comment]
Hello @miherlosev 

Yes, I can confirm that the issue has been fixed, and the feature works fine now every time. Thanks!
