### ISSUE TITLE
getBrowserConsoleMessages returns undefined in 1.8.0

### ISSUE THREAD

**Issue by sorin-davidoi** [DevExpress/testcafe#4662]
### What is your Test Scenario?

Load a simple page and fetch the console messages.
 
### What is the Current behavior?

`test.getBrowserConsoleMessages()` returns `undefined` or `null`.
 
### What is the Expected behavior?

It should return the console messages.
 
### What is your web application and your TestCafe test code?

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
fixture`Test`;

test
    .page('https://duckduckgo.com')
    ('test', async test => {
        const { error, warn, log, info } = await test.getBrowserConsoleMessages();
    });
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```
Test
 ✖ test

   1) TypeError: Cannot destructure property `error` of 'undefined' or 'null'.

      Browser: Firefox 72.0 / macOS 10.15

         1 |fixture`Test`;
         2 |
         3 |test
         4 |    .page('https://duckduckgo.com')
         5 |    ('test', async test => {
       > 6 |        const { error, warn, log, info } = await test.getBrowserConsoleMessages();
         7 |    });
         8 |

         at Object.<anonymous> (/Users/sorindavidoi/Repositories/HTML-Client/test.ts:6:15)
         at fulfilled (<redacted>test.ts:3:58)
         at $$testcafe_test_run$$flJkbqpN0$$
      (<redacted>/node_modules/testcafe/src/api/test-run-tracker.js:76:16)
         at $$testcafe_test_run$$flJkbqpN0$$
      (<redacted>/node_modules/testcafe/src/api/test-run-tracker.js:76:16)
```
</details>

### Steps to Reproduce:

See test file.
 
### Your Environment details:
 
* testcafe version: 1.8.0                  
* node.js version: v12.14.1                   
* command-line arguments: firefox test.ts  
* browser name and version: Firefox 72 
* platform and version: macOS 10.15          
* other:                                   

This is a regression in 1.8.0 - it does not happen in 1.7.1.

**Comment by miherlosev** [comment]
Hi @sorin-davidoi 

I've reproduced the problem. Thank you for the provided information.

**Comment by miherlosev** [comment]
Fixed in https://github.com/DevExpress/testcafe/pull/4664
