### ISSUE TITLE
Testcafe doesn’t find some selectors

### ISSUE THREAD

**Issue by sivanisentinel** [DevExpress/testcafe#4663]
Hello,
We are using Material design components in our app but testcafe can’t find these selectors.
i.e: 
https://material.angular.io/components/select/examples
in this select component we are try to select one of the dropdown options and it just wont select it.
this is one of the selectors we tried: 
```js
Selector('mat-option').withExactText('Pizza')
```

can you please help us with that?

**Comment by Farfurix** [comment]
@sivanisentinel 

Hello,

I created a test to select "Material Design" options. Please check this out:
```js
import { Selector } from 'testcafe';

fixture `Fixture`
    .page `https://material.angular.io/components/select/examples`;

test('Test', async t => {
    const favoriteFood = Selector('#mat-select-0 > div > div.mat-select-value.ng-tns-c100-4 > span');
    const pizza        = Selector('#mat-option-1 > span');

    const cars        = Selector('#mat-input-0');
    const carsOptions = cars.find('option');

    const select2way = Selector('#mat-select-1 > div > div.mat-select-value.ng-tns-c100-7')
    const option3    = Selector('#mat-option-6 > span')

    await t
        .click(favoriteFood)
        .click(pizza);

    await t
        .click(cars)
        .click(carsOptions.withText('Saab'));

    await t
        .click(select2way)
        .click(option3)


    await t.debug();
});

```
Result:
![Capture](https://user-images.githubusercontent.com/30019338/72794731-8a614400-3c4d-11ea-88db-ccfa106e6320.PNG)

In this case it may be useful to check the markup of required elements. Please refer to the "TestCafe Examples" repository: [https://github.com/DevExpress/testcafe-examples/blob/master/examples/element-properties/check-element-markup.js](https://github.com/DevExpress/testcafe-examples/blob/master/examples/element-properties/check-element-markup.js)
