### ISSUE TITLE
Google sign in fails to find elements when run headless

### ISSUE THREAD

**Issue by qualityshepherd** [DevExpress/testcafe#4672]
## Steps:
1. given a Testcafe project or Testcafe is installed globally
1. save the code below to a file (eg. test.js)
1. run headlessly with latest (1.7.x) version of Testcafe and either Chrome (78.0.3904.70) or Firefox (70.0.0)

eg. `./node_modules/.bin/testcafe firefox:headless tests/test.js`

## Results:
The test fails trying to locate Google's sign in email input (#identifierId) and throws an error:
`The specified selector does not match any element in the DOM tree. > | Selector('#identifierId')`

## Impact:
This does not occur when run non-headless in chrome or ff.
node v12.14.1
Mac OS X 10.14.0 (also occurs on Ubuntu CI)

Test code
```
import { Selector } from "testcafe";

// google signin
const gmailUrl = 'https://accounts.google.com/signin/v2/';
const googleEmail = Selector('#identifierId');
const googleEmailNextBtn = Selector('#identifierNext');
const googlePassword = Selector('[name="password"]');
const googlePasswordNextBtn = Selector('#passwordNext');
const email = 'fake@gmail.com';
const password = 'password';

fixture`Headless Testcafe Tests`;

test('should sign in via google', async (t) => {
  await t
    .navigateTo(gmailUrl)
    // fails here with error: "The specified selector does not match any element in the DOM tree.""
    .typeText(googleEmail, email)
    .click(googleEmailNextBtn)
    .typeText(googlePassword, password)
    .click(googlePasswordNextBtn);
});
```

This is a regression of #4434 that was fixed for a bit. It wasn't clear if this is an issue with Testcafe, but that it occurs in both headless chrome and firefox... 🤔

**Comment by AndreyBelym** [comment]
I was able to reproduce this behavior. Google serves 2 slightly different pages depending on the user agent string: one for Chrome & Firefox and another for all other browsers (e.g. Headless Chrome, Headless Firefox, Microsoft Edge). You can change the user agent string in Headless Chrome by enabling emulation mode: [Using Chrome Device Emulation](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/using-chromium-device-emulation.html#substitute-a-user-agent). I've changed the user agent to `"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"` and the test worked in headless mode. It's better to use a config file when replacing the user agent string.  It contains a lot of characters that have some special meaning in `bash`, `Powershell` and `cmd` and should be escaped when passed in a CLI parameter. 

Also, it's better to remove the trailing slash from `https://accounts.google.com/signin/v2`. It can cause 404 errors in any browser.

**Comment by qualityshepherd** [comment]
I kinda hate google. Thanks for this!
