### ISSUE TITLE
Please do not eat errors here

### ISSUE THREAD

**Issue by danwenzel** [DevExpress/testcafe#4673]
In this section of code, we have a `catch` block that completely eats all errors: https://github.com/DevExpress/testcafe/blob/master/src/browser/provider/pool.js#L77-L79

As a result, any errors thrown from trying to find a provider module here get silently ignored.

In my specific case, CircleCI was running `yarn testcafe -b lambdatest`, and returning `The specified "lambdatest" browser provider was not found`, even though I definitely have `testcafe-browser-provider-lambdatest` installed.

After several hours of digging, I realized that the attempt at pulling the module in this try block was throwing `Error: Cannot find module '../build/safe-execute'`. It took just a few minutes of googling to realize that I needed to reset my node_modules.

Silently eating the thrown error here makes debugging much more difficult. Can we make it so that these errors are properly handled?

**Comment by AndreyBelym** [comment]
Thank you for your report. We are aware of this issue, and already have a similar suggestion: https://github.com/DevExpress/testcafe/issues/4522. So I have to close your issue as a duplicate. Please use https://github.com/DevExpress/testcafe/issues/4522 to track our progress in improving the error message. Also, if you want to make a PR, I will be happy to assist you.

**Comment by danwenzel** [comment]
ah, missed that one.  Thanks, @AndreyBelym!  If I get some extra time, I might take a crack at this

**Comment by danwenzel** [comment]
@AndreyBelym - I think this should do it: https://github.com/DevExpress/testcafe/pull/4690
