### ISSUE TITLE
TestCafe always forces you to set output file for second reporter

### ISSUE THREAD

**Issue by aleks-pro** [DevExpress/testcafe#4675]
TestCafe forces you to set an output file for a second reporter even if it doesn't output to stdout
(e.g. the dashboard reporter outputs neither to file nor to stdout.)

### What is your Test Scenario?
I need to use spec reporter with dashboard reporter for TestCafe tests:
`testcafe chrome -r spec, dashboard`
 
### What is the Current behavior?
TestCafe doesn't start tests and throws the following error: `Multiple reporters attempting to write to stdout: "spec, dashboard". Only one reporter can write to stdout.`
 
### What is the Expected behavior?
TestCafe start tests without error.

**Comment by AndreyBelym** [comment]
IMHO if we can implement this, we will be able to close https://github.com/DevExpress/testcafe/issues/3765 too.
