### ISSUE TITLE
Implement specifying browser paths through 'path:' prefix

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#468]
Require a user to add `path:`  prefix when specifying a browser path in the CLI.

What we have now:
`.\testcafe chrome,ie,C:\Firefox\firefox.exe test.js`

What it should be:
`.\testcafe chrome,ie,path:C:\Firefox\firefox.exe test.js`

Or, for if path contains spaces:
`.\testcafe chrome,ff,path:"C:\Program Files\Internet Explorer\ie.exe" test.js`
`.\testcafe chrome,ff,path:'C:\Program Files\Internet Explorer\ie.exe' test.js`

**Comment by AndreyBelym** [comment]
Working on this.

**Comment by AndreyBelym** [comment]
Need to be careful with `,`: it may be contained in paths on Unix. Tested on MacOS and Ubuntu.

**Comment by inikulin** [comment]
> Need to be careful with ,: it may be contained in paths on Unix. Tested on MacOS and Ubuntu.

I guess we should enforce  `"` for path then
