### ISSUE TITLE
Check-box checked assertion does not pass

### ISSUE THREAD

**Issue by Gjodim** [DevExpress/testcafe#4681]
If you have all reproduction steps with a complete sample app, please share as many details as possible in the sections below.

Make sure that you tried using the latest TestCafe version (https://github.com/DevExpress/testcafe/releases), where this behavior might have been already addressed.

Before submitting an issue, please check CONTRIBUTING.md and existing issues in this repository (https://github.com/DevExpress/testcafe/issues) in case a similar issue exists or was already addressed. This may save your time (and ours).
-->

### What is your Test Scenario?
 My scenario is to check or un-check check-boxes, and assert that the desired behavior is the actual behavior. 
 
### What is the Current behavior?
Current behavior is that the assertion does not pass that the check-box is checked 
 
### What is the Expected behavior?
 Check-box assertion should pass
 
### What is your web application and your TestCafe test code?
 Share a public accessible link to your application or provide a simple app which we can run.
 
Your website URL (or attach your complete example):

<details>
<summary>
My scenario is to check or un-check check-boxes, and assert that the desired behavior is the actual behavior.
I am using an approach almost identical to the one in the page object example found here - https://devexpress.github.io/testcafe/documentation/recipes/extract-reusable-test-code/use-page-model.html
Also i have already tried a solution to a similar problem found here https://stackoverflow.com/questions/54153903/testcafe-test-script-checkbox-checked-always-return-false-even-when-checked-how , but in my case this does not work as well.

I have tried several different variations which i will show here.

In my page object i am trying the following:

```
_const label = Selector('coral-checkbox-label');

export class Feature {
    constructor (text) {
        this.label    = label.withText(text);
        this.checkbox = label.parent(0).parent(0)  // .child(0)       
// the reason _.child(0)_  is commented will be mentioned in the following
}
}

export class Page {
    constructor () {
        this.featureList = [
           new Feature('Display Category')
];
    }
}_


In my test i use a function like so:

_let page = new Page();

for (const feature of page.featureList) {
        console.log(feature.checkbox);
        await t
            .click(feature.label)
            .wait(5000)
            .expect(feature.checkbox.checked).ok();
    }_
```

The element in the DOM is as follows:

<coral-checkbox name="./displayCategory" value="true" data-foundation-validation="" data-validation="" class="coral-Form-field coral3-Checkbox" aria-disabled="false" aria-required="false" aria-invalid="false" aria-readonly="false">
   <input type="checkbox" handle="input" class=" coral3-Checkbox-input" id="coral-id-7" 
   value="true" name="./displayCategory">
   <span class=" coral3-Checkbox-checkmark" handle="checkbox"></span>
   <label class=" coral3-Checkbox-description" handle="labelWrapper" for="coral-id-7"><coral- 
   checkbox-label>Display Category
    </coral-checkbox-label></label>
</coral-checkbox>

The clicking on the check-box works fine, but the problem comes out when asserting if it's checked or not.

For this i have two main approaches:
1. accessing the parent element _coral-checkbox_ in the first line of code. This is because when inspecting the DOM while engaging with the check-box, the attribute 'checked' is added here on the parent level
2. accessing the first child of the parent _<input type="checkbox" handle="input" class=" coral3-Checkbox-input" id="coral-id-7" _ - mentioned in the comment of the first line of code. This is because, test-cafe assertion of a check-box works on a _input_ type only.

Neither of these approaches work, nor does something in between, like different types of assertions, positive or negative scenarios ...:</summary>

```
_const label = Selector('coral-checkbox-label');

export class Feature {
    constructor (text) {
        this.label    = label.withText(text);
        this.checkbox = label.parent(0).parent(0)  // .child(0)       
// the reason _.child(0)_  is commented will be mentioned in the following
}
}

export class Page {
    constructor () {
        this.featureList = [
           new Feature('Display Category')
];
    }
}_


In my test i use a function like so:

_let page = new Page();

for (const feature of page.featureList) {
        console.log(feature.checkbox);
        await t
            .click(feature.label)
            .wait(5000)
            .expect(feature.checkbox.checked).ok();
    }_
``` --> 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

 {
  "name": "test-cafe-jp",
  "version": "1.0.0",
  "description": "",
  "main": "test/contentPage.js",
  "directories": {
    "test": "tests"
  },
  "dependencies": {
    "minimist": "^1.2.0"
  },
  "devDependencies": {
    "testcafe": "^1.8.0"
  },
  "scripts": {
    "test-contentPage": "testcafe chrome tests/configurationPage.js --env='localhost:4502'"
  },
  "author": "",
  "license": "ISC"
}
 -->
```

```
</details>

<details>
<summary>Chrome 79.0.3945 / Mac OS X 10.13.6
AssertionError: expected false to be truthy

Browser: Chrome 79.0.3945 / Mac OS X 10.13.6
Screenshot: 

                                
                                
                                
                            

   78 |         for (const feature of page.featureList) {
   79 |         console.log(feature.checkbox);
   80 |         await t
   81 |             .click(feature.label)
   82 |             .wait(5000)
 > 83 |             .expect(feature.checkbox.checked).ok();
   84 |     }
   85 |         //await markCheckBox(t, elements);
   86 |         await selectTab(t, elements.teaserContentTab);
   87 |         await populateText(t,'textarea', 'name', './teaserTitle', inputData.teaserTab['Teaser Title']);
   88 |         await populateText(t, 'textarea', 'name', './teaserDescription', inputData.teaserTab['Teaser Description']);

   at ok)}/Users/gjorgidimov/Desktop/TestCafe-Axpo/tests/TeaserComponent.js:83:47:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:
My scenario is to check or un-check check-boxes, and assert that the desired behavior is the actual behavior.
I am using an approach almost identical to the one in the page object example found here - https://devexpress.github.io/testcafe/documentation/recipes/extract-reusable-test-code/use-page-model.html
Also i have already tried a solution to a similar problem found here https://stackoverflow.com/questions/54153903/testcafe-test-script-checkbox-checked-always-return-false-even-when-checked-how , but in my case this does not work as well. 
I am using the TestCafe Studio, with the following configuration: 
![image](https://user-images.githubusercontent.com/46923914/72892818-cf51ad00-3d17-11ea-9eaa-99bfeb2be459.png)
![image](https://user-images.githubusercontent.com/46923914/72892837-d678bb00-3d17-11ea-9472-e5713efcda3a.png)
 -->

 
### Your Environment details:
 
* testcafe version:                    1.8.0` 
* node.js version:                     10.15.3` 
* command-line arguments:   example: "testcafe ie,chrome -e test.js" 
* browser name and version:  Chrome  Version 79.0.3945.88 (Official Build) (64-bit) 
* platform and version:          example: "macOS HighSierra Version 10.13.6

**Comment by alexey-lin** [comment]
@Gjodim,
We'd love to help you, but the given information is not enough to reproduce the issue on our side. Could you please provide us with a public page URL or sample project code? The full test code and complete test report also might be useful.

**Comment by Gjodim** [comment]
![image](https://user-images.githubusercontent.com/46923914/73000246-dbfe0000-3e00-11ea-8cd1-a7863f76f407.png)

On the image above i have the element of interest.
It is a check-box which is yet un-marked.

My scenario is, that i want to make a page object for check-boxes in general.
With this page object, i can see if any desired check-box (at the moment in the given example is the 'Display Category' check-box), is checked, and if not, to check the same and afterwards assert that it is indeed checked.

So in my page object file i have the following:

/* Class where the check-box will be marked - using the below class Page, together with this class Feature, using a method given in the the Test-code (at the end), i am trying first to click on the label (feature.label), thus checking the check-box, and then assert to see if the check-box is indeed marked as checked ( .expect(feature.checkbox.checked).ok(); ) 

 // this will translate to:
// click.Selector('coral-checkbox-label').withText('Display Category);

// expect(Selector('coral-checkbox-label').withText('Display   
// Category).parent(0).parent(0).checked).ok;    // or

// expect(Selector('coral-checkbox-label').withText('Display   
// Category).parent(0).parent(0).child(0).checked).ok

// I use either the parent or the child, because:
// 1. Parent is used because, when marking the check-box, and inspecting, the 'checked' element is // shown on the parent (coral-checkbox)
// 2. In a similar issue, the solution is to do the assertion if the check-box is checked, on the
// element which is of type <input>. In my code, this translates to the above mentioned child(0).
https://stackoverflow.com/questions/54153903/testcafe-test-script-checkbox-checked-always-return-false-even-when-checked-how

     Helper.js // filename

_const label = Selector('coral-checkbox-label'); 

export class Feature {
    constructor (text) {
        this.label    = label.withText(text);
        this.checkbox = label.parent(0).parent(0)  // .child(0)       
// the reason _.child(0)_  is commented will be mentioned in the following
}
}

// List of all desired check-boxes taken by label
export class Page {
    constructor () {
        this.featureList = [
           new Feature('Display Category')
];
    }
}_

     // Test code where check-boxes should be checked and asserted
import Page from Helper.js
_let page = new Page();
for (const feature of page.featureList) {
        console.log(feature.checkbox);
        await t
            .click(feature.label)
            .wait(5000)
            .expect(feature.checkbox.checked).ok();
    }_


// Either way i execute, i get the following report:


![image](https://user-images.githubusercontent.com/46923914/73001741-37c98880-3e03-11ea-9f34-31ddebfd20a8.png)

**Comment by Farfurix** [comment]
@Gjodim 

Hello,

This information is not sufficient to reproduce the issue. Please provide us with your **complete** example which includes your project or a public URL and your test code. We'll examine it and check for a suitable solution.

**Comment by Gjodim** [comment]
I don't have a public URL, the project is under development.

I can give you the complete code but i don't see how it would do any hood since the code i have here is the one in relevance.

**Comment by LavrovArtem** [comment]
>This is because, test-cafe assertion of a check-box works on a input type only.

This is expected behavior because only the `input` tag has the `checked` standard attribute. If you use a non-standard element with a specific attribute, you should use the `hasAttribute` function to check that some attribute exists on the element.

I created an [example](https://github.com/DevExpress/testcafe/files/4116235/tc4681.zip), which illustrates my solution. If it does not help you, please modify my example to reproduce the issue.

**Comment by Gjodim** [comment]
@LavrovArtem 
It does not work either way.
1. If i use the `parent(0).parent(0)` with `hasAttribute('checked')`, i get the same result.
2. if i use `parent(0).parent(0).child(0)`, which translates to the `input` element you have mentioned (see the DOM in the first image i uploaded), again i get the same result.

**Comment by LavrovArtem** [comment]
@Gjodim
Did you manage to execute my sample on your side? Please modify it to replicate the issue and send it back to me so we can also take a look at it. Thank you in advance.

**Comment by Gjodim** [comment]
I tried both solutions @LavrovArtem 
Both
`.expect(feature.checkbox.find('input[type="checkbox"]').checked).ok()
            .expect(feature.checkbox.hasAttribute("checked")).ok();`

as well as separately each line ... same result

**Comment by AlexSkorkin** [comment]
Thank you for your clarification. Our attempts to replicate this behavior, however, were unsuccessful. Please modify our example to illustrate the behavior you observe, so we can also see it on our side and provide you with a solution.

**Comment by Gjodim** [comment]
I know that in theory should have worked either way or another (both examples), but maybe the platform i am using (AEM), has also something to do with it or maybe i missed something to report to you.

Anyhow, i resolved the issue by using only the `input` element

`<input type="checkbox" handle="input" class=" coral3-Checkbox-input" id="coral-id-510" value="true" name="./displayDescription">`

I use the `name` attribute to both click on the check-box and also assert if it is checked.

Thanks for the help anyhow

**Comment by AlexSkorkin** [comment]
Thank you for sharing your findings with us. I'm happy to hear that you have figured out how to resolve the issue.
