### ISSUE TITLE
Test Cafe Requires Permission To Record Screen -> but permission is already granted on MAC

### ISSUE THREAD

**Issue by artipsingh** [DevExpress/testcafe#4684]
I have already given TestCafe access to record my screen and I have run automated tests successfully, however I am now working on a new project and I am now getting this message :

TestCafe requires permission to record the screen. Open 'System Preferences > Security & Privacy > Privacy > Screen Recording' and check 'TestCafe Browser Tools' in the application list.

Has anyone experienced this before?

**Comment by alexey-lin** [comment]
It can happen after a TestCafe update. In this case, the 'TestCafe Browser Tools' permission has to be un-checked and then checked again.
