### ISSUE TITLE
IE 11 freezes on file upload

### ISSUE THREAD

**Issue by AlexSkorkin** [DevExpress/testcafe#4688]
### What is your Test Scenario?

Upload files in IE.

### What is the Current behavior?

setFilesToUpload freezes IE. A test is passed in Chrome and Firefox.
 
### What is the Expected behavior?

 
A test is passed in IE as well.

### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example): https://www.htmlquick.com/reference/tags/input-file.html

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
import { Selector } from 'testcafe';

fixture `T853370`
    .page `https://www.htmlquick.com/reference/tags/input-file.html`;

test('New Test', async t => {
    await t
        .click(Selector('#examples').find('[name="uploadedfile"]'))
        .setFilesToUpload(Selector('#examples').find('[name="uploadedfile"]'), [
         'C:\\Program Files (x86)\\Google\\Chrome\\Application\\79.0.3945.130\\chrome.dll',
         'C:\\Program Files (x86)\\Google\\Chrome\\Application\\79.0.3945.130\\chrome.dll.sig',
         'C:\\Program Files (x86)\\Google\\Chrome\\Application\\79.0.3945.130\\chrome.exe.sig']) 
}); 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
none
```
</details>

<details>
<summary>Your complete test report:</summary>

```
testcafe chrome T853370.js
Using locally installed version of TestCafe.
 Running tests in:
 - Chrome 79.0.3945.117 / Windows 10

 T853370
 √ New Test


 1 passed (15s)

c:\Temp\!TestCafe>testcafe firefox T853370.js
Using locally installed version of TestCafe.
 Running tests in:
 - Firefox 72.0 / Windows 10

 T853370
 √ New Test


 1 passed (15s)

c:\Temp\!TestCafe>testcafe ie T853370.js
Using locally installed version of TestCafe.
 Running tests in:
 - Internet Explorer 11.0 / Windows 10

 T853370

STUCK HERE FOR 1 HOUR
```
</details>

### Steps to Reproduce:

1. Run the test case in IE 11
 
### Your Environment details:
 
* testcafe version:                   1.8.0
* node.js version:                    v10.16.1
* command-line arguments:  testcafe ie test.js
* browser name and version: IE 11.1184.17134.0
* platform and version:           Win 10 x64
* other:                                   [T853370 - Freezes open file dialog in IE 11](https://supportcenter.devexpress.com/internal/ticket/details/T853370)

**Comment by ArrayKnight** [comment]
This also was occurring for me in the non-Chromium version of Edge

**Comment by AlexKamaev** [comment]
duplicate https://github.com/DevExpress/testcafe-hammerhead/issues/1304
