### ISSUE TITLE
ERROR TypeError: Cannot read property 'match' of undefined in version 1.8.1

### ISSUE THREAD

**Issue by markbaird** [DevExpress/testcafe#4691]
### What is your Test Scenario?

simple one from the docs
https://devexpress.github.io/testcafe/documentation/getting-started/
 
### What is the Current behavior?

Tried upgrading to 1.8.0 but I encountered the error described here: https://github.com/DevExpress/testcafe/issues/4661

Today I pulled down 1.8.1 with the fix for the above error, but I just get a new error from the `testcafe-browser-tools` library:

> ERROR TypeError: Cannot read property 'match' of undefined

 
### What is the Expected behavior?

run as usual 

### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```
ERROR TypeError: Cannot read property 'match' of undefined
    at Object.default_1 [as default] (C:\Projects\my-project\ui\client\e2e\node_modules\testcafe-browser-tools\src\utils\unquote.js:7:33)
    at C:\Projects\my-project\ui\client\e2e\node_modules\testcafe-browser-tools\src\api\get-installations.js:89:36
    at Array.map (<anonymous>)
    at C:\Projects\my-project\ui\client\e2e\node_modules\testcafe-browser-tools\src\api\get-installations.js:88:14
    at Array.map (<anonymous>)
    at searchInRegistry (C:\Projects\my-project\ui\client\e2e\node_modules\testcafe-browser-tools\src\api\get-installations.js:84:10)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at findWindowsBrowsers (C:\Projects\my-project\ui\client\e2e\node_modules\testcafe-browser-tools\src\api\get-installations.js:102:39)
    at findBrowsers (C:\Projects\my-project\ui\client\e2e\node_modules\testcafe-browser-tools\src\api\get-installations.js:168:16)
    at Object.default_1 [as default] (C:\Projects\my-project\ui\client\e2e\node_modules\testcafe-browser-tools\src\api\get-installations.js:223:30)
    at Object.default_1 [as getBrowserInfo] (C:\Projects\my-project\ui\client\e2e\node_modules\testcafe-browser-tools\src\api\get-browser-info.js:23:27)
    at BrowserProviderPluginHost.isValidBrowserName (C:\Projects\my-project\ui\client\e2e\node_modules\testcafe\src\browser\provider\built-in\dedicated\base.js:25:29)
    at BrowserProvider.isValidBrowserName (C:\Projects\my-project\ui\client\e2e\node_modules\testcafe\src\browser\provider\index.ts:279:16)
    at Object.getBrowserInfo (C:\Projects\my-project\ui\client\e2e\node_modules\testcafe\src\browser\provider\pool.js:108:14)
    at async Promise.all (index 0)
    at Bootstrapper._getBrowserInfo (C:\Projects\my-project\ui\client\e2e\node_modules\testcafe\src\runner\bootstrapper.ts:206:29)
    at Bootstrapper.createRunnableConfiguration (C:\Projects\my-project\ui\client\e2e\node_modules\testcafe\src\runner\bootstrapper.ts:421:29)
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:          1.8.1         
* node.js version:          v12.13.1          
* command-line arguments: `chrome` 
* browser name and version: Google Chrome Version 79.0.3945.117 (Official Build) (64-bit)
* platform and version:    Windows 10 Pro x64      
* other:       Other browsers installed on my system: 
        - IE11
        - Edge Chromium version 79.0.309.71 (Official build) (64-bit)
        - Firefox 72.0.1
        - Brave 1.2.43

**Comment by markbaird** [comment]
It appears that `unquote.js` needs a check that `start` is not `undefined` before attempting a regex match.

**Comment by markbaird** [comment]
I was able to work-around this issue for now by uninstalling the Brave browser from my system.

**Comment by AndreyBelym** [comment]
Thank you for your report. I've reproduced the issue.

**Comment by AndreyBelym** [comment]
As an alternative to removing Brave, you can remove only the `HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Brave\shell\open\command` registry key with the following PowerShell command:
```ps
Remove-Item Registry::HKCU\Software\Clients\StartMenuInternet\Brave\shell\open\command -Recurse
```

The only negative effect of this workaround is that you won't be able to set Brave as a default browser via the System Settings app.

**Comment by AndreyBelym** [comment]
Or even better, you can try to reinstall Brave. There are high chances that a new Brave installation will write a correct registry key and fix the issue's reason.

**Comment by AndreyBelym** [comment]
The problem is that TestCafe can't process incorrect empty registry keys, that can be left in the registry by some browsers after the installation or update processes. Removing a problematic key or reinstalling the browser that is responsible for that key can effectively fix the issue.

I've searched for other bug reports and found a similar case. It also references Brave as a source of the problem. If you never installed Brave on your machine but still experiencing the issue, execute the following command to figure out the browser responsible for the problem:
```ps
Get-Item Registry::HKLM\Software\Clients\StartMenuInternet\*\shell\open\command | Get-ItemProperty -Name '(default)'|Format-List -Property '(default)','PSPath'|Out-String -Width 2147483647| Write-Host

Get-Item Registry::HKCU\Software\Clients\StartMenuInternet\*\shell\open\command | Get-ItemProperty -Name '(default)'|Format-List -Property '(default)','PSPath'|Out-String -Width 2147483647| Write-Host
```

You the problematic registry key by looking for a `PSPath` row which is next to an empty `(default)` row in the output. E.g. if you had the following output:
```
(default) : "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe"
PSPath    : Microsoft.PowerShell.Core\Registry::HKLM\Software\Clients\StartMenuInternet\Brave\shell\open\command

(default) :
PSPath    : Microsoft.PowerShell.Core\Registry::HKLM\Software\Clients\StartMenuInternet\Firefox-308046B0AF4A39CB\shell\open\command
``` 
you could consider Firefox as a problem's source. since its `PSPath` entry resides next to an empty `(default)` entry.

**Comment by markbaird** [comment]
> The problem is that TestCafe can't process incorrect empty registry keys, that can be left in the registry by some browsers after the installation or update processes. Removing a problematic key or reinstalling the browser that is responsible for that key can effectively fix the issue.

That's a good description of the problem, and we definitely have a good work-around to continue working with TestCafe if we encounter this issue. However it does seem that a simple check for `undefined` in the browser tools package would be appropriate to prevent this from being a continuing issue for people in the future.

**Comment by AndreyBelym** [comment]
Yes, you're right. We should definitely fix it in the next release.
