### ISSUE TITLE
Custom reporter: Create option to pass in namespaced custom reporter path

### ISSUE THREAD

**Issue by mcbriarty** [DevExpress/testcafe#4692]
### What is your Test Scenario?
Currently, the path to the custom reporter must be at the node_modules root level. A reporter that I created lives in a namespaced location so I need to add a postinstall action that moves the folder from the namespace to the root level. It would be great if we could avoid the postinstall command.

### What are you suggesting?
Pass in an optional path to the reporter so we can keep our custom reporter in our namespace:
```
node_modules/@someNamespace/testcafe-reporter-custom
```

### What alternatives have you considered?
n/a

### Additional context
Reference to the currently hardcoded path:
https://github.com/DevExpress/testcafe/blob/251c9aa14daae826895db3079954de865fdf1c4b/src/runner/bootstrapper.ts#L291

**Comment by LavrovArtem** [comment]
Thank you for the good suggestion. We will help you if he wants to do PR. In the meantime, you can install your package without scopes using the next npm 6+ feature:

```
npm i --save testcafe-reporter-custom@npm:@someNamespace/testcafe-reporter-custom
```

**Comment by mcbriarty** [comment]
Thanks! I hadn't known about the alternate install method introduced in npm 6 and it works like a charm.
