### ISSUE TITLE
Testcafe hangs if global eval function is overriden

### ISSUE THREAD

**Issue by nicodh** [DevExpress/testcafe#4693]
I want to use testcafe in an electron app and managed to configure it so that it loads the start page of the app.

When I now try to run a simple test I see the loading of the fixture but then nothing happens...
No error, the app just stays loaded. (see log attached)

If I remove the script which loads the bundled code of the react app the tests run through, the results are shown and the app is closed again. (see log attached)

These are my tests: https://github.com/deltachat/deltachat-desktop/blob/testcafe/test/testcafe/test.js
This is the test page: https://github.com/deltachat/deltachat-desktop/blob/testcafe/static/test.html
I added a clientScript which is correct loaded once the app is ready.

Is there anything special to consider if testing an electron/react app ?

For tests or reproducing the problem: https://github.com/deltachat/deltachat-desktop/pull/1363

[test-hangs-log.txt](https://github.com/DevExpress/testcafe-browser-provider-electron/files/4083951/test-hangs-log.txt)
[without-react-log.txt](https://github.com/DevExpress/testcafe-browser-provider-electron/files/4083952/without-react-log.txt)

**Comment by AlexKamaev** [comment]
To the team:
possible solution is replace `eval(fnCode)` in the `eval-function.js` to `hammerhead.nativeMethods.eval(fnCode)`

**Comment by nicodh** [comment]
Thank you so much - that solved the problem!

**Comment by miherlosev** [comment]
The solution (`hammerhead.nativeMethods.eval(fnCode)`) suggested previously will not work if `ClientFunction` has dependencies.
Our code uses eval in local scope (local function arguments available in `eval` context). If we change the code to  hammerhead.nativeMethods.eval(fnCode) the eval scope becomes global.
