### ISSUE TITLE
Page doesn't load after a form is filled in Edge Legacy

### ISSUE THREAD

**Issue by alexey-lin** [DevExpress/testcafe#4694]
After the form is filled and the Submit button is clicked, the browser stays on the form page and does not navigate to the confirmation page.

The issue is reproduced only in MS Edge and does not occur if the same steps are done manually.

I added an assertion with a one-minute timeout to the end of the test, but it doesn't help.

**Comment by alexey-lin** [comment]
For the team:
SC ticket - https://supportcenter.devexpress.com/internal/ticket/details/T854400/
Steps to reproduce can be found there.

**Comment by miherlosev** [comment]
The original customer site is unreachable. We shared a workaround here: [https://supportcenter.devexpress.com/internal/ticket/details/T854400/](https://supportcenter.devexpress.com/internal/ticket/details/T854400/). So, we can close this issue.
