### ISSUE TITLE
TestCafe should blur focused input after a click on a non-focusable in an iframe.

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#4697]
### What is your Test Scenario?
Click a non-focusable element in an iframe. Check that the previously focused element lost the focus.
 
### What is the Current behavior?
TestCafe doesn't blur the previously focused element.
 
### What is the Expected behavior?
TestCafe should blur the previously focused element.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):
<summary>**testPage.html**</summary>

 
```html
 <!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>     
</head>
<body>
    <form id="form1" runat="server">
        <iframe id="testFrame" src="testPage_frame.html">
        </iframe>
        <input type="text" id="testInput" />        
    </form>
</body>
</html>
```
</details>

<summary>**testPage_frame.html**</summary>

 
```html
 <!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div id="testDiv" style="width: 20px; height: 20px; background-color: green">    
        </div>
    </form>
</body>
</html>
```
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 fixture('Fixture').page(`./testPage.html`);

test('test', async t => { 
	await t
	.click("#testInput") 
	.switchToIframe("#testFrame")
	.click("#testDiv")
	.switchToMainWindow() 

	await t.debug();
	t.pressKey('A S D');
	await t.debug();
})
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.8.1
* node.js version:                    12.14.1
* command-line arguments:  testcafe chrome test.js
* browser name and version: Chrome 79
* platform and version:          Windows 10 1909
* other:

**Comment by wentwrong** [comment]
The problem cannot be reproduced anymore on the latest version (v1.14.2).
