### ISSUE TITLE
Support `httpAuth` within a Role

### ISSUE THREAD

**Issue by matias-matteucci** [DevExpress/testcafe#4699]
### What is your Test Scenario?

I'd like to be able to create a User Role for an application that requires NTLM Authentication. Currently, the `httpAuth` method can only be used within a fixture or test context. This creates the problem of not being able to switch users from the same test, and not being able to reutilize the session/cookies from the same role throughout the suite.
### What are you suggesting?

I'd like for Role to also support `httpAuth`.
### What alternatives have you considered?

I tried using `setNativeDialogHandler` to handle the native login prompt, but TestCafe does not show it when running the tests.
### Additional context

I'm running my suite using Google Chrome.

**Comment by LavrovArtem** [comment]
Thank you for sharing your idea with us. We will discuss it and consider implementing it in one of our future product updates.

**Comment by miherlosev** [comment]
Hi @matias-matteucci

Thank you for your interest in TestCafe. Yet, we didn't establish any ETA for this feature.

> We would really like to be able to implement this.
Would you like to try to implement this feature yourself?

**Comment by miherlosev** [comment]
https://stackoverflow.com/questions/63635483/how-to-login-only-once-before-each-fixture-in-testcafe
