### ISSUE TITLE
onInput is not called on file upload

### ISSUE THREAD

**Issue by Bharath0989** [DevExpress/testcafe#4703]
Input type file action is not triggering upon file upload

### What is your Test Scenario?
File upload 
 
### What is the Current behavior?
File upload is not calling onInput action
 
### What is the Expected behavior?
File upload is should trigger onInput action
 
### What is your web application and your TestCafe test code?
Web page code
`<Input type='file' onInput={this.handleReadFile}></Input>`

Testcafe code
await t
	.expect(Selector('input[type=file]').exists).ok()
        .setFilesToUpload(Selector('input[type=file]'), './data/sample.xlsx')
	.expect(Selector('input[type=file]').value).contains('sample.xlsx');

This test case passes but the function wont get called. 

Environment details:
* testcafe version:                   ^1.8.1
* node.js version:                    6.13.6
* browser name and version: Chrome 79.0.3945
* platform and version:           Mac OS X 10.14.6

**Comment by AlexKamaev** [comment]
I was able to reproduce the issue. I checked that the `oninput` event should be raised on `fileupload`. As a workaround, you can use the `change` event of the input[file] element.
