### ISSUE TITLE
Chrome browser hangs while navigating to app url

### ISSUE THREAD

**Issue by romulanul** [DevExpress/testcafe#4705]
### What is your Test Scenario?
Navigate to an application login page and try to login.
 
### What is the Current behavior?
While trying to navigate to the app url, once in a while (1 run within 20-30 attempts), the browser (chrome) just hangs with a blank page: there is no error thrown, no timeout - the test might run endlessly if not manually terminated. Alternatively, manually refreshing the browser will cause the test to resume and finish with success.

**More information:**

- Chrome dev tools - Network tab: there are "heartbeat" requests sent continuously to the proxy server (http://localhost:29892/browser/heartbeat/~Tjj6rm) 

- Chrome dev tools - Sources tab: if pausing the scripts execution, there is always the same line 16161 - hammerhead.js - after applying "pretty print" feature over the minified js file

Attaching files: BrowserNetwork.jpg, BrowserSources.jpg
 
### What is the Expected behavior?
There should be some sort of error or timeout thrown and the test should end; otherwise an unattended run might never get complete.
 
### What is your web application and your TestCafe test code?

Your website URL (or attach your complete example): 
I can provide an url on a private channel.

<details>
<summary>Test code:</summary>

 
```js
//sample.js
import { Selector, t } from 'testcafe';
fixture('Some test fixture')
    .beforeEach(async t => {
        await t.navigateTo('https://myurl/');
    });

test('Some test', async () => {
    await t.click(Selector('div#LoginConfirmButton'));
});

//runner.js
const createTestCafe = require('testcafe');
let testcafe = null;

runManyTimes();

async function runManyTimes() {
    for (var i = 0; i < 100; i++) {
        console.log(`>>>>>>>Iteration: ${i}`);
        await runTestCafe();
    }

}

async function runTestCafe() {
    await createTestCafe('localhost')
        .then(tc => {            
            testcafe = tc;
            const runner = testcafe.createRunner();

            return runner
                .src(['./sample.js'])
                .filter((testName) => {
                    return testName.match(/Some test/);
                })
                .browsers(['chrome'])
                .run();
        })
        .then(failedCount => {
            console.log('Tests failed: ' + failedCount);
            testcafe.close();
        });
}


```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

No configuration file is used

</details>

<details>
<summary>Your complete test report:</summary>
No errors, no information is outputted

</details>

<details>
<summary>Screenshots:</summary>

```
![BrowserNetwork](https://user-images.githubusercontent.com/36658502/73276554-8dca7180-41f1-11ea-82b1-543da89a85e2.jpg)
![BrowserSources](https://user-images.githubusercontent.com/36658502/73276564-93c05280-41f1-11ea-9203-0cc3d3cb1229.jpg)



```
</details>

### Steps to Reproduce:

Run the "runner.js" script above: 

> node .\runner.js

 (please replace https://myurl/ with the url provided in private)
 
### Your Environment details:
 
* testcafe version:     1.8.1              
* node.js version:       v12.13.0             
* command-line arguments: node .\runner.js  
* browser name and version: Chrome  79.0.3945.130 
* platform and version:  Windows 10  Enterprise (1803)      
* other:

**Comment by Dmitry-Ostashev** [comment]
Thank you for your report. I've reproduced this behavior with the [http://example.com](http://example.com) url. We'll research the issue and will notify you as soon as we have any result.

**Comment by yashLadha** [comment]
Got memory leak while running tests
```bash
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
```

**Comment by AndreyBelym** [comment]
`testcafe.close` is an asynchronous function. It's better to always mark your function as `async` and use the `await` keyword when calling asynchronous functions. If you prefer to use plain Promises, you can return a Promise returned by `testcafe.close` from the `then` handler:
```js
.then(() => {
   return testcafe.close();
});
```

TestCafe may not work correctly if `testcafe.close` was not called properly.

The `MaxListenersExceedWarning` is a separate minor issue and should have no negative effect: https://github.com/DevExpress/testcafe/issues/4862.

**Comment by romulanul** [comment]
The code above was provided just as a mean to quickly reproduce the issue. The "real" tests are executed directly (no runner) and as described in the issue (please see above), the browser randomly hangs once in a while. There is no explicit testcafe.close() in any of the tests so I don't understand how this can solve the issue.

**Comment by AndreyBelym** [comment]
I cannot reproduce the issue with the following PowerShell script:
```
For($i=0; $i -lt 10;$i++) { npx testcafe chrome test.js  }
```

It can be related to https://github.com/DevExpress/testcafe/issues/4530. Could you please try to install `testcafe@1.8.3-rc.1` and check if you can reproduce the issue with this build in your environment?

**Comment by romulanul** [comment]
I tried the following:
- running all my existing tests with "testcafe chrome...." command
- running the sample test above with the PowerShell script suggested (thank you for this simple and useful idea to repeat a test)
- running the test with the test runner as initially described in the current issue

TestCafe versions used were both 1.8.1 and 1.8.3-rc.1

I cannot reproduce the issue anymore, even though I have reproduced it constantly by the time first reporting the bug and also @Dmitry-Ostashev  confirmed the issue (using a different url)

The only difference I can see is the Chrome version:
- by the time when reproducing the bug the Chrome version was 79.0.3945.130
- currently the Chrome version is 80.0.3987.132

**Comment by Dmitry-Ostashev** [comment]
We apologize for the delayed response.

It seems I was trying to reproduce this issue in the incorrect way as @AndreyBelym mentioned above. Could you please give us a full test example and your application url to detect the problem on our side?

Note that our policy prevents us from accessing internal resources without prior written approval from a site owner. Please send us a written confirmation and your application url to the following address: [support@devexpress.com](mailto:support@devexpress.com). It must permit DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes.

**Comment by AlexSkorkin** [comment]
Just a quick note - we received your sample and access confirmation. We will look into this issue.

**Comment by AlexSkorkin** [comment]
I was able to replicate some kind of hang (but not the white screen issue you mentioned) using version 1.8.2 of testcafe. However, once I've updated testcafe to the official version (1.8.3), the issue was not reproduced - all 50 test iterations were properly passed:

![image](https://user-images.githubusercontent.com/995726/77913593-3605c080-729d-11ea-8ebb-99c3b690d5b7.png)

For now, it is unclear why the issue occurs. If you have a better example in which the issue is *always* reproduced, please share it with us so that we can examine it.
