### ISSUE TITLE
test cafe can not click on span element container text that is broken across multiple lines

### ISSUE THREAD

**Issue by mostlymark** [DevExpress/testcafe#4707]
### Are you requesting a feature or reporting a bug?

Bug report.

### What is your Test Scenario?

I have a test that requires test cafe to click on a text <span> element that with an attached click handler.

### What is the Current behavior?

If the text within the span element appears all on a single line, everything works as expected. However, if the text happens to be broken across two lines, test cafe is not able to click on the span element, and the test fails.

### What is the Expected behavior?

Test cafe should be able to click on a span element that contains text that is broken across multiple lines.

### How would you reproduce the current behavior (if this is a bug)?

Setup a test that requires clicking on a span element with text that extends across two or more lines.

#### Provide the test code and the tested page URL (if applicable)

 N/A
Your website URL (or attach your complete example):
N/A

Your complete test code (or attach your test files)
_This should be easy to reproduce. If you have trouble, just ping me._

### Your Environment details:
 
* testcafe version:     1.7.0              
* node.js version:    v11.1.0                
* command-line arguments: testcafe client/main.cafe.ts  
* browser name and version: Chrome 79.0.3945.130 
* platform and version: macOS 10.14.6         
* other:

**Comment by AndreyBelym** [comment]
I cannot reproduce the issue with the following test and page. Could you please provide an example that can be used to reproduce it?

##### test.html
```html
<html>
<head></head>
<body>
    <div style="width:30px">
        <span>text text text text text text</span>
    </div>
    <span>
        text<br>
        text
    </span>
    <script>
        document.querySelectorAll('span').forEach(span => span.onclick = (() => span.style.backgroundColor = 'green'))
</script>
</body>
</html>
```

##### test.js
```js
import { Selector } from 'testcafe';

fixture`Getting Started`
    .page`./test.html`;

test(`Click on span`, async t => {
    await t
        .click(Selector('span').nth(0))
        .expect(Selector('span').nth(0).getStyleProperty('background-color')).eql('rgb(0, 128, 0)')
        .debug()
        .click(Selector('span').nth(1))
        .expect(Selector('span').nth(1).getStyleProperty('background-color')).eql('rgb(0, 128, 0)')
        .debug()
});
```
