### ISSUE TITLE
testcafe 1.5.0 gives Uncaught exception with empty stack trace

### ISSUE THREAD

**Issue by sukhvinderb** [DevExpress/testcafe#4708]
My test is navigation through certain links to make sure that the loaded pages do not have any error and all the links are working fine. I am using testcafe docker 1.6.0 with Chrome browser
This is how I run my test
npm run test-file myTestFile.ts --test-name myTest --system-url https://localhost:8080

It navigate through all the links but gives Uncaught Exception error. It happens only in Chrome

01/30/20 08:14:56    1) Uncaught exception:
01/30/20 08:14:56 
01/30/20 08:14:56       Error:
01/30/20 08:14:56 
01/30/20 08:14:56       Browser: Chrome 72.0.3626 / Linux 0.0.0

**Comment by AlexSkorkin** [comment]
The information you provided is insufficient to determine the cause of the issue. Please fill in all fields of the bug template including the reproduction steps, environment details and sample application.

**Comment by sukhvinderb** [comment]
I am running the test on Linux environment. Please let me know what do you need from me so that this issue can be resolved. Your test basically needs to navigate though certain links to open them.You can also help me to add some code to my testing code so that it does not generate empty stack trace.

**Comment by alexey-lin** [comment]
@sukhvinderb, 

Here is our [bug template](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md). It contains several questions. Please answer them so that we can help you solve the issue. Also, try updating to the latest v1.8.1. There is a chance that an error causing this behavior was already fixed since v1.5.0.
