### ISSUE TITLE
Fix unstable qunit tests.

### ISSUE THREAD

**Issue by georgiy-abbasov** [DevExpress/testcafe#471]
https://travis-ci.org/testcafe-build-bot/testcafe/jobs/123972863#L1183
https://travis-ci.org/testcafe-build-bot/testcafe/jobs/123978257#L1183
https://travis-ci.org/testcafe-build-bot/testcafe/jobs/123984540#L1181
https://travis-ci.org/testcafe-build-bot/testcafe/jobs/123990910#L1183

They are mostly ios and android tests, but it can be os x test.

**Comment by AlexanderMoskovkin** [comment]
one more:
https://travis-ci.org/testcafe-build-bot/testcafe/jobs/124983050#L1186

**Comment by georgiy-abbasov** [comment]
At the current moment most falling tests are (descending on occurence):

###### Content-editable (/fixtures/runner/content-editable/api-actions-content-editable-test/index-test.js)

Test: difficult inverse select
message: Timeout is exceeded
expected: true
actual: false

Test: $startElement and $endElement
message: Timeout is exceeded
expected: true
actual: false

Test: without args
message: Timeout is exceeded
expected: true
actual: false


###### Select (/fixtures/runner/api/select-test/index-test.js)

Test: positive offset as a parameters
message: Timeout is exceeded
expected: true
actual: false

Test: startLine, startPos less than endLine, endPos as a parameters
message: Timeout is exceeded
expected: true
actual: false

Test: zero offset as a parameters
message: Timeout is exceeded
expected: true
actual: false

###### Cross-domain - in-iframe (/fixtures/runner/cross-domain/in-iframe-test.js)
Test: shared data
message: failed, expected argument to be truthy, was: false
expected: true
actual: false


###### Press (/fixtures/runner/api/press-test.js)
Test: B238757 - It is impossible to record and run 'press' action with '+' key
message: TypeError: n is null

The list can be extended.

**Comment by AndreyBelym** [comment]
I've seen this test failing frequently before:
https://travis-ci.org/testcafe-build-bot/testcafe/jobs/124989990#L1188
###### Press (/fixtures/runner/api/press-test.js)
Test: B253200 - TestCafe doesn't emulate browsers behavior for press "enter" key on the focused HyperLink editor (link with javascript)
message: Timeout is exceeded
expected: true
actual: false

**Comment by georgiy-abbasov** [comment]
Thanks @AndreyBelym, i updated comment above.

**Comment by georgiy-abbasov** [comment]
Found next behavior in IOS:
If safari just opened the page and we have called window.scrollTo () method, the page will scroll to specified coords, then to the top position, then to last scroll position (if we were on this page before) and after this all it will scroll again to our specified position. If we have immediatly called window.scrollTo() method  several times after page has been opened and without (or with small) delay between calls, this odd chain will be executed after our last method call.

**Comment by AlexanderMoskovkin** [comment]
Adding to the previous comment: it's reproduced only on saucelabs virtual machines with ios device emulators. It's **not** reproduced on macbook and browserstack

**Comment by georgiy-abbasov** [comment]
Found next behavior on Android simulator platform:
Overriding native dialog method, like in example below, will provoke native environment to call overriden method. It brings to raising unexpected dialog error, and the tests, where we check that an error wasn't raised, fail.
```js
window.alert = function() {

};
```

**Comment by AlexanderMoskovkin** [comment]
We have fixed frequently blinking tests so I close this. We will open a new issue (or reopen this one) if when we discover other unstable tests
