### ISSUE TITLE
Official apollo mocking

### ISSUE THREAD

**Issue by MeisterTea** [DevExpress/testcafe#4711]
### What is your Test Scenario?
I need to mock an apollo mock

### What are you suggesting?
It would be great if the testcafe team shared with us a way to mock apollo calls and a way to get mock data

see: https://stackoverflow.com/questions/59845424/mock-apollo-queries-inside-of-testcafe

**Comment by miherlosev** [comment]
Hi @MeisterTea

As far as I understand, to mock Apollo queries, you need a capability to specify an asynchronous function for the `onResponse` handler of the `RequestMock` function. This feature is not implemented - please track the [https://github.com/DevExpress/testcafe/issues/4467](https://github.com/DevExpress/testcafe/issues/4467) issue to be informed of our progress or try to implement it yourself.
