### ISSUE TITLE
CI Instructions for Travis are not working

### ISSUE THREAD

**Issue by benmonro** [DevExpress/testcafe#4714]
### What is your Test Scenario?

 My build for testcafe-testing-library has been using the instructions found on the testcafe docs for travis located here: https://devexpress.github.io/testcafe/documentation/continuous-integration/travis.html
### What is the Current behavior?

 When my builds run I get the following error:
```
apt-get install failed
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install google-chrome-stable fluxbox" failed and exited with 100 during .
```
### What is the Expected behavior?

 no errors
### What is your web application and your TestCafe test code?

 you can find my .travis file here: https://github.com/testing-library/testcafe-testing-library/blob/master/.travis.yml
<details>
<summary>Your website URL (or attach your complete example): https://github.com/testing-library/testcafe-testing-library/blob/master/.travis.yml</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):https://github.com/testing-library/testcafe-testing-library</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by miherlosev** [comment]
Hi @benmonro 

Could you please create a test PR in your repository so that I can debug the issue?

**Comment by benmonro** [comment]
yeah, here's a build where you can see it failing: https://travis-ci.org/testing-library/testcafe-testing-library/builds/645520274?utm_source=github_status&utm_medium=notification

and here's the PR for the build: https://github.com/testing-library/testcafe-testing-library/pull/111

I tried rebuilding this multiple times and it fails each time.

**Comment by AndreyBelym** [comment]
The issue is caused by an expired key in the Google Chrome APT repository. It happened before several times:

https://askubuntu.com/a/307564
https://travis-ci.community/t/packages-cannot-be-authenticated-gpg-error-google-chrome-stable/3000

We have to wait until Google fixes it on their side.
