### ISSUE TITLE
RequestLogger - Property 'timestamp' does not exist on type 'ResponseData'

### ISSUE THREAD

**Issue by bennymeade** [DevExpress/testcafe#4718]
### What is your Test Scenario?
Using the RequestLogger, the [documentation](https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/logging-http-requests.html) lists **request.timestamp** and **response.timestamp** as available objects. But neither of these objects exist on ResponseData.

 
### What is the Current behaviour?
![Untitled](https://user-images.githubusercontent.com/1033474/73675014-99aeab80-46a9-11ea-9595-a48f47161b1f.png)

![Untitled 2](https://user-images.githubusercontent.com/1033474/73675218-e8f4dc00-46a9-11ea-82e2-2e2ed5e387fa.png)

 
### What is the Expected behavior?
That **request.timestamp** and **response.timestamp** are available objects.

 
### Your Environment details:
 
"testcafe": "^1.8.1"
Node.js: 12.4.0
V8: 7.6.303.31-electron.0 
OS: Darwin x64 18.2.0

**Comment by LavrovArtem** [comment]
Thank you for reporting this issue. We will fix the typescript definitions.
