### ISSUE TITLE
Document the Feature That it is Possible to Pass a Custom Reporter to `Runner.reporter`

### ISSUE THREAD

**Issue by htho** [DevExpress/testcafe#4723]
I found out that it is possible to circumvent the tedious and error prone reporter-plugin packaging process, by simply passing the reporter object as name to `Runner.reporter`.

This is so awesome. I spent hours forking, adjusting and trying to locally publish my version of the `testcafe-reporter-json`.

### What are you suggesting?
My suggestion is to document this feature and to make sure it does not disappear. An alternative is to create a different property instead of `name` that is there to pass a reporter implementation.

### Reason 1: There is no need to publish project-specific reporters.

I implemented a very project-specific reporter, which has no value for others. There is no reason to share it with anyone.
Yes - there are ways to work with private repositories, but I can not spend my time setting up such a repository. There should be a simpler way for a simple task.

### Reason 2: The packaging process is tedious and error prone.

`npm link` does not always work on windows machines.

Forking an existing reporter is even harder, because it is hard to fulfill all the publish rules.

## Example Code

```JavaScript
const createTestCafe = require("testcafe");
const tcReporterMy = {
    async reportTaskStart (startTime, userAgents, testCount) {},
    async reportFixtureStart (name, path, meta) {},
    async reportTestDone (name, testRunInfo, meta) {},
    async reportTaskDone (endTime, passed, warnings, result) {}
};

(async ()=>{
    const testcafe = await createTestCafe(/* [...] */);
    const runner = testcafe.createRunner();
    runner.src(/* [...] */);
    runner.reporter([
        "spec",
        {name: tcReporterMy, output: "./path/to/myreport"},
    ]);
    runner.browsers(/* [...] */);
    await runner.run();
})();
```

**Comment by Dmitry-Ostashev** [comment]
Thank you for your suggestion. We will discuss it and consider improving our documentation topics about reporters.
