### ISSUE TITLE
Timeout option does't work

### ISSUE THREAD

**Issue by Prashanthram** [DevExpress/testcafe#4730]
### Are you requesting a feature or reporting a bug?
Timeout option doesn't seem to work.
Testcafe: 1.8.0
NodeJS: 10.x

### What is your Test Scenario?
I am running a case that involves transition between pages.

### What is the Current behavior?
I'm explicitly giving a wait time to get the page loaded. I tried using inbuilt timeouts but they are not working. So, Now I'm going with explicit wait
 Does ReactJS have to be implemented with different timeout strategy?

### Your Environment details:
 
* testcafe version:                   1.8.0
* node.js version:                    10.x
* command-line arguments:  testcafe chrome ./tests/PerformTest.ts --page-load-timeout 30000 --assertion-timeout 30000 --selector-timeout 30000
* browser name and version: Chrome 79.0.3945.130
* platform and version:           macOS 10.14.6

**Comment by Farfurix** [comment]
@Prashanthram 

Hello,

This information is not sufficient to reproduce the issue. Could you please provide us with a sample project (or a public URL) and your test code? We will examine it and check for a suitable solution.
