### ISSUE TITLE
Error in functions containing "new Set()" passed to Selector

### ISSUE THREAD

**Issue by kwaping** [DevExpress/testcafe#4733]
### What is your Test Scenario?
I have a set of test functions which I loop through, passing each one to Selector() to gather a list of Nodes that match.

### What is the Current behavior?
Functions which create new Set objects throw this error:
```
An error occurred in Selector code:

ReferenceError: Can't find variable: _set2
```

### What is the Expected behavior?
The test code executes successfully and does not throw an error.

### What is your web application and your TestCafe test code?
<details>
<summary>Your complete test code (or attach your test files):</summary>

```js
import { Selector } from 'testcafe';

const rule = document => {
  const buttons = new Set([]);
  return Array.from(buttons);
};

fixture('Rules test').page('http://localhost:5000/example');

const applyRule = Selector(rule => {
  return rule({ document });
});

test('rule failed', async t => {
  const failed = applyRule(rule);
  const count = await failed.count;
});
```
</details>

<details>
<summary>Your complete test report:</summary>

```
 Running tests in:
 - Safari 13.0.5 / macOS 10.14.6

 Rules test
 ✖ rule failed

   1) An error occurred in Selector code:

      ReferenceError: Can't find variable: _set2

      Browser: Safari 13.0.5 / macOS 10.14.6

         10 |  return rule({ document });
         11 |});
         12 |
         13 |test('rule failed', async t => {
         14 |  const failed = applyRule(rule);
       > 15 |  const count = await failed.count;
         16 |});
         17 |

         at <anonymous> (/path/to/bug_example.js:15:30)
         at test (/path/to/bug_example.js:13:1)
         at <anonymous> (/path/to/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at TestRun._executeTestFn (/path/to/node_modules/testcafe/src/test-run/index.js:294:19)
         at TestRun.start (/path/to/node_modules/testcafe/src/test-run/index.js:345:24)

 1/1 failed (1s)
```
</details>

### Steps to Reproduce:

1. Change the URL in the script to point to a real website.
2. Run the script.

### Your Environment details:

* testcafe version: 1.8.1
* node.js version: v10.15.3
* command-line arguments: testcafe safari bug_example.js
* browser name and version: Safari 13.0.5, Chrome 79.0.3945.130, Firefox 72.0
* platform and version: macOS 10.14.6
* other:

**Comment by Farfurix** [comment]
@kwaping 

Hello,

If I understand correctly, you want to return `Set` object from `Selector`. Please refer to this documentation article: https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/creating-selectors.html#initialize-selectors. I suggest you rewrite your `Selector` initialization function according to this rule: "A regular function executed on the client side. This function must return a DOM node, an array of DOM nodes, `NodeList`, `HTMLCollection`, `null` or `undefined`".

**Comment by kwaping** [comment]
Sorry about my example code, I tried to simplify it and went to far.

I am not trying to return a Set from the function, I eventually turn the Set object into an array and return a list of Nodes, as per spec. The example function above removed that part for (I thought) clarity. If you run the sample code, it will error with the one this ticket is created for, not because of returning a Set.

Please reopen this, thank you!

**Comment by kwaping** [comment]
I have updated my sample code to address this confusion.

**Comment by kwaping** [comment]
Thank you for reopening this! Should the type be set to Bug, also?

**Comment by AlexKamaev** [comment]
@kwaping
Hello, thank you for your input.
We aware of this behavior, however, at this moment it is not fixed. A similar problem was reported in the [https://github.com/DevExpress/testcafe/issues/3713](https://github.com/DevExpress/testcafe/issues/3713) and [https://github.com/DevExpress/testcafe/issues/4137](https://github.com/DevExpress/testcafe/issues/4137) issues.
As a workaround to the `Set` issue, you can use `new window.Set(...)` instead of `new Set(...)`.
