### ISSUE TITLE
Page reloads when using `history.pushState`

### ISSUE THREAD

**Issue by trustyoo86** [DevExpress/testcafe#4734]
### What is your Test Scenario?
We developed using `history.pushState` function for url manipulation after client rendering, And test client action.

```javascript
test.disablePageReloads('filter test', () => {
  t
   .click(Selector('label[for=checkfilter]');
   .expect(Selector('input[id="checkfilter").checked).ok();

});
``` 

### What is the Current behavior?
We setting `disablePageReloads`, but page reloads when url is changing.
 
### What is the Expected behavior?
We setting `disablePageReloads`, but page reloads when url is changing.
 
### What is your web application and your TestCafe test code?
*Chrome*
 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   v1.8.1
* node.js version:                    v12.14.1
* browser name and version: Chrome
* platform and version:         MacOS

**Comment by AlexKamaev** [comment]
The `disabledPageReloads` feature does not prevent a page from reloading. It just prevents the page reload between test runs.
Please also note that the `disablePageReloads` feature is not officially supported and documented, so we do not guarantee that your scenario should work.
If you have further questions feel free to write it here. I'll reopen the issue if it's needed.

**Comment by trustyoo86** [comment]
@AlexKamaev 
Thank you for reply.
I wonder that disable page reload when client code use `history.pushState` function.

As far as I know, `history.pushstate` changes only the url without reloading the page.
In my page, when I click the button, I am only changing the url through history.pushstate without reloading the page.
But, use testcafe, when I click the button, test browser is reload. So, I need to know how disable page reload when use `history.pushState`.

Thank you.

**Comment by LavrovArtem** [comment]
It really looks like a bug. But this information is not sufficient to find the cause of the issue. Could you please provide a page or a small example so that we can reproduce it on our side?

**Comment by caias** [comment]
@AlexKamaev 
@LavrovArtem 
Hi guys 
im co-worker with @trustyoo86 in this issue.
sorry for late check U R reply
  
here is simple test case code about some website used history.pushstate
  
```js
fixture('push-state example').page('https://hydejack.com/');

test.disablePageReloads('reload test between test function', async (t) => {
  await t
    .click(await Selector('.sidebar-nav-item').nth(0));
});

test.disablePageReloads('reload test between test function', async (t) => {
  await t
    .click(await Selector('.sidebar-nav-item').nth(1));
});

test.disablePageReloads('reload test between test function', async (t) => {
  await t
    .click(await Selector('.sidebar-nav-item').nth(2));
});

test.disablePageReloads('reload test between test function', async (t) => {
  await t
    .click(await Selector('.sidebar-nav-item').nth(3));
});
```

I hope this issue wiil be fix correct ASAP. 
Thank you so much.

**Comment by LavrovArtem** [comment]
I've reproduced the behavior when the page is reloaded between tests with the `disablePageReloads` option enabled, but we will not address it. As @AlexKamaev explained, this feature does not prevent page reload. It prevents it only between test runs. The disablePageReloads feature is not supported and documented officially. We do not guarantee that it will work in all scenarios under all circumstances.

> As far as I know, history.pushstate changes only the url without reloading the page.
In my page, when I click the button, I am only changing the url through history.pushstate without reloading the page.
But, use testcafe, when I click the button, test browser is reload. So, I need to know how disable page reload when use history.pushState.

I didn't manage to reproduce this issue. Please try to append the `wait` action before and after the `click` action and open your browser console to check if this works.

**Comment by rbardini** [comment]
I'm facing the same problem: when I disable page reloads and the application navigates using `history.push`, the page reloads back to the original URL. It seems `disablePageReloads` not only disables page reloads between test runs, but also URL changes resulted from page interactions.

I understand `disablePageReloads` is not officially supported and documented, but are there any plans for first-class SPA support? Right now I have to put all actions and assertions into a single, huge `test`, and reimplement reporting with inline logs to keep track of the test run progress.

Related: https://github.com/DevExpress/testcafe/issues/1770, https://github.com/DevExpress/testcafe/issues/1381

**Comment by wentwrong** [comment]
Hi, @rbardini,

For now our team works on multi window support. So, we'll keep gathering user feedback on this enhancement. 
Thank you for your input.
