### ISSUE TITLE
Add addtional info to reportTestActionDone

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#4745]
The `reportTestActionDone` method should provide:
 - [x] action execution time
 - [ ] current test page
 - [x] snapshot of the element actually used in an action (#4779)
 - [ ] selector execution time (mark selector executions on obscured elements)

**Comment by helen-dikareva** [comment]
Current list of the extended log improvements related to the info from testcafe reporter is [here](https://github.com/DevExpress/testcafe-dashboard/issues/1042)
