### ISSUE TITLE
Inserting data into table cells with testcafe

### ISSUE THREAD

**Issue by saripr** [DevExpress/testcafe#4746]
### What is your Test Scenario?
I have a table with 3 rows and 4 columns like below and I need to enter the values into the table cells and assert them.

Columnone|columntwo|columnthreee|columnfour|
checkbox|dropdown(in which new values can be inserted)|textbox|textbox|
checkbox|dropdown(in which new values can be inserted)|textbox|textbox|
checkbox|dropdown(in which new values can be inserted)|textbox|textbox|
I need to enter values like below into the table using testcafe:

Columnone|columntwo|columnthreee|columnfour|
checkbox|columntwo0|columnthreee0|columnfour0|
checkbox|columntwo1|columnthreee1|columnfour1|
checkbox|columntwo2|columnthreee2|columnfour2|
 
### What is the Current behavior?
document.queryselectorall doesnot return any value and cannot perform typetext
 
### What is the Expected behavior?
1.document.querysleectorall does return right value
2.Choosing selector didnt work as well

### What is your web application and your TestCafe test code?
Tried below:
I tried the below code and tdText is of type function and not from client:

```
test("My test second", async t => {
  const table = Selector(".table");
  const rowCount = await table.find("tbody > tr").count;

  for (let i = 0; i < rowCount; i++) {
    const tdText =  table
      .find("tbody > tr")
      .nth(i)
      .find("td");
    for (let j = 1; j < tdText.length; j++) {
      const tdReferrer =  table
        .find("tbody > tr")
        .nth(i)
        .find("td")
        .nth(j);
      //console.log(typeof tdReferrer);
      //type text into each cell of a table
    }
  }
});

 
```
So tried below and tdText is of type function:

```
test("My test second", async t => {
  const table = Selector(".table");
  const rowCount = await table.find("tbody > tr").count;
  //dataInsert(table,rowCount);

  for (let i = 0; i < rowCount; i++) {
    const tdText = ClientFunction(() =>
      table
        .find("tbody > tr")
        .nth(i)
        .find("td")
    );
    for (let j = 1; j < tdText.length; j++) {
      const tdReferrer = table
        .find("tbody > tr")
        .nth(i)
        .find("td")
        .nth(j);
      //console.log(typeof tdReferrer);
      //type text into each cell of a table
    }
  }
});
```

Also tried below and the value of test was undefined:
```
getest("My test third", async t => {
  const table = Selector(".table");
  const rowCount = await table.find("tbody > tr").count;
  const colCount = await table.find("thead > tr >th").count;
  const rowSelector = Selector(".table>tbody>tr");
  const getrow = ClientFunction(rowno => {
    document.querySelectorAll(".table>tbody>tr")[rowno];
  });
  const test = await getrow(1);
  const tcol = ClientFunction(
    (rowno, colno) =>
      document
        .querySelectorAll(".table>tbody>tr")
        [rowno].querySelectorAll("td")[colno]
  );
  for (let i = 0; i < rowCount; i++) {
    let datavalue = getrow(i);
    //console.log(tdText().length);
    for (let j = 1; j < colCount; j++) {
      let testcol= getcol(i, j);
      //t.typeText(testcol).value = headertext appended with number
    }
  }
});
```
 
### Your Environment details:
 
* testcafe version:                   1.8.1
* node.js version:                    9
* command-line arguments:  testcafe chrome test.js
* browser name and version: chrome 79
* platform and version:          Linux 16

Possibly related to https://github.com/DevExpress/testcafe/issues/4540

**Comment by miherlosev** [comment]
Hi @saripr 

You have already asked the same question on the [StackOverflow thread](https://stackoverflow.com/questions/60136086/inserting-data-into-table-cells-with-testcafe). 
We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)). Please, don't duplicate questions from StackOverflow here.
