### ISSUE TITLE
A JavaScript error occurred "--skip-js-errors" option happening even configuring the package.json

### ISSUE THREAD

**Issue by Srihari88** [DevExpress/testcafe#4747]
### What is your Test Scenario?

 I have set configuration in package.json to prevent JSerror and to get screenshot and saved it in to my local folder, after setting the configuration on package.json with below details still it's not taking the screenshot and as well when run my test it's showing JSerrors. 

`"screenshots": {
    "path": "../testcafe-framework/Screenshots",
    "fullPage": true,
    "pathPattern": "${DATE}_${TIME}/test-${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.png"
},
  "skipJsErrors": true,
  "skipUncaughtErrors": true`
 
### What is the Current behavior?

Still JSErrors showing on the console and it's unable to capture the screenshots. 
 
### What is the Expected behavior?

JSErrors shouldn't show on the console and will able to capture the screenshots and store it on to the respective folder. 
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

- [ ] 

- [ ] 

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by alexey-lin** [comment]
Hi @Srihari88,

As far as I understand you placed these configuration options to the `package.json` file? TestCafe uses its own configuration file. It should be named `.testcaferc.json` and placed to the directory from where you run TestCafe. Please refer to the [Configuration File](https://devexpress.github.io/testcafe/documentation/using-testcafe/configuration-file.html) documentation topic to learn more.

**Comment by Srihari88** [comment]
Thank you. it's fixed.
