### ISSUE TITLE
Add capability to get a screenshot information in the test code

### ISSUE THREAD

**Issue by ferencbeutel4711** [DevExpress/testcafe#4748]
### What is your Test Scenario?
I would like to implement tests which are comparing screenshots of the page

### What are you suggesting?
Please enable the takeScreenshot-Command to return the binary data of the image directly without writing it into a file

### What alternatives have you considered?
Currently, I need to manually load the image into memory again after testcafe has put it into the location specified by the command

### Additional context
Hi guys, for tests which are comparing screenshots with a diffing-tool like rembrand, it would be useful to get the binary data representing the screenshot directly instead of first writing it into a file. I hope this wouldnt be a big change, but since I dont know how exactly you are taking the screenshot, the required change might be bigger than expected. Since it is quite easy to read the file into memory afterwards a workaround is present, so there is no huge issue to overcome.

**Comment by miherlosev** [comment]
Hi @ferencbeutel4711 

Thank you for your suggestion. It can be useful in the screenshot comparison scenario.
We have a development plan - [https://devexpress.github.io/testcafe/roadmap](https://devexpress.github.io/testcafe/roadmap). Though it can be difficult to make time for that. If the proposed feature is very important for you, a PR will be highly appreciated.
