### ISSUE TITLE
Infinite login loop with testcafe, MSAL js and Azure AD B2C

### ISSUE THREAD

**Issue by evansabove** [DevExpress/testcafe#4754]
### What is your Test Scenario?
Logging in to a web application using MSAL.js and Azure AD B2C using testcafe causes an infinite login loop. 
 
### What is the Current behavior?
The testcafe test opens the root url of the website, and gets redirected to an Azure AD B2C login page as the user is not authenticated. The user signs in with their credentials and is redirected to the original website (https://localhost:8080) with a login token. The login appears successful for a brief moment and then the app is redirected to the login callback url (in this case https://localhost:8080/#state=....). Following this the app is then redirected successfully to the home page, but then back out to the #state page etc.

Completing the same steps by hand works fine and there isn't any infinite login loop.
 
### What is the Expected behavior?
To log in once and not be redirected in a loop.
 
### What is your web application and your TestCafe test code?
The code is here: https://github.com/evansabove/testcafe-msal-sample 
It's not hosted anywhere but I can do so if it helps.

The app folder is a simple Vue JS app.
The test folder is a testcafe project with a single test demonstrating the bug.
 
<details>
<summary>Your complete test code (or attach your test files):</summary>

 

**The main.js from the Vue application**
```js
const msalConfig = {
  auth: {
      clientId: 'a1ed63c8-b3eb-4386-bf56-46a15d7694cc',
      validateAuthority: false,
      authority: 'https://andrewjamesevans.b2clogin.com/tfp/2f9626a3-9b17-40c8-839b-402afff47f01/B2C_1_SignIn',
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: true
  }
};

const msalInstance = new Msal.UserAgentApplication(msalConfig);

msalInstance.handleRedirectCallback((error, response) => {
  console.log(error);
  console.log(response);
});

let isLoggedIn = msalInstance.getAccount() != null;

if(!isLoggedIn) {
  console.log("You aren't logged in.")
  msalInstance.loginRedirect();
}
else {
  console.log("You're logged in!")
  new Vue({
    render: h => h(App, { props: { username: msalInstance.getAccount().name }}),
  }).$mount('#app')
}
```

**The login test**
```js
import TestUser from '../utilities/test-user'
import HomePage from '../page-model/home-page';

fixture `Login Tests`

test('should be able to log in and verify the welcome message is correct', async t => {
    await t
        .useRole(TestUser)
        .expect(HomePage.welcomeMessage.innerText).eql("Hello Test User, you are logged in!")
});
```

**The user role**
```js
import logonPage from '../page-model/login-page';
import Settings from '../settings'
import { Role } from 'testcafe'

export async function login(t: any) {
    await t
        .typeText(logonPage.username, Settings.username)
        .typeText(logonPage.password, Settings.password)
        .click(logonPage.signIn)
}

const TestUser = Role(Settings.appUrl, login, { preserveUrl: true });

export default TestUser
```
</details>

### Steps to Reproduce:

**Run the app**
1. cd app
2. npm install
3. npm run serve

**Run the test**
1. cd test
2. npm install
3. npm run test

### Your Environment details:
 
* testcafe version: 1.8.1                  
* node.js version: 12.15.0                   
* msal: 1.2.1
* command-line arguments: testcafe chrome tests/ --selector-timeout 10000 --assertion-timeout 10000
* browser name and version: Chrome 80.0.3987.87
* platform and version: Windows 10

**Comment by Farfurix** [comment]
@evansabove 

Hello,

Thank your for the detailed information. I was able to reproduce the behavior. We will examine it in the context of this issue: https://github.com/DevExpress/testcafe/issues/4024.

For the team:
The issue possibly relates to https://github.com/DevExpress/testcafe/issues/4296.
