### ISSUE TITLE
Browser fails to close after tests

### ISSUE THREAD

**Issue by ArrayKnight** [DevExpress/testcafe#4756]
### What is your Test Scenario?
Any and all tests being run non-headless-ly

### What is the Current behavior?
The test starts and executes, but then when the test is complete, the browser never closes and the CLI process never outputs results and never exits. The browser must be manually closed and the CLI forced exited, and still no results are output (kinda expected considering the force exit).
 
### What is the Expected behavior?
Browser should close, CLI should show results and then exit.
 
### What is your web application and your TestCafe test code?
My project is private, but it is a Create React App based Typescript app.
 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 test.before(async (t) => {
    await setupTest(t, ({ mocker }) => {
        t.ctx = {
            mocks: setupMocks(
                mocker,
                {},
                {
                    parse: new ResponseMock('parse/batchspec', specSheet),
                }
            ),
        }
    })
})('Upload Spec Sheet', async (t) => {
    await Analyses.load()

    await Analyses.createAnalysis(async () => {
        await SpecificationTable.uploadSpecSheet(
            '../../assets/sample-spec-sheet.csv'
        )

        const parseSpecSheet = await waitForRequest(
            findRequest('parse/batchspec', isRequestMethod('post'))
        )

        await SpecificationTable.validateSpecSheet(parseSpecSheet!.response)
    }, false)
})
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
    "tsConfigPath": "./tsconfig.testcafe.json",
    "src": "./e2e/**/*test.ts",
    "reporter": "palix",
    "concurrency": 4,
    "developmentMode": true,
    "screenshots": {
        "fullPage": true,
        "takeOnFails": true,
        "pathPattern": "${DATE}_${TIME}/${FIXTURE}/${TEST}/${USERAGENT}/${QUARANTINE_ATTEMPT}_${FILE_INDEX}.png"
    },
    "skipJsErrors": true,
    "skipUncaughtErrors": true
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```
$ npm run test:e2e:dev

> palix-react-frontend@0.1.0 test:e2e:dev C:\Users\ArrayKnight\Git\palix-react-frontend
> npm-run-all -p -r start test:e2e:dev:env


> palix-react-frontend@0.1.0 start C:\Users\ArrayKnight\Git\palix-react-frontend
> node scripts/start.js


> palix-react-frontend@0.1.0 test:e2e:dev:env C:\Users\ArrayKnight\Git\palix-react-frontend
> wait-on http://localhost:3000/ && cross-env APP_CLIENT_URI=http://localhost:3000/ MOCK=true npm run test:e2e:dev:exec

i ｢wds｣: Project is running at http://10.20.1.88/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from C:\Users\ArrayKnight\Git\palix-react-frontend\public
i ｢wds｣: 404s will fallback to /index.html
Starting the development server...
Compiled with warnings.

./node_modules/pdfjs-dist/build/pdf.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/pdfjs-dist/build/pdf.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/pdfjs-dist/build/pdf.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/pdfjs-dist/build/pdf.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.


> palix-react-frontend@0.1.0 test:e2e:dev:exec C:\Users\ArrayKnight\Git\palix-react-frontend
> dotenv -- cross-var testcafe chrome ./e2e/pages/%E2E_PAGE%/test.ts --test "%E2E_TEST%" --concurrency 1

The "src", "concurrency", "filter" options from the configuration file will be ignored.
 Running tests in:
 - Chrome 79.0.3945.130 / Windows 10

 Analyses

```
</details>

<details>
<summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/5431637/74385624-d022af80-4da8-11ea-8905-ab9ac36e40a1.png)

</details>

### Steps to Reproduce:

1. Run the dev server
2. Execute the TestCafe script (config and parameters don't seem to make a difference)
3. Wait for the test to complete
 
### Your Environment details:
 
* testcafe version:                   1.8.1
* testcafe-react-selectors:       3.3.0
* node.js version:                    12.13.1
* command-line arguments:  Anything except using a headless browser
* browser name and version: Chrome 79, Firefox 72, Edge 80
* platform and version:          Windows 10
* other:                                   The exact same code + tests run as expected with headless browsers

**Comment by Farfurix** [comment]
@ArrayKnight 

Hello,

I wasn't able to reproduce the issue. Could you please share a sample project with us? We will examine it and check for a suitable solution.

**Comment by ArrayKnight** [comment]
When it is in this hung state, there are still constant network requests occurring.

http://10.0.75.1:52269/browser/heartbeat/fCsWjon

But the response cycles between three things:

```
{"code":"ok","url":""}
```

```
{"code":null}
```

```
{"cmd":"idle","url":"http://10.0.75.1:52269/browser/idle/fCsWjon"}
```

Not sure if that's helpful.

I let it run for a full 5 minutes after test completion and it just never exits.

**Comment by ArrayKnight** [comment]
If I run the same test with quarantine mode enabled, the expected behavior occurs.

**Comment by Dmitry-Ostashev** [comment]
Unfortunately, we cannot determine the cause of the issue by your description. We need a sample project to reproduce and research it on our side.
