### ISSUE TITLE
Latest TestCafe 1.8.2 not available on https://www.npmjs.com/package/testcafe

### ISSUE THREAD

**Issue by jiteshsojitra** [DevExpress/testcafe#4761]
When latest TestCafe 1.8.2 would be available on https://www.npmjs.com/package/testcafe ?

Seems like you changed version from 1.8.2 to v1.8.2-rc.1 :)

**Comment by AndreyBelym** [comment]
Thank you for your interest in a new TestCafe release 😄. We will never release a stable TestCafe build without releasing and testing a preliminary `alpha` or `rc`  build. So it was just an inaccurate Git tag 😞 

We are actively testing a release candidate (`testcafe@1.8.2-rc.1`) and will release `v1.8.2` if we don't find any critical problems. If you are don't mind installing preliminary builds, you can try to install `testcafe@1.8.2-rc.1` from `npm`. 

I will post a notification in this thread when `testcafe@1.8.2` is published to NPM.

**Comment by AndreyBelym** [comment]
Thank you for your patience, `testcafe@1.8.2` is available now.
