### ISSUE TITLE
Bottom part of web page is not visible for testcafe

### ISSUE THREAD

**Issue by ZaPaw** [DevExpress/testcafe#4763]
### What is your Test Scenario?

I would like to test form page. In given example I want to type text to textarea.
 
### What is the Current behavior?

Test failed. I get information that:
" 1) The element that matches the specified selector is not visible."

### What is the Expected behavior?

 Typed text: "Hello TestCafe!" to textarea.

### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>
https://tfoeunqa.thereforeonline.com//Client/forms/embed/2?allowanonymous=1

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```ts
import { Selector } from 'testcafe';

fixture('My fixture')
    .page('https://tfoeunqa.thereforeonline.com//Client/forms/embed/2?allowanonymous=1');

    const messageInput = Selector('#message');
      
    test("My first test", async t=> {

      await t.maximizeWindow();
      await t.debug();
      await t.typeText(messageInput,"Hello TestCafe!");
        
    });
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Run test from code I pasted. Command I used for start test is: npx testcafe chrome  test.ts
 
### Your Environment details:
 
* testcafe version:      1.8.1         
* node.js version:    v12.14.1                
* command-line arguments:  npx testcafe chrome  test.ts 
* browser name and version: Chrome 80.0.3987.100
* platform and version:   Windows 10       
* other:   When I used debug mode and manually zoom out page to 80% and then resume, test passed.

**Comment by Dmitry-Ostashev** [comment]
Thank you for your report. I've reproduced this issue. We'll research it and notify you as soon as we have any results.

**Comment by znar** [comment]
Hello, i think we are running into the same issue.
Our page is rendered on the server side and there is no css which hides the element.
But sometimes the element cant be clicked because testcafe says its not visible.
if i run testcafe with --debug-on-fail and open the browsers debug console and search it via querySelector i can find it.
That bug occurs randomly if i run the tests concurrently.
But what all failing tests have alike is that the elelements are at the bottom of the page.

We are using the newest version of testcafe 1.11.0

**Comment by AlexanderMoiseev** [comment]
Hello @znar

Currently, the webpage from the original message by @ZaPaw does not work. Please send us an example project so we can reproduce the issue.
