### ISSUE TITLE
Composable selectors

### ISSUE THREAD

**Issue by DavidSampson** [DevExpress/testcafe#4765]
### What is your Test Scenario?
It is often necessary to find related elements of a particular selector that match certain criteria. Currently we have `.find()`, `.filter()`, `.child()`, `.parent()`, etc. These take a CSS selector string, or a filter function, or sometimes another value, but *not* a TestCafe Selector.
```javascript
await t.expect(Selector('.card').parent(Selector('div')).exists).ok();
```
Yields: 
```
ERROR Cannot prepare tests due to an error.

find code is expected to be specified as a function, but string was passed.
```

### What are you suggesting?
In the interest of not repeating oneself, it would be incredibly useful to be able to use TestCafe Selectors as arguments to filtering and searching methods that already take CSS selector strings. This is especially handy in the context of the Page model:
```javascript
class Post {
  constructor(){
    this.title = Selector('.post-title')
    this.el = Selector('.post');
    this.starred = Selector('.post-status').withText('Starred!');
  }
}
let post = new Post();
class HomePage {
  constructor(){
    this.recentPosts = Selector('.recent-posts');
    this.favoriteNewPosts = this.recentPosts.find(post.starred).parent(post.el);
  }
}    
```
### What alternatives have you considered?

The main alternative is either to store CSS selector strings and pass those around, which doesn't work if you need the functionality of `.withText()` or similar (and defeats the purpose of having TestCafe Selectors), or to repeat the logic used to select in each location (`this.favoriteNewPosts = this.recentPosts.find('.post-status').withText('Starred!').parent('.post')`), which breaks encapsulation and makes changes more difficult.

**Comment by AlexKamaev** [comment]
Thank you for your input. We'll take it into account.
