### ISSUE TITLE
I can't execute an `expect` with my own Promise without awaiting

### ISSUE THREAD

**Issue by stefanschenk** [DevExpress/testcafe#4767]
If I look at some TestController properties / methods from TestCafe, they all return a promise, eg.

`SelectorAPI.count: Promise<number>`
`SelectorAPI.visible: Promise<boolean>`

The `expect` method can accept `actual: A | Promise<A>`. 

If I run my script and I have `t.expect(x.count).eql(#)`, the assertion is perfectly executed so it handled the promise of count.

However if I run expect with on my own method which returns a promise, I get an error. eg.

`myCount: Promise<number> = new Promise(resolve => resolve(4))`

But now, when I run `t.expect(myCount).eql(4)` I get the following exception:

```
Attempted to run assertions on a Promise object. Did you forget to await it? If not, pass "{ all
owUnawaitedPromise: true }" to the assertion options.
```

And I know, running `t.expect(await myCount).eql(4)` will execute fine, but it is weird that the expect function can accept promises, but only promises from the testcontroller and not my own created promises.

Could someone please elaborate on this functionality and why expect cannot handle all promises?

 
### Your Environment details:
 
* testcafe version:                   1.8.1
* node.js version:                    12.13.1

**Comment by Dmitry-Ostashev** [comment]
By default, only Selector and ClientFunction promises can be passed as the assertion's actual value. You can use the [allowUnawaitedPromise](https://devexpress.github.io/testcafe/documentation/test-api/assertions/#optionsallowunawaitedpromise) option to assert your own Promise.

**Comment by stefanschenk** [comment]
@Dmitry-Ostashev I don't know why you closed this issue. I know only certain types work, my question is why other promises are not able to work (without adding await or a assertionOption).

If you look at the types, `.count(x)` returns a normal promise, nothing special. So again my question. Why not handle all promises natively without some ugly option.

**Comment by stefanschenk** [comment]
Just an example:

Simple promise property:
`const myCount: Promise<number> = new Promise(resolve => resolve(4));`

Without any await or assertion options you get the error
```
Attempted to run assertions on a Promise object. Did you forget to await it? If not, pass "{ allowUnawaitedPromise: true }" to the assertion options.
```

I add the assertion option:
`await t.expect(myCount).eql(4, { allowUnawaitedPromise: true });`

Then I get the following result:
`AssertionError: expected {} to deeply equal 4`

So the allow unawaited promise option does not resolve the unawaited promise. I don't really know what this option has done at this moment.

**Comment by alexey-lin** [comment]
Hi @stefanschenk,

When `expect` receives Selector or ClientFunction as an actual value, it calculates it using the [Smart Assertion Query Machanism](https://devexpress.github.io/testcafe/documentation/test-api/assertions/#smart-assertion-query-mechanism). In the case of your custom promise, this approach is obviously not applicable.

What are you trying to achieve when you pass a promise as an actual value? Do you want it to be awaited and its result to be checked? If so, you need to add `await`. If you want the promise object to be examined, use the `allowUnawaitedPromise` option.
