### ISSUE TITLE
A call to an async function is not awaited. Use the "await" keyword before actions, assertions or chains of them to ensure that they run in the right sequence.

### ISSUE THREAD

**Issue by Srihari88** [DevExpress/testcafe#4772]
### What is your Test Scenario?

My Testcase
   test('As a User I can able to create a deck to enter all valid information', async t => {

        await LoginToApplication('abcd','abcd')
        await CreateFlashcard()
        await CreateDeckWithValidDetails('Automation','FrontName', 'BackName');
        await VerifyTheDeck()

    });

My Methods below:
 export async function CreateDeckWithValidDetails(NameOftheDeck,frontCard,backCard){

        await t.click(browser.Create_Deck_name)
              t.typeText(browser.Enter_deck_name,NameOftheDeck)
              t.typeText(browser.Deck_fornt_side, frontCard)
              t.typeText(browser.Deck_back_side, backCard)
              t.click(browser.Done_button)
    };

   export async function LoginToApplication(email,pass) {
 
        await t.maximizeWindow()
              t.click(browser.Login_Button);
              t.typeText(browser.Enter_Email, email);
              t.typeText(browser.Enter_Password, pass);
              t.click(browser.Submit_Button);
    };

   // After login the user click on the crete flashcard button
    export async function CreateFlashcard(){

        await t.click(browser.Create_Flashcard)
    };
 --> 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
A call to an async function is not awaited. Use the "await" keyword before actions, assertions or chains of them to ensure that they run in the right sequence.

       Browser: Chrome 79.0.3945.130 / macOS 10.14.6

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by AlexKamaev** [comment]
I think there is a typo in your code:

**Comment by AlexKamaev** [comment]
I think there is a typo in your code:
```JS
    await t.click(browser.Create_Deck_name)
          t.typeText(browser.Enter_deck_name,NameOftheDeck)
          t.typeText(browser.Deck_fornt_side, frontCard)
          t.typeText(browser.Deck_back_side, backCard)
          t.click(browser.Done_button)
```
As far as I understand, you want to call these methods in chain. In this case you need to remove the `t` variable before calling the methods.
Please see the following code:
```JS
    await t.click(browser.Create_Deck_name)
          .typeText(browser.Enter_deck_name,NameOftheDeck)
          .typeText(browser.Deck_fornt_side, frontCard)
          .typeText(browser.Deck_back_side, backCard)
          .click(browser.Done_button)
```
Or, if you do not want to chain the methods, you can write the test as follows:
```JS
    await t.click(browser.Create_Deck_name)
    await t.typeText(browser.Enter_deck_name,NameOftheDeck)
    await t.typeText(browser.Deck_fornt_side, frontCard)
    await t.typeText(browser.Deck_back_side, backCard)
```
