### ISSUE TITLE
Starting browser with arguments does not work in macos

### ISSUE THREAD

**Issue by mattdeckard** [DevExpress/testcafe#4773]
### What is your Test Scenario?
Any test scenario, doesn't matter.
Launch in `zsh` with command line arguments:
```
testcafe 'chrome --window-size=1400,800' *.spec.js
```
(per [TestCafe's documentation](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#starting-browser-with-arguments), enclosing the browser call and its arguments in single quotation marks
 
### What is the Current behavior?
```
ERROR Unable to find the browser. "800" is not a browser alias or path to an executable file.

Type "testcafe -h" for help.
```

### What is the Expected behavior?
I would expect it to launch Chrome with the arguments `--window-size=1400,800`.
 
### What is your web application and your TestCafe test code?
This behavior is not dependent on the application or test code, it's the command line interface itself.

### Steps to Reproduce:

1. Open a `zsh` shell in macos (its possible this happens in other unix-ish environments as well, I've just only tested in macos)
3. Execute this command: `testcafe 'chrome --window-size=1400,800' *.spec.js
4. See the error described above
 
### Your Environment details:
 
* testcafe version:                   1.7.1
* node.js version:                    v10.17.0
* command-line arguments:  testcafe 'chrome --window-size=1400,800' *.spec.js
* browser name and version: Chrome 80
* platform and version:          macOS 10.14.6
* other:                                   N/A

**Comment by AlexKamaev** [comment]
I was able to reproduce the issue. We already were reported about a similar problem in the context of the [https://github.com/DevExpress/testcafe/issues/3456](https://github.com/DevExpress/testcafe/issues/3456) issue.
Please try running testcafe using the following command exactly with the same quotes: `testcafe "chrome --window-size-'400,400'"`. Let us know your results.
