### ISSUE TITLE
why can't I see the window.alert()??

### ISSUE THREAD

**Issue by juuuuuuuuuuuuuu** [DevExpress/testcafe#4774]
In my code, when I press the button, the window.alert pops up.
but the testpage doesn't showing the dialog.
I use window.alert() , but testpage is not working.

  await t
    .setNativeDialogHandler(() => true)
    .click(button)
});

**Comment by AlexSkorkin** [comment]
Thank you for your interest in our testing tools. You are welcome to ask any TestCafe related questions on StackOverflow (https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions. If you think that you found a bug, feel free to open a new issue in the GitHub repo https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md). Thank you in advance.
