### ISSUE TITLE
Page with ads from prebid.js is not loading through testcafe

### ISSUE THREAD

**Issue by darekodz** [DevExpress/testcafe#4783]
I need to test page with ads from the prebid.js, here is my working test page:
http://dev.testcommon.insideall.com/gmc/test-marieclaire.html?pbjs_debug=true -> you should see blue ads.

When I use testcafe the page is loading very slow, and finally not all ads are displayed.
test
	.page('http://dev.testcommon.insideall.com/gmc/test-marieclaire.html?pbjs_debug=true')

The important thing is to have a different host for the testcafe server (ads cannot be served from localhost), e.g. I am using 
createTestCafe('example.com', 1337, 1338)
in my runner.js file

The problem is partially explained here:
https://stackoverflow.com/questions/52745697/requestlogger-not-intercepting-all-http-requests 

Are you able to fix it?

**Comment by LavrovArtem** [comment]
Hello,
Could you specify your TestCafe version? I tried to run the test below and everything works as expected.

```js
fixture `Page with ads from prebid.js is not loading through testcafe`
    .page `http://dev.testcommon.insideall.com/gmc/test-marieclaire.html?pbjs_debug=true`;

test('Load ads', async t => {
    await t.debug();
});
```

* testcafe version: `v1.8.2`
* node.js version: `v12.4.0`
* command-line arguments: `testcafe chrome test.js`
* browser name and version: `Chrome 79`
* platform and version: `Windows 10`


Would you please provide more information about this issue?

**Comment by darekodz** [comment]
Hi Artem,
Thanks for your feedback. I have almost the same configuration as you. Seems there was an issue on my computer side - I rebuilt again the project by yarn (before I used npm) and it started to work as expected.
Sorry for the mess - this ticket can be closed.

**Comment by AlexSkorkin** [comment]
@darekodz, 
Thank you for the update. I'm happy to hear that you have figured out how to resolve the issue.
