### ISSUE TITLE
Redesign test run UI

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#479]
Implement status bar at the bottom of the page which will replace `Loading page...` screen and waiting element modal popup and add additional test run info. Status bar will become nearly completely opaque on hover (if you want to observer the page below it):
![image](https://cloud.githubusercontent.com/assets/453071/14787216/282e6cc6-0b0b-11e6-8451-7066799f373a.png)

**Comment by helen-dikareva** [comment]
![status-bar](https://cloud.githubusercontent.com/assets/12034551/15645841/688c4a04-2663-11e6-97f2-0b86ff4c833c.png)

Designer proposed to implement status indicator similarly like in google-design
https://www.google.com/design/spec/components/progress-activity.html

What do you think?

**Comment by inikulin** [comment]
I like it. I guess we will use determinate indicator for elements waiting and indeterminate  for page loads.

**Comment by AlexanderMoskovkin** [comment]
I like it too

**Comment by helen-dikareva** [comment]
Last question about appearance when just test in progress. 
Should we show grey line instead of progress bar? I think no.
What about text: "Test in progress..." ?

**Comment by inikulin** [comment]
> Should we show grey line instead of progress bar?

What guide lines tell about?

**Comment by VasilyStrelyaev** [comment]
Why not?
`Test in Progress...` if we use title capitalization. I'm not sure...
Compare:
`Test in Progress...` `Loading Web Page...`
`Test in progress...` `Loading web page...`

After all, Google suggests that we use sentence capitalization everywhere except buttons. Which is the most common practice nowadays, from what I notice.

**Comment by VasilyStrelyaev** [comment]
And yeah, no bar for test in progress

**Comment by VasilyStrelyaev** [comment]
> After all, Google suggests that we use sentence capitalization everywhere except buttons.

Apple doesn't, but...
![image](https://cloud.githubusercontent.com/assets/11459924/15649303/32b1ca2e-2679-11e6-92f9-081cbd5372ea.png)

I don't like being addressed by a Title
