### ISSUE TITLE
Expose timing information for debugging

### ISSUE THREAD

**Issue by Raynos** [DevExpress/testcafe#4795]
It would be great if `testcafe` can expose timing information for the test run. Currently my testcafe tests take quite a long time and I suspect that there are low hanging fruit that can speed up the tests quite a bit.

It would be great if I could ask testcafe for a report of the time that everything took.

I've found a third party library ( https://github.com/jimthedev/timecafe ) but that's not quite what I am looking for.

### What is your Test Scenario?

Running my tests with `DEBUG=testcafe:* testcafe ...` prints pretty much every single command send to the test runner in the browser.

### What are you suggesting?

Show me timing information for the command send to the browser, including which ones are slow / medium / fast, as well as total times per test.

### What alternatives have you considered?

Using a third party library like `timecafe` or contributing it myself.

**Comment by Raynos** [comment]
If there is a blog post about timing & fast tests with testcafe that I can read instead then that would be cool too.

**Comment by Raynos** [comment]
BTW; one of the low hanging fruit that I am pretty certain of is the builtin timeout for clicking an element if its "not visible" ; for some reason my CSS tricks testcafe into waiting for an "animation" to complete before clicking it anyway.

**Comment by AlexSkorkin** [comment]
Thank you for reaching out to us and submitting your feature request. Right now, there's no functionality to display timing information for test cases. We will work on this functionality in the context of the "[More verbose output about actions and assertions](https://github.com/DevExpress/testcafe/issues/4001)" thread.

**Comment by Raynos** [comment]
Seems reasonable.
