### ISSUE TITLE
Document supported browser versions matrix with each release

### ISSUE THREAD

**Issue by ciarancourtney** [DevExpress/testcafe#4798]
### What are you suggesting?
Each release of testcafe should be tested against a matrix of major browser versions, as new ES2020+ features are used, older browsers can be dropped as long as its made explicit in release notes and the benefit of new features/perf improvements outweighs legacy support. Users required to support these dropped versions can run the previous version of testcafe using npx for example `npx testcafe@1.2.1 remote e2e/tests/`

* I understand tests are run in BrowserStack, is it possible to see the browser matrix and results for each release/commit?

* Does local/remote matter?

* Are there any tools that can help build a matrix of browser support by scanning the build output and perhaps querying caniuse.com?

### What alternatives have you considered?
Maintaining annual snapshot of `package-lock.json` files with approximate browser versions of era known to work

### Additional context

Some users cannot always assume the 'latest' browser version at time of dev e.g.:
* Kiosks
* Corporate environments
* Older Android webview

The closest reference I can find to supported versions is in https://github.com/DevExpress/testcafe/issues/1628#issuecomment-316745478 from 2017.

From the browser-support.md [git blame](https://github.com/DevExpress/testcafe/blame/master/docs/articles/documentation/using-testcafe/common-concepts/browsers/browser-support.md) I can infer that IE support was bumped from 9 to 11 in v0.20, perhaps indicating minimum ES2015+ changes roughly around this point.

For extra context, I opened this issue because I'm hitting a console error after adding a remote Chrome v48 to my test farm. FYI I'm using recent testcafe (v1.8.1)

    Cannot read property 'call' of undefined        hammerhead.js:1
    Cannot read property 'body' of undefined        hammerhead.js:3

I've tried reverting Testcafe all the way back to v0.0.22 without luck, its difficult to know what sub-dependancy introduced the break (hammerhead I'm assuming in this case), some are pinned 'exact', some aren't.

IE10 also doesn't work, which I would have expected to work as its pre v0.20. IE11 works fine.

**Comment by Farfurix** [comment]
Hello, @ciarancourtney.

> I understand tests are run in BrowserStack, is it possible to see the browser matrix and results for each release/commit?
> Are there any tools that can help build a matrix of browser support by scanning the build output and perhaps querying caniuse.com?

We cannot compose the "full browser support" matrix. Our code base has some conditions that represent a particular browser version but all new issues are addressed in the context of the latest browser version. It means that any current fix may not be a valid solution for some older browser versions.

> Users required to support these dropped versions can run the previous version of TestCafe using npx for example npx testcafe@1.2.1 remote e2e/tests/

Even if you can find all specific TestCafe versions for each required browser version, you may encounter the following:
1. Bugs of older browsers versions may be detected.
2. You cannot use the latest features.
3. You will need to take into account all breaking changes.
