### ISSUE TITLE
Not able to create extension method off Selector

### ISSUE THREAD

**Issue by jenaewhitmore** [DevExpress/testcafe#4800]
When trying to create extension methods of Selector for the TestController methods, I get an error that it is not a function

### What is your Test Scenario?
I would like to call actions off Selectors instead of passing in selectors to actions. i.e. 
```ts
let element = Selector("#id);
element .click();
element.dobuleClick();
....
```
 
### What is the Current behavior?
I get an error "..is not a function"
 
### What is the Expected behavior?
I should be able to create extension methods off Selector
 
### What is your web application and your TestCafe test code?
Test Application for trying out testCafe 
 
<details>
<summary>Your website URL (or attach your complete example):</summary>
http://www.practiceselenium.com
</details>

<summary>Your complete test code (or attach your test files):</summary>

```ts
import { Selector, t as controller } from 'testcafe';
declare global {
    interface Selector{
        Click(): TestController;
    }
}
Selector.prototype.Click = function(): TestController{
    return controller.click(Selector(this));
}
export{};
```
**ALSO TRIED**

```ts
import { Selector, t as controller } from 'testcafe';
declare global {
    interface Selector{
        Click(): TestController;
    }
}
Selector.prototype.Click = function(this: Selector): TestController{
    return controller.click(this);
}
export{};
```
**PAGE OBJECT**
```ts
mport { BasePageObject } from 'testcafe-tools';
import { MenuPage } from './MenuPage';
import './Extensions';

export class HomePage extends BasePageObject{

private herbalTeaLink = this.Select("#wsb-button-00000000-0000-0000-0000-000450914890");

public async ClickHerbalTea(): Promise<MenuPage>{

    await this.herbalTeaLink.Click();
    return new MenuPage();
}

}
```
**TEST**
```ts
mport { HomePage } from '../PageObjects/HomePage';
import { MenuPage } from '../PageObjects/MenuPage';
import { CheckOutPage } from '../PageObjects/CheckOutPage';
import {t as controller} from 'testcafe';

test('Can I get to Check out page', async controller =>{
let homePage: HomePage =  new HomePage();
let menuPage: MenuPage = await homePage.ClickHerbalTea();
let checkOutPage: CheckOutPage =  await menuPage.CheckOutGreenTea();

await controller.expect(checkOutPage.PageTitle).eql("Check Out").
          expect(checkOutPage.PageUrl()).eql("http://www.practiceselenium.com/check-out.html");
});
```
<details>
<summary>Your complete configuration file (if any):</summary>

   "browsers": "chrome:headless", 
    "src": "tests/**",
    "skipJsErrors": true, 
    "reporter": [
        {
            "name": "spec"
        },
        {
            "name": "xunit",
            "output": "report.xml"
        }
    ]
</details>

<details>
<summary>Your complete test report:</summary>

```
× Can I get to Check out page

   1) TypeError: this.herbalTeaLink.Click is not a function

      Browser: Chrome 79.0.3945.130 / Windows 10

          6 |
          7 |private herbalTeaLink = this.Select("#wsb-button-00000000-0000-0000-0000-000450914890");
          8 |
          9 |public async ClickHerbalTea(): Promise<MenuPage>{
         10 |
       > 11 |    await this.herbalTeaLink.Click();
         12 |    return new MenuPage();
         13 |}
         14 |
         15 |}
         16 |

         at HomePage.<anonymous> (D:\Git\SeleniumTools\TestCafeSample\PageObjects\HomePage.ts:11:30)
         at <anonymous> (D:\Git\SeleniumTools\TestCafeSample\PageObjects\HomePage.ts:8:71)
         at __awaiter (D:\Git\SeleniumTools\TestCafeSample\PageObjects\HomePage.ts:4:12)
         at HomePage.ClickHerbalTea (D:\Git\SeleniumTools\TestCafeSample\PageObjects\HomePage.ts:21:16)
         at <anonymous> (D:\Git\SeleniumTools\TestCafeSample\tests\SampleTest.ts:49:29)
         at Function.And (D:\Git\SeleniumTools\TestCafeSample\node_modules\gherkin-executor-typescript\lib\GherkinArrange.js:8:16)
         at <anonymous> (D:\Git\SeleniumTools\TestCafeSample\tests\SampleTest.ts:47:10)
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.8.1
* node.js version:                    13.1.0
* command-line arguments:  test
* browser name and version: Version 79.0.3945.130 (Official Build) (64-bit)
* platform and version:          Windows 10 Pro v.1909 OS18363.657 64bit
* other:

**Comment by AlexSkorkin** [comment]
Thank you for your inquiry.
This issue looks like a question on JavaScript inheritance that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.
We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafeontributing)).
