### ISSUE TITLE
Click problem 

### ISSUE THREAD

**Issue by Turkirafaa** [DevExpress/testcafe#4806]
### What is your Test Scenario?

I am trying to click in dashboard card when i use click command its redirecting to the same dashboard its not going further
 
### What is the Current behavior?
ts redirecting to the same dashboard
 
### What is the Expected behavior?
It should come in to dashboard material
 
### What is your web application and your TestCafe test `code?

 
```async function CourseExplore(baseUrl) {
    await t 
           .navigateTo(baseUrl)
           .click(Selector('div > carousel-card:nth-child(1)'))
           .expect(Selector('.courses-create-course-card-content').exists).ok()
           .expect(Selector('.course-explore-material').exists).ok()

} 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```
![Skärmavbild 2020-02-25 kl  09 51 33](https://user-images.githubusercontent.com/32999333/75231720-37336180-57b6-11ea-93d0-7de7753954d3.png)


```
</details>

### Your Environment details:
Web app 
 
* testcafe version:  1.8.2                
* node.js version:  12.16.1

**Comment by Turkirafaa** [comment]
<carousel-card class="carousel-card-container ng-scope ng-isolate-scope" material="userMaterial" ng-repeat="userMaterial in $ctrl.userMaterials track by $index" on-card-click="$ctrl.onCardClick({card: userMaterial})"><a href="courses/114" class="carousel-card" target=""><div class="image-container"><div class="carousel-card-image" ng-class="{'carousel-card-image-coming-soon': $ctrl.material.underConstruction }" ng-style="::$ctrl.getCardImage()" style="background-image: url(&quot;https://laromedel.ne.se/assets/ne/image/2018.09.05.10.32.41_original_115454.jpg&quot;);"></div></div><div class="carousel-card-text-container"><span class="carousel-card-title ng-binding" ng-bind-html="$ctrl.material.materialTitle">Biologi 1</span> </div></a></carousel-card>

**Comment by alexey-lin** [comment]
Hi @Turkirafaa,

I'm afraid, this information is not sufficient to reproduce the issue. Could you please provide us with a public URL or with sample code reproducing the issue? We need to reproduce this behavior to understand what causes it.
