### ISSUE TITLE
Provide the capability to access browser information from test code

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#481]
Make browser information available in the test controller - add the `t.browserInfo` property.

There are various use cases for this feature, including conditional test actions and assertions:

```js
test('My Test', async t => {
    if(t.browserInfo.name === 'IE')
        await t.click('#some-div');
});
```

**Comment by AlexanderMoskovkin** [comment]
It would be useful to add a concurrent worker number to the `browserInfo` (initially proposed in the #1778)

**Comment by dlangerenken** [comment]
are there any updates on this? any planned release date? @AndreyBelym

**Comment by AndreyBelym** [comment]
We have plans to implement this feature, but I can't give you an estimate yet. As a workaround, you can retrieve the `navigator.userAgent` property via a `ClientFunction` and then parse it using a third-party module (`useragent`):
```
import { ClientFunction } from 'testcafe';
import useragent from 'useragent';

fixture `get ua`
    .page `http://example.com`;

const getUA = ClientFunction(() => navigator.userAgent);

test('get ua', async t => {
    const ua = await getUA();

    console.log(useragent.parse(ua).family);
});
```
