### ISSUE TITLE
My electron-app (uses 'trilogy' library)  got a syntax error when i test it with testcafe  

### ISSUE THREAD

**Issue by 1500mh** [DevExpress/testcafe#4811]
### What is your Test Scenario?
 electron on windows 10.
 
### What is the Current behavior?
 electron'render process works abnormal,because it have a blank dom tree.
 
### What is the Expected behavior?
Tests should start successfully.
 
### What is your web application and your TestCafe test code?
It can be reproduced with any app which uses 'trilogy' library.

```js
import { connect } from 'trilogy';

const db = connect('./test.db', {
  client: 'sqli.js'
});

(async function () {
  const foo = await db.model('games', {
    name: { type: String },
    type: String
  })
  await foo.create({
    name: '111',
    type: 'FPS'
  })
})()
```
errors on the Dev-tool:
```js
// error location:  E:\code\erb-testcafe-example\app\node_modules\trilogy\dist\index.js:425
//  422 beforeCreate(...args) {
//  423    if (args.length === 2) {
//  424       const [ __get$Loc(location), fn] = args;
//  425     return this.getModel( __get$Loc(location)).beforeCreate(fn);
//  426 }

Uncaught SyntaxError: Unexpected token (  
    at createScript (vm.js:80)
    at Object.runInThisContext (vm.js:139)
    at Object.runInThisContext (hammerhead.js:2)
    at Module._compile (module.js:606)
    at Object.Module._extensions..js (module.js:653)
    at Module.load (module.js:561)
    at tryModuleLoad (module.js:504)
    at Function.Module._load (module.js:496)
    at Module.require (module.js:586)
    at require (internal/module.js:11)
```
### Steps to Reproduce:
1、 add code uses 'trilogy' to any electron app
2、 start test 
 
### Your Environment details:
 
* testcafe version:                   0.20.4
* node.js version:                    12.11
* command-line arguments:  testcafe electron:./app ./test/e2e/HomePage.e2e.js --debug-on-fail
* browser name and version: electron 2.0
* platform and version:         windows 10

**Comment by Dmitry-Ostashev** [comment]
I was unable to reproduce this issue on my side. Could you please attach a complete example illustrating this behavior?

**Comment by 1500mh** [comment]
Thank's for your reply, to reproduce this error you can follow this steps:
1、clone example code
```bash
git clone https://github.com/amilajack/erb-testcafe-example.git
yarn
```
2、add code to `app/components/Counter.js`
```js
import { connect } from 'trilogy';

const db = connect('./test.db', {
  client: 'sql.js'
});

(async function testdb() {
  const foo = await db.model('games', {
    name: { type: String },
    type: String
  })
  await foo.create({
    name: '111',
    type: 'FPS'
  })

})()
```
3、install trilogy and sql.js module by yarn
```bash
cd app && yarn add trilogy sql.js
```
4、run test scripts
```bash
yarn build-e2e
yarn test-e2e
```

**Comment by Farfurix** [comment]
@1500mh 

Hello,

I was able to reproduce this issue. We need some time to examine your project. Please stay tuned to our updates in this thread.

**Comment by miherlosev** [comment]
Hi @1500mh 

The script error is not reproduced with the latest TestCafe version (`1.9.1`). 
Try to update TestCafe related modules to the followings versions:
```js
"testcafe": "^1.9.1",
"testcafe-browser-provider-electron": "0.0.15",
"testcafe-react-selectors": "^4.0.0",
```
and let us know about your results.

**Comment by 1500mh** [comment]
Yes, testcafe(1.9.1) resolve my problem.
