### ISSUE TITLE
Document how to enable pop-up windows for Safari

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#4815]
https://www.technipages.com/safari-popup-blocker

Also, we can try to check a status of the pop-up window  blocking for Safari before test running.

**Comment by DIRECTcut** [comment]
waits for #912

**Comment by miherlosev** [comment]
The [Multiple Browser Windows](https://testcafe.io/documentation/402841/guides/intermediate-guides/multiple-browser-windows) feature is not implemented in Safari. So, it's not possible to accomplish this task.
