### ISSUE TITLE
Cannot resolve `.tsx` files

### ISSUE THREAD

**Issue by rbardini** [DevExpress/testcafe#4817]
Support for custom TypeScript compiler options was added in https://github.com/DevExpress/testcafe/pull/3882, but TestCafe seems to restrict TypeScript files to `.ts` only:

https://github.com/DevExpress/testcafe/blob/5b4979d60ced70c54e7e331847c60d90ec8be3cb/src/compiler/test-file/formats/typescript/compiler.ts#L145-L147

This means I cannot write tests to `.tsx` files or import from them, which was one of my main reasons to upvote custom compiler options: https://github.com/DevExpress/testcafe/issues/1845#issuecomment-497704566.

I suppose we could add support for multiple file extensions per compiler and return both `.ts` and `.tsx` from the TypeScript one. I can submit a PR if that's the case.

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. It can be a useful feature, but could you please add more details about your use case? Also, I doubt if we can execute a compiled JSX/TSX code outside of a React context.

**Comment by rbardini** [comment]
Hi @AndreyBelym. We use `.tsx` for all TypeScript files in our codebase, not only those containing JSX. The reasoning behind this is summed up in https://github.com/Microsoft/TypeScript-React-Starter/issues/4#issuecomment-301336690:

> It was just simpler to stick with TSX files across the board instead of involving users with this explanation. If you know the difference, that's great and you should feel free to use `.ts` when JSX isn't used, but in the end `.ts` files will always be able to interface with `.tsx` files anyway.

The difference being that TypeScript disallows angle bracket type assertions in `.tsx` files, as it conflicts with JSX grammar (which doesn't mean a `.tsx` file _must_ have JSX inside).

Since TestCafe restricts TypeScript files to `.ts` only, we have to make an exception for it, but also change the extension of any project-specific TypeScript file imported from fixtures (e.g. types, mocks, helpers).

**Comment by aleks-pro** [comment]
Hi  @rbardini ,

Thank you for the clarification. We will consider adding this functionality in the future. You are always welcome to submit a PR for this feature.

**Comment by benmonro** [comment]
I could use this feature as well.  Cypress has this library (see link below) and I was trying to write the same thing for testcafe but ran into the same problem with JSX.

https://github.com/bahmutov/cypress-react-unit-test

**Comment by Dmitry-Ostashev** [comment]
@benmonro Thank you for your comment. We'll take your scenario into account.

**Comment by benmonro** [comment]
@Dmitry-Ostashev Thank you!  I want to underscore that this could be a HUGE win for testcafe.  This would open many doors to be able to write unit & integration tests in testcafe:

* visual testing of JSX components (using tools like Applitools, percy, etc) 📸
* A11y testing of JSX components ♿️
* cross browser unit tests 🤯

**Comment by rbardini** [comment]
I want to point out that, even though I agree supporting JSX would be great, I opened this issue merely to include `.tsx` files besides `.ts` for compilation, regardless of JSX usage. The `.tsx` extension was introduced to disallow angle bracket type assertions and avoid ambiguities with JSX's syntax, but JSX is not a requirement for using `.tsx` files. In fact, our codebase uses `.tsx` for everything, but TestCafe doesn't resolve these files.

If supporting JSX is much more complex than just `.tsx` files without the `jsx` option, it might be a good idea to open a separate issue for JSX compilation 🙂

**Comment by benmonro** [comment]
I suspect they are probably linked.  For me I definitely need actual JSX in test code.  This could potentially even replace jest and we would only use testcafe as our sole test runner.

**Comment by AlexKamaev** [comment]
@benmonro
I think it is better to extract your suggestion into a separate issue since your task looks quite complex and may require further discussion.
