### ISSUE TITLE
Node-forge test is not working

### ISSUE THREAD

**Issue by vsorrokin** [DevExpress/testcafe#4823]
I have created simple code with node-forge lib which generates key pair (I use this lib in my project). The code works fine but when I try to run testcafe test it fails with console error "prime.worker.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)" – I know that it is node-forge lib error but the code works fine out of testcafe environment. I have created git repo with error to reproduce https://github.com/vsorrokin/testcafe-bugs. I have tested the code in testcafe-hammerhead also and it works fine within your proxy.

### What is your Test Scenario?
Node-forge keyPair generation
 
### What is the Current behavior?
Works out of testcafe env and fails in testcafe
 
### What is the Expected behavior?
Works same way in both cases
 
### What is your web application and your TestCafe test code?
https://github.com/vsorrokin/testcafe-bugs
 
<details>
<summary>Your website URL (or attach your complete example):</summary>

```html
 <!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Testcafe</title>
    <script src="https://cdn.jsdelivr.net/npm/node-forge@0.7.0/dist/forge.min.js"></script>
  </head>
  <body>
    <div id="message"></div>

    <script>


      var t0 = performance.now();

      forge.pki.rsa.generateKeyPair({bits: 4096, workerScript: ''}, function(err, pair) {
        var t1 = performance.now();

        document.querySelector('#message').textContent = `Pair generated. Time: ${t1 - t0}ms`;
      });

    </script>
  </body>
</html>
```
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from 'testcafe';

fixture `node-forge`
  .page `127.0.0.1:8001`;

test('Generate pair', async t => {

  await t
    .expect(Selector('div').withText('Pair generated').exists).ok();

});

```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```
$ testcafe chrome ./test --debug-on-fail
 Running tests in:
 - Chrome 80.0.3987.122 / macOS 10.15.1

 node-forge

----
Chrome 80.0.3987.122 / macOS 10.15.1
DEBUGGER PAUSE ON FAILED TEST:
AssertionError: expected false to be truthy

Browser: Chrome 80.0.3987.122 / macOS 10.15.1

4 |  .page `127.0.0.1:8001`;
5 |
6 |test('Generate pair', async t => {
7 |
8 |  await t
>  9 |    .expect(Selector('div').withText('Pair generated').exists).ok();
10 |
11 |});
12 |

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Clone my repo https://github.com/vsorrokin/testcafe-bugs
2. Install deps with yarn
3. Run static server with yarn start
4. Make sure that code works fine - open localhost:8001 in your browser
5. Run test with yarn test and you will see error
 
### Your Environment details:
 
* testcafe version:                   1.8.2
* node.js version:                    12.13.1
* command-line arguments:  testcafe chrome ./test --debug-on-fail
* browser name and version: Chrome 80.0.3987.106
* platform and version:          macOS 10.15.1

**Comment by Farfurix** [comment]
@vsorrokin

Hello,

Thank you for the complete example. I reproduced it under Windows 10 / Chrome 80 and I confirm than there is no issue if I run the project in our `testcafe-hammerhead` proxy. We will examine your case and check for a suitable solution.

**Comment by vsorrokin** [comment]
Problem was in crypto.subtle because it is accessible in secure context only or on localhost. So to resolve the problem need to run testcafe with --hostname=localhost or use --ssl option.
