### ISSUE TITLE
Configuration file: consider using confinode

### ISSUE THREAD

**Issue by sveyret** [DevExpress/testcafe#4824]
### What is your Test Scenario?

Using a configuration file for _TestCafé_ is a bit “restrictive” as there can be only a single name and a single format.

### What are you suggesting?

I suggest you to use [confinode](https://www.npmjs.com/package/confinode) which would manage the configuration file for you. This would bring some advantages which would at least answer to #3428 and #3136:

- create _JavaScript_ and _TypeScript_ configuration files, in which real configuration could be selected using environment variable;
- use indirection to ease this process;
- use inheritance to create a common parent configuration file and where real configuration files only override some values;
- many more…

### Additional context

I am the author of _confinode_ and try to make it being a bit known to Node.js community. So if you have any question or need help (or a PR), do not hesitate and ask me.

Whether you want to use the library or not, I'd really appreciate if you tell me why.

**Comment by Farfurix** [comment]
@sveyret 

Hello,

Thank you for this information. We will take it into account when considering all possible ways to implement this feature. Currently, I cannot provide you with any estimates. I will close this issue in favor of #3428 and #3136.
