### ISSUE TITLE
Testcafe doesn't load certain sites, results in about:error

### ISSUE THREAD

**Issue by elimence** [DevExpress/testcafe#4833]
### What is your Test Scenario?
I'm running a simple test on a specific website
 
### What is the Current behavior?
After testcafe connects to the browser, it fails to load the page.
I see an "about:error" in the network logs
 
### What is the Expected behavior?
Load webpage and continue test
 
### What is your web application and your TestCafe test code?
https://github.com/elimence/testcafe-sample

Works as expected for the commented-out origin, but not the currently set.
 
<img width="1122" alt="Screen Shot 2020-03-02 at 2 22 28 PM" src="https://user-images.githubusercontent.com/2939919/75672861-b29f8200-5c92-11ea-87a7-1fd0363cbe74.png">

### Your Environment details:
 
* testcafe version:                   1.8.2
* node.js version:                    v13.2.0
* command-line arguments:  testcafe chrome test.js --debug-on-fail
* browser name and version: chrome 80
* platform and version:          macOS 10.15.3

**Comment by Dmitry-Ostashev** [comment]
I checked your example and found that the side produces a response header with an incorrect char. This issue looks like a duplicate of [https://github.com/DevExpress/testcafe-hammerhead/issues/2188](https://github.com/DevExpress/testcafe-hammerhead/issues/2188). You can refer to that thread and try to use a workaround described there.

**Comment by elimence** [comment]
@Dmitry-Ostashev  Indeed, I did a quick check with node lts/carbon and the page loaded successfully.
I'll close this now and take a look at the linked issue.
Thanks 👍
