### ISSUE TITLE
How to perform E2E login process and navigate to homepage

### ISSUE THREAD

**Issue by valerxx22** [DevExpress/testcafe#4836]
I'm using `testcafe` in an `Electron-React` app trying to integrate some basic `e2e tests`.

The test works, however they are not relevant.  

I would like to know, how can I **pass the login page and navigate to `/home` and add extra clicks there as well.**

**App.e2e.js**

    import { Selector } from 'testcafe';
    import { getPageTitle, getPageUrl, fixture, test, login } from './helpers';

    const assertNoConsoleErrors = async browser => {
      const { error } = await browser.getBrowserConsoleMessages();
      await browser.expect(error).eql([]);
    };

    fixture`Electron Client`.page('../../app/app.html').afterEach(assertNoConsoleErrors);

    test('should atempt login without credentials', async browser => {
      await login({
        email: 'name@name.com',
        password: '123456',
        browser,
      });
      await browser
        .click('button[type=submit]')
        .expect(getPageUrl())
        .contains('/login');

      const email = Selector('[name="email"]');
      const password = Selector('[name="password"]');

      await browser.expect(email.value).eql('name@name.com');
      await browser.expect(password.value).eql('123456');
    });

**helpers.js**

    import { ClientFunction } from 'testcafe';

    export const getPageTitle = ClientFunction(() => document.title);

    export const fixture = (...args) => global.fixture(...args);

    export const test = (...args) => global.test(...args);

    export const getPageUrl = ClientFunction(() => window.location.href);

    export const login = async ({ email, password, browser }) => {
      await browser.typeText('[data-test="email"]', email);
      await browser.typeText('[data-test="password"]', password);
      await browser.click('button[type=submit]');
    };

**Comment by AlexSkorkin** [comment]
Thank you for your interest in our testing tools. You are welcome to ask any TestCafe related questions on StackOverflow (https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions. If you think that you found a bug, feel free to open a new issue in the GitHub repo https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md). Thank you in advance.
