### ISSUE TITLE
Is it possible to attach a RequestLogger using an API method similar to runner.screenshots

### ISSUE THREAD

**Issue by switch201** [DevExpress/testcafe#4839]
This is both a question and a feature request depending on if what i am asking for is possible.

When using test cafe I create my own test runner instance using the testcafe API and configure it before I launch the browser. I was wanting to added HTTP Request and Response logging to my tests. All of the examples I have found online only show ways in which to attach the logger to the test fixture, but I was hoping there would be a way to attach the request logger to the runner object itself using the test runner API.

If this is not possible, I would like to request it be made possible.

**Comment by switch201** [comment]
I was able to achieve my end goal by attaching it to the fixture, but was surprised there was no runner api option still.

**Comment by AlexanderMoiseev** [comment]
Hello,

TestCafe does not support this functionality. However, we appreciate your suggestion and we will consider it for the future.

You are welcome to submit your PR with the implementation, and we will review it.

**Comment by switch201** [comment]
Thank you. I may consider doing that if I have the time. I will close this issue.
