### ISSUE TITLE
Cookie auditing as part of tests

### ISSUE THREAD

**Issue by dsample** [DevExpress/testcafe#4845]
_I've looked on StackOverflow, and can't see a similar question, and I think it will result in a feature request, so I'm creating an issue._

Context: As part of GDPR compliance, we need to create a list of all of the cookies we use, and give visitors a way to opt-out of non-critical ones. Part of this process is auditing the cookies we have on our site.

What I'd like to do is run our normal test suite, but be able to record the cookies seen during the tests (both created by server responses, and by client-side JavaScript), but I can't see an option in TestCafe which would do this.

One option which would get at least the server-created cookies is to save HAR files to process after the tests have completed. I might be able to use `RequestLogger` to accomplish this part, but I don't think that will track the cookies created from client-side JS.

I'm hoping it would be possible to log any create/update/delete events which happen with cookies during the sessions, including `name`, `value`, other cookie properties, and as much detail about the cause of the event (eg. which server URI set it as part of its response headers.

**Comment by aleks-pro** [comment]
Hello @dsample ,

Thank you for sharing your idea with us. Please check if the following feature request suits your needs: [https://github.com/DevExpress/testcafe/issues/4428](https://github.com/DevExpress/testcafe/issues/4428)
