### ISSUE TITLE
Error when running npx testcafe-live test.js

### ISSUE THREAD

**Issue by herawatimanurung** [DevExpress/testcafe#4850]
### What is your Test Scenario?

I want to click menu conversation after login to app.
Here's the steps:
1. Login
2. Click on conversation menu
 
### What is the Expected behavior?
Go to conversation page
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from 'testcafe';
import libHelper from '../../lib/helper';
require('dotenv').config();

const helper = new libHelper();

fixture `broadcast`
    .beforeEach( async t => {
        await t.getBrowserConsoleMessages()
        await helper.adminLogin()
    })

test('Admin redirected to conversation page', async t => {
    await t
    // click on Conversation menu
    .click(Selector('.nav-label').withText('Conversations'))

    let conversElemt = Selector('.jss41.jss43.jss42').child('h5').withText('Conversations')

    // expect go to conversation page
    await t.expect(conversElemt).ok()   
})
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Login
2. Click on conversation menu
3. I use testcafe-live command since step 2 will open new browser, I want it reuse the previous session so click conversation menu no need to relogin. But I got this issue 
PS C:\Users\heraw\vouch-bot-staging> npx testcafe-live test-case/admin/conversation.js
(node:8312) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at new FileWatcher (C:\Users\heraw\vouch-bot-staging\node_modules\testcafe-live\lib\file-watcher\index.js:18:15)
    at Controller._initFileWatching (C:\Users\heraw\vouch-bot-staging\node_modules\testcafe-live\lib\controller.js:52:29)
    at Controller.init (C:\Users\heraw\vouch-bot-staging\node_modules\testcafe-live\lib\controller.js:24:14)
    at C:\Users\heraw\vouch-bot-staging\node_modules\testcafe-live\lib\index.js:16:28
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:8312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8312) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 
### Your Environment details:
 
* testcafe version:                    1.8.2
* node.js version:                     12.16.1
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by AlexKamaev** [comment]
The `testcafe-live` repository is obsolete. You need to use TestCafe Live Mode instead. Refer to the following article for more details: [https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/live-mode.html](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/live-mode.html)

If you have further questions, please provide us with your full project to demonstrate the issue.
