### ISSUE TITLE
RequestLogger attached to fixture is not recording 404 request/responses

### ISSUE THREAD

**Issue by switch201** [DevExpress/testcafe#4853]
### What is your Test Scenario?
I am testing a front end system that currently has a bug. When loading one of the pages a number of requests respond with a 404 status code and cause the page to fail to load.
 
### What is the Current behavior?
I have recently the RequestLogger for test cafe and I expected to see the 404 responses in the log but I do not. I see other positive requests and responses that are hitting the back end, but the failed 404 responses are not present in the log.
 
### What is the Expected behavior?
I expect to the the 404 responses in the log.
 
### What is your web application and your TestCafe test code?
N/A
 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 this is how I have my request logger configured:
httpLogger.requestLogger = RequestLogger(undefined, {
            logRequestHeaders: true,
            logRequestBody: true,
            stringifyRequestBody: true,
            logResponseHeaders: true,
            logResponseBody: true,
            stringifyResponseBody: true
        }
```
I then attach the logger at the start of the test, when the test finishes I call `httpLogger.requestLogger.requests` and save that to file as my request log.

</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version: 1.7.0                  
* node.js version:   13.3.0                 
* command-line arguments:  
* browser name and version: chrome 
* platform and version: macOS         
* other:

**Comment by AlexKamaev** [comment]
This is unexpected behavior. However, I was not able to reproduce it on my side. Please create an example, so that we can reproduce the issue on our side.

**Comment by switch201** [comment]
I will see what I can do for you but it will take me some time
