### ISSUE TITLE
Can't assert dynamic element

### ISSUE THREAD

**Issue by herawatimanurung** [DevExpress/testcafe#4858]
### What is your Test Scenario?
I want to assert an dynamic element, the element don't have id, it has dynamic class, and parent class and sibling class also dynamic.
 
### What is the Expected behavior?
Expect the element is visible
 
### What is your web application and your TestCafe test code?
here's the snippet code 
<img width="372" alt="11" src="https://user-images.githubusercontent.com/36288001/76499073-a8d70500-6470-11ea-8763-9fa4015cec52.png">

<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js

 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

I use the following code
```
    .expect(Selector('h6').withAttribute('class', '/jss/i /jss/i').withText('Chat with Junita'))
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

I got this error
```
  1) An assertion method is not specified.
```
</details>

### Steps to Reproduce:

1. Execute testcafe command
 
### Your Environment details:
 
* testcafe version:                   1.8.2
* node.js version:                     12.16.1
* command-line arguments:  
* browser name and version:  Chrome 80
* platform and version:          
* other:

**Comment by miherlosev** [comment]
Hi @herawatimanurung 

See the ways how to select elements with dynamic identificators [here](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/examples-of-working-with-dom-elements.html#select-elements-with-dynamic-ids).

**Comment by herawatimanurung** [comment]
I tried  ```` .expect(Selector('h6').withAttribute('class', 'jss\w+/ jss\w+/').withText('Chat with\w+/'))```` still getting the same An assertion method is not specified.

**Comment by AlexSkorkin** [comment]
Let's continue discussing this issue in the context of your StackOverflow thread: [How to define an selector if the elements are dynamic element](https://stackoverflow.com/questions/60629541/how-to-define-an-selector-if-the-elements-are-dynamic-element)

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafeontributing)).

**Comment by herawatimanurung** [comment]
Please help, still unable to get the correct way

Pada tanggal Jum, 13 Mar 2020 pukul 18.01 Alex Skorkin <
notifications@github.com> menulis:

**Comment by herawatimanurung** [comment]
I report the bugs on  https://github.com/DevExpress/testcafe/issues/4873

Pada tanggal Jum, 13 Mar 2020 pukul 18.01 Alex Skorkin <
notifications@github.com> menulis:

**Comment by herawatimanurung** [comment]
yes, need help on thread https://stackoverflow.com/questions/60629541/how-to-define-an-selector-if-the-elements-are-dynamic-element, still waiting someone to help
