### ISSUE TITLE
Option to get tests information

### ISSUE THREAD

**Issue by rcarro** [DevExpress/testcafe#4861]
### Are you requesting a feature or reporting a bug?
I need to list the tests I have (title, and metadata). Sometimes it would be all, or just some of them, filtering by metadata info. There is a way to do so? like a flag i.e.

### What is your Test Scenario?
I need the information of an specific set of tests before running them. Can be all available tests, of some tests with a certain parameter in metadata.
Something like:
[Test xxx] - Perform actions......
[Test xxx] - Something ....

### Your Environment details:
 
* testcafe version:                   1.8.1
* node.js version:                    10.16.1

**Comment by alreadytaken** [comment]
I'm looking for a similar solution. 

I would like to understand if it's possible to create a custom runner or to modify the source code to do so. I just need the test metadata, not actually running the tests.

If I do

`testcafe chrome TestFolder/* --test-meta smokeTest=true`

the the output would be something like:

{
  "test": "SuperSmokeTest1",
  "meta": "smokeTest",
  "meta": "enabled",
  "meta": "testAllTheThings"
 }

{
  "test": "SuperSmokeTest2",
  "meta": "smokeTest",
  "meta": "disable",
  "meta": "doNotTest"
 }

Not looking for a json output, it is just an example.

**Comment by aleks-pro** [comment]
Hello,

This issue looks like a duplicate. Please check if a solution described in the following thread meets your needs: [https://github.com/DevExpress/testcafe/issues/4340](https://github.com/DevExpress/testcafe/issues/4340)

Feel free to reopen this issue if you have further questions.
