### ISSUE TITLE
ie11 testing on CircleCI (or "remote" PowerShell) hangs on start-up

### ISSUE THREAD

**Issue by jesseolsen** [DevExpress/testcafe#4863]
### What is your Test Scenario?

 
We have tests running successfully with CircleCI and testcafe with chrome.
We would like to run tests in CircleCI for ie11.
When we run this, it hangs trying to bring up the tests, then times out after 6 minutes 45 seconds.
Running locally in PowerShell works fine.
I was able to reproduce this issue locally by setting up PowerShell on my laptop to support remote PowerShell connections, following this [ https://www.howtogeek.com/117192/how-to-run-powershell-commands-on-remote-computers/ ] article.  I then "remoted" in to the same laptop, and ran the same command.  It brought up an npm black DOS window with no text, 

![image](https://user-images.githubusercontent.com/6043493/76576901-2c9ceb80-6489-11ea-8c89-dd7b96583a68.png)

then brought up ie11, with Test Cafe,

![image](https://user-images.githubusercontent.com/6043493/76576974-78e82b80-6489-11ea-9667-4a2a067e00bc.png)

then went to just a white background.  

![image](https://user-images.githubusercontent.com/6043493/76576986-83a2c080-6489-11ea-9838-400697dfe1dc.png)

If I click in the corner, I get a menu
![image](https://user-images.githubusercontent.com/6043493/76577055-acc35100-6489-11ea-99fd-7b4ea5df5f65.png)

I can even right-click and select Inspect Element

![image](https://user-images.githubusercontent.com/6043493/76577111-d8463b80-6489-11ea-8694-993c60ba2158.png)

It hangs for 6 minutes 45 seconds, then shows a time-out error.  See below.

### What is the Current behavior?

```
...\node_modules\.bin\testcafe -e ie --hostname 127.0.0.1 --port 1234,5678 packages/e2e/src/smokeTest/index.js --dev
 Running tests in:
 - IE 11.0.0 / Windows 10.0.0

 Smoke Test
ERROR The IE 11.0.0 / Windows 10.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.

Type "testcafe -h" for help.
yarn : error Command failed with exit code 1.
    + CategoryInfo          : NotSpecified: (error Command failed with exit code 1.:String) [], RemoteExcepti
   on
    + FullyQualifiedErrorId : NativeCommandError

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
{ Error: Command failed: C:\windows\system32\cmd.exe /q /s /c "yarn testcafe -e ie --hostname 127.0.0.1
--port 1234,5678 packages/e2e/src/smokeTest/index.js --dev"
    at makeError (C:\Users\...\...\...\node_modules\start-server-and-test\node_modules\execa\index.js:174:9)
    at Promise.all.then.arr (C:\Users\...\...\...\node_modules\start-server-and-test\node_modules\execa\index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd:
   'C:\\windows\\system32\\cmd.exe /q /s /c "yarn testcafe -e ie --hostname 127.0.0.1 --port 1234,5678
packages/e2e/src/smokeTest/index.js --dev"',
  timedOut: false,
  killed: false }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

 
### What is the Expected behavior?

 
When I run the same basic smoke test ("does the page come up?"), I see the ie11 GUI just fine as tests are executing, and in the console get the following in 52 seconds:

```
testcafe -e ie --hostname 127.0.0.1 --port 1234,5678 packages/e2e/src/smokeTest/index.js --dev
 Running tests in:
 - Internet Explorer 11.0 / Windows 10

 Smoke Test
 √ navigation header appears


 1 passed (24s)
Done in 52.18s.

```

### What is your web application and your TestCafe test code?

 
Just a very simple test to verify the web page came up.

<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```
See screenshots above.

```
</details>

### Steps to Reproduce:

1. Set up a simple test that works when run from ie11 in PowerShell.
2. Set up PowerShell to support remote PowerShell connections, following this [ https://www.howtogeek.com/117192/how-to-run-powershell-commands-on-remote-computers/ ] 3. "remote" in to the same laptop (I used the hostname instead of localhost, though they are the same), and run the test.
4. See that it hangs for 5 minutes, and errors out with a timeout.  Also note the odd ie11 and npm windows. (See screenshots)
 
### Your Environment details:
 
* testcafe version:   v1.8.3-rc.1                
* node.js version:      v10.16.3              
* command-line arguments: testcafe -e ie --hostname 127.0.0.1 --port 1234,5678 packages/e2e/src/smokeTest/index.js --dev 
* browser name and version: ie11 
* platform and version:  Windows 10        
* other: PowerShell

**Comment by AlexKamaev** [comment]
I was able to reproduce the issue in the following way:

1. Run `powershell` as admin.
2. Execute the `Enter-PSSession -ComputerName <COMPUTERNAME>` command.
3. Change the directory to your test project and execute the `testcafe ie <path>` command.


We didn't get reports about similar issues with powershell remote sessions. However, I confirm that it works in Chrome and FF but not in IE.

We need time to research this issue in detail. Thank you for your input.

**Comment by jesseolsen** [comment]
Thanks for reproducing this @AlexKamaev ! CircleCi's free trial includes access to the Windows build server. You can reproduce it pretty easily in there I'd assume: https://circleci.com/pricing/
