### ISSUE TITLE
Cannot use multiple roles in 1 test with sessionStorage token

### ISSUE THREAD

**Issue by rafszyma** [DevExpress/testcafe#4864]
### Are you requesting a feature or reporting a bug?
This can be bug but also missing feature, if this is how useRole should work.

### What is your Test Scenario?
1. useRole(admin) -> gets admin token from authentication server and adds it to sessionStorage
2. Change some permissions around in app
3. useRole(client) -> gets client token from authentication server and adds it to sessionStorage for previous place
4. Opening app and admin is still logged in, and admin token is in session storage

### What is the Current behavior?
Admin is still logged in, whenever I clear localStorage admin values are used, even thou last t.useRole was client

### What is the Expected behavior?
Client token is in the storage unless I use other role

### How would you reproduce the current behavior (if this is a bug)?
1. use -> ClientFunction(key, value) => sessionStorage.setItem() in role definition
2. switch roles and check that old sessionStorage values are there

#### Provide the test code and the tested page URL (if applicable)

 
Your website URL (or attach your complete example):

Your complete test code (or attach your test files)

```js
const setKey = ClientFunction((key, value) => sessionStorage.setItem(key, value));

export const adminRole = Role(
'http:localhost:4200',
async t => {
const token = await getToken('admin');
await setKey('access_token', token);
await t.navigateTo('http:localhost:4200');
)

export const clientRole = Role(
'http:localhost:4200',
async t => {
const token = await getToken('client');
await setKey('access_token', token);
await t.navigateTo('http:localhost:4200');
)

test('my test', async t=> {
await t.useRole(adminRole);
await t.useRole(clientRole);

// expect to on last role here
})
```
### Your Environment details:
 
* testcafe version:                   1.8.2
* node.js version:                    v10.16.3
* command-line arguments:  testcafe -c 1
* browser name and version: Chrome 80, etc. -->
* platform and version:          
* other:                                   If I'm using normal page login, this feature works fine. Only applies to sessionStorage token

**Comment by LavrovArtem** [comment]
I cannot reproduce this issue. My test on [http://example.com/](http://example.com/) works fine. Could you please send us an example where the problem is reproduced?


```js
import { Role, ClientFunction } from 'testcafe';

const setKey = ClientFunction((key, value) => sessionStorage.setItem(key, value));
const getAccessToken = ClientFunction(() => sessionStorage.getItem('access_token'));

export const adminRole = Role('http://example.com/', async t => {
    await setKey('access_token', 'admin_token');
    await t.navigateTo('http://example.com/');
});

export const clientRole = Role('http://example.com/', async t => {
    await setKey('access_token', 'client_token');
    await t.navigateTo('http://example.com/');
});

fixture `fixture`
    .page `http://example.com/`;

test('my test', async t=> {
    await t
        .useRole(adminRole)
        .expect(getAccessToken()).eql('admin_token')
        .useRole(clientRole)
        .expect(getAccessToken()).eql('client_token');
});
```

**Comment by rafszyma** [comment]
Found problem and fixed it. It does not reproduce in the test you wrote, but it does on:

```js
test('my test', async t=> {
    await t
        .useRole(adminRole)
        .expect(getAccessToken()).eql('admin_token')
        .useRole(clientRole)
        .expect(getAccessToken()).eql('client_token')
        .useRole(adminRole)
        .expect(getAccessToken()).eql('admin_token')
        .useRole(clientRole)
        .expect(getAccessToken()).eql('client_token');
});
```

Solution to this problem is using `--disable-page-caching` option in the runtime, then everything runs smooth

Thanks!
