### ISSUE TITLE
Improve test stability for Azure Pipelines

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#4869]
- [ ] Investigate and fix the known blinking tests (GH-845 test for Firefox, `Should clear the upload` and the `Should upload a file` test). 
 - [ ] Find other blinking tests.

**Comment by AlexKamaev** [comment]
I catched the error on `Should upload` test even after FF profile was fixed in Browserstack

**Comment by miherlosev** [comment]
I've created a separate issue for the blinking tests - https://github.com/DevExpress/testcafe/issues/4918
