### ISSUE TITLE
Testcafe doesn't work locally when user's folder has whitespace in name

### ISSUE THREAD

**Issue by lloydstubber** [DevExpress/testcafe#4870]
From what I'm seeing it seems like the library can't handle whitespace in the path. Seems like something similar to this [issue](https://github.com/DevExpress/testcafe/issues/3973) although mine is fine for opening a browser.
 
### What is the Current behavior?
It opens 3 Chrome windows and fails to run app.
 
### What is the Expected behavior?
It would open a single window in the correct address and run test.

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
  "src": "functionalTests/**.ts",
  "clientScripts": [
    "./node_modules/@testing-library/dom/dist/@testing-library/dom.umd.js"
  ]
}

```
</details>

### Steps to Reproduce:

1. Run `env NODE_ENV=local yarn testcafe chrome` in directory (via Gitbash on Windows 10)
2. Yarn prints `"C:\Users\LL COOL J\SQUAREYES\mobile-web\node_modules\.bin\testcafe" chrome` to the terminal
3. Then opens an alert dialog
![image](https://user-images.githubusercontent.com/18339250/76713969-7848e100-6778-11ea-8673-1117cb394b56.png)
4. Tries to open 3 windows and updates the URL to each part of string separated by whitespace e.g. LL, COOL, J
5. Fails to find localhost address to test
6. Exits
 
### Your Environment details:
 
* testcafe version:                   1.8.2
* node.js version:                    v12.16.1
* command-line arguments:  env NODE_ENV=local yarn testcafe chrome
* browser name and version: Chrome
* platform and version:          Windows 10
* other:                                   Gitbash

**Comment by Farfurix** [comment]
@lloydstubber 

Hello,

I wasn't able to reproduce the issue. My setup:
Windows 10, testcafe@1.8.2, Git Bash.
**package.json**:
```json
{
  "name": "mobile-web",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "testcafe": "^1.8.2"
  }
}
```
**./tests/test.js**:
```js
fixture `Fixture`;

test
    .page('http://google.com')
('test', async t => {
    const browser = t.browser;

    console.log('browser = ', browser);

    await t.expect(true).eql(true);
});
```
**Result**:
![Capture](https://user-images.githubusercontent.com/30019338/76854253-d0a6de00-685f-11ea-80cc-07a69265d077.PNG)

Could you please provide us with a complete example? We will examine it and check for a suitable solution.
