### ISSUE TITLE
Unable to assert dynamic element

### ISSUE THREAD

**Issue by herawatimanurung** [DevExpress/testcafe#4872]
#4013 # What is your Test Scenario?
Assert dynamic element in testcafe by using regex
 
### What is the Expected behavior?
Element exists
 
### What is your web application and your TestCafe test code?

<details>
All class on the page is dynamic element, don't have ID or static element. Here's the screenshoot. I want to expect text "Chat with" "......."
<img width="347" alt="dynamic" src="https://user-images.githubusercontent.com/36288001/76738939-1ac78b00-679e-11ea-93f8-b910212ad957.png">

**Here's my code**
test('Admin able to open chat with customer', async t => {
    await t
    // click on Conversation menu
    .click(Selector('.nav-label').withText('Conversations'))
    // login to livechat
    await helper.adminLoginLiveChat()
    
    let conversElemt =  Selector('.jss41.jss43.jss42').child('h5').withText('Conversations')
    let img = Selector('img').withAttribute('src', customerImgSrc)
    let customerName = 'Junita Lilianty'
   

    await t
    // expect go to livechat page
    .expect(conversElemt).ok()  
    // click on customer
    .click(img)
    // expect go to conversation
    .expect(Selector('h5').withAttribute('class', '/jss\w+/ /jss\w+/').withText('Chat with Junita Lilianty').exists).ok('')
    // .expect(Selector('div').)
 
```
I got error: Expected not truthy
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

<!-- Paste your complete test config file here (even if it is huge): -->
```

```
</details>

<details>
<summary>Your complete test report:</summary>

<!-- Paste your complete result test report here (even if it is huge): -->
```

```
</details>

/<details>
<summary>Screenshots:</summary>
<!-- If applicable, add screenshots to help explain the issue. -->

```

```
</details>

### Steps to Reproduce:
<!-- Describe what we should do to reproduce the behavior you encountered. -->

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   <!-- run `testcafe -v` -->
* node.js version:                    <!-- run `node -v` -->
* command-line arguments:  <!-- example: "testcafe ie,chrome -e test.js" -->
* browser name and version: <!-- example: IE 11, Chrome 69, Firefox 100, etc. -->
* platform and version:          <!-- example: "macOS 10.14, Windows, Linux Ubuntu 18.04.1, iOS 12 -->
* other:                                   <!-- any notes you consider important -->

**Comment by Farfurix** [comment]
@herawatimanurung

Hello,

You need to use [regular expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) without the extra `'` symbols. Also, two regular expressions cannot be combined like that: `/jss\w+/ /jss\w+/`. I modified this part as follows:

```diff
- withAttribute('class', '/jss\w+/ /jss\w+/')
+ withAttribute('class', /jss\w+\sjss\w+/)
```

Please refer to the following examples:

1. https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/functional-style-selectors.html#withattribute
2. https://regex101.com/r/VR5mJ0/1


For the team. It duplicates the following issues:

1. https://stackoverflow.com/questions/60482159/unable-to-find-element-when-uploading-file-in-testcafe
2. https://stackoverflow.com/questions/60629541/how-to-define-an-selector-if-the-elements-are-dynamic-element
