### ISSUE TITLE
Unable to assert dynamic element in testcafe

### ISSUE THREAD

**Issue by herawatimanurung** [DevExpress/testcafe#4873]
### What is your Test Scenario?
I want to expect element with text "Chat with" "Junita" "Lilianty"
Here's the snippet code that I want to assert 
<img width="347" alt="dynamic" src="https://user-images.githubusercontent.com/36288001/76741057-76dfde80-67a1-11ea-8f35-6f4ba9746a3b.png">

 
### What is the Expected behavior?
Able to assert dynamic element

### What is your web application and your TestCafe test code?

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```test.only('Admin able to open chat with customer', async t => {
    await t
    // click on Conversation menu
    .click(Selector('.nav-label').withText('Conversations'))
    // login to livechat
    await helper.adminLoginLiveChat()
    
    let conversElemt =  Selector('.jss41.jss43.jss42').child('h5').withText('Conversations')
    let img = Selector('img').withAttribute('src', customerImgSrc)
    let customerName = 'Junita Lilianty'
   

    await t
    // expect go to livechat page
    .expect(conversElemt).ok()  
    // click on customer
    .click(img)
    // expect go to conversation
    .expect(Selector('h5').withAttribute('class', '/jss\w+/ /jss\w+/').withText('Chat with' + customerName).exists).ok('')
 
```

<details>
I got error : AssertionError: expected false to be truthy
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by Farfurix** [comment]
@herawatimanurung 

Hello,
It duplicates the https://github.com/DevExpress/testcafe/issues/4872 issue. Please see [the answer](https://github.com/DevExpress/testcafe/issues/4872#issuecomment-599919313) in the original issue.
