### ISSUE TITLE
Unable to Run Test on Node v12.16.1

### ISSUE THREAD

**Issue by penrodlol** [DevExpress/testcafe#4876]
Receiving the following error:  **'Error: Parse Error: Invalid header value char'** when trying to run tests. Wasn't happening on older versions of Node. Not sure if there's a cap on Node version comparability.
This is happening on start up, when trying to hit the initial page.

**Comment by Farfurix** [comment]
@penrodlol 

Hello,

This information is not sufficient to reproduce the issue. I checked the `v12.16.1` Node.js version and don't see any issues in my base test scenario.

Could you please provide us with a sample project or a public URL? We will examine it and check for a suitable solution.

**Comment by miherlosev** [comment]
Hi @penrodlol 

This issue is related to new Node.js versions. See an explanation and a workaround in the https://github.com/DevExpress/testcafe-hammerhead/issues/2188 issue.
