### ISSUE TITLE
Local "all" browsers recording: 'Video recording is not supported by the "undefined" browser'

### ISSUE THREAD

**Issue by Farfurix** [DevExpress/testcafe#4879]
### Steps to Reproduce:
**test.js**:
```js
fixture `Fixture`;

test('test', async t => {
    await t.expect(true).eql(false);
});
```
**Command**:
```
testcafe all test.js --video artifacts/videos --video-options failed-only=true,pathPattern=${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.mp4
```
**Result**:
```
...
 Warnings (1):
 --
  Video recording is not supported by the "undefined" browser.

```
**Additional info**:
```
>testcafe -b
firefox
ie
chrome
edge
chrome-canary
edge-legacy

```
 
### Your Environment details:
 
* testcafe version:                   v1.8.3-rc.2
* node.js version:                    v12.16.1
* command-line arguments:  `testcafe all test.js --video artifacts/videos --video-options failed-only=true,pathPattern=${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.mp4`
* platform and version:          Windows 10

**Comment by saurabh2k26** [comment]
It seems ffmpeg is not supported in any one of the browsers. Why don't you try running on each browser one by one and figure out which browser have the issue.

**Comment by AlexSkorkin** [comment]
Thank you for your input. We will take it into account.

**Comment by Jeevankumar555** [comment]
Video recording is not supported by the "chrome" browser but chrome:headless is supported

**Comment by Farfurix** [comment]
@Jeevankumar555 

It looks like your case doesn't relate to the original one (the multiple browser case). Try to update your TestCafe version up to v1.14.0. If the issue persists, please share a reproducible example in a new bug report. You can use [our template](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=&template=bug-report.md) for that.
