### ISSUE TITLE
Input type="number", pressKey('up') don't work

### ISSUE THREAD

**Issue by wyhsunflower** [DevExpress/testcafe#4882]
version:
"testcafe": "1.8.1",
"@angular/common": "8.2.13",
"@angular/compiler": "8.2.13",
"@angular/core": "8.2.13",
code:
<input type="number" class="custom" value="00">

my e2e code:

  public input: Selector = Selector('input.custom');
  test.('testcafe', async (t: any) =>{
        await t.typeText(input, '11', { replace: true });
        .pressKey('up')
        .expect(po.timePickerHourInput.value).eql('12');
})

This was failed. And I found,  after .pressKey('up'), the cursor was move to left.
So, does testcafe not support type=number ??

**Comment by AlexKamaev** [comment]
Thank you for reporting the issue to us. I was able to reproduce it. TestCafe supports input[type=number], so this behavior should be fixed.

**Comment by wyhsunflower** [comment]
code:
public getElementSelectionStart: any = ClientFunction((selector: any) => selector().selectionStart);
numberTypeSelector = Selector = Selector('input');

des:
Also, i found [<input type=numbar> , has some bugs. getElementSelectionStart(numberTypeSelector) always return null. And the behavior of  "left" key  is wrong, when pressKey('left'), the cursor is move to the right. (The cursor is in the start of value, then presskey('left'), curosr moves to the end of the input value).

**Comment by LavrovArtem** [comment]
Please create a separate issue and fill in the bug template.
