### ISSUE TITLE
redirect timeout should be configurable

### ISSUE THREAD

**Issue by znar** [DevExpress/testcafe#4884]
We run our tests in parallel mode and sometimes a page redirect takes more than 15sec which causes the test to fail. We can configure pageLoadTimeout    , selectorTimeout and assertionTimeout why not also the redirectTimeout?

**Comment by AlexKamaev** [comment]
Thank you for your input. We already discussed a similar issue in the following ticket: [https://github.com/DevExpress/testcafe/issues/2940](https://github.com/DevExpress/testcafe/issues/2940)

At the moment, this feature is not implemented, however, there is a workaround. Please refer to the following comment: [https://github.com/DevExpress/testcafe/issues/2940#issuecomment-427799295](https://github.com/DevExpress/testcafe/issues/2940#issuecomment-427799295)

Take a look at the following code:
```JS
const DestinationRequest = require('../../../../../../node_modules/testcafe-hammerhead/lib/request-pipeline/destination-request');
...
DestinationRequest.TIMEOUT = 60000;
```
