### ISSUE TITLE
Audit report shows some highest version of testcafe to update

### ISSUE THREAD

**Issue by hansiemithun** [DevExpress/testcafe#4885]
`# Run  npm install --save-dev testcafe@15.1.317922  to resolve 3 vulnerabilities`

**SEMVER WARNING:** Recommended action is a potentially breaking change

But we see 1.8.3 is the latest version here. From where is this 15.x coming?

**Comment by hansiemithun** [comment]
Any update on this? It is unnecessarily trying to update for **15.1.317922** version

**Comment by AlexKamaev** [comment]
The latest version is 1.8.3. The 15.x version is another product that used another approach to versioning.
