### ISSUE TITLE
How to handel Browser popup while recording a script

### ISSUE THREAD

**Issue by satish-abbadi** [DevExpress/testcafe#4888]
In am using to record a page that has a browser popup, while recroding i a not getting that popup in browser, due to that i am not able to complete ymrecording it self. i have attached the screen shot also. Please can any one help how to resolve this issue while recoding and execution.
![Browser popup](https://user-images.githubusercontent.com/62377925/77051486-5f973000-69f1-11ea-87a0-7408f1d94138.PNG)

**Comment by AlexKamaev** [comment]
Hello.
As you mentioned you were recording a page, I assume you are using TestCafe Studio. If so, please use the DevExpress Support Center to submit tickets regarding your version ([https://www.devexpress.com/Support/Center/Question/Create](https://www.devexpress.com/Support/Center/Question/Create)) as we generally process issues related to the paid TestCafe version there to avoid mixing two different versions. The GitHub channel is intended for the open-source version.

As for your question, it looks like your page requires HTTP authentication. Please refer to the following articles to get details:
[https://devexpress.github.io/testcafe/documentation/test-api/authentication/http-authentication.html](https://devexpress.github.io/testcafe/documentation/test-api/authentication/http-authentication.html)
[https://docs.devexpress.com/TestCafeStudio/400184/user-interface/fixture-properties-dialog#basic-httpntlm-authentication-settings](https://docs.devexpress.com/TestCafeStudio/400184/user-interface/fixture-properties-dialog#basic-httpntlm-authentication-settings)
