### ISSUE TITLE
Role - Quarantine mode not working if 'Error in Role initializer' happens

### ISSUE THREAD

**Issue by sijosyn** [DevExpress/testcafe#4892]
### What is your Test Scenario?

I have 70+ tests with userRole and runs with quarantine mode on.
 
### What is the Current behavior?

If login page fails to render for an unknown reason (for example due to rendering issue, page fails to load) in the Role initialization sequence. All my tests are marked as failed with 'Error in Role initializer'. I don't see quarantine mode attempt happening in this case. See attached test code.
 
### What is the Expected behavior?

I would like to see quarantine mode happen if error in role initializer occurs until it passes or fails three times.

### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector, Role } from 'testcafe';

const user = Role(`http://testing-ground.scraping.pro/login`, async t => {
	let timesRun = 1;	
	await console.log(timesRun++);
	await t.expect(Selector('.xyz').exists).ok('Test should fail here.');
}, { preserveUrl: true });

fixture `My Fixture`

test('test 1', async t => {
	await t
		.useRole(user);
});

test('test 2', async t => {
	await t
		.useRole(user);
});

test('test 3', async t => {
	await t
		.useRole(user);
});

test('test 4', async t => {
	await t
		.useRole(user);
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

<img width="741" alt="Screen Shot 2020-03-20 at 1 05 30 PM" src="https://user-images.githubusercontent.com/29459281/77188035-c11bd500-6aab-11ea-98a2-98dc14f440e3.png">

</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                    1.8.2
* node.js version:                     12.13.1
* command-line arguments:   testcafe chrome test.js -q    
* browser name and version:  Chrome 80
* platform and version:           macOS 10.14
* other:

**Comment by AlexanderMoiseev** [comment]
Hello,

Role is initialized only once. So, a function passed to 'Role' as an argument will be called only once even in quarantine mode. I suggest you move the code that you want to execute in quarantine mode outside of the Role's initialization.
