### ISSUE TITLE
Uncaught object "[object object]" was thrown...

### ISSUE THREAD

**Issue by rob4629** [DevExpress/testcafe#4893]
### What is your Test Scenario?

Test scenario is to sign a petition, in mobile emulation mode.
 
### What is the Current behavior?

2 things are happening, but I'm unable to debug the 1st issue due to TestCafe throwing an unhelpful error `uncaught object "[object object]" was thrown. Throw error instead` with no stacktrace.

Prior to this error occurring, testcafe seems unable to correctly enter text in to our `email` field... crashing after this step.
 
### What is the Expected behavior?

I would expect testcafe to be able to handle entering text in to our `email` field while in `mobile emulation` mode (like it does, using desktop Chrome), or throw a helpful error if something catastrophic has occurred.
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

Website: www.change.org
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 fixture('Sign Petition as a New User').page('https://www.change.org');

test('Sign Petition as Guest', async t => {
  const firstNameInput = Selector('[name="firstName"], [name="first_name"]').filterVisible();
  const lastNameInput = Selector('[name="lastName"], [name="last_name"]').filterVisible();
  const emailInput = Selector('.js-email-sign, input[name="email"]').filterVisible();
  const cityInput = Selector('input[name=city]');
  const stateCodeSelect = Selector('select[name="stateCode"], select[name="state_code"]').filterVisible();
  const stateCodeOption = stateCodeSelect.find('option');
  const zipCodeInput = Selector('input[name=postalCode], input[name="postal_code"]').filterVisible();
  const signPetitionButton = Selector('.js-sign-button, button[type="submit"]').filterVisible();

  await t
    .navigateTo('/p/the-world-send-matt-damon-to-mars-to-recover-opportunity?country_code=US&lang=en-US')
    .click(Selector('.mobile-action-button-container .btn-action'))
    .typeText(firstNameInput, 'Anything')
    .typeText(lastNameInput, 'Here')
    .typeText(emailInput, 'some.email@email.com')
    .click(stateCodeSelect)
    .click(stateCodeOption.withText('WA'))
    .typeText(cityInput, 'Seattle')
    .typeText(zipCodeInput, '98101')
    .click(signPetitionButton)
    .expect(signPetitionButton.exists)
    .notOk();
});

```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
  "browsers": ["chrome:headless"],
  "src": "./tests/**/*.js",

  "assertionTimeout": 10000,
  "pageLoadTimeout": 30000,
  "selectorTimeout": 10000,

  "quarantineMode": false,
  "skipJsErrors": true,

  "disablePageCaching": true,

  "reporter": [
    {
      "name": "xunit",
      "output": "artifacts/test-results/results.xml"
    },
    {
      "name": "spec"
    }
  ],

  "screenshots": {
    "fullPage": true,
    "takeOnFails": true,
    "pathPattern": "${TEST_ID}/${RUN_ID}_${FILE_INDEX}.png",
    "path": "artifacts/screenshots"
  },

  "videoOptions": {
    "singleFile": false,
    "failedOnly": true,
    "pathPattern": "${TEST_INDEX}/${RUN_ID}_${FILE_INDEX}.mp4"
  },
  "videoPath": "artifacts/recordings"
}

```
</details>

<details>
<summary>Your complete test report:</summary>

```sh
Using locally installed version of TestCafe.
The "src", "browsers" options from the configuration file will be ignored.
 Running tests in:
 - Chrome 80.0.3987.149 / Other 0.0

 Sign Petition as a New User
 ✖ Sign Petition as Guest (screenshots: /**/artifacts/screenshots/test-1/_errors/1.png)

   1) Uncaught object "[object Object]" was thrown. Throw Error instead.

      Browser: Chrome 80.0.3987.149 / Other 0.0
      Screenshot: /**/artifacts/screenshots/test-1/_errors/1.png


 1/1 failed (53s)
```
</details>

<details>
<summary>Screenshots:</summary>

```
[TestCafe Mobile failure videos.zip](https://github.com/DevExpress/testcafe/files/4357383/TestCafe.Mobile.failure.videos.zip)

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version: 1.8.3                   
* node.js version: 12.14.1                   
* command-line arguments:  `testcafe 'chrome:emulation:width=400;height=800;mobile=true;orientation=vertical;touch=true --user-agent=\"Chrome/80.0.3987.149\ Mobile\"'`
* browser name and version: Chrome 80 (mobile emulation)
* platform and version:          Mac Catalina 
* other:  Seems possibly related to https://github.com/DevExpress/testcafe/issues/3189. Or at least, the error is the same

**Comment by rob4629** [comment]
I feel like this is a fairly new issue, as I was previously able to get passed this step using `v1.7.0` (and possibly even `v1.8.0` (_although will need to confirm_)

**Comment by LavrovArtem** [comment]
I've reproduced this issue. Something wrong with typing in the input with the `email` type when TestCafe is running with a custom user agent. Here is a simplified example:
```html
<!--  page simple.html -->
<input type="email">
```
```js
// test.js
fixture('Email input with custom user-agent').page('./simple.html');

test('Type text', async t => {
  await t.typeText('[type="email"]', 'some.email@email.com')
});
```

chrome: `80.0.3987.132`
testcafe: `1.8.3`
command line: `testcafe 'chrome --user-agent="Chrome/80.0.3987.149 Mobile"' test.js`

**Comment by AlexKamaev** [comment]
fixed in https://github.com/DevExpress/testcafe-hammerhead/pull/2281
