### ISSUE TITLE
Not focusing on testcafe browser fails click() intermittently in live test

### ISSUE THREAD

**Issue by frnkshin** [DevExpress/testcafe#4897]
### What is your Test Scenario?
I want to run `testcafe` in a full screen terminal, and to have it be 100% consistent
 
### What is the Current behavior?
test controller fails to click on an element when I'm not focusing on the testcafe browser, and when I'm on a different workspace in OS X. (Full screen terminal, etc)
 
### What is the Expected behavior?
It should still click the element
 
### What is your web application and your TestCafe test code?
It's an internal applications and cannot be shared.

Sample test cafe code is as follows, however:
```
navigator = Selector('button')

async openNav(t: TestController) {
  const navElement = await navigator.with({ visibilityCheck: true })();
  // navElement.visible = true at this point, with height and width being > 0
  return testController.click(navElement)
}
```
 
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
running with chrome --incognito --live, --debug-on-fail for debugging  purposes
```
</details>

### Your complete test report:
```
The specified selector does not match any element in the DOM tree.

   | Selector('button')
 > |   .withText('sign in')
```
This error is not finding element in DOM due to click() not executing previously.

### Steps to Reproduce:

* Use OS X Catalina, may apply to lower versions *
1. Open terminal, full screen it
2. Run test cafe
3. Initial run is successful (majority of times)
4. press C-r to restart
5. Stay in terminal, don't focus browser
6. click() fails, and the subsequent selector search in DOM fails (intermittently)
 
### Your Environment details:
 
* testcafe version:                    1.8.3
* node.js version:                     v10.16.1
* command-line arguments:     testcafe --skip-js-errors --live 'chrome -incognito' test.ts --selector-timeout 5000 -r spec:output.spec --debug-on-fail,
* browser name and version:  Latest Chrome
* platform and version:           macOS 10.15.3
* other:                                   --> **Can someone reproduce this issue?**

**Comment by ljowen** [comment]
I haven't encountered this issue myself but I'd recommend running chrome headlessly as I imagine that will fix your issue

**Comment by frnkshin** [comment]
@ljowen
Yes, running headless has consistent outputs.
It'd be great if you (or anyone) could reproduce this issue on OS X, so I will know that I'm not alone on this.

**Comment by Farfurix** [comment]
@frnkshin 

Hello,

I wasn't able to reproduce the issue. Here are steps I followed:
1. Open a terminal (fullscreen mode).
2. Run `testcafe --live chrome test.js`.
3. macOS switches to the Chrome window.
4. Switch back to the terminal.
5. Restart tests several times.

Test code:
```js
import { Selector } from 'testcafe';

fixture `Fixture`
    .page `https://github.com/`

test('test', async t => {
     const selector = Selector('a').withText('Sign up');
     
     await t
         .click(selector);
});
```

Result:
![Capture-1](https://user-images.githubusercontent.com/30019338/77525276-d2912280-6e99-11ea-9ba7-b13eff4ab3ec.PNG)

Could you please send us a project (or a public URL with your test code)? We will examine it and check for a suitable solution.

**Comment by frnkshin** [comment]
@Farfurix 
Weird, I'm getting inconsistent results with your provided code.

Running with following `testcafe` command:
* `$ testcafe  --skip-js-errors --live 'chrome -incognito --start-maximized' index.js -r spec:output.spec --debug-on-fail`

Here are the outputs:
```
$ cat output.spec
 Running tests in:
 - Chrome 80.0.3987.149 / macOS 10.15.3

 Fixture
 ✖ test

   1) The element that matches the specified selector is not visible.

      Browser: Chrome 80.0.3987.149 / macOS 10.15.3

          6 |test('test', async t => {
          7 |     const selector = Selector('a').withText('Sign up');
          8 |     await selector.with({ visibilityCheck: true });
          9 |
         10 |     await t
       > 11 |         .click(selector);
         12 |});
         13 |

         at <anonymous> (/opt/projects/testcafe-tutorial/index.js:11:11)



 1/1 failed (14s)
 Running tests in:
 - Chrome 80.0.3987.149 / macOS 10.15.3

 Fixture
 ✓ test


 1 passed (5s)
 Running tests in:
 - Chrome 80.0.3987.149 / macOS 10.15.3

 Fixture
 ✖ test

   1) The element that matches the specified selector is not visible.

      Browser: Chrome 80.0.3987.149 / macOS 10.15.3

          5 |
          6 |test('test', async t => {
          7 |     const selector = Selector('a').withText('Sign up');
          8 |
          9 |     await t
       > 10 |         .click(selector);
         11 |});
         12 |

         at <anonymous> (/opt/projects/testcafe-tutorial/index.js:10:11)
         at test (/opt/projects/testcafe-tutorial/index.js:6:1)
         at <anonymous>

   (/opt/projects/testcafe-tutorial/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at LiveModeTestRun._executeTestFn

   (/opt/projects/testcafe-tutorial/node_modules/testcafe/src/test-run/index.js:294:19)
         at LiveModeTestRun.start
      (/opt/projects/testcafe-tutorial/node_modules/testcafe/src/test-run/index.js:345:24)



 1/1 failed (12s)
```

**Comment by miherlosev** [comment]
Hi @frnkshin 

I cannot reproduce the problem either. It is likely that the issue is connected to the web page with where you run tests. We need an complete example to reproduce the problem. Feel free to reopen this issue if you can create such example.

**Comment by frnkshin** [comment]
I made a quick screencast, feel free to check it out.

https://www.youtube.com/watch?v=C7N8_q7HYzM

**Comment by aleks-pro** [comment]
Hello @frnkshin ,

Thank you for the screencast. It looks like the problem is in the `Selector` here. Please try to use the following one:
```js
...
const selector = Selector('.HeaderMenu a').withText(/Sign\sup/);
...
```

**Comment by frnkshin** [comment]
Hey @aleks-pro,

Thanks for the fix, that fixed the example code.
It looks like having a single quote text value for `withText()` does not seem to work.
Is it always recommended to use the backslash to escape strings for TestCafe?
Or are there specific instances where you'd use one over the other?

**Comment by aleks-pro** [comment]
Hi @frnkshin,

Backslashes in the `/Sign\sup/` expression are used to create a [`RegExp`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) instance. This is pure javascript syntax. So you can use the [`withText`](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/functional-style-selectors.html#withtext) method with all capabilities of regular expressions.
