### ISSUE TITLE
Feature request: Rerun test from the last failed assertion in Live mode

### ISSUE THREAD

**Issue by hinok** [DevExpress/testcafe#4909]
### What is your Test Scenario?

1. Create a long-running test.
2. Test fails in the middle of the flow.
3. Fix the issue and rerun the test again.

### What are you suggesting?

**Currently**
Test starts from the beginning.

**Expected**
Test starts from the last failed assertion.

### What alternatives have you considered?

N/A

### Additional context

This feature should be built for [Live mode](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/live-mode.html).

This feature could enhance testing workflow and speed up dramatically development.

**Comment by Farfurix** [comment]
@hinok

Hello,

Thank you for your request. There is no guarantee that the current page state is correct due to a failed action/assertion. So we have to restart the whole test.

**Comment by hinok** [comment]
@Farfurix Hey, what did you mean by saying
> There is no guarantee that the current page state is correct

?

**Comment by AlexSkorkin** [comment]
This means that the current page state that you are currently testing may not correspond to the expected page state you would like to test. That is why it is better to start the test from scratch to avoid any unexpected testing behavior. Anyway, we appreciate your idea.

**Comment by hinok** [comment]
@AlexSkorkin Got it. I'd say that in live mode I can easily assess whether the state of the page is valid or not because I see that page in the browser.

I didn't propose this feature for "regular mode". I found it a bit frustrating where writing longer tests force you to run them from the beginning if they fail somewhere in the middle (e.g. timeout from external API etc).

**Comment by AlexSkorkin** [comment]
Thank you for your clarification.
