### ISSUE TITLE
Print the HTML of the page in the error

### ISSUE THREAD

**Issue by tieTYT** [DevExpress/testcafe#4910]
### What is your Test Scenario?
```
.expect(Selector('.container:nth-child(1)').textContent)
    .contains("word")
```
this gives me an error that says: `Cannot obtain information about the node because the specified selector does not match any node in the DOM tree.`

### What are you suggesting?
When I use the debugger, I do see this in the Dom tree. From my perspective, testcafe is seeing a different Dom tree than I can see. I'd like it to explicitly tell me what it sees in this situation.

I wouldn't want to turn this feature on at all times, It's just something I want but I can't figure out why there is happening.

### What alternatives have you considered?
Maybe it would be possible to log the HTML right before I try to run this expectation, but I don't think that's a better solution because I don't know if I can trust the HTML I see * before* the expectation that's failing.

**Comment by AlexKamaev** [comment]
Thank you for your input. As far as I understand, you cannot correctly debug TestCafe selectors. We are aware of this problem. We are currently researching it in the following issue: [https://github.com/DevExpress/testcafe/issues/3244](https://github.com/DevExpress/testcafe/issues/3244). Please refer to it to track our progress.

**Comment by tieTYT** [comment]
I do not see anything in that issue that relates to what I'm proposing except that they're both about debugging selectors. We are suggesting different ways of doing it, and I think they might both be worth doing. My request is for something that I would imagine is far easier to implement: print out exactly what HTML testcafe sees on the page when it's erroring.  

Sometimes I get errors that might be caused by html race conditions. When I look at the page, it seems fine, but testcafe reports he can't my selector.  If testcafe could just print out exactly what it sees when it errors, this would be very helpful for debugging.

**Comment by miherlosev** [comment]
Hi @tieTYT 

In assertions, you compare selector properties with expected values.
Debugging selectors will allow you to inspect these properties for target selector. 
It's more convenient than searching for them in the whole HTML code of the page.

You can print page HTML code using this `ClientFunction`.
 ```js
import { ClientFunction } from 'testcafe';

fixture `Fixture`
	.page('https://devexpress.github.io/testcafe/example/');
 
const getPageHTML = ClientFunction(() => {
	return document.documentElement.outerHTML;
}); 
 
test('test', async t => {
	console.log(await getPageHTML());
});
```
