### ISSUE TITLE
Add support for strongly typed context

### ISSUE THREAD

**Issue by crhistianramirez** [DevExpress/testcafe#4911]
### What is your Test Scenario?

I have some context I've set but in my test I misspelled the property name and got an unexpected value of `undefined`

```typescript
fixture`Fixture1`.beforeEach(async t => {
  t.ctx.color= 'red'
})

test('Test1', async t => {
  console.log(t.ctx.colorr) // ooops, undefined
})
```

### What are you suggesting?
Context is typed as a dictionary `{[key:string]:any}` which doesn't give us much type safety. I propose it takes an optional type parameter so it can be defined by the consumer.

```typescript
interface TestController<TContext = any> {
    ctx: TContext
}
```

Then it could be used like so:

```typescript
interface MyContext {
  color: string
}

fixture`Fixture1`.beforeEach(async (t: TestController<MyContext>) => {
  t.ctx.color = 'red' // strongly typed!
})

test('Test1', async (t: TestController<MyContext>) => {
  console.log(t.ctx.color) // 'red' strongly typed!
})
```

This is an optional type parameter so it would be an opt-in feature.

### What alternatives have you considered?
In my proposed solution, the fallback type is of type `any`. It could be argued that I'm making `ctx `less type-safe for anyone not using the optional type parameter. I'd argue that the dictionary type defined currently really serves more as a point of semantics because it is pretty weakly typed.

If that's a problem though we could modify my primary solution like so:

```typescript
interface TestController<TContext = {[key:string]: any}> {
    ctx: TContext
}
```

The downside here is that the properties in `MyContext` have to be optional.

### Additional context
If this looks good I'd like to make a pull request with the proposed changes.

**Comment by Dmitry-Ostashev** [comment]
Thank you for your suggestion.

However, you can declare your own TestController interface in the fixture file:

```
interface MyContext {
    color: string
}

interface TestControllerEx<TContext> extends Omit<TestController, 'ctx'> {
    ctx: TContext;
}

fixture`Fixture1`.beforeEach(async (t: TestControllerEx<MyContext>) => {
    t.ctx.color = 'red' // strongly typed!
});

test('Test1', async (t: TestControllerEx<MyContext>) => {
    await t.expect(t.ctx.color).eql('red'); // 'red' strongly typed!
});
```

**Comment by crhistianramirez** [comment]
@Dmitry-Ostashev I don't disagree that you could do it that way but it definitely smells a little hacky. Testcafe should have a built-in method of extending the context model.

**Comment by AlexanderMoiseev** [comment]
Hello, we have discussed your proposal with the team and decided not to support this functionality for now. Please use the solution provided by Dmitry. It is completely valid.
