### ISSUE TITLE
Access elements in iFrame without need to use switchToIframe()

### ISSUE THREAD

**Issue by fmancardi** [DevExpress/testcafe#4913]
### What is your Test Scenario?
Want to test an application that implements TABs using iFrame

### What are you suggesting?
I've used taiko and there is no need to call something similar to switchToIframe()
this reduces the number of errors you face when you create test scripts manually,
not using TestCafe Studio

**Comment by Dmitry-Ostashev** [comment]
The top window and iframes contain documents with the different DOM trees. This may lead to some another difficulties. You can see the similar switching in the Chrome DevTools.

However, it would be nice to learn more about your scenario and requirements.

**Comment by fmancardi** [comment]
Sorry for the delay to provide details.
Our application TESISQUARE PLATFORM (www.tesisquare.com) has pages that contain tabs.
When accessing the page from the menu,  the page content is in the MainWindow, but the tab content is managed inside an iframe.
If I want to check/validate the breadcrumb I need switchToMainWindow(), but if I want to check the input labels I need to switchToIframe().

If the use of the switchTo functions can not be avoided, a thing that IMHO will be very useful is to have a testcafe function/method to understand if I'm in the MainWindow or an Iframe (and the Iframe ID/Name).   

Another thing that will be useful is that switchToMainWindow() and switchToIframe() will return the current window id allowing to change Window/Iframe and be able to return to the original window.   

Hope now is a little bit clear

**Comment by miherlosev** [comment]
Hi @fmancardi

Thank you for sharing your scenario.

On the one hand, it is useful to have access to an element in iframe without switching between windows (you can drop the `switchToIframe` and `switchToMainWindow` method calls from your tests).
On the other hand, different elements in different iframes can have the same selectors. So, you need to specify a target window for the element selector anyway. It can be done at the selector level or at the method call level. TestCafe allows you to select a target window at the test controller method level - the `switchToIframe` and`switchToMainWindow` methods. At present, we don't have plans to specify a target window using another way.

> If the use of the switchTo functions can not be avoided, a thing that IMHO will be very useful is to have a testcafe function/method to understand if I'm in the MainWindow or an Iframe (and the Iframe ID/Name).
This task can be achieved using the following ClientFunction:
```js
const isInTopWindow = ClientFunction(() => window.top === window.self);
```
