### ISSUE TITLE
[docs] Website - Cannot scroll down the main menu on mobile

### ISSUE THREAD

**Issue by VasilyStrelyaev** [DevExpress/testcafe#4916]

**Comment by DIRECTcut** [comment]
The hamburger menu scrolls fine.
Although TestCafe Studio banner gets squashed if the `Docs` section is expanded (Safari IOS)

![99jnx-Ch21k](https://user-images.githubusercontent.com/49588154/104960142-b5a77c00-59e4-11eb-91b3-e41919bad0c4.jpg)
![cI7yj7_9WSI](https://user-images.githubusercontent.com/49588154/104960143-b6d8a900-59e4-11eb-9a4f-530ee187f1d9.jpg)

**Comment by DIRECTcut** [comment]
Additionally, when `Docs` is collapsed, scrolling of the hamburger menu scrolls the site instead (Safari IOS)

**Comment by DIRECTcut** [comment]
Low severity: won't fix
