### ISSUE TITLE
Fix blinking tests

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#4918]
- [ ] [`[Regression] GH-3904 - Should correctly switch to iframe loaded from form`](https://github.com/DevExpress/testcafe/blob/6c301c194acdce61ff8848120a934bc82d722726/test/functional/fixtures/regression/gh-3904/test.js)
- [ ] `Upload -> Should clear the upload`
- [ ] `Upload -> Should upload files`
- [ ] `[Regression](GH-856) Test should not hang when redirect occurs after the page is loaded`
- [ ] `[API] t.switchToIframe(), t.switchToMainWindow()->   Should keep context if the page was reloaded`
- [ ] (https://github.com/DevExpress/testcafe/pull/5104) `Scroll -> Events initiated by scroll should have valid properties`

**Comment by AndreyBelym** [comment]
`Scroll -> Events initiated by scroll should have valid properties` started blinking again
