### ISSUE TITLE
Provide browser info after user agent deprecation

### ISSUE THREAD

**Issue by amitzur** [DevExpress/testcafe#4921]
### What is your Test Scenario?
There an [API](https://devexpress.github.io/testcafe/documentation/test-api/identify-the-browser-and-platform.html) for getting browser information. It's currently based on the user agent string (I'm relying on [this code](https://github.com/DevExpress/testcafe/blob/master/src/browser/connection/gateway.ts#L92)).

Chrome [intends to freeze and deprecate](https://groups.google.com/a/chromium.org/forum/m/#!msg/blink-dev/-2JIRNMWJ7s/yHe4tQNLCgAJ) the user agent string ([crbug](https://bugs.chromium.org/p/chromium/issues/detail?id=955620)).
Once this is in, the browser info code will break.

### What are you suggesting?
Using [client-hints](https://github.com/WICG/ua-client-hints#a-proposal) or the planned JavaScript `navigator.getUserAgent()` function.

**Comment by miherlosev** [comment]
Hi @amitzur 

Thank you for pointing this out. We will investigate it.
