### ISSUE TITLE
Does testcafe allow integration of jenkins as a CI tool

### ISSUE THREAD

**Issue by ashwini5gaikwad** [DevExpress/testcafe#4924]
Does testcafe allow integration of jenkins as a CI tool

**Comment by AlexSkorkin** [comment]
Yes: [https://devexpress.github.io/testcafe/documentation/continuous-integration/](https://devexpress.github.io/testcafe/documentation/continuous-integration/).

If you face any issues during the integration, feel free to ask your inquiries on StackOverflow - an amazing platform for users to ask and answer questions. We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)).
