### ISSUE TITLE
Test the multiwindow functionality

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#4927]

**Comment by kirovboris** [comment]
mac 10.15.3, node 12.16.1, chrome 80
```js
fixture `Avito`
    .page('https://www.avito.ru/rossiya');

test('Login via Google', async t => {
    await t
        .click('[data-marker="header/login-button"]')
        .click('[data-marker="social-network-item(gp)"]')
        .click('div')
        .debug();
});
```
<details>
JavaScript error details:
      RangeError: Maximum call stack size exceeded
          at t.r.setCookie (http://192.168.1.34:56823/hammerhead.js:6:19630)
          at t.r.syncWindowCookie
      (http://192.168.1.34:56823/hammerhead.js:6:21362)
          at e.t._delegateSyncBetweenWindowsToMainTopWindow
      (http://192.168.1.34:56823/hammerhead.js:6:23592)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24241)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24511)
          at e.t._delegateSyncBetweenWindowsToMainTopWindow
      (http://192.168.1.34:56823/hammerhead.js:6:23630)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24241)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24511)
          at e.t._delegateSyncBetweenWindowsToMainTopWindow
      (http://192.168.1.34:56823/hammerhead.js:6:23630)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24241)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24511)
          at e.t._delegateSyncBetweenWindowsToMainTopWindow
      (http://192.168.1.34:56823/hammerhead.js:6:23630)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24241)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24511)
          at e.t._delegateSyncBetweenWindowsToMainTopWindow
      (http://192.168.1.34:56823/hammerhead.js:6:23630)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24241)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24511)
          at e.t._delegateSyncBetweenWindowsToMainTopWindow
      (http://192.168.1.34:56823/hammerhead.js:6:23630)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24241)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24511)
          at e.t._delegateSyncBetweenWindowsToMainTopWindow
      (http://192.168.1.34:56823/hammerhead.js:6:23630)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24241)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24511)
          at e.t._delegateSyncBetweenWindowsToMainTopWindow
      (http://192.168.1.34:56823/hammerhead.js:6:23630)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24241)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24511)
          at e.t._delegateSyncBetweenWindowsToMainTopWindow
      (http://192.168.1.34:56823/hammerhead.js:6:23630)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24241)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24511)
          at e.t._delegateSyncBetweenWindowsToMainTopWindow
      (http://192.168.1.34:56823/hammerhead.js:6:23630)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24241)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24511)
          at e.t._delegateSyncBetweenWindowsToMainTopWindow
      (http://192.168.1.34:56823/hammerhead.js:6:23630)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24241)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24511)
          at e.t._delegateSyncBetweenWindowsToMainTopWindow
      (http://192.168.1.34:56823/hammerhead.js:6:23630)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24241)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24511)
          at e.t._delegateSyncBetweenWindowsToMainTopWindow
      (http://192.168.1.34:56823/hammerhead.js:6:23630)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24241)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24511)
          at e.t._delegateSyncBetweenWindowsToMainTopWindow
      (http://192.168.1.34:56823/hammerhead.js:6:23630)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24241)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24511)
          at e.t._delegateSyncBetweenWindowsToMainTopWindow
      (http://192.168.1.34:56823/hammerhead.js:6:23630)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24241)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24511)
          at e.t._delegateSyncBetweenWindowsToMainTopWindow
      (http://192.168.1.34:56823/hammerhead.js:6:23630)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24241)
          at e.t.syncBetweenWindows
      (http://192.168.1.34:56823/hammerhead.js:6:24511)
</details>

**Comment by kirovboris** [comment]
Login via Github the same error:
```js
import { Selector } from 'testcafe';

fixture `Github`.page`https://www.hackerrank.com/dashboard`;

test(''Login via Github', async t => {
  await t
	.click('.login')
	.click(Selector('.social-btn-icon').nth(-1))
	.typeText('#login_field', '<user>')
	.typeText('#password', '<pass>')
	.pressKey('enter')
	.debug();
});
```

**Comment by Farfurix** [comment]
Test with an error (the `DecodingTransformer` error does not occur every time): Login via Twitter
```js
import { Selector, ClientFunction } from 'testcafe';

const aliexpressHomePage = 'https://aliexpress.ru/home.htm';

fixture `AliExpress`
    .page(aliexpressHomePage);

const closeAdButton       = Selector('body > div.ui-window.ui-window-normal.ui-window-transition.ui-newuser-layer-dialog > div > div > a');
const myProfile           = Selector('#nav-user-account > span > a > span');
const signButton          = Selector('#nav-user-account > div > div > p.flyout-bottons > a.sign-btn');
const showAllLoginOptions = Selector('#login-sns-wrap > p > a.show-all');
const twitterButton       = Selector('#login-sns-wrap > div > div:nth-child(5) > a');

const twitterLoginInput    = Selector('#username_or_email');
const twitterPasswordInput = Selector('#password');
const submitPasswordButton = Selector('#allow');

const twitterLogin = '**********';
const twitterPass  = '**********';

const getLocation = ClientFunction(() => window.location.href);


test('Login via Twitter', async t => {
    await t
        .maximizeWindow()
        .wait(1000);

    await t
        .click(closeAdButton)
        .hover(myProfile)
        .click(signButton)
        .click(showAllLoginOptions)
        .click(twitterButton);

    await t
        .typeText(twitterLoginInput, twitterLogin)
        .typeText(twitterPasswordInput, twitterPass)
        .click(submitPasswordButton);

    // wait for login
    await t.wait(10000);

    await t.expect(getLocation()).eql(aliexpressHomePage)
});

```
Result:
```
D:\work\multi-window-test>testcafe chrome tests/ali-twitter-test.js --allow-multiple-windows -e
 Running tests in:
 - Chrome 80.0.3987.149 / Windows 10

 AliExpress
 × Login via Twitter

   1) TypeError: Cannot read property '0' of null

      Browser: Chrome 80.0.3987.149 / Windows 10

         266 |        this._handlePlainObject(val);
         267 |};
         268 |
         269 |DecodingTransformer.prototype.transform = function () {
         270 |    this.visitedRefs[0] = true;
       > 271 |    this._handleValue(this.references[0], this.references, 0);
         272 |
         273 |    return this.references[0];
         274 |};
         275 |
         276 |

         at DecodingTransformer.transform (D:\work\multi-window-test\node_modules\replicator\index.js:271:38)
         at module.exports.Replicator.decode (D:\work\multi-window-test\node_modules\replicator\index.js:559:24)
         at ClientFunctionBuilder._processResult (D:\work\multi-window-test\node_modules\testcafe\src\client-functions\client-function-builder.js:146:32)
         at <anonymous> (D:\work\multi-window-test\node_modules\testcafe\src\client-functions\client-function-builder.js:141:25)



 1/1 failed (29s)

D:\work\multi-window-test>testcafe chrome tests/ali-twitter-test.js --allow-multiple-windows -e
 Running tests in:
 - Chrome 80.0.3987.149 / Windows 10

 AliExpress
 √ Login via Twitter


 1 passed (27s)

```

**Comment by AndreyBelym** [comment]
Cannot hide the login dialog after signing in with VK or Twitter:
```js
import { Selector } from 'testcafe';

fixture `DTF`.page`http://dtf.ru`;

const credentials = {
    twitter: {
        username: 'belym.a.2105@gmail.com',
        password: '0@1b35H132134'
    },
    vk: {
        username: '+79065350915',
        password: 'yippee-ki-yay'
    }
}
const dtf = {
    login: {
        mainForm:      Selector('body > div.main_menu.layout > div.popup > div.popup__container.popup__container--shown > div > div.popup__container__window__tpl > div > div > div.auth-form__main > div.auth-form__tab.auth_tab.auth_tab--signin-start'),
        mainButton:    Selector('body > div.main_menu.layout > div.layout__column.layout__column--center.l-flex > div.main_menu__right-side.l-ml-auto.lm-ml-0.l-flex.l-fa-center > div.main_menu__auth.l-ml-10.lm-ml-10.l-mr-40.lm-mr-0 > div > span'),
        twitterButton: Selector('body > div.main_menu.layout > div.popup > div.popup__container.popup__container--shown > div > div.popup__container__window__tpl > div > div > div.auth-form__main > div.auth-form__tab.auth_tab.auth_tab--signin-start > div.auth-form__content > div.social-auth.social-auth--with-email > div:nth-child(5) > div'),
        vkButton:      Selector('body > div.main_menu.layout > div.popup > div.popup__container.popup__container--shown > div > div.popup__container__window__tpl > div > div > div.auth-form__main > div.auth-form__tab.auth_tab.auth_tab--signin-start > div.auth-form__content > div.social-auth.social-auth--with-email > div:nth-child(2) > div')
    },

    mainLogo: Selector('body > div.main_menu.layout > div.layout__column.layout__column--left.layout__column--unique > div > a.main_menu__logo.l-ml-20.lm-ml-15.l-mr-20.lm-mr-10')
};

const twitter = {
    usernameEditor: Selector('#username_or_email'),
    passwordEditor: Selector('#password'),
    loginButton:    Selector('#allow')
};

const vk = {
    usernameEditor: Selector('#login_submit > div > div > input:nth-child(7)'),
    passwordEditor: Selector('#login_submit > div > div > input:nth-child(9)'),
    loginButton:    Selector('#install_allow')
};

test(`Twitter`, async t => {
    await t.click(dtf.login.mainButton);
    await t.click(dtf.login.twitterButton);

    await t.typeText(twitter.usernameEditor, credentials.twitter.username);
    await t.typeText(twitter.passwordEditor, credentials.twitter.password);

    await t.click(twitter.loginButton);

    await t.expect(Selector(dtf.mainLogo).exists).eql(true);
    await t.expect(Selector(dtf.login.mainForm).exists).eql(false);
});

test(`VK`, async t => {
    await t.click(dtf.login.mainButton);
    await t.click(dtf.login.vkButton);

    await t.typeText(vk.usernameEditor, credentials.vk.username);
    await t.typeText(vk.passwordEditor, credentials.vk.password);
    await t.click(vk.loginButton);

    await t.debug(); //2FA

    await t.expect(Selector(dtf.mainLogo).exists).eql(true);
    await t.expect(Selector(dtf.login.mainForm).exists).eql(false);
});
```

**Comment by AndreyBelym** [comment]
import { Selector } from 'testcafe';

fixture `DTF`.page`http://dtf.ru`;

const credentials = {
    twitter: {
        username: '',
        password: ''
    },
    vk: {
        username: '',
        password: ''
    }
}
const dtf = {
    login: {
        mainForm:      Selector('body > div.main_menu.layout > div.popup > div.popup__container.popup__container--shown > div > div.popup__container__window__tpl > div > div > div.auth-form__main > div.auth-form__tab.auth_tab.auth_tab--signin-start'),
        mainButton:    Selector('body > div.main_menu.layout > div.layout__column.layout__column--center.l-flex > div.main_menu__right-side.l-ml-auto.lm-ml-0.l-flex.l-fa-center > div.main_menu__auth.l-ml-10.lm-ml-10.l-mr-40.lm-mr-0 > div > span'),
        twitterButton: Selector('body > div.main_menu.layout > div.popup > div.popup__container.popup__container--shown > div > div.popup__container__window__tpl > div > div > div.auth-form__main > div.auth-form__tab.auth_tab.auth_tab--signin-start > div.auth-form__content > div.social-auth.social-auth--with-email > div:nth-child(5) > div'),
        vkButton:      Selector('body > div.main_menu.layout > div.popup > div.popup__container.popup__container--shown > div > div.popup__container__window__tpl > div > div > div.auth-form__main > div.auth-form__tab.auth_tab.auth_tab--signin-start > div.auth-form__content > div.social-auth.social-auth--with-email > div:nth-child(2) > div')
    },

    mainLogo: Selector('body > div.main_menu.layout > div.layout__column.layout__column--left.layout__column--unique > div > a.main_menu__logo.l-ml-20.lm-ml-15.l-mr-20.lm-mr-10')
};

const twitter = {
    usernameEditor: Selector('#username_or_email'),
    passwordEditor: Selector('#password'),
    loginButton:    Selector('#allow')
};

const vk = {
    usernameEditor: Selector('#login_submit > div > div > input:nth-child(7)'),
    passwordEditor: Selector('#login_submit > div > div > input:nth-child(9)'),
    loginButton:    Selector('#install_allow')
};

test(`Twitter`, async t => {
    await t.click(dtf.login.mainButton);
    await t.click(dtf.login.twitterButton);

    await t.typeText(twitter.usernameEditor, credentials.twitter.username);
    await t.typeText(twitter.passwordEditor, credentials.twitter.password);

    await t.click(twitter.loginButton);

    await t.expect(Selector(dtf.mainLogo).exists).eql(true);
    await t.expect(Selector(dtf.login.mainForm).exists).eql(false);
});

test(`VK`, async t => {
    await t.click(dtf.login.mainButton);
    await t.click(dtf.login.vkButton);

    await t.typeText(vk.usernameEditor, credentials.vk.username);
    await t.typeText(vk.passwordEditor, credentials.vk.password);
    await t.click(vk.loginButton);

    await t.debug(); //2FA

    await t.expect(Selector(dtf.mainLogo).exists).eql(true);
    await t.expect(Selector(dtf.login.mainForm).exists).eql(false);
});

**Comment by AndreyBelym** [comment]
1. Low performance on Facebook
2. If a `t.debug` command pauses the test execution on the Facebook page before it gets closed, TestCafe will unpause the test execution on the MySlo page.

```js
import { Selector } from 'testcafe';

fixture `MySlo`.page`http://myslo.ru`;


const credentials = {
    facebook: {
        username: '',
        password: ''
    }
};

const myslo = {
    login: {
        mainButton:     Selector('body > div.main > div.head.tiny-hide > div > noindex:nth-child(5) > div > div.uactionbutton > a.uactionbutton-login'),
        facebookButton: Selector('#Login-registration > div > div.padding > noindex > div.social-login-list > a:nth-child(3) > img')
    }
}

const facebook = {
    usernameEditor: Selector('#email'),
    passwordEditor: Selector('#pass'),
    loginButton:    Selector('#loginbutton')
}

test(`Facebook`, async t => {
    await t.wait(10000);
    await t.click(myslo.login.mainButton);
    await t.click(myslo.login.facebookButton);
    await t.typeText(facebook.usernameEditor, credentials.facebook.username);
    await t.typeText(facebook.passwordEditor, credentials.facebook.password);
    await t.click(facebook.loginButton);

    await t.debug();
    await t.debug();
});
```

**Comment by AlexKamaev** [comment]
```JS
import { Selector, ClientFunction } from 'testcafe';
fixture `grammarly`
    .page('https://www.grammarly.com/signin');
const loginLink = Selector('div').withAttribute('data-qa', 'btnGoogleSignUp');
test('Login via Google', async t => {
    await t.click(loginLink)
        .wait(10000)
});
```
The Google Auth dialog is not opened after click

**Comment by miherlosev** [comment]
@AlexKamaev 

Click is performed too early and web-site script handles do not have time to set up.
Need to modify 'loginLink' selector as follows:
```js
import { Selector } from 'testcafe';

fixture `grammarly`
    .page('https://www.grammarly.com/signin');

const loginLink = Selector('div')
    .withAttribute('data-qa', 'btnGoogleSignUp')
    .find('div').withText('Continue with Google');

test('Login via Google', async t => {
    await t
        .click(loginLink)
        .wait(10000);
});
```

**Comment by AndreyBelym** [comment]
I guess this testing round is closed.
