### ISSUE TITLE
access url directly using --proxy-bypass not working

### ISSUE THREAD

**Issue by nelhu** [DevExpress/testcafe#4933]
### What is your Test Scenario?
I am using an iOS webview device to connect the URL of testface server
and the test page is nothing special but with an iframe element which src=https://__bridge_loaded__
 
### What is the Current behavior?
my page loaded correctly bu iframe failed
the src attribute were modified, current is src="http://172.16.50.108:4002/pze8awgHK!i/https://bridge_loaded__"
 
### What is the Expected behavior?
I want access my src directly, not by proxy
 
### What is your web application and your TestCafe test code?
I used testcafe@1.8.3 and my config file is blew
```js
{
  "browsers": "chrome",
  "speed": 0.3,
  "qrCode": true,
  "skipJsErrors": false,
  "pageLoadTimeout": 1000,
  "port1": "4001",
  "port2": "4002"
}
```

my page served at port 3000

my index.test.js

```js
import { ClientFunction } from 'testcafe';

export const delay = ms => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({ message: 'delay...' });
    }, ms);
  });
};

const start = ClientFunction(() => {
  return new Promise(resolve => {
    return delay(50000).then(() => resolve('balabala'));
  });
}, { dependencies: { delay } });


fixture `execute client script`
  .page('http://localhost:3000');

test('start', async t => {
  const res = await start();
  console.log('res: ', res);

  await t
    .expect(device).ok()
});
```

I tried this
```bash
testcafe index.test.js  --proxy-bypass https://__bridge_loaded__
```
and this 
```bash
testcafe index.test.js  --proxy 127.0.0.1 --proxy-bypass https://__bridge_loaded__
```
both are failed;

**all I want is access my src directly**
Anyone who can help me would appreciated a lot!

this is the error
![image](https://user-images.githubusercontent.com/24311105/78030498-c672fc80-7394-11ea-9588-b9526d1b9690.png)

**Comment by nelhu** [comment]
I wonder how the --proxy-by-pass get work? or I did the wrong usage?
I run command just as document did
```bash
npx testcafe remote index.test.js --proxy-bypass https://__bridge_loaded__
```
but my iframe src was still proxied as "http://myip/xx/https://__bridge_loaded__"

## all I want is access my src "https://__bridge_loaded__" directly

**Comment by arubtsov** [comment]
Hello @nelhu,

As stated in the [docs](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--proxy-host) TestCafe's `--proxy`, the CLI option specifies the proxy server used in your local network to access the Internet and `--proxy-bypass` requires that TestCafe bypasses that proxy server to access the specified resources. These options are not intended to work with the internal TestCafe proxy mechanism.

**Comment by nelhu** [comment]
> Hello @nelhu,
> 
> As stated in the [docs](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--proxy-host) TestCafe's `--proxy`, the CLI option specifies the proxy server used in your local network to access the Internet and `--proxy-bypass` requires that TestCafe bypasses that proxy server to access the specified resources. These options are not intended to work with the internal TestCafe proxy mechanism.

Thanks for your reply, what should i do ?
I want access my src "https://__bridge_loaded__" directly

**Comment by arubtsov** [comment]
Internal proxy is essential for TestCafe to automate user actions so TestCafe does not offer a way to disable it. Please stay tuned to the [original issue](https://github.com/DevExpress/testcafe/issues/3904). We do not have a workaround for it, but this issue is in the current sprint.

**Comment by nelhu** [comment]
> Internal proxy is essential for TestCafe to automate user actions so TestCafe does not offer a way to disable it. Please stay tuned to the [original issue](https://github.com/DevExpress/testcafe/issues/3904). We do not have a workaround for it, but this issue is in the current sprint.

OK, thanks a lot! I expect resolving origin issue so much
