### ISSUE TITLE
Testcafe, Firebase, Roles seem not to work together.

### ISSUE THREAD

**Issue by viking2917** [DevExpress/testcafe#4939]
https://stackoverflow.com/questions/60979064/anyone-have-testcafe-firebase-and-testcafe-roles-working-together

### What is your Test Scenario?

 
Would like to use Firebase for user Authentication, Testcafe Roles to manage roles during multi-user test execution. 

### What is the Current behavior?

When using a Role that is on a Firebase-based website, after defining a role, and doing useRole, then exiting useRole and moving to next test case step, the role state is not preserved.
 
### What is the Expected behavior?

The role state should be preserved.  (in my example, a check box is set during the Role initiation, but after exiting useRole, the checkbox state is lost). (This is a small example, my larger app has the problem on a larger scale. This occurred on my own app after switching from an early version of Firebase to the current release of Firebase). 

### What is your web application and your TestCafe test code?

The following test definition shows the problem. 

```
import { Selector, Role } from 'testcafe';

const ackTerms = Selector('span.mdl-checkbox__tick-outline');
const checkBox = Selector('.mdl-checkbox.is-checked');

const role1 = Role('https://friendly-pix.com/', async t => {
    await t
	.expect(checkBox.count).eql(0)
	.click(ackTerms) 
	.expect(checkBox.count).eql(1)    //on
	.click(ackTerms)
	.expect(checkBox.count).eql(0)    // off
	.click(ackTerms) 
	.expect(checkBox.count).eql(1);    // on, when we exit Role creation.
    // at this point the check box is checked.
}, {preserveUrl: true});

fixture `Friendly Pix test`
    .page `https://friendly-pix.com/`;

test('Roles test', async t => {
    await t
	.wait(5000)   // just let everything settle down.

	.useRole(role1)
    // when useRole is done, the check box should be still checked, however when you get to this breakpoint it will not be.
	.expect(checkBox.count).eql(1)

    // but clicking still works...if you remove the above assertion.
	.click(ackTerms)  //off
	.click(ackTerms); //on
});

``` 

<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
1.8.3
* node.js version:                    
v8.9.4
* command-line arguments:  
testcafe chrome test.js
* browser name and version: 
* platform and version:          
macOS 10.14.6
* other:

**Comment by miherlosev** [comment]
Hi @viking2917

The [Roles](https://devexpress.github.io/testcafe/documentation/test-api/authentication/user-roles.html) functionality doesn't store the whole page state. It makes a snapshot of the cookie, sessionStorage, localStorage and applies this snapshot after the `t.useRole` call.

We have a suggestion to implement the capability to dump the whole page state - [https://github.com/DevExpress/testcafe/issues/3286](https://github.com/DevExpress/testcafe/issues/3286).

Also, Firebase applications usually use the [indexedDb](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) database to store their data. TestCafe doesn't include data from `indexedDb` databases in the snapshot created by `Roles`. In some cases, it means that the `Roles` functionality will incorrectly work with a Firebase application.
We have a suggestion to add the `indexedDb` data to the snapshot created by the `Roles` functionality - [https://github.com/DevExpress/testcafe/issues/2420](https://github.com/DevExpress/testcafe/issues/2420)

Please track both these suggestions to be informed of our progress.

**Comment by viking2917** [comment]
Hi @miherlosev Thanks so much that clarifies what's happening. I saw this  in trying to produce a larger problem - that larger problem (firebase login information wasn't correctly getting restored when I changed roles) is explained by the notes on https://github.com/DevExpress/testcafe/issues/2420 - I will follow that issue for further info.

Thanks! Love TestCafe, great tool.

**Comment by viking2917** [comment]
(The implication, if I understand correctly, is that newer versions of Firebase cannot be used with TestCafe Roles. That's a pretty serious limitation, if I understand correctly....)
