### ISSUE TITLE
Unable to locate an element in nested shadow root DOM

### ISSUE THREAD

**Issue by A30004314** [DevExpress/testcafe#4943]
Trying to locate an element in the DOM mentioned in the attached screenshot using below methods :

Method 1 : 
const shadowInput = Selector(() => document.querySelector('app-root').shadowRoot.querySelector('agl-ds-guided-container').querySelector('agl-ds-guided-banner').shadowRoot.querySelector('agl-ds-h1.guided-banner-container__h1').querySelectorAll('span'));

Method 2:
const demoPage = Selector('app-root');

const guidedContainer = Selector(() => {
    // @ts-ignore: Cannot find name 'demoPageSelector'.
    return demoPageSelector().shadowRoot.querySelector('agl-ds-guided-container')
}, { dependencies: { demoPageSelector: demoPage } });

const guidedBanner = Selector(() => {
    // @ts-ignore: Cannot find name 'demoPageSelector'.
    return guidedBannerSelector().shadowRoot.querySelector('agl-ds-guided-banner')
}, { dependencies: { guidedBannerSelector: guidedContainer } });

const guidedh1 = Selector(() => {
    // @ts-ignore: Cannot find name 'demoPageSelector'.
    return guidedh1Selector().shadowRoot.querySelector('agl-ds-h1')
}, { dependencies: { guidedh1Selector: guidedBanner } });

const span = Selector(() => {
    
    // @ts-ignore: Cannot find name 'demoPageSelector'.
    return spanSelector().shadowRoot.querySelectorAll('span');
}, { dependencies: { spanSelector: guidedh1 } });

None of the code is able to locate the element.  either it gives undefined null error or annot obtain information about the node because the specified selector does not match any node in the DOM tree.
![image](https://user-images.githubusercontent.com/58277772/78312094-62238900-759e-11ea-9fe6-104b7522fe4c.png)

**Comment by aleks-pro** [comment]
Please provide us with the `html` page on which you are trying to execute selectors, so we will be able to find a suitable solution for you.

**Comment by A30004314** [comment]
Saving html or copying html elements from browser console( as shown in above screen shot) is not saving the page with correct tags because of shadow root.  

I am able to locate  app-root element using **const demoPage = Selector('app-root');**
but unable to locate guided-container under app-root  using 
**const guidedContainer = Selector(() => {
    // @ts-ignore: Cannot find name 'demoPageSelector'.
    return demoPageSelector().shadowRoot.querySelector('agl-ds-guided-container')
}, { dependencies: { demoPageSelector: demoPage } });**

**Comment by alexey-lin** [comment]
As far as I can see from the screenshot, the `span` you are trying to locate is in the top-level Shadow DOM, not in the nested one. So `const shadowInput = Selector(() => document.querySelector('app-root').shadowRoot.querySelector('agl-ds-guided-container').querySelector('agl-ds-guided-banner').querySelectorAll('span'));` should work for you. Please feel free to reopen this issue if it doesn't.
