### ISSUE TITLE
'Content of the iframe did not load' for IE 11

### ISSUE THREAD

**Issue by rob4629** [DevExpress/testcafe#4945]
### What is your Test Scenario?

We use 3rd party iframes on our site (Stripe) for collecting payment information. We have a payment form which is used on 2 different pages, and the functionality is the same. I would expect TestCafe to behave the same on both pages... when running with IE 11.
 
### What is the Current behavior?

I'm seeing a weird issue when running TestCafe on IE 11 where on one of our pages (Membership/Contributions) TestCafe can access the iframe and the test passes... however on another page (Promotion), we get the error: `Content of the iframe in which the test is currently operating did not load.`. It uses the same payment form, so I'm unsure of what the issue is.
 
### What is the Expected behavior?

Behaviour should be consistent, with Testcafe able to type in these payment iframes.

### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>
https://www.change.org
<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 fixture('Promote As Guest').page('https://www.change.org/');

test('Promote as guest with credit card, decline membership upsell', async t => {
  const emailAddressInput = Selector('[data-testid="input_email"]').filterVisible();
  const confirmationEmailInput = Selector('[data-testid="input_confirmation_email"]').filterVisible();

  await t
    .navigateTo('/p/the-world-send-matt-damon-to-mars-to-recover-opportunity/sponsors/new')
    .typeText(Selector('input[name=amount]'), '123', { replace: true, speed: 0.3 });

  // await t.click(Selector('[id="next-step"]'));  // Sometimes this button appears (on Chrome)

  await t
    .typeText(emailAddressInput, 'Random@email.com')
    .typeText(confirmationEmailInput, 'Random@email.com')
    .typeText(Selector('[data-testid="input_first_name"]'), 'Random')
    .typeText(Selector('[data-testid="input_last_name"]'), 'Name');

  // enter payment details
  await t
    .switchToIframe(Selector('[data-testid="credit-card-number"] iframe'))
    .typeText(Selector('input[name="cardnumber"]'), '1234 1234 1234 1234', { replace: true })
    .switchToMainWindow()

    .switchToIframe(Selector('[data-testid="credit-card-expiry"] iframe'))
    .typeText(Selector('input[name="exp-date"]'), '1124', { replace: true, speed: 0.3 })
    .switchToMainWindow()

    .switchToIframe(Selector('[data-testid="credit-card-cvc"] iframe'))
    .typeText(Selector('input[name="cvc"]'), '123', { replace: true, speed: 0.3 })
    .switchToMainWindow();

  await t.click(Selector('[data-testid="submit-payment-button"]'));
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```
Promote as guest with credit card

   1) Content of the iframe in which the test is currently operating did not load.

      Browser: Internet Explorer 11.0 / Windows 10
      (https://automate.browserstack.com/builds/**/sessions/**)

         30 |    .typeText(Selector('[data-testid="input_last_name"]'), 'Name');
         31 |
         32 |  // enter payment details
         33 |  await t
         34 |    .switchToIframe(Selector('[data-testid="credit-card-number"] iframe'))
       > 35 |    .typeText(Selector('input[name="cardnumber"]'), '1234 1234 1234 1234', { replace: true })
         36 |    .switchToMainWindow()
         37 |
         38 |    .switchToIframe(Selector('[data-testid="credit-card-expiry"] iframe'))
         39 |    .typeText(Selector('input[name="exp-date"]'), '1124', { replace: true, speed: 0.3 })
         40 |    .switchToMainWindow()



 1/1 failed (1m 02s)
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:  1.8.3                 
* node.js version: 12.14.1                   
* command-line arguments:  testcafe browserstack:ie 
* browser name and version: IE 11 
* platform and version:  Windows 10        
* other:

**Comment by aleks-pro** [comment]
Hello,

Thank you for the provided info. I've reproduced the issue. We will research it and update this thread as soon as we have any results.

**Comment by sharda-Mahendra-cko** [comment]
Is there any update on this issue?I am facing similar issue where test fails with error `Content of the iframe to which you are switching did not load.`
This works on all other browser type and just a limitation on IE.
Internet Explorer 11.0 / Windows 10
Testcafe Version-1.10.1
