### ISSUE TITLE
Testcafe based selector Convertor for coverting the xpath to appropriate selector

### ISSUE THREAD

**Issue by SubraGomz** [DevExpress/testcafe#4947]
### What is your Test Scenario?
Difficult to find selectors for some use cases 
### What are you suggesting?
If you can provide a convertor for converting the normal xpath to testcafe based selector, will be more efficient to work on testcafe

### What alternatives have you considered?
Don't have any alternatives for issues like https://stackoverflow.com/questions/61033117/how-to-write-xpath-for-text-after-br-tag-using-testcaf%c3%a9

**Comment by miherlosev** [comment]
Hi @SubraGomz

There are two ways to achieve your goal:

* don't convert XPath selectors into TestCafe Selectors. Use XPath selectors directly in your tests (see an example [here](https://github.com/DevExpress/testcafe-examples/tree/master/examples/use-xpath-selectors))
* convert XPath selectors into CSS selectors using any module from npm: [xpath-to-css](https://www.npmjs.com/package/xpath-to-css), [xpath2css](https://www.npmjs.com/package/xpath2css), etc.
