### ISSUE TITLE
Enters a loop when using Azure AD for authentication when running tests in chrome (both headless and browser) after MSAL library upgrade

### ISSUE THREAD

**Issue by hkaurSL** [DevExpress/testcafe#4958]
### What is your Test Scenario?
Log In to the app and land on the application Home page when authentication is successful
 
### What is the Current behavior?
Tests are failing at authentication step, app enters a loop on the LogIn page.
 
### What is the Expected behavior?
Test user is able to log in and, upon success lands on the application Home Page
 
### What is your web application and your TestCafe test code?
We can do a screen share, but due to security can't share the app information here.
 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
testcafe version: 1.8.3
node.js version: v10.16.3
command-line arguments: none

browser name and version: Chrome 80, Firefox 75, Edge 44.18362
platform and version: Windows 10 Enterprise 1909

**Comment by LavrovArtem** [comment]
This information is not sufficient to reproduce the issue. Could you please share a minimal project with us? We will examine it and check for a suitable solution.

**Comment by hkaurSL** [comment]
I am working on providing your team a minimal solution. Thanks.

**Comment by hkaurSL** [comment]
Here is the solution for your to try reproducing the issue:
Instructions:
1. Extract contents of zip file
2. Open a command prompt where the files were extracted
3. Run 'npm install'
4. Run 'npm start'
5. Open a new commpant prompt in the same directory
6. Run 'npm run testcafe'
[AngularB2C_Test.zip](https://github.com/DevExpress/testcafe/files/4458972/AngularB2C_Test.zip)

Let us know if you have any other questions. 

Thank you.

**Comment by hkaurSL** [comment]
> This information is not sufficient to reproduce the issue. Could you please share a minimal project with us? We will examine it and check for a suitable solution.
Here is the solution for your to try reproducing the issue:
Instructions:
Extract contents of zip file
Open a command prompt where the files were extracted
Run 'npm install'
Run 'npm start'
Open a new commpant prompt in the same directory
Run 'npm run testcafe'
[AngularB2C_Test.zip](https://github.com/DevExpress/testcafe/files/4458974/AngularB2C_Test.zip)

**Comment by arubtsov** [comment]
Thank you for the example. In both tests login failed, however, I did not encounter any redirection loops while running them. We need some time to research this behavior and determine its cause.

**Comment by hkaurSL** [comment]
Thank you. Yeah it’s failed login that’s what we want to troubleshoot and resolve.




Harvinder Kaur | Consultant, Enterprise Applications
E hkaur@softlanding.ca
C 306.303.6003
http://www.softlanding.ca<http://www.softlanding.ca/>
[cid:image001.png@01D6119E.C769C130]

**Comment by hkaurSL** [comment]
> Thank you for the example. In both tests login failed, however, I did not encounter any redirection loops while running them. We need some time to research this behavior and determine its cause.

Hi,

Thank you for your response. Just wanted to reach out if there's an ETA on this?

Regards,
Harvinder

**Comment by alexey-lin** [comment]
Any personal estimate might be misleading, so I cannot give you precise time frames.
If you wish to participate, your PR would be highly appreciated.

**Comment by hkaurSL** [comment]
Hi,

One of our teammate spent some more time looking into the issue, seems like testcafe’s proxy and additional security with MSAL is blocking stuff.

I see a number of people reported this issue, would appreciate an interim workaround to unblock teams. AT this point, testcafe is totally blocked for our team.

Thanks,

Harvinder Kaur | Consultant, Enterprise Applications
E hkaur@softlanding.ca
C 306.303.6003
http://www.softlanding.ca<http://www.softlanding.ca/>
[cid:image001.png@01D6172B.7D7D8920]

**Comment by miherlosev** [comment]
hkaurSL

Could you please run your tests with the latest TestCafe version `1.10.1` and let us know about the results?
