### ISSUE TITLE
Concurrently run tests don't run in multiple browser windows.

### ISSUE THREAD

**Issue by ChrstphGrnr** [DevExpress/testcafe#4959]
### What is your Test Scenario?
Running multiple tests (6) in multiple browser windows (5) with:
`"test:chrome:5": "testcafe -c 5 chrome './tests/bank app tests'"`
Test run timer without concurrency is 13s. 
 
### What is the Current behavior?
Once tests are executed, 5 browser windows appear, but two of them have tests executed in it. 
The other windows stay dark. After tests concluded, all windows are closed. 
Test run timer with concurrency is 13s as well. 
 
### What is the Expected behavior?
Test run timer should be significantly less and all browser windows should have tests executed in them.
See note under `Steps to Reproduce` below for the fix I found for this. 
When switching to v1.7.0 the above mentioned behavior was not present, the tests were executed in all 5 browser windows. 
 
### What is your web application and your TestCafe test code?

<details>
<summary>Website: http://zero.webappsecurity.com/index.html</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

[testfiles.zip](https://github.com/DevExpress/testcafe/files/4447439/testfiles.zip)

</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
	"name": "testcafe-project",
	"version": "1.0.0",
	"description": "first testcafe description",
	"main": "index.js",
	"scripts": {
		"test:chrome": "testcafe chrome './tests/bank app tests'",
		"test:chrome:5": "testcafe -c 5 chrome './tests/bank app tests'",
		"test:chrome:headless": "testcafe chrome:headless ./tests -s takeOnFails=true",
		"test:chrome:mobile": "testcafe chrome:emulation:device=iphone X ./tests -s takeOnFails=true",
		"test:chrome:mobile:headless": "testcafe chrome:headless:emulation:device=iphone X ./tests -s takeOnFails=true",
		"test:safari": "testcafe safari ./tests -s takeOnFails=true",
		"test:safari:headless": "testcafe safari:headless ./tests -s takeOnFails=true",
		"test:firefox": "testcafe firefox ./tests -s takeOnFails=true"
	},
	"repository": {
		"type": "git",
		"url": "git+https://github.com/ChrstphGrnr/testcafe-project.git"
	},
	"keywords": [
		"testcafe",
		"automation",
		"tests"
	],
	"author": "ChrstphGrnr",
	"license": "MIT",
	"bugs": {
		"url": "https://github.com/ChrstphGrnr/testcafe-project/issues"
	},
	"homepage": "https://github.com/ChrstphGrnr/testcafe-project#readme",
	"dependencies": {
		"node": "10.7.0",
		"testcafe": "^1.8.3"
	}
}

```
</details>

<details>
<summary>Your complete test report:</summary>

```
> testcafe-project@1.0.0 test:chrome:5 /Users/chrstphgrnr/Development/Testing/Automation Challenge/testcafe project
> testcafe -c 5 chrome './tests/bank app tests'

 Running tests in:
 - Chrome 80.0.3987.163 / macOS 10.15.4

 Feedback form submission test
 ✓ User can submit Feedback form and see their name on the page after submission

 Send forgotten password test
 ✓ User can request new password to be sent through his email

 Login Test
 ✓ User cannot login with invalid credentials
 ✓ User CAN login with valid credentials

 New payee test
 ✓ User can add a new payee to the list of payees

 Search form test
 ✓ User can submit form and see results page


 6 passed (13s)

```
</details>

<details>
<summary>Screenshots:</summary>
<img width="1748" alt="Screen Shot 2020-04-07 at 5 21 58 PM" src="https://user-images.githubusercontent.com/46858206/78728492-b8712e80-78f4-11ea-91b0-1afe1cf4b88a.png">

</details>

### Steps to Reproduce:

**Note: This behavior was only observed when using testcafe v1.8.3 or v1.8.4 
           When using testcafe v1.7.0 the tests ran concurrently in the 5 different browser windows.** 

### Your Environment details:
 
* testcafe version:                   v1.8.3 OR v1.8.4
* node.js version:                    v10.7.0
* command-line arguments: "testcafe -c 5 chrome './tests/bank app tests'"
* browser name and version: Chrome Version 80.0.3987.163
* platform and version:          MacOS 10.15.4

[](url)

**Comment by AlexKamaev** [comment]
The issue exists in version `1.8.3`. We fixed it in `1.8.4`. I checked your tests (except those with the `login` module) and they work as expected. Please check that you are using version `1.8.4`.
