### ISSUE TITLE
Hammerhead changes a behaviour of original XHR status code evaluation

### ISSUE THREAD

**Issue by eugene-tkachenko** [DevExpress/testcafe#4961]
### What is your Test Scenario?
Looks like testcafe(or testcafe-hammerhead) evaluates some XHR statuses not like it happens in "real world". Here are the steps that my testcafe test performs:

1) Open a login page
2) Execute login with a valid creds
3) Wait until all resources are loaded up

After that I'm getting a "Server Error" popup inside my app because it thinks(front-end controller) that something went wrong and some of the XHRs have `403/404/500/504` error. If I execute the same steps in my browser or even in the same browser that was instanciated by testcafe but without using the testcafe-hammerhed proxy prefix I wouldn't see the same error. Why it happens: if you open the Network tab you will see that some of XHRs really got `403/404` errors and they were evaluated by `testcafe-hammerhead.js`. Response bodies has the error nodes as well. But in "real world" the same XHRs get `200` response code even though it has the same errors in response bodies. It happens because they were evaluated by `VM` or in other words - by custom/native script and they got its custom response codes.
 
### What is the Current behavior?
Testcafe doesn't evaluate a response code of XHR like it would be evaluated in "real world". Some of XHRs get `403/404` errors because these request were executed and processed by testcafe separately from the app-custom script. 

P.S. Real world - outside the testcafe proxy.
 
### What is the Expected behavior?
Testcafe should emulate a native browser behaviour. Probably something related was fixed and discussed here - https://github.com/DevExpress/testcafe/issues/1973
 
 
### Your Environment details:
 
* testcafe version:                   1.8.3
* node.js version:                    v12.16.1
* command-line arguments: testcafe chrome <name_of_spec_file>.js
* browser name and version: Chrome 80.0.3987.16
* platform and version:          macOS 10.15.3 Catalina

![40](https://user-images.githubusercontent.com/6412195/78782244-5bd04b00-79aa-11ea-8942-a4a9f7bfb2f4.png)

**Comment by LavrovArtem** [comment]
This information is not sufficient to reproduce the issue. Could you please share a minimal project with us? We will examine it and check for a suitable solution.
