### ISSUE TITLE
React Devtools raise an error from Hammerhead

### ISSUE THREAD

**Issue by aaronmcadam** [DevExpress/testcafe#4966]
### What is your Test Scenario?

I'd like to be able to use the React devtools to help debug test failures.

 
### What is the Current behavior?

When I open the Chrome devtools, I see a lot of the following errors:

![CleanShot 2020-04-09 at 11 38 19](https://user-images.githubusercontent.com/37928/78886934-f1c1af80-7a56-11ea-8921-2348e101ac4e.gif)

![CleanShot 2020-04-09 at 11 15 49@2x](https://user-images.githubusercontent.com/37928/78885410-72cb7780-7a54-11ea-8789-481b828986da.jpg)

This issue also breaks the test runner because the issue raises an error in the JavaScript:

![CleanShot 2020-04-09 at 11 35 18@2x](https://user-images.githubusercontent.com/37928/78886494-3862da00-7a56-11ea-8b29-3bfe81eb2817.jpg)

### What is the Expected behavior?

That I can use the React devtools.
 
### What is your web application and your TestCafe test code?

This is an electron project.

### Steps to Reproduce:

This can be demonstrated by following these steps:

1. Clone https://github.com/aaronmcadam/electron-react-boilerplate

2. Run `yarn`.

3. Run `yarn build-e2e`

4. Run `yarn test-e2e-live`

 
### Your Environment details:
 
* testcafe version: 1.8.4              
* node.js version: 12.14                  
* command-line arguments:  
* browser name and version: Electron 7
* platform and version:  MacOS 10.15.4
* other:

**Comment by AlexKamaev** [comment]
Thank you for your input. There are some restrictions in using TestCafe along the React/Vue DevTools, so unfortunately you cannot run your React DevTool while TestCafe is running.

**Comment by aaronmcadam** [comment]
Ok, thanks for the response.
