### ISSUE TITLE
Testcafe hangs if using live reload and skipped tests in file

### ISSUE THREAD

**Issue by ShonP** [DevExpress/testcafe#4967]
### What is your Test Scenario?
testing nothing at all
 
### What is the Current behavior?
testcafe hangs if the script has live reload and skipped test
 
### What is the Expected behavior?
testcafe finish to run if there is a skipped test
 
### What is your web application and your TestCafe test code?
https://github.com/ShonP/testcafe-live-skip-bug
 
<details>
<summary>Your website URL (or attach your complete example): https://github.com/ShonP/testcafe-live-skip-bug </summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>
https://github.com/ShonP/testcafe-live-skip-bug
 
fixture('Test Example');
test('Test 1', async (t) => {});
test.skip('Test 2', async (t) => {});

</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

$ testcafe -L chrome test.e2e.js

Live mode is enabled.
TestCafe now watches source files and reruns
the tests once the changes are saved.
                    
You can use the following keys in the terminal:
'Ctrl+S' - stops the test run;
'Ctrl+R' - restarts the test run;
'Ctrl+W' - enables/disables watching files;
'Ctrl+C' - quits live mode and closes the browsers.

Watching the following files:
  /Users/shonpazarker/projects/testcafe-test/test.e2e.js
 Running tests in:
 - Chrome 80.0.3987.163 / macOS 10.14.6

 Test Example
 ✓ Test 1
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:
1. clone https://github.com/ShonP/testcafe-live-skip-bug
2. run yarn
3. run yarn test

expected: 1 test pass 1 test skip
resulted: 1 test pass, testcafe hangs
 
* testcafe version:                   1.8.2
* node.js version:                    
* command-line arguments:  
* browser name and version: CHROME 80
* platform and version:         macos 10.14.6 mojave

**Comment by alexey-lin** [comment]
Hi @ShonP,
Thanks for contacting us. I've reproduced the issue. We'll look into it.
