### ISSUE TITLE
To run the tests on mobile browsers during Github Actions CI

### ISSUE THREAD

**Issue by AnushaErrabelli** [DevExpress/testcafe#4970]
### What is your Test Scenario?
To run the tests on mobile browsers during Github Actions CI

### What are you suggesting?
I would like to test the application which supports mobile and desktop versions. Currently able to run the tests on chrome headless, fire fox headless during CI run. I would like to add it to more browsers (Safari&IE) and mobile browsers (Safari&Chrome) .

### What alternatives have you considered?
I haven't think of other alternatives yet!

**Comment by AlexanderMoiseev** [comment]
Hello,

Github actions do not support mobile browsers out of the box. However, you can still test your application across on-demand browsers, operating systems and mobile devices using [testcafe-browser-provider-browserstack plugin](https://itnext.io/using-testcafe-with-browserstack-ea180520feb). You might also want to take a look at the following [article](https://www.npmjs.com/package/testcafe-browser-provider-browserstack). Try this and let me know if any questions arise.

**Comment by AnushaErrabelli** [comment]
@AlexanderMoiseev thank you so much for the quick response I appreciate it, I will try provided plugin
