### ISSUE TITLE
TestCafe reloading page while it's loading causing local storage to be cleared

### ISSUE THREAD

**Issue by Cesaario** [DevExpress/testcafe#4971]
### What is your Test Scenario?
I have an app that uses microsoft login to authenticate the user. I managed to skip that login process and mock the access tokens in the local storage. The page then starts loading and pulling data from the backend using the data in the local storage.
 
### What is the Current behavior?
TestCafe is reloading the page several times while it's loading, clearing the local storage, causing an infine loading.
 
### What is the Expected behavior?
I expect the page not to be reloaded.
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>
It's being run in my local machine and I can't share the whole project.

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

import { Selector } from 'testcafe';
import Login from '../commands';

fixture `Getting Started`
    .page `http://localhost:3000/`;

test('My first test', async t => {
    Login();
    await t
    .hover(Selector('.destacamento'));

}); 

</details>

<details>
<summary>Your complete configuration file (if any):</summary>
N/A

</details>

<details>
<summary>Your complete test report:</summary>
N/A

</details>

<details>
<summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/17167472/78912318-d3ab7d80-7a5d-11ea-8af5-4406b59e2070.png)

</details>

### Steps to Reproduce:

Sorry, I can't provide a way to reproduce it since I can't share the project.
 
### Your Environment details:
 
* testcafe version:                   1.8.4
* node.js version:                    12.16.1
* command-line arguments:  testcafe chrome test.js
* browser name and version: Chrome 80
* platform and version:          Windows
* other:

**Comment by AlexanderMoiseev** [comment]
The information you provided is insufficient to determine the cause of the problem. Please provide the minimal code of your project reproducing the problem so that we can research it on our side.
