### ISSUE TITLE
PDF printing broken by #4300

### ISSUE THREAD

**Issue by taylor-cedar** [DevExpress/testcafe#4973]
Upgrading from version 1.2.1 to 1.8.4 caused my PDF tests to break. I load a PDF in an iframe and then trigger a print via `iframeWindow.print()`. This behavior no longer works in TestCafe, but works in standard Chrome.

It is caused by this change in #4300 . 
https://github.com/DevExpress/testcafe/pull/4300/files#diff-6a1c34d02133d08d11fa2458ab76ee7aR22
```
'plugins': {
  'always_open_pdf_externally': true
 },
```

### What is your Test Scenario?
Load a PDF in an iframe and call `iframeWindow.print()`
 
### What is the Current behavior?
Print is broken because PDFs are considered cross-frame if they download a file instead of load in the browser. 
```
 JavaScript error details:
      Error: Blocked a frame with origin "http://192.168.0.10:54649" from
```
 
### What is the Expected behavior?
iframe.print() works correctly and shows print modal
 
### What is your web application and your TestCafe test code?
Load a PDF in an iframe (same domain). Try to run `iframe.print()`. It now fails

My suggestion is we revert this change.

**Comment by AlexanderMoiseev** [comment]
Hello,
The information you provided is insufficient to determine the cause of the issue. Please share more details and send us a small project or video reproducing the problem.

**Comment by taylor-cedar** [comment]
@aleks-pro Here is some example code that works in the browser, but fails in TestCafe.

https://run.plnkr.co/preview/ck8v7tqhc00083f63t2vbtuk1/

If you click the "print PDF" button, it work in Chrome. Since TestCafe has set the setting above it fails with the error described above.

Here is the link to edit the code if you need. https://plnkr.co/edit/064te1MvmHwIQw8q?open=lib%2Fscript.js

**Comment by AlexKamaev** [comment]
I was able to reproduce the issue. However, I do not think that we need to roll back the `always_open_pdf_externally` changes. I think that in test cases, if I click the `pdf` link, I want to check that the file is downloaded, but not displayed.

Could you please clarify your scenario?

* you click the button
* the print dialog appears
* what do you do next? How do you handle this dialog? How can you be sure that your test passes?


Moreover, we have plans to handle the `print` dialog as in the `alert/confirm` case: [https://github.com/DevExpress/testcafe/issues/2331](https://github.com/DevExpress/testcafe/issues/2331)

**Comment by taylor-cedar** [comment]
> I want to check that the file is downloaded, but not displayed.

Files are not downloaded if they are in an iframe with setting `always_open_pdf_externally`. It just throws an error when you access `.print` on the iframe window

> Could you please clarify your scenario?

- .setNativeDialogHandler(() => true)
- .click(PaymentInfo.PRINT_RECEIPT)
- Dialog disappears (no JS error)
- Test another part

**Comment by aleks-pro** [comment]
It's true that error occurred after the `always_open_pdf_externally` changes. But it's not clear how you managed to handle this dialog. So, could you please provide your full test code, which can help us to reproduce the scenario on how it worked before.

**Comment by taylor-cedar** [comment]
@aleks-pro I posted the code above... I can't copy the exact code because it's proprietary. Here is the code that matters.

```js
test("a test", async () => {
  // ... Navigate to print button

  await t.setNativeDialogHandler(() => true).click(SELECTOR_TRIGGERS_PRINT_DIALOG);

  // .. Some stuff after
  await t.click(SOMETHING_ELSE_OUTSIDE_PRINT_DIALOG)
});
```

**Comment by AlexanderMoiseev** [comment]
Hello, the test case you provided should not work in testcafe 1.2.1 as this functionality was not implemented. We reproduced this scenario using the testcafe version 1.2.1 and, as expected, native dialog handler for the print dialog does not work as the test stops execution and hangs, please see the attached video. However, as @AlexKamaev mentioned, we have plans to handle the print dialog in the same manner like it is done in the alert/confirm case #2331 .

Also, please review the sample code below for the project and the test and let us know if our steps of reproducing the problem match your case

```html
<!doctype html>

<html>
  <body>
    <button class="btn" onclick="window.frames['printable'].print()">Print PDF</button>
    <iframe name="printable" src="./some.pdf">
  </body>
</html>
```
```js
test("a test", async () => {
  await t.setNativeDialogHandler(() => true).click('.btn'); //hangs here 
});
```

**Comment by taylor-cedar** [comment]
@AlekseyMartynov It does work in my case, you just need to click something else on the page after the print as I describe above. I fixed your example to match the code I wrote above. Test for yourself, it passes.

```html
<!doctype html>

<html>
  <body>
    <button class="btn" onclick="window.frames['printable'].print()">Print PDF</button>
    <iframe name="printable" src="./some.pdf"></iframe>
    <div>
      <button class="btn2">Another button</button>
    </div>
  </body>
</html>
```

```js
// This test passes and use to throw an error
test("a test", async () => {
  await t.setNativeDialogHandler(() => true).click('.btn');

  // Click something outside the print dialog
  await t.click("btn2");
});
```

**Comment by SergeyShurygin** [comment]
Hi,
We've discussed your example with the team and found the following:
 - The setNativeDialogHandler function is not suitable here - it didn't work with the print dialog in v1.2.1 and in v1.8.4. So, the test just runs further with the print dialog shown in the browser.
 - Such functionality (window.print()) will not work for users who disabled the pdf view inside the browser or in browsers without pdf support.
 
Also, we've added the always_open_pdf_externally option to prevent tests from hanging when a direct link to a pdf file is clicked, so it would be unsafe to roll it back.

So, I recommend you rewrite the test to check if the pdf file was requested by the browser and the print() function was actually called:

```js
import { RequestMock, ClientFunction } from 'testcafe';
let pdfRequested = false;
const isPrintOpened = ClientFunction(() => window.printOpened);
const pdfMock = RequestMock()
    .onRequestTo(/.*pdf/)
    .respond((req, res) => {
        pdfRequested = true;
        return 'OK';
    });
const printMock = () => {
    window.print = () => window.top.printOpened = true;
};
fixture('test login functionality')
   .page('./test.html')
   .requestHooks(pdfMock)
   .clientScripts({ content: `(${printMock.toString()})()` });
test("a test", async t => {
    await t.click('#print');
    await t.expect(pdfRequested).ok();
    await t.expect(isPrintOpened()).ok();
});
```
