### ISSUE TITLE
Snap installed firefox is not starting

### ISSUE THREAD

**Issue by oguera** [DevExpress/testcafe#4974]
### What is your Test Scenario?

I want start testcafe browser tests by executing `testcafe firefox path/to/my/tests`. 

### What is the Current behavior?

Firefox starts with a dialog `Your Firefox profile cannot be loaded. It may be missing or inaccessible.` and closes after confirming the dialog. However: If i start testcafe by providing the path to my installation (`/snap/firefox/current/firefox-bin`) everything works fine.

### What is the Expected behavior?

Firefox should start if installed via snap.

### Steps to Reproduce:

1. install firefox via [snap](https://snapcraft.io/)
2. run testcafe like this `testcafe firefox path/to/tests`
3. firefox should start but with the dialog described above
 
### Your Environment details:
 
* testcafe version:                   1.8.4
* node.js version:                    12.16.1
* command-line arguments:  `testcafe firefox path/to/tests`
* browser name and version: firefox 75.0 (current@snap)
* platform and version:          ElementaryOS (Linux 5.3.0-45-generic #37~18.04.1-Ubuntu SMP Fri Mar 27 15:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux)

What i've done so far:

- The dialog only pops up if testcafe starts firefox not when i start it myself to browse arround. I followed the [steps provided by mozilla regarding this dialog](https://support.mozilla.org/en-US/kb/how-run-firefox-when-profile-missing-inaccessible)

- I symlinked the .mozilla (config) folder from the ~/snap/firefox/common/.mozilla to ~/.mozilla

- I checked if testcafe detected firefox (`testcafe --list-browsers`) and it prints out `firefox`

**Comment by AlexKamaev** [comment]
We cannot pass a custom user profile if the browser is installed as snap package. It's better to install browsers using `app-get`.

As a workaround try to pass a custom profile to Fireox as described in the following article: [https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/user-profiles.html](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/user-profiles.html)
