### ISSUE TITLE
Tests Scheduling Policy

### ISSUE THREAD

**Issue by yashLadha** [DevExpress/testcafe#4989]
### What is your test scenario?

I have a test suite of several hundreds of tests (say 400 - 40 fixtures with 10 tests each) - each of them independent and the tests can run in any order.

### What am I doing?

I run these tests on my internal grid or a 3rd party cloud provider (like BrowserStack). Running all tests in a single browser instance takes a lot of time, so I execute tests in parallel as follows.
When I run the tests in parallel (say in 20 concurrent sessions using `--concurrency 20`), TestCafe automatically runs my 400 tests in these 20 browsers (selected in a random manner).

### What is the problem?
While the test execution times have reduced because of executing tests in parallel, debugging the failed tests is a huge pain because I now need to maintain a mapping (_for which I need to change my tests and hack around_) of which test ran on which browser (and also which video / logs to look at for further debugging).

### What is the ideal scenario?

Depending on my test requirements, I should be able to:

1. Run each test in a separate browser (with the concurrency that is specified) - so that each test has a separate video / logs. In my example, it would create 400 different sessions on my internal grid / 3rd party provider - so it is much easier for me to identify which video / logs to look at.
2. Run all tests in a fixture in a single browser (with the concurrency that is specified) - so that I can look at all logs of a fixture in a single place. In my example, it would create 40 sessions on my internal grid / 3rd party provider.

Respecting the concurrency params and queueing the tests to be run is something that needs to be looked at. In my case, I want 20 tests to run at a given point, and the remaining tests to be queued. Once a test finishes, another test can be dequeued (as long as the test queue is not empty) to maintain the desired concurrency.

### What are you suggesting?

I am suggesting that we have a couple of flags / args that help users to achieve the above. I'd suggest something like `--group-by` (`-g`) which takes the following values:

* `default`: the current behaviour and can be default for now. This can also be a fallback if the user passes an invalid argument (may be throw a warning?)
* `test`: used to run every test in a separate browser window (and hence, a different video & logs are generated)
* `fixture`: used to run all tests in a fixture in a separate browser window (and hence all tests in a single fixture are guaranteed to be in the same video / log file)
Eventually, `fixture` can be the default mode as it makes debugging much easier for us.
For example, to run my 400 tests in parallel (20 at a time), each in its own browser instance, I would use:
```bash
testcafe --concurrency 20 --group-by test <other params>
```

If I need to run all tests in a single fixture on the same browser instance, I'd use: 
```bash
testcafe --concurrency 20 --group-by fixture <other params>
```

### What alternatives have you considered?

Executing the test scripts in chunks (mimicking the above requirement myself using subprocesses and maintaining queues myself) but this is not a neat solution as lot of client-side script handling is required to first listen for completion of tests and then execute them. 

It would be better to have this feature enabled in the core library itself so that everyone can use this!

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. I feel that we already discussed similar suggestions in other issues:
1. https://github.com/DevExpress/testcafe-browser-provider-browserstack/issues/76
2. https://github.com/DevExpress/testcafe/issues/2011

Please use them for further discussions.
