### ISSUE TITLE
Selectors no longer work between 1.7.1 and 1.8.4aa

### ISSUE THREAD

**Issue by LyleMartin** [DevExpress/testcafe#4992]
I have had a difficult time getting Selectors to work with Isomorphic SmartClient v.10.  In version 1.7.1 the Selectors reasonably work in a limited fashion.  With a mixture of CSS and SCLocators using isc sclocator.  

I upgraded to TestCafe 1.8.4 because it is supposed to fix the "visible" issue. I have a component that is there but not visible, despite the fact I can click it.  So trying to set it visible within TestCafe code then click it.  Still get tons of errors.  But even worse, none of my previous code with the mixture of selectors and mentioned above work.  Pretty much the files fail on the first few lines, but none is reported. 

I read the release notes which were of no help.  

Any guidance or support, to learn how to make this work better  and more consistently (across versions) would be greatly appreciated.  I rolled things back to 1.7.1.  Actually have both versions available to test with.  So still stuck on the visible issue if I stay with 1.7.1.

**Comment by Dmitry-Ostashev** [comment]
Could you please share a test example illustrating the issues?

**Comment by sjt003** [comment]
Anecdotally, I've struggled at testcafe 1.8.2 with Selectors and buttons in angular 1.7.x app.

**Comment by LyleMartin** [comment]
Very simple code, that works in 1.7.1 but does not work at all in 1.8.2.  

fixture `Login, Create Standard Project`
    .page `http://192.168.2.86/mpes/login.jsp`

test(' Login, Create a Standard Project', async t => {
    const okButton  = Selector('input').withAttribute('name','ok')
    await t.click(okButton)
})

With the real code it goes on and does a bunch of things after this.  But with 1.8.2 it just dies from the very beginning ... object object errors etc.  Yet 1.7.1 finds the selectors and works fine.  I run them side by side. Baffling.  

I need 1.8.2 to fix the issue with a non-visible component.  Trying to set it to visible.  But cannot remotely get to that part.  1.8.2 cannot find anything .. no selectors.

**Comment by alexey-lin** [comment]
@LyleMartin,

Thank you for the information. I run this test against a simple page with a single button on it, and the test passed. I couldn't reproduce the issue. Could you also provide us with a project code or a public URL for a further investigation?

Please note that if it involves accessing any internal resources, we will need prior written approval from a website owner. It must permit DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes and can be sent to [support@devexpress.com](mailto:support@devexpress.com).
