### ISSUE TITLE
Cannot use React Developer Tools in Chrome after use of t.debug()

### ISSUE THREAD

**Issue by hinok** [DevExpress/testcafe#4997]
### What is your Test Scenario?

I want to use `t.debug()` and use `React Developer Tools` to check specific components `state` and `props`.
 
### What is the Current behavior?

It doesn't work.

```bash
Uncaught TypeError: Cannot read property 'source' of undefined
```
 
### What is the Expected behavior?

`React Developer Tools` (react-dev-tools) should work in Chrome.
 
### What is your web application and your TestCafe test code?

```
fixture `Debugger example`
    .page `https://reactjs.org/`;

test('Example', async t => {
    await t
        .debug()
        .click(Selector('a').withText('Docs'))
});
```
 
<details>
<summary>Your website URL (or attach your complete example):</summary>
https://reactjs.org/

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 fixture `Debugger example`
    .page `https://reactjs.org/`;

test('Example', async t => {
    await t
        .debug()
        .click(Selector('a').withText('Docs'))
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
testcafe chrome:userProfile src -S -s screenshots
```
</details>

<details>
<summary>Your complete test report:</summary>

```
N/A
```
</details>

<details>
<summary>Screenshots:</summary>

![Zrzut ekranu 2020-04-17 o 12 46 15](https://user-images.githubusercontent.com/1313605/79562170-e1d74a80-80aa-11ea-844f-c72955c26e5d.png)

![Zrzut ekranu 2020-04-17 o 12 46 25](https://user-images.githubusercontent.com/1313605/79562182-e865c200-80aa-11ea-8ac9-cd47daefca28.png)

![Zrzut ekranu 2020-04-8 o 12 40 34](https://user-images.githubusercontent.com/1313605/79560919-c2d7b900-80a8-11ea-8d64-c43f63a8bb05.png)

![Zrzut ekranu 2020-04-8 o 12 39 58](https://user-images.githubusercontent.com/1313605/79560951-cf5c1180-80a8-11ea-81d1-575541a0a2d0.png)

![Zrzut ekranu 2020-04-8 o 12 39 40](https://user-images.githubusercontent.com/1313605/79560964-d551f280-80a8-11ea-99e5-22255af39fdc.png)
</details>

### Steps to Reproduce:

1. Go to website: https://reactjs.org
3. Execute this command: `t.debug()` and try to use `React Developer Tools`
4. See the error: `Uncaught TypeError: Cannot read property 'source' of undefined`
 
### Your Environment details:
 
* testcafe version: `1.8.2`                 
* node.js version: `10.16.2`                   
* command-line arguments: `testcafe chrome:userProfile src -S -s screenshots` 
* browser name and version: `Chrome 80.x` 
* platform and version: `macOS 10.14.6`         
* other:

**Comment by alexey-lin** [comment]
Thank you for contacting us. Unfortunately, React/Vue Developer Tools cannot be used while TestCafe is running. It is a known limitation.

**Comment by hinok** [comment]
@alexey-lin Thanks for quick response. I didn't know about it and also it's not mentioned anywhere in the docs. Maybe it's worth to add a small note in FAQ (https://devexpress.github.io/testcafe/faq/)? 

Clear curiosity, is it not possible to make testcafe working with dev tools or the effort is not worth?

**Comment by Farfurix** [comment]
@hinok

Hello,

> I didn't know about it and also it's not mentioned anywhere in the docs.

We created a new issue based on your request. You can track our progress here: [https://github.com/DevExpress/testcafe/issues/4998](https://github.com/DevExpress/testcafe/issues/4998).

> Clear curiosity, is it not possible to make testcafe working with dev tools or the effort is not worth? I mean the cost of work, refactoring etc.

We don't have plans to work on this and haven't estimated the cost of such changes.
