### ISSUE TITLE
Refactor client scripts (move scripts to ES6)

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#50]
1) Linting (scripts and tests)
2) Constants (const keyword, new naming format)
3) Classes (use where possible, any object which has state now or init method or something like this should be turned into the classes and instantiated there necessary)
4) Arrows
5) Promises (get rid of the async module and callbacks)

**Comment by inikulin** [comment]
We need to get rid of callbacks as well and use promises instead

**Comment by inikulin** [comment]
I think we can close it for now.
