### ISSUE TITLE
filterVisibility behaviour change in v1.8.4

### ISSUE THREAD

**Issue by rob4629** [DevExpress/testcafe#5002]
### What is your Test Scenario?

I upgraded to the latest version, to take advantage of #4904. However, since doing so, unrelated functionality has now broken in our regression tests.

### What is the Current behavior?

 In order to reduce code duplication, we have 2 selector values for our `login` button (one is the element found when navigating to the login page, and the other is for our login modal), then use `.filterVisible()` to filter the visible element.

After upgrading, `await t.expect(loginButton.visible).ok();` now fails for some of our tests (_navigating to the login page_). Downgrading to 1.8.3 allows those tests to pass.

### What is the Expected behavior?

I would expect these same tests to pass in the latest version, and not have breaking changes with upgrading to the latest version. 

### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

http://www.change.org
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
import { Selector } from 'testcafe';

fixture('test login functionality').page('www.change.org');

test.only('Check for login button', async t => {
  const loginButton = Selector('#content [type="submit"], .js-login-button').filterVisible();

  await t
    .navigateTo('/login_or_join')
    .expect(loginButton.visible)
    .ok();
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```
test login functionality
 ✖ Check for login button (screenshots: /Users/**/artifacts/screenshots/test-1/_errors/1.png)

   1) AssertionError: expected false to be truthy

      Browser: Chrome 81.0.4044.113 / macOS 10.15.4
      Screenshot: /Users/**/artifacts/screenshots/test-1/_errors/1.png

          6 |  const loginButton = Selector('#content [type="submit"], .js-login-button').filterVisible();
          7 |
          8 |  await t
          9 |    .navigateTo('/login_or_join')
         10 |    .expect(loginButton.visible)
       > 11 |    .ok();
         12 |});
         13 |

         at <anonymous> (/Users/**/tests/demo/test.js:11:6)
         at <anonymous> (/Users/**/tests/demo/test.js:5:1)
         at <anonymous> (/Users/**/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at TestRun._executeTestFn (/Users/**/node_modules/testcafe/src/test-run/index.js:295:19)
         at TestRun.start (/Users/**/node_modules/testcafe/src/test-run/index.js:345:24)



 1/1 failed (18s)
```
</details>

<details>
<summary>Screenshots:</summary>

```
![1](https://user-images.githubusercontent.com/37812673/79806807-24548d80-831e-11ea-9d59-a406b7e2b39e.png)

```
</details>

### Steps to Reproduce:

1. Install v1.8.3, and run the above test
2. Upgrade to v1.8.4 and re-run test
 
### Your Environment details:
 
* testcafe version: 1.8.4                  
* node.js version: 12.14.1                   
* command-line arguments: testcafe chrome:headless 
* browser name and version: Chrome 81.0.4044.113 
* platform and version:  MacOS 10.15.4      
* other:

**Comment by SergeyShurygin** [comment]
Thank you for your report. We will look into this.
