### ISSUE TITLE
video recording is not working with testcafe-reporter-allure-expanded 

### ISSUE THREAD

**Issue by seleniumragu** [DevExpress/testcafe#5009]
I have installed testcafe-reporter-allure-expanded using the "npm install testcafe-reporter-allure-expanded" command.

And added below configuration code

const DOC_ALLURE_CONFIG = {
CLEAN_REPORT_DIR: true,
COPY_HISTORY: false,
ADD_VIDEOS: true,
CLEAN_VIDEOS: false,
REMOVE_VIDEOS: false,
CLEAN_SCREENSHOTS: false,
RESULT_DIR: '/allure/allure-results',
REPORT_DIR: '/allure/allure-report',
META: {
TEST_ID: 'ID',
TAG: 'TAG',
BLOK: 'BLOK',
MODULE: 'MODULE',
SEVERITY: 'SEVERITY',
USER_STORY: 'USER_STORY',
DESCRIPTION: 'DESCRIPTION'
},
STORY_LABEL: 'Jira Story Link',
STORY_URL: 'https://jiraexample.cloud/browse/{{ID}}',
VIDEO_PATH: 'Videos',
videoOptions: {
singleFile: true,
failedOnly: true,
pathPattern: "${DATE}_${TIME}/${TEST}/${USERAGENT}/${FILE_INDEX}.mp4"
},
REPORTS_PATH: 'Reports/',
SCREENSHOT_PATH: 'Screenshots/',
CATEGORY_FILE_PATH: 'allure/',
labels: {
screenshotLabel: 'Screenshot',
videoLabel: 'Executie Video',
reportsLabel: 'Reports',
browserLabel: 'Browser',
userAgentLabel: 'User Agent',
allureStartMessage: 'Allure reporter started...',
allureClosedMessage: 'Allure reporter closed...'
}
};

module.exports = DOC_ALLURE_CONFIG;

Allure reports are generated successfully.

But the videos folder is empty. There no videos found in the "Videos" folder.

I want to get the videos in the "Videos" folder and I want to display the videos in the "allure reports"

**Comment by miherlosev** [comment]
Hi @seleniumragu

This issue relates to the `testcafe-reporter-allure-expanded` module. I cannot find the source code repository for this module on GitHub. Try to connect with the module's author and describe the issue to him.

**Comment by AndreyBelym** [comment]
It looks like you missed the [videoPath](https://devexpress.github.io/testcafe/documentation/using-testcafe/configuration-file.html#videopath) property in your configuration.

**Comment by seleniumragu** [comment]
@AndreyBelym My code have the video path properties

![image](https://user-images.githubusercontent.com/64066809/80164638-24010e80-860c-11ea-8227-7c5ce9ea3ce2.png)

VIDEO_PATH: 'Videos',
videoOptions: {
singleFile: true,
failedOnly: true,
pathPattern: "${DATE}_${TIME}/${TEST}/${USERAGENT}/${FILE_INDEX}.mp4"
},

I already added these lines of code for capturing the videos. Still its not working.

**Comment by seleniumragu** [comment]
@miherlosev Yes cannot find the github repository.

**Comment by Farfurix** [comment]
@seleniumragu 

Hello,

> `VIDEO_PATH: 'Videos',`

It should be `videoPath: '...'`. Please refer to this documentation article: https://devexpress.github.io/testcafe/documentation/using-testcafe/configuration-file.html#videopath.

**Comment by seleniumragu** [comment]
@Farfurix VIDEO_PATH: 'Videos', this line is correct. 

I need to add the video path options in .testcaferc.json file.

 "videoPath": "Videos/",
    "videoOptions": {
        "singleFile": false,
        "failedOnly": false,
        "pathPattern": "${DATE}_${TIME}/${TEST}/${USERAGENT}/${FILE_INDEX}.mp4"

and i have to remove the video options  from the doc-allure-config.js file.

videoOptions: {
singleFile: true,
failedOnly: true,
pathPattern: "${DATE}_${TIME}/${TEST}/${USERAGENT}/${FILE_INDEX}.mp4"
},

This will solve the problem.
