### ISSUE TITLE
Set window position

### ISSUE THREAD

**Issue by vicentesaettone09** [DevExpress/testcafe#5015]
### What is your Test Scenario?
I would like to control the position of the browser window for a test to run. There are some cases where we want to be sure that the window is in the upper left corner of the screen without maximizing it, and also we want to test the app behavior under different window positions.

Additionally, we are trying to get a recording of the whole screen when a test is executed (not the browser exclusively), and for some reason, the window is moved to the lower right corner when the execution starts, leaving at least half of the browser window out of the visible screen. We do this because the Electron provided does not allow us to record a video of the execution.

### What are you suggesting?
I would like to have a function to set the window position. This function would receive two parameters or an object with the x and y coordinates, relatives to the top left corner of the screen. It can be something like `t.setPosition(150, 200)`.

### What alternatives have you considered?
We already use the existing functions to resize and maximize the browser window, but we did not find one to resize it.

**Comment by Dmitry-Ostashev** [comment]
Thank you for your suggestion. We have an existing issue describing the possibility to record a video with the testcafe-browser-provider-electron: https://github.com/DevExpress/testcafe-browser-provider-electron/issues/56. You may track it to be notified about its progress.

**Comment by vicentesaettone09** [comment]
Thank you @Dmitry-Ostashev.

Kind regards,

Vicente
