### ISSUE TITLE
Enable screenshots, resizing and videos in child windows

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#5017]
We should enable window management actions for child windows.

**Comment by jornncc** [comment]
Any update on this? Would love to be able to resize an opened window.

**Comment by itrusevich** [comment]
Yes, I'm also watching this issue and would love to hear if there are any updates.

**Comment by AlexKamaev** [comment]
@jornncc @itrusevich
Resizing and screenshots will be available in Chrome with the next TestCafe release.

**Comment by itrusevich** [comment]
@AlexKamaev great, thank you for the update!

**Comment by miherlosev** [comment]
https://github.com/DevExpress/testcafe/issues/5017

The feature is shipped with `testcafe@1.12.0`.
