### ISSUE TITLE
Electron app shutdown during test run causes TestCafe to hang

### ISSUE THREAD

**Issue by maximojoexpress** [DevExpress/testcafe#5021]
I need to shut down our Electron app from within the Electron app UI. However, TestCafe often hangs when I do this as, most likely, it wants to shutdown the app itself and perform some kind of cleanup internally.

I have tried various solutions including hacking the TestCafe source itself and doing the UI shutdown in the various after and afterEach callbacks but have found no reliable solution. Sometimes TestCafe shuts down gracefully, other times it hangs with the error:

ERROR The Electron 3.0.2 / Windows 10 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.

Originally posted here https://stackoverflow.com/questions/61449043/with-testcafe-and-electron-is-there-a-way-to-allow-the-electron-app-to-shut-its

I have replicated what (hopefully) is the same scenario with the "hash" example Electron app.

### What is your Test Scenario?
Shutting down an electron application during a test run to test our app shutdown functionality.
 
### What is the Current behavior?
TestCafe hangs and eventually displays

>ERROR The Electron 3.1.13 / Windows 10 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.

Debugging through VSCode adding Uncaught Exceptions breakpoints I see:

![image](https://user-images.githubusercontent.com/17994986/80431267-4fe60200-8934-11ea-84b2-a939ffa2f622.png)

 ![image](https://user-images.githubusercontent.com/17994986/80431283-5eccb480-8934-11ea-9564-b246716e712d.png)

### What is the Expected behavior?
TestCafe shuts down gracefully without error.
 
### What is your web application and your TestCafe test code?
See attached file.

### Steps to Reproduce:

1. Run, yarn run testcafe "electron:./" "shutdown.js"
2. When you see "waiting. Close app now!" close the hash app through the Windows "X" close button

or

1. Load app folder in VSCode
2. Check Breakpoints > Unhandled Exceptions (if desired)
3. Run
4. When you see "waiting. Close app now!" close the hash app through the Windows "X" close button

TestCafe hangs and eventually displays

>ERROR The Electron 3.1.13 / Windows 10 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.
 
### Your Environment details:
 
* testcafe version:                   latest
* node.js version:                    10.15.3
* command-line arguments:  yarn run testcafe "electron:./" "shutdown.js"
* browser name and version: Electron
* platform and version:          Windows 10

**Comment by maximojoexpress** [comment]
[shutdown-issue-example.zip](https://github.com/DevExpress/testcafe/files/4542596/shutdown-issue-example.zip)

**Comment by alexey-lin** [comment]
Hi @maximojoexpress,

Could you describe your scenario in more detail? TestCafe automatically closes the application after a test run. Why is it necessary for you to close the application during a test?

**Comment by maximojoexpress** [comment]
Our application has a somewhat complicated shutdown process and must shutdown Windows services (can take up to 10 seconds) among other things when the user exits the application. As part of the automated tests, I would like to test that this works.

Currently, after Testcafe finishes its test run I have to

1) shut down services with Powershell and
2) kill any left over running processes for our Electron app (often one of the three Electron processes hangs around after Testcafe finishes, a known issue I believe)

If Testcafe could allow me to shutdown the app through the UI, the shutdown process would be clean and I could test this functionality.

In my current test script thus DOES work sometimes i.e our app shuts down and Testcafe finishes without error, but not always resulting in a test fail when Testcafe hangs.

**Comment by AlexKamaev** [comment]
@maximojoexpress

Let me please explain why TestCafe "hangs".
TestCafe has a built-in mechanism which detects if a browser is disconnected. Every 2s browser sends XHR request to the TestCafe, which allows TestCafe to determine that the browser is working as expected. If TestCafe does not get these requests for 2 minutes, TestCafe thinks that the browser is hanging. So if the browser hangs there is no need to continue test execution. In this case TestCafe will try to restart the browser or throw the error.
Thus, the opened and working browser (or electron) is a required part of the testing process with TestCafe. TestCafe is intended to test opened sites and applications. We have some thoughts to extend this functionality and use TestCafe for unit testing [https://github.com/DevExpress/testcafe/issues/1314](https://github.com/DevExpress/testcafe/issues/1314). However, at this moment, we are not working on this task.

I think for your scenario you can use [testcafe programming interface](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/)
After the `runner.run` method is executed TestCafe will close the browser/electron automatically.
This means that you will be able to check your processes/services at this moment.


```JS
runner
    .src('tests/myFixture.js')
    .browsers(...)
    .run()
    .then(failedCount => {
// Here the browser is already closed
    })
    .catch(error => {
    });
```

**Comment by maximojoexpress** [comment]
> TestCafe will close the browser/electron automatically.
This means that you will be able to check your processes/services at this moment.

I don't think this will help. The problem is TestCafe does not seem to call window.close to shutdown the application, correct? Or am I mistaken? If it did, that would run our shutdown process.

As an aside there is currently [this issue](https://github.com/DevExpress/testcafe-browser-provider-electron/issues/49) so TestCafe often does not shutdown all processes of Electron applications.

**Comment by maximojoexpress** [comment]
Indeed, running through the API still does not work. TestCafe does not seem to call window.close which would go through our app's normal shutdown process. The three Electron processes are stopped by TestCafe but our services are still running.

This is the same result as what is produced by running through the commandline.

**Comment by maximojoexpress** [comment]
I thought about possibly using Live mode in some fashion as it won't shut down TestCafe on it's own and possibly allow me to do it. But I can't think of a viable way to know when the tests have completed via the API as you have to press CTL+C to end the session. Or am I missing a callback? Though perhaps TestCafe would hang anyway.

**Comment by AlexSkorkin** [comment]
Thank you for providing this information. We need additional time to discuss this with the team.

In the meantime, you can check how the closeBrowser function is implemented in the Electron browser provider: [https://github.com/DevExpress/testcafe-browser-provider-electron/blob/9a3da3a1d84a9ee0e0e39f53838ab3002ee5e7d5/src/index.js#L112](https://github.com/DevExpress/testcafe-browser-provider-electron/blob/9a3da3a1d84a9ee0e0e39f53838ab3002ee5e7d5/src/index.js#L112)

**Comment by maximojoexpress** [comment]
Thank you Alex, will take a look. Perhaps allow us to handle shutdown ourselves by letting us register an userShutdown callback? Or change a setting which will automatically call "win.close" to shutdown an Electron application.

FYI currently this is what we do for win.close in our pagemodel file which shuts down our services and then the Electron processes.

```
   close: ClientFunction = ClientFunction(() => {
        const win: Electron.BrowserWindow = require('electron').remote.getCurrentWindow();
        win.close();
    });

```

**Comment by Farfurix** [comment]
@maximojoexpress 

Hello,

>  Perhaps allow us to handle shutdown ourselves by letting us register an userShutdown callback? Or change a setting which will automatically call "win.close" to shutdown an Electron application.

Thank you, our team will discuss this idea.

**Comment by maximojoexpress** [comment]
Hi again, just wondering if there is any update on this one @Farfurix ? m
