### ISSUE TITLE
The "reporter" option from the configuration file will be ignored.

### ISSUE THREAD

**Issue by seleniumragu** [DevExpress/testcafe#5022]
When I execute the testcafe script with .testcaferc.json file

I got The "reporter" option from the configuration file will be ignored. error messae

My .testcaferc.json file code is below

{
    "reporter": 
    [
        { 
            "name": "json",
            "output": "Reports/report.json"
        },
        {
            "name": "xunit",
            "output": "Reports/report.xml"
        },
        {
            "name": "allure-expanded"
        }
],
    "screenshots": {
        "path": "/home/user/tests/screenshots/",
        "takeOnFails": true,
        "pathPattern": "${DATE}_${TIME}/test-${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.png"
    },
    "videoPath": "reports/screen-captures",
    "videoOptions": {
        "singleFile": false,
        "failedOnly": false,
        "pathPattern": "${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.mp4"
    }
}

**Comment by AlexKamaev** [comment]
This message appears if you define a `reporter` argument in your cli command and in the `.testcaferc.json` config. I suppose that your command looks as follows: `testcafe chrome test.js --reporter spec`. In this case the `spec` reporter will apply and the warning message about reporters in the config file will appear.
You need to remove the `--reporter` option from your cli command.
Please try this and let me know if this helps.
