### ISSUE TITLE
type="module" scripts only load in first test

### ISSUE THREAD

**Issue by LEhlerding** [DevExpress/testcafe#5026]
### Are you requesting a feature or reporting a bug?
bug

### What is your Test Scenario?
More than one test with <script type="module"> in code

### What is the Current behavior?
The first test works fine.
The second test fail with same code because the module script not loading

### What is the Expected behavior?
If i start the same test again it must be the same result

### How would you reproduce the current behavior (if this is a bug)?
Write a test where you include a script (type="module")

#### Provide the test code and the tested page URL (if applicable)
I have no url but i can write you a example

The website must only include  "<script src="test.js" type="module"></script>"

Testscript
```js

fixture(`Login`)

// Works fine
test("X1", async (t) => {
  await t.navigateTo("https://example.test")
  await t.wait(5000)
  await t.expect(Selector("#username").exists).eql(true)

  await t.navigateTo("https://example.test")
  await t.wait(5000)
  await t.expect(Selector("#username").exists).eql(true)
})

// Not loading module
test("X2", async (t) => {
  await t.navigateTo("https://example.test")
  await t.wait(5000)
  await t.expect(Selector("#username").exists).eql(true)

  await t.navigateTo("https://example.test")
  await t.wait(5000)
  await t.expect(Selector("#username").exists).eql(true)
})
```
### Your Environment details:
 
* testcafe version:                   1.8.3
* node.js version:                    12.15.0
* command-line arguments:  docker run --add-host example.com:192.168.65.2 -v 
                                               "C:\Users\XXX\...\tests":/tests testcafe chromium tests/*.ts
* browser name and version: Chrome 80.0.3987.149
* platform and version:          Docker, Linux 4.19.76-linuxkit x86_64

**Comment by AlexKamaev** [comment]
I was not able to reproduce the issue in the following example:
- index.html
```HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<span>
</span>
<script type="module" src="module2.js"></script>
</body>
</html>
```
- module1.js
```JS
export function draw (arg) {
    return 'Doe ' + arg;
}
```
- module2.js
```JS
import { draw } from './module1.js';

document.querySelector('span').innerHTML = draw('John');
```
- test code
```JS
import { Selector } from 'testcafe';

fixture `My Fixture`
    .page `about:blank`;

test('My test', async t => {
    await t.navigateTo('http://127.0.0.1:8080/');

    await t.expect(Selector('span').innerText).eql('Doe John');
});

test('My test', async t => {
    await t.navigateTo('http://127.0.0.1:8080/');

    await t.expect(Selector('span').innerText).eql('Doe John');
});

test('My test', async t => {
    await t.navigateTo('http://127.0.0.1:8080/');

    await t.expect(Selector('span').innerText).eql('Doe John');
});

test('My test', async t => {
    await t.navigateTo('http://127.0.0.1:8080/');

    await t.expect(Selector('span').innerText).eql('Doe John');
});
```
All tests are passed correctly. Could you please check my example? Please modify it so that I can reproduce the issue on my side.

**Comment by LEhlerding** [comment]
This will work but not my project.

I use nodejs Server and I start with a sandbox.
So I don’t use a html page.

I think the problem is the sandbox but I will check out what the problem is.
Im busy at this moment so please wait for my report.

Viele Grüße / Best Regards,
Lasse Ehlerding

SpecialTec - Lasse Ehlerding
E-Mail: lasse.ehlerding@specialtec.org<mailto:lasse.ehlerding@specialtec.org>
Tel :     0178 300 42 60

Von: AlexKamaev <notifications@github.com>
Gesendet: Mittwoch, 29. April 2020 13:06
An: DevExpress/testcafe <testcafe@noreply.github.com>
Cc: Lasse Ehlerding <Lasse.Ehlerding@specialtec.org>; Author <author@noreply.github.com>
Betreff: Re: [DevExpress/testcafe] type="module" scripts only load in first test (#5026)


I was not able to reproduce the issue in the following example:

  *   index.html

<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>Title</title>

</head>

<body>

<span>

</span>

<script type="module" src="module2.js"></script>

</body>

</html>

  *   module1.js

export function draw (arg) {

    return 'Doe ' + arg;

}

  *   module2.js

import { draw } from './module1.js';



document.querySelector('span').innerHTML = draw('John');

  *   test code

import { Selector } from 'testcafe';



fixture `My Fixture`

    .page `about:blank`;



test('My test', async t => {

    await t.navigateTo('http://127.0.0.1:8080/');



    await t.expect(Selector('span').innerText).eql('Doe John');

});



test('My test', async t => {

    await t.navigateTo('http://127.0.0.1:8080/');



    await t.expect(Selector('span').innerText).eql('Doe John');

});



test('My test', async t => {

    await t.navigateTo('http://127.0.0.1:8080/');



    await t.expect(Selector('span').innerText).eql('Doe John');

});



test('My test', async t => {

    await t.navigateTo('http://127.0.0.1:8080/');



    await t.expect(Selector('span').innerText).eql('Doe John');

});

All tests are passed correctly. Could you please check my example? Please modify it so that I can reproduce the issue on my side.
