### ISSUE TITLE
 NativeBinaryHasFailedError: Testcafe fails to connect to chrome when running tests from WSL2

### ISSUE THREAD

**Issue by KEC79** [DevExpress/testcafe#5027]
Testcafe versions 1.7.0 onwards cannot connect to Chrome from WSL2 and throws error:
```
NativeBinaryHasFailedError: The /node_modules/testcafe-browser-tools/bin/linux/glibc-64/find-window process failed with the 101 exit code. 
at Object.execFile (/node_modules/testcafe-browser-tools/src/utils/exec.js:120:15)
```
The tests are ran using this command: 
`testcafe chrome:/mnt/c/Program\\ Files\\ \\(x86\\)/Google/Chrome/Application/chrome.exe -c 2`

The above command runs the tests from WSL with no issue using testcafe version 1.6.1, but fails from testcafe version 1.7.0 onwards.

### What is the Current behavior?
Testcafe fails to connect to chrome. It manages to launch chrome but cannot connect so aborts with the NativeBinaryHasFailedError error shown above.
 
### What is the Expected behavior?
Chrome should launch and testcafe should be able to connect. This works as expected using testcafe version 1.6.1
 
### Steps to Reproduce:

1. Open up a terminal in WSL.
2. cd into the approproate directory where tests are ran from.
3. Run this command to start tests: `testcafe chrome:/mnt/c/Program\\ Files\\ \\(x86\\)/Google/Chrome/Application/chrome.exe -c 2`
4. Chrome is launched but testcafe fails to connect and NativeBinaryHasError is shown in console. 
 
### Your Environment details:
 
* testcafe version:                   Tried on versions of testcafe from v1.7.0 upwards
* node.js version:                    v13.13.0
* command-line arguments:  `testcafe chrome:/mnt/c/Program\\ Files\\ \\(x86\\)/Google/Chrome/Application/chrome.exe -c 2`
* browser name and version: Chrome 80 
* platform and version:          Windows, WSL2, Ubuntu 18.04

**Comment by AlexKamaev** [comment]
It looks like we alredy discussed this issue. Please try to use the workaround from the [https://github.com/DevExpress/testcafe/issues/4742](https://github.com/DevExpress/testcafe/issues/4742) thread.

If this does not help or the issue is different, please describe it in greater detail.
