### ISSUE TITLE
Testcafe internal error on the DevExtreme js demo

### ISSUE THREAD

**Issue by SergeyShurygin** [DevExpress/testcafe#5030]
Then i run this test:
```js
import { Selector } from 'testcafe';

fixture `devextreme selectbox`
    .page `https://js.devexpress.com/Demos/WidgetsGallery/Demo/SelectBox/Overview/jQuery/Light/`        

test('My second test', async t => {
    await t
        .debug()
        .click(Selector('#products-placeholder'))            
        .expect(Selector('.dx-item-content.dx-list-item-content').withText('HD Video Player').visible).ok;
})
```

i ve got a testcafe error

### What is your Test Scenario?
I want to open the products select box and click item "hd video player"
 
### What is the Current behavior?
testcafe opens page, waits for page loading and closes with success without any test actions executed

if i run test in live mode, the next error shown:
{ code: 'E24', isTestCafeError: true, callsite: CallsiteRecord { filename: 'C:\\Projects\\testcafe_issues_5000\\tests\\test4.ts', lineNum: 9, callsiteFrameIdx: 6, stackFrames: [ [CallSite], 
[CallSite], [CallSite], [CallSite], [CallSite], [CallSite], [CallSite], CallSite {}, [CallSite], CallSite {}, [CallSite], [CallSite], [CallSite], [CallSite], [CallSite], [CallSite], [CallSite] ], isV8Frames: true }, apiFnChain: [ 'Selector(\'#products-placeholder1')' ], apiFnIndex: 0 }
 
### Your Environment details:
 
* testcafe version:                 1.8.4
* node.js version:                    10.16.0
* command-line arguments:  testcafe chrome test\test4.ts
* browser name and version: chrome
* platform and version:          win 10

**Comment by miherlosev** [comment]
You found 2 problems:

* TestCafe doesn't recognize the syntax problem - `ok` is an assertion method, not a property. So you need to change the last assertion as follows:

```js
.expect(Selector('.dx-item-content.dx-list-item-content').withText('HD Video Player').visible).ok();
```

* grid is placed inside of a frame, so you need to add the `swithToIframe('#demoFrame'). We will think about how to improve the 'E24-actionElementNotFoundError` error message.
