### ISSUE TITLE
Enable debug mode in child windows

### ISSUE THREAD

**Issue by rob4629** [DevExpress/testcafe#5031]
Right now, running with `--allow-multiple-windows` only enables debug options in the main/parent window

**Comment by miherlosev** [comment]
Hi @rob4629 

Hi @rob4629

We fixed the [debug](https://devexpress.github.io/testcafe/documentation/test-api/debugging.html#client-side-debugging) action for child windows in `testcafe@1.8.5-alpha.2`.

If the problem still exists or you mean another problem, please feel free to reopen this issue and provide us with more details about it.

**Comment by rob4629** [comment]
It might be related to #5033

**Comment by AlexSkorkin** [comment]
Thank you for your clarification, Rob. We will look into that issue.
