### ISSUE TITLE
typeText works incorrectly 

### ISSUE THREAD

**Issue by orihomie** [DevExpress/testcafe#5032]
### What is your Test Scenario?
I fill some field this way:
> t.typeText(selector, value, { replace: true });

then I go further and I need to get back and change this field's value, so I do

>t.typeText(selector, anotherValue, { replace: true });
 
### What is the Current behavior?
From time to time my second input does not replace old value fully but saves first character of old value and then appends new value
 
### What is the Expected behavior?
Old value will be replaced fully
 
### What is your web application and your TestCafe test code?
It's sravni.ru/osago/wl step when you fill auto registration data then go and recieve SMS, go to summary page and then go back to edit auto registration data.
 
<summary>sravni.ru/osago/wl</summary>
 
### Your Environment details:
 
* testcafe version: 1.8.4                  
* node.js version: v12.10.0              
* command-line arguments: testcafe chrome $FilePath$ --ts-config-path testcafe.tsconfig.json  
```js
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  }
}
```
* browser name and version: Chrome  81.0.4044.129 x64 
* platform and version: macOS 10.15.4

**Comment by AlexSkorkin** [comment]
Thank you for reaching out to us and submitting this issue. My attempts to replicate it, however, were unsuccessful. Here's my sample code:

```
import { Selector } from 'testcafe';
fixture `sravni`
    .page `www.sravni.ru/osago/wl`;
test('New Test 1', async t => {
    await t
        .click(Selector('#autoNumber'))
        .typeText(Selector('#autoNumber'), 'A7777AA777')
        .click(Selector('button').withText('ПРОДОЛЖИТЬ'))
        .click(Selector('button').withText('ПРОДОЛЖИТЬ'))
        .click(Selector('#registration'))
        .typeText(Selector('#registration'), 'мос')
        .click(Selector('li').withText('г Москва').nth(0))
        .click(Selector('button').withText('ПРОДОЛЖИТЬ'))
        .typeText(Selector('#drivers\\[0\\]\\.lastName'), 'Иванов', { replace: true })
        .selectText(Selector('#drivers\\[0\\]\\.lastName'), 6, 0)
        .typeText(Selector('#drivers\\[0\\]\\.lastName'), 'Петров', { replace: true })
        .expect(Selector('#drivers\\[0\\]\\.lastName').value).eql("Петров");
});
```

Would you please update it so that we can reproduce the issue on our side? Also, it would be great if you can record a screencast of what's going on. This way, we can better understand the behavior you described. Thank you in advance.

**Comment by orihomie** [comment]
I'll leave a mini project ASAP, give me a bit of time.

**Comment by orihomie** [comment]
https://github.com/orihomie/testcafe-bug/tree/master

**Comment by Dmitry-Ostashev** [comment]
@orihomie Thank you for your project. I've reproduced the issue on my side. We'll research it and notify as soon as we have any result.
