### ISSUE TITLE
Create an API allowing to open/close browser windows

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#5034]
Example 

```js
   await t
    .openWindow(URL)
    .closeWindow(w => w.url === URL);
```

_Originally posted by @miherlosev in https://github.com/DevExpress/testcafe/issues/912#issuecomment-621803797_

**Comment by ambeecher** [comment]
I have no problem opening up a window via chrome or firefox.  I tried using t.pressKey('ctrl+w') to close a browser window and it is failing.  I also am trying to use t.pressKey('ctrl+<number 1-9>') to change my windows focus and that is failing as well.  Is there another way to send a 'ctrl+<key>' from the test code to the browser window that currently has focus?

**Comment by AlexKamaev** [comment]
@ambeecher
Switching between tabs and closing/opening tabs with keyboard shortcuts is not supported. We have plans to support the capability to open/close/switch tabs using the test API in the future.

**Comment by arubtsov** [comment]
@ambeecher

This feature is included into the current sprint (the API discussion is in progress), however we cannot give you any precise time estimates. As @AlexKamaev mentioned, keyboard shortcuts support is not in our plans at the moment.

**Comment by miherlosev** [comment]
Implemented in https://github.com/DevExpress/testcafe/pull/5210
