### ISSUE TITLE
.nth changes as you click things

### ISSUE THREAD

**Issue by benmonro** [DevExpress/testcafe#5035]
### What is your Test Scenario?
I have a bunch of buttons on a page w/ text "Add to cart."  When you click these buttons they are replaced w/ a different button showing the quantity in your cart.  I'd like to click 3 of these buttons in order w/ test code like this:

```js
const buttons = Selector("button").withText("Add to cart");

await t
  .click(buttons.nth(0))
  .click(buttons.nth(1))
  .click(buttons.nth(2))
```
### What is the Current behavior?
Currently this will click the 1st button then the 3rd and then nothing (because there are only 3 on the screen).

I did some experimenting and if I always use `.nth(0)` it will work, or if i do it in reverse order (2, 1, 0) it will work as well.
 
### What is the Expected behavior?
I would expect to be able to do it in the order the user would probably do it (from left to right - 0, 1, 2)
 
### What is your web application and your TestCafe test code?

 
```js
const buttons = Selector("button").withText("Add to cart");

await t
  .click(buttons.nth(0))
  .click(buttons.nth(1))
  .click(buttons.nth(2))
```
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:   1.8.3                
* node.js version:   12.x                 
* command-line arguments:  
* browser name and version: chrome 81 
* platform and version:   mac       
* other:

**Comment by AlexSkorkin** [comment]
Thank you for submitting this issue. TestCafe does not monitor what happens on your web page with the buttons and clicks the existing buttons in the order you specified. I recommend that you modify the button selectors so that they correspond to your current page behavior.

**Comment by benmonro** [comment]
@AlexSkorkin there should at least be a note about this in the documentation.  I think you can see how it might confuse people no?

**Comment by benmonro** [comment]
Something that says that ".nth" is calculated in real time and not ahead of time.  Something to that effect

**Comment by AlexSkorkin** [comment]
Thank you for your idea. I passed it to our technical writers.

**Comment by DIRECTcut** [comment]
Fixed in https://github.com/DevExpress/testcafe/pull/5386
