### ISSUE TITLE
drag from/to coordinates: mousedown, mousemove, mouseup

### ISSUE THREAD

**Issue by aaronshaf** [DevExpress/testcafe#5036]
I'd like to migrate the following from Puppeteer to TestCafe, but TestCafe seems to lack mousedown, mousemove, and mouseup:

```js
export async function drag([fromLeft, fromTop], [toLeft, toTop], page) {
  await page.mouse.move(fromLeft, fromTop, { steps: 10 })
  await page.mouse.down()
  await page.mouse.move(toLeft, toTop, { steps: 10 })
  await page.mouse.up()
}
```

Is there a way to do this in TestCafe?

**Comment by AlexSkorkin** [comment]
I recommend that you refer to the [Drag Element](https://devexpress.github.io/testcafe/documentation/test-api/actions/drag-element.html) topic where you can find two ways to drag an element. There's no action to drag "anything" by using only coordinates.

**Comment by aaronshaf** [comment]
Do you recommend that I open a feature request? My use case is the
selection of text and the drawing of coordinates in an annotation web app.

**Comment by AlexSkorkin** [comment]
There's no need in opening a new feature request. We are aware of your requirements and will consider implementing them.

**Comment by aaronshaf** [comment]
Is there an existing feature request I can subscribe to for updates? Thanks!

**Comment by aaronshaf** [comment]
Nevermind, I found https://github.com/DevExpress/testcafe/issues/527

**Comment by AlexSkorkin** [comment]
Thank you for the update.
