### ISSUE TITLE
Testcafe: Unable to work with multiple browser windows feature of @1.8.5-alpha.1 version

### ISSUE THREAD

**Issue by poojathakur2** [DevExpress/testcafe#5040]
In the latest version 

### What is your Test Scenario?
Scenario I am facing issue with, 2 buttons lets say A and B and 1 link lets say X
1. Click on button A which will open page in new tab
2.Click on button B which will open page in new tab
3. Click on link X which will open page in new tab
 
### What is the Current behavior?
1. Upon clicking button A, getting 'Invalid Authentication' error on the page
2. Upon clicking button B, page is continously loading
3. Upon clicking on link X, getting 'Invalid Authentication' error on the page
 
### What is the Expected behavior?
in three of the scenario new page is expected to open in new tab in browser 
 
### What is your web application and your TestCafe test code?

 Sorry can't provide the link,
My webapplication is related to Background verification domain

<details>
<summary>Your website URL (or attach your complete example):</summary>
More details please refer screenshot,
Using the debugger mode, some method which generating some token is been invoked upon clicking on the Button or the Link mentioned above, this is not working with Testcafe, 
The link where no dependency is there i n current page it works fine, for the scenario where it passes the token or some unique Id by the method invoked when we click on the respective button or link.

import { Selector, ClientFunction } from 'testcafe';

fixture `F1`
//    .page `PRIVACY issue’

test('New Test', async t => {
    await t
        .typeText(Selector('.auth0-lock-widget').find('[name="username"]'), 'testuser-3')
        .pressKey('tab')
        .typeText(Selector('.auth0-lock-widget').find('[name="password"]'), 'qauser')
        .pressKey('enter')
        .click(Selector('a').withText('Processing'))
        .click(Selector('#nextRequestButton'))
         .wait(5000)
        //.click(Selector('#resultOperatingProcedures'))
         // .wait(5000)
          .click(Selector('#otherRequestsButton'))
           .wait(5000)
    //    .click(Selector('#resultClientPreferences'))
});

<details>
<summary>Your complete test report:</summary>

```
**The specified selector does not match any element in the DOM tree.**

 **> | Selector('#lblrequestId')**

Browser: Chrome 81.0.4044.113 / Windows 10

   14 |          .wait(5000)
   15 |         .click(Selector('#resultOperatingProcedures'))
   16 |          // .wait(5000)
   17 |         //  .click(Selector('#otherRequestsButton'))
   18 |            .wait(7000)
 **> 19 |            .click(Selector('#lblrequestId'))**
   20 |            
   21 |     //    .click(Selector('#resultClientPreferences'))
   22 | });


   at )}C:\Users\verfaxbot\Documents\TestCase-Test\ClientPreferenceOperating.js:19:13
   at )}C:\Users\verfaxbot\Documents\TestCase-Test\ClientPreferenceOperating.js:6:1
   at )}C:\Users\verfaxbot\AppData\Local\Programs\TestCafe Studio\resources\app.asar.unpacked\node_modules\testcafe\src\api\wrap-test-function.js:17:28
   at TestRun._executeTestFn)}C:\Users\verfaxbot\AppData\Local\Programs\TestCafe Studio\resources\app.asar.unpacked\node_modules\testcafe\src\test-run\index.js:294:19
   at TestRun.start)}C:\Users\verfaxbot\AppData\Local\Programs\TestCafe Studio\resources\app.asar.unpacked\node_modules\testcafe\src\test-run\index.js:345:24


```
</details>

<details>

Can't provide the url due to Client's privacy policy ,
// Command line interface
Environment and command used,
I executed in Testcafe studio as well as Command line and Visual studio code as well but facing the same issue,
Used command for command line: 
testcafe chrome test.js --allow-multiple-windows

**Comment by AlexSkorkin** [comment]
Thank you for reaching out to us and submitting this issue. However, the information you provided is insufficient to determine the cause of the issue. Please create a simple sample illustrating the issue so we can examine it. Thank you in advance.

**Comment by poojathakur2** [comment]
> Thank you for reaching out to us and submitting this issue. However, the information you provided is insufficient to determine the cause of the issue. Please create a simple sample illustrating the issue so we can examine it. Thank you in advance.

Is it possible that we share the issue in Zoom meeting, due to the client policies  won't be able to share the details related to the application, if you are ok with the Zoom meeting we can go ahead and setup a meeting please do let me know.

**Comment by LavrovArtem** [comment]
We don't support such remote service. It would be better if you share a simple sample illustrating this behavior, so that we can research it.
