### ISSUE TITLE
Support non-editable element for 'selectText' action

### ISSUE THREAD

**Issue by aaronshaf** [DevExpress/testcafe#5041]
I manage a web app that supports annotations in the browser. I listen for `selectionchange` events on comments and then draw shapes. It would be useful if `t.selectText` could select text in non-editable nodes.

**Comment by Farfurix** [comment]
@aaronshaf

Hello,

Could you please share a simple project and your test scenario with us? This will help us better understand your case and check for a suitable solution.

**Comment by gruhn** [comment]
Here is one scenario where it would make sense to test for behavior in response to selection of non-editable text:

I have multiple sentences of text in a certain language (say English) which is translated to a different language (say French). When I select portions of the translated text, I want the associated source sentence to be highlighted:

![Untitled-2](https://user-images.githubusercontent.com/26570572/89891347-3744e380-dbd5-11ea-8742-33f9946e00b2.gif)

Another scenario I can think of is something like what they have at [medium.com](https://medium.com/@deathmood/how-to-write-your-own-virtual-dom-ee74acc13060). You can select any potion of an articles text and get a tooltip with sharing options:

![Untitled](https://user-images.githubusercontent.com/26570572/89891358-3a3fd400-dbd5-11ea-8709-3210e3778698.gif)

**Comment by gruhn** [comment]
And here is another one: At [genius.com](https://genius.com/20558094) logged in users can add explanations or trivia to song lyrics by creating annotations for specific words or phrases:

![Untitled](https://user-images.githubusercontent.com/26570572/89892832-9146a880-dbd7-11ea-9cda-49ed4d921ce1.gif)

**Comment by wentwrong** [comment]
Thank you for sharing your scenarios with us. They demonstrate that this feature should be useful.

Although, currently the selection can be performed only for inputs, text areas and content-editable elements, there is a workaround with [ClientFunctions](https://devexpress.github.io/testcafe/documentation/guides/basic-guides/obtain-client-side-info.html) and the [Selection API](https://developer.mozilla.org/en-US/docs/Web/API/Selection). For example, you can use the code below to implement one of the described scenarios:

```js
import { Selector, ClientFunction } from 'testcafe';

fixture `Non Editable element selection`
    .page `https://medium.com/@deathmood/how-to-write-your-own-virtual-dom-ee74acc13060`;

const selectElement = (selector) => ClientFunction(() => {
    const nonEditableElement = selector();
    const textOfElement = nonEditableElement.firstChild;
    const selection = document.getSelection();
    const range = document.createRange();

    range.setStart(textOfElement, 245);
    range.setEnd(textOfElement, 271);

    selection.addRange(range);
}, { dependencies: { selector } });

test(`Should select the 'Virtual DOM can be written' sentence`, async t => {
    await selectElement(Selector('p').withText('Virtual DOM can be written'))();

    await t.debug();
});
```
