### ISSUE TITLE
Can't clear localStorage when site hosted on testcafe server

### ISSUE THREAD

**Issue by maximkoev** [DevExpress/testcafe#5049]
### What is your Test Scenario?
    await t.eval(()=> {
      localStorage.clear()
      location.reload()
    })
or 

export const DoUserLogout = ClientFunction(() => {
  localStorage.clear()
window.location.reload()
});

 
### What is the Current behavior?
Happens only reload page action. localStorage.length returns 0

 
### What is the Expected behavior?

User logout. When I do the same thing in browser console (without testcafe) log out happens success

 
### What is your web application and your TestCafe test code?
Unfortunately no way share link due to NDA

**Comment by alexey-lin** [comment]
Hi @maximkoev,

We need to reproduce the issue to determine its cause. In other scenarios `localStorage.clear` works well. So, it is important to understand why your case is different. Since you cannot share a public URL, could you please send us a small sample project?
