### ISSUE TITLE
TestCafe fails in app with map. Cannot read property 'destUrl' of null

### ISSUE THREAD

**Issue by hvitis** [DevExpress/testcafe#5053]
### What is your Test Scenario?
Issues preventing TestCafe from executing tests and moving forward after redirection login callback (when entering main page with the map).
 
### What is the Current behavior?
After opening the main page with the app, just after redirecting from login (works fine) the console log shows error:
Cannot read property 'destUrl' of null

### Chrome

>  hammerhead.js:6 TypeError: Cannot read property 'destUrl' of null
>     at Function.t._sameOriginCheck (hammerhead.js:9)
>     at r.fetch (hammerhead.js:9)
>     at l (2.1976ca39.chunk.js:2)
>     at ye (2.1976ca39.chunk.js:2)
>     at _e (2.1976ca39.chunk.js:2)
>     at be (2.1976ca39.chunk.js:2)
>     at Object.e [as getImage] (2.1976ca39.chunk.js:2)
>     at i.loadImage (2.1976ca39.chunk.js:2)
>     at k (main.60a09fdd.chunk.js:2)
>     at main.60a09fdd.chunk.js:2

### FireFox

> TypeError: "m.parseProxyUrl(...) is null"
>     _sameOriginCheck http://172.20.193.114:52263/hammerhead.js:9
>     fetch http://172.20.193.114:52263/hammerhead.js:9
> 

### What is the Expected behavior?
Tests set should follow and be executed.
 
### What is your web application and your TestCafe test code?
Proprietary company's code.  Currently we do not have any tests related to MapBox directly. Testing only other functionalities but not the map. Can't share the details.
 
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 (fixture`Basic tests` as any).beforeEach(async (t) => {
  await t.useRole(testUser);
  t.ctx.page = new MainPage();
  await t.ctx.page.open(t);
});

test("redirects to default route", async t => {
  const page: MainPage = t.ctx.page;
  
  await t
    .expect(await page.getPageUrl())
    .contains("heatint/heatint");
});
Basic test, changing roles and other ways of navigating etc causes the same issue.
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
    "test:ch": "npm run tsc && testcafe --skip-js-errors --debug-on-fail --app-init-delay 10000 --env=dev --user=HJORING chrome --speed 1 build/index.js",


{
    "compilerOptions": {
        "outDir": "./build",
        "types": ["testcafe", "node"]
    },
    "include": ["./**/*"]
}

"dependencies": {
    "concurrently": "^5.2.0",
    "wait-on": "^4.0.2"
  },
  "devDependencies": {
    "@types/node": "^13.13.4",
    "@typescript-eslint/eslint-plugin": "^2.9.0",
    "@typescript-eslint/parser": "^2.9.0",
    "eslint": "6.7.2",
    "eslint-config-prettier": "6.7.0",
    "eslint-plugin-import": "2.18.2",
    "eslint-plugin-prettier": "3.1.1",
    "eslint-plugin-testcafe": "^0.2.1",
    "jest": "^25.5.2",
    "jest-image-snapshot": "^3.1.0",
    "jest-puppeteer": "^4.4.0",
    "minimist": "^1.2.5",
    "prettier": "1.19.1",
    "puppeteer": "^3.0.2",
    "start-server-and-test": "^1.11.0",
    "testcafe": "^1.8.4",
    "typescript": "3.7.4"
  }
```
</details>

<details>
<summary>Your complete test report:</summary>

```
![image](https://user-images.githubusercontent.com/17104239/81192107-1d827780-8fba-11ea-846c-727021669eb2.png)

```
</details>

<details>

### Steps to Reproduce:

I can't provide users nor URL. I could try searching for other MapBox implementations and using their URL as reference.
 
### Your Environment details:
 
* testcafe version:                   1.8.4
* node.js version:                    6.14.4
* command-line arguments:  testcafe chrome tests
* browser name and version:  chrome, firefox
* platform and version:          win10
</details>

#### Related issue: 
#2044

**Comment by AlexKamaev** [comment]
This information is insufficient to determine the cause of the issue. We would really appreciate it if you find a project that demonstrates the issue or extract only the problematic part of your project and share it with us for further research.

**Comment by hvitis** [comment]
I am sorry it's impossible to share the access to our app but I've found other MapBox map that causes issues with my TC setup (works when entering manually).

https://flight-spotter.janhartmann.dk/

Unfortunately the error is not the same. 

More logs from the error I have show Mapbox-gl library
![image](https://user-images.githubusercontent.com/17104239/81554722-96e9e380-9387-11ea-8271-eb5d99436fc4.png)
![image](https://user-images.githubusercontent.com/17104239/81554990-ff38c500-9387-11ea-9f24-ffed6ca9cc7c.png)


You think it might be useful to contact MapBox team?

**Comment by AlexSkorkin** [comment]
> You think it might be useful to contact MapBox team?

Probably.

In the meantime, if you could create a simple sample that we can run on our side, that will help us diagnose the issue.

**Comment by hvitis** [comment]
Ok, I will try. Thank you!
