### ISSUE TITLE
Unable to open browser with secured connection in Testcafe

### ISSUE THREAD

**Issue by viswack** [DevExpress/testcafe#5055]
Hi all,

I am trying to open a url on chrome browser. When i open it manually it is opening with secured connection. But while running the testcafe script, browser opens as "not secure" connection.
Same code is working fine with IE. Issue is only with Chrome.

Actually page is not loading. I am getting 503 exception in the browser console. I am guessing it is due to this "not secure" connection browser is not loading. 

I see the following error code in testcafe terminal:
npm ERR! code ELIFECYCLE
npm ERR! errno 1

Is there a way we can open the browser with secured connection in Chrome?  Any help is greatly appreciated.
![Capture1](https://user-images.githubusercontent.com/64960921/81525422-4025df00-9372-11ea-8a27-f86e9ae71ae6.JPG)

Thank you.

**Comment by miherlosev** [comment]
Hi @viswack 

> But while running the testcafe script, browser opens as "not secure" connection.

It's expected. Internally, TestCafe communicates with your web site with secured connection (see the [How TestCafe works](https://devexpress.github.io/testcafe/documentation/how-it-works/#page-proxying) article). 

If your site works incorrectly, please give us a public link to it.
