### ISSUE TITLE
Need alpine be updated to next version

### ISSUE THREAD

**Issue by NazarKur** [DevExpress/testcafe#5057]
### What is your Test Scenario?

 I want to update my chromium to the latest version of chromium (81), but could not do that as testcafe is using --repository http://dl-cdn.alpinelinux.org/alpine/v3.10/main/ in docker file when the 81 version starts supporting form alpine/v3.11.
### What is the Current behavior?

Could not update to 81 version of chromium as testcafe repo uses not the latest version of alpine in docker file.
 
### What is the Expected behavior?

Wherever docker file in testcafe repo will be updated it will give me the possibility to update my chromium
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version: 1.8.1                  
* node.js version:  v12.16.3                  
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by SergeyShurygin** [comment]
Thank you for pointing this out. We will update the Alpine version in the upcoming testcafe release.
