### ISSUE TITLE
Website - we need an Example page

### ISSUE THREAD

**Issue by VasilyStrelyaev** [DevExpress/testcafe#506]

**Comment by VasilyStrelyaev** [comment]
I feel like we will need some help with the Example page. Ideas and technical matters.
\cc @DevExpress/testcafe

**Comment by VasilyStrelyaev** [comment]
First, I assume that we can technically borrow the existing Example page. Despite it's MVC while our GitHub pages website is static. Cause this page does not make much use of MVC currently.

**Comment by VasilyStrelyaev** [comment]
But we may probably want something more. For instance, something that includes `contentEditable` elements.

**Comment by inikulin** [comment]
>  For instance, something that includes contentEditable elements.

I guess we can not care much about page looking as a real page. Moreover we can have multiple example pages. E.g. copy existing one for getting started (I don't think we need any server-side functionality for it). When we can create some additional example pages for specific actions, e.g. to illustrate contentEditable typing we can just create single page with some popular online editor embedded on it and so on.

**Comment by VasilyStrelyaev** [comment]
OK, sounds good.

> E.g. copy existing one for getting started 

BTW, is there a fast way to copy a page?

**Comment by inikulin** [comment]
> BTW, is there a fast way to copy a page?

Yes:
- Open HTML markup in editor of your choice. 
- Set focus to the editor window
-Use the following key combination: <kbd>CTRL</kbd>+<kbd>A</kbd>, <kbd>CTRL</kbd>+<kbd>A</kbd>
- Create destination file in your editor
- Focus to it's window
- Press <kbd>CTRL</kbd>+<kbd>V</kbd>
- Decorate it with your CSS
...
- PROFIT!

**Comment by VasilyStrelyaev** [comment]
Had to make it from the ground up and... managed to create such a thing so far:
[http://strelyaev-w8:8080/testcafe/example/](http://strelyaev-w8:8080/testcafe/example/)

Is it okay and I'm calling the designer - or did I do it wrong?

**Comment by inikulin** [comment]
> Is it okay and I'm calling the designer

What do you mean by that?

**Comment by VasilyStrelyaev** [comment]
If it's ok, I'll ask the designer to improve the visual part (mostly, the layout) and then open a PR.

**Comment by inikulin** [comment]
Unfortunately, I can't access your URL from home

**Comment by VasilyStrelyaev** [comment]
Even using VPN?

**Comment by miherlosev** [comment]
Try http://strelyaev-w8.corp.devexpress.com:8080/testcafe/example

**Comment by VasilyStrelyaev** [comment]
okay then, we'll get back to it later...
does anyone else have something to say?

**Comment by inikulin** [comment]
> Try http://strelyaev-w8.corp.devexpress.com:8080/testcafe/example

I don't have VPN here

**Comment by miherlosev** [comment]
http://strelyaev-w8.corp.devexpress.com:8080/testcafe/example is public url.
It will work without VPN
