### ISSUE TITLE
Video recording not working in chrome docker

### ISSUE THREAD

**Issue by saurabh2k26** [DevExpress/testcafe#5062]
Suppose i am on mac and want to test my testcafe scripts on linux chrome.
Approach i have followed is to use chrome docker image along with package - testcafe-browser-provider-selenium
It all works fine, but now i need to record video and i am getting error:
`Video recording is not supported by the "selenium:chrome" browser.`

### What is your Test Scenario?
Run testcafe on chrome docker image and record video successfully.
 
### What is the Current behavior?
getting error:
`Video recording is not supported by the "selenium:chrome" browser.`
 
### What is the Expected behavior?
Video should be recorded
 
### What is your web application and your TestCafe test code?
Precondition: this package should be installed:
`npm install testcafe-browser-provider-selenium`

Test code (my_first_test.js)
```
fixture `Getting Started`
    .page `http://google.com`;

    test('Sample test', async t => {
        await t
        console.log("webpage opened")
    })
```
DockerFile:
```
FROM node:latest AS node_base

RUN npm install --save @ffmpeg-installer/ffmpeg

FROM selenium/standalone-chrome

USER root

COPY --from=node_base . .

RUN echo "file ends..."
```

Setup container(dockerfile in same folder)
```
docker build -t mychrome:1.6 .
docker run -d -p 4444:4444 -v /dev/shm:/dev/shm mychrome:1.6
```
run testcafe:
`testcafe selenium:chrome my_first_test.js `

Everything works well till now, so lets try to record video:
`testcafe selenium:chrome my_first_test.js --video myvideo`

This is the result:
```
Using locally installed version of TestCafe.
 Running tests in:
 - Chrome 81.0.4044.92 / Linux 0.0

 Getting Started
webpage opened
 ✓ Sample test


 1 passed (2s)

 Warnings (1):
 --
  Video recording is not supported by the "selenium:chrome" browser.
```
 I want to have video support. I don't want to use testcafe docker image since we still want to use local testcafe and only dockerized browser.

**Comment by AlexSkorkin** [comment]
Thank you for submitting this issue. Currently, video recording is supported in Google Chrome, Mozilla Firefox, and Microsoft Edge (Chromium-based). Remove browsers are not supported.

The selenium browser provider plug-in you mentioned should have this support implemented via the getVideoFrameData method. Our team does not develop or maintain this plug-in. I recommend that you port your issue in the corresponding repository: [https://github.com/alexschwantes/testcafe-browser-provider-selenium/issues](https://github.com/alexschwantes/testcafe-browser-provider-selenium/issues).

**Comment by oemekaogala** [comment]
@AlexSkorkin Where can I find documentation on implementing getVideoFrameData()? I don't see this anywhere in the [docs](https://devexpress.github.io/testcafe/documentation/guides/extend-testcafe/browser-provider-plugin.html).

**Comment by Dmitry-Ostashev** [comment]
@oemekaogala Currently, this method is not described in the documentation. I've created a separate issue for this case.

Here is the `getVideoFrameData` method implementation for Chrome: https://github.com/DevExpress/testcafe/blob/master/src/browser/provider/built-in/dedicated/chrome/index.js#L85

**Comment by oemekaogala** [comment]
Thanks @Dmitry-Ostashev
