### ISSUE TITLE
Cookies set via TC are getting lost when browser moves to a different page type (i.e. react pages to websphere jsp pages)

### ISSUE THREAD

**Issue by bennymeade** [DevExpress/testcafe#5065]
### What is your Test Scenario?
To set cookies in browser and have them available throughout the test run.
 
### What is the Current behavior?
Web application uses a combination of react pages and websphere jsp pages, cookies set on one page type are being lost when test moves to the other page type. Follow steps:

* set cookies on the react pages 
* document.cookie shows that new cookie is present
* move to websphere jsp page
* document.cookie shows that new cookie is now not present
* same happens if test done vice versa (websphere jsp page -> react page)
 
### What is the Expected behavior?
Set cookies should be retained by TestCafe for full duration of test run on all page types.
 
### What is your web application and your TestCafe test code?

```
import { ClientFunction } from 'testcafe';

export const setCookie = ClientFunction((name, val) => {
    document.cookie = [name, val].join('=')
});

fixture `Place Order`
    .page`https://www.sainsburys.co.uk/shop/LogonView/Identifier` // react page

test.only
('Example of browser losing previosly set cookies', async t => {
    await setCookie('NewCookieSetViaTc', 'xyz')
    await t.eval(() => location.reload(true));
    await t.debug() // check console for "document.cookie" => cookie is present: NewCookieSetViaTc=xyz;
    await t.navigateTo('https://www.sainsburys.co.uk/shop/gb/groceries') // websphere jsp page
    await t.debug() // check console for "document.cookie" => cookie is Not present
});
```

### Steps to Reproduce:
Run test code example and manually check the cookies at the t.debug() steps.
 
### Your Environment details:
 
* testcafe version:                   v1.8.4
* node.js version:                    v12.13.0
* browser name and version: Chrome v81
* platform and version:          Mac OS

**Comment by LavrovArtem** [comment]
You will see the same behavior if you do the same actions without TestCafe.
You need to use the `path` directive for your cookies. For example, set it to the root of the site: `/`.
The default `path` directive value on `https://www.sainsburys.co.uk/shop/LogonView/Identifier` is `/shop/LogonView`.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Scope_of_cookies

**Comment by bennymeade** [comment]
This does indeed work, thank you.

`const setCookie = ClientFunction(() => {
    document.cookie = "mycookiename=xyz; path=/;"
  });`
