### ISSUE TITLE
typescript error on clientScripts

### ISSUE THREAD

**Issue by benmonro** [DevExpress/testcafe#5071]
### What is your Test Scenario?
The testcafe docs show that you can use a clientScripts module on a fixture or test: 

```ts
fixture`foo`
	.clientScripts({module:"foo"})
```
 

### What is the Current behavior?

 In typescript I get the following error: 

![image](https://user-images.githubusercontent.com/399236/81867810-275e2a80-9526-11ea-880b-f82213c8d996.png)
### What is the Expected behavior?

 no errors, as it's using the documented api.
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by Dmitry-Ostashev** [comment]
Thank you for your report. I've reproduced this issue. We'll work on it and notify you once we have any news. Your PR would be also appreciated.
