### ISSUE TITLE
302 Redirection causing - Cannot read property 'destUrl' of null

### ISSUE THREAD

**Issue by dineshk-qa** [DevExpress/testcafe#5073]
### What is your Test Scenario?

 clicking on logout button results in 302 redirection and ultimately user is redirected back to login page.
### What is the Current behavior?
TypeError: Cannot read property 'destUrl' of null
 ```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent
      to the client
      at ServerResponse.setHeader (_http_outgoing.js:526:11)
      at ServerResponse.writeHead (_http_server.js:273:21)
      at RequestPipelineContext.sendResponseHeaders
```
Also The test cafe browser url is shown as at failure:
`http://localhost:1337/03WvIUCEQ/about:error`

This is happening while clicking on a logout button.
There is 302 redirection happening and ultimately user is redirected back to login page.

### What is the Expected behavior?

 I should be able to assert that user is navigated back to login page after logged out

### What is your web application and your TestCafe test code?

<summary>Your complete test code (or attach your test files):</summary>

 
```js
 await t.click(Selector('.left .button--secondary'));
```
### Your Environment details:
testcafe - 1.8.4
OS - Mac Catalina
browser - chrome 81 
Node - 12.16.3

**Comment by dineshk-qa** [comment]
This is the network tab after clicking Logout:
![Screen Shot 2020-05-15 at 12 33 20 pm](https://user-images.githubusercontent.com/14121860/82005313-6320fd80-96a8-11ea-930d-a69752b4e223.png)

**Comment by dineshk-qa** [comment]
This is Network tab after clicking Logout

![Screen Shot 2020-05-15 at 12 33 20 pm](https://user-images.githubusercontent.com/14121860/82005613-24d80e00-96a9-11ea-87cc-f86badd28107.png)

**Comment by AlexKamaev** [comment]
This information is insufficient to reproduce the issue. We would appreciate it if you share your project with us to demonstrate the issue. If you are unable to share your project here please send us a sample with the problematic part so we can research it in detail.
