### ISSUE TITLE
Unit test React components with TestCafe

### ISSUE THREAD

**Issue by AlexKamaev** [DevExpress/testcafe#5076]
There is a library by **[@benmonro](https://github.com/benmonro),** which allows you to write unit tests for React Components with TestCafe.

https://github.com/testcafe-community/testcafe-react-testing

We can consider implementing this behavior in TestCafe in the future.

> I could use this feature as well.  Cypress has [this library](
> https://github.com/bahmutov/cypress-react-unit-test) and I was trying to write the same thing for testcafe but ran into the same problem with JSX.
> 
> 
> I actually have my library working (link below) but it requires you to use `React.createElement`. If you guys can add support for jsx and/or tsx, then I can help you keep Cypress where they belong: in the gutter. :)
> 
> https://github.com/benmonro/testcafe-react-testing/blob/master/test/index.test.ts#L11

_Originally posted by @benmonro in https://github.com/DevExpress/testcafe/issues/4817#issuecomment-628394906_

https://github.com/DevExpress/testcafe/issues/4817#issuecomment-628776784

**Comment by benmonro** [comment]
@AlexKamaev Thanks for posting this here, really excited for you to add this feature to testcafe!  I'm going to be checking this issue every day! haha

**Comment by benmonro** [comment]
@AlexKamaev I Have a PR that I will open shortly that adds support for JSX in js files

**Comment by miherlosev** [comment]
Hi @benmonro 

Thank you for your contribution in TestCafe. We will review your PR.

**Comment by prudhvidandamudi** [comment]
@miherlosev 
Are there any docs or is it possible to do component level testing on an angular application using testcafe?

**Comment by arubtsov** [comment]
@prudhvidandamudi, currently, it's impossible to unit-test any components with TestCafe out of the box. So, there is no documentation related to this.
