### ISSUE TITLE
Concurrency parameter works incorrectly

### ISSUE THREAD

**Issue by orihomie** [DevExpress/testcafe#5085]
I've noticed that when I set concurrency parameter to a value of 
> $(nproc --all

Is 12 for my pc and amount of tests I have is 6, launching them by mask, so I've expected testcafe would launch only 6 browsers, but was 12.

Launch command was
> npx testcafe "firefox" tests/e2e/ --test-grep "^[^w]" --ts-config-path testcafe.tsconfig.json --speed 1.0 --concurrency 12 -r teamcity --video /tmp/ --video-options 'singleFile=false,failedOnly=true,pathPattern=${TEST}_${USERAGENT}.mp4'

```
node v14.2.0
npm v6.14.4
npx v6.14.4
testcafe v1.8.4
macOs v10.15.4
```

**Comment by miherlosev** [comment]
Hi @orihomie 

This's expected. If you specify `--concurrency 12`, TestCafe will opens 12 browser instances ignoring the number of tests. If there are fewer tests than browser instances, extra browser instances will not execute tests.
