### ISSUE TITLE
Enable quarantine for all cloud browsers

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#5092]
#### Provide the test code and the tested page URL (if applicable)

 
Your website URL (or attach your complete example):

Your complete test code (or attach your test files)

```js

```
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by miherlosev** [comment]
Implemented in https://github.com/DevExpress/testcafe/commit/458f78dc44308f37c496305ac9d50cd9c512aaa2
