### ISSUE TITLE
npm install testcafe@latest not pulling latest TC version

### ISSUE THREAD

**Issue by bennymeade** [DevExpress/testcafe#5095]
Running: npm install testcafe@latest 
Gives: "testcafe": "^1.8.4",

Even though the latest version available is: v1.8.5-alpha.3

**Comment by AlexanderMoiseev** [comment]
Hello, 

This behavior is correct. Using ‘npm install <pkg>@latest’ is equivalent to using ‘npm install <pkg>’ since ‘npm install <pkg>’ will use the latest tag by default and install the latest stable release.

**Comment by AndreyBelym** [comment]
You can use `npm install testcafe@alpha` to install the latest alpha version.
