### ISSUE TITLE
Control Browser Clock

### ISSUE THREAD

**Issue by djornada** [DevExpress/testcafe#5098]
### What is your Test Scenario?

1. The user access the app URL
2. The user stays at the app by *x* minutes
3. The app warns the user with _your session will expire in *y* minutes_
4. The user stays at the app by *x* minutes
5. The app warns the user the session expired

### What are you suggesting?

A way to control the browser clock as we do in with jest _advanceInTime_ something like:
`advanceInTime(timeInMs)` as parameter we provide how many miliseconds we wand to advance in time and the magic happens

### What alternatives have you considered?

Didn't find, I would love to hear alternatives =)

### Additional context
[stackoverflow discussion](https://stackoverflow.com/questions/61821094/control-browser-clock/61865081#61865081)

**Comment by LavrovArtem** [comment]
Thank you for the idea. It is an interesting suggestion. Currently, as a workaround, you can try overriding the `Date` constructor using a client function. For example:

```js
const overrideDate = ClientFunction(() => {
    window.Date = function() {
         // something
         return new Date(calculatedDate);
    };
});
```

**Comment by djornada** [comment]
Thanks for the suggestion @LavrovArtem but it seems not to work on my case now. Cause the warns are scheduled using setTimeout, which I believe not look for the Date object but the sys clock
