### ISSUE TITLE
Seeing BrowserSet._checkForDisconnections errors for versions 1.7.x and higher of TestCafe

### ISSUE THREAD

**Issue by pterofractal** [DevExpress/testcafe#5101]
### What is your Test Scenario?
I am trying to execute tests remotely from my mobile phone
 
### What is the Current behavior?
If I execute `testcafe remote` or use the `createTestCafe` API to create a remote connection my phone will connect to TestCafe, filter out the tests not to run, then fail with the error `checkForDisconnections`

The suite of tests run fine with version 1.6.1 but anything higher and TestCafe throws the above error. My company has some fairly complicated firewalls and securities in place but my phone is able to access the internal network. Also, the tests all pass fine with version `1.6.1`. Glancing at the changelog I can see that in `1.7` there were some browser related changes though I didn't dig through the diffs to see what could be the issue.
 
### What is the Expected behavior?
My phone connects to my TestCafe instance and executes all tests
 
### What is your web application and your TestCafe test code?
I can't provide accurate repro steps because I am running these tests on my company issued laptop and my network set up may also be interfering with things. Below is a test and `package.json` file which fail to execute a remote test using the iOS Simulator on my mac.

<details>
<summary>package.json</summary>

```json
{
  "name": "MyAwesomeTestPackage",
  "version": "1.0.0",
  "dependencies": {
    "typescript": "~3.0.0"
  },
  "devDependencies": {
    "testcafe": "~1.7.0"
  },
  "scripts": {
    "testcafe": "testcafe"
  }
}
```
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from 'testcafe';

fixture `Google`.page `https://google.com`;
test('Validate can search for ', async (t) => {
  await t
    .typeText('input[type="text"]', 'The Beatles')
    .pressKey('enter')
    .expect(Selector('#result-stats').exists).ok();
});
```
</details>

<details>
<summary>Your complete test report:</summary>

```
> testcafe "remote" "src/open-book/test.ts"

Connecting 1 remote browser(s)...
Navigate to the following URL from each remote browser.
Connect URL: http://192.168.1.100:34285/browser/connect
CONNECTED Chrome 81.0.4044.113 / macOS 10.14.6
ERROR The following browsers disconnected: Chrome 81.0.4044.113 / macOS 10.14.6. Tests will not be run.

Type "testcafe -h" for help.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! MyAwesomeTestPackage@1.0.0 testcafe: `testcafe "remote" "src/open-book/test.ts"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the MyAwesomeTestPackage@1.0.0 testcafe script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ksivaran/.npm/_logs/2020-05-20T04_11_21_278Z-debug.log

```
</details>

<details>

### Steps to Reproduce:

1. Run `testcafe remote path/to/test.ts`
2. Open the resulting link on a mobile device of iOS Simulator
3. Notice the test fails with a browse disconnects error
 
### Your Environment details:
 
* testcafe version: 
* node.js version:  `12.16.3`
* command-line arguments:  `testcafe "remote" "src/open-book/test.ts"`
* browser name and version: `Safari 13.0.4 ` and Chrome
* platform and version:          macOS 10.15
* other:                                   My company probably has some firewall and security measures installed on my machine but I don't know what they are or how they could be impacting the tests

**Comment by LavrovArtem** [comment]
Could you please try the latest 1.8.5 version of TestCafe?

**Comment by pterofractal** [comment]
Shoot. Sorry. `1.8.4` looks to work. I think I had tried `1.7.0 - 1.8.3` and those all failed. Sorry about opening this.

**Comment by pterofractal** [comment]
Sorry. I spoke too soon. 

I tried `1.8.5` and `1.8.6-alpha-1` and the issue still exists. The issue is more complicated than I originally thought though. 

* If I run the tests from my laptop and open a simulator on the same machine the test connects and everything is fine. 
* If I run the tests from a _remote EC2 instance_ and then try to connect to the test from my laptop I get a browser disconnected error.

The failing scenario works fine though with version `1.6.1.`. 

Is it possible to share some details as to how TestCafe is validating the browser is disconnecting? 

I am not sure what other information I can share to help you debug this. This is most likely due to our companies internal networking set up so maybe this isn't something that can be easily fixed on your end.

Thanks,
Krishna

**Comment by AndreyBelym** [comment]
The situation in your second setup (headless Amazon EC2 Linux container and a remote browser) looks very similar to the conditions described in #4742. As a workaround, you can try to install and run Xvfb before TestCafe in your EC2 container. 

I close this issue as a duplicate for maintenance purposes. Please use #4742 to track our progress in this issue.
