### ISSUE TITLE
Usage of the environment variable is not available in `.testcaferc.json file`

### ISSUE THREAD

**Issue by CyHuH** [DevExpress/testcafe#5105]
### What is your Test Scenario?

 I want to filter my tests by meta like that 
```
"filter": {
    "testMeta": {
      "category": "${CATEGORY}"
    }
  }
```
then I do `export CATEGORY=regression` and try to run tests like that `npx testcafe`.
Also, I tried to run it like that `CATEGORY=regression npx testcafe`
### What is the Current behavior?

 ```ERROR No tests to run. Either the test files contain no tests or the filter function is too restrictive.```
### What is the Expected behavior?

 tests are started
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by SergeyShurygin** [comment]
Hello Andrey,

Thank you for your report. The .testcaferc.json file does not support environmental variables, and it's not supposed to be used in a such way.

I discussed you scenario with the team. We believe that a more flexible approach is to perform such customizations using the JS configuration files. We've created the following issue: ["Support JS TestCafe configuration files"](https://github.com/DevExpress/testcafe/issues/5109). Please track it to get updates.

We will appreciate it if you submit your PR with the implementation of this functionality.
