### ISSUE TITLE
Add type definitions for RequestMock respond/onRequestTo/RequestOptions

### ISSUE THREAD

**Issue by cdrini** [DevExpress/testcafe#5108]
This is more a refactor than a bug, but it felt more like a bug than a feature :P Hope that's ok.

### What is your Test Scenario?
Trying to get autocompletion/type-safety for the `.respond((req, res) => {})` and `.onRequestTo((req) => boolean)` methods of `RequestMock`.
 
### What is the Current behavior?
Currently these function's arguments have types `any`:
https://github.com/DevExpress/testcafe/blob/e5d2081bd7f40ca99769402271fc65293260ea12/ts-defs-src/test-api/request-hook.d.ts#L149-L162
 
### What is the Expected behavior?
They should have types `RequestOptions`, as defined here: https://devexpress.github.io/testcafe/documentation/reference/test-api/requestmock/respond.html#requestoptions , and some other type for `Response`.
 
### What is your web application and your TestCafe test code?
Not really applicable, but https://github.com/internetarchive/bookreader
 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

https://github.com/internetarchive/bookreader/pull/314/files#diff-53a5fe68f6659bdf074d53e1ac18547b

Here's a minimal snippet:

```js
import { RequestMock } from 'testcafe';

RequestMock()
.onRequestTo(req => req.url) // No autocomplete after `req.`
.response((req, res) => res.setBody('foo')); // No autocomplete for `res.`
```

</details>

<details>
<summary>Your complete configuration file (if any):</summary>

NA

</details>

<details>
<summary>Your complete test report:</summary>

NA

</details>

<details>
<summary>Screenshots:</summary>

NA

</details>

### Steps to Reproduce:

1. Paste the minimal code snippet in vscode
2. Try to get autocomplete
 
### Your Environment details:
 
* testcafe version:                   1.8.1
* node.js version:                    12.4.0
* command-line arguments:  NA
* browser name and version: NA
* platform and version:          Win10
* other:                                   None

**Comment by SergeyShurygin** [comment]
Thank you for pointing this out. We will keep it in mind.
We will also appreciate if you submit your PR with implementation of this functionality.

**Comment by cdrini** [comment]
Awesome, thank you!

**Comment by cdrini** [comment]
Is there any automation in play here, or can I edit testcafe/ts-defs-src/test-api/request-hook.d.ts directly?

**Comment by SergeyShurygin** [comment]
Yes, you can directly edit the .d.ts files.
