### ISSUE TITLE
Tests from different fixtures cannot be run in parallel

### ISSUE THREAD

**Issue by vishpat2020** [DevExpress/testcafe#5112]
### What is your Test Scenario?

 Run tests from different fixtures concurrently

### What is the Current behavior?

 Only tests from individual fixtures are run concurrently. However, tests from different fixtures are run sequentially. 

### What is the Expected behavior?

Tests from different fixtures should be run concurrently. 

In the below example, the two tests should be run in two browsers. They are actually run in single browser sequentially. 

### What is your web application and your TestCafe test code?
file: test.js >> 

fixture `1`

test(`1`, t => t.wait(5000))

fixture `2`

test(`1`, t => t.wait(5000))

### Steps to Reproduce:
testcafe -c 2 test.js 

### Your Environment details:
 
* testcafe version:                   1.8.3
* node.js version:                   v12.16.1
* command-line arguments:  testcafe -c 2 test.js 
* browser name and version: Chrome 81.0.4044.138 / Windows 10
* platform and version:          Windows 10
* other:                                  NA

**Comment by arubtsov** [comment]
Thank you for submitting this issue.
We are aware of it and it was fixed in the 1.8.4 release, so please update your testcafe version.
