### ISSUE TITLE
ctrl modifier does not work on a select with multiple options

### ISSUE THREAD

**Issue by marcdubs-gsg** [DevExpress/testcafe#5113]
### What is your Test Scenario?
Example html:
```html
<html>
<body>
<select id="my-test-select" multiple="1">
  <option value=1">My Test Option 1</option>
  <option value=2">My Test Option 2</option>
  <option value=3">My Test Option 3</option>
  <option value=4">My Test Option 4</option>
  <option value=5">My Test Option 5</option>
</select>
</body>
</html>
```

Example testcafe script:
```es6
import { Selector } from "testcafe";
fixture`Getting Started`.page`http://xxx/`;
test("My first test", async t => {
    const select = Selector("select#my-test-select");
    await t.click(select.find("option").withExactText("My Test Option 1"), {
        modifiers: { ctrl: true }
    });
    await t.click(select.find("option").withExactText("My Test Option 2"), {
        modifiers: { ctrl: true }
    });
});
```
 
### What is the Current behavior?
Both options are not selected. Instead, each option is selected individually.
 
### What is the Expected behavior?
Both options should be selected. Like what would happen if you held down ctrl and clicked on both of the options by hand.
 
### What is your web application and your TestCafe test code?
(See code above for an example page and a test)

### Steps to Reproduce:
Run the test code on the example html.
 
### Your Environment details:
 
* testcafe version: 1.6.0 (remote mode doesn't seem to work on later versions)
* node.js version: v10.19.0
* command-line arguments: --ports 10972,11972 --speed 0.5 remote --live
* browser name and version: Chrome 81.0.4044.
* platform and version: Mac OS X 10.15

**Comment by arubtsov** [comment]
Hello @marcdubs-gsg,

Thank you for reporting this issue. I was able to reproduce it. Our team will research it and check for a suitable solution.

In the meantime, you can use `ClientFunction` to mimic the desired behavior as a workaround:
```javascript
test("My first test", async t => {
    const select = Selector("select#my-test-select");
    const option1 = select.find("option").withExactText("My Test Option 1");
    const option2 = select.find("option").withExactText("My Test Option 2");

    const setSelected = ClientFunction(option => {
        option().selected = true;
    });

    await setSelected(option1);
    await setSelected(option2);

    await t.debug();
});
```

**Comment by marcdubs-gsg** [comment]
@arubtsov Thanks for the workaround!

**Comment by puneetpunj** [comment]
This workaround did not work for us. We are automating Salesforce. It selects two options but on clicking Next Salesforce asks to select the option.

**Comment by Farfurix** [comment]
@puneetpunj 

Hello,

It looks like your case is different from the original one. Please create [a new bug report](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=&template=bug-report.md) with an example where the issue is reproducible.

**Comment by viktorss89** [comment]
Hello,

I ran into the same issue

```
async setMultipleSearchComponentType(...filters) {
    for (const filter of filters) {
      await t.debug();
      await t.click(Selector('select[name="types"]').find('option').withExactText(filter), {modifiers: {ctrl: true}});
    }
  }
```
I tried the snippet at https://github.com/DevExpress/testcafe/issues/5113#issuecomment-633431468 but even though it selects both options then when I submit the form the options selected are not sent.

Just wanted to know if there's a timeline when this bug is expected to be fixed.

Thanks,

**Comment by Aleksey28** [comment]
Hi @viktorss89,

In your function, I don't see where you use `ClientFunction`. That's the main idea of the workaround. Please try using it. If it doesn't help, feel free to drop me a line and share a simple sample that helps us reproduce the issue.

As for the main issue, currently I cannot give you a precise date. Any personal estimate may be misleading.
