### ISSUE TITLE
Not able to automate Fillable PDF document.

### ISSUE THREAD

**Issue by dipeshDM1** [DevExpress/testcafe#5114]
Testcafe version : 1.8.4

### What is your Test Scenario?

Performing various operations Fillable pdf component such as passing data into textboxes, clicking checkboxes and radio buttons.
### What is the Current behavior?

 Blank Fillable PDF document is getting opened without any elements.

### What is the Expected behavior?

 User should be able to see fillable pdf elements and to perform various operations on it.

### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.8.4
* node.js version:                     v10.16.0
* command-line arguments:  
* browser name and version:  chrome 81.0.4044.138 (Official Build) (64-bit)
* platform and version:           
* other:                                   
[Screen-Prints for the issue.docx](https://github.com/DevExpress/testcafe/files/4663350/Screen-Prints.for.the.issue.docx)

**Comment by dipeshDM1** [comment]
Attached the screen-prints

**Comment by Farfurix** [comment]
@dipeshDM1 

Hello,

At present, TestCafe doesn't support the automation of non-html pages (for example, PDF).

Note: in your test scenario, you can [check](https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/intercept-http-requests.html#log-http-requests) if the PDF file was requested. You can also [use the `fs` module to verify your PDF file](https://github.com/DevExpress/testcafe-examples/blob/d36b647b3f4c167a6a01ed970057a12184d038ae/examples/wait-for-file-download/test.js).
