### ISSUE TITLE
Video not recording using ffmpeg

### ISSUE THREAD

**Issue by AutomationTester143** [DevExpress/testcafe#5117]
### What is your Test Scenario?
I am just checking how video works in testcafe. 

I am using testcafe version 1.8.5 and ffmpeg 4.2.2.
I also added FFmpeg path  in the environment variables.

 
### What is the Current behavior?
I am running my tests on chrome and all the tests are working fine without video capturing. Once I add video options in .testcaferc.json then tests run till the end and stuck at one point where test script is getting failed. Even quarantine mode is not working with video options. The browser remains in the opened state for unlimited time

 "videoPath": "artifacts/videos",
  "videoOptions": {
    "singleFile": false,
    "failedOnly": false,
    "ffmpegPath": "D://RFP//ReactJs-Application//ffmpeg//bin",
    "pathPattern": "${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.mp4"
  },
  "videoEncodingOptions": {
    "r": 20,
    "aspect": "4:3"
  },

Once I remove video option (above code) from testcaferc.json file then script works and quarantine mode also works.
 
### What is the Expected behavior?
Video should be recorded with ffmpeg 
 
### What is your web application and your TestCafe test code?
import {selector} from 'testcafe';

fixture `MyFixture`
.meta(`fixtureID`,`1`)
.meta({author:`QASource`, CreationDate:`20 May 2020`})
.meta({ severity: 'low', testedWebVersion: '1.0' })

.page `http://www.google.com/`;

test ('google description', async t=> {
    await t
        .setNativeDialogHandler(() => true)
        .click('#populate')
        .click('#submit-button');

});

<details>
<summary>Google.com</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```
import {selector} from 'testcafe';

fixture `MyFixture`
.meta(`fixtureID`,`1`)
.meta({author:`QASource`, CreationDate:`20 May 2020`})
.meta({ severity: 'low', testedWebVersion: '1.0' })

.page `http://www.google.com/`;

test ('google description', async t=> {
    await t
        .setNativeDialogHandler(() => true)
        .click('#populate')
        .click('#submit-button');


});

 Specify your
operating system: Win 10
testcafe version: 1.8.5
node.js version: 13.13.0
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by AutomationTester143** [comment]
Specify your
operating system: Win 10
testcafe version: 1.8.5
node.js version: 13.13.0
Chrome:81

**Comment by AlexKamaev** [comment]
I was able to reproduce the issue. I think that the cause of the issue is that your path does not contain the filename part. Please add `ffmpeg.exe` at the end of your "ffmpegPath" definition.

**Comment by AutomationTester143** [comment]
Thanks AlexKamaev

**Comment by AutomationTester143** [comment]
yes, its working with full path. Thanks

**Comment by miherlosev** [comment]
It's not a bug. [This](https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/screenshots-and-videos.html#basic-video-options) TestCafe help topic describes that the `ffmpegPath` parameter should contain a path to the FFmpeg codec executable. So, the filename part is required.
