### ISSUE TITLE
Test steps executed before page load completely finished

### ISSUE THREAD

**Issue by bartzielonka** [DevExpress/testcafe#5127]
### What is your Test Scenario?

In order to properly test email alerts I need to be able to log in and add alert to my account through 'email alert' button.
 
### What is the Current behavior?

`click()` is happening before page is completely loaded (using  `.navigateTo` action). TC `Loading Web Page...` tag disappears before browser throbber animation is done.
Pop up modal on my page is not opened.

Behavior is even visible just from looking at the page when tests are running. 

@AlexKamaev comment: 
> Situation when the next action is being executed while the page is not yet loaded is incorrect. 

 
### What is the Expected behavior?

`.click()` on button happens after page is completely loaded. Pop up modal opens on click.

### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

```
Sent compressed .zip file with project (project URL included) over your support email.
```

Shared by 

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 

```
helpers.js file:
import { RequestLogger } from 'testcafe';

class Helpers {
  constructor () {
    this.logger = (url, method = 'get') => {
      return RequestLogger((request) => {
        return request.url === url &&
          request.method === method
      });
    };
  };
};

export default new Helpers();
```

```
test.js file:
import helpers from '../commons/helpers';
import { Selector } from 'testcafe';

const logger = helpers.logger('https://url', 'post');

fixture `Test fixture`
.requestHooks(logger)
.beforeEach(async (t) => {
    await t
      .maximizeWindow()
      .navigateTo('https://url')
  })

test('My test', async t => {
    await t
        // Click happens before navigate to is done.
        .click(Selector('._17dZy8').nth(2))
        .wait(10000)
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
Sent compressed .zip file with project over your support email.
```
</details>

<details>
<summary>Attachements</summary>

```
Sent video over your support email.
```
</details>

### Steps to Reproduce:

1. Copy project to you local folder.
2. Run TestCafe from command line.
3. See that click is happening before page load.
 
### Your Environment details:
 
* testcafe version:                   TestCafe 1.8.0, TestCafe 1.8.4 (tested on both)
* node.js version:                    v13.1.0, v14.3.0 (tested on both)
* command-line arguments:  testcafe chrome tests/test.js
* browser name and version: Chrome 83.0.4103.61 OR Microsoft Edge 83.0.478.37
* platform and version:          macOS 10.15.4 
* other:                                    none

**Comment by bartzielonka** [comment]
@AlexKamaev I dig a bit...

Problems are starting when you are adding `.requestHooks(logger)` without `.page('https://url')` in fixture in the first place. When this happens steps are executed before page load.

What was happening in my test originally:
```
fixture `Fixture title.`
  .page `homepage.url`
  .requestHooks(logger)
  .beforeEach(async (t) => {
    await t
      .maximizeWindow()
      .useRole(roles.regularUser)
  })`

datSet((data) => {
  test(`Create alert through button under: '${data.name}'.`, async (t) => {
    await t
      .click(buttonSelector)
      .further_code.........
  })
})
```

After useRole I was going back to `homepage.url` (reload is normal when you go out of the useRole function). I am unlucky because `homepage url` is where you are redirected within a role as well. So exactly the same url was loading twice.
fyi `PreserveUrl: True` does not really matter in my case.

This means that for a moment between those two loads page was ready and it was enough for TC to start executing some code (my click). I decided to bypass `.page` this would help to make a difference between `homepage.url` and url you land on after log in. However in this case loading problems are starting which I described in this ticket.

**Comment by miherlosev** [comment]
Hi @bartzielonka 

> Problems are starting when you are adding .requestHooks(logger) without .page('https://url') in fixture in the first place. When this happens steps are executed before page load.

We need to debug the page loading process to research ways to improve the test starting logic. Could you please send me a small example where we can reproduce the problem locally?

**Comment by bartzielonka** [comment]
@miherlosev Thank you for your response. 
I've sent the example to TestCafe support email, title `Relates to issue: 5127`.

**Comment by miherlosev** [comment]
See explanation in https://github.com/DevExpress/testcafe/issues/5042#issuecomment-633994478
