### ISSUE TITLE
Uncaught Exception with Empty Stack Trace

### ISSUE THREAD

**Issue by sukhvinderb** [DevExpress/testcafe#5138]
I see an Uncaught Exception which makes my tests to fail. My test basically clicks on the links on the left panel of the page. It gives uncaught exception on certain links. Every time I run the the test, it fails on a different link
Uncaught exception:
Error:
Browser: Chrome 81.0.4044.138 / Linux 0.0.0

I am using TestCafe version 1.8.1
Environment details:
 
* testcafe version:                   1.8.1
* node.js version:                    v10.16.3
* command-line arguments:  --script $TEST_SCRIPT --console --video --reporter spec,my-reporter:/tc_automation/test_results --system-url $MY_SYSTEM_URL
* browser name and version: Chrome 81.0.4044.138
* platform and version:          Linux /3.10.0-514.26.2.el7.x86_64

**Comment by LavrovArtem** [comment]
This information is not sufficient to reproduce the issue. Could you please share a minimal project with us? We will examine it and check for a suitable solution.

**Comment by sukhvinderb** [comment]
@LavrovArtem The web application has a panel on the left of the page which has links. The test is clicking on the link one at a time to see if it loads the appropriate page. The test executes all the steps successfully but leaves Uncaught exception with empty stack trace. I have seen a similar issue on your repo but that has been closed.I am not using headless browser. It works some time and does not work other time

**Comment by Farfurix** [comment]
@sukhvinderb

Hello,

> The web application has a panel on the left of the page which has links. The test is clicking on the link one at a time to see if it loads the appropriate page. The test executes all the steps successfully but leaves Uncaught exception with empty stack trace.

Thank you for the additional information, but, unfortunately, it doesn't give us a clue. To find the cause of the issue, we need to reproduce it locally. Please send us a sample project and we'll do our best to find a solution.
