### ISSUE TITLE
TestCafe cannot click buttons at a specific website

### ISSUE THREAD

**Issue by alexey-lin** [DevExpress/testcafe#5141]
A button click has no effect. If I unlock the page, all works just fine. If I record this test scenario with TestCafe Studio, I get a test that cannot run.

Please, see the [T891136](https://supportcenter.devexpress.com/internal/ticket/details/T891136) for details.

**Comment by alexey-lin** [comment]
[Ionic UI Components](https://ionicframework.com/) is used on this page. I don't know if it matters.

**Comment by Ogurecher** [comment]
This issue was resolved in DevExpress/testcafe-hammerhead#2346 so I'm closing it
