### ISSUE TITLE
Documentation: wrong condition example in custom reporters

### ISSUE THREAD

**Issue by pavelsaman** [DevExpress/testcafe#5145]
I'm not sure if this "bug" fits in here, but I have not found a better way to reach you.

In your documentation on this site: https://devexpress.github.io/testcafe/documentation/reference/plugin-api/reporter.html and also here: https://devexpress.github.io/testcafe/documentation/guides/extend-testcafe/reporter-plugin.html you repeatedly write something like:

```
const hasErrors   = !!errors.length;
const result      = hasErrors ? `passed` : `failed`;
```

or

```
const hasErr      = !!testRunInfo.errs.length;
const result      = testRunInfo.skipped ? 'skipped' : hasErr ? `passed` : `failed`;
```

but if `testRunInfo` is an array that contains errors, then it will have non-zero length if there're some errors. If you use `!!` then, you will end up with `true` in `hasErr`. Assigning "passed" in such a case doesn't seem what was intended.

I honestly kept looking into this for a while because this bug seems to be on so many places in the documentation that I couldn't believe it's actually wrong. But there's one piece of code where it's used correctly:

```
const hasErr = !!testRunInfo.errs.length;

    if (hasErr) {
        errs.forEach((err, idx) => {
            this.newline()
                .write(this.formatError(err, `${idx + 1}) `));
        });
    }
```

The default spec reporter here: https://github.com/DevExpress/testcafe-reporter-spec/blob/master/src/index.js use it in a similar manner, that is "printing/assigning **failed**" when `hasErr` is true.

**Comment by AlexKamaev** [comment]
Thank you for pointing out this issue. I confirm that it's a bug in our documentation. We'll correct it.
