### ISSUE TITLE
Ability to modify user agent for remote browser in saucelabs

### ISSUE THREAD

**Issue by sree27** [DevExpress/testcafe#5146]
### Are you requesting a feature or reporting a bug?

Feature

### What is your Test Scenario?

Substitute a User Agent #
Use the userAgent parameter to substitute a user agent string.
testcafe $'chrome:emulation:userAgent=\'Mozilla/5.0 (Windows NT 10.0\\; Win64\\; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36\'' test.js

We are using saucelabs to launch the chrome browser, when we launch the chrome browser we are not able to override useragent string. We want a similar option available when using saucelabs

### What is the Current behavior?

Can not override user agent string when using saucelabs browser

### What is the Expected behavior?

Ability to override user agent string  when using saucelabs browser

### How would you reproduce the current behavior (if this is a bug)?

1. use saucelabs to launch chrome
 "browsers": ["saucelabs:chrome:Windows 10"]

#### Provide the test code and the tested page URL (if applicable)

 
Your website URL (or attach your complete example):

Your complete test code (or attach your test files)

```js

```
### Your Environment details:
 
* testcafe version:                  "^1.8.2",
* node.js version:                   node:10-alpine
* command-line arguments:  "testcafe \"chrome:emulation:userAgent='functional-test'\" custom-steps/index.js features/*.feature --tags ~@skip"
* browser name and version: 
* platform and version:          
* other:                                   
"testcafe-browser-provider-saucelabs": "^1.8.0",

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. The specified user agent is very similar to Chrome 70 user agent. You can run Chrome 70 instead of changing the user agent:
```
"browsers": ["saucelabs:chrome@70:Windows 10"]
```
If you need to completely change the user agent, you can use the [SAUCE_CAPABILITIES_OVERRIDES_PATH](https://github.com/DevExpress/testcafe-browser-provider-saucelabs#configuration) environment variable and provide a capability override file with the following structure:
```json
{
  "goog:chromeOptions": {
        "args": ["--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"]
   }
}
```
