### ISSUE TITLE
Not able to click on buttons where AngularJS component is passed a disabled property

### ISSUE THREAD

**Issue by luujam2** [DevExpress/testcafe#5147]
### What is your Test Scenario?
We're using AngularJS (1.x), I'd like to click a button contained inside a wrapping component. The wrapping component contains a `disabled` property which doesn't necessarily mean the component is disabled; it's just passed to other nested components. I'm guessing when TestCafe attempts to click it, the `disabled` property of the AngularJS component stops the event from working.
 
### What is the Current behavior?
Clicking on the accordion or any of its contents does nothing. However the component can still be manually toggled.
 
### What is the Expected behavior?
Clicking on the accordion should open it. Interaction of its contents should react accordingly.
 
### What is your web application and your TestCafe test code?
Please clone and run the test here: https://github.com/luujam2/testcafe-angularjs.
Supporting codepen: https://codepen.io/jl00161/pen/rNOXLmZ

### Steps to Reproduce:

1. Go to the aforementioned github repository
3. Clone repository
4. run `npm i`
5. run `npm test`
6. Modify the codepen to remove the disabled property
7. run the test again
 
### Your Environment details:
 
* testcafe version:                   1.8.5
* node.js version:                    10.18.1
* command-line arguments:  
* browser name and version: Chrome 83
* platform and version:          MacOS 10.14

**Comment by AlexKamaev** [comment]
Thank you for your input. I was able to reproduce the issue.

**Comment by LuudJanssen** [comment]
I'm also running into this issue. I found that this happens from me from version 1.8.3 and later.

**Comment by AndreyBelym** [comment]
Probably relatedto #5240

**Comment by miherlosev** [comment]
Hi @luujam2

A similar [issue](https://github.com/DevExpress/testcafe/issues/5240) was fixed.
I cannot check the shared example, because I cannot get through the 'I am human' check in TestCafe.
Could you please modify your example so that we can download it and run it locally?
