### ISSUE TITLE
Mouse up event seems to be not triggered when dragged.

### ISSUE THREAD

**Issue by hd-esteban** [DevExpress/testcafe#5148]
I have this test page ( http://test-viewer.kristianhristov.com/test/A2-simple-with-zoom.html ) where I would like to test the zoom panel. 

Basically when the chair is clicked I expect the zoom panel to be displayed and when mouse is moved the zoom panel should be moved. Everything works fine at this point whit some other tests I have. 

The problem I'm facing is to test the drag functionality of the zoom panel when user drags it. For that case the zoom panel should be closed because the mouse down/mouse up events has been triggered and zoom panel  has not been configured to be moved with the drag events, so it should be closed. 

When I test it manually as you can confirm with the example I'm sharing when zoom panel is opened and you drag the zoom panel it is closed as expected, but when I perform the action with Test Cafe the panel is not closed.
 
```
import { Selector } from 'testcafe';

const testCaseName = `Zoom`;

fixture(testCaseName).page('http://test-viewer.kristianhristov.com/test/A2-simple-with-zoom.html');

test("Zoom panel should be closed when element is dragged.", async t => {
  await t.wait(20000).click(Selector('.cylindo-viewer-frame-1'));
  let mainZoomCnt = await Selector('.cylindo-zoom-imagery').parent();
  // drag zoom container
  await t.drag(
    mainZoomCnt,
    -100,
    -100,
    {
      offsetX: 300,
      offsetY: 300,
      speed: 0.1
    }
  ).wait(1000);
  await t
    .wait(500)
    .expect(mainZoomCnt.exists).ok()
    .expect(mainZoomCnt.visible).ok();
    
});
```

* testcafe version:                  1.8.5
* node.js version:                    v10.13.0
* browser name and version: Google Chrome | 83.0.4103.61
* platform and version:           macOS 10.14.4

**Comment by AlexKamaev** [comment]
Thank you for your input. I was able to reproduce the issue.

**Comment by SergeyShurygin** [comment]
We haven't found any workaround at this time.  We will update this issue once we have any results.

**Comment by Esteban26** [comment]
Thanks Sergey

**Comment by Esteban26** [comment]
Hello @DevExpress team, any news here?

**Comment by AlexSkorkin** [comment]
We will update this issue once we have any news.

**Comment by Esteban26** [comment]
Hi @AlexSkorkin , do you have any update on this issue?

**Comment by AlexSkorkin** [comment]
No updates yet.

**Comment by Esteban26** [comment]
Hi test cafe team, any updates about this issue?

**Comment by AlexSkorkin** [comment]
No updates yet.
