### ISSUE TITLE
Custom selector SelectorOptions timeout property

### ISSUE THREAD

**Issue by orihomie** [DevExpress/testcafe#5151]
It seems this property dont work at all because no matter what value do I pass here - it fails without awaiting passed amount of time, would it be 1000 or 100000

What am I doing wrong?

```js
import { Selector } from 'testcafe';

const elementByXPath = Selector((xpath) => {
  const iterator = document.evaluate(
    xpath,
    document,
    null,
    XPathResult.UNORDERED_NODE_ITERATOR_TYPE,
    null
  );
  const items = [];

  let item = iterator.iterateNext();

  while (item) {
    items.push(item);
    item = iterator.iterateNext();
  }

  return items;
});

export default function (xpath: string, timeout?: number) {
  if (!timeout) timeout = 9000;

  return Selector(elementByXPath(xpath), { timeout: timeout });
}
```

**Comment by SergeyShurygin** [comment]
Hi,

I've attached a sample that works for me. Please modify it or send a test sample showing the issue on a public page.

[test-xpath-timeout.zip](https://github.com/DevExpress/testcafe/files/4717076/test-xpath-timeout.zip)
