### ISSUE TITLE
Tests hanging on Testcafe Version 1.8.5

### ISSUE THREAD

**Issue by smithahebbar** [DevExpress/testcafe#5152]
### What is your Test Scenario?
 Login to the app.
 
### What is the Current behavior?
Login to app works fine, but after login there is an initializing page which doesn't move forward. The page keeps hanging at that step. I reverted the Testcafe version from 1.8.5 to 1.8.1, the app started working fine. There is no hanging issue with 1.8.1. Please investigate the issue.
 
### What is the Expected behavior?
The App has to login successfully and land on the home page
 
### What is your web application and your TestCafe test code?

<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```
class login: 
login = async (t, creds_keyword) => {
    if ((await creds_keyword) === undefined) {
      await t.typeText(this.email_field_name, urls_creds.get_creds().email, {
        paste: true
      });
    } else {
      await t.typeText(
        this.email_field_name,
        urls_creds.get_login_creds(creds_keyword).email,
        {
          paste: true
        }
      );
    }

In my login test:
fixture`Login to application`
  .page`${url_and_creds.get_base_url()}`.beforeEach(async t => {
  await login.login(t);
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
 "staging": {
    "test_user": {
      "email": "abc@xyz.com",
      "password": "......",
      "base_url": "https://login.com"
    },

```
</details>

<details>
<summary>Your complete test report:</summary>

```
[
](url)
```
</details>

<details>
<summary>Screenshots:</summary>

```
[
<img width="1187" alt="Screen Shot 2020-05-31 at 6 39 10 PM" src="https://user-images.githubusercontent.com/18411642/83441759-e908ac80-a3fb-11ea-99f0-25c8e756f909.png">
](url)
```
</details>

### Steps to Reproduce:

1. run the testcafe -e chrome tests/Platform/Login/test_login_page.js --env=staging in command line.
2. Above testcase with login to app.
3. After login the tests just wait /hang on the initializing page. 

 
### Your Environment details:
 
* testcafe version: 1.8.5                   
* node.js version: v12.17.0                
* command-line arguments:  testcafe -e chrome tests/Platform/Login/test_login_page.js --env=staging
* browser name and version: chrome 83.0.4103.61
* platform and version: macOS 10.15.4, Linux 0.0 ,Ubuntu 18.04.1      
* other:

**Comment by SergeyShurygin** [comment]
We would love to assist you and diagnose this issue. However, the information you shared is insufficient for me to determine the cause of the issue and find a precise solution. Please share the public URL of your website or a simple sample that we can run on our side.
 
If your website sits behind a proxy and requires authentication, I will not be able to access it. Our policy prevents us from accessing a customer’s internal resources without prior written approval from the entity that owns the server/web resource. If you want us to research the problem further, we’ll need access to the server/web resource. Please ask the website owner to send us (support@devexpress.com) a written confirmation. It must permit DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes.

As an alternate way, you can debug testcafe locallу (https://devexpress.github.io/testcafe/documentation/recipes/debugging/chrome-dev-tools.html) and check if there are any unhandled exceptions. Also, ensure that there are no errors in browser's console.
