### ISSUE TITLE
hammerhead (Illegal invocation) Err

### ISSUE THREAD

**Issue by kimpazzang** [DevExpress/testcafe#5153]
### What is your Test Scenario?
Management system> Click the button > No response to any action
 
### What is the Current behavior?
Page  (hammerhead )js error
 
### What is your web application and your TestCafe test code?
    await t
        .typeText(Selector('input[name="managerId"]'), 'stqatest123', { replace: true })
        .click(Selector('#***Id'))
        // .pressKey('tab').pressKey('enter')

<details>
    "esotope-hammerhead": {
      "version": "0.5.1",
      "resolved": "https://registry.npmjs.org/esotope-hammerhead/-/esotope-hammerhead-0.5.1.tgz",
      "integrity": "sha512-h3zWENn0KTJYZRj+Hl9lAVzp+KDSljtfkA2SdQC2H7aQWdTXBwTRb6y6a+jvapOQYF9fLJqslZYnIkfHZwTKDg==",
      "requires": {
        "@types/estree": "^0.0.39"
      }
    },
</details>
<details>
![jserr](https://user-images.githubusercontent.com/66294699/83497868-b3dc8700-a4ed-11ea-81bc-9e88750ced0a.jpg)

</details>
<details>
Elements information
![1](https://user-images.githubusercontent.com/66294699/83984077-c16a9480-a965-11ea-87f7-5b337f1960d5.jpg)
![2](https://user-images.githubusercontent.com/66294699/83984081-c596b200-a965-11ea-965a-ac1e00b9de16.jpg)

</details>

**Comment by miherlosev** [comment]
Hi @kimpazzang 

I am afraid this information is not sufficient to find the cause of the issue. Could you please provide a small example so that we can reproduce it on our side?

**Comment by kimpazzang** [comment]
upload Elements information Hope to useful.
Manual operation this button is also normal. And all other buttons on the web page work fine.

**Comment by Farfurix** [comment]
@kimpazzang 

Hello,

We need an example project (or a public URL) to reproduce the issue on our side. Could you please provide it?

**Comment by kimpazzang** [comment]
it is the background management system page，so only company IP can visit this page, but I don't have enought permission to add External IP address...

In addition, and my department is an automated testing part, so I do not have the developer's permission to view the original webpage code files....

soo sorry..But is there no other way to confirm this issues?

**Comment by AlexanderMoiseev** [comment]
Hello,

Unfortunately, we need a sample. If you manage to create one, please reopen the issue.
