### ISSUE TITLE
dom.lib types not recognized 

### ISSUE THREAD

**Issue by criskrzysiu** [DevExpress/testcafe#5155]
After upgradidng to Angular 9 and typescript 3.8.3 we are facing problem with testcafe. It's throwing "ReferenceError: Document is not defined", "ReferenceError: Event is not defined" etc. for types from typescript dom.lib.ts.

**Comment by miherlosev** [comment]
Hi @criskrzysiu 

I am afraid this information is not sufficient to find the cause of the issue. Could you please provide an example so that we can reproduce it on our side?
