### ISSUE TITLE
Close browser after each test feature

### ISSUE THREAD

**Issue by AutomationTester143** [DevExpress/testcafe#5158]
### What is your Test Scenario?
I want to close the browser after each test and want to start browser before each test

### What are you suggesting?
Reason I want to clear browser cache after each test

**Comment by AlexSkorkin** [comment]
After a test is completed, TestCafe resets the browser state:

* deletes cookies
* clears local and session storages
* reloads the tested page

Please refer to the following topic for more information: [Isolated Test Runs](https://devexpress.github.io/testcafe/documentation/how-it-works/#isolated-test-runs).

If this is not what you're after, please elaborate on why the current behavior does not meet your requirements.

**Comment by AutomationTester143** [comment]
Thanks for looking into this. 

I have once scenario:
I want to execute Testrail testcases after each test. 
I know t.aftereach() test is supported in Fixture and t.aftereach () is working fine for single fixture.

But If I have 5 fixtures and each are in a single file then I  have to apply  t.aftereach (// testrail execution code ) on each file for each fixture. So this is kind of code redundancy in each fixture. 

runner.aftereach() should be supported so that some operations can be done after each test irrespective of the fixture.

**Comment by Ogurecher** [comment]
Hello,
Thank you for the feature suggestion, we appreciate your input. Please share more information on your specific use case: why do you want to close the browser after each test?

**Comment by bladyk1** [comment]
I have a problem with MSAL login (login via Azure), I have 2 tests which need to be fired one by one.
Tests steps are:

1. login to 1st app which is using MSAL login
2. do some actions

1a. login to 2nd app which is using MSAL login
2a. do some actions

The problem is I cannot login to second application, there is a white page with loading which never ends(till the timeout). I was debugging this and seems local storage or session storage are not cleared. Also i tried to clear everything by using: 
localStorage.clear, sessionStorage.clear, deleteCookies with no luck.
What I found is the issue can be related to MSAL itself
https://docs.microsoft.com/en-us/answers/questions/263335/msal-sign-out-does-not-appear-to-clear-cache.html
I think closing browser after each test can be a solution here. This feature is implemented in many other test frameworks, as optional of course.

**Comment by miherlosev** [comment]
Hi @bladyk1 

Try to use the [Fixture.disablePageCaching](https://testcafe.io/documentation/402782/reference/test-api/fixture/disablepagecaching) option. If the issue still persists, please create a separate issue with an example that reproduces the issue.

**Comment by eminecevik** [comment]
Hello, 
We aim to close the driver after each UI end-to-end test. This is prompted by the occasional occurrence of tests getting stuck without clear explanations on our end. While we understand that TestCafe is designed to reset the browser state, in the event of a test or browser becoming unresponsive, what course of action would you suggest?

**Comment by Bayheck** [comment]
Hello, I am not sure that closing the driver after each UI end-to-end test will fix the issue.

> This is prompted by the occasional occurrence of tests getting stuck without clear explanations on our end.

This behavior is incorrect. Could you share an example where we can reproduce this behavior even occasionally? With it, we'll be in a better position to find out why it occurs.

**Comment by eminecevik** [comment]
Thanks for your response. Unfortunately, I can't share all the steps to reproduce with you but I'm sharing the example trace of what we observe in the pipeline.

```
[201]GeneralError: The Chrome 109.0.5414.119 / Debian 10.13 browser disconnected. If you did not close the browser yourself, browser performance or network issues may be at fault.

[202] at BrowserConnection._createBrowserDisconnectedError (/app/node_modules/testcafe/src/browser/connection/index.ts:318:16)

[203] at Timeout._onTimeout (/app/node_modules/testcafe/src/browser/connection/index.ts:323:30)

[204] at listOnTimeout (node:internal/timers:569:17)

[205] at processTimers (node:internal/timers:512:7) {

[206] code: 'E1002',

[207]  data: [ 'Chrome 109.0.5414.119 / Debian 10.13' ]

[208] }

[209] > cp -v allure/allure-results/* allure-temp/

[210]'allure/allure-results/58094963-ead4-4686-8590-f61c2988cbfb-container.json' -> 'allure-temp/58094963-ead4-4686-8590-f61c2988cbfb-container.json'

[211]'allure/allure-results/categories.json' -> 'allure-temp/categories.json'

[212]'allure/allure-results/environment.properties' -> 'allure-temp/environment.properties'

[213](node ./src/index.js --test-meta identifier=test-2 || true)

[214]ERROR: Job failed: execution took longer than 2h0m0s seconds
```
Browsers remain open in our execution of the e2e pipeline and this causes the execution time from the usual 30min to 2h

**Comment by Bayheck** [comment]
Hello, 
Unfortunately, we still don’t have enough information to help you. We understand now what you observe in the pipeline, yet we still need more details. If you would like us to help you find a solution to the problem, please send us a small example that illustrates the described issue.
