### ISSUE TITLE
Can we filter using request body while using RequestMock?

### ISSUE THREAD

**Issue by amalsgit** [DevExpress/testcafe#5173]
### What is your Test Scenario?
I want to filter request based on the request body so as to provide the right mock response. It does not seem to work though. Any help with this is appreciated.
My code looks like this:
```RequestMock()
    .onRequestTo({
      url: /\/api\/assets\/.*\/staged-document/,
      method: 'POST',
      body: '{id: something}'
    })
    .respond((req, res) => {
      res.headers['access-control-allow-credentials'] = 'true';
      res.headers['access-control-allow-origin'] = loadConfig.baseUrl;
      res.headers['access-control-allow-methods'] = 'GET, POST, PUT, OPTIONS';
      res.statusCode = status;
      res.setBody({something})
```
 
### What is the Current behavior?
TestCafe does not seem to filter based on the body defined in the `onRequestTo` section. It is filtering only based on the url and method parameters.
Am I doing this right? or is this a bug?
 
### What is the Expected behavior?
I expect the RequestMock to filter based on the request body specified in `onRequestTo` section
 
### Your Environment details:
 
* testcafe version:                   1.8.4

**Comment by Farfurix** [comment]
@amalsgit 

Hello,

You can use a predicate function in your `onRequestTo`. I created a simple example to demonstrate it:

```js
import { RequestMock } from 'testcafe';

fixture `Fixture`;

const mock = RequestMock()
    .onRequestTo(request => {
        console.log(request); // The full request object

        return request.url.indexOf('google') > -1; // Here you can set your own rule
    })
    .respond((req, res) => {
        res.setBody('<html><body><h1>OK</h1></body></html>');
    });

test
    .requestHooks(mock)
    ('test', async t => {
        await t
            .navigateTo('https://google.com')
            .debug(); // Here we can see our mocked response
    });
```
Result:
![Capture](https://user-images.githubusercontent.com/30019338/84017521-7497b580-a987-11ea-85e7-d635148a82f7.PNG)
