### ISSUE TITLE
Typescript warnings for using get/set with default target option

### ISSUE THREAD

**Issue by TAVkiev** [DevExpress/testcafe#5174]
### What is your Test Scenario?
Adding getter or setter into ts file. In order to make compilation process path - I am adding target option to tsconfig.json:
"target": "ES5"
 
### What is the Current behavior?
typescript error:
Accessors are only available when targeting ECMAScript 5 and higher

After explicitly adding target option, testcafe warning appears:
You cannot override the "target" compiler option in the TypeScript configuration file.
 
### What is the Expected behavior?
using features es5 and higher. getters/setters, flat etc

<details>
<summary>Your complete configuration file (if any):</summary>

```
tsconfig.json
{
  "compilerOptions": {
    /* Strict Type-Checking Options */
    "strict": true /* Enable all strict type-checking options. */,
    "noImplicitAny": true /* Raise error on expressions and declarations with an implied 'any' type. */,
    "strictNullChecks": true /* Enable strict null checks. */,
    "strictFunctionTypes": true /* Enable strict checking of function types. */,
    "noImplicitThis": true /* Raise error on 'this' expressions with an implied 'any' type. */,
    "alwaysStrict": true /* Parse in strict mode and emit "use strict" for each source file. */,
    "skipLibCheck": true,

    /* Additional Checks */
    "noUnusedLocals": true /* Report errors on unused locals. */,
    "noUnusedParameters": true /* Report errors on unused parameters. */,
    "noImplicitReturns": true /* Report error when not all code paths in function return a value. */,
    "noFallthroughCasesInSwitch": true /* Report errors for fallthrough cases in switch statement. */,
    "esModuleInterop": true,
    "target": "ES5"
  },
  "exclude": [
    "resources"
  ]
}
```
```
testcaferc.json
{
	"browsers": "chrome",
	"skipJsErrors": true,
	"appInitDelay": 3000,
	"selectorTimeout": 10000,
	"assertionTimeout": 10000,
	"pageLoadTimeout": 30000,
	"speed": 1,
	"stopOnFirstFail": false,
	"tsConfigPath": "tsconfig.json",
	"concurrency": 2,
	"screenshots": {
		"path": "reports/screenshots",
		"takeOnFails": true,
		"pathPattern": "${DATE}_${TIME}/${FIXTURE}_${TEST}.png"
	}
}

```
</details>

### Steps to Reproduce:

1. create some .*ts file
3. add getter
4. See the error from typescript compiler:
Accessors are only available when targeting ECMAScript 5 and higher
Warning from testcafe:
You cannot override the "target" compiler option in the TypeScript configuration file.
 
### Your Environment details:
 
* testcafe version:    1.8.4               
* node.js version:     12.13.0               
* browser name and version:  Chrome 83.0.4103.61 (Official Build) (64-bit) 
* platform and version:    Windows

**Comment by Dmitry-Ostashev** [comment]
TestCafe doesn't allow setting the compilerOptions.target property because it is internally defined specially for different node.js versions. In common cases, ECMAScript ES2017 or ES2018 are used. Therefore, I was unable to reproduce the issue with get/set accessors on my side. Could you please attach a simple project that will show the problem with these accessors?

**Comment by chikunov** [comment]
@Dmitry-Ostashev 
Simple example would be just to create a page object like
```
export class Button {
    private _root: Selector;

    public get label() {
        return this._root.find('[data-test~="button__label"]');
    }

    public constructor() {
        this._root = Selector('[data-test~="button"]');
    }

    public click = async () => {
        await t.click(this._root);
    };
}
```

ts compiler is going to complain about `label` property because tsconfig.json does not have a target specified (per testcafe requirements) and defaults to an older version. It affect IDE only, the build itself is still successful (probably because testcafe overrides it with es2015+)

**Comment by alexey-lin** [comment]
Hi @chikunov,

You can actually use getters and setters in your tests. Also, you don't need to compile them - TestCafe will take care of it during a test run. If your IDE shows annoying warnings, you can probably solve this using of IDE settings.

**Comment by chikunov** [comment]
> Hi @chikunov,
> 
> You can actually use getters and setters in your tests. Also, you don't need to compile them - TestCafe will take care of it during a test run. 
this is what i said?

any IDE uses tsservice that in turn uses tsconfig.json to determine and show validations. It doesn't know that testcafe overrides them somewhere later with a different target.

**Comment by chikunov** [comment]
Workaround for now:
1. Create tsconfig.testCafe.json with general configuration per documentation requirements, i.e:
```
{
    "compilerOptions": {
        "lib": ["es6"],
        "strict": true,
        "strictNullChecks": true,
        "downlevelIteration": true,
        "importHelpers": false,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "types": ["node"]
    },
    "include": ["./src/**/*.ts"]
}
```

2. Create tsconfig.json so that tsservice would be able to work with all the necessary features. Values for target and module should correspond with https://github.com/DevExpress/testcafe/blob/master/src/tsconfig.json:
```
{
    "extends": "./tsconfig.testcafe.json",
    "compilerOptions": {
        "target": "es2017",
        "module": "commonjs"
    }
}
```

3. Set up TestCafe to use tsconfig.testCafe.json in .testcaferc.json:
```
{
    "src": ["./src/**/*.fixture.ts"],
    "tsConfigPath": "./tsconfig.testcafe.json"
}
```

4. Profit. Now you're able to use getter/setter props without your IDE complaining.

**Comment by wentwrong** [comment]
Thanks for sharing your workaround. We'll think about adding it to our guide about TypeScript Support.
As an alternative, you can use your `tsconfig.json` with the overridden `target` option. TestCafe will show a message about that, but it won't interrupt the compilation process and can be safely ignored.
Nevertheless, we will consider ways to disable warnings about overridden TypeScript compiler options.
