### ISSUE TITLE
Nested iframes switching error

### ISSUE THREAD

**Issue by AGrigorii** [DevExpress/testcafe#5175]
### What is your Test Scenario?
Open app within Salesforce new lightning, trying to communicate with them
 
### What is the Current behavior?
I get error while trying to switch on the second-nested iframe
 
### What is the Expected behavior?
I switch to the deepest iframe and click app's button
 
<details>
<summary>My complete test code (I've also sent you an email with credentials):</summary>

 
```js
import {Selector} from 'testcafe';

fixture('iframes')
    .page('https://eu13.lightning.force.com/lightning/n/CFCRM10__Application');

test('iframes', async (t) => {
    await t.typeText(Selector('input.username'), '*****', {replace: true});
    await t.typeText(Selector('input.password'), '*****', {replace: true});
    await t.click(Selector('#Login'));


    await t.wait(30000).switchToIframe(Selector('div.viewport').find('iframe'));
    await t.wait(3000).switchToIframe(Selector('iframe')); // -> 1) The iframe in which the test is currently operating does not...
    await t.wait(3000).switchToIframe(Selector('iframe'));
}); 
```
</details>

### Your Environment details:
 
* testcafe version:                   1.8.6
* node.js version:                    12.15.0
* browser name and version: Chrome 83
* platform and version:          Windows Server 2016 standard
* other:                                    it fails even when chrome web security turned off

**Comment by Dmitry-Ostashev** [comment]
Thank you for your report and example. I've reproduced the issue on my side. We'll research it and notify you as soon as we have any news.

**Comment by AGrigorii** [comment]
Any updates?

**Comment by AlexSkorkin** [comment]
Once we get any results, we will share them here.

**Comment by AGrigorii** [comment]
Any updates?)

**Comment by SergeyShurygin** [comment]
We will update this thread once we have any results.
