### ISSUE TITLE
Unable to login successfully after one test, when use Role in Mobile mode

### ISSUE THREAD

**Issue by xiaofeixiaer** [DevExpress/testcafe#5179]
### What is your Test Scenario?
i have many test cases in a fixture, all cases need to login.I create a role by Role function, and use the same role in each test case.
 
### What is the Current behavior?
When i run in mobile mode ,only the first case login successfully, other cases unable to use role to  login  successfully.
However, when i run in desktop mode, all cases can use role login successfully.

### What is the Expected behavior?
All cases can use the same role to login successfully when in mobile mode.
 
### Test Code
 
```
import { Role } from 'testcafe';

const role = Role('http://example.com', t => {
   t
        .typeText('#login', 'TestUser')
        .typeText('#password', 'testpass')
        .click('#sign-in');
});

fixture `f`

test(`test 1`, async t => {
    await t.useRole(role);

    await t.click('h1');
});

test(`test 2`, async t => {
    await t.useRole(role);

    await t.click('h1');
});
```
 
### Your Environment details:
 
* testcafe version:                   1.8.3
* node.js version:                    14.2.0
* command-line arguments:  testcafe chrome:emulation:device=iphone X;cdpPort=9223
* browser name and version: chrome:emulation:device=iphone X

**Comment by AlexKamaev** [comment]
It's difficult to say anything precise without a working example. We would really appreciate it if you share an example or public url to your site to reproduce the issue.

In addition, I want to mention that your code inside the role initializer contains an error.
The role initializer is async function, so the role definition should be as follows:

```JS
const role = Role('http://example.com', async t => {
   await t
        .typeText('#login', 'TestUser')
        .typeText('#password', 'testpass')
        .click('#sign-in');
});
```

In theory, these missing `async/await` definitions could be the cause of your issue.
