### ISSUE TITLE
ResponseMock setBody now only accepts a string as value

### ISSUE THREAD

**Issue by stefanschenk** [DevExpress/testcafe#5180]
I'm using the latest TestCafe version (1.8.6) in which you added type definitions for RequestMock.respond methods. 

In former versions of TestCafe I would add a json object as response body with the `setBody` method and it would work perfectly, but the new `ResponseMock` interface only accepts a string for the setBody method. 

The following does not work anymore with TestCafe 1.8.6;

```
return RequestMock()
    .onRequestTo((request: RequestData) => {
      ...
    })
    .respond((request: RequestOptions, response: ResponseMock) => {
      response.statusCode = 200;
      response.setBody({
        data: {
          result: {
            success: true,
          },
        },
      });
    });
```

**Comment by AlexKamaev** [comment]
Thank you a lot for pointing this out to us. I reproduced the issue. I discussed the issue with the team and we concluded that the `setBody` method should accept `object|string|Buffer|null` as a parameter. We'll fix the definition.
