### ISSUE TITLE
[docs] Rewrite the "Filter with a Predicate" example for the RequestMock case

### ISSUE THREAD

**Issue by Farfurix** [DevExpress/testcafe#5182]
Found in 
https://github.com/DevExpress/testcafe/issues/5173,
https://stackoverflow.com/questions/62219146/change-testcafe-requestmock-api-response-based-on-request-body.

We should have here a `RequestMock.onRequestTo` example insted of `RequestLogger` one: https://devexpress.github.io/testcafe/documentation/reference/test-api/requestmock/onrequestto.html#filter-with-a-predicate

**Comment by titerman** [comment]
The "Filter with a predicate" section now includes the correct example.

https://testcafe.io/documentation/402763/reference/test-api/requestmock/onrequestto#filter-with-a-predicate
