### ISSUE TITLE
Update Travis docs to use headless browsers instead of xvfb

### ISSUE THREAD

**Issue by cdrini** [DevExpress/testcafe#5183]
(not sure where a docs update belongs, so skipped the template)

The current docs for Travis integration suggest using Xvfb. This _does not_ support resizing (so not usable for mobile testing). Using headless browsers seems like the better suggestion here.

I recently updated https://github.com/internetarchive/bookreader to this scheme here: https://github.com/internetarchive/bookreader/commit/19a233a6f09a92ba376ef50a2a88a013a3220354 , and would like to update the docs to suggest this .travis.yml as the default over what's currently specified in https://devexpress.github.io/testcafe/documentation/guides/continuous-integration/travis.html .

**Comment by AlexKamaev** [comment]
Thank you for sharing your opinion. I think we can add a note to the documentation, stating that it's possible to use headless browsers instead of Xvfb.
