### ISSUE TITLE
Add 'cdpPort' property to the 't.browserInfo'

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#5187]

**Comment by abhinaba-ghosh** [comment]
Hey @miherlosev , is there any update?

**Comment by wentwrong** [comment]
Hi @abhinaba-ghosh,
There are no updates yet. You can use the following workaround to obtain information about the `cdpPort` in use:
```js
const openedBrowsers = t.testRun.browserConnection.browserInfo.provider.plugin.openedBrowsers;

for (const browserId in openedBrowsers)
    console.log(browserId, openedBrowsers[browserId].cdpPort);
```
Please note that the workaround uses a private API - it can be changed in the future without notification.
