### ISSUE TITLE
Docs: need to describe that `Runner.run()` promise is cancellable 

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#520]

**Comment by VasilyStrelyaev** [comment]
I guess using the `stop()` function and cancelling individual tasks are both valid scenarios?

**Comment by inikulin** [comment]
`Runner.stop()` cancels all task produced by runner. By cancelling `Runner.run()` promise you cancel individual task.

**Comment by VasilyStrelyaev** [comment]
I understand what they do, I just wanted to make sure that we expect users to use both.
Thanks!

**Comment by VasilyStrelyaev** [comment]
Does such an example make sense?

```js
const tasks = [];

tasks.push( runner
    .src('tests/fixture1.js')
    .browsers([remoteConnection, 'chrome'])
    .reporter('json')
    .run()
);

tasks.push( runner
    .src('tests/fixture2.js')
    .reporter('xunit')
    .run()
);

server.on('request', function (request, response) {
    parsedUrl = urlUtils.parse(request.url, true);
    if (parsedUrl.pathname == '/cancel')
        await tasks[parsedUrl.query['taskNum']].cancel();
});
```

**Comment by VasilyStrelyaev** [comment]
I was just trying to imagine what can trigger the cancel...

**Comment by VasilyStrelyaev** [comment]
pardon
```js
server.on('request', async (request, response) => {
    parsedUrl = urlUtils.parse(request.url, true);
    if (parsedUrl.pathname == '/cancel')
        await tasks[parsedUrl.query['taskNum']].cancel();
});
```

**Comment by inikulin** [comment]
I'd rather go with example like this:

```js
const taskPromise = runner
    .src('tests/fixture1.js')
    .browsers([remoteConnection, 'chrome'])
    .reporter('json')
    .run();

await taskPromise.cancel();
```

**Comment by VasilyStrelyaev** [comment]
emm.... I was thinking of something more real-life but if it looks too complicated...
Maybe we'll have a real-life sample in **Receipts**.

**Comment by inikulin** [comment]
> emm.... I was thinking of something more real-life but if it looks too complicated...

This doesn't look like a real life example for me. Also I have no idea how it will be adopted by users. We use it to cancel task in the studio, I'd rather describe the possibility of doing so without any premise. I believe it will be really uncommon scenario, so it shouldn't go to recipes. We need just to mention that we have such API

**Comment by VasilyStrelyaev** [comment]
ok, got it
