### ISSUE TITLE
[docs] Create a best practices article

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#5201]
Some of our competitors have such articles. We should promote smart assertions, page objects, using Roles for login and so on. [[1](https://stackoverflow.com/questions/61172186/what-would-be-the-ultimate-golden-standard-for-writing-a-login-function )]

**Comment by VasilyStrelyaev** [comment]
I'll start a list, extend it please:

- [ ] Smart Assertions
- [ ] Page Objects
- [ ] Roles for Login

**Comment by kirovboris** [comment]
- [ ] File structure
- [ ] Clean up on beforeEach
- [ ] Testing only e2e scenarios / e2e tests appliance
