### ISSUE TITLE
span element pressKey('pageup') don't work

### ISSUE THREAD

**Issue by Anthony-zjz** [DevExpress/testcafe#5205]
version:
"testcafe": "1.8.1",
"@angular/common": "9.1.3",
"@angular/compiler": "9.1.3",
"@angular/compiler-cli": "9.1.3",
"@angular/core": "9.1.3",

e2e code: Implement AM/PM conversion

public MeridianSpan: Selector = Selector('span.meridian');
test.('testcafe', async (t: any) =>{
await t
           .click(MeridianSpan)
           .pressKey('pageup')
           .expect(MeridianSpan.textContent)
           .eql('PM');
})

In this case, .presskey ('pageup') will not work, testCafe does not support the span element of pageup/ Pagedown?

**Comment by Ogurecher** [comment]
Hello,

I couldn't reproduce this issue. Please share the error message you are getting and your webpage URL or an example page. It would be even better if you re-create the issue and fill in all requested fields.
