### ISSUE TITLE
Switching from main page to iframe gets failed

### ISSUE THREAD

**Issue by salmansrabon** [DevExpress/testcafe#5208]
My test scenario is 
1. Navigate to a site
2. Input product details
3. Click on submit button
4. Now switching to iframe

Result: .click(...).switchToIframe(...).type is    
      not a function

Test Code:
const btnSubmit=Selector('#submit')
const txtCardNo=Selector('#card-number')
const txtCVV=Selector('#cvv')
const txtExpiryDate=Selector('#expiration-date')
test('My Test', async t => {
    await t
    .click(btnSubmit)
    .switchToIframe('#purchase-iframe')    //error found in this line
    .type(txtCardNo,'4001 1003 0000 1001')
    .type(txtCVV,'012')
    .type(txtExpiryDate,'06/25')
    .wait(2000)

})

**Comment by devmondo** [comment]
from your post, i see this error

> Result: .click(...).switchToIframe(...).type is
> not a function

which makes sense, because there is no type method on testcafe controller, check this out
https://devexpress.github.io/testcafe/documentation/reference/test-api/testcontroller/typetext.html
