### ISSUE TITLE
Documentation: XSRF-TOKEN X-XSRF-TOKEN processing

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [DevExpress/testcafe#5213]
### What are you suggesting?
It would be great benefit if documentation will cover dealing with XSRF-TOKEN cookie processing in testing - setting cookie and header for applications which uses that mechanism to prevent Cross Site Request Forgery.

**Comment by AlexKamaev** [comment]
We decided to close this issue since we do not have enough user feedback about it.
