### ISSUE TITLE
Testcafe doesn't throw any error if it looses connection to the browser

### ISSUE THREAD

**Issue by danielhammerl** [DevExpress/testcafe#5216]
### What is the Current behavior?

if i start my testcafe tests running on chromium 83 in concurrency mode and shortly after starting, i open the windows Task Manager and quit all chromium processes which are open and all which will open , testcafe doesn't throw any error and runs forever.

 
### What is the Expected behavior?

Testcafe should exit and throw an error (maybe after a specified timeout)
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.8.6
* node.js version:                    12.13.0
* command-line arguments:  
* browser name and version:  chromium 83
* platform and version:          Windows 10
* other:

**Comment by miherlosev** [comment]
Hi @danielhammerl

Thank you for sharing this use case. We will try to handle the loss connection with the browser in a more suitable way.
