### ISSUE TITLE
Rename file e

### ISSUE THREAD

**Issue by zhkostadinov** [DevExpress/testcafe#5218]

**Comment by zhkostadinov** [comment]
Hi team.
Is there any way to rename the file before being downloaded?  
With the current implementation, the file is downloaded automatically in the default browser file destination. 
Thanks

**Comment by miherlosev** [comment]
Hi @zhkostadinov 

> the file is downloaded automatically in the default browser file destination.

This is a native browser behavior. Could you please describe the scenario where it is necessary?

**Comment by zhkostadinov** [comment]
Hello. The flow is:
**without Testcafe:** when I'm trying to save the file via Chrome, the modal is pop up. In that modal, I can enter the name of the file and save the destination.
**with Testcafe:**  on the same page, the file is downloaded automatically without that modal. I've tried to run the script with `--user-data-dir` flag, but it doesn't work. 
Any advice?

**Comment by AlexanderMoiseev** [comment]
Hello, do you want to download a file to a non-default directory and then make certain test assertions?

**Comment by zhkostadinov** [comment]
Hi. The Testcafe does not wait for the file t be downloaded. If the file takes 2minuts to be downloaded, the test cafe just closes the browser. That just terminate the download process. 
Any advice on how to prevent that?

**Comment by wentwrong** [comment]
Hello, @zhkostadinov,

You can take a look at this [example](https://github.com/DevExpress/testcafe-examples/tree/master/examples/wait-for-file-download) if you encounter problems with waiting after downloading a file.

If you have more questions about TestCafe usage, please refer to StackOverflow - an amazing platform for users to ask and answer questions. We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe/#contributing)).

**Comment by zhkostadinov** [comment]
Hi wentwrong.
Thanks for the example, but that is not the issue.
The issue is in that when the file is larger, let's say 100MB, will take 3-4minus to be downloaded.
How behaves TestCafe in this case, when the download is started after a while just closes the  browser. That just interrupt the download process!

**Comment by wentwrong** [comment]
Hello, @zhkostadinov,

TestCafe's [Built-In Wait Mechanisms](https://devexpress.github.io/testcafe/documentation/guides/concepts/built-in-wait-mechanisms.html) don't support waiting until a file is downloaded. Therefore, to prevent premature closing, you should explicitly pause a test for a required amount of time.

If the example with a function for checking if a file exists (which is just a wrapper around [t.wait](https://devexpress.github.io/testcafe/documentation/reference/test-api/testcontroller/wait.html)) does not help, you can use the t.wait itself:

```js
await t
    .click('#downloadButton')
    .wait(APPROPRIATE_AMOUNT_OF_TIME_TO_DOWNLOAD);
```

**Comment by zhkostadinov** [comment]
Hi @wentwrong .
Thanks for the reply. I can't use t.wait(amount of time), because that will make the TC flaky. 
Download the might cost 20 seconds or 1,20 minutes. 
Thanks.

**Comment by AndreyBelym** [comment]
If the download time can vary between 20 seconds and 2 minutes, you can change the wait time in the [example](https://github.com/DevExpress/testcafe-examples/tree/master/examples/wait-for-file-download) mentioned by @wentwrong:
```js
async function waitForFileDownload (path) {
    for (let i = 0; i < 10; i++) {
        if (fs.existsSync(path))
            return true;

        await t.wait(20000);
    }

    return fs.existsSync(path);
}
```
If this code doesn't work with your page, could you please provide an example that can be used to reproduce the issue?

**Comment by zhkostadinov** [comment]
@AndreyBelym  thanks for the example. I already move to the "old good Selenium" to tackle my problem.
