### ISSUE TITLE
Set file to upload appears to not be working on dataloader.io and jenkins with Xvfb

### ISSUE THREAD

**Issue by ngrossi** [DevExpress/testcafe#5219]
jenkins file

#!groovy

final String RED = '#ff6666'
final String GREEN = '#07ff00'

String PIPELINE_ENV

//SLACK_CHANNEL = 'bat-bot' /* Slack channel to be used */

pipeline {
    agent {
        dockerfile true
    }

    parameters {
        string(name: 'PIPELINE_USER', defaultValue: 'nicolas.grossi@mulesoft.com', description: 'Username')
    }

    /* https://jenkins.io/doc/book/pipeline/syntax/ cron documentation */
    triggers {
        cron('H H * * *')
    }

    environment {
        DATALOADER_AUTOMATION_PASSWORD = credentials('DATALOADER_AUTOMATION_PASSWORD')
        //SLACK_WEBHOOK = credentials('slack-webhook')
        BROWSER = "chrome"
    }

    stages {
        stage('Initialize') {
            steps {
                script {
                    sh "node -v"
                    sh "npm -v"
                    // if (params.PIPELINE_ENV == null)
                    //     PIPELINE_ENV = "prod"
                    // else
                    //     PIPELINE_ENV = params.PIPELINE_ENV
                    sh "export BROWSERSTACK_DISPLAY_RESOLUTION=2880x1800"
                    sh "Xvfb :1 -screen 0 2880x1800x24 &"
                    sh "sleep 3"
                    sh "export DISPLAY=:1"
                    sh "DISPLAY=:1"
                    sh "rm -rf node_modules"
                    sh "npm i"

                }
            }
        }
        stage("Dataloader UI sanity - tests - E2E - PROD") {
            steps {
                script{
                    environment = 'prod'
                }

                catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                /* CatchError documentation: https://jenkins.io/doc/pipeline/steps/workflow-basic-steps/*/ 
                /* -e option is to skip-test https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors */
                sh "DISPLAY=:1 ENV=${environment} npm run test"
                }
            }
        }
    }
}

-----

code on jenkins job

public async runTest(): Promise<any> {

    
    await DLNavigator.loginOnDL()

    await this.testCaseRunner.when('Go to New Task Import and Choose CSV', async () => {
    await t.click(dataloaderPage.newTaskButton)
    await t.click(dataloaderPage.importButton)
    await t.click(Selector('#wizard-view').find('span').withText('Account').nth(1))
    await t.click(Selector('#wizard-view').find('button').withText('Next'))
    await t.click(Selector('label').withText('Upload CSV'))
    await t.setFilesToUpload(Selector('label').withText('Upload CSV'), ['/hola.csv'])
    }).it('Go to Import and Choose CSV shuold be selected correctly')
}

click on button does not seems to wrk under this context:     await t.click(Selector('label').withText('Upload CSV'))

the above action does not open the file browser

test cafe version 1.8.6

**Comment by miherlosev** [comment]
Hi @ngrossi 

> the above action does not open the file browser

This behavior is expected. You don't need to initiate the opening of the 'Browse File' dialog. Instead, find an `<input type=file>` element that will contain the selected file.

You code should be changed as follows:

```js
await t.click(Selector('#wizard-view').find('button').withText('Next'))
await t.setFilesToUpload('<input selector>', ['/hola.csv'])
```

**Comment by ngrossi** [comment]
@miherlosev I will check that and let you know ASAP.

KR

Nico

**Comment by ngrossi** [comment]
public async runTest(): Promise<any> {

    
    await DLNavigator.loginOnDL()

    await this.testCaseRunner.when('Go to New Task Import and Choose CSV', async () => {
    await t.click(dataloaderPage.newTaskButton)
    await t.click(dataloaderPage.importButton)
    await t.click(Selector('#wizard-view').find('span').withText('Account').nth(1))
    await t.click(Selector('#wizard-view').find('button').withText('Next'))
    await t.setFilesToUpload(Selector('#upload-form-input-648'), ['/hola.csv'])
    }).it('Go to Import and Choose CSV shuold be selected correctly')

with the above code works. thanks!
