### ISSUE TITLE
Is it possible to use webdriver capabilities in testcafe

### ISSUE THREAD

**Issue by saurabh2k26** [DevExpress/testcafe#5220]
I am experimenting with running testcafe tests on android docker images.

It seems, i need to define few webdriver capabilities in my test scripts like platformName.

more about webdriver capabilities: https://w3c.github.io/webdriver/#capabilities

How to implement same in testcafe?

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.
We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe/#contributing)). 

TestCafe core doesn't use WebDriver. However, setting WebDriver options may be supported by third-party browser provider plugins or Docker images you want to use. It's better to specify which third-party software (Docker images, plugins) do you use and take a look at its documentation.
