### ISSUE TITLE
[Docs] Describe how to use the file upload functionality

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#5225]
Describe the following things:
* you don't need to click on the element that should initiate the opening of the `Browse File` dialog
* `Browse File` dialog is not shown - it's expected behavior.
* You should find a target <input type=file> and populate it. Target input is an input that should contain the files selected in 'Browse File' dialog.
* If you are using the custom file loader you should not 'submit' file.

**Comment by titerman** [comment]
We don't plan to address this issue in the near future. Feel free to reopen the ticket if the issue is important for you.
