### ISSUE TITLE
Wrong focus behavior on click on Safari

### ISSUE THREAD

**Issue by palpatine1991** [DevExpress/testcafe#5226]
### What is your Test Scenario?
Clicking on customized checkbox should follow the browser behavior of assigning the focus
 
### What is the Current behavior?
Currently, at some cases, clicking on customized checkbox does not out the focus into checkbox input in all cases. It happens in all browser EXCEPT Safari.
 
### What is the Expected behavior?
Testcafe should follow the browser behavior
 
### What is your web application and your TestCafe test code?
https://material.angular.io/components/checkbox/overview

Following code passes on both Chrome and Safari. But manually, it does NOT work in Safari (focus is not assigned to native checkbox.

 
```js
fixture`Checkbox - Desktop - tooltip - Tab `
    .page(`https://material.angular.io/components/checkbox/overview`)
test.only('Should check and uncheck checkbox', async () => {
    const chck = Selector('mat-checkbox');
    const realChck = chck.find('input');
    const checkboxSquare = chck.find('.mat-checkbox-inner-container');

    let isChecked = await realChck.checked;

    await t
        .expect(isChecked).notOk()
        //check by click
        .click(checkboxSquare);

    isChecked = await realChck.checked;

    await t
        //should be checked now
        .expect(isChecked).ok()
        //change state by pressing spacebar
        .pressKey('space');

    isChecked = await realChck.checked;

    await t.expect(isChecked).notOk();
});
 
```

**Comment by alexey-lin** [comment]
Hi @palpatine1991,

Thank you for reporting the issue. We reproduced it and will look into it. But I have to note that usually there is no need in testing browser-specific behavior. It's already tested by browser developers. And Material Design components should be tested by their developers too.

**Comment by palpatine1991** [comment]
@alexey-lin Well, we have Safari in the list of supported browsers and in this case, our customer reported this anomaly .

When we wrote the testcafe E2E test to cover it, we have found out that the testcafe test did pass even before the fix (we are wrapping the material components somehow so we were able to fix the focus behavior)
