### ISSUE TITLE
Click events firing twice during tests

### ISSUE THREAD

**Issue by alienintheheights** [DevExpress/testcafe#5227]
### What is your Test Scenario?

Click a button, except it to be clicked once and only once 

### What is the Current behavior?

During test runs, many buttons are being fired twice. Because these trigger REST calls, we can see entries like this in our docker logs during test runs, note the duplicate api call and the timestamps

```
2020-06-16 15:00:33.711 ... updateRecord record= {"name":"Unit Test 1592319589885",
2020-06-16 15:00:33.733 ... updateRecord record= {"name":"Unit Test 1592319589885",
````
This results in DB conflict errors, etc, and from that, test failures.

### What is the Expected behavior?

 One click, one outcome

### What is your web application and your TestCafe test code?

 
```

```
<details>
<summary>Your website URL (or attach your complete example):</summary>
Internal application, can not share.

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 // for example....
  switch (action) {
    case 'Test':
        await t.expect(selectors.inlineTestMenuItem.exists).ok()
                .click(selectors.inlineTestMenuItem)
                .expect(journey.nextSibling().innerText).eql('Ready')
        break
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
   
    "browsers": ["chrome"],
    "src": ["test/functional/pages/*-test.js"],

    "speed": 1,
    "selectorTimeout": 20000,
    "assertionTimeout": 6000,
    "pageLoadTimeout": 6000,

    "quarantineMode": true,
    "debugMode": false,
    "debugOnFail": true,
    "stopOnFirstFail": false,
    "skipJsErrors": true,
    "skipUncaughtErrors": true,
    "disablePageCaching": true,
    
    "reporter": [
        {
            "name": "spec"
        },
        {
            "name": "xunit",
            "output": "test/functional/test-report/uiTestReport.xml"
        },
        {
            "name": "html",
            "output": "test/functional/test-report/uiTestReport.html"
        }
    ],

    "screenshots": {
        "path": "test/screenshots",
        "takeOnFails": true,
        "pathPattern": "${DATE}_${TIME}/test-${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.png"
    },

    "videoPath": "test/artifacts/videos",
    "videoOptions": {
        "singleFile": true,
        "failedOnly": true,
        "pathPattern": "${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.mp4"
    },
    "videoEncodingOptions": {
        "r": 20,
        "aspect": "4:3"
    }
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```
AssertionError: expected false to be truthy

Browser: Chrome 83.0.4103.106 / Windows 10
Screenshot: E:\dev\webapp\test\screenshots\2020-06-18_12-22-08\test-36\Chrome_83.0.4103.106_Windows_
10\errors\1.png

366 |    switch (status) {
367 |    case 'Test':
368 |            // check current status
369 |        await t.expect(await getCurrentStatus()).eql('Draft')
370 |                // check status button
> 371 |                .expect(statusButton.exists).ok()
```
</details>

<details>
<summary>Screenshots:</summary>

```
![Inkedtesterror_LI](https://user-images.githubusercontent.com/682815/85054771-2ee6a400-b162-11ea-8a2e-186178de77b1.jpg)


```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.8.6
* node.js version:                    10.20.1 
* command-line arguments:  testcafe
* browser name and version: chrome, latest 
* platform and version:          Windows 10 
* other:

**Comment by AlexanderMoiseev** [comment]
Hello,

Unfortunately, we can't help here until we reproduce the problem. Please send us a sample project.

**Comment by alienintheheights** [comment]
Could you point me to where in the testcafe code this click function is executing so I can debug this? We only see this double fire issue while running tests; it never happens while using the application. I'll also see if I can construct a standalone example.

**Comment by alexey-lin** [comment]
@alienintheheights I'm afraid it might be not so straightforward. You can start digging [here](https://github.com/DevExpress/testcafe/blob/master/src/test-run/index.js#L635) or [here](https://github.com/DevExpress/testcafe/blob/master/src/client/automation/playback/click/click-command.js#L21). A standalone example would be great, thanks.

**Comment by alienintheheights** [comment]
I put a debug point in the testcafe _`enqueueCommand()` and am seeing that consistently that whenever a test click() double fires as described above there are two click events occurring within the `_enqueueTask`. When it works, there's just one, as expected. This makes me wonder if there's something in the emit step of these events that's getting tangled up.

so our code has:
```
console.log('inlineFinishMenuItem clicking Finish')
await t.click(selectors.inlineTestMenuItem)
console.log('inlineFinishMenuItem awaiting Draft')
await t.expect(dataSet.tableStatus(name, 'draft').exists).ok()
```

The corresponding fail state console output looks like

```
inlineFinishMenuItem clicking Finish
_enqueueCommand click
_enqueueCommand click
inlineMenuAction awaiting Draft
```

Whereas the non-fail state is this

```
inlineFinishMenuItem clicking Finish
_enqueueCommand click
inlineMenuAction awaiting Draft
```

The insanely frustrating part is the inconsistency. Mostly everything works. But one in, say, 5 times will misfire like this. 

I hope to have a standalone example this week. FWIW, our app is ReactJS and the buttons are via Material UI.

Also, we upgraded to 1.8.7 today

**Comment by SergeyShurygin** [comment]
Thank you for sharing your findings with us. This information is still insufficient for us to determine the cause of the issue and find a precise solution. We are looking forward to seeing a real example where we can debug the issue.
