### ISSUE TITLE
APIv2: Hybrids - we need to figure out behavior on page unloads

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#523]

**Comment by inikulin** [comment]
\cc @DevExpress/testcafe I still don't have a good idea about what we should do if page unload occurs during Hybrid execution. There are two options here:
- [ ] On page load return undefined as hybrid result, since it was not able to complete on given page
- [ ] Re-execute hybrid on new page

Also I think we should use some part of the already machinery for the actions (do not send results on unloads, store result in local storage, etc.). 
So, let me know what do you think?

**Comment by kirovboris** [comment]
I think re-executing hybrid on new page can hide problems in a test, so i prefer the first way.

**Comment by inikulin** [comment]
> I think re-executing hybrid on new page can hide problems in a test, so i prefer the first way.

Yes, but what if hybrid execution happens at the moment of some buffer-redirect page (like on gmail login) and returns `undefined`. It will be quite confusing.

**Comment by kirovboris** [comment]
In this case user doen't understand at which moment the hybrid is executing. It's confusing me too. And what does mean result of hybrid on buffer-redirect page if we have calculated it?

**Comment by inikulin** [comment]
We logged in on gmail. Out barriers triggers next action which is Hybrid execution. We execute hybrid. During login gmail redirects through number of pages and at this moment we execute hybrid - user receives undefined result.

**Comment by inikulin** [comment]
Also, it's not correct semantically to have function result affected by side effects. If function has determined behavior (it's code) it's result should always be consistent within this determined behavior.

**Comment by kirovboris** [comment]
Probably, we should raise the test error in this case. Isn't it?

**Comment by inikulin** [comment]
Well, the more we discussing it the more I like the second option. We trying to make user to not care about page transitions and side effects, right? And then he executes hybrid and receives error because of page load.

**Comment by miherlosev** [comment]
I think that behaviour should be customizable.
If redirect expected then we should execute hybrid on the next page.
If not then we shoue raise the error.

**Comment by AndreyBelym** [comment]
Can we put a barrier, that prevents a page from changing the location, on `beforeunload` event, when a Hybrid execution start, and change the location after it is finished?

**Comment by inikulin** [comment]
> Can we put a barrier, that prevents a page from changing the location, on beforeunload event, when a Hybrid execution start, and change the location after it is finished?

Hybrid functions is an observation action - it's shouldn't affect page state

**Comment by inikulin** [comment]
> I think that behaviour should be customizable.
If redirect expected then we should execute hybrid on the next page.
If not then we shoue raise the error.

Too complicated.

**Comment by inikulin** [comment]
> Can we put a barrier, that prevents a page from changing the location, on beforeunload event, when a Hybrid execution start, and change the location after it is finished?

Also, it doesn't solve issue with buffer-redirect pages. I don't want state of buffer-page, I need state of the page once I've logged in

**Comment by kirovboris** [comment]
I afraid of unpredictable result of hybrid. If buffer page loads significant time i will have differrent results on every test machine, in continuous integration etc.

**Comment by AndreyBelym** [comment]
> Also, it doesn't solve issue with buffer-redirect pages. I don't want state of buffer-page, I need state of the page once I've logged in

If you aware of buffer pages in your app, you can just wait, or check the location of current page, return null and try again.

**Comment by AndreyBelym** [comment]
As it looks for me, Hybrids execution will be far more predictable, if we will just execute in place where we are now. If we can not finish it, we should just to inform the user about the incident. Maybe throw an error, or introduce a status code.

**Comment by inikulin** [comment]
> As it looks for me, Hybrids execution will be far more predictable, if we will just execute in place where we are now. If we cannot finish it, we should just to inform the user about the incident. Maybe throw an error, or introduce a status code.

But it breaks the paradigm we use for actions. I don't understand why we allow it for actions, but don't allow it for hybrids. Also, what about Hybrids passed as action selectors? In that case they will have different behavior which is yet again inconsistent

**Comment by AlexanderMoskovkin** [comment]
What if hybrid function executing leads to page location changing? If we will re-execute it after redirect it'll be an endless loop.

**Comment by inikulin** [comment]
> What if hybrid function executing leads to page location changing? If we will re-execute it after redirect it'll be an endless loop.

I like this argument.

**Comment by inikulin** [comment]
So, in case of page unload we need to throw `Client code execution was interrupted by page change` error?

**Comment by AndreyBelym** [comment]
> What if hybrid function executing leads to page location changing? If we will re-execute it after redirect it'll be an endless loop.

Looks like it conflicts with
> Hybrid function execution is an observation

**Comment by AndreyBelym** [comment]
BTW I feel like that Hybrids are far more powerful to restrict them for observation use only.

**Comment by inikulin** [comment]
@AlexanderMoskovkin can you take care on this issue, since you have the best knowledge of the action-related driver code.

**Comment by AlexanderMoskovkin** [comment]
sure

**Comment by AlexanderMoskovkin** [comment]
> So, in case of page unload we need to throw Client code execution was interrupted by page change error?

So, we don't allow to change a page location via a hybrid function?

> Looks like it conflicts with

A customer can write anything in a function, we should process this correct

**Comment by inikulin** [comment]
> BTW I feel like that Hybrids are far more powerful to restrict them for observation use only.

Well, in functional testing **good** test shouldn't perform any actions by code, it should use user emulated actions. I think we should stick with paradigm that Hybrids should be use **primarily** for the observation. Otherwise we need to treat them as actions and e.g. they should be rejectable by page errors (but I believe it's not what you expect in most cases).

**Comment by AlexanderMoskovkin** [comment]
Agree

**Comment by AlexanderMoskovkin** [comment]
I'm working on this
