### ISSUE TITLE
Hovering over an element does not result in expected outcome.

### ISSUE THREAD

**Issue by fanik05** [DevExpress/testcafe#5230]
### What is your Test Scenario?

 When user hover his/her mouse pointer over language selector widget, it should expand.
### What is the Current behavior?

 In my testcafe script, I used the `t.hover` method to hover over the widget. But the widget doesn't expand.
### What is the Expected behavior?

 It should expand into selection menu for different languages.
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>
[Club Swan](https://member.clubswan.com/)

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
import { Selector } from 'testcafe';

fixture `Club Swan Login Page`
    .page `https://member.clubswan.com/`;

test('Check localize widget functions', async t => {
        await t 
            .hover(localizeWidget, {
                offsetX: 20,
                offsetY: 20,
                speed: 0.5
            })
            .wait(20000);
    });
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
  "name": "testcafe-versetile",
  "version": "1.0.0",
  "description": "testcafe different feature practice",
  "main": "index.js",
  "scripts": {
    "test": "testcafe chrome tests/",
    "headless-test": "testcafe 'chrome:headless' tests/"
  },
  "keywords": [],
  "author": "Fatin Noor Anik",
  "license": "ISC",
  "devDependencies": {
    "testcafe": "^1.8.6"
  }
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```
Running tests in:
 - Chrome 83.0.4103.106 / Windows 10

 Club Swan Login Page
 √ Check localize widget functions


 1 passed (32s)
```
</details>

<details>
<summary>Screenshots:</summary>

```
![normal_behavior](https://user-images.githubusercontent.com/48475054/85131731-32108b80-b259-11ea-9224-68a54a22eeae.png)
![testcafe_behavior](https://user-images.githubusercontent.com/48475054/85131753-3c328a00-b259-11ea-8527-ce5a3554dd17.png)
```
</details>

### Steps to Reproduce:

1. Go to Club Swan login page.
2. Hover the mouse pointer over the languge widget.
3. Observe.
4. Now Run the given testcafe script.
5. Observe.
6. See the screenshots section for further clarification.
 
### Your Environment details:
 
* testcafe version: 1.8.6                  
* node.js version: 12.18.0                   
* command-line arguments: npx testcafe chrome tests/ 
* browser name and version: Chrome 83.0.4103.106 
* platform and version: Windows 10         
* other: I am new to testcafe and Javascript. So, I may have done some silly mistake(s).

**Comment by Ogurecher** [comment]
Hello,

Thank you for your report. We've managed to reproduce this issue.
We'll update this thread once it's fixed.
