### ISSUE TITLE
Test is getting failed

### ISSUE THREAD

**Issue by arvindarun** [DevExpress/testcafe#5235]
<img width="1113" alt="Screenshot 1942-04-01 at 12 49 17 AM" src="https://user-images.githubusercontent.com/54062330/85233218-46ec4b00-b422-11ea-91f2-5102426296c0.png">

Can anyone help me with this issue

**Comment by mewc** [comment]
As the error says, you need to use a `https://mysite.com` address not `http://mysite.com`.

**Comment by arvindarun** [comment]
> As the error says, you need to use a `https://mysite.com` address not `http://mysite.com`.
After completing all the test steps getting this error message and the site is accepting http request

**Comment by alexey-lin** [comment]
It's hard to give you a definite answer as I didn't see your test code or a test page. I can only suggest you try using the [`--ssl` option](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#--ssl-options).

If you have questions about a TestCafe API, its usage and configuration, we recommend [StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)).

You may also find answers in our up-to-date [documentation](https://devexpress.github.io/testcafe/documentation/getting-started/) and [answered questions](https://stackoverflow.com/questions/tagged/testcafe) on StackOverflow. This may save your time.

If you have already looked there and have not found an appropriate answer, [file a new question on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe).
