### ISSUE TITLE
Browser freezes and goes into not responding state for IE 11

### ISSUE THREAD

**Issue by saibs** [DevExpress/testcafe#5236]
### What is your Test Scenario?

I have simple login form which is a aws amplify screen.
 
### What is the Current behavior?

When the tests run for login, the browser actually freezes for chrome, firefox and IE11 but it recovers for chrome and firefox after sometime but IE 11 never recovers and goes into not responding state. 

### What is the Expected behavior?

Login should work normally without freezing browser.

### What is your web application and your TestCafe test code?

 Link to the app

<details>
You can even give incorrect credentials.
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Role, Selector } from 'testcafe'

import { config } from './config'

export const admin = Role(`${config.baseUrl}`, async (t) => {
  await t
    .typeText(
      '[name="username"][data-test="username-input"]',
      config.appAdminUserName(),
    )
    .pressKey('tab')
    .typeText('[type="password"]', config.appAdminPassword())
    .pressKey('enter')
    .click('button[type=submit]')
    .expect(Selector('[data-testid="signout"]').exists)
    .ok()
})
```
</details>
[screen capture](https://user-images.githubusercontent.com/1705639/85275519-bc870400-b480-11ea-8812-dd9d72e87ec4.gif)

You can see in the gif attached, the first part of the video where I try to login manually which works fine, when I switch tab and running a remote test and performing same scenario the browser freezes for firefox but recovers after somepoint but never recovers for IE 11. Added breakpoints to show where the delay is in executing javascript.

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
  "src": ["./src/specs"],
  "tsConfigPath": "./tsconfig.json"
}

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                  1.86
* node.js version:                    12

* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by saibs** [comment]
Sent details of the application over support email.

**Comment by Farfurix** [comment]
@saibs 

Hello,

I confirm there are some differences in native/TestCafe behavior when the submit button is clicked. We need some time to examine it.

For the team.
1. Click the submit button without login/password:
Chrome 83 / Windows 10 - **failed**
IE 11 / Windows 10 - passed
Firefox 77 / Windows 10 - passed
```js
import { Role, Selector } from 'testcafe';

const pageURL = 'PAGE_URL';

const admin = Role(pageURL, async t => {
    await t
        .click(Selector('button[type=submit]'))
        .expect(Selector('span').withText('Benutzername darf nicht leer sein').exists).ok('', { timeout: 25000 });
});

fixture `Fixture`;

test
    .page(pageURL)
    ('test', async t => {
    await t
        .useRole(admin);
});
```
2. Click the submit button with incorrect login/password:
IE 11 / Windows 10 - **no result**
Chrome 83 / Windows 10 - **cannot type password**
Firefox 77 / Windows 10 - passed
```js
import { Role, Selector } from 'testcafe';

const pageURL = 'PAGE_URL';

const admin = Role(pageURL, async t => {
    await t
        .typeText(
            Selector('[name="username"][data-test="username-input"]'),
            'username',
        )
        .typeText(Selector('[type="password"]'), 'password')
        // .wait(3000)
        // .pressKey('enter')
        .click(Selector('button[type=submit]'));

    await t
        .expect(Selector('span').withText('Benutzer existiert nicht').exists).ok('', { timeout: 25000 });
});

fixture `Fixture`;

test
    .page(pageURL)
    ('test', async t => {
    await t
        .useRole(admin);
});
```

**Comment by saibs** [comment]
The page has css zoom settings, hence you cannot type in password, if opened with default resolution. I generally test with remote urls or resize window before running the tests to 1600x1200

**Comment by Farfurix** [comment]
@saibs 

Thank you for the additional information. We'll take it into account.

**Comment by saibs** [comment]
Further investigation hope it helps, browser freezes in testcafe when this particular computation is run
[AuthenticationHelper AWS amplify](https://github.com/aws-amplify/amplify-js/blob/8dd92959fbe11c328ec4f8e467c0929ed1e7e5ca/packages/amazon-cognito-identity-js/src/AuthenticationHelper.js#L179).
I believe it's a longer computation to encrypt password, and ie11 never recovers moving into non-responding mode.

**Comment by aleks-pro** [comment]
Hello @saibs ,

Thank you for the update. We will take this info into account.
