### ISSUE TITLE
APIv2: Use structured clone-like algorithm for Hybrid's result and arguments serialization

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#524]
- [x] Implement replicatior library with basic types serialization
- [x] Rename `ExecuteHybridFnCommand` to `ExecuteClientCodeCommand` 
- [x] Use replicator for Hybrid results and arguments
- [x] Hybrid functions and functions as parameters
- [x] Function as return value

**Comment by inikulin** [comment]
I'm working on this

**Comment by inikulin** [comment]
Ok, I would like to discuss how element descriptor will look like. Here are descriptors for different node types.

### Element
```js
{
    nodeType: 1,
    tagName: String,
    attributes: { name: value },
    namespaceURI: String,
    hasChildren: Boolean,
    childrenCount: Number,
    getParentNode: Hybrid,
    getChildNodes: Hybrid,
    width: Number,
    height: Number,
    text: String,
    style: <computed style>
}
```

### CommentNode
```js
{
    nodeType: 8,
    text: String,
    getParentNode: Hybrid
}
```


### CommentNode
```js
{
    nodeType: 8,
    text: String,
    getParentNode: Hybrid
}
```

### DocumentFragment
```js
{
    nodeType: 11,
    getChildNodes: Hybrid
}
```

### Document
```js
{
    nodeType: 9,
    getChildNodes: Hybrid
}
```

\cc @DevExpress/testcafe

**Comment by AlexanderMoskovkin** [comment]
It looks complete for me, I just was thinking about `id` and `className` for elements, but we can get it from `attributes`.

**Comment by georgiy-abbasov** [comment]
@inikulin, what about property `hasFocus` or `isFocused` for Element ?

```js
{
  hasFocus: `Hybrid`
}
```

**Comment by inikulin** [comment]
Added `focused` property and `hasClass` function

**Comment by AlexanderMoskovkin** [comment]
> what about property hasFocus or isFocused for Element

I'm not sure we should add the `focused` property because a dom element doesn't have any property like `focused` or `isActive`. You always can check this via  `Hybrid(() => document.activeElement)` that returns an element. But if you want, you can add)

**Comment by inikulin** [comment]
Well, it doesn't have `width` property as well, but we add it to simplify things

**Comment by inikulin** [comment]
BTW, I wonder if we should add `textContent` and `innerText` properties. Difference described here: https://developer.mozilla.org/en/docs/Web/API/Node/textContent

**Comment by georgiy-abbasov** [comment]
@AlexanderMoskovkin, i think it's easier
Using this
```js
test('Test', async t => {
// defining ourElement
 ok(ourElement.focused);
});
```
instead of
```js
const getFocusedElement = Hybrid(() => document.activeElement);


test('Test', async t => {
// defining ourElement
 var focusedElement = await getFocusedElement();

 equal(focusedElement, ourElement);
})
```

**Comment by AlexanderMoskovkin** [comment]
These are not completed examples, it should be like the following:
```js
var elementId = 'id';

test('1', async t => {
    const element = Hybrid(id => document.getElementById(id))(elementId);
    expect(element.focused).to.be.true;
});

test('2', async t => {
    const activeElement = Hybrid(() => document.activeElement)();
    expect(activeElement.id).is.eql(elementId);
});
```

So, there is no any difference =)
But I'm not against of the `focused` property publishing

**Comment by inikulin** [comment]
@AlexanderMoskovkin it makes sense if you want to assert various properties of element. So you will end up with two hybrids and two hybrid calls.

**Comment by AlexanderMoskovkin** [comment]
> BTW, I wonder if we should add textContent and innerText properties

@inikulin I have a question, what the `text` property returns. It works the same way as `textContent` ?

**Comment by churkin** [comment]
What about `innerHTML` ?

**Comment by churkin** [comment]
I often faced with this property in tests

**Comment by inikulin** [comment]
> @inikulin I have a question, what the text property returns. It works the same way as textContent 

I guess it should be more like `innerHTML` - ignore invisible nodes and `<script>` and `<style>` elements content. I guess we need `textContent` in addition

**Comment by inikulin** [comment]
> What about innerHTML ?

Can be really huge chunk of data. And I can't figure out common usage scenarios from the top of my mind

**Comment by churkin** [comment]
@inikulin I just open our aspxperience tests:

```javascript
'1. Click toolbar item (toolbar item is menu item)': function () {
        this.prevMarkup = getToolbarInnerMarkup();
       ....
    },

'2. Check changing content after toolbar item click. Other toolbar item click': function () {
        var currentMarkup = getToolbarInnerMarkup();
        notEq(currentMarkup, this.prevMarkup);
       ...
    },

```

**Comment by inikulin** [comment]
BTW, should we have `computedStyle` and `style` properties?

**Comment by inikulin** [comment]
@churkin This is an example of lazy poorly written test. It doesn't checks particular changes (e.g. new button appeared), but just checks for any markup changes. You can always create hybrid for `innerHTML`. But it's really bad usage example.

**Comment by inikulin** [comment]
BTW, do we filter hammerhead attributes set on element in sandbox?

**Comment by churkin** [comment]
@inikulin I agree, it's bad. But even we do it :)

**Comment by inikulin** [comment]
@churkin I'd rather not add it to descriptor - too huge overhead for each element

**Comment by churkin** [comment]
@inikulin 
>> BTW, should we have computedStyle and style properties?
Of course

**Comment by inikulin** [comment]
I mean both. AFAIK in old version we had only computed styles in recorder

**Comment by churkin** [comment]
I vote for both at the same time

**Comment by inikulin** [comment]
BTW, I guess we need `Location` object descriptor as well

**Comment by inikulin** [comment]
@churkin https://github.com/DevExpress/testcafe/issues/524#issuecomment-223017242?

**Comment by miherlosev** [comment]
> @churkin #524 (comment)?
https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/utils/dom.js#L339

**Comment by inikulin** [comment]
BTW, do we need additional properties (or subclass with addtional properties) for inputs? Like `value`, `checked`, etc.?

**Comment by inikulin** [comment]
Just figured out that pure Hybrids concept bring us back to situation then we have action argument which can't be awaited. E.g.:
```js
const someElement = await someHybrid(); // returns null, because e.g. didn't appeared yet 

await t.click(someElement);
```

What we can do:
### Option 1
Introduce special kind of hybrid: `Selector`. Forbid elements as return values in regular hybrids with appropriate message: `if you want to return DOM nodes use Selector`. Selector will behave like hybrids, but will expect `null` or DOM node as return value and will enable our standard element waiting mechanism. This also cures another issue: we've forbidden hybrids to be executed in beetwen page loads, but it will be possible with implicitly declared selectors.

### Option 2
Keep everything as is and suggest people to use `t.waitForElement`. 

### Option 3
Use "magical ways" of hybrid's execution with actions:
```js
t.click(someHybrid()) // don't execute hybrid immidiately, wait for next tick, check if was passed to action and use hybrid function as selector, instead of running hybrid machinery uses element waiting mechanism
```
Still has a problem, then we select element before action with separate hybrid call. But can be cured by use of `t.waitForElement`. If we'll have custom assertions with same machinery as actions things will get even simpler.

\cc @DevExpress/testcafe

**Comment by kirovboris** [comment]
I dislike the third option, because:
1. It waits extended time if element doesn't exist on page.
2. It's unclearly and can causes unstable tests.

First and second options are ok for me, but ```Selector``` hybrid function looks redundant.
The main point - I want to have the full control on my test and avoid "magical ways", when i don't understand how it works. Also similar machineries can cause large-scale and inexplicable failure of tests if we changed anything in the waiting of element.

**Comment by inikulin** [comment]
We've done here. Selector functionality and node descriptor discussion moved to #574
