### ISSUE TITLE
Allow to handle multiple windows in live mode

### ISSUE THREAD

**Issue by devmondo** [DevExpress/testcafe#5242]
### What is your Test Scenario?
Testing Multiple Windows new feature
 
### What is the Current behavior?
Without Live Mode it works fine, but once we enable Live Mode we get the following Error

```bash
GeneralError: You cannot use multi-window mode in "chrome".
    at LiveModeRunner._validateBrowsersForAllowMultipleWindowsOption (C:\projects\test\node_modules\testcafe\src\runner\index.js:338:15)
    at LiveModeRunner._validateAllowMultipleWindowsOption (C:\projects\test\node_modules\testcafe\src\runner\index.js:348:14)
    at C:\projects\test\node_modules\testcafe\src\runner\index.js:527:22 {
  code: 'E1056',
  data: [ '"chrome"' ]
}

``` 

### What is the Expected behavior?
To be able to use multi windows feature in Live Mode
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
fixture(`test`);
test(`test`, async (I) => {
 await I.openWindow(`https://google.com`)
}
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
const createTestCafe = require("testcafe");
let testcafe = null;

createTestCafe("localhost", 1337, 1338)
    .then(tc => {
        testcafe = tc;
        const runner = testcafe.createLiveModeRunner();

        return runner
            .src(["tests/fixture1.js"])
            .browsers(["chrome"])
            .run({
                allowMultipleWindows:true,
            });
    })
    .then(failedCount => {
        console.log("Tests failed: " + failedCount);
        testcafe.close();
    });
```
</details>

<details>
<summary>Your complete test report:</summary>

```
GeneralError: You cannot use multi-window mode in "chrome".
    at LiveModeRunner._validateBrowsersForAllowMultipleWindowsOption (C:\projects\test\node_modules\testcafe\src\runner\index.js:338:15)
    at LiveModeRunner._validateAllowMultipleWindowsOption (C:\projects\test\node_modules\testcafe\src\runner\index.js:348:14)
    at C:\projects\test\node_modules\testcafe\src\runner\index.js:527:22 {
  code: 'E1056',
  data: [ '"chrome"' ]
}



```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.8.7-rc.2
* node.js version:                    12.6.0
* command-line arguments:  
* browser name and version: Chrome Latest
* platform and version:          WIndows 10
* other:

**Comment by AndreyBelym** [comment]
Thank you for your report. The window managing feature is actively developed and still not ready for production use. Some TestCafe features can work incorrectly when it is enabled. We will consider improving compatibility with Live mode before the public release.
