### ISSUE TITLE
Do not hardcode dependencies versions

### ISSUE THREAD

**Issue by darkowic** [DevExpress/testcafe#5251]
Allow installing dependencies within some versions range - at least the bugfix range e.g `"testcafe-hammerhead": "^17.1.7",`. It will allow installing a newer package version with some fix (like this one https://github.com/DevExpress/testcafe-hammerhead/issues/2334) without waiting for a new testcafe version.

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. Currently, `testcafe` and `testcafe-hammerhead` have too many shared subsystems, and upgrading `testcafe` and `testcafe-hammerhead` packages independently can lead to unexpected compatibility problems. We will try to solve this problem in the context of issue https://github.com/DevExpress/testcafe/issues/4100.
