### ISSUE TITLE
Ability to set header for page url.

### ISSUE THREAD

**Issue by benmonro** [DevExpress/testcafe#5258]
### What is your Test Scenario?

We are using testcafe with flagger & istio for a canary rollout in our CI/CD pipeline.  as such we need to be able to set a header or cookie on the page.  Would be nice to add this globally to all of calls to `.page()` in testcafe.  If there's already a way to do this, please advise and we can close this ticket, but if not, I feel it would be a very useful feature to be able to set a cookie or header that `.page()` uses.

**Comment by LavrovArtem** [comment]
Could you please try the [RequestHook Class](https://devexpress.github.io/testcafe/documentation/reference/test-api/requesthook/) for your needs? If it isn't suitable for you, please describe your scenario in more detail.
