### ISSUE TITLE
[Not a bug] [Introduction] Smart Monkey - Free recorder for TestCafe

### ISSUE THREAD

**Issue by nglthach** [DevExpress/testcafe#5259]
Hi,

I'm Thach. I'm the author of Smart Monkey. I have added a functionality for exporting a project to TestCafe code. Here is the video for demo: https://www.youtube.com/watch?v=jQxYUu1KGhU

Please visit https://www.smartmonkey.app for more information!

Sincerely,
Thach

**Comment by Ogurecher** [comment]
Hello Thach,

Thank you for your work and the demo you sent. We appreciate your interest in our product.
