### ISSUE TITLE
[docs] Describe 'Add the capability to perform testing in multiple browser windows' feature

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#5261]
The description should contain the following things:
* the feature description should be marked as `BETA`.
* how to run TestCafe in the `Multiple windows` mode (https://github.com/DevExpress/testcafe/issues/912#issuecomment-618398461). 
* execution context on open/close windows: TestCafe automatically switches the execution context to the new opened window or to the parent of closed window. It allowing customers to avoid adding the additional 'switchToWindow' action.
* open/close/switch API. See the list of supported API methods [here](https://github.com/DevExpress/testcafe/pull/5210).
* the current restricts: [Videos and screenshots are not supported for child windows](https://github.com/DevExpress/testcafe/issues/5017), [Cloud browsers are not supported](https://github.com/DevExpress/testcafe/issues/5024)
* examples (see them [here](https://github.com/DevExpress/testcafe/pull/5210/files#diff-18f4394a493bcc63c2d89bd6cbffe496R94) and [here](https://github.com/DevExpress/testcafe/pull/5210/files#diff-12a80585677e3d3d26721584a3f71774R10))

**Comment by AlexKamaev** [comment]
https://github.com/DevExpress/testcafe/pull/5277

API description:

1. getCurrentWindow(): unknown
2. openWindow(url: string)
3. switchToWindow(window)
4. closeWindow(window?)
    - the `window` parameter is optional. If window is not given the current active window will be closed
    - if we try to close the parent from the child the error message should appear

```JS
test('test', async t => {
    const parent  = await t.getCurrentWindow();
    const window1 = await t.openWindow('/join-chat?id=1');
    const window2 = await t.openWindow('/join-chat?id=1');

    await t
        .switchToWindow(window1)
        .typeText('input', 'hello')
        .switchToWindow(window2)
        .typeText('input', 'world')
        .switchToWindow(parent)
        .closeWindow(window1)
        .closeWindow(window2)
});
```

1. switchToParentWindow()
2. switchToRecentWindow()
    - without history. Only back to previous.
3. switchToWindow(predicate: ({ url: Object, title: string }))
```JS
switchToWindow(w => w.title === 'test title');
switchToWindow(w => w.location.href === 'http://example.com')
switchToWindow(w => w.title === 'Title' && w.location.host === 'example.com')
```
