### ISSUE TITLE
'testcafe' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by kahlan88** [DevExpress/testcafe#5262]
### What is your Test Scenario?
`yarn add testcafe -g`
`testcafe chrome test.ts`
 
### What is the Current behavior?
`'testcafe' is not recognized as an internal or external command,
operable program or batch file.`
 
### What is the Expected behavior?
Tests run.
 
 <details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
import { Selector } from 'testcafe';

fixture `Getting Started`
    .page `http://devexpress.github.io/testcafe/example`;

test('My first test', async t => {
    // Hello
})
```
</details>

### Your Environment details:
 
* testcafe version:                   `^1.8.7`
* node.js version:                    `v10.16.2`
* command-line arguments:  `testcafe chrome test.js` `testcafe`
* other:                                   
* package.json scripts:            `"test": "testcafe chrome tests/",`
`yarn test` runs the tests.

I don't understand. Having followed your getting started, I was expecting to be able to use everything as described.

Issue is similar to [this comment](https://github.com/DevExpress/testcafe/issues/700#issuecomment-237765634), but it's been 4 years so I imagine there were many more releases. 

(I have tried installing with `yarn add -D testcafe@alpha` just to be sure I tried everything, but no luck either.

**Comment by Ogurecher** [comment]
Hello,

Use `yarn global add testcafe` instead of `yarn add testcafe -g` to resolve this issue. See [global](https://classic.yarnpkg.com/en/docs/cli/global) for more information.
