### ISSUE TITLE
Enable resizing multiple Windows

### ISSUE THREAD

**Issue by KouraiBee** [DevExpress/testcafe#5268]
I've been playing around with the new [multiple browsers functionnality](https://github.com/DevExpress/testcafe/pull/5210), and one thing that's missing for me is to resize the new windows. 
I tried 
`	const win1 = await t.openWindow('/bi8o');
	await t.switchToWindow(win1)
                  .resizeWindow(1000, 1000); `

and `	const win1 = await t.openWindow('/bi8o').resizeWindow(1000, 1000);`

and it did only resize the parent windows and not `win1`.
It would be very very very usefull for my project to be able to do so, as for now,  `win1` is way to small, it can't even be used as a mobile windows. 

This functionality could be used directly in a test like i tried, or a flag.
If this functionality is hard to implement, I'd like to be able to define a default size for all new windows at least

**Comment by Ogurecher** [comment]
Hello,
 
Thank you for your inquiry. This feature will be implemented in the context of https://github.com/DevExpress/testcafe/issues/5017. Please use issue #5017 to discuss and track our progress.
