### ISSUE TITLE
Implement touch gestures actions

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#527]
- `t.pullUp`, 
- `t.pullDown`,
- `t.swipeRight`, 
- `t.swipeLeft`.

 Which will gracefully degrade to scrolling on devices without touch support.

**Comment by AlexanderMoskovkin** [comment]
Let's clarify new actions api and it's behavior

```js
t.scroll(selector, offsetOptions); // offsetOptions = { offsetX, offsetY }
//----------------
t.mouseDown(selector, clickOptions); // clickOptions = { modifiers, caretPos, offsetX, offsetY }
//or
t.mouseDown(selector, mouseOptions); // mouseOptions = { modifiers, offsetX, offsetY }
//----------------
t.rightMouseDown(selector, clickOptions);
//----------------
t.mouseUp();
t.rightMouseUp();
//or
t.mouseUp(selector, clickOptions);
t.rightMouseUp(selector, clickOptions);
```

The things to discuss:
1) `t.mouseDown(selector, clickOptions || mouseOptions);`
Should we have the `caretPos` option here like in the `click` command?

 I suppose, yes, because mouseDown leads to the element focusing (and set selection for editable elements)

2) Should `t.mouseUp` have arguments? If no - it's just raise mouse up event on the position where the cursor is placed right now. Or it's should be `t.mouseUp(selector, options)`. In this case if you call 
`t.mouseDown(element1).mouseUp(element2)` - it means 
```js
- mouse down on element1
- move to element2
- mouse up on element2
```
I'm not sure what we should choose here, but I am inclined to choose the first to make action more simple

3) Should we emulate native behavior when a combination of simple actions is used? For example if you call  `t.mouseDown(input1, { /* someOffsets */ }).hover(input1, { /* otherOffsets*/ }.mouseUp())` should we change a selection of the input (in other words - execute it like a select action)?

I suppose, yes

4) Since we have `mouseDown` and `mouseUp` action should not we have `move` or `moveTo` action (how we have `hover`)? (/cc @VasilyStrelyaev)

What do you think, @inikulin @helen-dikareva ?

**Comment by inikulin** [comment]
Let's postpone mouse events discussion for now, since I think they are not quite important and we don't need them in MVP. The more important is `t.scroll` which is often used e.g. in mobile devices. What kind of scroll actions should we have:
`t.scrollDocumenToTop`,`t.scrollDocumenToBottom` or should it have selector? Should we have `t.scrollToElement` version or `t.scroll` with offset?

**Comment by helen-dikareva** [comment]
1) I vote for t.mouseDown(selector, clickOptions);
2) t.mouseUp without arguments
3) i think we should support native behavior for combination of simple actions
4) `move` looks more attractive

**Comment by helen-dikareva** [comment]
I think `t.scrollDocumenToTop,t.scrollDocumenToBottom` insufficiently reusable variants.
I think we should have command `t.scrollToElement` because `t.scroll` looks like we should scroll element itself

**Comment by inikulin** [comment]
> I think t.scrollDocumenToTop,t.scrollDocumenToBottom insufficiently reusable variants.

I don't agree. The most common scenario people asked for is to scroll down the document e.g. to load additional comments/items in live feed.

**Comment by helen-dikareva** [comment]
Let's call it `t.scrollDocument` and send offsets to it

**Comment by inikulin** [comment]
I just thought we don't need scroll action at all. What we need is touch device gestures: `t.swipeUp`, `t.swipeDown`, `t.swipeRight`, `t.swipeLeft`

**Comment by inikulin** [comment]
@AlexanderMoskovkin PivotGrid team expressed a high interest in scrolling gestures. I guess we can plan it for Sprint#2. Before figuring out final API it's worth discuss it with other teams and maybe test prototypes during development with them as well.

**Comment by AlexanderMoskovkin** [comment]
ok, I'll do this

**Comment by Dtphelan1** [comment]
Has this been implemented? I'm running into issues where tests fail because of an overlapping element has a parent who has 'position':'fixed', and one way I could work around this would be to use t.pullDown to the bottom of the page manually, instead of relying on testCafe to find it automatically.

**Comment by AlexanderMoskovkin** [comment]
Hi @Dtphelan1,

It's not implemented yet.

We've discussed such issue in the [#1057](https://github.com/DevExpress/testcafe/issues/1057#issuecomment-328476208) issue. Usually you can use another workaround. Before an action on the target element call the `hover` action for this element with the `offsetY` property, for example:
```js
await t
    .hover('#target', { offsetY: 100 })
    .click('#target');
```

**Comment by AlisarDius** [comment]
Hello guys, 

I'm working with Testcafe API for like a month. I've just encountered the issue that Testcafe cannot click on pagination number at the bottom of our application because the element is in overflow and testcafe shows error that the element is not visible. t.hover doesn't work for me. And t.pressKey('end') also not. I need this scrolling functionality to be implemented. 

Also I noticed that the scrolling acts weird. If I scroll down at the bottom, it immediately jumps back up. Basically I need to spam the scrolling wheel down while Testcafe waits for the element to appear and then it usually works. Therefore, I'm not sure how successful would the t.pullDown action would be, but hopefully it would be enough.

Kinds regards,
Libor

**Comment by talentedunicorn** [comment]
I've been using `ClientFunction` wrapped in a helper function that I import in my tests. The whole snippet looks like this

```js
export const scroll = ClientFunction((x, y) => window.scrollBy(x, y))
```

Which i will letter use like so for vertical scrolling:

```js
test('something that needs to scroll', await t => {
....
await scroll(0, divHeight);
expect(....).ok()
})
```

**Comment by caroe233** [comment]
> Let's postpone mouse events discussion for now, since I think they are not quite important and we don't need them in MVP. The more important is `t.scroll` which is often used e.g. in mobile devices. What kind of scroll actions should we have:
> `t.scrollDocumenToTop`,`t.scrollDocumenToBottom` or should it have selector? Should we have `t.scrollToElement` version or `t.scroll` with offset?

I vote for having selectors. Need to scroll within an element...

**Comment by leegee** [comment]
This is a rather old issue -- has there been any thought or progress on touch selectors?

**Comment by Farfurix** [comment]
@leegee 

Hello,

Thank you for your interest in this enhancement. We will update this thread once we have any news on this.

**Comment by switch201** [comment]
I opened the issue referenced above. Many other automated testing frame works allow for explicit scrolling. On some apps scrolling may cause things to happen on the web page that need to be tested for example.

Also it is sometimes nice to offset the default scrolling behavior of testCafe, so that it scrolls a little more than the minimum required amount. I know that any element that is interacted with is/should be automatically scrolled to, but what is the reservation with giving more power to the user in this regard?

**Comment by AlexKamaev** [comment]
@switch201 
Thanks for your opinion. We greatly appreciate it. This issue is still opened, which means that we are going to extend Actions API in the future, however, we cannot give any estimates.

**Comment by AndreyBelym** [comment]
@hitautodestruct, you can use `t.hover` for scrolling. TestCafe scrolls your page and containers to a point defined by the `offsetX` and `offsetY` options: https://devexpress.github.io/testcafe/documentation/test-api/actions/hover.html

**Comment by hitautodestruct** [comment]
@AndreyBelym Will this scroll to points that are still not existent on the page?
We have a virtual scroller that only renders elements if the container is scrolled.

**Comment by AlexKamaev** [comment]
@hitautodestruct 
If you choose your scroll container as a target of the `hover` action, it should work.
```HTML
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        #wrapper {
            overflow-y: scroll;
            height: 500px;
        }

        #container {
            height: 5000px;
        }
    </style>
</head>
<body>
<div id="wrapper">
    <div id="container">
        <button>Click me
        </button>
    </div>
</div>
</body>
</html>

```
```JS
fixture ``
    .page `../pages/index.html`;

test(`test`, async t => {
    await t.hover('#wrapper', { offsetY: 100 });
    await t.hover('#wrapper', { offsetY: 1000 });
    await t.hover('#wrapper', { offsetY: -1 });
});

```
The last line should scroll the container to the bottom and initiate your virtual loading.

**Comment by LathaSan** [comment]
> Let's clarify new actions api and it's behavior
> 
> ```js
> t.scroll(selector, offsetOptions); // offsetOptions = { offsetX, offsetY }
> //----------------
> t.mouseDown(selector, clickOptions); // clickOptions = { modifiers, caretPos, offsetX, offsetY }
> //or
> t.mouseDown(selector, mouseOptions); // mouseOptions = { modifiers, offsetX, offsetY }
> //----------------
> t.rightMouseDown(selector, clickOptions);
> //----------------
> t.mouseUp();
> t.rightMouseUp();
> //or
> t.mouseUp(selector, clickOptions);
> t.rightMouseUp(selector, clickOptions);
> ```
> 
> The things to discuss:
> 
> 1. `t.mouseDown(selector, clickOptions || mouseOptions);`
>    Should we have the `caretPos` option here like in the `click` command?
> 
> I suppose, yes, because mouseDown leads to the element focusing (and set selection for editable elements)
> 
> 1. Should `t.mouseUp` have arguments? If no - it's just raise mouse up event on the position where the cursor is placed right now. Or it's should be `t.mouseUp(selector, options)`. In this case if you call
>    `t.mouseDown(element1).mouseUp(element2)` - it means
> 
> ```js
> - mouse down on element1
> - move to element2
> - mouse up on element2
> ```
> 
> I'm not sure what we should choose here, but I am inclined to choose the first to make action more simple
> 
> 1. Should we emulate native behavior when a combination of simple actions is used? For example if you call  `t.mouseDown(input1, { /* someOffsets */ }).hover(input1, { /* otherOffsets*/ }.mouseUp())` should we change a selection of the input (in other words - execute it like a select action)?
> 
> I suppose, yes
> 
> 1. Since we have `mouseDown` and `mouseUp` action should not we have `move` or `moveTo` action (how we have `hover`)? (/cc @VasilyStrelyaev)
> 
> What do you think, @inikulin @helen-dikareva ?

Hi @AlexanderMoskovkin,
These mouse events are implemented in testcafe, as I have a requirement to long press a button and swipe left and right options are also needed.

**Comment by arubtsov** [comment]
Hi @LathaSan,

Thank you for sharing your scenario with us. We will take it into account when implementing this feature. If you share an example, we might find a workaround for [https://github.com/DevExpress/testcafe/issues/2054](https://github.com/DevExpress/testcafe/issues/2054).

**Comment by LathaSan** [comment]
> Hi @LathaSan,
> 
> Thank you for sharing your scenario with us. We will take it into account when implementing this feature. If you share an example, we might find a workaround for #2054.

Hi @arubtsov,

I have an icon in footer, I have to long press that icon for 3 to 5 secs, then the filters added will be cleared and footer icon color will be changed. Could you please help me to achieve this.

**Comment by LathaSan** [comment]
> > Hi @LathaSan,
> > Thank you for sharing your scenario with us. We will take it into account when implementing this feature. If you share an example, we might find a workaround for #2054.
> 
> Hi @arubtsov,
> 
> I have an icon in footer, I have to long press that icon for 3 to 5 secs, then the filters added will be cleared and footer icon color will be changed. Could you please help me to achieve this.

Hi @arubtsov,
For touch gestures, we use touchswipe library. In that we use long tap event to stimulate long press action. Demo link is 'http://labs.rampinteractive.co.uk/touchSwipe/demos/Tap_vs_swipe.html'

**Comment by wentwrong** [comment]
@LathaSan, I've already answered this - please see https://github.com/DevExpress/testcafe/issues/2054#issuecomment-790447511

**Comment by miherlosev** [comment]
We decided not to implement this feature. All additional event simulation can be achieved using the [t.dispatchEvent](https://testcafe.io/documentation/403091/reference/test-api/testcontroller/dispatchevent) action.
