### ISSUE TITLE
Cannot set a cookie

### ISSUE THREAD

**Issue by ngrossi** [DevExpress/testcafe#5273]
I have the following code
--
  public async setCookie(): Promise<void> {
  
    const cookie = ClientFunction(() => {
      const date= new Date();
      const name = 'bat-ui-version';
      const value = 'new';
      document.cookie = name+"="+value+"; expires="+date.toUTCString()+"; path=/";
      console.log(chalk.bold.yellow("setting cookie"))
    });
  }
--
and my test
--
public static async loginAndGoToMonitoringNewUI(): Promise<boolean> {

    const username = Credentials.userName
    const password = Credentials.getPasswordForEnvironment(Main.env)

    ConsoleOutput.startedTestGlobal(`Logging in to anypoint platform... (User: ${username})`)
    await anypointLanding.setCookie()
    await t.click(loginPage.userNameInput).typeText(loginPage.userNameInput, username)
    await t.click(loginPage.passwordInput)
    await t.typeText(loginPage.passwordInput, password, {caretPos: 0})
    await t.pressKey('enter')
    await anypointLanding.at()   
    await anypointLanding.goToMonitoring()
    await apitestingPage.at()
    ConsoleOutput.successfulTestGlobal('Logged in')
    return true
  }
----

cookie appears to not be stetted

**Comment by AlexSkorkin** [comment]
Thank you for your interest in our testing tools. You are welcome to ask any TestCafe related questions on StackOverflow (https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions. If you think that you found a bug, feel free to open a new issue in the GitHub repo https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md). Thank you in advance. 

See also: [Injecting cookies in your testcafe automation](https://azevedorafaela.com/2019/07/24/inject-cookies-in-your-testcafe-automation/)
