### ISSUE TITLE
all test files in folder (and parent) are run no matter specific file is provided in command line

### ISSUE THREAD

**Issue by fmancardi** [DevExpress/testcafe#5285]
### What is your Test Scenario?
Have a folder ./test/ with this structure
./test/component01
./test/customer01
./test/development
./test/development/phase1
./test/development/phase2

in each folder different js files with test cases exists.
I want to run the file ./test/development/createKeywords.js

 
### What is the Current behavior?
I use the following command
testcafe chrome --skip-js-errors -s takeOnFails=true --test-meta WKFSTATUS=ready --start-fullscreen  ./test/createKeywords.js

But other test files present in the ./test folder at any depth are run
If I add in the command the --cfg= option everything works as expected.
The command that is ok is:

testcafe chrome --skip-js-errors -s takeOnFails=true --test-meta WKFSTATUS=ready --start-fullscreen **--cfg=mycfg.json** ./test/createKeywords.js
 
### What is the Expected behavior?
Only the specified js file must be run

### Steps to Reproduce:
detailed in section  **What is the Current behavior?**

### Your Environment details:
 
* testcafe version:                   1.8.7
* node.js version:                    v12.9.1
* command-line arguments:  testcafe chrome --skip-js-errors -s takeOnFails=true --test-meta WKFSTATUS=ready --start-fullscreen  ./test/createKeywords.js
* browser name and version:  83.0.4103.116 (Official Build) (64-bit)
* platform and version:          macOS Mojave - Darwin Kernel Version 18.7.0

**Comment by Ogurecher** [comment]
Hello,

Thank you for reporting this issue. We researched your scenario and found the cause of this behavior: `--start-fullscreen` is a browser argument, not a TestCafe CLI argument. Please use the following command:
`testcafe 'chrome --start-fullscreen' --skip-js-errors -s takeOnFails=true --test-meta WKFSTATUS=ready ./test/createKeywords.js`
For more information, refer to [our CLI documentation article](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#start-a-browser-with-arguments).

**Comment by fmancardi** [comment]
my fault, thanks a lot

**Comment by Ogurecher** [comment]
@fmancardi, You're welcome
