### ISSUE TITLE
ERR:EMPTY_RESPONSE for XHR requests on first try

### ISSUE THREAD

**Issue by rovervannispen** [DevExpress/testcafe#5292]
### What is your Test Scenario?
Automation script fills in a form and clicks on submit. After the page has been submitted it'll route to the next page. The script runs an assertion to see if it's being redirected to the next step.
 
### What is the Current behavior?
It clicks the button but doesn't actually send out a request. I get an `ERR:EMPTY_RESPONSE`. I'm using the debugOnFail flag which leaves the test window open. When I unlock the page and click the same button manually it does fire the real request (without failure). I (and my colleagues as well) NEVER get this error when we're doing some manual tests. It only happens when running my tests in Testcafe. The same bug is happening across multiple browsers.

I also tried all the solutions Google gave me for`ERR:EMPTY_RESPONSE` (like flushing DNS) however the same error still persists and it only occurs when running Testcafe. I checked the server access logs and the request isn't in there, somehow it gets blocked.

<img width="1792" alt="Screenshot 2020-07-02 at 14 54 09" src="https://user-images.githubusercontent.com/8696218/86598712-cf7bf700-bf9d-11ea-9653-79cac6e2034a.png">

I've made a really hacky workaround which does work but I don't want to wrap all my assertions with this.

```
await t
    .typeText(PatientModel.bsn, patient.bsn)
    .click(PatientModel.setGender(patient.gender))
    .typeText(PatientModel.initials, patient.initials)
    .typeText(PatientModel.insertion, patient.insertion)
    .typeText(PatientModel.last_name, getTesterLastName())
    .typeText(PatientModel.street, patient.street)
    .typeText(PatientModel.house_nr, patient.house_nr)
    .typeText(PatientModel.house_nr_addition, patient.house_nr_addition)
    .typeText(PatientModel.postal_code, patient.postal_code)
    .typeText(PatientModel.city, patient.city)
    .typeText(PatientModel.tel, patient.tel)
    .typeText(PatientModel.tel2, patient.tel2)
    .click(PatientModel.birthday)
    .click(PatientModel.setBirthday(patient.date_of_birth))
    .click(PatientModel.insurer)
    .click(PatientModel.setInsurer(patient.insurer))
    .typeText(PatientModel.insurance_nr, patient.insurance_nr)
    .typeText(PatientModel.pharmacy_name, patient.pharmacy_name)
    .typeText(PatientModel.pharmacy_city, patient.pharmacy_city)
    .typeText(PatientModel.comments, patient.comments)
    .click(PatientModel.submit);

  const notification = await GeneralModel.notification.innerText;

  if (notification === "Added successfully ") {
    await t
      .expect(getCurrentRoute())
      .contains("/patients")
      .expect(PatientOverview.testUserRow.exists)
      .ok();
  } else {
    // retry once
    await t
      .click(PatientModel.submit) // now it actually does the REAL submit
      .expect(GeneralModel.notification.innerText)
      .contains("Added successfully", { timeout: 6000 });
  }
```

### What is the Expected behavior?
It should click the button and do the request on the first try

### Your Environment details:
 
* testcafe version: 1.8.7
* node.js version: 14.4.0
* command-line arguments: 
```
{
  "browsers": ["chrome --auto-open-devtools-for-tabs"],
  "debugOnFail": true,
  "developmentMode": true,
  "disablePageCaching": true,
  "quarantineMode": false,
  "takeOnFails": true
}
```

* browser name and version: Chrome 83.0.4103.116 / 
* platform and version:          macOS 10.15.5

**Comment by LavrovArtem** [comment]
This information is not sufficient for debugging this issue. Could you please send us a simple example or public page for reproducing and debugging this issue?

P.S. Also, you can enable the server logging by setting the environment variable `DEBUG=hammerhead:*` that shows you the data our proxy sends to your server.

**Comment by Farfurix** [comment]
@rovervannispen 

Hello,

Could you please send us a DevTools screenshot that includes the "Headers" tab of this request without TestCafe?

**Comment by rovervannispen** [comment]
Here you go!
<img width="1229" alt="Screenshot 2020-07-08 at 15 32 47" src="https://user-images.githubusercontent.com/8696218/86925255-e99a0e80-c130-11ea-9e10-7dada7b33aba.png">

**Comment by AlexKamaev** [comment]
@rovervannispen
Thank you for your cooperation. As I see in your messages, with TestCafe, the `Content-Length` header is equal to `502`. However, without TestCafe, this value is `466`.

I assume that data that is sent with TestCafe is different from data sent without TestCafe. Could you please check your posted data in DevTools and make screenshots?

Thank you in advance.

**Comment by rovervannispen** [comment]
Okay so here is the exact same request. The first one is the one that I did manually (without using Testcafe) and the second one is with using Testcafe. They both have exactly the same payload and they're both using the same endpoint.

<img width="1303" alt="Screenshot 2020-07-10 at 18 19 16" src="https://user-images.githubusercontent.com/8696218/87176476-716f4c80-c2da-11ea-90b8-2c3e6c68cac8.png">

<img width="1778" alt="Screenshot 2020-07-10 at 18 21 11" src="https://user-images.githubusercontent.com/8696218/87176509-7fbd6880-c2da-11ea-82c0-9334db81d72f.png">

**Comment by LavrovArtem** [comment]
@rovervannispen,

It's difficult to help you without an example, but I'll try to improve logging to find the cause of the issue. Please, track this issue to stay informed of our updates.

**Comment by LavrovArtem** [comment]
@rovervannispen,

Please install the `1.9.0-alpha.1` version, run your test in debug mode and send us a full log of the failed request.

P.S. All logs of one request are available by the request ID.
```
hammerhead:proxy Proxy request UTpVORCmn ...
                               ^^^^^^^^^
```

**Comment by rovervannispen** [comment]
I updated Testcafe `"testcafe": "^1.9.0-alpha.1"` but don't see any more details. I do still get the same `Error: socket hang up`

In the screenshot below I filtered the logs by request ID
<img width="1783" alt="Screenshot 2020-07-16 at 09 55 00" src="https://user-images.githubusercontent.com/8696218/87643485-3db57c00-c74b-11ea-81fe-80164f86ae8e.png">

**Comment by LavrovArtem** [comment]
It is strange. This version should contain two additional logs with the hammerhead:destination:socket prefix. Could you please check if they are present?

**Comment by rovervannispen** [comment]
Hmm, the `hammerhead:destination:socket` only appears when the request succeeds. I just had a random 200 which showed me the `hammerhead:destination:socket`. I ran the tests a few more times but it fails every time. So when I see a `Destination error WFbZtimQt Error: socket hang up` I don't see the `hammerhead:destination:socket` log statement

**Comment by LavrovArtem** [comment]
[This code](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/request-pipeline/destination-request/index.ts#L84-L90) is executed regardless of the response status code. I've created a sample server (see below) and found that the `hammerhead:destination:socket` log does not appear only if a destination server destroys connection without data. Could you please check your server reply for the request from our proxy?

```js
const net = require('net');

net
    .createServer(connection => { 
        console.log('client connected');

        connection.on('data', data => {
            const url = data.toString().replace(/^(?:GET|POST) ([^\s]*?) HTTP\/1[\s\S]+$/g, '$1');
            
            if (url && url === '/')
                connection.write(`HTTP/1.1 200 Ok\r\nContent-Type: text/html\r\nContent-Length: 53\r\n\r\n<link rel="icon" href="/favicon.ico"><h1>Hello!</h1>\r\n`);
            else
                connection.destroy();
        })
    })
    .listen(2020, () => console.log('Open http://localhost:2020'));
```

**Comment by rovervannispen** [comment]
Because of the socket connection error, it doesn't fire the actual request. I can't see anything on my server. These records are all related to the same `requestId`. Is this enough to debug this?

<img width="1772" alt="Screenshot 2020-07-22 at 14 00 05" src="https://user-images.githubusercontent.com/8696218/88174293-5a0e5880-cc24-11ea-9cd6-5d11777c8875.png">

**Comment by LavrovArtem** [comment]
This information is not sufficient to debug this issue. We are out of any ideas on what's going on. Only a sample app will help us to diagnose and research the issue.

**Comment by rovervannispen** [comment]
We still have some issues testing our POST requests using Testcafe. Since I can’t share the actual codebase, would it make sense to make a video of the test and the related requests/responses? Maybe I can share some snippets in private. We really would like some help 👍

**Comment by Farfurix** [comment]
@rovervannispen

Hello,

Your scenario is quite complex and we need to examine your project locally. Since the project is private you can send us your project (or an URL address with credentials) to our mailbox (support@devexpress.com). Our policy prevents us from accessing a customer’s internal resources without prior written approval from the entity that owns the server/web resource. If you want us to research the problem further, we’ll need access to the server/web resource. Please ask the website owner to send us (support@devexpress.com) a written confirmation. It must permit DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes.
