### ISSUE TITLE
Command to run two or multiple tests with test patterns

### ISSUE THREAD

**Issue by Muthuvenaktesh** [DevExpress/testcafe#5295]
### Are you requesting a feature or reporting a bug?
The below test grep command was working fine with the testcafe version 1.6.0, but with the latest version 1.8.4 it is not working.

testcafe -e -u chrome testcafe/tests -T 'pattern1|pattern2|pattern3'

### What is the Current behavior?

'QA_028' is not recognized as an internal or external command,
operable program or batch file. - getting this error , instead of running two testcases.

### How would you reproduce the current behavior (if this is a bug)?

testcafe -e -u chrome testcafe/tests -T 'pattern1|pattern2|pattern3'

#### Provide the test code and the tested page URL (if applicable)

testcafe chrome *.ts -e -u environment=QA browser=chrome --hostname 127.0.0.1 --selector-timeout 50000 --assertion-timeout 50000 -r spec -T 'QA_029|QA_028'

'QA_028' is not recognized as an internal or external command,
operable program or batch file.

Reference :
https://stackoverflow.com/questions/54351485/command-to-run-two-or-multiple-tests

### Your Environment details:
 
* testcafe version:                    1.8.4
* node.js version:                    10.15.3
* command-line arguments:   testcafe chrome *.ts -e -u environment=QA browser=chrome --hostname 127.0.0.1 --selector-timeout 50000 --assertion-timeout 50000 -r spec -T 'QA_029|QA_028'
* browser name and version: chrome
* platform and version:          Windows
* other:

**Comment by LavrovArtem** [comment]
It seems that the problem is related to the command line which you are using but not to TestCafe. Some of these accept only double quotation marks. You can replace your single quotation marks with double ones. For example, use `testcafe -e -u chrome testcafe/tests -T "pattern1|pattern2|pattern3"`. If this does not resolve the issue, please send us a fully reproducible sample project.

**Comment by Muthuvenaktesh** [comment]
Hi @LavrovArtem , I have even tried with double quotes, still same issue. Please find the attached screen shot.
![Testcafe_Grep_pattern](https://user-images.githubusercontent.com/43955483/86829644-8e164500-c08c-11ea-911f-0f59da3b0604.JPG)

**Comment by Farfurix** [comment]
@Muthuvenaktesh 

Hello,

I checked the double quotation case and it works well:
```
>testcafe "chrome:headless --no-sandbox" *.ts -T "T001|D002"
Using locally installed version of TestCafe.
 Running tests in:
 - Chrome 83.0.4103.116 / Windows 10

 PATTERN_GREP_TEST
test1
 √ T001:As an user Test1


 1 passed (3s)
```

**Comment by Muthuvenaktesh** [comment]
Thanks @Farfurix

**Comment by Farfurix** [comment]
@Muthuvenaktesh 

You are welcome.
