### ISSUE TITLE
Phantom mouse events when using dragToElement (only on SVG elements?)

### ISSUE THREAD

**Issue by fpiesche** [DevExpress/testcafe#5301]
### What is your Test Scenario?
I'm working on testing for a web app for drawing chemical diagrams. The app runs in React and uses a Canvas with an SVG to render the diagram. A test is trying to verify that clicking and dragging between two atoms draws a bond between them.
 
### What is the Current behavior?
The click-and-drag generally works correctly and a bond is drawn, but appears to fire another mouse click event at the very end of the drag, right after letting go. This causes the app to "sprout" another bond with an extra atom off the destination element (which is intended behaviour for just clicking an existing atom).
 
### What is the Expected behavior?
The dragToElement only fires a mouse down event when starting the drag and only a mouse up event when ending the drag.
 
### What is your web application and your TestCafe test code?
The application is currently entirely internal, however I have been able to reproduce similar behaviour on another public chemical diagram sketcher - though here, the app seems to receive a mouse up event immediately after TestCafe starts the drag, causing an extra atom to sprout from the starting element and no bond to be drawn.

Note, when viewing the test being run, that a green highlight ring appears around the "sprouted" atom as the mouse moves towards the target. This only occurs on atoms that have been drawn to the canvas - contrast opening https://www.chemspider.com/StructureSearch.aspx, drawing a single atom, then clicking and dragging away from it and moving the mouse cursor over the "preview" while still holding the mouse down; no highlight ring appears here.
 
<details>
<summary>Your website URL (or attach your complete example):</summary>
(none, local internal project only)
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from "testcafe";

fixture`Sketcher`.page`https://www.chemspider.com/StructureSearch.aspx`;

test("Check for phantom mouse events on SVG ChemSpider sketcher", async (t) => {
  console.log("Select the Ketcher iframe");
  await t.switchToIframe(Selector("#ifKetcher"));

  console.log("Click the Carbon button");
  await t.click(await Selector("#atom_c"));

  console.log("Draw two atoms");
  await t.click(await Selector("#client_area"), { offsetX: 10, offsetY: 10 });
  await t.click(await Selector("#client_area"), { offsetX: 400, offsetY: 400 });

  console.log("Draw a single bond between the two atoms");
  var atom1 = await Selector("text").withExactText("C").nth(0);
  var atom2 = await Selector("text").withExactText("C").nth(1);
  await t.click(await Selector("#bond_single"));
  await t.dragToElement(atom1, atom2, {
    speed: 0.01,
    destinationOffsetX: 8,
    destinationOffsetY: 8,
  });

  var carbon_atoms = await Selector("text").withExactText("C");
  var num_carbons = await carbon_atoms.count;
  await t
    .expect(num_carbons)
    .eql(
      2,
      "A bond has been drawn between the two carbons and no additional carbon atoms created."
    );
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>
(none)
</details>
<details>
<summary>Your complete test report:</summary>

```
[vagrant@vagrant-webdev-centos7 sketcher]$ $(npm bin)/testcafe testcafe-test.js
The "src" option from the configuration file will be ignored.
 Running tests in:
 - Chrome 83.0.4103.116 / Linux 0.0

 Sketcher
Select the Ketcher iframe
Click the Carbon button
Draw two atoms
Draw a single bond between the two atoms
 ✖ Check for phantom mouse events on SVG ChemSpider sketcher (screenshots:
 /home/vagrant/sketcher/sketcher/reports/screenshots/2020-07-08_11-28-21/test-1/Chrome_83.0.4103.116_Linux_0.0/errors/1.png)

   1) AssertionError: A bond has been drawn between the two carbons and no additional carbon atoms created.: expected 3 to deeply equal 2

      Browser: Chrome 83.0.4103.116 / Linux 0.0
      Screenshot: /home/vagrant/sketcher/sketcher/reports/screenshots/2020-07-08_11-28-21/test-1/Chrome_83.0.4103.116_Linux_0.0/errors/1.png

         25 |
         26 |  var carbon_atoms = await Selector("text").withExactText("C");
         27 |  var num_carbons = await carbon_atoms.count;
         28 |  await t
         29 |    .expect(num_carbons)
       > 30 |    .eql(
         31 |      2,
         32 |      "A bond has been drawn between the two carbons and no additional carbon atoms created."
         33 |    );
         34 |});
         35 |

         at <anonymous> (/home/vagrant/sketcher/sketcher/testcafe-test.js:30:6)



 1/1 failed (17s)
```
</details>

<details>
<summary>Screenshots:</summary>

Here is a gif recording of the problem on our internal app:
![2020-07-08 12 03 41](https://user-images.githubusercontent.com/393620/86911488-543c5180-c113-11ea-8db8-d989ea91d78b.gif)
</details>

### Steps to Reproduce:
Run the example test.
 
### Your Environment details:
 
* testcafe version:                   1.8.5
* node.js version:                    12.16.1
* command-line arguments:  `testcafe firefox,chrome test.js`
* browser name and version: Chrome 83, Firefox 68
* platform and version:          Observed on Ubuntu 18.04.4, CentOS 7.8
* other: The problem as it manifests on our internal app seems identical to https://github.com/DevExpress/testcafe/issues/1516.

**Comment by fpiesche** [comment]
Note that these phantom click events do not seem to occur on regular HTML elements - I initially tried to write an example using just images on google.com but they do not cause the problem. However, both our internal app and the ChemSpider sketcher which are built around SVG elements seem to exhibit similar (though not identical) issues with dragToElement. Could this be related to how SVGs work in the DOM?

**Comment by Ogurecher** [comment]
Hello,

Thank you for reporting this issue. We've managed to reproduce the outlined behavior using the test you shared. However, in this specific example, the issue is not related to TestCafe. The [page](https://www.chemspider.com/StructureSearch.aspx) illustrated the same behavior without TestCafe: if the element is placed along the left edge of the iframe, it can't sprout a bond to another element. The test passes if the first element's position is changed to `{ offsetX: 100, offsetY: 100 }`.

We would greatly appreciate it if you shared another example to demonstrate the issue.

**Comment by fpiesche** [comment]
I'll spend some time in the very near future to try and help you with access to our internal app - might need a few days though.
