### ISSUE TITLE
 Tests do not run in Microsoft Edge 16.16299

### ISSUE THREAD

**Issue by vitalykorneev** [DevExpress/testcafe#5302]
### What is your Test Scenario?
Form submission on this page http://devexpress.github.io/testcafe/example
 
### What is the Current behavior?
1. Running tests in Microsoft Edge 16.16299 / Windows 10
2. Testing page opens  
3. No value is set in the text field
4. In the developer tools I see an error: `Object doesn't support property or method 'postMessage'`
 
### What is the Expected behavior?
Text typed and submit button is clicked

### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

http://devexpress.github.io/testcafe/example
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
import { Selector } from 'testcafe';

fixture `Getting Started`
    .page `http://devexpress.github.io/testcafe/example`;

test('My first test', async t => {
    await t
        .typeText('#developer-name', 'John Smith')
        .click('#submit-button');
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```
> testcafe edge tests --hostname localhost
 Running tests in:
 - Microsoft Edge 16.16299 / Windows 10
 Getting Started
(node:6632) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
ERROR The Microsoft Edge 16.16299 / Windows 10 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.
Type "testcafe -h" for help.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@1.0.0 test:edge: `testcafe edge tests --hostname localhost`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@1.0.0 test:edge script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Vitaly\AppData\Roaming\npm-cache\_logs\2020-07-08T11_14_07_593Z-debug.log


```
</details>

<details>
<summary>Screenshots:</summary>

Browser
<img width="513" alt="Screenshot 2020-07-08 at 14 12 38" src="https://user-images.githubusercontent.com/13301591/86914818-9c666e80-c129-11ea-8a0a-b438d89f463f.png">

Node.js command prompt
<img width="505" alt="Screenshot 2020-07-08 at 14 23 40" src="https://user-images.githubusercontent.com/13301591/86914897-bacc6a00-c129-11ea-9398-d90138a2dc64.png">
</details>

### Steps to Reproduce:

1. Run tests from [tutorial](https://devexpress.github.io/testcafe/documentation/getting-started/#performing-actions-on-the-page) in Microsoft Edge 16.16299
2. See the error `Object doesn't support property or method 'postMessage'` in the developer tools 
 
### Your Environment details:
 
* testcafe version:                   1.8.8
* node.js version:                    12.18.2
* command-line arguments:  testcafe edge tests --hostname localhost
* browser name and version: Microsoft Edge 41.16299.15.0 / Microsoft EdgeHTML 16.16299
* platform and version:          Windows 10 Pro, 1709

**Comment by AlexKamaev** [comment]
Hello, thank you for your input.
I checked your scenario on BrowserStack with Edge 16 and it does not work as expected. However, I see that version 18 works well. TestCafe supports the latest version of each browser ([https://devexpress.github.io/testcafe/documentation/guides/concepts/browsers.html#officially-supported-browsers](https://devexpress.github.io/testcafe/documentation/guides/concepts/browsers.html#officially-supported-browsers))

I would recommend you update your Edge version. Or, if it's possible, you can install the new Edge based on Chromium.
