### ISSUE TITLE
Testcafe times out waiting for page resource

### ISSUE THREAD

**Issue by Holger2233** [DevExpress/testcafe#5309]
I raised this issue in Stackoverflow already, but so far it does not look like somebody is able to provide an answer, so I am also raising it here.
We have a set of Testcafe tests for our login page and recently found that the tests failed to run in our internal test environments. Testcafe would start and load the start page defined with the fixture or within the test, but instead of proceeding with the test execution just keep continuously reloading without any error. After enabling debug mode, I found this message repeatedly logged in Testcafe:
{
    cmd: 'wait-for-file-download',
    sessionId: '0X_DqYtz0'
}
We have meanwhile isolated the root cause as a script in the page source that is being blocked by the Content Security Policy and after removing it, the tests are running correctly again. 
However I am concerned by the way Testcafe handled this issue by just constantly and silently polling for the resource and possibly eventually timing out. Is there a way to make Testcafe either fail or ignore these issues, so that the test would run provided no functionality is affected?

**Comment by Holger2233** [comment]
Note that this behaviour as observed with Testcafe versions 1.8.6 and 1.8.8 across all browser (Chrome, Firefox, Edge) on Windows 10.

**Comment by alexey-lin** [comment]
Do I understand you correctly that a page (or some resource on it) couldn't be loaded in your case? 

How would you suggest that TestCafe processes this situation? Page loading can fail due to a poor network connection, for example. That's why TestCafe tries to reload a resource several times. It doesn't look a viable option to me to ignore these errors, because TestCafe doesn't know how this resource is used and how it can influence the operation.

**Comment by Holger2233** [comment]
Yes you are right, that is my understanding too and I appreciate that handling this is not straight forward. My problem here is that Testcafe does neither fail, nor report any issue unless in debug mode, nor time out within a reasonable time, until I manually killed it. 
On a side note, the resource in question is just some sort of tracker and not relevant for the functionality provided by the page, which is why the issue would pass undetected by manual testing and other test tools.
 
It is good that thanks Testcafe we caught these CSP violations, but only because we were triggering the tests manually while observing the results, and only after some extensive investigation. However, if the tests were integrated in our CI/CD pipeline and run automatically on deploy I an concerned that the test would just poll for an extended time (or maybe forever), until somebody manually steps in to cancel the deploy and investigates, which again is hard without and logging on this issue.

What would be great is to have the option to fail a test after waiting for a resource for an specific  time to help catch issues like this.

**Comment by Dmitry-Ostashev** [comment]
@Holger2233 The described situation looks unclear. Could you please share with us a simple project with test data to reproduce this behavior? We need to research it more deeply to make a decision on how to improve this behavior.

**Comment by Holger2233** [comment]
The resource in question is a script injected into the page source by Akamai for website performance tracking via mPulse. For details see 
https://www.akamai.com/us/en/products/performance/mpulse-real-user-monitoring.jsp
https://developer.akamai.com/tools/boomerang#implementation
https://developer.akamai.com/tools/boomerang#content-security-policy-(csp)

The offending script in the page source looks like this:
```
<script>(window.BOOMR_mq=window.BOOMR_mq||[]).push(["addVar",{"rua.upush":"false","rua.cpush":"false","rua.upre":"false","rua.cpre":"false","rua.uprl":"false","rua.cprl":"false","rua.cprf":"false","rua.trans":"","rua.cook":"false","rua.ims":"false","rua.ufprl":"false","rua.cfprl":"false"}]);</script>
<script>!function(a){var e="https://s.go-mpulse.net/boomerang/",t="addEventListener";if(""=="True")a.BOOMR_config=a.BOOMR_config||{},a.BOOMR_config.PageParams=a.BOOMR_config.PageParams||{},a.BOOMR_config.PageParams.pci=!0,e="https://s2.go-mpulse.net/boomerang/";if(window.BOOMR_API_key="RWE6L-7NAYR-8UP7S-5F2GR-HGQUL",function(){function n(e){a.BOOMR_onload=e&&e.timeStamp||(new Date).getTime()}if(!a.BOOMR||!a.BOOMR.version&&!a.BOOMR.snippetExecuted){a.BOOMR=a.BOOMR||{},a.BOOMR.snippetExecuted=!0;var i,o,_,r=document.createElement("iframe");if(a[t])a[t]("load",n,!1);else if(a.attachEvent)a.attachEvent("onload",n);r.src="javascript:void(0)",r.title="",r.role="presentation",(r.frameElement||r).style.cssText="width:0;height:0;border:0;display:none;",_=document.getElementsByTagName("script")[0],_.parentNode.insertBefore(r,_);try{o=r.contentWindow.document}catch(O){i=document.domain,r.src="javascript:var d=document.open();d.domain='"+i+"';void(0);",o=r.contentWindow.document}o.open()._l=function(){var a=this.createElement("script");if(i)this.domain=i;a.id="boomr-if-as",a.src=e+"RWE6L-7NAYR-8UP7S-5F2GR-HGQUL",BOOMR_lstart=(new Date).getTime(),this.body.appendChild(a)},o.write("<bo"+'dy onload="document._l();">'),o.close()}}(),"".length>0)if(a&&"performance"in a&&a.performance&&"function"==typeof a.performance.setResourceTimingBufferSize)a.performance.setResourceTimingBufferSize();!function(){if(BOOMR=a.BOOMR||{},BOOMR.plugins=BOOMR.plugins||{},!BOOMR.plugins.AK){var e=""=="true"?1:0,t="",n="dnx7kxaxz3zswxygjfza-f-9d3a76701-clientnsv4-s.akamaihd.net",i={"ak.v":"27","ak.cp":"572978","ak.ai":parseInt("435445",10),"ak.ol":"0","ak.cr":74,"ak.ipv":4,"ak.proto":"h2","ak.rid":"69c5c7f","ak.r":29822,"ak.a2":e,"ak.m":"a","ak.n":"essl","ak.bpcip":"27.111.245.0","ak.cport":63821,"ak.gh":"23.206.243.39","ak.quicv":"","ak.tlsv":"tls1.3","ak.0rtt":"","ak.csrc":"-","ak.acc":"","ak.t":"1594247538","ak.ak":"hOBiQwZUYzCg5VSAfCLimQ==f4HDRj5ZjjYqaDhI9y1QvxrZicDYJsS0ykLn97BchdOJPxduOyQJADw1OKcgailW9VWYUTi2n+CIm/6a4UsrWhAdQxnXfpsgCWX32mrr0HxcTFjzjWHymAtjedVSrd1ZQZZVe85u+Jf+CmoxsbE22542gsI3kGD1UvcyZicTiMBJhi8Wflx0iTBCoeWswJZ77QH8roVsfwX3EllgGc9r+htM+Oix+sUBWVVy/EmerEkXnqJh+RhwB+2qe3URx4vzrpnGe/Zl7R+hfGO5UWhA75gYduWSu4+Ak0FIPJIgRDgWZovPZKBBBIl4rpr1VEksfAv5ZAY6+pvWsdXtSl+RFGXRn12B+n3Rnz8zhRyPBUGj+HI1RRFKjIDU5K1aqDebnO4h8XQTwAuHkU04ezUV0LVycjRUPKaB667qJiW9+Hg=","ak.pv":"148"};if(""!==t)i["ak.ruds"]=t;var o={i:!1,av:function(e){var t="http.initiator";if(e&&(!e[t]||"spa_hard"===e[t]))i["ak.feo"]=void 0!==a.aFeoApplied?1:0,BOOMR.addVar(i)},rv:function(){var a=["ak.bpcip","ak.cport","ak.cr","ak.csrc","ak.gh","ak.ipv","ak.m","ak.n","ak.ol","ak.proto","ak.quicv","ak.tlsv","ak.0rtt","ak.r","ak.acc","ak.t"];BOOMR.removeVar(a)}};BOOMR.plugins.AK={akVars:i,akDNSPreFetchDomain:n,init:function(){if(!o.i){var a=BOOMR.subscribe;a("before_beacon",o.av,null,null),a("onbeacon",o.rv,null,null),o.i=!0}return this},is_complete:function(){return!0}}}}()}(window);</script></head>
```
and triggers this error in the browser console:
![image](https://user-images.githubusercontent.com/25468236/87361422-4d548980-c5c0-11ea-940d-54e210a9ba4e.png)

I hope this information will help you with your investigation.

**Comment by Farfurix** [comment]
@Holger2233 

I wasn't able to reproduce the "Refused to execute inline script..." issue. In my attempt I added the code above to the blank body page:
```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<script>(window.BOOMR_mq=window.BOOMR_mq||[]).push(["addVar",{"rua.upush":"false","rua.cpush":"false","rua.upre":"false","rua.cpre":"false","rua.uprl":"false","rua.cprl":"false","rua.cprf":"false","rua.trans":"","rua.cook":"false","rua.ims":"false","rua.ufprl":"false","rua.cfprl":"false"}]);</script>
<script>!function(a){var e="https://s.go-mpulse.net/boomerang/",t="addEventListener";if(""=="True")a.BOOMR_config=a.BOOMR_config||{},a.BOOMR_config.PageParams=a.BOOMR_config.PageParams||{},a.BOOMR_config.PageParams.pci=!0,e="https://s2.go-mpulse.net/boomerang/";if(window.BOOMR_API_key="RWE6L-7NAYR-8UP7S-5F2GR-HGQUL",function(){function n(e){a.BOOMR_onload=e&&e.timeStamp||(new Date).getTime()}if(!a.BOOMR||!a.BOOMR.version&&!a.BOOMR.snippetExecuted){a.BOOMR=a.BOOMR||{},a.BOOMR.snippetExecuted=!0;var i,o,_,r=document.createElement("iframe");if(a[t])a[t]("load",n,!1);else if(a.attachEvent)a.attachEvent("onload",n);r.src="javascript:void(0)",r.title="",r.role="presentation",(r.frameElement||r).style.cssText="width:0;height:0;border:0;display:none;",_=document.getElementsByTagName("script")[0],_.parentNode.insertBefore(r,_);try{o=r.contentWindow.document}catch(O){i=document.domain,r.src="javascript:var d=document.open();d.domain='"+i+"';void(0);",o=r.contentWindow.document}o.open()._l=function(){var a=this.createElement("script");if(i)this.domain=i;a.id="boomr-if-as",a.src=e+"RWE6L-7NAYR-8UP7S-5F2GR-HGQUL",BOOMR_lstart=(new Date).getTime(),this.body.appendChild(a)},o.write("<bo"+'dy onload="document._l();">'),o.close()}}(),"".length>0)if(a&&"performance"in a&&a.performance&&"function"==typeof a.performance.setResourceTimingBufferSize)a.performance.setResourceTimingBufferSize();!function(){if(BOOMR=a.BOOMR||{},BOOMR.plugins=BOOMR.plugins||{},!BOOMR.plugins.AK){var e=""=="true"?1:0,t="",n="dnx7kxaxz3zswxygjfza-f-9d3a76701-clientnsv4-s.akamaihd.net",i={"ak.v":"27","ak.cp":"572978","ak.ai":parseInt("435445",10),"ak.ol":"0","ak.cr":74,"ak.ipv":4,"ak.proto":"h2","ak.rid":"69c5c7f","ak.r":29822,"ak.a2":e,"ak.m":"a","ak.n":"essl","ak.bpcip":"27.111.245.0","ak.cport":63821,"ak.gh":"23.206.243.39","ak.quicv":"","ak.tlsv":"tls1.3","ak.0rtt":"","ak.csrc":"-","ak.acc":"","ak.t":"1594247538","ak.ak":"hOBiQwZUYzCg5VSAfCLimQ==f4HDRj5ZjjYqaDhI9y1QvxrZicDYJsS0ykLn97BchdOJPxduOyQJADw1OKcgailW9VWYUTi2n+CIm/6a4UsrWhAdQxnXfpsgCWX32mrr0HxcTFjzjWHymAtjedVSrd1ZQZZVe85u+Jf+CmoxsbE22542gsI3kGD1UvcyZicTiMBJhi8Wflx0iTBCoeWswJZ77QH8roVsfwX3EllgGc9r+htM+Oix+sUBWVVy/EmerEkXnqJh+RhwB+2qe3URx4vzrpnGe/Zl7R+hfGO5UWhA75gYduWSu4+Ak0FIPJIgRDgWZovPZKBBBIl4rpr1VEksfAv5ZAY6+pvWsdXtSl+RFGXRn12B+n3Rnz8zhRyPBUGj+HI1RRFKjIDU5K1aqDebnO4h8XQTwAuHkU04ezUV0LVycjRUPKaB667qJiW9+Hg=","ak.pv":"148"};if(""!==t)i["ak.ruds"]=t;var o={i:!1,av:function(e){var t="http.initiator";if(e&&(!e[t]||"spa_hard"===e[t]))i["ak.feo"]=void 0!==a.aFeoApplied?1:0,BOOMR.addVar(i)},rv:function(){var a=["ak.bpcip","ak.cport","ak.cr","ak.csrc","ak.gh","ak.ipv","ak.m","ak.n","ak.ol","ak.proto","ak.quicv","ak.tlsv","ak.0rtt","ak.r","ak.acc","ak.t"];BOOMR.removeVar(a)}};BOOMR.plugins.AK={akVars:i,akDNSPreFetchDomain:n,init:function(){if(!o.i){var a=BOOMR.subscribe;a("before_beacon",o.av,null,null),a("onbeacon",o.rv,null,null),o.i=!0}return this},is_complete:function(){return!0}}}}()}(window);</script></head>
</body>
</html>
```
**test.js**
```js
import { Selector } from 'testcafe';

fixture `Fixture`;

test
    .page('localhost:8080')('test', async t => {
       await t
           .debug()
           .expect(true).ok();
});
```
Could you please share a simple project with us? We'll examine it and check for a suitable solution.

**Comment by Holger2233** [comment]
We tried to set up a small project for you to reproduce  the issue, but sadly it did not work, i.e. we were not able to reproduce it ourselves. So even though rolling back the change that introduced the script eventually fixed the issue with Testcafe. So for now we will keep investigating.

**Comment by Farfurix** [comment]
@Holger2233

Hello,

> eventually fixed the issue with Testcafe

Do you have any "Refused to execute inline script..." errors on the website at the moment?

**Comment by Holger2233** [comment]
Hello,
I can see such an error in some of our environments, but none of them has the effect on Testcafe as the one we identified and subsequently rolled back. Something must be different and special about that particular resource, but right now I am unable to replicate the problem anywhere myself or provide you with any more information. 
However, some of our developers are still investigating and trying to fix the issue on the application/server side and I will share any new information on this with you asap.

**Comment by Farfurix** [comment]
@Holger2233

OK, we'll wait for your update.
