### ISSUE TITLE
Unable to establish one or more of the specified browser connections / Ubuntu / Firefox Headless

### ISSUE THREAD

**Issue by doverradio** [DevExpress/testcafe#5314]
https://stackoverflow.com/questions/62884969/unable-to-establish-one-or-more-of-the-specified-browser-connections-ubuntu

My setup:
OS: Ubuntu 18
Testcafe Version: 1.8.8
Browser: Firefox

I have several Ubuntu servers which had Testcafe working.  Then I had to reinstall the servers entirely for a security reason. After reinstalling Ubuntu and setting up Testcafe freshly, Testcafe no longer works properly.  
Before:
1. Issue command: `sudo testcafe test.js`
2. Expected behavior: After a moment, I could visibly see in the logs that the test was running using Firefox headless.

Now:
1. Issue command: `sudo testcafe test.js`
2. Unexpected behavior: After a moment, I get this in console:
```
Using locally installed version of TestCafe.
ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
```

Here is the .testcaferc.json I am using:
```
{
    "browsers": ["firefox:headless"],
        "speed": 0.1,
        "skipJsErrors" : true,
        "pageLoadTimeout": 5000
}
```

When I run `testcafe --list-browsers`, I get:
`firefox`

My test file:
```
import { ClientFunction, Selector } from 'testcafe';

fixture `triage`
    .page('https://www.google.com/');

test(`test debugging`, async t => {

await t
    .wait(5000)
        console.log(`I did it!`)

})
```

Please let me know what I am doing wrong as this identical setup works on Windows 10.  Previously there was no issue whatsoever.  Only after reinstalling the server and re-setting up everything (in the way I thought was identical to the previous working version) did it begin to fail.  I have actually 5 servers like this and really need a fix.  Any ideas why this is happening?

I even installed chrome.  Same issue!  Failure to establish a connection to chrome too.

**Comment by Farfurix** [comment]
@doverradio 

Hello,

I wasn't able to reproduce the issue under Ubuntu 18.04.4 LTS / Node.js v12.18.2:
![Capture](https://user-images.githubusercontent.com/30019338/87431117-dbdfff80-c5ee-11ea-9cb3-49ef59c08994.PNG)

Could you please clarify the following:
1. Your Node.js and Ubuntu versions.
2. Is it possible to run this test under Chrome or headless Firefox in your Ubuntu environment?

**Comment by AndreyBelym** [comment]
Likely you missed some dependencies after reinstalling your OS. To help us detect missing dependencies, please run the following commands and share their output:

1. ``ldd `which firefox` ``
2. `firefox -headless`

**Comment by doverradio** [comment]
Thanks so much for the response.

@Andrey
The second command with result:
$ ldd `which firefox`
       * not a dynamic executable*

and the second command with result:
firefox -headless
**** You are running in headless mode.*

@Vladimir

Your Node.js and Ubuntu versions.
>*v12.18.2*
>*Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-106-generic x86_64)*

Is it possible to run this test under Chrome or headless Firefox in your
Ubuntu environment?
Tests don't work for either browser and I have both installed.

**Comment by doverradio** [comment]
Hello, 

I have rebuilt a droplet and [recorded a short video (under 3 minutes](https://youtu.be/qHMD1jbnaPU)) clearly demonstrating my issue.  If you have any issue seeing the video, I can email you the MP4.

**Comment by Ogurecher** [comment]
Hello,

Thank you for the video.

Please try running `npm install` and `testcafe` without `sudo`.

If that does not work, install `testcafe` locally and run it with `npx testcafe` or `./node_modules/testcafe/bin/testcafe.js`.

**Comment by doverradio** [comment]
Hello,

I attempted the suggested solutions and made [another short video demonstrating this (2 minutes)](https://youtu.be/kmaYlBzT2Fg). Tho it works on a local machine (Windows 10), still it did not work on Ubuntu. I do all the Ubuntu via ssh 100% which means no GUI and so I must do headless.  I am still unable to get Testcafe working, as the video shows.

**Comment by wentwrong** [comment]
Thank you for your videos. In the second video I noticed that the owner of the `doesTestCafeWork` directory is `root`. This leads to permission problems when packages are installed. To avoid them, remove the directory and create a new one from the user account (or just change the folder ownership).
It is not recommended to work with npm from sudo.

To find a solution for you, we need more information from the browser output. Run this command step by step:

```
export CI=1
npm i testcafe@1.8.8-alpha.2
testcafe remote test.js &
firefox -headless [INSERT YOUR CONNECT_URL]
```

1. Set a CI environment variable to disable the load of spin animation in stdout.
2. Install the latest alpha version of TestCafe (it's the required part (!) because it allows running in remote mode on systems without the GUI).
3. Run TestCafe tests in [remote mode](https://devexpress.github.io/testcafe/documentation/recipes/basics/test-on-remote-computers-and-mobile-devices.html) in background (via an ampersand (&) symbol). It'll show the following message:

```
Connecting 1 remote browser(s)...
Navigate to the following URL from each remote browser.
Connect URL: http://192.168.43.81:43111/browser/connect
```

4. Run Firefox in headless mode and navigate to the connection URL mentioned in the message above.


Share the Firefox logs with us.

Also, specify the Firefox version installed on your system:

```
firefox -v
```

**Comment by doverradio** [comment]
Hello, 

I came back to post that I got one of my servers back and then saw your post.  I will share the logs but let me first explain what I did differently.  

Previous install steps:
1. Install Ubuntu
2. Login as root
3. Create new user
4. Login to new user accout
5. Install Node.js as sudo in new user account
6. Install Firefox as sudo in new user account
7. Install Testcafe as sudo in new user account
8. Setup git clone of express...

After days of looking at this I thought wait _Unable to establish one or more of the specified browser connections_ may just mean _Can't see the browser due to being installed as sudo in a user account thus unable to establish that browser connection..._ (like it can't see it for some reason).  
To test this theory, I rearranged the install steps and suddenly everything worked!  
Here are the steps that solved this issue just now:
1. Install Ubuntu
2. Login as root
3. Install Node.js AS ROOT
4. Install Firefox AS ROOT
5. Install Testcafe AS ROOT (this allows you to do `npm i -g testcafe` )
6. Create new user
7. Login to new user account
8. Setup git clone of express...

Now all my requests are triggering the tests as before.  Thank GOD!  

I will respond back on the items you requested.
