### ISSUE TITLE
TestCafe freeze issue - Page won't close after the test run.

### ISSUE THREAD

**Issue by sijosyn** [DevExpress/testcafe#5315]
### What is your Test Scenario?

A simple request to the 'http://uat-net.technoratimedia.com/ping' causes TestCafe to freeze and page won't close after test run.
 
### What is the Current behavior?

TestCafe freezes and page won't close. 
 
### What is the Expected behavior?

Page shows 'Pong' on page which means success. TestCafe should close the page after the test run.
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 fixture `Connection Test`;

test.page('http://uat-net.technoratimedia.com/ping')('Ping', async t => {
});

```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Run provided test code.
 
### Your Environment details:
 
* testcafe version:                    1.8.8
* node.js version:                     12.13.1
* command-line arguments:   testcafe chrome test.js
* browser name and version:  Chrome 83.0.4103.116
* platform and version:           macOS 10.14.6
* other:

**Comment by Farfurix** [comment]
@sijosyn

Hello,

I reproduced the issue under Chrome 83.0.4103.116 / Windows 10 / Node.js v12.18.1. Our team will examine it and check for a suitable solution.

**Comment by Farfurix** [comment]
@sijosyn 

The same issue was discussed here: https://github.com/DevExpress/testcafe/issues/1471.

Your page content type is `'text/plain'`:
![Capture](https://user-images.githubusercontent.com/30019338/87444316-51ec6280-c5ff-11ea-956d-5c8d73aef1f2.PNG)

A simple example to reproduce:
**server.js**
```js
const http = require('http');

const requestListener = function (req, res) {
    res.writeHead(200, {
        'Content-Type': 'text/plain'
    });
    res.end('Hello, World!');
}

const server = http.createServer(requestListener);
server.listen(8081);
```
**test.js**
```js
fixture `Fixture`;

test
    .page('localhost:8081')('test', async t => {
        await t
            .expect(true).ok();
    });
```
