### ISSUE TITLE
Remove unused field `xhrBarrier.passed`

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#532]

**Comment by AlexanderMoskovkin** [comment]
https://github.com/DevExpress/testcafe/blob/master/src/client/core/xhr-barrier.js#L23

**Comment by miherlosev** [comment]
Also remove the `xhrBarrier._removeXhrFromQueue` method.
https://github.com/DevExpress/testcafe/blob/master/src/client/core/xhr-barrier.js#L49
