### ISSUE TITLE
Window size does not reset between tests or fixtures

### ISSUE THREAD

**Issue by ChrisLane** [DevExpress/testcafe#5324]
### What is the Current behavior?
`resizeWindow()` changes the window size for the text it is executed in and all following tests, including those in different fixtures. 
 
### What is the Expected behavior?
I would expect the window size to reset after every test, if not at least after every fixture.
 
### What is your web application and your TestCafe test code?
Not project specific.

### Steps to Reproduce:
1. Write some tests
1. Make an early running test change the window size
1. Note that all subsequent tests are affected by the window size remaining
 
### Your Environment details:
 
* testcafe version:                   1.8.8
* node.js version:                    v14.5.0
* command-line arguments:   `testcafe chromium testcafe/*`
* browser name and version:  Chromium 84.0.4147.89
* platform and version:           Arch Linux 5.7.8

**Comment by Ogurecher** [comment]
Hello,

Thank you for your report. This behavior is expected. TestCafe does not restore a browser window's original size between tests or fixtures.

If you want to reset the window to its original size between tests, you can use `resizeWindow` in [beforeEach](https://devexpress.github.io/testcafe/documentation/reference/test-api/fixture/beforeeach.html) or [afterEach](https://devexpress.github.io/testcafe/documentation/reference/test-api/fixture/aftereach.html) hooks.

**Comment by ChrisLane** [comment]
I would think that you'd want to make the default for tests to have the highest likelihood of having the same outcome no matter the order that they're running in.

Thanks for the quick response. I'll just add `maximiseWindow()` to the end of any tests where I change the window size.
