### ISSUE TITLE
New window's id matches its parent's id if it's opened in a specific way

### ISSUE THREAD

**Issue by Ogurecher** [DevExpress/testcafe#5325]
## Description
https://github.com/DevExpress/testcafe/issues/912#issuecomment-653123581

## Example project
https://github.com/DevExpress/testcafe/issues/912#issuecomment-658356160
Instructions are inside the example repo.

**NOTE:** in `package.json` change `ng` to `npx ng` in the `start` script

**Comment by anjali-amle** [comment]
If new window is opening in another tab in same browser window. both, parent and new window same same id and its throwing the below error.

TypeError: Cannot read property '0' of null

**Comment by viktoria2506** [comment]
Thank you for the information. We will take it into account.
