### ISSUE TITLE
When click on an url within the iframe and after the new page loaded the test stop from there without any error message. 

### ISSUE THREAD

**Issue by wchangGuidewire** [DevExpress/testcafe#5327]
Hi team,

I am currently facing an issue when try to process my test within iframe.
The situation is that I have an e-sign iframe within my application. There are a few documents need to be signed, and after signing all documents the page will move on to next step by returning a response. I am able to click on the first document, but after I click the link, the document loaded in the iframe the test just stop from there without any error message. I'm not sure if this is a bug or the framework not supporting this kind of feature. Would be really appreciate if there is an workaround for this.

### What is your Test Scenario?
Switch to iframe then click on first document and sign the document.
 
### What is the Current behavior?
Test stop after document loaded.
 
### What is the Expected behavior?
Able to move forward to the following test.
 
### What is your web application and your TestCafe test code?
It's company application so appologize that I am not able to provide the link for it. But the page is like below.

 
### Your Environment details:
 
* testcafe version: 1.8.7
* node.js version: 6.3.1
* command-line arguments:  testcafe chrome
* browser name and version: Chrome 
* platform and version:          Windows

**Comment by Ogurecher** [comment]
Hello,

Thank you for your report. The information you shared isn't sufficient to reproduce the issue.
Please share an example page that demonstrates it. With it, we'll be able to determine the cause of the issue.

**Comment by wchangGuidewire** [comment]
Sorry I'm afraid I'm not able to provide the page. I try using navigateTo but I found out the promise never return so the test stop there. Is there anyway to force navigateTo  promise timeout after a certain of time? Thanks!

**Comment by LavrovArtem** [comment]
@wchangGuidewire,

The information you shared is insufficient to determine the cause of the issue. We need a simple example or a public page that demonstrates the incorrect behavior.
