### ISSUE TITLE
SendKeys (Selenium) to thirdparty iframe works fine in Safari 12.1 on Mac but doesn't work on Iphone, iOS 13.2. 

### ISSUE THREAD

**Issue by Mmallineni** [DevExpress/testcafe#5330]
#### HEADS UP!

For TestCafe API, usage and configuration inquiries, we recommend [StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)).

You may also find answers in our up-to-date [documentation](https://devexpress.github.io/testcafe/documentation/getting-started/) and [answered questions](https://stackoverflow.com/questions/tagged/testcafe) on StackOverflow. This may save your time.

If you have already looked there and have not found an appropriate answer, [file a new question on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe).

**Comment by alexey-lin** [comment]
TestCafe is not Selenium, it's entirely different product, so we cannot help you with this issue. I suggest you [search the answer](https://stackoverflow.com/questions/tagged/selenium) on StackOverflow or [ask a new question](https://stackoverflow.com/questions/ask?tags=selenium) there.
