### ISSUE TITLE
How to subscribe to TestCafe Blog https://devexpress.github.io/testcafe/media/team-blog/

### ISSUE THREAD

**Issue by harry7771** [DevExpress/testcafe#5333]
Sorry....really wasn't sure how/where else to ask this question:  How can I subscribe to the TestCafe team blog (https://devexpress.github.io/testcafe/media/team-blog/)?  I just want to receive notifications when there are new blog entries.  Thank you.

**Comment by alexey-lin** [comment]
Hi @harry7771,

Thank you for your interest in our blog. You can subscribe to its [RSS feed](https://devexpress.github.io/testcafe/feed.xml). You can also follow us on [Twitter](https://twitter.com/DXTestCafe).
