### ISSUE TITLE
Test freezes when the contents of a pop up are changed by its parent using document.write()

### ISSUE THREAD

**Issue by titerman** [DevExpress/testcafe#5337]
node v12.16.1, testcafe 1.9.0-alpha.1

HTML:
```html
  <button value="Press me" id="btn1">Press me</button>
  <input type='text' id="text"></input>
````

JS:
```js
    const openWindow2 = () => {
        let popUp = window.open('any/path/you/want', window, "height=200,width=500");
        popUp.document.write('Test');
    };
    const btn = document.querySelector('#btn1');
    btn.addEventListener('click', openWindow2);
```

Test code:
```js
import { Selector, ClientFunction } from 'testcafe';

fixture `Test page`
    .page('path/to/the/html/file');

test('Open and close', async t => {
    const parent = await t.getCurrentWindow();
    await t.click('#btn1');
    console.log('clicked the button');
    await t.switchToWindow(parent);
    console.log('switched to the parent window');
    await t.typeText('#text', 'text');
});
```
 
### What is the Current behavior?

The test stops running after the button is clicked. No error is logged. After several minutes of waiting, the browser disconnects, and the process is terminated with an error. If the user manually closes the pop-up window, the test succeeds. 

Shell output (no action taken):
```text
 Running tests in:
 - Firefox 78.0 / Linux 0.0

 Test page
button clicked
ERROR The Firefox 78.0 / Linux 0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.
```

Shell output (manually closed the pop-up):
```text
 Running tests in:
 - Firefox 78.0 / Linux 0.0

 Test page
button clicked
window switched
 ✓ Open and close


 1 passed (3s)
```
If we substitute the following line:
```js
popUp.document.write('Test');
```
for:
```js
popUp.document.querySelector('body').appendChild(document.createTextNode('Test'));
```

everything works as it should.

### What is the Expected behavior?
The test should keep running after the contents of a pop-up window are modified using document.write();

**Comment by AlexKamaev** [comment]
To the team:
I researched the issue, but its real cause is still unclear.
It looks like it all relates to the `document.write` method call. However, I cannot say this for sure as I was not able to reproduce the issue without the `document.write` method.
I also found that even if I add a small delay instead if using the existing code, the browser still hangs. When I remove the delay, the code starts working as expected. So, the issue does not seem to directly relate to the multi-window functionality.
