### ISSUE TITLE
Reporter: screenshots are generated in screenshots folder but not passed to the reporter [BrowserStack]

### ISSUE THREAD

**Issue by hdorgeval** [DevExpress/testcafe#5341]
### What is your Test Scenario?
While running tests on browserstack, in some situation, screenshots are not passed to the reporter although they are created in the screenshots folder, but instead the reporter receives only warnings about processing of these screenshots.
 
### What is the Expected behavior?
When a screenshot is generated on disk, it should be passed to the reporter even if the TestCafé runtime cannot process it.
 
### What is your web application and your TestCafe test code?
I have setup a repo that reproduces the problem with all details:

[reporter issue repo](https://github.com/hdorgeval/reporter-issue)

Thanks!

**Comment by Dmitry-Ostashev** [comment]
The similar problem was discussed here: https://github.com/DevExpress/testcafe-browser-provider-browserstack/issues/51#issuecomment-460156835. I suggest you try a solution from this comment. Let us know if it doesn't help.

**Comment by hdorgeval** [comment]
Hi @Dmitry-Ostashev, I have tested all these suggestions but none works. In the sample repo given above, two element screenshots and one full-page screenshot are asked, but none of these screenshots are reported to the reporter.

The problem is that at least the full-page screenshot should have been passed to the reporter but this is not the case.

So for me, the TestCafé Reporter Plugin Host is breaking the contract expected by the reporter: that is, when a screenshot file has been generated on disk, it must be passed to the reporter.

This issue is not an issue on screenshot generation but an issue between the **Reporter Plugin Host** and the loaded **Reporters** as you are not compliant with your [own documentation](https://devexpress.github.io/testcafe/documentation/reference/plugin-api/reporter.html#screenshots-object)!

**Comment by AlexKamaev** [comment]
@hdorgeval I checked your scenario and found the following:

* it works as expected if the browser is set as "browserstack:chrome" and `BROWSERSTACK_USE_AUTOMATE=1`
* it works as you described if the browser is set as "browserstack:Xiaomi Redmi Note 8" even if `BROWSERSTACK_USE_AUTOMATE === 1`


In the second case, I see that some screenshots are saved in the `screenshots` directory. However, I see the `Unable to locate...` error and the `screenshots` field in the `testRunInfo` object is empty.

This behavior looks unexpected. We'll work on it.

**Comment by hdorgeval** [comment]
Hi @AlexKamaev, thank you for your feedback. You are perfectly right in your analysis. It would be great if you could update the Reporter Plugin Host, so that the TestRunInfo object passes generated screenshots files even when there are some errors while processing them. Having the raw screenshot is better than no screenshot at all.

Thanks!

**Comment by vasantverma-LM** [comment]
Hi @AlexKamaev - Do you have any update on this ?  
This is a blocker for running testcafe tests on browserstack.

**Comment by wentwrong** [comment]
Hi @vasantverma-LM 

You are right that information about generated screenshots should be passed to a reporter regardless of whether there are any problems with processing them. We'll update this thread once we have more information to share or the fix is deployed.
