### ISSUE TITLE
Research authorizing with different accounts in different windows

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#5343]

**Comment by miherlosev** [comment]
The task contains 3 sub-tasks:
* support several sessions per one test run. Need to: change internal objects hierarchy in the `SessionController`, remove the connection between `testRun.id` and `session.id`, clone resources (request hooks, client scripts) from the initial session. 
* `userRole` in the multi-session mode. Need to discuss the handling of the edge case: apply role for another session, the initial session is closed, the session is closed during role initialization).
* decide what action will initiate the new session creation (`openWindow` call, `useRole` call, or something else).

https://github.com/DevExpress/testcafe/compare/master...miherlosev:i5343
