### ISSUE TITLE
Testcafe failure on page load 1.8.7 -> 1.9.0-alpha.2 (Uncaught SyntaxError: Unexpected token ';' )

### ISSUE THREAD

**Issue by michaelcariello** [DevExpress/testcafe#5345]
### What is your Test Scenario?
Step 1: Attempt to load and login to page 
Result: App does not load, login fails, test fails to find first object 

### What is the Current behavior?
 Immediately on web page load , failure in title is found using the inspection tool .

### What is the Expected behavior?
Expected behavior is for all versions > 1.8.4 to function the same as 1.8.4. On version 1.8.4 of testcafe when attempting to log into local app , login & page load work with no issues. Once upgrading above this number, this issue arises on page load of all tests preventing test suites from being able to move forward. 
 
### What is your web application and your TestCafe test code?

My web application is private IP I am unable to share information that exposes that IP. If there is specific logs/data required for debugging that does not expose private IP I will gladly share. 

<details>
<summary>Screenshots:</summary>
 -->

<img width="330" alt="Screen Shot 2020-07-21 at 12 17 42 PM" src="https://user-images.githubusercontent.com/63267395/88098285-60ca9c00-cb4e-11ea-95a1-752085fc185a.png">

<img width="572" alt="Screen Shot 2020-07-21 at 12 37 48 PM" src="https://user-images.githubusercontent.com/63267395/88098677-03831a80-cb4f-11ea-84b9-9a292141b868.png">

</details>

### Your Environment details:
 
* testcafe version:                   1.8.7, 1.8.8, 1.9.0-alpha.1, 1.9.0-alpha.2
* node.js version:                    v12.16.3
* command-line arguments:  testcafe chrome -e Mytest.js
* browser name and version:  Chrome 84.0.4147.89 
* platform and version:          macOS 10.15.4
* other:                                   All functionality has no issues on 1.8.4 version. Upgrade the build and failures begin to arise on page load

**Comment by LavrovArtem** [comment]
The information you shared is insufficient to determine the cause of the issue. We need a simple example that demonstrates the problematic behavior.

**Comment by michaelcariello** [comment]
> The information you shared is insufficient to determine the cause of the issue. We need a simple example that demonstrates the problematic behavior.

Hi yes what sort of example are you looking for? The only example I can give you is , go to url, attempt to find username login selector.

**Comment by michaelcariello** [comment]
`fixture`Add and Save an FX Rate`.page`${baseUrl()}`.beforeEach(async (t) => {
    Logger.info('Attempting to login');
    await LoginPage.login();
});`

**Comment by michaelcariello** [comment]
here is a screen recording of what occurs: https://photos.app.goo.gl/f96i5nEfTWzLBS138
This occurs on every version after 1.8.4 for the same test. However this happens for every test we have in our suite. When using 1.8.4 there is no issue.

**Comment by elfia** [comment]
hi i am seeing similar problem with the latest version. With 1.8.6 I am able to run tests without any problems, but with 1.8.7 the whole page gets blocked. I am using Jira cloud dev framework - atlassian-connect. This is reproduced with Chrome and Firefox browsers on Mac OS. The error is:
`commons.f014572ad96de19a5daf.8.js:13 Uncaught SyntaxError: Unexpected token ','` - there is a comment in the file for hammerhead script start and end.
Not sure if this error is the reason but with 1.8.6 I do not see error in the hammerhead script and tests are running successfully.

**Comment by alexey-lin** [comment]
@elfia, I am happy to hear that alpha2 solved the problem.

@michaelcariello, we need the code of a failed test and a public URL or sample project that we could run on our side to reproduce the issue, investigate it and find its cause. Unfortunately, I couldn't reproduce the issue using only this line of code.

**Comment by michaelcariello** [comment]
Hi I understand this issue is closed. I am unable to give you any version of the app that I am running on as it is Private IP. Legally I am not allow to give you a public URL of a product protected by Private IP. It seems other people have ran into this issues. I will test out whatever release comes next in hopes that it gets fixed.

**Comment by michaelcariello** [comment]
I am willing to setup a conversation give you whatever you need but there is no way i can give you the application we are developing.

**Comment by michaelcariello** [comment]
Tested new testcafe RC put out 2 days ago and seems the issue is no longer reproducible in that version.

**Comment by AlexSkorkin** [comment]
Thank you for the update. I am happy to hear that the new RC solved the issue.
