### ISSUE TITLE
Unknown option: chrome with locally installed version of TestCafe

### ISSUE THREAD

**Issue by zhkostadinov** [DevExpress/testcafe#5347]
I'm using locally installed version of testCafe. That version is: 15.1.317922 
Starting from today, I have the following error:

**Using locally installed version of TestCafe.                                                                                                                                                     Unknown option: chrome                                                                                                                                                                           npm ERR! code ELIFECYCLE                                                                                                                                                                         npm ERR! errno 1
--**

I'm runing the following command with npm:
`./node_modules/.bin/testcafe chrome -e -q tests/ -s ./artifacts/screenshots/ -p ${TEST_INDEX}_${DATE}_${TIME}.png --screenshots-on-fails=true --fullPage=\"true\" --reporter html:artifacts/html/RegressionReport.html --selector-timeout 150000 --page-load-timeout 150000 --assertion-timeout 30000"`
Tha command is located in my package.jsons, scripts section. 
That behavior is with all browsers. No matter which I'm trying to use.
Any advice? 

 
Using locally installed version of TestCafe.

**Comment by LavrovArtem** [comment]
Hello,

The `15.1.317922` version is the old [TestCafe v2015.1](https://testcafe.devexpress.com/Documentation/) version. To use TestCafe, install it via `npm install testcafe@latest`.

**Comment by zhkostadinov** [comment]
In my  package.json i have:
"testcafe": "^15.1.317922"

That should install the latest version, correct?

**Comment by AndreyBelym** [comment]
Please use the following line in your `package.json`:
```
"testcafe": "^1.8.8"
```
