### ISSUE TITLE
Ability to reinitialize role

### ISSUE THREAD

**Issue by lunstb** [DevExpress/testcafe#5351]
### Are you requesting a feature or reporting a bug?
Bug

### What is your Test Scenario?
I have a role (adminRole) that I use to login for most of my tests. Generally, I have some code that logs into it in each fixture's beforeEach hook (await t.useRole(adminRole)). This works well except there is one test that requires logging in without using the role (following a specific link) which makes the role invalid resulting in all following tests failing without being able to login. I would like to be able to change the phase property on adminRole to require the test to login to the account again so that it works.

### What is the Expected behavior?
I expect to be able to 

#### Provide the test code and the tested page URL (if applicable)
Here is the code for loggin in to adminRole:
```
adminUser = Role(
    '',
    async (t) => {
      const user = Users.ADMIN

      await t.navigateTo(`${this.targetURL}/login`)
      const loginPage: LoginPage = new LoginPage()

      const username = this.secretsFile[user].username
      const password = this.secretsFile[user].password

      await t.typeText(loginPage.username, username).typeText(loginPage.password, password).click(loginPage.loginButton)
    },
    { preserveUrl: true }
  )
```

Here is what I get when I log out adminRole in the console (I would like to be able to change phase)
```
Role {
  domain: null,
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  id: '74~Qw2e',
  phase: 'initialized',
  loginPage: 'http://',
  initFn: [AsyncFunction],
  opts: { preserveUrl: true },
  url: 'https://coolwebsitename.com',
  stateSnapshot:
   StateSnapshot {
     cookies:
      '{cookie information}',
     storages:
      { localStorage: '[[],[]]',
        sessionStorage:
         'session data' } },
  initErr: null,
  [Symbol(testRun)]: true }
```

### Your Environment details:
 
* testcafe version:                   1.8.8
* node.js version:                    v10.16.0
* command-line arguments:  none
* browser name and version: Chrome 84
* platform and version:          Windows

**Comment by alexey-lin** [comment]
Hi @tuktukmaster,

Thank you for the suggestion. We will think about it. For now, you can consider using two identical roles: one before invalidation and the other after that.

**Comment by Ogurecher** [comment]
Another use case for this feature is as follows: the authorization cookie expires before the test run is finished. It would be helpful if we could re-initialize the `Role`.

**Comment by miherlosev** [comment]
https://stackoverflow.com/questions/56439705/is-it-possible-to-uninitialize-reinitialize-delete-role-in-testcafe-e2e-test
https://stackoverflow.com/questions/66978389/testcafe-is-there-a-way-that-a-role-can-detect-an-expired-session

**Comment by wombatka** [comment]
I faced this problem when trying to write test for proper session timeout handling. I could not use the existing role after session expired anymore. After digging like for half a day I finally managed to find a workaround
1.create new role for same credentials
2. update cookies of old role with cookies from new role. 
async function reinitializeRole() {
    const newRole = Role(appUrl, async () => {
        await loginPageModel.login('username', 'password')
    });
    await t.useRole(newRole);
    const stateSnapshotCookies = JSON.parse(newRole.stateSnapshot.cookies);
    **oldExpiredRole.stateSnapshot.cookies = JSON.stringify(stateSnapshotCookies);**
  
}
I think it would be really useful to add a simple mechanism to do it
Or at least update docs with such or different workaround solution...

**Comment by VasilyStrelyaev** [comment]
Thank you for sharing your workaround! Please note that Role.stateSnapshot is a part of the internal API. It's not documented and is subject to change without prior notice.
 
I can suggest a similar solution, which does not involve an internal API. You can create your own helper method useRole, which will checks if the user is no longer logged in and re-create the Role object if so:

```js
import { ClientFunction } from 'testcafe';

const isLoggedOut = ClientFunction(() => document.location.href === 'https://mysite.com/login/');

let role = new Role(/* ... */);

async function useRole (t) {
    if (await isLoggedOut())
        role = new Role(/* ... */);
    await t.useRole(role);
}
 
fixture `My fixture`
    .beforeEach(async t => {
        await useRole(t);
    });
``` 

My example uses a client function that detects if the login page is currently open as an indicator that a user is logged out (assuming that a website redirects users with expired authentication automatically). You can use a different indicator, which is suitable for your scenario.
