### ISSUE TITLE
TestCafe doesn't support MacOS latest versions in cloud CI systems (Gut Hub Actions)

### ISSUE THREAD

**Issue by revanthreddygandra** [DevExpress/testcafe#5352]
#### HEADS UP!
are these features in progress or completely put on hold ?

**Comment by alexey-lin** [comment]
Hi @revanthreddygandra,

Just to be clear, are we talking about official DevExpress [Run TestCafe](https://github.com/marketplace/actions/run-testcafe) GitHub action? What exact difficulties did you face configuring it to run on `macos-latest`? Are you getting some error?

**Comment by revanthreddygandra** [comment]
Hi @alexey-lin 
Yes I am getting the following error.

UnableToAccessScreenRecordingAPIError: The find-window process cannot access the Screen Recording API.

When I change the OS to macos-latest.
was going through some discussions and got to know that testcafe doesn't support the latest versions of mac os on cloud CI a while ago.
Wanted to know any solution is given or not yet.

**Comment by wentwrong** [comment]
As described [here](https://devexpress.github.io/testcafe/documentation/guides/basic-guides/install-testcafe.html#screen-recording-permission):

> TestCafe requires a screen recording permission on macOS (v10.15 Catalina and newer) to perform test actions, take screenshots and record videos. When TestCafe starts the first time, macOS asks you to allow screen recording for TestCafe Browser Tools.

Github Actions [uses](https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners) the `macOS Catalina 10.15` virtual environment with the enabled "System Integrity Protection" as `macos-latest`.

As stated [here](https://github.com/DevExpress/testcafe/issues/4512#issuecomment-577177550):

> MacOS 10.15 Catalina brought an update to the security system that makes TestCafe unable to even detect browser windows without obtaining the Screen Recording permission. Moreover, this permission can't be obtained programmatically without disabling the System Integrity Protection and rebooting the system

I think this [suggestion](https://github.com/actions/virtual-environments/issues/650) to allow the use of Mac with the disabled SIP on Github Actions should solve this problem.
We'll address this in our current limitations. Thanks for pointing this out.
