### ISSUE TITLE
Provide browser instance id for concurrent tests

### ISSUE THREAD

**Issue by mixtur** [DevExpress/testcafe#5356]
### What is your Test Scenario?
Multiple tests that concurrently use the same data (on a server). When we use concurrent tests execution (-c) race conditions emerge.

### What are you suggesting?
We would like to remove the concurrency and run tests in isolated sandboxes, one sandbox per browser instance. To do so we'll need to identify browser instances from test code.
I suggest simply adding `concurrentInstanceId` or `instanceIndex` to `t.browser` with a value unique per browser instance.

### What alternatives have you considered?
- `t.useRole(createRandomRole())` before each test. Aka running every single test in its own sandbox. It works but collisions still may happen and it introduces unnecessary overhead.
- `t.useRole(presavedRandomRole)`. Does not work because it seems roles are shared across instances.

### Additional context
There is some discussion in [this StackOverflow question](https://stackoverflow.com/questions/62994313/is-there-a-way-to-tell-one-browser-instance-from-another-when-running-concurrent)

I think `t.testRun.browserConnection.id` is what I am looking for but I am not sure, and also I am not sure if it is something documented.

**Comment by wentwrong** [comment]
Thank you for your suggestion. This feature can be really useful to determine using a test in what particular browser it is being executed.
`t.testRun.browserConnection.id` contains a unique identifier of the browser instance. However, this functionality is intended for internal usage (therefore, it is not documented). So, we cannot guarantee that it won't be changed in the future.
