### ISSUE TITLE
Quarantine-mode  brakes Jenkins runs against Chrome and Edge

### ISSUE THREAD

**Issue by zhkostadinov** [DevExpress/testcafe#5360]
I've installed Tescafe v1.8.8 on Jenkins v2.235.2 under Windows Server 2012.
I run the jobs thought bat file. I have in that bat file:
`./node_modules/.bin/testcafe chrome -e -g tests/ -s ./artifacts/screenshots/ -p ${TEST_INDEX}_${DATE}_${TIME}.png -s takeOnFails=true --fullPage=\"true\" -r html:artifacts/html/RegressionReport.html --selector-timeout 150000 --page-load-timeout 150000 --assertion-timeout 30000`    
For a week the builds started to fail after 20-30miniutes of execution. The error is always the same:
`ERROR The Microsoft Edge 84.0.522.39 / Windows 8.1 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.`
That happens only on the Edge and Chrome. Firefox is working perfectly. 
I've tried to downgrade the version of Chrome and Edge without positive results. 
I've tried to run without bat file the configuration, directly in the Jenkins batch window without positive results.
When I remove that `-q` option from the command line, the job & tests are working fine.

Any ideas peeps?

**Comment by wentwrong** [comment]
It's very unusual that disabling of the quarantine mode helped to avoid this error. In most cases, this error is thrown due to the unstable connection (by the way, currently we are [working](https://github.com/DevExpress/testcafe/issues/5239) on improving that situation with the help of service workers).
Could you share with us a minimal reproducible example?

**Comment by zhkostadinov** [comment]
Hello. Thanks for the response. What information do you need from my side?

**Comment by miherlosev** [comment]
Hi @zhkostadinov 

Could you please share with us Jenkins job logs and test execution reports with and without the 'concurrency' option?

**Comment by zhkostadinov** [comment]
It seems Chrome has some issues: https://support.google.com/chrome/thread/60047370?hl=en 
It might be related. 
That is the log from the Jenkins:
16:59:57 No emails were triggered.
16:59:57 [Regression] $ cmd /c call C:\Windows\TEMP\jenkins6422969229760146468.bat
17:00:25  Running tests in:
17:00:25  - Chrome 84.0.4147.89 / Windows 8.1
17:00:25 
17:00:25  Create projects tests
17:01:09  âˆš User should land on create new idea page
17:01:14  âˆš Not registred user should land on create new idea page
17:04:47 ERROR The Chrome 84.0.4147.89 / Windows 8.1 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.
17:04:47 
17:04:47 Type "testcafe -h" for help.
17:04:49 Build step 'Execute Windows batch command' marked build as failure
17:04:53 Email was triggered for: Failure
17:04:53 Sending email for trigger: Failure

**Comment by wentwrong** [comment]
I'm not sure that the Chrome bug which you mentioned could be a problem in this case (until you use a browser profile or your tests in some way interact with "Inspector tool" in Chrome. But more often - they don't).

It's hard to say without an example what was the real cause of the error. But in general, we can give you the following recommendations:
* Can the issue be reproduced via running out of Jenkins? (CI systems are often provide different wrappers to run script files);
* Is it suitable to use [headless](https://devexpress.github.io/testcafe/documentation/guides/concepts/browsers.html#test-in-headless-mode) mode in your case? (It's often the best approach);
* Check that active resource (CPU/RAM) consumption during test execution does not reach a critical level;
* As I described above, we are in the process of handling the problem with a stability of a browser connection. You may try to use our test build, which includes a mechanism for it. All that needs to be done for this is:

Install it by using the

```
npm install --save-dev https://git.io/JJZoa
```
command (or just replace your TestCafe version with https://git.io/JJZoa in your package.json)

As I asked in my first comment, a minimal reproducible example would be very helpful. You can share it with us privately by support@devexpress.com. But please note that our policy prevents us from accessing a customer’s internal resources without prior written approval from the entity that owns the server/web resource. If your tests use some resources that aren't public to all Internet users, please ask the website owner to send us support@devexpress.com a written confirmation. It must permit DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes.

**Comment by zhkostadinov** [comment]
Thanks for the response. The "issue" is in that,  it's not failed consistently. It might take after 3 or 30 minutes in different places. 
Will give a try with that test build. Will keep you posted.

**Comment by zhkostadinov** [comment]
That error log I have with the test build:

02:07:58 Tue, 28 Jul 2020 23:07:58 GMT testcafe:browser:connection:E~EZ~29 Browser opened
02:15:37 Tue, 28 Jul 2020 23:15:37 GMT testcafe:browser:connection:E~EZ~29 Browser disconnected GeneralError: The Firefox 78.0 / Windows 8.1 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.
02:15:37     at BrowserConnection._createBrowserDisconnectedError (C:\Users\Administrator\.jenkins\workspace\Regression\TestCafe\node_modules\testcafe\src\browser\connection\index.ts:196:16)
02:15:37     at Timeout._onTimeout (C:\Users\Administrator\.jenkins\workspace\Regression\TestCafe\node_modules\testcafe\src\browser\connection\index.ts:201:30)
02:15:37     at listOnTimeout (internal/timers.js:531:17)
02:15:37     at processTimers (internal/timers.js:475:7) {
02:15:37   code: 'E1002',
02:15:37   data: [ 'Firefox 78.0 / Windows 8.1' ]
02:15:37 }
02:15:38 Tue, 28 Jul 2020 23:15:37 GMT testcafe:browser:connection:E~EZ~29 Browser restart
02:15:45 Tue, 28 Jul 2020 23:15:45 GMT testcafe:browser:connection:E~EZ~29 Browser closed
02:16:37 Tue, 28 Jul 2020 23:16:37 GMT testcafe:browser:connection:E~EZ~29 Error: The Firefox 78.0 / Windows 8.1 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.
02:16:37     at BrowserConnection._createBrowserDisconnectedError (C:\Users\Administrator\.jenkins\workspace\Regression\TestCafe\node_modules\testcafe\src\browser\connection\index.ts:196:16)
02:16:37     at C:\Users\Administrator\.jenkins\workspace\Regression\TestCafe\node_modules\testcafe\src\browser\connection\index.ts:259:45
02:16:38 Tue, 28 Jul 2020 23:16:38 GMT testcafe:browser:connection:E~EZ~29 TypeError: Cannot read property 'config' of undefined
02:16:38     at BrowserProviderPluginHost.isHeadlessBrowser (C:\Users\Administrator\.jenkins\workspace\Regression\TestCafe\node_modules\testcafe\src\browser\provider\built-in\dedicated\base.js:45:47)
02:16:38     at BrowserProvider.canUseDefaultWindowActions (C:\Users\Administrator\.jenkins\workspace\Regression\TestCafe\node_modules\testcafe\src\browser\provider\index.ts:215:53)
02:16:38     at BrowserProvider.closeBrowser (C:\Users\Administrator\.jenkins\workspace\Regression\TestCafe\node_modules\testcafe\src\browser\provider\index.ts:276:44)
02:16:38     at BrowserConnection._closeBrowser (C:\Users\Administrator\.jenkins\workspace\Regression\TestCafe\node_modules\testcafe\src\browser\connection\index.ts:178:13)
02:16:38 ERROR The Firefox 78.0 / Windows 8.1 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.

**Comment by alexey-lin** [comment]
Hi @zhkostadinov,

Thank you for the extended log. Unfortunately, it didn't prove the hypothesis we had. As Pavel said before, we need some reproducible example to reproduce the issue and investigate it on our side.

**Comment by zhkostadinov** [comment]
Hello peeps.
After a hours spent in the investigation finally, the issue was found. 
It comes from two directions:  Malwarebytes and CPU usage of 100%.  
By the way, with that new feature to restart the chrome in case of error helps me a lot.
Cheers. Thanks
