### ISSUE TITLE
Negative filtering in the CLI

### ISSUE THREAD

**Issue by mixtur** [DevExpress/testcafe#5369]
### What is your Test Scenario?
We have multiple builds in Team City for different platforms. For some of them we would like to disable certain tests. Since we cannot yet [conditionally skip tests](https://github.com/DevExpress/testcafe/issues/1626) We are disabling them on file basis. But it looks terrible. We have to basically enumerate all the test files in the CLI except ones we want to exclude. It is very inconvenient to write and hard to read afterwards.

### What are you suggesting?
Either negative filtering by meta or negative filtering by globs.
I would imagine filtering by meta as `--fixture-meta key\!=value`
Negative globs would be something like `testcafe chrome "tests/all/**/* \!tests/all/except-one.js"`

 `\!` - is escaped because bash has a special meaning for `!`

 I believe negative globs should work already because it is supported by `node-glob` but they doesn't for whatever reason.

**Comment by Ogurecher** [comment]
Hello @mixtur,

Thank you for your report. You can filter out tests using negative globs: `testcafe chrome "tests/all/**/*" \!"tests/all/except-one.js"`. Please make sure that you pass each pattern as a separate argument.

**Comment by mixtur** [comment]
Thank you, that helps a lot.
But I think this should be explicitly documented as it is not too obvious.
