### ISSUE TITLE
Run execution error

### ISSUE THREAD

**Issue by bayouprophet22** [DevExpress/testcafe#5372]
### What is your Test Scenario?

// JavaScript source code
import { Selector } from 'testcafe';

fixture `Getting Started`
    .page `http://devexpress.github.io/testcafe/example`;

test('My first test', async t => {
    // Test code
});

### What is the Expected behavior?

![image](https://user-images.githubusercontent.com/68291306/88816604-2e3e2600-d182-11ea-9ed3-5bdb38ba79ae.png)

#### Provide the test code and the tested page URL (if applicable)

 
Your website URL (or attach your complete example):

Your complete test code (or attach your test files)

```js
![image](https://user-images.githubusercontent.com/68291306/88816702-49a93100-d182-11ea-90ef-31fe2028bdc3.png)

```
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by Farfurix** [comment]
@bayouprophet22 

Hello,

Your macOS version [has the "Unsupported. Extended support ended in September 2018." support status](https://en.wikipedia.org/wiki/OS_X_El_Capitan).
I suggest you [use a minimal supported macOS version](https://github.com/DevExpress/testcafe-browser-provider-browserstack/issues/125#issuecomment-666994653) with the latest browser version. If you have other issues as a result, please report them.
