### ISSUE TITLE
Enable TestCafe to Take Browser Heap Snapshot as we can take from Chrome DevTool Memory Tab Option

### ISSUE THREAD

**Issue by rakeshkumartripathy** [DevExpress/testcafe#5373]
### What is your Test Scenario?
I do take Memory Heap Snapshot of different pages in Chrome DevTool Memory Option which I think could be Automated in TestCafe. 

### What are you suggesting?
I do take Memory Heap Snapshot of different pages in Chrome DevTool Memory Option which I think could be implemented in TestCafe. This Will help to take automatic Browser Heap Snapshots of WebPages and later we can analyze those Heap snapshots by just loading to Chrome DevTool Memory Tab.

### What alternatives have you considered?
Right Now I do this manually in Chrome DevTool Memory Tab like in below screenshot for different pages :-

![image](https://user-images.githubusercontent.com/68940011/88904361-9d934300-d272-11ea-9fa8-b907b6008d60.png)

**Comment by Farfurix** [comment]
@rakeshkumartripathy 

Hello,

At present, we cannot interact with DevTools UI / [DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/tot/HeapProfiler/#method-takeHeapSnapshot) to take a Heap snapshot. I marked this issue as an enhancement.

As a workaround, I suggest you use the `window.performance` interface to collect all needed information. [Here](https://github.com/DevExpress/testcafe/issues/3546) you can find a way to access the `memory` and `timing` objects in tests. **Note that TestCafe affects browser performance and, as a result, your performance analysis**.
