### ISSUE TITLE
[docs] Add a recipe(s) for testing HTML5 features (video, audio, fullscreen, etc.)

### ISSUE THREAD

**Issue by Ogurecher** [DevExpress/testcafe#5374]
https://supportcenter.devexpress.com/internal/ticket/details/T918787

**Comment by Ogurecher** [comment]
I think we also should explain how to mock the camera using ClientFunctions.

**Comment by titerman** [comment]
We don't plan to address this issue in the near future. Feel free to reopen the ticket if the issue is important for you.
