### ISSUE TITLE
Test Cafe is not refreshing UI and this is not loading elements in UI 

### ISSUE THREAD

**Issue by NewaBoy** [DevExpress/testcafe#5379]
When Form is opened through any action and needs to display elements in the form with backend logic, these elements are not getting loaded.

eg. 
- Click the button to open the form
- Before loading the form, the elements needs to be loaded based on backend logic from database.

Issue: TestCafe just opens a form  before backend logic is triggered. This is causing elements to be not loaded.

**Comment by Farfurix** [comment]
Hello,

We need more information to determine the cause of the issue. Could you please share a simple project with us? We'll examine it and check for a suitable solution.
