### ISSUE TITLE
Unable to switch to a frame which is inside a <object> tag

### ISSUE THREAD

**Issue by sayantan528** [DevExpress/testcafe#5382]
The html of the page looks like

<html>
<body>
....
....
<object id="myFrame">
......
....
</object>
</body>
</html>

![2020-07-31](https://user-images.githubusercontent.com/69032781/89014892-d3e4c700-d333-11ea-8d3a-2a7c15a6a7f4.png)

Version->
Testcafe-1.8.8
Chrome-84..4147.105

**Comment by wentwrong** [comment]
Thank you for pointing out to this. I suggest you track issue [#1021](https://github.com/DevExpress/testcafe/issues/1021) to be aware of our progress with this functionality.

**Comment by vasantverma-LM** [comment]
@wentwrong - Thank you for your response.
I have seen the issue #1021 . The conversation on that issue has been marked as resolved and I am not able to add a comment on it.
Do you we have any release note for issue #1021 ?

**Comment by Dmitry-Ostashev** [comment]
At present, we cannot give any time frames because any personal estimate may be misleading. We reopened issue https://github.com/DevExpress/testcafe/issues/1021. Once we have any results, we will update that thread.
