### ISSUE TITLE
Syntax error at the end of the script

### ISSUE THREAD

**Issue by bayouprophet22** [DevExpress/testcafe#5385]
Getting error:
```
SyntaxError: C:/Users/bayou/TestCafe/philosearch.js: Unexpected token (16:3)
  14 |         .typeText('#developer-name', 'John Smith')
  15 |         .pressKey('space')
> 16 | });
```

After running the following code. New to coding and can't figure out why this is happening

```js
// JavaScript source code
import { Selector } from 'testcafe';

fixture `Getting Started`
    .page `https://help.philo.com/`;

test('Philo search', async t => {
const search = Selector(async() => {
    return document.getElementById('search');

   await t

		.click('search')
        .typeText('#developer-name', 'John Smith')
        .pressKey('space')
});
```

**Comment by AlexSkorkin** [comment]
Thank you for your interest in our testing tools. You are welcome to ask any TestCafe related questions on StackOverflow (https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.

If you think that you found a bug, feel free to open a new issue in the GitHub repo https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md). Thank you in advance.
