### ISSUE TITLE
A window is opened in an existing tab instead of a new window

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#5393]
### Are you requesting a feature or reporting a bug?
Bug

### What is your Test Scenario?
Use the multiple window feature, click a link that opens in a new tab/window.

### What is the Current behavior?
When the link is clicked, a new tab is opened in an existing window. This leads to an error afterwards.

### What is the Expected behavior?
A new separate window should be opened, no error should be thrown.

### How would you reproduce the current behavior (if this is a bug)?
Run the test.

#### Provide the test code and the tested page URL (if applicable)

 
Your website URL (or attach your complete example):

Your complete test code (or attach your test files)

```js
fixture`dtf`.page`dtf.ru`;

test('check terms&conditions', async t => {
    await t
        .click('body > div.site-header > div:nth-child(9) > div')
        .click('body > div.popup > div.popup__container.popup__container--shown > div > div.popup__container__window__tpl > div > div > div.auth-form__main > div.auth-form__tab.auth_tab.auth_tab--signin-start > div.auth-form__content > div.social-auth.social-auth--with-email > div:nth-child(5) > div')
        .click('#bd > div > div.app-info > dl > dd:nth-child(10) > p > a')

    const window = await t.getCurrentWindow();

    // Terms and conditions title
    console.log(await t.eval(() => document.title));

    await t
        .switchToPreviousWindow()
        // Error here because we cannot properly switch to the previous window
        // when the first window in the tab is suppressed
        .click('#cancel');
});

```
### Your Environment details:
 
* testcafe version:                   `1.9.0-rc.1`
* node.js version:                    `14.0.0`
* command-line arguments:  `testcafe chrome test.js`
* browser name and version: `chrome 84`
* platform and version:          `Windows 10`
* other:

**Comment by AlexKamaev** [comment]
fixed in https://github.com/DevExpress/testcafe-hammerhead/pull/2564
