### ISSUE TITLE
During termination of the code 

### ISSUE THREAD

**Issue by arvindarun** [DevExpress/testcafe#5397]
![image](https://user-images.githubusercontent.com/54062330/89447789-3692f400-d774-11ea-9848-8418ceaab2ee.png)

Code is executing successfully during termination it is throwing error message as mentioned in the screenshot
Node version: 14.7.0
npm version: 6.14.7
testcafe version: 1.8.1

**Comment by miherlosev** [comment]
Hi @arvindarun

You are using an outdated TestCafe version. Try to run your tests with the latest TestCafe version (`1.8.8`) and let us know if this addresses the issue.

**Comment by arvindarun** [comment]
Hi @miherlosev
On upgrading testcafe version issue got resolved, thanks for the solution
