### ISSUE TITLE
TestCafe cannot drag an element on an Angular page

### ISSUE THREAD

**Issue by ofirrifo** [DevExpress/testcafe#5401]
### What is your Test Scenario?

I have an DOM element that can be resizable.
I try to use the drag function but it not work 

```
  await t.wait(100).drag(Selector('any selector'),
    100, 0, { offsetX: 193, offsetY: 400, speed: 0.01 });
```

### What are you suggesting?
to add support function for resize element

### What alternatives have you considered?
I try to use the drag function but it not work 

```
  await t.wait(100).drag(Selector('any selector'),
    100, 0, { offsetX: 193, offsetY: 400, speed: 0.01 });
```

### Additional context

I saw that selenium support it
http://www.appliedselenium.com/2019/04/actions-class-in-selenium-drag-drop-resize/

**Comment by Farfurix** [comment]
@ofirrifo 

Hello,

Could you please share with us a simple project that illustrates your scenario? We'll examine it and check for a suitable solution.

**Comment by ofirrifo** [comment]
@Farfurix sure I will add example soon

**Comment by ofirrifo** [comment]
@Farfurix 
so I created example of an element that can be resize
[Example](https://stackblitz.com/edit/angular-ivy-ynljsz?file=src%2Fapp%2Fapp.component.html)

In my test I want to check that resize work

**Comment by Farfurix** [comment]
@ofirrifo 

Hello,

Thank you for the example. I reproduced the issue. Our team will examine it and check for a suitable solution.
For the team.

Local example: [proj.zip](https://github.com/DevExpress/testcafe/files/5068378/proj.zip)

Commands:
```
npm run start
npm run testcafe
```

**Comment by ofirrifo** [comment]
@Farfurix 
 I'm really Appreciate you'r fast response.
Thanks,
