### ISSUE TITLE
Take Screenshots failed!

### ISSUE THREAD

**Issue by Tester-Dolores** [DevExpress/testcafe#5403]
code
```
fixture `My fixture`
    .page `http://devexpress.github.io/testcafe/example/`;

test('Take a screenshot of a fieldset', async t => {
    await t
        .typeText('#developer-name', 'Peter Parker')
        .click('#tried-test-cafe')
        .typeText('#comments', 'I think TestCafe is awesome!')
        .takeElementScreenshot('#comments')
        .click('#submit-button')
        .takeScreenshot();
});
```
run test
` testcafe chrome ./ `
result
![image](https://user-images.githubusercontent.com/68461925/89598268-f6746400-d88e-11ea-9cb6-7399483dde90.png)

**Comment by AlexSkorkin** [comment]
Thank you for your interest in our testing tools.

My attempts to replicate this issue were unsuccessful. I've got two screenshots successfully:

![image](https://user-images.githubusercontent.com/995726/89619199-3db22300-d896-11ea-8dd0-9feec3fe9e94.png)

![image](https://user-images.githubusercontent.com/995726/89619207-4145aa00-d896-11ea-8241-d068dc74212f.png)

I recommend that you follow the instructions from the error message.
