### ISSUE TITLE
Auto wait mechanism if when specific element on page is detected

### ISSUE THREAD

**Issue by Evilweed** [DevExpress/testcafe#5404]
Hello, I want to propose creating auto wait mechanism that will pause executing test script and start counting time till timeout, defined in config, if when specific element on page is detected (and selectors to find this element/elements are defined in config).

Why this is useful. Testcafe does pretty good job on auto waiting when there are proper hard reloads/path changes in browser, but in SPA apps it is not that great. We click some button, data is being loaded for quite long time before new "sub page" is ready to be displayed, there is moment with blank page, but counting time till timeout has already started. Then after for example 20s we are on "Sub page" but now we are loading more data and more elements to page and we are displaying "Loading..." element that stays there for another 20 seconds. But timeout has already passed.

Creating system to deal with it on our end would be very painful and not that prone to errors, and we would need to manually add those custom waits in many places - and obviously we don't want that, it is hell to maintain this, that's why newer frameworks have auto wait mechanisms.

### What is your Test Scenario?
```
test("can design in 3D Editor", async t => {
    await productPage.load();
    await t.click(productPage.designIn3dEditorButton);
    // Currently here there is "soft" redirect to new page (SPA app)
    // and timeout for next action
    // 1. For 10 seconds we still see old page
    // 2. For 10 seconds we see blank page 
    // 3. For 15 seconds we see "Loading..." element on page 
    //     \________ this is where I would like the new mechanism to kick in
    //               and start counting new timeout until this element disappears
    // 4. "Loading..." element disappears
    // 5. Now i want the test to resume
    await t.click(editor3dPage.addPhotoButton);
    await uploadPhoto();
    // 1. For 5 seconds we see "Loading..." element on page
    //     \________ this is where I would like the new mechanism to kick in
    //               and start counting new timeout until this element disappears
    await t.click(editor3dPage.addToCartButton);
});
```

### What are you suggesting?
```
{
    "specs": "/Users/mastah/programowanie/packhelp/packhelp/e2e-tests/helpers/../specs"
    "runnerSettings": {
        "cssSelectorsForAutoWait": ['[data-test-id="loading-spinner"]', '[data-test-id="loading-text"]'],
        "autoWaitSelectorsTimeout": 30000,
    }
}
```
### What alternatives have you considered?
I had this system implemented in Protractor and it was blessing! In Testcafe I am currently using obscene big timeouts in custom places adding:
```
t.hover(someElement).with({timeout: 120*1000});
```
But whenever someone changes code and there is new place that has long soft page loads (in SPA), then test fails on CI and we have to manually update this place to use extremely long timeout :(

**Comment by alexey-lin** [comment]
Hi @Evilweed,

Thank you for your suggestion. We will review it in the context of the [#1191](https://github.com/DevExpress/testcafe/issues/1191) issue. Please track it to be informed of our progress.

**Comment by Evilweed** [comment]
@alexey-lin I've read #1191 and sadly it does not refer to the same thing. In #1191 the only thing you are trying to add it to add custom wait mechanism after using `t.navigateTo()`. What I need is a custom wait mechanism that stops test execution any time during test there is some element visible/in dom on page. That means, not only after page load, but between any step. We have SPA app, and there are many moments where we display loading spinners and it is just painful to add some custom code waits in all of those places. :<

**Comment by wentwrong** [comment]
The #1191 thread contains a detailed discussion with multiple valuable ideas. One of them is to specify custom conditions when the page should be marked as ready for the built-in wait mechanism. We have changed the title of the issue to be less confusing. I suggest moving our discussion regarding your case to #1191, because it may be helpful for other users.
