### ISSUE TITLE
load testing with real browsers[not HTTP based load testing like Jmeter]

### ISSUE THREAD

**Issue by rajeshshettysrs** [DevExpress/testcafe#5407]
### What is your Test Scenario?
Recently we are using testcafe for end to end testing,But we have one Scenario like 10 or 100 different users logins simultaniously[parallelly] to our website and each user uploads different excel files.Is it possible to acheive is testcafe?

### What are you suggesting?
New to testcafe

### What alternatives have you considered?
we are planning to use Flood element for above scenario

### Additional context
New to testcafe

**Comment by AlexSkorkin** [comment]
TestCafe was not designed for load testing so, unfortunately, this task cannot be accomplished with it.

**Comment by rajeshshettysrs** [comment]
thank you very much for clarification
