### ISSUE TITLE
Chrome window randomly re-sizing when running multiple tests

### ISSUE THREAD

**Issue by claudyunosquare** [DevExpress/testcafe#5410]
Hey guys,

So ever since the release of 1.9.0 I have been experiencing failures while running multiple tests, when I go into my test report with failure screenshots it shows that the browser has been re-sized to be smaller leading to my tests not being able to pick up elements on the page. Also in the before each hooks we specify ` await t.maximizeWindow();`

When I revert back to 1.8 the issues do not occur.

Steps to reproduce

1. So far the best repo steps I can give is run 40 tests concurrently via jenkins

Expected behavior 
Tests pass as they did before grabbing the latest testcafe version

Actually behavior 
Tests fail at random points, screenshot folder showing that only a quarter of the screen is visible
 
Environment details with bug:
 
* testcafe version:                   `1.9.0`
* node.js version:                    `2.14.1`
* command-line arguments:  `testcafe --hostname localhost chrome enable-dotenv.test.js tests/**/**/*.js -c 3 -S -s screenshots --test-meta testTag=regression-test --skip-js-errors json:report.json",`
* browser name and version: `Chrome 84.0.4147.105`
* platform and version:          `macOS 10.13.6`

Environment details when bug does not occur:
 
* testcafe version:                   `1.8.7`
* node.js version:                    `2.14.1`
* command-line arguments:  `testcafe --hostname localhost chrome enable-dotenv.test.js tests/**/**/*.js -c 3 -S -s screenshots --test-meta testTag=regression-test --skip-js-errors json:report.json",`
* browser name and version: `Chrome 84.0.4147.105`
* platform and version:          `macOS 10.13.6`

I know the repo steps are a bit vague at the moment, I will investigate this further and add to this ticket. Thanks for reading guys.

**Comment by Dmitry-Ostashev** [comment]
Hello,

Thank you for your report. I was unable though to reproduce the issue on my Win10 machine by using your description. Looking forward to further details from you.
