### ISSUE TITLE
Multiple browser window sample test does not work in TypeScript

### ISSUE THREAD

**Issue by ayemelyanenko-chegg** [DevExpress/testcafe#5411]
### Are you requesting a feature or reporting a bug?

Reporting a bug

### What is your Test Scenario?

Trying to run an example multiple browser window test in typescript

### What is the Current behavior?

Test run fails with properties not existing on type TestController
**Running the same test using JavaScript works fine, attaching screenshots. Other tests using TS also run fine, just this attempt at multiple browser windows fails**
<img width="570" alt="Screen Shot 2020-08-10 at 12 20 28 PM" src="https://user-images.githubusercontent.com/14633459/89822789-33e22700-db05-11ea-86bd-23618bc5eee3.png">

<img width="574" alt="Screen Shot 2020-08-10 at 12 21 57 PM" src="https://user-images.githubusercontent.com/14633459/89822816-3d6b8f00-db05-11ea-8c75-43137ec4b68a.png">

### What is the Expected behavior?

Expect the be able to run the test using TypeScript

### How would you reproduce the current behavior (if this is a bug)?

Create a sample TypeScript test as listed below and try and run it

#### Provide the test code and the tested page URL (if applicable)

 
Your website URL (or attach your complete example):

Your complete test code (or attach your test files)

```js
fixture `Example page`
    .page('https://example.com');

test('Switch to a specific window', async t => {
    const initialWindow = await t.getCurrentWindow();
    const popUp1        = await t.openWindow('https://devexpress.com');
    const popUp2        = await t.openWindow('https://github.com');

    await t.switchToWindow(initialWindow);

    const url = t.eval(() => document.documentURI);

    await t.expect(url).eql('https://example.com/');

    await t
        .switchToWindow(popUp2)
        .expect(url).eql('https://www.github.com');
});
```
### Your Environment details:
 
* testcafe version:                    1.9.0
* node.js version:                     10.15.3
* command-line arguments:   yarn testcafe chrome ./fetests/multipleBrowser.ts --allow-multiple-windows
* browser name and version:  Chrome 84.0.4147.105
* platform and version:           macOs 10.15.6
* other:

**Comment by AndreyBelym** [comment]
Thank you for your report. I cannot reproduce the issue. It's likely that your TestCafe installation is not completed. I suggest you remove your `node_modules`, clean the Yarn/npm cache and reinstall TestCafe. Then, you can run `yarn testcafe -v` to ensure that Yarn uses the latest TestCafe version.
 
Please note that `testcafe@1.9.0` enables the window management functionality by default. If you have to use the --allow-multiple-windows switch to enable it, you are definitely running an outdated TestCafe version.

**Comment by ayemelyanenko-chegg** [comment]
Thank you for your help @AndreyBelym, doing the steps you provided above and running without the --allow-multiple-windows got it working as expected

**Comment by AndreyBelym** [comment]
Hice to know that the issue is resolved, thank you for the confirmation 👍
