### ISSUE TITLE
global requestHooks

### ISSUE THREAD

**Issue by benmonro** [DevExpress/testcafe#5412]
### What is your Test Scenario?

we have some request hooks that we would like to register globally, across all fixtures.

### What are you suggesting?

either via the test runner API or config, or something, some way to register request hooks globally across all fixtures.

### What alternatives have you considered?

adding the request hooks to each fixture (this is not ideal)

**Comment by miherlosev** [comment]
Duplicate of https://github.com/DevExpress/testcafe/issues/5364
