### ISSUE TITLE
Use packages from the latest stable Alpine release for building the Docker image

### ISSUE THREAD

**Issue by mrahman2327** [DevExpress/testcafe#5413]
### What is your Test Scenario?
I want to run all tests in latest version for Chromium. This is a follow up of #5057.
 
### What is the Current behavior?
We were able to run the tests in Chrome version 81 after issue #5057 was fixed and upgrading the version of testcafe. However, now Chromium version 84 is out but tests keep running on version 81.
 
### What is the Expected behavior?
We expected that the version of chromium should be updated automatically and we won't have to update testcafe each time to make it happen. 

What action if any we need to do from our side to keep the versions updated?

### Your Environment details:
 
* testcafe version:                   1.8.5
* node.js version:                    v13.9.0
* command-line arguments:  `chromium --headless --no-sandbox --disable-gpu' ${TEST_SUITE} --quarantine-mode`

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. Currently, our Docker image uses packages from the outdated Alpine release (v3.11). I think we can switch to the `latest-stable` Alpine repository for stable packages. I will post a comment here when a release with the updated packages is available.

As a temporary solution, you modify our Dockerfile and build your own image using the latest packages. You need to clone the repository and install dependencies with `npm install`. Then you can replace `v3.11` with `latest-stable` in the [Dockerfile](https://github.com/DevExpress/testcafe/blob/9e854f1d93ef45df437c20dd4db4263df12cdb94/docker/Dockerfile#L11) and build your own image by running `npx gulp docker-build`. 

If you want to publish your image to Docker Hub, you will need to modify the image name in the [Gulpfile](https://github.com/DevExpress/testcafe/blob/9e854f1d93ef45df437c20dd4db4263df12cdb94/Gulpfile.js#L148), login to your Docker Hub account with `docker login` and run the `npx gulp docker-publish` command.
