### ISSUE TITLE
retry logic for only failed tests 

### ISSUE THREAD

**Issue by shyedhu** [DevExpress/testcafe#5415]
### What is your Test Scenario?

As we know we have --quarantine-mode to retry test cases run , however current way took long time execution which ran more than 2 or 3 times and  i'm looking best retry logic for only failed tests with number of times, For example if i wanted to run two times for only failed tests 

### What are you suggesting?
It would be great to implement retry logic and to have retry flag like 'testcafe chrome tests/test.js --retry 2'

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. We already have a similar suggestion in our repository: https://github.com/DevExpress/testcafe/issues/3891. Please add 👍 to help us prioritize it, and use it to share your thoughts and track our progress in implementing this feature. I will close this issue as a duplicate for housekeeping purposes.
