### ISSUE TITLE
Support for Deno

### ISSUE THREAD

**Issue by devdelpiero** [DevExpress/testcafe#5419]
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. We try to keep our repository for bugs and feature suggestions only. For inquiries like this one, we suggest using [StackOverflow](https://stackoverflow.com/questions/tagged/testcafe) - an amazing platform to ask and answer questions.

Regarding the topic: I think we need to wait a little until Deno's ecosystem gets mature. Then we can decide if we should offer TestCafe to Deno users. A lot of Deno built-in APIs are different, and most of third-party modules that TestCafe uses are not available yet. Moreover, Deno's audience doesn't seem so big right now. Could you please share your personal experience with Deno, if you use it?

**Comment by devdelpiero** [comment]
One word, elegant. Testcafe needs to be the first e2e framework for Deno!

**Comment by miherlosev** [comment]
I agree with @AndreyBelym that Deno's ecosystem and community are very small now.
We can track user interest in this functionality. Add the 'thumb up' reaction if you are interested in this feature.

Also, I see that the tools for migrating the Node.js modules to the Deno platform (for example, [denoify](https://github.com/garronej/denoify)) are starting to appear in NPM. You can try to use them.

**Comment by andreespirela** [comment]
Is there any progress on this? At least any further discussion on whether it will be added at some point?. What would the implications to support testcafe be?
- External packages testcafe uses
- Internal technologies testcafe requires

I'll be happy to collaborate in the transition of a first beta version of Testcafe in Deno.

**Comment by miherlosev** [comment]
Hi @andreespirela
At present, we just track customer interest in the `Deno` support. We are currently focused on features from our [roadmap](https://devexpress.github.io/testcafe/roadmap/). You can try to create a TestCafe package for Deno yourself.
