### ISSUE TITLE
improperly behaviour of window.getSelection().getRangeAt(0) 

### ISSUE THREAD

**Issue by deringwer** [DevExpress/testcafe#5420]
### What is your Test Scenario?
Getting a selection of characters after focusing out by Tab key
 
### What is the Current behavior?
Does'not return a selection after focusing out
 
### What is the Expected behavior?
Should return a selected value after focusing out
 
### What is your web application and your TestCafe test code?
**Web app code:** 

```
<div contenteditable="true">Sample Text</div>
<button>Button to focus</button>
```

**TestCafe code:**
`
window.getSelection().getRangeAt(0)
`

### Steps to Reproduce:

1. Run web app code
2. Select a few characters by CTRL
3. Press Tab key to unfocus
4. Run TestCafe code to get a currently selected characters
 
### Your Environment details:
 
* testcafe version: 1.8.2                
* node.js version: 10.18.1                  
* browser name and version: Chrome 84, Edge 84, Safari 13.1

* platform and version: macOS, Windows

**Comment by Farfurix** [comment]
@kukuhaha 

Hello,

> testcafe version: 1.8.2

Please, update your version to the latest `v1.9.1`.

I suppose you tried to return the `Range` object from `ClientFunction`. As a workaround, you can use the following example based on [this comment](https://github.com/DevExpress/testcafe/issues/3546#issuecomment-471503749):
**index.html**
```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<div id="div" contenteditable="true">Sample Text</div>
<button id="btn">Button to focus</button>
</body>
</html>
```

**test.js**
```js
import { ClientFunction } from 'testcafe';

fixture `Fixture`
    .page `./index.html`;

const getSelectionRange = async t => JSON.parse(await t.eval(() => {
    const { startOffset, endOffset, collapsed } = window.getSelection().getRangeAt(0);

    return JSON.stringify({ startOffset, endOffset });
}));

const focusOnButton = ClientFunction(() => {
    document.getElementById('btn').focus();
});

test('test', async t => {
    await t
        .selectText('#div', 2, 8)

    await focusOnButton();

    const expectedRange = {
        startOffset: 2,
        endOffset:   8
    }

    await t
        .expect(await getSelectionRange(t)).eql(expectedRange);
});
```

Result:
```
>testcafe chrome test.js
 Running tests in:
 - Chrome 84.0.4147.125 / Windows 10

 Fixture
 √ test


 1 passed (1s)
```
