### ISSUE TITLE
Ability to log stdout and stderr of tested-app (appCommand child process) 

### ISSUE THREAD

**Issue by kubejm** [DevExpress/testcafe#5423]
The ability to view the stdout and stderr of the test-app (appCommand child process) would provide value for debugging the application under test, especially in the case where the appCommand exits due to failure.  At the moment, the implementation rejects with the error at exit and effectively swallows the logs.  The output leading up to the appCommand failure would provide value in debugging.

### What is your Test Scenario?
The test-app (appCommand) fails on start-up or during execution.

### What are you suggesting?
Introducing configuration to allow for the ability to log the stdout and/or stderr of the test-app (appCommand child process).  The configuration would be used as flags for logging the stdout and stderr on the callback (3rd parameter) of the exec invocation for producing/running the appCommand.

The following code in particular:
https://github.com/DevExpress/testcafe/blob/master/src/runner/tested-app.ts#L49-L55

I can work to contribute this if there is appetite for it.

### What alternatives have you considered?
Adjusting the application code to write to disk or running the application under test outside of testcafe.  However, these solutions seem like unfavorable workarounds.

**Comment by alexey-lin** [comment]
Hi @kubejm,

Thank you for your suggestion. I believe, this is a good idea. Of course, your contribution will be highly appreciated! Also, you can use `debuggerLog` like [here](https://github.com/DevExpress/testcafe/blob/f1d3ae38eedbd2b7e43869971c3705d76bb7fc36/src/video-recorder/process.js#L115) to prevent test-app log from being swallowed.

By the way, TestCafe already has the [`--dev` option](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#--dev). What do you think about using it instead of introducing a new one? Too many options may be inconvenient to use and difficult to maintain.

**Comment by kubejm** [comment]
Hi @alexey-lin,

No problem and that's good to hear.

Thank you for the suggestions and I definitely agree about not trying to introduce other options if one fits the bill already.  I'll try to toss a PR together shortly and provide an update as I make progress.

Thanks!

**Comment by kubejm** [comment]
I'll have a PR submitted shortly.

After taking a stab at it, I no longer think this will require an additional flag based on your suggestion of using the `debug` package (e.g. `debugLogger`).  The utilization of the `DEBUG` environment variable can serve as the guard for invoking this logic.  It does not appear that the `--dev` flag is being utilized to guard other `debug` invocations and seems to be use for asset loading (such as the spinner).

However, I would be interested to hear your thoughts and would be happy to adjust.

**Comment by miherlosev** [comment]
Hi @kubejm 

Thank you for your contribution in TestCafe. We will review your PR.

**Comment by kubejm** [comment]
Hi @miherlosev,

Thanks for taking a look!  Let me know if I can do anything to assist further.

**Comment by AndreyBelym** [comment]
Thank you for using and contributing to TestCafe.

**Comment by kubejm** [comment]
No problem!  Thank you for helping and working this through.
