### ISSUE TITLE
t.getBrowserConsoleMessages method returning a string instead of an object

### ISSUE THREAD

**Issue by sharmaji-coder** [DevExpress/testcafe#5424]
TestCafe v: 1.8.4
Steps: 
We have an object logged in the client console.
So, we try to get the log from the console using t.getBrowserConsoleMessages()
`const { log } = await t.getBrowserConsoleMessages();`
On printing `testLog` value, we are getting `[ ' [object Object]' ]`

But what we expect an object that contains:
`{ p1:"www" ,p2:"xxx" ,p3:"yyy" }
p2:"xxx
p1:"www"
p3:"yyy
__proto__:Object`

![Screen Shot 2020-08-14 at 4 48 12 pm](https://user-images.githubusercontent.com/69667036/90223719-ee4d9300-de51-11ea-869d-03b69016e264.png)

**Comment by miherlosev** [comment]
Hi @sharmaji-coder 
 
The `getBrowserConsoleMessages()` function returns the result with another signature.

```js
const { error, warn, log, infor } = await t.getBrowserConsoleMessages();
```

 
Try to change the test code. If the problem exists, try to run your tests with the latest TestCafe version (`1.9.1`).

If these actions don't fix the problem, could you please share a simple example that can be reproduced on our side?

**Comment by sharmaji-coder** [comment]
Sorry, it was a typo. was using `log`. Updated the question

**Comment by miherlosev** [comment]
At present, TestCafe has no support for capturing the console messages with the `object` type. Track a #5425 issue to be informed about our progress.
If it's possible, try to add the `JSON.stringify` call for all complex console messages on the client-side and parse the strings in the test using the `JSON.parse` function.
