### ISSUE TITLE
The 'TestCafe could not find the test file' error occurs when a file name contains brackets

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe#5426]
### What is your Test Scenario?
Run a test file with the name containing brackets.
 
### What is the Current behavior?
The following error occurs:
`TestCafe could not find the test file`
 
### What is the Expected behavior?
Tests should be launched without errors.
 
### What is your web application and your TestCafe test code?
A file named, for example, `test (test).js`
 
<summary>Your complete test report:</summary>

```
ERROR TestCafe could not find the test files that match the following patterns:
test (test).js
```

### Steps to Reproduce:
`npx testcafe chromium *.js`
 
### Your Environment details:
 
* testcafe version:                   v1.9.1;
* node.js version:                    v12.x.x;
* command-line arguments:  `npx testcafe chromium *.js`;
* browser name and version: Chromium;
* platform and version:          Win10, Ubuntu;

**Comment by Campaio** [comment]
hello there, I'm facing the same issue, where testcafe fails on executing a file that contains parenthesis, any updates on this? this is the console output I get
`ERROR TestCafe could not find the test files that match the following patterns:
C:\Users\myUser\tests\blank_test().ts

The "C:\myTestCafeProject" current working directory was used as the base path.
Ensure the file patterns are correct or change the current working directory.
For more information on how to specify test files, see https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#file-pathglob-pattern.`

Note files don't contain parenthesis in their name are executed with no issue.

**Comment by miherlosev** [comment]
Hi @Campaio,

Run the tests using the latest TestCafe version – `3.0.0`. If the issue still occurs, please create a separate issue with all the information that is required to reproduce issue locally, such as test files, screenshot of the terminal, and so on.
