### ISSUE TITLE
Browser not invoking through testcafe command

### ISSUE THREAD

**Issue by anujkesarwani** [DevExpress/testcafe#5427]
### Are you requesting a feature or reporting a bug?
Bug

### What is your Test Scenario?
I installed node.js then I installed testcafe globally. Everything successfully installed but when I try to run any script using testcafe command 'testcafe chrome tests/', it does not work. The testcafe cursor keeps on rotating and no browser is ever invoked. It also does not throws any error.
My node version is 12.18.3
My npm version is 6.14.7
I used 'npm install -g testcafe' to install testcafe
My testcafe version is 1.9.1

Please help. I am kind of new to this platform so little detailed explanation would be helpful.

### What is the Current behavior?
The browser is not invoking on executing js script through testcafe command. It shows endless loading

### What is the Expected behavior?
The browser should invoke and test should run.

#### Provide the test code and the tested page URL (if applicable)

 
Your website URL (or attach your complete example):

Your complete test code (or attach your test files)

```js

```
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by wentwrong** [comment]
This information is not sufficient to reproduce the issue on our side. Would you please share your test code? Can you run tests in another browser? A video demonstrating the issue can be also very helpful.
