### ISSUE TITLE
Allow switching to parent iframe

### ISSUE THREAD

**Issue by tourdedave** [DevExpress/testcafe#5429]
### What is your Test Scenario?
Walk into a nested frame, and then access the parent frame without knowing the explicit selector for it.
 
### What is the Current behavior?
Getting an element not visible error.
 
### What is the Expected behavior?
TestCafe should switch into the parent frame.
 
### Reproducer

```js
const assert = require('assert')
const {Selector} = require('testcafe')

fixture`Nested Frames`.page`https://applitools.github.io/demo/TestPages/FramesTestPage/`

test('walk nested frame tree', async driver => {
    await driver.switchToIframe('[name="frame1"]')
    const parentDocument = await Selector('html')()
    await driver.switchToIframe('[name="frame1-1"]')
    const frameDocument = await Selector('html')()
    await driver.switchToIframe(frameDocument.selector.parent(0))
})
```

```sh
 Nested Frames
 ✖ walk nested frame tree

   1) The element that matches the specified selector is not visible.

      Browser: Chrome 84.0.4147.125 / macOS 10.15.5

          6 |test('walk nested frame tree', async driver => {
          7 |    await driver.switchToIframe('[name="frame1"]')
          8 |    const parentDocument = await Selector('html')()
          9 |    await driver.switchToIframe('[name="frame1-1"]')
         10 |    const frameDocument = await Selector('html')()
       > 11 |    await driver.switchToIframe(frameDocument.selector.parent(0))
         12 |})
         13 |
```

### Steps to Reproduce:

1. Unzip the [repro.zip](https://github.com/DevExpress/testcafe/files/5085044/repro.zip) file
2. `npm i`
3. `npm t`
 
### Your Environment details:
 
* testcafe version:                   `1.9.1`
* node.js version:                    `12.18.3`
* command-line arguments:  `chrome:headless ./example.spec.js`
* browser name and version: `Chrome 84.0.4147.125`
* platform and version:           `macOS 10.15.5`

**Comment by miherlosev** [comment]
Hi @tourdedave 
 
At present, it possible to switch into the parent iframe window only using the following approach: `switch to main window` -> `navigate to target iframe`.
I believe the `switchToIframeParentWindow` method can be useful for your case. I will mark this issue as enhancement.
