### ISSUE TITLE
Testcafe doesn't finish running after opening a new page in an iframe

### ISSUE THREAD

**Issue by MatiasFB** [DevExpress/testcafe#5430]
THIS BUG IS STILL HAPPENING: https://github.com/DevExpress/testcafe/issues/2515
Are you requesting a feature or reporting a bug?
Bug

What is the current behavior?
Testcafe keeps hanging idle during a test after clicking a link that opens a new tab with javascript

What is the expected behavior?
Testcafe should exit and report tests.

How would you reproduce the current behavior (if this is a bug)?
Have a button in an iframe that redirects or opens a new page.
This is the iframe.html file:

<script>
  function openUrl () {
    window.open('https://www.google.com');
  }
</script>

<a href="#" id="button" onclick="openUrl()">Google link</a>
Then have testcafe click it. It will stop working (without throwing any errors).

Provide the test code and the tested page URL (if applicable)
Tested page URL: https://horsetoast.github.io/testcafe-button-problem/

Test code

import { ClientFunction, Selector } from 'testcafe';

fixture`Testcafe redirect bug`.page(
  `https://horsetoast.github.io/testcafe-button-problem/`
);

test('Click a button in iframe and redirect', async t => {

  const iframe = Selector('#iframe');
  const button = Selector('#button');
  await t
    .switchToIframe(iframe)
    .click(button)
});
here is my github repo with the problem
https://github.com/Horsetoast/testcafe-button-problem

**Comment by Ogurecher** [comment]
Hello @MatiasFB,
Thank you for your report. I've reproduced this issue with TestCafe version 0.20.3 included in the example repo. However, the example works as expected with TestCafe 1.9.1.

To fix this issue, you can update TestCafe to the latest version. The fix involves the new [multi-windows feature](https://github.com/DevExpress/testcafe/issues/912) which is currently in beta.

**Comment by MatiasFB** [comment]
I am having the same exactly issue with with TestCafe 1.9.1.
Try to switch to the main windows after click on the button, and the test will be paused unexpectedly.
await t
.switchToIframe(iframe)
.click(button)
.switchToMainWindow();

**Comment by Ogurecher** [comment]
@MatiasFB, I've modified the example as you suggested, but I still can't reproduce the issue on TestCafe 1.9.1.

Please delete the `node_modules` folder and the `package-lock.json` file and then run `npm remove testcafe` and `npm install testcafe` to verify the installation.

If this does not resolve the issue, please share the following details:
1) OS name and version
2) Node version (run `node -v`)
3) TestCafe version (run `testcafe -v`)
4) Browser name and version
5) Your tested page in case you've modified the page from the example repo
6) Your test code
7) Command-line arguments you pass to run the test

**Comment by MatiasFB** [comment]
The bug is still happening, we were dealing with a lot of iframes but here is happening something weird.
1-macOs Catalina - version 10.15.6
2- v12.18.1
3- 1.9.1
4-Chrome Version 84.0.4147.105 (64-bit)
6-  `async selectAssetFromAssetAndWarrantySection() {
        await t
        .switchToIframe(this.iFrameCaseDetails)
        .click(this.assetSelectLink)
        .switchToMainWindow();
    }`
The click is done but it is paused when it try  .switchToMainWindow();
7- node ./Runners/caferun.js
`const createTestCafe = require('gherkin-testcafe');
let testcafe = null;

createTestCafe()
    .then(tc => {
        testcafe = tc;
        const runner = testcafe.createRunner();

        return runner
            .src(['./StepDefinitions/login.js', './FeatureFiles/login.feature'])
            .browsers(['chrome'])
            .run({
                debugMode: true,
                 assertionTimeout: 20000,  
                 selectorTimeout: 20000,
                 pageLoadTimeout: 20000           
            });
    })
    .then(failedCount => {
        console.log('Tests failed: ' + failedCount);
        testcafe.close();
    });`

**Comment by Ogurecher** [comment]
@MatiasFB, Thank you for sharing additional details. This code is different from that in the example you previously shared. Does the example from [the repository you shared](https://github.com/Horsetoast/testcafe-button-problem) work for you after TestCafe was updated to v1.9.1?

We need a complete example that we can run on our side to reproduce this issue. If [the example you initially shared](https://github.com/Horsetoast/testcafe-button-problem) works as expected, please share another repository that demonstrates this issue.
