### ISSUE TITLE
typeOf and notTypeOf assertions don't have the null type to check against

### ISSUE THREAD

**Issue by Vla8islav** [DevExpress/testcafe#5446]
Here https://devexpress.github.io/testcafe/documentation/reference/test-api/testcontroller/expect/typeof.html we have this example:

await t
    .expect({ a: 'bar' }).typeOf('object', 'it\'s an object')
    .expect(/bar/).typeOf('regexp', 'it\'s a regular expression')
    .expect(null).typeOf('null', 'it\'s a null');

but if you try to execute 

> await t.expect(null).typeOf('null', 'it\'s a null');

you will get an error since null is not an option in the type list:

https://github.com/DevExpress/testcafe/blob/bfd8985cf30b8a9f97d496afe5f89c07a7ae1842/ts-defs-src/test-api/assertions.d.ts#L121
>            typeOf(typeName: 'function' | 'object' | 'number' | 'string' | 'boolean' | 'undefined' | 'regex', message?: string, options?: AssertionOptions): TestControllerPromise;

either remove null from the example or add null to typeOf and notTypeOf

>             typeOf(typeName: 'function' | 'object' | 'number' | 'string' | 'boolean' | 'undefined' | 'regex' | 'null', message?: string, options?: AssertionOptions): TestControllerPromise;

**Comment by Ogurecher** [comment]
@Vla8islav,

Thank you for your report. I've reproduced this issue. We'll appreciate your contribution in updating these type definitions. Please see our [contribution guide](https://github.com/DevExpress/testcafe/blob/master/CONTRIBUTING.md#code-contribution).

**Comment by Vla8islav** [comment]
https://github.com/DevExpress/testcafe/pull/5456
created the pull request. I think that linking an issue is not available to me.

**Comment by Ogurecher** [comment]
@Vla8islav, Thank you for your contribution. We've merged your pull requests and will add these type definitions with the next version.
