### ISSUE TITLE
Snapshot property warnings work incorrectly with helper functions

### ISSUE THREAD

**Issue by Ogurecher** [DevExpress/testcafe#5449]
Using the example code from @Ogurecher I also get the warnings, despite them not being prefixed by `await`. 

I am honestly baffled how a super hacky method like checking line numbers ever got merged. Not least because autoformatters such as Prettier will force the expect and selector to be on the same line in most cases. Adding a warning of this kind is fine but not with this implementation. I have made a hacky fix by putting my selectors on different lines for now but I hope this is changed in a future release.

Regardless, for me personally it is failing even with selector and expect on the same line and I've forked @Ogurecher 's sample repo and made a reproducable sample: https://github.com/favna/warning-example
Simply run `npm run test` to run testcafe here

_Originally posted by @Favna in https://github.com/DevExpress/testcafe/pull/5250#issuecomment-678322252_

**Comment by Ogurecher** [comment]
@Favna, Thank you for the example. I've reproduced the issue on my side.

**Comment by Favna** [comment]
Thanks for migrating my comment to an issue and trying my sample. Looking forward to see progress here.

**Comment by xorxero** [comment]
Can this be solved already? 

Makes looking through logs a nightmare I have to scroll thousands of lines of this useless warning to find what actually failed. 

At least give an option to disable the warning.

**Comment by AndreyBelym** [comment]
I set the critical status for this issue. We are trying to find a solution as soon as possible, stay tuned for updates.

**Comment by Ogurecher** [comment]
https://github.com/DevExpress/testcafe/issues/5389#issuecomment-698184934

**Comment by Khartir** [comment]
@xorxero: I just stumbled upon this issue. A workaround is described [here](https://github.com/DevExpress/testcafe/pull/5250#issuecomment-678322252)

**Comment by Ogurecher** [comment]
For the team:
This issue is caused by the same reason as #5389.

When the snapshot property promise is resolved, its callsite is saved to a callsite storage. We check this storage in the `.expect` assertion call. If the storage contains a callsite with the same `filename` and `lineNumber` as the `.expect`'s callsite, we delete it and raise a warning.

If the property was not awaited, the `.expect` would execute before the property promise's `.then` method. Thus, some callsites would remain in the storage after they were asserted (we delete them only in `.expect`). It works fine if we use our assertion only once, but causes the warnings to raise if we call `.expect` from the same line of code again.

**Comment by kflore16** [comment]
Hello I have a helper class with a method that asserts a few things and this helper class extends a different helper class because it uses some of its functions.
```javascript
async fillField(field) {
    let fieldSelector = await this.getInputSelector(
      field.fieldType,
      field.fieldKey
    )
    await t
      .expect(fieldSelector.textContent) //this flags the warning
      .notContains(field.name, { timeout: 20000 })
     //More stuff
```
raises that warning above.
The structure of the logic is that (inherited).getInputSelector(value,value) uses that value to determine the function to be used then returns the Selector passed by the other function thus resulting in a chain of await's per function reference like so:
```javascript
targetSelector = await getInputSelector(string data, returns the Selector returned from next function) -> await getTypeSelector(string data, returns the Selector returned from next function) -> await fieldTypeSelector(string data and returns the selector)
```
It is not the case that at each return the data is wrapped in Selector() as it only gets returned as a Selector from fieldTypeSelector() function propogated downward.

TestCafe version 1.16.1

**Comment by AlexKamaev** [comment]
@kflore16
This issue is closed. Please create a separate [issue](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&template=bug_report.yaml) and share an example that we can run without any additional setup.
