### ISSUE TITLE
TestCafe is having trouble finding elements after selecting a bottom element in a long dropdown

### ISSUE THREAD

**Issue by raj-balaebail** [DevExpress/testcafe#5451]
### What is your Test Scenario?
Type in to a field after selecting a long dropdown and verify form errors
 
### What is the Current behavior?
After selecting a value which is towards the bottom from a long dropdown, TestCafe is having trouble finding the next field. I see that the bottom of the text field is partially visible, and it looks like TestCafe is trying to scroll up but fails. I see testcafe assertion bar at the bottom flashing green continuously till it times out. If I manually scroll up as the test is running it works as expected.

Note that selecting a value from the top of the dropdown or tabbing out of the field both avoid the issue.
 
### What is the Expected behavior?
Selecting any value regardless of where it is in the dropdown should find the next element on the page successfully. 
 
### What is your web application and your TestCafe test code?

The web application is behind a firewall. Attaching the test code below.
 
Adding `.pressKey('tab')` after the dropdown or selecting a value from the top of the dropdown make the page behave correctly. In addition, if I manually scroll as the test is running, it finds the element. 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
import { t, Selector } from 'testcafe';

fixture("Dropdown bug")
  .page('https://asdf')

test('Reproduce dropdown bug', async t => {
  //await pAPage.clickElement(pAPage.fillButton)
  await t
    .click(Selector('[for=citizenship_is_us_citizen_false]'))
    .click(Selector('#citizenship_country'))
    .click(Selector('#citizenship_country').find('option').withText('RAWANDA'))
    .typeText(Selector('#identification_foreign_passport_identification_number'), '111111', { replace: true })
    .click(Selector('button').withText('Check Loan Options'))
    .expect(Selector('*').innerText).contains('The ID # entered is invalid. Please update to a valid number.')
})
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```
![Screen Shot 2020-08-24 at 9 22 08 AM](https://user-images.githubusercontent.com/66964979/91057073-5fc4d880-e5ec-11ea-88f3-1837a25837fa.png)

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by raj-balaebail** [comment]
![Screen Shot 2020-08-24 at 9 22 08 AM](https://user-images.githubusercontent.com/66964979/91056440-9817e700-e5eb-11ea-9c40-75df6434d148.png)

**Comment by raj-balaebail** [comment]
![Screen Shot 2020-08-24 at 9 22 08 AM](https://user-images.githubusercontent.com/66964979/91057095-65222300-e5ec-11ea-99ff-a1a423924235.png)

**Comment by Dmitry-Ostashev** [comment]
I was trying to reproduce this behavior with a similar drop-down component from the DevExtreme demo page. The following test code works as expected:

```
import { Selector } from 'testcafe';

fixture `Drop-Down`
    .page `https://js.devexpress.com/Demos/WidgetsGallery/Demo/DropDownBox/SingleSelection/jQuery/Light/`;

test('Test', async t => {
    await t
        .resizeWindow(1048, 572)
        .switchToIframe('#demoFrame')
        .click('#treeBox .dx-dropdowneditor-icon')
        .debug()
        //Scroll the page manually to reproduce the issue
        .click(Selector('div').withText('Projectors').nth(9));
});
```

Could you please share a simple page with such a drop-down or a markup snippet so that we can research this issue locally?

**Comment by raj-balaebail** [comment]
@Dmitry-Ostashev Thank you for getting back to me. I can reproduce this on a publicly accessible website. 
`import { t, Selector } from 'testcafe';

fixture("Dropdown bug")
  .page('https://avant.com/apply')

test('Reproduce dropdown bug', async t => {
  //await pAPage.clickElement(pAPage.fillButton)
  await t
    .click(Selector('#person_date_of_birth_year'))
    .click(Selector('#person_date_of_birth_year').find('option').withText('1921'))
    .typeText(Selector('#person_home_phone'), '1111111', { replace: true })
    .click(Selector('button').withText('Agree and Check Your Loan Options'))
    .expect(Selector('*').innerText).contains('Please fill in your phone number.')
})`

**Comment by Dmitry-Ostashev** [comment]
Thank you for your test example. I reproduced this behavior. As I can see on this page, the target element is hovered by the page header with a large z-index. TestCafe tries to click on the top element and type text there.
I suggest you specify offsetX and offsetY options to click exactly on the target element to focus it and make it possible to type text there.

We'll research the cause of this behavior and update this ticket once we have any news to share.

**Comment by raj-balaebail** [comment]
@Dmitry-Ostashev any update on this issue ?

**Comment by AlexSkorkin** [comment]
Once we get any results, we will share them here.
