### ISSUE TITLE
Unable to access an internal endpoint through TestCafe UI automation tool

### ISSUE THREAD

**Issue by FixIt101** [DevExpress/testcafe#5460]
### What is your Test Scenario?
Im trying to click a button and move to a new page
 
### What is the Current behavior?
Upon clicking the button, expected url doesn’t load but results in ‘about:error'.
 
### What is the Expected behavior?
User should be taken to appropriate URL/page
 
### Your Environment details:
 
* testcafe version:                   1.8.4
* node.js version:                    v12.14.1
* browser name and version: All browsers latest version
* platform and version:          macOS 10.14.6, Windows

**Comment by Farfurix** [comment]
@FixIt101 

Hello,

This information is not sufficient to reproduce the issue. Could you please share some project (or a public URL with a test) with us?
