### ISSUE TITLE
ClientFunctions fail when transpiling with Babel

### ISSUE THREAD

**Issue by xorxero** [DevExpress/testcafe#5461]
Basically using babel to compile my testcafe project and when I then run, I have some tests that fail and looks like the ClientFunction names are changed and it can't find it or something.

I'll update this with more info on how to re-create the problem when I have time, right now just posting this if anyone has a clue what I'm talking about.

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. We look forward to a sample or any other update on this. Could you please also fill up the [bug report template](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md) once you attach your example?

Please note that you cannot use closures and other variables from outer scopes declared outside the ClientFunction body. You can use `options.dependencies` instead:  https://devexpress.github.io/testcafe/documentation/reference/test-api/clientfunction/constructor.html#optionsdependencies
