### ISSUE TITLE
JS error which is present only under testcafe: ReferenceError: caches is not defined

### ISSUE THREAD

**Issue by nonkor** [DevExpress/testcafe#5467]
### What is your Test Scenario?
It's about opening quiz details for editing. 
 
### What is the Current behavior?
Test fails with:

```
      JavaScript error details:
      ReferenceError: caches is not defined
          at https://dev.qubl.tech/instance-bundle:43:194609
          at Object.Ii.t.$$.update (https://dev.qubl.tech/instance-bundle:43:194782)
          at ht (https://dev.qubl.tech/instance-bundle:2:5098)
          at new <anonymous> (https://dev.qubl.tech/instance-bundle:43:199317)
          at HTMLDocument.a.createElement (http://192.168.1.2:57990/hammerhead.js:10:13773)
          at Ka (https://dev.qubl.tech/static/js/17.e3ffef77.chunk.js:3:778593)
          at lu (https://dev.qubl.tech/static/js/17.e3ffef77.chunk.js:3:800123)
          at cu (https://dev.qubl.tech/static/js/17.e3ffef77.chunk.js:3:800011)
          at su (https://dev.qubl.tech/static/js/17.e3ffef77.chunk.js:3:799864)
          at Js (https://dev.qubl.tech/static/js/17.e3ffef77.chunk.js:3:796873)
```

But there is no real js error in network tab in chrome if you open this page without testcafe
 
### What is the Expected behavior?
Test continues
 
### What is your web application and your TestCafe test code?
 
<details>
<summary>Your website URL (or attach your complete example):</summary>

https://dev.qubl.tech/
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>
```
fixture("Quiz Instance")
  .page("https://output.jsbin.com/devuluh")
  .beforeEach(async t => {
    await t.maximizeWindow();
  });
test("Quiz Instance - dropdown test", async t => {
  await t.debug()
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>
```
{
    "screenshots": {
        "path": "./screenshots",
        "pathPattern": "${DATE}_${TIME}/${FIXTURE}-${TEST}/${USERAGENT}/${FILE_INDEX}.png",
        "takeOnFails": true,
        "fullPage": true
    }
}
```

</details>

<details>
<summary>Your complete test report:</summary>
❯ npx testcafe chrome test/quiz-edit-test-copy.js -t "Add a single select question"
The "filter" option from the configuration file will be ignored.
 Running tests in:
 - Chrome 85.0.4183.83 / macOS 10.15.4

 Quiz Edit
 ✖ Add a single select question (screenshots: /Users/alexmikitenko/Projects/qubl/test/ui/screenshots/2020-08-26_20-32-58/Quiz Edit-Add a single select question/Chrome_85.0.4183.83_macOS_10.15.4/errors/1.png)

   1) A JavaScript error occurred on "https://dev.qubl.tech/quiz/edit/298/questions/_singleChoice".
      Repeat test actions in the browser and check the console for errors.
      If you see this error, it means that the tested website caused it. You can fix it or disable tracking JavaScript errors in TestCafe. To do the latter, enable the "--skip-js-errors" option.
      If this error does not occur, please write a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      ReferenceError: caches is not defined
          at https://dev.qubl.tech/instance-bundle:43:194731
          at Object.Ii.t.$$.update (https://dev.qubl.tech/instance-bundle:43:194904)
          at ht (https://dev.qubl.tech/instance-bundle:2:5098)
          at new <anonymous> (https://dev.qubl.tech/instance-bundle:43:199472)
          at HTMLDocument.a.createElement (http://192.168.1.2:59805/hammerhead.js:10:13773)
          at Ka (https://dev.qubl.tech/static/js/17.e77143c9.chunk.js:3:778593)
          at lu (https://dev.qubl.tech/static/js/17.e77143c9.chunk.js:3:800123)
          at cu (https://dev.qubl.tech/static/js/17.e77143c9.chunk.js:3:800011)
          at su (https://dev.qubl.tech/static/js/17.e77143c9.chunk.js:3:799864)
          at Js (https://dev.qubl.tech/static/js/17.e77143c9.chunk.js:3:796873)

      Browser: Chrome 85.0.4183.83 / macOS 10.15.4
      Screenshot: /Users/alexmikitenko/Projects/qubl/test/ui/screenshots/2020-08-26_20-32-58/Quiz Edit-Add a single select question/Chrome_85.0.4183.83_macOS_10.15.4/errors/1.png

         124 |    await t.expect(Selector("div.node").withText(title).exists).ok();
         125 |  }
         126 |
         127 |  async addSingleSelectQuestion(title, description, preset) {
         128 |    await t.click(this.addQuestionButton);
       > 129 |    await t.click(this.singleSelectButton);
         130 |    await t
         131 |      .typeText(quizQuestionPage.questionTitleField, title, { paste: true })
         132 |      .typeText(quizQuestionPage.questionDescriptionField, description, {
         133 |        paste: true,
         134 |      })

         at <anonymous> (/Users/alexmikitenko/Projects/qubl/test/ui/pages/quiz-edit-page.js:129:13)

 1/1 failed (27s)
</details>

<details>
<summary>Screenshots:</summary>
<img src="https://user-images.githubusercontent.com/6322897/91594723-043b7780-e96b-11ea-9629-ed34d2bf1cd5.png">
</details>

### Steps to Reproduce:
1. Run test cafe without option "--skip-js-errors"
2. Navigate to quiz result webpage https://jsbin.com/devuluh
3. See js error
 
### Your Environment details:
 
* testcafe version: 1.9.1
* node.js version: v13.2.0
* command-line arguments: 
* browser name and version: Google Chrome Version 84.0.4147.135 (Official Build) (64-bit)
* platform and version:          macOS 10.15.2
* other:

**Comment by AndreyBelym** [comment]
Thank you for your report. We look forward to a sample or any other update on this. It seems that your site requires authentication to open the test page. In this case, we need the website owner's written confirmation that permits the DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes. Please attach it to your example or send it to us as a separate email. Without it, we won't have a right to use your example. A single confirmation for both #5467 and #5468 issues will be enough.

**Comment by nonkor** [comment]
@AndreyBelym I got an answer from owners and they would prefer not giving access to the quiz itself. But we add the sources here: https://output.jsbin.com/devuluh

You can run this code:
```
fixture("Quiz Instance")
  .page("https://output.jsbin.com/devuluh")
  .beforeEach(async t => {
    await t.maximizeWindow();
  });
test("Quiz Instance - dropdown test", async t => {
  await t.debug()
});
```
without `-e` parameter and catch the error. I'll update the issue description

**Comment by AndreyBelym** [comment]
Thank you for your example. I reproduced this behavior.

Your page uses the `Cache API` that requires a secure origin. Browsers consider `localhost` and SSL-enabled domains as secure origins. Thus you can use `--hostname localhost` or [setup SSL for your tests](https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/test-https-features-and-http2-websites.html#test-https-websites) to avoid the issue. I successfully fixed it on my side by using `--hostname localhost`.
