### ISSUE TITLE
Missed web components under testcafe view

### ISSUE THREAD

**Issue by nonkor** [DevExpress/testcafe#5468]
### What is your Test Scenario?
It's about opening quiz resuls for review
 
### What is the Current behavior?
Testcafe driver renders page without some web components (see screenshots)
 
### What is the Expected behavior?
Testcafe driver renders page correctly (see screenshots)
 
### What is your web application and your TestCafe test code?
 
<details>
<summary>Your website URL (or attach your complete example):</summary>

https://dev.qubl.tech/
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>
fixture("Quiz Instance")
  .page("https://output.jsbin.com/devuluh")
  .beforeEach(async t => {
    await t.maximizeWindow();
  });
test("Quiz Instance - dropdown test", async t => {
  await t.debug()
});
</details>

<details>
<summary>Your complete configuration file (if any):</summary>
```
{
    "screenshots": {
        "path": "./screenshots",
        "pathPattern": "${DATE}_${TIME}/${FIXTURE}-${TEST}/${USERAGENT}/${FILE_INDEX}.png",
        "takeOnFails": true,
        "fullPage": true
    }
}
```

</details>

<details>
<summary>Your complete test report:</summary>
See screenshots
</details>

<details>
<summary>Screenshots:</summary>
Normal view: 
<img src="https://user-images.githubusercontent.com/6322897/91595282-fa664400-e96b-11ea-9999-3c485f946e54.png">
Under testcafe:
<img src="https://user-images.githubusercontent.com/6322897/91595191-cb4fd280-e96b-11ea-8e45-a31ba54560e1.png">

</details>

### Steps to Reproduce:
1. Run test cafe with option "--skip-js-errors"
2. Navigate to quiz results webpage https://output.jsbin.com/devuluh
3. See the difference
 
### Your Environment details:
 
* testcafe version: 1.9.1
* node.js version: v13.2.0
* command-line arguments:  `--skip-js-errors`
* browser name and version: Google Chrome Version 84.0.4147.135 (Official Build) (64-bit)
* platform and version:          macOS 10.15.2
* other:

**Comment by AndreyBelym** [comment]
Thank you for your report. We look forward to a sample or any other update on this. It seems that your site requires authentication to open the test page. In this case, we need the website owner's written confirmation that permits the DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes. Please attach it to your example or send it to us as a separate email. Without it, we won't have a right to use your example. A single confirmation for both #5467 and #5468 issues will be enough.

**Comment by nonkor** [comment]
@AndreyBelym I got an answer from owners and they would prefer not giving access to the quiz itself. But we add the sources here: https://output.jsbin.com/devuluh

You can run this code:

fixture("Quiz Instance")
  .page("https://output.jsbin.com/devuluh")
  .beforeEach(async t => {
    await t.maximizeWindow();
  });
test("Quiz Instance - dropdown test", async t => {
  await t.debug()
});
with -e parameter and see the difference. I'll update the issue description

**Comment by AndreyBelym** [comment]
Thank you for your example. This behavior is caused by #5467. Once you [run tests with a secure origin](https://github.com/DevExpress/testcafe/issues/5467#issuecomment-683647816), the page renders completely.
