### ISSUE TITLE
Where do downloaded files go? Path?

### ISSUE THREAD

**Issue by xorxero** [DevExpress/testcafe#5471]
I understand this isn't a specific TestCafe question but you guys might be aware of the solution.

I'm trying to download a file and then I check if file is on the system. This works fine on my system but when I deploy it to AWS Codebuild, this test fails because it can't find the location.

Did some digging, and can't find anything. Looks like the path should be fine for all operating systems.  This is the code I'm using.

```

export async function waitForFileDownload(fpath) {
  for (let i = 0; i < 10; i++) {
    // file was downloaded, now delete it and return true;
    if (fs.existsSync(fpath)) {
      fs.unlinkSync(fpath);
      return true;
    }

    await t.wait(500);
  }

  // file was downloaded, now delete it and return true;
  if (fs.existsSync(fpath)) {
    fs.unlinkSync(fpath);
    return true;
  }

  return false;
}

export function getFileDownloadPath(filename) {
  const fpath = path.join(os.homedir(), "Downloads", filename);

  // remove if exists
  if (fs.existsSync(fpath)) fs.unlinkSync(fpath);

  return fpath;
}


test.page`${LOGIN_PAGE_URL}`("should download file", async (t) => {
  // Run this test only with the Google Chrome browser to simplify the searching of the downloaded file.
  if (t.browser.name !== "Chrome") return;
  const path = getFileDownloadPath("file.pdf");

  await t.click(Selector("#download-btn"));

  const fileDownloaded = await waitForFileDownload(path);
  await t.expect(fileDownloaded).eql(true);
});


```

**Comment by wentwrong** [comment]
The file will be saved in your default Chrome download location, which depends on the OS. The following steps can help you:

* Make sure that the default download location path exists and directory permissions are set properly.
* You can setup the `logger` object to log requests to the target file URL. After intercepting the body of the response, you can process it as you wish. Check out [this](https://stackoverflow.com/a/54308667/5114901) answer on StackOverflow.

We generally track GitHub issues for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)). If you have any questions, please ask them on [StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe). StackOverflow is an amazing platform for users to ask and answer questions: the community will see your inquiry and help you there.
