### ISSUE TITLE
Load tests using require or fs.readfile / Webpack support

### ISSUE THREAD

**Issue by xorxero** [DevExpress/testcafe#5472]
### What is your Test Scenario?

I'm using the TestCafe runner API to run my tests. Right now, I'm passing the path for it to look for test files. However, I wanted to package my entire e2e project into an executable for easy deployments using something like pkg or nexe. But they are unable to package it since it doesn't show up in the dependency tree. Nexe allows to package extra files but they can only be accessed using fs.readfile. 

Right now, its just the runner being packaged as an executable but the executable at runtime will looks for the path to the fixture/test files and those files rely on additional files, etc. So because my Runner object has no code references to any of the test files, they + any files they use get skipped. 

**This problem would also come up when you are trying to use something like Webpack or Browserify to boil all code down to a single file.**

### What are you suggesting?

Allow more flexibility in how we load tests and provide tests to the runner.src. Maybe I don't want to give a path but rather the loaded objects.

### What alternatives have you considered?

Tried using pkg and with it Testcafe can't even load properly.

### Additional context

Just want to make an executable file out of my e2e so I can deploy it easier instead of building the project on each deployment...

**Comment by wentwrong** [comment]
You cannot import TestCafe tests in external files because of two reasons:
* TestCafe defines some non-standard global functions that can be used in test files (`fixture`, `test`);
* TestCafe accept different formats of tests (`.js`,`.ts`,`.testcafe`, Legacy TestCafe v2015.1 tests);

I suggest that you configure the tool you are using to create an executable package to include resources (tests).

**Comment by xorxero** [comment]
> You cannot import TestCafe tests in external files because of two reasons:
> 
> * TestCafe defines some non-standard global functions that can be used in test files (`fixture`, `test`);
> * TestCafe accept different formats of tests (`.js`,`.ts`,`.testcafe`, Legacy TestCafe v2015.1 tests);
> 
> I suggest that you configure the tool you are using to create an executable package to include resources (tests).

Hmm. So I did configure the tool to do that, it packages the tests and says it should be available using the fs.readfile, however when I run the executable, it still expects the folder to be beside it...

Has anyone done this successfully? Using nexe because pkg throws a warning due to one of TestCafe's dependencies.
