### ISSUE TITLE
Incorrect diff for the expect.contains assertion

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#5473]
### What is your Test Scenario?
Use `expect.contains` to compare two string values.

### What is the Current behavior?
An incorrect diff shown (pay attention to the error message and the diff):
```
AssertionError: expected 'test' to include 'foo'

      + expected - actual

      -'test'
      +undefined
```
### What is the Expected behavior?
```
AssertionError: expected 'test' to include 'foo'

      + expected - actual

      -'foo'
      +'test'
``` 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 fixture`1`.page`./index.html`

test(`1`, async t => {
    await t.expect('test').contains('foo');
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

Run the test
 
### Your Environment details:
 
* testcafe version:                   v1.9.1
* node.js version:                    v14.1.0
* command-line arguments:  `testcafe chrome test.js`
* browser name and version: Chrome 84
* platform and version:          Windows 10
* other:

**Comment by wentwrong** [comment]
[t.expect.notOk](https://devexpress.github.io/testcafe/documentation/reference/test-api/testcontroller/expect/notok.html) method result shown in diff as `undefined` instead of `false`:
```
AssertionError: expected true to be falsy

      + expected - actual

      -true
      +undefined


      Browser: Chrome 84.0.4147.135 / Windows 10

         1 |fixture `Getting Started`
         2 |    .page `http://devexpress.github.io/testcafe/example`;
         3 |
         4 |test('Should be failed', async t => {
       > 5 |    await t.expect(true).notOk();
         6 |});
         7 |
```
