### ISSUE TITLE
Failing in Chrome on t.eval within iframe "Cannot read property '0' of null"

### ISSUE THREAD

**Issue by alshdavid** [DevExpress/testcafe#5478]
### What is your Test Scenario?

I have an iframe that exposes a `close` method on the `window`. This method messages the parent window and removes the iframe from the page (running `window.context.close()`).

I am using `switchToIframe` to move my context to the iframe then `t.eval` to run the close function.

I am using TypeScript and there is an HTTP server running in the background hosting the static files.

```typescript
test('Should close widget', async t => {
  await t
    .switchToIframe('iframe')

  await t.eval(() => {
    (window as any).context.close()
  })
});
```
 
### What is the Current behavior?
Under Chrome, the test runner fails with:

```
 ✖ Should load widget

   1) TypeError: Cannot read property '0' of null

      Browser: Chrome 85.0.4183.83 / Windows 10

         266 |        this._handlePlainObject(val);
         267 |};
         268 |
         269 |DecodingTransformer.prototype.transform = function () {
         270 |    this.visitedRefs[0] = true;
       > 271 |    this._handleValue(this.references[0], this.references, 0);
         272 |
         273 |    return this.references[0];
         274 |};
         275 |
         276 |

         at DecodingTransformer.transform (/home/alshdavid/Development/project/node_modules/replicator/index.js:271:38)
         at module.exports.Replicator.decode (/home/alshdavid/Development/project/node_modules/replicator/index.js:559:24)
```

I have tested with Firefox and it works without crashing.
 
### What is the Expected behavior?
To evaluate the code and continue execution
 
### What is your web application and your TestCafe test code?
It's a private work-related repository so I cannot provide source code to it, sadly. It is however simply a top level page with an iframe. The iframe has a method `close` exposed on the window which closes the iframe.

Could it be that when closing the iframe, we are losing the testing context and that is causing the test to fail?
 
### Your Environment details:
 
* testcafe version:                   1.9.1
* node.js version:                    14.9.0 
* command-line arguments:  `npx testcafe remote ./tests --ts-config-path ./tsconfig.json`
* browser name and version: Chrome 85 and Firefox
* platform and version:          Windows (under WSL2 Debian)
* other:                                   I am using the remote URL to connect to testcafe

**Comment by alshdavid** [comment]
Placing the command in a `setTimeout` allows me to proceed without crashing the test runner in Chrome

```typescript
test('Should close widget', async t => {
  await t
    .switchToIframe('iframe')

  await t.eval(() => {
    setTimeout(() =>  (window as any).context.close())
  })
});
```

**Comment by alexey-lin** [comment]
Hi @alshdavid,

I'm happy to hear that you managed to resolve the issue. Still, it'd be good to understand what caused it. Could you please help us reproduce the error? Since your project is private, maybe you could give us a simple project that demonstrates the issue?
