### ISSUE TITLE
Is there a /ping endpoint for remote mode?

### ISSUE THREAD

**Issue by alshdavid** [DevExpress/testcafe#5481]
It's important that we wait for the test runner to be active before launching the browser and navigating to the URL. Is there an endpoint in the API which can serve as a ready check?

```
npx wait-on http://localhost:5567/ping && chrome --headless http://localhost:5567/ping &
npx testcafe remote ./tests --ports 5567,5568
```

In this case I am obviously using a local chrome instance, however in CI the instance would be located remotely and I would use an API to navigate to the testcafe remote URL when it's ready

**Comment by alshdavid** [comment]
I am using `npx wait-on http-get://localhost:5567/testcafe-core.js && echo Ready!`

**Comment by AndreyBelym** [comment]
TestCafe is ready to accept browser connections as soon as specified ports are occupied. So you can use `wait-on tcp:5667` to delay the start of your browser.
