### ISSUE TITLE
Does not run tests when Chrome browser is remote and headless

### ISSUE THREAD

**Issue by alshdavid** [DevExpress/testcafe#5482]
### What is your Test Scenario?
I have Chrome running locally (will eventually be inside a docker image). When using the remote mode, chrome will not automate when not visible on the screen.

This includes if it is running headless or on another virtual desktop.

I am using the following script to launch headless Chrome locally in parallel with testcafe.

```bash
#!bin/bash

CHROME_BIN="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

npx wait-on http-get://localhost:5567/testcafe-core.js && sleep 2 && \
"$CHROME_BIN" --headless --disable-gpu http://localhost:5567/browser/connect &

npx testcafe remote ./tests --ports 5567,5568
```

### What is the Current behavior?
The browser will connect, however the tests will not begin executing. I have tested the same behaviour in Firefox and it works fine.
 
### What is the Expected behavior?
The tests execute when the browser is running headlessly
 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Have a simple "getting started" page
2. Try to launch it using the above command

### Your Environment details:
 
* testcafe version:                   1.8.4
* node.js version:                    v14.2.0
* command-line arguments:  See above
* browser name and version: Chrome 85
* platform and version:          MacOS (Also tried on Windows 10)

**Comment by AndreyBelym** [comment]
Headless Chrome cannot work correctly until an explicit remote debugging port is assigned via command-line arguments. Adding `--remote-debugging-port=9222` fixed the issue for me.
