### ISSUE TITLE
TestCafe/Proxy test run requests different urls than a normal browser session

### ISSUE THREAD

**Issue by enbma9** [DevExpress/testcafe#5493]
### What is your Test Scenario?
Testing the login to our website.
 
### What is the Current behavior?
TestCafe starts but waits forever for the website/dom to appear until it runs into a timeout. By looking into the console, an exception is thrown that prevents the application to start:

```
ERROR Error: "Uncaught (in promise): t: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":404,"statusText":"Not Found","url":"https://apiserver/ApiServer/html/appconfig.json/index.html","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://apiserver/ApiServer/html/appconfig.json/index.html: 404 Not Found"
```

By looking into the requests made by TestCafe and its respective proxy, the request urls look quite strange. I have attached two screenshots below showing the details for both the requests by TestCafe as well as the requests by a normal browser session.

<details>
<summary>Screenshots:</summary>

<img width="1292" alt="TestCafeRequests" src="https://user-images.githubusercontent.com/70652971/92009874-67515380-ed49-11ea-8a35-59501356cc4e.png">

<img width="1283" alt="ClientRequests" src="https://user-images.githubusercontent.com/70652971/92009920-759f6f80-ed49-11ea-8808-1c35773578fe.png">
</details>
 
### What is the Expected behavior?
TestCafe requests all resources properly and loads the website.
 
### What is your web application and your TestCafe test code?
We are testing an enterprise web application, this is just a very simple example of one test:

```js
fixture `Main Page - Navigation`

    .page('https://apiserver/ApiServer/html/rbwebshop/')

    .before(async () => {
        await dbConnection.connect();
    })

    .after(async () => {
        await dbConnection.disconnect();
    })

    .beforeEach(async t => {
        await login(t);
        await t.switchToMainWindow();
    });

test('StartAtWelcomePage', async t => {

    await t
        .switchToIframe('iframe')
        .expect(Selector('h1').find('span').withText('Welcome').innerText).eql('Welcome');
});
```

### Your Environment details:
 
* testcafe version: 1.9.1                  
* node.js version: v12.18.0                    
* command-line arguments: testcafe firefox testfile.js 
* browser name and version: firefox 68.12.0esr 
* platform and version:  Windows 10        
* other:

**Comment by Farfurix** [comment]
@enbma9 

Hello,

This information is not sufficient to reproduce the issue. We need to examine a minimal project or some public URL. Could you please share it with us?

Since your website is private and requires authentication, I will not be able to access it. Our policy prevents us from accessing a customer’s internal resources without prior written approval from the entity that owns the server/web resource.

If you want us to research the problem further, we’ll need access to the server/web resource. Please ask the website owner to send us (mailto:support@devexpress.com) written confirmation. It must permit the DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes.

**Comment by enbma9** [comment]
@Farfurix 

Hello,

unfortunately there is no possibility to access the project or to setup something identical as the web application is an enterprise product deployed within the enterprise network. The login itself is also not the problem as the login page that should be loaded cannot be loaded due to the wrong requests made by the browser controlled by the TestCafe session.

The big question is why does the TestCafe session tries to:

```
GET http://<testcafe proxy...>/https://apiserver/ApiSever/html/appconfig.json
```

Instead of:

```
GET http://<testcafe proxy...>/https://apiserver/ApiSever/html/rbwebshop/appconfig.json
```

This would be the expected behavior as a normal browser session also requests only

```
GET https://apiserver/ApiSever/html/rbwebshop/appconfig.json
```

Is there any way to provide more details besides accessing the project? For instance a log to give you more information what happens behind the scenes?

Best regards.

**Comment by Farfurix** [comment]
@enbma9 

Hello,

>Instead of:
>```
>GET http://<testcafe proxy...>/https://apiserver/ApiSever/html/rbwebshop/appconfig.json
>```

If you do not see the `https://apiserver/ApiSever/html/rbwebshop/appconfig.json` without testcafe, then this may be due to incorrect URL resolve.

>Is there any way to provide more details besides accessing the project? For instance a log to give you more information what happens behind the scenes?

It is impossible to find the cause of this issue without examining your application code. You can try to isolate the problematic URL logic and show us how the `appconfig.json` request goes. Perhaps this request (`/appconfig.json`) is resolved regarding the incorrect `https://apiserver/ApiSever/html/rbwebshop` location.

**Comment by enbma9** [comment]
@Farfurix 

Hello,

> If you do not see the https://apiserver/ApiSever/html/rbwebshop/appconfig.json without testcafe, then this may be due to incorrect URL resolve.

Its the other way around.

I can see https://apiserver/ApiSever/html/rbwebshop/appconfig.json being properly requested without TestCafe. Hence the url is properly resolved by using the browser. But TestCafe is trying to get https://apiserver/ApiSever/html/appconfig.json for whatever reason. 

You can take a look about the requests made by TestCafe:

[10.143.180.208_Archive [20-09-04 14-37-25]_redacted.har.zip](https://github.com/DevExpress/testcafe/files/5174874/10.143.180.208_Archive.20-09-04.14-37-25._redacted.har.zip)

Looking into these http requests, i see no reason why TestCafe cuts off **rbwebshop** in the url when trying to get the resource.

**Comment by AndreyBelym** [comment]
Thank you for sharing the HAR log. I can see two requests that look problematic (`http://ORIGIN/ID/http://apiserver/ApiServer/html/appconfig.json` and `http://ORIGIN/ID/http://apiserver/ApiServer/html/appconfig.json/index.html`). However, as @Farfurix said, we need to understand your app logic to localize, debug, and fix the problem.

If you cannot share a complete sample or a link to your application, could you please share the HAR log of your app launched without TestCafe and the piece of code that creates the problematic request? You can place a breakpoint into the `fetch`/`XHR.open` call and copy the code of surrounding functions from several frames.

Also, could you please try to install the latest TestCafe release (v1.9.2) and make sure that you can reproduce the issue with it?
