### ISSUE TITLE
A child window may be opened twice in some cases

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe#5494]
### What is your Test Scenario?
Click a link that opens a separate window
 
### What is the Current behavior?
On my page test opens the child window twice
 
### What is the Expected behavior?
The child window should be opened only once, as it works without TestCafe
 
### What is your web application and your TestCafe test code?

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 fixture `Multiple window`
    .page `file:///C:/Work/root-page.html`;

test('New Test', async t => {
    await t
        .click('#link')
        .debug();
});
```
</details>

[root-page.zip](https://github.com/DevExpress/testcafe/files/5164169/root-page.zip)

### Steps to Reproduce:

1. Run the test for the attached page
2. Two windows will be opened instead of only one
 
### Your Environment details:
 
* testcafe version:                   v1.9.1
* node.js version:                    v12.16.1
* command-line arguments:  testcafe chrome test.js
* browser name and version: Chrome 85
* platform and version:          Win 10

**Comment by miherlosev** [comment]
```js    
<script type="text/javascript">
        function openWindow () {
            console.log('Open window');
            var child = window.open('http://google.com','name','width=600,height=400');
        }
    </script>
    <a id="link" href="http://google.com" target="_blank" onclick="openWindow()">Link</a>
```

**Comment by AlexKamaev** [comment]
It's correct behavior that two child windows are opened. Without TestCafe one window is blocked by Chrome, but if you prevent the blocking both windows will be opened.
