### ISSUE TITLE
When spawning processes in browser plugins to run applications, in certain circumstances the plugin fails to shut down

### ISSUE THREAD

**Issue by bsmithb2** [DevExpress/testcafe#5495]
### What is your Test Scenario?
When creating a browser plugin that enables tests on Apple Simulators, I built a build pipeline in Azure DevOps on Mac that ran a single test. The browser provider code is here: https://github.com/bsmithb2/testcafe-browser-provider-idevices/ and includes the example test as well as the pipeline configuration. 
The browser provider goes through the process of resetting the iphone's caches and then opening Safari in the same way that Appium does - through running an XCUITest to control the device. 
This works fine on high powered build devices because the TestCafe app opens fast enough to run the test and trigger XCUITest's check to see that nothing is happening on the device before closure. On a 2018 15" i7 MBP it's about 1.2 seconds. 

In Azure DevOps the test runs for about 1.4 seconds then fails. It seems that the Simulator types in the URL for the testcafe service, but then fails to see the start of a test. Adding a five second sleep after attempting to load the URL allows testcafe to continue. https://github.com/bsmithb2/testcafe-browser-provider-idevices/pull/12/commits/30da96bac7f045c799e39b7abd8a7f02905b2f0b

My belief is that the slower performance of the Azure DevOps agent means that the TestCafe service never completes the connection request before the simulator is shut down, which leads to the heartbeat never triggering. 
 
### What is the Current behavior?
Testcafe tests don't start running, and no logging is provided that enables you to identify this. 
 
### What is the Expected behavior?
Provide additional logging during browser plugin start (at least from a debug perspective) that enables provider creators to understand why the service is timing out (say for example because the heartbeat failed prior to the successful initiation of the first test)
 
### What is your web application and your TestCafe test code?
Browser provider at https://github.com/bsmithb2/testcafe-browser-provider-idevices
 
<details>
<summary>Your website URL (or attach your complete example):</summary>
Browser provider at https://github.com/bsmithb2/testcafe-browser-provider-idevices

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
https://dev.azure.com/BradleySmith0287/testcafe-browser-provider-idevices/_build/results?buildId=112&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=c3091b1e-314e-512e-11db-151fdba14cd6 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
https://github.com/bsmithb2/testcafe-browser-provider-idevices/blob/30da96bac7f045c799e39b7abd8a7f02905b2f0b/azure-pipelines.yml
```
</details>

<details>
<summary>Your complete test report:</summary>

```
    t =    25.33s         Get number of matches for: Elements containing elements matching predicate 'hasKeyboardFocus == 1'
    t =    26.39s     Wait for com.apple.mobilesafari to idle
    t =    26.48s Tear Down
Test Case '-[testApplicationUITests.testApplicationUITests testRunCleanSafariAndExecuteTestCafe]' passed (26.480 seconds).
Test Suite 'testApplicationUITests' passed at 2020-09-02 22:56:09.572.
	 Executed 1 test, with 0 failures (0 unexpected) in 26.480 (26.481) seconds
Test Suite 'testApplicationUITests.xctest' passed at 2020-09-02 22:56:09.573.
	 Executed 1 test, with 0 failures (0 unexpected) in 26.480 (26.482) seconds
Test Suite 'All tests' passed at 2020-09-02 22:56:09.574.
	 Executed 1 test, with 0 failures (0 unexpected) in 26.480 (26.484) seconds
2020-09-02 22:56:10.142 xcodebuild[4482:48341] [MT] IDETestOperationsObserverDebug: 40.061 elapsed -- Testing started completed.
2020-09-02 22:56:10.142 xcodebuild[4482:48341] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2020-09-02 22:56:10.142 xcodebuild[4482:48341] [MT] IDETestOperationsObserverDebug: 40.061 sec, +40.061 sec -- end

Test session results, code coverage, and logs:
	/Users/runner/Library/Developer/Xcode/DerivedData/testApplication-crwymenpiuxagyagerpplogjxwea/Logs/Test/Test-testApplication-2020.09.02_22-55-28-+0000.xcresult

** TEST SUCCEEDED **

Testing started on 'iPhone 11'
exit: code:0 signal:null

close: code:0 signal:null

called closebrowser

called dispose

ERROR The Safari 13.1.2 / iOS 13.6 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.

Type "testcafe -h" for help.
npm ERR! Test failed.  See above for more details.

##[error]Bash exited with code '1'.
Finishing: run tests
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Remove Thread.sleep from XCUITest. 
2. Run azure-pipelines.yml in an Azure DevOps build pipeline. Free is fine. 
 
### Your Environment details:
 
* testcafe version:                   1.9.1
* node.js version:                   8.17.0 x64
* browser name and version: iPhone11 and Safari 13 Simulator
* platform and version:  macOS 10.15 on Azure DevOps
* other:

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. I agree that we should need more logging in TestCafe. Currently, we use the [debug](https://npmjs.com/package/debug) to output debug logs. If you have a list of specific places where logging could help you when debugging your plugin, could you please share it here or make a PR that outputs the necessary information via the `debug` module?
