### ISSUE TITLE
Error 'Cannot read property 'data' of undefined'

### ISSUE THREAD

**Issue by estavreva** [DevExpress/testcafe#5499]
Steps to reproduce the bug :

1.I am running the automation tests with the command :

  testcafe chrome /path../ 
2.As soon as I am logged in the application , an error is shown ,which says "Cannot read property 'data' of undefined "

![image](https://user-images.githubusercontent.com/70747103/92220987-70573780-eea5-11ea-85d1-4db9104eee84.png)

3.I checked in the console the request: bad request 400 - Uncaught (in promise) TypeError

4.Four requests to the back end are failing ,giving the response:

Status Code: 400 Bad Request

![image](https://user-images.githubusercontent.com/70747103/92221048-89f87f00-eea5-11ea-8548-5bfc23907c72.png)

5.The test I am actually trying to run is:

test.only("Articles table access", async t => {
await t.click(homePageView.productMenu)

await t.expect((articlesPageView.articleTable).exists).ok();

});

### Your Environment details:
 
* testcafe 1.9.2 version:                   
* node.js version:                    
* command-line arguments: testcafe chrome e2e-tests/fixtures/articles-table.ts   
* browser name and version: Chrome Version 85.0.4183.83 (Official Build) (64-bit)  
* platform and version:Windows 10

**Comment by miherlosev** [comment]
Hi @estavreva 

The problem occurs on the client side of the tested web application. To find the cause of the problem, we need to debug web application locally. Could please share with us a public link to your application or create a simple example illustrating the problematic behavior?

**Comment by estavreva** [comment]
Hi @miherlosev ,

The problematic behaviour is shown above in my comment (see the first screenshot) that once logged in the application ,I get the error 'Cannot read property  'data' of undefined'.What other kind of information do you need besides the attached screenshots and the steps to reproduce the bug ?

**Comment by Farfurix** [comment]
@estavreva

Hello,

There is no public URL (or some minimal example to run) in your steps. Could you please share [the information we requested](https://github.com/DevExpress/testcafe/issues/5499#issuecomment-688099245)? We'll examine it and check for a suitable solution.

**Comment by estavreva** [comment]
Hello @Farfurix @miherlosev ,

Thank you for the answers.Is there any other possibility to find the cause of the problem without debugging the application locally (without the required url )  ?

**Comment by miherlosev** [comment]
In your case, we don't see another way to find the cause of the problem except for application debugging.
