### ISSUE TITLE
Fail when running on IE11 and tests involve iframes

### ISSUE THREAD

**Issue by alshdavid** [DevExpress/testcafe#5500]
### What is your Test Scenario?
Trying to get a selector on the page
 
### What is the Current behavior?

I am running testcafe using:
```
npx testcafe remote ./tests --skip-js-errors
```

The page looks something like the following

```
<body>
  <iframe>
    // <div id="target">text</div>
  </iframe>
</body>
```

The tests `switchToIframe` and attempt to get an element with a selector on it.

I then see errors relating to hammerhead.js in the console
![image](https://user-images.githubusercontent.com/12656294/92223257-8f74ba00-eee3-11ea-8187-9da81acb0fcc.png)

I suspect that the polyfills may not be recursively injected into embedded iframes
 
### What is the Expected behavior?
It runs in the same way as a modern browser
 

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.9.1
* node.js version:                    14
* command-line arguments:  `npx testcafe remote ./tests --skip-js-errors`
* browser name and version: IE11
* platform and version:          Windows 10 (WSL2)

**Comment by wentwrong** [comment]
I have tried your scenario with the following setup:
test.js:
```js
import { Selector } from 'testcafe'

fixture(`Checking incorrect work with IFrames in IE11`)
  .page('./index.html');

test('Should work fine', async t => {
  const targetText = Selector('#target').textContent;

  await t
    .switchToIframe(Selector('iframe'))
    .expect(targetText).eql('text inside div inside iframe');
});
```

index.html:

```html
<!DOCTYPE html>
<html>
    <head></head>
    <body>
        <iframe src="./iframe.html">
        </iframe>
    </body>
</html>
```
iframe.html:
```html
<div id="target">text inside div inside iframe</div>
```

My environment details:

* testcafe version: 1.9.1
* node.js version: v14.0.0
* command-line arguments: npx testcafe remote ./tests --skip-js-errors
* browser name and version: IE11 (11.53.18362.0)
* platform and version: Windows 10 (**without WSL**)

It seems like everything works as it should. Please try to reproduce the issue with the setup above. Maybe your site has additional logic that I didn't take into account.

In addition, may I ask you to perform the following steps?

* update to the latest TestCafe version (v1.9.2 for now) and check if this solves the issue;
* share your exact version of IE11 (Tools (Alt+X) -> About Internet Explorer);
* run tests with the [--dev](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#--dev) flag and share a screenshot of the errors you see in the browser console - this will help us identify problematic areas in the non-minified client-side hammerhead library;
* make sure the [Compatibility View](https://support.microsoft.com/en-us/help/17472/windows-internet-explorer-11-fix-site-display-problems-compatibility-v) is **turned off.**
