### ISSUE TITLE
Clicking on a tab just highlights and doesnt switch the tab

### ISSUE THREAD

**Issue by nikolarss0n** [DevExpress/testcafe#5501]
### What is your Test Scenario?
It should test switching between the tabs and assert that the tab is the expected one.

 
### What is the Current behavior?
At the moment when click on the tab it just highlight the tab and it doesn't return any data.
 
### What is the Expected behavior?
It should return item 3D visualization
 
### What is your web application and your TestCafe test code?
app = https://uk.misumi-ec.com/

Just pasted all you need to access the item and the 3D preview tab  

  test.only.page('https://uk.misumi-ec.com/vona2/detail/110302634310/?PNSearch=SFJ3-30&HissuCode=SFJ3-30&searchFlow=suggest2products&Keyword=SFJ3-30')('Click test', async t => {
    await t.click(Selector('#Tab_preview'));
    await t.wait(10000)
  });

### Steps to Reproduce:

1. Go to https://uk.misumi-ec.com/vona2/detail/110302634310/?PNSearch=SFJ3-30&HissuCode=SFJ3-30&searchFlow=suggest2products&Keyword=SFJ3-30
3. Click on 3D Preview tab 
4. It doesnt return any data, just highlight the tab
 
### Your Environment details:
 
* testcafe version:                   1.9.2
* node.js version:                    12.16.3
* command-line arguments:  testcafe chrome ....
* browser name and version:  chrome 85.0.4183.83
* platform and version:          Windows 10
* other:                                   

Tested the same scenario with Selenium and Puppeteer and it works. I suspect something with the proxy

**Comment by AlexSkorkin** [comment]
Thank you for reporting this issue. I have managed to replicate this behavior. Our team will research it and find a suitable solution.

**Comment by nikolarss0n** [comment]
> Thank you for reporting this issue. I have managed to replicate this behavior. Our team will research it and find a suitable solution.

Thank you very much for your assistance.

**Comment by nikolarss0n** [comment]
Any update on the issue?

**Comment by AlexSkorkin** [comment]
No updates yet. Once we get any results, we will share them here.

**Comment by d4niloArantes** [comment]
Hi guys! I'm facing a related issue to that. When I click in a button which opens [this site](https://drivin.ac-page.com/sistema-de-logistica-e-transporte-brasil?member_id=j74ad26a-y80a-4756-ddc9-1207fd3c62e1) on a new tab, in my case the tab opens up and switches to it but it hangs forever with the message on the TestCafé footer: "Loading Web Page"
![image](https://user-images.githubusercontent.com/13650384/133488209-6fa1e251-559d-405e-8b70-359aa25da988.png)

**Comment by Farfurix** [comment]
@d4niloArantes 

Hello,

Your case is different from the original issue, which relates to page tabs (not browser tabs). Please open a new issue using [our template](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=&template=bug-report.md) with some [reproducible example](https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue).

**Comment by hoqueal** [comment]
any update? I am facing the same issue

**Comment by Aleksey28** [comment]
Hi @hoqueal,

There are no updates yet. We will update this thread once we have news. Also, I found out that `3D Preview` appears, but below the previous tab, not instead of it.

**Comment by miherlosev** [comment]
Hi @nikolarss0n

This issue is not reproduced if I use the [experimental-proxyless](https://testcafe.io/documentation/402639/reference/command-line-interface#--experimental-proxyless) option.
Please try running the tests using this option and let us know your results.

**Comment by miherlosev** [comment]
Hi @nikolarss0n,

This issue is not reproduced with combination of `testcafe@3.0.1` and the Google Chrome browser. Feel free to reopen this issue if you encounter it in other browsers.
