### ISSUE TITLE
"body" element is undefined in Confluence 7 when testing with Testcafe

### ISSUE THREAD

**Issue by MaxStroh** [DevExpress/testcafe#5502]
### What is your Test Scenario?
viadee BPMN-Modeler Plugin for Confluence in Confluence v7.x
 
### What is the Current behavior?
Testing manually, everything works. Running tests with Testcafe, internal Confluence methods are throwing errors and searching for the "body" element in the DOM tree via browser console returns undefined. Searching for "bODy" or "Body" or "bodY" returns the correct corresponding body element (so only "body" returns undefined).

We assume that Testcafe might cache some elementary DOM elements like the body element and some internal code of Confluence tries to find the body too early so it is undefined at this moment, but this value is cached in Testcafe afterwards. This is just an idea, where the error might come from and we hope it helps finding the source of the problem.

Finding the body element nevertheless is elementary for us. Not only the code of the plugin we develop uses the body as entrypoint to append some HTML-snippets, but also internal methods of Confluence do not work correctly in our tests afterwards (e.g. opening default Confluence dialogs like "Do you really want to delete this page" sometimes crashed if we tried to "reset" the body element on our own in our plugin JS code).
Although this behaviour does also appear in **plain Confluence without even installing our plugin**, this makes it impossible for us to even add an instance of our plugin on a Confluence page via Testcafe. Therefore, this keeps us from using Testcafe to test our plugin in Confluence 7.x at all.

As Confluence is one of the most used company wikis and our BPMN-Modeler plugin is used by several hundred companies worldwide, we would appreciate, if Testcafe would be compatible with the newer versions of Confluence. Without this bug being fixed we can no longer use Testcafe at all in future, which would be very sad.
 
### What is the Expected behavior?
The "body" element can be found everytime so no internal Confluence methods throw errors and our plugin code is able to add HTML-snippets to the body.
 
### What is your web application and your TestCafe test code?
 
<details>
<summary>Building an simple example environment (Confluence 7):</summary>

This guide will show you how to simply run and setup a plain Confluence 7 in a docker container where the provided testcode can be run on.
Every step of the Confluence setup is documented in the attached screenshots, too.

1. Create a desired target directory on your system (e.g. `mkdir confluence-data`)
2. Run a confluence instance as docker container, mounting the target directory:
`docker run -v <PATH_TO_TARGET_DIR>/confluence-data:/var/atlassian/application-data/confluence --name="confluence" -d -p 8090:8090 -p 8091:8091 atlassian/confluence-server`
(e.g. on Windows: `docker run -v C:\Users\fancyuser123\confluence-data:/var/atlassian/application-data/confluence --name="confluence" -d -p 8090:8090 -p 8091:8091 atlassian/confluence-server`)
3. Open `http://localhost:8090` in the browser to go through the Confluence setup
4. On "Get apps" page: Click "Next" without checking any checkboxes
5. On "License key" page: Click on "Get an evaluation license" under the textarea-box
6. Log into your Atlassian account or create a new account
7. You will be redirected to a "New Trial License" page. There, choose "Confluence (Server)" and click on "Generate license"
8. A popup will appear to automatically add the generated license into your localhost Confluence setup. In this popup click "Yes" and you will be redirected back to your localhost Confluence and the license key should be entered in the textbox now
9. With the entered license key, click "Next"
10. On "Set up your database" page: Choose "Built in" and click "Next" (might take a while)
11. On "Load Content" page: Choose "Example Site"
12. On "Configure User Management" page: Choose "Manage users and groups within Confluence"
13. On "Configure System Administrator Account" page: Enter the following data:
```
Username: admin
Name: John Doe
Email: johndoe@example.org (this does not have to be a valid email)
Password: johndoeadmin2020
```
(These data are used by the test later on, so if you want to enter custom data, remember to change them in the provided test, too)
14. Click on "Next", you will land on a "Setup Successful" page. Click "Start"
15. On the Welcome page, enter "Test" as Space name and click on "Continue"
16. You will land in a page editor. A popup "Welcome to the editor" will appear. Click on "Skip tutorial"
17. Click on the placeholder "Page title" and enter "Foobar" as page title (used by the test later on). If you like, add any content to the page, but an empty page throws the error, too
18. Finally, click on "Publish" in the lower right corner and you're done.
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

app.js:

```js
 fixture `Getting Started`
    .page `http://localhost:8090/display/TEST/Foobar`;

test('My first test', async t => {
  await t
    .typeText('#os_username', 'admin', { paste: true })
    .typeText('#os_password', 'johndoeadmin2020', { paste: true })
    .click('#loginButton');
  await t.debug();
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

package.json:

```
{
  "name": "testcafe-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "testcafe": "^1.9.1"
  }
}
```
</details>

<details>
<summary>Your complete test report:</summary>

Our simple example test passes, but the error is thrown in the browser console, so remember to include the `await t.debug()` command in the test.
Error from the browser console:

```
Failed to run init function: Cannot enable drop zone on invalid container. Received: undefined ƒ (b){a.DragAndDropUtils.enableDropZoneOn(b("body")[0])} Error: Cannot enable drop zone on invalid container. Received: undefined
    at Object.enableDropZoneOn (batch.js?gatekeeper-ui-v2=true&healthcheck-resources=true&highlightactions=true&hostenabled=true&locale=de-DE&user-logged-in=true:2212)
    at batch.js?frontend.editor.v4=true&gatekeeper-ui-v2=true&healthcheck-resources=true&highlightactions=true&hostenabled=true&locale=de-DE&user-logged-in=true:473
    at batch.js?locale=de-DE:2116 Error: Cannot enable drop zone on invalid container. Received: undefined
    at Object.enableDropZoneOn (http://192.168.160.1:56572/SVmdh7KJE*tGjO4VuJb!s!utf-8/http://localhost:8090/s/800aa510049e345ef1a7d3227632b390-CDN/3olygv/8502/98c8e43717c0ab2f2ac7cca8cdb7048d439e20e4/58ea4b4b1ca83e6653fa74fbdf8e8e7f/_/download/contextbatch/js/atl.confluence.plugins.pagetree-desktop,main,viewcontent,atl.general,page,atl.comments,-_super/batch.js?gatekeeper-ui-v2=true&healthcheck-resources=true&highlightactions=true&hostenabled=true&locale=de-DE&user-logged-in=true:2212:80)
    at http://192.168.160.1:56572/SVmdh7KJE*tGjO4VuJb!s!utf-8/http://localhost:8090/s/ca7f8701fd519189f272c5b334c95b4a-CDN/3olygv/8502/98c8e43717c0ab2f2ac7cca8cdb7048d439e20e4/1f8e7c4f6f23e7c4aad98238d6795aab/_/download/contextbatch/js/editor-v4,editor,macro-browser,-_super,-atl.general,-viewcontent,-main,-page,-browser-metrics-plugin.contrib,-atl.comments/batch.js?frontend.editor.v4=true&gatekeeper-ui-v2=true&healthcheck-resources=true&highlightactions=true&hostenabled=true&locale=de-DE&user-logged-in=true:473:125
    at http://192.168.160.1:56572/SVmdh7KJE*tGjO4VuJb!s!utf-8/http://localhost:8090/s/4a1a53eefb1783684b00e45a60deedaf-CDN/3olygv/8502/98c8e43717c0ab2f2ac7cca8cdb7048d439e20e4/4a424b0cc300679de1caf7cc03e9fe6f/_/download/contextbatch/js/_super/batch.js?locale=de-DE:2116:504
window.console.<computed> @ hammerhead.js:6
(anonymous) @ batch.js?locale=de-DE:1981
(anonymous) @ batch.js?locale=de-DE:2116
document.getElementsByTagName('body')[0]
undefined
document.getElementsByTagName('bodY')[0]
<body id=​"com-atlassian-confluence" class=​"theme-default  aui-layout aui-theme-default">​…​</body>​
```
</details>

<details>
<summary>Screenshots:</summary>

Error:
![testcafe-confluence-error](https://user-images.githubusercontent.com/19880127/92234120-c631dc80-eeb1-11ea-837e-c59f4bdab495.png)

Confluence Setup Steps:
![confl-setup01-get-apps](https://user-images.githubusercontent.com/19880127/92234157-d5188f00-eeb1-11ea-9f84-7e5107244bbd.png)
![confl-setup02-license](https://user-images.githubusercontent.com/19880127/92234300-0b560e80-eeb2-11ea-9a86-fd7df003c399.png)
![confl-setup03-get-eval-license](https://user-images.githubusercontent.com/19880127/92234162-d649bc00-eeb1-11ea-8840-3b693205d0ca.png)
![confl-setup04-database](https://user-images.githubusercontent.com/19880127/92234164-d649bc00-eeb1-11ea-9cdd-9e27e95d5e57.png)
![confl-setup05-content](https://user-images.githubusercontent.com/19880127/92234165-d6e25280-eeb1-11ea-8a68-5fbc3edf1497.png)
![confl-setup06-user-management](https://user-images.githubusercontent.com/19880127/92234166-d6e25280-eeb1-11ea-9f3f-025171fd2033.png)
![confl-setup07-admin-account](https://user-images.githubusercontent.com/19880127/92234168-d77ae900-eeb1-11ea-8444-35e0a1d31f72.png)
![confl-setup08-setup-successful](https://user-images.githubusercontent.com/19880127/92234169-d77ae900-eeb1-11ea-8b72-83a8476f3a24.png)
![confl-setup09-test-spacename](https://user-images.githubusercontent.com/19880127/92234171-d8137f80-eeb1-11ea-80d8-ea53c777d935.png)
![confl-setup10-skip-tutorial](https://user-images.githubusercontent.com/19880127/92234173-d8137f80-eeb1-11ea-91e3-10935332e756.png)
![confl-setup11-publish-page](https://user-images.githubusercontent.com/19880127/92234174-d8ac1600-eeb1-11ea-960d-197bb05d480a.png)

</details>

### Steps to Reproduce:

1. Setup a Confluence 7 instance with the guide above
2. Run the test by running `npx testcafe chrome app.js` in a terminal
3. When Testcafe is in debug mode on the Confluence page, open the browser console
4. Look at the errors thrown by Confluence (they say that they tried to find the body by `$("body")[0]` but did not find the container to init DrapAndDrop features
5. In the browser console: Enter `document.getElementsByTagName('body')[0]` --> This will return `undefined`
6. In the browser console: Enter `document.getElementsByTagName('bodY')[0]` --> This will return the correct corresponding body element
7. If you like: Try steps 3 to 6 in your localhost Confluence instance manually to see that no error is thrown by Confluence and both queries in the browser console will return the correct body element

### Additional information:
* In Firefox, the command `document.getElementsByTagName('body')[0]` returns the correct body element, but the Confluence error is thrown nevertheless
* As our plugin code is executed by Confluence at the same time the Confluence error is thrown (we do not have influence on that), our JS code also returns undefined in Testcafe when searching for the body element. This can only be fixed by including `setTimeout()` calls in our plugin's JS code, although our JS code works perfectly without `setTimeout()` calls in the productive plugin. Because we do not want to add these calls in productive JS code just to get tests running, unfortunately this is no workaround for us
* Nevertheless, even if we find a workaround on our own for our plugin: Getting the body should always work and we have a bad feeling about it, if some internal functions in Confluence are not working correctly
* Additionally, excluding Chrome from testing is not an option for us
* We also built a simple test in Cypress to validate that the problem is not mainly caused by Confluence and with Cypress everything worked fine in Chrome and Firefox

### Your Environment details:
 
* testcafe version:                   1.9.1
* node.js version:                    12.18.3
* command-line arguments:   npx testcafe chrome app.js
* browser name and version: Chrome 85.0.4183.83, Firefox 80.0.1
* platform and version:          Windows 10
* other:                                   Confluence v7.x

**Comment by Ogurecher** [comment]
@MaxStroh, Thank you for your report and for the detailed instructions. You're absolutely right, this issue occurs because the stored result of the first `document.getElementsByTagName('body')` call is not updated. We're working on this issue in the context of this thread: #5322. We'll update that thread once we fix it.
