### ISSUE TITLE
Allow setting test context contents from runner

### ISSUE THREAD

**Issue by xorxero** [DevExpress/testcafe#5503]
# What is your Test Scenario?
I have a runner object and it runs fine running one test at a time as I am setting the environment with the unique username before I call runner.run.

Now I want to run 50 runner instances ASYNCHRONOUSLY to simulate load.
I need to generate unique ids for each runner that the tests it runs can use.
I need a way to pass these ids to the tests in a reliable manner from runner.

Right now, i didn't find a way to pass some string or object from runner to the tests reliably.

If i use an ENV variable, this affects all the tests across all instances and will not work in this async env.

### What are you suggesting?

Allow to pass a config object with runner that is accessible from t.ctx. 

So like:

```
await testRunner.run({
config: { USERNAME: generateRandomUsername() },
    selectorTimeout: 50000,
    assertionTimeout: 7000,
    pageLoadTimeout: 8000,
    speed: 1,
  });
```

### What alternatives have you considered?

ENV variables...

Creating a separate script to launch each run in a different process. This will probably work but it's not ideal.

Another approach I guess is to inject my config into the page using a clientscript since runner takes a clientscript but this is just nasty.

### Additional context

Its pretty important for scalability and parallelization to have this type of support.

Any time you want to run your tests multiple times and your app requires a unique value for the context, this becomes an issue.

Basically i want to run all my tests several times and I'm creating multiple runners but i need each each instance to be unique and use their own unique username.

I want each instance of runner to be unique and don't want any collision between the different instances and that is the challenge I face using env variables.

== My Setup

I have multiple fixtures with different tests. My app needs a unique username to work and I manipulate the database based on this unique username before tests and then I check in the tests if the app is behaving as intended. 

If I have multiple tests happening (ex on CI and on my PC) at the same time using the same username, I have problems both instances will be modifying the database and thus tests will fail as state of app is determined by db. 

So naturally, I make a unique id/username with my runner and pass that to my tests using an env variable. Works fine for different computers and processes. 

Now I want to launch 50 instances of chrome and each instance runs all tests independently using its own unique id.

**Comment by xorxero** [comment]
I was able to make a solution where I'm doing a loop and launching my test runner script in a new process (new instance of testcafe and everything per process) but this is not ideal, there definitely needs to be a proper way to transfer some data or config from runner object into the fixtures and tests (not ENV variables lol...)

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. I need to note that the primary purpose of TestCafe is end-to-end testing, not load testing, and specialized load testing tools can be more optimal and convenient.

As a more lightweight alternative to spawning a separate process for each runner, you can use the following code:

```
const vm = require('vm');

//...

async function runTests (runner, opts, config) {
    const context = { runner, opts, config };

    return vm.runInNewContext('runner.run(opts)', Object.assign(Object.create(global), context));
}
```

**Comment by xorxero** [comment]
Thank you. I decided to go the path of moving the username generation into the tests so now tests will generate what they need then clean up the database after. I did this so I can use the Testcafe concurrency option and now I don't need to pass anything from runner into the test context. 

But I still do think what I outlined is a useful feature to have
