### ISSUE TITLE
Tests not running in Edge 18

### ISSUE THREAD

**Issue by amal-architrave** [DevExpress/testcafe#5504]
### What is your Test Scenario?
I find test execution in the legacy version of Edge very flakey. Most times TestCafe is not able to make the test execution happen.
 
### What is the Current behavior?
I get the following error when tests are executed on Edge. I am running the test inside windows 10 parallels edition on my mac.

![image](https://user-images.githubusercontent.com/60701371/92393187-c8996e00-f11f-11ea-87e2-ec0120c9798c.png)

Brower Version: 
![image](https://user-images.githubusercontent.com/60701371/92393277-eff03b00-f11f-11ea-9e13-7f2dfb8c5c6c.png)

Command Line Logs:
![image](https://user-images.githubusercontent.com/60701371/92393571-612fee00-f120-11ea-8c8c-9c582c520f4f.png)

 
<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from 'testcafe';

fixture.only('test').page('https://fineuploader.com/demos.html');

test.only('test', async (t) => {
  const file = ['../test_data/testFile.pdf'];
  const ccc = Selector('input[type=file]').nth(1);

  await t.expect(ccc.exists).ok().setFilesToUpload(ccc, file);

  await t.click('#trigger-upload');

  await t.wait(5000);
  await t.debug();
});

```
</details>

### Your Environment details:
 
* testcafe version:                   1.9.1
* node.js version:                    12.16.2
* command-line arguments:  yarn testcafe edge
* browser name and version: Edge 18
* platform and version:          Windows 10 in parallels

**Comment by Ogurecher** [comment]
@amal-architrave, Thank you for your report. I couldn't reproduce this issue on my side. Please run your tests with `--hostname localhost` or `--hostname 127.0.0.1` and let us know if this resolves the issue.

**Comment by amal-architrave** [comment]
Hi, @Ogurecher using `--hostname localhost` worked. Thanks a bunch!
