### ISSUE TITLE
Add 'timestamp' field to each browser console message returned by 't.getBrowserConsoleMessages' method

### ISSUE THREAD

**Issue by milahu** [DevExpress/testcafe#5508]
title says all

[currently](https://github.com/DevExpress/testcafe/blob/74fd3524b1f39fb698984889e7bdd01945063f08/src/test-run/browser-console-messages.js#L6) `getBrowserConsoleMessages()` returns an object of arrays
where its impossible to tell what message came first (that is the bug)

```js
// old format
t.getBrowserConsoleMessages() == {
  log: ['2', '4'],
  info: ['1', '3'],
  warn: [],
  error: [],
}
```

expected result is: messages appear in chronological order

```js
// new format
t.getBrowserConsoleMessages() == [
  ['info', '1'],
  ['log', '2'],
  ['info', '3'],
  ['log', '4'],
]
```

.... assuming our test does

```js
console.info('1');
console.log('2');
console.info('3');
console.log('4');
```

to make it more cryptic, we could use only one char

```
l = log
i = info
w = warn
e = error
```
so ....

```js
// new format 2
t.getBrowserConsoleMessages() == [
  ['i', '1'],
  ['l', '2'],
  ['i', '3'],
  ['l', '4'],
]
```

for backward compatibility
the new function could be called `getBrowserConsoleHistory`

internally the strings are stored as array

fun fact: the `console.*` functions are async
and 'write done' is signalled by the `drain` event

**Comment by miherlosev** [comment]
Hi milahu,
 
I guess we can imitate the behavior of the browser development tools and add the 'timestamp' field to each browser console message. It allows us to know the order of these messages' appearance.

**Comment by milahu** [comment]
> add the 'timestamp' field to each browser console message.
> It allows us to know the order of these messages' appearance.

only after we manually sort the data

object is simply the wrong data structure for this
since the console is primarily sorted by time


with timestamps my proposal is
```js
// new format 2
t.getBrowserConsoleMessages() == [
  [100, 'i', '1'],
  [200, 'l', '2'],
  [250, 'i', '3'],
  [280, 'l', '4'],
]

// sample use
const typeName = {i: 'info', e: 'error', w: 'warn', l: 'log'};
t.getBrowserConsoleMessages().map(([time, type, msg]) => {
  console.log(`${typeName[type]}: ${msg}`);
});
```
in this sample i used relative time in ms since test start
using absolute time (ms since unix epoch)
costs one subtraction operation less, but some bytes more network traffic ....

sounds like youre afraid of changing the API?
told ya, we can keep the current format for getBrowserConsoleMessages
and introduce the new format with getBrowserConsoleHistory
internally the old getBrowserConsoleMessages is only a wrapper for the new func

**Comment by miherlosev** [comment]
I see what you mean. At present, however, we are focused on finishing the [Multiple Browser Windows](https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/multiple-browser-windows.html) feature. You can use the following workaround to achieve your goal:

### test.js
```js
  const addTimeStampForConsoleMessages = `
   const storedConsoleLog = console.log;
   
   console.log = function (message) {
      const modifiedMsg = JSON.stringify({
         type: 'log',
         value: message,
         timestamp: Date.now()
      });
      
      storedConsoleLog.call(this, modifiedMsg);
   }
`;

 


fixture `Fixture`
    .page('./index.html')
    .clientScripts({ content: addTimeStampForConsoleMessages });

 

test('test', async t => {
    await t.wait(3000);

 

    const { log } = await t.getBrowserConsoleMessages();

 

    console.log(log.sort(i => i.timestamp));
});
```

 
### index.html
```html
<html>
<body>
<script>
    console.log('log 3');

 

    setTimeout(() => {
        console.log('log 2');
    }, 100);

 

    setTimeout(() => {
        console.log('log 1');
    }, 1000);
</script>
</body>
</html>
```
