### ISSUE TITLE
Nested tests / subtests

### ISSUE THREAD

**Issue by xorxero** [DevExpress/testcafe#5511]
### What is your Test Scenario?

So I have a scenario in my app where I want to test something then going back to the previous step using the back button on my app (saves state) and do the test with some different data.

I got it working for now but everything is crammed into one test. 

### What are you suggesting?

To essentially define sub-tests within tests. So that they are only evaluated if previous logic succeeds. 

This is kind of how my logic is laid out right now
```
test("test errors") => {
login();
console.log("checking err 1");
uploadInfo(2);
await errorscreen.exists;
await clickbacktopreviousstep;
console.log("checking err 2");
uploadInfo(3);
await errorscreen.exists;
await clickbacktopreviousstep;
}
```

```
test("test errors") => {
login();

subtest("test err 1") = () => {
uploadInfo(2);
await errorscreen.exists;
}

await clickbacktopreviousstep;

subtest("test err 1") = () => {
uploadInfo(3);
await errorscreen.exists;
await clickbacktopreviousstep;
}

}

```

and in output we can just see a check  or X beside these subtests and they can be indented a tab from their parent test.

This way i can know exactly which "subtest" failed.

### Additional context

In this case its just checking errors but it would be more important if for example you enter or upload some info on one screen then proceed and you can navigate back to previous steps to update and override previous info.

If its a lot of logic, you want to be able to partition them into separate tests within a test so if anything fails you can more easily know what piece of logic is failing in this context.

**Comment by wentwrong** [comment]
I think that you can organize your tests in a different way to make them small and make each test check only one thing. You can extract repetitive logic with the help of [Test Hooks](https://devexpress.github.io/testcafe/documentation/guides/basic-guides/organize-tests.html#test-hooks) and plain functions.

We already received an enhancement request: [Implement BDD interface and nested fixtures](https://github.com/DevExpress/testcafe/issues/792). So I'll close this one as a duplicate.
