### ISSUE TITLE
Typescript fails to compile due to `import type` syntax in 3rd party TS declaration files

### ISSUE THREAD

**Issue by jmtoung** [DevExpress/testcafe#5512]
I'm running testcafe version 1.9.2 which seems to be using Typescript version 3.5.3.

When I try to compile a file, I get the following error. Inspecting each file and line that raises the error, it seems they all are using the `import Type` syntax. According to TS's website, this syntax is only allowed in versions 3.8 and above (https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html)

Do we know when this will be fixed?

```
Error: TypeScript compilation failed.
/Users/jonathan.toung/robinhood/rh/web/node_modules/@testing-library/dom/node_modules/pretty-format/build/index.d.ts (7, 13): '=' expected.
/Users/jonathan.toung/robinhood/rh/web/node_modules/@testing-library/dom/node_modules/pretty-format/build/index.d.ts (7, 18): ';' expected.
/Users/jonathan.toung/robinhood/rh/web/node_modules/@testing-library/dom/node_modules/pretty-format/build/index.d.ts (7, 31): ';' expected.
/Users/jonathan.toung/robinhood/rh/web/node_modules/@testing-library/dom/node_modules/pretty-format/build/index.d.ts (7, 36): ';' expected.
/Users/jonathan.toung/robinhood/rh/web/node_modules/@types/es-abstract/2015/ArraySetLength.d.ts (1, 13): '=' expected.
/Users/jonathan.toung/robinhood/rh/web/node_modules/@types/es-abstract/2015/ArraySetLength.d.ts (1, 41): ';' expected.
/Users/jonathan.toung/robinhood/rh/web/node_modules/@types/es-abstract/2015/CompletePropertyDescriptor.d.ts (1, 13): '=' expected.
/Users/jonathan.toung/robinhood/rh/web/node_modules/@types/es-abstract/2015/CompletePropertyDescriptor.d.ts (1, 60): ';' expected.
/Users/jonathan.toung/robinhood/rh/web/node_modules/@types/es-abstract/2015/CreateDataProperty.d.ts (1, 13): '=' expected.
/Users/jonathan.toung/robinhood/rh/web/node_modules/@types/es-abstract/2015/CreateDataProperty.d.ts (1, 34): ';' expected.
/Users/jonathan.toung/robinhood/rh/web/node_modules/@types/es-abstract/2015/CreateDataPropertyOrThrow.d.ts (1, 13): '=' expected.
/Users/jonathan.toung/robinhood/rh/web/node_modules/@types/es-abstract/2015/CreateDataPropertyOrThrow.d.ts (1, 34): ';' expected.
/Users/jonathan.toung/robinhood/rh/web/node_modules/@types/es-abstract/2015/CreateMethodProperty.d.ts (1, 13): '=' expected.
/Users/jonathan.toung/robinhood/rh/web/node_modules/@types/es-abstract/2015/CreateMethodProperty.d.ts (1, 34): ';' expected.
/Users/jonathan.toung/robinhood/rh/web/node_modules/@types/es-abstract/2015/DefinePropertyOrThrow.d.ts (1, 13): '=' expected.
/Users/jonathan.toung/robinhood/rh/web/node_modules/@types/es-abstract/2015/DefinePropertyOrThrow.d.ts (1, 54): ';' expected.


```

### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by Dmitry-Ostashev** [comment]
TestCafe can operate with TypeScript v3.8.x. I suggest that you delete package_lock.json and update your node_modules. Make sure that TypeScript v3.8.x is installed.
