### ISSUE TITLE
reduce repo file size

### ISSUE THREAD

**Issue by milahu** [DevExpress/testcafe#5515]
problem:
the git repository in its current state is way too large

the whole repo has 90 MB with only 3 MB code in `src/`

<details>
<summary><tt>du -shc testcafe/* | sort -h</tt></summary>

```
4.0K	testcafe/appveyor.yml
4.0K	testcafe/azure-pipelines.yml
4.0K	testcafe/CODE_OF_CONDUCT.md
4.0K	testcafe/CODEOWNERS
4.0K	testcafe/Gemfile
4.0K	testcafe/LICENSE
8.0K	testcafe/CONTRIBUTING.md
8.0K	testcafe/package.json
12K	testcafe/bin
20K	testcafe/docker
32K	testcafe/Gulpfile.js
32K	testcafe/README.md
76K	testcafe/@types
148K	testcafe/examples
156K	testcafe/ts-defs-src
196K	testcafe/CHANGELOG.md
2.9M	testcafe/src
11M	testcafe/media
11M	testcafe/test
67M	testcafe/docs
91M	total
```
</details>

solutions:
1. move `docs/articles` (currently 67 MB, mostly images and videos) and `media` (11 MB) to a separate branch on github (or to a separate repository like `DevExpress/testcafe-homepage`), so it is not cloned with a shallow clone like `git clone --depth=1 https://github.com/DevExpress/testcafe.git`
2. use that hidden branch for gh-pages = `https://devexpress.github.io/testcafe`
3. rewrite git history with [`git filter-branch`](https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository) (BFG Repo-Cleaner did not work for me), so the moved files are deleted from history of the master branch, so these files no longer are downloaded in a full clone like `git clone https://github.com/DevExpress/testcafe.git` - a full clone should be around 20 MB
4. move demo screenshots from README.md to gh-pages, so demos are one click away - could be worse
5. compress png images to webp. png is the largest format of them all. or better, convert png screenshots to svg - yes, this should be possible .... see [potrace](http://potrace.sourceforge.net/) for example
6. avoid video files like `docs/articles/images/landing-page/gallery-install-testcafe.gif` (text only), use css animations when possible, avoid moving windows in screenshot movies
7. deduplicate `media/new-0-10-0-autowait.*` (currently three formats, total 4.5 MB) and `media/new-0-10-0-autowait.*` and `docs/articles/images/blog/2020-07-23-multi-window.*` (prefer mp4 for hardware acceleration, compress more with CRF)
8. compress `test` folder (11 MB) by treeshaking/deduping/sharing code and compressing/avoiding png images, ~~OR move the whole test folder to a separate repository `testcafe-test` (not everybody needs to run `npm run test`)~~
9. generally, refactor duplicate code as reported by [jscpd](https://github.com/kucherenko/jscpd) - currently 12% duplicate lines in test/
10. indent code with tabs
11. avoid large dependencies like ffmpeg-downloader. i have ffmpeg/avconv installed on my machine, why download it again?

**Comment by miherlosev** [comment]
Hi @milahu

Thank you for your inquiry. We prefer to keep docs, tests, and code in the same repository. Currently, we do not consider using different repositories for this. Could you please share more details about the issue? Why do you feel that the size of the repository is an issue?
 
As a workaround, to reduce the size of the cloned repository, you can use partial cloning and sparse checkout from [Git 2.25](https://github.blog/2020-01-17-bring-your-monorepo-down-to-size-with-sparse-checkout) and get only those parts of the repository that you need:
```js
git clone --filter=blob:none --depth=1 --no-checkout https://github.com/DevExpress/testcafe
cd testcafe
git sparse-checkout init --cone
git sparse-checkout set @types bin src ts-defs-src
git checkout
```

**Comment by milahu** [comment]
> We prefer to keep [the status quo]

who is we? : P

also, why keep? except for laziness or lack of time

if you ('we') think the job is so terribly hard und ugly
i can write a script that does the job 99% automatic

> Why do you feel that the size of the repository is an issue?

efficiency

i mean .. the best argument for testcafe is
we can avoid downloading a full browser blob
just to run puppeteer / selenium / playwright / etc

but then, if i want to hack on some 3 MB of code
you expect me to download a 90 MB repo ....
this is just plain anti-professional
or at least inconsistent with the project goal
to offer a lightweight browser controller
and does not make a good impression
on the "optimize all the parts" people like me

but it matches with my overall impression (subjective opinion)
that the testcafe project "could have better maintainers"
the project looks like it got stuck like 5 years ago

> you can use partial cloning and sparse checkout from Git 2.25

last time i checked, the status of git partial clone was this:
you will get a partial clone as end result
but on the way there, git is still downloading the whole repo

the workaround i know is using the SVN interface of github
like in the script [yorkie/github-downloader.sh](https://gist.github.com/yorkie/8056734)

but workaround != solution

**Comment by miherlosev** [comment]
We (the TestCafe team) discussed your suggestion and decided that decreasing the size of the repository won't have a significant positive impact on the development and testing process.
The size of the 'node_modules' folder is 350 Mb. This is about 4 times larger than the released space.
It means that the time span between the download of the repository and the beginning of coding/running tests is practically unchanged.
If we decrease the size of the repository, its download will take a few seconds less.
However, this period is very short compared to the test run time (about 1 hour).
Also, storing documentation in the repository contributes to the cooperation between developers and technical writers.
 
If the size of the downloaded repository is critical, you can use the solution with 'sparse-checkout'. The size of the downloaded repository will be 3.9 Mb.
![image](https://user-images.githubusercontent.com/4133518/92907615-24b90680-f42e-11ea-87fa-a11be5bd5f3b.png)

**Comment by milahu** [comment]
thanks

* compression ratio (gzip) is very different for blob files
  * node modules: 19MB / 327MB = 95% less
  * docs: 61MB / 67MB = 10% less
  * docs is 61 / (19 + 61) = 75% of compressed download
  * .... according to my math
* 1 hour test run is another insane waste of resources. is this cpuburn.js?
* "storing documentation in the repository contributes to the cooperation between developers and technical writers."  
-- no. just no. how do you come up with such absurd claims?

but never mind

you guys just fanatically love your [cathedral](https://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar) ("feature not bug")
and see zero benefit in modular design and code splitting
maybe you do see some benefit, but you say "its too late now" - so be it

i was looking for a modular solution, so testcafe is clearly out of scope
