### ISSUE TITLE
testcafe wont run test. keep giving errors

### ISSUE THREAD

**Issue by IAmAlexPuga** [DevExpress/testcafe#5517]
### What is your Test Scenario?

 Run a test in chrome
### What is the Current behavior?

 gives error msg:
ERROR Was unable to open the browser "chrome:" due to error.

UnableToRunBrowsersError: Unable to run the browser. The file at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe does not exist or is not executable.
    at Object.default_1 [as open] (C:\Users\pugap\AppData\Roaming\npm\node_modules\testcafe\node_modules\testcafe-browser-tools\src\api\open.js:78:15)

### What is the Expected behavior?

 open a web browser and run test
### What is your web application and your TestCafe test code?

running locally

<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```import { Selector } from 'testcafe';

fixture `SpeedScore Interactions`

.page `http://127.0.0.1:5500/index.html`;

test('LoginGoesToActivityFeed', async t => {

await t

.typeText('#emailInput', 'hundhaus@wsu.edu')

.typeText('#passwordInput', '123#Eejl;')

.click('#loginBtn')

.expect(Selector('#feedModeDiv').visible).eql(true);

});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. run local server on vs code
3. testcafe chrome .\testfile.js
4. See the error...
 
### Your Environment details:
 
* testcafe version:  1.9.2                 
* node.js version:     12.8.3               
* command-line arguments: chrome 
* browser name and version: 
* platform and version: windows  10       
* other:      powershell/cmd admin

**Comment by AndreyBelym** [comment]
Thank you for your report. I cannot reproduce the issue in my environment. I think it may be related to the configuration of your OS or machine. Could you please answer some questions?

* Does Chrome's executable file exist at `C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`?
* If you have Chrome shortcuts in the Start menu or on the desktop, could you please check which file they reference (Context Menu -> Details -> Shortcut tab -> Object)?
* Could you check access rights for Chrome's executable file (Context Menu -> Details -> Security tab)?
* Is it possible to start Chrome from the command line (close all Chrome instances, then execute `cmd.exe` and `start C:\Program Files (x86)\Google\Chrome\Application\chrome.exe` in your Powershell window)?
* Do you have Windows Defender or some other antivirus software? Did you try turning it off before starting TestCafe?
* Did you try another browser (IE, Edge)?

**Comment by IAmAlexPuga** [comment]
Hi, thanks for getting back. I've answered your questions below:
 
- I checked the path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe and it exists.

- They reference "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" same as above

-  I set full access rights for chrome

- I tried to start chrome via command line given the two snippets from above but it opens up a cmd with the directory of where my tests are stored

- Ive disabled windows defender

- I get a very similar message for IE and Edge

**Comment by AndreyBelym** [comment]
I apologize for the incorrect start command in my previous comment. Could you please execute `cmd.exe` and `start /d "C:\Program Files (x86)\Google\Chrome\Application" .\chrome.exe`?

Please run the following Node.js script that is similar to the code that tests the browser path in TestCafe and share a screenshot of your terminal after the script is terminated.

```js
const fs = require('fs');
function exists (filePath) {
    return new Promise(resolve => fs.exists(filePath, resolve));
}
const path = 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe';
(async () => {
    const fileExists = await exists(path);
    if (!fileExists)
        console.log(`The file at ${path} does not exist or is not executable.`);
    else
        console.log(`The file at ${path} is found.`);
})();
```
