### ISSUE TITLE
Test Cafe not able to proceed after clicking login button 

### ISSUE THREAD

**Issue by rramji0211** [DevExpress/testcafe#5520]
### What is the Current behavior?
Test Cafe not able to proceed after clicking login button . Website is blocking further access to resources otherwise accessible when manually logged in.
 
### What is the Expected behavior?
Test cafe should have been able to login as done manually
 
### What is your web application and your TestCafe test code?
this is propriety software. Cannot be shared. but willing to share in a call.
 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

/******************Page Object Classes********************/
import { Selector, t } from 'testcafe';

/************Variable declarations***********************/
let config

/***********Test case Identifier************************/
config = {
    "TC_NAME": "cc_selActivity",
    "URL": ""
}

fixture `Navigate to GPA`.page(config.URL)

test(`login and select activity`, async t => {
    //await t.navigateTo(config.URL)
    await t.wait(5000)
    await t.maximizeWindow();

    let  uNameInput =Selector('#Login-LoginScreen-LoginDV-username > div > input[type=text]');
    const pwdInput =Selector('#Login-LoginScreen-LoginDV-password > div > input')
    const loginButton =Selector('#Login-LoginScreen-LoginDV-submit > div')

     await t.typeText(uNameInput,"su",{ replace: true })
    await t.typeText(pwdInput,"gw",{replace:true})
 await t.click(loginButton)

    await t.wait(10000)
})

```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

{
  "browsers": ["chrome"],
  "src": ["specs/dex-regression/"],
  "screenshots": {
    "path": "artifacts/screenshots/",
    "takeOnFails": true,
    "fullPage": true
   },
  "skipJsErrors": true,
  "skipUncaughtErrors": true,
  "selectorTimeout": 3000,
  "assertionTimeout": 1000,
  "pageLoadTimeout": 1000,
  "speed": 1
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
thats the element 
![image](https://user-images.githubusercontent.com/62260192/92657504-f539bb00-f2c2-11ea-818b-b1ad54f99200.png)

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by Farfurix** [comment]
@rramji0211

Debugging can take a lot of time. It can be significantly reduced if the person who is doing debugging can directly interact with the website. So, could you please share an URL address and all required credentials with us using our support@devexpress.com mailbox?

Since your website is private and requires authentication, I can't access it. Our policy prevents us from accessing a customer’s internal resources without a prior written approval from the person who owns the server/web resource. If you want us to research the problem further, we’ll need an access to the server/web resource. Please ask the website owner to send us ([support@devexpress.com](mailto:support@devexpress.com)) a written confirmation. It must permit DevExpress personnel to remotely access the website and its internal resources for research, testing and debugging purposes.

**Comment by stefanurziceanu** [comment]
Hi, I have a similar issue with the element from the screenshot below:
![image](https://user-images.githubusercontent.com/63287793/92706142-f5869480-f35c-11ea-8acd-c6a305673ce7.png)
The div that receives this click is:
![image](https://user-images.githubusercontent.com/63287793/92706868-88bfca00-f35d-11ea-8c8a-381413d3581f.png)

For whatever reason when clicking on this div using TestCafe, the click does not load a custom filter on page.
Here is the code (I use Cucumber integration with TestCafe for this):
![image](https://user-images.githubusercontent.com/63287793/92706534-439b9800-f35d-11ea-99a7-e474e37a5e1a.png)
![image](https://user-images.githubusercontent.com/63287793/92706609-544c0e00-f35d-11ea-9177-a7db083dbc68.png)

Here is the definition of the page object:
"div.st-tabs-tab.js-st-tabs-tab.st-tabs-tab--icon.js-st-tabs-tab-products" and the TestCafe script clicks on it but nothing happens.
Any help will be appreciated.

**Comment by Farfurix** [comment]
@stefanurziceanu

Hello,

We are still waiting for [the information we requested above](https://github.com/DevExpress/testcafe/issues/5520#issuecomment-690066804) in this thread. At first glance, the issue you described does not look like a duplicate (or a partial duplicate) of the problem we discuss here, but to be sure we need more information.

I suggest you create a new bug report with all the information we need to reproduce the issue (please use [our template](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md)).
