### ISSUE TITLE
In Mac Catalina for Chrome and Firefox, tests are not running in same tab. It opens a new window when the test is opening a new tab.

### ISSUE THREAD

**Issue by aman9922** [DevExpress/testcafe#5522]
### What is your Test Scenario?
On button click, a new tab should open.
 
### What is the Current behavior?
On button click, a new window is opening with default window size. After that elements are not visible because of small size of window and responsive behavior of website and I am not able to maximize it.

### What is the Expected behavior?
On button click, the new tab should open in the same tab (as per testcafe)
It works properly on Windows 10 for Chrome latest version
 
### Your Environment details:
 
* testcafe version:                  1.9.2
* node.js version:                    v12.18.3
* browser name and version: Chrome, Firefox latest
* platform and version:          Mac Catalina latest

**Comment by AlexSkorkin** [comment]
In v1.9.2, the [multi-window support](https://devexpress.github.io/testcafe/media/team-blog/introducing-multi-window-tests-beta.html) functionality is enabled by default.
 
Use the [--disable-multiple-windows CLI flag](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#--disable-multiple-windows) to disable support for multiple browser windows if you encounter compatibility issues with your tests.
