### ISSUE TITLE
QR Code from API

### ISSUE THREAD

**Issue by benmonro** [DevExpress/testcafe#5528]
### What is your Test Scenario?

Currently when running testcafe using the API there doesn't appear to be any way to use the qrCode flag that you can use in the CLI or config file.

### What are you suggesting?

adding support for QR code in the API.

i.e. something like this: 
```js
runner.run({
  qrCode: true
 ...
})
```

### What alternatives have you considered?

not sure?

**Comment by miherlosev** [comment]
Hi @benmonro
Thank you for bringing our attention to the absence of this feature in the programmatic API.
We will consider adding it in the future.
 
You can use the following workaround:
```js
const createTestCafe = require('testcafe');
const promisifyEvent = require('promisify-event');
const qrcode         = require('qrcode-terminal');

// Specify sources as a runner.js argument, e.g.:
// node runner.js tests/test.js
const sources = process.argv[2];

let testCafe          = null;
let browserConnection = null;

createTestCafe()
    .then(newTestCafe => {
        testCafe = newTestCafe;

        // Use testCafe.createBrowserConnection to prepare a remote browser connection
        return testCafe.createBrowserConnection();
    })
    .then(newBrowserConnection => {
        browserConnection = newBrowserConnection;

        // The testCafe.browserConnectionGateway.connectUrl property is a common URL for all remote connections in this session
        // You can retrieve unique per-browser connection url through the browserConnection.url property
        // See details at https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/browserconnection.html
        let connectionUrl = testCafe.browserConnectionGateway.connectUrl;

        console.log(connectionUrl);

        qrcode.generate(connectionUrl);

        // BrowserConnection emits 'ready' event when browser is connected
        return promisifyEvent(browserConnection, 'ready');
    })
    .then(() => {
        // Run tests, specify browserConnection as a browser
        return testCafe
            .createRunner()
            .browsers(browserConnection)
            .src(sources)
            .run();
    })
    .then(() => {
        return testCafe.close();
    });
```

**Comment by ericbiewener** [comment]
@miherlosev What is the advantage to using `testCafe.browserConnectionGateway.connectUrl` over `browserConnection.url`? The former doesn't appear to be a documented API, while the latter is.

**Comment by miherlosev** [comment]
`testCafe.browserConnectionGateway.connectUrl` is used to connect for all browser connections. You navigate to a single URL and all remote browsers connected in series.`browserConnection.url` is used to connect to the current browser connection.
It's better to use the `browserConnection.url` property since this property is part of the public API.
As soon as the `QR code from API` feature is implemented, we will remove all mentions of `testCafe.browserConnectionGateway.connectUrl` property usage.
We don't have plans to use the `testCafe.browserConnectionGateway.connectUrl` property in the future.

**Comment by ericbiewener** [comment]
Ok, so it looks like `browserConnection.url` produces the same URL, but with something like a unique identifier at the end, i.e. `http://localhost:60750/browser/connect/eeG1Z~Y`. And it appears that I need to strip off that unique identifier for the URL to actually work: `http://localhost:60750/browser/connect`. That sound right?

**Comment by AndreyBelym** [comment]
@ericbiewener You are totally correct, there is a browser UID at the end of `browserConnection.url`. You can strip it if you want a connection URL suitable for any browser.
