### ISSUE TITLE
RequestMock Typescript type should allow you to set any fields for headers

### ISSUE THREAD

**Issue by bdwain** [DevExpress/testcafe#5529]
### What is your Test Scenario?
Typescript types for requestmocks
 
### What is the Current behavior?
i can't set headers on the headers object.
 
### What is the Expected behavior?
I should be able to set headers on the headers object
 
### What is your web application and your TestCafe test code?

```ts
import { RequestMock } from 'testcafe';

const requestMock = RequestMock()
  .onRequestTo('myendpoint')
  .respond((req, res) => {
    res.headers['access-control-allow-origin'] = '*'; //TYPESCRIPT ERROR because you can't set fields on an `object`
  })
```

### Steps to Reproduce:
Make a typescr
 
### Your Environment details:
 
* testcafe version: 1.9.2
* node.js version:  10.14.2
* command-line arguments: N/A
* browser name and version: N/A
* platform and version: Mac OS X Catalina
* other: typescript version: happens on v3 and v4

**Comment by AndreyBelym** [comment]
Thank you for your report. I noticed your PR and will review it soon. Thank you for using and supporting TestCafe.
