### ISSUE TITLE
TestCafe does not trigger corresponding actions when clicking on a div with href attribute

### ISSUE THREAD

**Issue by stefanurziceanu** [DevExpress/testcafe#5532]
### What is your web application and your TestCafe test code?

 
<details>
<summary>https://www.st.com/en/amplifiers-and-comparators/comparators.html</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
Page objects code:
```js
'use strict';

let stPage = {
    cookiesButton: `button[aria-label='Accept Cookies']`,
    searchBox: `#widgetSearchBar`,
    searchButton: `div.small-3.columns>a`,
    searchResults: `td.search-rpns-min-width-col1>a`,
    productsMenu: `span>svg.st-svg.st-svg--all-products`,
    amplifiersLink: `a.st-nav__submenu-link`,
    comparatorProduct: `div.st-nav__blockmenu>a`,
    productSelector: `div.st-tabs-tab.js-st-tabs-tab.st-tabs-tab--icon.js-st-tabs-tab-products`,
    partNumberSearchBox: `div.st-sidebar__input.st-input--icon.st-input.js-st-input>input`,
    partNumberSearchButton: `div.st-sidebar__input.st-input--icon.st-input>svg.st-svg--block.st-svg--search`,
    partNumberResultElements: `a.js-st-quickview-toggle.js-st-quickview-adjust-height`,
    resetFiltersButton: `//div[contains(@class,'st-sidebar__filters') and not(contains(@class, 'hidden'))]//span[contains(@class,'st-sidebar__clear-all-btn')]`,
};

module.exports = stPage;
```

Testcafe code:
```js
When(
    'I/user click(s) {word} from {word}( page)',
    async function (t, [element, page]) {
        const elem = getElement(page, element);

        await t.click(elem);
    }
);

function getElement (page, elem) {
    const locator = pageObjects[page][elem];
    let element;

    try {
        if (isXPath(locator)) {
            element = SelectorXPath(locator);
        } else {
            element = locator;
        }
    } catch (error) {
        throw new ReferenceError(`${errors.SELECTOR_NOT_DEFINED} "${page}"."${element}" ${error}`);
    }

    return element;
}
```

</details>

<details>
<summary>I use TestCafe with Cucumber and testcaferc.json config file</summary>

```
{
    "browsers": "firefox",
    "src": ["node_modules/testcafe-cucumber-steps/index.js", "tests/**/*.js", "tests/**/*.feature"],
    "screenshots": {
        "path": "tests/screenshots/",
        "takeOnFails": true,
        "pathPattern": "${DATE}_${TIME}/test-${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.png"
    },
    "quarantineMode": false,
    "stopOnFirstFail": true,
    "skipJsErrors": true,
    "skipUncaughtErrors": true,
    "concurrency": 1,
    "selectorTimeout": 3000,
    "assertionTimeout": 1000,
    "pageLoadTimeout": 1000,
    "disablePageCaching": true
}
```
</details>

<details>
<summary>Your complete test report: The error occurs because the previous step of clicking the div is not working</summary>

```
Feature: Product Selector Filters
 × Scenario: Filter products by part number (screenshots: ..\Automation\TestCafe_Cucumber\tests\screenshots\2020-09-11_10-14-42\test-1\Firefox_80.0_Windows_10\errors\1.png)

   1) The element that matches the specified selector is not visible.

      Browser: Firefox 80.0 / Windows 10
      Screenshot: ..\Automation\TestCafe_Cucumber\tests\screenshots\2020-09-11_10-14-42\test-1\Firefox_80.0_Windows_10\errors\1.png

         420 |When('I/user type(s) {string} in {word} from {word}( page)', async function (
         421 |    t, [text, element, page]
         422 |) {
         423 |    const elem = getElement(page, element);
         424 |
       > 425 |    await t.typeText(elem, text);
         426 |});
         427 |
         428 |When('I/user type(s) {string}.{string} in {string}.{string}', async function (
         429 |    t, [page1, element1, page2, element2]
         430 |) {

         at <anonymous> (..\Automation\TestCafe_Cucumber\node_modules\testcafe-cucumber-steps\index.js:425:13)
         at <anonymous> (..\Automation\TestCafe_Cucumber\node_modules\testcafe-cucumber-steps\index.js:420:1)
         at GherkinTestcafeCompiler._runStep (..\Automation\TestCafe_Cucumber\node_modules\gherkin-testcafe\src\compiler.js:201:12)
         at GherkinTestcafeCompiler._resolveAndRunStepDefinition (..\Automation\TestCafe_Cucumber\node_modules\gherkin-testcafe\src\compiler.js:189:21)
         at <anonymous> (..\Automation\TestCafe_Cucumber\node_modules\gherkin-testcafe\src\compiler.js:108:28)
```
</details>

<details>
<summary>Screenshots:</summary>

the div element that receive the click is:

![image](https://user-images.githubusercontent.com/63287793/92895166-ed455c80-f423-11ea-95c3-2f1d5d13d6d6.png)

</details>

### Steps to Reproduce:

1. Go to the page URL from summary
3. Click on "Product selector link"
4. Wait until the custom search selector appears after click

Note: the same behavior can be found in a simple way using the TestCafe studio with the provided link and make the IDE perform the click (nothing happens either). Clicking manually the div is working ok.
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:   ".\node_modules\.bin\gherkin-testcafe firefox" 
* browser name and version: 
* platform and version:          
* other:

**Comment by stefanurziceanu** [comment]
Additionally you can try to run this code in TestCafe Studio, it will give the same behavior:

import { Selector } from 'testcafe';

fixture `New Fixture`
    .page `st.com`;

test('New Test', async t => {
    await t
        .click(Selector('button').withText('Accept Cookies'))
        .click(Selector('header a').withText('Amplifiers and Comparators'))
        .click(Selector('header span').withText('Products').nth(1))
        .click(Selector('header a').withText('Comparators').nth(2))
        .click(Selector('main span').withText('Product selector'))
        .click(Selector('main span').withText('Product selector'))
        .click(Selector('main span').withText('Product selector'));
});

**Comment by Ogurecher** [comment]
@stefanurziceanu, Thank you for your report. I've reproduced the issue. We'll update this thread once it's fixed.

**Comment by stefanurziceanu** [comment]
Hi, regarding this issue what I experienced with the browser launched by TestCafe, the dynamic page elements (probably related to third party controls integrated) are not displayed no matter how long I wait with timeouts. As soon as I remove the "http://10.0.0.72:56773/u5Mue81M2*AfD3R1R0D" part from the URL, the dynamic elements are loaded. Any thoughts?

**Comment by Ogurecher** [comment]
Hello @stefanurziceanu,
Thank you for sharing your observation. This part of the URL is [the proxy](https://devexpress.github.io/testcafe/documentation/how-it-works/#reverse-proxy) that TestCafe uses to interact with the page. If you remove it, you're basically just opening the tested page in your browser without TestCafe.

**Comment by stefanurziceanu** [comment]
> Hello @stefanurziceanu,
> Thank you for sharing your observation. This part of the URL is [the proxy](https://devexpress.github.io/testcafe/documentation/how-it-works/#reverse-proxy) that TestCafe uses to interact with the page. If you remove it, you're basically just opening the tested page in your browser without TestCafe.

Hello,
Thank you for your response. Is there any workaround for the proxy to load all the dynamic elements from the page in order to manipulate the page elments that now are not displayed?
Thank you.

**Comment by Ogurecher** [comment]
Unfortunately, there is no workaround for this issue at the moment. We need more time to research it. Once we fix the issue or find a workaround, we'll update this thread.
