### ISSUE TITLE
TestCafe crashes if it was created with 'createTestCafe(null)' call

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#5549]
https://stackoverflow.com/questions/63855087/testcafe-v1-9-0-unhandledpromiserejectionwarning-typeerror-cannot-convert-unde

```js
UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object 
at Function.entries (<anonymous>) 
at TestCafeConfiguration.mergeOptions (/Users/testcafe/node_modules/testcafe/lib/configuration/configuration-base.js:50:16) 
at TestCafeConfiguration.init (/Users/testcafe/node_modules/testcafe/lib/configuration/testcafe-configuration.js:48:14) 
at async getConfiguration (/Users/testcafe/node_modules/testcafe/lib/index.js:42:9) 
at async createTestCafe (/Users/testcafe/node_modules/testcafe/lib/index.js:59:27)
```

Code to reproduce the problem. This code works in `1.7.0`.

```js
const hostName = null;

createTestCafe(hostName).then(() => {});
```

**Comment by andrewRoj** [comment]
@miherlosev hi there. I appreciate the quick turnaround on this. I am still experiencing the same issue _but i found a fix_. 

on line 40 if i were to change 
`    if (args.length === 1 && typeof args[0] === 'object')` to 
`    if (args.length === 1 && typeof args[0] === 'undefined')
`

I am able to successfully run tests against browserstack.

**Comment by miherlosev** [comment]
> I am still experiencing the same issue
 
The version with a fix is not published in [npm](https://www.npmjs.com/) yet. We usually publish a new version every 2-3 weeks.
 
I built a new version for you to check the fix. You can install it with the 
```js
npm i https://github.com/miherlosev/tmp/files/5253670/testcafe-1.9.3-with-fix-i5549.zip
``` 
command. Please run your tests with this version. If the problem still exists, please create a separate issue with an example that we can run locally without any additional setup.

**Comment by andrewRoj** [comment]
Great! Thank you for the update. The fix looks like its working!
