### ISSUE TITLE
Property 'isAjax' does not exist on type 'RequestOptions'.

### ISSUE THREAD

**Issue by ruimarques** [DevExpress/testcafe#5557]
### What is your Test Scenario?
Mock requests
 
### What is the Current behavior?
```javascript
RequestMock()
      .onRequestTo(request => {
        if (request.isAjax) {
         // do something
        }
      })
```

Typescript error: Property 'isAjax' does not exist on type 'RequestOptions'.

### What is the Expected behavior?

According to documentation, isAjax should exist in request parameter from RequestMock().onRequestTo():
https://devexpress.github.io/testcafe/documentation/reference/test-api/requestmock/onrequestto.html
 

 
### Your Environment details:
 
* testcafe version:                  1.9.3

**Comment by Ogurecher** [comment]
@ruimarques, Thank you for your report. We've created [a separate thread](https://github.com/DevExpress/testcafe/issues/5562#L171) to address this issue. We would appreciate it if you contribute to fixing it. For more information, see our [Contribution Guide](https://github.com/DevExpress/testcafe/blob/master/CONTRIBUTING.md).

**Comment by miherlosev** [comment]
This issue is not reproduced with `testcafe@1.12.1`.
