### ISSUE TITLE
Add 'req.isAjax' option description

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#5562]
* Documentation - https://devexpress.github.io/testcafe/documentation/reference/test-api/requestmock/respond.html#requestoptions

* Typings - https://github.com/DevExpress/testcafe/blob/1e30f9de72e27a2afe10b1fdec317456bffb9723/ts-defs-src/test-api/request-hook.d.ts#L171

**Comment by DIRECTcut** [comment]
[RequestOptions.isAjax type def](https://github.com/DevExpress/testcafe-hammerhead/blob/012283d1d48e1a22ad8e70031ac97589c8c5c779/src/request-pipeline/request-options.ts#L19)
