### ISSUE TITLE
Update role cookies

### ISSUE THREAD

**Issue by andrzej-kodify** [DevExpress/testcafe#5566]
My scenario is as follows
1. User logs in and this is done with `Role` mechanism in testcafe. Logging in results in user getting `jwt` cookie
2. Subsequent test cases invoke `useRole` with that user's role
3. At some point (after approx. 10 minutes) JWT expires
4. So the test that is executing at that point makes call to a refresh token endpoint (this is done by our app JS code)
5. new `jwt` cookie is returned and test continues with properly authenticated user

Now the problem is that all subsequent tests will try to call refresh endpoint from now on since `useRole` restores initial state (that was right after login).

Is it possible to either expire role (force testcafe to recreate that role going through authentication again) or somehow force it to update that role state with new cookies?

Example:
```
import { Role, RequestMock, Selector } from 'testcafe';

let cnt = 0;

const mock = RequestMock()
    .onRequestTo('http://example.com/refresh')
    .respond((req, res) => {
        ++cnt;
        res.headers['set-cookie'] = `jwt=${cnt}; Domain=.example.com; Path=/; Expires=Thu, 01 Jan 2050 00:00:00 GMT`;
        res.setBody(JSON.stringify(req));
    })
    .onRequestTo('http://example.com/dump')
    .respond((req, res) => {
        res.setBody(`<html><body><div id="cookie">${req.headers.cookie}</div></body></html>`);
    });

const role = Role('http://example.com/dump', async t => {
    await t
        .navigateTo('http://example.com/refresh'); // log in and get initial jwt
});

fixture('Refresh token');

test('Test 1', async t => {
    await t
        .useRole(role)
        .navigateTo('http://example.com/dump')
        .expect(Selector('#cookie').textContent)
        .eql('jwt=1');
}).requestHooks(mock);

test('Test 2', async t => {
    await t
        .useRole(role)
        .navigateTo('http://example.com/dump')
        .expect(Selector('#cookie').textContent)
        .eql('jwt=1')
        // jwt was ok, but lets assume it expires on next call so refresh call is made
        .navigateTo('http://example.com/refresh')
        .navigateTo('http://example.com/dump')
        .expect(Selector('#cookie').textContent)
        .eql('jwt=2'); // I'd like this cookie to be preserved for next test
}).requestHooks(mock);

test('Test 3', async t => {
    await t
        .useRole(role) // how to get refreshed token here?
        .navigateTo('http://example.com/dump')
        .expect(Selector('#cookie').textContent)
        .eql('jwt=2');
}).requestHooks(mock);
```

**Comment by Ogurecher** [comment]
@andrzej-kodify, Thank you for your question. Unfortunately, you cannot update a user role using public TestCafe APIs. There is a [suggestion](https://github.com/DevExpress/testcafe/issues/5351%5D(https://github.com/DevExpress/testcafe/issues/5351)) for your use case.
In my opinion, the best way to handle this scenario is to simulate user actions instead of updating roles. In other words, when a user is logged out, you need to recreate their role and apply it.

**Comment by andrzej-kodify** [comment]
Thanks for reply.
I would argue that my flow doesn't mean user is logged out. It's a session refresh, that is actually made on client side with refresh call. Assume something like being logged in to bank and after 10 minutes your session times out, but while you're navigating these actions prolong the session. However with JWT instead of it being a server side session with single key, the user gets new cookie every 8 minutes or so and this cookie holds signed JWT.
So from end user perspective the user was never logged out. 
From test script perspective it is tricky to know when that role becomes invalid - I would need to `useRole`, get the cookie, decode JWT, if it's expired recreate role going through entire login process. I might not even know that it's expired since on loading page with expired JWT there's a refresh call being made automatically and my role will get fresh JWT, but of course this won't be stored.

**Comment by Ogurecher** [comment]
@andrzej-kodify

Thank you for the clarification.
 
You can apply a workaround using the internal API. The `Role`'s state is stored in the `stateSnapshot` property, so you can manually set cookies there.  

![Role](https://user-images.githubusercontent.com/28919867/94423328-23f3d480-0191-11eb-8b6e-9bf3d32b9eba.png)

 
You can set the updated cookie to `Role` in the `afterEach` hook:
```js
fixture('Refresh token')
    .afterEach(async () => {
        if (role.stateSnapshot) {
            debugger;
            const stateSnapshotCookies = JSON.parse(role.stateSnapshot.cookies);
            const jwtCookie            = stateSnapshotCookies.cookies.find(cookie => cookie.key === 'jwt');

            jwtCookie.value = await ClientFunction(() => {
                function getCookieByName (name) {
                    const match = document.cookie.match(new RegExp('(^| )' + name + '=([^;]+)'));
                    if (match) return match[2];
                }

                return getCookieByName('jwt');
            })();

            role.stateSnapshot.cookies = JSON.stringify(stateSnapshotCookies);
        }
    });
```

Please note that `Role.stateSnapshot` is a part of the internal API. It's not documented and is subject to change without prior notice.

Please also refer to [this suggestion](https://github.com/DevExpress/testcafe/issues/5351) and check if it is suitable for your use case. If so, please add your vote. This will help us prioritize this issue.
