### ISSUE TITLE
Add an option to route all requests (including images) through testcafe's reverse-proxy

### ISSUE THREAD

**Issue by jfdion** [DevExpress/testcafe#5568]
Would it be possible to add an option to allow for all the traffic to be routed through the reverse proxy. There is a setting in `testcafe-hammerhead` to force images through the reverse proxy (`forceProxySrcForImage`). 

Unfortunately this setting is not exposed through testcafe's config file

### What is your Test Scenario?
In our application we have a dedicated module for handling files. This module uses a compound security to allow access to certain files, which include a session cookie. Without this cookie the file token cannot be decrypted and thus, the file cannot be served.

### What are you suggesting?
It would be nice to have the option to set the value of `forceProxySrcForImage` for a specific `TestController` or globally through the application config `testcaferc.json`.

### Additional context
An other alternative could be to have a request hook to set the value

**Comment by miherlosev** [comment]
Hi @jfdion 
 
> In our application we have a dedicated module for handling files.  This module uses compound security to allow access to certain files, which include a session cookie.
 
Could you please describe what kind of files (`images`, `videos`, etc.) your application handles and how it does this in greater detail?
This information can help us understand your use case and pass cookies automatically without any setup.

**Comment by jfdion** [comment]
The flow is for images, videos and binary files (pdf, doc, ppt, etc.)

When a user is logged in the application a session cookie with a unique key is created. This cookie is provided to our differents modules on each request. 

If the response from any module would include a link to fetch a file, an access token is created by using that value has a part of the cypher. 

When the client fetches the file, it provides the token and its session cookie value. If the file handling module can decipher the token, the request is allowed to complete and the URL to fetch the file is returned

**Comment by miherlosev** [comment]
Thank you for the detailed description of the file handling functionality.

> When the client fetches the file

Could you describe which JavaScript API is used to fetch files?

**Comment by jfdion** [comment]
The file is fetched through `img` either from the `src` or `srcset` attibutes, `video` from `src` attribute or directly form an `a` through the `href` attribute

**Comment by miherlosev** [comment]
Thank you for the detailed information.

At present, the option `forceProxySrcForImage` will be `true` if a test has at least one request hook. So, as a workaround, add `RequestMock` or `RequestLogger` or a custom `RequestHook` to the test and all images from tested pages will be fetched via the proxy.
