### ISSUE TITLE
notOK() assertion showing expected as undefined

### ISSUE THREAD

**Issue by aprabh001c** [DevExpress/testcafe#5570]
We are using assertion for an element to disapper, i.e., wait until spinner disappears and seeing expected undefined if spinner stays more than expected time

Testcafe Step: -    await t.expect(Selector(.'spinner').exists).notOk("Wait For Spinner");

1) AssertionError: Wait For Spinner: expected true to be falsy

     + expected - actual

     -true
     +undefined

since expected showing as undefined browser is not getting closed and spinning forever. Could you please help

TestCafe version - 1.9

**Comment by AlexSkorkin** [comment]
We are looking into this issue in the context of the following thread: #5473
