### ISSUE TITLE
Unable to set value to input range

### ISSUE THREAD

**Issue by anilpothala** [DevExpress/testcafe#5571]
### What is your Test Scenario?

i would like to choose price range between 10 to 300
 
### What is the Current behavior?

Unable to set value to input field using typeText method

### What is the Expected behavior?

should set value for range filed using typeText method
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```
Test file
------------
import { Selector } from 'testcafe';

fixture `range manipulation`
    .page `./index.html`;



test(`Select an option from the drop-down menu`, async t => {
    const range = Selector('#cowbell');

   await t
        .typeText(range,'r',{ caretPos: 90 })
        
});

html file:-
--------

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Range element manipulation</title>
</head>
<body>


<input type="range" id="cowbell" name="cowbell" 
         min="10" max="300"  >

</body>
</html>
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
Test file
------------
import { Selector } from 'testcafe';

fixture `range manipulation`
    .page `./index.html`;



test(`Select an option from the drop-down menu`, async t => {
    const range = Selector('#cowbell');

   await t
        .typeText(range,'r',{ caretPos: 90 })
        
});

html file:-
--------

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Range element manipulation</title>
</head>
<body>


<input type="range" id="cowbell" name="cowbell" 
         min="10" max="300"  >

</body>
</html>





```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

https://github.com/anilpothala/input-range-selection

 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by arubtsov** [comment]
Hello @anilpothala,

Try setting the value as follows: `await t.typeText(selection, '250');`.
Feel free to reopen this issue if this doesn't meet your needs.

**Comment by anilpothala** [comment]
> Hello @anilpothala,
> 
> Try setting the value as follows: `await t.typeText(selection, '250');`.
> Feel free to reopen this issue if this doesn't meet your needs.

Hi @arubtsov when we have multiple range selection, typeText doesn't seems to be working.
above works only when we have single selection of range.

https://github.com/anilpothala/input-range-selection/

i have added code here for multiple range selection.

<img width="154" alt="Screen Shot 2020-09-24 at 12 42 44 AM" src="https://user-images.githubusercontent.com/16675424/94115669-e98bdf80-fdfe-11ea-86b3-c39a7398d1ee.png">

**Comment by aleks-pro** [comment]
Hello @anilpothala,

Thank you for the provided example.

To make two overlapping ranges work, you used the mousemove event. At the moment, TestCafe doesn't have actions that emulate this event. You can find the corresponding issue here: https://github.com/DevExpress/testcafe/issues/527.

As a workaround, you can use [ClientFunction](https://devexpress.github.io/testcafe/documentation/guides/basic-guides/obtain-client-side-info.html) API to set a range value:

```js
import { Selector, ClientFunction } from 'testcafe';
fixture `range manipulation`
    .page `./index.html`;
const setRangeValue = ClientFunction(value => {
    const element = document.getElementById('b');
    element.value = value;
});
test(`Select an option from the drop-down menu`, async t => {
    const range = Selector('input');
    await t
        .typeText(range.nth(0), '20')
        .expect(range.nth(0).value).eql('20');
    await setRangeValue('80');
    await t.expect(range.nth(1).value).eql('80');
});
```
