### ISSUE TITLE
Cannot download file by clicking the link with attributes: download, target='_blank' and href='blob:...'

### ISSUE THREAD

**Issue by AlexKamaev** [DevExpress/testcafe#5574]
```HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a download="hello.txt" href='#' id="link" target="_blank">Download</a>
<script>
    let blob = new Blob(["Hello, world!"], { type: 'text/plain' });

    document.querySelector('#link').href = URL.createObjectURL(blob);
</script>
</body>
</html>
```
```JS
fixture `f`
    .page `http://127.0.0.1:8080`;
test('test', async t => {
    await t.click('a');
    await t.wait(5000);
});

```

WORKAROUND: use the `--disable-multiple-windows` flag

**Comment by HDnLE** [comment]
In ref to your [comment ](https://stackoverflow.com/questions/64561911/testcafe-how-to-use-disablemultiplewindows-inside-test-function/64569570?noredirect=1#comment114201324_64569570):

I am afraid I cannot provide you the url due to the sensitivity of the on-going project. But what do you mean by "create a sample..."? A sample of the site under test? 

I was viewing at the browser's DevTools, the downloading is not similar to your example above where it uses download, target attributes. We are actually using SAPUI5 technology. Kind see attached screenshot:

![image](https://user-images.githubusercontent.com/22788779/97624193-0f705980-1a27-11eb-8b44-d5fa423f994b.png)

So right now I shifting to using the --disable-multiple-windows on all tests. But it would be great if there is a way to apply that option on a particular test only.

**Comment by AlexKamaev** [comment]
>But what do you mean by "create a sample..."? A sample of the site under test?

I mean that you can create a simple project that demonstrates the issue and share it with us.

>I was viewing at the browser's DevTools, the downloading is not similar to your example above where it uses download, target attributes. We are actually using SAPUI5 technology. Kind see attached screenshot:

The issue can still be the same despite the fact that your markdown differs from the markdown in my example. I found this issue using other UI controls. In those UI controls, the markdown from my example was generated via JS.

>But it would be great if there is a way to apply that option on a particular test only.

From our point of view, it's better to fix the cause of the issue. However, I can suggest a workaround. You can use [the programmatic API](https://devexpress.github.io/testcafe/documentation/reference/testcafe-api/runner/run.html) and run your tests two times: with the `disableMultipleWindows` option and without it.

I created a sample to demonstrate this approach:

Tests (test.js):
```JS
fixture `fixture`
    .page `http://example.com`;

test('1', async t => {
   await t.click('h1');
});

test('2', async t => {
    await t.click('h1');
});

test('3', async t => {
    await t.click('h1');
});

test('4', async t => {
    await t.click('h1');
});

test('5', async t => {
    await t.click('h1');
});
```
The runner (index.js):
```JS
const createTestCafe = require('testcafe');

async function start () {
    const testcafe = await createTestCafe('localhost', 1337, 1338);

    try {
        const runner = testcafe.createRunner();

        await runner
            .src(['test.js'])
            .browsers('chrome')
            .filter(testName => testName !== '3')
            .run({ disableMultipleWindows: false });

        await runner
            .filter(testName => testName === '3')
            .run({ disableMultipleWindows: true });
    }
    finally {
        await testcafe.close();
    }
}

return start();
```
You can run the tests using the following command in the terminal: `node index.js`.

Thus, 4 of 5 tests will be executed with the enabled multiple-windows feature and the last test with the disabled.

**Comment by AlexKamaev** [comment]
@AM1988 this issue is specific to the `href="blob:..."` case. I think that your usage scenario is similar to #6680.
Please try to check the [https://www.npmjs.com/package/testcafe/v/1.17.2-alpha.2](https://www.npmjs.com/package/testcafe/v/1.17.2-alpha.2) version.
If it does not help, please create a [new issue ](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&template=bug_report.yaml)and share your example with us.

**Comment by TusharBachchan** [comment]
We have tried this solution for #6946 but it did not work for us, we get a new blank window as shown :
![image](https://user-images.githubusercontent.com/57787633/169052349-26ed8f9f-8152-49a0-a078-e60bb03d48d2.png)
and our script freezes if we try to close the new window (using our script) and if we do not close the new window and we try to perform any action only one step further is performed and then it again freezes.

**Comment by AlexKamaev** [comment]
@TusharBachchan We'll take your usage scenario in account when we research the issue.

**Comment by AMuskan12** [comment]
Regarding issue #6946 :- Thank you for your response. Actually we have some dependency around this scenario, could you please take this scenario bit early if possible. Your help will be appreciated.

**Comment by yashaswi0812** [comment]
Is there any update? we tried the solution and it didn't work for us.  our script freezes if we try to close the new window (using our script) and if we do not close the new window and we try to perform any action only one step further is performed and then it again freezes and stays there till we manually close it.

**Comment by yashaswi0812** [comment]
we tried to write scripts in different tests still it didn't work. After Screen is frozen it doesn't move to another test. we even tried to forcefully close the window and it didn't work as well.

**Comment by TusharBachchan** [comment]
> @TusharBachchan We'll take your usage scenario in account when we research the issue.

Is there any updates regarding this issue, has this usage scenario taken into consideration?

**Comment by AlexKamaev** [comment]
We will update this thread once we have any news.
