### ISSUE TITLE
slowness on custom styled radio or checkbox

### ISSUE THREAD

**Issue by benmonro** [DevExpress/testcafe#5576]
### What is your Test Scenario?

 Testing a radio or checkbox that has custom styling.
### What is the Current behavior?

 Currently, clicking on the element is very slow, even though the element is present.  The click _will_ work, but not until the very end of the selector timeout.
### What is the Expected behavior?

 Not sure if this is a bug or by design.  If it's a bug, then I suppose it should fail?  if it's by design, then perhaps it should not wait for the timeout to complete?

### What is your web application and your TestCafe test code?

Repro can be found here (instructions in the readme):
 https://github.com/benmonro/slow-radio-testcafe-issue

<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Clone repo above
3. `yarn && yarn test`
4. See there are 2 tests, one is slow, one is fast, only difference: one sets a z-index on the custom styled input field, the other doesn't.
 
### Your Environment details:
 
* testcafe version:                   1.9.3
* node.js version:                   v12.16.1
* command-line arguments:  `yarn test`
* browser name and version:  chrome 85
* platform and version:         mac 
* other:

**Comment by AlexanderMoiseev** [comment]
Hello, 

This behavior is correct. TestCafe cannot interact with page elements under other elements. If the target element is not on top when an action is triggered, TestCafe waits for this element to appear in the foreground. If this does not happen within the selector timeout, the action is performed with an overlaying element. Please refer to the ['select-target-elements'](https://devexpress.github.io/testcafe/documentation/reference/test-api/testcontroller/click.html#select-target-elements)  documentation

**Comment by benmonro** [comment]
@AlexanderMoiseev curious what the reason is for this?  Custom radio/check box is a pretty common pattern.

**Comment by AlexanderMoiseev** [comment]
Hello,

To avoid waiting for the selector’s timeout, you can use the “span.checkmark” selector instead of your "input[type=radio]” selector.

As for your question, Testcafe emulates a user’s behavior. A user can’t click an element that is overlapped by another element, so Testcafe waits until this element becomes not overlapped. If this does not happen, the found element can be clicked as a fallback. 

We agree with you, since this is a popular pattern, we will consider handling this case more gracefully in the future.

**Comment by benmonro** [comment]
Thank you for that suggestion @AlexanderMoiseev.  And yeah thank you for addressing

**Comment by AlexanderMoiseev** [comment]
You are welcome. Should you have additional questions or require further assistance, feel free to contact us at your convenience. We are here to help.
