### ISSUE TITLE
Display the executed file path in the terminal when running in debug mode

### ISSUE THREAD

**Issue by benmonro** [DevExpress/testcafe#5577]
### What is your Test Scenario?

when running in debug mode, it would be nice to see the file that the code window is currently looking at.

### What are you suggesting?

It would be very helpful (especially for tests that use POM or helper functions) to know where in the code the debugger is currently stopped.  Currently it shows something like this: 

```sh
----
Chrome 85.0.4183.121 / macOS 10.15.6
DEBUGGER PAUSE:
10 |test.page`./slow.html`("is slow", async t => {
> 11 |    await t.debug().click(Selector("input[type=radio]").nth(0))
12 |});
----
```

But the filename is not displayed.  it would be very helpful to see that either above or below for example.

**Comment by miherlosev** [comment]
Hi @benmonro,

Thank you for this suggestion.
