### ISSUE TITLE
Allow restarting test while watching is disabled in livemode

### ISSUE THREAD

**Issue by Khartir** [DevExpress/testcafe#5581]
Currently it is not possible to restart test with `Ctrl+R` in livemode after watching has been disabled with `Ctrl+W`.

When working on a long test I prefer to use livemode to reduce the overhead on test startup.
However, it can often be the case, that watching is not desired: My IDE is set to save when I switch focus. When bugfixing a test, there are often several such focus changes. I don't want all of them to trigger a new testrun, so i disable watching.
Once I am done i would like to just start a new testrun with `Ctrl+R`. However, this does not work. I first have to restart watching and only then can I start a new testrun. I then have to disable watching again, so I can fix the next error.

Would it be possible to allow `Ctrl+R` to restart tests, even if watching has been disabled?

**Comment by Farfurix** [comment]
@Khartir 

Hello,

Thank you for describing your case. We'll consider introducing this enhancement.
