### ISSUE TITLE
IE cuts the page url if it is assigned to title

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#559]
Since the release of `testcafe-browser-natives@0.11.0` we use general approach when searching for IE windows, and do it by enumerating window titles. It caused failures of screenshot functional tests, because we are still putting page URLs to the window title, and unfortunately IE cuts them if they are too long. As an example for the screenshot test
url was
`http://127.0.0.1:2000/sj5drnbq/http://localhost:3000/api/es-next/take-screenshot/pages/index.html `
and title was:
`[ http://127.0.0.1:2000/sj5drnbq/http://localhost:3000/api/es-next/take-screenshot/pages/index. - internet explorer`
`html` part of URL was missing.

So I propose to put `TestRunId` in window title instead of page url. What do @inikulin, @helen-dikareva think about it?

**Comment by helen-dikareva** [comment]
I agree of course, because too long page Urls will provide us problems in future, not only for functional tests

**Comment by inikulin** [comment]
> So I propose to put TestRunId in window title instead of page url. 

As far as I remember we've discussed to use `browserWindowId` in context of browser providers. Maybe we will switch to it now? TestRun id is intrinsic thing of `testcafe` it's not quite good to use it in utility library which browser-native will become.

**Comment by AndreyBelym** [comment]
That's fine, except I thought that this is urgent. In that case fix for this issue will be delayed until browser providers will be merged.

**Comment by inikulin** [comment]
OK, let's go with test run id for now

**Comment by helen-dikareva** [comment]
ok
