### ISSUE TITLE
Fail tests on warnings

### ISSUE THREAD

**Issue by benmonro** [DevExpress/testcafe#5594]
### What is your Test Scenario?
We've seen a few team members accidentally use `t.expect(Selector)` w/out using `.exists`. This of course triggers the warning 
```sh
 Warnings (1):
 --
  You passed a Selector object to 't.expect()'.
  If you want to check that a matched element exists, pass the
  'selector.exists' value instead.
```

### What are you suggesting?
I would like to be able to configure testcafe to throw an error in this case so the developer knows to use `.exists`

### What alternatives have you considered?

a lint rule, but that could get very hairy and the runtime clearly is aware of it.

**Comment by Farfurix** [comment]
@benmonro 

Hello,

Thank you for your suggestion.

**For the team**.
See the "Treat errors as warning" feature description [here](https://docs.microsoft.com/en-us/visualstudio/ide/configuring-warnings-in-visual-basic?view=vs-2019#turning-warnings-off-and-on).
