### ISSUE TITLE
Could not login into google account using Chrome

### ISSUE THREAD

**Issue by takaaptech** [DevExpress/testcafe#5596]
Hi Everyone!
Currently, I log in to Google account with the command:
testcafe chrome:userProfile main.js
or 
testcafe chrome main.js

Then Google does not allow us to log in. I can log in to it before.
Is there any solution to this login? Thank you so much!
![image](https://user-images.githubusercontent.com/6276251/94800631-0f247480-040f-11eb-8f46-4abd032fb264.png)

**Comment by Farfurix** [comment]
@takaaptech 

Hello,

Please track our progress [here](https://github.com/DevExpress/testcafe-hammerhead/issues/2438). I closed this issue as a duplicate.

**Comment by takaaptech** [comment]
Hi, @Farfurix Thank you! I will follow that thread, Hope we can find a way to pass that issue!
