### ISSUE TITLE
External javascript produces error only when using testcafe

### ISSUE THREAD

**Issue by elgreg** [DevExpress/testcafe#5599]
### What is your Test Scenario?

I'm trying to do some basic tests of our login page https://slate.com/sign-in - in this case, just simply opening it.
 
### What is the Current behavior?

Any test of this page throws an error about one of our analytics vendors, permutive. But the page in just a regular browser does not throw the error:

```
 ✖ it produces a permutive error

   1) A JavaScript error occurred on "https://slate.com/sign-in".
      Repeat test actions in the browser and check the console for errors.
      If you see this error, it means that the tested website caused it. You can fix it or disable tracking JavaScript
      errors in TestCafe. To do the latter, enable the "--skip-js-errors" option.
      If this error does not occur, please write a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      TypeError: Cannot read property 'generateKey' of undefined
          at generateKey (https://cdn.permutive.com/16d3bd5c-bf92-4bf0-815a-eac397d3aadf-web.js:2:56392)
          at f.storeGivenOrGeneratedKey (https://cdn.permutive.com/16d3bd5c-bf92-4bf0-815a-eac397d3aadf-web.js:2:54968)
          at https://cdn.permutive.com/16d3bd5c-bf92-4bf0-815a-eac397d3aadf-web.js:2:54886
```

 
### What is the Expected behavior?

There should not be a javascript error
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

https://slate.com/sign-in

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
fixture("Slate login test").page(`https://slate.com/sign-in`);

test("it produces a permutive error", async t => {
  await t.wait(5000);
});
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
  "browsers": "chrome:headless",
  "src": "./test/e2e/**/*.js",
  "reporter": {
    "name": "xunit",
    "output": "res.xml"
  }
}

```
</details>

<details>
<summary>Your complete test report:</summary>

```
 ✖ it produces a permutive error

   1) A JavaScript error occurred on "https://slate.com/sign-in".
      Repeat test actions in the browser and check the console for errors.
      If you see this error, it means that the tested website caused it. You can fix it or disable tracking JavaScript
      errors in TestCafe. To do the latter, enable the "--skip-js-errors" option.
      If this error does not occur, please write a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      TypeError: Cannot read property 'generateKey' of undefined
          at generateKey (https://cdn.permutive.com/16d3bd5c-bf92-4bf0-815a-eac397d3aadf-web.js:2:56392)
          at f.storeGivenOrGeneratedKey (https://cdn.permutive.com/16d3bd5c-bf92-4bf0-815a-eac397d3aadf-web.js:2:54968)
          at https://cdn.permutive.com/16d3bd5c-bf92-4bf0-815a-eac397d3aadf-web.js:2:54886
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

Run this simple test:

```
fixture("Slate login test").page(`https://slate.com/sign-in`);

test("it produces a permutive error", async t => {
  await t.wait(5000);
});

```

And it should error out.

### Your Environment details:
 
* testcafe version:                   1.8.4
* node.js version:                    v12.14.1
* command-line arguments:  testcafe chrome -r spec
* browser name and version:  Chrome 85.0.4183.121
* platform and version:          macOS 10.15.6
* other:

**Comment by SergeyShurygin** [comment]
Hi,

I reproduced this issue on Windows in Chrome and FireFox. I used testcafe version 1.9.4 on node 12.18.3.  We'll look into it.

**Comment by elgreg** [comment]
Great! Happy to help debug if I can be of assistance.

**Comment by jbradenclickfunnels** [comment]
I have the same behavior happening for 'digest' of undefined on our login page. Nothing in the console, but tests fail. Any ETA on which release this fix will be a part of?

**Comment by miherlosev** [comment]
Hi folks,

The tested site works correctly only with the HTTPS connection due to the cryptography used on client side.
You need to run tests using the HTTPS protocol. See an instruction [here](https://testcafe.io/documentation/402839/guides/advanced-guides/test-https-features-and-http2-websites).
