### ISSUE TITLE
Script that worked in version 1.5.0 but no longer works in 1.9.4.

### ISSUE THREAD

**Issue by Sabou44** [DevExpress/testcafe#5600]
### What is the current behavior?

 
I have a script that worked in version 1.5.0 but no longer works in 1.9.4.
When I run the coffee test script, the following error occurs: 
```js
 e[t].log is undefined
```

In debugging it turns out this line corresponds to a simple console.log(..)

![Capture01](https://user-images.githubusercontent.com/59806062/94913459-9a524880-04a9-11eb-94e9-b03e12f15084.PNG)

### Steps to reproduce:

1. Download [test-simple-example.js.txt](https://github.com/DevExpress/testcafe/files/5317336/test-simple-example.js.txt) (remove extension .txt)
2. Download [basic-page-model.js.txt](https://github.com/DevExpress/testcafe/files/5317337/basic-page-model.js.txt) (remove extension .txt)
3. run `testcafe firefox test-simple-example.js`
 
### Environment details:
 
* testcafe version:                   1.9.4 
* node.js version:                    10.16.3 
* browser name and version: firefox 81.0 but same problem on chrome 85.0.4183.121
* platform and version:          Windows 10 Pro

**Comment by Ogurecher** [comment]
@Sabou44, Thank you for your report. We would love to assist you and diagnose this issue. However, your website sits behind a proxy and requires authentication, so I was not be able to access it. Our policy prevents us from accessing a customer’s internal resources without a written approval from the entity that owns the server/web resource. If you'd like us to research the issue further, we’ll need access to the server/web resource. Please ask the website owner to send us ([support@devexpress.com](mailto:support@devexpress.com)) a written confirmation. It must permit DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes.
 
Also, we would recommend you to remove the credentials from the attached file and send them to [support@devexpress.com](mailto:support@devexpress.com).

**Comment by Sabou44** [comment]
Thanks for your response but I'm not sure I understand the problem.
We have made a public server specifically for our request. What do you need to access?

**Comment by arubtsov** [comment]
@Sabou44,

Thank you for your cooperation. The page you shared requires authentication. I see that you gave us credentials, however, our policy prevents us from accessing it without a written confirmation from the resource owner. So could you please send a confirmation to our email address (support@devexpress.com)?

**Comment by Sabou44** [comment]
Okay thanks !
An email has just been sent ;)

**Comment by Ogurecher** [comment]
@Sabou44, Thank you for the confirmation email. I've reproduced this issue. I got a slightly different error message than the one you shared, but it's clear that both of them refer to the same object.
We need more time to investigate the issue. Once it's fixed, we'll update this thread.

For the team:

The error message:
```
1) A JavaScript error occurred on "https://wc-111-giessen.sodius.cloud/Windchill/app/#ptc1/tcomp/infoPage?ContainerOid=OR%3Awt.pdmlink.PDMLinkProduct%3A127278&oid=VR%3Awt.part.WTPart%3A127515&u8=1".
      Repeat test actions in the browser and check the console for errors.
      If you see this error, it means that the tested website caused it. You can fix it or disable tracking JavaScript errors in TestCafe. To do the latter, enable the "--skip-js-errors" option.
      If this error does not occur, please write a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      TypeError: Cannot read property 'slice' of undefined
          at http://172.27.63.129:62528/testcafe-driver.js:1:9880
          at Array.forEach (<anonymous>)
          at Yn.getCopy (http://172.27.63.129:62528/testcafe-driver.js:1:9841)
          at ra.set (http://172.27.63.129:62528/testcafe-driver.js:1:54095)
          at ra._onConsoleMessage (http://172.27.63.129:62528/testcafe-driver.js:1:56707)
          at t.<anonymous> (http://172.27.63.129:62528/testcafe-driver.js:1:83391)
          at t.emit (http://172.27.63.129:62528/hammerhead.js:15:5984)
          at console.window.console.<computed> [as log] (http://172.27.63.129:62528/hammerhead.js:6:17322)
          at Object.Sodius.windchill.loader.onReady (https://wc-111-giessen.sodius.cloud/Windchill/netmarkets/javascript/util/windchill-all.js:3100:52)
          at EXTUTIL.Event.fire (https://wc-111-giessen.sodius.cloud/Windchill/netmarkets/javascript/util/ext-and-extensions.js:59:325)

      Browser: Chrome 85.0.4183.121 / Windows 10

          9 |
         10 |const page = new Page();
         11 |
         12 |const selectProvider= async(t)=>{
         13 |    await t
       > 14 |           .click(page.spanCollaborationLink)
         15 |           .click(page.plusLinkButton)
         16 |           .click(page.combo_linkkinds)
         17 |           .click(page.combo_linkkindsOption.withText(linktype))
         18 |           .click(page.combo_providers)
         19 |           .click(page.combo_providersOption.withText('CLI-E2E-PROJECT'))

         at <anonymous> (D:\Work\tests\log-test\test-simple-example.js:14:4)
         at selectProvider (D:\Work\tests\log-test\test-simple-example.js:12:7)
         at <anonymous> (D:\Work\tests\log-test\test-simple-example.js:26:8)
         at <anonymous> (D:\Work\tests\log-test\test-simple-example.js:24:1)
```

![image](https://user-images.githubusercontent.com/28919867/95559310-35a26b00-0a20-11eb-9789-2d81f68f9c5d.png)

TestCafe v1.9.4

**Comment by Sabou44** [comment]
Hi,
@Ogurecher do you have more informations ?
Thanks

**Comment by Ogurecher** [comment]
@Sabou44, we don't have any updates on this issue.

**Comment by frejfrej** [comment]
Hi @Ogurecher 
Do you have any hint on when we shall expect an update on this? Or if we should at all?
Kind regards,

**Comment by Ogurecher** [comment]
@frejfrej, We can't share a time frame as any personal estimations may be misleading. However, considering the activity in this thread, we've raised the priority for this issue. We will consider fixing it in one of our next sprints.

**Comment by frejfrej** [comment]
Hi @Ogurecher, do you think you're any closer to start working on this than you were last time? 🤞

**Comment by Ogurecher** [comment]
@frejfrej, We haven't started working on this issue yet.

**Comment by frejfrej** [comment]
The test was working with version 1.7.1. Bug was introduced by release 1.8.0-rc.1.

**Comment by arubtsov** [comment]
@frejfrej, thank you for your assistance. We will take this into account while we work on the issue.

**Comment by frejfrej** [comment]
@miherlosev We can confirm that 1.10.0-rc.6 fixes the problem. Thanks a lot!

**Comment by Farfurix** [comment]
@frejfrej 

Hello,

[The linked PR](https://github.com/DevExpress/testcafe/pull/5781) is not yet merged. So, the 1.10.0-rc.6 release candidate version doesn't include these changes. I suggest you check your scenario once again after the next "rc" version containing these changes is released.
