### ISSUE TITLE
Can TestCafe Test Mobile Apps?

### ISSUE THREAD

**Issue by doverradio** [DevExpress/testcafe#5602]
Hello,

I know TestCafe can test mobile browsers but can it test a mobile app?  I am creating a React Native app but I am about to start looking for a testing framework to check for bugs.

**Comment by AlexSkorkin** [comment]
TestCafe is intended to test web applications (including Electron-based web applications). You cannot use it for testing native mobile apps.

P.S. We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)). This looks like a question that would be best to ask [on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - a great platform for users to ask and answer questions.
