### ISSUE TITLE
Error 'The request contains a header that doesn't comply with the specification' when opening page url

### ISSUE THREAD

**Issue by alexeygilmanov** [DevExpress/testcafe#5609]
### What is your Test Scenario?
Trying to open page url.
 
### What is the Current behavior?
Test failed with error: 'The request contains a header that doesn't comply with the specification'.
set NODE_OPTIONS='--insecure-http-parser' as suggested does not help.
 
### What is the Expected behavior?
Test succeeds.
 
### What is your web application and your TestCafe test code?
<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from 'testcafe';

fixture `Example`
    .page `https://checkout.abbyy.com/order/checkout.php`;

test('Test', async t => {
    await t
        .wait(1000)
});

```
</details>

<details>
<summary>Your complete test report:</summary>

```
Using locally installed version of TestCafe.
 Running tests in:
 - Chrome 85.0.4183.121 / Windows 10

 Example
 × Test

   1) A request to "https://checkout.abbyy.com/order/checkout.php" has failed.
      Use quarantine mode to perform additional attempts to execute this test.
      You can find troubleshooting information for this issue at
      "https://go.devexpress.com/TestCafe_FAQ_ARequestHasFailed.aspx".

      Error details:
      Failed to perform a request to the resource at "https://checkout.abbyy.com/order/checkout.php" because of an
      error.
      The request contains a header that doesn't comply with the specification
      "https://tools.ietf.org/html/rfc7230#section-3.2.4".
      It causes an internal Node.js error on parsing this header.

      Invalid characters:
      Character with code "32" in header "    XinOvalF" name at index 0
      Character with code "32" in header "    XinOvalF" name at index 1
      Character with code "32" in header "    XinOvalF" name at index 2
      Character with code "32" in header "    XinOvalF" name at index 3

      To fix the problem, you can add the '--insecure-http-parser' flag to the 'NODE_OPTIONS' environment variable:

      macOS, Linux (bash, zsh)
      export NODE_OPTIONS='--insecure-http-parser'

      Windows (powershell)
      $env:NODE_OPTIONS='--insecure-http-parser'

      Windows (cmd)
      set NODE_OPTIONS='--insecure-http-parser'

      and then start your tests.

      Browser: Chrome 85.0.4183.121 / Windows 10



 1/1 failed (2s)
```
</details>

### Steps to Reproduce:

1. Execute command 'testcafe chrome .\test.js -e'.
2. See the error...
 
### Your Environment details:
 
* testcafe version: 1.9.4
* node.js version: 12.18.4
* command-line arguments:  testcafe chrome .\test.js -e
* browser name and version:  Chrome 85.0.4183.121
* platform and version:  Windows 10

**Comment by Ogurecher** [comment]
I reproduced this issue, but the `--insecure-http-parser` workaround works fine on my side.

![image](https://user-images.githubusercontent.com/28919867/95435659-856b2e80-095b-11eb-98c9-0608d1ad7cc9.png)


Also, I added the [--skip-js-errors](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#-e---skip-js-errors) flag because your website contains a JavaScript error.

It looks like you set the environment variable incorrectly. To make sure the variable is set correctly, add the `echo %NODE_OPTIONS%` command before running a test.

```cmd
set NODE_OPTIONS='--insecure-http-parser'

echo %NODE_OPTIONS%

testcafe chrome tests
```
