### ISSUE TITLE
Assertion ignores a failure if 3 other expects with promises stay in queue after the failed expect. 

### ISSUE THREAD

**Issue by Ivan-Katovich** [DevExpress/testcafe#5611]
If we run a test queue of expects some of which are resolved promises we may miss a failure.

### What is your Test Scenario?

```
fixture `Getting Started`
    .page `http://devexpress.github.io/testcafe/example`;
test('My first test', async t => {
    const somethingAsyncWithTrue= async function(cond) {
        return new Promise((res) => {
            setTimeout(() => {
                res(cond);
            }, 1000);
        });
    };
    await t
        .expect(false).eql(true)
        .expect(true).ok()
        .expect(true).ok()
        .expect(await somethingAsyncWithTrue(true)).ok()
        .expect(await somethingAsyncWithTrue(true)).ok()
        .expect(await somethingAsyncWithTrue(true)).ok();
});

```

### What is the Current behavior?
Test is passed
 
### What is the Expected behavior?
Test have to be failed cause of **.expect(false).eql(true)**

 <details>

- If we add **skipUncaughtErrors: false** then the test is failed at the end and throw such error:

<img width="721" alt="Screenshot 2020-10-08 111043" src="https://user-images.githubusercontent.com/7858279/95432181-f9ef9e80-0956-11eb-9728-4a51afc60e14.png">

 - If we leave only one promised expect:
```
await t
                .expect(false).eql(true)
                .expect(true).ok()
                .expect(true).ok()
                .expect(await somethingAsyncWithTrue(true)).ok()
```
Everything works fine
</details>

### Steps to Reproduce:
1) Write a simple test with my expects queue.
2) Run it 
3) Watch results
 
### Your Environment details:
 
* testcafe version: 1.9.4  
* node.js version: 12.18.1  
* command-line arguments:   **testcafe chrome test.js --skip-uncaught-errors**
* browser name and version: Chrome 85.0.4183.121
* platform and version:  Windows 10 Enterprise

**Comment by AlexKamaev** [comment]
Thank you for pointing out the issue. At the moment, the cause of the issue is unclear. We need to research it in detail. As a workaround, I would suggest you break the chain of `expect` calls as follows:


```JS
    await t.expect(false).eql(true)
    await t.expect(true).ok()
    await t.expect(true).ok()
    await t.expect(await somethingAsyncWithTrue(true)).ok('')
    await t.expect(await somethingAsyncWithTrue(true)).ok('')
    await t.expect(await somethingAsyncWithTrue(true)).ok('')
```

**Comment by Ivan-Katovich** [comment]
> Thank you for pointing out the issue. At the moment, the cause of the issue is unclear. We need to research it in detail. As a workaround, I would suggest you break the chain of `expect` calls as follows:
> 
> ```js
>     await t.expect(false).eql(true)
>     await t.expect(true).ok()
>     await t.expect(true).ok()
>     await t.expect(await somethingAsyncWithTrue(true)).ok('')
>     await t.expect(await somethingAsyncWithTrue(true)).ok('')
>     await t.expect(await somethingAsyncWithTrue(true)).ok('')
> ```

Yes, I know the workaround, but all my tests have been written in expects queue format and it worked correctly for version 1.2.1. Now I just working with update testcafe version for my framework and faced with the issue. 
Thanks for your attention.

**Comment by AlexKamaev** [comment]
Thank you for the additional information.
I checked v1.2.1 and found that the test fails with two errors at the same time:

1. AssertionError: expected false to deeply equal true
2. Unhandled promise rejection.

Thus, even in 1.2.1, the test did not work perfectly. However, it does looks like your main issue starts to appear after 1.2.1.

**Comment by Ivan-Katovich** [comment]
Guys, do you have any estimations about fixing of the bug? 
Test Cafe version update on my production project is on hold due to the issue.

**Comment by aleks-pro** [comment]
Hello @Ivan-Katovich ,

We still have plans to fix this issue, but at the moment I cannot give you estimates regarding it. We will update this thread as soon as we have any news. Of course you are always free to open a Pull Request to fix it. We'd appreciate that.

**Comment by Ivan-Katovich** [comment]
Hi guys, I made some investigation of the problem and have a question:
Is it correct place for setting to zero executionChain property ? ( https://github.com/DevExpress/testcafe/blob/master/src/api/test-controller/index.js ) 

![image](https://user-images.githubusercontent.com/7858279/104939691-cb577a00-59c1-11eb-89c7-1644e8ce7b93.png)

When I removed 140 row then assertion chain started working correctly.

**Comment by wentwrong** [comment]
Thank you for your effort. Since it's difficult to predict how this change would affect the computation of the chain, I think we need to identify the cause of the issue first. Then, we can discuss possible solutions. We haven't researched the issue in detail yet, thus we can't say how well your approach will fit with the current implementation.

**Comment by Ivan-Katovich** [comment]
Just to help you with investigations:
It happens when executor.run() function starts before any of promised values in expect is resolved. It set executionChain to zero, but can not throw an error happened before.
I mean:

**Comment by wentwrong** [comment]
Thanks for researching this further. We'll look into it again with your findings in mind.
