### ISSUE TITLE
Support injecting client scripts asynchronously

### ISSUE THREAD

**Issue by Aaronius** [DevExpress/testcafe#5612]
### What is your Test Scenario?
We're trying to test that a script functions properly when loaded onto our test page asynchronously. In order to do a proper test, we need some way to [inject the script onto the page](https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/inject-client-scripts.html) such that the script loads asynchronously. Currently, when using the `clientScripts` API, it loads our injected script synchronously.

### What are you suggesting?
Add an `async` option to the `clientScripts` API that is a boolean indicating whether the script should be loaded asynchronously. If it should be loaded asynchronously, add an `async` attribute to the script element that TestCafe generates. You may want to do the same with `defer` and `nonce`, as I see those scenarios coming up as well.

### What alternatives have you considered?
Reading in my script file contents in my test file, wrapping the code in a setTimeout, then feeding the resulting code into the `clientScripts` API using the `content` option. That sort of simulates the code being loaded asynchronously, but it's not great.

**Comment by miherlosev** [comment]
Hi @Aaronius 

Thank you for pointing us to the possibility of extending the 'Client scripts' feature in such a way.
