### ISSUE TITLE
TestCafe's own <select> dropdown rendering does not render <empty> options

### ISSUE THREAD

**Issue by stefanschenk** [DevExpress/testcafe#5613]
We have a page with on it a <select> dropdown box. This dropdown box has three options, <empty>, 'Ja' and 'Nee'. When clicking on the <select> with TestCafe it only shows the 'Ja'|'Nee' options and omits the empty one.
I should be able to select the empty option in this dropdown box, just a normal user would be able to.

I'm not sure why TestCafe has it's own method to render the dropdown options (as mentioned by @alexey-lin in another [issue](https://github.com/DevExpress/testcafe/issues/4101#issuecomment-517688217)), but the rendering should be fixed to also include empty options.

Dropdown options when user clicks on it
![image](https://user-images.githubusercontent.com/12391671/95441874-f52ce980-095a-11eb-9af5-cdedda137a1a.png)

Dropdown options when TestCafe clicks on it
![image](https://user-images.githubusercontent.com/12391671/95441906-0118ab80-095b-11eb-97b0-4c85f01a71ad.png)

 
### Your Environment details:
 
* testcafe version: 1.8.6
* node.js version: v12.16.1
* browser name and version: Chrome 81.0.4044.0
* platform and version:  macOS 10.15.7

**Comment by AlexKamaev** [comment]
Thank you for pointing out the issue. I was able to reproduce it. I agree that the empty option should be rendered correctly as in the browser.

I inspected the HTML and found that the empty option exists in the HTML:
```HTML
<div class="tcOptionList-hammerhead-shadow-ui" style="">
    <div class="tcOption-hammerhead-shadow-ui"></div>
    <div class="tcOption-hammerhead-shadow-ui">Ja</div>
    <div class="tcOption-hammerhead-shadow-ui">Nee</div>
</div>
```
However, it does not have any styles, so it is rendered as a div with zero height.

My HTML page:
```HTML
<select>
    <option></option>
    <option>Ja</option>
    <option>Nee</option>
</select>

```
