### ISSUE TITLE
Click on ShadowDOM element does not work after scrolling the page

### ISSUE THREAD

**Issue by gregatp** [DevExpress/testcafe#5615]
### What is your Test Scenario?

- Open web page with elements inside ShadowDOM
- Click on some shadowed element
- Associated action is triggered
- Scroll the page down (the shadowed element should still be in visible area)  
- Click the shadowed element again

### What is the Current behavior?

- TestCafe clicks outside of selected element

### What is the Expected behavior?

- TestCafe should click on selected element and associated action should be triggered
 
### What is your web application and your TestCafe test code?

<details>
<summary>Your website URL (or attach your complete example):</summary>

[https://boltdesignsystem.com/pattern-lab/?p=viewall-components-tabs](https://boltdesignsystem.com/pattern-lab/?p=viewall-components-tabs)
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```javascript
import {Selector} from 'testcafe';

fixture`My fixture`
    .page`https://boltdesignsystem.com/pattern-lab/?p=viewall-components-tabs`;

const iFrame = Selector('iframe');

const tab = Selector(() => document
    .querySelector('bolt-band[size="small"] bolt-tabs')
    .shadowRoot.querySelectorAll('bolt-trigger'));

const tabPanel = Selector('bolt-band[size="small"] bolt-tabs bolt-tab-panel');

const subHeadline = Selector('.c-bolt-band__content bolt-list');
const label = Selector('bolt-text');

test('Check tabs with ShadowDOM', async t => {
    await t.switchToIframe(iFrame)
        // code below works as expected
        // testcafe clicks on elements and associated action are triggered
        .click(tab.nth(0))
        .expect(tabPanel.nth(0).visible).ok()
        .click(tab.nth(1))
        .expect(tabPanel.nth(1).visible).ok()
        .click(tab.nth(2))
        .expect(tabPanel.nth(2).visible).ok()
        // lets scroll page
        .hover(label.withText('Label spacing'))
        .hover(subHeadline.nth(0))
        // testcafe clicks outside of shadowed element
        // so action is not triggered and assertion failed
        .click(tab.nth(0))
        .expect(tabPanel.nth(0).visible).ok();
});
``` 
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```
 ✖ Check tabs with ShadowDOM

   1) AssertionError: expected false to be truthy
      
      + expected - actual
      
      -false
      +undefined
      
      Browser: Chrome 86.0.4240.75 / macOS 10.15.7

         28 |        .hover(label.withText('Label spacing'))
         29 |        .hover(subHeadline.nth(0))
         30 |        // testcafe clicks outside of shadowed element
         31 |        // so action is not triggered and assertion failed
         32 |        .click(tab.nth(0))
       > 33 |        .expect(tabPanel.nth(0).visible).ok();
         34 |});
```
</details>

<details>
<summary>Screenshots:</summary>

![click-shadowed-tab](https://user-images.githubusercontent.com/56645176/95443628-18f12f00-095d-11eb-966d-90b9cbd89849.png)

</details>

### Steps to Reproduce:

- run the test script attached above
 
### Your Environment details:
 
* testcafe version:                   1.9.4
* node.js version:                    v13.14.0
* command-line arguments:  `yarn testcafe chrome tests/clickOnShadowDOM.js`
* browser name and version: Chrome 86.0.4240.75
* platform and version:          macOS 10.15.7
* other:

**Comment by Ogurecher** [comment]
@gregatp, Thank you for your report. I've reproduced this issue. We'll update this thread once it's fixed.

**Comment by jacsamell** [comment]
Any update on this or a workaround?

**Comment by miherlosev** [comment]
Hi @jacsamell

We haven't found the cause of the issue yet. So, we cannot share any workarounds.
We will update this thread as soon as we get any news.

**Comment by Josef-Reichardt** [comment]
I just came across this problem and searched for a workaround.
In my case, it works if I make sure that the browser window is large enough (https://devexpress.github.io/testcafe/documentation/guides/concepts/browsers.html#emulate-screen-size) so that there is no need to scroll in the test.

Not a very good workaround and probably it doesn't work for many scenarios but in my case it has saved me from changing the test framework. The big disadvantage is that we are not able to test our responsive frontend on different dimensions. But maybe it will help someone.

**Comment by AlexSkorkin** [comment]
@Josef-Reichardt,
Thank you for sharing your workaroung.

**Comment by gregatp** [comment]
We are using `ClientFunction` and triggering click directly in the browser as workaround, for example:
```js
const clickTab = ClientFunction(() => document
    .querySelector('bolt-band[size="small"] bolt-tabs')
    .shadowRoot.querySelectorAll('bolt-trigger')[1].click());
    
await clickTab();
```

**Comment by AlexSkorkin** [comment]
@gregatp,
Thank you for sharing your workaround.

**Comment by Josef-Reichardt** [comment]
Is this related to #6207 or are there any other news for this issue?

**Comment by miherlosev** [comment]
For team

The issue is still reproduced with the `testcafe@.1.17.2-alpha.2`.

*The updated example*
```js
import {Selector} from 'testcafe';

fixture`My fixture`
    .page`https://boltdesignsystem.com/pattern-lab/?p=viewall-components-tabs`;

const iFrame = Selector('iframe');

const tab = Selector('bolt-tabs').shadowRoot().find('bolt-trigger');

const tabPanel = Selector('bolt-tabs bolt-tab-panel');

const subHeadline = Selector('bolt-list');
const label = Selector('bolt-text');

test('Check tabs with ShadowDOM', async t => {
    await t.switchToIframe(iFrame)
        .expect(tab.exists).ok()
        // code below works as expected
        // testcafe clicks on elements and associated action are triggered
        .click(tab.nth(0))
        .expect(tabPanel.nth(0).visible).ok()
        .click(tab.nth(1))
        .expect(tabPanel.nth(1).visible).ok()
        .click(tab.nth(2))
        .expect(tabPanel.nth(2).visible).ok()
        // lets scroll page
        .hover(label.withText('Label spacing'))
        .hover(subHeadline.nth(0))
        // testcafe clicks outside of shadowed element
        // so action is not triggered and assertion failed
        .click(tab.nth(0))
        .expect(tabPanel.nth(0).visible).ok();
});

```
