### ISSUE TITLE
TestCafe shows <select> options when the dropdown element is disabled

### ISSUE THREAD

**Issue by stefanschenk** [DevExpress/testcafe#5616]
Not much more to this issue. TestCafe will show the options of <select> dropdown box when this element is disabled in the dom.

Solution: respect `disabled` state of <select> element.

### Your Environment details:
 
* testcafe version:                   1.8.6
* node.js version:                    v12.16.1
* browser name and version: Chrome 81.0.4044.0
* platform and version:          macOS 10.15.7

Select element with status disabled
![image](https://user-images.githubusercontent.com/12391671/95444847-91a4bb00-095e-11eb-80d0-47298553c2e5.png)

Dropdown options are show even if the select element is disabled
![image](https://user-images.githubusercontent.com/12391671/95445535-6d95a980-095f-11eb-9cf4-6c65fc72d4ad.png)

**Comment by stefanschenk** [comment]
![image](https://user-images.githubusercontent.com/12391671/95445313-2dcec200-095f-11eb-9cfb-ca5f0a53bac9.png)

**Comment by Ogurecher** [comment]
@stefanschenk

Thank you for your report. I've reproduced the issue and we'll update this thread once it's fixed.
For the team: see [https://github.com/DevExpress/testcafe-hammerhead/pull/2346](https://github.com/DevExpress/testcafe-hammerhead/pull/2346) - this might be a bug in this PR's implementation.
