### ISSUE TITLE
Issue using Promise.allSettled() in testcafe

### ISSUE THREAD

**Issue by costag1982** [DevExpress/testcafe#5623]
### What is your Test Scenario?
In one of my tests I was trying to use Promise.allSettled() but I get the following error:

`1) TypeError: _promise2.default.allSettled is not a function`

Is Testcafe doing anything funky with promises under the hood?

I am using node v14.9
 
### What is the Current behavior?
This error is surfacing preventing me from using it.

`1) TypeError: _promise2.default.allSettled is not a function`
 
* testcafe version:                   1.9.2
* node.js version:                    14.9.0

**Comment by miherlosev** [comment]
Hi @costag1982

> Is Testcafe doing anything funky with promises under the hood?

TestCafe processed the code of tests using the Babel compiler to support the modern features. It looks like the Promise polyfill doesn't have the `allSettled` method.

It's a bug and we will fix it.

**Comment by costag1982** [comment]
Great thanks 👍
