### ISSUE TITLE
Testafe Studio Real is flopping on Us

### ISSUE THREAD

**Issue by jarosales65** [DevExpress/testcafe#5624]
Test Cafe Studio seemed to be a great tool to deliver test automation quick and easy at my business unit projects, but seems to be seems to be as frustrating, brittle and limited as other test tools.
Our needs are basic: 
We need to navigate to a page, identify elements & assert them as needed. Add edit delete functions, etc.

Yes we figured out how to create test cases recording steps and play them, that was easy but going beyond that the tool flops.
-- If we look for help in your blogs the Q&As in it seem to be beyond our skill level and interests.
-- If we look for tech support we cannot find a phone number or person to contact.
-- If we look for help in your training pages, we only find shallow comments "you can select this button to assert x", yes we got what the button is for, but we need detailed info with steps and examples on how to assert type x while creating or editing a test case. Same for all your functionality, It would be great to have detailed info on each button (what it is for, when to use it, how to use it, etc.).

Would it be possible to get better CS support? a number to call as the issues arise, maybe share desktop? 
TestCafe Studio can be the solution we (lots of companies) have been looking for years, a good UI based tool to automate testing without pretending being a developer, but without your support while we users get proficiency, the tool becomes a time consuming activity for our testers and will stop using it as we did with SE, QTP and many more.

**Comment by AlexSkorkin** [comment]
Hello,

Thank you for your interest in our testing tools.

TestCafe Studio comes with two support options. One is the official DevExpress support through the Support Center at [www.devexpress.com/ask](https://www.devexpress.com/ask). The second version is a Community edition where the product's community will help you on StackOverflow.com. Find more details at [https://www.devexpress.com/products/testcafestudio/#pricing](https://www.devexpress.com/products/testcafestudio/#pricing).

You can obtain free support when starting a 30-day trial of TestCafe Studio: [https://www.devexpress.com/products/testcafestudio/#download-trial](https://www.devexpress.com/products/testcafestudio/#download-trial)

This repository is intended for the open-source TestCafe version and TestCafe Studio is not supported here.
