### ISSUE TITLE
Video recording is not supported by chrome browser when using --user-data-dir

### ISSUE THREAD

**Issue by nestoru** [DevExpress/testcafe#5627]
testcafe version 1.9.1
useragent: "Chrome 85.0.4183.121 / Linux 0.0"

1. Add flag --user-data-dir to chrome browser
2. Result: Videos will not be recorded
3. Expected: Videos to record even when using a specific --user-data-dir since it is convenient to define where the browser will store all navigation related data
4. Remove --user-data-dir from chrome browser
5. Videos will be recorded

**Comment by AlexKamaev** [comment]
Hello.
When you are using the `--user-data-dir` flag TestCafe requires to specify the cdpPort argument in the command line. Please try the following command:
`testcafe "chrome:emulation:cdpPort=9222 --user-data-dir=your_user_data_dir" test.js --video artifacts/videos --speed 0.3`

If it does not help feel free to ask further questions here.

**Comment by miherlosev** [comment]
Add a note about it in https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/screenshots-and-videos.html#record-videos
