### ISSUE TITLE
TestCafe does not identify the WebElement when I divide the login steps in multiple tests. See example.

### ISSUE THREAD

**Issue by JainVirender** [DevExpress/testcafe#5628]
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by JainVirender** [comment]
Following is working:
test('Login Test App', async t => {
    await t
        .typeText(email, data.login)
        .click(submit_email)
        .wait(3000)
	.typeText(pass, data.pass)
        .click(submit_pass)
});


But following is not working:

test('Enter user', async t => {
    await t
        .typeText(email, data.login)
        .click(submit_email)
        .wait(3000)
});
test('Enter Pass', async t => {
    await t
	.typeText(pass, data.pass)
        .click(submit_pass)
});

Test application is one angular web application.

**Comment by Farfurix** [comment]
@JainVirender 

Hello,

It looks like your last test is incorrect, the login procedure cannot be divided into two tests. [TestCafe resets the browser state between tests](https://devexpress.github.io/testcafe/documentation/how-it-works/#isolated-test-runs). I suggest you use [User Roles](https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/authentication.html#user-roles) or [Fixture.beforeEach](https://devexpress.github.io/testcafe/documentation/reference/test-api/fixture/beforeeach.html) to automate your login procedure.

If you have some specific logic for the login procedure, please share a simple project (or a public URL) that demonstrates the issue.

**Comment by JainVirender** [comment]
Hi,

My question was on why the testcafe is not working when test steps are divided in two parts. I forgot to mentioned that I was getting error message ="The specified selector does not match any element in the DOM tree."
Today I notice that Testcase is re-initiating browser just before each test and giving error that selector not found.

let me share one another example. If I make one test for Login and another test for search any record then 2nd test is still failing. 
Because when testcafe starts the 2nd test then it re-initiate/refresh browser. It look like in each test I have to give login steps + steps for validate individual functionality.
I am not able to find any way to keep my webpage active for 2nd test, 3rd test. 
Re-login just before each test is too costly for me.
_
[App_Sample.js.txt](https://github.com/DevExpress/testcafe/files/5386968/App_Sample.js.txt)

[Abc_login.js.txt](https://github.com/DevExpress/testcafe/files/5386969/Abc_login.js.txt)

_

Either I am not able to divide steps in 2-3 test in correct structure or the Testcafe work such way that each test will open Brower, perform some steps and after that close the browser.  

I am also struggling to find step for, 
1. execute test on already open test application in Chrome Brower.
2. enter user inputs like OTP in middle of login process.

Regards,
Virender

**Comment by arubtsov** [comment]
@JainVirender,

"My question was on why the testcafe is not working when test steps are divided in two parts."

It is considered good practice to keep tests isolated from each other, so TestCafe reloads a page before each test (you can refer to [this](https://devexpress.github.io/testcafe/documentation/how-it-works/#isolated-test-runs) article as @Farfurix mentioned). Since a page is reloaded, any changes made in the previous test (for example, entering an email using the `typeText` action) will not persist in the next test.

We usually track GitHub issues for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)). If you have any questions, please ask them on [StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe). StackOverflow is an amazing platform for users to ask and answer questions; the community will see your inquiry and help you there.
