### ISSUE TITLE
Click on element doesn't work properly

### ISSUE THREAD

**Issue by aleks-pro** [DevExpress/testcafe#5629]
You can find details (e.g. test example) in the following private ticket: https://supportcenter.devexpress.com/internal/ticket/details/T930974

### Your Environment details:
 
* testcafe version:                   1.9.3
* node.js version:                    v12.18.0
* command-line arguments:  testcafe chrome test.js --skip-js-errors
* browser name and version: Chrome 86.0.4240.75
* platform and version:          macOS 10.15.6

**Comment by AlexKamaev** [comment]
the same issue in HH https://github.com/DevExpress/testcafe-hammerhead/issues/2313

**Comment by AlexKamaev** [comment]
fixed in https://github.com/DevExpress/testcafe-hammerhead/issues/2313
