### ISSUE TITLE
typeText does not input text in Autocomplete textbox (React component)

### ISSUE THREAD

**Issue by mlukjanska25f** [DevExpress/testcafe#5631]
The typetext does not seem to input the desired text in the Autocomplete textbox (React component)

### What is your Test Scenario?
I would like to input text in the autocomplete textbox and then select one of the matching options.
 
### What is the Current behavior?
The text field remains empty after execution.
 
### What is the Expected behavior?
The text that is specified in textbox is entered in the respective text field. 
Note: the pressKey function works and inputs the text.
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Website: https://goluggo.com/</summary>
</details>

<details>
<summary>Test code:</summary>

 
```js
import { Selector } from 'testcafe';

fixture `Sample test`

test
  ('Sample test', async t => {
      await t
        .navigateTo('https://www.goluggo.com/')
        .expect(Selector('#root').visible).ok()
        .expect(Selector('span').withText('Login').visible).ok()

        // typeText does not work - no text is entered in the field
        .typeText(Selector('label').withText('Arrival airport'), 'Riga (RIX)', { paste: true })

        // pressKey works - the respective letter is entered in the field
        //.click(landingPage.arrivalAirport)
        //.pressKey('R')
        .debug()
        .pressKey('down')
        .pressKey('enter')
    }); 
```
</details>

<details>
<summary>Complete configuration file (if any):</summary>

```
{
    "screenshots": {
        "path": "./tests/artifacts/screenshots/",
        "fullPage": true,
        "takeOnFails": true
    }
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```
$ yarn run testcafe chrome tests/e2e/test.js
yarn run v1.22.4
$ <path_to_project>/node_modules/.bin/testcafe chrome tests/e2e/test.js
 Running tests in:
 - Chrome 86.0.4240.75 / macOS 10.15.7

 E2E flow Tests
 ✓ D2D E2E flow


 1 passed (1m 01s)
✨  Done in 74.63s.
```
</details>

<details>
<summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/55700572/96008808-d6859180-0e37-11eb-8dd1-fd5a00c6fe8a.png)

</details>

### Steps to Reproduce:

1. Go to the website https://goluggo.com/ (but please note it is the production version, so please be gentle with number of attempts)
3. Execute ```.typeText(Selector('label').withText('Arrival airport'), 'Riga (RIX)', { paste: true })```
4. The 'Arrival airport' field remains empty
 
### Environment details:
 
* testcafe version:                   1.8.8
* node.js version:                    v12.18.3
* command-line arguments:  yarn run testcafe chrome tests/e2e/test.js
* browser name and version: Chrome 86
* platform and version:           macOS 10.15.7

**Comment by AlexanderMoiseev** [comment]
Hello, 

You should use a selector for the input field. In your case, try using ‘Selector('.MuiFormControl-root.MuiTextField-root input’)’. If you have any other questions, please report to stackoverflow since we keep only bugs and suggestions on github

**Comment by mlukjanska25f** [comment]
@AlexanderMoiseev Thanks, I thought I was already using a Selector :)
