### ISSUE TITLE
Add alias for all installed headless browsers

### ISSUE THREAD

**Issue by Vinnl** [DevExpress/testcafe#5641]
### What is your Test Scenario?

I am automatically running tests in CI, where browsers need to run in headless mode, on different operating systems.

### What are you suggesting?

I'd like to be able to make TestCafe autodetect all browsers that are installed in the CI environment it is running in (i.e. like [the `all` alias](https://devexpress.github.io/testcafe/documentation/guides/basic-guides/run-tests.html#run-tests-in-all-installed-browsers)) and are capable of running in headless mode (e.g. an `all:headless` alias).

### What alternatives have you considered?

I am currently just manually enumerating `chrome:headless,firefox:headless`. I could also hardcode in my CI script to use those on Linux, and add `edge:headless` on Windows and OS X. (And Safari on the latter if that supports headless mode.)

### Additional context

N/A

**Comment by Farfurix** [comment]
@Vinnl 

Hello,

Thank you for your request. We'll consider implementing this feature, however, I cannot give you any estimates.
