### ISSUE TITLE
Fixture.afterEach hook should be called even if Fixture.beforeEach fails with an error

### ISSUE THREAD

**Issue by xorxero** [DevExpress/testcafe#5644]
### What is your Test Scenario?

If one of my tests fail, i basically want to dump the browser console or network logs to see what went wrong.

### What are you suggesting?

Add an option to allow us to add a callback for when an error occurs, then we can perform our debugging logic

### What alternatives have you considered?

Print console in after each of the fixture but it doesn't call the after each when an error happens

### Additional context

Sometimes my tests are failing inconsistently when my pipeline is running. I'm looking at the screenshot and there is an error message on screen but i have nothing else to work with. I can't reproduce the error on my computer and it only happens on the CI sometimes.

**Comment by SergeyShurygin** [comment]
Hi,

Normally, TestCafe should execute the test.after method if tests fail. It isn't executed only if an error occurred in the test.before method. Could you please create a sample where the test.after is not called in a failed test and share it with us?

Another way to call some method when error occurs is to wrap problematic statements and assertions in a try/catch block.

Here is an example:

```
import { Selector } from 'testcafe';

fixture `Getting Started`
    .page `http://devexpress.github.io/testcafe/example`;

test('My first test', async t => {
    try {
         await t.click('#submit-button-invalid')
    }
    catch(e){
        console.log("error logged in try/catch");
        throw e
    }
}).after(async t => {
    console.log("error logged in test.after");

});
```
This sample prints both "error logged in try/catch" and "error logged in test.after" messages on my side.

**Comment by xorxero** [comment]
> Hi,
> 
> Normally, TestCafe should execute the test.after method if tests fail. It isn't executed only if an error occurred in the test.before method. Could you please create a sample where the test.after is not called in a failed test and share it with us?
> 
> Another way to call some method when error occurs is to wrap problematic statements and assertions in a try/catch block.
> 
> Here is an example:
> 
> ```
> import { Selector } from 'testcafe';
> 
> fixture `Getting Started`
>     .page `http://devexpress.github.io/testcafe/example`;
> 
> test('My first test', async t => {
>     try {
>          await t.click('#submit-button-invalid')
>     }
>     catch(e){
>         console.log("error logged in try/catch");
>         throw e
>     }
> }).after(async t => {
>     console.log("error logged in test.after");
> 
> });
> ```
> 
> This sample prints both "error logged in try/catch" and "error logged in test.after" messages on my side.

Hey 

Just looked and yeah looks like the error is happening in my beforeEach where I try to navigate to a certain page then conduct the test there. So, i'm not getting anything printed, i guess i'll try to wrap my beforeEach in a try/catch but would make sense if afterEach is fired regardless of what happened in the before/beforeEach. 

Thanks

**Comment by SergeyShurygin** [comment]
Thank you for pointing this out. We'll discuss this with the team.
