### ISSUE TITLE
TypeError: Failed to execute 'append' on 'FormData'

### ISSUE THREAD

**Issue by LeComptoirDesPharmacies** [DevExpress/testcafe#5647]
Hi, I'm using `testcafe` version `1.9.4` and I have a **bug when I try to upload a document** when `material-table` is imported in the react component. I don't think material table is the only library who can trigger this error, but its the only one I found for now.

### What is your Test Scenario?
Upload a file in an input with `material-table` imported in the component.
 
### What is the Current behavior?

I have this error when I try to upload a file with `setFilesToUpload` : 

`
TypeError: Failed to execute 'append' on 'FormData': parameter 2 is not of type 'Blob'.
at FormData.r.FormData.r.FormData.append (http://10.49.5.89:53610/hammerhead.js:12:24062)
`
 
### What is the Expected behavior?

The `FormData.append` should not failed.
 
### What is your web application and your TestCafe test code?
```
import { Selector } from 'testcafe';

fixture `code sandbox`
    .page `https://gks59.csb.app/`;


test('Test upload', async t => {
    await t
        .setFilesToUpload(Selector('input#myfileinput'), 'test.pdf');
});
```
 
You can have access to the sandbox at this url : https://codesandbox.io/s/lively-forest-gks59?file=/src/FileUpload.js

If you comment the `material-table` import, the upload will succeed. 

### Steps to Reproduce:

- Run the code above with testcafe : `testcafe chrome test.js --debug-on-fail`

 
### Your Environment details:
 
* testcafe version:                   `1.9.4`
* node.js version:                    `v14.6.0`
* command-line arguments:  `testcafe chrome test.js --debug-on-fail`
* platform and version:           `macOS 10.15.7`
* material-table:                       `1.67.0`
* react:                                      `16.13.1`

### Ticket related : 

- https://github.com/DevExpress/testcafe/issues/4965
- https://github.com/mbrn/material-table/issues/2560

**Comment by Ogurecher** [comment]
@LeComptoirDesPharmacies, Thank you for your report. I reproduced this issue. We'll update this thread once it's fixed.

**For the team:**
It's possible that the issue is caused by an [incorrect append override](https://github.com/DevExpress/testcafe-hammerhead/blob/7aae9888576cc34a320e52579b2dab7dc5684b4f/src/client/sandbox/node/window.ts#L801) in testcafe-hammerhead.

**Comment by zoudx** [comment]
Could I know when the issue will be solved @Ogurecher @AndreyBelym ? my cases was blocked

**Comment by miherlosev** [comment]
For team:

The cause of the issue - [FileListWrapper](https://github.com/DevExpress/testcafe-hammerhead/blob/a878aefb01e45c3dc58d9d92da6e618cbc494c4c/src/client/sandbox/upload/file-list-wrapper.ts) doesn't store the origin type of file [entry](https://github.com/DevExpress/testcafe-hammerhead/blob/a878aefb01e45c3dc58d9d92da6e618cbc494c4c/src/client/sandbox/upload/file-list-wrapper.ts#L50).
