### ISSUE TITLE
Support 'multiple windows' feature in custom browser providers

### ISSUE THREAD

**Issue by stefanschenk** [DevExpress/testcafe#5651]
I've updated to testcafe v1.9.4 and I would like to make use of the new multi-windows support. However I use a custom browser provider.

I would like information or documentation about implementing multi-browser support in a custom browser provider.
Or perhaps the TestCafe browser provider generator can be updated to include this awesome feature.

Thanks in advance.

**Comment by AlexKamaev** [comment]
At this moment, this feature is at the 'beta' stage. Implementation details may be changed before the release. This is why we don't announce 'multiple windows' support for a custom browser provider and cannot give any recommendations on the implementation of this feature. Once it is released, we will consider supporting multiple windows for custom browser providers.
