### ISSUE TITLE
Doubleclicking is too slow!

### ISSUE THREAD

**Issue by deep-cognite** [DevExpress/testcafe#5654]
### What is your Test Scenario?

Upon doubling clicking a row in the table, the map should fly to to a location.
 
### What is the Current behavior?

 Fly to doesn't work.

### What is the Expected behavior?

Should fly to location 

### What is your web application and your TestCafe test code?

 None.

---

I've tested this in various ways, however, nothing seems to work. In production (live) double clicking dispatches an event that triggers the flyTo function. However, double clicking is Testcafe acts as if it is a single click.  Any way of increasing the speed of the double click?

### Your Environment details:
 
* testcafe version:  1.9.3                 
* node.js version:      12.18.4              
* command-line arguments: ```
BASE_URL=https://localhost:11111 \
      testcafe \
        "chrome '--use-gl=swiftshader --disable-software-rasterizer --window-size=1500,1040'" \
        testcafe/* \
        --live \
        --screenshots-on-fails \
        --screenshots testcafe/screenshots \
        --video testcafe/videos \
        --video-options failedOnly=true \
        "${@:2}" 
```<!-- example: "testcafe ie,chrome -e test.js" -->
* browser name and version: chrome 85.0.4183.121 <!-- example: IE 11, Chrome 69, Firefox 100, etc. -->
* platform and version:    OSX      <!-- example: "macOS 10.14, Windows, Linux Ubuntu 18.04.1, iOS 12 -->
* other:                                   <!-- any notes you consider important -->

**Comment by arubtsov** [comment]
Hello @deep-cognite,

Thank you for reaching out to us. If I run the following test in Chrome on macOS Catalina, everything works fine:

```javascript
import { Selector } from 'testcafe';

fixture `Double click`
    .page `w3schools.com/jsref/tryit.asp?filename=tryjsref_ondblclick`;

test('Double click', async t => {
    await t
        .switchToIframe('#iframeResult')
        .expect(Selector('p').nth(1).textContent).eql('')
        .doubleClick(Selector('p').nth(0))
        .expect(Selector('p').nth(1).textContent).eql('Hello World');
});
```

Could you please share your public page URL or a small example so that we can reproduce the issue on our side?
