### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by suchitrak** [DevExpress/testcafe#5656]
Steps to reproduce:
Clone this repo - https://github.com/testcafeuser/TestcafeIssue.git
execute the command from terminal  testcafe chrome test1.js --hostname localhost --video artifacts/videos/

I see the below error:

```
mbp-010210:testcafeIssue` myusername$ testcafe chrome test1.js --hostname localhost --video artifacts/videos/
Using locally installed version of TestCafe.
 Running tests in:
 - Chrome 86.0.4240.111 / macOS 10.15.7

 Getting Started
^C^C^C^C^C^C


^C
<--- Last few GCs --->

[26589:0x102811000]   117971 ms: Mark-sweep 1272.4 (1440.4) -> 1256.9 (1436.9) MB, 5096.6 / 81.1 ms  (average mu = 0.072, current mu = 0.041) allocation failure scavenge might not succeed
[26589:0x102811000]   118056 ms: Scavenge 1270.9 (1436.9) -> 1261.9 (1439.4) MB, 9.1 / 0.3 ms  (average mu = 0.072, current mu = 0.041) allocation failure 
[26589:0x102811000]   118126 ms: Scavenge 1272.5 (1439.4) -> 1265.6 (1440.4) MB, 10.6 / 0.4 ms  (average mu = 0.072, current mu = 0.041) allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x1640471dbe3d]
Security context: 0x18af5729e6e9 <JSObject>
    1: /* anonymous */(aka /* anonymous */) [0x18af83d50369](this=0x18afab8026f1 <undefined>,0x18af83d4ffc1 <Error map = 0x18af4c4750b9>)
    2: StubFrame [pc: 0x1640471c1811]
    3: StubFrame [pc: 0x16404719f83a]
    4: EntryFrame [pc: 0x164047184ba1]
    5: ExitFrame [pc: 0x1640471dbe3d]
    6: _tickCallback [0x18af36305039] [internal/process/next_tick.js:...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003d051 node::Abort() [/Users/myusername/.nvm/versions/node/v10.19.0/bin/node]
 2: 0x10003d25b node::OnFatalError(char const*, char const*) [/Users/myusername/.nvm/versions/node/v10.19.0/bin/node]
 3: 0x1001b90e5 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/myusername/.nvm/versions/node/v10.19.0/bin/node]
 4: 0x100587042 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/myusername/.nvm/versions/node/v10.19.0/bin/node]
 5: 0x100589b15 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/Users/myusername/.nvm/versions/node/v10.19.0/bin/node]
 6: 0x1005859bf v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/myusername/.nvm/versions/node/v10.19.0/bin/node]
 7: 0x100583b94 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/myusername/.nvm/versions/node/v10.19.0/bin/node]
 8: 0x10059042c v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/myusername/.nvm/versions/node/v10.19.0/bin/node]
 9: 0x1005904af v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/myusername/.nvm/versions/node/v10.19.0/bin/node]
10: 0x100575f1c v8::internal::Handle<v8::internal::FixedArray> v8::internal::Factory::CopyArrayAndGrow<v8::internal::FixedArray>(v8::internal::Handle<v8::internal::FixedArray>, int, v8::internal::PretenureFlag) [/Users/myusername/.nvm/versions/node/v10.19.0/bin/node]
11: 0x100652211 v8::internal::Isolate::EnqueueMicrotask(v8::internal::Handle<v8::internal::Microtask>) [/Users/myusername/.nvm/versions/node/v10.19.0/bin/node]
12: 0x1006c07ff v8::internal::JSPromise::TriggerPromiseReactions(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::PromiseReaction::Type) [/Users/myusername/.nvm/versions/node/v10.19.0/bin/node]
13: 0x10081814e v8::internal::Runtime_RejectPromise(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/myusername/.nvm/versions/node/v10.19.0/bin/node]
14: 0x1640471dbe3d 
15: 0x164047418060 
Abort trap: 6
```

**Comment by Dmitry-Ostashev** [comment]
I was unable to reproduce the issue on my side with the ffmpeg library version 4.3.1. Could you please clarify node.js and ffmpeg library versions you are using?

**Comment by testcafeuser** [comment]
When I execute the tests in headless mode I don't see the error.  Does testcafe allow video recording/take screenshots only in headless mode?

"test:recordvideo": "testcafe chrome:headless test1.js --hostname localhost --video artifacts/videos/"

**Comment by arubtsov** [comment]
@testcafeuser, TestCafe does not restrict video recording only to headless mode. Still, no luck in reproducing this issue. Does it persist or occur randomly? Could you please share the result of `require('@ffmpeg-installer/ffmpeg').version`?

**Comment by rob4629** [comment]
I'm also seeing this issue in our CI runs, using `"@ffmpeg-installer/ffmpeg": "^1.0.20"`. Our `.testcaferc.json` file includes:

```json
"videoOptions": {
  "singleFile": false,
  "failedOnly": true,
  "pathPattern": "${TEST_INDEX}/${RUN_ID}_${FILE_INDEX}.mp4"
},
"videoPath": "artifacts/recordings"
```

And results in:
```sh
./scripts/test: line 47:   127 Killed                  DESKTOP="$DESKTOP" ENV="$ENVIRONMENT" NODE_PATH='./' node ./node_modules/testcafe/bin/testcafe -u "$BROWSER" $SMOKES $RETRY $DEBUG $TESTPATH
Exited with code exit status 137
CircleCI received exit code 137
```

I'll try to revert to an older version, and see if that makes a difference

**Comment by miherlosev** [comment]
Folks,
The problem is related to the lack of free memory. By default, the memory limit in Node.js is 512 MB. To solve this issue, you need to increase the memory limit with the [max-old-space-size](https://nodejs.org/api/cli.html#cli_max_old_space_size_size_in_megabytes) flag.

```js
node --max-old-space-size=1536 node_modules/testcafe/bin/testcafe chrome test.js
```

**Comment by rob4629** [comment]
Hi @miherlosev, thanks for your response. Upon including `--max-old-space-size=1536`, I'm still seeing the same error occur:

```sh
<--- Last few GCs --->

[139:0x3fa82a0]   232721 ms: Mark-sweep 1525.8 (1559.7) -> 1523.8 (1538.7) MB, 241.7 / 27.5 ms  (+ 489.6 ms in 104 steps since start of marking, biggest step 20.7 ms, walltime since start of marking 872 ms) (average mu = 0.266, current mu = 0.227) finaliz

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x215c991c08a1 <JSObject>
    0: builtin exit frame: new Error(aka Error)(this=0x3c17672c0589 <the_hole>,0x238c21c0e501 <String[#10]: not opened>,0x3c17672c0589 <the_hole>)

    1: ConstructFrame [pc: 0x12f223a]
    2: enqueueCommand [0x2b61d3545d91] [/home/circleci/regression-qaa/node_modules/chrome-remote-interface/lib/chrome.js:~126] [pc=0x38747521d478](this=0x10ff8047cfc9 <EventEmitter map = 0x12bbae015f61>,0x28e7bab...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x9dab70 node::Abort() [node]
 2: 0x9dbd26 node::OnFatalError(char const*, char const*) [node]
 3: 0xb3b18e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb3b509 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xce68a5  [node]
 6: 0xce6f36 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xcf2dca v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xcf3cd5 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xcf66e8 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [node]
10: 0xcbe401 v8::internal::Factory::NewFrameArray(int, v8::internal::AllocationType) [node]
11: 0xc8e648  [node]
12: 0xc8eef3 v8::internal::Isolate::CaptureAndSetSimpleStackTrace(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::FrameSkipMode, v8::internal::Handle<v8::internal::Object>) [node]
13: 0xca0520 v8::internal::ErrorUtils::Construct(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::FrameSkipMode, v8::internal::Handle<v8::internal::Object>, v8::internal::ErrorUtils::StackTraceCollection) [node]
14: 0xbd58f5 v8::internal::Builtin_ErrorConstructor(int, unsigned long*, v8::internal::Isolate*) [node]
15: 0x1376359  [node]
./scripts/test: line 47:   139 Aborted                 (core dumped) DESKTOP="$DESKTOP" ENV="$ENVIRONMENT" NODE_PATH='./' node --max-old-space-size=1536 ./node_modules/testcafe/bin/testcafe -u "$BROWSER" $SMOKES $RETRY $DEBUG $TESTPATH

Exited with code exit status 134
CircleCI received exit code 134
```

Any further suggestions? As previously mentioned, I'll revert to an older version just now, and test

**Comment by miherlosev** [comment]
The target problem is still `out-of-memory". The problem is not reproduced (or reproduced less frequently) in headless mode because the headless mode consumes less memory than the mode with GUI.

I've looked for a way to increase the max memory limit for the Circle CI build and it looks like that it's possible only for paid plans (see [comment](https://discuss.circleci.com/t/increase-4g-memory-limit/9070/5)). Try to use a paid plan or decrease the memory usage of test execution (don't use the `concurrency` feature, etc.).

**Comment by rob4629** [comment]
> The target problem is still `out-of-memory".

I agree.... but the _cause_ of the `out-of-memory` is ffmpeg recording failures. I'm now experiencing this problem locally, with 32GB of RAM...  using `--max-old-space-size=4096`.

The crash seems to occur for tests that use multiple windows (`PayPal` specifically). Any test that doesn't utilise a child window seems to fail and move on to the next test without any issues.

**Comment by miherlosev** [comment]
I'm glad that the cause of the issue is clear now. It looks like the `ffmpeg` library has some [issues](https://trac.ffmpeg.org/search?q=memory+leak&noquickjump=1&ticket=on) with memory usage. At present, it's difficult to determine the exact `ffmpeg` issue that occurred in your environment. `ffmpeg` is constantly updated. Let's see how `ffmpeg` will work in future versions.

**Comment by samplehub** [comment]
Hi , Can you reopen the issue please asap and look into it. 
This issue is defo happening when the test is trying to recording on multiple windows .
I have increased the RAM to 4096 ,still its happening.
Is there any permanent solution to this??
Any other alternative libraries for video recording on testcafe??

**Comment by AM1988** [comment]
Hi @miherlosev ,

I am seeing the same issue when running the tests on gitlabCI

`<--- Last few GCs --->
[65:0x7fba286a82a0]   569724 ms: Mark-sweep (reduce) 4094.4 (4101.0) -> 4093.5 (4102.2) MB, 2355.8 / 12.0 ms  (average mu = 0.083, current mu = 0.005) allocation failure scavenge might not succeed
[65:0x7fba286a82a0]   572166 ms: Mark-sweep (reduce) 4094.5 (4101.2) -> 4093.7 (4102.5) MB, 2430.7 / 12.2 ms  (average mu = 0.044, current mu = 0.005) allocation failure scavenge might not succeed
<--- JS stacktrace --->
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
Aborted (core dumped)`

I am using the official docker image and executing the tests

`/opt/testcafe/docker/testcafe-docker.sh "chromium --start-maximized --incognito" -c 1 e2e/tests/*.test.ts --skip-js-errors --color --reporter spec,xunit:e2e/tests/reports/index.xml,html:e2e/tests/reports/index.html,custom:e2e/tests/reports/result.json --video e2e/tests/reports/video --video-options singleFile=false,failedOnly=true,pathPattern='${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}'.mp4 -s takeOnFails=true,path=e2e/tests/reports/screenshots,fullPage=true,pathPattern='${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}'.png --page-load-timeout 90000 --assertion-timeout 60000 --page-request-timeout 60000 -q attemptLimit=2,successThreshold=1`

Could you please provide the example of how to set that --max-old-space-size=4096 (as far as understood from the error I have to set it to 4096)? 

Should it be something like

`/opt/testcafe/docker/testcafe-docker.sh --max-old-space-size=4096 "chromium --start-maximized --incognito" e2e/tests/*.test.ts`?

Or maybe is it possible to set this parameter inside the docker container and if yes would be great if you can provide an example?

Thanks in advance!

**Comment by miherlosev** [comment]
Hi @AM1988

There is no capability to pass Node.js flags to the TestCafe run command in the docker image.
To build a custom docker image, you need to update the following line: https://github.com/DevExpress/testcafe/blob/8d7cddf07ef075b112d95bfd05aa352280262dcf/docker/testcafe-docker.sh#L9. 

Here's how you can do it:
```js
node --max-old-space-size=4096 /usr/lib/node_modules/testcafe/bin/testcafe-with-v8-flag-filter.js --ports 1337,1338 "$@"
```

Check the [docker-build](https://github.com/DevExpress/testcafe/blob/8d7cddf07ef075b112d95bfd05aa352280262dcf/Gulpfile.js#L424) gulp task to see how we build an official TestCafe docker image.

**Comment by samplehub** [comment]
Hi @miherlosev,

This issue is happening for me locally for the automation tests which involve switching between multiple windows etc., 
Initially , I thought this was some bug related to video recording but later I disabled recording videos and can still this issue happening. 

This issue is with Testcafe API 
https://testcafe.io/402900/resources/blog/2020-8-26-introducing-multi-window-tests-beta

Can you please look into this further and provide a solution ??

Thanks
Deepti

**Comment by AM1988** [comment]
> ```js
> --max-old-space-size=4096
> ```

Thank you @miherlosev for the useful information. I will create a custom image.

I see it beneficial to have the capability to set/pass node flags, maybe it might be an improvement feature, what do you think?

**Comment by miherlosev** [comment]
> I see it beneficial to have the capability to set/pass node flags, maybe it might be an improvement feature, what do you think?

@AM1988 I agree with you. I created a separate [issue](https://github.com/DevExpress/testcafe/issues/6581) for this with label `enhancement`.

> This issue is happening for me locally for the automation tests which involve switching between multiple windows etc.,

Initially, I thought this was some bug related to video recording but later I disabled recording videos and this issue still occurs.
@samplehub
We need a simple example to find the cause of the issue. Please create a [simple example](https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue) and share it with us.
