### ISSUE TITLE
An error auth0-spa-js must run on a secure origin.is shown when a user tries to login to a portal which has a redirect to auth0

### ISSUE THREAD

**Issue by theTainted** [DevExpress/testcafe#5663]
### What is your Test Scenario?
When the user accesses the homepage, the User will be re-directed to a login screen with is auth0

 
### What is the Current behavior?
A blank page is shown and the console has the below error
```
Uncaught (in promise) Error: 
      auth0-spa-js must run on a secure origin.
      See https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-do-i-get-auth0-spa-js-must-run-on-a-secure-origin 
      for more information.
```

 
### What is the Expected behavior?
User should be allowed to log in
 
### What is your web application and your TestCafe test code?
Apologies, I can't share the URL for the application

### Steps to Reproduce:
Access a website which has a redirect to an auth0 login 
Try logging in
 
### Your Environment details:
 
* testcafe version:     1.9.4
* node.js version:       12.18.2
* command-line arguments:  
* browser name and version: Chrome 86 
* platform and version:          Windows 10
* other:

**Comment by Ogurecher** [comment]
@theTainted,

Thank you for your report. I could not reproduce this issue.
I tried to open the auth0 login page from the auth0 homepage at https://auth0.com.
Here is the test I used:

```js
import { Selector } from 'testcafe';
 
fixture('auth0').page('https://auth0.com');
 
test('Login', async t => {
    await t
        .click(Selector('header a').withText('LOGIN'))
        .typeText(Selector('input').withAttribute('name', 'email'), 'MY_EMAIL')
        .typeText(Selector('input').withAttribute('name', 'password'), 'MY_PASSWORD')
        .click(Selector('button').withAttribute('name', 'submit'));
})
```

 
If this test passes on your side, please share an example that we could use to reproduce the issue.

**Comment by theTainted** [comment]
@Ogurecher  
This works if you access the auth0 login page directly. The issue occurs when there is a silent re-direct to the auth0 page.
An example is : access https://awebsite.com  and then the user will get redirected to the login screen of awebsite.com (which is actually redirected to auth0.  Please note that awebsite.com is just a random site.

**Comment by Ogurecher** [comment]
@theTainted, Thank you for the clarification.

It looks like auth0 requires a secure HTTPS-connection.
You can run TestCafe with `--hostname localhost` as most modern browsers treat localhost as a secure origin.
If that does not work, try to establish an HTTPS-connection as explained [in the documentation](https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/test-https-features-and-http2-websites.html).

**Comment by theTainted** [comment]
@Ogurecher  
I had tried the above-mentioned solutions and unfortunately and it didn't work.

**Comment by Ogurecher** [comment]
@theTainted,

Could you please share a page (URL or html code) where we can run a test to reproduce this issue?
This doesn't have to be your actual application. An example page that illustrates the same behavior will be sufficient.

**Comment by theTainted** [comment]
Thanks for the comment, I will post an example as soon as i have one.

**Comment by theTainted** [comment]
@Ogurecher I have got this working with the solution https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/test-https-features-and-http2-websites.html. I had to add the OpenSSL bin to my environment variables manually.
Thanks for the help. You can close this and if I encounter a problem again, I will create a new ticket.
