### ISSUE TITLE
Performance Issues with Brotli Compression

### ISSUE THREAD

**Issue by scyman** [DevExpress/testcafe#5670]
### What is your Test Scenario?
Hi there,

we are using TestCafe for E2E testing of an Angular SPA. After migrating our infrastructure serving the app to the latest version of AWS CloudFront, we noticed failing tests. After a little bit of investigation, we are quite certain that this is related to [AWS adding support for Brotli content encoding](https://aws.amazon.com/de/about-aws/whats-new/2020/09/cloudfront-brotli-compression/).
After disabling Brotli explicitly so that gzip is used again, the tests are running fine again, as they were before.
 
### What is the Current behavior?
When executing the tests, the initial page load takes a long time. Loading the main Webpack bundle takes around 90s for 1.1 MB.
The network tab in Chrome running the tests shows it has to wait nearly all of the 90s for the first byte to be transferred (time-to-first-byte).
 
### What is the Expected behavior?
Before enabling Brotli, after disabling it again or with a previous version of Firefox, which favored gzip over Brotli, we had absolutely not performance issues, so we are quite sure this is indeed related to the content encoding using Brotli.
 
### What is your web application and your TestCafe test code?
Unfortunately, I cannot share any code from the application, but I am quite sure to be able to provide a minimal example to reproduce the problem, if needed.

### Your Environment details:
 
* testcafe version:                   1.9.4
* node.js version:                    v13.12.0
* browser name and version: Chrome Version 86.0.4240.111 (x86_64)
* platform and version:          macOS 10.15.7
* gherkin-testcafe: 2.5.2

Thanks!

**Comment by miherlosev** [comment]
TestCafe processes `brotli` and `gzip` encoded data with native Node.js functions. It's unexpected that the `time to first byte` parameter of the tested page depends on its encoding.

So, yeah, a simple example would be appreciated.
