### ISSUE TITLE
Ability to add attachments other than screenshots and videos

### ISSUE THREAD

**Issue by xiaoxinghu** [DevExpress/testcafe#5671]
### What is your Test Scenario?

It is useful to be able to attach extra information to test cases. E.g. a more detailed log file (so you don't overwhelm people with massive `console.log`s), a record of all rest API calls, test coverage or statistical info from 3rd party plugins or packages etc... We have native support for saving screenshots and videos in a very organized fashion, with customizable paths. It would be nice to be able to add arbitrary data in the mix and take advantage of the existing path pattern.

### What are you suggesting?

A couple of ideas, but probably not very well thought out, need input from the community.
- add API to attach data to test cases. `t.attach(filePath)` or `t.attach(content)` to associate these information to the current running test. It will use the path pattern defined in the config or a default one if it doesn't exist.
- generalize the "Attachment" concept, screenshots and videos are also attachments. so the API would be: `t.add(attachment)`, and attachment type is something like this:
```typescript
interface Attachment {
  type: 'screenshot' | 'video' | 'text'; // + something else I am not aware of?
  name: string; // will be used as the part of the file name on the file system
  data: string | buffer;
}
```
The existing API will use `add` function underneath, but also expose it publicly for flexibility and extensibility. This idea came from [Apple's XCTest framework](https://developer.apple.com/documentation/xctest/activities_and_attachments/adding_attachments_to_tests_activities_and_issues?language=objc).
- an even more flexible plugin API? Make the whole attachment thing an external plugin. testcafe will provide APIs to retrieve raw data of screenshots and videos, but don't care about where you put them. Plus more metadata will be provided to plugins.

### What alternatives have you considered?

Implementing some kind of plugin to organize all files by myself, but the metadata of the tests is limited (see #2826). Also, it seems to be a reinventing-the-wheels kind of work since we have screenshots and videos implemented already.

### Additional context

N/A

**Comment by AlexKamaev** [comment]
Hello, thank you for your input.

>E.g. a more detailed log file (so you don't overwhelm people with massive console.logs), a record of all rest API calls, test coverage or statistical info from 3rd party plugins or packages, etc...

We have ideas on how to improve the user debugger experience and add some new functionality. However, it is too early to speak about it in detail. Anyway, thank you for sharing your thoughts.

As for your attachment concept, could you please describe it in detail? Where do you want to use these attachments, in a custom reporter? Could you please describe a real test case in which you need to use this concept and clarify how you are going to use it? In what cases will you add attachments to your test code and how will you check if the attachment is added?

**Comment by xiaoxinghu** [comment]
Here is a real-life example, It all started with a very intermittent issue only happens in our CI pipelines. It's running in headless mode within a docker container, so debugging is not possible. So we need to gather as much information as possible. I decided to record all the API calls, I use the request logger to capture the requests and responses, Now I need to put them in files instead of print it out on the console (because it's a lot). Also, they have to be associated with individual test cases to be meaningful.

Then there're other ideas like custom reporter plugins, we can associate any kind of file to the tests (in addition to images and videos), and rely on testcafe to organize them. E.g. performance metrics data, screenshot comparison etc.

**Comment by AlexKamaev** [comment]
Thank you for the detailed explanation. As far as I understand, you wish to collect some debugging info to find the cause of the issue. We have an opened issue about debugging - [https://github.com/DevExpress/testcafe/issues/2413](https://github.com/DevExpress/testcafe/issues/2413), and we'll try to improve the debugging experience in the future.
You can use the code from the following comment to get request logs: [https://github.com/DevExpress/testcafe-hammerhead/issues/2449#issuecomment-694703396](https://github.com/DevExpress/testcafe-hammerhead/issues/2449#issuecomment-694703396).
As for attachments, at this moment, we are not ready to make plans for this. However, we'll keep your suggestion in mind.
