### ISSUE TITLE
[docs] Typo in the "Test HTTPS Features" article

### ISSUE THREAD

**Issue by Ogurecher** [DevExpress/testcafe#5672]
https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/test-https-features-and-http2-websites.html

> Most modern browsers **thread** localhost as a secure origin, and some built-in browser features that require a secure origin (Service workers, GeoAPI) should work.

I believe, we meant **treat**, not **thread**.

**Comment by VasilyStrelyaev** [comment]
Fixed by https://github.com/DevExpress/testcafe/commit/81672b1fbf591d176200a9c7892a462de5760c9d

Thanks!
