### ISSUE TITLE
Proxy missing identifiers when making Auth0 request on SPA

### ISSUE THREAD

**Issue by alexpthomasdev** [DevExpress/testcafe#5674]
### What is your Test Scenario?

We would like to sign in using Auth0 with the flag useRefreshToken enable.
 
### What is the Current behavior?

On call to auth0 token, we have a 404 error (page not found) due to testcafe proxy missing identifier:

Example request failed: http://localhost:1337//https://dev-thomas.eu.auth0.com/oauth/token

Example request working when the useRefreshToken flag is disable: http://localhost:1337/pEoiZVXss*WYH65fc4A
/https://dev-thomas.eu.auth0.com/oauth/token

### What is the Expected behavior?

We expect the proxy to correctly intercept the request to the token, please look at the example above.
 
### What is your web application and your TestCafe test code?

 
Using the sample application from auth0 (https://github.com/auth0/auth0-spa-js), force the useRefreshToken to be true always and then run the test.
What we do is:

AUTH0 Credentials
```
 var defaultDomain = 'dev-thomas.eu.auth0.com';
 var defaultClientId = 'QxaJHsHhAuVPv4M3uBv99ECfuE6LJgZ3';
 var defaultAudience = '';
```

Testcafe fixture
```
  await t.click(Selector("#login_redirect"));
  await t.typeText( Selector("#username"), "customerTest@thomas.co");
  await t.typeText(Selector("#password"), "Customer1!1");
  await t.click( Selector("button[type='submit']"));
  await t.click( Selector("button[data-cy='get-token']"));
  await t.click(getToken);
```
We are having a "Unexpected end of JSON input" and we want to see the token on the default section.

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
  await t.click(Selector("#login_redirect"));
  await t.typeText( Selector("#username"), "customerTest@thomas.co");
  await t.typeText(Selector("#password"), "Customer1!1");
  await t.click( Selector("button[type='submit']"));
  await t.click( Selector("button[data-cy='get-token']"));
  await t.click(getToken);

```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
 var defaultDomain = 'dev-thomas.eu.auth0.com';
 var defaultClientId = 'QxaJHsHhAuVPv4M3uBv99ECfuE6LJgZ3';
 var defaultAudience = '';
```
</details>

<details>
<summary>Screenshots:</summary>

```
![TestCafe](https://user-images.githubusercontent.com/50017052/97719792-69bcf900-1abf-11eb-9ba1-b56080e2cba3.PNG)

```
</details>

### Steps to Reproduce:

As abode descibed
 
### Your Environment details:
 
* testcafe version:  1.9.4                 
* node.js version:  11.10.1                  
* command-line arguments:  testcafe chrome test
* browser name and version: chrome (not headless) 
* platform and version:    Windows

**Comment by Ogurecher** [comment]
@alexpthomasdev, Thank you for your report.
I reproduced this issue, we'll update this thread once it's fixed.

 

For the team:
```js
import { Selector } from 'testcafe';

fixture`1`.page`localhost:3000`;

test('1', async t => {
    await t
        .typeText(Selector('#domain'), 'dev-thomas.eu.auth0.com', { replace: true })
        .typeText(Selector('#client_id'), 'QxaJHsHhAuVPv4M3uBv99ECfuE6LJgZ3', { replace: true })
        .click(Selector('button').withText('Save'));

    await t.navigateTo('http://localhost:3000');

    await t.click(Selector('#refresh_token_switch'));

    await t
        .click(Selector('#login_redirect'))
        .typeText(Selector('#username'), 'customerTest@thomas.co')
        .typeText(Selector('#password'), 'Customer1!1')
        .click(Selector('button[type="submit"]'))
        .click(Selector('button[data-cy="get-token"]'));

    await t.debug();
});
```

**Comment by dylanz666** [comment]
Any updates on this issue?

**Comment by Farfurix** [comment]
@dylanz666 

Hello,

We have no updates yet.

**Comment by svnindia** [comment]
any workaround there ?

**Comment by Farfurix** [comment]
@svnindia

There is no workaround. We need to research this issue. We'll update this thread once we have any results.

**Comment by danderton** [comment]
We've also hit this blocker, and unable to find away around it. :(

**Comment by wentwrong** [comment]
It seems like the issue was resolved in the latest TestCafe release ('v1.10.0'): the test posted [above](https://github.com/DevExpress/testcafe/issues/5674#issuecomment-720336000) works fine - the access token is shown in the default "Access tokens" section and there is no "Unexpected end of JSON input" message.

If anybody is still experiencing issues with this, please comment here with another example for reproducing the issue and we will reopen it.

**Comment by danderton** [comment]
Thanks @wentwrong. I can confirm this update has fixed our issues.

**Comment by wentwrong** [comment]
@danderton, I'm happy to hear it's resolved for you. Thank you for reporting back.
