### ISSUE TITLE
Feature: Property selectors for lists of values

### ISSUE THREAD

**Issue by GrahamLea** [DevExpress/testcafe#5679]
### What is your Test Scenario?
I want to test that the text of each of the items in a `<ul>` matches what I think it should be.

### What are you suggesting?
`Selector` should include an `innerTextAll: Promise<string[]>` property matcher, that returns the inner text of *each* of the elements matching the Selector. (`innerText` only returns the text of the first).

The suggested naming mirrors the `querySelector`/`querySelectorAll` pairing on `Document`.

There are probably other properties that would benefit from also having an `*All` counterpart, e.g. `textContent`.

### What alternatives have you considered?
Achieving the same functionality currently requires a `ClientFunction` to get all the values at once:
```typescript
export const textOfItems = ClientFunction(
  (nodesSelector: string, trimmed: boolean = true) => {
    const items: NodeListOf<Element> = document.querySelectorAll(nodesSelector);
    const result = [];
    for (let i = 0; i < items.length; i++) {
      const text = (items.item(i) as HTMLElement).innerText;
      result.push(trimmed ? text?.trim() : text);
    }

    return result;
  }
);
```

**Comment by miherlosev** [comment]
Hi @GrahamLea 

Thank you for this suggestion.
The `Selector` object points to the web page elements and in general, has [properties](https://devexpress.github.io/testcafe/documentation/reference/test-api/domnodestate.html) same as web element.
The `HTMLElement` doesn't contain the `innerTextAll` property and the described case happens quite rare among our users, so we are not ready to accept this suggestion.
