### ISSUE TITLE
typeText() is not working if input tag is present in shadow DOM for vue.js

### ISSUE THREAD

**Issue by aman9922** [DevExpress/testcafe#5682]
### What is your Test Scenario?
There is an input tag present in the shadow DOM. I got the webelement by using ClientFunction(). When I tried to enter text to textbox using typeText(), it is not working.
The application under test is developed using vue.js.
I tried to click using click() also. It didn't work and I got no error.

### What is the Expected behavior?
It should enter text in the textbox using typeText()

### Your Environment details:
 
* testcafe version:                   1.9.2
* node.js version:                    v12.18.3
* browser name and version: Chrome latest
* platform and version:         Mac Catlina

**Comment by miherlosev** [comment]
Hi @aman9922 

Could you please share an example illustrating the problem?
