### ISSUE TITLE
Window API: Unable to close 3rd Window

### ISSUE THREAD

**Issue by alexej-strelzow** [DevExpress/testcafe#5685]
### What is your Test Scenario?
I want to test that 3 links work properly and when the user clicks on in some content gets displayed in that new window.
I need the newly opened window to be closed after my check (see code below) otherwise it will hide elements from the main window.
 
### What is the Current behavior?
The first window gets opened and can be closed. Same for the second Window, but the 3rd window gets stuck during closing. I think there might be a bug i the Window API. I get this error:
```js
 Error: {
         code: 'E70',
         isTestCafeError: true,
         callsite: CallsiteRecord {
           filename: 'xxx',
           lineNum: 193,
           callsiteFrameIdx: 6,
           stackFrames: [
             [CallSite], [CallSite],
             [CallSite], [CallSite],
             [CallSite], [CallSite],
             [CallSite], CallSite {},
             [CallSite]
           ],
           isV8Frames: true
         }
       }
```
 
### What is the Expected behavior?
The 3rd window should be closable.
 
### What is your web application and your TestCafe test code?
The website is not publicly available but here is the example code I use:

 
```js
  const initialWindow = await t.getCurrentWindow(); // The ID of the main application

  await t.click($('.link-report a')); // a new Window gets opened that displays a report

  t.expect(await $('.mainpage').child(0).exists).to.eq(true); // some assertion

  const reportWindow = await t.getCurrentWindow();  // the ID of new Report-Window

  await t.switchToWindow(initialWindow); // <---- THIS WORKS every time
  return t.closeWindow(reportWindow);  // <----- THIS STEP DOES NOT EXECUTE PROPERLY THE 3rd TIME
```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
  
* testcafe version:                    1.9.4
* node.js version:                     12.19.0
* command-line arguments:   testcafe chrome -e test.js
* browser name and version:  Chrome Version 86.0.4240.111 (Official Build) (x86_64)
* platform and version:            macOS 10.15.7

**Comment by aleks-pro** [comment]
Hello @alexej-strelzow ,

Thank you for the test code, but it's hard to determine the cause of the issue based on it. Please create a simple Web application example where we can reproduce the issue.
