### ISSUE TITLE
TestCafe cannot start Firefox due to the browser's sandbox malfunction 

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#5689]
### What is your Test Scenario?
Use Firefox with CCNet
 
### What is the Current behavior?
TestCafe opens an empty Firefox window and cannot open the test page
![image](https://user-images.githubusercontent.com/4479386/98380137-39460380-2059-11eb-97bd-7b692b99d07b.png)
  
### What is the Expected behavior?
TestCafe should start the browser and open the test page.

**WORKAROUND**: The `MOZ_FORCE_DISABLE_E10S` environment variable can be set to the full browser version (e.g. `env:MOZ_FORCE_DISABLE_E10S=82.0.2`) to prevent the browser from spawning additional process and conflicting with CCNet.

For the team: we can programmatically get the browser version with `firefox -v` and add this variable to environment.
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   `testcafe v1.9.4`
* node.js version:                    
* command-line arguments:  
* browser name and version: Firefox 82
* platform and version:          Windows 10
* other:                                   CCNet

**Comment by miherlosev** [comment]
We decided to not implement this enhancement because the issue was found on a custom fork of [CCNet](https://cruisecontrol.sourceforge.net/) CI. If somebody encounters the same issue, use a workaround from the description.
