### ISSUE TITLE
Provide more information when "The element that matches the specified selector is not visible"

### ISSUE THREAD

**Issue by GrahamLea** [DevExpress/testcafe#5691]
### What is your Test Scenario?
My test was trying to click on an `<a>` tag that contains a `<div>`, but I was getting the error message `The element that matches the specified selector is not visible`. It turns out this was because (I think) the `<a>` had an auto height. Setting its `display` to `block` solved the problem, but only after an hour of googling and trying many different things. This problem seems to come up often, as evidenced in #1994 and #1988.

### What are you suggesting?
Improve the error message when the element is not visible, by explaining why it's not visible, Examples:
* `... because its display is 'none'`
* `... because its visibility is 'hidden'`
* `... because it has no height`
* `... because it has no width`

In my case, if the error message had said "because it has no height", I probably would have found the problem in a couple of minutes.

**Comment by aleks-pro** [comment]
Hello @GrahamLea ,

Thank you for sharing your idea with us. We already have a corresponding issue: https://github.com/DevExpress/testcafe/issues/3876. You can follow it to be informed about our progress.
