### ISSUE TITLE
HTML rendering issue

### ISSUE THREAD

**Issue by suryap666** [DevExpress/testcafe#5694]
Then submit button is rendered in unexpected place

When I open a browser it looks like shown below

![image](https://user-images.githubusercontent.com/36958912/98762279-63b60900-242b-11eb-8002-df8195691956.png)

When I open the same page using TestCafe

![image](https://user-images.githubusercontent.com/36958912/98762406-ac6dc200-242b-11eb-8b74-1da09f27ad6b.png)

"testcafe": "^1.9.4"

**Comment by Farfurix** [comment]
@suryap666 

Hello,

It is difficult to find the cause of the issue without a runnable example. Could you please share some project or a public URL?

**Comment by suryap666** [comment]
@Farfurix I agree with you, even I thought the same, how to share the page.  according to the company policy, I should not share the application URL, username and password etc.. But I am willing to attach the HTML page in this issue, I am not sure how to. please suggest me the standard to follow.

**Comment by aleks-pro** [comment]
Hello @suryap666,

I'm not sure we will be able to reproduce this issue with an HTML page, but you can pack it into a .zip archive and send to support@devexpress.com.
It's not necessary to provide access to your entire application URL. A simple example created based on your web site code should be sufficient.

**Comment by suryap666** [comment]
I do agree with you, The HTML page will not be helpful, when I am trying to save it in my local, it renders completely in a different way due to lack of full CSS. My application is a monolith code and as a tester, I haven't worked on the application code much. so cannot spare much time to build a sample website @aleks-pro Thanks for your support. I will close this issue for now. Since we are moving from bulk big application to single page application using Vue.js, I am sure this issue will not happen, if it happens, I will log a bug with a sample public-facing website.
