### ISSUE TITLE
TypeText function doesn't provide data attribute on input event

### ISSUE THREAD

**Issue by jogwir** [DevExpress/testcafe#5695]
I am testing an input component which expects the keyed value to exist on the data attribute of the input event. When testing using the TypeText function, the input event is fired, but the data attribute is always set to null.

Example component:
`<input (input)="onInput($event) />`

Example event handler:
`onInput(event: any) {
  console.log(event.data); }`

Example testcafe test: 
`await t.typeText(myInputSelector.get(), '1');`

* testcafe version:  1.8.8, running on Chrome.

**Comment by AlexKamaev** [comment]
I was able to reproduce the issue. Thank you for pointing this out.

**Comment by jogwir** [comment]
No problems Alex, thanks for looking into it. I look forward to a fix.
