### ISSUE TITLE
Base Path Support For Testcafe Server (dev.example.com/testcafe)

### ISSUE THREAD

**Issue by sartaj** [DevExpress/testcafe#5723]
### What is your Test Scenario?

Get Testcafe server to be available from a public url on a base path.

### What are you suggesting?

The hope for us is we can have the testcafe test runner available via a public url path, as I don't want to expose more ports to the outside world, and also make the URL ergonomic for regular users.

For example:

- `staging.coolcompany.com/run-tests`
- `dev.coolcompany.com/tests/e2e`

### What alternatives have you considered?

Currently, you can set the hostname, port, and even proxy, but if the public url needs to be on a path, we are out of luck.

### Willing to Contribute

I was able to get a grungy version working by editing `testcafe-hammerhead`.

I'd be willing to help get this to work as I already had a dumb demo working, but would want the +1 from the squad here before I move forward.

**Comment by miherlosev** [comment]
Hi @sartaj

Do you want to have a web interface or do you need access via the REST API to run tests, get test execution reports, etc.?

**Comment by sartaj-devoted** [comment]
Hi @miherlosev, thanks for the reply. Was hoping to have exposure to the web interface, so that for example a product owner could go `staging.coolcompany.com/run-tests` to see/debug the tests running in the web interface.

**Comment by miherlosev** [comment]
We don't have plans to add a web interface or other ways to communicate with the TestCafe runner. It is designed as a command-line tool - you can only run tests and format test execution results with an appropriate reporter.

For your task, it is better to use continuous integration systems like Jenkins, Travis, TeamCity, etc. They usually have a web interface in which you can run tests and see execution results.
