### ISSUE TITLE
Testcafe isn't seeing any elements inside #document tag

### ISSUE THREAD

**Issue by user-twenty-twenty** [DevExpress/testcafe#5729]
### What is your Test Scenario?
Trying to locate an element nested under #document tag/element

### What is the Current behavior?
Testcafe isn't seeing anything inside #document tag/element
![image](https://user-images.githubusercontent.com/74801767/99864453-33234d00-2b58-11eb-92b3-097004a7aec2.png)

 
### What is the Expected behavior?
Ability to locate elements inside #document tag/element
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>
Office Online Excel

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 await t.switchToIframe('#office_frame')
 await t.expect(Selector('#MainApp').exists).ok()
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```
 1) Content of the iframe in which the test is currently operating did not load.
  > 17 |    await t.expect(Selector(`#MainApp`).exists).ok()

```
</details>

<details>
<summary>Screenshots:</summary>

```
```
</details>

### Steps to Reproduce:

Testcafe is able to locate anything above the #document element.
In the test I successfully switch to the "#office_frame" iframe, then try to verify that one of the nested elements exist(for example '#MainApp' element) but Testcafe isn't seeing it.
I tried setting up larger timeouts, no luck.
I also verified it by running Testcafe's 'childElementCount' and 'childNodeCount' calls on the '#office_frame' iframe which both reported counts of 0 nodes/elements inside that iframe.
I don't have any issues with iframes in other cases, but this #document element doesn't let Testcafe to see any nested elelements.
 
### Your Environment details:
 
* testcafe version:   1.9.4                
* node.js version:  14.15.1                  
* command-line arguments:  
* browser name and version: Chrome 86 
* platform and version: MacOs Catalina          
* other:

**Comment by SergeyShurygin** [comment]
I tried to reproduce this issue on office online and tests passed successfully for me:

```
import { Selector } from 'testcafe';

fixture \\\`fixture 1\\\`
    .page \\\`https://devexpress-my.sharepoint.com/:w:/p/sergey_shurygin/ETe9cjRtnFBOoc3LyJQ7AVcB4q9KG3Ly0lwr9NdM9hzBKQ?e=fSAcCi\\\`


test ('test1', async t => {
    await t
    .switchToIframe('#WebApplicationFrame', { timeout: 10000 })
    .expect(Selector('#MainApp').visible).ok()
});

```

Note: I added a timeout for the switchToIframe operation because without it I get the 'Content of the iframe in which the test is currently operating did not load.' error.

Also, I run the test with the --skip-js-errors flag as there are errors on the Word Online page.

Could you please show your test demonstrating the issue?

**Comment by user-twenty-twenty** [comment]
@SergeySeleznyov thank you,
your test passes for me too, so this "#document" element isn't to blame here then. 
However my test still fails, very strange..
Will post more details soon.

**Comment by arubtsov** [comment]
@user-twenty-twenty, We will wait for the update.

**Comment by user-twenty-twenty** [comment]
I've tried adding timeouts, running with -e flag to skip js errors, but still no luck.
Here's screenshots of the page from the test and some console errors.
I added .debug() step after switching to the iframe and this is when I took the screenshots of the page and errors.
(I had to blur some parts for privacy reasons.)
Very strange that @SergeyShurygin 's test works for me too, but not my own test, they are identical. 
It finds and switches to the iframe but doesn't see anything inside of it.

```
await t
        .switchToIframe(Selector(`#office_frame`, {timeout: 20000}))
        .expect(Selector('#MainApp', {timeout: 20000}).exists).ok()
```

Error
```
1) Content of the iframe in which the test is currently operating did not load.
  > 17 |    await t.expect(Selector(`#MainApp`).exists).ok()
```

![testcafe issue - html](https://user-images.githubusercontent.com/74801767/100164352-85bc7c00-2e6c-11eb-97e6-af1670a6accb.png)

![testcafe issue - console errors](https://user-images.githubusercontent.com/74801767/100164357-88b76c80-2e6c-11eb-84f5-85dca4f141ae.png)

**Comment by SergeyShurygin** [comment]
I also get the "Content of the iframe in which the test is currently operating did not load." error sometimes. This error might occur because the Office Online pages perform heavy rendering (especially on slow machines, e.g. VMs on the CI) and there was more than a 20 sec timeout. Do you still get the error when you increase the timeout in the switchToIFrame action?

**Comment by SergeyShurygin** [comment]
I've noticed that in your code, the timeout is added to the Selector, not to the switchToIframe action as in my code. Thus, the timeout you added doesn't have any effect - the test doesn't wait for the iframe to load. As a result, your test fails.

**Comment by user-twenty-twenty** [comment]
@SergeyShurygin I wasn't able to add the timeout directly to switchToIframe(), Webstorm complained about it 
![image](https://user-images.githubusercontent.com/74801767/100370805-b2cb7480-2fbb-11eb-8232-53314b9b718b.png)

Also I thought adding it to the selector would work the same, based on this Testcafe documentation:
![image](https://user-images.githubusercontent.com/74801767/100370861-ca0a6200-2fbb-11eb-848f-bbdd9a497fb7.png)

**Comment by user-twenty-twenty** [comment]
And I tried increasing the selector timeout to 1 minute, unfortunately same result.

**Comment by SergeyShurygin** [comment]
hi,

Sorry for misleading you. There is no separate timeout option for the switchToIFrame command and the documentation is valid. You need to pass a timeout to Selector in the way it's described there.

My example from the first comment works for you because it ignores the options parameter and uses the default timeout.
To investigate why the timeout it not working in your test, we need a working example that we can use to reproduce the issue.
