### ISSUE TITLE
Documentation Hint for scripts generated using TestCafe Studio for Dinamically Generated Inputs

### ISSUE THREAD

**Issue by fmancardi** [DevExpress/testcafe#5730]
### What is your Test Scenario?
I've a control that when clicked generates and open a popup menu
Here when closed (before click)
![step01](https://user-images.githubusercontent.com/235697/99883981-04c27200-2c2b-11eb-9bff-18cbc14c4f9d.png)

Here the popup has been opened
![step02](https://user-images.githubusercontent.com/235697/99883987-0ee47080-2c2b-11eb-8ca8-04a117c9d533.png)

I want to implement a method resetCustom() , and I've used TestCafe studio to record it, getting this code (is only an excerpt)
.click('#results .btn.dropdown-toggle')
.click(Selector('#results a').withText('Reset'))

I've copied this logic in my test, and when I've runned it using the testacafe command line, sometimes the test failed,
because Selector('#results a').withText('Reset'), takes more time to become visible.
IMHO the best thing to do in my code is to add
if (await Selector('#results a').withText('Reset').exists && await Selector('#results a').withText('Reset').visibile) {
  await t.click(Selector('#results a').withText('Reset'));
}
 

### What are you suggesting?
Probably is too complex for the TestCafe recorder understand that Selector('#results a').withText('Reset') is not always visible,
and add the exists + visible check.
But it will be useful adding some generic text to signal the developer that sometimes the test can fail because
some element can not be visible, advicing the developer to analize better the System Under Test Behaviour

**Comment by Dmitry-Ostashev** [comment]
Hello,
Thank you for your suggestion. However, it's not clear in what cases TestCafe Studio recorder should consider delaying the appearance of an element? Do you need this for a particular element (e.g. <select> <option> or something else)? Could you please describe your thoughts and requirements further?

**Comment by fmancardi** [comment]
Hi
I've hit the following documentation: [say-goodbye-to-flakyness](https://github.com/hdorgeval/testcafe-snippets/blob/master/say-goodbye-to-flakyness.md)

The example there are useful but also scary:
**await t.typetext('#developer-name',"John Doe");**

that according the document author need to be translated in lot of lines.

I've used Test Case Studio to record the (failed) login to https://gitlab.com:

```
fixture `New Fixture`
    .page `https://gitlab.com/users/sign_in`;

test('New Test 1', async t => {
    await t
        .typeText('#user_login', 'testcafe studio test')
        .typeText('#user_password', 'blablabla')
        .click('#new_user .gl-button.btn.btn-success');
});

```
According to the article this test case is flaky, because:
- I'm not using **await ensure_form_is_loaded() // custom method specific to your App**
- I'm not checking the input existence & visibility.

My expectation is that code generated by Test Case Studio **will be NOT flaky**.
That's was I was trying to explain when opening this issue.

Reading the article I've also discovered that I've never understood in the right way or have misunderstood 
the 'Automatic Waiting Mechanism'.

I've seen that you are working in documentation improvement:
- [Describe difference between Selector and assertion timeouts](https://github.com/DevExpress/testcafe/pull/5755/files)
- [Create a best practices article] (https://github.com/DevExpress/testcafe/pull/5603/files)

And that is fantastic.
I think we need the rules to be applied to avoid developing test cases in the wrong way:
I've used tons of times:
`var howMany = await Selector('xx').count;
`
being confident that this was the **right way**, because any time I've used:
`var howMany =  Selector('xx').count;`

I've got 0 as result. But the article said I'm doing wrong.

Also for  
`var isPresent = await Selector('xx').exists;
`
if it is evaluated immediately without waiting for element existence, this need IMHO make **very clear** in the documentation.
I'm pretty sure I've need to read in more detail the documentation, and that anyway no matter it will be lot of
duplication, **it's absolutely CRITIC** that you provide a warning in the documentation of each method that can 
have this effect.
I'm using Test Cafe Studio as my **personal test scripting guru**, that's why IMHO we developers need to get 
the most advice as possible, in the generated code.

Returning to my example, here is the code (an excerpt)
```
        .click('#results .btn.dropdown-toggle')
        .click(Selector('#results a').withText('Reset'))

```
And this will be flaky, depending the elapsed time between 
- the click on the dropdown
- the time the browser takes to display the option 'Reset'.

No matter how 'unfocused' a developer can be while reading the documentation, IMHO a **big heads up** 
is needed when the documentation refers to Selector() usage and **timeouts**.

Hope now things are a little bit clear.

Best regards

**Comment by fmancardi** [comment]
According to your documentation:
>Before an action is performed, TestCafe waits for the target element to be in the DOM and become visible. 
If this does not happen within the selector timeout, the test fails.

In this document: [say-goodbye-to-flakyness](https://github.com/hdorgeval/testcafe-snippets/blob/master/say-goodbye-to-flakyness.md)
(OK it's not maintained or owned by Devexpress) 
There is this note:

> The property getter is immediately invoked. TestCafe will not apply the smart assertion mechanism because the property is not invoked from within an expect statement.

TestCafe waits for the element to appear in a 'smart way' ?

**Comment by fmancardi** [comment]
In the document:
**docs/articles/documentation/guides/basic-guides/select-page-elements.md**

This has been added:

>Selector timeouts have no effect on [Selector.exists](../../reference/test-api/selector/exists.md) and [Selector.count](../../reference/test-api/selector/count.md) properties. These properties are evaluated immediately regardless of a timeout. To apply a timeout to `exists` and `count` assertions, pass the timeout to the assertion method (`expect.ok`, `expect.eql`, etc.).

But sometimes you need to check for element existence and/or visibility, **but do not thrown on failure**, but you need
to execute a different logic.
An example:

You need to navigate a menu and you need to understand if you need to click to open a child or not.
![top-level](https://user-images.githubusercontent.com/235697/101340601-420c3e00-3880-11eb-9adc-0795018827e7.png)

The HTML when the menu is closed:

![closed](https://user-images.githubusercontent.com/235697/101340723-6700b100-3880-11eb-83e9-e1635cc01c5c.png)


The HTML when the menu is open:

![top-open](https://user-images.githubusercontent.com/235697/101340776-7a138100-3880-11eb-8551-50a097869dfe.png)

This code to understand if need is if closed and then open:
 
```
  var roleClosed = 'div#menucontainer ul li.ruolo > a';
  var roleOpen = 'div#menucontainer ul li.ruolo.open > a';

  var top = {};
  top.text = 'UFFICIO ACQUISTI - PROCUREMENT'; 
  top.closed = Selector(roleClosed).child('span').withExactText(top.text);
  top.open = Selector(roleOpen).child('span').withExactText(top.text);

  var closed = {};
  if (await top.open.exists == false || await top.open.visible == false) {
     ....
```
**But if you are not able to have a smart wait mechanism for exists, is this code flaky?**
How do it need to be re-written?

**Comment by Dmitry-Ostashev** [comment]
Thank you for the detailed explanation.

E2e tests are intended to simulate end-user actions. TestCafe Studio can record these actions, but it cannot detect and record waiting timeouts when the user is waiting for elements to appear on the page. Unfortunately, it's difficult to predict such cases and it's necessary to handle them manually (e.g. by tuning the selector and assertion timeouts or by adding a separate assertion to ensure that an element is visible).

The GitLab login process is not a simple case due to the redirect to the 'Checking your browser before redirecting' page with the 503 server response status. I've created a separate issue to research it: https://github.com/DevExpress/testcafe/issues/5779.

We'll consider implementing a mechanism to wait and check element existence without assertion. Also, we'll discuss how to make our documentation more clear based on your remarks.

**Comment by fmancardi** [comment]
1) I've used the gitlab login example just to provide you a public site that you can access, it was not my intention to provide the 503 use case. Thanks for opening a new issue

2) I understand the adding the timeouts in TestCafe Studio is not simple, that's why I'm suggesting to add some comment inside the generated code with the advice of considering the need of additional checks (exists, visible) and a link to your specific BEST PRACTICES document

thanks a  lot

**Comment by Dmitry-Ostashev** [comment]
Thank you for your feedback and suggestions. We noted it and we'll took it into account. Due to fact that this repository is intended for open-source TestCafe, let's close the issue.

**Comment by fmancardi** [comment]
I will open a ticket then on the support for TestCafe Studio

**Comment by arubtsov** [comment]
@fmancardi, Thank you for your assistance.
