### ISSUE TITLE
Run async code before `.page`

### ISSUE THREAD

**Issue by janhesters** [DevExpress/testcafe#5734]
### What is your Test Scenario?

I have a chat room app. Our team grew and many functional tests run in parallel. We want to generate a new room for each fixture.

### What are you suggesting?

Allow `.before` to run before `.page` in a `fixture` and let `.page` access the context.

```js
fixture`My Fixture`
  .before(async ctx => {
    const roomId = await createRoomId();
    ctx.roomId = roomId;
  })
  .page(ctx => `http:localhost:3000/${ctx.roomId}`);
```

### What alternatives have you considered?

The alternative would be to run the promise and then run the fixtures in it:

```js
createRoomId().then(roomId =>
  fixture`...`.page`...`
  // tests ...
);

**Comment by AlexKamaev** [comment]
You can use the `navigateTo` method of TestController and the `beforeEach` fixture hook to achieve the desired result.
Please see the following example:


```JS
async function createRoomId () {
    return 'test';
}

async function ensureChatRoom (ctx) {
    const roomId = await createRoomId();

    ctx.pageUrl = `http://example.com/${roomId}`;
}

fixture `fixture`
    .before(async ctx => {
        await ensureChatRoom(ctx);
    })
    .beforeEach(async t => {
        await t.navigateTo(t.fixtureCtx.pageUrl);
    });

test(`test 1`, async t => {
    await t.click('h1');
});

test(`test 2`, async t => {
    await t.click('h1');
});

```
