### ISSUE TITLE
disableScreenshots missing from runner.run RunOptions type definition

### ISSUE THREAD

**Issue by viheikki** [DevExpress/testcafe#5735]
### What is your Test Scenario?
I'd like to disable screenshots when running TestCafe using the API with TypeScript.
 
### What is the Current behavior?
TestCafe TypeScript type declarations are missing disableScreenshots field in the RunOptions type.
```
runner.run({
    disableScreenshots: true
});
```
Will result in incompatible type warning.
 
### What is the Expected behavior?
RunOptions should contain the disableScreenshots field like documented in https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/screenshots-and-videos.html#disable-screenshots
 
### What is your web application and your TestCafe test code?
Not relevant. 

### Steps to Reproduce:
1. Create a new TypeScript project and install TestCafe.
2. Create a TS file for running TestCafe with the API and add.
```
runner.run({
    disableScreenshots: true
});
```
3. See the TS warning:
`TS2345: Argument of type '{ disableScreenshots: boolean; }' is not assignable to parameter of type 'Partial<RunOptions>'.   Object literal may only specify known properties, and 'disableScreenshots' does not exist in type 'Partial<RunOptions>'.`
 
### Your Environment details:
 
* testcafe version: 1.9.4
* node.js version: v12.19.0
* command-line arguments: Not relevant
* browser name and version: Not relevant
* platform and version: macOS 10.14.6

**Comment by Ogurecher** [comment]
@viheikki, Thank you for your report. We'll add `disableScreenshots` to the `RunOptions` type.
