### ISSUE TITLE
[docs] Update the CircleCI guide

### ISSUE THREAD

**Issue by VasilyStrelyaev** [DevExpress/testcafe#5737]
Take the new [CircleCI + LambdaTest](https://github.com/DevExpress/testcafe/pull/5716) guide as an example.

**Comment by DIRECTcut** [comment]
I currently can't make CircleCI display xunit test report in the web view. So far it is only available for download via Artifacts.

The amount of passed/failed displays in the "Tests" panel, but te report doesn't.


Related CircleCI forums threads: [1]https://discuss.circleci.com/t/store-test-results-not-working-circle-2-0/11065/9() [2](https://discuss.circleci.com/t/test-result-report-not-detected/11081)
