### ISSUE TITLE
APIv2: implement `Selector` hybrids

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#574]
Unlike hybrids `Selector` returns element descriptor object. Selectors and their results can be used as action selectors. By default it will use our waiting heuristics for element to appear in the DOM. Selectors can return DOM node or `null`. If you want immediate value, you can use `.now` postfix of selector:
```js
const getElement = Selector(id => document.getElementById(id));
const elementNow = await getElement('yo').now;
```

- [x] Throw if hybrid returns DOM node
- [x] `Client code` -> `Hybrid function code`
- [x] Implement  basic `Selector` API
- [x] Node snapshots
  - [x] Element
       -  [x] `nodeType`
       -  [x] `id`
       -  [x] `tagName`
       -  [x] `attributes`
       -  [x] `namespaceURI`
       -  [x] `hasChildNodes`
       -  [x] `childNodeCount`
       -  [x] `hasChildElements`
       -  [x] `childElementCount`
       -  [x] `visible`
       -  [x] `scrollWidth`
       -  [x] `scrollHeight`
       -  [x] `scrollLeft`
       -  [x] `scrollTop`
       -  [x] `offsetWidth`
       -  [x] `offsetHeight`
       -  [x] `offsetLeft`
       -  [x] `offsetTop`
       -  [x] `clientWidth`
       -  [x] `clientHeight`
       -  [x] `clientLeft`
       -  [x] `clientTop`
       -  [x] `focused`
       -  [x] `value`
       -  [x] `checked`  
       -  [x] `boundingClientRect`
       -  [x] `textContent`
       - [x] `classNames`
       - [x] `innerText`
       - [x] `style`
  - [x] Comment
  - [x] Text
  - [x] DocumentFragment
  - [x] Document
  - [x] Methods: `getParentNode`, `getChildNode(i)`, `getChildElement(i)`, `hasClass` 
- [x] Rename `Hybrid` to `ClientFunction`
- [x] Forbid `function` return value for Hybrids: we can't determine kind of hybrid ahead of time

- [x] Cross-browser `innerText`
- [x] Get rid of `Hybrid` term. Introduce `ClientFunctionFactory`s
- [x] Error text adjustment for `Hybrids` and `Selector`
- [x] Selector from string

- [x] Node existence awaiting
- [x] `clientFunction.with()`
- [x] `selector.with({ visibilityCheck: Boolean})` and remove  `t.waitForElement`
- [x] `selector.with({timeout: 0})`
- [x] Use selectors machinery for action selectors
- [x] Auto-conversion in actions: function to selector if passed as parameter.

- [x] Throw if returns anything except `null`, `undefined` or DOM node
- [x] Function `scopeVars`
- [x] Selector result as action parameter
- [x] `t.select`

- [x] Figure out behavior then page load occurs during selector execution

- Select by text command and  `t.selectByText`  (moved to #615)

**Comment by inikulin** [comment]
## Node descriptors

### Element
```js
{
    nodeType: 1,
    tagName: String,
    attributes: { name: value },
    namespaceURI: String,
    hasChildren: Boolean,
    childrenCount: Number,
    getParentNode: Hybrid,
    getChildNodes: Hybrid,
    visible: Boolean,
    width: Number, // element own width in pixels
    height: Number, // element own height in pixels
    offsetWidth: Number,
    offsetHeight: Number,    
    focused: Boolean,
    hasClass: Function,
    text: String,
    textContent: String,
    computedStyle: { prop: value },
    style: { prop: value }
}
```

### CommentNode
```js
{
    nodeType: 8,
    text: String,
    getParentNode: Hybrid
}
```


### TextNode
```js
{
    nodeType: 3,
    text: String,
    getParentNode: Hybrid
}
```

### DocumentFragment
```js
{
    nodeType: 11,
    getChildNodes: Hybrid
}
```

### Document
```js
{
    nodeType: 9,
    getChildNodes: Hybrid
}
```

**Comment by VasilyStrelyaev** [comment]
Regarding `waitForElement`...
Let's assume I'm using a Hybrid to return a value I need to assert. What if I need to wait for a particular element in order to calculate that value? What if this element is invisible?
I may need `waitForElement` as well as `waitForElementVisible`- right?

**Comment by inikulin** [comment]
BTW, interestin question: should regular hybrids accept element descriptors as arguments?

**Comment by inikulin** [comment]
Should selector accept element descriptors?

**Comment by inikulin** [comment]
Or both should accept, but descriptors will not be converted back to actual DOM nodes?

**Comment by VasilyStrelyaev** [comment]
@DevExpress/testcafe ?

**Comment by VasilyStrelyaev** [comment]
Doesn't accepting element descriptors duplicates the `dependencies` mechanism for Hybrids - in a sense?

**Comment by VasilyStrelyaev** [comment]
And just to confirm - `t.eval` produces a regular Hybrid, doesn't it?

**Comment by AlexanderMoskovkin** [comment]
> Should selector accept element descriptors?

I'm not sure for now what is better, but just have a question. If we send an element descriptor to the Selector, what is it on the client, a dom-element or a snapshot of the element?
In other words:
```js
Selector(element => {
// can I use it as a dom-element ..
var loc = element.ownerDocument.location; // or something else

// ... or its just a snapshot?
var width = element.width
});
```

**Comment by inikulin** [comment]
@AlexanderMoskovkin This is exactly what I've asked https://github.com/DevExpress/testcafe/issues/574#issuecomment-223592034
idk

**Comment by AlexanderMoskovkin** [comment]
Oh yes, I understood your comment in the wrong way.

I'm inclined to don't allow to send an element descriptor as an argument. If we allow this we have some unclear things:
1) the question asked above
2) what if the element is not on the page

I think it's better to send Selector as an argument in this case. As I understand the following is allowed:
```js
var getGridRow = Selector(() => document.getElementById('get-row-selector'));
var myCustomSelector = Selector(() => {
    var row = getGridRow();
    //...
}, { getGridRow });
```

**Comment by inikulin** [comment]
We can implicitly execute descriptor's selector if it's passed as argument

**Comment by VasilyStrelyaev** [comment]
What about `t.eval`? https://github.com/DevExpress/testcafe/issues/574#issuecomment-223911488

**Comment by inikulin** [comment]
@VasilyStrelyaev Yes. For selectors we will have `t.select`
