### ISSUE TITLE
Testing an element that is not static but added by a script

### ISSUE THREAD

**Issue by OlgaPakhom** [DevExpress/testcafe#5740]
Hi Testcafe team,
We have a toggle button that is not static but added by a script and the test fails with error "The element that matches the specified selector is not visible." Tried with timeout but it does not help.

toggleButton = Selector(".slider-bg");
lightTheme = Selector(".light-theme"); 

test('Test toggle button in desktop view', async t => {
    await t
        .maximizeWindow()
        .expect(LandingPage.toggleButton.visible).ok({ timeout: 20000 })
        .click(LandingPage.toggleButton)
        .expect(LandingPage.lightTheme.exists).ok()

Could you please help to understand how Testcafe works: it just waits for the elements appears in the DOM and that's it? We need that scripts work and it is not clear if they work or not.

Thanks in advance for hints.

**Comment by SergeyShurygin** [comment]
Hi,

The elements that do not have the "display: none" or "visibility: hidden" CSS properties and have non-zero width and height are considered to be visible. Please check that all these conditions are true for the target element.

Assertion can fail if there are several elements that match the selector and the first of them is not visible.

If the page has only one matching element and it is visible according to the conditions mentioned above, but the test fails anyway, this may be a bug and we need an example to reproduce it.

**Comment by OlgaPakhom** [comment]
Thanks, Sergey
We checked the conditions but the issue is that the elements is visible only after the script is executed. I guess we need something like this https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/inject-client-scripts.html

**Comment by SergeyShurygin** [comment]
TestCafe waits until the execution of scripts is finished. Please refer to [https://devexpress.github.io/testcafe/documentation/guides/basic-guides/assert.html#smart-assertion-query-mechanism](https://devexpress.github.io/testcafe/documentation/guides/basic-guides/assert.html#smart-assertion-query-mechanism).
If it doesn't, there may be a bug.
Could you please share an example page and a test script so that we can investigate the issue?
