### ISSUE TITLE
Screenshot not captured for second tab opened using openWindow

### ISSUE THREAD

**Issue by alexmaddock** [DevExpress/testcafe#5741]
### What is your Test Scenario?
I am wanting a screenshot stored against a second tab after I have called t.openWindow either when there is a failure or when I explicitly call t.takeScreenshot.

But t.takeScreenshot with t.openWindow saves first tab as image not second tab that I am focused on.
 
### What is the Current behavior?
Screenshot is stored against first tab only.
 
### What is the Expected behavior?
Screenshot to be stored against second tab where command invoked.
 
### What is your web application and your TestCafe test code?
 
<details>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector, t } from 'testcafe';

fixture.only `Visit Email Servers`
    .page `https://www.gmail.com`

test('Screenshot for test case', async() => {
    await t.openWindow('https://outlook.com')
    await t.takeScreenshot({path: '/email-screenshot.png'});
})
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
    "browsers": ["firefox:headless", "chrome:headless"],
    "skipJsErrors": true,
    "selectorTimeout": 10000,
    "assertionTimeout": 8000,
    "allowMultipleWindows": true,
    "speed": 1,
    "screenshots": {
        "takeOnFails": true,
        "path": "artifacts/screensots",
        "fullPage": true
    }
}
```

 
* testcafe version:                   v1.9.4
* node.js version:                    v12.16.3
* command-line arguments:  "testcafe 'chrome --start-fullscreen' e2e-tests/**.spec.js -L",
* browser name and version: Version 87.0.4280.67 (Official Build) (x86_64)
* platform and version:          macOS 10.15.7

**Comment by AlexKamaev** [comment]
The screenshots for multiple windows will be available in Chrome-based browsers in v1.10.0. You can test this functionality in the release candidate (v1.10.0-rc.2).

This feature is not implemented in Firefox at this moment. Please track the [https://github.com/DevExpress/testcafe/issues/5699](https://github.com/DevExpress/testcafe/issues/5699) issue to follow the progress.
