### ISSUE TITLE
Unable to typeText non-numerical text into 'number' textfield

### ISSUE THREAD

**Issue by nilshartmann** [DevExpress/testcafe#5747]
### What is your Test Scenario?

I'd like to input chars into a `input[type='number']` field to test my field validations.

This seems to be similiar to #3197
 
### What is the Current behavior?

Using `typeText` or `pressKey` with chars in a numeric input field doesn't change it's value. It keeps empty.

### What is the Expected behavior?

`typeText` and `pressKey` enters even invalid characters into a numeric input field in the same way one can do it in a real browser.
 
### What is your web application and your TestCafe test code?

Almost the same as in #3197 but enter the string `aaa` into the numeric input field.

I also tried to set `paste: true` in the options, as suggested here: https://github.com/DevExpress/testcafe/issues/3197#issuecomment-454369650, but that also doesn't work.

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from "testcafe"; // first import testcafe selectors
// Based on: https://github.com/DevExpress/testcafe/issues/3197

fixture`Getting Started`.page // declare the fixture
`http://nativeformelements.com/`; // specify the start page

test("My first test", async (t) => {
  await t
    .typeText("input[type=number]", "aaa", { paste: true }) // note: it neither works with or without paste: true
    .expect(Selector("input[type=number]").value)
    .eql("aaa");
});

```
</details>

<details>
<summary>Your complete test report:</summary>

```
 Running tests in:
 - Firefox 83.0 / macOS 10.15

 Getting Started
 ✖ My first test

   1) AssertionError: expected '' to deeply equal 'aaa'
      
      + expected - actual
      
      -''
      +'aaa'
      

      Browser: Firefox 83.0 / macOS 10.15

          6 |//then create a test and place your code there
          7 |test("My first test", async (t) => {
          8 |  await t
          9 |    .typeText("input[type=number]", "aaa", { paste: true })
         10 |    .expect(Selector("input[type=number]").value)
       > 11 |    .eql("aaa");
         12 |});
         13 |

         at <anonymous> (/Users/nils/develop/xxx/testcafe/input.test.ts:11:6)
         at <anonymous> (/Users/nils/develop/xxx/testcafe/input.test.ts:8:71)
         at __awaiter (/Users/nils/develop/xxx/testcafe/input.test.ts:4:12)
         at <anonymous> (/Users/nils/develop/xxx/testcafe/input.test.ts:7:35)



 1/1 failed (4s)
```
</details>

### Steps to Reproduce:

1. Go to my nativeformelements.com
2. Select the input with the type number
3. Type in aaa

### Your Environment details:
 
* testcafe version:  1.9.4
* node.js version:  12.16.3
* command-line arguments: testcafe firefox input.test.ts -L
* browser name and version: Firefox 83.0 (64-Bit), Chrome 87
* platform and version:          MacOS 10.15.7 (Catalina)

**Comment by arubtsov** [comment]
Hello @nilshartmann,

Thank you for your input. I was able to reproduce this behavior in Firefox (in Chrome it is expected). Our team will research the issue and find a suitable solution.
