### ISSUE TITLE
switchToWindow doesn't allow you to resize or maximize new window

### ISSUE THREAD

**Issue by Srutherford2407** [DevExpress/testcafe#5748]
### What is your Test Scenario?
Testing a site registration process.
 
### What is the Current behavior?
Navigate to a site.
Click on the register link which opens a new window (smaller window then the main)
Use the switchToWindow action to access that window
If I attempt to resize the new window or maximize the new window and it doesn't alter the new window.
 
### What is the Expected behavior?
switchToWindow followed by the resize or maximizeWindow Action should resize the new window
 
### What is your web application and your TestCafe test code?
It's not a public site.
 
```
Tired:
   await t.switchToWindow(w => w.url.pathname === '/account/register');
   await t.maximizeWindow();

Tired: 
  await t.switchToWindow(w => w.url.pathname === '/account/register').maximizeWindow();

Tired:
   await t.switchToWindow(w => w.url.pathname === '/account/register').resizeWindow(600,600);

Tried:
   await t.switchToWindow(w => w.url.pathname === '/account/register');
   await.resizeWindow(600,600);
```

### Steps to Reproduce:
Navigate to a site.
Click on the register link which opens a new window (smaller window then the main)
Use the switchToWindow() or maximizeWindow() action to access that window
If I attempt to resize the new window or maximize the new window and it doesn't alter the new window.
 
### Your Environment details:
 
* testcafe version:                   1.9.0
* browser name and version: Chrome 86
* platform and version:          Windows 10

**Comment by AlexKamaev** [comment]
The resizing functionality for multiple windows will be available in Chrome-based browsers in v1.10.0. You can test this functionality in the release candidate (v1.10.0-rc.2).

Currently, this feature is not implemented in Firefox. Please track the [https://github.com/DevExpress/testcafe/issues/5700](https://github.com/DevExpress/testcafe/issues/5700) issue to see the progress.
