### ISSUE TITLE
Testcafe hangs with firefox browser only in docker container

### ISSUE THREAD

**Issue by raj-balaebail** [DevExpress/testcafe#5754]
### What is your Scenario?

 Go to https://www.avant.com/
Click on 'Check your loan options' under personal loans
Verify the following page has 'Welcome' in its header.

### What is the Current behavior?

 ERROR The Firefox 68.0 / Linux 0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.

### What is the Expected behavior?

 Tests run on firefox as they run on chromium browser

### What is your public web site URL?

https://www.avant.com/

Your website URL (or attach your complete example): 

<details>
<summary>Your complete app code (or attach your test files):</summary>

 
```js
 fixture("tests")
	.page("https://www.avant.com/")

test('testing', async t => {
  const sel = Selector('a').withText('Check Your Loan Options');
  await t.click(sel)
  await t.expect(Selector('*').withText('Welcome').visible).ok()
})
```
</details>
This is branched off of [2364](https://github.com/DevExpress/testcafe-hammerhead/issues/2364)
docker run -v ~/amount-repos/compost/testcafe:/tests -it testcafe/testcafe:1.8.8-alpha.1 chromium,firefox /tests

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

- Go to https://www.avant.com/
- Click on 'Check your loan options' under personal loans
- Verify the following page has 'Welcome' in its header.
 
### Your Environment details:

* node.js version:                     
* browser name and version: firefox browser packaged in testcafe/testcafe
* platform and version:          
* other:

**Comment by yunj** [comment]
Hi, we are experiencing the same issue. For the time being, we created a custom image and it works. Just wondering if the latest testcafe docker image could have a newer Firefox installed? Thanks.

**Comment by AlexanderMoiseev** [comment]
Hello @yunj

Thank you for your suggestion. We will consider changing firefox' ‘esr’ version to ‘latest’ after the 1.11 release. Stay tuned.
