### ISSUE TITLE
[Docs] Add a note about using `all` browser alias

### ISSUE THREAD

**Issue by wentwrong** [DevExpress/testcafe#5759]
Currently [Run Tests in All Installed Browsers](https://devexpress.github.io/testcafe/documentation/guides/basic-guides/run-tests.html#run-tests-in-all-installed-browsers) section of "Run Tests" guide misses one important point about running tests this way. 

The point is that when we run tests using `all` as a browser alias, all locally installed browsers are being controlled by a special common built-in provider ([src/browser/provider/built-in/locally-installed.js](https://github.com/DevExpress/testcafe/blob/master/src/browser/provider/built-in/locally-installed.js)). As a result, provider-specific functionality is not working.

For example, when tests are run in TestCafe Docker image with `all` browser alias, TestCafe throws an error:
> ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.

This happens because the built-in provider for locally-installed browsers doesn't apply Chromium-specific flags like `--no-sandbox`, which should be specified to run Chromium in unprivileged Docker container (see [this answer](https://github.com/DevExpress/testcafe/issues/1838#issuecomment-333754009) for more information).

**Comment by VasilyStrelyaev** [comment]
Closed in favor of https://github.com/DevExpress/testcafe/issues/5801
