### ISSUE TITLE
Reverse proxy fails to startup intermittently.

### ISSUE THREAD

**Issue by jm-ra** [DevExpress/testcafe#5765]
We run TestCafe in our CI system to test an Electron application written in Typescript.

Each test in our test suite executes on one VM, and then the VM is restarted and may be used for other tests later.

Intermittently, we notice that the TestCafe proxy does not work, and we see:

**ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.**

There is no pattern to the VM this happens on, or to the test that is running.

I'd like to know:
1) Is there a workaround to this problem?
2) Or, is there an easy way to write a script to detect that the proxy is not starting correctly and re-start testcafe?

### What is your Test Scenario?
We do not have a duplication scenario because this problem is intermittent.
 
### What is the Current behavior?
We see the error below, and it seems the reverse proxy is not working because the logs don't show

**ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.**
 
### What is the Expected behavior?
Don't expect any errors and expect reverse proxy to work.
 
### What is your web application and your TestCafe test code?

Not publicly available yet.
### Steps to Reproduce:

Don't know.
 
### Your Environment details:

**I am getting this information and will update soon.** 
 
* testcafe version:      1.8.1
* node.js version:      12              
* command-line arguments:  npx testcafe electron components/**/*.ts tests/common/**/*.ts tests/pit/**/*.ts tests/performance/**/*.ts  --test-meta TC-1177=true

* browser name and version: Electron 8.3.3
* platform and version:      Windows10

**Comment by Farfurix** [comment]
@jm-ra 

Hello,

It looks like your CI lacks resources. I suggest you add some resources to your CI machine and update your TestCafe version to the latest version (v1.9.4) to make your test results more stable.

We plan to improve the "Unable to establish one or more of the specified browser connections" error message. You can track our progress here: https://github.com/DevExpress/testcafe/issues/5307.

**Comment by jm-ra** [comment]
What are "resources"? How would I know which ones to add?

**Comment by Farfurix** [comment]
@jm-ra 

Hello,

I mean the number of processors and the amount of RAM. It's hard to name the exact cause of the "Unable to establish.." error. I suggest you experiment with your CI config settings.

**Comment by jm-ra** [comment]
Thanks. We have hundreds of VM's that run these tests. All the VM's are the same. Intermittenty, on random VM's the reverse proxy does not start. The test can later run ok on same VM.

My question was: How to detect this condition programatically, so we can restart the test.

**Comment by Farfurix** [comment]
@jm-ra 

The "Unable to establish one or more of the specified browser connections" error means that the browser/browsers did not have time to initialize during the timeout. Most likely this happened due to a lack of resources. At present you cannot configure this timeout. You can solve this issue by adding resources to your virtual machines. We will think how to make this timeout configurable.
