### ISSUE TITLE
window.addEventListener not running for message event

### ISSUE THREAD

**Issue by kingeric027** [DevExpress/testcafe#5768]
I have an event listener listening to a message event that emits an event in an angular 9 application. This event listener is not being triggered when testing this component with testcafe. As a result I am unable to actually test this functionality. Here is the code where this event listener is implemented: 

`  ngOnInit(): void {

    const component = this
    window.addEventListener(
      'message',
      function (event: any) {
        const response = JSON.parse(event.data)
        component.ccEntered.emit(response)
      },
      false
    )
  }`

### What is your Test Scenario?
I would like to test submitting values in a form
 
### What is the Current behavior?
Unable to click the submit button because it is still disabled in my application due to the fact that this event listener has not been triggered.
 

 
### Your Environment details:
 
* testcafe version:                   1.9.4
* node.js version:                    14.15.1
* command-line arguments:  yarn testcafe -c 1 chrome -t 'Can I request a quote product? | 19979' --selector-timeout 30000 --assertion-timeout 30000 --page-load-timeout 30000 --skip-js-errors --debug-on-fail
* browser name and version: chrome
* platform and version:          windows
* other:

**Comment by AndreyBelym** [comment]
I apologize for the delayed response. I cannot reproduce the issue with my own examples. Could you please provide a sample page and tests that can be used to reproduce the problem?

**Comment by duffmagic** [comment]
@kingeric027 Are you certain the listener is not being hit?

I'm seeing a similar issue, but it's around references to `event.data`. It appears that TC wraps your messages in it's own, so my own data object moves from `event.data` down to `event.data.message`. I would imagine TC wraps and unwraps all messages and this may be a defect in the unwrapping as the data structure should be the same for our code to work.

Were you perhaps getting any error on `JSON.parse(event.data)`.

Aside, I'd love to know where this MessageEvent handling is documented / coded so I could figure out whether it's a defect.

**Comment by viktoria2506** [comment]
Please send us a sample page and tests to reproduce the problem. We'll try to figure out what's going on.

**Comment by duffmagic** [comment]
> Please send us a sample page and tests to reproduce the problem. We'll try to figure out what's going on.

Thanks. I was slow to respond as it took some time and help to produce a sample.  I'll raise a new ticket today and mention you and this ticket in the description.
