### ISSUE TITLE
Typescript v4+ support

### ISSUE THREAD

**Issue by HarshiShah** [DevExpress/testcafe#5772]
### What is your Test Scenario?
I am using Testcafe and MSW in my repo and I need to upgrade to the latest MSW version but [this](https://www.typescriptlang.org/play?ts=3.9.7#code/C4TwDgpgBAggTgS1AeQHYQGKqgXigCgEM4BzALikNRAEpcA+S6gKFEigAUEBjAawBlCAZ2ABJVABUArmAA2EADwSoEAB7AIqACZCmIANoBdRnmVqN23fuZQoAOgdwIIiglQAzCHCgBVADQ2lKSorh5eUPwBhoEA-BGBFOgAbl6s4NAYCHAiWBzEhAC2EBpwEulKKuqaOnpGJpz5RSVCClx8giLi0nKKEvT0+lQg0WzQHcC5jcVeZZAV5tW6Q3W4UABKxVJwkuUS+gAMxszMAPQAVGc2Z1AAwgD2BWB3Qs6UUCQIKdiyCCJQd+4oO4pKhuMAEHdULo3MA7m90AB3IEgsEQ7DAAAWhGAV0qEG4Ug0unccAeUEQJAxwCgsKg8ncwDsVxOzDUTzg1OBoPBkKg3AeTxeCkCZiqllgiBQ6CwRgCtn4EAZG2AWx27AW4sy2QmqDycEK01Ku3ocvWCEpwGVqtm0A1NXGk31TRmxuY9HwgQcdncUIoEmYNAoHtsXuIJCEFAVSs22xtlQsNWS4TiSbgRigFH0UctMbVEGidBwjDW5qpVtj6SgAG9Ak4VdsCKHSEJC4wa7ZbHXVUCoXYnFopNwICWLfh8PSdRQhn5yaWda3q4EO+Tc3TFTqoG4RFQhwDOKSCr8IEvl1A4hwD0e+847rIUuP11gaHZMZp8BSqU+T8uKB+dQ+GS-ZcAF8ZzDIQDkMGhAmA5hYKAA) code in it fails on any typescript version below 4. 
Testcafe currently does not support a TS version above 4 and throws compilation errors for the above code.

### What are you suggesting?
Support for TS v4+ in Testcafe

### What alternatives have you considered?
Writing a script to update/delete the typescript package under Testcafe in my node modules

**Comment by wentwrong** [comment]
The next TestCafe release (v1.10.0) will include a new feature that allows you to specify a custom TypeScript compiler. See more information about this feature in the [Customize Compiler Options](https://devexpress.github.io/testcafe/documentation/guides/concepts/typescript-and-coffeescript.html#customize-compiler-options) guide.

In the meantime, you can try it in the release candidate version:
```
npm i testcafe@1.10.0-rc.6
```
