### ISSUE TITLE
Release 1.9.0 - Disable Multi Window Support

### ISSUE THREAD

**Issue by jbirdmotox** [DevExpress/testcafe#5783]
Hello,
I'm currently running TestCafe version 1.8.1 without issue. I tried upgrading to version 1.9.0 but my current tests fail because of automatic application online help pop-ups. To disable I tried the config setting disableMultipleWindows=true but that didn't stop the pop-ups.
Is there another way to disable this new feature so I could upgrade?

Thanks,
Jon

**Comment by AlexKamaev** [comment]
Hello.
There are three ways to disable multiple windows - see the following article: [https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/multiple-browser-windows.html](https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/multiple-browser-windows.html).

> You can disable support for multiple browser windows if you encounter compatibility issues with your tests. Use one of the following settings:

>the --disable-multiple-windows command line flag,
the disableMultipleWindows runner.run option,
the disableMultipleWindows configuration file property.

We didn't get any messages that `disableMultipleWindows` does not work in some cases. I checked it, and it works as expected in my tests. Could you please share your project's URL or create an example to demonstrate the issue to us?

**Comment by jbirdmotox** [comment]
Hi Alex,
I wouldn't be able to provide the URL. It's an internal/company application. I could take some screen shots of the 1.8.1 vs 1.9.0 behavior. Not sure if that would be helpful to you though?

Thanks,
Jon

**Comment by AlexKamaev** [comment]
@jbirdmotox, It would be difficult to determine the cause of the issue without a working application. Could you please somehow emulate the described behavior in a sample project and share it here? If you cannot share your project here, you can send it to support@devexpress.com.

Please note that if your website is behind a proxy and requires authentication, we will not be able to access it. Our policy doesn't allow us to access a customer’s internal resources without prior written approval from the entity that owns the server/web resource. If you want us to research the problem further, we’ll need access to the server/web resource. Please ask the website owner to send us ([support@devexpress.com](mailto:support@devexpress.com)) written confirmation. It must permit DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes.

If this is not suitable for you, please share a video showing how your project behaves with v1.8.1 and v1.9.0. You can use the following tool to make a video: [https://www.techsmith.com/jing-tool.html](https://www.techsmith.com/jing-tool.html).

Please also specify the command that you use to run your TestCafe tests and clarify how you set the `disableMultipleWindow` option (your TestCafe runner file/the `testcaferc.json` configuration file).
