### ISSUE TITLE
Request json file response empty content cause by wrong content-type

### ISSUE THREAD

**Issue by moJiXiang** [DevExpress/testcafe#5785]
### Steps to Reproduce:

Request URL: http://172.17.19.48:53640/A7k3KMrG6/file:///F:/angular/angular-electron/dist/assets/i18n/en.json
Request Method: GET
Status Code: 222 unknown
Remote Address: 172.17.19.48:53640
Referrer Policy: no-referrer-when-downgrade

**Response Headers**
Connection: keep-alive
content-type: text/html
Date: Wed, 09 Dec 2020 05:41:52 GMT
Keep-Alive: timeout=5
Transfer-Encoding: chunked

When I paste the Request URL in chrome browser, response json result correct. I think content-type of this response should be application/json.
 
### Your Environment details:
 
* testcafe version:                   1.9.4
* node.js version:                    14.15.1
* platform and version:          Windows 10
* electron version                   10.1.5
* testcafe-browser-provider-electron  0.0.15

**Comment by Farfurix** [comment]
@moJiXiang 

Hello,

It looks like a CORS failure. Make sure that the route includes CORS headers (for example, "access-control-allow-origin") in its response. If so, and your scenario works successfully without TestCafe, please share a simplified project with us. We will examine it and check for a suitable solution.
