### ISSUE TITLE
Enable Chrome emulation for multiple windows

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#5787]

**Comment by rob4629** [comment]
I might have some time in Jan or Feb to investigate this. The last time I looked in to it, I struggled to set breakpoints in the code, to debug where the issue might be happening. Could you tell me how I can achieve this?

**Comment by miherlosev** [comment]
Hi @rob4629 

> Could you tell me how I can achieve this?

We wrote this enhancement as an idea. At present, we don't have strict instructions on how to implement this feature. 
So, we can share only general instructions:
* check how emulation works for a single window (see [here](https://github.com/DevExpress/testcafe/blob/ac88e67a155168024315ad7894401014b0bb7d92/src/browser/provider/built-in/dedicated/chrome/cdp-client/index.ts#L156))
* check how the window switching mechanism works (see [here](https://github.com/DevExpress/testcafe/blob/6de1ed7b91acd64df6dfc0df900233135253421b/src/client/driver/driver.js#L1013)).
