### ISSUE TITLE
Uncaught (in promise) Error: GraphQL error: Not authorized issue while running testcafe

### ISSUE THREAD

**Issue by rehanmomin** [DevExpress/testcafe#5791]
I can not provide the url and steps as it is confidential.
But the issue is I am able to login manually to a url but when trying to login using Testcafe it gives me the above error in console and does not login.

I am using the latest version of node and testcafe.

This is the error while running from testCafe
![image](https://user-images.githubusercontent.com/42905671/101781287-9ed85480-3b1d-11eb-97f1-f254dfc6e0a9.png)

**Comment by Farfurix** [comment]
@rehanmomin 

Hello,

> I can not provide the url and steps as it is confidential.

In this case, could you create a simplified project that partially uses your original application logic and illustrates the problematic scenario? We need to reproduce the issue on our side to find its cause.

If you faced the "GraphQL error: Not authorized" error without using TestCafe, you can refer to [this answer](https://stackoverflow.com/a/55286778/10448174).

**Comment by satyadipon** [comment]
@Farfurix 
PFB the error details

` My first test
   1) A JavaScript error occurred on "https://d1yw1bkcv3jx9x.cloudfront.net/login".
      Repeat test actions in the browser and check the console for errors.
      If you see this error, it means that the tested website caused it. You can fix it or disable tracking JavaScript errors in TestCafe. To do the latter, enable the "--skip-js-errors"
      option.
      If this error does not occur, please write a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".
      JavaScript error details:
      Error: GraphQL error: Not authorized
          at new t (https://d1yw1bkcv3jx9x.cloudfront.net/static/js/2.7132cbb7.chunk.js:3:402048)
          at https://d1yw1bkcv3jx9x.cloudfront.net/static/js/2.7132cbb7.chunk.js:3:430980
          at Object.next (https://d1yw1bkcv3jx9x.cloudfront.net/static/js/2.7132cbb7.chunk.js:3:889022)
          at g (https://d1yw1bkcv3jx9x.cloudfront.net/static/js/2.7132cbb7.chunk.js:3:886826)
          at w (https://d1yw1bkcv3jx9x.cloudfront.net/static/js/2.7132cbb7.chunk.js:3:887348)
          at e.value (https://d1yw1bkcv3jx9x.cloudfront.net/static/js/2.7132cbb7.chunk.js:3:887901)
          at https://d1yw1bkcv3jx9x.cloudfront.net/static/js/2.7132cbb7.chunk.js:3:416767
          at Set.forEach (<anonymous>)
          at Object.next (https://d1yw1bkcv3jx9x.cloudfront.net/static/js/2.7132cbb7.chunk.js:3:416729)
          at g (https://d1yw1bkcv3jx9x.cloudfront.net/static/js/2.7132cbb7.chunk.js:3:886826)
      Browser: Chrome 87.0.4280.88 / macOS 10.15.7`

**Comment by satyadipon** [comment]
the issue seems to be with testcafe version.
upgrading testcafe version to "1.9.4" resolved the problem

**Comment by rehanmomin** [comment]
Thanks @satyadipon it is resolved now.
