### ISSUE TITLE
expect() - options to : 1) limit amount of feedback 2) send output to file

### ISSUE THREAD

**Issue by fmancardi** [DevExpress/testcafe#5795]
### What is your Test Scenario?
It's not the only scenario to what this request apply, but it more evident when you 
develop a Data Driven Test, where you are going to loop over the test.

### What are you suggesting?
the expect() method when it fails, generates information that is useful from the script developer point of view,
but a **little overwhelming** if you want to provide feedback to the user/tester that had launched the test.
Here an example:
```
   1) AssertionError: Use case: inserire uno user con utenza scaduta:
      expected false to be truthy

      + expected - actual

      -false
      +true

      Browser: Chrome 87.0.4280.88 / Windows 10
  
         267 |
         268 |  var opOK = false;
         269 |  var msg = ctx.useCase;
         270 |  switch (ctx.validateOpt.onFailure) {
         271 |    case 'throw':
       > 272 |      await t.expect(loginPage.loginButton.exists).ok(msg.bgRed);
         273 |      await t.expect(loginPage.loginButton.visible).ok(msg.bgRed);
         274 |      opOK = true;
         275 |    break;
         276 |
         277 |    default:

         at Object.<anonymous>
      (C:\development\xxx\testautomation\lib\helpers\login.js:272:52) at Object.validateLoginFailure
      (C:\development\xxx\testautomation\lib\helpers\login.js:283:62) at <anonymous>
      (C:\development\xxx\testautomation\test\AccessoAlSistema\EBS-20-Accesso-Al-Sistema.js:43:40)
```
If we consider the previous text as the standard log/feedback then the following options will be IMHO useful
- send full feedback to screen -> everything works as today
- send full feedback to file/stream
- send full feedback to null -> full feedback OFF
- send minimal feedback to screen
  Only the text:
```
AssertionError: Use case: inserire uno user con utenza scaduta:
```
will be sent to the screen.

## examples
send full feedback to **file** + send minimal feedback to screen 
send full feedback to **null** + send minimal feedback to screen 
   
## OFF TOPIC
```
+ expected - actual
      -false
      +true
```
May be it will be better to organize the message in this way
```
+ expected - actual
      +true
      -false
```
Or 
```
expected -> true
actual -> false
```

**Comment by arubtsov** [comment]
Hello @fmancardi,

Thank you for your input. 
TestCafe offers a solution for both of your requests.
You can shape TestCafe output by implementing and using [custom reporters](https://devexpress.github.io/testcafe/documentation/guides/extend-testcafe/reporter-plugin.html). You can also specify a file path in the reporter option ([command line interface](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#-r-nameoutput---reporter-nameoutput), [programming interface](https://devexpress.github.io/testcafe/documentation/reference/testcafe-api/runner/reporter.html#save-the-report-to-a-file), [configuration file](https://devexpress.github.io/testcafe/documentation/reference/configuration-file.html#reporter)) and TestCafe will save a report into a file.
Feel free to contact us if these solutions do not meet your needs.

**Comment by fmancardi** [comment]
OK, I'm going to try.
IMHO anyway it will be better if you can provide a new standard reporter with this behivour

regards

**Comment by fmancardi** [comment]
Hi, here one useful reporter -> https://www.npmjs.com/package/testcafe-reporter-mini
IMHO it will be great if you add it to the standard distribution

**Comment by arubtsov** [comment]
@fmancardi, we add only those reporters that were developed by the team. Information about a callsite is essential when one needs to find a failed assertion in test code - it is not a common use case for most testcafe users. Could you please describe your scenario in greater detail? If it is related to TestCafe Studio, [Support Center](http://www.devexpress.com/ask) might be a better place to discuss this issue.
