### ISSUE TITLE
The 'all' browser alias should run the browsers through the browser-specific providers

### ISSUE THREAD

**Issue by VasilyStrelyaev** [DevExpress/testcafe#5801]
The `all` alias now uses a separate built-in browser provider that runs the browsers it detects in a different way than `chrome`, `firefox`, and other built-in providers.

For instance, chromium providers set the `--no-sandbox` flag if they run in Docker; the `all` provider doesn't do this so `all` doesn't work in Docker at all if you have Chromium on the image. There's no way to set the browser flags manually when you use `all` either.

**Comment by AndreyBelym** [comment]
Yet another issue connected to this one: https://github.com/DevExpress/testcafe/issues/3899. `all` should start browsers using profiles by default (for supported browsers).
