### ISSUE TITLE
Typescript : Selector.addCustomMethods could be typed with added methods

### ISSUE THREAD

**Issue by Pantalaimon** [DevExpress/testcafe#5806]
### What is your Test Scenario?

When using addCustomMethods in typescript, the resulting Selector is properly typed with added methods, without manually declaring the interface.

```typescript
const test = Selector.('div').addCustomMethods({
  sayHello : (el, name) => console.log(`Hello to ${name} from ${el}`)
})

test.sayHello('John') // no typescript compilation error
```

### What are you suggesting?

Typescript is powerful enough to deduce the new interface of the Selector if addCustomMethods type is explicit enough.
Here is my workaround code:

```typescript
type WithoutFirstArg<F extends Function> = F extends (a: any, ...x: infer ARGS) => infer R
  ? (x: ARGS) => R
  : never

type AsCustomMethods<METHODS extends Record<string, Function>> = {
  [k in keyof METHODS]: WithoutFirstArg<METHODS[k]>
}

/**
 * Selector.addCustomMethods with typescript typings!
 */
function addTypedCustomMethods<
  METHODS extends { [method: string]: (node: Element, ...methodParams: any[]) => any }
>(selector: Selector, methods: METHODS, opts?: { returnDOMNodes?: boolean }) {
  return selector.addCustomMethods(methods, opts) as Selector & AsCustomMethods<METHODS>
}
```

### What alternatives have you considered?

The current documented solution of specifying the interface every time works, but it can generate lots of boilerplate.

**Comment by miherlosev** [comment]
Hi @Pantalaimon 

Thank you for sharing this idea with us.
