### ISSUE TITLE
PressKey, meta and contenteditable

### ISSUE THREAD

**Issue by baptistemanson** [DevExpress/testcafe#5810]
### What is your Test Scenario?
We have the keyboard shortcut meta+i to italicize some text. We want to check that the text is well italicized.
 
### What is the Current behavior?
A "i" is added after the meta+i is pressed.
 
### What is the Expected behavior?
Meta+i should not add an i in the contenteditable event target.
 
### What is your web application and your TestCafe test code?
Upcoming.
 
```js
   await t.pressKey("meta+i");
```
Please note we have no bug with ctrl or shift, it is specific to meta.

### Your Environment details:
 
* testcafe version:                   1.10
* node.js version:                  v14.0.0
* command-line arguments:  none
* browser name and version: chrome 87
* platform and version:          MacOS 10.14

**Comment by Dmitry-Ostashev** [comment]
It's difficult to find the cause of the problem without an example of a web page. Could you please give us a website url so that we can reproduce and research the issue on our side?

**Comment by biw** [comment]
@Dmitry-Ostashev, I'm also hitting this issue and have created a minimal repo to display my issue: https://github.com/biw/testcafe-5810-example

To summarize the behavior I see vs. the behavior I'd expect:

**Result** (with extra 'i' from `.pressKey("meta+i")`:
```
0: hi therei
1: 
```
**Expected**:
```
0: hi there
1: 
```

**Comment by Dmitry-Ostashev** [comment]
@biw Thank you for your example. I've reproduced the issue. We'll research it and we'll update this thread as soon as we have any news.

**Comment by biw** [comment]
Awesome, thank you @Dmitry-Ostashev!
