### ISSUE TITLE
Error: Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.

### ISSUE THREAD

**Issue by willyestrada81** [DevExpress/testcafe#5814]
Since we upgraded TestCafe to latest version 1.10.0, we are having the error "Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure. 
It happens locally to all of our team members as well as in our CI/CD pipelines.

It's happening in Chrome, Firefox

Once we downgrade to version 1.9.4 which was the one we were using before, it works fine.

For the pipelines we use:
`npx testcafe 'chrome:headless --no-sandbox' src/tests/smoke/ --disable-multiple-windows -e`

Which is the one we were using forever.

Locally we use:
testcafe chrome src/tests/smoke  --disable-multiple-windows -e

<img width="992" alt="Screen Shot 2020-12-18 at 3 19 57 PM" src="https://user-images.githubusercontent.com/34007144/102658286-47ea0500-4145-11eb-817b-db66a76ecf55.png">
 
### Environment details:
 
* testcafe version:                            1.10.0
* node.js version:                             v14.4.0
* command-line arguments:          `testcafe chrome src/tests/smoke  --disable-multiple-windows -e`
* browser name and version:          Chrome 87.0.4280.88
* browser name and version in CI:  Chrome 72.0.3626.121
* platform and version:                   macOS 11.1.0
* platform and version in CI:           Linux 0.0

**Comment by nullpr** [comment]
Have the same issue, after some investigation, it seems that problem appear after new compiler (https://github.com/DevExpress/testcafe/pull/5607/files)
Now it takes much longer time to compile files (more than 2 minutes *default timeout for setting up connection")

**Comment by aleks-pro** [comment]
Hello @russelldavis,

Please try to run tests without the [`--dev`](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#--dev) flag: `testcafe chrome tests/repro.js`. Unminimized TestCafe scripts may significantly slow tests' execution.

**Comment by willyestrada81** [comment]
Hi @aleks-pro, I'm not using the `--dev` flag in any of the commands

**Comment by aleks-pro** [comment]
Hi @willyestrada81 , 
    
Please accept my apologies. The previous comment was meant for another issue.

I have not managed to reproduce the issue. Can you please provide a sample project where we can reproduce it?
