### ISSUE TITLE
pass location of .testcaferc.json as a CLI param

### ISSUE THREAD

**Issue by oreporan** [DevExpress/testcafe#5815]
### What is your Test Scenario?
I have a mono repo frontend architecture, with testcafe files in each one.
Currently writing a shared `.testcaferc.json` doesn't work, and I have to manually write this file in each folder of the project.

### What are you suggesting?
`testcafe -configPath='../../root/.testcaferc.json'`

### What alternatives have you considered?
Writing it in each folder

**Comment by Farfurix** [comment]
@oreporan 

Hello,

It's a duplicate of https://github.com/DevExpress/testcafe/issues/3428. I'll close this issue.
