### ISSUE TITLE
The-iframe-in-which-the-test-is-currently-operating-does-not-exist-anymore.

### ISSUE THREAD

**Issue by imsureshkrishna03** [DevExpress/testcafe#5816]
Getting this error after switched to iframe and refer my code samples below,

```
  const iframe = xpathSelector('//iframe[@title="accessibility title"]')
  await t.switchToIframe(iframe)
  await t.click(xpathSelector('//button[text()="Save"]'))      //Getting the error in this point
```

Note: Using latest recommended testcafe

I think the code which i am using is pretty correct but i do know why getting this error, can anybody who bypassed this error please let me know.

**Comment by aleks-pro** [comment]
Hello @imsureshkrishna03,

Could you please share a public link to your Web application or a sample project where we can reproduce the issue?

NOTE: We can't access a customer’s internal resources without a prior written approval from the entity that owns the server/web resource. If you want us to research the problem further on your server/web resource, we’ll need a written approval to access it. Please ask the website owner to send us (mailto:support@devexpress.com) confirmation. It must permit DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes.
