### ISSUE TITLE
Feature: Code-Defined Timeouts

### ISSUE THREAD

**Issue by timostark** [DevExpress/testcafe#5833]
Hi There,

I am writing framework specific selectors for [SAPUI5 ](https://blogs.sap.com/2020/12/27/automated-testing-with-ui5/?update=updated). During implementation I found one feature request: "Smarter-Wait-Times".
With direct access to the UI framework custom selector code has more "in-depth" knowledge about currently active and long running tasks on the webpage.

### What is your Test Scenario?
Test a page, where the framework itself is doing some extensive initialization, actions [...].
Currently: I am setting selector timeout on a pretty high value (30 seconds), so that testcafe is waiting for the framework activities. In case of an failures, this leads to long running tests.
Goal: Wait "until" the framework SAPUI5 is not doing anything anymore - afterwards only have a very short timeout (e.g. 5 seconds) --> Much faster tests in case of failures.

### What are you suggesting?
Alternative a) Add an asynchronous Test-Initialization method "wait" (like before, after, meta, ..) which is executed before every test-controller action, and allows the custom execution of e.g. client functions. Only after the client function is done, the test continues with the selector/assertion.
Alternative b) Allow custom selectors to return a flag "continue waiting". The Flag can be set, in case the custom selector is detecting the UI5 framework

PS: I am aware of beforeEach to perform a waiting time before every test (see [angular selectors](https://github.com/DevExpress/testcafe-angular-selectors)) - That is not really sufficient though in multiple use-cases (example a: starting on non-sapui5 page, and navigating to a sapui5 page, or b) extensive actions within the test).

**Comment by AlexKamaev** [comment]
Hello,
It is clear what issue you faced. However, currently, we are not ready to consider your suggestions for planning. You may want to try the workaround from the following article: [Create Helpers](https://devexpress.github.io/testcafe/documentation/recipes/best-practices/create-helpers.html). You can write your own methods and add all the required logic to them.

Another possible solution is adding custom methods to the test controller as described in the following suggestion: [https://github.com/DevExpress/testcafe/issues/1535](https://github.com/DevExpress/testcafe/issues/1535). So, please track that issue.
