### ISSUE TITLE
RequestMock - Post Request's Body is Buffer not JSON

### ISSUE THREAD

**Issue by BrkCoder** [DevExpress/testcafe#5835]
I have looked in stackoverflow for hours, and none of the existing answers solved my issue.

My issue is that the request body returns as buffer and not as JSON. I want to compare JSON and buffer contents(not reference) in 

order to return the suitable response for current body.

Also I think that creating a docs example for Post Request with different answers based on body contents is required for the official docs of testCafe.

#### Any help is welcome!

**Comment by wentwrong** [comment]
You can convert NodeJS Buffer into JSON [in the respond](https://devexpress.github.io/testcafe/documentation/reference/test-api/requestmock/respond.html) method of the RequestMock class. After that, apply additional checks and set a suitable body:

```js
const mock = RequestMock()
    .onRequestTo(/post-request/)
    .respond((req, res) => {
        const parsedRequestBody = JSON.parse(req.body.toString());

        if (parsedRequestBody.user.name === 'something')
            res.setBody('mock body');
        else
            res.setBody('another mock body');
    });
```

As handling a POST request is no different from handling other types of requests, I don't think that we need an additional example in the documentation.
