### ISSUE TITLE
Is there a way to tell 'typeText' to NOT use CAPS LOCK for UpperCase characters?

### ISSUE THREAD

**Issue by iamle0pard** [DevExpress/testcafe#5836]
We have a test that types text into a password field and on our website we indicate a warning to the end user when their CAPS LOCK key is on.  We've noticed that passwords which end in an uppercase letter are causing our tests to fail because we don't expect the CAPS LOCK error to be displayed at this time.

Does anyone know if there is a way to tell ".typeText" to use the SHIFT key instead of CAPS lock?  Or are there alternative ways to enter this text such that the caps lock key won't be used?

**Comment by AlexSkorkin** [comment]
Thank you for your inquiry. We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe/#contributing)). 
This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.
