### ISSUE TITLE
[docs] Add a note about advanced features in browsers launched with the `all` browser alias or with with a path

### ISSUE THREAD

**Issue by DIRECTcut** [DevExpress/testcafe#5838]
Browsers that are launched:
 * with the `all` browser alias 
 * with a path
 
 ```sh
 testcafe "path:`C:/Program Files (x86)/Google/Chrome/Application/chrome.exe` --lang=fr","path:`C:/Program Files (x86)/Google/Chrome/Application/chrome.exe` --lang=es" test.js
 ```
  don't [use browser-specific providers](https://github.com/DevExpress/testcafe/issues/5801). Therefore, advanced features (like temporary clean profile) don't work in browsers launched this way. 

We need to be more explicit about this (perhaps a note) [in the docs](https://devexpress.github.io/testcafe/documentation/guides/basic-guides/run-tests.html#run-tests-in-all-installed-browsers).

**Comment by titerman** [comment]
We don't plan to address this issue in the near future. Feel free to reopen the ticket if the issue is important for you.
