### ISSUE TITLE
Allow multiple before/beforeEach/after/afterEach hooks at the same time

### ISSUE THREAD

**Issue by barrerajl** [DevExpress/testcafe#5839]
### What is your Test Scenario?
I want to have the same settings for a lot of different tests. Extending somehow the default beforeEach behavior so they are easily to put in groups.

### What are you suggesting?
Being able to define more than one beforeEach like we have more than one meta for each fixture so we can extend and group fixtures that need a common setup.

### Additional context
for example
```
export function desktop_fixture(fixture_name) {
  return fixture(fixture_name)
    .meta('fixture_size', 'desktop')
    .beforeEach(async t => {
      await t.maximizeWindow();
    });
}
```
and then have desktop_fixture for some of my tests and others are mobile_fixtures and they have the beforeEach also for them in the fixture definition...

**Comment by wentwrong** [comment]
Thank you for your suggestion. The idea to specify multiple fixture/test hooks without them being overridden looks interesting. We will consider supporting this scenario.

Also, I think you can achieve the desired functionality once it is possible to specify fixture and test hooks at the test run level (#4323). After that, you can [run tests whose metadata contains specific values](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#--fixture-meta-keyvaluekey2value2) with a separate setup logic:
```
testcafe chrome --fixture-meta fixture_size=desktop e2e/**/* --global-setup desktop-setup.js
testcafe "chrome:emulation:device=iphone X" --fixture-meta fixture_size=mobile e2e/**/* --global-setup mobile-setup.js
```
Then, these runs can be divided among multiple CI jobs. Please note that we haven't finalized the feature design of global hooks yet, so it'll probably be changed in the future.
