### ISSUE TITLE
TestCafe doesn't close Chrome instances

### ISSUE THREAD

**Issue by Farfurix** [DevExpress/testcafe#5842]
Found in https://github.com/DevExpress/testcafe/issues/5832.

### What is your Test Scenario?
Using custom chrome profiles
 
### What is the Current behavior?
TestCafe doesn't close Chrome instances
 
### What is the Expected behavior?
TestCafe closes Chrome instances
 
### What is your web application and your TestCafe test code?
 
<details>
<summary>Your complete test code (or attach your test files):</summary>

```js
 import { ClientFunction } from 'testcafe';

fixture `Fixture`
    .page('https://google.com');

test('log window.navigator.language', async t => {
    const getLanguage = ClientFunction(() => window.navigator.language);

    console.log(await getLanguage());

    await t.expect(true).ok();
});
```
</details>

<details>
<summary>Your complete test report:</summary>

```
d:\work\issues\i5832-tc>testcafe "chrome --user-data-dir=D:\work\ChromeProfiles\FR" test.js
 Running tests in:
 - Chrome 87.0.4280.88 / Windows 10

 Fixture
fr-FR
 √ log window.navigator.language


 1 passed (2s)

d:\work\issues\i5832-tc>testcafe "chrome --user-data-dir=D:\work\ChromeProfiles\FR","chrome --user-data-dir=D:\work\ChromeProfiles\ES" test.js
 Running tests in:
 - Chrome 87.0.4280.88 / Windows 10
 - Chrome 87.0.4280.88 / Windows 10

 Fixture
fr-FR
es
 √ log window.navigator.language


 1 passed (2s)
```
</details>

### Steps to Reproduce:

1. Copy the "User Data" directory contents to another place (for example, D:\work\ChromeProfiles\FR).
2. Run Chrome with this profile ("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --user-data-dir="D:\work\ChromeProfiles\FR").
3. Change FR profile language to French, click the "Display Google Chrome in this language".
4. Run `testcafe "chrome --user-data-dir=D:\work\ChromeProfiles\FR" test.js`.
5. TestCafe doesn't close the browser instance after test is done.

https://user-images.githubusercontent.com/30019338/103342236-10ab1a80-4a9a-11eb-8e40-7de577c1096d.mp4

### Your Environment details:
 
* testcafe version:                   1.10.1
* node.js version:                    12.19.0
* command-line arguments:  `testcafe "chrome --user-data-dir=D:\work\ChromeProfiles\FR" test.js`, `testcafe "chrome --user-data-dir=D:\work\ChromeProfiles\FR","chrome --user-data-dir=D:\work\ChromeProfiles\ES" test.js`
* browser name and version: Chrome 87
* platform and version:          Windows 10

**Comment by Aleksey28** [comment]
Fixed in the `testcafe@1.11.0`
