### ISSUE TITLE
[RequestMock] Requests to different URLs are not mocked

### ISSUE THREAD

**Issue by yourpchelp** [DevExpress/testcafe#5847]
### What is your Test Scenario?
When you open a website, this site can generate requests (POST, GET).
The goal is to mock some of these requests.
 
### What is the Current behavior?
When the site generates the request with another URL, this request cannot be captured and mocked.
 
### What is the Expected behavior?
Every generated request can be captured and mocked.
 
### What is your web application and your TestCafe test code?
```
import { Selector, RequestMock, t } from 'testcafe';

// Requests to be mocked:
// https://id.rambler.ru/api/v3/session/getRsidx
// https://ssp.rambler.ru/blockstat_post
// https://id.rambler.ru/jsonrpc
// https://www.rambler.ru/metrics/

// const urlRegExp = new RegExp('/getRsidx'); // failed
// const urlRegExp = new RegExp('/blockstat_post'); // failed
// const urlRegExp = new RegExp('/jsonrpc'); // failed
const urlRegExp = new RegExp('/metrics'); // passed
const mock = RequestMock()
    .onRequestTo(urlRegExp)
    .respond({error: 'this request has been mocked'}, 500);

fixture (`RequestMock test`)
    .requestHooks(mock)

test('open Rambler', async t => {
    await t.debug();
    await t.navigateTo('https://www.rambler.ru');
    await t.debug();
});
```

### Steps to Reproduce:
see the above code
 
### Your Environment details:
* testcafe version:                   1.8.2
* node.js version:                   v12.18.2
* command-line arguments:  testcafe chrome ./test_example.js --skip-js-errors
* browser name and version: Chrome Version 87.0.4280.88 (Official Build) (x86_64), Firefox 83.0 (64-bit)
* platform and version:          macOS Big Sur, Version 11.1

**Comment by miherlosev** [comment]
https://github.com/DevExpress/testcafe/issues/5847

Hi @yourpchelp 

To mock cross-domain requests (https://id.rambler.ru/api/v3/session/getRsidx, https://ssp.rambler.ru/blockstat_post, https://id.rambler.ru/jsonrpc), you need to specify CORS related headers for the [respond](https://devexpress.github.io/testcafe/documentation/reference/test-api/requestmock/respond.html) method.

I updated the example you shared.

```js
import { Selector, RequestMock, t } from 'testcafe';

// Requests to be mocked:
// https://id.rambler.ru/api/v3/session/getRsidx
// https://ssp.rambler.ru/blockstat_post
// https://id.rambler.ru/jsonrpc
// https://www.rambler.ru/metrics/

// Сначало должно пройти cors проверку.
const urlRegExp = new RegExp('/getRsidx'); // failed
// const urlRegExp = new RegExp('/blockstat_post'); // failed
// const urlRegExp = new RegExp('/jsonrpc'); // failed
//const urlRegExp = new RegExp('/metrics'); // passed
const mock = RequestMock()
    .onRequestTo(urlRegExp)
    .respond({error: 'this request has been mocked'}, 500, {
        'access-control-allow-origin':      'https://www.rambler.ru',
        'access-control-allow-credentials': true
    });

fixture (`RequestMock test`)
    .requestHooks(mock)

test('open Rambler', async t => {
    await t.debug();
    await t.navigateTo('https://www.rambler.ru');
    await t.debug();
});

```
