### ISSUE TITLE
Support switching to Iframes that are places in a Shadow Root.

### ISSUE THREAD

**Issue by thakurrugved** [DevExpress/testcafe#5848]
### What is your Test Scenario?
Use t.switchToIframe with an iframe element that is located inside a shadow root. There was an issue opened for this but got closed over the time. https://github.com/DevExpress/testcafe/issues/3673

 
### What is the Current behavior?
Currently, if you try to perform this, you will get the The iframe in which the test is currently operating does not exist anymore error.

 
### What is the Expected behavior?
Support this case.

 
**Additional context**

**test.html**

```
<!DOCTYPE html>
<html>
    <head>
        <title>Test Shadow IFrame</title>
    </head>
    <body>
        <div id="shadowRootElement"></div>
        <script>
            shadowRootElement.attachShadow({mode: 'open'});

            const shadowRoot = shadowRootElement.shadowRoot;
            const iframe     = document.createElement('iframe');

            iframe.src = 'iframe.html';
            
            shadowRoot.appendChild(iframe);
        </script>
    </body>
</html>
```
**iframe.html**

```
<!DOCTYPE html>
<html>
    <head>
        <title>Shadow Iframe</title>
    </head>
    <body>
        <div id="logElement"></div>
        <button onclick="logElement.textContent = 'It works'">Click me</button>
    </body>
</html>
```

**test.js**
```
fixture `Test Shadow`
    .page`./test.html`;

test(`iframe`, async t => {
    await t
        .switchToIframe(() => shadowRootElement.shadowRoot.querySelector('iframe'))
        .click('button')
        .wait(3000);
})
```

**Comment by miherlosev** [comment]
Hi @thakurrugved,

Thank your for the example. I reopened the original #3673 issue. Please track it to be informed about its progress.
