### ISSUE TITLE
testcafe does not work in a jenkins slave running at k8s

### ISSUE THREAD

**Issue by runningman84** [DevExpress/testcafe#5852]
### What is your Test Scenario?

I would like to run some tests.
 
### What is the Current behavior?

I can run the tests locally and using docker with this command
testcafe chromium:headless /tests/e2e-tests/ --fixture-meta 'xyz=one' -r spec,json:reports/report1.json
But in a jenkins slave I get an error like this:
```
The specified selector does not match any element in the DOM tree.
``` 
The screenshoot function generates an empty/white page.
The funny thing is It work fine in case I just start some random pod and execute the tests there... 

### What is the Expected behavior?

testcafe should produce the same results locally, in docker, in k8s, in a jenkins slave in k8s
 
### What is your web application and your TestCafe test code?

```
       > | Selector('.l-header__searchWrap')

      Browser: Chrome 86.0.4240.111 / Linux 0.0

         13 |    }
         14 |  }
         15 |
         16 |  search = async (t: TestController, partName: string) => {
         17 |    const getURLTxt = await getURL()
       > 18 |    await t.hover(Selector('.l-header__searchWrap'), {
      offsetX: 1, offsetY: 50 }); //Move mouse vertical below navigation
      menu to avoid dropdown effect on hover
         19 |    await t.typeText(this.searchBar, partName, { replace:
      true });
         20 |    await this.firstElement(t, partName);
         21 |    if (await this.modalInput.exists) {
         22 |      await t.typeText(this.modalInput, "1", { replace: true
      });
         23 |      await t.click(this.modalAddToCart);

         at HomePage.<anonymous>
      (/tests/e2e-tests/pages/home_page.ts:18:13)
         at fulfilled (/tests/e2e-tests/pages/home_page.ts:5:58)
``` 

<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

I haven't been able to reproduce this error outside of a jenkins slave running in k8s. Even running the command inside container works (using kubectl exec ...).
 
### Your Environment details:
 
* testcafe version:    1.8.2        
* node.js version:    v14.15.3  
* command-line arguments:  
* browser name and version: 86.0.4240.111  
* platform and version:          
* other:

**Comment by miherlosev** [comment]
Hi @runningman84,

Try to run your tests with the latest testcafe version (`1.10.1`) and let us know about your results.

**Comment by tuxBurner** [comment]
Perhaps this helps: https://github.com/DevExpress/testcafe/issues/7671#issuecomment-1716154759
