### ISSUE TITLE
Hammerhead causing Javascript error on login page

### ISSUE THREAD

**Issue by smparelhoff** [DevExpress/testcafe#5853]
### What is your Test Scenario?
Smoketests: use User Roles to attempt login and then confirm the page loads
Scenario tests for component on main page: user User Roles to attempt login and interact with page components

 
### What is the Current behavior?

Recently tests started failing in dev, but still pass in higher environments. The error output being logged by Testcafe indicates that it is a Javascript error occurring on the login page. 

I should say here that we use a SSO process that is managed by another department, so the login page itself is not owned by my team. Users navigate to our URL, click the "Login" button, and are redirected to the SSO login page. Recently, there were some updates made to the beta version page, which is what is used by our dev site and probably exactly when the tests started failing there. Javascript error is below--note that I only see this error in the console when I run our Testcafe tests in debug mode. If I navigate to this page in my browser there are no errors in the console. I've also confirmed that the tests all pass if I run with the --skip-jsErrors option. See below for the error
 
JavaScript error details:
Error: Failed to execute 'querySelectorAll' on 'Element': 'input:-webkit-autofill:not([type="submit"]):not([type="hidden"],input:-webkit-autofill:not([type="su
bmit"]):not([type="hidden"]' is not a valid selector.
    at HTMLFormElement.querySelectorAll (http://127.0.0.1:63711/hammerhead.js:18688:72)

### What is the Expected behavior?
These tests continue to pass in dev, as they are currently passing in higher environments. I fear it is just a matter of time before the changes made to the SSO login page in beta roll up to prod, and then these tests will start failing there as well. 
 
### What is your web application and your TestCafe test code?

 Very sorry, but I am unable to share a link to our application or code. However, the error seems to have to do with this bit of the javascript from the login page, which checks to see if required fields are populated: 
 ```
 setTimeout(() => {
                let autoFilled = this.parentElm.querySelectorAll('input:-webkit-autofill:not([type="submit"]):not([type="hidden"]'),
                    requiredInputs = this.parentElm.querySelectorAll('input[required]:not([type="submit"]):not([type="hidden"]');

                //simple check if required fields are populated
                if(autoFilled.length > 0 && autoFilled.length === requiredInputs.length) {
                    this.formIsValid();
                }
            }, 50);
```

 
### Your Environment details:
 
* testcafe version:                  1.10.1
* node.js version:                    v12.13.0
* browser name and version: Chrome 87.0.4280.88
* platform and version:           macOS 10.15.7
* other:

**Comment by miherlosev** [comment]
Hi @smparelhoff 

I am afraid this information is not sufficient to find the cause of the issue. Could you please provide a small example so that we can reproduce it on our side?

**Comment by smparelhoff** [comment]
> Hi @smparelhoff
> 
> I am afraid this information is not sufficient to find the cause of the issue. Could you please share a small example so that we can reproduce it on our side?

I understand--I will try and post a simple example as soon as time permits. Thanks for the help!

**Comment by ovidiuc** [comment]
I have a similar issue which might be related.
```
import { Role } from 'testcafe';

const regularAccUser = Role(
    `${process.env.BASE_URL}signin`,
    async t => {
        await t
            .typeText('#email', 'test@example.com')
            .typeText('#password', 'password')
            .click('#submit'); // throws undefined here.
    },
    { preserveUrl: true }
);

export { regularAccUser };
```

The tests using this role does not get executed, as it fails on the `.click('#submit');` line:
```
JavaScript error details:
      undefined
          No stack trace available
```
Both `t` and `click` are not `undefined`, so that leaves the `#click` element. Which leads me to believe it's trying to find the element again, after the navigation off the login page has occurred. To note that the `click` is executed, the login is successful and the page is redirected to the proper URL after login.

If I add `--skip-js-errors` option, it works fine. There are no js errors on the site itself and the DOM elements are present.

**Comment by Farfurix** [comment]
@ovidiuc 

Hello,

Could you please create a [new bug report](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=&template=bug-report.md) with a minimal example that can reproduce the issue on our side? We will examine it and check for a suitable solution.

**Comment by ovidiuc** [comment]
While trying to create an insolated test case for the bug report I found the actual problem, which is in my code. TestCafe was in fact correctly reporting an "undefined" js error, which only showed up on a specific sequence of URLs and with certain data.

So my posts here can be deleted, sorry for not paying attention ☹️

**Comment by Farfurix** [comment]
@ovidiuc 

Hello,

It looks like a TestCafe issue – we should log errors in their original form. If possible, please create a separate issue with a reproducible example.
