### ISSUE TITLE
Script stopped after a long freeze period

### ISSUE THREAD

**Issue by Sabou44** [DevExpress/testcafe#5857]
### What is the Current behavior?
The script runs until `** Start verification` and freezes.

![Capture01](https://user-images.githubusercontent.com/59806062/104290492-b0b16c80-54ba-11eb-8370-bf829f0303a2.PNG)
 

### Steps to Reproduce:

1. Download [basic-page-model.js.txt](https://github.com/DevExpress/testcafe/files/5800864/basic-page-model.js.txt) (remove extension .txt)
2. Download [test-simple-example.js.txt](https://github.com/DevExpress/testcafe/files/5800865/test-simple-example.js.txt) (remove extension .txt)
3. Run `testcafe chrome test-simple-example.js`
 
### Environment details:
 
* testcafe version: 1.10.1
* node.js version: 10.16.3
* browser name and version: Chrome 87.0.4280.88 (Official Build) (64-bit)
* platform and version: Windows 10 Pro

**Comment by AlexKamaev** [comment]
Thank you for sharing the example with us. I was able to reproduce the issue. Please follow this ticket to track our progress.

**Comment by Sabou44** [comment]
Thanks for resolving this issue so quickly !

**Comment by Sabou44** [comment]
Hi,
I still have a problem with this example.
The test runs fine up to `console.log(** End verification);` but the test doesn't stop the execution window remains open and you have to kill it manually.

**Comment by AlexKamaev** [comment]
@Sabou44
Hi, did you try the [1.10.2-alpha.1](https://www.npmjs.com/package/testcafe/v/1.10.2-alpha.1) version?
I checked your scenario and it worked for me.

**Comment by Sabou44** [comment]
Hi,
Thanks @AlexKamaev.

I runned the script with the master but I still have the same problem. The script runs until the last console.log but after the test doesn't end.

![Capture](https://user-images.githubusercontent.com/59806062/105164384-5bf29f00-5b15-11eb-85d4-58d76e0e50da.PNG)

I never see the test result at the end.
![Capture3](https://user-images.githubusercontent.com/59806062/105184410-9bc68000-5b2f-11eb-92a6-269de89a5496.PNG)

**Comment by AlexKamaev** [comment]
@Sabou44 I checked your scenario again using the master branch, and it works as expected in my case. I noticed the following message in your console: `Using locally installed version of TestCafe`. This means that for some reason, you have another TestCafe version installed locally. So, probably, for some reason, the `testcafe` folder exists in your `node_modules`. Please try to remove this folder or reinstall TestCafe from the `master` branch into a clear folder.
