### ISSUE TITLE
`resizeWindow` functional tests fails locally if browser initially not maximized

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#586]

**Comment by AndreyBelym** [comment]
Did #589 fixed that? I cann't reproduce it now.

**Comment by helen-dikareva** [comment]
I think it fixed, I could not reproduce too after https://github.com/DevExpress/testcafe/pull/589

**Comment by inikulin** [comment]
Unfortunately I can't check at the moment (started big new feature in my master :tired_face: ).

**Comment by inikulin** [comment]
Nope, still reproduces (unstable) on my side. First test in the fixture fails, no matter which fails it is. I assume it need to resize at least once to pass correctly.

**Comment by inikulin** [comment]
What's the status of this one @AndreyBelym ?

**Comment by AndreyBelym** [comment]
See part 1 of https://github.com/DevExpress/testcafe/issues/722#issuecomment-240043450. Need to add some delays between native operations in resize hack.

**Comment by AndreyBelym** [comment]
I'm working on it.
