### ISSUE TITLE
Use of md5 for hashing fails on FIPS enabled Kernels

### ISSUE THREAD

**Issue by beatrichartz** [DevExpress/testcafe#5860]
This is related to https://github.com/DevExpress/testcafe-hammerhead/issues/2516

### What is your Scenario?

Running test on a linux image with FIPS enabled
 
### What is the Current behavior?

Tests error with error `ERROR Error: error:060800C8:digital envelope routines:EVP_DigestInit_ex:disabled for FIPS`
 
### What is the Expected behavior?

Tests should run

### Steps to Reproduce:

1. Run testcafe on a FIPS enabled Kernel (check `cat /proc/sys/crypto/fips_enabled` returns 1)
2. See it fail because of use of `md5` in https://github.com/DevExpress/testcafe/blob/master/src/custom-client-scripts/client-script.ts#L115
 
### Suggestion
Use sha256 for etags

### Your Environment details:

* node.js version:                    14.15.1
* browser name and version: Any (chromium, firefox)
* platform and version:          RHEL 8

**Comment by miherlosev** [comment]
https://github.com/DevExpress/testcafe/issues/5860

Hi @beatrichartz 

Thank you for pointing this us out. I created a separate #5864 issue for this case. Track it to be informed about our progress.
