### ISSUE TITLE
Selector cannot find "div" elements

### ISSUE THREAD

**Issue by CassenH** [DevExpress/testcafe#5869]
This problem suddenly occured and I have no idea why. When I try to find select a "div" element, I get the following error:

> Function that specifies a selector can only return a DOM node, an array of nodes, NodeList, HTMLCollection, null or undefined. Use
> ClientFunction to return other values.

It works for other elements though.

This works fine:
```
await t.click(Selector("span").withAttribute('id', 'foo'));
await t.click(Selector("p").withAttribute('id', 'foo'));
await t.click(Selector("button").withAttribute('id', 'foo'));
await t.click(Selector("input").withAttribute('id', 'foo'));
```

This throws an error:
`await t.click(Selector("div").withAttribute('id', 'foo'));
`

I'm using testcafe 1.10.1

Update: Apparently testcafe still works on other sites. It is just that one website where I cannot access "div" elements. Any ideas why that could be?

**Comment by AlexKamaev** [comment]
This issue can occur if you pass a function with an incorrect return value as a Selector argument:
```JS
test('Return non-DOM node', async () => {
    await Selector(() => 'hey')();
});
```
However, the error should not occur if you use string as a parameter to specify your selector. Please check that you do not pass a function to your Selector object.

If your Selector is defined correctly and the issue still appears, please share the example (html page or public url to your site) and your full test code to demonstrate the issue.

**Comment by CassenH** [comment]
I'm not passing a function, I'm using the basic annotation displayed above. Unluckily the page is still confidential so I cannot show it to you. Do you have any other guesses what the issue could be? It must have something to do with the code that is used on that specific project.

**Comment by AlexKamaev** [comment]
@CassenH
I need to review a reproducible example to determine the cause of the issue. If you cannot share your example/project here, you can send it at support@devexpress.com. It will help us research the issue quickly.

The basic usage in your case should not lead to such an error. Basic TestCafe Selectors use the `document.querySelectorAll` method internally, so you can try the following:

* Execute the `document.querySelectorAll('div')` without TestCafe inside the Chrome DevTools Console. Please share the results with us.
* Simplify your Selector in the test as follows: `await t.click(Selector("div")`. Does the error still occur? Does the error only occur when you add `withAttribute` call?


I want to add that if you are able to send your project via email, our policy prevents us from accessing internal resources without prior written approval from a site owner. If we need to access non-public parts of your website or pass through authorization pages, please ask the website owner to send us ([support@devexpress.com](mailto:support@devexpress.com)) a written confirmation. It must permit DevExpress personnel to access the website and its internal resources remotely for research, testing, and debugging purposes.

**Comment by CassenH** [comment]
I won't be able to send you any project content right now but I did follow your steps.

- Using document.querySelectorAll('div') all 'div' elements are found as usual.
- await t.click(Selector("div")) leads to the same error.

For some reason the testcafe selector is not able to work with "div" elements in this project. I guess I'll try to use a workaround for this project.

**Comment by arubtsov** [comment]
@CassenH, It is impossible to determine the cause of the issue without an example. Could you create a synthetic one? It may be helpful if you share some details about the technologies you're using.
