### ISSUE TITLE
RequestLogger not working

### ISSUE THREAD

**Issue by sasasakuna** [DevExpress/testcafe#5876]
### What is your Test Scenario?
Use requestLogger to intercept requests. Run below test.js on Mac.
```
import { RequestLogger } from 'testcafe';

const logger     = RequestLogger('http://vcdn.adnxs.com/p/creative-image/27/c0/52/67/27c05267-5a6d-4874-834e-18e218493c32.png');

fixture('Prebid')
    .page(`http://prebid.org/`);

test
    .requestHooks(logger)
    (`image loading`, async (t) => {
        await t
            .expect(logger.contains(record => record.response.statusCode === 200)).ok();
    });
```
 
### What is the Current behavior?
RequestLogger is not working as expected. It can't intercept requests. 

```
Running tests in:
 - Chrome 87.0.4280.141 / macOS 10.15.5

 Prebid
 ✖ image loading

   1) AssertionError: expected false to be truthy
      
      + expected - actual
      
      -false
      +undefined
      

      Browser: Chrome 87.0.4280.141 / macOS 10.15.5

          7 |
          8 |test
          9 |    .requestHooks(logger)
         10 |    (`image loading`, async (t) => {
         11 |        await t
       > 12 |            .expect(logger.contains(record => record.response.statusCode === 200)).ok();
         13 |    });

 1/1 failed (33s)
```

### Steps to Reproduce:

1. run below test.js with command ` testcafe chrome ./tests/test.js --skip-js-errors --disable-page-caching`
```
import { RequestLogger } from 'testcafe';

const logger     = RequestLogger('http://vcdn.adnxs.com/p/creative-image/27/c0/52/67/27c05267-5a6d-4874-834e-18e218493c32.png');

fixture('Prebid')
    .page(`http://prebid.org/`);

test
    .requestHooks(logger)
    (`image loading`, async (t) => {
        await t
            .expect(logger.contains(record => record.response.statusCode === 200)).ok();
    });
```
2. See the error
```
Running tests in:
 - Chrome 87.0.4280.141 / macOS 10.15.5

 Prebid
 ✖ image loading

   1) AssertionError: expected false to be truthy
      
      + expected - actual
      
      -false
      +undefined
      

      Browser: Chrome 87.0.4280.141 / macOS 10.15.5

          7 |
          8 |test
          9 |    .requestHooks(logger)
         10 |    (`image loading`, async (t) => {
         11 |        await t
       > 12 |            .expect(logger.contains(record => record.response.statusCode === 200)).ok();
         13 |    });

```
 
### Your Environment details:
 
* testcafe version:                   "^1.10.1"
* node.js version:                    v12.20.0
* command-line arguments:  testcafe chrome ./tests/test.js --skip-js-errors --disable-page-caching
* browser name and version:  Chrome 87.0.4280.141 (Tried with other browsers(Safari 13.1.1 / macOS 10.15.5) on Mac, it has same error.)
* platform and version:         MacOS 10.15.5, Ruby ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19], Python Python 3.6.0
* other:

**Comment by Dmitry-Ostashev** [comment]
Thank you for your report. I was trying to reproduce the issue, and I didn't find the request with the url mentioned in your example. The attached screenshots illustrates a list of requests to image files. Could you please make sure that the url is correct?

![image](https://user-images.githubusercontent.com/24777868/105151071-927ce980-5b16-11eb-8ab4-5670a4864d15.png)

**Comment by sasasakuna** [comment]
Thanks for reply! I followed the same way you gave and found out it is the configuration of local env for my project is wrong so that's why the requestLogger could not find the request. You can close this one. Thanks a lot!
