### ISSUE TITLE
Unable to establish one or more of the specified browser connections on Chromium 87

### ISSUE THREAD

**Issue by fmartinou** [DevExpress/testcafe#5879]
Hi,

Our tests were perfectly working up to Chromium 85.
Starting with Chromium 87, we encounter "Unable to establish one or more of the specified browser connections" 90% of the time.

### What is your Test Scenario?
We build Docker images containing:
- Base image (`centos7` with SElinux enabled)
- TestCafe (tested with `v1.10.1`, `1.9.4`, `v1.8.8`)
- Node.js (`12.20.1`)
- Our fixtures to test

We run these images on an Openshift cluster (`v3.9.0`)
- Host VM (`centos7` with SElinux enabled)
- Requested CPU/RAM (various configurations tested up to 4 cores / 2GB RAM)

```
testcafe 'chromium:headless --no-sandbox --disable-dev-shm-usage'
```
 
### What is the Current behavior?
90% of the time, Testcafe is terminating in timeout after 2 minutes trying to connect the browser.

We have no logs except:
```
ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
```
(maybe https://github.com/DevExpress/testcafe/issues/5212 will help)

We made several tests by changing the allocated resources to the pod.
- If CPU/RAM is really low, Testcafe fails 100% of the time
- If CPU/RAM is decent (4cores/1GB RAM), Testcafe fails 90% of the time without concurrency
- If CPU/RAM is decent (4cores/1GB RAM), Testcafe fails 100% of the time with concurrency (>=2)

We made the same tests on the same Docker image with a downgraded Chromium (` v85`):
- All is perfectly working, even with high concurrency (`--concurrency=10`)

It seems to be close to the issue https://github.com/DevExpress/testcafe/issues/5212  for which I don't see a clear solution.

Any idea? Would you need additional info to investigate?

**Comment by wentwrong** [comment]
> 90% of the time, Testcafe is terminating in timeout after 2 minutes trying to connect the browser.

We added a way to change the default timeout using the "--browser-init-timeout" flag (or "browserInitTimeout" options of the [runner.run](https://devexpress.github.io/testcafe/documentation/reference/testcafe-api/runner/run.html) method and the configuration file). Although these changes are not yet reflected in the documentation, they are already included in the latest alpha version of TestCafe, so you can try them and check if they help with the issue. Install the alpha version of the TestCafe package:
```
npm i testcafe@1.10.2-alpha.1
```
After that, you can increase the default timeout using the flag I mentioned. E.g., change the default timeout value to `180000` ms (3 minutes):
```
testcafe chromium:headless e2e/**/* --browser-init-timeout 180000
```

**Comment by dlangerenken** [comment]
Hi @wentwrong - we see similar issues to what @fmartinou describes. The workaround of increasing the browser init timeout seems to work, but I'm still curious why this started to fail with newer chrome/chromium versions. Did you change something in testcafe or did the browsers memory consumption change?

**Comment by AndreyBelym** [comment]
It is likely caused by some changes in a newer browser version. Both TestCafe and your site can lead to excessive memory and CPU consumption. Since our functional tests are fine, we need an example that we can run to reproduce the issue. Without such an example, we cannot debug and fix it.
