### ISSUE TITLE
Test execution keeps blinking/reloading

### ISSUE THREAD

**Issue by sharath2106** [DevExpress/testcafe#5882]
This issue is related to https://github.com/DevExpress/testcafe/issues/3437

### What is your Test Scenario?
We're using TestCafe to run UI tests against our website. Since our website is designed to behave responsively, we are running the tests against the Chrome browser in desktop and mobile devices `(chrome:emulation:device=iphone X)`. 

### What is the Current behavior?
On running our tests against the desktop device, the tests are executed properly but when the execution is on a mobile device, there is constant flickering/blinking/reloading in the browser. Due to which we are blocked from executing tests in mobile devices.
 
### What is the Expected behavior?
The test execution should happen without any flickering/blinking issues.

```
const url = `${env.qa}/web/abcd/`;

fixture`Running Tests for /web/abcd`
  .meta('runTest', 'sanity')
  .page(url);

console.log(url);
```
env.qa = "https://www.google.com"

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...

### Your Environment details:

* testcafe version: 1.10.1                  
* node.js version: 14.4.0                  
* command-line arguments:  ```testcafe 'chrome:emulation:device=iphone X' ./tests/ --window-size=375,812 --skip-js-errors --test-meta runTest=sanity --page-load-timeout 30000 -s path=./screenshots/,takeOnFails=true```
* browser name and version: chrome

https://user-images.githubusercontent.com/25933070/105165023-d46c5680-5b3b-11eb-88fc-5e1a9703d5eb.mov

**Comment by Farfurix** [comment]
@sharath2106 

Hello,

I cannot reproduce the issue with this information. Could you please share a complete test file and specify your operating system version?

**Comment by sharath2106** [comment]
Unfortunately, I'm not supposed to share the actual source code. let me find another way and get back to you.

**Comment by hmniw** [comment]
Hey @sharath2106 did you ever find a fix for this? Definitely seeing the exact same thing happening to me when using chrome device emulation.

**Comment by apis3445** [comment]
Hey @sharath2106 did you ever find a fix for this? I got the same issue with mac m1 with chrome device emulation with last version of testcafe. I need to continue restarting VS Code
