### ISSUE TITLE
In Android Chrome the pointerdown event triggers twice

### ISSUE THREAD

**Issue by scribetw** [DevExpress/testcafe#5891]
### What is your Test Scenario?

Click an element on Android Chrome.
 
### What is the Current behavior?

Received 2 pointerdown events.
 
### What is the Expected behavior?

Receive 1 pointerdown event.
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div id="content" style="width: 100px; height: 100px; border: 1px solid red;">
        click me
    </div>
    <div id="log">
    </div>
    <script type="text/javascript">
    var c = document.getElementById('content'),
        l = document.getElementById('log');
    c.addEventListener('pointerdown', e => {
        l.innerHTML += "pointerdown"
    })
    </script>
</body>
</html>
```
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
import {Selector} from 'testcafe';

fixture `Test Touch`
    .page `./touchevent.html`

test('Test Touch', async t => {
    await t.click('#content')
        .expect(Selector('#log').innerText).eql('pointerdown');
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```
Using locally installed version of TestCafe.
Connecting 1 remote browser(s)...
Navigate to the following URL from each remote browser.
Connect URL: http://10.1.3.158:10240/browser/connect
CONNECTED Chrome 88.0.4324.93 / Android 7.1.2
 Running tests in:
 - Chrome 88.0.4324.93 / Android 7.1.2

 Test Touch
 ✖ Test Touch

   1) AssertionError: expected 'pointerdownpointerdown' to deeply equal 'pointerdown'
      
      + expected - actual
      
      -'pointerdownpointerdown'
      +'pointerdown'
      

      Browser: Chrome 88.0.4324.93 / Android 7.1.2

         3 |fixture `Test Touch`
         4 |    .page `./touchevent.html`
         5 |
         6 |test('Test Touch', async t => {
         7 |    await t.click('#content')
       > 8 |        .expect(Selector('#log').innerText).eql('pointerdown');
         9 |});

         at <anonymous> (/Users/rudyhuang/IdeaProjects/testcafe/test-touch.js:8:45)
         at asyncGeneratorStep (/Users/rudyhuang/IdeaProjects/testcafe/test-touch.js:1:230)
         at _next (/Users/rudyhuang/IdeaProjects/testcafe/test-touch.js:1:568)
         at <anonymous> (/Users/rudyhuang/IdeaProjects/testcafe/test-touch.js:1:733)
         at <anonymous> (/Users/rudyhuang/IdeaProjects/testcafe/test-touch.js:1:474)
         at <anonymous> (/Users/rudyhuang/IdeaProjects/testcafe/test-touch.js:6:5)



 1/1 failed (5s)
```
</details>

<details>
<summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/6398934/105686827-ac616680-5f32-11eb-8fb0-7ff8a0fe3d2b.png)

</details>

### Steps to Reproduce:

1. Save the HTML (touchevent.html) and test js
2. Execute TestCafe using remote or "chrome:emulation:device=Pixel 2"
```
testcafe remote --ports 10240,10241 test-touch.js
testcafe "chrome:emulation:device=Pixel 2" test-touch.js
```
3. See the error...
 
### Your Environment details:
 
* testcafe version: 1.10.1                  
* node.js version: v14.15.0                   
* command-line arguments: `testcafe remote --ports 10240,10241 test-touch.js` 
* browser name and version: Chrome 88.0.4324.93 
* platform and version: Android 7.1.2 (Using BlueStacks 4 mac)         
* other:

**Comment by Farfurix** [comment]
@scribetw 

Hello,

Thank you for the example. I reproduced the issue. Our team will examine this case and check for a suitable solution.

**Comment by AlexKamaev** [comment]
fixed in https://github.com/DevExpress/testcafe-hammerhead/pull/2718
