### ISSUE TITLE
XML files can not be downloaded without dialogue box [Firefox]

### ISSUE THREAD

**Issue by Ivan-Katovich** [DevExpress/testcafe#5892]
### What is your Test Scenario?
Go to an application and try to export XML file using **firefox** browser
 
### What is the Current behavior?
Dialog box appears each time I try to do it
 
### What is the Expected behavior?
XML file downloaded without any dialogs

 
<details>
<summary>can NOT be fixed by adding necessary parameter to browser.helperApps.neverAsk.saveToDisk into firefox's about:config</summary>
</details>
 
### Your Environment details:
 
* testcafe version:                   1.10.1
* node.js version:                    12.18.1
* browser name and version: firefox 84.0.2 (64-bit)
* platform and version:          Windows 10 Enterprise

**Comment by arubtsov** [comment]
Hi @Ivan-Katovich. Thank you for your input. I reproduced this behavior.

**Comment by AndreyBelym** [comment]
Closed by #6218
