### ISSUE TITLE
[docs] Document how to setup Testcafe on custom docker image

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#5894]
Describe:
- which images it's possible to use
- why it's necessary to install some package: `tzdata` (https://github.com/DevExpress/testcafe/issues/5572), `fluxbox` - for 'Resize' action support, `xvfb` - headless browsers, etc.

**Comment by miherlosev** [comment]
https://stackoverflow.com/questions/65925380/run-a-testcafe-script-on-chrome-headless-in-a-docker-container

**Comment by titerman** [comment]
Closed in favour of #7153
