### ISSUE TITLE
test fails to navigate to success page as request header size exceeds the set limit

### ISSUE THREAD

**Issue by sharda-Mahendra-cko** [DevExpress/testcafe#5896]
<!--

I am trying to run a test on Ecommerce platform which creates an order. Test fails when it tries to navigate to success page which displays the order number with below message

  Error details:
  Failed to perform a request to the resource at
  "URL" because of an error.
  The request header's size is 2257 bytes which exceeds the set limit.

As suggested I used below command to change the max header size and run the test locally

export NODE_OPTIONS="--max-http-header-size=64000" & npm run test.local;

but still it fails and every time I get a different request header size.

### Your Environment details:
 
* testcafe version:                    1.9.4
* node.js version:                    12.18.3
* browser name and version:  Chrome  88.0.4324.96
* platform and version:          macOS 10.15

**Comment by AlexSkorkin** [comment]
Please submit a new issue and fill the issue template completely including your TestCafe version and a sample.
