### ISSUE TITLE
Test fails to navigate to success page as request header size exceeds the set limit

### ISSUE THREAD

**Issue by sharda-Mahendra-cko** [DevExpress/testcafe#5897]
Scenario:
My test creates an order on Ecommerce website.
When test tries to navigate to success page (which displays the order number),it fails. 

  Error details:
  Failed to perform a request to the resource at
  "URL" because of an error.
  The request header's size is 2257 bytes which exceeds the set limit.

I am using below command to change the max header size and run the test locally

export NODE_OPTIONS="--max-http-header-size=64000" & npm run test.local;

but still the test fails and every time I get a different request header size limit.

Can you help??

### Your Environment details:
 
* testcafe version:                   ~~1.9.4~~ 1.10.1
* node.js version:                    v12.18.3
* command-line arguments:  export NODE_OPTIONS="--max-http-header-size=64000" & npm run test.local;
* browser name and version: chrome  88.0.4324.96
* platform and version:          macOS 10.15.7

**Comment by sharda-Mahendra-cko** [comment]
I have updated the testcafe version to 1.10.1, and I still face the same issue.

**Comment by miherlosev** [comment]
Hi @sharda-Mahendra-cko

TestCafe sets up the maximum header size for a request as [80 kb](https://github.com/DevExpress/testcafe-hammerhead/blob/8e8f0f33ac5d2bed1ca084b248816a1256894818/src/proxy/index.ts#L60(https://github.com/DevExpress/testcafe-hammerhead/blob/8e8f0f33ac5d2bed1ca084b248816a1256894818/src/proxy/index.ts#L60)). It means that you can remove the `export NODE_OPTIONS="--max-http-header-size=64000"` instruction from TestCafe's run parameters.

If after applying this change, the issue persists, please share with us an example that we can debug locally.
