### ISSUE TITLE
Is Multiple Browser Window Functionality Ready for Production Environments?

### ISSUE THREAD

**Issue by kathyzknight** [DevExpress/testcafe#5901]
### What is your Test Scenario?
Thank you so much for TestCafe, and the latest Multiple Browser Windows functionality, wonderful tools!  I want to run a very basic TestCafe script without the _--disable-multiple-windows_ command line flag, on our Production environment.  I still have challenges with some features (closeWindow, switchToPreviousWindow), so I'm not using them.  Instead, my script launches a 2nd window mid-script, and finishes the script in the 2nd window.  I have run it repeatedly on test environments, with great success!

### What are you suggesting?
TestCafe [documentation](https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/multiple-browser-windows.html) states "Please do not use this feature in production environments."  What is the latest TestCafe recommendation?  Is Multiple Browser Windows (limited) functionality ready for Production environments?

**Comment by miherlosev** [comment]
Hi @kathyzknight

For the current TestCafe version (1.10.1), this feature has an experimental status. So, the 'Please do not use this feature in production environments.' recommendation is actual.
However, we are preparing the official release of the 'Testing in multiple browser windows' functionality. Stay tuned for official resources: blog, changelog, etc.
