### ISSUE TITLE
single fixture with 2000+ tests hangs then closes

### ISSUE THREAD

**Issue by jpelt-engie** [DevExpress/testcafe#5906]
### What is your Test Scenario?

I use xstate/test. It currently generates 16499 tests.
 
### What is the Current behavior?

After generating the tests but before running them the browser closes and I see the following:

ERROR The Chrome 87.0.4280.141 / Windows 10 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.
 
### What is the Expected behavior?

Tests run.
 
### What is your web application and your TestCafe test code?

 

<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 const TOTAL_TESTS = 2000;

const tests = (new Array(TOTAL_TESTS))
    .fill(1)
    .map((one, i) => one + i);

tests.forEach((value) => {
    fixture(`test: ${value}`)
        .disablePageReloads
        .page('example.com');

    test(`via: ${value}`, async (t) => {
        await t.expect(value).eql(value);
    });
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
    "browsers": ["chrome"],
    "hostname": "localhost",
    "clientScripts": [
        {
            "module": "@testing-library/dom/dist/@testing-library/dom.umd.js"
        }
    ]
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

Running 2000 or more tests seems to always hang.
 
### Your Environment details:
 
* testcafe version:                   1.10.1 
* node.js version:                    15.5.1 
* command-line arguments:  npx testcafe chrome ./e2e/specs/example.e2e-spec.ts 
* browser name and version: chrome 87.0.4280.141 
* platform and version:          windows 10 
* other:                                   just limiting to less than 1000 tests seems to work, but I really need to be able to generate a significant number of tests.

**Comment by jpelt-engie** [comment]
I found that running the testcafe global does work. I currently think it has something to do with @testing-library in my clientScripts.

**Comment by jpelt-engie** [comment]
It has something to do with @testing-library/dom/dist/@testing-library/dom.umd.js. When I remove that, the tests run.

**Comment by felis2803** [comment]
I tried to reproduce the problem without the libraries you specified but failed. So, it seems it's related to them than to our components. I recommend that you contact the author of the library to research the issue further.

**Comment by jpelt-engie** [comment]
I think so as well.
