### ISSUE TITLE
useRole not redirecting back to test as expected

### ISSUE THREAD

**Issue by ben-gooding-sky** [DevExpress/testcafe#5907]
### What is your Test Scenario?
My app works in a specific way that redirects to login if not logged in, and then when you login it redirects to either your previous page or, the home page.

### What is the Current behavior?
When using `useRole` it works as expected the first run through and logs in and redirects to home and as expected goes back to the page the test was run on.

But on the second run through it gets the session cookie as expected, but goes to the login page (which I thought it shouldn't do since it already has the session cookie as useRole has already been used on this fixture) and then instantly redirects to the home page since it's already logged in (not the same as the page in the test) and gets stuck on the home page.
 
### What is the Expected behavior?
I would expect to call .useRole(someRole) in the second test and not be redirected to the login page at all, or at least not get stuck after it redirects on the login page
 
### What is your web application and your TestCafe test code?
This is a next.js application, so it's react based but uses next.js router.push() to redirect (not sure if this interferes)
 

<summary>Your complete test code (or attach your test files):</summary>

 
```js
class LoginPage {
  async login(username, password) {
    await t.typeText(this.usernameInput, username).typeText(this.passwordInput, password).click(this.loginButton);
  }
}
 const admin = Role(`${BASE_URL}/login`, async () => {
  await LoginPage.login(process.env.ADMIN_USERNAME, process.env.ADMIN_PASSWORD);
});

fixture('Some page')
  .page(someUrl)
  .beforeEach(async (t) => {
    await t.useRole(admin);
  });
test('test 1', async (t) => {
  await t.expect(selectSomething).contains('text that only admin can see'); //Passes
});
test('test 2', async (t) => {
  await t.expect(selectSomething).contains('text that only admin can see'); //Fails, stuck on home page
});
test('test 3', async (t) => {
  await t.navigateTo(someUrl);
  await t.expect(selectSomething).contains('text that only admin can see'); //Passes
});

 
### Your Environment details:
 
* testcafe version: 1.9.4
* node.js version: 12.19.0
* command-line arguments: `NODE_ENV=test testcafe 'chrome:headless --start-maximized' dirToTests/testcafe`
* browser name and version: chrome
* platform and version: mac0S 10

**Comment by aleks-pro** [comment]
Hello @ben-gooding-sky,

Thank you for the test code.
Could you please share a sample project of the Web application where we can reproduce the issue? You can sent it to supportcenter@devexpress.com.

**Comment by Steven-Beasley** [comment]
sounds like you want to user the preserveUrl: true option
```
const admin = Role(`${BASE_URL}/login`, async () => {
  await LoginPage.login(process.env.ADMIN_USERNAME, process.env.ADMIN_PASSWORD);
}, {preserverUrl: true});
```

If that still doesn't give you the results you want.  we had to add a navigateTo(page I want to land on) after using the useRole
