### ISSUE TITLE
RFC: support typescript compilation via babel, versus tsc

### ISSUE THREAD

**Issue by cdaringe** [DevExpress/testcafe#5911]
### What is your Test Scenario?

testing with typescript

### What are you suggesting?

- [TestCafe supports TypeScript](https://devexpress.github.io/testcafe/documentation/guides/concepts/typescript-and-coffeescript.html), but this uses the typescript compiler. Though `tsc` is _great_, it is assumed that for various project and source-code, using `babel` to simply _strip_ types and convert to javascript should be faster. Because we typecheck at _other_ quality gates/steps in our system, it would be great to remove the typecheck penalty from our TestCafe tests to _go faster_

### What alternatives have you considered?

- sucrase, swc, friends. but, `babel` is already first class in TC, so perhaps simply supporting the TS plugins in babel would do the trick!

### Additional context

- https://www.typescriptlang.org/docs/handbook/babel-with-typescript.html#babel-for-transpiling-tsc-for-types
- benchmarking here is probably _worthwhile_. i suspect that perf w/ code w/ complex types will be faster w/ babel, but may not be significant for smaller codebases/projects

**Comment by wentwrong** [comment]
Thank you for your inquiry. I'll close this thread because we already have a similar enhancement request at [#2659](https://github.com/DevExpress/testcafe/issues/2659) - there, we will address support of different compiler backends. Please use it to track our progress with this feature.
