### ISSUE TITLE
The hover action doesn't effect certain radio button components

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe#5916]
Based on the following SC ticket: https://supportcenter.devexpress.com/internal/ticket/details/T969328/

Steps to reproduce:

Steps to reproduce:

1. Run the Linux machine (I've done it with Debian).
2. Clone the repository mentioned in the SC ticket.
3. Run `sudo npm i`. I've managed to install all the required dependencies with root credentials. If some problems occur during the installation, make sure that` python3` and `pip` are installed on the machine.
4. Run `npm run build`.
5. Run `npm run dev`.
6. 1. Open the following webpage - http://localhost:8080/playback/controls/player/radiobutton-widget/basic-radio. 1. You will be able to hover over these radio buttons.
7. Run the following test: 

```
import { Selector } from 'testcafe';

fixture `hover`
    .page `http://localhost:8080/playback/controls/player/radiobutton-widget/basic-radio`;

test('New Test', async t => {
    await t
        .hover(Selector('input').nth(0))
        .debug();
});
```
8. The t.hover action does nothing.
9. Unlock the page and try to move the mouse cursor across the radio buttons. They wouldn't display their "hovered" state.

* testcafe version:                  1.10.1
* node.js version:                    14.15.4
* command-line arguments:   npx testcafe chrome test.js
* browser name and version: Chrome 87
* platform and version:          Debian 10 (or Ubuntu 20)

**Comment by AlexKamaev** [comment]
fixed in https://github.com/DevExpress/testcafe-hammerhead/pull/2587
