### ISSUE TITLE
Selector is not working with attributes

### ISSUE THREAD

**Issue by glazovg** [DevExpress/testcafe#5917]
Testcafe has problems when attributes are set into the selector either with a proper one.
example:

select ('[class="tab-pane active "] input[id*=investment-amount]');

Getting:
<img width="1073" alt="Screen Shot 2021-02-04 at 5 44 51 PM" src="https://user-images.githubusercontent.com/43226340/106969570-afb5d880-6710-11eb-9d7a-e791516c21f8.png">

Selector working properly from chrome console:
<img width="532" alt="Screen Shot 2021-02-04 at 5 46 00 PM" src="https://user-images.githubusercontent.com/43226340/106969652-daa02c80-6710-11eb-97dd-fe005581d13b.png">

Am I setting the attributes in a wrong way?

Is there any way to set the attributes and make it work? I even tried with:

<img width="1064" alt="Screen Shot 2021-02-04 at 5 47 22 PM" src="https://user-images.githubusercontent.com/43226340/106969729-0ae7cb00-6711-11eb-8ee5-367797106467.png">

### Environment details:
 
* testcafe version:                   1.10.0
* node.js version:                    10.22.1
* browser name and version: Chrome 87
* platform and version:          Windows 10

**Comment by felis2803** [comment]
Hello,
I could not reproduce the error with selectors similar to yours. I guess the problem is not in how you define the selectors. Could you please send us a page address and an example of a test that fails with such an error?

**Comment by glazovg** [comment]
Hi Felis,

I cannot share the page address since is a bank's project, but I can send these images, one of the DOM and the other one of my step definition code:

<img width="1011" alt="Screen Shot 2021-02-05 at 11 05 43 AM" src="https://user-images.githubusercontent.com/43226340/107065684-abd29680-67a2-11eb-9af5-0c6d7603f192.png">


<img width="687" alt="Screen Shot 2021-02-05 at 11 07 12 AM" src="https://user-images.githubusercontent.com/43226340/107065705-b42ad180-67a2-11eb-99b6-f2bd07481aac.png">


Thanks in advance.

**Comment by felis2803** [comment]
I'm happy to hear that you figured out how to resolve the issue.
