### ISSUE TITLE
typeText replace option doesn't work when the input already has a value that fit maxlength

### ISSUE THREAD

**Issue by rueyaa332266** [DevExpress/testcafe#5921]
### What is your Test Scenario?
Replacing the old value in the text input with a new value. The old value has a length that fit maxlength.
 
### What is the Current behavior?
The new value doesn't replace the old value.
 
### What is the Expected behavior?
The new value replace the old value.
 
### What is your web application and your TestCafe test code?
 
<details>
<summary>Your website URL (or attach your complete example):</summary>
The example app is just a simple html form.

```html
<form>
    <input type="text" id="name" maxlength="5">
</form>
```

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

```js
import { Selector } from 'testcafe';

fixture `Example`
    .page `file:///path/to/form.html`;

test('Example test', async t => {
    await t
        .typeText('#name', '12345') // Input the old value.
        .typeText('#name', 'abcde', { replace: true }) // Replace the new value.
        .expect(Selector('#name').value).eql('abcde'); // Assert the input value.
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

Not using configuration file.
</details>

<details>
<summary>Your complete test report:</summary>
Actually it's not getting any error.

```
 Running tests in:
 - Chrome 88.0.4324.146 / macOS 10.15.7

 Example
 ✖ Example test

   1) AssertionError: expected '12345' to deeply equal 'abcde'
      
      + expected - actual
      
      -'12345'
      +'abcde'
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Create an example html file.
```html:form.html
<form>
    <input type="text" id="name" maxlength="5">
</form>
```
2. Create an example test file.
```js:example.js
import { Selector } from 'testcafe';

fixture `Example`
    .page `file:///path/to/form.html`;

test('Example test', async t => {
    await t
        .typeText('#name', '12345') // Input the old value.
        .typeText('#name', 'abcde', { replace: true }) // Replace the new value.
        .expect(Selector('#name').value).eql('abcde'); // Assert the input value.
});
```
3. Execute this command
```
testcafe chrome example.js
```
4. Check the behavior.
 
### Your Environment details:
 
* testcafe version: 1.10.1 
* node.js version: v14.6.0  
* command-line arguments: testcafe chrome example.js
* browser name and version: Chrome 88.0.4324.146 
* platform and version: macOS 10.15.7

**Comment by AlexKamaev** [comment]
Thank you for the example. I reproduced the issue.

**Comment by rueyaa332266** [comment]
@AlexKamaev 
Hi, thanks for reproducing the issue. 
If it's not a critical bug, I'm wondering that can I try to fix it by myself?

**Comment by AlexKamaev** [comment]
You need to take a look at the following method:
https://github.com/DevExpress/testcafe/blob/46460d16e044abff52bff497aaec29b20022ed21/src/client/automation/playback/type/type-text.js#L242

I modified it as follows:
```JS
function _typeTextToTextEditable (element, text) {
    const elementValue      = domUtils.getElementValue(element);
    const textLength        = text.length;
    let startSelection      = textSelection.getSelectionStart(element);
    let endSelection        = textSelection.getSelectionEnd(element);
    const isInputTypeNumber = domUtils.isInputElement(element) && element.type === 'number';

    if (!simulateBeforeInput(element, text, browserUtils.isChrome))
        return;

    let needProcessInput = simulateTextInput(element, text);

    if (needProcessInput)
        needProcessInput = simulateBeforeInput(element, text, browserUtils.isSafari);

    if (!needProcessInput)
        return;

    // NOTE: the 'maxlength' attribute doesn't work in all browsers. IE still doesn't support input with the 'number' type
    let elementMaxLength = !browserUtils.isIE && isInputTypeNumber ? null : parseInt(element.maxLength, 10);

    if (elementMaxLength < 0)
        elementMaxLength = browserUtils.isIE && browserUtils.version < 17 ? 0 : null;

    const newElementValue = elementValue.substring(0, startSelection) + text + elementValue.substring(endSelection, elementValue.length);

    if (elementMaxLength === null || isNaN(elementMaxLength) || elementMaxLength >= newElementValue.length) {
        // NOTE: B254013
        if (isInputTypeNumber && browserUtils.isIOS && elementValue[elementValue.length - 1] === '.') {
            startSelection += 1;
            endSelection += 1;
        }

        domUtils.setElementValue(element, newElementValue);

        textSelection.select(element, startSelection + textLength, startSelection + textLength);
    }

    // NOTE: We should simulate the 'input' event after typing a char (B253410, T138385)
    eventSimulator.input(element, text);
}
```
And now, the test is successfully passed.
If you want to create a PR, you can take my method and test it with more complex scenarios.
Also, you need to add your test to the following folder:
https://github.com/DevExpress/testcafe/tree/master/test/functional/fixtures/regression
Please take a look at any other test in this folder and make a similar one.
Thank you in advance.
