### ISSUE TITLE
Stripe payment system does not load on iOs Safari 14 due to cross origin errors

### ISSUE THREAD

**Issue by PedroBorracho** [DevExpress/testcafe#5922]
### What is your Test Scenario?
On iOs Safari 14, a payment page containing Stripe Iframes fails to load with these errors:

`
Blocked a frame with origin "http://localhost:1402" from accessing a frame with origin "http://localhost:1401". Protocols, domains, and ports must match.
`

`
Blocked a frame with origin "http://localhost:1401" from accessing a frame with origin "http://localhost:1402". Protocols, domains, and ports must match.
`

There is a way to force the port used to load the web site content to a single port or bypass specific domains to have all the frames targeting the same origin?

### Steps to Reproduce:
It can be reproduced by writing a test targeting the [Stripe demo](https://stripe-payments-demo.appspot.com) or directly using the Hammerhead playground targeting the same page using an iOs device (or iOs Simulators in xCode).

The page will not load the Payment form properly and you will see the errors in console.
<img width="1012" alt="Screenshot 2021-02-07 at 21 04 19" src="https://user-images.githubusercontent.com/1810992/107158845-f7e12f00-698c-11eb-973a-3a5f3dc01044.png">
 
### Your Environment details:
* testcafe version:                  v1.9.4
* node.js version:                   v10.15.3
* browser name and version: Safari on iOs 13, iOs14
* platform and version:          iOs 13, iOs14

**Comment by PedroBorracho** [comment]
is present also updating to:
`
"testcafe": "1.10.1"
`

**Comment by Farfurix** [comment]
@PedroBorracho 

Hello,

I reproduced the "Blocked a frame with origin "http://localhost:1402" from accessing a frame with origin "http://localhost:1401". Protocols, domains, and ports must match." issue with macOS, Safari, and the latest `testcafe-hammerhead`. Our team will examine this issue and check for a suitable solution.

**Comment by PedroBorracho** [comment]
any update? There are possible workaround to put in place waiting for a fix?

Thanks!

**Comment by Farfurix** [comment]
@PedroBorracho 

Hello,

Unfortunately, no updates and no workaround for this issue yet.

**Comment by sladg** [comment]
Hey, having the same problem, @PedroBorracho is there any open issue on the Stripe repo? I wasn't able to find anything else related to Stripe on Safari 14.
