### ISSUE TITLE
"use strict" on SSO pages

### ISSUE THREAD

**Issue by csutorasr** [DevExpress/testcafe#5927]
### What is your Test Scenario?

I have addressed an issue on Stackoverflow. It is described well there. https://stackoverflow.com/questions/66030966/strict-mode-testcafe
 
### What is the Current behavior?

The page is not loading due to javascript error in Chrome. The script is not parsed, and cannot go further from login.

The page is working in real case scenario.
 
### What is the Expected behavior?

Make the site work as expected. This is working in real flows, only testcafe breaks it.
 
### What is your web application and your TestCafe test code?

Angular application redirecting to AngularJS application for SSO.
The AngularJS application won't even load. So navigating to that page is not working at all.
 
<details>
<summary>Your website URL (or attach your complete example):</summary>

The name of the site is secret. I have mailed it to support@devexpress.com, if you would like to test in the real scenario. Please handle it carefully.

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

```js
 export const adminRole = Role(
  `https://url of the oauth site`,
  async (t) => {
    await t
      .typeText(Selector('#username'), 'username')
      .typeText(Selector('#password'), 'strongpassword')
      .click(Selector('#mainButton'));
  },
  { preserveUrl: true }
);

fixture('Home page');

test('Show profile page', async (t) => {
  await t.useRole(adminRole);
  await t.navigateTo('http://tested site/profile');
  await waitForAngular();
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>
This is the original config file.
</details>

<details>
<summary>Your complete test report:</summary>

```
- Error in Role initializer -
      A JavaScript error occurred on ...
Repeat test actions in the browser and check the console for errors.
      If you see this error, it means that the tested website caused it. You can fix it or disable tracking JavaScript errors in TestCafe. To do the
      latter, enable the "--skip-js-errors" option.
      If this error does not occur, please write a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".
      
      JavaScript error details:
      SyntaxError: In strict mode code, functions can only be declared at top level or inside a block.

      Browser: Chrome 88.0.4324.146 / macOS 10.15.7
```
</details>

<details>
<summary>Screenshots:</summary>
A white page, as AngularJS couldn't load.
</details>

### Steps to Reproduce:

1. Go to the provided page.
2. See the error.
 
### Your Environment details:
 
* testcafe version:                   1.10.1
* node.js version:                    v12.18.3
* command-line arguments:  chrome --no-sandbox
* browser name and version: Chrome 88.0.4324.150
* platform and version:          macOS 10.15.7
* other:                                   The name of the site is secret. I have mailed it to support@devexpress.com, if you would like to test in the real scenario. Please handle it carefully.

**Comment by AlexSkorkin** [comment]
Thank you for reaching out to us and submitting this issue. We requested additional information by replying to your Email.

**Comment by Farfurix** [comment]
@csutorasr 

Hello,

I reproduced the issue with Windows 10 and Chrome. Our team will examine this case and check for a suitable solution.

**For the team.**
This issue can be reproduced with `http-playground`.
The "Uncaught SyntaxError: In strict mode code, functions can only be declared at top level or inside a block." minimal example:
```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>i5927</title>
</head>
<body>
<script>
    !function () {
        "use strict";
        var fn = function() {
            var location = 0;
            if (true)
                do
                    location += '',
                    void 0;
                while (true);
                return location = '';
        };
    }();
</script>
</body>
</html>
```

**Comment by csutorasr** [comment]
Is here any news regarding this issue?
