### ISSUE TITLE
Deleting cookie during testcafe test does not work

### ISSUE THREAD

**Issue by ghost23** [DevExpress/testcafe#5929]
### What is your Test Scenario?
I have created a minimalistic example here: https://github.com/ghost23/testcafe-cookie-test

I have a web app, that creates a cookie with the push of one button and deletes it with the push of another button. It does the deletion via setting the value to empty and max-age to 0.
 
### What is the Current behavior?
After deleting the cookie this way, when testing this manually in the browser, document.cookie does not return any cookies anymore.

But when testing this within a testcafe test, document.cookie returns the cookie with an empty value.
 
### What is the Expected behavior?
I want testcafe to behave the same way as with the manual test. If I set the cookie to empty value and max-age to 0, the cookie should be gone completely and not just set to empty value.
 
### What is your web application and your TestCafe test code?
Again, see here: https://github.com/ghost23/testcafe-cookie-test

### Steps to Reproduce:
- checkout https://github.com/ghost23/testcafe-cookie-test
- `npm install`
- in one terminal: `npm run serve`
- in another terminal `npm run test`
 
### Your Environment details:
 
* testcafe version:                   1.10.1
* node.js version:                    14.0.0
* command-line arguments:  testcafe chrome test/cookie.test.js
* browser name and version: Chrome Version 88.0.4324.146
* platform and version:          Windows

**Comment by AlexanderMoiseev** [comment]
Hello,

Thank you for the example project. We have reproduced the issue and need some time to investigate it, please stay tuned.

**Comment by dgrebb** [comment]
@AlexanderMoiseev howdy! Was this ever resolved?
