### ISSUE TITLE
`Cannot switch to the window` after/while interacting with child window

### ISSUE THREAD

**Issue by rob4629** [DevExpress/testcafe#5930]
### What is your Test Scenario?

We have a number of tests which interact with the PayPal window, multiple times.

Example flow:
1. Make a Payment using PayPal
2. Return to Payment page, and make a 2nd Payment
3. Interact with PayPal 3rd time
4. Confirm payment successful
 
### What is the Current behavior?

Although inconsistently, TestCafe often fails switching between windows; either the last step inside the paypal child window (click _confirm/continue_), or the 1st step after the window closes (_switching to the PayPal iFrame, to click again_): `Cannot switch to the window`.
For some reason the test for my demo app also fails with `A native alert dialog was invoked on page...` but that is unrelated since it's not happening on our actual tests.
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

If you check out my [testcafe_issues](https://github.com/rob4629/testcafe_issues) repo, you should just be able to use the test `Enter child window multiple times`
1. npm start -- starts the local server.
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 

```js
 fixture("Multiple Window Testing").page("localhost:4000")

const clickPayWithPaypal = async () => {
    const buttonIframe = Selector('#smart-button-container iframe');
    const payWithPaypalButton = Selector('[data-funding-source="paypal"]');

    await t
        .switchToIframe(buttonIframe)
        .expect(payWithPaypalButton.with({ visibilityCheck: true }).exists)
        .ok({ timeout: 40000 })
        .hover(payWithPaypalButton)
        .click(payWithPaypalButton)
        .switchToMainWindow();
}

const clickContinueButtonWithRetry = async () => {
    const acceptAllButton = Selector('#acceptAllButton');
    const continueButton = Selector('[data-testid="submit-button-initial"]');
    if (await acceptAllButton.visible) await t.click(acceptAllButton);
    await t.click(continueButton);
    if (await continueButton.visible) await t.click(continueButton);
  }

test("Enter child window multiple times", async () => {
    await clickPayWithPaypal();

    await t
      .typeText(Selector('#email'), <test-email>)
      .click(Selector('#btnNext'))
      .typeText(Selector('#password'), <test-password>)
      .click(Selector('#btnLogin'));
    await clickContinueButtonWithRetry();

    // Repeat
    await clickPayWithPaypal();
    await clickContinueButtonWithRetry();

    // Repeat
    await clickPayWithPaypal();
    await t.click(Selector('[data-testid="submit-button-initial"]')).wait(750);
});

```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
  "assertionTimeout": 15000,
  "pageLoadTimeout": 30000,
  "selectorTimeout": 15000,

  "disableMultipleWindows": false,

  "quarantineMode": false,
  "skipJsErrors": true,

  "disablePageCaching": true,

  "reporter": [
    {
      "name": "xunit",
      "output": "artifacts/test-results/results.xml"
    },
    {
      "name": "spec"
    }
  ],

  "screenshots": {
    "fullPage": true,
    "takeOnFails": true,
    "pathPattern": "${TEST_ID}/${RUN_ID}_${FILE_INDEX}.png",
    "path": "artifacts/screenshots"
  }
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```
 Enter child window multiple times (screenshots:
 /Users/rcooper/Personal/testcafe_issues/artifacts/screenshots/test-1/_errors/1.png)

   1) A native alert dialog was invoked on page "http://localhost:4000/", but no handler was set for it. Use the
      "setNativeDialogHandler" function to introduce a handler function for native dialogs.

      Browser: Chrome 88.0.4324.150 / macOS 10.15.7


   2) Cannot switch to the window.

      Browser: Chrome 88.0.4324.150 / macOS 10.15.7
      Screenshot: null

         22 |}
         23 |
         24 |const clickContinueButtonWithRetry = async () => {
         25 |    const acceptAllButton = Selector('#acceptAllButton');
         26 |    const continueButton = Selector('[data-testid="submit-button-initial"]');
       > 27 |    if (await acceptAllButton.visible) await t.click(acceptAllButton);
         28 |    await t.setNativeDialogHandler(() => true).click(continueButton);
         29 |    if (await continueButton.visible) await t.setNativeDialogHandler(() => true).click(continueButton);
         30 |  }
         31 |
         32 |test("Click link within iFrame to open window", async () => {

         at <anonymous> (/Users/rcooper/Personal/testcafe_issues/tests/multi_window_link.js:27:31)
         at asyncGeneratorStep (/Users/rcooper/Personal/testcafe_issues/tests/multi_window_link.js:1:231)
         at _next (/Users/rcooper/Personal/testcafe_issues/tests/multi_window_link.js:1:569)
         at <anonymous> (/Users/rcooper/Personal/testcafe_issues/tests/multi_window_link.js:1:734)
         at <anonymous> (/Users/rcooper/Personal/testcafe_issues/tests/multi_window_link.js:1:475)
         at clickContinueButtonWithRetry (/Users/rcooper/Personal/testcafe_issues/tests/multi_window_link.js:24:35)
         at <anonymous> (/Users/rcooper/Personal/testcafe_issues/tests/multi_window_link.js:58:11)
         at asyncGeneratorStep (/Users/rcooper/Personal/testcafe_issues/tests/multi_window_link.js:1:231)
         at _next (/Users/rcooper/Personal/testcafe_issues/tests/multi_window_link.js:1:569)


 1/1 failed (45s)
npm ERR! Test failed.  See above for more details.
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Check out my demo repo
2. Start the server (`npm start`)
3. Open a new console and run the `Enter child window multiple times` test
4. See the error...
 
### Your Environment details:
 
* testcafe version: 1.10.0-rc.4 > 1.10.2-alpha.2                  
* node.js version: 12.14.3                   
* command-line arguments:  
* browser name and version: Chrome 87 
* platform and version: Mac OS  
* other:

**Comment by rob4629** [comment]
I left the PayPal email and password blank, hoping you might have a sandbox/demo environment of your own. If you need this info, let me know and I'll send them over.

**Comment by AlexKamaev** [comment]
I was able to reproduce the issue. I think that its cause partially lies in the test code.
We do not need to call `switchToMainWindow` here because we will be working in the child window by that time:
[https://github.com/rob4629/testcafe_issues/blob/398ed793eec857f66426673e231db4ab8162fcec/tests/multi_window_link.js#L15](https://github.com/rob4629/testcafe_issues/blob/398ed793eec857f66426673e231db4ab8162fcec/tests/multi_window_link.js#L15)

Besides, it seems to me that this line is also redundant because we are in the child window where there is no alert message:
[https://github.com/rob4629/testcafe_issues/blob/398ed793eec857f66426673e231db4ab8162fcec/tests/multi_window_link.js#L22](https://github.com/rob4629/testcafe_issues/blob/398ed793eec857f66426673e231db4ab8162fcec/tests/multi_window_link.js#L22)

However, even if I modify the test code, different issues still occur. I'll research them further.

**Comment by rob4629** [comment]
Ok, I'll play about with it today and see if I can find anything. I remember hitting some issues previously by **not** specifying `switchToMainWindow `... but that might have been before the introduction of multi-window support...

> Besides, it seems to me that this line is also redundant because we are in the child window where there is no alert message:
Definitely redundant, I put it there due to the fact it was failing with `A native alert dialog was invoked on page...`. I'll remove it from the example (as it isn't in our actual test code).
