### ISSUE TITLE
[docs] Describe '--cache' option

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#5935]
Need to do
- [x] Describe the `--cache` option.
- [x] Add paragraph to the `Decrease test execution time` topic.

Draft "--cache" option description:
The `--cache` option enables the caching of the website resources (styles, script, images, etc.) on the TestCafe's proxy side.
![image](https://user-images.githubusercontent.com/4133518/107335903-8c50ac00-6ac9-11eb-9f25-ba612db2b51b.png)
TestCafe emulates the native browser behavior and cache only these files that the browser will cache without TestCafe.
TestCafe does not cache the HTML pages and some other resources because it may break the `Roles` feature.
The use of this feature can be useful if your application loads a lot of resources (scripts, styles, fonts, etc.) on the first visit and cache them. Note, that this feature is experimental.

The '--cache' option is available in 3 interfaces: command-line, programmatic, and configuration file.
*Command-line*
```js
testcafe chrome tests --cache
```

*Programmatic*
```js
runner.run({ cache: true });
```

*Configuration file*
```js
{
 "cache": true
}
```

**Comment by DIRECTcut** [comment]
fixed in #5969
