### ISSUE TITLE
getComputedStyle method does not work for pseudo-elements on Firefox

### ISSUE THREAD

**Issue by Nikolaj1010** [DevExpress/testcafe#5944]
### What is your Test Scenario?
I am trying to get a style property of pseudo-element (:after) using `window.getComputedStyle` but it does not work on Firefox browser.
 
### What is the Current behavior?
When I am trying to get a style property (border style in my case) from (:after) pseudo-element, my code in TestCafe returns undefined on Firefox browser. The same code perfectly works in Chrome. It seems that method which I am using `getPseudoElementFunction`  (you can find it in the example below) returns an incomplete object of all styles in TestCafe unlike the case when I tried it directly in the browser console.
I also tried to use getDefaultComputedStyle instead of .getComputedStyle in TestCafe and the result is still the same.
 
### What is the Expected behavior?
`window.getComputedStyle` should work on Firefox in TestCafe too
 
### What is your web application and your TestCafe test code?
The issue can be reproduced here: https://material.angular.io/components/menu/examples

#### Used method
```
 static getPseudoElementFunction(element:string):ClientFunction {
        return ClientFunction(() => {
            const htmlElement = <HTMLElement>document.querySelector(element);
            return window.getComputedStyle(htmlElement, ':after');
        }, {
            dependencies: {element}
        });
    }
```

#### TestCafe code
```
 fixture`Gets style property of ::after element`
    .page(`https://material.angular.io/components/menu/examples`);
test('Should gets border style solid of ::after element from menu component', async () => {
    await t.click('example-viewer:nth-child(4) .docs-example-viewer-body button');

    const pseudoElementAfterOfMenuBtn = await ToolkitHelper.getPseudoElementFunction('.cdk-overlay-connected-position-bounding-box .mat-menu-panel button')();
    await t.expect(pseudoElementAfterOfMenuBtn.borderStyle).eql('solid');
});
```

#### Screenshots:
Firefox result:
![firefoxAfterElement](https://user-images.githubusercontent.com/32637406/107496623-d69d6000-6b91-11eb-887b-596a1477d225.png)

Chrome result:
![chromeAfterElement](https://user-images.githubusercontent.com/32637406/107496651-dd2bd780-6b91-11eb-90b9-1b5847ecba33.png)
 
### Your Environment details:
 
* testcafe version:                   1.8.2
* node.js version:                    v10.16.0
* browser name and version: Firefox 85.0
* platform and version:          Window 7 (it does not work on Window 10 too)

**Comment by Nikolaj1010** [comment]
Hello, I updated the version of TestCafe to 1.10.1 but the issue is still reproducible. 
![LastestTestcafe](https://user-images.githubusercontent.com/32637406/107613740-3145c300-6c49-11eb-9eae-3fe340e8dade.png)

**Comment by AlexanderMoiseev** [comment]
Hello,

Thank you for bringing this to our attention. However, TestCafe behavior is correct. The Firefox browser indeed returns an empty value for your element's borderStyle property. You can check this with the console debugger.

![image](https://user-images.githubusercontent.com/1498953/107748846-ba80f680-6d2a-11eb-885b-044355821683.png)

**Comment by vizdatom** [comment]
Hi,
I experienced the same issue on Firefox and Safari. The actual problem is in the way Firefox and newly Safari (from version 15.5) exposes CSS properties.
In Blink (Chrome and Edge, etc.) `window.getComputedStyle` returns a `CSSStyleDeclaration` instance. However, Firefox and Safari gives `CSS2Properties`, which inherits from `CSSStyleDeclaration`.
So to get this solve, we have to retrieve `CSSStyleDeclaration` from `CSS2Properties` by using Object.getPrototypeOf(), e.g.
```
const computedStyles = window.getComputedStyle(htmlElement, pseudoElement);
const result = {};
Object.getOwnPropertyNames(Object.getPrototypeOf(computedStyles)).forEach((key) => {
    result[key] = computedStyles[key];
});
return Object.assign(result, computedStyles);
```
Unfortunately, the solution above does not work well in Chrome, so you need to add `return Object.assign(result, computedStyles);` and it'll work in all browsers.

**Comment by Aleksey28** [comment]
Hi @vizdatom,

Thank you for your research. You are right. It resolves the issue. However, the example from the issue doesn't work anymore, because the pseudo-element is no longer there. By the way, I created my own example locally and it works with your solution as expected.
