### ISSUE TITLE
Unable to upload files

### ISSUE THREAD

**Issue by mariusuncrop** [DevExpress/testcafe#5948]
### What is your Test Scenario?
Upload files to web app
 
### What is the Current behavior?
File is not uploaded. When clicking on the submit button, the upload request fails because there is no file selected (**same behavior as clicking without using setFilesToUpload method**)
 
### What is the Expected behavior?
Successfully file upload
 
### Notes
The problem seems to be app specific since I was able to successfully test files uploads on another web apps. Am I missing something? Is is something wrong in my script? Thanks

### What is your web application and your TestCafe test code?
Unfortunately I cannot provide access to the app
 

The page looks like this:

```<div class="well">
   <div class="form-horizontal">
      <fieldset>
         <legend>Uploaded Files</legend>
         <div class="form-group ">
            <label class="col-lg-2 control-label">LE ID<span class="fa fa-asterisk required"></span></label>
            <div class="col-lg-10">
               <div class="">
                  <div class="Select is-searchable Select--single">
                     <div class="Select-control">
                        <div class="Select-multi-value-wrapper" id="react-select-2--value">
                           <div class="Select-placeholder">Select LE ID...</div>
                           <div class="Select-input" style="display: inline-block;">
                              <input aria-activedescendant="react-select-2--value" aria-expanded="false" aria-haspopup="false" aria-owns="" role="combobox" value="" style="box-sizing: content-box; width: 5px;">
                              <div style="position: absolute; top: 0px; left: 0px; visibility: hidden; height: 0px; overflow: scroll; white-space: pre; font-size: 14px; font-family: &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: 400; font-style: normal; letter-spacing: normal; text-transform: none;"></div>
                           </div>
                        </div>
                        <span class="Select-arrow-zone"><span class="Select-arrow"></span></span>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="form-group ">
            <label class="col-lg-2 control-label">EE ID</label>
            <div class="col-lg-10">
               <div class="">
                  <div class="Select is-searchable Select--single">
                     <div class="Select-control">
                        <div class="Select-multi-value-wrapper" id="react-select-3--value">
                           <div class="Select-placeholder">Select EE ID...</div>
                           <div class="Select-input" style="display: inline-block;">
                              <input aria-activedescendant="react-select-3--value" aria-expanded="false" aria-haspopup="false" aria-owns="" role="combobox" value="" style="box-sizing: content-box; width: 5px;">
                              <div style="position: absolute; top: 0px; left: 0px; visibility: hidden; height: 0px; overflow: scroll; white-space: pre; font-size: 14px; font-family: &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: 400; font-style: normal; letter-spacing: normal; text-transform: none;"></div>
                           </div>
                        </div>
                        <span class="Select-arrow-zone"><span class="Select-arrow"></span></span>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="form-group">
            <label class="col-lg-2 control-label">File<span class="fa fa-asterisk required"></span></label>
            <div class="col-lg-10"><input id="file" type="file" disabled="" class="form-control"></div>
         </div>
         <div class="form-group  ">
            <label class="col-lg-2 control-label">Comment</label>
            <div class="col-lg-10"><i class="form-text text-muted"></i><input type="text" class="form-control" placeholder="Comment..." value=""></div>
         </div>
         <div class="form-group">
            <div class="col-lg-10 col-lg-offset-2"><a href="/payroll/uploaded-files"><button class="btn btn-default margin-right-5">Cancel</button></a><button type="submit" class="btn btn-primary">Submit</button></div>
         </div>
      </fieldset>
   </div>
</div>
```

### Steps to Reproduce:
1. Create a simple test that goes to the page and uploads a new file:
```test ('Check uploaded files', async t => {
    await t
        .navigateTo(url)
        .click(Selector('.Select-arrow-zone').nth(0))
        .click(Selector('.Select-menu[role=listbox] [role=option]').nth(0))    
        .setFilesToUpload(Selector('fieldset input').withAttribute("type", "file"), [
            'C:/Users/MariusUncrop/Downloads/test.txt'
        ])
        .click(Selector('button.btn-primary'))
});
```
2. Run test

### Your Environment details:
 
* testcafe version:                   tried with different versions: 0.9.4, 1.10.0
* node.js version:                    v14.15.1
* command-line arguments:  npx testcafe chrome -c 1
* browser name and version: Chrome, Firefox, Edge
* platform and version:          Windows 10

**Comment by Farfurix** [comment]
@mariusuncrop 

Hello,

This information is not sufficient to reproduce the steps of your test scenario. Could you please create a simple application that contains your form uploading logic? We will examine your application on our side and check for a suitable solution.

**Comment by mariusuncrop** [comment]
Not sure if this is relevant, but I can see some difference on the request sent when testing manually and testing through testcafe

manually testing: 
![image](https://user-images.githubusercontent.com/28760204/107743102-f57a2e80-6d18-11eb-8fda-811a6824eb80.png)

testcafe test:
![image](https://user-images.githubusercontent.com/28760204/107743151-0b87ef00-6d19-11eb-9750-9998ddf32325.png)

**Comment by Farfurix** [comment]
@mariusuncrop 

Hello,

We need to reproduce your case on our side to determine the cause of this issue. Please share a [complete example](https://github.com/DevExpress/testcafe/issues/5948#issuecomment-778037862) with us.

**Comment by danekszy** [comment]
So our frontend code - apart from having file input field - uploads the file via our ajax helper `upload` ...
We select data from the input in this way:
```javascript
const fileData = new FormData();
fileData.append('file', document.getElementById('file').files[0]);
upload({ params: { ... }, body: fileData });
```
console.logging `document.getElementById('file').files[0]` shows that the file uses different API for testcafe & real-life browser. Browser expects File object, while testcafe (hammerhead?) supplies some object that tries to mimic the API surface of the browser filepicker.
We could try & work around this issue, but we don't want to have code in prod that's only applicable to one of our testing tools.
Is this sufficient for you to debug the issue?

**Comment by Farfurix** [comment]
@danekszy 

Hello,

Yes, we have a wrapper for `FileList` and it could be the cause of false condition results (for example: `if (file instanceof File)`) in your custom upload logic. We are waiting for a reproducible example from @mariusuncrop. If you have another case, create a separate bug report using [our template](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=&template=bug-report.md).
