### ISSUE TITLE
Error: Cannot find module '@babel/runtime/helpers/asyncToGenerator'

### ISSUE THREAD

**Issue by ZebraFlesh** [DevExpress/testcafe#5950]
### What is your Test Scenario?
Simple test that browser renders content and interacts with page:
```js
import boilerplatePage from '../page_objects/boilerplate';

fixture('Boilerplate').page(process.env.TEST_BASE_URL);

test('Static Content Loads', async (t) => {
  await t.expect(boilerplatePage.title.visible).ok();
  await t.expect(boilerplatePage.clickCount.textContent).contains('0');
  await boilerplatePage.clickPrimaryButton();
  await t.expect(boilerplatePage.clickCount.textContent).contains('1');
  await t.expect(boilerplatePage.cdnImage.visible).ok();
});
```
 
### What is the Current behavior?
Using TestCafe 1.10.0 and 1.10.1, I receive the error `Cannot find module '@babel/runtime/helpers/asyncToGenerator'` and the TestCafe run aborts with an exit code of 1. Downgrading to 1.9.2 resolves the issue.
 
### What is the Expected behavior?
Browser is launched and tests run.
 
### Your Environment details:
 
* testcafe version:                   1.10.1
* node.js version:                    12.20.2
* command-line arguments:  `TEST_BASE_URL=https://<my private url> npx testcafe`
* browser name and version: Chrome 88
* platform and version:           macOS 11.2.1
* other:                                     npm version = 6.14.11; Downgrading to testcafe 1.9.2 resolves the issue.

**Comment by AlexanderMoiseev** [comment]
Hello,

We could not reproduce the issue, but the problem may be related to incorrectly installed dependencies. Try to clean the npm cache ( npm cache clean ), delete your project’s ‘package.lock’ file, and run ‘npm install’ again. If the problem still persists, please send us an example project.

**Comment by ZebraFlesh** [comment]
Thanks, that fixed it.
