### ISSUE TITLE
SurveyJS drag drop issue

### ISSUE THREAD

**Issue by dmitrykurmanov** [DevExpress/testcafe#5954]
steps to reproduce:

1. git clone https://github.com/surveyjs/survey-library.git
2.  npm i
3. comment `click("body")` [hack](https://github.com/surveyjs/survey-library/blob/df12538214092a7153ff54e69deae9b5ffe67392/testCafe/questions/ranking.js#L218)
4. run the test: `testcafe chrome testCafe/questions/ranking.js --selector-timeout 1500 --reporter minimal`

here the branch for reproduce: https://github.com/surveyjs/survey-library/tree/testcafe5954

**Comment by miherlosev** [comment]
> here the branch for reproduce: https://github.com/surveyjs/survey-library/tree/testcafe5954

At present, there is no such branch in the repository. Please update the description.
