### ISSUE TITLE
takeScreenshot with fullpage: true is not working as expected

### ISSUE THREAD

**Issue by mihaisorintoma** [DevExpress/testcafe#5961]
### What is your Test Scenario?

I want to create a screenshot of the entire page, thus I use .takeScreenshot({fullPage: true})
 
### What is the Current behavior?

The screenshot generated has a scrollbar. The footer is not entirely visible.
 
### What is the Expected behavior?

The screenshot generated contains the whole page, without any scroll.
 
### What is your web application and your TestCafe test code?

https://advancedinstaller.com/blog/page-1.html

```
import {Selector} from 'testcafe'

fixture `test`
  .page(`https://advancedinstaller.com/blog/page-1.html`)

    test(`test screenshot of blog page}`, async t => {
      await t
        .resizeWindow(768,800)
        .click(Selector('#cookies button'))
        .takeScreenshot({fullPage: true});
    });
```

### Steps to Reproduce:

1. Run the test code above using "testcafe chrome:headless"

 
### Your Environment details:
 
* testcafe version:                    1.11.0
* node.js version:                    v10.15.3
* command-line arguments:   testcafe chrome:headless
* browser name and version:  Chrome 88.0.4324.150
* platform and version:           Windows 10 x64 20H2
* other:                                    None

**Comment by AlexKamaev** [comment]
Thank you for sharing the example. I reproduced the issue. We need time to research it.

**Comment by sharath2106** [comment]
Hi @AlexKamaev I'd like to work on this if this is not fixed. Would also appreciate if you can provide some insights on what might actually have caused this issue (since this is my first contribution in TestCafe).

**Comment by viktoria2506** [comment]
We'd appreciate it if you contribute to the development of the application.
It looks like you should debug screenshot cropping in the [Capturer](https://github.com/DevExpress/testcafe/blob/master/src/screenshots/capturer.js) module.
Try to do this.

**Comment by sharath2106** [comment]
Okay @viktoria2506!

**Comment by Artem-Babich** [comment]
Hello, @avimredis!

This issue is caused by the different behavior between the Chrome and Chrome:headless browsers. We are currently working on this issue and will update this thread once we have any news.

**Comment by avimredis** [comment]
> Hello, @avimredis!
> 
> This issue is caused by the different behavior between the Chrome and Chrome:headless browsers. We are currently working on this issue and will update this thread once we have any news.

@Artem-Babich Thanks for the quick reply!

**Comment by uuRae** [comment]
I am experiencing this as well. Screenshots were full page in the past, but now are cropped. This does occur on Chrome as well as headless Chrome and headless Firefox.

**Comment by avimredis** [comment]
@uuRae the workaround I found is that if you know about a flaky or failing test and you need to see the full page, you can place this right before the failing step and it will take a full screen

await t.takeScreenshot({
                path:     `DESCRIPTIVE-NAME.png`,
                fullPage: true,
            })
            
I think it's specifically a bug with the screenshot on fail, so this works
