### ISSUE TITLE
Roadmap: Interactive Demo Center

### ISSUE THREAD

**Issue by DIRECTcut** [DevExpress/testcafe#5966]
We currently use the [TestCafe Example Page](https://devexpress.github.io/testcafe/example/) in our demos and code snippets for the documentation. 

It is planned to expand this page to a 'Demo Center' that would include multiple pages. Every page in the Center would have a different purpose (for example, a page that simulates a single-page application) and a snippet of TestCafe code that could be used to test that page.

- [x] #6831
- [ ] ...
- [ ] Write more demo pages to cover all TestCafe features

**Comment by miherlosev** [comment]
We decided to not implement it and focus on the TestCafe core features.
