### ISSUE TITLE
Roadmap: Improve Waiting Mechanism for Assertions      

### ISSUE THREAD

**Issue by DIRECTcut** [DevExpress/testcafe#5967]
TestCafe's built-in [waiting mechanism ](https://devexpress.github.io/testcafe/documentation/guides/concepts/built-in-wait-mechanisms.html) is designed to eliminate the need for manual timeouts during assertions.  

It's planned to rethink this mechanism, especially concerning `exists` and `visible` assertions. Such improvement would increase test stability for most users.

**Comment by helen-dikareva** [comment]
Take into account https://github.com/DevExpress/testcafe/issues/1191

**Comment by miherlosev** [comment]
Closed in favor https://github.com/DevExpress/testcafe/issues/1191
