### ISSUE TITLE
'typeText' doesn't input whitespaces in fields with type="email" 

### ISSUE THREAD

**Issue by mihaisorintoma** [DevExpress/testcafe#5968]
### What is your Test Scenario?

I am trying to input spaces into a field of type="email" in order to check its validation.
 
### What is the Current behavior?

The spaces given in the input field are simply ignored (not typed).
e.g. if I have 'string string' the result will be 'stringstring'
 
### What is the Expected behavior?

The spaces provided in the input field are taken into consideration and typed into the field.
e.g. if I have 'string string', I expect the result to be 'string string' in the field
 
### What is your web application and your TestCafe test code?
I am using https://account.advancedinstaller.com/#/login.

The test code is the following:

```
const { Selector } = require("testcafe");

fixture `Test`

test.page(`https://account.advancedinstaller.com/#/login`)('My Test', async t => {
  let input = Selector('#email');
  await t
      .typeText(input, 'Peter')
      .typeText(input, ' Parker', { speed: 0.1 });
});
```
**Note:** you can ignore the speed setting as it doesn't affect the outcome of the test; it was left there because it's the example provided at the bottom of this page: https://devexpress.github.io/testcafe/documentation/reference/test-api/testcontroller/typetext.html

I have also tried the following code as a workaround for this issue by using the .pressKey method but the outcome was the same (the space key was simply ignored):

```
const { Selector } = require("testcafe");

fixture `Test`

test.page(`https://account.advancedinstaller.com`)
  (`Login Page`, async t => {
    await t
      .click(Selector('#email'))
      .pressKey('s t r i n g space s t r i n g')
});
```
**Note2:** On a field with type="text", as the one in your example from the typeText method (link above), everything works fine.
**Note3:** I've also tried to input using  '.typeText(Selector('#email'), 'string/ string')' but also didn't work.

### Steps to Reproduce:

Simply run the tests above using 'testcafe chrome test.js'
 
### Your Environment details:
 
* testcafe version:                   1.11.0
* node.js version:                    v10.15.3
* command-line arguments:  testcafe chrome test.js
* browser name and version: Chrome 88.0.4324.150
* platform and version:          Windows 10 x64 Version 20H2
* other:                                   N/A

**Comment by SergeyShurygin** [comment]
Thank you for sharing the issue. I've reproduced it and this behavior looks like a bug.
