### ISSUE TITLE
Add more concurrency details to the documentation

### ISSUE THREAD

**Issue by AcademyOfF** [DevExpress/testcafe#5971]
I received a reply [here](https://github.com/DevExpress/testcafe/issues/5686#issuecomment-780739986) regarding how concurrency works:

> You can find the information about work distribution in concurrency mode in the [documentation](https://devexpress.github.io/testcafe/documentation/reference/configuration-file.html#concurrency): "Tests are run concurrently against this pool, that is, each test is run in the first free instance." ... really long tests may result in one of the instances being idle

I'd like more clarification: Will one of the instances be idle only at the end of the test suite when there are `n` tests left, but `> n` instances? Or, can that happen in other situations?

What does it put in the pool and when? e.g., Does add each test in the whole suite upfront? Each test in a fixture, then move on to the next figure when it's depleted?

**Comment by felis2803** [comment]
TestCafe will open the number of instances you specified. Tests are not pre-allocated across instances, but will be provided to each instance as they are released (test execution).
Regarding the stopping: no test will delay the execution of tests in other instances, but all instances can be closed only after the entire pool has been executed.
Tests from different files and fixtures will run in the same way as the tests inside the same fixture, if the fixtures do not have hooks. If a fixture has hooks, all instances will wait for the fixture to be completed.
You can learn more about the technical side of that issue in this [conversation](https://github.com/DevExpress/testcafe/issues/3897).

**Comment by felis2803** [comment]
Also, we have recorded a task to update the documentation in accordance with your request: [https://github.com/DevExpress/testcafe/issues/3951#issuecomment-781224586](https://github.com/DevExpress/testcafe/issues/3951#issuecomment-781224586).

**Comment by AcademyOfF** [comment]
thank you for your reply. I want to confirm I understand the answer to this question: "Does it add each test in the whole suite upfront? Each test in a fixture, then move on to the next figure when it's depleted?" Let me ask it a different way:

Imagine you have two fixtures. Each has two tests. You run your suite with `-c 3`. There are no hooks involved.

When I **start** testcafe, will all 3 instances be executing tests, or only 2?

Thanks again!

**Comment by felis2803** [comment]
All three instances will run tests. You can run this code to verify this as follows:
```js
import { Selector } from 'testcafe';

fixture`Fixture 1`
    .page`http://devexpress.github.io/testcafe/example/`;

test('Test 1.1', async t => {
    await t.typeText('#developer-name', 'test 1.1').wait(1000);
});

test('Test 1.2', async t => {
    await t.typeText('#developer-name', 'test 1.2').wait(5000);
});

fixture`Fixture 2`
    .page`https://google.com`;

test('Test 2.1', async t => {
    await t.typeText(Selector('form input').nth(3), 'test 2.1').wait(5000);
});

test('Test 2.2', async t => {
    await t.typeText(Selector('form input').nth(3), 'test 2.2').wait(4000);
});
```
