### ISSUE TITLE
Describe the treatment of overlapping DOM elements

### ISSUE THREAD

**Issue by titerman** [DevExpress/testcafe#5975]
Add the description to the [Built-In Wait Mechanisms](https://devexpress.github.io/testcafe/documentation/guides/concepts/built-in-wait-mechanisms.html#wait-mechanism-for-actions) page

**Comment by helen-dikareva** [comment]
https://stackoverflow.com/questions/66820142/selector-timeout-speeding-up-the-test

**Comment by titerman** [comment]
https://github.com/DevExpress/testcafe/issues/5975
