### ISSUE TITLE
Not able to run tests on Safari under CircleCi 

### ISSUE THREAD

**Issue by milan-easykad** [DevExpress/testcafe#5977]
### What is your Test Scenario?

 Running tests on CircleCI using Safari as a browser 

### What is the Current behavior?

 
![image](https://user-images.githubusercontent.com/68648172/108571384-5e146d00-7310-11eb-9586-75e1799e45c2.png)

### What is the Expected behavior?

Execute tests on CircleCi on Safari browser 

### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
    "reporter": [
        {
            "name": "spec"
        },
        {
            "name": "xunit",
            "output": "reports/testcafe/report.xml"
        }
    ],
    "screenshots": {
        "takeOnFails": true,
        "path": "artifacts/screenshots"
    },
    "browserInitTimeout": 180000
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
config.yml file: 
![image](https://user-images.githubusercontent.com/68648172/108571943-82bd1480-7311-11eb-8156-fc614d202908.png)

</details>

### Steps to Reproduce:

1. execute test on CircleCi on macOS
 
### Your Environment details:
 
* testcafe version: 1.11.0                  
* node.js version:  12.10.0             
* command-line arguments:  npx testcafe safari ./tests/demo/*.spec.js --skip-js-errors --env=dev 
* browser name and version: Safari 
* platform and version: macOS 10.14          
* other:

**Comment by Farfurix** [comment]
@milan-easykad 

Hello,

This issue doesn't seem to be related to [SIP on macOS](https://circleci.com/docs/2.0/testing-macos/#supported-xcode-and-macos-versions), but I recommend you use
```json
macos:
    xcode: 11.7.0
```
in your configuration file. If this doesn't help, please share a minimal configuration file so we can reproduce the "Unable to establish one or more of the specified browser connections" error.

This link might also be helpful: [use remote mode](https://stackoverflow.com/a/63355065/10448174).
