### ISSUE TITLE
Selector cannot implicitly resolve the test run in context of which it should be executed. If you need to call       Selector from the Node.js API callback, pass the test controller manually via Selector's `.with({ boundTestRun:           t })` method first. Note that you cannot execute Selector outside the test code.

### ISSUE THREAD

**Issue by umairrizwan** [DevExpress/testcafe#5980]
I have 3 files with the following code:
login.ts
Navbar.ts
dashboard.ts
-------------------------------------------------------------------------------------------------
import {Selector,t} from 'testcafe';

class Dashboard
{
    public dashboardTitle=Selector('.page-title').innerText;
    
    constructor()
    {
        this.dashboardTitle;
    }
}

export default Dashboard

---------------------------------------------------------------------------------------------

import {Selector,t} from 'testcafe'

class Navigation{

    usernameTxtBox = Selector('#txtUsername');
    paswrodTxtBox = Selector('#txtPassword');
    loginButton = Selector('#btnLogin');
      
      async UserLogin(username:string, password:string) {
        
         await t
        .click(this.usernameTxtBox).pressKey('ctrl+a delete')
        .click(this.paswrodTxtBox).pressKey('ctrl+a delete')
        .typeText(this.usernameTxtBox,username)
        .typeText(this.paswrodTxtBox,password)
        .click(this.loginButton);
        
    }

 }

export default Navigation

------------------------------------------------------------------------------------------------------

import {Selector} from 'testcafe'
import Navigation from '../Navbar'
import Dashboard from '../pages/dashboard'

const navObj = new Navigation();
const dashObj=new Dashboard();

fixture('To verify the login functionality')
.page('https://orangehrm-demo-6x.orangehrmlive.com/auth/login');

test('User login in the application with proper credentials', async t =>{
      
    await navObj.UserLogin('admin','admin123');   
    await t.expect(dashObj.dashboardTitle).contains('Dashboard'); 
    
});
----------------------------------------------------------------------------------------------------------

**When I am executing login.ts file I am getting the following error:

1) Selector cannot implicitly resolve the test run in context of which it should be executed. If you need to call
      Selector from the Node.js API callback, pass the test controller manually via Selector's `.with({ boundTestRun:    
      t })` method first. Note that you cannot execute Selector outside the test code.**

**Comment by AlexSkorkin** [comment]
You can't use DOM Node state properties in this manner. Refer to the [DOMNodeState Object](https://devexpress.github.io/testcafe/documentation/reference/test-api/domnodestate.html) topic to learn more.

As a workaround, you can pass the TestController object to the constructor of the Dashboard class. For example:

```ts
constructor(t)
{
this.dashboardTitle;
}

```

Your test case will look as follows:

```ts
test('User login in the application with proper credentials', async t =>{

const navObj = new Navigation();
const dashObj=new Dashboard(t);

await navObj.UserLogin('admin','admin123');
await t.expect(dashObj.dashboardTitle).contains('Dashboard');
});

```

P.S. Please ask any TestCafe related questions on StackOverflow ([https://stackoverflow.com/questions/ask?tags=testcafe](https://stackoverflow.com/questions/ask?tags=testcafe)). This is an amazing platform for users to ask and answer questions. We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe/#contributing)).
