### ISSUE TITLE
Mouse-Event in React application

### ISSUE THREAD

**Issue by becciwatson** [DevExpress/testcafe#5982]
### What is your Test Scenario?
In a javascript react.js web application (not React Native) test movement using mouseup, mouse down, mousemove

### What are you suggesting?
We need to drag and drop as equivalent to what is available in Cypress called trigger for Mouse-Event in React application (https://docs.cypress.io/api/commands/trigger.html#Mouse-Events

### What alternatives have you considered?
Bad non-ui alternative, using API
We have considered the t-drag method, but this does not provide the granularity required
(https://devexpress.github.io/testcafe/documentation/reference/test-api/testcontroller/drag.html)

### Additional context
I am prepared to pay a Senior Javascript Developer to get this done immediately - If interested, email your resume to Becci @ BecciWatson.com.au

**Comment by dmcgill50** [comment]
Did these options not serve your purpose? https://devexpress.github.io/testcafe/documentation/reference/test-api/testcontroller/drag.html

**Comment by SergeyShurygin** [comment]
We agree that individual interactivity actions make sense and we already have the corresponding issue ([https://github.com/DevExpress/testcafe/issues/3750](https://github.com/DevExpress/testcafe/issues/3750)). Could you please share you requirements so that we can take them into account? What use cases can't be covered with the drag action mentioned above?

**Comment by becciwatson** [comment]
Hi Sergey, here's some requirements
**1st Requirment: Drag and drop to expanded container**
1.	click onto the draggable element in container 1 and hold
2.	move the element to container 2
3.	release element
4.	the element should be under container 2

**2nd Requirement: Drag and drop to collapsed container**
1.	click onto the draggable element in container 1 and hold
2.	move the element to container 2
3.	wait until the element is expanded
4.	release element
5.	the element should be under container 2

The technology stack we are using: 
•	react
•	trello-smooth-dnd

**3rd Requirement: Mouse Functions to be Made are:**
1.	mousedown
2.	mousemove
3.	mouseup

**4th Requirement: Index value and mouse coordinates**
•	functions should have a possibility to pass options with a button index value and  clientX, clientY mouse coordinates
.new_function('mousemove', {
        button: BUTTON_INDEX,
        clientX: coordsDrop.x + xoffset,
        clientY: coordsDrop.y + 200,

  })
•	working example from cypress has steps:
1.	find droppable element and calculate element coordinates using getBoundingClientRect()
2.	find draggable element and calculate element coordinates using getBoundingClientRect()
3.	Click on a draggable element using 'mousedown' with options: element index, clientX, clientY
4.	move a draggable element to simulate click on hold using 'mousemove' with options: element index, clientX, clientY
5.	move a draggable element on droppable element location using 'mousemove' with options: element index, clientX, clientY
6.	release element on droppable element location using 'mouseup' with options: element index, clientX, clientY

**Comment by SergeyShurygin** [comment]
Thank you for your detailed description.

**Comment by miherlosev** [comment]
Closed in favor https://github.com/DevExpress/testcafe/issues/6039.
