### ISSUE TITLE
 Switch Between Multiple Environment Configuration Files

### ISSUE THREAD

**Issue by becciwatson** [DevExpress/testcafe#5983]
### What is your Test Scenario?
 snytax that automates the ability to switch between multiple environment configuration files, so we can easily move between Dev-Test-Prod.

### What are you suggesting?
Environment Variables specified with JSON like this: https://docs.cypress.io/api/plugins/configuration-api.html#Switch-between-multiple-configuration-files 

### What alternatives have you considered?
CypressIO

### Additional context
I will pay a Senior Javascript Engineer to do this freelancing for immediate start.  Please email your CV to becci @ becciwatson.com.au or skype me becciwatson of Sydney, Australia.

Scope This job is to:
a) TDD write the unit tests; and
b) write the features in javascript to comply with repo coding standards; and
c) test them to be fully functioning; and
d) write the documentation in English for users: and
e) commit them to TestCafe open source github repo; and
f) follow up to have the pull request accepted into main repo (not forked); and
g) I will use them and test they work, you fix any bugs accordingly.

**Comment by aleks-pro** [comment]
Hello @becciwatson ,

Thank you for the feedback.
Configuration file management in TestCafe requires improvement. There is a corresponding issue regarding this problem: https://github.com/DevExpress/testcafe/issues/3428. We will take your inquiry into account when considering approaches to implement it. You can follow this issue to be aware of our progress.
