### ISSUE TITLE
SelectorAPI.getAttribute can return undefined but docs indicate it always returns a string

### ISSUE THREAD

**Issue by kPepis** [DevExpress/testcafe#5984]
### What is your Test Scenario?
Using `SelectorAPI.getAttribute` can return `undefined` for attributes that are not present in the current selector.
 
### What is the Current behavior?
`SelectorAPI.getAttribute`'s  type indicates it returns `Promise<string>`.
 
### What is the Expected behavior?
`SelectorAPI.getAttribute` should return `Promise<string | undefined>`.

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 const mySelector = Selector('a');
 const undefinedAttribute = mySelector.getAttribute('this-does-not-exist');
 const undefinedAttribute.trim(); // method does not exist
```
</details>

**Comment by AlexanderMoiseev** [comment]
Hello,

Thank you for pointing this out. We have reproduced this behavior and will fix it in the context of this thread. Please stay tuned.

**Comment by Farfurix** [comment]
Our `getAttribute`'s returned value (`undefined`) is not consistent with [`Element.getAttribute()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttribute) ([`null`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttribute#non-existing_attributes)). We need to fix it in our source code and type definitions.
