### ISSUE TITLE
There is a button that on Headless gives 

### ISSUE THREAD

**Issue by wolfsblessing** [DevExpress/testcafe#5987]
I'm testing on testing environment with Testcafe and it's all good until I try the same test with ':headless' and then it reaches to a button that doesn't see it and crashes with these reports:

× Online TikTak Public Site Test

   1) A JavaScript error occurred on "https://qa.tiktak.mk/PublicPatient".
      Repeat test actions in the browser and check the console for errors.
      If you see this error, it means that the tested website caused it. You can fix it or disable tracking JavaScript errors in TestCafe. To do the latter, enable the "--skip-js-errors" option.
      If this error does not occur, please write a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      TypeError: Cannot read property 'name' of undefined
          at https://qa.tiktak.mk/_nuxt/d77879ff1298af2e2cab.js:2:435334

The site is: https://qa.tiktak.mk
So to get to the page where headless doesn't work is: 

https://qa.tiktak.mk/  >  УСЛУГА ВО МЕДИЦИНСКА УСТАНОВА  >  Вадење на траен заб  >  закажете термин (button on the right side for that service/section)  >  click any time slot and then at the bottom of the page 'потврди' button... then on the Patient (info) page click the 'регистрирај се' to open up the big form, and I start filling the form. At the end of the form, after the checkbox at the bottom of the page is checked, the 'регистрирај се' button gets enabled... and this is the button that should be clicked makes the problems when on Headless testing, and gives the above written error. 

It's the latest Testcafe and Chrome

### What is your Test Scenario?

 https://qa.tiktak.mk/  >  УСЛУГА ВО МЕДИЦИНСКА УСТАНОВА  >  Вадење на траен заб  >  закажете термин (button on the right side for that service/section)  >  click any time slot and then at the bottom of the page 'потврди' button... then on the Patient (info) page click the 'регистрирај се' to open up the big form, and I start filling the form. At the end of the form, after the checkbox at the bottom of the page is checked, the 'регистрирај се' button gets enabled... and this is the button that should be clicked

### What is the Current behavior?

      JavaScript error details:
      TypeError: Cannot read property 'name' of undefined
          at https://qa.tiktak.mk/_nuxt/d77879ff1298af2e2cab.js:2:435334
 
### What is the Expected behavior?

To be clicked so can proceed on different page
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>
https://qa.tiktak.mk

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>
 https://qa.tiktak.mk/  >  УСЛУГА ВО МЕДИЦИНСКА УСТАНОВА  >  Вадење на траен заб  >  закажете термин (button on the right side for that service/section)  >  click any time slot and then at the bottom of the page 'потврди' button... then on the Patient (info) page click the 'регистрирај се' to open up the big form, and I start filling the form. At the end of the form, after the checkbox at the bottom of the page is checked, the 'регистрирај се' button gets enabled... and this is the button that should be clicked

 
```js
 
import { Selector, t, ClientFunction } from 'testcafe';
import GlobalVariables from '../variables/variablesNew';

const globalVariables = new GlobalVariables();

export default class GlobalFunctions 
{
  constructor() 
  {
  }//End of Constructor

  //New User Form filling
    async TestFormAutoFill()
    {
      await t
        .wait(250)
        .click(await globalVariables.RegisterBtn.withText("регистрирај се"))
        .wait(250)
        .typeText(await globalVariables.NameFieldElement, globalVariables.MyName)
        .typeText(await globalVariables.LastNameFieldElement, globalVariables.MyLastName);
      
      await t
      // .debug()
        .click(await globalVariables.GenderElement)
        .click(await globalVariables.MaleElement)
        .click(await globalVariables.CalendarElement);

      await t
        .click(await globalVariables.DayCalendarElement)
        .typeText(await globalVariables.IDElement, globalVariables.ID)
        .click(await globalVariables.CountryDropDownElement);
      
      await t
        .click(await globalVariables.CountryElement.withText(globalVariables.CountryToSelect))
        .click(await globalVariables.CityToClick)
        .click(await globalVariables.CityElement.withText(globalVariables.CityToChose));

      await t
        .typeText(await globalVariables.PhoneElement, globalVariables.MyPhone)
        .typeText(await globalVariables.EmailElement, globalVariables.MyEmail);
        // .debug()

      await t
        .click(await Selector("input#accept-condition"))
        .wait(3000)
        .click(await Selector(".patient-registration"));
        // .click(await globalVariables.RegisterBtn.withText("регистрирај се")) //This is the same button as the one above this line i was trying to select and click and makes problems
        .click(await Selector(globalVariables.FinalRegisterBtn));
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'TikTakNewUser'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.19.0
4 verbose run-script [ 'preTikTakNewUser', 'TikTakNewUser', 'postTikTakNewUser' ]
5 info lifecycle @~preTikTakNewUser: @
6 info lifecycle @~TikTakNewUser: @
7 verbose lifecycle @~TikTakNewUser: unsafe-perm in lifecycle true
8 verbose lifecycle @~TikTakNewUser: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Bekim Kurtishi\Desktop\TestCafe\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\nodejs\;C:\Users\Bekim Kurtishi\AppData\Local\Microsoft\WindowsApps;C:\Users\Bekim Kurtishi\.dotnet\tools;C:\Users\Bekim Kurtishi\AppData\Local\GitHubDesktop\bin;C:\Users\Bekim Kurtishi\AppData\Local\Microsoft\WindowsApps;C:\Web Drivers;C:\Users\Bekim Kurtishi\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Bekim Kurtishi\.dotnet\tools;C:\Users\Bekim Kurtishi\AppData\Roaming\npm
9 verbose lifecycle @~TikTakNewUser: CWD: C:\Users\Bekim Kurtishi\Desktop\TestCafe
10 silly lifecycle @~TikTakNewUser: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'testcafe chrome:headless tests/Session2/AllTikTakTest/NewPublic/TikTakNewUser.js screenshots tests/Session2/screenshots -- screenshots-on-fails'
10 silly lifecycle ]
11 silly lifecycle @~TikTakNewUser: Returned: code: 1  signal: null
12 info lifecycle @~TikTakNewUser: Failed to exec TikTakNewUser script
13 verbose stack Error: @ TikTakNewUser: `testcafe chrome:headless tests/Session2/AllTikTakTest/NewPublic/TikTakNewUser.js screenshots tests/Session2/screenshots -- screenshots-on-fails`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid @
15 verbose cwd C:\Users\Bekim Kurtishi\Desktop\TestCafe
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "TikTakNewUser"
18 verbose node v12.19.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error @ TikTakNewUser: `testcafe chrome:headless tests/Session2/AllTikTakTest/NewPublic/TikTakNewUser.js screenshots tests/Session2/screenshots -- screenshots-on-fails`
22 error Exit status 1
23 error Failed at the @ TikTakNewUser script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by Farfurix** [comment]
@wolfsblessing 

Hello,

I followed the steps you described and got the same error without using TestCafe:
![Capture](https://user-images.githubusercontent.com/30019338/109275095-53346d80-7825-11eb-9c43-a558c328b12a.PNG)

This error should be fixed on the website side. You can avoid this error by using the [`--skip-js-errors`](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#-e---skip-js-errors) option.

Note that you don't need to add the `await` keyword before selectors in your test actions (`.click(await Selector("input#accept-condition"))`). Please refer to our [Built-In Wait Mechanisms](https://devexpress.github.io/testcafe/documentation/guides/concepts/built-in-wait-mechanisms.html#wait-mechanism-for-actions) article.

**Comment by wolfsblessing** [comment]
Thank you for  the reply, I really appreciate it.
It is what you say too, and now we see that the problem occurs when a City has not been selected... and that's when the chosen city is down bellow the dropdown list. So, having said that, when I don't use ':headless', Testcafe scrolls down the drop down list and it's fine, but, when I use the ':headless' mode, then it doesn't scroll and it just skips. So, in order to work for me in ':headless' mode, I have to chose a city that is on top of the list and the app doesn't need to scroll, and then, all is fine.
