### ISSUE TITLE
Unable to select the selector due to case sensitivity of withText method 

### ISSUE THREAD

**Issue by rita740** [DevExpress/testcafe#5989]
### What is your Test Scenario
hi, I am trying to select the item from the dropdown menu
 
### What is the Current behavior?
selector cannot be selected due to case sensitivity of withText method

### What is the Expected behavior?
  should be able to select the selector even though letters represented in the dropdown is in different case format.
 
### What is your web application and your TestCafe test code?
desktop web application
 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
//page.js
export class AccountMenu{
  constructor () {
    this.accountLogo = Selector('md-icon').withAttribute('ng-click','triggerCrmSearch()');
    this.accountHeaderSearchField = Selector('input').withAttribute('id','crmsearch');
    this.virtualRepeatScroller = Selector('div').withAttribute('class','md-virtual-repeat-scroller');
    this.autoCompleteAccInfo = Selector('ul li').find('md-autocomplete-parent-scope div').withAttribute('ng-class','statusClass(item.accountStatusName)').child('span');   
  }
  async accountSearch (destinationAccNum, destinationAccName) {
    await t.click(this.accountLogo);
    await t.click(this.accountHeaderSearchField)
    await t.typeText(this.accountHeaderSearchField,destinationAccNum, { paste:true, replace:true })
  
    await t.expect(this.virtualRepeatScroller.visible).ok({ timeout:2000 });
    await t.click(this.autoCompleteAccInfo.withText(destinationAccName))
  }
}
//mainpage.js
await accountMenu.accountSearch(destinationAccNum,destinationAccName);
.
```
</details>
hi, I am trying to to search the destination account using its account number and trying to select by its name, but the name appeared in the drop down is in different case format than name i have passed ,so it could not be selected.
<details>

   1) The specified selector does not match any element in the DOM tree.

       > | Selector('ul li')
         |   .find('md-autocomplete-parent-scope div')
         |   .withAttribute('ng-class', 'statusClass(item.accountStatusName)')
         |   .child('span')
         |   .withText('Fusce Mi Lorem LLP')

I am getting this error coz, the accName i have passed appears like'Fusce Mi Lorem Llp' in the dropdown. what should i do to get my selector right.
</details>

<details>
<summary>Your complete test report:</summary>

**Comment by AlexanderMoiseev** [comment]
Hello, 

This behavior is correct - the ‘withText’ method is indeed case sensitive ([documentation](https://devexpress.github.io/testcafe/documentation/reference/test-api/selector/withtext.html#withtexttext)). To make it case insensitive, you can use the ‘withText’ method that accepts Regexp with [ignore case modifier](https://www.w3schools.com/jsref/jsref_regexp_i.asp) as param
