### ISSUE TITLE
Local storage is cleared on every t.navigateTo in Safari

### ISSUE THREAD

**Issue by Aaronius** [DevExpress/testcafe#5992]
### What is your Test Scenario?

Set a local storage item (e.g., set `foo` to `bar`)..
Use `t.navigateTo` to navigate to another page on the same origin.
Read the local storage item that was previously set.
 
### What is the Current behavior?
The local storage item is null.

 
### What is the Expected behavior?
The local storage item retains its value.

 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

index.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
  <a href="index2.html">Go to page 2</a>
</body>
</html>
```

index2.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>

</body>
</html>
```

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

```js
import { ClientFunction } from "testcafe";

fixture("local storage").page("http://localhost:3000");

const setLocalStorageItem = ClientFunction(() => {
  window.localStorage.setItem("foo", "bar");
});

const getLocalStorageItem = ClientFunction(() => {
  return window.localStorage.getItem("foo");
});

test("should not delete local storage", async t => {
  await setLocalStorageItem();
  const valueOnPage1 = await getLocalStorageItem();
  await t.navigateTo("index2.html");
  const valueOnPage2 = await getLocalStorageItem();
  await t.expect(valueOnPage1).eql(valueOnPage2);
});
```
</details>
<details>
<summary>Your complete test report:</summary>

```
> testcafe-test@0.1.0 test /Users/aahardy/dev/testcafe-test
> testcafe safari

 Running tests in:
 - Safari 14.0.2 / macOS 10.15.7

 local storage
 ✖ should not delete local storage

   1) AssertionError: expected 'bar' to deeply equal null
      
      + expected - actual
      
      -'bar'
      +null
      

      Browser: Safari 14.0.2 / macOS 10.15.7

         25 |test("should not delete local storage", async t => {
         26 |  await setLocalStorageItem();
         27 |  const valueOnPage1 = await getLocalStorageItem();
         28 |  await t.navigateTo("index2.html");
         29 |  const valueOnPage2 = await getLocalStorageItem();
       > 30 |  await t.expect(valueOnPage1).eql(valueOnPage2);
         31 |});

         at <anonymous> (/Users/aahardy/dev/testcafe-test/tests/localStorage.spec.js:30:32)
         at asyncGeneratorStep (/Users/aahardy/dev/testcafe-test/tests/localStorage.spec.js:13:211)
         at _next (/Users/aahardy/dev/testcafe-test/tests/localStorage.spec.js:13:549)
```
</details>

<details>
<summary>Screenshots:</summary>

</details>

### Steps to Reproduce:

Set a local storage item (e.g., set `foo` to `bar`).
Use `t.navigateTo` to navigate to another page on the same origin.
Read the local storage item that was previously set.
Notice the value is null. Local storage was somehow cleared during navigation.
 
### Your Environment details:
 
* testcafe version: 1.11.0                  
* node.js version: 14.15.3                
* command-line arguments: testcafe safari  
* browser name and version: Safari 14.0.1 
* platform and version:  Mac 10.15.7        
* other: Local storage is NOT cleared on Chrome and Firefox

**Comment by kPepis** [comment]
Talk about timing, I'm also experiencing this issue except that my test is accessing `sessionStorage` and that also gets cleared in Safari after calling `t.navigateTo()`, while Firefox and Chrome work correctly.

Environment details:
- testcafe version: 1.11.0
- node.js version: 10.24.0
- command-line arguments: testcafe safari
- browser name and version:  Safari 14.0.3
- platform and version: macOS 10.15.6 (11.2.1)

**Comment by AlexanderMoiseev** [comment]
Hello,
 
Thank you for your input. We have reproduced the problem and need some time to investigate it. Please stay tuned.

**Comment by adenhertog** [comment]
I've got a workaround whilst this is being patched. 

Instead of using `t.navigateTo()` that seems to drop the localstorage, I made a client function:

```typescript
const navigateTo = ClientFunction((url: string) => window.location.href = url)

// ...

await navigateTo(...)
```

This uses the client's javascript to do the navigation instead of the cluster of browserstack/testcafe/selenium that is somehow dropping localstorage just for ios safari.

**Comment by rfalke** [comment]
We also encountered this. We are using `t.click(...)` to load a new page. It looks like `saveToNativeStorages` in https://github.com/DevExpress/testcafe-hammerhead/blob/e4b63a650dfad77b033475de2125fbfad7143f1d/src/client/sandbox/storages/index.ts#L81 isn't called before the new page is loaded and the updated hammerhead storage proxy isn't persisted to the real session storage.

We only see this on Safari (15.0 and 15.2). Sadly we can't easily test old versions to see when this behavior was introduced.

Our workaround which brings this from 100% failing to 100% success rate is:

```
const flushHammerheadStorageProxyToNative = ClientFunction(() => {
  sessionStorage.unwrapProxy().saveToNativeStorage();
});

...
  await flushHammerheadStorageProxyToNative();
  await t.click(button);
```

**Comment by AlexanderMoiseev** [comment]
Hi @rfalke.

Thank you for pointing this out.  Once we have any news, we will post them here. Please stay tuned.

**Comment by andrzej-kodify** [comment]
Still occurs with Safari Version 16.1 (18614.2.9.1.12) on MacOS 13.0.1
