### ISSUE TITLE
Misleading error message when Selector filtering results in an empty set

### ISSUE THREAD

**Issue by JasonRammoray** [DevExpress/testcafe#5995]
### What is your Test Scenario?
* Query some existing elements in a DOM tree using `Selector`
* [Filter](https://devexpress.github.io/testcafe/documentation/reference/test-api/selector/filter.html) that selector by passing a callback always returning `false` and store the resulted selector in a separate variable
* Try clicking on the filtered selector by using the variable from the previous step
 
### What is the Current behavior?
An error message says:
> The specified selector does not match any element in the DOM tree.
 
### What is the Expected behavior?
The error message should be rephrased to reflect the fact that the filtered results are empty. 
Upon the first look, one might think the issue is in the original selector, however, that's not the case because there are plenty of links on the TestCafe's main page.
 
### What is your web application and your TestCafe test code?
<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import {Selector} from 'testcafe';
  
fixture('Demo for filter issue')
.beforeEach(t => t.navigateTo('https://devexpress.github.io/testcafe/'));

test('should provide correct failure message', async t => {
  const links = Selector('a');
  await t.expect(links.exists).ok();
  const filteredLinks = links.filter(() => false);
  await t.click(filteredLinks);
});
```
</details>

<details>
<summary>Your complete test report:</summary>

Running tests in:
 - Chrome 88.0.4324.192 / macOS 10.15.7

 Demo for filter issue
 ✖ should provide correct failure message

   1) The specified selector does not match any element in the DOM tree.
```      
         | Selector('a')
       > |   .filter([function])
```
      Browser: Chrome 88.0.4324.192 / macOS 10.15.7
```
          5 |
          6 |test('should provide correct failure message', async t => {
          7 |  const links = Selector('a');
          8 |  await t.expect(links.exists).ok();
          9 |  const filteredLinks = links.filter(() => false);
       > 10 |  await t.click(filteredLinks);
         11 |});
         12 |
```
         at <anonymous>
      (/Users/vmoskalenko/Projects/test_cafe_filter_issue/test.spec.ts:10:11)
         at fulfilled
      (/Users/vmoskalenko/Projects/test_cafe_filter_issue/test.spec.ts:5:58)

 1/1 failed (15s)
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:  1.11.0
* node.js version: v14.15.5
* command-line arguments:  `npx testcafe chrome test.spec.ts`
* browser name and version: Chrome 88.0.4324.192
* platform and version: macOS 10.15.7

**Comment by SergeyShurygin** [comment]
I agree that the error text seems to be misleading since it says "elements matching the selector are not found" instead of "the filter action returns an empty list". But it is correct for the entire selector chain because there are no elements that match all conditions on the page.

Also, please note that TestCafe's error output contains information about the failed part of the selector chain:
![image](https://user-images.githubusercontent.com/1165734/109637769-4a61d580-7b5e-11eb-8ffe-7f5f515ddacc.png)
The '>' mark shows the place where the error occurs. In this case, it should be clear that no matching elements were found while the filter step of the selector's chain was executed.

Perhaps, the cause of the problem is that this mark is not very noticeable and we should emphasize it somehow.

**Comment by JasonRammoray** [comment]
For the short-term solution, the `>` arrow  could be definitely improved to something more noticeable.
For the long-term approach, though, it'd be great to have a handy message, precisely illustrating the filtering issue.
The aim is to spend as less time as possible when it comes to debugging a test, figuring out the real reason of the error.
At the moment, it might not be immediately obvious and might take a while to realize the filter (s), producing a Selector matching no elements in a DOM, is the actual source of the issue.

**Comment by SergeyShurygin** [comment]
I registered a separate issue (https://github.com/DevExpress/testcafe/issues/6007) to collect all requests on this topic.
