### ISSUE TITLE
TestCafe should synchronize storages between windows

### ISSUE THREAD

**Issue by gabbersepp** [DevExpress/testcafe#5999]
### What is your Test Scenario?
I have two browser instances that share the same localstorage (same url) and want to communicate between them using the `storage` event. 
My usecase: I have built an electron app which leverages multiple windows. They communicate with the electron communication channel. Spectron does not work very good for testing (it doesn't work at all) and so I decided to test the webapp with testcafe. To allow communication between windows I wrote a wrapper around the communication stuff and used the `storage` event to have a similar cimmunication channel as in electron.
 
### What is the Current behavior?
Two windows opened by testcafe can't see the `storage`  event of eacher.

### What is the Expected behavior?
As both windows run under the same url they should share the same localstorage and receive the `storage` event.
 
### What is your web application and your TestCafe test code?
This example contains a small example plus the test code:
https://github.com/gabbersepp/testcafe-issue

### Steps to Reproduce:

1. Checkout the repo
2. `npm install`
3. `npm run serve`
4. `npm test`
 
### Your Environment details:
 
* testcafe version:                   1.11.0
* node.js version:                    v12.18.3
* command-line arguments:  testcafe chrome tests/
* browser name and version: Chrome 88
* platform and version:          Win 10

**Comment by AlexanderMoiseev** [comment]
Hello, Thank you for your input. We have reproduced the problem and need some time to investigate it. Please stay tuned.
For the team: can be reproduced with the following test

import { Selector } from 'testcafe';

fixture `New Fixture`.page `https://mdn.github.io/dom-examples/web-storage/event.html`;

test('New Test', async t => {
  await t
  .setTestSpeed(0.1)
  .openWindow('https://mdn.github.io/dom-examples/web-storage/index.html')
  .click('#image')
  .click(Selector('#image option').withText('Crocodile'))
  .switchToPreviousWindow()
  .expect(Selector('.my-new').textContent).eql('images/crocodile.png');
});

**Comment by rr13k** [comment]
What's going on? That's what I care about

**Comment by AndreyBelym** [comment]
This can be a part of #5291
