### ISSUE TITLE
Unable to Interact with Hover State outside of the Context of iFrame

### ISSUE THREAD

**Issue by aaebrahim** [DevExpress/testcafe#6008]
### Are you requesting a feature or reporting a bug?
Reporting a Bug

### What is your Test Scenario?
Test adding and editing blocks in an inline editor.

### What is the Current behavior?
The hover state which is outside of the context of the iFrame does not appear and is not accessible.

### What is the Expected behavior?
When you hover over content in the iFrame, there should be a hover state you can interact with outside of the iFrame to add and edit new content blocks.

https://d.pr/i/7GyW9a

### How would you reproduce the current behavior (if this is a bug)?
Switch into the iFrame and hover over the header.  Hover state will not show up.

#### Provide the test code and the tested page URL (if applicable)

 
Your website URL (or attach your complete example):
https://mailchimp.com/ 

Create a regular email campaign. Edit the design of the email. This will put you in the editor.

https://mailchimp.com/help/create-a-regular-email-campaign/

Your complete test code (or attach your test files)

```js

async addContentBlock(block) {
    const exampleBlock = Selector("div h1").withText(
      "It's time to design your email"
    );
    const editor = Selector("[class *= 'editorPreview']");
    const plusIcon = Selector("[class *= 'editorPreview'] svg");
    const newBlock = Selector("button div").withText(block);
    await t
      .hover(exampleBlock) // content in the iFrame
      .switchToMainWindow() // switch to interact with the hover state
      .hover(editor)
      .click(plusIcon)
      .click(newBlock);
  }

test("Users can add and edit content blocks within the new editor", async t => {
 
  await t
    .switchToIframe("#fallback")
    .click(campaignChecklist.designEmail)
    .switchToMainWindow()
    .wait(10000)
    .switchToIframe(emailEditor.loadedIframe); // the iFrame in which the content of the inline editor is
 
  await emailEditor.addContentBlock("Heading");
});
```
### Your Environment details:
 
* testcafe version: 1.8.9
* node.js version: 10.16.3
* browser name and version: Chrome Version 88.0.4324.192
* platform and version: macOS Catalina 10.15.7
* other:

**Comment by aaebrahim** [comment]
We are running on an older version because the newer versions are causing other iFrame issues for us that 1.8.9 is not. However,  I updated to v1.12 and ran the test again and am still able to reproduce the issue.

**Comment by Farfurix** [comment]
@aaebrahim 

Hello,

I created a test account but didn't manage to reproduce your test scenario using the information you provided. Could you please share your complete test files (without credentials, I will use my own) that can be run with my MailChimp account so we can reproduce the issue?

**Comment by aaebrahim** [comment]
Hey,

In order to see the page with the issue, you will need to create a new mailchimp account on mailchimp.com - https://d.pr/i/pJ8Z4f .

Here are the steps to reproduce after creating a new account:

1. Go to the campaigns page
<img width="1519" alt="Markup 2021-03-10 at 10 00 50" src="https://user-images.githubusercontent.com/43886782/110649432-95e03900-8187-11eb-9189-ae086ac8d84b.png">

2. Create a campaign 
<img width="1523" alt="Markup 2021-03-10 at 10 02 12" src="https://user-images.githubusercontent.com/43886782/110649551-b4463480-8187-11eb-96ef-fb09e5e5dcb8.png">

3. Select the Email option
<img width="1036" alt="Markup 2021-03-10 at 10 07 03" src="https://user-images.githubusercontent.com/43886782/110650278-67af2900-8188-11eb-99b8-886afa0e5aed.png">

4. Create a Regular Email
5. Select the Design Email button 
![Annotation on 2021-03-10 at 10-08-36](https://user-images.githubusercontent.com/43886782/110650567-a8a73d80-8188-11eb-950a-524a9089b97c.png)

6. Select the new builder
<img width="1002" alt="Markup 2021-03-10 at 10 09 48" src="https://user-images.githubusercontent.com/43886782/110650740-cbd1ed00-8188-11eb-9a72-801a9984a86d.png">

7. You will now be in the new builder where we need to test
<img width="1677" alt="Markup 2021-03-10 at 10 12 05" src="https://user-images.githubusercontent.com/43886782/110651108-22d7c200-8189-11eb-9dab-d67b700877b6.png">

This is where we are having the issue not able to interact with the hover state after hovering on content in the iFrame.

This is the expected behavior: 
![Screen Capture on 2021-03-03 at 10-53-46](https://user-images.githubusercontent.com/43886782/110651251-4569db00-8189-11eb-9485-f291522f6a69.gif)

The hover state is not accessible in TestCafe and causes the tests to fail.

**Comment by Farfurix** [comment]
@aaebrahim 

Hello,

I followed your steps and reproduced the "unable to interact with the editor" issue in Windows 10 and Chrome. Our team will examine this issue but I cannot give you any time estimates.

For the team:
```js
import { Selector } from 'testcafe';

fixture `MailChimp`
    .page `https://us1.admin.mailchimp.com/`;

test('New Test', async t => {
    await t
        .typeText('main .av-text', '**************')
        .typeText('main .av-password', '**************')
        .click(Selector('main button').withText('Log In'))
        .debug()
        .click(Selector('#root a').withText('Campaigns'))
        .switchToIframe('main [title="Campaigns | Mailchimp"]')
        .click(Selector('main button').withText('Create Campaign'))
        .switchToMainWindow()
        .click(Selector('#uniqName_28_0 p').withText('Design and send automated or regular emails to you'))
        .click(Selector('#uniqName_47_31 button').withText('Begin'))
        .switchToIframe('main [title="Campaigns | Mailchimp"]')
        .click(Selector('main button').withText('Design Email'))
        .switchToMainWindow()
        // interact with the email editor
        // .click(Selector('main .wink-icon').nth(7)) // interact with the email editor
        // .click(Selector('main div div div').nth(50).find('div div div section button svg'))
        // .switchToIframe('main [title="Preview"]')
        // .click(Selector('#root h1').withText('It\'s time to design your email'), {
        //     caretPos: 16
        // })
        // .typeText(Selector('#root h1').withText('It\'s time to design your email'), '123', {
        //     caretPos: 16
        // });
});
```

**Comment by jwingo1002** [comment]
Hello @Farfurix is there any update to when this will be fixed? We are blocked with moving forward with our tests.

**Comment by jwingo1002** [comment]
Hello @Farfurix can we get any information about the status of this issue. Are you working on it? Do yall have a solution? Anything that i can take back to my team about the progress? We have been blocked for months now with no information as to the progress.

**Comment by Farfurix** [comment]
Hello,

We are focused on other issues right now. I cannot say exactly when we’ll get back to this.

You can try using t.dispatchEvent to interact with problematic elements. Refer to [this method's draft documentation](https://gist.github.com/AndreyBelym/b9a09481ef4932c3541c837d3ac2c40d).

**Comment by jwingo1002** [comment]
Hello @Farfurix i tried to use the t.dispatchEvent when i switch the focus to inside the iframe and its not clicking. instead it throws an error message: Uncaught object "[object Object]" was thrown. Throw Error instead.

i am able to hover over the element but after that testcafe doesnt interact with that element at all. Can you help with this blocker?

**Comment by Farfurix** [comment]
@jwingo1002 

Hello,

We have no workaround for this issue. I cannot give you any time estimate as to when this issue will be resolved.

**Comment by AlexKamaev** [comment]
Hi everyone,

This issue can be fixed in Chrome in Native Automation mode. Please try using Native Automation mode in the latest TestCafe version to check if it helps.
