### ISSUE TITLE
Update reporters and reporter generator with new decorator and test data

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#601]
- [x] Update reporters with new errors test data 
  - [x] spec
  - [x] list
  - [x] minimal
  - [x] json
  - [x] xunit
- [x] Update `generator-testcafe-reporter` with new decorator and test data

(cloned from #374)

**Comment by inikulin** [comment]
I'll take care of this

**Comment by inikulin** [comment]
To tech writters:

- [ ] Update screenshots for all reporters and publish versions with new screenshots in README to npm.

- [ ] Update README for generator and docs where needed. From the top of my mind you will need to go through the `publish-please` installation steps on project creation. Also reporter project should be now published via `npm run publish-please`

**Comment by inikulin** [comment]
\cc @MargaritaLoseva @VasilyStrelyaev

**Comment by VasilyStrelyaev** [comment]
I'll do it!
