### ISSUE TITLE
Ability to set resizeWindowToFitDevice from command line 

### ISSUE THREAD

**Issue by qualityshepherd** [DevExpress/testcafe#6016]
I'm looking to leverage my existing e2e tests to also test our mobile web implementation. It would be lovely if I could set `resizeWindowToFitDevice` via the command line to change the browser size for _all_ tests in conjunction with a `--fixture-meta` to run a subset of tests. 

The workaround might be to pass a size to each browser... eg. `testcafe "chrome '--window-size=375,812'" tests/mySassyTest.js`... but where's the fun in that :D

**Comment by felis2803** [comment]
Hello @qualityshepherd

Thank you for the idea.
Currently we have plans to implement test hooks at the global level: #4323. I think this feature can be helpful in your use case.
At the moment, you might be able to use chrome's ability to emulate devices: https://devexpress.github.io/testcafe/documentation/guides/concepts/browsers.html#emulate-a-device

**Comment by qualityshepherd** [comment]
#sadface
