### ISSUE TITLE
Medium screen resolution(iPad, iphonexr, iphone11): Unable to resize the window because the specified size exceeds the screen size

### ISSUE THREAD

**Issue by szhux** [DevExpress/testcafe#6019]
I use testcafe 1.12.1-alpha.1

The test suit **works fine** for **iphone8plus or iphone8.**
But **fails** for following: **iPad, iphonexr, iphone11**
I suspect it's because of difference in screen resolutions.

### Steps to Reproduce:
1)
I tried to execute for "iphonexr": {
    "portraitWidth": 414,
    "landscapeWidth": 896,
    "name": "iPhone XR"
  },
2)
dev test -b chrome -d iphonexr
3)
I got this error  1) - Error in fixture.beforeEach hook -
the same for iPad, iphone11 etc

### What is the Current behavior?
I got this error  1) - Error in fixture.beforeEach hook -
      Unable to resize the window because the specified size exceeds the
      screen size. On macOS, a window cannot be larger than the screen.
 
### What is the Expected behavior?
I checked https://github.com/DevExpress/testcafe/issues/2284 and 
and executed in debug mode to get available screen resolutions and got this

![DevTools - 192 168 86 39:55228:wCgsKiAUU*PTbIApccb:https:handshake-web-internal shopifycloud com: 2021-03-05 10-33-33](https://user-images.githubusercontent.com/33559259/110098189-31486700-7da0-11eb-9c2e-5e2d6f9f8d77.jpg)

It looks like I have available screen resolution in my Mac
available width and length > iphonexr width and length

Please correct me if I'm wrong
 
### Your Environment details:
 
* testcafe version:                   testcafe 1.12.1-alpha.1
* node.js version:                    v12.17.0
* command-line arguments:  
* browser name and version: Chrome Version 88.0.4324.192
* platform and version:          MacOS BigSur 11.2.1
* Screens:
![image](https://user-images.githubusercontent.com/33559259/110099089-33f78c00-7da1-11eb-8185-6da9276c1207.png)

**Comment by wentwrong** [comment]
Would you please clarify how you run TestCafe? What is your test code? Without this information, is not clear whether you are using [Chromium Device Emulation](https://devexpress.github.io/testcafe/documentation/guides/concepts/browsers.html#use-chromium-device-emulation) to run tests or just use the [t.resizeWindowToFitDevice](https://devexpress.github.io/testcafe/documentation/reference/test-api/testcontroller/resizewindowtofitdevice.html) method in the `beforeEach` hook.

**Comment by szhux** [comment]
The issue with the t.resizeWindowToFitDevice 


Actually our test works fine for all platforms(including  iPad, iphonexr, iphone11)  when we try to execute them using Chrominum Device Emulation:
testcafe "chrome:emulation:device=iphone X" tests/handshake.com_tests/login.js

But when we try to use t.resizeWindowToFitDevice  we get 
"- Error in fixture.beforeEach hook -
      Unable to resize the window because the specified size exceeds the
      screen size. On macOS, a window cannot be larger than the screen."

the full snippet of usage is 
fixture`Login`
  .page`${env.baseUrl}`
  .beforeEach(async (t) => {
    if (device.name) {
        await t
        **.resizeWindowToFitDevice(device.name, {**
          portraitOrientation: device.portraitOrientation});
    }
  });

**Comment by viktoria2506** [comment]
The height of 896 and the width of 414 (for iPhone XR) are the height and width of the viewport. The size of the outer window, i.e., the height and width of the browser window are larger (984 and 430), which, in turn, is larger than what is allowed on your screen.
Chromium Device Emulation works because the size of the outer window is set there. You can use the resizeWindow function to manually set the height and width of the viewport. However, note that you will need to get the correct size of the outer window equal to or smaller than the allowed size.

**Comment by szhux** [comment]
it's not clear for me:
_the height and width of the browser window are larger (984 and 430), which, in turn, is larger than what is allowed on your screen._
My screen resolution is 2880x1800
Did you probably mean that available height is 960 that is lower that 984.
If so then could you please recommend me how I can change that value in test test script?
I tried resizeWindow before the resizeWindowToFitDevice command :

    await t
        .resizeWindow(1000,1000)
      .resizeWindowToFitDevice(device.name, {
        portraitOrientation: device.portraitOrientation});

But I got the same error.

**Comment by szhux** [comment]
I tried to debug and added 
console.log(await t.eval(() => [innerWidth, innerHeight, outerWidth, outerHeight, screen.availWidth, screen.availHeight]))
and go this string:
[ 1200, 837, 1200, 916, 1920, 960 ]

**Comment by szhux** [comment]
So it looks like the cause of the issue that
screen.availHeight(960) < height of iphoneXR (984)

Could you please confirm? If so could do you know the way how I can config screen.availHeight or step it over?

Thank you.

**Comment by szhux** [comment]
I got `Browser availableHeight` based on manual from
https://testcafe-discuss.devexpress.com/t/setting-the-browser-window-size-on-mac-os-x/170/2

**Comment by szhux** [comment]
Also I tried to 
add maximize window function. So updated snippet is :
async function resizeToDevice(t) {
  if (device.name) {
screen.availHeight]))
    await t
        .maximizeWindow()
        .debug()
      .resizeWindowToFitDevice(device.name, {
        portraitOrientation: device.portraitOrientation});
  }
}
![image](https://user-images.githubusercontent.com/33559259/111136482-1505b080-857e-11eb-9cb6-626e4aa61ef5.png)
but still getting the same error

**Comment by szhux** [comment]
Fun fact that it works when I changed my MAC screen resolution to huge one.
So it works for
![image](https://user-images.githubusercontent.com/33559259/111140105-3b2d4f80-8582-11eb-984d-3433e3312194.png)
Thank you,
do you know the way how I manually override Chrome available screen resolution in test scripts?

**Comment by arubtsov** [comment]
```
My screen resolution is 2880x1800
```
On the Mac platform, the Dock and menu bar decrease [`availableHeight`](https://developer.mozilla.org/en-US/docs/Web/API/Screen/availHeight#value).
```
So it looks like the cause of the issue that
screen.availHeight(960) < height of iphoneXR (984)
```
Yes, that is right.

TestCafe does not offer any means to override Mac defaults.
