### ISSUE TITLE
There is no official documentation on cucumber integration with testcafe on testcafe official website

### ISSUE THREAD

**Issue by haideralii** [DevExpress/testcafe#6022]
There are certain posts which explain how we can integrate TestCafe with cucumber, but it's not enough, as there are much issues in those, there should be proper documentation on TestCafe website on how we can integrate TestCafe with cucumber and how we can create a proper framework with it
Thanks

**Comment by AlexSkorkin** [comment]
TestCafe does not have this functionality out of the box. All those plug-ins are third-party ones.

Track this issue to stay informed: [https://github.com/DevExpress/testcafe/issues/2835](https://github.com/DevExpress/testcafe/issues/2835). We'll make an announcement if we implement this feature and publish its documentation.
