### ISSUE TITLE
Unable to turn off quarantineMode via configuration file

### ISSUE THREAD

**Issue by ryansongfabfitfun** [DevExpress/testcafe#6023]
### Are you requesting a feature or reporting a bug?

Bug 

### What is your Test Scenario?

1. Add the quarantineMode in configuration file and set the flag "true".
      {
          "quarantineMode": true
      }
2. Tests will re-try 3 time before fail.
3. Change the quarantineMode to "false" or remove quarantineMode from the configuration file
4. Test should fail on the first attempt. 

### What is the Current behavior?

Tests still re-try 3 time and getting errors on browser disconnected.
Ex: "ERROR The Chrome 89.0.4389.82 / macOS 11.2.2 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues."

### What is the Expected behavior?

After change the quarantineMode to "false" or remove quarantineMode from the configuration file, the tests should on the first attempt. 

### How would you reproduce the current behavior (if this is a bug)?

1. create a test that will fail, such as try find an element does not exist.
2. Add  "quarantineMode": true to the configuration file and run the test
3. Remove the change the quarantineMode to "false" or remove quarantineMode from the configuration file
4. Run the test again

#### Provide the test code and the tested page URL (if applicable)

 
Your website URL (or attach your complete example):

Your complete test code (or attach your test files)

```js
     {
          "quarantineMode": true
      }
```
### Your Environment details:
 
* testcafe version:  1.12.0                 
* node.js version:   v15.10.0                
* command-line arguments:  testcafe chrome testcafe-tests/test/web/demo.test.js 
* browser name and version:  Chrome 89.0.4389.82 
* platform and version:  macOS 11.2.2         
* other:

**Comment by AlexanderMoiseev** [comment]
Hello,

Unfortunately, we could not reproduce this behavior.
Please send us an example project and a video to show how you reproduce the issue. Make sure that the callstack with the problem is visible.
