### ISSUE TITLE
roles issue

### ISSUE THREAD

**Issue by damcik** [DevExpress/testcafe#6026]
### What is your Test Scenario?
My test scenario is about log-in. I think it's not necessary to say what im testing later, because the core of this problem is about logging.
 
### What is the Current behavior?
Im using role to log-in, then clicks into dropdown menu (this menu only occurs for logged in users), and useRole sometimes not works then this test fails, because can't see this dropdown menu.
 
### What is the Expected behavior?
Working roles on my site
 
### What is your web application and your TestCafe test code?
https://github.com/mdyd-dev/product-marketplace-template
 
<details>
<summary>Your website URL (or attach your complete example):</summary>
https://damian-staging.staging.oregon.platformos.com/

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```
export const sellerRole = Role(myUrl + "/sessions/new", async (t) => {
  await t
    .typeText(loginForm.inputs.email, SellerRandomUser.email)
    .typeText(loginForm.inputs.password, SellerRandomUser.password)
    .click(loginForm.buttons.logIn)

  await t.expect(Selector('main').withText(loginConfirmation).exists).ok('message ' + loginConfirmation + " doesn't exists")
})

test('Edit John Profile Page', async (t) => {
  await t.useRole(sellerRole)
// test fails here
  await t
    .click(topMenu.buttons.profileDropdown)
    .click(topMenu.buttons.dashboard)
 


Page Objects

import { Selector } from 'testcafe';

export default class NewSessionForm {
  constructor() {
    this.inputs = {
      firstName: Selector('input[name="profile[first_name]"]'),
      lastName: Selector('input[name="profile[last_name]"]'),
      email: Selector('input[name="user[email]"]'),
      password: Selector('input[name="user[password]"]')
    }
    this.labels = {
      email: Selector('fieldset').withText('E-mail'),
      password: Selector('fieldset').withText('Password'),
      username: Selector('label[for="username"]')
    }
    this.buttons = {
      logIn: Selector('button').withText('Log In'),
      regSubmit: Selector('button').withText('Sign Up'),
      termsAccept: Selector('input[name="user[agreed]"]'),
      register: Selector('a').withText('Register'),
      resetPassword: Selector('a').withText('Reset')
    }


import { Selector } from 'testcafe';

export default class TopMenuBtns {
  constructor() {
    this.buttons = {
      logo: Selector('span').withText('MVP Marketplace'),
      addDropdown: Selector('header').find('button').withAttribute('title', 'Add content'),
      listItem: Selector('a').withText('Create item'),
      addQuestion: Selector('a').withText('Add question'),
      profileDropdown: Selector('header nav > ul > li:last-child button').withAttribute('data-dropdown-toggle'),
      profile: Selector('header').find('a').withText('Profile'),
      selling: Selector('header').find('a').withText('Selling'),
      dashboard: Selector('a').withText('Dashboard'),
      logIn: Selector('header').find('a').withText('Log in'),
      logOut: Selector('header').find('button').withText('Log out'),
      adminPanel: Selector('header').find('a').withText('Admin'),
      items: Selector('header').find('a').withText('Items'),
      groups: Selector('a').withText('Groups'),
      feed: Selector('a').withText('Feed'),
      chat: Selector('#notifications-chat')
    }
    this.addDropdown = {
      addPost: Selector('li a').withText('Add post'),
      addQuestion: Selector('li a').withText('Add question'),
      createGroup: Selector('li a').withText('Create group'),
      createItem:  Selector('li a').withText('Create item')
    }
    this.profileDropdown = {
      profile: Selector('nav a').withText('Public Profile'),
      admin: Selector('li a').withText('Admin'),
      dashboard: Selector('a').withText('Dashboard'),
      selling: Selector('li a').withText('Selling')
    }
  }
}


```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

- Error in Role initializer -
AssertionError: message Logged in doesn't exists: expected false to be truthy

+ expected - actual
```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
2. Register an account
3. Log in
 
### Your Environment details:
 
* testcafe version:                     1.12.0
* node.js version:                     14.11.0
* command-line arguments:   testcafe chrome tests/ --debug-on-fail
* browser name and version:  Chrome newest
* platform and version:           linux mint
* other:

**Comment by SergeyShurygin** [comment]
The attached code looks incomplete. It uses a page model (loginForm, topMenu variables) and the buyerRole in the test while the sellerRole is declared. Please share a full working example so we can reproduce the issue.

**Comment by damcik** [comment]
@SergeyShurygin ok i added missing info

**Comment by SergeyShurygin** [comment]
I reproduced this behavior. The test sometimes passes for me, but in most cases, it fails since the application remains unauthorized after the useRole action

**Comment by damcik** [comment]
exactly, that is core of this report :)

**Comment by miherlosev** [comment]
Hi @damcik 

Could you please simplify the shared test example so I can run it without cloning the repository, investigate that test I should run, etc? The preferred variant - to have only 1 test file with plain selectors (without using page model) that I can run with the command `testcafe chrome <test-file.js>`.
