### ISSUE TITLE
Add the capability to record HTTP requests

### ISSUE THREAD

**Issue by vire** [DevExpress/testcafe#6028]
As a `testcafe` user I would expect an easy way how to export requests from a test into a [HAR file](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting) using an idiomatic testcafe approach e.g. **HarRequestHook**  etc.

Maybe there is already an easy way how to get a HAR export for a test I don't know about.

**Comment by miherlosev** [comment]
Hi @vire 

Could you please describe the scenario where it is necessary?

**Comment by vire** [comment]
As a developer writing an e2e smoke test, I would like to store all the requests+responses in form of HAR for further analysis or creation of mock-data for a statically (network off mode) kinda like recording.

![image](https://user-images.githubusercontent.com/4021908/110782962-0fe7ef00-8268-11eb-89a2-79f407a78f54.png)

**Comment by miherlosev** [comment]
Thank you for the clarification. I guess, the main idea is to have the capability to record HTTP requests. So, the usage of the HAR format is optional.
