### ISSUE TITLE
Starting incognito window and interacting with main window

### ISSUE THREAD

**Issue by dimitriy-k** [DevExpress/testcafe#6031]
I am writing tests for co-viewing functionality: **user** is filling out form in his browser and **controller** can view entered data in his browser.

When I just [open new window](https://devexpress.github.io/testcafe/documentation/guides/basic-guides/run-tests.html), then the same role is applied (of **controller**) and I am not able to use **user** role (so, no cookies or whatever).

I have tried [new instance](https://devexpress.github.io/testcafe/documentation/guides/basic-guides/run-tests.html), but did not succeed to run new testcafe instance inside testcafe test.

What are possibilities to run two different windows, which do not share storages/cookies, but I should be able to interact between windows (passing data, entering data in one window, checking entered data in another window)?

**Comment by felis2803** [comment]
It is not possible at the moment. We will work on this functionality in the context of the [#5291](https://github.com/DevExpress/testcafe/issues/5291) issue. Please track it to be aware of our progress.
As a workaround, you can implement your script using parallel execution with [child_process.exec](https://nodejs.org/dist/latest-v14.x/docs/api/child_process.html#child_process_child_process_exec_command_options_callback) or [Web Workers API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API), but it is a complex task and such a test will be difficult to debug.
Try rewriting your tests to remove interactivity and run scripts for different roles in sequence.
