### ISSUE TITLE
TestCafe defines the element in an iframe as invisible although it isn't

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#6033]
### What is your Test Scenario?
Switch to an iframe, click on iframe's element (an input)
 
### What is the Current behavior?
Test fails. Maybe switching to an iframe executed wrong.
 
### What is the Expected behavior?
Test should pass
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>
Please see Studio issue https://github.com/DevExpress/testcafe-studio/issues/3616 for more information.
This issue based on SC ticket from licensed user https://supportcenter.devexpress.com/internal/ticket/details/T973105/
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from 'testcafe';

fixture `arcgis`
    .page `***`;

test('New Test', async t => {
const iframe = Selector('main .demo-app-module--live-demo--18PqP');

    await t
        .expect(iframe.visible).ok('', {timeout: 10000})
        .switchToIframe('main .demo-app-module--live-demo--18PqP')
        .wait(10000)

        .click(Selector('[title="Find address or place"]'));
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```
Running tests in:
 - Chrome 88.0.4324.190 / Windows 10

 arcgis
 × New Test

   1) The element that matches the specified selector is not visible.

      Browser: Chrome 88.0.4324.190 / Windows 10

         10 |        .expect(iframe.visible).ok('', {timeout: 10000})
         11 |        .switchToIframe('main .demo-app-module--live-demo--18PqP')
         12 |        .wait(10000)
         13 |
         14 |        .debug()
       > 15 |        .click(Selector('[title="Find address or place"]'));
         16 |});
         17 |

         at <anonymous> (D:\GitHub\testcafe-phoenix\test.js:15:10)
         at asyncGeneratorStep (D:\GitHub\testcafe-phoenix\test.js:1:201)
         at _next (D:\GitHub\testcafe-phoenix\test.js:1:539)
         at <anonymous> (D:\GitHub\testcafe-phoenix\test.js:1:704)
         at <anonymous> (D:\GitHub\testcafe-phoenix\test.js:1:445)
         at <anonymous> (D:\GitHub\testcafe-phoenix\test.js:6:5)
```
</details>

<details>
<summary>Screenshots:</summary>

See a video in Studio ticket
</details>

### Steps to Reproduce:

1. Run test 
2. On debugger check that element `Selector('[title="Find address or place"]')` is visible
3.  Get failed test result
 
### Your Environment details:
 
* testcafe version:                   1.12.0
* node.js version:                    14.15.0
* command-line arguments:  `testcafe chrome test.js`
* browser name and version: Chrome 88.0.4324.190 (Official Build) (64-bit)
* platform and version:          Windows 10
* other:

**Comment by gabrielrobert** [comment]
I can also reproduce this error using Chrome headless on Linux.
