### ISSUE TITLE
t.expect.contains failing with objects in an array

### ISSUE THREAD

**Issue by jdtimmerman** [DevExpress/testcafe#6036]
### What is your Test Scenario?
I have an array of objects. I want to check if this array contains a specific object.
 
### What is the Current behavior?
The assertion fails even though the object I am searching exactly matches one of the objects in the array.
 
### What is the Expected behavior?
The assertion to correctly compare the object in the array and have my test pass.
 
### What is your web application and your TestCafe test code?
I can reproduce the issue with this minimal working example

```javascript
fixture`Compare objects in arrays`;

test("objects", async t => {
  // Given some array of objects
  const array = [
    {a: "a", b: "c"},
    {a: "d", b: "e"},
    {a: "f", b: "x"}
  ];
  // This is an exact copy/paste copy of array[0]
  const test = {a: "a", b: "c"};

  // expect.contains appears to work correctly with an exact instance
  await t.expect(array).contains(array[0]);

  // comparing objects also works as expected
  await t.expect(array[0]).eql(test);

  // The following assertion fails even though the previous 2 assertions pass
  await t.expect(array).contains(test);
});
```

Running this example gives the following output

```
$ npx testcafe firefox test/tests/bug.js
 Running tests in:
 - Firefox 86.0 / Linux 0.0

 Compare objects in arrays
 ✖ objects

   1) AssertionError: expected [ Array(3) ] to include { a: 'a', b: 'c' }
      
      + expected - actual
      
      -[
      -  {
      -    a: 'a'
      -    b: 'c'
      -  }
      -  {
      -    a: 'd'
      -    b: 'e'
      -  }
      -  {
      -    a: 'f'
      -    b: 'x'
      -  }
      -]
      +undefined
      

      Browser: Firefox 86.0 / Linux 0.0

         15 |
         16 |  // comparing objects also works as expected
         17 |  await t.expect(array[0]).eql(test);
         18 |
         19 |  // The following assertion fails even though the previous 2 assertions pass
       > 20 |  await t.expect(array).contains(test);
         21 |});
         22 |


         at <anonymous> (/x/test/tests/bug.js:20:25)
         at asyncGeneratorStep (/x/test/tests/bug.js:1:114)
         at _next (/x/test/tests/bug.js:1:452)
```

### Your Environment details:
 
* testcafe version:                  `1.12.0`
* node.js version:                   `v15.10.0`
* command-line arguments:  `npx testcafe firefox test/tests/bug.js`
* browser name and version: `Mozilla Firefox 86.0`
* platform and version:          `Linux X 5.11.2-1-MANJARO #1 SMP PREEMPT -date- x86_64 GNU/Linux`

**Comment by viktoria2506** [comment]
You can't use contains in your case, because it is implemented through includes. Includes can't be used to find an object in an object array, since it does not compare field values.
For example, this option will work in your case:
`await t.expect(array).contains(array[0]);` ,
This option will not work:
`await t.expect(array).contains(test);` .
This occurs because the objects' array[0] and test are the same, but not identical.
This is a feature of the [includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes) method.

I suggest you use the following workaround:

`await t.expect(array.find(a => JSON.stringify(a) === JSON.stringify(test))).ok();`

**Comment by jdtimmerman** [comment]
This works, although serialization seems fragile. I hope that my properties are always serialized in the exact same order. And the output in case of a test-failure is a lot less intuitive (`expected undefined to be truthy`).

**Comment by viktoria2506** [comment]
You can sort the properties so that they are always serialized in the same order, and also add a message in case the test fails.
For example:
`await t.expect(array.find(a => JSON.stringify(a) === JSON.stringify(test))).ok('the object is not contained in the array');`
