### ISSUE TITLE
Testcase hangs after expecting in two different windows. Testcafe V1.12 Chrome 89.

### ISSUE THREAD

**Issue by PatrickVibild** [DevExpress/testcafe#6037]
### What is your Test Scenario?
Running a test that requires interaction with two windows and expecting in two windows.
 
### What is the Current behavior?
The tests hangs if expecting in both windows with Chrome.
 
### What is the Expected behavior?
Finish the test result.
 
### What is your web application and your TestCafe test code?
Running testcafe on website that requires access. However I replicated this issue on a public website. 

The issue comes when expecting in two different windows. If the new created window did not had any expect the tests result would finish. However if both windows are expected the tests hangs when expecting in the main or parent window.

 
```
fixture('Two windows - expect bug')
    .page('https://www.dr.dk/');
test
('Open website page in 2 windows and expect', async t => {
    await t
        .click(Selector('button[name="submitAll"]'))
        .click(Selector('button[class="dre-search-input__button dre-search-input--expand__button"]'))
        .typeText(Selector('input[name="query"]'), 'foo')
        .openWindow('https://www.dr.dk/').resizeWindow(1200,700)
        .typeText(Selector('input[name="query"]'), 'foo')
        .pressKey('enter')
        .expect(Selector('a[href="https://www.dr.dk/"]').exists).ok({ timeout: 5000 })
        .closeWindow()
        .pressKey('enter')
        .expect(Selector('a[href="https://www.dr.dk/"]').exists).ok({ timeout: 5000 })
        .expect(Selector('span').withText('Yuk Foo | Wolf Alice').exists).ok({ timeout: 5000 });
}).only;
 
```
### Your Environment details:
 
* testcafe version:                   1.12.0
* node.js version:                    14.15.4
* command-line arguments:  testcafe chrome src/tests -c 1
* browser name and version: Chrome v89
* platform and version:          Windows 10

**Comment by AndreyBelym** [comment]
Thank you for your report. Unfortunately, I cannot reproduce the issue with the version from the Git repo. Could you please install 
[testcafe-1.12.1-alpha.1.tar.gz](https://github.com/DevExpress/testcafe/files/6130384/testcafe-1.12.1-alpha.1.tar.gz) with the following command:
```
npm i https://github.com/DevExpress/testcafe/files/6130384/testcafe-1.12.1-alpha.1.tar.gz
```
or by using the following line in your `package.json` in the `dependencies` or `devDependencies` sections:
```
"testcafe": "https://github.com/DevExpress/testcafe/files/6130384/testcafe-1.12.1-alpha.1.tar.gz"
```
and check if the problem can be reproduced with this version and your machine?

**Comment by PatrickVibild** [comment]
Hi,

I tried with alpha 1.12.1 version. Also fails.

However, I found that the issue might be when running this tests with my `.testcaferc.json` file.

When I remove my testcafe config file the test doesnt hung anymore. Can you please try if running the previous tests with the next `.testcaferc.json` triggers the issue? 

```
{
  "browsers": [
    "chromium"
  ],
  "src": [
    "src/tests"
  ],
  "screenshots": {
    "path": "report/media",

    "takeOnFails": true,
    "pathPattern": "${DATE}/${TEST}/${FILE_INDEX}.png"
  },
  "videoPath": "report/media",
  "videoOptions": {
    "singleFile": false,
    "failedOnly": true,
    "pathPattern": "${DATE}/${TEST}/${FILE_INDEX}.mp4"
  },
  "skipJsErrors": true,
  "skipUncaughtErrors": true
}
```

**Comment by AndreyBelym** [comment]
Thank you for sharing your config file. I was able to reproduce the issue. It seems that it is caused by video recording options: the test passes when I remove them from the config file.

**Comment by achernak** [comment]
@AndreyBelym Any updates regarding the issue? Is there any chance that it will be picked up and fixed soon?
