### ISSUE TITLE
Failed to restore connection to window within the allocated timeout.

### ISSUE THREAD

**Issue by rob4629** [DevExpress/testcafe#6038]
### What is your Test Scenario?

As per:
https://stackoverflow.com/questions/66555583/is-there-a-way-to-wait-for-a-window-to-close-with-testcafe

We have a few test flows which go through the PayPal window twice (2nd time is the the [vault flow](https://developers.braintreepayments.com/guides/paypal/vault/javascript/v2#:~:text=Vaulting%20a%20PayPal%20account%20will,addresses%20in%20the%20PayPal%20account)). It seems that TestCafe fails to return to the main window, once the child window is closed (after completing the Vault flow).
 
### What is the Current behavior?

TestCafe fails with `Failed to restore connection to window within the allocated timeout.` (for desktop chrome).
 
### What is the Expected behavior?

To behave in the same way as the non-vault flow, returning focus to the main/parent window once child window closes.

### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
import { Selector, t } from 'testcafe';
import Chance from 'chance';

const submitWithPaypalButton = async (ppmu = false) => {
  const paypalIframe = Selector('[data-testid="paypal-button"] iframe').withAttribute('src');
  const ppmuPaypalIframe = Selector('#modal-paypal-button iframe').withAttribute('src');
  const payWithPaypalButton = Selector('[data-funding-source="paypal"]').filterVisible();

const paypalIframeSelector = ppmu ? ppmuPaypalIframe : paypalIframe;
  await t
    .expect(paypalIframeSelector.visible)
    .ok()
    .switchToIframe(paypalIframeSelector)
    .hover(payWithPaypalButton)
    .click(payWithPaypalButton)
    .wait(500);
};

const paypalLogin = async () => {
  const emailInput = Selector('#email');
  await t
    .expect(emailInput.visible)
    .ok({ timeout: 30000 })
    .typeText(emailInput, 'you@email.com')
    .click(Selector('#btnNext'))
    .typeText(Selector('#password'), 'password1')
    .click(Selector('#btnLogin'));
};

const completePaypalMiniWindow = async ({ shouldLogin = true, oneTimePayment = false } = {}) => {
  const consentButton = Selector('#consentButton, [data-test-id="continueButton"]').filterVisible();
  const submitButtonInitial = Selector('[data-testid="submit-button-initial"]');
  if (shouldLogin) {
    await paypalLogin();
  }

  const continueButton = oneTimePayment ? submitButtonInitial : consentButton;
  const paymentOptions = Selector('#paymentMethod, [data-testid="stacked-payment-options"]').filterVisible();

  await t
    .expect(paymentOptions.visible)
    .ok()
    .hover(continueButton)
    .click(continueButton);
};

fixture('This is a demo fixture').page('https://www.staging-change.org/').httpAuth({ "username": "testcafe", "password": "<password>" });

test.only('Failed to restore connection to window within the allocated timeout', async () => {
  const emailAddress = chance.email();
  // Navigate to the Sponsorship page, enter promotion amount and pay with PayPal
  await t
    .navigateTo('/p/asdf-stgaqaoppscore8/sponsors/new?country_code=FR&lang=fr-FR')
    .click(Selector('[data-testid="cookie-wall-accept"]'))
    .expect(Selector('.js-payment-form').visible)
    .ok()
    .typeText(Selector('[data-testid="payment-form-amount-input"]'), '1', { replace: true })
    .click(Selector(`[data-testid="payment-option-button-paypal"]`));

  await t
    .typeText(Selector('[data-testid="input_email"]').filterVisible(), emailAddress)
    .typeText(Selector('[data-testid="input_confirmation_email"]').filterVisible(), emailAddress)
    .typeText(Selector('[data-testid="input_first_name"]'), 'first')
    .typeText(Selector('[data-testid="input_last_name"]'), 'last');
  await submitWithPaypalButton();

  // PayPal Window
  await completePaypalMiniWindow({ oneTimePayment: true });

  // Accept Upsell
  await submitWithPaypalButton(true);
  await completePaypalMiniWindow({ shouldLogin: false });
  await t.expect(Selector('[data-testid="ppmu-ty"]').visible).ok();
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
  "browsers": ["chrome"],
  "src": "./tests/**/*.js",

  "assertionTimeout": 15000,
  "pageLoadTimeout": 30000,
  "selectorTimeout": 15000,

  "disableMultipleWindows": false,

  "quarantineMode": false,
  "skipJsErrors": true,

  "disablePageCaching": true,

  "reporter": [
    {
      "name": "xunit",
      "output": "artifacts/test-results/results.xml"
    },
    {
      "name": "spec"
    }
  ],

  "screenshots": {
    "fullPage": true,
    "takeOnFails": true,
    "pathPattern": "${TEST_ID}/${RUN_ID}_${FILE_INDEX}.png",
    "path": "artifacts/screenshots"
  }
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```
    ✖ This is a demo test (screenshots: /pathqaa/artifacts/screenshots/test-1/_errors/1.png)

   1) Failed to restore connection to window within the allocated timeout.

      Browser: Chrome 89.0.4389.90 / macOS 10.15.7
      Screenshot: /path/artifacts/screenshots/test-1/_errors/1.png

         72 |  await completePaypalMiniWindow({ oneTimePayment: true });
         73 |
         74 |  // Accept Upsell
         75 |  await submitWithPaypalButton(true);
         76 |  await completePaypalMiniWindow({ shouldLogin: false });
       > 77 |  await t.expect(Selector('[data-testid="ppmu-ty"]').visible).ok();
         78 |});

         at <anonymous> (/path/tests/demo/test.js:77:63)
         at asyncGeneratorStep (/path/tests/demo/test.js:3:302)
         at _next (/path/tests/demo/test.js:3:640)


 1/1 failed (1m 26s)

```
</details>

<details>
<summary>Screenshots:</summary>

```
![1](https://user-images.githubusercontent.com/37812673/111845361-e8c19b00-88c1-11eb-8030-d27ff24fc411.png)

```
</details>

### Steps to Reproduce:

1. Go to my website ...
2. Run test code (_use your own email and password_)...
3. See the error...
 
### Your Environment details:
 
* testcafe version: 1.12.0                  
* node.js version: 12.14.1                   
* command-line arguments:  testcafe chrome 
* browser name and version: Chrome 89.0.4389.82
* platform and version:          
* other:

**Comment by viktoria2506** [comment]
The error message does not match the test you submitted. Please check the data so that we can reproduce the problem and offer you a solution.

**Comment by rob4629** [comment]
I'll update the configuration file to use `chrome` rather than `chome:emulation...`. That should let you see the error.
Can you tell me what other error you're seeing? (I'm about to raise a separate bug around PayPal being blocked in emulation mode)

**Comment by viktoria2506** [comment]
I didn't get any errors. I mean that in your test report, there is code that is not available in your test file. For instance, the assertPPMUThankYou function is missing in the test. Check the test report and the test you submitted so that we can verify the issue. Also, please modify the test so that there is no payment process in it. Thank you.

**Comment by rob4629** [comment]
> Also, please modify the test so that there is no payment process in it.

I've been unable to reproduce this issue _without_  the payment process. I'll keep trying though. In the meantime, we can refund all of the promotions made for that petition.

I've updated the error, I converted `assertPPMUThankYou` to the individual steps, and forgot to copy in the new console error. I've also added a screenshot, which just shows our `Thank You` page (so you can see it successfully navigates to that page after completing the PayPal window).

**Comment by aleks-pro** [comment]
Hello @rob4629,

Please share a web app project sample so that we can reproduce the issue by using the PayPal sandbox account.

**Comment by rob4629** [comment]
I'm working on trying to reproduce this in my sample web app... but not having much luck. I'll continue with it next week and update you then. Sorry for the inconvenience

**Comment by rob4629** [comment]
Sorry for the delay, we're going to set up access to our deployment environment, so you can test using a sandbox paypal account. I'll send an email to `support@devexpress.com` with the details, once its ready.

**Comment by aleks-pro** [comment]
For the team: take a look at this private ticket to reproduce the issue - https://supportcenter.devexpress.com/internal/ticket/details/T990544

**Comment by olenahuk** [comment]
I also have similar issue. Is there any updates on this?
