### ISSUE TITLE
Implement mouse actions

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#6039]
- [ ] t.mouseDown
- [ ] t.rightMouseDown
- [ ] t.mouseUp
- [ ] t.rightMouseUp

**Comment by becciwatson** [comment]
We are looking forward to being the first to test and use this functionality!
Thanks in advance.

**Comment by becciwatson** [comment]
Until this native branch gets published, check out @Dmitry-Ostashev did this awesome code as a helper function that is an awesome and works really well 
https://github.com/Dmitry-Ostashev/testcafe-mouse-events-example
