### ISSUE TITLE
Enumerate tests without running

### ISSUE THREAD

**Issue by anthony-chu** [DevExpress/testcafe#6042]
### What is your Test Scenario?

I would like to see the concurrency functionality have a dry-run option, where tests for each session/instance are listed without actually running them. 

### What are you suggesting?

Currently, users can indicate to TestCafe how many concurrent sessions are needed in order to run a suite of tests, and TestCafe automatically spawns those sessions. However, there is no indication upfront of what those tests are. It would be helpful for some workflows to know ahead of time which tests will be run in each session.

For example, sometimes tests are split off into multiple pods or containers, and each pod or container is responsible for running a set of tests. This gives the added benefit of reducing strain and resource consumption on a single container or pod. The results would later be joined together later. However, this means that users need to pre-determine which tests should be run together in a given pod/container, and there is not (as far as I know, and I may be wrong, so correction/feedback is welcome) a way for TestCafe to list out the tests will go in each session.

I am suggesting that a dry-run option be added to the concurrency capability, so that a list of tests/fixtures can be listed out without actually running the tests (Cucumber has a similar functionality). That way, the tests can be broken down by TestCafe (as opposed to testers ahead of time) and sent to individual pods/containers to run their respective test suites.

### What alternatives have you considered?

The impetus comes from having used Cucumber and parallel_tests, where cucumber could break up tests dynamically. Currently, our team is spending time and effort into manually breaking up tests to distribute to the different pods/containers, and it would be great if TestCafe were able to handle this otherwise time-consuming task for testers. We recently switched over to TestCafe from Cucumber and have missed this functionality. It would be great to see a similar functionality with TestCafe.

**Comment by viktoria2506** [comment]
Thanks for your suggestion to enumerate tests without running. However, regarding the concurrency mode, we cannot know in advance which browser instance each test will run in, because the test is dispatched after an instance is free.

**Comment by anthony-chu** [comment]
I see, so the tests are not split up beforehand, but rather distributed as an instance is available. Am I understanding how concurrency works in TestCafe?

**Comment by viktoria2506** [comment]
In concurrent mode, TestCafe invokes multiple instances of each browser. These instances constitute the pool of browsers against which tests run concurrently, i.e. each test runs in the first available instance.
For more information about the concurrency mode, please refer to:
[https://devexpress.github.io/testcafe/documentation/guides/basic-guides/run-tests.html#run-tests-concurrently](https://devexpress.github.io/testcafe/documentation/guides/basic-guides/run-tests.html#run-tests-concurrently)

**Comment by anthony-chu** [comment]
Thanks for the explanation. Since the concurrency functionality does not split up the tests prior to running, I'll go ahead and close this issue.
