### ISSUE TITLE
Proxy causing paypal error: `expected window to be same domain`

### ISSUE THREAD

**Issue by rob4629** [DevExpress/testcafe#6045]
### What is your Test Scenario?

Promote a petition using PayPal, in mobile emulation mode
 
### What is the Current behavior?

An issue is occurring where the PayPal mini-window is blocked when running tests in Chrome mobile emulation mode (`"chrome:emulation:device=iPhone X"`). This isn't happening for Desktop runs (`chrome`)... so I'm not sure what the cause is.
Errors we're seeing in Amplitude are `Can not open popup window - blocked` and `expected window to be same domain` 

### What is the Expected behavior?

Like Desktop (`chrome`), I expect the PayPal window to open without any issues.
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector, t } from 'testcafe';

const submitWithPaypalButton = async () => {
  const paypalIframe = Selector('[data-testid="paypal-button"] iframe').withAttribute('src');
  const payWithPaypalButton = Selector('[data-funding-source="paypal"]').filterVisible();

  await t
    .expect(paypalIframe.visible)
    .ok()
    .switchToIframe(paypalIframe)
    .hover(payWithPaypalButton)
    .click(payWithPaypalButton)
    .wait(500);
};

const paypalLogin = async () => {
  const emailInput = Selector('#email');
  await t
    .expect(emailInput.visible)
    .ok({ timeout: 30000 })
    .typeText(emailInput, 'you@email.com')
    .click(Selector('#btnNext'))
    .typeText(Selector('#password'), 'password1')
    .click(Selector('#btnLogin'));
};

const completePaypalMiniWindow = async ({ shouldLogin = true } = {}) => {
  if (shouldLogin) {
    await paypalLogin();
  }

  const continueButton = Selector('#consentButton, [data-test-id="continueButton"]').filterVisible();
  const paymentOptions = Selector('#paymentMethod, [data-testid="stacked-payment-options"]').filterVisible();

  await t
    .expect(paymentOptions.visible)
    .ok()
    .hover(continueButton)
    .click(continueButton);
};

fixture('Login to PayPal').page('https://www.change.org');

test('Complete PayPal window', async () => {
  // Navigate to the Start a Petition page, and enter in Ask and DM details

  await t
    .navigateTo('/p/change-org-to-test-a-small-petition/sponsors/new?country_code=US&lang=en-US')
    .expect(Selector('.js-payment-form').visible)
    .ok()
    .typeText(Selector('[data-testid="payment-form-amount-input"]'), '1', { replace: true })
    .click(Selector(`[data-testid="payment-option-button-paypal"]`));

  await t
    .typeText(Selector('[data-testid="input_email"]').filterVisible(), 'email@email.com')
    .typeText(Selector('[data-testid="input_confirmation_email"]').filterVisible(), 'email@email.com')
    .typeText(Selector('[data-testid="input_first_name"]'), 'first')
    .typeText(Selector('[data-testid="input_last_name"]'), 'last');
  await submitWithPaypalButton();

  // PayPal Window
  await completePaypalMiniWindow();
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
  "browsers": ["chrome:emulation:device=iPhone X"],
  "src": "./tests/**/*.js",
  "clientScripts":[
    {
      "module":"axe-core/axe.min.js"
    }
  ],

  "assertionTimeout": 15000,
  "pageLoadTimeout": 30000,
  "selectorTimeout": 15000,

  "disableMultipleWindows": false,

  "quarantineMode": false,
  "skipJsErrors": true,

  "disablePageCaching": true,

  "reporter": [
    {
      "name": "xunit",
      "output": "artifacts/test-results/results.xml"
    },
    {
      "name": "spec"
    }
  ],

  "screenshots": {
    "fullPage": true,
    "takeOnFails": true,
    "pathPattern": "${TEST_ID}/${RUN_ID}_${FILE_INDEX}.png",
    "path": "artifacts/screenshots"
  }
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```
No errors here, except not finding the email field...
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:  1.12.0                  
* node.js version:  12.14.1                   
* command-line arguments: testcafe "chrome:emulation:device=iPhone X"  
* browser name and version: Chrome 
* platform and version:  MacOS        
* other:

**Comment by AndreyBelym** [comment]
Thank you for your feedback. Currently, device emulation is not supported when using multiple windows: https://github.com/DevExpress/testcafe/issues/5787. Although we have plans to implement this functionality, I cannot say anything specific about when it will be released. Please subscribe to #5787 to get notified about our progress and discuss this feature.
