### ISSUE TITLE
Testcafe browser differs from local browser

### ISSUE THREAD

**Issue by AndrewRedisLabs** [DevExpress/testcafe#6055]
### What is your Test Scenario?

 I would like to make sure that testcafe fails when it should in this particular case as its passing when it should fail.
### What is the Current behavior?

 The scenario is at my company we raise instances in AWS put our product on the instance then run the automation. When I try to go to the instance I get stuck with a spinner at the login page. I tried firefox, chrome, chromium, safari, incognito, tor, etc... They all get stuck at this spinner and you cant get to the login page because of this.

When I run some tests via testcafe on my computer using chrome on this instance it gets past this spinner, logs in, then just resumes tests like nothing is wrong. I have tried using localhost as the host, different ports, skip js errors, and other flags.

I believe I have proved this is related to the proxy server as if i try some online proxy servers, some of them perform like testcafe does and successfully gets to the login page.  

The developers have found out that this was due to bad headers in the code.  I am not sure but my guess is that testcafe is filtering out these headers with the proxy server thus allowing the test to bypass the error in the browser.
### What is the Expected behavior?

When i run a test via testcafe it will also get stuck on this spinner then fail.
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>
Please let me know if this is needed and when someone will look into this and I will raise an instance for a short period of time and provide the IP.  Also is there a way to keep the IP private?

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Your Environment details:
 
* testcafe version: 1.11.0
* node.js version: 12.13.1
* command-line arguments: -e
* browser name and version: chrome Version 88.0.4324.192
* platform and version: Mac Version 10.15.7
* other:

**Comment by AndrewRedisLabs** [comment]
I have upgraded to 1.12.0 and this is still occurring.

**Comment by miherlosev** [comment]
> Please let me know if this is needed and when someone will look into this and I will raise an instance for a short period of time and provide the IP. Also is there a way to keep the IP private?

> The developers have found out that this was due to bad headers in the code.

We cannot debug the issue in the way you wish to proceed. We need to be able to run the example locally. It looks like your programmers figured out the area where the issue might be. So, please share a simple example that we can use to reproduce and research the issue.

**Comment by AndrewRedisLabs** [comment]
Hi you can use this:

https://54.167.52.16:8443

**Comment by arubtsov** [comment]
Thank you for sharing the example. I was able to reproduce the described behavior.

**Comment by AndrewRedisLabs** [comment]
Thanks i have torn down the environment as of now.  Please let me know if you need another instance of this.

**Comment by miherlosev** [comment]
@AndrewRedisLabs 

To investigate the issue, we need a testing page that should be reachable at any time.  Feel free to reopen this issue if you can make such an example.
