### ISSUE TITLE
Add capability to process the source code of custom browser extensions

### ISSUE THREAD

**Issue by duffmagic** [DevExpress/testcafe#6059]
### What is your Test Scenario?
It appears that TC (hammerhead) wraps messages (e.g. from window.postMessage and received via window.addEventListener).  I'm seeing 2 issues with this wrapping/unwrapping both effecting communication between a page's inline script and a Chrome extension's JS file.
**Similarly reproducible in Edge Chromium browser.**

 
### What is the Current behavior?

1. UNWRAPPING NOT HAPPENING ISSUE
When I postMessage from my html page's script tag and receive it with addEventListener from a JS file within a Chrome Extension, my own data object moves from event.data down to event.data.message.  This may be a defect in the unwrapping.
**While I can technically workaround this issue by allowing for it in my production code, this is far from ideal.** 

2. WRAPPING NOT HAPPENING ISSUE (I think)
When I postMessage from my JS file within a Chrome Extension and receive it with my html page's script tag, event.data arrives 'undefined'.
**I have found no workaround for this issue.**

**Note:**
- In creating the simplified demonstration of these issues, I noticed that they **do not occur when** we reference Content.js like an external JS file, from a <script> tag in `index.html`.  They **only arise when we moved Content.js out to an extension**.  Unfortunately for us, an extension is what we need in production (as it needs to also communicate with a Native Message Host application on the other side - the extension is the middle man).
 
### What is the Expected behavior?

Both messages should contain the data as it was sent rather than being affected by the testing infrastructure.
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Attached SimpleSample.zip</summary>
[SimpleSample.zip](https://github.com/DevExpress/testcafe/files/6164949/SimpleSample.zip)

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 see attached
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
n/a
```
</details>

<details>
<summary>Your complete test report:</summary>

```
n/a
```
</details>

<details>
<summary>Screenshots:</summary>

<img width="1214" alt="Debug_Issue_1" src="https://user-images.githubusercontent.com/18442389/111645386-8fda0000-87f8-11eb-9855-4e04838f9c68.png">
<img width="1216" alt="Debug_Issue_2" src="https://user-images.githubusercontent.com/18442389/111645680-e1828a80-87f8-11eb-9dce-8523219d4dc5.png">

</details>

### Steps to Reproduce:

1. Download the attached zip, extract and update the `pageUrl` filepath in `mytest.js` to point at the `index.html` file in the extracted location.
2. Open Chrome using your default profile and goto Menu > More Tools > Extensions
3. Enable Developer Mode
4. Select `Load Unpacked` and point at the `extension` folder in the extracted location. More info on this at https://developer.chrome.com/docs/extensions/mv2/getstarted/#manifest
5. Open `index.html` and you should see a text box saying "Loading..." immediately replaced by "Page and Extension communication is working!"
6. Now run the same in TC using the `mytest.js` script
e.g. I used these commands
```
testcafe chrome:userProfile C:\Users\Administrator\Downloads\SimpleSample\SimpleSample\mytest.js --live -S -s .
testcafe edge:userProfile C:\Users\Administrator\Downloads\SimpleSample\SimpleSample\mytest.js --live -S -s .
```
The page content becomes
```
Loading...

TC-HH forgot to unwrap event.data.message

TC-HH deleted my message's event.data
```
7. Place breakpoints on the points in the code where it's leading to outputting these 2 notes to understand what's going on. (See attached screenshots for examples of debugging both points)
 
### Your Environment details:
 
* testcafe version:                   1.12.0
* node.js version:                    v14.16.0
* command-line arguments:  chrome/edge:userProfile C:\Users\Administrator\Downloads\SimpleSample\SimpleSample\mytest.js --live -S -s .
* browser name and version: Chrome 89.0.4389.82 (Official Build) (64-bit), Edge 89.0.774.54 (Official build) (64-bit)
* platform and version:    Windows 10 Enterprise, 20H2, 19042.867, Windows Feature Experience Pack 120.2212.551.0, Intel Core Processor (Skylake, IBRS)   2.20 GHz  (4 processors), Installed RAM	32.0 GB, 64-bit operating system, x64-based processor

* other:                                   

@viktoria2506 as mentioned on #5768

**Comment by miherlosev** [comment]
TestCafe modifies the tested website source code to support the [built-in wait](https://devexpress.github.io/testcafe/documentation/guides/concepts/built-in-wait-mechanisms.html)[ing](https://devexpress.github.io/testcafe/documentation/guides/concepts/built-in-wait-mechanisms.html)[ mechanisms](https://devexpress.github.io/testcafe/documentation/guides/concepts/built-in-wait-mechanisms.html).
At present, TestCafe doesn't modify the source code of custom browser extensions. This can sometimes lead to the problems that you faced. In the future, we will think about the capability to modify the JavaScript code of browser extensions.

**Comment by duffmagic** [comment]
@miherlosev Thanks for the response. 
I take it this means that it's not something TC plan on addressing in the short-term?

If not, have you any pointers on what in TC I would need to update to add this support myself? My fix might be easier as I only need to cater for my own use-case.

Without any fixes, have you any suggested workarounds for issue 2?  I was thinking that I might be able to wrap the message myself as if TC had done it.

Finally, I believe it's possible to inject JS onto pages in TC.  I might go down this route to avoid changing my production code. 
 Would TC block me from injecting JS into my extension's JS?

**Comment by aleks-pro** [comment]
Hello @duffmagic ,

You are right. This task looks very complex and, at the moment, we have no plans to implement it.
testcafe-hammerhead uses [PageProcessor ](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/processing/resources/index.ts) to get scripts from HTML-page and modify them to wrap postMessage calls. So, to fix the issue, you will need to find how to get plugin content and process it using PageProcessor.
