### ISSUE TITLE
Some URLs are not correctly resolved

### ISSUE THREAD

**Issue by sorin-davidoi** [DevExpress/testcafe#6069]
### What is your Scenario?

Upgrade from testcafe@1.10.1 to testcafe@1.12.0.
 
### What is the Current behavior?

All the tests are passing.
 
### What is the Expected behavior?

Some tests are failing because some requests are made to the wrong address.

### Steps to Reproduce:

1. Run `node node_modules/gulp/bin/gulp http-playground`
2. Load https://docs.google.com/presentation/d/1XrSz1-5B_gEUQS9YXQclm-vzTBlizHqwDmFVIJDu0sY/edit (same as DevExpress/testcafe-hammerhead#2569, it loads now)
3. Search in the Network panel for "peoplestackwebexperiments"

With https://github.com/DevExpress/testcafe-hammerhead/commit/add0f742e0a9105ef1817073b28078bf0f8324f6 the request is made to http://localhost:1402/6fBSZKdHg!a!1!s*docs.google.com/https://peoplestackwebexperiments-pa.clients6.google.com/$rpc/peoplestackwebexperiments.PeopleStackExperimentsService/GetExperimentFlags.

With https://github.com/DevExpress/testcafe-hammerhead/commit/5bad4c2fc9d63cb106fb7e77f8f9215437e370ea the request is made to http://localhost:1401/Px9bBEMp0/https://peoplestackwebexperiments-pa.clients6.google.com/$rpc/peoplestackwebexperiments.PeopleStackExperimentsService/GetExperimentFlags

The change in behavior seems to have been introduced by https://github.com/DevExpress/testcafe-hammerhead/commit/add0f742e0a9105ef1817073b28078bf0f8324f6, and is still present in https://github.com/DevExpress/testcafe-hammerhead/commit/402199342b365cbf61c41bbb752e4e9e1bcfea7d.
 
### Your Environment details:

* node.js version:                    v14.16.0
* browser name and version: Firefox 86
* platform and version:          macOS 11.2

**Comment by Dmitry-Ostashev** [comment]
We use only the main TestCafe repository for user suggestions and bugs, so I transferred this issue to the `DevExpress/testcafe` repository.

**Comment by LavrovArtem** [comment]
I've checked this issue and cannot see the wrong address.

>With add0f74 the request is made to http://localhost:1402/6fBSZKdHg!a!1!s*docs.google.com/https://peoplestackwebexperiments-pa.clients6.google.com/$rpc/peoplestackwebexperiments.PeopleStackExperimentsService/GetExperimentFlags.
>
>With 5bad4c2 the request is made to http://localhost:1401/Px9bBEMp0/https://peoplestackwebexperiments-pa.clients6.google.com/$rpc/peoplestackwebexperiments.PeopleStackExperimentsService/GetExperimentFlags

```diff
-http://localhost:1401/Px9bBEMp0/
https://peoplestackwebexperiments-pa.clients6.google.com/$rpc/peoplestackwebexperiments.PeopleStackExperimentsService/GetExperimentFlags
+http://localhost:1402/6fBSZKdHg!a!1!s*docs.google.com/
https://peoplestackwebexperiments-pa.clients6.google.com/$rpc/peoplestackwebexperiments.PeopleStackExperimentsService/GetExperimentFlags
```

URLs are equal except for our proxy part. It's different because we change the processing mechanism of client requests(fetch, xhr), and all works as expected.
