### ISSUE TITLE
Proxy use different port numbers causing iframe sameorigin error

### ISSUE THREAD

**Issue by yunj** [DevExpress/testcafe#6074]
### What is your Test Scenario?
The end to end test is across multiple domains.
 
### What is the Current behavior?
Does TestCafe assign different port number for each domain? If so, the iframe does not work as expected when having different domain.
![image](https://user-images.githubusercontent.com/18545475/112078851-0190c000-8be4-11eb-9100-a31f2cb7b010.png)
 
### Your Environment details:
 
* testcafe version: 1.12.0
* node.js version: 14.15.4
* command-line arguments:
* browser name and version: Chrome 89
* platform and version: Windows 10
* other: Firefox 86 works fine.

**Comment by wentwrong** [comment]
Yes, TestCafe assigns different port numbers to different domains. However, could you please clarify how the code of the iframe looks like? If a page embedded in the iframe sets the 'X-Frame-Options' header to 'sameorigin' and has a different domain, then how it passes the same-origin policy check?
