### ISSUE TITLE
Unable to capture service worker network request

### ISSUE THREAD

**Issue by msherman** [DevExpress/testcafe#6079]
### What is your Test Scenario?
The testcafe process we run inside our pipeline, sometimes has intermittent access to the outside world. Part of this process it makes a call to a CDN and fails the test because the cdn is inaccessible.

To add to the complexity the call to the CDN is inside a service worker, seen here:
![image](https://user-images.githubusercontent.com/136849/112391205-8ef81100-8cc5-11eb-9311-6cf754a577ca.png)

I'd like to mock that get call and return a local version of that file inside the testcafe tests.
 
### What is the Current behavior?
The call goes through to the CDN and I am unable to capture that call using a regex pattern seen here:
https://github.com/msherman/mock-js-source/blob/main/e2e/simple.js#L17 
 
### What is the Expected behavior?
Successfully able to capture the network call made by the service worker.
 
### What is your web application and your TestCafe test code?
The test: https://github.com/msherman/mock-js-source/blob/main/e2e/simple.js
The code to run locally to test: https://github.com/msherman/mock-js-source
 
<details>
<summary>Your website URL (or attach your complete example):</summary>
localhost:4200p-.

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { RequestHook } from 'testcafe';

class MyHook extends RequestHook {
    constructor (requestFilterRules, responseEventConfigureOpts) {
        super(requestFilterRules, responseEventConfigureOpts);
    }

    async onRequest (e) {
        console.log(e.requestOptions.url);
    }

    async onResponse (e) {
    }
}

fixture `Getting Started`
    .requestHooks(new MyHook(/cdn/, {
        logRequestHeaders: true,
        logResponseHeaders: true}))
    .page `localhost:4200`;

test('Mock the CDN', async t => {
    await t
        .typeText('#developer-name', 'John Smith')
        .click('#submit-button');
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```
 Running tests in:
 - Chrome 89.0.4389.90 / macOS 10.15.7

 Getting Started
(node:51260) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 ✖ Mock the CDN

   1) The specified selector does not match any element in the DOM tree.
      
       > | Selector('#developer-name')

      Browser: Chrome 89.0.4389.90 / macOS 10.15.7

         19 |        logResponseHeaders: true}))
         20 |    .page `localhost:4200`;
         21 |
         22 |test('Mock the CDN', async t => {
         23 |    await t
       > 24 |        .typeText('#developer-name', 'John Smith')
         25 |        .click('#submit-button');
         26 |});

         at <anonymous>
      (/Users/mikesherman/Projects/sandbox/mock-js-source/e2e/simple.js:24:10)
         at asyncGeneratorStep
      (/Users/mikesherman/Projects/sandbox/mock-js-source/e2e/simple.js:1:246)
         at _next
      (/Users/mikesherman/Projects/sandbox/mock-js-source/e2e/simple.js:1:584)
         at <anonymous>
      (/Users/mikesherman/Projects/sandbox/mock-js-source/e2e/simple.js:1:749)
         at <anonymous>
      (/Users/mikesherman/Projects/sandbox/mock-js-source/e2e/simple.js:1:490)
         at <anonymous>
      (/Users/mikesherman/Projects/sandbox/mock-js-source/e2e/simple.js:22:5)



 1/1 failed (12s)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! e2e@1.0.0 test: `testcafe chrome simple.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the e2e@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. execute runme.sh from https://github.com/msherman/mock-js-source

To manually execute...
1. clone repo https://github.com/msherman/mock-js-source
2. cd mock-js-app
3. npm i
4. npm start
5. open.a new terminal
6. cd e2e
7. npm i
8. npm run test
 
### Your Environment details:
 
* testcafe version: 1.13.0                  
* node.js version:   14.5.0                 
* command-line arguments:  https://github.com/msherman/mock-js-source/blob/main/e2e/package.json#L11 
* browser name and version: Chrome 89 
* platform and version:         macOS 10.15 
* other:

**Comment by wentwrong** [comment]
Thank you for the example. Seems that the call to the CDN server is originated from the service worker and is made with the help of the following code:
```js
importScripts('https://cdn.jsdelivr.net/npm/pdfjs-dist@2.5.207/es5/build/pdf.worker.js');
```

Currently, the `WorkerGlobalScope.importScripts` method is not proxied by us: [WorkerGlobalScope.importScripts should be overwritten](https://github.com/DevExpress/testcafe-hammerhead/issues/2521), and that's why you can't see the request in `RequestHook`. For now, I recommend you follow that issue so you can get updates on it. I'll close this thread as a duplicate.
