### ISSUE TITLE
Fix typo in the page-unload-barrier

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#608]
https://github.com/DevExpress/testcafe/blob/9950f6bc253b07c0f8e8bed730a2d98f8f5dc74f/src/client/core/page-unload-barrier.js#L42

`e.isFakeIEBeforeUnloadEvent -> e.isFakeIEEvent`

**Comment by georgiy-abbasov** [comment]
I'll do this in the context of https://github.com/DevExpress/testcafe/issues/437

**Comment by georgiy-abbasov** [comment]
We decided to get rid of  ` if (e.isFakeIEEvent)` check. See https://github.com/DevExpress/testcafe/pull/748#issuecomment-244110031
