### ISSUE TITLE
Unable to add a descriptive name to an action

### ISSUE THREAD

**Issue by amitrai99** [DevExpress/testcafe#6081]
### What is your Test Scenario?

I'm using a licensed version of TestCafe Studio and want to record multiple actions. However, i noticed that there is no way to change the default action names like `Click` to something more descriptive like `Click on Submit button` and have it print with the report. 

### What is the Current behavior?

 
- I cannot add custom step description.
- Report does not provide any granularity for each action.

### What is the Expected behavior?

- I should be able to add custom step description.
- Report should provide action level granularity.

 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:  1.11.0                 
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by viktoria2506** [comment]
We reviewed our testing approach a while ago and changed the API: [https://devexpress.github.io/testcafe/faq/#has-testcafe-v20151-been-deprecated](https://devexpress.github.io/testcafe/faq/#has-testcafe-v20151-been-deprecated). We do not plan to return to the concept of named steps anytime soon.
As for the reporter, we are planning to improve it. Thank you for the idea. We will discuss it with the team.

P.S. This repository is for the **Open Source version of TestCafe**. Also, you have the TestCafe Studio Community Subscription license which **includes only the community** support service: [https://www.devexpress.com/products/testcafestudio/#pricing](https://www.devexpress.com/products/testcafestudio/#pricing). It is better to address such inquiries to StackOverflow ([https://stackoverflow.com/questions/ask?tags=testcafe](https://stackoverflow.com/questions/ask?tags=testcafe)) - an amazing platform for users to ask and answer questions.

**Comment by amitrai99** [comment]
> We reviewed our testing approach a while ago and changed the API: https://devexpress.github.io/testcafe/faq/#has-testcafe-v20151-been-deprecated. We do not plan to return to the concept of named steps anytime soon.
> As for the reporter, we are planning to improve it. Thank you for the idea. We will discuss it with the team.
> 
> P.S. This repository is for the Open Source version of TestCafe. Also, you have the TestCafe Studio Community Subscription license which includes only the community support service: https://www.devexpress.com/products/testcafestudio/#pricing. It is better to address such inquiries to StackOverflow (https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.

Do you have any timelines or ticket that can tracks reporter related changes.
It would be awesome if we can have reporters that can print each action's outcome.

**Comment by wentwrong** [comment]
There is a ticket for improving the report so that it contains a description about each executed action: [More verbose output about actions and assertions](https://github.com/DevExpress/testcafe/issues/4001). We can't give any time estimates for its implementation at the moment. Stay tuned to that ticket for updates.
