### ISSUE TITLE
TestCafe hangs when the test switches between windows after switching to iframe

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe#6085]
### What is your Test Scenario?
Switch to another window after switching to iframe
 
### What is the Current behavior?
The test is passed, but it cannot be finished. TestCafe hangs without terminating.
 
### What is the Expected behavior?
The TestCafe process should be finished.
 
### What is your web application and your TestCafe test code?

```js
 fixture `New Fixture`  
    .page `https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe`;

test('Test', async t => {
    const documentation = await t.openWindow('http://devexpress.github.io/testcafe/documentation');

    await t
        .switchToParentWindow()
        .switchToIframe('iframe')
        .switchToWindow(documentation)
        .click('h1');
});
```

### Steps to Reproduce:
Run the test. TestCafe will execute all the steps. However, it will not be finished automatically.

 
### Your Environment details:
 
* testcafe version:                   1.13.0
* node.js version:                    12.19.0
* command-line arguments:  npx testcafe chrome test.js
* browser name and version: Chrome 88
* platform and version:          Win 10

**Comment by thelazurite-cell** [comment]
Hi Dmitry, 

I've come across something like this too while working within iframes. I think as a work around try creating a function to wrap around managing an iframe like this:

```typescript
    public async withinIframe(i: TestController, iframe: Selector, code: () => Promise<void>): Promise<void> {
        let error: Error;

        await i.switchToIframe(iframe);

        try {
            await code().catch(res => error = res);
        } catch (e) {
            error = e;
        }
        await i.switchToMainWindow();

        if (error) {
            throw error;
        }
    }
```

**Comment by viktoria2506** [comment]
Thank you for sharing this workaround. I believe it will be helpful to other users.
