### ISSUE TITLE
Latest version 1.13.0 - npm dependency issues

### ISSUE THREAD

**Issue by langersp** [DevExpress/testcafe#6091]
npm errors are faced when using the latest version of testcafe (as of writing 1.13.0)

I had to add the install the following packages independently to fix:

    "@nodelib/fs.macchiato": "^1.0.3",
    "sinon": "^10.0.0"

**Comment by bbonczek** [comment]
We had a similar issue - one of our dependencies was sharing its dependency with testcafe and we had to add
```
"@types/lodash": "^4.14.119",
```
...and we're even not using lodash. I'd blame it on the library I'm using though - it seems to have its peer dependencies specified in a wrong version.

**Comment by AndreyBelym** [comment]
Especially we need `package.json` and `package-lock.json` if you use it. Please also try to remove your `node_modules` and `package-lock.json`, clean npm cache with `npm cache clean -f` and try to reinstall modules.
