### ISSUE TITLE
Can we use TestCafe engine without the test runner or compiler?

### ISSUE THREAD

**Issue by alshdavid** [DevExpress/testcafe#6092]
I really like TestCafe's engine implementation, using a server to proxy the client page and a ws connection to transmit commands to the page/frames.

I need to control the other parts of the process, such as JavaScript preprocessing, the test runner, linting, etc. Currently TestCafe is an entire testing platform which includes compilation configuration, running, asserions, etc. This makes it difficult to fit into an existing codebase(s) with enforced programming standards, configuration rules and linting expectations.

Giving developers lower level access to the TestCafe engine would allow developers to use TestCafe for a broader range of automation tasks as it integrates with existing environments better and also empowers developers to use the test runner and assertion mechanisms of their choice.

It would also help in scenarios where the TestCafe runner fails but provides no logs or logs with limited useful information as developers would control the environment better, allowing them to identify issues quicker.

I would love to be able to use the TestCafe engine directly and connect to it via a JavaScript library:

# JavaScript API

```javascript
// index.js
const TestCafe = require('testcafe')
const { spawn } = require("child_process")

void async main function(){
  // Create a TestCafe proxy server that can send commands
  const engine = await TestCafe.createEngine({
    url: 'https://google.com'
  })

  // listen to connections to the URL via an observable or callback
  engine.onConnection.subscribe(page => {
    // Send commands to the page 
    page.type('input[title="Search"]', 'TestCafe')
    page.click('input[type="submit"][value="Google Search"]')
  })

  // Launch my browsers of choice asynchronously - chrome, firefox, safari
  // page.url is the local proxy url set up by TestCafe
  spawn('google-chrome', [page.url])
  spawn('firefox', [page.url])
}()
```

Then I would run
```bash
node index.js
```

# Terminal + Remote node client connection

It's necessary to have a remote client engine connection capability for TestCafe engines setup externally of the current node process. 

A case for this is if the TestCafe engine is set up on the CLI and the node process is started after, or if the TestCafe engine is set up on a different node process and we need to connect to the same engine instance (such as with Jest using multiple workers)

```bash
npx testcafe --engine-only --url https://google.com
# Testcafe engine running on port 1337
```

```javascript
// index.js
const TestCafe = require('testcafe')
const { spawn } = require("child_process")

void async main function(){
  // Connect to a TestCafe proxy server that can send commands
  const engine = await TestCafe.createEngine({
    remoteEngineUrl: 'http://localhost:1337'
  })

  // rest of file is the same as above
}()
```

Then, in a seperate terminal, I would run
```bash
node index.js
```

**Comment by felis2803** [comment]
Thanks for the idea. We will consider your suggestion.

**Comment by alshdavid** [comment]
Thank you for considering this. 

I would like to stress that I really like the approach TestCafe takes in how it provides a portable solution for automated browser testing - this alone makes it more powerful than cypress, puppeteer and playwright. The simplicity of the approach makes it more powerful than selenium. Using `remote` control via a URL allows for simple testing through docker containers, remote environments and is honestly the best solution I have come across.

However where it falls short is being too high level to the point where it can become counterproductive.

As an example, I just spent 4 days debugging an issue where a test was simply hanging. The testcafe runner presented no output logs, no debugging information and I had no way of know what was wrong.

Of course, I could have raised a GitHub issue asking for advice on how to approach this and potentially looking for ways to improve the test runner - but test runners are a problem that have been solved well in the past.

If the test runner was separate to the browser control engine, I would have found that issue quicker because it wouldn't have cared that the browser control engine was failing, only that a certain test timed out. This would have led me to the problem immediately. 

Instead I started looking at the bash scripts ahead of the test runner, falsely thinking it never got to the point where it was running. Eventually I found out it was hanging, and without knowing how to do any remote debugging, I littered my tests with `console.log(1)` `console.log(2)` to find out where it hangs.

Additionally, because the runner doesn't enforce code standards, our QA team wrote TypeScript, JavaScript with modules and JavaScript using commonjs. It was a nightmare to dig through. If the compilation environment was in our control, the QA team wouldn't have been able to write anything other than TypeScript.

And lastly, what if I just want to use TestCafe to do some simple web scraping/automation tasks? Right now it's positioned as explicitly a platform for browser testing.

There are real world cases for giving us lower level control and they would be immensely powerful.

**Comment by felis2803** [comment]
Hello David,

Thank you for your positive feedback on our product.

Our [hammerhead](https://github.com/DevExpress/testcafe-hammerhead) proxy server seems to me to be able to cover most of your needs.

Now it is not very clear to me exactly how and for what purpose you want to use TestCafe's engine, therefore I can give only general recommendations:
- clone and run hammerhead as described in [readme.md](https://github.com/DevExpress/testcafe-hammerhead/blob/master/README.md);
- see how we use hammerhead sessions and inject scripts into the client:

https://github.com/DevExpress/testcafe/blob/38fa4d96a7a8a000ea5a929551747ad2c33670dd/src/test-run/index.js#L107
 
https://github.com/DevExpress/testcafe/blob/38fa4d96a7a8a000ea5a929551747ad2c33670dd/src/test-run/index.js#L147

https://github.com/DevExpress/testcafe/blob/38fa4d96a7a8a000ea5a929551747ad2c33670dd/src/test-run/index.js#L179
 
https://github.com/DevExpress/testcafe/blob/38fa4d96a7a8a000ea5a929551747ad2c33670dd/src/assets/injectables.js#L7

https://github.com/DevExpress/testcafe/blob/38fa4d96a7a8a000ea5a929551747ad2c33670dd/src/test-run/session-controller.js#L9

- and how we access [hammerhead](https://github.com/DevExpress/testcafe-hammerhead) functions from client scripts:

https://github.com/DevExpress/testcafe/blob/38fa4d96a7a8a000ea5a929551747ad2c33670dd/src/client/driver/driver.js#L102

Could you tell us more about the non-testing tasks for which you want to use TestCafe?
