### ISSUE TITLE
Digitally signed executables 

### ISSUE THREAD

**Issue by evryzou** [DevExpress/testcafe#6095]
Hi there!

I am an employee of a large financial institution that is extensibly using TestCafe across many teams. As a result of a recent direction to mandate the upgrade of the MAC OS workstations to Big Sur, we have run into an issue using TestCafe version 1.13.0.

Prior to the OS upgrade, we did not experience this issue. However, TestCafe relies on enabling the screen recording privacy settings under privacy in the preferences - this feature requires admin access to be enabled as part of the our company policy.

To that effect, I have been advised to seek digitally signed executables that confirm the software author and guarantee that the code has not been altered or corrupted since it was signed! Is this something you can help me with?

Urgent help needed!!

Thanks,. Evry

**Comment by aleks-pro** [comment]
Hello,

TestCafe is an npm package. npm adds the PGP signature to package metadata. So, you can verify an npm package by using the package PGP signature and npm's public PGP key. For more information, please refer to the following topics in npm documentation:
[About package PGP signatures](https://docs.npmjs.com/about-pgp-signatures-for-packages-in-the-public-registry)
[Verifying the PGP signature of a package from the npm public registry](https://docs.npmjs.com/verifying-the-pgp-signature-for-a-package-from-the-npm-public-registry)
