### ISSUE TITLE
Test Frequently Lose Connected (EPIPE error)

### ISSUE THREAD

**Issue by qualityshepherd** [DevExpress/testcafe#6106]
I've been seeing this occasionally and now almost every time I run all my tests (~50) against our staging environment. After a _lot_ of debugging, I discovered the issue is with all recent versions of Testcafe and Node lts versions > 8.17.0. Same tests fail on v10 & v12. 

I've not been able to find _sharable_ test code that reproduces the problem _yet_. I'll update if I can... I see a similar issue has been reported previously (#1647). 

I'm running Testcafe 1.8.2; Chrome 80.0.3987.122; macOS 10.14.6 but I've also seen this issue (less frequently) from our Linux CI server. 

```
1 Uncaught exception:

  Error: write EPIPE
  at afterWriteDispatched (internal/stream_base_commons.js:154:25)
  at writeGeneric (internal/stream_base_commons.js:145:3)
  at Socket._writeGeneric (net.js:780:11)
  at Socket._write (net.js:792:8)
  at doWrite (_stream_writable.js:441:12)
  at writeOrBuffer (_stream_writable.js:425:5)
  at Socket.Writable.write (_stream_writable.js:316:11)
  at TLSSocket.ondata (_stream_readable.js:714:22)
  at TLSSocket.emit (events.js:311:20)
  at TLSSocket.EventEmitter.emit (domain.js:505:15)

  Browser: Chrome 80.0.3987.122 / macOS 10.14.6
```

**Comment by rmkranack** [comment]
> @rmkranack, I tried to reproduce the issue on pages that have both the '#/info' fragment and the message in the developer console, but in my case everything works fine - seems that it's not the original cause. Could you please share a reproducible example (the code of the failed test which we can run and see the error)?

I sent the code via email. 
Thanks

**Comment by Farfurix** [comment]
@rmkranack 

Hello,

I don't see any emails from you in our mailbox (support@devexpress.com). Could you please send it again?

**Comment by rmkranack** [comment]
Hello,

Thank you for your help. Here is a link to the files on Google Drive.
https://drive.google.com/drive/folders/1ITg6lBbzd24xSc8QhxGdz4_CLBv3FM_R?usp=sharing

Let me know if you need anything else. This is the command I am running
when I encounter the error " testcafe chrome
tests/src/e2e/Register/Register.js --env='dev' ". If I run the tests one at
a time, they pass.

**Comment by Farfurix** [comment]
@rmkranack 

Hello,

I wasn't able to reproduce the issue using the information you shared. Could you please clarify if the issue can be reproduced without the login procedure? You use an environment variable to store your password (`const patientPassword = process.env.PATIENT_PASSWORD;`), and of course I don't have it.

If the login procedure is necessary, we need written confirmation and all required authentication data (login, password). Since your website ([https://dev.seqster.com/register#/](https://dev.seqster.com/register#/)) sits behind a proxy and requires authentication, I will not be able to access it. Our policy prevents us from accessing a customer’s internal resources without prior written approval from the entity that owns the server/web resource.

If you want us to research the problem further, we’ll need access to the server/web resource. Please ask the website owner to send us ([support@devexpress.com](mailto:support@devexpress.com)) written confirmation. It must permit DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes.

**Comment by rmkranack** [comment]
Hello,

The environment variable is used for the password to create new members. It
could be a generic password such as PATIENT_PASSWORD=Password123!

Login is not necessary to access our qa site.
https://dev.seqster.com/register#/ is our qa site and is not behind a
proxy.

Thanks,
Robert

**Comment by Farfurix** [comment]
@rmkranack 

Hello,

I cannot reproduce this issue with TestCafe 1.14.0:
```
>testcafe chrome tests/src/e2e/Register/Register.js --env='dev'
 Running tests in:
 - Chrome 89.0.4389.114 / Windows 10

 Register
 √ Register_Signup | C24
 √ Register_Splash_Continue | C37
 √ GetStarted_Continue | C38
 √ GetStartedMore_Continue | C41
 √ GetStarted_AddAccount_No  | C43
 √ GetStarted_AddAccount_Yes  | C42
 √ GetStarted_AddAccount_Yes_TellMore_Cancel  | C45
 √ GetStarted_AddAccount_Yes_TellMore_Continue  | C44
 √ GetStarted_AddAccount_Yes_TellMore2_Continue  | C46


 9 passed (3m 09s)

```
```
>testcafe "saucelabs:Chrome@88.0:macOS 10.15" tests/src/e2e/Register/Register.js --env='dev'
 Running tests in:
 - Chrome 88.0.4324.96 / macOS 10.15.4 (https://app.saucelabs.com/tests/db88b14d7bc44f1b96bc9598ba307ae5)

 Register
 √ Register_Signup | C24
 √ Register_Splash_Continue | C37
 √ GetStarted_Continue | C38
 √ GetStartedMore_Continue | C41
 √ GetStarted_AddAccount_No  | C43
 √ GetStarted_AddAccount_Yes  | C42
 √ GetStarted_AddAccount_Yes_TellMore_Cancel  | C45
 √ GetStarted_AddAccount_Yes_TellMore_Continue  | C44
 √ GetStarted_AddAccount_Yes_TellMore2_Continue  | C46


 9 passed (7m 36s)

```

My setup: TestCafe 1.14.0, Chrome, Windows 10/macOS 10.15. Please check your scenario with the latest TestCafe version.

**Comment by rmkranack** [comment]
I tried again on 2 different macbooks and still have the same issue. They
are both running TestCafe 1.14.0. The tests pass on Firefox 88.0b8.

Macbook1 - ios 11.2.2, Chrome 89.0.4389.128, Node 13.12.0
Macbook2 - ios 10.15.7, Chrome 89.0.4389.128, Node 15.11.0

Here is one error I get:

✖ Register | Register_Splash_Continue | C37

   1) Uncaught exception:

      Error: write EPIPE
      at afterWriteDispatched (node:internal/stream_base_commons:160:15)
      at writeGeneric (node:internal/stream_base_commons:151:3)
      at Socket._writeGeneric (node:net:773:11)
      at Socket._write (node:net:785:8)
      at writeOrBuffer (node:internal/streams/writable:395:12)
      at Socket.Writable.write (node:internal/streams/writable:340:10)
      at TLSSocket.ondata (node:internal/streams/readable:750:22)
      at TLSSocket.emit (node:events:378:20)
      at TLSSocket.EventEmitter.emit (node:domain:532:15)
      at addChunk (node:internal/streams/readable:313:12)

      Browser: Chrome 89.0.4389.128 / macOS 10.15.7

**Comment by Farfurix** [comment]
@rmkranack 

Hello,

I still cannot reproduce the issue. I used a virtual Catalina machine and a real Big Sur Mac mini. So, I will close this issue. Feel free to open a new one with an example that can be reproduced on our side.
![mac-test](https://user-images.githubusercontent.com/30019338/114994077-15f37000-9ea5-11eb-8dda-a477026d5613.PNG)
![mac-test-big-sur](https://user-images.githubusercontent.com/30019338/114994081-17249d00-9ea5-11eb-8d04-838cd7238c8f.jpg)

**Comment by jbradenclickfunnels** [comment]
I am also getting this error when running my test suite.
TestCafe: 1.15.2
Node: 14.18.0
npm: 6.14.15
OS: MacOS Big Sur 11.6
Concurrency: 7

1) - Error in fixture.beforeEach hook -
      Uncaught exception:

      Error: write EPIPE
      at afterWriteDispatched (internal/stream_base_commons.js:156:25)
      at writeGeneric (internal/stream_base_commons.js:147:3)
      at Socket._writeGeneric (net.js:798:11)
      at Socket._write (net.js:810:8)
      at writeOrBuffer (internal/streams/writable.js:358:12)
      at Socket.Writable.write (internal/streams/writable.js:303:10)
      at TLSSocket.ondata (internal/streams/readable.js:731:22)
      at TLSSocket.emit (events.js:400:28)
      at TLSSocket.emit (domain.js:537:15)
      at addChunk (internal/streams/readable.js:293:12)

      Browser: Chrome 94.0.4606.71 / macOS 10.15.7

My .beforeEach is a login method that uses hardcoded data to login:

.beforeEach(async t => {
    await LoginPageObjects.login_with_password(data.users.account_owner.user_email, data.users.account_owner.user_password)
