### ISSUE TITLE
t.getAllWindows method would be useful

### ISSUE THREAD

**Issue by Ivan-Katovich** [DevExpress/testcafe#6108]
### What is your Test Scenario?
import { Selector, ClientFunction } from 'testcafe';

fixture `Test page`
    .page('https://devexpress.github.io/testcafe/example/');

test('Open a new window', async t => {
    const allWindowsArray1 = await t.getAllWindos();
    await t.openWindow('http://example.com');
    const allWindowsArray2 = await t.getAllWindos();
    await t.expect(allWindowsArray1.length).lt(allWindowsArray2.length);
});

### What are you suggesting?
Can you introduce something like that cause only one possibility to access full array of windows is t.switchToWindow(predicate); where we can filter windows. 

### What alternatives have you considered?
t.switchToWindow(predicate); 

### Additional context
It would be a good supporting function for multiple windows usability

**Comment by viktoria2506** [comment]
Thanks for your suggestion.
