### ISSUE TITLE
incorrect behavior for "enter" key using t.PressKey() method

### ISSUE THREAD

**Issue by spencekim** [DevExpress/testcafe#6110]
### What is your Test Scenario?

When the cursor is within a bullet list item, pressing the enter key creates a new bullet list item directly below and moves the selection to the front of the new bullet list item. 

This is standard behavior for nested lists. We are using standard <ul and <li html elements.
 
### What is the Current behavior?

When pressing the enter key manually within the testCafe browser, the behavior works as expected. 
However, when using the method t.pressKey('enter'), the state changes to:

Before:
![Screen Shot 2021-04-02 at 9 41 45 AM](https://user-images.githubusercontent.com/19200359/113448705-0bf74a80-9398-11eb-86ce-ededa862aa55.png)

After:
![Screen Shot 2021-04-02 at 9 42 20 AM](https://user-images.githubusercontent.com/19200359/113448721-144f8580-9398-11eb-82cd-06c6c1577d31.png)

### What is the Expected behavior?

After:
![Screen Shot 2021-04-02 at 9 41 49 AM](https://user-images.githubusercontent.com/19200359/113448759-24676500-9398-11eb-817f-52544beb7f6d.png)

### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

### Your Environment details:
 
testcafe version: 1.10
node.js version: v14.0.0
command-line arguments: none
browser name and version: chrome 87
platform and version: MacOS 10.14

**Comment by Farfurix** [comment]
@spencekim 

Hello,

Could you please check your scenario with the latest TestCafe version (v1.13.0)? If the issue persists, please share a reproducible example with us. Our team will examine your case.

**Comment by spencekim** [comment]
@Farfurix the issue still persists with version v1.13.0

**Comment by Farfurix** [comment]
@spencekim 

Hello,

I don't see a reproducible example in [your post](https://github.com/DevExpress/testcafe/issues/6110#issue-849432707). Please share a complete example that we can run on our side.

**Comment by spencekim** [comment]
Does this work?

<img width="1010" alt="Screen Shot 2021-04-12 at 9 44 54 AM" src="https://user-images.githubusercontent.com/19200359/114452099-c3981380-9b73-11eb-8173-c3f8aa05f1e6.png">

**Comment by viktoria2506** [comment]
I cannot reproduce the issue locally because your example does not contain a site to run the test.
[https://devexpress.github.io/testcafe/documentation/guides/basic-guides/organize-tests.html#specify-the-start-webpage](https://devexpress.github.io/testcafe/documentation/guides/basic-guides/organize-tests.html#specify-the-start-webpage)
Please share a complete example with your website URL (or an example of your application) that we can run locally.
