### ISSUE TITLE
NavigateTo action should be considered as a top window command

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#6113]
This does not match the way browsers work.

### What is your Test Scenario?
```js
fixture `fixture`
    .page `http://test`;

test('t', async t => {
    await t
        .switchToIframe('iframe')
        .navigateTo('http://google.com');

//iframe's window will be redirected to a new url instead of the top window
})
```

### What are you suggesting?
The `isExecutableInTopWindowOnly` method should return true for the `navigateTo` command 

### Additional context
Based on Becci Watson feedback

**Comment by thelazurite-cell** [comment]
This would be a great addition. I have worked around it with this method in the past:
https://github.com/DevExpress/testcafe/issues/6085#issuecomment-811800194
