### ISSUE TITLE
 Support InputDeviceCapabilities

### ISSUE THREAD

**Issue by scribetw** [DevExpress/testcafe#6114]
### What is your Test Scenario?

I want to use the [InputDeviceCapabilities](https://developers.google.com/web/updates/2015/10/inputdevicecapabilities) introduced since Chrome 47, and I included the polyfill js for unsupported browsers.

I know it's still not standardized yet, but how do I do to let TestCafe use it correctly? 
 
### What is the Current behavior?

It prints `null`.
 
### What is the Expected behavior?

It prints `[object InputDeviceCapabilities]`
 
### What is your web application and your TestCafe test code?

[sourceCapabilitiesTestcase.zip](https://github.com/DevExpress/testcafe/files/6262125/sourceCapabilitiesTestcase.zip)
<details>
<summary>Your website URL (or attach your complete example):</summary>

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test sourceCapabilities</title>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/gh/WICG/input-device-capabilities@gh-pages/inputdevicecapabilities-polyfill.js"></script>
</head>
<body>
    <button id="btnTest">
        Click me
    </button>
    <div id="result">
    </div>
    <script type="text/javascript">
    var btnTest = document.getElementById('btnTest'),
        result = document.getElementById('result');
    btnTest.addEventListener('click', e => {
        var sourceCapabilities = e.sourceCapabilities;
        console.log(sourceCapabilities);
        result.innerText += sourceCapabilities + "\n";
    });
    </script>
</body>
</html>
```
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
import { Selector } from 'testcafe';

fixture `sourceCapabilities`
    .page('./index.html');

test('test UIEvent.sourceCapabilities', async t => {
    await t.click('#btnTest')
        .expect(Selector('#result').innerText)
        .notContains('null');
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```
$ npm test                  

> sourcecapabilitiestestcase@1.0.0 test /Users/rudyhuang/IdeaProjects/sourceCapabilitiesTestcase
> testcafe chrome test.js

 Running tests in:
 - Chrome 89.0.4389.114 / macOS 10.15.6

 sourceCapabilities
 ✖ test UIEvent.sourceCapabilities

   1) AssertionError: expected 'null\n' to not include 'null'
      
      + expected - actual
      
      -'null\n'
      +undefined
      

      Browser: Chrome 89.0.4389.114 / macOS 10.15.6

          4 |    .page('./index.html');
          5 |
          6 |test('test UIEvent.sourceCapabilities', async t => {
          7 |    await t.click('#btnTest')
          8 |        .expect(Selector('#result').innerText)
       >  9 |        .notContains('null');
         10 |});
         11 |
         12 |

         at <anonymous> (/Users/rudyhuang/IdeaProjects/sourceCapabilitiesTestcase/test.js:9:10)
         at asyncGeneratorStep (/Users/rudyhuang/IdeaProjects/sourceCapabilitiesTestcase/test.js:1:248)
         at _next (/Users/rudyhuang/IdeaProjects/sourceCapabilitiesTestcase/test.js:1:586)
         at <anonymous> (/Users/rudyhuang/IdeaProjects/sourceCapabilitiesTestcase/test.js:1:751)
         at <anonymous> (/Users/rudyhuang/IdeaProjects/sourceCapabilitiesTestcase/test.js:1:492)
         at <anonymous> (/Users/rudyhuang/IdeaProjects/sourceCapabilitiesTestcase/test.js:6:5)



 1/1 failed (4s)
npm ERR! Test failed.  See above for more details.
```
</details>

<details>
<summary>Screenshots:</summary>

TestCafe:

![testcafe](https://user-images.githubusercontent.com/6398934/113659765-4f71f180-96d5-11eb-83e0-2150c7b18e51.png)

Real Chrome:

![real](https://user-images.githubusercontent.com/6398934/113659777-57319600-96d5-11eb-95d3-5b22ec6da6a6.png)
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version: 1.13.0                  
* node.js version: v14.15.0                   
* command-line arguments: testcafe chrome test.js 
* browser name and version: Chrome Version 89.0.4389.114 (Official Build) (x86_64) 
* platform and version: macOS 10.15.6         
* other:

**Comment by AlexanderMoiseev** [comment]
Hello, 

At this moment, this functionality is not supported and we cannot give you any workaround. Please keep track of the issue to stay tuned.
