### ISSUE TITLE
TestCafe hangs on obtaining the 'form' element's attributes

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe#6117]
See the following SC ticket for details: https://supportcenter.devexpress.com/internal/ticket/details/T987924 for details.

The test specified in this ticket hangs when the following code line is executed:

`var ff2 = await Selector('form').attributes;`

**Comment by AlexKamaev** [comment]
fixed in https://github.com/DevExpress/testcafe-hammerhead/pull/2629
