### ISSUE TITLE
Let's rename elementTimeout and elementAvailabilityTimeout to selectorTimeout

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#612]
\cc @VasilyStrelyaev @helen-dikareva @AlexanderMoskovkin

**Comment by VasilyStrelyaev** [comment]
Good idea! I'm totally ok with that.

**Comment by helen-dikareva** [comment]
We use `elementAvailabilityTimeout` also for waiting for establishment connection with child driver link (during `switchToIframe` command https://github.com/DevExpress/testcafe/blob/master/src/client/driver/driver.js#L203) and for waiting for browser dialog during `hadleAlert` (and etc.) command

**Comment by inikulin** [comment]
Well, for iframe it's still a selector. For browser dialogs - it's wrong, because browser dialog is not an element

**Comment by helen-dikareva** [comment]
Do we need tunable timeout for dialogs?

**Comment by inikulin** [comment]
Well, I guess so, but I think as `timeout` option for the appropriate functions.

**Comment by inikulin** [comment]
Not sure if we need global option for this, since unlike selectors this is something that you will not use very often.

**Comment by AlexanderMoskovkin** [comment]
I'm agree with that all
