### ISSUE TITLE
Don't stop a test on failure, instead log it and continue

### ISSUE THREAD

**Issue by Akshay-Kawlay** [DevExpress/testcafe#6129]
### What is your Test Scenario?
Currently for a test, when it encounter's an error, it fails and stops and starts running next test in the test suite

### What are you suggesting?
On failure of a test, don't end that test. Instead log the failure and continue running the test until completion or until some predefined timeout

### What alternatives have you considered?
I was thinking of creating an interrupt handler for test failures but not sure where to add that in testcafe code.
Also, if this is a big request, could you please let me know where in testcafe code I can make changes so it ignores stopping on test failures altogether and instead logs it?

### Additional context
This feature is useful when working with a non-deterministic/randomized program where it is impossible to get rid of all errors/failures but instead the goal is to measure total number of failures seen in a given time. So, we can use this info to guide the development to reduce the total failures seen per unit time.

**Comment by Dmitry-Ostashev** [comment]
Hello @Akshay-Kawlay,
Thank you for your suggestion.

This task looks complex. Besides, we are not sure that many people really need this feature.
The simplest way to do it in the test is to wrap a particular step with `try ... catch` and log the error.

**Comment by Dmitry-Ostashev** [comment]
After the test fails at a certain step, your page may end up in the undetermined state, so further checks may be useless. Could you please describe in greater detail for what cases and errors you need to skip failures? This information will help us in our discussion of this feature.

**Comment by Akshay-Kawlay** [comment]
Hello, sorry for the late response. I tried a custom built testcafe workaround for this by increasing the QUARANTINE_THRESHOLD and DISCONNECT_THRESHOLD to a big value like a million however testcafe still quits after like 1000 restarts with this error : `ERROR The Chrome 89.0.4389.90 / Linux 0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.`

Is there something else that causes this error and forces testcafe to stop?
Thanks in advance!

**Comment by AlexKamaev** [comment]
duplicated in 
https://github.com/DevExpress/testcafe/issues/6246 
and 
https://stackoverflow.com/questions/67660525/manually-setting-quarantine-threshold-and-disconnect-threshold-in-testcafe-does/67683650#67683650
