### ISSUE TITLE
Plaid login issue with Testcafe >= v.1.11.0

### ISSUE THREAD

**Issue by george-vrancianu** [DevExpress/testcafe#6134]
After upgrading from Testcafe v1.3.0 to v1.11.0, our E2E started to fail when testing Plaid integration.

### What is your Test Scenario?
Testing Plaid (https://plaid.com/) login and linking an account to a bank.

### What is the Current behavior?
Page's DOM goes blank after going through an authentification.  

### What is the Expected behavior?
Page's DOM should not go blank. When testing with Testcafe v.1.3.0 up to v.1.10.0, this does not happen
 
### What is your web application and your TestCafe test code?
Attached an app with a frontend and a node backend to reproduce this issue using a Plaid sandbox account.
 
<details>
<summary>Complete example attached</summary>
[plaid-testcafe.zip](https://github.com/DevExpress/testcafe/files/6305064/plaid-testcafe.zip)

Please check the README file on how to run the frontend, backend and the test. The example is fairly easy and should work on any machine.
</details>

### Steps to Reproduce:

1. Click on "Launch Link"

![Screenshot 2021-04-13 at 18 36 42](https://user-images.githubusercontent.com/9293870/114583128-f2a0a900-9c89-11eb-8d13-4fefdff23e5a.png)

2. Click on "Continue"

![Screenshot 2021-04-13 at 18 36 49](https://user-images.githubusercontent.com/9293870/114583145-f6ccc680-9c89-11eb-8db6-17f49a51d270.png)

3. Choose "Chase bank" option

![Screenshot 2021-04-13 at 18 37 01](https://user-images.githubusercontent.com/9293870/114583153-f9c7b700-9c89-11eb-92c8-81974ee1a90f.png)

4. Enter login: user_good/pass_good. Click "Submit".

![Screenshot 2021-04-13 at 18 37 14](https://user-images.githubusercontent.com/9293870/114583165-fc2a1100-9c89-11eb-973b-0bc1635f804e.png)

5. Success page looks something like this, but the DOM is just `<html><head></head><body></body></html>`
 
![Screenshot 2021-04-13 at 18 37 42](https://user-images.githubusercontent.com/9293870/114583181-02b88880-9c8a-11eb-83dc-929462efa9e6.png)

### Your Environment details:
 
* testcafe version:                   1.14.0
* node.js version:                    14.15.4
* command-line arguments:  testcafe chrome e2e/tests/test.js --hostname localhost
* browser name and version:  Chrome 89
* platform and version:          macOS 10.15.7

**Comment by george-vrancianu** [comment]
Mentioning this bug reproduces also with the latest Testcafe version 1.14.0.

**Comment by VasilyStrelyaev** [comment]
Thank you for providing the example. I have reproduced the described behavior. We will investigate this issue.

**Comment by aloklal** [comment]
Any updates @VasilyStrelyaev?  Has a fix gone out in a new version of Test Cafe?

**Comment by george-vrancianu** [comment]
Mentioning that someone on the team found a workaround.
When the html DOM goes blank, insert this:

`await t.closeWindow();`
`await t.switchToIframe('#plaid-link-iframe-1');`

Probably there was an empty popup that was being opened. Doing a closeWindow and then switching back to the iframe seems to fix it for now. 
I hope this helps.

**Comment by Farfurix** [comment]
@george-vrancianu 

Hello,

Thank you for the workaround. Note that you can [disable Multiple Windows](https://testcafe.io/documentation/402841/guides/advanced-guides/multiple-browser-windows) if you don't need it in your test. This should fix this issue.
