### ISSUE TITLE
Allow executing part of the test in currently opened browser

### ISSUE THREAD

**Issue by Evilweed** [DevExpress/testcafe#6135]
### What is your Test Scenario?
TestCafe and Cypress are often rejected as test frameworks because it takes more time to write tests/check if new parts work. Right now you need to run the whole test (and in some companies one E2E test can run for >4 min). Every time you add new part to the test, you need to run it, wait 4 mins, see it fail at the end, and then proceed with updates.

### What are you suggesting?
Allow running part of the TestCafe test in currently opened browser. User can open chrome, go to the page that he is now scripting in TestCafe. Attach test cafe to the browser, and execute newly added part of test, instantly, and iterate on it on real browser very fast.

Below showing exactly this feature in other testing tool:
![Executing in opened browser](https://miro.medium.com/max/1400/0*cJptTh8oR9FbGeb3 "Executing in opened browser")
[https://github.com/testwisely/agiletravel-ui-tests/blob/master/selenium-webdriver-rspec/test_helper.rb](https://github.com/testwisely/agiletravel-ui-tests/blob/master/selenium-webdriver-rspec/test_helper.rb)

### What alternatives have you considered?
- I don't think there is any other feature in TestCafe that would speed up test creation with proper Page Object pattern

**Comment by Dmitry-Ostashev** [comment]
Thank you for the interesting suggestion. Have you tried TestCafe [Live Mode](https://devexpress.github.io/testcafe/documentation/guides/basic-guides/run-tests.html#live-mode)? It is pretty close to the feature you described.

**Comment by Evilweed** [comment]
@Dmitry-Ostashev ofcourse I tried those! And they are not something that is enterprise grade/ready. (by the way, Livemode does not always work - so we have completely stopped using it)

If You test your app, that is not a simple to-do list but a complicated and big app or collections of apps, then you can end up with for example 200 tests where longest ones take for example 5-6 min to run. Imagine you change implementation and now need to quickly update 20 tests that take 5 min to run. After each small change at 4th minute, you need to run the test and wait 4 mins to see result, and then again and again. This is why modern frameworks add "run in current browser", "self healing Selectors" or other features that speed up fixing broken tests, or writing new ones.

Modern features like that allow your framework to completely change the experience and speed.

**Comment by VasilyStrelyaev** [comment]
Thank you for the explanation. We will consider implementing this feature in the future.
