### ISSUE TITLE
Slow performance for heavy data crunching in a worker

### ISSUE THREAD

**Issue by kmannislands** [DevExpress/testcafe#6136]
### What is your Test Scenario?
I'm trying to write testcafe e2e tests for a fairly data-intensive react/three.js application.

We use web workers heavily to smooth out data loading and crunching.
 
### What is the Current behavior?
A certain step in loading our application takes 15s without testcafe/hammerhead. Running locally, it takes upwards of 10 minutes. Running in our CI environment where we record videos, this can run over an hour and eventually time out.
 
### What is the Expected behavior?
Less overhead!
 
### What is your web application and your TestCafe test code?
I've profiled this and most of the overhead seems to come from hammerhead instrumentation in one of our web workers.

In this worker, we run the marching cubes method from this library: https://github.com/gl-vis/gl-isosurface3d#readme reapeatedly. ~400 times.

As mentioned, in the worker this generally isn't a show stopper. I'm observing 50-80ms per geometry we create in plain chrome. In testcafe, this takes ~1000ms per iteration which adds up.

I can't share my application but the library has some public demos like this: https://gl-vis.github.io/gl-isosurface3d/surface_points.html

I've tested this example in the hammerhead playground and it is significantly slower than plain chrome, roughly in line with the ~10x slowdown I've observed in my application. Their public examples aren't as heavy as my use-case so hard to observe anything as drastic as what I'm reporting.

Reading through the instrumented code from hammerhead, the `__get$` and `__set$` shims seem like a likely source of the overhead? Not sure on this yet.

Is there a way to prevent hammerhead instrumentation for a single worker or resource in testcafe? Thanks in advance.
 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
    "src": ["test-cafe/*e2e*.ts", "test-cafe/**/*e2e*.ts"],
    "reporter": [
        {
            "name": "spec"
        },
        {
            "name": "xunit",
            "output": "./dist/artifacts/reports/report.xml"
        }
    ],
    "videoPath": "./dist/artifacts/videos",
    "videoOptions": {
        "singleFile": false,
        "pathPattern": "XXX-${TEST_INDEX}-${FILE_INDEX}-${FIXTURE}-${TEST}-${BROWSER}.mp4"
    },
    "screenshots": {
        "path": "./dist/artifacts/screenshots",
        "takeOnFails": true
    }
}

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version: 1.14.0                  
* node.js version:  v12.18.4                  
* command-line arguments:  N/A 
* browser name and version: Chrome  89.0.4389.114 
* platform and version: MacOs 10.15.7. Reproducable on debian.         
* other: WebWorkers are involved. Comlink is used as RPC but I didn't observe too much overhead in worker communication

**Comment by kmannislands** [comment]
Please let me know if it's more appropriate to open this ticket against hammerhead itself. Thanks in advance.

**Comment by VasilyStrelyaev** [comment]
Thank you for reporting the issue. I have reproduced it on the example page you provided. We will investigate this case.

**Comment by jacobdr** [comment]
Sorry to bug you @VasilyStrelyaev but do you have any sense of where this issue stands in the backlog?
