### ISSUE TITLE
Configuration of test suites with environment variable files

### ISSUE THREAD

**Issue by rehael** [DevExpress/testcafe#6143]
### What is your Test Scenario?

I want to have my test suites use different variables in tests depending which environment (dev, test, uat, production, etc) I am working on in my CI/CD pipeline.

### What are you suggesting?

For anyone having trouble of making the tests suites configurable – working on ideas presented here:

- https://devexpress.github.io/testcafe/documentation/recipes/best-practices/create-helpers.html
- https://devexpress.github.io/testcafe/documentation/recipes/best-practices/create-data-driven-tests.html
- https://devexpress.github.io/testcafe/documentation/recipes/configuration/access-environment-variables-in-tests.html

I created minimal working example of such approach – https://github.com/rehael/testcafe-config-example – this (UNLICENSED, just take it and enjoy) solution helps with making test suites configurable with variables specified in external file driven by environmental variable. There are many other ways one can do it, but if it can help anyone – enjoy.

Dear TestCafé developers – if you'd like to include this example somewhere (or even copy-paste pieces of it into docs or testcafe-examples) – it'd be cool. It's unlicensed, I don't need attribution.

### What alternatives have you considered?

There are many other approached one can take – but thanks to TestCafé not being strongly opinionated, we can roll with whatever approach we want – so thank you for making TestCafé so flexible! ❤

### Additional context

Previously discussed in: #5983, #3428

**Comment by VasilyStrelyaev** [comment]
Thank you! We will consider the possibility of implementing it in the future.

**Comment by lucky36999** [comment]
Any further news on this please

**Comment by felis2803** [comment]
Currently, we do not see much interest in this feature from the TestCafe community. Therefore, we are not ready to implement it. If this feature is important to you, you can try to implement it yourself.
