### ISSUE TITLE
npm package does not match github

### ISSUE THREAD

**Issue by Asher-** [DevExpress/testcafe#6149]
urix and resolve-url are reported deprecated because testcafe-hammerhead is being installed at 21.0.0 instead of 24.1.0.

This is because https://github.com/DevExpress/testcafe/blob/master/package.json for 1.14.0 contains "testcafe-hammerhead": "24.1.0" (correct) but npm package.json for 1.14.0 contains "testcafe-hammerhead": "21.0.0", which results in old packages.

Why is the npm package out of sync with github?

### Steps to Reproduce:

npm install testcafe

[asher:Zero] [12:47:12] [Sat Apr 17] [~/Projects/js/wtf/node_modules] 
∴ npm list urix
wtf@1.0.0 /Users/asher/Projects/js/wtf
├─┬ css@2.2.3 extraneous
│ └── urix@0.1.0 deduped
├─┬ source-map-resolve@0.5.3 extraneous
│ └── urix@0.1.0 deduped
├─┬ testcafe@1.14.0
│ └─┬ testcafe-hammerhead@21.0.0
│   └─┬ css@2.2.3
│     ├─┬ source-map-resolve@0.5.3
│     │ └── urix@0.1.0 deduped
│     └── urix@0.1.0
└── urix@0.1.0 extraneous

**Comment by Farfurix** [comment]
@Asher- 

Hello,

TestCafe uses a fixed version of `testcafe-hammerhead`. [The `testcafe@1.14.0` version was published with `testcafe-hammerhead@21.0.0`](https://github.com/DevExpress/testcafe/blob/v1.14.0/package.json#L132). [Here](https://github.com/DevExpress/testcafe/blob/master/package.json#L132) you can see the current state of the main branch. This does not mean that these changes were published to npm - the latest changes will be published when we release a new version.
