### ISSUE TITLE
Rework selectors to support selection by text and n-th element selection

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#615]
Seems like we will need to use a little bit different machinery for this one to make it work in raw API (dedicated factory and executor)

**Update**
*Final API* (see discussion below):
`Selector(fn, options)`
`ClientFunction(fn, options)`
`t.select(fn, options)`
`t.eval(fn, options)`
`selector.with(options)`
`clientFunction.with(options)`

`options` are:
`dependencies` - functions and variables used by selector code 
`boundTestRun` - bound test run

Selector-specific `options`:
`visibilityCheck` - wait for element to become visible
`timeout` - element waiting timeout
`textFilter` - regexp or string, filters returned element or element collection by specified text
`index` - if selector returns enumerable collection specifies index of the selected element in that collection, 0 by default. If node returned `index` is ignored.

-----

- [x] Rename client function factories to builders
- [x] Pass `options` to ctor
- [x] `.with()` should merge options and create new builder and function
- [x] Rename `scopeVars` to `dependencies`
- [x] Implement `index`, let selector return DOM node, DOM collection or array. throw otherwise
- [x] Implement `textFilter`

**Comment by inikulin** [comment]
`t.selectByText(regExpOrString, n = 0)`
`SelectorByText(regExpOrString)` or `Selector.byText(regExpOrString)`

Nth element selector:
`t.selectNth(selector, n =0, deps, opts)` or we can just add additional parameter to `t.select`

\cc @DevExpress/testcafe What do you guys think?

**Comment by kirovboris** [comment]
```Selector.byText(regExpOrString, n = 0)```
```Selectron.nthOfType(selector, n = 0, deps, opts)```

**Comment by VasilyStrelyaev** [comment]
`t.select`
`t.selectByText`
`t.selectText`

Which is the odd-one-out?

**Comment by inikulin** [comment]
We've decided to rename `t.select` so we have:
`t.selectNode`
`t.selectNodeByText`

**Comment by inikulin** [comment]
OK, so we have:
`Selector.byText(regExpOrString, idx, scopeVars)`
`Selector.nthOfType(fn, idx, scopeVars)`

`t.selectNodeByText(regExpOrString, idx, scoperVars, opts)`
`t.selectNthOfType(fn, idx, scoperVars, opts)`

**Comment by VasilyStrelyaev** [comment]
One more:
`Selector` -> `SelectFunction` (like `ClientFunction`)
+ `SelectByTextFunction`

**Comment by inikulin** [comment]
BTW, regarding text selector, after a little dog fooding I found out that it extremely useful to specify additional selector for text and then filter it's results by text, so here is how it might look like:
`Selector.byText(fn, textFilter (re or string), index)`
or
`Selector.byText(regExpOrString, subsetSelector, index)`

Here is how it will be used:
```js
Selector.byText('li.items', 'Honda', 0);

// or

Selector.byText('Honda', 'li.items', 0);
``` 

\cc @DevExpress/testcafe

**Comment by AlexanderMoskovkin** [comment]
I prefer the second, because I expect the `text` argument to be first in the `byText` function. And can I write `Selector.byText('Honda')` in this case if I want to find an element by text only (without selector)?

**Comment by inikulin** [comment]
Or as a third option we can have compound signature for selector:
```js
Selector(fn, textFilter, n, scopeVars)
```
and we will not need additional functions then.

**Comment by VasilyStrelyaev** [comment]
ohh, I've nearly documented all this stuff...

okay, so I **stop updating documentation until we have a release version finalized**.

Once we finalize it, allow a few days for docs to be updated accordingly.

**Comment by inikulin** [comment]
@VasilyStrelyaev What would you say about proposal?

**Comment by VasilyStrelyaev** [comment]
I prefer the last one (3rd) option

**Comment by inikulin** [comment]
OK, so we will have:
```js
Selector(fn, textFilter, index, scopeVars)
// and
t.select(fn, textFilter, index, scoperVars, options)
```

I'm thinking about host object for `textFilter`, `index` and `scopeVars`, so we will have:
```
t.select('li.item', { withText: 'Honda' })
```

Any ideas how to name such object?

**Comment by inikulin** [comment]
I predict that question will arose about difference between `options` object and such host object (let's name it `initOptions` for now). `options` specifies optional things, selector will function without them, they just adjust some aspects of behavior. Meanwhile `initOptions` describes selector itself, it's not an adjustment of the options it's a part of selector definition.

**Comment by inikulin** [comment]
One more question: how we should behave if selector `fn` returns single element and we have `index` specified? Should we throw in that case or if `index > 0` return `null`?

**Comment by VasilyStrelyaev** [comment]
of if we return 3 nodes and index === 4

**Comment by AlexanderMoskovkin** [comment]
I suppose it should be the same behavior if selector doesn't return any element. What we do in this case now?

**Comment by VasilyStrelyaev** [comment]
I think we should return `null` if `index` > the number of returned nodes

**Comment by inikulin** [comment]
> of if we return 3 nodes and index === 4

It will be `null` then. Regarding `initializeOptions`: how about `filteringOptions` or `filterOptions`?

**Comment by inikulin** [comment]
Or we can just completely ignore index if `fn` returns DOM node.

**Comment by AlexanderMoskovkin** [comment]
I think we should not ignore this. If you write select(selector, 1), you expect that should be more than one elements with this selector on the page. If there is just one, something went wrong

**Comment by VasilyStrelyaev** [comment]
> Regarding initializeOptions: how about filteringOptions or filterOptions?

em... you mean `filterOptions` will include `scopeVars`. no, I think

**Comment by inikulin** [comment]
> em... you mean filterOptions will include scopeVars. no, I think

We can remove `scopeVars` from this object then. 

>  If you write select(selector, 1), you expect that should be more than one elements with this selector on the page. If there is just one, something went wrong

Emm, if you specify `select(selector, 1)` it doesn't make things better either. Or we should have `index: null` by default, signaling that we don't expect any collection.

**Comment by inikulin** [comment]
Or maybe I'm just over complicate things and we should just merge all options in one object?

**Comment by inikulin** [comment]
@DevExpress/testcafe 
Is it clear with such naming:
```js
var selector = Selector(fn, filterOptions, scopeVars); // BTW, I'm thinking about renaming scopeVars
                                                                                   // back to dependencies

var newSelector = selector.with(executionOptions);

```

**Comment by AlexanderMoskovkin** [comment]
I think, yes

**Comment by helen-dikareva** [comment]
Will `executionOptions` contains `scopeVars` in second case?

**Comment by AndreyBelym** [comment]
Looks nice. But... would not it be a little better if it would be like
`Selector(fn, scopeVars).filter(filteringOptions).with(executionOptions)`?

**Comment by inikulin** [comment]
> Will executionOptions contains scopeVars in second case?

Nope, `scopeVars` is the part of selector definition

> Selector(fn, scopeVars).filter(filteringOptions).with(executionOptions)?

Looks interesting, but we've just discussed if it correct. E.g. `fn` may return DOM node collection without filter it will end up in selector error (because we don't allow anything except node as selector return value), so without additional `.filter` call selector is not functional. In general we should avoid such cases by enforcing correct behavior with API, so I have a strong feeling that `filterOptions` should be a part of selector definition, like `scopeVars`

**Comment by VasilyStrelyaev** [comment]
As long as `index` belongs to filtering...
What if we go with
```
var selector = Selector(fn, options, scopeVars);

var newSelector = selector.with(executionOptions);
```

**Comment by VasilyStrelyaev** [comment]
yeah, it brings mess to `t.select(fn, options, scopeVars, executionOptions) though

**Comment by VasilyStrelyaev** [comment]
whats stops us from merging all options in... just `options`.
```js
var selector = Selector(fn, options, scopeVars);
t.select(fn, options, scopeVars);
```
You may redefine them all via `with`. (we are creating a new selector anyway)
```js
var newSelector = selector.with(options);
```
or, it hurts the ideology, we can get rid of `with` and use
```js
var newSelector = Selector(selector, options);
```
instead
