### ISSUE TITLE
repl it not working

### ISSUE THREAD

**Issue by easella** [DevExpress/testcafe#6150]
![image](https://user-images.githubusercontent.com/74786054/115126460-2be45c00-9f9d-11eb-8e59-8b2dfbb34421.png)
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by miherlosev** [comment]
Hi @easella

I am not familiar with the `https://replit.com` service. Please share a detailed step-by-step instruction with us so that we can reproduce the issue.
