### ISSUE TITLE
Sometimes the file uploader does not attach a document

### ISSUE THREAD

**Issue by thelazurite-cell** [DevExpress/testcafe#6151]
### What is your Test Scenario?
In some scenarios while working with testcafe, I have found that no matter what I try I am unable to attach a document to a page, though in most cases this works as expected. In the application being tested, there are no javascript errrors. However in the example provided I have had to use `--ignore-js-errors`. Though, the result is the same in the example attached.
 
### What is the Current behavior?
The file has not been attached
 
### What is the Expected behavior?
The file should've been attached to the page
 
### What is your web application and your TestCafe test code?
Please see the attached example below :)
 
<details>
<summary>Your website URL (or attach your complete example):</summary>
`npm run serve` to run the basic web server && `npm run test` to run testcafe.
  
[example.zip](https://github.com/DevExpress/testcafe/files/6339397/example.zip)
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```
❯ testcafe chrome test.ts --skip-js-errors
Using locally installed version of TestCafe.
 Running tests in:
 - Chrome 89.0.4389.128 / Windows 10

 Uploading a file
 √ Bug Example


 1 passed (10m 53s)

```
</details>

<details>
<summary>Screenshots:</summary>
![image](https://user-images.githubusercontent.com/75317253/115311123-0440ef80-a167-11eb-90cf-1c65705e6614.png)

</details>

### Steps to Reproduce:

1. Run `npm i` 
2. Run the webserver using `npm run serve`
3. Run the test with the cli arguments listed below
 
### Your Environment details:
 
* testcafe version:                   1.14.0
* node.js version:                    10.15.0
* command-line arguments:  `testcafe chrome test.ts --skip-js-errors`
* browser name and version: Chrome 89.0.4389.128
* platform and version:          Windows 10
* other:

**Comment by Farfurix** [comment]
@thelazurite-cell 

Hello,

I checked your example, and I don't see any issues. My setup was: TestCafe 1.14.0, Chrome 90, Node.js 14.15.4. To check upload input, I added some `uploadInput.value` logs to your test:
```ts
import { Selector } from 'testcafe';
import { join } from 'path';

fixture('Uploading a file').page('http://localhost:8080');

test('Bug Example', async (t: TestController) => {
    const file     = join(__dirname, 'exampleFile.txt');
    const uploader = Selector('#uploadBtn');

    await t.setFilesToUpload(uploader, file);
    console.log('1. After setFilesToUpload:', await uploader.value);
    await t.clearUpload(uploader);
    console.log('2. After clearUpload:', await uploader.value);
});

```

Result:
```
"C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" test --scripts-prepend-node-path=auto

> tc-upload-bug@1.0.0 test D:\work\issues\i6151-tc\example
> testcafe chrome test.ts --skip-js-errors

 Running tests in:
 - Chrome 90.0.4430.72 / Windows 10

 Uploading a file
1. After setFilesToUpload: C:\fakepath\D:\work\issues\i6151-tc\example\exampleFile.txt
2. After clearUpload:
 √ Bug Example


 1 passed (1s)

Process finished with exit code 0

```

Reference: [TestCafe's file upload emulation is differrent from what a real user would do to upload files](https://testcafe.io/documentation/402808/recipes/basics/test-file-upload).

**Comment by thelazurite-cell** [comment]
Thank you for your response! Working as expected in the application under test.
I appreciate the detailed explanation and reference. :)
