### ISSUE TITLE
[docs] Add more details about the state of the <input type="file"> element

### ISSUE THREAD

**Issue by Farfurix** [DevExpress/testcafe#6156]
https://testcafe.io/documentation/402808/recipes/basics/test-file-upload

Found in https://github.com/DevExpress/testcafe/issues/6151.

> TestCafe cannot interact with the native dialog. It uses the `.setFilesToUpload` action to directly change the state of the `<input type="file">` element.

We can add here an example of checking the current state of the upload input (reference: https://github.com/DevExpress/testcafe/issues/6151#issuecomment-823073738).
```js
await t.setFilesToUpload(uploadInput, file);
console.log(await uploadInput.value) // 'C:\fakepath\text-file.txt'
await t.clearUpload(uploadInput);
console.log(await uploadInput.value) // ''
```
or
```js
const uploadInput= Selector('#upload').addCustomDOMProperties({
    filesLength: el => el.files.length
});

await t.setFilesToUpload(uploadInput, file);
console.log(await uploadInput.filesLength) // 1
await t.clearUpload(uploader);
console.log(await uploadInput.filesLength) // 0
```

**Comment by titerman** [comment]
The documentation has been updated. It may take a while for the website to reflect the changes.
