### ISSUE TITLE
testcafe/hammerhead iframe is not xhtml valid and causes testfailing

### ISSUE THREAD

**Issue by Leinad-Buhtig** [DevExpress/testcafe#6157]
Currently the head-content of the testcafe iframe.html is not xhtml valid, it contains these unclosed link & meta tag:
link type="text/css" rel=stylesheet href="/styles.css" class="ui-stylesheet-hammerhead-shadow-ui"
meta class="charset-hammerhead-shadow-ui" charset="utf-8"
    
In some scenarios this leads to testcase failures, since hammerhead detects a tag mismatch and stops working.
This started with Testcafe 1.10.0 and happens also with the current version of testcafe (1.14.0)
It works with Testcafe before 1.10.0.

The reason for this behavior seems to be the parse5 library, which doesn't generate end tags for link/meta-Tags:
https://github.com/inikulin/parse5/blob/v1.5.1/lib/serialization/serializer.js#L96
https://github.com/inikulin/parse5/blob/v2.2.3/lib/serializer/index.js#L98
 
But I can't say yet why Testcafe (Hammerhead) before 1.10.0 doesn't care about this.
 
### Your Environment details:
 
* testcafe version:                 1.10.0 - 1.14.0

**Comment by miherlosev** [comment]
Hi @Leinad-Buhtig,

At present, TestCafe doesn't support XHTML pages. Track the following issue to be informed of updates: [https://github.com/DevExpress/testcafe-hammerhead/issues/350](https://github.com/DevExpress/testcafe-hammerhead/issues/350).
