### ISSUE TITLE
runner.filter fixtureMeta excludes all tests while CLI --fixture-meta works

### ISSUE THREAD

**Issue by mypchas6fans** [DevExpress/testcafe#6159]
### What is your Test Scenario?
Multiple runners for PC/H5, using fixture meta to run specific tests on each.
 
### What is the Current behavior?
**runner without filter runs all tests successfully.
CLI with --fixture-meta runs specifict tests fine.
runner with filter fails as below**

Error: The specified filter settings exclude all tests.
Modify these settings to leave at least one available test.
For more information on how to specify filter settings, see https://devexpress.github.io/testcafe/documentation/using-testcafe/configuration-file.html#filter.
    at Bootstrapper._getTests (C:\Users\totao\Downloads\ikeacn-e2e-test\node_modules\testcafe\src\runner\bootstrapper.ts:289:19)
    at async Promise.all (index 1)
    at Bootstrapper._bootstrapParallel (C:\Users\totao\Downloads\ikeacn-e2e-test\node_modules\testcafe\src\runner\bootstrapper.ts:398:38)
    at Bootstrapper.createRunnableConfiguration (C:\Users\totao\Downloads\ikeacn-e2e-test\node_modules\testcafe\src\runner\bootstrapper.ts:434:42)

### What is the Expected behavior?
runner.filter should be able to filter tests as CLI
 
<details>
```js

//runner.js

const createTestCafe = require('testcafe');

(async () => {
    const testCafe = await createTestCafe();

    const runner1 = testCafe
        .createRunner()
        .src('test.js')
        //.filter((testName, fixtureName, fixturePath, testMeta, fixtureMeta) => {
        //    return 
        //        fixtureMeta.client === 'pc';
        //})
        .browsers('chrome:emulation:device=iphone X');

    const runner2 = testCafe
        .createRunner()
        .src('test.js')
        //.filter((testName, fixtureName, fixturePath, testMeta, fixtureMeta) => {
        //    return 
        //        fixtureMeta.client === 'h5';
        //})
        .browsers('firefox');

    await Promise.all([runner1, runner2].map(runner => runner.run({skipJsErrors: true,quarantineMode: true,speed: 0.8})));

    await testCafe.close();
})();


//test.js

fixture `bing-pc-en`
    .meta({'client':'pc'})
    .page`https://www.bing.com`

test('bing', async t => {
    console.log('');
});

fixture `baidu-h5-cn`
    .meta({'client':'h5'})
    .page`https://www.baidu.com`

test('baidu', async t => {
    console.log('');
});

```
 
### Your Environment details:
 
* testcafe version:                   1.14.0
* node.js version:                    14.16.1
* command-line arguments:  testcafe firefox,chrome test.js -e -q --fixture-meta client=pc  /  node runner.js
* browser name and version: chrome 90/firefox 87
* platform and version:          win10/ubuntu 20.04
* other:

**Comment by VasilyStrelyaev** [comment]
The runner code you provided works as intended on my side if I write the filter expression on the same line as the `return` statement:
 
```js
.filter((testName, fixtureName, fixturePath, testMeta, fixtureMeta) => {
    return fixtureMeta.client === 'pc';
})

// ...

.filter((testName, fixtureName, fixturePath, testMeta, fixtureMeta) => {
    return fixtureMeta.client === 'h5';
})
```
 
Could you please check if this modification works for you?

**Comment by mypchas6fans** [comment]
Yes this indeed works and I found the topic about "auto semicolon insertion".
No issue for testcafe.
