### ISSUE TITLE
video recording enabled in testcafe runner api does not terminate the node process after test execution when fixture is skipped

### ISSUE THREAD

**Issue by monicainde** [DevExpress/testcafe#6163]
### What is your Test Scenario?
We have a testcafe setup where we use testcafe runner apis and enabled video recording. 
 
### What is the Current behavior?

- Whenever we execute test fixtures in which one of the fixture is skipped with `fixture.skip` the node process seems to be still running after executing all tests. 
- This does not have any impact on test execution whatsoever, all tests get executed as expected and generate a report/videos as specified in runner config.
- The only issue is parent process of testcafe is not being terminated after testcafe is closed which causes our CI system to run till timeout and terminate the job as failure.
- This issue is only observed when we have combination of _video recording is enabled with testcafe runner api + anyone (or all) of the fixture is skipped_
- We have other projects of testcafe( with similar configs) where command line version of testcafe is used instead of api and everythings seems fine there.

 
### What is the Expected behavior?
after testcafe is closed the calling node process should terminate and show the shell again.

### What is your web application and your TestCafe test code?
can be tested with any website

<details>
<summary>Your complete test code (or attach your test files):</summary>

runner.ts:
```js
 const createTestCafe = require('testcafe');
let runner, testcafe;

createTestCafe( 'localhost', '', '')
    .then(testcafeInstance => {
        runner = testcafeInstance.createRunner();
        testcafe = testcafeInstance;
    })
    .then(() => {

        return runner
            .src('fixture.ts')
            .browsers('chrome')
            .video('reports')
            .run();
    }).then(() => {
    testcafe.close();
});

```
In fixture.ts:
```js
import t from 'testcafe';

fixture.skip `MyFixture`
    .page `http://devexpress.github.io/testcafe/example`;

test('Test1', async t => {
    // Starts at http://devexpress.github.io/testcafe/example
});

```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

package.json
```
{
  "name": "tcp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "node runnner.ts"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@ffmpeg-installer/ffmpeg": "^1.0.20",
    "testcafe": "^1.14.0"
  }
}
```
</details>

### Steps to Reproduce:

1. Place above code in appropriate files
3. execute runner.ts with command _node runner.ts_
4. Observe that the shell does not return after executing tests, it just stays hung.
5. Comment the video recording part in _runner.ts_ and observe that after test execution the command terminates and flashes the new shell as expected.
 
### Your Environment details:
 
* testcafe version:                   1.14.0
* node.js version:                    10.13.0
* command-line arguments:  node runner.ts
* browser name and version: chrome
* platform and version:          mac & linux

**Comment by VasilyStrelyaev** [comment]
Thank you for the example. I have reproduced the behavior you described. We will investigate it.

Please also note that the `testcafe.close()` method is asynchronous, so you need to ensure that you return a promise (or add `await` when you use async/await syntax):

 ```js
.then(() => {
    return testcafe.close();
});
```
