### ISSUE TITLE
Simplify selecting elements that directly contains a node with the specified text

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#6165]
### What is your Test Scenario?
DOM trees are hierarchical, and all parent nodes contain all texts of child nodes in the `textContent` property. It makes hard to address only the deepest node that contains some text, e.g.
```html
<div class="child">
    <div class="target">
        child text
    </div>
</div>
```
```html
<div class="child">
    <div class="child-child-1"> child-child-1 text</div>
        <div class="target">
            child text
        </div>
    <div class="child-child-2"> child-child-2 text</div>
</div>
```

### What are you suggesting?
Add some new or modify an existing API method (`withExactText`) to easily select the deepest node that contains only the specified text and nothing more.

### What alternatives have you considered?
```js
Selector('*').find(node => [node.nodeValue, node.innerHTML].some(value => /^[^<>]*child text[^<>]*$/.test(value))
```

**Comment by dmitrykurmanov** [comment]
here the [another possible workaround without regexp ](https://plnkr.co/edit/OXMbj2fDQG7kYlJx?open=lib%2Fscript.js&preview)(JFI)
