### ISSUE TITLE
MaxListenersExceededWarning when running with cache enabled

### ISSUE THREAD

**Issue by P4** [DevExpress/testcafe#6167]
After we upgraded to a newer version of TestCafe, our test suite started throwning warnings about a memory leak:
```
(node:10723) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [IncomingMessageLike]. Use emitter.setMaxListeners() to increase limit
(node:10723) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [IncomingMessageLike]. Use emitter.setMaxListeners() to increase limit
(node:10723) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [IncomingMessageLike]. Use emitter.setMaxListeners() to increase limit
(node:10723) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [IncomingMessageLike]. Use emitter.setMaxListeners() to increase limit
(node:10723) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [IncomingMessageLike]. Use emitter.setMaxListeners() to increase limit
(node:10723) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [IncomingMessageLike]. Use emitter.setMaxListeners() to increase limit
...
```
I identified `IncomingMessageLike` as part of testcafe-hammerhead:
https://github.com/DevExpress/testcafe-hammerhead/blob/dc085edb4b01ab436df06fa803f7862e003f4c1e/src/request-pipeline/incoming-message-like.ts

Things I've noticed while trying to get rid of the warnings:
* The warnings always appear in the same number and at the exact same moment during each execution of the test suite
* Increasing the global listeners limit from the default 10 to 12 still makes the warnings appear exactly **two tests later** - this suggests that _something_ is being reused between tests without proper cleanup
* This something turns out to be related to the cache feature, which I've enabled after the upgrade. Setting the `cache` option to `false` causes the warnings to disappear

### What is your Test Scenario?
A suite of 500+ tests for our web application. Since I cannot share the code, I've provided a minimal reproduction of the issue that produces identical warnings. 

### What is the Current behavior?
We start to see warnings during the 12th test that's being run, and later in batches at different intervals, likely tied to whatever new resources are being added to the cache
 
### What is the Expected behavior?
No warnings about the listeners during the entire test suite.

### What is your web application and your TestCafe test code?
Here's a minimal example (in TypeScript) using https://testcafe.io in place of our web app:
```typescript
import {Selector} from "testcafe";

fixture("MaxListenersExceededWarning").page("https://testcafe.io/")

// uncomment to shift the warnings to occur two tests later
// require("events").EventEmitter.defaultMaxListeners += 2;

const fn = async (t: TestController) => await t.expect(Selector(".hero-content h1").exists).ok();

let i = 0;

test(`test #${++i}`, fn)
test(`test #${++i}`, fn)
test(`test #${++i}`, fn)
test(`test #${++i}`, fn)
test(`test #${++i}`, fn)

test(`test #${++i}`, fn)
test(`test #${++i}`, fn)
test(`test #${++i}`, fn)
test(`test #${++i}`, fn)
test(`test #${++i}`, fn)

test(`test #${++i}`, fn)
test(`test #${++i}`, fn)
test(`test #${++i}`, fn)
test(`test #${++i}`, fn)
test(`test #${++i}`, fn)
```
 
### Steps to Reproduce:
1. Run the provided code with `testcafe chrome --cache` to get warnings durning `test #12`
2. Uncomment line 6 and run again to get warnings during `test #14`
3. Run with `testcafe chrome` (without `--cache`) to get no warnings.
 
### Your Environment details:
 
* testcafe version:                   1.14.0
* node.js version:                    v12.16.3
* command-line arguments: `testcafe chrome`, `testcafe chrome --cache`
* browser name and version: Chrome 89.0.4389.114
* platform and version:           Linux Ubuntu 18.04.5

**Comment by felis2803** [comment]
Thank you for your report. I reproduced this issue.

**Comment by miherlosev** [comment]
Fixed in https://github.com/DevExpress/testcafe-hammerhead/pull/2624.
