### ISSUE TITLE
Unable to drag on specific element

### ISSUE THREAD

**Issue by aleks-pro** [DevExpress/testcafe#6168]
Test code:
```js
import { Selector } from 'testcafe';

fixture `DragDrop`
    .page `./testcafe/testcafe.html`;

test('Create two pages', async t => {
    await t
        .maximizeWindow()
        .setTestSpeed(0.2)
        .click(Selector('.svc-page__content').nth(0))
        .dragToElement(Selector('div[aria-label=\'Checkbox toolbox item\']'), Selector('.svc-page__content').nth(1))
        .debug();
});

```
App sample:
https://devexpress-my.sharepoint.com/:u:/p/alexander_prokhorov/EYnySrYxSDRGtg60udkC-c0Bm7omdDMmlXjLsSrVxsBkCA?e=0WcZSl

The problem is that `dragToElement` action always drops `'div[aria-label=\'Checkbox toolbox item\']'` element to the `Selector('.svc-page__content').nth(0)` instead of the `Selector('.svc-page__content').nth(1)` element.
 
* testcafe version:                   1.14.0
* node.js version:                    12.18.0
* command-line arguments:  testcafe chrome test.js
* browser name and version: Chrome 90
* platform and version:          macOS 10.15

**Comment by AndreyBelym** [comment]
The target element moves after debugging starts. I like to qualify this as a case of #1374.

As a workaround, you can predict a distance that the target element moves, and specify it as the `destinationOffsetY` option. E.g. `destinationOffsetY: 200` is a perfect workaround for this specific issue.
