### ISSUE TITLE
Add more browsers for functional testing

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#617]
At first we need to split old API and new API tests. And run tests for new API in all browsers. Also, maybe we could skip running client tests if code in `client` is not affected by PR?

**Comment by inikulin** [comment]
Or as better idea: extract both client and functional tests for old API and run them on daily basis as smoke tests, e.g. 2 times a day, like we do for health monitor. The task is quite important, because we need to test our stuff in all browsers before release.

**Comment by AlexanderMoskovkin** [comment]
a nice idea, I'll do this

**Comment by AlexanderMoskovkin** [comment]
I'm working on this

**Comment by AlexanderMoskovkin** [comment]
- [ ] Separate tests:
 - Legacy client tests
 - Client tests
 - Legacy functional tests
 - Functional tests

- [ ] Run functional tests in the next browsers
 - [ ] (Win 10) Chrome, Firefox, IE11
 - [ ] (OS X) Safari
 - [ ] (OS X) Chrome
 - [ ] (OS X) Firefox
 - [ ] Android simulator
 - [ ] iPad simulator
 - [ ] iPhone simulator

**Comment by AlexanderMoskovkin** [comment]
@inikulin Please check browsers list above. Do we need run functional tests in IE9,10

**Comment by inikulin** [comment]
Ideally we should test in all browsers for which we declare support
