### ISSUE TITLE
[docs] Add the 'Support for advanced scenarios'

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#6171]
We constantly say that testcafe supports advanced scenarios, but there is no place of what we are talking about.
It'd be nice if we'll have such page with:

- full list of such scenarios
- required examples (we will be able to use our demo pages once they're ready)
- why it is important for a test framework to support complex scenarios

**Comment by titerman** [comment]
We don't plan to address this issue in the near future. Feel free to reopen the ticket if the issue is important for you.
