### ISSUE TITLE
Provide logs to troubleshoot "ERROR Unable to establish one or more of the specified browser connections."

### ISSUE THREAD

**Issue by tieTYT** [DevExpress/testcafe#6173]
### What is your Test Scenario?
I inconsistently get this error when I run my tests: 

```
ERROR Unable to establish one or more of the specified browser connections.
1 of 3 browser connections have not been established:
- chrome:headless
```

### What are you suggesting?
Lots of people are get this error for different reasons. Whenever they post an issue here, the maintainers ask for a sample project. I understand why they are asking for that, but IMHO, it's not enough information to provide: just because it errors on one computer doesn't mean it will error on another. Some say these issues can happen if your computer is pegged at certain moments.

I am requesting a log so that users can troubleshoot these errors. It may not be enough to solve the issues on our own, but it would help maintainers troubleshoot, too.

### What alternatives have you considered?
Contributing a sample project where I experienced this issue.

### Additional context
I get this error when I run locally in headless mood. Most people experience it remotely.

**Comment by Dmitry-Ostashev** [comment]
Thank you for your suggestion. There is a similar issue that is already open: https://github.com/DevExpress/testcafe/issues/5683. Let's collect all the requirements there.
