### ISSUE TITLE
[docs] How to add screenshots and videos to Azure DevOps runs as either attachments or artifacts

### ISSUE THREAD

**Issue by VasilyStrelyaev** [DevExpress/testcafe#6176]
See this answer: https://stackoverflow.com/a/67227685/4762842

In the [Azure integration guide](https://testcafe.io/documentation/402822/guides/continuous-integration/azure-devops), we should say that you can easily add images and videos as *artifacts*. However, in order to add them as *attachments*, you should use the community-developed NUnit 3.0 reporter

**Comment by miherlosev** [comment]
https://stackoverflow.com/questions/62959243/does-anyone-know-if-we-can-upload-screenshots-to-azure-devops-with-testcafe-cicd
https://stackoverflow.com/questions/64966406/display-screenshots-on-test-failure-in-azure-devops-pipeline
https://stackoverflow.com/questions/67210425/how-to-attach-test-failure-screenshots-to-azure-pipeline-test-run-in-yaml
https://stackoverflow.com/questions/67247685/how-can-i-save-screenshots-and-videos-as-attachments-in-azure-build-pipeline-wit
https://supportcenter.devexpress.com/internal/ticket/details/T992880
https://supportcenter.devexpress.com/internal/ticket/details/T952204
https://supportcenter.devexpress.com/internal/ticket/details/T951872
https://supportcenter.devexpress.com/internal/ticket/details/T748679

**Comment by titerman** [comment]
We don't plan to address this issue in the near future. Feel free to reopen the ticket if the issue is important for you.
