### ISSUE TITLE
[docs] Add the --disable-multiple-windows option to the help section of the command line help

### ISSUE THREAD

**Issue by AlexSkorkin** [DevExpress/testcafe#6179]
### What is your Test Scenario?

After executing the `testcafe -h` command, the help does not contain any mention of the `--disable-multiple-windows` command.

### What are you suggesting?

Add the `--disable-multiple-windows` command to the list of available commands.

### What alternatives have you considered?

Online help.

**Comment by miherlosev** [comment]
The issue is not reproduced with the last commit (https://github.com/DevExpress/testcafe/commit/a476d43a215b31f6b7a21c9f8550572f836fe51e)
