### ISSUE TITLE
[docs] Add a note (or an article section) about new scroll functionality to the "How to Scroll Web Pages Using TestCafe" article

### ISSUE THREAD

**Issue by Farfurix** [DevExpress/testcafe#6180]
[How to Scroll Web Pages Using TestCafe](https://testcafe.io/402893/resources/blog/2020-4-20-how-to-scroll-web-pages-using-testcafe).

New scroll functionality: [Scroll Actions](https://testcafe.io/403064/release-notes/framework/2021-4-7-testcafe-v1-14-0-released).

Reference: we have already added such a note here: [Scroll Elements Into View](https://github.com/DevExpress/testcafe-examples/tree/master/examples/scroll).

**Comment by supportcoreorient** [comment]
https://github.com/DevExpress/testcafe/issues/6185

**Comment by AnnaKondratova** [comment]
The topic is updated.
