### ISSUE TITLE
Incorrect fullPage screenshot sizing

### ISSUE THREAD

**Issue by YannikRudolph0108** [DevExpress/testcafe#6186]
### What is your Test Scenario?
To explain this issue, I created a dummy HTML page that is composed of 10 rows of 10 boxes, where every single box is 100px wide. So the tested page in total has a size of 1000px * 1000px. In this testcafe test the html page is opened, and the headless chrome browser is resized to a certain browser size (1050px, 768px). With this configuration the browser should be able to display the whole page without any line breaks. After the resizing a screenshot is taken with the parameter `fullPage: true`.

This issue is connected to this [stackoverflow question](https://stackoverflow.com/questions/66465995/how-to-take-full-page-screenshots-with-testcaf%c3%a9-correctly).

### What is the Current behavior?
Testcafe takes a screenshot, that is has a width of 1024px and a height of 1000px. This is the expected size for the screenshot, but the screenshot itself, the lines of boxes have a line break after 9 boxes. Due to the line break the whole page extends and not all the content is shown in the screenshot. Besides, there is a scrollbar in the screenshot, which I do not expect, if I take a screenshot with the fullPage configuration. 

### What is the Expected behavior?
I expect that the screenshot displays the full page with all 100 boxes and no scrollbar. This also means, that there should be no line breaks.

### What is your web application and your TestCafe test code?

<details>
<summary>Your website URL (or attach your complete example):</summary>
<a href="https://github.com/YannikRudolph0108/testcafe-screenshot-sizing-issue">https://github.com/YannikRudolph0108/testcafe-screenshot-sizing-issue</a>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
test('Screenshot test', async t => {
  await t
    .resizeWindow(1050, 768)
    .takeScreenshot({
      path: '/dummy-screenshot' + new Date().getTime(),
      fullPage: true
    });
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

No configuration file, only the test command

```
testcafe chrome:headless screenshot-test.js
```
</details>

<details>
<summary>Your complete test report:</summary>

```
 Running tests in:
 - Chrome 90.0.4430.93 / Windows 10

 Screenshot test suite
 √ Screenshot test (screenshots: C:\Users\USER\Workspace\testcafe-screenshot-sizing-issue\screenshots\dummy-screenshot1619680071553.png)


 1 passed (3s)
```
</details>

<details>
<summary>Screenshots:</summary>

<img src="https://user-images.githubusercontent.com/81756970/116514849-df1d5100-a8cb-11eb-8048-7e5449ae9fcd.png"/>
</details>

### Steps to Reproduce:

1. Go to my the project [testcafe-screenshot-sizing-issue](https://github.com/YannikRudolph0108/testcafe-screenshot-sizing-issue)
2. Install dependencies with `npm i`
3. Run testcase with `npm test`
4. See broken screenshot in folder `/screenshots`

### Your Environment details:

* testcafe version: 1.14.0
* node.js version: 14.16.1
* command-line arguments: `testcafe chrome:headless`
* browser name and version: Chrome 90
* platform and version: Windows 10

**Comment by AlexSkorkin** [comment]
Thank you for reaching out to us and submitting this issue. My attempts to replicate it, however, were unsuccessful. I followed your instructions and ran the test. Here's a screenshot of the test output:

![image](https://user-images.githubusercontent.com/995726/116855183-a352f600-ac01-11eb-904b-29971adce7b4.png)

I use TestCafe v1.14, Node 14.16.1, Chrome 90.0.4430.93 (Official Build) (64-bit) on Windows 10 20H2. Are there any additional steps I need to take in order to replicate this issue?
