### ISSUE TITLE
Latest rc (1.15.0-alpha.1) of testcafe gives babel errors in docker

### ISSUE THREAD

**Issue by raj-balaebail** [DevExpress/testcafe#6195]
### What is your Test Scenario?

Run tests in docker 

### What is the Current behavior?

```
ERROR Cannot prepare tests due to an error.

Error: [BABEL] /testcafe/tests/pos/verification/td_tests/preverification_page/preverification-page-tests.spec.js: Failed to resolve "@babel/runtime" relative to "/testcafe" (While processing: "base$0")
```
 
### What is the Expected behavior?

Run tests in docker 
 
### What is your web application and your TestCafe test code?

Not needed
 
<details>
<summary>Your website URL (or attach your complete example):</summary>
Not needed

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
1.15.0-alpha.1
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by wentwrong** [comment]
Hello @raj-balaebail,

I couldn't reproduce the error with the specified version of TestCafe (1.15.0-alpha.1) in Docker. I used the following command:
```sh
docker run -it -v ${PWD}:/tests -w /tests testcafe/testcafe:1.15.0-alpha.1 chromium,firefox test.js
```
The tests passed without any problems. Could you please share an example showing how we can reproduce the issue on our side?

**Comment by raj-balaebail** [comment]
Interestingly, I can't reproduce this anymore too. We did have some issues with our internal artifactory which stores all the images around the same time. Presumably the image had gotten corrupted.
