### ISSUE TITLE
Test Cafe Requires Permission To Record Screen -> but permission is already granted on MAC

### ISSUE THREAD

**Issue by rob4629** [DevExpress/testcafe#6198]
### What is your Test Scenario?

To be able to record the screen on failures
 
### What is the Current behavior?

Copying from #4684 (which is closed & locked)
I recently upgraded my mac to Big Sur, and installed the latest alpha version of TestCafe (`1.15.0-aplpha.1`). When trying to run testcafe I get 

```
TestCafe requires permission to record the screen. Open 'System Preferences > Security & Privacy > Privacy > Screen Recording' and check 'TestCafe Browser Tools' in the application list.

Press any key to retry.
ERROR UnableToAccessScreenRecordingAPIError: The find-window process cannot access the Screen Recording API.
    at runFindWindowBinary
```

Screen Recording Permission has already been granted for TestCafe... following the advice in #4684, I have unchecked and rechecked `TestCafe Browser Tools` + restarted my Mac

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
  "browsers": ["chrome:headless:emulation:device=iPhone X"],
  "src": "./tests/**/*.js",
  "clientScripts":[
    {
      "module":"axe-core/axe.min.js"
    }
  ],

  "assertionTimeout": 15000,
  "pageLoadTimeout": 30000,
  "selectorTimeout": 15000,

  "disableMultipleWindows": false,

  "quarantineMode": false,
  "skipJsErrors": true,

  "disablePageCaching": true,

  "reporter": [
    {
      "name": "xunit",
      "output": "artifacts/test-results/results.xml"
    },
    {
      "name": "spec"
    }
  ],

  "screenshots": {
    "fullPage": true,
    "takeOnFails": true,
    "pathPattern": "${TEST_ID}/${RUN_ID}_${FILE_INDEX}.png",
    "path": "artifacts/screenshots"
  }
}

```
</details>

<details>
<summary>Your complete test report:</summary>

```
The "quarantineMode" option from the configuration file will be ignored.
TestCafe requires permission to record the screen. Open 'System Preferences > Security & Privacy > Privacy > Screen Recording' and check 'TestCafe Browser Tools' in the application list.

Press any key to retry.
ERROR UnableToAccessScreenRecordingAPIError: The find-window process cannot access the Screen Recording API.
    at runFindWindowBinary (/Users/rcooper/work/github.com/change/regression-qaa/node_modules/testcafe-browser-tools/src/api/find-window.js:36:19)

Type "testcafe -h" for help.
```
</details>

<details>
<summary>Screenshots:</summary>

```
<img width="905" alt="Screenshot 2021-05-01 at 3 57 52 PM" src="https://user-images.githubusercontent.com/37812673/116797143-4804f480-aa97-11eb-9f77-2a131a995d76.png">

```
</details>

### Steps to Reproduce:

Using `Big Sur` MacOS, run: `testcafe chrome -q passCount=1`
 
### Your Environment details:
 
* testcafe version:   1.15.0-alpha.1                
* node.js version:   12.14.1                 
* command-line arguments:  testcafe chrome -q passCount=1 
* browser name and version: chrome 90.0 
* platform and version:  MacOS Big Sur 11.3        
* other:

**Comment by VasilyStrelyaev** [comment]
Please also try removing TestCafe Browser Tools from the list. Use the "minus" button to remove the item and then run a test that takes a screenshot. macOS will request recording permissions and, once you confirm the request, it will grant them from scratch.

**Comment by rob4629** [comment]
Ahh sorry, this should have been a StackOverflow question instead of a bug 🤦🏻 . Thanks for answering

**Comment by Aaronius** [comment]
Using the minus sign was very important. I do wish this tip were in the message that TestCafe logs to the console.

**Comment by cattermo** [comment]
> It looks like not every testcafe command will reset the permissions. I ran the following one and it worked `testcafe chrome -q passCount=1`. The thing to notice is that the command I was trying to run to trigger the reset did not work.

This did not work for me. I have tried removing with the minus sign. Any other suggestions? The permissions dialog just keeps popping up every time 😱 

MAC OS - Big Sur 11.6.1
Node v16.13.0
testcafe v1.17.1

Testcafe was working fine on one project. This problem appeared when I added testcafe to a brand new project on the same computer.

**Comment by liront2** [comment]
Solved it.
it happens when you grant permission to the globally installed testcafe, instead of the one installed in your node_modules.
You can grant permissions to the testcafe under:
`node_modules/testcafe-browser-tools/bin/mac/TestCafe Browser Tools.app`
it fixed it for me.
