### ISSUE TITLE
Ability to extract string locator from already defined Selector in Testcafe

### ISSUE THREAD

**Issue by gforepsly** [DevExpress/testcafe#6215]
### What is your Test Scenario?
I would like to extract string of already defined Selector in Testcafe
[https://stackoverflow.com/questions/67333535/is-it-possible-to-get-string-locator-from-already-defined-selector-in-testcafe](url)

Reason?
Using protractor, we had this ".locator()" method on elements there, which we heavily used inside reusable methods. In our repo, I have clickOnElement(), checkIfVisible() and similar methods, which have few steps that I use as reusables for many many situations. The problem is, when something fails, the error that we get is very generic in some situations, I would like to expand with custom message for t.expect() where I would like to add my locator of provided elements etc. Currently it's hard to locate what exactly failed without a heavy refactor.

Example of one helper method:
```JS
async inputText(elem: Selector, text: string) {
        await this.checkIfElementPresent(elem);
        await t.click(elem)
            .pressKey('ctrl+a backspace')
            .typeText(elem, text);
    }
async checkIfElementPresent(elem: Selector) {
        await t.expect(elem.exists).ok('The element you provided is not present!', { timeout: TestcafeTimeoutHelper.GlobalTimeout });
    }
```

It would be pretty neat to add something like ('The element you provided is not present! ' + elem.locator()) for fail scenarios. 

### What are you suggesting?
Example:
```JS
const element = Selector('[test-id="picker-placeTerritoriesFilter-territory"] button');
console.log(element.locator()) should give me the '[test-id="picker-placeTerritoriesFilter-territory"] button' value
```

Example 2:
```JS
`const element = Selector('[test-id="picker-placeTerritoriesFilter-territory"]').find('button);
console.log(element.locator()) should give me the '[test-id="picker-placeTerritoriesFilter-territory"] button' value
```

And so on...

### What alternatives have you considered?
https://testcafe.io/documentation/402829/guides/basic-guides/select-page-elements#extend-selectors-with-custom-properties-and-methods
I can use custom properties, but then I have to define them for all elements (I have 500+ elements and it just grows). Also, I need to define strings in a variable in order to have the value in one place, which is also really not convenient for us. 

### Additional context
If protractor had this, why wouldn't testcafe have it as well :)

**Comment by AlexKamaev** [comment]
It seems to me that your `checkIfElementPresent` method is redundant. TestCafe already has a built-in visibility check for elements. In your case, if you remove the `checkIfElementPresent` check and the target element does not exist, the test will fail on `t.click(elem)`, and you will see a similar message:
```
   1) The specified selector does not match any element in the DOM tree.

       > | Selector('body div .non-existing')

      Browser: Chrome 90.0.4430.93 / Windows 10

          4 |
          5 |async function checkIfElementPresent(t, elem) {
          6 |    // await t.expect(elem.exists).ok('The element you provided is not present!', { timeout: 5000 });
          7 |
          8 |
       >  9 |    await t.click(elem);
         10 |}
```

Please try this approach.

**Comment by gforepsly** [comment]
Hi @AlexKamaev!

Thx for your response. 
I just gave 1 example, we have many. Even if I just wait for t.expect(element.visible).notOk(), my error will in that case be something like "expect truthy to be false", which will not help a lot.  I have to use custom error messages in those scenarios, and to add them for so many situations is just not convenient. Doable, but not convenient :) I would rather extend my base element helper methods with suggested approach. 

You are correct with this being redundant, but I do have some occasions where this scenario fails if I don't expect for existence of an element I'm working with, so I ended up doing this, and this work 100% of the time. Maybe it's because of app is currently a hybrid between AngularJS and newest Angular, sometimes when jumping back and forth I really had to do some waits, global default timeouts didn't help. I can maybe retry as now I'm using latest testcafe version, but this still doesn't change our requirement. 

If all methods of "t.expect().someAssert" can always state the selector in their log (the ones that are using one), that would even be better. Do let me know what do you think about it.

**Comment by AlexKamaev** [comment]
I understand your point. I think it makes sense. We have some plans to improve the `visibility checking` experience: [https://github.com/DevExpress/testcafe/milestone/53](https://github.com/DevExpress/testcafe/milestone/53)
So, I will add this issue to that list. However, at present, we cannot guarantee that we will work on this issue.

**Comment by gforepsly** [comment]
> I understand your point. I think it makes sense. We have some plans to improve the `visibility checking` experience: https://github.com/DevExpress/testcafe/milestone/53
> So, I will add this issue to that list. However, at present, we cannot guarantee that we will work on this issue.

Thx for your answer!
The most important for us is "visibility" and "exists" properties, asserting and failing those is not precise enough, like described. When you have 2-3 steps even in perfectly structured independent test block, failing on those is tricky to debug out of the box by just looking at the error message.

Best scenario is to output the selector whenever step which asserts some element fails.

**Comment by rob4629** [comment]
We would also really appreciate this level of detail in the instance of a failed assertion. Bumping so that it doesn't get closed
