### ISSUE TITLE
Not able to switch to iframe with headless browser

### ISSUE THREAD

**Issue by arvindarun** [DevExpress/testcafe#6224]
When trying to switch from one iframe to another iframe, an exception is thrown "Cannot switch to the window.". This exception occurs with headless browser, but it works fine without a headless browser

![image](https://user-images.githubusercontent.com/54062330/118167630-85c52e00-b444-11eb-94e1-6cb029563560.png)

Testcafe version: 1.14.0
Browser: chrome
Browser version: 90.0
OS: mac and windows

**Comment by arvindarun** [comment]
> Thank you for submitting this issue. We would love to assist you and diagnose it. However, we need a simple sample that we can easily run on our side in order to replicate the issue and research its cause. Without a sample, we are not able to figure out what's going on and why this issue occurs. We look forward to your response.

I cannot share my source code here

**Comment by aleks-pro** [comment]
Hello @arvindarun,

If you cannot share your projet here, you can send it to support@devexpress.com.

**Comment by arvindarun** [comment]
> Hello @arvindarun,
> 
> If you cannot share your projet here, you can send it to [support@devexpress.com](mailto:support@devexpress.com).

I sent but still, I have not got any reply

**Comment by aleks-pro** [comment]
We checked our inbox and we did not find any messages regarding this issue. Could you please send your example to us again?
