### ISSUE TITLE
how to resolve Testcafe : Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by ckswami78** [DevExpress/testcafe#6225]
I am trying to launch my test web site using TestCafe in chrome browser. Our site asks for Windows Authentication popup, we provided the credentials using httpAuth. The issue is, Windows Authentication popup loads after 20 -30 seconds by that time TestCafe exits the test with timeout error. Please provide your suggestion to resolve.

fixture Automation -QA Env
    .meta('fixturepack', 'regression')
    .meta('Product', 'UI')
    .meta('Project', 'UI')
    .meta('Program', 'TestComponent')
    .page(BaseTest.config.qa_URL)
    .httpAuth({
        username:'test',
        password:'test'
    })
    .beforeEach(async t => {
      
        DriverManager.setDriver(t);
        await DriverManager.maximize(); 
        await t
        .setPageLoadTimeout(19500000);       
    })

Following is the error:

Error in fixture.beforeEach hook - A request to "https://*********************" has failed. Use quarantine mode to perform additional attempts to execute this test. You can find troubleshooting information for this issue at "https://go.devexpress.com/TestCafe_FAQ_ARequestHasFailed.aspx".
Error details: Failed to perform a request to the resource at "https://***************" because of an error.
Error: connect ETIMEDOUT ********** `

**Comment by ckswami78** [comment]
Thanks for your response. URL is internal and required VPN connection to launch to reproduce.  Do you have any thoughts on how we can inform TestCafe module to wait for windows authentication pop up load instead of timing out in few seconds ?

**Comment by miherlosev** [comment]
Hi @ckswami78 

Judging by the error message, you are using an earlier TestCafe version. Please update to the latest TestCafe version: `1.14.2`.
Increase the request timeout using the [page request timeout](https://testcafe.io/documentation/402639/reference/command-line-interface#--page-request-timeout-ms) option so that windows authentication has time to finish.

**Comment by ckswami78** [comment]
@miherlosev 
I have updated with latest test cafe as mentioned 1.14.2 and added page request timeout. Still I am getting Timedout error. Also in the browser URL it appends about:error when it fails to launch the page. This issue is inconsitent. One time loads and one time fails.
