### ISSUE TITLE
withText() - add option caseInsensitive

### ISSUE THREAD

**Issue by fmancardi** [DevExpress/testcafe#6229]
### What is your Test Scenario?
I've a JQuery Select2 that has following values

![jquery](https://user-images.githubusercontent.com/235697/118451386-7caeb800-b6f5-11eb-8356-45938d58f0ae.png)

But when to test was written for a previous version all options were Capitalized.
Then in the test I've the following test 
var whereToAct = await Selector(this.idStartsWithSingle).find('div').withText(valueToString);
that now fails.

### What are you suggesting?
provide an option to allow compare be case insensitive -> DEFAULT: current behaivour Case Sensitive.

var whereToAct = await Selector(this.idStartsWithSingle).find('div').withText(valueToString, **{caseInsensitive: true}**);

The same requests applies to withExactText()

**Comment by thelazurite-cell** [comment]
I believe the `withText` method supports regex, so you can use the /i flag:

`/MyValue/gi`

useful tool for debugging a regex: https://regexr.com/

**Comment by fmancardi** [comment]
@thelazurite-cell Thanks, you are right , my mindset is not regexp oriented.  :(
Probably adding also the option it's not bad.

**Comment by thelazurite-cell** [comment]
Yeah I think it could still be a nice addition, glad you were able to get it sorted though :)

**Comment by Farfurix** [comment]
@fmancardi 

Hello,

We will consider implementing the "case" option or some separate method.
