### ISSUE TITLE
Refactor CLI options to allow configuring quarantine

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#6231]
Before, `--quarantine-mode` was a boolean switch. That allowed using it like `testcafe -q chrome test.js`

If we allow optional parameters for it, (`-q opt=value`), the parser cannot deduct that `chrome` or `test.js` are not an input for this property

~~So we should use the dedicated `--quarantine-options retryCount=X,passCount=Y` switch.~~
UPDATE: We decided to fix the original case without adding the `--quarantine-options` option.

Options:
- [ ] ~~Add the `--quarantine` alias to `--quarantine-mode` to make naming more consistent.~~
- [x] Rename quarantine parameters as `attemptLimit` and `successThreshold` (https://github.com/DevExpress/testcafe/pull/6312)

Assignee: @Farfurix

**Comment by Farfurix** [comment]
We decided to fix the original case without adding the `--quarantine-options` option.
