### ISSUE TITLE
Randomly raising ERR_HTTP2_GOAWAY_SESSION errors with Testcafe v. 1.14

### ISSUE THREAD

**Issue by sam-yh** [DevExpress/testcafe#6234]
### What is your Test Scenario?
We are running testcafe tests for a web application on a staging environment, both on local machines and on CI.
 
### What is the Current behavior?
With the upgrade to Testcafe version 1.14+ we suddenly encounter this type of error:

```
1) Unhandled promise rejection:
      Error [ERR_HTTP2_GOAWAY_SESSION]: New streams cannot be created
      after receiving a GOAWAY
      at ClientHttp2Session.request (internal/http2/core.js:1563:13)
      at DestinationRequest._sendRealThroughHttp2
   (xyz\node_modules\testcafe-hammerhead\lib\request-pipeline\destination-request\index.js:47:32)
      at DestinationRequest._send
   (xyz\node_modules\testcafe-hammerhead\lib\request-pipeline\destination-request\index.js:99:18)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      Browser: Chrome 90.0.4430.212 / Windows 10
```

These errors are not happening all the time, we can also not provide any clear way to reproduce it (beyond using Testcafe version 1.14).

When they do occur, it is rather rarely (~ 1 in 10 test files) but currently it prevents us from using Testcafe 1.14+.
Downgrading to Testcafe 1.13, we do not see these errors at all anymore.

What I can share about the involved server configuration (staging system) is that we are running nginx 1.18.
The config looks something like this
```
server {
    listen 443 ssl http2 default_server;
[...]
```

Generally the downgrading to http1 is working, and is also working with Testcafe 1.13.

So somehow it seems there is a bug in version 1.14 where from time to time, the downgrading from http2 to http1 fails and the "GOAWAY" is triggered.

### What is the Expected behavior?
Not to raise any ERR_HTTP2_GOAWAY_SESSION errors when running tests with Testcafe 1.14
 
### What is your web application and your TestCafe test code?
I cannot really share much here. I can tell you that it does not seem to be connected to specific test code, because it can happen randomly with different tests. Watching video recordings of failed tests, it seems the error gets raised mostly between page requests.

### Steps to Reproduce:
1) Run tests with Testcafe v. 1.14 against a server that supports http 2 and http1.1  where the downgrading is handled automatically 10 to 30 times

reproduced with chrome and firefox in headless and non-headless mode
 
### Your Environment details:
 
* testcafe version:                   1.14.2
* node.js version:                    v16.1.0
* command-line arguments:  testcafe chrome:headless
* browser name and version: Chrome 90, Firefox 88
* platform and version:         Windows 10
* other:                                 Unfortunately hard to reproduce

**Comment by mm-breuninger** [comment]
I have the same issue. I think this is rather a hammerhead issue. 
Hammerhead (or testcafe) should try to create a new http2 connection on this kind of failure instead of failing completely. 
Hammerhead is reusing the same http2 connection for all requests to the same host. So recovering from a broken connection should happen here.
