### ISSUE TITLE
Random behaviour - count table records after submit

### ISSUE THREAD

**Issue by fmancardi** [DevExpress/testcafe#6237]
### What is your Test Scenario?
Our application have the classic page where a list of items is displayed and where the user can set filters, then submit the page returning to the same page but with less items due to the filter.  
A simple test case consists in counting the rows present after the filter is applied.  
After the await t.click(sumitButton) a function to get the table row count is called.
   
### What is the Current behavior?
Sometimes the right count is got other the row count **_is the number of rows before the button click_**
This rise one question: how testcafe is able to understand that after the click the page content has changed or is the old one?
 
### What is your web application and your TestCafe test code?
I can provide (via private email) credentials to access the test environment.  

### Your Environment details:
 
* testcafe version:    1.11.0
* node.js version:     v14.15.5
* command-line arguments:   testcafe 'chrome --start-fullscreen' --skip-js-errors -s takeOnFails=true --test-meta WKFSTATUS=ready,6.3=yes
* browser name and version: Version 90.0.4430.212 (Official Build) (64-bit)
* platform and version:          Windows 10

**Comment by AlexKamaev** [comment]
>how testcafe is able to understand that after the click the page content has changed or is the old one?

TestCafe does not look for any changes on the client. If you want to check the table row count before and after the click, you need to call your function twice or execute the `Selector(...).count` property twice as in the following example:


```HTML
<body>
    <table>
        <tr>
            <td>1</td><td>2</td>
        </tr>
        <tr>
            <td>3</td><td>4</td>
        </tr>
    </table>
    <script>
        function clickHandler () {
            var table = document.querySelector('table');
            var tr    = document.createElement('tr');
            var td1   = document.createElement('td');
            var td2   = document.createElement('td');

            td1.innerHTML = '5';
            td2.innerHTML = '6';

            tr.appendChild(td1);
            tr.appendChild(td2);

            table.appendChild(tr);
        }
    </script>
    <button onclick="clickHandler()">click me</button>
</body>
```

```JS
import { Selector } from 'testcafe';

fixture `f`
    .page `../pages/index.html`;

const trs = Selector('table').find('tr');

test('Click in iframe', async t => {
    console.log(await trs.count);
    await t.click('button');
    console.log(await trs.count);
});
```
As far as I understand, your code is similar to my code, but it does not work for some reason. I suggest you share your project with us for further research.
> I can provide (via private email) credentials to access the test environment.

Please send the credentials to support@devexpress.com.

**Comment by fmancardi** [comment]
Thanks for your answer,
I'm going to provide more details with a mail to support.
Then when things will be clear I will post conclusions here

**Comment by fmancardi** [comment]
Hi
I know I've not still providing the details, but I would like (if possible) a clarification.

I've found this in the documentation:

_When a selector is executed, TestCafe waits for the target node to appear in the DOM until the selector timeout expires._

Returning to your code example:  

test('Click in iframe', async t => {
    console.log(await trs.count);  **// STEP 1 **
    await t.click('button'); **// STEP 2 **
    console.log(await trs.count);  **// STEP 3 **
});

On STEP 1 testcafe will find target node in the DOM

**Q1 - After the STEP 2, what is the mechanisim used by testcafe, that  will make it consider that the target node is not  present in the anymore in the DOM ?** 
**Q2** It's possible that after page reload I see an element in the screen, but test cafe considers that the element does not exist?
**Q3** it's possible this situation

```
if (await elem.visible) {
   await t.expect(elem.exists).ok();   **// and that this expect will fail?**
}
```

I'm asking these questions because I'm experimenting weird behaviour, that make my test scripts flaky

best regards

**Comment by AlexKamaev** [comment]
Hi

> Q1 - After the STEP 2, what is the mechanisim used by testcafe, that will make it consider that the target node is not present in the anymore in the DOM ?

TestCafe does not cache results of the Selector execution. So, when you execute your Selector for the second time, TestCafe tries to find the target element again. Therefore, if the element is missing for some reason, TestCafe shows the error message.

> Q2 It's possible that after page reload I see an element in the screen, but test cafe considers that the element does not exist?

In some cases, TestCafe can consider the element as `not visible` (`el.visible` returns `false`) even if you see the element on your screen. However, TestCafe should consider it as `existing` (`el.exists` returns `true`) anyway.

> Q3 it's possible this situation
```
if (await elem.visible) {
   await t.expect(elem.exists).ok();   **// and that this expect will fail?**
}
```
In general, this should not happen. It can only happen if the element is deleted on the client side after the `elem.visible` check is complete.

**Comment by fmancardi** [comment]
I'm sending you all credentials and links to support email, explaining a situation where exists fails in random way

**Comment by fmancardi** [comment]
I've verified that this issue happens randomly when the table is inside an iframe.
Hope this additional info can help.

please let me know

**Comment by AlexKamaev** [comment]
Thank you for the provided credentials. However, I did not find any test. Please prepare a single test to demonstrate the issue.

**Comment by miherlosev** [comment]
Hi @fmancardi 

We still don't have a completed example. Without it, we can't say something definite. Feel free to reopen the issue if you can create a full example that we can run locally without any additional setup.
