### ISSUE TITLE
Add ability to get skipped tests in embedding-utils.js

### ISSUE THREAD

**Issue by flora8984461** [DevExpress/testcafe#6238]
### What is your Test Scenario?

I am trying to add some personal static analysis to my testcafe tests according to different features I am testing. I found there is getTypeScriptTestList in the following API, https://github.com/DevExpress/testcafe/blob/fcd93e8dbee76ea70786ee3aee4fb35990260e2a/src/embedding-utils.js#L54 (I am using Typescript), and I can get a list of the tests with very basic info without running all the tests, however, there seems no information getting the skipped tests, and it would be great if it's also included.

### What are you suggesting?

The current returned properties include: `name, loc, start, end, and meta`.
It would be great to add one like `skipped`?

### What alternatives have you considered?

Maybe some more info can be added as well that I am currently not aware of?

### Additional context

~~I found this feature request https://github.com/DevExpress/testcafe/issues/4340 and mine is more like adding one more property based on it.~~

Sorry, just found the feature request was not similar, mine is adding one more ability in the current existing embedding-utils.

Not sure if it's possible to add, many thanks to testcafe team and the community!

**Comment by AlexKamaev** [comment]
Hello.
Currently, we do not plan to modify these utils. If you want, you can research the possibility of adding a new property and make a PR.
