### ISSUE TITLE
about:error in the browser address bar

### ISSUE THREAD

**Issue by ckswami78** [DevExpress/testcafe#6239]
What is your Test Scenario?
I'm trying to load https://dev.ccsweb.federated.fds/Marawebv2.0 our application dev environment and verify that the page loaded.

What is the Current behavior?
When I'm using node version 13.8.0, the page loads occasionally and most of the time get about:error in browser address bar. 

Console log error:
  1) - Error in fixture.beforeEach hook -
     Failed to load the page at "https://dev.ccsweb.federated.fds/Marawebv2.0/".
     Increase the value of the "pageRequestTimeout" variable, enable the "retryTestPages" option, or use quarantine mode to perform additional attempts to execute this test.
     You can find troubleshooting information for this issue at "https://go.devexpress.com/TestCafe_FAQ_ARequestHasFailed.aspx".      

     Error details:
     Failed to perform a request to the resource at "https://dev.ccsweb.federated.fds/Marawebv2.0/" because of an error.
     Error: connect ETIMEDOUT 11.120.113.22:443
	 
What is the Expected behavior?
I am expecting the page to load.

What is your web application and your TestCafe test code?
Using node version 13.8.0, and testcafe v1.14.2

import BaseTest from '@mtp/mtp-testcafe-core/lib/BaseTest'
import DriverManager from '@mtp/mtp-testcafe-core/lib/DriverManager';

fixture`UIAutomation-Dev Env`
    .meta('fixturepack', 'regression')
    .meta('Product', 'UI')
    .meta('Project', 'UI')
    .meta('Program', 'StepComponent')
    .page('https://dev.ccsweb.federated.fds/Marawebv2.0/')
    .httpAuth({
        username:'bcx001',
        password:'test'
    })
    .beforeEach(async t => {
        DriverManager.setDriver(t);
        await DriverManager.maximize(); 
        await t
        .setPageLoadTimeout(19500000)             
    })
   

  BaseTest.JSONDataSet("QAStepper.json", "Verify_the_Stepper_Component_Content_before_selecting_the_reason").forEach(data => {
    test
        .meta('description', 'ReasonStepperComponent')
        .meta('testpack', 'singleFile')
        .meta('testtype', 'smoke')
        .meta('module', 'Stepper Component')
        .meta('test', 'Reason Stepper')
        (data.testid, async t => {
         console.log('Loaded Succssfully');  

        });
    }); 
 

Steps to Reproduce:
Run the above code using Using node version 13.8.0, and testcafe v1.14.2
Notice that the website not loading and getting about: error in the browser address bar

Uur dev environment will popup windows authentication. It takes between 20-30 secs to loaded.  We have provided the credentials by using httpAuth. It works some times and most of the time it's timing out.

We tried below config as well and no use.

    "runnerOptions": {
        "skipJsErrors": true,
        "quarantineMode": true,
        "selectorTimeout": 1900000,
        "assertionTimeout":1900000,
        "pageLoadTimeout": 1900000,
        "pageRequestTimeout":1900000,
        "browserInitTimeout": 1900000,
        "speed": 0.1,
        "developmentMode": true
    }
	
Tried below directly in the script as well but no luck.
test
    .timeouts({
        pageLoadTimeout:    1900000,
        pageRequestTimeout: 1900000,
        ajaxRequestTimeout: 1900000
    })

command-line arguments: npm start
browser name and version: Chrome 90.0.4430.93
platform and version: windows 10

**WE ARE BLOCKED. ANY SUGESSTION and GUIDENCE WOULD BE APPRICIATED**

**Comment by AlexanderMoiseev** [comment]
Hello, unfortunately, this page is unavailable, so we could not reproduce the problem. Please make sure the page is loading without Testcafe in your browser

**Comment by ckswami78** [comment]
Thanks @AlexanderMoiseev . Our application launching without any issue in regular chrome browser. This is our internal site and it will not load out of our network. All We need is TestCafe team guidance to handle window based authentication popup that comes during initial launch of the application. This window authentication popup loads with a 15-25 secs delay. 

 Windows based authentication popup loads only in incognito window and Test cafe browser session.  We are entering the credentials in windows authentication popup using httpAuth function. Problems this works some time and not working in most of the times. With this issue we are struggling to use TestCafe. I can post a recorded video , let me know where I can post it.

Also we tried pageLoadTimeout,pageRequestTimeout as well but no luck. Really appreciate your guidance on this.

**Comment by ckswami78** [comment]
https://user-images.githubusercontent.com/67126541/118819104-03dd6680-b883-11eb-910e-fdb7812f324e.mp4

**Comment by ckswami78** [comment]
![Windows auth popup](https://user-images.githubusercontent.com/67126541/118819645-89611680-b883-11eb-8289-e5b8d5617b93.jpg)

**Comment by ckswami78** [comment]
Attached the video file and screen shot. Let me know in case of more data required.

**Comment by AlexanderMoiseev** [comment]
Hello. Unfortunately we can't help you without reproducing the problem, if you manage to provide the sample project, please reopen the issue.
