### ISSUE TITLE
Not able to test testcafe script on burp

### ISSUE THREAD

**Issue by ap0506** [DevExpress/testcafe#6240]
We have our application hosted on a server
We are testing the hosted application through testcafe.
Testcafe host application on http://172.31.17.23:60335 by adding unique session id to the application server URL 
Also this instance will be opened in a new chrome browser.
So the case is, whenever the test case got executed ,host 172 runs application by adding unique id to dev url.
After the test case got executed completely, the session got expired and that unique id becomes unreachable for burp, so then its shows abandoned to all the request from test café instance.

### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by Farfurix** [comment]
@ap0506 

Hello,

Your usage scenario is not clear to me. How do you use the TestCafe URL (with a session ID) in your "burp" test? Could you please share a simple project to illustrate your usage scenario?

**Comment by ap0506** [comment]
burp will scan the testcafe url..if i added it as a target

**Comment by ap0506** [comment]
to be more clearer-
Tried running Test Café scripts on burp, since Test Café is itself a proxy based tool, so it was creating one session on local machine using proxy setup, so burp was scanning the local machine IP with port number as host instead of using Application URL as host. All the requests going to server were having test café session id appended with the request.

**Comment by ap0506** [comment]
Once, Test Café execution is completed, session is closed and all the requests started giving abandoned errors.

**Comment by Farfurix** [comment]
@ap0506 

> burp will scan the testcafe url..if i added it as a target

I am not familiar with "burp". Please share a simple project (TestCafe and the use of "burp") that illustrates the issue.
