### ISSUE TITLE
TestCafé hangs & fails when a button click triggers a download in a separate browser window

### ISSUE THREAD

**Issue by mhanci92** [DevExpress/testcafe#6242]
### What is your Test Scenario?
As part of a test, we click on a button which leads to a document being downloaded. The download url is being supplied by our backend, and the frontend basically calls a window.open(documentUrl, "_blank") on it. TestCafe opens a blank window (about:blank), where the download is being completed in. 

### What is the Current behavior?
When a button is clicked that triggers a download, TestCafè opens a separate browser window and seems not to be able to switch to this download-window. Sooner or later the test runs into an error with the message "Cannot switch to the window.". 
 
### What is the Expected behavior?
TestCafé is able to continue with the test after clicking a button that triggers a download in a separate browser window.
 
### What is your web application and your TestCafe test code?
A minimal example to reproduce the mentioned problem:

The HTML-Code:
 ```html
<html>
  <head>
    <script>
      function download() {
        window.open("testcafe-download.zip");
      }
    </script>
  </head>
  <body>
    <h1>TestCafe Download</h1>
    <button onclick="javascript:download();">Download Test File</button>
  </body>
</html>
```

The TestCafé/TypeScript code to reproduce the problem:
```typescript
import { Selector, ClientFunction } from "testcafe";

fixture`My download tests`.page("file://C:/Users/path/to/testcafe-test.html");

test("First download test", async (t) => {
  const downloadButton = Selector("button");

  await t.expect(Selector("button").exists).ok("Seems like the page is missing key components!");
  await t.click(downloadButton);
});
```

The TestCafé/TypeScript code including a workaround that I came up with:
```typescript
import { Selector, ClientFunction } from "testcafe";

fixture`My download tests`.page("file://C:/Users/path/to/testcafe-test.html").beforeEach(async (t) => {
  console.log("Another test starts..");
});

const overrideWindowOpen = ClientFunction(() => {
  // @ts-ignore
  window.open = function (url) {
    // @ts-ignore
    window.__lastWindowOpenUrl = url;
  };
});

// @ts-ignore
const getLastWindowOpenUrl = ClientFunction(() => window.__lastWindowOpenUrl);

test("First download test", async (t) => {
  const downloadButton = Selector("button");

  await t.expect(Selector("button").exists).ok("Seems like the page is missing key components!");
  await overrideWindowOpen();
  await t.click(downloadButton);
  const downloadUrl = await getLastWindowOpenUrl();
  await t.navigateTo(downloadUrl); // navigate to the download-url within the same browser window to trigger the download in there
});
```
Calling the ClientFunction "overrideWindowOpen" right before clicking the button solved the issue for me as a workaround.

### Steps to Reproduce:

1. Save the given HTML code as well as zip folder with the name "testcafe-download.zip" together in one folder
2. Make sure that the page() call in the TestCafé/TypeScript code points correctly to the HTML file saved locally
3. Run your test command `testcafe chrome src/to/my/testfile.ts` (has to be adjusted accordingly)
4. See the blank window that pops up in which the download completes. TestCafé hangs from there and can not finish the test properly.
 
### Your Environment details:
 
* testcafe version: 1.14.2
* node.js version: 14.16.1
* command-line arguments:  testcafe chrome src/to/my/testfile.ts
* browser name and version: Chrome 90.0.4430.93
* platform and version: Windows 10

**Comment by maksnester** [comment]
I also caught the same issue when upgraded testcafe from "1.7.0" to "1.15.0". I checked what's different by running testcafe with `--live` flag and in 1.15 a new window is opened to download a file and it hangs the test:

![image](https://user-images.githubusercontent.com/4989157/127287104-6f2f04a5-d3f0-47d5-83ce-1c80cb129bc2.png)

While in 1.7.0 no new browser windows are opened, the downloaded file appears at the bottom of the browser window and the same test doesn't fail: 

![image](https://user-images.githubusercontent.com/4989157/127287848-05ca4c2c-afba-45ee-948e-af3f25963c7b.png)

**Comment by AlexanderMoiseev** [comment]
Hello,

Thank you for your input. We have reproduced the problem and need some time to investigate it, please stay tuned.
