### ISSUE TITLE
Unable to close the driver successfully

### ISSUE THREAD

**Issue by chetanhp** [DevExpress/testcafe#6245]
steps:
1) Open the UR L - https://ksrtc.in/oprs-web/
2) Hover on the Header section " Cancel Tickets" 

Output : Getting  an Error message "1) A JavaScript error occurred on "https://ksrtc.in/oprs-web/".
      Repeat test actions in the browser and check the console for errors.
      To ignore client-side JavaScript errors, enable the "--skip-js-errors" CLI option, or      
      set the "skipJsErrors" configuration file property to "true"."

and driver is quitting unexpectedly and testcase is getting failed.

Before submitting an issue, please check CONTRIBUTING.md and existing issues in this repository (https://github.com/DevExpress/testcafe/issues) in case a similar issue exists or was already addressed. This may save your time (and ours).
-->

### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by Farfurix** [comment]
@chetanhp 

Hello,

I see a lot of `Uncaught SyntaxError: Unexpected token = in JSON at position 1` errors (not some kind of "driver" error). This can be reproduced with the start page without any actions. My setup is Windows 10, Chrome 90, Node.js 14.17.0, and TestCafe v1.14.2.

**test.js**:
```js
fixture `Fixture`
    .page('https://ksrtc.in/oprs-web/');

test('test', async t => {
    // await t
    //     .hover('#navbarCollapse > ul > li:nth-child(3) > a');

    await t.debug();
});
```
**Command**: `testcafe chrome test.js`

**Result**:
![Capture](https://user-images.githubusercontent.com/30019338/119314575-93b55300-bc7d-11eb-938e-57a6977961ca.PNG)

Could you please clarify if you observe this "Uncaught SyntaxError" error?
