### ISSUE TITLE
Increasing the QUARANTINE_THRESHOLD to a large number still stops the test before the threshold is reached

### ISSUE THREAD

**Issue by Akshay-Kawlay** [DevExpress/testcafe#6246]
#### HEADS UP!

I changed the QUARANTINE_THRESHOLD and DISCONNECT_THRESHOLD  in test_run_controller.ts file to 1 million each and built successfully however, my test still fails after around 1000-10000 restarts with the error : 
`ERROR The Chrome 89.0.4389.90 / Linux 0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.`
Is there something else that may be forcing testcafe to quit? or is the issue in browser perhaps?

Another question I had was regarding testcafe's typetext function. If I by mistake do typetext on an element that does not accept text like a paragraph tag or div tag, then it waits for a long time instead of realizing the element is not typeable. (around 2 mins; sometimes more). The message I see is "waiting for element to appear" on the bottom of the browser. How do I set the timeout to a shorter value for that message to detect sooner?

Thank you

**Comment by AlexKamaev** [comment]
According to the error, your browser hangs for some reason. The problem could be in the way you organize your tests. It's likely that you have some code that leads to memory leaks, and after 1000-10000 restarts, your machine does not have enough RAM to run the browser.


Please clarify why you need to restart your tests 1000-10000 times.

>I changed the QUARANTINE_THRESHOLD and DISCONNECT_THRESHOLD in test_run_controller.ts file

We are working on the quarantine mode configuration, so you will have the capability to change quarantine options out of the box.

> Another question I had was regarding testcafe's typetext function. If I by mistake do typetext on an element that does not accept text like a paragraph tag or div tag, then it waits for a long time instead of realizing the element is not typeable. (around 2 mins; sometimes more). The message I see is "waiting for element to appear" on the bottom of the browser. How do I set the timeout to a shorter value for that message to detect sooner?

Please create a separate issue using the following link: https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=&template=bug-report.md

Please create a separate issue using the following link: [https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=&template=bug-report.md](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=&template=bug-report.md)

At this moment, I can only say that the described behavior is unexpected.
