### ISSUE TITLE
Incomplete call stacks in testcafe

### ISSUE THREAD

**Issue by IssacH** [DevExpress/testcafe#6251]
Hi @ai @rybesh @Mehul @NickCis @renancouto ,

I have one question which is related to the callstack in testcafe. Basically I have below test file:

test.js

import {t} from "testcafe";
import util1 from "./util1";
const utilins = new util1();
fixture`Basic`;

test(`Navigate to baidu`, async t => {
  await t.navigateTo("http://www.baidu.com");
  await utilins.assert();
});

And below util files:

util1.js

import {t} from "testcafe";
import util2 from "./util2";
export default class util1 {
  constructor() {
    this.util2 = new util2();
  }
  async assert() {
    await this.util2.log();
    throw new Error("This is an error!!!!");
  }
}

util2.js

import {t} from "testcafe";
export default class util2 {
  constructor() {}
  async log() {
    console.log("issac");
  }
}

Final callstack:

× Navigate to baidu

   1) Error: This is an error!!!!

      Browser: Chrome 90.0.4430.212 / Windows 10

          4 |  constructor() {
          5 |    this.util2 = new util2();
          6 |  }
          7 |  async assert() {
          8 |    await this.util2.log();
       >  9 |    throw new Error("This is an error!!!!");
         10 |  }
         11 |}
         12 |

         at <anonymous> (C:\testcafePOC\tests\modeler\util1.js:9:11)
         at asyncGeneratorStep (C:\testcafePOC\tests\modeler\util1.js:2:249)
         at _next (C:\testcafePOC\tests\modeler\util1.js:2:587)

 1/1 failed (2s)

After the execution of the test case, I can only see the call stack trace of util1.js, but I cannot see the stack trace for test.js. I already read [https://stackoverflow.com/questions/54239586/how-to-get-full-stack-trace-in-test-cafe-errors](url) and just wonder if it is possible now to get the full stack trace in testcafe.

Thanks very much!

Thanks,
Issac

**Comment by VasilyStrelyaev** [comment]
TestCafe currently shows call stacks "as is" if an error was thrown from a user's code. This behavior was introduced to prevent loss of important information, which could occur if the call stack of user functions was modified. As mentioned in the StackOverflow answer you linked, the call stack includes only functions called after the last `await`. It does not show earlier calls because of how Babel transpiles the async/await syntax.

**Comment by IssacH** [comment]
> TestCafe currently shows call stacks "as is" if an error was thrown from a user's code



> TestCafe currently shows call stacks "as is" if an error was thrown from a user's code. This behavior was introduced to prevent loss of important information, which could occur if the call stack of user functions was modified. As mentioned in the StackOverflow answer you linked, the call stack includes only functions called after the last `await`. It does not show earlier calls because of how Babel transpiles the async/await syntax.

Hi @VasilyStrelyaev ,
Thanks for your reply! And I found a flag '--async-stack-traces' which seems to be a solution for this issue. It's a flag for node, and currently when we use testcafe to start our tests, we simply call 'testcafe chrome ./tests', is there anyway to append a node flag when starting testcafe?

Thanks,
Issac

**Comment by miherlosev** [comment]
Hi @IssacH

The `Babel` compiler is necessary to support the modern JavaScript features for old Node.js versions and inject TestCafe's service utils. So, there is no such capability without using Babel. In the future, we will consider discontinuing Babel to speed up test compilation and show stack traces in the origin Node.js format.
