### ISSUE TITLE
Modal Dialog box action URL replaces to main page URL

### ISSUE THREAD

**Issue by Royals007** [DevExpress/testcafe#6254]
Hi all, Firstly i am very new to create an issues in git (if anything is not appropriate or correct place to post. please let me know). 
Am unable to figure out the issue which am facing. I opened a modal-dialog box(it should be pop up window-- which has some info form filled and save it). which I had already solved it -- but here action URL is confusing the testcafe.

![image](https://user-images.githubusercontent.com/64093554/119470291-7dc09480-bd48-11eb-87b0-655ea5c2302d.png)

When I run it, the modal dialog opened and replaced(in 2s) as main page URL with black and white window and executed (with out saving- because div element different).

how can I open my modal dialog as popup window and fill the form and save it!
Here is my sample code:

    export async function test() {
       // open urls by click functions here
    //required page was opened and searching the user exists or not
        const searchUserExists = 'user1'
        await t.typeText('[type="search"]', searchUserExists);
    
        const firstNameUser = "UserFirstName"
        const lastNameUser = "UserLastName"
        const emailUser = "moderator@moderator.de"
        await t.debug().click(' #ent_administration_user_new, .modal-body, 
        [action="null"]')  // worked
    
    **here problem  arises**
    
        await t.typeText(Selector("#user_firstname"), firstNameUser)
            .typeText(Selector("#user_lastname"), lastNameUser)
            .typeText(Selector("#user_username"), searchUserExists)
            .typeText(Selector("#user_email"), emailUser)
            .click(".save-item");
    }

@AndreyBelym @miherlosev @VasilyStrelyaev @AlexanderMoskovkin 
#symfony #testcafe #bootstrap4 #test #automated-tests #javascript

 ##3 Modal Dialog box action URL replaces to main page URL(blackedout) error

### Your Environment details:
 
* testcafe version:                   1.14.0
* node.js version:                     14.15.1
* command-line arguments:  
* browser name:  chrome
* platform and version:           macOS 10.15.7

**Comment by Royals007** [comment]
Please have a look at the sample Html and css for modal dialog.  [https://github.com/Royals007/Testcafe-sample](url).  But in my form there is an action URL which is replaces to the localhost URL (shown in below figure) instead of popup window.

![Bildschirmfoto 2021-05-27 um 17 57 13](https://user-images.githubusercontent.com/64093554/119859490-b8c3f300-bf15-11eb-9eff-3c91501df157.png)

**Comment by Dmitry-Ostashev** [comment]
Thank you for the example. Unfortunately, I can only see a blank page in the browser. I ran it by using the expressJS server. Сould you please share a full example that we can run without additional tweaks and with which we can reproduce the problematic behavior?
