### ISSUE TITLE
Mention examples are in Coffee-Script

### ISSUE THREAD

**Issue by quangv** [DevExpress/testcafe#6256]
### What is your Test Scenario?
https://testcafe.io/documentation/402635/getting-started

### What are you suggesting?

Hi, I'm new to testcafe, I was on the Getting Started page, the examples looked foreign to me, took me a minute to realize it's in coffee-script.

```
fixture `Getting Started`
    .page `http://devexpress.github.io/testcafe/example`;
```

The examples are in coffee-script correct? Suggesting it's called out / made more explicit that the examples are in coffee-script.

### What alternatives have you considered?
Alternatively covert examples to JS or TS, maybe just the "Getting Started" page so it doesn't force user to know coffee-script.

### Additional context
Please correct me if I'm wrong, and it's not coffee-script.

**Comment by viktoria2506** [comment]
On the “Getting started” page, tests are written in JavaScript with [template strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals). Also, you can read about TypeScript and CoffeScript support [here](https://testcafe.io/documentation/402824/guides/concepts/typescript-and-coffeescript).
