### ISSUE TITLE
Testcafe fails to run single fixture

### ISSUE THREAD

**Issue by soletan** [DevExpress/testcafe#6259]
### What is your Test Scenario?

Run single fixture in a set of fixtures.
 
### What is the Current behavior?

When invoking testcafe without `--fixture` a particular test implementation is processed. As soon as I provide the name of fixture used in that file in option `--fixture`, testcafe complains about all available tests being excluding by fixture filter.
 
### What is the Expected behavior?

Testcafe should find that single fixture and run it.
 
### What is your web application and your TestCafe test code?

It is closed source. Here are some excerpts illustrating my setup:

* Testcafe is invoked from scripts section in package.json defined like this:

      "test:e2e:regression": "testcafe chrome test/e2e/**/*.test.ts --fixture 'Regression: Bug #27897'"

* The related test file is in **test/e2e/regressions/27897.test.ts** and looks like this:

      import {adminUser, idpFix} from "../lib/idp-login";
      import {Selector} from "testcafe";
      
      fixture `Regression: Bug #27897`
          .clientScripts(idpFix);
      
      test('transport order sorting after activating manual order', async t => {
          await t.click( "button" );
      });

When I invoke the script **test:e2e.regression**, it fails:

    > testcafe chrome test/e2e/**/*.test.ts --fixture 'Regression: Bug #27897'
    
    ERROR The specified filter settings exclude all tests.
    Modify these settings to leave at least one available test.
    For more information on how to specify filter settings, see https://devexpress.github.io/testcafe/documentation/using-testcafe/configuration-file.html#filter.

When I remove the `--fixture 'Regression: Bug #27897'` the illustrated test is processed.
 
### Your Environment details:
 
* testcafe version:                   1.14.2
* node.js version:                    14.17.0
* command-line arguments:  testcafe chrome test/e2e/**/*.test.ts --fixture 'Regression: Bug #27897'
* browser name and version: Chrome 90
* platform and version:          Windows 10 20H2

**Comment by AlexanderMoiseev** [comment]
Hello,

Unfortunately, we could not reproduce this behavior. What terminal do you use? Have you tried running tests from your terminal directly? If not, please try this.
If the problem still persists, send us an example project.

**Comment by soletan** [comment]
Basically, I used to start this via npm integration tool included with PhpStorm IDE. Tried running it from terminal integrated there as well which is Git Bash for Windows. Eventually I tried cmd.exe and Git Bash for Windows started as separate processes.

via npm from IDE: not working
via npm from terminal in IDE: not working
via npm from separate Git Bash: not working
via npm from cmd.exe: not working
using npx w/o npm from terminal in IDE: not working
using npx w/o npm from Git Bash: working
using npx w/o npm from cmd.exe: not working

AFAICS, npm fails no matter which way it is started. when omitting npm, using separate Git bash seems to be only working option.

**Comment by AlexanderMoiseev** [comment]
Hello, use double quotes instead of single ones. Please note that your quotes in the package.json file should be escaped with the \ character, e.g. 

"test:e2e:regression": "testcafe chrome test/e2e/**/*.test.ts --fixture \"Regression: Bug #27897\""

**Comment by soletan** [comment]
Yes, that's solving the issue ... strange, though ...
