### ISSUE TITLE
Instead of babel, is there any way to use node original mechanism to interpret the modules?

### ISSUE THREAD

**Issue by IssacH** [DevExpress/testcafe#6270]
Hi guys,

Currently we are facing a problem in testcafe that the callstack will be incomplete when we are using page object to organize our async/await util functions. We could only see the file causing the error, but we could not see the full call stack information. Since node with latest version has a flag '--async-stack-traces' and I did some testing with this flag and I can see a clear callstack for all the async functions. So is there any chance for testcafe not to use babel but to use node original mechanism to interpret the modules? Or do you have any other solution now to show a complete full stack trace for testcafe?

Reference:
https://stackoverflow.com/questions/54239586/how-to-get-full-stack-trace-in-test-cafe-errors

Thanks,
Issac

**Comment by VasilyStrelyaev** [comment]
There is no such capability at present. Please see the detailed explanation in [this comment](https://github.com/DevExpress/testcafe/issues/6251#issuecomment-852076584).
