### ISSUE TITLE
Element not visible when running test using testcafe docker image but visible in local (Google login page)

### ISSUE THREAD

**Issue by edgarmfarias** [DevExpress/testcafe#6278]
### What is your Test Scenario?
I'm trying to login into https://accounts.google.com/signin/v2 through a pipeline using the testcafe docker image in Drone.io
 
### What is the Current behavior?
Locally, I can login without any issue, but when running it in a pipeline (Drone.io) and clicking the Google's next button after entering the email, nothing seems to happen (also tried with pressKey('enter')), since the password field never becomes visible.
 
### What is the Expected behavior?
After entering the email and clicking on the next button, the password field should be displayed, so that a successful login happens.
 
### What is your web application and your TestCafe test code?
 
<details>
<summary>https://accounts.google.com/signin/v2</summary>
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 

#### LOGIN PAGE:

```js
 import { t, Selector } from "testcafe";

class LoginPage {
  constructor() {
    this.usernameGoogleText = Selector("input[type='email']");
    this.passwordGoogleText = Selector("input[type='password']");
    this.loginWithGoogleButton = Selector("div")
      .withText(/log in with google/i)
      .parent("a[type='button']");
    this.continueGoogleButton = Selector("span")
      .withText(/siguiente|next/i)
      .parent("button");
    this.twoStepVerificationLabel =
      Selector("span").withText(/2-step verification/i);
  }

  async loginWithGoogle(username, password) {
    await t
      .click(this.loginWithGoogleButton)
      .typeText(this.usernameGoogleText, username)
      .click(this.continueGoogleButton)
      .typeText(this.passwordGoogleText, password)
      .click(this.continueGoogleButton)
      .expect(this.twoStepVerificationLabel.exists)
      .notOk({ timeout: 60000 });
  }
}

export default new LoginPage();
```

#### TEST
```js
import { BASE_URL, CREDENTIALS } from "../data/constants";

import { LoginPage } from "../pages";

fixture("Login feature").page`${BASE_URL}`;

test("Log in with a regular Google user", async (t) => {
  await LoginPage.loginWithGoogle(
    CREDENTIALS.REGULAR_USER_NAME,
    CREDENTIALS.REGULAR_USER_PASSWORD
  );
});
```

#### PIPELINE CONFIG FILE
```yml
  - name: e2e-tests
    image: testcafe/testcafe
    failure: ignore
    environment:
      TESTCAFE_SLACK_WEBHOOK:
        from_secret: testcafe_slack_webhook
      AUTOMATION_USER_NAME:
        from_secret: automation_user_name
      AUTOMATION_USER_PASSWORD:
        from_secret: automation_user_password
    commands:
      - /opt/testcafe/docker/testcafe-docker.sh chromium packages/e2e/src/tests/*
  when:
    branch:
      - develop
      - feature/*
      - hotfix/*
      - support/*
      - bugfix/*
      - feature_*
      - hotfix_*
      - test/*
```

Any google credentials can be used
</details>

<details>
<summary>Your complete test report:</summary>
```
+ /opt/testcafe/docker/testcafe-docker.sh 'chromium --no-sandbox --disable-dev-shm-usage' packages/e2e/src/tests/*  
--  
2 | Running tests in:  
3 | - Chrome 90.0.4430.93 / Linux 0.0  
4 | &nbsp;  
5 | Login feature. 
6 | &nbsp;  
7 | ✖ Log in with a regular Google user  
8 | &nbsp;  
9 | 1) - Error in Role initializer -  
10 | The element that matches the specified selector is not visible.  
11 | &nbsp;  
12 | Browser: Chrome 90.0.4430.93 / Linux 0.0  
13 | &nbsp;  
14 | &nbsp;  
15 | 19 \| .click(this.loginWithGoogleButton)  
16 | 20 \| .typeText(this.usernameGoogleText, username)  
17 | 21 \| .wait(3000)  
18 | 22 \| .click(this.continueGoogleButton)  
19 | 23 \| .wait(3000)  
20 | >>> 24 \| .typeText(this.passwordGoogleText, password)  
21 | 25 \| .wait(3000)  
22 | 26 \| .click(this.continueGoogleButton);  
23 | 27 \| await t  
24 | 28 \| .expect(this.twoStepVerificationLabel.exists)  
25 | 29 \| .notOk({ timeout: 60000 });  
26 | &nbsp;  
27 | at &lt;anonymous&gt;  
28 | (/drone/src/packages/e2e/src/pages/Login.page.js:24:8)  
29 | at asyncGeneratorStep  
30 | (/drone/src/packages/e2e/src/pages/Login.page.js:1:251)  
31 | at _next (/drone/src/packages/e2e/src/pages/Login.page.js:1:589)  
32 | at &lt;anonymous&gt;  
33 | (/drone/src/packages/e2e/src/pages/Login.page.js:1:754)  
34 | at &lt;anonymous&gt;  
35 | (/drone/src/packages/e2e/src/pages/Login.page.js:1:495)  
36 | at LoginPage.loginWithGoogle  
37 | (/drone/src/packages/e2e/src/pages/Login.page.js:17:45)  
38 | at &lt;anonymous&gt;  
39 | (/drone/src/packages/e2e/src/helpers/roles.js:6:19)  
40 | at asyncGeneratorStep  
41 | (/drone/src/packages/e2e/src/helpers/roles.js:3:134)  
42 | at _next (/drone/src/packages/e2e/src/helpers/roles.js:3:472)  
43 | at &lt;anonymous&gt;  
44 | (/drone/src/packages/e2e/src/helpers/roles.js:3:637)  
45 | &nbsp;  
46 | &nbsp;   
47 | &nbsp;  
48 | 1/1 failed (39s)  
```

</details>

<details>
<summary>Screenshots:</summary>
<img width="1028" alt="Screen Shot 2021-06-02 at 9 49 59" src="https://user-images.githubusercontent.com/72106062/120503142-a5d37780-c388-11eb-86bd-3a63564745fb.png">
</details>
### Steps to Reproduce:

Executing through a pipeline:

1. Go https://accounts.google.com/signin/v2
2. Enter google email
3. Click on the next button

(Basically just executing the test pasted above)
 
### Your Environment details:
 
* testcafe version: testcafe image 1.14.2
* node.js version: testcafe image 1.14.2                  
* command-line arguments:  /opt/testcafe/docker/testcafe-docker.sh chromium:headless packages/e2e/src/tests/* 
* browser name and version: Chrome 90.0.4430.93 
* platform and version:          Linux 0.0
* other:  everything was run inside a docker container with the testcafe image v1.14.2 through Drone.io

**Comment by Farfurix** [comment]
@edgarmfarias 

Hello,

There is a platform independent issue related to the Google login. You received a security message after clicking the continue button. I'll close this issue as a duplicate. You can track [the original thread](https://github.com/DevExpress/testcafe-hammerhead/issues/2438).
