### ISSUE TITLE
Bug? how the offending method in the chain is highlighted

### ISSUE THREAD

**Issue by fmancardi** [DevExpress/testcafe#6281]
### What is your Test Scenario?
The following code fails because data-value attribute is not '='
```
await t.click(
Selector('#filters_g1')
  .find('button')
  .withAttribute('data-bound-to', 'txtDataInValMat_op')
  .sibling('ul')
  .find('li')
  .withAttribute('data-value', '=')
)
```
### What is the Current behavior?

According to the documentation: 
An error can also occur when you call a selector’s methods in a chain.   
These methods are applied to the selector one by one.   
**TestCafe detects the first method that returns no elements and highlights it in the error message**

         | Selector('#filters_g1')
       > |   .find('button')
         |   .withAttribute('data-bound-to', 'txtDataInValMat_op')
         |   .sibling('ul')
         |   .find('li')
         |   .withAttribute('data-value', '=')
 
### What is the Expected behavior?

         | Selector('#filters_g1')
         |   .find('button')
         |   .withAttribute('data-bound-to', 'txtDataInValMat_op')
         |   .sibling('ul')
         >|   .find('li')
         |   .withAttribute('data-value', '=')

May be I've misunderstood the documentation

### Your Environment details:
* testcafe version:         1.14.2
* node.js version:          14.15.5
* browser name and version:  91.0.4472.77 (Official Build) (64-bit)
* platform and version:         Windows 10

**Comment by fmancardi** [comment]
I've created a simple sample HTML file, and it works as expected, here the sample
```
<html>

<body>
  <div id="filters_g1">
    <div class="col-md-3">
      <div class="form-group data ">
        <label class="form-label" for="txtDataInValMat"><span title="Validità">Validità</span><span class="pin"></span></label>
        <div class="input-group">
          <div class="input-group-btn">
            <button data-bound-to="txtDataInValMat_op" type="button" class="btn btn-default dropdown-toggle operator-selected" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            =
            </button>
            <ul class="dropdown-menu operator-list" data-bound-to="txtDataInValMat_op">
              <li class="" data-value="9"><a href="#">&lt;</a></li>
              <li class="" data-value="10"><a href="#">&gt;</a></li>
              <li class="" data-value="11"><a href="#">≤</a></li>
              <li class="" data-value="12"><a href="#">≥</a></li>
              <li class="selected" data-value="13"><a href="#">=</a></li>
              <li class="" data-value="14"><a href="#">≠</a></li>
            </ul>
            <select id="txtDataInValMat_op" name="txtDataInValMat_op" class="hidden">
              <option value="9">&lt;</option>
              <option value="10">&gt;</option>
              <option value="11">≤</option>
              <option value="12">≥</option>
              <option selected="" value="13">=</option>
              <option value="14">≠</option>
            </select>
          </div>
          <div class="input-append input-group date" data-type="date" data-date-format="DD/MM/YYYY">
            <input type="text" class="form-control text-left " data-date-format="DD/MM/YYYY" data-date-extra-formats="[&quot;DDMMYY&quot;, &quot;DDMMYYYY&quot;]" placeholder="dd/mm/yyyy" id="txtDataInValMat" name="txtDataInValMat" value="05/06/2021" data-type="date" autocomplete="off">
            <span class="input-group-addon add-on"><span class="arrow"></span><i class="fa fa-calendar"></i></span>
          </div>
        </div>
      </div>
    </div>
  </div>  
</body>
</html>
```

But when running in my application the error highlight is wrong!
I suppose it will not be easy for you to reproduce it :(

**Comment by fmancardi** [comment]
here the test script

```
import { Selector, t, ClientFunction } from 'testcafe';

fixture `issue`
    .page `http://localhost:81/testlink/tcaf.html`;

test
 .meta({'WKFSTATUS': 'ready',
        '6.3': 'yes'})
    ('ac', async t => {

  var e= Selector('#filters_g1');
  await t.click(e);  

  var e= Selector('#filters_g1')
          .find('button')
  await t.click(e);  

  var e= Selector('#filters_g1')
          .find('button')
          .withAttribute('data-bound-to', 'txtDataInValMat_op')
  await t.click(e);  


  var e= Selector('#filters_g1')
          .find('button')
          .withAttribute('data-bound-to', 'txtDataInValMat_op')
          .sibling('ul')
  await t.click(e);  

  var e= Selector('#filters_g1')
          .find('button')
          .withAttribute('data-bound-to', 'txtDataInValMat_op')
          .sibling('ul')
          .find('li')
  await t.click(e);  

  var e= Selector('#filters_g1')
          .find('button')
          .withAttribute('data-bound-to', 'txtDataInValMat_op')
          .sibling('ul')
          .find('li')
          .withAttribute('data-value', '=');
  await t.click(e);  


});

```

**Comment by VasilyStrelyaev** [comment]
I checked your example - indeed, it works as expected. Unfortunately, we cannot investigate an issue without a reproducible example. I'm closing this issue, but you are free to update your example once you discover which part of your app causes the problematic behavior.

Alternatively, you can mail the URL and credentials for your app to [support@devexpress.com](mailto:support@devexpress.com) if the app is accessible from the Internet. In that case, please ask the website owner to [send us](mailto:support@devexpress.com) written confirmation. It must permit DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes.
