### ISSUE TITLE
Browser disconnect issue -  Console contains multiple ERR_INVALID_HTTP_RESPONSE

### ISSUE THREAD

**Issue by apoleon1001** [DevExpress/testcafe#6292]
### Are you requesting a feature or reporting a bug?
Bug

### What is your Test Scenario?
import { Selector } from 'testcafe';

fixture`Getting Started`
    .page`http://devexpress.github.io/testcafe/example`;

test('My first test', async t => {
    await t
        .typeText('#developer-name', 'John Smith')
        .click('#submit-button')

        // Use the assertion to check if the actual header text is equal to the expected one
        .expect(Selector('#article-header').innerText).eql('Thank you, John Smith!');
});

### What is the Current behavior?
Browser starts but nothing happens on the page.
---------------------------------
From the Browser console:

Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
192.168.0.220/:8 GET http://192.168.0.220:55408/hammerhead.js net::ERR_INVALID_HTTP_RESPONSE
192.168.0.220/:8 GET http://192.168.0.220:55408/testcafe-driver.js net::ERR_INVALID_HTTP_RESPONSE
192.168.0.220/:8 GET http://192.168.0.220:55408/testcafe-automation.js net::ERR_INVALID_HTTP_RESPONSE
testcafe-core.js:1 Uncaught TypeError: Cannot read property 'utils' of undefined
    at testcafe-core.js:1
(anonymous) @ testcafe-core.js:1
testcafe-ui.js:1 Uncaught TypeError: Cannot read property 'utils' of undefined
    at testcafe-ui.js:1
(anonymous) @ testcafe-ui.js:1
task.js:1 Uncaught TypeError: Cannot read property 'utils' of undefined
    at task.js:1
(anonymous) @ task.js:1
(index):8 Uncaught TypeError: Cannot read property 'sandbox' of undefined
    at (index):8
    at (index):8
(anonymous) @ (index):8
(anonymous) @ (index):8
jquery-1.12.4.min.js:3 Uncaught TypeError: __call$ is not a function
    at jquery-1.12.4.min.js:3
    at jquery-1.12.4.min.js:3
    at jquery-1.12.4.min.js:3
(anonymous) @ jquery-1.12.4.min.js:3
(anonymous) @ jquery-1.12.4.min.js:3
(anonymous) @ jquery-1.12.4.min.js:3
jquery-ui.min.js:7 Uncaught ReferenceError: jQuery is not defined
    at jquery-ui.min.js:7
    at jquery-ui.min.js:7
(anonymous) @ jquery-ui.min.js:7
(anonymous) @ jquery-ui.min.js:7
(index):12 Uncaught ReferenceError: $ is not defined
    at (index):12

### Your Environment details:
 
* testcafe version:                   1.14.2
* node.js version:                    14.17.0
* command-line arguments:  testcafe chrome ./Login.js
* browser name and version: Chrome 91.0.4472.77
* platform and version:          macOS 10.15.7

**Comment by Dmitry-Ostashev** [comment]
I wasn't able to reproduce the issue. I can see just the warning in the browser console, but the test is passed. Could you please try to run the test with the `--hostname localhost` argument?

For the team: possibly related to this issue: [https://github.com/DevExpress/testcafe/issues/624](https://github.com/DevExpress/testcafe/issues/6241)

**Comment by apoleon1001** [comment]
When I use the --hostname localhost everything is working fine. Can you explain me why I need this? Until last week every script worked fine without this parameter!

**Comment by VasilyStrelyaev** [comment]
Most probably, this behavior is caused by [this Node.js issue](https://github.com/nodejs/node/issues/38709), which, in turn, is caused by the Network Monitor component in macOS. We will keep track of the progress with these issues. In the meantime, please use the workaround with `--hostname`.

**Comment by ArmandoAmador** [comment]
Hi, I was having the same issue as @apoleon1001 until I saw the `--hostname` workaround. 🥇 

Is there a workaround for the case when you use `testcafe remote` command? The Browser starts but nothing happens on the page. 😢

**Comment by VasilyStrelyaev** [comment]
I posted my reply in the https://github.com/DevExpress/testcafe/issues/6241 issue.
