### ISSUE TITLE
Slow performance during test execution

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe#6297]
See the following SC ticket for details: https://supportcenter.devexpress.com/internal/ticket/details/T1005405
 
https://github.com/DevExpress/testcafe-studio/issues/3853

* testcafe version:                   1.14.2
* node.js version:                    12.19
* browser name and version: Chrome
* platform and version:          Win 10, Debian 10

**Comment by miherlosev** [comment]
Click on `Filter` icon (` .click(Selector('#RDT').nth(1).find('.fa.fa-list-alt'))`) without TestCafe executes about 10 sec.
With TestCafe it takes about 75 sec. So, it looks like as hung.

Note, the tested site can be unstable and display some server errors.
