### ISSUE TITLE
[REQUEST] Upgrade typescript dependancy to v4.x.x]

### ISSUE THREAD

**Issue by Linoyperetz** [DevExpress/testcafe#6299]
### What is your Test Scenario?
Trying to run a .ts file that uses aws-sdk v3 package that requires typescript version older than 4. (Because of a compilation error with typescript lower than that). The issue we have is https://github.com/aws/aws-sdk-js-v3/issues/1842#issuecomment-752162592, while I see that testcafe dev dependency is using with 3.9.9. Even tough locally I have typescript v4, testcafe dependancy is avoiding me to use aws-sdk v3 due to the compilation issue. 

### What is the Current behavior?
Testcafe is using Typescript 3.9.9

### What is the Expected behavior?
Typescript version will be updated. 
 
### What is your web application and your TestCafe test code?
Getting a compilation error which does not reproduced when running with JS compiler. 

 
### Your Environment details:
 
* testcafe version:                   1.14.0
* node.js version:                    10.24.1
* browser name:                      Chrome
* platform and version:          macOS 10.15.7

**Comment by wentwrong** [comment]
You can specify a custom compiler to compile your tests with a different version of TypeScript:
```
testcafe chrome test.ts --compiler-options typescript.customCompilerModulePath=../typescript@4
```
You can find the documentation for this feature here: https://testcafe.io/documentation/402639/reference/command-line-interface#--compiler-options-options.
