### ISSUE TITLE
Performance & stability problems in TestCafe 1.14.2 & 1.15.0-rc.1 not present in 1.14.0

### ISSUE THREAD

**Issue by PaulMEdwards** [DevExpress/testcafe#6304]
We're experiencing stability and performance problems in our otherwise stable & performant mature test collection against our Ember web application which has not changed in months following the update of TestCafe from 1.14.0 to 1.14.2.

Here are metrics collected from running the entire collection:

* 1.14.0
`178 passed (11m 34s)`
* 1.14.2
`53/178 failed (1h 11m 30s)`
* 1.15.0-rc.1
`51/178 failed (59m 19s)`

The failures are inability to locate elements due to the page simply not rendering before timing out. I have even tried increasing the page load timeout from 10 seconds to 5 minutes without significant improvement. By the way, all run times above are with the page timeout set to 10 seconds.

I previously misdiagnosed this as being due to a critical asset file being too large to cache causing the issue, and submitted [testcafe-hammerhead feature request #2638](https://github.com/DevExpress/testcafe-hammerhead/issues/2638) for the ability to increase the maximum size of cached assets, but I've now determined that is NOT the issue and the problem began after updating TestCafe from 1.14.0 to 1.14.2, and is resolved by downgrading TestCafe back to 1.14.0.

### What is your Test Scenario?

Our regularly run entire suite of tests.

### What is the Current behavior?

The tests are taking dramatically more time to run and a large number of them are failing due to the page just not rendering after upgrading TestCafe beyond 1.14.0.

### What is the Expected behavior?

The tests would continue to run with similar performance and reliability after upgrading from 1.14.0.

### What is your web application and your TestCafe test code?

<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

The AUT contains sensitive private data and is secured by multiple layers of access controls, so I cannot provide you access to it at this time. However, I have inquired with my superiors about granting you access since I know it may be critical for you to troubleshoot, debug, and resolve this issue. They would need to understand your procedures for accessing sites with sensitive data prior to granting access.

<details>
<summary>Your complete test code (or attach your test files):</summary>

 

</details>

<details>
<summary>Your complete configuration file (if any):</summary>

</details>

I have prepared a stripped down subset of our test code and configuration file, which does reproduce the issue, that I will provide privately once your access approval has been granted.

<details>
<summary>Your complete test report:</summary>

</details>

[reports.zip](https://github.com/DevExpress/testcafe/files/6635854/reports.zip)

<details>

</details>

### Steps to Reproduce:

1. Run our tests against our webapp using TestCafe 1.14.0 ... all pass quickly
2. Update to TestCafe 1.14.2 and/or 1.15.0-rc.1 and re-run the tests ... they run much slower and some fail inexplicably

### Your Environment details:

* testcafe version:                   1.14.0 / 1.14.2 / 1.15.0-rc.1
* node.js version:                    14.17.0 (current LTS)
* command-line arguments:  `npx testcafe chrome specs/* -c 4`
* browser name and version: Chrome 91.0.4472.101
* platform and version:          macOS 11.4 Big Sur

**Comment by PaulMEdwards** [comment]
My superiors asked if a video recording of the issue or a remote support session would be sufficient for your investigation or if you would require access to the AUT from your network for debugging/troubleshooting? If you would require access, they may need you to sign an NDA.

**Comment by miherlosev** [comment]
Hi @PaulMEdwards

In our experience, a remote support session is inconvenient and requires a lot of preliminary preparation. It doesn't guarantee that we will find the cause of the problem during it. This is why we don't conduct them.

We need a possibility of reproducing the issue locally anytime without any additional setup and approvals with third parties. So, we need a complete example without sensitive data.
Feel free to reopen this issue if you can prepare an example that can be shared in this thread.

**Comment by PaulMEdwards** [comment]
@Aaronius you liked this, are you experiencing similar?

**Comment by Aaronius** [comment]
My like was mostly regarding increased instability, but it turns out the instability we've experienced wasn't introduced between 1.14.0 and 1.14.2, but before that.

**Comment by duhseekoh** [comment]
Same issue here. Any upgrade beyond 1.14.0 and test times DRASTICALLY increase. Was hoping 1.16.0 would've fixed it, but same problem as with 1.15.0.
