### ISSUE TITLE
"Cannot read property 'tests' of null" when using client scripts

### ISSUE THREAD

**Issue by Aaronius** [DevExpress/testcafe#6305]
### What is your Test Scenario?
My test scenario can be as simple as this:

```
fixture`Getting Started`.page`http://devexpress.github.io/testcafe/example`;

test("My first test", async t => {
  // Test code
});
```

But this issue isn't so much about my test scenario as it is configuring the testcafe runner with clientScripts. Here's my setup:

```js
await testcafe
    .createLiveModeRunner()
    .clientScripts("preventSpecificErrorsFromFailingTests.js")
    .src(testsDir)
    .browsers("chrome")
    .run();
```

### What is the Current behavior?

I receive the following error in the console:

```
TypeError: Cannot read property 'tests' of null
    at LiveModeRunner._finishPreviousTestRuns (/Users/aahardy/dev/reactor-extension-alloy/node_modules/testcafe/src/live/test-runner.js:151:38)
    at LiveModeRunner.runTests (/Users/aahardy/dev/reactor-extension-alloy/node_modules/testcafe/src/live/test-runner.js:36:21)
    at /Users/aahardy/dev/reactor-extension-alloy/node_modules/testcafe/src/live/test-runner.js:113:30
Error: Cannot load a client script from preventSpecificErrorsFromFailingTests.js.
    at ClientScript._loadFromPath (/Users/aahardy/dev/reactor-extension-alloy/node_modules/testcafe/src/custom-client-scripts/client-script.ts:64:19)
    at ClientScript.load (/Users/aahardy/dev/reactor-extension-alloy/node_modules/testcafe/src/custom-client-scripts/client-script.ts:91:13)
    at async Promise.all (index 0)
    at Object.default_1 [as default] (/Users/aahardy/dev/reactor-extension-alloy/node_modules/testcafe/src/custom-client-scripts/load.ts:11:5)
    at LiveModeBootstrapper.createRunnableConfiguration (/Users/aahardy/dev/reactor-extension-alloy/node_modules/testcafe/src/runner/bootstrapper.ts:419:37)
```
 
### What is the Expected behavior?
A successful test run. Note that if I remove the `.clientScripts("preventSpecificErrorsFromFailingTests.js")` line, the test run completes just fine. Currently my `preventSpecificErrorsFromFailingTests.js` file contains no content, but it doesn't really matter what I put in that file.

 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 fixture`Getting Started`.page`http://devexpress.github.io/testcafe/example`;

test("My first test", async t => {
  // Test code
});

```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
#!/usr/bin/env node
const path = require("path");
const createTestCafe = require("testcafe");
const testsDir = path.join(__dirname, "../test/sample");

(async () => {
  const testcafe = await createTestCafe("localhost", 1337, 1338);
  const failedCount = await testcafe
    .createLiveModeRunner()
    .clientScripts("preventSpecificErrorsFromFailingTests.js")
    .src(testsDir)
    .browsers("chrome")
    .run();
  testcafe.close();
  process.exit(failedCount ? 1 : 0);
})();

```
</details>

<details>
<summary>Your complete test report:</summary>

N/A
</details>

<details>
<summary>Screenshots:</summary>
N/A
</details>

### Steps to Reproduce:

1. Clone https://github.com/Aaronius/testcafe-bugs
2.  Checkout the `client-scripts` branch
3. Run `npm install`
4. Run `npm test`
### Your Environment details:
 
* testcafe version: 1.14.2                  
* node.js version: 14.16.1                    
* command-line arguments: None, just using the library as described.  
* browser name and version: Chrome 91 
* platform and version: Mac Catalina          
* other:

**Comment by miherlosev** [comment]
Hi @Aaronius 

Thank you for the shared example. I've reproduced the issue.
