### ISSUE TITLE
.with() seems to modify the existing selector, rather than return a new one

### ISSUE THREAD

**Issue by stephenryanlee** [DevExpress/testcafe#6306]
### What is your Test Scenario?

I have a function that will add `.with({visibilityCheck: true})` to selectors at various times when needed. 

### What is the Current behavior?

If you save a selector to a variable, and then add that .with() to it, it will permanently alter the variable 

### What is the Expected behavior?

According to the [documentation](https://testcafe.io/documentation/402743/reference/test-api/selector/with), it's supposed to return a new selector

### What is your web application and your TestCafe test code?
<summary>Your complete test code (or attach your test files):</summary>

 
```js
import { Selector } from "testcafe";

// Here's a function I wrote to help print out what a selector chain looks like
function printSelector(selector) {
console.log(selector[Object.getOwnPropertySymbols(selector)[0]].options.apiFnChain.join(""));
}

let mySelector = Selector('button').withText('foo');
printSelector(mySelector);
// prints Selector('button').withText('foo')

await mySelector.with({visibilityCheck: true});
printSelector(mySelector);
// prints Selector('button').withText('foo').with({ visibilityCheck: true })

await mySelector.with({visibilityCheck: true});
await mySelector.with({visibilityCheck: true});

printSelector(mySelector);
// prints Selector('button').withText('foo').with({ visibilityCheck: true }).with({ visibilityCheck: true }).with({ visibilityCheck: true })


```

In all three of those print statements, I would _not_ expect to see it print the .with()

### Steps to Reproduce:

1. Run the above test code in any testcafe file
 
### Your Environment details:
 
* testcafe version: 1.7.1                  
* node.js version: 11.10.1

**Comment by miherlosev** [comment]
Hi @stephenryanlee

The phrase `return a new selector` means that changing public [options](https://testcafe.io/documentation/402743/reference/test-api/selector/with#options) of the initial selector doesn't affect public options of a new selector.
`options.apiFnChain` is an internal API and you should not use it for any purposes.
If you found an issue with the `with` method, please prepare an example that uses a public API. Feel free to reopen this issue and share it.
