### ISSUE TITLE
Testcafe not failing the test on page load fail 404

### ISSUE THREAD

**Issue by aman9922** [DevExpress/testcafe#6307]
One of the webpage is throwing 404 and the test case is not getting failed instead it got stuck. Because of this we are not able to complete the test run and report is also not generating.

beforeEach() is also not executing and browser is reloading after a certain time again and again but the test is not failing and testcafe is stucked in the same test.

We are not able to run our automation tests using Testcafe because of this issue.

 
### What is your web application and your TestCafe test code?
This is the HTML content of the page.
<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">default backend - 404</pre></body></html>

fixture`fixture name`.page`${config.baseUrl + "/endpoint"}`
    .beforeEach(async t => {
        await t.maximizeWindow()
    });

test('testcase name', async t => {
 //testcafe code
});
 
### Your Environment details:
 
* testcafe version:                  1.14.0
* node.js version:                    v14.16.0
* browser name and version  Chrome, Firefox 
* platform and version:         macOS catalina

**Comment by aman9922** [comment]
<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">default backend - 404</pre></body></html>
This is the HTML content of the page.

fixture`Current page `.page`url of the page with the above content`
.beforeEach(async t => {
await t.maximizeWindow()
});

test('verify title', async t => {
//code to verify title
});

After navigating to the given url, Testcafe is not even maximising the window based on before each method and it is not even failing the test. Instead it reloads the same test again and again after few minutes.
Do let me know if you need more details.

**Comment by aleks-pro** [comment]
Hello @aman9922,

It looks like the problem you are facing is similar to the one from [this issue](https://github.com/DevExpress/testcafe/issues/1471). Could you check if you can reproduce it by using TestCafe v1.15.0-rc.1?

**Comment by aman9922** [comment]
Hi @aleks-pro 

TestCafe v1.15.0-rc.1 is solving the issue. Thanks
