### ISSUE TITLE
Failing tests on initial focus in iFrame

### ISSUE THREAD

**Issue by JPeer264** [DevExpress/testcafe#6318]
### What is your Test Scenario?
I have an iFrame with some initial set `.focus()` on the first given input. When clicking to the second input the blur event from the first input should be called to display another div.
 
### What is the Current behavior?

`.blur()` will not get triggered if set `.focus()` initially on the page load
 
### What is the Expected behavior?

The `.blur()` event should get triggered.
 
### What is your web application and your TestCafe test code?

https://github.com/JPeer264/testcafe-repro

### Steps to Reproduce:

Everything inside the repo.

After some investigation I found that #5556 introduced this bug (`v1.9.4` works fine, `v1.9.5-rc.1` does not). More specifically these lines: 

https://github.com/DevExpress/testcafe/blob/4d16eb2e6b3e29e6ee0aad9004a8f8a587e88120/src/client/automation/utils/utils.js#L58-L62
 
When I remove this if and run my tests again then everything works. Unfortunately my expertise in debugging any further in testcafe are too low to go any deeper. But I hope this helps to investigate on your side any further.

Maybe related: #6008

### Your Environment details:
 
* testcafe version: v1.14.2
* node.js version: v14.16.0
* command-line arguments: -
* browser name and version: Chrome 91.0.4472.101, Firefox 89, Safari 14.0.3
* platform and version: macOS 10.15.7 (as displayed in the testcafe startup window), actual os version 11.2.1 (displayed in `About This Mac`)
* other: -

**Comment by wentwrong** [comment]
Thank you for sharing such a good example and for identifying the commit that introduced the bug. I reproduced the problem.

As a workaround, you can manually trigger the "blur" event as follows:

```js
test('dispatching the "blur" event manually should work', async (t) => {
  await t
    .navigateTo('http://localhost:1235')
    .switchToIframe(Selector('iframe'))
    .dispatchEvent('input.focused-element', 'blur')
    .typeText('input.another-element', 'write something here')
    .expect(Selector('.this-should-appear').exists).ok();
});
```

Please note that we didn't release documentation about the "t.dispatchEvent" method yet, so please refer to [this method's draft documentation](https://gist.github.com/AndreyBelym/b9a09481ef4932c3541c837d3ac2c40d).
