### ISSUE TITLE
when taking non-error screenshots with firefox 89 and windows 10 (and ubuntu) testcafe hangs on 2nd screen shot

### ISSUE THREAD

**Issue by zoe-jobson-IL** [DevExpress/testcafe#6325]
### What is your Test Scenario?
screenshots from firefox in shared folder (shared amongst tests and test runs that is)
 
### What is the Current behavior?
hangs when taking second screen shot (or occasionally later)
 
### What is the Expected behavior?
does not hang
 
### What is your web application and your TestCafe test code?
attached zip - I can repo on your page, zip has package.json and testcaferc file as well as simplest test script for repo

### Steps to Reproduce:
1. unzip attached, in project folder npm i (just typescript, local testcafe and video app)
2. npm run testPOCf
3. testcafe hangs either on the second screenshot or when re-run. The chrome runner works fine and runs through.
4. If I change the folder for results and images then it works for the first screen shot and again fails for the second.
5. If I run the test through with chrome first "npm run testPOCc", then it hangs when run in firefox as per step 2
 
### Your Environment details:
 
* testcafe version:                   1.14.2
* node.js version:                    14.16.1
* command-line arguments:  npm run testPOCf
* browser name and version: firefox 89.0
* platform and version:          Windows 10, version 20H2, Ubuntu 20.04.2 LTS, the guy trying to dockerize our project says it also fails in your docker image with firefox
* other:                                   it sometimes succeeds the first time through . But it usually hangs when it tries to take the second screenshot. 

[.testcaferc.zip](https://github.com/DevExpress/testcafe/files/6687328/default.testcaferc.zip)

**Comment by zoe-jobson-IL** [comment]
if the file name of the zip causes an issue to this one 
[testcaferc.zip](https://github.com/DevExpress/testcafe/files/6687999/testcaferc.zip)

**Comment by wentwrong** [comment]
Thank you for the report. I've reproduced the bug with the following simple test code:
```js
fixture `fixture`
    .page `https://example.com`;

test(`test`, async t => {
    await t.takeScreenshot();
});
```

I ran this test with the "video" flag specified against the Firefox browser as follows:

```sh
testcafe firefox test.js --video videos
```

In this case, the browser hangs for some reason. However, if you disable video recording, everything works as expected.
