### ISSUE TITLE
Selector.filter by input value

### ISSUE THREAD

**Issue by mokone91** [DevExpress/testcafe#6327]
Hi guys! 
I need to filter inputs by value inside.

So when im typing something like 

```
await
     .expect(settingsCannedMessagesTextDisabledInput.filter((node)=>{ 
         return node.value == 'my test value'
    }).visible).ok()
```
I getting `TS2339: Property 'value' does not exist on type 'Element'.` error.

as workaround i can specify node type explicitly and pass type check, and code working as expected:

`return (node as HTMLInputElement).value == 'my test value'`

so, seems node type should be a extended with HTMLInputElement

Thanks!

**Comment by AlexKamaev** [comment]
We do not think that we need to modify the type for the `node` argument. The current type is `Element`, and it contains properties that exist in all HTML elements. If we modify the type, the TS compiler will ignore the case when the node does not have the `value` property.

If you need a property that exists only in a specific HTML element type (like input elements), you need to continue using type casting.

**Comment by mokone91** [comment]
Hi! Thanks for reply!

Probably you're right, and its not a problem for developer(what about testers?) to handle such cases, but there is no any notes in Selector.filter documentation for this...

**Comment by Dmitry-Ostashev** [comment]
[Such information](https://testcafe.io/documentation/402824/guides/concepts/typescript-and-coffeescript#type-cast-page-elements) already exists in our documentation. We will check if it is possible to make it easier for users to find this information.
