### ISSUE TITLE
Is it possible to inject XHR request with clientScripts

### ISSUE THREAD

**Issue by yusufkaracaburun** [DevExpress/testcafe#6329]
Hi,

Is it possible to inject an XHR request with ClienScripts?
e.g;
 window.addEventListener('DOMContentLoaded', () => {
          const xhr = new XMLHttpRequest();
          xhr.addEventListener('readystatechange', () => {
              if (xhr.readyState === xhr.DONE) {
                  const node = document.body.appendChild(document.createElement('div'));
                  node.setAttribute('hidden', 'hidden');
                  node.setAttribute('data-request-method', '${method}');
                  node.setAttribute('data-request-url', '${url}');
                  node.setAttribute('data-request-status', xhr.status);
                  node.innerText = xhr.responseText;
              }
          });
          xhr.setRequestHeader('Content-Type', 'application/json');
          xhr.open('${method}', '${url}');
          xhr.send(${body});
      });

**Comment by VasilyStrelyaev** [comment]
Yes, you can inject any code as a client script. You can put code that sends an XHR request in a `.js` file and [inject this file](https://testcafe.io/documentation/402843/guides/advanced-guides/inject-client-scripts#inject-a-javascript-file) or specify this code in your test suite [in-line](https://testcafe.io/documentation/402843/guides/advanced-guides/inject-client-scripts#inject-script-code).

Did you already encounter any issues with sending XHR requests from injected code? If so, please share your code with us.

**Comment by yusufkaracaburun** [comment]
Thanks for your reply, I had forgot to add a backlash before the quotes in the body. After adding that it worked. 

But now I'm getting a 500 statuscode with the following error message:
message: "query did not return a unique result: 2; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 2"

**Comment by yusufkaracaburun** [comment]
Thanks for the confirmation. We've found the error. The body was incorrect, after ading some backslashes before the quotes it worked like a charm.
