### ISSUE TITLE
Add ffmpeg package to the standard docker image

### ISSUE THREAD

**Issue by ejosafat** [DevExpress/testcafe#6330]
### What is your Test Scenario?
I'm building a docker image based on the testcafe standard image to be used in the CI pipeline. However I'm unable to record videos as there is no ffmpeg package installed in the original image.

### What are you suggesting?
Would it be possible to add the package to the standard testcafe docker image?

### What alternatives have you considered?
I checked this closed issue: https://github.com/DevExpress/testcafe/issues/5215, one of the suggestions is to add the ffmpeg package in your derived image, however that doesn't work as the standard image specifies ```USER user```, so any attempt of installing a package later throws a Permission denied exception. I can add ```USER root``` to my image and then install the package, however that means that then I have to run the tests as a root user as if I try to use the standard user it will throw an error when trying to record results.

### Additional context
This is my Dockerfile:
```
FROM testcafe/testcafe

WORKDIR /app

COPY --chown=user:user . .

RUN npm install

USER root
RUN apk add ffmpeg
```

**Comment by wentwrong** [comment]
As described in [this](https://github.com/DevExpress/testcafe/issues/3572#issuecomment-621172930) comment, license restrictions do not allow us to install the ffmpeg package in the official TestCafe Docker image. Therefore, you need to build and use your own Docker image.

For example, I used the following Dockerfile:

```Dockerfile
FROM testcafe/testcafe
USER root
RUN apk add --no-cache ffmpeg
USER user
```
and the following commands to build an image from it and run tests with video recording enabled:

```PowerShell
docker build -t tc_with_ffmpeg .
docker run -it -v ${PWD}:/tests -w /tests tc_with_ffmpeg chromium test.js --video videos
```

(Navigate to the [docker docs](https://docs.docker.com/engine/reference/commandline/run/) if you stumble upon some flags I used).

**Comment by ejosafat** [comment]
ah I see, sorry I missed that comment. Thanks for the tip!
