### ISSUE TITLE
Cannot read property importKey of undefined

### ISSUE THREAD

**Issue by tusia95** [DevExpress/testcafe#6332]
### What is your Test Scenario?
try to login on platform https://vimbox.skyeng.ru
 
### What is the Current behavior?
my test inputs values to email and password fields and click login button, then i`m redirecting to empty page, also I can see error in console "Cannot read property "importKey" of undefined
https://monosnap.com/file/b0xlIpf98socqIgUinzxXdFySnLPa2
 
### What is the Expected behavior?
successfully authenticated test user is redirected to https://vimbox.skyeng.ru/showcase
 
### What is your web application and your TestCafe test code?

 https://vimbox.skyeng.ru - app I try to login

<details>
<summary>Your website URL (or attach your complete example):</summary>
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
You can fing my code here https://github.com/tusia95/e2e-tests-testcafe
I use login method:
with selectors
 loginField: Selector = Selector('[name="username"]');
    passwordField: Selector = Selector('[action*="submit"] [name="password"]');
    loginButton: Selector = Selector('[class*=password-form-button]');
    async enterCredentials(t: TestController, email: string, password: string) {
        await t
            .typeText(this.loginField, email, {replace: true, paste: true})
            .typeText(this.passwordField, password, {replace: true, paste: true})
            .click(this.loginButton)
    }
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
const createTestCafe = require('testcafe');

createTestCafe('localhost', 1337, 1338)
    .then(tc => {
        testcafe = tc;
        const runner = testcafe.createRunner();
        return runner
            .src('./testcafe/*.tests.ts')
            .browsers(['chrome'])
            .concurrency(3)
            .run();
    })
    .then(failedCount => {
        console.log(`Failed tests: ${failedCount}`);
        testcafe.close();
    });

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

https://monosnap.com/file/b0xlIpf98socqIgUinzxXdFySnLPa2
</details>

### Steps to Reproduce:

1. Go to my website 
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                  1.14.2

* node.js version:                    Node.js v14.16.1.

* command-line arguments:  testcafe "chrome -incognito" group.tests.ts

* browser name and version: Chrome Version 91.0.4472.77 (Official Build) (64-bit)

* platform and version:          Win10
* other:

**Comment by viktoria2506** [comment]
Could you please send us the entire test file?

I tried to run this code:
```
import from 'testcafe';

async function enterCredentials(t: TestController, email: string, password: string) {
    const loginField: Selector = Selector('[name="username"]');
    const passwordField: Selector = Selector('[action*="submit"] [name="password"]');
    const loginButton: Selector = Selector('[class*=password-form-button]');

    await t
        .typeText(loginField, email, {replace: true, paste: true})
        .typeText(passwordField, password, {replace: true, paste: true})
        .click(loginButton)
}

fixture(`Fixture`).page(`https://vimbox.skyeng.ru/showcase`);

test(`Test`, async (t) => {
    await enterCredentials(t, 'email', 'password');
});

```
I used the following console:
```
testcafe "chrome -incognito" group.tests.ts
```
However, I couldn't reproduce the issue.

**Comment by tusia95** [comment]
Victoria you can fin my code here https://github.com/tusia95/e2e-tests-testcafe

**Comment by tusia95** [comment]
you should input real email/password - these data contains in my code (go to the github link)

**Comment by wentwrong** [comment]
Hi, @tusia95

Thank you for sharing the example with us. The problem is that the [SubtleCrypto.importKey()](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/importKey) method used in the code of the website you tested is available only in secure contexts. To solve the problem, you need to either specify `--hostname localhost` (because localhost is a secure context) or use SSL. See the following documentation entries about these options: [--hostname](https://testcafe.io/documentation/402639/reference/command-line-interface#--hostname-name) and [--ssl](https://testcafe.io/documentation/402639/reference/command-line-interface#--ssl-options).

Also please note that you probably don't need to pass the `--incognito` flag for Chrome because TestCafe launches browsers with a clean profile by default and some Incognito Mode features (such as disabling cookies) may affect test execution.
