### ISSUE TITLE
[docs]: Add information about set up docker image for video recording

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#6333]
The official TestCafe's docker image doesn't contain the `ffmpeg` library due to license restrictions.
So, the video recording feature is not working in the docker image out of box.
To make it work, need to create a new image based on the TestCafe docker image with the installed `ffmpeg` library.
First, create a new `docker` file with the following content:
For example, I've used the following Dockerfile:
```Dockerfile
FROM testcafe/testcafe
USER root
RUN apk add --no-cache ffmpeg
USER user
```
When build a new image:
```PowerShell
docker build -t tc_with_ffmpeg .
docker run -it -v ${PWD}:/tests -w /tests tc_with_ffmpeg chromium test.js --video videos
```

The built image support the video recording during test execution.

**Comment by titerman** [comment]
Closed in favour of #7153
