### ISSUE TITLE
[docs] Update Troubleshooting with a macOS permissions example and add this link in the SCREEN_RECORDING_PERMISSION_REQUEST message

### ISSUE THREAD

**Issue by Farfurix** [DevExpress/testcafe#6334]
Found in https://github.com/DevExpress/testcafe/issues/6198

References:
https://github.com/DevExpress/testcafe/issues/6198#issuecomment-831844297
https://docs.devexpress.com/TestCafeStudio/400610/faq -> "I cannot run tests on macOS"

**Comment by titerman** [comment]
The documentation now includes a proper macOS permissions guide. It may take a while for the article to show up on the website.
