### ISSUE TITLE
After logging in to home page it is again redirecting to login page

### ISSUE THREAD

**Issue by arvindarun** [DevExpress/testcafe#6343]
Reproduction steps:

Basically, I have 2 users 
1. I will log in with user 1 and perform some action
2. Now I will log in with user 2, now it will be logged in successfully and redirects back to the login page

Testcafe version: 1.14.2
npm version: 7.9.0

https://www.loom.com/share/92c35afb892d47288daf19d79fe90e08

can someone help me to resolve this issue

**Comment by Dmitry-Ostashev** [comment]
Unfortunately, it's difficult to determine the cause of the issue based on the video. Could you please attach a simple test and give us a public url of the page so we can reproduce and research the issue on our side?

Note that our policy prevents us from accessing internal resources without prior written approval from a site owner. Please ask the website owner to send us ([support@devexpress.com](mailto:support@devexpress.com)) a written confirmation. It must permit DevExpress personnel to remotely access the website and its internal resources for research/testing and debugging purposes.

**Comment by arvindarun** [comment]
> Unfortunately, it's difficult to determine the cause of the issue based on the video. Could you please attach a simple test and give us a public url of the page so we can reproduce and research the issue on our side?
> 
> Note that our policy prevents us from accessing internal resources without prior written approval from a site owner. Please ask the website owner to send us ([support@devexpress.com](mailto:support@devexpress.com)) a written confirmation. It must permit DevExpress personnel to remotely access the website and its internal resources for research/testing and debugging purposes.

I have shared the sample code to the mentioned mail id.

**Comment by Dmitry-Ostashev** [comment]
Thank you for your project. I reproduced the issue. We will research it and update this thread once we have any results.

**Comment by arvindarun** [comment]
Thanks for your reply

Regards
Arvind

**Comment by arvindarun** [comment]
Hi, can I know what is the status of this issue

Regards
Arvind

**Comment by arvindarun** [comment]
can I know when this issue will be fixed

**Comment by miherlosev** [comment]
Hi @arvindarun,

The tested site is unreachable now. Please fix it. After this, we can continue to investigate the cause of the issue.
