### ISSUE TITLE
Testcafe runner taking to long to close

### ISSUE THREAD

**Issue by sblandon** [DevExpress/testcafe#6344]
### What is your Test Scenario?
The test is a really simple test, we are just trying to open a page. 
 
### What is the Current behavior?
The test is being executed correctly, but the process is taking really long to be done. 
 
### What is the Expected behavior?
We are expecting that when the testcafe runner is closed, the process is done, but this is not closing immediately.
 
### What is your web application and your TestCafe test code?

 
 ```
 const createTestCafe = require('testcafe');
class Lambda {
  static async run(event, context, callback) {
    const testcafeInstance = await createTestCafe();
    const runner = testcafeInstance.createRunner();
    try {
        await runner
          .browsers(`chrome:headless`)
          .src('test')
          .run();
        await testcafeInstance.close();
        return callback(null, {});
    } catch (err) {
      console.log(err);
      return callback(err, null);
    }
  };
}
module.exports = Lambda;
```

Test Scenario
```
import { Selector } from 'testcafe';
fixture `Getting Started`
    .page `http://devexpress.github.io/testcafe/example`;
test('My first test', async t => {
    // Test code
}); 
```

We have a test runner that is running in a lambda on AWS, everything was working correctly until June 22th, we did migrate our app to a new infrastructure on AWS that has exactly the same configuration and characteristics as the previous environment that we were using, the problem seems to occur right in the execution of the testcafe runner,  we are getting this error in AWS 
```
Runtime exited without providing a reason
```
We did check why the error and we found out that this error is related to processes or connections that have not been close correctly, we tried using different testcafe versions including the last version. We are using node version 10 and 12 and it is not working for us, as I mentioned above this was working for us until June 22nd. We are calling the testcafe closed correctly using an await, as you can see in the code pasted above. Our solution is working locally without any issues but it is still giving performance issues after closing testcafe.

Here is the NPM package chrome-aws-lambda version 10.0.0. that we are using as browser for our project.

Locally we are using chrome. 

we use WTFNode to check the processes and we found these processes were active after closing test cafe

<img width="490" alt="Screen Shot 2021-06-28 at 3 47 52 PM" src="https://user-images.githubusercontent.com/11699384/123702102-574eb700-d828-11eb-89d6-d89c1107e521.png">

We think that the problem is relate to the 5 seconds timer. 

<details>
<summary>Unfortunelly I cant paste the full test of our app because NDA reasons</summary>

 

</details>

<details>
<summary>We have not config file</summary>

```

```
</details>

<details>
<summary>

</summary>

<img width="322" alt="Screen Shot 2021-06-28 at 3 51 19 PM" src="https://user-images.githubusercontent.com/11699384/123702628-fd022600-d828-11eb-8647-6eebf0522bfe.png">

</details>

<summary>Screenshots:</summary>

https://user-images.githubusercontent.com/11699384/123702937-5cf8cc80-d829-11eb-8f25-3b81b9c4a9c2.mp4

### Steps to Reproduce:

1. create a folder called test
2. Save inside that folder the test

```
import { Selector } from 'testcafe';

fixture `Getting Started`
    .page `http://devexpress.github.io/testcafe/example`;
```

3. Create a js file called index.js, the code should be at the same level than the test folder ( root): 

```
const Lambda = require('./lambda');
async function run() {
  return await Lambda.run({}, {}, (err, resp) => {
    return resp;
  });  
}
run().then((res) => {
  console.log(res);
}).catch((err) => console.log(err));
```

4. Create another JS file with the following code ( Please name it lambda.js) 

```
const createTestCafe = require('testcafe');

class Lambda {
  static async run(event, context, callback) {
    const testcafeInstance = await createTestCafe();
```
5. Run the index.js file using node.
 
### Your Environment details:
 
* testcafe version:                    1.14.2
* node.js version:                     12
* command-line arguments:   node index.js 
* browser name and version:  Chrome 91.0.4, package chrome-aws-lambda version 10.0.0
* platform and version:           Docker image public.ecr.aws/lambda/nodejs:10 --- macOS10.15.7  ---- Ubuntu 20.04
* other:

**Comment by sblandon** [comment]
UPDATE: Today we tested with a lambda using a .zip and it works for us, but when the lambda is using a docker image it does crash. 

Summary : 
First we tried again on the old infrastructure  using .zip file to deploy the code (on our old lambda function) and everything worked. After that, we tested with container image on our new infra and it didn’t work so we confirmed that the problem is just with the container lambda.

Finally, we created a new function on our new envirorment account using zip file to the code, and it worked again. So the project is running with zip file now on QA account, but as I mentioned above it doesn't work using the docker image.

**Comment by AlexKamaev** [comment]
Your environment is very complex, so please provide us with a testing account so that we reproduce and research the issue. Please also share a more detailed instruction on how to reproduce the issue on Lambda. You can send credentials at support@devexpress.com

**Comment by sblandon** [comment]
@AlexKamaev sure, I will get back to you with all this info asap.
