### ISSUE TITLE
Cookie Banner not showing in chrome headless mode

### ISSUE THREAD

**Issue by Deepa-radhakrishnan** [DevExpress/testcafe#6346]
I have written test to accept the cookie banner and proceed to the page.
Test works ok in Chrome Open mode but the same test not able to find the element in chrome headless mode.
I also tried to set the cookie and get Cookie. Even though the Get cookie retrieves the cookie its not being set for the test to pass.

How to get this cookie banner to work in Chrome headless mode?

**TEst 1 code**

const baseUrl = 'https://www.integration.project4.com';
const url = `${baseUrl}/mugs-set-of-4-340ml/coral/p3911957`;

fixture.only`PDP components`.page(url).beforeEach(async (t) => {
  await setCookies();
  await t.eval(() => location.reload(true));

});

test('PDP title', async (t) => {
  const title = Selector('[data-testid="product:title');
  const cookiesAcceptButton = Selector('[data-test=cookie-banner-content] [data-test=allow-all]');
  await t
  .click(cookiesAcceptButton)
    .expect(title.textContent)
    .eql('Stoneware Mugs, Set of 4, 340ml');
});

**Test 2**
const setCookies = ClientFunction(() => {
  document.cookie = 'cookie-1; path=/';
});

const baseUrl = 'https://www.integration.project4.com';
const url = `${baseUrl}/coral/p3911957`;

fixture.only`PDP components`.page(url).beforeEach(async (t) => {
  await setCookies();
  await t.eval(() => location.reload(true));
  });

test('PDP title', async (t) => {
  const title = Selector('[data-testid="product:title');
  
  await t

    .expect(title.textContent)
    .eql(' Set of 4, 340ml');
});

**Comment by AlexanderMoiseev** [comment]
Hi,

I cannot access your site to reproduce the issue. It shows the 'Access Denied' message. Feel free to reopen the issue if you can fix it.

**Comment by Deepa-radhakrishnan** [comment]
Can you please try this piece of code in chrome headless mode?

import { Selector } from 'testcafe';
import { ClientFunction } from 'testcafe';

const getLocation = ClientFunction(()=>document.location.href);


fixture `Getting Started`
    .page `https://www.johnlewis.com/emma-bridgewater-mama-bear-mum-half-pint-mug-310ml-orange-white/p4447067`;

    test('My first test', async t => {
    const cookiesAcceptButton = Selector("[data-test=cookie-banner-content] [data-test=allow-all]");
        await t
            .click(cookiesAcceptButton)
    });

Above works in open mode but not in chrome headless

**Comment by Deepa-radhakrishnan** [comment]
Can you please provide your details and I can email you privately the website?

**Comment by VasilyStrelyaev** [comment]
This issue duplicates https://github.com/DevExpress/testcafe/issues/6347. Let's continue the discussion there.
