### ISSUE TITLE
Cookie banner not showing in the chrome headless mode

### ISSUE THREAD

**Issue by Deepa-radhakrishnan** [DevExpress/testcafe#6347]
### What is your Test Scenario?
Accept the cookie banner in chrome headless mode
 
### What is the Current behavior?
Error when run on chrome headless mode
**The specified selector does not match any element in the DOM tree.
      
       > | Selector('[data-test=cookie-banner-content] [data-test=allow-all]')** 
 
### What is the Expected behavior?
Test should pass and behave same as Chrome Open mode
 
### What is your web application and your TestCafe test code?
```
import { Selector } from 'testcafe';
import { ClientFunction } from 'testcafe';

const getLocation = ClientFunction(()=>document.location.href);


fixture `Getting Started`
    .page `https://www.example.com/emma-bridgewater-mama-bear-mum-half-pint-mug-310ml-orange-white/p4447067`;

    test('My first test', async t => {
    const cookiesAcceptButton = Selector("[data-test=cookie-banner-content] [data-test=allow-all]");
        await t
            .click(cookiesAcceptButton)
    });
```
### Steps to Reproduce:

1. Go to website
2. Run testcafe "chrome:headless" test1.js
 
### Your Environment details:
 
* testcafe version:                   1.14.0
* node.js version:                    v14.16.1
* command-line arguments:  testcafe "chrome:headless" test1.js
* browser name and version:  Latest Chrome in headless mode
* platform and version:          MAC 10

**Comment by Deepa-radhakrishnan** [comment]
Can you please try this piece of code in chrome headless mode?

I also have updated Testcafe to latest version 1.14.2 and tried

import { Selector } from 'testcafe';
import { ClientFunction } from 'testcafe';

const getLocation = ClientFunction(()=>document.location.href);


fixture `Getting Started`
    .page `https://www.example.com/emma-bridgewater-mama-bear-mum-half-pint-mug-310ml-orange-white/p4447067`;

    test('My first test', async t => {
    const cookiesAcceptButton = Selector("[data-test=cookie-banner-content] [data-test=allow-all]");
        await t
            .click(cookiesAcceptButton)
    });

Above works in open mode but not in chrome headless.

this is the case with any website that shows cookie banner. Try to access the deep URL than just homepage.

**Comment by Farfurix** [comment]
@Deepa-radhakrishnan 

Hello,

I reproduced this behavior with Windows 10 and Chrome 91. However, I would not say that this issue relates to TestCafe. Could you look for the reason that leads to the missing banner? It may be caused by cookie difference and the application logic. Please check headless/non-headless cookies using this test:

```js
import { Selector, ClientFunction } from 'testcafe';

const logCookies = ClientFunction(() => document.cookie.split(';'));

fixture `Getting Started`
    .page `*********/emma-bridgewater-mama-bear-mum-half-pint-mug-310ml-orange-white/p4447067`;

test('My first test', async t => {
    const cookiesAcceptButton = Selector("[data-test=cookie-banner-content] [data-test=allow-all]");

    console.log(await logCookies());

    // await t.takeScreenshot();

    await t
        .click(cookiesAcceptButton)
});
```
