### ISSUE TITLE
Allow TestCafe retry mechanism to work with pure unawaited promises

### ISSUE THREAD

**Issue by Evilweed** [DevExpress/testcafe#6350]
### What is your Test Scenario?
Allow TestCafe retry mechanism to work with pure unawaited promises. Or allow TestCafe users to create some special Promise that TestCafe will handle with retry mechanism.

Retry mechanism is awesome. Imagine you have some action that will happen on the same page but at some point, like state change due to delayed job result. If we have retry mechanism that checks the status each couple seconds until timeout, or even refresh the page and check the status, then we are golden. If we don't have that kind of thing, expect will take the value at the moment of running expect line and that's it.

In my example, I only used Page Object pattern to hide the implementation details (but there are other examples like reload page, click something, and then check some textContent). To make the code more readable to Developers and Testers. And in this form retry mechanism does not work.

```
// In Page Object
export class SettingsSection {
    selectedOrderManagerName = async(): Promise<string> => {
        return this.offerManagerSelect.find('option').withAttribute('selected').textContent
    }
...
}


// In spec file:
    await t.expect(
        selectedOrderManagerName() // <--- Notice missing await before promise.
    ).notEql(offer.manager.email);

// This case will fail as Testcafe throws error that we have provided unawaited promise to expect.
```

```
// In spec file:
    await t.expect(
        await selectedOrderManagerName() // <--- Added await
    ).notEql(offer.manager.email);

// This case won't have retry mechanism, value will be collected only once
```
### What are you suggesting?
```
class TestCafeRetryPromise {
    constructor (methodToRun, options?: SomeExtraIfNeeded) {
        this.methodToRun = methodToRun
   }
}

const customActionThatShouldRetry = new TestCafeRetryPromise(() => {
    await t.click(someButton)
    await selectSomethingInDropdown()
    return await someTestCafeSelector.innerText
})
expect(customActionThatShouldRetry).toBe("some text") // <-- TestCafe should rerun this promise until value is met or until timeout is reached.
```

### What alternatives have you considered?
I don't see any. Tried to use try {} catch {} but TestCafe somehow knows that something failed inside try {} catch {} and next click or other action fails the test.

IMPORTANT:
Please do not propose using ClientFunction to accomplish this as ClientFunction fails the test on page load/reload. Which means that if we have t.click() and then expect(clientFunction).toBe('something') and there is page reload between, then test will fail.

**Comment by aleks-pro** [comment]
The auto-waiting mechanism implementation for a pure Promise is a very complex task. So, we decided to implement a custom internal Promise for that purpose. Turning off the auto-waiting mechanism (by adding the `await` keyword) is one of the causes of the issue. We have added a warning message for this case:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/14822473/124460876-9d5fc980-dd98-11eb-86e2-809c77a1b1d9.png)
If the warning doesn't appear, please make sure that you are using the latest TestCafe version.
The second cause is described in https://github.com/DevExpress/testcafe/issues/6342. You can track it to be informed about the updates regarding it.

**Comment by Evilweed** [comment]
> The auto-waiting mechanism implementation for a pure Promise is a very complex task. So, we decided to implement a custom internal Promise for that purpose.

@aleks-pro then can you allow us to use this Internal Promise and construct ourselves compatible promise that does something inside and works well with your retry mechanism? That was one of the suggestions in my proposal.

```
class TestCafeRetryPromise {
    constructor (methodToRunAndRetry, options?: SomeExtraIfNeeded) {
        this.methodToRunAndRetry = methodToRunAndRetry
   }
}

const customActionThatShouldRetry = new TestCafeRetryPromise(() => {
    await t.click(someButton)
    await selectSomethingInDropdown()
    return await someTestCafeSelector.innerText
})

expect(customActionThatShouldRetry).toBe("some text")

```

**Comment by aleks-pro** [comment]
@Evilweed, see the internal Promise source code [here](https://github.com/DevExpress/testcafe/blob/master/src/utils/re-executable-promise.ts). You can extend it to achieve the desired behavior.

However, we have no plans to make it public because in this case, we will not be able to make changes in that code and will require extra resources to support it. So, we cannot guarantee that the derived Promise will work in future TestCafe versions.
