### ISSUE TITLE
Minor improvement to (IMHO) have better readability of expect message

### ISSUE THREAD

**Issue by fmancardi** [DevExpress/testcafe#6351]
### What is your Test Scenario?
have a test that fails and provide this message

   1) AssertionError: expected 4 to deeply equal 0

      \+ expected - actual

      -4
      +0

### What are you suggesting?
A minor information reorder and an additional text 
 1) AssertionError: 4 **(actual)** ,  **expected** to deeply equal 0 **(expected)**
  
     \- actual
      4

    \+ expected 
      0

**Comment by felis2803** [comment]
Hello,

We will change the output format of the report in the context of this issue: #4001.
In the meantime, you can also create a new plug-in or update the existing one to change the output format: [Reporter Plugin](https://testcafe.io/documentation/402810/guides/extend-testcafe/reporter-plugin).

**Comment by fmancardi** [comment]
Hi, I've searched the testcafe-reporter-spec for the place where to change this but I was not able to find the lines.
Would you mind to point me to the lines to change?

Regards

**Comment by Farfurix** [comment]
@fmancardi 

Hello,

You can take the error rendering function ([`_renderErrors`](https://github.com/DevExpress/testcafe-reporter-spec/blob/master/src/index.js#L38) in node_modules/testcafe-reporter-spec/lib/index.js) as a starting point:
```diff
_renderErrors: function _renderErrors(errs) {
+    console.log('errs:');
+    console.log(errs);
```
test.js:
```js
fixture `Fixture`
    .page('https://google.com');

test('test', async t => {
   await t
       .expect({'foo': 'bar'}).eql({'bar': 'baz'});
});
```
Result:
```
node bin/testcafe chrome D:\work\testcafe-test\tests1\simple-test3.js
 Running tests in:
 - Chrome 91.0.4472.124 / Windows 10

 Fixture
 × test
errs:
[
  TestRunErrorFormattableAdapter {
    userAgent: 'Chrome 91.0.4472.124 / Windows 10',
    screenshotPath: '',
    testRunId: '3wwfkuPqr',
    testRunPhase: 'inTest',
    code: 'E53',
    isTestCafeError: true,
    callsite: CallsiteRecord {
      filename: 'D:\\work\\testcafe-test\\tests1\\simple-test3.js',
      lineNum: 5,
      callsiteFrameIdx: 6,
      stackFrames: [Array],
      isV8Frames: true
    },
    errMsg: "AssertionError: expected { foo: 'bar' } to deeply equal { bar: 'baz' }",
    diff: '<span class="diff-not-modified"> {</span>\n' +
      '<span class="diff-removed">-  foo: &#39;bar&#39;</span>\n' +
      '<span class="diff-added">+  bar: &#39;baz&#39;</span>\n' +
      '<span class="diff-not-modified"> }</span>\n' +
      '<span class="diff-not-modified"></span>'
  }
]


   1) AssertionError: expected { foo: 'bar' } to deeply equal { bar: 'baz' }

      + expected - actual

       {
      -  foo: 'bar'
      +  bar: 'baz'
       }


      Browser: Chrome 91.0.4472.124 / Windows 10

         1 |fixture `Fixture`
         2 |    .page('https://google.com');
         3 |
         4 |test('test', async t => {
         5 |   await t
       > 6 |       .expect({'foo': 'bar'}).eql({'bar': 'baz'});
         7 |});
         8 |

         at <anonymous> (D:\work\testcafe-test\tests1\simple-test3.js:6:32)
         at asyncGeneratorStep (D:\work\testcafe-test\tests1\simple-test3.js:1:114)
         at _next (D:\work\testcafe-test\tests1\simple-test3.js:1:452)
         at <anonymous> (D:\work\testcafe-test\tests1\simple-test3.js:1:617)
         at <anonymous> (D:\work\testcafe-test\tests1\simple-test3.js:1:358)
         at <anonymous> (D:\work\testcafe-test\tests1\simple-test3.js:4:5)



 1/1 failed (2s)

```

You can find the `errMsg` error message generation procedure in `chai` (`getMessage`, node_modules/chai/lib/chai/utils/getMessage.js). It returns `expected { foo: 'bar' } to deeply equal { bar: 'baz' }` for the above test.

**Comment by fmancardi** [comment]
Thanks for your help!
