### ISSUE TITLE
Automate testing new TestCafe versions with Studio and Dashboard

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#6354]
As a first step we can setup dependabot or renovate bot to update testafe version in Studio and Dashboard tests

 - [x] Setup an NPM registry proxy
 - [ ] Publish testcafe-hammerhead autobuilds to the NPM proxy
 - [ ] #7197
 - [ ] Publish testcafe autobuilds to the NPM proxy
 - [ ] Automate updating testcafe in testcafe-dashboard
 - [ ] Automate updating testcafe in testcafe-studio

**Comment by aleks-pro** [comment]
Renovate bot configs added to testcafe-dashboard and testcafe-studio repos:
https://github.com/DevExpress/testcafe-dashboard/blob/master/.github/renovate.json
https://github.com/DevExpress/testcafe-studio/blob/master/.github/renovate.json
