### ISSUE TITLE
Strange behavior from Testcafe after navigating to another page

### ISSUE THREAD

**Issue by khlifi1994** [DevExpress/testcafe#6366]
### What is the Current behavior?
Normally I get redirected to another page, but I get a page with an XML structure.
 
![TestcafeError](https://user-images.githubusercontent.com/48571335/124913108-a2b25380-dfe6-11eb-865c-340cc397787e.png)

 
* testcafe version:                   Latest
* node.js version:                    Latest
* command-line arguments:  testcafe chrome UI_Tests/**/.ts --video artifacts/videos --video-options failedOnly=true,aspect=16:9 --screenshots takeOnFails=true --skip-js-errors --proxy="**************:8080"
* browser name and version: Chrome
* platform and version:          Windows 10

**Comment by khlifi1994** [comment]
The link I want to navigate to is something like this: https://**************/share/wHp25, bit it becomes https://***************/api/RHS/Short/?value=wHp25
It's clear in the screenshot

**Comment by khlifi1994** [comment]
Sorry but I can't share the URL of my company, you can't even access to it. But its simple, that error appears when I reach the navigateTo(url) command.

**Comment by Farfurix** [comment]
@khlifi1994 

Hello,

> But its simple, that error appears when I reach the navigateTo(url) command.

I tried to reproduce this with the following test:
```js
fixture `Fixture`
    .page('https://github.com');

test('test', async t => {
    await t.navigateTo('https://google.com');
    await t.debug();
});

```
My setup was Windows 10, Chrome 91, Node.js 14.17.0, TestCafe v1.15.0, and everything works as expected. Could you please modify my test to illustrate your usage scenario?

I can only suppose that your TestCafe version is lower than 1.15.0. Please check your test with the latest 1.15.0 version and share your result. With the latest version, TestCafe should download an XML file when navigating to it.
