### ISSUE TITLE
Async 'Runner.filter' function

### ISSUE THREAD

**Issue by eignatyev** [DevExpress/testcafe#6370]
### What is your Test Scenario?
* use an asynchronous function as predicate for the runner.filter function
* assert the filtered array of tests contains expected items only

### What are you suggesting?
use an asynchronous filter

### What alternatives have you considered?
none, I need to have freedom in using both, sync and async functions when filtering tests using the Runner object

**Comment by Farfurix** [comment]
Closed by https://github.com/DevExpress/testcafe/pull/6371.
