### ISSUE TITLE
Uncaught type error when opening www.ikea.cn with testcafe + Chrome 91 emulating mobile device

### ISSUE THREAD

**Issue by mypchas6fans** [DevExpress/testcafe#6374]
### What is your Test Scenario?
Simply run below test and testcafe will fail to load www.ikea.cn
testcafe "chrome:emulation:device=iphone X" testH5.js -e --speed 0.8 --debug-on-fail
And we have tried iphone 8/pixel 2 getting the same result.
 
### What is the Current behavior?
Chrome starts and tries to load the page www.ikea.cn, but many elements cannot be loaded.
And Chrome console prompts infinite loop of following error:

Uncaught TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at y (hammerhead.js:1)
    at E (hammerhead.js:1)
    at t._overrideStyleInstanceProp (hammerhead.js:15)
    at t._processStyleInstance (hammerhead.js:15)
    at HTMLDivElement.E.getter [as style] (hammerhead.js:15)
    at Object.Me [as set] (hammerhead.js:1)
    at Object.set (testcafe-core.js:1)
    at testcafe-ui.js:1

If we manually start Chrome emulating mobile devices, the web site can be loaded successfully without error loop.
That's why we raise this issue.
But it was working fine about 2 days ago, so we are also checking what was changed inside the web site.
And if we don't use debug to pause the test, it will throw error and exit:

Uncaught object "[object Object]" was thrown. Throw Error instead.
 
### What is the Expected behavior?
Page can be loaded without error and following test steps can be executed.
 
### What is your web application and your TestCafe test code? 
<details>
<summary>Your website URL:  https://www.ikea.cn</summary>
</details>

<details>
<summary>Simply start and debug-on-fail should be able to reproduce this issue.</summary>

 
```js
 
fixture('test')
    .page('https://www.ikea.cn')

test
    ('search-pip-groupbuy-checkout', async t => {
    var article = '00217132';
    //await t.debug();
});
```
</details>

<details>
<summary>Screenshots:</summary>

```
![testcafe](https://user-images.githubusercontent.com/5707530/125198794-f6969400-e295-11eb-9037-0d246717433d.png)

```
</details>

### Steps to Reproduce:

1. Put above code snippet in a js file;
2. Run "testcafe "chrome:emulation:device=iphone X" testH5.js -e --speed 0.8 --debug-on-fail"
3. Chrome starts and tries to load the page, going to debug;
4. Open developer tools and see errors in console.
 
### Your Environment details:
 
* testcafe version:                   1.15.0
* node.js version:                    14.17.3
* command-line arguments:  testcafe "chrome:emulation:device=iphone X" testH5.js -e --speed 0.8
* browser name and version: Chrome 91.0.4472.124
* platform and version:          Windows 10
* other:

**Comment by Dmitry-Ostashev** [comment]
Thank you for your report. I reproduced the issue. We will research it and will update this thread once we have any news.

For the team:
This problem can be reproduced with testcafe-hammerhead `http-playground` command.

**Comment by mypchas6fans** [comment]
This is probably due to Akamai CDN blocking testcafe for its bot-like behavior based on our observation.
IKEA.com/us, IKEA.com/ru also suffers and it goes fine if we skip cdn.
Of course it would be ideal if testcafe could handle the error gracefully.

**Comment by miherlosev** [comment]
The issue is not reproduced with `testcafe@1.17.2-rc.2`.
