### ISSUE TITLE
[docs] Confusing docs for assertions wait mechanism

### ISSUE THREAD

**Issue by AlexanderMoiseev** [DevExpress/testcafe#6380]
Documentation for the [assertion mechanism ](https://testcafe.io/documentation/402827/guides/concepts/built-in-wait-mechanisms#wait-mechanism-for-assertions)is confusing. It is not clear if it is required to check whether an element exists before checking its properties.

[example](https://stackoverflow.com/questions/68338812/should-i-assert-for-existing-before-assertion-for-selector-property)

**Comment by titerman** [comment]
The January update to the Assertions guide fixed this issue
https://testcafe.io/documentation/402837/guides/basic-guides/assertions
