### ISSUE TITLE
Update the "Multi-window not supported" error message to indicate cloud, remote and provider-based browser limitations

### ISSUE THREAD

**Issue by VasilyStrelyaev** [DevExpress/testcafe#6387]
https://supportcenter.devexpress.com/internal/ticket/details/T1014268/
https://testcafe.io/documentation/402841/guides/advanced-guides/multiple-browser-windows#supported-browsers

**Comment by miherlosev** [comment]
It is necessary to add that the only `locally installed` browsers are supported.
