### ISSUE TITLE
Rename 'ff' browser alias to 'firefox'

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#639]

**Comment by AndreyBelym** [comment]
Please, wait for https://github.com/DevExpress/testcafe-browser-natives/issues/76.

**Comment by AndreyBelym** [comment]
Required code is merged. I didn't found any occurrences of `ff`,so @VasilyStrelyaev, please, fix the docs, or confirm that they are fine in their current state.

**Comment by VasilyStrelyaev** [comment]
We sure have a full list of aliases
https://github.com/DevExpress/testcafe/blob/master/docs/articles/documentation/using-testcafe/common-concepts/browser-aliases.md

**Comment by VasilyStrelyaev** [comment]
So we have to update the docs

**Comment by AndreyBelym** [comment]
Ok, I will fix them.

**Comment by AlexanderMoskovkin** [comment]
finished in https://github.com/DevExpress/testcafe/pull/645
