### ISSUE TITLE
RequestMock not intercepting request

### ISSUE THREAD

**Issue by Aaronius** [DevExpress/testcafe#6393]
### What is your Test Scenario?

 I'm attempting to use a RequestMock to mock a request.
 
### What is the Current behavior?

The request is not intercepted.
 
### What is the Expected behavior?

The request is intercepted.
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>React App</title>
    <script>
      fetch("https://edge.adobe.io/configs/user/edge?orderby=title", {
        headers: {
          "Authorization": "Bearer redacted",
          "Content-Type": "application/json",
          "x-api-key": "Activation-DTM",
          "x-gw-ims-org-id": "5BFE274A5F6980A50A495C08@AdobeOrg"
        }
      });
    </script>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
  </body>
</html>
```

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import {RequestMock} from "testcafe";

fixture.only("edge configs").page("http://localhost:3000");

const requestMock = RequestMock()
  .onRequestTo({
    url: "https://edge.adobe.io/configs/user/edge?orderby=title",
    method: "GET"
  })
  .respond(
    {
      foo: "bar"
    },
    200,
    {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Headers":
        "Accept,Authorization,Content-Type,If-Match,If-None-Match,User-Agent,x-api-key,x-gw-ims-org-id,x-request-id,x-debug-enabled,Keep-Alive,X-Requested-With"
    }
  )

test.requestHooks(requestMock)("My first test", async t => {
  // Test code
});

```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

The test passes but that's not really applicable.
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Follow the readme instructions here: https://github.com/Aaronius/testcafe-bugs/tree/request-mock-not-intercepting
3. When running the test, open the network panel and look for the request to `https://edge.adobe.io/configs/user/edge?orderby=title`.
4. Notice it's receiving a 401 Unauthorized. This should not be happening. TestCafe should instead be intercepting that request and returning a response object with `{ foo: "bar" }` (see [the spec](https://github.com/Aaronius/testcafe-bugs/blob/request-mock-not-intercepting/tests/example.spec.js)).

Does CORS play into this and, if so, why/how? I may just be misunderstanding something.

### Your Environment details:
 
* testcafe version:                   1.15.0
* node.js version:                    v14.16.1
* command-line arguments:  testcafe chrome -L
* browser name and version: Chrome Version 91.0.4472.114 (Official Build) (x86_64)
* platform and version:         OS 1.4 (20F71)
* other:

**Comment by pavsenin** [comment]
Hello,
Thank you for providing the code sample and detailed explanations.
We have reproduced the issue and will research it.
