### ISSUE TITLE
Implement global request hooks

### ISSUE THREAD

**Issue by Aleksey28** [DevExpress/testcafe#6395]
### What is your Test Scenario?
The ability to describe requests hooks for all tests.

### What are you suggesting?
Request hooks are assigned in the configuration file. After that, they start with each test.

**Comment by brombomb** [comment]
+1 I am trying to debug some possible flaky network issues.  Would love to be able to have a requestLogger/hook at the global level to catch errors and report on their status.  We have over 130 fixtures and 800 tests
