### ISSUE TITLE
t.click() on some selectors not working on Firefox 85 or newer

### ISSUE THREAD

**Issue by ebarila** [DevExpress/testcafe#6397]
### What is your Test Scenario?
Since Firefox 85 we've been experiencing issues with selectors, we currently test on safari, chrome, Edge, Opera on several different OS and the issue is only experienced on Firefox since version 85.

Example: Fifrefox 85 and further is not able to click this selector:

await t.click(userMenu);
User menu is defined like this.

Selector('button').find('span').withAttribute('aria-label', 'User Menu');
 
### What is the Current behavior?
Testcafe times out while trying to find and click the the user menu. 
 
### What is the Expected behavior?
Testcafe should find and click the selector.
 
### What is your web application and your TestCafe test code?
https://admin-demo.intouchstaging.com/
Authorization and credentials have been provided privately to Alex Skorkin.

Code has been shared in the past via StackOverflow but the issue seems to be independent of it.

### Steps to Reproduce:

1. Go to my website https://admin-demo.intouchstaging.com/
2. Log with the credentials provided for askorkin, it should drive you to a user table.
3. Execute this command: 

let userMenu = Selector('button').find('span').withAttribute('aria-label', 'User Menu');
await t.click(userMenu);
(Its the button on the upper right corner of the website)
4. See the error: Timeout
 
### Your Environment details:
 (will update this soon, not on my working computer right now. It shouldn't matter.)
* testcafe version:  1.15.0
* node.js version:   v15.10.0
* command-line arguments:   ./node_modules/.bin/testcafe firefox test.js --env XXX --test-meta TRID=XXXXXX
* browser name and version: Firefox >= 85
* platform and version:  Ubuntu 20.04 / MacOs Big Sur /Windows 10

**Comment by AlexKamaev** [comment]
I was able to reproduce the issue with Windows 10 and Firefox 90. However, I do not see any error. In my case, the expected popup window does not appear after the click. Do you face similar behavior?

We'll research the issue.

**Comment by ebarila** [comment]
That right, the problem is with the click action that isn't finding the UserMenu. I don't know why.

**Comment by rob4629** [comment]
We're also seeing this on a small section of our tests... I'll investigate reverting to an older version of FF. I'm happy to provide a details test scenario, if that would be helpful (but it seems like you've managed to reproduce it anyway)

**Comment by miherlosev** [comment]
Hi @rob4629

It will be useful if you can provide one more example. It can point to another issue.
