### ISSUE TITLE
Usage of 'testcafe' binary in the local installation mode

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#640]
According to https://docs.npmjs.com/files/folders#executables, locally installed binaries are linked to `node_modules/.bin/` directory. 

So which way is more convenient to use:
`node ./node_modules/testcafe/bin/testcafe ...args`
or 
`./node_modules/.bin/testcafe ...args`
?

**Comment by inikulin** [comment]
Neither. For local installations it should be used from npm scripts, e.g. `{ "test" : "testcafe myfile.js" }` For all other cases use globally installed CLI
