### ISSUE TITLE
TestCafe hangs on opening new window by clicking a button

### ISSUE THREAD

**Issue by BenDriesen** [DevExpress/testcafe#6400]
### What is your Test Scenario?
By clicking on a button, a new window is opened. The test should continue on the new window.
This was working on TestCafe 1.8.8, but seems to have broken after that version.
 
### What is the Current behavior?
TestCafe opens the new window, but then a js error is logged in the console and it waits for some time. Then the test restarts.
 
### What is the Expected behavior?
TestCafe opens the new window and the test continues in the new window
 
### What is your web application and your TestCafe test code?
<details>
<summary>Your website URL (or attach your complete example):</summary>
It is reproducible with the following web page

```
<script type="text/javascript">
    function openNewWindow(){    
      let newtab = window.open();
      newtab.location= `/page2.html`
    }
  </script>
<button type="button" onclick=openNewWindow();>Click me!</button>
```
page2.html contains some h1 text.

**Note: if you create the onclick event as onclick = window.open(`/page2.html`), the test works fine**

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

```js
 fixture`Smoke test`
test('Open new window on button click', async t => {
    await t
        .navigateTo('http://127.0.0.1:8080/index.html')
        .click(Selector('button'))
        .expect(Selector('h1').visible).ok()
  });
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>
No config file
</details>

<details>
<summary>Your complete test report:</summary>
After a few retries of the test, it ends with the following report; 

```
 Running tests in:
 - Chrome 91.0.4472.124 / Windows 10
 Smoke test
ERROR The Chrome 91.0.4472.124 / Windows 10 browser disconnected. If you did not close the browser yourself, browser performance or network issues may be at fault.
```
</details>

<details>
<summary>Screenshot</summary>
Screenshot of page2 and console
![image](https://user-images.githubusercontent.com/43610051/126304850-761ed0f9-2417-450c-bbcb-d324dcf9fc00.png)
</details>

### Steps to Reproduce:

1. Create the simple index page as described above and the page2.html
2. Use the test code to test you can click the button on the first page and the second page opens in a new window
3. The second page opens, but testcafe hangs. Open the console and you see an error message.
4. After some time, the test is retries

 
### Your Environment details:
 
* testcafe version:                   1.15.0
* node.js version:                    14.2.0
* command-line arguments:  testcafe chrome buttontest.js
* browser name and version: Chrome 91
* platform and version:          Windows 10
* other:                                   Was working correctly on version 1.8.8 and before, broke after that version.

**Comment by AlexKamaev** [comment]
Thank you for your example. I was able to reproduce the issue. As a workaround for the latest TestCafe versions, you can use the `--disable-multiple-windows` [option](https://testcafe.io/documentation/402841/guides/advanced-guides/multiple-browser-windows#disable-support-for-multiple-windows) while we are searching for a solution.
