### ISSUE TITLE
How to executes scripts using tags in Testcafe

### ISSUE THREAD

**Issue by Indium-SureshSK** [DevExpress/testcafe#6401]
I'm trying to execute only the smoke related test cases so kindly let me know how to use the tags functionality in testcafe so that if mention "@smoke" only the smoke related test cases can be executed

Let me know how to provide the Tags in 'fixture' level as well as the 'test' level.

![fixture   test](https://user-images.githubusercontent.com/39326747/126325237-406da21e-3f92-4cab-8ba2-38765234834e.png)
![folder structure](https://user-images.githubusercontent.com/39326747/126325244-d1607a98-032c-47ed-97ee-f8d54e4e68a0.png)

**Comment by flora8984461** [comment]
You may want to use "meta", such as test.meta({smoke: true}) or test.meta({type: smoke}), and use filter in testrunner object.
reference: https://testcafe.io/documentation/402641/reference/testcafe-api/runner
https://testcafe.io/documentation/402657/reference/testcafe-api/runner/filter
