### ISSUE TITLE
1.15.1-rc.1 is throwing Uncaught object "[object Object]" was thrown. Throw Error instead.

### ISSUE THREAD

**Issue by raj-balaebail** [DevExpress/testcafe#6405]
### What is your Test Scenario?

The test is clicking a button. Currently I get 
```Uncaught object "[object Object]" was thrown. Throw Error instead.```

https://hub.docker.com/layers/testcafe/testcafe/1.15.1-rc.1/images/sha256-eff6bea6e23556bd041d47a3a02b74a8fd123710d4c2b21f0785a0d93ffed6d6?context=explore
 
### What is the Current behavior?

```
rajbalaebail@Rajs-MacBook-Pro e2e-tests % docker run -v /Users/rajbalaebail/amount-repos/e2e-tests/testcafe:/tests -it testcafe/testcafe:rc chromium /tests/tests/uil/apply/eloan-tests/personal-application-page/personal-application-page-tests.spec.js
 Running tests in:
 - Chrome 91.0.4472.164 / Linux 0.0

Personal application page tests - eLoan
App ID: 49
 ✖ eLoan - Step 1 - PA Page: Verify person age <18 is declined

   1) Uncaught object "[object Object]" was thrown. Throw Error instead.

      Browser: Chrome 91.0.4472.164 / Linux 0.0
```
### What is the Expected behavior?

```
rajbalaebail@Rajs-MacBook-Pro e2e-tests % docker run -v /Users/rajbalaebail/amount-repos/e2e-tests/testcafe:/tests -it testcafe/testcafe:1.15.0 chromium /tests/tests/uil/apply/eloan-tests/personal-application-page/personal-application-page-tests.spec.js

 Running tests in:
 - Chrome 91.0.4472.124 / Linux 0.0

Personal application page tests - eLoan
App ID: 51
 ✓ eLoan - Step 1 - PA Page: Verify person age <18 is declined
 ```
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by raj-balaebail** [comment]
Looks like this is happening when you try to press the TAB button.

```
import { Selector, t } from 'testcafe';

fixture('DevExpress/testcafe/issues/6405')
  .page('https://eloan.stg.internal.amount.com/apply')

test('test', async t => {
  console.log('here')
  await t.pressKey('tab')
  console.log('here 1')
})
```
```
rajbalaebail@Rajs-MacBook-Pro e2e-tests % docker run -v /Users/rajbalaebail/amount-repos/e2e-tests/testcafe:/tests -it testcafe/testcafe:rc chromium /tests/tests/uil/apply/eloan-tests/personal-application-page/test.spec.js
 Running tests in:
 - Chrome 91.0.4472.164 / Linux 0.0

 DevExpress/testcafe/issues/6405
here
 ✖ eLoan - Step 1 - PA Page: Verify fields, field errors, tooltips, dropdowns

   1) Uncaught object "[object Object]" was thrown. Throw Error instead.

      Browser: Chrome 91.0.4472.164 / Linux 0.0



 1/1 failed (19s)
```

**Comment by AlexKamaev** [comment]
I was not able to reproduce the issue. It looks like the website is unreachable for me. Please provide us with access to your website or prepare a separate sample. Thank you in advance.
 
If you need to share some credentials to us you can send it at support@devexpress.com
 

Please note that our policy prevents us from accessing internal resources without prior written approval from a site owner. If we need to access non-public parts of your website or pass through authorization pages, please ask the website owner to send us (support@devexpress.com)) a written confirmation. It must permit DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes.

**Comment by raj-balaebail** [comment]
@AlexKamaev you can try this on `https://www.my.eloan.com/apply` instead.

**Comment by AlexKamaev** [comment]
I was able to reproduce the issue. Thank you for your assistance.
