### ISSUE TITLE
Failure to login through oAuth with Azure Static Web Apps

### ISSUE THREAD

**Issue by baguilar-work** [DevExpress/testcafe#6408]
### What is your Test Scenario?
The big goal is to do End to End testing on our applications, including login. The Test Scenario is attempting to login on a 3rd party oAuth System (FusionAuth) which is being ran and through Azure Static Web Apps Custom Authentication. 
 
### What is the Current behavior?
I am redirected back to the home page not logged in and no session cookie or data is saved.
 
### What is the Expected behavior?
After login, we are successfully redirect to the call back URL OR we are successfully logged in then I can code the redirect to the next page myself. Either is fine.
 
### What is your web application and your TestCafe test code?
Very small Sample Application for testing this: https://github.com/littlevahn/TestLoginSample/tree/dev
 
<details>
<summary>Test Login App</summary>

Code: https://github.com/littlevahn/TestLoginSample/tree/dev
URL of App: https://purple-pond-078e7901e.azurestaticapps.net/
Creds have been emailed to the desired email. 
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector, Role } from 'testcafe';

const testUser = Role('https://purple-pond-078e7901e.azurestaticapps.net/login', async t => {
	const username = 'ed3dc4d914cb4b15bc57@mailspons.com';
	const password = 'Wl1Z!Yz#C6OKzOX%D6o1';
	await t
		.typeText('#loginId', username)
		.typeText('#password', password)
		.click('.submit');
}, { preserveUrl: true });

fixture
	.disablePageCaching`Dashboard Order Flyer NOW! - Integration Flow`
	.page`https://purple-pond-078e7901e.azurestaticapps.net/`;

test
	.disablePageCaching('Login to Test Users Account', async t => {

		await t.useRole(testUser);

		//const username = 'ed3dc4d914cb4b15bc57@mailspons.com';
		//const password = 'Wl1Z!Yz#C6OKzOX%D6o1'
		/*await t
			.click('.MuiButtonBase-root-30')
			.typeText('#loginId', username)
			.typeText('#password', password)
			.click('.submit')
			.expect('#cardContentWrapper > div:nth-child(1) > div').exists;
			*/
	});

test
	('Select a listing and Purcahse a flyer', async t => {
		await t
			.navigateTo('https://purple-pond-078e7901e.azurestaticapps.net/ml/home')
			.expect('#cardContentWrapper > div:nth-child(1) > div').exists;
	});

```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```
> testcafe chrome --max-http-header-size=2048000 --live tests\endToEnd\NowDashboard\OrderFlyer.spec.js


Live mode is enabled.
TestCafe now watches source files and reruns
the tests once the changes are saved.

You can use the following keys in the terminal:
'Ctrl+S' - stops the test run;
'Ctrl+R' - restarts the test run;
'Ctrl+W' - enables/disables watching files;
'Ctrl+C' - quits live mode and closes the browsers.


Watching the following files:
  C:\TF\Src\IntegrationTests2\tests\endToEnd\NOWDashboard\OrderFlyer.spec.js
 Running tests in:
 - Chrome 91.0.4472.164 / Windows 10

 Dashboard Order Flyer NOW! - Integration Flow
 √ Login to Test Users Account


 2 passed (6s)

Make changes to the source files or press Ctrl+R to restart the test run.

Stopping TestCafe live mode...
Terminate batch job (Y/N)? y
PS C:\TF\Src\IntegrationTests2> npm run testPOC

> integrationtests2@1.0.0 testPOC C:\TF\Src\IntegrationTests2
> testcafe chrome --max-http-header-size=2048000 --live tests\endToEnd\NowDashboard\OrderFlyer.spec.js


Live mode is enabled.
TestCafe now watches source files and reruns
the tests once the changes are saved.

You can use the following keys in the terminal:
'Ctrl+S' - stops the test run;
'Ctrl+R' - restarts the test run;
'Ctrl+W' - enables/disables watching files;
'Ctrl+C' - quits live mode and closes the browsers.


Watching the following files:
  C:\TF\Src\IntegrationTests2\tests\endToEnd\NOWDashboard\OrderFlyer.spec.js
 Running tests in:
 - Chrome 91.0.4472.164 / Windows 10

 Dashboard Order Flyer NOW! - Integration Flow
 √ Login to Test Users Account
 √ Select a listing and Purchase a flyer


 2 passed (6s)
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

What Success looks like through the UI none testcafe:

1. Go to https://purple-pond-078e7901e.azurestaticapps.net/
2. Click signin
3. Fill in Credentials (emailed)
4. Click submit
5. Get redirect to https://purple-pond-078e7901e.azurestaticapps.net/ml/home Logged in and see 'listing data'

 
### Your Environment details:
 
* testcafe version:                   1.15.0
* node.js version:                    v12.18.0
* command-line arguments:  testcafe chrome --max-http-header-size=2048000 --live tests\\endToEnd\\NowDashboard\\OrderFlyer.spec.js
* browser name and version:  Chrome 91
* platform and version:          Windows 10

**Comment by miherlosev** [comment]
Hi @baguilar-work 

Thank you for the shared information. I've reproduced the issue.

**Comment by earlyriser** [comment]
Hi @miherlosev 

Is there an ETA for this fix? Maybe I'm having the same (or a similar) issue: I'm able to login with FusionAuth on my first test, but on the second one that login status is not preserved, and if I try to login again it's not possible.
