### ISSUE TITLE
Update to the latest typescript version

### ISSUE THREAD

**Issue by DanKaplanSES** [DevExpress/testcafe#6410]
### What is your Test Scenario?
In my project I'm using [Template Literal Types](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html). When I run testcafe, I get this error message: 

```
Error: TypeScript compilation failed.
a/path/to/a/typescript/file.ts (34, 16): Type expected.
a/path/to/a/typescript/file.ts (34, 34): Cannot find name 'Lowercase'.
a/path/to/a/typescript/file.ts (34, 53): '(' expected.
a/path/to/a/typescript/file.ts (34, 54): Argument expression expected.
a/path/to/a/typescript/file.ts (34, 56): Cannot find name 'but'.
a/path/to/a/typescript/file.ts (34, 60): ',' expected.
a/path/to/a/typescript/file.ts (34, 60): Cannot find name 'you'.
a/path/to/a/typescript/file.ts (34, 64): ',' expected.
a/path/to/a/typescript/file.ts (34, 64): 'never' only refers to a type, but is being used as a value here.
a/path/to/a/typescript/file.ts (34, 70): ',' expected.
a/path/to/a/typescript/file.ts (34, 70): Cannot find name 'know'.
a/path/to/a/typescript/file.ts (37, 1): Unterminated template literal.
```

That line is this: ``description: `...${Lowercase<Foo>}, but you never know!` `` and it compiles without error when I run `tsc`. I'm assuming that the problem is that testcafe is using an old version of typescript to execute my code, one that has a breaking change to this functionality.

### What are you suggesting?
Update to the latest version of typescript.

### What alternatives have you considered?
I tried forking the project to see if I could create a PR for this, but for reasons I don't understand, the steps to follow in the contribute file error when I try to run the tests. There's typescript errors all over the place complaining about how `Selector` isn't defined, for example. For all I know, updating to the latest version will work fine, but I have no a way of confirming this since I can't test the project.

**Comment by AndreyBelym** [comment]
Upgrading typescript from version 3 to version 4 is a breaking change, so currently we cannot upgrade  the default typescript version. Currently, you can use the  `typescript.customCompilerModulePath` option to specify your own typescript compiler: https://testcafe.io/documentation/402639/reference/command-line-interface#--compiler-options-options
