### ISSUE TITLE
Custom reporter :: TypeError: Cannot read property 'viewportWidth' of undefined

### ISSUE THREAD

**Issue by MindaugasMateika** [DevExpress/testcafe#6414]
### What is the Current behavior?
When using [helper function to format error](https://testcafe.io/documentation/402790/reference/plugin-api/reporter#formaterror) it throws an error `TypeError: Cannot read property 'viewportWidth' of undefined`. Since the error is originating in Testcafe source hence the issue is in this repository.
 
### What is the Expected behavior?
It should format error without throwing an error.

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js

// Snippet with formatError usage:

        if (testRunInfo.errs.length) {
            try {
                testRunInfo.errs.forEach(err => {
                    let error = nativeFormatError(err, 'smth');
                    console.log(`Error: ${error}`);
                })
            } catch (e) {
                console.log(`Couldn't format: ${e}`);
            }
        }

// Helper
import { IReporterPluginHost } from './models'

const ReporterPluginHost = require('testcafe/lib/reporter/plugin-host')
const outStream: string = '';
const plugin: IReporterPluginHost = new ReporterPluginHost({}, outStream);

export const nativeFormatError = plugin.formatError;

// ReporterPluginHost interface
export interface IReporterPluginHost {
    formatError: (err: any, prefix: string) => string;
}
 
```
</details>
 
### Your Environment details:
 
* testcafe version:                  1.0.1 but tried other versions as well
* node.js version:                    16.3.0
* browser                                chrome, chrome:headless
* platform and version:          macOS 11.3.1

**Comment by AlexanderMoiseev** [comment]
Hello,

To fix your code, bind the formatError function to the plugin object:

`const nativeFormatError = plugin.formatError.bind(plugin);`

Also, please note that using a private API is risky and can stop working at some point.
