### ISSUE TITLE
A non-informative report is generated when running a *.testcafe fixture file using CLI

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe#6424]
### What is your Test Scenario?
Need to find out which step of the recorded (`*.testcafe`)  test fails.
 
### What is the Current behavior?
The report doesn't specify the failed step.
 
### What is the Expected behavior?
It should display the number and/or a description of the failed step.
 
### What is your web application and your TestCafe test code?
[recorded-examples.zip](https://github.com/DevExpress/testcafe/files/6892278/recorded-examples.zip)

<details>
<summary>Your complete test report:</summary>

```
 Running tests in:
 - Chrome 91.0.4472.164 / Windows 10

 A set of examples that illustrate how to use TestCafe API
 × 1

   1) AssertionError: expected true to be falsy

      Browser: Chrome 91.0.4472.164 / Windows 10

      10

```
</details>

### Steps to Reproduce:
1. Launch `npx testcafe chrome recorded-examples.testcafe`
 
### Your Environment details:
 
* testcafe version:                   1.15.0
* node.js version:                    16.3.0
* command-line arguments:  npx testcafe chrome recorded-examples.testcafe
* browser name and version: Chrome 91
* platform and version:          Windows 10

**Comment by sashikamw** [comment]
@Dmitry-Ostashev I'm using testcafe docker image to execute my tests, and I'm still experiencing this issue 

```
1) AssertionError: expected false to be truthy
--
18 |  
19 | Browser: Chrome 101.0.4951.64 / Linux 0.0
20 |  
21 | 23
```


This is the command I'm using 
`/opt/testcafe/docker/testcafe-docker.sh -c 3 chromium -q --skip-js-errors --assertion-timeout 60000 --selector-timeout 60000 TestsRepo/*.testcafe`

Appreciate any help to get this solved?

**Comment by Dmitry-Ostashev** [comment]
@sashikamw Thank you for your comment. TestCafe does not show full error information for a failed assertion step. I created a separate issue for this case: [https://github.com/DevExpress/testcafe/issues/7089](https://github.com/DevExpress/testcafe/issues/7089). Please track it to be notified when it is fixed.
