### ISSUE TITLE
Command Line Arguments not working correctly after 1.15.1 release

### ISSUE THREAD

**Issue by etobin** [DevExpress/testcafe#6426]
### Are you requesting a feature or reporting a bug?
Reporting a bug

### What is your Test Scenario?
I am running a testcafe command and passing an argument to specify what environment I want to run my test in. For example:
`testcafe "browserstack:chrome@78.0:OS X Mojave" smoke-test.js --skip-js-errors --env=production`

### What is the Current behavior?
With version 1.15.1 when I include `--env=production` the command fails with `error: unknown option '--env=production'`

### What is the Expected behavior?
With version 1.15.0 I was able to successfully pass my env command line argument with no problem.

### How would you reproduce the current behavior (if this is a bug)?
Try to run command like the above with testcafe version 1.15.1

#### Provide the test code and the tested page URL (if applicable)
Not applicable since this is a command line problem
 
Your website URL (or attach your complete example):

Your complete test code (or attach your test files)

```js

```
### Your Environment details:
 
* testcafe version:                   1.15.1
* node.js version:                    
* command-line arguments:  testcafe "browserstack:chrome@78.0:OS X Mojave" smoke-test.js --skip-js-errors --env=production
* browser name and version: 
* platform and version:          
* other:

**Comment by felis2803** [comment]
Thank you for your report. We will deal with this bug. Stay tuned for updates on this issue.

**Comment by EasyKAD-tester** [comment]
I have the same issue. Sharing GitHub action traces, maybe it can be helpful. 

![image](https://user-images.githubusercontent.com/81394921/127555200-f08e79d2-4409-45e7-b503-88baf4a643df.png)

**Comment by becciwatson** [comment]
Yes we have the same problem, pull request for this bug is not yet pulled/released.

**Comment by AlexanderMoiseev** [comment]
Hi, 

Thank you for your input, we'll get back to you when we have any results.
