### ISSUE TITLE
Testcafe keeps sending heartbeat to a browser which returning 200 status

### ISSUE THREAD

**Issue by IssacH** [DevExpress/testcafe#6430]
Hi guys,

Recently I encountered one issue when I am using testcafe as automation tool. My scenario is quite simple as below:
1. Navigate to one page
2. Do some operations
3. Navigate to another page(May need to load many resources for js and css files). 

For the third step, testcafe will fail to navigate to that page and when I checked in the network tab of Dev tool, testcafe keeps sending heartbeat to a browser which returning 200 status. Also, sometimes a request like "http://localhost:50321/testcafe-ui-sprite.png" will also be sent repeatedly and the page will not be loaded. Could you please give me some suggestions? Please refer to the attachments, sorry but I could not share my testing environment due to the internal usage.

Environment:
Testcafe: "^1.14.2"
Chrome: "Version 92.0.4515.107"

Attachments:
![testcafe navigation](https://user-images.githubusercontent.com/17758420/127765465-6158571a-1d1c-4872-bcc4-4c2dda008d6a.png)

https://user-images.githubusercontent.com/17758420/127766573-97c16a2e-825e-47ad-ae6d-83ca4f77d118.mp4

Thanks,
Issac

**Comment by AlexKamaev** [comment]
Heartbeat is a TestCafe mechanism that helps TestCafe understand whether the browser is still running or was disconnected for some reason. So, it's OK even if the page did not load correctly. Heartbeat runs in a separate worker, so it should not cause problems with page loading.
