### ISSUE TITLE
getTestList and getTypeScriptTestList in embeddingUtils get wrong test info with disablePageCaching

### ISSUE THREAD

**Issue by flora8984461** [DevExpress/testcafe#6433]
### What is your Test Scenario?

I found this when I work on the [PR](https://github.com/DevExpress/testcafe/pull/6398) to get skipped info from `getTestList` and `getTypeScriptTestList`.

The test case is:
```
test.disablePageCaching(`testname`, async t => {})
``` 

Or 

```
import page from './page-model';


fixture `A set of examples that illustrate how to use TestCafe API`
    .page `https://devexpress.github.io/testcafe/example/`;

// Tests
test.disablePageCaching('Text typing basics', async t => {
    await t
        .typeText(page.nameInput, 'Peter') // Type name
        .typeText(page.nameInput, 'Paker', { replace: true }) // Replace with last name
        .typeText(page.nameInput, 'r', { caretPos: 2 }) // Correct last name
        .expect(page.nameInput.value).eql('Parker'); // Check result
});
```

### What is the Current behavior?

`getTestList` and `getTypeScriptTestList` cannot recognize the test if the test name is wrapped inside disablePageCaching().

The result returns:
```
[{"name":"A set of examples that illustrate how to use TestCafe API","loc":{"start":{"line":4,"column":0},"end":{"line":5,"column":58}},"start":38,"end":165,"meta":{},"tests":[]}]
```
 
### What is the Expected behavior?

It should recognize the test and put it in the tests array. When I run the test, it is executed.

### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Use the same test case above.
2. Use this API call: 
```
const getTestList = require('testcafe').embeddingUtils.getTestList;  // The same for getTypeScriptTestList()
const res = await getTestList('TEST_FILE_PATH');
```
3. Check the result, the test is not recognized
 
### Your Environment details:
 
* testcafe version:                   1.15.1 
* node.js version:                    14.16.1
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:                                   

I am not sure if this is expected behaviour? 

Thanks!

**Comment by AlexKamaev** [comment]
This behavior is not expected. However, as we already mentioned, modifying these utils is not in our prior tasks. If you want, you can create a PR, but before this, we need to merge the PR with the skipped tests.
