### ISSUE TITLE
Testcafe fails to run in macOS with weird failure messages each time

### ISSUE THREAD

**Issue by itskavya28** [DevExpress/testcafe#6434]
### What is your Test Scenario?
**Our setup**

We're running testCafe in Visual Studio Team Services as a part of our build infrastructure. We're using VM's running macOS 10.15.7. We're installing Chrome (latest stable), Firefox in headless mode. 
### What is the Current behavior?

im seeing the following errors when i do `testcafe chrome test.spec.smoke.js` also tried with firefox but it fails to load the UI and fails , ref ss below 
![image](https://user-images.githubusercontent.com/81216530/127968522-8928277e-3f68-48f5-b264-035d8196e170.png)

![image](https://user-images.githubusercontent.com/81216530/127968938-daab9d4b-7693-4f88-a6e7-cb72a9eda681.png)

i have also set the permission for Testcafe in my mac system preferences. 
![image](https://user-images.githubusercontent.com/81216530/127969302-857df4fb-0ecb-41e1-99eb-2451c4303737.png)

### What is the Expected behavior?
It works on my windows machine, but strangely it is failing in macOS. 

### What is your web application and your TestCafe test code?
my sample test code looks like this
```
fixture`Getting Started`
    .page`${config.uiServerURL}/web/#/gettingStarted`
    .requestHooks(baseMock)

test('Sanity', async t => {
    await t
        .expect(Page.instructionsHeaderText()).contains('Setting up App')
        .expect(Page.hideButtonExists()).ok();
    await takeScreenshot(t, 'Getting started');
});
test('Hide button should hide page', async t => {
    await Page.clickHideButton(t);
    await t.expect(getLocationHash()).contains('/alerts')   
})
```
<detail>
Any suggestions on how to fix this would be highly appreciated.
</detail>
### Your Environment details:
 
* testcafe version: 1.15.1                  
* node.js version:    14.17.3                
* npm version 6.14.13
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by Farfurix** [comment]
@itskavya28 

Hello,

Could you please check if the issue persists by performing some public URL simple test on your VM? You can also try to [reset macOS permissions](https://stackoverflow.com/questions/58595993/tests-not-running-in-testcafe-getting-error-typeerror-cannot-read-property-sp#comment103595160_58595993).
**test.js**:
```js
import { Selector } from 'testcafe';

fixture `MyFixture`
    .page('http://devexpress.github.io/testcafe/example');

test('My test', async t => {
    const h1Exists = Selector('#main-form > div > header > h1').exists;

    await t.expect(h1Exists).ok();
});
```
**Command**:
```
testcafe chrome test.js
```

If the above test is successful, please share a simple reproducible example. Your attached test doesn't contain any URL. So, we cannot examine your application logic on our side.

**Comment by itskavya28** [comment]
@Farfurix  sorry for not being clear in my issue. 
I tried what you suggested. 
1. Cleared my sustem prefrences by `tccutil reset AppleEvents` and did a reset `tccutil reset ScreenCapture`
2. Added the code above and ran it, I still see the issue , tests are not getting executed see the errors in the ss. 
3. 
<img width="1204" alt="Screenshot 2021-08-03 at 1 58 44 PM" src="https://user-images.githubusercontent.com/81216530/127984848-0c48f9d6-50b7-4e1f-b6c8-848e5ff12bbe.png">

4. After about 5-7 mins of testcafe retrying it failed. Ref ss below for error. 
5. 
<img width="1404" alt="Screenshot 2021-08-03 at 2 02 49 PM" src="https://user-images.githubusercontent.com/81216530/127984990-b9e5ae62-08f1-478a-a190-a4dea280969d.png">

**Comment by Farfurix** [comment]
@itskavya28 

> Im using `testcafe -v Using locally installed version of TestCafe. 1.13.0`

Could you please check this usage scenario with the latest TestCafe version (v1.15.1) and share your result?

**Comment by itskavya28** [comment]
there is absolutely no difference in the situation @Farfurix :( 
I updated testcafe to `1.15.1`
please see the screenshots.
![image](https://user-images.githubusercontent.com/81216530/127996975-44b13725-c569-4708-aabd-ba207c551d43.png)


![image](https://user-images.githubusercontent.com/81216530/127996921-2a65e702-36e3-41ca-8504-920d4a36fb0a.png)

**Comment by Farfurix** [comment]
@itskavya28 

Thank you for the clarification. It looks like this issue relates to your network setup. Since I cannot reproduce this issue, I can only advise you to add [`--hostname localhost`](https://testcafe.io/documentation/402639/reference/command-line-interface#--hostname-name) to your TestCafe command and share the result again.

**Comment by itskavya28** [comment]
@Farfurix  All our testcafe tests run on` localhost:8080` and we have specified this in the `configFile` and use the same in our tests , so it means my initial problem was with localhost itself. 
This is my config file
```
import _ from 'lodash';

let config = {
    uiServerURL: 'http://localhost:8080',
};

function processConfig() {
    try {
        config = _.extend(config, require('../config'));
    }
    catch (e) {
        console.warn(`(No optional config.json found)`);
    }

    // also allow env vars to override config settings
    if (!_.isEmpty(process.env.UI_SERVER_URL)) config.uiServerURL = process.env.UI_SERVER_URL;

    // eslint-disable-next-line  no-console
    console.log(`config uiServerURL = ${config.uiServerURL}`);
}

processConfig();

export default config;
```

we use it in our tests like this 

```
fixture`Getting Started`
    .page`${config.uiServerURL}/web/#/gettingStarted`
    .requestHooks(baseMock)

test('Sanity', async t => {
    await t
        .expect(Page.instructionsHeaderText()).contains('Setting up App')
        .expect(Page.hideButtonExists()).ok();
    await takeScreenshot(t, 'Getting started');
});
test('Hide button should hide page', async t => {
    await Page.clickHideButton(t);
    await t.expect(getLocationHash()).contains('/alerts')   
})
```

I tried `testcafe chrome  --hostname localhost tests.js`  command for the test which you shared it dosent seem to execute with `--hostname localhost 
`

Please let me know how can make this work so I can share the results.

**Comment by Farfurix** [comment]
@itskavya28 

> I tried testcafe chrome --hostname localhost tests.js command for the test which you shared it dosent seem to execute with --hostname localhost

Do you get an error when using both `chrome --hostname localhost tests.js` and `chrome tests.js --hostname localhost` variants of the command? Please share the complete log for both cases of the command.

Please clarify the steps I should perform to reproduce the issue:
1. What is your local machine's operating system?
2. What virtualization software do you use on your local machine to run macOS Catalina (10.15.7)?
3. Do you run your test directly from the macOS virtual machine?

**Comment by itskavya28** [comment]
@Farfurix 
Using chrome tests.js --hostname localhost worked with the example test.js that you shared however , My other tests are still failing, with same above mentioned errors. (Still not sure Why)
1. Im using Macbook with MacOS 11.4 Big Sur
2. I use visual studio code(vsCode) to run testcafe tests which takes macOS 10.15.7
3. I run my tests directly from my macbook/macOS

**Comment by Farfurix** [comment]
@itskavya28 

OK, I see. You don't use any VM on your Mac. Please note that "macOS 10.15.7" is calculated based on `navigator.userAgent` of your browser:
![Screenshot-2021-08-05-at-10 16](https://user-images.githubusercontent.com/30019338/128309086-5bcad6ca-8cc7-4da4-b07f-6d625e59e414.jpg)
Your tests are running on your "11.4 Big Sur".

Let's summarize your case:
1. To pass the "http://devexpress.github.io/testcafe/example" simple test, you have to add the `--hostname` option to your command: `testcafe chrome test.js --hostname localhost`.
2. Your project tests that are hosted locally (localhost:8080) cannot be passed successfully even with adding the `--hostname localhost` option.

Could you please check the following example project on your side? I want to know if it is possible to pass a test with a simple locally hosted page.

1. Commands for a new project:
```
npm init -y
npm i testcafe http-server
```
2. Add files to the root project directory:

**index.html**
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Test</h2>
</body>
</html>
```
**test.js**
```js
import { Selector } from 'testcafe';

fixture `Fixture`
    .page('http://localhost:8080');

test('test', async t => {
    const h2Exists = Selector('h2').withText('Test').exists;

    await t.expect(h2Exists).ok();
});
```
3. Start the server (it is more convenient to use a separate terminal window/tab for this):
```
npx http-server
```
4. Run TestCafe without `--hostname`: `npx testcafe chrome test.js`
5. Run TestCafe with `--hostname`: `npx testcafe chrome test.js --hostname localhost`.
6. Share the results of steps 4 and 5.
