### ISSUE TITLE
Option to have entire fixtures run concurrently

### ISSUE THREAD

**Issue by kdueckmann** [DevExpress/testcafe#6435]
### What is your Test Scenario?
We are testing a large Website with numerous pages (using Page Object Models) and several asynchronous and long-running operations. For example, to test the creation of a user, we have to refresh our page for up to 15 minutes to check if it has been successfully created. That lead us to use "setup" and "teardown" tests in the beginning and end of a fixture to create and delete the ressources we want to perform tests on.

Now we would like to introduce concurrency into our test pipeline. In our case, a fixture should be run in its original order consecutively, but multiple fixtures can be run in parallel. This is not yet possible or configurable with TestCafe, but would help us immensely in reducing execution time, especially considering the long waiting periods for certain resources.

### What are you suggesting?
An additional flag/option when using concurrent execution, which achieves that one browser is matched with one fixture, completes that fixtures execution in order, and is then matched with the next fixture.

### What alternatives have you considered?
We have thought about actually making every test case completely independent (as it usually should be), but have decided against it because of the immense waiting time we would produce by having every test create a separate ressource.

Without an option like this, concurrency is not poissible in our case. But it would massively help with execution time.

### Additional context
/

**Comment by AlexKamaev** [comment]
Hello.
We already have a similar request so I'll close this one as a duplicate. Please track the [https://github.com/DevExpress/testcafe/issues/2011](https://github.com/DevExpress/testcafe/issues/2011) issue.
