### ISSUE TITLE
Add the information from the original error in the reporter to the console output.

### ISSUE THREAD

**Issue by artinada** [DevExpress/testcafe#6437]
### What is your Test Scenario?
Executing tests in testcafe with "xray-cloud-json" reporter

### What is the Current behavior?
It's hard to understand what is going on with the report because the error is ignored.
https://github.com/DevExpress/testcafe/blob/61f3703d50ef8cc64331d09659837c52a9aae862/src/utils/reporter.ts#L9-L10

```
yarn test:wellbeing
yarn run v1.22.10
$ JIRA_XRAY_CLOUD_TESTPLANKEY=WEB-1314 dotenv -- testcafe --reporter xray-cloud-json
The "reporter" option from the configuration file will be ignored.
ERROR The provided "xray-cloud-json" reporter does not exist. Check that you have specified the report format correctly.

Type "testcafe -h" for help.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### What is the Expected behavior?
Please add an original error (`err`) output in the console
For example, in my case it should be:
```
yarn test:wellbeing
yarn run v1.22.10
$ JIRA_XRAY_CLOUD_TESTPLANKEY=WEB-1314 dotenv -- testcafe --reporter xray-cloud-json
The "reporter", "filter" options from the configuration file will be ignored.
Error: ENOENT: no such file or directory, open '.env.example'
```

### Your Environment details:
testcafe version: 1.9.3
node.js version: node 12.18.2
command-line arguments: --reporter xray-cloud-json
browser name and version: running in chrome Browserstack
platform and version: MacOs

**Comment by pavsenin** [comment]
Hello,
Thank you for pointing out this issue to us. We will consider adding the information from the original error to the console output.

**Comment by Artem-Babich** [comment]
Implemented in https://github.com/DevExpress/testcafe/pull/7759
