### ISSUE TITLE
Angular part of the application is not loaded

### ISSUE THREAD

**Issue by valiakseyeva** [DevExpress/testcafe#6438]
Our company is currently evaluating TestCafe / TestCafe Studio as a testing framework for our e2e testing.

We created a UI test for our application and were faced with an issue that did not allow us to go further.

We have a multi-frame version of the application that is combined ExtJs (parent iframe) and Angular (inner iframe).

When we click on the button inside the parent iframe (ExtJs), TestCafe opens a new window and the Angular part is not loaded.

When we use our application manually or with other test frameworks, no new windows are created, and iframe is loaded into the existing window.

With Testcafe, clicking on the button, always causing opening a new browser window, without loading any data.

The issue is reproducible across different browsers Chrome, Firefox, and Safari. There are no errors in the console and no failed network requests or other errors.

We tried to disable multiple finds with `--disable-multiple-windows` flag, it prevented a new window from being opened; however, the iframe still wasn't loaded.
 
### What is your web application and your TestCafe test code?
Our application is not public, so a person without the username and password cannot log in and get access to it. Our company can provide temporary access to the dev machine for testing purposes. However, we cannot share any credentials on GitHub. We can provide this information: the link to the server, credentials, and test code to someone from your support team directly by email

Thanks for understanding. We appreciate your help!
 
### Your Environment details:
 
System:
OS Linux 3.10.0-1160.36.2.el7.x86_64 x86_64
Angular CLI: 11.2.14
Sencha Cmd v7.2.0.56
TestCafe version: 6.14.13

Testing environment:
OS: macOS 10.15.7 (19H1030)
Chrome: 83.0.4103.97 (64-bit)
Firefox: 88.0.1 (64-bit)
Safari 14.1.2 (15611.3.10.1.5, 15611)

**Comment by felis2803** [comment]
Hello Viktoryia,

Please send the data required to access your application by email to support@devexpress.com. In the email, refer to this issue.
Also, I should note that our policy prevents us from accessing a customer's internal resources without prior written approval from the entity that owns the server/web resource. Therefore, the request for research must come from the person who has the right to grant us access. It should contain permission for DevExpress personnel to access the resource for the purpose of research, testing, and debugging.

**Comment by valiakseyeva** [comment]
The email was sent. Thank you!

**Comment by jurisv** [comment]
Team, I see that "Need response" label was added again yesterday. We sent the requested info on Friday. 
Please let us know if there is anything else you might need.

**Comment by Farfurix** [comment]
@valiakseyeva @jurisv 

Hello,

Thank you for the information. I reproduced the issue with Windows 10 and Chrome 92.

**Comment by jurisv** [comment]
Hello @Farfurix !
Were you able to come up with the fix/workaround?

Best,
Juris
