### ISSUE TITLE
Scrolling to the top of page occurs before taking screenshot by takeElementScreenshot

### ISSUE THREAD

**Issue by DmitryKalbeka** [DevExpress/testcafe#6440]
### What is your Test Scenario?
To take a screenshot of an element
 
### What is the Current behavior?
The incorrect page area screenshot is taken by takeElementScreenshot due to scrolling to the top of the page

### What is the Expected behavior?
The element screenshot is taken
 
 
```js
import { Selector } from 'testcafe'

fixture`Tmp`.page`https://www.w3schools.com/js/default.asp`

test(`Tmp`, async (t) => {
  const label = Selector('h2').withExactText('Learning Speed')
  await t.hover(label)
  await t.takeElementScreenshot(label, 'element.png')
})  
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
  "src": ["src/specs/**/*.ts"],
  "browsers": ["browserstack:chrome"],
  "tsConfigPath": "./tsconfig.json",
  "screenshots": {
    "path": "./screenshots/",
    "pathPattern": "${DATE}_${TIME}/${TEST}/${USERAGENT}/${FILE_INDEX}.png",
    "takeOnFails": false,
    "fullPage": true
  },
  "debugOnFail": false,
  "concurrency": 1,
  "pageLoadTimeout": 30000,
  "selectorTimeout": 10000,
  "assertionTimeout": 30000,
  "reporter": [
    {
      "name": "spec"
    },
    {
      "name": "xunit",
      "output": "reports/test-results/results.xml"
    }
  ]
}
```
</details>

<details>
<summary>Actual result:</summary>
![image](https://user-images.githubusercontent.com/48528215/128344671-00888974-7bf0-4249-91e2-cb113cf6b189.png)
</details>

<details>
<summary>Expected result:</summary>
![image](https://user-images.githubusercontent.com/48528215/128344537-159955ca-2e67-4ea7-9bf2-3e2d575866c4.png)
</details>
 
### Note:
It works correctly on browserstack

### Your Environment details:
 
* testcafe version:                   1.9.3, 1.15.1
* node.js version:                    14.15.0
* command-line arguments:  dotenv -- testcafe chrome src/specs/tmp.ts
* browser name and version: Chrome 92
* platform and version:          Windows 10

**Comment by AlexanderMoiseev** [comment]
Hi,

Thank you for your input. We have reproduced the problem and need some time to investigate it, please stay tuned.

**Comment by DmitryKalbeka** [comment]
I have noticed that reason is `screenshots.fullPage:true` of .testcaferc.json config. Without this screenshot works correctly on local browser, and with this sometimes the entire page is screenshotted on BrowserStack
