### ISSUE TITLE
--debug-on-fail not working on 1.15.1

### ISSUE THREAD

**Issue by viktorss89** [DevExpress/testcafe#6442]
### What is the Current behavior?
When running my tests with the flag --debug-on-fail and a test is failing, I can't debug. browser closes.
 
### What is the Expected behavior?
When running my tests with the flag --debug-on-fail and a test is failing, I can debug. I upgraded from 1.10.1 to 1.15.1 and I had no issues at all in 1.10.1
 
### Your Environment details:
 
* testcafe version:                   1.15.1
* node.js version:                    12.16.3
* command-line arguments:  testcafe chrome --debug-on-fail (and then the path to tests)
* browser name and version: Chrome 91.0.4472.114 
* platform and version:          / macOS 10.14.6

**Comment by flora8984461** [comment]
I seem to have the same issue on "testcafe": "^1.15.0-rc.3". But it's working for the example project, I am not sure would it be caused by my project's other settings? ( but it happened like all of a sudden) As a temp, I use t.debug().

**Comment by flora8984461** [comment]
Hi @viktorss89, are you able to figure out? thanks!

**Comment by viktorss89** [comment]
Hey @flora8984461 I upgraded to 1.15.2 and it works again... no idea what was the problem

**Comment by flora8984461** [comment]
> Hey @flora8984461 I upgraded to 1.15.2 and it works again... no idea what was the problem

Thanks, good news you solved it. I have chatted with my teammates it seems only broken for me (I did reinstall the packages and reinstall the node). I will try to upgrade to see, hope it works back for me, thanks!
