### ISSUE TITLE
testcafe v1.15.1 fails with reporter custom args 

### ISSUE THREAD

**Issue by RoniSegal** [DevExpress/testcafe#6444]
I'm trying to use the sealights reporter (https://www.npmjs.com/package/testcafe-reporter-sealights) this reporter requires to provide some extra CLI args to the protractor such as tokenfile
An example command: `testcafe chrome 'path/to/test/file.js' --reporter sealights --sl-tokenfile <path/to/token-file>  --sl-buildsessionidfile <path/to/buildSessionId-file>`
This used to work till the latest version (1.15.1) 
 
### What is the Current behavior?
Tests fails with the following error `error: unknown option '--sl-tokenfile'`
 
### What is the Expected behavior?
Tests should run with the sealights reporter
 

### Your Environment details:
 
* testcafe version:                  1.15.1
* node.js version:                   14.17.4
* command-line arguments:   `testcafe chrome 'path/to/test/file.js' --reporter sealights --sl-tokenfile <path/to/token-file>  --sl-buildsessionidfile <path/to/buildSessionId-file>`
* browser name and version:  chrome
* platform and version:          
* other:

**Comment by AndreyBelym** [comment]
Thank you for your report. This issue should be already fixed in `testcafe@1.15.2-rc.1`. Please try this version in your environment and reopen the issue if it still can be reproduced.
