### ISSUE TITLE
Problems with Okta Sign In redirect after clicking on the button (which should trigger the redirect and store tokens)

### ISSUE THREAD

**Issue by gforepsly** [DevExpress/testcafe#6449]
### What is your Test Scenario?
When I click on the "Log in with SSO" button on our login page, I should be redirected to okta sign in webview form. Maybe the issue is the cross-site origin as it is different when reaching the SSO (okta in our case) domain in comparisson to starting domain.

EDIT:
I managed to get pass this by issuing a SSL certificate and using it to work with HTTPS Testcafe Server.
Another workaround is to use --hostname and force it as a localhost, it works as well. 
Now I have different issue, and that one is Role and Local/Session storage. It doesn't store bearer or other cookies I need. Without that, I'm never in the application.
Is it because of the different domains? 
 
### What is the Current behavior?
Redirect to Okta Sign In URL never happens, it's just blank screen (Works when using --hostname as localhost)
The flow goes like this: https://somedomain/account/logon -> https://somedomain/account/logon-sso -> https://oktapreview.somedomain.com -> https://somedomain/account/logon-sso/callback -> https://somedomain (our home page). After using Role, I'm not signed in to the application.
 
### What is the Expected behavior?
I should be redirected to a Okta login page (our SSO provider).
After signing in, I should be in the application

How to work with Roles and SSO?
 
### What is your web application and your TestCafe test code?
```
fixture`QAB-1972 - [SSO] Log in using Okta SSO servic - Smoke/Acceptance Test`;

test('User can login to the webapp using valid, existing Okta email password using SSO login', async t => {
    await t.navigateTo('https://somedomain/account/logon')
               .click('a[class*=sso-link]')
               .typeText('input[name="username"]', 'SomeRandomEmail')
               .click('input[id*=submit]')
               .typeText('input#okta-signin-password', 'SomePass) //Ping me for credentials
                .click('input[id*=submit]') // After this redirected back to the login page from where I start. I'm missing bearer so I can't 
                                                              enter the app
});
 
```

 
<details>
<summary>Your website URL (or attach your complete example):</summary>
Code attached above.

I did find some errors when I was running in the debug mode! Let me paste it here, maybe it can help:
`hammerhead.js:24501 Error: Uncaught (in promise): AuthSdkError: PKCE requires a modern browser with encryption support running in a secure context.
AuthSdkError: PKCE requires a modern browser with encryption support running in a secure context`

 
```
fixture`QAB-1972 - [SSO] Log in using Okta SSO servic - Smoke/Acceptance Test`;

test('User can login to the webapp using valid, existing Okta email password using SSO login', async t => {
    await t.navigateTo('https://somedomain/account/logon')
               .click('a[class*=sso-link]')
               .typeText('input[name="username"]', 'SomeRandomEmail')
               .click('input[id*=submit]')
               .typeText('input#okta-signin-password', 'SomePass) //Ping me for credentials
                .click('input[id*=submit]') // After this redirected back to the login page from where I start. I'm missing bearer so I can't 
                                                              enter the app
});
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>
We use:
"skipJsErrors": true,
    "skipUncaughtErrors": true
   
i testcaferc.json file

```
{
    "browsers": ["chrome:headless --incognito"],
    "src": "testcafe/regression",
    "reporter": [
        {
            "name": "spec"
        }
    ],
    "skipJsErrors": true,
    "skipUncaughtErrors": true,
    "hostname": "localhost"
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website 'https://somedomain/account/logon' (I can provide details)
3. Click on the Log in with SSO button
4. user should land on 'https://oktapreview.somedomain.com/' page (happens when you try over native Chrome (browser installed on my machine)), works even using Cypress, not happens when using Testcafe.
 
### Your Environment details:
 
* testcafe version:                   1.15.1
* node.js version:                    14.5.1
* command-line arguments:   Using testcaferc.json, so just running 'testcafe'
* browser name and version:  Chrome 92.0.4515.131
* platform and version:          Windows 10 Home
* other:                                   N/A

**Comment by Farfurix** [comment]
@gforepsly 

Hello,

> Now I have different issue, and that one is Role and Local/Session storage. It doesn't store bearer or other cookies I need. Without that, I'm never in the application.

Your usage case is not entirely clear to me. Your attached test contains no Roles. Could you please send us a complete test file with all the necessary information to reproduce the issue on our side? You can use our mailbox: support@devexpress.com.
