### ISSUE TITLE
1.15.1 breaks node arguments (eg. -- --env dev); throws error: unknown option '--env'

### ISSUE THREAD

**Issue by qualityshepherd** [DevExpress/testcafe#6450]
### Steps:
1. given upgrading to Testcafe 1.15.1 from 1.15.0
2. attempt to pass an env var: eg. `testcafe chrome tests/ -- --env dev`

### Results:
error thrown: `error: unknown option '--env'`. 
 
 I've been running tests like this for years... looks like 1.15.1 broke other options as well... 
 
Testcafe 1.15.1; node 14.16.0; chrome 92.0.4515.131

**Comment by qualityshepherd** [comment]
aaaaannnnnndddd... it's fixed in 1.15.2...

**Comment by neekfenwick** [comment]
OK thank you :) yeah I found I could regress with `npm i testcafe@1.15.0` and it worked.. but if it's fixed I'll up to 1.15.2 tomorrow.
