### ISSUE TITLE
Press space key does not work on focused button element

### ISSUE THREAD

**Issue by Nikolaj1010** [DevExpress/testcafe#6452]
**Are you requesting a feature or reporting a bug?**
Bug

**What is the current behavior?**
Pressing the space key on the focused button (the submit one) does not cause any reaction, but it should be the same as clicking on the button. This wrong behavior appears on Chrome and Edge, but it seems that it works on Firefox 90.0.2

**What is the expected behavior?**
Pressing the space key on focused button (the submit one) should triggers click event which should redirect the user to "thank-you.html" test page displaying the text: "Thank you, " + inserted name from the input with label 'your name'

**Steps to reproduce:**

1. Insert some text into the input with label 'your name'
2. Click on the checkbox with text ' I have tried TestCafe'
2. Pressing the tab key three times to focus the 'Submit' button
3. Pressing the space key to simulate click event
4. Page should displays the text "Thank you, [insert name from the first input]" but it does not happen

**Tested page URL:**

http://devexpress.github.io/testcafe/example/

**Your complete test code (or attach your test files):**

 
```
test('Should focus the "Submit" button by pressing tab key from previous element, then pressing space key to simulate click event on the button ', async () => {
    await t
        .typeText(Selector('#developer-name'), 'Nick')
        .click(Selector('#tried-test-cafe'))
        .pressKey('tab tab tab')
        .pressKey('space')
        .expect(Selector('#article-header').innerText).eql('Thank you, Nick!');
});

```

**Your complete test report:**

![testcafeIssueAboutSpaceOnBtn](https://user-images.githubusercontent.com/32637406/128999665-52dc6cb2-80f8-4356-b399-df01a1e11ab0.png)
 
### Your Environment details:
 
* testcafe version:                  `1.15.0`
* node.js version:                    `v14.16.1`
* browser name and version:  `Chrome Version 92.0.4515.131 and Edge Version 92.0.902.67`
* platform and version:           `Windows 10 Enterprise`

**Comment by Nikolaj1010** [comment]
Hello, I created a new issue with up-to-date information after you closed the old issue: https://github.com/DevExpress/testcafe/issues/2066 after a prolonged period of inactivity. This functionality is still needed so I hope that you are going to implement it as you promised here: https://github.com/DevExpress/testcafe/issues/2066#issuecomment-360395058. Thank you for the understanding.

**Comment by VasilyStrelyaev** [comment]
We apologize for the inconvenience. This issue is re-prioritized and marked as a bug, so it won't be closed automatically anymore.

**Comment by chundhau** [comment]
This bug should be expanded to include the `up` and `down` keys as well, both of which can be defined to open a menu. I can provide documentation and a screen video to illustrate the bug, which seems more nuanced than is described here. I can get `space` and `enter`  to open the menu but not shift focus to the first menu item. However, the `up` and `down` keys do not even open the menu.

**Comment by aleks-pro** [comment]
@chundhau, thank you for your feedback. We will take it into account. Also, it would be very helpful if you share a working example that illustrates your usage scenario.

**Comment by onkarb68** [comment]
I can still see this issue popup and space button is not even working with following hack.

await t.setTestSpeed(0.01);
await t.pressKey('tab');
await t.setTestSpeed(0.01);
await t.pressKey('tab');
await t.setTestSpeed(0.01);
await t.pressKey('space space space space space space space')
await t.wait(1000)

Please take it on priority to fix it.

**Comment by Aleksey28** [comment]
Hi @onkarb68

We keep this issue in mind. We will update this thread once we have news. However, I cannot give you a precise date, as any estimate may be misleading.

**Comment by yoksel** [comment]
Pressing buttons with space can be vital for testing accessibility and emulating behaviour of vision impaired people. It would be great if you fix it

**Comment by Aleksey28** [comment]
Hi @yoksel,

Yes, we know about this issue. We don't have any news yet, but we will update this thread once we have any results.

**Comment by daimoonis** [comment]
Hello, the issue with pressKey `down` occurs also at Firefox 105.

testcafe version: 1.18.4
Firefox version: 105.0.3
URL tested: http://devexpress.github.io/testcafe/example/

test('Should select Windows operating system as primary, press down key to select MacOS', async () => {
    await t
        .click('#windows')
        .expect(Selector('#windows').checked).eql(true)
        .expect(Selector('#macos').checked).eql(false)
        .pressKey('down') // on FF 105.0.3 this does not move to next radio item, on FF 104.0.1 it does and passes
        .pressKey('space')
        .expect(Selector('#windows').checked).eql(false)
        .expect(Selector('#macos').checked).eql(true);
});

**Comment by Aleksey28** [comment]
Hi @daimoonis,

It isn't the same issue. However, we already know about this case and [fixed it](https://github.com/DevExpress/testcafe/pull/7325). This fix will be included in the nearest release.

**Comment by abibas9000** [comment]
Hello,

The .pressKey('enter') still doesn't work for Firefox.

Testcafe version: 2.0.0
Firefox version: 107.0.1
Platform: Windows 10 Enterprise

**Comment by Nikolaj1010** [comment]
It seems that this issue is fixed right now
