### ISSUE TITLE
Since 1.15.0 'all' browser is not working

### ISSUE THREAD

**Issue by MacFJA** [DevExpress/testcafe#6456]
### What is the Current behavior?
An error is thrown because the parameters give to the browser provider are incorrect.
```
ERROR Unable to open the "locally-installed:opera" browser due to the following error:

TypeError: Cannot read property 'split' of undefined
    at BrowserProviderPluginHost.openBrowser (/private/tmp/testcafe/node_modules/testcafe/src/browser/provider/built-in/locally-installed.js:7:35)
    at BrowserProvider.openBrowser (/private/tmp/testcafe/node_modules/testcafe/src/browser/provider/index.ts:314:27)
    at BrowserConnection._runBrowser (/private/tmp/testcafe/node_modules/testcafe/src/browser/connection/index.ts:190:33)
    at /private/tmp/testcafe/node_modules/testcafe/src/browser/connection/index.ts:165:37
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
``` 
### What is the Expected behavior?
All browser are opened to run tests, like it was in 1.14.2

### Steps to Reproduce:

```
mkdir /tmp/testcafe
cd /tmp/testcafe
npm install --save-dev testcafe sirv-cli
echo '<h1>Hello world</h1>' > test.html
echo 'fixture("all browser bug").page("http://localhost:5000");test("test", t => {});' > test.js
npx testcafe all test.js --app 'npx sirv .'
```

----

If I run this command it works as expected: `npx testcafe opera test.js --app 'npx sirv .'`

### Your Environment details:
 
```
$ npx envinfo --system --binaries

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 170.70 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.16.1 - /opt/local/bin/node
    Yarn: 1.22.10 - /opt/local/bin/yarn
    npm: 6.14.8 - /opt/local/bin/npm

$ npm info testcafe version
1.15.2
```

### Error root cause

In the version [1.5.0](https://github.com/DevExpress/testcafe/compare/v1.14.2...v1.15.0) the `openBrowser` functions have been changed from having the browserName to having browserOption, but some providers are not compatible with the new call
(files where the functions call have been changed: `src/browser/provider/index.ts`, `src/browser/connection/index.ts`)

From my understanding, `src/browser/provider/built-in/path.js`, `src/browser/provider/built-in/locally-installed.js` are affected by this issue

**Comment by pavsenin** [comment]
Hello,
Thank you for pointing out this issue.
I have reproduced it locally.
