### ISSUE TITLE
Debug underlying code during test

### ISSUE THREAD

**Issue by NathanHazout** [DevExpress/testcafe#6457]
Following these instructions (https://testcafe.io/documentation/402799/recipes/debugging/webstorm) allows me to debug the test itself (actually even without those instructions, it worked out of the box in webstorm).

However, what I want to debug is my website, while it's being tested by testcafe. 

When not running in testcafe, I am able to debug my website (a react app) by using webstorm's "javascript debug" configuration. It opens a new window and connects the debugger.

How do I make testcafe start my app in debug mode? Or make testcafe use the chrome instance already opened by the debugger?

**Comment by AlexKamaev** [comment]
It depends on how you run your website. TestCafe has the following options:
[--app](https://testcafe.io/documentation/402639/reference/command-line-interface#-a-command---app-command) - executes a specified shell command before tests start;
[--app-init-delay](https://testcafe.io/documentation/402639/reference/command-line-interface#--app-init-delay-ms) - specifies the time (in milliseconds) allowed for initialization of an application launched with the --app option;



If you run your website with `node` command, you can just add the `--inspect-brk` flag:
```testcafe chrome my-tests --app "node --inspect-brk server.js" --app-init-delay 4000```

You can also do not use these flags and just run your website and TestCafe in different terminal tabs.

**Comment by NathanHazout** [comment]
I'm not sure I understand ... I see how I can start my app in debug mode either directly or through the `-app` param.  
However, when webstorm wants to do a javascript (client side) debug, it opens a new chrome window. 
So both TestCafe and Webstorm open their own chrome window. That's the underlying issue.

**Comment by miherlosev** [comment]
> However, what I want to debug is my website, while it's being tested by testcafe.
You can do it using the `chrome --auto-open-devtools-for-tabs` Chrome flag.

```js
testcafe "chrome --auto-open-devtools-for-tabs" tests
```

Chrome will start with the opened DevTools, and you can debug JavaScript using it (see the instruction [here](https://developer.chrome.com/docs/devtools/javascript/)).
