### ISSUE TITLE
Testcafe fails to load a javascript and the network fails with 500 error on newer versions

### ISSUE THREAD

**Issue by jeevananthank** [DevExpress/testcafe#6458]
### What is your Test Scenario?
Creating the issue in connection to this question in [stackoverflow](https://stackoverflow.com/questions/68710342/tests-started-failing-with-new-version-of-testcafe-where-a-http-call-to-load-a-s).
The test scenario is just clicking on a page that loads several javascript files with http calls and the one of js file of size 6.6. mb fails with an error code 500 and the application fails to load.
 
### What is the Current behavior?
I have testcafe tests working fine until version `1.14.0` and with the upgrade of the version to the latest (> 1.14.0), the tests have started to fail and the from console/network calls of the browser, I could see that one of the call to get the js file, has failed with 500 Internal server error and a blank white screen was loaded.
 
### What is the Expected behavior?
The tests should be running as the tests run in `1.14.0`
 
### What is your web application and your TestCafe test code?
1. Build the application local following the procedures as described [here](https://github.com/Altinn/altinn-studio/tree/master/src/studio#installing).

2. Your complete test code:
[Test code](https://gist.github.com/jeevananthank/3abf7eff48f85d57a9f672950e86edc7)

### Steps to Reproduce:
1. Start the application as described and create an user with password and replace in the script.
3. Execute this command : `testcafe 'chrome' test.js --assertion-timeout 10000 -u -e -q`
4. See the error in console that the loading of the script has failed with the latest test cafe versions.
 
### Your Environment details:
 
* testcafe version:                   >1.14.0
* node.js version:                    v14.15.0
* command-line arguments:  testcafe chrome -e test.js
* browser name and version: Chrome 92
* platform and version:          Windows

**Comment by Dmitry-Ostashev** [comment]
Thank you for your report. I reproduced the issue with TestCafe v1.15.0. However, the test is passed successfully with v1.15.2. So, try to update TestCafe to the latest version.

**Comment by jeevananthank** [comment]
not always the tests pass and especially in CI with the updated the testcafe version, the test just hangs and nothing proceeds further. Tried to test the same in a windows machine locally, and i observe the issue described, the application does not load.

**Comment by Dmitry-Ostashev** [comment]
I ran the test above with two TestCafe versions:

1) TestCafe v1.15.1 - failed:
![image](https://user-images.githubusercontent.com/24777868/130029221-4d015717-55cc-43cb-bebb-94511ef1eec4.png)
![image](https://user-images.githubusercontent.com/24777868/130029684-fe7fbefd-1c77-47a4-88af-c4273e30b761.png)

2) TestCafe latest v1.15.3-rc.1 - passed:
![image](https://user-images.githubusercontent.com/24777868/130028670-891c8781-b1e5-48c6-af41-e7a42cab1323.png)

In the first case, the application is launched, but the test fails after the `navigateTo` action. With the newest TestCafe version, it works properly on my side. Could you clarify if you see the same error as in the first screenshot? If the problem looks different, please attach a screenshot or capture a video to illustrate it.

**Comment by jeevananthank** [comment]
Tests are working fine with `1.15.3`. Will post a comment if the issue is experience again. thanks for the help.

**Comment by Chramox** [comment]
**What is the Current behavior?**
I have the same problem as mentioned here with testcafe in version 1.19.0, did the upgrade to the latest version 2.2.0 and the problem continues.  The .js that can´t be loaded is this:
` <script src="https://test.frontier7.com/chunk/chunk-BZA67JWP.js"></script>`

Put the script in a new React project and Testcafe also gave the same error.

![image](https://user-images.githubusercontent.com/59344490/212352504-f8095818-14a7-4db0-aab5-b07d863332c2.png)


**What is the Expected behavior?**
The URL put in .page() should redirect to Login but instead I see the behavior describer here. Also tried to do Login first and then navigate to the project and the behavior is the same.


**What is your web application and your TestCafe test code?**
```
import { Selector } from "testcafe";
fixture('CreateProject')
  .page('https://test.frontier7.com/project/63adf96c785a40eb5d88a835/build')

test('log-in and do stuff', async t => {
  await t.wait(10000);
  const email_input = Selector('input[type="text"]');
  const password_input = Selector('input[type="password"]');
  const submit = Selector('button[type=submit]');
  const email = "email_password";
  const password = "user_password";

  await t.typeText(email_input, email, { replace: true })
  .typeText(password_input, password, { replace: true })
  .click(submit);
 
  await t.wait(10000000); //just to inspect browser console
});
```

**Steps to Reproduce:**
Run the test

**Environment details:**
testcafe version: >2.2.0
node.js version: v18.13.0
command-line arguments: testcafe chrome -e test.js
browser name and version: Chrome 108
platform and version: Windows

**Comment by Artem-Babich** [comment]
Hi @Chramox 
I reproduced the issue and created a separate github issue for it: [7461](https://github.com/DevExpress/testcafe/issues/7461)
Let's continue our discussion there.
