### ISSUE TITLE
[TypeScript] Upgrade TypeScript version

### ISSUE THREAD

**Issue by antochiw-monarch** [DevExpress/testcafe#6473]
Current TypeScript version being used is **3.3.3**, which is 3 years old. A lot of cool new features has been released since then, but are not being leveraged by TestCafe. This could be a simple change that has greater impact to users, like faster compilation or broader support on newest features like updates on Promises API.

### What is your Test Scenario?
Test code that includes fairly new syntax fails if using, for example, `Promise.allSettled([])`. The following error is being thrown:
```
Property 'allSettled' does not exist on type 'PromiseConstructor'
```

### What are you suggesting?
This particular property (`allSettled`) was introduced with **TypeScript 3.8.0**, almost a year ago. Upgrading to the latest version of TypeScript would fix this particular issue, along with others. For example, it may fix: https://github.com/DevExpress/testcafe/issues/6472

Upgrading a library is not always an easy task, but in some cases, when there are not breaking changes it could be done fairly quick.

### What alternatives have you considered?
If upgrading to the latest version of TypeScript represents a challenge due to breaking changes, then consider upgrading to another more recent version. You would still get some of the benefits, like better performance.

### Additional context
Current latest stable version of TypeScript is **v.4.3.5**. A full list of available versions is available on [NPM](https://www.npmjs.com/package/typescript/v/3.8.2).

**Comment by Farfurix** [comment]
@antochiw-monarch 

Hello,

We plan to update our TypeScript dependency version in the next major release (v2.0.0). Now you can specify a custom version of TypeScript using [Compiler options](https://testcafe.io/documentation/402824/guides/concepts/typescript-and-coffeescript#customize-compiler-options).

**Comment by Hagendorn** [comment]
Hi @Farfurix,

do you have a timeline for the 2.0 release? I am maintaining the `@testing-library/testcafe` project and I am running in some problems to upgrade `@testing-library/dom` because of `@testing-library/*` is using TypeScript >= 4.x but `testcafe` sill using TypeScript 3.x.

Thanks

**Comment by Artem-Babich** [comment]
Hi @Hagendorn,

I'm afraid that we cannot give you any ETA at present. We will update this thread once we have news.

**Comment by miherlosev** [comment]
https://github.com/DevExpress/testcafe/pull/7103
