### ISSUE TITLE
Browser hangs after clicking on a link which downloads a pdf file

### ISSUE THREAD

**Issue by aarti315** [DevExpress/testcafe#6479]
I have to verify usermenu of our application hence I am expected to click on all links present under usermenu example 'Terms of User', 'Security' and 'User Guide' and verify the behavior. Script for all links v=works fine except for 'User Guide' link. 'User Guide' link points to a PDF present on application. If we click on 'User Guide' it either opens PDF in browser or downloads the file in new BLANK window.

Due to BLANK window browser becomes hang and it doesn't go to the next testcase and at the end, we get an error as 'ERROR The Chrome 92.0.4515.131 / Windows 10 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.'

### What is your Test Scenario?
To test the behavior of a link pointing to a PDF file. 
 
### What is the Current behavior?
Once clicked on the link it opens a new BLANK chrome window and downloads the file. I am not able to close this new BLANK window and test run fails. It does not run the next testcase.
 
### What is the Expected behavior?
Once clicked on the link it should download the file (in new/existing chrome window) and it should move on to the net test case.
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by aarti315** [comment]
I can not share code sample.

WebPage to test should have a hyper link and make it point to a file. We need to verify if user has access to the file. In our application we have a user guide link which we need to test. We need to make sure link is not broken and user has access to the link

**Comment by Farfurix** [comment]
@aarti315 

Hello,

We need to examine your particular usage scenario. We haven’t come across this before and we cannot say anything about it. This issue doesn't contain any reproducible example and it looks like a duplicate of https://github.com/DevExpress/testcafe/issues/6493. So, I'll close it.
