### ISSUE TITLE
A click on the "Log in" button (Keycloak) does not produce any result

### ISSUE THREAD

**Issue by k08as** [DevExpress/testcafe#6485]
### What is your Test Scenario?
Trying to login via Keycloak
 
### What is the Current behavior?
Fails to redirect to Keycloak login page once you click on [Log in] button
 
### What is the Expected behavior?
Keycloak login page opens
 
### What is your web application and your TestCafe test code?
Simplified version of the code below (removed Role functionality for simplicity purpose; Cookies don't affect this either)
 
```js
fixture `Login`
    .beforeEach(async t => {
        await t.maximizeWindow();
    });

test('Login from header with Quandoo account', async t => {
    await t
        .navigateTo('https://www.quandoo.de/en')
        .click('[data-qa="header-login-btn"]')
        .click('[data-qa="login-btn"]')
});
```

### Other notes:
Tried with and without `--skip-js-errors` & `--disable-page-caching` flags + preserving URL. Nothing worked
Often reproducible in Safari as well

### Your Environment details:
 
* testcafe version:  1.15.2 (reproducible on the older versions as well)
* node.js version:  16 (reproducible on the older versions as well)
* command-line arguments:  testcafe chrome <path/test_name.js> --disable-page-caching --skip-js-errors (tried without the flags as well)
* browser name and version: both Chrome / FF headless & full versions (incl. the latest versions)
* platform and version: ran it on macOS Catalina and BigSur at least

### Similar Issues:
[Keycloak issue](https://github.com/DevExpress/testcafe/issues/5684)

**Comment by Farfurix** [comment]
@k08as 

Hello,

I reproduced the issue with macOS Big Sur / Windows 10 and Chrome 92. We need time to research it. Please bear with us.
