### ISSUE TITLE
Support filtering of tests with multiple test names

### ISSUE THREAD

**Issue by vinayvennela** [DevExpress/testcafe#6492]
### Are you requesting a feature or reporting a bug?
Feature

### What is your Test Scenario?

Would like to support multiple -t filters like
testcafe ie tests/sample-fixture.js -t "Click a label" -t "Click another label"

### What is the Current behavior?

Currently, when the above command is run only the last test in the chaining -t will run. i.e. "Click another label" test will only be run

### What is the Expected behavior?

Expected that both tests run

### How would you reproduce the current behavior (if this is a bug)?

Just add any two tests and try to filter more than one test using -t filter

#### Provide the test code and the tested page URL (if applicable)

 
Your website URL (or attach your complete example):

Your complete test code (or attach your test files)

```js

```
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by Farfurix** [comment]
@vinayvennela 

Hello,

You need to use [the `--test-grep` option](https://testcafe.io/documentation/402639/reference/command-line-interface#-t-pattern---test-grep-pattern). For example:
```js
fixture `Fixture`
    .page('https://google.com');

test('Test 1', async t => {
    await t.expect(true).ok();
});

test('Test 2', async t => {
    await t.expect(true).ok();
});

test('Test 3', async t => {
    await t.expect(true).ok();
});
```
Result:
```
>testcafe chrome test.js --test-grep "Test 2|3"
 Running tests in:
 - Chrome 92.0.4515.159 / Windows 10

 Fixture
 √ Test 2
 √ Test 3


 2 passed (3s)
```

For more complex cases, you can use [`Runner API`](https://testcafe.io/documentation/402641/reference/testcafe-api/runner). You can use the [`Runner.filter` method](https://testcafe.io/documentation/402657/reference/testcafe-api/runner/filter) to customize your filter.
