### ISSUE TITLE
Browser hangs if server response is not 200

### ISSUE THREAD

**Issue by aarti315** [DevExpress/testcafe#6493]
I have approx 100 testcases running on daily basis but it gets stuck at some specific testcase and after 1 hour it gets timeout in CI as per max allotted time for build. As I wanted to fix this issue but could not figure our any solution.

I have seen similar behavior when server response is not 200.

### What is your Test Scenario?
Verifying if user has access to a file stored on web app.
 
### What is the Current behavior?
Script works fine if user has access and file gets downloaded if we try to access file path. If user does not have access to the file path then browser shows 404/403 error. After this error no subsequent test will get execute and our test pipeline gets timedout.
 
### What is the Expected behavior?
If user has access to the file then test should pass and if user does not have access then test should fail and in both cases at the end of the test next test case execution should begin
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```
import { RequestLogger, Selector } from 'testcafe';
const Helper = require('../Helper/CommonFunctions.js');
const url = 'https://************************/documentrepository/Workshar/UserGuide_v5.1.pdf';


const requestLoggerForFile = RequestLogger({ url, method: 'GET' }, {
    logResponseHeaders: true,
    logResponseBody: false
    //stringifyResponseBody: true
});

fixture`TeamLink US - Permission Report`
    .httpAuth({
        username: Helper.Config.userId,
        password: Helper.Config.password
    })
    .beforeEach(async t => {
        await t.useRole(Helper.User.Oneplacetest1)
    })
    .requestHooks(requestLoggerForFile);

test('TeamLink US - Create Permission Report', async t => {
    await t
        .navigateTo(url)
    console.log(requestLoggerForFile.requests.length);
    console.log(requestLoggerForFile.requests[0].response.statusCode);
    console.log(requestLoggerForFile.requests[0].response.headers['content-type']);
    await t.expect(requestLoggerForFile.requests[0].response.headers['content-type']).eql('application/pdf')

});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

</details>

<details>
<summary>Your complete test report:</summary>

</details>

<details>
<summary>Screenshots:</summary>

</details>

### Steps to Reproduce:

1. Use a web app and try to access file url directly
### Your Environment details:
 
* testcafe version:                   1.10.1
* node.js version:                    14.15.5
* command-line arguments:  testcafe chrome test.js
* browser name and version: chrome
* platform and version:          windows
* other:                                   
![Uploading CaptureError.PNG…]()

**Comment by aarti315** [comment]
![CaptureError](https://user-images.githubusercontent.com/89137872/130606183-b8760d12-9bc6-4aea-abce-ddbba83f434f.PNG)
Error snapshot when user does not have access to file. In case of error test ends with message 'ERROR The Chrome 92.0.4515.159 / Windows 10 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.'

**Comment by Farfurix** [comment]
@aarti315 

Hello,

Your TestCafe version is outdated. Please update it to the latest version (`v1.15.3`) and check the result.
I opened a public PDF file and didn't see any browser hangs. We need some example to reproduce this behavior. Please share it with us.

**Comment by aarti315** [comment]
There are 2 scenario:

Scenario 1: User has access  to the file
TestCafe behavior: Script runs fine. File is downloaded when user hits the URL. RequestLogger object identifies download PDF file(Test Passed). TestCafe continues executing further testcases.

Scenario 2: User does not have  access  to the file path
TestCafe behavior: When user hits the URL browser shows 404 not found error. Browser is hanged at this test hence next testcases in Pipeline does not gets executed. Browser gets disconnected after some time. (Test neither passed not failed) Below errr is shown on cmd screen
Error message: 'ERROR The Chrome 92.0.4515.159 / Windows 10 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.'

**Comment by aarti315** [comment]
Hi Victoria, thanks for your time for the investigation. Sorry, my bad as I forgot to mention that URL is not the actual URL instead I just put '*' as a placeholder. I Will get back with actual URL and script where I am facing issue else I will try to prepare a demo to replicate the issue.

**Comment by aarti315** [comment]
[TestCafeJSScript.txt](https://github.com/DevExpress/testcafe/files/7093220/TestCafeJSScript.txt)

Hi Viktoria,

You can try the attached script either on TestCafe Studio or CMD.
The file contains 3 tests out of which Test number 2 is having issues.

Kindly note as mentioned in the issue description browser gets disconnected in case of errors like: 500/502/403/404 etc

**Comment by pavsenin** [comment]
Hello aarti315,

Thank you for providing us with a code example.
I am able to reproduce the issue with it on my side.

**Comment by aarti315** [comment]
Hi, Is there any timeline decided to fix the issue?

**Comment by dcsaszar** [comment]
This still affects us.
* We've had the issue of tests hanging indefinitely in > 50% of test runs in all Sauce-Labs-based tests (IE11, Edge 18 and Mobile Safari). All local browser runs were fine. So the issue may potentially be triggered by the addition of another proxy (Sauce Connect).
* After some digging we came across this issue and found that the hanging tests always occurred when testing a URL which responds with a 404 status code: We test an SPA with catch-all fallbacks, i.e. some 404 URLs behave like the canonical URL counterpart with a 200 OK. We also test the 404 page itself. I.e. we're testing something comparable to scenario 2 in https://github.com/DevExpress/testcafe/issues/6493#issuecomment-905405690.
* After quarantining the affected tests on Sauce Labs the hanging runs are gone.
* Note that we also have tests for URLs with 301 responses. These are fine. Also the TestCafe heartbeat is running all the time in the 404 cases. So maybe the issue title can be changed from "Browser hangs if server response is not 200" to "TestCafe hangs if server response is 404"?

**Comment by AlexKamaev** [comment]
@dcsaszar Thank you for the information. We agree that the issue can be caused by the use of SauceLabs. If the quarantine mode works in your case, please use it until the issue is fixed.
It also seems that test cases from other users in the thread are not available anymore, so it's better to [open a separate issue](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&template=bug_report.yaml), prepare a [very simple example](https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue), and share a detailed instruction on how to reproduce the issue.
