### ISSUE TITLE
Second scenario tests not triggering after completing first scenario in Windows

### ISSUE THREAD

**Issue by RanjitAwati** [DevExpress/testcafe#6495]
Hi all,
I'm getting error in hooks.js for the subsequent scenarios after completing first one. Getting error in Before function()
Browser is launches and freezes
Here is my hooks.js:

const fs = require('fs')
const createTestCafe = require('testcafe')
const testControllerHolder = require('../support/testControllerHolder')
const { AfterAll, setDefaultTimeout, Before, After, Status } = require('cucumber')
const errorHandling = require('../support/errorHandling')
const TIMEOUT = 2 * 30000
let isTestCafeError = false
let attachScreenshotToReport = null
let cafeRunner = null
let n = 0

function createTestFile () {
  fs.writeFileSync('test.js',
    'import errorHandling from "./features/support/errorHandling.js";\n' +
        'import testControllerHolder from "./features/support/testControllerHolder.js";\n\n' +
        'fixture("fixture")\n' +
        'test\n' +
        '("test", testControllerHolder.capture)')
}
function runTest (iteration, browser) {
  createTestCafe('localhost', 1338 + iteration, 1339 + iteration)
    .then(function (tc) {
      cafeRunner = tc
      const runner = tc.createRunner()
      return runner
        .src('./test.js')
        .screenshots('reports/screenshots/', true)
        .browsers(browser)
        .run()
        .catch(function (error) {
          console.error(error)
        })
    })
    .then(function (report) {
    })
}

setDefaultTimeout(TIMEOUT)

Before(function () {
  runTest(n, this.setBrowser())
  createTestFile()
  n += 2
  return this.waitForTestController.then(function (testController) {
    return testController.maximizeWindow()
    //return testController.resizeWindow(1920, 1080)
  })
})
After(function () {
  fs.unlinkSync('test.js')
  testControllerHolder.free()
})
After(async function (testCase) {
  const world = this
  if (testCase.result.status === Status.FAILED) {
    isTestCafeError = true
    attachScreenshotToReport = world.attachScreenshotToReport
    errorHandling.addErrorToController()
    await errorHandling.ifErrorTakeScreenshot(testController)
  }
  cafeRunner.close()
})
AfterAll(function () {
  let intervalId = null
  function waitForTestCafe () {
    intervalId = setInterval(checkLastResponse, 500)
  }
  function checkLastResponse () {
   // if (testController.testRun.lastDriverStatusResponse === 'test-done-confirmation') {
      cafeRunner.close()
      process.exit()
      clearInterval(intervalId)
   // }
  }
  waitForTestCafe()
})
const getIsTestCafeError = function () {
  return isTestCafeError
}
const getAttachScreenshotToReport = function (path) {
  return attachScreenshotToReport(path)
}
exports.getIsTestCafeError = getIsTestCafeError
exports.getAttachScreenshotToReport = getAttachScreenshotToReport

![TC](https://user-images.githubusercontent.com/47976619/130734322-bd03d066-cb31-4cd9-84c2-9090be097080.png)

**Comment by pavsenin** [comment]
Hello,

When I tried to reproduce the issue, I got the following error:

Error: Cannot find module '../support/testControllerHolder'

Could you please share a complete project archive with all required files so that we can reproduce this issue on our side?

**Comment by pavsenin** [comment]
Hello,
Would you please change your example to reproduce the issue without cucumber?
If the issue is reproducible with testcafe only, we will research it. If not, it's better to contact the cucumber support team.

**Comment by RanjitAwati** [comment]
Hi @pavsenin I tried without cucumber and it worked so after researching testcafe is not supporting the latest version of cucumber which is @cucumber/cucumber 
can you please raise this and get the support to be fixed ?

**Comment by pavsenin** [comment]
Hello RanjitAwati,

Please refer to [this](#6514) thread for more information on the latest cucumber version support.

**Comment by GOPIRAJU11** [comment]
For me also second senario fails any solution??

**Comment by GOPIRAJU11** [comment]
> Hi all, I'm getting error in hooks.js for the subsequent scenarios after completing first one. Getting error in Before function() Browser is launches and freezes Here is my hooks.js:
> 
> const fs = require('fs') const createTestCafe = require('testcafe') const testControllerHolder = require('../support/testControllerHolder') const { AfterAll, setDefaultTimeout, Before, After, Status } = require('cucumber') const errorHandling = require('../support/errorHandling') const TIMEOUT = 2 * 30000 let isTestCafeError = false let attachScreenshotToReport = null let cafeRunner = null let n = 0
> 
> function createTestFile () { fs.writeFileSync('test.js', 'import errorHandling from "./features/support/errorHandling.js";\n' + 'import testControllerHolder from "./features/support/testControllerHolder.js";\n\n' + 'fixture("fixture")\n' + 'test\n' + '("test", testControllerHolder.capture)') } function runTest (iteration, browser) { createTestCafe('localhost', 1338 + iteration, 1339 + iteration) .then(function (tc) { cafeRunner = tc const runner = tc.createRunner() return runner .src('./test.js') .screenshots('reports/screenshots/', true) .browsers(browser) .run() .catch(function (error) { console.error(error) }) }) .then(function (report) { }) }
> 
> setDefaultTimeout(TIMEOUT)
> 
> Before(function () { runTest(n, this.setBrowser()) createTestFile() n += 2 return this.waitForTestController.then(function (testController) { return testController.maximizeWindow() //return testController.resizeWindow(1920, 1080) }) }) After(function () { fs.unlinkSync('test.js') testControllerHolder.free() }) After(async function (testCase) { const world = this if (testCase.result.status === Status.FAILED) { isTestCafeError = true attachScreenshotToReport = world.attachScreenshotToReport errorHandling.addErrorToController() await errorHandling.ifErrorTakeScreenshot(testController) } cafeRunner.close() }) AfterAll(function () { let intervalId = null function waitForTestCafe () { intervalId = setInterval(checkLastResponse, 500) } function checkLastResponse () { // if (testController.testRun.lastDriverStatusResponse === 'test-done-confirmation') { cafeRunner.close() process.exit() clearInterval(intervalId) // } } waitForTestCafe() }) const getIsTestCafeError = function () { return isTestCafeError } const getAttachScreenshotToReport = function (path) { return attachScreenshotToReport(path) } exports.getIsTestCafeError = getIsTestCafeError exports.getAttachScreenshotToReport = getAttachScreenshotToReport
> 
> ![TC](https://user-images.githubusercontent.com/47976619/130734322-bd03d066-cb31-4cd9-84c2-9090be097080.png)
@RanjitAwati did u find solution?
