### ISSUE TITLE
Make screenshots paths more user-friendly

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#650]
We've discussed this with @superroma and here is the idea how we can transform screenshot paths:
`YYYY-MM-DD_HH-MM-SS/{user-agent}/{1,2,3,...}.jpg`

For errors:
`YYYY-MM-DD_HH-MM-SS/{user-agent}/errors/{1,2,3,...}.jpg`

Date is the start time of the test task. Screenshots are sequentially numbered within directories.
BTW, currently we manually escape user agent in path, I suggest to use https://www.npmjs.com/package/sanitize-filename package for this purpose.

**Comment by inikulin** [comment]
`{task-start-date}/{user-agent}/test{num}/{1,2,3,...}.jpg`

**Comment by inikulin** [comment]
What's breaking about it?

**Comment by helen-dikareva** [comment]
It's can break existent tests. Especially it concerns Legacy api tests.

**Comment by inikulin** [comment]
http://semver.org Guys, please read. Is screenshot path is a part of API?
