### ISSUE TITLE
Skip tests through filter option in testcaferc.json file

### ISSUE THREAD

**Issue by jbradenclickfunnels** [DevExpress/testcafe#6501]
### What is your Test Scenario?

I want to be able to run all tests EXCEPT with specific values set in the testcaferc.json file.

### What are you suggesting?

Right now, you can do this in the runner and add test.skip in the test, but there doesn't seem to be a documented way to skip tests with specific values in the testcaferc.json file.

### What alternatives have you considered?

Marking each individual test as skip. This is annoying and time consuming and dynamic.

**Comment by viktoria2506** [comment]
Thanks for your interest in our TestCafe product. We will consider adding this feature.

**Comment by pavsenin** [comment]
We discussed your use case with the team and decided not to implement.
You can skip tests using the [testGrep](https://testcafe.io/documentation/402638/reference/configuration-file#filtertestgrep) and [fixtureGrep](https://testcafe.io/documentation/402638/reference/configuration-file#filterfixturegrep) options.
For example, you can use the following pattern to exclude all tests with names that contain the 'MyTest' string:

```
{
  "filter": {
    "testGrep": "^((?!MyTest).)*$"
    }
}
```

For more complex cases, you can use a programmatic API - https://testcafe.io/documentation/402657/reference/testcafe-api/runner/filter#header.
Also, we are working on the capability to use a JavaScript configuration file that would allow one to specify test filter conditions in the configuration file.

**Comment by jbradenclickfunnels** [comment]
Thanks for the better understanding. It may be worth adding to the documentation that you can use these filters for tests NOT to run. The way all the documentation is written regarding testGrep and runner is for tests that you WANT to run.

**Comment by pavsenin** [comment]
Thank you for your inquiry.
We'll consider at adding this case to our documentation.
