### ISSUE TITLE
TypeError: o.add is not a function - hammerhead.js

### ISSUE THREAD

**Issue by avilano** [DevExpress/testcafe#6502]
### What is your Test Scenario?
Test logs in with a specific user then clicks a button to navigate to a different page of the react app
 
### What is the Current behavior?
While manually clicking the same button results in the react app rendering the correct page, running (even on slow speed) the same behavior in testcafe will instantly break the web app as it throws a console error
 
### What is the Expected behavior?
Web app renders react page successfully so it can do asserts/expects correctly
 
### What is your web application and your TestCafe test code?

<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```
fixture `Institutional User Login`
  .page(homeUrl)
  .httpAuth({
    username: devUsername,
    password: devPassword,
  })
  .beforeEach(async t => {
    await t.maximizeWindow()
  })

test(`Institutional User ${eduEmail} can navigate to Dashboard Page`, async t => {
  await t.setNativeDialogHandler(() => true).useRole(eduRole)
  await registerInstitutionalPage.validateDashboardPage()
})
```

```
async validateDashboardPage() {
    await t
      .click(this.myDashboard, {timeout: 1000 })
      .expect(this.insightsHeader.exists).ok("Inquiry header is missing", { timeout: 1000 })
  } 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```
Running tests in:
 - Chrome 92.0.4515.159 / macOS 10.15.7

 Institutional User Login

----
Chrome 92.0.4515.159 / macOS 10.15.7
DEBUGGER PAUSE ON FAILED TEST:
AssertionError: Inquiry header is missing: expected false to be truthy

Browser: Chrome 92.0.4515.159 / macOS 10.15.7

81 |
82 |  async validateDashboardPage() {
83 |    await t
84 |      .click(this.myDashboard, {timeout: 1000 })
85 |      .wait(2000)
> 86 |      .expect(this.insightsHeader.exists).ok("Inquiry header is missing", { timeout: 1000 })


at <anonymous> (/Users/avilano/Documents/GitHub/Bold/qa/pages/register-institutional-page.js:86:43)
at asyncGeneratorStep (/Users/avilano/Documents/GitHub/Bold/qa/pages/register-institutional-page.js:3:167)
at _next (/Users/avilano/Documents/GitHub/Bold/qa/pages/register-institutional-page.js:3:505)
at <anonymous> (/Users/avilano/Documents/GitHub/Bold/qa/pages/register-institutional-page.js:3:670)
at <anonymous> (/Users/avilano/Documents/GitHub/Bold/qa/pages/register-institutional-page.js:3:411)
at RegisterInstitutionalPage.validateDashboardPage (/Users/avilano/Documents/GitHub/Bold/qa/pages/register-institutional-page.js:82:33)
at <anonymous> (/Users/avilano/Documents/GitHub/Bold/qa/fixtures/institutional-login-test.js:45:35)
at asyncGeneratorStep (/Users/avilano/Documents/GitHub/Bold/qa/fixtures/institutional-login-test.js:6:299)
at _next (/Users/avilano/Documents/GitHub/Bold/qa/fixtures/institutional-login-test.js:6:637)
```
</details>

<details>
<summary>Screenshots:</summary>

<img width="1590" alt="Screen Shot 2021-08-26 at 5 18 33 PM" src="https://user-images.githubusercontent.com/20048240/131043446-dce38052-0964-4287-8db8-50bb9e7ab8c5.png">

</details>

### Steps to Reproduce:

1. Run testcafe
 
### Your Environment details:
 
* testcafe version:                   1.15.2
* node.js version:                    v16.7.0
* command-line arguments:  "testcafe 'chrome' fixtures/institutional* --reporter xunit:report/xunit/test_report_institutional.xml -q"
* browser name and version: Chrome 92.0.4515.159
* platform and version:          macOS 10.15.7
* other:

**Comment by Farfurix** [comment]
@avilano 

We need to reproduce this issue on our side. I don't think we will be able to determine the cause of the issue with the help of a HAR file only. Please share [the information we requested](https://github.com/DevExpress/testcafe/issues/6502#issuecomment-907196113) previously.

**Comment by avilano** [comment]
Hello, I will send details to the email provided support@devexpress.com to provide the requested information
