### ISSUE TITLE
[docs] Describe execution timeouts

### ISSUE THREAD

**Issue by Aleksey28** [DevExpress/testcafe#6503]
Issue: https://github.com/DevExpress/testcafe/issues/6096
PR: https://github.com/DevExpress/testcafe/pull/6441
Discussion: https://teams.microsoft.com/l/message/19:7e845d3e5e324502abae3417a2ac8c7c@thread.skype/1628000541062?tenantId=e4d60396-9352-4ae8-b84c-e69244584fa4&groupId=c3abb0f3-231c-4d87-b5a3-44925dc1d075&parentMessageId=1628000541062&teamName=TestCafe&channelName=Framework%20(Open%20source)&createdTime=1628000541062

Describe the possibility to set timeout via the configuration file and the CLI. There are two timeouts:
-testExecutionTimeout - timeout for each test
-runExecutionTimeout - timeout for all process

##### CLI
```
testcafe chrome my-tests --test-execution-timeout 180000
testcafe chrome my-tests --run-execution-timeout 180000
```

##### Configuration file
```json
{
    "testExecutionTimeout": 180000,
    "runExecutionTimeout": 180000
}
```

**Comment by miherlosev** [comment]
Implemented.
