### ISSUE TITLE
Exception when clicking on element inside iFrame

### ISSUE THREAD

**Issue by vicus-hopin** [DevExpress/testcafe#6505]
### What is your Test Scenario?
Accept cookies dialog in an iFrame element and do actions in the main windows afterwards.
 
### What is the Current behavior?
TestCafe throws exception:
```
Uncaught object "[object Object]" was thrown. Throw Error instead.
```
 
### What is the Expected behavior?
No exceptions
 
### What is your web application and your TestCafe test code?
See below
 
<details>
<summary>Your website URL (or attach your complete example):</summary>

https://hopin.com/explore

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 const input = Selector('input.qa-id-search-events-input');
await t.navigateTo('https://hopin.com/explore');
await t.switchToIframe(Selector('iframe[name="mtm-frame-prompt"]')).click(Selector('button').nth(2));
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:
1. Go to my website https://hopin.com/explore
2. Wait for cookies dialog to appear in iFrame
3. Switch to iFrame
4. Click Yes button
 
### Your Environment details:
 
* testcafe version:                   1.15.1
* node.js version:                   14.15.0
* command-line arguments:  testcafe 'chrome:emulation:width=1366;height=800; --test-type --disable-accelerated-video --disable-accelerated-plugins --disable-accelerated-layers --disable-accelerated-compositing --disable-accelerated-2d-canvas --disable-web-security --allow-running-insecure-content --dev --allow-insecure-localhost --ignore-certificate-errors --disable-dev-shm-usage --disable-gpu --autoplay-policy=no-user-gesture-required --disable-infobars --use-fake-ui-for-media-stream --allow-running-insecure-content 
* browser name and version: Chrome 92
* platform and version:          macOS

**Comment by Farfurix** [comment]
@vicus-hopin 

Hello,

I reproduced this issue with Windows 10 and Chrome 92. We will update this thread once we have any news.
