### ISSUE TITLE
After navigation the website shows blank page for tests.

### ISSUE THREAD

**Issue by AnushaErrabelli** [DevExpress/testcafe#6506]
### What is your Test Scenario?
I would like to automate this website https://wordpress.com/ . 
 
### What is the Current behavior?
I have automated the  tests as below it's working good until login it's showing blank page after login. 

 
### What is the Expected behavior?
It should click myprofile button and enter firstname, lastname in myprofile section.
 
### What is your web application and your TestCafe test code?
fixture `Wordpress website tests`.page(`https://wordpress.com`);

test("Login and My profile page verification", async (t: TestController) => {
   //Login tests
    await t.click("a[title='Log In']");
    await t.typeText(t#usernameOrEmail, gifocit125drlatviacom );
    await t.click(".form-button");
    await t.typeText("#password" gifocit125drlatviacom);
    await t.click(".formatted-header"); 
    //my profile tests
    await t.click(".gravatar")
    await t.typeText(#first_name, firstName)
    await t.typeText(#last_name, lastName)
    });
    

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:   1.15.3                
* node.js version:    14.0.0                
* command-line arguments:  "testcafe chrome -e test.js"
* browser name and version: Chrome 92.0 
* platform and version:    "macOS 11.2.3 , BigSur"

**Comment by AlexanderMoiseev** [comment]
Hello, 

Thank you for your input. Indeed, the blank page is shown after logging in. We need some time to investigate the issue. Please stay tuned.
