### ISSUE TITLE
Testcafe never ends on IE when used with core-js@3.16

### ISSUE THREAD

**Issue by ysgk** [DevExpress/testcafe#6510]
Although I don't know this is a bug of testcafe or of core-js, can you please help me?

### What is your Test Scenario?
I want to test my app that imports core-js@3.16 on IE 11.
 
### What is the Current behavior?
Testcafe hangs up on IE when `core-js/es/regexp/test` is imported in the app. This module is included in `core-js/stable`. Neither 3.16.0 nor 3.16.4 worked. 3.15 was fine.

This is the failing run:
https://github.com/ysgk/corejs-testcafe-repro/runs/3472587058
(I canceled it because it would never end.)

Although I don't have a physical windows machine, I found that the console says `Out of stack space` repeatedly by using saucelabs (I attached the screenshot below).

The page works correctly when directly accessed (like `http://localhost:3000`, not like `http://192.168.210.68/rNAPZiDB8/http://localhost:3000/`).

And the test finishes successfully if I remove the import statement.

```diff
-import 'core-js/es/regexp/test'
```

This is the successful run:
https://github.com/ysgk/corejs-testcafe-repro/actions/runs/1186060882
 
### What is the Expected behavior?
Finishes tests on IE when core-js@3.16 is imported in the app.
 
### What is your web application and your TestCafe test code?
<details>
<summary>Your website URL (or attach your complete example):</summary>

```js
// index.js
import 'core-js/es/regexp/test' // This line causes it.

const div = document.createElement('div')
const text = document.createTextNode('Hello')
div.appendChild(text)
const root = document.getElementById('root')
root.appendChild(div)
```
</details>
 
<details>
<summary>Your complete test code (or attach your test files):</summary>

```js
// test.js
import { Selector } from 'testcafe'

fixture`Getting Started`.page`http://localhost:${process.env.PORT}`

test('My first test', async (t) => {
  await t.expect(Selector('#root').hasChildElements).ok()
})
```
</details>

<details>
<summary>Your complete test report:</summary>
The test hangs up on IE. The console says `Out of stack space` repeatedly.

</details>

<details>
<summary>Screenshots:</summary>

<img width="1265" alt="スクリーンショット 2021-08-23 1 09 38のコピー" src="https://user-images.githubusercontent.com/13102129/131501984-8e4d07f4-f3df-4cfa-a485-5ff8dfae64dd.png">
</details>

### Steps to Reproduce:

1. Please see this failing GitHub action: https://github.com/ysgk/corejs-testcafe-repro/actions/runs/1186022249
 
### Your Environment details:
 
* testcafe version:                   1.15.3
* node.js version:                    14.17.5
* command-line arguments:  `testcafe ie e2e/test.js -a "http-server dist -p 3000"`
* browser name and version: IE 11
* platform and version:          Windows 10, Windows Server 2019
* other:                                   

## Minimal reproduction
https://github.com/ysgk/corejs-testcafe-repro

**Comment by miherlosev** [comment]
Hi @ysgk 

Thank you for the shared example. I've reproduced the issue.
