### ISSUE TITLE
Support for New Cucumber version (@cucumber/cucumber)

### ISSUE THREAD

**Issue by RanjitAwati** [DevExpress/testcafe#6514]
Currently Testcafe is not supporting the latest version of @cucumber/cucumber
Since the older version of Cucumber is deprecated and the tests running with cucumber are on hold now 
Using Testcontroller, hooks and cucumber should be supported

**Comment by pavsenin** [comment]
Hello,
Testcafe does not have any built-in integration with Cucumber.
For further support, you need to contact the author of the Cucumber package.
