### ISSUE TITLE
JavaScript Error only using Testcafe

### ISSUE THREAD

**Issue by zakmketool** [DevExpress/testcafe#6516]
JavaScript error details:
      ResizeObserver loop limit exceeded
          No stack trace available

Checked using browser myself and no JS error occurred.

**Comment by miherlosev** [comment]
Hi @zakmketool 

This issue does not relate to TestCafe, so I will close it. See a detailed explanation at [https://github.com/DevExpress/testcafe/issues/4857#issuecomment-598775956](https://github.com/DevExpress/testcafe/issues/4857#issuecomment-598775956).
