### ISSUE TITLE
Can this support firefox app testing on mobile 

### ISSUE THREAD

**Issue by RollerIn** [DevExpress/testcafe#6518]
Can this support firefox app testing on mobile <android>?

if yes, can share a link to explore to know leverage for my project.

**Comment by Farfurix** [comment]
@RollerIn 

Hello,

Please refer to our "[Test on Remote Computers and Mobile Devices](https://testcafe.io/documentation/402807/recipes/basics/test-on-remote-computers-and-mobile-devices)" article. You can also find useful information in the [Continuous Integration](https://testcafe.io/documentation/402809/guides/continuous-integration) section.
