### ISSUE TITLE
.contains with callback

### ISSUE THREAD

**Issue by ben-gooding-sky** [DevExpress/testcafe#6526]
### What is your Test Scenario?
assert on an array whether it contains a string that returns true for a given callback

### What are you suggesting?
```
  const callback = (log) => log.includes('requires this');
  await t.expect(consoleLogsArray).contains(callback);
```

### Additional context
It's a very common and easy to implement solution, and I think it is useful enough that it should be provided and I don't have to roll my own version.

Also the request logger already has this exact functionality when you call .contains on it.

**Comment by ben-gooding-sky** [comment]
Here is an example of my workaround, but I feel it should be native:
```
export const contains = async (iterable, callback, message = 'No items found in iterable') => {
  for (const item of iterable) {
    if (callback(item)) {
      return true;
    }
  }
  await t.expect(false).ok(message);
};
```

**Comment by AlexanderMoiseev** [comment]
Hello, 

Thank you for your suggestion. We discussed it and see that you can achieve your goal by simply doing the following:

`await t.expect(consoleLogsArray.some(log => log.includes('requires this'))).eql(true);`

Your code is not necessary in this case.
