### ISSUE TITLE
Unable to open a url with ws02 authentication

### ISSUE THREAD

**Issue by pp1982** [DevExpress/testcafe#6529]
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 fixture`Initial setup test`.meta('env', getEnv()).page("https://mycloudpages.appspot.com/")
test('check login feature', async () => {
await t.typeText(Selector('input[type="email"], email')
await t.typeText(Selector('input[type="Password"], password')
})
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```
<img width="894" alt="urlLoad" src="https://user-images.githubusercontent.com/88386798/132881063-1d882530-57f2-4425-9dd1-0f395b119926.PNG">

```
</details>

 
### Your Environment details:
 
* testcafe version:                   1.15.3
* node.js version:                   14.17.5
* browser name and version: chrome 93.0.4577.63

**Comment by miherlosev** [comment]
Hi @pp1982 

Thank you for the shared information. I've reproduced the issue.

For team:
```js
import { t, Selector } from 'testcafe';

fixture`Initial setup test`
	.page("https://mycloudpages.appspot.com/");

test('check login feature', async () => {
	await t.typeText(Selector('input[type="email"]', { timeout: 60000 }), 'email');
	await t.typeText(Selector('input[type="Password"]'), 'password');
});
```

**Comment by mahesh-nihr** [comment]
Hi guys, any temporary workarounds to solve this issue?

**Comment by pp1982** [comment]
Could you please let us know when we can receive a reponse, this is a major blocker for us and all of the regression is stranded which is definitely having an impact on testing. So at this stage may its better to move onto another tool, as I am really disappointed with the slowness of response.

**Comment by aleks-pro** [comment]
Hello @pp1982 ,

We will update this thread once we have any news regarding this issue.
