### ISSUE TITLE
Not helpful error messages on bad token in request headers

### ISSUE THREAD

**Issue by Evilweed** [DevExpress/testcafe#6530]
Messages we get when request headers are for some reason invalid are not helpful. There is no information what request was it, to what URL, what are the headers, or at least what is the full header that is improper. Instead we get just the information of which token is invalid.

<img width="1001" alt="CleanShot 2021-09-12 at 14 44 22@2x" src="https://user-images.githubusercontent.com/5477821/132988083-855efd6a-4383-4b5a-9bf8-49381febf6be.png">

### What is your Test Scenario?
Because the error messages are not helpful at all we cannot provide test scenario as we don't even know what request is causing issues.
 
### What is the Current behavior?
Error message of invalid token in headers is not showing detailed helpful information like URL, all headers.
 
### What is the Expected behavior?
Error message should contain request URL and at least full header name and value of faulty header.
 
### What is your web application and your TestCafe test code?
Because the error messages are not helpful at all we cannot provide test scenario as we don't even know what request is causing issues.

### Steps to Reproduce:

1. Create endpoint that returns request with invalid tokens in header
3. Run test that loads page with invalid headers
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.15.3
* node.js version:                    v12.18.2
* command-line arguments:  testcafe chrome -e test.js
* browser name and version: Chrome 93
* platform and version:          macOS 11.5.2

**Comment by miherlosev** [comment]
Hi @Evilweed

These error messages are raised by the internal code of Node.js. You should address your proposal to the [Node.js repository](https://github.com/nodejs/node).
