### ISSUE TITLE
Support interacting with "video" html5 element via mouse click

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe#6536]
### What is your Test Scenario?
Test a video playing in the `<video>` element.

### What are you suggesting?
Video playing should start with the mouse click. At present, nothing happens when TestCafe clicks the video on the page.

### What alternatives have you considered?
`document.querySelector('video').play();`

### Additional context
SC ticket: https://supportcenter.devexpress.com/internal/ticket/details/T1028548

**Comment by miherlosev** [comment]
TestCafe normally works with the `video` elements in the `NativeAutomation` mode.

```js
import { Selector } from 'testcafe';

fixture `Fixture`
    .page('https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video');
	
test('test', async t => {
	await t
	    .click(Selector('main .interactive.is-tabbed-standard-height'))
		.switchToIframe('iframe.interactive')
	    .switchToIframe('#output-iframe')
		.click('video', { offsetX: 20, offsetY: 80 })
		.wait(3000);
});	
```

So, it's necessary to add the support of the `NativeAutomation` mode for TestCafe Studio.
