### ISSUE TITLE
Testcafe fails sso redirection after upgrading to version 1.14.1

### ISSUE THREAD

**Issue by LLocciOWT** [DevExpress/testcafe#6537]
### What is your Test Scenario?
Hello,
I'm writing tests for an internal application using authentication through ADFS. I had no problem running the tests until I upgraded my Testcafé version to the 1.15 (I found out that it works well with the 1.14.0 and below but not with the 1.14.1 and above).

### What is the Current behavior?
The sso redirection is not working, the test stops after a short redirection waiting time. The user authentication seems to work well. I do not get any specific redirection error in the console. The loading page remains blank, and I simply get a "DOM element not found" message after the test stops. What I understand is that the sso redirection does not work after the authentication, and thus DOM is not loaded.

### What is the Expected behavior?
Testcafe should redirect properly through the flow and execute the test, and then fail or succeed.

### What is your web application and your TestCafe test code?
The application is an internal app, thus I can not provide a link in this post. Here is one example of the tests I tried to run: 
```
require('custom-env').env(true)

//------------------------------------- IMPORTS -------------------------------------
import { authenticateUser } from '../Roles/Users.js';
import { SalesDocumentsList, SalesDocumentEntry } from './sales.pageModels.js';
import { Selector } from 'testcafe';

//-------------------- FIXTURE : SALES FIXTURE ---------------------

fixture `FIXTURE: SALES FIXTURE`
    .page(process.env.SALES_DOC_LIST_URL_C)
    .beforeEach(async t => {
        await t.useRole(authenticateUser(process.env.EMAIL, process.env.PASSWORD, process.env.SALES_DOC_LIST_URL_C));
    });

//------------------------------- Sales - Roles and user rights > X library access rights  ---------------------------------
test
.httpAuth({
    username: process.env.USERNAME,
    password: process.env.PASSWORD
})(' Admin user can access the X library in the Y workspace', async t => {

    console.log('\n\n--- Sales - Roles and user rights > X library access rights --- \n');
    const docListPage = new SalesDocumentsList();

    await t
        .expect(docListPage.WDocLib.exists).ok('The W doclib is not visible to the admin user.')
        .expect(docListPage.XDocLib.exists).ok('The X doclib is not visible to the admin user.')
        .click(docListPage.XDocLib)
        .expect(Selector('#pageTitle').find('a').withExactText('X').exists).ok('The X page has not been loaded');
    }
);
```

I use the function "useRole" for authentication. Here is the code handling the authentication : 

```
export function authenticateUser(email, password, startpage){
    
    const continueButton =  Selector('input').withAttribute('name','HomeByEmail');

    const myUser = Role(startpage, async t => {

        const employeLogin = Selector('span').withExactText('Employee Login');
        
        // Use the appropriate authentication
        if(await employeLogin.exists){
            //console.log('\n\n Login through : Employee login \n');
            await t
            .click(employeLogin);
        }
        else{
            //console.log('\n\n Login through : another type of login \n')
            await t
            .typeText('#emailInput',  email) // enter email in the bar
            .click(continueButton); // click on the continue button
        }

    },{ preserveUrl: true });

    return myUser;
}
```

When testcafe starts a new test, it first needs to click on  the employee login button, then provides the credentials (ADFS authentication) and is then redirected to the right page. The redirection URL (provided in the fixture under the variable *process.env.SALES_DOC_LIST_URL_C* ) is basically similar to : https://appName-environment.companyName/sales/workspaceID/libraryName/Forms/viewName.aspx

### Your Environment details:
 
* testcafe version: I tested it with 1.14.1, 1.14.2 and 1.15, none of them work. However the same exact test works well with testcafe 1.14.0 .
* node.js version: 14.15.1.
* npm version: 6.14.8
* command-line arguments:  testcafe chrome mytest.js --speed 0.7
* browser name and version: Chrome --> version 93.0.4577.63 ; Edge --> version 93.0.961.47
* platform and version: Windows 10
* other: I work with a VPN connexion to the internal network of my company

Thank you very much for your help

**Comment by pavsenin** [comment]
Hello LLocciOWT,

Thank you for the code sample, but I couldn't reproduce the issue on my side without valid values for SALES_DOC_LIST_URL_C, USERNAME, and PASSWORD environment variables.

It would be helpful if you prepare a test environment (the valid page URL, login, and password) where I can reproduce the issue on my side and research it further.

**Comment by LLocciOWT** [comment]
Hello Pavel,

Thank you very much for your reply, I will prepare this and come back to
you as soon as possible.

Best regards.

**Comment by LLocciOWT** [comment]
Hello, 

I was not able to get a specific environment for you to reproduce the issue because of confidentiality issues. I made two short videos of the same exact test, one with the version 1.14.0 of Testcafé (working usecase), and the other with the version 1.14.1 of Testcafé (non working usecase). I hope this can help to further understand the issue we are encountering. 

Thank you for your help.

![Version1-14-0_working](https://user-images.githubusercontent.com/85735772/133284902-46ff021b-8e04-489d-bd34-f6845f4e2a35.gif)
![Version1-14-1_NOTworking](https://user-images.githubusercontent.com/85735772/133284938-48df6f70-73ef-49b2-9f19-f707dfe2143f.gif)

**Comment by pavsenin** [comment]
Hello LLocciOWT,

In TestCafe 1.14.1, we added support of [HTTP/2](https://http2.github.io/)[﻿](https://http2.github.io/) requests, so it may be related to this issue. To check this, please run your tests with TestCafe 1.14.1 using the [https://testcafe.io/documentation/402639/reference/command-line-interface#--disable-http2](https://testcafe.io/documentation/402639/reference/command-line-interface#--disable-http2) option and let me know your results.

It is hard to determine the cause of the issue without reproducing it locally. If you do not want to share confidential information here, you can send it to support@devexpress.com.

**Comment by LLocciOWT** [comment]
Hello Pavsenin, 

Thank you for the proposition. I tried to disable the HTTP/2 requests but it does not work neither. I will contact the support@devexpress.com. 

Thank you for your help.
