### ISSUE TITLE
Redirect Never goes fully through

### ISSUE THREAD

**Issue by JamesWilhelm** [DevExpress/testcafe#6538]
While Running my test to get to https://billmgmt.dteenergy.com testcafe seems to stop on the SAML authentication redirect and never gets to the actual login screen.

### What is your Test Scenario?
I am trying to log into the following site: https://billmgmt.dteenergy.com. However, I can never get testcafe to land on that page to enter the actual username and password. 

I can cheat it by going to "https://newlook.dteenergy.com/wps/wcm/connect/dte-web/login?SAML=true&samlContext=863395140504_1da2d0de-06e9-43e4-8005-0f3e3e15ff36" 

But once there it doesn't submit (the button never goes anywhere). 

### What is the Current behavior?
Testcafe is not letting the website fully load in order for me to enter the credentials. 

### What is the Expected behavior?
The site would load and then allow for me to enter the creds

### How would you reproduce the current behavior (if this is a bug)?
By just trying to visit the page via test cafe (I've tested this on selenium and it works fine)

#### Provide the test code and the tested page URL (if applicable)

 
Your website URL (or attach your complete example):

Your complete test code (or attach your test files)

`import {Selector } from "testcafe";
const dataSet = require('../data.json')

fixture `Login Test`
    .page('https://billmgmt.dteenergy.com')

    .beforeEach(async t => {
        await t
        .setTestSpeed(0.1)
        .wait(8000)
        
    
    })

// dataSet.forEach(data => {
test(`User Can Login with valid creds`, async t => {
    await t.wait(7000)
    
    const signInButton = Selector('#signinAndReloadUnified')
    
    
    //check for login form
    const loginForm = Selector('.custom-form-style')
    await t.expect(loginForm.exists).ok()

    const usernameInput = Selector('#input-Email')
    const passwordInput = Selector('#input-Password')
    //put input (paste:true puts input in all at once)
    // usernameInput, data.username
    // passwordInput, data.password
    await t.typeText(usernameInput, "random", {paste:true})
    await t.typeText(passwordInput,"random", {paste:true})

    //submit
    await t.click(signInButton)
    await t.wait(7000)

    const billContributorsHeader = Selector('.mb-4 text-xl font-semibold').exists
    await t.takeScreenshot()
    await t.expect(billContributorsHeader).ok()
    
   
    //check to make sure login form is gone
    await t.expect(loginForm.exists).notOk()

})
    
// })
`
### Your Environment details:
 
* testcafe version:                   1.15.1
* node.js version:                    v14.17.4

**Comment by VasilyStrelyaev** [comment]
Hello @JamesWilhelm
I tried to open https://billmgmt.dteenergy.com/ from a new Incognito tab in Chrome (without TestCafe), and I observed the same behavior - the redirect never ended and the browser threw `ERR_CONNECTION_TIMED_OUT`. TestCafe opens the tested website from a clean browser state, so it gets the same result.
 
You may be able to open this website with Selenium because it uses your current profile, which has certain data required to complete the redirect in the cookies or storage. To do the same with TestCafe, add the `:userProfile` postfix to the browser alias as described in the [User Profiles](https://testcafe.io/documentation/402828/guides/concepts/browsers#user-profiles) document.

**Comment by JamesWilhelm** [comment]
@VasilyStrelyaev Just to confirm the only I need to do is add the :UserProfile after the browser? upon trying this I was still unable to get the site to load. Its as if it doesn't accept the SAML redirect (our site redirects twice) and it seems like test cafe is timing out before the 2nd redirect occurs. 

Thank you

**Comment by VasilyStrelyaev** [comment]
The Google Chrome browser does not complete the redirect and times out in the same way when I try to open this website.

<img width="972" alt="image" src="https://user-images.githubusercontent.com/11459924/133572242-d47f284b-cd17-40b2-b906-52f390c9a4b8.png">

This means that TestCafe replicates the browser behavior, so I do not see a problem with TestCafe in this example.
 
To confirm a TestCafe issue, I need a scenario that I could complete successfully in my browser and where TestCafe's behavior is different.

**Comment by JamesWilhelm** [comment]
@VasilyStrelyaev I've tested this solution with chrome and having incognito mode enabled and it goes through.
<img width="710" alt="Screen Shot 2021-09-17 at 2 41 10 PM" src="https://user-images.githubusercontent.com/51054098/133838123-3eaa6c9f-ae1a-490c-b21c-415d5a5a4331.png">

I'm not sure why you aren't able to access it, but for me the chrome browser (incognito enabled) works every-time.  

I put a video below showing how test cafe never completes the re-direct but the incognito tab does for me.

https://user-images.githubusercontent.com/51054098/133838654-c195a008-c62c-4bbf-aef9-3951a784c158.mov

**Comment by aleks-pro** [comment]
Hi @JamesWilhelm , 

I have managed to reach the login page after I enabled VPN. Also, we tried different VPNs and not all of them solve the issue. This fact adds complexity to debugging and fixing the problematic behavior. So, would you create and share with us a self-hosted example where the problem is reproduced?

Also, the debug info can help us find the cause of the issue. To collect it, set the `DEBUG` environment variable to `hammerhead:*,testcafe:*` and run your tests, e.g.:
```
set DEBUG=hammerhead:*,testcafe:*  
testcafe chrome ./test.js 2> testcafe.log
```
Then, share it with us.

**Comment by JamesWilhelm** [comment]
@aleks-pro can I just add those variable to the script I run? Or is there somewhere specific I set the "DEBUG"? (sorry I'm still new with this framework.)

**Comment by aleks-pro** [comment]
You need to set the `DEBUG` [environment variable ](https://en.wikipedia.org/wiki/Environment_variable) in a terminal before you call the command that starts TestCafe tests. The API that sets the environment variable differs depending on the terminal system.

bash/zsh:     `export DEBUG=hammerhead:*,testcafe:*`
cmd.exe:      `set DEBUG=hammerhead:*,testcafe:*`
PowerShell: `$Env: DEBUG = "hammerhead:*,testcafe:*"`
