### ISSUE TITLE
An error is thrown when a certain ERP page with TestCafe or Hammerhead is opened

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe#6545]
See the issue in the TestCafe Studio repo: https://github.com/DevExpress/testcafe-studio/issues/4024

Steps to reproduce:

1. Launch the testcafe-hammerhead proxy using the `gulp https-playground` command.
2. Click the link specified in the SC ticket to navigate to the ERP page.
3. Fill in the login form.
4. After redirecting, you will see an infinite spinner on the page. Also, there will be the following error in the browser console:
`Error: The value property of a object ([object HTMLElement]) cannot be assigned.`

* testcafe version: 1.16.0
* node.js version: 14.16.0

**Comment by AlexKamaev** [comment]
I replied in private repo
