### ISSUE TITLE
TestCafe runs into the "undefined is not an object" error (Safari 15) and hangs when connecting to iOS 15 remote browsers

### ISSUE THREAD

**Issue by rob4629** [DevExpress/testcafe#6546]
### What is your Test Scenario?

We're trying to run our automated regression tests targeting Safari iOS 15 (BrowserStack iPhone 11 Pro). BrowserStack has a Beta release of iOS 15, which we want to make sure won't break our site. You can target this using their browserstack-config.json file:

```json
{
  "os_version": "15 Beta"
}
```
 
### What is the Current behavior?

Once our site loads, TestCafe fails to start and hangs
 
### What is the Expected behavior?

I would expect TestCafe to run against iOS 15 in the same way it does for previous iOS versions
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
fixture('Check Page loads').page('https://www.change.org/');

  test('Head to Promotion page and verify it loads', async t => {
    await t
      .navigateTo('/p/the-world-send-matt-damon-to-mars-to-recover-opportunity/sponsors/new')
      .expect(Selector('.js-email').visible)
      .ok();
  });
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
2. Run tests against BrowserStack's iPhone 11 Pro (iOS 15) browser
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:  1.16.0                 
* node.js version:                    
* command-line arguments: BROWSERSTACK_CAPABILITIES_CONFIG_PATH='browserstack-config.json' BROWSERSTACK_USE_AUTOMATE=1 testcafe 'browserstack:iPhone 11 Pro' 
* browser name and version: 
* platform and version:          
* other:

**Comment by rob4629** [comment]
Working with BroswerStack, it seems like an issue within testcafe-hammerhead. The hanging occurs because we're skipping js errors by default (removing this option, displays the error)

```
JavaScript error details:
      undefined is not an object (evaluating 's["default"].objectHasOwnProperty.call(l,"writable")')
      hasOwnProperty@[native code]
      i@http://192.168.0.111:51702/hammerhead.js:15:23673
      a@http://192.168.0.111:51702/hammerhead.js:15:23798
```

**Comment by Farfurix** [comment]
@rob4629 

Hello,

I reproduced this issue. We will update this thread once we have news.

Logs:
![Capture](https://user-images.githubusercontent.com/30019338/133970649-f3c67322-d953-45e4-baba-23cb0402539f.PNG)

https://user-images.githubusercontent.com/30019338/133970658-0bfb4502-1a01-4fca-8388-27157e65d681.mp4

**Comment by Farfurix** [comment]
For the team:
I checked this scenario with macOS Big Sur 11.6 and Safari 14.1.2 and the test ran without any errors.

**Comment by rob4629** [comment]
BrowserStack's development team have opened a PR for this issue: https://github.com/DevExpress/testcafe-browser-provider-browserstack/pull/156

**Comment by Farfurix** [comment]
@rob4629 

Thank you. We'll take a look.

**Comment by Farfurix** [comment]
I reproduced the "undefined is not an object" error with Safari 15 and macOS 11.6 (without BrowserStack). It looks like we need to fix our style overriding in the Safari 15 case.
For the team.

```
> Object.getOwnPropertyDescriptor(document.createElement('img').style, 'background-image')
< undefined // Safari 15, but Chrome returns the correct descriptor
```

To get the descriptor, we need to get a prototype:
```
> Object.getOwnPropertyDescriptor(Object.getPrototypeOf(document.createElement('img').style), 'background-image')
< {get: function, set: function, enumerable: true, configurable: true} // Safari 15
```

**Comment by Farfurix** [comment]
For the team: check this Safari 15 local hanging scenario - https://github.com/DevExpress/testcafe/issues/6583.
