### ISSUE TITLE
PDF filename after download varies between testcafe versions

### ISSUE THREAD

**Issue by thakurshikha** [DevExpress/testcafe#6548]
**Test scenario:**
Download a pdf file on clicking print button in an application opened in chrome browser.

**Difference in behavior:**
**_In v1.14.2_** - PDF is saved by it's filename
**_In v1.15.0 and above_** - PDF is saved by it's Title

**Actual behavior:**
PDF is saved by it's Title

**Expected behavior:**
PDF should be saved by it's filename

I recently upgraded testcafe version from 1.14.2 to 1.15.0 ( or 1.16.0). I found that the pdf downloaded has different names if testcafe version is changed for the same application.( I can't share applicational URL)
If I perform the same action manually in an application then pdf is downloaded by it's filename likewise in v1.14.2.

![PDF_filename](https://user-images.githubusercontent.com/48122139/134327772-a79b0436-cda1-4c72-8f24-c2fdc4bf53b9.jpg)

**Your Environment details:**
testcafe version:  1.14.2 (works as expected), 1.15.0 or above (not working as expected)
node.js version: 14.15.4.
browser name and version: Chrome --> version 93.0.4577.82
platform and version: Windows 10

**Comment by thakurshikha** [comment]
I could only manage a screenshot to explain my issue for now. Will it serve the purpose?

![PDF_filename](https://user-images.githubusercontent.com/48122139/134329300-66adcb06-4fda-4bc5-a753-4132ae451989.jpg)

 As you can see in above screenshot the `title` and `filename/resource uri` is different for a PDF file. And I understood on further investigation that it could possibly issue with chrome extension. However, I am wondering what has changed on testcafe side that causing below difference in behavior. Could it be dependency **_chrome-remote-interface_** ? 
**In v1.14.2** - PDF is saved by it's filename
**In v1.15.0 and above** - PDF is saved by it's Title/Resource URI

**Comment by AlexKamaev** [comment]
Unfortunately, the information you provided is not sufficient. I was not able to reproduce the issue using the screenshot. Moreover, from your description, it's unclear what Chrome extension you mean.
Please create a minimal reproducible example as described in the article that is mentioned above.
