### ISSUE TITLE
Testcafe fails to load universal-cookie correctly

### ISSUE THREAD

**Issue by st3mc5** [DevExpress/testcafe#6549]
### What is your Test Scenario?

When running tests that import universal-cookie testcafe throws a type error.
 
### What is the Current behavior?

When trying to use TypeScript and universal-cookie testcafe errors with:
```
TypeError: universal_cookie_1.default is not a constructor
```
This appears to be something odd in the way testcafe is building the typescript as universal cookie works fine in other situations.

### What is the Expected behavior?
The tests run and pass or fail based on the actual test case.
 
### What is your web application and your TestCafe test code?

https://github.com/st3mc5/testcafe-bug
 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import Cookies from "universal-cookie";

fixture`Getting Started`.page`http://localhost:3001/`;

test("My first test", async (t) => {
  const cookies = new Cookies();
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
none
```
</details>

<details>
<summary>Your complete test report:</summary>

```
 yarn testcafe -c 5 chrome:headless './e2e/cookietest.e2e.ts'
yarn run v1.22.10
$ /home/steve/alinta/testcafe-bug/node_modules/.bin/testcafe -c 5 chrome:headless ./e2e/cookietest.e2e.ts
 Running tests in:
 - Chrome 89.0.4389.90 / Linux 0.0

 Getting Started
 ✖ My first test

   1) TypeError: universal_cookie_1.default is not a constructor

      Browser: Chrome 89.0.4389.90 / Linux 0.0

         2 |import Cookies from "universal-cookie";
         3 |
         4 |fixture`Getting Started`.page`http://localhost:3001/`;
         5 |
         6 |test("My first test", async (t) => {
       > 7 |  const cookies = new Cookies();
         8 |});
         9 |

         at <anonymous> (/home/steve/alinta/testcafe-bug/e2e/cookietest.e2e.ts:7:19)
         at <anonymous> (/home/steve/alinta/testcafe-bug/e2e/cookietest.e2e.ts:8:71)
         at __awaiter (/home/steve/alinta/testcafe-bug/e2e/cookietest.e2e.ts:4:12)
         at <anonymous> (/home/steve/alinta/testcafe-bug/e2e/cookietest.e2e.ts:6:35)


   2) undefinedFailed to load the page at "http://localhost:3001/".
      Increase the value of the "pageRequestTimeout" variable, enable the "retryTestPages" option, or use quarantine mode to perform additional attempts to execute this test.
      You can find troubleshooting information for this issue at "https://go.devexpress.com/TestCafe_FAQ_ARequestHasFailed.aspx".
      
      Error details:
      Failed to find a DNS-record for the resource at "http://localhost:3001/".

      Browser: Chrome 89.0.4389.90 / Linux 0.0



 1/1 failed (0s)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</details>

<details>
<summary>Screenshots:</summary>
![image](https://user-images.githubusercontent.com/74217363/133962582-8e7808af-05e6-4767-ba09-f8f9c9d55a70.png)
</details>

### Steps to Reproduce:

1. Using example codebase run `yarn testcafe -c 5 chrome:headless './e2e/cookietest.e2e.ts'`

### Your Environment details:
 
* testcafe version:                   1.16.0 
* node.js version:                    v12.19.1 
* command-line arguments:  `yarn testcafe -c 5 chrome:headless './e2e/cookietest.e2e.ts'`
* browser name and version: Chrome but N/A
* platform and version:          WSL Ubuntu and Azure Piplines
* other:                                   May be related to ESM loading: https://github.com/DevExpress/testcafe/issues/6535 ?

**Comment by AlexKamaev** [comment]
This is not an issue with TestCafe. Please refer the following thread:
https://github.com/reactivestack/cookies/issues/187
You can fix the issue using the TestCafe configuration file (https://testcafe.io/documentation/402638/reference/configuration-file) with the following content:
```JSON
{
  "compilerOptions": {
    "typescript": {
      "options": {
        "esModuleInterop": true
      }
    }
  }
}
```
