### ISSUE TITLE
'TypeError: Invalid value used as weak map key.' error in new testcafe versions 

### ISSUE THREAD

**Issue by AlexanderMoiseev** [DevExpress/testcafe#6563]
### What is your Test Scenario?
Run tests from the attached archive 
 
### What is the Current behavior?
'TypeError: Invalid value used as weak map key.' occurs 
 
### Steps to Reproduce:
1) download attached test project [Testcafe.zip](https://github.com/DevExpress/testcafe/files/7216808/Testcafe.zip)
2) Run the following commands
```
npx testcafe@1.16.0 chrome control.test.ts
npx testcafe@1.16.0 chrome data-inspector.test.ts
```
PS. works ok in Testcafe v.1.9.4 

### Your Environment details:
 
* testcafe version:                   1.16.0

**Comment by AlexKamaev** [comment]
fixed in https://github.com/DevExpress/testcafe-hammerhead/pull/2713
