### ISSUE TITLE
Emit a warning if proxy is enabled for HTTPS/HTTP2

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#6564]
We should emit a warning in following cases:
 - [ ] The target server uses HTTP/2 protocol, and proxy settings are specified
 - [ ] The target page is served via HTTPS, and the specified proxy doesn't support HTTPS

**Comment by AlexKamaev** [comment]
fixed in https://github.com/DevExpress/testcafe-hammerhead/pull/2696
