### ISSUE TITLE
Role is initialized without useRole()

### ISSUE THREAD

**Issue by AM1988** [DevExpress/testcafe#6567]
Hello.

Observing the not-expected behavior when working with Roles.

**helpers.js**

`import { Role } from 'testcafe';

export var registeredUser = Role(t => {
    await t
        .navigateTo('http://example.org')
        .typeText('#login', 'TonyStark')
        .typeText('#password', 'swordFish');
        .click('#login');
console.log('Role has been initialized');
});;`
**test.js**

`fixture 'example.org tests';

test('Anonymous users can see newly created comments', async t => {
    await t
        .navigateTo('http://example.org');
});`

I do not use t.useRole(registeredUser) in my test or befoEach hook but the message 'Role has been initialized' is printed to console. I expect that registeredUser role will be initialized only when I call it directly in the test or beforeEach hook but this seems not the case.

**Comment by AlexanderMoiseev** [comment]
Hi,

You are right, a role should be initialized only when being called. It accepts "loginUrl" as the first argument, not function. Please fix your code according to the [documentation](https://testcafe.io/documentation/402845/guides/advanced-guides/authentication#quick-guide) and let us know the results.
