### ISSUE TITLE
Make quarantine optional for each test

### ISSUE THREAD

**Issue by gemal** [DevExpress/testcafe#6569]
I have some tests that are not possible to retry. They change data in the database and rerunning the tests are just a waste of time as they will always fail.

So out of 10 tests only 3 of them are not retry able

So I would like to be able to mark some my test as not quarantine retry

**Comment by AlexanderMoiseev** [comment]
Hi,

We track interest in this option. I can't, however, provide you with a precise date as to when it may be introduced. For now I recommend you use the following [workaround](https://stackoverflow.com/questions/57288071/quarantine-mode-for-the-fixture-or-test).
