### ISSUE TITLE
Website: Update the design

### ISSUE THREAD

**Issue by VasilyStrelyaev** [DevExpress/testcafe#657]
What we want:
- [ ] Create a second-level top menu with items from the side menu's first level:  GS, Using testcafe, test API, extending, recipes.
- [x] Fix the header.
- [x] Fix the side menu. Let it have its own scrolling.
- [x] Make the article area rubber.

**Comment by inikulin** [comment]
@VasilyStrelyaev I guess we can close it now?

**Comment by VasilyStrelyaev** [comment]
You also wanted a separate top menu with top-level sections (GETTING STARTED, USING TESTCAFE, TEST API, EXTENDING TESTCAFE...)
See item 1

**Comment by inikulin** [comment]
Nah, I guess it looks just fine now. Let's return to this topic if there will be necessity
