### ISSUE TITLE
Incorrect type definitions of the RequestHook.onRequest and RequestHook.onResponse methods

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe#6572]
### What is your Test Scenario?
Implement custom RequestHook in the *.ts file as it is described here: [Create a Custom Request Hook](https://testcafe.io/documentation/402842/guides/advanced-guides/intercept-http-requests#create-a-custom-request-hook)
 
### What is the Current behavior?
A type error occurs when an example is copied from documentation:

```
Property 'onRequest' in type 'DropAccessTokenRequestHook' is not assignable to the same property in base type 'RequestHook'.
Type '(e: any) => void' is not assignable to type '(requestEvent: object) => Promise<void>'.
Type 'void' is not assignable to type 'Promise<void>'.
```
 
### What is the Expected behavior?
A synchronous `onRequest` method should be considered as valid.

**Comment by AndreyBelym** [comment]
TS definitions should allow passing both synchronous and asynchronous functions as request hooks methods.

**Comment by Aleksey28** [comment]
Fixed in the https://github.com/DevExpress/testcafe/pull/6708
