### ISSUE TITLE
Empty Uncaught Exceptions are flooding my test results

### ISSUE THREAD

**Issue by jbradenclickfunnels** [DevExpress/testcafe#6593]
### What is your Test Scenario?

 I'd like my tests to pass without the test results spamming me with empty uncaught exceptions

### What is the Current behavior?

 Test results say my tests failed due to uncaught exceptions, but the videos show the test runs all the way through and passes on the front end.

### What is the Expected behavior?

TestCafe reports back that the test passed OR it provides information on the uncaught exceptions.
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 fixture `editor`
  .page `reborncf.com/users/sign_in`
  .beforeEach(async t => {
    await t
      .maximizeWindow()
    await LoginPageObjects.login_with_password(data.users.account_owner.user_email, data.users.account_owner.user_password)
  })

test
  .meta({ createdOn: '08/10/21', createdBy: '', updatedOn: '09/28/21', updatedBy: '' })
  .meta({ scope: 'functional', priority: 'low', showstopper: 'no' })
  .meta({ ptOriginalId: '', ptAutomationId: '' })
  .after(async t => {
    await PagesPageObjects.delete_existing_page(page_name_1)
  })
  ('user_is_able_to_add_a_section_column_row_and_element_to_editor', async t => {

    // Purpose: To check that a section, row, and element can be added in the editor
    
    // Global variable to pass to the .after steps
    globalThis.page_name_1 = 'Add section row and element'

    await WorkspaceMainNavPageObjects.navigate_to_workspace_sites()
    await SitesPageObjects.navigate_to_pages_page()
    await PagesPageObjects.create_new_page(page_name_1)
    await HelperObjects.choose_existing_link(page_name_1)

    while(EditorPageObjects.iframe_edit_page().visible == false){
      await t
        .wait(.250)
    }

    await t
      .switchToIframe(EditorPageObjects.iframe_edit_page())

    await EditorPageObjects.add_full_page_section_to_page()
    await EditorPageObjects.add_1_column_row_to_page()
    await EditorPageObjects.add_headline_element_to_page()

    // Asserts the headline was added to the page
    await t
      .expect(EditorPageObjects.txt_call_to_action_headline_in_page.visible).ok()
  })
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
    "assertionTimeout": 5000,
    "browsers": [
        "chrome --window-size=1920,1159"
    ],
    "concurrency": 7,
    "filter": {
        "testGrep": []
    },
    "pageLoadTimeout": 30000,
    "reporter": {
        "name": "spec",
        "output": "artifacts/reports/test_suite_results"
    },
    "screenshots": {
        "path": "artifacts/screenshots",
        "pathPattern": "${TEST}_${DATE}_${TIME}.png",
        "takeOnFails": true
    },
    "selectorTimeout": 15000,
    "skipJsErrors": true,
    "src": "tests",
    "videoEncodingOptions": {
        "aspect": "16:9",
        "framerate": 30
    },
    "videoOptions": {
        "failedOnly": true,
        "pathPattern": "${TEST}_${DATE}_${TIME}.mp4",
        "singleFile": false
    },
    "videoPath": "artifacts/recordings"
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```
editor
 ✖ user_is_able_to_add_a_section_column_row_and_element_to_editor

   1) - Error in test.after hook -
      Uncaught exception:

      Error:

      Browser: Chrome 94.0.4606.71 / macOS 10.15.7


 ✖ pop_up_element_displays_during_page_preview

   1) Uncaught exception:

      Error:

      Browser: Chrome 94.0.4606.71 / macOS 10.15.7


 ✖ clicking_button_shows_hides_elements

   1) Uncaught exception:

      Error:

      Browser: Chrome 94.0.4606.71 / macOS 10.15.7


 ✖ user_is_able_to_save_when_adding_a_video

   1) Uncaught exception:

      Error:

      Browser: Chrome 94.0.4606.71 / macOS 10.15.7


 ✖ user_is_able_to_save_when_leaving_video_embed_blank

   1) Uncaught exception:

      Error:

      Browser: Chrome 94.0.4606.71 / macOS 10.15.7
```
</details>

<details>
<summary>Screenshots:</summary>

```
Video attached of test passing
```
https://user-images.githubusercontent.com/87319403/136227489-2124fe67-5b68-40f5-bb11-b8100d3289d4.mp4
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.15.2
* node.js version:                    14.18.0
* command-line arguments:  
* browser name and version: See test results
* platform and version:          See test results
* other:

**Comment by jbradenclickfunnels** [comment]
Thank you, @Farfurix. I have sent an email to support@devexpress.com to get this moving forward.

**Comment by Farfurix** [comment]
@jbradenclickfunnels 

Hello,

I reproduced a lot of errors in headless/non headless mode under Windows 10. Your project is quite complex and I suggest starting with [this socket error](https://github.com/DevExpress/testcafe/issues/6558). Please reply to my comment here: [https://github.com/DevExpress/testcafe/issues/6558#issuecomment-940823659](https://github.com/DevExpress/testcafe/issues/6558#issuecomment-940823659).

**Comment by rob4629** [comment]
I'm not sure if this is related, or if you need me to open a separate ticket.

We're experiencing an uncaught exception for our Safari based tests (Safari desktop, and using BrowserStack iPhones):
`Uncaught object "[object Object]" was thrown. Throw Error instead`. I can provide some example tests, which result in this failure

**Comment by Farfurix** [comment]
@rob4629 

Hello,

It's better to create a new one with your example and a link to this issue. While fixing, we will check all usage cases.

**Comment by Aleksey28** [comment]
Hi @jbradenclickfunnels,

Please check if the issue is still reproduced in the latest version. I cannot do it since it is not possible to download files with imported page models. If it is still reproduced, please attach the code for page models to this thread. You can remove the credentials from them as we already have them.

**Comment by rob4629** [comment]
My comment is no longer relevant. I created a separate ticket #6624 which has subsequently been fixed. Thanks
