### ISSUE TITLE
Test Results are printing in terminal instead of file

### ISSUE THREAD

**Issue by jbradenclickfunnels** [DevExpress/testcafe#6594]
### What is your Test Scenario?

Just running tests
### What is the Current behavior?

Test results are spitting out in the terminal instead of a defined file.
### What is the Expected behavior?

Test results to populate in the defined file.
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
    "assertionTimeout": 5000,
    "browsers": [
        "chrome --window-size=1920,1159"
    ],
    "concurrency": 7,
    "filter": {
        "testGrep": []
    },
    "pageLoadTimeout": 30000,
    "reporter": {
        "name": "spec",
        "output": "artifacts/reports/test_suite_results"
    },
    "screenshots": {
        "path": "artifacts/screenshots",
        "pathPattern": "${TEST}_${DATE}_${TIME}.png",
        "takeOnFails": true
    },
    "selectorTimeout": 15000,
    "skipJsErrors": true,
    "src": "tests",
    "videoEncodingOptions": {
        "aspect": "16:9",
        "framerate": 30
    },
    "videoOptions": {
        "failedOnly": true,
        "pathPattern": "${TEST}_${DATE}_${TIME}.mp4",
        "singleFile": false
    },
    "videoPath": "artifacts/recordings"
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```
![Screen Shot 2021-10-06 at 11 01 13 AM](https://user-images.githubusercontent.com/87319403/136240817-f3c5bee8-134d-42d8-83cf-13038798c4e9.png)
```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.16.1
* node.js version:                    16.10.0
* command-line arguments:  testcafe
* browser name and version: chrome 94.0.4606.71
* platform and version:          MacOS 11.6
* other:                                   All I did was update my testcafe and node. Now test results are spitting out in the terminal instead of the defined file in the testcaferc file.

**Comment by AlexanderMoiseev** [comment]
Hello,

Thank you for your input. We’ve reproduced the issue and need some time to investigate it. We'll get back to you when we have any results.

**Comment by onigoetz** [comment]
Hello, I have the same problem and it seems it was introduced between 1.16.0 and 1.16.1 as my CI worked fine with version 1.16.0
I hope it helps narrow down the issue more precisely.

**Comment by gregatp** [comment]
Hello,

I have the same issue.
It seems that reporter options in configuration file is ignored.
When I passed reporter options in command line, result is saved in file as expected.
`testcafe -r spec:artifacts/reports/test_suite_results`

**Comment by jbradenclickfunnels** [comment]
Hello,

I noticed that 1.16.1 and 1.17.0.rc1 are both available to download, but neither have the test results fix in them. Shouldn't DevExpress be focused on making sure newer versions aren't still regressed in previously implemented features?

I say this to ask the priority on this fix. I was hoping it would be in 1.16.2, but now that I'm seeing 1.17.0.rc1, I'm getting concerned. 

We don't want to stay on older versions due to an issue like this. 

Thanks,

**Comment by miherlosev** [comment]
The current development sprint is filed. We will consider fixing this issue in the next development sprint.

**Comment by aleks-pro** [comment]
We will process this inquiry here: https://github.com/DevExpress/testcafe/issues/6665. I will close the current issue as a duplicate.
