### ISSUE TITLE
Asynchronous function for providing httpAuth credentials

### ISSUE THREAD

**Issue by osmoossi** [DevExpress/testcafe#6595]
### What is your Test Scenario?
I'm using TestCafe to a test a website that uses HTTP basic authentication. The tests are ran on a pipeline and the password needs to be fetched from AWS SecretsManager. The operation to fetch the password is asynchronous, so it can not be used with TestCafe .httpAuth() function. The .before() method can not be used either to fetch and store the password, since .httpAuth() is ran before it.

### What are you suggesting?

```javascript
fixture('Test set name')
  .httpAuth(async () => ({
    username: 'username',
    password: await getSecret('password'),
  }))
  .page('http://website.url.com');
```

### What alternatives have you considered?

As a workaround, I have created a function that is ran in .beforeEach() to open and login to the website.

```javascript
const openAndLogin = async () => {
  const password = await getSecret('password');
  const url = `https://username:${password}@website.url.com`;
  await t.navigateTo(url);
};

...

fixture('Test set name')
  .page('about:blank');
  .beforeEach(async () => {
    await openAndLogin();
  });
```

However, this method stopped working with TestCafe update 1.14.0 -> 1.16.0, and is not supported by all browsers in general.

**Comment by miherlosev** [comment]
Hi @osmoossi

At present, we are focused on our [roadmap](https://testcafe.io/402949/roadmap) and don't expect to support this feature. If this feature is very important to you, try to implement it yourself.
