### ISSUE TITLE
The t.scrollIntoView method may cause the "element not visible" error

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe#6601]
### What is your Test Scenario?
Scroll the DevExtreme DataGrid to make a particular row visible.
 
### What is the Current behavior?
The t.scrollIntoView method causes the "element not visible" error.
 
### What is the Expected behavior?
The t.scrollIntoView method should scroll the DataGrid content.
 
### What is your web application and your TestCafe test code?
<details>
<summary>Your website URL (or attach your complete example):</summary>
https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/VirtualScrolling/jQuery/Light

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from 'testcafe';
fixture `dxtreme-scroll`
    .page `https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/VirtualScrolling/jQuery/Light/`;
test('New Test', async t => {
    await t
        .switchToIframe('.demo-frame').wait(10000);
    const el = Selector('[aria-rowindex="16"] [aria-colindex="2"]');
    await t
        .expect(el.visible).ok()
        .scrollIntoView(el);
});
```
</details>

<details>
<summary>Your complete test report:</summary>

```
The element that matches the specified selector is not visible.

Browser: Chrome 94.0.4606.61 / Windows 10

    9 | 
   10 |     const el = Selector('[aria-rowindex="16"] [aria-colindex="2"]');
   11 | 
   12 |     await t
   13 |         .expect(el.visible).ok()
 > 14 |         .scrollIntoView(el);
```
</details>

### Steps to Reproduce:

Run the test. 
 
### Your Environment details:
 
* testcafe version:                   1.16.0
* node.js version:                    14.18.0
* browser name and version: Chrome 94

**Comment by helen-dikareva** [comment]
Could be the same with https://supportcenter.devexpress.com/internal/ticket/details/T1059032/
