### ISSUE TITLE
[docs]: Set option `devServerTarget`

### ISSUE THREAD

**Issue by Aleksey28** [DevExpress/testcafe#6617]
https://testcafe.io/documentation/402793/recipes/integrations/use-angular-cli-builder#configuration-example

It needs to assign `devServerTarget` in both examples of this page

```
...
"options" : {
  "devServerTarget": "my-project:serve",
  ...
}
...
```

Also in the topic 'Configure a Target in the Angular Workspace' we should notice something like that:
"It needs to assign `"devServerTarget": "<project-name>:serve"` to automatically start a server, otherwise the server must be started by hands

**Comment by titerman** [comment]
The snippets and the description have been updated. It may take a while for the website to reflect these changes.
