### ISSUE TITLE
Browser in configuration file are parsed even if browsers are given on the command line

### ISSUE THREAD

**Issue by piefel** [DevExpress/testcafe#6618]
Applies to TestCafé 1.16.1

### What is your Test Scenario?

I have a [`.testcaferc.json` file](https://testcafe.io/documentation/402638/reference/configuration-file#browsers) such as:
```
{
    "browsers": ["ie", "firefox"]
}
```
Also, I do have Firefox installed but not Internet Explorer.
 
### What is the Current behaviour?
I call `npx testcafe edge tests/ --skip-js-errors`

Now I get: `ERROR Cannot find the browser. "ie" is neither a known browser alias, nor a path to an executable file.`
 
### What is the Expected behaviour?

Since the browser `edge` is given on the command line, the browsers from the config file should be ignored.
 
This is a change from previous behaviour. At least for 1.10.1, the config file browsers list was ignored. It took me ages to pinpoint the problem when our CI broke: We had a `.testcaferc.json` checked in for local development, but CI tried to use Browserstack instead; now the build broken just saying that chrome was not available.

**Comment by piefel** [comment]
I just noticed that under certain circumstances, the browsers list in the configuration file is _checked_ (including a bad exception if the browser is not found), but then _ignored_:

```
$ npm run test:browserstack:ie11

> ui-tests@1.0.0 test:browserstack:ie11 /…/ui-tests
> export $(cat .browserstack-config.properties | xargs) && testcafe 'browserstack:ie@11.0:Windows 10' tests/ --reporter teamcity

The "browsers" option from the configuration file will be ignored.
```

Running testcafe through npx directly, or having it in `package.json` _without_ the export bit, will still result in the browser from the command line being ignored completely.

**Comment by miherlosev** [comment]
The issue is not reproduced with `testcafe@1.18.0`.

![image](https://user-images.githubusercontent.com/4133518/147232343-bc65e78e-dcd2-4e01-8e11-9f350b3e5f74.png)

**Comment by dboujot** [comment]
Hello @miherlosev,
I have the same problem than @piefel.
I have a .testcaferc.json such as : 
`{
  "browsers": [
    "chrome",
    "firefox",
    "edge"
  ],
  "src": "tests/e2e/**/*.ts"
}`

When I launch my tests with testcafe v **1.18.1** from my gitlab pipeline I have the following error  "_ERROR Cannot find the browser. "edge" is neither a known browser alias, nor a path to an executable file_." The browser name provided by the command is ignored.
![image](https://user-images.githubusercontent.com/5011635/147951194-16d03873-ec11-4212-bdbc-78d0ee2df5da.png)

When I launch the same tests with an older version of testcafe, **v 1.14.2**, everything works fine
![image](https://user-images.githubusercontent.com/5011635/147951670-e0b8571c-458c-402a-9d39-b9d746af98c3.png)

@miherlosev,  cloud you do the test with an other OS than Windows, please?

**Comment by AlexanderMoiseev** [comment]
Hi @dboujot,

Thank you for pointing this out. I was able to reproduce it on a Mac device. Please stay tuned for further updates.

**Comment by dboujot** [comment]
Hi @AlexanderMoiseev,
I would have liked to know if this bug could soon be taken into account for correction?

Thanks for your feedback
