### ISSUE TITLE
Testcafe wrongly shows "filter" warning

### ISSUE THREAD

**Issue by di5ko** [DevExpress/testcafe#6620]
### What is your Test Scenario?
Run a test with a `--fixture-meta` flag or with a `.filter()` directive in a test runner file, without having any `filter` directives set up in `.testcaferc.json`.
 
### What is the Current behavior?
Testcafe shows a `The "filter" option from the configuration file will be ignored.` warning above and below each test run.
 
### What is the Expected behavior?
This warning not to show up.
 
### What is your web application and your TestCafe test code?
See MWE: https://github.com/di5ko/testcafe-filter-warning
 
### Steps to Reproduce:
Run the test from above MWE. Also see https://github.com/DevExpress/testcafe/issues/5544#issuecomment-942254698. 

### Your Environment details:
 
* testcafe version:                   1.16.1
* node.js version:                    v14.15.1
* command-line arguments:  npx testcafe chromium:headless filterissue.test.js --fixture-meta issue=true
* browser name and version: Chrome 93.0.4577.0 
* platform and version:           macOS 10.15.7
* other:                                     n/a

**Comment by di5ko** [comment]
@AlexKamaev filter warning is still shown for me in `v1.18.1`:

```
....

 7 passed (43s)

 Warnings (1):
 --
  The "filter" option from the configuration file will be ignored.
[RUN-TESTS] All tests done!
~/git/e2e-testing [2021-01-03-hotfix-pipeline*] $ cat .testcaferc.json 
{
    "selectorTimeout": 20000,
    "assertionTimeout": 20000,
    "pageLoadTimeout": 20000,
    "stopOnFirstFail": true,
    "skipUncaughtErrors": true,
    "disablePageCaching": true
}
```

**Comment by AlexanderMoiseev** [comment]
Hi,

The fix is available but not yet released. Please wait for the next Testcafe release or get changes from the master branch.
