### ISSUE TITLE
Add support for custom user variables in CLI

### ISSUE THREAD

**Issue by aleks-pro** [DevExpress/testcafe#6621]
You can setup custom user variables in the configuration file: https://testcafe.io/403403/release-notes/framework/2021-9-8-testcafe-v1-16-0-released#support-for-custom-user-variables-in-the-configuration-file

The similar functionality would be useful in CLI

**Comment by dantman** [comment]
Yes, please. I don't see the point of userVariables existing if you can't override it.

**Comment by KubaOczko** [comment]
I totally agree,

We have a url variable defined in the configuration file. This works great for CI, but if I want to run the tests locally, I need to change the domain name.

With CLI support I would call the command with the --user-variables url:https://localhost.... option.

currently, I have to edit the config file and discard the changes later, or I can create a development version of the config file, but I have to keep the development config file in sync with the original.

**Comment by Artem-Babich** [comment]
After additional research, we decided not to implement this functionality. There are different workarounds for this issue. The first one is to use a JS configuration file that defines user variables from the environment variables. In this case, you can specify environment variables via CLI, and they will be applied to the userVariables field.
Another solution is to use multiple JS config files with inheritance. For example:

```js
//common-config.js
module.exports = { src: “” }
```

```js
//prod-user-var.js
const commonSettings = require(‘./common-config’)
module.exports = {
…commonSettings,
userVariables: { someVar: ‘test’ } 
}
```

```js
//dev-user-var.js
const commonSettings = require(‘./common-config’)
module.exports = {
…commonSettings,
userVariables: { someDevVar: ‘test2’ } 
}
```

`testcafe –config-file prod-user-var.js`
`testcafe –config-file dev-user-var.js`
