### ISSUE TITLE
TestCafe hangs when running tests on Safari 15 (macOS Big Sur)

### ISSUE THREAD

**Issue by fadious** [DevExpress/testcafe#6632]
### What is your Test Scenario?

When trying to run any test on Safari 15, TestCafe hangs and can't perform any test step without any error. The same test works fine on other browsers like Chrome or FireFox.
 
### What is the Current behavior?

Once the site loads, TestCafe hangs 

### What is the Expected behavior?

TestCafe should run the test on Safari without any issue.
 
### What is your web application and your TestCafe test code?

 
<summary>Your website URL :</summary>

[https://www.easybib.com/](https://www.easybib.com/)

<summary>Test code:</summary>

 
```js
import { Selector } from 'testcafe'

fixture`Sample Test Fixture`.page('https://www.easybib.com')

test('Sample Test Case', async t => {
  await t.click(Selector('[data-test="create-citations-btn"]'))
})
```

### Steps to Reproduce:

1. Execute the sample test provided above

### Your Environment details:
 
* testcafe version:  1.16.1                 
* browser name and version: Safari 15.0 
* platform and version:  macOS 11.6

**Comment by joshhansen** [comment]
Any progress on this? I'm getting something similar on macOS Monterey with Safari 15.2---Firefox and Chrome run my tests perfectly, but the Safari window never even opens. It seemed to run fine previous to upgrading.

**Comment by jazirk** [comment]
Any progress on this?

**Comment by joserodriguezgit** [comment]
Checking in to see if there's any updates on this. Having this same issue with Safari 15.5, MacOS 10.15.7.
Thank you.

**Comment by miherlosev** [comment]
Hi @joserodriguezgit,

At present, there are no updates. Once we have news, we will update this thread.

**Comment by alameluQA** [comment]
Testcafe version 1.20.1
Safari Version 15.6 
MacOS Version 12.5 Montery

Same issue. Tests not executing after the url is loaded on Safari.

**Comment by anjali-amle** [comment]
Facing the same issue with Testcafe version  "testcafe": "1.18.0", and  "1.20.1"
safari version : 13

**Comment by goncaloneto** [comment]
Same here with TestCafe 2.0.1 and Safari 16.0.

**Comment by alameluQA** [comment]
any updates on this issue?

**Comment by aleks-pro** [comment]
Hello @alameluQA ,

There are not updates yet. We will raise the priority of the issue. Please stay tuned.
