### ISSUE TITLE
The upload form doesn't appear after button clicking

### ISSUE THREAD

**Issue by karthees05** [DevExpress/testcafe#6633]
### What is your Test Scenario?
One of my test is calling a 3rd party URI after clicking a button.
When it called, the "src" attribute is setting with the URI like,
src="http://my-local-ip or proxy uri/https://3rd party uri"
Due to the prefix of "http://my-local-ip or proxy uri" the connection is not happening with the 3rd party uri.
I want that "src" attribute to set with "https://3rd party uri"

### What is the Current behavior?
The "src" attribute is setting with the URI prefix of from where I am running my scenario

### What is the Expected behavior?
The "src" attribute should only set with the 3rd party uri.

Your complete test code (or attach your test files)

```js

```
### Your Environment details:
 
* testcafe version:  1.16.0                 
* node.js version:                    
* command-line arguments: npx testcafe chrome dotenv.js scenario.js 
* browser name and version: chrome, firefox
* platform and version: mac         
* other:

**Comment by karthees05** [comment]
Hi 

The below is my example scenario, 

`fixture `Getting Started`
    .page `https://flatfile.com/developers/playgrounds/`;

test('My first test', async t => {
    const test1 = Selector("*[class*='Flex__FlexWrapper']").nth(8);
    await t.click(test1)
    await t.wait(5000)    
    // then upload a document
});`

The testcafe is launching the base url as - http://193.163.0.17:636222/NwsIDbfKy*IC5vf4dzN/https://flatfile.com/developers/playgrounds/

And the same url is there in all the src/href properties in that page, due to that my test not uploading the data sheet into flat file server.

The same is working if I do manually as in normal browser the src/href properties are setting with the proper flat file url and not prefixed like the above url.

Is there a way to make my test run.

Thanks

**Comment by Farfurix** [comment]
@karthees05 

Hello,

Your selector (`Selector("*[class*='Flex__FlexWrapper']").nth(8)`) doesn't point to an upload link:
![Capture](https://user-images.githubusercontent.com/30019338/139806503-fb120661-1e00-4c81-be67-65383537554b.PNG)
Could you please clarify your test scenario? You click "Import Customer Data →" and then upload data from a file. Am I correct?

**Comment by kartheeswaranramasamy** [comment]
yes , you are right.
This is a sample one, as I can not post the client content. Thanks

**Comment by Farfurix** [comment]
@kartheeswaranramasamy 

Hello,

OK, I'll rename this issue to describe the actual behavior.

For the team:
After clicking the "Import Customer Data" button, the "Bulk add Customers" form (`iframe`) doesn't appear. This issue can be reproduced with the `testcafe-hammerhead` proxy.

```js
import { Selector } from 'testcafe';

fixture `Getting Started`
    .page `https://flatfile.com/developers/playgrounds/`;

test('upload', async t => {
    // The "Import Customer Data" button
    const importCustomerDataButton = Selector('#gatsby-focus-wrapper > div > div.Container-sc-xev89j-0.ecfSBh > div > div.docs-pages__MDXContainer-sc-1s1dzyw-1.playgrounds__DemoContainer-sc-13y0sal-3.jQCpOB.hSIYlk > div.playgrounds__Example-sc-13y0sal-9.bmhVXz > div > button');

    await t
        .click(importCustomerDataButton); // The "Bulk add Customers" upload form doesn't appear

    await t
        .wait(7000);
});
```
