### ISSUE TITLE
Allow video playback testing on Firefox

### ISSUE THREAD

**Issue by terciogarcia-hotmart** [DevExpress/testcafe#6640]
### What is the Current behavior?
I'm trying to test a HTML5 media player application, but when I run my tests in Firefox, it blocks the play interaction due to the default security settings.

Chrome has the same behavior, but I can easily solve it by passing the args `--autoplay-policy=no-user-gesture-required`.

This could be solved if the following params would be added to the Firefox prefs:
```js
'user_pref("media.autoplay.enabled.user-gestures-needed", false)',
'user_pref("media.autoplay.enabled.blocking_policy", 0)',
'user_pref("media.autoplay.default", 0)',
'user_pref("media.autoplay.enabled", true)',
'user_pref("media.autoplay.allow-muted", true)',
```

As far as I know, TestCafe API doesn't allow to customize those Firefox preferences, so I wonder if they could be added to the project.

### What is the Expected behavior?
Be able to play videos when testing in Firefox.

### Your Environment details:
testcafe version: 1.16.1
node.js version: 14.18
browser name and version: Firefox 93.0, Firefox 80.0
platform and version: MacOS BigSur 11.6

**Comment by AlexKamaev** [comment]
We decided to close this issue to keep our back log up to date. If anyone wants to make a PR to support the described functionality - we will review it.
