### ISSUE TITLE
[docs] describe test run hooks

### ISSUE THREAD

**Issue by titerman** [DevExpress/testcafe#6656]
Issue: https://github.com/DevExpress/testcafe/issues/745 
PR: https://github.com/DevExpress/testcafe/pull/6643

You can define testRun hooks in JavaScript configuration files. TestCafe executes these hooks before and after the test run. During the development stage, these hooks were known as setup/teardown tasks.

#### JS configuration file

Common template
```js
module.exports = {
  hooks: {
    testRun: {
      before: fn(ctx),
      after: fn(ctx),
    },
};
```

**Comment by AndreyBelym** [comment]
Done
