### ISSUE TITLE
Test Cafe Requires Permission To Record Screen -> but permission is already granted on MAC

### ISSUE THREAD

**Issue by roelvandijk88** [DevExpress/testcafe#6662]
### What is your Test Scenario?
To be able to record the screen on failures
 
### What is the Current behavior?
I recently upgraded my mac to Big Sur, and have the following version of TestCafe (1.16.1). When trying to run Testcafe I get the following error:

`TestCafe requires permission to record the screen. Open 'System Preferences > Security & Privacy > Privacy > Screen Recording' and check 'TestCafe Browser Tools' in the application list.`

I did the following:
**Unchecked and rechecked TestCafe Browser Tools, even tried removing the app using minus sign**
restarted my Mac

 
### What is the Expected behavior?
To be able to record the screen on failures
 

### Your Environment details:
 
* testcafe version:                   1.16.1
* node.js version:                    v12.18.3
* command-line arguments:  Not possible to run due to the error 
* browser name and version: Chrome 95.0.4638.69
* platform and version:          macOs Big Sur 11.6

**Comment by Farfurix** [comment]
@roelvandijk88 

Hello,

We faced a similar issue with TestCafe and TestCafe Studio installed at the same time. So, I'll close this issue as a duplicate. If your usage scenario is different from ours (TestCafe and TestCafe Studio installed at the same time), then describe it here: https://github.com/DevExpress/testcafe/issues/6604.

Also, you can try to reset system privacy permissions for macOS applications (`tccutil reset`) and restart your Mac.

**Comment by roelvandijk88** [comment]
@Farfurix

Hello,

I have both TestCafe and TestCafe Studio installed at the same time, so I think I have the same issue. But https://github.com/DevExpress/testcafe/issues/6604 shows a comment to another issue which gives a 404. 

Thanks in advance,
Roel

**Comment by Farfurix** [comment]
@roelvandijk88 

> I have both TestCafe and TestCafe Studio installed at the same time, so I think I have the same issue.

Thank you for the clarification.

>But #6604 shows a comment to another issue which gives a 404.

It refers to another issue in our private repository. Once we have any news, we'll update the https://github.com/DevExpress/testcafe/issues/6604 thread.

**Comment by roelvandijk88** [comment]
I'm still having issues, could you please help me?

**Comment by viktoria2506** [comment]
This issue was fixed in the latest Testcafe version (1.18.1). We are also preparing for the release of 1.7.0 of the Studio that will contain necessary improvements and fixes. For more detailed information, contact our [support center](https://supportcenter.devexpress.com/ticket/list?preset=f87f1c52-9062-4192-9faf-4675b1d37249).

**Comment by roelvandijk88** [comment]
Thanks for the help, I got it working again with https://testcafe.io/403664/release-notes/framework/2021-12-22-testcafe-v1-18-0-released#upgrade-instructions. Hope that the release of 1.7.0. will follow soon.

**Comment by liront2** [comment]
solved it.
Simply gave permission to the local testcafe app instead of the global.

**Comment by dmtri** [comment]
You could also remove existing TestCafe permission and add back again on prompt

**Comment by kjvarga** [comment]
Removing the existing TestCafe permission entry and then adding it back on prompt worked for me too.
