### ISSUE TITLE
Login form doesn't appear after click on a Login button

### ISSUE THREAD

**Issue by aleks-pro** [DevExpress/testcafe#6673]
A click on a login button should invoke a new browser window with the login form on a website. With TestCafe, this doesn't work. You can find additional info in the following private ticket:https://supportcenter.devexpress.com/internal/ticket/details/T1037471
 
* testcafe version:                   1.16.0
* node.js version:                    16.5.0
* command-line arguments:  testcafe chrome test.js
* browser name and version: Chrome 95
* platform and version:          macOS 10.15

**Comment by AndreyBelym** [comment]
The issue could be triggered by an invalid certificate on the client side. Likely it's not a TestCafe issue at all.
