### ISSUE TITLE
[docs] Add a description for dashboard options

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe#6674]
1. Topic "Dashboard options"

TestCafe Dashboard supports the following options:

**option:**
`token`

**type:**
string 

**description:**
authentication token for           
the particular project

**default value:**
specified in the TESTCAFE_DASHBOARD_AUTHENTICATION_TOKEN environment variable 

`buildId`
string
an id for merging several runs into one
''

`noScreenshotUpload`
boolean
prevents uploading screenshots to Dashboard
false

`noVideoUpload`
boolean
prevents uploading videos to Dashboard
false

2. Topic "Command Line Interface" (https://testcafe.io/documentation/402639/reference/command-line-interface):

-D, --dashboard <option=value[option2=value2,...]>
Specifies options of using TestCafe Dashboard

`testcafe chrome test.js --dashboard token=my_project_token,noScreenshotUpload=true`
`testcafe chrome test.js -D token=my_project_token,noScreenshotUpload=true`

See TestCafe Dashboard Options for details

3. Topic "Runner.dashboard Method"

Enabled TestCafe to store test run report in TestCafe Dashboard
`dashboard(options) → this`

Parameter "options" . Type "string". Description: Options for setting up TestCafe Dashboard. See "Dashboard options" for details.

4. Topic "Configuration File" (https://testcafe.io/documentation/402638/reference/configuration-file)
Enabled TestCafe to store test run report in TestCafe Dashboard
`dashboard`

```
{
    "dashboard": {
        "token": "my_project_token",
        "noVideoUpload": true
    }
}
```

CLI: `--dashboard`
ALI: `runner.dashboard`

**Comment by aleks-pro** [comment]
https://teams.microsoft.com/l/message/19:7e845d3e5e324502abae3417a2ac8c7c@thread.skype/1635335459152?tenantId=e4d60396-9352-4ae8-b84c-e69244584fa4&groupId=c3abb0f3-231c-4d87-b5a3-44925dc1d075&parentMessageId=1635335459152&teamName=TestCafe&channelName=Framework%20(Open%20source)&createdTime=1635335459152

**Comment by miherlosev** [comment]
We will not do this because the Dashboard release was declined.
