### ISSUE TITLE
A process in loop doesn't finish the test

### ISSUE THREAD

**Issue by Francysdeaguiar** [DevExpress/testcafe#6675]
I have a e2e with PayPal purchase, when I make the pay and I arrive in the Thank You page, my test doesn't finish. If  enter in the network, I see two process in loop.

Loop:
<img width="1240" alt="Captura de pantalla 2021-11-03 a las 16 49 15" src="https://user-images.githubusercontent.com/93668283/140094872-8870a355-b178-4693-8579-624be7fff78c.png">

Code:
![image](https://user-images.githubusercontent.com/93668283/140094987-d8512bd6-a7a0-4758-932d-1f838f759e8e.png)

Console:
![image](https://user-images.githubusercontent.com/93668283/140095091-cc2d8cdc-69e9-49c5-a94a-4e697eb4643e.png)

The last line, apparently doesn't execute and never finish the test. I was try validate the url and elements and never I can finish the test.

**Comment by Francysdeaguiar** [comment]
I was testing with .switchToMainWindow() and apparently the PayPal window is always open, but I can't see it.  If I do a console.log(url) I see the url of the sandbox but I see the thank you page.

**Comment by Francysdeaguiar** [comment]
Hi @miherlosev thanks for your reply. I have tried to update to the latest version, but when I want to run my test, I always see this error in the console. I have deleted the node_modules directory, and it doesn't work for me. Furthermore, I run with versions higher than 1.15.2, and it always gives the same error.

Error with versions v1.17.0, v1.16.1, v1.16.0 
![image](https://user-images.githubusercontent.com/93668283/140490621-1e497c88-7c3d-470c-b085-b93cde41537e.png)


Error with v1.15.3
![image](https://user-images.githubusercontent.com/93668283/140490700-6d4dd846-dacd-4556-8e87-dce74faf990a.png)


And with v1.15.2 it is executable and opens the testcafe interfaces.

**Comment by miherlosev** [comment]
The TestCafe team doesn't maintain the `gherkin-testcafe` module. You can address this issue in its repository.

If you can create a [simple example](https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue) with plain TestCafe syntax that reproduces the issue, please share it in this thread. Private information can be emailed to `support@devexpress.com`.
