### ISSUE TITLE
[docs] Document the 'experimentalDebug' option

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#6679]
See its description [here](https://teams.microsoft.com/l/message/19:7e845d3e5e324502abae3417a2ac8c7c@thread.skype/1631621459321?tenantId=e4d60396-9352-4ae8-b84c-e69244584fa4&groupId=c3abb0f3-231c-4d87-b5a3-44925dc1d075&parentMessageId=1631621459321&teamName=TestCafe&channelName=Framework%20(Open%20source)&createdTime=1631621459321).

**Comment by helen-dikareva** [comment]
DoD: short description how it works

**Comment by miherlosev** [comment]
Done
