### ISSUE TITLE
Page with iframe throws error on TestCafe 1.17.0

### ISSUE THREAD

**Issue by agataDeviniti** [DevExpress/testcafe#6681]
### What is your Scenario?

TestCafe 1.14.2: When trying to open page on Jira Cloud with iframe  everything works fine:
<img width="1480" alt="Zrzut ekranu 2021-11-9 o 10 11 13" src="https://user-images.githubusercontent.com/93976627/140895562-bd68a1d2-9807-4c7c-b1a6-c7d0521f6a44.png">
TestCafe 1.17.0: When trying to open page on Jira Cloud with iframe it throws error
<img width="1143" alt="Zrzut ekranu 2021-11-9 o 10 11 42" src="https://user-images.githubusercontent.com/93976627/140895630-0591b5d9-8f6b-4b27-8673-ecf175bcfc64.png">

This problem appears on Jira Cloud.

### What is the Current behavior?

On TestCafe 1.17.0 I receive error when navigating to page with iframe

### What is the Expected behavior?

I should not receive error when accessing page with iframe (as it is on TestCafe 1.14.2)

### What is your public website URL? (or attach your complete example)

My test environment: https://testcafe-example.atlassian.net

### What is your TestCafe test code?

```js
import { Selector } from 'testcafe';

fixture('TestCafe - bug on TestCafe 1.17.0').page(
    'https://testcafe-example.atlassian.net/',
);

test.meta({ key: 'testcafe' })(`Problem with iframe`, async (t) => {
    await t
        .click('form#form-login input#username')
        .typeText(
            'form#form-login input#username',
            'qadeviniti+testcafe@gmail.com',
        )
        .click('form#form-login button#login-submit')
        .typeText('input#password', 'testcafe123!')
        .click('form#form-login button#login-submit');
    await t
        .click('span[aria-label="Settings"]')
        .click('[href$="source=side_nav_find_new_addons"]');
    await t.click('[href$="rtm__get-started"]');
    await t
        .switchToIframe('iframe')
        .expect(Selector('[data-testid="Get-Started-select"]').visible)
        .ok();
});
````

### Steps to Reproduce

1. Ensure you have TestCafe 1.17.0 installed
2. Login to Jira Cloud
3. Navigate to page with iframe, for example page from app

### TestCafe version

1.17.0

### Command-line arguments

chrome -e test.ts

### Browser name(s) and version(s)

does not matter

**Comment by aleks-pro** [comment]
Hello @agataDeviniti,

Thank you for the example. I reproduced the issue. We will research it and will update this thread once we have any results.

**Comment by milan-easykad** [comment]
Hi @aleks-pro , any update on this? I am still on 1.15.0due to this issue

**Comment by aleks-pro** [comment]
Hello @milan-easykad,

There are no updates yet. Once we have any, we will post them here.

**Comment by milan-easykad** [comment]
@aleks-pro why does this issue has a label Need response? 
Do you need some examples of how to reproduce the issue?

**Comment by Aleksey28** [comment]
Hi @milan-easykad

It's a label for the TestCafe team. It means that somebody from the team should give a response.

**Comment by miherlosev** [comment]
https://github.com/DevExpress/testcafe/issues/6681

Hello @agataDeviniti,

The 'Page unavailable' message is displayed on the tested page.
![image](https://user-images.githubusercontent.com/4133518/207231125-c3883a52-86ae-454f-9973-e24f5d78c539.png)

Could you please update the example to make it working?
