### ISSUE TITLE
New window opening from an existing window is not carrying parent window cookie information

### ISSUE THREAD

**Issue by dineshpaduchuri** [DevExpress/testcafe#6684]
### What is your Scenario?

In my Application, 
1.Let say User is in parent window(Example: logged in to application and accessing some data)
2.User clicks on Print icon in the parent window, then our application opens a new separate window(url changes) of the selected content for print(Print is for example. there are many other functionalities which opens in a seperate window).

### What is the Current behavior?

In test cafe, currently the new window is opening in new incognito window with the URL redirected. So as this is new incongnito window my application will redirect user to the login page. 
From testcafe , the existing page cookies or watever relevant are not considered when new window is opened.

### What is the Expected behavior?

My Expectation is that the parent window cookies should be carried to the new window opened and displayed the expected content instead of going to login page

![image](https://user-images.githubusercontent.com/42802100/141096739-7a97008a-f032-4e7e-879f-96adb73ef4fc.png)
<img width="959" alt="Untitled" src="https://user-images.githubusercontent.com/42802100/141096855-c19ac90f-5b4c-4ce2-87e9-3bd7d6c99dd6.png">

### What is your public website URL? (or attach your complete example)

No public site URL

### What is your TestCafe test code?

**Sample Code:**
    await t.click(Selector('#aid_packComp').find('div').find('ul').find('li').find('a'));  -->This is where we are clicking on the link
    await t.wait(5000);
    await t.switchToIframe(Selector('iframe')) - we are switching to iframe 
    const body = Selector('body');
    await t.expect(body.textContent).eql('Request.Form params:Request.QueryString params:param1: %parameter1%param2: %parameter2%Details: Default URL')
    await t.switchToMainWindow(); and switching back to main window

Here new window is opened in incognito mode and our application considers that as a new window and redirects to login page of the application.

### Screenshots

<img width="959" alt="Untitled" src="https://user-images.githubusercontent.com/42802100/141097523-27b021ae-2d39-4f29-b713-b608833f5108.png">

### Steps to Reproduce

1.
2.
3.
As mentioned in the current behaviour

### TestCafe version

1.10.0

### Node.js version

v10.16.3

### Command-line arguments

testcafe chrome test.js

### Browser name(s) and version(s)

Chrome browser Version 95.0.4638.69 (Official Build) (64-bit)

### Platform(s) and version(s)

windows 10

**Comment by dineshpaduchuri** [comment]
I have installed latest version of Testcafe 1.17.1 and executed the same test, this time the new window is opened and closed immediately.

In older version, atleast the new window is opened and displayed but now it is getting closed automatically.

**Comment by AlexKamaev** [comment]
@dineshpaduchuri
We have an issue with multiple windows in v1.17.1. We are working on it. Please try to update your version to v1.16.1: [https://www.npmjs.com/package/testcafe/v/1.16.1](https://www.npmjs.com/package/testcafe/v/1.16.1)

**Comment by dineshpaduchuri** [comment]
After installing v1.16.1, i can see the new window opened and displayed but the same issue redirecting to the login page as the new window url is opened with new instance(i guess).

Manually, when i click on someaction which open new window will display the expected content. Only using testcafe i have this issue.

Please help

**Comment by AlexKamaev** [comment]
I didn't manage to create a sample that reproduces the described issue.
Please create a simple sample that we can easily run on our side in order to replicate the issue and research its cause. Without such a sample, we are not able to figure out what's going on and why this issue occurs.
