### ISSUE TITLE
.parent(cssSelector) return empty when using within shadow DOM

### ISSUE THREAD

**Issue by VietNguyenQuoc** [DevExpress/testcafe#6688]
### What is your Scenario?

I'm trying to filter the parents of a node with tag `div` by using `.parent('div')`

### What is the Current behavior?

No elements has been returned

### What is the Expected behavior?

Some elements must be returned like the way it behaves when using with light DOM

### What is your public website URL? (or attach your complete example)

https://jsfiddle.net/fc067gv1/7/

### What is your TestCafe test code?

index.js
```js
const { Selector } = require("testcafe");

fixture`Shadow DOM Example`.page`https://jsfiddle.net/fc067gv1/7/`;

test.timeouts({ pageLoadTimeout: 30000, pageRequestTimeout: 30000 })(
  "Filter parent with css selector when using shadow DOM",
  async (t) => {
    const outputIframe = Selector("iframe").withAttribute("name", "result");
    const host = Selector(() => document.querySelector("#host"));
    const shadow = host.shadowRoot();

    const type = shadow.find("span").withText("Salary");
    const container = type.parent("div");

    await t
      .wait(5000)
      .switchToIframe(outputIframe)
      .expect(type.exists)
      .ok()
      .expect(container.exists)
      .ok(); // This will fail
  }
);

test("Filter parent with css select when using light DOM", async (t) => {
  const outputIframe = Selector("iframe").withAttribute("name", "result");
  const host = Selector(() => document.querySelector("#host2"));

  const type = host.find("span").withText("Salary");
  const container = type.parent("div");

  await t
    .wait(5000)
    .switchToIframe(outputIframe)
    .expect(type.exists)
    .ok()
    .expect(container.exists)
    .ok();
});
```

### Steps to Reproduce

1. Run the test code

### TestCafe version

1.17.0

### Node.js version

v16.13.0

### Command-line arguments

testcafe chrome index.js  

### Browser name(s) and version(s)

Chrome 95.0.4638.69

### Platform(s) and version(s)

macOS 11.6

**Comment by dositec** [comment]
Hello,
Thank you for notifying us about the issue. We reproduced it.

Currently, I can recommend performing the following actions as a workaround:
replace this row:
`const container = type.parent("div");`

with the following row:
`const container = type.parent(node => node.tagName === 'DIV');`

We will try to fix the issue as soon as possible. Once we make progress, we will let you know.

**Comment by VietNguyenQuoc** [comment]
@dositec Thanks for quick respond. 
By the way I think `.parent().filter('div')` also suffers from this issue.

**Comment by dositec** [comment]
Thank you. We will check this behavior when working on the current issue.

**Comment by PavelMor25** [comment]
Hello @msvihaRA,
Please create a separate ticket using this [template](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&template=bug_report.yaml) and also share a [Minimal Working Example](https://testcafe.io/documentation/402636/faq/general-info?search#how-to-create-a-minimal-working-example-when-you-submit-an-issue) in that ticket so that the TestCafe team can research the issue and help you.
