### ISSUE TITLE
NetworkError: WorkerGlobalScope.importScripts: Failed to load worker script when opening page: twitch.tv

### ISSUE THREAD

**Issue by mccartyb1** [DevExpress/testcafe#6693]
### What is your Scenario?

I'd like to build some automation for twitch.tv, however there is an error when testcafe loads the page that blocks any subsequent automation.  

### What is the Current behavior?

When loading the page a JavaScript error occurs (more details in full report below):
JavaScript error details:
      NetworkError: WorkerGlobalScope.importScripts: Failed to load worker script

If I try using --skip-js-errors, it does skip the error.  However, most of the page does not load and is not functional.  

### What is the Expected behavior?

Page loads correctly and automation can act upon it.

### What is your public website URL? (or attach your complete example)

https://www.twitch.tv/

### What is your TestCafe test code?

import {Selector} from 'testcafe';

const loginButton = Selector("button").withAttribute("data-a-target", "login-button");

fixture("Crown Tests")
.page("https://www.twitch.tv/");

test("Crown Test1", async t => {
    await t
    .expect(loginButton.exists).ok()
});

### Your complete configuration file

package.json
_______________
{
  "dependencies": {
    "testcafe": "^1.17.1"
  }
}

### Your complete test report

 Running tests in:
 - Firefox 91.0 / Windows 10

 Crown Tests
 × Crown Test1

   1) A JavaScript error occurred on "https://www.twitch.tv/".
      Repeat test actions in the browser and check the console for errors.
      To ignore client-side JavaScript errors, enable the "--skip-js-errors" CLI option, or set the "skipJsErrors" configuration file property to "true".
      If the website only throws this error when you test it with TestCafe, please create a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      NetworkError: WorkerGlobalScope.importScripts: Failed to load worker script at http://10.119.127.175:1228/!s/https://static.twitchcdn.net/assets/amazon-ivs-wasmworker.min-4dcf5c30e7a36a636fd2.js (nsresult    
      = 0x804b001d)
          No stack trace available

      Browser: Firefox 91.0 / Windows 10

 1/1 failed (4s)

### Steps to Reproduce

1.  Run the provided script in testcafe (navigate to www.twitch.tv in testcafe)

### TestCafe version

1.17.1

### Node.js version

16.0.0

### Command-line arguments

testcafe firefox test/basic_twitch_open.js

### Browser name(s) and version(s)

Firefox 91.2.0, chrome 95.0.4638.69, Safari 15.1

### Platform(s) and version(s)

windows 10, Mac OS v11.6

### Other

- I have tested this on windows 10: firefox, chrome.  Mac OS v11.6: firefox, chrome, safari.  I am unable to load the page in any of these when using testcafe.
- I have also tried Cypress and am able to load the page without this issue so it seems specific to TestCafe.

**Comment by AlexanderMoiseev** [comment]
Hello, 

Thank you for your input. We have reproduced the problem and need some time to investigate it, please stay tuned.

**Comment by mccartyb1** [comment]
Hello.  Just checking in to see if there has been any update on this.  Thanks!

**Comment by miherlosev** [comment]
Hi @mccartyb1,

This issue is not reproduced with combination of `testcafe@3.0.1` and the Google Chrome browser. Feel free to reopen this issue if you encounter it in other browsers.
