### ISSUE TITLE
Regression: New window getting closed immidately after opening it in TestCafe 1.7.0 and 1.7.1

### ISSUE THREAD

**Issue by jiteshsojitra** [DevExpress/testcafe#6695]
Regression bug after TestCafe 1.16.1:

### What is your Scenario?

Test opens new window but after certain moment it is getting closed.

### What is the Current behavior?

New window should not be closed immediately.

### What is the Expected behavior?

New window should be remained open. This issue was not there in TestCafe 1.16.1.

### What is your public website URL? (or attach your complete example)

Please run any code which opens new window and verify new window url. Execute sample code for new window.

### What is your TestCafe test code?

```
// Verify new window content

const initialWindow = await t.getCurrentWindow();

try {
	await calendar.panel.clickEventLocation();
	const url = await t.eval(() => document.documentURI);
	console.log(jitsiMettingURL);
	await t.expect(url).eql(jitsiMettingURL, 'Verify new window url');
} finally {
	await t.switchToWindow(initialWindow);
}
		
```

### Steps to Reproduce

- Test launches browser
- Click to link which opens new window
- Verify new window URL

### TestCafe version

1.7.0 and 1.7.1 both

### Node.js version

v14.16.0

### Command-line arguments

node tests/testcafe/utils/testcafe-run.js -T yourtest

### Browser name(s) and version(s)

All

### Platform(s) and version(s)

All

**Comment by zubarlec** [comment]
Seems to be broken with https://github.com/DevExpress/testcafe/pull/6573

**Comment by AlexKamaev** [comment]
https://github.com/DevExpress/testcafe/issues/6680
