### ISSUE TITLE
Test run is slowed down tremendously if your file path contains Slipstream

### ISSUE THREAD

**Issue by KingM1** [DevExpress/testcafe#6706]
### What is your Scenario?

My folder structure has a root directory called "Slipstream" (e.g. `Slipstream/e2e/test-spec.js` ). If I try to run this test, it takes about 3 minutes to run a simple test. On older machines, it doesn't even complete the run, and it freezes the entire machine to the point of needing a restart. If I rename the folder to anything else (e.g. `testcafe-examples/e2e/test-spec.js`), the test runs in about 10 seconds.

### What is the Current behavior?

Tests run so slow to the point of being unusable (on older machines, it even freezes the entire machine to the point where you have to force restart the computer to reset)

### What is the Expected behavior?

Should run the same as when "Slipstream" is not in the file path

### What is your public website URL? (or attach your complete example)

Can reproduce with the test-cafe examples folder: https://github.com/DevExpress/testcafe-examples
When you pull down the repository, rename "testcafe-examples" folder to "Slipstream"

### What is your TestCafe test code?

Using the example repo provided by testcafe

### Steps to Reproduce

1. git clone https://github.com/DevExpress/testcafe-examples.git
2. mv testcafe-examples Slipstream
3. cd Slipstream
4. npm install
5. npm test

### TestCafe version

1.9.2 (also seeing it when we upgrade to 1.17.1)

### Node.js version

14.15.4

### Command-line arguments

npm test

### Browser name(s) and version(s)

All browsers (Safari is the worst offender, but also happens on Chrome + Firefox)

**Comment by dositec** [comment]
I tried to reproduce the problem on my side many times, but without success. I recorded a [screencast ](https://www.screencast.com/t/To7GMzKAPgSj)to illustrate my steps to reproduce the problem.

Could you please review the [screencast](https://www.screencast.com/t/To7GMzKAPgSj) and point out what I am doing wrong? Also, please specify the OS that you are using and its version and clarify what you mean by "older machines". To reproduce the problem, we need to know their tech specs, OS, and their versions.

A sample screencast demonstrating freezing would be very helpful. If possible, record a video showing it in action. To do this, you can use the [Jing software](https://www.techsmith.com/jing-tool.html) or external device (e.g., a cell phone).

I look forward to your response.

**Comment by KingM1** [comment]
Unfortunately, I don't have the computer that freezes anymore (I believe it was a 2015 Macbook Pro). 

Below is the video of my issue. You can see that when I don't have Slipstream in the folder name, it takes 20 seconds to start the first test. Once I rename the folder to have Slipstream, it takes 1 minute 20 seconds to start the first test (with our own private repo, we have steps that we do before the test, so it takes even longer to boot up, about 3-4 minutes)

With that reproduction, I'm on Macbook Pro 2019 Big Sur.

https://www.screencast.com/t/WZILOdlo

Also worth noting, it seems to happen when the directory has "ps". Seeing it happen when the folder is:
- Slipstream (but not Sliptream)
- ps (but not sp)
- raps (but not rasp)

So this is a screencast of running on Safari, and going from "Sliptream" (which works), "ps" (which hangs), and "sp" (which works)
https://www.screencast.com/t/ubJ5DNXVojv

Sorry, I know this is a very bizarre issue. I'll play around with it some more to see if there's anything else I can pin down.

**Comment by dositec** [comment]
Thank you for additional info and the screencasts.

We tried to reproduce the problem on our side using the steps and information from your screenсasts, but unfortunately without success.
We have recorded the screencast:
[https://user-images.githubusercontent.com/10861668/142849453-a7b9610d-96b2-4246-86de-66ce861449ae.mov](https://user-images.githubusercontent.com/10861668/142849453-a7b9610d-96b2-4246-86de-66ce861449ae.mov)
that shows our attempts to reproduce the problem in action on a Mac.
At this stage, we don't understand the cause of such incorrect behavior on your side, but we suppose that the issue can be related to the local settings of your Mac.
We will keep the issue on our radar and if we have any ideas about its cause, we will notify you about this in the current ticket.

I'll play around with it a bit more to see if there's anything else I can pin down.

Thx, if you find any steps to narrow down the problem, please let us know.
