### ISSUE TITLE
Implement test run warnings

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#671]
Warnings should appear in reports. Currently we should add warning for the following situations:
- Test directory is not specified and there was an attempt to take screenshot
- Where was an error during screenshot creation
- Attempt to take screenshot on remote browser

- [x] Move all browser manipulation logic to the browser manipulation queue
- [x] Create warnings infrastructure in test run

- [x] Create temporary local JSON reporter which supports new feature so we can run functional tests

- [x] Make warnings global per task

- [x] Update reporting system
  - [x] Plugin host
  - [x] spec
  - [x] list
  - [x] minimal
  - [x] xunit
  - [x] json
  - [x] generator

- [x] Implement warnings
   - [x] Test directory is not specified and there was an attempt to take screenshot
   - [x] Where was an error during screenshot creation 
   - [x] Attempt to perform browser manipulation on Linux machine
   - [x] Warning on attempt to perform browser manipulation with browser provider which doesn't support them, e.g. remote browsers (blocking on #573, move to separate issue)

- [x] Upgrade all reporters
- [x] Remove temporary local JSON reporter (in addition move `screenshots` from `runner` dir)

**Comment by AndreyBelym** [comment]
Also, IMHO it worth to note that we need to show the full text of the error (in case of screenshot error), and maybe some ways to overcome the problem.

**Comment by inikulin** [comment]
@VasilyStrelyaev @MargaritaLoseva 
Breaking changes that affects documentation:
- Error format changed, warnings added (new reporter screenshots required)
- Generator/reporter - `reportTestDone` method now accepts two args: `name` and `testRunInfo` object: https://github.com/DevExpress/testcafe/blob/master/src/reporter/index.js#L35
- Generator/reporter - `reportTaskDone` now accepts array of warning strings as third argument

**Comment by inikulin** [comment]
Closed via #692
