### ISSUE TITLE
Cannot select dropdown list item in XAF application

### ISSUE THREAD

**Issue by pavsenin** [DevExpress/testcafe#6712]
### What is your Scenario?

Tried to select dropdown list item in simple XAF application. Please see the projects attached in https://supportcenter.devexpress.com/internal/ticket/details/T1046147

### What is the Current behavior?

The test fails with the 'The element that matches the specified selector is not visible.' error.

### What is the Expected behavior?

Test passes.

### What is your public website URL? (or attach your complete example)

No

### What is your TestCafe test code?

import { Selector } from "testcafe";
import Navbar from "../page-objects/components/navbar";
import StaffPage from '../page-objects/pages/StaffPage';

const dataSet = require('../data/staff.json');
const staffPage = new StaffPage();
const navbar = new Navbar();

// prettier-ignore
fixture `Staff Tests`
    .page `http://localhost:44222/`

dataSet.forEach(data => {
    // var today = new Date();
    // var strToday = (today.getMonth()+1)+'/'+today.getDate()+'/'+today.getFullYear();
    // data.date = strToday;

    test
    ("User can add a new staff record", async t => {
        await t.setTestSpeed(0.5);
        // Get Selectors
        await t.maximizeWindow()
        
        // go to new client page
        navbar.gotoStaffList()

        // Actions
        await t.click(navbar.listNewAction)        
            .typeText(staffPage.nameInput,data.name)
            .click(staffPage.ethnicityDropDown)
        
        console.log(data.ethnicity);

        await staffPage.SelectEthnicity(data.ethnicity)

        // await t.click(navbar.saveAndClose)
            
        // Asserts
        await t.expect(staffPage.nameView.withText(data.name).exists).ok()            
        
    })
})

### Steps to Reproduce

1. Build and run the XAFTestCafeDemo app
2. Run tests from the XAFTestCafeTests app

### TestCafe version

1.17.1

### Command-line arguments

testcafe chrome XAFTests/tests/staff.test.js

**Comment by pavsenin** [comment]
Note the last comment from customer:

OK. I did just figure out another way to get the value into this dropdown input. Rather than using clicks I just used typetext() with this selector:
'input[id$="xaf_dviEthnicity_Edit_I"]'

So if you can't figure out the how to get working with click actions it's not a big deal.

**Comment by Aleksey28** [comment]
It occurs because you tried to click on the 'ethnicityDropDown' twice. First, it occurs in the test file itself after the typing name and then in the 'SelectEthnicity' method of the 'StaffPage'.
```js
//...
await t.click(navbar.listNewAction)        
    .typeText(staffPage.nameInput,data.name)
    .click(staffPage.ethnicityDropDown) // <-- First
    
await staffPage.SelectEthnicity(data.ethnicity)
//...
```

```js
//...
async SelectEthnicity(ethnicityName) {
    await t.click(this.ethnicityDropDown) // <-- Second
    var ethnicityTable = Selector('table[id$="Ethnicity_Edit_DDD_L_LBT"]')
//...
```
