### ISSUE TITLE
Parameters not available for runner

### ISSUE THREAD

**Issue by Sabou44** [DevExpress/testcafe#6713]
### What is your Scenario?

Hi,

In TestCafe v1.17.1 Release Notes, it's said that it's possible to use new options to configure the runner. I would like to use the testExecutionTimeout and runExecutionTimeout options

runner.run({ testExecutionTimeout: 360000 });
But I get the message :

```
TSError: ⨯ Unable to compile TypeScript:
runner.ts:66:24 - error TS2345: Argument of type '{ testExecutionTimeout: number; }' is not assignable to parameter of type 'Partial<RunOptions>'.
 Object literal may only specify known properties, and 'testExecutionTimeout' does not exist in type 'Partial<RunOptions>'.
```

Is this option already available?
And if not, when will it be available?

I am using the latest stable release v1.17.1

### What is the Current behavior?

```
TSError: ⨯ Unable to compile TypeScript:
runner.ts:66:24 - error TS2345: Argument of type '{ testExecutionTimeout: number; }' is not assignable to parameter of type 'Partial<RunOptions>'.
 Object literal may only specify known properties, and 'testExecutionTimeout' does not exist in type 'Partial<RunOptions>'.
```

### What is the Expected behavior?

run

### What is your public website URL? (or attach your complete example)

[testExecutionTimeout.zip](https://github.com/DevExpress/testcafe/files/7581907/testExecutionTimeout.zip)

### What is your TestCafe test code?

fixture`Simple test`;

test('Go to google', async t => {
    await t.navigateTo('https://www.google.com');
});

### Steps to Reproduce

1. npm i
2. ts-node runner.ts

### TestCafe version

1.17.1

### Command-line arguments

ts-node runner.ts

**Comment by viktoria2506** [comment]
Thank you for submitting this issue.
As a workaround, you can add `//@ts-ignore` before the error line to suppress the compilation error.

**Comment by Sabou44** [comment]
Thanks @viktoria2506 for this workaround.
