### ISSUE TITLE
IE Crashes when clicking an `option` node from a long `select` list

### ISSUE THREAD

**Issue by ccheraa** [DevExpress/testcafe#6717]
### What is your Scenario?

Trying to click an `option` node by finding it using `Selector('option').withExactText('Option 1')`.

### What is the Current behavior?

- The browser freezes for a long time then crashes without any error message.
- TestCafe says that the browser got closed.

### What is the Expected behavior?

The option is selected

### What is your public website URL? (or attach your complete example)

This problem happened on a privately developed project that can't be shared.
The project uses `jQuery` and `jQueryUI`.

### What is your TestCafe test code?

This crashes the browser:
```typescript
t.click(Selector('#modal #select-input option[value=user]'))
```
This works without a problem:
```typescript
t.click(Selector('#modal #select-input option').withExactText('User'))
```

### Your complete configuration file

No special config

### Steps to Reproduce

Unfortunately, we've tried to isolate the problem but we couldn't reproduce it outside of the context.
But we know that the browser doesn't crash if the `select` node doesn't have a lot of options.

### TestCafe version

1.17.0

### Node.js version

16.13.0

### Command-line arguments

yarn testcafe ie --skip-js-errors -L tests/test.ts

### Browser name(s) and version(s)

IE11

### Platform(s) and version(s)

Windows 10

### Other

If you run the same test on Edge (non chromium based Edge), it freezes for a long time, after that, sometimes it finishes the test, sometimes Edge crashes, and on rare occasions Windows restarts.

**Comment by dositec** [comment]
[https://github.com/DevExpress/testcafe/issues/6717](https://github.com/DevExpress/testcafe/issues/6717)

I tried to reproduce the problem locally with the help of the following "test.js" and "testhtml.htm" files, but unfortunately without success:
**test.js**

import from 'testcafe';

    fixture`Getting Started`
    .page`./testhtml.html`;
    
    test('test', async t => {
      const selectElement = Selector('#select-input');
      const option = Selector('#select-input option[value=user]');
      await t.click(selectElement).click(option);
    });


**testhtml.html**

    <!DOCTYPE html>
      <html>
          <body>
           <div id="modal">
              <select id="select-input">
                <option value="first">First</option>
                <option value="user">User</option>
                <option value="second">Second</option>
                <option value="third">Third</option>
              </select>
            </div>
          </body>
      </html>


Could you please update the files so the problem can be reproduced in these, and provide us with the changes. It should help us diagnose the cause of the problem and fix it.
