### ISSUE TITLE
Click on an image do not work with the actual version 1.17.1

### ISSUE THREAD

**Issue by DimitriGer** [DevExpress/testcafe#6720]
### What is your Scenario?

When you click on the image (a map), you create a new customer position.
This works only until version 1.12.0. After that version no click is done. I use the npm version 6.14.10. 

You can easy test it with this typescript code:

import { Selector, t } from "testcafe"

let page = 'https://developer.myptv.com/'
let fixtureName = 'fixture: ClickOnMap.ts'

fixture(fixtureName)
.page(page)

test('test: click on map', async t =>  
{
   await t.maximizeWindow()

   await t.click(Selector('#Header').find('a').withExactText('Documentation'))
   await t.click(Selector('#Header').find('a').withExactText('Route Optimization API'))

   await t.click(Selector('a').withExactText('Code Samples'))
   await t.click(Selector('a').withExactText('Roundtrip'))
   await t.click(Selector('a').withExactText('Create a roundtrip'))

   await t.hover(Selector('#requestMapDiv'))
   await t.click(Selector('#requestMapDiv').find('a').withAttribute('class', 'leaflet-control-zoom-out'))
   await t.click(Selector('#requestMapDiv'))

   await t.hover(Selector('#site_2_id'))
   await t.click(Selector('div').withAttribute('title', 'Delete customer'))

   // check
   await t.expect(Selector('#site_2_id').exists).notOk('Second customer still exist in list')

   await t.wait(2000)
})

### What is the Current behavior?

No click (only move) is done. 
Screenshot: version 1.17.1:

![Screenshot - version 1 17 1](https://user-images.githubusercontent.com/94928386/143211965-3a535e4a-c9f6-4e0c-a4f0-30a3a7ee6ecb.png)

### What is the Expected behavior?

Click is done.
Screenshot: version 1.12.0:

![Screenshot - version 1 12 0](https://user-images.githubusercontent.com/94928386/143212325-97d86c53-e5e2-4bd7-9634-a2460e78d0d0.png)

### What is your public website URL? (or attach your complete example)

https://developer.myptv.com

### What is your TestCafe test code?

import { Selector, t } from "testcafe"

let page = 'https://developer.myptv.com/'
let fixtureName = 'fixture: ClickOnMap.ts'

fixture(fixtureName)
.page(page)

test('test: click on map', async t =>  
{
   await t.maximizeWindow()

   await t.click(Selector('#Header').find('a').withExactText('Documentation'))
   await t.click(Selector('#Header').find('a').withExactText('Route Optimization API'))

   await t.click(Selector('a').withExactText('Code Samples'))
   await t.click(Selector('a').withExactText('Roundtrip'))
   await t.click(Selector('a').withExactText('Create a roundtrip'))

   await t.hover(Selector('#requestMapDiv'))
   await t.click(Selector('#requestMapDiv').find('a').withAttribute('class', 'leaflet-control-zoom-out'))
   await t.click(Selector('#requestMapDiv'))

   await t.hover(Selector('#site_2_id'))
   await t.click(Selector('div').withAttribute('title', 'Delete customer'))

   // check
   await t.expect(Selector('#site_2_id').exists).notOk('Second customer still exist in list')

   await t.wait(2000)
})

### Steps to Reproduce

1. Run test with actual version.
2. Run test with version 1.12.0

### TestCafe version

1.1.7.1

### Node.js version

14.15.4

### Command-line arguments

testcafe "chrome" .\*.ts -e

### Browser name(s) and version(s)

Chrome 96.0.4664.45 

### Platform(s) and version(s)

Windows 10

**Comment by AlexanderMoiseev** [comment]
Hello, 

Thank you for your input. We have reproduced the problem. Please stay tuned.
