### ISSUE TITLE
It's taking a long time to load the iframe and causes test to fail

### ISSUE THREAD

**Issue by letemad** [DevExpress/testcafe#6726]
### What is your Scenario?

Our application has a screen and at some point it needs to load a third party iframe.

### What is the Current behavior?

It takes a long time to load the third party iframe using the latest version of Testcafe `1.17.1`
Note that it can load it using Testcafe version `1.14.0`

### What is the Expected behavior?

It should load the third party iframe as fast as version `1.14.0`.

### What is your public website URL? (or attach your complete example)

[Testcafe.zip](https://github.com/DevExpress/testcafe/files/7605222/Testcafe.zip)

### What is your TestCafe test code?

[Testcafe.zip](https://github.com/DevExpress/testcafe/files/7605224/Testcafe.zip)

### Screenshots

![Screen Shot 2021-11-25 at 4 08 13 PM](https://user-images.githubusercontent.com/9958263/143500287-2905239f-d49c-4416-9881-e89564a681f7.png)

### Steps to Reproduce

1. Unzip the Testcafe.zip
2. Open it with VSCode
3. Run the 'Airfilter Sign up Test'

### TestCafe version

1.17.1

### Node.js version

v12.15.0

### Command-line arguments

testcafe chrome ./e2e/tests/signup.js -e

### Browser name(s) and version(s)

Chrome 96.0.4664.55

### Platform(s) and version(s)

macOS 10.15.2

**Comment by AlexanderMoiseev** [comment]
Hi, 

Thank you for your input. We have reproduced the problem. Please stay tuned.

**Comment by letemad** [comment]
> Hi,
> 
> Thank you for your input. We have reproduced the problem. Please stay tuned.

Cool, thank you @AlexanderMoiseev

**Comment by AlexanderMoiseev** [comment]
Hi,

You're welcome, @letemad

**Comment by letemad** [comment]
Any update on this issue? It's blocking us from upgrading Testcafe to latest version.

**Comment by nechu16** [comment]
It has been many months since last update. Any updates on this issue? This is still blocking us from upgrading Testcafe to the latest version. We recently attempted to update to v1.18.6 and still encountered issues.

**Comment by AlexKamaev** [comment]
At this moment, we do not have any updates on this issue. I'll prioritize it.

**Comment by Elza-C** [comment]
We took a run using proxyless mode in v2.3.0 and our web application is not compatible with proxyless mode. Tests are failing at authentication.

**Comment by AlexKamaev** [comment]
@Elza-C
The proxyless mode is one of our top-priority tasks at this moment. We will really appreciate it if you share your usage scenario and sample where the issue is reproduced. Please use the following link to create a new ticket: [https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&template=bug_report.yaml](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&template=bug_report.yaml)
