### ISSUE TITLE
Cannot click on element using Chrome Headless

### ISSUE THREAD

**Issue by mishmaccas** [DevExpress/testcafe#6739]
### What is your Scenario?

Currently many of our tests are failing when they log into our customer account page and attempt to click on a link in chrome headless browser.

I need to know if this is a bug or if something NQR about our webpage links  because before these tests were rock solid.
![screenshots](https://user-images.githubusercontent.com/15898223/143955246-cc687815-b4cc-4188-83f4-9807b256d0c1.png)

### What is the Current behavior?

TestCafe cannot find the elements on this Account page when running chrome headless mode.
I test to see if the element exists and I get this error
**AssertionError: expected false to be truthy**

In normal Chrome, Firefox or Edge the tests pass.

For example the element selector I want to click is like this.
`#addrBook > button > span`

i have tried three different selectors but they all fail in chrome headless
```
addressBook: Selector("span").withText("Address Book"),
    addressBookLink: Selector("li#addrBook>button"),
    addrBook: Selector("#addrBook"),

```

### What is the Expected behavior?

I expect i can see that the element is visible and I can click on it when running chrome headless

### What is your public website URL? (or attach your complete example)

https://acceptance.aesop.com/au/

Refer to test code in GitHub to run the test with the Http Auth included

### What is your TestCafe test code?

   await t
        //.maximizeWindow()
        .click(locators.newLogin(), {
            offsetX: 5,
            offsetY: 5
        })
        .typeText(locators.emailaddress(), 'test@aesop.com')
        .pressKey('enter')
        .typeText(locators.password(), 'Welcome1')
        .pressKey('enter')
        .pressKey('enter')
        .takeScreenshot("./screenshots")
        // .expect(locators.addressBook().exists).ok()
        // .click(locators.addressBook())
        // .expect(locators.addressBookLink().exists).ok()
        // .click(locators.addressBookLink())
        .expect(locators.addrBook().exists).ok()
        .click(locators.addrBook())
        .takeScreenshot("./screenshots")
        .expect(locators.shippingAddressHeader().visible).ok()

### Your complete configuration file

{
    "skipJsErrors": true,
    "skipUncaughtErrors": true,
    "selectorTimeout": 10000,
    "assertionTimeout": 10000,
    "concurrency": 1,
    "quarantineMode": false,
    "screenshots": {
        "path": "screenshots/",
        "fullPage": false,
        "takeOnFails": true
    }
}

### Your complete test report

> Executing task: npm run test1-fails-headless <

> test1@1.0.0 test1-fails-headless
> testcafe chrome:headless ./tests/login.js --speed 0.5

 Running tests in:
 - Chrome 96.0.4664.55 / macOS 10.15.7

 Login Aesop
 ✖ Address Book

   1) AssertionError: expected false to be truthy

      Browser: Chrome 96.0.4664.55 / macOS 10.15.7

         26 |        .takeScreenshot("./screenshots")
         27 |        // .expect(locators.addressBook().exists).ok()
         28 |        // .click(locators.addressBook())
         29 |        // .expect(locators.addressBookLink().exists).ok()
         30 |        // .click(locators.addressBookLink())
       > 31 |        .expect(locators.addrBook().exists).ok()
         32 |        .click(locators.addrBook())
         33 |        .takeScreenshot("./screenshots")
         34 |        .expect(locators.shippingAddressHeader().visible).ok()
         35 |
         36 |});

         at <anonymous> (/Users/michelle.macdonald/digital/test-simple-purchase/tests/login.js:31:45)
         at asyncGeneratorStep (/Users/michelle.macdonald/digital/test-simple-purchase/tests/login.js:1:114)
         at _next (/Users/michelle.macdonald/digital/test-simple-purchase/tests/login.js:1:452)
         at <anonymous> (/Users/michelle.macdonald/digital/test-simple-purchase/tests/login.js:1:617)
         at <anonymous> (/Users/michelle.macdonald/digital/test-simple-purchase/tests/login.js:1:358)
         at <anonymous> (/Users/michelle.macdonald/digital/test-simple-purchase/tests/login.js:12:5)

 1/1 failed (37s)

 Warnings (1):
 --
  Was unable to take a screenshot due to an error.

  Error: Unexpected end of input
      at module.exports.ChunkStream._end
  (/Users/michelle.macdonald/digital/test-simple-purchase/node_modules/pngjs/lib/chunkstream.js:100:7)
      at module.exports.ChunkStream._process
  (/Users/michelle.macdonald/digital/test-simple-purchase/node_modules/pngjs/lib/chunkstream.js:203:12)
      at module.exports.ChunkStream.end
  (/Users/michelle.macdonald/digital/test-simple-purchase/node_modules/pngjs/lib/chunkstream.js:90:10)
      at exports.PNG.PNG.end
  (/Users/michelle.macdonald/digital/test-simple-purchase/node_modules/pngjs/lib/png.js:98:16)
      at exports.PNG.PNG.parse
  (/Users/michelle.macdonald/digital/test-simple-purchase/node_modules/pngjs/lib/png.js:88:8)
      at Object.readPng
  (/Users/michelle.macdonald/digital/test-simple-purchase/node_modules/testcafe/src/utils/promisified-functions.js:25:9)
      at BrowserProviderPluginHost.takeScreenshot
  (/Users/michelle.macdonald/digital/test-simple-purchase/node_modules/testcafe/src/browser/provider/built-in/dedicated/base.js:90:30)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at BrowserProvider.takeScreenshot
  (/Users/michelle.macdonald/digital/test-simple-purchase/node_modules/testcafe/src/browser/provider/index.ts:401:13)
      at Capturer._takeScreenshot
  (/Users/michelle.macdonald/digital/test-simple-purchase/node_modules/testcafe/src/screenshots/capturer.js:116:9)
The terminal process "bash '-c', 'npm run test1-fails-headless'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

### Steps to Reproduce

1. Go to the GitHub Repo 
https://github.com/mishmaccas/test-simple-purchase

Currently @Dmitry-Ostashev  has access to this simple repo

2. Run the script that fails
 "test1-fails-headless": "testcafe chrome:headless ./tests/login.js --speed 0.5",
    
3. Run the script that passes
"test2-passes-nonheadless": "testcafe chrome ./tests/login.js --speed 0.5",

### TestCafe version

1.17.1

### Node.js version

17.1.0

### Command-line arguments

Run scripts in package.json

**Comment by Dmitry-Ostashev** [comment]
@mishmaccas I reviewed your project and found two possible causes of the issue:

1. The `addrBook` selector is defined twice in the "selectors.js" file (see lines 105 and 112).
2. The web page markup depends on window size. In headless mode, the browser window is wider than in headful mode. So, the correct selector in headful mode becomes incorrect in headless mode.


I added the `t.resizeWindow` action to make the page look the same in different modes, and the test is passed in both cases.

**Comment by mishmaccas** [comment]
@Dmitry-Ostashev  Thank you so much for looking into this.      I didn't realise about the window size. I am using "chrome:headless --no-sandbox --window-size=1200,800" and it works a treat so far, I am testing it out on the real framework
