### ISSUE TITLE
Second Window does not stay open with .openWindow() 

### ISSUE THREAD

**Issue by dsaINTELE** [DevExpress/testcafe#6744]
### What is your Scenario?

I would like to have two seperate window instances open by Testcafe.

### What is the Current behavior?

The initial Window opens as expected. Though, when the method .openWindow() is executed, a Window is opened and rapidly closed and reopened again. This goes on for ca. 10 seconds. Is have tested this with the exact example code provided by testcafe (https://testcafe.io/documentation/402694/reference/test-api/testcontroller/openwindow).

### What is the Expected behavior?

I expected the second Window to stay open for further operations.

### What is your public website URL? (or attach your complete example)

Tested with testcafe's example code: https://testcafe.io/documentation/402694/reference/test-api/testcontroller/openwindow

### What is your TestCafe test code?

import { Selector } from 'testcafe';

fixture `Example page`
    .page `http://www.example.com/`;

test('Open the TestCafe website', async t => {
    await t
        .openWindow('http://devexpress.github.io/testcafe')
        .openWindow('./documentation');
});

### Steps to Reproduce

1. Create Example file https://testcafe.io/documentation/402694/reference/test-api/testcontroller/openwindow
2. Execute example file with "testcafe chrome .\path\file.js"

### TestCafe version

1.17.1

### Node.js version

v16.13.0

### Command-line arguments

testcafe chrome  .\e2e\openwindowtest.js

### Browser name(s) and version(s)

Chrome 96.0.4664.45 (Official build) (64-Bit)

### Platform(s) and version(s)

Windows 10 20H2

**Comment by Khartir** [comment]
I think I have a similar bug: I have a test that clicks on a link, that opens a new window (`target="_blank"`). Prior to version 1.17.0, the window was opened and further tests were possible. With version 1.17.0 and greater the windows is opened and immediately closed, failing tests that try to validate the content of the new window. This is the case for Chrome, Chromium and Firefox, both headless and normal mode.

**Comment by Khartir** [comment]
I just realized that my issue is most likely #6680 and not this. Sorry for the noise.

**Comment by AlexKamaev** [comment]
@dsaINTELE @Khartir
I researched this behavior. The cause of this issue is also #6680

Please try checking [https://www.npmjs.com/package/testcafe/v/1.17.2-alpha.2](https://www.npmjs.com/package/testcafe/v/1.17.2-alpha.2)
