### ISSUE TITLE
Firefox tests are terminated along with JavaScript "too much recursion" error occurrence

### ISSUE THREAD

**Issue by PierreRott** [DevExpress/testcafe#6747]
### What is your Scenario?

I would like to run the test within our application on Firefox browser.
Test is terminated along with error in console (see section "Current behavior" below).
The similar issue was reported, but it was unfortunately closed: https://github.com/DevExpress/testcafe/issues/6578
for missing minimal working example.
The size of our application is approximately 35Mb.
I noticed the issue on v. 1.16.1. and 1.17.1.
Everything works well on v. 1.15.0.
There are no issues on Edge or Chrome at all.

### What is the Current behavior?

Running test on Firefox browser leads to termination of the test.
Error appears in console:

```
   1) A JavaScript error occurred on "http://localhost:8080/accordion-item".
      Repeat test actions in the browser and check the console for errors.
      To ignore client-side JavaScript errors, enable the "--skip-js-errors" CLI option, or set the "skipJsErrors" configuration file property to "true".
      If the website only throws this error when you test it with TestCafe, please create a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      too much recursion
      e/</Sh</e.prototype._replaceUrlAttributes@http://172.28.3.110:50328/hammerhead.js:9:1687
      e/</Sh</e.prototype.process@http://172.28.3.110:50328/hammerhead.js:9:923
      e/</lf</t._processTextContent@http://172.28.3.110:50328/hammerhead.js:10:24481
      e/</lf</t.prototype._prepareNodesForInsertion@http://172.28.3.110:50328/hammerhead.js:10:18797
      e/</lf</t.prototype._addNodeCore@http://172.28.3.110:50328/hammerhead.js:10:18217
      appendChild@http://172.28.3.110:50328/hammerhead.js:10:20972
      S@http://localhost:8080/scripts.f9c6a0ac383dd1b470f8.js:2:5926
      B@http://localhost:8080/scripts.f9c6a0ac383dd1b470f8.js:2:4716
      O@http://localhost:8080/scripts.f9c6a0ac383dd1b470f8.js:2:2613
      A.exports@http://localhost:8080/scripts.f9c6a0ac383dd1b470f8.js:2:5197
      @http://localhost:8080/scripts.f9c6a0ac383dd1b470f8.js:2:6483
      N@http://localhost:8080/scripts.f9c6a0ac383dd1b470f8.js:2:146
      @http://localhost:8080/scripts.f9c6a0ac383dd1b470f8.js:2:6409
      N@http://localhost:8080/scripts.f9c6a0ac383dd1b470f8.js:2:146
      @http://localhost:8080/scripts.f9c6a0ac383dd1b470f8.js:2:6362
      N@http://localhost:8080/scripts.f9c6a0ac383dd1b470f8.js:2:146
      @http://localhost:8080/scripts.f9c6a0ac383dd1b470f8.js:2:950
      @http://localhost:8080/scripts.f9c6a0ac383dd1b470f8.js:2:959
```
Running the same test on Edge or Chrome browser does not cause any issues.

### What is the Expected behavior?

Running test on Firefox should not lead to termination of the test.

### What is your public website URL? (or attach your complete example)

n/a

### What is your TestCafe test code?

```
fixture`Firefox test`
    .page(`http://localhost:8080/button`);
test.only('Should execute test on Firefox browser', async () => {
    await t.click(Selector('#basicButton'));
});
```

### Your complete test report

```
$ testcafe firefox:headless **.e2e-spec.ts
 Running tests in:
 - Firefox 94.0 / Windows 10

 Firefox test
 × Should execute test on Firefox browser

   1) A JavaScript error occurred on "http://localhost:8080/button".
      Repeat test actions in the browser and check the console for errors.
      To ignore client-side JavaScript errors, enable the "--skip-js-errors" CLI option, or set the "skipJsErrors" configuration file property to "true".
      If the website only throws this error when you test it with TestCafe, please create a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      too much recursion
      e/</Sh</e.prototype._replaceUrlAttributes@http://172.28.3.110:51660/hammerhead.js:9:1687
      e/</Sh</e.prototype.process@http://172.28.3.110:51660/hammerhead.js:9:923
      e/</lf</t._processTextContent@http://172.28.3.110:51660/hammerhead.js:10:24481
      e/</lf</t.prototype._prepareNodesForInsertion@http://172.28.3.110:51660/hammerhead.js:10:18797
      e/</lf</t.prototype._addNodeCore@http://172.28.3.110:51660/hammerhead.js:10:18217
      appendChild@http://172.28.3.110:51660/hammerhead.js:10:20972
      S@http://localhost:8080/scripts.f9c6a0ac383dd1b470f8.js:2:5926
      B@http://localhost:8080/scripts.f9c6a0ac383dd1b470f8.js:2:4716
      O@http://localhost:8080/scripts.f9c6a0ac383dd1b470f8.js:2:2613
      A.exports@http://localhost:8080/scripts.f9c6a0ac383dd1b470f8.js:2:5197
      @http://localhost:8080/scripts.f9c6a0ac383dd1b470f8.js:2:6483
      N@http://localhost:8080/scripts.f9c6a0ac383dd1b470f8.js:2:146
      @http://localhost:8080/scripts.f9c6a0ac383dd1b470f8.js:2:6409
      N@http://localhost:8080/scripts.f9c6a0ac383dd1b470f8.js:2:146
      @http://localhost:8080/scripts.f9c6a0ac383dd1b470f8.js:2:6362
      N@http://localhost:8080/scripts.f9c6a0ac383dd1b470f8.js:2:146
      @http://localhost:8080/scripts.f9c6a0ac383dd1b470f8.js:2:950
      @http://localhost:8080/scripts.f9c6a0ac383dd1b470f8.js:2:959

      Browser: Firefox 94.0 / Windows 10

         328 |});
         329 |
         330 |fixture`Firefox test`
         331 |    .page(`http://localhost:8080/button`);
         332 |test.only('Should execute test on Firefox browser', async () => {
       > 333 |    await t.click(Selector('#basicButton'));
         334 |});
         335 |
         336 |
         337 |
         338 |

```

### Steps to Reproduce

1. Build any application of minimal size 35Mb.
2. Run any test on Firefox.
3. See that test is terminated and that error appears in console.

### TestCafe version

1.16.1, 1.17.1

### Node.js version

14.16.1

### Command-line arguments

testcafe firefox:headless **.e2e-spec.ts

### Browser name(s) and version(s)

Firefox 94.0.2

### Platform(s) and version(s)

Windows 10

### Other

JavaScript error can be ignored by "-e" command. In such case test runs, but it's not a solution.
Behavior is not dependent on headless mode, issue is reproducible in headed mode too.
Our assumption is that issue is related to the size of application, we tried to run tests on publicly accessible pages, 
but issue did not occur.
Closed issue https://github.com/DevExpress/testcafe/issues/6578 also points to #1481 and DevExpress/testcafe-hammerhead#1716.

**Comment by Farfurix** [comment]
@PierreRott 

Hello,

Thank you. We will update this thread once we have any results.

For the team:
It looks like the test application overrides the `String.replace` and `Array.indexOf` methods we use in our style processor (`StyleProcessor._replaceUrlAttributes`). This leads to this error. We need to replace the methods with native ones.

**Comment by jhwegener** [comment]
We encountered - perhaps the same - problem with _replaceUrlAttributes.
It occurs while embedding SVG files as base64 encoded strings in CSS. This produces quite big CSS files. The error occurs on our system, when the size of a single CSS file is bigger than ~90kb.
We try to circumvent this error now by a more lightweight approach in embedding the SVG file - which is perhaps also a better solution for us.

**Comment by miherlosev** [comment]
Hi @jhwegener

The supposed cause of the issue (from [https://github.com/DevExpress/testcafe/issues/6747#issuecomment-985326471](https://github.com/DevExpress/testcafe/issues/6747#issuecomment-985326471)) is not confirmed. So, we still need a simple example to reproduce.
Let's try to investigate the CSS text that leads to the errors without sharing an example with us.
To do that, please, perform the following actions:

* open the `node_modules/testcafe-hammerhead/lib/processing/style.js` file in a text editor;
* add the `console.log(css)` statement at the start of the `_replaceUrlAttributes` function
* run TestCafe with the `--dev` and `-e` options
* open the browser console, copy the CSS text before the error message, and share it in this thread.

**Comment by PierreRott** [comment]
Please do not close this thread, I will reply after holidays.

**Comment by RandomNonameDude** [comment]
Hello, I'm from the same team as @PierreRott. It seems that the log might contain some sensitive data specific to our company. We're currently reviewing if we can provide it to you. We'll get in touch once we know more.

**Comment by PierreRott** [comment]
@jhwegener @miherlosev I am sorry for the delay, I am sending you the requested log.
Can you reopen this issue, please?
[testcafe_css_log.txt](https://github.com/DevExpress/testcafe/files/7924310/testcafe_css_log.txt)

**Comment by miherlosev** [comment]
Hi @PierreRott,

Unfortunately, I cannot reproduce the issue using the shared information. At present, I have no idea how to reproduce the issue without a full example that we can run locally. Could you please share such an example?

**Comment by vizdatom** [comment]
Hi @miherlosev,
I am from the same team as @PierreRott and I prepared a simple angular application as an example here https://github.com/vizdatom/testcafe-test-app.
The application uses Testcafe version 1.18.3, but the errors occur on versions  ^1.16.1 as well.

**Comment by vizdatom** [comment]
It seems that styles with svg loaded as base64 causes the problem. The `_replaceUrlAttributes` cannot handle the base64 encoded svg strings if it exceeds ~50 KB.

**Comment by aleks-pro** [comment]
Hello @vizdatom ,

Thank you for the example. I reproduced the issue. We will investigate it and update this thread once we have any results.

**Comment by RandomNonameDude** [comment]
@aleks-pro Hi, do you have an idea when this might get fixed?
