### ISSUE TITLE
[docs] It is possible to specify the "filter" option as a method in the JS configuration file

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe#6752]
### What is your Scenario?

Specify a method to filter tests in the JS configuration file. It's possible to do this in the following way (like via the Runner.filter method):

```
module.exports = {
    src: './tests/test.js',
    filter: (testName => !testName.includes('one') && !testName.includes('two'))
}
```

However, this approach is not described in the Documentation.

### What are you suggesting?

Describe the richer capabilities of the JS configuration file options.

### Additional context

https://stackoverflow.com/questions/70186825/testcafe-how-to-have-multiple-regex-for-testgrep-in-testcaferc-file

**Comment by rob4629** [comment]
Could this also be done with test `meta` values?

**Comment by Dmitry-Ostashev** [comment]
@rob4629 Yes, this method has the same arguments as the callback of the [Runner.filter](https://testcafe.io/documentation/402657/reference/testcafe-api/runner/filter#header) method.

**Comment by titerman** [comment]
Fixed https://testcafe.io/documentation/402638/reference/configuration-file#filter-tests-by-function
