### ISSUE TITLE
Multiple reopening one window with the command `openWindow`

### ISSUE THREAD

**Issue by Aleksey28** [DevExpress/testcafe#6766]
### What is your Scenario?

I'd like to open a new window.

### What is the Current behavior?

I see multiple reopening one window per one command.

### What is the Expected behavior?

I expect not to see reopening the window per one command.

### What is your public website URL? (or attach your complete example)

https://devexpress.github.io/testcafe/example/
https://devexpress.github.io/testcafe

### What is your TestCafe test code?

fixture`My fixture`
    .page`https://devexpress.github.io/testcafe/example/`;

test('Open window', async t => {
    await t.openWindow('https://devexpress.github.io/testcafe');
});

### Screenshots

![Alt Text](https://media.giphy.com/media/9B2Roe5V7LnKHOsqsR/giphy-downsized-large.gif)

### Steps to Reproduce

1. Install testcafe
2. Create a test file with code
3. Run this file with testcafe

### TestCafe version

1.17.0

### Node.js version

v16.13.1

### Command-line arguments

testcafe chrome ./test.js

### Browser name(s) and version(s)

Chrome 96.0.4664.93

### Platform(s) and version(s)

Windows 10

**Comment by miherlosev** [comment]
Fixed in `testcafe@1.17.2-alpha.2`
