### ISSUE TITLE
iframe pointing to a pdf file never loads on chrome

### ISSUE THREAD

**Issue by ccheraa** [DevExpress/testcafe#6767]
### What is your Scenario?

I want to check the content of an iframe.

### What is the Current behavior?

I can't switch to the frame, I get this eroor:
`Content of the iframe to which you are switching did not load.`

### What is the Expected behavior?

TestCafe should switch to the iframe, and then I can check its content.

### What is your public website URL? (or attach your complete example)

```html
<!DOCTYPE html>
<html lang="en">
<body>
  <iframe src="./file.pdf" frameborder="0"></iframe>
</body>
</html>
```

### What is your TestCafe test code?

```typescript
import { ClientFunction, Selector } from 'testcafe';

fixture`iframe`
  .page('http://127.0.0.1:5500/index.html');

test.disablePageReloads('check items inside iframe', async t => {
  await t
    .expect(Selector('h1').innerText).eql('main')
    .switchToIframe('iframe')
    .expect(Selector('body.pdf').exists).ok();
});
```

### Your complete configuration file

I tried to run TestCafe with both `chrome` and `chrome:userProfile` without sucess
The test passes on Firefox though.

### Your complete test report

```
Running tests in:
 - Chrome 96.0.4664.45 / Linux 0.0

 iframe
 ✖ check items inside iframe

   1) Content of the iframe to which you are switching did not load.

      Browser: Chrome 96.0.4664.45 / Linux 0.0

          4 |  .page('http://127.0.0.1:5500/index.html');
          5 |
          6 |test.disablePageReloads('check items inside iframe', async t => {
          7 |  await t
          8 |    .expect(Selector('h1').innerText).eql('main')
       >  9 |    .switchToIframe('iframe')
         10 |    .expect(Selector('body.pdf').exists).ok();
         11 |});
         12 |

         at <anonymous> (/home/user/Test/test.ts:9:6)
         at <anonymous> (/home/user/Test/test.ts:8:71)
         at __awaiter (/home/user/Test/test.ts:4:12)
         at <anonymous> (/home/user/Test/test.ts:6:64)



 1/1 failed (11s)
```

### Steps to Reproduce

1. create the file `index.html`
2. add any pdf file in the same directory and name it `file.pdf`
3. run the test

### TestCafe version

1.22.17

### Node.js version

17.1.0

### Command-line arguments

chrome:userProfile test.ts

### Browser name(s) and version(s)

Chrome 96.0.4664.45

### Platform(s) and version(s)

Ubuntu 21.10

**Comment by AlexanderMoiseev** [comment]
Hi, 

TestCafe can interact only with HTML pages. Content of your iframe is a pdf file. So, TestCafe is unable to interact with it. If you want to check your pdf file content, you can use [RequestLogger](https://testcafe.io/documentation/402668/reference/test-api/requestlogger). The checking flow will be the following: capture a pdf file with RequestLogger, read pdf content with any library from npm, and then check the required entities.
