### ISSUE TITLE
ERROR Cannot establish one or more browser connections.

### ISSUE THREAD

**Issue by ayemelyanenko-chegg** [DevExpress/testcafe#6769]
### What is your Scenario?

Hello, I am running concurrent testcafe tests using browserstack and gitlab.

Before December 9th, everything was running properly. On December 9th, I started to notice consistent test failures. Looking at the logs, I noticed the following:

```
ERROR Cannot establish one or more browser connections.
1 of 6 browser connections have not been established:
- browserstack:chrome
Hints:
- The host machine may not be powerful enough to handle the specified concurrency factor (6). Try to decrease the concurrency factor or allocate more computing resources to the host machine.
- Increase the value of the "browserInitTimeout" option if it is too low (currently: 2 minutes for local browsers and 6 minutes for remote browsers). This option determines how long TestCafe waits for browsers to be ready.
- The error can also be caused by network issues or remote device failure. Make sure that your network connection is stable and you can reach the remote device.
Type "testcafe -h" for help.
```

Based on the logs, I adjusted the concurrency factor to 3 but still get occasional failures with the following:

```
ERROR Cannot establish one or more browser connections.
1 of 3 browser connections have not been established:
- browserstack:chrome
Hints:
- Increase the value of the "browserInitTimeout" option if it is too low (currently: 2 minutes for local browsers and 6 minutes for remote browsers). This option determines how long TestCafe waits for browsers to be ready.
- The error can also be caused by network issues or remote device failure. Make sure that your network connection is stable and you can reach the remote device.
Type "testcafe -h" for help.

```
I have not updated the testcafe or testcafe-browserstack version so wondering what might have changed. I also reached out to the browserstack team with the same issue as it's not clear to me whether it's a testcafe or a browserstack issue.

### What is the Current behavior?

Test jobs on gitlab fail intermittently with the following:

```
1 of 3 browser connections have not been established:
- browserstack:chrome
Hints:
- Increase the value of the "browserInitTimeout" option if it is too low (currently: 2 minutes for local browsers and 6 minutes for remote browsers). This option determines how long TestCafe waits for browsers to be ready.
- The error can also be caused by network issues or remote device failure. Make sure that your network connection is stable and you can reach the remote device.
Type "testcafe -h" for help.
```

### What is the Expected behavior?

The expected behavior would be for there to be no errors in browser connection and to be able to run 6 concurrent browsers as I did before December 9th

### What is your public website URL? (or attach your complete example)

N/A for the purpose of this issue

### What is your TestCafe test code?

N/A for the purpose of this issue

### Screenshots

<img width="751" alt="Screen Shot 2021-12-11 at 10 15 39 AM" src="https://user-images.githubusercontent.com/14633459/145687762-00f7d720-1cc9-42c5-813b-6f49bfa31409.png">

<img width="682" alt="Screen Shot 2021-12-11 at 10 10 12 AM" src="https://user-images.githubusercontent.com/14633459/145687763-f2c6e802-c0b5-41be-8375-75258ccac8e7.png">

### Steps to Reproduce

1. Run a collection of any tests against browserstack with a concurrency factor of 6

### TestCafe version

1.17.1

### TestCafe browserstack provider version

1.13.2-alpha.1

### Node.js version

12.14.1

### Command-line arguments

node --max-http-header-size=9999999 node_modules/testcafe/bin/testcafe -c 6 browserstack:chrome testcafe/tests/searchTest.ts

### Browser name(s) and version(s)

Latest Chrome and Firefox

**Comment by felis2803** [comment]
Hello,
This error occurs when you try to launch more streams than your browserstack tariff plan allows.
The [testcafe-browser-provider-browserstack](https://github.com/DevExpress/testcafe-browser-provider-browserstack) module, which allows you to run tests in browserstack, was updated more than a year ago and therefore could not affect the operation of your tests on December 9th. Perhaps, something has changed on the browserstack side. In particular, I noticed that over-limit tasks are not queued - instead, they freeze.
Please make sure that you do not exceed your allocated concurrency limits.
Also, please take a look at this [article](https://github.com/DevExpress/testcafe-browser-provider-browserstack/issues/18). Perhaps, it will be useful to you.

**Comment by ayemelyanenko-chegg** [comment]
Thanks @felis2803, I reached out to the browserstack team.
