### ISSUE TITLE
ERROR NativeBinaryHasFailedError: The find-window process failed with the 1 exit code.

### ISSUE THREAD

**Issue by rob4629** [DevExpress/testcafe#6774]
### What is your Scenario?

I upgraded to the latest release candidate (1.17.2-rc.2), and trying to run any test using any browser, on MacOS. The tests fail to start, and hang, unable to exit using the terminal.

I can stop the `node` session using activity monitor... but if I try to repeat then node isn't started the 2nd time and I have to close the terminal window to exit.

### What is the Current behavior?

An error is returned, and the tests don't start

```sh
Using locally installed version of TestCafe.
The "browsers" option from the configuration file will be ignored.
ERROR NativeBinaryHasFailedError: The find-window process failed with the 1 exit code.
Process output:
The application /Users/rcooper/.testcafe-browser-tools/TestCafe Browser Tools.app/Contents/MacOS/testcafe-browser-tools cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10661 "(null)" UserInfo={_LSLine=3844, _LSFunction=_LSOpenStuffCallLocal}
    at ChildProcess.<anonymous> (/Users/rcooper/work/github.com/change/regression-qaa/node_modules/testcafe-browser-tools/src/utils/exec.js:74:24)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.emit (node:domain:475:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17)

Type "testcafe -h" for help.
```

### What is the Expected behavior?

Testcafe should trigger tests as per normal.

### What is your public website URL? (or attach your complete example)

Tests don't start, so N/A

### What is your TestCafe test code?

N/A

### Your complete configuration file

N/A

### Your complete test report

```sh
Using locally installed version of TestCafe.
The "browsers" option from the configuration file will be ignored.
ERROR NativeBinaryHasFailedError: The find-window process failed with the 1 exit code.
Process output:
The application /Users/rcooper/.testcafe-browser-tools/TestCafe Browser Tools.app/Contents/MacOS/testcafe-browser-tools cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10661 "(null)" UserInfo={_LSLine=3844, _LSFunction=_LSOpenStuffCallLocal}
    at ChildProcess.<anonymous> (/Users/rcooper/work/github.com/change/regression-qaa/node_modules/testcafe-browser-tools/src/utils/exec.js:74:24)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.emit (node:domain:475:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17)

Type "testcafe -h" for help.
```

### Steps to Reproduce

1. Install the latest release candidate
2. Run `testcafe chrome`

### TestCafe version

1.17.2-rc.2

### Node.js version

16.13.0 (but also failing with 10.15.3)

### Command-line arguments

testcafe chrome

### Platform(s) and version(s)

MacOS Big Sur - 11.6.2

### Other

This only seems to be happening on my laptop, since our CircleCi runs are working (which uses Linux). I've uninstalled testcafe-browser-tools + testcafe and did a clean install, also attempted running with `sudo` in case it's a permissions thing... no luck

**Comment by rob4629** [comment]
Looks like it's a re-occurrence of #4742  (/ #5293)

**Comment by AlexanderMoiseev** [comment]
Hi, 

Thank you for your input. We have reproduced the problem, please stay tuned.

**Comment by rob4629** [comment]
No longer experiencing this. I followed the `testcafe-browser-tools` upgrade instructions, along with a few restarts... and the problem has now gone. Feel free to close, and re-open if someone else experiences it.

**Comment by AlexanderMoiseev** [comment]
Hi @rob4629,

I'm glad to hear that. Thank you for reaching out to us and considering DevExpress for your software development needs.

**Comment by KingM1** [comment]
I'm still seeing this issue. I tried upgrading from 1.171 to 1.18.1 (and followed the upgrade instructions), but still getting this error. 

- Ran `tccutil reset ScreenCapture com.devexpress.testcafe-browser-tools`
- Ran `tccutil reset AppleEvents com.devexpress.testcafe-browser-tools`
- Ran `npm i --save testcafe@1.18.1`
- Ran a test, get this error

I've also tried restarting my computer a few times, still get this error.

**Comment by rob4629** [comment]
The only other thing I tried was using `sudo` when running the testcafe command (due to the permissions issue you mentioned). Did you try that?

**Comment by AlexanderMoiseev** [comment]
Hi @KingM1

If you previously installed testcafe v1.17.2-rc, try removing the .testcafe-browser-tools folder from your home directory. If this does not help, please open a new issue with an sample project and a video to demonstrate how you reproduce the issue. Make sure that the callstack with the problem is also visible.

**Comment by AlexanderMoiseev** [comment]
Hi, @KingM1 
You are very welcome.
