### ISSUE TITLE
We need to add test run warning if browser provider doesn't support browser manipulation

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#678]
Blocking on #573. Extracted from #671

**Comment by inikulin** [comment]
I believe it was implemented in context of browser providers? \cc @AndreyBelym

**Comment by AndreyBelym** [comment]
Yes, it was implemented: https://github.com/DevExpress/testcafe/blob/master/src/browser/provider/plugin-host.js#L81

**Comment by inikulin** [comment]
Closed via #573
