### ISSUE TITLE
Incorrect sequence of events for clicking a label element with "for" attribute

### ISSUE THREAD

**Issue by peskovaa** [DevExpress/testcafe#6780]
### What is your Scenario?

Click for label with attribute "for". Сhecking the sequence of events.

### What is the Current behavior?

onfocus input's event fired the first and then fired onmouseup label's event with activeElement.tagName=="INPUT"

### What is the Expected behavior?

fired onmouseup label event with activeElement.tagName=="BODY" and then should be fired input onfocus event

### What is your public website URL? (or attach your complete example)
```HTML
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <script>
        function focusMethod() {
            print("inputElement got focus\n");
        }
        function mouseupMethod() {
            print("activeElement.tagName=" + document.activeElement.tagName + "\n");
        }
        function print(message) {
            var logTextArea = document.getElementById("logTextArea");
            logTextArea.value += message;
        }
    </script>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <textarea id="logTextArea" style="position: fixed; right: 0; height: 500px; width: 200px"></textarea>
            <label id="label" onmouseup="mouseupMethod()" for="input">label</label>
            <input id="input" onfocus="focusMethod()" />
        </div>
    </form>
</body>
</html>
```

### What is your TestCafe test code?
```JS
fixture('1')
test.page("./test.html")("test", async t=> {
await t
    .click(Selector("#label"))
    .expect(logTextArea.value).eql('activeElement.tagName=BODY\ninputElement got focus\n');
});
```

### Steps to Reproduce

1.Run the test
2. If the test doesn't fail due to an unexpected alert, there is a bug

### TestCafe version

1.17.1

### Command-line arguments

testcafe chrome test.js

### Browser name(s) and version(s)

chrome 96

### Platform(s) and version(s)

Windows 10

**Comment by AlexanderMoiseev** [comment]
Hi, 

Thank you for your example. We have reproduced this behavior, please stay tuned.
