### ISSUE TITLE
Error with FAST button

### ISSUE THREAD

**Issue by mollykreis** [DevExpress/testcafe#6785]
### What is your Scenario?

There is an error with TestCafe when a site contains a `fast-button` element from [Microsoft's FAST components](https://www.fast.design/docs/introduction).

When I run tests with TestCafe, I get the following error:

> JavaScript error details:
      Error: Failed to execute 'removeAttributeNode' on 'Element': The node provided is owned by another element.

I see the same error using the Hammerhead playground from master [here](https://github.com/DevExpress/testcafe-hammerhead).

### What is the Current behavior?

An exception occurs when a page containing a `fast-button` is run using TestCafe. The error does not occur normally on the page.

From my debugging, it seems the error occurs [here](https://github.com/microsoft/fast/blob/b816a09d0cf393567396e3f5a8e06312798dc05e/packages/web-components/fast-element/src/templating/compiler.ts#L138) in the compilation of the `fast-button`. It appears that `attributes` does not get updated to reflect that an attribute was removed during the call to `removeAttributeNode`, so in the next iteration of the for-loop, the same attribute is attempted to be removed again, causing the exception.

Note: I did not try every FAST component, so the issue may occur with more than just the button.

### What is the Expected behavior?

The page should load successfully.

### What is your public website URL? (or attach your complete example)

Public website: https://explore.fast.design/components/fast-button

I've also attached a simple Angular app containing only a fast-button.
[TestCafeError.zip](https://github.com/DevExpress/testcafe/files/7747280/TestCafeError.zip)

### What is your TestCafe test code?

Not relevant. I reproduced this directly using the Hammerhead playground.

### Steps to Reproduce

To reproduce using public site:
1. Run Hammerhead playground as described in [testcafe-hammerhead readme](https://github.com/DevExpress/testcafe-hammerhead/blob/master/README.md)
2. Enter `https://explore.fast.design/components/fast-button` in the text box and click "Proxy"
3. Notice all the exceptions in the console
4. Notice that the main example button on the page doesn't appear

To reproduce using the attached app:
1. Open the attached project
2. Install dependencies using `npm install`
3. Run the app using `npm run start` and see a page with a button open to localhost:4200
4. Run Hammerhead playground as described in [testcafe-hammerhead readme](https://github.com/DevExpress/testcafe-hammerhead/blob/master/README.md)
5. Enter `http://localhost:4200` in the text box and click "Proxy"
6. Notice the exception in the console
7. Notice that the button does not appear on the page

### TestCafe version

testcafe-hammerhead version 24.5.9

### Node.js version

16.13.0

### Command-line arguments

N/A

### Browser name(s) and version(s)

Chrome: Version 96.0.4664.45 (Official Build) (64-bit)

### Platform(s) and version(s)

Windows

**Comment by Dmitry-Ostashev** [comment]
Thank you for your report. I reproduced the issue. We will research it and update this thread once we have any news.

**Comment by TrevorKarjanis** [comment]
Support for HTMLElement.removeAttributeNode has been merged and released in [testcafe-hammerhead@25.5.15](https://github.com/DevExpress/testcafe-hammerhead/releases/tag/v24.5.15). We're waiting for the root testcafe package to [uptake the version](https://github.com/DevExpress/testcafe/blob/020a5f3c7f4458fbc01808dabf77601ee44c43c2/package.json#L137) before validation can be completed.

**Comment by miherlosev** [comment]
Hi @TrevorKarjanis 

The fix will be available in the next TestCafe version.

**Comment by miherlosev** [comment]
Fixed in https://github.com/DevExpress/testcafe-hammerhead/pull/2742
