### ISSUE TITLE
Iframe does not load in Testcafe, manually works 

### ISSUE THREAD

**Issue by rehanmomin** [DevExpress/testcafe#6786]
### What is your Scenario?

I am trying to open a iframe and navigate to it.
it works when I amnually open the iframe but not through testcafe. tried with latest testCafe version and different browsers

### What is the Current behavior?

Iframe is showing page not loaded.

### What is the Expected behavior?

Iframe should load as it loads when I open it manually

### What is your public website URL? (or attach your complete example)

https://www.davidjones.com/Product/23034277/Intensive-Skin-Serum-Foundation

### What is your TestCafe test code?

import { Selector } from "testcafe";
import el from "./elements"

fixture `David Jones MMM Widget Tests`
    .page`https://www.davidjones.com/`
    .beforeEach(async t => {
        await t.maximizeWindow()
    });

test
    ('BOBBY Brown : Intensive Skin Serum Foundation', async t => {

        const CTA = Selector('#findShadeMMM')
        const widget = Selector('#firstStepKnownUnknownSelection')
        const iframe = Selector('iframe[referrerpolicy="origin"]')

        await t.navigateTo("https://www.davidjones.com/Product/23034277/Intensive-Skin-Serum-Foundation")
        await t.expect(CTA.exists).ok("MMM CTA is not present")
        await t.click(CTA)
        await t.switchToIframe(iframe)
        await t.wait(10000)
        await t.expect(el.widget.exists).ok("Widget is not loaded")

    });

### Steps to Reproduce

1. Go to https://www.davidjones.com/Product/23034277/Intensive-Skin-Serum-Foundation
2. Click on Match My Shade
3. Iframe should load as expected

### TestCafe version

1.17.1

### Node.js version

14.17.3

### Command-line arguments

testcafe chrome --skip-js-errors retailers.js

### Browser name(s) and version(s)

All browsers 

### Platform(s) and version(s)

MAC OS

**Comment by AlexKamaev** [comment]
At this moment, `https://www.davidjones.com/` is unreachable, so I cannot examine the test (see the screenshot):

![image](https://user-images.githubusercontent.com/1678902/147047823-f3cfe132-7bf2-4d54-a186-315c30960b34.png)

Please create a simple example to demonstrate the issue or fix the site. Thank you.

**Comment by rehanmomin** [comment]
@AlexKamaev the site is up now you can check 
![image](https://user-images.githubusercontent.com/42905671/147068536-897622db-f341-4f36-ae08-9bec41935395.png)

**Comment by AlexKamaev** [comment]
We still couldn't reproduce the issue with your website. We got the following error:
```
Error details:
      Failed to perform a request to the resource at "https://www.davidjones.com/" because of an error.
      The request contains a header that doesn't comply with the specification
      "https://tools.ietf.org/html/rfc7230#section-3.2.4".
      It causes an internal Node.js error on parsing this header.
      Invalid characters:
      Character with code "32" in header "    XjeOtalM" name at index 0
      Character with code "32" in header "    XjeOtalM" name at index 1
      Character with code "32" in header "    XjeOtalM" name at index 2
      Character with code "32" in header "    XjeOtalM" name at index 3
```
Please fix the error or prepare a separate example to demonstrate the issue.
