### ISSUE TITLE
t.closeWindow do not close window

### ISSUE THREAD

**Issue by olenahuk** [DevExpress/testcafe#6787]
### What is your Scenario?

During my test I need to open email with the code. 
So I'm opening Mailinator in new window do what I need and want to close it before continue.

### What is the Current behavior?

Window with opened email still present but test go on and want to enter the code in second window.
I'm switching to main window to proceed and during further run mail window closed somewhere.
But from time to time it fail with error that window can't be found.

### What is the Expected behavior?

Window should be closed before proceeding with next step.

### What is your public website URL? (or attach your complete example)

export async function getVerificationCodeFromEmail(email: string, t: TestController): Promise<string> {
	//open new window and navigate to mailinator
	const url = `https://www.mailinator.com/v4/public/inboxes.jsp?to=${email}`;
	console.log("URL " + url);
	await t.openWindow(url);
	const mailinator = await t.getCurrentWindow();
	//open correct email with "Verification Code" text in title
	const mail = Selector("[ng-repeat='email in emails']").withText("Verification Code");
	await t.click(mail);
	//save the code
	const codeSelector = Selector("#verification_code_id");
	await t.switchToIframe("#html_msg_body");
	const verificationCode = await codeSelector.innerText;
	await t.switchToMainWindow();
	await t.closeWindow(mailinator);

	return verificationCode;
}

### What is your TestCafe test code?

export async function getVerificationCodeFromEmail(email: string, t: TestController): Promise<string> {
	//open new window and navigate to mailinator
	const url = `https://www.mailinator.com/v4/public/inboxes.jsp?to=${email}`;
	console.log("URL " + url);
	await t.openWindow(url);
	const mailinator = await t.getCurrentWindow();
	//open correct email with "Verification Code" text in title
	const mail = Selector("[ng-repeat='email in emails']").withText("Verification Code");
	await t.click(mail);
	//save the code
	const codeSelector = Selector("#verification_code_id");
	await t.switchToIframe("#html_msg_body");
	const verificationCode = await codeSelector.innerText;
	await t.switchToMainWindow();
	await t.closeWindow(mailinator);

	return verificationCode;
}

### Steps to Reproduce

1. Open first window
2. Open second window with mailinator
3. Close mailinator window
4. Perform some steps to see if  window has been closed

### TestCafe version

1.16.0

### Node.js version

v14.17.0

### Command-line arguments

node ./build --browsers chrome:emulation:device=iphoneX

### Browser name(s) and version(s)

Chrome Version 96.0.4664.110 (Official Build) (64-bit)

### Platform(s) and version(s)

Windows 10

**Comment by olenahuk** [comment]
import {Selector} from 'testcafe';

fixture`Microsoft DevBlogs Login page`
    .page('https://www-stg.yuugado.com/');

test('automatically change execution context', async t => {
    const email = 'Test_Automation_Theia_20211124152148@mailinator.com';
    const url = `https://www.mailinator.com/v4/public/inboxes.jsp?to=${email}`;

    const mailinator = await t.openWindow(url);

    const mail = Selector("[ng-repeat='email in emails']").withText("Verification Code");
    await t.click(mail);
    //save the code
    const codeSelector = Selector("#verification_code_id");
    await t.switchToIframe("#html_msg_body");
    const verificationCode = await codeSelector.innerText;

    await t.closeWindow(mailinator);

    await t.wait(5000);
    console.log("Ver code " + verificationCode);
});

With this code test pass but you can see that mailinator window not closed

**Comment by AlexKamaev** [comment]
I checked this test and found that the test fails in the `await t.click(mail)` line.
I modified the test by removing this code as follows:

```JS
import { Selector } from 'testcafe';

fixture`Microsoft DevBlogs Login page`
    .page('https://example.com');

test('automatically change execution context', async t => {
    const email = 'Test_Automation_Theia_20211124152148@mailinator.com';
    const url   = `https://www.mailinator.com/v4/public/inboxes.jsp?to=${email}`;

    const mailinator = await t.openWindow(url);

    const mail = Selector('[ng-repeat=\'email in emails\']').withText('Verification Code');

    // await t.click(mail);

    // const codeSelector = Selector('#verification_code_id');
    // await t.switchToIframe('#html_msg_body');

    // const verificationCode = await codeSelector.innerText;

    await t.closeWindow(mailinator);

    await t.wait(5000);

});
```
It works as expected. The window is closed successfully.
Please modify your test to demonstrate the issue.
