### ISSUE TITLE
New window still immediately closes under some circumstances

### ISSUE THREAD

**Issue by Khartir** [DevExpress/testcafe#6794]
### What is your Scenario?

This is a follow on to #6680.

On Version 1.18.0 a new window still is immediately closed, if it is opened in the first test a test run.
On Chrome, if it is opened in a later test, the error does sometimes not occur. This workaround does not seem work with Firefox.

I just tried to reproduce this with a fresh installation of testcafe and then it does not work at all.

### What is the Current behavior?

If a single test is executed and that test opens a new window, the window is closed before it can be inspected. If there is any test before that test, the window stays open.

### What is the Expected behavior?

Windows stay open until closed

### What is your public website URL? (or attach your complete example)

https://rto11.csb.app/

### What is your TestCafe test code?

import {ClientFunction, t} from "testcafe";

fixture`fail`.page('https://rto11.csb.app/');

//uncomment to fix
// test('do nothing', async() => {});

test('new window', async () => {
    await t
        .click('a')
        .expect(ClientFunction(() => document.location.href)())
        .eql('https://www.google.com/')
        .closeWindow();
})

### Your complete configuration file

no configuration

### Your complete test report

 fail
 ✖ new window

   1) AssertionError: expected 'https://rto11.csb.app/' to deeply equal 'https://www.google.com/'
      
      + expected - actual
      
      -https://rto11.csb.app/
      +https://www.google.com/
      

      Browser: Chrome 95.0.4638.69 / Linux 0.0

         18 |
         19 |test('new window', async () => {
         20 |    await t
         21 |        .click('a')
         22 |        .expect(ClientFunction(() => document.location.href)())
       > 23 |        .eql('https://www.google.com/')
         24 |        .closeWindow();
         25 |})
         26 |
         27 |

         at <anonymous> (/home/tgnandt/projects/tmp/dummy.js:23:10)
         at asyncGeneratorStep (/home/tgnandt/projects/tmp/dummy.js:1:218)
         at _next (/home/tgnandt/projects/tmp/dummy.js:1:556)
         at <anonymous> (/home/tgnandt/projects/tmp/dummy.js:1:721)
         at <anonymous> (/home/tgnandt/projects/tmp/dummy.js:1:462)

 1/1 failed (9s)

### Steps to Reproduce

Run code above to see the error, uncomment the empty test to see it (sometimes) working

### TestCafe version

1.18.0

### Node.js version

v14.18.2

### Command-line arguments

testcafe chromium

### Browser name(s) and version(s)

Chromium 95, Firefox 95

### Platform(s) and version(s)

Linux Mint 19.3

**Comment by AlexKamaev** [comment]
I checked your scenario on Windows 10 and Ubuntu with the latest Chrome version and everything works as expected. Please make sure you are using the latest TestCafe version. You can check your actual version using the `testcafe -v` command. If the issue persists please modify your scenario to make it reproducible.

**Comment by Khartir** [comment]
So reproducing this is really strange. I tried it on my local machine with several browsers and it sometimes works but mostly doesn't. 

So Itried this with a fresh Ubuntu 20.04 LTS-vm and the test failed:
```
t@t-VirtualBox:~/test$ cat test.js 
import {ClientFunction, t} from "testcafe";

fixture`fail`.page('https://rto11.csb.app/');

test('new window', async () => {
  await t.click('a')
    .expect(ClientFunction(() => document.location.href)())
    .eql('https://www.google.com')
    .closeWindow();
});
t@t-VirtualBox:~/test$ node -v
v10.19.0
t@t-VirtualBox:~/test$ npx testcafe -v
npx: installed 461 in 27.914s
1.18.0
t@t-VirtualBox:~/test$ npx testcafe firefox:headless test.js 
npx: installed 461 in 23.124s
 Running tests in:
 - Firefox 95.0 / Linux 0.0

 fail
 ✖ new window

   1) AssertionError: expected 'https://rto11.csb.app/' to deeply equal 'https://www.google.com'
      
      + expected - actual
      
      -https://rto11.csb.app/
      +https://www.google.com
      

      Browser: Firefox 95.0 / Linux 0.0

          3 |fixture`fail`.page('https://rto11.csb.app/');
          4 |
          5 |test('new window', async () => {
          6 |  await t.click('a')
          7 |    .expect(ClientFunction(() => document.location.href)())
       >  8 |    .eql('https://www.google.com')
          9 |    .closeWindow();
         10 |});
         11 |

         at <anonymous> (/home/t/test/test.js:8:6)
         at asyncGeneratorStep (/home/t/test/test.js:1:218)
         at _next (/home/t/test/test.js:1:556)
         at <anonymous> (/home/t/test/test.js:1:721)
         at <anonymous> (/home/t/test/test.js:1:462)



 1/1 failed (20s)
```
I also updated to node 14.18.2 and it did not work either.

**Comment by AlexKamaev** [comment]
I still can't reproduce the issue. Please try to run your project on other machines. I think that the issue may be caused by some kind of conflict of testcafe versions.
