### ISSUE TITLE
TestCafe crashes waiting for child window to open

### ISSUE THREAD

**Issue by rob4629** [DevExpress/testcafe#6798]
### What is your Scenario?

To make a payment using PayPal child window, as part of our promotion flow

### What is the Current behavior?

While we assert the Paypal window has loaded properly, Testcafe crashes and returns to the `CONNECTED` splash screen (then hangs).

### What is the Expected behavior?

Shouldn't crash. If it does, then the test should restart, not hang indefinitely.

### What is your public website URL? (or attach your complete example)

www.change.org

### What is your TestCafe test code?

import { Selector, t } from 'testcafe';
import Chance from 'chance';

const submitWithPaypalButton = async (ppmu = false) => {
  const paypalIframe = Selector('[data-testid="paypal-button"] iframe').withAttribute('src');
  const ppmuPaypalIframe = Selector('#modal-paypal-button iframe').withAttribute('src');
  const payWithPaypalButton = Selector('[data-funding-source="paypal"]').filterVisible();

const paypalIframeSelector = ppmu ? ppmuPaypalIframe : paypalIframe;
  await t
    .expect(paypalIframeSelector.visible)
    .ok()
    .switchToIframe(paypalIframeSelector)
    .hover(payWithPaypalButton)
    .click(payWithPaypalButton)
    .wait(500);
};

const paypalLogin = async () => {
  const emailInput = Selector('#email');
  await t
    .expect(emailInput.visible)
    .ok({ timeout: 30000 })
    .typeText(emailInput, 'you@email.com')
    .click(Selector('#btnNext'))
    .typeText(Selector('#password'), 'password1')
    .click(Selector('#btnLogin'));
};

const completePaypalMiniWindow = async ({ shouldLogin = true, oneTimePayment = false } = {}) => {
  const consentButton = Selector('#consentButton, [data-test-id="continueButton"]').filterVisible();
  const submitButtonInitial = Selector('[data-testid="submit-button-initial"]');
  if (shouldLogin) {
    await paypalLogin();
  }

  const continueButton = oneTimePayment ? submitButtonInitial : consentButton;
  const paymentOptions = Selector('#paymentMethod, [data-testid="stacked-payment-options"]').filterVisible();

  await t
    .expect(paymentOptions.visible)
    .ok()
    .hover(continueButton)
    .click(continueButton);
};

fixture('Promote petition as authenticated user with saved PayPal (Part 2)
').page('https://www.staging-change.org/').httpAuth({ "username": "testcafe", "password": "<password>" });

test.only('User has saved PayPal payment info but does not use saved PayPal, instead saves new PayPal payment info. It overwrites the payment info and redirects to the thank you page', async () => {
  const emailAddress = chance.email();
  // Navigate to the Sponsorship page, enter promotion amount and pay with PayPal
  await t
    .navigateTo('/p/asdf-stgaqaoppscore8/sponsors/new')
    .expect(Selector('.js-payment-form').visible)
    .ok()
    .typeText(Selector('[data-testid="payment-form-amount-input"]'), '30', { replace: true })
    .click(Selector(`[data-testid="payment-option-button-paypal"]`));

  await t
    .expect(Selector('[data-testid="input_email"]').visible)
    .ok()
    .typeText(Selector('[data-testid="input_email"]').filterVisible(), emailAddress)
    .typeText(Selector('[data-testid="input_confirmation_email"]').filterVisible(), emailAddress)
    .typeText(Selector('[data-testid="input_first_name"]'), 'first')
    .typeText(Selector('[data-testid="input_last_name"]'), 'last');
  await submitWithPaypalButton();

  // PayPal Window
  await completePaypalMiniWindow();
});

### Your complete configuration file

{
  "browsers": ["chrome:headless:emulation:device=iPhone X"],
  "src": "./tests/**/*.js",

  "assertionTimeout": 15000,
  "ajaxRequestTimeout": 40000,
  "pageLoadTimeout": 30000,
  "selectorTimeout": 15000,

  "disableMultipleWindows": false,

  "quarantineMode": false,
  "skipJsErrors": true,

  "disablePageCaching": true,

  "reporter": [
    {
      "name": "xunit",
      "output": "artifacts/test-results/results.xml"
    },
    {
      "name": "spec"
    }
  ],

  "screenshots": {
    "fullPage": true,
    "takeOnFails": true,
    "pathPattern": "${TEST_ID}/${RUN_ID}_${FILE_INDEX}.png",
    "path": "artifacts/screenshots",
    "thumbnails": false
  }
}

### Your complete test report

~/work/regression-qaa()[testcafe-18] testcafe chrome -q successThreshold=1
Using locally installed version of TestCafe.
The "browsers" and "quarantineMode" options from the configuration file will be ignored.
 Running tests in:
 - Chrome 96.0.4664.110 / macOS 10.15.7

 Promote petition as authenticated user with saved PayPal (Part 2)
User has saved PayPal payment info but does not use saved PayPal, instead saves new PayPal payment info. It overwrites the payment info and redirects to the thank you page

### Screenshots

https://user-images.githubusercontent.com/37812673/147288313-ff5292b8-c06b-46f0-888a-39f58e4cea72.mov

### Steps to Reproduce

1. Replace httpAuth `<password>` value with DevExpress access password (provided in previous correspondence)
2. testcafe chrome -q successThreshold=1 

### TestCafe version

1.18.1

### Node.js version

16.13.1

### Command-line arguments

testcafe chrome -q successThreshold=1

### Browser name(s) and version(s)

Chrome 96

### Platform(s) and version(s)

MacOS 10.15.7

**Comment by miherlosev** [comment]
Hi @rob4629 

> Replace httpAuth <password> value with DevExpress access password (provided in previous correspondence)

Could you please sent this password one more time and mention in the email body that it should be used to reproduce the https://github.com/DevExpress/testcafe/issues/6798 issue.

**Comment by rob4629** [comment]
Hi @miherlosev, I sent the requested information.... so hopefully you have everything to reproduce. It looks like the crash is happening if I do an assert in the child window (which was missing from the steps I sent). I've updated my original post to include the assertion so you can reproduce.

**Comment by miherlosev** [comment]
Hi @rob4629 

Thank you for the credentials.
I couldn't reproduce the issue. 
This is my test execution report.
![image](https://user-images.githubusercontent.com/4133518/148526958-2c4b6f43-197a-44b9-b602-aea9dc7862e2.png)

Could you please update the example, so that the highlighted assertion does not fail?
