### ISSUE TITLE
Research potential problems and ways to rewrite subsystems in Hammerhead to implement proxy-less mode

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#6802]
We should know how fast we can build a proxyless prototype. We should check what problems we can get.
 - [x] #6830
 - [x] Rewrite remaining TestRun messages handlers to use CDP
 - [x] Rewrite BrowserConnectionGateway message handlers
 - [x] Refactor and remove dead code (in the TestCafe class)

**Comment by miherlosev** [comment]
Done
