### ISSUE TITLE
Proxy server issue when launching the website

### ISSUE THREAD

**Issue by Vooha-QualiTlabs** [DevExpress/testcafe#6803]
### What is your Scenario?

When opening https://xeni.booking.xeniapp.net/ URL using the Test Cafe.

### What is the Current behavior?

404 page is shown

### What is the Expected behavior?

It should show the webpage correctly

### What is your public website URL? (or attach your complete example)

https://xeni.booking.xeniapp.net/

### What is your TestCafe test code?

fixture `Launch Website`
  .page(`https://xeni.booking.xeniapp.net/`);

test('Launch page', async () => {
});

### Your complete configuration file

{
    "selectorTimeout": 90000,
    "pageLoadTimeout": 90000,
    "browserInitTimeout": 180000,
    "assertionTimeOut": 90000,
    "disableMultipleWindows": true,
    "skipJsErrors": true,
    "concurrency": 1,
    "speed": 1,
    "stopOnFirstFail": false,
    "quarantineMode":{
      "successThreshold":1,
      "attemptLimit": 3
    },
    "screenshotPath": "/screenshots/",
    "screenshots": {
      "takeOnFails": true,
      "fullPage": true,
      "pathPattern": "${DATE}_${TIME}/test-${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.png"  
    }  
  }

### Screenshots
![image](https://user-images.githubusercontent.com/91185844/147479407-2025c00c-53ae-4f11-a9ec-807fe80cbb68.png)

### Steps to Reproduce

1.Launch browser
2.Navigate to the https://xeni.booking.xeniapp.net/ URL.

### TestCafe version

1.16.0

### Node.js version

14.17.4

### Command-line arguments

testcafe chrome src/pricing.js --skip-js-errors

### Browser name(s) and version(s)

Chrome v 96.0

### Platform(s) and version(s)

Windows 10

### Other

We have all the tests completed on the https://xeniapp.com/ website using Testcafe. But we have launched the Multi-tenant system as a new application, which is on top of the old application, but due to this issue we are not able to login to the application.
We thought that the issue is from our side, but our dev team has tried to fix and realized that this is the issue from the Testcafe side. Could you please look into it asap? thank you.

**Comment by Vooha-QualiTlabs** [comment]
@Dmitry-Ostashev could you please look into this issue? thank you

**Comment by diljitprdev** [comment]
This happens when the targetUi and backend apis are hosted on different domains. For e.g. UI is a.com and backend api is api.b.com.

**Comment by Dmitry-Ostashev** [comment]
@Vooha-QualiTlabs I cannot navigate to webpages using the urls you specified (https://xeni.qa.booking.clubxeni.com  and https://xeni.booking.xeniapp.net) without TestCafe. I see the following error in the browser console:
![image](https://user-images.githubusercontent.com/24777868/147539300-f02d2366-eb43-4baf-a468-7e2d8ba2602d.png)

Could you please check and clarify if you see issues on these websites?

**Comment by Vooha-QualiTlabs** [comment]
@Dmitry-Ostashev Those are working fine for me. From which location are you accessing?

**Comment by Dmitry-Ostashev** [comment]
@Vooha-QualiTlabs, I'm trying to open the website from Russia.

**Comment by Vooha-QualiTlabs** [comment]
I will check with my dev team @Dmitry-Ostashev

**Comment by Vooha-QualiTlabs** [comment]
@Dmitry-Ostashev Can you try with this dev environment https://xeni.dev.booking.clubxeni.com/?

**Comment by Dmitry-Ostashev** [comment]
@Vooha-QualiTlabs Thank you, I reproduced the error with the [testcafe-hammerhead proxy playground](https://github.com/DevExpress/testcafe-hammerhead#first-look). It seems that your web application uses React Router, and the issue looks similar to the following ones: [https://github.com/DevExpress/testcafe-hammerhead/issues/2147](https://github.com/DevExpress/testcafe-hammerhead/issues/2147), [https://github.com/DevExpress/testcafe/issues/3337](https://github.com/DevExpress/testcafe/issues/3337).

**Comment by Vooha-QualiTlabs** [comment]
@Dmitry-Ostashev Okay, thank you. Could you let me know when can this be fixed? thank you.

**Comment by Dmitry-Ostashev** [comment]
@Vooha-QualiTlabs We cannot give an exact estimate on this issue because it could be misleading. We will update this thread once we have news. Please stay tuned.

Also, could you check the example mentioned in this issue: [https://github.com/DevExpress/testcafe-hammerhead/issues/2147](https://github.com/DevExpress/testcafe-hammerhead/issues/2147) to see if the React Router history is used in the same way in your application? This could help us determine the cause of the issue and find a solution.

**Comment by Vooha-QualiTlabs** [comment]
@Dmitry-Ostashev I am not sure I understand the issue that you wanted me to check, however I have tried but I don't see any issue with the router history.
The issue we have found is the proxy and the previous URL is also being appended to the API request.

![image](https://user-images.githubusercontent.com/91185844/147907467-8ad0919b-033b-4777-b299-e79823c3a47a.png)
![image](https://user-images.githubusercontent.com/91185844/147907481-8cb89f10-bf5b-49a2-8cd0-a017a7f8371c.png)

**Comment by miherlosev** [comment]
Hi @Vooha-QualiTlabs 

Thank you for the information. We will investigate it.

**Comment by Vooha-QualiTlabs** [comment]
@miherlosev Any update on this? thank you.

**Comment by Vooha-QualiTlabs** [comment]
@miherlosev This issue is sorted out from our side. The cause for this is we are verifying the agency name with the referrer header in the request. With the Testcafe, it is sending the proxy server URL as the referrer. Our developer has found the cause and we have added the `Custom-Referrer` as our website URL. Now, it is working fine. We can close this issue.
