### ISSUE TITLE
Authentication Workflow Redirection fails

### ISSUE THREAD

**Issue by brownhoward** [DevExpress/testcafe#6809]
### What is your Scenario?

I am testing an open source application PodBrowser (https://podbrowser.inrupt.com) against several Solid (https://solidproject.org) servers. The authentication workflow requires a number of redirections:

1. User opens https://podbrowser.inrupt.com.
2. On Login page, user enters a IdP URL (e.g., https://broker.pod.inrupt.com) and is redirected to that IdP for authentication.
3. After successful authentication, the user is redirected to Allow access to your WebID.
4. After Allowing, the user is redirected back to PodBrowser.
5. The PodBrowser main Files page is displayed.

### What is the Current behavior?

The described authentication workflow works correctly manually, and has been working (mostly) for many months via TestCafe tests. But suddenly the tests hang between steps 4 & 5. 

### What is the Expected behavior?

PodBrowser Files page is displayed after successful authentication.

### What is your public website URL? (or attach your complete example)

https://podbrowser.inrupt.com

### What is your TestCafe test code?

```
import { screen } from "@testing-library/testcafe";
import { t, ClientFunction } from "testcafe";

// Get the Window Size
export async function getWindowSize() : Promise<Record<string, number>> {
    const fn = ClientFunction(() => {
        return {
            width:window.innerWidth,
            height: window.innerHeight
        };
    });

    return fn();
}


// Login Fixture
fixture("Login")
    .page("https://podbrowser.inrupt.com");


// Login
test("Login", async() => {

    await t.wait(1000);

    let otherProvidersButton = screen.findAllByTestId("other-providers-button");
    let loginTextbox = screen.getByTestId("login-field");
    let identityCombobox = screen.getByRole("textbox", { name: /select id provider/i });
    let goButton = screen.getByTestId("go-button");

    // Log in via ESS Broker service
    await t
        .expect(otherProvidersButton.exists).ok("Other Provier button exists");

    await t
        .click(otherProvidersButton)
        .expect(loginTextbox.exists).ok("Login Textbox exists");
    
    await t
        .click(loginTextbox)
        .typeText(loginTextbox, "https://broker.pod.inrupt.com", { replace: true, paste: true })
        .expect(goButton.exists).ok("Go button exists");

    await t
        .click(goButton);

    // Submit Button visible?
    const isSubmitVisible:boolean = await screen.findByRole("button", { name: /submit/i }).visible;
    if (isSubmitVisible) {

        // Resize Window
        const windowSize = await getWindowSize();
        let resized = false;
        if (windowSize.width >= 640) {
            resized = true;
            await t.resizeWindowToFitDevice("iphone6", {portraitOrientation: true});
            await t.wait(1000);
        }

        // Username
        await t.typeText(screen.findByRole("textbox", { name: /username username/i }), "{username}", { replace: true, paste: true });

        // Password
        await t.typeText(screen.findByLabelText(/password/i), "{password}", { replace: true, paste: true });

        // Submit
        await t.click(screen.findByRole("button", { name: /submit/i }));

        // Resize Window
        if (resized) {
            await t.resizeWindow(windowSize.width, windowSize.height);
        }
    }

    // Authorize our client application to access Pod resources
    const isAllowVisible:boolean = await screen.findByRole("button", { name: /allow/i }).visible;
    if (isAllowVisible) {
        await t
            .click(screen.findByRole("button", { name: /allow/i }));
    }

    // Has the application been opened?
    await t.wait(5000);
    await t.expect(screen.findByRole("heading", { name: /files/i }).visible).ok("");
});
```

### Your complete configuration file
```
{
    "clientScripts": [
        { "module": "@testing-library/dom/dist/@testing-library/dom.umd.js" }
    ],
    "reporter": [
        {
          "name": "spec"
        }
    ],
    "debugMode": false,
    "debugOnFail": false,
    "stopOnFirstFail": false,
    "skipJsErrors": true,
    "skipUncaughtErrors": true,
    "concurrency": 1,
    "quarantineMode": {
        "attemptLimit": 3,
        "successThreshold": 1
    }
}
```
### Your complete test report
```
 Running tests in:
 - Microsoft Edge 96.0.1054.62 / Windows 10

 Login
 × Login (screenshots:
 C:\GitHub\inrupt\PodBrowser-TestCafe\screenshots\2022-01-05_15-02-35\test-1\Microsoft_Edge_96.0.1054.62_Windows_10\errors\1.png)

   1) AssertionError: expected false to be truthy

      Browser: Microsoft Edge 96.0.1054.62 / Windows 10
      Screenshot:

   C:\GitHub\inrupt\PodBrowser-TestCafe\screenshots\2022-01-05_15-02-35\test-1\Microsoft_Edge_96.0.1054.62_Windows_10\errors\1.png

         80 |            .click(screen.findByRole("button", { name: /allow/i }));
         81 |    }
         82 |
         83 |    // Has the application been opened?
         84 |    await t.wait(5000);
       > 85 |    await t.expect(screen.findByRole("heading", { name: /files/i }).visible).ok("");
         86 |});
         87 |

         at <anonymous> (C:\GitHub\inrupt\PodBrowser-TestCafe\login.ts:85:78)
         at fulfilled (C:\GitHub\inrupt\PodBrowser-TestCafe\login.ts:5:58)



 1/1 failed (1m 31s)
```

### Steps to Reproduce

1. Create a PodBrowser account at https://signup.pod.inrupt.com
2. Update test code with {username} and {password}
3. Execute TestCafe test `> testcafe chrome login.ts`

### TestCafe version

Using locally installed version of TestCafe. 1.18.1

### Node.js version

v17.0.1

### Command-line arguments

testcafe edge ./login.ts

### Browser name(s) and version(s)

Microsoft Edge 96.0.1054.62

### Platform(s) and version(s)

Window 10 Pro

**Comment by justin-barca-at-camis** [comment]
I am having problems with this issue too. I am using the `@openid/appauth` package which by default uses localStorage to perform an authentication flow. My app starts on `http://172.30.160.1:49782` and then redirects to a login page (on a different domain). The testcafe server is still on the same url. Then, when the login page redirects back to my app, the server is now on `http://172.30.160.1:49783` so the data saved in localStorage upon login redirect can't be retrieved. Although hammerhead seems to do some proxying so that the "true" domain ends up in the key of the localstorage item and the items are scoped to the domain, none of this matters if the testcafe server changes ports.

**Comment by miherlosev** [comment]
Hi @justin-barca-at-camis 

Thank you for the shared information. I've reproduced the issue.

**Comment by kevin-inrupt** [comment]
Hi @miherlosev,

Good that you have been able to replicate. Before contacting you, I tried the suggestions in over tickets (`.disablePageCaching`, `node --max-http-header-size=1024000 ./node_modules/testcafe/bin/testcafe.js chrome login.ts`) but nothing seemed to work.

Any pointers/recommendations/suggestions would be appreciated.

**Comment by miherlosev** [comment]
@kevin-inrupt

At present, we haven't found the cause of the issue. So, we cannot share any workarounds. We will update this thread once we have news.
