### ISSUE TITLE
TestCafe hangs if the specified screenshots directory contains forbidden symbols

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#681]
`mkdirp` falls into infinite recursion, if the specified path contains some forbidden symbols, e.g. `':'` on Windows. To reproduce, just try: 

`node .\bin\testcafe.js remote test.js -s .\scrs:\`

**Comment by AndreyBelym** [comment]
https://github.com/substack/node-mkdirp/issues/70

**Comment by inikulin** [comment]
We can consider switching to another package if this one is abandoned

**Comment by AndreyBelym** [comment]
I'm working on it.
