### ISSUE TITLE
Testcafe v1.8.8 is not running for node 8.93

### ISSUE THREAD

**Issue by future-mine** [DevExpress/testcafe#6811]
### What is your Scenario?

I was running testcafe v1.8.8 for node 8.9.3
It was working well.

### What is the Current behavior?

Recently I reinstalled testcafe 1.8.8 and getting this error.
![image](https://user-images.githubusercontent.com/59634187/148742902-ed432f2a-e75b-4869-ab05-4027301e4fff.png)
But now I am getting this issue.

### What is the Expected behavior?

It should open a testcafe popup but it didn't

### What is your public website URL? (or attach your complete example)

There is not public.
Just for a simple test. it didn't work.

```
import { APP_URL } from '../lib/config';
fixture('term-condition').page(`${APP_URL}/`);

const sleep = (ms) => new Promise((resolve)=>setTimeout(resolve, ms))
test('Test', async (t) => {
  await sleep()
})
```

### What is your TestCafe test code?

import { APP_URL } from '../lib/config';
fixture('term-condition').page(`${APP_URL}/`);

const sleep = (ms) => new Promise((resolve)=>setTimeout(resolve, ms))
test('Test', async (t) => {
  await sleep()

### Steps to Reproduce

1. install node 8.9.3
2. install testcafe 1.8.8
3. create a simple test.
4. Run the test with installed testcafe

### TestCafe version

1.8.8

### Node.js version

8.9.3

### Command-line arguments

testcafe chrome -e tests/test.test.js

**Comment by felis2803** [comment]
Hello,

I could not reproduce this bug. It may be specific to your application. Please try to reproduce it on any public website.
