### ISSUE TITLE
Handling of native dialogs inconsistent with handling in Firefox

### ISSUE THREAD

**Issue by dfn-certling** [DevExpress/testcafe#6815]
### What is your Scenario?

I have a form with a `beforeunload` handler attached on changes. I want to write a test that verifies the conditions of the dialog being shown.

### What is the Current behavior?

The dialog appears when opened in the browser directly, but it is not triggered when exercised in a test.

### What is the Expected behavior?

The dialog should be triggered in the test.

### What is your public website URL? (or attach your complete example)

The behavior can be reproduced with the following example page

```html
<html>
<body>
    <script>
        var formSubmitting = false;
        var setFormSubmitting = function () { formSubmitting = true; };

        window.onload = function () {
            window.addEventListener("beforeunload", function (e) {
                if (formSubmitting) {
                    return undefined;
                }

                e.preventDefault();
                e.returnValue = '';
            });
        };
    </script>
    <form method="post" onsubmit="setFormSubmitting()">
        <input type="text">
        <button type=submit>Ok!</button>
    </form>
    <button type="button" onclick="window.location.reload()">Refresh!</button>
</body>
</html>
```

This is an adaption of the example used in https://github.com/DevExpress/testcafe/issues/5994#issuecomment-789537195. According to the [MDN documentation on onbeforeunload](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload) strings returned or set for `returnValue` are not presented to the user anymore. The example present in the documentation gives the above `e.preventDefault()` and `e.returnValue` commands to display the dialog, which works in Firefox directly.

### What is your TestCafe test code?

```js
import { Selector } from 'testcafe';

fixture `New Fixture`
    .page `file:///<path>/test.html`
    
test(`New Test`, async t => {
    await t
        .setNativeDialogHandler(() => true)
        .typeText('form input', 'wqeqweqw')    
        .click(Selector('button').withText('Refresh!'))

    console.log(await t.getNativeDialogHistory());
});
```

### Your complete configuration file

No further configuration

### Your complete test report

```
 Running tests in:
 - Firefox 95.0 / Linux 0.0

 New Fixture
[]
 ✓ New Test


 1 passed (1s)
```

### Steps to Reproduce

1. Run the above test with Firefox; at least in my setup no dialog is logged
2. Compare with opening the page directly in the browser and testing by hand

Curiously some changes to the example page do trigger it. One way is to set a nonempty string for the `returnValue`, another one is to switch the order of calling `preventDefault` and setting `returnValue`. None of these changes change the result when testing in the browser directly, and they are not required by my reading of the MDN documentation. This only happens in Firefox, Brave for example (Chromium based) triggers the dialog also in the test all the time.

### TestCafe version

1.18.1

### Node.js version

v16.13.1

### Command-line arguments

testcafe firefox test-handler.js

### Browser name(s) and version(s)

Firefox 95.0

### Platform(s) and version(s)

openSUSE Tumbleweed

**Comment by aleks-pro** [comment]
Hello @dfn-certling ,

Thank you for pointing out this issue and sharing the code example.
We reproduced the empty output for the Firefox browser. We will research this issue in detail.

**Comment by dfn-certling** [comment]
The issue is still present as originally described with TestCafe 2.2.0, Node v16.18.0 and Firefox 108.0.2.

**Comment by AlexKamaev** [comment]
fixed in https://github.com/DevExpress/testcafe-hammerhead/pull/2980
