### ISSUE TITLE
cannot filter elements by shadow DOM

### ISSUE THREAD

**Issue by soletan** [DevExpress/testcafe#6820]
### What is your Scenario?

I'm trying to filter sets of nodes matching a particular selector based on properties per match that are found in shadow DOMs.

### What is the Current behavior?

Selector methods such as `withText()` are intended to narrow down the number of matching elements. In opposition to methods like `find()`, those methods don't replace all nodes in a set of matching nodes, but reduce such a set instead. These semantics apply unless working with custom components that happen to use a shadow DOM. In those cases, `shadowRoot()` must be used before using `withText()` which results in replacing all nodes of original set with either node's subordinated shadow DOM. After that, interaction with resulting set of reduced nodes such as clicking isn't possible anymore.

### What is the Expected behavior?

Using shadowRoot() should not adjust the set of matching nodes.

### What is your public website URL? (or attach your complete example)

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
    </head>
    <body>
        <script>
            class CustomButton extends HTMLElement {
                constructor() {
                    super();

                    this.attachShadow({mode: "open"});
                }

                connectedCallback() {
                    const label = document.createElement("label");
                    const text = document.createTextNode(this.getAttribute("content"));
                    label.appendChild(text);

                    this.shadowRoot.appendChild(label);
                }

                disconnectedCallback() {
                    this.shadowRoot.removeChild(this.shadowRoot.firstChild);
                }
            }

            customElements.define("my-button", CustomButton );

        </script>
        <h1>
            Shadow Buttons
        </h1>
        <ul>
            <li>
                <my-button content="first shadow button"></my-button>
            </li>
            <li>
                <my-button content="second shadow button"></my-button>
            </li>
        </ul>
        <h1>
            Light Buttons
        </h1>
        <ul>
            <li>
                <button>
                    <label>first light button</label>
                </button>
            </li>
            <li>
                <button>
                    <label>second light button</label>
                </button>
            </li>
        </ul>
    </body>
</html>
```

### What is your TestCafe test code?

```javascript
const {Selector} = require( "testcafe" );

fixture`Filtering with and without shadow`.page("http://localhost:3000/fiddle.html");

const shadowButtons = Selector("my-button");
const lightButtons = Selector("button");

test("can click light button with particular label", async t => {
    await t.expect(lightButtons.exists).ok();

    const second = lightButtons.withText("second light button");
    await t.expect(second.exists).ok();

    await t.click(second);
    await t.expect(second.tagName).eql("button");
});

test("can click shadow button with particular label", async t => {
    await t.expect(shadowButtons.exists).ok();

    let second = shadowButtons.withText("second shadow button");
    await t.expect(second.exists).notOk();

    second = shadowButtons.shadowRoot().withText("second shadow button");
    await t.expect(second.exists).ok();

    await t.click(second); // fails for second is addressing the shadow DOM's root of matching button
    await t.expect(second.tagName).eql("my-button"); // would fail as well ...
});
```

### Your complete test report

```
$ npx testcafe chrome fiddle-test.js
 Running tests in:
 - Chrome 97.0.4692.71 / Windows 10

 Filtering with and without shadow
 √ can click light button with particular label
 × can click shadow button with particular label

   1) The specified selector is expected to match a DOM element, but it matches a document fragment node.

      Browser: Chrome 97.0.4692.71 / Windows 10

         22 |    await t.expect(second.exists).notOk();
         23 |
         24 |    second = shadowButtons.shadowRoot().withText("second shadow button");
         25 |    await t.expect(second.exists).ok();
         26 |
       > 27 |    await t.click(second); // fails for second is addressing the shadow DOM's root of matching button
         28 |    await t.expect(second.tagName).eql("my-button"); // would fail as well ...
         29 |});
         30 |

         at <anonymous> (C:\foo\fiddle-test.js:27:13)
         at asyncGeneratorStep (C:\foo\fiddle-test.js:1:114)
         at _next (C:\foo\fiddle-test.js:1:452)



 1/2 failed (12s)
```

### Steps to Reproduce

1.
2.
3.

### TestCafe version

1.18.1

### Node.js version

16.13.0

### Command-line arguments

testcafe chrome fiddle-test.js

### Browser name(s) and version(s)

Chrome 97.0.4692.71

### Platform(s) and version(s)

Windows 10

### Other

The example can be circumvented by checking the attributes of custom components instead of using withText() on the shadow DOM. But that's meant for illustration purposes, only.

**Comment by Dmitry-Ostashev** [comment]
TestCafe cannot perform actions with a node returned by the `shadowRoot()` method. You need to operate with child nodes of the shadow DOM. For example:

> second = shadowButtons.shadowRoot().**find('label')**.withText("second shadow button");


Refer to this note for details: https://testcafe.io/documentation/402745/reference/test-api/selector/shadowroot

**Comment by soletan** [comment]
I think, you've missed my intention. I don't care about trying to act on the shadowRoot itself. The referenced note is basically explaining the presented outcome I've posted, but that's the point of this issue.

Based on what is listed on page https://testcafe.io/documentation/402666/reference/test-api/selector, I don't want to _search for elements relative to a custom component_ (using one of the methods in second table on that page), but _filter element from the selector_ (using methods from the first table without mapping all elements of current selector).

E.g. how do I achieve a test scenario like this one? There are 5 buttons made as custom components each with different text content (and I don't care if it's a label element or a span or some combination of both) implemented in shadow DOM. I want to get all of these 5 buttons with their textContent matching `/\bcreate\b/i` and when I got those I want to keep on testing the resulting set of two custom components, not some labels inside of them, e.g. for matching a given class or any other attribute or look for the succeeding sibling of either component in the light DOM.

**Comment by Dmitry-Ostashev** [comment]
Thank you for the clarification. TestCafe selectors internally use the `document.querySelectorAll` method, which does not dive into the shadow DOM and does not allow obtaining custom element's text content. So, TestCafe does not allow filtering shadowRoot elements.

As a workaround, you can implement your own filter callback as follows:

```
const shadowButtons = Selector("my-button");
const second = shadowButtons.filter(node => /second shadow button/.test(node.shadowRoot.textContent));
```
