### ISSUE TITLE
skip waiting for XHR/fetch to resolve

### ISSUE THREAD

**Issue by dasDaniel** [DevExpress/testcafe#6822]
### What is your Scenario?

I have a UI that will make an API request while user types. Until  the API is resolved, a button should be disabled.

While the [functionality to wait for the XHR and fetch requests to resolve](https://testcafe.io/documentation/402827/guides/concepts/built-in-wait-mechanisms#wait-mechanism-for-xhr-and-fetch-requests), it makes testing this behavior more complicated.

It would be helpful if this 3 second wait could be skipped in such scenarios.

### What are you suggesting?

something like `awaitFetch:false`  to skip waiting for 3 seconds

```js
t.typeText(Selector('input'), 'yoo hoo', {awaitFetch:false });
```

### What alternatives have you considered?

Stretching to mock timeout, but too long slows down tests and too short becomes flaky.

I've also tried storing a resolve function for a promise in a global variable which gets called during the test. 

```js
let resolveFn = null;

RequestMock()
  .onRequestTo(/my\-trunk/)
  .respond(async (req, res) => {
    await new Promise((resolve) => (resolveFn = resolve));
    res.setBody("my junk");
  });

// in test...
  await t.typeText(Selector('input'), 'yoo hoo', {awaitFetch:false });
  resolveFn()
```

but it still waits for those 3 extra seconds, but it's now less flaky

**Comment by miherlosev** [comment]
Hi @dasDaniel

> it makes testing this behavior more complicated.

Could you please share a test code example that illustrates the described behavior?

**Comment by dasDaniel** [comment]
> Hi @dasDaniel
> 
> > it makes testing this behavior more complicated.
> 
> Could you please share a test code example that illustrates the described behavior?

sure, here's a repo

https://github.com/dasDaniel/example-testcafe-timeout

This illustrates the workaround, but if I start to add more complexity, like a long debounce, this will no longer work as-well.

If there are many of such assertions in the test, this can make the time to complete test grow very fast.

**Comment by miherlosev** [comment]
Hi @dasDaniel

In your test, you try to check that the `myBtn` button is disabled during the fetch request to the `api.json` resource. Since the request is performed very fast on a local machine, it's difficult to check the disabled state of the `myBtn` button.
If you perform the test actions manually, you will see the same result.
To check the disabled state, the approach from your test is correct.
Also, you can imitate the fixed delay of the `api.json` resource:

```js
import { RequestMock, Selector } from "testcafe";

const API_DELAY = 10000;

const mock = RequestMock()
  .onRequestTo(/api\.json/)
  .respond(async (req, res) => {
    await new Promise((resolve) => {
        setTimeout(resolve, API_DELAY);
    });
    res.setBody({ ok: "👌" });
  });

fixture`example`.page`http://127.0.0.1:7772/index.html`.requestHooks(mock);

test("example", async (t) => {
  const btn = Selector("button"),
    input = Selector("input");

  await t
    // assert button enabled
    .expect(btn.hasAttribute("disabled"))
    .notOk()

    // add some text
    .typeText(input, "🤖")

    // assert button disabled
    .expect(btn.hasAttribute("disabled"))
    .ok()
    .wait(API_DELAY);

  // now check that it is enabled again
  await t.expect(btn.hasAttribute("disabled")).notOk();
});
```
```
