### ISSUE TITLE
Add possibility to mock/intercept multipart/form-data requests

### ISSUE THREAD

**Issue by marpapikyan** [DevExpress/testcafe#6824]
### What is your Scenario?

I need to send a mock video to the server.

### What are you suggesting?

I suggest to add a possibility in Request Mock to handle multipart/form-data mocking as well.

**Comment by aleks-pro** [comment]
Hello @marpapikyan ,

Please describe your scenario in greater detail. What exact functionality do you miss in TestCafe (filtering by the content-type header with the multipart/form-data value, the possibility to send several response pieces for a single request)?
