### ISSUE TITLE
Research possibility to run tests in web with Codespaces

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#6831]

**Comment by WidgetKing** [comment]
Any luck?

I've been playing around with using remote testing. I feel like I have gotten achingly close. The testcafe server is running in codespaces, a QR code appears in the terminal, the port is forwarded and public, but when I open it GitHub tells me the page doesn't exist.

Would be really nice to have a minimum viable testcafe codespaces repo as a starting point. I was using Cypress before, but that's a major headache to get working in codespaces. That's what turned my head to testcafe.

**Comment by AlexKamaev** [comment]
This is in our plans. However, at present, we are still not ready to share any results and give any estimates on this.

**Comment by WidgetKing** [comment]
Understood. Will stay tuned.

**Comment by AndreyBelym** [comment]
Browsers in headless are fully functional. You can install them with `apt` in the base Codespace image, or use a custom image with preinstalled browsers (e.g. our official image).

If you want to connect your local browser as a remote, you had to bypass our [hostname and ports validation code](https://github.com/DevExpress/testcafe/blob/21e774d6bfb1f8e7a15a44040499f0777fda20f2/src/index.js#L18) and override [public ports and hostname in hammerhead](https://github.com/DevExpress/testcafe-hammerhead/blob/72fe9e6daa2a2badbacb8c39e597c54567cee286/src/proxy/index.ts#L72). 

Since Codespaces are available for Github Teams only, I cannot provide a public demo for now. We should research how to improve UX (including for non-Github users) and performance, so we can use this technology for our online demos. Considering this as closed.
