### ISSUE TITLE
t.maximizeWindow with firefox:headless casues testcafe to hang

### ISSUE THREAD

**Issue by zoe-jobson-IL** [DevExpress/testcafe#6835]
### What is your Scenario?

use t.maximize window on all browsers - or error cleanly and not hang.

### What is the Current behavior?

firefox:headless casues a hang - and even the test timeout doesn't kick off we have to kill any test process involving a test with t.maximizeWindow

### What is the Expected behavior?

maximizeWindow can be used with all browsers headless or headed without a hang.

### What is your public website URL? (or attach your complete example)

https://www.immersivelabs.com

### What is your TestCafe test code?

/* eslint-disable no-console */
import { Selector } from "testcafe";

fixture("Broken test")
  .page(`https://www.immersivelabs.com/`)
  .beforeEach(async (t) => {
    console.log("hello");
    await t.maximizeWindow();
  });

test.meta("testFeature", "badTest").meta("role", "smoke")(
  "Test to demo firefox issue",
  async (t) => {
    const demo = Selector("a[href='/demo/']");
    await t.expect(demo.exists).ok("Get a demo exists");
  }
);

### Your complete configuration file

{
  "src": "./testcafe/tests/**/*.ts",
  "videoPath": "results/videos",
  "testExecutionTimeout": 5000
}

### Your complete test report

PS C:\Users\user\CODE\testcafe> testcafe firefox:headless  --test-meta testFeature=badTest 
Using locally installed version of TestCafe.
The "filter" option from the configuration file will be ignored.
 Running tests in:
 - Firefox 95.0 / Windows 10

 Broken test
hello

### Screenshots

impossible due to hang

### Steps to Reproduce

just run testcafe firefox:headless  --test-meta testFeature=badTest with the test and config above

### TestCafe version

1.18.1

### Node.js version

14.16.1

### Command-line arguments

testcafe firefox:headless  --test-meta testFeature=badTest

### Browser name(s) and version(s)

firefox:headless (I have also tried firefox, chrome, chrome:headless and edge:headless)

### Platform(s) and version(s)

windows, and testcafe docker image linux

### Other

we have ffmpeg installed for videos as per webpage.
Its the combination of video and firefox:headless that causes the hang

**Comment by Dmitry-Ostashev** [comment]
Thank you for your report. I reproduced the issue. We will research it and update this thread once we have any news.
