### ISSUE TITLE
Communication between iFrame and parent window doesn't work

### ISSUE THREAD

**Issue by aleks-pro** [DevExpress/testcafe#6847]
### What is your Scenario?

Test an application with an iFrame. The iFrame communicates with the parent window via `window.parent.postMessage` API

### What is the Current behavior?

A parent window receives a message, but its' data is empty. Without TestCafe everything works as expected.

### What is the Expected behavior?

The message data should not be empty

### What is your TestCafe test code?

```js
fixture`Foo`
  .page`http://localhost:8000`;

test('Bar', async t => {
  await t
    .debug()
    .wait(120000);
});
```

### Steps to Reproduce

Use the following example to reproduce the issue: [postMessageIssue.zip](https://github.com/DevExpress/testcafe/files/7971764/postMessageIssue.zip)

1. Run `server.js` script: `node server.js`
2. Run `test.ts` TestCafe test: `testcafe chrome test.ts`

### TestCafe version

1.18.3

### Node.js version

v16.5.0

### Command-line arguments

testcafe chrome test.ts

### Other

You can find additional details here: https://stackoverflow.com/questions/70862884/when-running-testcafe-some-language-constructs-ruin-the-postmessage-from-an-ifra

**Comment by AlexKamaev** [comment]
Additional info from user:
>Meanwhile I found out, that this is a bug in AppleWebkit < 14 which is used in the TestCafe-Browser as well. 
https://stackoverflow.com/questions/70862884/when-running-testcafe-some-language-constructs-ruin-the-postmessage-from-an-ifra
