### ISSUE TITLE
Using .testcaferc.js file results in error "This file is not a well-formed JSON file."

### ISSUE THREAD

**Issue by maximojoexpress** [DevExpress/testcafe#6855]
### What is your Scenario?

Attemp to pass in a [.testcaferc.js file per documentation](https://testcafe.io/documentation/402638/reference/configuration-file#javascript) results in the below:

> Failed to parse the 'D:/source/test/.testcaferc.js' file.
> 
> This file is not a well-formed JSON file.

The contents of the .testcaferc.js file are from [the documentation](https://testcafe.io/documentation/403435/guides/advanced-guides/hooks#global-hooks) as below:

> module.exports = {
>     hooks: {
>         fixture: {
>             before: async (ctx) => {
>                 // your code
>             },
>             after: async (ctx) => {
>                 // your code
>             }
>         },
>         test: {
>             before: async (t) => {
>                 // your code
>             },
>             after: async (t) => {
>                 // your code
>             }
>         }
>     }
> };

I pass in the switch below:

> --config-file D:/source/test/.testcaferc.js

### What is the Current behavior?

The error below is seen and the .testcaferc.js file is not used:

> Failed to parse the 'D:/source/test/.testcaferc.js' file.
> 
> This file is not a well-formed JSON file.

### What is the Expected behavior?

The .testcaferc.js file is loaded and used. No error is seen.

### What is your public website URL? (or attach your complete example)

Apologies, I cannot share our app.

### What is your TestCafe test code?

> module.exports = {
>     hooks: {
>         fixture: {
>             before: async (ctx) => {
>                 // your code
>             },
>             after: async (ctx) => {
>                 // your code
>             }
>         },
>         test: {
>             before: async (t) => {
>                 // your code
>             },
>             after: async (t) => {
>                 // your code
>             }
>         }
>     }
> };

### Your complete configuration file

> module.exports = {
>     hooks: {
>         fixture: {
>             before: async (ctx) => {
>                 // your code
>             },
>             after: async (ctx) => {
>                 // your code
>             }
>         },
>         test: {
>             before: async (t) => {
>                 // your code
>             },
>             after: async (t) => {
>                 // your code
>             }
>         }
>     }
> };

### Steps to Reproduce

1. Attempt to launch a simple testcafe test with a .testcaferc.js file using the commandline parameter
> --config-file D:/source/test/.testcaferc.js
2. Observe the output

### TestCafe version

1.14.0

### Node.js version

10

### Command-line arguments

--config-file D:/source/test/.testcaferc.js

**Comment by VasilyStrelyaev** [comment]
JavaScript configuration files were [introduced in v1.16.0](https://github.com/DevExpress/testcafe/blob/master/CHANGELOG.md#v1160-2021-09-08). In previous versions, including v1.14.0 you are using, TestCafe could read only JSON configuration files. Please upgrade TestCafe to the latest version and try again.

**Comment by maximojoexpress** [comment]
> JavaScript configuration files were [introduced in v1.16.0](https://github.com/DevExpress/testcafe/blob/master/CHANGELOG.md#v1160-2021-09-08). In previous versions, including v1.14.0 you are using, TestCafe could read only JSON configuration files. Please upgrade TestCafe to the latest version and try again.

Right. Unfortunately we are stuck at node 10 for the moment. Will have to wait to upgrade as > TestCafe v15 requires > node v12.

Thanks
