### ISSUE TITLE
Screenshots are not saved correctly if the browser path is specified

### ISSUE THREAD

**Issue by peskovaa** [DevExpress/testcafe#6857]
### What is your Scenario?

start test with browser path
issue:               testcafe 'path:`C:/Program Files/Google/Chrome/Application/chrome.exe`' c:\1.ts

works correct:  testcafe chrome c:\1.ts

### What is the Current behavior?

The whole visible body selector on the picture

### What is the Expected behavior?

Only specified element should be on the picture

### What is your public website URL? (or attach your complete example)

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style>
        .custom{
            width: 100px;
            height: 100px;
            background-color: blue;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div class="custom">
        </div>
    </form>
</body>
</html>

### What is your TestCafe test code?

test
    .page(`1.aspx`)
    ('Test', async t => {        
            await t.takeElementScreenshot(Selector('.custom'), '111.png');
        }
    );

### Steps to Reproduce

1. start test
2. check picture

### TestCafe version

1.18.3

### Command-line arguments

testcafe 'path:`C:/Program Files/Google/Chrome/Application/chrome.exe`' c:\1.ts

### Browser name(s) and version(s)

chrome 98

**Comment by AlexKamaev** [comment]
Thank you for sharing the example with us. I was able to reproduce the issue. Please follow this ticket to track our progress.
