### ISSUE TITLE
Use typescript for global hooks

### ISSUE THREAD

**Issue by Georgegriff** [DevExpress/testcafe#6867]
### What is your Scenario?

We have hook code written in typescript that we currently have to copy and paste to all our tests, it would be nice to be able to define our global fixture/test hook code once but because it's written in typescript we would have to pre-compile it in order to use it in the JavaScript config file

### What are you suggesting?

Some mechanism for defining a file where you hooks can live instead of the code being directly in the config file. For example if you could specify a path to your hooks file instead of the functions directly this code could be written in typescript and compiled by testcafe

### What alternatives have you considered?

Compiling the code before using it, this would be a little awkward as it would require two typescript builds one before testcafe starts and the one by testcafe.

I had the thought that we could maybe do this as a work around: 

```js
module.exports = {
    hooks: {
        fixture: {
            before: async (ctx) => {
                const {before} = require("./ts-compiled/hooks")
                await before(ctx);
            },
            after: async (ctx) => {
                const {after} = require("./ts-compiled/hooks")
                await after(ctx);
            }
        },
        test: {
            before: async (t) => {
                const {beforeTest} = require("./ts-compiled/hooks")
                await beforeTest(ctx);
            },
            after: async (t) => {
                const {afterTest} = require("./ts-compiled/hooks")
                await afterTest(ctx);
            }
        }
    }
};
```

but there does not seem to be a way to find out where the TS is compiled to by testcafe or not clear if testcafe would know to compile these files at all

**Comment by AlexKamaev** [comment]
Thank you for your suggestion. We'll take it into account.

**Comment by srsholmes** [comment]
This would be really handy to have.
