### ISSUE TITLE
Make it easier to use test cafe with DevExtreme control

### ISSUE THREAD

**Issue by andrew-vdb** [DevExpress/testcafe#6868]
### What is your Scenario?

At this moment I'm writing test cafe test which test DevExtreme control, I found it extremely hard and wondering if you guys from same company test it with test cafe? For example testing select box recipe is just html select box, try to test cafe DevExtreme select box, you will be surprised how difficult it is to implement

### What are you suggesting?

Obviously we can't complain to DevExtreme to change how they render the component
I did try to get the instance of the component from test cafe, but does not seems to work

### What alternatives have you considered?

Keep hacking but not sure anymore if its the right direction

**Comment by felis2803** [comment]
Hello @andrew-vdb,

The DevExtreme team uses TestCafe to test their components. They also face similar challenges, so they create page models and helpers.
I think you're right, and it would be great to make it easier to test DevExtreme components with some kind of adapter. We will discuss this with the DevExtreme team.
Do you have any specific suggestions on how this might look like?

**Comment by andrew-vdb** [comment]
in the end, within my test cafe, i can call my vue component method (therefore it call devextreme method component)
So for filling the form and assert the value, i use vue component method
but to trigger the submit, still using test cafe click button
that make my life hundred times easier

would be nice if your team can also share the helper right?

**Comment by felis2803** [comment]
I discussed this issue with the DevExtreme team.
The release of such a tool will require a lot of effort from the DevExtreme team and we do not expect it to appear anytime soon.
However, you can see how the DevExtreme team uses TestCafe [here](https://github.com/DevExpress/DevExtreme/tree/22_1/testing/testcafe). You can use their helpers and models to write your own tests.
