### ISSUE TITLE
Video recording is not supported by the "chrome" browser.

### ISSUE THREAD

**Issue by VadimKrim** [DevExpress/testcafe#6870]
### What is your Scenario?

Running from CLI `testcafe chrome -s takeOnFails=true --compiler-options typescript.customCompilerModulePath=../typescript --video ./videos --video-options failedOnly=true --video-encoding-options r=24 test.ts`

### What is the Current behavior?

When the test fails getting message "Video recording is not supported by the "chrome" browser."
No video recorded.

### What is the Expected behavior?

Video recording on failure should be created

### What is your public website URL? (or attach your complete example)

test.com

### What is your TestCafe test code?

<any code>

### Your complete test report

 Warnings (1):
 --
  Video recording is not supported by the "chrome" browser.

### Steps to Reproduce

1. Run from windows CLI `testcafe chrome -s takeOnFails=true --compiler-options typescript.customCompilerModulePath=../typescript --video ./videos --video-options failedOnly=true --video-encoding-options r=24 test.ts`

### TestCafe version

1.18.3

### Node.js version

16.10.0

### Command-line arguments

testcafe chrome -s takeOnFails=true --compiler-options typescript.customCompilerModulePath=../typescript --video ./videos --video-options failedOnly=true --video-encoding-options r=24 test.ts

### Browser name(s) and version(s)

Chrome Version 98.0.4758.82 (Official Build) (64-bit)

### Platform(s) and version(s)

Windows 10

**Comment by VadimKrim** [comment]
Cannot recreate. Works fine meanwhile...

**Comment by Jgrabenbauer** [comment]
I am getting the same when just running `ENV=staging testcafe chrome -t 'user_can_view_a_published_blog' -c1 `

**Comment by AlexKamaev** [comment]
@Jgrabenbauer, could you describe your usage scenario in greater detail? Usually, there are no issues with video recording in Chrome. I see that the Chrome browser you are using is installed on your machine. This means that video recording should work correctly.

Please send us a sample that demonstrates the issue.
