### ISSUE TITLE
TestCafe basic test failed with UnableToAccessScreenRecordingAPIError on macOS Big Sur 11.6.3

### ISSUE THREAD

**Issue by pragmatictesters** [DevExpress/testcafe#6871]
### What is your Scenario?

I am trying to the run a [basis TestCafe test](https://testcafe.io/documentation/402635/getting-started) from VS Code/Terminal window from a MacBook Air with Big Sur 11.6.3

[Screen recording ](https://www.screencast.com/t/bTlPOzqXqeyd)

### What is the Current behavior?

It prompts for screen recording permission.

It was not successful even after giving the permissions through the System Preference window.

Then I followed the instructions given in the [stackoverflow](https://stackoverflow.com/questions/71108522/testcafe-tests-are-not-executed-on-macbook-big-sur-with-unabletoaccessscreenreco/71108903#71108903).

Issue was not resolved.

Following error is thrown into the command line 
`admin@Macbooks-MacBook-Air tests % testcafe chrome temp_test.js
Using locally installed version of TestCafe.
TestCafe requires permission to record the screen. Open 'System Preferences > Security & Privacy > Privacy > Screen Recording' and check 'TestCafe Browser Tools' in the application list.

Press any key to retry.
ERROR UnableToAccessScreenRecordingAPIError: The find-window process cannot access the Screen Recording API.`

### What is the Expected behavior?

It's expected to run the test against the target browser.

### What is your public website URL? (or attach your complete example)

https://devexpress.github.io/testcafe/example

### What is your TestCafe test code?

import { Selector } from 'testcafe';

fixture`Getting Started`
    .page`https://devexpress.github.io/testcafe/example`;

test('My first test', async t => {
    await t
        .typeText('#developer-name', 'John Smith')
        .click('#submit-button');
});

### Your complete configuration file

{
  "browsers": ["chrome"],
  "skipJsErrors": true
}

### Steps to Reproduce

1. Install the testcafe from CLI with npm 
2. Create a basic test 
3. Run the test from VS code/command line
<<It prompt for setting screen recording permission>>
4. Set the required permission through System Preference  

[Screen recording ](https://www.screencast.com/t/bTlPOzqXqeyd)

### TestCafe version

1.18.3

### Node.js version

v16.13.0

### Command-line arguments

testcafe chrome temp_test.js

### Browser name(s) and version(s)

chrome

### Platform(s) and version(s)

macOS 11.6.3

### Other

There was no issue in running the test with TestCafe Studio

**Comment by aleks-pro** [comment]
Thank you for your inquiry. This issue looks like a question. We keep the GitHub issues tracker only for bugs and feature requests (see Contributing). So, let us discuss this problem in the thread that you created on StackOverflow.

If you believe that this is a bug, feel free to reopen it.
