### ISSUE TITLE
Screenshot pixel comparison - visual regression testing

### ISSUE THREAD

**Issue by ben-gooding-sky** [DevExpress/testcafe#6874]
### What is your Scenario?

Visual regression testing using testcafe. Compare screenshots that testcafe takes to test for changes to page styling.

### What are you suggesting?

Able to take a screenshot in a test, that then gets saved to a folder somewhere, then on subsequent tests that image is compared against to see for any regression.

### What alternatives have you considered?

Currently use backstop.js, but we would much rather share our POM's and use the testcafe api to write these tests.

**Comment by VasilyStrelyaev** [comment]
Thank you for your suggestion!

However, we have a similar one here: https://github.com/DevExpress/testcafe/issues/1207. Thus, I'm closing this issue. Please subscribe to https://github.com/DevExpress/testcafe/issues/1207 to stay tuned and keep track of our progress.
