### ISSUE TITLE
When you have a multi OS team t.keypress can fail

### ISSUE THREAD

**Issue by zoe-jobson-IL** [DevExpress/testcafe#6876]
### What is your Scenario?

We have a test which uses (on windows/linux) t.keypress("ctrl+alt+f"), this works fine on windows and linux, but when a mac user runs it the test fails becuase the same dialog requires "meta+alt+f" we have a workaround (testing for the OS and modifying the string and returning it), but would it be possible to encorporate OS knowledge into the code which handles the keypress ?

### What are you suggesting?

that the code which handles t.keypress either modifies ctrl to meta (and visa versa depending on OS), or at least notifies the user that they have used a key which doesn't exist in their OS.

**Comment by Dmitry-Ostashev** [comment]
Thank you for your suggestion. However, I don't think it's applicable to all cases. Perhaps, some users need to simulate Ctrl too on MacOS.

**Comment by zoe-jobson-IL** [comment]
I thought mac keyboards didn't have a ctrl key
