### ISSUE TITLE
Testcafe support for Babylon.js 5 input system

### ISSUE THREAD

**Issue by Mszpyt** [DevExpress/testcafe#6881]
### What is your Scenario?

I’m using testcafe test runner as a tool to automate some user actions and create e2e tests for 3d project based on Babylon.js . So far it worked very well but when I checked mouse drag movement simulation on Babylon.js v5 it is no longer working. I got answer from Babylon team that they modified the input system to work with an intermediate system to enable Babylon Native to work with various JS input classes - but I don't feel really competent in mouse simulation to try pinpoint the root cause myself. Here Is a topic on Babylon forum with more details and recordings along with TestCafe test example:
https://forum.babylonjs.com/t/babylon-js-5-changed-simulated-mouse-movement-behavior/27651/5

I suspect It's the way Testcafe simulates mouse movement which is not 1 to 1 with "true" mouse movement as it is in i.e. Playwright - where the drag movement is working just fine with Babylon 5. However I would much rather stay with TestCafe.

Would you mind hopping in the mentioned topic and let me know if you would be able/willing to adjust TestCafe to support Babylon.js 5 input system?

### What are you suggesting?

TestCafe to support Babylon.js 5 input system

### What alternatives have you considered?

Playwright mouse simulation works fine with Babylon.js 5.

**Comment by Mszpyt** [comment]
Here is detailed example and video how drag&drop is now working with Babylonjs version 5 vs 4:
https://drive.google.com/file/d/1URgHGpJluPo-ymJ0TXhb3_gYGeQbqIdn/view

Test is here (long):
`// @ts-nocheck
import { ClientFunction } from "testcafe";

//long func to get sphere location on screen
let getSphere = ClientFunction(() => {
  let tokenMesh = BABYLON.Inspector._Scene.getNodeByName("sphere1");
  let vector3 = BABYLON.Vector3;
  scene.preventDefaultOnPointerDown;
  const coordinates = tokenMesh._boundingInfo.boundingBox.vectors.map(
    (vector) =>
      vector3.Project(
        vector,
        tokenMesh._worldMatrix,
        BABYLON.Inspector._Scene._transformMatrix,
        BABYLON.Inspector._Scene.activeCamera.viewport.toGlobal(
          BABYLON.Inspector._Scene._engine.getRenderWidth(),
          BABYLON.Inspector._Scene._engine.getRenderHeight()
        )
      )
  );

  const minMax = {
    min: coordinates[0],
    max: coordinates[0],
  };

  for (let i = 1; i < coordinates.length; i++) {
    minMax.min = vector3.Minimize(minMax.min, coordinates[i]);
    minMax.max = vector3.Maximize(minMax.max, coordinates[i]);
  }

  let result = {
    x: Math.round((minMax.max.x + minMax.min.x) / 2),
    y: Math.round((minMax.max.y + minMax.min.y) / 2),
  };

  return result;
});

//waiter for scene to load
let isSceneReady = ClientFunction(() => {
  let isRdy = false;
  let pendingData = BABYLON.Inspector._Scene._pendingData.length;
  let pendingAnimation = BABYLON.Inspector._Scene.animatables.length;

  if (pendingData + pendingAnimation == 0) {
    isRdy = true;
  }
  console.log("scene rdy: " + isRdy);
  return isRdy;
});

fixture`DM token move`
  .page("https://playground.babylonjs.com/#8UQCQI#22")
  .beforeEach(async (t) => {
    //waiter till page and scene loads
    await t
      .wait(5000)
      .expect(await isSceneReady())
      .ok({ timeout: 70000 });
  });

test("movement in 5.0", async (t) => {
  await t.debug();

  while (true) {
    let sphere = await getSphere();

    await t
    .click("#renderCanvas", {
      offsetX: sphere.x,
      offsetY: sphere.y,
    })
    .drag("#renderCanvas", 100, 0, {
      offsetX: sphere.x,
      offsetY: sphere.y,
      speed: 0.2,
    })
    .debug()
    .wait(2000);
  }
});`

Issue now seems to be that simulated drag movement: pointermove is intertwined with pointerup events and it's losing the  drag on the object its holding.

**Comment by miherlosev** [comment]
Hi @Mszpyt 

In the shared code example, you drag the `canvas` element. 
![image](https://user-images.githubusercontent.com/4133518/154907616-60e4820b-4fcc-43d1-b0d3-6665044953a6.png)
I guess you want to drag only the sphere not whole canvas. Since the sphere is not a html document, the [drag](https://testcafe.io/documentation/402705/reference/test-api/testcontroller/drag#header) method is not intended for dragging it. 
To achieve you use case, it's necessary to manually dispatch necessary events using the [dispatchEvent](https://testcafe.io/documentation/403091/reference/test-api/testcontroller/dispatchevent#header) method.

**Comment by Mszpyt** [comment]
Right ! DispatchEvent works like a charm thx !
