### ISSUE TITLE
Log-update-async-hook@2.0.4 does not work properly with Testcafe

### ISSUE THREAD

**Issue by Nikolaj1010** [DevExpress/testcafe#6888]
### What is your Scenario?

I would like to report a problem with `log-update-async-hook@2.0.4` library when using with Testcafe **remote** command. It looks like it should be a problem of  **Log-update-async-hook** library because when I downgrade the version to `log-update-async-hook@2.0.2` Testcafe **remote** command works as intended. I just wanted to report that here to be sure and to make you aware of it.

### What is the Current behavior?

When I am trying to run Testcafe with "remote" command, following error is displayed in the console 
`TypeError: Cannot read property 'call' of undefined `
`at Function.render.clear (*\node_modules\log-update-async-hook\src\index.js:68:23)`

### What is the Expected behavior?

Testcafe "remote" command should work as intended

### What is your public website URL? (or attach your complete example)

No need of that

### What is your TestCafe test code?

No code is needed, it is enough to run any file with Testcafe using "remote" command

### Steps to Reproduce

1. Insert `testcafe remote "any-file-name-you-want"` into the console
2. See the error in the console

### TestCafe version

1.15.0

### Node.js version

v14.16.1

### Command-line arguments

testcafe remote any-file-you-have

### Browser name(s) and version(s)

all

### Platform(s) and version(s)

all

**Comment by VasilyStrelyaev** [comment]
Thank you for your report. I have reproduced this behavior with TestCafe v1.18.4.

We have just updated the `log-update-async-hook` module to version `2.0.5` that includes the fix for this issue. You can skip waiting for a TestCafe update and reference `log-update-async-hook@2.0.5` in your `package-lock.json` or `yarn.lock` file right now.
