### ISSUE TITLE
After clicking on submit button in chrome it just keep on loading

### ISSUE THREAD

**Issue by arvindarun** [DevExpress/testcafe#6891]
### What is your Scenario?

After providing the login details on clicking on submit button it keeps on loading. It is working fine on other browsers

Can anyone help me out the cause for this issue.

https://user-images.githubusercontent.com/54062330/155101034-31289719-0dcc-449e-be33-6c9ca8d0bb74.mp4

### What is the Current behavior?

After clicking on the button it keeps on loading

### What is the Expected behavior?

Should be able to login

### What is your public website URL? (or attach your complete example)

https://develop-widget-refactor.bloksports.com/Login

### What is your TestCafe test code?

`import { Selector, t } from 'testcafe';
import { Login } from '../../login';

class LoginPage {
	public userName: Selector;
	public password: Selector;
	public submitBtn: Selector;
	public homePage: Selector;
	public forgotPassword: Selector;
	public signUp: Selector;
	public errMsg: Selector;

	constructor() {
		this.userName = Selector('input[id="username"]');
		this.password = Selector('input[id="password"]');
		this.submitBtn = Selector('button[type="submit"]');
		this.homePage = Selector('div').withExactText('Available balance');
		this.forgotPassword = Selector('a').withExactText('Forgot Password?');
		this.signUp = Selector('div[area="page"] > div > a[href="/register"]');
		this.errMsg = Selector('#login > div > div');
	}

	async fillLoginForm(login: Login) {
		login.username != null ? await t.typeText(this.userName, login.username) : null;
		login.password != null ? await t.typeText(this.password, login.password) : null;
	}

	async submit() {
		await t
			.wait(2000)
			.click(this.submitBtn);
	}

	async signUpLink() {
		await t.click(this.signUp);
	}

	async forgotPasswordLink() {
		await t.click(this.forgotPassword)
	}
}

export default new LoginPage();
`

`fixture('Login')
	.page(`${EnvironmentVariables.url}${Routing.LOGIN}`)
	.beforeEach(async t => {
		if (EnvironmentVariables.env == Tags.DEV) t.ctx.loginData = devLogin;
		if (EnvironmentVariables.env == Tags.STAGE) t.ctx.loginData = stageLogin;
	}).afterEach(async t => {
		await Logout.logout();
	});

test.meta(CreateMetaData([Tags.DEV, Tags.STAGE]))
	('Input valid login credentials using user name', async t => {
		await LoginPage.fillLoginForm(t.ctx.loginData.validLoginCredentials);
		await LoginPage.submit();
		await t.expect(LoginPage.homePage.exists).ok({ timeout: Times.MEDIUM });
	}).only;`

### Steps to Reproduce

1. Enter username and password
2. Clcik on submit button

### TestCafe version

1.18.3

### Command-line arguments

testcafe 'chrome --window-size=1920x1080' src/tests -c 1 --reporter spec --url=https://develop-widget-refactor.bloksports.com --env=dev --test-meta dev=true --skipJsErrors

### Browser name(s) and version(s)

Chrome 98.0.4758.102

**Comment by arvindarun** [comment]
@Dmitry-Ostashev Tried with above code after waiting for 5 minutes still not able to login

**Comment by VasilyStrelyaev** [comment]
Thank you for trying our sample. If you still see the problematic behavior when you run it, this means that we need to reproduce the login process on our side to assist you further with the issue.

Please create a test account on the website and send us the credentials to [support@devexpress.com](mailto:support@devexpress.com). Please also include a written approval from the website owner. It should permit DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes.
