### ISSUE TITLE
Referer is being removed during query requests

### ISSUE THREAD

**Issue by jbradenclickfunnels** [DevExpress/testcafe#6895]
### What is your Scenario?

We are attempting to search on our site

### What is the Current behavior?

The URL that is generated when executing the search is missing the referer '/contacts' before the query parameter:

https://localhost:62547/7rcyyDQu5*wQZYcneWL/https://myworkspace231a66.reborncf.com/account/workspaces/zvbkPe?q=cf2-automation-customer-me23v5bixz%40mailinator.com

Instead of: 

https://localhost:62547/7rcyyDQu5*wQZYcneWL/https://myworkspace231a66.reborncf.com/account/workspaces/zvbkPe/contacts?q=cf2-automation-customer-me23v5bixz%40mailinator.com

Because of this, we are being routed to the dashboard of our site instead of the search executing and displaying results.

### What is the Expected behavior?

The URL generated includes the referer and the search is successful.

### What is your public website URL? (or attach your complete example)

Sent via email

### What is your TestCafe test code?

Sent via email

### Your complete configuration file

See .testcaferc.js from email

### Screenshots

https://user-images.githubusercontent.com/87319403/155603126-10a90705-9b9c-401b-8517-36b416052877.mp4

![Screen Shot 2022-02-24 at 2 22 56 PM](https://user-images.githubusercontent.com/87319403/155602004-a4cb5d84-9c22-4ccd-99d3-e6f6329afe24.png)

### Steps to Reproduce

1. Run ENV=staging testcafe chrome -t "newly_enrolled_user_receives_verification_email" -c 1

### TestCafe version

1.18.4

### Node.js version

16.13.0

### Command-line arguments

ENV=staging testcafe chrome -t "newly_enrolled_user_receives_verification_email" -c 1

### Browser name(s) and version(s)

Chrome 98

### Platform(s) and version(s)

macOS 12.2.1

### Other

This just started failing for us today even though the script was made back in January. We tried on 1.18.3 and 1.18.4 and it's failing in both. We tested this scenario in another tool called testproject.io and this is working just fine there.

**Comment by Dmitry-Ostashev** [comment]
Thank you for your detailed report and project. I reproduced the issue. Please stay tuned for our updates.

**Comment by AndreyBelym** [comment]
Duplicate: https://supportcenter.devexpress.com/internal/ticket/details/T1129084

**Comment by Aleksey28** [comment]
Hi @jbradenclickfunnels,

I cannot reproduce this behavior anymore. Please check it yourself and let us know if nothing has changed.
