### ISSUE TITLE
Rethink testing infrastructure (pr tests + smoke tests)

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#690]
We need to decrease travis task count to improve testing performance. Now we have to wait for a long time while travis give us a testing vm because we have too much tasks

**Comment by inikulin** [comment]
First line (runs on every PR):
- Android
- FF (win)
- Chrome (win)
- IE 11
- iPhone

It would be nice to put Safari here as well if it's possible

Second line (twice a day):
- Firefox (mac)
- Chrome (mac)
- IE9
- IE10
- Edge
- Safari (?)

Also, we need some kind of reporting for smoke tests (badges are untrustable). Can we create an issue for cumulative test run results (functional + legacy) if they fail?

**Comment by inikulin** [comment]
Also, we need a way to trigger any of smoke test tasks using bot command, use case: you've fixed some issue in smoke tests and you need to get PR via particular test task

**Comment by AlexanderMoskovkin** [comment]
I'll try to create some complex solution for this all, that connects our repo, testcafe-build-bot and CCTray farm. It can take some time. 
But I suppose we should join travis tasks first to improve out working process right now, am I right?

**Comment by inikulin** [comment]
@AlexanderMoskovkin Yeah, but at least we need some reporting as well. I'm really worried about broken smoke tasks.

**Comment by AlexanderMoskovkin** [comment]
Now it's on my personal attention, but sure I'll implement something for this soon

**Comment by miherlosev** [comment]
I think we should add perfomance tests for `testcafe`.
For example:
- average time for tests with basic actions (`click`, `type`, etc).
- average time for large test suite (full asp or devexteme test suite)
- perfomance comparison with Selenium.
What do you think @inikulin @AlexanderMoskovkin ?

**Comment by inikulin** [comment]
@miherlosev Not sure we should. It's not a main pain point currently. The thing that still bothers me the most in the whole framework is still hammerhead and it's endless regressions.
