### ISSUE TITLE
Contents of closed `<details>` element mistakenly treated as visible in Chrome

### ISSUE THREAD

**Issue by mikejamesthompson** [DevExpress/testcafe#6907]
### What is your Scenario?

I'd like to test that the contents of a `<details>` element is hidden by default and that clicking on the `<summary>` element within the `<details>` element reveals the content.

E.g. for HTML like:
```
<details>
    <summary>Click me</summary>
    <ul>
      <li>I'm hidden by default</li>
      <li>So am I</li>
      <li>And me</li>
      <li>And me too!</li>
    </ul>
  </details>
```

And test code like:
```
await t
    .expect(Selector('details li').filterVisible().count).eql(0)
```

The test should pass.

### What is the Current behavior?

In Chrome 98 and 99, TestCafé reports that all the `<li>` elements within the `<details>` element are visible and the test fails.

In contrast, the same test passes when run against Firefox and Safari.

The test also passes in our CI when running against an earlier version of Chromium (`Chrome 93.0.4577.82`)

### What is the Expected behavior?

TestCafé should treat the contents within the `<details>` as not visible in all browsers.

### What is your public website URL? (or attach your complete example)

Full test case here:
https://github.com/mikejamesthompson/testcafe-details-element-test

### What is your TestCafe test code?

```
import { t, Selector } from 'testcafe';

fixture`Details element content visibility tests`
  .page`http://localhost:8000/index.html`

test('Content is hidden', async () => {
  await t
    .expect(Selector('details li').filterVisible().count)
      .eql(0, "Details element content unexpectedly visible")
});
```

### Your complete configuration file

N/A

### Your complete test report

Visible here:
https://github.com/mikejamesthompson/testcafe-details-element-test/runs/5382459486?check_suite_focus=true

### Steps to Reproduce

1. Clone the [test repo](https://github.com/mikejamesthompson/testcafe-details-element-test)
2. Make sure you have Docker installed
3. Run `make`
4. Check the output

### TestCafe version

1.18.4

### Node.js version

v16

### Command-line arguments

testcafe chrome:headless ./test.js

### Browser name(s) and version(s)

Chrome 98 and Chrome 99

### Platform(s) and version(s)

Observed on Debian Linux Bullseye and macOS 10.15.7

**Comment by alexphilin** [comment]
Hi @mikejamesthompson 
According to the current visibility checking rules (does not have `display: none` or `visibility: hidden` CSS properties and has non-zero width and height), the element is interpreted as visible because it has a non-zero width and height.

Run the following test to check this:

```js
test('Content is hidden', async () => {
const details = Selector('details');
console.log(await details.tagName);
console.log(await details.visible);
console.log(await details.boundingClientRect);
});
```

We have plans to improve the visibility checking algorithm in the future.

**Comment by mikejamesthompson** [comment]
I think this deserves more consideration @alexphilin.

After some digging, I've found that the cause here is a change in behaviour in Chromium in version 97/98.

See this bug raised by a member of the Playwright team:
https://bugs.chromium.org/p/chromium/issues/detail?id=1276028&q=component%3ABlink%3EHTML%3EDetails&can=2#c12

Note that Playwright have taken action to disable this behaviour in Chromium and bring it in line with other browsers:
https://github.com/microsoft/playwright/pull/10679

Also, the sample test code you provided is incorrect as the details element itself is expected to be visible. Its contents, apart from the summary element, are hidden. The code should be:

```
test('Log li properties', async () => {
  const li = Selector('details li');
  console.log(await li.tagName);
  console.log(await li.visible);
  console.log(await li.boundingClientRect);
});
```

This code run in Firefox will show `{ left: 0, right: 0, top: 0, bottom: 0, width: 0, height: 0 }` for `boundingClientRect` and non-zero values in Chromium, like `{ left: 48, right: 1272, top: 42, bottom: 60, width: 1224, height: 18 }`.

**Comment by alexphilin** [comment]
Hi @mikejamesthompson

Thank you for sharing the additional information. Since it's a Google Chrome issue, we will be waiting for the fix on their side.
As a workaround, you can add the necessary command-line argument to Google Chrome as follows:

```js
testcafe "chrome --disable-features=AutoExpandDetailsElement" tests
```
