### ISSUE TITLE
SurveyJS Imagepicker DnD blinking issue

### ISSUE THREAD

**Issue by dmitrykurmanov** [DevExpress/testcafe#6908]
### What is your Scenario?

The test is blinking at the azure CI sometimes 

### What is the Current behavior?

Sometimes the test blinking and fails

### What is the Expected behavior?

test run without blinking

### What is your public website URL? (or attach your complete example)

https://surveyjs.io/create-survey

minimal sample: https://github.com/surveyjs/testcafe-blinking-issue

https://dev.azure.com/SurveyJS/SurveyJS%20Integration%20Tests/_build/results?buildId=41022&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5

### What is your TestCafe test code?

import { Selector, ClientFunction } from "testcafe";
const title = "Drag Drop";

const url = "https://surveyjs.io/create-survey";

const setJSON = ClientFunction((json) => {
  window["creator"].text = JSON.stringify(json);
});

const getItemValueByIndex = ClientFunction((questionName, index) => {
  const question = window["creator"].survey.getQuestionByName(questionName);
  const choices = question.visibleChoices;
  return choices[index].value;
});

const arr = [];
arr.length = 100;
arr.fill(null);

arr.forEach(
  () => {
    fixture`${title}`.page`${url}`.beforeEach(async (t) => {
      await t.maximizeWindow();
    });

    test("Drag Drop ImagePicker (choices)", async (t) => {
      await t.resizeWindow(2560, 1440);

      const json = {
        pages: [
          {
            name: "page1",
            elements: [
              {
                "type": "imagepicker",
                "name": "question1",
                "choices": [
                  {
                    "value": "lion",
                    "imageLink": "https://surveyjs.io/Content/Images/examples/image-picker/lion.jpg"
                  },
                  {
                    "value": "giraffe",
                    "imageLink": "https://surveyjs.io/Content/Images/examples/image-picker/giraffe.jpg"
                  },
                  {
                    "value": "panda",
                    "imageLink": "https://surveyjs.io/Content/Images/examples/image-picker/panda.jpg"
                  },
                  {
                    "value": "camel",
                    "imageLink": "https://surveyjs.io/Content/Images/examples/image-picker/camel.jpg"
                  }
                ]
              }
            ]
          }
        ]
      };
      await setJSON(json);

      const expectedValue = "giraffe";
      let value;

      const Question1 = Selector("[data-name=\"question1\"]");
      const LionItem = Selector("[data-sv-drop-target-item-value=\"lion\"]");
      const GiraffeItem = Selector("[data-sv-drop-target-item-value=\"giraffe\"]");
      const PandaItem = Selector("[data-sv-drop-target-item-value=\"panda\"]");
      const CamelItem = Selector("[data-sv-drop-target-item-value=\"camel\"]");

      const DragZoneGiraffeItem = GiraffeItem.find(".svc-image-item-value-controls__drag-area-indicator").filterVisible();

      await t
        .click(Question1, { speed: 0.5 })
        .hover(PandaItem).hover(LionItem).hover(CamelItem).hover(GiraffeItem).hover(DragZoneGiraffeItem)
        .dragToElement(DragZoneGiraffeItem, LionItem, { speed: 0.5 });
      value = await getItemValueByIndex("question1", 0);
      await t.expect(value).eql(expectedValue);

      await t
        .click(Question1, { speed: 0.5 })
        .hover(PandaItem).hover(LionItem).hover(CamelItem).hover(GiraffeItem).hover(DragZoneGiraffeItem)
        .dragToElement(DragZoneGiraffeItem, PandaItem, { speed: 0.5 });
      value = await getItemValueByIndex("question1", 2);
      await t.expect(value).eql(expectedValue);
    });
  }
);

### Your complete configuration file

none

### Your complete test report

      800 |  await t
      801 |    .click(Question1, { speed: 0.5 })
      802 |
   .hover(PandaItem).hover(LionItem).hover(CamelItem).hover(GiraffeItem).hover(DragZoneGiraffeItem)
      803 |    .dragToElement(DragZoneGiraffeItem, PandaItem, { speed: 0.5
   });
      804 |  value = await getItemValueByIndex("question1", 2);
    > 805 |  await t.expect(value).eql(expectedValue);
      806 |});
      807 |
      808 |test("Drag Drop MatrixRows (property grid)", async (t) => {
      809 |  const json = {
      810 |    pages: [

      at <anonymous>
   (/home/vsts/work/1/s/survey-creator/testCafe/designer/drag-drop.ts:805:25)
      at fulfilled
   (/home/vsts/work/1/s/survey-creator/testCafe/designer/drag-drop.ts:5:58)

 1/112 failed

 Warnings (1):

### Steps to Reproduce

1. go to repo
2. npm i
3. npm test (probably many times because of blinking)

### TestCafe version

latest

### Node.js version

14

### Command-line arguments

 -c 4 -q chrome:headless --selector-timeout 1500 --reporter minimal,dashboard

### Browser name(s) and version(s)

Chrome 

### Platform(s) and version(s)

Ubuntu

**Comment by alexphilin** [comment]
Hello @dmitrykurmanov 

Thank you for reporting this bug. We managed to reproduced it. We will research it and update this thread once we have any results.

**Comment by miherlosev** [comment]
Hi @dmitrykurmanov,

You need to rewrite the assertion in this way:

```js
value = await getItemValueByIndex("question1", 0);
await t.expect(value).eql(expectedValue);

->

await t.expect(getItemValueByIndex("question1", 0)).eql(expectedValue);
```

It allows TestCafe to use the [Smart Assertion Query Mechanism](https://testcafe.io/documentation/402837/guides/basic-guides/assertions?search#smart-assertion-query-mechanism), which helps avoiding test instability.
