### ISSUE TITLE
Failure to navigate from home page to other page, when we performed any action in the application after Okta authentication

### ISSUE THREAD

**Issue by Satyanarayana-Kota** [DevExpress/testcafe#6909]
### What is your Scenario?

Hi,

We are working on a Guidewire application under Insurance domain. We used to write automation test scripts for our application. Even we have some written scripts as well. Previously we used to login into our application with Super User credentials (Without Okta authentication) by using our existing scripts we are able to execute our tests successfully and pass. 

Recently our application has been migrated to 'Okta Authentication' process. We have created the automation script for 'Okta Authentication' process and able to login to our application and redirected to 'Home' page successfully. Now the issue is, **Whenever we have performed any action on the web elements exists in 'Home' page, TestCafe is not navigating to concerned action item page.** 

Example: When I click() on 'New Account' button in Home page it should navigates to 'Enter Account Details' page but it is staying on the same home page itself. Here, TestCafe is able to identify the web element by JS path and performing the action but unable to navigate to that resultant page. This is happens for all the web elements available in the 'Home' page and that too after migrating to 'Okta Authentication' only.

### What is the Current behavior?

After successfully authenticating through Okta, Whenever we have performed any action on the web elements exists in 'Home' page it is not navigating to concerned action item page. 

Example: When I click() on 'New Account' button in Home page it should navigates to 'Enter Account Details' page but it is staying on the same home page itself. Here, TestCafe is able to identify the webelement by JS path and performing the action but unable to navigate to that resultant page. This is happens for all the web elements available in that 'Home' page and that too after migrating to 'Okta Authentication' only.

### What is the Expected behavior?

Testcafe should redirect properly through the flow and execute the test, and then fail or succeed.

### What is your public website URL? (or attach your complete example)

The web application is not public so I cannot link it, as it requires my Organization ID and it is not accessible outside our company network.

### What is your TestCafe test code?

import { AccountTabBar_Ext } from "./ScenarioPages/Account/AccountTabBar_Ext";
import { NewAccount } from "../../pages/account/NewAccount";
import { NewBusinessAccountScreen } from "./ScenarioPages/Account/NewBusinessAccountScreen";
import { Summary } from "../../pages/account/Summary";
import { DesktopMenuActions } from "../../pages/navigation/menuActions/DesktopMenuActions";
import { t } from "testcafe";
import world from "../utils/world.js";
import { jsonReader } from "../utils/jsonFileReader.js";
import { DesktopTabBar } from "../../pages/navigation/tabBar/DesktopTabBar";

const accountTabBar_Ext = new AccountTabBar_Ext();
const newAccount = new NewAccount();
const newPersonAccountScreen = new NewPersonAccountScreen();
const newBusinessAccountScreen = new NewBusinessAccountScreen();
const summary = new Summary();
const desktopMenuActions = new DesktopMenuActions();
const desktopTabBar = new DesktopTabBar();

var companyName = '', firstName = '', lastName = '', addressLine1 = '', city = '', postalCode = '', state = '', addressType = '', country = '', coverageCurrency = '', settlementCurrency = '', organizationType = '', organizationName = '', organizationCode = '';

export class AccountScenario {
    constructor() {}
    
        async createBusinessAccount() {
        jsonReader('../guidewiretestingui/policysolutions/surepath/utils/addBusinessAccount.json',(err,addBusinessAccount) => {
            if(err){
                console.log(err);
                return;
            }
            companyName = addBusinessAccount.data.attributes.initialAccountHolder.companyName;
            country = addBusinessAccount.data.attributes.initialAccountHolder.country.code;
            addressLine1 = addBusinessAccount.data.attributes.initialAccountHolder.primaryAddress.addressLine1;
            city = addBusinessAccount.data.attributes.initialAccountHolder.primaryAddress.city;
            postalCode = addBusinessAccount.data.attributes.initialAccountHolder.primaryAddress.postalCode;
            state = addBusinessAccount.data.attributes.initialAccountHolder.primaryAddress.state.code;
            addressType = addBusinessAccount.data.attributes.initialAccountHolder.primaryAddress.addressType.code;
            coverageCurrency = addBusinessAccount.data.attributes.initialAccountHolder.primaryAddress.preferredCoverageCurrency.code;
            settlementCurrency = addBusinessAccount.data.attributes.initialAccountHolder.primaryAddress.preferredSettlementCurrency.code;
            organizationType = addBusinessAccount.data.attributes.initialAccountHolder.primaryAddress.organizationType.code;
            organizationName = addBusinessAccount.data.attributes.producerCodes.organizatioName;
            organizationCode = addBusinessAccount.data.attributes.producerCodes.id;
        });
        console.log(companyName);
        await desktopMenuActions.desktopDesktopMenuActions.click();
        await desktopMenuActions.desktopMenuActions_CreateDesktopMenuActions_NewAccount.click();
        
        await newAccount.newAccountNewAccountScreenNewAccountSearchDVGlobalContactNameInputSetName.setValue(companyName);
        await newAccount.newAccountNewAccountScreenNewAccountSearchDVSearchAndResetInputSetSearchLinksInputSetSearch.click();
        
        //click new account company button
        await newAccount.newAccountScreenNewAccountButton.click();
        await newAccount.newAccountButtonNewAccount_Company.click();
        
        //Enter account details
        await newBusinessAccountScreen.country.selectOptionByLabel(country); //"Canada");
        await newBusinessAccountScreen.addressLine1.setValue(addressLine1); //"1234 Hillsdale Blvd");
        await newBusinessAccountScreen.city.setValue(city); //"Toronto");
        await newBusinessAccountScreen.state.click();
        await newBusinessAccountScreen.state.selectOptionByLabel(state); //"Ontario");
        await newBusinessAccountScreen.postalcode.setValue(postalCode); //"M4X1C9");
        await newBusinessAccountScreen.addressType.click();
        await newBusinessAccountScreen.addressType.selectOptionByLabel(addressType); //"Home");
        await newBusinessAccountScreen.settelmentCurrency.selectOptionByLabel(settlementCurrency); //"CAD");
        await newBusinessAccountScreen.coverageCurrency.selectOptionByLabel(coverageCurrency); //"CAD");
        await newBusinessAccountScreen.organizationType.selectOptionByLabel(organizationType); //Individual
      
       // await newBusinessAccountScreen.producer.setValue(organizationName); //"AON REED STENHOUSE INC.");
        await newBusinessAccountScreen.producerSearch.click();
        await newBusinessAccountScreen.selectOrganizationName(organizationName);
        await newBusinessAccountScreen.producerCode.selectOptionByLabel(organizationCode); //"9601455 Aon Reed Stenhouse Inc");
        await newBusinessAccountScreen.updateButton.click();
        world.accountNumber = await summary.accountDetailsDetailViewTile_DVAccountNumber.getValue();
    }
  
}

### Steps to Reproduce

1. Launch the URL and navigates to the PC
2. Enter the Okta Username and click on 'Next' button
3. Enter the Okta Password and click on 'SignIn' button
4. User navigates to application 'Home Page'
5. When I click on 'New Account', Account-->'New Account' button in Home page it should navigates to 'Enter Account Details' page 

### TestCafe version

8.1.0

### Node.js version

v16.13.0

### Command-line arguments

npm run gt-ui-tests -- --cucumberTags='@cp_e2escenario-2'

### Browser name(s) and version(s)

Chrome 98.0.4758.102

### Platform(s) and version(s)

Windows 8

**Comment by Satyanarayana-Kota** [comment]
Hi,
Any update on this issue, as we are blocked by this issue, you could consider this is a showstopper. Please someone can look into it and help us in how to proceed further.

Thanks in advance!

**Comment by alexphilin** [comment]
Thank you for your report. However, we cannot assist you with this issue unless we reproduce the problematic behavior on our side. If you are unable to allow external access to the tested application, you can prepare a minimal sample web application or standalone web page that we could use to reproduce the issue.

**Comment by Subhasish14** [comment]
Hello ,

I am trying to automate a Guidewire Application using testCafe. But I am facing similar issue. I am unable to login  with username password and navigate to the home page . The script is entering username and password values in respective fields then clicking on login. But it is not navigating to next page .

Can you please give any idea what i should do to resolve this issue ?

**Comment by Dmitry-Ostashev** [comment]
Hello @Subhasish14 ,

I've commented your issue [https://github.com/DevExpress/testcafe/issues/7091](https://github.com/DevExpress/testcafe/issues/7091). Let's continue conversation about your case there.
