### ISSUE TITLE
Mechanism to not inject hammerhead code into JS resources at runtime

### ISSUE THREAD

**Issue by leojh** [DevExpress/testcafe#6913]
### What is your Scenario?

Currently, Test Cafe uses a reverse proxy which acts like a man in the middle and injects Test Cafe/Hammerhead specific code into the main HTML document and also all linked JavaScript resources. The problem with this injection is that for a lot of cases it's very intrusive and breaks all sourcemaps that are associated with the code. 
The specific problem it creates for me is that as the tests run, and the application throws runtime exceptions, our error reporting tool (Sentry), cannot link to the sourcemaps it has since the stack frames no longer match.

### What are you suggesting?

There should be a package that we import, or a webpack loader, that basically enables the hammerhead code without having to inject it adhoc at runtime. 

### What alternatives have you considered?

There are none other than going with a different tool that does not do adhoc injecting at runtime.

**Comment by alexphilin** [comment]
Hi @leojh

 

TestCafe is based on code injection into the tested page. It's necessary for the [Smart assertion mechanisms](https://testcafe.io/documentation/402837/guides/basic-guides/assert#smart-assertion-query-mechanism) and [Built-in wait mechanisms](https://testcafe.io/documentation/402827/guides/concepts/built-in-wait-mechanisms#header). So, it's hard to work without code injection and we will not implement such capability. We will consider possible issues separately.

The case with [support for sourcemaps](https://github.com/DevExpress/testcafe/issues/1793) is described.

 

You can prepare a simple example illustrating the issue you found and attach it here.

**Comment by leojh** [comment]
This is a real shame since there shouldn't be a need to inject the code. The developer should have the option to just simply include hammerhead as a dependency and have the application be under test using the exact code that is deployed without injection. Breaking the source maps is unfortunately a pretty serious side effect currently.

**Comment by miherlosev** [comment]
I agree with you that there are several negative side effects related to using proxy.
We have plans to implement the capability to run tests without using the `testcafe-hammerhead` proxy.
We will announce it once it is implemented.

**Comment by leojh** [comment]
@miherlosev any recent convos or updates on your end about this? btw we're also happy to help out on the implementation side if you need that.

**Comment by miherlosev** [comment]
Hi @leojh,

Thank you for your offer to help. At present, we are working on prototype. Later, we will create a list of tasks to make prototype more stable and functionality. If there are tasks that can be done by non-team contributors, we notify you.

**Comment by miherlosev** [comment]
Hi @leojh,

The new [test run mode](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode) became the default mode in `testcafe@3.x`. Please run tests with the latest TestCafe version and let us know your results.
