### ISSUE TITLE
Testcafe Redirect is not working with Angular 13

### ISSUE THREAD

**Issue by Parulag19** [DevExpress/testcafe#6914]
### What is your Scenario?

Given
Angular13
Testcafe version: 1.18.4

\When we are executing tests, the redirect is not functioning properly, and browser keeps on spinning before the Login page. It is showinh hammerhead error

### What is the Current behavior?

Url is getting redirected, and giving the hammerhead error

![image](https://user-images.githubusercontent.com/100848000/157046565-63f7a707-d414-4dd6-bc29-5e4bc9bb26dd.png)

### What is the Expected behavior?

Login page should load

### What is your public website URL? (or attach your complete example)

![image](https://user-images.githubusercontent.com/100848000/157047089-e86f1206-8cf4-4754-8dbc-11f0b5f2bffb.png)

### What is your TestCafe test code?

"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.User = void 0;
const testcafe_1 = require("testcafe");
class User {
    constructor(userName, password, url) {
        this._userName = userName;
        this._password = password;
        this._url = url;
    }
    GetRole() {
        const role = testcafe_1.Role(this._url, (controller) => __awaiter(this, void 0, void 0, function* () {
            const button = testcafe_1.Selector('button').withText('Login');
            yield controller
                .typeText('#Username', this._userName)
                .typeText('#Password', this._password)
                .click(button);
        }), { preserveUrl: true });
        return role;
    }
    static Login(role, url) {
        return __awaiter(this, void 0, void 0, function* () {
            yield testcafe_1.t
                .useRole(role)
                .navigateTo(url);
        });
    }
}
exports.User = User;

### Your complete configuration file

{
    "browsers": "edge:headless",
    "concurrency": 1,
    "reporter": [
        {
            "name": "spec"
        },
        {
            "name": "xunit",
            "output": "e2eReport.xml"
        }
    ],
    "selectorTimeout": 20000,
    "assertionTimeout": 20000,
    "pageLoadTimeout": 120000,
    "pageRequestTimeout": 120000,
    "speed": 0.8,
    "screenshots": {
        "takeOnFails": true,
        "pathPattern": "${BROWSER}/${FIXTURE}/${TEST}.png"
    }
}

### Steps to Reproduce

1.
2.
3.

### TestCafe version

1.18.4

### Node.js version

14.17.0

### Command-line arguments

testcafe edge .\apps\fleet-command-e2e\src\tests --proxy *.azurewebsites.net  --proxy-bypass localhost:4200 -e -u

### Browser name(s) and version(s)

Edge: Version 98.0.1108.62 (Official build) (64-bit)

### Platform(s) and version(s)

Windows

**Comment by AlexKamaev** [comment]
@jenaewhitmore Thank you for your cooperation. We really appreciate it.
