### ISSUE TITLE
Docs typos

### ISSUE THREAD

**Issue by Joao-S-Martins** [DevExpress/testcafe#6917]
### What is your Scenario?

`https://github.com/DevExpress/testcafe/blob/master/CONTRIBUTING.md#contribute-to-documentation` says to submit an issue for docs changes. The new templates don't let me create a generic issue and label it as `AREA: docs`, per instructions. So, I'm specifying the typos here and requesting that you add an issue template for docs changes.

### What is the Current behavior?

`.useRole(admin;`

### What is the Expected behavior?

`t.useRole(admin);`

### What is your public website URL? (or attach your complete example)

https://testcafe.io/documentation/402638/reference/configuration-file#hooks

### What is your TestCafe test code?

N/A

### Steps to Reproduce

Go to the URL.

### TestCafe version

N/A

### Command-line arguments

N/A

**Comment by VasilyStrelyaev** [comment]
Thank you for pointing this out to us. However, we already have a similar issue: https://github.com/DevExpress/testcafe/issues/6916.

Please subscribe to this issue to keep track of our progress.
