### ISSUE TITLE
Can't save screenshot files when the file name includes a backslash

### ISSUE THREAD

**Issue by michalmos** [DevExpress/testcafe#6919]
### What is your Scenario?

Include in a test name a backslash.
For example: 'Verify that we can select something from the list apple/house/banana'

### What is the Current behavior?

In our tests, we take screenshots (png files) when they fail, and many of our tests include a backslash.
When testcafe tries to save the file, the “/” is being broken into another dir and when our plugin tries to upload the file it doesn't find it.

### What is the Expected behavior?

Testcafe should take into account that every character in the test name is a part of the name.

### What is your public website URL? (or attach your complete example)

no public website URL

### What is your TestCafe test code?

Include in a test name a backslash.
For example: 'Verify that we can select something from the list apple/house/banana'

### Steps to Reproduce

Include in a test name a backslash.
For example: 'Verify that we can select something from the list apple/house/banana'

### TestCafe version

1.18.1

### Node.js version

v16.14.0

### Command-line arguments

testcafe chrome --debug-on-fail

**Comment by helen-dikareva** [comment]
Special characters like `/:*?"<>|` on Windows are forbidden. This means that TestCafe cannot create files with such symbols in their names on Windows anyway.
While it is possible to use '/' on Linux and OS-X, it is still highly not recommended to use it in file naming.
I advise against backslashes in test names. However, if using such symbols on macOs and Linux is important for your use case, you can modify TestCafe's open source behavior - your PR is welcome. The entry point is the [`getPath` method](https://github.com/DevExpress/testcafe/blob/master/src/utils/path-pattern.js#L127).
