### ISSUE TITLE
CLI parsing doesn't work with bad optional quarantine-mode values

### ISSUE THREAD

**Issue by rfalke** [DevExpress/testcafe#6922]
### What is your Scenario?

I want to run
```
testcafe --quarantine-mode attemptlimit=3,successThreshold=1 'browserstack:safari@14.1:OS X Big Sur'
```

From the help page
```
Usage: testcafe [options] <comma-separated-browser-list> <file-or-glob ...>
...
  -q, --quarantine-mode [option=value,...]       enable quarantine mode and (optionally) modify quarantine mode settings
```

so it should be possible to specify the `--quarantine-mode` before the browser and with an optional argument.

### What is the Current behavior?

An error:
```
ERROR Cannot find the browser. "attemptlimit=3" is neither a known browser alias, nor a path to an executable file.
```

### What is the Expected behavior?

That it runs the test in quarantine-mode with the given parameters.

### What is your public website URL? (or attach your complete example)

Install testcafe and run from the shell
```
./node_modules/.bin/testcafe --quarantine-mode attemptlimit=3,successThreshold=1 'browserstack:safari@14.1:OS X Big Sur'
```

### What is your TestCafe test code?

Not relevant

### Steps to Reproduce

See above

### TestCafe version

1.18.4

### Node.js version

v14.18.2

### Command-line arguments

See above

### Other

It looks like the error is in `node_modules/testcafe/lib/cli/argument-parser.js:_prepareQuarantineOptions()` which doesn't consider the optional argument.

**Comment by rfalke** [comment]
Digging further into this shows that I used `attemptlimit` and not `attemptLimit`. Because of this mismatch the parameter isn't moved by `_prepareQuarantineOptions`.

If I disable the argv modification `_prepareQuarantineOptions` and rerun with `attemptlimit` I get the (a bit more) helpful:
```
ERROR The "--quarantine-mode" option does not exist. Specify "attemptLimit" and "successThreshold" to configure quarantine mode.
```

So I see:
- Error message for unknown quarantine-mode parameters doesn't mention the bad parameter
- The argv modification in `_prepareQuarantineOptions` is not robust wrt bad quarantine-mode parameters AND currently prevents the showing the real/proper error message

**Comment by AlexKamaev** [comment]
Thank you for your explanation. I agree that in some cases argument processing errors could be more clear. We'll take it in account.
