### ISSUE TITLE
TestCafe not using Chrome's `iPhone 12 Pro` emulation preset

### ISSUE THREAD

**Issue by JPrymek-Change** [DevExpress/testcafe#6923]
### What is your Scenario?

My team would like to run tests in Chrome, emulating a recent model iPhone.  We've previously been using the `iPhone X` preset, and are looking for something more recent.  The only entry available in Chrome's default device list that suits our criteria is `iPhone 12 Pro`.

### What is the Current behavior?

The TestCafe window is not using the mobile emulation mode.  The browser window does not resize, and the user agent is showing `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36`.  

### What is the Expected behavior?

The browser window should be resized to 390 x 844 px, with a DPR of 3.0.  Touch controls should be enabled.  The user agent should be `Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E304 Safari/602.1`

### What is your public website URL? (or attach your complete example)

This test can be run on `https://www.google.com/search?q=show+user+agent` for easy visual debugging.

### What is your TestCafe test code?

// tests/browsertest.js

fixture('Browser Testing')
.page('https://www.google.com/search?q=show+user+agent')

test('[DEBUG] Show browsers user agent', async t => {
  await t.takeScreenshot('browserUserAgent.png');
  await t.debug();
});

### Your complete configuration file

{
  "browsers": ["chrome:headless:emulation:device=iPhone X"],
  "src": "./tests/**/*.js",
  "clientScripts":[
    {
      "module":"axe-core/axe.min.js"
    }
  ],

  "assertionTimeout": 15000,
  "ajaxRequestTimeout": 40000,
  "pageLoadTimeout": 30000,
  "selectorTimeout": 15000,

  "disableMultipleWindows": false,

  "quarantineMode": false,
  "skipJsErrors": true,

  "disablePageCaching": true,

  "reporter": [
    {
      "name": "xunit",
      "output": "artifacts/test-results/results.xml"
    },
    {
      "name": "spec"
    }
  ],

  "screenshots": {
    "fullPage": true,
    "takeOnFails": true,
    "pathPattern": "${TEST_ID}/${RUN_ID}_${FILE_INDEX}.png",
    "path": "artifacts/screenshots",
    "thumbnails": false
  }
}

### Your complete test report

Using locally installed version of TestCafe.
The "src" and "browsers" options from the configuration file will be ignored.
 Running tests in:
 - Chrome 99.0.4844.51 / macOS 10.15.7

 Browser Testing
 ✓ [DEBUG] Show browsers user agent (screenshots: /Users/jprymek/Documents/ChangeOrg/TestAutomation/FE_Suite/regression-qaa/artifacts/screenshots/browserUserAgent.png)

 1 passed (10m 42s)

 Warnings (1):
 --
  The "src" and "browsers" options from the configuration file will be ignored.

### Screenshots

Browser window in TestCafe:
![Screen Shot 2022-03-11 at 10 08 27 AM](https://user-images.githubusercontent.com/59627355/157904882-6013f204-b424-403f-95f5-b67d3a4fc517.png)

Regular browser, with device emulation enabled:
![Screen Shot 2022-03-11 at 10 09 36 AM](https://user-images.githubusercontent.com/59627355/157904851-05a0c162-b0c3-4ba3-922a-2bbb138bd735.png)

### Steps to Reproduce

1.  Run the attached test code using `'chrome:emulation:device=iPhone 12 Pro'` as the browser
2.  View the browser window size.
3.  View the user agent (via Google search result, or via request headers in dev tools' network tab)

### TestCafe version

1.16.1

### Node.js version

16.13.0

### Command-line arguments

testcafe 'chrome:emulation:device=iPhone 12 Pro' tests/browsertest.js

### Browser name(s) and version(s)

Chrome 99

### Platform(s) and version(s)

Mac OS 11.6.2

### Other

I have also verified this behavior occurs with TestCafe version 1.18.4 as well.

**Comment by VasilyStrelyaev** [comment]
Thank you for your report. I will mark this issue as an enhancement request. We will take it into account during our future planning.

To address this issue promptly, take note of the `device-specs` repository where we store the list of devices for Chromium emulation: https://github.com/DevExpress/device-specs. You are welcome to open a pull request to this repository.

Note that you can use the `npm run update` task to automatically fetch the recent device list from the Chromium repository. After you run the `update` task, verify that everything is okay, commit the changes, and open a pull request.

**Comment by JPrymek-Change** [comment]
Closing this issue, as it should be addressed by merging [this PR](https://github.com/DevExpress/device-specs/pull/7).
