### ISSUE TITLE
Testcafe not loading completely  once we enter login and password, ---page is broken 

### ISSUE THREAD

**Issue by shanthkumar043** [DevExpress/testcafe#6929]
### What is your Scenario?

url : https://adminsec2.nike.net/admin-app/#/users
EmailAddress : shefali.gulati@nike.com
Password:Ankit@314

manually page loading correctly

![image](https://user-images.githubusercontent.com/52404918/158735117-042afa2b-d6b8-4e79-80c3-8b4737054cbc.png)

when we run test cafe 
![image](https://user-images.githubusercontent.com/52404918/158735362-8fddaa9e-ae45-4afb-af0c-6cb7096aeae3.png)

same issue in testcafe studio

please help me to resolve this issue..i tried wait await ..still no luck...
 

### What is the Current behavior?

Page not lodaing when we enter user name and pass word

### What is the Expected behavior?

page should load with all the content ...

### What is your public website URL? (or attach your complete example)

url : https://adminsec2.nike.net/admin-app/#/users
EmailAddress : shefali.gulati@nike.com
Password:Ankit@314

manually page loading correctly

![image](https://user-images.githubusercontent.com/52404918/158735117-042afa2b-d6b8-4e79-80c3-8b4737054cbc.png)

when we run test cafe 
![image](https://user-images.githubusercontent.com/52404918/158735362-8fddaa9e-ae45-4afb-af0c-6cb7096aeae3.png)

same issue in testcafe studio

please help me to resolve this issue..i tried wait await ..still no luck...
 

### What is your TestCafe test code?
```js
import { Selector } from 'testcafe';
import { ClientFunction } from 'testcafe';
//import { AngularSelector, waitForAngular } from 'testcafe-angular-selectors';

const cancelLoading = ClientFunction(() => window.stop());



const elementByXPath = Selector(xpath => {
    const iterator = document.evaluate(xpath, document, null, XPathResult.UNORDERED_NODE_ITERATOR_TYPE, null )
    const items = [];

    let item = iterator.iterateNext();

    while (item) {
        items.push(item);
        item = iterator.iterateNext();
    }

    return items;
});  

const logIn = Selector('#okta-signin-submit');
const EmailAddress = Selector(elementByXPath('//*[@id="okta-signin-username"]'));
const Password = Selector(elementByXPath('//*[@id="okta-signin-password"]'));
const dropdown = Selector(elementByXPath('//*[@id="search_dropdown_chosen"]/a'));
const searchtextBox = Selector(elementByXPath('//input[@id="search_input"]'));
const searchButton = Selector(elementByXPath('//*[@id="search_mgfy_glass"]'));
const pageheader = Selector(elementByXPath('//*[@id="page_header"]/h2/translate'));
const option = Selector(elementByXPath('//*[@id="search_dropdown_chosen"]/div/ul/li[7]'));
const user = Selector(elementByXPath('/html[1]/body[1]/div[4]/div[1]/table[1]/tbody[1]/tr[2]/td[1]/a[1]'));
const HeaderUserName = Selector(elementByXPath('//translate[normalize-space()="Username"]'));
const ImpersonateUser = Selector(elementByXPath('//translate[normalize-space()="Impersonate User"]'));
const changepartner = Selector(elementByXPath('//a[@id="change_customer"]'));
const Partner = Selector(elementByXPath('//td[@class="input-radio"]//label[@for="account_0005025475"]'));
const SetPartnerButton = Selector(elementByXPath('//translate[normalize-space()="Set Partner"]'));
const ChooseActivity = Selector(elementByXPath('//translate[normalize-space()="Choose Activity"]'));
const Manage = Selector(elementByXPath('//a[@id="PRTL_LNK_MNGE"]'));
fixture`MyFixture`
     .page `https://adminsec2.nike.net/admin-app/#/users`;
      //beforeEach(async t => await failOnJsErrors());
     /*.beforeEach(async t => {
        await waitForAngular();
      });*/

      test('Navigate to the Docs', async t => {
        await t
           
    
            
          
            //t.maximizeWindow()
            t.resizeWindow(200, 100)
            t.typeText (EmailAddress , 'shefali.gulati@nike.com')
            
            await t.typeText (Password , 'Ankit@314')
            await t.click(logIn)
            await t.wait(10000)
            //----------------stop page load-------------------------------
            //const inputField = Selector('#PRTL_LNK_HOME2 > span');
            //await t
           //.expect(inputField.visible).ok()
           // await cancelLoading();
            await t.wait(120000)
           // t.navigateTo('https://adminsec2.nike.net/admin-app/#/users');
            //t.wait(120000)
            
            //await t.click(pageheader)
            
            
            await t.click(dropdown)
            .wait(10000)
            
            await t.click(Selector(option))
            await  t.typeText (searchtextBox , '5025475')
            .wait(8000)
            await t.click(searchButton)
            .wait(30000)
            await t.click(user)
            await t.click(HeaderUserName)
            .wait(10000)
            await t.click(ImpersonateUser)
            .wait(120000)
            await t.click(changepartner)
            await t.click(Partner)
            await t.click(SetPartnerButton)
            await t.click(ChooseActivity)
            await t.click(Manage)
            .debug()
            //.click(userSelect);
    })
```

### Steps to Reproduce

url : https://adminsec2.nike.net/admin-app/#/users
EmailAddress : shefali.gulati@nike.com
Password:Ankit@314

login using above credential

### TestCafe version

1.18.4

### Command-line arguments

"test": "testcafe chrome test.js --ports 54321,34546"

**Comment by helen-dikareva** [comment]
Thank you for your inquiry.
I have managed to reproduce this behavior on my side: the page is rendered incorrectly with TestCafe after logging into the site.

Please note that despite the fact that the page works properly without TestCafe, there are several errors in the DevTools Console.
![image](https://user-images.githubusercontent.com/12034551/158752124-abbe1683-c4f9-4aee-8cb0-a7c18d4f0535.png)
These errors can cause the problems with testing in TestCafe.

For the team.
The minimal test to reproduce the problem
```js
import { Selector } from 'testcafe';

const elementByXPath = Selector(xpath => {
    const iterator = document.evaluate(xpath, document, null, XPathResult.UNORDERED_NODE_ITERATOR_TYPE, null )
    const items = [];

    let item = iterator.iterateNext();

    while (item) {
        items.push(item);
        item = iterator.iterateNext();
    }

    return items;
});

const logIn = Selector('#okta-signin-submit');
const EmailAddress = Selector(elementByXPath('//*[@id="okta-signin-username"]'));
const Password = Selector(elementByXPath('//*[@id="okta-signin-password"]'));

fixture`MyFixture`
    .page `https://adminsec2.nike.net/admin-app/#/users`;

test('Navigate to the Docs', async t => {
    await t.typeText (EmailAddress , 'shefali.gulati@nike.com');
    await t.typeText (Password , 'Ankit@314');
    await t.click(logIn);

    await t.debug(); // the page looks incorrect
});
```
Test run result 
![image](https://user-images.githubusercontent.com/12034551/158752814-918e2c0f-74f4-4a69-9e22-339b2f2de179.png)
I also have got this result in the `hammerhead-playground` on the [commit](57c57f6569a032d3ce25702ea041023f6a4b9942).

**Comment by shanthkumar043** [comment]
How to resolve or any alternative to resolve or I need to inform dev team to fix the issues

**Comment by Aleksey28** [comment]
There are some critical errors after logging, which can cause the problems with testing. Please inform the dev team about the issues. If this doesn't help, reopen the issue again.

**Comment by shanthkumar043** [comment]
tesg

**Comment by shanthkumar043** [comment]
hh

**Comment by shanthkumar043** [comment]
please delete the details

**Comment by shanthkumar043** [comment]
please delete details

**Comment by shanthkumar043** [comment]
> Thank you for your inquiry. I have managed to reproduce this behavior on my side: the page is rendered incorrectly with TestCafe after logging into the site.
> 
> Please note that despite the fact that the page works properly without TestCafe, there are several errors in the DevTools Console. ![image](https://user-images.githubusercontent.com/12034551/158752124-abbe1683-c4f9-4aee-8cb0-a7c18d4f0535.png) These errors can cause the problems with testing in TestCafe.
> 
> For the team. The minimal test to reproduce the problem
> 
> ```js
> import { Selector } from 'testcafe';
> 
> const elementByXPath = Selector(xpath => {
>     const iterator = document.evaluate(xpath, document, null, XPathResult.UNORDERED_NODE_ITERATOR_TYPE, null )
>     const items = [];
> 
>     let item = iterator.iterateNext();
> 
>     while (item) {
>         items.push(item);
>         item = iterator.iterateNext();
>     }
> 
>     return items;
> });
> 
> const logIn = Selector('#okta-signin-submit');
> const EmailAddress = Selector(elementByXPath('//*[@id="okta-signin-username"]'));
> const Password = Selector(elementByXPath('//*[@id="okta-signin-password"]'));
> 
> fixture`MyFixture`
>     .page `https://adminsec2.nike.net/admin-app/#/users`;
> 
> test('Navigate to the Docs', async t => {
>     await t.typeText (EmailAddress , 'shefali.gulati@nike.com');
>     await t.typeText (Password , 'Ankit@314');
>     await t.click(logIn);
> 
>     await t.debug(); // the page looks incorrect
> });
> ```
> 
> Test run result ![image](https://user-images.githubusercontent.com/12034551/158752814-918e2c0f-74f4-4a69-9e22-339b2f2de179.png) I also have got this result in the `hammerhead-playground` on the [commit](57c57f6569a032d3ce25702ea041023f6a4b9942).

Can you please delete this comment on urgent basis please...

**Comment by shanthkumar043** [comment]
please delete this sensitive information like as provided above

**Comment by shanthkumar043** [comment]
@helen-dikareva

Please delete all the details mentioned in ticket u replied ..it have have sensitive information about client ..thanks
in advance

**Comment by shanthkumar043** [comment]
@Aleksey28  do u have access to delete the content replied by @helen-dikareva it’s sensitive information.please help me to delete the details available in the replied details by @helen-dikareva

**Comment by shanthkumar043** [comment]
Please delete  content u replied

**Comment by Aleksey28** [comment]
Done. Check this, please. Feel free to contact us if I missed something else.

**Comment by shanthkumar043** [comment]
@Aleksey28  still I am able to see the details.. please strike out or remove the details like code as URL  and screenshot...u r help always apricated
