### ISSUE TITLE
hasClass does nothing. t.expect(selector.hasClass('Blah').notOk('Blah')

### ISSUE THREAD

**Issue by future-mine** [DevExpress/testcafe#6932]
### File a new question on StackOverflow

https://stackoverflow.com/questions/ask?tags=testcafe

**Comment by future-mine** [comment]
t.expect(selector.hasClass('Blah').notOk('Blah')
It does nothing.
The test is stuck here without throwing an error or assertion.
Really weird.
Trying to debug for over 3 days. 
But nothing makes sense to me.

Thing is that the component is vue main app component So it will be updated frequentrly.

**Comment by Aleksey28** [comment]
Hi @future-mine

Please create a new issue with [the bug template](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&template=bug_report.yaml).
