### ISSUE TITLE
Unable to run TestCafe Browser Tool on my Mac running Big Sur.

### ISSUE THREAD

**Issue by vansgee** [DevExpress/testcafe#6935]
### What is your Scenario?

The TestCafe tool is complaining about the screen recording setting on my Mac. I've turned it on and off through my Mac settings but I am still unable to run TestCafe from the command line. TestCafe Studio works fine. Found a support note that said I needed to update my tool, https://testcafe.io/403664/release-notes/framework/2021-12-22-testcafe-v1-18-0-released#upgrade-instructions. Attempted to follow the instructions to upgrade the version but my version is still 1.16.1.

What can I do to get TestCafe running from the command line?

### What is the Current behavior?

Attempting to run TestCafe from the command line will always prompt me to change my screen recording settings for "TestCafe Brower Tools". Turning it on or off has no effect. I'm running TestCafe version 1.16.1

### What is the Expected behavior?

TestCafe to run from the command line.

### What is your public website URL? (or attach your complete example)

None

### What is your TestCafe test code?

None

### Steps to Reproduce

1. Open a terminal window
2. Goto me git repo
3. testcafe chrome:headless src/purchase-refund-test-US.js

### TestCafe version

1.16.1

### Node.js version

v16.14.2

### Command-line arguments

testcafe chrome:headless src/purchase-refund-test-US.js

### Browser name(s) and version(s)

Chrome 99.0.4844.74

### Platform(s) and version(s)

macOS 11.6.4

### Other

Started happening after I upgraded my macOS.

**Comment by VasilyStrelyaev** [comment]
To update the TestCafe version, perform the following steps (assuming that you install TestCafe locally in your project):

1. Ensure that the `package.json` file references the latest TestCafe version.
2. Check if the project directory contains the `package-lock.json` file that may reference an older version.
3. Remove `package-lock.json` if it exists. You can also remove the `node_modules` directory for clean installation.
4. Run `npm install`.

If you run a globally installed TestCafe module, simply update it with `npm install -g testcafe`.

After you successfully updated TestCafe to the latest version, you will need to follow instructions from https://testcafe.io/403664/release-notes/framework/2021-12-22-testcafe-v1-18-0-released#upgrade-instructions

If you do not want to update, you can grant screen recording permissions to TestCafe v1.16.1. To do this, select the correct instance of the `TestCafe Browser Tools` binary in system settings:

1. Open `System Preferences` -> `Security and Privacy` -> `Privacy`. Select `Screen Recording` in the right panel. Unlock the settings to allow modifications.
2. Select `TestCafe Browser Tools` and click the `–` button to remove the currently listed binary.
3. Click `+` and locate the binary from your project's `node_modules` directory. The binary can be found in `node_modules/testcafe-browser-tools/bin/mac/TestCafe Browser Tools.app`.
4. Select this file to add it to the list or permitted applications.

Try running TestCafe from the command line again. It should not require screen recording permissions any longer.
