### ISSUE TITLE
Render correct error text for internal uncaught errors

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#6936]
### What is your Scenario?

I'd like to use browser manipulation actions (e.g. `resizeWindow`, `maximizeWindow` etc.) the same way with other actions in my tests in the recording process.
Test run for such tests works properly.

TestCafe Studio issue: https://github.com/DevExpress/testcafe-studio/issues/4170

### What is the Current behavior?

When I add such actions in my tests (both `*.js/ts` and `*.testcafe` formats) and start recording for them in **TestCafe Studio** I get an error 

Such a message is displayed when any exception in TestCafe internal code is thrown.

![image](https://user-images.githubusercontent.com/12034551/159424123-1e1eb7dc-d51f-4a67-9c2d-4eaee425b302.png)

### What is the Expected behavior?

**Correct error message.**
We should show more descriptive error message. Otherwise we spend to much time to determinate the real cause and we won't be able to diagnost user's problems if they write to us about them.

Please add TestCafe Studio squad for review PR if API is changed or provide us with Breaking change list.

### What is your public website URL? (or attach your complete example)

any

### What is your TestCafe test code?

The smallest example could be the following
```js
fixture `Google`
  .page `https://google.com`;
  
test(`New Test`, async t => {
  await t.maximizeWindow();
});
```

### Your complete configuration file

-

### Your complete test report

-

### Screenshots

-

### Steps to Reproduce

1. Run test in TestCafe Studio 

### TestCafe version

1.18.4

### Node.js version

14.9.0

### Command-line arguments

-

### Browser name(s) and version(s)

any

### Platform(s) and version(s)

any

### Other

**The research result:**
The TestRun's constructor API was changed in the [PR](https://github.com/AlexKamaev/testcafe/commit/c1bd42625bfc3e00d44c1f2ee2f10b920ab359ec#diff-fef708c327f195e4413c0ec149074dc0dc5cde2f9f45e468283a8738f39bc9c0R232) @Aleksey28 
Specifically `messageBus` was added as a parameter.
But in Studio [we use this API ](https://github.com/DevExpress/testcafe-studio/blob/master/src/recorder/record-run.js#L48).

The `[object object]` error was inroduced after the [PR](https://github.com/DevExpress/testcafe/pull/6630) merging @AlexKamaev. [This line](https://github.com/DevExpress/testcafe/pull/6630/files#diff-6c23899482162d984f8bdf510e8c3fca9f7b1853f7af0a7eefa9a4e564f8658bR110) raise error `"TypeError: Cannot read property 'on' of undefined"` and this error is catch in [the catch block](https://github.com/DevExpress/testcafe/blob/master/src/test-run/index.ts#L1550).  But still in Studio we get an unidentified `[object object]` error.

**Comment by Florian-HH** [comment]
I have the same issue with "Uncaught object "[object Object]" was thrown. Throw Error instead." in Testcafe version 1.20.0-rc.1 for selectors where I try to get the text with .innerText or .textContent.

**Comment by AlexKamaev** [comment]
@Florian-HH I believe this issue is not related to the original one. Please share your project and your test code with us so that we can reproduce the issue on our side

**Comment by Florian-HH** [comment]
@AlexKamaev I am sorry, but the project and the test code is owned by a company and can't be shared.
What I can say is that the object is the result of a java script function which updates the value every 1000ms. This value is shown in the html in a sub element of an svg. The test code tries to assign this value to a const via textContent. Does that help?

**Comment by miherlosev** [comment]
Hi @Florian-HH,

We need an example that we can reproduce locally without any additional setup (see [how to create a minimal working example](https://testcafe.io/402636/faq?search#how-to-create-a-minimal-working-example-when-you-submit-an-issue)). If you can create such an example please create a separate issue and attach an example to it. Also, it's not necessary to use the production code that cann't be shared. It's possible to create a simple example based on production code. Such example will not contain private information.
