### ISSUE TITLE
Requests returning 204 NO_CONTENT fail to complete

### ISSUE THREAD

**Issue by tomjonkman** [DevExpress/testcafe#6938]
### What is your Scenario?

In my test I'm making a call to an API endpoint that returns 204 NO CONTENT. I would like to be able to call these endpoints with the browser actually receiving the 204 and complete the request.

### What is the Current behavior?

A request with a 204 response will fail to complete and stay on pending. 
The request is made and handled by the API, but the browser does not receive the 204 response. 
If I change the status response code to 200 OK it works like expected.

### What is the Expected behavior?

The 204 response should be catched by the browser just like any other status response code.

### What is your public website URL? (or attach your complete example)

Can't share and don't have time for a sandbox :(

### What is your TestCafe test code?

Not possible unfortunately.

### Your complete configuration file

{
  "skipJsErrors": true,
  "disablePageCaching": true
}

### Steps to Reproduce

1. Create a button that makes a request that gets a 204 response
2. Write a test that clicks the button
3. Check the network tab to see that the request stays on pending forever

### TestCafe version

1.16.1

### Node.js version

14.16.1

### Command-line arguments

chrome -L

### Browser name(s) and version(s)

Chrome

### Platform(s) and version(s)

Windows

**Comment by Aleksey28** [comment]
Hi @tomjonkman ,

I can't reproduce your case based on your description. My implementation:
```js
//server.js
const http = require('http');

const hostname = 'localhost';
const port1    = 3000;
const port2    = 3001;

const server1 = http.createServer((req, res) => {
    res.statusCode = 200;
    res.setHeader('Content-Type', 'text/plain');
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.end('Ok');
});

const server2 = http.createServer((req, res) => {
    res.statusCode = 204;
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.end();
});

server1.listen(port1, hostname, () => {
    console.log(`Server running at http://${hostname}:${port1}/`);
});

server2.listen(port2, hostname, () => {
    console.log(`Server running at http://${hostname}:${port2}/`);
});
```
```html
<!--index.html-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <button id="request200">Request 200</button>
    <button id="request204">Request 204</button>
    <script>
        document.querySelector('#request200').addEventListener('click', async () => {
            const response = await fetch('http://localhost:3000/');
            const result   = await response.text();
            console.log(result);
        });
        document.querySelector('#request204').addEventListener('click', async () => {
            const res  = await fetch('http://localhost:3001/');
            const body = await res.text();
            console.log(body);
        });
    </script>
</body>
</html>
```
```js
//test.js
fixture`Requests returning 204 NO_CONTENT fail to complete`
    .page('./index.html');

test('test', async (t) => {
    await t.click('#request200');
    await t.click('#request204');
    await t.debug();
})
```

Please create an example, which demonstrates this issue or modify my example.
