### ISSUE TITLE
Separate TestCafe CLI

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#694]
Separate CLI into a separate package `testcafe-cli`, like `gulp` does. `testcafe-cli` must be installed globally to use the CLI, and runner must be installed in project local folder. 

Pros:
 - Disk space economy due to removing unneeded runner code in globally installed CLI.
 - Solved problem with reporter and browser provider plugins: we can't use locally installed plugins in global TestCafe installation yet, because require works relative to the script file, not to the working directory.

Cons:
 - Users are forced to install two packages, if they want to use CLI.
 - As a result, major CLI upgrades that are depend on runner upgrades will require manual upgrade of these two packages.

**Comment by inikulin** [comment]
> As a result, major CLI upgrades that are depend on runner upgrades will require manual upgrade of these two packages.

Not a problem actually, CLI code can still be in locally installed TestCafe, we will just perform lookup and delegate handling to testcafe package.

**Comment by inikulin** [comment]
We've decided to go with all-in-one approach
