### ISSUE TITLE
Retry browser connection on failure for CI

### ISSUE THREAD

**Issue by DKhalil** [DevExpress/testcafe#6943]
### What is your Scenario?

I'm running testcafe within the bitbucket CI, which runs great, except sometimes it will run into a browser connection timeout. The suggestions coming up are increasing "browserInitTimeout", which doesn't really do anything.

### What are you suggesting?

It would be great to have an option to just retry the whole process on failure instead of testcafe throwing an error, similar to quarantine mode retrying tests for a specified amount of times

**Comment by Dmitry-Ostashev** [comment]
TestCafe already has the described feature. It would restart browser three times in case of a connection error. Could you please describe how you run your tests in greater detail? Test file example, report and yaml file example will be greatly appreciated. It might help us to determine a cause of the browser error in your case.

**Comment by DKhalil** [comment]
@Dmitry-Ostashev sorry, took me a while. Yes of course. The issue is also still relevant.

bitbucket.yml:
```
image: circleci/node:16-browsers

pipelines:
  default:
    - step:
        name: Testcafe run
        caches:
          - node
        script:
          - yarn install --frozen-lockfile
          - testbuild=true locale=sv yarn build-no-modern
          - yarn testcafe
          - testbuild=true locale=zz yarn build-no-modern
          - yarn testcafe

```

This result will sometimes (30-50%) appear after in the 2nd run of the test:
```
yarn run v1.22.15
$ testcafe 'chrome:headless --window-size="1280,1080" --no-sandbox --disable-dev-shm-usage' tests/testcafe -q attemptLimit=3,successThreshold=1 --app "testbuild=true locale=zz yarn start" --app-init-delay 5000
ERROR Cannot establish one or more browser connections.
1 of 1 browser connections have not been established:
- chrome:headless --window-size=1280,1080 --no-sandbox --disable-dev-shm-usage
Hints:
- Increase the value of the "browserInitTimeout" option if it is too low (currently: 2 minutes for local browsers and 6 minutes for remote browsers). This option determines how long TestCafe waits for browsers to be ready.
- The error can also be caused by network issues or remote device failure. Make sure that your network connection is stable and you can reach the remote device.
Type "testcafe -h" for help.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
```

**Comment by felis2803** [comment]
This may be an issue with the Bitbucket environment. Could you please create a ready-to-use repository using Bitbucket with which it's possible to reproduce the issue?
