### ISSUE TITLE
Multi Tab/Window Issue with Dynamic URL

### ISSUE THREAD

**Issue by TusharBachchan** [DevExpress/testcafe#6946]
### What is your Scenario?

"blob:[myproject.com/57019f99-239e-426a-8cb2-fee08b67e519](https://myproject.com/57019f99-239e-426a-8cb2-fee08b67e519)" -> This is a sample Url generated after clicking the print button. Here the part "blob:[myproject.com](https://myproject.com/)" is static and this value -> "57019f99-239e-426a-8cb2-fee08b67e519", keeps changing all the time, we want to access as well as close the new window opened which has this dynamic URL as the testcafe script does not move ahead due to this new window, please suggest a way by which we close this new window and our script can proceed further steps in the automation process.

### What is the Current behavior?

When we click on a button a new window is opened -> "Untitled Google Chrome", due to this window our script pauses and futher lines of code is not executed.

### What is the Expected behavior?

We want to access that window having dynamic URL and then close it and get back to the previous window which had the button which triggered this new window.

### What is your public website URL? (or attach your complete example)

NA

### What is your TestCafe test code?

NA

### Your complete configuration file

NA

### Steps to Reproduce

1. We login in our application
2. Then We click on a button on one screen
3. The button click results in opening of a new window with dynamic URL
4. We are not able to switch to this new window as well as we can't close it
5. Due to opening of this new window the script for previous window also stops and it freezes, we can't close this new window as we can't access it.

### TestCafe version

1.18.4

### Node.js version

v14.17.5

### Command-line arguments

testcafe chrome test.js

**Comment by AlexKamaev** [comment]
TestCafe cannot process native print dialogs, so it's unclear how TestCafe works in your specific scenario. Moreover, TestCafe has a known issue with the blob links. Please track the [https://github.com/DevExpress/testcafe/issues/5574](https://github.com/DevExpress/testcafe/issues/5574) issue for details. If you think that the issue is not related to #5574, please share your full example to demonstrate it.

**Comment by AlexKamaev** [comment]
Thank you for the additional information. However, we need a simple sample that we can easily run on our side in order to replicate the issue and research its cause. To learn how to create an example, review the following article: [How To: Create a Minimal Working Example When You Submit an Issue](https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue). We look forward to your response.

**Comment by TusharBachchan** [comment]
Thank you for the response, We have added a similar code but for now we can't create a similar situation , we will have to use some external resources for a page which shows some data, the page containing this data will have a dynamic URL due to blob,  but we can share the screenshots of our dev tools for a clear picture of what's happening in our Application along with some dummy code.

1st Screenshot : Shows the print button which opens a pdf in a new tab with the dynamic blob URL
![image](https://user-images.githubusercontent.com/57787633/161915224-3f2fce1f-66a4-4d9c-8d50-f7646d293c6c.png)
2nd Screenshot : Shows the Dynamic blob URL in which the pdf opens 
![image](https://user-images.githubusercontent.com/57787633/161925162-4cec0b90-a51d-4b94-92c0-4fd21c04c3e0.png)

Dummy Code Snippet :

`import { Selector } from 'testcafe';

fixture `New Fixture`
.page `https://www.example.com/`;

test('New Test', async t => {
await t
.typeText('#username', 'username') // type username
.typeText('#login-password', 'password') // type password
.click(Selector('#loginForm button').withText('Sign in')) // Sign in into the application
.click(Selector('[role="menuitem"]').withExactText('Funds')) // Clicking on Funds Dropdown
.click(Selector('[role="menuitem"]').withExactText('Print Checks')) // Selecting Print Check from Funds Dropdown to navigate to Print Check screen
.click(Selector('#btnPrePrint')) // Clicking on the print button which opens the new tab with a dynamic url whose structure is explained earlier
.wait(1000)
const s=await ClientFunction(() => window.location.pathname)() // We are trying to get that dynamic blob URL
await t.switchToWindow(f1 => f1.url.pathname === s) // We are trying to that dynamic blob URL
`});`

In case you need more information, can we please set up a call if it's convenient for you? As this issue is blocking a lot of our tasks.

**Comment by TusharBachchan** [comment]
> We cannot have a call on this. Your scenario is quite complex and we cannot reproduce it on our side. So, we have to ask you to share a small reproducible example. I cannot guarantee that we'll fix your scenario in the near future as it contains a lot of edge cases (multiple windows, the print button, and a pdf viewer). I realize it may take time, but we do need reproducible steps and a sample project to be able to proceed.

We have created a Sample project which replicates our issue : [Sample-Project](https://github.com/TusharBachchan/Sample_Project)

Please have a look at it and let us know if anything else is required.
**Reminder of The issue** : "blob:[myproject.com/57019f99-239e-426a-8cb2-fee08b67e519](https://myproject.com/57019f99-239e-426a-8cb2-fee08b67e519)" -> This is a sample Url generated after clicking the print button. Here the part "blob:[myproject.com](https://myproject.com/)" is static and this value -> "57019f99-239e-426a-8cb2-fee08b67e519", keeps changing all the time, we want to access as well as close the new window opened which has this dynamic URL as the testcafe script does not move ahead due to this new window, please suggest a way by which we close this new window and our script can proceed further steps in the automation process.

**Comment by AlexKamaev** [comment]
Thank you for your sample. I managed to reproduce the issue. It's really related to #5574
