### ISSUE TITLE
Feature to start chromium-based browsers with remote debugging mode to allow to use Puppeteer during a test run.

### ISSUE THREAD

**Issue by pavlobu** [DevExpress/testcafe#6951]
### What is your Scenario?

TestCafe is a great tool, thank you for developing and maintaining it!
I really think that TestCafe can benefit even more if it is combined with the power of Puppeteer for chromium based browsers.
Things like setting up specific time zone during a test run, setting up geolocation, changing emulated device orientation during test run, resizing test window during a test run are not doable with built in TestCafe features but can be done with the help of Puppeteer.

To use Puppeteer with TestCafe Chrome we need to use --remote-debugging-port=<any-port-nubmer> flag in cli.

This will start Chrome browser in development mode and Puppeteer can connect to it.

If chromium based browsers during TestCafe execution will start with their own remote debugging port number during a test, this will be a great start for us and will open great opportunities for developers to write even better tests with TestCafe.
For example they can develop their own NodeJS http server to accept requests to do certain actions on opened chromium browser windows that are running tests with tests cafe. And this would be possible to do dynamically during a test run.

I can submit a PR with that feature and feature flag it with some cli command. But I need any word from you guys that you approve these changes. Otherwise it will remain on my custom TestCafe fork.

### What are you suggesting?

Add a feature flagged feature to enable starting chromium based browsers with --remote-debugging-port=<any-port-nubmer> . This will allow us to use Puppeteer to remotely connect to testcafe chrome browser instance and control this browser from puppeteer remotely dynamically during a test.

### What alternatives have you considered?

Really there is none.
I've only heard of the other tool for Firefox browser that has similar to Puppeteer features such as Marionette. This can be also added as well for Firefox browser.

### Additional context

Later on when we have TestCafe chromium based testing browsers starting in remote debugging mode, we can add a simple NodeJS http helper server that executes puppeteer commands for specific testing browser upon test code request. testcafe will be able to communicate to such server during a test to change browser conditions during a test run e.g. specific network conditions, specific browser client timezone, specific device size and screen resizing during a test and so on.

<img width="845" alt="Screenshot 2022-03-29 at 17 39 09" src="https://user-images.githubusercontent.com/14937251/160637289-ecbc872b-e4dc-48d5-a337-71ebaf393b4c.png">
.

**Comment by AlexKamaev** [comment]
Please take a look at the `cdpPort` option. It seems that it should satisfy you requirements. Refer to the following article to get details: [https://testcafe.io/documentation/402828/guides/concepts/browsers#emulator-parameters](https://testcafe.io/documentation/402828/guides/concepts/browsers#emulator-parameters)
Internally, this flag adds the `--remote-debugging-port` argument to the chrome launch command.
You can also get the `chrome debug interface` instance to execute some commands specific to chrome devtools. You can take a look at the following test to see how it works:
[https://github.com/DevExpress/testcafe/blob/016e481c7612390c8d7f10e5363085d8cf1c2356/test/functional/fixtures/regression/gh-3929/testcafe-fixtures/index.js#L10](https://github.com/DevExpress/testcafe/blob/016e481c7612390c8d7f10e5363085d8cf1c2356/test/functional/fixtures/regression/gh-3929/testcafe-fixtures/index.js#L10)
If these solutions do not help, feel free to ask further questions.

**Comment by pavlobu** [comment]
@AlexKamaev thanks for a swift response

cdpPort actually works but it works only for 1 browser. 
This doesn't work with concurrency option greater than 1

**Comment by pavlobu** [comment]
@AlexKamaev ok, so cdpPort works indeed but seems there are problems to use it in non-headless mode. I'm getting this error for browser combination 

```
GeneralError: Cannot find the browser. "chrome:cdpPort" is neither a known browser alias, nor a path to an executable file.
    at Object.getBrowserInfo (/fun/path/node_modules/testcafe/lib/browser/provider/pool.js:94:19)
    at Function.all (<anonymous>:null:null)
    at TestCafeConfiguration._getBrowserInfo (/fun/path/node_modules/testcafe/lib/configuration/testcafe-configuration.js:185:29)
    at TestCafeConfiguration.asyncMergeOptions (/fun/path/node_modules/testcafe/lib/configuration/testcafe-configuration.js:64:44)
    at Runner._setConfigurationOptions (/fun/path/node_modules/testcafe/lib/runner/index.js:434:9)
 {
  code: 'E1005',
  data: [ 'chrome:cdpPort' ]
}
```

**Comment by AlexKamaev** [comment]
The `cdpPort` option works with the enabled `emulation` option. So, the correct way to use it will be the following:

```
testcafe "chrome:emulation:cdpPort=9229" test.js
```

As a result, the Chrome browser will be launched with the following command line arguments:

```
--remote-debugging-port=9229 --user-data-dir=<my_custom_path>. --disable-infobars --disable-session-crashed-bubble --no-first-run --new-window
--disable-background-networking --disable-ipc-flooding-protection --disable-background-timer-throttling
--disable-backgrounding-occluded-windows --autoplay-policy=no-user-gesture-required
```

**Comment by pavlobu** [comment]
@AlexKamaev awesome. 
    `chrome:emulation:cdpPort:device=Pixel` -- mobile emulation with cdpPort
    `chrome:emulation:cdpPort` -- regular desktop mode
worked for me.
thank you!

**Comment by pavlobu** [comment]
just in case if someone came in this thread from the internet. here is how I scan for available cdpPorts when tests are running using puppeteer:

```ts
// connect to browser with puppeteer scanning all ports example code
const puppeteer = require('puppeteer');

(async () => {
  const openForDebugChromePorts = [];
  for (let i = 100; i < 66000; ++i) {
    if (i === 49153) { // idk, for some reason this script freezes on this port
      continue;
    }
    const browserURL = `http://127.0.0.1:${i}`;
    try {
      const browser = await puppeteer.connect({ browserURL });
      console.info(browser);
      openForDebugChromePorts.push(i);
    } catch (err) {
      if (err.code !== 'ECONNREFUSED' && err.code !== 'ERR_INVALID_URL') {
        console.log('err', err);
      }
    }
  }
  console.log('openForDebugChromePorts', openForDebugChromePorts);
})();
```

**Comment by Aleksey28** [comment]
@pavlobu,

You are always welcome!
