### ISSUE TITLE
Cannot Login to Angular App that uses Angular 13 ERROR TypeError: Cannot read properties of undefined (reading 'digest') 

### ISSUE THREAD

**Issue by jenaewhitmore** [DevExpress/testcafe#6954]
### What is your Scenario?

We upgraded to angular 13 from angular 9 and we are no longer able to reach our login page.

### What is the Current behavior?

An error is displayed in the console just trying to login
//console error = hammerhead.js:15     
    //    ERROR TypeError: Cannot read properties of undefined (reading 'digest')
    //    at JwtWindowCryptoService.calcHash (vendor.js:221136:74)
    //    at JwtWindowCryptoService.generateCodeChallenge (vendor.js:221123:17)
    //    at UrlService.createUrlCodeFlowAuthorize (vendor.js:222609:40)
    //    at UrlService.getAuthorizeUrl (vendor.js:222295:19)
    //    at SafeSubscriber._next (vendor.js:226686:23)
    //    at SafeSubscriber.__tryOrUnsub (vendor.js:64444:16)
    //    at SafeSubscriber.next (vendor.js:64383:22)
    //    at Subscriber._next (vendor.js:64333:26)
    //    at Subscriber.next (vendor.js:64310:18)
    //    at Observable._subscribe (vendor.js:69185:20)

### What is the Expected behavior?

To be able to get to the login page

### What is your public website URL? (or attach your complete example)

https://testcafe.fleetcommand.biz/

### What is your TestCafe test code?

import { Selector } from "testcafe";

fixture`Home Test`
.page`testcafe.fleetcommand.biz`;

test('Can I Login', async controller => {

    const button = Selector('button').withText('Login');
    await controller 
    .typeText('#Username', 'user')
    .typeText('#Password', 'password')
    .click(button);

### Your complete configuration file

{
    "browsers": "edge",
    "concurrency": 1,
    "skipJsErrors": true, 
}

### Your complete test report

//console error = hammerhead.js:15     
    //    ERROR TypeError: Cannot read properties of undefined (reading 'digest')
    //    at JwtWindowCryptoService.calcHash (vendor.js:221136:74)
    //    at JwtWindowCryptoService.generateCodeChallenge (vendor.js:221123:17)
    //    at UrlService.createUrlCodeFlowAuthorize (vendor.js:222609:40)
    //    at UrlService.getAuthorizeUrl (vendor.js:222295:19)
    //    at SafeSubscriber._next (vendor.js:226686:23)
    //    at SafeSubscriber.__tryOrUnsub (vendor.js:64444:16)
    //    at SafeSubscriber.next (vendor.js:64383:22)
    //    at Subscriber._next (vendor.js:64333:26)
    //    at Subscriber.next (vendor.js:64310:18)
    //    at Observable._subscribe (vendor.js:69185:20)

× Can I Login

   1) The specified selector does not match any element in the DOM tree.

       > | Selector('#Username')

      Browser: Microsoft Edge 99.0.1150.39 / Windows 10

          5 |
          6 |test('Can I Login', async controller => {
          7 |
          8 |    const button = Selector('button').withText('Login');
          9 |    await controller
       > 10 |    .typeText('#Username', 'Username')
         11 |    .typeText('#Password', 'Password')
         12 |    .click(button);
         13 |//console error = hammerhead.js:15     
         14 |    //    ERROR TypeError: Cannot read properties of undefined (reading 'digest')
         15 |    //    at JwtWindowCryptoService.calcHash (vendor.js:221136:74)

         at <anonymous> (D:\Git\TestCafeTools\tests\pagetests\Angular13-Tests.ts:10:6)
         at <anonymous> (D:\Git\TestCafeTools\tests\pagetests\Angular13-Tests.ts:8:71)
         at __awaiter (D:\Git\TestCafeTools\tests\pagetests\Angular13-Tests.ts:4:12)
         at <anonymous> (D:\Git\TestCafeTools\tests\pagetests\Angular13-Tests.ts:6:40)

### Steps to Reproduce

1.  Run the test script that will
2. Navigate to the site
3. Enter username
4. Enter password
5. Click login button

### TestCafe version

1.18.4

### Node.js version

16.14.0

### Command-line arguments

testcafe .\tests\pagetests\Angular13-Tests.ts

### Browser name(s) and version(s)

edge

### Platform(s) and version(s)

Window 10

### Other

Ill be sending the user name and password to the email stated above

**Comment by AlexKamaev** [comment]
I was not able to reproduce the issue. I've got the 404 error when I tried to reach the `https://testcafe.fleetcommand.biz/` site. Please share a working example or create a simplified sample that demonstrates the issue. Thank you in advance.

**Comment by BullDoggen** [comment]
We have exactly the same issue, just updated to Angular 13. Unfortunately can't share any kind of sample project to reproduce.

**Comment by Aleksey28** [comment]
We need a working example to research this issue. Please try to create a simplified sample if you can't share your project.

**Comment by jenaewhitmore** [comment]
> I was not able to reproduce the issue. I've got the 404 error when I tried to reach the `https://testcafe.fleetcommand.biz/` site. Please share a working example or create a simplified sample that demonstrates the issue. Thank you in advance.

I sent the username and password to the email stated on the testcafe page, is that not being used?

**Comment by Aleksey28** [comment]
As well as @AlexKamaev, I got the 404 error when I tried to reach the [https://testcafe.fleetcommand.biz/](https://testcafe.fleetcommand.biz/) site. We are also awaiting a written confirmation that must permit us to remotely access the website and its internal resources.

**Comment by jenaewhitmore** [comment]
> As well as @AlexKamaev, I got the 404 error when I tried to reach the https://testcafe.fleetcommand.biz/ site. We are also awaiting a written confirmation that must permit us to remotely access the website and its internal resources.

I have already sent the username and password to support@devexpress.com. and referenced this issue,  you don't have access to that email? I can't give out the credentials here...

**Comment by jenaewhitmore** [comment]
> > > As well as @AlexKamaev, I got the 404 error when I tried to reach the https://testcafe.fleetcommand.biz/ site. We are also awaiting a written confirmation that must permit us to remotely access the website and its internal resources.
> > 
> > 
> > I have already sent the username and password to [support@devexpress.com](mailto:support@devexpress.com). and referenced this issue, you don't have access to that email? I can't give out the credentials here...
> 
> They will need a written permission from the owner of domain/software you are testing before they can access it with given credentials.

Who would that need to be? I'm the senior SDET over the project, do you need the CEO?

**Comment by jenaewhitmore** [comment]
> > > > > As well as @AlexKamaev, I got the 404 error when I tried to reach the https://testcafe.fleetcommand.biz/ site. We are also awaiting a written confirmation that must permit us to remotely access the website and its internal resources.
> > > > 
> > > > 
> > > > I have already sent the username and password to [support@devexpress.com](mailto:support@devexpress.com). and referenced this issue, you don't have access to that email? I can't give out the credentials here...
> > > 
> > > 
> > > They will need a written permission from the owner of domain/software you are testing before they can access it with given credentials.
> > 
> > 
> > Who would that need to be? I'm the senior SDET over the project, do you need the CEO?
> 
> When I needed to provide the permission I got it from our CEO, because he is the official owner of our domain.

Is permission from our CTO sufficient?

**Comment by Aleksey28** [comment]
Yes, it is. Permission from your CTO is sufficient.

**Comment by BullDoggen** [comment]
> Is permission from our CTO sufficient?

Please reply if you can proceed with this, otherwise I could try to get the permission and sample code from our side.

**Comment by jenaewhitmore** [comment]
> > Is permission from our CTO sufficient?
> 
> Please reply if you can proceed with this, otherwise I could try to get the permission and sample code from our side.

My vice president of IT will be sending the email with permission over today

**Comment by Aleksey28** [comment]
Thank you for the example. I reproduced this behavior. The issue occurs because of redirecting after opening the following page: https://testcafe.fleetcommand.biz/. We will research it and update this thread once we have any news.

In the meantime, you can open the login page directly: https://fleetauth-dev.azurewebsites.net/Account/Login.

**Comment by jenaewhitmore** [comment]
> Thank you for the example. I reproduced this behavior. The issue occurs because of redirecting after opening the following page: https://testcafe.fleetcommand.biz/. We will research it and update this thread once we have any news.
> 
> Can u please remove the reference to our dev Auth from this thread? That should not be publicly listed.

**Comment by Aleksey28** [comment]
Done.

**Comment by Aleksey28** [comment]
I have news on this issue. It happens because some features of the browser don't work correctly without a secure connection but Testcafe starts testing with HTTP by default. To make this work, it is necessary to use the [SSL option](https://testcafe.io/documentation/402639/reference/command-line-interface#--ssl-options). The easiest way is illustrated in [this example](https://testcafe.io/documentation/402839/guides/advanced-guides/test-https-features-and-http2-websites#generate-a-certificate-in-your-code).

**Comment by jenaewhitmore** [comment]
> I have news on this issue. It happens because some features of the browser don't work correctly without a secure connection but Testcafe starts testing with HTTP by default. To make this work, it is necessary to use the [SSL option](https://testcafe.io/documentation/402639/reference/command-line-interface#--ssl-options). The easiest way is illustrated in [this example](https://testcafe.io/documentation/402839/guides/advanced-guides/test-https-features-and-http2-websites#generate-a-certificate-in-your-code).

I don't understand what I need to do to be able to run the tests locally and in the CI using the illustration

**Comment by jenaewhitmore** [comment]
> > I have news on this issue. It happens because some features of the browser don't work correctly without a secure connection but Testcafe starts testing with HTTP by default. To make this work, it is necessary to use the [SSL option](https://testcafe.io/documentation/402639/reference/command-line-interface#--ssl-options). The easiest way is illustrated in [this example](https://testcafe.io/documentation/402839/guides/advanced-guides/test-https-features-and-http2-websites#generate-a-certificate-in-your-code).
> 
> I don't understand what I need to do to be able to run the tests locally and in the CI using the illustration

Oh wait I see, I have to create my own node.js application. Did you try this and it worked? Ill try now.

**Comment by jenaewhitmore** [comment]
> > > I have news on this issue. It happens because some features of the browser don't work correctly without a secure connection but Testcafe starts testing with HTTP by default. To make this work, it is necessary to use the [SSL option](https://testcafe.io/documentation/402639/reference/command-line-interface#--ssl-options). The easiest way is illustrated in [this example](https://testcafe.io/documentation/402839/guides/advanced-guides/test-https-features-and-http2-websites#generate-a-certificate-in-your-code).
> > 
> > 
> > I don't understand what I need to do to be able to run the tests locally and in the CI using the illustration
> 
> Oh wait I see, I have to create my own node.js application. Did you try this and it worked? Ill try now.

Ok, I tried and it does work, Its a heavy way to do things now since we run tests by folder using the CLI. It means Ill have to create a server instance for each folder set we want to run in the CI, <sigh>

**Comment by jenaewhitmore** [comment]
> > > > I have news on this issue. It happens because some features of the browser don't work correctly without a secure connection but Testcafe starts testing with HTTP by default. To make this work, it is necessary to use the [SSL option](https://testcafe.io/documentation/402639/reference/command-line-interface#--ssl-options). The easiest way is illustrated in [this example](https://testcafe.io/documentation/402839/guides/advanced-guides/test-https-features-and-http2-websites#generate-a-certificate-in-your-code).
> > > 
> > > 
> > > I don't understand what I need to do to be able to run the tests locally and in the CI using the illustration
> > 
> > 
> > Oh wait I see, I have to create my own node.js application. Did you try this and it worked? Ill try now.
> 
> Ok, I tried and it does work, Its a heavy way to do things now since we run tests by folder using the CLI. It means Ill have to create a server instance for each folder set we want to run in the CI,

Not as bad as  I thought after implementing I just added a parameter to the node argument. For those with the same issue I did this:
1. Created a custom test cafe server instance. Created the testCafeRunner.ts file with the following code and added it to the base of the folder (make sure to install the selfsigned package with npm as a dev or main dependency)
```
 (async () => {
    const createTestCafe        = require('testcafe');
    const selfSignedSertificate = require('openssl-self-signed-certificate');

    const sslOptions = {
        key:  selfSignedSertificate.key,
        cert: selfSignedSertificate.cert,
    };

    const testCafeOptions = {
        hostname: 'localhost',
        port1:    1337,
        port2:    1338,
        sslOptions,
    };

    const testcafe = await createTestCafe(testCafeOptions);
    const tests = process.argv.slice(2)[0];

    await testcafe.createRunner()
        .src(tests)
        .run();

    await testcafe.close();
})();
```
2. To run the tests I use the following command
3. ` node testCafeRunner.ts pathToTests`

**Comment by Aleksey28** [comment]
Looks good. Well done.
