### ISSUE TITLE
beforeAll fixture hook also needed as in #3517

### ISSUE THREAD

**Issue by MikiPopovic** [DevExpress/testcafe#6959]
### What is your Scenario?

The scenario is the same as in the issue #3517.

I need to run some test preparation through the page UI and then execute all test in the fixture.

It would be too time consuming and repetitive to do all these actions before each test using beforeAll hook.

Any chance this feature might be added, please?

### What are you suggesting?

I need to run some test preparation through the page UI and then execute all test in the fixture.

It would be too time consuming and repetitive to do all these actions before each test using beforeAll hook.

Any chance this feature might be added, please?

**Comment by Aleksey28** [comment]
Hi, this feature already exists. Please use the following module to accomplish your task: [https://www.npmjs.com/package/testcafe-once-hook](https://www.npmjs.com/package/testcafe-once-hook).
