### ISSUE TITLE
Facing similar issue as #6695 - New window getting closed immediately (occasionally)

### ISSUE THREAD

**Issue by aarti315** [DevExpress/testcafe#6961]
### What is your Scenario?

Click on new link

### What is the Current behavior?

Link opens in new window on TestCafe and gets closed immediately. 

### What is the Expected behavior?

Link opens in new window and should not be closed immediately 

### What is your public website URL? (or attach your complete example)

Refer to #6695

### What is your TestCafe test code?

Can not share script

### Steps to Reproduce

1. Click on link
2.
3.

### TestCafe version

1.18.4

### Command-line arguments

testcafe chrome Test.js --disable-http2

**Comment by Aleksey28** [comment]
Hi @aarti315,

I'm not able to reproduce this behavior. Please create a minimal working example for further research - follow the instruction at the link below: [https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue](https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue).

**Comment by aarti315** [comment]
Thank you for sharing link to create Minimal working example. I will try to provide code sample.
