### ISSUE TITLE
please delete the content replied in  the issue 

### ISSUE THREAD

**Issue by shanthkumar043** [DevExpress/testcafe#6963]
### What is your Scenario?

please delete the content or delete this issue have client information 

#6929

### What is the Current behavior?

please delete the content or delete this issue have client information 

#6929

### What is the Expected behavior?

please delete the content or delete this issue have client information 

#6929

### What is your public website URL? (or attach your complete example)

please delete the content or delete this issue have client information 

#6929

### What is your TestCafe test code?

please delete the content or delete this issue have client information 

#6929

### Your complete configuration file

please delete the content or delete this issue have client information 

#6929

### Your complete test report

please delete the content or delete this issue have client information 

#6929

### Screenshots

please delete the content or delete this issue have client information 

#6929

### Steps to Reproduce

1.
2.
3.

### TestCafe version

1

### Node.js version

1

### Command-line arguments

1

### Browser name(s) and version(s)

1

**Comment by shanthkumar043** [comment]
please delete the details from mentioned tickets ...it has sensitive information https://github.com/DevExpress/testcafe/issues/6929

**Comment by shanthkumar043** [comment]
#6929 Please delete comments or hide all the comments details replied by @helen-dikareva .I tried to delete I am not able to delete..  @helen-dikareva  please delete the screenshot and code as u replied to my question it has client information

**Comment by shanthkumar043** [comment]
@testcafe-build-bot  please delete the content replied by @helen-dikareva  in the ticket #6929  it has client information.

**Comment by Aleksey28** [comment]
Done. Check this, please. Feel free to contact us if I missed something else.

**Comment by shanthkumar043** [comment]
@Aleksey28  Thanks
