### ISSUE TITLE
pathPattern ignoes ${RUN_ID} for videos (not screenshots)

### ISSUE THREAD

**Issue by bessey** [DevExpress/testcafe#6967]
### What is your Scenario?

We are customising the output of pathPattern for screenshots and videos as follows:

```
const screenShotPathPattern = "${TEST}/${RUN_ID}/${FILE_INDEX}.png"
const videoPathPattern = "${TEST}/${RUN_ID}/recording.mp4"
```

### What is the Current behavior?

We are seeing that even when running in quarantine mode, only screenshots are being namespaced with their run ID:
![Screenshot from 2022-04-06 12-27-47](https://user-images.githubusercontent.com/708200/161966123-f71c1b95-f8fb-4a95-9979-eef58e44cb6f.png)
![Screenshot from 2022-04-06 12-27-31](https://user-images.githubusercontent.com/708200/161966126-6dc94e4e-2a54-486a-a03d-6a04523e47ec.png)

### What is the Expected behavior?

Both videos and screenshots are namespaced, so that subsequent runs do not overwrite prior ones.

### What is your public website URL? (or attach your complete example)

Irrelevant, happens for all tests.

### What is your TestCafe test code?

Irrelevant, happens for all tests.

### Your complete configuration file

```js
# .testcaferc.js

const windowSize = { width: 1920, height: 1080 };

const isRunningInCI = process.env.CI;
const chromeLike = isRunningInCI ? "chromium" : "chrome";

// When we're running locally we are careful to make sure we don't overwrite previous run videos.
// In CI this is not an issue because we get a new filesystem on every run, so things are simpler.
// ${RUN_ID} distinguishes Quarantine Mode repeated runs from one another.
const screenShotPathPattern = isRunningInCI
  ? "${TEST}/${RUN_ID}/${FILE_INDEX}.png"
  : "${DATE}_${TIME}/${TEST}/${RUN_ID}/${FILE_INDEX}.png";
const videoPathPattern = isRunningInCI
  ? "${TEST}/${RUN_ID}/recording.mp4"
  : "${DATE}_${TIME}/${TEST}/${RUN_ID}/recording.mp4";

module.exports = {
  // Completely common config across all test suites. If there's any chance
  // someone would want to override it, it does not belong in here.
  common: {
    src: "./testcafe/tests/**/*.ts",
    selectorTimeout: 10000,
    assertionTimeout: 10000,
    pageLoadTimeout: 10000,
    testExecutionTimeout: 240000,
    reporter: [
      {
        name: "spec",
      },
      {
        name: "json",
        output: "results/report.json",
      },
      {
        name: "xunit",
        output: "results/report.xml",
      },
    ],
    screenshots: {
      path: "results/screenshots",
      pathPattern: screenShotPathPattern,
      takeOnFails: true,
    },
    compilerOptions: {
      typescript: {
        customCompilerModulePath: "../../node_modules/typescript",
      },
    },
  },
  // Video configuration. Unlike screenshots, configuring enables the feature
  // so just leave it out if you don't want to record videos
  video: {
    videoPath: "results/videos",
    videoOptions: {
      pathPattern: videoPathPattern,
    },
    videoEncodingOptions: {
      r: 10,
    },
  },
  // Convenience methods for browsers
  browsers: {
    chromeHeadless: {
      browsers: `${chromeLike}:headless --window-size=${windowSize.width},${windowSize.height}`,
    },
    chromeHeaded: {
      browsers: `${chromeLike} --window-size=${windowSize.width},${windowSize.height}`,
    },
    edgeHeaded: {
      browsers: `edge --window-size=${windowSize.width},${windowSize.height}`,
    },
    firefoxHeaded: {
      browsers: `firefox -width =${windowSize.width} -height ${windowSize.height}`,
    },
    firefoxHeadless: {
      browsers: `firefox:headless -width =${windowSize.width} -height ${windowSize.height}`,
    },
  },
  quarantineOnlyInCI: {
    quarantineMode: process.env.CI,
  },
};
```

### Steps to Reproduce

1. Include ${RUN_ID} in your videoOptions.pathPattern
2. Run in quarantine mode
3. Observe that it has no effect

### TestCafe version

1.18.5

### Command-line arguments

testcafe

**Comment by felis2803** [comment]
Hello @bessey,

Thank you for your report. I reproduced this bug. Until we fix it, try using `${QUARANTINE_ATTEMPT}` instead of `${RUN_ID}`.

**Comment by miherlosev** [comment]
Hi @bessey,

I investigated the issue further and I can say that everything works as expected.
TestCafe records a video of the whole test run. E.g. the video shows all test runs. In the video, you can see the `run-1` run, then - the `run-2` run and so on. So, placeholders related to `quarantine mode` do not make sense and they will be ignored.
