### ISSUE TITLE
Pressing spacebar does not select focused checkbox in Firefox

### ISSUE THREAD

**Issue by SpaceWolf87** [DevExpress/testcafe#6969]
### What is your Scenario?

Couple of our tests have started to fail recently due to the following issue. We updated testcafe from `1.15.0` to `1.18.4` just a few days ago so it might be related.

### What is the Current behavior?

In Firefox when you use `pressKey('space')` method it will not select/unselect checkbox with the focus. It seems to behave correctly in other browsers.

### What is the Expected behavior?

`pressKey('space')` method should work correctly regardless the browser.

### What is your public website URL? (or attach your complete example)

https://devexpress.github.io/testcafe/example/

### What is your TestCafe test code?

```ts
fixture`Testcafe Firefox Issue`
    .page`https://devexpress.github.io/testcafe/example/`;
test('Should check/uncheck checkbox on space key press', async () => {
    const testCheckbox = Selector('#tried-test-cafe');
    await t
        .click(testCheckbox)
        .expect(testCheckbox.checked).ok()
        .expect(testCheckbox.focused).ok()
        .pressKey('space')
        .expect(testCheckbox.checked).notOk();
});
```

### Steps to Reproduce

1. Set focus to checkbox type input.
2. call `pressKey('space')` method.
3. Checkbox value does not change.

### TestCafe version

1.18.4

### Node.js version

16.14.2

### Command-line arguments

testcafe firefox <test-file-path>

### Browser name(s) and version(s)

Firefox 99.0

**Comment by Aleksey28** [comment]
Thank you for your feedback. I reproduced this behavior. We will research it and update this thread once we have any news.
