### ISSUE TITLE
Is there way to customize error message on failure.

### ISSUE THREAD

**Issue by aprabh001c** [DevExpress/testcafe#6972]
### File a new question on StackOverflow

https://stackoverflow.com/questions/ask?tags=testcafe

**Comment by aprabh001c** [comment]
Instead of displaying where exactly code failed, just wanted to display error message alone
AssertionError: WebUiActions, verifyPageUrl: expected urlSegment activeaccount did not match actual url https://xxxxxxxxx expected false to be truthy

Dont want to display below portions:
-----------------------------------------------
Browser: Chrome 100.0.4896.60 / Linux 0.0
Screenshot: /app/automation/reports/screenshots/2022-04-05_20-39-04/test-67/run-3/Chrome_100.0.4896.60_Linux_0.0/errors/1.png


   32 |        };
   33 |        return false;

**Comment by Aleksey28** [comment]
Hi @aprabh001c ,
Yes, the [TestCafe Reporter plugin](https://testcafe.io/documentation/402810/guides/extend-testcafe/reporter-plugin#implement-the-reporter) is responsible for the output format. If you want to use your custom format, you can implement your personal reporter. Also, Testcafe has many built-in reporters, and NPM has a huge amount of third-party reporters. Try researching them - perhaps, you will find what you need.
