### ISSUE TITLE
Pressing and holding CTRL while clicking on a button doesn't work

### ISSUE THREAD

**Issue by dsuleimanova** [DevExpress/testcafe#6973]
### What is your Scenario?

There is a "DELETE' button that is visible but disabled:

`<a class="danger ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only ui-button-disabled ui-state-disabled" id="btn-delete-chassis" role="button" aria-disabled="true"><span class="ui-button-text">Delete</span></a>`

If  hold down the CTRL key, then the "DELETE'  button becomes active:
`<a class="danger ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" id="btn-delete-chassis" role="button" aria-disabled="false"><span class="ui-button-text">Delete</span></a>`

 Hold down CTRL while clicking on the button. A deletion confirmation dialog box will open.

Here the Test:
`await t
                .click(Selector('#btn-delete-chassis'), { modifiers: { ctrl: true }, speed: 0.05});`

### What is the Current behavior?

Key Pressed CTRL
click to disabled "DELETE' button. 
Button does not respond

### What is the Expected behavior?

Key Down CTRL
Wait for the "DELETE'  button to become enabled
Click the "DELETE'  button
Key UP CTRL

### What is your public website URL? (or attach your complete example)

It is internal

### What is your TestCafe test code?

`await t
.pressKey('ctrl')
.click(Selector('#btn-delete-chassis'), { modifiers: { ctrl: true }, speed: 0.05});`

### Screenshots

Manual test:
1) Before Press CTRL
![image](https://user-images.githubusercontent.com/97892213/162448233-9cc6a69f-7436-4f68-b76f-ccd66ebfdcca.png)

2) Press CTRL and hold:
![image](https://user-images.githubusercontent.com/97892213/162448516-6be981fa-96b7-42a7-a92f-339294f85f3d.png)

Testcafe trying to click to disabled button
![image](https://user-images.githubusercontent.com/97892213/162451241-9c9d130c-b772-430d-96de-6f85adc7f265.png)

### Steps to Reproduce

1. Press CTRL and hold
2. Click 'Delete' button
3. Key UP

### TestCafe version

1.18.5

### Node.js version

v17.1.0

### Command-line arguments

testcafe chrome -e test.js

### Browser name(s) and version(s)

Chrome Version 99.0.4844.74

### Platform(s) and version(s)

Ubuntu 18.04.5

**Comment by Aleksey28** [comment]
I didn't manage to reproduce the issue. Please create a simple sample by following this instruction: https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue.

**Comment by dsuleimanova** [comment]
handle button click in app:
`$.fn.confirmButton = function() {
    var btn = this.button();
    btn.button("disable");
    $(window).keydown(function(ev) {
        if (ev.ctrlKey || ev.metaKey) {
            btn.button();
            btn.button("enable");
        }
    }).keyup(function(ev) {
        if (ev.ctrlKey || ev.metaKey || ev.keyCode === 17) {
            btn.button();
            btn.button("disable");
        }
    });
    return btn;
};
`
Frontend button's properties:
before press CTRL:
`<a class="danger ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only ui-button-disabled ui-state-disabled" id="btn-delete-chassis" role="button" aria-disabled="true"><span class="ui-button-text">Delete</span></a>
`
After pressing CTRL:
`<a class="danger ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" id="btn-delete-chassis" role="button" aria-disabled="false"><span class="ui-button-text">Delete</span></a>`

Using jquery-2.1.0.min.js, jquery-ui.min.js

TESTCAFE CODE:
`test('003 | Test Chassis page. Delete Chassis', async t => {
    await t
        .setNativeDialogHandler((text) =>{
            console.log(text);
            true} )`
const deleteBtn = Selector('#btn-delete-chassis');
await t
                .click(Selector('#btn-delete-chassis'), { modifiers: { ctrl: true }, speed: 0.05});
}

**Comment by Aleksey28** [comment]
Thank you for your example. I reproduced this behavior. We will research it and update this thread once we have any news.

For the team:
```html
<!--page-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-2.1.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
</head>
<body>
<a class="danger ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only ui-button-disabled ui-state-disabled"
   id="btn-delete-chassis" role="button" aria-disabled="true">
    <span class="ui-button-text">Delete</span>
</a>
<script>
    $.fn.confirmButton = function () {
        var btn = this.button();
        btn.button('disable');
        $(window).keydown(function (ev) {
            if (ev.ctrlKey || ev.metaKey) {
                btn.button();
                btn.button('enable');
            }
        }).keyup(function (ev) {
            if (ev.ctrlKey || ev.metaKey || ev.keyCode === 17) {
                btn.button();
                btn.button('disable');
            }
        });
        btn.click(() => {
            this.text('Save');
        });
        return btn;
    };
    $('#btn-delete-chassis').confirmButton();
</script>
</body>
</html>
```

```js
// server
const express = require('express');
const path    = require('path');
module.exports = function () {
    const app  = express();
    const port = 3000;
    app.get('/', (req, res) => {
        res.sendFile(path.resolve('index.html'));
    });
    app.listen(port, () => {
        console.log(`Example app listening on port ${port}`);
    });
};
```

```js
//test
import { Selector } from 'testcafe';
import server from './server';
fixture`Pressing and holding CTRL while clicking on a button doesn't work`
    .before(() => {
        server();
    })
    .page('http://localhost:3000/');
test('003 | Test Chassis page. Delete Chassis', async t => {
    const deleteBtn = Selector('#btn-delete-chassis');
    await t.expect(deleteBtn.innerText).eql('Delete');
    await t.click(deleteBtn, { modifiers: { ctrl: true } });
    await t.expect(deleteBtn.innerText).eql('Save');
});
```

**Comment by AlexKamaev** [comment]
This behavior is by design. The `click` action does not trigger the `keydown` event, despite the property.
We recommend using the [t.dispatchEvent](https://testcafe.io/documentation/403091/reference/test-api/testcontroller/dispatchevent) method as a workaround:

```JS
test('test', async t => {
    await t.dispatchEvent('a', 'keydown', { ctrlKey: true })
    await t.click('a');
});
```

Please also take a look at the following issue: [https://github.com/DevExpress/testcafe/issues/1839](https://github.com/DevExpress/testcafe/issues/1839)
