### ISSUE TITLE
test.only breaks test/** and fixture-meta usage

### ISSUE THREAD

**Issue by yoavws** [DevExpress/testcafe#6979]
### What is your Scenario?

We are trying to run suite of tests via meta-tags with the use of fixture-meta.
when trying to use a specific folder we found it fails (while other worked as expected)

during investigation we found out that the faulty dir had tests with the test.only notation which **impacted other tests and the whole suite**
that test wasn't part of the execution flow, it's being inside of the directory is enough for breaking the behavior

### What is the Current behavior?

test.only in one file breaks the replay of multiple tests in other files - it override other external CLI/runner settings

### What is the Expected behavior?

the test.only will be followed only if the correspond fixture is executed

### What is your public website URL? (or attach your complete example)

not relevant

### What is your TestCafe test code?

```
testcafe chrome:headless './tests/suite1/**/*.ts' --fixture-meta some-tag=true
or testcafe chrome:headless './tests/suite1/**/*.ts' 
```

in combination of :
```
test.only('test', async t => {
  ///
});
```

### Steps to Reproduce

1.
2.
3.

### TestCafe version

1.18.1 

### Node.js version

16

### Command-line arguments

testcafe chrome:headless './tests/suite1/**/*.ts' --fixture-meta some-tag=true

**Comment by felis2803** [comment]
Hello @yoavws,

Thanks for your report. I reproduced this behavior. We will write to this thread when we have news on fixing this issue.
