### ISSUE TITLE
Upgrading from 1.16.1 to 1.18.x unable to open Chrome when running on CicleCI 14-browser Image

### ISSUE THREAD

**Issue by jpcole** [DevExpress/testcafe#6987]
### What is your Scenario?

After upgrading from Testcafe 1.16.1 to 1.18.1 or 1.18.5 Testcafe cannot open Chrome at start of test when running on CircleCI 14-browsers image.

### What is the Current behavior?

fails on gitlab runner using circleci image

```
Pulling docker image circleci/node:[14](.../-/jobs/2343069921#L14)-browsers ...
Using docker image sha256:50fbc61c614ffb4a8808049bb507042342c6d7a457ec34ce62e37970bf399425 for circleci/node:14-browsers with digest circleci/node@sha256:d2890888d79d27c58df7baca058e5b7f089787847df57ea431c7fef147776307
```

Error trying to startup test:
```
Error: Unable to open the "chrome: --allow-insecure-localhost" browser due to the following error:
Error: connect ECONNREFUSED 127.0.0.1:38240
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
    at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:130:17)
    at BrowserConnection._runBrowser (.../node_modules/testcafe/src/browser/connection/index.ts:214:32)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

### What is the Expected behavior?

no error starting up chrome browser.

### What is your public website URL? (or attach your complete example)

NA

### What is your TestCafe test code?
```
// e2e-tests/testcafe-config-local.js

const createTestCafe = require('testcafe');
async function configureTestcafe() {
  const testcafe = await createTestCafe('localhost', '9003', '9004');

  try {
    const runner = testcafe.createRunner();

    const failedCount = await runner
      .startApp('node server.js', 15000)
      .src('e2e-tests/tests/functional/')
      .browsers('chrome --allow-insecure-localhost')
      .concurrency(3)
      .reporter(['spec', {
        name: 'spec',
        output: 'e2e-tests/test-cases/test-results.txt'
      }])
      .run();

    console.log('Tests failed: ' + failedCount);
    if (failedCount > 0) {
      throw new Error('failed tests so fail job');
    }
  } finally {
    await testcafe.close();
  }
}
configureTestcafe();
```

### Steps to Reproduce

1. load circleci image
2. run node command to run testcafe using the file above

### TestCafe version

1.18.5

### Node.js version

14.18.2

### Command-line arguments

node e2e-tests/testcafe-config-local.js

### Browser name(s) and version(s)

Chrome

### Platform(s) and version(s)

circleci 14-browser image

### Other

There was new logic in the code to check if it is a docker container and we think it might be the cause of the issue.

https://github.com/DevExpress/testcafe/blob/7ec61d876d6c3fe9d019490979ec228ae48861db/src/browser/provider/built-in/dedicated/chrome/index.js#L59

**Comment by miherlosev** [comment]
Hi @jpcole

We changed the Chrome run logic in the docker between mentioned versions. Could you please prepare a public repository with testing on Circle CI so that we can reproduce the issue without any additional setup?

**Comment by jpcole** [comment]
Ok.  I will try to work on that this week to provide a project.   Do you have a recommended way to set this up?   I was going to try to setup a github project using circle ci image to run the e2e test.

**Comment by miherlosev** [comment]
> Do you have a recommended way to set this up?

We have only general recommendations: it should be possible to reproduce the issue without any additional setup.

**Comment by josephgavin** [comment]
I hate seeing these after two years with no useful response from the owner of the repo. This issue just occurred for me and pages like this where someone flags the issue and you fail to provide a fix bog down search results. This just happened to me. Please advise.

**Comment by Bayheck** [comment]
Hello, please take a look at my response here https://github.com/DevExpress/testcafe/issues/8312.
