### ISSUE TITLE
Support processing 'class' syntax

### ISSUE THREAD

**Issue by andrewnmccall** [DevExpress/testcafe#6988]
### What is your Scenario?

I have a webpage that presents the user with options to continue on to a a following screen. On click of an option, a javascript file uses location.href = [url] to redirect the user to a new location. Normally, scripts are altered by Hammerhead and these expressions are replaced with code that keeps the browser in the localhost proxy session (I'm not sure if this is the proper terminology for what is happening here). This one script is loaded as is without any conversions nor the intro comment of "/*hammerhead|script|start*/"; however, I have a class declaration in the file with public class field declarations. If I remove these, the file is converted by hammerhead and the location.href expression is replaced with a function. Without this conversion, the redirect step causes the test to go outside of the localhost proxy, all cookies are lost, and testcafe loses control of the browser.

### What is the Current behavior?

Websites under test that have javascript files that use public class field declarations are not converted by hammerhead, resulting in redirects going out of the localhost proxy.

### What is the Expected behavior?

Files with public class field declarations are converted by hammerhead

### What is your public website URL? (or attach your complete example)

[test.zip](https://github.com/DevExpress/testcafe/files/8500963/test.zip)

### What is your TestCafe test code?

import { Selector, t } from 'testcafe';

fixture `Fixture`
.page('http://127.0.0.1:8080/index.html');
// .page('https://google.com/');

test('test', async t => {
	await t.click(Selector('button'));
	//This step is not even reached because the redirect takes the browser out of testcafe's proxy
	await t.expect(`#display`).contains('display=CARRIED');
});

### Your complete test report

 Running tests in:
 - Chrome 100.0.4896.88 / Windows 10

 Fixture

### Steps to Reproduce

1. extract the zip file to a directory and run an http server in the root of that directory to 127.0.0.1:8080
2. run npm install and run the test script: bash ./node_modules/.bin/testcafe --hostname=localhost chrome test.js
3. Note that the test does not get to the assertion after the redirect.

### TestCafe version

1.18.5

### Node.js version

v17.9.0

### Command-line arguments

 --hostname=localhost chrome test.js

### Browser name(s) and version(s)

chrome 100.0.4896.88

### Platform(s) and version(s)

windows 10

**Comment by miherlosev** [comment]
Hi @andrewnmccall

Thank you for the example. At present, the testing web application whose code contains the `class` syntax can be broken.
We will consider supporting this capability in the future.

**Comment by Artem-Babich** [comment]
This issue is not reproducible in TestCafe v2.2.0. Feel free to reopen this thread if you encounter this issue in v2.2.0 or later.
