### ISSUE TITLE
Error reading .testcaferc.js config file

### ISSUE THREAD

**Issue by lyqht** [DevExpress/testcafe#6989]
### What is your Scenario?

I would like to use the `userVariables` as a means to access my environment variables.

.testcaferc.js

```
import toggles from "../src/config/toggles";
module.exports = {
  userVariables: {
    featureXEnabled: toggles.isFeatureXEnabled()
  }
}
```

toggles file
```
class Toggles {
  public get featureXEnabled(): string {
    return get(window, "__ENV.REACT_APP_INTERVENTIONS_TOGGLE", "off");
  }
}

export default new Toggles();

```

### What is the Current behavior?

```
> NODE_ENV=test TZ='Asia/Singapore' BASE_URL=localhost:3000 testcafe chrome ./e2e/cohort.test.ts --dev --disable-page-caching --config-file ./e2e/.testcaferc.js

An error has occurred while reading the "/Users/lyqht/proj/e2e/.testcaferc.js" configuration file.
```

Testcafe ignores this error and proceeds running the tests which will fail.

```
  1) TypeError: Cannot read property 'featureX' of null
```

### What is the Expected behavior?

Be able to read the env file

### TestCafe version

1.18.5

**Comment by miherlosev** [comment]
Hi @lyqht,

The `.testcaferc.js` file (and its dependencies) should be written using the `CommonJS` syntax.

```js
const toggles = require("../src/config/toggles");

module.exports = {
  userVariables: {
    featureXEnabled: toggles.isFeatureXEnabled()
  }
}
```

**Comment by qualityshepherd** [comment]
Then why do the docs use `import`?

<img width="361" alt="image" src="https://user-images.githubusercontent.com/3298906/178337390-dcb644d3-a241-4a6a-af56-b49fdeb45bdc.png">

**Comment by Aleksey28** [comment]
In this example, the `CommonJS` syntax is used in the upper part of the documentation on the configuration: https://testcafe.io/documentation/402638/reference/configuration-file#javascript. But yes, there is a mistake in the [`Test Hooks`](https://testcafe.io/documentation/402638/reference/configuration-file#test-hooks) part. We'll fix it.

**Comment by titerman** [comment]
The documentation has been updated. It may take a while for the website to reflect these changes.

**Comment by Victorgabarullo** [comment]
Hi! I'm trying to do it but I got the same issue. I'm using the CJS form: 

![imagen](https://user-images.githubusercontent.com/45743656/228665700-a141c784-9a44-4137-9409-1bca00c837a5.png)

But i got the same result

![imagen](https://user-images.githubusercontent.com/45743656/228665794-71444c89-b492-4a1e-a728-b78645aa29e0.png)

This is the module: 

![imagen](https://user-images.githubusercontent.com/45743656/228665964-0a9dda47-055d-4a8c-9ca1-018e7057ae6a.png)

I also tried to change all files to JS but it's the same result.

Could anyone help me out with this please?

**Comment by Aleksey28** [comment]
Hi @Victorgabarullo,

Utils scripts for the config file should be created with the same rules as the config file. The config file supports only CommonJS syntax. It means that you can't use import/export from ESM and you can't use TypeScript.
