### ISSUE TITLE
Testcafe incorrectly detects svg as hidden

### ISSUE THREAD

**Issue by Makavelic** [DevExpress/testcafe#6998]
### What is your Scenario?

I have a svg with a parent div that has a height of 0. The SVG is visible and I want to click it.

### What is the Current behavior?

Testcafe doesn't let me click the SVG because it thinks it's hidden:
**The element that matches the specified selector is not visible.**

### What is the Expected behavior?

I should be able to click the SVG

### What is your public website URL? (or attach your complete example)

[TestcafeSampleProjectBug.zip](https://github.com/DevExpress/testcafe/files/8543302/TestcafeSampleProjectBug.zip)

Sample html:
```
<html>
    <body>
		<div style="height: 0">
			<svg height="100" width="100">
				<circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />
			</svg>
		</div>
    </body>
</html>
```

### What is your TestCafe test code?

```
import { t } from "testcafe";

fixture("bugTest").beforeEach(async t => {
	await t.navigateTo(`file://${__dirname}/testcafeBug.html`);
});

test("bug", async t => {
	await t.click("svg");
});
```

### Screenshots
**SVG with hidden parent**:
![visibleSvg](https://user-images.githubusercontent.com/9947758/164775460-768c82c7-a23b-499e-8e7e-1275def0a1f3.png)

### Steps to Reproduce

Steps
1. Extract project
2. Run yarn or npm to build project
3. Launch test in terminal: `testcafe chrome tests`

### TestCafe version

1.18.6

### Node.js version

16.13.0

### Command-line arguments

testcafe chrome tests

### Browser name(s) and version(s)

Chrome 100

### Platform(s) and version(s)

Windows 10

### Other

This looks like a regression from #3495 

src/client/core/utils/shared/visibility.ts
```
if (adapter.dom.isSVGElement(el)) {
        if (adapter.style.get(el, 'visibility') === 'hidden' || adapter.style.get(el, 'display') === 'none')
            return false;

        const parent = adapter.dom.findParent(el);

        return parent ? isElementVisible(parent) : true;
}
```

I suspect the problem is that testcafe checks visibility by looking at the height property. It is possible for a parent element to be hidden while the svg is visible and interactable.

Source:
https://github.com/DevExpress/testcafe/blob/master/src/client/core/utils/shared/visibility.ts#L12
```
if (elementRectangle.width === 0 || elementRectangle.height === 0)
            return false;
```

**Comment by miherlosev** [comment]
Hi @Makavelic,

Thank you for the shared example. I've reproduced the issue.

**Comment by Aleksey28** [comment]
Hi @Makavelic

Any personal estimate may be misleading, so I cannot currently tell you the precise date. Usually, we publish a new release approximately once every two weeks.
