### ISSUE TITLE
Cannot run example test after installing testcafe

### ISSUE THREAD

**Issue by IgnatovDan** [DevExpress/testcafe#700]
The following error occurs:
c:\Projects>runtest.cmd

c:\Projects>"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node.exe" "node_modules\testcafe\bin\testcafe" ie C:\Projects\example.test.js
module.js:327
    throw err;
    ^

Error: Cannot find module 'c:\Projects\node_modules\testcafe\bin\testcafe'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3

I have installed testcafe in this way (Node v5.4.1):
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\npm.cmd" install testcafe

and run a test in this way:
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node.exe" "node_modules\testcafe\bin\testcafe" ie C:\Projects\example.test.js

an received the 'Cannot find module' error.
The same error occurs if I specify the "node_modules\testcafe" module and if I have installed testcafe globally ("-g" option).

Note, that the same test run successfully with the '0.0.22-alpha' version:

"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\npm.cmd" install testcafe@0.0.22-alpha

Also, I have successfully started 'keystonejs' on the same environments but cannot start 'testcafe'.
Would you please clarify how to install testcafe and run a test on Win10?

**Comment by AndreyBelym** [comment]
Hi Dan, we changed the name of the executable file in version `0.0.24-alpha`, now it is called `testcafe.js`. So likely you need to update your `runtest.cmd` and change the way the `testcafe` is started:

"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node.exe" "node_modules\testcafe\bin\testcafe**.js**" ie C:\Projects\example.test.js

**Comment by AndreyBelym** [comment]
Oh, also since you didn't specify the version in `npm install testcafe`, it has installed `testcafe@15.1.3`. You must explicitly specify the `alpha` tag while we are in alpha stage:
```
npm install testcafe@alpha
```

**Comment by inikulin** [comment]
Also, it's a bad practice to run node bins this way: you either install it globally or install it locally and run via npm scripts or programmatical API

**Comment by IgnatovDan** [comment]
I hope you will update the https://github.com/DevExpress/testcafe/blob/master/docs/articles/documentation/getting-started/index.md topic:
> Make sure that Node.js and npm are installed on your computer, then run a single command:
> npm install -g testcafe

Such code and docs contradiction introduces unnecessary difficulties to investigation process that can take a long time. All the 'bin', 'node_modules\testcafe' and other approaches are caused by that text in your docs.

**Comment by inikulin** [comment]
Not sure I understand how it's related, since you have instructions about how to correctly run testcafe in the same doc.

**Comment by IgnatovDan** [comment]
That doc specify this command line to install testcafe:
`npm install testcafe`
and I have encountered difficulties when running scripts from that doc after I have installed testcafe with this command line.

AndreyBelym committed that that command line should not be used and suggested another command line:
`npm install testcafe@alpha`
With this command line I have successfully finished the first test from that topic.

So, it's obvious that the command line and test scripts are related and should be consistent but currently they are not and it creates difficulties at the very first stages.

**Comment by inikulin** [comment]
> That doc specify this command line to install testcafe:
npm install testcafe

No, it's not:

> Make sure that Node.js and npm are installed on your computer, then run a single command:
npm install -g testcafe
For more information, see Installing TestCafe.

There is a `-g` flag there.


> AndreyBelym committed that that command line should not be used and suggested another command line:
npm install testcafe@alpha
With this command line I have successfully finished the first test from that topic.

Docs are obviously designed for the release version. Release not happened yet, so meanwhile it's a requirement to  install testcafe via `npm install testcafe@alpha` command.

**Comment by IgnatovDan** [comment]
I apologize for the lost '-g', it was a typo.
And, I understand that there are the 'released' and 'dev' versions, but...

I have tried the 'npm install -g testcafe' command on a clear VM with the following results:
```
c:\Projects>npm install -g testcafe
npm WARN deprecated tough-cookie@1.1.0: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'

> ws@0.4.32 install C:\Users\Admin\AppData\Roaming\npm\node_modules\testcafe\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\Users\Admin\AppData\Roaming\npm\node_modules\testcafe\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws>if not defined npm_config_node_gyp (node "C:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
testcafe@15.1.3 C:\Users\Admin\AppData\Roaming\npm\node_modules\testcafe
├── node-int64@0.3.0
├── async@0.2.6
├── buffer-crc32@0.2.3
├── webauth@0.1.1
├── mime@1.2.11
├── revalidator@0.1.5
├── node-uuid@1.3.3
├── iconv-lite@0.4.11
├── tough-cookie@1.1.0
├── ejs@0.8.4
├── useragent@2.1.7 (lru-cache@2.2.4)
├── markdown@0.5.0 (nopt@2.1.2)
├── moment@1.7.0
├── uglify-js@1.2.6
├── whacko@0.17.4 (lodash@2.4.2, parse5@1.5.1, CSSselect@0.4.1, domutils@1.5.1)
├── node-zip@1.1.1 (jszip@2.5.0)
├── express@3.2.5 (methods@0.0.1, fresh@0.1.0, range-parser@0.0.4, cookie-signature@1.0.1, buffer-crc32@0.2.1, commander@0.6.1, cookie@0.1.0, mkdirp@0.3.4, send@0.1.0, debug@2.2.0, connect@2.7.10)
└── socket.io@0.9.13 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3, socket.io-client@0.9.11)
```

Then, I started the first test from the GettingStarted topic:
```
fixture `Getting Started`
    .page('http://testcafe.devexpress.com/example');

test('My first test', async t => {
    // Test code
});
```

and got the following results:
```
c:\Projects>testcafe ie test1.js
'testcafe' is not recognized as an internal or external command,
operable program or batch file.
```

I have not encountered this difficulty when using the 'npm install -g testcafe@alpha' command and test was completed with the following results:
```
c:\Projects>testcafe ie test1.js
 Running tests in:
 - IE 11.0.0 / Windows 10 0.0.0

 Getting Started
 √ My first test


 1 passed (2s)

```
For more details see the attached file with results of the same steps: 
[install_testcafe_alpha.txt](https://github.com/DevExpress/testcafe/files/403212/install_testcafe_alpha.txt)

I hope this information will help you investigate this newby' difficulty and avoid it even at this development stage when release is not published yet because this repository is marked as public.

**Comment by inikulin** [comment]
This happens because current versions which installs by default is an old version that doesn't support new API. Once new version will be released, we will switch release tag from `alpha` to `stable` and new version will be available by this install command.
