### ISSUE TITLE
Provide keyboard shortcut keys for Unlock Page, Resume and Next Action when using t.debug()

### ISSUE THREAD

**Issue by jiteshsojitra** [DevExpress/testcafe#7003]
### What is your Scenario?

We are heavily using t.debug() and need to unlock page/resume and take actions. Everytime execution stops at develop, we have to use must move mouse over particular action. Can we have keyboard shortcut key support for the same?

### What are you suggesting?

Shortcut keys?
Unlock Page - uu
Resume - rr
Next Action - nn

**Comment by miherlosev** [comment]
Hi @jiteshsojitra 

Thank you for pointing out this enhancement. At present, we are focusing on our [roadmap](https://testcafe.io/402949/roadmap). If this enhancement is very important for you, the PR is greatly appreciated.

**Comment by AlexKamaev** [comment]
We decided to close this issue since it is not popular among TestCafe users. If you still need this issue, you can create your own PR - we'll review it.
