### ISSUE TITLE
Upload Docker images to AWS gallery aw

### ISSUE THREAD

**Issue by kaestlej-tng** [DevExpress/testcafe#7008]
### What is your Scenario?

We're using AWS CodePipeline as our CI/CD environment and want to run our testcafe tests inside this pipeline. Thus, we want to use the testcafe/testcafe docker image for it but we keep running in the Docker pull limits. 

### What are you suggesting?

If the testcafe docker images would also be available at the public ECR from AWS (https://gallery.ecr.aws), then we could pull inside the AWS infrastructure without rate limits. 

This would also help other testcafe users who are inside the AWS infrastructure.

### What alternatives have you considered?

Alternatives are 
(1) Reuploading the docker images to a private ECR
(2) Having a paid docker account

**Comment by miherlosev** [comment]
Hi @kaestlej-tng 

Thank you for pointing out this enhancement.
