### ISSUE TITLE
Test from 'Performing Actions on the Page' section fails

### ISSUE THREAD

**Issue by IgnatovDan** [DevExpress/testcafe#701]
I have successfully started test from the 'Creating a Test' section at https://github.com/DevExpress/testcafe/blob/master/docs/articles/documentation/getting-started/index.md

```
fixture `Getting Started`
    .page('http://testcafe.devexpress.com/example');

test('My first test', async t => {
    // Test code
});

```
But the test from the 'Performing Actions on the Page' section:
```
fixture `Getting Started`
    .page('http://testcafe.devexpress.com/example');

test('My first test', async t => {
    await t
        .typeText('#developer-name', 'John Smith')
        .click('#submit-button');
});
```

failed with the following result:
c:\Projects>testcafe ie C:\Projects\test1_2_PerformAction.js
 Running tests in:
 - IE 11.0.0 / Windows 10 0.0.0

 Getting Started
 × My first test

   1) The specified selector does not match any element in the DOM tree.

      Browser: IE 11.0.0 / Windows 10 0.0.0

         1 |fixture `Getting Started`
         2 |    .page('http://testcafe.devexpress.com/example');
         3 |
         4 |test('My first test', async t => {
         5 |    await t
       > 6 |        .typeText('#developer-name', 'John Smith')
         7 |        .click('#submit-button');
         8 |});

         at <anonymous> (C:\Projects\test1_2_PerformAction.js:6:9)
         at <anonymous> (C:\Projects\test1_2_PerformAction.js:8:42)

 1/1 failed (12s)

How to manage it?
I am using nodejs-v4-4-7 and this testcafe: 'npm install -g testcafe@alpha'

**Comment by AndreyBelym** [comment]
The test from the docs must be used with new version of the example page. It's not available online yet.

You need to check and replace selectors you are using:
```
fixture `Getting Started`
    .page('http://testcafe.devexpress.com/example');

test('My first test', async t => {
    await t
        .typeText('#Developer_Name', 'John Smith') // see: #Developer_Name
        .click('#submit-button');
});
```

**Comment by inikulin** [comment]
BTW I thought we'll host new example page on GH \cc @VasilyStrelyaev

**Comment by IgnatovDan** [comment]
Thank you. I have updated my test and it passed.

I hope you will update the following text in the https://github.com/DevExpress/testcafe/blob/master/docs/articles/documentation/getting-started/index.md topic:

> .typeText('#developer-name', 'John Smith')

And, I hope you will check each other script in this topic to be sure that noone will encounter difficulties at this very first stage when reviewing capabilities of your product.

**Comment by IgnatovDan** [comment]
Anyway, I have reviewed your next test with the ' await getElementById' command and it fails with the "getElementById is not defined" error:

C:\Users\Admin>testcafe ie C:\Projects\test1.test.js
 Running tests in:
 - IE 11.0.0 / Windows 10 0.0.0

 Getting Started
 × My first test

   1) ReferenceError: getElementById is not defined

      Browser: IE 11.0.0 / Windows 10 0.0.0

          5 |    await t
          6 |        .typeText('#Developer_Name', 'John Smith')
          7 |        .click('#submit-button');
          8 |
          9 |    // Use the Selector function to get access to the article header
       > 10 |    const articleHeader = await getElementById('article-header');
         11 |
         12 |    // Obtain the text of the article header
         13 |    const headerText = articleHeader.innerText;
         14 |});

         at <anonymous> (C:\Projects\test1.test.js:10:33)

 1/1 failed (5s)

Would you please clarify how to manage this error?

**Comment by inikulin** [comment]
@IgnatovDan Please, provide full source code of the test.

**Comment by IgnatovDan** [comment]
I lost the following lines in my test:
```
import { Selector } from 'testcafe';

// Declare the parameterized Selector function
// to get access to a DOM element identified by the `id` attribute
const getElementById = Selector(id => document.querySelector(`#${id}`));

```
With this code test fails with the "Cannot read property 'innerText' of null" message:

c:\Projects>testcafe ie C:\Projects\test1.js
 Running tests in:
 - IE 11.0.0 / Windows 10 0.0.0

 Getting Started
 × My first test

   1) TypeError: Cannot read property 'innerText' of null

      Browser: IE 11.0.0 / Windows 10 0.0.0

         14 |
         15 |    // Use the Selector function to get access to the article header
         16 |    const articleHeader = await getElementById('article-header');
         17 |
         18 |    // Obtain the text of the article header
       > 19 |    const headerText = articleHeader.innerText;
         20 |});

         at <anonymous> (C:\Projects\test1.js:19:24)



 1/1 failed (15s)

**Comment by inikulin** [comment]
That's correct, this is happens because this part of the test was designed for new example page. We've already changed test code in on of PRs, so it reference new example page not the old one.
