### ISSUE TITLE
Something slows down page loading

### ISSUE THREAD

**Issue by felis2803** [DevExpress/testcafe#7013]
### What is your Scenario?

Test:
```js
import { Selector } from 'testcafe';

fixture `New Fixture`
    .page `https://www.underarmour.com/en-us/p/tops/mens_ua_tech_long_sleeve/1328496.html?dwvar_1328496_color=012`;
    
test(`New Test`, async t => {
    await t
        .click('#welcome-mat-modal [alt="US"][title="Country"]')    
        .click('#emailPopUpModal .g-email-pop-modal-close.g-modal-close-button')
        .click(Selector('main a').withText('Shop Jordan’s Official Kits'));
});
```

Run it: `testcafe chrome test.js -e`

### What is the Current behavior?

The page loads very slowly.

### What is the Expected behavior?

The page should not load much longer than without TestCafe.

### What is your public website URL? (or attach your complete example)

https://www.underarmour.com/en-us/p/tops/mens_ua_tech_long_sleeve/1328496.html?dwvar_1328496_color=012

### What is your TestCafe test code?
```js
import { Selector } from 'testcafe';

fixture `New Fixture`
    .page `https://www.underarmour.com/en-us/p/tops/mens_ua_tech_long_sleeve/1328496.html?dwvar_1328496_color=012`;
    
test(`New Test`, async t => {
    await t
        .click('#welcome-mat-modal [alt="US"][title="Country"]')    
        .click('#emailPopUpModal .g-email-pop-modal-close.g-modal-close-button')
        .click(Selector('main a').withText('Shop Jordan’s Official Kits'));
});
```

### Steps to Reproduce

1. Open [this](https://www.underarmour.com/en-us/p/tops/mens_ua_tech_long_sleeve/1328496.html?dwvar_1328496_color=012) page without TestCafe. It loads without noticeable delays.
2. Try to perform some actions on the page. It also doesn't freeze.
3. After that, try running the above test and observe the page load speed. Almost any action will occur with large delays.

### TestCafe version

1.18.6

### Node.js version

16.14.2

### Command-line arguments

testcafe chrome test.js -e

### Browser name(s) and version(s)

chrome@101.0.4951.54

### Platform(s) and version(s)

Windows 10

### Related
https://supportcenter.devexpress.com/internal/ticket/details/T1086784

**Comment by AlexKamaev** [comment]
I researched the described behavior. The page runs slowly because of a lot of scripts injected on the page (more than 60 different scripts). TestCafe uses web-proxy. This means that every script is processed by that proxy and this increases the test time.
We are aware of this problem and we are working on it.
