### ISSUE TITLE
Session cookie lifetime doesn't get refreshed when its lifetime is extended

### ISSUE THREAD

**Issue by michaelperrin** [DevExpress/testcafe#7015]
### What is your Scenario?

**Given** a page sets a session cookie with a 3-second lifetime (with `Set-Cookie` HTTP header)
**And** an other page reading the session to display whether session data is available or not
**And** that this other page extends the session cookie lifetime by 3 more seconds
**When** a user loads the page that sets the cookie session
**And** the user navigates the page that reads the session
**And** the user reloads that page less than 3 seconds after
**Then** the session should still be active

### What is the Current behavior?

**In a browser:** as far as the page gets refreshed less than 3 seconds later, the session is still active
**In TestCafe:** the session gets inactive after 3 seconds _after the page was first loaded_, no matter if the page has been refreshed multiple times (which extends the cookie lifetime)

### What is the Expected behavior?

The session should still be active as far as the page is reloaded no more than 3 seconds after.

### What is your public website URL? (or attach your complete example)

I made a complete repository with a simple test that allows to reproduce the issue with an Node / Express app:
https://github.com/michaelperrin/testcafe-cookie-issue-test

PHP alternative available at https://github.com/michaelperrin/testcafe-cookie-issue-test/tree/test-with-php-session

### What is your TestCafe test code?

This is part of the [the repository](https://github.com/michaelperrin/testcafe-cookie-issue-test) I created to reproduce the issue:

```javascript
import { Selector } from 'testcafe';

fixture`Getting Started`
    .page`127.0.0.1:3000`;

test('Session does not expire after 3 seconds if page has been reloaded', async t => {
    // Go to second page and check that session is active
    await t.expect(Selector('#text').innerText).eql('Starting session!');

    // Reload page after 2 seconds and check that session is still active
    await t
        .wait(2000) // 2+ seconds from session creation on first page
        .click('#reload-page')
        .expect(Selector('#text').innerText).eql('Has session');

    // Reload page after 2 seconds and check that session is still active
    // THIS FAILS BUT SHOULD NOT
    await t
        .wait(2000)
        .click('#reload-page')
        .expect(Selector('#text').innerText).eql('Has session');

    await t
        .wait(2000)
        .click('#reload-page')
        .expect(Selector('#text').innerText).eql('Has session');
});

```

### Your complete test report

```
✓ Session expires after 3 seconds
 ✖ Session does not expire after 3 seconds if page has been reloaded

   1) AssertionError: expected 'Starting session!' to deeply equal 'Has session'
      
      + expected - actual
      
      -Starting session!
      +Has session
      

      Browser: Chrome 101.0.4951.54 / macOS 10.15.7

         30 |        .expect(Selector('#text').innerText).eql('Has session');
         31 |
         32 |    await t
         33 |        .wait(2000)
         34 |        .click('#reload-page')
       > 35 |        .expect(Selector('#text').innerText).eql('Has session');
         36 |});
         37 |

         at <anonymous> (/Users/michaelperrin/Temp/testcafe-test/test2.js:35:46)
         at asyncGeneratorStep (/Users/michaelperrin/Temp/testcafe-test/test2.js:1:228)
         at _next (/Users/michaelperrin/Temp/testcafe-test/test2.js:1:566)



 1/2 failed (14s)
```

### Steps to Reproduce

1. Start a session with a cookie that has a 3-second lifetime
2. Load a page that makes use of the session and refreshes the 3-second lifetime
3. Wait for 2 seconds
4. Reload page
5. Wait for 2 seconds
6. Reload page

Result: session should still be active

### TestCafe version

1.18.6

### Node.js version

v16.13.2

### Command-line arguments

testcafe chrome test.js

### Browser name(s) and version(s)

Chrome 101, Firefox 100

### Platform(s) and version(s)

MacOS 12.3.1

**Comment by miherlosev** [comment]
Hi @michaelperrin 

Thank for the shared example. I've reproduced the issue.
