### ISSUE TITLE
TestCafe requires screen capture permission on MacOS when disableScreenshots is true

### ISSUE THREAD

**Issue by vergilfromadyen** [DevExpress/testcafe#7019]
### What is your Scenario?

Some environments cannot easily provide screen capture permissions to TestCafe. An example would be org-managed MacOS (since Monterey) instances configured in ways that would make it necessary for TestCafe to be codesigned and installed on a predictable path. This is of course possible but difficult to manage if there are many versions of TestCafe used across projects on the same machine.

Disabling screen capturing and video recording seems like an obvious way to work around the permission check while retaining access to the core features of TestCafe.

### What is the Current behavior?

Setting `disableScreenshots: true` and keeping `video` options disabled still requires screen capture permissions. In the cases where it's not possible to grant screen capture permissions, TestCafe is virtually unusable.

### What is the Expected behavior?

Setting `disableScreenshots: true` disables the check for screen capture permissions on MacOS

### What is your public website URL? (or attach your complete example)

-

### What is your TestCafe test code?

```js
fixture`Open anything`.beforeEach(async (t) => {
    await t.navigateTo('https://testcafe.io/');
});
test.only('Empty test', async (t) => {
    await t.expect(true).eql(true);
});
```

### Your complete configuration file
```json
{
  "skipJsErrors": true,
  "disableScreenshots": true,
  "compilerOptions": {
    "typescript": {
      "configPath": "tsconfig-testcafe.json"
    }
  }
}
```

### Steps to Reproduce

1. Run a MacOS instance
2. Create an empty test suite
3. Run TestCafe with `disableScreenshots: true`

### TestCafe version

1.8.4

### Command-line arguments

testcafe chrome test.js

**Comment by miherlosev** [comment]
Hi @vergilfromadyen,

Thank for pointing this out. We will research ways to improve setting permissions on macOS.

**Comment by vergilfromadyen** [comment]
Hi @miherlosev, I already opened a #7028 PR but I couldn't set up my machine in a way that tests would run correctly, hopefully this way you don't need any research :) but let me know if you need more help with this.

**Comment by AndreyBelym** [comment]
Thank you for your feedback. Unfortunately, avoiding the Screen Capture permission only won't help you much - you still have to deal with the Automation permission when TestCafe starts a browser. I've shared more details in a comment to your PR: https://github.com/DevExpress/testcafe/pull/7028#issuecomment-1130559567.

Also, this issue is actually a duplicate: https://github.com/DevExpress/testcafe/issues/6789. Let's continue our discussion there.
