### ISSUE TITLE
Quarantine mode not stopping after getting a successful run even after setting successThreshold

### ISSUE THREAD

**Issue by MukulCode** [DevExpress/testcafe#7023]
### What is your Scenario?

We have a very simple test case which generates a random number 0/1. 
It will fail if the number generated is 0 and pass when the number generated is 1.

I am using quarantine mode to run the test case and while calling run I am passing { quarantineMode: { successThreshold: 1, attemptLimit: 3 } }.

### What is the Current behavior?

What I am able to see is:
1. Test Case got failed -> Test case got passed in retry(No errors were there in logs) ->  Retry again happened(Test case passed) -> End Result: Test case failed
2. Test Case got failed -> Test case got failed in retry(No errors were there in logs) ->  Retry again happened(Test case passed) -> End Result: Test case failed
3. Test Case got failed -> Test case got passed in retry(No errors were there in logs) ->  Retry again happened(Test case failed) -> End Result: Test case failed

No matter what happens in second or third retry, the end result is "Test case failed" only.

### What is the Expected behavior?

Expectation: If the test cases fails in first attempt -> Retry will happen -> If the test case passes -> It should stop since successThreshold is 1 -> End result should be passed.

### What is your public website URL? (or attach your complete example)

// everything already added in other blocks. This is not needed.

### What is your TestCafe test code?

```
fixture `My fixture`;

test('Test', async t => {
     let random = getRandomNumber(2); //It will generate a random number. It will be 0 or 1
  console.log(random);
  assert(random, "hello the random number was 0 and due to which this test case got failed"); // Test Case will fail if the number is 0
});
```

### Your complete configuration file

`{
  "assertionTimeout": 10000,
  "selectorTimeout": 10000,
  "pageLoadTimeout": 10000,
  "src": [
    "xxx/xxx/xxxx/**/*.ts",
  ],
  "compilerOptions": {
    "typescript":   {
      "customCompilerModulePath": "../../../typescript",
      "configPath": "tsconfig.json",
      "experimentalDecorators": true
    }
    },
  "reporter": [
    {
      "name": "spec"
    },
    {
      "name": "tim-json",
      "output": "xx/xx-xx-x/xx/report.tim.json",
      "options": {
        "addAttachments": false
       }
    },
    {
      "name": "html",
      "output": "xx/xx-xx-xx/xx.html"
    }
  ],
  "screenshots": {
    "path": "xx/xx-xx-x/web/screenshots",
    "takeOnFails": true,
    "pathPattern": "${DATE}_${TIME}/${FIXTURE}/${TEST}/${RUN_ID}/${TEST_ID}/${FILE_INDEX}.png"
  },
  "skipJsErrors": true,
  "debugOnFail": false
}
`

### Steps to Reproduce

1. Write any test case and generate a random number 0/1
2. Make it fail when the number is 0 and make it pass when the number is 1
3. Run with quarantine mode and observe the case when the random number is 0 for the first retry

### TestCafe version

1.15.1(Same issue on the latest version as well)

### Node.js version

v17.0.1

### Command-line arguments

node testname.js

### Output

```
Executing -----------------SampleTestCase-----------------

0
2022-05-17 16:21:22,863 ERROR [TestCafeTest] Testcase failed
2022-05-17 16:21:22,864 ERROR [TestCafeTest] {"generatedMessage":false,"name":"AssertionError [ERR_ASSERTION]","code":"ERR_ASSERTION","actual":0,"expected":true,"operator":"=="}
2022-05-17 16:21:33,653 INFO [Manager] Ending the test case

Executing -----------------SampleTestCase-----------------

1
2022-05-17 16:21:43,644 INFO [Manager] Ending the test case

Executing -----------------SampleTestCase-----------------

0
2022-05-17 16:21:46,555 ERROR [TestCafeTest] Testcase failed
2022-05-17 16:21:46,555 ERROR [TestCafeTest] {"generatedMessage":false,"name":"AssertionError [ERR_ASSERTION]","code":"ERR_ASSERTION","actual":0,"expected":true,"operator":"=="}
2022-05-17 16:21:54,220 INFO [Manager] Ending the test case

 ✖ SampleTestCase (screenshots: aaa/xxx/xxx/xxx/xxx/SampleTestCase)

   1) AssertionError [ERR_ASSERTION]: hello the random number was 0 and due to which this test case got failed

      Browser: Chrome 101.0.4951.64 / macOS 10.15.7
      Screenshot: "XXXX/xx/xxx/xxx/SampleTestCase.jpg"



 1/1 failed (36s)
2022-05-17 16:21:57,054 INFO [TestDriver] ********* Tests finished *********
2022-05-17 16:21:57,054 INFO [TestDriver] Number of cases failed 1

```

**Comment by MukulCode** [comment]
Hii Team !!
Do we have any update on this scenario please :)

**Comment by MukulCode** [comment]
Update:

I have tried to use 
```
"quarantineMode": {
        "successThreshold": 1,
         "attemptLimit": 3
    }
```
in my .testcaferc.json file as well.

I can see that quarantine mode is running since the test case is getting executed 3 times but the test case is not passing when second/third attempt passes.
If the test case fails for the first time and passes the next 2 times, still the final result is "Test case failed".

**Comment by MukulCode** [comment]
Same results on the latest version as well

**Comment by MukulCode** [comment]
adding another detail: 
I have tried to change the reporters as well but getting the same error. (Using the latest version of Testcafe)

**Comment by MukulCode** [comment]
Hii Team !!
Can we have a look at this issue please. I have updated the issue and tried with the latest version as well.
Thanks for help :)

**Comment by AlexKamaev** [comment]
I did not manage to reproduce the issue. I used the following example:
```JS
fixture `fixture`
    .page `http://example.com`;

let attemptNumber = 0;

test(`test`, async t => {
    attemptNumber++;

    const value = Math.round(Math.random());

    console.log(attemptNumber, value);

    await t.expect(value).eql(1);
});

```
I executed the following command: `npx testcafe chrome test.js -q attemptLimit=3,successThreshold=1`.
These were the results:


```
 fixture
1 0
2 1
 √ test (unstable)
```
```
1 0
2 0
3 1
 √ test (unstable)

```

Please use my example to reproduce the issue and share your results with us.
