### ISSUE TITLE
We need a contribution guide, issue and bug report templates

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#703]

**Comment by VasilyStrelyaev** [comment]
So, I guess we first need to figure out the contribution rules.

And what are issue and bug report templates? I've seen a kind of check lists: 

> - [ ] I haven't found info in the docs
> - [ ] I've tried it on Linux
> - [ ] I've tried it on the latest version

Do you mean these things?

**Comment by VasilyStrelyaev** [comment]
a monday ping, sir

**Comment by inikulin** [comment]
@VasilyStrelyaev 

Contribution rules:

1. First create an issue (if there is no issue already for the given bug/functionality).  It may be functionality that unlikely will be landed or bug fix require some bikeshedding, so to avoid doing job that will not be used it's a good idea to discuss functionality and bug details with core team before submitting the PR.
2. Fork testcafe and create a branch named against the issue number, e.g. `gh852`, `gh853`
3. Commit your changes into the branch
4. Bug fixes should have regression tests added into the appropriate sections (search for `Regression` via code). New functionality should be tested as well
5. Fetch upstream changes and rebase your branch onto `master`
6. Run tests: `gulp test-server`, `gulp test-functional-local`, `gulp test-client` before submitting a PR and ensure that everything works properly
7. Push changes to your fork
8. Submit a PR. PR name should describe what was done in pull request and contain `closes` directive with appropriate issue number. Documentation PRs should have `[docs]` prefix in their title.
9. Use separate PRs for documentation and functionality

GitHub supports issue templates: https://help.github.com/articles/creating-an-issue-template-for-your-repository/

Required information for the bug report:
1. Operating system
2. testcafe version
3. node version
4. Test code
5. Tested page URL
6. Expected behavior
7. Actual behavior
