### ISSUE TITLE
Mocks added in before are preserved between quarantine runs

### ISSUE THREAD

**Issue by andrzej-woof** [DevExpress/testcafe#7030]
### What is your Scenario?

I'm using testcafe runner API and I'm adding request mock in `before`

### What is the Current behavior?

If test fails and quarantine mode is enabled next quarantine attempts use the initial request mock

### What is the Expected behavior?

I'd expect mocks to be cleared between quarantine attempts

### What is your public website URL? (or attach your complete example)

n/a

### What is your TestCafe test code?

`index.js`

```js
const createTestCafe = require('testcafe');

let runNumber = 0;

const config = {
    hooks: {
        test: {
            before: async (browser) => {
                const { RequestMock } = require('testcafe');
                const staticMock = RequestMock()
                    .onRequestTo('http://getrunnumber.invalid/static')
                    .respond(`<html><body><div id="runNumberStatic">${runNumber}</div></body></html>`, 200);
                const dynamicMock = RequestMock()
                    .onRequestTo(`http://getrunnumber.invalid/${runNumber}`)
                    .respond(`<html><body><div id="runNumber">${runNumber}</div></body></html>`, 200);
                runNumber++;
                await browser.addRequestHooks([staticMock, dynamicMock]);
            }
        }
    }  
}

new Promise(async (resolve) => {
    const testcafe = await createTestCafe(config);
    const runner = testcafe.createRunner();
    await runner.src('test.js').browsers('chrome').run({ quarantineMode: true });
    resolve();
});
```

`test.js`
```js
const { Selector } = require('testcafe');

fixture('test');

let expectedRunNumber = -1;
let shouldFail = true;

test('test', async (browser) => {
    ++expectedRunNumber;
    await browser.navigateTo(`http://getrunnumber.invalid/${expectedRunNumber}`);
    await browser.expect(Selector('#runNumber').exists).ok();
    const dynamicVal = await Selector('#runNumber').textContent;
    await browser.navigateTo('http://getrunnumber.invalid/static');
    await browser.expect(Selector('#runNumberStatic').exists).ok();
    const staticVal = await Selector('#runNumberStatic').textContent;
    console.log(`run: ${expectedRunNumber}, dynamic: ${dynamicVal}, static ${staticVal}`);
    await browser.expect(dynamicVal).eql(`${expectedRunNumber}`);
    await browser.expect(staticVal).eql(`${expectedRunNumber}`);
    if (shouldFail) {
        shouldFail = false;
        await browser.expect(false).ok();
    }
})
```

### Your complete test report

node index.js
 Running tests in:
 - Chrome 101.0.4951.64 / macOS 10.15.7

 test
run: 0, dynamic: 0, static 0
run: 1, dynamic: 1, static 0
run: 2, dynamic: 2, static 0
 ✖ test

   1) AssertionError: expected '0' to deeply equal '2'

      + expected - actual

      -0
      +2

      Browser: Chrome 101.0.4951.64 / macOS 10.15.7

         13 |    await browser.navigateTo('http://getrunnumber.invalid/static');
         14 |    await browser.expect(Selector('#runNumberStatic').exists).ok();
         15 |    const staticVal = await Selector('#runNumberStatic').textContent;
         16 |    console.log(`run: ${expectedRunNumber}, dynamic: ${dynamicVal}, static ${staticVal}`);
         17 |    await browser.expect(dynamicVal).eql(`${expectedRunNumber}`);
       > 18 |    await browser.expect(staticVal).eql(`${expectedRunNumber}`);
         19 |    if (shouldFail) {
         20 |        shouldFail = false;
         21 |        await browser.expect(false).ok();
         22 |    }
         23 |})

         at <anonymous> (/Users/andrzej-kodify/projects/testcafe-before-request-hooks/test.js:18:37)
         at asyncGeneratorStep (/Users/andrzej-kodify/projects/testcafe-before-request-hooks/test.js:1:114)
         at _next (/Users/andrzej-kodify/projects/testcafe-before-request-hooks/test.js:1:452)

 1/1 failed (1s)

### Steps to Reproduce

1.
2.
3.

### TestCafe version

1.18.6

### Node.js version

v16.14.2

### Command-line arguments

n/a

**Comment by andrzej-kodify** [comment]
Thanks for reply, I've used another workaround where URL contains test run ID, so it's unique per quarantine attempt (although removing mocks is probably better).

I just feel like the behaviour of keeping anything between test runs is inconsistent with the rest (as e.g. user session is cleared) so I wanted to point it out. Other than that all good, maybe worth adding this to documentation (if it's not there already)

**Comment by Aleksey28** [comment]
> Thanks for reply, I've used another workaround where URL contains test run ID, so it's unique per quarantine attempt (although removing mocks is probably better).

Thank you for sharing this workaround.

> Other than that all good, maybe worth adding this to documentation (if it's not there already)

We will consider updating our documentation though we find this use case a very rare situation.
