### ISSUE TITLE
Incorrect type definition for quarantineMode

### ISSUE THREAD

**Issue by andrzej-kodify** [DevExpress/testcafe#7031]
### What is your Scenario?

Using quarantineMode with testrunner api

### What is the Current behavior?

api claims to take `Record<string, string>` for quarantine mode `RunOptions`

https://github.com/DevExpress/testcafe/blob/af2813df48b7742a41ca3ebefe272884a36b6038/ts-defs-src/runner-api/runner-api.d.ts#L151

https://github.com/DevExpress/testcafe/blob/73c00e3e2a2fe102f9f55da85ade05626cf91eea/ts-defs-src/runner-api/options.d.ts#L203

While passing strings e.g. `{ attemptLimit: '2', successThreshold: '1' }` seems ok, in fact it seems to use default values instead of ones provided. Everything works correctly if numbers are passed e.g. `{ attemptLimit: 2, successThreshold: 1 }`, but then you need to ignore typescript error

### What is the Expected behavior?

I think type definition should be changed to
```
quarantineMode: boolean | Record<string, number>;
```

or even better to list allowed properties instead of just being a `Record`

### What is your public website URL? (or attach your complete example)

n/a

### What is your TestCafe test code?

n/a

### Steps to Reproduce

1.
2.
3.

### TestCafe version

1.18.6

### Command-line arguments

v16.14.2

**Comment by miherlosev** [comment]
Hi @andrzej-kodify 

Thank you for pointing this out to us. I've created a [PR](https://github.com/DevExpress/testcafe/pull/7034) with more strict TypeScript typings for the `quarantine mode` option.
