### ISSUE TITLE
[docs] `Thumbnails` option of the `screenshot`

### ISSUE THREAD

**Issue by Aleksey28** [DevExpress/testcafe#7032]
### What is your Scenario?

[The docs topic](https://testcafe.io/documentation/402840/guides/advanced-guides/screenshots-and-videos#header) doesn't have any mentions about the option `thumbnails` of the `screenshot`. But it exists in the other topics, e.g. https://testcafe.io/documentation/402654/reference/testcafe-api/runner/screenshots.

### What are you suggesting?

Сomplement documentation with this option.

**Comment by titerman** [comment]
The documentation has been updated. It may take a while for the website to reflect these changes.
