### ISSUE TITLE
Getting this error 'Cannot implicitly resolve the test run in the context of which the test controller action should be executed. Use test function's 't' argument instead' when trying to get the browser and device details in the custom testcafe reporter

### ISSUE THREAD

**Issue by Vooha-QualiTlabs** [DevExpress/testcafe#7039]
### What is your Scenario?

I have used my custom testcafe reporter: `testcafe-reporter-xray-jira`
https://www.npmjs.com/package/testcafe-reporter-xray-jira in the xray.js file to get the device name for mobiles

async function getDeviceType() {
    var platformType = await t.browser.platform;

    if(platformType == 'desktop') {
        console.log('t.browser.os.name', await t.browser.os.name);
        return t.browser.os.name;
    } else if(platformType == 'mobile') {
        console.log('t.browser.alias', await t.browser.alias);
        var deviceName = t.browser.alias;
        var device = deviceName.split(':');
        console.log('device Name', device[1]);
        return device[1];
    }
}

We are using browser stack as the browser provider. I have set this code and linked the package locally. When I run the code with this I am getting an error.

### What is the Current behavior?

![image](https://user-images.githubusercontent.com/91185844/169281136-5daedeee-4f0e-467a-abf7-68a82e8c5c7e.png)

I have tried setting up a env variable to set it from my code, but that flow doesn't seem to work as the reporter code executes first.
![image](https://user-images.githubusercontent.com/91185844/169281376-a41ed613-3e32-4595-961c-775896d49467.png)

![image](https://user-images.githubusercontent.com/91185844/169281450-27316b72-dd03-4c75-8daa-2d5d3be9b76c.png)

![image](https://user-images.githubusercontent.com/91185844/169281835-00588f6e-b349-4a5c-8b39-6bc707212391.png)

### What is the Expected behavior?

Please help me if there is any way to set the mobile device name in to the reporter

### What is your public website URL? (or attach your complete example)

xxx

### What is your TestCafe test code?

xxx

### Steps to Reproduce

xxx

### TestCafe version

xx

### Command-line arguments

xx

**Comment by Vooha-QualiTlabs** [comment]
@Dmitry-Ostashev  @Artem-Babich  please help me with this. Thanks.

**Comment by AlexKamaev** [comment]
You cannot use the `t` variable in the reporter since the reporter is executed after the test. However, your solution with environment variables is correct. I created a sample, which demonstrates how you can use environment variables to pass data to the reporter.

Please run this test:


The test
```JS
function getDeviceType(t) {
    var platformType = t.browser.platform;

    if (platformType == 'desktop') {
        return t.browser.os.name;
    }
    else if (platformType == 'mobile') {
        var deviceName = t.browser.alias;
        var device     = deviceName.split(':');
        return device[1];
    }
}

fixture `fixture`
    .page `http://example.com`
    .beforeEach(t => {
        process.env['deviceType'] = getDeviceType(t);
    })

test(`test`, async t => {
    await t.click('h1');
});
```
Add the following lines to the `reportTestDone` function of your reporter:


```JS
reportTestDone: function reportTestDone(name, testRunInfo) {
    this.write('Device type: ');
    this.write(process.env['deviceType']);
}
```

**Comment by Vooha-QualiTlabs** [comment]
@AlexKamaev That's working. Thank you very much.
