### ISSUE TITLE
Request to different subdomain does not se the cookies

### ISSUE THREAD

**Issue by jucallej** [DevExpress/testcafe#7040]
### What is your Scenario?

- I make a request from http://ui.something.more.hammerhead.local:8080 to http://server.something.more.hammerhead.local:3000
- http://server.something.more.hammerhead.local:3000 returns cookies that are valid for both subdomains (eg. `Domain=.something.more.hammerhead.local;`)
- I should see the cookies in http://ui.something.more.hammerhead.local:8080 and should be able to use them normally.

### What is the Current behavior?

- I make a request from http://ui.something.more.hammerhead.local:8080 to http://server.something.more.hammerhead.local:3000
- http://server.something.more.hammerhead.local:3000 returns cookies that are valid for both subdomains (eg. `Domain=.something.more.hammerhead.local;`)
- The cookie is not saved save

### What is the Expected behavior?

The cookie should be saved

### What is your public website URL? (or attach your complete example)

https://github.com/jucallej/testcafe-subdomains

### What is your TestCafe test code?

fixture `The web page in a different subdomain than the api`
    .page `http://ui.something.more.hammerhead.local:8080`;
import { RequestLogger, ClientFunction } from 'testcafe';

// eslint-disable-next-line no-undefined
export const logger = RequestLogger(undefined, {
    logRequestHeaders:     true,
    logResponseHeaders:    true,
    logRequestBody:        true,
    stringifyRequestBody:  true,
    logResponseBody:       true,
    stringifyResponseBody: true,
});

test('does not set the cookie from a different subdomain', async () => {
    const getCookies = ClientFunction(() => document.cookie);

    console.log('Response headers cookies being set:', logger.requests[1].response.headers['set-cookie']);
    console.log('Actual cookies:', await getCookies());
}).requestHooks(logger);

### Steps to Reproduce

1. Add to your host files (eg. on mac `/etc/hosts `)
```
127.0.0.1 ui.something.more.hammerhead.local
127.0.0.1 server.something.more.hammerhead.local
```
2. Download https://github.com/jucallej/testcafe-subdomains
3. `npm i`
4. `npm start`
5. The cookie is not printed in the logs
6. If you run `npm run dependencies` and browse to http://ui.something.more.hammerhead.local:8080 you see that the cookie does get set outside of testcafe

### TestCafe version

1.18.6

### Command-line arguments

testcafe chrome examples --skip-js-errors -a \"npm run dependencies\"

**Comment by Artem-Babich** [comment]
Thank you for the sample project. I was able to reproduce the issue. We will update this thread once we have any news.

**Comment by miherlosev** [comment]
Hi @jucallej,

This issue is not reproduced with combination of `testcafe@3.0.1` and the Google Chrome browser. Feel free to reopen this issue if you encounter it in other browsers.
