### ISSUE TITLE
Make scrolling speed configurable

### ISSUE THREAD

**Issue by aweaver5-chwy** [DevExpress/testcafe#7044]
### What is your Scenario?

Resurrecting https://github.com/DevExpress/testcafe/issues/2837

I would like to scroll to the bottom of a page at a slower speed.

### What are you suggesting?

The current scroll functions (`scroll()`, `scrollBy()`, and `scrollIntoView()`) scroll the page at the maximum speed possible. This should be configurable, akin to the `behavior` option of [Element.scroll()](https://developer.mozilla.org/en-US/docs/Web/API/Element/scroll).

**Comment by Aleksey28** [comment]
Hi @aweaver5-chwy ,

Thank you for your feedback. We will consider this enhancement and update this thread once we have results.

**Comment by aweaver5-chwy** [comment]
Thank you @Aleksey28,

For context, we are using `scroll()` to trigger Google Analytics/GTM events set to activate when elements are visible in the window. We are testing that the correct amount and types of events trigger for a given page. Currently, the events aren't triggered because the scroll speed is too fast. I've verified that the events trigger at a slower scroll speed by manually scrolling in `--debug-mode`.

The implementation of a scroll speed modifier would serve as a tremendous unblocker for our automated testing.
