### ISSUE TITLE
Browser providers aftermath changes

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#705]
- [x] Rename `testcafe-browser-natives` (linked to https://github.com/DevExpress/testcafe-browser-natives/issues/95)
- [x] Create `yeoman` generator package
- [x] Extract `soucelabs` and `phantomjs` providers into separate packages

**Comment by inikulin** [comment]
@AndreyBelym Can we close it now?

**Comment by AndreyBelym** [comment]
Implemented in #709
