### ISSUE TITLE
Request logger does not count mocked requests in 'contains' and 'count', but records them to 'requests'

### ISSUE THREAD

**Issue by VasilyStrelyaev** [DevExpress/testcafe#7057]
### What is your Scenario?

I need to search through certain requests with `contains`. I don't want them to reach the server, so I have to mock them.

### What is the Current behavior?

The `RequestLogger` does not count requests mocked with `RequestMock` in its `.contains()` and `.count()` methods. However, I can see these requests in `requests`.

The behavior was confirmed by @AndreyBelym by looking at the code 😄 .

### What is the Expected behavior?

We need consistent behavior. The `.count` and `.contains` methods should take into account mocked requests.

If this is not possible, maybe we can acknowledge a limitation in the documentation and remove them from `.requests` for consistency (and suggest that people use their mocks for counting). 

### What is your public website URL? (or attach your complete example)

-

### What is your TestCafe test code?

-

### Steps to Reproduce

1. -
2. -
3. -

### TestCafe version

-

### Command-line arguments

-

**Comment by miherlosev** [comment]
I cannot reproduce the issue with the following example:

```js
import { RequestLogger, RequestMock } from 'testcafe';
const mockedPageUrl = 'https://test-domain.com/mocked-page/';
const loggedPageUrl = 'https://example.com/';
const logger        = new RequestLogger([loggedPageUrl, mockedPageUrl]);
const requestMock = RequestMock()
    .onRequestTo(mockedPageUrl)
    .respond('<html><body><h1>Mocked page</h1></body></html>');
fixture `Fixture`
    .requestHooks(logger, requestMock);
test('Test', async t => {
    await t
        .navigateTo(loggedPageUrl)
        .navigateTo(mockedPageUrl)
        .expect(logger.count(r => r.request.url === loggedPageUrl)).eql(1)
        .expect(logger.count(r => r.request.url === mockedPageUrl)).eql(1);
});
```

Please prepare an example yourself or attract someone from the team.
