### ISSUE TITLE
Command line screenshot does not respect multiple options

### ISSUE THREAD

**Issue by GurpinderSandhu** [DevExpress/testcafe#7063]
### What is your Scenario?

When using the screenshots command in the command line and supplying more than one option, testcafe only seems to recognize the first option listed and ignores the second

### What is the Current behavior?

After running the command with multiple screenshot options (i.e path and takeOnFails) it will only override one option

`Using locally installed version of TestCafe.
The "browsers" and "screenshots.path" options from the configuration file will be ignored.`

### What is the Expected behavior?

After running the command with multiple screenshot options (i.e path and takeOnFails) it will override both options

`Using locally installed version of TestCafe.
The "browsers" and "screenshots.path" and "screenshots.takeOnFails" options from the configuration file will be ignored.`

### What is your public website URL? (or attach your complete example)

N/A

### What is your TestCafe test code?

`testcafe "edge --ignore-certificate-errors" .\path\to\test -e -s path=test/goldens,takeOnFails=false`

### Your complete configuration file

`{
  "color": true,
  "disableHttp2": true,
  "browsers": ["edge"],
  "concurrency": 1,
  "quarantineMode": false,
  "speed": 0.75,
  "pageLoadTimeout": 3000,
  "selectorTimeout": 15000,
  "assertionTimeout": 10000,
  "screenshots": {
    "path": "./screenshots",
    "takeOnFails": true,
    "fullPage": true,
    "pathPattern": "${DATE}/${USERAGENT}/${FIXTURE}/${TIME}_${TEST}_${FILE_INDEX}.png"
  },
  "videoPath": "./videos",
  "videoOptions": {
    "failedOnly": true,
    "pathPattern": "${DATE}/${USERAGENT}/${FIXTURE}/${TIME}_${TEST}_${RUN_ID}.png",
    "videoEncodingOptions": {
      "c": "v libx264 -crf 19 -level 3.1 -preset slow -tune film",
      "filter": "v scale=-1:720 -sws_flags lanczos"
    }
  },
  "reporter": [
    {
      "name": "spec",
      "output": "reports/report.xml"
    },
    {
      "name": "spec"
    },
    {
      "name": "slack"
    }
  ]
}
`

### Steps to Reproduce

1. Run something similar to `testcafe "edge --ignore-certificate-errors" .\path\to\test -e -s path=test/goldens,takeOnFails=false`
2. Notice the command line output to only ignore one of the options in the config file

### TestCafe version

1.18.6

### Node.js version

16.13.2

### Command-line arguments

`testcafe "edge --ignore-certificate-errors" .\path\to\test -e -s path=test/goldens,takeOnFails=false`

### Browser name(s) and version(s)

edge

### Platform(s) and version(s)

Windows

**Comment by AlexKamaev** [comment]
I was not able to reproduce the issue. I tried both 1.18.6 and 1.19.0. In all cases, this works as expected. Could you please record a video that demonstrates the behavior you described?
