### ISSUE TITLE
switchtoWindow() leaves that window in the background

### ISSUE THREAD

**Issue by tgrodano** [DevExpress/testcafe#7070]
### What is your Scenario?

I have a test that opens another window. I call switchToWindow(), to interact with the other window. However, when I do this, the window that I switch to does not move to the foreground. This causes a problem because it makes it difficult to debug the test because the recordings from my test framework capture what you see, and you can't see what is happening to the background window.  I expect that the window that I am switching to gets moved into the foreground.

### What is the Current behavior?

switchToWindow() leaves that window you are switching to in the background. The test automation does interact with the window that you have switched to, but you might not be able to see it.

### What is the Expected behavior?

When I call switchToWindow(), I expect that the window that I am switching to gets visually moved into the foreground 

### What is your public website URL? (or attach your complete example)

[test.zip](https://github.com/DevExpress/testcafe/files/8848395/test.zip)

### What is your TestCafe test code?

import { Selector } from 'testcafe';

fixture `Switch Windows`
    .page `https://devexpress.github.io/testcafe/example/`;

test
('Switching between windows', async t => {
    const windowDevExpress = await t.getCurrentWindow();
    const nameInput = Selector('#developer-name');
    const triedTestCafeCheckbox = Selector('#tried-test-cafe');
    const searchText = Selector("input[title='Search']");
    await t .maximizeWindow()        
    
    const windowGoogle = await t.openWindow('https://www.google.com/');
    await t.maximizeWindow();    

    // now switch back to devexpress window and observe it is still in the background
    // and even though you are interacting with it, it remains hidden behind the other window
    // Expected result was that it would get moved to the foreground on switchToWindow()
    await t
        .switchToWindow(windowDevExpress)
        .typeText(nameInput, 'MyName')
        .click(triedTestCafeCheckbox)
        .expect(nameInput.value).eql('MyName')
        .takeScreenshot()
        .wait(2000);
            
    // close the foreground (google) window and you will see that the devexpress window was updated
    // while it was in the background  
    await t
        .switchToWindow(windowGoogle)
        .typeText(searchText, 'TestCafe')
        .pressKey('enter')
        .wait(2000)
        .closeWindow(windowGoogle)
        .wait(3000);
});

### Steps to Reproduce

1. Run the attached sample test and observe it while it runs. Observe that the google window is in the foreground. When it closes, observe that the test interacted with the devexpress window in the background

On line 21 I call switchToWindow to display the devexpress window, but the google window that was opened on line 14 is still in the foreground. When closeWindow is called on line 35, you can see that the name and checkbox were set on the devexpress window while it was in the background. This becomes a problem when the test doesn't pass and you want to look at the recording to help you debug, but can't see what is happening because the active window was in the background.

### TestCafe version

1.18.2

### Node.js version

14.15

### Command-line arguments

testcafe chrome test.js

### Browser name(s) and version(s)

Chrome

### Platform(s) and version(s)

Windows 10

**Comment by AlexKamaev** [comment]
I'll mark this issue as enhancement, since this behavior does not break any TestCafe functionality.
Please note that you also can record a video using built-in TestCafe mechanism.
Refer to the following articles to get details and read about limitations:
https://testcafe.io/documentation/402840/guides/intermediate-guides/screenshots-and-videos#record-videos
https://testcafe.io/documentation/402841/guides/intermediate-guides/multiple-browser-windows#recorded-video-aspect-ratio-in-multiple-windows

**Comment by AlexKamaev** [comment]
We decided to close the issue, since it's not popular among TestCafe users. As for video recording, I would recommend using the built-in video recording functionality as described in the comment above.
