### ISSUE TITLE
Please export TestController interface

### ISSUE THREAD

**Issue by ravi005e** [DevExpress/testcafe#7071]
### What is your Scenario?

doing something like this

private controller: TestController;

constructor(controller: TestController) {
this.controller = controller;
}

protected dosomething(): void {
this.controller.click('.foo')
}

### What is the Current behavior?

doing something like this

private controller: TestController;

constructor(controller: TestController) {
this.controller = controller;
}

protected dosomething(): void {
this.controller.click('.foo')
}

### What is the Expected behavior?

should able to import "TestController"

### What is your public website URL? (or attach your complete example)

n/a

### What is your TestCafe test code?

n/a

### Steps to Reproduce

see scenario above

### TestCafe version

latest

### Command-line arguments

n/a

**Comment by Aleksey28** [comment]
It should work as you described. By the way, I recommend you see [this article](https://testcafe.io/documentation/402665/reference/test-api/testcontroller#implicit-test-controller-use) - it describes how to import TestController in the right way.
