### ISSUE TITLE
Stacktrace / Callsite with Typescript not working correctly

### ISSUE THREAD

**Issue by pschmolke** [DevExpress/testcafe#7078]
### What is your Scenario?

When an assertion fails the spec reporter outputs me the expected and actual value of that assertion, but I cannot see where this assertion exactly failed. Which is real pain for deep nested functions.
When specifying the `sourceMap` to `true` in the `tsconfig.json` I get presented wrong lines in the output. The callsite is wrong too.
When using `inlineSourceMap` inside `tsconfig.json` I even get no line numbers at all and no callsite at all in the output. 

Funny side note:
On setting up a test project the problem did not occur. Then I tested a few different options and it did not work anymore. Then I reverted all changes again but strangely I could not get the output correctly presented anymore.

### What is the Current behavior?

I cannot get the reporter to work properly on an assertion error.

### What is the Expected behavior?

Whether I use inlined source maps or source maps in different files, the report should output the lines of failure and a correct callsite.

### What is your public website URL? (or attach your complete example)

n/a

### What is your TestCafe test code?

```
import { Selector } from 'testcafe';

fixture `DEBUGGING`;

test( 'will this work', async (t:TestController) => {
   await t.expect( true ).eql( false );
} );

//asd asda

// asdasd

```

### Your complete configuration file

# .testcaferc.json

```
{
   "compilerOptions": {
      "typescript": {
         "configPath": "./tsconfig.json"
      }
   },
   "browsers": [
      "chrome:headless:width=1800;height=1000"
   ],
   "disableMultipleWindows": true,
   "disablePageCaching": true,
   "retryTestPages": false
}
```

# tsconfig.json

```
{
   "compilerOptions": {
      "sourceMap": true,
      "inlineSources": false,
      "inlineSourceMap": false,
      "outDir": "dist",
      "experimentalDecorators": true,
      "moduleResolution": "node",
      "resolveJsonModule": true,
   },
}
```

### Your complete test report

```
 Running tests in:
 - Chrome 102.0.5005.61 / macOS 10.15.7

 DEBUGGING
 ✖ will this work

   1) AssertionError: expected true to deeply equal false

      + expected - actual

      -true
      +false


      Browser: Chrome 102.0.5005.61 / macOS 10.15.7

         10 |
         11 |// asdasd
         12 |

         at <anonymous> (/Users/pschmolke/develop/git/testcafe-testing/tests/debug.ts:15:26)
         at <anonymous> (/Users/pschmolke/develop/git/testcafe-testing/tests/debug.ts:8:71)
         at __awaiter (/Users/pschmolke/develop/git/testcafe-testing/tests/debug.ts:4:12)
         at <anonymous> (/Users/pschmolke/develop/git/testcafe-testing/tests/debug.ts:14:31)



 1/1 failed (0s)
```

### Steps to Reproduce

1. Init Testcafe project
2. Init Typescript compiler
3. Use "inlineSourceMap"
4.  Fail an assertion

### TestCafe version

1.19.0

### Node.js version

v16.3.0

### Command-line arguments

testcafe chrome tests/debug.ts

### Browser name(s) and version(s)

Chrome 102

### Platform(s) and version(s)

macOS 10.15.7

**Comment by AlexKamaev** [comment]
I tried to reproduce the issue without an additional `tsconfig.json`. Everything works as expected. Apparently, your `tsconfig.json` file. causes the error.
Please try to apply the settings from the TestCafe default typescript configuration to your configuration file and share the results with us.
You can find it here: [https://github.com/DevExpress/testcafe/blob/37b40966300ed2d29aaa5c865032771d97c183e1/src/configuration/default-values.ts#L23](https://github.com/DevExpress/testcafe/blob/37b40966300ed2d29aaa5c865032771d97c183e1/src/configuration/default-values.ts#L23)
I modified your `tsconfig.json` to make callsite work:

```JSON
{
"compilerOptions": {
  "sourceMap": false,
  "inlineSources": false,
  "inlineSourceMap": true,
  "experimentalDecorators": true,
  "moduleResolution": "node",
  "resolveJsonModule": true,
  }
}
```

It looks like the cause of the issue is related to the use of the `outDir` property. Why do you need to use this property for TestCafe tests?

**Comment by pschmolke** [comment]
Hi @AlexKamaev, thank you for your response!
I've tested your hypothesis and I can confirm it. Removing the "outDir" from my `tsconfig.json` resolves again into stacktraces which get shown.

I do not **need** the option per se, but it would have been nice for a clean workspace. I remove it from the project now.
Thanks alot!
