### ISSUE TITLE
jQuery mobile checkboxradio widgets do not work from testcafe

### ISSUE THREAD

**Issue by tgreiser** [DevExpress/testcafe#7079]
### What is your Scenario?

Trigger a single click on the checkbox using testcafe.

### What is the Current behavior?

Two click events appear to fire as a result of one t.click() call. The checkbox registers as checked for a short time, and then reverts to unchecked.

### What is the Expected behavior?

A similar test passes with a vanilla checkbox.

```
import { Selector } from 'testcafe';

fixture`checkboxradio test`
    .page`https://html.form.guide/checkbox/html-form-with-checkbox/`;

test('Checkbox state from testcafe', async t => {
        const cb = await Selector('input[type=checkbox]');
        await t.expect(cb.nth(0).checked).eql(false)
                .click(cb.nth(0));

        await t.expect(cb.nth(0).checked).eql(true);
});
```

### What is your public website URL? (or attach your complete example)

https://demos.jquerymobile.com/1.4.5/checkboxradio-checkbox/

### What is your TestCafe test code?

import { Selector } from 'testcafe';

fixture`checkboxradio test`
    .page`https://demos.jquerymobile.com/1.4.5/checkboxradio-checkbox/`;

test('Checkbox state from testcafe', async t => {
        const cb = await Selector('#checkbox-h-2a');
        await t.expect(cb.checked).eql(false)
                .click(cb);

        await t.expect(cb.checked).eql(true);
});

### Your complete test report

```
$ testcafe chrome src/jquerymobile_checkboxradio.js
 Running tests in:
 - Chrome 102.0.5005.63 / Windows 10

 checkboxradio test
 × Checkbox state from testcafe

   1) AssertionError: expected false to deeply equal true

      + expected - actual

      -false
      +true


      Browser: Chrome 102.0.5005.63 / Windows 10

          6 |test('Checkbox state from testcafe', async t => {
          7 |    const cb = await Selector('#checkbox-h-2a');
          8 |   await t.expect(cb.checked).eql(false)
          9 |           .click(cb);
         10 |
       > 11 |   await t.expect(cb.checked).eql(true);
         12 |});
         13 |

         at <anonymous>
      (D:\Code\checkboxradioTest\src\jquerymobile_checkboxradio.js:11:29)
         at asyncGeneratorStep
      (D:\Code\checkboxradioTest\src\jquerymobile_checkboxradio.js:1:239)
         at _next
      (D:\Code\checkboxradioTest\src\jquerymobile_checkboxradio.js:1:577)



 1/1 failed (16s)
```

### Steps to Reproduce

1. Run the example test with chrome - it uses a public URL example page.
2.
3.

### TestCafe version

1.19.0

### Node.js version

v15.11.0

### Command-line arguments

testcafe chrome test.js

### Browser name(s) and version(s)

Chrome 102.0.5005.63

### Platform(s) and version(s)

Windows 10

**Comment by AlexKamaev** [comment]
I reproduced the issue. Please track this ticket to follow our progress.
