### ISSUE TITLE
Create CSS Selector Path for Elements on the page

### ISSUE THREAD

**Issue by uhPotato** [DevExpress/testcafe#7081]
### What is your Scenario?

I am working on some project of mine that requires me to compare mapping of elements to document containing selectors.
Map contains Key value pairs of CSS Selector path and Attribute with value.

Testcafe is great for iterating through an array of selectors and getting values. However, Pulling selector path of elements doesn't seem to be an option.

### What are you suggesting?

Could there be a feature added that would allow for a unique CSS selector path to be built and provided for elements on a page? These would then be able to be stored and used as unique selector values.

### What alternatives have you considered?

Have used other libraries and packages. However this requires me to drop testcafe selectors and use document or the 'finder' selector functions. Defeating the purpose of using Testcafe.

**Comment by AlexKamaev** [comment]
Currently, TestCafe does not provide any mechanism to pick selectors from the page. We have plans to improve the way TestCafe is working with selectors. However, right now, I cannot give you any time estimates on this. We'll take your usage scenario into account.
In the meantime, you can try to use the `--experimental-debug` feature. I hope it will help you with selector picking.
