### ISSUE TITLE
Element fails to scroll if the CSS property is set to flex-direction: column-reverse

### ISSUE THREAD

**Issue by bugnano** [DevExpress/testcafe#7083]
### What is your Scenario?

The scenario is a chat application.

On top of the chat, there is a link with id `showMore`, that is used to show
older messages.
Right after that link, there are all the chat messages.

Now, I want to test what happens when the user clicks the `#showMore` element.
As there are many messages, and we have the last message into view, the test
code needs to scroll up, until the `#showMore` element is visible.

### What is the Current behavior?

When I try to interact with the `#showMore` element with testcafe functions, the test fails with the error

```
The element that matches the specified selector is not visible.
```

### What is the Expected behavior?

The `#showMore` element is scrolled into view, and interacted with.

### What is your public website URL? (or attach your complete example)

I made a complete example in this repository, and the README.md file has all the instructions needed to run the test.

https://github.com/talkjs/testcafe_bug

### What is your TestCafe test code?

The test code is in the same repository

https://github.com/talkjs/testcafe_bug

### Steps to Reproduce

1. Git clone https://github.com/talkjs/testcafe_bug
2. Follow the instructions in the README.md file
3. Profit!

### TestCafe version

1.19.0

### Node.js version

v16.15.1

### Command-line arguments

npx testcafe chromium tests/

### Platform(s) and version(s)

Linux Ubuntu 20.04

**Comment by Aleksey28** [comment]
Hi @bugnano,

Thank you for the example. I managed to reproduce this issue. We'll update this thread once we have news.
