### ISSUE TITLE
Test Cafe need permission to launch test on chrome browser 

### ISSUE THREAD

**Issue by gautammontu** [DevExpress/testcafe#7086]
### What is your Scenario?

Executed 12 test parallel in chrome browser out of which one test is not executed since pop up displayed  to  grant access for executing the test

Job details : https://app.saucelabs.com/tests/854b826dae404448a3419cc0f0660966

  

### What is the Current behavior?

Permission pop up window got displayed 

### What is the Expected behavior?

Test should execute 

### What is your public website URL? (or attach your complete example)

https://app.saucelabs.com/tests/854b826dae404448a3419cc0f0660966

### What is your TestCafe test code?

https://app.saucelabs.com/tests/854b826dae404448a3419cc0f0660966

### Steps to Reproduce

Details can be found in this recording:

https://app.saucelabs.com/tests/854b826dae404448a3419cc0f0660966

### TestCafe version

1.18.5

### Command-line arguments

saucectl run

**Comment by miherlosev** [comment]
Hi @gautammontu 

I got the 404 error on opening the `SauceLabs` links from the issue description. It means, I don't have permissions to see them.
Could you please attach a recorded video of test execution to this issue?
