### ISSUE TITLE
Contains ClassNames will always resolve to true

### ISSUE THREAD

**Issue by zakmketool** [DevExpress/testcafe#7093]
### What is your Scenario?

Using a data-test-id for the selector I am trying to determine if a field is clickable or if the input box is disabled. Using .expect(Selector([myIDTag]).classNames).contains("ant-select-disabled") always resolved to true. Screenshot below shows what happens when I create the scenario in the TestCafe IDE. 

![image](https://user-images.githubusercontent.com/89992640/174164152-85337d2a-4265-428c-8ce9-cdbf622792f4.png)

### What is the Current behavior?

Expressions using className or getAttribute('class') always resolve to true. 

### What is the Expected behavior?

Evaluation should be done to determine if the given input is contained inside the selector's class contents. 

### What is your public website URL? (or attach your complete example)

Internal site. Not specific to my site. 

### What is your TestCafe test code?

        .expect(Selector(cTake.productCategory).classNames).contains("ant-select-disabled")

### Steps to Reproduce

1. Use this expression:         .expect(Selector(cTake.productCategory).classNames).contains("ant-select-disabled")

### TestCafe version

1.18.1

### Command-line arguments

testcafe chrome tests/*

**Comment by AlexKamaev** [comment]
I didn't manage to reproduce the issue. Please prepare a sample using some public website so that we can reproduce the issue on our side.

**Comment by AlexKamaev** [comment]
I did not manage to reproduce the issue even on the [https://www.nytimes.com](https://www.nytimes.com) website.
Please try to update your TestCafe version to the latest one and share your results with us.

**Comment by AlexKamaev** [comment]
I tried to reproduce the issue using your example:


```JS
import { Selector } from 'testcafe';

fixture `New Fixture`
    .page `https://www.nytimes.com/`;

test('New Test', async t => {
    await t
        .expect(Selector('#site-content h3')
            .withText('As Fuel Prices')
            .getAttribute('class'))
        .contains("cows");
});
```

I got the following error in the report:
```
New Fixture                         
 × New Test

   1) AssertionError: expected 'indicate-hover css-1pvrrwb' to include 'cows'

      Browser: Chrome 102.0.5005.115 / Windows 10

          6 |test('New Test', async t => {
          7 |    await t
          8 |        .expect(Selector('#site-content h3')
          9 |            .withText('As Fuel Prices')
         10 |            .getAttribute('class'))
       > 11 |        .contains("cows");
         12 |});
         13 |
         14 |

         at <anonymous> (C:\Projects\testcafe\test\functional\fixtures\regression\gh-1994\testcafe-fixtures\index.js:11:10)
         at asyncGeneratorStep (C:\Projects\testcafe\test\functional\fixtures\regression\gh-1994\testcafe-fixtures\index.js:1:195)
         at _next (C:\Projects\testcafe\test\functional\fixtures\regression\gh-1994\testcafe-fixtures\index.js:1:533)
         at <anonymous> (C:\Projects\testcafe\test\functional\fixtures\regression\gh-1994\testcafe-fixtures\index.js:1:698)
         at <anonymous> (C:\Projects\testcafe\test\functional\fixtures\regression\gh-1994\testcafe-fixtures\index.js:1:439)
         at <anonymous> (C:\Projects\testcafe\test\functional\fixtures\regression\gh-1994\testcafe-fixtures\index.js:6:5)



 1/1 failed (12s)

```
As you can see, the test failed as expected.
Please check the TestCafe version you are using. Execute the following command in your test directory:
```
npx testcafe -v
```

**Comment by zakmketool** [comment]
Hello, looking to see if you confirmed my NYT example and class names checks always resolving to true.

Zak Ziolkowski
QA Engineer II
Milwaukee Tool
C: 262-617-8285
***@***.******@***.***>

Stay Connected
***@***.******@***.******@***.******@***.******@***.******@***.***<https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.flickr.com%2Fphotos%2Fmilwaukeetool&data=04%7C01%7CZachary.Ziolkowski%40milwaukeetool.com%7Ca41a0ef627004b91259f08d8dcf68f62%7C324f02a1b90146ec867ea62e49604dbb%7C0%7C0%7C637502298820480215%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BCFxVQ0xueV08sONMPuK%2BCvvJyVZwtM7AYnhadjNuMI%3D&reserved=0>[Milwaukee Electric Tool Email Signature Glassdoor]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.glassdoor.com%2FOverview%2FWorking-at-Milwaukee-Tool-EI_IE13627.11%2C25.htm&data=04%7C01%7CZachary.Ziolkowski%40milwaukeetool.com%7Ca41a0ef627004b91259f08d8dcf68f62%7C324f02a1b90146ec867ea62e49604dbb%7C0%7C0%7C637502298820490214%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FQ9Uqi0axFLGO17KdXW2iqdnfyIDXn%2BJoxlq26%2Bk1Ww%3D&reserved=0>

[Description: C:\Users\pmueller\AppData\Roaming\Microsoft\Signatures\METCoLogos\METCo_STD_Logo-RW.gif]

**Comment by AlexKamaev** [comment]
I did not manage to reproduce the incorrect behavior.
