### ISSUE TITLE
global hooks not working

### ISSUE THREAD

**Issue by vertic4l** [DevExpress/testcafe#7098]
### What is your Scenario?

We are trying to set a window property before running our tests. If set, it will change the behaviour of our site. 
Tried ClientFunction and now hooks, but nothing seems to work.

in our testcaferc.js we set up a hook like this
```
module.exports = {
    color: true,
    debugOnFail: false,
    skipJsErrors: false,
    speed: 1,
    hooks: {
        test: {
            before: async (t) => {
                await t.eval(() => (window.isE2E = true));
            },
        },
    },
};
```

### What is the Current behavior?

window.isE2E will never be set and therefore our site behaves not as intended.

### What is the Expected behavior?

window.isE2E will be set and our site behaves as intended.

### What is your public website URL? (or attach your complete example)

-

### What is your TestCafe test code?

see above

### Steps to Reproduce

Use config example from above and check if window.isE2E is set during any tests.

### TestCafe version

1.19

### Command-line arguments

-

**Comment by Aleksey28** [comment]
Hi @vertic4l,

I cannot reproduce this issue. In my example, everything works correctly.

```js
//.testcaferc.js
module.exports = {
  color: true,
  debugOnFail: false,
  skipJsErrors: false,
  speed: 1,
  hooks: {
    test: {
      before: async (t) => {
        await t.eval(() => (window.isE2E = true));
      },
    },
  },
};
```

```js 
//test.js
fixture`Fixture`
    .page`https://devexpress.github.io/testcafe/example/`;

test(`Test`, async (t) => {
    await t.expect(t.eval(() => window.isE2E)).eql(true);
})
```

Please clarify what steps I need to perform in order to reproduce the issue.
