### ISSUE TITLE
[docs] Create a better overview of TestCafe and its capabilities

### ISSUE THREAD

**Issue by titerman** [DevExpress/testcafe#7146]
### What is your Scenario?

The [Why TestCafe?](https://testcafe.io/documentation/402631/why-testcafe#header) article leaves a lot to be desired

### What are you suggesting?

Split the article in two: Why TestCafe? and How does TestCafe work?
Create a new article that goes over all the TestCafe capabilities

**Comment by helen-dikareva** [comment]
Related:
https://github.com/DevExpress/testcafe-marketing/issues/313
https://github.com/DevExpress/testcafe-marketing/issues/316
