### ISSUE TITLE
Testcafe run never finishesh in case browser freezes

### ISSUE THREAD

**Issue by wombatka** [DevExpress/testcafe#7162]
### What is your Scenario?

since 1.18.5 I have an issue with testcafe when running concurrently. Tests in one browser get stuck on click on navigation and no further action is performed in this browser window . This happens ocasionally and randomly -  each time in different test (i did not create an issue for that as i cannot track it with any simple example and the behaviour is totally random). After one window gets frozens- tests in other browser windows continue running normally. However- there is no more reporter output in console ( i use spec reporter) . Additionally the testcafe execution never finishes- because the frozen window is never closed. There should be some mechanism to detect unresponsive browser  and fail a test after significant amount of time. I tried using :  --test-execution-timeout - but it does not detect the timeout in the frozen browser- so does not fail the test. 

### What is the Current behavior?

testcafe never finishes executing after one browser gets stuck

### What is the Expected behavior?

Tesctafe should detetct unresponsive browsers and failt the test and continue running

### What is your public website URL? (or attach your complete example)

described above- no steps

### What is your TestCafe test code?

described above- no steps

### Steps to Reproduce

1.Run tests with -c 4 in firefox
2.wait until one of the browsers freezes on click navigation (happens ocasionally)
3.NOT OK - the testcafe run will never finish

### TestCafe version

1.18.5

### Node.js version

v14.16.0

### Command-line arguments

npm test

### Browser name(s) and version(s)

FIrefox 99

**Comment by AlexKamaev** [comment]
I did not manage to reproduce the issue. I understand that it can be difficult to create a reproducible example, but we are not able to research the issue without it. So, please try to create an example with which we can reproduce the problematic behavior on our machines.

Please also update your TestCafe, NodeJS, and Firefox versions to the latest or recommended versions.
