### ISSUE TITLE
Invalid tests execution on selenium grid with chrome browser

### ISSUE THREAD

**Issue by wombatka** [DevExpress/testcafe#7164]
### What is your Scenario?

We are running testcafe tests on selenium grid using this plugin: https://github.com/alexschwantes/testcafe-browser-provider-selenium. We use chrome and concurrency - 5
The issue does not occur on firefox grid. Reducing the number of browsers even to 2 does not help
Issue occurs also on earlier testcafe versions (including 1.18.2) and on different node versions as well and on earlier chrome versions (including 100)

### What is the Current behavior?

In case tests are executed with concurrency  (-c 5) the tests are not run correctly- reporter does not print any output and the test run is endlsess 

### What is the Expected behavior?

tests should run as on normal browser 

### What is your public website URL? (or attach your complete example)

I attach a simple example with 26 tests doing nothing more than open page- click element and print the value of variable i 

### What is your TestCafe test code?

example.js
import {Selector, t} from "testcafe"

fixture `example`
    .beforeEach(async () => {
        await t.maximizeWindow()
        await t.navigateTo(`https://mui.com/material-ui/getting-started/overview/`);
        await t.click(Selector("a").withText("Components"));
        await t.click(Selector("a").withText("Button"));
        await t.expect(Selector("[name=loading]").exists).ok()

    })
var i = 0
test('E1', async t => {
     await t.click(Selector("[name=loading]"));
     await t.click(Selector("button").withText("SEND").nth(1));
     console.log("I value is: " + i++);

})

test('E2', async t => {
    await t.click(Selector("[name=loading]"));
    await t.click(Selector("button").withText("SEND").nth(1));
    console.log("I value is: " + i++);

})

test('E3', async t => {
    await t.click(Selector("[name=loading]"));
    await t.click(Selector("button").withText("SEND").nth(1));
    console.log("I value is: " + i++);

})

test('E4', async t => {
    await t.click(Selector("[name=loading]"));
    await t.click(Selector("button").withText("SEND").nth(1));
    console.log("I value is: " + i++);

})

test('E5', async t => {
    await t.click(Selector("[name=loading]"));
    await t.click(Selector("button").withText("SEND").nth(1));
    console.log("I value is: " + i++);

})

test('E6', async t => {
    await t.click(Selector("[name=loading]"));
    await t.click(Selector("button").withText("SEND").nth(1));
    console.log("I value is: " + i++);

})

test('E7', async t => {
    await t.click(Selector("[name=loading]"));
    await t.click(Selector("button").withText("SEND").nth(1));
    console.log("I value is: " + i++);

})

test('E8', async t => {
    await t.click(Selector("[name=loading]"));
    await t.click(Selector("button").withText("SEND").nth(1));
    console.log("I value is: " + i++);

})

test('E9', async t => {
    await t.click(Selector("[name=loading]"));
    await t.click(Selector("button").withText("SEND").nth(1));
    console.log("I value is: " + i++);

})

test('E10', async t => {
    await t.click(Selector("[name=loading]"));
    await t.click(Selector("button").withText("SEND").nth(1));
    console.log("I value is: " + i++);

})

test('E11', async t => {
    await t.click(Selector("[name=loading]"));
    await t.click(Selector("button").withText("SEND").nth(1));
    console.log("I value is: " + i++);

})

test('E12', async t => {
    await t.click(Selector("[name=loading]"));
    await t.click(Selector("button").withText("SEND").nth(1));
    console.log("I value is: " + i++);

})

test('E13', async t => {
    await t.click(Selector("[name=loading]"));
    await t.click(Selector("button").withText("SEND").nth(1));
    console.log("I value is: " + i++);

})

test('E14', async t => {
    await t.click(Selector("[name=loading]"));
    await t.click(Selector("button").withText("SEND").nth(1));
    console.log("I value is: " + i++);

})

test('E15', async t => {
    await t.click(Selector("[name=loading]"));
    await t.click(Selector("button").withText("SEND").nth(1));
    console.log("I value is: " + i++);

})

test('E16', async t => {
    await t.click(Selector("[name=loading]"));
    await t.click(Selector("button").withText("SEND").nth(1));
})

test('E17', async t => {
    await t.click(Selector("[name=loading]"));
    await t.click(Selector("button").withText("SEND").nth(1));
    console.log("I value is: " + i++);

})

test('E18', async t => {
    await t.click(Selector("[name=loading]"));
    await t.click(Selector("button").withText("SEND").nth(1));
    console.log("I value is: " + i++);

})

test('E19', async t => {
    await t.click(Selector("[name=loading]"));
    await t.click(Selector("button").withText("SEND").nth(1));
    console.log("I value is: " + i++);

})

test('E20', async t => {
    await t.click(Selector("[name=loading]"));
    await t.click(Selector("button").withText("SEND").nth(1));
    console.log("I value is: " + i++);

})

test('E21', async t => {
    await t.click(Selector("[name=loading]"));
    await t.click(Selector("button").withText("SEND").nth(1));
    console.log("I value is: " + i++);

})

test('E22', async t => {
    await t.click(Selector("[name=loading]"));
    await t.click(Selector("button").withText("SEND").nth(1));
    console.log("I value is: " + i++);

})

test('E23', async t => {
    await t.click(Selector("[name=loading]"));
    await t.click(Selector("button").withText("SEND").nth(1));
    console.log("I value is: " + i++);

})

test('E24', async t => {
    await t.click(Selector("[name=loading]"));
    await t.click(Selector("button").withText("SEND").nth(1));
    console.log("I value is: " + i++);

})

test('E25', async t => {
    await t.click(Selector("[name=loading]"));
    await t.click(Selector("button").withText("SEND").nth(1));
    console.log("I value is: " + i++);

})

test('E26', async t => {
    await t.click(Selector("[name=loading]"));
    await t.click(Selector("button").withText("SEND").nth(1));
    console.log("I value is: " + i++);

})

### Your complete configuration file

.testcaferc.json
{
  "screenshots": {
    "path": "testoutput/screenshots",
    "pathPattern": "${FIXTURE}/${TEST}_${DATE}_${TIME}_${USERAGENT}_${QUARANTINE_ATTEMPT}_${FILE_INDEX}.png",
    "takeOnFails": true,
    "fullPage": true
  },
  "assertionTimeout": 10000,
  "selectorTimeout": 3000,
  "skipJsErrors": true,
  "reporter": [
    {
      "name": "spec-time"
    }
  ]
}

package.json

{
  "name": "testcafeexample",
  "version": "1.0.0",
  "description": "",
  "main": "example.js",
  "scripts": {
    "test": "testcafe -c 5 selenium:chrome example.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "testcafe": "1.20.0-rc.1",
    "testcafe-browser-provider-selenium": "^1.2.0",
    "testcafe-reporter-spec-time": "^4.0.0"
  }
}

### Screenshots

When the tests are run the console output is as follows:
![image](https://user-images.githubusercontent.com/25752375/179678985-b9205330-6bf3-4d70-8c26-d13b4783ddbd.png)
only first test is printed by reporter- then only the console.log output is printed, so that you can see that the tests are executed, but there is no output from reporter. The build will never finish, unless you open http://localhost:4444/ui/index.html#/sessions and view the session, open each browser- then  browsers will finally manage to finish execution and the build finishes. Then you will get the reporter output
![image](https://user-images.githubusercontent.com/25752375/179679748-b45af2dd-12a4-4dc6-8182-cdee0a84d947.png)

### Steps to Reproduce

1.run grid with:  sudo docker run -d -p 4444:4444 -p 7900:7900 --name=chromeGrid --shm-size="2g" -e 'VNC_NO_PASSWORD=1' -e 'SCREEN_WIDTH=1680' -e 'SCREEN_HEIGHT=1050' -e 'SE_NODE_MAX_SESSIONS=7' selenium/standalone-chrome
2. use package.json provided above and run npm install
3. run npm test to run the tests

### TestCafe version

1.20.0-rc.1

### Node.js version

v14.16.0

### Command-line arguments

npm test

### Browser name(s) and version(s)

Chrome 103.0.5060.114 / Linux 0.0

### Platform(s) and version(s)

Ubuntu Linux

**Comment by miherlosev** [comment]
Hi @wombatka 

It looks like this issue is related to the `testcafe-browser-provider-selenium` module. So, please write an issue in the https://github.com/alexschwantes/testcafe-browser-provider-selenium repository and share all necessary information there.
