### ISSUE TITLE
CleanAttributes() dosn't work with Attribute "length"

### ISSUE THREAD

**Issue by lisandrogreco** [DevExpress/testcafe#7172]
### What is your Scenario?

When a wrapper element contains an attribute which is named "length". The for loop crashes because the length attribute got removed. This breaks the Test execution in Testcafe

https://github.com/DevExpress/testcafe-hammerhead/blob/a878aefb01e45c3dc58d9d92da6e618cbc494c4c/src/client/sandbox/node/attributes/index.ts#L8

### What is the Current behavior?

Testcafe execution fails when element has an attribute named "length"

### What is the Expected behavior?

Testcafe works as expected

### What is your public website URL? (or attach your complete example)

http://axas-welt.de/

### What is your TestCafe test code?

```
import { Selector } from 'testcafe';

fixture`Getting Started`
    .page`http://axas-welt.de/`;
    

test('My first test', async t => {
   await t
   .typeText("#myId", "Hallo")
});

### Your complete configuration file

```
{
    "browsers": "chrome",
    "selectorTimeout": 45000,
    "assertionTimeout": 45000,
    "pageLoadTimeout": 45000,
    "screenshots": {
        "takeOnFails": false
    },
    "skipJsErrors": true,
    "disableHttp2": true
}

### Screenshots

![2022-03-06_15-56-13](https://user-images.githubusercontent.com/47175747/156929249-5c4bcd56-7647-411c-a52c-22683e69590b.png)

![2022-03-06_17-09-28](https://user-images.githubusercontent.com/47175747/156991311-ce2a6752-5636-47f7-9731-2ad1b3fe6cf0.png)

### Steps to Reproduce

1.  Execute Test  

### TestCafe version

1.18.4

### Node.js version

v16.14.0

### Command-line arguments

testcafe test.ts

### Browser name(s) and version(s)

Chrome

### Platform(s) and version(s)

Windows

### Other

As workaround i changed the for loop with skipping the deletion of the attribute

```
function cleanAttributes(wrapper) {
	    if (wrapper.length) {
	        for (var i = 0; i < wrapper.length; i++) {
		if(wrapper[i].name == "length")
		{					
                    continue;
		}
	            delete wrapper[wrapper[i].name];
	            delete wrapper[i];
	        }
	    }
	}

**Comment by Artem-Babich** [comment]
We will close this issue since it is fixed in the [Native Automation mode](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode). Please try the native automation mode in your tests.
Feel free to reopen the issue if you need a fix for the other browsers or you cannot use Native Automation for some reason.
