### ISSUE TITLE
Failure to redirect after authentication through Okta

### ISSUE THREAD

**Issue by andrewlw89** [DevExpress/testcafe#7173]
### What is your Scenario?

I am trying to log into a web application that is using Okta oauth2 authentication.

### What is the Current behavior?

After successfully authenticating through Okta, the user is redirected back to the original login page at https://oktaqa.iloveasinsflywheel.com/#/auth/login and is not logged in.

### What is the Expected behavior?

After successfully authenticating through Okta, the user is redirected to the root of the application, the authentication token is detected, and the application redirects on to https://oktaqa.iloveasinsflywheel.com/#/home.

### What is your public website URL? (or attach your complete example)

https://oktaqa.iloveasinsflywheel.com

### What is your TestCafe test code?

Not needed. This is easily recreated using only the Hammerhead HTTP Playground.

### Steps to Reproduce

1. Navigate to https://oktaqa.iloveasinsflywheel.com/
2. Enter username and password in the correct form fields (to be sent over via email)
3. Click login button

### TestCafe version

1.17.0

### Node.js version

v12.18.4

### Command-line arguments

N/A. Suggest using the hammerhead HTTP playground.

### Browser name(s) and version(s)

Chrome 95

### Platform(s) and version(s)

macOS 11.5

**Comment by Artem-Babich** [comment]
Hi @andrewlw89,

I just tried reproducing this issue with the latest testcafe version, however, it looks like your test credentials are no longer valid. Would you please share updated credentials for testing or test this case yourself using TestCafe v2.3.0-rc.2 with the [experimental-proxyless](https://testcafe.io/documentation/404237/guides/experimental-capabilities/proxyless-mode) option enabled?
