### ISSUE TITLE
Google logins no longer work through Testcafe

### ISSUE THREAD

**Issue by adriancable** [DevExpress/testcafe#7178]
It looks like, as of a few days ago, Google has started detecting testcafe-hammerhead (or something it does) and rejecting log-in attempts. Fails on testcafe-hammerhead 17.1.17, but tested various previous versions too and have the same issue, so it does not appear to be a regression on the testcafe-hammerhead side.

To reproduce:

1. Chrome 85.0.4183.102, Mac OS X 10.15.6 but seems to happen on all Chrome versions I have been able to test with, and also Safari (but does not seem to happen every time)
2. Start testcafe-hammerhead playground
3. Enter: https://accounts.google.com
4. When prompted for user ID, enter: abc123
5. Get 'This browser or app may not be secure' warning, before even being prompted for password

Since the proxy should be invisible to the visited site, I am not sure why this now breaks (it has worked for the past 12 months). This would affect any testing that involves authenticating via Google, which is quite commonplace. Any ideas?

**UPD**:
[Sign in with a supported browser](https://support.google.com/accounts/answer/7675428?hl=en#zippy=%2Ccheck-your-privacy-settings%2Ccheck-for-security-programs%2Cturn-off-extensions-in-chrome%2Cupdate-your-browser%2Cif-you-use-a-work-computer)

**Comment by miherlosev** [comment]
Hi @adriancable,

This issue is not reproduced with combination of `testcafe@3.0.1` and the Google Chrome browser. Feel free to reopen this issue if you encounter it in other browsers.
