### ISSUE TITLE
Implement HTTP/2 support

### ISSUE THREAD

**Issue by Jeffhabs** [DevExpress/testcafe#7182]
- [x] DevExpress/testcafe-hammerhead#2706 ([DONE](https://github.com/DevExpress/testcafe-hammerhead/pull/2598))
- [x] DevExpress/testcafe#7174

### What is your Test Scenario?

According to [this](https://testcafe-discuss.devexpress.com/t/websockets-and-http-2-supported/116/4) discussion thread, HTTP/2 should be supported. I've found this to not be the case.
I've tested this by simply opening the network tab while running `TestCafeStudio` and noticing all of my requests being sent via `HTTP/1`

Here is a screenshot of my network using `TestCafe`
![image](https://user-images.githubusercontent.com/10523812/53991071-ffd02e80-40e6-11e9-9b0d-863d4f7aede3.png)

Here is a screenshot not using `TestCafe`
![image](https://user-images.githubusercontent.com/10523812/53991221-59d0f400-40e7-11e9-895a-f9f5c5c8d018.png)

Seems the hammerhead url proxy translates my http/2 requests to http/1?

### What are you suggesting?

I suggest either adding HTTP/2 support, or clearly specify that HTTP/2 is not supported. Can someone at TestCafe confirm this?

### What alternatives have you considered?

N/A

### Additional context
The web application I am testing is live and not running in localhost.

**Comment by miherlosev** [comment]
Implemented in https://github.com/DevExpress/testcafe-hammerhead/issues/2706
