### ISSUE TITLE
Creating videos creates memory-leak warning on the 11th test in testcafe docker image testcafe:1.20.0

### ISSUE THREAD

**Issue by GeorgZentgraf** [DevExpress/testcafe#7188]
### What is your Scenario?

Running multiple tests and recording videos for each

### What is the Current behavior?

the 11th test throws a MaxListenersExceededWarning

(node:19) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 Page.screencastFrame listeners added to [Chrome]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)

### What is the Expected behavior?

there should be no MaxListenersExceededWarning, after any number of tests

as of docker image version 1.19.0 no warning was thrown, so something might have changed in the amount of Page.screencastFrame listener that are registered

### What is your public website URL? (or attach your complete example)

https://github.com/GeorgZentgraf/testcafe-bug

### What is your TestCafe test code?

see [test.spec.ts](https://github.com/GeorgZentgraf/testcafe-bug/blob/main/test.spec.ts) 

### Your complete configuration file

[.testcaferc.json](https://github.com/GeorgZentgraf/testcafe-bug/blob/main/.testcaferc.json)

### Your complete test report

docker run test
 Running tests in:
 - Chrome 103.0.5060.114 / Alpine Linux 3.17_alpha20220715

 Getting Started
 ✓ 1
 ✓ 2
 ✓ 3
 ✓ 4
 ✓ 5
 ✓ 6
 ✓ 7
 ✓ 8
 ✓ 9
 ✓ 10
(node:19) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 Page.screencastFrame listeners added to [Chrome]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
 ✓ 11
 ✓ 12

### Steps to Reproduce

1. (install docker desktop)
2. clone [repo](https://github.com/GeorgZentgraf/testcafe-bug)
4. run `docker build . -t test`
5. run `docker run test`

### TestCafe version

docker image testcafe/testcafe:1.20.0

### Command-line arguments

default from testcafe docker image

### Browser name(s) and version(s)

Chrome 103.0.5060.114

### Other

The warning doen't show, when using the testcafe image version 1.19.0
Might be related to #7047

**Comment by miherlosev** [comment]
Hi @GeorgZentgraf 

Thank you for the shared information. I've reproduced the issue.

**Comment by pschmolke** [comment]
I still get this warning / memory leak on 10 concurrent tests inside a custom docker container

**Comment by Artem-Babich** [comment]
Hi, @pschmolke !
The memory leak issue should already be fixed. Would you please share an example that illustrates the behavior on your side?

**Comment by pschmolke** [comment]
Yes sure,
I have created my own docker image to test the current projects frontend. It is based on `alpine linux`.

I have a directory for tests that can run concurrently and ones that cannot.
I use job control to launch the tests in both directories simultaneously. 

The output and cli param can be seen below:
```
+ npx testcafe --no-color 'chromium:headless:width=1800;height=1000' src/tests/smoke/parallel/ --concurrency 9 --quarantine-mode attemptLimit=3,successThreshold=1 --reporter xunit-gitlab-fork:xunit_smoke_parallel_report.xml,spec
+ npx testcafe --no-color 'chromium:headless:width=1800;height=1000' src/tests/smoke/sequential/ --concurrency 1 --reporter xunit-gitlab-fork:xunit_smoke_sequential_report.xml,spec
+ wait
⠹
The "browsers" option from the configuration file will be ignored.
(node:86) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [BrowserSet]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
 Running tests in:
 - Chrome 102.0.5005.173 / Alpine Linux 3.16.0
 ```

**Comment by miherlosev** [comment]
Hi @pschmolke

Thank you for the information. I reproduced the issue.

For the team: use the example from the description to reproduce the issue by adding the `concurrency 4` option.
