### ISSUE TITLE
Videos in 1.20 concurrent and several tests 

### ISSUE THREAD

**Issue by zoe-jobson-IL** [DevExpress/testcafe#7189]
### What is your Scenario?

run 40ish tests concurrently on the testcafe docker image (or locally on my laptop) with videos enabled in testcafe 1.20.0, some tests takes seconds a few take minutes.

### What is the Current behavior?

When multiple tests are run concurrently or in sequence with videos on the first set (or test) run have videos as expected but as runs go on later videos start starting with the tail end of a previous test and loosing the tail end of the test that the file name refers to so we can't tie up the last few seconds of failing tests. We have a couple of longer running tests that tend to happen in the middle of the test run, currently they are getting chopped up into peices (one got split into 9.5 videos (the last one suddenly switching to the end of another test (not the one it should have been)

### What is the Expected behavior?

Videos should all match the test they belong to and should be complete

### What is your public website URL? (or attach your complete example)

irrelevant

### What is your TestCafe test code?

we have a complex system of 40 ish tests with structured test code.
I could produce comparative videos if this will help

### Steps to Reproduce

Run a number of tests in sequence or concurrently (if concurrent should be > 2 per 'runner)
look through videos
note later ones start with end of previous one

### TestCafe version

1.20.0

### Node.js version

16.14.2

### Command-line arguments

irrelevant (we have a series of configuration js

### Browser name(s) and version(s)

Chrome Version 103.0.5060.134 (Official Build) (64-bit)

### Platform(s) and version(s)

alpine (testcafe docker image) and windows 11

**Comment by miherlosev** [comment]
Hi @zoe-jobson-IL,

It seems to be similar to the issue in [https://github.com/DevExpress/testcafe/issues/7188](https://github.com/DevExpress/testcafe/issues/7188). Try to check if this problem is resolved after the [https://github.com/DevExpress/testcafe/issues/7188](https://github.com/DevExpress/testcafe/issues/7188) issue is fixed.
