### ISSUE TITLE
Error in Role initializer - Role cannot be switched while another role is being initialized.

### ISSUE THREAD

**Issue by kajalk3010** [DevExpress/testcafe#7204]
### What is your Scenario?

The error is intermittent when running in the pipeline. Initially we were running with concurrency 4 and never had this issue cropped up. We have tried with concurrency set to 1 as well but no help Before initialising the role used await t.useRole(Role.anonymous());

So that the user is logged out internally before taking another role. However the problem still persist. Also we have added skip js errors But still the problem exists.

testcafe versions : 1.17.1

### What is the Current behavior?

It is failing in azure pipeline and saying 

**- Error in Role initializer -
Role cannot be switched while another role is being initialized.**

### What is the Expected behavior?

This was working perfectly still last month. 

### What is your public website URL? (or attach your complete example)

This isn't issue with application, may be testcafe behavior has changed. 

### What is your TestCafe test code?

import { ROLES } from "../conf"
import { Role, Selector } from "testcafe";
import testdata from "../testdata.json";

export async function signOut(t: TestController) {
  await t.click(Selector('[data-testid="navigation--logOut-button"]'));
}

export async function signIn(t: TestController, userName: string) {
  const userFirstnameLastname = `${userName}-firstnamelastname`;
  t.ctx.assessor = testdata[`${userFirstnameLastname}`];
  const role = ROLES[userName];

  if (!role) {
    throw new Error(
      `The role '${userName}' does not exist. Existing roles: ${Object.keys(
        ROLES
      ).join(", ")}`
    );
  }
  await t.useRole(Role.anonymous());
  await t.wait(2000);
  await t.useRole(role);
}

### Your complete configuration file

const createTestCafe = require("gherkin-testcafe");
const selfSignedSertificate = require("openssl-self-signed-certificate");
const ip = require("ip");
const path = require("path");
const startsWith = require("lodash/startsWith");
const getTags = require("./util/prompts/getTags");
const { setupCli } = require("./helpers");
const sql = require("mssql");
const fs = require("fs");
const testdata = require(`./testdata.json`);
const environment = testdata["environment"];
const dbserver = testdata["db-server"].replace(/{environment}/g, environment);
const database = testdata["db-database"];
const { Role } = require("testcafe");
const { askForCredentials } = require("./util/prompts/askForCredentials");
const { fillInLoginForm } = require("./common/interactions/fillInLoginForm");

const { AzureSecrets } = require("artio-qa-ui-library/lib/common/extractAzureSecrets");
const backupTestData = JSON.stringify(testdata, null, 2);
let azureSecrets = new AzureSecrets();

azureSecrets.replaceTestDataValues(testdata).then((testdataWithAzureSecrets) => {
  fs.writeFileSync('testdata.json', JSON.stringify(testdataWithAzureSecrets, null, 2));
  let dbpassword = "";
  let dbusername = "";

  if (environment.toLowerCase() === 'pdn') {
    dbusername = "xxx"
    dbpassword = testdata["xxx"];
  }
  else {
    dbusername = testdata["xx"].replace(/{environment}/g, environment);
    dbpassword = testdata["xxx-{env}-sqlsrv01".replace(/{env}/g, environment)];
  }

  const dbConfig = {
    user: dbusername,
    password: dbpassword,
    server: dbserver,
    database: database,
    options: {
      "enableArithAbort": true,
      "trustServerCertificate": true
    }
  };

  let runner = null;
  let testcafe = null;
  let hostRunner = "localhost";
  const { ScriptElementKindModifier } = require("typescript");

  const args = setupCli();
  const {
    src,
    selectorTimeout,
    assertionTimeout,
    pageLoadTimeout,
    defaultuser,
    suppliersourcinguser,    
    concurrent: concurrency,
    slabUserName,
    slabAccessKey,
    slabHost,
    host,
    tags: tagsToRun,
    localrun: localRun,
    headless,
    speed,
    browser,
    debug: debugOnFail

  } = args;

  const sslOptions = startsWith(host, "https")
    ? {
      key: selfSignedSertificate.key,
      cert: selfSignedSertificate.cert
    }
    : null;

  // Use the correct browser if not specified on the command line
  const browserList = [getBrowser(localRun, headless)];

  setupSauceLabEnvironmentVariables(localRun);
  const USERS = {
    defaultuser,
    suppliersourcinguser   
  }

  const ROLES = {};
  let user
  // Create roles for all users
  Object.keys(USERS).forEach(roleKey => {
    const role = Role(host, async t => {
      if (isInteractive) {
        user = await askForCredentials();
      } else {
        user = USERS[roleKey];
      }
      return fillInLoginForm(t, user)
    });
    ROLES[roleKey] = role;
  });

  function getBrowser(localRun, headless) {
    if (!localRun) {
      console.log(`Browser connection string is: ${browser}`);
      return `${browser}`;
    }

    if (!headless) {
      console.log(`Browser connection string is: ${browser} --allow-insecure-localhost`);
      return `${browser} --allow-insecure-localhost`;
    }

    console.log(`Browser connection string is:${browser}:headless --allow-insecure-localhost`);
    return `${browser}:headless --allow-insecure-localhost`;
  }

  function setupSauceLabEnvironmentVariables(localRun) {
    if (!localRun) {
      var sauceConfigFileLocation = null;
      if (browser.toLowerCase().includes("chrome")) {
        sauceConfigFileLocation = "./sauceLabsConfig/chrome.json"; // Linux path, change for Windows test execution
      } else if (browser.toLowerCase().includes("firefox")) {
        sauceConfigFileLocation = "./sauceLabsConfig/firefox.json"; // Linux path, change for Windows test execution
      } else if (browser.toLowerCase().includes("ie")) {
        sauceConfigFileLocation = "./sauceLabsConfig/ie.json"; // Linux path, change for Windows test execution
      } else if (browser.toLowerCase().includes("ipad")) {
        sauceConfigFileLocation = "./sauceLabsConfig/ipad.json"; // Linux path, change for Windows test execution
      } else if (browser.toLowerCase().includes("samsung")) {
        sauceConfigFileLocation = "./sauceLabsConfig/android.json"; // Linux path, change for Windows test execution
      }

      if (sauceConfigFileLocation !== null) {
        var sauceConfig = fs.readFileSync(sauceConfigFileLocation);
        console.log("Sauce Labs config is: " + sauceConfig);
        process.env.SAUCE_CAPABILITIES_OVERRIDES_PATH = sauceConfigFileLocation;
      }
      process.env.SAUCE_USERNAME = slabUserName;
      process.env.SAUCE_ACCESS_KEY = slabAccessKey;
      process.env.SAUCE_API_HOST = slabHost;
      //process.env.SAUCE_CONNECTOR_CONFIG_PATH = 'C:/temp/sconfig.txt'
      hostRunner = ip.address();
      console.log("Sauce Labs username is: " + Boolean(args.slabUserName));
      console.log("Sauce Labs accesskey is: " + Boolean(args.slabAccessKey));
      console.log("Sauce Labs api host is: " + Boolean(args.slabHost));
      console.log("Host runner IP is: " + hostRunner);
    }
  }

  (async function startUp() {
    process.env.executionEnvironment = args.e;
    const tags = await getTags(tagsToRun, isInteractive);
    const tc = await createTestCafe(hostRunner, 1337, 1338, sslOptions);
    testcafe = tc;
    runner = testcafe.createRunner();
    const result = await runner
      .tags(tags)
      .src(src)
      .browsers(browserList)
      .reporter([
        "spec",
        {
          name: "nunit3",
          output: "reports/report.xml"
        }
      ])
      .screenshots(
        "reports/screenshots/",
        true,
        "${DATE}_${TIME}/test-${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.png"
      )
      .video('reports/videos/',
        {
          failedOnly: true,
          pathPattern: '${DATE}_${TIME}/test-${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.mp4'
        })
      .compilerOptions(
        {
          typescript:
          {
            configPath: "./tsconfig.json"
          }
        }
      )
      .run({
        debugOnFail,
        selectorTimeout: 90000,
        assertionTimeout: 90000,
        pageLoadTimeout: 90000,
        concurrency: 2,
        speed,
        skipJsErrors: true,
        skipUncaughtErrors: true,
        quarantineMode: {
          successThreshold: 1,
          attemptLimit: 2
        }
      });
    console[result ? "error" : "log"](`Completed test run with ${result} failure(s)`);
    testcafe.close().then(() => {
      if (backupTestData != null)
        fs.writeFileSync('testdata.json', backupTestData);
    });
  })();

  // Export
  module.exports = {
    host,
    ROLES,
    dbConfig
  };

});

### Screenshots

<img width="484" alt="RoleInitializer" src="https://user-images.githubusercontent.com/45262066/181289249-2349eecb-df1d-4882-89f2-8b2147d850f7.PNG">

### Steps to Reproduce

1.Try login with different users
2.
3.

### TestCafe version

1.17.1

### Node.js version

v16.15.0

### Command-line arguments

node conf.js --headless false --host https://dev.com --tags @current

### Browser name(s) and version(s)

Chrome 103

**Comment by AlexKamaev** [comment]
I inspected your code and it looks correct. Please try to update your TestCafe to the latest version. If this does not help, share a working project with us or create a sample that demonstrates the issue. If you cannot share your project here, you can send it to [support@devexpress.com](mailto:support@devexpress.com).
