### ISSUE TITLE
Stucked at login page after session expires

### ISSUE THREAD

**Issue by Oraclesports** [DevExpress/testcafe#7212]
### What is your Scenario?

Using `t.useRoles` method - https://testcafe.io/documentation/402845/guides/advanced-guides/authentication#how-roles-work

Upon the first login and first hour - the fixtures have no issues.
After one hour, the session expires and the subsequent tests begin failing at the login page.

My workaround is to use a manual login but it increases the duration of the test.
Is there a way to renew the session or perform a logout periodically?
I have tried using await t.useRole(Role.anonymous()); previously afterEach test but it didn't seem to work.

### What is the Current behavior?

Stuck at login page

### What is the Expected behavior?

Refreshes behavior. For example, perform a manual login instead of using a useRole mechanism

### What is your TestCafe test code?

```
export interface IUser extends ILoginArgs {
    role: Role;
}

interface ILoginArgs{
    username: string;
    password?: string;
}

class RolesBuilder {

    public readonly readonly_admin: IUser = this.buildUser('readonly-admin');

    public useRole(loginArgs: ILoginArgs): Role {
        return Role(prep.defaults.url, async t => {
            await this.authenticateUser(loginArgs);
            await this.model.layout.postUseRoleSuccess();
        });
    }
  
   private authenticateUser(args): Role {
      //authenticate user
   }

    private buildUser(username: string, password: string = this.DefaultPassword): IUser {
        return {
            username: username,
            role: this.useRole({
                username,
                password,
            }),
        };
    }
}

export default new RolesBuilder();
```
Under the test
```
fixture('Fixture 1')
    .page(config.console)
    .beforeEach(async t => {
        await t.useRole(roles.readonly_admin.role);
    });
```

### Your complete configuration file

module.exports = {
  skipJsErrors: true,
  disablePageCaching: true,
  }

### TestCafe version

1.20.0

### Command-line arguments

testcafe chrome

**Comment by miherlosev** [comment]
Hi @Oraclesports,

At present, the `Role` cannot be reinitialized. It breaks scenarios when the user session expires.
You can try some workarounds:

* setup your test application so that the user session does not expire during the test run
* write a wrapper around the `t.useRole` method that will refresh `Role` when necessary (see example [here](https://github.com/DevExpress/testcafe/issues/5351#issuecomment-850448884))

**Comment by slaydenriley** [comment]
We have this exact same issue, it starts happening after 1 hr. We'll go ahead and attempt the suggested workaround, though it will get messy, considering we use around 20 unique `Role`s.
