### ISSUE TITLE
Mocking API errors doesn't work in 1.20.0

### ISSUE THREAD

**Issue by sorin-davidoi** [DevExpress/testcafe#7213]
### What is your Scenario?

Use `RequestMock` to mock API errors (status code != 200).

### What is the Current behavior?

TestCafe throws `An unhandled error occurred in the "onResponse" method of the "RequestMock" class: null`.

### What is the Expected behavior?

The request should be mocked and no error thrown. This used to work in 1.19.0.

### What is your public website URL? (or attach your complete example)

https://testcafe.io

### What is your TestCafe test code?

```typescript
import { RequestMock, t } from 'testcafe';

fixture`Demo`;

test
    .page('https://testcafe.io')
    .requestHooks(
        RequestMock()
            .onRequestTo(/d/)
            .respond('', 500)
    )
    ('should pass', async () => {
        await t.wait(1000);
    });
```

### Your complete test report

```
Demo
 ✖ should pass

   1) An unhandled error occurred in the "onResponse" method of the "RequestMock" class:
      
      null

      Browser: Firefox 102.0 / Linux 0.0
```

### Steps to Reproduce

1. Install testcafe@1.20.0
2. Run `testcafe firefox:headless test.ts`, observe failure
3. Run with testcafe@1.19.0, observe that the test passes

### TestCafe version

1.20.0

### Node.js version

v16.14.0

### Command-line arguments

testcafe firefox:headless test.ts

### Browser name(s) and version(s)

Firefox 102

### Platform(s) and version(s)

Fedora 36

### Other

Works in 1.19.0.

**Comment by Aleksey28** [comment]
Hi @sorin-davidoi,

I reproduced the issue. We will update this thread once we have news.
