### ISSUE TITLE
Resize of Browser on Ubuntu failed

### ISSUE THREAD

**Issue by ognif** [DevExpress/testcafe#7214]
### What is your Scenario?

Starting testcafe test suite. I use an resize window function but I cannot figure out if this is a problem.
```
  await t.useRole(smTester);
  await t
    .navigateTo(
      "https://xxx"
    )
    .resizeWindow(1280, 800);
```

### What is the Current behavior?

  --
0|Worker server 1  |   Was unable to resize the window due to an error.
0|Worker server 1  |   The /home/developer/devel_bot/clipcafebot/node_modules/testcafe-browser-tools/bin/linux/glibc-64/resize process failed with the 1 exit code.

This happens not always, just after some test stuites were started. Before the resize works well.

### What is the Expected behavior?

Resize have to work stable

### What is your public website URL? (or attach your complete example)

None

### What is your TestCafe test code?

  await t.useRole(smTester);
  await t
    .navigateTo(
      "xxx"
    )
    .resizeWindow(1280, 800);

### Steps to Reproduce

Run a test with resize

### TestCafe version

1.20

### Node.js version

16.16

### Command-line arguments

none

### Browser name(s) and version(s)

Chrome 103.0.5060.134

### Platform(s) and version(s)

Ubuntu 21.10

**Comment by felis2803** [comment]
Hi @ognif

I could not reproduce the bug according to the description that you provided. Apparently something is missing. It would be great if you made an example for us that reproduces the behavior you specified, and which we could explore on our side.
