### ISSUE TITLE
Intermittent Node EPIPE exceptions when video recording is on

### ISSUE THREAD

**Issue by VasilyStrelyaev** [DevExpress/testcafe#7216]
### What is your Scenario?

I run my tests with video recording enabled.

### What is the Current behavior?

I get intermittent errors like:

<img width="931" alt="изображение" src="https://user-images.githubusercontent.com/11459924/182605655-9553f2c3-93e7-4706-9096-5007f2760b25.png">

They are not thrown if I disable video recording.

### What is the Expected behavior?

No errors appear.

### What is your public website URL? (or attach your complete example)

See **Steps to Reproduce**.

### What is your TestCafe test code?

See **Steps to Reproduce**.

### Steps to Reproduce

Team members can see the steps here: https://devexpress-my.sharepoint.com/:w:/p/vasily_strelyaev/EfM8qhSSyt1AoxImRERf4qQBDQFY9OVSKBYGHVvJMghV2g?e=VSu6yu

### TestCafe version

1.20.0

### Node.js version

16.15.1

### Command-line arguments

See **Steps to Reproduce**.

**Comment by miherlosev** [comment]
I've reproduced the issue with Node.js `16.15.0`.

![image](https://user-images.githubusercontent.com/4133518/182619191-bdb184d7-ab70-4fdb-9fc4-2ad57d7d9936.png)
![image](https://user-images.githubusercontent.com/4133518/182619465-d0befab3-9fa5-453f-922a-3ab695713043.png)

**Comment by miherlosev** [comment]
The issue is reproduced in Mac OS with `testcafe@1.20-rc.2` with another error:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/4133518/183081263-c4bb6c20-eb0a-451e-aaa7-5e77c8f9a2d3.png)
