### ISSUE TITLE
Status bar does not disappear on hover

### ISSUE THREAD

**Issue by felis2803** [DevExpress/testcafe#7217]
### What is your Scenario?

In live mode, I hover over the status bar.

### What is the Current behavior?

The status bar does not disappear.

### What is the Expected behavior?

The status bar should disappear.

### What is your public website URL? (or attach your complete example)

See issue https://github.com/DevExpress/testcafe-studio/issues/4266.

### What is your TestCafe test code?

See issue https://github.com/DevExpress/testcafe-studio/issues/4266.

### Steps to Reproduce

1. Create a test as in [DevExpress/testcafe-studio#4266](https://github.com/DevExpress/testcafe-studio/issues/4266).
2. Run it in live mode.
3. Hover over the status bar.

### TestCafe version

1.20.0

### Node.js version

18.5.0

### Command-line arguments

`testcafe chrome -L test.js`

### Browser name(s) and version(s)

Chrome@103.0.5060.134

### Platform(s) and version(s)

Windows 10

**Comment by Aleksey28** [comment]
I didn't manage to reproduce the issue by following your description. Please check the issue again.
