### ISSUE TITLE
Provide an arm version of the Docker container

### ISSUE THREAD

**Issue by kojoru** [DevExpress/testcafe#7219]
### What is your Scenario?

I'd like to run the testcafe docker containers natively on m1 Macs and arm-based cloud hostings.

### What are you suggesting?

An arm64 version of a docker container that would work exactly the same way. Currently the container is amd64-only.

**Comment by miherlosev** [comment]
Hi @kojoru,

Thank you for pointing out this enhancement.

**Comment by danieltroger** [comment]
I'd also love this. I was struggling to get the Docker version running on my M1 laptop and always have to let my colleague run it on his intel mac right now

**Comment by carltheperson** [comment]
An arm version would be super nice

**Comment by kojoru** [comment]
@AlexKamaev so you also wouldn't accept it as a pull request, correct?

**Comment by AlexKamaev** [comment]
Yes, that's correct. We are not ready to maintain multiple docker images.
