### ISSUE TITLE
Remove the testcafe-reporter-dashboard dependency

### ISSUE THREAD

**Issue by thibaudszy** [DevExpress/testcafe#7220]
### What is your Scenario?

We ([Adyen](https://www.adyen.com/)) would like to update Testcafe to the latest version. However, we currently cannot do that because the source code for `testcafe-reporter-dashboard@1.0.0-rc.3` is not available. For security reason, we cannot use dependencies for which the source code is not available. 

### What are you suggesting?

The `testcafe-reporter-dashboard@1.0.0-rc.3` is added as a dependency but does not seem to be used in the project. Removing it would solve the security issue for us and reduce the bundle size. 

### What alternatives have you considered?

If it is used in the project, are there any blockers to open sourcing it?

**Comment by miherlosev** [comment]
Hi @thibaudszy,

We will discuss it with the team if we can we make the `testcafe-reporter-dashboard` repository public.

> For security reason, we cannot use dependencies for which the source code is not available.

This repository can be audited using the `npm audit` command. The code of the installed module is not obfuscated. So, you can understand its logic.
Could you please clarify why you need the source code of the repository?

**Comment by thibaudszy** [comment]
Hi @miherlosev 

Thanks for considering open sourcing it. We tend to follow best practices in the OSS community and security regarding NPM packages. Which is why we always check that the source code of every package we use has its source code in a public repository. 

If this is not an option, would it be possible to load the `testcafe-reporter-dashboard` as an optional dependency (similar to what is done for [vscode](https://github.com/microsoft/vscode/blob/389938998fa2ca900f9730839c2ee8c90ae0a68c/package.json#L224))? My understanding is that it is used by the users of the [TestCafe dashboard](https://testcafe.io/403442/resources/blog/2021-10-7-dashboard-alpha-invitation-announce#header) which is currently in alpha. Or would this create issues for the project in general?

**Comment by miherlosev** [comment]
We decided to make the `testcafe-reporter-dashboard` repository public. We are going to do that in one of the next development sprints.

**Comment by thibaudszy** [comment]
That's great news. Thank you for addressing our issue.

**Comment by miherlosev** [comment]
https://github.com/DevExpress/testcafe/issues/7220

The [testcafe-reporter-dashboard](https://github.com/devexpress/testcafe-reporter-dashboard) repository became public.
