### ISSUE TITLE
Some API's are failing with TestCafe framework due to which data is not rendering on UI

### ISSUE THREAD

**Issue by shaheemanjum** [DevExpress/testcafe#7223]
### File a new question on StackOverflow

https://stackoverflow.com/questions/73288615/some-apis-are-failing-with-testcafe-framework-due-to-which-data-is-not-renderin

**Comment by shaheemanjum** [comment]
Hi @Aleksey28  , 
When i click on button with testcafe ,  data is not rendering for a particular section. Please find below screenshot.
![image](https://user-images.githubusercontent.com/88390841/183844073-86baa8c3-5478-4fd5-8762-bcbee7d88d21.png)

But manually it is working fine :PFA scrrenshot:

![image](https://user-images.githubusercontent.com/88390841/183844337-2cc24e7a-9ca1-4c2e-b20f-1e1a522cc1de.png)

.When i inspected the screen , I found that a particular API is failing everytime with testcafe .PFA screenshot:

![image](https://user-images.githubusercontent.com/88390841/183844639-e15aaf0f-4c4b-4130-b594-1301cc437e62.png)

I think it is related to HammerHead.js  but i am not sure coz other API are passing .

**Comment by Aleksey28** [comment]
Hi @shaheemanjum,

It's difficult to research a problem based only on screenshots. Please share a simple sample, which I can reproduce locally. You can follow this instruction: [https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue](https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue).

**Comment by shaheemanjum** [comment]
Hi @Aleksey28 ,

I can not share the repo as access is restricted. Can you please tell me any other way to resolve this.
with testcafe Below API call is failing with **Hammerhead.js** whereas other API is passing .

![image](https://user-images.githubusercontent.com/88390841/184131538-193eed44-0560-4849-9b55-a953317b6d2e.png)

**Comment by Aleksey28** [comment]
You don't need to share the whole repo. Just create a simple sample as described here: [https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue](https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue)

**Comment by shaheemanjum** [comment]
No Its not resolved yet.
Quick question -
1. Can we bypass the Hammerhead.js proxy . cause i think the issue is related to hammerhead.?
2. Can i send you guys a video recording of my issue ?

**Comment by Aleksey28** [comment]
1. Proxyless mode hasn't been implemented yet. We will announce it once we implement it.
2. We cannot find the cause of the issue without a simple example (see how to create it [https://testcafe.io/402636/faq?search#how-to-create-a-minimal-working-example-when-you-submit-an-issue](https://testcafe.io/402636/faq?search#how-to-create-a-minimal-working-example-when-you-submit-an-issue)). Feel free to reopen this issue if you can create such an example.

**Comment by shaheemanjum** [comment]
Hi @Aleksey28  , 

Can i upload a video o my flow ?
As i am not able to understand what is the sample example.

**Comment by Aleksey28** [comment]
Hi @shaheemanjum,

A sample example is a minimal reproducible example that I can run locally. It will allow me to research the problem (see how to create it here: [https://testcafe.io/402636/faq?search#how-to-create-a-minimal-working-example-when-you-submit-an-issue](https://testcafe.io/402636/faq?search#how-to-create-a-minimal-working-example-when-you-submit-an-issue)).
