### ISSUE TITLE
Timeout reporting enhancements

### ISSUE THREAD

**Issue by JESii** [DevExpress/testcafe#7226]
### What is your Scenario?

I have found that we frequently have failures trying to load the multiple graphs that we are displaying on the pages -- often (I think) because of page-load timeouts, but the problem is I don't know if a timeout was what triggered the failure and, if so, exactly which timeout was the triggering event.

Even though I'm pretty sure the failure was caused by a timeout (e.g., I see a spinner on the page we were trying to load), the error I get is along the lines of "Unable to locate client name..." or "expected false to be truthy".

### What are you suggesting?

I'd like to see a message in the results showing if a timeout was triggered and which timeout it was. It might be something like:
```
Error message
❌ TimeoutError: ERROR: pageLoadsTimeout exceeded 6000ms
❌ AssertionError: ERROR: Unable to locate client name: expected false to be truthy
```
or something similar.

### What alternatives have you considered?

None... it's all a manual process of reviewing the failure image to see if there's a spinner at which point I don't worry about it -- unless, of course, there are many such failures.

### Additional context

None

**Comment by Dmitry-Ostashev** [comment]
TestCafe waits for the `window.load` event after the `DOMContentLoaded` event. Probably, these events are raised, and the spinner on your page is not related to them. Have you tried increasing the [pageLoadTimeout](https://testcafe.io/documentation/402638/reference/configuration-file#pageloadtimeout) value? If your spinner just shows graph loading on the page, you can use an additional assertion, for example, the following one:

```
await t.expect(Selector('.spinner').visible).notOk()
```

Also, you can attach a simple project example or send us a public page URL so that we can better understand your usage scenario.

**Comment by JESii** [comment]
Wish I could send you the URL, but it's a private website for a client of mine.
Yes, I have increased the pageLoadTimeout value, along with every timeout value I saw.
What I'd like to see -- along with the specific error which is reported already -- is:
1) Was this error triggered following a timeout
2) If yes, what was the specific timeout that was exceeded

thanks much...

**Comment by Aleksey28** [comment]
Hi @JESii,

To resolve the issue, we need to find its cause. However it's difficult without researching your project on our side.

We will be happy to research the problem further, but we’ll need access to this website. Please ask the website owner to send written confirmation to [support@devexpress.com](mailto:support@devexpress.com). It must permit DevExpress personnel to remotely access the website and its internal resources for research, testing, and debugging purposes.

Alternatively, please follow these instructions to create a simple example: [https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue](https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue).

**Comment by JESii** [comment]
Thanks… I’ll see if I can get permission to do that or figure out a way to get you a working sample!

…Jon
Stay safe; be well

Jon Seidel, CMC®

**Comment by JESii** [comment]
OK; I figured out what the problem was: TestCafe was not able to find the configuration file and was using the default timeout values which were not long enough. At the end of the day, I believe it was the pageLoadTimeout that was the issue.
We worked around this problem by specifying longer timeout values on the command-line. Our TC scripts run in a docker environment:
This is the shell script we use to run the tests: `make run` for a single test; `make run_m` for the full test run, and `make run_test` for one-off testing:
```
## ********** General Variables ********** #
# Set first argument for local makefile variable
arg1 := $(word 1,$(MAKECMDGOALS))
# Set Directory path and makefile path as makefile variables
mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
root_dir := $(dir $(mkfile_path))

TCPORT1=1337
TCPORT2=1338
TEST_SUITE= /path/to/file/testfile1.js 
ifneq (,$(wildcard ${root_dir}/.env.docker))
    include .env.docker
    export
endif

# TestCafe default timeout values are: --selector-timeout=10000 --assertion-timout=3000 --page-load-timeout=3000 
# Our TestCafe default timeout values are in .testcaferc.json
# ... and includes 'takeOnFails true'

run:
	docker run --rm --env-file .env.docker \
	  -p ${TCPORT1}:1337 \
	  -p ${TCPORT2}:1338 \
	  -v ${root_dir}:/app \
	  -v ${root_dir}src:/src \
	  -v ${root_dir}/results:/results \
	  -i testcafe/testcafe \
	  chromium:headless --hostname=localhost ${TEST_SUITE} -s path=results/screenshots -S --reporter nunit3:results/report.xml

run_test:
	docker run --rm --env-file .env.docker \
	  -p ${TCPORT1}:1337 \
	  -p ${TCPORT2}:1338 \
	  -v ${root_dir}:/app \
	  -v ${root_dir}src:/src \
	  -v ${root_dir}/results:/results \
	  -i testcafe/testcafe \
	  chromium:headless --hostname=localhost ${TEST_SUITE} -s path=results/screenshots -S --reporter nunit3:results/report.xml

run_m:
	{ docker run --rm --env-file .env.docker --name <testName> \
	  -p 1337:1337 \
	  -p 1338:1338 \
	  -v ${root_dir}:/app \
	  -v ${root_dir}src:/src \
	  -v ${root_dir}/results:/results \
	  -i testcafe/testcafe \
	  chromium:headless --hostname=localhost /path/to/file/testfile1.js -s path=results/<testName>/screenshots -S --reporter nunit3:results/<testName>/report.xml; } &
	{ docker run --rm --env-file .env.docker --name <testName> \
	  -p 1339:1337 \
	  -p 1340:1338 \
	  -v ${root_dir}:/app \
	  -v ${root_dir}src:/src \
	  -v ${root_dir}/results:/results \
	  -i testcafe/testcafe \
	  chromium:headless  --hostname=localhost /path/to/file/testfile1.js -s path=results/<testName>/screenshots -S --reporter nunit3:results/<testName>/report.xml; } &
	{ docker run --rm --env-file .env.docker --name <testName> \
	  -p 1341:1337 \
	  -p 1342:1338 \
	  -v ${root_dir}:/app \
	  -v ${root_dir}src:/src \
	  -v ${root_dir}/results:/results \
	  -i testcafe/testcafe \
	  chromium:headless  --hostname=localhost /path/to/file/testfile1.js-s path=results/<testName>/screenshots -S --reporter nunit3:results/<testName>/report.xml; } &
	{ docker run --rm --env-file .env.docker --name <testName> \
	  -p 1343:1337 \
	  -p 1344:1338 \
	  -v ${root_dir}:/app \
	  -v ${root_dir}src:/src \
	  -v ${root_dir}/results:/results \
	  -i testcafe/testcafe \
	  chromium:headless  --hostname=localhost /path/to/file/testfile1.js -s path=results/<testName>/screenshots -S --reporter nunit3:results/<testName>/report.xml; } &

tc:
	yarn test:tc:ci
```
This is the associated `.env.docker` file
```
TEST_URL=XXXX
LOGIN_ID=XXXX
PASSWORD=XXXX
NODE_PATH=/app/node_modules
TEST_SUITE=/path/to/file/testfile1.js
```
Here's the .testcaferc.json file; we also tried a .js version -- neither worked, even though they are in the root directory and in git.
```
{
  "screenshots": {
    "takeOnFails": true
  },
  "selectorTimeout": 20000,
  "pageLoadTimeout": 20000,
  "assertionTimeout": 20000,
  "clientScripts": [{"module": "@testing-library/dom/dist/@testing-library/dom.umd.js"}]
}
```
