### ISSUE TITLE
Support doubleClick event in replaying Chrome Recorder JSON

### ISSUE THREAD

**Issue by jecfish** [DevExpress/testcafe#7241]
### What is your Scenario?

Not able to replay JSON files with double click step

### What are you suggesting?

Support double click event in replaying Chrome Recorder json

**Comment by AlexKamaev** [comment]
https://github.com/DevExpress/testcafe/issues/7242#issuecomment-1222009978

**Comment by AlexKamaev** [comment]
fixed in https://github.com/DevExpress/testcafe/commit/fe00aa9cb090f1b2990f0d2ddbd55a6d5f691454
