### ISSUE TITLE
Support rightClick event in replaying Chrome Recorder JSON

### ISSUE THREAD

**Issue by jecfish** [DevExpress/testcafe#7242]
### What is your Scenario?

Not able to replay JSON files with right click step

### What are you suggesting?

Support right click event in replaying Chrome Recorder json

**Comment by AlexKamaev** [comment]
It looks like the Chrome Recorder introduced new features, such as 'rightClick', 'hover', and 'doubleClick'. Thank you for pointing this out. We'll consider implementing these features.

You can create a PR to support these actions. Use this file as a starting point: [https://github.com/DevExpress/testcafe/blob/master/src/compiler/test-file/formats/dev-tools/compiler.ts](https://github.com/DevExpress/testcafe/blob/master/src/compiler/test-file/formats/dev-tools/compiler.ts).

**Comment by AlexKamaev** [comment]
fixed in https://github.com/DevExpress/testcafe/commit/fe00aa9cb090f1b2990f0d2ddbd55a6d5f691454
