### ISSUE TITLE
Facility to run API tests without opening browser

### ISSUE THREAD

**Issue by jiteshsojitra** [DevExpress/testcafe#7243]
### What is your Scenario?

TestCafe is mostly used for front-end automation tool and its great. It would be great to have facility to bypass browser login and can be used as back-end automation too like mocha.

### What are you suggesting?

Same facility which TestCafe provides to end-to-end like server tests runs without opening browser window.

### What alternatives have you considered?

Mocha, Chai.

**Comment by miherlosev** [comment]
Hi @jiteshsojitra

> It would be great to have facility to bypass browser login and can be used as back-end automation too like mocha.

Could you please clarify what you mean? Mocha is not a backend automation tool. Primarily, Mocha is used for running unit tests. If by 'back-end automation' you mean the capability to send HTTP requests and assert their responses, then you can use the [t.request](https://testcafe.io/documentation/403981/reference/test-api/testcontroller/request) method right now. If you mean the capability to run unit tests in the same way as Mocha, then this feature is not yet implemented. You can track this [issue](https://github.com/DevExpress/testcafe/issues/1314) to be informed about our progress.

**Comment by jiteshsojitra** [comment]
Yes same, mark duplicate of https://github.com/DevExpress/testcafe/issues/1314 ?

**Comment by Aleksey28** [comment]
Duplicate https://github.com/DevExpress/testcafe/issues/1314
