### ISSUE TITLE
XUnit Reporter - User Agent for concurrent tests

### ISSUE THREAD

**Issue by pschmolke** [DevExpress/testcafe#7244]
### What is your Scenario?

I start a test execution with the concurrency cli option set to `7`, e.g.
`npx testcafe --no-color src/tests/parallel/ -c 7 --reporter xunit:xunit-parallel-report.xml,spec`

### What is the Current behavior?

The testsuite name inside the report concatinates (with ',') the user agent of every single test run. Which is obviously the same, because it is specified in `.testcaferc.json`. This results in a report file that shows the opening tag for the testsuite as follow:
`<testsuite name="TestCafe Tests: Chrome 102.0.5005.173 / Alpine Linux 3.16.0, Chrome 102.0.5005.173 / Alpine Linux 3.16.0, Chrome 102.0.5005.173 / Alpine Linux 3.16.0, Chrome 102.0.5005.173 / Alpine Linux 3.16.0, Chrome 102.0.5005.173 / Alpine Linux 3.16.0, Chrome 102.0.5005.173 / Alpine Linux 3.16.0, Chrome 102.0.5005.173 / Alpine Linux 3.16.0" tests="155" failures="14" skipped="0" errors="14" time="2110.331" timestamp="Mon, 22 Aug 2022 13:23:58 GMT" >` 

### What is the Expected behavior?

The Test Controller started the same user agent so I expect it to be a single entry and not 7 that are identical.

### What is your public website URL? (or attach your complete example)

n/a

### What is your TestCafe test code?

n/a

### Steps to Reproduce

1. read steps above

### TestCafe version

1.20.0

### Node.js version

v18.6.0

### Command-line arguments

see example above

### Browser name(s) and version(s)

Chrome 102

### Platform(s) and version(s)

Alpine Linux 3.16.0, Debian 5.10.127-2

**Comment by miherlosev** [comment]
Hi @pschmolke 

We displayed a list of browsers (`User Agents`) in such format for all [built-in reporters](https://testcafe.io/documentation/402825/guides/intermediate-guides/reporters?search#included-reporters). We don't have plans to change it. You can fork the XUnit reporter repository and customize it as you want.
