### ISSUE TITLE
disableMultipleWindows missing from runner.run RunOptions type definition

### ISSUE THREAD

**Issue by vlad-dargel** [DevExpress/testcafe#7245]
### What is your Scenario?

I'd like to disable Multiple Windows when running TestCafe using the API with TypeScript.

### What is the Current behavior?

TestCafe TypeScript type declarations are missing disableMultipleWindows field in the RunOptions type.

runner.run({
    disableMultipleWindows: true
});
Will result in incompatible type warning.

### What is the Expected behavior?

RunOptions should contain the disableMultipleWindows field like documented in https://testcafe.io/documentation/402841/guides/advanced-guides/multiple-browser-windows

### What is your public website URL? (or attach your complete example)

Not relevant.

### What is your TestCafe test code?

Not relevant.

### Steps to Reproduce

1. Create a new TypeScript project and install TestCafe.
2. Create a TS file for running TestCafe with the API and add.
runner.run({
    disableMultipleWindows: true
});
3. See the TS warning:
TS2345: Argument of type '{ disableMultipleWindows: boolean; }' is not assignable to parameter of type 'Partial<RunOptions>'.   Object literal may only specify known properties, and 'disableMultipleWindows' does not exist in type 'Partial<RunOptions>'.

### TestCafe version

1.14.2

### Node.js version

v16.15.1

### Command-line arguments

Not relevant.

### Browser name(s) and version(s)

Not relevant.

### Platform(s) and version(s)

Windows 10

**Comment by Aleksey28** [comment]
Hi @vlad-dargel,

Please update `testcafe` to the latest version. This definition already exists there.
