### ISSUE TITLE
Test dependencies

### ISSUE THREAD

**Issue by pschmolke** [DevExpress/testcafe#7254]
### What is your Scenario?

I would like to write some tests that are executed after one another because the first test prepares data which is used by the second test. And a third test depends on data of the second test and so on and so forth.

I could easily split them in different fixtures but that is not exactly what I want, because there are other tests that belong in this suite and I want to utilize the `concurrency` factor of the TestController. But when I do the tests are executed non-deterministic.

### What are you suggesting?

A new method, i.e. `depends()`, to the `TestObject` would be perfect, which takes the Test Name or another identifier as its argument.

**Comment by Aleksey28** [comment]
Hi @pschmolke,

The best practice is to use separate tests. Usually, all preparations are made before the tests. That is why we don't plan to work on this suggestion. Instead, I recommend using [before hooks](https://testcafe.io/documentation/403435/guides/intermediate-guides/hooks?search#hooks-before-and-after-tests).

If you cannot avoid test dependencies, you can use [`fixtureCtx`](https://testcafe.io/documentation/402701/reference/test-api/testcontroller/fixturectx). However, I strongly recommend you avoid using it in this case.
