### ISSUE TITLE
Add ability to modify a request in interceptor

### ISSUE THREAD

**Issue by creativeprogramming** [DevExpress/testcafe#7259]
### What is your Scenario?

Hi, 

We need to modify the request on certain conditions, eg. replace the request url with a pre-produticion file hosted publically

Is it possible right now?

I found that not, so I opened that ticket hoping in your attention.

Thanks

### What are you suggesting?

Having a modificable req object in the onRequest method like tools like cyperss are offering

### What alternatives have you considered?

Mocking the request response with a node-fetch fetched reply form the http file we need, but we found issues in using await in 'top-level' testcafe files

**Comment by Aleksey28** [comment]
Hi @creativeprogramming,

Yes, it is possible. You can create [`custom RequestHook`](https://testcafe.io/documentation/402842/guides/intermediate-guides/intercept-http-requests#create-a-custom-request-hook) and rewrite a path. For example:

```js
class CustomRequestHook extends RequestHooks {
  onRequest(e) {
      e.requestOptions.path = '/another-url';
  }
}
```
