### ISSUE TITLE
Update CLI description with highlights of browser providers mechanism

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#726]
I have a feeling that we need to mention browser providers here as well somehow: https://github.com/DevExpress/testcafe/blob/master/src/cli/argument-parser.js#L24

**Comment by inikulin** [comment]
ping @VasilyStrelyaev @MargaritaLoseva

**Comment by MargaritaLoseva** [comment]
I've updated this 3 hours ago in this pull request - https://github.com/DevExpress/testcafe/pull/725

**Comment by inikulin** [comment]
@MargaritaLoseva Add `closes` directive to PR name then
