### ISSUE TITLE
Allow attaching metadata to actions and client functions and accessing it in the reporter

### ISSUE THREAD

**Issue by VasilyStrelyaev** [DevExpress/testcafe#7266]
### What is your Scenario?

I would like to hide certain actions and client function calls from the test run report generated by my reporter.

### What are you suggesting?

I'm suggesting an approach where I would be able to pass custom metadata to the actions/client functions. I will pass a flag `hideFromReport: true` when I call an action or call/create a client function, then I will check this flag in the reporter and just ignore actions/client function calls with this flag.

*Note about client function skipping*: in my current scenario, I need to skip all calls to certain CFs. So, it does not matter if I will be able to pass metadata with `hideFromReport: true` when I create these functions or call them. You can choose an option you like better.

### What alternatives have you considered?

@AndreyBelym suggested maybe I would like an approach when there is a TestCafe-handled action option "do not tell the reporter". If this option is set for an action/CF, TestCafe simply does not call the reporter methods for this action.

However, I think this approach is less flexible because it only allows for skipping actions marked in the test code unconditionally. In the metadata approach, I could introduce additional conditions in the reporter.

**Comment by AndreyBelym** [comment]
Implemented an alternative approach #1535.
