### ISSUE TITLE
Event still bubbles even if the event target was deleted

### ISSUE THREAD

**Issue by AlexKamaev** [DevExpress/testcafe#7277]
### What is your Scenario?

see example

### What is the Current behavior?

see example

### What is the Expected behavior?

event should not bubble if the target was deleted

### What is your public website URL? (or attach your complete example)

```HTML
<!DOCTYPE html>
<html>
<head>
    <title>TestCafe Tests Container</title>

    <style>
        body {
            height: 400px;
            width: 400px;
            border: 1px solid black;
        }

        #container {
            display: inline-block;
            height: 200px;
            width: 200px;
            background-color: red;
        }
    </style>
</head>
<body>
<div id="container"></div>

<script>
    document.querySelector('#container').addEventListener('pointerdown', (e) => { e.target.parentNode.removeChild(e.target); });

    document.addEventListener('click', () => {
        window.bubbled = true;
    });
</script>
</body>
</html>


```

### What is your TestCafe test code?

```JS
import { Selector, ClientFunction } from 'testcafe';

fixture `Test`
    .page('./index.html');

const container = Selector('#container');
const body = Selector('body');

const isBubbled = ClientFunction(() => {
   return window.bubbled;
});

test('Test', async (t) => {
    await t.click(container);

    await t.expect(isBubbled()).notOk();
});

```

### Steps to Reproduce

see example

### TestCafe version

2.0.0

### Node.js version

does not matter

### Command-line arguments

does not matter

### Browser name(s) and version(s)

Chrome 

### Platform(s) and version(s)

Windows 10

**Comment by AlexKamaev** [comment]
Fun fact 1:  if you remove the body styles everything will work as expected.
Fun fact 2: it works in proxyless mode

**Comment by miherlosev** [comment]
This issue is not reproduced with combination of `testcafe@3.0.1` and the Google Chrome browser. Feel free to reopen this issue if you encounter it in other browsers.
