### ISSUE TITLE
Cannot load Esri ArcGIS map because TestCafe reverse proxy isn't secure

### ISSUE THREAD

**Issue by kendricchung-aqi** [DevExpress/testcafe#7286]
### What is your Scenario?

I have an application which needs to load Esri ArcGIS, however, it isn't able to actually load most of the JS files from the ArcGIS package because the origin of the request includes the entire reverse proxy url. Is there a way to disable this?

The issue is coming from in the package of ArcGIS where it needs to make API calls to fetch JS files. This isn't working because the origin isn't secure.

### What is the Current behavior?

Currently, the API calls throws and error and most of the JS files that need to be loaded, are not.

### What is the Expected behavior?

The JS files should be fetched and load the map as expected.

### What is your public website URL? (or attach your complete example)

N/A

### What is your TestCafe test code?

```import { Selector } from 'testcafe';

fixture`Getting Started`
    .page`<my url here>`;

test('My first test', async t => {
    // Test code
});```

This happens on load of the website rather than actually running tests.

### Your complete configuration file

_No response_

### Your complete test report

_No response_

### Screenshots

_No response_

### Steps to Reproduce

1. Import ArcGIS as a script in a webpage
2. Run a simple TestCafe test against that page
3. Error should popup in the console


### TestCafe version

1.20.1

### Node.js version

v14.20.0

### Command-line arguments

testcafe chrome --skip-js-errors tests/

### Browser name(s) and version(s)

_No response_

### Platform(s) and version(s)

_No response_

### Other

_No response_

**Comment by miherlosev** [comment]
Hi @kendricchung-aqi 

You need to run TestCafe over the HTTPS protocol. See [Test HTTPS Websites](https://testcafe.io/documentation/402839/guides/advanced-guides/test-https-features-and-http2-websites?search#test-https-websites) for more information.
