### ISSUE TITLE
Missing RSS feed for the team blog

### ISSUE THREAD

**Issue by gg-kialo** [DevExpress/testcafe#7291]
### What is your Scenario?

The team blog (https://testcafe.io/resources/team-blog) appears to be missing an RSS feed. The old feed (not linked to from the page, I discovered a link in #5333) https://devexpress.github.io/testcafe/feed.xml, has no posts since April 2021.

### What are you suggesting?

Adding a rss feed for the blog, and including a link to it in the head of the blog page, like: `<link rel="alternate" type="application/rss+xml" href="https://testcafe.io/resources/team-blog/feed.xml" title="Testcafe Team Blog">`

### What alternatives have you considered?

There's no rss or atom links on the page.

**Comment by felis2803** [comment]
Thank you for the reminder. We'll restore RSS on the new site. However, we cannot guarantee that this will be done in the near future. Please bear with us.
