### ISSUE TITLE
Consider researching a different library for video recording

### ISSUE THREAD

**Issue by ayemelyanenko-chegg** [DevExpress/testcafe#7294]
### What is your Scenario?

Hello, please consider researching using a library for video recording that is not as resource heavy as ffmpeg

### What are you suggesting?

If possible, please research using another library for video recording instead of the ffmpeg one. Or please consider updating the video documentation with tips on how to set up the videoEncodingOptions so that the video recording is consuming as few resources as possible.

### What alternatives have you considered?

I have not seen any alternatives but perhaps there are some that the TestCafe dev team might be aware of.

### Additional context

It seems like ffmpeg consumes a lot of CPU when it's running locally and on CI as well. In addition, ffmpeg might also cause memory leaks when running it on the CI system.
https://stackoverflow.com/questions/4565567/how-can-i-limit-ffmpeg-cpu-usage
https://stackoverflow.com/questions/41775549/memory-leak-when-using-ffmpeg

**Comment by miherlosev** [comment]
Hi @ayemelyanenko-chegg,

`FFmpeg` is a best-in-class library for video recording. This library is used by most tools with the same functionality.

I read the shared links and think that we should add a capability to set up the FFmpeg `-treads` parameter to reduce CPU usage on low-performance machines.

**Comment by miherlosev** [comment]
Hi @ayemelyanenko-chegg,

`FFmpeg` is a best-in-class library for video recording. This library is used by most tools with the same functionality.

I read the shared links and think that you need to specify the FFmpeg `-treads` parameter to reduce CPU usage on low-performance machines. You can do this using the [video-encoding-options](%5Bhttps://testcafe.io/documentation/402840/guides/intermediate-guides/screenshots-and-videos?search#video-encoding-options%5D(https://testcafe.io/documentation/402840/guides/intermediate-guides/screenshots-and-videos?search#video-encoding-options)).
