### ISSUE TITLE
Execute async function in TestCafe .js config

### ISSUE THREAD

**Issue by Despair-Bear** [DevExpress/testcafe#7296]
### What is your Scenario?

I need to make an API call to fetch environment information and then filter out tests based on that response

### What are you suggesting?

Make it possible to execute asynchronous API calls within the `.testcaferc.js` file

### What alternatives have you considered?

Utilizing global before hooks in order to fetch information to dynamically skip tests, but this would result in an API request per test/fixture.  Would like to just query the environment and pass that to the filter portion of the config file

**Comment by Aleksey28** [comment]
Hi @Despair-Bear,

You can execute API calls in a filter function in the `.testcaferc.js` file and filter your tests based on the response. For example:

```js
//.testcaferc.js
module.exports = {
    filter: async (testName) => {
        const apiResponse = await callAPI();

 

        //...
    }
};
```

**Comment by Despair-Bear** [comment]
So this should work in theory, however is it possible to import async api calls from existing modules in the project?  When I attempt to import functions Testcafe seems to throw an error when reading .testcaferc.js

**Comment by Aleksey28** [comment]
Yes, it is possible. You need to import it with the `require` syntax.

**Comment by Despair-Bear** [comment]
> Yes, it is possible. You need to import it with the `require` syntax.

Is there an example of this somewhere?  No matter where I attempt to import with the `require` syntax I am still getting the same generic `An error has occurred while reading the {file name} configuration file`

**Comment by Despair-Bear** [comment]
Okay so likely the final question, when I'm attempting to execute an API call within the async filter declaration, I am receiving the following error:
```ClientFunction cannot implicitly resolve the test run in context of which it should be executed. If you need to call ClientFunction from the Node.js API callback, pass the test controller manually via ClientFunction's `.with({ boundTestRun: t })` method first. Note that you cannot execute ClientFunction outside the test code.```

Is there any way to use a previously declared ClientFunction within the configuration files filter?

**Comment by Aleksey28** [comment]
You can use `ClientFunction` only inside the test code. Test filters run outside the test code. To call API requests in test filters, you need to use third-party libraries.
