### ISSUE TITLE
TestCafe - Getting 401 Authorization error on logging into application when test cases are executed one after another in same window (disableMultipleWindows:true)

### ISSUE THREAD

**Issue by SanthoshAsokan89** [DevExpress/testcafe#7316]
### What is your Scenario?

TestCafe - Getting 401 Authorization error on logging into application when test cases are executed one after another in same window (disableMultipleWindows:true)

Scenario:-
We are testing end to end using multiple applications.
1. User logs into Application1 using Microsoft Login credentials.
2. Performs some actions in APplication1.
3. User logs into APplication2 (outlook.com) using Microsoft login credentials and performs some action.
4. Test Case 1 ends
5. Test Case 2 begins in the same browser.
6. In Test Case2, when user tries to login to Application 1 using same credentials then user is getting Authorization 401 error page after entering the credentials.
7. Looks like caching related to login is not cleared.

**_I tried User Roles and disable disablePageCaching as well, but no luck._**

Please note that the issue works fine when  disableMultipleWindows:false and I open each application in new window. However, I cannot use this since there are lot of test cases that will need to be changed if we use this feature.

Wanted to check if there are any alternatives or some known issue regarding this.

### What is the Current behavior?

 Getting 401 Authorization error on logging into application when test cases are executed one after another in same window

### What is the Expected behavior?

User should not get the error

### What is your public website URL? (or attach your complete example)

NA

### What is your TestCafe test code?

Cannot share the code here for now.

### Steps to Reproduce

We are testing end to end using multiple applications.
1. User logs into Application1 using Microsoft Login credentials.
2. Performs some actions in APplication1.
3. User logs into APplication2 (outlook.com) using Microsoft login credentials and performs some action.
4. Test Case 1 ends
5. Test Case 2 begins in the same browser.
6. In Test Case2, when user tries to login to Application 1 using same credentials then user is getting Authorization 401 error page after entering the credentials.
7. Looks like caching related to login is not cleared.

### TestCafe version

1.18.6

### Node.js version

14

### Command-line arguments

C:\Program Files\nodejs\node.exe --max-http-header-size=10240000 .\test-runner.js --browser=chrome --concurrency=1 --environment=QA1 --suite=""

**Comment by SanthoshAsokan89** [comment]
The applications url are internal and hence cant be shared. However, I can share my screen in zoom/teams if someone is available to debug the issue. 
Also I have noticed that the issue is similar to the below. However there was no solution mentioned in it as well.
https://github.com/DevExpress/testcafe/issues/3780

**Comment by AlexKamaev** [comment]
We understand that you cannot share a full project for certain reasons. In this case, please prepare a simple sample that demonstrates the issue. A screen sharing session in zoom/teams is not effective, so we do not use this approach.

**Comment by SanthoshAsokan89** [comment]
@AlexKamaev  is there a way I can close the browser after every test case and launch the browser for a new test case when multiple test cases are executed in parallel and disableMultipleWindows:true  ??

**Comment by AlexKamaev** [comment]
No. TestCafe cannot close browsers between different test runs. TestCafe opens a browser and keeps it opened until all tests are finished.
