### ISSUE TITLE
Selector filter function 'withExactText' broken?

### ISSUE THREAD

**Issue by pschmolke** [DevExpress/testcafe#7323]
### What is your Scenario?

I want to filter various html elements which display some numbers.

Let's say I want to find the element that displays '2'.
Therefore I want to use `selector.withExactText( ' 2 ' )` because `.withText( '2' )` would also find elements that display for example '200' because it contains a '2'. The spaces are intentionally added around the number because `withExactText()` filters strictly by `textContent` and not by `innerText` like the counterpart `withText`.

### What is the Current behavior?

The filtered node selection does not include the wanted elements, even though the `textContent` value strictly matches the passed argument.

### What is the Expected behavior?

Retrieve a set of nodes by the passed filter method like the docs describe the behaviour.

### What is your public website URL? (or attach your complete example)

N/A

### What is your TestCafe test code?

```js
// I have added this quick and dirty test code to evaluate behaviour

// creates string ' 2 '
const text = String.fromCharCode( 32, 50, 32 );
console.log( text );
const pageSelector = Selector( '.ax-pagination' ).find( 'li' ).withExactText( text );
const textContent = await Selector( '.ax-pagination' ).find( 'li:nth-child(3)' ).textContent;
console.log( textContent );
console.log( textContent === text );

console.log( await pageSelector.exists );
```

This code snippet will when running the test result in the following console output

```js
 2 // build string ' 2 '
 2 // textContent read from frontend
true // textContent === text strictly matches
false // await pageSelector.exists reports no selector matches filter
```

### Steps to Reproduce

1. Create a list that has multiple `<li>` elements which display numbers
2. Use the `withExactText()` filter
3. Property `.exists` responds with `false`

### TestCafe version

2.0.1

### Node.js version

v16.3.0

### Command-line arguments

npx testcafe tests/debug_test.ts

### Browser name(s) and version(s)

Chrome 105

### Platform(s) and version(s)

MacOS Monterey 12

**Comment by Aleksey28** [comment]
Hi @pschmolke,

Please describe how exactly you put spaces on the page. Do you use the `&nbsp; `, the `pre` tag, or something else?

**Comment by pschmolke** [comment]
Hi @Aleksey28,
I do not put spaces there by myself. I use vueJs as the frontend framework and the code for the element where this fails is as follows:
```vue
<li
    v-else
    :key="i"
    :class="{ active: page === el.page }"
    @click="selectPage( el.page )">
    {{ el.label }}
</li>

```

**Comment by Aleksey28** [comment]
Thank you for the additional information. I reproduced the issue with the following example:
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <ul>
        <li> 0 </li>
        <li> 1 </li>
        <li> 2 </li>
        <li> 3 </li>
    </ul>
</body>
</html>
```

```js
import { Selector } from 'testcafe';

fixture`Fixture`.page`./index.html`;

test('Test', async (t) => {
    const text = ' 2 ';
    const selectorByText = Selector('li').withExactText(text);
    const selectorByIndex = Selector('li').nth(2);

    await t.expect(selectorByIndex.textContent).eql(text);
    await t.expect(selectorByText.exists).ok();
})
```

As a workaround, you can get an element by index using the [`nth`](https://testcafe.io/documentation/402748/reference/test-api/selector/nth) method instead of withText.

**Comment by miherlosev** [comment]
Hi @pschmolke 

It's expected behavior.
`Selector.text` refer to the `HTMLElement.innerText` value.
The `innerText` value of the `li` element from https://github.com/DevExpress/testcafe/issues/7323#issuecomment-1272965903 doesn't contain spaces.

![image](https://github.com/DevExpress/testcafe/assets/4133518/f9cc2784-2795-4d69-ba68-e475acf4617d)
