### ISSUE TITLE
temp directory cleanup process prevents browser connections on some machines

### ISSUE THREAD

**Issue by Asuza** [DevExpress/testcafe#7327]
### What is your Scenario?

Run TestCafe using Yarn PnP (as opposed to a node_modules folder). This works great except on certain machines.

### What is the Current behavior?

```
ERROR Cannot establish one or more browser connections.
1 of 1 browser connections have not been established:
- chrome
```

### What is the Expected behavior?

The tests should run as usual.

### What is your public website URL? (or attach your complete example)

N/A, steps to reproduce are below

### What is your TestCafe test code?

```javascript
fixture `Pizza Palace`
    .page `https://testcafe-demo-page.glitch.me/`;

test('Submit a form', async t => {
    await t
        // automatically dismiss dialog boxes
        .setNativeDialogHandler(() => true)

        // drag the pizza size slider
        .drag('.noUi-handle', 100, 0)

        // select the toppings
        .click('.next-step')
        .click('label[for="pepperoni"]')
        .click('#step2 .next-step')

        // fill the address form
        .click('.confirm-address')
        .typeText('#phone-input', '+1-541-754-3001')
        .click('#step3 .next-step')

        // zoom into the iframe map
        .switchToIframe('.restaurant-location iframe')
        .click('button[title="Zoom in"]')

        // submit the order
        .switchToMainWindow()
        .click('.complete-order');
});
```

### Your complete configuration file

N/A

### Your complete test report

N/A

### Screenshots

N/A

### Steps to Reproduce

Create a new directory, navigate into that directory via terminal, and then run the following commands (assuming `yarn` is already installed globally):
```
yarn init
yarn set version berry
yarn add testcafe
```

Then copy and save the TestCafe example at https://testcafe.io/ (the fixture about Pizza Palace) to that directory as _pizza.test.js_.

Finally,
```
yarn run testcafe chrome pizza.test.js
```

Chrome should open up, the test should run, and the browser should close. For me, it acts as if TestCafe cannot connect to Chrome.

### TestCafe version

At least 1.19.0 to 2.0.1

### Node.js version

At least v16.17.0 and v16.17.1. I believe v14 had the same behavior when checked some time ago.

### Command-line arguments

chrome pizza.test.js

### Browser name(s) and version(s)

Chrome 105.0.0.0

### Platform(s) and version(s)

Windows 10

### Other

If I manually comment out this line before running my commands, the browser launches and tests run without any problems.
https://github.com/DevExpress/testcafe/blob/ec3c373ad819b30c27d3e23d7c6c7e3c790b6c5d/src/utils/temp-directory/index.js#L96
I don't yet understand why this breaks the entire process, and need to further study the promise it's waiting on. I created this bug report in hopes y'all would be able to assist with that part.

**Comment by Aleksey28** [comment]
Hi,

I cannot reproduce the problem with the same `node` and `testcafe` versions, but with a higher `chrome` version - 106.0.5249.103 (Official Build) (64-bit). So, please update your browser and check if this helps.

**Comment by Asuza** [comment]
To verify, I updated my Chrome to 106.0.5249.103 (Official Build) (64-bit), and tested Firefox and Edge. The issue persists, so it's not browser-specific. If I dig into the TestCafe code, it appears as if the spawned worker process in _CleanupProcess_ never responds to the process that spawned it. When the worker process does not respond, TestCafe sort of just dies there and does not connect to any browser.

I suppose that's the closest I can get you to the bug. To play around in the TestCafe code with this setup, I used the `yarn unplug testcafe` command, which unzips the module and places it in the _.yarn/unplugged_ folder. I then directly modified files in TestCafe's _lib_ directory to study the issue.

**Comment by Aleksey28** [comment]
I didn't manage to reproduce the issue with the mentioned example and these conditions:
TestCafe version: 2.0.1
Node.js version: 16.17.0
Platform and version: Windows 10
Browser name and version: Chrome to 106.0.5249.103 (Official Build) (64-bit)

Are you sure that you have the same conditions? Do you perform all mentioned steps and run the example in an empty project?

**Comment by Asuza** [comment]
That's sort of the problem is that there is something missing in the environment which I can't explain or account for. For the items you've listed (TestCafe, Node.js, and platform), those are exactly what I have. I want to believe there's some strange disconnect between Node, Yarn, and TestCafe, but I don't know what it is.

The most I've figured out is that when the worker process gets created, but doesn't respond, then TestCafe does not proceed any further, but also gives an incorrect error message. I'm not sure how to patch the worker-related code to fail in a way that would cause it to behave in a nice way when the worker fails to respond. Maybe there's a way to add a timeout? Not sure.

I did patch my local version of TestCafe to skip `await cleanupProcess.init();` and do a similar cleanup, but that doesn't help me understand why it's happening.

**Comment by Aleksey28** [comment]
We need a simple example that we can run locally without any additional setup. Please create a new project where the issue is reproduced and attach this project to the next answer. If you share such an example, please feel free to reopen the issue.

**Comment by Klaster1** [comment]
@Aleksey28 while writing tests for my TestCafe tools using Node.js test runner in which I was spawning TestCafe with `execSync('npx testcase')` and checking reports, I caught the same error. But only after starting the node suite with `--watch`. Debugging revealed that [this process message listener](https://github.com/DevExpress/testcafe/blob/89895bed2f932b95d815c5f3c15a7cd7e90b3d53/src/utils/temp-directory/cleanup-process/index.js#L32) does not validate the payload and always assumes that messages will have the `id` property:
```
{
  'watch:require': [
    'C:\\dev\\testcafe-repeat-test\\node_modules\\testcafe\\lib\\utils\\temp-directory\\cleanup-process\\commands.js'
  ]
}
```
Back when the issue was reported, I suspect Yarn didn't detach child processes it spawned.
