### ISSUE TITLE
elegant-spinner does not work well on Travis CI

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#733]
See https://travis-ci.org/DevExpress/testcafe-browser-provider-saucelabs/jobs/153545421

**Comment by inikulin** [comment]
Hmm, overall what's by design, it doesn't support CLI clean up. You will get same results with any animated output, the question is if we can handle it gracefully, e.g. disabling spinner in such envirionments. @AndreyBelym can you investigate, pls?

**Comment by AndreyBelym** [comment]
Looks like that the key is `CI` environment variable. It's not documented in Travis CI docs (but it is described in [AppVeyor docs](https://www.appveyor.com/docs/environment-variables/) ), but https://github.com/sindresorhus/ora/blob/master/index.js#L34 uses it.

**Comment by inikulin** [comment]
Let's use condition from Ora

**Comment by inikulin** [comment]
We have a isTTY var cli/log that enables animated spinner, we can introduce isAnimated var instead that will use condition from Ora (don't forget to give package a credit in code comment)
