### ISSUE TITLE
SwitchToIFrame hangs on 1.20.1 and 2.0.1 , but worked OK on 1.19.0

### ISSUE THREAD

**Issue by fmancardi** [DevExpress/testcafe#7331]
### What is your Scenario?

I have to fill a form that is openen in a iFrame,

### What is the Current behavior?

switchToIframe hangs forever

### What is the Expected behavior?

switch to the iframe

### What is your public website URL? (or attach your complete example)

test is too complicated to provide here

### What is your TestCafe test code?

-

### Your complete configuration file

-

### Steps to Reproduce

create a sample page with a button to open an iframe

### TestCafe version

1.20.1 and 2.0.1

### Node.js version

v18.4.0

### Command-line arguments

testcafe 'chrome --start-fullscreen' --test-meta WKFSTATUS=ready,7.0=yes --cfg=at-7.0.json ./test/product-tree/PT.05.TMS.Planning/Multiappuntamento/PPT-7490-Conf-creaTrasp-outb-singAppun-Fascia.js

### Browser name(s) and version(s)

chrome

### Platform(s) and version(s)

windows 11

**Comment by fmancardi** [comment]
[iFrameIssue.zip](https://github.com/DevExpress/testcafe/files/9786637/iFrameIssue.zip)

Here the example, testcafe version 2.0.1

**Comment by Aleksey28** [comment]
Hi @fmancardi,

Thank you for the example. I managed to reproduce the issue. I understand why this behavior occurs but it will take some time to fix it. At the moment, as a workaround, you need to set a [timeout ](https://testcafe.io/documentation/402672/reference/test-api/testcontroller/wait)approximately to 500ms before switching to the iframe.

```js
await t.wait(500)
```

**Comment by aflalves** [comment]
I have the same issue (or very similar) after updating testcafe version. I was on v1.19.0 and the issue started after v2 update. I've spend a lot of time debugging today, the provided workaround doesn't help, here are some details:

When the element that loads the iFrame is clicked, testcafe hangs and the `await t.click()` promise is never resolved, so I don't even get a chance to call `switchToIframe` after the click, chaining also doesn't work. Basically its stuck forever:

```js 
console.log('this is logged');
await t.click(selectorThatTriggersTheIframe);
console.log('this is never reached');
```

Interesting thing, if I add a `debug()` before, remove the `click(), unlock the page and click on it myself and resume, it works.

@Aleksey28 You mentioned you understand why the original issue happens, do you believe its the same? Are there any other workaround? Is it possible somehow to have a timeout for `click()`?

Thank you

**Comment by miherlosev** [comment]
Hi @fmancardi,

If I run the example from [https://github.com/DevExpress/testcafe/issues/7331#issuecomment-1279004344](https://github.com/DevExpress/testcafe/issues/7331#issuecomment-1279004344) with the [experimental-proxyless](https://testcafe.io/documentation/402639/reference/command-line-interface#--experimental-proxyless) option, the test doesn't hang on the `switchToIframe` action.
It fails with the `Selector not found` error.
Please try to fix the test and run it with [experimental-proxyless](https://testcafe.io/documentation/402639/reference/command-line-interface#--experimental-proxyless).

**Comment by fmancardi** [comment]
Thanks, I'm going to try (with latest test cafe version) and provide feedback.

have a nice week end

**Comment by fmancardi** [comment]
Hi
I've done a couple of runs in TestCafe Studio 1.8.2, that uses TestCafe framework 2.1.0, without adding the experimental-proxyless option and it seems to work OK.  
Going to provide more feedback in the next weeks

regards
