### ISSUE TITLE
Add support for xpath and text selector when running JSON with DevTools Recorder

### ISSUE THREAD

**Issue by jecfish** [DevExpress/testcafe#7333]
### What is your Scenario?

DevTools Recorder support text and XPath selector from Chrome 108 onwards. I am wondering if there are similar selector in testcafe?

Here is the example step's json.

```json
{
      "type": "click",
      "target": "main",
      "selectors": [
        [
          "aria/Proceed to checkout"
        ],
        [
          "[data-test=checkout]"
        ],
        [
          "xpath///*[@data-test=\"checkout\"]"
        ],
        [
          "text/Total: $0.00"
        ]
      ]
    }
```

<img width="500" alt="Screen Shot 2022-10-16 at 9 35 19 AM" src="https://user-images.githubusercontent.com/5917927/196023955-28e86ac8-fb1b-44ee-aa7a-006b7c4b9ec3.png">

### What are you suggesting?

Add support for xpath and text selector when replay with DevTools Recorder

**Comment by miherlosev** [comment]
Hi @jecfish,

At present, there is no built-in support for XPath queries.
There is a proposal for this case - [https://github.com/DevExpress/testcafe/issues/1178](https://github.com/DevExpress/testcafe/issues/1178).
As soon as TestCafe supports XPath-based Selectors, DevTools tests will automatically support it.
