### ISSUE TITLE
Spiff login page errors in Chrome/Edge, but works fine for Firefox

### ISSUE THREAD

**Issue by Asuza** [DevExpress/testcafe#7340]
### What is your Scenario?

Run tests that start at https://app.spiff.com/login.

### What is the Current behavior?

The site show an error message in Chrome and Edge.
It works fine in Firefox.

### What is the Expected behavior?

The site to load properly in all browsers (as it does when navigating to the site manually).

### What is your public website URL? (or attach your complete example)

https://app.spiff.com/login

### What is your TestCafe test code?

```javascript
import { Selector } from 'testcafe';

fixture `Spiff`
    .page `https://app.spiff.com/login`;

test('Visit the site', async t => {
    await t
        // Expect there to not be an error
        .expect(Selector('h1').withText('Sorry, something went wrong.').exists).notOk();
});
```

### Your complete configuration file

N/A

### Your complete test report

```
testcafe chrome spiff.test.js --skip-js-errors
 Running tests in:
 - Chrome 106.0.0.0 / Windows 10

 Spiff
 × Visit the site

   1) AssertionError: expected true to be falsy

      Browser: Chrome 106.0.0.0 / Windows 10

          4 |    .page `https://app.spiff.com/login`;
          5 |
          6 |test('Visit the site', async t => {
          7 |    await t
          8 |        // Expect there to not be an error
       >  9 |        .expect(Selector('h1').withText('Sorry, something went wrong.').exists).notOk();
         10 |});
         11 |
```

### Screenshots

![image](https://user-images.githubusercontent.com/658248/197049840-f35eb132-a754-4891-9347-3a326f56afaf.png)

### Steps to Reproduce

1. Save the above test code as _spiff.test.js_.
2. Run `testcafe firefox spiff.test.js --skip-js-errors`. The test should pass.
3. Run `testcafe chrome spiff.test.js --skip-js-errors`. The test should fail.

### TestCafe version

Tested 1.17.0 and 2.0.1

### Node.js version

v16.18.0

### Command-line arguments

testcafe chrome spiff.test.js --skip-js-errors

### Browser name(s) and version(s)

Chrome 106.0.0.0, Firefox 107.0

### Platform(s) and version(s)

Windows 10

**Comment by AlexKamaev** [comment]
Thank you for sharing the example. I managed to reproduce the issue.
To the team:
The issue is reproducible in the hammerhead `http-playground`. Also, I got the following js error:
 
![image](https://user-images.githubusercontent.com/1678902/197462436-2f07918c-d4e6-48da-a3f8-6ba3e50fcc12.png)

**Comment by miherlosev** [comment]
The issue is not reproduced with `testcafe@3.0.1`.
