### ISSUE TITLE
Downloading pdf instead of opening a new tab with pdf preview

### ISSUE THREAD

**Issue by bogdanbotin** [DevExpress/testcafe#7343]
### What is your Scenario?

The test scenarios consists in opening a new tab in the same browser with a pdf preview.

### What is the Current behavior?

The scenario works until it should open a new tab with the pdf preview, but instead of this, it dowloads the pdf and it is not opening a new window.

### What is the Expected behavior?

In the moment I click on pdf link, it should open a new tab or window with pdf preview.

### What is your public website URL? (or attach your complete example)

.

### What is your TestCafe test code?

.

### Steps to Reproduce

Any scenario which checks the preview of pdf files opened in a new tab or window in same browser.

### TestCafe version

2.0.1-rc.1

### Node.js version

v16.13.1

### Command-line arguments

.

### Browser name(s) and version(s)

Chrome

### Platform(s) and version(s)

Window 10

**Comment by Aleksey28** [comment]
Hi @bogdanbotin,

TestCafe is required for testing HTML pages. A tab with PDF is a non-HTML page. Thus, TestCafe downloads a file. You can only [check](https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/intercept-http-requests.html#log-http-requests) if the PDF file was requested or [use the fs module to check the downloaded PDF file](https://github.com/DevExpress/testcafe-examples/blob/d36b647b3f4c167a6a01ed970057a12184d038ae/examples/wait-for-file-download/test.js).
