### ISSUE TITLE
It takes too long to terminate testcafe in Angular 14 e2e tests

### ISSUE THREAD

**Issue by yklymenko** [DevExpress/testcafe#7348]
### What is your Scenario?

The test scenario is already described in https://github.com/DevExpress/angular-testcafe/issues/89 and was reproduced by the angular-testcafe  team. 

Even if testCafe instance will be closed correctly with a close() method, it takes approx. 30-60 sec. to terminate process. All this time I can see "worker.js" from the testcafe cleanup-process running on my machine.  This behaviour was "introduced" in version 3.0.0. Older versions terminate immediately after tests execution.

### What is the Current behavior?

It takes too long to terminate process

### What is the Expected behavior?

Process should be terminated after tests executions

### What is your public website URL? (or attach your complete example)

https://github.com/DevExpress/angular-testcafe/issues/89

### What is your TestCafe test code?

already available at https://github.com/DevExpress/angular-testcafe/issues/89

### Steps to Reproduce

https://github.com/DevExpress/angular-testcafe/issues/89

### TestCafe version

2.0.1

### Node.js version

v16.10.0

### Command-line arguments

https://github.com/DevExpress/angular-testcafe/issues/89

**Comment by Aleksey28** [comment]
Yes, we know about this problem. The `testcafe` team and `angular-testcafe` team are the same. I'll close it as a duplicate.
