### ISSUE TITLE
I need to dynamically generate TestCafe test script. Where number of testcases would be equal to number items returned by a service call

### ISSUE THREAD

**Issue by aarti315** [DevExpress/testcafe#7351]
### File a new question on StackOverflow

https://stackoverflow.com/questions/ask?tags=testcafe

**Comment by aarti315** [comment]
import { Selector } from 'testcafe';

let appList;
let username = '';
let password = '';

var requestNode = require('request');
var options = {
    'method': 'GET',
    'url': 'https://********.com/_layouts/15/cors/testcafeapps.ashx',
    'headers': {
        'Authorization': '*****w=='
    }
};
requestNode(options, function (error, response) {

    if (error) throw new Error(error);
    appList = JSON.parse(response.body);    
});

fixture`Validate`
    .httpAuth({
        username: username,
        password: password
    })    
for (const app in appList) {
    test('SSO test for ' + appList[app], async t => {
        try {
            console.log('Checking login for ' + appList[app])
            await t
                .navigateTo(appList[app])
             
        }
        catch (testError) {
            console.log(testError.errMsg); throw testError;
        }
    });
}

**Comment by aarti315** [comment]
I have written above code where I am trying to perform some test steps for each of the app returned by service call. I get an error as "Source file do not contain valid 'fixture' and 'test' declaration"

Instead of using service call if I use hardcoded JSON and iterate through JSON items then my code works but my actual requirement is to not use hardcoded JSON data instead get data from a Service call. Kindly let me know how I can achieve this.

**Comment by Aleksey28** [comment]
It's not a bug or enhancement. Please follow this [stackowerflow](https://stackoverflow.com/questions/74232936/how-to-dynamically-generate-testcafe-test-script-where-number-of-testcases-would) thread for further communication.
