### ISSUE TITLE
Generating tests dynamically depending on result from another tests

### ISSUE THREAD

**Issue by aarti315** [DevExpress/testcafe#7353]
### What is your Scenario?

In a system where we have N number of apps. We get lists of all apps and then tests each app as an individual tests. In this case number of tests case depends on starting testcase.  

### What are you suggesting?

Consider a scenario where Test1 gives me all list of apps present on application.
Using List of apps received from Test1 we need to generate N number of Tests to validate if all apps are working

**Comment by Aleksey28** [comment]
It's not a bug or enhancement. Please follow this [stackowerflow](https://stackoverflow.com/questions/74232936/how-to-dynamically-generate-testcafe-test-script-where-number-of-testcases-would) thread for further communication.
