### ISSUE TITLE
Incorrect pointer events on mobile devices

### ISSUE THREAD

**Issue by ewclide** [DevExpress/testcafe#7354]
### What is your Scenario?

We use an input system based on pointer events inside our project.
And also we use testcafe for testing project behavior in different cases and platforms.
We have problems with built-in functions like `click` and `drag` on android devices.

- The first problem is that `pointerover` event occurs once per test and  `pointerout` event doesn't occur when the emulated finger is released. It looks like a behavior on a desktop device but for a mobile device this is wrong.

- The second problem is an incorrect value of `button` property - it is zero all the time. But if you try to click by your finger it's not.

### What is the Current behavior?

Current behavior of click:
```
pointerover 0
pointerdown 0
pointerup 0
```
Current behavior of drag:
```
pointerdown 0
pointermove 0 // N times
pointerup 0
```

### What is the Expected behavior?

Expected behavior of click:
```
pointerover 1
pointerdown 1
pointerup 0
pointerout 0
```
Expected behavior of drag:
```
pointerover 1
pointerdown 1
pointermove 1 // N times
pointerup 0
pointerout 0
```

### What is your public website URL? (or attach your complete example)

Page doesn't matter. You can start for example `npx http-server` with empty page 

### What is your TestCafe test code?

For reproducing the problem run a simple test on a remote device:
```javascript
import { Selector } from 'testcafe';

fixture `Fixture`
  .page('http://localhost:8080');

test.only('example', async (t) => {
    await t.eval(() => {
        document.body.addEventListener('pointerover', (e) => console.log('pointerover', e.buttons));
        document.body.addEventListener('pointerdown', (e) => console.log('pointerdown', e.buttons));
        document.body.addEventListener('pointerup', (e) => console.log('pointerup', e.buttons));
        document.body.addEventListener('pointermove', (e) => console.log('pointermove', e.buttons));
        document.body.addEventListener('pointerout', (e) => console.log('pointerout', e.buttons));
    });

    await t.wait(1000);
    await t.click(Selector('body'), { offsetX: 200, offsetY: 200 });

    await t.wait(1000);
    await t.drag(Selector('body'), 100, 100, { offsetX: 100, offsetY: 100, speed: 0.02 });
});
```

### Steps to Reproduce

1.
2.
3.

### TestCafe version

2.0.1

### Node.js version

16.16.0

### Command-line arguments

testcafe remote --live --qr-code

### Browser name(s) and version(s)

Chrome 105

### Platform(s) and version(s)

Android 9

**Comment by miherlosev** [comment]
Hi @ewclide 

Thank you for the shared example. I've reproduced the issue.
