### ISSUE TITLE
Option for per-test localStorage when using Roles

### ISSUE THREAD

**Issue by ChrisLane** [DevExpress/testcafe#7370]
### What is your Scenario?

I run tests in parallel that may fail if there is data in localStorage from other running tests.
To login to my app in tests, I use a Role.

### What are you suggesting?

I would like to be able to use my Role to login to the app without localStorage being shared between tests.

### What alternatives have you considered?

I noticed that my tests were failing even when I setup a localStorage value in `test.before()` and removed it in `test.after()`.
When I removed my Role usage and instead had manual type/click actions in `fixture.beforeEach()`, my tests started passing.
This is my current workaround.

### Additional context

Testcafe: 2.0.2
Chromium: 107.0.5304.87

**Comment by AlexKamaev** [comment]
When you use a role, your localStorage is copied from one test and applied to the other test. This is how roles work. It looks like your website has some specifics that prevent you from using roles in your usage scenario. If you'd like us to research your usage scenario, please share a simple sample that demonstrates the issue.
