### ISSUE TITLE
Can't able to close the pop-up windows

### ISSUE THREAD

**Issue by LakshmiYaswanth** [DevExpress/testcafe#7371]
### What is your Scenario?
Can't able to close the pop-up windows this is the piece of code given below. 

fixture('New Window Feature')
.page('https://www.quackit.com/html/codes/html_popup_window_code.cfm');
test('New Window Opened Automatically After Click ', async t => {
   let url;
   let ytSelector = Selector('p>a');
    url = await t.eval(() => document.documentURI);
    console.log('Main URL: '+ url);
    await t.expect(url).eql('https://www.quackit.com/html/codes/html_popup_window_code.cfm');
    await t.switchToIframe("iframe.result").click(ytSelector);
    url = await t.eval(() => document.documentURI);
    console.log(url);
    await t.expect(url).eql('https://www.quackit.com/preview/preview_example_code.cfm');
   await t.closeWindow()
    await t.switchToParentWindow();
    await t.switchToIframe("iframe.result").click(ytSelector);
    await t.expect(ytSelector.exists).ok();
  });

here iam trying to close child pop up window but i can't able to close the pop up window.

### What is the Current behavior?

"Cannot close the window because it does not have a parent. The parent window was closed or you are attempting to close the root browser window where tests were launched".

### What is the Expected behavior?

Tt should close the pop-up window.

### What is your public website URL? (or attach your complete example)

fixture('New Window Feature')
.page('https://www.quackit.com/html/codes/html_popup_window_code.cfm');
test('New Window Opened Automatically After Click ', async t => {
let url;
let ytSelector = Selector('p>a');
url = await t.eval(() => document.documentURI);
console.log('Main URL: '+ url);
await t.expect(url).eql('https://www.quackit.com/html/codes/html_popup_window_code.cfm');
await t.switchToIframe("iframe.result").click(ytSelector);
url = await t.eval(() => document.documentURI);
console.log(url);
await t.expect(url).eql('https://www.quackit.com/preview/preview_example_code.cfm');
await t.closeWindow()
await t.switchToParentWindow();
await t.switchToIframe("iframe.result").click(ytSelector);
await t.expect(ytSelector.exists).ok();
});

### What is your TestCafe test code?

fixture('New Window Feature')
.page('https://www.quackit.com/html/codes/html_popup_window_code.cfm');
test('New Window Opened Automatically After Click ', async t => {
let url;
let ytSelector = Selector('p>a');
url = await t.eval(() => document.documentURI);
console.log('Main URL: '+ url);
await t.expect(url).eql('https://www.quackit.com/html/codes/html_popup_window_code.cfm');
await t.switchToIframe("iframe.result").click(ytSelector);
url = await t.eval(() => document.documentURI);
console.log(url);
await t.expect(url).eql('https://www.quackit.com/preview/preview_example_code.cfm');
await t.closeWindow()
await t.switchToParentWindow();
await t.switchToIframe("iframe.result").click(ytSelector);
await t.expect(ytSelector.exists).ok();
});

### Your complete configuration file

{ 
    "browsers": "chrome",
    "src": "tests/dataDriven/*.js",
    "screenshots": {
        "path":  "./configuration_file/screenshots/",
        "takeOnFails": true, 
        "fullPage": false
    },
    "videoPath": "./configuration_file/videos/",
    "skipJsErrors": true, 
    "concurrency": 1,
    "selectorTimeOut": 5000,
    "assertionTimeOut": 5000,
    "pageLoadTimeOut": 5000,
    "speed": 1

} 

### Steps to Reproduce

fixture('New Window Feature')
.page('https://www.quackit.com/html/codes/html_popup_window_code.cfm');
test('New Window Opened Automatically After Click ', async t => {
let url;
let ytSelector = Selector('p>a');
url = await t.eval(() => document.documentURI);
console.log('Main URL: '+ url);
await t.expect(url).eql('https://www.quackit.com/html/codes/html_popup_window_code.cfm');
await t.switchToIframe("iframe.result").click(ytSelector);
url = await t.eval(() => document.documentURI);
console.log(url);
await t.expect(url).eql('https://www.quackit.com/preview/preview_example_code.cfm');
await t.closeWindow()
await t.switchToParentWindow();
await t.switchToIframe("iframe.result").click(ytSelector);
await t.expect(ytSelector.exists).ok();
});

2.testcafe chrome tests/manageWindows/*.js --skip-js-errors run in cmd

### TestCafe version

"1.9.1"

### Node.js version

16.3

### Command-line arguments

testcafe chrome tests/manageWindows/*.js --skip-js-errors

**Comment by Aleksey28** [comment]
Hi @LakshmiYaswanth,

When some actions in the test open a new window, TestCafe doesn't automatically switch to the new window in version `1.9.*`. This behavior has changed since version `1.10.*`. So, you need to update your TestCafe version.
