### ISSUE TITLE
Add support for TypeScript configuration file

### ISSUE THREAD

**Issue by Halllker** [DevExpress/testcafe#7373]
### What is your Scenario?

TestCafe with TypeScript is so far a great experience, however there is an issue with global hooks and configuration file.

Global hooks can be defined only with JS configuration file which restricts from importing TypeScript classes and functions.
This makes global hooks nearly impossible to use without some solid dark magic.

### What are you suggesting?

Please, add a support for TypeScript configuration file so TS code can be referenced in global hooks and similar functionality (if any).

### What alternatives have you considered?

Other possibility would be to separate global hooks from configuration files completely, which would maybe feel a bit more natural and there would be no need for js or ts config files and everything necessary could be handled by simple json.

**Comment by Halllker** [comment]
And of course right after I've created this issue I stumbled upon similar one that approaches basically the same problem from the other side. https://github.com/DevExpress/testcafe/issues/6867

**Comment by Aleksey28** [comment]
Hi @Halllker,

Thank you for the suggestion. We'll update this thread once we have any news.

**Comment by gforepsly** [comment]
This enhancement would be great! I had similiar issues so I just went with .testcaferc.json for the configuration, and I created my own re-usable classes to handle repeating stuff. This would solve many issues for sure, thumbs up!

**Comment by Jackman3005** [comment]
While we wait for the exciting PR to get merged. Is there a type annotation I can add in a comment in the `.testcaferc.js` file to get some type support for configuration options. Most tools I use support typescript config files and I immediately miss type support for exploring configuration options (and validating them) and am a little annoyed by having to visit the documentation every time I want to tweak or add something.

I tried looking through the source code to find a type definition for the config file contents, but I am not actually sure that one exists at this point...

**Comment by gforepsly** [comment]
Is this still possible to do? This would solve a lot of our issues, so I'm trying to bump :)

**Comment by Bayheck** [comment]
Hello, 
We have investigated the issue and found that there are technical difficulties that block the fix. We do not have plans to address this issue in the near future.
However, you can compile your tests manually as described [here](https://testcafe.io/documentation/402824/guides/intermediate-guides/typescript-and-coffeescript#automatic-compilation-and-manual-compilation).
