### ISSUE TITLE
Ajax request referrer header altered after iframe loads

### ISSUE THREAD

**Issue by naggingant** [DevExpress/testcafe#7376]
### What is your Scenario?

Since TestCafe 1.20.x, we started getting errors on some ajax requests in our tests, claiming the referrer header is not allowed etc. which implied the header is not set properly as before.

### What is the Current behavior?

I could debug a little by inspecting the outgoing headers, and noticed the proxied request's referrer header had been replaced by the iframe src URL that was last loaded in the target page.

### What is the Expected behavior?

I suppose most browsers would set the header to the current page location that the request is made from, so I considered this a bug, i.e. the referrer header should remain the page URL and not change after an iframe load.

### What is your public website URL? (or attach your complete example)

```html
<html>
    <head />
    <body>
        <script type="text/javascript">
            function doAjax () {
                fetch('https://httpbin.org/headers')
                    .then(res => res.json())
                    .then(body => console.log(body.headers.Referer)) // this prints https://example.com
            }
        </script>
        <iframe src="https://example.com" onload="doAjax()" />
    </body>
</html>
```

### What is your TestCafe test code?

Assuming the above HTML is served at `http://localhost:9000`
```js
test('bug', async t => {
    await t
        .navigateTo('http://localhost:9000')
        .debug()
})
```

### Steps to Reproduce

1. Save the attached HTML and serve it via HTTP
2. Modify and run the attached test scenario
3. Observe `https://example.com` is printed in the console, instead of `http://localhost:9000`

### TestCafe version

2.0.2

### Node.js version

v16.14.0

### Command-line arguments

testcafe chromium -e test.js

**Comment by naggingant** [comment]
Oh... sorry for this mess

**Comment by Aleksey28** [comment]
Hi @naggingant,

I reproduced the issue. Thank you for your PR. I'll review it as soon as possible.
