### ISSUE TITLE
Actions (hover / click / typeText) doesn't scroll correctly to element behide a sticky element with padding

### ISSUE THREAD

**Issue by trooperjey01** [DevExpress/testcafe#7377]
### What is your Scenario?

I have a form with a sticky footer

I want to fill out the form 

### What is the Current behavior?

Testcafe doesn't scroll correctly to the element which is not in the view (it is hidden by the sticky footer with padding property ). 
typeText method doesn't work

### What is the Expected behavior?

Testcafe scroll correctly to the element

typeText method works

### What is your public website URL? (or attach your complete example)

https://jsfiddle.net/4bgvs8q3/

### What is your TestCafe test code?
```
import { Selector } from 'testcafe';
fixture('issue example')
.page('https://jsfiddle.net/4bgvs8q3/');

const input2 = Selector('#input2').find('input');
const input8 = Selector('#input8').find('input');
const frame = Selector('[name="result"]');

test('fill a form', async (t) => {
  await t.maximizeWindow();
  await t.switchToIframe(frame)
  await t.typeText(input2, 'test ok');
  await t.expect(input2.value).eql('test ok');
  await t.typeText(input8, 'test ko');
  await t.expect(input8.value).eql('test ko');
});
```

### Steps to Reproduce

1. Use the public website url
2. Try to do an action in an off-screen DOM element (hover / click / typeText) 

### TestCafe version

1.20.1

### Node.js version

v16.17.1

### Command-line arguments

testcafe chrome test.js

### Browser name(s) and version(s)

All supported browsers

**Comment by Aleksey28** [comment]
Hi @trooperjey01,

I managed to reproduce this issue. As a workaround, you can manually scroll the page:

```js
  const input8Rect = await input8().boundingClientRect

  await t.scroll(0, input8Rect.top);
```

**Comment by trooperjey01** [comment]
Sorry wrong click.

Thanks for your answer @Aleksey28 ,

I'll use your tips until the issue is resolved.
