### ISSUE TITLE
A JavaScript error occurs on testing a Blazor app page containing Monaco Editor

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe#7378]
### What is your Scenario?

Test a Blazor app page containing Monaco Editor

### What is the Current behavior?

The following JavaScript error occurs:

```
worker-hammerhead.js:3320 Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:1401/!s/https://unpkg.com/monaco-editor@latest/min/vs/base/worker/workerMain.js' failed to load.
    at importScripts (http://localhost:1401/worker-hammerhead.js:3320:49)
    at blob:http://localhost:1401/bcef2816-abdc-4b0a-8941-e99675fc5b2d:6:2
```

### What is the Expected behavior?

No errors occur

### What is your public website URL? (or attach your complete example)

See https://supportcenter.devexpress.com/internal/ticket/details/T1119220.

### What is your TestCafe test code?

See https://supportcenter.devexpress.com/internal/ticket/details/T1119220.

### Steps to Reproduce

1. Open the project attached to the last comment.
2. `dotnet run`
3. Launch the TestCafe Hammerhead playground.
4. Open the Dashboard page and DevTools. See the error in Console.

### TestCafe version

testcafe-hammerhead 28.2.0

### Node.js version

v16.14.2

### Command-line arguments

gulp http-playground

### Browser name(s) and version(s)

Chrome

### Platform(s) and version(s)

Windows 10

**Comment by AndreyBelym** [comment]
+1 https://teams.microsoft.com/l/message/19:55a62654075d4d03916baf02272c3e9e@thread.skype/1668419196386?tenantId=e4d60396-9352-4ae8-b84c-e69244584fa4&groupId=c3abb0f3-231c-4d87-b5a3-44925dc1d075&parentMessageId=1668418946422&teamName=TestCafe&channelName=General&createdTime=1668419196386&allowXTenantAccess=false
