### ISSUE TITLE
Measure Carbon Emissions of Web Pages

### ISSUE THREAD

**Issue by ng-druid** [DevExpress/testcafe#7379]
### What is your Scenario?

Our organization [Roll The Cloud Inc.](https://rollthecloud.com) is a 501(c)3 with a mission of freeing the web of carbon emissions. To this end we would like to better understand the carbon emissions of the websites that we create.

### What are you suggesting?

A recent tool that we discovered [GreenFrame.io](https://greenframe.io/) can be used to measure a websites carbon emissions via running [Playwright](https://playwright.dev/) tests. Green frame could made compatible with Test Cafe providing both green software awareness exposure to new audiences and major value add to TestCafe ecosystem itself.

### What alternatives have you considered?

Write our tests using Playwright instead of TestCafe so that we can run them on green frame.

### Additional context

* https://greensoftware.foundation
* https://learn.greensoftware.foundation
* https://patterns.greensoftware.foundation

**Comment by felis2803** [comment]
Thank you for letting us know about this tool. We will consider the possibility of using it in TestCafe.

**Comment by Artem-Babich** [comment]
TestCafe injects its own client scripts on a page as well as overrides a lot of native functionalities to handle all browsers' native behavior. So, any measurements will be unfair in this case. Unfortunately, there is no way to use TestCafe for your task.
