### ISSUE TITLE
t.takeElementScreenshot scolls element with `overflow: hidden`

### ISSUE THREAD

**Issue by htho** [DevExpress/testcafe#7380]
### What is your Scenario?

I have a div element with a small height. The text in that div is vertically cropped.
This is the expected behavior. I want screenshots to reflect that.

### What is the Current behavior?

`t.takeElementScreenshot` produces screenshots that contain the whole text, although it should be cropped.
`t.takeScreenshot` produces a correct screenshot.

TestCafe 1.6.0 produced correct screenshots.

### What is the Expected behavior?

`t.takeElementScreenshot` should produce a screenshot that is a cropped version of a full page screenshot.

### What is your public website URL? (or attach your complete example)

TestPage:
https://htho.github.io/testcafe-repro-screenshot-box/public/

Complete Repository:
https://github.com/htho/testcafe-repro-screenshot-box

Test HTML:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        #text {
            height: 10px;
            overflow: hidden;
            border: 1px solid red;
        }
        body {
            border: 1px dashed green;
        }
    </style>
</head>
<body>
<div id="text">AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz0123456789</div>
</body>
</html>
```

### What is your TestCafe test code?

```TypeScript
fixture("screenshot")
	.page("https://htho.github.io/testcafe-repro-screenshot-box/public/")

test("takeElementScreenshot", async (t) => {
    await t.takeElementScreenshot("#text");
});
test("takeScreenshot", async (t) => {
    await t.takeScreenshot();
});
```

### Your complete configuration file

none

### Your complete test report

```
C:\XXX\github.com\htho\testcafe-repro-screenshot-box> npm run test

> repro-testcafe-screenshot-box@1.0.0 test
> testcafe chrome test.tc.ts

 Running tests in:
 - Chrome 107.0.0.0 / Windows 10

 screenshot
 √ takeElementScreenshot (screenshots:
 C:\XXX\github.com\htho\testcafe-repro-screenshot-box\screenshots\2022-11-14_11-55-38\test-1\Chrome_107.0.0.0_Windows_10\1.png)
 √ takeScreenshot (screenshots:
 C:\XXX\github.com\htho\testcafe-repro-screenshot-box\screenshots\2022-11-14_11-55-38\test-2\Chrome_107.0.0.0_Windows_10\1.png)


 2 passed (3s)
```

### Screenshots

takeElementScreenshot on TestCafe 2.1.0 (unexpected behavior):
![1](https://user-images.githubusercontent.com/2182288/201644986-be0c56eb-c4e6-4508-b7cb-9e06c3aa67f7.png)

takeElementScreenshot on TestCafe 1.6.0 (expected behavior):
![1](https://user-images.githubusercontent.com/2182288/201645334-6ac7a56b-290f-41ea-b714-dec9793edfd6.png)

takeScreenshot on TestCafe 2.1.0:
![1](https://user-images.githubusercontent.com/2182288/201645806-90b3e128-392f-4b67-b342-e15768538dcb.png)

takeScreenshot on TestCafe 1.6.0:
![1](https://user-images.githubusercontent.com/2182288/201645464-58413f12-c863-4c03-af7e-602769155a7b.png)

### Steps to Reproduce

1. `npm i`
2. `npm serve`
3. `npm run test` (in another terminal)

### TestCafe version

2.1.0

### Node.js version

v16.17.1

### Command-line arguments

testcafe chrome test.tc.ts

### Browser name(s) and version(s)

chrome 107

### Platform(s) and version(s)

Windows 10

### Other

I asked this question on stackoverflow: https://stackoverflow.com/q/74305165/1635906
The answer suggested to use Version 2.1.0 (rc at the time): https://stackoverflow.com/q/74305165/1635906
Because it might fix the issue as it includes this PR: https://github.com/DevExpress/testcafe/pull/7054
Clearly it doesn't.

I investigated a bit and found that the `takeElementScreenshot` action creates/executes a call to `ScrollAutomation._scrollElement` (testcafe-core).
This checks if the element is scrollable using the `hasScroll` function.
This uses `getScrollable` to finally checks if `overflowX` or `overflowY` is one of "`auto`", "`scroll`" or "`hidden`".

Now it is a question of the requirements:
`overflow: hidden` means crop the elements no-matter-what.
In my opinion the screenshot should reflect that.

If I think of this more, this scroll-to-make-a-screenshot should be an option to the `takeElementScreenshot` function:
If I have scrollable list, it is best practice to crop the last element, so the user perceives: "there is more - I should try to scroll".
If I want to test this and see it in a screenshot, I don't want this feature either.

**Comment by Aleksey28** [comment]
Hi @htho,

I managed to reproduce the issue. We will update this thread once we have any news.

**Comment by Artem-Babich** [comment]
Hi, the scroll behavior is described in our documentation: [takeElementScreenshot](https://testcafe.io/documentation/402676/reference/test-api/testcontroller/takeelementscreenshot).

We will research the ability to change this behavior in such cases. As a workaround, you can use the targetScrollY and targetScrollX options:
```js
await t.takeElementScreenshot('#text', { scrollTargetY: 0 });
```
