### ISSUE TITLE
Hammerhead.js is causing Test Cafe to fail a test

### ISSUE THREAD

**Issue by felis2803** [DevExpress/testcafe#7385]
### What is your Scenario?

I'm running the test that fails due to a hammerhead error.

### What is the Current behavior?

The test fails.

### What is the Expected behavior?

The test must pass.

### What is your public website URL? (or attach your complete example)

See private ticket [T1127746](https://supportcenter.devexpress.com/internal/ticket/details/T1127746).

### What is your TestCafe test code?

See private ticket [T1127746](https://supportcenter.devexpress.com/internal/ticket/details/T1127746).

### Steps to Reproduce

1. Run the test.
2. Wait for result.

### TestCafe version

2.1.0

### Node.js version

16.18.0

### Command-line arguments

testcafe chrome test.js

### Browser name(s) and version(s)

Chrome@107.0.5304.107

### Platform(s) and version(s)

Windows 10

**Comment by JSteunou** [comment]
@felis2803 could you share the stacktrace or more error if possible so we can see if it could be a similar error than another we could experience?

**Comment by bbutel** [comment]
Same question than @JSteunou please :)

**Comment by felis2803** [comment]
@JSteunou, @bbutel,
I'm sorry, I can't do that because a user from the DevExpress Support Center contacted us with this issue, and I can't share their data. Also, today they posted that they found the issue that was causing the hammerhead error and fixed it on their side. So, this issue will be closed.
It is better for you to open a separate issue dedicated to the problem you encountered. We will try to help.

**Comment by JSteunou** [comment]
Ok. It was juste to know if it is the same issue than we discovered (issue not opened yet because running out of time to make a simple example). It is related to optional chaining & hammerhead.
