### ISSUE TITLE
Testcafe: Cannot establish one or more browser connections

### ISSUE THREAD

**Issue by vilasrajbhar** [DevExpress/testcafe#7389]
### What is your Scenario?

I am currently using Testcafe latest image from docker hub (https://hub.docker.com/r/testcafe/testcafe/tags)
testcafe version: 2.1.0

testcaferc.json:

{
  "browsers": "firefox:headless",
  "selectorTimeout": 90000,
  "assertionTimeout": 90000,
  "concurrency": 10,
  "speed": 1,
  "debugOnFail": false,
  "skipJsErrors": true,
  "skipUncaughtErrors": true,
  "takeScreenshotsOnFails": true,
  "browserInitTimeout": 180000,
  "quarantineMode": {
    "attemptLimit": 2,
    "successThreshold": 1
  },
  "disableMultipleWindows": true,
  "reporter": [
    {
      "name": "slack",
      "options": {
        "webhookUrl": "slackurl",
        "channel": "#abc",
        "username": "testcafebot",
        "_comment": "value can be TEST or SUMMARY for logginglevel",
        "loggingLevel": "SUMMARY",
        "quietMode": true
      }
    }
  ]
}

### What is the Current behavior?

**For Firefox:**
I tried upgrading both Chromium browser and Firefox, still getting below error.
The "browsers", "reporter", and "filter" options from the configuration file will be ignored.
ERROR Cannot establish one or more browser connections.
1 of 1 browser connections have not been established:
- firefox:headless

**For Chromium:**
The "browsers", "reporter", and "filter" options from the configuration file will be ignored.
ERROR Cannot establish one or more browser connections.
1 of 1 browser connections have not been established:
- Chromium:headless

### What is the Expected behavior?

From last two years same script was running perfectly and all of sudden we started facing this error. I suspect there was latest image pushed to docker hub.

### What is your public website URL? (or attach your complete example)

N/A for the purpose of this issue

### What is your TestCafe test code?

N/A for the purpose of this issue

### Your complete configuration file

N/A for the purpose of this issue

### Your complete test report

N/A for the purpose of this issue

### Screenshots

![image](https://user-images.githubusercontent.com/62281101/202749423-d46ea934-d3d6-4289-8146-dd9a777cb2fd.png)
![image](https://user-images.githubusercontent.com/62281101/202749509-741c33ce-7ad1-4cb5-a0eb-94d05e342b83.png)

![image](https://user-images.githubusercontent.com/62281101/202858281-bdf629ec-d5eb-4b06-97ed-0bf3476be077.png)

**NPM logs:**
cat 2022-11-19T15_20_35_837Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'ci:automation:smoke' ]
2 info using npm@6.14.15
3 info using node@v18.12.1
4 verbose run-script [
4 verbose run-script   'preci:automation:smoke',
4 verbose run-script   'ci:automation:smoke',
4 verbose run-script   'postci:automation:smoke'
4 verbose run-script ]
5 info lifecycle privacy-portal-automation@1.0.0~preci:automation:smoke: privacy-portal-automation@1.0.0
6 info lifecycle privacy-portal-automation@1.0.0~ci:automation:smoke: privacy-portal-automation@1.0.0
7 verbose lifecycle privacy-portal-automation@1.0.0~ci:automation:smoke: unsafe-perm in lifecycle true
8 verbose lifecycle privacy-portal-automation@1.0.0~ci:automation:smoke: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/tmp/build/2cb8e61c/automation-repo/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
13 verbose stack     at EventEmitter.emit (node:events:513:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (node:events:513:28)
13 verbose stack     at maybeClose (node:internal/child_process:1091:16)13 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
14 verbose pkgid privacy-portal-automation@1.0.0
15 verbose cwd /tmp/build/2cb8e61c/automation-repo
16 verbose Linux 4.14.296-222.539.amzn2.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "ci:automation:smoke"18 verbose node v18.12.119 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error privacy-portal-automation@1.0.0 ci:automation:smoke: `npm run remove:automation:report && npx testcafe firefox:headless --no-sandbox --disable-dev-shm-usage --test-meta smoke=true  automation/ -S -s automation/reports/screenshots --reporter xoe-reporter:automation/reports/report_smoke.json,slack --reporter-app-name='E2E' --reporter-app-version='1.0.0'`
22 error Exit status 1
23 error Failed at the privacy-portal-automation@1.0.0 ci:automation:smoke script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
/home/user/.npm/_logs #

### Steps to Reproduce

1.
2.
3.

### TestCafe version

2.1.0

### Node.js version

v14.20.0

### Command-line arguments

npm run remove:automation:report && npx testcafe firefox:headless --no-sandbox --disable-dev-shm-usage --test-meta smoke=true  automation/ -S -s automation/reports/screenshots --reporter xoe-reporter:automation/reports/report_smoke.json,slack --reporter-app-name='E2E' --reporter-app-version='1.0.0'

### Browser name(s) and version(s)

Chromium 107.0.5304.110-r0

### Platform(s) and version(s)

Alpine Linux edge - 3.17_alpha20220715

**Comment by AndreyBelym** [comment]
Please try to remove `"concurrency": 10` from your config or at least decrease it. I wonder that it worked before, because running 10 browsers at the same time should cause a critical CPU and disk load especially in Docker.

**Comment by vilasrajbhar** [comment]
@AndreyBelym  I already tried that. Previously in my code, it was set as 1. I referred few articles from internet, which mentioned to increased concurrency to 10 and try again, but it did not worked, so I have already rollback the changes and currently concurrency is set to 1.

**Comment by miherlosev** [comment]
Hi @vilasrajbhar,

Since the suggestion from @AndreyBelym doesn't help fix the issue, we need an example that can be run locally. Could you please share such an example?
