### ISSUE TITLE
Incorrect cursor UI offset while performing action on iOS

### ISSUE THREAD

**Issue by georgiy-abbasov** [DevExpress/testcafe#739]
Reproducing on next page:

``` html
<!DOCTYPE html>
<html>
<head>
    <title>Title</title>
</head>
<body>
<div id='target'
     style="left:2000px; top:2000px; position:absolute; background: #015; width: 500px; height: 500px">
</div>
<div style="left:2700px; top:2700px; position:absolute; background: #000; width: 50px; height: 50px">
</div>
</body>
</html>
```

Test scenario:

``` js
test('Click on the target div', async t => {
    await t.click('#target', { offsetX: 400, offsetY: 400 });
});
```

![screen shot 2016-08-26 at 6 25 25 pm](https://cloud.githubusercontent.com/assets/15088565/18010869/0c8cc59c-6bbb-11e6-85ad-150415f66581.png)

If we specify `initial-scale`  in `<meta>` tag, cursor offset will be ok.

**Comment by AlexanderMoskovkin** [comment]
@georgiy-abbasov is this problem of UI only? Are click event arguments (pageX, pageY etc) ok?

**Comment by georgiy-abbasov** [comment]
@AlexanderMoskovkin, yes, the arguments still ok.
