### ISSUE TITLE
Multiple windows mode: a new window closes unexpectedly

### ISSUE THREAD

**Issue by felis2803** [DevExpress/testcafe#7395]
### What is your Scenario?

I click on a link with the attribute `target="_blank"` and want to make sure I'm on the right page.
```js
import { ClientFunction } from 'testcafe';

fixture `New Fixture`
    .page `https://devexpress.com`;
    
test(`New Test`, async t => {
    await t
        .click('#wsMsgWnd .CloseButton')
        .click('[title="Twitter"]')
        .expect(ClientFunction(() => location.href)()).eql('https://twitter.com/DevExpress')
});
```

### What is the Current behavior?

1. Clicking on the link `[title="Twitter"]` does not switch to a new window.
2. A new window opens for a fraction of a second and closes immediately.

### What is the Expected behavior?

1. TestCafe must switch to a new window so that the client function that will return the address is launched in it.
2. The window should not close before the test ends.

Here is an example of correct behavior:
```js
import { Selector, ClientFunction } from 'testcafe';

fixture `New Fixture`
    .page `https://puzzleweb.ru/html/examples/a_target.php`;
    
test(`New Test`, async t => {
    await t
        .switchToIframe('.result_output')    
        .click(Selector('a').withText('теги html с кратким описанием'))
        .switchToMainWindow()
        .expect(ClientFunction(() => location.href)()).eql('https://puzzleweb.ru/html/all_tags.php')
});
```

### What is your public website URL? (or attach your complete example)

https://devexpress.com

### TestCafe version

2.1.0

### Node.js version

16.18.0

### Command-line arguments

testcafe chrome test.js

### Browser name(s) and version(s)

chrome, firefox, edge

### Other

There is a workaround: disable multiwindow. However, it is not suitable as it will affect other tests.

### References

https://supportcenter.devexpress.com/internal/ticket/details/T1129386

**Comment by hoqueal** [comment]
Is there any update on this issue?

**Comment by Aleksey28** [comment]
Duplicate https://github.com/DevExpress/testcafe/issues/6926
