### ISSUE TITLE
TestCafe crashes on Node 18

### ISSUE THREAD

**Issue by alex-zh** [DevExpress/testcafe#7396]
### What is your Scenario?

Everything works fine on Node 14.
Update to Node 18 leads to "500 Internal Server Error" while loading
**http://localhost:5003/GFxi51qUa!s!utf-8/http://localhost:8080/hub/assets/main.js** 
though **http://localhost:8080/hub/assets/main.js**  is available
Checked the same problem with different domain names (besides localhost). 
See attached screenshots.

### What is the Current behavior?

It seems there is some internal problem with testcafe proxying, should work correctly

### What is the Expected behavior?

Should work correctly

### What is your public website URL? (or attach your complete example)

-

### What is your TestCafe test code?

Standard site using webpack-devserver

### Screenshots

![TestCafe_Node18](https://user-images.githubusercontent.com/6177523/204000354-99ca77d0-c610-4cae-b4a9-e3431e3e1ec6.JPG)

### Steps to Reproduce

1. Run tests
2. See the page is not open
3.

### TestCafe version

2.1.0

### Node.js version

18.12.1

### Command-line arguments

-

### Browser name(s) and version(s)

Chrome 107.0.5304.122

### Platform(s) and version(s)

Windows

**Comment by Aleksey28** [comment]
Hi @alex-zh,

I managed to reproduce the issue. We will update this thread once we have any news.

For the team:

1. Start `http-server` with any page and any port.
2. Try to open the URL with `localhost` in `http-playground`.

**Comment by AndreyBelym** [comment]
It happens due to this change in Node.js: https://github.com/nodejs/node/issues/40537. We will try to fix it ASAP. Right now, you can add this line at the start of some of your test files or a JS config file:
```js
require('dns').setDefaultResultOrder('ipv4first');
```
