### ISSUE TITLE
Press enter key does not work on focused button element in Firefox

### ISSUE THREAD

**Issue by PierreRott** [DevExpress/testcafe#7402]
### What is your Scenario?

I would like to use `pressKey('enter')` on the focused button in Firefox browser.

### What is the Current behavior?

Button does not respond.

### What is the Expected behavior?

`pressKey('enter')` should behave in Firefox browser the same way as in Chrome browser and the same way as manually.

### What is your public website URL? (or attach your complete example)

http://devexpress.github.io/testcafe/example/

### What is your TestCafe test code?

```
 test('Should focus the "Submit" button and press enter key to trigger button event', async () => {
     await t
         .typeText(Selector('#developer-name'), 'Fipy')
         .click(Selector('#tried-test-cafe'))
         .pressKey('tab tab tab')
         .pressKey('enter')
         .expect(Selector('#article-header').innerText).eql('Thank you, Fipy!');
 });
```

### Your complete test report

![firefoxIssue](https://user-images.githubusercontent.com/34771265/204837518-0e653899-a355-4c48-a413-0258c57a5018.JPG)

### Steps to Reproduce

1. Insert some text into the input with label 'your name'
2. Click on the checkbox with text ' I have tried TestCafe'
3. Press the tab key three times to focus the 'Submit' button
4. Press the enter key to simulate click event
5. Page should display the text "Thank you, [insert name from the first input]" but it does not happen

### TestCafe version

2.0.0

### Node.js version

16.17.1

### Command-line arguments

 testcafe firefox **.e2e-spec.ts

### Browser name(s) and version(s)

Firefox 107.0.1

### Platform(s) and version(s)

Windows 10

**Comment by miherlosev** [comment]
Hi @PierreRott,

This issue was fixed in `testcafe@2.1.1-alpha.1`. Try to run the tests with this version and let us know the results.
