### ISSUE TITLE
Error in before hook

### ISSUE THREAD

**Issue by marinamarin91** [DevExpress/testcafe#7416]
### What is your Scenario?

Using before hook to set some meta properties and get some environment variables

### What is the Current behavior?

Test is working locally, but have the following error in Jenkins: 
![image](https://user-images.githubusercontent.com/97027602/206654676-0bea026c-87f8-4bcf-937a-9058bf99c83a.png)

### What is the Expected behavior?

Tests should behave the same locally and in Jenkins machine

### What is your public website URL? (or attach your complete example)

NA

### What is your TestCafe test code?

fixture ('Atlantis Menu Tests')
.meta('type', 'SmokeTests-nightly')
.meta('system', 'COM')
.before( async ctx => {  
  ctx.pwd=process.env.TESTUSER_PSW; 
  ctx.acc=process.env.TESTUSER_USR;
  ctx.key = process.env.SECRET_KEY;
  //console.log(ctx.key)
  ctx.GoogleCode = generateToken(ctx.key);
})

### Your complete test report

[388.zip](https://github.com/DevExpress/testcafe/files/10192915/388.zip)

### Steps to Reproduce

1. Add meta to any test scenario to automatically identify the tests to be executed in before hook executed from jenkins with the following command from shell script:
 find $2 -name \*.js -print | xargs testcafe "chrome:headless" -S \
        --screenshots $SCREENSHOTS_DIR -p $2/$3/"Testcafe-\${TEST_INDEX}-\${TEST}.png"\
        --video $VIDEO_DIR --video-options "pathPattern=$2/$3/Testcafe-\${TEST_INDEX}-\${TEST}",'failedOnly=true'\
        --reporter html:$REPORTS_DIR/Testcafe-$2-$3-${DATE}.html > artifacts/log-${DATE}.txt \
        --fixture-meta "type=$2,system=$3"\

where $2 is "SmokeTests-nightly'" and $3 = COM, according to the meta data set by me.

### TestCafe version

 "testcafe": "^2.0.1-rc.1"

### Command-line arguments

testcafe chrome:headless *.js

### Other

{
  "dependencies": {
    "@faker-js/faker": "^7.3.0",
    "@ffmpeg-installer/ffmpeg": "^1.1.0",
    "authenticator": "^1.1.5",
    "axios": "^0.27.2",
    "nanoid": "^3.3.1",
    "node-fetch": "^3.2.4",
    "testcafe": "^2.0.1-rc.1",
    "testcafe-reporter-html": "^1.4.6"
  }
}

**Comment by marinamarin91** [comment]
Can we have a meeting and check the problem together? We will need jenkins to run the test, so just sending a scenario I do not think will help too much.

**Comment by AlexKamaev** [comment]
Unfortunately, we cannot organize an online session to solve the issue. Regarding Jenkins, it's not a problem, we can set up Jenkins on a local machine. We would be happy to research the issue if you share your usage scenario that reproduces the issue and an instruction on how to set up your project in Jenkins.
