### ISSUE TITLE
Hammerhead does not parse arguments correctly when fetch signature is <Request, { credentials : 'include' }> 

### ISSUE THREAD

**Issue by SilentM0ng00se** [DevExpress/testcafe#7417]
### What is your Scenario?

I am debugging a test that logs in. The login flow test is as follows: 

1. Open page with url `myawesomedomain.com`
2. Enter email and password
3. Click on the login button
4. The user is redirected to the 2 Factor Authentication page
5. Enter the 2FA code and click Login/Verify
6. A post request should get sent with the 2FA credentials in the post body to `myawesomedomain.com/verify`

Upon analyzing the network requests in the browser using testcafe debug, Instead of a `POST` request in step 6, the request sent is a `GET` which results in a `403`.

Debugging revealed that the fetch function in my code base is as below: 

```
const response = await fetch(
        new Request(
            url: 'myawesomedomain.com/verify', 
           options: {
                method: 'POST',
                body: 'some data',
           }),
           { credentials: 'include' },
  );
```

Note that I am passing { credentials : 'include' } as a parameter of fetch, and not of Request. This is a valid signature as mentioned in the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/fetch#syntax)

Tracing the calls further, I discovered that the [_processArguments](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/fetch.ts#L76) function in testcafe-hammerhead is parsing the Request parameter incorrectly. 

It returns only the string portion of the Request and discards everything else. 

### What is the Current behaviour?

The `[_processArgument](https://github.com/DevExpress/testcafe-hammerhead/blob/83c059ba76e7f32c91798019cee8b0ad9dfefa43/src/client/sandbox/fetch.ts#L76)` function in hammerhead returns the string `'myawesomedomain.com/verify'` for the request part and completely ignores everything else if the request options are sent as a part of the `fetch()` object. 

As a result, the request sent out of testcafe is a `GET` (default fetch request if no method is specified ) instead of a `POST`. That is to say the resultant request has only the `string` url.

### What is the Expected behavior?

All params should be parsed, and the correct request should be sent.
When sending POST request, POST should be sent and not GET

### What is your public website URL? (or attach your complete example)

This would be reproducible via a unit test : 

```
test('<Request, { credentials: 'include'}> signature', function () {
        var request = new Request( '/xhr-test/100', method: POST));

        return fetch(new Request(request), { credentials: 'include' })
            .then(function (response) {
                // assertion here
            })
    });
```

### What is your TestCafe test code?

// test.js
```
test('Test Login', () => {
    await loginPage.loginAsNewUser(t.context.email, t.context.password);
})
```

Login Page calls: 

```
await t.click(this.loginButton);
```

Which calls : 
```
const response = await fetch(
        new Request(
            url: 'myawesomedomain.com/verify', 
           options: {
                method: 'POST',
                body: 'some data',
           }),
           { credentials: 'include' },
  );
```

### Steps to Reproduce

1. Have a request function with signature `fetch(new Request, { credentials: 'include'} )`
8. Make a POST request using this function via testcafe
9. Observe network request / response

### TestCafe version

2.1.0

### Node.js version

16.16.0

### Command-line arguments

testcafe chrome -e test.js

### Other

This behaviour seems to have been introduced in hammerhead version >= 19.0.0 with issue [#2501](https://github.com/DevExpress/testcafe-hammerhead/pull/2501)

**Comment by Artem-Babich** [comment]
Hi @SilentM0ng00se

I just tried reproducing this issue with the latest testcafe version, and it doesn't seem to occur anymore. Please try reproducing it on your side. If the issue still occurs, send us a simple working project so that we can reproduce it locally.
