### ISSUE TITLE
Multiple line text with .typeText()

### ISSUE THREAD

**Issue by oliverzelmat** [DevExpress/testcafe#7418]
### What is your Scenario?

I would like to write a multiple line text in a contenteditable.

### What is the Current behavior?

There is no way to do so. pressKey('enter') does nothing.

### What is the Expected behavior?

Maybe add something like a \n to typeText() to trigger a new line.

### What is your public website URL? (or attach your complete example)

<!DOCTYPE html>
<html>
<head>

</head>
<body>

  <h1>Template</h1>
  
  <div id="123" style="border: 1px solid red; height: 200px; width:200px;" contenteditable="true">This is a blank template for a web page.</div>

</body>
</html>

### What is your TestCafe test code?

test('memo', async t => {

    await t
    .click(Selector('#123'))

    await t.eval(() =>{
         var el = document.getElementById('123')
         var evt = new KeyboardEvent('keydown', {altKey:false,
       bubbles: true,
       cancelBubble: false, 
       cancelable: true,
       charCode: 0,
       code: "Enter",
       composed: true,
       ctrlKey: false,
       currentTarget: null,
       defaultPrevented: true,
       detail: 0,
       eventPhase: 0,
       isComposing: false,
       isTrusted: true,
       key: "Enter",
       keyCode: 13,
       location: 0,
       metaKey: false,
       repeat: false,
       returnValue: false,
       shiftKey: false,
       type: "keydown",
       which: 13,
       view: window
       })

    el.dispatchEvent(evt);

        
    });

});

### Steps to Reproduce

1. Click in a contenteditable
2. use pressKey('enter')

### TestCafe version

1.20.0

### Command-line arguments

testcafe chrome test.js

**Comment by Aleksey28** [comment]
Hi @oliverzelmat,

Thank you for the suggestion. We will update this thread once we have any news.

**Comment by TAkbay** [comment]
Is there maybe a known workaround? I thought using \n or similar would help, but it didn't.
`.typeText(Selector('body'), This will be a very long text.\n Here is another line')`

**Comment by Dmitry-Ostashev** [comment]
@TAkbay The workaround with `.pressKey('enter')` works in [Native Automation mode](https://testcafe.io/404431/resources/blog/2023-6-21-testcafe-goes-native) in Chromium-based browsers.

For example:
```
import { Selector } from "testcafe";

fixture`Multiline`.page`file:///C:/Work/Pages/index.html`;

test('Test', async t => {
    await t
        .typeText('div[contenteditable=true]', 'abc')
        .pressKey('enter')
        .typeText('div[contenteditable=true]', 'def')
        .debug();
});
```

Starting with TestCafe v3.0.0, this mode is enabled by default.

**Comment by AlexKamaev** [comment]
We decided to close the issue since the workaround resolves it. Please use the workaround with [Native Automation mode](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode). If you have further questions, feel free to ask them here.
