### ISSUE TITLE
Support for webpacks implementation of trusted types in combination with 'eval-source-map'

### ISSUE THREAD

**Issue by mspoerer** [DevExpress/testcafe#7423]
### What is your Scenario?

[Trusted Types](https://web.dev/trusted-types/) is a new experimental DOM API created to combat DOM XSS, supported now in Chrome 83, with a polyfill available for other browsers. Webpack5 is capable of using Trusted Types to load dynamically constructed scripts, to adhere to CSP [require-trusted-types-for](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/require-trusted-types-for) directive restrictions. See [output.trustedTypes](https://webpack.js.org/configuration/output/#outputtrustedtypes) configuration option.

With 'trusted types' & 'eval-source-map' [devtool](https://webpack.js.org/configuration/devtool/)  enabled, Hammerhead does not rewrite all properties of the appropriate JavaScript objects that contain URL values. 

### What is the Current behavior?

It seems like there is a problem with the initialization order. The following images show lines of code from the generated Webpack bundles.

1. Trusted Types = disabled; Devtool =  'eval-source-map'
<img width="505" alt="image" src="https://user-images.githubusercontent.com/6773651/207626739-d46b14dc-38b2-4623-bd88-12ba626728fd.png">

2. **Manipulated through Hummerhead - Works as expected**
Trusted Types = disabled; Devtool = 'eval-source-map'; 
<img width="505" alt="image" src="https://user-images.githubusercontent.com/6773651/207626505-117967d9-ad70-4fdc-b345-4b220c708859.png">

3. Trusted Types = enabled; Devtool =  'eval-source-map'
<img width="505" alt="image" src="https://user-images.githubusercontent.com/6773651/207633527-48ab69c4-519f-483a-b15a-ed1ee05496ee.png">

4. **Manipulated through Hummerhead - Does not rewrite properties as expected**
Trusted Types = enabled; Devtool = 'eval-source-map'; 
<img width="505" alt="image" src="https://user-images.githubusercontent.com/6773651/207614296-ae721f33-b63a-4acb-886c-18fb31cd2533.png">

### What is the Expected behavior?

Hummerhead should rewrite all properties as expected. 

### What is your public website URL? (or attach your complete example)

Simple React, Webpack 5 & testcafe project.
https://github.com/mspoerer/react-webpack-testcafe

### What is your TestCafe test code?

-------

### Steps to Reproduce

1. Checkout project
2. run npm install
3. run npm run dev
4. execute testcafe test via npm run test
5. landing page prints wrong href value ('hash-of-testcafe/http://localhost:3000')
6. open webpack.config.js and delete trustedTypes
7. execute testcafe test via npm run test
8. landing page prints correct href value ('http://localhost:3000')

### TestCafe version

2.1.0

### Command-line arguments

----

**Comment by miherlosev** [comment]
Hi @mspoerer,

Thank you for the example. I've reproduced this issue.

As a workaround, you can try running tests with the `--experimental-proxyless` option. The application renders the correct URL if you run tests with this option.

Note that this option is available only in Google Chrome. Also, you need to upgrade testcafe to the `2.1.1-alpha.3` version.

**Comment by miherlosev** [comment]
Hi @mspoerer,

This issue is not reproduced with combination of `testcafe@3.0.1` and the Google Chrome browser. Feel free to reopen this issue if you encounter it in other browsers.
