### ISSUE TITLE
Getting  sometime "Uncaught exception: Error: write EOF" OR "Uncaught exception: Error: write EPIPE" when I run testcafe testcase over teamcity build.

### ISSUE THREAD

**Issue by rupesh1395** [DevExpress/testcafe#7426]
### What is your Scenario?

Simple write the tetscafe tetscase in typescript.
Put in Suite and run the suite 7 to 8 time in TeamCity.
 I used -u  also.
It will give below error
Test Failed
Uncaught exception:
Error: write EPIPE

### What is the Current behavior?

Getting this error 
Test Failed
Uncaught exception:
Error: write EPIPE
at afterWriteDispatched (internal/stream_base_commons.js:156:25)
at writeGeneric (internal/stream_base_commons.js:147:3)
at Socket._writeGeneric (net.js:787:11)
at Socket._write (net.js:799:8)
at doWrite (internal/streams/writable.js:377:12)
at clearBuffer (internal/streams/writable.js:529:7)
at onwrite (internal/streams/writable.js:430:7)
at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:103:10)
at WriteWrap.callbackTrampoline (internal/async_hooks.js:131:17)
Browser: Chrome 108.0.0.0 / Windows 10

### What is the Expected behavior?

Testcase should be pass or fail .Uncaught exception error should not return

### What is your public website URL? (or attach your complete example)

You can run on any test website.

### What is your TestCafe test code?

function testViewTest(): any {
    test('View Test', async(t) => {
        await testcom.login(t);
        await t
            .resizeWindow(1600, 1100);
        await MainPage.pagenavigate();
        await t
            .expect(testpage.getFileNameTableCell(test).exists).notOk()
            .expect(testpage.getFileNameTableCell(test).exists).notOk()
            .expect(testpage.getFileNameTableCell(test).exists).notOk();

      hhshs.forEach(async header => {
            await t
                .expect(hshs.exists).ok();
        });
        t.ctx.passed = true;
    });
}

### Your complete configuration file

"skipJsErrors": true,
    "pageRequestTimeout": 60000,
    "browserInitTimeout": 600000

### Screenshots

![image](https://user-images.githubusercontent.com/121029835/208420348-9503280d-0910-45e6-8938-8d327a359dd8.png)
![image](https://user-images.githubusercontent.com/121029835/208420579-09ef3f72-82ab-46bb-8341-0797bf844509.png)

### Steps to Reproduce

1.Simple write any testcafe test case in typescript language. Put the testcase in suite
2. Run suite through TeamCity build 
3. See the error in build log

### TestCafe version

2.0.0

### Node.js version

v14.18.1

### Command-line arguments

runner .src(tests) .browsers('chrome').reporter('teamcity') 

### Browser name(s) and version(s)

Chrome 108

### Platform(s) and version(s)

Windows

**Comment by rupesh1395** [comment]
Hey it is simple to replicate this issue . Write simple  testcafe test case and put in a one suite file and run through teamcity 5 to6 times you will get uncaught exception error

**Comment by AlexKamaev** [comment]
It's a very complex usage scenario, and it's not clear if it's related to TestCafe. Please simplify your usage scenario to reproduce the issue on a local machine.
Please also update your nodejs version.
In addition, the `testcafe-reporter-teamcity` module is marked as deprecated.

**Comment by rupesh1395** [comment]
I am not getting this issue in current version(Testcafe 2.1.0). Thank you
