### ISSUE TITLE
Uncaught object "[object Object]" was thrown. Throw Error instead on t.takeScreenshot() with Node 18

### ISSUE THREAD

**Issue by tsherkqa** [DevExpress/testcafe#7428]
### What is your Scenario?

Take a screenshot when a test fails, or take a screenshot during a test, while on Node 18.2.1

### What is the Current behavior?

If a screenshot is taken during a test, the error "Uncaught object "[object Object]" was thrown. Throw Error instead.

If a screenshot is taken when a test fails, the testrunner stalls _indefinitely_

**If I roll back to my original version of Node 14.17.6, both scenarios work as intended**

### What is the Expected behavior?

If a screenshot is taken during the test or on a test failure, the terminal should report back the error and the screenshot should be published to the specified test-artifacts folder

### What is your public website URL? (or attach your complete example)

[Testcafe Demo Site](https://devexpress.github.io/testcafe/example/)

### What is your TestCafe test code?

[Github repo with sample test and setup](https://github.com/tsherkqa/testcafenode18headless)

### Your complete configuration file

`{
	"screenshots": {
		"path": "test-artifacts/screenshots",
		"pathPattern": "${TEST_ID}_${FILE_INDEX}_${DATE}_${TIME}_${BROWSER}${RUN_ID}.png",
		"takeOnFails": true
	}
}`

### Steps to Reproduce

1. Pull down the demo repository attached, make sure Node 18.2.1 is installed
2. Run the sample test as is to see the error on taking a screenshot during the test as described in the title of this issue, and then run it again without t.takeScreenshot in the test to see it stall on taking the screenshot when the test fails

### TestCafe version

2.1.0

### Node.js version

18.2.1

### Command-line arguments

chrome:headless

### Platform(s) and version(s)

Windows 10

### Other

Remember that this issue with screenshot is only present on the latest version of Node 18.2.1, but work as intended on Node 14.17.6. I did not test any other versions of Node.

**Comment by Aleksey28** [comment]
Hi @tsherkqa,

Yes, this behavior is reproduced in TestCafe v`2.1.0` TestCafe. Please update TestCafe to [`2.2.0-rc.1`](https://www.npmjs.com/package/testcafe/v/2.2.0-rc.1) to resolve the issue.
