### ISSUE TITLE
dbus-daemon stuck in Testcafe Docker container on AlmaLinux 9

### ISSUE THREAD

**Issue by dschuldt** [DevExpress/testcafe#7431]
### What is your Scenario?

We are running tests with the following command:

```
docker run -it --rm --user root -v $(pwd):/tests/ testcafe/testcafe:1.19.0 firefox -S --screenshots /tests/reports/screenshots --selector-timeout 120000 --assertion-timeout 120000 /tests/src/testcafe/tests/smoketest --reporter spec,xunit:/tests/reports/testcafe-test-report.xml
```

### What is the Current behavior?

The testcafe process is not executed, but a `dbus-daemon --session --fork` process is started, which utilizes 100% CPU (please see attached image).

### What is the Expected behavior?

The tests are executed in the Docker container

### What is your public website URL? (or attach your complete example)

Not relevant, since test code is never executed

### What is your TestCafe test code?

Not relevant, since test code is never executed

### Screenshots

![Screenshot 2022-12-20 183547](https://user-images.githubusercontent.com/15954969/208732310-8bfd9ab5-1984-4d82-8b51-91346ff4ed44.png)

### Steps to Reproduce

1. Setup AlmaLinux 9 host
2. Install docker-ce 20.10.22
3. Run any minimal test with Testcafe Image >= 1.19.0

### TestCafe version

1.19.0

### Command-line arguments

Not relevant, since Testcafe is not executed

### Platform(s) and version(s)

AlmaLinux 9.1 (Kernel 5.14.0-162.6.1.el9_1.x86_64), Docker-CE 20.10.22

### Other

If we omit the `dbus-daemon --session --fork` command in the testcafe-docker.sh script, the tests are executed. (Why is the dbus needed?)

I tracked the behaviour down to dbus 1.14.x. It does not happen with dbus 1.12.x. 

Since Testcafe Image is based on alpine:edge, you can reproduce the issue with running the following simple commands in alpine:edge

```
apk add dbus
dbus-daemon --version
```

**Comment by AndreyBelym** [comment]
I don't have an AlmaLinux host, installing and configuring it can take some time. And I cannot reproduce the issue on Windows with Docker 20.10.21.

![image](https://user-images.githubusercontent.com/4479386/209358846-63207ab2-b31d-4837-8f8c-a15550693d2d.png)

So I guess it's better to submit this issue to the AlmaLinux bug tracker.

**Comment by miherlosev** [comment]
Hi @dschuldt

Thank you for sharing this workaround.
