### ISSUE TITLE
How restart browser after timeout?

### ISSUE THREAD

**Issue by taral14** [DevExpress/testcafe#7433]
### File a new question on StackOverflow

https://stackoverflow.com/questions/ask?tags=testcafe

**Comment by taral14** [comment]
Testcafe opens browsers at the beginning of execution and then all tests pass in them. But the aws deviceFarm has a session timeout of 40 minutes (default 15). After that the connection is interrupted and I catch the error
>>> Fatal error GeneralError: The Chrome 108.0.0.0 / Windows 10 browser disconnected. If you did not close the browser yourself, browser performance or network issues may be at fault.
>>> TimeoutError: The session d954255f3e3fc33b5e2c3ed21459c843 has timed out because it has reached maximum session duration of 900 seconds. Please refer to our documentation for details on how to increase your session duration through a capability.

**Comment by Aleksey28** [comment]
Hi @taral14,

TestCafe does not support `aws deviceFarm` out of the box. Try to find a way to increase its timeout.

Duplicate [https://github.com/DevExpress/testcafe/issues/7434](https://github.com/DevExpress/testcafe/issues/7434)
