### ISSUE TITLE
integration problem with aws deviceFarm

### ISSUE THREAD

**Issue by taral14** [DevExpress/testcafe#7434]
### What is your Scenario?

Testcafe opens browsers at the beginning of execution and then all tests pass in them. But the aws deviceFarm has a session timeout max 40 minutes (default 15).
https://docs.aws.amazon.com/devicefarm/latest/testgrid/techref-support.html
aws:maxDurationSecs (integer, optional, defaults to 900)
Maximum duration of the session before it is forcibly closed, in seconds. Range: 180 to 2400.

After that the connection is interrupted and I catch the error
```
Fatal error GeneralError: The Chrome 108.0.0.0 / Windows 10 browser disconnected. If you did not close the browser yourself, browser performance or network issues may be at fault.

TimeoutError: The session d954255f3e3fc33b5e2c3ed21459c843 has timed out because it has reached maximum session duration of 900 seconds. Please refer to our documentation for details on how to increase your session duration through a capability.
```

### What are you suggesting?

I see the solution in restarting browsers every 15 minutes. And its create new sessions on device Farm

**Comment by AlexKamaev** [comment]
TestCafe does not have `aws deviceFarm` support out of the box.
However, I found that there is a repo that implements TestCafe support for `aws deviceFarm`: [https://github.com/karki-minma/testcafe-browser-provider-devicefarm/](https://github.com/karki-minma/testcafe-browser-provider-devicefarm/)
Please try using that provider and ask the author if they can help with this issue.

**Comment by taral14** [comment]
Thank you. This solution is based on the testcafe-browser-provider-selenium plugin. I implemented the same. I looked at the code and there are no significant differences. I will definitely try this solution. But the problem is that the farm device cuts off the session after 15 minutes by timeout. And this case is also not processed in the current solution.

**Comment by taral14** [comment]
problem is that the testcafe opens the browser and performs all tests in one connection. And the session is dead.

**Comment by AlexKamaev** [comment]
We understand the issue. However, while `testcafe-browser-provider-selenium` or `aws deviceFarm` is not officially supported, we recommend you ask the authors of those repositories to help you.
