### ISSUE TITLE
es-next/compiler.js fails to resolve module after typescript successfully resolves and compiles it

### ISSUE THREAD

**Issue by cdaringe** [DevExpress/testcafe#7436]
### What is your Scenario?

I want to:

* use typescript
* use `tsconfig::compilerOptions::paths` (and `tsconfig::extends`, but not related to this issue)
* use testcafe

### What is the Current behavior?

Internally, the typescript compiler compiles `page.test.ts` fine. A downstream es-next compiler cannot resolve a module that the typescript compiler resolved.

### What is the Expected behavior?

Either not use the es-next compiler, or extend es-next compiler module resolution with paths as used from the typescript compiler.

### What is your public website URL? (or attach your complete example)

tiny, minimal reproduction posted here: https://github.com/cdaringe/testcafe-path-resolution-typescript

### What is your TestCafe test code?

```ts
// test/page.test.ts
import { foo } from "foo";
import { ClientFunction } from "testcafe";

fixture`foo`.page("http://localhost:3333");

const log = ClientFunction(() => console.log("sup"));

test("bar", async (t) => {
  foo();
  await log();
  await t.debug();
});
```

```ts
// src/foo.ts
export const foo = () => "bar";
```

### Your complete configuration file

none, cli only.

`DEBUG=testcafe* testcafe --compiler-options='typescript.configPath=tsconfig.json' chrome test/`

### Your complete test report

n/a

### Screenshots

```
Error: Cannot find module 'foo'
Require stack:
- /demo/test/page.test.ts
- /demo/node_modules/.pnpm/testcafe@2.2.0-rc.1/node_modules/testcafe/lib/compiler/test-file/formats/es-next/compiler.js
- /demo/node_modules/.pnpm/testcafe@2.2.0-rc.1/node_modules/testcafe/lib/compiler/compilers.js
- /demo/node_modules/.pnpm/testcafe@2.2.0-rc.1/node_modules/testcafe/lib/compiler/index.js
- /demo/node_modules/.pnpm/testcafe@2.2.0-rc.1/node_modules/testcafe/lib/runner/bootstrapper.js
- /demo/node_modules/.pnpm/testcafe@2.2.0-rc.1/node_modules/testcafe/lib/runner/index.js
- /demo/node_modules/.pnpm/testcafe@2.2.0-rc.1/node_modules/testcafe/lib/testcafe.js
- /demo/node_modules/.pnpm/testcafe@2.2.0-rc.1/node_modules/testcafe/lib/index.js
- /demo/node_modules/.pnpm/testcafe@2.2.0-rc.1/node_modules/testcafe/lib/cli/cli.js
- /demo/node_modules/.pnpm/testcafe@2.2.0-rc.1/node_modules/testcafe/lib/cli/index.js
```

### Steps to Reproduce

run the reproduction

### TestCafe version

2.2.0-rc.1

### Node.js version

18.4.0

### Command-line arguments

testcafe --compiler-options='typescript.configPath=tsconfig.json' chrome test/

### Browser name(s) and version(s)

chrome

### Platform(s) and version(s)

macos 12.6.1

### Other

n/a

**Comment by Aleksey28** [comment]
Hi @cdaringe,

You cannot override the `target` compiler option in the TypeScript configuration file. However, there is [PR](https://github.com/DevExpress/testcafe/pull/7411) that supports native ESM. You can use it once it is merged and published.

**Comment by cdaringe** [comment]
hey @Aleksey28 , thx for the reply. i've dropped `target` from the demo so as to keep this bug report focused on the resolution issue. indeed, i don't need that target, i just used a bunch of the defaults from `tsc --init`, but i appreciate the tip/ref regardless!

**Comment by Aleksey28** [comment]
Hi @cdaringe,

You're welcome. I'll close the issue. Feel free to contact us if you have further questions.

**Comment by cdaringe** [comment]
@Aleksey28  forgive me—the issue should not be closed. The issue should remain open. My above remark was politely stating that your suggestion is not relevant to this specific problem

**Comment by Aleksey28** [comment]
Ok. In this case, please update your example so that I can run it and reproduce this error.

**Comment by cdaringe** [comment]
@Aleksey28, the example is updated and runnable, with instructions in the repo. thanks!

**Comment by Aleksey28** [comment]
I managed to reproduce the issue. We will update this thread once we have any news.

**Comment by hendriku** [comment]
Thanks for providing a minimal example; I've already spent hours on debugging that in our project. Are there any known workarounds or versions where this bug is not present in?

**Comment by Klaster1** [comment]
@hendriku https://github.com/DevExpress/testcafe/issues/4144
