### ISSUE TITLE
Unable to run tests due to a TypeError when using nodejs 14.15.0 with the latest TestCafe version (2.2.0)

### ISSUE THREAD

**Issue by ayemelyanenko-chegg** [DevExpress/testcafe#7447]
### What is your Scenario?

Run tests using the latest TestCafe version (2.2.0)

### What is the Current behavior?

There is an error that prevents to run tests for all browsers when using the latest TestCafe version (2.2.0).

The error is:

`ERROR TypeError: dns_1.default.setDefaultResultOrder is not a function
    at new Proxy (/Users/ayemelyanenko/testcafe-examples/node_modules/testcafe-hammerhead/lib/proxy/index.js:75:23)
    at new TestCafe (/Users/ayemelyanenko/testcafe-examples/node_modules/testcafe/src/testcafe.js:30:30)
    at Object.construct (/Users/ayemelyanenko/testcafe-examples/node_modules/import-lazy/index.js:19:20)
    at createTestCafe (/Users/ayemelyanenko/testcafe-examples/node_modules/testcafe/src/index.js:93:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runTests (/Users/ayemelyanenko/testcafe-examples/node_modules/testcafe/src/cli/cli.js:92:22)
    at cli (/Users/ayemelyanenko/testcafe-examples/node_modules/testcafe/src/cli/cli.js:196:13)`

### What is the Expected behavior?

User should be able to run tests on all browsers when using the latest TestCafe version (2.2) and when using either npm or yarn.

### What is your public website URL? (or attach your complete example)

https://github.com/DevExpress/testcafe-examples

### What is your TestCafe test code?

The test examples are present in the attached repo from DevExpress

### Steps to Reproduce

1. Clone https://github.com/DevExpress/testcafe-examples
2. npm uninstall existing testcafe version (2.1)
3. npm install testcafe to get the latest TestCafe version (2.2)
4. Attempt to run tests by using npm test

### TestCafe version

2.2.0

### Node.js version

14.15.0

### Command-line arguments

npm test

**Comment by wombatka** [comment]
i have the same issue using Ubuntu 22.04.1 LTS , testcafe 2.2 and node 16.7.0

**Comment by pschmolke** [comment]
I have the exakt same issue on my Debian 5.10.158-2 Host with node v14.17.6 and npm v6.14.15.
My dockerized environment, which runs in CI systems with latest Alpine as it's base image, has also this TypeError with node v18.9.1 and npm v8.10.0

**Comment by ayemelyanenko-chegg** [comment]
@wombatka @pschmolke node version 14.20.1 seems to work so perhaps setting your node instances to that particular version could be used as a workaround until this issue is resolved.

**Comment by felis2803** [comment]
We are working on this issue: [https://github.com/DevExpress/testcafe-hammerhead/pull/2834](https://github.com/DevExpress/testcafe-hammerhead/pull/2834).

As a workaround, you can place this code before importing TestCafe:

```js
import dns from 'dns';

dns.setDefaultResultOrder = () => {}
```
