### ISSUE TITLE
Doesn't see a svg from a shadowRoot

### ISSUE THREAD

**Issue by AuthorSkN** [DevExpress/testcafe#7454]
### What is your Scenario?

My application displays a diagram as a svg and I need to test clicks on the elements of this diagram.  SVG of diagram wrapped in shadow DOM.

Whenever I try to click on any or expect any svg, I get the following:
```
An error occurred in Selector code:
      TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
```
      
    
      
  

### What is the Current behavior?

I find svg in shadow root using `Selector` but when I try to click it throws the error.

### What is the Expected behavior?

I can click SVG elements in the shadow DOM

### What is your public website URL? (or attach your complete example)

For example we can create simple component with shadow DOM:
[shadowDom-svg.zip](https://github.com/DevExpress/testcafe/files/10389760/shadowDom-svg.zip)

### What is your TestCafe test code?

```
fixture('Shadow dom svg test').page('./svg-component.html')

test("Shadow root find svg", async testController => {
    const rectElement = await Selector("my-chart").shadowRoot().find("rect");
    await testController.click(rectElement);
});

```

### Your complete test report

```
An error occurred in Selector code:

      TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

      Browser: Chrome 108.0.0.0 / Windows 10

         2 |
         3 |fixture('Shadow dom svg test').page('./svg-component.html')
         4 |
         5 |test("Shadow root find svg", async testController => {
         6 |    const rectElement = await Selector("my-chart").shadowRoot().find("rect");
       > 7 |    await testController.click(rectElement);
         8 |});
         9 |
```

### Screenshots

![image](https://user-images.githubusercontent.com/23282234/211744992-ddb134b6-ea30-46f3-8849-8c9c1d6720e5.png)

### Steps to Reproduce

1. Download the zip attached.
2. run npm install
3. run npm run start
4. Notice the problem.

### TestCafe version

1.20.1

### Node.js version

16.6.0

### Command-line arguments

npm run start

### Browser name(s) and version(s)

Edge latest, Chrome latest

### Platform(s) and version(s)

Windows 10

**Comment by Aleksey28** [comment]
Hi @AuthorSkN,

Thank you for the example. I managed to reproduce the issue. We will update this thread once we have any news.
