### ISSUE TITLE
Fix screenshots path in report for tests in quarantine mode

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#746]
Due to https://github.com/DevExpress/testcafe/pull/732#issuecomment-242022126
Now if we run test in quarantine mode in screenshotBase dir will be created three dirs:
```
-{task-start-date}
    -test-1
        -....
    -test-1-1
        -....
    -test-1-2
        -....
```
And in report will be specified last path: `{basePath}\{task-start-date}\test-1-2`.
We have two ideas to fix it:
1) specified several paths in report
2) or use for quarantine mode different way to save screenshots:
```
-{task-start-date}
    -test-1
        -run-1
            -...
        -run-2
            -...
        -run-3
            -...
```
for report we will use `{basePath}\{task-start-date}\test-1` path.

**Comment by helen-dikareva** [comment]
What do ypu think? @inikulin

**Comment by AlexanderMoskovkin** [comment]
I prefer the second way.
When quarantine mode enabled we use the following pattern: `{task-start-date}/test-{num}/run-{num}/{user-agent}/`
When quarantine mode disabled we use: `{task-start-date}/test-{num}/{user-agent}/`

In both cases we write in the report: `screenshots: {task-start-date}/test-{num}/`

Maybe someone has some other idea?

**Comment by inikulin** [comment]
Sounds good

**Comment by helen-dikareva** [comment]
ok
