### ISSUE TITLE
Interacting with iframe fires focusout and focus on Main Window

### ISSUE THREAD

**Issue by aquaductape** [DevExpress/testcafe#7473]
### What is your Scenario?

Interacting with iframe, suck as clicking.
```
await t.switchToIframe(`.container-div #iframe`).click("button");
```

### What is the Current behavior?

div container that has iframe, where iframe's button is clicked, fires "focusin" event and iframe element fires "focus" event.

### What is the Expected behavior?

div container shouldn't fire "focusin" event and iframe element shouldn't fire "focus" event. When interacting iframe in non-test browsers, not emitting focusin or focus is the expected behavior.

### What is your public website URL? (or attach your complete example)

Github repo: https://github.com/aquaductape/testcafe-iframe-mainpage-focus-bug

### What is your TestCafe test code?

```js
fixture`Test Focus`.page`./index.html`;

test("Dont fire focusin and focus events on Main Window", async (t) => {
  await t.switchToIframe(`.container-div #iframe`).click("button");
  await t.switchToMainWindow();
  const { error, log } = await t.getBrowserConsoleMessages();
  log.forEach((log) => console.log(log));
  // logs ['iframe focus fired', 'focusin fired'], when it should be empty array, since focusin shouldn't bubble from iframe and iframe focus shouldn't fire
  await t.expect(log.length).eql(0);
});
```

### Your complete configuration file

```js
const os = require("os");

module.exports = {
  skipJsErrors: false,
  hostname: os.hostname(),
  browsers: ["chrome"],
  src: ["./test-focus.js"],
};
```
### Your complete test report

```
> testcafe-focus-bug@1.0.0 test
> testcafe

 Running tests in:
 - Chrome 109.0.0.0 / Ventura 13

 Test Focus
iframe focus fired
focusin fired
 ✖ Dont fire focusin and focus events on Main Window

   1) AssertionError: expected 2 to deeply equal 0
      
      + expected - actual
      
      -2
      +0
      

      Browser: Chrome 109.0.0.0 / macOS 10.15.7

          4 |  await t.switchToIframe(`.container-div #iframe`).click("button");
          5 |  await t.switchToMainWindow();
          6 |  const { error, log } = await t.getBrowserConsoleMessages();
          7 |  log.forEach((log) => console.log(log));
          8 |  // logs ['iframe focus fired', 'focusin fired'], when it should be empty array, since focusin shouldn't bubble from iframe and iframe focus
      shouldn't fire
       >  9 |  await t.expect(log.length).eql(0);
         10 |});
         11 |

         at <anonymous> (/Users/caleb/Documents/just-programming/testcafe-iframe-mainpage-focus-bug/test-focus.js:9:30)
         at asyncGeneratorStep (/Users/caleb/Documents/just-programming/testcafe-iframe-mainpage-focus-bug/test-focus.js:1:114)
         at _next (/Users/caleb/Documents/just-programming/testcafe-iframe-mainpage-focus-bug/test-focus.js:1:452)



 1/1 failed (4s)
```

### Steps to Reproduce

1. Click iframe button

### TestCafe version

2.2.0

### Node.js version

v18.12.1

### Command-line arguments

`npm run test` which runs `testcafe`

### Browser name(s) and version(s)

Safari Version 16.3 (18614.4.6.1.5), Chrome Version 109.0.5414.87, Firefox 109.0 (64-bit)

**Comment by Aleksey28** [comment]
Hi @aquaductape,

I reproduced the issue. We need additional time to research it. Please bear with us. We will update this thread once we have any news.

**Comment by AlexKamaev** [comment]
The issue is fixed for the Chrome browser in Native Automation mode, which is enabled by default in TestCafe version 3.x.x. If you cannot use this mode in for some reason, please describe your usage scenario in greater detail.
