### ISSUE TITLE
TestCafe not loading page in 2.2.0/2.3.0 version.

### ISSUE THREAD

**Issue by GSAK-python** [DevExpress/testcafe#7481]
### What is your Scenario?

Upgrade TestCafe to 2.2.0 or 2.3.0 and run test script with "yarn" or "npm run".

### What is the Current behavior?

TestCafe session page is loaded but no further actions are taken

![image](https://user-images.githubusercontent.com/60710713/216270102-ea7df0eb-6b57-48c1-aa59-faf977dde725.png)

### What is the Expected behavior?

Test should be finished

TestCafe in version 2.1.0 works ok.

### What is your public website URL? (or attach your complete example)

https://testcafe.io/documentation/402635/getting-started

### What is your TestCafe test code?

import { Selector } from "testcafe";

```
fixture`Simple test 1`
    .page('https://testcafe.io/documentation/402635/getting-started')

test('Simple test 1', async t => {
    await t.expect(Selector('#header').exists).ok();
    const value = await Selector('#what-is-testcafe__\\$').innerText;
    await t.expect(value).eql('What Is TestCafe?');
});
```

### Your complete configuration file

testcafe-react-selectors@5.0.2
testcafe@2.3.0
@types/node@18.11.18
yarn 1.22.19
nodejs 19.5.0
nvm 1.1.9

### Your complete test report

No test result

### Screenshots

Screenshot uploaded in 'What is the Current behavior?'

### Steps to Reproduce

1. Run test script with _yarn_ or _npm run_ from directory with package.json file
2. 
3.

### TestCafe version

2.2.0/2.3.0

### Node.js version

19.5.0

### Command-line arguments
Package.sjon scirpt:
"simple": "testcafe chrome tests/simple.ts",

yarn simple
npm run simple

### Browser name(s) and version(s)

Chrome 109

### Platform(s) and version(s)

Windows 10.0.19044

### Other

What is weird test script is executing from VS code terminal. VS code launch.json settings:
```
       {
            "type": "node",
            "request": "launch",
            "name": "Chrome: REGULAR",
            "program": "${workspaceFolder}/main/test/e2e/node_modules/testcafe/bin/testcafe.js",
            "args": [
                "chrome",
                "${file}"
            ],
            "console": "integratedTerminal",
            "cwd": "${workspaceFolder}",
            "smartStep": true,
            "skipFiles": [
                "${workspaceFolder}/main//test/e2e/node_modules/**/*.js",
                "${workspaceFolder}/main//test/e2e/node_modules/**/**/*.js",
                "${workspaceFolder}/main/test/e2e/node_modules/**/**/**/*.js",
                "${workspaceFolder}/main/test/e2e/node_modules/**/**/**/**/*.js",
               ],
            "sourceMaps": true
        }

```

**Comment by GSAK-python** [comment]
I updated issue with new data. I hope it will help :)

**Comment by Aleksey28** [comment]
I cannot reproduce the issue. I followed these steps:
1. Created these files in a new repo:
```json 
//package.json
{
  "name": "tests",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "simple": "testcafe chrome tests/simple.ts"
  },
  "dependencies": {
    "testcafe": "2.3.0"
  }
}
```

```js
// tests/simple.ts

import { Selector } from "testcafe";

fixture`Simple test 1`
    .page('https://testcafe.io/documentation/402635/getting-started')

test('Simple test 1', async t => {
    await t.expect(Selector('#header').exists).ok();
    const value = await Selector('#what-is-testcafe__\\$').innerText;
    await t.expect(value).eql('What Is TestCafe?');
});
```
2. Installed the yarn:
```bash
yarn install
```
3. Run the commands:
```bash
node -v && testcafe -v && yarn simple
```
This is my console output:
![image](https://user-images.githubusercontent.com/32869530/216530150-37e983d5-95d9-4e49-87d8-f97b3fa95cd9.png)

Please check these steps and clarify what I miss.

>What is weird test script is executing from VS code terminal. VS code launch.json settings:

As I see in your screenshots, you run the script in the `Bash` terminal. What does this have to do with VS code terminal?

**Comment by GSAK-python** [comment]
1. I pointed out vscode terminal, because I can run my test with TestCafe 2.2.0/2.30 with vscode integrated terminal but not with yarn or npm run from bash.
![image](https://user-images.githubusercontent.com/60710713/216576686-682fc1ad-face-44fb-be2e-2c03d9529914.png)

2. The only difference I see is I do not have testcafe installed globally, only locally form package.json.
![image](https://user-images.githubusercontent.com/60710713/216577182-78781ddb-84e2-4bd4-a2a6-38580902ee33.png)

And it is working with testcafe 2.1.0

**Comment by GSAK-python** [comment]
I tried it on both, GitBash and PowerShell, result is the same, page is loaded and no further actions are taken.

![image](https://user-images.githubusercontent.com/60710713/217173244-dc4f37bc-9fc0-4523-aa71-54da49c0852e.png)

**Comment by Aleksey28** [comment]
Did you create a new project as described? If so, please run the test like this:

```cli
export DEBUG="testcafe:*,hammerhead:*" && testcafe chrome tests/simple.ts 2> testcafe.log
```

And share the created `testcafe.log` here.
