### ISSUE TITLE
Regression in 2.3.0

### ISSUE THREAD

**Issue by michael-mader** [DevExpress/testcafe#7482]
### What is your Scenario?

A regression was introduced in testcafe 2.3.0 which causes the following code to throw an error.

It used to run in older versions of testcafe and does not look faulty.

### What is the Current behavior?

Running the test fails with this message:
```
~/tmp/testcafe-bug »  npx testcafe chrome:headless
ERROR Cannot prepare tests due to the following error:

TypeError: _index.test.meta is not a function
    at Object.<anonymous> (/Users/user/tmp/testcafe-bug/tests/test.js:14:6)

Type "testcafe -h" for help.
```

### What is the Expected behavior?

the test runs without issues

### What is your public website URL? (or attach your complete example)

-

### What is your TestCafe test code?

```js
// this is working:
//import { Selector } from 'testcafe';
// this works also:
//import { Selector, fixture } from 'testcafe';
// this causes the described error message:
import { Selector, fixture, test } from 'testcafe';

const nameInput = Selector('#developer-name');

fixture `A set of examples that illustrate how to use TestCafe API`
    .page `https://devexpress.github.io/testcafe/example/`;

// Tests
test.meta('dev', 'true')('Text typing basics', async t => {
    await t
        .typeText(nameInput, 'Peter') // Type name
        .typeText(nameInput, 'Paker', { replace: true }) // Replace with last name
        .typeText(nameInput, 'r', { caretPos: 2 }) // Correct last name
        .expect(nameInput.value).eql('Parker'); // Check result
});
```

### Steps to Reproduce

1. create the testfile with the code above
2. run it either with `npx testcafe chrome` or whatever
3. see it fail

if you change to another kind of import in the first few lines it is working. It stops working as soon as `test` is imported from testcafe package (which makes typehints in your editor possible, that's why we have this somewhat redundant import)

### TestCafe version

2.3.0

### Command-line arguments

irrelevant

**Comment by Aleksey28** [comment]
Hi @michael-mader,

I reproduced the issue. As a workaround, you can put `meta` after the test function:

```js
test('Text typing basics', async t => {
    await t
        .typeText(nameInput, 'Peter') // Type name
        .typeText(nameInput, 'Paker', { replace: true }) // Replace with last name
        .typeText(nameInput, 'r', { caretPos: 2 }) // Correct last name
        .expect(nameInput.value).eql('Parker'); // Check result
}).meta('dev', 'true');
```

We will update this thread once we have news.

**Comment by michael-mader** [comment]
yes that works. I've tested it before but it is really tedious to change this for 200+ tests 😞 
For now I stick with the old version of testcafe until this is fixed
