### ISSUE TITLE
Provide DOM Node snapshot extensions mechanism

### ISSUE THREAD

**Issue by kirovboris** [DevExpress/testcafe#749]
I'm working on this.

**Comment by kirovboris** [comment]
We decide to add ```find``` method for DOM Node snapshot. This method will be looking for dom snapshot element on the page and after that looking for element inside of found DOM element. 
```find``` method should provide ```Selector``` functionality.
E.g. 
```javascript
var body = await Selector(() => document.body)();

t.click(body.find('#element'));
```

**Comment by kirovboris** [comment]
We need the name for extending snapshot method, e.g. ```extendSnapshot```
I assume the following use:
```javascript
var extendedSnapshot = await Selector('div', {
	extendSnapshot: (snapshot, node) => {
		snapshot.customField = node.tagName + '.' + node.className;

		return snapshot;
	}
})();
```
Also should we support ```function```, ```Selector```, ...  argument for ```find``` method? 
E.g. we can do:
```javascript
var body = await Selector(() => document.body)();

var button = body.find(cont => cont.firstElementChild);
```
/cc @inikulin @VasilyStrelyaev

**Comment by inikulin** [comment]
> We need the name for extending snapshot method, e.g. extendSnapshot
I assume the following use:

It should look good in `with` method, so I guess it should be:
```js
const selector = Selector('div', { snapshotExtension: () => {} }
```

> Also should we support function, Selector, ... argument for find method? 

Yes. it should all arguments that regular selector accepts, it just has `contexNode` argument always bound to it.

**Comment by inikulin** [comment]
BTW, we can alternative API:

```js
const selector = Selector('div', { 
    snapshotExtensions: {
        state: () => {}
    } 
}
```

This will add property `state` to snapshot. The good thing about this approach is that it will cooperate well with #771. We will be able to create property shortcuts for extensions.

**Comment by kirovboris** [comment]
> BTW, we can alternative API

Do you mean support alternative API(1) or implement instead of written above(2). It looks a little bit superfluous? I like (1) option.
E.g.
```javascript
var reactComponentHeight = snapshot.state.prop.height;
```

**Comment by VasilyStrelyaev** [comment]
> The good thing about this approach is that it will cooperate well with #771. 

And it also justifies the use of a noun `extensions`.

**Comment by kirovboris** [comment]
In according to #798 we don't need the ```find``` method anymore.
