### ISSUE TITLE
Error: aborted

### ISSUE THREAD

**Issue by andreaz-musement** [DevExpress/testcafe#7494]
### File a new question on StackOverflow

https://stackoverflow.com/questions/ask?tags=testcafe

**Comment by andreaz-musement** [comment]
Hello
it seems that there is nothing related to my error on stackoverflow. So, here I am to describe it and hopefully to find at least a way to debug it easily.
Sometime during the execution of my pipeline, I have seen this message "Error: aborted" as shown in attached image.
<img width="603" alt="Screenshot 2023-02-03 at 14 25 40" src="https://user-images.githubusercontent.com/118759910/216640042-fa62af59-661c-4f5e-b5b7-177852584f11.png">
It has randomly happened since last year and I cannot related to any of my changes. By now, there are 54 tests divided in two groups and executed in parallel. Please tell me if you need any further information.

Kinds regards.

**Comment by miherlosev** [comment]
Hi @andreaz-musement,

It looks like you are using an outdated browser version - `Chrome 97`. The current browser version is [109](https://en.wikipedia.org/wiki/Google_Chrome_version_history). Please update the browser version and run the tests again. Also, make sure you are using the latest testcafe version - `2.3.0`.
