### ISSUE TITLE
switchToIFrame() - add option timeout

### ISSUE THREAD

**Issue by fmancardi** [DevExpress/testcafe#7501]
### What is your Scenario?

In your documentation 
https://testcafe.io/documentation/402681/reference/test-api/testcontroller/switchtoiframe#wait-until-an-iframe-is-loaded

you suggest how to wait until iframe is loaded.

### What are you suggesting?

IMHO it will be great if you add the timeout option to the switchToIFrame() method

**Comment by Artem-Babich** [comment]
Hello, 

Thank you for your suggestion. Currently, the switchToIframe command uses the timeout you pass to its selector argument: [driver.js](https://github.com/DevExpress/testcafe/blob/master/src/client/driver/driver.js#L991).
We will consider adding a separate argument to the switchToIframe command after we collect enough user votes.

**Comment by patrickathompson** [comment]
User Vote

**Comment by Aleksey28** [comment]
Hi @patrickathompson,

If you want to vote, please react with the 'like' emoji to the main post.

**Comment by AlexKamaev** [comment]
We discussed the issue with the team and decided to close it. Since we already can pass the 'timeout' argument from Selector, so there is no need to add any additional options
