### ISSUE TITLE
Add selector property ".index" to capture the index of the element under its parent in the DOM

### ISSUE THREAD

**Issue by nathanbeme13** [DevExpress/testcafe#7507]
### What is your Scenario?

I am writing tests for several user-specified, dynamically generated tables. It is challenging to retrieve data from a specific table column when the columns are not always in the same order.

I want to get the DOM index of a given column header, then use that index to locate table data in the same column.
(e.g., I want to read the Country from the first row of a table. So I would like to get the index of the Country `<th>` element, and then get .innerText from the `<td>` element in the same column for a given row.)

While I can use `.child(n)` to find the nth element under its parent, I have not found a way to do the reverse -- i.e., to get the index of an element under its parent.

### What are you suggesting?

I would like for .index to be added as a selector property (ideally zero-indexed for consistency).

This example should return 1 for `columName.index`, indicating the second of three columns in this table:
```
import { Selector } from 'testcafe';

fixture `Fixture`
    .page('https://www.w3schools.com/html/html_tables.asp');

test('test', async t => {
    const columnName = Selector('th').withText('Contact')
    await t.expect(columnName.index).eql(1);
});
```

### What alternatives have you considered?

When `.innerText` returns text from multiple child elements, a newline character separates the different elements. Using that information, I can theoretically use `.split('\n')` to create a string array, then use `.indexOf()` to get the index of the column name.

```
const columnList = (await this.tableHeader.innerText).split('\n');
columnIndex = columnList.indexOf(columnName);
```

The trouble is, in this situation, `.innerText` also returns a lot of "junk" such as empty strings, hidden text, and other bits. This crowds out the header names I'm looking for.

I'm still looking for another workaround.

**Comment by Aleksey28** [comment]
Hi @nathanbeme13,

Thank you for the suggestion. This use case is quite rare and we can't accept it. Keep in mind that you can achieve the required behavior on your own by using the[`addCustomDOMProperties` method](https://testcafe.io/documentation/402759/reference/test-api/selector/addcustomdomproperties). For example:

```js
import { Selector } from 'testcafe';

function getColumnIndex(el) {
  return el.cellIndex;
}

const customDOMProperties = {
  index: getColumnIndex,
}

fixture`Fixture`
  .page('https://www.w3schools.com/html/html_tables.asp');

test('test', async t => {
  const columnName = Selector('th').withText('Contact').addCustomDOMProperties(customDOMProperties);

  await t.expect(columnName.index).eql(1)
});
```
