### ISSUE TITLE
401 error after upgrading to new version of test cafe

### ISSUE THREAD

**Issue by deepak30051982** [DevExpress/testcafe#7513]
### What is your Scenario?

Automating a website using testcafe
The issue is while authenticating with windows auth
We are getting a 401 unauthorized exception
 
We used the below version
Node version 14 or later
Test cafe version 1.13 or later

The same scripts working in below version

Node version 14
Test cafe version 1.13 or below

Writing our scripts in vscode
Testing in edge chromium 
We are using .httpAuth with username, password, and domain. We tried without domain.

We tried to find out SendRequest method in hammerhead but could not find

### What is the Current behavior?

while authenticating with windows auth
We are getting a 401 unauthorized exception

### What is the Expected behavior?

The browser popup for credential would come and post authentication should go to the home page

### What is your public website URL? (or attach your complete example)

Na

### What is your TestCafe test code?

Na

### Steps to Reproduce

1.
2.
3.

### TestCafe version

1.13+

### Node.js version

14

### Command-line arguments

Na

**Comment by deepak30051982** [comment]
Hello Thank you team,

We are trying in client regulated environment and application which we are testing is an INTRANET web site.
It is only doing logging in using windows authentication and going to a particular url
It is working in an older version of testcafe with the same scripts.
Only issue with apps having windows authentication

Can you help with the below

1. Is there any specific library that we should look for that is required for Windows authentication but may not have been installed during the upgrade?
2. Could you provide us with a file/class in a node module that we can debug to better understand window authentication so that we can see if any specific arguments, such as the header, are passed or not?
3. Any alternative to .httpAuth, which resembles Windows authentication and works in both earlier and later versions
4. Is there a difference in the creation of webproxies in recent versions that is preventing Windows authentication?

**Comment by marcHalewyn** [comment]
We are experiencing exactly the same issue. We are stuck on version 1.14 of testcafe because of this.

**Comment by AlexKamaev** [comment]
Hello @deepak30051982
>Is there any specific library that we should look for that is required for Windows authentication but may not have been installed during the upgrade?

NTLM authentication in TestCafe is implemented in the [https://github.com/DevExpress/testcafe-hammerhead](https://github.com/DevExpress/testcafe-hammerhead) module. The `testcafe-hammerhead` module uses the `webauth` module to add credentials to the request options.
>Could you send us a file/class in a node module that we can debug to understand window authentication better and see if any specific arguments, such as the header, are passed?

Sure, you can start with the `_onResponse` method in `testcafe-hammerhead` here:
[https://github.com/DevExpress/testcafe-hammerhead/blob/3e60530b9ebcfdd176878905102c98609ef533e6/src/request-pipeline/destination-request/index.ts#L176](https://github.com/DevExpress/testcafe-hammerhead/blob/3e60530b9ebcfdd176878905102c98609ef533e6/src/request-pipeline/destination-request/index.ts#L176)
Then, you can go with the `_resendWithCredentials` method:
[https://github.com/DevExpress/testcafe-hammerhead/blob/3e60530b9ebcfdd176878905102c98609ef533e6/src/request-pipeline/destination-request/index.ts#L204](https://github.com/DevExpress/testcafe-hammerhead/blob/3e60530b9ebcfdd176878905102c98609ef533e6/src/request-pipeline/destination-request/index.ts#L204)
The idea of the `httpAuth` is resending the initial request if the response status code is 401.

>Any alternative to .httpAuth, which resembles Windows authentication and works in both earlier and later versions

TestCafe only assumes using the `httpAuth` method.
>Is there a difference in the creation of webproxies in recent versions that is preventing Windows authentication?

There should not be any difference. This code has not been changed in recent years.
