### ISSUE TITLE
URL link does not point to the set page

### ISSUE THREAD

**Issue by Nikolaj1010** [DevExpress/testcafe#7519]
### What is your Scenario?

It seems that hyperlink does not point to the set page (google.com in this case) when new window is open in Testcafe

### What is the Current behavior?

When I click on the link the new window is open but the URL contains my IP address with some error instead of "google.com"

### What is the Expected behavior?

When I click on the link the new window should be open with set URL "google.com"

### What is your public website URL? (or attach your complete example)

```
<!DOCTYPE html>
<html>
<body>

<a id="link" href="https://www.google.com/">go to google.com</a>

</body>
</html>
```

### What is your TestCafe test code?

```
import {ClientFunction, Selector, t} from 'testcafe';

test.only('Should check that link to google works as intended', async () => {
    await t
        .wait(2000)
        .click(Selector('#link'));

    // ensure correct url opens in the new window
    const getLocation = ClientFunction(() => {
        return window.location.href;
    });
    await t.expect(getLocation()).contains('https://www.google.com/');
});
```

### Your complete test report

![newWindowLink](https://user-images.githubusercontent.com/32637406/219601889-34b3429a-0556-4350-be4c-5db1821029d8.png)

### Steps to Reproduce

1. Click on hyperlink
2. Check the URL of the new open window

### TestCafe version

2.3.0

### Node.js version

16.17.1

### Command-line arguments

testcafe chrome *.ts (running my .ts file inside my project where the test is located)

### Browser name(s) and version(s)

Chrome 110.0.0.0

### Platform(s) and version(s)

Windows 10

**Comment by Aleksey28** [comment]
Hi @Nikolaj1010,

I didn't manage to reproduce the issue. I created files and run them using v2.3.0 of TestCafe and v16.19.0 of Node.js:
```html
<!-- index.html -->
<!DOCTYPE html>
<html>
<body>
  <a id="link" href="https://www.google.com/">go to google.com</a>
</body>
</html>
```

```js
// test.js
import { ClientFunction, Selector } from "testcafe";

fixture('My fixture')
  .page('./index.html');
test('Should check that link to google works as intended', async t => {
  await t
    .wait(2000)
    .click(Selector('#link'));

  // ensure correct url opens in the new window
  const getLocation = ClientFunction(() => {
    return window.location.href;
  });
  await t.expect(getLocation()).contains('https://www.google.com/');
});
```
Please check your example again. I see that you don't have `t` in arguments of your test function. Is it imported in the file? Also, I noticed that you use the CLI command `testcafe chrome *.html`. Make sure that you run the file with the test script, for example, `testcafe chrome test.js`.

**Comment by Nikolaj1010** [comment]
Hi @Aleksey28,

You are right, `t`  argument is imported in my .ts file where the test is located. I also changed the description and added the test report printscreen so I hope that all is clear now

**Comment by Aleksey28** [comment]
I still cannot reproduce the issue.

My log:
![image](https://user-images.githubusercontent.com/32869530/220056073-d889f8b6-e547-45ac-933b-cd7c2775d5b3.png)
My test file: 
```js
// test.js
import { ClientFunction, Selector, t } from "testcafe";

fixture('My fixture')
  .page('./index.html');
test('Should check that link to google works as intended', async () => {
  await t
    .wait(2000)
    .click(Selector('#link'));

  // ensure correct url opens in the new window
  const getLocation = ClientFunction(() => {
    return window.location.href;
  });
  await t.expect(getLocation()).contains('https://www.google.com/');
});
```

Please create a new project that illustrates this issue.

**Comment by Nikolaj1010** [comment]
It seems that the problem was ultimately on my side so I am sorry for the misunderstanfing.

**Comment by Aleksey28** [comment]
No worries. Feel free to contact us at any time.
