### ISSUE TITLE
getCookies not returning some cookies

### ISSUE THREAD

**Issue by jawadst** [DevExpress/testcafe#7520]
### What is your Scenario?

I am trying to test that a specific cookie is created (in JavaScript) by the page that I am testing.

### What is the Current behavior?

`getCookies` returns an empty array

### What is the Expected behavior?

`getCookies` should return the cookie that was created by the tested page

### What is your public website URL? (or attach your complete example)

No public URL ; see TestCafe test code that should be self sufficient

### What is your TestCafe test code?

```js
fixture`FixtureCookie`.page('http://localhost:8081/');

test('Creates a cookie', async t => {
  await t.eval(() => (document.cookie = 'favorite_food=tripe'));

  let cookies = await t.getCookies('favorite_food');

  console.log({ cookies });

  await t.expect(cookies.length).gte(1);
});

```

### Your complete configuration file

No config

### Your complete test report

 Running tests in:
 - Chrome 110.0.0.0 / Ventura 13

 FixtureCookie
{ cookies: [] }
 ✖ Creates a cookie

   1) AssertionError: expected 0 to be at least 1

      + expected - actual

      -0
      +1

      Browser: Chrome 110.0.0.0 / macOS 10.15.7

          5 |
          6 |  let cookies = await t.getCookies('favorite_food');
          7 |
          8 |  console.log({ cookies });
          9 |
       > 10 |  await t.expect(cookies.length).gte(1);
         11 |});
         12 |

         at <anonymous> (/secure-cookies.js:10:34)
         at asyncGeneratorStep (/secure-cookies.js:1:114)
         at _next (/secure-cookies.js:1:452)

### Screenshots

The cookie correctly appears in Chrome Devtools:

<img width="1592" alt="Screenshot 2023-02-16 at 6 13 11 PM" src="https://user-images.githubusercontent.com/584597/219532023-c1d86022-421e-40a1-9596-8b60c6f7efd1.png">

### Steps to Reproduce

Simply run the provided test

### TestCafe version

2.3.0

### Node.js version

16.16.0

### Command-line arguments

testcafe chrome /secure-cookies.js

### Browser name(s) and version(s)

Chrome 110

### Platform(s) and version(s)

Mac OS

**Comment by jawadst** [comment]
I did some more testing and the test passes when enabling proxyless mode.

**Comment by Aleksey28** [comment]
Hi @jawadst,

I managed to reproduce the issue. But it happens only if you set cookies with `ClientFunction` or `t.eval`. If you set cookies directly on the page, the `getCookies` method will return them. I recommend you replace setting cookies with `ClientFunction` or `t.eval` to the [`setCookies`](https://testcafe.io/documentation/403872/reference/test-api/testcontroller/setcookies) method.

**Comment by jawadst** [comment]
Hi @Aleksey28,

Thanks for taking a look. I see the same problem if I set the cookie on a test page instead of via `t.eval` in the test.

Example HTML:

```html
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script type="text/javascript">
      document.cookie = 'favorite_food';
    </script>
  </head>

  <body></body>
</html>
```

And the test that is failing:

```js
fixture`FixtureCookie`.page('http://localhost:8081/page.html');

test('Creates a cookie', async t => {
  let cookies = await t.getCookies();

  console.log({ cookies });

  await t.expect(cookies.length).gte(1);
});
```

Here again, the test is failing while the cookie shows in the DevTools:
<img width="1680" alt="Screenshot 2023-02-21 at 6 28 17 PM" src="https://user-images.githubusercontent.com/584597/220505434-9a48233e-0629-4edf-bf4a-0fba8c8b026a.png">

I wrote those tests as the smallest reproducible test cases that would fail to submit them here but I am generally seeing that TestCafe misses cookies in `getCookies` when testing with our full application as well (that sets cookies with `document.cookie` in JS). We generally see some cookies but not all of them. Could it be related to setting cookies client-side via `document.cookie`?

**Comment by Aleksey28** [comment]
I managed to reproduce the issue. We will update this thread once we have any news.

As a workaround, you can use the [`--experimental-proxyless`](https://testcafe.io/documentation/404237/guides/experimental-capabilities/proxyless-mode) option. We are actively working on this mode.

**Comment by miherlosev** [comment]
Hi @jawadst,

This issue is not reproduced with combination of `testcafe@3.0.1` and the Google Chrome browser. Feel free to reopen this issue if you encounter it in other browsers.
