### ISSUE TITLE
t.request() not working with proxyless

### ISSUE THREAD

**Issue by BenDriesen** [DevExpress/testcafe#7523]
### What is your Scenario?

When sending api requests with the experimental proxyless feature, the test directly fails with a type error:

TypeError: Cannot read properties of null (reading 'proxy')

When proxyless is disabled, this works fine

### What is the Current behavior?

Test fails with TypeError: Cannot read properties of null (reading 'proxy')

### What is the Expected behavior?

API request is executed similarly as without proxyless

### What is your public website URL? (or attach your complete example)
`https://google.com`

### What is your TestCafe test code?
`test('Request google page', async t => {
  const res = await t.request('https://google.com')
})`

### Your complete configuration file

`{
    "experimentalProxyless": true
}`

### Your complete test report

` ✖ Request google page

   1) TypeError: Cannot read properties of null (reading 'proxy')`

### Steps to Reproduce

1. Create a request with t.request() and execute the request without the proxyless setting enabled, the test runs fine
2. Now run the same test with --experimental-proxyless. The test now fails with a type error

### TestCafe version

2.3.1

### Node.js version

19.0.1

### Command-line arguments

testcafe chrome test.js --experimental-proxyless

### Browser name(s) and version(s)

Chrome 109.0.0.0

### Platform(s) and version(s)

macOS 10.15.7

**Comment by BenDriesen** [comment]
@Artem-Babich, I've added an example

**Comment by miherlosev** [comment]
Hi @BenDriesen,

Support for the `t.request` action was implemented in [https://github.com/DevExpress/testcafe/pull/7504](https://github.com/DevExpress/testcafe/pull/7504).
This feature will be available in the next release.
