### ISSUE TITLE
Add capability running tests on 'pCloudy' cloud browser

### ISSUE THREAD

**Issue by Advinsteve** [DevExpress/testcafe#7533]
### What is your Scenario?

I like to run the test case in the browser available in cloud not in browserstack or Sauselab I like to run in pCloudy it's also a cloud platform

### What are you suggesting?

capabilities require for authentication and connections are 
                
osVersion
browserVersion;
clientName
apiKey
email

**Comment by felis2803** [comment]
Hi @Advinsteve,

To solve this problem, you need your own browser provider. [generator-testcafe-browser-provider](https://github.com/DevExpress/generator-testcafe-browser-provider) will help you with this. Also, the following topic will be useful: [Browser Provider Plugin](https://testcafe.io/documentation/402812/guides/extend-testcafe/browser-provider-plugin).
