### ISSUE TITLE
Issue with button click with experimentalProxyless=true

### ISSUE THREAD

**Issue by aprabh001c** [DevExpress/testcafe#7535]
### What is your Scenario?

When experimentalProxyless=true, testcafe is not clicking _search button mentioned in below script ( or after clicking browser is not responding) and it fails

This is related to https://github.com/DevExpress/testcafe/issues/6861 (without experimentalproxyless mode we are hitting issue #6891)

_Script Used to reproduce with Public Website_
import {t, Selector} from 'testcafe'

fixture `UnHandledException`

test(`UnhandledExceptionTC`, async tn=>{
    const _addressField = Selector('#Address_SingleStreetAddress,input[name="localizationAddressField"]');
    const _search = Selector(".localization-container button[type='submit']");

await t.navigateTo("https://www.xfinity.com/learn/offers");
await t.wait(10000);
await t.typeText(_addressField,"200 MAIN ST, NORTHAMPTON, MA 01060",{paste:true})
await t.wait(2000)
await t.click(_search)
await t.expect(_search.visible).notOk();

})

### What is the Current behavior?

button not clicked or not responding

### What is the Expected behavior?

Should proceed to next step

### What is your public website URL? (or attach your complete example)

https://www.xfinity.com/learn/offers

### What is your TestCafe test code?

import {t, Selector} from 'testcafe'

fixture `UnHandledException`

test(`UnhandledExceptionTC`, async tn=>{
    const _addressField = Selector('#Address_SingleStreetAddress,input[name="localizationAddressField"]');
    const _search = Selector(".localization-container button[type='submit']");

await t.navigateTo("https://www.xfinity.com/learn/offers");
await t.wait(10000);
await t.typeText(_addressField,"200 MAIN ST, NORTHAMPTON, MA 01060",{paste:true})
await t.wait(2000)
await t.click(_search)
await t.expect(_search.visible).notOk();

})

### Your complete configuration file

experimentalProxyless=true

### Steps to Reproduce

import {t, Selector} from 'testcafe'

fixture `UnHandledException`

test(`UnhandledExceptionTC`, async tn=>{
    const _addressField = Selector('#Address_SingleStreetAddress,input[name="localizationAddressField"]');
    const _search = Selector(".localization-container button[type='submit']");

await t.navigateTo("https://www.xfinity.com/learn/offers");
await t.wait(10000);
await t.typeText(_addressField,"200 MAIN ST, NORTHAMPTON, MA 01060",{paste:true})
await t.wait(2000)
await t.click(_search)
await t.expect(_search.visible).notOk();

})

### TestCafe version

2.3.0

### Node.js version

19.3.0

### Command-line arguments

testcafe chrome -F UnHandledException

**Comment by AlexKamaev** [comment]
Thank you for the example. I managed to reproduce the problem. The actual issue is not with the `click` action, but with some XHR request that is related to the `click` action. We'll research it.

**Comment by patrickathompson** [comment]
I am also experiencing this issue. After enabling proxyless mode in 2.4.0, a button click is no longer functioning. Proxyless mode is needed because the page cannot be tested with hammerhead-js due to its bugs.

**Comment by AlexKamaev** [comment]
@patrickathompson the original issue is very specific. It's unlikely that you have a similar one. Please create a separate issue and share an example using this [template](%5Bhttps://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&template=bug_report.yaml%5D(https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&template=bug_report.yaml)).

**Comment by patrickathompson** [comment]
I appreciate the advice. I was able to find a way to hack around my issue. His example seems to be a very general usecase (not a specific one) of utilizing .click() in a test. It appears that testcafe behavior is different between proxy vs proxyless mode. Once proxyless mode is enabled code that worked to click a button no longer works in the same manner. It's likely that if I created a ticket on this issue it would get the same attention and support as the current one. It is unlikely that there has been any progress on resolving the issue. You have to ask yourself, how good is a test framework that cannot click a button reliably? How critical is this type of bug for a test framework?

**Comment by AlexKamaev** [comment]
@aprabh001c
I cannot reproduce the issue anymore. Please try updating your TestCafe version to 2.5.0 and try the test again.

**Comment by aprabh001c** [comment]
Hi 
Thank you for your response
I am able to see this issue in 2.5 as well.
Node version - 18.16.0
Browser  - Chrome  112.0.5615.138
configuration:
  "nativeAutomation": "true"
Please let me know if i need to provide more details

with   "nativeAutomation": "false", we are seeing Error: Session closed with error code 11 for no reason

**Comment by AlexKamaev** [comment]
I've recorded a video to demonstrate that TestCafe handles a button click correctly. Please take a look at the attached video file.
Please also try using the following TestCafe version: [https://www.npmjs.com/package/testcafe/v/2.5.1-rc.1](https://www.npmjs.com/package/testcafe/v/2.5.1-rc.1)
If the issue persists, record a video that demonstrates the issue. Use the following command to record such a video:
`npx testcafe chrome test.js -e --native-automation --video artifacts`


https://user-images.githubusercontent.com/1678902/235848409-ccbeefc7-42e5-43d9-b4d2-ea4df8bc0875.mp4

**Comment by aprabh001c** [comment]
I am not seeing this issue with 2.5.1-rc.1 version, but hitting another issue, which is not related to this. I will raise a new issue for that. Thank you for your support.
