### ISSUE TITLE
Test get stuck if `testName` contains more than one singlequote

### ISSUE THREAD

**Issue by georgiy-abbasov** [DevExpress/testcafe#754]
Test to reproduce:
```js
fixture `Simple demo`
    .page `http://example.com`;

test("one'two'three", async t => {
    await t.click('body');
});
```
We will get this on the client:
![2016-09-06_1450](https://cloud.githubusercontent.com/assets/15088565/18272652/931b9a00-7441-11e6-8ff4-1723e44df485.png)

**Comment by inikulin** [comment]
Same applies to `fixtureName` I guess

**Comment by inikulin** [comment]
Is anyone working on this? Because we need to fix it ASAP

**Comment by AlexanderMoskovkin** [comment]
I'll do it soon

**Comment by inikulin** [comment]
@AlexanderMoskovkin Should be fixed very easy by using RegExp with `g` flag here, instead of string: https://github.com/DevExpress/testcafe/blob/master/src/test-run/index.js#L80

But we need regression test as well

**Comment by AlexanderMoskovkin** [comment]
I'm working on this
