### ISSUE TITLE
can't able to  close pop window and take screenshot of popup window.

### ISSUE THREAD

**Issue by LakshmiYaswanth** [DevExpress/testcafe#7544]
### What is your Scenario?

can't able to  close pop window and take screenshot of popup window.

1.Load URl('https://www.quackit.com/html/codes/html_popup_window_code.cfm')
2.Click on popup link
3.Take screenshot of popup window.

### What is the Current behavior?

TypeError: Cannot read properties of undefined (reading 'windowDescriptors')
    at BrowserProviderPluginHost.setWindowDescriptor (automation\node_modules\testcafe\src\browser\provider\built-in\dedicated\base.js:37:21)
    at BrowserProvider._setWindowDescriptor (automation\node_modules\testcafe\src\browser\provider\index.ts:100:25)
    at BrowserProvider._ensureBrowserWindowDescriptor (automation\node_modules\testcafe\src\browser\provider\index.ts:193:18)
    at BrowserProvider._ensureBrowserWindowParameters (automation\node_modules\testcafe\src\browser\provider\index.ts:198:9)
    at BrowserProvider.openBrowser (automation\node_modules\testcafe\src\browser\provider\index.ts:319:13)
    at BrowserConnection._runBrowser (automation\node_modules\testcafe\src\browser\connection\index.ts:186:13)

### What is the Expected behavior?

User should able to close popup window and take screenshot of popup window.

### What is your public website URL? (or attach your complete example)

('https://www.quackit.com/html/codes/html_popup_window_code.cfm')

### What is your TestCafe test code?

fixture('New Window Feature')
.page('https://www.quackit.com/html/codes/html_popup_window_code.cfm');
test('New Window Opened Automatically After Click ', async t => {
let url;
let ytSelector = Selector('p>a');
url = await t.eval(() => document.documentURI);
console.log('Main URL: '+ url);
await t.expect(url).eql('https://www.quackit.com/html/codes/html_popup_window_code.cfm');
await t.switchToIframe("iframe.result").click(ytSelector);
url = await t.eval(() => document.documentURI);
console.log(url);
await t.expect(url).eql('https://www.quackit.com/preview/preview_example_code.cfm');
await t.closeWindow()
await t.switchToParentWindow();
await t.switchToIframe("iframe.result").click(ytSelector);
await t.expect(ytSelector.exists).ok();
});

### Your complete configuration file

{
"browsers": "chrome",
"src": "tests/dataDriven/*.js",
"screenshots": {
"path": "./configuration_file/screenshots/",
"takeOnFails": true,
"fullPage": false
},
"videoPath": "./configuration_file/videos/",
"skipJsErrors": true,
"concurrency": 1,
"selectorTimeOut": 5000,
"assertionTimeOut": 5000,
"pageLoadTimeOut": 5000,
"speed": 1

}

### Steps to Reproduce

1.
2.
3.

### TestCafe version

1.14.2

### Node.js version

v16.17.0

### Command-line arguments

testcafe chrome test.spec.ts

### Browser name(s) and version(s)

chrome 110 

### Platform(s) and version(s)

Windows

**Comment by LakshmiYaswanth** [comment]
Still issue exists in testcafe with version 2.3.1. We can't able to close to window pop and cant able to take screenshot popup. Is there any other way to achieve this functionality.

**Comment by felis2803** [comment]
There are several errors in your test:
1. After `.closeWindow()`, you don't need to call `.switchToParentWindow()` because at this stage, there will be only one window left, and you will be automatically switched to it.
2. After closing the popup window, you try to open it again: `.switchToIframe("iframe.result").click(ytSelector)`. Remove the `.click(ytSelector)` action from this line.

After fixing these bugs, a bit of formatting, and adding the `.takeScreenshot()` action, I ended up with this test:
```js
import { Selector } from 'testcafe';

fixture('New Window Feature')
    .page('https://www.quackit.com/html/codes/html_popup_window_code.cfm');

test('New Window Opened Automatically After Click ', async t => {
    let url;
    let ytSelector = Selector('p>a');

    url = await t.eval(() => document.documentURI);

    console.log('Main URL: '+ url);

    await t
        .expect(url).eql('https://www.quackit.com/html/codes/html_popup_window_code.cfm')
        .switchToIframe("iframe.result").click(ytSelector);

    url = await t.eval(() => document.documentURI);

    console.log(url);

    await t
        .expect(url).eql('https://www.quackit.com/javascript/examples/sample_popup.cfm')
        .takeScreenshot()
        .closeWindow()
        .switchToIframe("iframe.result")
        .expect(ytSelector.exists).ok();
});
```
It runs successfully, and a screenshot of the popup is taken correctly.
As for the `TypeError: Cannot read properties of undefined (reading 'windowDescriptors')` error, I didn't encounter it after several attempts to restart the test.

**Comment by LakshmiYaswanth** [comment]
It working fine but in some  application(like react  application ) is not working. Do we have any option to change view from window  to  another window.

**Comment by felis2803** [comment]
Please give an example where this does not work.
Also, please clarify what you mean by "any option to change view from window to another window". Is the [t.switchToWindow](https://testcafe.io/documentation/402680/reference/test-api/testcontroller/switchtomainwindow) family of functions of the [Multiple Browser Windows](https://testcafe.io/documentation/402841/guides/intermediate-guides/multiple-browser-windows) mechanism not what you need?
