### ISSUE TITLE
Issues with testcafe Intellij plugin and proxyless

### ISSUE THREAD

**Issue by wombatka** [DevExpress/testcafe#7547]
### What is your Scenario?

After update to version 2.3.1 and adding    "experimentalProxyless": "true",
 to my .testcaferc.json I face issues when running tests from intellij using testcafe intellij plugin (latest version)
- first attempt to run test fails with error immediatelly after browser appears
ERROR Unable to open the "chrome:" browser due to the following error:

TypeError: Cannot read property 'Fetch' of undefined
    at Proxyless.init (/home/asia/WAS/testCafe-was-gui-tests/node_modules/testcafe/src/proxyless/index.ts:44:28)
    at BrowserProviderPluginHost._setupProxyless (/home/asia/WAS/testCafe-was-gui-tests/node_modules/testcafe/src/browser/provider/built-in/dedicated/chrome/index.js:53:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at BrowserProviderPluginHost.openBrowser (/home/asia/WAS/testCafe-was-gui-tests/node_modules/testcafe/src/browser/provider/built-in/dedicated/chrome/index.js:96:13)
    at BrowserProvider.openBrowser (/home/asia/WAS/testCafe-was-gui-tests/node_modules/testcafe/src/browser/provider/index.ts:325:9)
    at BrowserConnection._runBrowser (/home/asia/WAS/testCafe-was-gui-tests/node_modules/testcafe/src/browser/connection/index.ts:267:13)

when try to run for the second time- test runs without issues

- when try to use livemode- browser is opened but it is empty and test does not start nor finish
![image](https://user-images.githubusercontent.com/25752375/222650065-ee5429e7-59a1-4d7f-bab1-2e01b54399c4.png)

### What is the Current behavior?

proxyless causes problems with running tests from intellij using testcafe intellij plugin

### What is the Expected behavior?

There should be no issues with proxyless and intellij 

### What is your public website URL? (or attach your complete example)

no public url

### What is your TestCafe test code?

just run any test from intellij

### Your complete configuration file

.testcaferc.json

{
  "screenshots": {
    "path": "testoutput/screenshots",
    "pathPattern": "${FIXTURE}/${TEST}_${DATE}_${TIME}_${USERAGENT}_${QUARANTINE_ATTEMPT}_${FILE_INDEX}.png",
    "takeOnFails": true,
    "fullPage": true
  },
  "assertionTimeout": 10000,
  "selectorTimeout": 3000,
  "skipJsErrors": true,
  "experimentalProxyless": "true",
  "reporter": [
    {
      "name": "spec-time"
    },
    {
      "name": "xunit",
      "output": "testoutput/reports/xunitreport.xml"
    }
  ]
}

### Steps to Reproduce

1.run test  from intellij with testcafe plugin
2.
3.

### TestCafe version

2.3.1

### Node.js version

16.7.0

### Command-line arguments

no command- run with plugin

### Browser name(s) and version(s)

Chrome 110.0.0.0 / Linux 0.0

### Platform(s) and version(s)

Ubuntu 22.04.2 LTS

**Comment by miherlosev** [comment]
Hi @wombatka,

> After update to version 2.3.1 and adding "experimentalProxyless": "true", to my .testcaferc.json I face issues when running tests from intellij using testcafe intellij plugin (latest version)

If the issue is reproduced without the `IntelliJ` plugin, please share an example that illustrates it.
If the issue reproduced only with the `IntelliJ` plugin, address your feedback to the owner of this plugin.
