### ISSUE TITLE
Cannot execute the test when it is redirected to another application with auth token in the URL  

### ISSUE THREAD

**Issue by pragmatictesters** [DevExpress/testcafe#7548]
### What is your Scenario?

Log in to the application with valid credentials. 
Click on the Quik Update icon on the left and the menu (side bar)

### What is the Current behavior?

A white screen is loaded, and the user is not directed to the application.

Following is shown in the URL 
http://192.168.1.102:65486/IcH97oB0G*czEtTUt9m/about:error

### What is the Expected behavior?

Test should be directed to the quick update page 

### What is your public website URL? (or attach your complete example)

"base_url" : "https://test.cammsrisk.com.au/CammsRisk"
  "OrganizationName": "Auto_Risk_Incident"
  "UserName": "jsmith"
  "Password": "3l@st!c5ity6"

### What is your TestCafe test code?

import { Selector } from "testcafe";

fixture('TestCafe SOF Quation -1 ').page("https://test.cammsrisk.com.au/CammsRisk")

test("Quick demo of the issue",async (t) => {
    
    console.log("Starting the test")
    await t
        .typeText(Selector('#LoginControlSAAS_txtOrganisation'), "Auto_Risk_Incident")
        .typeText(Selector('#LoginControlSAAS_txtUsername'), "jsmith")
        .typeText(Selector('#LoginControlSAAS_txtPassword'), "3l@st!c5ity6")
        .click(Selector('#LoginControlSAAS_btnLogin'))
        .click(Selector("#ctl00_WelcomeControlSAAS_aMyQuickUpdate"))
       .expect(Selector("#mainContainer>span").textContent).contains("My Quick Update")
        .debug()
})

### Your complete configuration file

module.exports=
{
    "browsers": [
        "chrome:headless"
    ],
    "concurrency": 1,
    "developmentMode": false,
    "screenshots": {
        "takeOnFails": true,
        "path":"artifacts/screenshots",
        "fullPage": true
    },
    "selectorTimeout": 120001,
    "skipJsErrors": true,
    "baseUrl": "https://test.cammsrisk.com.au/CammsRisk",
    "userVariables": {
        "base_url" : "https://test.cammsrisk.com.au/CammsRisk",
        "OrganizationName": "Auto_Risk_Incident",
        "UserName": "jsmith",
        "Password": "3l@st!c5ity6",
        "serverId": "",
        "serverDomain": "",
        "mailosaurApiKey": ""
    },
    "assertionTimeout": 120000
}

### Your complete test report

he "browsers" option from the configuration file will be ignored.
 Running tests in:
 - Chrome 110.0.0.0 / Monterey 12

 TestCafe SOF Quation -1 
Starting the test
 ✖ Quick demo of the issue

   1) Failed to load the page at "https://test.cammsrisk.com.au/CammsRisk/Authorised/Home/MyUpdateHome.aspx".
      Increase the value of the "pageRequestTimeout" variable, enable the "retryTestPages" option, or use quarantine mode to
      perform additional attempts to execute this test.
      You can find troubleshooting information for this issue at "https://go.devexpress.com/TestCafe_FAQ_ARequestHasFailed.aspx".
      
      Error details:
      Failed to complete a request to "https://test.cammsrisk.com.au/CammsRisk/Authorised/Home/MyUpdateHome.aspx" within the
      timeout period. The problem may be related to local machine's network or firewall settings, server outage, or network
      problems that make the server inaccessible.

      Browser: Chrome 110.0.0.0 / macOS 10.15.7

 1/1 failed (1m 15s)

 Warnings (1):
 --
  The "browsers" option from the configuration file will be ignored.

### Steps to Reproduce

1.
2.
3.

### TestCafe version

2.3.0

### Node.js version

v18.13.0

### Command-line arguments

testcafe chrome testSuite/tests/stackoverflow-q.ts 

### Platform(s) and version(s)

macOS 12.6

**Comment by pragmatictesters** [comment]
Apparently the issue is due to local configuration

**Comment by pragmatictesters** [comment]
@Aleksey28 Please let me know if you need further information

**Comment by Artem-Babich** [comment]
Hi, 

I've reproduced the issue with the latest TestCafe version. However, I also tried to run this test with [proxyless mode](https://testcafe.io/documentation/404237/guides/experimental-capabilities/proxyless-mode) enabled and it passed without errors. Could you try enabling proxyless mode on your side and check if the test passes correctly?

**Comment by pragmatictesters** [comment]
The issue was resolved with proxyless mode . Thanks @Artem-Babich
