### ISSUE TITLE
TestCafe tries to click to incorrect place in iframe

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe#7557]
### What is your Scenario?

Click an element in the iframe

### What is the Current behavior?

TestCafe clicks on the incorrect place

### What is the Expected behavior?

It should click on the specified element

### What is your public website URL? (or attach your complete example)

https://js.devexpress.com/Demos/WidgetsGallery/Demo/ActionSheet/Basics/jQuery/Light/

### What is your TestCafe test code?

```
fixture`Proxyless`.page`https://js.devexpress.com/Demos/WidgetsGallery/Demo/ActionSheet/Basics/jQuery/Light/`;

test('Test', async t => {
    await t
        .wait(1000)
        .switchToIframe('#demoFrame');
        await t.eval(() => {
            document.body.addEventListener('click', ev => console.dir(ev), true);
            document.body.addEventListener('mouseup', ev => console.dir(ev), true);
        });
        await t
            .click('#button')
            // .expect(Selector('.dx-toolbar-center').withText('Choose action').visible).ok()
            .debug();
});
```

### Steps to Reproduce

Just run the test.

### TestCafe version

2.4.0

### Node.js version

18.12.1

### Command-line arguments

npx testcafe chrome test.js --experimental-proxyless

**Comment by AlexKamaev** [comment]
The issue consists of two problems:
- incorrect calculation of position for mouse events in frames, because of scrolling in the parent containers.
- incorrect calculation of scrolling when fixed header overlaps target element
