### ISSUE TITLE
Print individual test execution time

### ISSUE THREAD

**Issue by ChrisLane** [DevExpress/testcafe#7572]
### What is your Scenario?

I am reviewing CI logs of long TestCafe test suite execution times and would like to know which tests are taking the longest to run so that I can identify any potential issues.

### What are you suggesting?

I would like to be able to set an option for TestCafe that will cause TestCafe to print timing information for fixtures and individual tests.
I would also consider this a sensible default, as such the option should instead be to disable timing information.

### What alternatives have you considered?

I could watch each test running or time tests individually but that would be very slow.

**Comment by Aleksey28** [comment]
Hi @ChrisLane,

If your mean showing the execution time in our default `spec` reporter, we know about this case and have this task in our roadmap. Now we are working on [sending custom information to a reporter](https://github.com/DevExpress/testcafe/pull/7562).

For now, you can [create your own custom reporter](https://testcafe.io/documentation/402810/guides/extend-testcafe/reporter-plugin) or use other reporters like [xunit ](https://github.com/DevExpress/testcafe-reporter-xunit)or [json](https://github.com/DevExpress/testcafe-reporter-json) that show this information.

**Comment by ChrisLane** [comment]
@Aleksey28 I mean in the command-line results.
![image](https://user-images.githubusercontent.com/925091/226904767-fa6da764-f858-47b1-9e91-f27de62ec0fd.png)

For example, it could look like this
**Load OneView page tests** [took: 5s]
:heavy_check_mark: load oneview [took: 5s]

**OneView page element tests** [took: 1m 10s]
:heavy_check_mark: timeframe picker [took: 5s]
:heavy_check_mark: refresh icon [took: 1m 5s]

**Comment by Artem-Babich** [comment]
Hi,

Thank you for the detailed description. We understand your task. Currently, we are working on reporter experience improvement:
#7562 
#7584 

So, you will be able to accomplish your task without creating a custom reporter once #7584 is released.

**Comment by Artem-Babich** [comment]
Hi @ChrisLane,

We released a new TestCafe version that includes the [onBeforeWrite](https://testcafe.io/documentation/404388/guides/advanced-guides/modify-reporter-output) hook. You can use it to accomplish your task:

```js
module.exports = {
    hooks: {
        reporter: {
            onBeforeWrite: {
                spec:  (writeInfo) => {
                    if (writeInfo.initiator !== 'reportTestDone')
                        return;

                    const { name, testRunInfo } = writeInfo.data;
                    const success = !testRunInfo.errs.length;
                    const duration = testRunInfo.durationMs;

                    if (success)
                        writeInfo.formattedText = \\\` \x1B[32m✓\x1B[39m \x1B[90m${name}\x1B[39m (took ${duration}ms)\\\`
                }
            }
        }
    }
}
```
