### ISSUE TITLE
TestCaffe devtools_recorder exporter

### ISSUE THREAD

**Issue by hkashlan** [DevExpress/testcafe#7573]
### What is your Scenario?

- do chrome devtools record (like https://developer.chrome.com/docs/devtools/recorder/)
- export it as testcafe code 

### What are you suggesting?

write a chrome exporter extension.
ability to customize:

-  the before test (some time we need to log in)

### What alternatives have you considered?

I was following https://testcafe.io/documentation/403998/guides/advanced-guides/chrome-replay-support

but what I am missing is the exporter

**Comment by Dmitry-Ostashev** [comment]
Hello @hkashlan,

Thank you for your suggestion. We do not plan to implement such an extension in the near future. Besides, check out the [TestCafe Studio](https://www.devexpress.com/products/testcafestudio/) tool. It allows recording tests in TestCafe script format (JS or TS).
