### ISSUE TITLE
Testcafe proxyless mode modifies authorization header

### ISSUE THREAD

**Issue by PatrickSys** [DevExpress/testcafe#7575]
### What is your Scenario?

I have an app which backend is secured so the frontend passes an auth header.

### What is the Current behavior?

Testcafe modifies the authorization header sent to the backend even in proxyless mode: 
![image](https://user-images.githubusercontent.com/74001504/226868494-febc35ce-d752-4c27-9615-e816aed5f56b.png)

### What is the Expected behavior?

The authorization header is not modified on proxyless mode

### What is your public website URL? (or attach your complete example)

Not relevant--

### What is your TestCafe test code?

Not relevant--

### Steps to Reproduce

1.Test an app that has authenticated requests
2. See that the header is modified even on proxyless mode
3.

### TestCafe version

2.4.0

### Command-line arguments

testcafe chrome apps/admin-e2e/src/index.dev.ts

**Comment by AlexKamaev** [comment]
We fixed the issue that I described in my example.
Please try running your tests in TestCafe v2.5.0-rc.1: [https://github.com/DevExpress/testcafe/releases/tag/v2.5.0-rc.1](https://github.com/DevExpress/testcafe/releases/tag/v2.5.0-rc.1).

Please share your results with us.

**Comment by AlexKamaev** [comment]
fixed in https://github.com/DevExpress/testcafe/releases/tag/v2.5.0-rc.1
