### ISSUE TITLE
POST multi-part/form-data with file for TestCafe t.request

### ISSUE THREAD

**Issue by codambro** [DevExpress/testcafe#7579]
### File a new question on StackOverflow

https://stackoverflow.com/questions/ask?tags=testcafe

**Comment by codambro** [comment]
pinging this again. Cannot get `t.request()` to work for uploading files. I'm hoping this is existing functionality that I just can't figure out.

**Comment by AlexKamaev** [comment]
Sending files using the `t.request` method is currently unsupported. We'll research this usage scenario.

**Comment by codambro** [comment]
can this be reopened as a requested improvement to testcafe?

**Comment by AlexKamaev** [comment]
We have already made our plans for the nearest future. We are not ready to work on this functionality at this time.
