### ISSUE TITLE
.dispatchEvent is not working for 'mousedown'

### ISSUE THREAD

**Issue by jbraden6075** [DevExpress/testcafe#7582]
### What is your Scenario?

I want to simulate a long click on a button by using .dispatchevent(target, 'mousedown')

### What is the Current behavior?

TestCafe doesn't seem to do anything when trying to use .dispatchEvent()

### What is the Expected behavior?

When I execute .dispatchEvent(), my scenario should have the button's text change.

### What is your public website URL? (or attach your complete example)

letcode.in/buttons

### What is your TestCafe test code?

test('User Can Long Hold On a Button', async t => {
    const target = Selector('button').withText('Button Hold!')

        await t
            .dispatchEvent(target, 'mousedown')
            .wait(5000)
            .dispatchEvent(target, 'mouseup')

    await t
        .expect(target.innerText).eql('Button has been long pressed')
})

### Your complete configuration file

module.exports = {
    browsers: "chrome",
    src: "./tests/**/*.js",
    reporter: {
        name: "spec",
        output: "./artifacts/reports/spec.txt"
    },
    screenshots: {
        path: "./artifacts/screenshots",
        pathPattern: "${DATE}_${TIME}/${TEST}.png",
        takeOnFails: true,
        thumbnails: false,
        fullPage: true,
    },
    skipJsErrors: true,
}

### Your complete test report

 Running tests in:
 - Chrome 111.0.0.0 / Windows 11

 letCodeIn - button
 × User Can Long Hold On a Button

   1) AssertionError: expected 'Button Hold!' to deeply equal 'Button has been long pressed'

      + expected - actual

      -Button Hold!
      +Button has been long pressed

      Browser: Chrome 111.0.0.0 / Windows 10
         89 |
         90 |test('User Can Long Hold On a Button', async t => {
         91 |    await buttonPageRepo.longClickButton()
         92 |
         93 |    await t
       > 94 |        .expect(buttonPageRepo.btnLongClick.innerText).eql('Button has been long pressed')
         95 |})
         96 |

         at <anonymous> (C:\Users\Jbrad\Documents\letCodeIn\tests\buttonPage\buttonPage.js:94:56)
         at asyncGeneratorStep (C:\Users\Jbrad\Documents\letCodeIn\tests\buttonPage\buttonPage.js:2:54)
         at _next (C:\Users\Jbrad\Documents\letCodeIn\tests\buttonPage\buttonPage.js:2:54)

 1/1 failed (10s)

### Steps to Reproduce

1. Navigate to letcode.in/buttons
2. Long click on 'Button Hold!' (3 seconds is plenty)
3. Assert text changed on button to 'Button has been long pressed'

### TestCafe version

2.4.0

### Node.js version

v18.15.0

### Command-line arguments

testcafe -t 'User Can Long Hold On a Button'

### Browser name(s) and version(s)

Chrome 111

### Platform(s) and version(s)

Windows 11

**Comment by Aleksey28** [comment]
Hi @jbraden6075,

It is a problem with the click handler for this button. It is executed only if you click exactly the `h2` element in this button. Try manually clicking the border of this button, and you will see that nothing will change.

Use this selector to trigger required events: `Selector('#isDisabled > div > h2')`
