### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by ajadhav** [DevExpress/testcafe#7589]
### What is your Scenario?

There seems to be a typo in the code example/text for scroll by.
[Scroll by documentation](https://testcafe.io/documentation/403066/reference/test-api/testcontroller/scrollby)

### What is the Current behavior?

The documentation states 'In the example below, TestCafe scrolls the webpage 200px up and 500px to the right:'
Whereas the code example shows 500 in the x, and -10 in the y direction:
```
 `fixtureTestController.scrollBy`
    .page`https://devexpress.github.io/testcafe/example/`;

test('Scroll the webpage', async t => {
    await t.scrollBy(500, -10);
});
```

### What is the Expected behavior?

The code example should match the text for the amount scrolled in the y direction.

### What is your public website URL? (or attach your complete example)

N/A

### What is your TestCafe test code?

N/A

### Steps to Reproduce

1. Visit [documentation link ](https://testcafe.io/documentation/403066/reference/test-api/testcontroller/scrollby#options)

### TestCafe version

6.14.17

### Command-line arguments

N/A

**Comment by AlexKamaev** [comment]
Thank you for bringing this typo to our attention. We'll fix it.
