### ISSUE TITLE
Email body field values are not saved after running the automation script.

### ISSUE THREAD

**Issue by chamikanishanchandrarathne** [DevExpress/testcafe#7590]
### What is your Scenario?

All Locators are correctly identified in the Notification template page but saved without the "Email Body" field values after running the automation script without any errors.

### What is the Current behavior?

After running the automation script, the email body values appear, but values are missing once the page is loaded manually.

### What is the Expected behavior?

Once the test script is completed, the email body value should appear within the body.

### What is your public website URL? (or attach your complete example)

https://example2.cammanagementsolutions.com.au/Auto_Risk_Incident_Example/CammsIncident/app

### What is your TestCafe test code?

```JS
import { Selector } from 'testcafe';

fixture`NewFixture`
    .page`https://example2.cammanagementsolutions.com.au/Auto_Risk_Incident_Example/CammsIncident/`;

test('New Test', async t => {
    await t.typeText('#OrganizationName', 'Auto_Risk_Incident_Example')
        .typeText('#UserName', 'sysadmin')
        .typeText('#Password', '5c@lab!lit47')
        .click('#OrganizationName', { caretPos: 0 })
        .click('#btnLogin')
        .click('#bs-example-navbar-collapse-1 [alt="Main Navigation"]')
        .click(Selector('a').withText('Incident Settings'))
        .click(Selector('#li_NotificationTemplates a').withText('Notification Templates'))
        .click(Selector('#result a').withText('New'))
        .typeText('#Name', 'Testppp11')
        .click(Selector('#LoadEmailTemplateConfigurationDetails span').withText('Please Select').nth(2))
        .click(Selector('#EmailType_listbox li').withText('Incident'))
        .typeText('#Description', 'Description ')
        .typeText('#Subject', 'Suject text')
        .click(Selector('#divBodyEditor .k-input').nth(1))
        .click(Selector("[id*='istbox'] li").withText('[IncidentCode]'))
        .wait(5000)
        .switchToIframe('#divBodyEditor .k-content')
        .typeText('.k-state-active', ' Test 123456790')
        .pressKey('enter')
        .switchToMainWindow()
        .click(Selector('#divBodyEditor .k-icon.k-i-arrow-60-down').nth(1))
        .click(Selector('[id*=\'istbox\'] li').withText('[IncidentTitle]')).pressKey('enter')

        .click(Selector('#divBodyEditor .k-icon.k-i-arrow-60-down').nth(1))
        .click(Selector('[id*=\'istbox\'] li').withText('[IncidentDescription]')).pressKey('enter')

        .click(Selector('#divBodyEditor .k-icon.k-i-arrow-60-down').nth(1))
        .click(Selector('[id*=\'istbox\'] li').withText('[IncidentReportedBy]')).pressKey('enter')

        .click(Selector('#divBodyEditor .k-icon.k-i-arrow-60-down').nth(1))
        .click(Selector('[id*=\'istbox\'] li').withText('[IncidentReportedDate]'))
        .pressKey('enter')

        .click(Selector('#divBodyEditor .k-icon.k-i-arrow-60-down').nth(1))
        .click(Selector('[id*=\'istbox\'] li').withText('[IncidentResponsibleperson]'))
        .click(Selector('#LoadEmailTemplateConfigurationDetails a').withText('Save'))
        .expect(Selector('#ModalSuccess_Message').textContent).contains('Template Configuration Details Saved Successfully')
        .debug()
});

```

### Your complete configuration file

module.exports=
{
    "browsers": [
        "chrome:headless"
    ],
    "concurrency": 1,
    "developmentMode": false,
    "screenshots": {
        "takeOnFails": true,
        "path":"artifacts/screenshots",
        "fullPage": true
    },
    "selectorTimeout": 30001,
    "skipJsErrors": true,
    "baseUrl": "https://example2.cammanagementsolutions.com.au/Auto_Risk_Incident_Example/CammsIncident/app",
    "userVariables": {
        "base_url" : "https://example2.cammanagementsolutions.com.au/Auto_Risk_Incident_Example/CammsIncident/app",
        "OrganizationName": "Auto_Risk_Incident_Example",
        "UserName": "sysadmin",
        "Password": "5c@lab!lit47",
        "serverId": "b2aaqhob",
        "serverDomain": "b2aaqhob.mailosaur.net",
        "mailosaurApiKey": "Z4cCAeGeCU96g5mB",
        "experimentalProxyless": "true"
        
    },
    "assertionTimeout": 20000
}

### Your complete test report

![image](https://user-images.githubusercontent.com/39464058/227731600-1aeb152e-3245-401a-b378-eb960cadd274.png)

### Screenshots

![2023-03-24_20h03_54](https://user-images.githubusercontent.com/39464058/227731639-c7b51f16-36f8-46df-968b-d9d49ec7130c.gif)

### Steps to Reproduce

1. First, Run the attached automation test script file
2. Then Login manually using the given credentials
3. Click on the Menu Dropdown in the top navigation
4. Click on the incident settings
5. Click on the Notifications settings
6. Click on the Filter icon on the Name column
7. Select the first dropdown value as “Contains” and type “Testppp11” in the second textbox 
8. Click on the “Testppp11” record item
9. Check the body filed values are not saved

### TestCafe version

2.4.0

### Node.js version

v18.12.1

### Command-line arguments

testcafe chrome testnotificationtemplete.ts

### Browser name(s) and version(s)

chrome 111.0.0.0

### Platform(s) and version(s)

Windows 11

### Other

 **Credentials**

Organization – Auto_Risk_Incident_Example
UserName – sysadmin
Password - 5c@lab!lit47

**Comment by chamikanishanchandrarathne** [comment]
Any updates for the above issue

**Comment by miherlosev** [comment]
Hi @chamikanishanchandrarathne,

The tested website has been changed. Please update the example, run it with the latest TestCafe version (`3.0.1`), and let us know your results.
