### ISSUE TITLE
Node 18.7.0: DNS Failure When Using BrowserStackLocal + Testcafe

### ISSUE THREAD

**Issue by berwyn** [DevExpress/testcafe#7598]
### What is your Scenario?

We use Testcafe with the Browserstack runner to run an E2E suite on our staging environment. Because the staging environment isn't exposed to the internet, we have a script in CI that wraps the E2E suite to start BrowserStackLocal before the tests run.

### What is the Current behavior?

When using a Node 18 container to launch BrowserStackLocal and start the suite, DNS lookup for our staging URLs fails, causing the suite to fail. Setting `NODE_OPTIONS=--dns-result-order=ipv4first` has no effect. Reverting to a Node 16 container fixes DNS resolution and allows the suite to pass. Other than the version tag, the two containers are otherwise identical and instrumented the same inside of Jenkins.

The suites universally fail with a non-descript DNS error:
```
     1) - Error in fixture.beforeEach hook -
        Failed to load the page at "https://[redacted]".
        Increase the value of the "pageRequestTimeout" variable, enable the "retryTestPages" option, or use quarantine mode to perform additional attempts to execute this test.
        You can find troubleshooting information for this issue at "https://go.devexpress.com/TestCafe_FAQ_ARequestHasFailed.aspx".
  
        Error details:
        Failed to find a DNS-record for the resource at "https://[redacted]".
```

### What is the Expected behavior?

The suite should be able to run and resolve DNS on Node 18 just as it does on Node 16.

### What is your public website URL? (or attach your complete example)

Our test sites are not available outside the corporate network. I'm currently seeing if I can create a minimal reproduction against a public website, but to provide context, our packages are
|package|version|
|:--------|:-------|
|`testcafe`|^2.4.0|
|`testcafe-browser-provider-browserstack`|^1.14.1|
|`testcafe-reporter-junit`|^3.0.2|
|`testcafe-reporter-slack`|^1.0.0|
|`testcafe-vue-selectors`|^3.1.1|

And the tests are instrumented with a script to the effect of
```sh
# set `BROWSERSTACK_*`
# set `TESTCAFE_*`


# Ensure local daemon is not running
BrowserStackLocal --daemon stop

# Start the local daemon
BrowserStackLocal --daemon start --key $BROWSERSTACK_ACCESS_KEY --local-identifier $BROWSERSTACK_LOCAL_IDENTIFIER

# Run the tests
npm run test:e2e:browserstack -- --config-file .testcaferc.browserstack.ci.js

# Stop the local daemon
BrowserStackLocal --daemon stop
```

### What is your TestCafe test code?

Because it's every test in the suite and occurs when the test attempt to navigate to the page, we instrument all our tests with the same basic block:

```js
	fixture `${testName}`
		.page(url)
		.meta({ url })
		.beforeEach(async (t) => { /* some setup code */ });
```

### Your complete configuration file

Lightly redacted, but our complete config resolves to

```js
module.exports = {
	src: './tests/e2e/fixtures',
	assertionTimeout: 50000,
	selectorTimeout: 50000,
	pageLoadTimeout: 50000,
	quarantineMode: {
		successThreshold: 3,
		attemptLimit: 5,
	},
	concurrency: 8,

	hostname: 'localhost',

	reporter: [
		{
			name: 'spec',
		},
		{
			name: 'junit',
			output: 'testcafe-results.xml',
		},
		{
			name: 'slack',
		},
	],

	browserInitTimeout: 120000,
	browsers: [
		'browserstack:chrome@108.0:Windows 10',
		'browserstack:Google Pixel 7@13.0',
	],
};
```

### Steps to Reproduce

1. Use a Node 18.7.0 environment (Docker may or may not be relevant here)
2. Install Testcafe packages
3. Start `BrowserStackLocal`
4. Start the test suite

### TestCafe version

2.4.0

### Node.js version

18.7.0

### Command-line arguments

testcafe --config-file .testcaferc.browserstack.ci.js

### Other

When I drop into a shell in the container, `dns.lookup()` for the failing addresses returns a valid IPv4 address and `curl` is able to establish a connection to the site, and the results are identical between Node 16 and Node 18. There is no code or configuration difference between the two containers other than Node versions.

**Comment by AlexKamaev** [comment]
> I'm currently seeing if I can create a minimal reproduction against a public website

Such an example will be very helpful as, unfortunately, we can't reproduce this issue in your usage scenario due to its complexity. So, please simplify the example as much as possible. If the docker is not relevant, you can exclude it. You may find the following article helpful: [How to create a Minimal Working Example when you submit an issue ](https://testcafe.io/documentation/402636/faq/general-info#how-to-create-a-minimal-working-example-when-you-submit-an-issue)
