### ISSUE TITLE
Proxyless does not work correctly when open second browser window

### ISSUE THREAD

**Issue by wombatka** [DevExpress/testcafe#7599]
### What is your Scenario?

In my test I open second browser window using experimental-proxyless 

### What is the Current behavior?

The url is incorrect in the second window

### What is the Expected behavior?

The url should be correct

### What is your public website URL? (or attach your complete example)

In the example beforeEach method opens an url- url is ok
in test i open another window with another url\
Url is incorrect
![image](https://user-images.githubusercontent.com/25752375/228429048-352c7969-2460-460d-ad8c-d6b7ed4122df.png)

### What is your TestCafe test code?

file: example.js

fixture`Open navigation`
    .beforeEach(async t => {
        await t.navigateTo("https://reactnavigation.org/docs/hello-react-navigation/");
       
    })

test("Expand navigation", async t => {
    await t.openWindow("https://reactnavigation.org");
});

### Your complete configuration file

no config file needed

### Your complete test report

![image](https://user-images.githubusercontent.com/25752375/228429183-675f43a7-c1a3-4b2f-bc67-a13dba7a0a06.png)

### Steps to Reproduce

1.open url
2.open window with other url
3.

### TestCafe version

2.4.0

### Node.js version

16.7.0

### Command-line arguments

 testcafe chrome --experimental-proxyless example.js -t "Expand navigation"

### Browser name(s) and version(s)

Chrome 111 Linux

### Platform(s) and version(s)

Linux Ubuntu 22

**Comment by AlexKamaev** [comment]
Thank you for sharing this. Currently, the proxyless mode is not supported in multiple window mode. Please use the '--disable-multiple-windows' flag.
