### ISSUE TITLE
Currently there are problems with opening the dropdown

### ISSUE THREAD

**Issue by Fernoel** [DevExpress/testcafe#7602]
### What is your Scenario?

after new angular 15 update testcafe not working properly with prime ng elements

https://user-images.githubusercontent.com/80269470/228852214-28c0ba17-9da6-4c54-a918-a1d27c06396c.mp4

### What are you suggesting?

previous versions of angular testcafe worked correctly, I think this process should be reviewed and to identify if testcafe has any problem with the https://primeng.org/ component with angular

**Comment by imma90** [comment]
I encountered the same issue and created a minimal working example with the demos in the PrimeNg documentation.

I ran the tests with testcafe 2.6.0 in Chrome 113.0.0.0 / Windows 11 with no special configuration. See [this repo](https://github.com/imma90/testcafe-primeng-dropdown). Testcafe does not work properly with the basic dropdown in primeng versions 14 and 15, but does work correctly in primeng version 13.

```ts
import { fixture, Selector } from 'testcafe';

fixture('primeng example');

test.page('https://www.primefaces.org/primeng-v15-lts/dropdown')('primeng v15 example', async (t) => {
  const basicDropdown: Selector = Selector('dropdown-basic-demo p-dropdown');
  const dropdownItems: Selector = basicDropdown.find('p-dropdownitem');

  await t.click(basicDropdown);

  await t.expect(dropdownItems.count).gt(0, 'No dropdown list items'); // fails
});

test.page('https://www.primefaces.org/primeng-v14-lts/dropdown')('primeng v14 example', async (t) => {
  const header: Selector = Selector('h5').withExactText('Basic');
  const basicDropdown: Selector = header.nextSibling('p-dropdown');
  const dropdownItems: Selector = basicDropdown.find('p-dropdownitem');

  await t.click(basicDropdown);

  await t.expect(dropdownItems.count).gt(0, 'No dropdown list items'); // fails
});

test.page('https://www.primefaces.org/primeng-v13-lts/#/dropdown')('primeng v13 example', async (t) => {
  const header: Selector = Selector('h5').withExactText('Basic');
  const basicDropdown: Selector = header.nextSibling('p-dropdown');
  const toggleExpandBtn: Selector = basicDropdown.find('div[role="button"]');
  const dropdownItems: Selector = basicDropdown.find('p-dropdownitem');

  await t.click(basicDropdown);

  await t.expect(toggleExpandBtn.getAttribute('aria-expanded')).eql('true'); // passes
  await t.expect(dropdownItems.count).gt(0, 'No dropdown list items'); // passes
});
```

**Comment by miherlosev** [comment]
Let's continue this discussions in this [thread](https://github.com/DevExpress/testcafe/issues/7713).
