### ISSUE TITLE
Make RequestMock precedent reversal configurable

### ISSUE THREAD

**Issue by lesterchoi-okta** [DevExpress/testcafe#7603]
### What is your Scenario?

The order of execution/precedent of request hooks seems counter-intuitive. IMHO most developers would expect the default execution order to go from most to least specific.

Scenario: I want `GET /api/foo` to return a `200 OK` most of the time, I want it to return `404 Not Found` in one fixture, and I want it to return `410 Gone` for one test in that fixture. With TestCafe's execution order, I cannot achieve this with a graceful "cascade".

NOTE: By "specific" I mean proximity to the assertions, not how they match the filter.

```js
// .testcaferc.js
module.exports = {
  hooks: {
    request: RequestMock()
      .onRequestTo({ url: /\/api\/foo/ })
      .respond('OK', 200),
  },
};

// Normal.spec.js
fixture('most cases')
test('should return 200 OK', (t) => {/* ... */});

// Errors.spec.js
fixture('handle errors').requestHooks(
  RequestMock()
    .onRequestTo({ url: /\/api\/foo/ })
    .respond('Not Found', 404)
);

test('should return 404 Not Found', (t) => {/* ... */});

test.requestHooks(
  RequestMock()
    .onRequestTo({ url: /\/api\/foo/ })
    .respond('Gone', 410)
)('should return 410 Gone', (t) => {/* ... */});

```

From https://testcafe.io/documentation/402842/guides/intermediate-guides/intercept-http-requests#request-hook-conflicts

> If a single request is subject to multiple request hooks, TestCafe executes the hooks in the following order:
> - Global hook
> - Fixture hook
> - Test hook

### What are you suggesting?

Provide a boolean configuration option that allows the developer to opt-in to this behavior by flipping the order of execution when multiple request hooks match.

Changing the **default** execution order would be a breaking change. Consider making it the default behavior in an upcoming major version?

```js
// .testcaferc.js
module.exports = {
  reverseHooksOrder: true, // or whatever you want to call it
}
```

### What alternatives have you considered?

1. Using a wrapper class to register request hooks in the desired order and applying them to each test.
2. Exporting [global] mocks from a module and controlling the order per test

```js
// .testcaferc.js
module.exports = {
  // no hooks registered
}

// global-mocks.js
module.exports = RequestMocks().onRequestTo(/\/api\/foo/).respond('OK', 200);

// Normal.spec.js
const globalMocks = require('./global-mocks');
fixture('normal').requestHooks(globalMocks);

test.requestHooks(globalMocks)('should return 200 OK', (t) => {/* ... */});

// Errors.spec.js
const globalMocks = require('./global-mocks');
const fixtureHooks = RequestMocks().onRequestTo(/\/api\/foo/).respond('Not Found', 404);

fixture('errors'); // no hooks registered

test.requestHooks(
  RequestMocks().onRequestTo(/\/api\/foo/).respond('Gone', 410),
  fixtureHooks,
  globalMocks,
)('should return 410 Gone', (t) => {/* ... */});

test.requestHooks(
  fixtureHooks,
  globalMocks,
)('should return 404 Not Found', (t) => {/* ... */});
```

**Comment by aleks-pro** [comment]
Hello @lesterchoi-okta ,

Thank you for your feedback. We will discuss your suggestion with the team.

**Comment by AlexKamaev** [comment]
We discussed the issue with the team and decided to close it. We agree that your point makes sense. However, currently, we have higher priority tasks to do. If you want, you can make a PR for the implementation of such functionality. We'll review it.
