### ISSUE TITLE
TestCafe Hangs Randomly With Video Recording Enabled

### ISSUE THREAD

**Issue by codambro** [DevExpress/testcafe#7604]
### What is your Scenario?

I am seeing TestCafe `t.()` actions hang randomly. Sometimes `t.navigateTo()`, sometimes `t.click()`. Without much rhyme or reason. I'm noticing it is only when video recording is enabled.

### What is the Current behavior?

`t` actions randomly hang.

### What is the Expected behavior?

Test continues or times out.

### What is your public website URL? (or attach your complete example)

DM for URL/creds. Unfortunately I can not reproduce it on other sites as readily.

### What is your TestCafe test code?

```
import { Role, Selector, t } from "testcafe";


// DM codambro for URL/email/password
const baseUrl = "URL";
const email = "EMAIL";
const password = "PASSWORD";

const demoUser = Role(
  baseUrl,
  async () => {
    // Login
    await t
      .typeText(Selector("#user_email"), email)
      .typeText(Selector("#user_password"), password)
      .click(Selector(`input[name="commit"]`));
  },
  {
    preserveUrl: true,
  },
);

fixture("TestCafe Hang Test")
  .page(baseUrl)
  .beforeEach(async t => {
    await t.useRole(demoUser);
  });

for (let i = 1; i <= 20; i++) {
  test(`Test A - Dismiss Tour - Attempt ${i}`, async t => {
    const endTourButton = Selector("div.popover-navigation").find("button").withText("End Tour");
    await t.navigateTo("/explore/");
    await t.click(endTourButton);
    // Often hangs after clicking button
    await t.typeText(Selector("#q"), `os:"Windows"`);
    await t.expect(true).ok();
  });
}
```

### Your complete configuration file

```
{
  "videoPath": "results/videos/",
  "hostname": "localhost",
  "disablePageCaching": true,
  "skipUncaughtErrors": true,
  "skipJsErrors": true
}
```

### Steps to Reproduce

1. Have video recording enabled
2. Have some test scenario where the webpage is interacted via TestController `t`
3. See test execution halts and hangs forever.
4. Sometimes refreshing browser will make test continue.

### TestCafe version

2.4.0

### Node.js version

18.12.1

### Command-line arguments

./node_modules/.bin/testcafe chrome --config-file ./config/testcaferc/all.json tests/testcafeHangTest.ts

### Platform(s) and version(s)

Mac and Ubuntu

**Comment by AlexKamaev** [comment]
Thank you for sharing your usage scenario.
>DM for URL/creds. Unfortunately I can not reproduce it on other sites as readily.

Please send it to our email: support@devexpress.com

**Comment by codambro** [comment]
Done!

**Comment by AlexKamaev** [comment]
Thank you. We've got the email.
I managed to reproduce the issue. However, it appears the Roles mechanism is not working for some reason.

So, I modified your code as follows:

```JS
fixture("TestCafe Hang Test")
    .page(baseUrl)
    .beforeEach(async t => {
        await t
            .typeText(Selector("#user_email"), email)
            .typeText(Selector("#user_password"), password)
            .click(Selector('input[name="commit"]'));
    });
```

Then, I was able to reproduce the issue as you described (only with video enabled). 

However, I was not able to research this further because the server started to send 429 responses.

Could you please not block our requests so we can research the issue in detail?

**Comment by codambro** [comment]
Unfortunately, 429 is temporary rate limiting. I cannot change the throttle settings on the server. I think the requests limit is 5/minute. On Apr 4, 2023, at 3:57 AM, AlexKamaev ***@***.***> wrote:﻿
Thank you. We've got the email.
I managed to reproduce the issue. However, it appears the Roles mechanism is not working for some reason.
So, I modified your code as follows:
fixture("TestCafe Hang Test")
    .page(baseUrl)
    .beforeEach(async t => {
        await t
            .typeText(Selector("#user_email"), email)
            .typeText(Selector("#user_password"), password)
            .click(Selector('input[name="commit"]'));
    });
Then, I was able to reproduce the issue as you described (only with video enabled).
However, I was not able to research this further because the server started to send 429 responses.
Could you please not block our requests so we can research the issue in detail?

**Comment by AlexKamaev** [comment]
It's very difficult to reproduce the issue when I get 429 responses. Could you please create a sample that reproduces the issue or modify the server settings to stop the request blocking of the test user?

**Comment by codambro** [comment]
You mentioned you were able to reproduce with the original sample provided. Are you still? This is the best I can do. I can't change the server settings. My best recommendation would be to reduce the rate of requests you are making. Normally when running the test above we do not hit 429s.

**Comment by AlexKamaev** [comment]
Yes, I was able to reproduce the issue. We can research your usage scenario now. However, I should warn you that it will not be very productive with the current project. That's why I asked you for another example.

**Comment by AlexKamaev** [comment]
We need another example that reproduces the described issue. The initial example was blocking requests and was very difficult to research. If anybody has an example that demonstrates the incorrect behavior, please create a separate issue and attach a sample.
