### ISSUE TITLE
Add in debug instructions to the bug report template

### ISSUE THREAD

**Issue by ayemelyanenko-chegg** [DevExpress/testcafe#7616]
### What is your Scenario?

I think it might be a good idea to add in instructions on how to provide a log for debugging to the bug report template. This might help the TestCafe team debug easier 

https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&template=bug_report.yaml

### What are you suggesting?

Add in instructions on how to add a log to the bug report template.

Something like the below:

```
Please provide a log by running your test(s) with

export DEBUG="testcafe:*,hammerhead:*" && [testcafe run command] 2>  testcafe.log
```

**Comment by miherlosev** [comment]
Hi @ayemelyanenko-chegg 

> I think it might be a good idea to add in instructions on how to provide a log for debugging to the bug report template.

The log collected in this way helps understand a small amount of issue. It's not necessary for the most users. This is why we don't add it into the bug template.
