### ISSUE TITLE
Docs: add README in the /docs with the TOC

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#762]
We need to create auto-generated README with TOC in `docs` dir which will make docs easily navigable on github. Also, I guess we should add remark to readme that content is better viewed on website

**Comment by VasilyStrelyaev** [comment]
'Auto-generated' - like completely automatic? A bot that regenerates it on each PR that affects the TOC at [docs/nav/nav-menu.yml](https://github.com/DevExpress/testcafe/blob/master/docs/nav/nav-menu.yml) (if it is possible at all)?

Or like semi-automatic - run a generating script locally and add the resulting `docs/README.md` to PR. Build bot can then warn you if your PR affects `docs/nav/nav-menu.yml` but not `docs/README.md`.

**Comment by inikulin** [comment]
> Or like semi-automatic - run a generating script locally and add the resulting docs/README.md to PR. Build bot can then warn you if your PR affects docs/nav/nav-menu.yml but not docs/README.md.

This

**Comment by VasilyStrelyaev** [comment]
@AlexanderMoskovkin, how difficult it is to upgrade the bot in such a way?

**Comment by AlexanderMoskovkin** [comment]
It's no problem
