### ISSUE TITLE
Provide better support for handling non-`Error` exceptions in `skipJsErrors`

### ISSUE THREAD

**Issue by lg-kialo** [DevExpress/testcafe#7627]
### What is your Scenario?

TestCafe seems to assume that any JS exceptions that are thrown are `Error`s. As such, the `skipJsErrors` callback receives an object with `message`, `stack` and `pageUrl` as the only fields. More specifically `SkipJsErrorsCallback` is typed as

```ts
type SkipJsErrorsCallback = (opts?: {message: string; stack: string; pageUrl: string }) => boolean;
```

In reality though, anything can be thrown, not only `Error`s. When a non-`Error` is thrown in the client (e.g. `throw 42;`), the `skipJsErrors` callback receives an object like the following:

```ts
{
    stack: 'undefined\n    No stack trace available',
    pageUrl: [the page URL]
}
```

Two problems with this:
1. The types are misleading as the `message` field is actually missing from the object received by the callback (I would consider this a bug)
2. There is not enough information about what was thrown to build an effective filter that only targets specific exceptions, as non-`Error` exceptions are indistinguishable from each other, they all look the same

We faced this issue in a real-world scenario due to non-`Error` exceptions being generated by an external library that we use (Wistia).

### What are you suggesting?

1. Fix the type of `SkipJsErrorsCallback` to reflect that the `message` field might be missing
2. Provide more information about the original exception to the `skipJsErrors` callback, e.g. provide the original exception object as `originalException` field

**Comment by miherlosev** [comment]
Hi @lg-kialo,

> TestCafe seems to assume that any JS exceptions that are thrown are Errors.

That's not quite true. TestCafe catches uncaught errors and uncaught promise rejections - [https://github.com/DevExpress/testcafe-hammerhead/blob/fdedd21b2d9ff7874c77ec95d6bf52763fb09f67/src/client/sandbox/node/window.ts#L172](https://github.com/DevExpress/testcafe-hammerhead/blob/fdedd21b2d9ff7874c77ec95d6bf52763fb09f67/src/client/sandbox/node/window.ts#L172).

Theoretically, the proposed enhancement makes sense, but we are not aware of a widely known library or component that raised an error not as an `Error` class. If you know such a component or library, please tell us about them.

If not, we will close this issue as this enhancement will not benefit a significant number of users.

**Comment by lg-kialo** [comment]
> Hi @lg-kialo,
> 
> > TestCafe seems to assume that any JS exceptions that are thrown are Errors.
> 
> That's not quite true. TestCafe catches uncaught errors and uncaught promise rejections - https://github.com/DevExpress/testcafe-hammerhead/blob/fdedd21b2d9ff7874c77ec95d6bf52763fb09f67/src/client/sandbox/node/window.ts#L172.
> 
> Theoretically, the proposed enhancement makes sense, but we are not aware of a widely known library or component that raised an error not as an `Error` class. If you know such a component or library, please tell us about them.
> 
> If not, we will close this issue as this enhancement will not benefit a significant number of users.

Hi @miherlosev,

I can only provide anecdotal evidence that we have been observing such errors "in the wild" and they caused our automation tests to fail. As I mentioned, we believe they are related to the [Wistia](https://wistia.com/) video player external code that we use. They're not open source so I can't really point out a piece of code that does that.

I understand that it's rather uncommon for non-`Error` exceptions to be raised, and probably not a best practice too, but still something that can happen.
If supporting this use-case is not a priority for you, I would urge you to at least adjust the typings to mark the `message` field of the object received by the `skipJsErrors` parameter as optional, since as I noted above it will be missing when a non-`Error` exception is thrown. It's also a very low effort change I assume.

**Comment by miherlosev** [comment]
> I would urge ask you to at least adjust the typings to mark the message field of the object received by the skipJsErrors parameter as optional, since as I noted above it will be missing when a non-Error exception is thrown. It's also a very low effort change I assume.

Could you please share a code sample that illustrates the described behavior?

**Comment by AlexKamaev** [comment]
I discussed this issue with the team, and we decided to close it since the described usage scenario seems to be quite rare and unpopular among TestCafe users. If you want to implement this enhancement, you can create a PR - we'll check it.
