### ISSUE TITLE
Click an URL, testcafe will loss connect of session

### ISSUE THREAD

**Issue by Icefox8888** [DevExpress/testcafe#7631]
### What is your Scenario?

1. In testcafe, t.click(sector); //the sector is a URL value.
2. click the URL, launch a new tab with the URL.
3. but my orginal session is lost connect. Then the automation is lost control.
4. I can't use t.openWindow(url). Because I need to test to click the cell to get the result.
5. I know this is testcafe issue. When you can fix it?
Thanks.

### What is the Current behavior?

chrome

### What is the Expected behavior?

I expect t.click(url) the behavior is the same as t.openWindow(url). Keep the original session control.

### What is your public website URL? (or attach your complete example)

none

### What is your TestCafe test code?

I can't do this. sorry.

### Steps to Reproduce

1. log in a session.
2. excel cell with url
3. t.click(cell.url)
4. launch the other tag, the original session is kept contol. 
5.

### TestCafe version

Version: 1.77.2 (user setup) Commit: e344f1f539a80912a0e9357cec841f36ce97a4e2 Date: 2023-04-06T10:08:05.978Z Electron: 19.1.11 Chromium: 102.0.5005.196 Node.js: 16.14.2 V8: 10.2.154.26-electron.0 OS: Windows_NT x64 10.0.19042 Sandboxed: No

### Node.js version

v16.13.0

### Command-line arguments

run at VS code version 1.77.2

### Browser name(s) and version(s)

Chrome Version 111.0.5563.65 (Official Build) (64-bit)

### Platform(s) and version(s)

Windows 10 Enterprise

### Other

none

**Comment by Dmitry-Ostashev** [comment]
Hello @Icefox8888,

Thank you for your code example. However, this example is not suitable. I cannot reproduce the issue with it (even if I remove the Role that does not work on the example.com website). Please share an application example or a public URL where we can see the described behavior on our side.
Also, I recommend you try using the latest (v2.5.0 at this moment) TestCafe version.
