### ISSUE TITLE
Opening new window/tabs from within an iframe breaks with --native-automtion due to wrong URL

### ISSUE THREAD

**Issue by roman-mibex-2** [DevExpress/testcafe#7638]
### What is your Scenario?

- We do OAuth logins to Bitbucket Cloud and other apps. This does that:
   1. Click a link, which opens a new tab/window doing the OAuth. This part runs in an iframe.
   2. The URL goes to a Bitbucket Cloud OAUth URL. 
   3. This URL redirects back to our app.

- In Test Cafe 2.4.0 this worked as expected.
- In Test Cafe 2.5.0 in 'classic' mode it works as expected
- In Test Cafe 2.5.0 'nativeAutomation' this breaks.

### What is the Current behavior?

1. Run in 'nativeAutomation'
2. When the Window/Tab. The URL looks like this. It goes to our apps URL, but on a random port.
    https://gamlor.info:35075/wDxRcT1im*44991/https://google.com/
    
    It does look like it kind of still tries to create a TestCafe 'classic' URLs, but then builds a complete wrong URL

### What is the Expected behavior?

1. This URL doesn't make sense. It should be the target URL
   - https://google.com instead of  https://gamlor.info:35075/wDxRcT1im*44991/https://google.com/

### What is your public website URL? (or attach your complete example)

Reproduction page is here: https://gamlor.info/files/testcafe.html 

Note:

### What is your TestCafe test code?

```
import {Selector} from "testcafe";
fixture('Reproduce Issue')
    .page('https://gamlor.info/files/testcafe.html');

test('Click link', async (t) => {
    const authorizationLink = Selector('a').withText(
        `Test Cafe Click Me`
    );
    await t
        .navigateTo('https://gamlor.info/files/testcafe.html')
        .switchToIframe(new Selector('iframe[id^="ch.mibex.confluence.cloud"]', { timeout: 30000 }))
        .click(authorizationLink)
});
```

### Your complete configuration file

```
{
  "browsers": ["chromium:headless"],
  "src": "e2e-tests",
  "reporter": "list",
  "screenshots": {
    "path": "e2e-tests/screenshots",
    "takeOnFails": true,
    "thumbnails": false,
    "pathPattern": "failures/test-${FIXTURE}/${BROWSER}/${FIXTURE}-${TEST_INDEX}.png"
  },
  "debugOnFail": false,
  "skipJsErrors": true,
  "skipUncaughtErrors": false,
  "concurrency": 1,
  "selectorTimeout": 5000,
  "assertionTimeout": 5000,
  "pageLoadTimeout": 5000,
  "quarantineMode": {
    "successThreshold": 1,
    "attemptLimit": 3
  },
  "speed": 1,
  "nativeAutomation": "true"
}
```

### Steps to Reproduce

1. Use the provided example script
2. Run `npx testcafe chromium reproduce/reproduce.js`. Note how it opens Google in the new window/tab. The test works.
3. Run `npx testcafe chromium reproduce/reproduce.js --native-automation`. 
4. *Is* When it opens new window/tab, the URL is broken and Google is not opened. A broken URL is opened, something like `https://gamlor.info:35075/wDxRcT1im*44991/https://google.com/`
    *Expected*: That google is opened and the test succeeds.

### TestCafe version

2.5.0

### Node.js version

2.5.0

### Command-line arguments

npx testcafe chromium

### Browser name(s) and version(s)

chromium 112.0.5615.121

### Platform(s) and version(s)

Linux

**Comment by AlexKamaev** [comment]
Currently, the `Native Automation` mode does not support `Multiple Browser windows`. If you need to use the `Native Automation` mode for some reason, you can split your test suite into two tasks - the first one with `Multiple Browser windows` enabled and without the `Native Automation` mode, and the second one with `Native Automation` and without `Multiple Browser windows`.
