### ISSUE TITLE
Incorrect browser alias is displayed while running Edge in headless mode

### ISSUE THREAD

**Issue by PierreRott** [DevExpress/testcafe#7647]
### What is your Scenario?

I want to run Edge in headless mode and see the correct browser alias in the console.

### What is the Current behavior?

I am running Edge browser in the headless mode but the console displays Chrome alias.
However console displays correct (Edge) alias while Edge is running in headed mode.

### What is the Expected behavior?

Correct browser alias should be displayed regardless of the mode (headless/headed).

### What is your public website URL? (or attach your complete example)

N/A

### What is your TestCafe test code?

Content of the test is not relevant.

### Your complete test report

$ testcafe edge:headless **.e2e-spec.ts                                                                               
 Running tests in:
 - Chrome 112.0.1722.48 / Windows 10

 TestCafé example
 √ Should click on button

### Screenshots

![headlessEdge](https://user-images.githubusercontent.com/34771265/233343916-5c8a3fbe-7c61-4f02-849a-faad3cafd69e.JPG)

### Steps to Reproduce

1. run Edge in headless mode
2. check that the browser alias in console is Chrome

### TestCafe version

2.0.0

### Node.js version

v16.17.1

### Command-line arguments

testcafe edge:headless **.e2e-spec.ts

### Browser name(s) and version(s)

Edge 112.0.1722.48, Chrome 112.0.5615.86

### Platform(s) and version(s)

Windows 10

**Comment by AlexKamaev** [comment]
Thank you for reaching out to us. I managed to reproduce the issue.
