### ISSUE TITLE
skipJsErrors inside `test` not working, but working outside of `test`

### ISSUE THREAD

**Issue by ManuelRauber** [DevExpress/testcafe#7648]
### What is your Scenario?

I'd like to skip javascript errors on a page that I know it will throw.

I'm using `skipJsErrors()` inside the test and expect the error not to interrupt the test execution.
If I use it outside the test via `test(() => {...}).skipJsErrors()` it works.

(Even better, I'd like to expect that error to be thrown, [but how](https://stackoverflow.com/questions/76070197/is-it-possible-in-testcafe-to-expect-errors-to-be-thrown)?

### What is the Current behavior?

Using `skipJsErrors` inside the test still interrupts the test run and throws.
Using it outside in `test().skipJsErrors()` it works.

### What is the Expected behavior?

I expect that `skipJsErrors()` works inside a test as well.

### What is your public website URL? (or attach your complete example)

-

### What is your TestCafe test code?

```ts
test('Test 1', async (t) => {
    const element = Selector('a');

    // even though skipJsErrors is set, it does not skip it but fails the test.
    // I've also tried skipJsErrors(true) or skipJsErrors(() => true), same result: test fails.
    await t
        .skipJsErrors()
        .click(element);
});

// Using it like this works
test('Test 2', async (t) => {
    const vacancy = Selector('a');

    await t.click(vacancy);
}).skipJsErrors();
```

### Your complete configuration file

```json
{
  "browsers": [
    "chrome"
  ],
  "baseUrl": "http://localhost:4200",
  "appCommand": "static dist/host --port 4200 --spa",
  "src": "e2e",
  "reporter": [
    {
      "name": "spec"
    }
  ]
}
```

### Your complete test report

```
[TestCafe]  ✖ Test 1
[TestCafe]
[TestCafe]    1) A JavaScript error occurred on "http://localhost:4200/example".
[TestCafe]       Repeat test actions in the browser and check the console for errors.
[TestCafe]       Enable the “skipJsErrors” option to ignore JavaScript errors during test execution. Learn more: "https://testcafe.io/documentation/404038/recipes/debugging/skip-javascript-errors"
[TestCafe]       If the website only throws this error when you test it with TestCafe, please create a new issue at:
[TestCafe]       "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".
[TestCafe]
[TestCafe]       JavaScript error details:
[TestCafe]       Error: ID not set.
[TestCafe]       << Removed Stack Trace >>
[TestCafe]
[TestCafe]       Browser: Chrome 112.0.0.0 / macOS 10.15.7
[TestCafe]
[TestCafe]          16 |
[TestCafe]          17 |    test('Test 1', async (t) => {
[TestCafe]          18 |        const element = Selector('a');
[TestCafe]          19 |
[TestCafe]        > 21 |        await t.skipJsErrors().click(element);
[TestCafe]          22 |    });
[TestCafe]          23 |});
[TestCafe]          24 |
[TestCafe]
[TestCafe]  1/2 failed (2s)
```

### Steps to Reproduce

1.
2.
3.

### TestCafe version

2.4.0

### Node.js version

18.16.0

### Command-line arguments

testcafe --live

**Comment by Artem-Babich** [comment]
Hi!

I reproduced the issue. However, I was able to resolve it by passing the "true" argument to the skipJsErrors action:
`await t.skipJsErrors(true)`

If this workaround doesn't work in your case, please share a sample project illustrating the issue so that we can research it on our side.
