### ISSUE TITLE
testcafe just stops/hangs with nativeAutomation true

### ISSUE THREAD

**Issue by stefanlivens** [DevExpress/testcafe#7652]
### What is your Scenario?

i'm testing a Vue3 application. Without nativeAutomation everything runs fine (the tests i mean)
If i turn on NativeAutomation, the tests just stops, or hangs or just doesn't do anything.

There are no errors, no warnings in the output of testcafe, nor in the console of the browser. It just 'stops'. it seems like the expect doesn't signal to the test that it is finished.

As you can see in below example, i get the console.logs a and b, but never c. the browser just sits there. Also no timeout errors. just ...nothing...

I cannot create a sample repo as it is internal app. but i would like to have hints or tips on what i can turn on to get more info or debug info? I tried debugMode, and it stops at the first expect, upon resuming it has the same behaviour: it just stops

### What is the Current behavior?

test run just hangs

### What is the Expected behavior?

run to the finish

### What is your public website URL? (or attach your complete example)

internal app.

### What is your TestCafe test code?

import RequestTravellerInfo from '../pageModels/RequestTravellerInfo';

fixture('Request traveller info page')
  .page(RequestTravellerInfo.pageURL)

test('The request-traveller-info page should show the correct title', async (testController) => {
  console.log('do i get here?','a');//yes
  await testController
    .expect(RequestTravellerInfo.title.innerText)
    .contains('Warp tickets');
  console.log('do i get here?','b');//yes
  await testController
    .expect(RequestTravellerInfo.title.innerText)
    .contains('Warp tickets');
});

test('The user should be able to fill in the inputfield firstname', async (testController) => {
  console.log('do i get here?','c');//NO!!
  await testController
    .typeText(RequestTravellerInfo.firstNameInput, 'Spock')
    .expect(RequestTravellerInfo.firstNameInput.value).eql('Spock');
});

### Your complete configuration file

{
    "browsers": [
        "chrome"
    ],
    "src": "./tests/functional/**/*.cspec.js",
    "hostname": "localhost",
    "reporter": [
        {
            "name": "spec"
        },
        {
            "name": "html",
            "output": "./tests/functional/reports/html/index.html"
        },
        {
            "name": "xunit",
            "output": "./tests/functional/reports/report.xml"
        }
    ],
    "screenshots": {
        "takeOnFails": true,
        "path": "./tests/screenshots",
        "fullPage": true,
        "pathPattern": "${FIXTURE}/${TEST}/test-${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.png"
    },
    "pageLoadTimeout": 10000,
    "clientScripts": [
        {
            "module": "axe-core/axe.min.js"
        }
    ],
    "debugMode": true,
    "nativeAutomation": true
}

### Your complete test report

no report, because the tests doesn't conclude.

### Steps to Reproduce

1.
2.
3.

### TestCafe version

2.5.0

### Node.js version

16.18.1

### Command-line arguments

testcafe './tests/functional/fixtures/RequestTravellerInfo.cspec.js'

### Browser name(s) and version(s)

chrome 112

### Platform(s) and version(s)

macOS 13.3.1

**Comment by jurgensweere** [comment]
Here is a sample repository to replicate the issue:

[https://github.com/jurgensweere/hello-world](https://github.com/jurgensweere/hello-world)

It is a vuejs application generated with the vue-cli, added testcafe, enabled nativeAutomation and added 5 tests. When running in Node v18.16.0 it will run 1 (or 2) tests successfully but never reaches any additional tests.

You can replicate by cloning the repository and then:
`npm install`
`npm run serve-test`

**Comment by AlexKamaev** [comment]
Thank you for your cooperation. I managed to reproduce the issue. We'll research it.

**Comment by mikkel-ol** [comment]
+1

**Comment by awacode21** [comment]
i am running in the same issue. what fixes it?

**Comment by PavelMor25** [comment]
Hello @awacode21,

Could you please create a separate ticket based on this [template](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&template=bug_report.yaml) and share more details? Specifically:

- [Minimal working example ](https://testcafe.io/documentation/402636/faq/general-info?search#how-to-create-a-minimal-working-example-when-you-submit-an-issue)
- Configuration
- Browser
- OS version
- Exact Node.js version
- Any additional information that might help us reproduce the issue
