### ISSUE TITLE
[Concurrency] Testcafe will perform a page refresh when I run a test with concurrency on only

### ISSUE THREAD

**Issue by Makavelic** [DevExpress/testcafe#7653]
### What is your Scenario?

I have a test file with a bunch of tests that run concurrently. If I run them without concurrency everything works fine. If I run them concurrently, at a predictable point for a couple of tests, the website page will perform a refresh (no where in my test do I tell it to open a page or do anything that would trigger a page reload). This causes the tests to fail because a page reload causes the page to revert its state (this is by design for the website i'm testing).

### What is the Current behavior?

Page reloads when I don't want it to.

### What is the Expected behavior?

The page should never reload unless I tell it to.

### What is your public website URL? (or attach your complete example)

This is particular to my company project which I cannot share but my project uses the page object model and it looks similar to this:

await panel.setvalue(someValue); 
await t.expect(await toolbar.canDoSomething()).notOk();

setValue looks like this:

await t.typeText(this.someSelector.find("textarea").filterVisible(), value, { paste: true, replace: false});
await t.wait(500); // Wait needed for debounce

After setValue is called, the website reloads for some unknown reason.

Can someone please tell me if there's something I can do to debug why the page is reloading. Or if there's some configuration I can add to force testcafe to NEVER do this that would be helpful as well.

Note: I tried turning on --native-automation but it fails there too. This also fails on firefox.

If I understand things correctly, each browser launched concurrently should be completely independent of each other so I don't know why 1 test can potentially cause another test to reload the page.

### What is your TestCafe test code?

I won't be able to provide a sample unfortunately but I'm just looking for guidance for what to debug.

### Steps to Reproduce

1. Unavailble
2.
3.

### TestCafe version

2.5.0

### Node.js version

18.13.0

### Command-line arguments

None

### Browser name(s) and version(s)

Chrome 111

### Platform(s) and version(s)

Windows 10

**Comment by Makavelic** [comment]
@AlexKamaev, it won't be possible to create a minimal working example for you guys. Instead, can you please give me tips on how I can debug the issue further OR tell me if there's a configuration I can set to prevent the browser from reloading. Once I have info on how to debug this problem I can possibly create a MWE.

**Comment by AlexKamaev** [comment]
Unfortunately, this information is not sufficient to make any presumptions. Based on your description, we do not have any clues on why such a reload can happen.
