### ISSUE TITLE
TestCafe v2.5.0 Native-automation

### ISSUE THREAD

**Issue by robogo83** [DevExpress/testcafe#7656]
### What is your Scenario?

I've updated TestCafe from 2.4.0 to 2.5.0 to try the new native-automation feature. I am using chrome as my browser and my test includes opening multiple windows.

### What is the Current behavior?

The initial window is loaded as expected but when the new window is supposed to be open the chrome browser blocks it with a message saying that pop-up windows are blocked. This behaviour persists even after allowing pop-up windows in Chrome browser. 
The test runs as expected without --native-automation flag
The question is, does it mean that running tests in multiple windows with native-automation is not allowed anymore?

### What is the Expected behavior?

New window is not being blocked by the browser when using --native-automation flag

### What is your public website URL? (or attach your complete example)

```
test('multiple windows', async (t) => {
 await t.openWindow('https://www.google.com/')
await t.openWindow('https://testcafe.io/documentation/402635/guides/overview/getting-started')
})
```

### What is your TestCafe test code?

I cannot provide the test code but I would like to know if this is a general issue. I believe if you reproduce a scenario with multiple windows you should get a similar outcome unless there's something in my local setting that is blocking the pop-up windows.

### Steps to Reproduce

1. Create a test with multiple windows opened using chrome as a browser and --native-automation flag

### TestCafe version

2.5.0

### Node.js version

v18.14.0

### Command-line arguments

chrome <path-to-the-test> --native-automation --reporter html:./reports/reports.html

### Browser name(s) and version(s)

Chrome 112.0.5615.121

### Platform(s) and version(s)

Windows 10

**Comment by Dmitry-Ostashev** [comment]
Hello @robogo83 ,

Currently, TestCafe does not allow opening multiple windows in native-automation mode. Please refer to the following issue to track our progress with this feature:: [https://github.com/DevExpress/testcafe/issues/7661](https://github.com/DevExpress/testcafe/issues/7661).
