### ISSUE TITLE
When using a custom testcafe server the browser uses chrome instead of edge when edge is set in the configuration file

### ISSUE THREAD

**Issue by jwhitmore-fleetresponse** [DevExpress/testcafe#7657]
### What is your Scenario?

We have a custom testcafe server that is used. We use the testcaferc.json file. When running locally sometimes it uses chrome instead of edge intermittently. When the tests are run in the azure pipeline using the vm image ubuntu-latest tests fail and show that chrome is being used for every failed test. 

### What is the Current behavior?

The chrome browser is being used when running tests even though it is configured to use edge

### What is the Expected behavior?

Use the edge browser that is configured in the testcaferc.json file

### What is your public website URL? (or attach your complete example)

A URL is not needed as the issue is that the incorrect browser is being used when tests are run intermittently on my local windows machine and when run in the azure pipeline using the ubuntu-latest vm image

The code used for my custom TestCafe Server is this:

### What is your TestCafe test code?

My TestCafe Server Code (testCafeRunner.ts)

(async () => {
    const createTestCafe        = require('testcafe');
    const argv                  = require('minimist')(process.argv.slice(2));
    const selfSignedSertificate = require('openssl-self-signed-certificate');

    const sslOptions = {
        key:  selfSignedSertificate.key,
        cert: selfSignedSertificate.cert,
    };

    const testCafeOptions = {
        hostname: 'localhost',
        port1:    1337,
        port2:    1338,
        sslOptions,
    };

    const testcafe = await createTestCafe(testCafeOptions);
    const tests = process.argv.slice(2)[0]
    const filter = argv.meta;

    if(filter == null || filter == 'undefined'){
        await testcafe.createRunner()
        .src(tests)
        .run();
    }
    else{
        await testcafe.createRunner()
        .src(tests)
        .filter((testName, fixtureName, fixturePath, testMeta, fixtureMeta) => testMeta.Severity === filter)
        .run();
    }

    await testcafe.close();
})();

### Your complete configuration file

My .testcaferc.json file
{
    "browsers": "edge:headless",
    "concurrency": 1,
    "reporter": [
        {
            "name": "spec"
        },
        {
            "name": "xunit",
            "output": "e2eReport.xml"
        }
    ],
    "selectorTimeout": 20000,
    "assertionTimeout": 20000,
    "pageLoadTimeout": 120000,
    "pageRequestTimeout": 120000,
    "speed": 0.8,
    "screenshots": {
        "takeOnFails": true,
        "pathPattern": "${BROWSER}/${FIXTURE}/${TEST}.png"
    }
}

### Your complete test report

One of the failed Tests Error:
 The specified selector does not match any element in the DOM tree.
&#160;&gt; | Selector(&#39;[data-qaid=&quot;btn-loss-notice-send&quot;]&#39;)
Browser: Chrome 112.0.1722.48 / Linux 0.0

### Steps to Reproduce

1.  Run Tests in azure pipeline using vm image ubuntu-latest and custom testcafe server
2.
3.

### TestCafe version

2.3.0

### Node.js version

18.16.0

### Command-line arguments

--meta=Critical

### Browser name(s) and version(s)

Edge

### Platform(s) and version(s)

Ubuntu 22.04

**Comment by Makavelic** [comment]
I think this is the same issue my team is seeing (with latest testcafe as well). Based on my testing edge is being reported as chrome even though the test is using edge. For example, I have a different version of chrome installed (that differs from the version of edge) and the report displays chrome<edgeVersion> instead of the version of chrome I have installed.  This only happens if you run headless. Without headless it reports edge as expected.
