### ISSUE TITLE
Support multiple windows in native automation mode

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe#7661]
### What is your Scenario?

At present, TestCafe does not support multiple windows in native automation mode.

### What are you suggesting?

Support multiple windows in native automation mode.

**Comment by tsherkqa** [comment]
Thank you for opening this ticket - our team is looking for support of multiple windows in native mode too. Clicking links that open new pop out windows is something we need to cover, so we can't turn this on for every test yet.

**Comment by patrickathompson** [comment]
same or similar issue: 

The application under test is programmed to open a new window or tab when a button is clicked. We need support for this type of interaction in TestCafe, because the application under test cannot always be modified to open in the same window.

**Comment by vlad-dargel** [comment]
The same problem. We have many tests with multiple windows, and native automation mode doesn't work with them.

**Comment by Jgrabenbauer** [comment]
Are there any workarounds with this @aleks-pro ? Or maybe at least to exclude certain tests from using native automation?

Thanks!

**Comment by Aleksey28** [comment]
Hi @Jgrabenbauer,

You can create two separate test runs - in Native Automation mode and without it. Specify test paths with the glob pattern as follows: [Test files](https://testcafe.io/documentation/402639/reference/command-line-interface#test-files). Use [the ](https://testcafe.io/documentation/402639/reference/command-line-interface#--disable-native-automation)[`--disable-native-automation`](https://testcafe.io/documentation/402639/reference/command-line-interface#--disable-native-automation) option for this purpose.

Run tests with NA:

```cli
testcafe chrome "tests/**/*" "!tests/multiple-tests/**/*"
```

Run tests without NA:

```cli
testcafe chrome "tests/multiple-tests/**/*" --disable-native-automation
```

You can do the same with [configuration files](https://testcafe.io/documentation/402638/reference/configuration-file) or with a [Runner](https://testcafe.io/documentation/402641/reference/testcafe-api/runner) object. Also, you can filter tests by [metadata](https://testcafe.io/documentation/402639/reference/command-line-interface#filter-tests-and-fixtures-by-name-grep-pattern-or-metadata).

**Comment by aleks-pro** [comment]
One more request https://stackoverflow.com/questions/76806603/how-to-use-disablenativeautomation-in-testcafe-for-one-test-only

**Comment by gforepsly** [comment]
We have the same issue - there is no workaround, 1 test i part of a larger group where we need to combine native and not native automation modes. 
Any ETA when this can be fixed/supported? It's a really nasty issue and a blocker for us.

**Comment by Aleksey28** [comment]
Hi @gforepsly,

We supported the [--disable-multiple-windows](https://testcafe.io/documentation/402639/reference/command-line-interface#--disable-multiple-windows) option in Native Automation mode, and it's already published in TestCafe 3.3.0-rc.1. Please test it.

**Comment by tandreys** [comment]
Is there an option to ignore popup window? I have an auto-closing popup, with proxy mode I just add a small t.wait, but in native mode Testcafe disable popup

**Comment by AlexKamaev** [comment]
Could you elaborate on what you mean by popup window? Do you mean a real browser window or just some kind of DOM element with a fixed/absolute position? Please share a simple reproducible sample to demonstrate what kind of popup you have.

**Comment by tandreys** [comment]
I mean a real window that process authentication on remote system. I don't have access to the real code but it's something like the js below where instead of opening a website yahoo, it's open a auth.html page
...
var myWindow = window.open('http://www.yahoo.com','1366002941508','width=600,height=400,left=5,top=3')
setTimeout(function() { myWindow.close();}, 3000);

**Comment by AlexKamaev** [comment]
@tandreys
In this case, the only workaround is to use the `--disable-native-automation` option to disable the Native Automation mode.

**Comment by Bayheck** [comment]
Testcafe released a new [version v3.5.0](https://testcafe.io/404732/release-notes/framework/2023-12-28-testcafe-v3-5-0-released#experimental-run-multi-window-tests-with-native-automation).
The experimental CLI flag ‘[--experimental-multiple-windows](https://testcafe.io/documentation/402639/reference/command-line-interface#--experimental-multiple-windows)’ allows multiple-window tests with native automation. Please try this solution and let us know if you encounter any issues.

**Comment by mx-bernhard** [comment]
I have a `RequestLogger` in my test that expects a certain request to have been logged for the newly opened window. Unfortunately, it seems that all requests from the new window are not recorded with the `RequestLogger`, just the ones from the initial window. Is this still unsupported in 3.5.0?

**Comment by Bayheck** [comment]
Hello, 

Multiple windows mode with native automation is still an experimental feature.
Thank you for your feedback. We will take it into account.

**Comment by Bayheck** [comment]
Hello @juan-garces @mx-bernhard , 
Please create a separate ticket based on this [template](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&template=bug_report.yaml) and also share a [minimal working example](https://testcafe.io/documentation/402636/faq/general-info?search#how-to-create-a-minimal-working-example-when-you-submit-an-issue) in that ticket so that the TestCafe team can research the issue and help you.
