### ISSUE TITLE
Support handling WebSocket handshake requests in RequestHooks

### ISSUE THREAD

**Issue by Klaster1** [DevExpress/testcafe#7662]
As per [request](https://github.com/DevExpress/testcafe/issues/7640#issuecomment-1522866234), I've extracted the WS handshake request hook regression into a new issue.

### What is your Scenario?

Using a RequestHook, I want to change the destination URL of WebSocket handshakes to point to a different web server. See details [here](https://github.com/DevExpress/testcafe/issues/7640#issuecomment-1517508786).

### What is the Current behavior?

Without native automation, the `RequestHook` detects WebSocket handshakes and modifies the request destination.
<details>
  <summary>Event example</summary>

```
RequestEvent {
  requestFilterRule: RequestFilterRule {
    options: { url: /\/browser/, method: undefined, isAjax: undefined },
    id: 'nMckIGK4K',
    isPredicate: false
  },
  _requestInfo: RequestInfo {
    requestId: 'LzK00xZ08',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36',
    url: 'ws://localhost:4200/browsers',
    method: 'get',
    isAjax: false,
    headers: {
      host: 'localhost:4200',
      connection: 'Upgrade',
      pragma: 'no-cache',
      'cache-control': 'no-cache',
      'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36',
      upgrade: 'websocket',
      origin: 'http://localhost:4200',
      'sec-websocket-version': '13',
      'accept-encoding': 'gzip, deflate',
      'accept-language': 'en-US,en;q=0.9',
      'sec-websocket-key': 'ZSNq+i5rOyRBFKgHDCmf3w==',
      'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits',
      'sec-websocket-protocol': 'v10.stomp, v11.stomp, v12.stomp',
      cookie: 'x-test-port=50634; connect.sid=s%3Agyl-BRVv_ShgGUYCnV1i7DfPa3ie-fDz.4ZMV1iZdj4sbNi1zY%2BFDuXrMQjpliXBmT9GPike1xLM'
    },
    body: <Buffer >,
    sessionId: '5xuFX6x0g'
  },
  reqOpts: RequestOptions {
    isAjax: false,
    rawHeaders: [
      'Host',
      '192.168.1.7:50478',
      'Connection',
      'Upgrade',
      'Pragma',
      'no-cache',
      'Cache-Control',
      'no-cache',
      'User-Agent',
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36',
      'Upgrade',
      'websocket',
      'Origin',
      'http://192.168.1.7:50478',
      'Sec-WebSocket-Version',
      '13',
      'Accept-Encoding',
      'gzip, deflate',
      'Accept-Language',
      'en-US,en;q=0.9',
      'Sec-WebSocket-Key',
      'ZSNq+i5rOyRBFKgHDCmf3w==',
      'Sec-WebSocket-Extensions',
      'permessage-deflate; client_max_window_bits',
      'Sec-WebSocket-Protocol',
      'v10.stomp, v11.stomp, v12.stomp'
    ],
    isWebSocket: true,
    requestId: 'LzK00xZ08',
    headers: {
      host: 'localhost:4200',
      connection: 'Upgrade',
      pragma: 'no-cache',
      'cache-control': 'no-cache',
      'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36',
      upgrade: 'websocket',
      origin: 'http://localhost:4200',
      'sec-websocket-version': '13',
      'accept-encoding': 'gzip, deflate',
      'accept-language': 'en-US,en;q=0.9',
      'sec-websocket-key': 'ZSNq+i5rOyRBFKgHDCmf3w==',
      'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits',
      'sec-websocket-protocol': 'v10.stomp, v11.stomp, v12.stomp',
      cookie: 'x-test-port=50634; connect.sid=s%3Agyl-BRVv_ShgGUYCnV1i7DfPa3ie-fDz.4ZMV1iZdj4sbNi1zY%2BFDuXrMQjpliXBmT9GPike1xLM'
    },
    externalProxySettings: undefined,
    url: 'http://localhost:4200/browsers',
    protocol: 'http:',
    hostname: 'localhost',
    host: 'localhost:4200',
    port: '4200',
    path: '/browsers',
    auth: undefined,
    method: 'GET',
    credentials: null,
    body: <Buffer >,
    requestTimeout: { page: undefined, ajax: undefined },
    disableHttp2: false
  },
  setMockFn: [Function: bound setMock] AsyncFunction,
  id: 'x9bnrL09z'
}
```

</details>

### What is the Expected behavior?

With native automation, the `RequestHook` does not detect any WebSocket handshake requests.

### What is your public website URL? (or attach your complete example)

See [here](https://github.com/DevExpress/testcafe/issues/7640#issuecomment-1517508786).

### What is your TestCafe test code?

```
// tester-integration.ts
export class GmcTesterHook extends RequestHook {
  constructor(private port: number) {
    super([/\/browser/, /\/api/]); // For example, ws://localhost:4200/browsers
    this.tester = new GmcTester(this.port)
  }
  private tester: GmcTester;
  static async init(): Promise<GmcTesterHook> {
    const port = await getPort({ port: getPort.makeRange(3001, 3200) });
    const hook = new GmcTesterHook(port);
    await hook.tester.ready;
    return hook;
  }
  async onRequest(e: any) {
    e.requestOptions.hostname = 'localhost';
    e.requestOptions.host = `localhost:${this.port}`;
    e.requestOptions.port = this.port.toString();
  }
  async onResponse() {}
  async destroy() {
    await this.tester.destroy();
  }
  use(fn: HookFn) {
    this.tester.use((t) => fn(t, this.store));
    return this;
  }
}

export interface GmcTestController<T extends any = {}> extends TestController {
  ctx: T & { hook: GmcTesterHook };
}

// test.ts
test.before(async (t: GmcTestController<{hook: GmcTester}>) => {
  t.ctx.hook = await GmcTesterHook.init();
  t.updateState((draft) => {
    draft.users.add(makeUser())
  })
})
```

### Steps to Reproduce

1. Add RequestHook that rewrites the WebSocket handshake request destination.
2. Check that it works without native automation.
3. Check that it doesn't with native automation.

### TestCafe version

2.5.1-rc.1

### Node.js version

18.15.0

### Command-line arguments

testcafe chrome fixture.ts --test="Test name" --live --native-automation

### Browser name(s) and version(s)

Chrome 112

### Platform(s) and version(s)

Windows 11 22H2

**Comment by miherlosev** [comment]
Hi @Klaster1,

All related issues are fixed. Please try running the tests with the custom TestCafe build. If the issue still occurs, share an example to reproduce it locally.
To install the custom TestCafe build, run this command:

```js
npm i https://github.com/miherlosev/tmp/files/11458249/testcafe-2.6.0.zip
```

**Comment by Klaster1** [comment]
@miherlosev the issue still happens with your custom build. Here's a reproducer: [testcafe-7662.zip](https://github.com/DevExpress/testcafe/files/11463372/testcafe-7662.zip).

**Comment by miherlosev** [comment]
Thank you for the shared example. I've reproduced the issue.

**Comment by Klaster1** [comment]
Any updates on this? The lack WS mocks in NA is a real bummer.

**Comment by Klaster1** [comment]
Apparently, even [CDP `Fetch` has trouble intercepting WebSocket requests](https://bugs.chromium.org/p/chromium/issues/detail?id=1283412).

**Comment by marinamarin91** [comment]
Hello, 
Any updates on this? 
I am trying using Role in my testcafe tests and I am getting this error:
![image](https://github.com/DevExpress/testcafe/assets/97027602/2f6c578b-e297-46f5-8783-f58d99fc98c7)

**Comment by AlexKamaev** [comment]
My attempts to research the issue were unsuccessful. It seems that WebSocket requests cannot be modified using the Fetch events. When I attempted to specify the resourceType as `resourceType: 'WebSocket'` for the `Fetch.enable` method, I received the following error message:

```
Unknown resource type in fetch filter: 'WebSocket'
```

I was unable to intercept WebSocket requests in the `requestPaused` event. Although events from the Network domain (such as [https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-webSocketFrameReceived](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-webSocketFrameReceived)) can handle WebSocket requests, it appears there is no way to mock these types of requests from Network events.

I will close the issue until the [Chrome bug](https://github.com/DevExpress/testcafe/issues/7662#issuecomment-1630295106) described above is fixed.
