### ISSUE TITLE
Unable to sign into a website while using native automation mode

### ISSUE THREAD

**Issue by ayemelyanenko-chegg** [DevExpress/testcafe#7664]
### What is your Scenario?

Would like to be able to sign into the website using native automation

### What is the Current behavior?

Unable to sign into the website when using native automation

### What is the Expected behavior?

User should be able to sign into the website when using native automation

### What is your public website URL? (or attach your complete example)

https://www.easybib.com/login

### What is your TestCafe test code?

```
import {t, Selector} from 'testcafe';
const loginUrl = `https://www.easybib.com/login`;
export const emailForSignIn = Selector('input[id*="email"]');
export const passForSignin = Selector('input[type="password"]');
export const signInButton = Selector('button').withText('Sign in');
export const upgradeButton = Selector('button[aria-controls="accountMenu"]');

// user log in/log out methods
async function userLogInWithCredentials(
  email: string,
  password: string
): Promise<void> {
  await t.navigateTo(loginUrl);
  await t
    .typeText(emailForSignIn, email, { paste: true })
    .typeText(passForSignin, password, { paste: true })
    .click(signInButton)
    .wait(6000);
  console.log(`Logged in as user: ${email}`);
}

fixture`User log in`
  .meta({ fixtureID: 'f-0001', author: 'GROWTH', app: '' })
  .beforeEach(async (t) => {});

test.meta({
  testID: 't-0001',
})(
  'Sign in',
  async (t) => {
    await userLogInWithCredentials('test_email_chegg@chegg.com', 'Password1');
    await t
          .expect(upgradeButton.visible)
          .ok();
 `});
```

### Screenshots

**When running with native automation, test fails when trying to log in**

<img width="480" alt="Screenshot 2023-04-26 at 11 28 03 AM" src="https://user-images.githubusercontent.com/14633459/234696369-8b045c1a-4870-4046-ba4f-3fbc6ffda790.png">

<img width="569" alt="Screenshot 2023-04-26 at 11 28 26 AM" src="https://user-images.githubusercontent.com/14633459/234696415-abefe34e-e0eb-4c75-a97b-fbddd9d43932.png">

**When running without native automation, test passes when trying to log in**

<img width="386" alt="Screenshot 2023-04-26 at 11 29 31 AM" src="https://user-images.githubusercontent.com/14633459/234696453-a9f701c2-56a9-4894-993a-b31edc4d479c.png">

### Steps to Reproduce

1. Clone https://github.com/ayemelyanenko-chegg/nextjs-nodejs-example
2. CD into nextjs-nodejs-example/
3. cd into my-app
4. npm install
5. Run with: npx testcafe chrome tests/sampleLoginTest.ts -e -L --native-automation **and test fails because the user never actually logs in and the element visible upon logging in is not visible**
5. Run with: npx testcafe chrome tests/sampleLoginTest.ts -e -L **and test passes because the user actually logs in and the element is visible**

### TestCafe version

2.5.1-rc.1

### Node.js version

18.16.0

### Command-line arguments

npx testcafe chrome tests/sampleLoginTest.ts -e -L --native-automation

### Browser name(s) and version(s)

Chrome 112.0.0.0

**Comment by AlexKamaev** [comment]
Thank you for the example. I managed to reproduce the issue. We'll research it.

**Comment by nmackey** [comment]
I believe I'm running into the same issue.  It doesn't look like it handles CORS requests, it never makes the preflight call.

**Comment by di5ko** [comment]
This is similar to my issue(s).

**Comment by miherlosev** [comment]
Hi @ayemelyanenko-chegg,

![](https://user-images.githubusercontent.com/4133518/236777878-15adbdd9-791e-491b-819f-fdd63cfcee91.png)

The error message is too general. To investigate the cause of the issue, we need more information. Could you please inspect the authentication logic of the [https://www.easybib.com/login](https://www.easybib.com/login) and describe why the authentication request fails?

**Comment by ayemelyanenko-chegg** [comment]
@miherlosev Hello, it seems like the values entered into the email/password fields appear to be empty as per the request preview. This only happens in native automation mode, running this test without the native automation mode works properly.

<img width="1134" alt="Screenshot 2023-05-09 at 11 32 54 AM" src="https://github.com/DevExpress/testcafe/assets/14633459/86762a4d-4379-4a95-9f18-67b7de9e6402">

Also, might these comments help out in the investigation?

https://github.com/DevExpress/testcafe/issues/7664#issuecomment-1528919420

https://github.com/DevExpress/testcafe/issues/7664#issuecomment-1529422747

**Comment by Aleksey28** [comment]
Hi @ayemelyanenko-chegg,

Thank you for the additional information. We'll research the issue and update this thread once we have news.

**Comment by ayemelyanenko-chegg** [comment]
Thanks for the fix @Aleksey28 @miherlosev. In order to be able to utilize it, we will need to wait for an updated TestCafe version?

**Comment by Aleksey28** [comment]
You can wait for the TestCafe release or manually set the latest [`testcafe-hammerhead`](https://www.npmjs.com/package/testcafe-hammerhead) version in [`overrides`](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides) of package.json.
