### ISSUE TITLE
Wobbling of dropdown options

### ISSUE THREAD

**Issue by MBQA73** [DevExpress/testcafe#7670]
### What is your Scenario?

Hi,
I have reported this issue a few months ago, but I can't find the old conversation about it. Sorry, I am new to this!
I know it wasn't resolved so I am trying to report it again to see if there is a solution.
I just started learning TestCafe to automate some of my regression test cases. Many of my test cases entail creating test users in my web application. Each time I create a new test user, I have to specify if I want the user to be an active user or an inactive user. In order to do that, I have to click on a 'Status' dropdown box which contains the two options (Active and Inactive). When I launch the script, I see the cursor hovering over the Status dropdown, clicking on it, then no matter if I select Active or Inactive the status (i.e. Active) wobbles for several seconds (apprx 5-6 seconds) during which TestCafe is "waiting for element to appear"...then if finally click on it. The test passes, I just can't figure out why it wobbles first. I tried several options...the .wait...the visibilityCheck...the .exists....just to name a few. I even asked chatGPT for other options. Nothing worked.
Has anyone encountered this issue before?
Thanks in advance.
-Marco 

### What is the Current behavior?

Wobbling of element for 5-6 seconds, which it is clearly visible, before it is finally clicked on.

### What is the Expected behavior?

Visible element shouldn't wobble for several seconds before being clicked on.

### What is your public website URL? (or attach your complete example)

Need to ask Security dept first. Sorry. Let me know if the issue can be looked at without this info first. Thank you.

### What is your TestCafe test code?

Where do I find this?

### Steps to Reproduce

1.
2.
3.
 
I have to ask my Security dept. if I am allowed to share login credentials. Even if it's only a test user with limited access to our QA/lower environment which will then be deleted, I still need to ask them. Let me know if this issue can be looked at without accessing our web application, before I ask them. Thank you!

### TestCafe version

2.3.1

### Node.js version

v18.14.0

### Command-line arguments

n/a

### Browser name(s) and version(s)

Chrome

### Platform(s) and version(s)

Windows 11

**Comment by di5ko** [comment]
I have encountered something similar. I was able to speed up my click action by doing something like below, maybe it will help you too:

`.click(Selector(".someClass").with({ timeout: 100 }))`

**Comment by MBQA73** [comment]
@di5ko - Erik, that fixed it! Thank you so very much. I had been trying for a few months now. You solved my issue. Much appreciated.
Cheers,
Marco

**Comment by MBQA73** [comment]
Erik (di5ko) was able to help me fix the wobbling issue. I am closing this ticket.

**Comment by di5ko** [comment]
Great to hear @MBQA73 - you're welcome :)
