### ISSUE TITLE
Issue when trying to screenshot scrolled state of component(s)

### ISSUE THREAD

**Issue by weihsma** [DevExpress/testcafe#7672]
### What is your Scenario?

I am having a mat-list component which has sticky elements on scroll, trying to screenshot this sticky behavior is not possible with testcafe currently. 

### What is the Current behavior?

The mat-list component has a sticky separator element on top, whenever one of the list items gets clicked its getting set to active and will be sticky below that first separator. While scrolling the list, the next separator in the list will get sticky as well, below that active element, to see here on the screenshot:

![Sticky state - wish](https://user-images.githubusercontent.com/42008461/235844071-fc30750e-b8b9-467b-9941-4f66118f93ff.PNG)

Setting up this testcase in testcafe works fine, until the method/function "**takeElementScreenshot(ele)**", here testcafe scrolls up and the sticky state is wrong:
![Sticky state - result](https://user-images.githubusercontent.com/42008461/235844456-88a4273d-a5cf-47c8-b2a7-8c3b35ee978f.PNG)

### What is the Expected behavior?

The expected screenshot result should be something like this, showing the three sticky elements:

![Sticky state - wish](https://user-images.githubusercontent.com/42008461/235844071-fc30750e-b8b9-467b-9941-4f66118f93ff.PNG)

### What is your public website URL? (or attach your complete example)

[testcafe-scroll-report.zip](https://github.com/DevExpress/testcafe/files/11379888/testcafe-scroll-report.zip)

### What is your TestCafe test code?

Please check "**testcafe-scroll-report.zip**"

```const Selector = require('testcafe');

fixture`object-list`
  .page`http://localhost:4200/`;

// object list with scroll state
test('1', async  t => {
  const scrollContainer = Selector.Selector('#scroll-list');
  const firstItem = Selector.Selector('#scroll-list .mat-mdc-list-item');

  const secondListSeparator = Selector.Selector('#scroll-list .via-list-name').withExactText('Another notes Item 3');

  await t
    .debug()
    .click(firstItem)
    .scrollIntoView(secondListSeparator) // fine until here, but screenshot is wrong
    .wait(300)
    .takeElementScreenshot(scrollContainer);
})
```

### Your complete configuration file

none

### Your complete test report

none

### Screenshots

already attached on top current/expected behavior

### Steps to Reproduce

1. unzup attached file "**testcafe-scroll-report.zip**"
2. run **npm i** 
3. ng serve --open // make sure its on port 4200 or change URL in list.js file
4. run testcafe from cmd: testcafe chrome .\tests\list.js  --hostname localhost

### TestCafe version

2.5.1-rc-1

### Node.js version

16.15.0

### Command-line arguments

--hostname localhost

### Browser name(s) and version(s)

Chrome Version 112.0.5615.138 

### Platform(s) and version(s)

Windows

**Comment by weihsma** [comment]
Hey there, quick update:
The issue only happens if your try to take the screenshot on the scrolled element itself, if you take the a wrapper-tag its working fine. So its possible to do the screenshots as wanted! You can decide if you still want to investigate here and apply a fix on my matter or close the ticket. Thank you ;)

**Comment by Aleksey28** [comment]
Hi @weihsma ,

I managed to reproduce the issue. It seems similar to the following: [https://github.com/DevExpress/testcafe/issues/7380](https://github.com/DevExpress/testcafe/issues/7380). Refer to that thread for further information. In the meantime, you can use your workaround or `takeScreenshot`.
