### ISSUE TITLE
remote javascript src tag causes 'Uncaught Object was thrown. ...Throw error instead.' when executing test commands

### ISSUE THREAD

**Issue by patrickathompson** [DevExpress/testcafe#7674]
### What is your Scenario?

I would like to load the provided javascript src tag on a webpage and ensure that the test actions do not throw an error.

### What is the Current behavior?

I am unable to perform test actions on the page with the custom javascript src tag provided. When converting to local js file, the issue does not occur. 

```
 Running tests in:
 - Chrome 112.0.0.0 / Ventura 13

 testcafe bug
 ✖ test error in testcafe

   1) Uncaught object
      "{"callsite":{"filename":"/Users/patrick.thompson/workspace/testcafe-test/test.ts","lineNum":8,"callsiteFrameIdx":5,"stackFrames":[{},{},{},{},{},{},{},{},{}],"isV8Frames":true}}"
      was thrown. Throw Error instead.

      Browser: Chrome 112.0.0.0 / Ventura 13



 1/1 failed (5s)
```

### What is the Expected behavior?

Testcafe should execute test commands without error when the provided javascript file is served both locally and remotely.

### What is your public website URL? (or attach your complete example)

n/a, src code attached below

### What is your TestCafe test code?

**index.html:**
```
<html>
<head>
        <title>
            SomeTitle
        </title>
</head>
<body>
    <iframe id='iframe1' src="frame1.html"></iframe>
</body>
</html>
```

**frame1.html:**
```
<html>
<head>
        <title>
            SomeTitle
        </title>
</head>
<body>
<div id="accelerateDropdown"><a href='http://www.google.com'>clickme</a></div>
<script src="https://cdn.crm.vinsolutions.com/customer/CDCStaticResources/CustomerDashboard1/script.js" type="text/javascript"></script>
<!-- script src="script.js" type="text/javascript"></script -->
</body>
</html>
```

**test.ts:**
```
fixture('testcafe bug');

test('test error in testcafe', async (t) => {
    await t.navigateTo('http://0.0.0.0:8080/index.html');
    await t.switchToIframe('#iframe1')
    await t.click('#accelerateDropdown');
});
```

### Steps to Reproduce

1. Serve the html file locally on port 8080
2. Run using proxy: `testcafe chrome test.ts -e -c 1`
3. Run using native-automation: `npx testcafe chrome test.ts -e -c 1 --native-automation`
4. Observe the test failing
5. Download script file content and place inside local script.js file
6. Uncomment and replace remote script src tag withe local copy
7. Comment or remove the switch to iframe command
8. Re-run steps 2 & 3
9. Observe test passing
10. Modify test to navigate directly to the iframe with remote js src file
11. Re-run steps 2&3
12. Observe test failing for proxy mode, but passing for native automation

### TestCafe version

2.5.1-rc.1 (ff843d6)

### Node.js version

v16.19.1

### Command-line arguments

chrome test.ts -e -c 1

### Browser name(s) and version(s)

Chrome 112.0.0.0

### Platform(s) and version(s)

macOS Ventura 13.3.1

### Other

Download the remote file in the source html and uncomment the local src tag in the index.html to observe the test working.

**Comment by AlexKamaev** [comment]
I did not manage to reproduce the issue. In my case, the test is passed in all scenarios: with/without native automation enabled and with external/local script. Perhaps I missed some required steps when I tried to reproduce the described behavior. Please create a separate github repository with an example and `serve` and `test` commands in package.json.

**Comment by patrickathompson** [comment]
I created a gist with all the files you requested and the instructions on how to run:

https://gist.github.com/patrickathompson/341ddd7c78c227a3ec047ab3c63a3deb

What OS and nodeJS version are you using in your local environment?

**Comment by AlexKamaev** [comment]
I managed to reproduce the issue using the NodeJS 16.20 version on Windows 10.
However, I was able to reproduce it in both usage scenarios: in the Native Automation mode and without it.
Could you please clarify if you can reproduce the issue only in the Native Automation mode or even without it?

**Comment by patrickathompson** [comment]
Yes, the issue is present in both modes for me as well

**Comment by miherlosev** [comment]
Hi @patrickathompson,

Could you please pack all necessary files into a public repository so that it will be possible to run tests with one command?

**Comment by patrickathompson** [comment]
Not one command, but you should be able to execute:

`git clone git@gist.github.com:341ddd7c78c227a3ec047ab3c63a3deb.git issue-7674`
`cd issue-7674 && npm install`
`npm test`

I also included a README.md in the gist with instructions on how to run. Good Luck!

**Comment by miherlosev** [comment]
I cannot get the files due to permission restrictions. Please fix this.

![image](https://github.com/DevExpress/testcafe/assets/4133518/7e11d3de-83da-4b36-82b8-e7e017ddfc97)

**Comment by patrickathompson** [comment]
The issue is on your end. The repo is public. Try adding your private ssh key.

**Comment by AlexKamaev** [comment]
I managed to reproduce the issue using the https repo.

**Comment by PavelMor25** [comment]
Hello @patrickathompson,

We researched the issue and determined the reason for this behavior. The issue was not caused by your code - it related to `lite-server`, which utilizes `browser-sync`. `Browser-sync` embeds itself into the page, similarly to what `TestCafe` does, resulting in incorrect behavior. When you run tests using `TestCafe`, run the lite server with a configuration that includes the `snippet: false` option.
