### ISSUE TITLE
Exception occurs only through TestCafe, executing manually or through other autmation tool looks good

### ISSUE THREAD

**Issue by aprabh001c** [DevExpress/testcafe#7686]
### What is your Scenario?

1. Launch https://www.xfinity.com/learn/offers
2. Search with a valid address
3. Select an offer 
Expected: - No exception should be given
Actual:- Something went wrong error shown, but manually or running through other automation tools it looks fine

Script:
```js
import {t, Selector} from 'testcafe'

fixture `UnHandledException`

test(`UnhandledExceptionTC`, async tn=>{
const _addressField = Selector('#Address_SingleStreetAddress,input[name="localizationAddressField"]');
const _search = Selector(".localization-container button[type='submit']");

await t.navigateTo("https://www.xfinity.com/learn/offers");
await t.wait(10000);
await t.typeText(_addressField,"1800 ARCH ST, APT C1230, PHILADELPHIA, PA 19103",{paste:true})
await t.debug()
await t.click(Selector('main span').withText('1800 ARCH ST, APT C1230, PHILADELPHIA, PA 19103'))
await t.click(Selector('[class="localization-container"] button[type="submit"]'))
await t.wait(2000)
await t.click(Selector('footer button').withText('View Deals'))
await t.click(Selector('[alt="add-icon"]'))
await t.click(Selector('[name="INTERNET"]~label'))
})
```

Note: - Tried to record video using --video command but it ended up with blank white screen
Downloaded FFMEG and set as env variable as well, but it didnt help 
![image](https://user-images.githubusercontent.com/58048733/236922123-8d7dcc65-4772-44f6-a245-500d1328b853.png)
+
![image](https://user-images.githubusercontent.com/58048733/236922224-700a0a97-2aa1-448a-b025-77cd37e7329b.png)

### What is the Current behavior?

![image](https://user-images.githubusercontent.com/58048733/236921196-9fec8187-3833-4751-b3d2-6ee099939b61.png)

### What is the Expected behavior?

No exception should be given

### What is your public website URL? (or attach your complete example)

https://www.xfinity.com/learn/offers

### What is your TestCafe test code?

```js
import {t, Selector} from 'testcafe'

fixture `UnHandledException`

test(`UnhandledExceptionTC`, async tn=>{
const _addressField = Selector('#Address_SingleStreetAddress,input[name="localizationAddressField"]');
const _search = Selector(".localization-container button[type='submit']");

await t.navigateTo("https://www.xfinity.com/learn/offers");
await t.wait(10000);
await t.typeText(_addressField,"1800 ARCH ST, APT C1230, PHILADELPHIA, PA 19103",{paste:true})
await t.debug()
await t.click(Selector('main span').withText('1800 ARCH ST, APT C1230, PHILADELPHIA, PA 19103'))
await t.click(Selector('[class="localization-container"] button[type="submit"]'))
await t.wait(2000)
await t.click(Selector('footer button').withText('View Deals'))
await t.click(Selector('[alt="add-icon"]'))
await t.click(Selector('[name="INTERNET"]~label'))
})
```

### Your complete configuration file

npx testcafe chrome testing.js -e --native-automation

### Screenshots

![image](https://user-images.githubusercontent.com/58048733/236921498-2dc2d095-a752-4d8d-aa7b-bdf0fbca469b.png)

### Steps to Reproduce

1. Launch https://www.xfinity.com/learn/offers
2. Search with a valid address
3. Select an offer 

### TestCafe version

2.5.1-rc.1

### Node.js version

18.16.0

### Command-line arguments

npx testcafe chrome testing.js -e --native-automation

### Browser name(s) and version(s)

Chrome 113.0.5672.64

### Platform(s) and version(s)

windows 2016 server

**Comment by aleks-pro** [comment]
Hello @aprabh001c ,

Thank you for sharing the test code.
I did not manage to reproduce the issue. Please check the attached screencast:

https://github.com/DevExpress/testcafe/assets/14822473/1b009477-f5c7-490a-883f-e828b5262d46

I tried to reproduce it in the attached project sample. You can run it by using the following commands:
```
npm ci
npx testcafe chrome ./tests/test.js -e --native-automation
```
[i7686.zip](https://github.com/DevExpress/testcafe/files/11464823/i7686.zip)

Please modify the project sample so that we can reproduce the problematic behavior on our side.

**Comment by aprabh001c** [comment]
Hi even in attached video provided as part of your reply,  you can see the error message after selecting the block. Below error message doesnt occur if you do same steps manually.
![image](https://github.com/DevExpress/testcafe/assets/58048733/fcc0a0ab-1771-4663-ac0c-e91c95d969c9)

**Comment by aleks-pro** [comment]
Hi @aprabh001c ,

I see the problematic behavior now. Thank you for reporting the issue. We will look into it and update this thread once we have any results. In the meantime, as a workaround, you can disable the Native Automation mode.

**Comment by aprabh001c** [comment]
Thanks for looking into it, with Native Automation Off, we always hit below error at end of script (issue raised for same https://github.com/DevExpress/testcafe/issues/6861 )

 × UnhandledExceptionTC

   1) Uncaught exception:

      Error: Session closed with error code 11
      at new NodeError (node:internal/errors:399:5)
      at Http2Session.onGoawayData (node:internal/http2/core:687:21)
      at Http2Session.callbackTrampoline (node:internal/async_hooks:130:17)

**Comment by aprabh001c** [comment]
Thank you for fixing this. Please let me know which version I can expect
this fix.

**Comment by Aleksey28** [comment]
Hi @aprabh001c,

We will introduce this fix in the upcoming version.
