### ISSUE TITLE
The switchToIframe method does not have its own setTimeout method

### ISSUE THREAD

**Issue by RomainGratier** [DevExpress/testcafe#7687]
### What is your Scenario?

I want to use the switchToIframe function safely in any CI.

### What are you suggesting?

A possible solution would be to add js logic to check every x milliseconds if the iframe is loaded. It would also require a maximum timeout that can be overwritten when calling the switchToIframe function to avoid having an infinite loop if the iframe is never loaded.

### What alternatives have you considered?

Adding some sleep functions but it is pretty dummy and inefficient.

### Additional context

I am thinking of a function that looks like this:

```js
await t.switchToIframe(Selector(SELECTOR_IFRAME), { setTimeout: IFRAME_TIMEOUT })
```

**Comment by Aleksey28** [comment]
Hi @RomainGratier,

TestCafe waits for iframe loading. However, if it isn't enough for you, you can use selector timeout.

```js
await t.switchToIframe(Selector(SELECTOR_IFRAME, { timeout: IFRAME_TIMEOUT })
```

See the following topic for more details: [https://testcafe.io/documentation/402681/reference/test-api/testcontroller/switchtoiframe#wait-until-an-iframe-is-loaded](https://testcafe.io/documentation/402681/reference/test-api/testcontroller/switchtoiframe#wait-until-an-iframe-is-loaded)
