### ISSUE TITLE
The .resizeWindow method stopped working entirely after the Chrome update

### ISSUE THREAD

**Issue by rhemfelt** [DevExpress/testcafe#7691]
### What is your Scenario?

I have a number of tests with the t.resizeWindow() method that have been working and passing for months/years. Some of my tests require a resize for selectors to be visible so the test can pass.  

### What is the Current behavior?

All of my previously working t.resizeWindow() methods are now non-functional. There's no resize of any kind happening. All of the other resize methods are also non-functional, like t. resizeWindowToFitDevice and t.maximizeWindow. 

### What is the Expected behavior?

The window changes to the size specified. 

### What is your public website URL? (or attach your complete example)

https://github.com/DevExpress/testcafe/

### What is your TestCafe test code?

//I just wrote a very simple demonstration against the DevExpress website. If you upgrade Chrome to 113 I think you'll see the same issue

import { Selector } from "testcafe";

fixture`test`.page`https://github.com/DevExpress/testcafe/`;

test("test", async (t) => {
  await t.resizeWindow(500, 200);
  await t.resizeWindow(600, 200);
  await t.resizeWindow(500, 300);
  await t.resizeWindow(500, 400);
  await t.resizeWindow(50, 50);
});

### Steps to Reproduce

1. Upgrade Chrome to 113, run the code above in debug mode (I named the file sandbox6.js)
2. Each step of the test should resize the window to the specified dimension

### TestCafe version

1.20.1

### Node.js version

v14.17.2

### Command-line arguments

testcafe chrome sandbox6.js -eu --debug-mode

### Browser name(s) and version(s)

Chrome Version 113.0.5672.92 (Official Build) (arm64)

### Platform(s) and version(s)

Mac Ventura 13.2.1 (22D68)

**Comment by Aleksey28** [comment]
Hi @rhemfelt,

An issue with same problem has been already created. Let's continue our discussion there: [https://github.com/DevExpress/testcafe/issues/7684](https://github.com/DevExpress/testcafe/issues/7684).

This issue will be closed.
