### ISSUE TITLE
t.maximizeWindow() does not work for Chrome

### ISSUE THREAD

**Issue by yourpchelp** [DevExpress/testcafe#7694]
### What is your Scenario?

Using testcafe, just open the page with https://www.google.com and try  to maximize the window.

### What is the Current behavior?

The browser's window is not maximized.
t.maximizeWindow() does nothing.

### What is the Expected behavior?

The browser's window must be maximized.

### What is your public website URL? (or attach your complete example)

https://www.google.com

### What is your TestCafe test code?

```
import { Selector, t } from 'testcafe';
fixture('maximize window')
.page('https://www.google.com')
test.only('check t.maximizeWindow method', async t => {
    await t.maximizeWindow();
    await t.wait(10000);
})
```

### Your complete test report

 Warnings (1):
 
  Was unable to maximize the window due to an error.

  The get-window-max-bounds process failed with the 1 exit code.
  Process output:
  Incorrect arguments

  Exit code: 1

### Steps to Reproduce

Run the above code.

### TestCafe version

2.6.0

### Node.js version

v18.16.0

### Command-line arguments

testcafe chrome ./maximizeWindow_test.js --skip-js-errors

### Browser name(s) and version(s)

Google Chrome, Version 113.0.5672.92 (Official Build) (x86_64)

### Platform(s) and version(s)

macOS Ventura 13.3.1

**Comment by hskolamala** [comment]
This issue started with chrome version 113

**Comment by Aleksey28** [comment]
Hi @yourpchelp ,

An issue with the same problem has already been created. Let's continue our discussion there: #7684.

This issue will be closed.
