### ISSUE TITLE
Testcafe crashes if driver status result is null

### ISSUE THREAD

**Issue by Kirdock** [DevExpress/testcafe#7707]
### What is your Scenario?

I don't know what exactly the trigger is because this behavior is flaky, but in some cases the [driver status](https://github.com/DevExpress/testcafe/blob/fba2da17670c9457a36789899a2bfb3cb1123f08/src/test-run/index.ts#LL1457C21-L1457C41) is `null`. This leads to resolving the [testRun.executeCommand](https://github.com/DevExpress/testcafe/blob/fba2da17670c9457a36789899a2bfb3cb1123f08/src/client-functions/client-function-builder.js#L159) with `null`. This again will be forwarded until [this.replicator.decode](https://github.com/DevExpress/testcafe/blob/fba2da17670c9457a36789899a2bfb3cb1123f08/src/client-functions/client-function-builder.js#L196) is called with null, which throws an execption because it expects an array.

Some command traces (I put some logs in the testcafe code):
```
action command switch-to-iframe
internal execute command switch-to-iframe
enqueue command switch-to-iframe
handle driver request null
driver status null
resolve driver task null
action command switch-to-main-window
internal execute command switch-to-main-window
enqueue command switch-to-main-window
handle driver request null
driver status null
resolve driver task null
action command navigate-to
internal execute command navigate-to
enqueue command navigate-to
handle driver request null
driver status null
resolve driver task null
action command switch-to-iframe
internal execute command switch-to-iframe
enqueue command switch-to-iframe
handle driver request null
driver status null
resolve driver task null
action command execute-client-function
internal execute command execute-client-function
enqueue command execute-client-function
handle driver request null
driver status null
resolve driver task null
```

### What is the Current behavior?

Testcafe crashes after navigating to a page
```
TypeError: Cannot read properties of null (reading '0')

273 ||DecodingTransformer.prototype.transform = function () {
274 |    this.visitedRefs[0] = true;
> 275 |    this._handleValue(this.references[0], this.references, 0);
276 |
277 |    return this.references[0];
278 |};

```

The command that propagates the `null` driver status result is `execute-client-function`.

### What is the Expected behavior?

It does not crash

### What is your public website URL? (or attach your complete example)

Not public

### What is your TestCafe test code?

It's a using a role (login SSO) after login, then navigating to a certain page and setting the context to an iframe => crash

```ts
import { Selector } from 'testcafe';
import { waitForReact } from 'testcafe-react-selectors';

fixture `Fixture`
  .page('http://example.com');

test('test', async t => {
  const userRole = Role(
    'http://example.com',
    async (t) => {
      // login
    },
    { preserveUrl: true },
  );
  await t.useRole(userRole);
  await t.resizeWindow(1200, 800);
  await t.switchToIframe(Selector('iframe'));



  await t.switchToMainWindow();
  await t.navigateTo('http://example.com/etc')
  await waitForReact(60_000);
  await t.switchToIframe(Selector('iframe'));

  // some actions (not executed because it crashes before)

});
```

### Your complete configuration file

```js
module.exports = {
  compilerOptions: {
    typescript: {
      configPath: "./e2e/tsconfig.json",
    }
  },
  browsers: ['chrome:headless'],
  reporter: [
    {
      name: 'xunit',
      output: `reports/report-e2e.${process.pid}.xml`,
    },
    {
      name: 'spec',
    },
  ],
  src: ['e2e/tests'],
  disableScreenshots: false,
  debugMode: false,
  skipJsErrors: true,
  skipUncaughtErrors: false,
  concurrency: 1,
  selectorTimeout: 20000,
  hostname: 'localhost',
  developmentMode: false,
  disablePageCaching: true,
  color: true,
  screenshots: {
    path: 'screenshots',
    takeOnFails: true,
    fullPage: true,
  },
  clientScripts: [
    {
      content: 'window.localStorage.setItem("something", "true")',
    }
  ],
  hooks: {
    test: {
      before: async (t) => {
        await t.resizeWindow(1200, 800);

        try {
          const browserConnection = t?.testRun?.browserConnection;
          const providerPlugin = browserConnection?.provider?.plugin;
          const browserClient = providerPlugin?._getBrowserProtocolClient(providerPlugin?.openedBrowsers[browserConnection.id]);
          if (browserClient?.getActiveClient) {
            const cdpClient = await browserClient.getActiveClient();
            await cdpClient?.Emulation?.setTimezoneOverride({timezoneId: 'Etc/UTC'});
          }
        } catch (error) {
          console.error('Failed to change the timezone', error);
        }
      }
    }
  }
};
```

### Steps to Reproduce

?. It's flaky

### TestCafe version

2.5.0

### Node.js version

18.15.0

### Command-line arguments

testcafe --debug-on-fail chrome

### Browser name(s) and version(s)

Chrome 113.0.0.0

### Platform(s) and version(s)

Windows 11

**Comment by Aleksey28** [comment]
Hi @Kirdock,

I didn't manage to reproduce the issue following your example. Please create a reproducible simple sample following this instruction: [https://testcafe.io/documentation/402636/faq/general-info#how-to-create-a-minimal-working-example-when-you-submit-an-issue](https://testcafe.io/documentation/402636/faq/general-info#how-to-create-a-minimal-working-example-when-you-submit-an-issue).

**Comment by Kirdock** [comment]
The behavior is flaky I don't have specific case where it happens always. I don't know what the trigger is for the driver status result being `null`. Anyway, I just saw there are a lot of issues regarding it. So mine is a duplicate
#7012, #6918, #5478, #4402

But the cause is that replicator consumes a parameter which is null and tries to access `null[0]` which results in the failure. There should be a workaround or typecheck before calling [decode here](https://github.com/DevExpress/testcafe/blob/fba2da17670c9457a36789899a2bfb3cb1123f08/src/client-functions/client-function-builder.js#L196) with `null`

**Comment by Aleksey28** [comment]
It appears there is an issue with the driver. However, we need an example to reproduce the issue. We can't research and fix this without an example. If you can share a reproducible sample, feel free to reopen the issue. As a workaround, you can try [`Native Automation Mode`](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode).

**Comment by Kirdock** [comment]
@Aleksey28 I managed to reproduce it.
I just took a random application I found on codesandbox.

```ts
import { ClientFunction, Selector } from 'testcafe';

fixture `Getting Started`

test('My first test', async t => {
  await t
    .navigateTo('https://codesandbox.io/s/react-new')
    .switchToIframe(Selector('#sandbox-preview'))

  // error thrown while inside here
  await ClientFunction(() => {
    return new Promise<boolean>((resolve, reject) => {setTimeout(resolve, 3_000)}); // or just don't resolve at all
  })();
  // error thrown while inside here
});

```

The error happens when switching to an iframe and a `ClientFunction` is executed next, that runs a bit longer

**Comment by Aleksey28** [comment]
I managed to reproduce your issue on the fifteenth time with this example. I run it on:
node: v16.19.0
testcafe: v2.6.0

We will update this thread once we have news. As a workaround, try to run it in [Native Automation Mode](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode).

For team:
The issue happens in `replicator`
