### ISSUE TITLE
Testcafe does not open primeng dropdown

### ISSUE THREAD

**Issue by imma90** [DevExpress/testcafe#7713]
### What is your Scenario?

Testcafe could not open primeng dropdowns for primeng 13 and primeng 15. This is the same issue as #7602 - I also encountered this after we upgraded to Angular 15.

### What is the Current behavior?

Dropdown does not expand when testcafe clicks on it with `t.click()`.

For primeng version 13, the dropdown still works (see my example code). For versions 14 and 15, not anymore.

### What is the Expected behavior?

Dropdown expands, dropdown items become visible.

### What is your public website URL? (or attach your complete example)

Primeng demo website:
- version 13: https://www.primefaces.org/primeng-v13-lts/#/dropdown
- version 14: https://www.primefaces.org/primeng-v14-lts/dropdown
- version 15: https://www.primefaces.org/primeng-v15-lts/dropdown

### What is your TestCafe test code?

See [this repository](https://github.com/imma90/testcafe-primeng-dropdown). The test code:

```ts
import { fixture, Selector } from 'testcafe';

fixture('primeng example');

test.page('https://www.primefaces.org/primeng-v15-lts/dropdown')('primeng v15 example', async (t) => {
  const basicDropdown: Selector = Selector('dropdown-basic-demo p-dropdown');
  const dropdownItems: Selector = basicDropdown.find('p-dropdownitem');

  await t.click(basicDropdown);

  await t.expect(dropdownItems.count).gt(0, 'No dropdown list items'); // fails
});

test.page('https://www.primefaces.org/primeng-v14-lts/dropdown')('primeng v14 example', async (t) => {
  const header: Selector = Selector('h5').withExactText('Basic');
  const basicDropdown: Selector = header.nextSibling('p-dropdown');
  const dropdownItems: Selector = basicDropdown.find('p-dropdownitem');

  await t.click(basicDropdown);

  await t.expect(dropdownItems.count).gt(0, 'No dropdown list items'); // fails
});

test.page('https://www.primefaces.org/primeng-v13-lts/#/dropdown')('primeng v13 example', async (t) => {
  const header: Selector = Selector('h5').withExactText('Basic');
  const basicDropdown: Selector = header.nextSibling('p-dropdown');
  const toggleExpandBtn: Selector = basicDropdown.find('div[role="button"]');
  const dropdownItems: Selector = basicDropdown.find('p-dropdownitem');

  await t.click(basicDropdown);

  await t.expect(toggleExpandBtn.getAttribute('aria-expanded')).eql('true'); // passes
  await t.expect(dropdownItems.count).gt(0, 'No dropdown list items'); // passes
});
```

### Your complete configuration file

```js
module.exports = {
    "src": "tests"
}
```

### Steps to Reproduce

Run test:
`npx testcafe chrome`

### TestCafe version

2.6.0

### Node.js version

v16.15.1

### Command-line arguments

npx testcafe chrome

### Browser name(s) and version(s)

Chrome 113.0.0.0

### Platform(s) and version(s)

Windows 11

### Other

Does not occur in native automation mode. Native automation mode has other issues, e.g. no firefox support and [issues with RequestMock and RequestLogger](https://github.com/DevExpress/testcafe/issues/7683).

**Comment by miherlosev** [comment]
Hi @imma90 

Thank you for the shared example. I've reproduced the issue.

**Comment by Klaster1** [comment]
This looks very similar to the issue I noticed a couple of months ago, after updating to Angular 14 and then to 15, although the project uses Angular Material, not primeng - the clicks handler sometimes do not trigger in tests, although the ripple activates (in the OP video, the select focuses). Happens in both NA and the regular modes. Might be an Angular bug or something in my app for all I know. As a workaround, I've been using this client function instead of `t.click`:

```
export const clickWithKeyboard = async (element: Selector, key: 'space' | 'enter' = 'enter') => {
  await t.expect(element.exists).ok();
  await t.eval(
    () => {
      // @ts-ignore
      return (element() as HTMLElement).focus();
    },
    { dependencies: { element } },
  );
  await t.pressKey(key);
};
```

https://github.com/DevExpress/testcafe/assets/2667662/ddc63136-7556-4933-ba78-e57c622967b8

**Comment by Aleksey28** [comment]
[https://github.com/DevExpress/testcafe/issues/7713](https://github.com/DevExpress/testcafe/issues/7713)

Hi @Klaster1,

Thank you for sharing the workaround. As for the fix, we will update this thread once we have any news.
