### ISSUE TITLE
TestCafe reports js error (Cannot read properties of undefined)

### ISSUE THREAD

**Issue by gemal** [DevExpress/testcafe#7724]
### What is your Scenario?

we are testing a simple login form and everything works just fine on all browsers
but on testcafe it fails every time

### What is the Current behavior?

type text into a login field

### What is the Expected behavior?

text accepted

### What is your public website URL? (or attach your complete example)

https://dinnerbooking.com/dk/en-US/users/business_login

### What is your TestCafe test code?

```
        .navigateTo('https://dinnerbooking.com/dk/en-US/users/business_login')
        .typeText('#login-email', 'no@example.com')
        .typeText('#login-pwd', '1234567')

```

### Your complete configuration file

var TestCafeModule = {
    browsers: "chrome:headless",
    cache: true,
    stopOnFirstFail:true,
};

### Your complete test report

```
JavaScript error details:
      TypeError: Cannot read properties of undefined (reading 'bind')
```

### Steps to Reproduce

1. run above testcafe case
2.
3.

### TestCafe version

2.6.0

### Node.js version

v18.16.0

### Command-line arguments

testcafe chrome

### Browser name(s) and version(s)

Chrome 113.0.0.0

### Platform(s) and version(s)

Windows 10

**Comment by ayemelyanenko-chegg** [comment]
Hi @gemal , I believe in this case, you should pass in skipJsErrors: true to your configuration file and the test should pass

```
var TestCafeModule = {
    stopOnFirstFail: true,
    browsers: "chrome:headless",
    skipJsErrors: true
}
```

**Comment by Aleksey28** [comment]
Hi @gemal,

I managed to reproduce the issue using your example, and it occurs only under TestCafe.

As a workaround, use the advice given by @ayemelyanenko-chegg - the test will be executed if you set [the `skipJsErrors` option](https://testcafe.io/documentation/404038/recipes/debugging/skip-javascript-errors) in the config file.

**Comment by miherlosev** [comment]
Hi @gemal,

This issue is not reproduced with combination of `testcafe@3.0.1` and the Google Chrome browser. Feel free to reopen this issue if you encounter it in other browsers.
