### ISSUE TITLE
Unable to use clientScripts in test as page hangs while attempting to log in

### ISSUE THREAD

**Issue by ayemelyanenko-chegg** [DevExpress/testcafe#7725]
### What is your Scenario?

Would like to log in and then inject .clientScripts into the test

### What is the Current behavior?

Test hangs on log in if .clientScripts is appended to the test or to the fixture

### What is the Expected behavior?

Test should log in and then inject the desired client script

### What is your public website URL? (or attach your complete example)

https://www.chegg.com

### What is your TestCafe test code?

```
import { t, Selector } from "testcafe";
const loginUrl = `https://www.chegg.com/auth?action=login`;
const emailForSignIn = Selector('input[id*="email"]');
const passForSignin = Selector('input[type="password"]');
const signInButton = Selector("button").withText("Sign in");
const closeButton = Selector('*[aria-label="Cancel"]');

// user log in/log out methods
async function userLogInWithCredentials(
  email: string,
  password: string
): Promise<void> {
  await t.navigateTo(loginUrl);
  await t
    .typeText(emailForSignIn, email, { paste: true })
    .typeText(passForSignin, password, { paste: true })
    .click(signInButton)
    .wait(6000);
  console.log(`Logged in as user: ${email}`);
}

const mockDate = `
    Date.prototype.getTime = function () {
        return 42;
    };
`;

fixture`Script test`
  .meta({
    fixtureID: "f-0001",
  })
  .beforeEach(async (t) => {
    await userLogInWithCredentials(
      "sample_script_user@chegg.com",
      "Password@123@123"
    );
  });

// this test hangs after a sign in attempt
test("My test 1", async (t) => {
  console.log(
    "user should be able to log in with the client script attached to test"
  );
  await t.expect(closeButton.visible).ok();
}).clientScripts({ content: mockDate });

// this test doesn't hang after a sign in attempt
test("My test 2", async (t) => {
  console.log(
    "user able to log in as the client script is not attached to test"
  );
  await t.expect(closeButton.visible).ok();
});

```

### Your complete configuration file

module.exports = {
    clientScripts: [{ module: "@testing-library/dom/dist/@testing-library/dom.umd.js" }],
    skipJsErrors: true
}

### Screenshots

**Test hangs if using clientScripts appended to the test or fixture**

<img width="1002" alt="Screenshot 2023-05-24 at 4 34 26 PM" src="https://github.com/DevExpress/testcafe/assets/14633459/317f177d-6e9b-4f1e-b034-eae1c2d3cffe">

**Test passes if not using clientScripts appended to the test or fixture**

<img width="1039" alt="Screenshot 2023-05-24 at 4 35 17 PM" src="https://github.com/DevExpress/testcafe/assets/14633459/f7549006-ec5b-4c5a-a6e1-3e2b03c7ffd6">

### Steps to Reproduce

Clone https://github.com/ayemelyanenko-chegg/nextjs-nodejs-example

CD into nextjs-nodejs-example/

cd into my-app

npm install

Run first test with: npx testcafe chrome tests/scriptTest.ts, **it hangs**

Run second test with: npx testcafe chrome tests/scriptTest.ts, **it passes**

### TestCafe version

2.5.1-rc.1

### Node.js version

18.16.0

### Command-line arguments

npx testcafe chrome tests/scriptTest.ts

**Comment by AlexKamaev** [comment]
Meanwhile, I managed to reproduce the issue using your test code and project with incorrect credentials. The test hangs even without a correct login/password pair. Thank you for sharing the example.

To the team: if I remove the `getDate` method overriding, the test works. This means that the problem is not only with client scripts, but also with their content.

**Comment by ayemelyanenko-chegg** [comment]
Hi @AlexKamaev, about the internal resources, I work for the company (Chegg) and any public person can create an account to access the website. There is no explicit owner of the website so I'm not sure if I can find someone who can provide a written approval? As I am an employee of the company, would my approval be enough? I don't think there is any private company information that is being shared because any person who can create an account will be able to see the same thing that you're seeing after signing up. Or do you mean that you have to take a look at our internal code as part of the fix?

As far as being able to reproduce with incorrect credentials. If there is a need, then I can just change the example test to provide incorrect credentials? Would that be an acceptable solution to help you investigate a fix?

**Comment by AlexKamaev** [comment]
>There is no explicit owner of the website so I'm not sure if I can find someone who can provide a written approval? As I am an employee of the company, would my approval be enough?

Yes, since it's difficult to find someone, your approval will be enough.

>Or do you mean that you have to take a look at our internal code as part of the fix?

We do not need to look at your internal code.

>As far as being able to reproduce with incorrect credentials. If there is a need, then I can just change the example test to provide incorrect credentials? Would that be an acceptable solution to help you investigate a fix?

Yes. Since the issue can be reproduced even without the correct login procedure, we can research the issue without the correct credentials.

**Comment by ayemelyanenko-chegg** [comment]
@AlexKamaev Thanks. I sent the email with the permission to support@devexpress.com

**Comment by miherlosev** [comment]
Hi @ayemelyanenko-chegg,

This issue is not related to TestCafe. If you change the code as follows:

```js
const mockDate = `
    Date.prototype.getTime = function () {
        debugger;
    };
`;
```

and open `DevTools` during test execution, you will see that the Google Chrome debugger stops on the `debugger` statement.

The hang occurred because of the wrong Date mocking. Please debug and fix it.

**Comment by ayemelyanenko-chegg** [comment]
Hi @miherlosev. Thanks for the reply.
I actually got the script example from TestCafe documentation. Maybe the example needs to be updated?
https://testcafe.io/documentation/402737/reference/test-api/test/clientscripts

![Screenshot_20230704-124358_Chrome](https://github.com/DevExpress/testcafe/assets/14633459/c2970a35-c823-4afb-b3a4-186685674f71)

**Comment by miherlosev** [comment]
> The hang occurred because of the wrong Date mocking.
This example is correct. However, it may work incorrectly on a tested website due to its internal logic.

```js
const mockDate = `
Date.prototype.getTime = function () {
return 42;
}
`;
```

The code above shows that you emulated the `1970, 00:00:42` date on the tested website (see: [Date.getTime](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime)). 

If someone comes across a similar issue, we will consider changing the example.
