### ISSUE TITLE
Matching configuration file option for "--color" CLI argument

### ISSUE THREAD

**Issue by ChrisLane** [DevExpress/testcafe#7730]
### What is your Scenario?

I want to configure all of my testcafe options via a .testcaferc.cjs file, including forcing coloured output.

### What are you suggesting?

I would like to be able to have the following in a configuration file to force coloured output:
```js
{
  color: true
}
```

### What alternatives have you considered?

I am currently using the existing `--color` argument to the command-line to force coloured output.

### Additional context

I need to force coloured output because TestCafe detects my CI environment as not having coloured output support.

**Comment by ChrisLane** [comment]
I wish I did but the documentation states that coloured output is the default which is already where problems start for me because this is not the case.

The `noColor` option is for disabling coloured output, setting it to false does not force coloured output.
Setting `noColor: false` does not give me coloured output.
`noColor: false` !== `color: true`

I imagine this is the reason both options are available for command-line (`--no-color` and `--color`) and as a result I would expect that there should be a matching option for the configuration file.

**Comment by miherlosev** [comment]
Hi @ChrisLane,

Thank you for pointing this out.
The coloring options are handled by the `chalk` module internally and it's only applied in the CLI interface.
As a workaround, you can use the environment variables to configure it in other interfaces.

```js
// analog of --no-color
process.env.FORCE_COLOR = '0';
const createTestCafe = require('testcafe');
....
```

```js
// analog of --color
process.env.FORCE_COLOR = '1';
const createTestCafe = require('testcafe');
....
```

For the team: see the `supports-color` module code.

**Comment by ChrisLane** [comment]
Thanks for the workaround but I think I'll stick with the CLI option until the configuration file option is available.
Can that workaround be applied in `.testcaferc.cjs`?

**Comment by miherlosev** [comment]
Yes, it can. Note that the environment variable should be set before the `createTestCafe` method call.

**Comment by ChrisLane** [comment]
> Yes, it can. Note that the environment variable should be set before the `createTestCafe` method call.

Considering we're not currently using `createTestCafe` anywhere in our code, this would unfortunately be a messier temporary solution than specifying  `--color` on the CLI.

**Comment by AlexKamaev** [comment]
We decided to close the issue since it is not really popular among TestCafe users, and we have tasks with higher priority at the moment. If you need this functionality, you can create a PR. We'll review it.
