### ISSUE TITLE
The "src" option from the configuration file will be ignored if user sends an unknown option to CLI

### ISSUE THREAD

**Issue by Gimmemosa** [DevExpress/testcafe#7740]
### What is your Scenario?

I am currently creating my own js configuration files according to testCafe Documentation

When I try to run those config files through CLI with a command from root folder 
TestCafe gives me a message in console "The "src" option from the configuration file will be ignored."

I am sure that the src path I am using is 100% correct since currently I'm using the same path to specify it in the CLI command and it works correctly, taking only the tests from the path I've provided + applying the configuration file filtering and set ups.

I tried to use default testcaferc.json file instead of creating a custom one but src is also ignored in this case.

Note that providing path in cli works as expected but it doesn't suite my needs since I'm trying to remove this cli dependency and move it to configuration files.

In the TestCafe documentation I didn't find anything about this error or why src is ignored.

StackOverflow:https://stackoverflow.com/questions/76231497/the-src-option-from-the-configuration-file-will-be-ignored

### What is the Current behavior?

Using a command like testcafe firefox ./Tests/Desktop/**/*.js --skip-js-errors --env staging --debug-on-fail --config-file customConfig.js
Which includes --env ( unknown option for testCafe ), Test cafe gives a message in console "The "src" option from the configuration file will be ignored."

### What is the Expected behavior?

SRC option not to be ignored if it is provided in the config file.

### What is your public website URL? (or attach your complete example)

Nope

### What is your TestCafe test code?

Doesn't matter

### Your complete configuration file

module.exports = {
    disableHttp2: true,
    reporter: 'spec-time',
    disableMultipleWindows: true,
    proxy: 'PROXY',
    clientScripts: 'SCRIPTSPATH',
    src: ['./Tests/Desktop/**/*.js'],
    filter: {
        testMeta: {
            type: 'regression',
            priority: 'high',
        },
    },
};

I also tried same configuration but with JSON format

{
    "disableHttp2": true,
    "reporter": "spec-time",
    "disableMultipleWindows": true,
    "proxy": "PROXY",
    "clientScripts": "SCRIPTSPATH",
    "src": "./Tests/Desktop/**/*.js",
    "filter": {
        "testMeta": {
            "type": "regression",
            "priority": "high"
        }
    }
}

### Steps to Reproduce

1.create a config file with src
2.provide an additional unknown option to cli command
3. run the command

### TestCafe version

2.4.0

### Command-line arguments

testcafe firefox --skip-js-errors --env staging --debug-on-fail --config-file customConfig.js

**Comment by Artem-Babich** [comment]
Hello, you observe expected behavior. TestCafe tries to resolve browsers and sources from CLI. Since you are passing an unknown parameter, TestCafe decides that this is your test source. That is why you are getting the warning message about an option override. Could you please clarify why you are passing an unknown option to a TestCafe command and what behavior you are trying to achieve?

**Comment by Artem-Babich** [comment]
Hi again, I just found out that passing node arguments will also result in the same behavior. This behavior is incorrect. We will investigate and fix it.

**Comment by PavelMor25** [comment]
We tried to reproduce this behavior with a simple example using the following command: "npx testcafe chrome --env".
It is expected that the "--env" flag overwrites the 'src' configuration option because "--env" is a valid name for a test folder.

>passing node arguments will also result in the same behavior

As for passing node arguments, Testcafe supports not all node flags, so some of them can be processed as valid folder names.
