### ISSUE TITLE
2.6.1 no longer works in Internet Explorer

### ISSUE THREAD

**Issue by dcsaszar** [DevExpress/testcafe#7741]
### What is your Scenario?

Running on IE11

### What is the Current behavior?

The test hangs after showing the example.org domain, the Testcafe bottom bar appears to be missing.

<img width="916" alt="image" src="https://github.com/DevExpress/testcafe/assets/986170/4bdd7763-9c09-43eb-ab85-622be42db46a">

```bash
~/js.scrivito.com·master⋮ SAUCE_USERNAME=*** SAUCE_ACCESS_KEY=*** npx -- testcafe 'saucelabs:internet explorer' test.js
 Running tests in:
 - Internet Explorer 11.0 / Windows 10 (https://app.saucelabs.com/tests/a1907d764e08408482d8daa023eecb82)

 Example
```
(no further output)

### What is the Expected behavior?

like in V 2.9.0:

<img width="852" alt="image" src="https://github.com/DevExpress/testcafe/assets/986170/d72c7798-e50b-40f0-83bb-375bcf945075">

```bash
SAUCE_USERNAME=*** SAUCE_ACCESS_KEY=*** npx -- testcafe 'saucelabs:internet explorer' test.js
 Running tests in:
 - Internet Explorer 11.0 / Windows 10 (https://app.saucelabs.com/tests/1ee7212c73ee4ad1bd61215b03795a81)

 Example
 ✓ Page content


 1 passed (6s)
```

### What is your public website URL? (or attach your complete example)

https://www.example.org

### What is your TestCafe test code?

test.js:

```js
import { Selector } from "testcafe";

fixture`Example`.page`https://www.example.org`;

test("Page content", async (t) => {
  await t.expect(Selector("h1").withText("Example Domain").exists).ok();
});
```

### Steps to Reproduce

1. Install testcafe and testcafe-browser-provider-saucelabs
2. Create "test.js"
3. Run the test on Saucelabs: `SAUCE_USERNAME=*** SAUCE_ACCESS_KEY=*** npx -- testcafe 'saucelabs:internet explorer' test.js`

### TestCafe version

2.6.1

### Node.js version

v19.8.1

### Command-line arguments

'saucelabs:internet explorer' test.js

### Browser name(s) and version(s)

IE 11

### Platform(s) and version(s)

Windows 10

### Other

```
"testcafe-browser-provider-saucelabs": "^2.0.0"
```

**Comment by AlexKamaev** [comment]
Thank you for reporting this issue. Our team is actively working on resolving it. We'll let you know as soon as a fix is implemented.

**Comment by AlexKamaev** [comment]
fixed in https://github.com/DevExpress/testcafe-hammerhead/pull/2900
