### ISSUE TITLE
Modifying headers with RequestHooks does not work with --native-automation

### ISSUE THREAD

**Issue by omacranger** [DevExpress/testcafe#7748]
### What is your Scenario?

I'd like to be able to modify the headers in a request prior to it being sent to the server, as seen in an example on the testcafe docs here: https://testcafe.io/documentation/402772/reference/test-api/requesthook/onrequest

### What is the Current behavior?

With `nativeAutomation: false` we are able to modify headers. With `nativeAutomation: true` the headers are not modified.

### What is the Expected behavior?

The headers should be modified.

### What is your public website URL? (or attach your complete example)

I forked the testcafe example repo and added a test for it here: https://github.com/omacranger/testcafe-examples/commit/7a1d840a73be9dd91370400259d3475c4776d241

### What is your TestCafe test code?

Full example in in the commit / repo above.

### Steps to Reproduce

Checkout the example repo I duplicated above, and do the following:

In one terminal
```
node ./server/index.js
```

In another
```
npx testcafe chrome ./examples/set-request-headers
npx testcafe chrome ./examples/set-request-headers --native-automation
```

Notice the first command passes, and the second command fails.

### TestCafe version

2.6.1

### Node.js version

v18.12.0

### Command-line arguments

--native-automation

### Other

I think this is related to #7732 as well.

**Comment by AlexKamaev** [comment]
I managed to reproduce the issue.

**Comment by AlexKamaev** [comment]
fixed in https://github.com/DevExpress/testcafe/pull/7754
