### ISSUE TITLE
JS / Unexpected token Errors when upgrading to 2.6.0

### ISSUE THREAD

**Issue by omacranger** [DevExpress/testcafe#7751]
### What is your Scenario?

Run tests on the latest versions of TestCafe.

### What is the Current behavior?

Errors appear randomly during test results

### What is the Expected behavior?

No errors appearing

### What is your public website URL? (or attach your complete example)

Due to the intermittent nature of the issue, we don't really have a sample to share, but with some help / knowledge of the recent TestCafe changes perhaps you can guide me to where I can help track it down and provide one.

The issue only appears on 2.6.0+ and happens consistently in CI on random jobs / tests. Reverting back to 2.5.0 resolves the issue completely with no other changes. **Can someone from the team speak about any changes that occurred from 2.5.0 -> 2.6.x perhaps related to the TestCafe proxy?** If so, I'd be happy to try and track down what's causing it and try to provide a reproducible example.

Native automation doesn't work for us due to #7748 so we can't see if the issue is resolved in the non-proxy mode.

### What is your TestCafe test code?

Even simple tests are failing in this setup, but here's a pseudo-code example of a basic test structure which is one of the ones that randomly failed.

```
fixture('Interaction Details Test')
  .beforeEach(() => ClientFunction(() => document.cookie = ""))
  .meta({ app: 'job-details', type: 'e2e', group: '1' })
  .page(PageModel.getCurrentPageUrl());

test('should navigate', async (testcafe) => {
  await testcafe.click(PageModel.buttonSelector);
});
```

### Your complete test report

```
1) packages/path-to-file/test/e2e/main-view.e2e.js
      (Page View) Main page
        ✓ should display main view (content) (19915ms)
        ✓ should display main view (buttons function) (19913ms)
        ✓ should display main (nested -> content) (19911ms)
        ✖ should display main (nested -> buttons function) (28945ms)
        1) - Error in fixture.beforeEach hook -
           A JavaScript error occurred on "http://localhost:8080/page-url".
           Repeat test actions in the browser and check the console for errors.
           Enable the “skipJsErrors” option to ignore JavaScript errors during test execution. Learn more: "https://testcafe.io/documentation/404038/recipes/debugging/skip-javascript-errors"
           If the website only throws this error when you test it with TestCafe, please create a new issue at:
           "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".
           JavaScript error details:
           SyntaxError: Unexpected token '<'
           Browser: Chrome 86.0.4240.111 / Alpine Linux 3.15.7
```

### Steps to Reproduce

Upgrade to 2.6.x and running in CI. Downgrading back to 2.5.0 fixes the issue consistently.

### TestCafe version

2.6.1

### Command-line arguments

n/a

### Browser name(s) and version(s)

Chrome 86

### Platform(s) and version(s)

Alpine Linux in Gitlab CI

**Comment by AlexKamaev** [comment]
This information is insufficient to find the cause of the issue. There were a lot of changes in v2.5.0 and later, so it's difficult to say precisely what led to the problem. We'll be able to research the issue only if we have an example demonstrating the incorrect behavior. Please refer to the following help topic: [How to create a Minimal Working Example when you submit an issue](https://testcafe.io/documentation/402636/faq/general-info#how-to-create-a-minimal-working-example-when-you-submit-an-issue).

**Comment by omacranger** [comment]
I understand and from the outside looking in I was trying to debug without success since I couldn't narrow down changes to the proxy very well. It seems most of the changes from 2.5.0 -> 2.6.0 were renaming experimentalProxyless to nativeAutomation so it was hard to pinpoint other unrelated changes. However, this only appears in 2.6.x. It happens _almost_ exclusively in CI (perhaps due to increased concurrency & longer jobs) by only changing the package version there.  I was hoping we could get some pointers as to what may have changed to help narrow it down and provide a smaller, more reproducible example repo for this issue.

**Comment by AlexKamaev** [comment]
There were changes in not only the TestCafe repository but the underlying `testcafe-hammerhead` module as well, so it's very difficult to determine the cause of the issue. You can create a separate GitHub repository and reproduce the issue on GitHub actions. You can also take a look at [TestCafe action](https://github.com/DevExpress/testcafe-action/(https://github.com/DevExpress/testcafe-action/)). It should help you switch between TestCafe versions (and even commits) in your test repository. This can help you find the problematic commit.

**Comment by omacranger** [comment]
Okay. I'll wait to see if the requesthook fix for native automation solves our issues. If not I'll try comparing the changes in `testcafe-hammerhead` and go from there. Thanks.
