### ISSUE TITLE
An error occurred in ClientFunction code: ReferenceError: axe is not defined in TestCafe version 2.6 and 2.6.1

### ISSUE THREAD

**Issue by ayemelyanenko-chegg** [DevExpress/testcafe#7755]
### What is your Scenario?

Would like to run the test without running into an  'An error occurred in ClientFunction code: ReferenceError: axe is not defined' issue **on version 2.6 and 2.6.1**

### What is the Current behavior?

Tests fail consistently with 'An error occurred in ClientFunction code: ReferenceError: axe is not defined'

For comparison, tests never fail with this issue when running using **2.5.1-rc.1**

### What is the Expected behavior?

Test should pass in all places without failing intermittently with 'An error occurred in ClientFunction code: ReferenceError: axe is not defined' issue on **version 2.6 and 2.6.1**

### What is your public website URL? (or attach your complete example)

https://www.citethisforme.com

### What is your TestCafe test code?

```
// @ts-ignore
import { t, Selector } from "testcafe";
const loginUrl = `https://www.citethisforme.com/login`;
export const emailForSignIn = Selector('input[id*="email"]');
export const passForSignin = Selector('input[type="password"]');
export const signInButton = Selector("button").withText("Sign in");
export const upgradeButton = Selector('button[aria-controls="accountMenu"]');
const a11y = require("./a11y.ts");

// user log in/log out methods
async function userLogInWithCredentials(
  email: string,
  password: string
): Promise<void> {
  await t.navigateTo(loginUrl);
  await t
    .typeText(emailForSignIn, email, { paste: true })
    .typeText(passForSignin, password, { paste: true })
    .click(signInButton)
    .wait(6000);
  console.log(`Logged in as user: ${email}`);
}

fixture`User log in and axe core client function failure`
  .meta({ fixtureID: "f-0001", author: "GROWTH", app: "" })
  .beforeEach(async (t) => {});

test.meta({
  testID: "t-0001",
})("User log in and axe core client function failure", async (t) => {
  await userLogInWithCredentials("sample_acct@chegg.com", "Password@123");
  await t.expect(upgradeButton.visible).ok();
  await a11y(t);
});

test.meta({
    testID: "t-0001",
  })("User log in and axe core client function failure", async (t) => {
    await userLogInWithCredentials("sample_acct@chegg.com", "Password@123");
    await t.expect(upgradeButton.visible).ok();
    await a11y(t);
  });

  test.meta({
    testID: "t-0001",
  })("User log in and axe core client function failure", async (t) => {
    await userLogInWithCredentials("sample_acct@chegg.com", "Password@123");
    await t.expect(upgradeButton.visible).ok();
    await a11y(t);
  });

  test.meta({
    testID: "t-0001",
  })("User log in and axe core client function failure", async (t) => {
    await userLogInWithCredentials("sample_acct@chegg.com", "Password@123");
    await t.expect(upgradeButton.visible).ok();
    await a11y(t);
  });

  test.meta({
    testID: "t-0001",
  })("User log in and axe core client function failure", async (t) => {
    await userLogInWithCredentials("sample_acct@chegg.com", "Password@123");
    await t.expect(upgradeButton.visible).ok();
    await a11y(t);
  });
```

### Your complete configuration file

```
module.exports = {
    clientScripts: [{ module: 'axe-core/axe.min.js' }],
    skipJsErrors: true
}
```

### Your complete test report

An error occurred in ClientFunction code:
      
ReferenceError: axe is not defined

### Screenshots

<img width="331" alt="Screenshot 2023-06-01 at 4 15 29 PM" src="https://github.com/DevExpress/testcafe/assets/14633459/385d8415-fa05-4de4-b27b-7b3ae051bbde">

### Steps to Reproduce

1. Clone https://github.com/ayemelyanenko-chegg/nextjs-nodejs-example
2. CD into nextjs-nodejs-example/
3. cd into my-app
4. npm install
5.  npx testcafe chrome tests/sampleA11yTest.ts -L -c 10

**For comparison, downgrade to version 2.5.1-rc.1 and run step 5 again. Tests will pass each time**

### TestCafe version

2.6.0 and 2.6.1

### Node.js version

18.16.0

### Command-line arguments

npx testcafe chrome tests/sampleA11yTest.ts -L -c 10

### Browser name(s) and version(s)

Chrome 114

### Platform(s) and version(s)

Mac OS

### Other

Attaching in a log file if not able to run/reproduce locally. Please search for 'ReferenceError: axe is not defined' in the log file

https://upload.disroot.org/r/jGbr3cvK#KfeLRgGF5B/OyH7Oxz74rnFHOddSjrelwVr0TVituu8=

**Comment by Dmitry-Ostashev** [comment]
Hello,

Thank you for your report. As far as I can see, the test contains a login process. Our policy prevents us from accessing a customer's internal resources without prior written approval from the entity that owns the server/web resource. We did not obtain such approval for the web site mentioned in this issue. So, please send us a written confirmation, which permits DevExpress personnel to remotely access the website and its internal resources for research/testing and debugging purposes ([support@devexpress.com](mailto:support@devexpress.com)).

**Comment by ayemelyanenko-chegg** [comment]
Hello @Dmitry-Ostashev. I sent the email with the authorization today. Thank you.

**Comment by Dmitry-Ostashev** [comment]
Thank you for your email. I reproduced the issue.

**Comment by miherlosev** [comment]
Fixed in https://github.com/DevExpress/testcafe/pull/7771.
