### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'numericFieldValidator')

### ISSUE THREAD

**Issue by rawat9** [DevExpress/testcafe#7758]
### What is your Scenario?

The error on the browser console when form dialog is opened, however the test passes.

Project dependencies:
- `Angular` **v15.2.9**
- `ngx-formly` **v6.1.7**
- `testcafe` **v2.6.0**

**_Note_**: The issue didn't occur with `ngx-formly v5.12.7`. Only with `versions > 6.x.x`

### What is the Current behavior?

The error on the browser console when form dialog is opened.

### What is the Expected behavior?

There is no error on the browser console and the test still passes.

### What is your public website URL? (or attach your complete example)

We created a test project for testcafe team to reproduce the bug.

Link: https://github.com/rawat9/test

### What is your TestCafe test code?

```typescript
// e2e/tests/general.e2e-spec.ts
...
const numberField = Selector('mat-label').withText('Test number').parent().child('formly-field-mat-input').child('input');
await t.click(button);
await t.typeText(numberField, '3')
...
```

### Your complete configuration file

```typescript
module.exports = {
  browsers: 'chrome',
  clientScripts: [{ module: 'axe-core/axe.min.js' }],
  src: ['e2e/tests/*.e2e-spec.ts'],
  screenshots: {
    path: 'tmp/screenshots/',
    takeOnFails: true,
    pathPattern: '${DATE}_${TIME}_${TEST}_${QUARANTINE_ATTEMPT}.png',
  },
  concurrency: 1,
  selectorTimeout: 4000,
  quarantineMode: {
    successThreshold: 1,
    attemptLimit: 3,
  },
  compilerOptions: {
    typescript: {
      customCompilerModulePath: '../typescript',
    },
  },
};
```

### Screenshots

![image001](https://github.com/DevExpress/testcafe-hammerhead/assets/64035803/7f482bbb-c740-44a8-86fd-b82184a91b22)

### Steps to Reproduce

1. Start the app locally (`npm run start`)
2. In separate session, run the test (`npm run test`)
3. Open the TestCafe browser console and see the error

### TestCafe version

2.6.0

### Node.js version

18.16.0

### Command-line arguments

--config-file=e2e/.testcaferc.js

### Browser name(s) and version(s)

Chrome 114.0.0.0

### Platform(s) and version(s)

macOS Ventura 13

**Comment by rawat9** [comment]
Thanks for your reply. I tried adding `nativeAutomation: true` in testcafe config as you recommended. It works fine for the example "test" repository however it doesn't work for our main repository.

**Comment by AlexKamaev** [comment]
@rawat9
Thank you for sharing this information. The Native Automation mode is one of our prior tasks right now. We would really appreciate it if you share a simple project containing your main repository (if it's possible). We will check it in Native Automation mode.

**Comment by rawat9** [comment]
Thanks for your reply. Unfortunately it won't be possible to share our project. We will consider looking into your suggestion i.e with `nativeAutomation` in-depth.

**Comment by rawat9** [comment]
With `TestCafe v2.6.2`, the error didn't occur with Native Automation mode enabled and the test passes. However, it has introduced a few other failing tests. These tests open new browser tab and from referring to the docs, I think Native Automation doesn't yet support multiple windows/tabs. This issue is already raised I think - #7661. Is TestCafe team already working on this?

Is there a workaround for this too temporarily until fixed?

**Comment by AlexKamaev** [comment]
Hi @rawat9,

We are actively working on the Native Automation mode. However, as you mentioned, this mode does not support testing in multiple windows yet. At present, we cannot give you any precise estimates on when this will be implemented in Native Automation.

I recommend that separate your TestCafe tasks into two:

* use Native Automation for general purposes, including this issue
* do not use Native Automation for specific tests that use multiple windows
