### ISSUE TITLE
When takeOnFails is triggered, fullPage is ignored: the screenshot is not full-page.

### ISSUE THREAD

**Issue by DanKaplanSES** [DevExpress/testcafe#7761]
### What is your Scenario?

I want to create a screenshot of the entire page on failure. `.takeScreenshot({fullPage: true})` in my test does this, but `    "takeOnFails": true, "fullPage": true` in my configuration does not.

### What is the Current behavior?

A non-fullscreen screenshot is taken.

### What is the Expected behavior?

A fullscreen screenshot is taken.

### What is your public website URL? (or attach your complete example)

https://advancedinstaller.com/blog/page-1.html

### What is your TestCafe test code?

```ts
import { Selector } from 'testcafe';

fixture.only`test`.page(`https://advancedinstaller.com/blog/page-1.html`);

test(`test screenshot of blog page`, async (t) => {
  await t
    .resizeWindow(768, 800)
    .click(Selector('#cookies button'))
    .click(Selector('#cookies button').withText('There is no way this exists'));
});
```

### Your complete configuration file

```json
{
  "browsers": ["firefox:headless"],
  "screenshots": {
    "takeOnFails": true,
    "fullPage": true
  },
  "compilerOptions": {
    "typescript": {
      "customCompilerModulePath": "../typescript",
      "options": { "forceConsistentCasingInFileNames": "false" },
      "configPath": "tsconfig.testcafe.json"
    }
  }
}
```

### Screenshots

![image](https://github.com/DevExpress/testcafe/assets/373675/6a929d06-43d4-47c2-9323-8cbba19181b0)

### Steps to Reproduce

```ts
import { Selector } from 'testcafe';

fixture.only`test`.page(`https://advancedinstaller.com/blog/page-1.html`);

test(`test screenshot of blog page`, async (t) => {
  await t
    .resizeWindow(768, 800)
    .click(Selector('#cookies button'))
    .click(Selector('#cookies button').withText('There is no way this exists'));
});
```

### TestCafe version

2.5.0

### Node.js version

v18.15.0

### Command-line arguments

'tsc/**.ts'"

### Browser name(s) and version(s)

113.0.2 (64-bit)

### Platform(s) and version(s)

Windows 10

### Other

This has been around for a while and probably exists on chrome browsers, too; [I've basically turned this comment into its own issue.](https://github.com/DevExpress/testcafe/issues/5961#issuecomment-1292498592)

**Comment by AlexKamaev** [comment]
I managed to reproduce the issue. I confirm that the `fullPage` option is ignored in `debugOnFail` mode. We will research the issue on our side, but I can't give you any promises or time estimates. Thank you for your report.

**Comment by DanKaplanSES** [comment]
> I managed to reproduce the issue. I confirm that the `fullPage` option is ignored in `debugOnFail` mode. 

I'm not sure I'm familiar with `debugOnFail`. Did you mean `takeOnFails`?

**Comment by AlexKamaev** [comment]
Yes, I meant the takeOnFails option. Sorry for the typo.
