### ISSUE TITLE
Unable to open Gherkin-Testcafe report with 7.00 version

### ISSUE THREAD

**Issue by testcafe-HK** [DevExpress/testcafe#7765]
### What is your Scenario?

"testcafe-reporter-cucumber-json": "^6.3.0" version is not working with Gerkin-Testcafe 7.00 version.
when I run npm run report .Report is opening blank. Can anyone update the gherkin-testcafe version in reporter. It works fine with TG version 5.6.7 .

### What is the Current behavior?

Report is opening with bad/blank page

### What is the Expected behavior?

Report should be open with all test details

### What is your public website URL? (or attach your complete example)

TBD

### What is your TestCafe test code?

npm run report

https://www.npmjs.com/package/testcafe-reporter-cucumber-json

### Steps to Reproduce

1.Run the test in Gherkin-Testcafe 7 Version
2. Run the report via npm run report
3.

### TestCafe version

7.00

### Node.js version

18

### Command-line arguments

npm run report

### Other

sdsd

**Comment by miherlosev** [comment]
Hi @testcafe-HK,

The TestCafe team doesn't develop and maintain `gerkin-testcafe` and [testcafe-reporter-cucumber-json](https://www.npmjs.com/package/testcafe-reporter-cucumber-json) modules. Please address this issue to the `gerkin-testcafe` or `testcafe-reporter-cucumber-json` repository.
