### ISSUE TITLE
Native Automation: Monaco editor does not show code completion widget when testing in native automation mode

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe#7770]
### What is your Scenario?

Test the Monaco Editor code completion.

### What is the Current behavior?

When typing some text, the editor should display a code completion widget with code suggestions. It is working fine in proxied mode. However, the widget is not shown in native automation mode.

### What is the Expected behavior?

The code completion widget should appear in native automation mode.

### What is your public website URL? (or attach your complete example)

https://microsoft.github.io/monaco-editor/playground.html?source=v0.39.0#example-creating-the-editor-hello-world

### What is your TestCafe test code?

```
import { Selector } from "testcafe";

fixture`monaco`.page`https://microsoft.github.io/monaco-editor/playground.html?source=v0.39.0#example-creating-the-editor-hello-world`; 

test('Test', async t => {
    await t
        .typeText(Selector('.inputarea'), 'document')
        .debug();
});
```

### Screenshots

Proxied mode:
![image](https://github.com/DevExpress/testcafe/assets/24777868/1802cf92-0af5-42b1-ae4b-e7dec44772e7)

Native automation mode:
![image](https://github.com/DevExpress/testcafe/assets/24777868/a0b460f8-9aff-4cd4-ae2d-df959eb2d2c4)

### Steps to Reproduce

Run the test above in native automation and proxied modes.

### TestCafe version

2.6.2

### Node.js version

18.16.0

### Command-line arguments

npx testcafe chrome test.js

### Browser name(s) and version(s)

Chrome

### Platform(s) and version(s)

Windows 10

**Comment by AlexKamaev** [comment]
fixed in https://github.com/DevExpress/testcafe/pull/7773
