### ISSUE TITLE
Native Automation: TestCafe hangs when it accesses text files.

### ISSUE THREAD

**Issue by AlexKamaev** [DevExpress/testcafe#7786]
### What is your Scenario?

Navigating to a text file causes TestCafe to hang.

### What is the Current behavior?

After navigating to a text file, TestCafe becomes unresponsive.

### What is the Expected behavior?

TestCafe should not hang when navigating to a text file.

### What is your public website URL? (or attach your complete example)

Page
```HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="get" action="./file.txt">
    <button id="btn" type="submit">Go to file</button>
</form>
</body>
</html>
```
Test file:
```
// file.txt
Any text here
```

### What is your TestCafe test code?

```JS
fixture`Interact With the Page`
    .page`./index.html`

test('Click', async t => {
    await t
        .click('#btn')
});
```

### Steps to Reproduce

1. Launch TestCafe in Native Automation mode.
2. TestCafe becomes unresponsive and hangs.

### TestCafe version

3.0.0-rc.1

### Command-line arguments

testcafe chrome test.js

### Browser name(s) and version(s)

Chromium-based

**Comment by miherlosev** [comment]
It's a synthetic scenario. We will not consider it until the first real-life user case.
