### ISSUE TITLE
It is not possible to set the `httpOnly` flag via the `setCookies` action in Native Automation mode

### ISSUE THREAD

**Issue by aleks-pro** [DevExpress/testcafe#7793]
### What is your Scenario?

Try to set the `httpOnly` flag with true value via `setCookies` test action

### What is the Current behavior?

The `httpOnly` flag is not set

### What is the Expected behavior?

The `httpOnly` flag value should be true

### What is your public website URL? (or attach your complete example)

https://devexpress.github.io/testcafe/example/

### What is your TestCafe test code?

```ts
fixture`[API] Set Cookies`
    .page('https://devexpress.github.io/testcafe/example/');

test('Should set cookies with special properties', async t => {
    const cookieObject = { name: 'apiCookie1', value: 'value1', domain: 'localhost', httpOnly: true };

    await t.setCookies(cookieObject);

    const cookies = await t.getCookies();

    await t
        .expect(cookies.length).eql(1)
        .expect(cookies[0]).contains(cookieObject);
});
```

### Steps to Reproduce

Run the following example in Native Automation mode: https://github.com/DevExpress/testcafeio-examples/blob/main/tests/documentation/reference/test-api/test-controller/set-cookies/single-with-props.js

### TestCafe version

3.0.0-rc.1

### Command-line arguments

npx testcafe chrome

### Browser name(s) and version(s)

Chrom 113

### Platform(s) and version(s)

Mac OS Ventura

**Comment by miherlosev** [comment]
Fixed in https://github.com/DevExpress/testcafe/pull/7844
