### ISSUE TITLE
Native Automation Mode: Click on a button at very bottom of a page inside an iframe does not work

### ISSUE THREAD

**Issue by Kirdock** [DevExpress/testcafe#7797]
### What is your Scenario?

If an element in an iframe is at the very bottom of a page, testcafe does not click the element if told so. It also does not throw any errors. exists works, clicks works, but the click does not trigger a click.

### What is the Current behavior?

The element is not clicked

### What is the Expected behavior?

The element is clicked

### What is your public website URL? (or attach your complete example)

https://codesandbox.io/s/jolly-star-w6d2cv?file=/src/App.js

If you set the variable on top (marginBottom) to e.g., "100px" the test succeeds.

### What is your TestCafe test code?

```ts
import { ClientFunction, Selector } from 'testcafe';

fixture(`Getting Started`).only;

test('My first test', async (t) => {
  const button = Selector('#test');
  const iframeSelector = Selector('#sandbox-preview');
  const rightContentItems = Selector('.elements__Container-l1fwko-0');
  const clickedText = Selector('#clicked');

  await t
    .setNativeDialogHandler(() => true)
    .navigateTo('https://codesandbox.io/s/jolly-star-w6d2cv?file=/src/App.js')
    .expect(
      // I just need to remove one element in the right panel in order to move the button more to the bottom
      ClientFunction<boolean, [Selector]>((selector: Selector) => {
        const element = selector() as unknown as HTMLElement | undefined;
        element?.remove();
        return true;
      })(rightContentItems.nth(1)),
    )
    .ok()
    .expect(rightContentItems.count)
    .eql(1);

  await t
    .switchToIframe(iframeSelector)
    .wait(2000)
    .expect(button.exists)
    .ok()
    .click(button)
    .expect(clickedText.textContent)
    .eql('Clicked: true');
});

```

### Your complete configuration file

```js
/** @type {import('testcafe/ts-defs').TestCafeConfigurationOptions */
module.exports = {
  compilerOptions: {
    typescript: {
      configPath: "./e2e/tsconfig.json",
    }
  },
  browsers: ['chrome:headless'],
  src: ['e2e/tests'],
  skipJsErrors: true,
};
```

### Steps to Reproduce

1. Have an app with an iframe
2. The iframe has a button at the very bottom (there should be any space between the button and the end of the window)
3. Click the button
4. Wonder why the click did not work

### TestCafe version

3.0.0-rc1

### Node.js version

18.15.0

### Command-line arguments

--debug-on-fail chrome

**Comment by AlexKamaev** [comment]
Thank you for reaching out to us. I managed to reproduce the issue. We'll research it and follow up with you promptly.

**Comment by AlexKamaev** [comment]
for the team:
I researched the issue. The problem is in the Status Bar. It overlaps the button.
