### ISSUE TITLE
The DOMNodeState.style object does not contain some style properties

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe#7800]
### What is your Scenario?

Check how an element inherits the `white-space` style property.

### What is the Current behavior?

The expressions `Selector('p').withText('Some text').style['white-space']` and `Selector('p').withText('Some text').style['whiteSpace']` return `undefined`. However, the `window.getComputedStyle(p)['white-space']` expression returns a correct value.

### What is the Expected behavior?

The DOMNodeState.style property should work in the same way as the method [getComputedStyle()](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle) works.

### What is your public website URL? (or attach your complete example)

```
<html>
	<body>
	    <style type="text/css">            
                    div > span {
                        white-space: pre-wrap;
                    }
            </style>
            <div>
                <span>
                    <p>Some text</p>
                </span>
            </div>
	</body>
</html>
```

### What is your TestCafe test code?

```
import { Selector } from 'testcafe';

fixture `New Fixture`
    .page `file:///C:/Work/Pages/page.html`;
    
test(`New Test`, async t => {
    const style = await Selector('p').withText('Some text').style;

    console.log(style);
    console.log(style['white-space']);
    console.log(style['whiteSpace']);

    await t.expect(Selector('p').withText('Some text').style['white-space']).eql('pre-wrap');
});
```

### Steps to Reproduce

1. Run the test. It will fail.
2. Run the code below in the browser console. It will return a correct value.

`window.getComputedStyle(document.querySelector('p'))['white-space'];`

### TestCafe version

3.0.0-rc.1

### Command-line arguments

npx testcafe chrome test.js

**Comment by Dmitry-Ostashev** [comment]
@Klaster1 Yes, it looks like a bug. This issue appeared after the Chrome update.

**Comment by miherlosev** [comment]
It's a bug in Google Chrome. If you inspect style properties by their index, the `white-space` property will not exist:
![](https://github.com/DevExpress/testcafe/assets/4133518/e1ac61df-fbdd-4e35-897e-75d50e9dab6c)
![](https://github.com/DevExpress/testcafe/assets/4133518/e723c25e-1b95-42b1-9932-64a20903e833)

If you get the style property value by its name, it returns the correct value:
![](https://github.com/DevExpress/testcafe/assets/4133518/63f9cd2c-8d1f-46c0-80ab-1033519e3a08)

Please use a workaround based on `ClientFunction` for Edge:

```js
const selector = Selector('p').withText('Some text');

const getWhiteSpaceStyleProperty = ClientFunction(() => {
        return window.getComputedStyle(el())['white-space'];
}, { dependencies: {el : selector }});

await t.expect(getWhiteSpaceStyleProperty()).eql('pre-wrap');
```

Alternatively, use a workaround based on the `Selector.getStyleProperty` method:

```js
// NOTE: property name can be changed to the camel case notation
const selector = Selector('p').withText('Some text');

await t.expect(selector.getStyleProperty('whiteSpace')).eql('pre-wrap');
```

**Comment by Klaster1** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1449763
https://github.com/w3c/csswg-drafts/issues/8398
