### ISSUE TITLE
Testcafe does not interact with any DOM elements on salesforce page

### ISSUE THREAD

**Issue by tgrisley** [DevExpress/testcafe#7801]
### What is your Scenario?

I have an example within my project where testcafe does not find any elements once a specific salesforce page has loaded

### What is the Current behavior?

No matter what selector combination I try, no elements on this page can be found. 

Have tried waiting, switching iframes, etc. 

### What is the Expected behavior?

Testcafe to find the elements 

### What is your public website URL? (or attach your complete example)

economist.com

### What is your TestCafe test code?

```
import { fixture, Selector } from 'testcafe';
fixture `example`
.page('https://myaccount.economist.com/s/login')
 
const submitButton = Selector('.call-to-action-button_full_width')

test('this should click something', async t => {
  await t.click(submitButton)
  console.log('should get here')
});
```

### Your complete test report

The specified selector does not match any element in the DOM tree.
      
       > | Selector('.call-to-action-button_full_width')

### Steps to Reproduce

1. Run code above
2. Notice it fails
3. Try other selector types
4.  Still fails

### TestCafe version

2.5.1

### Command-line arguments

testcafe chrome example.js

**Comment by Aleksey28** [comment]
Hi @tgrisley,

This issue does not relate to TestCafe. I tried to open the page from the test manually and to execute the command `document.querySelector('.call-to-action-button_full_width')`. I got `null`.
