### ISSUE TITLE
ERROR TypeError: Cannot read properties of null (reading 'pendingTaskDonePromise')

### ISSUE THREAD

**Issue by joey-beech-it** [DevExpress/testcafe#7805]
### What is your Scenario?

I am using Jenkins to run some tests. We seem to get some errors after updating to the latest version of testcafe.
We run quite some tests ~100 / hour
The test are mostly stable 99% and we would like them to be 100% stable. Or atleast fix the error mentioned in the title. 
We've had unstable behaviour before but after the update we get relevant errors. 

### What is the Current behavior?

We run alot of test with the following Jenkins job configuration.
We have a different 'MyFolder' for each customer - mostly 5-6 tests for each folder.
These are small tests and usually take no long then 5 seconds after the browser and page is loaded. 

```
#!/bin/bash
echo prepare testsuite
node -v
npm install
cd node_modules/testcafe/bin
node testcafe.js chrome:headless ../../../1-Anonimyzed/* reporter:json -q --disable-http2 attemptLimit=3,successThreshold=1
```

### What is the Expected behavior?

Test will pass or atleast run accordingly. 

### What is your public website URL? (or attach your complete example)

Unable to share URL. This however occurs on alot of different domains, even domains like google.com. 
Its very inconsistant and not domain bound.

### What is your TestCafe test code?

Testcafe runs are usually very simple tests that are like the following. However the error occurs before the tests are run.

```
import {Selector} from 'testcafe';

fixture`Customer`
    .page`https://www.google.com/`;

test('Customer.test.js - link: https://www.google.com/, async t => {

    await t
        .expect(Selector(".ClassOnImgTag").count).gt(0, 'there should be more than 1 logo')
});
```

### Your complete configuration file

We have no specific configuration file. So i guess it falls back to all the default values.

### Your complete test report

```
13:46:31 Started by timer
13:46:31 Running as SYSTEM
13:46:31 Building in workspace /var/lib/jenkins/workspace/1-Anonimyzed
13:46:31 The recommended git tool is: NONE
13:46:31 using credential 9a3be32d-f2fe-46bd-8be0-12b4615cd630
13:46:31  > git rev-parse --resolve-git-dir /var/lib/jenkins/workspace/1-Anonimyzed/.git # timeout=10
13:46:31 Fetching changes from the remote Git repository
13:46:31  > git config remote.origin.url https://gitlab.anonimyzed.it/anonimyzed/testing/uptest.git # timeout=10
13:46:31 Fetching upstream changes from https://gitlab.anonimyzed.it/anonimyzed/testing/uptest.git
13:46:31  > git --version # timeout=10
13:46:31  > git --version # 'git version 2.25.1'
13:46:31 using GIT_ASKPASS to set credentials
13:46:31  > git fetch --tags --force --progress -- https://gitlab.anonimyzed.it/anonimyzed/testing/uptest.git +refs/heads/*:refs/remotes/origin/* # timeout=10
13:46:31  > git rev-parse origin/master^{commit} # timeout=10
13:46:31 Checking out Revision 3e3c4ef112a6eb1c818a23c17662233f064cfe78 (origin/master)
13:46:31  > git config core.sparsecheckout # timeout=10
13:46:31  > git checkout -f 3e3c4ef112a6eb1c818a23c17662233f064cfe78 # timeout=10
13:46:31 Commit message: "Merge branch 'set-external-cert-test-to-10-days' into 'master'"
13:46:31  > git rev-list --no-walk 3e3c4ef112a6eb1c818a23c17662233f064cfe78 # timeout=10
13:46:31 [1-Anonimyzed] $ /bin/bash /tmp/jenkins14338792129680546090.sh
13:46:31 prepare testsuite
13:46:31 v18.16.0
13:46:33
13:46:33 up to date, audited 473 packages in 1s
13:46:33
13:46:33 35 packages are looking for funding
13:46:33   run `npm fund` for details
13:46:33
13:46:33 found 0 vulnerabilities
13:48:38 ERROR TypeError: Cannot read properties of null (reading 'pendingTaskDonePromise')
13:48:38     at /var/lib/jenkins/workspace/1-Anonimyzed/node_modules/testcafe/src/runner/index.js:183:75
13:48:38     at Array.map (<anonymous>)
13:48:38     at Runner._getTaskResult (/var/lib/jenkins/workspace/1-Anonimyzed/node_modules/testcafe/src/runner/index.js:183:41)
13:48:38
13:48:38 Type "testcafe -h" for help.
13:48:38 Build step 'Execute shell' marked build as failure
13:48:38 Sending e-mails to: jenkins@anonimyzed.it
13:48:39 Finished: FAILURE
```

### Steps to Reproduce

No idea, since its very inconsistent. 

### TestCafe version

2.6.~

### Node.js version

v18.16.0

### Command-line arguments

node testcafe.js chrome:headless ../../../1-Anonimyzed/* reporter:json -q --disable-http2 attemptLimit=3,successThreshold=1

### Browser name(s) and version(s)

The Chrome 114.0.5735.106 (updating regularly)

### Platform(s) and version(s)

Ubuntu 20.4 LTS

**Comment by miherlosev** [comment]
Hi @joey-beech-it 

I believe the 'json' reporter finished incorrectly.
Try collecting the extended log using the DEBUG environment variable:

```js
set DEBUG=testcafe:*,hammerhead:*
testcafe chrome index.js 2> testcafe.log
```

and share it with us.

**Comment by joey-beech-it** [comment]
@miherlosev 

For some reason we have not encoutered it for a whole week now with out any changes. Seems to be more stable. So i am not able to give a log at the moment

**Comment by miherlosev** [comment]
> For some reason we have not encoutered it for a whole week now with out any changes

I'm happy to hear that.

> Seems to be more stable. So i am not able to give a log at the moment

I added [additional debug logic](https://github.com/DevExpress/testcafe/pull/7829) for the `Reporting` subsystem. If you encounter the same issue again, please run your tests with the next TestCafe version and share the debug log with us.
