### ISSUE TITLE
t.takeScreenshot does not finish on Ubuntu

### ISSUE THREAD

**Issue by Kirdock** [DevExpress/testcafe#7809]
### What is your Scenario?

When running a test with a `t.takeScreenshot()` step, testcafe does not finish and the test runs indefinitely. The next steps aren't executed. The error seems to appear after v2.6.0. Everything is working fine with <=2.6.0. The screenshot is taken, it just does not proceed.
On Windows it is working but not on Ubuntu.

### What is the Current behavior?

Testcafe does not proceed after `t.takeScreenshot()`

### What is the Expected behavior?

The test goes on or finishes

### What is your public website URL? (or attach your complete example)

not needed

### What is your TestCafe test code?

```ts
fixture`screenshot bug`.only;

test('screenshot', async (testController) => {
  await testController.navigateTo('https://google.com');
  await testController.takeScreenshot();
});

```

### Your complete configuration file

```js
/** @type {import('testcafe/ts-defs').TestCafeConfigurationOptions */
module.exports = {
  compilerOptions: {
    typescript: {
      configPath: "./e2e/tsconfig.json",
    }
  },
  browsers: ['chrome:headless'],
  src: ['e2e/tests'],
  screenshots: {
    path: 'screenshots',
    takeOnFails: true,
    fullPage: true,
  },
};
```

### Steps to Reproduce

1. Use Ubuntu
2. Take a screenshot in a test
3. Wonder why the test is not finishing

### TestCafe version

2.6.2

### Node.js version

16.20.0

### Command-line arguments

--debug-on-fail chrome

### Browser name(s) and version(s)

Chrome 107.0.0.0

### Platform(s) and version(s)

Ubuntu 20.04.5 LTS (Windows WSL)

**Comment by aleks-pro** [comment]
Hello @Kirdock ,

Please try to run your tests with `testcafe-browser-tools` version 2.0.23 and share the result with us. To achieve this, you can add the [overrides ](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) section to the `package.json`:
```json
{
    "overrides": {
        "testcafe-browser-tools": "2.0.23"
    }
}
```
and run the `npm install` command.

**Comment by Kirdock** [comment]
@aleks-pro I can confirm that with this version it is working as intended.

**Comment by aleks-pro** [comment]
Thank you for the update.

I will close this issue as a duplicate. We will address your usage scenario in the context of the following issue since they have the same cause: https://github.com/DevExpress/testcafe/issues/7752.

You can follow it to be notified about our progress.
