### ISSUE TITLE
Clicks flaky due to cumulative content shifts (CLS)

### ISSUE THREAD

**Issue by Klaster1** [DevExpress/testcafe#7812]
### What is your Scenario?

I want to click on stuff and not think about marginal CLS edge cases.

### What is the Current behavior?

Sometimes, only the `mousedown` portion of the click completes, resulting in unstable test runs. It's tough to know beforehand where you have to use a workaround [without sampling the test extensively](https://github.com/DevExpress/testcafe/issues/7445).

After asking around, I discovered that WebDriver does not have this issue because[ it synthesizes `click` in a single operation](https://github.com/SeleniumHQ/selenium/blob/c3b226cebff8caf4fdbc792b87f2de23f42dab3a/javascript/atoms/device.js#L383), while [TestCafe requests element coordinates once at the start of the action and uses the same coordinates to trigger multiple events](https://github.com/DevExpress/testcafe/blob/v3.0.0-rc.1/src/client/automation/playback/click/index.ts), with short delays in-between. The asynchronous, multi-step click approach leaves gaps for CLS to affect the result, by design. Maybe triggering events synchronously from the client code would work?

Obviously, you can argue that real users of my app will experience the same issue, that I have to fix instances of CLS myself and the reported behavior actually benefits me by exposing the issue. On the other hand, everyone in my team shares a notion that calling `t.click` should always do what it was told to, the same as what a hypothetical real person would have done if they were asked to perform the action, and that such obscure behaviors you have to be aware of when authoring the tests cause more trouble than good.

### What is the Expected behavior?

`t.click` succeeds every time. Maybe log a warning that a CLS happened, similar to what TC does when clicking obscured elements, let the test author to decide on what they compromise - test stability or fixing minor CLS instances.

### What is your TestCafe test code?

[testcafe-clicks.zip](https://github.com/DevExpress/testcafe/files/11784226/testcafe-clicks.zip)
Run the `test:bad` npm script to reproduce the issue, `test:good` for a workaround demo. Tweak the animation variables in the `index.html` to increase failure rate or increase the concurrency.

### Steps to Reproduce

1. Have web page with content that content layout shifts.
2. Write a test that clicks on an element position of which is affected by CLS.
3. Run the test multiple times, under high load.

### TestCafe version

2.6.1 NA off, 3.0.0-rc.1 NA on

### Node.js version

18.15.0

### Browser name(s) and version(s)

Chrome 114

### Platform(s) and version(s)

Windows 11, macOS

### Other

Similar to [this issue](https://github.com/DevExpress/testcafe/issues/1934).

**Comment by AlexKamaev** [comment]
I reproduced the issue. We agree that clicking on an element in this use case can work unstably. However, we cannot estimate when we fix the issue. You can create a PR with a fix; we'll accept it if everything is OK. You can also use the workaround you described.

**Comment by AlexKamaev** [comment]
I've researched the issue and concluded that we currently cannot give you a 100% accurate solution for this behavior for both the Native Automation and `proxy` modes. So, in this specific use case, we recommend using the workaround with the `t.dispatchEvent` method call.
