### ISSUE TITLE
possibility to disable the Visual Selector Debugger

### ISSUE THREAD

**Issue by chris125964** [DevExpress/testcafe#7816]
### What is your Scenario?

Deactivate the Visual Selector Debugger by configuration

### What are you suggesting?

In my project the Visual Selector Debugger hides some buttons at the bottom line which are needed to continue the program to be tested. That means if the program stops at a debugger breakpoint then the Visual Selector Debugger appears and thus prevents the from being continued manually even if the "Unlock Page" button has been pressed.
Since the Visual Selector Debugger is not always required it would be helpful to have an option to deactivate by a configuration option.

**Comment by Aleksey28** [comment]
Hi @chris125964,

Please elaborate on your goal. Do you want to click this button manually in debug mode?

If you just want to stop before clicking and then click 'Resume' or 'Next action', TestCafe will hide the Debug Panel before executing the click action.

**Comment by chris125964** [comment]
Yes, I want to click the button manually in debug mode but it is hidden by the Visual Selector Debugger bar.

There is currently no useful way to click this button as it is covered by the Visual Selector Bar. The only workaround at the moment is to increase the height of this button so that part of it is visible above the Visual Selector Debugger Bar and can therefore be selected again.

**Comment by Aleksey28** [comment]
I see. There is no way to hide the debug panel. Please describe your use case - why do you need to click this button manually? Why not use a testcafe action to click before the debugging step?

**Comment by bladyk1** [comment]
Hi, this Visual Selector Debugger disturbs a lot. It should have a button(e.g.minimize) to hide it like each windows has.
My use case is that I run the test in the TestCafe with debug mode. 
It's running 10 minutes, reach the page which I need and then when it stops I am checking selectors and adding them to the code. As well i would like to play manually with the buttons which are hidden behind this debugger.
It would save me a lot of time if I could do it this way.

**Comment by Aleksey28** [comment]
Hi @bladyk1,

I understand. As a workaround, you can temporarily add a `display: none` style for this panel and click wherever you want. We will update this thread once we have news about this feature.

**Comment by PavelMor25** [comment]
Hello everyone,

We have added a new button that hides the Visual Selector Debugger. You can find more details in the [release notes](https://testcafe.io/404619/release-notes/framework/2023-11-10-testcafe-v3-4-0-released).
