### ISSUE TITLE
Visual selector debugger chrome/edge extension

### ISSUE THREAD

**Issue by liviuavram** [DevExpress/testcafe#7818]
### What is your Scenario?

I would like to be able to test my selectors without running the actual tests.

### What are you suggesting?

A good solution in my opinion would be to be able to test individual selectors while I write them is to have the Visual selector debugger implemented in v 2.4.0 as a browser extension or have the option to fire it up somehow without running the test and wait for a failure.

### What alternatives have you considered?

I just intentionally fail tests to be able to test my selectors 1 by 1 before actually writing new tests.

**Comment by Aleksey28** [comment]
Hi @liviuavram,

It's hard to extract Selector Debugger as a plugin for architectural reasons. We aren't ready to take on this task.

However, I have a solution for you. You don't have to rerun your test for each step. Just click `Unlock Page` on the debug bar. Then, you can pick an element selector, save it to your test, manually click this element, then repeat these steps until you perform all actions from your test. Don't click `Resume` or `Next Action` in this case. Please refer to the video and drop us a line if you have more questions.

https://github.com/DevExpress/testcafe/assets/32869530/4ce6683a-a69d-49ef-a1c9-82cfdb52dd28
