### ISSUE TITLE
typeText overwrite previous letters 

### ISSUE THREAD

**Issue by Rmichalowski** [DevExpress/testcafe#7819]
### What is your Scenario?

Using TypeText into primefaces calendar field writes some letters and then deletes some of the input leaving empty spaces. 
It happens often when chrome tab is in background, but also sometimes when it's visible.  Tried with different speed and parameters and nothing.

<img width="727" alt="Zrzut ekranu 2023-06-21 115907" src="https://github.com/DevExpress/testcafe/assets/58588822/a50fa2d4-9887-4a76-9db3-2f3179a18dd6">
<img width="274" alt="image" src="https://github.com/DevExpress/testcafe/assets/58588822/beac390d-0473-4e71-b433-b33898224cd1">
<img width="532" alt="image" src="https://github.com/DevExpress/testcafe/assets/58588822/c294e55d-2c36-4708-9fe2-259490d829fb">

### What is the Current behavior?

Testcafe overwrites input leaving empty spaces in date. 

### What is the Expected behavior?

Just inputing whole date.  

### What is your public website URL? (or attach your complete example)

using  <p:calendar> from jsf primefaces library create's this issue. 

### What is your TestCafe test code?

.click('#offersConsignDeadlineCalendar_input')
        .typeText('#offersConsignDeadlineCalendar_input',nextMinuteDateFormattedWithHour(),{  speed: 0.2, replace: true, caretPos: 0, paste: true  })
        .typeText('#offersOpeningDateCalendar_input',nextMinuteDateFormattedWithHour(),{  speed: 0.2, replace: true, caretPos: 0 })
        .typeText('#generalNoteInput',nextMinuteDateFormattedWithHour(),{ speed: 0.2, replace: true, caretPos: 0 })

### Steps to Reproduce

1.TypeText into primeface's library calendar input field in format dd / MM / yyyy HH:mm. Input string like '21.06.20231000'

### TestCafe version

2.6.2

### Node.js version

18.16.0

### Command-line arguments

using both testcafe play button and chrome \test.js --url='exmpale.xhtml''

### Browser name(s) and version(s)

Chrome 114

### Platform(s) and version(s)

Windows 11

**Comment by Rmichalowski** [comment]
https://github.com/DevExpress/testcafe/assets/58588822/bf468828-d57f-45d6-a225-e10769c82f2b

Issue when pasting/ typing  '210620231245' 

When pasting or typing this manually everything works ok.

**Comment by Rmichalowski** [comment]
I ve created repo with jsf app, tomcat server to run app, and testcafe test. I ran it in intellij. 

https://github.com/Rmichalowski/testCafeDateFail

**Comment by AlexKamaev** [comment]
@Rmichalowski
Could you please write an instruction on how to run your application? It appears I missed some required packages like `mvn`. Please share some details and please note that we cannot just download IntelliJ to run your tests.

**Comment by Rmichalowski** [comment]
I cannot provide different instructions than run in community intellij, cause it's the only one i used. You can use any other IDE with server for java ee. Mvn packages are in pom.xml so they should automatically be downloaded (primefaces, javax servlet). Tomcat is server which runs in intellij. You can use other server to run java classes. When app is running i used testcafe studio to run test.js file using url of the tomcat server. 

I have tested this for a few days and i've found the problem is with primefaces v6.1.0 object: Calendar with attribute mask:true. 

You can use this example in any application : 
<p:calendar id="offersConsignDeadlineCalendar"
					value="26 / 06 / 2023 / 12:26"
					showOn="both" navigator="true"
					pattern="dd / MM / yyyy HH:mm" mask="true"
					mindate="26 / 06 / 2023 / 10:26"
					placeholder="test" styleClass="material" locale="pl"
					required="true"
					requiredMessage="test">
			<p:ajax global="false" event="dateSelect"/>

</p:calendar>

**Comment by AlexKamaev** [comment]
This scenario is too complex to reproduce it in our environment. I see that PrimeFaces controls have their own demo page. Please try to reproduce the problematic behavior on a public page or share another example that does not require any additional setup

**Comment by Rmichalowski** [comment]
Demo page is on version above 6. I am working on old project with lots of usage of primefaces 6 which cannot be updated to higher version. Oldest documentation and page with examples from primefaces is on version 7.

**Comment by AlexKamaev** [comment]
In the case of a dockerized app, we will not be able to research and debug the problematic behavior. The best option is to prepare a sample that demonstrates the issue on our machines.
