### ISSUE TITLE
"AssertionError: expected undefined to..." when testing for statusText property of HTTP response in testcafe v3.0.0

### ISSUE THREAD

**Issue by rafal-k** [DevExpress/testcafe#7825]
### What is your Scenario?

I send a HTTP request and expect to get a response with its `status` and `statusText` properties in order to use them in assertions.

### What is the Current behavior?

I can access the response's `status` property, but not the `statusText` property. This was not the case in TC v2.6.2, where both properties were available.

### What is the Expected behavior?

I can access both `status` and `statusText` properties.

### What is your public website URL? (or attach your complete example)

N/A

### What is your TestCafe test code?

```
fixture`Testing HTTP responses`
  .page('https://en.wikipedia.org');


test('Check responseText', async (t) => {
  const response = await t.request({url: '/wiki/Main_Page', method: 'get'});
  await t.expect(response.status).eql(200);
  await t.expect(response.statusText).eql('OK');
});
```

### Your complete configuration file

N/A

### Your complete test report

```$ testcafe "chrome:headless" test-response-text.js
 Running tests in:
 - Chrome 114.0.5735.133 / Ubuntu 20.04

 Testing HTTP responses
 ✖ Check responseText

   1) AssertionError: expected undefined to deeply equal 'OK'
      
      + expected - actual
      
      -undefined
      +OK
      

      Browser: Chrome 114.0.5735.133 / Ubuntu 20.04

          6 |
          7 |
          8 |test('Check responseText', async (t) => {
          9 |  const response = await t.request({url: '/wiki/Main_Page', method: 'get'});
         10 |  await t.expect(response.status).eql(200);
       > 11 |  await t.expect(response.statusText).eql('OK');
         12 |});
         13 |
         14 |

         at <anonymous> (test-response-text.js:11:39)
         at asyncGeneratorStep (test-response-text.js:1:37)
         at _next (test-response-text.js:1:37)



 1/1 failed (3s)
```

### Screenshots

N/A

### Steps to Reproduce

N/A

### TestCafe version

3.0.0

### Node.js version

18.16.0

### Command-line arguments

testcafe "chrome:headless" test-response-text.js

### Browser name(s) and version(s)

Chrome 114.0.5735.133

### Platform(s) and version(s)

Ubuntu 20.04

**Comment by miherlosev** [comment]
Hi @rafal-k,

I researched the described behavior and concluded that it is correct.
The [https://en.wikipedia.org/wiki/Main_Page](https://en.wikipedia.org/wiki/Main_Page) page is served via the HTTP/2 protocol.
![](https://github.com/DevExpress/testcafe/assets/4133518/b1d71766-ff12-4f13-9b8c-8bf0fb2a9b19)
[response.statusMessage](https://nodejs.org/api/http2.html#responsestatusmessage) doesn't exist when using HTTP/2.
[response.statusText](https://testcafe.io/documentation/403981/reference/test-api/testcontroller/request#return-value) is an alias for `response.statusMessage`. So, it is expected to be `undefined`.
The `OK` value for the `statusText` property calculated in the previous versions of TestCafe is incorrect.
