### ISSUE TITLE
Define mask when make screenshot

### ISSUE THREAD

**Issue by mokone91** [DevExpress/testcafe#7845]
### What is your Scenario?

Hi! i want to compare page screenshots during test scenarios, the compare logic is wery custom but the only what i need - its to pass some html selectors to 'takeScreenshot' or 'takeElementScreenshot', this allow to hide some dynamic/sensitive data by  passing some classe/id/etc

### What are you suggesting?

allow to pass array of selectors to hide some data

**Comment by Dmitry-Ostashev** [comment]
Hello,

Thank you for your suggestion. We will consider it after we collect enough user votes.

As a workaround, you can hide some elements using ClientFunction. Refer to the following StackOverflow thread to learn how to do this: https://stackoverflow.com/a/72811378/10684943.

**Comment by AlexKamaev** [comment]
We discussed this issue with the team and decided to close it since it is not popular among users. We recommend that you use the workaround described above to hide some specific elements.
