### ISSUE TITLE
visibilityCheck is ignored for wait for a selector to appear

### ISSUE THREAD

**Issue by vasilyevi** [DevExpress/testcafe#7848]
### What is your Scenario?

Trying to use the following snippet https://github.com/hdorgeval/testcafe-snippets/blob/master/README.md#tc-wait-for-a-selector-to-appear.

### What is the Current behavior?

Tests passed if element is hidden

### What is the Expected behavior?

Tests have to be failed if element is hidden

### What is your public website URL? (or attach your complete example)

https://devexpress.github.io/testcafe/example/

### What is your TestCafe test code?

  await t.expect(Selector("#testcafe-rank").with({visibilityCheck: true}).exists).ok("", {timeout: 5000});

### Steps to Reproduce

run the except

### TestCafe version

3.0.1

### Node.js version

v16.19.0

### Command-line arguments

npx testcafe chrome

**Comment by Aleksey28** [comment]
Hi @vasilyevi,

[`visibilityCheck`](https://testcafe.io/documentation/402743/reference/test-api/selector/with?search#optionsvisibilitycheck) only means that you cannot interact with this selector. It doesn't affect properties like `count` or `exists`. Use [`filterVisible`](https://testcafe.io/documentation/402751/reference/test-api/selector/filtervisible) for this goal.
