### ISSUE TITLE
Regression on basic http authentication

### ISSUE THREAD

**Issue by Arthy000** [DevExpress/testcafe#7852]
### What is your Scenario?

Using [test.httpAuth](https://testcafe.io/documentation/402735/reference/test-api/test/httpauth) doesn't work anymore.

### What is the Current behavior?

No header is added to the requests triggered by the actions of the test. As the feature relies on that header, it doesn't work and I get a 401 response.

### What is the Expected behavior?

A http header is added to requests triggered during the test. The success page is displayed.

### What is your public website URL? (or attach your complete example)

A good place to check basic http authentication:
https://authenticationtest.com/

### What is your TestCafe test code?

```ts
import { Selector } from "testcafe"; // first import testcafe selectors

fixture`Testing stuff` 
  .page`https://authenticationtest.com/`;

test("Basic http auth", async (t) => {
  const linkSelector = Selector(
    "div.row:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > a:nth-child(3)"
  );
  const titleSelector = Selector("div.container h1");

  await t
    .click(linkSelector)
    .expect(titleSelector.innerText)
    .eql("Login Success");
}).httpAuth({ username: "user", password: "pass" });

```

### Steps to Reproduce

1. Use httpAuth method with valid credentials
2. Start the test

### TestCafe version

3 and above

### Command-line arguments

testcafe chrome ./tests/*

### Browser name(s) and version(s)

Chrome 114

### Platform(s) and version(s)

Ventura 13

### Other

The exact same test works just fine with TC version 2.5.0 so this is definitely a regression.

**Comment by AlexKamaev** [comment]
Please use the `--disable-native-automation` flag until the issue is fixed.
