### ISSUE TITLE
Width and Height of a selector is not correct in Testcafe Browser for SVG

### ISSUE THREAD

**Issue by sdontul** [DevExpress/testcafe#7854]
### What is your Scenario?

I have an scenario where I was trying to do drag and drop. there the target element is coming with extra height

The original :
<svg x="580.2106169931955" y="292.1047895950575" width="169.28390222313547" height="263.6856312148274"

### What is the Current behavior?

The Testcafe generated:
<svg x="580.4716981132076" y="-1995" width="168.39622641509433" height="7125"

### What is the Expected behavior?

The svg element Height and Y co-ordinate values should be proper and close to the original values

### What is your public website URL? (or attach your complete example)

Can't share my application url

### What is your TestCafe test code?

no issues with code, only issues with testcafe DOM width and height of a svg element after switching to new window

### Steps to Reproduce

1.As I was not able to share application url not providing any steps
2.
3.

### TestCafe version

3.0.0

### Node.js version

v10.24.0

### Command-line arguments

npx testcafe filename.js

### Platform(s) and version(s)

windows

**Comment by Aleksey28** [comment]
Hi @sdontul,

First of all, TestCafe doesn't support NodeJS lower than v16. Please update your NodeJS to, at least, v16.
I didn't manage to reproduce the issue in NodeJS v16.19.0 and TestCafe v3.0.1.
I'll close this issue. If updating to NodeJS v16 doesn't help you, feel free to write again and describe how you try to get these attributes with TestCafe.

**Comment by sdontul** [comment]
Installed latest NodeJS v20.4.0 and TestCafe v3.0.1 still same issues. Please help

**Comment by Dmitry-Ostashev** [comment]
I didn't manage to reproduce the issue with a simple SVG element. We are currently unable to determine what is causing the issue. Please share a more detailed description and prepare a sample web page using which we can reproduce the issue.
