### ISSUE TITLE
I am getting error "The element is expected to be an <iframe>"

### ISSUE THREAD

**Issue by Mayur0619** [DevExpress/testcafe#7857]
### What is your Scenario?

I am getting error "The element is expected to be an <iframe>" while using t.switchtoIframe(Selelctor('frame[name='f4']'));

HTML - 
```
<html>
<head></head>
<frameset>
     <frame name='f1'></frame>
     <frameset>
            <frame name='f2'></frame>
            <frame name='f3'></frame>
            <frame name='f4'></frame>
      </frameset>
      <frame name='f5'></frame>
</frameset>
</html>
```

### What is the Current behavior?

I am getting error "The element is expected to be an <iframe>" while using t.switchtoIframe(Selelctor('frame[name='f4']'));

### What is the Expected behavior?

It should switch to frame f4

### What is your public website URL? (or attach your complete example)

I am getting error "The element is expected to be an <iframe>" while using t.switchtoIframe(Selelctor('frame[name='f4']'));

### What is your TestCafe test code?

I am getting error "The element is expected to be an <iframe>" while using t.switchtoIframe(Selelctor('frame[name='f4']'));

HTML - 
<html>
<head></head>
<frameset>
     <frame name='f1'></frame>
     <frameset>
            <frame name='f2'></frame>
            <frame name='f3'></frame>
            <frame name='f4'></frame>
      </frameset>
      <frame name='f5'></frame>
</frameset>
</html>

### Steps to Reproduce

1.I am getting error "The element is expected to be an <iframe>" while using t.switchtoIframe(Selelctor('frame[name='f4']'));

HTML - 
<html>
<head></head>
<frameset>
     <frame name='f1'></frame>
     <frameset>
            <frame name='f2'></frame>
            <frame name='f3'></frame>
            <frame name='f4'></frame>
      </frameset>
      <frame name='f5'></frame>
</frameset>
</html>
2.
3.

### TestCafe version

1.13.0

### Node.js version

v16.17.0

### Command-line arguments

npm start

**Comment by Aleksey28** [comment]
Hi @Mayur0619,

I see that you try to switch to an element with the `frame` tag, but the [`switchToIframe`](https://testcafe.io/documentation/402681/reference/test-api/testcontroller/switchtoiframe) method is used only for elements with the `iframe` tag.

Also, I see that you use 1.13.0. Please update TestCafe to the latest version.

**Comment by Mayur0619** [comment]
Then what should be used instead of switchToIframe()

**Comment by Aleksey28** [comment]
The only way is to replace your `frame` with `iframe`. A duplicate of [https://github.com/DevExpress/testcafe/issues/1565](https://github.com/DevExpress/testcafe/issues/1565).

Updating won't resolve the issue. However, later versions are more stable in working with `iframe`.
