### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'parent')

### ISSUE THREAD

**Issue by gemal** [DevExpress/testcafe#7860]
### What is your Scenario?

I have a window that is generated by a ajax call and I keep getting the same problem with hammerhead.js

![image](https://github.com/DevExpress/testcafe/assets/69105/0333ed34-dd5a-4e2c-ba11-742e3dfc9b00)

![image](https://github.com/DevExpress/testcafe/assets/69105/04a5a0ef-7bdd-4b5e-8b05-ac5fc1ce1319)

on testcafe 3.0.1

### What is the Current behavior?

test failure

### What is the Expected behavior?

test success

### What is your public website URL? (or attach your complete example)

test it not public

### What is your TestCafe test code?

test is not public

### Steps to Reproduce

1. generate a window using ajax
2.
3.

### TestCafe version

3.0.1

### Node.js version

18.16.0

### Command-line arguments

testcafe chrome

### Browser name(s) and version(s)

chrome 114

### Platform(s) and version(s)

windows 10

**Comment by Aleksey28** [comment]
Hi @gemal,

TestCafe [v3.0.0](https://testcafe.io/404438/release-notes/framework/2023-6-21-introducing-testcafe-v-3-0-0#native-automation) works with a faster and more stable `Native Automation` mode by default. We are actively working on this mode, but, currently, it doesn't support multiple windows. You can track updates about supporting the multiple windows in Native Automation mode in this issue: [https://github.com/DevExpress/testcafe/issues/7661](https://github.com/DevExpress/testcafe/issues/7661)

As a workaround, I recommend you separate your TestCafe tasks into two:

* Use Native Automation for general purposes.
* Do not use Native Automation for specific tests that use multiple windows.
