### ISSUE TITLE
Nested iframe selection using .switchToIFrame hangs on 3.0.0

### ISSUE THREAD

**Issue by MK-97** [DevExpress/testcafe#7861]
### What is your Scenario?

> const innerIframe = Selector('#inner_Iframe')
>
>await t.switchToIframe('#parent_Iframe')
>              .switchToIframe(innerIframe)
>              .typeText('#input_inside_inner_iframe', 'text')

In previous versions 2.6.1 and below, I was able to select a nested iframe, and do something like the above. This no longer works

### What is the Current behavior?

> const innerIframe = Selector('#inner_Iframe')
>
>await t.switchToIframe('#parent_Iframe')
>              .switchToIframe(innerIframe)
>              .typeText('#input_inside_inner_iframe', 'text')

Test hangs at the second switchToIframe indefinitely

### What is the Expected behavior?

I expect to be able to switch to nested iframes

### What is your public website URL? (or attach your complete example)

n/a

### What is your TestCafe test code?

n/a

### Steps to Reproduce

1. Have an iframe nested within an iframe
2. Switch from parent iframe to child iframe
3. Test hangs

### TestCafe version

3.0.0

### Command-line arguments

testcafe chrome --disable-multiple-windows

**Comment by Christopher-C-Robinson** [comment]
I also am having issues with switching to a nested iframe. I’m trying to switch to an iframe that is within another iframe.
