### ISSUE TITLE
Some obfuscation is not able to be parsed correctly and throws errors

### ISSUE THREAD

**Issue by Ghxst** [DevExpress/testcafe#7862]
### What is your Scenario?

We're encountering some pages that contain some obfuscation that is not being parsed correctly.

### What is the Current behavior?

![image](https://github.com/DevExpress/testcafe-hammerhead/assets/45855847/1de95f3a-21c6-4978-a1b3-96b98a6299ff)
Hammerhead.js attempts to parse the JS but encounters uncaught errors.

Script in question:
- https://gist.github.com/Ghxst/b835e90b2f966e5ce5d1d937acb42370

Public url:
- https://www.expedia.ca/ga6zxEs5QN8r/p9BxDw/p50xPF/hO1amGm6ta/QysCRnJjBw/fCE9RXNm/STc

### What is the Expected behavior?

Ideally to parse without errors.

### What is your public website URL? (or attach your complete example)

- https://www.expedia.ca/login (**no authentication required**, simply visit the page)
- https://www.expedia.ca/ga6zxEs5QN8r/p9BxDw/p50xPF/hO1amGm6ta/QysCRnJjBw/fCE9RXNm/STc (raw script / js)

### What is your TestCafe test code?

I'm using `node node_modules/gulp/bin/gulp multi-window-http-playground `

### Steps to Reproduce

1. run `node node_modules/gulp/bin/gulp multi-window-http-playground `
2. proxy `https://www.expedia.ca/login` 

### TestCafe version

n/a

### Command-line arguments

n/a

### Browser name(s) and version(s)

Chrome 114

### Platform(s) and version(s)

Windows, Linux Ubuntu

**Comment by AlexKamaev** [comment]
I've researched the issue and found out that there is no error in the latest TestCafe version in the Chrome browser. Starting from v3.0, TestCafe has a [Native Automation](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode) mode enabled by default. Please try to run your tests in the latest TestCafe version. I'll close the issue for now. If you have any further questions, feel free to ask here.
