### ISSUE TITLE
Ability to get screenshot path during test execution specified as pathPattern in settings

### ISSUE THREAD

**Issue by vasilyevi** [DevExpress/testcafe#7864]
### What is your Scenario?

Trying to integrate autotests with 3rd party service(test reporting solution) and need to upload screenshot. Need to get an exact screenshot path in the end of each test. The pathPattern is the following `"${DATE}_${TIME}/${TEST}/${FILE_INDEX}_${QUARANTINE_ATTEMPT}.png"`

### What are you suggesting?

get from t?

### What alternatives have you considered?

didn't find a good solution

**Comment by htho** [comment]
I have a collection of undocumented TestCafe "functions".

```TypeScript
// testcafe-undocumented.ts

export const screenshotPath = (t: TestController): string => (t as any).testRun.opts.screenshots.path;
```

Although they are undocumented and can change anytime - this did not change since TestCafe 1.x.

**Comment by Dmitry-Ostashev** [comment]
@vasilyevi You can implement your own Reporter or wrap an existing one. The reporter plugin contains the [reportTestDone](https://testcafe.io/documentation/402790/reference/plugin-api/reporter#reporttestdone) method with the [testRunInfo](https://testcafe.io/documentation/402790/reference/plugin-api/reporter#testruninfo-object) object argument. This object contains all captured screenshot paths.

**Comment by AlexKamaev** [comment]
You cannot access this object from the test using `t` testController. However, you can pass any information from the test (from `t` testController) to a custom reporter using the [t.report](https://testcafe.io/documentation/404350/reference/test-api/testcontroller/report) action. Then, you can process this passed information in your custom reporter

**Comment by AlexKamaev** [comment]
Alternatively, you can get your screenshot paths in reporter hook methods: [https://testcafe.io/documentation/404388/guides/advanced-guides/modify-reporter-output](https://testcafe.io/documentation/404388/guides/advanced-guides/modify-reporter-output).

Here is a basic example for screenshots:
```JS
function onBeforeWriteHook(writeInfo) {
    if (writeInfo.initiator === 'reportTestDone')
        writeInfo.formattedText += JSON.stringify(writeInfo.data.testRunInfo.screenshots.map(s => s.screenshotPath));
}

 module.exports = {
    hooks: {
        reporter: {
            onBeforeWrite: {
                'spec': onBeforeWriteHook,
            },
        },
    },
};
```
However, I still believe that you need to write your custom reporter to pass screenshots to your third-party service.
