### ISSUE TITLE
Cookie/LocalStorage set in global test hook 'before' is not found in test

### ISSUE THREAD

**Issue by BehaminBakhshaie** [DevExpress/testcafe#7874]
### What is your Scenario?

In testcafe I want to set a cookie when testcafe runs which the tested website can use as condition to do something e.g. hide some dialogs (cookie consent) to make tests more simple.

In my configuration file .testcaferc.cjs i set a global test before hook.

```
test: {
      before: async (t) => {
        // global before test goes here
        await t.setCookies({ testCafeRun: 'true' }, baseUrl);
        const cookies1 = await t.getCookies('testCafeRun');
        console.log(cookies1);
      },
      after: async (t) => {
        // global after test goes here
      },
    },
```

but what i find strange is that the cookie is not present in my tests:

```
fixture('Language test')
  .page('./')
  .beforeEach(async (t) => {
    await t.useRole(userRole);
  });
    
    test('test 1', async (t) => {
      const cookies2 = await t.getCookies('testCafeRun');
      console.log(cookies2);
    });
```

Following is probably relevant:
nativeAutomation: false,
Testcafe version 3.0.0
Stackoverflow: https://stackoverflow.com/questions/76653104/testcafe-cookie-set-in-global-test-hook-before-is-not-found-in-test/76661567#76661567

### What is the Current behavior?

The cookie is found within the hook but not found in the test. cookies1 has value, cookies2 is null. Is this a bug or am i missing something? I get same experience when I use local storage. If I however save cookie/localstorage in beforeEach then it will work. 

### What is the Expected behavior?

I was expecting to see the cookie or localstorage in my test since the global test before has access to browser/testcontroller. 

### What is your public website URL? (or attach your complete example)

Not public - I believe the code provided is sufficient. 

### What is your TestCafe test code?

```
import { premiumUserRole } from '../constants/users.const';
import fieldPlanPage from '../pages/fieldplan.page';
import { goToAppPage } from '../utils/goToAppPage.fn';

// Activate role before each test.
fixture('Language test')
  .page('./')
  .beforeEach(async (t) => {
    await t.useRole(premiumUserRole); // activate role
    await goToAppPage(`./`);
  });


test('Default language is DK', async (t) => {
  const cookies2 = await t.getCookies('testCafeRun');
  console.log(cookies2);
  await t.expect(fieldPlanPage.fieldPlanBtn.innerText).contains('Markplan');
});

test('Language changing to EN', async (t) => {
  await t.click(fieldPlanPage.e2eUserInfoToggle).click(fieldPlanPage.e2eLanguagePicker).click(fieldPlanPage.e2eLanguageEN);
  await t.expect(fieldPlanPage.fieldPlanBtn.innerText).contains('Field Plan');
});
```

```
import { Selector, t } from 'testcafe';

export async function goToAppPage(url: string) {
  await t.navigateTo(url);

  const cmLoginButton = Selector('#e2e-logOnCm', { timeout: 5000 });

  if ((await cmLoginButton.exists) && (await cmLoginButton.visible)) {
    await t.click(cmLoginButton);
  }
}
```

### Your complete configuration file

```
const baseUrl = process.env.WEBAPP_URL || 'https://localhost.vfltest.dk:8080/'; // baseUrl is changed from github hosted runner

module.exports = {
  src: ['./e2e/testcafe/tests/*.cafe.ts', './e2e/testcafe/tests/cultivation-journal/*.cafe.ts'],
  browsers: ['chrome:headless:emulation:width=1920;height=1080'],
  concurrency: 3,
  baseUrl: baseUrl,
  selectorTimeout: 20000,
  pageLoadTimeout: 5000,
  compilerOptions: {
    typescript: {
      configPath: '../ClientApp/e2e/testcafe/tsconfig.cafe.json',
    },
  },
  reporter: [
    { name: 'spec' },
    {
      name: 'xunit',
      output: 'e2e/testcafe/reports/report.xml',
    },
  ],
  screenshots: {
    takeOnFails: true,
    fullPage: true,
    path: 'e2e/testcafe/reports/',
    pathPattern: '${DATE}_${TIME}_${TEST_INDEX}_${TEST_ID}_${QUARANTINE_ATTEMPT}.png',
    thumbnails: false,
  },
  videoPath: 'e2e/testcafe/reports/',
  videoOptions: {
    failedOnly: true,
    pathPattern: '${DATE}_${TIME}_${TEST_INDEX}_${TEST_ID}_${QUARANTINE_ATTEMPT}.mp4',
  },
  disablePageCaching: false,
  skipJsErrors: false,
  quarantineMode: {
    successThreshold: 1,
    attemptLimit: 3,
  },
  nativeAutomation: false,
  stopOnFirstFail: true,

  hooks: {
    test: {
      before: async (t) => {
        // global before test goes here
        await t.setCookies({ testCafeRun: 'true' }, baseUrl);
        const cookies1 = await t.getCookies('testCafeRun');
        console.log(cookies1);
      },
      after: async (t) => {
        // global after test goes here
      },
    },
  },
};
```

### Steps to Reproduce

1. Copy the configuration file
2. Copy the test file
3. Run the code
4. Check that the console.log of cookies1 has value
5. Check that the console.log of cookies2 is null
6. Expected: cookie2 is the same as cookies1. 

### TestCafe version

3.0.0

### Node.js version

v16.20.1

### Command-line arguments

npx testcafe

### Browser name(s) and version(s)

Chrome 114

### Platform(s) and version(s)

Windows and Ubunto github hosted runner

### Other

Angular website
https://dev-cropmanager.vfltest.dk/#/

We use feature branches, URL can look like this too:
https://dev-cropmanager.vfltest.dk/CT2-8022-calculate/#/

**Comment by BehaminBakhshaie** [comment]
I noticed there is a new flag for nativeautomation:
disableNativeAutomation: false,

I have not tried the difference in behavior for with and without nativeautomation

**Comment by BehaminBakhshaie** [comment]
@Artem-Babich So I have confirmed that the bug is not dependant on disableNativeAutomation. It is however dependant on useRole(). 

This is the most simple example i can come up with:

OK: This will work. cookies2 has value. 
```
fixture('Check if cookie is set in global before test')
  .page('./')
  .beforeEach(async (t) => {
  });

test.only('Check if cookie exists', async (t) => {
  const cookies2 = await t.getCookies('testCafeRun');
  console.log('cookies2', cookies2);

  await t.expect(true).ok();
});
```

Bug: When using roles. cookies2 will be null. 
```
import { premiumUserRole } from '../constants/users.const';
fixture('Check if cookie is set in global before test')
  .page('./')
  .beforeEach(async (t) => {
    await t.useRole(premiumUserRole); // activate role
  });

test.only('Check if cookie exists', async (t) => {
  const cookies2 = await t.getCookies('testCafeRun');
  console.log('cookies2', cookies2);

  await t.expect(true).ok();
});
```

Same results no matter disableNativeAutomation: true or disableNativeAutomation: false.
Let me know if I can assist in any other way.

**Comment by Aleksey28** [comment]
Hi @BehaminBakhshaie,

We checked the reported issue. The issue doesn't occur with `disableNativeAutomation: true`. Please take a look at my example:

```js
//.testcaferc.js
module.exports = {
  browsers: 'chrome',
  hooks: {
    test: {
      before: async (t) => {
        // global before test goes here
        await t.setCookies({ testCafeRun: 'true' });
        const cookies = await t.getCookies('testCafeRun');
        console.log(cookies);
      },
      after: async (t) => {
        // global after test goes here
      },
    },
  }
}
```
```js
//test.js
import { Role } from "testcafe";

const registeredUser = Role('https://devexpress.github.io/testcafe/example/', async t => { });

fixture('Language test')
  .page('https://devexpress.github.io/testcafe/example/')
  .beforeEach(async (t) => {
    await t.useRole(registeredUser);
  });

test('test 1', async (t) => {
  const cookies = await t.getCookies('testCafeRun');
  console.log(cookies);
});
```
If I run it with the `testcafe chrome test.js --disable-native-automation`command, it will work as expected.

**Comment by BehaminBakhshaie** [comment]
@Aleksey28 

I tried your code and you are right, it works. It does however not work for me. I pinpointed the issue to the way we use roles.
You set roles on the url that is testet: `const registeredUser = Role('https://devexpress.github.io/testcafe/example/', async t => { });`

I set role on a login flow that directs to a 3rd party website (which we also own) that sets a authentication cookie on client browser.

Try it out. should work with your configuration file. 

run it with: testcafe chrome

I have created a working example of the bug:

```
import { Role, Selector } from 'testcafe';

export const premiumUserRole = Role(`https://dev-cropmanager.vfltest.dk/e2e-vra-downloads/#/`, async (t) => {
  await t.click(Selector('#e2e-logOnCm'));

  // Wait for the new page to load
  await t.expect(Selector('#submitButton').exists).ok();
  await t.expect(Selector('#submitButton').visible).ok();

  await t.typeText(Selector('#userNameInput'), 'PublicUser');
  await t.typeText(Selector('#passwordInput'), 'WeLoveTestCafe');

  await t.click(Selector('#submitButton'));

  await t.expect(true).ok();
});

fixture('Check if cookie is set in global before test')
  .page('./')
  .beforeEach(async (t) => {
    await t.useRole(premiumUserRole); // activate role
  });

test.only('Check if cookie exists', async (t) => {
  const cookies2 = await t.getCookies('testCafeRun');
  console.log('cookies2', cookies2);

  await t.expect(true).ok();
});
```

**Comment by BehaminBakhshaie** [comment]
It gets worse for us because with disableNativeAutomation: true, testcafe hangs in github hosted runner (ubuntu). It is a different issue though. 

```
import { Selector } from 'testcafe';

// Activate role before each test.
fixture('Native Automation Bug Test').page('https://dev-cropmanager.vfltest.dk/e2e-vra-downloads/#/');

test.only('Will fail at click #submitButton', async (t) => {
  await t.click(Selector('#e2e-logOnCm'));

  // Wait for the new page to load
  await t.expect(Selector('#submitButton').exists).ok();
  await t.expect(Selector('#submitButton').visible).ok();

  await t.typeText(Selector('#userNameInput'), 'PublicUser');
  await t.typeText(Selector('#passwordInput'), 'WeLoveTestCafe');

  console.log('aa');
  await t.click(Selector('#submitButton')); // Fails
  console.log('bb'); // runner never reaches here

  await t.expect(true).ok();
});

```

**Comment by Artem-Babich** [comment]
Hi @BehaminBakhshaie,

Thank you for the code example. I was able to reproduce the issue with cookies in both modes (native automation and hammerhead). We will research it. To speed up this process, you can create a sample project that illustrates your cookie authorization mechanism so that we can debug this app on our side.

Regarding the second issue - please create a separate GitHub issue using the following template: [Bug Report](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&template=bug_report.yaml) and share as many details as possible. Please also clarify if the issue occurs only in the CI environment or locally as well. If it occurs only in the CI environment, share details about your CI.

**Comment by BehaminBakhshaie** [comment]
@Artem-Babich  I created following bug as well. might be related: https://github.com/DevExpress/testcafe/issues/7884

**Comment by Artem-Babich** [comment]
Hi @BehaminBakhshaie,

After additional research, we found out that the cookies were not cleared due to a bug with reloading. After this fix. the roles will work the same way as in native automation. The `useRole` method call clears cookies and applies those cookies that were set during the first role execution. You can set additional cookies after applying the role or in the role's initialization code.
