### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'prepareInjectableUserScripts')

### ISSUE THREAD

**Issue by andrzej-woof** [DevExpress/testcafe#7881]
### What is your Scenario?

I have few request mocks and hooks set up, running in parallel with quarantine mode on github actions. Same issue doesn't seem to happen locally on MacOS Ventura 13

### What is the Current behavior?

Tests randomly fail with 

```
      1) Unhandled promise rejection:

         TypeError: Cannot read properties of undefined (reading 'prepareInjectableUserScripts')
         at NativeAutomationRequestPipeline._getUserScripts (/home/runner/work/clear-frontend/clear-frontend/clear-frontend/e2e-tests/node_modules/testcafe/lib/native-automation/request-pipeline/index.js:107:31)
         at NativeAutomationRequestPipeline._respondToOtherRequest (/home/runner/work/clear-frontend/clear-frontend/clear-frontend/e2e-tests/node_modules/testcafe/lib/native-automation/request-pipeline/index.js:137:44)
         at runMicrotasks (<anonymous>:null:null)
         at processTicksAndRejections (node:internal/process/task_queues:96:5)
         at NativeAutomationRequestPipeline._tryRespondToOtherRequest (/home/runner/work/clear-frontend/clear-frontend/clear-frontend/e2e-tests/node_modules/testcafe/lib/native-automation/request-pipeline/index.js:191:17)
         at NativeAutomationRequestPipeline._handleOtherRequests (/home/runner/work/clear-frontend/clear-frontend/clear-frontend/e2e-tests/node_modules/testcafe/lib/native-automation/request-pipeline/index.js:221:13)
         at Chrome.<anonymous> (/home/runner/work/clear-frontend/clear-frontend/clear-frontend/e2e-tests/node_modules/testcafe/lib/native-automation/request-pipeline/index.js:284:17)

         Browser: Chrome 114.0.5735.198 / Ubuntu 22.04
``` 

### What is the Expected behavior?

Not failing

### What is your public website URL? (or attach your complete example)

private url

### What is your TestCafe test code?

unfortunately cannot share

### Steps to Reproduce

1.
2.
3.

### TestCafe version

3.0.1

### Command-line arguments

running with API

### Browser name(s) and version(s)

Chrome 114.0.5735.198 Headless

### Platform(s) and version(s)

Ubuntu 22.04

### Other

I've caught one event that seems to cause this 

```
{
  requestId: 'interception-job-158.1',
  request: {
    url: 'http://app.local:8090/redirect/',
    urlFragment: '#state=http%3A%2F%2Fapp.local%3A8090%2Fredirect&access_token=3afdfcdd-6b4a-4994-9937-90539b0acc21&token_type=Bearer&expires_in=3599&scope=https://www.googleapis.com/auth/analytics.readonly%20https://www.googleapis.com/auth/analytics.edit',
    method: 'GET',
    headers: {
      Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
      Referer: 'http://app.local:8090/',
      'Upgrade-Insecure-Requests': '1',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/114.0.5735.198 Safari/537.36',
      'sec-ch-ua': '"Not.A/Brand";v="8", "Chromium";v="114", "HeadlessChrome";v="114"',
      'sec-ch-ua-mobile': '?0',
      'sec-ch-ua-platform': '"macOS"'
    },
    initialPriority: 'VeryHigh',
    referrerPolicy: 'strict-origin-when-cross-origin'
  },
  frameId: 'D944F3FEBC73DDD7E8B530F5C5D08F50',
  resourceType: 'Document',
  responseStatusCode: 200,
  responseStatusText: 'OK',
  responseHeaders: [
    { name: 'X-Powered-By', value: 'Express' },
    { name: 'Accept-Ranges', value: 'bytes' },
    { name: 'Date', value: 'Fri, 14 Jul 2023 15:15:00 GMT' },
    { name: 'Content-Type', value: 'text/html; charset=utf-8' },
    { name: 'Content-Length', value: '796' },
    { name: 'ETag', value: 'W/"31c-AK0TsXQep3YI3+x2bnyajQafgY8"' },
    { name: 'Vary', value: 'Accept-Encoding' }
  ],
  networkId: '7CDA9987C0883206023C208FB374E6F4',
  redirectedRequestId: 'interception-job-158.0'
}
```

Note the `#` in url (`urlFragment`). That turned out to be problematic for some reason when I've upgraded to `testcafe@3`, previously I've had a mock that returned `302` with location header `http://app.local:8090/redirect#something` and it worked fine with `testcafe@2`, after upgrade it was stuck after this redirect showing whitepage, so I've changed location to `http://app.local:8090/redirect/#something` (added slash) and test continued, but maybe there's still some underlying issue with urls containing `#`

And it does seem in this particular case `this._pipelineContexts` had a context for that `requestId` but it got disposed somewhere before throwing this error

**Comment by andrzej-woof** [comment]
Sorry, but I'm unable to isolate minimal working example as it doesn't seem to fail when I try to simulate similar conditions

**Comment by Aleksey28** [comment]
I'd like to help you but it is hardly possible without a simple example. Feel free to reopen the issue once you manage to create it.

As a temporary solution, you can run this test with option [`--disable-native-automation`](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode#configuration-file).
