### ISSUE TITLE
Native Automation Documentation: Collect Differences/Oddities When Switching to Native Automation

### ISSUE THREAD

**Issue by htho** [DevExpress/testcafe#7892]
### What is your Scenario?

I have big collection of e2e tests, some fail since I updated to v3.

A Test failed because a click on an element revealed another element. That element was immediately hovered. It was not expected to be hovered. (see my repo: https://github.com/htho/testcafe-repro-click-hover)

I searched the changelog for anything click-related but did not find anything.

### What are you suggesting?

A collection of differences and oddities that may happen when switching to native automation.

The current documentation is very generic: https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode#q-do-i-need-to-change-my-tests-to-run-testcafe-3x

An extra section/page with concrete cases like mine would help.

**Comment by Aleksey28** [comment]
Hi @htho,

I checked your example. When I run the `npm run test-dna` command, I do not get any errors. When I run `npm run test-na`, I get an error:
![](https://github.com/DevExpress/testcafe/assets/32869530/806d14ec-9be4-4733-848a-7dedb1603050)
If I understand it correctly, you meant that there should be `.ok()` in the 16th row. If this is the case, yes, there is a bug when the Native Automation mode is not used. Please create a separate issue for this bug and separate issues in the case of other bugs and illustrate them with simple examples.

>An extra section/page with concrete cases like mine would help.

We have a section with the [limitations](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode#q-what-are-the-limitations-of-native-automation). It makes no sense to create a section for such bugs. You can find all known bugs in this repo.
