### ISSUE TITLE
useRole is not working

### ISSUE THREAD

**Issue by SantiagoGalicia** [DevExpress/testcafe#7906]
### What is your Scenario?

i tried to run multiple scenarios using the useRole feature 

i want that each escenario make a login

### What is the Current behavior?

the current behavior is that only the first useRole works the next dont login

### What is the Expected behavior?

all the useRole should be executed

### What is your public website URL? (or attach your complete example)

inhouse url

### What is your TestCafe test code?

when i run my scenarios only the first useRole works

import { userAdmin } from "../../Commons/roles";
import { ClientFunction, t, Selector } from 'testcafe';
import Urls from "../../Commons/Urls";
const getUrl = ClientFunction(() => window.location.href)
import Utils from "../../Pages/Actions/Utils";
import AllMerchantsLocators from "../../Pages/Locators/AllMerchantsLocators"
import B2bLocators from "../../Pages/Locators/b2b/B2bLocators"
import B2b from "../../Pages/Actions/B2b/B2b";
import Merchants from "../../Commons/Merchants";

fixture `B2b Test`

test
.meta('testID', 'AUTOQA-1555')
.meta({ level1: 'Critical', level2: 'Smoke' })  
('FE | verify change status top account ', async t => {
    await t
    .useRole(userAdmin)    //Enter the right credentials
    .expect(getUrl()).contains(Urls.Customer360.DashboardUrl)
    await Utils.waitandclick(AllMerchantsLocators.images.imgAllmerchants)
    await t
        .click(AllMerchantsLocators.images.imgB2b)
        .click(B2bLocators.button.btnB2b)
        .click(B2bLocators.button.btnStatusChange)
        .typeText(B2bLocators.textBox.txtMeId,Merchants.Search.ME_ID, { replace: true })
        .click(B2bLocators.button.btnNewStatus)
        .click(B2bLocators.button.btnSetStatus)
        .typeText(B2bLocators.textBox.txtAssign,"team QA", { replace: true })
        .typeText(B2bLocators.textBox.txtComments,"Test Qa", { replace: true })
        .click(B2bLocators.button.btnSave)
        .expect(B2bLocators.asserts.lblStatusChange.visible).ok()
    });

test
.meta('testID', 'AUTOQA-1557')
.meta({ level1: 'Critical', level2: 'Smoke' })  
('FE | verify log top accounts', async t => {
    await t
    .useRole(userAdmin)    //this code is not executed
    .expect(getUrl()).contains(Urls.Customer360.DashboardUrl)
    await Utils.waitandclick(AllMerchantsLocators.images.imgAllmerchants)
    await t
        .click(AllMerchantsLocators.images.imgB2b)
        .click(B2bLocators.images.imgLogs)
        .expect(B2bLocators.asserts.lblLogStatus.visible).ok()
       
    });

my role setup

const userAdmin = Role(Urls.Customer360.LoginUrl, async t => {
    await LoginActions.loginForm(Users.ADMINCredentials.USR_ADMIN, Users.ADMINCredentials.PWD_ADMIN) 
    },
    { preserveUrl: true } // keep the post-login page open
    );

when i debug the scenarios the first login works but the next are skipped 

### Your complete configuration file

module.exports = {
    skipJsErrors: true,
    browsers: ['chrome'],
    concurrency: 1,
    attemptLimit: 2,
    pageLoadTimeout: 9000,
    quarantineMode: false,
    reporter: [
        {
            name: "spec"
        },
        {
            name: "html",
            output: 'reports/html/report.html'
        },
        {
            name: 'junit',
            output: 'reports/xml/report.xml'
        },
        {
            name: 'json',
            output: 'reports/json/report.json'
        },
        {
            name: 'allure',
        }
    ],
    screenshots: {
        path: "Screenshots/",
        takeOnFails: true,
        
    }
}

### Steps to Reproduce

1.write the useRole method to login
2.use the useRole method on multiple test
3.run the test and verify if make the login on every test

### TestCafe version

3.1.0

### Command-line arguments

testcafe Tests/B2b/B2bTests.js --skip-js-errors --config-file testCafeConfigs/TestConfigs.js

### Browser name(s) and version(s)

chrome

**Comment by miherlosev** [comment]
Hi @SantiagoGalicia,

Could you please modify the shared sample so that we can reproduce the issue locally without additional setup (see [how to create a minimal working example](https://testcafe.io/documentation/402636/faq/general-info#how-to-create-a-minimal-working-example-when-you-submit-an-issue))?

**Comment by SantiagoGalicia** [comment]
here you have the sample


```
import { userAdmin } from "../../Commons/roles";
import Urls from "../../Commons/Urls";

fixture B2b Test

test
('FE | verify change status top account ', async t => {
await t
.useRole(userAdmin) //Enter the right credentials
.expect(getUrl()).contains(Urls.Customer360.DashboardUrl) //validate the url
});

test
('FE | verify change status top account ', async t => {
await t
.useRole(userAdmin) //Enter the right credentials
.expect(getUrl()).contains(Urls.Customer360.DashboardUrl) //validate the url
});

```

The current behavior is that only the first .useRole is executed
previous version execute the useRole all the times not only on the first test (example "testcafe": "^2.3.0")

**Comment by Artem-Babich** [comment]
Hi,

> only the first .useRole is executed

If I understand it correctly, you mean that the Role code is executed only once.

Each Role executes its code only once per test run. For all subsequent role activations, we use authentication data (cookies, session) from the first Role activation: [How Roles Work](https://testcafe.io/documentation/402845/guides/intermediate-guides/authentication#how-roles-work). This behavior is also applicable to v2.3.0. So, if your Role code was executed more than one time, it was a bug.

Could you please clarify if the second Role use doesn't apply authentication data? If so, please share all code required to reproduce the issue. Your previous example includes references to the following modules:

import from "../../Commons/roles";
import Urls from "../../Commons/Urls";

Also, we still need to see your config file.

**Comment by miherlosev** [comment]
Hi @SantiagoGalicia,

We still don't have a complete example that is possible to download and run without any additional setup (see [How to create a Minimal Working Example when you submit an issue](https://testcafe.io/documentation/402636/faq/general-info#how-to-create-a-minimal-working-example-when-you-submit-an-issue)). Feel free to reopen this issue if you prepare such an example.
