### ISSUE TITLE
Use MacOS on Travis CI

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#791]
We can run functional tests directly on Travis CI MacOS VMs, instead of using SauceLabs.

**Comment by AlexanderMoskovkin** [comment]
awesome!

**Comment by AlexanderMoskovkin** [comment]
is there a way to save a screencast for them?

**Comment by AndreyBelym** [comment]
It's easy enough to grab the screen with [ffmpeg](https://ffmpeg.org), but it will capture the entire screen, not the specific browser window. JFYI, SauceLabs uses it to make screencasts, but SauceLabs provides dedicated VM for each browser, so they don't face the problem with multiple browsers inside the same VM.

**Comment by AndreyBelym** [comment]
Looks like that Travis macOS VM's doesn't have enough performance to run 3 browsers at the same time, so to use it we need to create 3 separate tasks, one for each browser (Firefox, Chrome, Safari). Also keep in mind that total number of macOS VM's is very limited (128 at now), so it will drastically  increase tests time. By these reasons @AlexanderMoskovkin and I decided not to implement this.

**Comment by AlexanderMoskovkin** [comment]
> By these reasons @AlexanderMoskovkin and I decided not to implement this.
