### ISSUE TITLE
Cannot resize window on Ubuntu

### ISSUE THREAD

**Issue by Madalinagabriela** [DevExpress/testcafe#7912]
### What is your Scenario?

Resize/maximize a window

### What is the Current behavior?

Testcafe cannot resize/maximize the window

### What is the Expected behavior?

Should resize/maximize window

### What is your public website URL? (or attach your complete example)

See attached file with the project [testcafe-resize-window.zip](https://github.com/DevExpress/testcafe/files/12227156/testcafe-resize-window.zip)

### What is your TestCafe test code?

```js
fixture `Test resize window`;


test('Test resize window', async t => {
    await t.navigateTo(`https://devexpress.github.io/testcafe/example/`);
    await t.maximizeWindow(); // doesn't work
    await t.resizeWindow(400, 700); // doesn't work
    await t.resizeWindowToFitDevice('iphone'); // doesn't work
});
```

### Steps to Reproduce

1. npm install
2. testcafe chrome tests

### TestCafe version

Repeoducing using TestCade 2.6.1, 2.6.2, 3.0.0

### Node.js version

v16.14.2

### Command-line arguments

testcafe chrome

### Browser name(s) and version(s)

Chrome Version 115.0.5790.98 (Official Build) (64-bit)

### Platform(s) and version(s)

Ubuntu 18.04.2 LTS

**Comment by Aleksey28** [comment]
Hi @Madalinagabriela,

I didn't manage to reproduce the issue with the following configuration:
platform: Ubuntu 22.04
node: 16.16.0
chrome: 115.0.5790.110
testcafe: 2.6.2, 3.0.0, 3.1.0

It's an issue related to an old Ubuntu version. Please update your OS version and check it again.
