### ISSUE TITLE
--lang flag doesn't override browser preferred language

### ISSUE THREAD

**Issue by OlgaNel** [DevExpress/testcafe#7913]
### What is your Scenario?

I would like to run a browser with a specific language (en_US).

### What is the Current behavior?

Browser is run with English (United Kingdom) selected language

### What is the Expected behavior?

The browser has  English (United States) selected language

### What is your public website URL? (or attach your complete example)

-

### What is your TestCafe test code?

-

### Your complete configuration file

```
const gitlabReporter = require('./tests/e2e/reporters/gitlab');
const path = require('path');

const browser = process.env.CI
  ? 'chrome:headless'
  : 'chrome';

module.exports = {
  browsers: [
    `${browser} --lang=en_US --autoplay-policy=no-user-gesture-required --disable-dev-shm-usage`
  ],
  src: [
    'tests/e2e/**/*.feature',
    //'tests/**/FilterContacts.feature',
    'tests/e2e/**/*.ts',
  ],
  screenshots: {
    takeOnFails: true,
    pathPattern: '/${FIXTURE} - ${TEST}/${RUN_ID}/${FILE_INDEX}.png'
  },
  reporter: [
    {
      name: 'gtc-reporter-spec'
      // name: 'spec'

    },
    {
      name: gitlabReporter,
      output: './reports/e2e_report.xml'
    }
  ],
  disablePageCaching: true,
  compilerOptions: {
    typescript: {
      customCompilerModulePath: require.resolve('typescript'),
      configPath: 'tsconfig.json'
    }
  }
}
```

### Screenshots

![image](https://github.com/DevExpress/testcafe/assets/46747313/90d429e6-c209-4925-8a85-e59069057e94)

### Steps to Reproduce

1. Run tests

### TestCafe version

2.6.6, 3.1.0

### Node.js version

v16.15.1

### Command-line arguments

chrome

### Platform(s) and version(s)

MacOs Monterey 12.5

**Comment by miherlosev** [comment]
Hi @OlgaNel,

It appears you incorrectly specified the value for the `--lang` parameter. According to the [article](https://peter.sh/experiments/chromium-command-line-switches/), `lang` should be a 2-letter code from ISO-639. You can run the browser without TestCafe and validate the `lang` parameter setup.
