### ISSUE TITLE
Implement BDD interface and nested fixtures

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#792]
``` js
describe('Utils', () => {
  describe('compose', () => {
    it('composes from right to left', () => {
         ...
    });
  });
});
```

**Comment by mjhea0** [comment]
+1 for the nesting. do you have a branch for this?

**Comment by inikulin** [comment]
@mjhea0 It's still in the `proposal` state. We haven't even considered adding it yet, due to low demand.

**Comment by mjhea0** [comment]
Would be nice to see some patterns then. I break things up right now with my `await`s, since I have to authenticate, which gets messy:

```javascript
fixture.only('Smoke Test as a User')
  .page('https://blah.com');

  test(`performances...`, async (t) => {
    await t  // log in
      .useRole(user)
    await t // open "page"
      ...
    await t // ensure "something" is visible
      ...
    await t // ensure "something" is visible
      ...
  });
```

**Comment by inikulin** [comment]
I'm not sure I understand why you need BDD in that case. Can you just make multiple tests and use role in each of them, e.g. via `beforeEach`? Or you have same scenario as in https://github.com/DevExpress/testcafe/issues/1339#issuecomment-289529144?

**Comment by mjhea0** [comment]
It's less about bdd and more about nesting without losing the context of being logged in. Roles are a solution but they are still expensive. I'd like to be able to set a role in an outer scope and then be able to run a number of test cases without having to re authenticate.

**Comment by mjhea0** [comment]
Similar scenario. Love the idea of sections!

**Comment by inikulin** [comment]
@mjhea0 
> Roles are a solution but they are still expensive.

Note that roles perform authentication steps only once, afterwards role switching is basically page reload. We also had idea to implement `test.useRole` and `fixture.useRole` - with this API, authentication will be performed only once per role and each test run will start immediately in logged in state.

**Comment by PriyoBh** [comment]
Hi - do you guys have a timeline to implement this? Really looking forward to the fixture.userole() feature to be added. I have a subset of tests in the same functional area - they require the same login and the starting page is same for running that group of tests. So I need to do userole, navigate to that page, wait till the page is loaded properly - just once before running those tests. At the moment - I cannot do it in the fixture level as it cannot access the DOM. I have to use test.beforeEach() -- but this is a redundancy for my purpose

**Comment by miherlosev** [comment]
Hi @PriyoBh 

We cannot provide information when the feature will be implemented. As soon as we start to implement it, the `Milestone` field of this issue will be changed and you get a notification.

**Comment by chikunov** [comment]
I would like to put more emphasis on "sections" and "contexts" for organization and shared setup, other than just for roles. 
In any decently complex application there would be lots of areas that require some setup before you can run any tests. Currently all setup (before/after) is restricted to ```fixture``` and ```test``` which is not enough for more complex scenarios.

**Comment by LavrovArtem** [comment]
Would you please clarify what you mean by `put more emphasis on "sections" and "contexts"`. Could you please also share some examples of test structures that you wish to have?

**Comment by chikunov** [comment]
Sure,

lets say that i have a page with a form that could be in 2 different modes: read-only and editing. As name suggests, you should switch to the edit mode before you can change any values in the form. Rendering for those is different too.
I would like to have something like the following:

```js
fixture `MyPage`
    .page `http://mypage.com`;

section
    .before(async t => {
        await t.scrollTo(form);
    })
    ('Form', async t => {
        section
            .before(() => {
                await form.switchToReadOnlyMode();
            })
            ('Read-only mode', () => {
                test();
                test();
            });

        section
            .before(() => {
                await form.switchToEditMode();
            })
            ('Edit mode', () => {
                test();
                test();
            });
    });

section("Something unrelated to form on the same page", () => {})
```

This allows to group tests together and have a single setup point for a group. Furthermore, it allows to apply some metadata to sections and use it in reporting afterwards
```js
section('Some page area', () => {
  section.metadata('browser', 'chrome')("chrome tests", t => {
     test(); 
  });

  section.metadata('browser', 'firefox')("firefox tests", t => {
     test(); 
  });
})
```

It is possible to replicate similar behavior by moving those preparations into a separate function and calling them in every test, setting up metadata on every test etc. But this leads to a lot of duplication in code.

**Comment by gilmeir-curv** [comment]
Adding to what @inikulin reported, take for example jest, which lets you nest multiple `describe` sections, including each section's hooks. See [my comment here](https://github.com/DevExpress/testcafe/issues/2230#issuecomment-661819842).

**Comment by miherlosev** [comment]
We decided to not to complicate the product by adding new API for structuring tests.
