### ISSUE TITLE
TestCafe problem with decompression buffer from RequestLogger

### ISSUE THREAD

**Issue by JakubMaz** [DevExpress/testcafe#7922]
### What is your Scenario?

I want to recive request body from [RequestLogger](https://testcafe.io/documentation/402668/reference/test-api/requestlogger).

I use several ways:
1. Native automation = true, RequestLogger with stringifyResponseBody = ture
2. Native automation = true,  RequestLogger with stringifyResponseBody = false and I decode with `zlib.brotliDecompressSync(buffer)`
3. Native automation = false - RequestLogger with stringifyResponseBody = false and I decode with `zlib.brotliDecompressSync(buffer)`
4. Native automation = false - RequestLogger with stringifyResponseBody = true

### What is the Current behavior?

1st way - works OK.
2nd way - I got a `Decompression failed` error
3rd way - Decompression works fine
4th way - don't works, response body looks like: `�bu�L'!u§F♦��♥]���@↔j♥�t�n��U��♦����i��r�UM4T�D��▼z�؁ǆ@�$x����RBt◄
��2�1�L[�Pk��bG��q�@����CZ�♦|ǈ

��@�▲)F�*�GV‼7�I��PN0�����↓��ȉn�1duo_�8�O�����R��
H��/��E�↕y���5♣Q3�¶�������� �K�J♦�wbQ�►�@&��3�→#Ug��☻�▬�W♠♦�S6�ܧ�b��;寄�{�8��A�fv��М����`

### What is the Expected behavior?

I expect to my decopression code `zlib.brotliDecompressSync(buffer)` works when I use NativeAutomation.
(but RequestLogger with `stringifyResponseBody = ture` on nonNative Automation mode should works too)

I run my test on chrome (with Native Automation) and firefox (wchith is nonChromimum so it's run in nonNative Automation mode) there is no way to run my tests correctly.
There is a way to run mytests correctly on chrome or Filrefox but not on both of this. 

Workaround is to run chrome in onNative Automation mode.

### What is your public website URL? (or attach your complete example)

I reproduce this on https://reqres.in/

### What is your TestCafe test code?

```
import zlib from 'zlib';
import { RequestLogger, t } from 'testcafe';

const logger = RequestLogger({ url: /https:\/\/reqres.in\/api\/users/, method: 'get' }, {
    logResponseBody: true,
    logResponseHeaders: true,
});

const getBodyFromRequest = (request) => {
    const reqHeaderContentEncoding = request.response?.headers?.['content-encoding'];
    const isBrotliEncoding = reqHeaderContentEncoding === 'br';
    const buffer = request.response?.body;

    if (!buffer) {
        return {};
    }

    if (isBrotliEncoding) {
        const decoded = zlib.brotliDecompressSync(buffer);

        return JSON.parse(decoded.toString('utf-8'));
    }

    return JSON.parse(buffer.toString('utf-8'));
};

fixture('Test decode')
    .page('https://reqres.in/')
    .requestHooks(logger);

test('testDecodeBuffer', async () => {
    await t.expect(logger.contains(record => record.response.statusCode === 200)).ok();

    const requestBody = getBodyFromRequest(logger.requests[0]);

    /*
    ... test code
   */
});
```

### Steps to Reproduce

1. Receive request from website using RequestLogger (request should be compressed with br) 
2. Decode request response body with node function `zlib.brotli DecompresS(buffer)`

### TestCafe version

3.1.0

### Node.js version

18.17.0

### Command-line arguments

testcafe chrome tests/decode.js

### Browser name(s) and version(s)

chrome 115.0.5790.110, Firefox 115.0

### Platform(s) and version(s)

Windows

**Comment by miherlosev** [comment]
Hi @JakubMaz,

It's the difference between the `NativeAutomation` mode and the legacy `proxy` mode.
You don't need to manually decompress data with the `zlib.brotliDecompressSync` method in `NativeAutomation` mode.
Google Chrome API, which is used in `NativeAutomation` mode, automatically decodes request data.
And you need to decode the response manually in legacy proxy mode.
In your example, the target request has `gzip` encoding. I modified the shared example to make it work completely.

```js
import zlib from 'zlib';
import { RequestLogger, t } from 'testcafe';

const logger = RequestLogger({ url: /https:\/\/reqres.in\/api\/users/, method: 'get' }, {
    logResponseBody: true,
    logResponseHeaders: true,
    stringifyResponseBody: false,
});

const getBodyFromRequest = (request, isNativeAutomation) => {
    const reqHeaderContentEncoding = request.response?.headers?.['content-encoding'];
    const isGZipEncoding = reqHeaderContentEncoding === 'gzip';
    const buffer = request.response?.body;

    if (!buffer) {
        return {};
    }

    if (isNativeAutomation)
        return JSON.parse(buffer.toString('utf-8'));

    if (isGZipEncoding) {
        const decoded = zlib.gunzipSync(buffer);

        return JSON.parse(decoded.toString('utf-8'));
    }

    return decoded.toString('utf-8');
};

fixture('Test decode')
    .page('https://reqres.in/')
    .requestHooks(logger);

test('testDecodeBuffer', async () => {
    // setup before test run
    const isNativeAutomation = !!process.env.NATIVE_AUTOMATION === 'true';
    await t.expect(logger.contains(record => record.response.statusCode === 200)).ok({ timeout: 20_000});

    const requestBody = getBodyFromRequest(logger.requests[0], isNativeAutomation);
    console.log('requestBody', requestBody);
    /*
    ... test code
    */
});
```

**Comment by Aleksey28** [comment]
Hi @JakubMaz,

We already have a [PR ](https://github.com/DevExpress/testcafe/pull/7930) with this capability. It will be published in the nearest release after the merge.
