### ISSUE TITLE
Testcafe with userProfile option crashes

### ISSUE THREAD

**Issue by sofiyanguyen** [DevExpress/testcafe#7925]
### What is your Scenario?

TestCafe crashes when using the :userProfile browser option, with both Edge and Chrome. Upgraded from Testcafe v2.6.1 and encountered this issue.

### What is the Current behavior?

Crashes.

### What is the Expected behavior?

Should not crash.

### What is your public website URL? (or attach your complete example)

Running with any fixture produces this issue.

### What is your TestCafe test code?

Reproduce with minimal test.js: 

fixture `Fixture`
  .page('https://devexpress.github.io/testcafe/example/');

test('test', async t => {
    await t.wait(2000);
});

### Your complete configuration file

{
    "concurrency": 1,
    "selectorTimeout": 5000,
    "pageLoadTimeout": 5000,
    "assertionTimeout": 5000,
    "quarantineMode": false,
    "browser": "edge:userProfile",
    "screenshotPath": "artifacts",
    "screenshots": {
        "takeOnFails": true,
        "pathPattern": "${DATE}_${TIME}/${FIXTURE}/${TEST}_R${QUARANTINE_ATTEMPT}-${FILE_INDEX}.png"
    },
    "videoPath": "artifacts",
    "videoOptions": {
        "singleFile": false,
        "failedOnly": true,
        "pathPattern": "${DATE}_${TIME}/${FIXTURE}/${TEST}_R${QUARANTINE_ATTEMPT}-${FILE_INDEX}.mp4"
    },
    "reporter": [
        {
            "name": "spec"
        },
        {
            "name": "xunit",
            "output": "report-testcafe.xml"
        }
    ]
}

### Your complete test report

ERROR Unable to open the "edge:userProfile" browser due to the following error:

TypeError: Cannot read properties of undefined (reading 'Fetch')
    at NativeAutomationRequestPipeline.start (...\node_modules\testcafe\src\native-automation\request-pipeline\index.ts:387:28)
    at NativeAutomation.start (...\node_modules\testcafe\src\native-automation\index.ts:46:29)
    at BrowserProviderPluginHost._setupNativeAutomation (...\node_modules\testcafe\src\browser\provider\built-in\dedicated\chrome\index.js:63:32)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at BrowserProviderPluginHost.openBrowser (...\node_modules\testcafe\src\browser\provider\built-in\dedicated\chrome\index.js:109:13)
    at BrowserProvider.openBrowser (...\node_modules\testcafe\src\browser\provider\index.ts:326:9)
    at BrowserConnection._runBrowser (...\node_modules\testcafe\src\browser\connection\index.ts:279:13)
Type "testcafe -h" for help.
Process exited with code 1

### Steps to Reproduce

1. Run `testcafe.js  'edge:userProfile' test.js` 

### TestCafe version

3.1.0

### Node.js version

v18.16.1

### Command-line arguments

testcafe 'edge:userProfile' test.js

### Browser name(s) and version(s)

Edge Version 115.0.1901.188 (Official build) (64-bit), Chrome Version 115.0.5790.171 (Official Build) (64-bit)

### Platform(s) and version(s)

Windows

**Comment by AlexKamaev** [comment]
We decided to throw an error if the `:userProfile` option is used in Native Automation mode (this mode is used by default starting from TestCafe v3.0). Using the :userProfile option can lead to losing all cookie/localStorage data in your browser in Native Automation mode.
If you still need to use the `:userProfile` option, you can disable Native Automation using the `--disable-native-automation` flag ([https://testcafe.io/documentation/402638/reference/configuration-file#disablenativeautomation](https://testcafe.io/documentation/402638/reference/configuration-file#disablenativeautomation)).
