### ISSUE TITLE
RequestLogger works weird with concurrency >= 2 and CDP

### ISSUE THREAD

**Issue by vasilyevi** [DevExpress/testcafe#7977]
### What is your Scenario?

Trying to log the requests using RequestLogger and from time to time it shows incorrect data. I'm not able to reproduce the issue with concurrency = 1. 

### What is the Current behavior?

It does not log the correct requests.

I get the following error
`1) TypeError: Cannot read properties of undefined (reading 'response')`

I do log ne

### What is the Expected behavior?

It have to

### What is your public website URL? (or attach your complete example)

Sent the details to the [support@devexpress.com](mailto:support@devexpress.com)

### What is your TestCafe test code?

Sent the details to the [support@devexpress.com](mailto:support@devexpress.com)

### Your complete configuration file

```
const requestLogger = require("./tests/requestLogger");

module.exports = {
    screenshots: {
        path: "./artifacts/screenshots",
        takeOnFails: true,
        pathPattern: "${DATE}_${TIME}/${TEST}/${FILE_INDEX}_${QUARANTINE_ATTEMPT}.png",
        thumbnails: false
    },
    disableMultipleWindows: true,
    browsers: "chrome:headless",
    concurrency: 1,
    skipJsErrors: true,
    pageLoadTimeout: 40000,
    pageRequestTimeout: 45000,
    selectorTimeout: 15000,
    quarantineMode: false,
    hooks: {
        request: requestLogger,
    },
    disableNativeAutomation: false,

}
```

### Steps to Reproduce

Run the tests which I send to [support@devexpress.com](mailto:support@devexpress.com)

### TestCafe version

3.3.0-rc.1

### Node.js version

v18.17.0

### Command-line arguments

npx testcafe

**Comment by vasilyevi** [comment]
When do you plan to release the fix?

**Comment by PavelMor25** [comment]
At present, we can't give you an exact date as to when the next version will be released.

**Comment by vasilyevi** [comment]
but, it's a critical issue.... at least by my opinion...

**Comment by AlexKamaev** [comment]
We consider this issue important. That's why we tried to fix it as soon as possible. However, we cannot consider it `critical` because it does not affect a really big number of users. It is not a security issue, and it is not a crash. We still do not have the date of the next release. However, we usually try to release a new version every three/four weeks, so I hope it will be soon enough.

**Comment by AlexKamaev** [comment]
@vasilyevi
We are still working on the new version. I hope it will be ready soon. However, I cannot give you the exact time frames.
