### ISSUE TITLE
Redesign selector system

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#798]
I've got this idea while thinking about #795 and making API examples. Currently we have selector and snapshots. Selectors are functions that allow you retrieve node state aka node snapshot. Having a node snapshot you can retrieve other snapshots in DOM hierarchy. Moreover, we are going to add `find` method that will allow you to retrieve descendants of the element represented by snapshot. There is a problem with this approach: we have everything messed up together. It's confusing and we don't have ability to implement some scenarios due to this approach. E.g. having a selector `A` how can I write selector `B` which will select some child of the element given by selector `A`? And we should be able to pass this descendant selector to action and should have all properties like regular selectors. The correct answer is that selectors should be _combinable_ in order to reuse selectors to get nodes that are in relation with nodes, given by selector.
### The proposal
- Remove all selector methods from node snapshot: `getParentNode`, `getChildNode`,...
- Introduce methods above to selectors itself, which will return new selector, e.g. `parentNode()`
- Add method `descendant` and `ancestor` to selector
- Add `Selector.count()` method, that returns number of matching elements

So, e.g. instead of:

``` js
const ul = Selector('#list');

const paragraph = Selector(() => {
    var list = getList();

    if (!list) 
      return null;

   return list.querySelector('p');
}, { dependencies: { getList: ul } };
```

We'll be able to write:

``` js
const ul = Selector('#list');
const paragraph = ul.descendant('p');

// Now you can filter paragraphs by text:
paragraphWithText = paragraph.with({text:'Yo'});
```

it's extremely useful e.g. in page models, there need to build relations without data actual retrieval. 

I'm not sure, but seems like we can even get rid of `dependencies` with this approach.

Also, we will have consistent API: selectors are all about retrieval and can be combined in the functional programming style. Snapshots are just plain data.

\cc @DevExpress/testcafe 

---

**Update (22.09.16)**

Proposed API:
- [x] Deprecate snapshot hierarchy selectors (e.g. `getChildNode`)
- [x] Deprecate `t.select`
- [x] Deprecate `options.index`
- [x] Deprecate `options.dependencies`
- [x] Deprecate `options.text`

- [x] Allow unawaited calls to Selector outside of test context. 
- [x] Return `null` if Selector returns single node and `index` is more than 0.

- [x] `.nth(idx)`
- [x] `.withText(text|re)`

- [x] `.find(cssSelector)`
- [x] `.find(filterFn)`

- [x] `.parent(idx = 0)`
- [x] `.parent(cssSelector)`
- [x] `.parent(filterFn)`

- [x] `.child(idx = 0)`
- [x] `.child(cssSelector)`
- [x] `.child(filterFn)`

- [x] `.sibling(idx = 0)`
- [x] `.sibling(cssSelector)`
- [x] `.sibling(filterFn)`

- [x] `.count`
- [x] `.exists`

**Comment by AlexanderMoskovkin** [comment]
:+1: Looks good 

> I'm not sure, but seems like we can even get rid of dependencies with this approach.

```js
const getElementById     = Selector(id => document.querySelector(`#${id}`));
const getStatusBtn       = Selector(() => getElementById('statusBtn'), { dependencies: { getElementById } });
```
As a see we can't get rid of dependencies in this case or we can?

**Comment by inikulin** [comment]
@AlexanderMoskovkin It's synthetic example, you can just do:
```js
const getStatusBtn = Selector('#statusBtn');
```

But it would be nice if you add more examples, to see how they will fit into new paradigm

**Comment by AlexanderMoskovkin** [comment]
an example from our documentation:
```js
const getGridRow  = Selector(n => document.getElementsByClassName('grid-row')[n]);
const getGridCell = Selector((m, n) => getGridRow(m).children[n], {
     dependencies: { getGridRow }
});
```

**Comment by helen-dikareva** [comment]
I like it

**Comment by kirovboris** [comment]
Looks good, but in my opinion ```descendant``` and ```ancestor``` to typing too long.

**Comment by helen-dikareva** [comment]
may by `child/parent`

**Comment by helen-dikareva** [comment]
by `child/parent` looks like we'll fin on one level

**Comment by inikulin** [comment]
@helen-dikareva Correct. `Child/parent` means single level, but we'll have them as well.

**Comment by inikulin** [comment]
@kirovboris What do you think? Does fits well for you selector extensions?

**Comment by kirovboris** [comment]
If we're discussing the selector extensions, not the snapshot extension, it looks useful.
I mean this changes can't replace the snapshot extending for ```react-selectors``` plugin.

**Comment by inikulin** [comment]
@kirovboris It doesn't it applies only to selector combination. Snapshot extensions looks even more meaningful with this one.
