### ISSUE TITLE
No stacktrace on error when using the spec reporter

### ISSUE THREAD

**Issue by ChristianThingKnudsen** [DevExpress/testcafe#7987]
### What is your Scenario?

When an assertion goes wrong the line number of the assertion is not always printed when using the `spec` reporter as shown in the README: https://github.com/DevExpress/testcafe-reporter-spec. Some examples of my outputs:

```
      1) AssertionError: expected false to deeply equal true
         + expected - actual
         -false
         +true
``` 

```
    1) Cannot obtain information about the node because the specified selector does not match any node in the DOM tree.
          > | Selector('#send-reply-component')
            |   .find('#send-reply-ack-text')
```

### What is the Current behavior?

Stacktrace is not always printed

### What is the Expected behavior?

Stacktrace should always be printed

### What is your public website URL? (or attach your complete example)

N/A

### What is your TestCafe test code?

```
import { Selector } from 'testcafe';

fixture `Fixture`
  .page('http://example.com');

test('test', async t => {
await t.expect(true).eql(false)
});

```

### Steps to Reproduce

1. Run code snippet

### TestCafe version

3.0.0

### Node.js version

16.17.0

### Command-line arguments

none

**Comment by ChristianThingKnudsen** [comment]
Just updated the simple example `await t.expect(true).eql(false)`

**Comment by AlexKamaev** [comment]
I ran your test with `await t.expect(true).eql(false)` and got the following result:
![image](https://github.com/DevExpress/testcafe/assets/1678902/128e4a39-c799-40f3-81d2-31f905d671b2)
I'm not sure that I understand the issue. Do you expect that the report should have the following line?:
```
 > | await t.expect(true).eql(false)
```

**Comment by ChristianThingKnudsen** [comment]
Alright, let me explain more. Here is a more thorough example:

```
fixture("Stack trace").page("https://google.com");

test("Should show stack trace", async (t) => {
  await t.expect(true).eql(false);
});
```

When running this code I don't get the stack trace you do. Here is a screenshot: 
<img width="429" alt="image" src="https://github.com/DevExpress/testcafe/assets/27851699/87776094-8302-4e82-9cb8-9a7d32146108">

I am here running testcafe v.3.3.0 and nodejs nodejs 16.17.0. Here is a screenshot when running in a docker container (however this time I am running Testcafe v.3.0.0): 
<img width="522" alt="image" src="https://github.com/DevExpress/testcafe/assets/27851699/0f1ac718-8523-4236-971b-fcb017b896e0">

I only get the indication of which tests have failed not which assertions

**Comment by aleks-pro** [comment]
Hello @ChristianThingKnudsen ,

I did not manage to reproduce the issue with TestCafe v3.0.0 and the test example you shared. I'm using Ventura 13, Chrome 116, and NodeJS version 16.17.0. This is my output:

<img width="561" alt="image" src="https://github.com/DevExpress/testcafe/assets/14822473/4af88f6b-2e10-439a-b4e1-d101e54858bd">

Could you please share with us the entire project? Possibly there are customizations in it that prevent the spec reporter from outputting the stack trace

**Comment by ChristianThingKnudsen** [comment]
That is weird. I can reproduce it just by running it without any customization however my chrome version seems slightly different than yours. 
```
christianthingknudsen@MBPtilhhristian functional-tests % ./node_modules/.bin/testcafe chrome testcafe/fixtures/test-fixture.ts
 Running tests in:
 - Chrome 116.0.0.0 / Ventura 13

 Stack trace
 ✖ Should show stack trace

   1) AssertionError: expected true to deeply equal false

      + expected - actual

      -true
      +false


      Browser: Chrome 116.0.0.0 / Ventura 13



 1/1 failed (3s)
```

**Comment by AlexKamaev** [comment]
We checked it one more time on different machines with a different NodeJS version. It works as expected in our case. Unfortunately, we cannot do much, since the information is not sufficient to reproduce the issue.
