### ISSUE TITLE
errorInEachBrowserContains doesn't work if some browsers not failed

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#799]
See here: https://github.com/DevExpress/testcafe/blob/master/test/functional/assertion-helper.js#L79. `errorInEachBrowserContains` will return `true` even if the specified error is contained in just one browser, not in all of them, 'cause it loops not over the actual tested browsers, but over the errored ones.

**Comment by inikulin** [comment]
This on is a serious blocked. Is anyone working on it?

**Comment by AndreyBelym** [comment]
I'm working on it.
