### ISSUE TITLE
Dynamically-created iframe not loading properly in Firefox

### ISSUE THREAD

**Issue by drrnkin** [DevExpress/testcafe#7991]
### What is your Scenario?

A test loads a page that dynamically inserts an iframe. element and loads that content. The iframe fails to load.

### What is the Current behavior?

In Firefox, the iframe does not load at all (in any version of TestCafe that I have tried; 1.x, 2.x, 3.x).

Note that there's an error about `querySelectorAll` in the console.  In the provided sample, the main.ts file simply imports Highcharts (a popular charting library: https://www.highcharts.com/) and that's enough to cause the issue. I don't have the source so I can't whittle it down further.

### What is the Expected behavior?

Simple test at https://github.com/drrnkin/testcafe-iframe should pass. The test should detect the content in the iframe that is dynamically created by a script in the iframe. The test does not pass in Firefox in any version of TestCafe.

Expected: test should pass in Firefox and all other supported browsers.

### What is your public website URL? (or attach your complete example)

https://github.com/drrnkin/testcafe-iframe

### What is your TestCafe test code?

See provided repo

### Your complete configuration file

See provided repo

### Steps to Reproduce

1. Clone the repo https://github.com/drrnkin/testcafe-iframe
2. yarn
3. yarn build
4. yarn test-firefox

### TestCafe version

3.3.0

### Node.js version

v16.20.2

### Command-line arguments

See Steps to Reproduce

### Browser name(s) and version(s)

Firefox 116.0.3 (currently latest

### Platform(s) and version(s)

Windows 10

### Other

Split from #7983 .  This one is specific to Firefox.

**Comment by drrnkin** [comment]
Commenting to remove stale state

**Comment by matt-kxs** [comment]
This is still an issue with same steps.

**Comment by Bayheck** [comment]
This is a rare, low-priority use case, and a possible fix would be quite complex. As a workaround, please use Chrome for this case.
