### ISSUE TITLE
Let test fail on first failed assertion?

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#80]
Is it really usable to keep test running if assertion is already failed?

Pros:
- Simplify our code (no more fatal/non-fatal errors)
- Cleaner reports
- Possibly faster test runs 

Let's discus \cc @churkin @AlexanderMoskovkin @kirovboris @miherlosev @LavrovArtem @arubtsov @AndreyBelym  @VasilyStrelyaev @MargaritaLoseva

**Comment by kirovboris** [comment]
I think we should do it. If assertion failed, the page has unexpected state and next actions doesn't make sense.

**Comment by AlexanderMoskovkin** [comment]
I don't like it. Usually you have several assertions in the one step after some actions. For example if I have 5 assertions I would like to now they all are failed after one test run (not after 5 runs). Especially it's actual during test creating. It's actual for CI also. It takes more time to run tests and I would like to see all the problems after just one run.
Have you seen this approach in other test frameworks?

**Comment by kirovboris** [comment]
Anyway failed assertion is the same error like failed action. We can check the start of action, e.g. click the button, but only assertion can check - is it working or no. We should not separate fatal/non-fatal errors.

**Comment by inikulin** [comment]
@AlexanderMoskovkin Yep, actually nearly **all** frameworks follow this approach. More likely first assertion will show you what's going wrong and often other fails occurs because of "avalanche" effect. Haven't seen useful multiple failed assertions yet, IMO it's just pollutes the output.

**Comment by MargaritaLoseva** [comment]
Сan we create the Stop on error option? If the option is enabled, test execution ends if an error occurs.

**Comment by AndreyBelym** [comment]
Some frameworks stops execution after failed assertion(using default assertion mechanism), examples are [JUnit](http://stackoverflow.com/questions/10221891/continuing-test-execution-in-junit4-even-when-one-of-the-asserts-fails), [Visual Studio Team System](https://social.msdn.microsoft.com/Forums/en-US/e36fde7e-0d2b-43f2-92dd-de04e3bfb370/continuing-test-execution-after-an-assert-fails?forum=vststest), [NUnit](http://stackoverflow.com/questions/2834717/nunit-is-it-possible-to-continue-executing-test-after-assert-fails), [Selenium](http://sqa.stackexchange.com/questions/12967/is-there-any-way-to-continue-selenium-web-driver-script-after-assert-fails). 

But most of them have mechanisms to continue test case execution: Soft Assertions in Selenium, Error Collector in JUnit, Multiple Asserts in NUnit; so I'd give my vote for 'Stop on error' option.

**Comment by inikulin** [comment]
Not implementing custom assertion system. Test fails on first assertion

**Comment by darlanmendonca** [comment]
@inikulin when my spec fails, the testcafe continues run.

has an option to stop if fails?

**Comment by inikulin** [comment]
@darlanmendonca Do you mean if we have an option to not throw on assertions?

**Comment by darlanmendonca** [comment]
@inikulin no, I meant to stop the tests once the first break. Exactly like mocha --bail

**Comment by inikulin** [comment]
@darlanmendonca This is default behavior currently.

**Comment by inikulin** [comment]
@darlanmendonca Oh, my bad. `mocha -- bail` fails whole task once there is an error in the test. I guess we can implement it, can you issue separate feature request, please?

**Comment by darlanmendonca** [comment]
@inikulin nice, I will do

**Comment by darlanmendonca** [comment]
here https://github.com/DevExpress/testcafe/issues/1323 :D
