### ISSUE TITLE
Should click event be triggered by clicking on a disabled button? 

### ISSUE THREAD

**Issue by VasRoko** [DevExpress/testcafe#8004]
### File a new question on StackOverflow

https://stackoverflow.com/questions/ask?tags=testcafe

**Comment by AlexKamaev** [comment]
TestCafe should emulate browser behavior, so a disabled button should not work. I checked this behavior, and it works as expected in the latest TestCafe version.
Here is an example:
```HTML
<body>
    <button disabled="disabled">click me</button>
    <script>
        document.querySelector('button').addEventListener('click', () => {
            throw new Error('clicked');
        });
    </script>
</body>
```
```JS
test(`t`, async t => {
    await t.click('button');
});
```
Please check it on your machine and share your results.
Please also update your TestCafe version if you are not using the latest version.
