### ISSUE TITLE
NativeAutomation - Enable/Disable based on test meta value. NativeAutomation do not use existing sso login

### ISSUE THREAD

**Issue by aprabh001c** [DevExpress/testcafe#8008]
### What is your Scenario?

I have two suggestions/Enhancement w.r.t native automation

1. There should be an option to enable / disable native automation at test level/fixture level (similar to meta value). Right now we are using separate jobs for native automation enable/disable mode (as it doesn't support multi window). It would be good, if it can be enabled/disabled at test level/fixture level
2. Native automation is using existing SSO credentials for running the test, there should be an option to start the browser as clean ( the way it happens in disable mode). So that we can key in test creds rather than using user sso info.

### What are you suggesting?

1. There should be an option to enable / disable native automation at test level/fixture level (similar to meta value).
2. Native automation is using existing SSO credentials for running the test, there should be an option to start the browser as clean ( the way it happens in disable mode). So that we can key in test creds rather than using user sso info.

### What alternatives have you considered?

1. Right now we are using separate jobs for native automation enable/disable mode (as it doesn't support multi window). It would be good, if it can be enabled/disabled at test level/fixture level
2. Running in disabled mode

**Comment by AlexKamaev** [comment]
Hello.
Thank you for your suggestions. We are interested in implementing the described functionality. However, at this moment, there are some technical obstacles. I'll close the issue for now. However, in the future, we may return to these usage scenarios.
