### ISSUE TITLE
Support RequestMock Write

### ISSUE THREAD

**Issue by kerl4real** [DevExpress/testcafe#8011]
### What is your Scenario?

Scenario:
I would like the ability to use RequestMock to respond with a write function to be able to send a response in chunks. Currently the only way to send a response with RequestMock is by calling `setBody()` which is a one time call only.
NodeJS implementation: https://nodejs.org/api/http.html#responsewritechunk-encoding-callback

Use case: 
I am trying to mock a request to download a large data file that is being read in by a stream on the client side. I have tried setting the response body many ways but I think it needs to be streamed, which I cannot do with `setBody`.

### What are you suggesting?

TestCafe RequestMock implements a `write` function, similar to https://nodejs.org/api/http.html#responsewritechunk-encoding-callback that allows continual writing of the response to the consumer.

Another potential solution would to be able to `pipe` a stream to the response: https://nodejs.org/api/stream.html#readablepipedestination-options

### What alternatives have you considered?

I may look into mocking at an external level using WireMock.

**Comment by AlexKamaev** [comment]
Thank you for sharing your idea. The described functionality is interesting. However, it will take a lot of resources to implement such a behavior. Unfortunately, we are not ready to consider implementing this feature. We can return to the discussion in the future, but for now - I'll mark it as closed.
