### ISSUE TITLE
Relative URLs passed as --base-url CLI flag do not work with Role feature

### ISSUE THREAD

**Issue by razvanvancea** [DevExpress/testcafe#8012]
### What is your Scenario?

I am using --base-url CLI flag to pass the URL of my environments, however, I am facing an issue when running tests that use Role feature because its constructor does not support relative URLs ( error: You cannot specify relative login page URLs in the Role constructor. Use an absolute URL)

Testcafe v3.1.0-rc.3

const regularUser = Role('./autentificare', async (t) => {
        await t.click(homepageModel.acceptCookie);
        await LoginPage.doLogin();
});

### What is the Current behavior?

ERROR Cannot prepare tests due to the following error:

You cannot specify relative login page URLs in the Role constructor. Use an absolute URL.

### What is the Expected behavior?

Somehow Role constructor to be able to use a relative URL by concatenating the URL passed as --base-url PLUS the path passed in the constructor

### What is your public website URL? (or attach your complete example)

it s a dev environment, public app not available yet

### What is your TestCafe test code?

=== roles file ===
import { Role, t } from 'testcafe';
import homepageModel from '../page_models/homepageModel';

import minimist from 'minimist';
import LoginPage from '../page_models/LoginPage';

const loginURL = '/autentificare';

const regularUser = Role('./autentificare', async (t) => {
        await t.click(homepageModel.acceptCookie);
        await LoginPage.doLogin();
});

export { regularUser };

==== test file =====
test(`Add to favorite and remove item from favorite`, async (t) => {
        await t.useRole(regularUser);
        await t.navigateTo()......

### Steps to Reproduce

1. implement Role feature
2. pass app URL as CLI flag using  --base-url https://my-dev-env-website.com
3. run the test

### TestCafe version

3.1.0-rc.3

### Node.js version

v18.16.1

### Command-line arguments

npx testcafe tests/testFile.js --base-url https://my-dev-env-website.com

### Browser name(s) and version(s)

Chrome 116

### Platform(s) and version(s)

macos

**Comment by AlexKamaev** [comment]
I reopened the [original issue](https://github.com/DevExpress/testcafe/issues/3406) and closed this one as a duplicate. We'll discuss this enhancement with the team.
