### ISSUE TITLE
.pressKey not working as expected

### ISSUE THREAD

**Issue by JsonTyler** [DevExpress/testcafe#8026]
### What is your Scenario?

I'd like to be able to test my listbox component's keyboard navigation. I've used the .pressKey on other components to test keyboard navigation and it's worked fine.  

### What is the Current behavior?

- Test Cafe navigates to the listbox page
- Test Cafe clicks one of the listbox items
- Keypress (in code) for select all happens, but nothing happens in the test
- Test Fails

### What is the Expected behavior?

- Go to [this](https://design.sprbrk.com/components/listbox) site
- Under the Styles section click on the first item in the "Smart" listbox (labeled with A)
- Now with keyboard navigation do "ctrl+a"
- You'll notice that all of the items in the listbox are now selected
- Now with keyboard navigation do "ctrl+d"
- You'll notice that all of the items in the listbox are now selected

### What is your public website URL? (or attach your complete example)

https://design.sprbrk.com/components/listbox

### What is your TestCafe test code?

const { fixture, test, Selector, t } = require('testcafe');

fixture('Listbox - Accessibility Tests')
    .page('https://design.sprbrk.com/components/listbox');

test('Test select all keyboard nav of listbox', async t => {
    const listbox = Selector('div.e-listbox-container').nth(0);
    const listboxItem1 = listbox.find('li.e-list-item').nth(0);
    const listboxItem2 = listbox.find('li.e-list-item').nth(1);
    const listboxItem3 = listbox.find('li.e-list-item').nth(2);
    const listboxItem4 = listbox.find('li.e-list-item').nth(3);
    const listboxItem5 = listbox.find('li.e-list-item').nth(4);
    const listboxItem6 = listbox.find('li.e-list-item').nth(5);

    await t
        .expect(listbox.exists).ok()
        .click(listbox)
        .pressKey('ctrl+a')
        .expect(listboxItem1.getAttribute('aria-selected')).eql('true')
        .expect(listboxItem2.getAttribute('aria-selected')).eql('true')
        .expect(listboxItem3.getAttribute('aria-selected')).eql('true')
        .expect(listboxItem4.getAttribute('aria-selected')).eql('true')
        .expect(listboxItem5.getAttribute('aria-selected')).eql('true')
        .expect(listboxItem6.getAttribute('aria-selected')).eql('true')
});

test('Test de-select all keyboard nav of listbox', async t => {
    const listbox = Selector('div.e-listbox-container').nth(0);
    const listboxItem1 = listbox.find('li.e-list-item').nth(0);
    const listboxItem2 = listbox.find('li.e-list-item').nth(1);
    const listboxItem3 = listbox.find('li.e-list-item').nth(2);
    const listboxItem4 = listbox.find('li.e-list-item').nth(3);
    const listboxItem5 = listbox.find('li.e-list-item').nth(4);
    const listboxItem6 = listbox.find('li.e-list-item').nth(5);

    await t
        .expect(listbox.exists).ok()
        .click(listbox)
        .pressKey('ctrl+d')
        .expect(listboxItem1.getAttribute('aria-selected')).eql('false')
        .expect(listboxItem2.getAttribute('aria-selected')).eql('false')
        .expect(listboxItem3.getAttribute('aria-selected')).eql('false')
        .expect(listboxItem4.getAttribute('aria-selected')).eql('false')
        .expect(listboxItem5.getAttribute('aria-selected')).eql('false')
        .expect(listboxItem6.getAttribute('aria-selected')).eql('false')
});

### Your complete configuration file

module.exports = {
    browsers: ["chrome"],
    assertionTimeout: 50000,
    pageLoadTimeout: 50000,
    quarantineMode: true,
    selectorTimeout: 50000,
    skipJsErrors: true,
}

### Steps to Reproduce

1. Go to [this](https://design.sprbrk.com/components/listbox) site

2. Under the Styles section click on the first item in the "Smart" listbox (labeled with A)
 
3. Now with keyboard navigation do "ctrl+a"

4. You'll notice that all of the items in the listbox are now selected

5. Now with keyboard navigation do "ctrl+d"

6. You'll notice that all of the items in the listbox are now selected

### TestCafe version

3.3.0

### Node.js version

18.17.1

### Command-line arguments

testcafe myTest.js

**Comment by Bayheck** [comment]
Hello,
Your example website uses the [KeyboardEvent.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) property for handling the ‘ctrl+a’ command. TestCafe t.pressKey does not support the code property of KeyboardEvent. We recommend using the following workaround with[ the ](https://testcafe.io/documentation/403091/reference/test-api/testcontroller/dispatchevent)[t.dispatchEvent](https://testcafe.io/documentation/403091/reference/test-api/testcontroller/dispatchevent) method to fire your own DOM event:

test('Test select all keyboard nav of listbox', async t => {
    const listbox = Selector('div.e-listbox-container').nth(0);
    const listboxItem1 = listbox.find('li.e-list-item').nth(0);
    const listboxItem2 = listbox.find('li.e-list-item').nth(1);
    const listboxItem3 = listbox.find('li.e-list-item').nth(2);
    const listboxItem4 = listbox.find('li.e-list-item').nth(3);
    const listboxItem5 = listbox.find('li.e-list-item').nth(4);
    const listboxItem6 = listbox.find('li.e-list-item').nth(5);
 
    const optionsControl = {
        key: 'Control',
    };
 
    const optionsA = {
        code:    'KeyA',
        ctrlKey: true,
    };
 
    await t
        .expect(listbox.exists).ok()
        .click(listbox)
        .dispatchEvent(listbox, 'keydown', optionsControl)
        .dispatchEvent(listbox, 'keydown', optionsA)
        .dispatchEvent(listbox, 'keyup', optionsA)
        .dispatchEvent(listbox, 'keyup', optionsControl)
        .expect(listboxItem1.getAttribute('aria-selected')).eql('true')
        .expect(listboxItem2.getAttribute('aria-selected')).eql('true')
        .expect(listboxItem3.getAttribute('aria-selected')).eql('true')
        .expect(listboxItem4.getAttribute('aria-selected')).eql('true')
        .expect(listboxItem5.getAttribute('aria-selected')).eql('true')
        .expect(listboxItem6.getAttribute('aria-selected')).eql('true');
});
