### ISSUE TITLE
Property "white-space" returns "undefined" on Safari

### ISSUE THREAD

**Issue by PierreRott** [DevExpress/testcafe#8028]
### What is your Scenario?

I would like to get property "white-space" on Safari browser.

### What is the Current behavior?

TestCafé returns the property value as "undefined".

### What is the Expected behavior?

TestCafé should return valid value such as "nowrap".

### What is your public website URL? (or attach your complete example)

**HTML:**
```
<div>
    <span id="myProperty">my text</span>
</div>
```

**CSS:**
```
#myProperty {
    white-space: nowrap;
    padding-bottom: 500px;
}
```

### What is your TestCafe test code?

```
test.only('Should check white-space property', async () => {
    console.log(await Selector('#myProperty').getStyleProperty('white-space'));
    console.log(await Selector('#myProperty').getStyleProperty('padding-bottom'));
});
```

### Your complete test report

undefined
500px
 √ Should check white-space property

### Steps to Reproduce

1. Set element CSS "white-space" property to "nowrap"
2. Get "white-space" style property value by method ".getStyleProperty('white-space')"
3. Check that returned value is "undefined"

### TestCafe version

3.2.0

### Node.js version

v20.8.0

### Command-line arguments

testcafe remote **.e2e-spec.ts --hostname [ip-address]

### Browser name(s) and version(s)

Safari 17.0

### Platform(s) and version(s)

macOS Sonoma 14.0

**Comment by PavelMor25** [comment]
Hello @PierreRott,

We have already encountered the same issue.

You can use the workaround from [The DOMNodeState.style object does not contain some style properties](https://github.com/DevExpress/testcafe/issues/7800).

**Comment by PierreRott** [comment]
@PavelMor25 
Thank you for the prompt reply.

First of all, it should be noted that the mentioned issue 7800 refers to the implementation of Chrome, where the rule "white-space" divides into two other rules ("text-wrap" and "white-space-collapse"). However, in this case, the problem is reported for behavior on Safari. If the style can be obtained other than via `getStyleProperty`, the more it seems that this method is not doing what one would expect.

I am aware that there is a workaround via ClitentFunction, but we are dependent on using TestCafé's implementation of the Selector type, where the vast majority of our methods expects the parameter of this data type.

We would have to get the selector from the `Selector` in the string data type, which TestCafé does not currently allow. 
The only way I've been able to find is `selector[Object.getOwnPropertySymbols(selector)[0]].options.apiFnChain`. 
All of this requires too much bypassing of your framework's intended behavior. 
If you still don't consider this a bug, could you please convert this issue to a "Feature request"?

**Comment by PavelMor25** [comment]
@PierreRott 

I tried to reproduce the issue and obtained the expected result:
safari 16.1 / Ventura 13 / testcafe 3.3.0

![photo1697119741](https://github.com/DevExpress/testcafe/assets/77216072/632bc799-340e-4216-a3c4-6b57774f5f14)

>If you still don't consider this a bug, could you please convert this issue to a "Feature request"?

This looks more like a browser bug rather than a testcafe bug, so right now we can only recommend working with the suggested workaround.
