### ISSUE TITLE
.afterEach block should still execute when .beforeEach fails

### ISSUE THREAD

**Issue by Makavelic** [DevExpress/testcafe#8050]
### What is your Scenario?

I do environment setup in the .beforeEach (adding users for example), and cleanup in the .afterEach(deleting users). If the .beforeEach fails at any point, the .afterEach will not execute and my data is not cleaned up. 

### What is the Current behavior?

.afterEach will not execute if .beforeEach fails

### What is the Expected behavior?

.afterEach should always execute

### What is your public website URL? (or attach your complete example)

```
fixture("test")
	.beforeEach(async t => {
		console.log("startBeforeEach");
		const fail = true;
		if (fail) {
			throw new Error();
		}
		await t.wait(1);
	})

	.afterEach(async t => {
		console.log("startAfterEach");
		await t.wait(1);
	});

test("test1", async t => {
	await t.wait(1);
});
```

### What is your TestCafe test code?

```
fixture("test")
	.beforeEach(async t => {
		console.log("startBeforeEach");
		const fail = true;
		if (fail) {
			throw new Error();
		}
		await t.wait(1);
	})

	.afterEach(async t => {
		console.log("startAfterEach");
		await t.wait(1);
	});

test("test1", async t => {
	await t.wait(1);
});
```

### Your complete configuration file

None needed

### Your complete test report

![image](https://github.com/DevExpress/testcafe/assets/9947758/dba96ece-ca83-4aa5-a40c-c5f54f7e21a1)

### Screenshots

![image](https://github.com/DevExpress/testcafe/assets/9947758/31423926-eeca-4cd3-aa4a-dd246304c31c)

### Steps to Reproduce

1. Run test
2. Notice no console.log for startAfterEach

### TestCafe version

3.3.0

### Node.js version

18.16.0

### Command-line arguments

testcafe 'chrome' 'path\testName.ts' '-c' '1' '--test' 'test1'

### Browser name(s) and version(s)

Chrome 118

### Platform(s) and version(s)

Windows 11

**Comment by AlexKamaev** [comment]
Thank you for sharing your suggestion. We cannot consider this behavior as a bug. From our perspective, if beforeHook fails, this means that beforeHook is incorrect itself. It's not afterHook's purpose to сlean up the changes made in the incorrect beforeHook.

We think that the correct approach in this case should be the following:

1. wrap beforeHook in a `try/catch` block;
2. process the error and clean up everything you need;
3. re-throw the error.

**Comment by Makavelic** [comment]
> Thank you for sharing your suggestion. We cannot consider this behavior as a bug. From our perspective, if `beforeHook` fails, this means that `beforeHook` is incorrect itself. It's not `afterHook`'s purpose to сlean up the changes made in the incorrect `beforeHook`.
> 
> We think that the correct approach in this case should be the following:
> 
> 1. wrap `beforeHook` in a `try/catch` block;
> 2. process the error and clean up everything you need;
> 3. re-throw the error.

That's just asking for ugly code and isn't as efficient as being able to rely on fixture hooks. For reference, Junit works this way. If you don't agree with it being the default behavior is it possible to look into allowing configuration for it? I think doing setup in the .beforeEach and cleaning up in the .afterEach is a very common pattern -  adding a try catch on every setup call (there could be many within a single hook) doesn't sound like a good workaround.

**Comment by AlexKamaev** [comment]
We discussed the issue with the team and decided to keep it closed. In our opinion, in general, it's difficult to determine which data should be cleaned up on the `afterEach` hook if the `beforeEach` hook has failed, so it's better to clean up data immediately after the failure, not on the `afterEach` hook.
