### ISSUE TITLE
OKTA authentication with Testcafe

### ISSUE THREAD

**Issue by shyedhu** [DevExpress/testcafe#8051]
### What is your Scenario?

I have OKTA login application wanted to automate LoginbyOKTAApi through backend call instead of UI validation with help of Testcafe . How to do OKTA authentication through testcafe , I was able to see such good feature through cypress automation tool https://docs.cypress.io/guides/end-to-end-testing/okta-authentication

do we have a similar feature to cover the OKTA authentication through testcafe??

### What are you suggesting?

Okta authentication through testcafe

**Comment by PavelMor25** [comment]
Hello @shyedhu
>do we have a similar feature to cover the OKTA authentication through testcafe??

Testcafe doesn't have a similar feature. I examined the Cypress example and can suggest you to use the example and functional Testcafe to solve your task:
`t.request` - to get `id_token` ;
`clientFunction` - to save data in localStorage.

Please refer to the following help topic to read about [Client Functions](https://testcafe.io/documentation/402832/guides/basic-guides/client-functions) and [.request()](https://testcafe.io/documentation/403981/reference/test-api/testcontroller/request)
