### ISSUE TITLE
It is not clear if "ESM Module Support" and Typescript are mutually exclusive 

### ISSUE THREAD

**Issue by tipy01** [DevExpress/testcafe#8052]
### What is your Scenario?

I want to import the latest version of [dateformat](https://github.com/felixge/node-dateformat) that exports itself as esm module only in my Typescript test file.

### What is the Current behavior?

As dateformat only exports as esm I get:
```
ERROR Cannot import the /my-project/node_modules/dateformat/lib/dateformat.js ECMAScript module from /my-project/e2e/myTest.spec.ts. Use a dynamic import() statement or enable the --esm CLI flag.
```
So I enable the  ["ESM Module Support"](https://testcafe.io/documentation/404258/guides/advanced-guides/esm-module-support) and I get:

```
ERROR Cannot prepare tests due to the following error:

TypeError: Unknown file extension ".ts" for /my-project/e2e/myTest.spec.ts
 ```
I also tried importing dateformat without "ESM Module Support" and using a dynamic import() in my test function and I get the same `Use a dynamic import() statement or enable the --esm CLI flag`.

So I understand that "ESM Module Support" and Typescript are mutually exclusive.

### What is the Expected behavior?

The [documentation](https://testcafe.io/documentation/402639/reference/command-line-interface?search#--esm) should states that "ESM Module Support" and Typescript are mutually exclusive if it is true.

Eventually I would expect to be able to import esm only lib in my Typescript tests.

### What is your public website URL? (or attach your complete example)

This issue does not mind about accessing DOM elements.

### What is your TestCafe test code?

```TypeScript
import { Selector, t } from "testcafe";
import DateFormat from "dateformat";

fixture`My fixture;

test("My test", async () => {
    const myElementSel = Selector("#myElement");
    await t.expect(myElementSel.innerText).contains(DateFormat(new Date(), "yyyy-mm-dd"));
});
```

### Your complete configuration file

```cjs
module.exports = {
    browsers: [
        "chrome",
    ],
    src: "e2e/**/*.spec.ts",
    reporter: [
        {
            name: "spec",
        },
        {
            name: "spec",
            output: "reports/report.txt",
        }
    ],
    quarantineMode: false,
    debugMode: false,
    debugOnFail: true,
    stopOnFirstFail: true,
    skipJsErrors: true,
    skipUncaughtErrors: true,
    appInitDelay: 7000,
    concurrency: 1,
    selectorTimeout: 5000,
    assertionTimeout: 5000,
    pageLoadTimeout: 3000,
    speed: 0.8,
    disablePageCaching: false,
    developmentMode: false,
    qrCode: false,
};

```

### Steps to Reproduce

1. Develop a test using Typescript
2. Import a lib that export only as esm module 
3. Run the test

### TestCafe version

testcafe@3.3.0

### Node.js version

v18.18.2

### Command-line arguments

chrome

**Comment by Aleksey28** [comment]
Hi @tipy01,

I didn't manage to reproduce the issue. I took your test and config. First of all, I ran the test as is and got an error saying that I should use the `--esm` option. Then I tried to run the test with the `--esm` option and everything worked correctly except for the error with the selector.
My test has a `*.ts` extension and a config with a`*.js` extension. I run it on Node 18.18.2, TestCafe 3.3.0, Windows 11. Please check your test again in isolated conditions.

**Comment by tipy01** [comment]
Hi @Aleksey28, thank you for your fast response.

I think that you did not manage to reproduce it because you do not have the [`"type": "module"` ](https://nodejs.org/api/packages.html#type) line in your package.json.

I have this line in mine and my testacfe config has a `.cjs` extension (as it fits for a project with `"type": "module"` in package.json).

**Comment by Aleksey28** [comment]
I changed the extension of the `testcafe` config file to `*.cjs`, and added `"type": "module"` to the `package.json`. I got the same result – only the issue with `selector`. Please create a public repo on GitHub with this example.

**Comment by tipy01** [comment]
Thanks for trying @Aleksey28,

I made a [minimal repo](https://github.com/tipy01/testcafe-8052)

So you can try launching the test in e2e folder with and without `esm: true,` in .testcaferc.cjs

**Comment by Aleksey28** [comment]
StartupHi @tipy01,

I see that you try to set the `esm` option to the config file. There is only one way to turn on ESM: pass the `--esm` option to CLI. You cannot pass this option to the config file or directly to the runner.

**Comment by tipy01** [comment]
Hi @Aleksey28,

I get the same problem if I put the `"--esm",`  in the args list of launch.json (so as a CLI option).

**Comment by Aleksey28** [comment]
I managed to reproduce the issue. It occurs because the launcher with these configs starts a process in a way that bypasses our ESM handler. As a workaround, you can add a script to `package.json`, for example:

```json
  "scripts": {
    "testChrome": "testcafe chrome e2e/test.spec.ts --esm --ignore-certificate-errors"
  },
```

Then, add this type of config to the launcher:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node-terminal",
      "request": "launch",
      "name": "TestCafe Chrome launch test file",
      "command": "npm run testChrome"
    }
  ]
}
```

**Comment by tipy01** [comment]
Hello @Aleksey28,

Thank you for your attempts, I tried your workaround but it does not works (I get similar errors). 

Actually I do not think it is linked to the way we launch the test because I get the sames errors when I type `node ./node_modules/testcafe/bin/testcafe.js chrome e2e/test.spec.ts --esm --ignore-certificate-errors` in the VS Code terminal.

**Comment by Aleksey28** [comment]
Hi @tipy01,

I see. Use `./node_modules/testcafe/bin/testcafe-with-v8-flag-filter.js` instead of `./node_modules/testcafe/bin/testcafe.js`.

**Comment by tipy01** [comment]
Hi @Aleksey28,

Ok with `testcafe-with-v8-flag-filter.js` it works. Thanks.
