### ISSUE TITLE
On device emulation, click on items on the very side of page doesn't work

### ISSUE THREAD

**Issue by Silhm** [DevExpress/testcafe#8057]
### What is your Scenario?

When using device emulation, clicking on very side of the page doesn't trigger anything on my page
Testcafe hangs until timeout

### What is the Current behavior?

I know that the design of my snippet is not optimal in real web apps.
The click doesn't trigger the innerText to change.

I tried with Testcafe 2.4.0 without any trouble, but with Testcafe 3.3.0 the test doesn't pass anymore

### What is the Expected behavior?

I would expect item to be clickable in the test on Mobile device emulation

### What is your public website URL? (or attach your complete example)

On a given html document:
```html
<body style="margin:0">
    <span id="target" style="position:fixed; right:0" onclick="this.innerText='boop'">T</span>
</body>
```
    
[https://www.silhm.fr/issues/testcafe-click.html](https://www.silhm.fr/issues/testcafe-click.html)

### What is your TestCafe test code?

My _test.spec.js_ is quite simple:
```js
import { Selector } from 'testcafe';

fixture('Getting Started')
    .page('https://www.silhm.fr/issues/testcafe-click.html');

test('My first test', async t => {
    await t
        .click('#target')
        .expect(Selector('#target').innerText).eql('boop');
});
```

### Steps to Reproduce

1. Run the attached test with testcafe 2.4.0 : it works
2. Run the attached test with testcafe 3.3.0 : it doen't work anymore

### TestCafe version

3.3.0

### Node.js version

20.8.1

### Command-line arguments

npx testcafe "chrome:emulation:device=Pixel 2" test.spec.js` 

### Browser name(s) and version(s)

chrome:emulation:device=Pixel 2    (chrome 118)

### Platform(s) and version(s)

Linux Mint 21.2

**Comment by PavelMor25** [comment]
Hello @Silhm

Thank you for your sharing the information.

We know about this issue and fixed it in the next release.
This behavior occurs with native automation mode, so you need to disable it to solve the issue until the next version is released.

Please refer to following help topic to read about [disableNativeAutomation](https://testcafe.io/documentation/402638/reference/configuration-file#disablenativeautomation).
