### ISSUE TITLE
[release] First public beta

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#806]
I'm going to release first RC for the public beta tomorrow. Do we have anything blocking?
\cc @DevExpress/testcafe  

**Update**
RC was released, further steps:

- [x] Fix all found issues https://github.com/DevExpress/testcafe/milestone/12
- [x] Update all package dependencies with beta:
   - [x] https://github.com/DevExpress/gulp-testcafe (and release it)
   - [x] https://github.com/DevExpress/testcafe-browser-provider-saucelabs
   - [x] https://github.com/DevExpress/testcafe-browser-provider-phantomjs
   - [x] https://github.com/DevExpress/testcafe-reporter-list
   - [x] https://github.com/DevExpress/testcafe-reporter-spec
   - [x] https://github.com/DevExpress/testcafe-reporter-minimal
   - [x] https://github.com/DevExpress/testcafe-reporter-json
   - [x] https://github.com/DevExpress/testcafe-reporter-xunit

**Comment by inikulin** [comment]
@VasilyStrelyaev it doesn't relate to docs or promotional material. I'm asking about functionality things.

**Comment by AlexanderMoskovkin** [comment]
@inikulin The only thing I'm worry about - it looks like legacy api compiler takes too much memory (it's about 200MB for 134 asp fixtures in my case). But I think it'll be fixed in the `testcafe-legacy-api` repository

**Comment by inikulin** [comment]
RC was released
