### ISSUE TITLE
Test Cafe Script throwing JS Errors

### ISSUE THREAD

**Issue by harshitshah4** [DevExpress/testcafe#8067]
### What is your Scenario?

We are currently using test cafe to test Apple Pay demo website: https://applepaydemo.apple.com/, on opening that website Apple Pay button was not shown, initially it was due to website being not served over https and hence Apple Pay was giving error that website is not served is secure context.
Then we followed the doc: https://testcafe.io/documentation/402839/guides/advanced-guides/test-https-features-and-http2-websites
After serving the website over https, it no longer gives error for secure context.
But we are receiving another JS error:
```
 ✖ End to End Scenario

   1) A JavaScript error occurred on "https://applepaydemo.apple.com/".
      Repeat test actions in the browser and check the console for errors.
      Enable the “skipJsErrors” option to ignore JavaScript errors during test execution. Learn
      more: "https://testcafe.io/documentation/404038/recipes/debugging/skip-javascript-errors"
      If the website only throws this error when you test it with TestCafe, please create a new
      issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      undefined is not an object (evaluating '__get$(this,"t") .innerHTML='<button><span
      id="container" /></button>'')
      rt@https://applepay.cdn-apple.com/jsapi/v1.1.0/apple-pay-button.js:94:54394
      define@[native code]
      @https://applepay.cdn-apple.com/jsapi/v1.1.0/apple-pay-button.js:94:58039
      module code@https://applepay.cdn-apple.com/jsapi/v1.1.0/apple-pay-button.js:94:58066
      evaluate@[native code]
      moduleEvaluation@[native code]
      @[native code]
      asyncFunctionResume@[native code]
      @[native code]
      promiseReactionJobWithoutPromise@[native code]
      promiseReactionJob@[native code]

      Browser: Safari 15.6.1 / macOS 10.15.7
```
This error does not come without Test Cafe and website works fine too.
The code also looks to be coming from Hammerhead script.

### What is the Current behavior?

JS error coming and Apple Pay Button being not visible.

### What is the Expected behavior?

No errors should come, and Apple Pay button should be visible.

### What is the public URL of the test page? (attach your complete example)

https://applepaydemo.apple.com/

### What is your TestCafe test code?

```
fixture("e2e")
    .page("https://applepaydemo.apple.com/");


test("End to End Scenario", async (t) => {
    await new Promise((res, _) => setTimeout(res, 80000));
})
```

### Screenshots

Error:
<img width="997" alt="Screenshot 2023-11-03 at 12 50 32 PM" src="https://github.com/DevExpress/testcafe/assets/14928914/cf3077a2-b38a-473c-9b4f-5b94f80f73f9">

Current behavior:
<img width="1313" alt="Screenshot 2023-11-03 at 12 47 41 PM" src="https://github.com/DevExpress/testcafe/assets/14928914/3dcf0bd7-1bbd-450b-90da-d3a9ab6f7fb6">

Expected behavior:
<img width="1312" alt="Screenshot 2023-11-03 at 12 51 35 PM" src="https://github.com/DevExpress/testcafe/assets/14928914/b1712ae1-0899-4d4a-910e-896c1ab8214b">

### Steps to Reproduce

1. Open "https://applepaydemo.apple.com/" using Hammerhead proxy.

### TestCafe version

3.3.0

### Node.js version

v16.20.2

### Command-line arguments

testcafe safari -e test.js --ssl pfx=testingdomain.pfx;rejectUnauthorized=true;

### Browser name(s) and version(s)

Safari 15.6.1

### Platform(s) and version(s)

macOS 12.6.2

**Comment by CormacBrowserStack** [comment]
Hello Team,

I'm confirming this issue for a customer we have. Do we have timelines for this?
