### ISSUE TITLE
Access fixture metadata from tests

### ISSUE THREAD

**Issue by jawadst** [DevExpress/testcafe#8069]
### What is your Scenario?

We run tests that dynamically adapt their expectations based on fixture metadata. It would be great to be able to access the fixture metadata from the tests.

### What are you suggesting?

Provide a copy of the fixture metadata to the tests

Example:

```js
fixture
  .page(...)
  .meta({
    key: 'value'
  });

test(
  'Test',
  async t => {
    await t.expect(t.fixtureMeta.key).eql('value');
  },
);
```

**Comment by Bayheck** [comment]
Hello, thank you for reaching out to us. Actually, you can access the fixture metadata from tests using t.fixture property. You can find information on this subject in our documentation for TestController (https://testcafe.io/documentation/404445/reference/test-api/testcontroller/fixture).
So, for your example it would be something like this:

`fixture.page().meta({
    key: 'value'
  });`

`test(
  'Test',
  async t => {
    await t.expect(t.fixture.meta.key).eql('value');
  },
);`
