### ISSUE TITLE
Unable to upload files using Testcafe in headless browser due to difference in behaviour with normal browser run.

### ISSUE THREAD

**Issue by devashish2203** [DevExpress/testcafe#8081]
### What is your Scenario?

We have a Test cafe test that tries to upload a file using the setFilesToUpload method. The test works fine when run in normal chrome browser, but the test fails in headless browser mode.

### What is the Current behavior?

Based on our investigations it looks like the cancel event is triggered first in the headless browser mode while in the normal mode the cancel event is not triggered.

### What is the Expected behavior?

File upload behaves the same in normal vs Headless browser execution.

### What is the public URL of the test page? (attach your complete example)

Created a sample app to reproduce the issue we are facing. The app is accessible at https://jsfiddle.net/dreadlord2203/e7qrgtzc/

On click of the upload button two event handlers are registered (cancelHandler and changeHandler), when either of the events is triggered we remove the event listeners and process the received event.

For the example we are logging a message when the handler is called.

### What is your TestCafe test code?

```
import { Selector, t } from 'testcafe';

fixture('Example File Upload').beforeEach(async () => {
  await t.navigateTo('https://jsfiddle.net/dreadlord2203/e7qrgtzc/');
});

const dataFilesPath = `${process.cwd()}/e2e/src/data/files`;
const uploadButton = Selector('#uploadButton', { timeout: 60000 });
const uploadInput = Selector('#myFile', { timeout: 60000 });
const filePath = `${dataFilesPath}/allTypes.csv`;
const consoleElement = Selector('#console', { timeout: 60000 });
test('Js Fiddle file upload', async () => {
  await t.click(consoleElement);
  await t.switchToIframe(Selector('main [name="result"]', { timeout: 60000 }));
  const uploadButtonElement = await uploadButton();
  await t.click(uploadButton);
  await t.setFilesToUpload(uploadInput, filePath);
  await t.switchToMainWindow();
  await t.wait(10000);
  await t.takeScreenshot('FileUploadErrorTest/image.png');
});
```

### Your complete configuration file

{
  "color": true,
  "compilerOptions": {
    "typescript": {
      "configPath": "e2e/tsconfig.json",
      "customCompilerModulePath": "../typescript"
    }
  },
  "pageLoadTimeout": 5000,
  "appInitDelay": 3000,
  "browserInitTimeout": 60000,
  "selectorTimeout": 5000,
  "assertionTimeout": 5000,
  "testExecutionTimeout": 600000,
  "runExecutionTimeout": 10800000,
  "speed": 1,
  "screenshots": {
    "path": "e2e/artifacts/screenshots",
    "takeOnFails": true,
    "pathPattern": "${FIXTURE}/${TEST}-${DATE}-${TIME}.png"
  },
  "videoPath": "e2e/artifacts/videos",
  "videoOptions": {
    "singleFile": false,
    "failedOnly": false,
    "pathPattern": "${FIXTURE}/${TEST}-${DATE}-${TIME}.mp4"
  },
  "disablePageCaching": true
}

Running with Native Automation enabled

### Screenshots

Screenshot1 - In normal browser mode

![image](https://github.com/DevExpress/testcafe/assets/7950196/a150a3f4-fc13-446a-9359-fd90350f8540)

The console shows that the change event was triggered and value was set properly.

Screenshot 2 - In chrome headless mode
![image](https://github.com/DevExpress/testcafe/assets/7950196/62f62fd6-a1ff-49b3-9179-696bf7ce5f9b)

The console shows that the cancel event was triggered, and due to that the change handler is never called.

### Steps to Reproduce

Run the above test code against the example URL.

### TestCafe version

"testcafe": "3.3.0"

### Node.js version

v18.18.2

### Command-line arguments

-r spec -r html:report.html  -b=chrome and for headless -b=chrome --headless

**Comment by PavelMor25** [comment]
Duplicate #8082
