### ISSUE TITLE
takeScreenshot ignores Path Pattern Placeholders

### ISSUE THREAD

**Issue by vasilyevi** [DevExpress/testcafe#8086]
### What is your Scenario?

Trying to specify name for the screenshot ad it ignores Path Pattern Placeholders specified in config file.

### What is the Current behavior?

it ignores Path Pattern Placeholders specified in config file

### What is the Expected behavior?

have to use Path Pattern Placeholders

### What is the public URL of the test page? (attach your complete example)

N/A

### What is your TestCafe test code?

await t.takeScreenshot("asd"); -> saves in ./artifacts/screenshots/asd.png

await t.takeScreenshot("${DATE}_${TIME}/${TEST}/asd.png"); -> saves in ./artifacts/screenshots/${DATE}_${TIME}/${TEST}/asd.png

### Your complete configuration file

screenshots: {
        path: "./artifacts/screenshots",
        takeOnFails: true,
        pathPattern: "${DATE}_${TIME}/${TEST}/${FILE_INDEX}_${QUARANTINE_ATTEMPT}.png",
        thumbnails: false
    },

### Steps to Reproduce

N/A

### TestCafe version

3.4.0

### Node.js version

v18.17.0

### Command-line arguments

npx testcafe

**Comment by PavelMor25** [comment]
Hello @vasilyevi,

When you add a path in the `takeScreenshot` method the argument overrides the relative path specified with the default or custom path patterns from your config file.

Please refer to the following help topic: [t.takeScreenshot Method](https://testcafe.io/documentation/402675/reference/test-api/testcontroller/takescreenshot)

**Comment by vasilyevi** [comment]
I do understand that it overrides, but my need is to make a screenshot with a custom name, but save it exactly to the same folder. Is it supported? what's the reason if not?

**Comment by PavelMor25** [comment]
TestCafe does not support this functionality, and we cannot classify it as a bug. We can accept this ticket as an enhancement request. However, we cannot specify estimates for when this feature may be implemented.

**Comment by vasilyevi** [comment]
I definitely disagree as one feature bakes the logic of another one. I surprised it wasn't reported previously. Anyway it's up to you
