### ISSUE TITLE
TypeError when trying to update testcafe to 3.4.0

### ISSUE THREAD

**Issue by trudeloli** [DevExpress/testcafe#8089]
### What is your Scenario?

I try to update my testcafe to 3.4.0 from 2.1.0 but I got an error when I start a Test

node_modules\@babel\plugin-transform-runtime\lib\babel-7\polyfills.cjs: 

_index2.createPolyfillPlugins is not a function (While processing: "base$0") (While processing: "base$0")

### What is the Current behavior?

Impossible to start a test,

### What is the Expected behavior?

Able to run a test

### What is the public URL of the test page? (attach your complete example)

no response

### What is your TestCafe test code?

node_modules\@babel\plugin-transform-runtime\lib\babel-7\polyfills.cjs: _index2.createPolyfillPlugins is not a function (While processing: "base$0") (While processing: "base$0")

### Steps to Reproduce

1.
2.
3.

### TestCafe version

2.1.0

### Node.js version

v18.12.1

### Command-line arguments

yarn testcafe

**Comment by AlexKamaev** [comment]
It's unlikely a TestCafe issue. Please try to delete the `node_modules` folder in your project, remove `package-lock.json` if it exists, uninstall the global `testcafe` module if it's installed globally and try to install all dependencies again. If this does not work, please share a sample that demonstrates the incorrect behavior.

**Comment by ayemelyanenko-chegg** [comment]
I managed to reproduce the issue.

Please clone this [sample repository,](https://github.com/ayemelyanenko-chegg/sample-axios-testcafe.git) 
run `yarn install` 
and then from root, run
`yarn testcafe chrome sampleTest.ts `

And this error will show up

<img width="562" alt="Screenshot 2023-12-08 at 3 04 47 PM" src="https://github.com/DevExpress/testcafe/assets/14633459/801e9666-3515-424c-ba4b-ced3243ec4bd">

**Comment by PavelMor25** [comment]
Dublicate #8091
