### ISSUE TITLE
Multiple browser disconnected errors with NativeAutomation enabled

### ISSUE THREAD

**Issue by alex-zh** [DevExpress/testcafe#8090]
### What is your Scenario?

We updated version 2.6  to version 3.4. After that we get massive  "browser disconnected" errors on our k8s cluster
if set disableNativeAutomation = true, errors are gone away 

### What is the Current behavior?

57 out of 200 fixtures (many attempts), so 1/4  of the tests consistently fail with 

```
 GeneralError: The Chrome 119.0.6045.159 / Debian 12.2 browser disconnected. If you did not close the browser yourself, browser performance or network issues may be at fault.
22:26:09         at BrowserConnection._createBrowserDisconnectedError (/usr/src/app/node_modules/testcafe/src/browser/connection/index.ts:318:16)
22:26:09         at Timeout._onTimeout (/usr/src/app/node_modules/testcafe/src/browser/connection/index.ts:326:30)
22:26:09         at listOnTimeout (node:internal/timers:569:17)
22:26:09         at processTimers (node:internal/timers:512:7) {
22:26:09       code: 'E1002',
22:26:09       data: [ 'Chrome 119.0.6045.159 / Debian 12.2' ]``
```

### What is the Expected behavior?

no errors

### What is the public URL of the test page? (attach your complete example)

-

### What is your TestCafe test code?

standard usecases, nothing special

### Screenshots

-

### Steps to Reproduce

-

### TestCafe version

3.4.0

### Node.js version

18.16

### Command-line arguments

-

### Browser name(s) and version(s)

Chrome

### Platform(s) and version(s)

 Debian 12.2

### Other

-

**Comment by Makavelic** [comment]
In-case this doesn't automatically get closed, this is also my experience with native automation. Even worse, sometimes the browser loses connection mid test and testcafe doesn't know how to recover so our jenkins times out, not testcafe. In our case its in a windows environment. The failures are not consistent on my end so I couldn't debug further, OP hopefully you have better luck getting them a sample they can investigate :).
