### ISSUE TITLE
Set Babel dependancies to a certain version, not point to the latest version

### ISSUE THREAD

**Issue by gforepsly** [DevExpress/testcafe#8091]
### What is your Scenario?

When @babel/plugin-transform-runtime version 7.23.4 came out, we couldn't run testcafe tests because of some weird runtime error. The error was:

TypeError: [BABEL] /opt/TeamCityAgent/work/47767e15a36475f9/node_modules/@babel/plugin-transform-runtime/lib/babel-7/polyfills.cjs: _index2.createPolyfillPlugins is not a function (While processing: "base$0") (While processing: "base$0")
08:45:25       at Object.<anonymous> 

Basically it pointed to 1 of our helper files which we import into tests, which imports axios. It's not possible to reproduce when trying a new, fresh testcafe project, so I guess it's something deeper in our structure. 
But, hardcoding version of @babel/plugin-transform-runtime version to version 7.22.15 in our package.json as a dev devependency solved the issue.

I managed to check the package-lock.json and noticed testcafe uses latest version when you run npm i testcafe as a dependancy ("@babel/plugin-transform-runtime": "^7.12.1").
Is it possible to hardcode only 1 working version as a testcafe dependancy so we don't run into this kind of issues in the future?

### What is the Current behavior?

When Babel package gets new version, there is a possibility that running testscafe stops working in certain scenarios because testcafe uses latest dependacy of babel npm packages

### What is the Expected behavior?

It should be better to use only 1 version and update to another when needed.

### What is the public URL of the test page? (attach your complete example)

No public URL, simply a comment on the dependandcies policy

### What is your TestCafe test code?

Explained in the first step

### Steps to Reproduce

1. Basically just run the test in certain conditions and the code never gets compiled properly

### TestCafe version

3.4.0

### Node.js version

18.18.0

### Command-line arguments

testcafe testName.ts

### Browser name(s) and version(s)

chrome latest

### Platform(s) and version(s)

MacOS Ventura 13.1 or any Windows machine

**Comment by mokone91** [comment]
same issue with latest @babel/plugin-transform-runtime

**Comment by gforepsly** [comment]
> same issue with latest @babel/plugin-transform-runtime

Do you maybe have some simple code example to replicate this? I can't share my whole complex repo for this one, too much sensitive data.

**Comment by ayemelyanenko-chegg** [comment]
I managed to reproduce the issue.

Please clone this [sample repository,](https://github.com/ayemelyanenko-chegg/sample-axios-testcafe.git) 
run `yarn install` 
and then from root, run
`yarn testcafe chrome sampleTest.ts `

And this error will show up

<img width="562" alt="Screenshot 2023-12-08 at 3 04 47 PM" src="https://github.com/DevExpress/testcafe/assets/14633459/801e9666-3515-424c-ba4b-ced3243ec4bd">

**Comment by PavelMor25** [comment]
While we are investigating the issue, you can override the version of @babel/plugin-transform-runtime through resolutions if you are using Yarn or through the overrides section if you are using npm.

**Comment by Humberto1945** [comment]
Hi, Thanks for the advice! Looks like I am still having the issue though. Did you remove the override?

**Comment by gforepsly** [comment]
> Hi, Thanks for the advice! Looks like I am still having the issue though. Did you remove the override?

We did not, we still have the override like I explained we have it. Fortunately everything works fine for us. I hope the Testcafe team will fix it soon, this is a nasty issue.

**Comment by Humberto1945** [comment]
Very nasty issue not being able to run tests.  I hope they are able to fix this soon as well.

**Comment by Humberto1945** [comment]
Just reverted to 3.3.0
