### ISSUE TITLE
Regex condition for Quarantine Mode

### ISSUE THREAD

**Issue by vasilyevi** [DevExpress/testcafe#8094]
### What is your Scenario?

Would like to re-run only tests with a particular text in the issue.

### What are you suggesting?

Add regex as condition

**Comment by AlexKamaev** [comment]
We don't see the need for such functionality. You can split your tests into two parts by using [different filtering mechanisms](https://testcafe.io/documentation/403436/guides/intermediate-guides/metadata-and-filtering). Then, you can apply quarantine settings only to a specific part of your tests.

**Comment by vasilyevi** [comment]
First of all if you're executing the full regression you don't need to split unstable tests into separate executions. The second, testcafe proxy is not stable sometimes. I have failed tests because testcafe cannot open the site at all frequently. Usually 2-3 tests are failed because of that when execution 300+ tests. No such issue with CDP, but I cannot use CDP for mobile browsers and would like to re-run tests which fail because of such issues. Please think about it

**Comment by AlexKamaev** [comment]
We agree that the TestCafe proxy can be unstable for different reasons. However, I still do not understand why it's required to apply quarantine mode only for specific tests. If you have 300+ tests and only 2-3 of them failed, only these failed tests will rerun even if you apply quarantine mode on the whole task.
Please describe your usage scenario in greater detail. Why do you need to filter tests before you apply quarantine mode on them?
You can find more info about Quarantine Mode here: [https://testcafe.io/documentation/403841/guides/intermediate-guides/quarantine-mode](https://testcafe.io/documentation/403841/guides/intermediate-guides/quarantine-mode)

**Comment by vasilyevi** [comment]
the whole run might have tests which fail due to bug in the AUT, I don't want to re-run them and the tests are iun general stable, but testcafe proxy is not. Why do I need to re-run 10 tests which are failed due to existing bug in the AUT and dev team is working on them, but DO NOT test functionality at all just because of testcafe proxy instability?

**Comment by AlexKamaev** [comment]
Thank you for the detailed explanation; now we understand your position. We cannot take this enhancement into work, since currently, we are completely focused on other tasks.  **We may reconsider this task's priority in the future if we get requests for it.** However, if you want you can make a PR with the described functionality. We will review and accept it if everything is OK.
