### ISSUE TITLE
Failed to load OpenUI5/SAPUI5 core.js in proxy mode

### ISSUE THREAD

**Issue by tandreys** [DevExpress/testcafe#8098]
### What is your Scenario?

After updating to latest version of SAP UI5, tests that need to run in proxy mode (because on multiple windows) are failing.
Because Testcafe is affecting the load on ui5 core.js.
Browser console is showing errors.

In native automation, there is no issue. But test need to handle 2 windows so I need to disableNativeAutomation

### What is the Current behavior?

page is not loading

### What is the Expected behavior?

page to load normally

### What is the public URL of the test page? (attach your complete example)

https://sdk.openui5.org/test-resources/sap/ui/core/demokit/tutorial/navigation/17/webapp/index.html?sap-ui-theme=sap_horizon#/employees

### What is your TestCafe test code?

test('checkcell', async t => {
    await t.navigateTo("https://sdk.openui5.org/test-resources/sap/ui/core/demokit/tutorial/navigation/17/webapp/index.html?sap-ui-theme=sap_horizon#/employees");
    await t.maximizeWindow( );
 
   await t.click("#__item0-container-nav---employeeList--employeeList-0");

    await t.debug();
});

### Your complete configuration file

{
    "selectorTimeout": 60000,
    "pageLoadTimeout": 60000,
    "pageRequestTimeout": 60000,
    "assertionTimeout": 15000,
    "browserInitTimeout": 180000,
    "speed": 1,
    "disableNativeAutomation": true,
    "debugOnFail": false,
    "skipJsErrors": true,
    "reporter": [
        {
            "name": "xunit",
            "output": "reports/report.xml"
        },
        {
            "name": "json",
            "output": "reports/report.json"
        }
    ]
}

### Steps to Reproduce

just run the test

### TestCafe version

3.4

### Node.js version

18.17.1

### Command-line arguments

testcafe "chrome" test.js

### Browser name(s) and version(s)

Chrome 117,119, 120beta

### Platform(s) and version(s)

Ubuntu 22, Windows 11

**Comment by tandreys** [comment]
Issue is not fixed in Testcafe 3.5.
core.js is still not loading
Can you reopen the issue?

**Comment by Bayheck** [comment]
Thank you for your request. 
We are aware of this issue and we already fixed it in the next release.
In the meantime, try using [TestCafe v3.5.0](https://testcafe.io/404732/release-notes/framework/2023-12-28-testcafe-v3-5-0-released#experimental-run-multi-window-tests-with-native-automation) ‘--experimental-multiple-windows’ mode in Native Automation. Please try this and let us know if you encounter any issues.

**Comment by bhassane73** [comment]
--experimental-multiple-windows’ within v3.5.0 don't fix the issue.
