### ISSUE TITLE
Access to testRunInfo in testRun before and after hooks

### ISSUE THREAD

**Issue by codambro** [DevExpress/testcafe#8106]
### What is your Scenario?

I would like to access the `testRun` object within the testRun before/after hooks. My specific use case is I have some setup that only needs to be run if certain test fixtures are executed, and I need the testRun info to be able to determine what fixtures are run.

### What are you suggesting?

the `fixture.before` global hook takes two arguments:
`async (ctx, fixtureInfo) => {}`

But the `testRun.before` global hook only takes 1:
`async ctx => {}`

I believe the testRun before hook should be the same as the fixture level hooks:
`async (ctx, testRunInfo) => {}`

### What alternatives have you considered?
Parsing command line args

### Additional context
Realize I don't know exactly where in `testRunInfo` the tests would be or if that info even exists

**Comment by PavelMor25** [comment]
Hello @codambro,

What information do you expect to retrieve from `testRunInfo`? 

Please describe your usage scenario in greater detail. There might already be an existing functionality or workaround in TestCafe that aligns with your scenario.

**Comment by codambro** [comment]
Hello. Yeah I think I realized testRunInfo may not even have what I need. 

I'm defining a global testRun.before hook that sets something up for specific tests to use. But it takes a long time to run. So I only want to set it up if one or more of the specific tests is being executed in the testRun. 

Ideally in testRun.before I can determine which exact tests are part of the run, including with respect to .meta filtering, along with .skip and .only modifiers.

**Comment by PavelMor25** [comment]
Perhaps, this workaround can solve the issue or allow you to create your own solution:

```javascript
module.exports = {
    hooks: {
        test: {
            before: async t => {
                const testfile = t.testRun.test.testFile;
            }
        },
    },
};
``` 
From the `testFile`, you can access the following information:

- `.collectedTests`: a list of tests from the current test file. From each list item, you can get information such as `meta`, `name`, `only`, and `skip`;
- `.currentFixture`: information about the current fixture with the same properties as the test item from `collectedTests`.

However, It's not part of our public API and can be changed at any time. Please use it with caution.

**Comment by codambro** [comment]
Thanks for the suggestion. Unfortunately it wouldn't help since I need the information at the start of the testRun and not at the start of each individual fixture.

**Comment by PavelMor25** [comment]
We can consider your enhancement request, but we need to understand if this enhancement has practical application. Please describe how it should work and provide a detailed example of how this enhancement would be applied in practice.

**Comment by codambro** [comment]
Found a sufficient workaround. Sharing in case others have similar issues. I'm using the createRunner API with a filter function. In there, I'm tracking what tests would run.

```
export const testRunTests = [];

async function filterFn(testName, fixtureName, fixturePath, testMeta, fixtureMeta) {
  // Some logic to return true if test should run, false otherwise
  // ...
  
  // Before returning true, add test to testRun list
  testRunList.push(`${fixtureName}.${testName}`);
  return true;
}

const runner = testcafe.createRunner();
runner.filter(filterFn);
```

Then my testRun hook functions can call that in testcaferc.js:
```
const { testRunTests } = require("../testcafeRunner");

module.exports = {
  hooks: {
    testRun: {
      before: async ctx => {
        if (testRunTests.includes("someFixtureName.someTestName")) {
          // perform slow, test specific setup
        }
      }
    }
  }
}

```
