### ISSUE TITLE
SyntaxError when running scripts after angular update

### ISSUE THREAD

**Issue by PatatN7** [DevExpress/testcafe#8108]
### What is your Scenario?

When I test our site manually there are no javascript errors, but getting an error when trying to run scripts after angular update 14 > 15

Skip JSErrors also did not help.

### What is the Current behavior?

When the scripts are ran, the site shows our loading spinner, but then errors with a Javascript error SyntaxError: Unexpected token ';'

### What is the Expected behavior?

No error and website loads

### What is the public URL of the test page? (attach your complete example)

Its an angular SPA

I can unfortunately not share our testing environment URL and the angular update is not on Production yet

### What is your TestCafe test code?

import { Selector } from 'testcafe'
import adminLogin from '../../../page_models/admin/login'

// Test Data
const adminEmail = '[jane@foo.co.za](mailto:jane@foo.co.za)'
const adminPassword = 'ipsum'

fixture('Example Fixture')
.page(adminLogin.staging)

test('Example Test', async (t) => {
// Resize window
await t.resizeWindow(1280, 720)

// Login
await adminLogin.login(adminEmail, adminPassword)
}

### Your complete configuration file

module.exports = {
assertionTimeout: 30000,
selectorTimeout: 30000,
pageLoadTimeout: 30000,
disableNativeAutomation: true,
ssl: {
pfx: 'testcafeCert.pfx',
rejectUnauthorized: true,
passphrase: process.env.CERT_PASSPHRASE,
},
hostname: 'localhost',
browsers: 'chrome:headless --allow-insecure-localhost',
}

### Your complete test report

× Example Test

A JavaScript error occurred on "http://localhost:4200/".
Repeat test actions in the browser and check the console for errors.
Enable the “skipJsErrors” option to ignore JavaScript errors during test execution. Learn more: "https://testcafe.io/documentation/404038/recipes/debugging/skip-javascript-errors"
If the website only throws this error when you test it with TestCafe, please create a new issue at:
"https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

JavaScript error details:
SyntaxError: Unexpected token ';'

Browser: Chrome 120.0.0.0 / Windows 10

13 | adminLogin.staging,
14 |)
15 |
16 |test('Example Test', async (t) => {
17 | // Resize window

18 | await t.resizeWindow(1280, 720)
19 |
20 | // Login
21 | await adminLogin.login(adminEmail, adminPassword)
22 |}

### Screenshots

![image](https://github.com/DevExpress/testcafe/assets/86985863/8708467a-aec7-43db-b679-970415f5d1d2)

### Steps to Reproduce

I have tried reproducing this with new projects, but unfortunately was not able to replicate

### TestCafe version

v3.4.0

### Node.js version

v18.13.0

### Command-line arguments

testcafe "chrome --allow-insecure-localhost" --hostname localhost .\path\to\test\myTest.js

### Browser name(s) and version(s)

Chrome 120.0.6099.130

### Platform(s) and version(s)

Windows 10 22H2 (Build 19045.3803)

### Other

This error occours with any TestCafe command-line arguments I use

Also other browsers and platforms (Linux and iOS)

**Comment by Bayheck** [comment]
Hello, thank you for reaching out to us.
Unfortunately, it's difficult to determine the cause of the issue without a sample.
 
I noticed that you enable the `disableNativeAutomation` option in your configuration file. Could you please remove this option and run tests in Native Automation mode if possible?
 
If this does not help, I believe we still need an example to research the issue further.
