### ISSUE TITLE
RequestLogger gzip response body corrupted in Native Automation

### ISSUE THREAD

**Issue by codambro** [DevExpress/testcafe#8114]
### What is your Scenario?

Trying to log all requests and responses using RequestLogger. Some responses are gzip bodies. I am unable to unzip them when running with native automation.

### What is the Current behavior?

Trying to unzip compressed response bodies fails with native automation

### What is the Expected behavior?

body unzips normally

### What is the public URL of the test page? (attach your complete example)

https://testkenna.kennasecurity.com/users/sign_in

### What is your TestCafe test code?

```
import { RequestLogger } from "testcafe";
import zlib from "zlib";

const url = "https://testkenna.kennasecurity.com/users/sign_in";

// create and attach request logger
const requestLogger = RequestLogger(url, { logResponseHeaders: true, logResponseBody: true })

fixture("Fixture").requestHooks(requestLogger);

test("Test", async t => {
    // go to URL that gives gzip response and wait for it to load
    await t.navigateTo(url);
    await t.wait(3000);

    // verify response status 200 and header indicates gzip
    const resp = requestLogger.requests[0].response;
    await t.expect(resp.statusCode).eql(200);
    await t.expect(resp.headers["content-encoding"]).eql("gzip");

    // decompress body
    const buffer = resp.body;
    const decoded = zlib.gunzipSync(buffer);
    console.log(decoded.toString());
})
```

With Native Automation:
```
 Fixture
 ✖ Test (screenshots:
 /Users/codambro/Documents/GitHub/KennaSecurity/qa-automation-e2e/results/screenshots/Chrome_120.0.0.0_macOS_10.15.7/Fixture_Test_1.png)

   1) Error: incorrect header check

      Browser: Chrome 120.0.0.0 / macOS 10.15.7
      Screenshot:
      /Users/codambro/Documents/GitHub/KennaSecurity/qa-automation-e2e/results/screenshots/Chrome_120.0.0.0_macOS_10.15.7/Fixture_Test_1.png
```

With `disableNativeAutomation: true`
```
Fixture

<!DOCTYPE html>
<html lang="en">
  <head>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,600' rel='stylesheet' type='text/css'>

<meta charset="utf-8">


<title>Cisco</title>
...
... 
...
  </body>
</html>

 ✓ Test


 1 passed (9s)
```

### Steps to Reproduce

see above

### TestCafe version

3.5.0

### Command-line arguments

using testcafe runner api

### Browser name(s) and version(s)

chrome

### Platform(s) and version(s)

macOS

**Comment by Bayheck** [comment]
Hello,
I managed to reproduce the issue. As a workaround, you can use `stringifyResponseBody` in [RequestLogger](https://testcafe.io/documentation/402769/reference/test-api/requestlogger/constructor) Constructor options. Please try this solution and let us know if you encounter any issues.

**Comment by codambro** [comment]
Interesting. With `disableNativeAutomation`, using `stringifyResponseBody` returned garbage data since it was gzip. But I do see `stringifyResponseBody` does return the correct string format. good to know
