### ISSUE TITLE
maximizeWindow does not work on mac os 14.2.1

### ISSUE THREAD

**Issue by vasilyevi** [DevExpress/testcafe#8117]
### What is your Scenario?

t.maximizeWindow()

### What is the Current behavior?

does not work

### What is the Expected behavior?

window have to be maximized

### What is the public URL of the test page? (attach your complete example)

N/A

### What is your TestCafe test code?

t.maximizeWindow()

### Steps to Reproduce

t.maximizeWindow()

### TestCafe version

3.5.0

### Node.js version

v18.17.0

### Command-line arguments

npx testcafe

### Other

Could you add unit tests it's not a first time

**Comment by PavelMor25** [comment]
Hello @vasilyevi ,

I can't reproduce the issue on macOS 10.15.7 and 13.6.3 with TestCafe v3.5.0.

Regarding the tests, they're available for the entire main API, including `maximizeWindow`.

**Comment by vasilyevi** [comment]
10.15.7?
Im using Sonoma 14.2.1 (23C71)

**Comment by PavelMor25** [comment]
Hello,
I attempted to run the test with the maximizeWindow() method on Sonoma 14.12.1 (Chrome 120.0.0 / Safari 17.2) and observed the expected behavior. Currently, we cannot determine the issue. If you have any information that can help us reproduce the issue, please share it.



![photo1705901661](https://github.com/DevExpress/testcafe/assets/77216072/0e7d8ad2-413f-4290-a15a-bc73010c5789)

**Comment by vasilyevi** [comment]
did you try chrome headed mode?

**Comment by AlekseyKravtsov17** [comment]
I have the same issue on windows 10 with TestCafe v3.5.0

**Comment by vasilyevi** [comment]
@PavelMor25 try with headed mode.
I use the same chrome Chrome 120.0.0.0 / Sonoma 14
maybe node version is also important? my is v18.17.0

**Comment by PavelMor25** [comment]
@vasilyevi, I tried to reproduce it in Chrome 120.0.0.0 / Sonoma 14 / Node v18.17.1 in both headed and headless modes. Everything works as expected. Could you record the entire test run process? It might help us investigate the issue.

@AlekseyKravtsov17, could you please specify the browser in which you encounter the issue and the version of Node.js you are using?

**Comment by AlekseyKravtsov17** [comment]
@PavelMor25 I also use Chrome 120.0.0.0 and Node v16.17.0

**Comment by vasilyevi** [comment]
[maximizeWindow.zip](https://github.com/DevExpress/testcafe/files/14036426/maximizeWindow.zip)
npm install
npx testcafe

Try it out

**Comment by vasilyevi** [comment]
@PavelMor25

**Comment by vasilyevi** [comment]
Give me the email where I can send the recording

**Comment by PavelMor25** [comment]
Hello @vasilyevi, I was able to reproduce the issue from your example.

For the team: Some test controller methods don't work in the `beforeEach` fixture hook.

@AlekseyKravtsov17, are you also using `maximizeWindow` in the `beforeEach` fixture hook?

**Comment by AlekseyKravtsov17** [comment]
@PavelMor25 yes, I have the same test scenario as @vasilyevi

**Comment by vasilyevi** [comment]
@PavelMor25 please add tests on that also. When we can expect a fix?

**Comment by PavelMor25** [comment]
Hello @vasilyevi,
We add a test for each fix or new functionality. We are working on this issue. However, we cannot give you any estimates on when the issue is fixed.

**Comment by Raydir** [comment]
same here with resize - glad you found it already :D

**Comment by PavelMor25** [comment]
Hello @Raydir,

Thank you for sharing this information. If your usage scenario is different, please share a [minimal working example](https://testcafe.io/documentation/402636/faq/general-info?search#how-to-create-a-minimal-working-example-when-you-submit-an-issue) with us.

**Comment by Raydir** [comment]
hm.. i had the same behaviour in beforeEach with Testcafe 3.5.0
For me "resize" and "maximize" did not work.

**However:**
I deleted all nodemodules and package-lock.json and after reinstalling 3.5.0 new and now it does work again for me.

Sorry for the missing minimal working example.

**Comment by vasilyevi** [comment]
Are you going to release the fix?

**Comment by Bayheck** [comment]
Hello,

We cannot give you an ETA for when we will release this fix. Hopefully, it will be in the next TestCafe release.

**Comment by vasilyevi** [comment]
does not work with node 20, but worked with node 18

**Comment by PavelMor25** [comment]
Hello @vasilyevi,

I couldn't reproduce the issue with Node 20.

Could you please create a separate ticket and provide more details? Specifically:

- Configuration
- macOS version
- Exact Node.js version
- Any additional information that might help us reproduce the issue
