### ISSUE TITLE
Implement `t.maximizeWindow`

### ISSUE THREAD

**Issue by kirovboris** [DevExpress/testcafe#812]
# Feature summary

### maximizeWindow (browserId)
Maximizes the browser window `browserId`.

**Comment by inikulin** [comment]
@kirovboris Can you provide use cases, please?

**Comment by kirovboris** [comment]
I have several different sites in my test directory. For one of them i use ```t.resizeWindow```, e.g. for checking adaptive content. After that i should restore window size for another sites. Let's say window size is ```1920*1080```. After that i want to run test on the virtual machine with another screen resolution and now i should use the condition or something like that and it makes my test not flexible.

**Comment by inikulin** [comment]
So if we'll just restore size of the window to the initial (maximized) before each test run it will work for you?

**Comment by kirovboris** [comment]
Yes, it sounds good.

**Comment by inikulin** [comment]
OK, I'll rename the issue and move it to planned.

**Comment by inikulin** [comment]
After some discussion, we've decided to move to the original proposal

**Comment by AndreyBelym** [comment]
## Browser provider API changes

### maximizeWindow (browserId)
Maximizes the browser window `browserId`.
