### ISSUE TITLE
Testcafe slow compile time with big project

### ISSUE THREAD

**Issue by Makavelic** [DevExpress/testcafe#8136]
### What is your Scenario?

This relates to [issue 4054](https://github.com/DevExpress/testcafe/issues/4054)

The provided solution does not work for our repo. Our page classes more often than not take a mandatory constructor for re-use purposes in order to act as the base selector. For example, we use checkboxes everywhere in the product but in order to select the correct one we first need to scope it to a container selector. 

Additionally, page classes are often the ones actually constructing the new pages (because they often derive the selector required to pass into the constructor). Think something like  `async clickButton: Promise<SomeNewPage`>. Because of this dynamic nature, we can't simply do something like `export default new PageClass();`

Based on my debugging the long compile time occurs here:

node_modules\testcafe\lib\compiler\index.js -> _compileTestFiles.

The browser to run the tests only opens once this compile step is done.

I have no idea how to debug further to figure out how to optimize this or whether anything is configurable.

Our repo has over 2000 tests and 500 page classes and continues to grow. Currently our tests can take any where from 30 seconds to 3 minutes just to open the browser (depending on machine specs but also can sometimes vary by 30 seconds between runs on the same machine some reason). 

Is there anyway to create some sort of cache between test runs so we don't need to wait every single time we run a test?

Also just a FYI I am aware of this guide:
https://testcafe.io/documentation/402963/guides/best-practices/speed-up-test-execution#optimize-your-page-model

but I don't think its realistic for our use case. We can't have tests that test pages in isolation - we're testing e2e and need to navigate from page to page. As a result, our test files will always need multiple page objects.

### What is the Current behavior?

Tests take too long to open the browser (due to _compileTestFiles)

### What is the Expected behavior?

_compileTestFiles should be faster

### What is the public URL of the test page? (attach your complete example)

See https://github.com/DevExpress/testcafe/issues/4054

### What is your TestCafe test code?

See https://github.com/DevExpress/testcafe/issues/4054

### Steps to Reproduce

1. Run tests
2. Compile time takes long

### TestCafe version

3.5.0

### Node.js version

18.18.2

### Command-line arguments

testcafe 'chrome' 'path\testName.ts' '-c' '1' '--test' 'test1'

**Comment by PavelMor25** [comment]
Hello @Makavelic,

You can use the `--esm` option to run the test. This should reduce the load on the compiler.

> we're testing e2e and need to navigate from page to page. As a result, our test files will always need multiple page objects.

Also, could you please share a project with several examples that cover the usage scenario you described? This will allow the TestCafe team to research it and look for a workaround.

**Comment by di5ko** [comment]
Might be a bit off-topic, but for me it's a similar case of E2E testing with multiple pages. I *am* using the page model for a better structure of my code (selector re-use, organisational benefits, etc), even though I understand from the documentation that I cannot expect speed benefits by doing so.

I cannot share a project, but basically it's a document library with tests that start on the homepage (`homepage` page model), login here, go to the search page (`search` page model), then do all kinds of search queries and eventually end up clicking a document (`document` page model).
