### ISSUE TITLE
TestCafe useRole hangs test execution

### ISSUE THREAD

**Issue by SwetaBhadani** [DevExpress/testcafe#8144]
### What is your Scenario?

I am trying to move my login to UseRoles to reduce the execution time of the tests. 
Using Roles to skip multiple login attempts for individual test

### What is the Current behavior?

The test stops when executing useRole (be it inside individual test or before each)

### What is the Expected behavior?

The tests should run with useRoles

### What is the public URL of the test page? (attach your complete example)

https://www.saucedemo.com/

### What is your TestCafe test code?

import { Selector, Role } from 'testcafe';

const role = Role('https://www.saucedemo.com/', async t => {
    await t
        .typeText(Selector('[data-test="username"]'), 'standard_user')
        .typeText(Selector('#password'), 'secret_sauce')
        .click(Selector('#login-button'))

}, { "preserveurl": true});

fixture`My fixture`
    .page`https://www.saucedemo.com/`
    .beforeEach(async t => {
        await t.useRole(role);
    });

test('test1', async t => {
    console.log('starting test 1');
    await t
        .click(Selector('#react-burger-menu-btn'));
    console.log('finished test 1');
});

test('test2', async t => {
    console.log('starting test 2');
    await t
        .click(Selector('#react-burger-menu-btn'))
        .click(Selector('a').withText('About'));
    console.log('finished test 2');
});

### Your complete configuration file

module.exports = {
    "src": "tests"
}

### Your complete test report

swetabhadani@Rahuls-MacBook-Air TestCafeProject % testcafe -d chrome tests/test1.js         
Using locally installed version of TestCafe.
The "src" option from the configuration file will be ignored.
 Running tests in:
 - Chrome 121.0.0.0 / Big Sur 11

 My fixture

----
Chrome 121.0.0.0 / Big Sur 11
DEBUGGER PAUSE:
13 |    .beforeEach(async t => {
> 14 |        await t.useRole(role);
15 |    });
----

### Screenshots

![Screenshot 2024-02-20 at 12 40 00 PM](https://github.com/DevExpress/testcafe/assets/68321175/2f6b704c-1a8c-4291-9a7b-4a2a2c196c27)
![Screenshot 2024-02-20 at 12 40 14 PM](https://github.com/DevExpress/testcafe/assets/68321175/0712f0d7-61bb-431d-971d-b24edfacd95e)

### Steps to Reproduce

1. run => testcafe chrome tests/test1.js (test1.js being the testcafe code pasted above)

### TestCafe version

3.5.0

### Node.js version

v20.11.0

### Command-line arguments

testcafe chrome tests/test1.js

### Browser name(s) and version(s)

Chrome 121

### Platform(s) and version(s)

macOS 11.4

**Comment by Bayheck** [comment]
Hello,

The issue is similar to this one: [https://github.com/DevExpress/testcafe/issues/8123](https://github.com/DevExpress/testcafe/issues/8123). It is caused by the 'service worker'.

As a workaround, you can run your test as follows:


import { Selector, Role } from 'testcafe';

 

const role = Role('[https://www.saucedemo.com/'](https://www.saucedemo.com/%27), async t => {

await t

.typeText(Selector('[data-test="username"]'), 'standard_user')

.typeText(Selector('#password'), 'secret_sauce')

.click(Selector('#login-button'))

 

}, { "preserveurl": true});

 

fixture`My fixture`

.page`[https://www.saucedemo.com/`](https://www.saucedemo.com/%60)

.beforeEach(async t => {

    const idConnection = t.testRun.browserConnection.id;

    const cdpClient    = t.testRun.browserConnection.getNativeAutomation(idConnection)._client;

    await cdpClient.Network.setBypassServiceWorker()

    await t.useRole(role);

});

 

test('test1', async t => {

    await t.navigateTo(`/inventory.html`) // or [https://www.saucedemo.com/inventory.html](https://www.saucedemo.com/inventory.html)

    await t.click(Selector('#react-burger-menu-btn'))

        .click(Selector('a#reset_sidebar_link'))

        .click(Selector('#shopping_cart_container'));

});

**Comment by SwetaBhadani** [comment]
Thank you Adil
