### ISSUE TITLE
Headless test execution failing while passing  successfully without headless.

### ISSUE THREAD

**Issue by testcafe-HK** [DevExpress/testcafe#8152]
### What is your Scenario?

I am trying to run test in headless mode but getting following error .I have increased the timeout but still failing .It is working fine when headless mode is off. Testcafe version : 3.5.0
The command I ran is 
testcafe chrome:headless mytest.js 

### What is the Current behavior?

I am getting an error
 Increase the value of the "pageRequestTimeout" variable, enable the "retryTestPages" option, or use
      quarantine mode to perform additional attempts to execute this test.
      You can find troubleshooting information for this issue at
      "https://go.devexpress.com/TestCafe_FAQ_ARequestHasFailed.aspx".

      Error details:
      Failed to find a DNS-record for the resource at

### What is the Expected behavior?

It should run without any error like it is running without headless.

### What is the public URL of the test page? (attach your complete example)

http://testurl.com
this a fake url I can not share private url

### What is your TestCafe test code?

fixture('testing a new feature').page("http://testingurl.com");

test('run new test') , async t =>{

//here is my source code I can not share

})

### Steps to Reproduce

1.runing the test in headless it is failing
2.
3.

### TestCafe version

3.5.0

### Node.js version

18.1

### Command-line arguments

testcafe chrome:headless test.js

### Browser name(s) and version(s)

chrome 122

### Platform(s) and version(s)

windows 10

**Comment by testcafe-HK** [comment]
Hi 
Due to security reason I can not copy the code let me explain steps .As I said It is working fine without headless
1. The test is failing in fixture('test something').page("http://onboardutility.com")
2. I am getting this url  after it failed in error message so it is surrounded by amazoncognito
. **https://56062851220898xxxxxxxxxx.auth.us-east-1.amazoncognito.com/oauth2/authorize?client_id=998989932jeiq&redirect_uri=**https%3A%2F%2Fvehicl-ooard-portal.fcl-02.prep.com**%2Foauth2%2Fidpresponse&response_type=code&scope=openid%20integration.fcl.fcagcv.com%2FManager&state=9Wbsls%2FJ4x6U8KgNmoR7AZ%2FKQzVEe8viofW0Q%3D%3D**

Now you can have idea why it is failing in headless mode

**Comment by testcafe-HK** [comment]
**Source code is ..**

import { Selector} from 'testcafe';

const vinDetails = require("../../resource/nafta.json");

import {setUserId,assosiateVinStatus,getUserId,report,selfManageToken} from "../util/sendRequest"
import common from "../util/common";

fixture('Generating VIN...')
.page(vinDetails.url);


test('For nafta and emea region ', async t =>{
   let vinNumber =await common.vehicleOnBoard(t);  
    let email = await common.enrollment(t);
   console.log(email);
   const token = await selfManageToken(t);
   let UID =await setUserId(t,email);
   await assosiateVinStatus(t,token,UID,vinNumber);
   await report(t,email,vinNumber,UID);
   let correctVin = await common.globalCSI(t,vinNumber);
   console.log(correctVin);
}).timeouts({
   pageLoadTimeout:    2000,
   pageRequestTimeout: 60000,
   ajaxRequestTimeout: 60000,
})


**Execution result**


testcafe chrome:headless   vin.js -q --skip-js-errors --brand=FIAT --region=emea
 Running tests in:
 - Chrome 122.0.6261.95 / Windows 10

 Generating VIN...
 × For nafta and emea region 

   1) Failed to load the page at

   "https://56062888888261234.auth.us-east-1.amazoncognito.com/oauth2/authorize?client_id=2iaou3irs5egk4m3or0o32jeiq&redirect_uri=https%3A%2F%2Fvehicle-onboard-portal.fcl-02.prep.fcagcv.com%2Foauth2%2Fidpresponse&response_type=code&scope=openid%20integration.fcl.fcagcv.com%2FManager&state=4jreAbYps6CDJOJVxK74vuhBERzn6ak6RnWTtWYTaNgm33RoW9HTWzmcO1SkGK0SJNNO3c7u%2F9kFMnjuH9xYivTZQ9H8Cz1u9K5YHzEQsIy%2BBORlPZWx8MEV6IYB%2B3yDdbCpZekMH8RTymj76kSkhqpVi9h5I06%2FksAraA%2BPTwKHAebcS%2FlsPuzYMsNDaigbbVmMcFlvqiBQ%3D%3D".
      Increase the value of the "pageRequestTimeout" variable, enable the "retryTestPages" option,     
      or use quarantine mode to perform additional attempts to execute this test.
      You can find troubleshooting information for this issue at
      "https://go.devexpress.com/TestCafe_FAQ_ARequestHasFailed.aspx".

      Error details:
      Error: Failed to find a DNS-record for the resource at

   "https://56062851220966261234.auth.us-east-1.amazoncognito.com/oauth2/authorize?client_id=2iaou3irs5egk4m3or0o32jeiq&redirect_uri=https%3A%2F%2Fvehicle-onboard-portal.fcl-02.prep.fcagcv.com%2Foauth2%2Fidpresponse&response_type=code&scope=openid%20integration.fcl.fcagcv.com%2FManager&state=4jreAbYps6CDJOJVxK74vuhBERzn6ak6RnWTtWYTaNgm33RoW9HTWzmcO1SkGK0SJNNO3c7u%2F9kFMnjuH9xYivTZQ9H8Cz1u9K5YHzEQsIy%2BBORlPZWx8MEV6IYB%2B3yDdbCpZekMH8RTymjapjUpamYGcv9%2FpW0raA%2BPTwKHAebcS%2FlsPuzYMsNDaigbbVmMcFlvqiBQ%3D%3D"

      Browser: Chrome 122.0.6261.95 / Windows 10

         109 |
         110 |const vehicleOnBoard = async (t) =>{
         111 |   // await isVisible(t,vinPage.label_tbm_Details,30000);
         112 |    await t
         113 |    //.maximizeWindow()
       > 114 |    .click(vinPage.eventType)
         115 |    .wait(2000)
         116 |    .click(vinPage.eventType.find('option').withText('New'))
         117 |    .click(vinPage.company)
         118 |    .click(vinPage.company.find('option').withText(vehicleDetails.company))
         119 |    .click(vinPage.TBMregion)

         at Object.<anonymous>
      (C:\Users\t123r5\Documents\Vins\VINUtility\src\util\common.js:114:6)
         at asyncGeneratorStep (C:\Users\t123r5\Documents\Vins\VINUtility\src\util\common.js:8:39)    
         at _next (C:\Users\t123r5\Documents\Vins\VINUtility\src\util\common.js:8:39)
         at <anonymous> (C:\Users\t123r5\Documents\Vins\VINUtility\src\util\common.js:8:39)
         at Object.<anonymous> (C:\Users\t123r5\Documents\Vins\VINUtility\src\util\common.js:8:39)    
         at Object.vehicleOnBoard [as vehicleOnBoard]
      (C:\Users\t123r5\Documents\Vins\VINUtility\src\util\common.js:110:21)
         at <anonymous> (C:\Users\t123r5\Documents\Vins\VINUtility\src\source\vin.js:13:32)
         at asyncGeneratorStep (C:\Users\t123r5\Documents\Vins\VINUtility\src\source\vin.js:6:37)     
         at _next (C:\Users\t123r5\Documents\Vins\VINUtility\src\source\vin.js:6:37)
         at <anonymous> (C:\Users\t123r5\Documents\Vins\VINUtility\src\source\vin.js:6:37)

**Comment by Bayheck** [comment]
Hello,

Thank you for the source code. Unfortunately, you did not share the files that this source code requires. Could you please zip all necessary files in one folder and share it?

Specifically, I am referring to these lines: 

const vinDetails = require("../../resource/nafta.json");

import {setUserId,assosiateVinStatus,getUserId,report,selfManageToken} from "../util/sendRequest"

import common from "../util/common";

**Comment by testcafe-HK** [comment]
Hi
This is the minimal source I make where it is failing . I can not attach it but I copied it here . url will not work as it's internal.
fixture('Generating VIN...')
.page("https://vehicle-onboard-portal..prep..com/");


test.only('For nafta and emea region ', async t =>{

   await t
    .maximizeWindow()
    .click(Selector('#eventType'))
    .wait(2000)
    .click( Selector('#eventType').find('option').withText('New'))
    .click(Selector('#company'))
    .click(Selector('#company').find('option').withText('FCA'))
    .click(Selector('#vehicleRegion'))
    .click(Selector('#vehicleRegion').find('option').withText('NAFTA'))
    .click(Selector('#TBMType'))
    .click(Selector('#TBMType').find('option').withText('Smart High'))
    .click('#feedType')
    .click(Selector("#feedType").find('option').withText("SHIPPING"));
    await t
     .click(Selector('#hardwareNumber'))
     .click(Selector('#hardwareNumber').find('option').withText('TBM2H Smart'));
})

**Error**
error is same as I mentioned above but this is the exact line where it is failing in this case even if I comment maximize windows it is failing in next line


Browser: Chrome 122.0.6261.95 / Windows 10

         27 |
         28 |
         29 |test.only('For nafta and emea region ', async t =>{
         30 |
         31 |   await t
       > 32 |    .maximizeWindow()
         33 |    .click(Selector('#eventType'))
         34 |    .wait(2000)
         35 |    .click( Selector('#eventType').find('option').withText('New'))
         36 |    .click(Selector('#company'))
         37 |    .click(Selector('#company').find('option').withText('FCA'))

**Comment by Bayheck** [comment]
Hello, this issue might be similar to this one: [https://github.com/DevExpress/testcafe/issues/8145](https://github.com/DevExpress/testcafe/issues/8145).

Try running your tests with

```
testcafe chrome headless=new test.js
```

Please let us know your results.

**Comment by testcafe-HK** [comment]
Hi @Bayheck 

I used above command but it is not running in headless mode .it is opening the browser and finishing the test. I want to run the test in headless mode .I tried with edge browser but same result.

"https://56062888888261234.auth.us-east-1.amazoncognito.com/oauth2/authorize?client_id=2iaou3irs5egk4m3or0o32jeiq&redirect_uri=https%3A%2F%2Fvehicle-onboard-portal.fcl-02.prep.fcagcv.com%2Foauth2%2Fidpresponse&response_type=code&scope=openid%20integration.fcl.fcagcv.com%2FManager&state=4jreAbYps6CDJOJVxK74vuhBERzn6ak6RnWTtWYTaNgm33RoW9HTWzmcO1SkGK0SJNNO3c7u%2F9kFMnjuH9xYivTZQ9H8Cz1u9K5YHzEQsIy%2BBORlPZWx8MEV6IYB%2B3yDdbCpZekMH8RTymj76kSkhqpVi9h5I06%2FksAraA%2BPTwKHAebcS%2FlsPuzYMsNDaigbbVmMcFlvqiBQ%3D%3D".
Increase the value of the "pageRequestTimeout" variable, enable the "retryTestPages" option,
or use quarantine mode to perform additional attempts to execute this test.
You can find troubleshooting information for this issue at
"https://go.devexpress.com/TestCafe_FAQ_ARequestHasFailed.aspx".

**Comment by Bayheck** [comment]
Hello,

I apologize for any confusion. I meant testcafe 'chrome --headless=new' test.js - pay attention to the quotes.

I understand that due to security reasons, you can not copy your code. However, I am asking you to create a minimal working example that we can reproduce on our end. Without this working sample with a working url, we can not effectively help you.

In addition, could you please try 'retryTestPages' or use quarantine mode to perform additional attempts to execute this test and share the results with us?

[https://testcafe.io/documentation/402638/reference/configuration-file?search#retrytestpages](https://testcafe.io/documentation/402638/reference/configuration-file?search#retrytestpages)
[https://testcafe.io/documentation/403841/guides/intermediate-guides/quarantine-mode](https://testcafe.io/documentation/403841/guides/intermediate-guides/quarantine-mode)
