### ISSUE TITLE
Request hooks - Redirect responses are not captured

### ISSUE THREAD

**Issue by csaundersz** [DevExpress/testcafe#8155]
### What is your Scenario?

I want to assert that the correct redirect is performed when a link that executes a download is clicked.

I'm using a request logger to assert this.

### What is the Current behavior?

1. The `.response` on the request is undefined
2. `.contains()` on the request logger doesn't return the request because it is deemed incomplete because the response was not captured

### What is the Expected behavior?

`.response` on the request from the request logger should capture the redirect response.

### What is the public URL of the test page? (attach your complete example)

Using youtube.com -> www.youtube.com as the example.

### What is your TestCafe test code?

```
testcafe chrome test.js
```

```javascript
import {RequestLogger, Selector} from 'testcafe';

const requestLogger = RequestLogger({ url: /youtube\.com\/$/, method: 'GET' });

fixture `Getting Started
    .requestHooks(requestLogger)
    .page(`https://youtube.com`)
    .after(async () => {
        requestLogger.requests.forEach(req => {
            console.log('req', req.request);
            console.log('res', req.response); // This will log undefined for the redirects
        });
    });

test('Redirects responses are dropped', async t => {
    await t
        .expect(requestLogger.requests.length).gte(2, { timeout: 10000 })
        .expect(requestLogger.contains(req => req.request.url === 'https://youtube.com/')).ok() // Assertion fails, fixture.after proves this request is captured but `contains` discards it because there is no response.

});
```

### Your complete test report

```
req {
  timestamp: 1710413906635,
  url: 'https://youtube.com/',
  method: 'get'
}
res undefined
req {
  timestamp: 1710413906721,
  url: 'https://youtube.com/',
  method: 'get'
}
res undefined
req {
  timestamp: 1710413906724,
  url: 'https://www.youtube.com/',
  method: 'get'
}
res { statusCode: 200, timestamp: 1710413906989 }
```

Logged output of the test. Can see here the redirects have a res of `undefined`

### Steps to Reproduce

1. Save repro example as `test.js`
2. run `testcafe chrome test.js`

### TestCafe version

3.5.0

### Node.js version

20.10.0

### Command-line arguments

testcafe chrome test.js

### Browser name(s) and version(s)

Chrome 122

### Platform(s) and version(s)

mac OS

**Comment by Bayheck** [comment]
Hello, 

This is intended behavior - response bodies are not available for redirects.

[https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#method-getResponseBody](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#method-getResponseBody)

**Comment by csaundersz** [comment]
I understand that a redirect does not have a response body; that's not what I'm looking for.

On a redirect, there is a response containing a status code and headers. TestCafe isn't capturing that.

**Comment by Bayheck** [comment]
We did not intend to address such scenarios. However, if you create a Pull Request that implements it, we will be more than happy to review your PR.

 

If I understand your scenario right, you want to check the URL to which test execution was redirected after file download. 

As a workaround, if you want to check a redirect to the right url, you can get it via `ClientFunction` API:

 

```
const getURL = ClientFunction(() => window.location.href);

await getURL();
```

 

 

You may find the following thread helpful: [https://stackoverflow.com/questions/52952565/write-current-url-to-console-in-testcafe](https://stackoverflow.com/questions/52952565/write-current-url-to-console-in-testcafe)
