### ISSUE TITLE
Unhandled rejection for tests that starts with `about:blank` page

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#817]
If you specify unhandled rejections handler in node:
```js
process.on('unhandledRejection', function(reason){
    console.log(reason.message);
});
```

You will get `Protocol "about:" not supported. Expected "https:".` For tests that utilizes `about:blank` page. This is happens because we missing `return` in special pages branch in Hammerhead: https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/request-pipeline/index.js#L25, so we still try to perform request for such pages.
@miherlosev @churkin Please fill a corresponding issue in hammerhead repo.

**Comment by miherlosev** [comment]
I will create issue

**Comment by inikulin** [comment]
@miherlosev Please, cross-reference them

**Comment by inikulin** [comment]
Fixed in hammerhead, waiting for release
