### ISSUE TITLE
Unable to proceed to next step after upload file when using setFilesToUpload function

### ISSUE THREAD

**Issue by ayemelyanenko-chegg** [DevExpress/testcafe#8173]
### What is your Scenario?

Would like to upload file and move on automatically to next step after it uploads

### What is the Current behavior?

File is seemingly uploaded but the automatic next step doesn't start

### What is the Expected behavior?

File should be uploaded and then automatic next step should start (as seen in manual mode)

### What is the public URL of the test page? (attach your complete example)

www.chegg.com

### What is your TestCafe test code?

```
import * as path from "path";
import { Selector, t } from "testcafe";
export const emailForSignIn = Selector('input[id*="email"]');
export const passForSignin = Selector('input[type="password"]');
export const signInButton = Selector("button").withText("Sign in");
const letsGetStartedBtn = Selector("span").withText("Get started");
const upload = Selector('div[data-test="file-upload-area-upload-drop-zone"]');
const uploadOntoCanvas = Selector('input[type="file"]');
const pathToFile = path.resolve(__dirname, `./dummy.pdf`);
const nextModal = Selector('div[id="notes-upload-status-modal"]');

// user log in
async function userLogInWithCredentials(
  email: string,
  password: string
): Promise<void> {
  await t.navigateTo(
    "https://www.chegg.com/auth?redirect=https%3A%2F%2Fwww.chegg.com%2F"
  );
  await t
    .typeText(emailForSignIn, email, { paste: true })
    .typeText(passForSignin, password, { paste: true })
    .click(signInButton)
    .wait(6000);
  console.log(`Logged in as user: ${email}`);
}

fixture`Next steps after upload should work`;
test.meta({
  testID: "t-0001",
})("Next steps after upload should work", async (t) => {
  await userLogInWithCredentials("test_user_upload@chegg.us", "Password@1");
  await t.navigateTo("/pla/powernotes");
  await t.click(letsGetStartedBtn);
  await t.setFilesToUpload(uploadOntoCanvas, pathToFile);
  // upload is seemingly there but the next step where the modal should appear never happens
  await t.expect(nextModal.visible).ok();
});
```

### Steps to Reproduce

1. Clone https://github.com/ayemelyanenko-chegg/nextjs-nodejs-example
2. cd into repo
3. cd into my-app
4. npm install
5. npx testcafe chrome tests/sampleUploadTest.ts -L or npx testcafe chrome tests/sampleUploadTest.ts --experimental-multiple-windows or npx testcafe chrome tests/sampleUploadTest.ts --disable-native-automation
6. File is seemingly uploaded but no next step begins in any of the three runs above

![Screenshot 2024-04-23 at 10 30 08 AM](https://github.com/DevExpress/testcafe/assets/14633459/864c536b-b8e6-4f1a-8e8b-f15e26806959)

To see correct behavior manually:
1. Go to https://www.chegg.com/auth?redirect=https%3A%2F%2Fwww.chegg.com%2F
2. Sign in as test_user_upload@chegg.us/Password@1
3. Go to www.chegg.com/pla/powernotes
4. Click on Get Started button
5. Upload a docx document
7. See the modal show up with next steps

<img width="1052" alt="Screenshot 2024-04-17 at 11 05 50 AM" src="https://github.com/DevExpress/testcafe/assets/14633459/43df48e9-f80b-4834-877c-c39dbbb785e4">

### TestCafe version

3.5

### Command-line arguments

npx testcafe chrome tests/sampleUploadTest.ts -L

**Comment by Bayheck** [comment]
Hello, 

I tried reproducing the issue and indeed, it does not automatically proceed to next steps after file uploading.

However, I noticed that there is an error, after we call setFilesToUpload:

![image](https://github.com/DevExpress/testcafe/assets/67043367/70370664-0355-41f1-ba15-e3db2608d36f)
![image](https://github.com/DevExpress/testcafe/assets/67043367/155a2ee3-1374-407e-9df5-308294b88601)
Please note that, according to documentation (https://testcafe.io/documentation/402808/recipes/basics/test-file-upload), setFilesToUpload directly changes the state of the <input type="file"> element. So, there might be some discrepancies between manually clicking the upload and using setFilesToUpload.
Please check what could be the cause of this error, and let us know if the issue is on our side.

**Comment by ayemelyanenko-chegg** [comment]
Hello, I tried uploading other allowed formats (pptx, pdf) and it doesn't go through each time.

When I opened the console log of the automated browser, I notice an error that points to hammerhead

hammerhead.js:42066

This leads me to believe that the error is on the TestCafe side as it mentions hammerhead

![Screenshot 2024-04-22 at 9 15 20 AM](https://github.com/DevExpress/testcafe/assets/14633459/5621d70d-50b0-4fb9-b8d1-f425fbb13b0e)

I also tried to upload the file with a different automation framework as a test (which also uses an input file method) and it worked fine which further leads me to believe that the issue is on the TestCafe side

![Screenshot 2024-04-22 at 9 28 58 AM](https://github.com/DevExpress/testcafe/assets/14633459/c1c2937f-1d30-489a-b200-8d2dd04e1a0c)

**Comment by Bayheck** [comment]
Hello,

I tried running your usage scenario again and made sure that file uploading works as expected with

```
await t.setFilesToUpload(uploadOntoCanvas, "./test_pdf.pdf");
console.log(await uploadOntoCanvas.value);
```

([https://testcafe.io/documentation/402808/recipes/basics/test-file-upload#observe-input-state](https://testcafe.io/documentation/402808/recipes/basics/test-file-upload#observe-input-state))

 

 

Could you please share a [Minimal Working Example](%5Bhttps://testcafe.io/documentation/402636/faq/general-info?search#how-to-create-a-minimal-working-example-when-you-submit-an-issue)]([https://testcafe.io/documentation/402636/faq/general-info?search#how-to-create-a-minimal-working-example-when-you-submit-an-issue](https://testcafe.io/documentation/402636/faq/general-info?search#how-to-create-a-minimal-working-example-when-you-submit-an-issue))) that we can run locally?

**Comment by ayemelyanenko-chegg** [comment]
Hello, this doesn't proceed onto the next step though. Once the file is uploaded, it should move on to the next steps of analyzing the documents and it doesn't do so in automation.

Here is a screenshot of where TestCafe stops

![Screenshot 2024-04-23 at 9 28 48 AM](https://github.com/DevExpress/testcafe/assets/14633459/f2b066a9-1187-4949-831d-a076404cb133)

Here is where it should do after an upload, I listed the steps to reproduce the proper flow manually and I believe you tried it and saw it

1) Go to https://www.chegg.com/auth?redirect=https%3A%2F%2Fwww.chegg.com%2F
2) Sign in as [test_user_upload@chegg.us](mailto:test_user_upload@chegg.us)/Password@1
3) Go to [www.chegg.com/pla/powernotes](http://www.chegg.com/pla/powernotes)
4) Click on Get Started button
5) Upload a docx document
6) See the pop up show up with next steps

Here is a video of how it will look after an upload (doing this manually):

https://github.com/DevExpress/testcafe/assets/14633459/898395fe-f182-4f53-bea6-3af3f98d92e3


The minimally working example is present in the steps to reproduce and in the repo that I provided. I will adjust the automation in the sample repo that I provided to assert that the next step is visible and it will fail because the next steps after the upload don't go through.

![Screenshot 2024-04-23 at 10 30 08 AM](https://github.com/DevExpress/testcafe/assets/14633459/f706a7b1-4af4-471d-9f52-3274a791273f)

**Comment by Bayheck** [comment]
Hello,

I understand that after uploading a file, it should move on to the next steps. I managed to reproduce this behavior using your example. However, we can not determine the cause of the issue without seeing the logic behind your source code.

As I mentioned earlier, there could be differences between manually clicking the upload and using setFilesToUpload.

By "Minimal Working Example", I meant a simple page with file upload and the logic of the next automatic steps. In this minimal example, we don't have to navigate to [https://www.chegg.com](https://www.chegg.com).

Thank you for your understanding.

**Comment by ayemelyanenko-chegg** [comment]
@Bayheck Hello, looks like this issue resolved itself for our team. We didn't even need to go to version 3.6, it was fixed with 3.5. Thanks for your help.

**Comment by Gandhi11** [comment]
@ayemelyanenko-chegg I have the same problem in v3.6.0, did you guys updated something to make the step after de setFilesToUpload work?

**Comment by ayemelyanenko-chegg** [comment]
@Gandhi11 No, it just resolved itself in our case. Seems like our developers made some changes to the code that got TestCafe upload function to work.
