### ISSUE TITLE
Testcafe became very unstable a few weeks ago

### ISSUE THREAD

**Issue by rEtoAChM** [DevExpress/testcafe#8184]
### What is your Scenario?

Running latest testcafe with 'chromium:headless' within the testcafe/testcafe:latest docker image

### What is the Current behavior?

We have the same issue as described here: https://github.com/DevExpress/testcafe/issues/8145
But the described workaround doesnt work for us. 

Running the tests with: 'testcafe chromium:headless tests.tsx' leads in 80% of runs to the described issue. Only workaround is to retry it as long as it works

Running tests with the suggested workaround: 'testcafe "chromium --headless=new" tests.tsx' leads to "Error: connect ECONNREFUSED 127.0.0.1:40603"

### What is the Expected behavior?

-

### What is the public URL of the test page? (attach your complete example)

-

### What is your TestCafe test code?

-

### Steps to Reproduce

1.
2.
3.

### TestCafe version

3.6.0

### Node.js version

20.x

### Command-line arguments

testcafe "chromium --headless=new" tests.tsx

**Comment by Bayheck** [comment]
Hello,

Please try running it with

testcafe chromium --headless=new

or

testcafe 'chrome --headless=new'

 

Please be aware of the quotes. 

In TestCafe v3.6 and later, headless=new is default, and you can use chrome:headless again.

If these solutions don't fix the issue, please elaborate on it.

>Running the tests with: 'testcafe chromium:headless tests.tsx' leads in 80% of runs to the described issue.

Do you mean you get the following error?

```
Error: Unable to open the "chrome:headless" browser due to the following error
```
