### ISSUE TITLE
Application landing on blank page / not loading property

### ISSUE THREAD

**Issue by aprabh001c** [DevExpress/testcafe#8185]
### What is your Scenario?

Testcafe is getting stuck or landing blank page for many pages. In many cases, testcafe gets stucks and launches a new browser. This behavior varies across the pages. Tried with both native automation ON and OFF, but still application new browser is launched and gets stuck in some other page.

### What is the Current behavior?

Application landing on blank page / not loading property

### What is the Expected behavior?

App load properly

### What is the public URL of the test page? (attach your complete example)

https://www.xfinity.com

### What is your TestCafe test code?

import { t, Selector } from "testcafe";

fixture`SampleFixture`

test(`SampleTC`, async tn => {

    await t.navigateTo("https://www.xfinity.com/learn/offers");
    await t.wait(10000);
    await t.click(Selector('button[id="onetrust-accept-btn-handler"], [aria-label="allow cookies"]'))
    await t.typeText(Selector('input[name="localizationAddressField"]'), "8299 COMCAST, UNIT 100, BLUEFIELD, WV 24701");
    await t.wait(3000)
    await t.click(Selector('.suggestions-select__item'))
    await t.click(Selector('button[type="submit"]').withText('Build your plan'));
    await t.wait(10000);
    await t.click(Selector('[data-testid="Internet-lob-drawer-cta"]'))
    await t.wait(5000)
    await t.click(Selector('button[data-testid="offer-tile-Connect"]'))

})

### Steps to Reproduce

import { t, Selector } from "testcafe";

fixture`SampleFixture`

test(`SampleTC`, async tn => {

    await t.navigateTo("https://www.xfinity.com/learn/offers");
    await t.wait(10000);
    await t.click(Selector('button[id="onetrust-accept-btn-handler"], [aria-label="allow cookies"]'))
    await t.typeText(Selector('input[name="localizationAddressField"]'), "8299 COMCAST, UNIT 100, BLUEFIELD, WV 24701");
    await t.wait(3000)
    await t.click(Selector('.suggestions-select__item'))
    await t.click(Selector('button[type="submit"]').withText('Build your plan'));
    await t.wait(10000);
    await t.click(Selector('[data-testid="Internet-lob-drawer-cta"]'))
    await t.wait(5000)
    await t.click(Selector('button[data-testid="offer-tile-Connect"]'))

})

### TestCafe version

3.6

### Node.js version

18.12.0

### Command-line arguments

testcafe chrome --concurrency 1  -F SampleFixture

### Browser name(s) and version(s)

chrome 124.0.6367.119 

### Platform(s) and version(s)

Windows 10 Enterprise

**Comment by aprabh001c** [comment]
Error message in console - The Chrome 124.0.0.0 / Windows Server 2019 browser disconnected. If you did not close the browser yourself, browser performance or network issues may be at
 fault.

**Comment by PavelMor25** [comment]
Hello @aprabh001c ,

I can't reproduce the issue; I'm getting an "access denied" error. Could you please create a [minimal working example](https://testcafe.io/documentation/402636/faq/general-info?search#how-to-create-a-minimal-working-example-when-you-submit-an-issue)?

![image](https://github.com/DevExpress/testcafe/assets/77216072/30cc8f30-255d-4b0b-b4d8-61a6e4d234f9)

**Comment by aprabh001c** [comment]
Could you please try with https?

**Comment by PavelMor25** [comment]
Hello,

I tried both options, but I still encounter this error and can't investigate the issue. Could you please create a [minimal working example](https://testcafe.io/documentation/402636/faq/general-info?search#how-to-create-a-minimal-working-example-when-you-submit-an-issue)? Alternatively, if you have any other method for us to investigate the issue, please let us know.

**Comment by aprabh001c** [comment]
Hi,
It's tough to reproduce with public domains, and the provided website is
public. I am not sure why it is not accessible in your network.
