### ISSUE TITLE
Inspected target navigated or closed

### ISSUE THREAD

**Issue by vasilyevi** [DevExpress/testcafe#8193]
### What is your Scenario?

After upgrading to 3.6.0 the issue happens randomly, the same code might work multiple time, but 1-3 of of 10 run could be failed

### What is the Current behavior?

Unhandled promise rejection:

ERROR 'Error: Inspected target navigated or closed
    at /home/runner/test/src/js/tests/node_modules/chrome-remote-interface/lib/chrome.js:94:35
    at Chrome._handleMessage (/home/runner/test/src/js/tests/node_modules/chrome-remote-interface/lib/chrome.js:272:17)
    at WebSocket.<anonymous> (/home/runner/test/src/js/tests/node_modules/chrome-remote-interface/lib/chrome.js:240:22)
    at WebSocket.emit (node:events:517:28)
    at WebSocket.emit (node:domain:489:12)
    at Receiver.receiverOnMessage (/home/runner/test/src/js/tests/node_modules/ws/lib/websocket.js:1068:20)
    at Receiver.emit (node:events:517:28)
    at Receiver.emit (node:domain:489:12)
    at Receiver.dataMessage (/home/runner/test/src/js/tests/node_modules/ws/lib/receiver.js:517:14)
    at Receiver.getData (/home/runner/test/src/js/tests/node_modules/ws/lib/receiver.js:435:17)

### What is the Expected behavior?

N/A

### What is the public URL of the test page? (attach your complete example)

N/A

### What is your TestCafe test code?

N/A

### Steps to Reproduce

N/A

### TestCafe version

3.6.0

### Node.js version

v18.19.1

### Command-line arguments

npx testcafe

**Comment by vasilyevi** [comment]
few more things. As far as I can see it always happens as `Unhandled promise rejection `. Actually, everytime it happens the test itself is completed, so it performs all the steps from the beginning to the end. But on after step `const hasErr = !!t.testRun.errs.length;` returns true. 
Sometimes it happens in before hook, sometimes during the test itself, but always it completes all the steps and fail the test in after hook because it says that this is an error.

![image](https://github.com/DevExpress/testcafe/assets/28949557/2a36d8ae-487d-49ba-b5e8-c7604d6aa711)

Do you have any testcafe logs or something which might give more details?

**Comment by Bayheck** [comment]
Hello,

Unfortunately, without a minimal working example, we cannot determine the cause of this issue.

**Comment by vasilyevi** [comment]
So, there is no any testcafe logs or somehting?

**Comment by Bayheck** [comment]
Hello,

You can try to enable TestCafe logs on your CI - `set DEBUG=testcafe:*,hammerhead:*`.

**Comment by vasilyevi** [comment]
Where to set? is it env var?

**Comment by vasilyevi** [comment]
Would that work with native automation?

**Comment by Bayheck** [comment]
Yes, it is an environment variable, and it works with native automation.

To enable the debug log, you can use the following way: 

```
set DEBUG=testcafe:*,hammerhead:*
testcafe chrome index.js 2> testcafe.log
```

Before running TestCafe, you need to set the DEBUG environment variable like in the example above.
Then, you need to run TestCafe and redirect the output to the file.

 

Please refer to the following help topic for details: [https://testcafe.io/documentation/402636/faq/general-info#related-questions](https://testcafe.io/documentation/402636/faq/general-info#related-questions).

**Comment by Bayheck** [comment]
Hello,

Thank you for the example. However, we couldn't reproduce the issue because you did not include the actual navigation link:

> await t.navigateTo('<REDACTED>')

Please update your example so that we can reproduce the issue on our end.

**Comment by port-eighty** [comment]
> Hello,
> 
> Thank you for the example. However, we couldn't reproduce the issue because you did not include the actual navigation link:
> 
> > await t.navigateTo('')
> 
> Please update your example so that we can reproduce the issue on our end.

Hi,

I am unable to provide internal link nor able to reproduce it on other websites so far. What other tools or what can I do to further debug it?

**Comment by razvanvancea** [comment]
== page object ==
import { Selector } from 'testcafe';

class CommonPage {
	constructor() {
		this.acceptCookiesBtn = Selector('#cc-wrapper a').withText('Permite toate');
	}
}

export default new CommonPage();


== test ==
fixture`User actions Test Suite`.page`${baseUrl}`;
test('create account test', async (t) => {
	await t
		.click(CommonPage.acceptCookiesBtn)
		.hover(HeaderPage.myAccountBtn)
		.click(HeaderPage.createAccountBtn);
	await RegisterPage.createAccount(
		chance.first(),
		'TestCafe',
		`test@test.com`,
		'test'
	);

	await t
		.expect(
			Selector('main div').withText('Vă mulțumim că v-ați înregistrat la')
				.visible
		)
		.ok();
});

**Comment by port-eighty** [comment]
In `node_modules/testcafe/lib/native-automation/request-pipeline/index.js`
I have just opted to ignore that error entirely using:
```javascript
try{
                        await this._client.Runtime.runIfWaitingForDebugger(event.sessionId);
                    } catch(error) {
                        console.error('Caught weird error in-attachedToTarget')
                        if(error.response) {
                            /* console.error(typeof error.response)
                            console.error(error.response) */
                            if(error.response.message) {
                                /* console.error(typeof error.response.message)
                                console.error(error.response.message)
                                console.error(error.response.message.includes("Inspected target navigated or closed")) */
                                const message = error.response.message
                                if(typeof message === 'string' && message.includes("Inspected target navigated or closed")) {
                                    return
                                }
                            }
                            
                        }
                        //resolve other
                        console.error(error)
                    }
```
as my issue is only stemming from `await this._client.Runtime.runIfWaitingForDebugger(event.sessionId);` even though the test passes.

**Comment by Bayheck** [comment]
Hello, 

In order for TestCafe team to research and work on this issue, we need a reproducible minimal example ([https://testcafe.io/documentation/402636/faq/general-info#how-to-create-a-minimal-working-example-when-you-submit-an-issue](https://testcafe.io/documentation/402636/faq/general-info#how-to-create-a-minimal-working-example-when-you-submit-an-issue)).

This example has to have a working navigation link so that anyone can run the example and see the issue. 

Unfortunately, without such an example, we still cannot determine the cause of this issue. 

 

Please provide an example so that we can reproduce the issue on our end and start working on it.
