### ISSUE TITLE
Use esbuild instead of babel

### ISSUE THREAD

**Issue by mixtur** [DevExpress/testcafe#8197]
### What is your Scenario?

Not applicable

### What are you suggesting?

I was invstigating why do we have 2000+ transitive dependencies in our project, and figured that significant part of those are coming from testcafe.

When looking at your dependencies graph, I've noticed that approximately half of your dependncies have something to do with babel. https://npmgraph.js.org/?q=testcafe#zoom=h&select=exact%3A%40babel%2Fpreset-env%407.24.5

From my experience, esbuild convers most of the babel use cases and it is also much faster. Can you please consider migrating from babel to something else? If not esbuild, then maybe swc?

I imagine, that testing framework like yours probably requires, some crazy code transformations that are hardly possible with other transpilers, but maybe this is a design decision to reconsider as well?

**Comment by PavelMor25** [comment]
Hello @mixtur,

Thank you for bringing this to our attention.

We understand your concern about the high number of transitive dependencies, particularly those related to Babel.

However, at present, we cannot prioritize this task. Our current setup involves complex code transformations that are heavily reliant on Babel, and transitioning to a new transpiler would require significant effort and testing to ensure compatibility and stability.

That said, we are open to revisiting this decision in the future as priorities evolve. We appreciate your feedback and will keep it in mind for future improvements.

Thank you for your understanding.
