### ISSUE TITLE
Feature Request: Selector Composition

### ISSUE THREAD

**Issue by tcblight** [DevExpress/testcafe#8201]
### What is your Scenario?

I would like to be able to pass a Selector to any method of Selector that takes a cssSelector String. I think this would allow the PageModel best practice to be a little more flexible to find components of repeated elements on the page.

For instance, the situation this came up in was with a table where the rows have links in them.

There is an existing selector on the page model to find a link:

```
class PageModel {
   static Selectors = {
       reviewSubmission: Selector('a').withText('Review Submission')
    };
}
```

I want to be able to write a Selector with a query to find my desired row and then compose it with the existing reviewSubmission Selector to find the row's review submission link:

```
const customerName = "Firstname Lastname"
const selector = Selector('tr').withText(customerName).find(pageModel.Selectors.reviewSubmission)
t.click(selector)
```

But I can't, I have to chain it like so:

```
const customerName = "Firstname Lastname"
const selector = Selector('tr').withText(customerName).find('a').withText('Review Submission')
t.click(selector)
```

Which prevents me from reusing selectors that I defined in the page model as easily.

### What are you suggesting?

Implement all Selector methods that can take a cssSelector (.child, .find, .filter, etc) to take a Selector and apply its query on the resulting Selector 

### What alternatives have you considered?

I could just repeat myself more, but then I don't get to reuse elements of the page model as much.

I  could potentially change my page model to instead take an ancestor selector and apply the query I would put in a Selector otherwise, for instance:

```
  static reviewSubmission(ancestorSelector = Selector('body')) {
     return ancestorSelector.find('a').withText('Review Submission');
  }
```

But that wouldn't give me the flexibility to compose as freely since I am committing to the find() inside the page model. For instance, my proposed solution could allow you to reuse the same Selector for find, sibling, parent, etc of different Selectors, though that doesn't apply in my example.

**Comment by Bayheck** [comment]
Unfortunately, we cannot take this enhancement in work, since currently we are fully focused on other tasks. We may reconsider this task priority in the future if we get requests for it.

If you want, you can make a PR with the described functionality. We will review and accept it if everything is OK.
