### ISSUE TITLE
Type-Def: declare Metadata as interface

### ISSUE THREAD

**Issue by htho** [DevExpress/testcafe#8231]
### What is your Scenario?

I want type safety when I use metadata.
Therefore I want to declare the shape of the `Metadata` type.

### What are you suggesting?

This would be possible if `Metadata` was not defined as a `type` but as an `interface` in `./ts-defs-src/test-api/test-info.d.ts`.

This way I can create a file like this and declare the expected/known Metadata.

```typescript
// testcafe.global.d.ts
declare module "testcafe" {
	global {
		interface Metadata {
			manual?: boolean,
		}
	}
}

```

### Additional context

This is what `./ts-defs-src/test-api/test-info.d.ts` should look like.

```typescript
// Test Info
//----------------------------------------------------------------------------------------------------------------------

interface Metadata {
    [key: string]: unknown;
}

interface TestInfo {
    name: string;
    meta: Metadata;
}

interface FixtureInfo {
    name: string;
    meta: Metadata;
    path: string;
}
```

**Comment by Bayheck** [comment]
Hello,

Could you please try using the following example - it shows how to type check Metadata?

[https://github.com/DevExpress/testcafe-examples/tree/master/examples/type-check-for-meta](https://github.com/DevExpress/testcafe-examples/tree/master/examples/type-check-for-meta)

 

I look forward to your results.

**Comment by htho** [comment]
Hi,

no, this does not help, because it does not show errors when wrong/unknown metadata is set (except if  the generic overload is enforced - `test.meta<MetaOptions>`).

But only overloading `TestFn` is not enough, because I want typesafety for all places where `Metadata` is used: `FixtureFn`, `TestInfo`, `FixtureInfo`, `FilterFunction`, `FilterDescriptor`
