### ISSUE TITLE
Infinite loop when screenshot or video folder cannot be written

### ISSUE THREAD

**Issue by belug23** [DevExpress/testcafe#8236]
### What is your Scenario?

Take a screenshot when a test fail and get a visible error it the output directory is not writable

### What is the Current behavior?

When you use the screenshot or video recording feature and you're output folder isn't writable, test café goes into an infinite error loop. It's mainly a problem with docker where it's easy to have the volume configured with the wrong permissions.

### What is the Expected behavior?

Get an error message that the folder isn't writable

### What is the public URL of the test page? (attach your complete example)

https://github.com/belug23/test-cafe-infinite-loop

### What is your TestCafe test code?

```
fixture('Getting Started')
    .page('https://devexpress.github.io/testcafe/example');

test('My first test', async t => {
    await t.typeText('#developer-name-error', 'John Smith');
});
```

### Your complete configuration file

There's no configuration file

### Your complete test report

 Running tests in:
 - Chrome 126.0.0.0 / Alpine Linux 3.21.0_alpha20240606

 Getting Started

### Steps to Reproduce

```
git clone https://github.com/belug23/test-cafe-infinite-loop.git
cd test-cafe-infinite-loop
docker run --rm --name testcafe-infinite-loop -v $(pwd)/tests:/tests -v $(pwd)/screenshots:/screenshots -e DEBUG='testcafe*' -it testcafe/testcafe "chromium:headless:width=1600;height=900"  -s /screenshots/ --screenshots-full-page -S
```

### TestCafe version

3.6.2

### Node.js version

v20.13.1

### Command-line arguments

"chromium:headless:width=1600;height=900"  -s /screenshots/ --screenshots-full-page -S

### Browser name(s) and version(s)

Chrome 126.0.0.0

### Platform(s) and version(s)

Alpine Linux 3.21.0_alpha20240606

**Comment by Bayheck** [comment]
Hello,
This type of error handling is not implemented in testcafe. Unfortunately, we cannot take this enhancement in work because we are currently focused on other tasks.

Priority of this enhancement is low, so I will close this issue.
