### ISSUE TITLE
Page not loaded

### ISSUE THREAD

**Issue by marcvall** [DevExpress/testcafe#8239]
### What is your Scenario?

We want to browse a page and then execute some validations and/or actions on that page. Pages where we show some editorial content fail. Other pages work as expected.

We're using **native automation** and **it was working without any issue with Testcafe 3.5.0** (and still does).

### What is the Current behavior?

The page is not loaded and there are strange characters in the top-left corner of the page.
![1 error](https://github.com/user-attachments/assets/5bc5acb8-e22b-4ef6-9738-fa0c43fafefe)

### What is the Expected behavior?

Page successfully loaded.

### What is the public URL of the test page? (attach your complete example)

.

### What is your TestCafe test code?

```
await t.navigateTo(publishedUrl); // it navigates to the page as expected; however page is not loading
await t.expect(this.takeActionWidget.exists).ok({ timeout: 30000 }); // expect error
```

### Screenshots

![1 error](https://github.com/user-attachments/assets/39bb1987-bc6c-4d2d-95b7-74c43ade2171)

### Steps to Reproduce

1.
2.
3.

### TestCafe version

3.6.2

### Command-line arguments

testcafe "chrome '--window-size=1920,1080 --allow-insecure-localhost'"

### Browser name(s) and version(s)

Chrome 126

### Other

Not possible to share the pages where it fails, but it was working without issues with Testcafe 3.5.0.

**Comment by marcvall** [comment]
I can't share the pages where tests are failing. Investigating a bit more I can see that there is a JavaScript errors related to regular expression "Range out of order in character class" that were not thrown before (and are not thrown within the normal non-automated UI).

Plus I can see strange characters on the page rendering:

`
+ expected - actual

-E2EÂ BlogpostÂ forÂ migrationÂ editedÂ titleÂ 1721829796313
+E2E Blogpost for migration edited title 1721829796313`

This "Â" character doesn't appear when I browse the page without automation ¿? Don't know were it comes from...

**Comment by PavelMor25** [comment]
Hello @marcvall,

Unfortunately, we are unable to investigate this issue and determine its cause without a simple example. Could you please clarify if you ran the test only in native automation mode, and what encoding your website is using?

If you are using only native automation mode, please refer to the following help topic for further details: [How do I disable native automation?](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode?search#q-how-do-i-disable-native-automation)

**Comment by marcvall** [comment]
Hello @PavelMor25 , thanks for your answer.

Yes, we run the test only in native automation and the website encoding is UTF-8.

Looks like without native automation it works. Does it make any sense? Could it be any new/updated component regarding charsets/encoding that was introduced after 3.5.0 only for native automation?

We can't disable native automation in our pipeline automated tests as then we have other issues during login.

**Comment by PavelMor25** [comment]
We previously encountered cases where non-UTF-8 site encoding caused incorrect characters to appear in native automation. However, we're not certain if this applies to your situation.

Could you please try running your test on TestCafe v3.3.0? If the issue doesn't occur, we'll need a minimal working example of your usage scenario to investigate further and determine what specifically causes this behavior.
