### ISSUE TITLE
Testcafe is not opening any pop-up windows

### ISSUE THREAD

**Issue by sophia-cyclr** [DevExpress/testcafe#8243]
### What is your Scenario?

Testcafe no longer opens any pop-up windows, the button is clicked and nothing happens.

### What is the Current behavior?

Nothing happens.

### What is the Expected behavior?

The pop-up window opens.

### What is the public URL of the test page? (attach your complete example)

https://pinterest.com

### What is your TestCafe test code?

```
import { Selector, t } from "testcafe";

fixture`Test`;

test('pinterest', async t => {
    await t.navigateTo('https://pinterest.com/');
    await t.click(Selector('div').withExactText('Log in'));
    await t.click(Selector('span').withText('Continue with Google'));
    await t.typeText(Selector('#identifierId'), 'test@example.com');
});
```

### Steps to Reproduce

1. Run the test script, or any that use pop-up windows.
2.
3.

### TestCafe version

3.6.2

### Node.js version

20.16.0

### Command-line arguments

testcafe chrome test.js --disable-native-automation

### Browser name(s) and version(s)

Chrome 126

### Platform(s) and version(s)

Windows

**Comment by PavelMor25** [comment]
Hello @sophia-cyclr,

Try setting the `--disable-native-automation` option to `--experimental-multiple-windows`.

The [--experimental-multiple-windows ](https://testcafe.io/documentation/402639/reference/command-line-interface#--experimental-multiple-windows)option allows TestCafe to use [native automation](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode) when it runs multi-window tests.

Please let us know your results.

**Comment by sophia-cyclr** [comment]
> Hello @sophia-cyclr,
> 
> Try setting the `--disable-native-automation` option to `--experimental-multiple-windows`.
> 
> The [--experimental-multiple-windows ](https://testcafe.io/documentation/402639/reference/command-line-interface#--experimental-multiple-windows)option allows TestCafe to use [native automation](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode) when it runs multi-window tests.
> 
> Please let us know your results.

This works, however, I cannot use this flag in my real scenario (not the test one in the ticket) as the following console errors cause the page not to load. This is a private application so I can't provide repro details for it.
![image](https://github.com/user-attachments/assets/dd76408c-3368-4fce-9fb2-1ba6d2a0d69d)

Unfortunately, I have to use the TestCafe proxy until the multiple windows option becomes more stable.

In the pinterest example, the following console error appears:

`The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead. See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header.`

Could this be a related thing and how can I resolve it?
