### ISSUE TITLE
ERROR TypeError: Cannot read properties of null (reading 'pendingTaskDonePromise')

### ISSUE THREAD

**Issue by shypefx** [DevExpress/testcafe#8249]
### What is your Scenario?

I'm using testcafe to run ui integration test on a web application. 
I'm working on the development of a Util to simplify the creation of tests. 

### What is the Current behavior?

Since few days, I have this error of cannot read properties. 
I have tried to remove all my modifications (rebranch on main) but nothing has changed, I'm still having the issue.
I have updated the testcafe version (latest), remove the node modules and reinstall it, reboot my laptop, push my modification on jenkins (it's working so that mean we have a local issue). 
I think this come from a Windows update or something locally 
I cannot run any test 

### What is the Expected behavior?

To run the test without any errors

### What is the public URL of the test page? (attach your complete example)

Unable to share URL.

### What is your TestCafe test code?

i cannot send all the code because we have too much

### Your complete test report

$ npm run test:ui-integration

> @bpi-tools/process-builder-webapp@3.13.0 pretest:ui-integration
> npm run tsc:gojs-pagemodel

> @bpi-tools/process-builder-webapp@3.13.0 tsc:gojs-pagemodel
> tsc test/page-models/gojs-model.page.ts

> @bpi-tools/process-builder-webapp@3.13.0 test:ui-integration
> gherkin-testcafe --config-file test/.testcaferc.integration.json --tags @newCanvas

ERROR TypeError: Cannot read properties of null (reading 'pendingTaskDonePromise')
    at C:\SAPDevelop\src\process-builder\process-builder-webapp\node_modules\testcafe\src\runner\index.js:181:75
    at Array.map (<anonymous>)
    at Runner._getTaskResult (C:\SAPDevelop\src\process-builder\process-builder-webapp\node_modules\testcafe\src\runner\index.js:181:41)

### Steps to Reproduce

1. npm run test
2.
3.

### TestCafe version

3.6.2

### Node.js version

20.11

### Command-line arguments

gherkin-testcafe --config-file test/.testcaferc.integration.json --tags @newCanvas

### Browser name(s) and version(s)

127.0.6533.73

### Platform(s) and version(s)

Windows 11

**Comment by PavelMor25** [comment]
Hello @shypefx,

Based on your issue description, it looks like you're using the gherkin-testcafe package to run TestCafe. Please clarify if you tried reproducing the issue using only TestCafe.

If not, please check if the issue persists when you run your tests directly with TestCafe.

If the issue still occurs with TestCafe, please prepare a [minimal working example](https://testcafe.io/documentation/402636/faq/general-info?search#how-to-create-a-minimal-working-example-when-you-submit-an-issue) for us to investigate it further.
