### ISSUE TITLE
SetFileUpload is not working..

### ISSUE THREAD

**Issue by testcafe-HK** [DevExpress/testcafe#8254]
### What is your Scenario?

Getting werired way of error for upload 
await t
        .switchToIframe('#SelectDocumentToUploadPopup-2 > iframe');
await t
 .setFilesToUpload('#documents\:upload\:file', ["C:\\CCC\\CL30-PARKS.pdf"])
        .click(atlasPage.addDocuments_btn);
This is the addDocument input view source
<input autocomplete="off" class="rich-fileupload-hidden" id="documents:upload:file" name="documents:upload:file" onchange="return $('documents:upload').component.add(this);" style="cursor: pointer; right: 0px; top: 0px; font-size: 10em; position: absolute; padding: 0px" type="file" data-hammerhead-focused="true">

### What is the Current behavior?

1) Cannot find the following file(s) to upload:
      "
      C
      :
      C
      C
      C
      C
      L
      3
      0
      -
      P
      K
      .
      p
      d
      f
      "

### What is the Expected behavior?

File should be uploaded

### What is the public URL of the test page? (attach your complete example)

It's internal

### What is your TestCafe test code?

Getting werired way of error for upload 
**await t
        .switchToIframe('#SelectDocumentToUploadPopup-2 > iframe');
await t
 .setFilesToUpload('#documents\:upload\:file', ["C:\\CCC\\CL30-PARKS.pdf"])
        .click(atlasPage.addDocuments_btn);**
This is the addDocument input view source
<input autocomplete="off" class="rich-fileupload-hidden" id="documents:upload:file" name="documents:upload:file" onchange="return $('documents:upload').component.add(this);" style="cursor: pointer; right: 0px; top: 0px; font-size: 10em; position: absolute; padding: 0px" type="file" data-hammerhead-focused="true">

### Steps to Reproduce

1.Upload document 
2.
3.

### TestCafe version

3.5

### Command-line arguments

npm run test:e2e

**Comment by PavelMor25** [comment]
Hello @testcafe-HK,

Please try the latest version of TestCafe. If the issue persists, please share a [minimal working example](https://testcafe.io/documentation/402636/faq/general-info?search#how-to-create-a-minimal-working-example-when-you-submit-an-issue) so that the TestCafe team can investigate your issue in more detail.
