### ISSUE TITLE
click/.visible on dropdown list element: action target (xxx) is too small to be visible

### ISSUE THREAD

**Issue by Hellswing** [DevExpress/testcafe#8259]
### What is your Scenario?

After updating TestCafe, every .visible or .click on a list item failed.
This seems to be related to versions 3.6.1 and 3.6.2, as there are no such problems with version 3.6.0.
N.B.: with or without :headless

### What is the Current behavior?

In TestCafe versions >3.6.0, assertions on listElement.visible or clicking on these elements fail despite the fact that they are visible.

### What is the Expected behavior?

A visible element should be **.visible** and clickable

### What is the public URL of the test page? (attach your complete example)

I've tried to reproduce it with examples like https://www.w3schools.com/css/css_dropdowns.asp, but the problem doesn't appear.
I think it may be linked to the list, which is dynamic.

### What is your TestCafe test code?

I can't reveal all steps, as there are a lot. But only the following is failing
```
await t
     .expect(page.calculator.typeSelect.options(optionsNumber)[0].selector.visible)
    .ok()
    .click(page.calculator.typeSelect.options(optionsNumber)[0].selector);
```

### Your complete test report

   1) The action target (<option _ngcontent-ng-c32842283="" data-testid="type-option" _nghost-ng-c3742536035="" ng-reflect-value="1" role="option" id="option-3" class="option-wrapper">...</option>) is too small to be visible:
      224px x 24px.

      Browser: Chrome 127.0.0.0 / Ubuntu 22.04

         394 |  const optionsNumber: number = await page.calculator.typeSelect.count();
         395 |  await t.expect(page.calculator.typeSelectTest.visible).ok();
         396 |  await t
         397 |    /*   .expect(page.calculator.typeSelect.options(optionsNumber)[0].selector.visible)
         398 |    .ok()*/
       > 399 |    .click(page.calculator.typeSelect.options(optionsNumber)[0].selector);
         400 |});
         401 |

         at <anonymous> (/home/xx.ts:399:6)
         at fulfilled (/home/xx.ts:28:58)

Rem : .visible in comment so error is more explicit

### Screenshots

![image](https://github.com/user-attachments/assets/e54b2443-8ddd-4a40-bc61-5dcc29206153)

Here is the list

### Steps to Reproduce

1. run a test with a dropdown list (dynamic?) using TestCafe > 3.6.0
2. .visible or click on an element of this list
3. run the same with TestCafe 3.6.0

### TestCafe version

3.6.2

### Node.js version

22.1.0

### Command-line arguments

-b chrome

### Browser name(s) and version(s)

Chrome 127

### Platform(s) and version(s)

Linux, Ubuntu 22.04

**Comment by Hellswing** [comment]
I tried to find an example on a public site, but I'm afraid I couldn't find any.
If you know of one that uses select with dynamic data (in angular would be perfect), I'd be happy to give it a try.

**Comment by Bayheck** [comment]
Hello, thank you for your report.
 
Please refer to the https://github.com/DevExpress/testcafe/issues/8237 issue.
I'll close this issue as a duplicate.
