### ISSUE TITLE
Issue with the Guides

### ISSUE THREAD

**Issue by cassnapper** [DevExpress/testcafe#8262]
### What is your Scenario?

In the section headed Fixtures where the guide discusses Relative URLS, the exmaple given seems to be an Absolute path.
Further down in the Tests section , Releative URLS are revisited and state explicitly that the period char is used to define relative URL, and yet I am not seeing that in the example given either ? Am I missing something here ?

### What is the Current behavior?

na

### What is the Expected behavior?

na

### What is the public URL of the test page? (attach your complete example)

na

### What is your TestCafe test code?

na

### Steps to Reproduce

1.
2.
3.
na

### TestCafe version

na

### Command-line arguments

na

**Comment by Bayheck** [comment]
Hello, thank you for reaching out to us.
We fixed the issue in our documentation:
 
https://testcafe.io/documentation/402831/guides/basic-guides/test-structure#absolute-fixture-url
https://testcafe.io/documentation/402831/guides/basic-guides/test-structure#relative-test-url
