### ISSUE TITLE
JSON.parse error during playing empty test on phantomjs

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#827]
### Test

``` javascript
fixture `Getting Started`
    .page('http://mail.ru');

test('My first test', async t => {

});
```
### Log

![Console](https://cloud.githubusercontent.com/assets/4133518/18666470/abc4ba98-7f34-11e6-9487-345307a28e76.png)

**Comment by inikulin** [comment]
@miherlosev It's definitely an error with hammerhead. Please, fill issue there

**Comment by inikulin** [comment]
I guess we'll not support Phantom, unless it's using extremely outdated WebKit under the hood.
