### ISSUE TITLE
Tests fail with "Error: WebSocket connection closed" for Chrome 130.0.6723.6 (2024-09-18)

### ISSUE THREAD

**Issue by thomas-jakemeyn** [DevExpress/testcafe#8286]
### What is your Scenario?

We run the exact same 170+ TestCafe tests against the latest version of **Chrome** and **Chrome Beta**.

### What is the Current behavior?

Our tests still pass for **Chrome**. However, the majority of them started failing for **Chrome Beta** with the stacktrace below after we upgraded to the version `130.0.6723.6`. That version has been promoted to the _Beta_ channel on September 18, 2024 (see [here](https://chromereleases.googleblog.com/2024/09/chrome-beta-for-desktop-update_18.html)).

```
Error: WebSocket connection closed
at node_modules/chrome-remote-interface/lib/chrome.js:94:35
at Chrome._handleConnectionClose (node_modules/chrome-remote-interface/lib/chrome.js:256:13)
at WebSocket.<anonymous> (node_modules/chrome-remote-interface/lib/chrome.js:243:22)
at WebSocket.emit (node:events:519:28)
at WebSocket.emit (node:domain:488:12)
at WebSocket.emitClose (node_modules/ws/lib/websocket.js:246:10)
at Socket.socketOnClose (node_modules/ws/lib/websocket.js:1150:15)
at Socket.emit (node:events:519:28)
at Socket.emit (node:domain:488:12)
at TCP.<anonymous> (node:net:339:12)
```

### What is the Expected behavior?

Running tests against Chrome `130.0.6723.6` should not trigger `Error: WebSocket connection closed`.

### What is the public URL of the test page? (attach your complete example)

NA

### What is your TestCafe test code?

NA

### Steps to Reproduce

1.
2.
3.

### TestCafe version

3.6.2

### Command-line arguments

NA

**Comment by thomas-jakemeyn** [comment]
I forgot to mention that this problem happens when running the tests in Docker (on TeamCity).
I cannot reproduce it with a simple example.
Hopefully [this similar Cypress issue](https://github.com/cypress-io/cypress/issues/28523#issuecomment-2069651720) can shed some light on the matter.

**Comment by thomas-jakemeyn** [comment]
I just made an interesting observation... We have a test orchestration logic that runs every spec file in a separate Docker container (one container is in charge of executing one spec file). We can control the level of parallelism (aka the maximum number of test containers that can run at the same time). If I set `PARALLEL = 1` for **Chrome Beta** (aka if I force a sequential execution), then I don't get the error (but executing the tests takes 1h 13m instead of 14m). For **Chrome**, the tests are successful with `PARALLEL = 7` (everything is the same, just the browser is different)...

**Comment by mikejamesthompson** [comment]
Could this be related to #8258?

**Comment by thomas-jakemeyn** [comment]
I quickly checked our codebase and we don't launch any sub-window while executing the TestCafe tests.

**Comment by shivaprasad-inmar** [comment]
Facing the same issue, running the same test case bunch and seeing websocket errors.

**Comment by aprabh001c** [comment]
how can we use this fixed version or when it will be published?

**Comment by thomas-jakemeyn** [comment]
Thank you for fixing this problem! Any idea when the fix will be released?

**Comment by Bayheck** [comment]
Hello, 

We can not give an ETA on when we will release this fix. Hopefully, it will be in the next TestCafe release.

**Comment by thomas-jakemeyn** [comment]
When is the next release planned?
Would it be possible to backport that fix and release it as a patch?

**Comment by RafaelBeltranClip** [comment]
I'm also facing the same issues and waiting for the release of the fix. Any updates on when it might be available?

**Comment by ChrisLane** [comment]
@PavelMor25 Are you aware your release candidate wasn't published yesterday?

**Comment by Bayheck** [comment]
Hello, yes we are aware of that. We are working on publishing right now.

**Comment by TsvetanTsvetkovClevertap** [comment]
Hello, 
Just checking if there are news about the release candidate.
Which version should we specify in package.json to test if the fix works?

**Comment by Bayheck** [comment]
Hello,

We published 3.7.0-rc.1. Please take a look.

**Comment by SamShot81** [comment]
Hi, this is broken again. 

Running tests in Azure Devops Pipeline Agent with command : 
**testcafe chrome --disable-search-engine-choice-screen ./Tests --reporter spec,xunit:report.xml**

This gives the following error:

ERROR Unable to open the "chrome:" browser due to the following error:

Error: WebSocket connection closed
    at D:\a\1\s\node_modules\chrome-remote-interface\lib\chrome.js:94:35
    at Chrome._handleConnectionClose (D:\a\1\s\node_modules\chrome-remote-interface\lib\chrome.js:256:13)
    at WebSocket.<anonymous> (D:\a\1\s\node_modules\chrome-remote-interface\lib\chrome.js:243:22)
    at WebSocket.emit (node:events:519:28)
    at WebSocket.emit (node:domain:488:12)
    at WebSocket.emitClose (D:\a\1\s\node_modules\ws\lib\websocket.js:246:10)
    at Receiver.receiverOnFinish (D:\a\1\s\node_modules\ws\lib\websocket.js:1060:20)
    at Receiver.emit (node:events:519:28)
    at Receiver.emit (node:domain:488:12)
    at finish (node:internal/streams/writable:953:10)
    
Is there anywork around for time being ? Do we have an ETA ?
Thanks.

**Comment by joshuaegclark-rally** [comment]
@Bayheck What is the process for this getting released to `latest`? I tried the RC 1 and it seems to resolve the issue with chrome 130 (which is awesome!), but I don't want to commit bumping to an RC if it will hit latest shortly

**Comment by Bayheck** [comment]
Hello,
Personal predictions can be unreliable, so we are not ready to give you an ETA.

Please stay tuned.
