### ISSUE TITLE
Chrome does not start correctly in headless mode on Windows 11 (Chrome Version 129.0.6668.90)

### ISSUE THREAD

**Issue by GregorBiswanger** [DevExpress/testcafe#8294]
### What is your Scenario?

I am running tests in headless mode using **TestCafe version 3.6.2** and **Google Chrome version 129.0.6668.90** on **Windows 11**.

### What is the Current behavior?

When I execute the following command:
`npx testcafe chrome:headless e2e`

a blank, white Chrome window opens, but no content is displayed. The test seems to hang without progressing.

I also tried running the new headless mode using the following command:
`npx testcafe "chrome:--headless=new" e2e`

This results in the same issue. The only command that works is:
`npx testcafe "chrome:--headless=old" e2e`

### What is the Expected behavior?

The tests should run in headless mode with Chrome, displaying the page content without opening a visible Chrome window.

### What is the public URL of the test page? (attach your complete example)

N/A (this issue occurs in a local project).

### What is your TestCafe test code?

Basic e2e test structure.

### Steps to Reproduce

1. Run `npx testcafe chrome:headless` with Google Chrome version 129.0.6668.90 on Windows 11.
2. Observe that a blank, white window opens and the test hangs.

### TestCafe version

3.6.2

### Command-line arguments

npx testcafe chrome:headless e2e

**Comment by PavelMor25** [comment]
Duplicate #8287
