### ISSUE TITLE
Not possible to type text in code mirror editor, after it was clicked

### ISSUE THREAD

**Issue by wombatka** [DevExpress/testcafe#8321]
### What is your Scenario?

When i click in the code mirrror editor i cannot type text because Uncaught error occurs

### What is the Current behavior?

 Error occurs on test run
✖ Type text

   1) Uncaught object "{"callsite":{"filename":"/home/asia/testcafeExample/example.js","lineNum":12,"callsiteFrameIdx":5,"stackFrames":[{},{},{},{},{},{},{},{},{},{}],"isV8Frames":true}}" was thrown. Throw Error instead.

      Browser: Chrome 130.0.0.0 / Ubuntu 22.04

### What is the Expected behavior?

It should be possible to type text after click without errors

### What is the public URL of the test page? (attach your complete example)

example.js:

import {Selector, t} from "testcafe";

fixture`Open navigation`
    .beforeEach(async t => {
        await t.navigateTo("https://codemirror.net/");
        
    })

test("Type text", async t => {
    const editor = Selector("[contenteditable=true]");
    await t.click(editor);
    await t.typeText(editor, "text1");
});

package.json:

{
  "name": "testcafeexample",
  "version": "1.0.0",
  "description": "",
  "main": "example.js",
  "scripts": {
    "test": "testcafe chrome example.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "testcafe": "3.7.0-rc.2"

  }
}

### What is your TestCafe test code?

example.js:

 import {Selector, t} from "testcafe";

fixture`Open navigation`
    .beforeEach(async t => {
        await t.navigateTo("https://codemirror.net/");
        
    })

test("Type text", async t => {
    const editor = Selector("[contenteditable=true]");
    await t.click(editor);
    await t.typeText(editor, "text1");
});

package.json:

{
  "name": "testcafeexample",
  "version": "1.0.0",
  "description": "",
  "main": "example.js",
  "scripts": {
    "test": "testcafe chrome example.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "testcafe": "3.7.0-rc.2"

  }
}

### Your complete configuration file

none

### Your complete test report

 Running tests in:
 - Chrome 130.0.0.0 / Ubuntu 22.04

 Open navigation
 ✖ Type text

   1) Uncaught object "{"callsite":{"filename":"/home/asia/testcafeExample/example.js","lineNum":12,"callsiteFrameIdx":5,"stackFrames":[{},{},{},{},{},{},{},{},{},{}],"isV8Frames":true}}" was thrown. Throw Error instead.

      Browser: Chrome 130.0.0.0 / Ubuntu 22.04

 1/1 failed (11s)

Make changes to the source files or press Ctrl+R to restart the test run.

### Steps to Reproduce

1.Open url https://codemirror.net/
2. click the editor
3.type text in editor

### TestCafe version

3.7.0-rc.2

### Node.js version

21.7.1

### Command-line arguments

npm test

### Browser name(s) and version(s)

chrome 130.0

### Platform(s) and version(s)

Ubuntu 22.04.2 LTS

**Comment by markusguenther** [comment]
I also stumbled over this issue while running tests on a CKEditor implementation. For some cases, I could add some workarounds, but it would be soo cool if there would be a proper solution.

Thanks for all the work. ❤️
