### ISSUE TITLE
testcafe just stops/hangs when I added --disable-search-engine-choice-screen in package.json

### ISSUE THREAD

**Issue by phingankar** [DevExpress/testcafe#8333]
<img width="479" alt="Screenshot 2024-11-04 at 5 06 54 pm" src="https://github.com/user-attachments/assets/365f8230-ba9f-42b4-9340-501f09f10589">

### What is your Scenario?

I had  to add --disable-search-engine-choice-screen in my package.json since testcafe is not working on latest chrome version

 "production": "export NODE_ENV=production &&  npx testcafe ${BROWSER:-\"chrome --start-fullscreen --disable-search-engine-choice-screen\"} tests/* --debug-on-fail"

### What is the Current behavior?

On running the specific test by fixture.only, the chrome doesnt respond/hangs on running the test

### What is the Expected behavior?

The test should run successfully.

### What is your TestCafe test code?

fixture.only`Directory Listing Page`.page(url.root);
test('Display Top 3 Banner Ads with correct speciality and location', async (t) => {
    await Steps.search(
        'Psychologist in melbourne 3000',
        'specialties_in_localities',
        'Psychologist in Melbourne VIC 3000',
    );
    await t
        .expect(DirectoryListingPO.directoryListingBannerAds.count)
        .gte(2)
        .expect(DirectoryListingPO.titleTextContent())
        .contains(
            'Psychologists in Melbourne VIC 3000',
            'Title does not exist or incorrect',
        )
        .expect(
            DirectoryListingPO.directoryListingBannerAdSpeciality.withText(
                'Psychologist',
            ).count,
        )
        .gte(2)
        .expect(DirectoryListingPO.directoryListingBannerAdSpecialityFeaturedTitle.withText(
            'Featured',
            ).count,
        )
        .gte(2);
})

### Steps to Reproduce

1. Add export NODE_ENV=production &&  npx testcafe ${BROWSER:-\"chrome --start-fullscreen --disable-search-engine-choice-screen\"} tests/* --debug-on-fail in package.json
2. Add fixture.only
3. Run the test in chrome

### TestCafe version

3.6.2

### Node.js version

v18.12.1

### Command-line arguments

npm run production

### Browser name(s) and version(s)

Chrome 130.0.6723.92

### Platform(s) and version(s)

Macos

**Comment by Bayheck** [comment]
Hello,

Please try the latest version of TestCafe 3.7.0. If the issue persists, please share a [minimal working example](https://testcafe.io/documentation/402636/faq/general-info?search#how-to-create-a-minimal-working-example-when-you-submit-an-issue) so that the TestCafe team can investigate the issue in more detail.
