### ISSUE TITLE
After SSH Connection in TestCafe while executing Commands I am not able to load Aliases for them, how to handle and resolve this?

### ISSUE THREAD

**Issue by yashsharma115** [DevExpress/testcafe#8354]
### What is your Scenario?

In TestCafe I made a **SSH Connection**, forming a **non-interactive session**, now when I execute **command with aliases** I am **unable to execute the commands** as error is coming that **command not found**.

If I am doing it in an **interactive session**, the **commands are executing fine**. 

### What is the Current behavior?

The current behaviour is that the **commands with aliases are executing fine in interactive session of SSH but not in non-interactive session of SSH** as aliases are not loading, if I remove the aliases and replace it with the actual command, it runs fine and no error is coming then.

### What is the Expected behavior?

In **non-interactive session also I want that the commands with aliases should execute fine** and the aliases should load.

### What is the public URL of the test page? (attach your complete example)

I have shared the **Sample Code** you can **create sample using the steps mentioned in Steps to Reproduce**.

Repo for reference - https://github.com/yashsharma115/testCafeExample

### What is your TestCafe test code?

const { NodeSSH } = require('node-ssh');

const ssh = new NodeSSH();

// SSH Configuration
const sshConfig = {
  host: 'your_hostname',   // Replace with your server's IP or hostname
  username: 'your_username',  // Replace with the SSH username
  password: 'your_password',  // Use password or privateKey
  // privateKey: '/path/to/your/private-key',  // Optional if using SSH key authentication
};

async function executeSSHCommands() {
  try {
    // Establish SSH connection
    console.log('Connecting to the server...');
    await ssh.connect(sshConfig);
    console.log('SSH connection established!');

    // List of commands to execute
    const commands = [
      'mylist'
    ];

    // Execute commands sequentially
    for (const command of commands) {
      console.log(`Executing command: ${command}`);
      const result = await ssh.execCommand(command);
      console.log(`STDOUT: ${result.stdout}`);
      console.log(`STDERR: ${result.stderr}`);
    }

    console.log('All commands executed successfully!');
  } catch (error) {
    console.error('Error during SSH execution:', error.message);
  } finally {
    ssh.dispose(); // Close the SSH connection
    console.log('SSH connection closed.');
  }
}

// Run the function
executeSSHCommands();

### Screenshots

**For Non-Interactive session by node-ssh**

![image](https://github.com/user-attachments/assets/56c03d81-e4b9-4f7e-820e-d11e76133826)

**For Interactive session**

![image](https://github.com/user-attachments/assets/64ee35b5-14aa-404a-b08e-6be2da22e9f0)

### Steps to Reproduce

I have **Rocky Linux Container** in which I **create SSH connection** and the steps followed are -

1. Now login and **create SSH connection in cmd by command -> ssh username@IP_Address**.
2. Then **enter your password**.
3. After it create an alias like-> **alias mylist='ls -la'**.
4. Now **execute command in cmd-> mylist**, you will get the output as shown above in first screenshot.
5. Give the name to the file given above as sample code-> **sshCommand.js**.
6. Then **run the sample code with command-> node sshCommand.js in the terminal** after installing **packages testcafe and node-ssh**.
7. The output in the terminal is shown in the second screenshot above, kindly check it.
8. The error coming-> **mylist command not found**

### TestCafe version

3.7.0

### Node.js version

16.2.0

### Command-line arguments

node sshCommand.js

**Comment by Bayheck** [comment]
Hello,

Unfortunately, your scenario is out of TestCafe scope. I will close this issue.
