### ISSUE TITLE
Unable to run Chrome with Node 22

### ISSUE THREAD

**Issue by AleksandrSubach** [DevExpress/testcafe#8355]
### What is your Scenario?

Run TestCafe test example

### What is the Current behavior?

ERROR Unable to open the "chrome:" browser due to the following error:

Error: connect ECONNREFUSED ::1:62666
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)

### What is the Expected behavior?

Test pass

### What is the public URL of the test page? (attach your complete example)

https://devexpress.github.io/testcafe/example/

### What is your TestCafe test code?

```
import page from './page-model';

fixture `A set of examples that illustrate how to use TestCafe API`
    .page `https://devexpress.github.io/testcafe/example/`;

// Tests
test('Text typing basics', async t => {
    await t
        .typeText(page.nameInput, 'Peter') // Type name
        .typeText(page.nameInput, 'Paker', { replace: true }) // Replace with last name
        .typeText(page.nameInput, 'r', { caretPos: 2 }) // Correct last name
        .expect(page.nameInput.value).eql('Parker'); // Check result
});
```

### Steps to Reproduce

1. Install Node 22
2. Run test
3.

### TestCafe version

3.7.1

### Node.js version

v22.12.0

### Command-line arguments

 testcafe chrome tests/test.js

### Browser name(s) and version(s)

Chrome 131

### Platform(s) and version(s)

Windows 10

### Other

On Node 20 everything works as expected

**Comment by andreastorp** [comment]
I see the same issue when running testcafe in GitHub Actions using [windows-latest]. I also see the same error when running against edge.

I can confirm that the following "fixes" works for me:
- Downgrade to Node 20
- Run in [ubuntu-latest] instead
- Run Firefox instead

**Comment by PavelMor25** [comment]
duplicate #8350
