### ISSUE TITLE
Support the 'release' issue

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#85]
Build bot should recognize the issue with a special 'release' title and create a comment in the issue with list of issues closed after the last release and the guide 'what you should do before release'

**Comment by AlexanderMoskovkin** [comment]
Some updates:
- the issue will have the `release` label;
- bot should create a comment with the checklist 'what should you do before release';
- bot should create a comment with list of issues closed after the last release;
- bot should create a link to regenerate the list of the issues

**Comment by inikulin** [comment]
* Bot should suggest version number based on list (reading package json and analyzing API MODIFICATION LEVEL labels)
 * Issues list should contain information about API modification level
 * Bot should create warning comment if commit in PR doesn't have `closes/fixes/fix` directives
 * Bot should create comment which warns about missing `API MODIFICATION LEVEL` label once the issue gets closed. It should re-issue the warning comment two times a day until the label will not be set.

**Comment by AlexanderMoskovkin** [comment]
- when an issue with the `documentation required` label is closed Bot should open a new issue ('Create documentation for ...') and assign it to the chief technical writer ( @VasilyStrelyaev for now)
- when the `release` issue is opened Bot should create a checklist with opened `documentation` issues

**Comment by inikulin** [comment]
@AlexanderMoskovkin We need also task which will ping developer if label is not set (like for the API modification level labels)

**Comment by AlexanderMoskovkin** [comment]
>We need also task which will ping developer if label is not set (like for the API modification level labels)

updated the previous comment

**Comment by AlexanderMoskovkin** [comment]
- when the `release` issue is opened Bot turns on the `code freeze` mode. It add warnings to all new pull requests. (Optional) We should merge only pull requests with a `pre-release` label during the `release` issue is opened
- when the `release` issue is closed Bot send a comment to all pull requests about that
- Bot adds the release version to closed issues when the `release` issue is closed

**Comment by inikulin** [comment]
Planned in build bot.
