### ISSUE TITLE
Add `speed` option for actions

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#865]
# Proposal

This affects to delay between action parts (for example between mousedown and mouseup in `click`, or between each symbol typing in `typeText`), to the cursor speed. This option you can use if you need to emulate human-behavior (it can be useful for cases when your scripts work properly only if you do actions no too fast).

Now we have the following [options](https://github.com/DevExpress/testcafe/blob/master/docs/articles/documentation/test-api/actions/action-options.md): `Mouse Action Options, Click Action Options, Typing Action Options`.
I suppose it should be a new type of options: 
```js
Action Options: { speed: <number> }
```
 Mouse, Click and Typing options extend it.
So, we add `options` argument to [`Select Text`](https://github.com/DevExpress/testcafe/blob/master/docs/articles/documentation/test-api/actions/select-text.md), [`Type Text`](https://github.com/DevExpress/testcafe/blob/master/docs/articles/documentation/test-api/actions/type-text.md) and [`Press Key`](https://github.com/DevExpress/testcafe/blob/master/docs/articles/documentation/test-api/actions/press-key.md) actions.

### Multiply

If the test run speed options is set to some `value1` and action option is set to the `value2` - it will be multiplied and the action will be executing with speed `value1 * value2`

**Comment by inikulin** [comment]
Note that factors should multiply, so if we have `0.5` set in test controller and `0.5` for action the resulting speed should be `0.25`

**Comment by inikulin** [comment]
Also I guess it should be between `0.1` and `1`

**Comment by AlexanderMoskovkin** [comment]
I've updated the first post with feature proposal. What do you think about it?

\cc @inikulin @VasilyStrelyaev @DevExpress/testcafe

**Comment by inikulin** [comment]
@AlexanderMoskovkin I don't think we need test controller option. There should be CLI and programmatical API option. Also, min value should be `0.01`

**Comment by georgiy-abbasov** [comment]
> Multiply

Imho, there should be  `action speed` option priority upon `testController speed` option and they should be independent. For example: we have a test where all actions should be executed quickly except one. Multiply in this case can be confusing:
```
test `my test` (async t => {
    t.speed = 5;
   // ... bunch of quick actions
   await t.click( { speed: 0.5 } )
   // ... bunch of quick actions
});
```

**Comment by helen-dikareva** [comment]
I don't really like idea to multiply factors. May be just use speed factor specified for action, if we don't have it - use factor specified for test controller.

**Comment by helen-dikareva** [comment]
By default it will be slow mode? speed === 1?

**Comment by AlexanderMoskovkin** [comment]
> By default it will be slow mode? speed === 1
1 - fast, 0.01 - slow

**Comment by helen-dikareva** [comment]
Sure, sorry

**Comment by AlexanderMoskovkin** [comment]
> I don't think we need test controller option. There should be CLI and programmatical API option.

Yes, I'm agree

**Comment by kirovboris** [comment]
I think the ```speed``` option for one action is almost useless, because it's hard to support and requires to much attention for separate actions. It's almost the same as random placed ```t.wait``` actions. In my opinion, the speed option is usefull, when i want to make slower test if it's requires more time between actions or to see what's going on at during test time.

**Comment by miherlosev** [comment]
I don't like idea to multiply factors too.

**Comment by AlexanderMoskovkin** [comment]
> I think the speed option for one action is almost useless

For example some ASPx controls doesn't work properly when you type (or click, dblclick, drag) too fast like a robot (some script expect human-behavior with some delays between actions) . With this option you can run only several actions in slow mode but run the others fast (it will decrease tests duration)

**Comment by AlexanderMoskovkin** [comment]
> Is possible a scenario where all actions are slow and one should be executed quickly ?

Can you give a real case when this may be useful. I can't

**Comment by AlexanderMoskovkin** [comment]
Ok, it was discussed in private, I'll update the top post a little later

**Comment by VasilyStrelyaev** [comment]
> I'll update the top post a little later

@AlexanderMoskovkin  Taking into account the discussion, the top post doesn't seem to be up-to-date yet. Have you already decided on all the things? Can you pls update it?

**Comment by AlexanderMoskovkin** [comment]
> Have you already decided on all the things?

Not yet. I'll notify you

**Comment by AlexanderMoskovkin** [comment]
I've updated the top post. Here describes api changes. /cc @inikulin @VasilyStrelyaev

**Comment by sirgallifrey** [comment]
+1 to having ability to delay or speed up certain actions.
