### ISSUE TITLE
Functional tests hang on MS Edge 14 on Saucelabs

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#872]
It was ok on MS Edge 13

**Comment by inikulin** [comment]
We've found only one issue locally: https://github.com/DevExpress/testcafe/issues/875 And the fix is on it's way. It seems like that Edge 14 is just unstable on Saucelabs for some reason. Let's try to turn it on a little bit later.

**Comment by AlexanderMoskovkin** [comment]
The problem is gone after migration to BrowserStack
