### ISSUE TITLE
Test hangs if element scroll is fractional

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#882]
Move automation fall to an endless loop, because the target point coordinates will be fractional in this case, and we use integer coordinates for the pointer current position, so they will never be equal.

**Comment by inikulin** [comment]
@AndreyBelym Can you provide a test code please?

**Comment by AndreyBelym** [comment]
It's related to https://isc.devexpress.com/Thread/WorkplaceDetails/T432527, I'll post a regression test and page for the test here.
