### ISSUE TITLE
Support HTML5 Drag and drop 

### ISSUE THREAD

**Issue by kirovboris** [DevExpress/testcafe#897]
### Are you requesting a feature or reporting a bug?

feature
### Specify your
- operating system: windows 7
- testcafe version: 0.9.0
- node.js version: 6.2.1

**Comment by vzaidman** [comment]
these guys are managed to do it for some libraries:
https://github.com/Kuniwak/html-dnd

**Comment by inikulin** [comment]
@vzaidman Thank you for sharing this. This feature is moved to the next print and more likely will be available in one of the alphas within a couple of weeks.

**Comment by AlexanderMoskovkin** [comment]
I'm working on this

**Comment by vzaidman** [comment]
@AlexanderMoskovkin 
By the way. I contributed to the other project. You might want to see this code too:
https://github.com/PowToon/html-dnd

**Comment by AlexanderMoskovkin** [comment]
@vzaidman Thanks! I'll take it into account

**Comment by sagarvora** [comment]
Hi @AlexanderMoskovkin,

Thanks for this PR! `drag` now works in the latest alpha release.

I encountered a bug in `dragToElement`.

You can test the following code:
```
import { Selector } from 'testcafe';

fixture `Example page`
    .page `http://demo.erpnext.com`;

test('Check login', async t => {
    const login_btn = Selector('#login_btn');
    const task_icon = Selector('.case-wrapper[data-link="List/Task"]');
    const item_icon = Selector('.case-wrapper[data-link="List/Item"]');    

    await t
        .click(login_btn)
        .setTestSpeed(0.5)
        .dragToElement(task_icon, item_icon)
        .wait(1000)
});

```

Upon execution of above code, you will notice that the Task Icon gets clicked after dragging.

**Comment by AlexanderMoskovkin** [comment]
Hi @sagarvora,

Thanks for your report, I've reproduced it and I've created a [separate issue](https://github.com/DevExpress/testcafe/issues/1516). I've already found a cause of the problem, it will be fixed in the next version that should be released soon.
