### ISSUE TITLE
resizeWindowToFitDevice Feature Request

### ISSUE THREAD

**Issue by Elric-pp** [DevExpress/testcafe#902]
### Are you requesting a feature or reporting a bug?

feature

### What is the expected behavior?

resizeWindowToFitDevice that can simulate the viewport and the device pixel ratio would be good to test the mobile first page.

**Comment by AndreyBelym** [comment]
Hi! Do you mean that `resizeWindowToFitDevice` must set correct `Window.devicePixelRatio` for the specified device, right?

**Comment by Elric-pp** [comment]
Yes，just act like chrome devtool. It is useful for css media query breakpoint.

**Comment by AndreyBelym** [comment]
Setting the correct `Window.devicePixelRatio` doesn't look hard, but making CSS queries working with different DPR may be so. I doubt DevTools uses some browser internal  API to do the trick, but we are restricted to the standard JS APIs. We need some time for investigation, if it's possible at all, Please, stay tuned!

**Comment by Elric-pp** [comment]
Thx, so far so good. 👍
