### ISSUE TITLE
Add recipe on how to test static files from local file system

### ISSUE THREAD

**Issue by lukasoppermann** [DevExpress/testcafe#904]
Sorry, but I did not find anything in the docs. Is it not possible to test local files? Like testContent.html?

**Comment by inikulin** [comment]
Hi! TestCafe requires page to be served via HTTP(S) protocol. However, you can easily serve static pages by using packages like [static-server](https://www.npmjs.com/package/static-server)

**Comment by lukasoppermann** [comment]
Ahh, okay, thanks. Maybe you could add a short "how to" to the docs?

**Comment by inikulin** [comment]
@lukasoppermann Sure, we have [Recipes](https://github.com/DevExpress/testcafe/tree/master/docs/articles/documentation/recipes) section for such things. Feel free to contribute or if your're busy we'll take care of it. Meanwhile, I'll convert this issue into documentation feature request.

**Comment by lukasoppermann** [comment]
Thanks, I am not 100% how to do it, I would be better suited to read the recipe than to write it. 😉

**Comment by inikulin** [comment]
@lukasoppermann No problem, we'll do it 😃  \cc @VasilyStrelyaev

**Comment by renancouto** [comment]
@lukasoppermann I run testcafe on local files using [http-server](https://github.com/indexzero/http-server) as a simple server and [concurrently](https://github.com/kimmobrunfeldt/concurrently) to run both processes together and kill the server before exiting.

```
concurrently -r -k "http-server" "http-server ./dist -p 4000 -s" "testcafe chrome ./test/acceptance/**"
```

**Comment by AlexanderMoskovkin** [comment]
@renancouto Great solution, thanks!

**Comment by renancouto** [comment]
@AlexanderMoskovkin created a PR for that if you like: https://github.com/DevExpress/testcafe/pull/970

**Comment by AlexanderMoskovkin** [comment]
[done](https://github.com/DevExpress/testcafe/blob/master/docs/articles/documentation/recipes/test-static-html-pages.md)
