### ISSUE TITLE
Allow flags for browsers

### ISSUE THREAD

**Issue by felipenmoura** [DevExpress/testcafe#905]
Feature Request
### What is the current behavior?

Flags are not passed to the opening browser.
### What is the expected behavior?

The browser on which the test will run, should receive the flags
### How would you reproduce the current behavior (if this is a bug)?

I'm trying to use Service Workers in the page, but they require `localhost` or `https` and _testcafe_ is currently redirecting the browser to a server of itself (therefore, not https neither localhost). I could send a couple flags to the browser and it would not be a problem:

```
testcafe chrome --ignore-certificate-errors --unsafely-treat-insecure-origin-as-secure=* tests/
```
### Specify your
- operating system: MacOS Sierra
- testcafe version: 0.9.0
- node.js version: 4.2.6

**Comment by AlexanderMoskovkin** [comment]
Hi! While it doesn't work via [Command Line Interface](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html) you can use [Programming Interface](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/) as a workaround. You can see how to specify the Path to the Browser Executable with Command Line Parameters [here](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#specifying-the-path-with-command-line-parameters)

**Comment by felipenmoura** [comment]
Interesting, thanks!
But in this case, I must specify both `path` and `cmd`...and defining the path is not an easy task to do if I want it to run it in many different machines (including travis, for example).
Is there a way I could say "chrome" and the flags(cmd), perhaps?

**Comment by AlexanderMoskovkin** [comment]
Yes, you can use the [getBrowserInfo](https://github.com/DevExpress/testcafe-browser-tools/blob/master/API.md#async-getbrowserinfobrowser--browserinfo) function from our [TestCafe Browser Tools](https://github.com/DevExpress/testcafe-browser-tools) package. For example:
```js
const testcafeBrowserTools = require('testcafe-browser-tools');
const createTestCafe       = require('testcafe');

var chromeInfo = null;

testcafeBrowserTools
    .getBrowserInfo('chrome')
    .then(res => {
        chromeInfo = res;

        chromeInfo.cmd = `${chromeInfo.cmd} --incognito`;   // add your flags here
    })
    .then(() => createTestCafe('localhost', 1337, 1338))
    .then(testcafe => {
        return testcafe
            .createRunner()
            .src('your-test.js')
            .browsers(chromeInfo)
            .run();
    });
```

**Comment by inikulin** [comment]
I believe it's worth implementing on our side: add ability to specify browser parameters for aliases. But command line syntax requires some bike shedding. 
Maybe something like:
```sh
testcafe "chrome --ignore-certificate-errors --unsafely-treat-insecure-origin-as-secure=*" tests/
```

**Comment by felipenmoura** [comment]
Thanks @AlexanderMoskovkin, will try that, then.

@inikulin I think that would be an amazing implementation (using quotes), this way we could even use two or more browsers, sending to each one, its own flags.

As for _my situation_, all I need is it to be opened in the browser as `localhost`. I noticed you start a server in my machine's IP in the given ports...do testcafe **must** open it as an IP address? I mean, `localhost:port` would work as well, and would allow people to even use their `hosts` file or rules for "localhost" special treatments (as in my case, from Service Workers spec).

**Comment by inikulin** [comment]
> As for my situation, all I need is it to be opened in the browser as localhost. I noticed you start a server in my machine's IP in the given ports...do testcafe must open it as an IP address? I mean, localhost:port would work as well, and would allow people to even use their hosts file or rules for "localhost" special treatments (as in my case, from Service Workers spec).

You can specify `localhost` or your machine instead of IP address via [--hostname command line option](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--hostname-name). Initially, we've used localhost as default hostname for TestCafe server, but it had some performance problems with SauceLabs tunnel (I can't find issue references at the moment, guys can you provide some insights here please \cc @DevExpress/testcafe). So we decided to use NetBIOS name as a hostname, but it had problems with Edge browser: https://github.com/DevExpress/testcafe/issues/575 So we finally ended up using IP address as a solution that works properly with all platforms. Overall, if you're testing on local machine `localhost` should work just fine for you.

**Comment by felipenmoura** [comment]
Thank you @inikulin , I'm using it and it is working. I believe I will manage to have it published pretty soon :)
Will keep you up to date to check on ways (still working on it) to test service workers.

**Comment by sdeprez** [comment]
I didn't find in the docs but after some digging of the source code, it seems that the following syntax is also supported:
```
await createTestCafe()
  .src('file.ts')
  .browsers('chrome --incognito --no-sandbox')
```
