### ISSUE TITLE
Support .GIF to record the progress of a test

### ISSUE THREAD

**Issue by jkswoods** [DevExpress/testcafe#906]
### Are you requesting a feature or reporting a bug?

Requesting a feature
### What is the current behavior?

Still screenshots
### What is the requested behavior?

Recording the progress of a test and saving it as an animated gif in a specified folder once the test is complete.
### Specify your
- operating system: macOS 10.12
- testcafe version: 0.9.0
- node.js version: 6.5.0

**Comment by inikulin** [comment]
Hi @jkswoods.

Great idea! We have two ways how it can be done:
1. Make screenshots on each test action. So you will end up with gif that is composed of discrete static screenshots, like slide show of test state.
2. Record full video, like screencast feature in SauceLabs. 

Personally, I prefer first option. With second option you will have huge screencast files after each test run and I'm not sure if we'll be able to capture screen for browser that run in parallel. Please, let me know if it will work for you.

**Comment by jkswoods** [comment]
I'll have to agree with you on that one. The first option does seem like the best and will work in my case.

Thanks, @inikulin!

**Comment by AlexanderMoskovkin** [comment]
closed in favor of #2151
