### ISSUE TITLE
TestCafe run fails on non ubuntu/debian systems

### ISSUE THREAD

**Issue by derveloper** [DevExpress/testcafe#915]
### Are you requesting a feature or reporting a bug?

Reporting a bug
### What is the current behavior?

It does not run on non Ubuntu/Debian systems
It fails with

```
ERROR Was unable to open the browser "path:/usr/bin/chromium" due to error.

Command failed: update-alternatives --list x-www-browser
/bin/sh: update-alternatives: command not found
```
### What is the expected behavior?

It runs on any linux system e.g. on arch linux
### How would you reproduce the current behavior (if this is a bug)?

On arch linux run `testcafe path:/usr/bin/chromium *.test.js`
### Specify your
- operating system: arch linux
- testcafe version: 0.9.0
- node.js version: 6.6.0

**Comment by AndreyBelym** [comment]
Hi! Thank you for the issue! Browser autodetection do not work currently on non-Debian distros, but of course `testcafe` should be able to start browsers by path. BTW we will implement different mechanism to detecting browsers soon: https://github.com/DevExpress/testcafe-browser-tools/issues/104. Until it's done you can use remote browsers as workaround.
