### ISSUE TITLE
Add `t.debugger` action

### ISSUE THREAD

**Issue by churkin** [DevExpress/testcafe#918]
I want to be able to stop the test to debug:

``` javascript
await t
   .click('body')
   .debugger
   .click('#main_window');
```

After first clicking the test should stand on pause. During the pause, I can take any action in the browser console. To continue the test, I need to press the specifically button ("Continue test..." for example).

**Comment by helen-dikareva** [comment]
I'm working on this

**Comment by helen-dikareva** [comment]
![debugger](https://cloud.githubusercontent.com/assets/12034551/21496815/56763846-cc32-11e6-8486-fa8dd8d4b358.png)
