### ISSUE TITLE
click cannot be fired using hammer.js

### ISSUE THREAD

**Issue by Elric-pp** [DevExpress/testcafe#927]
### Are you requesting a feature or reporting a bug?

bug
### What is the current behavior?

click can not be fired when using hammer.js
### What is the expected behavior?

click can be fired. Beacause in response website alaways using gesture like tap.
### How would you reproduce the current behavior (if this is a bug)?

https://jsfiddle.net/ystg8wt4/
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

``` js
fixture `tap`
  .page('http://localhost:9002')

test(`Should alert hello`, async t => {
  await t
    .click('#tap')

  var history = await t.getNativeDialogHistory()
  await t
    .typeText('#input', history.length.toString())
})

```
### Specify your
- operating system: macOS Sierra
- testcafe version: testcafe 0.9.0
- node.js version: V6.9

**Comment by AlexanderMoskovkin** [comment]
Hi @Elric-pp,
I've checked your scenario. It seems testcafe clicks correctly but it necessary to add the [setNativeDialogHandler](https://github.com/DevExpress/testcafe/blob/master/docs/articles/documentation/test-api/handling-native-dialogs.md#dialog-handler) method to handle `alert` dialog.

I've modified your test, please check does it work on your side:
```js
import { Selector } from 'testcafe';
import { equal } from 'assert';

fixture `tap`
    .page('https://jsfiddle.net/ystg8wt4/')

test(`Should alert hello`, async t => {
    await t
        .switchToIframe('iframe[name=result]')
        .setNativeDialogHandler(() => {
        })
        .click('#tap')

    var history = await t.getNativeDialogHistory();

    await t
        .typeText('#input', history.length.toString())

    var inputSnapshot = await Selector('#input')();

    equal(inputSnapshot.value, '1');
})
```

**Comment by Elric-pp** [comment]
Hi, @AlexanderMoskovkin
It's seems to be chrome's bug. 
The test is pass on safari and firefox, but fails in chrome

Chrome Vesion: Chrome 56.0.2904 / Mac OS X 10.12.0

**Comment by AlexanderMoskovkin** [comment]
I see the test is ok in Chrome 54 (the last stable version), but it is failed in Chrome 55 (Beta channel) and Chrome 56 (Dev channel). We will investigate the issue.

**Comment by helen-dikareva** [comment]
It was fixed https://github.com/DevExpress/testcafe-hammerhead/issues/903
Please check test
