### ISSUE TITLE
Different behavior in the App and in Terminal via npm module

### ISSUE THREAD

**Issue by kaihaase-wd** [DevExpress/testcafe#931]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
I've got a problem to run tests with your TestCafe-App (Mac and Windows) and the npm version in the terminal.

I've created a test via App and get a valid result. But when I start the test in terminal an error occurs for GET-Request:

http://172.16.20.63:51526/HJj7N6Vee/http://localhost:1340/api/v1/users/?skip=0&limit=10

Request Header:
Accept	application/json, text/plain, */*
Accept-Encoding	gzip, deflate
Accept-Language	de,en-US;q=0.7,en;q=0.3
Authorization	JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImNyZWF0ZWRCeSI6IjU4MDRhMDU4MDZjMDczMmYwNWMzM2YyMyIsInVwZGF0ZWRCeSI6IjU4MDRhMDU4MDZjMDczMmYwNWMzM2YyMyIsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGNhbXBhcm91bmQuZGUiLCJmaXJzdE5hbWUiOiJTeXN0ZW0iLCJsYXN0TmFtZSI6IkFkbWluaXN0cmF0b3IiLCJjcmVhdGVkQnlOYW1lIjoiU3lzdGVtIEFkbWluaXN0cmF0b4aIiLCJ1cGRhdGVkQnlOYW1lIjoiU3lzdGVtIEFkbWluaXN0cmF0b3IiLCJyb2xlcyI6WyJhZG1pbiJdLCJsYW5ndWFnZSI6ImVuIiwibG9jYWxlIjoiZGUiLCJjcmVhdGVkQXQiOiIyMDE2LTEwLTE3VDA5OjU2OjQwLjQ1M1oiLCJ1cGRhdGVkQXQiOiIyMDE2LTEwLTMxVDEyOjQxOjE0LjMzM1oiLCJpZCI6IjU4MDRhMDU4MDZjMDczMmYwNWMzM2YyMyJ9LCJpYXQiOjE0Nzc5MTk4MTAsImF1ZCI6IjJCZm0LmlvIiwiaXNzIjoiMkJmaXQuaW8ifQ.Q9RaKU2u16bmtw0ayKwVIfSa9NTd3jvVpAFaqNrm7-g
Host	172.16.20.63:51526
Referer	http://172.16.20.63:51526/HJj7N6Vee/http://localhost:8080/app/users
User-Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:49.0) Gecko/20100101 Firefox/49.0
X-Camparound	1
x-hammerhead|xhr|cors-sup...	true
x-hammerhead|xhr|origin	http://localhost:8080
x-hammerhead|xhr|request-...	true

The request runs into a timeout. A previous POST-Request (without JWT) in the same test worked well in both (App and Terminal). 

### What is the expected behavior?
Both (App and Terminal) should lead to the same result.

### Speculation
It may be due to the JWT (JavaScript Web Token). But our server would send a HTML-Error-Response-Message and not nothing. It also works with the app version, so why not in Terminal?

### Specify your

* operating system: Mac OS 10.12.1 / Windows 10
* testcafe version: App 15.1.2, npm module testcafe@0.9.0
* node.js version: 6.8.1

**Comment by AndreyBelym** [comment]
Hello @kaihaase-wd! I'm really sorry, but unfortunately, we do not support HTTP Authorization yet in npm version of TestCafe (including JWT). But we are going to implement it soon, you can check the progress here: https://github.com/DevExpress/testcafe/issues/509.

**Comment by kaihaase-wd** [comment]
@AndreyBelym Thank you very much for your fast answer. We love your product, but for the integration in our stack we need the support for JWT in the npm version. When is an implementation of the support planned? We would like to support you with the integration, or is there a way to take over the source code from the app version?

**Comment by AndreyBelym** [comment]
@kaihaase-wd it will be here in next few iterations, might be even just in the next one. It's about a couple of weeks, I think.

**Comment by kaihaase-wd** [comment]
@AndreyBelym sounds good, let us know if we can support you.

**Comment by churkin** [comment]
@kaihaase-wd We would be grateful if you could help us implement this feature.
If you are interested, I'll tell you the details, and of course, I will help you with everything.

**Comment by kaihaase-wd** [comment]
@churkin I would like to support you. What is the most efficient way for implementation? Are there guidelines or do I have to consider anything special? Let me know how we should communicate to talk about further details, slack or mail, whatever you prefer.

**Comment by churkin** [comment]
@kaihaase-wd This is great news :). I will create a new issue and will try to describe how and what we need to do. I'll let you know.

Thank you.

**Comment by churkin** [comment]
@kaihaase-wd https://github.com/DevExpress/testcafe/issues/955
