### ISSUE TITLE
Add possibility to run tests on https://crossbrowsertesting.com/

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#932]
All our concurents integrates with https://crossbrowsertesting.com/
For more details see https://crossbrowsertesting.com/integrations

**Comment by inikulin** [comment]
I doubt we'll ever implement it

**Comment by sijosyn** [comment]
@miherlosev @inikulin - We are using CrossBrowserTesting platform in our company and if we had access to this browser provider, then we could easily run our TestCafe test scripts there. Could you please reconsider making crossbrowsertesting.com browser provider available for us?

**Comment by AlexanderMoskovkin** [comment]
Hi @sijosyn,

Thanks for your proposal. I doubt we'll implement it in the nearest future but we will be happy if someone is ready to do it. 
Here is a guide how to create a new [Browser Provider Plugin](https://devexpress.github.io/testcafe/documentation/extending-testcafe/browser-provider-plugin/). And we have plugins for other cloud services: [BrowserStack](https://github.com/DevExpress/testcafe-browser-provider-browserstack) and [SauceLabs](https://github.com/DevExpress/testcafe-browser-provider-saucelabs). They can be used as an example how to implement such provider.

**Comment by sijosyn** [comment]
Hi @AlexanderMoskovkin,

Thanks Alex for providing the instructions to create a new browser provider plugin. I followed the guide and I'm was able to create [CrossBrowserTesting](https://crossbrowsertesting.com) browser provider plugin. I have published my implementation on Github & NPM. Links provided below:

Github : https://github.com/sijosyn/testcafe-browser-provider-crossbrowsertesting
NPM.  : https://www.npmjs.com/package/testcafe-browser-provider-crossbrowsertesting

**Comment by AlexanderMoskovkin** [comment]
Hi @sijosyn.

It's great! We'll definitely check it out and add it into our ecosystem section. Thanks a lot!

**Comment by sijosyn** [comment]
@AlexanderMoskovkin we can go ahead and close this ticket.  This work is completed.

**Comment by AlexanderMoskovkin** [comment]
@sijosyn Awesome! Thanks a lot!
