### ISSUE TITLE
How does testcafe internally works?

### ISSUE THREAD

**Issue by vitalets** [DevExpress/testcafe#934]
hi! 

this library looks great but it is not clear from readme how does it internally works.
Does it use [W3C Webdriver Spec commands](https://w3c.github.io/webdriver/webdriver-spec.html) or if not how it communicates with web pages?
I think it would be useful to add to readme.
Thanks!

**Comment by AlexanderMoskovkin** [comment]
Hi @vitalets,

TestCafe doesn't use WebDriver, but it's based on a [URL-rewriting proxy] (https://github.com/DevExpress/testcafe-hammerhead). With the proxy we inject scripts that emulate user actions via DOM API. @inikulin have described [in our discussion board](https://testcafe-discuss.devexpress.com/t/why-not-use-selenium/47) what the difference between TestCafe and WebDriver-based solutions.
Feel free to ask us about any further technical details.

**Comment by vitalets** [comment]
@AlexanderMoskovkin Thanks for the link!
Btw, how are dealing with alerts/prompts that block js thread?

**Comment by inikulin** [comment]
Hi @vitalets.

Native dialogs are handled via pre-specified handlers, see: https://devexpress.github.io/testcafe/documentation/test-api/handling-native-dialogs.html

**Comment by vitalets** [comment]
But do you technically do this? You overwrite `window.alert` and don't actually show dialog but store info that it was called?

**Comment by inikulin** [comment]
@vitalets Correct. For other dialogs that require actions from user (like `confirm`) we also execute pre-defined handlers to decide how dialog should be handled.

**Comment by vitalets** [comment]
Ok, thanks! 
Also what about parallel running of tests? is it possible? Did not fond this in docs..

**Comment by inikulin** [comment]
You mean parallel run in different browsers or parallelize task using different instances of the same browser? If the first one, it's already supported (e.g. `testcafe chrome,firefox` - will run tests in parallel in Chrome and Firefox). If the second one, it's possible from technical perspective, but we haven't received any requests for this feature yet. So once there will be a demand, we'll implement it.

**Comment by vitalets** [comment]
Ok, thanks for detailed explanation! 
I think we can close the issue =)

**Comment by miherlosev** [comment]
Yes, TestCafe supports IE11 ([Officially supported browsers](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/browser-support.html#officially-supported-browsers))

**Comment by MichelleGuoFRB** [comment]
Thank you @miherlosev!!

I have another question, can the test take screenshot of a webpage?

**Comment by miherlosev** [comment]
Yes, see [Take screenshot](https://devexpress.github.io/testcafe/documentation/test-api/actions/take-screenshot.html) documentation topic.

**Comment by MichelleGuoFRB** [comment]
Thanks a lot @miherlosev , some more questions;
