### ISSUE TITLE
Add full text seach to the https://devexpress.github.io/testcafe/

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#939]
Try to look links:
https://github.com/christian-fei/Simple-Jekyll-Search
https://github.com/slashdotdash/jekyll-lunr-js-search
https://github.com/cebe/js-search

**Comment by inikulin** [comment]
https://www.algolia.com/

**Comment by AlexanderMoskovkin** [comment]
@VasilyStrelyaev can we do this in the next sprint (#5)?

**Comment by AlexanderMoskovkin** [comment]
done in https://github.com/DevExpress/testcafe/pull/1265
