### ISSUE TITLE
Dispatching of touch events doesn't work in Chrome 54 on touch monitor

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#944]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

browser  hangs on and error raised

### What is the expected behavior?

dispatching without errors

### How would you reproduce the current behavior (if this is a bug)?

run any test with mouse action (e.g. drag)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js
fixture `Example page`
    .page('https://google.ru');

test('Drag', async t => {
    await t.drag('#lst-ib', 50, 50);
});

```

### Specify your

* operating system:
Window 10
* testcafe version:
0.10.0-rc1
* node.js version:
v4.4.7

**Comment by helen-dikareva** [comment]
I'm working on it. https://github.com/DevExpress/testcafe-hammerhead/pull/910

**Comment by helen-dikareva** [comment]
Wait for update Hammerhead version

**Comment by AlexanderMoskovkin** [comment]
Fixed with https://github.com/DevExpress/testcafe-hammerhead/commit/6d2da16b173d2d31c6d7e5ff9e73fa1b23e56835
