### ISSUE TITLE
Test for m.youtube.com hangs in Chrome Mobile 54

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#945]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Test hangs on my Moto E with Chrome Mobile 54, but worked well with Chrome Mobile 49. It also hangs on Chrome 54 when Device Emulation is enabled. There is an error in console log:
```
:50556/Skm0F6ugl!i/https://accounts.google.com/ServiceLogin?ltmpl=mobile&pa…riginal_url%253Dhttps%25253A%25252F%25252Fm.youtube.com%25252F%26app%3Dm:1 Refused to display 'http://172.22.6.226:50556/Skm0F6ugl!i/https://accounts.google.com/ServiceLo…Foriginal_url%253Dhttps%25253A%25252F%25252Fm.youtube.com%25252F%26app%3Dm' in a frame because it set 'X-Frame-Options' to 'DENY'.
```
### What is the expected behavior?
Test performs click on the search button, and search box appears on top of the page.

### How would you reproduce the current behavior (if this is a bug)?
Start the test below on Chrome Mobile 54, or use Device Emulation in Chrome 54.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://m.youtube.com
Test code

```js
fixture `Google`.page `https://youtube.com`;

test('test', async t => {
    await t
        .click('#koya_elem_2_1 > div._mssb > div._mqsb._mvsb > button > span')
        .wait(3000);    
});
```

### Specify your

* operating system:
Windows 10, Android 6.0.1
* testcafe version:
0.10.0-rc1
* node.js version:
6.8.0

**Comment by inikulin** [comment]
I guess it's a Hammerhead issue, @churkin can you try it via playground?

**Comment by churkin** [comment]
@inikulin  I'll do it

**Comment by LavrovArtem** [comment]
I'm working on this

**Comment by LavrovArtem** [comment]
> :50556/Skm0F6ugl!i/https://accounts.google.com/ServiceLogin?ltmpl=mobile&pa…riginal_url%253Dhttps%25253A%25252F%25252Fm.youtube.com%25252F%26app%3Dm:1 Refused to display 'http://172.22.6.226:50556/Skm0F6ugl!i/https://accounts.google.com/ServiceLo…Foriginal_url%253Dhttps%25253A%25252F%25252Fm.youtube.com%25252F%26app%3Dm' in a frame because it set 'X-Frame-Options' to 'DENY'.

This error occurs without hammerhead

**Comment by LavrovArtem** [comment]
@AndreyBelym let's check it on your side.

**Comment by AndreyBelym** [comment]
Looks like the error is not related to the bug, the test passes successfully with the error using `Mobile (no touch)` emulation mode. So likely we have problems with touch events in automations.

**Comment by AndreyBelym** [comment]
Fixed by now.
