### ISSUE TITLE
Test hangs on AJAX request

### ISSUE THREAD

**Issue by crudo** [DevExpress/testcafe#946]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behaviour?

Page is not loaded. Response from server is never returned.

### What is the expected behaviour?

Page is loaded.

### How would you reproduce the current behaviour (if this is a bug)?

Run the included test.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://secure.gooddata.com/account.html

Test code

```js
fixture `login`
    .page('https://secure.gooddata.com/account.html');

test('login', async (t) => {
    await t
        .typeText('.s-login-login', 'john@example.com')
        .typeText('.s-login-password', 'xxx')
        .click('.s-login-button');

    await t.select('.gd-header');
});
```
### Specify your

* operating system: macOS 10.12
* testcafe version: 0.9
* node.js version: 6.7.0

**Comment by LavrovArtem** [comment]
I'm working on this

**Comment by AlexanderMoskovkin** [comment]
Hi @crudo,

Thanks for the issue. We have reproduced the problem and we are working on it.

**Comment by georgiy-abbasov** [comment]
@crudo, could you please check the issue with our new release version (it's with alpha tag now) ? We've pushed some fixes that can help. To check it please run `npm install testcafe@alpha`

**Comment by crudo** [comment]
@georgiy-abbasov It works like a charm. Thanks a lot!

**Comment by AlexanderMoskovkin** [comment]
Great! I close the issue then.
