### ISSUE TITLE
Provide API to set focus on element

### ISSUE THREAD

**Issue by ganlanyuan** [DevExpress/testcafe#948]
### Are you requesting a feature or reporting a bug?
Feature: focus

### What is the current behavior?
Can't set focus on element.

### What is the expected behavior?
await t.focus('.my element');

**Comment by helen-dikareva** [comment]
Hello William Lin. Thank you for your interest in TestCafe. Here is how you can focus an element using ClientFunction.
```js
var focus = ClientFunction(() => {
    document.getElementById('element').focus();
});

await focus();
```
Earlier we've decided not to create a separate action for focus.
Let's discuss it again @DevExpress/testcafe

**Comment by ganlanyuan** [comment]
@helen-dikareva 
Thanks a lot, it works.
