### ISSUE TITLE
Demo-test-cafe is failed with proxy enviroment

### ISSUE THREAD

**Issue by s-adachi2016** [DevExpress/testcafe#949]
### Are you requesting a feature or reporting a bug?

feature:failed  test local enviroment with proxy 

### What is the current behavior?

demo-test-cafe is tested my enviroment with proxy.

> npm test

chrome started but localhost URL is unconnected and network error.

### What is the expected behavior?

I  expect that demo-test-cafe npm test is successed.

If proxy setting API is exist, please tell me proxy setting code.

### Specify your

* operating system:Win7
* testcafe version:15.1
* node.js version:4.5.0

**Comment by AlexanderMoskovkin** [comment]
Hi @s-adachi2016,

Please confirm, do you try to run tests via https://github.com/azu/demo-test-cafe module? And do you have testcafe version 0.9.0 ?

At first we need to know is it possible to open any localhost page in the browser on your machine. Let's create a simple nodejs server. Please do the following in the cmd:
1) Create a temporary dir and install `express` module:
```bash
mkdir test-server
cd test-server
npm install express
```
2) Create `server.js` file in your test directory:
```js
var express = require('express');
var app = express();

app.get('/', function (req, res) {
  res.send('Hello World!');
});

app.listen(54000, function () {
  console.log('Example app listening on port 54000!');
});
```

3) Run the server
```bash
node server.js
```

4) Try to open http://localhost:54000/

Is the page with `Hello World!` text opened?

**Comment by s-adachi2016** [comment]
Hello Alexander,

Thanks for reply.

>Please confirm, do you try to run tests via https://github.com/azu/demo-test-cafe module? 

I tryed to run https://github.com/azu/demo-test-cafe module.

>And do you have testcafe version 0.9.0 ?

Yes.

I confirmed package.json in demo-test-cafe module.

Note taht

  "dependencies": {
    "testcafe": "^0.9.0"
  }

> Is the page with Hello World! text opened?

I tryed to run a simple nodejs server and access to http://localhost:54000/ or http://(local IP :10.*.*.*):54000/.

I confirmed that Hello World! text opened.

**Comment by georgiy-abbasov** [comment]
Hi @s-adachi2016 
    
Thank you for your reply. Let's try TestCafe via [CLI](http://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html). For this, follow next steps:

1) Create the `example.test.js` file in a test directory:

```js
const assert = require("assert");
import {Selector} from 'testcafe';
const getElementById = Selector(id => document.querySelector(`#${id}`));
fixture('Example page')
    .page('http://devexpress.github.io/testcafe/example');

test('Type the developer name, obtain the header text and check it', async t => {
    await t
        .typeText('#developer-name', 'John Smith')
        .click('#submit-button');

    const articleHeader = await getElementById('article-header');
    const headerText = articleHeader.innerText;

    assert.equal(headerText, 'Thank you, John!');
});
```
2) Create a temporary dir and install TestCafe in the cmd:

```cmd
mkdir temp
cd temp
npm install testcafe@alpha
cd node_modules\testcafe\bin
```

3) Run the test in the cmd:

`
node testcafe chrome <path to example.test.js> --ports 1337,1338
`

Also try to set-up your firewall: add TestCafe to exceptions and open ports that were specified in the command line.

**Comment by s-adachi2016** [comment]
Hi georgiy-abbasov

Thank you for your reply.

I opened port 1337,1338 via Win7 Firewall Setting.

I tryed following command that you tell me

``
testcafe chrome test.js --ports 1337,1338
``

But test failed.

Dou you have other settings?

Please tell me firewall settings detail.

**Comment by georgiy-abbasov** [comment]
@s-adachi2016, thank you for your reply. 
It seems that nodejs applications don't have access to the web resources without proxy settings on your machine. Please perform the following steps to check this. Once we get the result from you, we will be able to continue the investigation of this issue.

1) Create a temporary directory:
```cmd
mkdir test-request
cd test-request
```

2) Create the `request.js` file in the `test-request` directory:

```js
var http = require("http");

http.get('http://www.example.com', function (res) {
    var statusCode = res.statusCode;

    if (statusCode !== 200) {
        console.log(` Request Failed.\n Status Code: ${statusCode}`);

        res.resume();
        return;
    }

    console.log(` Request Success.\n Status Code: ${statusCode}`);
});
```

3) Run `request.js` via Node.js:

```cmd
node request.js
```

Post the output here, please.

**Comment by s-adachi2016** [comment]
@georgiy-abbasov, thank you for your reply.

I tryed to following your code.

```
var http = require("http");

http.get('http://devexpress.github.io/testcafe/', function (res) {
    var statusCode = res.statusCode;

    if (statusCode !== 200) {
        console.log(` Request Failed.\n Status Code: ${statusCode}`);

        res.resume();
        return;
    }

    console.log(` Request Success.\n Status Code: ${statusCode}`);
});
```

Output is following.

```
$ node request_proxy.js
```

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT (IP Address):80
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)
```

**Comment by s-adachi2016** [comment]
I added your code for proxy setting and modify following:

```
var Http = require('http');
 
var req = Http.request({
    host: 'proxy host name',
    // proxy IP
    port: 8080,
    // proxy port
    method: 'GET',
    path: 'http://devexpress.github.io/testcafe/' // full URL as path
}, function (res) {
    res.on('data', function (data) {
        console.log(data.toString());
    });
});
 
req.end();
```
Program successed.

**Comment by georgiy-abbasov** [comment]
Thanks for details. We need an additional time, to investigate this.
\cc @churkin, please research it.

**Comment by tiagorosendo** [comment]
Any update?

**Comment by AlexanderMoskovkin** [comment]
Not yet. We will comment here when we have results

**Comment by AlexanderMoskovkin** [comment]
We are working on this feature in the context of the https://github.com/DevExpress/testcafe/issues/1206 issue. Please subscribe on it to be notified about our progress.
