### ISSUE TITLE
Test hangs in Firefox and js error appears on the page

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#950]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

If I try to run the example in firefox (`testcafe firefox tests`). Firefox nightly is started and then the cli-tool just "hangs" (nothing is happening) and if I open the dev tools in firefox I see the following error: 

```
TypeError: Not allowed to define a non-configurable property on the WindowProxy object testcafe-core.js:1:7989
TypeError: C.default is undefined[Learn More] testcafe-ui.js:1:16328
TypeError: s.default is undefined[Learn More] testcafe-automation.js:1:1668
TypeError: u.default is undefined[Learn More] testcafe-driver.js:1:25145
TypeError: ClientDriver is not a constructor[Learn More]
```

### What is the expected behavior?

Test should be passed

### Specify your

* operating system: Mac OS X
* testcafe version: 0.9.0

(Created from the [comment](https://github.com/DevExpress/testcafe/issues/930#issuecomment-258772849) by @tjoskar)

**Comment by AlexanderMoskovkin** [comment]
Hi @tjoskar,

Could you please specify your Firefox version? It works well on my side.

**Comment by helen-dikareva** [comment]
Calling `defineProperety` and `defineProperties` for window raise error if `configurable` property is true  `TypeError: Not allowed to define a non-configurable property on the WindowProxy object`
Now it seems like feature https://www.fxsitecompat.com/en-CA/docs/2016/defining-non-configurable-property-on-window-will-throw-currently-only-on-nightly-and-developer-edition/ 
but it may change https://bugzilla.mozilla.org/show_bug.cgi?id=1178638
We will check it later

**Comment by helen-dikareva** [comment]
Now out basic example tests passe on all latest versions of Firefox:

- Last oficial version
- Beta
- Developer Edition
- Nightly
