### ISSUE TITLE
Add 'selectedIndex' to NodeSnapshot

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#951]
### Are you requesting a feature or reporting a bug?

feature

### What is the current behavior?

there is no `selectedIndex` in `NodeSnapchot`, but there is `checked` property.

### What is the expected behavior?

`NodeSnapchot` should contains `selectedIndex` for `select` elements

**Comment by georgiy-abbasov** [comment]
I'm working on this
