### ISSUE TITLE
Simple test hangs up on Angular2 TodoMvc demo

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#953]
### Are you requesting a feature or reporting a bug?
bug

### What is the current behavior?
Test hangs up. Todo list input is not rendered.

### What is the expected behavior?
Test should run.

### How would you reproduce the current behavior (if this is a bug)?
Run provided test.

#### Provide the test code and the tested page URL (if applicable)

Test code

```js
fixture `TODO MVC - angular2`
    .page `http://todomvc.com/examples/angular2`;


test('Add and remove TODO', async t => {
    await t.typeText('.new-todo', 'Write code')
});

```

**Comment by AlexanderMoskovkin** [comment]
Should be fixed in `testcafe-hammerhead`: https://github.com/DevExpress/testcafe-hammerhead/issues/923

**Comment by AlexanderMoskovkin** [comment]
Fixed with https://github.com/DevExpress/testcafe-hammerhead/commit/3d567d11c04da4124e9226d155bf2291a2813bd1
