### ISSUE TITLE
Add NTLM and Basic authentication support

### ISSUE THREAD

**Issue by churkin** [DevExpress/testcafe#955]
\сс @kaihaase-wd
Let's start with the fact that the testсafe has a core - [Hammerhead](https://github.com/DevExpress/testcafe-hammerhead). The Hammerhead already has `Basic` and `NTLM` authentication support. All we need is testcafe API extension:

1. Add a new `httpAuth` fixture directive:

```javascript
fixture('My fixture')
	.page('https://auth-demo.aerobatic.io/protected-standard/')
	.httpAuth({
		username: 'aerobatic',
		password: 'aerobatic'
	}); 
```

which will take the object with four fields:
```javascript	
{
    username: 'username',
    password: 'password',
    domain: 'domain',  // Needed for the NTLM auth
    workstation: 'workstation' // Needed for the NTLM auth
}
```
This can be done here: https://github.com/DevExpress/testcafe/blob/master/src/api/globals/fixture.js (by analogy with the `page` directive)

2. Transmit credentials to the Hammerhead. To do this, there is a virtual `getAuthCredentials` method: https://github.com/DevExpress/testcafe/blob/master/src/test-run/index.js#L107

These data can be received from the our fixture in the `TestRun` ctor:
https://github.com/DevExpress/testcafe/blob/master/src/test-run/index.js#L42

```javascript
this.test.fixture
```

If something is not clear, I will answer any questions.

**Comment by AlexanderMoskovkin** [comment]
done in #1062 
documenation added in #1027
