### ISSUE TITLE
[todomvc] Elements don't appear on the Dojo demo page

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#958]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

Elements don't appeared on the page

### What is the expected behavior?

Elements should be available for actions

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
http://todomvc.com/examples/dojo/
Test code

```js
fixture `TODO MVC - angular2`
    .page `http://todomvc.com/examples/dojo/`;


test('Add and remove TODO', async t => {
    await t
            .typeText(() => document.querySelector('.new-todo') || document.querySelector('#new-todo'), 'Write code')
            .pressKey('enter');
});
```

### Specify your
* testcafe version: 0.10.0

Page is correct if open it with hammerhead-playground

**Comment by helen-dikareva** [comment]
I'm working on this

**Comment by helen-dikareva** [comment]
https://github.com/DevExpress/testcafe-hammerhead/issues/934
