### ISSUE TITLE
Testcafe-browser-provider-saucelabs plugin uses Selenium API internel ?

### ISSUE THREAD

**Issue by s-adachi2016** [DevExpress/testcafe#959]
### Are you requesting a feature or reporting a bug?

feature 

### What is the current behavior?

Testcafe-browser-provider-saucelabs plugin uses Selenium API internel ?

**Comment by AndreyBelym** [comment]
Hello @s-adachi2016, `testcafe-browser-provider-saucelabs` internally uses [wd.js](https://www.npmjs.com/package/wd), that is actually a Node.js Selenium  WebDriver client, but only to do the following:

  1. Start/stop the remote browser

  2. Resize the browser window

  3. Take a screenshot of the browser window

All test-related things are handled by the our [proxy](https://github.com/DevExpress/testcafe-hammerhead), same as for desktop browsers.

**Comment by s-adachi2016** [comment]
Hello AndreyBelym.

Thanks for your comment.
I see your following comment.

>Hello @s-adachi2016, testcafe-browser-provider-saucelabs internally uses wd.js, that is actually a >Node.js Selenium WebDriver client, but only for SauceLabs remote browsers and only in order to do >the following:

>Start/stop the remote browser

>Resize the browser window

>Take a screenshot of the browser window

>All test-related things are handled by the our proxy.
