### ISSUE TITLE
JS-error appears on the Dart demo page

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#964]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

Js-error appears on the page

### What is the expected behavior?

It should not

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
http://todomvc.com/examples/vanilladart/build/web/

Test code

```js
fixture `TODO MVC - angularjs`
    .page `http://todomvc.com/examples/vanilladart/build/web/`;


test('Add and remove TODO', async t => {
    await t.wait(5000);
    await t
            .typeText(() => document.querySelector('.new-todo') || document.querySelector('#new-todo'), 'Write code')
            .pressKey('enter');
});
```

### Specify your
* testcafe version: 0.10.0

It's ok in hammerhead-playground

**Comment by AlexanderMoskovkin** [comment]
I'm working on it

**Comment by georgiy-abbasov** [comment]
I've checked this on the current alpha version - it works properly. I'll close the issue

**Comment by helen-dikareva** [comment]
Yahoo
