### ISSUE TITLE
navigateTo action fails silently with protocols like http*someString*://

### ISSUE THREAD

**Issue by arubtsov** [DevExpress/testcafe#965]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

No errors shown.

### What is the expected behavior?

Show ActionUnsupportedUrlProtocolError.

### How would you reproduce the current behavior (if this is a bug)?

Run provided test.

#### Provide the test code and the tested page URL (if applicable)

Test code

```
fixture `Url validation`
    .page `http://google.com`;

test('Navigate', async t => {
    await t.navigateTo('httpss://ya.ru');
    await t.click('.input__box');
});
```

### Specify your

* operating system: Windows 8.1
* testcafe version: 0.10.0
* node.js version: 6.2.2

**Comment by arubtsov** [comment]
https://github.com/DevExpress/testcafe/blob/acb782f45c886b036a5a0e8ac72c338e9370791a/src/test-run/commands/validations/argument.js#L23
`/^https?$/i` should fix the problem

**Comment by inikulin** [comment]
@arubtsov We allow relative links in `navigateTo`
