### ISSUE TITLE
Ember elements cause Uncaught TypeError

### ISSUE THREAD

**Issue by ClaytonAstrom** [DevExpress/testcafe#966]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

`Uncaught TypeError:  e.getAttribute is not a function`  We're unable to interact with Ember text input fields that are rendered through Ember.  We believe it's due to Ember Objects making their way through TestCafe DOM Elements filtering

### What is the expected behavior?

The test is able to interact with Ember elements

### How would you reproduce the current behavior (if this is a bug)?

Running similar tests against sites that use Ember textfields

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://www.twitch.tv/directory

Test code

```js
"use strict";

fixture("Text Field")
    .page("https://www.twitch.tv/directory");

test("Search for a test", async t => {
    await t.typeText(() => document.querySelector("#gameselector_input"), "Test");
    //I believe no matter what selector/function you put here, the entire page will fail to load

});

```

### Specify your

* operating system:  Windows 7
* testcafe version:  0.10.0
* node.js version:  6.9.1
* Ember versions: 1.13 and 2.4.4

**Comment by georgiy-abbasov** [comment]
Hi @ClaytonAstrom.

Thank you for the report. We have reproduced the problem and we are working on it.

**Comment by georgiy-abbasov** [comment]
Waiting for solving https://github.com/DevExpress/testcafe-hammerhead/issues/942

**Comment by georgiy-abbasov** [comment]
@ClaytonAstrom, we have fixed this in our new version (it's with alpha tag now). Please check whether the fix works with your site. To install fix, run `npm install testcafe@alpha`.

**Comment by ClaytonAstrom** [comment]
Looks good from my end, thanks @georgiy-abbasov !

**Comment by georgiy-abbasov** [comment]
@ClaytonAstrom, it's great news! Can we close the issue ?

**Comment by ClaytonAstrom** [comment]
Done!
