### ISSUE TITLE
Can I set a test as pending?

### ISSUE THREAD

**Issue by Angelmmiguel** [DevExpress/testcafe#968]
### Are you requesting a feature or reporting a bug?

Feature

### What is the current behavior?

I can't write pending tests now. I only can write empty tests and see them as "Success" in the console output.

### What is the expected behavior?

I want to write some empty tests and set them as `Pending`. When I run the testCafe, I want to read "Pending" instead of "Success", like `mocha` with the `xit` function.

### How would you reproduce the current behavior (if this is a bug)?

-

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: -

Test code -

```js
-
```

### Specify your

* operating system: Mac OS
* testcafe version: 0.9.0
* node.js version: v6.8.0

**Comment by inikulin** [comment]
Hi @Angelmmiguel,

We have a `skip` feature planned: https://github.com/DevExpress/testcafe/issues/246
I believe this is pretty much the same thing. Please, let me know if this approach will work for you.

**Comment by inikulin** [comment]
We also have a discussion going in https://github.com/DevExpress/testcafe/issues/802 about test flags/extensions syntax. Feel free to participate or vote for the variants that you like.

**Comment by Angelmmiguel** [comment]
Hello @inikulin,

Yes, it's the same feature. I'm going to watch that issue :)

Thanks for your response!

**Comment by inikulin** [comment]
Okay, I'm closing this one then.

**Comment by Angelmmiguel** [comment]
👍 @inikulin
