### ISSUE TITLE
If a project module contains a re-exported object, the test fails

### ISSUE THREAD

**Issue by sky3d** [DevExpress/testcafe#969]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

```
ERROR Cannot prepare tests due to an error.
SyntaxError: Unexpected token import 
```
### What is the expected behavior?

Test passed

### How would you reproduce the current behavior (if this is a bug)?

Add the re-exporting object to the any project module

`export * from './mod'`

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: -

Test code

_src/consts.js_:
```
export const FOO = 42;
```

_src/module.js_:
```
export * from './consts'
```

_tests/test.js_:
```
import { expect } from 'chai';
import * as app from '../src/module';

fixture('Export Issue')

test('re-export using asterix', async() => {
    expect(app.FOO).to.eql(42);
});
```
#### Related links
http://www.ecma-international.org/ecma-262/6.0/#sec-exports
https://github.com/babel/babel/issues/2877
https://github.com/babel/babel/issues/4751

### Specify your

* operating system: : macOS Sierra v10.12.1
* testcafe version: 0.10.0
* node.js version: v7.0.0

**Comment by inikulin** [comment]
The issue is caused by https://github.com/babel/babel/issues/2877. This ticket contains workaround for the issue, we can try to do it on our side. @AndreyBelym can you try workaround on our side?

**Comment by AndreyBelym** [comment]
Okay, I will try it.

**Comment by AndreyBelym** [comment]
Yep, the workaround works. I am creating the PR.
