### ISSUE TITLE
Add extra distance to scroll automation

### ISSUE THREAD

**Issue by georgiy-abbasov** [DevExpress/testcafe#973]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

TestCafe scrolls to the edge of the element while performing an action

### What is the expected behavior?

It's need to come back to the previous behavior, when we had a small distance between the element's edge and the browser window if there was a space. Some of ASP web controls needs this distance.

### How would you reproduce the current behavior (if this is a bug)?

Run test

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
Page markup:
```html
<body>
<div id='targetRight'
     style="left:2000px; top:2000px; position:absolute; background: #015;    width: 500px;    height: 500px">
    Lower right target
</div>
<div style="left:2700px; top:2700px; position:absolute; background: #000;    width: 50px;    height: 50px">
</div>
</body>
```

Test code

```js
const elementSelector    = Selector(() => document.querySelector('#targetRight'));
const documentSelector   = Selector(() => document.documentElement);


test('Scroll to lower right corner element', async t => {
    await t.click(elementSelector, { offsetX: 500, offsetY: 500 });

    const documentSnapshot = await documentSelector();
    const elementSnapshot  = await elementSelector();

    const rightIndent = documentSnapshot.clientWidth - elementSnapshot.getBoundingClientRectProperty('right');
    const topIndent   = documentSnapshot.clientHeight - elementSnapshot.getBoundingClientRectProperty('bottom');

    expect(rightIndent).to.be.above(0);
    expect(topIndent).to.be.above(0);
});
```

### Specify your

* operating system: Win10
* testcafe version: v0.11.0-alpha
* node.js version: v6.9.1

**Comment by georgiy-abbasov** [comment]
I'm working on this

**Comment by matt-catellier** [comment]
having issue with scrolling to bottom of an element. seems have addressed for extra width, but not adding extra height when scrolling?
