### ISSUE TITLE
Keep browser open after all tests have finished

### ISSUE THREAD

**Issue by ryx** [DevExpress/testcafe#979]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
It is currently impossible to keep the browser open, after all tests have finished. That makes it hard to debug clientside errors inside the tested environment.

### What is the expected behavior?
Testcafe should offer a commandline switch and/or option that causes the browser to stay open after all tests have finished. That would make it easy to use the browser's development tools to recognize errors and check the DOM.

**Comment by AndreyBelym** [comment]
Hello, Rico! Thank you for your feedback. What do you think about [dedicated debugger action](https://github.com/DevExpress/testcafe/issues/918), you can add it as the last expression in the test or as additional pseudo-test, and open devtools for debugging.

**Comment by ryx** [comment]
Hi Andrey, thanks for the quick response. Your proposal looks even more useful than what I had in mind. It has the same effect but allows stepping through the execution of the tests, too. Great idea!

**Comment by AlexanderMoskovkin** [comment]
@ryx While the #918 is not implemented yet you can use a workaround:

```js
import { ClientFunction } from 'testcafe';

fixture `myFixture`
    .page `http://example.com`;

var debug = ClientFunction(() => { debugger; });
    
test('Debug', async t => {
    // some test actions
    await t.wait(2000);
    await debug();
});
```

The test execution will be stopped on `debugger` if developer tools in your browser are opened.

**Comment by AlexanderMoskovkin** [comment]
> Your proposal looks even more useful than what I had in mind. It has the same effect but allows stepping through the execution of the tests, too. Great idea!

So, I close this one in favor of #918
