### ISSUE TITLE
Glob patterns in runner.src method

### ISSUE THREAD

**Issue by kirovboris** [DevExpress/testcafe#980]
### Are you requesting a feature or reporting a bug?

feature

### What is the current behavior?

```runner.src(...)``` method does not support glob patterns in parameters, it's inconsistent with [cli.](https://github.com/DevExpress/testcafe/blob/c4c6989b97e78a82340199daa8bb322f8ebb1775/docs/articles/documentation/using-testcafe/command-line-interface.md#file-pathglob-pattern)

### What is the expected behavior?

I want to have possibility specify global pattern or array of patterns in ```runner.src(...)``` method.
```javascript
runner.src(['C:/project/subProject1/**/*.js', 'C:/project/subProject2/**/*.js']);
```

### Specify your

* operating system: any
* testcafe version: 0.10.0
* node.js version: any

**Comment by miecio1212** [comment]
@inikulin I saw that but I don't see solution here...

**Comment by AlexanderMoskovkin** [comment]
As a workaround you can use the [node-glob](https://github.com/isaacs/node-glob) module to find files by a pattern and pass the `files` array to the `src` method.

**Comment by inikulin** [comment]
@miecio1212 The solution is either to issue a PR, or wait till functionality will be implemented, or use workaround that @AlexanderMoskovkin suggested.
