### ISSUE TITLE
Allow negative integer for offsetX/offsetY options

### ISSUE THREAD

**Issue by romanresh** [DevExpress/testcafe#981]
In my test I need to drag an element (source) to the right side of another element (target). So, I use this code:
`await t.dragToElement(source, target, { offsetX: -10 });`
but this exception occurs: "_The "offsetX" option is expected to be a positive integer, but it was -10._".

Provide the capability to set offsetX/offsetY options with negative number.

**Comment by helen-dikareva** [comment]
`Offset` options define a point inside `source` element. Now we don't have `offset` options to target element, so may be we should implement it.
