### ISSUE TITLE
TestCafe should not emulate touch events for touch monitors

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#984]
### Are you requesting a feature or reporting a bug?

feature

### What is the current behavior?

TestCafe switches in touch mode not only for testing in mobiles and tablets but in laptops and desktops with a monitor that supports touch events. But usually you expect to see mouse behavior when testing on a desktop. 

### What is the expected behavior?

I propose to switch in touch mode in desktops only if the `--touch-mode` flag enabled.

### How would you reproduce the current behavior (if this is a bug)?
The problem is reproduced on the http://demos.devexpress.com/bootstrap/GridView/Overview.aspx page. 
On the original page you can drag a column header with mouse but can't do it via touch events. So it's impossible to test this functionality on desktop with touch-monitor because TestCafe runs tests only with touch mode in this case.

/cc @inikulin @helen-dikareva

**Comment by helen-dikareva** [comment]
After discussion about `touch-mode` option we decided just not to emulate `touch` events for touch monitors (`mouse` events'll be emulated in this case)
