### ISSUE TITLE
Provide the filter(filterFn) method for selectors which return many elements

### ISSUE THREAD

**Issue by romanresh** [DevExpress/testcafe#990]
This issue makes sense as additional functionality for this feature: https://github.com/DevExpress/testcafe/pull/960 . 

I want to filter results of a selector like this one: 
`container.child("div").filter(el => el.nextSiblingElement && el.nextSiblingElement.tagName === "TABLE")`

In my example I tried to find a DIV element before a TABLE element in the hierarchy of BootstrapGridView (it contains a top gridview pager but it doesn't have any attributes like ID or className).

You already has two filter function: withText() and nth(). But I want to perform more advanced filtering.

**Comment by AlexanderMoskovkin** [comment]
I agree, it would be useful
