### ISSUE TITLE
PressKey action works wrong on the Angular2 demo page

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#993]
Test code
```js
 t.navigateTo('http://todomvc.com/examples/angular2');
    await t.typeText('.new-todo, #new-todo', '1')
           .pressKey('enter');

    await t.wait(4000);
```
I expect after `pressKey('enter')` action a new item was added to a list.
But it doesn't happen.

In hammerhead-playground all works good (I checked on https://github.com/DevExpress/testcafe-hammerhead/commit/bb719bd9892ec4781fa9c3c4f9516a930ff59689 commit)

* testcafe version: 0.11.0-alpha
* node.js version: 6.9.1

**Comment by miherlosev** [comment]
Same for http://todomvc.com/examples/backbone_require/

**Comment by georgiy-abbasov** [comment]
I'm working on this

**Comment by georgiy-abbasov** [comment]
We need to dispatch events with `event.key` and `event.keyIdentifier` (Safari) properties when simulating keyboard events. At the current moment we have an empty values for these props - https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/event/simulator.js#L334. 
@miherlosev, i decide to make a dictionary with keyCodes as keys and key\keyIdentifier as value in the context of testcafe-hammerhead.
This will help to solve problem with angular2 and humble.

Another situation with other 3 sites - jquery `keypress` handler executes correctly, but script, which adds note to list, is not loaded at the moment of `t.pressKey` execution. There is same situation on the original resources (without testcafe-hammerhead)
