### ISSUE TITLE
Create Slack Reporter plugin

### ISSUE THREAD

**Issue by ronaldohoch** [DevExpress/testcafe#994]
Is there a Slack Integration?

**Comment by AlexanderMoskovkin** [comment]
Hi @ronaldohoch,

We have not yet but it possible to implement it. What behavior do you expect from Slack Integration?

**Comment by ronaldohoch** [comment]
Hello @AlekseyMartynov.

I've made an example, basically, we can receive the same message we got in command, but the team receive in Slack's channel.

Unfortunately, we don't have colors in slack, but can play with emojis.

![image](https://cloud.githubusercontent.com/assets/2287371/20679709/2edd3c32-b583-11e6-9e7b-6f885fcad562.png)

**Comment by AlexanderMoskovkin** [comment]
@ronaldohoch  It can be implemented as a TestCafe Reporter Plugin. We have a detailed instruction how to create it in our [Reporter Plugin](https://devexpress.github.io/testcafe/documentation/extending-testcafe/reporter-plugin/) article. 
Feel free to create the plugin or if your're busy we'll take care of it.

**Comment by AlexanderMoskovkin** [comment]
It's created: https://github.com/Shafied/testcafe-reporter-slack
Thanks, @Shafied

**Comment by thecodechemist** [comment]
Going off the docs from https://github.com/Shafied/testcafe-reporter-slack, where does one put their slack team-name?
```
TESTCAFE_SLACK_WEBHOOK=https://hooks.slack.com/services/*****
TESTCAFE_SLACK_CHANNEL='#testcafe'
TESTCAFE_SLACK_USERNAME=testcafebot
```
