### ISSUE TITLE
Add getOuterHTML() method for DomNodeSnapshot

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#995]
User story:
I get a deep property of big pageObject.
For example, `pageObject.AppContainer.FilterPanel.Filters.All`
For debug purposes I want to get `outerHtml` of the selected html elements on every step.

* testcafe version: 0.11.0-alpha

**Comment by miherlosev** [comment]
And `getInnerHtml` method too.
It is usefull for checking rendering that change according the user input. 
For example for WYSIWYG and markdown editors.

**Comment by inikulin** [comment]
Can be implemented with custom methods
